### ISSUE TITLE
Build Encryption logic for files being generated in destinations

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#10009]
Part of #7555
Tech spec : https://docs.google.com/document/d/18_Ezbl7Z1aSpHBdFFUy6BHMlDfYTktI4Yp8h2DbX4RE/edit#heading=h.fa72b39y2m99
As part of this issue we should introduce logic to encrypt files that are being generated in destinations using external loading method. We should make sure we use ephemeral keys.

As part of this ticket we need to also decide how encryption interacts with the option in the Redshift destination which allows the user to keep the staging data.

**Comment by edgao** [comment]
Done in https://github.com/airbytehq/airbyte/pull/12452, also added to destination-snowflake
