### ISSUE TITLE
Source Google Analytics: New property with GA4 support

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#10007]
According to #6326 we need a `property id` to get GAv4 reports. 

What is property - https://support.google.com/adsense/answer/6090824?hl=en

How to determine a Google Analytics 4 property id:

1. Visit Google Analytics at https://analytics.google.com/.
2. Select Admin.
3. Select the Property.
4. Select Property Settings.

Now we have only one website in google analytics with UA tag.  But if we change it to GA4 tag (version):
1. We can test only with one type of config.
2.  Could not support all versions without switching.

So, according to the above, we need websites with different versions in google analytics.

Slack convo: https://airbytehq.slack.com/archives/C02UF50V9HA/p1643625530709939

**Comment by sherifnada** [comment]
This has been completed. We have a tag live on Airbyte.com and can start looking into GA v4 support.

**Comment by sherifnada** [comment]
measurement ID is G-HDBMVFQGBH
