### ISSUE TITLE
Source Google Analytics: Add Ecommerce Data stream

### ISSUE THREAD

**Issue by MPrejean** [airbytehq/airbyte#10049]
## Tell us about the problem you're trying to solve
Only native Google Analytics's data is available with Airbyte. It is missing Ecommerce Data, which is a big part of Google Analytics.

## Describe the solution you’d like
Having a table in BigQuery that have Ecommerce Data (dimensions and metrics). The data schema can be found [here](https://ga-dev-tools.web.app/dimensions-metrics-explorer/ecommerce#Ecommerce)

## Describe the alternative you’ve considered or used
Creating a custom report but it is time consuming and there are limitations of how many dimensions you can load

**Comment by adinamarca** [comment]
> ## Tell us about the problem you're trying to solve
> Only native Google Analytics's data is available with Airbyte. It is missing Ecommerce Data, which is a big part of Google Analytics.
> 
> ## Describe the solution you’d like
> Having a table in BigQuery that have Ecommerce Data (dimensions and metrics). The data schema can be found [here](https://ga-dev-tools.web.app/dimensions-metrics-explorer/ecommerce#Ecommerce)
> 
> ## Describe the alternative you’ve considered or used
> Creating a custom report but it is time consuming and there are limitations of how many dimensions you can load

Hi!

Did you extract the data of Ecommerce table somehow?

Thanks

**Comment by geoHeil** [comment]
Plus 1  - I would also love to see this feature.

**Comment by davydov-d** [comment]
Closing this issue since the Google Analytics v4 is going to be deprecated soon in favour of Google Analytics Data API.
