### ISSUE TITLE
Source Snapchat Marketing: Add account, campaign and ads stats 

### ISSUE THREAD

**Issue by KhristinaR** [airbytehq/airbyte#10040]
## Summary
- [ ] Update Snapchat Marketing connector

Currently Snapchat Marketing connector loads only Account, Ad, Campaign etc. metadata,
It doesn't have any streams with Campaign, Ads stats data (like spend, impressions). https://marketingapi.snapchat.com/docs/#get-ad-account-stats 

It is the most important information for this connector. So there is probably not much practical use in current streams as they load only metadata. 
We can get campaign and account names, but no stats for them like for Facebook Ads connector, for example.

**Comment by lluisgassovillarejo** [comment]
This is a critical feature since there isn't much use for Snapchat data without it. Are there any plans to add the stats data soon?

**Comment by sherifnada** [comment]
hi everyone, we plan to add this in the coming 4-6 weeks, and are happy to accept a contribution in the meantime if someone beats us to it!
