### ISSUE TITLE
CI Sandbox Salesforce Marketingcloud

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#10054]
## Tell us about the problem you're trying to solve
We need CI credentials for Salesforce Marketingcloudfor new PR https://github.com/airbytehq/airbyte/pull/10026

**Comment by harshithmullapudi** [comment]
@karinakuz can you help to get credentials for this

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, I have a call with SFMC on Thursday, they will give us a sandbox. I hope to resolve the issue with creds this week.

**Comment by harshithmullapudi** [comment]
Hurray thanks a lot 🙏🏻

**Comment by igrankova** [comment]
@harshithmullapudi, can you specify what streams we are going to test? It's needed for the sandbox setup.

**Comment by igrankova** [comment]
Now Andy is negotiating with SFMC according the discount for a sandbox account, still in progress.

**Comment by misteryeo** [comment]
Assigning to @harshithmullapudi to close out after his review.

**Comment by igrankova** [comment]
@harshithmullapudi 
hi! can we close this issue?

**Comment by igrankova** [comment]
@harshithmullapudi Do you still have an access to the SFMC account? We received an email:
![image](https://user-images.githubusercontent.com/87977540/188508342-0af1e300-9817-46de-8651-3733f6784ab7.png)
I've tried to login, but the Organization restore code wasn't accepted, so now I can't pass the authentication.
Can you login and update the FTP password or maybe you can share the new Organization restore code with me if it was changed?
cc @YowanR
