### ISSUE TITLE
Research Smartsheets source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#10074]
## Complete the following exercise for Smartsheets source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:
https://docs.google.com/document/d/1gWztezmxeXl2JX63iNbl-XqJj8sPGfidZm3n8mx9j78/edit?usp=sharing

[EPIC] GA & Beta Connector Research #9675

**Comment by jmcbroom** [comment]
I think the current connector is broken, it `zip`s each row's values with the columns, assuming they are in the same order, but they are not.

**Comment by igrankova** [comment]
Hi, Andy @misteryeo 
Can you help with this issue? https://github.com/airbytehq/airbyte/issues/10074#issuecomment-1033063176

**Comment by misteryeo** [comment]
@jmcbroom can you create a new Github issue to report this bug so we can prioritize accordingly? Thank you!

**Comment by igrankova** [comment]
@misteryeo, the research is done.

**Comment by jmcbroom** [comment]
> @jmcbroom can you create a new Github issue to report this bug so we can prioritize accordingly? Thank you!

Hey, I checked and it looks like it's already here: https://github.com/airbytehq/airbyte/issues/8099 !
