### ISSUE TITLE
MSSQL discovers tables from outside the schema specified by the user

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1008]
Context: https://airbytehq.slack.com/archives/C019WJFR1JT/p1605673969049400

Two issues:
1. The MSSQL source seems to be discovering tables not from the schema specified by the user. Plus, when those tables show up in the UI, they do not have any columns listed underneath them. 
1. The user is not able to un-select these tables when choosing the sync schema. 
 
Airbyte version is v0.5.3

**Comment by cgardens** [comment]
i think this is fixed now with the new jdbc source.
