### ISSUE TITLE
Research Asana source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#10099]
## Complete the following exercise for Asana source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:
https://docs.google.com/document/d/1lClC4dIptzvYLvSsg1ZhuboFG-vKviHth1_mlFZV1Uk/edit?usp=sharing

[EPIC] GA & Beta Connector Research #9675

**Comment by zbrak** [comment]
Heya @igrankova  was reviewing this issue - at Pliancy we actually have a really large use case for this right now! Would love to chat if you're willing?

**Comment by igrankova** [comment]
Hi, @zbrak, I'm currently unavailable due to the situation in Ukraine, I hope to start working next week. Would contact you soon.

**Comment by igrankova** [comment]
@zbrak I'm ready to discuss the use case for Asana. Should I do the research first?

**Comment by igrankova** [comment]
@misteryeo, @zbrak I've finished Asana research, please find a link to the doc in the issue body.

**Comment by YowanR** [comment]
@igrankova This issue looks complete so can you go ahead and close it off? Thanks!

**Comment by igrankova** [comment]
@YowanR, added Permissions chapter. Thanks!
