### ISSUE TITLE
Expose partial success and failure origin in the UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#10119]
## Tell us about the problem you're trying to solve
* Failure Origin: Our oncall process is severely hampered by our ability to quickly determine if the origin of a failure was a the source, destination or platform. We should add this information in to the UI
* Records committed: We now track the number of records actually _committed_ to the destination. We should expose that in the UI.
* Partial Success: is not clearly explained in the UI. We now expose enough information for the UI to say that a job was a partial success.

This issue is a subset of the work described in a bigger addition to the UI describe [here](https://github.com/airbytehq/airbyte/issues/10110). We are opting to do this issue first because it is very high value and are relatively small changes that we can do while send the rest through the full ui design process.

Mocks ups:

failure origin and records committed
![Screen Shot 2022-02-04 at 3 10 25 PM](https://user-images.githubusercontent.com/9092207/152615711-0860da65-77d5-4631-b949-6680b4f376cb.png)

partial success
![Screen Shot 2022-02-04 at 3 10 00 PM](https://user-images.githubusercontent.com/9092207/152615750-0b064046-4ea6-4d34-8939-1596d8c850f8.png)

(please tweak these to look sensible. i.e. use whatever tooltip we already use in the ui)

**Comment by cgardens** [comment]
@pmossman @jrhizor @timroes heads up.

**Comment by cgardens** [comment]
@harshithmullapudi would you be down to work on these UI changes next week?

**Comment by jrhizor** [comment]
Should partial success be yellow with ⚠️ ?

**Comment by cgardens** [comment]
Sure. Maybe use the same yellow circle and exclamation mark that we use for a connector that has never run yet?

**Comment by harshithmullapudi** [comment]
Sure. Will pick.

**Comment by harshithmullapudi** [comment]
@cgardens we can close this right?
