### ISSUE TITLE
add comprehensive labeling on k8s

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10126]
When managing connections at scale, we end up needing to look at pods that have run in different contexts. Without thorough labelling, it's difficult to quickly summarize pod states from `kubectl`. Outside of debugging, this would help us change the orchestrator pod killing for previous attempts to instead kill every non-terminal pod for the connection, which would be much cleaner.

For all container orchestrator pods we should label:
- connection id
- source definition id
- source version
- destination definition id
- destination version
- workspace id

For source/destination pods we'd want the same, just with either source or destination information.

The implementation is a little more involved than it initially seems. We need to modify various Temporal activity inputs to allow passing in all of these ids, which means likely means adding a new aggregate input object and bumping the workflow version.

**Comment by jrhizor** [comment]
Connection id has been added. I think the others are lower priority so moving this down.

**Comment by cpdeethree** [comment]
Dupe https://github.com/airbytehq/airbyte-platform-internal/issues/3588
