### ISSUE TITLE
Shopify Connector - missing FulfillmentOrders stream

### ISSUE THREAD

**Issue by yuhuishi-convect** [airbytehq/airbyte#10137]
## Environment
- **Airbyte version**:  0.35.15-alpha
- **OS Version / Instance**: Ubuntu 20.04 on AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.30
- **Destination Connector and version**: NA
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
`FulfillmentOrders` stream is missing from Shopify connector schema from UI

(There is only `Fulfillment` stream)
![image](https://user-images.githubusercontent.com/74702693/152713944-019b9740-68b6-4e3d-bebb-c988f3e52633.png)

## Expected Behavior
From the schemas setting, there should one `FulfillmentOrder` stream

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-shopify/source_shopify/schemas/fulfillment_orders.json

## Logs
NA

## Steps to Reproduce
1. Go to airbyte UI
2. Set up a new Shopify connector
3. Set up a new connection using the Shopify connector
4. From the schemas selection UI, the `FulfillmentOrders` stream is missing

## Are you willing to submit a PR?
Yes. But need to know the root cause.

**Comment by arsenlosenko** [comment]
the stream in question was made in scope of this PR:
https://github.com/airbytehq/airbyte/pull/7107
I have checked locally with the latest version of Airbyte OSS and the latest version of this Shopify connector, this stream can be enabled and sync with it works as expected.
