### ISSUE TITLE
Add Freshdesk source integration

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1014]
## Tell us about the new integration you’d like to have
I'd like to be able to sync data from Freshdesk via Airbyte. The entities I'd like to sync are: 

* Agents
* Contacts
* Companies
* Groups
* Products
* Roles
* Skills
* Surveys
* Tickets
* Time Entries

API docs: https://developers.freshdesk.com/api/

**Comment by rubenssoto** [comment]
Hello,

I think, important information about freshdesk Agents endpoint, there are two endpoints, one to list all agents and one to get each agent info. In my company agent roles information is important, so this info is only available on the second endpoint.

Thank you.

**Comment by michel-tricot** [comment]
Thanks @rubenssoto 
@sherifnada is it just a matter of adding a new entity?

**Comment by sherifnada** [comment]
@rubenssoto the Freshdesk API endpoints [view agent](https://developers.freshdesk.com/api/#view_agent)  and [list agents](https://developers.freshdesk.com/api/#list_all_agents) return the same entity (agent), but the former is a single agent and the latter is a list of the entities. Both contain the roleIDs for each agent. The Freshdesk connector syncs Roles and Agents via their list endpoints. Would this fulfill your use case? I believe based on your description and the API docs it should, but please let me know if this is not the case.
