### ISSUE TITLE
[EPIC] Speed up check connection time in Q1 GA connectors

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#10154]
Relates to: https://github.com/airbytehq/airbyte/issues/10149

## Tell us about the problem you're trying to solve
As part of the [investigation into speeding up check connection](https://github.com/airbytehq/airbyte/issues/10149), our testing found that the check connection method (and discover schema method) for some connectors is slow (even after removing platform overhead)

Ideally our 99 percentile for performing check connection is < 10 seconds. Given that the Kube overhead is ~5 seconds, we want the connector to finish in something like 3 seconds. This gives us 2 seconds of buffer to play with.

Results (does not include platform overhead):
* destination postgres - ~ 4 seconds (I was using this as a generic RDS connector)
* destination snowflake - ~ 14 seconds
* source salesforce - ~ 3 seconds

The connectors we should focus on since they are for GA:
* source salesforce
* source facebook
* destination snowflake
* destination bigquery

## Acceptance Criteria for this Epic:
- [ ] #10376
- [x] #10377
- [x] #10405
- [x] #10406 
- [ ] Add the <5 second connection check as a GA criterion (assigned to @sherifnada )

If it is necessary to remove some thoroughness in the check connection (i.e: do fewer operations and get a less granular failure message) then reach out to @misteryeo about it. 

@sherifnada heads up
@davinchia created this issue so connectors team could start looking into it.

**Comment by sherifnada** [comment]
discussed offline with Charles -- the current focus will be on sources which suffer most severely from this issue. The goal for EOQ1 is below 5 seconds for a connection check. 3 or less is perfect but not worth spending much time on.

**Comment by sherifnada** [comment]
cc @misteryeo 

Should we make the GA criteria for check connection be that it always takes <5 seconds? I don't see a reason we can't do this today

**Comment by misteryeo** [comment]
Assuming there is no technical limitation, this sounds great to me!

**Comment by davinchia** [comment]
Sherif, can we try to shoot for <=3 seconds to begin and reevaluate after some time to see if that's too ambitious a time? This gives us ~2 second of buffer for the odd case where things are slow.

**Comment by davinchia** [comment]
Let's assume we have a total time of 10 seconds. The 95 percentile for starting up the Kube pods is ~5 seconds. That gives us another 5 seconds for the pod to execute. If we can keep the execution to 3 seconds, we have a 2 second buffer for other edge cases.

**Comment by sherifnada** [comment]
Ok - I'll pass on the following guidance: "get check connection to 3 seconds is the goal, but if it's intractable then 5 seconds is acceptable". I just want to have something that prevents rabbit holding on this given that 10 to 12 has diminishing marginal return.

**Comment by davinchia** [comment]
Sounds good to start. Thanks.
