### ISSUE TITLE
Salesforce Source: Support "Replicate Incremental Deletes"

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10155]
## Tell us about the problem you're trying to solve
Support replicating incremental deletes to reach parity for GA connector as per [research](https://docs.google.com/document/d/1Z5wue_M3wKkWl667-aHLmtJd6IyyVNnoooUZzA0ucfA/edit#heading=h.kyp5r0t74f7a).

Example ticket: https://github.com/airbytehq/airbyte/issues/9842

**Comment by annalvova05** [comment]
@misteryeo @sherifnada 
It is possible to add a param in the SalesForce query and receive deleted records. Now, we use two endpoints in the SalesForce sync: [REST API](https://developer.salesforce.com/docs/atlas.en-us.232.0.api_rest.meta/api_rest/dome_queryall.htm) and [BulkAPI](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_get_all_jobs.htm).
In terms of implementation:
- add optional field in spec (like `include_deleted` - default=`False`);
- add `_ab_deleted` field to the stream schemas;
- receive deleted records and write them with PK, `_ab_deleted=True`, and empty data.

Do we need also to add the `_ab_deleted` field to the schema with the default `False` value?

**Comment by sherifnada** [comment]
@annalvova05  the [example docs](https://developer.salesforce.com/docs/atlas.en-us.232.0.api_rest.meta/api_rest/dome_queryall.htm) you linked contain a query like this:
```
SELECT+Name+from+Merchandise__c+WHERE+isDeleted+=+TRUE
```

If we don’t include this WHERE clause, doesn’t that mean we get records where isDeleted is either true or false? meaning we get all records? 

If yes, then is there an action item required here?

**Comment by annalvova05** [comment]
@sherifnada [REST API](https://developer.salesforce.com/docs/atlas.en-us.232.0.api_rest.meta/api_rest/dome_queryall.htm) and [BulkAPI](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/query_get_all_jobs.htm) include deleted records during the sync. If the stream supports deleted records, we have the `IsDeleted` field in the schema with both deleted and not records.

Do we need also to add `_ab_deleted` field and all other values make `null`?

**Comment by sherifnada** [comment]
@annalvova05 we do not need to add the _ab_deleted field or nullify other fields in this case. That functionality is more suitable for CDC databases where all updates to a record are replicated. But in this case a user could lose information e.g

1. Record(name=sherif, deleted=false) is created
2. Airbyte sync runs
3. Name is updated to sherif2 in sales force 
4. record is deleted
5. Sync runs

In this case the user would never know that the name was updated to sherif2 

So I think until we implement salesforce CDC we should maintain the current behavior. Also we should include a note in the docs which clarifies this behavior: specifically that we replicate deleted records and that they can be detected using the isDeleted field. 

@misteryeo pls chime in if you think this is not the right behavior

**Comment by annalvova05** [comment]
@sherifnada 
When the record was created, then deleted, we cannot update it. SF returns an error `ENTITY_IS_DELETED`. We retrieve the record during the first sync, and then after deleting it in incremental sync.
In your described scenario after the second sync, we retrieve the deleted record with updated `name=sherif2` and `IsDeleted=True`.

I will add tests for these cases.
