### ISSUE TITLE
[EPIC] Update connectors' code quality to make it pass all the checks

### ISSUE THREAD

**Issue by sergei-solonitcyn** [airbytehq/airbyte#10174]
We now have a configured tool to run some automatic checks of code quality. It can be run with `invoke` command from `airbyte-integrations/connectors/` directory. See its inline help.
The purpose of this epic is to have all the checks to be passed for every connector. So `invoke all-checks -c <connector_name>` has to return zero exit code.
In case we found any difference between configurations of this tool and *pre_commit*, that has to be solved before.

**Subtasks:**
- [x] #10192 
- [ ] #10423
- [ ] #10424
- [ ] #10425
- [ ] #10426
- [ ] #10427
- [ ] #10428
- [ ] #10429
- [ ] #10431
- [ ] #10432
- [ ] #10433
- [ ] #10434
- [ ] #10435
- [ ] #10436
- [ ] #10437
- [ ] #10438
- [ ] #10440
- [ ] #10441
- [ ] #10442

**Comment by noahkawasakigoogle** [comment]
When you say "checks of code quality" do you mean linters?

**Comment by sergei-solonitcyn** [comment]
Yes, linters, tests and test coverage
