### ISSUE TITLE
hubspot <> bigquery: incremental dedup normalization issues 

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#10179]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: linux
- **Deployment**: Kubernetes
- **Source Connector and version**: Hubspot 0.1.38
- **Destination Connector and version**: Bigquery 0.6.1
- **Severity**:  High 
- **Step where error happened**: Sync job

## Current Behavior
We're syncing companies stream from hubspot to bigquery. hubspot has around 370k entries and it takes around 1h to load data.

Issues:
1. Sync failed at the end of normalization step. The root cause appears to be `Caused by: io.fabric8.kubernetes.client.KubernetesClientException: too old resource version`
2. From logs it appears the last dbt step was not completed (?), namely `2022-02-15 07:42:09 normalization > 07:42:09 | 4 of 4 START incremental model airbyte.hubspot_companies_properties` but all data looks to be synced on bigquery side.
3. Attempt no 2. was initiated although all data was already synced to bigquery (only normalization failed). Cancelled this sync.

Full logs:  [logs-308.txt](https://github.com/airbytehq/airbyte/files/8067390/logs-308.txt)

Then ran incremental update and it finished with `332 records` updated. At this point _hubspot_companies_ and _hubspot_companies_properties_ tables start to diverge. one would expect there to be identical tables in size but they no longer are and there is no way to get 1-to-1 mapping between them.

Incremental logs: [logs-309.txt](https://github.com/airbytehq/airbyte/files/8067453/logs-309.txt)

**Comment by harshithmullapudi** [comment]
I think the cause of the kube failure is that normalisation has failed and the was asked to exit the pod. And yeah when normalisation fails the sync is considered as failure and new attempt would show up so, that seems fine to me.

Can you create a fresh connection between the source and destination and share the logs here?

**Comment by TSkrebe** [comment]
@harshithmullapudi [logs-308.txt](https://github.com/airbytehq/airbyte/files/8067390/logs-308.txt) are from fresh connection.

**Comment by harshithmullapudi** [comment]
You have configured incremental sync?

**Comment by marcosmarxm** [comment]
@TSkrebe can you test with latest vesion of both connectors? I'm closing due inactivity. Please open a new issue if the problem persist.
