### ISSUE TITLE
Snowflake Destination Unit Tests 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#10188]
The current Sonarqube report is very poor for Snowflake Destination. This is because Sonarqube doesnt acknowledge E2E acceptance tests. We should write unit tests to make the metrics better
Ref : https://github.com/airbytehq/airbyte/pull/9982#commitcomment-65818678

**Comment by sashaNeshcheret** [comment]
@misteryeo the issue was opened based on sonar report, but currently sonar is not working, so for closing issue i used intellij idea report and added screen. But seems we need issue to investigate sonar for java.

**Comment by misteryeo** [comment]
@sherifnada would be better to make the call in this instance so tagging him in :)
