### ISSUE TITLE
Write Tech Spec: alerting on platform usage

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#10182]
## Tell us about the problem you're trying to solve
SImilar to https://github.com/airbytehq/airbyte-cloud/issues/907
but also focused from user's point of view

## Describe the solution you’d like
How to detect repeat failure or bad configurations of connectors

tech spec draft https://docs.google.com/document/d/1eWDiy8cj7VvXyN_oKrmJAaEJ3-M9LqjX9JlDYyeeHFE/edit#

**Comment by sherifnada** [comment]
highlights from offline discussion with chris: 
* short-term tech spec has been ratified
* medium/long-term solutions will be figured out by alyssa
* closing this ticket and will create any needed issues for follow-up work
