### ISSUE TITLE
Source Marketo: leads stream always fails

### ISSUE THREAD

**Issue by KhristinaR** [airbytehq/airbyte#10191]
## Environment
- **Airbyte version**:  0.35.17-alpha
- **OS Version / Instance**: n1-standard-2
- **Deployment**: GCP (Compute Engine)
- **Source Connector and version**: Marketo 0.1.3
- **Destination Connector and version**: BigQuery 0.6.7
- **Severity**: Critical
- **Step where error happened**: Sync job 

## Current Behavior
 The ''leads'' stream fails every time in 30 sec. There are no issues with activities stream or with programs stream (a separate pipeline). The expected output is 333000 rows. No issues with API limits as Matillion can load the same data from the same API endpoints. 
## Expected Behavior
successful synch

## Logs
The logs are in the attachment.

## Steps to Reproduce

[logs-365.txt](https://github.com/airbytehq/airbyte/files/8026249/logs-365.txt)

**Comment by CyprienBarbault** [comment]
We used to have this issue but it doesn't happen anymore after updating Airbyte to v0.37.0-alpha

**Comment by davydov-d** [comment]
this issue has been temporary resolved, a long term fix should be implemented in https://github.com/airbytehq/airbyte/issues/14149
