### ISSUE TITLE
Source Salesforce: Update API version to 53 or above

### ISSUE THREAD

**Issue by da-firebolt** [airbytehq/airbyte#10207]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Hi team, 

We're trying to see some new Salesforce standard objects but they're not showing up in schema during Airbyte connection creation because they require Salesforce API version to be v53 or above and the following link shows current version to be v52. Do you have any ETA when we can expect this version to be bumped to v53 at least?

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py#L175

![image](https://user-images.githubusercontent.com/89909616/153152824-04793e17-3b48-4af7-89af-b8b2e83984a9.png)
## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by da-firebolt** [comment]
Hi team, any update on the ETA for this issue?

**Comment by marcosmarxm** [comment]
@da-firebolt the connectors stills use version v52, do you have any issue with that?

**Comment by amit-firebolt** [comment]
Chiming in for @da-firebolt, there are standard objects in Salesforce that are supported from v53 and above. That means any connector with a version below that, we can't see these objects therefore the issue still stands.

**Comment by roman-yermilov-gl** [comment]
Updated to v53.0: https://github.com/airbytehq/airbyte/pull/25352
