### ISSUE TITLE
Check Connection should have it's own flavor of KubePodProcess.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#10208]
## Tell us about the problem you're trying to solve
We want to be able to specify a different status check interval and a node selector for the Check Connection process.

This is follow up to #9303 and the application side of #10205.

## Describe the solution you’d like
Make it so it is possible to configure the above at the KubePodProcess level for the Check connection operation.

Ideally we also set the code up so it's easy to add other job-specific KubePodProcess in the future.

Some initial discussion: https://docs.google.com/document/d/1w9UBa1xTQcpJYLjmWi8zMLYN3vZ6DhDVyTxFIM5hgxk/edit?usp=sharing.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by pmossman** [comment]
This is now released on OSS and Cloud
