### ISSUE TITLE
Ignore Github streams that do not exist for a repo

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#10206]
## Tell us about the problem you're trying to solve
Some of the Github streams do not exist for certain repos. For example, a repo may not have the `projects` stream. Currently, the Github connector throws out the exception from the API directly (e.g. `404 Client Error: Not Found for url`). However, this behavior is too stringent.

## Describe the solution you’d like
Simply ignore the errors from streams that do not exist for a repo. This connector should adopt the philosophy of the S3 destination: “just hoard, don’t judge”.

## Describe the alternative you’ve considered or used
N/A

## Additional context
https://github.com/airbytehq/oncall/issues/130

**Comment by sherifnada** [comment]
cc @misteryeo I think this makes a lot of sense

**Comment by midavadim** [comment]
Github connector correctly handles 404 error for 'project' streams since 12.2022
