### ISSUE TITLE
`all-checks` task for `invoke` doesn't run all tasks

### ISSUE THREAD

**Issue by Zirochkaa** [airbytehq/airbyte#10237]
## Current Behavior
When running `invoke all-checks -c chargebee` (or any other connector) only `black` check is being run.

## Expected Behavior
When running `invoke all-checks -c chargebee` (or any other connector) following checks should be run one by one with default parameters: black, flake, isort, mypy, test, coverage.

## Steps to Reproduce
1. Run `invoke all-checks -c chargebee`.
2. See that only `black` was run.

## Are you willing to submit a PR?
Yes..

**Comment by sergei-solonitcyn** [comment]
Already have a PR to solve that:
https://github.com/airbytehq/airbyte/pull/9707
