### ISSUE TITLE
Source Intercom: remove `setting state of...` logs from intercom sync

### ISSUE THREAD

**Issue by TylerButh** [airbytehq/airbyte#10250]
## Tell us about the problem you're trying to solve
When syncing Intercom data after each Records read I am seeing perhaps thousands of `Setting state of ... stream to` log messages. I'm not sure if those are logs from a separate task running simultaneously or if they are logs of the current task, but they flood my log file so that I can't download the logs because the file is too large or it makes debugging errors extremely difficult as I'm going through hundreds of thousands of lines of logs, the majority of which are these messages.

![image](https://user-images.githubusercontent.com/5452396/153488132-5cdc7873-e22a-4d00-8531-909786cebd9c.png)

## Describe the solution you’d like
It would be nice to either remove this log entry all together, it's not personally useful to me. Or perhaps have a single log entry for "Setting the state of 321 rows of company_segments stream to..." or maybe group the log entries by the `updated_at` time. If you notice from the screenshot they are all duplicate entries of the same time. Just grouping them by the time would eliminate thousands of entries.

## Are you willing to submit a PR?
Not at the moment.

**Comment by misteryeo** [comment]
Assignee should take a look at this and validate whether there's value in retaining individual log entries for `setting state of...` and determine if there's a cleaner UX we can implement here.

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/9746
