### ISSUE TITLE
[EPIC] Implement QuickBooks requirements to list App on a Marketplace

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#10264]
## Tell us about the problem you're trying to solve
We have submitted the Public App on the QuickBooks Marketplace and we need to update our connector implementation according to the requirements for the QuickBooks support.

## Describe the solution you’d like
1. Change naming:
Current name: Quickbooks 
Should be:  **QuickBooks**
We need to update naming to correct one in all places where it's mentioned in the connector and docs and logos.
     - [x] #10265 
     - [x] #10344
2. The **Sign in with Intuit** button must be shown to the users in our application prior to the OAuth connection.
     - [x] #10266   
3. Our application must have provision of In-App disconnect feature. Clicking on disconnect must call QuickBooks Revoke Access API which terminates OAuth connection with QuickBooks Online company.
     - [x] #10274

**Comment by igrankova** [comment]
@misteryeo 
Hi, Andy! We have a bug on QuickBooks source, our docs link doesn't work due to the domain change from .io to .com: #10412
Can you assign this ticket to Artem Astapenko to fix this problem or maybe there's someone else who can help?

**Comment by misteryeo** [comment]
Let's mark this as blocked for now - I've highlighted with the frontend team :)
