### ISSUE TITLE
Source Woocommerce: connector doesn't use the `start_date` when using Incremental sync mode

### ISSUE THREAD

**Issue by sivakurella** [airbytehq/airbyte#10273]
## Environment
- **Airbyte version**:  example is 0.35.5-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: woocommerce 0.1.0-rc1
- **Destination Connector and version**: redshift 0.3.5
- **Severity**: Medium
- **Step where error happened**: Sync job 

## Current Behavior
source_woocommerce source connector does not use the start_date when using Incremental sync mode. When created a connection and syncing the data to the Redshift the orders source stream does not start from start_date mentioned in the source connection. I don't think the connector implemented the start_date correctly when compared to stripe connector. In the logs you can see that the sync job start from 2019-08-23 instead of the 2022-01-01(start_date) as mentioned in the source connector.

## Expected Behavior
Incremental Append Sync Job should use the start_date from the source connection info and the start from that date instead of loading the entire data.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2022-02-11 07:08:28 destination > 2022-02-11 07:08:28 INFO i.a.i.d.b.BufferedStreamConsumer(startTracked):125 - {} - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started.
2022-02-11 07:08:28 source > Setting state of orders stream to {'date_modified': '2019-08-23T00:05:01'}
2022-02-11 07:08:31 source > Setting state of orders stream to {'date_modified': '2019-08-23T00:07:29'}

```

</details>

## Steps to Reproduce
1. Download the new woocommerce connector
2. sync it to any database or local json
3. run the sync job and you can see the date_modified not using the start_date

## Are you willing to submit a PR?

I would love to contribute.

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/19903
