### ISSUE TITLE
CI Sandbox for Orb source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#10287]
## Tell us about the problem you're trying to solve
Need credentials to test community contribution adding Orb connector.

PR implementing the connector: https://github.com/airbytehq/airbyte/pull/9985

**Comment by lmossman** [comment]
@marcosmarxm I have saved the Orb integration test credentials to Lastpass, in a secure note titled `source orb test creds` in the `shared-integration-tests` folder
