### ISSUE TITLE
CI Sandbox for Talkdesk Explore

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#10285]
## Tell us about the problem you're trying to solve
Need credentials to test community contribution adding new connector Talkdesk Explore: https://github.com/airbytehq/airbyte/pull/10164

**Comment by igrankova** [comment]
Subscribed to the Partner program, asked for the sandbox - no answer.
Case to support: https://support.talkdesk.com/hc/en-us/requests/386773

**Comment by sh4sh** [comment]
Hey, is there any update on this? I've submitted some changes for the Talkdesk source connector and it would be great if we could test it.

**Comment by igrankova** [comment]
@sh4sh,
Got an answer finally! We have to fill several forms for partnership program. I'm starting it today and will keep you in the loop.

**Comment by sh4sh** [comment]
Hey @igrankova, any update? Hoping to merge some changes to this connector 🙂

**Comment by YowanR** [comment]
WIP. I believe @igrankova had a call with TalkDesk but we don't have the account yet, unfortunately.

**Comment by igrankova** [comment]
hey @sh4sh, we are still in progress. We are now applying to the partner program and there's a possibility to have a sandbox account. Hope to have some new next week.

**Comment by igrankova** [comment]
@sh4sh, hi!
We are stuck with the sandbox, no answer again. If you are a Talkdesk customer, could you help us and contact your Talkdesk sales manager and ask them about possibility to provide us a sandbox? Maybe they could agree to contact me (iryna.grankova@airbyte.io). Usually it works very good if we have a recommendation from the mutual customer.

**Comment by igrankova** [comment]
@sh4sh thank you very much, hope they could help us.

**Comment by igrankova** [comment]
We are still blocked here. Waiting for reply from the Talkdesk team to the mutual customers sandbox request for Airbyte.

**Comment by igrankova** [comment]
We are passing the partner onboarding steps:
1.        Partner Application 
2.        NDA
3.        Questionnaire 
the next one should be the sandbox receiving. Waiting for the reply from the partner team.

**Comment by alejobs** [comment]
Hi @igrankova,

Any news on this?

Thanks.

**Comment by igrankova** [comment]
Hi, @alejobs, no answer for my last email a month ago. I'll send one more.

**Comment by alejobs** [comment]
Hi @igrankova ,

Any news on this? Can I help with anything?

Thanks.

**Comment by igrankova** [comment]
Hi, @alejobs, nothing :( 
My last email also left without an answer.

**Comment by alejobs** [comment]
Hi @igrankova ,

Happy new year! Any news about this? Can I help anyway?

Thanks

**Comment by igrankova** [comment]
@alejobs hi! Happy new year to you too
I was on vacation. I'm writing a new email and put the Director  - Sales Operations in cc. Hope it works.

**Comment by igrankova** [comment]
@alejobs I'm wondering how you can help.. We received a contact - karina.margarian@talkdesk.com for a partnership program and filled the forms they provided, but the next step **4. Joint Technical Scoping Session** is on their side and they do not answer for our emails. This time I put the Director to cc, maybe he'll help to move this further.

**Comment by alejobs** [comment]
Hi,

We pushed also on our side. Any news?

**Comment by igrankova** [comment]
@alejobs hi! the contact from Talkdesk side ignores me. Can't reach her out.

**Comment by igrankova** [comment]
@alejobs can you contact them and ask to set up the Joint Technical Scoping Session for Airbyte?

**Comment by igrankova** [comment]
@alejobs 
LastPass name: Primary Talkdesk Developer Account
The OAuth app screen: https://airbyte-dev.mytalkdesk.com/atlas/apps/oauth-clients/65115b8232524c859cf1d7dd64ad5dd2/edit

**Comment by igrankova** [comment]
After the OAuth integration is implemented, we should send the Project for review to obtain a public access: https://airbyte-dev.mytalkdesk.com/atlas/apps/developer/projects

**Comment by igrankova** [comment]
@alejobs, I see the PR is merged already. So it's done.

**Comment by alejobs** [comment]
Ohhh, many thanks!

**Comment by alejobs** [comment]
hi @igrankova,

What we were requesting is still not merged: https://github.com/airbytehq/airbyte/pull/17587

What is blocking this?

**Comment by igrankova** [comment]
hi, @alejobs 
trying to find out what else can block the PR you need. [comment in PR17587](https://github.com/airbytehq/airbyte/pull/17587#issuecomment-1438157993)
