### ISSUE TITLE
Salesforce Source: Understand stream parity

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10282]
Based https://github.com/airbytehq/airbyte/issues/9679, there's some ambiguity around what streams Airbyte supports and what actually needs to happen to reach parity for MLP.

Assignee of this issue should follow-up on what's already been researched to catalog outstanding streams we need to support in order to reach parity with competitors and include them in epic: https://github.com/airbytehq/airbyte/issues/10283

**Comment by bazarnov** [comment]
Refer to the comment here:
https://github.com/airbytehq/airbyte/issues/10283#issuecomment-1042782800

**Comment by bazarnov** [comment]
Closed, cause the parent EPIC is resolved.
