### ISSUE TITLE
label existing connectors with release stage

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10288]
Add source and destination `release_stage` to each connector definition.

**Comment by sherifnada** [comment]
@jrhizor I'm realizing there is an issue with how this is implemented: it doesn't take into account connector version upgrades which I imagine can be misleading for users upgrading their connector versions without upgrading Airbyte core. It's not a show stopper but was this considered/is there a known path forward?

**Comment by jrhizor** [comment]
Had the same thought in parallel and created https://github.com/airbytehq/airbyte/issues/10361. I don't think it's a show stopper since it'll just stay on the same unlabeled behavior for existing connectors they're using on an instance.
