### ISSUE TITLE
REST API for Operations has inconsistent casing for operationID

### ISSUE THREAD

**Issue by sdairs** [airbytehq/airbyte#10307]
https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/operations/get 

For all resource operations the casing for IDs is camel-cased e.g. connectionId, sourceId, destinationId

However, the get for an operation returns the id with the key beginning with a capital (`OperationId` vs `operationId`) - while the Response after creating an Operation returns the expected camel-cased `operationId`

post /v1/operations/get 

`{
  "OperationId": "17ef4688-5fd0-4000-84ce-4c3b6a0b9401"
}`

post /v1/operations/create

RESPONSE 

` {
"workspaceId": "17ef4699-0620-4000-86a4-98e7762ee280",
"operationId": "17ef4699-0620-4000-83ca-264d0a0f8480",
"name": "string",
"operatorConfiguration": {
"operatorType": "normalization",
"normalization": {
"option": "basic"
},
"dbt": {
"gitRepoUrl": "string",
"gitRepoBranch": "string",
"dockerImage": "string",
"dbtArguments": "string"
}
}
}`

**Comment by alafanechere** [comment]
fixed after merging https://github.com/airbytehq/airbyte/pull/10464
