### ISSUE TITLE
Speed up getting an integration's spec

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1030]
## Tell us about the problem you're trying to solve
Retrieving an integration's spec takes a long time (5-10s) which heavily degrades the UI experience. We should ideally cache this information for an instant response.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368074773226) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
closed by https://github.com/airbytehq/airbyte/pull/1066/files
