### ISSUE TITLE
Ability to have multiple Sync frequencies for a connection

### ISSUE THREAD

**Issue by arvind-workit** [airbytehq/airbyte#10313]
## Tell us about the problem you're trying to solve
Ability to have multiple Sync Frequencies for a connection.

1. This helps the source and target application teams to have scheduled down time for the maintenance
2. Unwanted or low value sync runs are reduced in-turn reducing the credit usage in Airbyte Cloud and corresponding source and destinations
3. Reduction in logs written
4. Reduces the need to use an external orchestrator

## Describe the solution you’d like
In the business hours I want to be able to have a near real time sync (every 5 minutes) and in Non Business hours I want to be able to have sync every 2 hours or have a delayed run time with in non business hours.

## Describe the alternative you’ve considered or used
There is no other alternative where the connection is the same or even using multiple connections.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Multiple syncs for single connection](https://app.harvestr.io/components/0/list/tijZdqei5)

**Comment by evantahler** [comment]
@andyjih  can you link this up to the cron-syntax work?

**Comment by andyjih** [comment]
We're about to release cron-based scheduling as a feature! That will be coming in the next couple weeks. 

I believe that should cover the use case you described, but if not, do please comment in this other issue: https://github.com/airbytehq/airbyte/issues/2170
