### ISSUE TITLE
[EPIC] defogging connector health metrics noise

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10328]
## Tell us about the problem you're trying to solve

- [x] #12118 
- [x] #12119
- [x] https://github.com/airbytehq/airbyte-cloud/issues/1506

**Comment by evantahler** [comment]
I propose this epic (and child stories) be closed as well
* In the new metrics poposals by @bleonard, we do not need to know if a connection has been disabled or not.
* Incident management is already it's own epic
* Other work roughly captured by https://github.com/airbytehq/airbyte/issues/12118 and https://github.com/airbytehq/airbyte/issues/12119

**Comment by sherifnada** [comment]
@evantahler can you link to the new metrics proposals? i don't believe I've seen them

**Comment by bleonard** [comment]
> @evantahler can you link to the new metrics proposals? i don't believe I've seen them

Near term roadmap of [this](https://docs.google.com/document/d/1EahGAgEjrkujcasHJDpApP7dqMjEbU9ve0RoU1RE8ls/edit#heading=h.warglsyveguo) document.

**Comment by sherifnada** [comment]
@evantahler I'd like to keep this issue if only as an aggregator of all these other EPICs. It's useful to have a single entry point which encompasses all the things which, when done, constitutes a defogged style of life
