### ISSUE TITLE
Set up Cloud Health Dashboard

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#10327]
## Tell us about the problem you're trying to solve
We want automated alerting for stuck jobs in Cloud so that issues can be addressed proactively.

## Describe the solution you’d like
- If a job is in a non-terminal status beyond X threshold, a PagerDuty alert should be triggered
- ~~Metabase/BigQuery is updated hourly and may already contain the data we need to set this up~~ We should use Datadog for this. Talked with @ChristopheDuong about it and we should use Metabase for "slow" metrics. e.g. stuff where a day lag time okay. For things where seconds / minutes / hours count we should use DD. In addition, the pipeline into Metabase uses Airbyte, so if Airbyte is down, we won't have visibility into what is wrong. --charles
- We should have a Datadog dashboard that clearly shows stuck job status

## Misc
In order for us to trigger on long running jobs, we really need to be doing some sort of heart beating. We had something that tried to do this at some point. Really a long running job isn't a problem. It's a long running job that hasn't sent a record for X threshold that is a problem. There is likely dev work that has to be done before we can report on this, so it may not be something we do as part of this issue or what we do as part of this issue will need to be heavily caveated.

## Acceptance Criteria
- At a glance an engineer can see the health of the platform (person needs to think about what these are)
- Metrics are split out by 50th 85th 95th 99th percentiles
- Set threshold so that on call engineers is alerted when there are problems

## Metrics
_Here are some basic metrics, but the person doing this issue should brainstorm more._ 
note: We should filter out airbyte users

* % failed jobs
* % quarantined jobs
* % failed jobs due to non-source and non-destination error
* in one graph:
    * \# jobs launched per rolling 30 minutes 
    * \# jobs completed per rolling 30 min 
    * \# jobs failed per rolling 30 min
* \# concurrent running jobs
* \# enabled connections
* job run times over last 24 hours (percentiles)
* jobs by failure origin
* \# pending jobs (does this exist?)
* \# quarantined jobs

**Comment by pmossman** [comment]
Open questions for backlog grooming:
- What thresholds do we define?
- How do we get the necessary information from Metabase/BigQuery to DataDog?

**Comment by cgardens** [comment]
> What thresholds do we define?

Good question. For a long running job that is hard to say. Added some color on that above. For % failed jobs etc, I'm not sure the threshold. 95%? 95% on the first try?

> How do we get the necessary information from Metabase/BigQuery to DataDog?

We should report directly to DD instead of going through metabase. See comment I added above in body.

**Comment by pmossman** [comment]
For long running jobs, I wonder how feasible it would be to push a metric to DD periodically? Just spitballing here but we could have the message tracker push a metric to datadog when it sees a new state message, for instance, just so we know that progress is being made.

**Comment by davinchia** [comment]
I didn't realise we have the idea of `quarantined` jobs in our state machine. What state represents that?

**Comment by davinchia** [comment]
some other ideas:
* age of pending job
* breakdown of commonly used schedules 

does % failed jobs mean percentile of failed jobs? shouldn't failed jobs be a straightforward number?

**Comment by pmossman** [comment]
Sprint review notes:
- More complex DB queries are mostly figured out, still needs some polish/tests
- Next up is temporal query for quarantined jobs
- ^ goal is to have these two by Friday
- Everything else mostly figured out
