### ISSUE TITLE
[Chart] pre-install hook and service account

### ISSUE THREAD

**Issue by GKTheOne** [airbytehq/airbyte#10336]
## Environment
- **Airbyte version**:  0.35.28-alpha
- **OS Version / Instance**: macOS 12.2.1
- **Deployment**: Kubernetes
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: Medium
- **Step where error happened**: Deploy

## Current Behavior
When using helm to install via the chart in the repo, the bootloader pre-install hook reports that the service account cannot be found.

## Expected Behavior
Helm should be creating the service account resource before the bootloader pod.

## Logs

```
❯ helm upgrade --install --debug --namespace airbyte airbyte-eval ../../airbyte-project/charts/airbyte/ --values eval-values.yaml
history.go:56: [debug] getting history for release airbyte-eval
Release "airbyte-eval" does not exist. Installing it now.
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/gary/Projects/DataWarehouse/airbyte/airbyte-project/charts/airbyte

client.go:299: [debug] Starting delete for "airbyte-env" ConfigMap
client.go:328: [debug] configmaps "airbyte-env" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airbyte-eval-postgresql" Secret
client.go:328: [debug] secrets "airbyte-eval-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airbyte-eval-postgresql" Service
client.go:328: [debug] services "airbyte-eval-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airbyte-eval-postgresql" StatefulSet
client.go:328: [debug] statefulsets.apps "airbyte-eval-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airbyte-eval-postgresql-headless" Service
client.go:328: [debug] services "airbyte-eval-postgresql-headless" not found
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "airbyte-eval-bootloader" Pod
client.go:328: [debug] pods "airbyte-eval-bootloader" not found
client.go:128: [debug] creating 1 resource(s)
Error: failed pre-install: warning: Hook pre-install airbyte/templates/bootloader/pod.yaml failed: pods "airbyte-eval-bootloader" is forbidden: error looking up service account airbyte/airbyte-admin: serviceaccount "airbyte-admin" not found
helm.go:84: [debug] failed pre-install: warning: Hook pre-install airbyte/templates/bootloader/pod.yaml failed: pods "airbyte-eval-bootloader" is forbidden: error looking up service account airbyte/airbyte-admin: serviceaccount "airbyte-admin" not found
```

## Steps to Reproduce
1. Create a values file with release specific config. (Mine simply set webapp ingress annotations, hosts, & tls)
2. Helm install (or upgrade --install)

## Are you willing to submit a PR?
Not for a (probably long) while 😢

**Comment by GKTheOne** [comment]
I did find this [stackoverflow QA][1] that mentions setting a helm hook on the service account resource will correct the ordering.
I took the hook annotations from the bootloader pod template, adjusted the hook-weight value, added them to the service account declaration in the install values file, and the install now works as expected 🎉😄

```
serviceAccount:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
```

[1]: https://stackoverflow.com/questions/63381443/helm-pre-install-job-is-created-before-service-account

**Comment by marcosmarxm** [comment]
@GKTheOne I'm closing in favor of new Helm chart deployment method. Please open a new one if the issue persists.

**Comment by djpirra** [comment]
I am currently getting this error with the latest helm chart. What is the solution for this?
I have not changed the default values.yaml configuration.


```# Global params that are overwritten with umbrella chart
global:
  # -- Service Account name override
  serviceAccountName: &service-account-name "airbyte-admin"
