### ISSUE TITLE
Source Close.com: no export of custom fields values

### ISSUE THREAD

**Issue by maofet** [airbytehq/airbyte#10339]
## Environment
- **Airbyte version**:  0.35.4-alpha
- **OS Version / Instance**: Amazon Linux 2 ec2 m5.large
- **Deployment**: Docker
- **Source Connector and version**: Close.com 0.1.0
- **Destination Connector and version**: Postgres 0.3.14
- **Severity**: High
- **Step where error happened**: Data ingestion

## Current Behavior
We are trying to use [Close.com](http://close.com/) connector for Airbyte https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-close-com but faced with the situation that our custom fields are exported in right way, but we cannot find the values for this fields. For example, we have several rows in table contact_custom_fields but cannot find their value

## Expected Behavior
Custom fields values should be ingested separately or in main tables.

**Comment by YowanR** [comment]
@roman-yermilov-gl @lazebnyi Was this issue fixed already? I've added it to the epic as it was a bug.

**Comment by YowanR** [comment]
@roman-yermilov-gl @lazebnyi Was this issue fixed already? I've added it to the epic as it was a bug.

**Comment by lazebnyi** [comment]
Fixed during migration
