### ISSUE TITLE
Destination Clickhouse: normalization issue `Cannot parse string 'false' as Int8: syntax error at begin of string`

### ISSUE THREAD

**Issue by keshav-multi** [airbytehq/airbyte#10347]
## Environment
- **Airbyte version**:  example is 0.35.26-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker-compose
- **Source Connector and version**: Postgres 0.4.4
- **Destination Connector and version**: Clickhouse 0.1.3
- **Step where error happened**: Sync Job

## Current Behavior
Data is not normalizing. These are the 2 errors I see when I tried with 2 different tables

- First issue: 

> Cannot parse string 'false' as Int8: syntax error at begin of string. Note: there are toInt8OrZero and toInt8OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION CAST(is_staff :: 3, 'boolean' : 19) -> CAST(is_staff, 'boolean') Int8 : 22'

- Second issue:
> DB::Exception: Missing columns: 'true' while processing query: 'WITH __dbt__cte__test_dummyProject_dummyTable_ab1 AS (SELECT JSONExtractRaw(_airbyte_data, 'id') AS id, JSONExtractRaw(_airbyte_data, 'field') AS field, _airbyte_ab_id, _airbyte_emitted_at, now() AS _airbyte_normalized_at FROM public._airbyte_raw_test_dummyProject_dummyTable AS table_alias WHERE 1 = 1), __dbt__cte__test_dummyProject_dummyTable_ab2 AS (SELECT accurateCastOrNull(id, '\n    Float64\n') AS id, nullIf(accurateCastOrNull(replaceRegexpAll(field, concat('^[', regexpQuoteMeta('"'), ']*|[', regexpQuoteMeta('"'), ']*$'), ''), 'String'), 'null') AS field, _airbyte_ab_id, _airbyte_emitted_at, now() AS _airbyte_normalized_at FROM __dbt__cte__test_dummyProject_dummyTable_ab1 WHERE 1 = 1), __dbt__cte__test_dummyProject_dummyTable_ab3 AS (SELECT assumeNotNull(hex(MD5(concat(toString(id), '~', toString(field))))) AS _airbyte_test_offerW__pp_dummyTable_hashid, tmp.* FROM __dbt__cte__test_dummyProject_dummyTable_ab2 AS tmp WHERE 1 = 1) SELECT id, field, _airbyte_ab_id, _airbyte_emitted_at, now() AS _airbyte_normalized_at, _airbyte_test_offerW__pp_dummyTable_hashid FROM __dbt__cte__test_dummyProject_dummyTable_ab3 WHERE (1 = 1) AND coalesce(CAST(_airbyte_emitted_at, 'DateTime64') >= (identity(_CAST('0', 'Nullable(DateTime64(3))')) AS _subquery170), true)', required columns: '_airbyte_ab_id' 'field' '_airbyte_test_offerW__pp_dummyTable_hashid' '_airbyte_emitted_at' 'id' 'true' '_airbyte_ab_id' 'field' '_airbyte_test_offerW__pp_dummyTable_hashid' '_airbyte_emitted_at' 'id' 'true'. 

## Expected Behavior
Data should be normalized

## Logs
Log file of the first table. It is a standard Django user model. https://docs.djangoproject.com/en/4.0/ref/contrib/auth/
[logs-35902 (1).txt](https://github.com/airbytehq/airbyte/files/8069581/logs-35902.1.txt)

**Comment by wbchn** [comment]
i met the same error when using clickhouse as distnation.

after read the source , it is accouse by dbt-core, before 0.21.0, not work good on clickhouse: https://github.com/dbt-labs/dbt-core/issues/4084, and it already fixed at 0.21.1 https://github.com/dbt-labs/dbt-core/pull/4112.

so, in my opinion, just change the dbt version to 0.21.1 in `airbyte-integrations/bases/base-normalization/clickhouse.Dockerfile` will solve this problem.

i will try it tomorrow.

Sorry for the poor phone typo format.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
