### ISSUE TITLE
QuickBooks source connector - Icon update

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#10344]
## Tell us about the problem you're trying to solve
We have a QuickBooks icon used for a background picture as a visual. We received a requirement from the support to update this icon:
![Icon in visuals](https://user-images.githubusercontent.com/87977540/154044961-2e104b1f-7b14-4f66-8f30-805a75ffd253.png)

And we have the Icons with incorrect spelling: 
![image](https://user-images.githubusercontent.com/87977540/153884232-d94d0cf6-aee5-4c0b-8a6f-0e616e5f51b7.png)
![search](https://user-images.githubusercontent.com/87977540/154045492-48ea9a9a-b6c5-47d7-a33e-69b6df977c8b.png)

All Icons should include word "QuickBooks" with the correct spelling:
https://developer.intuit.com/app/developer/qbo/docs/go-live/list-on-the-app-store/naming-and-logo-guidelines#button-graphics
![image](https://user-images.githubusercontent.com/87977540/154046434-57d7069a-b897-4fbb-b8c2-939c328be03f.png)

## Describe the solution you’d like
**Now we have:** https://airbyte.com/connectors/quickbooks
![logo](https://user-images.githubusercontent.com/87977540/153884812-4d14a760-4d2f-4937-a041-1d3fa69d257b.png)

**Should be the logo with the name QuickBooks:**
![logo_update](https://user-images.githubusercontent.com/87977540/153885333-a90e6376-86b3-4c9c-b972-13eb82ef0ac8.png)
**or we can use one of the approved logos:** 
[intuit_approved_logos.zip](https://github.com/airbytehq/airbyte/files/8061637/intuit_approved_logos.zip)

**Comment by Upmitt** [comment]
@igrankova I updated the pictures and incorrect spelling. Let me know if I missed any logo or incorrect spellings. I saw they also have incorrect spelling on their website here: https://quickbooks.intuit.com/global/ - Maybe they would like to correct it. 
<img width="1328" alt="Screenshot 2022-04-11 at 10 53 08" src="https://user-images.githubusercontent.com/29780098/162701405-abbe5015-1273-4fd2-ab01-9317e62d8812.png">

**Comment by igrankova** [comment]
Hi, @Upmitt 
Thank you very much for this update. I kindly ask you to update one last spelling here: https://airbyte.com/connectors/quickbooks
![airbyte_com1](https://user-images.githubusercontent.com/87977540/162709810-7c442eae-3b64-46ef-9409-ae83b0a061fc.png)

Thank you for mentioning the mistake on their website, I'll let them know.

**Comment by igrankova** [comment]
@misteryeo Hi, Andy, we still have one missed spelling. See the comment above: https://github.com/airbytehq/airbyte/issues/10344#issuecomment-1094808629

**Comment by Upmitt** [comment]
@igrankova @misteryeo Updated on Webflow

**Comment by igrankova** [comment]
@misteryeo good! thank you. I'm closing this issue.
we still have two more issues to implement in the EPIC #10264
