### ISSUE TITLE
Using existing RSA token in MySQL connection with SSH Tunnel

### ISSUE THREAD

**Issue by matthewbrandt** [airbytehq/airbyte#10345]
## Environment
Is this your first time deploying Airbyte
=> Yes
OS Version / Instance
=> MacOS 12.1 Monterey
Deployment
=> Docker
Airbyte Version
=> 0.35.3-alpha
Source name/version
=> MySQL
Step
=> Set up the source
Description
=> io.airbyte.workers.WorkerException: Error while getting checking connection.

## Current Behavior
I am trying to connect to MySQL using an SSH tunnel and am able to do so with DataGrip (my local IDE), but cannot get the connection working inside Airbyte in Docker.
I've tried numerous things but keep getting a connection error. Have debugged with your support (Marcos Marx) who said I should create a ticket.

## Expected Behavior
My existing RSA token can be used and I can connect to the MySQL database.

## Logs
are attached here
[logs-062db089-3256-41de-8cd5-e80089205894-.txt](https://github.com/airbytehq/airbyte/files/8068538/logs-062db089-3256-41de-8cd5-e80089205894-.txt)

## Steps to Reproduce
1. Have a MySQL database set up through SSH tunnel
2. Create a new connection
3. Attempt to connect using an existing RSA token

## Are you willing to submit a PR?
No (insufficient knowledge)

**Comment by alafanechere** [comment]
Could you please make sure your RSA token is a valid PEM file? According to your logs, the connector fails at parsing your PEM file.

**Comment by matthewbrandt** [comment]
@alafanechere hey, this totally solved my issue!
