### ISSUE TITLE
allow linking to a specific job / attempt

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10369]
A common problem while maintaining an Airbyte instance is to share a link to a connection (see https://airbytehq-team.slack.com/archives/C02TXQ020QM/p1644962513455699 ) and then refer to a specific run by job id, time, attempt, etc. Then it's a struggle to figure out which one it actually is from any of those values. It'd be better if we could link to a specific one, either on its own route, or on a separate page. Ideally this link could be copied from the connection page. 

Ideally this link would open onto the connection page with that specific element expanded.

**Comment by jrhizor** [comment]
@erica-airbyte: I know this would be useful on the eng side, but would this be useful for TS? Or slightly different functionality that would be make this better for TS?

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
> After writing this, I think an even easier QoL improvement may be to just show the job id on the page so it's searchable.

Is this really more comfortable to use or were you thinking in terms of implementation ease? I feel we should just have a copy button in an attempt (besides the "download log" button), to copy a link containing a hash, bringing you directly to that attempt expanded when opened. I feel it's easier to share like this, specifically if we'll be asking users to share that with us.

**Comment by jrhizor** [comment]
@timroes yeah, it was purely in terms of implementation ease, not ease of use.

Expanding to the attempt is definitely ideal.
