### ISSUE TITLE
Add ability to select different schemas (rather than just public schema) in Postgres integration

### ISSUE THREAD

**Issue by sjlogan** [airbytehq/airbyte#1036]
I am attempting to use Airbyte to move data from a postgres db to a warehouse. The data I care about lives in a schema that is not the "public" schema. Airbyte currently only sees the public schema, thus I cannot use the tool to move my data.

When setting up a postgres integration in Airbyte, I would like to be able to see and select from a list of the schemas the postgres user I provided has access to before selecting the tables in that schema that I wish to migrate. Ideally, I would want to be able to select multiple schemas. Of course, this would also mean that Airbyte would have to be intelligent about writing data to their own schemas (or at least prepending schema names to target tables) when writing to the destination.

Stitch.io allows me to select a non-"public" schema as I am setting up a postgres source. If I select multiple schemas, it can prepend schema names to the target tables in the warehouse. They cannot write data to different target schemas in the target warehouse (without setting up multiple integrations), which would be the optimal solution.

Reach out if you have questions or if I can clarify anything.

**Comment by ChristopheDuong** [comment]
Adding conversation happening on slack around this use case: 
![Screenshot 2021-01-28 at 14 15 20](https://user-images.githubusercontent.com/7718175/106143638-5b8c8080-6173-11eb-96cb-0ac414f2df69.png)

**Comment by cgardens** [comment]
I believe the postgres source now supports multiple schemas. I think we just forgot to update this issue.

**Comment by davinchia** [comment]
Confirmed we support this today.

<img width="1187" alt="Screen Shot 2021-05-19 at 4 02 26 PM" src="https://user-images.githubusercontent.com/9772859/118777472-af0a1200-b8bb-11eb-9aa6-f3e32def9bd8.png">
