### ISSUE TITLE
why not support mysql （Incremental Sync - Deduped History）

### ISSUE THREAD

**Issue by kuaile1993** [airbytehq/airbyte#10373]
why not support mysql （Incremental Sync - Deduped History）

**Comment by marcosmarxm** [comment]
Hello @kuaile1993 thanks for opening this. This request is a duplicate of https://github.com/airbytehq/airbyte/issues/3487. I'll close in favor of the older one. Please if you have more info/contex about what this is important to you add a comment to the issue.
