### ISSUE TITLE
Destination BigQuery: improve check connection performance

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10377]
Relates to: https://github.com/airbytehq/airbyte/issues/10149

## Tell us about the problem you're trying to solve
As part of the [investigation into speeding up check connection](https://github.com/airbytehq/airbyte/issues/10149), our testing found that the check connection method (and discover schema method) for some connectors is slow (even after removing platform overhead)

Ideally, our 99 percentile for performing check connection is < 10 seconds. Given that the Kube overhead is ~5 seconds, we want the connector to finish in something like 3 seconds. This gives us 2 seconds of buffer to play with.

Results (does not include platform overhead):
* destination Postgres - ~ 4 seconds (I was using this as a generic RDS connector)
* destination Snowflake - ~ 14 seconds
* source salesforce - ~ 3 seconds

## Acceptance Criteria
- [ ] Destination BigQuery check (GCS & Insert load modes) connection takes < 5 seconds

If it is necessary to remove some thoroughness in the check connection (i.e: do fewer operations and get a less granular failure message)

**Comment by VitaliiMaltsev** [comment]
check method for destination BigQuery does not need to be optimized, as it is already reduced to a minimum. 

After numerous experiments, the results are as follows:
standard inserts ~ 2.7 seconds
GCS staging ~ 6-8 seconds

But it is important to understand that a very important role in calculating the time of processing the check method is the latency of the service that is being accessed and the stability of the Internet connection. 
In some cases, GCS staging can take up to 20 seconds or more

**Comment by misteryeo** [comment]
@VitaliiMaltsev to clarify, does this mean that there's nothing further we can optimize on the Airbyte side of things?

**Comment by davinchia** [comment]
@VitaliiMaltsev questions from me too:
1) how were you measuring the time taken?
2) what measures did you try to reduce the time?

**Comment by VitaliiMaltsev** [comment]
@misteryeo @davinchia BigQuery Destination check time consists of 2 main parts : 
**1.** **SELECT * FROM `%s.INFORMATION_SCHEMA.TABLES` LIMIT 1;** to check if BigQuery is available. This query is already limited by 1 row so i don't see options for optimization

_Note: in this case(SELECT) we check only read permission but not write and delete. In case of adding additional INSERT and DELETE(write and delete permissions) queries , the total time of the check method will also be increased for BigQuery destination_

**2.** Check permissions to  read/write/delete objects into GCS bucket which is also pretty simple 
    **s3Client.putObject(bucketName, testFile, "this is a test file");
    s3Client.deleteObject(bucketName, testFile);**

All tests were carried out locally, respectively, and the measured time refers to the localhost and may vary depending on where the airbyte is deployed

**Comment by davinchia** [comment]
Thanks for the explanation.

One follow up from me - for S3, is it possible to check for permissions on the bucket instead of attempting the operation with the current instruction set we have?

**Comment by VitaliiMaltsev** [comment]
@davinchia investigated your suggestion and created [PR](https://github.com/airbytehq/airbyte/pull/11350) to check for permissions on the bucket. Please review
The results are:
Standard inserts ~ 2.7 seconds
GCS staging ~ 3 seconds
