### ISSUE TITLE
Postgres Source Connector doesn't correctly read privileges for materialized views

### ISSUE THREAD

**Issue by jedwards-gc** [airbytehq/airbyte#10389]
## Environment
- **Airbyte version**: Not applicable (but I'm using v0.35.12-alpha)
- **OS Version / Instance**: Amazon Linux 2, AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 0.3.14+
- **Severity**: Medium
- **Step where error happened**: Setup new connection / Update latest source schema

## Current Behavior
I created issue #9012 which has been resolved, but my materialized views still don't show up in the sync catalog.

## Expected Behavior
Materialized views should show up in the sync catalog.

## Logs
Looking at the [PR](https://github.com/airbytehq/airbyte/pull/9116/files) I saw the following was added to the query for privileges:
```
SELECT r.rolname           AS table_catalog,
    n.nspname           AS table_schema,
    c.relname           AS table_name,
    -- the initial query is supposed to get a SELECT type. Since we use a UNION query
    -- to get Views that we can read (i.e. select) - then lets fill this columns with SELECT
    -- value to keep the backward-compatibility
    COALESCE ('SELECT') AS privilege_type
FROM   pg_class c
JOIN   pg_namespace n
ON     n.oid = relnamespace
JOIN   pg_roles r
ON     r.oid = relowner,
Unnest(COALESCE(relacl::text[], Format('{%s=arwdDxt/%s}', rolname, rolname)::text[])) acl,
    Regexp_split_to_array(acl, '=|/') s
WHERE  r.rolname = ?
AND    nspname = 'public'
    -- 'm' means Materialized View
AND    c.relkind = 'm'
AND    (
           -- all grants
           c.relacl IS NULL
           -- read grant
    OR     s[2] = 'r');
```

I adapted it to this query:
```
SELECT r.rolname,
       relacl,
       acl,
       s, s[1], s[2]
FROM pg_class
  JOIN pg_roles r ON r.oid = relowner, Unnest(COALESCE(relacl::text[],Format('{%s=arwdDxt/%s}',rolname,rolname)::text[])) AS acl, Regexp_split_to_array(acl, '=|/') AS s
WHERE relkind = 'm'
  AND relname LIKE 'my_materialized_views%'
```

Which showed me:
| rolname | relacl | acl | s | s[1] | s[2] |
| ------- | ------ | --- | - | ---- | ---- |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq,arwdDxt,u6g8dvvzr0ldvq} | u6g8dvvzr0ldvq | arwdDxt |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | engineer=r/u6g8dvvzr0ldvq | {engineer,r,u6g8dvvzr0ldvq} | engineer | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | analyst_ro=r/u6g8dvvzr0ldvq | {analyst_ro,r,u6g8dvvzr0ldvq} | analyst_ro | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | s3_logical_backups=r/u6g8dvvzr0ldvq | {s3_logical_backups,r,u6g8dvvzr0ldvq} | s3_logical_backups | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | glue=r/u6g8dvvzr0ldvq | {glue,r,u6g8dvvzr0ldvq} | glue | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq,arwdDxt,u6g8dvvzr0ldvq} | u6g8dvvzr0ldvq | arwdDxt |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | engineer=r/u6g8dvvzr0ldvq | {engineer,r,u6g8dvvzr0ldvq} | engineer | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | analyst_ro=r/u6g8dvvzr0ldvq | {analyst_ro,r,u6g8dvvzr0ldvq} | analyst_ro | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | s3_logical_backups=r/u6g8dvvzr0ldvq | {s3_logical_backups,r,u6g8dvvzr0ldvq} | s3_logical_backups | r |
| u6g8dvvzr0ldvq | {u6g8dvvzr0ldvq=arwdDxt/u6g8dvvzr0ldvq,engineer=r/u6g8dvvzr0ldvq,analyst_ro=r/u6g8dvvzr0ldvq,s3_logical_backups=r/u6g8dvvzr0ldvq,glue=r/u6g8dvvzr0ldvq} | glue=r/u6g8dvvzr0ldvq | {glue,r,u6g8dvvzr0ldvq} | glue | r |

The username I'm using in Airbyte is "glue", so I'm guessing that's what's being used as the role name in the query, e.g. `WHERE  r.rolname = 'glue'`, which obviously fails. I don't what the `"u6g8dvvzr0ldvq"` role name is, presumably it is something generated by Heroku (my source database is Heroku PostgreSQL). My instinct is the query should be
```
WHERE s[1] = 'glue'
```
instead.

**Comment by etsybaev** [comment]
Hi @jedwards-gc .
Don't you have some SQL queries to share that would allow me to reproduce this issue on clear DB? 
Thanks

**Comment by etsybaev** [comment]
Hi @jedwards-gc
It's hard to fix the issue when you can't fully reproduce it. I had some suggestions and fixed them accordingly. 
Please try again with the connector's version 0.4.10.
Feel free to re-open issues in case it's still reproducible, but kindly ask to provide more details\SQL scripts to reproduce on clear DB. Thanks!

**Comment by SophieLohezic** [comment]
Hello. It seems to work with connectors 0.4.4 but not with 0.4.10, 0.4.14 or 0.4.15 (latest versions). Could you please include materialized views and privileges in your testing cases)  🙏 ? Many thanks for your work.
