### ISSUE TITLE
Source Hubspot: Support the `property_history` stream

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10391]
## Main Issue
Currently, it seems that we currently don't support this stream, and it's been requested by a user.

## Relevant Slack Conversation
https://airbytehq.slack.com/archives/C01A4CAP81L/p1643410583469179

**Comment by misteryeo** [comment]
This stream is supported: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/property_history.json

Closing this out
