### ISSUE TITLE
Notion - blocks from child pages are not synced

### ISSUE THREAD

**Issue by divyav** [airbytehq/airbyte#10395]
## Environment
- **Airbyte version**:  0.35.27-alpha
- **OS Version / Instance**: AMazon Linux 2
- **Deployment**: Docker
- **Source Connector and version**: Notion 0.1.2 

- **Destination Connector and version**: s3 0.2.7 
- **Severity**: Critical
- **Step where error happened**: Post Sync

## Current Behavior
Post data sync, I see blocks only from main pages, not subpages(structure attached). Do I have to configure anything explicitly to get those blocks?

<img width="312" alt="notion-page-structure" src="https://user-images.githubusercontent.com/989410/154428981-a6fd9168-b741-4c41-91c6-b6116b8bc87b.png">

## Expected Behavior
Blocks from sub-pages are synced as well.

## Are you willing to submit a PR?
Yes

**Comment by lgomezm** [comment]
Hello @divyav. I've been trying to reproduce the issue and I have found this: If you want to sync blocks from subpages, you have to explicitly share them with your integration. Sharing a main page won't automatically share its subpages. I think that is why you can't see blocks from subpages.

I tried sharing both main pages and subpages with my test integration and it successfully syncs blocks from subpages.

Please let me know if this is your case or if there's anything else I should consider in the setup.

**Comment by lgomezm** [comment]
I am able to successfully sync child blocks if I share the child page with the integration:
<img width="916" alt="Screen Shot 2022-05-01 at 9 11 15 AM" src="https://user-images.githubusercontent.com/781929/166149701-29218632-7b2e-4a2b-aa0c-73519f50738e.png">

Then, you just have to setup a connection that syncs blocks. I am using Notion source connection, version 0.1.3:
<img width="974" alt="Screen Shot 2022-05-01 at 9 02 59 AM" src="https://user-images.githubusercontent.com/781929/166149758-a13e3353-df73-45dd-90dd-4a96b6e27f2f.png">

As it can be seen, it synced the quote block from the child page:
<img width="970" alt="Screen Shot 2022-05-01 at 9 02 42 AM" src="https://user-images.githubusercontent.com/781929/166149801-85e9c100-b147-4ded-9dfa-4baf1d44af32.png">

Local JSON file for blocks:
[_airbyte_raw_blocks.txt](https://github.com/airbytehq/airbyte/files/8599089/_airbyte_raw_blocks.txt)
