### ISSUE TITLE
Source Google Search Console: Add dataState parameter to get fresher data

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#10402]
## Tell us about the problem you're trying to solve
Get fresher data from the google search console api. Right now the data is 2-3 days old.

## Describe the solution you’d like
The search console api introduced a dataState parameter a while ago, that allows for getting fresher data from the api. The default api mode for this parameter is `dataState=final`, which only gives you final validated data. The second option is `dataState=all` which allows you to get the same data that is surfaced in the reports in the search console.

More info on the parameter:
https://searchengineland.com/google-search-console-api-gains-fresh-data-more-344552
https://developers.google.com/webmaster-tools/v1/searchanalytics/query

## Describe the alternative you’ve considered or used
Going back to use search console UI instead of our DWH.

**Comment by jrolom** [comment]
@artusiep assigning you to work on this one - looking forward to your PR!

**Comment by artusiep** [comment]
@jrolom Assign me to that issue, please

**Comment by sajarin** [comment]
Closed by #26452
