### ISSUE TITLE
Investigate onFocus requeries

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10401]
`react-query` does by default resend a query whenever the window loses/regains focus. This has no direct use-case for us, and we're also not really updating our UI/state inside the components based on the new query, thus we should disable this globally. We might want to leverage that feature later on individually in some places where it could make sense.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by Jamakase** [comment]
From docs

```
Stale queries are refetched automatically in the background when:
New instances of the query mount
The window is refocused
The network is reconnected.
The query is optionally configured with a refetch interval.
```

```
To change this functionality, you can use options like refetchOnMount, refetchOnWindowFocus, refetchOnReconnect and refetchInterval.
```

I believe we want to disable all of them, right?

**Comment by timroes** [comment]
I am not sure about `refreshInterval`, since I understood it, that unless we enable that the response will always be treated as cached no matter how long you're on the website. But I haven't tested that, and it might be a misunderstanding of the docs. I am also not sure about `refetchOnMount`. I feel it would make sense to load fresh data whenever the component is mounted e.g. the user is navigating to another page and back again - feels like it makes sense to me to get fresh data in that scenario.

`refetchOnWindowFocus` and `refetchOnReconnect` though could be disabled imho.

For `refetchInterval` I think it would be good to check if when disabled, we'll still get fresh data, e.g. on mount while navigating through the application.
