### ISSUE TITLE
Source FB Marketing: improve check connection performance

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10406]
Relates to: https://github.com/airbytehq/airbyte/issues/10149

## Tell us about the problem you're trying to solve
As part of the [investigation into speeding up check connection](https://github.com/airbytehq/airbyte/issues/10149), our testing found that the check connection method (and discover schema method) for some connectors is slow (even after removing platform overhead)

Ideally, our 99 percentile for performing check connection is < 10 seconds. Given that the Kube overhead is ~5 seconds, we want the connector to finish in something like 3 seconds. This gives us 2 seconds of buffer to play with.

Results (does not include platform overhead):
* destination Postgres - ~ 4 seconds (I was using this as a generic RDS connector)
* destination Snowflake - ~ 14 seconds
* source salesforce - ~ 3 seconds

## Acceptance Criteria
- [x] Source FB Marketing check connection takes < 5 seconds

If it is necessary to remove some thoroughness in the check connection (i.e: do fewer operations and get a less granular failure message)

**Comment by midavadim** [comment]
1. I have tested 'check' and 'discover' methods via UI and CLI and I have not seen any significant delays ( about 1s)

2. I have also checked connector code and I have not seen any places where the problem can happen

3. I have reviewed related issues and spreadsheets and I actually was not able to find any evidence (and numbers) which could indicate slowness of check and discover methods.

@misteryeo, @davinchia is it enough to close this issue? or could you help me to find more information about circumstances in which I can re-produce the problem?

**Comment by sherifnada** [comment]
@midavadim that should be sufficient to close!
