### ISSUE TITLE
Setup Cloud health dashboard (Datadog)

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#10414]
Should switch to Metabase and BigQuery instance for finding stuck workflows (left in Running, left in Failed, etc)

**Comment by pmossman** [comment]
Sprint planning notes: Is it possible to set up metric/alerts for unschedulable pods due to insufficient node resources? Perhaps we can create an alert when resource consumption is greater than X% so we can get ahead of it? Multivariate problem, needs some investigation

**Comment by davinchia** [comment]
I realise there was a duplicate issue https://github.com/airbytehq/airbyte/issues/10327
