### ISSUE TITLE
Add exception name to `externalMessage` into failureSummary

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10416]
Currently we may send a failure summary as follows:

```js
{
    "id": 2,
    "status": "failed",
    "createdAt": 1645038993,
    "updatedAt": 1645071127,
    "endedAt": 1645071126,
    "bytesSynced": null,
    "recordsSynced": null,
    "totalStats": null,
    "streamStats": [],
    "failureSummary": {
        "failures": [
            {
                "failureOrigin": "replication",
                "failureType": null,
                "externalMessage": "Something went wrong during replication",
                "stacktrace": "io.temporal.failure.TimeoutFailure: message='activity timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT\n",
                "retryable": null,
                "timestamp": 1645071126978
            }
        ],
        "partialSuccess": null
    }
}
```

In the UI we only show the `failureOrigin` and the `externalMessage`. This object already holds a bit more information, that would help investigating an error. While you can view the full log already (though in this very specific case the exception actually didn't make it into the log), and we could show a stacktrace in an expanded view, I think it would be helpful if we would at at least the exception name to the default `externalMessage`, i.e. have it along the lines of "Something went wrong during replication (io.temporal.failure.TimeoutFailure)" or "Something went wrong during replication (TimeoutFailure: activity timeout)". That would give the `externalMessage` a bit more usefulness to get a quick overview of what's failing.

**Comment by evantahler** [comment]
This is done!
