### ISSUE TITLE
Expose temporal stats

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#10413]
Will need to setup time with somebody on Infra, likely just adding some labels to temporal containers to push stats to either prometheus or statsd
- Want to be able to access temporal stats in Datadog, so we can track metrics that matter
  - tracking time between scheduling work and starting work, critical metric
  - number of failed activities
  - basically, a monitoring dashboard to see health of temporal service itself

**Comment by jrhizor** [comment]
thread: https://airbytehq-team.slack.com/archives/C02TXT37Y3Y/p1645154752953859

Still figuring out what approach to take.

**Comment by jrhizor** [comment]
We're now capturing temporal stats in a temporary Prometheus server. Going to close this issue since the short term goal of collecting usage estimates is complete and we won't actually do this in the future for cloud.

**Comment by jvstein** [comment]
Are there plans to make the prometheus metrics available for consumption in the open source version?

**Comment by jrhizor** [comment]
@jvstein I don't think that component will include the temporal stats.

Only two things are really required:
1. Modify the `development.yaml` file we mount to include 
```
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"
```

2. Add an environment variable mounted to the Temporal service: `PROMETHEUS_ENDPOINT: "0.0.0.0:9090"` 

Just that can give you access to Temporal _server_ metrics.

**Comment by jvstein** [comment]
@jrhizor Thank you, that worked great for enabling the temporal service metrics!
