### ISSUE TITLE
Source Twilio: 400 Client Error when syncing Massages table

### ISSUE THREAD

**Issue by nwayne94** [airbytehq/airbyte#10418]
## Environment
- **Airbyte version**:  0.35.10-alpha
- **OS Version / Instance**: Mac OS 11.5.2
- **Deployment**: Docker
- **Source Connector and version**: Twilio 0.1.2
- **Destination Connector and version**: Redshift 0.3.25
- **Severity**: Critical
- **Step where error happened**: Sync Job

## Current Behavior
When we run the sync, other tables are able to sync successfully, but a 400 Client Error gets thrown whenever the Messages table tires to sync

## Expected Behavior
Messages table should sync like the other tables

## Logs
[logs-1291.txt](https://github.com/airbytehq/airbyte/files/8090863/logs-1291.txt)

## Steps to Reproduce
1. Set up Twilio Source
2. Set up Redshift Destination
3. Set Messages table to sync

**Comment by novotl** [comment]
When replaying the errored request manually this is the error we receive 
```
{
  "code": 20004,
  "message": "Date range specified in query is partially or entirely outside of retention window of 400 days",
  "more_info": "https://www.twilio.com/docs/errors/20004",
  "status": 400
}
```

This is the default data retention for message media and message records.
