### ISSUE TITLE
Add an activity to check that all the pods related to a failed connection are down

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#10420]
## What

Add an activity in temporal to check that after a failure, all the pods related to this connection has a KILLED signal being send to them. 

Since this activity will be added in the middle of the history, it will require a new temporal version.

**Comment by cgardens** [comment]
@timroes @benmoriceau what is the observed behavior that this solves? it is pods that continue to run after failure? do they run to completion or do they terminate after some fixed time (this would expected behavior)? which pods stay running?

**Comment by cgardens** [comment]
Next step is to find the root cause of why we get into this state first.

**Comment by pmossman** [comment]
Decided this is risky and we don't want to do this after all
