### ISSUE TITLE
Separate Segment tokens per environment

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10450]
We should split our segment tokens based on what environment the product is running in.

* On-Prem (i.e. built into the product): `6cxNSmQyGSKcATLdJ2pL6WsawkzEMDAN` (this is the existing token)
* Cloud (Prod): `Z5x1PeHSvBUrs6OBdZzuq9uEZVjmz2P7`
* Cloud (all non-prod environments): `kXg9Zg4uT5RnzFpSMaNvfbpHY2ejpAUc`

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
