### ISSUE TITLE
pod sweeper cleans from the start time, not the end time

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10467]
This can cause a race condition in the worker (see https://github.com/airbytehq/airbyte/issues/10466).

While we have a temporary "fix" for cloud https://github.com/airbytehq/airbyte-cloud/pull/1038 by extending the waiting period, it's insufficient to guarantee this doesn't occur. 

We need to reference the last event seen for the pod instead of the creation time.

**Comment by cgardens** [comment]
To be clear, we have not actually seen this cause problems. It is just a hypothetical. The one case we thought it might be involved seems to be unrelated.

**Comment by jrhizor** [comment]
That is correct.

**Comment by cgardens** [comment]
@jrhizor How serious is this? Should we treat it as medium? @davinchia for visibility

**Comment by jrhizor** [comment]
Medium's appropriate. Could cause problems but hasn't yet.
