### ISSUE TITLE
Source Notion Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10474]
The centralized hub for all feature requests and bugs associated with the [Notion Source](https://docs.airbyte.com/integrations/sources/notion) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/1).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | All endpoints have associated streams. | | | | ✔️ | $300 |
| Incremental Sync| Not currently implemented for the `Users` stream | | | | ❌ | $300 |
| Pagination | | | | @lgomezm | ❌ | $200 |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-notion/unit_tests) | | | | ✔️ | - |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | | | | | ❌ | $100 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Blocks from sub pages are not synced |  | [Issue](https://github.com/airbytehq/airbyte/issues/10395) | | | ❌ | $100 |
| Basic normalization fails | | [Issue](https://github.com/airbytehq/airbyte/issues/8702) | | | ❌ | $200 |
</details>

**Comment by itaseskii** [comment]
Hey @avaidyanatha I have done some analysis of what can and can't be done from the above requirements and these are my findings.

1. **Incemental Sync:**
* **Users** -> Incremental sync can't be implemented since the Users stream doesn't provide any field that can be used as a cursor field.
		
3. **Pagination:**
* Already implemented for **Databases**, **Pages** and **Blocks**
* **Users** -> Most likely overlooked setting of next page in the request params.
```
class Users(NotionStream):
    """
    Docs: https://developers.notion.com/reference/get-users
    """

    def path(self, **kwargs) -> str:
        return "users"

    """
    TODO Probably needs to set the next_page_token as a query parameter when sending 
    a request as in the example bellow
    """
    
    def request_params(self, stream_state: Mapping[str, Any], stream_slice: Mapping[str, Any] = None,
                       next_page_token: Mapping[str, Any] = None) -> MutableMapping[str, Any]:
        if next_page_token:
            return {"start_cursor": next_page_token}

```

**Comment by lgomezm** [comment]
I’ll start working on pagination support for the `Users` stream. Other streams, as @itaseskii commented, already support this feature.

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
