### ISSUE TITLE
airbyte-workers module should not depend on airbyte-api

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#10479]
## Tell us about the problem you're trying to solve
The API interface should not be known to the internals of the worker. We should think about handling this sooner rather than later, because the longer it exists this way, the more clutter it gathers.

**Comment by cgardens** [comment]
@benmoriceau @jrhizor for visibility. you might have opinions on whether this is the right approach.

**Comment by davinchia** [comment]
I think this is straight-forward. Looked at it for 10 mins and should have a PR up shortly.
