### ISSUE TITLE
Remove frontmatter header from documentation sidesheet

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10491]
Our documentation markdown uses frontmatter, thus we need to make sure before rendering a documentation in the sidesheet to strip of the frontmatter headers. Currently they are simply rendered into the sidesheet:

![screenshot-20220221-092241](https://user-images.githubusercontent.com/877229/154915843-9ce259af-a1cf-4bdb-9aea-75fad7aa0316.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
