### ISSUE TITLE
External Secrets Store Support: AWS Secrets Manager

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#10518]
epic: https://github.com/airbytehq/airbyte/issues/837

## Tell us about the problem you're trying to solve
Currently, Airbyte only integrates with one external secrets store: GCP Secrets Manager. Users on AWS prefer to use [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/).

## Describe the solution you’d like
Add AWS Secrets Manager as an option for external secrets. 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today. We already have a `SecretsPersistence` interface to work with. The existing GCP Secrets Manager implementation can be found in the class `GoogleSecretManagerPersistence`. Basically we need to: 

1. Implement `SecretsPersistence` for AWS Secrets Manager with tests similar to what already exists.
2. Allow setting appropriate env variable to configure it and pipe through that configuration into the app.

In terms of external contribution part 1 should be very doable. We would be happy to help on part 2 once tests are passing for part 1.

**Comment by davinchia** [comment]
This is done!

**Comment by nataliekwong** [comment]
fyi @tryangul I saw this was referenced in a recent customer conversation and is now completed.
