### ISSUE TITLE
Destination snowflake: Typo mentioning redshift.

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10512]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

In this file: `./docs/integrations/destinations/snowflake.md` the AWS S3 staging section mentions Redshift specific setting but this file documents Snowflake destination connector. Moreover, default values mentioned: `This is 10MB by default` do not correspond to the 5Mb default set in the connector.

**Comment by koconder** [comment]
@alafanechere change is here https://github.com/airbytehq/airbyte/pull/18326 - Someone seems to have removed the redshift stuff already.
