### ISSUE TITLE
Database full and the job scheduler re-trying infinite causing denial of service

### ISSUE THREAD

**Issue by agrass** [airbytehq/airbyte#10521]
## Environment
- **Airbyte version**:  0.35.6-alpha
- **OS Version / Instance**: Linux EC2 m5.4xlarge
- **Deployment**: example are Docker
- **Destination Connector and version**:   MySQL 0.1.15
- **Severity**: Critical
- **Step where error happened**:  Sync job 
- 

## Current Behavior
When MySQL database it's full will infinite retry and due the infinite loop of retries the service stop working. I needed to delete the destination to recover it.

## Expected Behavior
 It would be great that after some number of retries pause the connection or just retry with longer timeframes.

**Comment by marcosmarxm** [comment]
Closed because scheduler container is deprecated.
