### ISSUE TITLE
Normalization error when string exceed max size

### ISSUE THREAD

**Issue by agrass** [airbytehq/airbyte#10520]
## Tell us about the problem you're trying to solve
Send larger strings without an error on normalization due maximum row size:
`ERROR creating table model : Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs   `

## Describe the solution you’d like
Be able to define the length on the JSON Schema, could be with "maxLength" (https://json-schema.org/understanding-json-schema/reference/string.html), by default maxLength will be with string data type but depending the size will select correctly text or blobs datatype depending the length. 

## Describe the alternative you’ve considered or used
Generate a custom DBT transformation

## Are you willing to submit a PR?
Yes, If you can help me where I can modify this I can try to solve this because it's a big issue to us. 

More info: https://airbytehq.slack.com/archives/C01MFR03D5W/p1628553949439300

**Comment by alafanechere** [comment]
@agrass do you confirm you're suggesting the following heuristic? -> if the generated schema declares a max length >= 65k the normalization for MySQL should use the `TEXT` type.

**Comment by agrass** [comment]
> @agrass do you confirm you're suggesting the following heuristic? -> if the generated schema declares a max length >= 65k the normalization for MySQL should use the `TEXT` type.

Exactly that's the idea, that way It's possible to solve this issue just changing the schema instead of generating a custom dbt

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
