### ISSUE TITLE
Source shopify: add balance transactions stream data to testing store

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#10524]
Add balance transactions stream in our testing store as the tests are failing. This will close #9850

**Comment by harshithmullapudi** [comment]
@igrankova can you help here? Is this possible?

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, let me find out what can I do.

**Comment by igrankova** [comment]
@harshithmullapudi can you specify what account should I update?

**Comment by harshithmullapudi** [comment]
Hey I think shop `airbyte-integration-test` is what we are using right now

**Comment by igrankova** [comment]
Thank you, I'm in.

**Comment by igrankova** [comment]
@harshithmullapudi still working on it, today I've created and paid orders, but I don't see the Balance Transactions changed after that. I'm finding out how to create these transactions with the support team.

**Comment by igrankova** [comment]
@harshithmullapudi, hi! Can you check the tests? Has anything changed with the Balance Transactions? If not, please specify more details for the support team.

**Comment by harshithmullapudi** [comment]
Hey sorry for late reply will check and update in some time

**Comment by igrankova** [comment]
@harshithmullapudi, can you answer this question from the Shopify support?
"let me know an estimate of how many transactions you will need to process for the purpose of testing your API? "
They are trying to help us with transactions for testing

**Comment by harshithmullapudi** [comment]
Hey I tried running the tests now bit looks like we are having some trouble with API rate limiting but anyways having transactions more than 10 or so is a good place to be

**Comment by igrankova** [comment]
@harshithmullapudi hi, I received an answer from the support: "Your store is now able to process up to 25 Orders for testing your integration on airbyte-integration-test.myshopify.com"
But I faced a problem to access the store now, the passwords from the LastPass do not work.

**Comment by igrankova** [comment]
@harshithmullapudi Hi! I've received the instructions from the support team and made several test payments. I kindly ask you to check transactions, can I do anything else for this task?

**Comment by harshithmullapudi** [comment]
@igrankova I ran and it still says the same `AssertionError: All streams should return some records, streams without records: ***'balance_transactions'***` did we verify if the API is returning results?
