### ISSUE TITLE
HubSpot Sync Job Hangs on Deals Sync

### ISSUE THREAD

**Issue by rorymalcolm** [airbytehq/airbyte#10544]
## Environment
- **Airbyte version**: 0.35.32-alpha
- **OS Version / Instance**: Ubuntu Focal 20.04
- **Deployment**: EC2
- **Source Connector and version**: HubSpot 0.1.41	
- **Destination Connector and version**: Redshift 0.3.25	
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Airbyte sync hangs on `Syncing stream: deals`, syncs succeed without deals

## Expected Behavior
Airbyte should sync deals from HubSpot

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

2022-02-22 14:36:36 source > Finished syncing SourceHubspot
2022-02-22 14:36:36 source > SourceHubspot runtimes:
2022-02-22 14:36:36 source > Syncing stream: deal_pipelines 
2022-02-22 14:36:36 source > Read 3 records from deal_pipelines stream
2022-02-22 14:36:36 source > Finished syncing SourceHubspot
2022-02-22 14:36:36 source > SourceHubspot runtimes:
2022-02-22 14:36:36 source > Syncing stream: deals 

</details>

## Steps to Reproduce
1. Setup HubSpot source with API key and deals as an input
2. Setup Redshift destination with S3 copying
3. Run a sync job

## Are you willing to submit a PR?
Yes

**Comment by rorymalcolm** [comment]
Tried to do further debugging including extracting worker logs etc, none the wiser

**Comment by ridem** [comment]
We're experiencing the exact same issue as OP.

## Environment
Airbyte version: 0.35.35-alpha
OS Version / Instance: Debian 10
Deployment: GCP
Source Connector and version: HubSpot 0.1.44
Destination Connector and version: Postgres 
Severity: High
Step where error happened: Sync job

## Extra context

Hubspot API call logs provide useful extra information. The endpoint `/deals/v1/deal/paged` keeps being called by Airbyte while it looks like it's hanging. It's sending approximately 150 requests per minute to Hubspot, as long as the job is live.

![Screen Shot 2022-02-25 at 17 01 02](https://user-images.githubusercontent.com/3911747/155747162-36233f5a-85c3-446e-bfc8-d609fb957c3e.png)

**Comment by rorymalcolm** [comment]
> We're experiencing the exact same issue as OP.
> 
> ## Environment
> Airbyte version: 0.35.35-alpha OS Version / Instance: Debian 10 Deployment: GCP Source Connector and version: HubSpot 0.1.44 Destination Connector and version: Postgres Severity: High Step where error happened: Sync job
> 
> ## Extra context
> Hubspot API call logs provide useful extra information. The endpoint `/deals/v1/deal/paged` keeps being called by Airbyte while it looks like it's hanging. It's sending approximately 150 requests per minute to Hubspot, as long as the job is live.
> 
> ![Screen Shot 2022-02-25 at 17 01 02](https://user-images.githubusercontent.com/3911747/155747162-36233f5a-85c3-446e-bfc8-d609fb957c3e.png)

Likewise saw the same behaviour & failure mode on the hubspot API

**Comment by lgomezm** [comment]
I've been looking at the source code and found that the `Deals` stream is also getting all deal stage history. The `DealStageHistory` stream is in turn getting all deals to transform them to deal stage history records. This all means the deals stream gets all deals twice to yield deals in the first sync! This also happens for getting incremental updates: it tries to get all deals (to get the deals stage history) and then matches deal stage history to the deal being yielded. This doesn't seem to me like the right approach.

This is the method by the way: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1038-L1053

In a similar problem I dealt with in the past, I wanted to get the deal stage name (that I can get with the DealPipelines stream) to set it to each deal, so I created a connection that sync both deals and deal pipelines and then I matched when I had both data in the destination. If users of the hubspot-source connector could do the same, it's possible to remove the use of `DealStageHistory` stream from the `Deals` stream and, instead, create a connection that uses both streams and then connect deals with their stage history at the destination. I submitted the above PR for that.

**Comment by rorymalcolm** [comment]
> I've been looking at the source code and found that the `Deals` stream is also getting all deal stage history. The `DealStageHistory` stream is in turn getting all deals to transform them to deal stage history records. This all means the deals stream gets all deals twice to yield deals in the first sync! This also happens for getting incremental updates: it tries to get all deals (to get the deals stage history) and then matches deal stage history to the deal being yielded. This doesn't seem to me like the right approach.
> 
> This is the method by the way: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1038-L1053
> 
> In a similar problem I dealt with in the past, I wanted to get the deal stage name (that I can get with the DealPipelines stream) to set it to each deal, so I created a connection that sync both deals and deal pipelines and then I matched when I had both data in the destination. If users of the hubspot-source connector could do the same, it's possible to remove the use of `DealStageHistory` stream from the `Deals` stream and, instead, create a connection that uses both streams and then connect deals with their stage history at the destination. I submitted the above PR for that.

Thanks, this makes a lot of sense

**Comment by matfiorlh** [comment]
We are facing a similar situation with the `engagements` object which is also connected to other objects related to it.
