### ISSUE TITLE
Insert batching doesn't work with Snowflake

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1054]
## Expected Behavior
We shouldn't send one record at the time

see https://airbytehq.slack.com/archives/C01A4CAP81L/p1605815910144200?thread_ts=1605810422.143400&cid=C01A4CAP81L

## Current Behavior
We are issuing one insert at a time. It might be affecting other destinations

## Severity of the bug for you
High: This destination is unusable

**Comment by michel-tricot** [comment]
@cgardens can we make sure we prioritize this ASAP?

**Comment by cgardens** [comment]
agreed. 

@michel-tricot have you verified this behavior or is this just based off of what is in this slack thread? 

did a very quick glance at the code, and it appears that the query that the destination uses _does_ attempt to batch records. that is to say, i am not seeing an obvious issue here in the code. that being said it is definitely possible something else in our pipeline is causing this. potentially how we are pulling from the on-disk queue, etc.

**Comment by michel-tricot** [comment]
I haven't verified it. So we should probably attempt to replicate before diving into it.

**Comment by cgardens** [comment]
okay so indeed this is a problem. this line creates n inserts statements instead of a single insert statement with n values. https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeRecordConsumer.java#L111-L113

**Comment by michel-tricot** [comment]
It seems to be using the addBatch API. Is that not the way to do it?

**Comment by cgardens** [comment]
done.
