### ISSUE TITLE
Source MongoDB: connector fail with password which contains special character

### ISSUE THREAD

**Issue by Morpheus1999** [airbytehq/airbyte#10569]
Dears
I found one bug when creating MongoDB connector with password which contains special character such as %
## Environment
- **Airbyte version**:  0.35.3-alpha
- **OS Version / Instance**: Centos7
- **Deployment**:  Docker
- **Source Connector and version**: source-mongodb-v2  0.1.10
- **Severity**:  Low
- **Step where error happened**: Create connector

## Current Behavior
It appears error when creating MongoDB source connector with password which contains special character such as % + / ?

## Expected Behavior
Password can contain special characters, for example % + / ?

## Steps to Reproduce
1. Create MongoDB connector
2. Input all necessary information  
3. Input password which consist of special character

## Are you willing to submit a PR?
Currently, do not have this plan.

**Comment by aglucky** [comment]
Is there an in-depth guide on setting up MongoDB with Airbyte? I'm having trouble creating a connection to a free-tier MongoDB Atlas I created to test my PR.
