### ISSUE TITLE
Normalization doesn't respect table name rule creating for reserved words

### ISSUE THREAD

**Issue by thisisile** [airbytehq/airbyte#10572]
## Environment
- **Airbyte version**:  0.35.26-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Salesforce
- **Destination Connector and version**: Snowflake
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
When syncing salesforce tables, there is a table created in snowflake with casing
All tables are uppercase but only one table (Case) has upper case and lower case

## Expected Behavior
All tables should be in uppercase in snowflake when running
SHOW TABLES IN DEV.SALESFORCE;
table Case should be CASE

**Comment by thisisile** [comment]
I assume maybe that this is a bug when tables are created in snowflake ?

**Comment by thisisile** [comment]
![salesforce-case-issue-to-upload](https://user-images.githubusercontent.com/85608733/159591718-f787a2af-865e-4059-b286-c0c4d36b72d8.png)

**Comment by marcosmarxm** [comment]
`Case` is a reserved word in Snowflake. This table is created as "Case". But good call @thisisile is something that can fix.

**Comment by thisisile** [comment]
@marcosmarxm Thank you. Do let me know when this is resolved.

**Comment by thisisile** [comment]
Hi @marcosmarxm. Just coming back to this. Is there an update here ?
The Case object is one of the main, default objects and we know what the issue is. 
Hopefully the issue can be resolved some time soon ? :pray:

**Comment by wwfch-cyrill** [comment]
Besides the object "Case", the salesforce Object "Order" is causing the same issues. Any workaround?

**Comment by marcosmarxm** [comment]
@evantahler I think this is another issue we can close with Normalization v2

**Comment by evantahler** [comment]
>  I think this is another issue we can close with Normalization v2
Yep! feel free to close now, and link to https://github.com/airbytehq/airbyte/issues/26028

**Comment by wwfch-cyrill** [comment]
> Besides the object "Case", the salesforce Object "Order" is causing the same issues. Any workaround?

The workaround is to add a prefix in the connection settings.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
