### ISSUE TITLE
change the domain in the body of the webhook notification

### ISSUE THREAD

**Issue by dahadaller** [airbytehq/airbyte#10598]
Hello, I was wondering how I can change the domain in the body of the webhook notification:
In the message below, I would like to change localhost:8000 to the public address where airbyte is being hosted. It doesn't appear that this is an option in the interface.

> Your connection from Okta version 0.1.4 to BigQuery version 0.6.7 succeeded
This was for sync started on Friday, February 18, 2022 at 1:03:08 PM Coordinated Universal Time, running for 8 minutes 29 seconds.
You can access its logs here: http://localhost:8000/connections/792cdbca-8f3f-446f-ac8c-bd4d94e5285d

**Comment by ameyabapat-bsft** [comment]
As it sends a POST request to the webhook and it conveys for both success and failure jobs. Instead of plain-text, we can redirect the response of `/api/v1/jobs/get` for respective jobid? it contains success/failure and meta data details around the data being synced we could avoid the huge log lines from the response. Users can consume the necessary data based on their requirements. it could help users of airbyte to keep track of the jobs details being run easily. Otherwise we have to periodically poll for specific jobid with the hope that it is complete and then gather the details.

**Comment by ameyabapat-bsft** [comment]
I think instead of plain-text, this type of Response would be more beneficial like 
`{
  "job": {
    "id": 783,
    "configType": "sync",
    "configId": "7e39a2bc-196e-44d7-ac54-7741356d2e22",
    "createdAt": 1647413090,
    "updatedAt": 1647413114,
    "status": "succeeded"
  },
  "attempts": [
    {
      "attempt": {
        "id": 0,
        "status": "succeeded",
        "createdAt": 1647413091,
        "updatedAt": 1647413114,
        "endedAt": 1647413114,
        "bytesSynced": 1500,
        "recordsSynced": 30,
        "totalStats": {
          "recordsEmitted": 30,
          "bytesEmitted": 1500,
          "stateMessagesEmitted": 1,
          "recordsCommitted": 30
        },
        "streamStats": [
          {
            "streamName": "TEST_SECONDS",
            "stats": {
              "recordsEmitted": 30,
              "bytesEmitted": 1500,
              "stateMessagesEmitted": null,
              "recordsCommitted": 30
            }
          }
        ]
      },
    }
  ]
}`

**Comment by pedroslopez** [comment]
Hi @dahadaller - you should be able to set this by changing the `WEBAPP_URL` environment variable to your public URL.

**Comment by evantahler** [comment]
Closing because I think the docs have the answer.  Please re-open this if you need more help!

**Comment by seanglynn-thrive** [comment]
@evantahler @dahadaller 
It would be great if we could modify this var within the helm chart:
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/env-configmap.yaml#L55
There is no option in our helm values file to edit this.

**Comment by evantahler** [comment]
@sjmunoz and @seanglynn-thrive please make a new issue so we can track it!

**Comment by seanglynn-thrive** [comment]
@evantahler I've opened: https://github.com/airbytehq/airbyte/issues/23269 
LMK if there is anything else I can do here 🙇
