### ISSUE TITLE
Number covered by usage bar

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#10609]
## Current Behavior
The usage credits when more than a few numbers after the decimal point are hidden behind the visual bar: 
![Airbyte  Credits 🔊 2022-02-24 at 8 56 31 AM](https://user-images.githubusercontent.com/16851149/155491742-2177fd3f-dd5f-484b-a6aa-29b71deb347b.jpg)

## Expected Behavior
The number should be displayed clearly and not overlap with the visual bar.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
