### ISSUE TITLE
manual operations sync/reset/cancel should show errors when the server fails

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10605]
Currently, if a user attempts to sync/reset/cancel and there is a server-side failure, no error is shown to the user and the page just feels uninteractive. For sync now, it's left in a consistently spinning state.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by Jamakase** [comment]
This is duplicate of https://github.com/airbytehq/airbyte/issues/10215
