### ISSUE TITLE
fix gradle --scan for connectors build

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10608]
When the connectors build fails, it's difficult to tell which test cases since it's failing without a build scan.

One "quick fix" might be to publish the test report in a way that is downloadable on the Github Actions UI with the `upload-artifact` action. You can see how we publish Kubernetes logs on failure as an example.

The real fix would be to remove the source dependencies introduced in `settings.gradle`:
```
sourceControl {
    gitRepository("https://github.com/airbytehq/json-avro-converter.git") {
        producesModule("tech.allegro.schema.json2avro:converter")
    }
    gitRepository("https://github.com/airbytehq/jsongenerator.git") {
        producesModule("net.jimblackler:jsongenerator")
    }
}
```

See https://github.com/gradle/gradle/issues/13795 for the underlying issue. My understanding is that we should turn these into real published artifacts and consume them instead of using the source repositories. Then the `--scan` option would work automatically.

Not having visibility on transient connector build failures (especially for `:airbyte-workers:test`) makes eliminating transient failures much harder.

**Comment by jrhizor** [comment]
@tuliren fyi (just tagging since you added the source dependencies)

**Comment by tuliren** [comment]
> we should turn these into real published artifacts and consume them instead of using the source repositories.

Agree with this.

@jrhizor, how urgent is this issue? Should we fix this in the next 2-3 sprints?

**Comment by jrhizor** [comment]
With https://github.com/airbytehq/airbyte/pull/10615 it should be much lower priority from the platform's perspective. I don't know how easy it is to debug for connectors - up to you on the prio of this.

**Comment by sherifnada** [comment]
fwiw this is not really a problem on python connectors since they use SAT anyways. @grishick moving this to the DBs backlog since it's not a concern for Sources DX

**Comment by tuliren** [comment]
The direct dependencies on the github repositories have been removed in https://github.com/airbytehq/airbyte/pull/12531.
