### ISSUE TITLE
handle deleted connections differently in UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10601]
## Tell us about the problem you're trying to solve
In Cloud, we're seeing a few users delete connections and then try to perform actions on them (like manual runs, cancellations, etc). Also, as an admin, it's difficult to see what's happening. For an example you can look at a connection like the one referenced in https://github.com/airbytehq/oncall/issues/150

## Describe the solution you’d like
Configuration updates, manual syncs, cancellation, etc. should not be available on the frontend for a deleted sync. The deleted sync's page also needs some kind of indicator to show that it was deleted (tombstoned). 

## Describe the alternative you’ve considered or used
We could just have the API 404 when this is requested. This is probably more confusing for admins though, since users may reference a specific connection to technical support, and it's hard to tell the order of events without being able to view the connection page for the deleted sync.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by Jamakase** [comment]
@jrhizor @timroes The problem is that connection/get request still returns this connection. I believe it just changes `status` field to deprecated. Should we just display some message that it is deprecated?

**Comment by jrhizor** [comment]
@Jamakase: that's right, deleted ==`deprecated`.

**Comment by timroes** [comment]
Feedback from syncing offline about this with @jrhizor:

* Users have some requirement of looking through past (deleted) syncs, thus the page should be accessible for deleted syncs.
* We want to disable all actions for a disabled sync and highlight that you're currently seeing a disabled sync (this is tracked via this issue and the draft PR).
* Users want to be able to access the previously deleted connections, thus we should give a way to access them, tracked via https://github.com/airbytehq/airbyte/issues/12099

**Comment by tealjulia** [comment]
I've created a new issue related to this around poor user experience when deleting the connection as well.
Seems worth addressing quite soon, but outside the scope of what @timroes outlined above.

https://github.com/airbytehq/airbyte/issues/12250
