### ISSUE TITLE
Checkboxes get into wrong enabled state

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10610]
When navigating to the Replication tab in a connection setting and back to any other page large switches will now be in a broken design state:

<img width="1619" alt="Screen Shot 2022-02-23 at 3 50 18 PM" src="https://user-images.githubusercontent.com/877229/155494838-c8c75f56-b9ca-420d-a9d0-8867fd377b4a.png">

This most likely means somthing is poluting the global styles on that page (I suspect the small switches in the table).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
