### ISSUE TITLE
MSSQL source sync adds T00:00:00Z to date values

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#10611]
So in my source MSSQL table I have a date column with values like "2020-01-01", but when syncing over to bigquery all these values in the raw table JSON suddenly are changed to "2020-01-01T00:00:00Z". 

Airbyte should not change source date like this!!

**Comment by marcosmarxm** [comment]
Close because of lack of information of what connector version and platform version.
