### ISSUE TITLE
Upgrade from 0.32 -> 0.35 is not persisting cursors

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#10616]
Bug/Issue found during configuration migration.

If user export the configuration and import it other server then *cursor* among all the connections are lost. (on and above <https://github.com/airbytehq/airbyte/releases/tag/v0.34.3-alpha|v0.34.3-alpha>)

Description:
I am trying to shift my configuration from EC2 instance to EKS. Hence performing configuration migration.
If I try to export configuration and try to import on other server (assuming on both airbyte is running same version and are above and equal to v0.34.3-alpha ) then after import all the connections restore, but all the existing log and execution are *lost*, along with cursor). Log are not important but cursor is needed. Otherwise, all the old data will be repeated again.
I tried same process with v0.34.2-alpha but airbyte is able restore all the configuration perfectly.

is this because of *<https://github.com/airbytehq/airbyte/pull/8646|this>* issue ?

I experimented this issue with following version:
```0.32.0-alpha-patch-1	working fine
0.32.11-alpha	        working fine
0.34.2-alpha	        working fine
0.34.3-alpha	        cursor lost
0.34.4-alpha	        cursor lost
0.35.1-alpha	        cursor lost
0.35.18-alpha	        cursor lost```


[Migration issue 2.docx](https://github.com/airbytehq/airbyte/files/8131668/Migration.issue.2.docx)

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1645109706430609?thread_ts=1645109706.430609&cid=C01MFR03D5W

**Comment by marcosmarxm** [comment]
Close due inactivity.
