### ISSUE TITLE
Saving changes to connector settings resets 'Namespace Custom Format' to 'null'

### ISSUE THREAD

**Issue by chrstnst** [airbytehq/airbyte#10633]
## Environment
- **Airbyte version**: 0.35.36-alpha
- **OS Version / Instance**: GCE n1
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.8
- **Destination Connector and version**: BigQuery 0.6.9
- **Severity**: Critical
- **Step where error happened**: Changing connector settings

## Current Behavior
Initial state: a connection is set up with 'Namespace Connection' of 'Custom Format' and a custom value in 'Namespace custom format'.

Saving changes to settings on the 'Replication' tab of connection settings (e.g. sync frequency) sets the 'Namespace Custom Format' to 'null'.

This might be a regression introduced with https://github.com/airbytehq/airbyte/pull/9025.

## Expected Behavior
Saving changes should leave the value unchanged.

## Steps to Reproduce
1. Open Settings > Replication of a connection with a custom namespace format
2. Change sync frequency and save changes
3. After leaving and returning to settings see value 'null' in custom namespace format

<img width="1306" alt="Screen Shot 2022-02-24 at 5 24 30 PM" src="https://user-images.githubusercontent.com/76215815/155573633-41f53395-c179-432e-a784-b35925be5db2.png">

**Comment by hellmund** [comment]
Seems to affect other connectors as well, e.g. File

Additional observation: When then changing the Namespace Custom Format to an actual value and pressing "Save changes" within the "Streams" card, the Replication frequency gets reset from "manual" to "Every 24 hours"

**Comment by chrstnst** [comment]
Issue is now being processed in https://github.com/airbytehq/airbyte/issues/10671
