### ISSUE TITLE
At the end of the onboarding, the links for the source / destination / connection for the ongoing initial sync are not working

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10643]
In the screenshot below, those 3 links should redirect to the corresponding source page, destination page, and connection status page. 

<img width="868" alt="Screen Shot 2022-02-24 at 1 27 12 PM" src="https://user-images.githubusercontent.com/68561602/155602552-fef19c7c-c3f1-4aac-965b-ecc5e6da1fd1.png">

cc @misteryeo

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
