### ISSUE TITLE
User should be able to go through source/destination setup, while setup guide is displayed

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10644]
If user uses the setup guide to set up a source or destination, they will most likely need the guide to be opened and displayed while setting up the source and destination. Right now, the setup guide prevents you from having access to the fields. This is not a great UX. 

See screenshot
<img width="1792" alt="Screen Shot 2022-02-24 at 1 31 36 PM" src="https://user-images.githubusercontent.com/68561602/155602892-6d95bb77-657f-4069-a5a3-83076262731f.png">

cc @misteryeo

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by misteryeo** [comment]
Just to clarify your suggestion here @johnlafleur, you're suggesting that instead of a sidesheet that pops out, this should be a side by side experience?

I think we should definitely factor this in as part of overall UX overhauls post launch.

**Comment by johnlafleur** [comment]
A side experience can be a solution indeed. 
The point is the user shouldn't go back and forth when setting up.

**Comment by cgardens** [comment]
@timroes what do you think the level of effort is for this one? rough engineering days estimate is fine.

**Comment by timroes** [comment]
@cgardens Depending on how we'd design this, this might somewhere between 1 day to a couple of days (if we require more redesign of that application for it).

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Setup guide sidesheet display](https://app.harvestr.io/components/0/list/HkZch2E0B)

**Comment by timroes** [comment]
https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26178%3A0

**Comment by tealjulia** [comment]
Linking to the specific item on that Figma that is relevant here: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32847%3A156452

**Comment by tealjulia** [comment]
@timroes last week we'd discussed having the Create Source and Create Destination pages use the two-panel view (ie: the layout in Figma) on initial page load with a placeholder image/CTA until a user selects a connector.  However, I don't think this flow works well for the Connections page because a user might or might not be creating a Source/Destination there.  

I think it may be better to mimic existing behavior across all pages (ie: only show the Setup Guide when a user clicks the Setup Guide link) with the only change being using the two-pane view proposed in place of the existing popup.  Thoughts?

**Comment by nataliekwong** [comment]
Loom video of the latest design (approved by Andy Jih) https://www.loom.com/share/594f82c0f689419fb29004c6ab0a8fd8
Link to Figma: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP?page-id=33609%3A177017&node-id=33609%3A177159&viewport=305%2C48%2C0.12&scaling=min-zoom&starting-point-node-id=33609%3A177159

**Comment by johnlafleur** [comment]
Just a question here: as this is pretty innovative in terms of user experience, would it be worth it to have a quick usability testing? we could ask in the Slack community or if we have calls with OSS users.

**Comment by tealjulia** [comment]
Thank you! Is there also a Figma and/or Loom for the Connection setup workflow? That is another one that has a less straightforward implementation (because a user may be creating a new Source/Destination or using an existing one within that same page)

**Comment by nataliekwong** [comment]
Nico put together the design to address 1) Creating a new source from an existing destination (similar behavior to creating a new destination from an existing source)

Video: https://www.loom.com/share/17fb99967b0f486791f5400e68e3d746 (note the connection settings should have open/show the setup guide even though the video shows it)

Prototype: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?page-id=33609%3A177017&node-id=33609%3A177159&viewport=305%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=33609%3A177159&show-proto-sidebar=1

Figma file: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/?node-id=33609%3A177017
