### ISSUE TITLE
"Connection Sync" should be sent when a sync starts, and when it ends (with results)

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1064]
Details are in tab "Track" as the last event. 
https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

Properties should be:
* user_id
* version_id
* sync_status
* sync_results
* frequency
* connector_source
* connector_destination

**Comment by cgardens** [comment]
done
