### ISSUE TITLE
🐛  Source Postgres: cannot retrieve all tables accessible to the user

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#10649]
## Environment
- **Airbyte version**:
- **OS Version / Instance**:
- **Deployment**:
- **Source Connector and version**: source postgres 0.4.8
- **Destination Connector and version**:
- **Severity**: Medium
- **Step where error happened**:

## Context
Slack [thread](https://airbytehq-team.slack.com/archives/C01VDDEGL7M/p1645725516903079)

> I’m using the latest 0.4.8 source-postgres source and I have a problem where I’m not able to list any tables in my source even though my user is able to select from the tables.
> I see there are a couple relevant tickets.
> * https://github.com/airbytehq/airbyte/pull/9875
> * https://github.com/airbytehq/airbyte/pull/10173
> I debugged and found that in AbstractJdbcSource.discoverInternal() where it filters tables with `excludeNotAccessibleTables`
> ```java
> protected Predicate<JsonNode> excludeNotAccessibleTables(final Set<String> internalSchemas,
>                                                            final Set<JdbcPrivilegeDto> tablesWithSelectGrantPrivilege) {
> the tablesWithSelectGrantPrivilege variable was empty.
> ```
>
> So because of that it entered this branch:
> ```java
> if (tablesWithSelectGrantPrivilege.isEmpty()) {
>   return isNotInternalSchema(jsonNode, internalSchemas);
> }
> ```
> and the PostgresSource has commented out the isNotInternalSchema() method to always filter out the
> ```java
> @Override
> protected boolean isNotInternalSchema(JsonNode jsonNode, Set<String> internalSchemas) {
>   return false;
> }
> ```
> If the `isNotInternalSchema` wasn’t overriden by postgres then my tables show up properly.
> I’m trying to understand the logic behind this?
> Whether the problem is with `getPrivilegesTableForCurrentUser` or that the `isNotInternalSchema` should not be overridden?
> Can someone shed some light on the philosophy behind how the `AbstractJdbcSource.excludeNotAccessibleTables` is supposed to work and the reasoning behind the
`PostgresSource.isNotInternalSchema` overriding?

Quick diagnosis:
- It looks like `isNotInternalSchema` was a new method introduced between PR #9875 and PR #10173.
- When PR #10173 tried to revert PR #9875, it added the `isNotInternalSchema` with a default implementation without thinking about what it meant.
- This is probably a bug.

**Comment by pcothenet** [comment]
Could be the same as #10548 ?

**Comment by grishick** [comment]
Ideally, the fix will be more generic than just addressing a single database, if that's possible. At the minimum, the fix should address current bug in Postgres source.
