### ISSUE TITLE
At the end of the onboarding experience, the cells of the recipes suggested are not clickable

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10642]
All the cells in the screenshot are not clickable, only the Skip button is. 
Those cells should be clickable and open the corresponding recipe in another tab. 

<img width="868" alt="Screen Shot 2022-02-24 at 1 27 12 PM copy" src="https://user-images.githubusercontent.com/68561602/155602249-7de95464-bdf9-42c7-aef6-50c280621f2f.png">

cc @misteryeo

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@johnlafleur Could you let me know which recipes they are meant to link to exactly. I didn't find a clear link for all of them. My understanding would be:

1)  "Replicate your MySQL database to Postgres with log-based CDC" -> https://airbyte.com/recipes/migrate-from-mysql-to-postgresql
2)  "Consolidate your marketing data to compute the CAC for your paid customers" -> ???
3)  "Consolidate your payment data to compute your LTV" -> ???
4)  "Build an activity dashboard for your engineering project" -> https://airbyte.com/recipes/build-a-github-activity-dashboard-for-your-project"
5)  "Visualize the time spent by your team in Zoom calls " -> https://airbyte.com/recipes/visualize-the-time-spent-by-your-team-in-zoom-calls

**Comment by johnlafleur** [comment]
Hey @timroes, sorry about this. 
If we're able to differentiate between Open-Source and Cloud here, here is what would be our suggestions:

**Cloud**
* Build a single customer view 
* Build a GitHub Activity dashboard
* Replicate your data between PostgreSQL databases
* Sync MySQL CDC to Kafka using Change Data Capture
* Build a data ingestion pipeline from Mailchimp to Snowflake

**Open-Source**
* Build a single customer view with open-source tools
* Orchestrate ELT pipelines with Prefect, Airbyte and dbt
* Automate your Data Scraping with Apache Airflow and Beautiful Soup | Airbyte
* Sync MySQL CDC to Kafka using Change Data Capture
* Partition and cluster BigQuery tables with Airbyte and dbt

If we can't distinguish both list, then the Cloud list.
