### ISSUE TITLE
Display the selected connector's certification status on the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10651]
## Tell us about the problem you're trying to solve
I selected Amplitude as a source on the source creation page and saw the following

<img width="811" alt="Screen Shot 2022-02-24 at 5 27 45 PM" src="https://user-images.githubusercontent.com/6246757/155636133-91d0ba3c-257b-4c8f-89c5-71ac73760d11.png">

This was confusing because it took me a second to realize that Amplitude was stated as alpha. I clicked the dropdown and it was clearer on the right: 
<img width="843" alt="Screen Shot 2022-02-24 at 5 26 44 PM" src="https://user-images.githubusercontent.com/6246757/155636225-77df0d9b-a75a-4758-a5cb-dc0289033529.png">

## Describe the solution you’d like
I would like the label to be displayed next to the connector name once it's selected (when the dropdown is not expanded)

CC @airbytehq/frontend

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
