### ISSUE TITLE
Source Google ads : labels fields does not have the correct values

### ISSUE THREAD

**Issue by iberchid** [airbytehq/airbyte#10662]
## Environment
- **Airbyte version**:  
- **OS Version / Instance**: 
- **Deployment**: Docker
- **Source Connector and version**: source-google-ads 0.1.28
- **Destination Connector and version**: 
- **Severity**: Medium
- **Step where error happened**: 

## Current Behavior
The field `labels` returned in the `campaigns` and in `ad_group_ads` stream do not have the right data. compared to the values shown in the UI and to another tool that uses the Google Ads API.

## Expected Behavior
The `labels` field should match the value from the UI.

## Steps to Reproduce
1. use the `campaigns` and in `ad_group_ads` streams in the configured catalog.
2. read the data.
3. compare it with the data in the UI.

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
Hello @iberchid could you give more information about what is different from the UI and the data returned from Airbyte Connector?

**Comment by iberchid** [comment]
Hi @marcosmarxm , maybe this is related to how these fields are fetched, for the [ad level](https://developers.google.com/google-ads/api/docs/migration/mapping#ad_performance) labels

![image](https://user-images.githubusercontent.com/93732608/155953412-6296e01c-5133-430b-a3f1-26f6ed7dd4af.png)

and for the [campaign level](https://developers.google.com/google-ads/api/docs/migration/mapping#campaign_performance) labels
![image](https://user-images.githubusercontent.com/93732608/155953773-971ff807-6c91-419e-bc3d-f683ad1f757b.png)

**Comment by edgao** [comment]
looking into this right now - yeah, it looks like we actually need to be querying against campaign_label (-> label.name). Unfortunately we'll need to make an extra query for this; Google doesn't actually link campaign -> campaign_label. Or at least the [query builder](https://developers.google.com/google-ads/api/fields/v7/campaign_query_builder) doesn't let you directly query for campaign_label from campaign.

I'm still familiarizing myself with this connector, but should have some idea of how to add this in the next few days.

**Comment by iberchid** [comment]
Hey @edgao , any update on this issue? Thanks!

**Comment by edgao** [comment]
sorry, haven't been able to make much progress on this. It's still high on my todo list, hoping to get to it in the next week or two!
