### ISSUE TITLE
Several regressions in the new connection UI

### ISSUE THREAD

**Issue by remisalmon** [airbytehq/airbyte#10671]
## Environment
- **Airbyte version**:  v0.35.35-alpha
- **OS Version / Instance**: AWS EC2 t2.xlarge
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.8 & HubSpot 0.1.44
- **Destination Connector and version**: Snowflake 0.4.14
- **Severity**: High
- **Step where error happened**: Update connector

## Current Behavior

The new UI has several regressions in the connection settings:
- changing the replication frequency changes the destination namespace custom format to "null"
- changing the destination namespace custom format changes the replication frequency to "Every 24h"
- changing the replication frequency changes the normalization back to "Original structure"

## Expected Behavior

The new UI should behave as expected/like the old one.

## Logs

Nothing unusual in the logs.

## Steps to Reproduce
1. Open a connection settings
2. Set replication frequency to manual, destination namespace to custom and normalization to "Serialized JSON"
4. Change the namespace custom format: the replication frequency is set to "Every 24h"
3. Change the replication frequency back to manual: the namespace custom format is set to "null" and the normalization is set to "Original structure"

Also reproduced with v0.35.38-alpha.

## Are you willing to submit a PR?

No.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@Jamakase Could you check if this is related to https://github.com/airbytehq/airbyte/issues/6791. If not can you please look into this issue.
