### ISSUE TITLE
UI toggle does not move depending on value

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10678]
## Current Behavior
I was setting up the salesforce connector, which has a boolean toggle. I set the toggle to false and it appeared like this: 
![Screen Shot 2022-02-27 at 7 39 00 PM](https://user-images.githubusercontent.com/6246757/155920089-b37c32d7-9d2e-4745-8456-a59ed2be0ebb.png)

When I set the toggle to true, the toggle's button was still on the left side. While the toggle's background turned blue, the toggle button itself did not move to the right: 
![Screen Shot 2022-02-27 at 7 39 40 PM](https://user-images.githubusercontent.com/6246757/155920149-ccb359c2-5fce-49a8-8eeb-f487267e9b7c.png)

## Expected Behavior
I expect the toggle button to move to the right/left when I toggle it on /off

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by sherifnada** [comment]
I also noticed this behavior happening on other toggles in the Ui e.g when selecting whether a stream should be synced or not in the connection settings page
