### ISSUE TITLE
Activated state when batch editing streams is not showing well

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10711]
Steps to reproduce:
* Go to the connection's Replication page
* Select a row for a stream, so the batch edit row is displayed
* Click on "activate" in the batch edit row
* Here's what is displayed: <img width="375" alt="Screen Shot 2022-02-28 at 9 56 42 AM" src="https://user-images.githubusercontent.com/68561602/156024965-025d509f-5a6a-45c7-afd8-80c6a85d92ef.png">
* The white circle didn't move, and the background should be a different purple so it is visible => see specs here: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=28448%3A108008

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/10678

This is already fixed on master, not yet deployed on cloud though.
