### ISSUE TITLE
Destination Oracle: custom JDBC parameters

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#10719]
## Tell us about the problem you're trying to solve
Add support for Oracle Destinations to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## Describe the solution you’d like
`AbstractJdbcDestination` can already handle jdbc parameters via the `jdbc_url_params` field, but the `OracleDestination` spec does not specify that field. We should update the spec to support additional jdbc parameters for Oracle destination

**Comment by oustynova** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/10719?planning-poker) with ZenHub @pcsoni89

**Comment by grishick** [comment]
What's the points estimate on this issue? IMHO Scoping Finished implies that we assigned the estimate.

**Comment by pcsoni89** [comment]
Tried setting up different source and GCS destination connector.
Not able to reproduce the issue (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;).
Looks like there was some issue while entering value for Access ID/secret key/GCS Bucket Path parameters.
Able to create connection for GCS destination for MySQL and data sync is done successfully.

**Comment by pcsoni89** [comment]
> 

Hi @grishick ,
By mistake i added comment here from a different ticket.
Sorry for inconvenience.
