### ISSUE TITLE
Destination Clickhouse: custom JDBC parameters

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#10717]
## Tell us about the problem you're trying to solve
Add support for MySQL Destinations to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## Describe the solution you’d like
`AbstractJdbcDestination` can already handle jdbc parameters via the `jdbc_url_params` field, but the `ClickhouseDestination` spec does not specify that field. We should update the spec to support additional jdbc parameters for Clickhouse destination

**Comment by etsybaev** [comment]
PR https://github.com/airbytehq/airbyte/pull/16444
