### ISSUE TITLE
The popup asking feedback after initial sync should only be displayed once if skipped

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10712]
Steps to reproduce: 
* Go through the onboarding and get a first successful sync
* Go back to Onboarding section, you will see this popup:
<img width="943" alt="Screen Shot 2022-02-28 at 10 00 17 AM" src="https://user-images.githubusercontent.com/68561602/156026272-94283460-f256-4552-a3c8-9d5acd5f386f.png">
* Click on Skip now
* Go to any other section (Connections)
* Go back to Onboarding, you will see that popup again. 

Suggested behavior: If I click on "Skip for now", I shouldn't see that popup again. Right now, the behavior is spammy. We could rename to "Skip" to be more explicit.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
