### ISSUE TITLE
Source Postgres: custom JDBC parameters

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#10729]
## Tell us about the problem you're trying to solve
Add support for Postgres Source to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## Describe the solution you’d like
`AbstractJdbcSource` can already handle jdbc parameters via the `connection_properties` field, but the source-postgres spec does not specify that field. We should update the spec to support additional jdbc parameters for Postgres source

**Comment by bleonard** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/10729?planning-poker) with ZenHub @grishick
