### ISSUE TITLE
Source MSSQL: custom JDBC parameters

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#10727]
## Tell us about the problem you're trying to solve
Add support for MSSQL Source to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## Describe the solution you’d like
`AbstractJdbcSource` can already handle jdbc parameters via the `connection_properties` field, but the source-mssql spec does not specify that field. We should update the spec to support additional jdbc parameters for MSSQL source

**Comment by alexandr-shegeda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/10727?planning-poker) with ZenHub @alexandertsukanov @etsybaev @VitaliiMaltsev @andriikorotkov @suhomud

**Comment by etsybaev** [comment]
Appears to be blocked by this ticket https://github.com/airbytehq/airbyte/issues/14628

**Comment by sashaNeshcheret** [comment]
Seems it is already resolved by [pr](https://github.com/airbytehq/airbyte/pull/11010) and can be closed as duplicate.
