### ISSUE TITLE
Destination Redshift: custom JDBC parameters

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#10721]
## Tell us about the problem you're trying to solve
Add support for Redshift Destinations to take in a JDBC URL Params input to specify any additional JDBC parameters for the connection.

This is a follow up to https://github.com/airbytehq/airbyte/pull/10421
This is part of https://github.com/airbytehq/airbyte/issues/9501

## Describe the solution you’d like
`AbstractJdbcDestination` can already handle jdbc parameters via the `jdbc_url_params` field, but the Redshift spec does not specify that field. We should update the spec to support additional jdbc parameters for redshift destination

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/10721?planning-poker) with ZenHub @tuliren @edgao @subodh1810
