### ISSUE TITLE
"Unknown error occurred" shows when trying to access a workspace without permissions

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10735]
When trying to access a workspace without permissions, this is what shows when the workspaces/get gets a 401:

![Screen Shot 2022-02-28 at 1 55 46 PM](https://user-images.githubusercontent.com/120362/156065162-cc7f663e-a6e3-4945-94d8-e8f8f97bcc06.png)

Ideally we would say that the user doesn't have permission to access the resource. Also, there should be something clickable that allows a user to get off the page for any error 401/unknown/etc, even if it only links to the root.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Discussed with frontend team. The solution is to display a message that you don't have access to this resource + CTA to return to the home page. Any more enhancements should be tracked as a separate issue.
