### ISSUE TITLE
Use of color instead of background color for the log prefix

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#10736]
## What

In the log display of a sync, some of the prefix are using a color instead of background color. It looks like a regression, and we need to understand how this has been introduced.

The affected prefix are `destination` and `source`. 

## Acceptance criteria

The prefix are using a background color instead of a color.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by benmoriceau** [comment]
[logs-7155.txt](https://github.com/airbytehq/airbyte/files/8157240/logs-7155.txt)
 This is a log example that contains the issue.

**Comment by benmoriceau** [comment]
![Screen Shot 2022-02-28 at 1 43 21 PM](https://user-images.githubusercontent.com/6792130/156067286-ab4b56a8-2848-4a76-8b35-2688ab6f991b.png)
