### ISSUE TITLE
Prepare MLP document for BigQuery Destination

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#10758]

**Comment by etsybaev** [comment]
https://docs.google.com/document/d/1uXNyQgnRdC64WVwfFKFcnd-Fmm6uAEe4FyXY5lxQybk/edit#

**Comment by alexandr-shegeda** [comment]
@misteryeo @sherifnada please review the MLP document for BigQuery Destination

**Comment by misteryeo** [comment]
Added some comments to clarify in the doc.

**Comment by misteryeo** [comment]
@alexandr-shegeda @etsybaev  This doc looks great. Let's use this as a template for destinations research moving forward - have included it as an example in the original doc.

As part of this epic https://github.com/airbytehq/airbyte/issues/10148 let's make sure to document the gaps that have been identified from the research. At a high level, I believe these should be:

Authentication gaps: SAML, Okta, Azure Active Directory, OAuth2
Data type gaps: Numeric, Bignumeric, Bytes

**Comment by etsybaev** [comment]
Created, thanks. Moving ticket to Airbyte Review

**Comment by sherifnada** [comment]
@etsybaev the tickets here https://github.com/airbytehq/airbyte/issues/11090 and https://github.com/airbytehq/airbyte/issues/11089 LGTM. Please move forward!
