### ISSUE TITLE
DX: SonarQube should pick up changes in branches

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#10750]
## Steps to Reproduce
1. Create PR
2. wait SQ report with errors
3. fix some of them and push changes
4. still have the same report with the same errors

## Are you willing to submit a PR?
no

**Comment by tuliren** [comment]
I think this is fixed? I remember recently the SonarQube report did get updated after I fixed some of the reported issues.

**Comment by davinchia** [comment]
Closing for now. Please reopen if this shows up again.
