### ISSUE TITLE
Dead links about licenses

### ISSUE THREAD

**Issue by dmikurube** [airbytehq/airbyte#10752]
### Tell us about the documentation you'd like us to add or update.

Hi, I found some dead links about Airbyte's licenses when I was reading through. Could you follow-up when you have time?

### If applicable, add links to the relevant docs that should be updated

* "FAQ" in https://docs.airbyte.com/project-overview/licenses
* Many links from https://docs.airbyte.com/project-overview/licenses/license-faq

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/airbytehq/airbyte/pull/12113
