### ISSUE TITLE
New Source Connector: Chargify

### ISSUE THREAD

**Issue by Javier162380** [airbytehq/airbyte#10792]
## Tell us about the new connector you’d like to have
* Which source and which destination?
Source: Chargify API (https://developers.chargify.com/docs/api-docs/YXBpOjE0MTA4MjYx-chargify-api). Chargify is a billing system, it already has a destination target for Airbyte (https://docs.airbyte.com/integrations/destinations/chargify), although it is not present as a source. 
I will like to have Chargify as a source connection for data modeling analysis.
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
No need to support the legacy API

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
 Finance data modeling
* How often do you want to run syncs?
   Daily.
* If this is an API source connector, which entities/endpoints do you need supported?
  Customers, Invoices, Subscriptions, Subscriptions Components and events
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
I already got an Airflow Operator with integration although I will like to have it present in Airbyte as well.

## Are you willing to submit a PR?

Yes!!!

**Comment by marcosmarxm** [comment]
Solved by https://github.com/airbytehq/airbyte/pull/10853
