### ISSUE TITLE
Reorganize Namespace fields in Connection Settings

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#10797]
## Tell us about the problem you're trying to solve
There are two fields related to setting the Namespace in the "Replication" tab of Connection Settings. They are listed one below the other. An additional input "Destination Stream Prefix (Optional)" is listed next to "Destination Namespace*". This is confusing to the user as they are unrelated to each other. 

## Describe the solution you’d like
The Namespace fields, since they are related to each other, should be clearly grouped in a way that shows they are related to each other. The field "Destination Stream Prefix (Optional)" should not be listed to the right of the Destination Namespace field, since they are not related to each other. In the past, the Namespace Custom Format was listed to the right of the Destination Namespace. 

Example screenshot of a connection: 
<img width="1016" alt="Screen Shot 2022-03-02 at 5 38 42 PM" src="https://user-images.githubusercontent.com/38087517/156406820-f43da42f-ed62-4268-a418-1a5c5e98aa4a.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
cc @upmitt

I wonder if we for now should simply change the order of those three boxes, and make it look as follows:

```
| Destination Namespace* | Namespace Custom Format |
| Destination Stream Prefix (Optional)                               |
```

**Comment by nataliekwong** [comment]
One detail I had not previously added was that the Namespace Custom Format box only appears if the user select "Custom" in the "Destination Namespace".  I believe it would still be intuitive for the user to see the "Custom" box show up to the right of the original one (vs the current solution which is below), but wanted to point that out and double check here with both of you.

Otherwise I see this as a good solution.

**Comment by andyjih** [comment]
From [this doc](https://docs.google.com/document/d/1RuaKrOr7zzCowtUGA4xItiYr-Nt5UcL3narNxKrvh-o/edit), sharing a small nit that these fields not being aligned looks a bit off to me.

![2022-04-11_17-34-31](https://user-images.githubusercontent.com/633226/163468006-9a9a0858-517d-44da-91f8-d9c54ef52e42.png)
