### ISSUE TITLE
After signing up and confirming email address, I should be redirected directly in my default workspace, and not be prompted to select a workspace

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#10819]
This page is confusing to the user and is not a necessary step to get our users to experience their first aha moment to sync data. 

![Screen Shot 2022-03-01 at 4 11 41 PM](https://user-images.githubusercontent.com/68561602/156470914-eec34e7b-78df-4d75-a6f4-73d76e11ecaa.png)

Impact expected:
* avoid users to create unnecessary workplace which will display 0 credits
* one less unncessary step in the onboarding

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
