### ISSUE TITLE
can you support `initialSetupComplete` in the create workspace API? 

### ISSUE THREAD

**Issue by yiyangli-heap** [airbytehq/airbyte#10834]
## Environment
- **Airbyte version**:  0.35.5-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Severity**: Low
- **Step where error happened**: 

## Current Behavior
- Create a new workspace, using the example https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/workspaces/create `displaySetupWizard` is false. 
- Get the workspace id from the payload, use it to access the workspace, for example, http://localhost:8000/workspaces/5c6f74ad-0c83-4c5a-8ab2-11e3ad32d169 
- You are asked to fill in the email and other settings again. If you fill in the form, the setup wizard shows up again. 
- this is the workaround. use the update API https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/workspaces/update, set `initialSetupComplete` to true. 
- The setting page will disappear, and the setup wizard doesn't show up. 

## Expected Behavior
- I guess the setup wizard is a state right after the initial setup page, it doesn't respect the setting of `displaySetupWizard` when I created a workspace using an api. 
- I am not able to include `initialSetupComplete` in the create API, it's not an allowed attribute. 
- I can't say this is a bug, I wish it could be a feature request to include `initialSetupComplete` in the create API. And if initialSetupComplete is true, the initial setting and following setup wizard won't show up. As a result, in order to create a clean workspace, I don't have to submit 2 requests. 

## Steps to Reproduce
1. Create a new workspace, using the example https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/workspaces/create `displaySetupWizard` is false. 
2. Get the workspace id from the payload, use it to access the workspace, for example, http://localhost:8000/workspaces/5c6f74ad-0c83-4c5a-8ab2-11e3ad32d169 

## Are you willing to submit a PR?
Yes, why not? Please advise.

**Comment by timroes** [comment]
Closing this, since this has since then been moved away a workspace configuration into the `/v1/instance_configuration/setup` API, which supports configuring this.
