### ISSUE TITLE
KLAVIYO: un-flattened columns in endpoint EVENTS

### ISSUE THREAD

**Issue by fortisoftware** [airbytehq/airbyte#10830]
The columns EVENTS.PERSON and EVENTS.EVENT_PROPERTIES are not flattened. I try making a custom dbt copying CAMPAIGNS.EXCLUDED_LISTS and it gives diferent json parsing errors.
They both have '$' at the beginning of some column names.

**Comment by fortisoftware** [comment]
They both hay '$' at the beggining of some column names.

**Comment by davydov-d** [comment]
@fortisoftware hey, could you please share the log file?

**Comment by fortisoftware** [comment]
Hello, there are no errors during synchronization or during normalization.
The problem is that basic normalization does not flatten columns (create a new table) that include fields that start with $.
The object has the following structure:
events.person = {
   "$address1": "",
   "$address2": "",
   "$city": "",
   "$country": "",
   "$email": "",
   "$first_name": "",
   "$id": "",
   "$last_name": "",
   "$latitude": 000,
   "$length": 000,
   "$organization": "",
   "$phone_number": "",
   "$region": "",
   "$timezone": "",
   "$title": "",
   "$zip": "",
   "MailChimp Rating": 0,
   "created": "2021-09-10 18:23:33",
   "email": "",
   "first_name": "",
   "id": "",
   "last_name": "",
   "object": "person",
   "updated": "2021-10-26 20:48:59"
}

Klaviyo places $ in front of certain special fields and the dbt is generated ignoring that it should flatten these columns.
When trying to do it ignoring those $ columns with the following code it fails:

------------------EVENTS_PERSON_AB1
{{ config(
    cluster_by = ["_AIRBYTE_EMITTED_AT"],
    schema = "_AIRBYTE_KLAVIYO",
    tags = [ "nested-intermediate" ]
) }}
-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: {{ ref('EVENTS') }}
{{ unnest_cte(ref('EVENTS'), 'EVENTS', 'PERSON') }}
select
    _AIRBYTE_EVENTS_HASHID,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['created'], ['created']) }} as CREATED,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['email'], ['email']) }} as EMAIL,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['first_name'], ['first_name']) }} as FIRST_NAME,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['id'], ['id']) }} as ID,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['last_name'], ['last_name']) }} as LAST_NAME,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['object'], ['object']) }} as OBJECT,
    {{ json_extract_scalar(unnested_column_value('PERSON'), ['updated'], ['updated']) }} as UPDATED,
    _AIRBYTE_AB_ID,
    _AIRBYTE_EMITTED_AT,
    {{ current_timestamp() }} as _AIRBYTE_NORMALIZED_AT
from {{ ref('EVENTS') }} as table_alias
-- PERSON at events/person
{{ cross_join_unnest('EVENTS', 'PERSON') }}
where 1 = 1
and PERSON is not null


------------------EVENTS_PERSON_AB2
{{ config(
    cluster_by = ["_AIRBYTE_EMITTED_AT"],
    schema = "_AIRBYTE_KLAVIYO",
    tags = [ "nested-intermediate" ]
) }}
-- SQL model to cast each column to its adequate SQL type converted from the JSON schema type
-- depends_on: {{ ref('EVENTS_PERSON_AB1') }}
select
    _AIRBYTE_EVENTS_HASHID,
    cast(EMAIL as {{ dbt_utils.type_string() }}) as EMAIL,
    cast(FIRST_NAME as {{ dbt_utils.type_string() }}) as FIRST_NAME,
    cast(ID as {{ dbt_utils.type_string() }}) as ID,
    cast(LAST_NAME as {{ dbt_utils.type_string() }}) as LAST_NAME,
    cast(OBJECT as {{ dbt_utils.type_string() }}) as OBJECT,
    case
        when CREATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}(\\+|-)\\d{4}' then to_timestamp_tz(CREATED, 'YYYY-MM-DDTHH24:MI:SSTZHTZM')
        when CREATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}(\\+|-)\\d{2}' then to_timestamp_tz(CREATED, 'YYYY-MM-DDTHH24:MI:SSTZH')
        when CREATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}\\.\\d{1,7}(\\+|-)\\d{4}' then to_timestamp_tz(CREATED, 'YYYY-MM-DDTHH24:MI:SS.FFTZHTZM')
        when CREATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}\\.\\d{1,7}(\\+|-)\\d{2}' then to_timestamp_tz(CREATED, 'YYYY-MM-DDTHH24:MI:SS.FFTZH')
        when CREATED = '' then NULL
    else to_timestamp_tz(CREATED)
    end as CREATED
    ,
    case
        when UPDATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}(\\+|-)\\d{4}' then to_timestamp_tz(UPDATED, 'YYYY-MM-DDTHH24:MI:SSTZHTZM')
        when UPDATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}(\\+|-)\\d{2}' then to_timestamp_tz(UPDATED, 'YYYY-MM-DDTHH24:MI:SSTZH')
        when UPDATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}\\.\\d{1,7}(\\+|-)\\d{4}' then to_timestamp_tz(UPDATED, 'YYYY-MM-DDTHH24:MI:SS.FFTZHTZM')
        when UPDATED regexp '\\d{4}-\\d{2}-\\d{2}T(\\d{2}:){2}\\d{2}\\.\\d{1,7}(\\+|-)\\d{2}' then to_timestamp_tz(UPDATED, 'YYYY-MM-DDTHH24:MI:SS.FFTZH')
        when UPDATED = '' then NULL
    else to_timestamp_tz(UPDATED)
    end as UPDATED
    ,
    _AIRBYTE_AB_ID,
    _AIRBYTE_EMITTED_AT,
    {{ current_timestamp() }} as _AIRBYTE_NORMALIZED_AT
from {{ ref('EVENTS_PERSON_AB1') }}
-- PERSON at events/person
where 1 = 1


------------------EVENTS_PERSON_AB3
{{ config(
    cluster_by = ["_AIRBYTE_EMITTED_AT"],
    schema = "_AIRBYTE_KLAVIYO",
    tags = [ "nested-intermediate" ]
) }}
-- SQL model to build a hash column based on the values of this record
-- depends_on: {{ ref('EVENTS_PERSON_AB2') }}
select
    {{ dbt_utils.surrogate_key([
        '_AIRBYTE_EVENTS_HASHID',
        'ID',
        'FIRST_NAME',
        'LAST_NAME',
        'EMAIL',
        'OBJECT',
        'CREATED',
        'UPDATED',
    ]) }} as _AIRBYTE_EVENTS_PERSON_HASHID,
    tmp.*
from {{ ref('EVENTS_PERSON_AB2') }} tmp
-- PERSON at events/person
where 1 = 1


------------------EVENTS_PERSON
{{ config(
    cluster_by = ["_AIRBYTE_EMITTED_AT"],
    schema = "KLAVIYO",
    tags = [ "nested" ]
) }}
-- Final base SQL model
-- depends_on: {{ ref('EVENTS_PERSON_AB3') }}
select
    _AIRBYTE_EVENTS_HASHID,
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME,
    OBJECT,
    CREATED,
    UPDATED,
    _AIRBYTE_AB_ID,
    _AIRBYTE_EMITTED_AT,
    {{ current_timestamp() }} as _AIRBYTE_NORMALIZED_AT,
    _AIRBYTE_EVENTS_PERSON_HASHID
from {{ ref('EVENTS_PERSON_AB3') }}
-- PERSON at events/person from {{ ref('CAMPAIGNS') }}
where 1 = 1

The error is the following:
2022-07-19 15:05:51 [45mdbt[0m > 15:05:51 | 10 of 10 ERROR creating table model KLAVIYO.EVENTS_PERSON.................................................... [[31mERROR[0m in 1.63s]
2022-07-19 15:05:53 [45mdbt[0m > 15:05:53 | 9 of 10 OK created table model KLAVIYO.EVENTS_EVENT_PROPERTIES............................................... [[32mSUCCESS 1[0m in 3.47s]
2022-07-19 15:05:53 [45mdbt[0m > 15:05:53 |
2022-07-19 15:05:53 [45mdbt[0m > 15:05:53 | Finished running 10 table models in 33.69s.
2022-07-19 15:05:53 [45mdbt[0m >
2022-07-19 15:05:53 [45mdbt[0m > [31mCompleted with 1 error and 0 warnings:[0m
2022-07-19 15:05:53 [45mdbt[0m >
2022-07-19 15:05:53 [45mdbt[0m > [33mDatabase Error in model EVENTS_PERSON (models/generated/airbyte_tables/KLAVIYO/EVENTS_PERSON.sql)[0m
2022-07-19 15:05:53 [45mdbt[0m >  000904 (42000): SQL compilation error: error line 113 at position 4
2022-07-19 15:05:53 [45mdbt[0m >  invalid identifier '_AIRBYTE_LISTS_HASHID'
2022-07-19 15:05:53 [45mdbt[0m >  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/KLAVIYO/EVENTS_PERSON.sql
2022-07-19 15:05:53 [45mdbt[0m >
2022-07-19 15:05:53 [45mdbt[0m > Done. PASS=9 WARN=0 ERROR=1 SKIP=0 TOTAL=10
2022-07-19 15:05:54 [32mINFO[m i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):158 - Completing future exceptionally...


In order to make it work for a snowflake DB we used this code:


------------------EVENTS_PERSON
{{ config(materialized='table') }}
with
EVENTS_PERSON_0 AS (
SELECT
PERSON:id as ID,
PERSON:email as EMAIL,
PERSON:first_name  as FIRST_NAME,
PERSON:last_name  as LAST_NAME,
PERSON:object  as OBJECT,
PERSON:created  as CREATED,
PERSON:updated  as UPDATED,
PERSON:{{ adapter.quote('MailChimp Rating') }} as MAILCHIMP_RATING,
_AIRBYTE_EMITTED_AT,
_AIRBYTE_AB_ID
from {{ref('EVENTS')  }})
SELECT
cast(ID as {{ dbt_utils.type_string() }}) as ID,
cast(EMAIL as {{ dbt_utils.type_string() }}) as EMAIL,
cast(FIRST_NAME as {{ dbt_utils.type_string() }}) as FIRST_NAME,
cast(LAST_NAME as {{ dbt_utils.type_string() }}) as LAST_NAME,
cast(OBJECT as {{ dbt_utils.type_string() }}) as OBJECT,
cast(CREATED as timestamp) as CREATED,
cast(UPDATED as timestamp) as UPDATED,
cast(MAILCHIMP_RATING as {{ dbt_utils.type_string() }}) as MAILCHIMP_RATING,
_AIRBYTE_EMITTED_AT,
_AIRBYTE_AB_ID
FROM EVENTS_PERSON_0
where ID is not null    --#Uncomment to remove records with null `id` values

**Comment by davydov-d** [comment]
@fortisoftware thanks for the detailed response.
Indeed, Klaviyo puts the `$` symbol in front of the default fields names. But that's not the reason of the problem you have faced.

The explanation to why dbt does not create a separate table for the events.person sub-entity is it has no schema - just a generic dict. I guess that's because person, as well as event_properties is an entity with dynamic schema - fields can be added, edited and removed (except for defaults).

To help you solve the dbt error I need to see your full `models/generated/airbyte_tables/KLAVIYO/EVENTS_PERSON.sql` please (it says the error originates from there)
 ```
2022-07-19 15:05:53 [45mdbt[0m > 000904 (42000): SQL compilation error: error line 113 at position 4
2022-07-19 15:05:53 [45mdbt[0m > invalid identifier '_AIRBYTE_LISTS_HASHID'
2022-07-19 15:05:53 [45mdbt[0m > compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/KLAVIYO/EVENTS_PERSON.sql
```

**Comment by davydov-d** [comment]
So I'm closing this one as the connector behaves as expected

**Comment by fortisoftware** [comment]
Hi thank you,
Sorry for the delay.
