### ISSUE TITLE
Source Github: deprecate "page size" input parameter

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10847]
## Tell us about the problem you're trying to solve
Like mentioned in the [UX handbook](https://docs.airbyte.io/connector-development/ux-handbook) this parameter is asking the user for input about an implementation detail. The user has no way of knowing what the right value for this parameter should be. 
<img width="773" alt="Screen Shot 2022-03-04 at 12 15 06 AM" src="https://user-images.githubusercontent.com/6246757/156725308-17defa09-7f46-48a9-8d8c-2f7a1c2a4f14.png">

## Describe the solution you’d like
Remove that option and use a sane value by default.

**Comment by grubberr** [comment]
Current usage statistic on cloud:

| Page Size | Usage |
|----------|----------|
| 1  | 1  |
| 5  | 1  |
| 10  | 449  |
| 12  | 1  |
| 15  | 4  |
| 20  | 11 |
| 25  | 3 |
| 30 | 26 |
| 50 | 1 |
| 100 | 2 |

**Comment by grubberr** [comment]
@sherifnada 

1. I propose to remove "page size" from the config and use the default page_size: 10
because it's the most popular value on airbyte cloud 

2. We can also still get PAGE_SIZE  from `os.environ` to allow tuning this parameter for experts

What do you think about (1) and (2)?

**Comment by GAHila** [comment]
I think this is not a good idea. My company just went through initial load of an org that has 20k repos and we'd hit the rate limit way more often if we did not increase the page size.

**Comment by SerhiiChvaliuk-cnic** [comment]
@GAHila 

> I think this is not a good idea. My company just went through initial load of an org that has 20k repos and we'd hit the rate limit way more often if we did not increase the page size.

Can you understand from logs what stream was rate-limited ?

tag: @sherifnada @lazebnyi

**Comment by grubberr** [comment]
@GAHila 

> I think this is not a good idea. My company just went through initial load of an org that has 20k repos and we'd hit the rate limit way more often if we did not increase the page size.

Can you understand from logs what stream was rate-limited ?

tag: @sherifnada @lazebnyi
