### ISSUE TITLE
UI prematurely reporting a connection is successful

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10842]
## Current Behavior
I cretaed a new connection and started a sync. The sync will run for a long time. But when I clicked "connections" on the left side of the UI the connecton has a checkmark next to it: 
![Screen Shot 2022-03-03 at 10 38 18 AM](https://user-images.githubusercontent.com/6246757/156630741-a1de41ae-bb92-4fc9-8714-82f3ac80e604.png)

This made me think the sync succeeded

However when I clicked through, the sync is still running:  
![Screen Shot 2022-03-03 at 10 38 27 AM](https://user-images.githubusercontent.com/6246757/156630836-c4bd060d-cae2-4a07-bab1-fa49675e1fd5.png)

seeing as no sync was previously successful, it was confusing to see the green checkmark

## Expected Behavior
I would prefer that there is a buffering icon or something similar if a connection had never succeeded its first sync

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
I agree. Currently this icon only shows if a connection is paused, never ran, or in all other cases successfull. I think it would make sense to better represent the state of the latest sync that has happened (or is still running) in this view.

@misteryeo Do you remember any reason why we shouldn't show the "current"/"last" state in the connection overview, but just this simplified version? If not, I'd suggest we change it as Sherif mentioned.

An implementation note: when we fix this we should also cleanup the `StatusIcon` component. It's currently using 4 booleans to represent a single available enum state. This makes it easier to potentially misuse this component in an unintended way.

**Comment by misteryeo** [comment]
Nope, I don't have context on this actually. May have been created before my time but I agree with Sherif's suggestion here.

**Comment by andyjih** [comment]
It sounds like we need some new status icons. After digging through with Edmundo a bit, here's what we need:

**current**
no recent run yet => Empty (white :no_entry_sign: on yellow bg)
most recent run `failed` => Failed (white :x: on red bg)
most recent run `succeeded`  => Active (:white_check_mark:)

**proposal**
most recent run `cancelled` -> same white X on red bg as failed
most recent run `pending` | `running`  -> something new (@Upmitt - have any thoughts?). A very quick fix would be to show an ellipsis `...` in a circle.

**Comment by timroes** [comment]
For pending | running I'd suggest we simply make the icon a loading spinner instead, which imho indicates best this is still in progress. That way we can also better have a loading spinner in front of the actual current run when looking at a specific connection.

**Comment by Upmitt** [comment]
Figma is updated, with missing icon > https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP?node-id=33424%3A159804 . I join the animated svg for pending/running
![airbyte_pending_2](https://user-images.githubusercontent.com/29780098/164018406-2b1477b8-bcff-4aff-80fc-62ea8e5a7c63.svg)

**Comment by sherifnada** [comment]
agreed w tim, the proposed icon 🚫 makes it seem like something is wrong

**Comment by Upmitt** [comment]
Agreed with tim and sherif - What about this kind of icon suggestion ?
<img width="656" alt="Screenshot 2022-04-22 at 11 16 53" src="https://user-images.githubusercontent.com/29780098/164676560-50668b82-5277-49b5-9a5f-3afea43ebc61.png">
