### ISSUE TITLE
New Source: Display&Video 360

### ISSUE THREAD

**Issue by iberchid** [airbytehq/airbyte#10850]
## Tell us about the new connector you’d like to have
- source connector for [DoubleClick Bid Manager API](https://developers.google.com/bid-manager/v1.1) of Display & Video 360

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
Tracking and reporting on websites & ads performance for better marketing campaigns optimization.

* How often do you want to run syncs? 
Daily

* If this is an API source connector, which entities/endpoints do you need supported?: 
https://www.googleapis.com/doubleclickbidmanager/v1.1

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
We are currently using another service provider, but we would like to use Airbyte instead.

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/2984
