### ISSUE TITLE
Variable input fields renders as a list of keys

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10858]
Currently a list of items, e.g. in the Salesforce source connector will just render as a list of array indexes after created:

![screenshot-20220304-183349](https://user-images.githubusercontent.com/877229/156813278-c667db4c-a8e5-42fa-8a98-3a3ef8fcbe30.png)

This issue keeps track of fixing this. We most likely want to improve the overall look and feel of that component at the same time and have some designs still in discussion for this.

cc @misteryeo

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Variable Input Listed as Keys](https://app.harvestr.io/components/0/list/Sj07lZcYY)

**Comment by andyjih** [comment]
Designs here: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP?node-id=34120%3A189267

Option 3 is my preference.

**Comment by timroes** [comment]
This is unfortunately not generic enough as a design for us to work in auto generated UIs. I'll leave some comments in the Figma, so we can reiterate over this.

**Comment by edmundito** [comment]
After reviewing, we agreed on option 4. See figma prototype.
