### ISSUE TITLE
Source Jira: add section explaining how to use custom fields

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#10871]
### Tell us about the documentation you'd like us to add or update.
From Slack discussion: https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1646138392039319
Looks the custom fields are really complex to be used in Jira connector.
Some fields are array and you need to request a pair or a hierarchy to start working.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by gcareri** [comment]
Hi everyone, 
Is there a documentation how to use custom fields on Jira?
Thanks

**Comment by grubberr** [comment]
In this PR https://github.com/airbytehq/airbyte/pull/20128 we have removed `additional_fields` params 
The `issues` stream returns just `*all` fields including custom fields too

**Comment by grubberr** [comment]
closed because of https://github.com/airbytehq/airbyte/pull/20128
