### ISSUE TITLE
Display cursor field when it is source defined

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10870]
## Tell us about the problem you're trying to solve
On the connection setup page (or connection settings > replication page), when a cursor is defined by the source, the UI displays `<sourceDefined>`. I think we can make this more informative by displaying the actual cursor field, to give the user more visibility on how the product is working. 
![Screen Shot 2022-03-04 at 1 43 20 PM](https://user-images.githubusercontent.com/6246757/156845820-81ecd3b6-a497-4112-8f17-e7ef91f3fb20.png)

## Describe the solution you’d like
I want `<sourceDefined>` to be replaced by the actual cursor field name

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by cgardens** [comment]
@sherifnada The source doesn't expose what the cursor field is externally. The idea here was to give source writers latitude. Was this the wrong tradeoff?

**Comment by sherifnada** [comment]
@cgardens in many cases it is actually exposed. Could we display in the UI if defined, otherwise show the current display?

**Comment by cgardens** [comment]
how is it exposed? default cursor field?

I'm intentionally being a little dense here. The contract in the protocol is [here](https://docs.airbyte.com/understanding-airbyte/catalog#logic-for-resolving-the-cursor-field). Sounds like you are suggesting a change to the protocol (even if it is reusing existing fields). Can you walk me through what that should look like? Do we need to expose multi-column cursor fields in this case? Is there a quick win you want to go for?

**Comment by sherifnada** [comment]
I am not suggesting a change to the protocol (or maybe we've just been using the protocol wrong!). If the cursor is source defined, it will be made available in the `default_cursor_field` property in the CDK. So the logic I am suggesting is for the UI to look at this field and if it is available, display that as the actual cursor field. 

We do not need to expose multi-column cursor fields (i believe that concept doesn't exist anywhere in the protocol at the moment), at least not for this request. 

Does that clarify?

**Comment by sherifnada** [comment]
@timroes any thoughts on thsi?

**Comment by timroes** [comment]
@sherifnada that sounds reasonable to me. Just to summarize, to make sure we're on the same page:

Actual server/protocol behavior stays unchanged, i.e.`source_defined_cursor` defines on whether the internal cursor is used or not. If this field is set to `true`, the UI should look into `default_cursor_field` which _should_ include the name of the field that the source will be using internally and show it (but doesn't allow for editing it). If that field (for some reason) might not be set, we show the "<source defined>" (or something more clear) instead.
