### ISSUE TITLE
normalization failed with ` Duplicate row detected during DML action` 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#10886]
## Current Behavior
Sync from google search console to snowflake fails with  `Duplicate row detected during DML action` during normalization.

## Logs
[logs-64315.txt](https://github.com/airbytehq/airbyte/files/8193267/logs-64315.txt)

## Steps to Reproduce
unsure, got this from a user workspace

**Comment by grishick** [comment]
Exit criteria: 
- repro scenario (test or workspace)
- issue filed with details on what needs to be fixed

Estimate/timebox: L (one sprint)

Best case scenario: something in Google source is causing this.

**Comment by etsybaev** [comment]
Similar to https://github.com/airbytehq/airbyte/issues/10189

**Comment by grishick** [comment]
@etsybaev is the problem that PK is incorrectly defined by the source?

**Comment by etsybaev** [comment]
@grishick have no idea for now. Wan't able to reproduce it yet. Maybe it's already fixed...

**Comment by etsybaev** [comment]
@grishick, I see you already closed this ticket. Should we also close this one https://github.com/airbytehq/airbyte/issues/10189 ? It seems to be similar - same source, same destination. I wasn't able to find anything similar for last months in Sentry.  
I also tried to run sync in different ways numerous times, but all syncs passed. Thanks
![image](https://user-images.githubusercontent.com/4688354/215933269-a08d1e0e-bafb-49a3-87a4-96f6455a23dd.png)
