### ISSUE TITLE
New Source Connector: TiDB

### ISSUE THREAD

**Issue by zhangyangyu** [airbytehq/airbyte#10891]
## Tell us about the new connector you’d like to have

Sources: [TiDB](https://github.com/pingcap/tidb)

## Describe the context around this new connector

TiDB ("Ti" stands for Titanium) is an open-source NewSQL database that supports Hybrid Transactional and Analytical Processing (HTAP) workloads. It is MySQL compatible and features horizontal scalability, strong consistency, and high availability. Besides OP deployment, it also has a [DbaaS cloud service](https://tidbcloud.com/).

Currently, TiDB supportes moving data from/to several other systems like MySQL/Aurora/Kafka, but types are very limited. Embracing Airbyte could open more possibilities.

TiDB is MySQL-compatible why not directly use MySQL connector? It's compatible but not 100% compatible. For example it has a `METRICS_SCHEMA` builtin database we don't want to migrate. It also does not have MySQL binlog.

## Describe the alternative you are considering or using

Nope.

## Are you willing to submit a PR?

We are going to develop the connector ourselves.

**Comment by troyyyang** [comment]
do you know if the mysql destination works for TiDB?

**Comment by Daemonxiao** [comment]
@troyyyang Since dbt-mysql used in mysql-destination is incompatible with TiDB, mysql-destination cannot be used for TiDB. Now TiDB has its own [dbt-tidb](https://github.com/pingcap/dbt-tidb). We will launch Airbyte tidb-destination in the future, and you can try it.

**Comment by troyyyang** [comment]
@Daemonxiao awesome to hear, I'll keep an eye out for the airbyte tidb destination!

**Comment by zhangyangyu** [comment]
@troyyyang We've contributed the TiDB destination connection already!

**Comment by zhangyangyu** [comment]
@marcosmarxm Any hints on how to get TiDB logo in this page? https://airbyte.com/connectors?connector-categories=databases
