### ISSUE TITLE
CDK: explain how to order fields in spec.json

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10894]
> Hello team !
> Is there a way to specify the order of the properties in spec.json?.
> Properties appear randomly in UI. I want it to appear in certain order like mandatory fields first, followed by optional.

Created from Slack: https://airbytehq-team.slack.com/archives/C01VDDEGL7M/p1644469471106649?thread_ts=1644469471.106649&cid=C01VDDEGL7M

**Comment by sherifnada** [comment]
described in https://docs.airbyte.com/connector-development/connector-specification-reference
