### ISSUE TITLE
Airbyte Connector development script generator

### ISSUE THREAD

**Issue by SriramThumma** [airbytehq/airbyte#10892]
## Tell us about the problem you're trying to solve
The existing documentation of airbyte for connector development is a bit confusing and not user friendly if some one is starting to create the new connector by editing the specs.json or source.py scripts which is a manual process and there is a scope for human errors and that drives the number of slack community requests for airbyte errors during the connector development process.

## Describe the solution you’d like
I would like to suggest a connector development script generator where if we provide the required details about the API/application, it would generate the specs.json or source.py or any other files automatically

## Describe the alternative you’ve considered or used
Right now , we are editing the default scripts that gets generated when a new connector is need to be developed.

## Are you willing to submit a PR?
Yes

**Comment by timroes** [comment]
This is nowadays possible via the [Connector Builder](https://docs.airbyte.com/connector-development/connector-builder-ui/overview), which allows easy configuration of an upstream API within the Airbyte UI.
