### ISSUE TITLE
Updating Source Settings resets sync frequency to manual

### ISSUE THREAD

**Issue by iainad** [airbytehq/airbyte#1089]
## Expected Behavior
When updating the settings on a source the sync frequency should reflect that selected on the UI whether changed or not

## Current Behavior
When `Save changes` is clicked on the sync settings screen (after making an update of any field) the sync settings are set to manual once the update completes.

The post sent to the `/update` endpoint has the payload:

```
{
  connectionId: "uuid",
  schedule: null,
  status: "active",
  syncSchema: { streams: [ <schema info >] }
}
```

The `schedule` is null in all cases no matter what the sync frequency selected on the select element.

## Steps to Reproduce
1. Create a new source 
1. Set it's frequency to a non manual option
1. Allow it to create
1. Once created move to the settings page
1. Make a change - e.g. change the frequency or any other setting
1. Click on save changes

The post succeeds and no error message is shown but the Select element remains on the previously selected frequency. If you navigate away and then back the frequency is then set to `manual`.

The only way to fix this is to delete and recreate the source and set a new sync frequency on 

## Severity of the bug for you
High

## Additional context
0.5.3-alpha / Running in GCP

**Comment by cgardens** [comment]
@iainad - hiya. first of all sorry for the slow response here, I somehow didn't see this issue. one of us will try to reproduce this tomorrow and make sure we have a fix for you by end of the day.

**Comment by cgardens** [comment]
@iainad - i spent some time trying to replicate this this morning but was not able to on the current version. I think the issue you were seeing in 0.5.3-alpha. was fixed in 0.6.0-alpha. I think it was the same underlying issue as we saw in this issue https://github.com/airbytehq/airbyte/issues/914 which was fixed in that version. would you mind jumping up to the new version and seeing if that resolves your issue?

**Comment by iainad** [comment]
@cgardens ok will do - is there an easy way to upgrade other than restarting from scratch?

**Comment by cgardens** [comment]
@iainad - while we're in alpha we unfortunately do not have great guarantees around upgrades from version to version. once we get out of alpha we will make sure to have an upgrade plan to making moving from version to version seamless. the thing that is most likely going to work is pulling master and starting from scratch. is that going to be painful for you at this point?

**Comment by iainad** [comment]
@cgardens ok I can confirm that `VERSION=0.6.0-alpha` has solved this issue when I created a new instance and reconnected Stripe.

**Comment by cgardens** [comment]
woohoo! Thanks @iainad. Glad it's working now. Let us know if you run into any other problems.
