### ISSUE TITLE
Source slack: explain how to refresh the token

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10901]
> I'm trying to pull data from Slack, but I keep getting "check connection failed". I've set up the app/bot as the docs have described, input the client ID, client secret, and bot user oauth token as the "access token". the docs don't describe how to get the refresh token, which i assume might be causing the connection break, but it's also not required... has anyone had similar issues?

Created from Slack: https://airbytehq.slack.com/archives/C01MFR03D5W/p1640620272396600?thread_ts=1640620272.396600&cid=C01MFR03D5W

**Comment by YowanR** [comment]
I will take a stab at this and will update once I have updated instructions

**Comment by YowanR** [comment]
Hi all, I don't believe there is any actions for us to take. As per the Slack link, the refresh token is optional so it is not required be default. Slack created OAuth in such a way that you can only use the access_token. You will need Refresh token only if you have the [Token rotation function enabled](https://api.slack.com/authentication/rotation). If you have this function enabled, then at the moment of access_token generation, you will also receive refresh_token in the same response body (more details about OAuth for Slack are described [here](https://api.slack.com/authentication/oauth-v2), and an example of the response body when receiving access_token you can see [here](https://api.slack.com/authentication/oauth-v2#exchanging) - the refresh_token should also come in the same body of the response, if you have Token rotation enabled)
In a word, if the Refresh Token is not part of the body of the response, then you have disabled the Token rotation function and you do not need to specify it to work with Airbyte. I've created a PR to update the doc. Will close this issue once the PR has been merged.

**Comment by YowanR** [comment]
Closing as [#15995](https://github.com/airbytehq/airbyte/pull/15995) has been merged with master.
