### ISSUE TITLE
Destination Bigquery: more details about GCS/BigQuery required permissions

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10902]
> 1. The exact permissions needed for GCS (for BigQuery staging) were a bit confusing. I think there's an open issue about the multipart upload being required already?
> 2. Same for the permissions for BigQuery. This could be made more obvious in the docs

Created from Slack: https://airbytehq.slack.com/archives/C019WJFR1JT/p1640892635138800

**Comment by andriikorotkov** [comment]
@alafanechere, about 1 item in this task - Charles added part to the doc with link to a BigQuery documentation and with list of needed GCS permissions  (these changes merged on 07.01.22). As for me, this is a good description of this item. I've added a similar list of permits needed to work with BigQuery, and added a link to the documentation with information about which permits apply to each role. We also already had links on how to create a service account and step-by-step instructions on how to set up an account. These changes will be added with this pull request - https://github.com/airbytehq/airbyte/pull/11238. Please, if you have comments and suggestions regarding the documentation, write them in this issue and I will try to process and add them to the documentation.
