### ISSUE TITLE
Destination GCS:  doc error using path with final /

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10912]
> Hi team! I am experiencing an error when attempting to send data to the GCS connector. No matter what source I use, I get the same error, and I can’t tell what it means. Can someone please have a look and see if anything jumps out? Logs in :thread:

Created from Slack: https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1642630442293300?thread_ts=1642630442.293300&cid=C01MFR03D5W

**Comment by pcsoni89** [comment]
Tried setting up different source and GCS destination connector.
Not able to reproduce the issue (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;).
Looks like there was some issue while entering value for Access ID/secret key/GCS Bucket Path parameters.
Able to create connection for GCS destination with MySQL source and data sync is done successfully.

**Comment by pcsoni89** [comment]
Hi @alafanechere ,

Have tried setting up connection with GCS destination, Observations are as below : 
(1) When we are trying to append "/" at last in "GCS Bucket Path" parameter, can see that validation is added for it.
Screen shot attached.

(2) Able to sync data for MySql (source) and GCS (destination).Screen shot attached for this as well.

Please help to have a look and share your input.
