### ISSUE TITLE
Zendesk Support: Get logs for failing connector

### ISSUE THREAD

**Issue by pgovind** [airbytehq/airbyte#10920]
## Environment
- **Airbyte version**:  0.32.1-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 0.1.4
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
UI reports: Unknown Error Occurred

## Expected Behavior
The UI sets up a new source

## Logs
*If applicable, please upload the logs from the failing operation. 
Not sure how to get the logs when Airbyte attemps to set up a new connection. If somebody can point out the steps, I'm happy to perform them. I can get to some server logs from the Airbyte UI: settings->configuration->Download server logs, but I'm not sure how useful those are. I can upload them here if someone wants to see them.

## Steps to Reproduce
1. Set up a Zendesk Support connection from the UI

## Are you willing to submit a PR?
No

My question: How do I know what is failing when setting up this connector? If I can get to the logs, I could try to figure out what is wrong with the setup.

**Comment by misteryeo** [comment]
@pgovind are you able to share a screenshot of what you're seeing as you try to setup a connector? Can you please have your console open for us to see any errors thrown there as well? Thanks!

**Comment by bazarnov** [comment]
@pgovind
As an option, please try to update the connector version in `Settings > Sources` to the latest version available and try to set up the source.

**Comment by bazarnov** [comment]
Closed for now. Please re-open the issue, once the problem persist.
