### ISSUE TITLE
Source Typeform Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10947]
The centralized hub for all feature requests and bugs associated with the [Typeform Source](https://docs.airbyte.com/integrations/sources/typeform) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/21).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | Need `Webhooks`, `Workspaces`, `Images`, `Themes` implemented | | | @itaseskii | ❌ | $300 |
| Incremental Sync | | | | | ✔️ | - |
| Pagination | | | | | ✔️ | - |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-typeform/unit_tests) - Coverage seems to be limited, needs more triage. | | | @itaseskii | ❌ | $300 |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | Needs description of steps in Airbyte UI. | | | | ❌ | $100 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Logs are not being returned from the connector. |  | [Issue](https://github.com/airbytehq/airbyte/issues/8817) | | | ❌ | $100 |
</details>

**Comment by itaseskii** [comment]
Hey @avaidyanatha I would like to wrap up the last unit tests coverage task left. Can you please assign it on me?

**Comment by itaseskii** [comment]
Going through the [reference](https://developer.typeform.com/get-started/) API documentation it seems that the connector is missing the following streams:
* **_Webhooks_** -> https://api.typeform.com/forms/{form_id}/webhooks
* **_Workspaces_** -> https://api.typeform.com/workspaces
* **_Images_** -> https://api.typeform.com/images
* **_Themes_** > https://api.typeform.com/themes

@avaidyanatha Can we sync the **_Full Stream Coverage_** requirement and add the appropriate bounty?

**Comment by avaidyanatha** [comment]
@itaseskii Done! Thank you for scoping this out :)

**Comment by itaseskii** [comment]
@avaidyanatha I would like to start working on adding full stream coverage for the Typeform connector next.

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
