### ISSUE TITLE
Source Freshdesk Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10948]
The centralized hub for all feature requests and bugs associated with the [Freshdesk Source](https://docs.airbyte.com/integrations/sources/freshdesk) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/22).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Migrate to new CDK | Triage needed ([Issue](https://github.com/airbytehq/airbyte/issues/11456)). | | | | ❌ | $500 |
| Full Stream Coverage | Triage needed. | [Issue with all required streams.](https://github.com/airbytehq/airbyte/issues/1387)| | | ❌ | $300 |
| Incremental Sync | | | | | ✔️ | - |
| Pagination | | | | | ✔️ | - |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-freshdesk/unit_tests) - Needs more triage. | | | | ❌ | $300 |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | Currently a stub. | | | | ❌ | $100 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
</details>

**Comment by itaseskii** [comment]
#11456

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
