### ISSUE TITLE
Source Bing Ads Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10946]
The centralized hub for all feature requests and bugs associated with the [Bing Ads Source](https://docs.airbyte.com/integrations/sources/bing-ads) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/20).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | Triage required. | | | |❓| - |
| Incremental Sync | | | | | ❌ | $300 |
| Pagination | | | | | ❌ | $200 |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-bing-ads/unit_tests) | | | | ✔️ | - |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | Formatting and clarity can be improved. | | | | ✔️ | - |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Change Account ID to User ID |  | [Issue](https://github.com/airbytehq/airbyte/issues/9972) | | | ❌ | $100 |
</details>

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
