### ISSUE TITLE
Source Google Analytics Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10941]
The centralized hub for all feature requests and bugs associated with the [Google Analytics Source](https://docs.airbyte.com/integrations/sources/google-analytics-v4) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/2).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | [Issue](https://github.com/airbytehq/airbyte/issues/10049) | | | | ❌ | $300 |
| Incremental Sync | | | | | ✔️ | - |
| Pagination | | | | | ✔️ | - |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-google-analytics-v4/unit_tests) | | | | ✔️ | - |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | | | | | ✔️ | - |
| Getting Started Guide | | | | | ✔️ | - |
| Filters and Segments for API Payload | | [Issue](https://github.com/airbytehq/airbyte/issues/6305) | | | ❌ | $200 |
| Allow Running w/o View ID | | [Issue](https://github.com/airbytehq/airbyte/issues/6326) | | | ❌ | $200 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
</details>

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
