### ISSUE TITLE
Source Google Search Console Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10943]
The centralized hub for all feature requests and bugs associated with the [Google Search Console Source](https://docs.airbyte.com/integrations/sources/google-search-console) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/15).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | Triage necessary. | | | | ❓ | - |
| Incremental Sync | | | | | ✔️ | - |
| Pagination | | | | | ❌ | $200 |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-google-search-console/unit_tests) | | | | ✔️ | - |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | This is technically done, but could use some improvements. | | | | ✔️ | - |
| Support working with a Domain Property | | [Issue](https://github.com/airbytehq/airbyte/issues/8387) | | | ❌ | $200 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Allow removal of the `end_date` param |  | [Issue](https://github.com/airbytehq/airbyte/issues/8060) | | | ❌ | $100 |
| Allow `end_date` param to be blank | Potentially related with above issue. | [Issue](https://github.com/airbytehq/airbyte/issues/9815) | | | ❌ | $100 |
| Add better error response messages to file size errors |  | [Issue](https://github.com/airbytehq/airbyte/issues/7900) | | | ❌ | $100 |
</details>

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
