### ISSUE TITLE
[EPIC] Sponsored Connector Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10950]
| Connector | Comments | Related Issue | Connector Status
|---|---|---|---|
| Notion | | https://github.com/airbytehq/airbyte/issues/10474 | Alpha
| Google Analytics | | https://github.com/airbytehq/airbyte/issues/10941 | Beta
| Amplitude | | https://github.com/airbytehq/airbyte/issues/10942 | Alpha
| Google Search Console | | https://github.com/airbytehq/airbyte/issues/10943 | Alpha
| Mixpanel | | https://github.com/airbytehq/airbyte/issues/11008 | Alpha
| Klaviyo | | https://github.com/airbytehq/airbyte/issues/10945 | Alpha
| Bing Ads | | https://github.com/airbytehq/airbyte/issues/10946 | Alpha
| Typeform | | https://github.com/airbytehq/airbyte/issues/10947 | Alpha
| Freshdesk | | https://github.com/airbytehq/airbyte/issues/10948 | Alpha
| Pipedrive | | https://github.com/airbytehq/airbyte/issues/11004 | Alpha

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
