### ISSUE TITLE
Split the ConnectionManagerWorkflowTest

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#10959]
## What
In order to make the test `ConnectionManagerWorkflowTest` more readable, we need to split it by nested test.
It will:
- Make it easier to maintain, the test being more than 1k lines, it start being to be hard to navigate.
- make it faster since it can now be parallelized by gradle

The split need to be done by Nested class, each nested class has to instantiate the test env by registering a specific child workflow.

**Comment by davinchia** [comment]
Closed in favor of https://github.com/airbytehq/airbyte-platform-internal/issues/7413.
