### ISSUE TITLE
Change Segment track event names

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10954]
Our segment track event names are currently a very free form (human readable) text. We want to change that to be more ID like and having a shared format across backend/frontend. We want to migrate all old events to the new format.

An event name in the new format would e.g. look as follows: `Airbyte.UI.User.Created`

### Structure

The first part should always be `Airbyte` for events we're sending. This allows us to later use third party prefixes if we purely forward events from other tools/libraries.

The second component should be the source that is creating this event. This should be either `UI` (all frontend code) or `API` (all backend code) for now.

Everything behind this is the actual event ID and should use `.` to separate e.g. namespaces (like `User` or `Connection`) from the actual event happened `Created`. There is not necessarily a limit two only two parts, if needed this can also have more than 2 components where it makes sense.

### Backward compatibility

When renaming we'll need to make sure that we move all data in BigQuery from the old collections into the new ones.

Also whereever possible we want to attach the old event name as a `legacy_event_name` parameter into the actual event parameters for some time to ensure we have access to both in all tools.

### Flattening events

In a couple of places (mostly frontend) we use very generic event names and then classify about the specific event as a parameter within this event, e.g. the FE event "Source - Action", which then uses an `action` parameter to differentiate. These are harder to leverage eventually, and we want to flatten them out, so that each "Source - Action > action" will eventually be it's own event ID.

cc @nataliekwong @ChristopheDuong

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by cgardens** [comment]
@andyjih to follow up with @timroes and @nataliekwong  on priority and owner

**Comment by andyjih** [comment]
Got an update-- Segment events are also triggered from the backend, so the request is that the platform follows the same pattern.

**Comment by nataliekwong** [comment]
The primary ones I am interested in (and would be used with Appcues if split) are:

New Source - Action (new_source_action) into four actions:
- Select a connector
- Test a connector
- Tested connector - success
- Tested connector - failure

New Destination - Action (new_destination_action) into four actions:
- Select a connector
- Test a connector
- Tested connector - success
- Tested connector - failure

There are likely future use cases for these other Segment calls too (but we don't currently focus efforts here yet):

New Connection - Action (new_connection_action):
- Set up connection
- Set a frequency

Source - Action (source_action):
- Full refresh sync
- Edit schema
- Disable connection
- Reenable connection
- Delete source

Destination - Action (destination_action):
- Delete destination

**Comment by tealjulia** [comment]
Should the action parameter still be included in the body? So for instance a user picking "Hubspot" in the dropdown for creating a source would be:

AIRBYTE.UI.SOURCE.SELECT, {
action: "Select a connector",
connector_source: "Hubspot",
connector_source_definition_id: "some_id",
legacy_event_name: "New Source - Action"
}

**Comment by nataliekwong** [comment]
I think we benefit from keeping it in the body, so that we don't have to infer it from the event name (or table name in BigQuery). Nice to have something readable too.

**Comment by tealjulia** [comment]
@nataliekwong it would only be ~an hour worth of work on my end to get that second set (the "future use cases") using the new format as well.  Would that be useful for you so things are consistent?  Happy to throw it all in the same PR.

**Comment by nataliekwong** [comment]
@tealjulia Yep, consistency is preferred! We'll end up focusing more on retention this coming quarter so definitely ideal to have them done now.

I noticed there aren't success / failure events for `New Connection - Action`, even though we do see people receive errors on the Connection Settings. Is there any comment left as to why that is? It came up this in our Fullstory review that we should pop up Intercom chats for connection settings failures, since we do see people struggling with the error messages there. I'm not sure if this was a deliberate omission back when these were originally set up, or just not scoped at the time. If there isn't any reason why not to have them, I can create a separate issue to get those created.

**Comment by tealjulia** [comment]
It doesn't look like a deliberate omission, go ahead and add an Issue!  A few other things I wondered:
* Disable connection and Reenable connection are listed above under "New Source - Action"... should they be named like `Airbyte.UI.Source.DisableConnection`?  I would think `Airbyte.UI.Connection.Disable` would be more descriptive, but I don't want to break anything you're doing!
* We have a call for Delete Source and Delete Destination... should Delete Connection be added as well?

**Comment by nataliekwong** [comment]
> Disable connection and Reenable connection are listed above under "New Source - Action"... should they be named like Airbyte.UI.Source.DisableConnection? I would think Airbyte.UI.Connection.Disable would be more descriptive (also, it's sending the data it usually sends with connections calls not source calls), but I don't want to break anything you're doing!

@tealjulia Yeah, that doesn't make sense to me either. I tested it and it triggers when I am toggling the enable/disable on the connection. We also don't have a concept of disabling a source, only deleting it. Agreed we should rename it - we're not triggering anything downstream right now so no worries about breaking anything. 

In the renaming, I assume the noun comes before the verb if we're following the ? (e.g. airbyte_ui_cloud.airbyte_ui_new_source_selection_opened) My only suggestion is to call it ConnectionDisable so that it matches that convention. 

> We have a call for Delete Source and Delete Destination... should Delete Connection be added as well?
Yes! I can create another issue unless you want to roll it up in this PR.

**Comment by tealjulia** [comment]
1. Great!  I can make those changes in the AM and get it in for review.
2. There were a few spots we send a `source_id` or a `destination_id` field, but the data we're sending is actually a source/destination definition id.  Would renaming those fields `source_definition_id` break anything?  Trying to tidy things up while I'm in here.
3. Let's make a separate issue to keep this PR to only migrating/cleaning up, not adding anything new.

**Comment by nataliekwong** [comment]
> There were a few spots we send a source_id or a destination_id field, but the data we're sending is actually a source/destination definition id. Would renaming those fields source_definition_id break anything? Trying to tidy things up while I'm in here.

Won't break anything!

> Let's make a separate issue to keep this PR to only migrating/cleaning up, not adding anything new.
Sounds good! https://github.com/airbytehq/airbyte/issues/13863
