### ISSUE TITLE
EC2 Runners for builds should have a clear name or label

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#10962]
## Tell us about the problem you're trying to solve
It looks like instances we spawn for builds don't have any naming or labeling to help distinguish them from other instances, which reduces our ability to filter and clean up hanging instances. We recently had an issue where a stop-runner action was missing, leading to resource exhaustion due to hanging instances ([Slack thread here](https://airbytehq-team.slack.com/archives/C02U2SSHP9S/p1646781556050349)). Because they lack a name or label, we don't have an easy way to filter and bulk clean these instances and have to hope that all unnamed instances that are several days old can be killed.

## Describe the solution you’d like
Go through our start-runner actions and add a clear name or label to the instance that is started.

**Comment by pmossman** [comment]
Closing as done

**Comment by davinchia** [comment]
evidence for posterity:

<img width="1739" alt="Screen Shot 2022-03-11 at 1 50 29 AM" src="https://user-images.githubusercontent.com/9772859/157724509-4d53a04c-b34f-49e7-99dd-596a53504305.png">
