### ISSUE TITLE
Creating Incremental Sync Is Not possible to Import IncrementalMixin class

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#10960]
Not possible to import class `IncrementalMixin` to implement Incremental Sync.
Looks is missing the exposing the class to the init file https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/__init__.py.

>I'm working on creating an incremental stream. [Based on the documentation](https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/6-read-data#adding-incremental-sync) it looks like I should use the IncrementalStream class, but I am running into errors importing IncrementalStream. I think this is because only Stream is exposed in _init_.py https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/__init__.py, but I may be forgetting my python.

See [Slack Thread](https://airbytehq-team.slack.com/archives/C01VDDEGL7M/p1646763796018669)

**Comment by jonoirwinrsa** [comment]
Yeah the docs and code seem to be out of sync with the code

**Comment by sherifnada** [comment]
fixed in the most recent CDK release
