### ISSUE TITLE
MySql -> Snowflake tiny int issue

### ISSUE THREAD

**Issue by thisisile** [airbytehq/airbyte#10976]
## Environment
- **Airbyte version**:  0.35.26-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: MySql 0.5.1
- **Destination Connector and version**: Snowflake 0.4.8
- **Severity**: Medium / High
- **Step where error happened**: Sync job

## Current Behavior
I have a table in MySql with a column of tinyint containing values 0,1,2, or 3,
but in the destination the values get converted to Boolean. 0 becomes false and 1,2, or 3 becomes true.
This is the case for both raw tables as well as basic normalization tables

## Expected Behavior
I expect values 0,1,2, or 3  being reflected in snowflake rather than boolean.
I might understand if distinct values were 0 or 1 maybe, but if there are ranges of values, this conversion should not happen.

**Comment by thisisile** [comment]
![image](https://user-images.githubusercontent.com/85608733/157436824-652a2d22-56a6-470e-adc6-a9648faa991c.png)
raw tables contain true/false but I expect values 0,1,2 or 3

**Comment by grishick** [comment]
This is currently the correct behavior. In MySQL TINYINT(1) is meant to represent boolean values.

**Comment by thisisile** [comment]
@grishick @tuliren Thank you for your responses.

You are indeed correct.
However,
While all Booleans get converted to `TINYINT(1)` of 1s and 0s, **NOT ALL** `TINYINT(1)` can be represented as `Boolean`, as this will impact data quality.

Furthermore, if data is stored as integers in the MySQL Db, why do we convert this back into Bool ? "A core tenet of ELT philosophy is that data should be untouched as it moves through the E and L stages so that the raw data is always accessible."
If one would want an identical replica of the MySQL Db would it not be more accurate to contain integers ?
Should one not rather use a transformation tool such as Dbt to transform these back if desired?

Having a look at Fivetran, 
https://fivetran.com/docs/databases/mysql#:~:text=TINYINT,1s%20or%200s.
We see that `TINYINT(1)` containing distinct values of 0 and 1 become Boolean, but become Integers if containing other values.
This seems to be the ideal solution when working with `TINYINT(1)`s

Perhaps we can adopt this behaviour ?

**Comment by toandm** [comment]
Hi guys, I have a case where a tinyint(1) column from customer database has 4 kinds of values: 0,1,2,3
Current behavior causes the column to lose all these data. Any ways you can allow user to treat tinyint(1) as int column instead of boolean?

**Comment by toandm** [comment]
Hi guys, I have a case where a tinyint(1) column from customer database has 4 kinds of values: 0,1,2,3
Current behavior causes the column to lose all these data. Any ways you can allow user to treat tinyint(1) as int column instead of boolean?

**Comment by toandm** [comment]
Leaving this to anyone having this issue:
You can add this JDBC param in and issue is resolved: `tinyInt1isBit=False`
![image](https://user-images.githubusercontent.com/95567342/186647916-486e1fca-be30-48bc-aa06-5985b5965ba8.png)

**Comment by choji-pro** [comment]
Hi @toandm would you add this JDBC URL Param to the source MySql or destination Snowflake ?

**Comment by toandm** [comment]
Hi @choji-pro JDBC param is for MySQL source only

**Comment by choji-pro** [comment]
@toandm This did not work for me

**Comment by rtuin** [comment]
Just dropping in to tell I also ran into this issue. Adding `tinyInt1isBit=False` to the connection string resolved the issue. 
The usability on this could be improved. For example, I like how it is implemented in this PR: https://github.com/planetscale/airbyte-source/pull/45
