### ISSUE TITLE
Improve TagInput component

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10985]
There are a couple of usability improvement we should do to the TagInput component:

* It currently gives no guidance that you actually need to press <kbd>Enter</kbd> to create a tag in it.
* Users should be able to paste values into it containing a separator character (e.g. `;`, `,`) and the component should offer creating multiple tags out of it. This should ideally be smart enough to detect a couple of different characters and offer to separate or not.

To achieve this with appropriate a11y it might be best to switch this component over to an existing library that solves those problems.

Related: #16765

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Array Fields](https://app.harvestr.io/components/0/list/m8eVzxM7k)

**Comment by tealjulia** [comment]
@misteryeo Here is what I'm thinking. 

For users typing in the input, a "tag" (item for the array) would be created:
- when a user hits `tab`
- when a user hits `enter`
- when a user types a comma

For copy/pasting into the input, a "tag" would support:
- comma-delimited
- semicolon-delimited
- new-line-delimited

Before I add any of these functionalities, I want to be sure that there aren't instances where a connector might expect a comma or a semicolon (or a new line) to be part of one of the strings in the array.  This is _only_ for connectors with the `array` property on their spec.  This wouldn't affect, for instance, pieces like the github connector's "repositories" property (which takes a space-separated list as a string, not as an array).

**Comment by tealjulia** [comment]
I agree that in the long run that would be good to support.  It also adds quite a bit of complexity to the implementation.  There are some other cases to consider when we get to that point as well (allowing users to escape single/double quotes if they want to include them in the tag, etc.)

Given that the current component is pretty poor and it doesn't sound like a common scenario, I think "done is better than perfect" for now.  Meaning support the lower-hanging fruit listed above, and I'll create a separate Issue to extend it to implement quoted strings creating a single tag.  I do agree we should get there!

**Comment by misteryeo** [comment]
Perfect, thank you!

---
Andy Yeo
Senior Product Manager
Github <https://github.com/airbytehq/airbyte> | Twitter
<https://twitter.com/AirbyteHQ> | LinkedIn
<https://www.linkedin.com/company/airbytehq/>


We're hiring, come work with me! <https://airbyte.io/careers> [image: 🚀]
