### ISSUE TITLE
🐙 octavia-cli: make connection configuration more readable

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#10980]
Connection configuration currently contains streams config + streams schema, which leads to huge YAML configuration files for some connectors. Moreover, users can edit the schema, which is not something Airbyte's backend currently supports.

We should only keep stream configuration in the connection configuration and split stream schema in a separate file that we prevent users to edit.

**Comment by mauricioalarcon** [comment]
+1 
Agreed, sources and destination are manageable but connections can get our of hand very easily when you have a lot of tables to replicate + jsonschema

How about a structure like this: ?
```
.
└── connection-definition
    ├── main-config.yaml
    └── streams
        ├── table1.yaml
        ├── table2.yaml
        └── table3.yaml
```
