### ISSUE TITLE
Replication frequency changes when source namespace change

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#10993]
This is a follow up from https://github.com/airbytehq/airbyte/issues/10671. When having a connection with Replication Frequency "Manual", changing the "Destination Namespace" setting, will change the schedule to every 24 hours, since we're sending this now in the `web_backend/connections/update` method.

**Steps to reproduce**

1) Create a connection with a manual schedule.
2) Go to the connection page (or refresh it)
3) Change the Destination Namespace
4) Observe how the Schedule changed now to "Every 24 hours".

Also see this Loom: https://www.loom.com/share/8b290d9e46c74d979c68f0508a5701d9

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Actually I just noticed the original issue seems neither to be fixed. You'll see that when switchin the replication frequency it will always not contain the "namespaceFormat" in the update request to `web_backend/connections/update`, and thus the backend currently resets it to the string "null", since it was marked as the default value.

**Comment by timroes** [comment]
Closing this was likely caused by our cloud deployment got rolled back.

**Comment by timroes** [comment]
Reopening this again. The originally described issue is still present. Only my [first comment](https://github.com/airbytehq/airbyte/issues/10993#issuecomment-1063153749) was caused by the wrong cloud deployment.

**Comment by timroes** [comment]
Talking to Nico, this was the outcome: We want to have still separate save/cancel buttons per tab (though not per card), and we should show a dialog asking to save before switching tabs, when the form is dirty. See the following Loom: https://www.loom.com/share/9c835749fe904a1292e66b2ff02d4275

@Jamakase If it helps making changes in our update API for this, to not run into this issue, let me know so we can make the adjustments.

We're ignoring for now behavior coming from operating in multiple tabs on the same connection.

**Comment by Jamakase** [comment]
Closing this issue as fixed. Part with popup will be implemented in separate followup task.
