### ISSUE TITLE
Source Pipedrive Feature/Bug Hub

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#11004]
The centralized hub for all feature requests and bugs associated with the [Pipedrive Source](https://docs.airbyte.com/integrations/sources/pipedrive) has been moved to the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13/views/24).

The table of issues that was previously on this issue is now deprecated but is left in the collapsed section below.
<details>
  <summary>Deprecated Issue Hub</summary>

**Feature Checklist**

| Feature |  Comments | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
| Full Stream Coverage | Triage needed. | | | |❓| - |
| Incremental Sync | The `Leads` and `ActivityFields` streams need to be supported. | | | | ❌ | - |
| Pagination | | | | | ✔️ | - |
| Test Coverage | [Unit Test Files](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-pipedrive/unit_tests) - No unit tests. | | [PR](https://github.com/airbytehq/airbyte/pull/11443) | @itaseskii | ❌ | $300 |
| Sandbox Account | | | | | ✔️ | - |
| Docs Formatting | This connector doc does not follow our new standard format. | | | | ❌ | $50 |
| Getting Started Guide | Needs description of steps in Airbyte UI. | | | | ❌ | $50 |
| Support Custom Fields | [Issue](https://github.com/airbytehq/airbyte/issues/9433) | | | @itaseskii | ❌ | $200 |

**Bug Checklist**

| Bug Description | Other Notes | Related Issue(s) | Related PR | Claimed By | Merged | Bounty |
|---|---|---|---|---|---|---|
</details>

**Comment by itaseskii** [comment]
Hey @avaidyanatha I would like to claim the **Test Coverage** issue for the Piperdrive connector

**Comment by itaseskii** [comment]
@avaidyanatha I would like to claim the task for adding support for custom fields next :)

**Comment by aharelick** [comment]
Closing this issue as this will all be managed by the [Maintainer Github Project](https://github.com/orgs/airbytehq/projects/13).
