### ISSUE TITLE
Airbyte Data transfer rate documentation

### ISSUE THREAD

**Issue by SriramThumma** [airbytehq/airbyte#11016]
### Tell us about the documentation you'd like us to add or update.
Looking for a documentation on the Data Transfer rate of Airbyte Cloud, Airbyte opensource. Is there a standard data transfer rate that airbyte can handle or it has any dependencies. If yes, please call out the dependencies. 

This is one of the criteria for a client/ an enterprise when they consider Airbyte for ELT.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
