### ISSUE TITLE
Allow to override REACT_APP_API_URL

### ISSUE THREAD

**Issue by GuillaumeLachaud** [airbytehq/airbyte#1102]
## Tell us about the problem you're trying to solve
Trying to deploy Airbyte on GKE behind cloud IAP to secure the deployment. Traffic between web-app and API must go through port 443 in order for this to work. Current implementation looks if REACT_APP_API_URL is set or defaults to port 8001. As REACT_APP_API_URL is set at build time, it's not convenient to change it.

## Describe the solution you’d like
Make it easier to override this env var at runtime, just as TRACKING_STRATEGY

## Describe the alternative you’ve considered or used
Alternative is for me to build my own custom image of airbyte/webapp which I don't have the time to maintain

**Comment by michel-tricot** [comment]
Thanks @GuillaumeLachaud. Indeed, I think we should implement it this way. 

@cgardens that will likely be necessary to support the URL as an env variable once we set up airbyte for k8s

**Comment by michel-tricot** [comment]
btw @GuillaumeLachaud if you're creating k8s manifests, any chance you could share them? We want to release some for mid-Dec

**Comment by GuillaumeLachaud** [comment]
I definitely can share them but ultimately, I didn't manage to completely deploy Airbyte over K8s. Here's a quick recap of what's not working yet (though it's not the topic of the current ticket):

 - In order for airbyte-server to be reachable by web-app, it needs to be exposed by a Service and an Ingress. They require a health check to pass before they start routing traffic to it. Which means an endpoint has to return a 200 on a GET request (default is / but it's customizable). Currently only /api/v1/debug is a GET endpoint and can be used for the Ingress healthcheck. But it fails and returns a 500, as the implementation is looking to call the docker executable which the current image doesn't seem to provide
 - Similarly, the scheduler seems to be involved in some DinD: it mounts the host docker socket and will I guess try to schedule jobs through it. Though it's possible to mount the docker this way in K8s, it's highly discouraged, the K8s cluster could be using another runtime than Docker.

Also, the Helm charts I have written are GCP specific as it uses Cloud IAP to add an authentication mechanism in front of the services.

**Comment by michel-tricot** [comment]
Thanks! Added you comment to the k8s issue
