### ISSUE TITLE
Add search input for primary key and cursor

### ISSUE THREAD

**Issue by jamakase** [airbytehq/airbyte#11022]
Add search input for dropdown in connection form.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/3767150/157659835-a758e236-9993-4e2c-a3c6-d3484d51da29.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Will be addressed in the streams table re-design.
