### ISSUE TITLE
Add Segment call for Source or Destination "Select a Connector" dropdown

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11048]
We do not have frontend analytics on how often & which users select the dropdown button to show the source or destination dropdowns. In Fullstory, we see users scrolling through the list, often without selecting one, before navigating away. By adding a Segment call for the selection of the dropdown, we can create baselines and track improvement to this specific part of the onboarding.

Name: Airbyte.UI.NewSource.Selected and Airbyte.UI.NewDestination.Selected (this is a suggestion, please suggest a better alternative if you can think of one based on the new naming convention)
Properties:
- workspace_id
- user_id

Alternatively, you can also (if this is easier) combine it into the New Source - Action call that already exists. The property `action ` would be "Select dropdown" and the property `connector_source` would be null/blank.  (The list of Segment calls we have on Cloud is here https://docs.google.com/spreadsheets/d/1lGLmLIhiSPt_-oaEf3CpK-IxXnCO0NRHurvmWldoA2w/edit#gid=1567609168)

This should apply for both the Onboarding flow (/onboarding), New Source (/source/new-source), and New Destination (/destination/new-destination). There is a selection of either the New or Existing Source on (/connections/new-connection), so it should fire when either of the options are selected, but be distinguishable with the property `new_existing`

![Screen Shot 2022-03-10 at 2 39 11 PM](https://user-images.githubusercontent.com/38087517/157741684-a35134b5-7463-403d-bf9c-85ad8bc9a27e.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Awesome! I see a few test events coming through. They are all in the dev environments and the latest is from 3/11 (it looks like local testing). I would have expected to see more since 3/11 - do we need to wait for a Cloud prod deploy before seeing the events come through?

**Comment by timroes** [comment]
Yes, this was merged yesterday and we haven't run another release since then. I'll lately create one once we merged the split token PR, but it might be that someone will create one already before that.

**Comment by nataliekwong** [comment]
Confirming I see the events now!
