### ISSUE TITLE
Use the Company Name when creating the Workspace

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11049]
The first workspace created on email verification uses the email to define the name of the workspace.

We see two issues with this. 
- The first is that users consistently create a secondary workspace named for their company name (e.g. chris-default is created, and a secondary workspace called Airbyte is created as the first action)
- The second are the downstream issues with duplication of the workspace names for common names for Technical Support (when navigating the admin page to see all workspaces)

Instead, since we ask for users to share their company name with us on signup, use the company name provided instead of the email.

@timroes has proposed that this change be merged at the same time as this change: https://github.com/airbytehq/airbyte/issues/10819

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
