### ISSUE TITLE
'Delete Connection' button doesn't provide immediate feedback when clicked

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#11046]
### What

When I click the 'Delete' button in the confirmation modal that pops up while deleting a connection, nothing happens until the request completes. This request can take several seconds, and a user might assume that the button click did not work. This can lead to users clicking multiple times before the first request completes and is overall a poor UX.

![image](https://user-images.githubusercontent.com/7798112/157726346-32d32f6a-6b4d-45b1-a8ea-ed7118f12349.png)

### How

The button should immediately become 'disabled' when clicked. Even better would be for the button to have a spinner or some indication that the request is being processed, so that the user knows to wait for requests that take a long time.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
