### ISSUE TITLE
New Source Connector: LaunchDarkly

### ISSUE THREAD

**Issue by miguel-firebolt** [airbytehq/airbyte#11055]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* [LaunchDarkly](https://docs.launchdarkly.com/) source 
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
* The most recent version

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
* We use LaunchDarkly to control feature flags and we want to bring this into our warehouse for reporting and analytics
* How often do you want to run syncs?
* Every hour
* If this is an API source connector, which entities/endpoints do you need supported?
* Yes its an API source connector. We are mostly need the Feature flags and segments endpoints, but could use other endpoints.
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?
Yes

**Comment by koconder** [comment]
@marcosmarxm ill take a look at this one.

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/18393
