### ISSUE TITLE
Wrong Timestamp while using BigQuery(Denormalized) Destination

### ISSUE THREAD

**Issue by cypherop** [airbytehq/airbyte#11067]
## Environment
- **Airbyte version**:  0.35.36-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Postgres 12.7
- **Destination Connector and version**: BigQuery(denormalized)
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Sync job

## Current Behavior
- Timestamp at Bigquery Denormalized destination is wrong. It is showing something like `54155-07-08 16:40:49 UTC`

## Expected Behavior
- Timestamp should be correct

## Steps to Reproduce
1. Using Postgres Source and Bigquery Denormalized destination set up a connection in full refresh append mode.
2. Run a sync on a Table.
3. On destination side you will see wrong Timestamp in `_airbyte_emitted_at` column.

## Are you willing to submit a PR?

No.

**Comment by marcosmarxm** [comment]
@cypherop could you post a desc table from the postgres source and one example of value from the source too?
