### ISSUE TITLE
Rest Api Connector

### ISSUE THREAD

**Issue by rubenssoto** [airbytehq/airbyte#1106]
Hello Guys, how are you?

Thank you so much for this great project.

Im running airbyte in my machine with docker, but I can't see the rest api connector. We are looking for a simple way to get data from Api, airbyte could be the way.

Thank you.

**Comment by michel-tricot** [comment]
Hey @rubenssoto,

We actually had to disable it because it wasn't working properly. (will add it back soon)

Could you tell us more about what you would like to achieve with it?

**Comment by cgardens** [comment]
@rubenssoto - it will be added back to the app on monday! will write back here when it is done.

**Comment by rubenssoto** [comment]
Hello,

Sorry for my late response, so, we are a Brazillian Company and we will have to make some integrations with some Brazillian services and I think it is impossible to have software with all api connectors that we need. So, we need software with many connectors and a way to make our own connectors in a simple way...today for each connector we created a specific extractor and it is a pain.

thank you

**Comment by cgardens** [comment]
@rubenssoto This was merged into master and is our most recent release. When you get a chance to try it out lmk if you have any questions!

**Comment by cgardens** [comment]
@rubenssoto I am going to go ahead and close this as I think we've hit waht you've needed. Feel free to reach out here if there's something else you need!
