### ISSUE TITLE
Visually highlight required errors in cursor field and primary keys field 

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11084]
Currently the cursor field and primary keys in the table don't have any visual error feedback that they are required. The form will just fail with a generic error leaving the user clueless what's happening.

![screenshot-20220312-013142](https://user-images.githubusercontent.com/877229/157995557-90757529-f801-494e-9e3a-7cda15bcd804.png)

Those fields should have clear visual highlights that they are required.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Default Sync Modes](https://app.harvestr.io/components/0/list/7ThS6bCn9)
