### ISSUE TITLE
Improve help text for Google Sheets

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11096]
### Current: 
When setting up Google Sheets, there is no example for the user to tell them what the Spreadsheet ID should look like. This is the current text: Spreadsheet ID * - The ID of the spreadsheet to be replicated.  

### Suggestion:
Change the help text to help the user understand what value we are expecting. For example,
"Spreadsheet ID * - The ID of the spreadsheet to be replicated. The ID is found in the URL of your spreadsheet, typically between "/d/" and "/edit" For example: 2JH4htAf-XUfLYEnlDug2vLYrmUkMCjmLjwAqSzGbqvY.

We can also put a greyed out dummy value in the input box. 

Examples of users entering the wrong input: 
- https://fsty.io/v/bjmyUD2E
- https://fsty.io/v/tXNBffAE

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@nataliekwong This is a change purely to wording of the connector specific UI. The UI is auto-generated from the connector specification, thus those wording changes will be a pure connectors specification change always. Could you please raise that issue with @sherifnada and the connectors team?

**Comment by nataliekwong** [comment]
Understood! I didn't realize that. I will connect with Andy/Sherif then.

**Comment by grishick** [comment]
@sherifnada you have fixed this as part if this commit: https://github.com/airbytehq/airbyte/commit/23d995d090a6be470b263685f402f5756cd86a6b

@nataliekwong this was fixed in December and the user guide now includes this section:
![Screen Shot 2022-03-18 at 11 27 44 AM](https://user-images.githubusercontent.com/1310940/159062086-2c697f00-2c1b-4e40-b93f-19ac1e002d3c.png)

**Comment by nataliekwong** [comment]
@grishick I understand the docs were changed. My suggestion was to edit the help text above the field. 
Can the help text be edited to show an example value within the box, or explain that it is found within the URL?

**Comment by grishick** [comment]
@nataliekwong thank you for the clarification. I have updated the description in the connector spec file. Now it looks like this:
![Screen Shot 2022-03-18 at 4 55 12 PM](https://user-images.githubusercontent.com/1310940/159098016-40fd715e-c9c2-4ab9-abee-538c2fb5394e.png)

**Comment by nataliekwong** [comment]
Thank you!
