### ISSUE TITLE
Improve Salesforce Setup / Config

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11097]
### Current:
The wording of the Salesforce setup fields is not intuitive to a user setting up Salesforce for the first time. Currently 44% of users try to authenticate Salesforce. I would expect users to attempt if the setup fields were more succinct and simpler to understand.

## Suggestion for Start Date:
Currently: Start Date - Date in the format 2017-01-25. Any data before this date will not be replicated. This field uses the "updated" field if available, otherwise the "created" fields if they are available for a stream. If not set, then by default all your data is replicated. (e.g. 2021-07-25, 2021-07-25T00:00:00Z) 

Suggestion:
- Add the word (Optional) explicitly to indicate it does not need to be filled in.
- Make the wording succinct. All objects in Salesforce have the Last Modified Date by default, so it can be removed.  
 
Start Date (Optional) - Any records updated before this date will not be replicated. If left blank, then by default all your data is replicated. (e.g. 2017-01-25)

Prefill the text box with an example date 2017-01-25.

## Suggestion for Salesforce Object filtering criteria (Optional)
Currently: Salesforce Object filtering criteria (Optional)
Add selection criteria for streams to read only the Salesforce objects which are relevant to you.

Suggestion: 
- Do not use the word streams here as Salesforce users are used to referring to these as Objects (what Salesforce called the tables).
- I actually find this confusing as I now have two places to filter objects from, here as well as the stream filtering later on. It would be helpful to the user to know these are most often left blank and they shouldn't need to worry about filling them in. 

Salesforce Object filter (Optional)
Pre-filter read objects using custom regex (used for speed optimization)

Finally, when I add items to this list, it shows as items 0, 1, etc. It works, but the numbering doesn't convey anything to the user. It can be replaced with the actual rule (e.g. Ends with "t"), or modify the name to be "Rule 1", "Rule 2". 
<img width="522" alt="Screen Shot 2022-03-14 at 12 36 38 AM" src="https://user-images.githubusercontent.com/38087517/158105691-6a3cc241-8717-4fd8-885f-b98b30a08b76.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@nataliekwong The problem with the Items list is tracked via https://github.com/airbytehq/airbyte/issues/10858 (we're still waiting on design discussions with @upmitt for this). I've created https://github.com/airbytehq/airbyte/issues/11100 to discuss the "Streams" wording. The rest of this issue will be connector specification changes and I'd ask you to bring it up with @sherifnada and the connectors team.

**Comment by nataliekwong** [comment]
Issues now resolved! Closing.
