### ISSUE TITLE
Make source/destinations tab present in the URL

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11102]
Currently when visting an individual's source or destinations page, it's not part of the URL whether the user is on the "Overview" tab or the "Settings" tab. This makes it hard to link to them from our documentation and we should reflect that tab within the URL, so we're able for documentation and support to link to a page directly.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This issue was actually resolved in https://github.com/airbytehq/airbyte/pull/12253 when the confirmation modal was added. The paths are:

Overview: `workspaces/:workspaceId/souce|destinaton/:sourceOrDestinationId`
Settings: `workspaces/:workspaceId/souce|destinaton/:sourceOrDestinationId/settings`
