### ISSUE TITLE
Documentation about Demo ConnectionSpecification is out of date

### ISSUE THREAD

**Issue by ramonvermeulen** [airbytehq/airbyte#11122]
### Tell us about the documentation you'd like us to add or update.
I followed the following guide: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/docs/HowTo-ConnectionSpecification.md
But it isn't working, it's referenced here: https://github.com/airbytehq/airbyte/blob/gitbook/v1/docs/connector-development/connector-specification-reference.md

My suggestion is to either delete this reference and part of the documentation, or bring the form back into storybook so it can be used.

### If applicable, add links to the relevant docs that should be updated
https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/docs/HowTo-ConnectionSpecification.md
https://github.com/airbytehq/airbyte/blob/gitbook/v1/docs/connector-development/connector-specification-reference.md

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
