### ISSUE TITLE
New Source: GCS (Google Cloud Storage)

### ISSUE THREAD

**Issue by terekete** [airbytehq/airbyte#11135]
## Tell us about the problem you're trying to solve
Like to be able to dump tabular data into a bucket and use GCS hmac to read it as a csv to write elsewhere. I see there is an s3 source. 

## Describe the solution you’d like
https://cloud.google.com/storage/docs/json_api/v1 
GCS source that is read in with a set schema and written to a dest.
It should support path patterns, CSV with delimiter support, parquet, avro
The following authentication methods should be supported: OAuth, Service Account ClientId/ Secret Stored in Vault

## Describe the alternative you’ve considered or used
Python client

**Comment by ChristopheDuong** [comment]
If the data in the GCS bucket is stored as JSON file (one record per file) instead of JSONL (one record per line)

And if this source connector could select all the files in the gcs bucket "folder" as rows for the same stream, that would be helpful to unblock https://github.com/airbytehq/airbyte-warehouse/issues/114

**Comment by clatko** [comment]
any progress on this in the past year?

**Comment by marcosmarxm** [comment]
There isn't a ETA today for this connector @clatko

**Comment by YowanR** [comment]
This connector should be built using the Python CDK, not the low-code one. Please let us know if you run into issues!

**Comment by tuanchris** [comment]
@YowanR I can work on this one

**Comment by YowanR** [comment]
Awesome! Looking forward to your contribution, @tuanchris ! 💪

**Comment by YowanR** [comment]
Closing this as completed! Thanks! @tuanchris 🚀
