### ISSUE TITLE
Detect when a change in OSS is breaking in Cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11137]
## Tell us about the problem you're trying to solve
Any interface change in OSS breaks the Cloud build. It is easy to set make that change in OSS and then forget to do it in Cloud. In this issue, we want to alert the developer when an OSS change breaks

**Comment by pmossman** [comment]
Grooming notes:
- high level idea: when an OSS commit is pushed to master, there should be a Cloud build attempt. If that cloud build fails, there should be some sort of notification to Slack, probably
- Who takes action on the slack notification? Is it the author of the OSS commit?
- Could do some sort of comment/warning/etc if certain folders are changes (like persistence, configurationApi, etc)
- Does OSS contribution ever break the build for Cloud? Whose job is it to fix that? 
  - Whoever did the Cloud version bump is the one who has to fix it
 
- Scope: every time a new commit lands on OSS master, we want a Slack notification if Cloud can't compile. So we're building cloud not only against official OSS releases, but every master commit

**Comment by git-phu** [comment]
Some quick notes:
- might be able to use something like [this](https://github.com/peter-evans/repository-dispatch) to trigger a cloud-repo build when oss master has a new commit
    - alternatively, just pull cloud repo in an oss workflow
- do something similar to [this](https://github.com/airbytehq/airbyte-cloud/blob/203daf98e29c16288ecb3eb609209bc359b33d88/.github/workflows/deploy-command.yml#L56-L137) to build cloud off of an oss ref
- create a new slack channel for these notifications?
- is it possible to fix the cloud build without creating an oss release?
   - do/should we recommend creating a new oss release every time a cloud breaking change is pushed to oss master?

**Comment by git-phu** [comment]
@davinchia I saw you created a `#cloud-master-build-failure` channel, could we just use that channel for these notifications?  If not I can create a new channel (in our team slack).

**Comment by davinchia** [comment]
@git-phu I think we can reuse the same channel for now and make it clear in the error message that it's a warning that the OSS release will break Cloud.

We can split it up if people find it noisy.

**Comment by git-phu** [comment]
Example of the cloud workflow triggered by a dispatch event from oss https://github.com/airbytehq/airbyte-cloud/actions/runs/2203154361
