### ISSUE TITLE
[SPIKE] Spring data

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11134]
## Tell us about the problem you're trying to solve
We have had multiple members of our team advocate for using Spring Data. Spring has bubbled to the top.

## Describe the solution you’d like
Spike out using Spring data for the cloud database. It is relatively less complex and isolated.

## Acceptance Criteria
- [ ] PR that uses Spring dependency injection that demonstrates what it would look like.
- [ ] If we like it, we should merge it.

**Comment by pmossman** [comment]
Grooming notes:
- Overlap with the other Spring spike: need some way to start a Spring context infrastructurally. The shaded airbyte server jar with classpath pollution will likely be an issue
  - Jonathan is basically stuck at this point, classes conflict with the server that is very difficult to exclude.
  - Airbyte server jar cleanup is on the infrastructure roadmap, but M1 cleanup is happening first. Jar cleanup here means separate jar publishing (avoid using a shaded jar, have normal transitive dependencies so dependencies can be excluded)
  - Probably not worth doing this until the jar cleanup is done (should be first thing infra works on in Q2)
