### ISSUE TITLE
Automatically detect when gradle caching is broken

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11132]
## Tell us about the problem you're trying to solve
Right now, it is really easy to make a change in gradle and accidentally break caching for the whole project.

## Describe the solution you’d like
I would like a build step (part of static analysis?) that can detect when a gradle module is configured in such a way that it will never cache properly and fails the build.

@jdpgrailsdev do you know if this is actually feasible or if it's me being pie in the sky?

**Comment by davinchia** [comment]
duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947
