### ISSUE TITLE
Ability to easily run an OSS branch on a locally running Cloud instance

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11136]
## Tell us about the problem you're trying to solve
Depends on 2 previous issues:
* - [x] https://github.com/airbytehq/airbyte/issues/9651
* - [x] https://github.com/airbytehq/airbyte-cloud/issues/1155

This issue is the cherry on top after we get the previous 2. As someone developing in OSS, I should be easily able to run my changes in a locally running version of cloud

**Comment by pmossman** [comment]
Grooming notes:
- Local cloud ticket is about deploying Cloud code locally while referencing a released OSS deployment, but this ticket is more about using both a local OSS branch AND local Cloud code.
- In a perfect world, this is a no-op once the two referenced issues are complete. But we want to capture this as an explicit goal. At minimum, we might need a script that automates this.

**Comment by cgardens** [comment]
@pmossman is your feeling that this is done or is there more work?

**Comment by pmossman** [comment]
I'd call the MVP done, though it would be a quality-of-life improvement to further automate the steps. Running a local OSS branch with local Cloud code IS possible now and relatively easy, now that you can set `OSS_VERSION=<local_oss_image_tag>` when running the Cloud build locally.

Here is what a developer needs to do now if starting from scratch:

1. From `airbyte` dir on your OSS branch, run your normal gradle build with `VERSION=<something>`
2. Then run `VERSION=<something> ./gradlew publishToMavenLocal`
3. Then from your `airbyte-cloud` dir, build with `OSS_VERSION=<something> ./gradlew build`
4. Then run `./tools/bin/deploy_cloud_locally.sh`

I have an issue where I'm collecting ideas for improvements to the local cloud deploy script, and I added an item to the list for making this easier, ie, just pass a flag and have it run those steps for you: https://github.com/airbytehq/airbyte-cloud/issues/1596

**Comment by pmossman** [comment]
@cgardens decided to just add this to the script right now so that we can close this epic without feeling conflicted: https://github.com/airbytehq/airbyte-cloud/pull/1970

**Comment by cgardens** [comment]
awesome!
