### ISSUE TITLE
Paginate workspaces API calls

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11146]
## Tell us about the problem you're trying to solve
Most of our APIs do not follow pagination best practices. In most cases, even in Cloud, we can get away with it in the short term. One place we cannot is when listing workspaces. Workspaces grow with the numbers of users. We should considering pagination everywhere, but this is the right place to start. Ultimately within a workspaces the number records returned (i.e. sources, destinations, connections) tend to be much more manageable.

**Comment by benmoriceau** [comment]
Wait for having the DB layer to be managed by Micronaut

**Comment by cgardens** [comment]
@malikdiarra Were we able to resolve whether this was a big factor in slow page load times for super admins in cloud? That would be the only thing that might bump up the priority of this issue.

**Comment by malikdiarra** [comment]
The call takes around 1s,=; it will have to be improved in the future but this is definitely not a high priority right now, especially since it mainly affects admin user.
`priority/low` seems appropriate to me

**Comment by evantahler** [comment]
Closing in favor of the new epic https://github.com/airbytehq/airbyte/issues/14282
