### ISSUE TITLE
Update the catalog interface between OSS Platform and Connectors

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11145]
## Tell us about the problem you're trying to solve
The connector catalog is constructed as part of the OSS build and then the Cloud version is done by the cloud build. This leads to a ton of head for all 3 teams involved. 

* connectors - It's bad for the connectors team, because it means that there is a multistep process for deploying new connectors (especially to cloud). This process is tied to the release cycle of the oss and cloud platform teams. In short, we all get in each other's way.
* oss platform - oss platform is responsible for building the catalog with the specs right now which creates all sorts of noise when it doesn't happen by accident.
* cloud platform - the cloud platform's catalog is tied to the OSS platform's catalog.

## Describe the solution you’d like
Instead of the platform teams having anything to do with constructing these catalogs, the connectors team should be responsible for publishing them as versioned artifacts that the platform teams consume. The connectors team would publish 2 catalogs: one for OSS and one for Cloud.

@sherifnada does this accurately describe your POV? I think you mentioned this to me the other day and I think it's right on.

**Comment by evantahler** [comment]
This is basically done now that the connectors can be updated without cloud being deployed.  We manage the catalogs as YMLs and JSON on GCS.
