### ISSUE TITLE
Missing records at Redshift destination on replication from Postgres

### ISSUE THREAD

**Issue by drewfustin** [airbytehq/airbyte#11158]
## Environment
- **Airbyte version**:  0.35.54-alpha
- **OS Version / Instance**: AWS EC2 (t3.large instance with amzn2-ami-hvm-2.0.20220218.3-x86_64-ebs AMI)
- **Deployment**: Docker on EC2
- **Source Connector and version**: Postgres 0.4.9 
- **Destination Connector and version**: Redshift 0.3.27 
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Replicating table `shortened_urls` from Heroku Postgres to Redshift. There are 88,701 records in the source table. After running the sync job, there are only 41,008 records in the destination table. This happens with other tables in our full replication as well. I've done a full rebuild of the EC2 and Airbyte docker-compose, I've changed the sync mode between "Full refresh | Overwrite" and "Incremental | Deduped + History", I've tried two different custom namespaces, and I've tried increasing the stream part size on the Redshift destination from 10 to 20. In all scenarios, it seems like the same number of records make it into the destination. This seems similar to [#2599](https://github.com/airbytehq/airbyte/issues/2599).

## Expected Behavior
I run the sync job and there are 88,701 records in the destination.

## Logs

[logs-28.txt](https://gist.github.com/drewfustin/9146fc29aaeb66515fd4009450e89bdf)

## Steps to Reproduce
1. Create Postgres source and Redshift destination
2. Create connection:
  - **Replication frequency:** Manual
  - **Destination Namespace:** Custom format
  - **Namespace Custom Format:** airbyte
3. Select Sync with "Full refresh | Overwrite" Sync mode for the table `shortened_urls`
4. Run sync

## Are you willing to submit a PR?

No

**Comment by alafanechere** [comment]
If you have missing records in the raw table it's probably related to this filter in the destination connector code:
https://github.com/airbytehq/airbyte/blob/0004a63ac120f35403a86bd955369e25c29bb06d/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftSqlOperations.java#L61

As redshift only allows `65535` bytes strings, the connector discards records exceeding this size during the write operation.

**Comment by drewfustin** [comment]
Looking at the staging data in S3, there are a few CSVs corresponding to other tables (with similar problems with missing data). It seems that the data in those CSVs has not been processed and put into our Redshift tables. 

Small example (note the small json size): 

`2022_03_15_1647350541116_20ede85e-a20c-4bc5-b616-7540616bc40a.csv`:
```
6979f44c-4368-4a71-84f5-155a0dfde261,"{""id"":1,""collection_id"":9398,""reservation_file_id"":306553,""added_by_user_id"":4,""created_at"":""2020-09-09T03:14:46.791783Z"",""updated_at"":""2020-09-09T03:14:46.791783Z""}",2022-03-15 13:22:21.607
c15e024c-d838-4ff4-813b-c7703a111d5b,"{""id"":2134,""collection_id"":9495,""reservation_file_id"":310200,""added_by_user_id"":4821,""created_at"":""2020-09-14T06:33:41.212217Z"",""updated_at"":""2020-09-14T06:33:41.212217Z""}",2022-03-15 13:22:21.607
...
```

and then looking in Redshift:

```sql
select count(*)  
from airbyte_postgres.collection_items  
where collection_id = 9398 or collection_id = 9495
```

returns 0.

**Comment by drewfustin** [comment]
This is exactly what is going on here:

Airbyte processed 88,769 emitted records into 2 CSV files in staging S3: one with 41,147 records and one with 47,622 records. Only one of those two files was written to Redshift, as both the `_airbyte_raw_shortened_urls` table and the `shortened_urls` table have only 41,147 records. If "Purge Staging Files and Tables" is set to `True` on the Redshift destination, both those CSV files are then deleted. I turned it to `False` to check the records in each CSV, and voila.

**Comment by drewfustin** [comment]
Same issue as #10646 / #11052

**Comment by kyle-cheung** [comment]
Would be awesome if Airbyte could asset some level of data quality check, an example where it could check the number of ingested rows vs target table, and if there's a significant difference then it could warn the user. In this case we were using full refresh overwrite, and essentially overwrote tables that had 200k with a table with only 2k record.
