### ISSUE TITLE
Source Zendesk Support to GCS Destination: parquet file IllegalArgumentException: bucket 

### ISSUE THREAD

**Issue by kempspo** [airbytehq/airbyte#11154]
## Environment
- **Airbyte version**:  0.35.46-alpha
- **OS Version / Instance**: GKE n1-standard-4
- **Deployment**: Kubernetes
- **Source Connector and version**: Zendesk Support 0.2.0
- **Destination Connector and version**:  Google Cloud Storage (GCS) 0.1.24
- **Severity**: Medium
- **Step where error happened**: On initial sync job

## Current Behavior
Throwing errors with `java.lang.IllegalArgumentException: bucket` on the GCS destination parquet files.

## Expected Behavior
*Tell us what should happen.*

## Logs
[logs-1.txt](https://github.com/airbytehq/airbyte/files/8252341/logs-1.txt)
(Uploaded a file instead since full logs are too long) 

<details>

<summary>LOG</summary> 

```
Failed to initialize fileystem s3a://bucket/data/2022_03_08_1646754764563_0.parquet: java.lang.IllegalArgumentException: bucket
2022-03-08 15:52:45 destination > 2022-03-08 15:52:45 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
```

</details>

## Steps to Reproduce
1. Setup connection with Zendesk Support as source and GCS Destination.
2. Switch to write Parquet Files. All default settings.
3. Change the `compression code` to `SNAPPY`

## Are you willing to submit a PR?
Yes, but would need help tracking down what the issue is exactly.

**Comment by kempspo** [comment]
Hi @andriikorotkov , I used the same bucket but instead writing csv files and it worked perfectly. So I don't think it's the bucket that's the issue.

**Comment by bazarnov** [comment]
> Hi @andriikorotkov , I used the same bucket but instead writing csv files and it worked perfectly. So I don't think it's the bucket that's the issue.
> 
> 
> 
> Adding this [link from slack](https://airbytehq.slack.com/archives/C01MFR03D5W/p1646756110450349) that I realize might have useful context

@kempspo please confirm source-connector works as expected in this case?

**Comment by kempspo** [comment]
@bazarnov, yep it works as expected, it's what I'm currently using while parquet files aren't working. Exactly the same setup (source-connector) except for the file type

**Comment by kempspo** [comment]
Just got to retest now, with a completely new deploy of airbyte seems like the previous errors are now gone
