### ISSUE TITLE
UI does not show selected oneOf in destination settings page

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11167]
## Current Behavior
I created a snowflake destination. I visited the destination settings page. But the dropdown at the bottom does not tell me which option I previously selected. 

<img width="791" alt="Screen Shot 2022-03-15 at 10 26 02 AM" src="https://user-images.githubusercontent.com/6246757/158436086-5044d64f-84a6-4b34-8f05-8a4f16642fee.png">

## Expected Behavior
The dropdown should list the option currently selected by the user

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@Jamakase this might be related to https://github.com/airbytehq/airbyte/pull/10883, could you please have a look at this.

**Comment by Jamakase** [comment]
@sherifnada I do not think it's an issue - everything is working as expected.

Based on the `spec.json` it corresponds to first value that was renamed from `Standard Inserts` to `Select another option`:

```
          {
            "title": "Select another option",
            "additionalProperties": false,
            "description": "Select another option",
            "required": ["method"],
            "properties": {
              "method": {
                "type": "string",
                "enum": ["Standard"],
                "default": "Standard"
              }
            }
          },
          {
            "title": "[Recommended] Internal Staging",
            "additionalProperties": false,
            "description": "Writes large batches of records to a file, uploads the file to Snowflake, then uses <pre>COPY INTO table</pre> to upload the file. Recommended for large production workloads for better speed and scalability.",
            "required": ["method"],
            "properties": {
              "method": {
                "type": "string",
                "enum": ["Internal Staging"],
                "default": "Internal Staging"
              }
            }
          },
```

**Comment by sherifnada** [comment]
Jeez I really fell for that one. Apologies for the confusion. Thanks for looking into it artem. Apologies for any wasted time again.
