### ISSUE TITLE
Namespace support for Streams (incremental/full_refresh)

### ISSUE THREAD

**Issue by romanlew** [airbytehq/airbyte#11180]
## Tell us about the problem you're trying to solve
Creating a connector source using a customized namespace, will end up in an misleading error message that message stream and catalog are not aligned, even though they are.
Reviewing the code, showed, that the custom namespace was applied to my schema. However, when trying to write records to the destination the namespace is not propagated to the AirbyteRecordMessage in the function _as_airbyte_record() in the class AbstractSource. Therefore Airbyte tries to write the records into the default namespace (unprepared) which then fails.

## Describe the solution you’d like
Please propagate the namespace to the necessary functions/classes to support custom namespaces for Streams.

## Describe the alternative you’ve considered or used
Currently I overwrote the two functions _read_incremental() and _as_airbyte_record() in my implemented class inherited from AbstractSource.

## Additional context
    def _read_incremental(
        self,
        logger: logging.Logger,
        stream_instance: Stream,
        configured_stream: ConfiguredAirbyteStream,
        connector_state: MutableMapping[str, Any],
        internal_config: InternalConfig,
    ) -> Iterator[AirbyteMessage]:
        """Read stream using incremental algorithm

        :param logger:
        :param stream_instance:
        :param configured_stream:
        :param connector_state:
        :param internal_config:
        :return:
        """
        stream_name = configured_stream.stream.name
        namespace = configured_stream.stream.namespace
        stream_state = connector_state.get(stream_name, {})
        if stream_state and "state" in dir(stream_instance):
            stream_instance.state = stream_state
            logger.info(f"Setting state of {stream_name} stream to {stream_state}")

        slices = stream_instance.stream_slices(
            cursor_field=configured_stream.cursor_field,
            sync_mode=SyncMode.incremental,
            stream_state=stream_state,
        )
        total_records_counter = 0
        for _slice in slices:
            records = stream_instance.read_records(
                sync_mode=SyncMode.incremental,
                stream_slice=_slice,
                stream_state=stream_state,
                cursor_field=configured_stream.cursor_field or None,
            )
            for record_counter, record_data in enumerate(records, start=1):
                yield self._as_airbyte_record(stream_name, record_data, namespace)
                stream_state = stream_instance.get_updated_state(stream_state, record_data)
                checkpoint_interval = stream_instance.state_checkpoint_interval
                if checkpoint_interval and record_counter % checkpoint_interval == 0:
                    yield self._checkpoint_state(stream_instance, stream_state, connector_state)

                total_records_counter += 1
                # This functionality should ideally live outside of this method
                # but since state is managed inside this method, we keep track
                # of it here.
                if self._limit_reached(internal_config, total_records_counter):
                    # Break from slice loop to save state and exit from _read_incremental function.
                    break

            yield self._checkpoint_state(stream_instance, stream_state, connector_state)
            if self._limit_reached(internal_config, total_records_counter):
                return

    def _as_airbyte_record(self, stream_name: str, data: Mapping[str, Any], namespace=None):
        now_millis = int(datetime.now().timestamp() * 1000)
        transformer, schema = self._get_stream_transformer_and_schema(stream_name)
        # Transform object fields according to config. Most likely you will
        # need it to normalize values against json schema. By default no action
        # taken unless configured. See
        # docs/connector-development/cdk-python/schemas.md for details.
        transformer.transform(data, schema)  # type: ignore
        message = AirbyteRecordMessage(stream=stream_name, data=data, emitted_at=now_millis, namespace=namespace)
        return AirbyteMessage(type=MessageType.RECORD, record=message)

**Comment by marcosmarxm** [comment]
This is fixed, please use latest version of Airbyte to use this feature.
