### ISSUE TITLE
Source Google Ads: user_location_view.country_criterion_id has incorrect JSON schema

### ISSUE THREAD

**Issue by shubhank-v** [airbytehq/airbyte#11184]
## Environment
- **Airbyte version**:  0.35.46-alpha
- **Deployment**: Kubernetes
- **Source Connector and version**:  Google Ads 0.1.28
- **Destination Connector and version**: S3 0.2.9
- **Severity**: Medium
- **Step where error happened**: Sync job 

## Current Behavior
Destination sync is failing while syncing the `user_location_view` table `country_criterion_id` to S3 destination.

## Expected Behavior
`country_criterion_id` type should be integer instead of a string.

Here's the Google Ads API reference [document](https://developers.google.com/google-ads/api/reference/rpc/v10/UserLocationView)

## Logs

<details>
<summary>LOG</summary> 

```

Syncing stream account_performance_report 0:00:09.645218
Syncing stream accounts 0:00:05.855254
Syncing stream ad_group_ad_report 0:17:32.094201
Syncing stream ad_group_ads 0:16:03.976155
Syncing stream ad_groups 0:02:07.724906
Syncing stream campaigns 0:01:08.030320
Syncing stream click_view 0:05:04.519747
Syncing stream display_keyword_performance_report 0:00:10.348991
Syncing stream display_topics_performance_report 0:00:11.030083
Syncing stream geographic_report 0:00:53.109884
Syncing stream keyword_report 0:01:40.848373
Syncing stream shopping_performance_report 0:00:14.373331
2022-03-15 05:08:33 [44msource[0m > Syncing stream: user_location_report 
2022-03-15 05:08:37 [43mdestination[0m > 2022-03-15 05:08:37 [1;31mERROR[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(accept):52 - Exception while accepting message
2022-03-15 05:08:37 [43mdestination[0m > tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field user_location_view_country_criterion_id is expected to be one of these: NULL, STRING. If this is a complex type, check if offending field: user_location_view_country_criterion_id adheres to schema.

```

</details>

## Steps to Reproduce
1. Create `Google Ads` Source and `S3` Destination connection
2. Sync `user_location_view` table

## Are you willing to submit a PR?

Yes.

**Comment by misteryeo** [comment]
@edgao as you're working on Google Ads

**Comment by edgao** [comment]
nice, thanks for the report! That explains the test failures I'm seeing in https://github.com/airbytehq/airbyte/pull/10919; will fix in that PR.
