### ISSUE TITLE
Integrate Support Portal into UI

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11187]
We want to add a separate "Support" menu into the UI on cloud. This should sit below the "Resources" menu, and contain two links:

* Chat with us -> Opening the intercom chat (the same as the "Chat with us" entry under resources does today). The button under "Resources" should be removed with this.
*  Submit a ticket -> Link to our new support portal: https://airbyte.com/contact-support

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/11745
