### ISSUE TITLE
Show beta/alpha connector label in more places

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11195]
We want to share the beta/alpha stage labels for connectors in more places around the UI.

1) In the sync overview:
![screenshot-20220316-134536](https://user-images.githubusercontent.com/877229/158592853-c74a4cbd-7da3-4e23-876b-9a466db6e734.png)

2) In the source/destination overview:
![screenshot-20220316-134611](https://user-images.githubusercontent.com/877229/158592966-8614a57f-7ad9-4ccc-8c0a-ad2860ef6280.png)

3) In the available sources/destinations under settings:
![screenshot-20220316-134728](https://user-images.githubusercontent.com/877229/158593169-065cec59-0941-416e-8931-6919d7f193e6.png)

**Comment by marcosmarxm** [comment]
Please add version too. Would be very helpful :p

**Comment by timroes** [comment]
@marcosmarxm Could you please open a separate issue for this. Also could you explain in this issue please what's the use-case why we'd expect users to be interested in the version of a connector in that specific places in the UI you'd like to have it added.
