### ISSUE TITLE
Source Salesloft: add new streams

### ISSUE THREAD

**Issue by yannibenoit** [airbytehq/airbyte#11198]
Context -> [message in slack](https://airbytehq.slack.com/archives/C01VDDEGL7M/p1647435938137639)

Would be cool to have data coming from other endpoints 

- [activities/email.json](https://developers.salesloft.com/api.html#!/Emails/get_v2_activities_emails_json)
- [groups.json](https://developers.salesloft.com/api.html#!/Groups/get_v2_groups_json)
- [steps.json](https://developers.salesloft.com/api.html#!/Steps/get_v2_steps_json)
- [notes.json](https://developers.salesloft.com/api.html#!/Notes/get_v2_notes_json)
- [team_templates.json](https://developers.salesloft.com/api.html#!/Team_Templates/get_v2_team_templates_json)

For example, one of the best challenge of cold/mass emailing practices is to preserve the domain name reputation and avoid to be detected as spammer

To prevent that we need to get a more data based on what airbyte offer :

- [activities/email.json](https://developers.salesloft.com/api.html#!/Emails/get_v2_activities_emails_json) -> for measuring deliverability and engagement (volume of email sent by day, bounce rate, click rate ...)
- [team_templates.json](https://developers.salesloft.com/api.html#!/Team_Templates/get_v2_team_templates_json) -> analyse content and detect if spamming words are added

**Comment by topefolorunso** [comment]
This has been fixed here https://github.com/airbytehq/airbyte/pull/11460 @justinbchau
