### ISSUE TITLE
Destination Postgres: error when schema start with number

### ISSUE THREAD

**Issue by solumnsilence** [airbytehq/airbyte#11207]
## Environment
- **Airbyte version**:  example is 0.35.39-alpha
- **OS Version / Instance**: Ubuntu 18.04, GCP e2-medium.
- **Deployment**: Docker deployment.
- **Destination Connector and version**: Postgres 0.3.15.
- **Severity**: Medium.
- **Step where error happened**: Setup new destination.

## Current Behavior
*Airbyte can't create a destination if there are numbers at the beginning of the schema name.*

## Expected Behavior
*The destination must be created even with a schema name that starts with numbers.*

## Steps to Reproduce
1. Change validation of the schema name for the Postgres destination type.

## Are you willing to submit a PR?
Yes, but I only write Python code, so it's great if I can help.

**Comment by marcosmarxm** [comment]
[Slack convo](https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1647423079088759)

![image](https://user-images.githubusercontent.com/5154322/158717614-e2c82ae0-a7f0-42a0-a843-7a1b28cedd50.png)
