### ISSUE TITLE
[Unexpected state] Delete connection

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#11214]
## Tell us about the problem you're trying to solve

Temporal can be in an unknown state because of a bug. This ticket is about addressing the scenario where no workflow exists and a delete connection is submitted.

This ticket is about implementing [this](https://docs.google.com/document/d/1I_uY1ML087HUwP2s55lOoEVb4DyVXzZZMjRX1WEwaVk/edit#heading=h.7sn6f6ucy8lp) diagram. 

## What is expected

When trying to submit a delete connection, if in the `TemporalClient` we detect that there is no existing temporal workflow, need to:
- Create a new workflow
- Submit a delete connection using a signal

No modification is expected in the `ConnectionManagerWorkflow`.

**Comment by terencecho** [comment]
acceptance test for this was added here: https://github.com/airbytehq/airbyte/pull/11563
