### ISSUE TITLE
[Unexpected state] Start manual reset

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#11216]
## Tell us about the problem you're trying to solve

Temporal can be in an unknown state because of a bug. This ticket is about addressing the scenario where no workflow exists and a manual reset is submitted.

This ticket is about implementing [this](https://docs.google.com/document/d/1I_uY1ML087HUwP2s55lOoEVb4DyVXzZZMjRX1WEwaVk/edit#heading=h.5bra1f7oarq6) diagram. 

## What is expected

When trying to submit a manual reset, if in the `TemporalClient` we detect that there is no existing temporal workflow, need to:
- Create a new workflow
- Submit a manual reset using a signal

No modification is expected in the `ConnectionManagerWorkflow`.

**Comment by pmossman** [comment]
@davinchia doing some backlog cleaning, is this something you're actively working on or should we ask the OSS team to take it back over?

**Comment by davinchia** [comment]
Not actively working on this. We should ask the team to take it back over. Thanks!
