### ISSUE TITLE
🐙 octavia-cli: docker hub image airbyte/octavia-cli:0.1.0 built only for OS/Arch `linux/arm64/v8`

### ISSUE THREAD

**Issue by nmacri** [airbytehq/airbyte#11210]
## Environment
- **Octavia version**: 0.1.0 (alpha)
- **OS Version / Instance**:  linux/amd64 (Debian 10, Intel Broadwell, GCP VM)
- **Deployment**: Docker
- **Severity**: Medium 
- **Step where error happened**: Deploy 

## Current Behavior

The [docker hub image `airbyte/octavia-cli:0.1.0`](https://hub.docker.com/r/airbyte/octavia-cli) is built for a target architecture linux/arm64/v8 and raises an error when deployed to more conventional `linux/amd64` hosts

Image details
- Tag: 0.1.0
- Digest: sha256:e614aa99cbdcfafba417edd8353cdf50bb13ceb801464fa0a2209de29e6a96a1
- OS/Arch: linux/arm64/v8

## Expected Behavior

Most of the other airbyte images in docker hub (e.g. [airbyte/webapp](https://hub.docker.com/r/airbyte/webapp)) are built for `linux/amd64`

## Logs / Steps to Reproduce

Command to launch the container
```
> docker run -i --rm -v /my-octavia-project:/home/octavia-project --network host -e AIRBYTE_URL="http://localhost:8000" airbyte/octavia-cli:0.1.0 -c apply
```

Observed output
```
work host -e AIRBYTE_URL="http://localhost:8000" airbyte/octavia-cli:0.1.0 -c apply
Unable to find image 'airbyte/octavia-cli:0.1.0' locally
0.1.0: Pulling from airbyte/octavia-cli
279a020076a7: Pull complete 
035530c61301: Pull complete 
430f5ca6cd82: Pull complete 
594f692a6b57: Pull complete 
70b1dc4462d0: Pull complete 
2335a7ff9e94: Pull complete 
e842140ae4de: Pull complete 
6c09a195d162: Pull complete 
a68e1d89bf22: Pull complete 
bc80abcf5ac8: Pull complete 
d4d76138afc8: Pull complete 
Digest: sha256:e614aa99cbdcfafba417edd8353cdf50bb13ceb801464fa0a2209de29e6a96a1
Status: Downloaded newer image for airbyte/octavia-cli:0.1.0
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host pla
tform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by marcosmarxm** [comment]
@alafanechere fyi thanks @nmacri
