### ISSUE TITLE
[Unexpected state] Ensure that we start from a clean state

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#11217]
## Tell us about the problem you're trying to solve

Temporal can be in an unknown state because of a bug or a migration. This ticket describe the reset of a state.

## What is expected

When starting a workflow, we need to ensure that we are starting from a "clean" state. A clean state describe a clean job status. It means that all the currently running workflow needs to be doing that.

## Why are we doing that

There is 2 scenario where this is relevant:
- Of the temporal workflow failed unexpectedly
- Upon migrating from the legacy scheduler to temporal

In both of the scenario, we can have a temporal workflow that start running with a non updated job status. We know that the job is actually not running and thus fail. We need to force the update of the job and the related attempt to fail.

## What need to be done

For the first run of the job, we need to run 2 temporal activity:
- one to fetch all the the RUNNING job
- One to fail the job and their related attempt
This could be in a single activity as well.

In order to detect that the workflow is starting we will need to add a new input parameter in order to be able to differentiate the start from a continue as new.

Out of precaution, the call of the new activity(ies) needs to be versionned.

**Comment by lmossman** [comment]
With the merge of [this change](https://github.com/airbytehq/airbyte/pull/13071), I believe all unexpected states are now covered by temporal. Closing this out!
