### ISSUE TITLE
Airbyte Deployment using helm chart - Unable to execute HTTP request: airbyte-minio

### ISSUE THREAD

**Issue by Shubham21k** [airbytehq/airbyte#11230]
Environment
- Airbyte version:  0.35.42-alpha
- Deployment: Kubernetes deploy using helm charts
- Step where error happened: Deploy 
 
Current Behavior
While deploying airbyte on kubernetes, airbyte worker pod is showing `Readiness probe failed: Get "http://10.5.18.26:9000/": dial tcp 10.5.18.26:9000: connect: connection refused
Back-off restarting failed container.`

We are using s3 for logging and have also disabled minio. But, in the worker logs we are getting warnings due to failure in HTTP request execution to minio. 

Since minio is disabled, we don't expect worker to establish any connection to minio.

## Logs
In the airbyte worker logs : 
`2022-03-17 10:37:10 INFO i.t.s.WorkflowServiceStubsImpl(<init>):188 - Created GRPC client for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=109, target=airbyte-temporal:7233}}
2022-03-17 10:37:10 WARN i.a.w.t.TemporalUtils(getTemporalClientWhenConnected):185 - Waiting for default namespace to be initialized in temporal...
Cannot start publish with com.van.logging.aws.S3PublishHelper@1742686e due to error: Cannot start publishing: Unable to execute HTTP request: airbyte-minio
Cannot end publish with com.van.logging.aws.S3PublishHelper@1742686e due to error: Cannot end publishing: Cannot publish to S3: Unable to execute HTTP request: airbyte-minio`

Please help us figure this out.

**Comment by KPhans** [comment]
Was this resolved? I think I am having the same error

**Comment by sfc-gh-pkommini** [comment]
@Shubham21k How did you resolve this error?
