### ISSUE TITLE
Video tutorial for the Google Ads connector

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#11233]
From Slack (https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1647375604441509) 

Error at authorization:
You cannot sign in with this app, because it is not compliant with the Google OAuth 2.0 requirenments.
You can contact the app developer directly to make him/her aware that at least one validation rule was not satisfied.
the code below is the error code
redirect_uri

Suggestion:
Create a video tutorial for the Google ads connector and link it in the docs

**Comment by juferafo** [comment]
Hello,

I am struggling with setting up the Google Ads connector and I am getting the same error. I think that a video tutorial including how to get the refresh token would be great. 

Thanks!
