### ISSUE TITLE
🐛 Source Gitlab: Connector is not working for Groups with Subgroups and Projects

### ISSUE THREAD

**Issue by pilayar76** [airbytehq/airbyte#11248]
## Environment
- **Airbyte version**:  0.35.45-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: (if applicable example Gitlab 0.1.3) 
- **Destination Connector and version**: (if applicable example MySQL 0.1.18) 
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
*It picks up only the immediate projects under a parent group but if a group has sub-groups and those sub-groups has projects, it does not pick*

## Expected Behavior
*Recursively projects should be picked up if we specify the parent group including the subgroups*

## Steps to Reproduce
1. Create a group and subgroup
2. Create a project under Group
3. Connect to Airbyte

## Are you willing to submit a PR?
Yes, I am willing to.

**Comment by davydov-d** [comment]
hey @pilayar76 
I tried to reproduce this issue but succeeded only when there's a list of `group_id` in the input config. Is that the case for you?
If yes, I wonder if we should treat it as a bug or not. @misteryeo do you think we should sync projects of a group's subgroups if there's a definitive list of groups IDs (containing only top level group IDs) in the input config?

**Comment by pilayar76** [comment]
Thanks @davydov-d  for picking this up.

Yes, that's the expectation.
