### ISSUE TITLE
Migrate Postgres (and AbstractJDBCSource) to use Incremental

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1127]
At the end of this postgres should sync data incrementally. It is not required that all sources that use abstractjdbcsource sync incrementally (though hopefully it will be relatively straightforward for someone else to pick up how they would do that based on how postgres is done).

**Comment by ChristopheDuong** [comment]
destination-jdbc handles incremental and postgres is based on it in https://github.com/airbytehq/airbyte/pull/1173
