### ISSUE TITLE
Syncs aren't automatically triggered by Scheduler

### ISSUE THREAD

**Issue by lsoica** [airbytehq/airbyte#11276]
## Environment
- **Airbyte version**:  example is 0.35.53-alpha
- **Deployment**: Kubernetes
- **Source Connector**: Custom REST API connector
- **Destination Connector and version**: PostgreSQL 0.3.15
- **Step where error happened**: Sync job

## Current Behavior
I have 2 connections, from a custom RestAPI Source to PostgreSQL destination.
The connections are configured with a 5 mins sync frequency

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1623282/159172698-2189a44f-e5ba-46df-a62f-0ef93a223d08.png">

Although the manual sync works fine, the automatic sync is never triggered.

## Expected Behavior
Sync should be triggered for every 5 minutes.

**Comment by marcosmarxm** [comment]
@lsoica can you share the connection history page for both connections? Maybe with 5 min sync frequency one connection is not finished and only add to the queue.

**Comment by lsoica** [comment]
@marcosmarxm here it is :
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/1623282/159851871-14480a17-2206-4b1f-96ff-e3b5b9dd02de.png">

**Comment by yoav-getloam** [comment]
I'm experiencing the same, were you able to resolve this issue?

**Comment by marcosmarxm** [comment]
@lsoica , @yoav-getloam and @satyavarma can you try latest Airbyte version with new scheduler?

**Comment by cgardens** [comment]
closed due to inactivity. feel free to reopen if it persists.
