### ISSUE TITLE
The last page of records is inserted twice (any source connector without primary key definition, postgres destination connector)

### ISSUE THREAD

**Issue by ralphiech** [airbytehq/airbyte#11273]
## Environment
- **Airbyte version**:  0.35.57-alpha
- **OS Version / Instance**: Ubuntu 20.04.4 LTS
- **Deployment**: Docker
- **Source Connector and version**: custom connector I work on
- **Destination Connector and version**: Postgres 0.3.15
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
I have a custom connector connecting to our CRM. The limit of returned records by the CRM system are 100 per call. I have 1718 records. If do not have a primary key defined in the source, so all data is appended.

The first call returns 1718 correctly. If I run sync again, my row count will go up to 3454. 

## Expected Behavior

The first call returns 1718 correctly. If I run sync again, my row count will go up to 3436. 

## Expected Behavior

Airbyte or the Postgres connector seems to insert the last batch it has received (18 rows) twice

## Steps to Reproduce

1) Use paging on any source connector without a primary key definition. The source system should at least return two pages of results, for example 100 records per page and the system contains 120 records in total
2) Use the postgres destination connector
3) Check the row count after the first sync run. In the above example we see 120 records
4) Check the row count after a 2nd sync run, you will see 260 records (which is wrong, we should see 240 records)

**Comment by marcosmarxm** [comment]
I'm closing due inactivity, @ralphiech if the issue persists please open a new issue and provide a code example of your connector. This issue doesn't appears in others sources connectors build by Airbyte.
