### ISSUE TITLE
Source Google Sheets sync job fails when all data is deleted from one of the sheets

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#11271]
## Environment
- **Deployment**: Docker
- **Source Connector and version**: Source Google Sheets version 0.2.9
- **Severity**: Medium
- **Step where error happened**: Sync job

### Steps to reproduce:
 1. Set up a connection with Google Sheets source and some data
 2. Run initial sync job
 3. Open the Google Sheets document and delete all data including column headers from one of the sheets (e.g. make the sheet completely empty) that are set up as streams
 4. Run the sync job again

Result: all subsequent sync jobs that run after step 3 will fail

## Expected Behavior
Sync job should succeed and log a message saying that no data was found in one of the streams

## Logs

<details>
<summary>logs-52.txt file attached below</summary> 

</details>

## Are you willing to submit a PR?
Yes
[logs-52.txt](https://github.com/airbytehq/airbyte/files/8308172/logs-52.txt)

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/pull/23272
