### ISSUE TITLE
New Source: Pivotal Tracker need credentials

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#11281]
## Tell us about the new connector you’d like to have
Need sandbox credentials for Pivotal Tracker #11060

**Comment by harshithmullapudi** [comment]
@igrankova can you help here

**Comment by igrankova** [comment]
@harshithmullapudi, contacted to support team and asked the Sandbox account for us. waiting for the response.

**Comment by igrankova** [comment]
@harshithmullapudi, please check creds in the LastPass, name: Pivotal Tracker OAuth

**Comment by harshithmullapudi** [comment]
Sure thank you @igrankova

**Comment by igrankova** [comment]
@harshithmullapudi have you had a chance to check creds? is this issue still actual or we can close it?
