### ISSUE TITLE
Revise Request a New Connector form

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11280]
# Current
We require a user to fill out both the Connector name and the connector website when Requesting a new connector. (screenshot below)

<img width="510" alt="Screen Shot 2022-03-20 at 10 24 20 PM" src="https://user-images.githubusercontent.com/38087517/159197810-2cdfe0f6-3609-4b5a-b045-97ff775163e3.png">

Our observation from Fullstory indicates users are dropping off from the form and not submitting it, even though they open it multiple times. 

# Proposed
Make the website field optional and only require the connector name.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
