### ISSUE TITLE
Salesforce Setup Guide redirects incorrectly

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11304]
## Current Behavior
Clicking "Setup Guide" in the Cloud application causes an error in the page and the sidesheet does not load.
https://www.loom.com/share/11387e24e27144909b88402e36d6c93f.

This only happens for Salesforce - not the other sources.

## Expected Behavior
The setup guide for Salesforce should load within the window

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
