### ISSUE TITLE
Redo the "bulk edit streams" feature

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11310]
We recently introduced a change that allows users to edit multiple streams at the same time during connection setup. The current implementation does not have a great UX, and we should redo it as part of redesigning some of the UI. A couple of points that came up more often from user:

* Clicking the "apply" button before changing anything is very unintuitive.
* The colors in that UI are confusing (e.g. purple buttons on purple backgrounds).
* It's not entirely clear sometimes how the "edit multiple" interacts when the streams table is filtered down (also often brought up in the context that the search on the stream table in general seems to be confusing and not clear that the table is atm filtered).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
Including this gif that shows a strange interaction where the menu shows up, pushing the rows in the table down. 

![2022-04-11_17-47-16 (1)](https://user-images.githubusercontent.com/633226/163489209-a91de1e0-56da-4cf2-86c3-741e245a4494.gif)

**Comment by edmundito** [comment]
Reviewed with @andyjih  - Will be addressed in the redesign
