### ISSUE TITLE
Fix link logic in documentation panel

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11313]
The way links are currently handled in the documentation sidepanel for connectors is having several issues.

* It's not properly working for fragment-only URLs (quick fix preventing an app crash in https://github.com/airbytehq/airbyte/pull/11312)
* Absolute URLs are turned into relative URLs within the airbyte application.
* Potential other edge cases not handled.

Problematic code: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/Connector/ServiceForm/components/Controls/Instruction.tsx#L74-L79

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
