### ISSUE TITLE
[EPIC] Improve database sources & destinations error messages

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11322]
## Tell us about the problem you're trying to solve
When users are setting up a database connector and fail (due to misconfiguration) they are often provided a non-descriptive error message like the following: 
![image](https://user-images.githubusercontent.com/6246757/159535845-8d017efd-d7f4-46c5-b03d-7a0dd8fc2c21.png)

This causes drop off in activation when users are trying out Airbyte. We'd like to make these error messages more descriptive as they can greatly increase the usage of Airbyte. 

## Describe the solution you’d like
I would like these error messages to be much more descriptive in the following connectors (ordered by priority): 
**Sources**: 
* Postgres 
* MySQL 
* MSSQL
* Snowflake
* Mongo
* File source
* Oracle

**Destinations**:
* Redshift
* GCS
* MySQL
* Postgres
* Mongo

I imagine the best way to achieve this: 
1. Induce as many configuration failures as we can think of in test cases
2. Identify which error messages returned by the database correspond to which errors
3. Return helpful error messages from the `check` method to help the user understand the action they can take to fix the problem
4. Write test cases to ensure that these error messages are always helpful to the user

Some error cases we can run into (this is not comprehensive, just the ones I can think of right now): 

- Wrong password (but correct everything else)
- Wrong username (but correct everything else)
- Wrong host (but correct everything else)
- Wrong port (but correct everything else)
- Wrong database name (but correct everything else)
- No permissions on the selected schema/DB/table
- Any other incorrect / incompatible settings

**Comment by tuliren** [comment]
More examples can be found in [this slack thread](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1650666613696049).

**Comment by grishick** [comment]
The fix should probably use the new AirbyteTraceMessage that is being added to the protocol: https://github.com/airbytehq/airbyte/pull/12458

**Comment by Phlair** [comment]
@grishick I'm currently working [on this](https://github.com/airbytehq/airbyte/issues/12471) to create AirbyteTraceMessage functionality for Java connectors, after which it can be used to create the improved errors as per this issue.

Had an idea for some incremental value here by doing this: https://github.com/airbytehq/airbyte/issues/12538
We looked at it in backlog grooming and think that ticket likely fits better in dbs & dws connector team, just fyi.

**Comment by alexandr-shegeda** [comment]
PR is already available for review [here](https://github.com/airbytehq/airbyte/pull/11927)

**Comment by grishick** [comment]
Are this ticker and PR still active?

**Comment by mkhokh-33** [comment]
yes, will merge last updates form master
