### ISSUE TITLE
Shopify app approval

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#11334]
Shopify must approve our app application.

Oustanding issues are
1. App must set security headers to protect against clickjacking.
Your app must set the proper [frame-ancestors content security policy directive](https://shopify.dev/apps/store/security/iframe-protection) to avoid clickjacking attacks. The 'content-security-policy' header should set frame-ancestors https://[shop].myshopify.com https://admin.shopify.com, where [shop] is the shop domain the app is embedded on.

2. App must verify the authenticity of the request from Shopify.
Expected HTTP 401 (Unauthorized), but got HTTP 200 from https://cloud.airbyte.io/partner/v1/shopify/shop/redact. Your app's HTTPS webhook endpoints must validate the HMAC digest of each request, and return an HTTP 401 (Unauthorized) response when rejecting a request that has an invalid digest. [Learn more about verifying a webhook](https://shopify.dev/apps/webhooks/https#verify-a-webhook)

- [x] security headers are added to all shopify endpoint. more info on testing this: https://shopify.dev/apps/store/security/iframe-protection
- [x] request authenticity is validated for all shopify webhook endpoints
- [x] go through requirements and make sure we're not missing anything else

**Comment by girarda** [comment]
The app was submitted for review on 03/25. We're waiting for an update on their end

**Comment by sherifnada** [comment]
After a couple of back & forths, still in review by the Shopify team

**Comment by mhbw** [comment]
just want to say I love this tool, and as a Shopify client, love seeing this is in progress! Thanks all.

**Comment by sherifnada** [comment]
update: our app is still in review. 

the main blockers right now are:
1. Shopify is requiring that we process any payments customers make to us to use the shopify connector through their billing API. e.g the customer puts their credit card in shopify, and when they want to use it in Airbyte, we call their API, and shopify pay us out based on the customer’s.
2. shopify is requiring that we do oauth by redirecting the customer to the shopify UI, having them install our app from the Shopify appstore directly, then having Airbyte somehow figure out what their shop URL etc..

**Comment by sherifnada** [comment]
@misteryeo assigning this to you for now to take the lead on making inroads with Shopify -- happy to help where I can here

**Comment by Echecivuole** [comment]
> Shopify must approve our app application.
> 
> Oustanding issues are
> 
> 1. App must set security headers to protect against clickjacking.
>    Your app must set the proper [frame-ancestors content security policy directive](https://shopify.dev/apps/store/security/iframe-protection) to avoid clickjacking attacks. The 'content-security-policy' header should set frame-ancestors https://[shop].myshopify.com https://admin.shopify.com, where [shop] is the shop domain the app is embedded on.
> 2. App must verify the authenticity of the request from Shopify.
>    Expected HTTP 401 (Unauthorized), but got HTTP 200 from https://cloud.airbyte.io/partner/v1/shopify/shop/redact. Your app's HTTPS webhook endpoints must validate the HMAC digest of each request, and return an HTTP 401 (Unauthorized) response when rejecting a request that has an invalid digest. [Learn more about verifying a webhook](https://shopify.dev/apps/webhooks/https#verify-a-webhook)
> 
> * [x]  security headers are added to all shopify endpoint. more info on testing this: https://shopify.dev/apps/store/security/iframe-protection
> * [x]  request authenticity is validated for all shopify webhook endpoints
> * [x]  go through requirements and make sure we're not missing anything else

Hi @girarda we hai the same issue of your point 2 and Shopify support is rejecting every time without telling us how to replicate their test! You will be loved by Mokapen team if you can tell us how to fix this issue :) thanks!

**Comment by girarda** [comment]
@Echecivuole I don't have much insights into what shopify does on their end either.

We tested this on our end by
1. sending a valid request and validate the computed hmac matches the one in the header
2. sending an invalid request and validate the computed hmac does not match the one in the header. You can try many variations of this by mutating either the hmac in the header or the body

**Comment by bazarnov** [comment]
@girarda Did we get the approval? What is the status of this issue?

**Comment by girarda** [comment]
The last update I have on this issue is from April. @YowanR is there an ongoing discussion with Shopify?

**Comment by YowanR** [comment]
@girarda Not at the moment, no. Let me ramp up a little bit there and then re-engage with Shopify. 
@bazarnov To make sure I understand, what do we miss if we don't get the shopify app approval? Is it only OAuth? Can we still support API key in the meantime?

**Comment by girarda** [comment]
@YowanR we're not allowed to support API key auth on Cloud. This ticket has a bit more context https://github.com/airbytehq/airbyte/issues/8633#issuecomment-1053849175

**Comment by YowanR** [comment]
I see. I'm starting to better understand the full picture now. We need this app approved to get OAuth and to get OAuth, we disable API key auth. So now, we are 100% relying on Shopify to get us approved before we can do anything. Let me re-engage with Shopify. FYI @ycherniaiev @igrankova

**Comment by sherifnada** [comment]
@YowanR the main blocker with shopify isn't removing API key auth in cloud (that's pretty doable), it's the issues mentioned in this link https://github.com/airbytehq/airbyte/issues/11334#issuecomment-1104689324

**Comment by YowanR** [comment]
Oh I see. That's quite a lot of overhead for us to support this connector then. We have restarted the process but if these are the blockers, then this will require work from a lot of different teams. @sherifnada Do you know how Fivetran or other competitors handle this?

**Comment by sherifnada** [comment]
when I asked, Shopify said that these were newer regulations, and that Fivetran will "eventually" have to become compliant with them. I don't quite buy it but we'll see :P

**Comment by bazarnov** [comment]
The Airbyte app got its approve for a public app. Closing this now.
