### ISSUE TITLE
Store the connector version in the DB

### ISSUE THREAD

**Issue by Javier162380** [airbytehq/airbyte#11345]
## Tell us about the problem you're trying to solve
Airbyte, the normalization process injects some metadata fields in the Database that are useful to guarantee the data quality and the integrity of datasets, like ```_airbyte_emitted_at``` or ```_airbyte_normalized_at```.

These data fields are useful to check the freshness state of a table but are not useful, to identify the different data models changes over the same dataset.

## Describe the solution you’d like

To guarantee better metadata management and monitoring over schemas changes, I would add a new field to all tables ``` _airbyte_connector_version``` this way, we could audit per raw which is the data model. Moreover, downstream data modeling macros could be done in DBT for instance, using this field when the schemas change from an API impacts the business model.  

## Describe the alternative you’ve considered or used
It is on the user side, and it will be create a table with the connector version suffix every time or optionally a connector version changes. I don't like this solution because the DWH will end up really ugly.

## Are you willing to submit a PR?

Remove this with your answer :Yes!!

**Comment by grishick** [comment]
Thank you for the idea! It sounds reasonable. Please tag me in the PR when you submit it.

**Comment by ChristopheDuong** [comment]
Another approach could be to add a sync id associated with all records written in the same batch.

This sync id could then be used to join to some other metadata table with more information such as the connector version that was used to produce it but also the catalog/configuration too, etc

This idea would become related to schema changes, so @grishick, you might want to check with @andyjih that is looking into schema evolution?

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
