### ISSUE TITLE
Destination ElasticSearch: allow usage of Private CA Certificate

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#11356]
## Tell us about the problem you're trying to solve
For some cases users have a more restricted access to their ElasticSearch cluster and need private keys.

## Describe the solution you’d like
Add an option to upload the key file OR paste the key in a field in the destination configuration.
There are other destination examples using private keys already.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Not this time.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/11356?planning-poker) with Zenhub @edgao @ryankfu @suhomud

**Comment by grishick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/11356?planning-poker) with Zenhub @etsybaev

**Comment by etsybaev** [comment]
https://github.com/airbytehq/airbyte/pull/18177
