### ISSUE TITLE
Enlarge CTAs on new Source, Destination, and Connection Pages

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11401]
# Current
Users who have not set up anything for Airbyte (no source, destination yet) tend to click around the platform to explore.  They encounter pages that are empty except for Octavia, with a speech bubble, pointing to the New Source/Destination/Connection buttons.

#Proposed Solution
The CTAs for the /source, /destination, and /connection can be displayed more prominently on the page (center and large), with Octavia drawing more attention to it.

We can also modify Octavia to remove her speech bubble (as users may think this is just a part of the graphic, rather than the direction as suggested by @timroes) and move this to be text on the page itself.

Link to design: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/Web-app?page-id=26178%3A0&node-id=32933%3A156966&viewport=305%2C48%2C1&scaling=min-zoom&starting-point-node-id=32933%3A156608&show-proto-sidebar=1

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This has been implemented nowadays. Closing this.
