### ISSUE TITLE
Connection Page Tooltips Not Appearing

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#11407]
**Problem**
The info tooltips that I would expect to appear on hover doesn't happen:
![Airbyte Connections Salesforce Demo → Snowflake Demo 2022-03-24 at 1 24 09 PM](https://user-images.githubusercontent.com/16851149/160003737-9aa13564-70f8-452b-a6c1-cfc79b733c12.jpg)

**Expectation**
When I hover over these (i) icons, I should see more information about that field.

**Comment by Jamakase** [comment]
@misteryeo I just checked it and it appears on hover. Could you provide a bit more info which browser you are using or when you face that behaviour.

**Comment by misteryeo** [comment]
@Jamakase Hmm that's strange, I checked it now and the tooltips appear now. We can close this now - thank you!
