### ISSUE TITLE
Credentials for Bamboo HR Source

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#11411]
## Tell us about the problem you're trying to solve
Today we have only a trial account for this source, after 14 days the CI is going to start failing.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by igrankova** [comment]
Received invoice for sandbox and transferred to pay.
Sandbox creds: 
URL: [https://airbytetest.bamboohr.com/](https://sl.bamboohr.com/t/10754/c/3e2ba020-6f05-4c8d-b316-0a2f87750361/NB2HI4DTHIXS6YLJOJRHS5DFORSXG5BOMJQW2YTPN5UHELTDN5WS6===/airbytetest-bamboohr-com)
Username: [sherif@airbyte.io](mailto:sherif@airbyte.io)
Password: Bamboo1234

**Comment by igrankova** [comment]
The payment details are added and the payment is done.
