### ISSUE TITLE
Apply buffering changes to Snowflake Destination using GCS staging

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#11428]
## Tell us about the problem you're trying to solve
As part of https://github.com/airbytehq/airbyte/issues/10260, replace `SnowflakeCopyGcsDestination` by `SnowflakeGcsStagingDestination` that use serialized buffering strategy.

**Comment by alexandr-shegeda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/11428?planning-poker) with ZenHub @VitaliiMaltsev

**Comment by grishick** [comment]
@VitaliiMaltsev I see this issue is in review for Airbyte, but I do not see a link to a PR. What do we need to review?

**Comment by VitaliiMaltsev** [comment]
@grishick added a link for PR
