### ISSUE TITLE
 Apply buffering changes to Redshift Destination 

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#11426]
## Tell us about the problem you're trying to solve
As part of https://github.com/airbytehq/airbyte/issues/10260, refactor destination-redshift to use serialized buffering strategy.

**Comment by grishick** [comment]
@VitaliiMaltsev could you please link the pull request to this issue?

**Comment by VitaliiMaltsev** [comment]
@grishick sorry i'm not familiar with Zenhub and don't know how to link PR here. You can review linked PR on Github https://github.com/airbytehq/airbyte/issues/11426

**Comment by grishick** [comment]
@VitaliiMaltsev linking a PR to an issue is a basic Github feature and does not require ZenHub. There is a Development section on the right side of the GitHub UI where you can link PRs to Issues and vice versa. Looks like @alexandr-shegeda just did that. Thanks @alexandr-shegeda !
