### ISSUE TITLE
SAT: improve incremental test

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11459]
## Tell us about the problem you're trying to solve
The current SAT incremental test does a very simple assertion to verify that incremental sync works: it runs a full incremental sync, then gets the last STATE message output by the connector, runs a second sync with that STATE as input, then expects no records to be output. 

This is not a very robust test due to how simple it is. 

## Describe the solution you’d like
If an incremental sync outputs many `STATE` messages, then re-run the sync with the last N such messages, and assert that only records which were output after that message in the initial sync were output. 

For example, let's say you run the first incremental sync and get the following output (`R` means `RECORD` message, `S` means `STATE` message): 
```
R1, R2, S1, R3, R4, S2, R5, R6, S3
```

Then if I run the sync again with S1 as input, I would expect R3-6 to be output. If I run it with S2 as input, I expect only R5-6. If I run it with S3 I expect no output. 

We can probably use a variant of this to make this test a lot more robust.

**Comment by girarda** [comment]
Implementation steps:
1. pick a source that supports incrementals and overloads `stream_slices`, and pull the config from lastpass to a `secret` directory.
2. run the acceptance test from the source's root directory to confirm they work as expected:
    * `docker build . -t airbyte/source-<connector>:dev && python3 -m pytest integration_tests -p integration_tests.acceptance`
    * you can temporarily remove extraneous tests from `acceptance-test-config.yml` if the tests hinder the iteration speed
3. Create a new test that should be similar to `TestIncremental.test_two_sequential_reads`
   1. `output = docker_runner.call_read(connector_config, configured_catalog_for_incremental)`
   2. Partition the output such that the first message of each batch is a state message
       Something like `[output[index:] for index,msg in enumerate(output) if msg.type == Type.STATE]` should do the trick
   3. For each batch, call `docker_runner.call_read` with the state being the batch's first message
   4. Assert the output of the read contains all messages from the batch (except the initial state), and none of the messages from the previous batches
4. It should now be fine to delete `TestIncremental.test_two_sequential_reads`

**Comment by sherifnada** [comment]
Notes from backlog grooming: we should also expose a flag which allows the tests to do the comparison without regard to ordering

**Comment by girarda** [comment]
notes from backlog grooming: this ticket is only scoped to verifying GA connectors

**Comment by sherifnada** [comment]
we should also make this turned on by default in all new connectors
