### ISSUE TITLE
Source Freshdesk: migrate to use CDK

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11456]
## Tell us about the problem you're trying to solve
The connector was written way before the current CDK version and is using outdated patterns. 

## Describe the solution you’d like
it should be re-written using the latest CDK patterns

**Comment by lgomezm** [comment]
I've claimed this issue.

**Comment by lgomezm** [comment]
I've submitted this PR to address this issue: https://github.com/airbytehq/airbyte/pull/12334
