### ISSUE TITLE
Survey Monkey Response Stream (Incremental Setting) does not pull all responses for a survey

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#11453]
## Environment
- **Airbyte version**:  0.35.50-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Survey Monkey 0.1.7
- **Destination Connector and version**: 0.4.17
- **Severity**: Critical
- **Step where error happened**: Sync

## Current Behavior
When a response stream is configured for "full-refresh" / "overwrite", all responses are pulled for a survey. However, when the response stream is configured for "incremental", it does not pull all responses, even if it is the first sync.

## Expected Behavior
I expect the same amount of responses pulled for the first sync irrespective of the stream configuration.

## Logs
<img width="1286" alt="Screen Shot 2022-03-23 at 7 20 27 pm" src="https://user-images.githubusercontent.com/33811744/160273494-7c8db944-eebd-44c4-a374-9d9e2491eea8.png">

## Steps to Reproduce
1. Configure response stream as incremental
2. Sync
3. Reset
4. Configure response stream as full-refresh/overwrite,
5. Sync
6. Obverve difference

## Are you willing to submit a PR?
No

**Comment by danieldiamond** [comment]
@marcosmarxm is there someone that understands _incremental_ streams that can apply the same logic for the survey monkey stream?

All other sources have incremental streams working correctly so I imagine it's just that this specific one is outdated e.g. applying [GoogleAds Incremental logic](https://github.com/airbytehq/airbyte/blob/838af6fe6ad67e2b32b4deaa3748831887032f64/airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py#L110) here.

Taking a step back, it's probably worth creating some base classes for the incremental stream (appreciating that each source has it's on limitations/configurations).

**Comment by alafanechere** [comment]
Hi @danieldiamond, the most up-to-date way of implementing incremental streams with our CDK is to use [`IncrementalMixin`classes](https://docs.airbyte.com/connector-development/cdk-python/incremental-stream/#incrementalmixin). 
In the SurveyMonkey context the `SurveyResponse` stream is overriding the default (and now legacy) `get_updated_state` function defined in `IncrementalSurveymonkeyStream` and tries to manage nested cursor (one cursor per Survey). I think the error lies in this function and this logic. I would suggest to rewrite this stream by leveraging [IncrementalMixin]((https://docs.airbyte.com/connector-development/cdk-python/incremental-stream/#incrementalmixin) and [HTTPSubstreams](https://docs.airbyte.com/connector-development/cdk-python/http-streams#nested-streams--caching). The Stripe connector could be a good example for the use of `HttpSubstream`.
