### ISSUE TITLE
S3 Destination ignoring s3_path_format argument

### ISSUE THREAD

**Issue by leoalmeidasant** [airbytehq/airbyte#11482]
## Environment
- **Airbyte version**:  example is 0.35.59-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Destination Connector and version**: s3-destination 0.2.12
- **Severity**: medium
- **Step where error happened**: Sync job

## Current Behavior
After upgrading s3 destination connector from 0.2.10 to 0.2.12, the output ignoring argument `s3_bucket_path ` in s3 path.
```
S3 Bucket Name = bucket-example
s3_bucket_path = foo
ouput_path will be s3://bucket-example/${SOUCE_NAMESPACE}/${STREAM_NAME}
```

## Expected Behavior
output_path should be `s3://bucket-example/foo/${SOUCE_NAMESPACE}/${STREAM_NAME}`

## Steps to Reproduce
1. create a source
2. create destination and keep empty the field `s3_path_format`
3. create a connection and sync

**Comment by ChristopheDuong** [comment]
Thanks for the report!

Sorry about that, I'm going to merge the "old" `s3_bucket_path` and "new" `s3_path_format` fields together then

**Comment by ChristopheDuong** [comment]
Thanks for reporting this!
