### ISSUE TITLE
Edit title of source/destination dropdown

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11487]
# Current
The current title for the source and destination dropdown is "Source Type" or "Destination Type", and we see users scrolling through the alphabetically organized list, rather than searching for the connector they have in mind.

![Screen Shot 2022-03-28 at 6 12 35 PM](https://user-images.githubusercontent.com/38087517/160495854-075840f1-6137-44ba-ab2b-21d2b109ebcb.png)

# Proposed
Modify the text above the dropdown selection to say:  “Type to search for a connector” to show users they can use the dropdown as a search bar as well as a dropdown.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
