### ISSUE TITLE
Source Amazon Ads: correct integration tests

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#11490]
To merge [community contribution](https://github.com/airbytehq/airbyte/pull/10513) I needed to remove a few tests because we don't have permissions anymore.
Please check commit:  https://github.com/airbytehq/airbyte/pull/11480/commits/48b350eb0c0dae4ab6a8890b4c1b19d8fc795d33

Adding the tests back again are necessary to have a good CI coverage.

**Comment by grubberr** [comment]
I think this already not actual and can be closed
