### ISSUE TITLE
Destination Redshift: improve check performance

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#11580]
Improve _check_ method connection time if possible

**Comment by Phlair** [comment]
@VitaliiMaltsev could you add some basic context stats to add to this issue please
e.g. 

Currently seeing check times ~ x seconds / minutes

Would like to get check times down to ~ x seconds

**Comment by VitaliiMaltsev** [comment]
@Phlair @misteryeo 
Check method for Redshift Destination performance test results:

After numerous experiments, the results are as follows:
**Master branch**
Standard inserts ~ 3.2 seconds
S3 staging ~ 5.8 seconds

[**Buffering strategy**](https://github.com/airbytehq/airbyte/pull/12601)
Standard inserts ~ 3.3 seconds
S3 staging ~ 5.8 seconds

[**AbstractJdbcDestination check improvement**](https://github.com/airbytehq/airbyte/pull/12196)
Standard inserts ~ 2.4 seconds
S3 staging ~ 4.6 seconds

no additional implementation is required for this task. The performance of the check method for all JDBC destinations will be improved as soon as [this PR](https://github.com/airbytehq/airbyte/pull/12196) is merged.

**Comment by misteryeo** [comment]
Thanks @VitaliiMaltsev - it looks like there are outstanding comments on the PR so it's not ready to be merged?

**Comment by VitaliiMaltsev** [comment]
> Thanks @VitaliiMaltsev - it looks like there are outstanding comments on the PR so it's not ready to be merged?

@ yes, the PR is currently in Airbyte review status, outstanding comments were replied today

**Comment by grishick** [comment]
@VitaliiMaltsev I've approved the [PR](https://github.com/airbytehq/airbyte/pull/12820)

**Comment by VitaliiMaltsev** [comment]
published and merged in scope of https://github.com/airbytehq/airbyte/pull/12820
