### ISSUE TITLE
Credits chart axis should calculate dynamic width

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11586]
The credit consumption chart currently has a fixed width causing the tick labels to be cut off depending on their length. The axis width should be calculated dynamically.

![screenshot-20220330-172907](https://user-images.githubusercontent.com/877229/160872977-379f5e51-bb1f-49ff-99ba-8725458d031e.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
