### ISSUE TITLE
Debug periodic connector tests not running daily

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#11593]
Based on the build statuses [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md), it looks like the automatic connector integration test stopped running since March 6th. This is not intended, and probably a bug.

**Comment by grishick** [comment]
The tests are running again. Looks like we had a whole bunch of problems during the last 3 weeks: EC2 not being able to start, API rate limits, a typo (fixed here https://github.com/airbytehq/airbyte/pull/11592).

**Comment by grishick** [comment]
Confirmed with @supertopher that this workflow is still triggered daily at 4AM. However, last run failed: https://github.com/airbytehq/airbyte/runs/5786705935?check_suite_focus=true

**Comment by grishick** [comment]
In this run https://github.com/airbytehq/airbyte/runs/5786705935?check_suite_focus=true it appears that Java version in the container was < 17 (`nextLong(long bound)` was added in Java 17).

**Comment by grishick** [comment]
Tests are now running again at 4AM daily
