### ISSUE TITLE
update the webapp to use the new workspace scoped endpoints for CRUD/list of connector definitions

### ISSUE THREAD

**Issue by git-phu** [airbytehq/airbyte#11606]
relates to https://github.com/airbytehq/airbyte/issues/9652

Several API methods need to be changed to work with the new workspace-scoped connector definitions:

- `getSourceDefinition()` => `getSourceDefinitionForWorkspace()`
- `getDestinationDefinition()` => `getDestinationDefinitionForWorkspace()`
- `listSourceDefinitions()` => `listSourceDefinitionsForWorkspace()`
- `listDestinationDefinitions()` => `listDestinationDefinitionsForWorkspace()`
- `createSourceDefinition()` => `createCustomSourceDefinition()`
- `createDestinationDefinition()` => `createCustomDestinationDefinition()`
- `updateDestinationDefinition` => `updateCustomDestinationDefinition()`
- `updateSourceDefinition()` => `updateCustomSourceDefinition()`

**Important:** these changes must be released together with the migration in https://github.com/airbytehq/airbyte/issues/11607

**Comment by evantahler** [comment]
Maybe @timroes - have we not done this yet?

**Comment by timroes** [comment]
I believe this has been done in the past and got reverted again because of some issues. This was though done outside the FE team, so I'm not fully recall the exact details. cc @git-phu @harshithmullapudi iirc one of you were working on that PR in FE and can maybe shed some more light on why this was reverted originally?

**Comment by git-phu** [comment]
There's this issue #11607 that should be released together with the ui changes made here and cloud hasn't been able to get to it.  We can probably mark this issue as blocked until cloud can get back to working on this.

**Comment by evantahler** [comment]
Got it.  I think I'll re-tag this issue for the cloud team then

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Blocked on https://github.com/airbytehq/airbyte/issues/11607

**Comment by josephkmh** [comment]
Linking the previous PR that reverted the chnage from `/source_definitions/list` > `/source_definitions/list_for_workspace` here: https://github.com/airbytehq/airbyte/pull/13341/files
