### ISSUE TITLE
Zendesk

### ISSUE THREAD

**Issue by grant-cpt** [airbytehq/airbyte#1160]
## Tell us about the new integration you’d like to have
Which source and which destination? - Zendesk 

Which frequency? - Once every 12 hours or 24 hours

## Describe the context around this new integration
Which team in your company wants this integration, what for? - Business Intelligence and Support Team. In-dept customer analysis and to evaluate support cost per ticket.

This helps us understand the use case.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte? - I'll try to get it working using just Singer-IO

**Comment by cgardens** [comment]
@grant-cpt - hiya! thanks for adding this issue. Zendesk as a source is on our short term roadmap. Our goal is to have it ready by the end of the month.

just to clarify are you looking for Zendesk as a _source_ or a _destination_? (or both).

**Comment by grant-cpt** [comment]
Hey Charles,For now, just as the source.ThanksGrant--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2020/12/02, 6:27 pm Charles <notifications@github.com> wrote:

   
  @grant-cpt - hiya! thanks for adding this issue. Zendesk as a source is on our short term roadmap. Our goal is to have it ready by the end of the month. 
  just to clarify are you looking for Zendesk as a source or a destination? (or both).

**Comment by sherifnada** [comment]
@grant-cpt we just added zendesk support as a source! Let us know if there are any questions or feedback
