### ISSUE TITLE
Remove KubeCost

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#11631]

**Comment by pmossman** [comment]
@lmossman this issue sort fell off the radar, is this something you're actively looking into? Should we add it to the OSS board?

**Comment by lmossman** [comment]
I didn't get around to this this sprint - at this point it would probably be a good idea to assign this to someone on cloud and I am happy to review the PR

**Comment by terencecho** [comment]
I couldn't directly link the PR to this issue since the PR is on the cloud repo. Here's the link: https://github.com/airbytehq/airbyte-cloud/pull/1514
