### ISSUE TITLE
exchangerate source should use standard tests, not java integrationTest

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1164]
Also should remove the hack at https://github.com/airbytehq/airbyte/pull/1157/files#diff-ad2f4c85c0a4ba187cb58172f2f535e144c2cbd143086152bbd44e4527a97810R20 n

**Comment by cgardens** [comment]
let's do this when we add incremental support to exchange rates. (i.e. pretty soon)

**Comment by cgardens** [comment]
@sherifnada is handling this with https://github.com/airbytehq/airbyte/pull/1290/files
