### ISSUE TITLE
UX on Airbyte UI: an area for users to leave comments/notes on configurations

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#11649]
## Tell us about the problem you're trying to solve
An airbyte instance may be managed by a team, thus, it would be nice to allow collaborative work on airbyte configurations. Even when the instance is managed by a single person, it would still be beneficial to leave documentation traces to one self for future references.

## Describe the solution you’d like
Providing additional fields or thread/forum/message features where users can easily leave comments or notes to each other on the different configurations:
- source
- destination
- connections
- maybe on a job sync as well, this could be used to explain why or what were the impacts of a sync failure from airbyte connectors
- etc

## Describe the alternative you’ve considered or used
- Use octavia-cli and export configurations in a git repository where comments can be handled on the files themselves or in GitHub functionalities.
- Put comments in the name of the source/destination connector (but this is very limited space)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by ChristopheDuong** [comment]
Maybe in certain cases, this could also be used by the TS team to communicate/point things at a more granular level on the airbyte-cloud with users?
