### ISSUE TITLE
The requested stream BalanceTransactions was not found in the source (Shopify)

### ISSUE THREAD

**Issue by hbd** [airbytehq/airbyte#11647]
## Environment
- **Airbyte version**:  0.35.62-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker (Compose)
- **Source Connector and version**: Shopify v0.1.36
- **Destination Connector and version**: S3 v0.2.3
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
After creating a new Shopify source using credentials from a Shopify Development store, syncing to an S3 destination (Parquet), the connection reports requested streams are not available. However, these streams are available for other merchants with the same configuration.

## Expected Behavior
The streams should be available.

## Logs

<details>
<summary>LOG</summary> 

```

2022-04-01 02:50:14 source > "The requested stream balance_transactions was not found in the source. Available streams: dict_keys(['orders', 'abandoned_checkouts', 'metafields', 'order_refunds', 'order_risks', 'tender_transactions', 'transactions', 'fulfillments', 'shop'])"

```

</details>

## Steps to Reproduce
1. Create source using Shopify development store credentials
2. Sync to S3 (probably works with any other destination)
3. View logs for the sync

## Are you willing to submit a PR?

Yes

**Comment by marcosmarxm** [comment]
Looks Shopify connector filters some stream based on the permission of your API key.
https://github.com/airbytehq/airbyte/blob/669e6ed39de46a7423b957ccf54b79e4e84b09cc/airbyte-integrations/connectors/source-shopify/source_shopify/source.py#L509-L542

Probably the connector needs to improve this workflow to not allow this to happen.

**Comment by hbd** [comment]
Agreed, best to prevent creation of the connection altogether if permissions are not available for the selected stream.

Alternatively, we could accept connection creation, then handle the streams for which permissions have not been met, and log that the stream is unavailable due to permission issues. This would allow at least the available streams to succeed.

**Comment by evantahler** [comment]
cc @pedroslopez we should investigate what's going on here as part of https://github.com/airbytehq/airbyte/issues/16639

**Comment by arsenlosenko** [comment]
the stream in question was implemented in this PR:
https://github.com/airbytehq/airbyte/pull/10204
I have tested locally if we can select it in UI and sync with it, everything worked as expected. 
As the question of flexible handling of streams based on permissions is handled in https://github.com/airbytehq/airbyte/issues/16639, so I will close this issue.
