### ISSUE TITLE
Upgrade Airbyte Repo to Python 3.9.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#11657]
## Tell us about the problem you're trying to solve
Airbyte is generally on Python 3.7 for the builds and all the connectors. 

This is an issue for M1 devs as 3.8 is the minimum supported Python version. So these devs are left to set up their laptops in a 3.7 compatible manner to develop python connectors. This also puts us in a weird spot as the Octavia CLI is on 3.8, as the Octavia CLI team uses M1 macs and cannot use 3.7.

Further, 3.7 is going to be deprecated June 2023.

With all these considerations, we want to get off Python 3.7 to provide a good developer experience for our devs and simplify our builds.

After internal discussion, we want to upgrade to Python 3.9 despite some [backward incompatibility](https://docs.python.org/3.9/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code). This is because 3.10, which is the latest, is not yet compatible with google-ads.

## Describe the solution you’d like
* Figure out a plan to upgrade all python connectors to 3.9.
* Execute this upgrade plan.
* Change the build runners to use 3.9.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by marcosmarxm** [comment]
@bleonard are you working in this issue?
