### ISSUE TITLE
sponsored_products_report_stream does not return adId despite it being added automatically by amazon

### ISSUE THREAD

**Issue by agroh1** [airbytehq/airbyte#11659]
## Environment
- **Airbyte version**:  example is 0.35.12-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**:  Amazon Ads 0.1.3

- **Severity**: Medium
- **Step where error happened**: Sync Job

## Current Behavior
sponsored_products_report_stream does not return adId

## Expected Behavior
adId should be returned for the productAds and asins report.  It is added automatically by Amazon to the report
See the amazon documentation in this link for the metrics list.  https://advertising.amazon.com/API/docs/en-us/concepts/reporting/report-types#product-ad-reports

The problem is that while adId is automatically added and returned, if adId is request the amazon api generates an error.  So the connector needs to handle adId without requesting it be returned from amazon (this does seem like an amazon bug)

This adId is pretty important to actually use this report data when you need to break down by adId

## Steps to Reproduce
1. Create a source connector and connection to amazon ads
2. See that adId is missing from sponsored_products_report_stream

## Are you willing to submit a PR?
I will be submitting a PR with a fix for this

**Comment by grubberr** [comment]
Can we close this ?
I see it's merged 
https://github.com/airbytehq/airbyte/pull/11660
