### ISSUE TITLE
setup platform pagerduty rotation and runbooks.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11672]
## Tell us about the problem you're trying to solve
we want to update the pagerduty rotation to add new people into the rotations as secondaries and then a reverse shadow the next week. 

people to add: peter, topher, terence.

**Comment by supertopher** [comment]
Me and Peter are working on this currently.  Overrides for me and Peter exist now.  During this Oncall we will establish a rotation for Platform, and later spread those ideas to Infra and Edward for connectors
