### ISSUE TITLE
Improve `schema_generator.py` developer experience

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11674]
## Tell us about the problem you're trying to solve
When building a connector, one of the most important requirements is to define the output schema of each stream in the connector. There are multiple ways of doing this: 
1. Transcribing the JSONSchema by hand based on reading API docs
2. Using the API's OpenAPI spec to discern the schema. [Docs](https://docs.airbyte.com/connector-development/cdk-python/schemas#generating-schemas-from-openapi-definitions)
3. reading data from the API and reverse engineering it using `./tools/integrations/schema_generator.py`

Solution 3, while it has its limitations, is convenient in many cases as it allows you to get a schema that should be mostly correct for your connector. However, it has many tactical drawbacks: 
1. It's not documented on the [CDK schemas page](https://docs.airbyte.com/connector-development/cdk-python/schemas) as a viable option
2. It doesn't leverage python virtual environments, which means the user must install packages (specifically, `genson`) in the global namespace to use the utility
3. There is no readme or doc describing how to use the tool (it works by piping the output of a connector into it e.g: `docker run <connector> read --config <path>  --catalog <path> | python ./tools/integrations/schema_generator.py`, but you need to read the code to make that guess)
4. It's a standalone tool that requires downloading the entire Airbyte monorepo to be used
5. It requires running python

## Describe the solution you’d like

Solving the points above: 

1. Package this as part of the Python CDK. I should be able to install only the CDK (`pip install airbyte_cdk`), then run a specific CDK command e.g: `cat records.txt | python -m airbyte_cdk infer_schemas`. Some things you should scope out as part of this ticket are: where in the CDK file structure should this go (probably in a utils/ package), and where the output schemas JSONs should go (currently they're just output to a new folder `schemas/` of the working directory from which you run that command)
2. if I use the tool incorrectly or ask for help e.g: `python schema_generator.py herp` or `python schema_generator.py --help` it should print a usage message describing how I'm supposed to use it
4. (optional, maybe just create a follow-up ticket for now) it should be runnable via docker image so non-python programmers find it accessible
5. Once the points above are solved, document it in the CDK schemas documentation and the CDK README

This ticket should definitely be split into separate subtasks/PRs each addressing one or at most two of the points above at a time. 

## Some problems to consider as you solve this problem
`genson` (the core package in this script) is only compatible (it seems?) with Python <=3.8 but the CDK uses 3.9. The 20/80 version of this ticket may be to: 
1. package this up in its own virtual env, backed with a setup.py etc.. -- it would still live in `tools/` but it would be in its own dedicated directory + virtualenv to run it (which is a decent place to be)
2. document the usage of this in both the docs & the code runner itself (like mentioned above, add a `USAGE` message)

**Comment by dougpm** [comment]
Hey this is something I was working on, so I was glad to find out that `schema_generator.py` already exists. I'd like to work on this issue, is that ok?

**Comment by sherifnada** [comment]
hi @dougpm ! thanks for offering to help. I think the 20/80 version of this ticket may be to: 
1. package this up in its own python package, virtual env, backed with a setup.py etc.. -- it would still live in `tools/` but it would be in its own dedicated directory + virtualenv to run it. This way it at least doesn't pollute the dev's global python namespace. Which is a decent place to be. 
2. document the usage of this in both the docs (in a section similar to the OpenAPI section [here](https://docs.airbyte.com/connector-development/cdk-python/schemas#generating-schemas-from-openapi-definitions)) & the code runner itself (like mentioned above, add a `USAGE` message)

I think these two things should hopefully be fairly low hanging fruit and give a ton of visibility / usability to this experience!

**Comment by dougpm** [comment]
Alright, thanks for the explanation. I'll get started on that then!

**Comment by dougpm** [comment]
So, I ran into an issue here: to run a connector we need a ConfiguredAirbyteCatalog. Do we have anything to automate the process of creating that?
If not, I could add an additional command for that purpose, maybe using something in the lines of what we have [here](https://github.com/airbytehq/airbyte/blob/8e173e6e96aaaffa0b07291ec3c7a2f6c07e0bd2/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/conftest.py#L71).

The end result could look something like this (probably `schema_generator` wouldn't be the best name in this case):
1. `docker run <connector> discover --config <path> | schema_generator configure_catalog` 
This could default the output to `integration_tests/configured_catalog.json`
2.   `docker run <connector> read --config <path> --catalog <path> | schema_generator infer_schemas`

**Comment by dougpm** [comment]
@sherifnada [here's a PR](https://github.com/airbytehq/airbyte/pull/13518)
