### ISSUE TITLE
SAT: check oneOf common property has only `const` keyword, no `default` and `enum` keywords

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#11703]
We need to improve SAT `test_oneof_usage` to check that common oneOf property looks like this:
```
"option_title": {
    "type": "string",
    "const": "OAuth Credentials",
    "order": 0
}
```

only `const` keyword
NO MORE `default` and `enum` keywords.

old value
```
"option_title": {
    "type": "string",
    "const": "OAuth Credentials",
    "enum": ["OAuth Credentials"],
    "default": "OAuth Credentials",
    "order": 0
}
```

**Comment by sherifnada** [comment]
@grubberr cant we just use const keyword always instead of adding the enum and default keywords?

**Comment by grubberr** [comment]
@sherifnada I just checked, `const` only keyword also can work! 

I see we have 2 option:

1. add new SAT test which makes sure we have only `const` and don't have  `enum` and don't have `default` keywords

or 

2.  also check (1) but to be backward compatible  if not (1)  also check if we have all 3 keywords check that `const == default` and `const in enum`
  
What  is better (a) or (b) ? What do you think ?

**Comment by sherifnada** [comment]
I think 1 is better, because it makes the iface simpler for the user
