### ISSUE TITLE
populate connector verification status list with cloud release status

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11707]
## Tell us about the problem you're trying to solve
[this sheet](https://docs.google.com/spreadsheets/d/1JvWV7IAG6fgElO7zP3HyDgdPQLCAIqNcgT_JJJjdC7A/edit?usp=drivesdk) should have cloud release status as well. 

For reference, see this AppScript code which can be attached to a gsheet to pull the connectors and populate a gsheet cell ([example of where this is applied](https://docs.google.com/spreadsheets/d/1W3L-n-7SGd1QlBSGzNH6aUALbHGxLzUDalZNfhplVrw/edit#gid=603858194))
```

function importYamlLib(){
  var success = eval(fetch('https://raw.githubusercontent.com/nodeca/js-yaml/master/dist/js-yaml.min.js'));
  Logger.log(`successfully imported yaml lib: ${success}`)
}

function fetch(url){
  return UrlFetchApp.fetch(url).getContentText();
}

function getConnectorNames(filename){
  var url = `https://raw.githubusercontent.com/airbytehq/airbyte/master/airbyte-config/init/src/main/resources/seed/${filename}`;
  var response = fetch(url);
  return jsyaml.load(response);
}

function getSrcs() {
  return getConnectorNames('source_definitions.yaml').map(x => x['name']);
}

function getDestinations(){
  return getConnectorNames('destination_definitions.yaml').map(x => x['name']);
}

function main(){
  importYamlLib();
  Logger.log(getSrcs());
  Logger.log(getDestinations());
}

main();
```

i'll finish this ticket soon

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by ChristopheDuong** [comment]
if we had a `destination-gsheet` you could have pulled all that from the warehouse into the sheet.

In the meantime you could use an extension to sheet to do that like `OWOX BI`

I am not sure what it would take to enable the "native" feature in gcp to do that too:
https://support.google.com/docs/answer/9702507?hl=en

**Comment by sherifnada** [comment]
gsheet destination: working on it! #11918 

thanks a lot for the advice. This is super helpful! Will take a look at how we can do it

**Comment by sherifnada** [comment]
Ticket next steps: 

1. Sync with Chris about the right way to populate this info
2. Actually write scripting to populate this info

**Comment by sherifnada** [comment]
@misteryeo can you confirm that this is the outcome we were looking for in this ticket? https://docs.google.com/spreadsheets/d/1JvWV7IAG6fgElO7zP3HyDgdPQLCAIqNcgT_JJJjdC7A/edit#gid=700426213

For posterity: 
0. I signed up for https://www.coupler.io/ a service which has BQ as a source and GSheets as a destination. to auth into our BQ instance I created a service account in the `ab-analytics` project, and a service account key. I dropped the service account key into Lastpass with the name `coupler bigquery service key`
1. I replicated the `actor_definition` table from the Airbyte Cloud DB, which contains a list of all the connectors published in cloud, into [this spreadsheet](https://docs.google.com/spreadsheets/d/1JvWV7IAG6fgElO7zP3HyDgdPQLCAIqNcgT_JJJjdC7A/edit#gid=700426213) 
2. I created a column whose formula is basically "if the connector definition ID is present in actor_defintiion table, print Yes else print No" (I know, real fancy stuff)

**Comment by ChristopheDuong** [comment]
> I replicated the actor_definition table from the Airbyte Cloud DB, which contains a list of all the connectors published in cloud, into [this spreadsheet](https://docs.google.com/spreadsheets/d/1JvWV7IAG6fgElO7zP3HyDgdPQLCAIqNcgT_JJJjdC7A/edit#gid=700426213)

I hope you are using the output of this [connection](https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/256f4e82-d22b-4ce7-b2a9-d6ec864617e0/status) that replicate the Airbyte-cloud db to bigquery already (and did not create a new sync job)

> I created a column whose formula is basically "if the connector definition ID is present in actor_defintiion table, print Yes else print No" (I know, real fancy stuff)

Instead of just `yes` or `no`, why don't you replace the column `Current status` completely with this new data coming from airbyte cloud DB?

In the data warehouse, the logic is done [here](https://github.com/airbytehq/airbyte-warehouse/blob/d9e028cef3c8e5dcecc1bb6e1d190b2b2bc4f888/dbt/models/2-marts/product/dim_connector.sql#L52)

This [line](https://github.com/airbytehq/airbyte-warehouse/blob/d9e028cef3c8e5dcecc1bb6e1d190b2b2bc4f888/dbt/models/2-marts/product/dim_connector.sql#L51) and this [line](https://github.com/airbytehq/airbyte-warehouse/blob/d9e028cef3c8e5dcecc1bb6e1d190b2b2bc4f888/dbt/models/2-marts/product/dim_connector.sql#L101) are making sure that if the release stage is not defined in the yaml for such a connector id, then it is marked as `-` which is equivalent to "Not deployed in Cloud"

Instead of taking the actor_definition table and you get your data from `airbyte_warehouse.dim_connector.official_status` then it would make it a little more DRY...

**Comment by misteryeo** [comment]
I'll let you answer Chris' questions above @sherifnada - but yep, the outcome looks great.

We covered this in our conversation but not necessarily outlined in this issue description but let's make sure we pull **all connectors in Airbyte** onto this list. GTM will use this moving forward to understand the difference between OSS and Cloud so we want to make sure we have all the OSS connectors accounted for as well. Thanks!

**Comment by ChristopheDuong** [comment]
If you pull data from `airbyte_warehouse.dim_connector.official_status` into the sheet, i can make sure it'll contain all OSS connectors (even the custom connectors that are never published to airbyte's dockerhub but are tracked by segment) and you don't have to maintain custom logic

**Comment by sherifnada** [comment]
> I hope you are using the output of this [connection on airbyte-cloud](https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/256f4e82-d22b-4ce7-b2a9-d6ec864617e0/status) that replicates the Airbyte-cloud db to bigquery already

Yup I did that. 

@ChristopheDuong I've setup that sync job to run daily now. See the sheet `Connector Status`
