### ISSUE TITLE
[EPIC] Databases and Data warehouse Benchmarking

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#11719]
## Tell us about the problem you're trying to solve
This epic is for DB source connector benchmarks, including JDBC and CDC configs for all supported database sources.

## Describe the solution you’d like
I would like to see benchmarks results being regularly (every time there is a change in a connector or platform) published on github for the following areas for each database source connector that is either in GA or Beta stage:
 - source to dev/null full refresh job broken down by size of source
 - source to dev/null incremental job (broken down by size of incremental change)

Additionally (lower priority), I would like us to be publishing results of E2E benchmarks from source databases to specific data warehouses. We can limit these to one DW per cloud provider and select one source database.
 - E2E source to a data warehouse full refresh job broken down by size of source
 - E2E source to a data warehouse incremental job (broken down by size of incremental change)

Each of the benchmarks listed above should also be split into JDBC and CDC (if supported) use cases.

## Numbers that benchmarks have to confirm/maintain
 - 4.5M rows/hour average throughput from database sources

## Tech spec draft

- [Tech spec doc ](https://docs.google.com/document/d/1GauTW709Zq2Udu00u3rExvu4vxUssd5t6Epf7flbbHU/edit#heading=h.kv22uf96cujw)
- [Mock benchmark result](https://docs.google.com/spreadsheets/d/1NvWmDUQEkro2gsFRNTOBC4B3HrA33Z-4NQvEMJVNo88/edit?usp=sharing)

## Inspiration

- [Processing one billion events per second with NiFi](https://blog.cloudera.com/benchmarking-nifi-performance-and-scalability/)
- [Airflow DAG Performance and Reliability](https://medium.com/pasarpolis-product-tech/airflow-dag-performance-and-reliability-3ccbc5f86570)

**Comment by noahkawasaki-airbyte** [comment]
Hey Ari, this project is super early and hasnt really even started yet lol! The idea is we're trying to replicate customer like volumes of data and have internal syncs running to make sure airbyte can handle them.

Definitely a good idea for a blog in the future when its built out though

**Comment by evantahler** [comment]
@grishick how does this epic relate to https://github.com/airbytehq/airbyte/issues/15152?
