### ISSUE TITLE
Source Klaviyo: adds `flow` and `campaign` streams

### ISSUE THREAD

**Issue by ahmed-buksh** [airbytehq/airbyte#11723]
## Tell us about the problem you're trying to solve
Klaviyo source is not providing flows detail in an explicit stream. Moreover, events should be providing information regarding relevant flow and campaigns.

## Describe the solution you’d like
Create a dedicated stream for Flow, and add flow and campaign information to the event.

## Describe the alternative you’ve considered or used
Didn't find any alternative.

## Are you willing to submit a PR?

Yes

**Comment by jrolom** [comment]
@marcosmarxm I think we can close this issue as I believe the connector already supports these two streams

**Comment by marcosmarxm** [comment]
You're correct:
* https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/flows.json
* https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/campaigns.json
