### ISSUE TITLE
Missing changelog on S3 version 3.0

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#11724]
I see on airbyte an update of the s3 destination connector. but there are no changelog on https://docs.airbyte.com/integrations/destinations/s3#changelog. Can you added it please?

**Comment by marcosmarxm** [comment]
There is a bug in our doc website @Amruta-Ranade can you check this please

**Comment by Amruta-Ranade** [comment]
The changelogs aren't being updated on Docs rn. Will report back when we start updating them again.

**Comment by ChristopheDuong** [comment]
In the meantime, @AM-I-Human you can find the actual changelog here: https://github.com/airbytehq/airbyte/blob/master/docs/integrations/destinations/s3.md

Normally this should update the docs website automatically, but something is broken atm.

**Comment by AM-I-Human** [comment]
I see the changes now, I think this issue is resolved
