### ISSUE TITLE
UI doesn't display data types correctly for date types

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11741]
## Tell us about the problem you're trying to solve
The table [of supported data types mentioned here](https://docs.airbyte.com/understanding-airbyte/supported-data-types#the-types) is not correctly reflected on the UI. 
For example see the schema definition below: 
```
json_schema = {  # Example
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
                "id": {"type": "number"},
                "created_at": {"type": "string", "format": "date-time", "airbyte_type": "timestamp_without_timezone"},
                "updated_at":{"type": "string", "format": "date-time", "airbyte_type": "timestamp_without_timezone"},
                "job": {"type": "string"},
                "company": {"type": "string"},
                "ssn": {"type": "string"},
                "residence": {"type": "string"},
                "current_location": {"type": "array", "items": "number"},
                "blood_group": {"type": "string"},
                "website": {"type": "array", "items": "string"},
                "username": {"type": "string"},
                "name": {"type": "string"},
                "sex": {"type": "string"},
                "address": {"type": "string"},
                "mail": {"type": "string"},
                "birthdate": {"type": "string", "format": "date"},
            },
        }
```

here is what's shown in the UI 
![image](https://user-images.githubusercontent.com/6246757/161867605-11ada4ff-1482-417d-85e6-5c1a81170777.png)

The updated_at column, for example, should be shown as a timestamp with timezone as opposed to a string. 

## Describe the solution you’d like
Correctly display on the UI

cc @evantahler

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by evantahler** [comment]
For reference, this was discovered while working on https://github.com/airbytehq/airbyte/pull/11738

**Comment by grishick** [comment]
@krishnaglick I noticed that this is still not working correctly for database sources. For example, this field will show as string in the UI:
```
"event_timestamp":{"type":"string","format":"date-time","airbyte_type":"timestamp_with_timezone"}}}
```
![Screen Shot 2022-08-22 at 6 23 52 PM](https://user-images.githubusercontent.com/1310940/186047761-78d7826e-8918-406d-ad56-12539b52140b.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
> @krishnaglick I noticed that this is still not working correctly for database sources. For example, this field will show as string in the UI:
> 
> ```
> "event_timestamp":{"type":"string","format":"date-time","airbyte_type":"timestamp_with_timezone"}}}
> ```
> 
> ![Screen Shot 2022-08-22 at 6 23 52 PM](https://user-images.githubusercontent.com/1310940/186047761-78d7826e-8918-406d-ad56-12539b52140b.png)

The work hadn't been merged, unsure why this was marked as done. I just merged it, please check it out again!

**Comment by grishick** [comment]
@krishnaglick this issues was likely auto-closed when https://github.com/airbytehq/airbyte/pull/11770 was merged:

![Screen Shot 2022-08-23 at 8 57 20 AM](https://user-images.githubusercontent.com/1310940/186205414-04fecf19-2bcb-4698-a1b5-b9c9b076d0f6.png)

is there another PR that is part of fixing this issue?

**Comment by krishnaglick** [comment]
#14671 is a cousin ticket I believe
