### ISSUE TITLE
[helm/k8s] Worker pod fails to start via helm deployment, missing ENV vars

### ISSUE THREAD

**Issue by ufou** [airbytehq/airbyte#11753]
## Environment
- **Airbyte version**:  0.35.65-alpha
- **OS Version / Instance**:  Ubuntu 18.04
- **Deployment**: Kubernetes (via Helm)
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Low 
- **Step where error happened**: Deploy 
## Current Behavior
Deployed via the helm chart found in `charts/airbyte` with minimal changes to values (enabling ingress) results in the airbyte-worker unable to start with error:
```
Error: couldn't find key JOB_KUBE_ANNOTATIONS in ConfigMap big-data/airbyte-env
```

## Expected Behavior
I would expect the ENV vars to be optional or to have sane defaults

## Are you willing to submit a PR?
PR incoming
https://github.com/airbytehq/airbyte/pull/11754

**Comment by marcosmarxm** [comment]
@ufou can you test latest Helm deployment? I'm closing due inactivity.
