### ISSUE TITLE
Redesign empty source/destination/connection screen

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#11775]
We want to redesign the empty state of the source/destination/connection screen.

Figma mock: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/Web-app?page-id=26178%3A0&node-id=32933%3A156966&viewport=305%2C48%2C1&scaling=min-zoom&starting-point-node-id=32933%3A156608&show-proto-sidebar=1

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537098520) by [Unito](https://www.unito.io)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
