### ISSUE TITLE
Destination Oracle: enable basic normalization

### ISSUE THREAD

**Issue by userguy** [airbytehq/airbyte#11779]
Hello Team , 

As per documentation https://docs.airbyte.com/integrations/destinations/oracle
Basic Normalization Yes
Doesn't support for nested json yet

I have connector 0.1.15 of oracle which is latest . But in UI i am not getting Basic Normalization . 
![image](https://user-images.githubusercontent.com/11783537/162104987-08e079e0-21ce-4875-b313-225af411af75.png)

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537097719) by [Unito](https://www.unito.io)

**Comment by Hyurt** [comment]
Hi, 
I'm seeing conflicting info as well as here [Destinations that support basic normalization](https://docs.airbyte.com/understanding-airbyte/basic-normalization#destinations-that-support-basic-normalization) there's no mentions of Oracle basic normalization

**Comment by Hyurt** [comment]
Guess that's some stuff left from this 
https://github.com/airbytehq/airbyte/issues/6892#issuecomment-1054466127

Oracle destination seemed to support normalization but was then removed, which causes this confusing information.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
