### ISSUE TITLE
Sync Enable/Disable Bar 

### ISSUE THREAD

**Issue by userguy** [airbytehq/airbyte#11780]
![image](https://user-images.githubusercontent.com/11783537/162105428-6d3857bb-369d-49e8-abac-050ddcf17858.png)

This was added to new versions and it creates confusion on how to disable sync for all columns , Previously Checkbox for all was enabled or disabled 
There is no corresponding documentation on how to disable this or enable . 

This is for version 0.35.56-alpha

For Version v0.35.65-alpha disable for all sync is not working as expected for me . hence went down to lower version . 

I am running in docker

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537097565) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@userguy can you check latest version the UI improved a lot.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
