### ISSUE TITLE
New Source: SFTP Connector

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#11797]
## Tell us about the new connector you’d like to have
Java SFTP source connector.

## Describe the alternative you are considering or using
As a reference, you can take a look at the S3 source connector.

### Acceptance criterias
* [x] #11879
* [x] Prepare scoping document and share [here](https://drive.google.com/drive/folders/18ho7BArEWqcgQNYUnF7TP30z9L2eb5n2)
* [ ] Implement MVP connector

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537094543) by [Unito](https://www.unito.io)

**Comment by ftapin** [comment]
Hi,
Do you have any idea about realease date?

**Comment by alexandr-shegeda** [comment]
hi @ftapin 
we don't have any release date as of now
currently, it's in scoping phase, but it would be great to get any details on your expectations 
cc @misteryeo

**Comment by misteryeo** [comment]
@ftapin we plan to release into Alpha this quarter - so sometime before end of June!

**Comment by ftapin** [comment]
Hi,
Thank you for your answers. 
Actually i'm ingesting several files from SFTP through Airflow but it'll be smarter to ingest them with Airbyte.
