### ISSUE TITLE
Automatically test projects that depend on the project being changed

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#11815]
## Tell us about the problem you're trying to solve
* We have a few destinations that use S3, GCS, or Azure as staging areas.
* Changes from the upstream blob storages can break the staging mode of these destinations.
* Currently we run the downstream destination tests manually. But one can easily forget about that.

## Describe the solution you’d like
* When we run `/test` on a PR, CI should automatically trigger tests for all projects that depend on the project being updated. For Java connectors /test task could analyze Gradle dependencies to figure this out. For Python this could potentially trigger a storm of tests if CDK is changed.
* The original problem that we wanted so solve is that changes in S3/GCS destinations also affect staging destinations, but tests for S3/GCS do not trigger tests for downstream dependencies

## Describe the alternative you’ve considered or used
* a quick workaround would be to have an additional file "also run these tests" in every project that can affect other projects

## Additional context
* N/A

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537089273) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment]
Candidate solution:
1. Use the [dependencies task](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html) to list all dependencies for the updated connector, and run integration test for connectors that depend on it.
2. Go through every connector under the `connectors` directory and parse the `build.gradle` files to see if a connector depends on the updated connector.
3. Keep a hard-coded connector dependency list in a file. This is not ideal because it is manual, and the file will probably be out-of-date very quickly.

**Comment by grishick** [comment]
I think the first iteration of this solution shouldn't trigger tests for downstream dependencies, but should make a comment on the PR listing the downstream dependencies. E.g.:

> Youd changes affect the following connectors. Make sure to run corresponding integration tests:
>  - destination-A
>  - source-B
>  - source-C

**Comment by suhomud** [comment]
@grishick @tuliren, I opened PR and added [Dummy commit to destination-gcs](https://github.com/airbytehq/airbyte/pull/15783/commits/354010c0d00fc7aac61bcedab7d9b890bbd24b18) to show the report example. 
It used github action for `pull_request` and python script to parse `build.gradle` files. Please have a look
