### ISSUE TITLE
Make test setup steps retry-able

### ISSUE THREAD

**Issue by git-phu** [airbytehq/airbyte#11819]
## Tell us about the problem you're trying to solve
Followup to https://github.com/airbytehq/airbyte/issues/10958
With #10958 we can implement retries for individual test cases.

However, currently the frontend/acceptance tests are run as a single step in a github action that runs a bash script.
These scripts both:

* set up the test environment (for example with `docker-compose up`)
* run the gradle task to run the test suite

Currently it is possible for the setup command(s) to fail, which is not something the changes in #10958 can address.

## Describe the solution you’d like
We can split out the setup commands into separate steps in the github action and run these steps with the [retry-step](https://github.com/marketplace/actions/retry-step) action.
Example:

```yaml
uses: nick-fields/retry@v2
with:
  timeout_minutes: 5
  max_attempts: 3
  retry_on: any
  command: ./tools/bin/docker-compose_up 
```

This would allow us to retry setup steps that can sometimes fail unexpectedly.

For this ticket we should focus on implementing retries for steps related to `docker compose` and `kubectl apply`.  If there are other steps that might need retry logic we can address those in a separate ticket.

## Additional context
The discussion in #10958 and in particular this [comment](https://github.com/airbytehq/airbyte/issues/10958#issuecomment-1090887952) has useful context.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537087887) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
I saw another instance of set up failing. Recording here: https://github.com/airbytehq/airbyte/runs/6017024892?check_suite_focus=true#step:10:649

**Comment by git-phu** [comment]
also this https://github.com/airbytehq/airbyte/runs/6120377383?check_suite_focus=true#step:14:95

**Comment by git-phu** [comment]
There are blanket retries all over our pipelines now so it's not as relevant anymore.
If there are specific actions that tend to flake out we could consider making them more retry-able by breaking out the problematic steps, but I think this issue as written can be closed now.
