### ISSUE TITLE
Destination MySQL: normalization failed

### ISSUE THREAD

**Issue by GreeshmaGirish** [airbytehq/airbyte#11826]
## Environment
* **Airbyte version**:  0.35.65-alpha
* **OS Version / Instance**: AWS EC2
* **Deployment**: Docker 
* **Source Connector and version**: mysql 8.0.28
* **Destination Connector and version**: mysql 8.0.28 docker
* **Severity**: Medium
* **Step where error happened**: Replication

## Current Behavior
Normalization fails for MySQL Source/Destination 

## Expected Behavior
Normalization should run as expected for MySQL Source/Destination

## Logs
Attached
[logs-36.txt](https://github.com/airbytehq/airbyte/files/8448282/logs-36.txt)

## Steps to Reproduce
1. Deploy Airbyte via docker-compose
1. Setup MySQL Source/Destination without SSH Tunnel
1. Create Connection, Replication Type - Mirror Source / Custom and Select Sync streams . Sync mode : Append / Overwrite/ Incremental

## Are you willing to submit a PR?

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537085760) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
Hello @GreeshmaGirish I didn't find any meaningful error in your logs, can you test with latest version of Airbyte. I'm closing the issue, please open a new one if the issue persits.
