### ISSUE TITLE
Improve the usage of the onboarding page

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11838]
A user will continue to see the Onboarding screen even if they are fully onboarded. In order to remove the Onboarding tab on the left, they need to click on "Close Onboarding" at the bottom of the page. 

An issue I could see with this:
Users don't find the page valuable at a point in time, but they don't know where to find the Close button. We could automate this or make the page content more relevant/valuable.

Some suggestions on how to improve this page:

1. Remove the onboarding tab once they become a paid customer, which assumes conversion to paid is a good enough signal this page is not helpful. Not convinced this is the right solution since you can become a customer without being fully onboarded.
1. Remove the 2-min demo and link to demo app once the user. has connected successfully since those are both intro videos
1. Customization on the use cases displayed depending on what the user has actually set up (perhaps limited for now due to number of Cloud recipes)

![](https://user-images.githubusercontent.com/38087517/162495955-9be9cd52-adc7-4b1c-be27-fa3402a78f73.png)

Pretty low priority.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537081620) by [Unito](https://www.unito.io)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Closing as we no longer have onboarding page
