### ISSUE TITLE
Track in Segment how many tables are available and how many are enabled

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11849]
We want to track with Segment when users are editing which tables to sync in the connection settings setup, to understand how they interact with the table settings. As a result of this additional call, we would understand how often users are only syncing a subset of the available tables (rather than all which is selected by default), to determine whether we can hide the tables to sync on connection setup.

There are two ways a user can deselect. They can manually deselect a single table, or they can use the mass deselect and apply the changes. Both cases we would want to capture. 

![](https://user-images.githubusercontent.com/38087517/162528016-99378b05-45cd-4bc7-a3bf-5726e64e5e2d.png)

We already have an event "New Connection - Action", where the name of the action relates to the action taken. We could reuse that or create a new event, like: airbyte_ui_cloud.airbyte_ui_new_connection_table_select

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537076830) by [Unito](https://www.unito.io)

**Comment by timroes** [comment]
Additional context from syncing offline: We want to just send that event when the connection is created or updated (i.e. the form is submitted and we send the request). Since this already emits an event, we want to add the amount of "available_streams" and "enabled_streams" as an attribute to those existing events.

**Comment by tealjulia** [comment]
I'm not very familiar with how Segment handles the data from these calls.  Is there anything to consider downstream when changing the shape of the data for an existing call in this way?  Or is it simply adding those two attributes to the existing event code?
