### ISSUE TITLE
Error when running base-normalization integration test

### ISSUE THREAD

**Issue by pchalasani** [airbytehq/airbyte#11855]
Trying to run this test from master, after setting up the virtual env, and installing requirements.

When I run this test:

```
cd airbyte-integrations/bases/base-normalization
 NORMALIZATION_TEST_TARGET=mysql pytest ./integration_tests/test_normalization.py
```

it results in an error when executing this docker cmd

```
 docker run --rm --init \
   -v /home/pchalasani/Git/airbyte/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/mysql/test_nested_streams:/data \
   --network host -i airbyte/destination-mysql:dev write \
   --config /data/destination_config.json \
   --catalog /data/reset_catalog.json
```

The error message is -- 

```
Unable to find image 'airbyte/destination-mysql:dev' locally
docker: Error response from daemon: manifest for airbyte/destination-mysql:dev not found: manifest unknown: manifest unknown.
```

I tried looking into the docs (and README.md in this dir) to see what I may be missing. Apparently some docker image needs to be built beforehand, but that was not clear from the README.md, nor how to build that image.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537074966) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@pchalasani you must build the destination manually or run normalization integration test using gradle to build for you.

**Comment by marcosmarxm** [comment]
Closing due inactivity. Please open a new ticket if the problem persits.
