### ISSUE TITLE
Remove button to "Sync Schema" when creating a new connection

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11859]
During the creation of new connection, the connection settings page shows a purple icon above the tables that prompts the user to "Sync Schema". Clicking it will refresh the source schema.

Suggestion is to remove the option to refresh the schema, as the creation of the source and destination prior has already done the check. Users do click the button thinking it will change something, but it just refreshes the page essentially with the same information as before.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537073427) by [Unito](https://www.unito.io)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@nataliekwong I wonder if this is something we'd still like to do. I think there could be some valid reasons for DB sources where you'd be waiting for specific data to appear and want to refresh while creating the connection? That said looking through full story I can't find many users using it that way and often uses it in a way to hope some other error might vanish.

cc @andyjih any thoughts around removing this button while creating a connection?

**Comment by nataliekwong** [comment]
I recall @Amruta-Ranade mentioned this to me originally as a point of confusion when she was using Airbyte Cloud, so tagging her here in case she has perspective to add!

**Comment by andyjih** [comment]
It's likely to add more confusion than not. I'm in favor of removing it, but also comfortable punting this issue until we revisit the Connection creation experience.
