### ISSUE TITLE
Offer Sample Data as a source

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11854]
Offer sample data as a source for users to be able to use in testing Airbyte. This is separate from US Census, PokeAPI, or other sources where the output is not guaranteed to work every time with every destination. It should just be a data set with a few different data types, a few hundred rows, and usable with the Google Sheets destination. 

This can be especially helpful for users who have security rules that prevent them from using third party services without an NDA or security approval, so they can start to see the value of Airbyte before using their own data.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537075336) by [Unito](https://www.unito.io)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
@misteryeo I created this with the Frontend area but @timroes let me know it's for the connectors team.

Let me know if/where I can provide more context!

**Comment by misteryeo** [comment]
Yep, this sounds like we'd want to create a custom source of sorts. We're currently building out Google Sheets as a destination already and haven't planned to look into the sample data. 

What is your perceived urgency here? Has this been validated or is this an experiment?

**Comment by nataliekwong** [comment]
I haven’t validated this. The larger drop off comes from the destination
availability, not source.

For me this is not high priority. We offer public data sets already, with
PokeAPI not needing any extra keys, so we can use those as a workaround for
now and also see if users find those useful during activation before
investing time for Eng to build a simpler/more obvious solution.

**Comment by nataliekwong** [comment]
I believe this is resolved with the renaming of the Faker source as Sample Data. cc @letiescanciano
