### ISSUE TITLE
[Specs] Scheduler V2 Job Retention Cron.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#11869]
## Tell us about the problem you're trying to solve
Scheduler V1 includes [job history purging](https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/app/src/main/java/io/airbyte/scheduler/app/JobCleaner.java) to minimise DB usage. Scheduler V2 is done with Temporal and there is currently no job sweeping available.

We need to figure out how to sweep jobs as Scheduler V2 gets stabilised and released to OSS. This is also important for Cloud to minimise cost.

## Describe the solution you’d like
The eventual solution should:
* be compatible across Docker and Kube.
* be usable in both OSS and Cloud.
* allow for sane sweeping configuration probably centered around days.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment]
fyi @benmoriceau and @cgardens

**Comment by benmoriceau** [comment]
@davinchia I tagged it as a spec issue and will try to make it to be in the next sprint. Do you know if there is some legal duration which we need to respect in order to define the priority of this ticket.

**Comment by davinchia** [comment]
@benmoriceau no legal requirements for now. We've historically do so for operational/cost reasons.

@nataliekwong @bmcgilli are either of you aware of any legal requirements to keep data?

**Comment by nataliekwong** [comment]
I'm not aware of any.

**Comment by bmcgilli** [comment]
What's changing? Previously there was no concern from our legal council. 

Also with Patsy starting in 2 weeks we can have her flag anything legal-related as she onboards

**Comment by benmoriceau** [comment]
It will be about fixing a regression. We had a sweeping of the old logs and DB in order to save cost which hasn't been added with the scheduler v2. We need to re-introduce it. I wonder if we promised to our clients that we will keeps logs up to X days/months

**Comment by davinchia** [comment]
@benmoriceau sounds like there are no new reqs. I think using the default of [sweeping after 60 days](https://github.com/airbytehq/airbyte/blob/fa9c4670988a990798e066abd49d41d5ca0c8b26/airbyte-config/models/src/main/java/io/airbyte/config/EnvConfigs.java#L158-L159) is good enough for now.

**Comment by cgardens** [comment]
Context: For the cloud product we will want to hold logs for 1 year for security compliance reasons.

**Comment by davinchia** [comment]
This is out of date.
