### ISSUE TITLE
Add image pull policy for sidecar containers in job pod

### ISSUE THREAD

**Issue by gfeldman** [airbytehq/airbyte#11867]
## Tell us about the problem you're trying to solve
Our Kubernetes cluster has an OPA policy that requires the `imagePullPolicy` on all containers be `Always`

## Describe the solution you’d like
Add another config `JOB_KUBE_SIDECAR_CONTAINER_IMAGE_PULL_POLICY` with a default of `IfNotPresent`. 

## Describe the alternative you’ve considered or used
Requesting an exemption from the OPA policy.

## Are you willing to submit a PR?
Yes.

**Comment by gfeldman** [comment]
I would like to work on this

**Comment by davinchia** [comment]
@gfeldman this sounds reasonable and straightforward. Feel free to open a PR and we can discuss on it.

**Comment by gfeldman** [comment]
Thanks for the fast reply! I opened a PR https://github.com/airbytehq/airbyte/pull/11868
