### ISSUE TITLE
Orbit.love

### ISSUE THREAD

**Issue by aantn** [airbytehq/airbyte#11865]
## Tell us about the new connector you’d like to have
I'd like to send data from Orbit.love to BigQuery

## Describe the context around this new connector
I'm interested in sending data on users and their identities from Orbit.love to BigQuery.

## Describe the alternative you are considering or using
A custom Python script which queries the Orbit.love API.

## Are you willing to submit a PR?
Yes, possibly. I'm very limited in the amount of time I can work on this though.

**Comment by sherifnada** [comment]
@avaidyanatha nope, all yours!

**Comment by aantn** [comment]
Hey all, I actually wrote a connector

**Comment by PeerRich** [comment]
I am getting a generic error when using the Orbit source. Has their API changed maybe?
![image](https://user-images.githubusercontent.com/8019099/211162479-c54bcb87-88b9-4725-b128-191c73b39f90.png)

slack thread: https://airbytehq.slack.com/archives/C021JANJ6TY/p1673111288738589
