### ISSUE TITLE
S3 Connector - doesnt attach csv file ending above version 0.2.11

### ISSUE THREAD

**Issue by wallies** [airbytehq/airbyte#11872]
## Environment
- **Airbyte version**:  v0.35.65-alpha 
- **OS Version / Instance**: GKE
- **Deployment**: Kubernetes
- **Source Connector and version**:  Survicate 0.0.8
- **Destination Connector and version**: S3 0.2.12 and above
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*
S3 Destination connector 0.2.12 and above doesnt add csv file format on the end of the file when syncing.
We are using incremental append mode.
We rolled back to 0,2,12 but then it outputs to a csv.gz with no option to not compress.

## Expected Behavior
*Tell us what should happen.*
- Have option to not compress the file
- I would expect the file format to always be appended to file

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
2.
3.

**Comment by tuliren** [comment]
@wallies, a new version of the S3 destination connector, `0.3.3`, has been published. This new version lets you turn off compression for CSV or JSONL files. Please use this new version, instead of rolling back to `0.2.12`.
