### ISSUE TITLE
Research OOM errors in JDBC source connectors

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#11883]
┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537069638) by [Unito](https://www.unito.io)

**Comment by igormp** [comment]
Hey, is there anything that I can do to help with this issue? I could try running locally with some DB instances that I manage and check the resource usage. In case that's helpful, is there any specific output that you'd like me to gather?

**Comment by grishick** [comment]
Exit criteria:
 - have a research spec for solutions
 - implementing the solution

**Comment by tuliren** [comment]
Design & experiment spec: [doc](https://docs.google.com/document/d/1UCsIPoBn8hu-G3Gs0P45NNylLmmnDNd-4isrOeeZYCA/edit?usp=sharing)
