### ISSUE TITLE
Brainstorm and Prioritize Internal Admin Tooling meeting

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#11882]
## Tell us about the problem you're trying to solve
Regarding this [epic](https://github.com/airbytehq/airbyte/issues/11143).
The last brainstorm for internal tooling was done 4 months ago, we want an updated brainstorm to finalize what to work on for Q2.

## Describe the solution you’d like
Set up a meeting with relevant stakeholders and document internal tooling ideas and their priority.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537069832) by [Unito](https://www.unito.io)

**Comment by pmossman** [comment]
Should invite Erica

**Comment by andyjih** [comment]
I pinged Erica. I sounds like a doc exists already, so I'll try to gather requirements async without needing a meeting.
