### ISSUE TITLE
Refactor CDK & unit Test YAML specs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11889]
full context in parent issue 

The current function (which looks for a .json to read by default) is not unit tested for no good reason. As part of this ticket, we should add unit tests in test_connector.py to verify all these behaviors. It may be a good idea to do this first (a la TDD) before doing the refactor to support YAMLs.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537068246) by [Unito](https://www.unito.io)

**Comment by pedroslopez** [comment]
@bleonard should have been more clear when closing this one: 
this was wrapped into https://github.com/airbytehq/airbyte/issues/11888 since test+implementation should be done together
