### ISSUE TITLE
rolled eyes on front page

### ISSUE THREAD

**Issue by manul7** [airbytehq/airbyte#11892]
This issue can be observed on https://airbyte.com/

## Environment
* **OS Version / Instance**: macOS
* **Browser**: Safari, Version 15.4 (17613.1.17.1.6)

* **Severity**: LOL

## Current Behavior
* Well, it's better to see
![image](https://user-images.githubusercontent.com/895669/162811097-66ec2ea7-6ac3-49ce-ab5e-bb55b87a458e.png)

https://user-images.githubusercontent.com/895669/162812318-ae2d4369-fc6c-43be-81a2-e60d0210997e.mp4

## Expected Behavior
* It's also not perfect, but better in Chrome Version 100.0.4896.75 (Official Build) (x86_64)
![image](https://user-images.githubusercontent.com/895669/162811357-8547a74c-ab2b-4082-acd2-ac05419e0b0f.png)

## Steps to Reproduce
1. Open https://airbyte.com/

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537067329) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
> Severity: LOL

🤣
