### ISSUE TITLE
Get Stripe issuing approval in sandbox account

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#11906]
## Tell us about the problem you're trying to solve
We need to get verified on our stripe integration test account whose login (creds are in lastpass). This ticket is a placeholder for following through on this. 

This is the link to see the status of the issuing review: https://dashboard.stripe.com/test/issuing/overview

There is an email chain between us and stripe to get the verification. We should expect a reply by April 13 if not sooner. Once that email chain is resolved, follow the link above to understand what are the next steps. If at any time you are not sure what the next steps are contact stripe customer support.

**Comment by igrankova** [comment]
@sherifnada, the next step needs your help, there's the personal information they need to complete the issuing verification:
![image](https://user-images.githubusercontent.com/87977540/162933690-821c74b7-261b-41ac-b452-e3b843495380.png)
https://dashboard.stripe.com/issuing/verifications/summary

**Comment by igrankova** [comment]
The verification is completed.
