### ISSUE TITLE
Audit Logging - Brainstorm and decide approach

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#11900]
Epic: https://github.com/airbytehq/airbyte/issues/8120

## Steps
1. Schedule a brainstorm with interested devs
2. Write a tech spec laying out a couple approaches/tradeoffs
3. Make a decision about implementation approach and add implementation issue(s) to epic
### Key Questions to answer:
- Track at the API layer vs the DB layer? Tradeoffs in complexity/coverage?
- Cloud-only or implemented in OSS as well?

### Useful Links
- [Approaches for tracking changes in Postgres](https://dba.stackexchange.com/questions/233735/track-all-modifications-to-a-postgresql-table)

**Comment by ChristopheDuong** [comment]
Tracking at the DB layer could be done by a `source-postgres` connector (with CDC feature on to be even better)?

or would it be a little higher in the "db" layer? and thus, it sounds like an API layer?

**Comment by cgardens** [comment]
Closing this. I picked an approach in this PR: https://github.com/airbytehq/airbyte/pull/18743 . If we decide it is the wrong approach we can re-open.

FWIW, I hunted for a tool to do this. I've now implemented this functionality at 3 different companies. I did not, however, find a tool at all (not even a bad one).
