### ISSUE TITLE
source-facebook-marketing: datetime fields are ISO8601, not RFC3339

### ISSUE THREAD

**Issue by mdibaiee** [airbytehq/airbyte#11923]
## Environment
- **Airbyte version**:  N/A
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: source-facebook-marketing@[0.2.42](https://hub.docker.com/layers/source-facebook-marketing/airbyte/source-facebook-marketing/0.2.42/images/sha256-3a6fe9f6f7bd5274de946008d6a4788bc893b0c9d1f1660c13805871c0f3029d?context=explore)
- **Destination Connector and version**: N/A
- **Severity**: Medium
- **Step where error happened**: Sync?

## Current Behavior

In the specification of source-facebook-marketing, datetime fields are marked with:

```
format: date-time
```

This format is reserved for RFC3339 datetimes per JSONSchema definition: https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times

However, Facebook's API uses ISO8601, which is not always compatible with RFC3339 (ISO8601 is a superset), for example Facebook's datetimes can use this timezone offset format:

```
2020-03-10T09:20:20-0400
```

While `-0400` is supported in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators), it is not supported in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt).

## Expected Behavior
- These fields should not be marked as RFC3339 datetimes

## Logs

<details>
<summary>LOG</summary> 

```
```

</details>

## Are you willing to submit a PR?

I need a confirmation from Airbyte team that this is something they want to do. I understand it potentially has implications for Airbyte's usage of this connector.

**Comment by marcosmarxm** [comment]
I'm closing due inactivity and didn't see other people complaining about this. @mdibaiee can you test latest version of the connector and see if the problem persist? Please open a new issue if does.
