### ISSUE TITLE
Cloud-specific feature coverage in acceptance tests (currently only focused on permissioning / security)

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#11932]
Should be broken down into specific features and/or routes (multiple issues)

- Key difference in Cloud vs OSS is workspace management
- Deletion of resources is not well tested, currently low confidence that we do deletions properly

**Comment by terencecho** [comment]
going to close this issue as we're moving all this work into this epic: https://github.com/airbytehq/airbyte/issues/15674

btw @pmossman, do you remember what this line was referring to?
> Deletion of resources is not well tested, currently low confidence that we do deletions properly

What are the resources that we're deleting?

**Comment by pmossman** [comment]
@terencecho I don't remember the specifics around deletions, maybe it's just referring to the fact that deletions might be more important in Cloud than OSS because we own the data instead of the user? Maybe the OSS acceptance test suite doesn't test deletion routes as much as we'd like to in Cloud?
