### ISSUE TITLE
Provide PLAIN authentication support for kafka. 

### ISSUE THREAD

**Issue by tirth7777777** [airbytehq/airbyte#11934]
I am using airbyte to read data from kafka cluster but in airbyte there is no option of PLAIN authentication with SASL_SSL. Currently airbyte supports SCRAM-256, SCRAM-512, OAUTHBEARER, GSSAPI

**Comment by tirth7777777** [comment]
I would be able to contribute to this

**Comment by sumitm-iiit** [comment]
@octavia-squidington-iii : What's the process to contribute the fix for this issue? As @tirth7777777 mentioned we have fix ready and we can contribute to the kafka connector as soon as we get the approval.

**Comment by davinchia** [comment]
fyi Octavia is a bot so you usually won't get a reply from a human :) 

Feel free to open a PR with your contribution. It'll be assign to someone to review. You can look at [our docs](https://docs.airbyte.com/connector-development/testing-connectors/) for documentation on how to contribute.

**Comment by sumitm-iiit** [comment]
aah...didn't look at that. Thanks for reminding @davinchia.
@tirth7777777 : Can you open a PR with your fix ?

**Comment by tirth7777777** [comment]
Fixed by #12134
