### ISSUE TITLE
🐛 Source Zendesk Support: Error on `Cursor Field`

### ISSUE THREAD

**Issue by kyle-cheung** [airbytehq/airbyte#11973]
## Environment
**Is this your first time deploying Airbyte:** No
**OS Version / Instance:** EC2 t2.large
**Memory / Disk:** 16Gb
**Deployment:** Docker
**Airbyte Version:** 0.35.56-alpha
**Source name/version:** Zendesk Support 0.2.3
**Destination name/version:** Snowflake 0.4.24
**Step:** Normalization
**Severity**: High
Description: I upgraded my Zendesk Support from 0.1.12 to 0.2.3 and now all of the jobs fail. Downgrading back to 0.1.12 works and the jobs finish. Not sure what’s happening, logs attached. Per @alafanechere 's help on discourse, It looks like a date field, used as a cursor field on one of the stream, is None and the connector expects it to be non nullable to perform a date parsing.

Discourse Link
https://discuss.airbyte.io/t/zendesk-support-0-2-3-errors-out-but-0-1-12-runs-fine/416/3

## Logs
[logs-6403.txt](https://github.com/airbytehq/airbyte/files/8482667/logs-6403.txt)

**Comment by kyle-cheung** [comment]
0.1.12 does not run successfully now.
[logs-7023.txt](https://github.com/airbytehq/airbyte/files/8541665/logs-7023.txt)

**Comment by bazarnov** [comment]
@kyle-cheung 
Please try to update on the latest version available and run the sync again. The `cursor_field` for certain streams were updated.

**Comment by bazarnov** [comment]
Closing the issue for now, if the problem persist - please re-open the issue.
