### ISSUE TITLE
Move deploy off of local machines

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1198]
## Tell us about the problem you're trying to solve
* Deploying (releasing new versions of connectors and of the core app) is painful right now because uploading docker images from a residential internet connection.
* Often times it involves switching branch and re-building a ton of stuff, so it stops any coding progress on other tasks while the deploy is happening.

## Describe the solution you’d like
* jrhizor implemented slash commands in github to allow triggering integration tests. Wondering if we can use a similar approach here as well.
* needs to be scoped by airbyte employee (unlike the integration tests)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368128422080) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
Bumping the priority of this since we just ran into an issue preventing users from upgrading or installing airbyte for the first time that could be prevented by building off of a CI machine.

**Comment by cgardens** [comment]
Release 0.29.3-alpha was not usable. See slack reports: [report 1](https://airbytehq.slack.com/archives/C01MFR03D5W/p1628626131462700) and [report 2](https://airbytehq.slack.com/archives/C01MFR03D5W/p1628634173469200). It was trying to use the Airbyte Cloud version of the webapp instead of the OSS version. Our hypothesis here is that this is because it picked up an environment variable that was set on the local machine of the deployer. Deploying a new version seems to have fixed the issue.

@davinchia fyi

**Comment by cgardens** [comment]
@subodh1810 did this!
