### ISSUE TITLE
Upgrade to new version without downtime

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#11986]
## Tell us about the problem you're trying to solve
Today we need to stop docker containers to upgrade the Airbyte instance, maybe we can have a service like the `bootstrap` container to orchestrate the version upgrade reducing the downtime.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
@marcosmarxm what is the urgency / motivation on this?

**Comment by evantahler** [comment]
We are not going to prioritize this for the moment - this would make our docker deployment rather complex.  I think that it is safe to assume that an OSS user choosing to upgrade Airbyte is doing so manually, and therefore aware of the downtime implications.  Also, our upgrade process is rather quick - just git pull, run docker-compose, and download some new images.
