### ISSUE TITLE
[SAT] connector check operation should also be tested in integration tests

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#12010]
We recently had an issue where Redshift connector's check command was broken, as a result we were not able to onboard new customers/users. We should make sure to test the connector's check command in integration tests to make sure it gets caught

**Comment by grishick** [comment]
Tagging this issue for all three connector teams.

**Comment by evantahler** [comment]
Closing this in favor of https://github.com/airbytehq/airbyte/issues/17184 - Once **all** connectors use SAT, we'll be able to test SPEC, CHECK, etc commands for databases just like we do for API sources
