### ISSUE TITLE
Per-stream state support (to be broken down)

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12024]
Add per-stream state support, in service of the Schema Evolution epic
[Tech spec](https://docs.google.com/document/d/1zJVUQkVy8ZJUcqzM_hYPGijr4pI0Xx6I2eqpagJ2r7E/edit#heading=h.fa72b39y2m99)

**Comment by grishick** [comment]
@benmoriceau would this issue https://github.com/airbytehq/airbyte/issues/3206 be part of the solution?

**Comment by benmoriceau** [comment]
@benmoriceau Next sprint: API focus and sync with Tim.

**Comment by grishick** [comment]
Is this a duplicate of https://github.com/airbytehq/airbyte/issues/6911?
