### ISSUE TITLE
Finalize design for differentiating user errors in connector telemtry

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12029]

**Comment by evantahler** [comment]
Finish spec to use AirbyteLogMessage and AirbyteDisplayMessage to create final sync statuses

**Comment by sherifnada** [comment]
spec WIP: https://docs.google.com/document/d/1ctrj3Yh_GjtQ93aND-WH3ocqGxsmxyC3jfiarrF6NY0/edit?usp=drivesdk

**Comment by evantahler** [comment]
[status] This is close, with the [doc](https://docs.google.com/document/d/1ctrj3Yh_GjtQ93aND-WH3ocqGxsmxyC3jfiarrF6NY0) and [diagram](https://whimsical.com/airbyte-connector-metrics-and-error-reporting-R825xrLbwKoti2BYEqupJG) being the main inputs to https://github.com/airbytehq/airbyte/issues/12118.  There are few more discussions to sort out about the changes to the airbyte spec
