### ISSUE TITLE
Add better documentation about Destination Namespace

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12022]
We see that users are often confused by the Destination Namespace selection during connection setup. We should add better documentation around what the individual options are doing and meaning.

For that we'll need to figure out

(a) how we want this to look? We could have a help icon opening a sidepanel describing all options, or show an inline documentation below the box for the currently selected option.
(b) Figure out the exact copy for the documentation we want to give for every option. cc @Amruta-Ranade Could you help with those texts?

cc @andyjih @nataliekwong

**Comment by Amruta-Ranade** [comment]
Absolutely!!

**Comment by andyjih** [comment]
Adding some ideas:
- Show explainer text once the user has chosen one of the options
- Link to docs
- Show previews in the table below
- Explore new names/terms for each of these options

**Comment by edmundito** [comment]
Moved to waiting: Need to define what the solution is.

**Comment by Amruta-Ranade** [comment]
Happy to set up some time to chat about the text!

**Comment by andyjih** [comment]
@Amruta-Ranade I added this issue to `team/documentation` and removed the frontend team from it. Let me know if that's a mistake!

**Comment by nataliekwong** [comment]
My preference is to move away from the pop-up modal where possible and rely on in-line education during connection setup or editing.

I've been really digging the new method we have for single-selects, which was implemented in the Postgres source connector: 
![Screen Shot 2023-09-28 at 5 13 00 PM](https://github.com/airbytehq/airbyte/assets/38087517/d86608c0-e1d1-4a1c-99a8-0c795a846868)

cc @nora-airbyte

**Comment by nataliekwong** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/29896 where we will:
1) only show options that are relevant to the user (https://whimsical.com/connection-sync-mode-MQ9Jr5Sn4nCzSHFaogvfXt)
2) match the verbiage in the app to the verbiage for that destination
