### ISSUE TITLE
Log an analytics event when no connector matching the query

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12033]
We want to log an analytics event every time a user types to search a connector in the dropdown, but nothing will be found. That will help us getting a better overview of potentially confusing named connectors as well as requested connectors.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Analytic events `Airbyte.UI.NewSource.NoMatchingConnector` and `Airbyte.UI.NewDestination.NoMatchingConnector` both with a `query` parameter were created.
