### ISSUE TITLE
Set a min-width for columns in the replication settings table

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12045]
![2022-04-11_17-43-52](https://user-images.githubusercontent.com/633226/163469793-ea258ef2-4253-4497-88b6-12762257a739.png)

All of the text here is quite small and often truncated into an ellipsis, making the table a bit hard to read and interpret.

Thoughts:
- Hide/collapse columns that might not be relevant
- Expand the width of the table

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
@Upmitt to provide the min-width values

**Comment by Upmitt** [comment]
I suggest to add 20px padding around the main bloc, so when we downsize we still see the beige background on right & left, and the min width suggested is 960px.

https://www.loom.com/share/c96342f5b1bf47a5b84d5c350fca3685

padding: 0px 20px 10px 20px;
min-width: 960px;
