### ISSUE TITLE
The bulk-action menu in the Streams table doesn't look aligned with the rows below it. 

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12050]
![2022-04-11_17-45-41](https://user-images.githubusercontent.com/633226/163489164-5466c201-76df-43e0-ba81-2c492555cb98.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
Closing as we'll address this in the connection page redesign
