### ISSUE TITLE
Revisit Sync History Design

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12056]
The name "Sync History" isn't entirely accurate since Resets also exist in this view. Additionally, whether the run was a Sync or a Reset was something that took me quite a while to figure out. 

Ideas:
- Rename "Sync History" to something else like "Run History" or "Sync and Reset History"
- For each run, concatenate the type of run that was done, so instead of just "Succeeded", show "Sync Succeeded" or "Reset Succeeded".

![Screen Shot 2022-04-14 at 4 52 56 PM](https://user-images.githubusercontent.com/633226/163494787-3aae5ae2-7814-4196-bbb9-383131ad2be3.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@andyjih Is this still relevant? Can this be closed?

**Comment by andyjih** [comment]
Closing for now
