### ISSUE TITLE
Modal overlay asking user to rate their first sync seems mis-timed

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12052]
Observed Behavior:
- I was waiting on the /onboarding page after setting up my first sync just to see what would happen.
- This modal showed up above everything

Reaction:
I didn't feel comfortable answering it just yet because I was curious to see the details of the run/sync in the UI. I also went to my destination DB to verify, but I wanted to explore the Airbyte product a bit more first before answering this question.

Questions:
- What is the purpose of this modal overlay? What do we do with the data if they do a thumbs up or thumbs down?

![2022-04-11_17-51-36](https://user-images.githubusercontent.com/633226/163489762-fde25306-93c9-48dc-a7e1-e875ec27c293.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@nataliekwong I wonder if we could remove this modal altogether and instead use one of our tools (currently used, or currently planned to be added), to implement a consent dialog instead?

**Comment by nataliekwong** [comment]
Did some analysis of the results here: https://docs.google.com/document/d/1hrbaQ0fCJ9pH3iTAy7qyKU3mVNnViBYDovuY8BVXnXs/edit#

I've added a proposal for a new survey tool that will be less intrusive in the experience and if implemented, there will be a delay of a few hours between successful sync and the onboarding feedback, which hopefully addresses the timing feedback.

**Comment by timroes** [comment]
Closing this, since we removed the feedback modal from the product and this is now handled delayed after the first sync (and therefore even better timed) via a third party surveying tool.
