### ISSUE TITLE
Source Intercom: conversation ID isn't being populated in `conversations_parts`

### ISSUE THREAD

**Issue by pylenin** [airbytehq/airbyte#12066]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Conversation ID column is empty in the conversation parts table. This modification was part of this PR.
https://github.com/airbytehq/airbyte/pull/11206

## Expected Behavior
Conversation ID should be populated.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by misteryeo** [comment]
@pylenin can you please populate the rest of the description template with all the applicable details please? Thank you!

**Comment by bazarnov** [comment]
@pylenin Hello, could you please confirm the issue still persist? What version of the connector do you use?

**Comment by bazarnov** [comment]
It appears to be the old version bug that is already fixed in the latest one. @pylenin please consider updating the connector to the latest version available. Once needed re-open the issue again. Closing for now.
