### ISSUE TITLE
global proxy setting for all sources and destinations

### ISSUE THREAD

**Issue by kamojiro** [airbytehq/airbyte#12070]
## Tell us about the problem you're trying to solve

I tried [Airbyte Open Source QuickStart](https://docs.airbyte.com/quickstart/deploy-airbyte) behind proxy.

## Describe the solution you’d like

I'd like a proxy setting parameter.(please let me know if there is already such parameter)

## Describe the alternative you’ve considered or used

Successfully to QuickStart, I edit [PokeAPI Dockerfile](https://github.com/airbytehq/airbyte/blob/5393070dc6c87c3fccad8b664cee8e30d3e52ba3/airbyte-integrations/connectors/source-pokeapi/Dockerfile), and add the following lines to this Dockerfile.

```
ENV http_proxy "http://~~~"
ENV https_proxy "http://~~~"
```

## Are you willing to submit a PR?

No.

**Comment by tooptoop4** [comment]
what is the fix @sherifnada ?
