### ISSUE TITLE
[Epic] Support schema evolution

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12089]
## User story
As an Operator/Analytics Engineer/Data Scientist/Data Analyst when i set up a new connection, I would like to be notified when source schemas are changing but my syncs should keep working, migrating data accordingly. Since data is tied to my business, I would like to be notified and be able to provide custom directives on how to migrate my old data and how to backfill accordingly (if needed).

Furthermore, to improve UX, Airbyte should support default actions for some typical scenarios, such as:
 - add column
 - remove column
 - column data type change
 - column renamed (if this can be detected)

**Comment by persunde** [comment]
It would be amazing if we could add extra columns without deleting all the existing data.
We transport data from database A to database B.
But A does not keep all the data, and deletes old rows. But we want to save all original rows in B. When we change the columns on table in database A, then the sync to B delete all rows in B and that is an issue for us.
Is it possible to solve this?
Keep the original data in destination when you change the columns on the source table.
Or at least keep rows that exists in destination, but no longer exists in source.

**Comment by Eloisee** [comment]
It would be great if we could detect and add new tables in the source automatically .
In the bigquery source, we connect with the dataset and there may be  new tables day by day , and we would like to sync it without any manual work.

**Comment by alepietrobon** [comment]
just checking, is this what is listed in the roadmap under "schema evolution"? I'm really keen on understanding progress on this work. Thanks! 
![image](https://user-images.githubusercontent.com/8207502/203747150-26d41c71-ceb2-41b8-8fc9-177e9adb8ed4.png)

**Comment by shaidar** [comment]
Would be interested in hearing more about if this is still in progress.

**Comment by andrevus** [comment]
I'm interested in too. Do you have any update?

**Comment by phdmohamedali** [comment]
any updates?

**Comment by brendavarguez** [comment]
Is this still in progress?

**Comment by malikdiarra** [comment]
Hi, this is now available in v0.50.1+, you can choose how you want schema to be replicated in the replication tab of your connection
