### ISSUE TITLE
Allow users to view deleted connections

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12099]
Users want to access deleted connections for their logs in the UI. We should add a button (on the bottom of the connection table) "View deleted connections", which shows a list of all deleted connections instead and allow the user to access them.

We need to figure out if this requires new server APIs that allows us to retrieve deleted connections.

Once this is available we should navigate directly away from the connection detail page once the connection gets deleted.

Related to https://github.com/airbytehq/airbyte/issues/10601

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
