### ISSUE TITLE
Design Feedback: Move the cancel button outside of the run click area

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12092]
Current behavior: 
In the Connection Run History page, the `Cancel` button is inside of the Run row, both of which are clickable. The hover state for the whole row activates when hovering over the `Cancel` button which makes it confusing what I will be doing. 

Figma:
https://www.figma.com/file/oHhHM96BTPDiBc2bn7VFKh/CANCEL_RUN?node-id=1%3A3

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
cc @Upmitt - would love to get your thoughts on this when you get a chance. Not super urgent though. Thanks!

**Comment by andyjih** [comment]
Designs: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/?node-id=33740%3A181245

**Comment by dizel852** [comment]
@andyjih could you please double-check the design link you've provided. It seems like the mockup was moved somewhere

**Comment by edmundito** [comment]
Updated description with new design:
https://www.figma.com/file/oHhHM96BTPDiBc2bn7VFKh/CANCEL_RUN?node-id=1%3A3
