### ISSUE TITLE
The cancel button doesn't seem to work or provide feedback to the user

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12091]
Current Behavior:
- When a Sync is running, I see a Cancel button. 
- Click the Cancel button.
- Nothing seems to happen

Proposed Behavior:
- Provide some feedback that Airbyte is canceling or attempting to cancel the sync. I imagine it might take some time for the cancelation to complete.
- 
![2022-04-15_15-45-26 (1)](https://user-images.githubusercontent.com/633226/163650468-386d1cf8-e87a-4789-b806-f648de065d27.gif)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
