### ISSUE TITLE
Browser back button doesn't work from the Connection Details Page

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12093]
Observed Behavior:
- Go to the Connections list page
- Click on an existing Connection
- Click the browser's back button
- See that the user does not go back to the list page.

Expected Behavior:
- The user goes back to the Connections listview page.

![2022-04-15_15-50-42 (1)](https://user-images.githubusercontent.com/633226/163650723-782c3da6-2716-4dab-8da9-a41ae21d241c.gif)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
