### ISSUE TITLE
Source facebook pages: remove the `path_param` method

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12109]
## Tell us about the problem you're trying to solve
[This method](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/streams.py#L31) is no longer being used and is confusing to see. 

## Describe the solution you’d like
Remove the method

**Comment by wub** [comment]
@misteryeo I'll do this one shortly.

**Comment by marcosmarxm** [comment]
Thanks @wub I assign this issue to you, please ping @sajarin if you need any help

**Comment by artem1205** [comment]
fixed while migrating to Low-code
