### ISSUE TITLE
Documentation: Self-service billing for Cloud

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#12110]
### Tell us about the documentation you'd like us to add or update.
Add documentation for Cloud's self-service billing feature.

**Comment by nataliekwong** [comment]
A few questions from users I have seen:
- Where do I go to purchase? (the credits page via the icon in left sidebar)
- How do I get an invoice for my payment? (currently not possible, coming soon)
- How do I get a receipt? (It's automatically emailed after payment)
- How do I know how many credits I need? (recommend reaching out to Sales)
- What is the minimum? (100 credits or $250)
- How do I change the quantity? (on the left hand side during checkout)

**Comment by sophia-wiley** [comment]
Self-service billing documentation available [here](https://docs.airbyte.com/cloud/managing-airbyte-cloud/#buy-credits)
