### ISSUE TITLE
Source Freshsales: `get_view_id` only returns a single view ID

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12111]
## Current Behavior
[This comment](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-freshsales/source_freshsales/source.py#L68) seems to indicate that this method is supposed to return multiple view IDs. But the method only returns a single view ID from a list. 

## Expected Behavior
We need to verify that this is the correct behavior and adjust the comment. If the behavior is incorrect the code should be adjusted.

**Comment by davydov-d** [comment]
on hold until the test account is activated
