### ISSUE TITLE
Source Amazon Seller Partner: not able to connect to Amazon Vendor Central accounts

### ISSUE THREAD

**Issue by krisjan-oldekamp** [airbytehq/airbyte#12124]
The Amazon Seller Partner API is able to connect to both Amazon Seller as Vendor Central accounts. However, during the authentication check in Airbyte when setting up a new connection, The Amazon Seller Partner connector checks if the Orders report can be fetched. The Vendor Central accounts do not have these types of reports so the connector can't be used for Vendor Central accounts. 

## Environment
- **Airbyte version**: 0.35.53
- **OS Version / Instance**: Google Compute Engine
- **Deployment**: Docker
- **Source Connector and version**: Amazon Seller Partner / 0.2.15
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
Connector authentication check fails when trying to connect to a Vendor Central account (because it checks the Orders report, which is not available for Vendor Central accounts).

## Expected Behavior
Connector should succeed when trying to connect to a Vendor Central account (for example to use a report that is available in both Seller als Vendor Central accounts, such as one of the Brand Analytics reports.

</details>

## Steps to Reproduce
1. Try to connect to Amazon Seller Partner API to a Vendor Central account (where the Orders report is not available)

## Are you willing to submit a PR?
No

**Comment by steven91** [comment]
It would be great to add these reports to support vendor central account : 
GET_VENDOR_SALES_REPORT
GET_VENDOR_TRAFFIC_REPORT
GET_VENDOR_FORECASTING_REPORT
GET_VENDOR_INVENTORY_REPORT

https://developer-docs.amazon.com/sp-api/docs/vendor-retail-analytics-reports-migration-guide
