### ISSUE TITLE
Source Freshcaller: CI Sandbox

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#12123]
## Tell us about the new connector you’d like to have
Credentials and integration account for community contribution: https://github.com/airbytehq/airbyte/pull/11987

**Comment by harshithmullapudi** [comment]
Hey @igrankova can you help me out here?

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, sure

**Comment by harshithmullapudi** [comment]
Hey @igrankova any update on this?

**Comment by igrankova** [comment]
Hi, @harshithmullapudi

**Comment by igrankova** [comment]
@harshithmullapudi today I received a call time, waiting for the invitation.

**Comment by harshithmullapudi** [comment]
Thanks for update @igrankova

**Comment by igrankova** [comment]
Hi, @harshithmullapudi 
I've asked the support team about Freshcaller sandbox. The thing is that we already have airbyte-team.myfreshworks.com account and it supports the Contact Center which is the Freshcaller.

The answer is below:
_This is a CRM bundled with the Contact Center, so there is no separate seeder URL to reach out to the Freshdesk Contact Center page.
You can handle everything within the CRM page._

They also gave me the docs link: https://developers.freshcaller.com/api/#authorization

So for now I'm trying to sign up to free trial first but expecting the problems to sign up.
As for my sandbox request, they replied: "From a preliminary level, we do not have any sandbox ability for Freshcaller, only our Freshdesk support desk and Freshservice ITSM products."

But anyway, as I get the trial account and get the API key, I'll let you know.

**Comment by igrankova** [comment]
@harshithmullapudi, 
you can find the creds and API key in the LastPass: Freshcaller
It's a trial account for 20 days for now, but I'm still trying to get a sandbox.

**Comment by harshithmullapudi** [comment]
Got it. Thanks for this

**Comment by igrankova** [comment]
@YowanR I noticed that the Freshcaller account (**LastPass: Primary Freshcaller account**) is expired and there's no option to receive a sandbox. So I'm leaving the pricing here, if we need to reactivate it in the future.
![image](https://user-images.githubusercontent.com/87977540/190131672-343435f8-35c9-4aea-968d-17448f580339.png)
