### ISSUE TITLE
UI Bug - Unable to update snowflake destination credentials

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#12121]
## Environment
- **Airbyte version**:  0.36.0-alpha (and also 0.34.XX)
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 
- **Destination Connector and version**: Snowflake (0.4.24)
- **Severity**: Critical
- **Step where error happened**: Update connector

## Current Behavior
Unable to update any fields in snowflake destination. The `save changes and test` button is greyed out when changing fields.

Additionally, when using the API to update various fields, I included `username` but left out `password`. and now the `password` field in the UI is permanently gone. Even when providing complete list of fields in the API request afterwards.

## Expected Behavior
I should be able to update the destination connector

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Change a field in the destination connector
2.
3.

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
The https://github.com/airbytehq/airbyte/pull/11093 changed the specification of the Snowflake connector. @danieldiamond you must insert the password inside the `credentials` object now. In the UI you must resubmit your password to make the changes.

**Comment by danieldiamond** [comment]
Issue was resulting in not having a password specified in the UI
