### ISSUE TITLE
🐙 octavia-cli: support for secured airbyte instance.

### ISSUE THREAD

**Issue by Imbruced** [airbytehq/airbyte#12137]
## Tell us about the problem you're trying to solve
We are using airbyte on ec2 instance and behind the scenes we have proxy to google sso authentication and basic auth (for airbyte). As far I understand octavia support only non-secured instances. Do you plan to add support such use case ? At the moment I modified octavia code a little bit to make it possible (added two flags --username and --password and creating appropriate header which is then use while creating client)

example below (For Basic auth)
```python
auth = urllib3.util.make_headers(
    basic_auth=f"{username}:{password}"
).get('authorization')

api_client = airbyte_api_client.ApiClient(client_configuration, header_name="Authorization", header_value=auth)
``` 

## Describe the solution you’d like
adding flags for username, password other authentication type arguments
example

```bash
octavia --username 'username' --password 'password' list
```
## Describe the alternative you’ve considered or used
I think there is no alternative ? Correct me if I am wrong.

## Additional context
NA

## Are you willing to submit a PR?
If you need additional resources to be able to provide such functionality I am always eager to help.

**Comment by alafanechere** [comment]
Thank you for this suggestion @Imbruced! We did not implement authentication at first because most of our users use port forwarding or IP whitelisting to connect to their Airbyte instance without auth.
We will consider adding this, probably by introducing new environment variables and CLI options.

**Comment by Imbruced** [comment]
@alafanechere WDYT about adding --headers file ? It will be a lot easier for users to adjust octavia cli to their needs.

**Comment by alafanechere** [comment]
@Imbruced yes this is a good suggestion, what would this file look like?

**Comment by Imbruced** [comment]
File or flag ? Currently octavia cli has 
--airbyte-url which is used to show airbyte instance
For headers we can include 
--headers flag

Correct if I am wrong, at the moment Client which octavia uses (open api) supports only one header and the string should looks like this 
--header "Authorization: Basic dXNlcm5hbWU6cGFhc3N3b3Jk"
Thats generic idea, but that allow users to be more flexible while using octavia cli.

**Comment by blarghmatey** [comment]
This is also relevant for using the CLI in conjunction with Airbyte Cloud. If there's no way to authenticate then it prevents users from being able to use the two utilities together.

**Comment by Imbruced** [comment]
If you don't mind I will create initial PR with unit tests (this weekend). For one of the client this is crucial to manage Airbyte instance securely on aws vpc (I have local version of that issue fixed).
