### ISSUE TITLE
Log View: Allow linking to a specific line in a log

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12130]
We want to give users the option to link to a specific line in the log view. That way we can craft links to specific log lines in other parts of our UI as well as allowing users to reference a specific line explicitally, e.g. when talking to support.

**Comment by lmossman** [comment]
If possible, I think linking to a specific _timestamp_ in the logs would also be really useful here, since I don't think we will always know the exact line number we want to link to, but we should know the timestamp that we want to link to

**Comment by evantahler** [comment]
I took a cursory look into this.  [`react-lazylog`](https://github.com/mozilla-frontend-infra/react-lazylog) is what we use to render logs. It also appears to be [unmaintained](https://github.com/mozilla-frontend-infra/react-lazylog/issues/114). There is an undocumented `scrollToLine` param you can pass the `<LazyLog />` component, but `follow` overrules that option, so we'll need to enable that conditionally if the sync is complete or not
