### ISSUE TITLE
Create `disable_all_connections` API endpoint

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#12146]
## Tell us about the problem you're trying to solve
As a user I'm want to be able to disable all connections in my workspace with one click or API call.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by evantahler** [comment]
For now, we aren't going to prioritize this.
