### ISSUE TITLE
'Reset your data' on a connection with an S3 destination bulk DELETES all sources, not just this connection's

### ISSUE THREAD

**Issue by skwaugh** [airbytehq/airbyte#12141]
## Environment
- **Severity**: beyond Critical
- **Environment**: Ubuntu 
- **Deployment**: Docker
- **Airbyte Version**: 0.35.65-alpha
- **Source**: File (0.2.10)
- **Destination**: S3 (0.3.0)
- **Step where error happened**: Reset your Data

## Current Behavior
`Reset your data` deletes all streams from all sources pointing to a given S3 destination.  I tried to reset a single Source.  
Instead, I've deleted all data synced by 11 different sources. 

## Expected Behavior
`Reset your data` should delete only the directories that correspond to this Source and its Streams.

The Confirmation modal reads: _Resetting your data will delete all the data for this connection in your destination and start syncs from scratch._

NOT 

_Resetting your data will delete all the data for this destination and start syncs from scratch._

No other Destination acts in this manner.  Executing `Reset your Data` with a Postgres Destination deletes the tables for a single source - not all the sources that have connections with that Postgres Destination.

## Logs

logs attached as .txt
[logs-13619.txt](https://github.com/airbytehq/airbyte/files/8514419/logs-13619.txt)
<details>
<summary>LOG</summary> 
`2022-04-19 15:22:17 [32mINFO[m i.a.w.p.DockerProcessFactory(create):158 - Preparing command: docker run --rm --init -i -w /data/13619/0 --log-driver none --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e WORKER_CONNECTOR_IMAGE=airbyte/destination-s3:0.3.0 -e WORKER_JOB_ATTEMPT=0 -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.35.65-alpha -e WORKER_JOB_ID=13619 airbyte/destination-s3:0.3.0 write --config destination_config.json --catalog destination_catalog.json`

</details>

**Comment by voroninman** [comment]
It seems to have been addressed here https://github.com/airbytehq/airbyte/pull/11728. Try `0.3.1` version of AWS S3 destination.

**Comment by marcosmarxm** [comment]
Solved by #11728

**Comment by skwaugh** [comment]
Thanks @voroninman @marcosmarxm !
