### ISSUE TITLE
Documentation: CLI Docs enhancements

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#12140]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

**Task:** Port the content from [GitHub readme](https://github.com/airbytehq/airbyte/blob/master/octavia-cli/README.md) to Docusaurus (main Docs website)

**Comment by somT-oss** [comment]
Hi @Amruta-Ranade,

I would like to work on this issue. 
I have a question though. What does GH stand for?

**Comment by Amruta-Ranade** [comment]
Sure!
GH stands for GitHub :)
