### ISSUE TITLE
Facebook can hit limits in request size with the current page_size=100

### ISSUE THREAD

**Issue by mdibaiee** [airbytehq/airbyte#12168]
## Environment
- **Airbyte version**:  N/A
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: 0.2.44
- **Destination Connector and version**: N/A
- **Severity**: High
- **Step where error happened**: Sync

## Current Behavior
I'm getting a Facebook API request size limit because of the current page_size=100.

```
{
  "timestamp": "2022-04-20T07:43:58.29039541Z",
  "level": "ERROR",
  "self.message": "Giving up call(...) after 5 tries (facebook_business.exceptions.FacebookRequestError:
  
  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v13.0/act_***********/activities?access_token=****&fields=actor_id,actor_name,application_id,application_name,date_time_in_timezone,event_time,event_type,extra_data,object_id,object_name,object_type,translated_event_typeu0026summary=trueu0026filtering=[{'field':'activity.delivery_info','operator':'IN','value':['active','archived','completed','limited','not_delivering','deleted','not_published','pending_review','permanently_deleted','recently_completed','recently_rejected','rejected','scheduled','inactive']}]u0026since=1609459200u0026after=cHVtYV9hbmNob3I6TVRZAeE5EZAzNOelUzTURFMU9DTTFOMkV5TmpObU5XRXhOalZAqT0dRMVpqazJOelEyTVRJNE4ySmlZAalF3TlRFeVl6SXlOR015WkRneE1USXhNelprTlROaU1EYzRZAekV5TXpCaFkyRmwjOTMZDu0026limit=10
  Params:  {'summary': 'true'}
  Status:  500
  Response:    {      'error': {        'code': 1,        'message': 'Please reduce the amount of data you're asking for, then retry your request'      }    })"
}
```

## Expected Behavior
- We should be able to configure the page_size to work around this kind of limitation.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Yes: https://github.com/airbytehq/airbyte/pull/12171

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/12171
