### ISSUE TITLE
[EPIC] 2022 Implement OAuth in OSS Connectors (not in Cloud)

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#12166]
### The main purpose of this epic is to track OAuth implementation progress for the connectors that are in OSS but not in Cloud.

For all connectors that are in OSS but not in Cloud, the team should make sure to [address this checklist item for OAuth](https://share.getcloudapp.com/L1uReK21) in parallel with any engineering efforts.
The team should prioritize work based on the connectors listed [here](https://docs.google.com/spreadsheets/d/10WspQDRR0S2m07aqRsET7KI2N-2GiEu-joAatQzLnRM/edit?usp=sharing).

The first priority is Required OAuth connectors. the second - Connector Supports OAuth, not required.

**Comment by igrankova** [comment]
@misteryeo 
Hi, I've updated the list. What is our next step?

**Comment by misteryeo** [comment]
@igrankova Thanks! Can you confirm that everything that the Unblockers team is able to do has been completed and the only remaining items are for engineering to actually implement OAuth?

I had one question on an issue marked as blocked: https://github.com/airbytehq/airbyte/issues/6289 - the latest comment seems to indicate that there's no further work to be done. What is blocked here?

**Comment by igrankova** [comment]
Hi, Andy,Yes, it’s done from unblockers’ side.I guess the issue #6289 is in the wrong status. I’ve closed it. Thank you. Iryna GrankovaSystem Business Analyst (Unblocker)GlobalLogic Inc. and its affiliates at1741 Technology Drive, Suite 400, San Jose, CA 95110, USAwww.globallogic.com+380636306253 From: AndySent: 7 червня 2022 р. 21:37To: airbytehq/airbyteCc: Iryna Grankova; MentionSubject: Re: [airbytehq/airbyte] [EPIC] 2022 Implement OAuth in OSS Connectors (not in Cloud) (Issue ***@***.*** Thanks! Can you confirm that everything that the Unblockers team is able to do has been completed and the only remaining items are for engineering to actually implement OAuth?I had one question on an issue marked as blocked: #6289 - the latest comment seems to indicate that there's no further work to be done. What is blocked here?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
