### ISSUE TITLE
Enforce Checkstyle for Java modules in OSS

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#12176]
## Tell us about the problem you're trying to solve

Inconsistent code quality between modules can make it difficult for contributors to work in the code.  Standardizing on a style and avoiding common coding mistakes will make it easier to contribute to the OSS project.

## Describe the solution you’d like

Apply the [Checkstyle Gradle plugin](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) and utilize the [configuration from the Cloud project ](https://github.com/airbytehq/airbyte-cloud/blob/master/tools/gradle/checkstyle/checkstyle.xml)to add [Checkstyle](https://checkstyle.org/index.html) enforcement to all Java modules in the OSS project.

## Additional context

Additional configuration bits:

* [Apply the plugin](https://github.com/airbytehq/airbyte-cloud/blob/master/build.gradle#L167)
* [Configure the plugin](https://github.com/airbytehq/airbyte-cloud/blob/master/build.gradle#L184)
* [Add exclusions to avoid generated code](https://github.com/airbytehq/airbyte-cloud/blob/master/build.gradle#L313)

## Acceptance Criteria

- [ ]  Plugin applied to all Java modules in OSS
- [ ]  Custom ruleset is used
- [ ]  All existing warnings are addressed

**Comment by davinchia** [comment]
Won't do!
