### ISSUE TITLE
🐛 Source Github: add incremental support to streams: Repositories, PullRequestCommentReactions, IssueReactions, IssueCommentReactions, CommitCommentReactions

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#12173]
## Tell us about the problem you're trying to solve
Add incremental support to streams: `Repositories`, `PullRequestCommentReactions`, `IssueReactions`, `IssueCommentReactions`, `CommitCommentReactions`

**Comment by ChristopheDuong** [comment]
It's very related but it would be nice to add more incremental options to other streams too, not just repository, see https://github.com/airbytehq/airbyte/issues/12266

(should we create issue for each streams to be incremental?)

**Comment by grubberr** [comment]
@ChristopheDuong thanks for this issue, I have assigned to myself.
 I will implement incremental for all rest streams where it possible in one PR
