### ISSUE TITLE
Add an endpoint to retrieve the connection's state type

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#12189]
After updating the schema for the state we need to expose the type of state which is expose.

## What need to be done

We need to add a new endpoint that will return the type of the state that is handle by a given connection. In order to do that we need a new endpoint and a persistence method to get the supported types.

**Comment by cgardens** [comment]
Grooming Notes:
* Use case: to allow or not allow per stream resets. 
* We do _not_ need to predict what state a connection will produce, we only care about what the _currently_ stored state.
* Basically display if the current state is per-stream or global by looking in the state_table
* If no state, default to global
