### ISSUE TITLE
Set date and/or time from a date picker in the connector UI

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12197]
## Tell us about the problem you're trying to solve
When editing the connector settings, users have to type in the date or date time and use the correct format depending on the type of connector. Typing this manually can lead to a number of issues such as:

- Understanding what the right format is for the connector
- Context switching between connector's expected values.
- Human error in typing the value
- User has to calculate their own timezone time to UTC

In this example for the Slack connector, the user must first read the description to understand how to enter the value correctly:
![image](https://user-images.githubusercontent.com/168664/164310783-73932a51-3a28-4f0d-bc36-2b2fcb411ecf.png)

The Github connector has a different description even though the format is the same, so the user must now memorize that the format is different, even though it's the same format.

![image](https://user-images.githubusercontent.com/168664/164311075-f9678b57-f329-413d-a7c9-2ceafee870a2.png)

Some connectors, such as the Exchange Rates API, just require date but not time:
![image](https://user-images.githubusercontent.com/168664/164311307-5eb754b1-27d1-4853-9a7d-04be56c13ae6.png)

## Describe the solution you’d like
The connector UI presents a date picker (with a time picker when appropriate and we determine it's important to set) so that the user can just select the date and time without having to worry about what's described above.

The ideal solution would use an existing OSS date component re-themed to fit the Airbyte UI. Building our own solution may be too complex or out of scope.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Example feedback from a Cloud user:
<img width="780" alt="Screen Shot 2022-06-10 at 1 15 11 PM" src="https://user-images.githubusercontent.com/38087517/173143811-1529b1e8-554e-4f20-9d66-1acf5272a91b.png">

**Comment by sherifnada** [comment]
@timroes i think this was already done, so I closed it. Please let me know if this is an error.
