### ISSUE TITLE
Connector UI group label is not aligned with group border or dropdown

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12199]
## Current Behavior
The Group label, the box its in, and the dropdown aren't aligned:
<img width="687" alt="Screen Shot 2022-04-20 at 11 40 51 AM" src="https://user-images.githubusercontent.com/633226/164300478-e038b8bc-8933-4b28-bd5c-af15d381e4bf.png">

## Expected Behavior
The label should vertical align with the horizontal line  and the dropdown

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
