### ISSUE TITLE
External password generator button overlaps with "show password" button

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12202]
## Current Behavior
With password generators (such as 1Password or LastPass,) the generator button injected into the page overlaps with our "show password" button.

<img width="144" alt="Screen Shot 2022-04-20 at 11 54 29 AM" src="https://user-images.githubusercontent.com/633226/164302595-016c677b-59b9-45fe-8632-440e61450199.png">

## Expected Behavior
The password generator button appears to the left of the show password button

## Steps to Reproduce
1. Have a password manager extension installed in your browser
1. Navigate to a source settings page that has a password field

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
