### ISSUE TITLE
Source Mixpanel: Incremental Sync

### ISSUE THREAD

**Issue by aharelick** [airbytehq/airbyte#12209]
Not currently implemented for the Engage, Annotations, Cohorts and Cohort Members streams.

Incremental Sync:
- Engage -> Needs investigation if 'created' property is present by default, if it is custom property stream will require user-defined cursor. *might require dynamic schema creation for custom user defined properties
- Annotations -> Date field present but connector note says 'annotation date - is the date for which annotation was added, this is not the date when annotation was added That's why stream does not support incremental sync.'
- Cohorts -> Contains 'created' field which can be used for incremental sync
- Cohorts Members -> Needs investigation if 'created' property is present by default, if it is custom property stream will require user-defined cursor. *might require dynamic schema creation for custom user defined properties.

^^ Taken from: https://github.com/airbytehq/airbyte/issues/11008#issuecomment-1073719600.

**Comment by itaseskii** [comment]
I'll claim this issue
