### ISSUE TITLE
In new source/destination UI, when switching type after having missing/invalid fields, red highlight does not reset

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12201]
## Current Behavior
If I see a required field validation error and then change the Source type, the new form fields show the same validation error. Perhaps the error is being tied to the Input Label. ![2022-04-20_11-49-06 (1)](https://user-images.githubusercontent.com/633226/164302054-17e2c52f-43ac-4da2-80bd-c639f842c5c5.gif)

## Expected Behavior
The red text should clear

## Steps to Reproduce
1. Create a new source or destination
2. Select a type and submit. Notice the required field descriptions are red
3. Select a different type

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Neither @edmundito nor I were able to reproduce this issue.
