### ISSUE TITLE
Full Stream Coverage

### ISSUE THREAD

**Issue by aharelick** [airbytehq/airbyte#12219]
Need Webhooks, Workspaces, Images, Themes implemented.

Going through the [reference](https://developer.typeform.com/get-started/) API documentation it seems that the connector is missing the following streams:

- Webhooks -> [https://api.typeform.com/forms/{form_id}/webhooks](https://api.typeform.com/forms/%7Bform_id%7D/webhooks)
- Workspaces -> https://api.typeform.com/workspaces
- Images -> https://api.typeform.com/images
- Themes > https://api.typeform.com/themes

^^ Taken from https://github.com/airbytehq/airbyte/issues/10947#issuecomment-1089131964.

**Comment by itaseskii** [comment]
I'll claim this issue

**Comment by alafanechere** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/13079
