### ISSUE TITLE
Remove sync mode from StandardSync struct

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1224]
## Tell us about the problem you're trying to solve
* The original data model configured sync mode on StandardSync. The new one does it at a stream level in the catalog. The field on StandardSync should not be used and should be removed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368135118630) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
We should have a migration that removes these from exported archived too

![Screenshot 2021-01-27 at 17 19 44](https://user-images.githubusercontent.com/7718175/106020279-e0b85c80-60c3-11eb-843f-abbb2af05cb6.png)
