### ISSUE TITLE
Source Freshservice: incorrect schema data type used

### ISSUE THREAD

**Issue by BenjaminGK** [airbytehq/airbyte#12243]
## Environment
- **Airbyte version**:  Master-branch
- **Source Connector and version**:  Freshservice
- **Severity**: High
- **Step where error happened**: Sync job 

## Current Behavior
*Tell us what happens.*
The current schema data type used for Freshservice is incorrect due to incorrect documentation from Freshservice which means that it is not possible to sync data due to incorrect columns being created.

## Expected Behavior
*Tell us what should happen.*
Ticket endpoint: 
**Category** field should be string instead of integer

Requester endpoint: 
**work_phone_number** should be string instead of integer
**mobile_phone_number** should be string instead of integer

Agent endpoint
**work_phone_number** should be string instead of integer
**mobile_phone_number** should be string instead of integer

**Comment by sajarin** [comment]
This is solved by #25743
