### ISSUE TITLE
Improve user experience when deleting a connection

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#12250]
## Tell us about the problem you're trying to solve
After a user clicks "Delete" in the confirmation modal to delete a connection, there isn't any visual confirmation that something has happened.  The button enters a loading state, but once it is done with loading the modal and button stick around, and the button is clickable, unless a user clicks "Cancel" or navigates to a different page.

If I navigate back to the Connections list page, I do see that the Connection  I've deleted has been removed.

## Describe the solution you’d like
To discuss

## Describe the alternative you’ve considered or used
- The modal turns into a confirmation that the connection is being deleted
- Redirect to Connections list page (or another page)
- Other?

## Additional context
https://user-images.githubusercontent.com/63751206/164517919-f555f792-a47b-4419-89c5-6d3f48c06eac.mo

related to https://github.com/airbytehq/airbyte/issues/10601

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This has been addressed nowadays and deleting a connection will navigate away from it.
