### ISSUE TITLE
Support OAuth for Snowflake destination

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12256]
## Tell us about the problem you're trying to solve
Currently for our snowflake destination we only support authentication via username and password but snowflake supports other forms of authentication as well. 

## Describe the solution you’d like
User should be able to use OAuth to authentication Airbyte Snowflake destination connector to Snowflake

## Describe the alternative you’ve considered or used
use username/password authentication mechanism

## Additional context
Snowflake documentation on OAuth: https://docs.snowflake.com/en/user-guide/oauth-snowflake.html

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202164096970304) by [Unito](https://www.unito.io)

**Comment by etsybaev** [comment]
I believe that we've implemented it in this pr
https://github.com/airbytehq/airbyte/pull/11093

**Comment by misteryeo** [comment]
Don't we already support this @grishick https://share.getcloudapp.com/wbuz446J?

**Comment by grishick** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/10033
