### ISSUE TITLE
Support Key Pair authentication for Snowflake destination

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12255]
## Tell us about the problem you're trying to solve
Currently for our snowflake destination we only support authentication via username and password but snowflake supports other forms of authentication as well. 
Ref : https://docs.snowflake.com/en/user-guide/authentication.html

## Describe the solution you’d like
A user should be able to use key pair authentication for Snowflake destination connector. More info here: https://docs.snowflake.com/en/user-guide/key-pair-auth.html

## Describe the alternative you’ve considered or used
The alternative is to use username/password authentication

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202164094257848) by [Unito](https://www.unito.io)

**Comment by bashyroger** [comment]
We need this too, as we are obliged to have MFA on in snowflake. Only by using key pair authentication can we mitigate the issue of unwanted MFA popups when using airbyte based Snowflake target connectors.

**Comment by etsybaev** [comment]
This ticket partially clones https://app.zenhub.com/workspaces/java-connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/6588

**Comment by sashaNeshcheret** [comment]
In scope of the ticket we need to:
- create private/public key;
- add it to snowflake user;
- add toggle for username/password or private/public key authentication;
- handle private/public key for jdbc.

**Comment by sashaNeshcheret** [comment]
- In scope of the ticket we need:
- generate keys;
- add them to snowflake user;
- create file with key for openssl;
- update jdbc config;
- add integration test for it.

**Comment by sashaNeshcheret** [comment]
@grishick do we need to create the same ticket for snowflake source?

**Comment by grishick** [comment]
> @grishick do we need to create the same ticket for snowflake source?

Yes, please create a separate ticket for the source
