### ISSUE TITLE
Source Github: add incremental support to workflow streams

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#12266]
## Tell us about the problem you're trying to solve
add incremental support to workflow streams

## Describe the solution you’d like
This cloud connection for internal usage: https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/a6bfadb7-182a-4766-81fd-1bc70597e594/replication
1. Should work
2. Be able to setup incremental sync modes for those streams

## Related Context
See https://github.com/airbytehq/airbyte-warehouse/issues/79#issuecomment-1104407338

**Comment by ChristopheDuong** [comment]
I verified on Airbyte-cloud that the streams are not configurable with incremental replication.

This is indeed the case (requires a reset schema though) on the workflow stream but not on the workflow_run streams

As an example, when pulling from the Airbyte OSS repo:
- workflow table size: 166.88 KB 
- workflow_run table size: 39.27 GB 

So the tiny table is now available for incremental updates but the huge one has to go through full_refresh... This does not make much sense, it would be better if it was the other way around instead (or have both being incremental)

@grubberr Should I re-open this issue?

**Comment by ChristopheDuong** [comment]
Note that the docs https://docs.airbyte.com/integrations/sources/github#output-schema has not been updated to reflect the changes from the new incremental streams either

cc @Amruta-Ranade

**Comment by grubberr** [comment]
@ChristopheDuong finally I have published, can we re-sync and check size again ?

**Comment by ChristopheDuong** [comment]
I'm re-opening the issue until we can confirm it is working on airbyte-cloud

**Comment by grubberr** [comment]
ok let's check airbyte cloud

**Comment by grubberr** [comment]
@ChristopheDuong do you have an idea how we can speed up this publish to cloud ? 
I want to make sure that everything is working and close this issue 
because we try to ceritify github for GA 
Thank you

**Comment by ChristopheDuong** [comment]
You could contact the person in charge of connector OnCall to help you out with deployments

But it seems 0.2.31 is deployed on cloud already.
However the sync here https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/a6bfadb7-182a-4766-81fd-1bc70597e594/status doesn't look to be finishing properly. Maybe you could look into the logs to investigate why?

**Comment by grubberr** [comment]
2022-06-04  Killed (too long)
2022-06-06 success 

Can we change sync_mode for `workflow_runs` from **full_refresh** to **incremental**?

**Comment by grubberr** [comment]
@ChristopheDuong PR for fixing memory problem https://github.com/airbytehq/airbyte/pull/13558

**Comment by grubberr** [comment]
Sync 

time                                            | report
------------------------------|------------
1:35AM 06/10 (2-nd attempt) | Read 325159 records from `workflow_runs` stream
9:24AM 06/10                           | Read 162 records from `workflow_runs` stream

No OOM killed
Incremental works!

@ChristopheDuong can we close this issue ?

**Comment by ChristopheDuong** [comment]
Great thanks!
