### ISSUE TITLE
🤖 /publish command: auto bumping version for multiple connectors in same PR fails

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#12276]
## Tell us about the problem you're trying to solve
If you /publish multiple connectors at the same in the same PR, the auto-bump will likely fail on any after the first because the git HEAD isn't up-to-date with the newly auto pushed changes from the first publish.

See example here: https://github.com/airbytehq/airbyte/pull/12274

## Describe the solution you’d like
Add a fetch + pull before we do the push from Octavia so we can catch this most of the time (there is still a window that this could fail on but it's significantly decreased with this fix)

**Comment by sherifnada** [comment]
@Phlair can you add this to the backlog grooming agenda?
