### ISSUE TITLE
🐛 octavia-cli: connections re-created on apply

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12270]
## Current Behavior
When a user generates a connection configuration and edits fields such as `namespace_definition` or `namespace_format` the connection is created but subsequent `octavia apply` recreates the same connection again leading to multiple connections getting created for a single config.

## Expected Behavior
The original connection should be updated on configuration changes.

**Comment by livelace** [comment]
@alafanechere Hi. I experience recreation problem right now with 0.42.1 octavia. Could you comment on this ?

**Comment by nlevee** [comment]
Same here, it recreate everything each time I apply
