### ISSUE TITLE
Update Metabase reports to exclude `failureType=config_error` failures from failure reports

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12284]
Connectors should not be noted as failing (for GA & Beta purposes) if their syncs were prevented by `failureType=config_error`.  This story is to add a new dashboard which is inline with https://docs.google.com/document/d/1yqnGKyqftA3nmzHrz970Qv8_vSL7ro8CUGIS99oIMxY/edit#heading=h.agrxfsjj7zsy

**Comment by evantahler** [comment]
cc @bleonard

**Comment by sherifnada** [comment]
@evantahler to update the ticket description to reflect current plan

**Comment by sherifnada** [comment]
next step for someone taking on this ticket is: 
1. talk to brian leonard / evan to understand exactly the goals we want to achieve with this 
2. do it!

**Comment by evantahler** [comment]
This story is also blocked by https://github.com/airbytehq/airbyte-warehouse/issues/92

**Comment by evantahler** [comment]
Closed in favor of https://github.com/airbytehq/airbyte-warehouse/issues/83
