### ISSUE TITLE
Option to change polling time in spec when consuming records for Source Kafka

### ISSUE THREAD

**Issue by tirth7777777** [airbytehq/airbyte#12296]
When consuming records for source Kafka, consumer polling time is fixed at 100ms. I need to increase the polling time so i need a option to change polling time using spec.

**Comment by tirth7777777** [comment]
I have fix ready for this. Should i create a pull request?

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/12903
