### ISSUE TITLE
New sandbox account: Enquire labs

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12308]
New connector PR: https://github.com/airbytehq/airbyte/pull/12264
Source service: https://enquirelabs.com/

Could you please create a sandbox account for EnquireLabs API?

**Comment by igrankova** [comment]
Hi, @alafanechere 
The LastPass creds name: enquirelabs.com
App creds: https://app.enquirelabs.com/shopify/account

**Comment by alafanechere** [comment]
Thank you @igrankova!!!
