### ISSUE TITLE
New sandbox account: Junip.co

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12309]
New connector PR: https://github.com/airbytehq/airbyte/pull/12267
Source service: https://junip.co/

Could you please create a sandbox account for Junip API?

**Comment by igrankova** [comment]
Hi, @alafanechere 
I've signed up for free test account, the **LastPass creds name:** Junip.co
The connected shopify store they asked is Airbyte. I also have installed the Junip app in the store.
I've asked about the sandbox by email to support and let you know when it's done. For now if you can use this free account, I hope it could be an option to start working.

**Comment by igrankova** [comment]
@alafanechere, I received an answer from the support that we can use this free plan permanently and we have a fool access to the API. If you need any additional functionality, please let me know, I can request it.

**Comment by alafanechere** [comment]
Thank you @igrankova!!!
