### ISSUE TITLE
Hubspot Connector 0.1.53 uses incorrect ticket_pipeline date type

### ISSUE THREAD

**Issue by austinhale** [airbytehq/airbyte#12318]
## Environment
- **Airbyte version**:  example is 0.36.2-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Hubspot 0.1.53
- **Destination Connector and version**: Postgres 
- **Severity**: High
- **Step where error happened**: Setup new connection (first sync)

## Current Behavior
When setting up a new Hubspot source connection, the sync fails if including the `ticket_pipelines` table & syncing to a source of Postgres due to a `Database Error in model ticket_pipelines (models/generated/airbyte_tables/hubspot/ticket_pipelines.sql)` which in this case is further described in the next two log lines: 
-  `invalid input syntax for type bigint: "2021-10-14T19:39:27.105Z"` 
- `compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/hubspot/ticket_pipelines.sql`

## Expected Behavior
Sync would occur successfully & create the corresponding rows in the destination. 

## Steps to Reproduce
1. Set up brand new Airbyte install on EC2
2. Create a Postgres destination
3. Create a Hubspot source
4. Try to sync the `ticket_pipelines` table

## Are you willing to submit a PR?
Yes

## Note
I am fairly confident making this change would fixe the issue. The [date fields here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/ticket_pipelines.json)

from 
```
    "createdAt": {
      "type": ["null", "integer"]
    },
    "updatedAt": {
      "type": ["null", "integer"]
    }
```

to 
```
"createdAt": {
      "type": ["null", "string"],
      "format": "date-time"
    },
    "updatedAt": {
      "type": ["null", "string"],
      "format": "date-time"
    },
```

Hubspot docs show those fields as date-time / string, not integers as well. 

![Screen Shot 2022-04-25 at 11 27 19](https://user-images.githubusercontent.com/6180399/165151137-626f0ef7-3bcb-4eab-ac64-53e24ccef092.png)

**Comment by marcosmarxm** [comment]
@austinhale can you update to version 0.1.53?

**Comment by austinhale** [comment]
Updated and the sync is now successful! Thanks @marcosmarxm 🙏

**Comment by DustyShap** [comment]
Seeing this issue on the current connection version:

https://discuss.airbyte.io/t/hubspot-to-postgres-sync-failures/1617

**Comment by DustyShap** [comment]
> @DustyShap did you update the schema after updating the connector version? Don't forget to click in Refresh New Schema ![image](https://user-images.githubusercontent.com/5154322/176040385-3c0a1ae6-e60a-4af6-a680-bb096f4bb7e1.png)

I did not, but I have now and it appears to be working.  Thanks for the 👀 .
