### ISSUE TITLE
Don't go back to the previous workspace when logging in with a different user

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12311]
We currently try to bring the user back after login to where they cam from. This leads to the weird scenario, if a user will log out and sign in (or register) with a different user, that doesn't have permission to the same workspace, they'll just see an error message because they can't access that workspace. Despite us needing to improve that error message (tracked via https://github.com/airbytehq/airbyte/issues/10735) we should not try to bring you back to the same workspace if you change your user after going to the login screen, but instead trying to bring them to their default workspace instead.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
