### ISSUE TITLE
Documentation link not rendering for alpha/beta connectors in-app

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12324]
connector.docsLink is shown instead of the URL to our connector docs. Applies to all connectors I can see in Airbyte Cloud.

![Airbyte New Source 2022-04-25 at 2 02 03 PM](https://user-images.githubusercontent.com/16851149/165174628-5febad74-b7fd-4152-93d5-23e602488b7e.jpg)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This broke with https://github.com/airbytehq/airbyte/pull/12252. Related to https://github.com/airbytehq/airbyte/issues/12321
