### ISSUE TITLE
Oracle database connector

### ISSUE THREAD

**Issue by zkiffli** [airbytehq/airbyte#1232]
## Tell us about the new integration you’d like to have
Source/Destination from/to oracle database

## Describe the context around this new integration
To do ETL

## Describe the alternative you are considering or using
Airflow

**Comment by michel-tricot** [comment]
Thanks @zkiffli !

Are you using a version in particular?

**Comment by zkiffli** [comment]
> Thanks @zkiffli !
> 
> Are you using a version in particular?

hi @michel-tricot thanks for your feedback. 
Yes, currently I'm using various oracle versions  e.g11g, 12c, .18 and 19 also. 
Thanks.

**Comment by sherifnada** [comment]
There is a [free test container ](https://www.testcontainers.org/modules/databases/oraclexe/) that can be used for testing, and a [JDBC driver](https://www.oracle.com/database/technologies/appdev/jdbc.html), so this could be a quick one.

**Comment by walkabout21** [comment]
Very interested in seeing this happen.  Using v19 at the moment.  Airbyte is a non starter at this point without an Oracle connector.

**Comment by JensGorman** [comment]
Oracle is still the most popular database, see [https://db-engines.com/en/ranking](url).

**Comment by sherifnada** [comment]
@walkabout21 or @JensGorman would either of you be interested/able in contributing this connector to Airbyte? We are strictly limited by bandwidth in implementing this connector.

Since it's JDBC-based, it could be pretty straightforward to implement it. The [postgres source](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-postgres) is an example.

**Comment by marcosmarxm** [comment]
@sherifnada can I take this?

**Comment by sherifnada** [comment]
@marcosmarxm absolutely! Java connectors are fully embedded in the gradle build and follow the normal development process (more details on [developing locally](https://docs.airbyte.io/contributing-to-airbyte/developing-locally).

The [Oracle DB test container](https://www.testcontainers.org/modules/databases/oraclexe/) and [JDBC driver](https://www.oracle.com/database/technologies/appdev/jdbc.html) will probably be useful here :) 

Can you take a look at these resources and let me know what support or information we can provide you with to help you get started? 

BTW, the simplest way to begin development is probably to copy `airbyte-integrations/connectors/source-postgres` into `airbyte-integrations/connectors/source-oracledb`, rename/refactor until you have a working implementation.

**Comment by zkiffli** [comment]
Thanks everyone for the brilliant effort. 🥇

**Comment by JensGorman** [comment]
Yes, thank you all very much!
