### ISSUE TITLE
GA tag hover description is not showing description 

### ISSUE THREAD

**Issue by erica-airbyte** [airbytehq/airbyte#12321]
## Environment
- **Airbyte version**:  Cloud Version: 0.36.3-alpha-0430dde
- **Deployment**: cloud
- **Severity**: Low
- **Step where error happened**: when hovering over connector description in the connector Status page

## Current Behavior
When hovering over the "info icon" for a GA connector it does not give the correct description.  

## Logs
<img width="528" alt="Screen Shot 2022-04-25 at 1 28 06 PM" src="https://user-images.githubusercontent.com/93952107/165160176-982ce375-8b4e-4bb2-9466-14333df5d951.png">

## Are you willing to submit a PR?
No

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
