### ISSUE TITLE
Add connector test that validates that the spec uses "valid" JSONSchema

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#12330]
## Problem
For the `spec` of a connector, we allow the usage of a _subset_ of the functionality that JSONSchema provides. When a `spec` uses a disabled JSONSchema feature it results in perplexing errors.

# Proposed Solution
* We should have a way to validate that a JSONSchema object only uses the features we allow. 
* We would it as one of the standard tests for each connectors so that before publishing a connector the developer could bring the spec into compliance.

Put this in OSS Platform and Sources DX backlogs as it will be a quality of life improvement for both.

@sherifnada @evantahler @bleonard for visibility.

**Comment by sherifnada** [comment]
@cgardens is the allowed subset of json schema described anywhere? I tried documenting as much as i know [here](https://docs.airbyte.io/connector-development/connector-specification-reference) over time but I'm not sure if there are other limitations/features.

**Comment by cgardens** [comment]
So far the subset I have in mind is:
* don't use `not`
* `type` MUST be set. for pure JSONSchema there are reasons why you might want to leave it unset, but for our use case, doing that is just a headache. See the long conversation Benoit and I had in the linked issue.
* the `oneOf`s stuff that is mentioned in the [docs you linked](https://docs.airbyte.com/connector-development/connector-specification-reference/#using-oneofs).
* When `airbyte_secret` can be used. I think the only types that should have `airbyte_secret` added to it are string, number, array<string> , and array<number>. But we have to do all of this other bonkers stuff right now to cover our behinds because theoretically someone could naively stick that flag anywhere. A compile time loud failure saves a lot of confusion at runtime.

**Comment by sherifnada** [comment]
cc @flash1293 related to your interest in additional SATs for the frontend

**Comment by flash1293** [comment]
Thanks, missed this issue. I copied over all context to https://github.com/airbytehq/airbyte/issues/20063 , closing this to consolidate
