### ISSUE TITLE
How can we enable Airbyte metrics on prometheus

### ISSUE THREAD

**Issue by chetangehlot** [airbytehq/airbyte#12338]
As I see your README but it is not sufficient documentation for deploying on my kubernetes.

Ref : - https://github.com/airbytehq/airbyte/tree/master/airbyte-metrics

**Comment by marcosmarxm** [comment]
Today is only possible to export to DataDog, @davinchia can you confirm it?

**Comment by davinchia** [comment]
Yes. This is not yet possible today. We are exploring adding an Open Telemetry interface to make this possible. This is slated for this quarter and will be done in a few weeks.

**Comment by chetangehlot** [comment]
Thanks @davinchia and @marcosmarxm .

**Comment by davinchia** [comment]
Update: we are rolling out an OTEL implementation users will be able to use in the next few weeks.

**Comment by xiaohansong** [comment]
Hello @chetangehlot!

The feature is now available - please see https://docs.airbyte.com/operator-guides/collecting-metrics/ for how to enable open telemetry on airbyte. Thanks for your request!
