### ISSUE TITLE
Duplicate record accumulated in _airbyte_raw_<table_name> for sync failed retry

### ISSUE THREAD

**Issue by nshigit** [airbytehq/airbyte#12336]
## Environment
- **Airbyte version**:  0.35.65-alpha
- **OS Version / Instance**: centos
- **Deployment**: docker
- **Source Connector and version**: airbyte/source-mysql  0.5.6 
- **Destination Connector and version**: airbyte/destination-mysql     0.1.18
- **Severity**:  High
- **Step where error happened**: Sync job

## Current Behavior
Each error retry adds duplicate records to the target table, resulting in the final number of records synchronized being retries.
row number:
source table: 100
after three times retry
destination normalize table: 300
after normalize finish:
destination table: 300

## Expected Behavior
Sync job doesn't remove dulicated table in normalize table.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. change the destination database host address to an unreachable address, that would cause sync job failed.
2. manual start sync job. 
3. the worker will retry three times (the number of retries can't be setting)
4. check normalize table row number

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
This is the high-level table or a nested table? Check the issue: https://github.com/airbytehq/airbyte/issues/9465

**Comment by marcosmarxm** [comment]
The raw tables can have duplicate records. You must use dedup+history to generate final table with deduplication rows.
