### ISSUE TITLE
Fix Hubspot schema and add date-time format test in SAT

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#12333]
I was testing a new JSON schema validation feature using the JsonSchemaValidator to validate that each record from a source conforms to the schema in the ConfiguredAirbyteCatalog. When I tested Hubspot, I saw a record schema validation for every record because several Hubspot streams include schemas with date-time fields like this:
```
"createdate" : { "type" : [ "null", "string" ],
                           "format" : "date-time"}
```
but the records themselves have datetimes that look like this: `"createdate":"2021-01-13 10:25:46"`

This fails validation because the JsonSchemaValidator expects date-time strings to be formatted with a T separating the date and time (`"createdate":"2021-01-13T10:25:46"`).

To fix this, we need two things:
1) Update the Hubspot schema to remove the date-time format for the createdate field
2) add a date time test case in SAT or Hubspot specific unit test that looks like "createdate":"2021-01-13 10:25:46".

**Comment by austinhale** [comment]
@alovew I ran into a [related issue](https://github.com/airbytehq/airbyte/issues/12318) yesterday with our Hubspot connector; however, at least on the `ticket_pipelines` table that's throwing the error, the date format in Hubspot is in ISO 8601 e.g. `2021-10-14T19:39:27.105Z` & the current airbyte schema file has the field as `integer`, hence the error.

Which table are you seeing the value without a T separator?

**Comment by alovew** [comment]
@austinhale I'm seeing it in the deals table

**Comment by austinhale** [comment]
@alovew odd -- are you seeing that same thing if you direct pull from their API? I just double checked two instances I have access to and I'm only able to get ISO 8601 results, which matches what their current API docs show in terms of the response object for deals (screenshot below). Is the Hubspot instance you're pulling the dates from older? I know they did some API date standardization back in ~ 2015, I believe. Per my understanding, at least after that standardization project they [accept both ISO 8601 & Unix epoch time formats for requests but responses only get returned as ISO 8601](https://developers.hubspot.com/docs/api/faq#timestamps). 

![Screen Shot 2022-04-28 at 09 52 52](https://user-images.githubusercontent.com/6180399/165804315-9ded7f2b-ffa6-499f-9d34-fa3184d18674.png)
