### ISSUE TITLE
Airbyte API: `WebBackendConnectionCreate` in OpenAPI config requires a property which is not listed in properties

### ISSUE THREAD

**Issue by Ohcui** [airbytehq/airbyte#12340]
## Environment
- **Airbyte version**:  0.36.3-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**: any
- **Destination Connector and version**: any
- **Severity**: Medium
- **Step where error happened**: Check `components.schemas.WebBackendConnectionCreate` section in `src/main/openapi/config.yaml` file

## Current Behavior
In WebBackendConnectionCreate config, there is no "connection" key in properties, but listed in required.

## Expected Behavior
No "connection“ key in required config.

## Are you willing to submit a PR?
Yes

**Comment by Ohcui** [comment]
I want to work on this.

**Comment by timroes** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/12341
