### ISSUE TITLE
Databases and Data warehouses Benchmark: Create connections for Full Refresh Overwrite

### ISSUE THREAD

**Issue by noahkawasaki-airbyte** [airbytehq/airbyte#12355]
Create the actual connections between sources/destinations for each benchmark dataset using full refresh. Use the octavia CLI to manage these connections in code. Say we have 3 benchmark datasets: small, medium, large. And two database sources: postgres and mysql. Two datawarehouses: snowflake and redshift.

We want these connections created

postgres - small - full refresh
postgres - medium - full refresh
postgres - large - full refresh
mysql - small - full refresh
mysql - medium - full refresh
mysql - large - full refresh

snowflake - small - overwrite
snowflake - medium - overwrite
snowflake - large - overwrite
redshift - small - overwrite
redshift - medium - overwrite
redshift - large - overwrite

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/15152
