### ISSUE TITLE
Databases and Data warehouses Benchmark: Output results into Metabase

### ISSUE THREAD

**Issue by noahkawasaki-airbyte** [airbytehq/airbyte#12351]
We'd like to somehow output the results of periodically running jobs into analytics. Maybe by adding Github Actions Jobs data into a stream into the BigQuery analytics location, or scraping the Airbyte API from the benchmark airbyte workspace

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/15152
