### ISSUE TITLE
Databases and Data warehouses Benchmark: Create all database sources in workspace with benchmark datasets

### ISSUE THREAD

**Issue by noahkawasaki-airbyte** [airbytehq/airbyte#12352]
Create Airbyte sources for all desired database sources with the chosen benchmark datasets loaded.

Entails:
1) Have database created in cloud somewhere
2) Load benchmark datasets in databases
3) Create source in Airbyte workspace

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/15152
