### ISSUE TITLE
Add temporal activities to fetch the reset to perform and update the reset persistence

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#12362]
We have added a persistence layer in order to store the running reset operation and the pending reset operation

## What

We need to create the following temporal activities:
- get list of streams for a given connectionId
- remove list of streams for a given connectionId
- add list of streams for a given connectionId

**Comment by benmoriceau** [comment]
https://whimsical.com/temporal-reset-run-LT67pvM2VH5Q8TFD5PLjh2

**Comment by alovew** [comment]
@benmoriceau I updated this ticket with the new specs - let me know if this looks right to you
