### ISSUE TITLE
[EPIC] Database Initialization Refactor

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#12375]
## Tell us about the problem you're trying to solve

* The goal of this project is to prepare the existing database access logic to be easily adapted for use in a dependency injection framework.  For more information, view the [OSS Database Initialization Refactor tech spec](https://docs.google.com/document/d/1e194USkxBvR0_EqPB-Qf4R9expfFluYksauiEzVcFDQ/edit?usp=sharing)

## Dependencies
* https://github.com/airbytehq/airbyte/issues/12356

## Projects
* https://github.com/airbytehq/airbyte/issues/12377
* https://github.com/airbytehq/airbyte/issues/12378
* https://github.com/airbytehq/airbyte/issues/12379

**Comment by cgardens** [comment]
@jdpgrailsdev all of the issues in this epic are closed. should we close the epic or is there more here?

**Comment by jdpgrailsdev** [comment]
> @jdpgrailsdev all of the issues in this epic are closed. should we close the epic or is there more here?

@cgardens Yes!  I must have missed this.  Feel free to close it.
