### ISSUE TITLE
Research why deleted_at field is not getting updated for deleted records

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12407]
The goal is to understand what is causing https://github.com/airbytehq/airbyte/issues/8830. The expectation for this ticket is to create an exit criteria for [8830](https://github.com/airbytehq/airbyte/issues/8830)

**Comment by edgao** [comment]
exit criteria added in https://github.com/airbytehq/airbyte/issues/8830#issuecomment-1119924013
