### ISSUE TITLE
Source Facebook Marketing: Slice large streams

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12412]
## Tell us about the problem you're trying to solve
The FB marketing source fails to sync very large, which is preventing customers from syncing all of their data.

As a workaround for https://github.com/airbytehq/oncall/issues/176, TS is manually updating the start and end time to pull data in 2 months intervals.

## Describe the solution you’d like
The FB integration should overwrite the `stream_slices` method to automate the slicing process instead of having someone manually update the date ranges.

## Implementation steps
0. `FBMarketingIncrementalStream` already has a [start and end date](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py#L150-L151)
1. Implement function to slice the stream by chunking the date range ([example of a connector doing a similar slicing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-appsflyer/source_appsflyer/source.py#L145-L170))
2. Test the slicing. This might be a good opportunity to [improve the incremental tests](https://github.com/airbytehq/airbyte/issues/11459)

**Comment by sherifnada** [comment]
Scope of what thsi change should be: 
1. test with one day increments and see what happens to runtime. 
2. If the slowdown isn't massive then just ship that change
