### ISSUE TITLE
I would like to be able to set the connector version in the admin page before I use it.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1242]
## Tell us about the problem you're trying to solve
* In the admin page I want to set the version of a connector before I go through the configuration process. 
* The reason for this is that I want to use the new version of the connector because the configuration in the old version is incompatible with my credentials for the source. 
![Screen Shot 2020-12-07 at 2 33 20 PM](https://user-images.githubusercontent.com/9092207/101413496-3c6f2200-3899-11eb-8b23-71384f0d0991.png)

## Describe the solution you’d like
* I would like to be able to set the version of connectors I haven't used yet

**Comment by sherifnada** [comment]
bumping priority to medium because this prevents makes for a bad UX when picking up bugfixes for connectors not in use.
