### ISSUE TITLE
Fix DATs blind spot: connection check

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#12459]
https://github.com/airbytehq/airbyte/pull/9407 and https://github.com/airbytehq/airbyte/pull/9610 introduced a bug that destination-redshift's `check` operation always failed. Investigate why this did not fail our DATs, then fix DATs to catch that case.

The latest master-branch commit affected by those commits is https://github.com/airbytehq/airbyte/commit/6ef2f80eba24675e03a290e6acc368cf64e4c0e8; `git checkout` to that commit and see if the issue is reproducible.

**Comment by alexandr-shegeda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/12459?planning-poker) with ZenHub @DoNotPanicUA @sashaNeshcheret
