### ISSUE TITLE
Empty config objects inside oneOfs cannot be saved

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#12457]
When I create a destination-snowflake connector using the `AWS S3 Staging` mode, then refresh the page and try to switch to the `[Recommended] Internal Staging` option, the `Save changes and retest` button remains grayed out:
![Screen Shot 2022-04-28 at 3 07 25 PM](https://user-images.githubusercontent.com/5741425/165855685-fd53ce31-3dfb-4f2d-8ab4-71a2ce5b8efc.png)

The spec, for reference (this is on master): https://github.com/airbytehq/airbyte/blob/e3bcbc86ca223c5a85e5b313290ebdc2db3621cc/airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json#L145-L157

This seems to happen for any empty object inside a oneOf, e.g. I see the same behavior on a [branch](https://github.com/airbytehq/airbyte/pull/12452) where I've added another empty object: https://github.com/airbytehq/airbyte/blob/2e14eacdb5b00aa7386a243e968bc5000a355606/airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json#L258-L271

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
