### ISSUE TITLE
Import configuration throwing  "$.catalog: null"

### ISSUE THREAD

**Issue by lassebenni** [airbytehq/airbyte#12464]
## Environment
- **Airbyte version**: 0.36.5-alpha
- **OS Version / Instance**: Ubuntu 20.04, GCP e2-standard-4
- **Deployment**:  Docker
- **Source Connector and version**: S3 0.1.10
- **Destination Connector and version**: BigQuery 1.1.1
- **Severity**: Low 
- **Step where error happened**: Import Configuration

## Current Behavior
In the UI when clicking the "Export configuration" button, downloading the tar file, and then trying to upload said file using the "Import configuration" button, an error is thrown in the logs (No error in UI). The error seems to indicate missing $.catalog id, which I expect is the `id` in `ACTOR_CATALOG.yaml` file that is exported:
`Errors: $.catalog: null found, object expected ` . See logs for full error.

[

https://user-images.githubusercontent.com/7990862/165902426-5ff0e659-7ee1-42b5-bb66-e585ae98d566.mov

](url)
## Expected Behavior
Importing the exact same configuration you just exported.

## Logs

<details>
<summary>LOG</summary> 

```
{
  "status": "failed",
  "reason": "io.airbyte.validation.json.JsonValidationException: json schema validation failed when comparing the data to the json schema. \nErrors: $.catalog: null found, object expected \nSchema: \n{\n  \"$schema\" : \"http://json-schema.org/draft-07/schema#\",\n  \"$id\" : \"https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/AttemptFailureSummary.yaml\",\n  \"title\" : \"ActorCatalog\",\n  \"description\" : \"Catalog of an actor.\",\n  \"type\" : \"object\",\n  \"additionalProperties\" : false,\n  \"required\" : [ \"id\", \"catalog\", \"catalogHash\" ],\n  \"properties\" : {\n    \"id\" : {\n      \"type\" : \"string\",\n      \"format\" : \"uuid\"\n    },\n    \"catalog\" : {\n      \"type\" : \"object\",\n      \"existingJavaType\" : \"com.fasterxml.jackson.databind.JsonNode\"\n    },\n    \"catalogHash\" : {\n      \"type\" : \"string\"\n    }\n  }\n}"
}


```

</details>

## Steps to Reproduce
1. Go to "Settings" -> "Configuration" page in the UI.
2. Click "Export Configuration". Download tar file with configurations.
3. Click "Import Configuration". Upload same tar file again.

## Are you willing to submit a PR?
Sure, if I get some help what to look for.

**Comment by lassebenni** [comment]
Any help?

**Comment by jyates-om1** [comment]
I'm running into the same issue on 0.39.1-alpha, running on local with docker-compose

**Comment by marcosmarxm** [comment]
closing this because import configuration is a deprecated feature.
