### ISSUE TITLE
Custom Transformation: sync fails when `dbt_profile` name other than 'normalize'

### ISSUE THREAD

**Issue by abhilash-m96** [airbytehq/airbyte#12465]
## Environment
- **Airbyte version**:  0.36.3-alpha
- **OS Version / Instance**: Ubuntu 20
- **Deployment**: Docker
- **Source Connector and version**: MongoDB/0.1.13
- **Destination Connector and version**: Postgres/0.3.18
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
The custom DBT transformation fails whenever the profile name is something other than 'normalize' in profiles.yml .

## Expected Behavior
Airbyte should allow custom DBT transformation with any custom profile name

## Logs
<details>
<summary>LOG</summary> 

```
Failure msg: “Could not find profile named ‘normalize’ .”  
```

</details>

## Steps to Reproduce
1. In normalization select Raw Data JSON
2. Add a custom DBT transformation which contains profile name something other than 'normalize'
3. Start the sync to see the failure

## Are you willing to submit a PR?
Yes

cc: @alafanechere

**Comment by cgardens** [comment]
We aren't going to pick this up. We want to stay away from orchestrating dbt. We recommend using Airflow or Dagster to do this orchestration. [Docs](https://docs.dagster.io/integrations/airbyte).
