### ISSUE TITLE
Update the Java CDK to emit `AirbyteTraceMessage`

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#12471]
Full context in parent issue https://github.com/airbytehq/airbyte/issues/12322
Java connectors should emit `AirbyteTraceMessage` with error information when something goes wrong.

### Scope / acceptance criteria: 
- [x] Implement java utility for AirbyteTraceMessage
- [x] Implement a naive exception catch across java connectors so we can log the new AirbyteTraceMessage
  - [x] We should propagate any existing error information up as part of this AirbyteTraceMessage, i.e. this change shouldn’t regress error usefulness.
  - [x] To be forward compatible, check if we're catching an AirbyteTraceMessage and if so throw as is (don't naively catch)
- [x] Write necessary tests
- [x] Add docs to explain usage to developers
- [ ] Version bump and publish current GA java connectors
  - this will start populating filled-out FailureReasons to work with for reporting purposes e.g. for building incident management.

### Not in Scope:
- Adding specific AirbyteTraceMessage errors to individual connectors
- Adding specific AirbyteTraceMessage errors to base/abstract connectors (e.g. JDBC)
- Implementing related testing ([separate issue for that](https://github.com/airbytehq/airbyte/issues/12473)).

**Comment by Phlair** [comment]
Open Qs:
- Where do we do the naive catch?
  - IntegrationRunner looks like a good contender
  - Depending on the answer to this, it may become necessary to bump and publish connectors to actually implement the naive try/catch. Is that in scope?

**Comment by grishick** [comment]
@Phlair once you are done with this, could you please guide @mkhokh-33 to correctly use the new `AirbyteTraceMessage` in [this issue](https://github.com/airbytehq/airbyte/issues/11322)
