### ISSUE TITLE
Complete data is not pulled for Gitlab Source

### ISSUE THREAD

**Issue by pilayar76** [airbytehq/airbyte#12476]
I am trying to use Gitlab Source Connector and load PostgreSQL database. 

Start Date of the application to pull is given from 2001 but I see some 20% data only.

Is there any settings to be enabled to sync complete data?

**Comment by pilayar76** [comment]
Just found that pipelines, merge_requests are only loaded with latest 100 records. Is there a way to extract the complete set please?

**Comment by marcosmarxm** [comment]
Closing because lack of information of connector and platform version. @pilayar76 please test with latest version of Airbyte and open a new issue if the problem persit.

**Comment by eflorico** [comment]
I am also experiencing this issue and can provide more details. This is a breaking issue for us–I have tried recreating and resetting the Gitlab connection many times, but I cannot get it to work so far.

Versions: Airbyte 0.40.26, Gitlab Source 0.1.12. Self-hosting in Docker.

Gitlab source config:
- API URL: gitlab.com
- Start Date: 2019-01-01T00:00:00Z
- Groups: (name of our group)
- Projects: (empty)

Destination config: BigQuery using GCS staging

Connection config: Syncing the following streams:
- branches - full refresh/overwrite
- commits - incremental/deduped+history
- merge_requests - incremental/deduped+history
- pipelines - incremental/deduped+history
- projects - full refresh/overwrite
- users - full refresh/overwrite

I found the following problems:
- For each project, a maximum of 50 pipelines, merge requests, and commits are retrieved
- I do see >50 branches for some projects, so I think branches may be fetched correctly
- Lots of duplicates in the users stream (all fields have the same values except for the `_airbyte_*` fields). This is a less important problem for me though. In total, I find 617 rows for 12 distinct users.

The following errors appear in the logs:
```
2023-01-05 18:05:51 source > Got 403 error when accessing URL https://gitlab.com/api/v4/projects/%%private project id%%%/merge_requests?per_page=50&scope=all&updated_after=2019-01-01T00%3A00%3A00Z. Very likely the feature is disabled for this project and/or group. Please double check it, or report a bug otherwise.
[...]
2023-01-05 18:06:12 source > Got 403 error when accessing URL https://gitlab.com/api/v4/projects/%%private project id%%%/pipelines?per_page=50&updated_after=2019-01-01T00%3A00%3A00Z. Very likely the feature is disabled for this project and/or group. Please double check it, or report a bug otherwise.
```

I cannot find such an error message for the commits stream.

I am currently evaluating both Airbyte and Meltano. Meltano seems to fetch data from Gitlab mostly fine after fixing some configuration issues. Interestingly, Meltano has the same issue with duplicate users.
