### ISSUE TITLE
Source BingAds: expose hourly/daily/weekly/monthly reports in discovery by default instead of in the connector's configuration settings

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12489]
## Tell us about the problem you're trying to solve
the Bing Ads connector is capable of syncing report streams which are aggregated by either an hourly, daily, weekly, or monthly time interval. 

Today, the way that a user can replicate these streams is that they first must turn on the following toggles in the connector's configuration page: 
![Screen Shot 2022-04-29 at 7 38 01 PM](https://user-images.githubusercontent.com/6246757/166087229-221595ba-e04e-48be-a43c-19f85ad140ce.png)

then they must choose to replicate those streams from the schema selection page when setting up a connection. 

It doesn't make sense that the user needs to opt-in to showing these streams by toggling the buttons above, then again needs to opt-in on the catalog page. 

## Describe the solution you’d like
It would be better if we remove those four toggles and assume the user always wants to see these streams output from the `discover` command of the connector (it would be equivalent to having those flags always turned on to `true` in the current configuration).

**Comment by bazarnov** [comment]
@bleonard @misteryeo @sherifnada 
Why this in `Icebox`? i believe we can include this into GA release, WDYT?
