### ISSUE TITLE
Allow users to create new connection regardless of credit balance

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12483]
Followup to #11775 - Update the button logic to allow cloud users to create new connections even if the workspace ran out of credits. This wasn't possible before until #12717 was merged.

### Context

When creating a new connection, the button is sometimes greyed out and not clickable. It seems to be an issue when a source or destination has been set up. (example workspace: https://cloud.airbyte.io/workspaces/80c785cb-bdd9-4034-9414-8763eeff1188/connections)
![Screen Shot 2022-04-29 at 5 21 37 PM](https://user-images.githubusercontent.com/38087517/166070861-cd909653-0db3-4ae1-a316-0a989ea0a76a.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Rather than remove the button, I would prefer to leave the button greyed out, but give the user an explanation of why (eg. on hover show a message, like: "Adding new destinations requires a positive credit balance".

But it seems what is really happening here is that users are blocked from creating connections.  

It isn't intuitive to me as a user why I can create new sources or destinations, but not connections. In this workspace, I can create a new source or destination, but only from specific pages (/source or /destination). My preference here is to change what we allow our users to do, and allow for connections to be set up, but continue to disable / disallow new syncs from running until the credit balance is positive.

**Comment by terencecho** [comment]
@edmundito the work on the backend has been done #12717

**Comment by edmundito** [comment]
Blocking issue was resolved in #2418
