### ISSUE TITLE
🐛 Airtable source: remove base & tables from spec.json, and use the API to list available bases & tables, using bases as the namespaces for streams

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12491]
## Tell us about the problem you're trying to solve
Airtable bases are equivalent to database schemas. We should use them as such. 

## Describe the solution you’d like
1. Remove the base & tables parameters from spec.json (we'll need to figure out how to handle backwards compatibility here, this is a tricky one)
2. Instead, list the bases inside the connector (when running `discover`) by calling the endpoint `https://api.airtable.com/v0/meta/bases` (see [the docs](https://airtable.com/api/meta)) and set them as the namespace property of each available table (stream). 
3. Then list all tables in a base , those are the streams and the base is the namespace 
4. Return all this in discovery output

**Comment by bazarnov** [comment]
In order to resolve this, we would need to obtain the Client-Secret in addition to API_KEY, we already have.
More info by the following link:

**Comment by sherifnada** [comment]
@bazarnov agreed with your reasoning for the short term. Can you leave this issue open? I think we may be able to get an exception from air table and integrate using oauth. 

Cc @misteryeo

**Comment by patygold** [comment]
Hey! Do we have an estimation on this issue already?

I think this will actually solve one of my issues actually. 
Basically: 
In the discovery step of this Airtable Source, Airbyte gets the schema from the first record returned by Airtable. The problem is, Airtable doesn't return the field in the GET request if the field is empty, even though this field might have a value in another record. This leads to a lot of fields missing from the schema on Airbyte.
And my guess is that this can be solved, if we do the discovery step using the Metadata API

**Comment by bazarnov** [comment]
> Hi @patygold, yes we understand that the Metadata API would solve this issue but unfortunately, we haven't been able to get access from the Airtable team. If you have someone on the Airtable side you could put us in touch with who could possibly get us access, we'd love to move forward here!
> 
> 
> 
> cc: @YowanR 

All we need is the account that has the access to the Metadata API, to reproduce and implement the new dynamic schemas.

But, this will force existing users to obtain the same level of access to be able to use the connector afterwards. 

Or, optionally, we can try to make the change backwards capable

**Comment by misteryeo** [comment]
Thanks for trying @patygold - we'll continue to find ways around this!

cc: @YowanR

**Comment by patygold** [comment]
Hey all! This morning I've received this email from Airtable. Now I think this might help us. The link: https://airtable.com/developers/web/api/changelog?utm_ID=recebVmIxYe5ut93c&utm_source=lifecycle_team&utm_medium=email&utm_campaign=it_ss_api_auth_public_beta&utm_content=email_waitlist-users&utm_extra5=metadata-api-users#anchor-2022-11-15
 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/8875581/202123439-ccf0d39d-1673-4444-b938-7841e25564ec.png">

**Comment by YowanR** [comment]
This is exciting! Thanks for sharing, @patygold! We'll have the team look at this once we have the bandwidth
