### ISSUE TITLE
Add a "name" field to a connection

### ISSUE THREAD

**Issue by ramonvermeulen** [airbytehq/airbyte#12508]
## Tell us about the problem you're trying to solve
When making a connection, I want to be able to give a connection a name. For instance, I am having multiple connections with the same source to the same destination, but with different settings. It would be nice if I can give a connection a name, so it is in one eye blink clear in the connection overview page what kind of connections I have. 

## Describe the solution you’d like
When creating a new connection I would like to have a field `name` to give the connection a specific name, maybe this can be default to someting like `${source_name} - ${destination_name}` ?

## Describe the alternative you’ve considered or used
There is no alternative

## Additional context
- 

## Are you willing to submit a PR?
I might look into the code later on, and see if it is a lot of work to add this feature. If it is not, I might submit a PR.

**Comment by andyjih** [comment]
Thanks for opening this issue @ramonvermeulen ! It's like you read our minds. We have designs for this and will be implementing something like what you've described soon.

**Comment by ramonvermeulen** [comment]
@andyjih Cool! Looking forward seeing this in Airbyte :)
