### ISSUE TITLE
DAT: Add test case for new field(s) appearing in data

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#12509]
## Tell us about the problem you're trying to solve
Right now, most destinations can handle new fields coming from the source that weren't previously specified. Exactly how they handle this is currently unenforced (e.g. field doesn't appear in output, field in pre-normalized JSON). Some destinations may fail on this behaviour but it is currently unclear if any would.

See [this slack thread](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1651252450266759?thread_ts=1651241470.584669&cid=C02TL38U5L7) for more context.

## Describe the solution you’d like
We would like to enforce that a destination _at least_ doesn't fail if new field(s) arrive in the data at any point after initial schema discovery and sync.
We can do this by adding a test case for this to the DAT.

## Describe the alternative you’ve considered or used
Currently, there is no explicit contract for this behaviour so it is somewhat assumed but this isn't a safe assumption unless we're testing every destination to confirm.

An alternative would be to enforce a stricter contract, e.g. enforce that a destination propagates new field(s) to the output data or enforce that a destination ignores new field(s). This may become the right approach in time.

**Comment by yurii-bidiuk** [comment]
`testSyncNotFailsWithNewFields()` is passed for all destination except `destination-aws-datalake`. It fails on CI when we verify that number of written messages is the same as was intended. But on the local env this test is passed
