### ISSUE TITLE
Error in Database Intercom Contacts SCD

### ISSUE THREAD

**Issue by ayyoubmaulana** [airbytehq/airbyte#12506]
## Environment
- **Airbyte version**:  0.36.4-alpha
- **Deployment**: Local
- **Source Connector and version**: Intercom 0.1.17
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
Error when models contacts_scd.sql intercom

## Expected Behavior
Success when union all

## Logs
[logs-539.txt](https://github.com/airbytehq/airbyte/files/8600802/logs-539.txt)

**Comment by bazarnov** [comment]
@ayyoubmaulana 
I can see from issue description you're using not latest version of `Platform` as well as `Source Intercom`, could you try to update both? As far as Platform update will provide updated `normalization` functionality.

**Comment by marcosmarxm** [comment]
Close due inactivity. @ayyoubmaulana please try latest version and if the issue persit please open a new issue.
