### ISSUE TITLE
Better docs for standard tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1250]
## Tell us about the documentation you'd like us to add or update
Eugene gave feedback that the standard testing process is too opaque. It's not clear how they work or what needs changing when the tests fail. I agree with his assessment. We should add better documentation describing the standard tests. Specifically: 

* What is their purpose
* 1000-foot description of how they work
* Example of the tests they run

## Are there any related areas of documentation that currently exist? Could you point to them? 
https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/testing-connectors this is the closest thing we have it seems

**Comment by cgardens** [comment]
Agreed. Per our discussion additional things we should include:

* Specific instructions on what the catalog needs to be configured with in order to work for incremental source-defined and incremental user-defined.
* Explanation on where to read the tests that are being run.
