### ISSUE TITLE
Enable 'New Destination' page from existing Source

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12512]
We merged a change to the new source, destination, and connection pages (https://github.com/airbytehq/airbyte/issues/11775)

When creating a new destination from an existing source, the old page still exists. (example URL: https://cloud.airbyte.io/workspaces/00fc1fef-9b4c-415a-8e45-013a30b0cf8e/source/3d5f2cb0-5af1-4dee-a90e-ec1f9182474f)

![Screen Shot 2022-05-02 at 12 41 23 PM](https://user-images.githubusercontent.com/38087517/166288905-d65b50c3-d7a7-4cf3-9ed0-bb112c46ca34.png)

The CTA is also greyed out and not clickable. In order to move forward, we need a design from Nico that addresses both the creation of a new destination and selection of an existing destination.

![Screen Shot 2022-05-02 at 12 46 43 PM](https://user-images.githubusercontent.com/38087517/166289909-4d30c764-f5b6-42be-9b45-d3caf526d82c.png)

Asana task: https://app.asana.com/0/1202192547291129/1202213000052650

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This also needs to be done from the destination side as well: When a new source to an existing destination without sources.

Figma:
https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP?page-id=34219%3A195976&node-id=34219%3A198326&viewport=305%2C48%2C0.12&scaling=min-zoom&starting-point-node-id=34219%3A198326

**Comment by nataliekwong** [comment]
Closing as this is resolved!
