### ISSUE TITLE
Source MSSQL: fail when the databaseName has "-" character into the name

### ISSUE THREAD

**Issue by joaquin-orono** [airbytehq/airbyte#12517]
## Environment
- **Airbyte version**:  0.35.59-alpha
- **OS Version / Instance**:  Ubuntu 18.04 on GCP
- **Deployment**: Docker
- **Source Connector and version**: MSSQL 0.3.22
- **Severity**: Critical
- **Step where error happened**: I want to use MSSQL Connector with CDC and the name of the database contain the character "-" the connection fail with the message:
Incorrect syntax near '-'
After that error you can't save the connection so is impossible to continue
I tryed to reproduce the error and it appear where Airbyte execute this sentence:
USE My-Database; SELECT * FROM cdc.change_tables'

**Comment by marcosmarxm** [comment]
I added the issue to connector team backlog @joaquin-orono

**Comment by prateekmukhedkar** [comment]
@joaquin-orono can you upgrade to the latest version of the connector and see if this is still an issue? We have verified that "-" in database name works.

**Comment by xiaohansong** [comment]
Validated we can support dash `-` in DB name along with other characters in latest version 3.1.0. Closing this ticket, if problem persists feel free to open a new one!
