### ISSUE TITLE
Improve usability of setting up webhook notifications

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12518]
We provide the following helptext for a user to set up their notifications via webhook.

> Notification Settings
> Connection status Webhook URL
> Get notifications the way you want (for instance, on Slack, or other).

![Screen Shot 2022-05-02 at 1 34 43 PM](https://user-images.githubusercontent.com/38087517/166296329-dd2dcb96-8c01-4e7b-9ef6-da62dccf73c6.png)

For a user that is unfamiliar with webhooks (e.g. non-engineers), this can be a daunting task because it is not as simple as just turning on a feature with a click, despite the feature being very useful for those who don't want to monitor their.

Suggestions for improvement: 
- Create an article on how to create a webhook URL using Slack (Tagging @arimbr for blog / content idea). A creative use case I've seen implemented is to actually use IFTTT webhooks, to allow that to propagate to multiple services, including email clients. We can link to that article from within the application (for example, in a product tour)
- Hyperlink to the Slack article https://api.slack.com/messaging/webhooks (seems brittle as a solution given URL may change) in the tooltip or product tour
- Create a product tour explaining how to set up and enable the feature (should be a temporary fix)

@Amruta-Ranade  do you have thoughts on how we can improve the usability of the feature?

**Comment by Amruta-Ranade** [comment]
+100 to creating a blog post detailing how to create a webhook + use cases

**Comment by Amruta-Ranade** [comment]
yep!

**Comment by Oluwasegungbogboota** [comment]
hey @arimbr, I tried reaching out to you but i got no response. This new open topic sounds exciting. @Amruta-Ranade, how do I get to work on it?

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
For reference, Nico's design is here: https://app.asana.com/0/1202192547291053/1202256499814919/f

**Comment by nataliekwong** [comment]
This was addressed in https://github.com/airbytehq/airbyte/pull/18159 
Closing this issue.
