### ISSUE TITLE
Update segment properties for source and destination to be consistent

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12527]
## Tell us about the problem you're trying to solve
Currently, when sending an analytics events, the properties are not consistent in the codebase:

1. Some sources use `connector_source_id` and others use `connector_source_definition_id`
2. Some destinations use `connector_destination` and others use `connector_destination_nefinition`

## Describe the solution you’d like
The goal is to match the analytics spec:

1. Sources should use `connector_source_definition_id`
2. Destinations should use `connector_destination`

## Describe the alternative you’ve considered or used
The alternative is to leave it as is and pick a consistent spec moving forward

## Additional context
Followup to #12526

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Related: #10954 Could invalidate this issue.

**Comment by timroes** [comment]
The events that used the unalligned naming have actually be changed as part of another analytics change, so this no longer is relevant.
