### ISSUE TITLE
Investigate the performance bottleneck of source database connectors

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#12532]
## Tell us about the problem you're trying to solve
- The source database connector syncs data end-to-end at the rate of 1-3K rows per second, or a few MB per second.
- It is way slower than just running the source connector alone.

## Describe the solution you’d like
- Investigate the amount of time spent on each part of the system.
- Figure out the potential max speed end-to-end.
- Locate the bottleneck and improve it.

## Describe the alternative you’ve considered or used
- A user from the community told us that [embulk](https://github.com/embulk/embulk) can be 3x faster ([thread](https://discuss.airbyte.io/t/mysql-source-connector-performance/1092/4)). We can also take a look at the source code and learn from them.

## Additional context
- Follow up of https://github.com/airbytehq/airbyte/issues/4314.

**Comment by acvelozo** [comment]
Hi, I don't know Java and am not fully aware of how the connector works, so I don't know if the following comment really makes sense. My apologies if it doesn't. After seeing the following code snippet from the **DefaultReplicationWorker.java** it seems that the connector reads one record at a time from the source:

![image](https://user-images.githubusercontent.com/16723411/166613412-4c361bbd-5401-41d8-819f-87f164eaac06.png)

I find it strange that data is read one record at a time. Wouldn't it be possible and faster to retrieve data by chunks? Initially I thought the fecthSize/batchSize parameter was referring to the size of each chunk. Not sure if it makes total sense, but maybe it can help.

**Comment by tuliren** [comment]
@acvelozo, thank you for looking into this.

The data is read in chunks from the database. The `fetchSize` is controlling the number of rows to read for each batch.

The code snippet above is processing the data in a later stage. Even though multiple rows of data can be retrieved from database at once, they still need to be handled one by one internally, at least according to our current design. It is possible that this process can be optimized, which will be the focus on this ticket.

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1693](https://airbyte7538.zendesk.com/agent/tickets/1693) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-07-23 at 01:44:*

<blockquote><div class="zd-comment" dir="auto">Hi @khungCU, it looks like fetch size is adjusted dynamically, ( <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/12400">https://github.com/airbytehq/airbyte/pull/12400</a> ) but this does not improve performance. I'm linking your post to an open issue regarding source connector performance:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/12532">https://github.com/airbytehq/airbyte/issues/12532</a><br></div></blockquote>

**Comment by inondavidw** [comment]
We lately integrated airbyte to our DC and we have the **same** issue, what is the status of this topic? can we help somehow?

**Comment by tuliren** [comment]
Relevant articles from Alex:
- https://www.elastic.co/blog/seven-tips-for-better-elasticsearch-benchmarks
- https://blog.cloudera.com/benchmarking-nifi-performance-and-scalability

**Comment by evantahler** [comment]
When we do performance measurements on this topic, we need to be sure to isolate the connectors from the platform, as it might be the platform itself that's introducing the slowdown. 

For example, @acvelozo was looking at the part of the platform that does message passing from the source to the destination - that part probably isn't slow, but getting all the messages prepared to do that logic might be.  We currently parse every JSON message we get to determine if it's a LOG, STATE, or RECORD message.  In some languages (*cough ruby*) JSON parsing is rather expensive.  I believe we are doing [full message parses](https://github.com/airbytehq/airbyte/blob/930cb309b5bee01c91dafbf318ca7f435b3ca2fe/airbyte-commons/src/main/java/io/airbyte/commons/json/Jsons.java#L80-L86), and on large RECORDS, could be rather slow, and lead to [memory leaks](https://github.com/airbytehq/oncall/issues/525).  An area of improvement might be to only partially parse the top-level node of all messages, and only fully parse STATE messages once we know the message's type (Jackson seems to support this).

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-28 at 20:15:*

<blockquote><div class="zd-comment" dir="auto">Hey, @khungCU! It looks like the GitHub issue has been resolved, could you update your Airbyte instance and check if the issue has been resolved?<br></div></blockquote>
