### ISSUE TITLE
CDK: Connectors can define a method to get error message

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#12537]
## Tell us about the problem you're trying to solve
After #12472, connectors using the CDK will generically emit `AirbyteTraceMessage`s when encountering unhandled exceptions. These `AirbyteTraceMessage`s contain a generic, uninformative `message` that is displayed to the user.

The goal is to give developers an easier way to provide a better user-friendly messages based on raised exceptions.

## Describe the solution you’d like
Provide an overridable `get_error_display_message` (name TBD) method at the `Source` or `Stream` level that is called when an exceptions occurs while reading. The method receives a param with the exception that was raised so that the developer can then return a user-friendly message if appropriate.

(rough example)
```python
def get_error_display_message(error):
    if issubclass(error, MyErrorType):
        return "The stream xyz is disabled for this acccount"
    return None
```

(optional)
We could then implement this in our own HTTPStreams to extract error messages from API responses when `raise_on_http_errors` is enabled, either directly or by exposing a new method where the developer can use the response itself to return the message 

(rough example)
```python
def parse_error_response(response):
    return response.json()["error"]["message"]
```

This approach can fit in nicely with connectors-as-config later down the line by allowing devs to specify the json path to the error message.

TODO:
- check some existing connector apis and see how the errors are returned 

## Describe the alternative you’ve considered or used
Connector developers can currently choose to emit `AirbyteTraceMessage`s themselves with a user-friendly `message`, but this means catching exceptions themselves and building up / being aware of `AirbyteTaceMessage`.

**Comment by bleonard** [comment]
random thoughts from using many api of structues to support:

```
 {
    error: "incorrect password"
 }
```

```
 {
    error: { message: "incorrect password" }
 }
```

```
 {
    error: { error: "incorrect password" }
 }
```

```
 {
    errors: [ "incorrect password", "bad username" ]
 }
```

```
 {
    errors: [ 
    	{ message: "incorrect password" }, 
    	{ message: "bad username" }
    ]
 }
```

```
 {
    errors: [ 
    	{ error: "incorrect password" }, 
    	{ error: "bad username" }
    ]
 }
```

```
{
  status: "error",
  message: " ",
  code: " "
}
```

```
{
    "error": "auth-0001",
    "message": "Incorrect username and password",
    "detail": "Ensure that the username and password included in the request are correct",
    "help": "https://example.com/help/error/auth-0001"
}
```
