### ISSUE TITLE
Update replication settings layout to match design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12551]
Followup to #10797

There's an update to the replication settings layout and the app should be reflected to match. You can see a screenshot between the current state and the desired state in the Figma:

https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP?node-id=33588%3A168733

1. Remove the setup connection header
2. Widen the gap between sections
3. Make "Activate streams you want to sync" a heading and add section separator above
4. Align dropdowns to the right

![image](https://user-images.githubusercontent.com/168664/166562394-e35b8c4f-3a38-4a19-aa6a-d5e0140547ca.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Todo: Confirm with Nico whether the fields should stay on the left or align right.
