### ISSUE TITLE
helm chart nil pointer evaluating interface {}.postgresql 

### ISSUE THREAD

**Issue by kssanthosh** [airbytehq/airbyte#12559]
## Environment
- **Airbyte version**:  0.36.7-alpha
- **OS Version / Instance**:  Ubuntu 18.04
- **Deployment**:  Kubernetes version  1.19.7 deploy with Helm
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 10.13.9) 
- **Severity**:  High 
- **Step where error happened**: Deploy

## Current Behavior
*Tell us what happens.*

## Expected Behavior
*Tell us what should happen.*

## Logs

<details>
<summary>LOG</summary> 

```
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: airbyte/templates/worker/deployment.yaml:60:23: executing "airbyte/templates/worker/deployment.yaml" at <include "airbyte.database.secret.name" .>: error calling include: template: airbyte/templates/_helpers.tpl:78:50: executing "airbyte.database.secret.name" at <.Subcharts.postgresql>: nil pointer evaluating interface {}.postgresql

Error: 1 chart(s) linted, 1 chart(s) failed

```

</details>

## Steps to Reproduce
1. on the version 0.36.7-alpha

2. ./ci.sh lint

**Comment by bilby91** [comment]
@kssanthosh The current airbyte helm chart needs helm >= 3.7 since it's using `.Subcharts` in order to reference a template from the `postgresql` subchart.

Change that introduces the feature => https://github.com/helm/helm/pull/9957

**Comment by evantahler** [comment]
Closing - this is a helm version issue, per @bilby91's comment
