### ISSUE TITLE
Fix wording on "New source" page

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12557]
## Current Behavior
The text on the page reads "Sources Sources are where..."
![Screen Shot 2022-05-04 at 12 50 22 AM](https://user-images.githubusercontent.com/38087517/166624639-2b70443f-ddd6-4449-a5e5-a231ae3430b7.png)

## Expected Behavior
The text should read "Sources are where..." 

It should look like the Figma here: https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP?page-id=26178%3A0&node-id=32933%3A156608&viewport=305%2C48%2C1&scaling=min-zoom&starting-point-node-id=32933%3A156608&show-proto-sidebar=1

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
