### ISSUE TITLE
Fix text overlay for sync modes in connection settings

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12574]
## Current Behavior
When a user reaches the connection settings (within the onboarding flow), and the sync mode is "Incremental | Deduped + History", the text of the sync mode does not fit in the width of the select box, causing text to run over itself.

Fullstory session: https://fsty.io/v/pXNCembg (using Chrome)

![Screen Shot 2022-05-04 at 12 45 55 PM](https://user-images.githubusercontent.com/38087517/166732257-86f1c3fa-12c9-458f-a65e-8d0596cc237a.png)

## Expected Behavior
The text should not run over itself.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
