### ISSUE TITLE
When a connector is being checked, the form should not be editable 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12575]
Page: `/workspaces/${workspace_id}/destination/${destination_id}/settings`

When a connector is being CHECKED, and the progress bar is displayed in the UI, the form-fields should no longer be editable.  As it stands now, if a change for the form is made mid-CHECK, it is not clear which values have been validated and persisted. 

<img width="925" alt="Screen Shot 2022-05-04 at 9 50 32 AM" src="https://user-images.githubusercontent.com/303226/166735576-a5e78365-d589-4bc1-9e47-30591ebe7c83.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
