### ISSUE TITLE
:bug: Destination Clickhouse : Normalization doesn't work in the acceptance tests.

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#12582]
## Current Behavior
The acceptance tests don't check any cases with normalization due to some problems with port sharing inside the container.
All tests with normalization are disabled. Also, we run DAT tests without normalization due to the false value in the `supportsNormalization` method.

![Screenshot from 2022-05-04 22-26-36](https://user-images.githubusercontent.com/30464745/166811009-735b75ac-6806-41b6-9f02-6b2278daf795.png)

## Expected Behavior
Run all test cases using normalization.

**Comment by etsybaev** [comment]
There are 2 ports to connect to clickhouse:
8123 - HTTP, which is used by JDBC driver, that’s used in clickhouse destination
9000 - TCP, which is used by DBT, that’s used in clickhouse normalization
The difficulty is that you can only specify one port in the config. 

So...in destination-clickhouse spec.json, we could have both port fields:
HTTP port, default 8123 for the clickhouse destination connector
TCP port, default 9000 for clickhouse normalization

**Comment by etsybaev** [comment]
There are 2 ports to connect to clickhouse:
8123 - HTTP, which is used by JDBC driver, that’s used in clickhouse destination
9000 - TCP, which is used by DBT, that’s used in clickhouse normalization
The difficulty is that you can only specify one port in the config. 

So...in destination-clickhouse spec.json, we could have both port fields:
HTTP port, default 8123 for the clickhouse destination connector
TCP port, default 9000 for clickhouse normalization.


Once this is done, also need to update the java test and python's normalization config for click house airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py -> transform_clickhouse method.
Also need to bump Normalization's version in NormalizationRunnerFactory -> NORMALIZATION_VERSION

(https://github.com/airbytehq/airbyte/pull/7620/files#r779428143)
