### ISSUE TITLE
The publish command no longer works for private docker repository

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#12584]
## Current Behavior
- In https://github.com/airbytehq/airbyte/pull/11654, a tag check was introduced to the publish command.
- However, the URL does not work for private connector like `destination-databricks.

## Expected Behavior
- The publish command should work for private connectors as well.

## Logs
https://github.com/airbytehq/airbyte/runs/6294841743?check_suite_focus=true
```
+ TAG_URL=https://hub.docker.com/v2/repositories/airbyte/destination-databricks/tags/0.1.5
++ curl --silent --output /dev/null --write-out '%***http_code***' https://hub.docker.com/v2/repositories/airbyte/destination-databricks/tags/0.1.5
+ DOCKERHUB_RESPONSE_CODE=404
+ [[ 404 == \4\0\4 ]]
+ echo 'Tag 0.1.5 was not registered on DockerHub for image airbyte/destination-databricks, please try to bump the version again.'
+ exit 1
Tag 0.1.5 was not registered on DockerHub for image airbyte/destination-databricks, please try to bump the version again.
Error: Process completed with exit code 1.
```

## Potential Solution
- Solution 1. Use a URL that works for private repositories as well.
- Solution 2. Add a `skip-tag-check` parameter to bypass the tag check.

**Comment by noahkawasaki-airbyte** [comment]
Hey @tuliren I'm looking into this and it seems to work for Databricks now, was databricks moved to public repo that you know of?

**Comment by noahkawasaki-airbyte** [comment]
Nvm I see its public now, ill do some testing

**Comment by tuliren** [comment]
Yes, Databricks is public now. So this is no longer a problem for Databricks. But still appreciate your patch for other private repos.
