### ISSUE TITLE
MSSQL CDC feature to capture only changes from now

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#12592]
## Tell us about the problem you're trying to solve
  We have many big tables and wants to implement CDC (SCD2) but, do not want to take snapshot  and only capture the changes from the time airbyte start. 

## Describe the solution you’d like
1. Have a option to disable initial snapshot whilst setting up connections 

## Describe the alternative you’ve considered or used
   Create a CDC table on mssql server and capture changes using incremental append however, it requires 2 columns for cursor (lsn and seq)
  Write a customer program to implement incremental append however, lot of coding, managing  bookmark/meta is difficult. 

## Are you willing to submit a PR?
    Yes if possible.  I am trying to implement option to select initial or not as debisum connector support "schema_only" option which reads only CDC and read_committed option however, I am facing some issue but, I will dig further 

https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-property-snapshot-mode

**Comment by sivankumar86** [comment]
I have created pull request . Please review and provide feedback 

https://github.com/airbytehq/airbyte/pull/12759

**Comment by tuliren** [comment]
Closed in https://github.com/airbytehq/airbyte/pull/12759 and https://github.com/airbytehq/airbyte/pull/13168.
