### ISSUE TITLE
RFC: Standard Source Tests V2

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1260]
@sherifnada and I brainstormed on what the next generation of our standard tests should look like. This was inspired to some issues that managed to slip through our current tests. These issues were specific to certain types of incremental and were hard to catch because the tests struggle to be specific enough to these types of incremental because of the existing interface.

## Tell us about the problem you're trying to solve
1. As we roll out new features that are supported by _some_ source, we want to be able to have standard tests that check them when relevant.
    * This often requires the user providing a little more information in order for the test to run in a comprehensive way.
1. We want the developer to have to have to do as little as possible in order for tests to run on their integrations
1. We want the DX for interacting with these tests to be intuitive and transparent.

The issue right now is that the first desire seems to be in conflict with the second one. As we need more specialized testing, we need more information which increases friction. For now we have some hacks to make this sort of work, but it comes at the cost of tests doing some magic (which hurts 3).

## Describe the solution you’d like
* Maximize along the 3 axes above.

## Proposed Solution
* Provided category labels for each source. We choose which test run based off of that.
* initial categories: `supports_full_refresh`, `supports_incremental_source_defined`, `supports_incremental_user_defined`
* We would then have 4 test classes:
    * base - this is a test class that sanity checks all basic functionality. it is run for _all_ source. but it will be fairly limited in its scope. included tests: 
            1. get spec
            2. check connection
            3. discover
            4. sync once and at least one record must be returned
     * the other 3 tests classes would correspond to the the categories mentioned above.
* categories would be declared in the spec. 
     * implementation detail: when the templater runs it would populate the spec as if it supported all categories and then the user removes the ones that don't apply.
* open questions: this means the user might be implementing multiple test classes. is this too high of friction. we are trading off having to do multiple for each one being simpler.

## Timeline
* We do not think this needs to happen right now, but should be targeted for early in the new year (or shortly after the next big release). It will help us a lot give good guarantees that our connectors work.

**Comment by cgardens** [comment]
not a rush at all, but we would like feedback on this when you have time @michel-tricot, @ChristopheDuong, @jrhizor

**Comment by cgardens** [comment]
https://docs.google.com/document/d/1pFLR8eLP5VOj6vDtWe69KZL0aWWHEA6Vkbod6NYJon4/edit

**Comment by sherifnada** [comment]
RFC reviewed and finalized.
