### ISSUE TITLE
🐛 JDBC source connectors: integer are converted to float on destination

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12606]
## Environment

- **Source Connector and version**: All database JDBC connector

## Current Behavior
JDBC connectors are typing `integer` as `number` in the source catalog. `number` are casted to `float` / `decimal` type on destination.

## Expected Behavior
`integer` in source database schemas should be defined as `integer` in the catalog schema that is generated by the source connector and not `number`.

**Comment by grishick** [comment]
Possible approaches are:

- Encode integers as JSON schema type integer
- Keep integers encoded as JSON schema type "number" and add airbyte_type "integer"
- Encode integers as JSON schema type "string" and add airbyte_type "integer"

Let's chose the least destructive approach at this time.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/12606?planning-poker) with ZenHub @subodh1810 @edgao @tuliren @grishick

**Comment by tuliren** [comment]
Notes:
- Approach 1 is not desireable, because we can run into serialization / deserialization issue by using JSON integer.
- Approach 3 is probably a better long term solution. But it will require us to change every destination first and then every source.
- Approach 2 is a good compromise between the two.

**Comment by sashaNeshcheret** [comment]
Based on [discussion](https://github.com/airbytehq/airbyte/issues/11627#issuecomment-1133170416) we need to extend support for long (big_integer) and float types as well on source side.

**Comment by edgao** [comment]
@tuliren it looks like destinations _already_ support `"type": "integer"` (e.g.: [avro](https://github.com/airbytehq/airbyte/blob/4313a22ca44654535e18f48d57bfceee5f4bebd5/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonSchemaType.java#L19), [normalization](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py#L515-L518)). So modifying sources to generate correctly-typed catalogs would be sufficient to get this (and https://github.com/airbytehq/airbyte/issues/12057) to work - your thoughts?

We'd still need something better for the decimal/numeric type (i.e. user-specified precision) but I didn't see any issues for those types.
