### ISSUE TITLE
Investigate root cause of JSONSchema validation errors (oAuth?)

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12616]
We currently show a debug log message saying that their JSON Schema Validation failed:

https://github.com/airbytehq/airbyte/blob/b9d8f760e3cc421b2195ea837aebf4eccb2bf845/airbyte-json-validation/src/main/java/io/airbyte/validation/json/JsonSchemaValidator.java#L56

```
2022-05-04 15:43:32 e[32mINFOe[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.client_id: is missing but it is required, $.client_secret: is missing but it is required, $.auth_type: must be a constant value OAuth
```

This message is confusing to users because if a sync fails, they think this validation error is the cause of the failure.

We could remove the message, but we should also figure out why this validation is failing in the first place.

**Comment by sherifnada** [comment]
same issue as #11272

**Comment by andyjih** [comment]
Hi @sherifnada! We chatted about this issue in our platform chat, and based on the validation errors, we _think_ it might be related to how we handle OAuth, since the errors are about client secrets and client IDs. Can you investigate if perhaps some OAuth-related connectors are triggering these errors? cc @evantahler

**Comment by andyjagoe** [comment]
I see a similar issue and wonder if it's related? I do a successful sync from my source to postgres and receive the following for every record:

```
2022-05-16 21:52:40 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: integer found, object expected
2022-05-16 21:52:40 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: 1652470370010
2022-05-16 21:52:40 source > {
2022-05-16 21:52:40 source >   did: 'did:key:zQ3shp4NdGw9GvSLrCw9LRLC5nCVpXtp5Jc9UETVauUvTYGKf',
2022-05-16 21:52:40 source >   meta: {
2022-05-16 21:52:40 source >     ts: 1652470370010,
2022-05-16 21:52:40 source >     rid: '90a782fa-c40b-417d-ace5-e58133b6a836',
2022-05-16 21:52:40 source >     hasCallback: true
2022-05-16 21:52:40 source >   },
2022-05-16 21:52:40 source >   type: 'track',
2022-05-16 21:52:40 source >   event: 'trackThing',
2022-05-16 21:52:40 source >   userId: 'userID',
2022-05-16 21:52:40 source >   options: {},
2022-05-16 21:52:40 source >   properties: {},
2022-05-16 21:52:40 source >   updated_at: 1652470370010,
2022-05-16 21:52:40 source >   anonymousId: '7662c59a-999e-416e-951b-c07805c563d8',
2022-05-16 21:52:40 source >   id: 'kjzl6cwe1jw147bnwsjov2yztlw2ss7031zsxpv8yvo1ffkak93ju4b94p0rwjl'
2022-05-16 21:52:40 source > }
```

Despite the error message, all data appears to be loaded correctly into Postgres. Is something not configured correctly or is there a problem with my data/schema?

My schema is below:

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Event",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "did": {
        "type": "string"
      },
      "updated_at": {
        "type": "integer"
      },
      "anonymousId": {
        "type": "string",
        "title": "anonymousId"
      },
      "event": {
        "type": "string",
        "title": "event"
      },
      "meta": {
        "type": "object",
        "title": "meta",
        "properties": {
          "ts": {
            "type": "integer"
          },
          "rid": {
            "type": "string"
          }
        }  
      },
      "options": {
          "type": "object",
          "title": "options"
        },
      "properties": {
          "type": "object",
          "title": "properties",
          "properties": {
            "url": {
              "type": "string"
            },
            "hash": {
              "type": "string"
            },
            "path": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            },
            "search": {
              "type": "string"
            },
            "referrer": {
              "type": "string"
            }
          }  
      },
      "traits": {
        "type": "object",
        "title": "traits",
        "properties": {
          "email": {
            "type": "string"
          }
        }
      },  
      "type": {
          "type": "string",
          "title": "type"
        },
      "userId": {
          "type": [ "string", "null" ],
          "title": "userId"
      }    
    }
}
```

**Comment by sherifnada** [comment]
@andyjih can you say more about what you mean by "how we handle oauth"? looking at this error with fresh eyes, my train of thought is: this happens in java code, so unless the spec specified by the connector is invalid, I would guess that the error is either in server or frontend code

**Comment by andyjih** [comment]
@evantahler I'm pretty sure we made this issue before @alovew's changes were merged.

The reason we flagged this as a potential Connector issue is because the error itself says the following, which looks oauth-related. Am I misunderstanding this here?

`$.client_id: is missing but it is required, $.client_secret: is missing but it is required, $.auth_type: must be a constant value OAuth`

**Comment by alovew** [comment]
@evantahler this is unrelated to the record schema validation. It's from different use of the json schema validator, but I'm not sure of the root cause.

**Comment by evantahler** [comment]
Ok then - back in the DX backlog for investigation!

**Comment by sherifnada** [comment]
@alovew @andyjih can you share the connection this happened in so we can reproduce? or if you already have repro instructions that would be super

**Comment by andyjih** [comment]
@sherifnada from @marcosmarxm "you can use e2e-source and 2e2-destination both throws the message"
