### ISSUE TITLE
Filter build report slack message only to beta/GA connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#12618]
## Tell us about the problem you're trying to solve
We post a slack message to the slack channel #connector-health every day indicating the build status of connectors. Many of these are red. But this is tolerable for now as they are alpha connectors. We want to start with a green base (GA/Beta) then gradually address any build failures as we certify connectors. 

## Describe the solution you’d like
Filter that list to only choose GA/beta connectors. Once #12599 is merged this should be trivial.

**Comment by evantahler** [comment]
closed by https://github.com/airbytehq/airbyte/pull/12684
