### ISSUE TITLE
[EPIC] Update documentation side panel design and behavior

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#12623]
The goal of this Epic is to apply design and functional changes to the side panel in onboarding, sources and destination.

Figma:
https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?node-id=33609%3A177017

- #10644 
- #12731

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
I believe your second bullet is referring to this issue #11434

**Comment by tealjulia** [comment]
https://github.com/airbytehq/airbyte/issues/12731 Side panel open by default
