### ISSUE TITLE
Make it more obvious if users attempt to configure a connection with duplicate stream names in the same namespace.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#12654]
## Tell us about the problem you're trying to solve
One configuration error case is having duplicate streams within the same namespace. An example of this is if a user has two tables with the same name in different schemas. e.g. an account table in schemaA and an account table in schemaB, and the user configures these two tables to go into the same schema.

This does not make sense and the job will error out. It would be better if we presented this at the configuration screen or perhaps as part of the api route.

We can also decide if this is something we want to support. The use case here would be combining tables. However this is complicated and thus not something I think we should do.

## Describe the solution you’d like
Make it obvious this configuration is not supported. We should also have documentation stating this.

**Comment by evantahler** [comment]
I believe with per-stream state we now more strongly enforce unique names/consider schemas/namespaces
