### ISSUE TITLE
Source Google Ads: enable incremental source acceptance test cases

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#12668]
Since Google Ads source 
 - has a limitation of age of the requested data (90 days)
 - performs a 14-days look back search during the sync
some SAT cases are not supported, therefore commented out.

The goal is to enable the test cases after https://github.com/airbytehq/airbyte/issues/12467 and https://github.com/airbytehq/airbyte/issues/12665 are implemented.

**Comment by pedroslopez** [comment]
Note: The 14-day look back part of this should be unblocked as of #12715

**Comment by davydov-d** [comment]
Since #12665 will not be implemented and there are custom integration tests covering same cases, here I just remove the commented test config

**Comment by davydov-d** [comment]
resolved in https://github.com/airbytehq/airbyte/pull/14191
