### ISSUE TITLE
Destination BigQuery: timestamps without timezone should be mapped to DATETIME

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#12660]
Due to new updates in the building of JSON schema, a new property `"airbyte_type"` was added to the field description. 
One of the possible values for `"airbyte_type"` is `"timestamp_without_timezone"`. Now `"airbyte_type"` is ignored and all `"timestamp_without_timezone"` fields with `"format":"date-time"` are mapped as `TIMESTAMP` in destination BigQuery. 

According to #11090 and this [comment](https://github.com/airbytehq/airbyte/issues/11090#issuecomment-1119113122) all fields with `"airbyte_type": "timestamp_without_timezone"` should be mapped as `DATETIME` in destination BigQuery. 

**Input JSON schema example:**
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "type_datetime_without_timezone": {
      "type": "string",
      "format": "date-time",
      "airbyte_type": "timestamp_without_timezone"
    },
    
  }
}
```
**Input data example:**
```
{
  "type_datetime_without_timezone": "2022-11-22T01:23:45"}
```

**Comment by yurii-bidiuk** [comment]
As datatype mapping for destiantion-bigquery should be done on the normalization side, I'm moving this ticket to the board of Phyton team 
cc: @alexandr-shegeda

**Comment by grishick** [comment]
@edgao does this issue depend (should it depend) on us implementing changes for handling data types using the new protocol version?

**Comment by edgao** [comment]
No dependency. Probably should _not_ happen in parallel with https://github.com/airbytehq/airbyte/issues/17647 to avoid merge conflicts, but they can happen in either order.

**Comment by etsybaev** [comment]
Seems to be already implemented as part of this PR 
https://github.com/airbytehq/airbyte/pull/13591/files#diff-d62e4a8a19e6547243431d0d09aea84f7653ab6fe1947236e0d822cac1334eeaR172

**Comment by grishick** [comment]
@etsybaev could you please run a test (manual test is fine in this case) to confirm that this is working as expected?
