### ISSUE TITLE
Source Google Analytics: enable incremental source acceptance test cases

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#12662]
Since GA source performs a 2-days look back search during the sync, incremental SAT case is not supported, therefore [commented out](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-analytics-v4/acceptance-test-config.yml#L23).
The goal is to enable the test case after #12467 is implemented.

**Comment by pedroslopez** [comment]
Hey @davydov-d , this should now be possible now that https://github.com/airbytehq/airbyte/pull/12715 has been released.

**Comment by davydov-d** [comment]
> Hey @davydov-d , this should now be possible now that #12715 has been released.

cc @sherifnada @misteryeo fyi, if you'd like to prioritize this issue - it is unblocked now
