### ISSUE TITLE
[Feature Request] Prevent running Sync if Source's connection is not valid

### ISSUE THREAD

**Issue by hbd** [airbytehq/airbyte#12686]
## Tell us about the problem you're trying to solve
A connection sync can run and provide ambiguous errors when their source is not longer valid. We have the ability to manually test a source, but it should be clear that a source is invalid _before_ running the sync, or at least an clear error should be provided.

## Describe the solution you’d like
I would like either:
1. Attempt to trigger a sync for a connection whose source's connection is no longer valid (e.g. `/check_connection` fails)
2. and/or a clear error log that describes that the source's connection is no longer valid

## Describe the alternative you’ve considered or used
N/A

## Are you willing to submit a PR?

Sure, provided some guidance on where to start

**Comment by sherifnada** [comment]
this is WIP here #12423

**Comment by hbd** [comment]
Wonderful, thank you. Will close and follow that issue.
