### ISSUE TITLE
Validate all documentation links in the webapp in CI

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#12694]
We currently store all links to documentation we present in the UI within one [file](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/config/uiConfig.ts). We should add a step to our CI, that validates if those links actually return a HTTP 200 status code, so we might be aware of broken links.

I'd suggest to run this step on our regular build on each PR (to prevent typos in URLs we add) as well as run this task separately on a schedule to be notified in case documentation change and existing links are breaking (and send some notification to the #dev-frontend channel for those).

Maybe as part of this task, we can also rename the file from `uiConfig.ts` into something more explicit like `docLinks.ts` to make clear this file should only contain links.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
