### ISSUE TITLE
Document how sync log data is generated for Airbyte Cloud

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#12692]
Reference: [Slack thread](https://airbytehq-team.slack.com/archives/C02UR8ZMV8R/p1651520175439699?thread_ts=1648854668.740049&cid=C02UR8ZMV8R)

**Comment by sophia-wiley** [comment]
Document available [here](https://docs.airbyte.com/cloud/managing-airbyte-cloud#view-the-sync-log-summary).
