### ISSUE TITLE
Octavia cli creates the same resource instead of updating it or not doing anything at all.

### ISSUE THREAD

**Issue by Imbruced** [airbytehq/airbyte#12690]
## Environment
- **Airbyte version**: any
- **OS Version / Instance**: macOS
- **Deployment**: docker-compose
- **Severity**: Medium
- **Step where error happened**: Update configuration

## Current Behavior
When updating connector using octavia cli it creates new one instead of updating existing one. It happens due to fact that only 3 fields are compared using octavia cli:
- sourceId
- destinationId
- connectionId

When you change namespaceDefinition to other than source it causes issue with updating the existing configuration using octavia cli.

## Expected Behavior
- When updating configuration with namespaceDefinition set to `destination` it should update the existing resource instead of creating new one.

## Logs
I dont think that logs are essential, I can show you in the code what actually breaks the octavia cli
In the resources.py file there is a search payload method

```python
  @property
    def search_payload(self) -> ConnectionSearch:
        """Defines the payload to search the remote connection. Search by connection name if no state found, otherwise search by connection id found in the state.
        Returns:
            ConnectionSearch: The ConnectionSearch model instance
        """
        if self.state is None:
            return ConnectionSearch(
                source_id=self.source_id, destination_id=self.destination_id, name=self.resource_name, status=self.status
            )
        else:
            return ConnectionSearch(
                connection_id=self.state.resource_id,
                source_id=self.source_id,
                destination_id=self.destination_id
            )
```

there are missing comparison fields used in /api/v1/connections/search endpoint. That stems from the fact that in api on java site there is line like 

```java
    return (connectionReadFromSearch == null || connectionReadFromSearch.equals(connectionRead)) &&
        matchSearch(connectionSearch.getSource(), sourceRead) &&
        matchSearch(connectionSearch.getDestination(), destinationRead);
```

so there should be added sth like this to search_payload method 
namespace_definition=NamespaceDefinitionType(self.configuration["namespaceDefinition"])
in connection constructor (and all other used to compare to)

## Steps to Reproduce
1. create connection using octavia cli
2. change field like namespaceDefinition in the configuration yaml
3. apply the configuration again

## Are you willing to submit a PR?
Definitely

**Comment by alafanechere** [comment]
@Imbruced I think I tackled this error with this recent PR https://github.com/airbytehq/airbyte/pull/12133 . I already created a related issue https://github.com/airbytehq/airbyte/issues/12270 .
Could you please re-install (/upgrade) octavia, this bug should not happen in `0.37.0`?

**Comment by Imbruced** [comment]
Yeah, I can see changes in the code on main branch. I am closing this one thanks, and sorry that I didnt see that.
