### ISSUE TITLE
Make <Button /> component consistent

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#12705]
## Tell us about the problem you're trying to solve
At this time we have two button components:
- `<Button />`
- `<LoadingButton />`

The second one is used only when we need to use a button and show some loading process.
The original button supports the 'isLoading' prop, but it does nothing
<img width="534" alt="image" src="https://user-images.githubusercontent.com/20929344/167463686-48dd5ed2-3e27-40b5-84d2-75c458f53086.png">

## Describe the solution you’d like
I suggest making the <Button /> consistent component, and if we need to show a spinner in the button, or combine it with another color(set 'danger' color) we just  need to pass an appropriate prop, like `<Button isLoading={condition} danger={anotherCondition} />`

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Fixed in #16604
