### ISSUE TITLE
Update the Create Connection endpoint to create a connection even if the credit balance is 0 or negative

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12717]
Related to https://github.com/airbytehq/airbyte/issues/12483

Context: Currently the front-end is preventing users who have zero or negative credits from creating a new connection, even though creating a new source or destination is still possible. 

The desired behavior is for folks to be able to create Sources, Destinations, and Connections, but the ability to turn on syncs or running a manual sync is enabled/disabled based on their credit balance.

**Comment by timroes** [comment]
@pmossman I am a bit confused about the credit status retrieval question and endpoint. As far as I can tell this is already part of the GET cloud-workspace API (https://github.com/airbytehq/airbyte-cloud/blob/master/cloud-api/src/main/openapi/config.yaml#L1067-L1076) and that's also where we're currently reading it from (https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/packages/cloud/cloudRoutes.tsx#L74) :thinking: So I am not entirely sure if I miss something here. Are we talking about a different status besides the one we already have?

**Comment by andyjih** [comment]
@pmossman Chatted with @timroes about this ticket: the current state is that the frontend is disabling the button based on the credit status, but the Create Connection endpoint also prevents the creation of a connection in the backend based on the credit status.

The requested change is that the endpoint allows the creation of a Connection in the disabled state if the credit status is zero or negative.

I'll update the title and description as well.

**Comment by pmossman** [comment]
While implementing, make sure that scheduled connections (ie every 24 hours) aren't able to start when the credit status is zero. Particularly if a connection is scheduled while the credit balance is > 0, but then becomes < 0 later on
