### ISSUE TITLE
Option to Auto-reload credits when they're running low

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#12719]
If a customer has their payment information already in stripe, we want to allow users to auto-reload credits when they're running low. The payment should be done with the invoicing API endpoint from: https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte/12718.

We also need to figure out where to save flag regarding if users want to auto-reload their credits (probably `cloud_workspace`  table.

Option1 for this process: have it be done on a cron to check at some interval, but that adds the possibility of users running out of credits before credits are re-loaded.

Option 2: do the check when we consume credits?

[Separate ticket](https://github.com/airbytehq/airbyte/issues/12747): send notifications to customers when their balance is auto-reloaded (Stripe might be able to do this for us, but we want it to be Airbyte-specific explaining the reasoning for the auto-reload charge). Probably don't need to send a warning email about credit balance being low if they are going to auto-reload

**Comment by pmossman** [comment]
Refining notes:
- Need to persist the user's choice whether they want auto-reload turned on or off
- Decide when to do the check/reload: (1) can make a cron that runs periodically. (2) check on every credit consumption if credits should be reloaded
    - (2) is preferable, doesn't leave credit gaps, can check it in real-time. billing cron is where we currently deduct credits based on sync jobs, so this is where we'd likely add the auto-reload logic

**Comment by nataliekwong** [comment]
Closing as we now offer this as of October 2023: https://docs.airbyte.com/cloud/managing-airbyte-cloud/manage-credits#automatic-reload-of-credits-beta
