### ISSUE TITLE
Intercom banner adjustments

### ISSUE THREAD

**Issue by Upmitt** [airbytehq/airbyte#12726]
3 little adjustments to do on Intercom banner:

1 - Octavia is cropped
2 - There is a big space between the text and the close
3 - Text color should be the Dark Blue #1A194D

<img width="1677" alt="Screenshot 2022-05-10 at 11 57 29" src="https://user-images.githubusercontent.com/29780098/167603114-01cb0f5e-4425-4c30-90d1-e320f1aea317.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Cc @nataliekwong since she's responsible for intercom. the FE team isn't related to those banners.

**Comment by nataliekwong** [comment]
@Upmitt  Thanks for calling these out!
1 - Octavia is cropped
Can you help send me the emoji of Octavia waving, but with a border? I believe the image I copied had no border, so when Intercom cropped the image into a circle, it cut off her head (eek!)

2 - There is a big space between the text and the close
What would you propose? Here is how it looks when I add a lot of spaces after the text. (this is the most to the right it can be) Note that in the rare case if the browser is squished to narrower than the banner it will move the text to the next row (with the additional spaces, it will show oddly indented on the second line)
<img width="755" alt="Screen Shot 2022-05-10 at 9 33 11 PM" src="https://user-images.githubusercontent.com/38087517/167751090-6e6fc153-3d94-461e-b509-67d7c980ec54.png">

3 - Text color should be the Dark Blue #1A194D
Intercom unfortunately does not allow you to change the text color. Here are the configuration options.
<img width="966" alt="Screen Shot 2022-05-10 at 9 34 12 PM" src="https://user-images.githubusercontent.com/38087517/167751143-5bd27874-a903-4c14-b7f1-2744930f653e.png">

**Comment by Upmitt** [comment]
![Octavia_hello_intercom_banner](https://user-images.githubusercontent.com/29780098/169473293-0ef94743-07d8-404d-909c-60fbc70e8602.png)
<img width="78" alt="Octavia_hello_intercom_banner@2x" src="https://user-images.githubusercontent.com/29780098/169473299-ca89e249-5f74-4353-a18e-d975a7d442f8.png">

**Comment by Upmitt** [comment]
Regarding the space between the text and the close, the idea was to remove/reduce it if possible :)
