### ISSUE TITLE
Boolean data type is missing from official docs

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12739]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

Airbyte documentation on data types (https://docs.airbyte.com/understanding-airbyte/supported-data-types/#the-types) does not list `boolean` as a supported type although the type is actually supported.

**Comment by ddoyediran** [comment]
@grishick Can I work on this since it is still open?

**Comment by grishick** [comment]
@ddoyediran yes, of course!

**Comment by ddoyediran** [comment]
Thank you @grishick. 

I have updated the document. 

Can you check it out? Let me know what you think (if there is anything you want me to add, remove or correct).
