### ISSUE TITLE
Endpoint to know what is the type of a connection

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#12736]
This ticket is about adding an endpoint to know what is the state type of a connection. There will be 3 possible types:
- legacy (the current deprecated state)
- Global
- per stream

In order to determine that, it needs to check the presence or absence of data in the state tables.
It work with exclusion:
- If no data is present in the global and per stream table, it is a legacy
- else is data is present in the global table, it is a global type
- else if data is present in the per stream table it is a per stream table.

For new connection (no state data will be present), we will default to the global state.

**Comment by cgardens** [comment]
done
