### ISSUE TITLE
Endpoint to submit a reset based on the new state message.

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#12742]
With the per stream state, we are now able to perform a reset for a single stream.

In order to be able to perform that we need a new endpoint to be able to submit such a reset. This ticket is about adding a new endpoint that will take a list of stream as well as a connection Id to submit a per stream reset.

Another endpoint need to be present to submit a global reset, it will just have a connection ID attached to it.

**Comment by lmossman** [comment]
- We could also do this in a single endpoint as long as there is something in the endpoint body indicating whether this is GLOBAL or PER_STREAM
