### ISSUE TITLE
airbyte-sever using high memory after updates v0.38.1-alpha

### ISSUE THREAD

**Issue by leoalmeidasant** [airbytehq/airbyte#12749]
## Environment
- **Airbyte version**:  example is 0.38.1-alpha
- **OS Version / Instance**: EKS
- **Deployment**: Kubernetes
- **Source Connector and version**: Postgres 0.4.14
- **Destination Connector and version**: S# 0.3.4
- **Severity**: High
- **Step where error happened**: Sync

## Current Behavior
After the update the airbyte-server pod is having memory spikes of up to 10GB.

## Expected Behavior
Expects not to use higher memory.

## Logs
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/17017833/167695965-e0926cc2-6f80-4171-880d-7ca32fd3261f.png">
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/17017833/167696039-7e992feb-b39c-49f2-bc71-a6d4a62f8c0c.png">

**Comment by leoalmeidasant** [comment]
I've notice that logs now are higher than before this version, and now are printing schema errar in multiline, event if connection refresh the schema, the sync continue logging mismatch schemas like this. 

```
Log4j2Appender says: Record schema validation failed. Errors: json schema validation failed when comparing the data to the json schema. 
Errors: $.balance_entity_id: null found, number expected 
Schema: 
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "number"
    },
    "type" : {
      "type" : "string"
    },
    "uuid" : {
      "type" : "string"
    },
    "is_test" : {
      "type" : "boolean"
    },
    "payout_type" : {
      "type" : "string"
    },
    "source_uuid" : {
      "type" : "string"
    },
    "created_date" : {
      "type" : "string"
    },
    "source_platform" : {
      "type" : "string"
    },
    "balance_entity_id" : {
      "type" : "number"
    },
    "last_external_version_instant" : {
      "type" : "string"
    }
  },
  "$schema" : "http://json-schema.org/draft-07/schema#"
}
```

Probably this is the cause which airbyte-server are using a lot of memory, every time when I click to see logs the server stops.

**Comment by marcosmarxm** [comment]
@leoalmeidasant I'm closing because this issue is about an old version of Airbyte. Please open a new issue if this persist in latest version.
