### ISSUE TITLE
Send email notification upon credit auto-reload.

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#12747]
Send notifications to customers when their balance is auto-reloaded (Stripe might be able to do this for us, but we want it to be Airbyte-specific explaining the reasoning for the auto-reload charge). Probably don't need to send a warning email about credit balance being low if they are going to auto-reload

This work will include framework to interact with customer.io using their app api key. This work exists in the open source repo, but not the cloud repo.

OSS example found [here.](https://github.com/airbytehq/airbyte/blob/e0aa76d35788bbf9ab22a4027cc38c7b2180a9f2/airbyte-notification/src/main/java/io/airbyte/notification/CustomeriolNotificationClient.java)
We probably want to just add that functionality in the already existing cloud handler [here.](https://github.com/airbytehq/airbyte-cloud/blob/7fb18d13e3d92f278bab66fa54b415aea6eb2cf2/cloud-partner-server/src/main/java/io/airbyte/cloud/partner/server/handlers/CustomerioHandler.java)

Dependent on https://github.com/airbytehq/airbyte/issues/12719.

**Comment by nataliekwong** [comment]
This is now done through Stripe invoices: https://docs.airbyte.com/cloud/managing-airbyte-cloud/manage-credits#automatic-reload-of-credits-beta
