### ISSUE TITLE
New reset upon update

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#12741]
If the update endpoint is being called on connection with a state type of STREAM or GLOBAL, we need to:

* Use the configured catalog to calculate the diff
* reset new/updated stream
* remove the removed stream from the state (no reset)
* Includes the catalog diff calculation

For LEGACY state types, none of the stream operations are possible. Thus we provide a slightly modified procedure.
* Use the configured catalog to calculate the diff
* Give the user the _option_ to reset all data for all streams
* Includes the catalog diff calculation

If there is no state present for this connection, don't perform any reset, as it unnecessary

**Comment by timroes** [comment]
Just to fill in some requirements from the UI side. I don't think we'd want to call a "reset stream" method from the frontend directly for streams that changed. Instead I'd expect the UI to keep calling the `web_backend/connections/update` API, which it does today every time the form is saved, and that API should be adjusted to figure out which streams have been changed and calling resetting them. Not sure though if there are other (non UI) places why we'd want to have this API, e.g. to have the connections/update API actually call it.

@benmoriceau do you want to track the adjustment to the `web_backend/connections/update` API as part of this issue, to make sure this API will trigger a reset for updated streams, or would you like me to create a separate issue for it?

cc @andyjih

**Comment by benmoriceau** [comment]
I think that we should keep this ticket. What about the reset button that is currently present in the.

@andyjih Will we allow manual reset on a specific list only.

**Comment by andyjih** [comment]
@benmoriceau I think the button to reset a connection on the connection page can reset all streams for now, and we can tackle resetting a single stream at a time in a future story if there's a compelling user case for it.

**Comment by benmoriceau** [comment]
If the update endpoint is being called and the state is a PER_STREAM state, we need to:
- Call schemaDiscovery to get the latest schema
- reset new/updated stream
- remove the removed stream from the state (no reset)

**Comment by cgardens** [comment]
@benmoriceau i updated the description to include the contents of the grooming notes. does this look accurate?

**Comment by andyjih** [comment]
https://github.com/airbytehq/airbyte/pull/14188
