### ISSUE TITLE
ImportError: Error loading shared library libstdc++.so.6

### ISSUE THREAD

**Issue by abhalawat** [airbytehq/airbyte#12760]
## Environment
- **Airbyte version**:  cloned from present master directory
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker environment

## Current Behavior
I was creating python source for an API under it when I build it on docker it happened successfully but after running the command

`docker run --rm <imagename>:3.3 spec`

It gave error as
 
`{"type": "LOG", "log": {"level": "FATAL", "message": "Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so)\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 9, in <module>\n    from source_twitter import SourceTwitter\n  File \"/airbyte/integration_code/source_twitter/__init__.py\", line 6, in <module>\n    from .source import SourceTwitter\n  File \"/airbyte/integration_code/source_twitter/source.py\", line 8, in <module>\n    from source_twitter.twint import twint\n  File \"/airbyte/integration_code/source_twitter/twint/twint/__init__.py\", line 14, in <module>\n    from . import run\n  File \"/airbyte/integration_code/source_twitter/twint/twint/run.py\", line 4, in <module>\n    from . import datelock, feed, get, output, verbose, storage\n  File \"/airbyte/integration_code/source_twitter/twint/twint/get.py\", line 17, in <module>\n    from .output import Tweets, Users\n  File \"/airbyte/integration_code/source_twitter/twint/twint/output.py\", line 6, in <module>\n    from .storage import db, elasticsearch, write, panda\n  File \"/airbyte/integration_code/source_twitter/twint/twint/storage/panda.py\", line 1, in <module>\n    import datetime, pandas as pd, warnings\n  File \"/usr/local/lib/python3.9/site-packages/pandas/__init__.py\", line 48, in <module>\n    from pandas.core.api import (\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/api.py\", line 48, in <module>\n    from pandas.core.groupby import (\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/groupby/__init__.py\", line 1, in <module>\n    from pandas.core.groupby.generic import (\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/groupby/generic.py\", line 70, in <module>\n    from pandas.core.frame import DataFrame\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/frame.py\", line 157, in <module>\n    from pandas.core.generic import NDFrame\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/generic.py\", line 152, in <module>\n    from pandas.core.window import (\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/window/__init__.py\", line 1, in <module>\n    from pandas.core.window.ewm import (  # noqa:F401\n  File \"/usr/local/lib/python3.9/site-packages/pandas/core/window/ewm.py\", line 12, in <module>\n    import pandas._libs.window.aggregations as window_aggregations\nImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.9/site-packages/pandas/_libs/window/aggregations.cpython-39-x86_64-linux-gnu.so)"}}`

The Docker File used was:

```
FROM python:3.9.11-alpine3.15 as base

# build and load all requirements
FROM base as builder
WORKDIR /airbyte/integration_code

# upgrade pip to the latest version
RUN apk --no-cache upgrade \
    && pip install --upgrade pip \
    && apk --no-cache add tzdata build-base \
    && apk --update --upgrade add gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev \
    && apk add --no-cache git \
    && apk add --no-cache libstdc++6


COPY setup.py ./


RUN pip install --prefix=/install .

# build a clean environment
FROM base
WORKDIR /airbyte/integration_code


# copy all loaded and built libraries to a pure basic image
COPY --from=builder /install /usr/local
# add default timezone settings
COPY --from=builder /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN echo "Etc/UTC" > /etc/timezone

# bash is installed for more convenient debugging.
RUN apk --no-cache add bash

# copy payload code only
COPY main.py ./
COPY source_twitter ./source_twitter

ENV AIRBYTE_ENTRYPOINT "python /airbyte/integration_code/main.py"
ENTRYPOINT ["python", "/airbyte/integration_code/main.py"]

LABEL io.airbyte.version=0.1.0
LABEL io.airbyte.name=airbyte/source-twitter
```

Could anyone guide me how to resolve this?

**Comment by marcosmarxm** [comment]
What happen if you force to pip install panda in the Dockerfile?

**Comment by abhalawat** [comment]
I solved that issue by changing docker environment. 

`FROM nickgryg/alpine-pandas:3.9.12 as base`

This solved the issue
