### ISSUE TITLE
Source TikTok Marketing: Missing Video Metrics

### ISSUE THREAD

**Issue by Zawar92** [airbytehq/airbyte#12762]
## Tell us about the problem you're trying to solve
We have implemented **[source-tiktok-marketing](https://github.com/Zawar92/airbyte/tree/zawar92/add_source_rki_covid/airbyte-integrations/connectors/source-tiktok-marketing)**. We got the data but **video metrics** are missing from it.

## Describe the solution you’d like
We would like to get the video metrics as they are very important for us. If you look at documentation **[Tiktok](https://ads.tiktok.com/marketing_api/docs?id=1701890951813121)**, they are available in supported metrics section. When data fetching is done video metrics are missing.

**Comment by marcosmarxm** [comment]
Closed by #13650
