### ISSUE TITLE
Some documentation links don't work

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#1277]
Some links to the docs from the airbyte ui don't work. For example the link to normalization:

"Whether or not to normalize the data in the destination. See basic normalization for more details." links to https://docs.airbyte.io/architecture/basic-normalization.md, but it should be https://docs.airbyte.io/architecture/basic-normalization

## Severity of the bug for you
Very low

**Comment by cgardens** [comment]
@awoehrl thanks for reporting this! just put a PR up to fix it.
