### ISSUE TITLE
Incremental postgres models normalization fails (string > 255)

### ISSUE THREAD

**Issue by shrodingers** [airbytehq/airbyte#12775]
## Environment
- **Airbyte version**:  0.35.66-alpha
- **OS Version / Instance**: EC2
- **Deployment**: docker
- **Source Connector and version**: Postgres 0.4.12
- **Destination Connector and version**: Postgres 0.3.13
- **Severity**: Low (but troublesome when it happens)
- **Step where error happened**: Normalisation step

## Current Behavior
if you refresh schema in incremental sync the new columns are synced with type character varying(256) instead of character varying (the one without limit)
This makes adding columns whose size exceeds 256 characters crashing normalization

## Expected Behavior
I think there should be no limit when adding columlns in incremental after schema change

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 
2022-05-11 10:36:44 [42mnormalization[0m > 10:36:41.001433 [info ] [MainThread]: 
2022-05-11 10:36:44 [42mnormalization[0m > 10:36:41.002727 [info ] [MainThread]: [31mCompleted with 1 error and 0 warnings:[0m
2022-05-11 10:36:44 [42mnormalization[0m > 10:36:41.004388 [info ] [MainThread]: 
2022-05-11 10:36:44 [42mnormalization[0m > 10:36:41.004757 [error] [MainThread]: [33mDatabase Error in model candidates_stg (models/generated/airbyte_incremental/airbyte_brigaders/candidates_stg.sql)[0m
2022-05-11 10:36:44 [42mnormalization[0m > 10:36:41.004984 [error] [MainThread]:   value too long for type character varying(256)
</details>

## Steps to Reproduce
1. setup a connection with a postgres destination (my case was for postgres w/ CDC to postgres)
2. sync a first time
3. add a new source column > 256 characters and inferred to string (ie : json / jsonb large blob)
4. refresh schema, save, wait for the reset and resync
5. normalisation will fail for the new column

## Are you willing to submit a PR?

I'm more than willing to, since i already made a fix for my usecase locally (rebuilt normalization image)
But i want a second opinion on the best way to do this  : 
Issue is caused by dbt implementation of column metadata retrieval and internal representation in DBT (they overrided the Column class for postgres to handle the text type without type limit, but not the varchar one).
The fix I made (to be able to fix directly the issue without depending on a DBT fix), was to override the postgres__get_columns_in_relation dbt adapter macro, to set the value to the max possible value for varchar columns when this value is NULL (the case when we use varchar with no size limits)
I think another possible fix is to override the postgres__type_string() for postgres to use TEXT instead of varchar
Or if needed, there is also the possibility to trigger a full_refresh when the destination table is empty, causing the tables to be rebuilt with the `CREATE TABLE name AS (SELECT ...)` syntax, and not relying on DBT type representation

In any ways, I can submit a PR with the fix deemed best, and i think i will also open a PR on DBT's repo because i'm not sure this behaviour is intended

**Comment by marcosmarxm** [comment]
Fixed by #12836
