### ISSUE TITLE
Make CDC debezium first record wait time configurable

### ISSUE THREAD

**Issue by ameyabhope** [airbytehq/airbyte#12776]
## Environment
- **Airbyte version**:  0.36.7-alpha
- **OS Version / Instance**: GCP n2.
- **Deployment**: GCP Compute Engine
- **Source Connector and version**: Postgres 
- **Destination Connector and version**: BigQuery 
- **Severity**: Medium
- **Step where error happened**:Sync job

## Current Behavior
*Tell us what happens.*
With logical replication, even when no new records are found the sync job takes greater than 5mins to complete. This seems to be the wait time set by [FIRST_RECORD_WAIT_TIME_MINUTES](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/internals/DebeziumRecordIterator.java#L37)
As a result, the sync job which should take less time when no new records are found, takes longer than when records are actually found.

## Expected Behavior
*Tell us what should happen.*
Sync job should take less time when no new records are found

## Logs
NA

</details>

## Steps to Reproduce
1. Configure replication with CDC 
2. Observe that Sync job takes greater than 5 mins when no new records are found 

## Are you willing to submit a PR?

Sure, but just need confirmation whether changing the wait time to something like ~1 min, doesn't have any other implications.

**Comment by grishick** [comment]
The real action item here is to update the docs to explain that 5 minutes is the minimum reasonable timeout for Debezium to wait for new WAL records from the source.

An additional action item that may answer the questions for those, who don't read the docs anyway is to make this value configurable in one minute increments from 1 to 10 minutes.

**Comment by ameyabhope** [comment]
Could you give more context around why 5 mins is the minimum reasonable timeout for Debezium?

**Comment by tuliren** [comment]
Extra benefit to make the timeout configurable: we can shorten the time to run integration test with CDC.

**Comment by tuliren** [comment]
> Could you give more context around why 5 mins is the minimum reasonable timeout for Debezium?

We are still investigating this.

**Comment by ameyabhope** [comment]
Just wanted to know if there is any update on this issue?

**Comment by ameyabhope** [comment]
Thanks @grishick for your response. Was curious to know if there's a timeline for the connection GA status?

**Comment by grishick** [comment]
> Thanks @grishick for your response. Was curious to know if there's a timeline for the connection GA status?

I cannot promise it, but we are trying to get it done in the next 3 months. However, this particular improvement is likely to be shipped sooner.

**Comment by grishick** [comment]
Another reason to reduce the timeout is that currently, integration tests spend 45 minutes out of 1hr execution waiting for Debezium timeout.
