### ISSUE TITLE
Update JDBC connectors to emit and handle per-stream state

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#12779]
We are changing the schema of of the AirbyteStateMessage in order to follow what is described in the [specs](https://docs.google.com/document/d/1zJVUQkVy8ZJUcqzM_hYPGijr4pI0Xx6I2eqpagJ2r7E/edit#). Once the platform work is tracked [here](https://github.com/airbytehq/airbyte/issues/12156) is done, we need to update the base classes for JDBC connectors to emit and consume per-stream state.

**Comment by grishick** [comment]
@cgardens how should I label this issue to put it on platform team's backlog?

**Comment by cgardens** [comment]
we are tracking it here: https://github.com/airbytehq/airbyte#workspaces/oss-platform-625a01eb010e82001390f49e/board
