### ISSUE TITLE
Add small margin to bottom of all Cloud pages

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#12780]
There is currently no margin at the bottom of the page:

![Screen Shot 2022-05-11 at 1 30 50 PM](https://user-images.githubusercontent.com/38087517/167911094-2a0cf33b-28cc-4a30-8d5a-3675f88b0256.png)

In order for the Intercom banner to render well alongside the rest of the components (and not overlap over the apply/save buttons), it would be helpful to have a margin added so that users don't have to "x" out of the banner in order to use the UI.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
