### ISSUE TITLE
The order of the sync history seems to be random

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#1278]
## Expected Behavior
The newest run should be added to either top or bottom of the sync history

## Current Behavior
Random order of the list

![grafik](https://user-images.githubusercontent.com/44875496/101777213-6ec78c00-3af2-11eb-9933-73552f2669e1.png)

**Comment by michel-tricot** [comment]
Thanks @awoehrl for the issue. Indeed that doesn't seem right. We've done a bunch of changes in that area in the past week. Might have remove a `sort` somewhere.
