### ISSUE TITLE
Help text for connector input should be more clear about accepting one or multiple values

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12792]
Consider the following help text we show when configuring a new connector.  

![image](https://user-images.githubusercontent.com/303226/167955010-9ca39724-c8ec-4844-b53d-7f394ce0e8ba.png)

This language implies we might accept a comma-separated list, but in reality, we only accept one Pokemon.  This input is built by the UI programatically from the [spec](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-pokeapi/source_pokeapi/spec.json) and [translated in en.json -> `form.examples`](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/locales/en.json#L94).

We should update this sentence to be more clear if we can only accept one value.  

Possible Suggestions:
* Quote each example and use "or" to delineate uniqueness 
> Pokemon requested from the API. (e.g. "ditto", "luxray", or "snorlax") Note: The value must match the pattern ^[a-z0-9_\-]+$"
* Use the phrase "one of" to delineate uniqueness 
> Pokemon requested from the API. (e.g. one of ditto, luxray, snorlax) Note: The value must match the pattern ^[a-z0-9_\-]+$"

Personally, I (@evantahler) like the first option

**Outstanding Questions:**
* Are there connectors which **can** accept a comma-separated list?  How can the UI know this?  Do we need an additional property in the spec clarifying this?

cc @sw-yx

**Comment by sw-yx** [comment]
note that its not just the language telling us to use comma saparated list, but also the _placeholder text_ inside the textbox itself, which is most definitely incorrect because it is invalid input...

**Comment by pedroslopez** [comment]
I think an issue here is that for the connector in question (pokeapi), the examples in the `spec.json` are specified as a single option:

https://github.com/airbytehq/airbyte/blob/62c3c4e93e7782478779965e571eb414b0380b6d/airbyte-integrations/connectors/source-pokeapi/source_pokeapi/spec.json#L15

See the stock ticker connector, which has the examples array correctly defined and only shows one as placeholder:

https://github.com/airbytehq/airbyte/blob/cf593a427e216eeff4a4b0523a6b7e2094d8b407/airbyte-integrations/connectors/source-stock-ticker-api-tutorial/spec.json#L13

![image.png](https://images.zenhubusercontent.com/62585178f8599f85447ea63f/e1e3b21c-e986-4555-8604-2796cc0cace5)

It might still be good to wrap each in quotes, but we should make sure that the examples are correctly defined on the connector specs.
