### ISSUE TITLE
Update python generators to use CDK version >= 0.1.55

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#12794]
Users were having issues generating a connector with yaml files due to not using a version of the CDK that supports `spec.yaml` (introduced in 0.1.55).

We should be explicit about this requirement in the `setup.py` to prevent this issue going forward.

**Comment by evantahler** [comment]
It's possible that folks using an older version of Python (3.8) would pick a previous version.  Bumping the requirement version would make things clear, and encourage a higher python version.
