### ISSUE TITLE
Streamline packaging for low-code connectors

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12799]
Testing low-code connectors is a little difficult right now because the docker image always pulls the CDK from the repository, which does not include the most recent changes.

Sample failed integration test run: https://github.com/airbytehq/airbyte/runs/6399119301?check_suite_focus=true

**Comment by evantahler** [comment]
Goal: This needs to somehow use your local version of the python CDK in the docker DEV images

**Comment by girarda** [comment]
closing because we can now test connectors with the local version of the CDK 🎉
