### ISSUE TITLE
Make source generator to update source_definitions.yml

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1280]
## Tell us about the problem you're trying to solve
Every new connector needs to be manually added to `source_definitions.yml` and `STANDARD_SOURCE_DEFINITION` folder.

## Describe the solution you’d like
Ideally, the code generator should do this automagically

## Describe the alternative you’ve considered or used
generate UUID4, create files, append lines, etc

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368201571070) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
If you only add it to the yaml, you can run `./gradlew generateSeed` to generate the JSON in `STANDARD_SOURCE_DEFINITION`

**Comment by ChristopheDuong** [comment]
@jrhizor 
Can this process of bumping versions (or creating a new entry) be handled in a command similar to the test-connector with github bot?
 
`tools/bin/ci_integration_workflow_launcher.sh`

In this PR #1331 (and thus #1363), I had to bump versions of all connectors, it could be nice if I did bump and publish command all (python)

**Comment by cgardens** [comment]
no longer relevant.
