### ISSUE TITLE
Google Firestore missing documentation

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#12808]
### Tell us about the documentation you'd like us to add or update.
The connector Google Firestore does not have a documentation page.

### If applicable, add links to the relevant docs that should be updated
- [Not an actual page yet](https://docs.airbyte.io/integrations/destinations/firestore)

**Comment by Amruta-Ranade** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/9727
