### ISSUE TITLE
Create base docker image for singer-based integrations

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1281]
## Tell us about the problem you're trying to solve
Currently, most singer-based integrations install GCC inside Dockerfile.

## Describe the solution you’d like
Until we get rid of this dependency I think it is smart to move this dependency in the base image for singer-base integrations.
This will significantly improve build speed.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368201571074) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Few thougths here:
- do all the singer need gcc? if not maybe we're adding gcc when it is not necessary
- If we add it to the base singer, do we need it on the "production" integration? Maybe we just need it to compile some python module but once they are compiled we can drop gcc. I wonder if we can exclude gcc, after we've installed the python deps, using the multi-stage docker build process.

**Comment by jrhizor** [comment]
Shaving off 30s off every Singer build would be nice, especially for two core Github Actions. It's hard to say exactly how it would impact overall build time, but that's likely a few minutes.

Our integrations with gcc already don't uninstall gcc or use a multi-stage process. Maybe if every singer integration deletes GCC after it's included in the base this is just a net improvement?

**Comment by cgardens** [comment]
Is this relevant to all python connectors or just the singer ones?

**Comment by sherifnada** [comment]
This would be relevant only to singer ones I believe

**Comment by sherifnada** [comment]
this was completed and deprecated shortly after 🤣
