### ISSUE TITLE
Connector Build Reports are no longer sent to Slack

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#12818]
After https://github.com/airbytehq/airbyte/pull/12684, the build report action has stopped sending slack messages.

Checking out a recent run (https://github.com/airbytehq/airbyte/runs/6406588128) it looks like there is information to send, but the step in the action `Slack Notification - Failure` is skipped due to missing/unset variable.

![Screen Shot 2022-05-12 at 11.05.37 AM.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/7a897d7c-db10-4a23-a2f6-532621a48861)

**Comment by sherifnada** [comment]
fixed in #12879
