### ISSUE TITLE
Remove scheduler migration logic on next major version bump

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#12823]
Some temporary logic was added to the airbyter ServerApp and the JobPersistence classes to support the migration from the old scheduler to the new temporal scheduler. See this PR for those changes: https://github.com/airbytehq/airbyte/pull/12757

Once we perform another "major" version bump that requires users to upgrade to some intermediate version that includes these changes, we can then remove this logic from the next version of Airbyte that comes after that.

**Acceptance Criteria:**
- The migration logic and persistence methods introduced in the PR linked above are removed from the Airbyte codebase after the next "major" version bump

**Comment by benmoriceau** [comment]
We could use this version bump in order to:
- to have a version that contains #12857 for sure.
- to remove the metadata code for the secrets that have been introduced in https://github.com/airbytehq/airbyte/pull/12516

**Comment by davinchia** [comment]
@benmoriceau @colesnodgrass if I'm poking around the job persistence class, do you mind if I grab this issue?

**Comment by benmoriceau** [comment]
@davinchia No, feel free to do it.
