### ISSUE TITLE
Add resource options to the Helm chart for bootloader and temporal pods

### ISSUE THREAD

**Issue by rcheatham-q** [airbytehq/airbyte#12825]
## Tell us about the problem you're trying to solve
The bootloader and temporal pods cannot have resource requests and limits set in the Helm chart.

## Describe the solution you’d like
Add options to the values file and associated changes in the templates to enable setting resource requests and limits for bootloader and temporal pods.

## Describe the alternative you’ve considered or used
There is no alternative for kubernetes clusters with resource quotas implemented.

## Additional context
This is probably only a big deal for admins trying to deploy Airbyte on kubernetes with resource quotas implemented.

## Are you willing to submit a PR?

Yes, I have the initial code changes ready, I'm just following the contributing guide [here](https://docs.airbyte.com/contributing-to-airbyte/#1-open-an-issue-or-find-a-similar-one). Note that I'm not sure how I could write tests for these changes, so please advise me on this 😄

**Comment by marcosmarxm** [comment]
Solved by #12828
