### ISSUE TITLE
User unable to delete a workspace

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12830]
Getting a 401 error when attempting to delete a workspace. No user feedback is shown as to why the deletion has failed. 

Loom: https://www.loom.com/share/6348f4e7b5604db2bc968ca16b3857d2

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte-cloud/issues/1475
