### ISSUE TITLE
DBT Custom transformation error in AirByte Open-Source deployed in EKS

### ISSUE THREAD

**Issue by daophat2496** [airbytehq/airbyte#12835]
I'm using Open-source AirByte (tag 0.36.2-alpha) deployed in EKS. The source is PostgreSQL, and the destination is Bigquery.
I've turned on Normalization, then add a custom DBT transform.

But it got stuck in the custom DBT transformation proccess.

I've checked the built-in DBT in AirByte is v1.0.0

Have you ever faced this case, or where should I find for more detail logs to figure out the issue. The log was just ended there with the "Retry" status for about a day until I cancelled it manually.

![image](https://user-images.githubusercontent.com/49853735/168228139-42250ee9-5903-4201-afaf-19a54a98ebf9.png)
Config Custom Transformation

![image](https://user-images.githubusercontent.com/49853735/168229055-31705e69-80e8-4bd4-b75f-3ec31fdc85a6.png)
This is where the logs end

![image](https://user-images.githubusercontent.com/49853735/168229349-8cee2642-1a95-4035-9d26-278dbe36d365.png)
This is model query in DBT project

Thank you very much

**Comment by marcosmarxm** [comment]
Custom transformation are not supported in Kubernetes deployment. Close as duplicated of https://github.com/airbytehq/airbyte/issues/5091
See more here: https://docs.airbyte.com/deploying-airbyte/on-kubernetes#known-issues
