### ISSUE TITLE
Need the hardware requirements section about local deployment

### ISSUE THREAD

**Issue by peter279k** [airbytehq/airbyte#12845]
### Tell us about the documentation you'd like us to add or update.

According to the [Airbyte local deployment](https://docs.airbyte.com/deploying-airbyte/local-deployment), it doesn't have the hardware requirements section.

I think it should need this and let users prepare proper host machine to build their Airbyte locally :thumbsup:.

### If applicable, add links to the relevant docs that should be updated
- [Airbyte local deployment](https://docs.airbyte.com/deploying-airbyte/local-deployment)

**Comment by marcosmarxm** [comment]
It will depends on how many connections and about your source data size. It isn't something we can give to you and you must explore based on your use case.
