### ISSUE TITLE
Report StandardSyncSummary outcomes at the end of the logs

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#12864]
## Tell us about the problem you're trying to solve
When going through the logs on large syncs, it's not unusual to scroll for a very long time through the log file to find which exceptions occurred first and investigate what happens during the sync, especially when it is marked as failed.

Adding to this scenario where a successful normalization step is ran after a failed replication step, it is not immediately obvious as to why the job is marked as FAILED whereas the last log lines from normalization seem to be all green and successful.

See [slack thread](https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1652467519304309):
> Is anyboyd else having issues where the normalization completes successfully, but the job itself is marked as failed?

it'd be nice to have a clear and concise summary printed at the end of the log file of what happened during the sync 

## Describe the solution you’d like

Similar to what dbt prints after running any commands, in this example, it is reporting an error on one model causing 28 models downstream from it to be skipped and 21 other models successfully updated:
```
09:06:26  Finished running 7 incremental models, 10 table models, 33 view models in 160.07s.
09:06:26  
09:06:26  Completed with 1 error and 0 warnings:
09:06:26  
09:06:26  Database Error in model fct_connector_active_sync_status_history (models/2-marts/product/incremental/fct_connector_active_sync_status_history.sql)
09:06:26    Could not cast literal "None" to type DATE at [3:136]
09:06:26  
09:06:26  Done. PASS=21 WARN=0 ERROR=1 SKIP=28 TOTAL=50
```

It'd be nice to "pretty" print the StandardSyncSummary and stats of what happens during the sync. 
Especially, formatting the `failureReasons` fields (with internal and external messages) that would make it easier to skim through what happened in the logs. If a user would need more details (such as the exact stacktraces, it would still be possible to scroll back to the actual exception in the logs)

These could also have links to the actual logs lines as described in https://github.com/airbytehq/airbyte/issues/12130

## Describe the alternative you’ve considered or used
Download the log files and scroll through it manually

## Additional context
See this question from TCS team: https://airbytehq-team.slack.com/archives/C02U2SSHP9S/p1652457474968539

**Comment by evantahler** [comment]
If we are going to add the ability for the worker to inject messages into the logs, I'd also like to add some lifecycle seperators:

```
----- starting checks
...
----- completed checks
----- starting sync
...
----- completed sync
----- starting normalization
...
----- completed normalization
----- summary:
...
```
