### ISSUE TITLE
Source Posthog: add ability to define `project_id`

### ISSUE THREAD

**Issue by andrewm4894** [airbytehq/airbyte#12874]
## Tell us about the problem you're trying to solve

We have multiple projects on app.posthog.com but i see that the connector does not let you define which `project_id` to pull from. 

## Describe the solution you’d like

In the PostHog api you now can [define the project id in the endpoint](https://posthog.com/docs/api/cohorts) like:

```
/api/projects/:project_id/cohorts/
```

So ideally when defining the PostHog collection i could add an optional `project_id` for cases where a user might have multiple PostHog projects and wants to make a connection for each one. 

## Are you willing to submit a PR?

Maybe :) 

Some of the endpoints returned in [here](https://github.com/airbytehq/airbyte/blob/657839195faf5d983a215d137b99b939bc3b465a/airbyte-integrations/connectors/source-posthog/source_posthog/streams.py#L146) would need to be able to have a `projects/:project_id` prefix added to them where `project_id` comes from the source definition. 

We are new to airbyte though so could be a bit of a learning curve for us. But also maybe a nice starter one too.

**Comment by andrewm4894** [comment]
no that does not work - would need to add the prefix in here maybe: https://github.com/airbytehq/airbyte/blob/657839195faf5d983a215d137b99b939bc3b465a/airbyte-integrations/connectors/source-posthog/source_posthog/streams.py#L22

**Comment by macobo** [comment]
Can confirm this from PostHog side: the URLs set in https://github.com/airbytehq/airbyte/blob/657839195faf5d983a215d137b99b939bc3b465a/airbyte-integrations/connectors/source-posthog/source_posthog/streams.py#L22 should include `/project/<project_id>` in the path.

As-is this integration only pulls data from the users currently active project, which will result in bad/invalid/missing data as users switch teams.
