### ISSUE TITLE
check connections in standard tests with invalid configs

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1288]
Standard tests should check that invalid configs are able to return a valid response object.

To do this, the test could create its own test object based on the input file (maybe with an invalid JSON config and a version that hashes the secret fields in the config?). Otherwise, this could be set up as part of the interface for python standard tests that are extended in the base implementation or every connector, specifying their own invalid config(s).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368201745136) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
done
