### ISSUE TITLE
Low-code connectors: Implement support for getting next page token from a URL's query param 

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#12889]
## What
Some connectors (eg greenhouse) extract the next_page_token by parsing a URL from the response and extracting query parameters from it.

## How
This can be done with a new type of paginator implementing this pseudo-code:
```
    def next_page_token(self, response: requests.Response) -> Optional[Mapping[str, Any]]:
        parsed_link = parse.urlparse(response.links.get("next", {}).get("url", ""))
        if parsed_link:
            query_params = dict(parse.parse_qsl(parsed_link.query))
            return query_params
        return None
```

The urllib methods to expose are
- urlparse: parses url into (path, params, query
- parse_qs: turn query string into dictionary

Flow:
1. decode response
2. get link from decoded response
3. parse_qs(urlparse(link).query)
4. select which qs to return

## Connectors that need this feature
- cart
- chargify
- delighted
- drift
- flexport
- freshservice
- greenhouse
- intercom
- okta
- outreach
- posthog
- twilio
- woocommerce
- zendesk-sunshine
- zendesk-talk

## Good connectors to use for QA
- cart
- delighted (people stream)
- flexport
- greenhouse
- intercom
- drift
- okta
- outreach
- posthog
- twilio
- woocommerce
- zendesk-sunshine
- zendesk-talk

## Connectors this unlocks (by itself)
1. greenhouse

**Comment by brianjlai** [comment]
As per the above, going to close this one out. I did a little extra reading on some of the API docs of the following see if they would be implementable using the existing paginators and they seem to be:
Cart
Flexport
Greenhouse
Intercom
Drift
Okta
Twilio
