### ISSUE TITLE
Source Google Search Console: exposed private key

### ISSUE THREAD

**Issue by ptiurin** [airbytehq/airbyte#12904]
I've stumbled upon the following file containing what looks to be a private key. Is it supposed to be exposed?

https://github.com/airbytehq/airbyte/blob/ec8c8c6438a0ccfd92dc97b3cdbf652d9373bd89/airbyte-integrations/connectors/source-google-search-console/config_1.json#L8

**Comment by sherifnada** [comment]
hi @ptiurin -- thank you for highlighting this. We'll rotate the keys asap.
