### ISSUE TITLE
Source Gitlab: wrong access to epic issues

### ISSUE THREAD

**Issue by gcoffin** [airbytehq/airbyte#12900]
## Environment
- **Airbyte version**:  0.38.3
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**: Gitlab
- **Destination Connector and version**: Postgres
- **Severity**: Medium
- **Step where error happened**: Sync job 

## Current Behavior
sync of epic issues fail - access to the url as coded raises error 403. That's because the url uses the id of the epic

## Expected Behavior
it should use the iid as specified in the Gitlab documentation https://docs.gitlab.com/ee/api/epic_issues.html

## Steps to Reproduce
1. pay Gitlab Premium Plan
2. setup a connection with Gitlab
3. sync up

## Are you willing to submit a PR?
yes

**Comment by davydov-d** [comment]
hey @igrankova @YowanR is it possible to get a Gitlab Premium Plan so we could reproduce this bug?

**Comment by igrankova** [comment]
@YowanR 
**[Premium](https://about.gitlab.com/pricing/)** $19 per user/month
Billed annually at $228 USD

**Comment by davydov-d** [comment]
> @YowanR **[Premium](https://about.gitlab.com/pricing/)** $19 per user/month Billed annually at $228 USD Reason is [here](https://docs.gitlab.com/ee/api/epic_issues.html)
> 
> cc @davydov-d

cc @misteryeo

**Comment by YowanR** [comment]
@davydov-d @igrankova let's go ahead and pay for it for the next month while we debug and get this connector out to our customers.
@gcoffin Thanks for submitting this bug. We usually partner up with service providers to speed up connector development. If you are already a Gitlab customer, could you be willing to help us connect with Gitlab by using you as a common customer? This usually speeds up the process significantly.

**Comment by igrankova** [comment]
@YowanR hi,
The subscription is yearly, there's no monthly option.
![image](https://user-images.githubusercontent.com/87977540/205856957-46818e75-fb8e-419a-b3e8-77b9843858f1.png)
cc @davydov-d

**Comment by YowanR** [comment]
I think this is a good investment given that it'll help us test both the connector itself but also single refresh token. Let's do it for the year and then re-assess next year. @igrankova

**Comment by igrankova** [comment]
@YowanR,
thanks for confirmation.
airbyte.io is currently using the Premium SaaS Plan (Formerly Silver)
cc @davydov-d
