### ISSUE TITLE
[QUESTION] - Why is Airbyte forcing a data reset when adding a new stream?

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#12918]
I have the following connection: Custom Connector Rest API (Source) -> Snowflake (Destination)

I have synced a couple of Streams:

* `stream_1`
* `stream_2`

both streams have synced over 30 millions rows into my destination (Snowflake).

I'm now updating my custom source connector to add a new endpoint; a new stream called `stream_3`

When configuring that new stream on Airbyte, it forces me to reset my whole destination and start syncing from scratch?
> Note that it will delete all the data in your destination and start syncing from scratch.

> WARNING! Updating the schema will delete all the data for this connection in your destination and start syncing from scratch.

**Why?** ☝️ **What's the logic behind this?**

I only want to sync new records for `stream_1` and `stream_2`, and sync `stream_3` from scratch.

**Comment by marcosmarxm** [comment]
What version of Airbyte are you using?

**Comment by marcosmarxm** [comment]
See discussion in issue: https://github.com/airbytehq/airbyte/issues/3520
I'll close the issue and you can ask more info in the issue itself.

**Comment by philippeboyd** [comment]
Thanks @marcosmarxm
