### ISSUE TITLE
Generic Metrics Implementation clean up.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#12910]
## Tell us about the problem you're trying to solve
Clean up tasks.

## Describe the solution you’d like
- [x] Add documentation showing what set of metrics are exposed and the recommended set users can use to alert on. Make this part of the [Scaling Airbyte doc](https://docs.airbyte.com/operator-guides/scaling-airbyte).
- [x] Find all issues related to open source metrics
- [x] Close all metrics related issues that can be reasonably closed. e.g. https://github.com/airbytehq/airbyte/issues/12338

**Comment by davinchia** [comment]
@xiaohansong I updated the first point here to make it clearer that we should bundle the OTEL work on generic metrics into the Scaling Airbyte docs. This is a great improvement for OSS users so we should make it clear!

fyi @Amruta-Ranade we should definitely announce this on the public slack since quite a few OSS users have asked for this.

Amruta, also curious on your thoughts on renaming the Scaling Airbyte section -> Productionising Airbyte to make it clear this is for power users.

fyi @jdpgrailsdev since we discussed this.

**Comment by Amruta-Ranade** [comment]
cc @sw-yx for changelogs

Happy to brainstorm renaming options! Can you help me understand why Scaling Airbyte no longer works and what we want to convey now? Want to maintain the simplicity and intuitiveness of "Scaling Airbyte" with the new title.

**Comment by davinchia** [comment]
Is Shawn in charge of changelogs now?

"Scaling Airbyte" sounds more focused on understanding Airbyte's scaling mechanisms. I feel "Productionising" covers running Airbyte in a production context, which includes scaling it up and metrics. Feels like a more encompassing scope.

**Comment by Amruta-Ranade** [comment]
Yep! Shawn's drafting changelogs now :)

As for renaming the section, how about "Run Airbyte in production"

**Comment by xiaohansong** [comment]
doc for review: https://docs.google.com/document/d/15UbG-psYLlmUBKbiTSnnlCcCuAYwqL7T3yyJxlpV88c/edit#heading=h.1qrkojibqv5a

**Comment by sw-yx** [comment]
i'm a bit unclear on the timeline. where is this work happening and when do we announce?

**Comment by davinchia** [comment]
@sw-yx work has completed. we can announce it whenever. maybe good idea to wait for the public facing docs to be done?

**Comment by sw-yx** [comment]
yeah sounds good - where do i follow along for public facing docs pls?

**Comment by xiaohansong** [comment]
@sw-yx  

@sophia-wiley has launched the doc:
https://docs.airbyte.com/operator-guides/scaling-airbyte/#recommended-metrics

**Comment by xiaohansong** [comment]
Didn't find any other tickets besides https://github.com/airbytehq/airbyte/issues/12338

I think we could close out the ticket. What's left in this topic is just an announcement for the feature.
