### ISSUE TITLE
Source Hubspot: invalid permissions for feedback_submissions

### ISSUE THREAD

**Issue by GouthamJM** [airbytehq/airbyte#12911]
### Destination - SQL DB - MySQL and PostGres

```
2022-05-17 11:58:30 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.client_id: is missing but it is required, $.client_secret: is missing but it is required, $.refresh_token: is missing but it is required, $.credentials_title: must be a constant value OAuth Credentials
2022-05-17 11:58:30 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.api_key: object found, string expected
```

I have attached the log for the same

[logs-53.txt](https://github.com/airbytehq/airbyte/files/8708027/logs-53.txt)

**Comment by Eddonofuture** [comment]
Had the same situation but rds - bq, and all the ETL are syncing but not working at all
<img width="2070" alt="image" src="https://user-images.githubusercontent.com/3847711/168856887-b13ee52e-9e93-40b1-9877-130f125f266a.png">
![image](https://user-images.githubusercontent.com/3847711/168856984-42cce928-85cb-420b-a790-ffad79e765c7.png)

![image](https://user-images.githubusercontent.com/3847711/168857029-e723b08d-3b95-4b02-bd24-62abe3d527d2.png)

[logs-33.txt](https://github.com/airbytehq/airbyte/files/8709830/logs-33.txt)

**Comment by grubberr** [comment]
Warning messages in the body of issue are generated from **JAVA**  JsonSchemaValidator
as for me java jsonschema validator not very correct:

schema:
```{
  "type": "SPEC",
  "spec": {
        "credentials": {
          "oneOf": [
            { 
              "required": ["client_id", "client_secret", "refresh_token", "credentials_title"],
              "properties": {
                "credentials_title": {
                "client_id": {
                "client_secret": {
                "refresh_token": {
```

config:
```
{
  "start_date": "2017-01-01T00:00:00Z",
  "credentials": {
    "api_key": "********",
    "credentials_title": "API Key Credentials"
  }
}
```

Validator tries to validate the config with schema and complains that this fields: `client_id`, `client_secret`, `refresh_token`, `credentials_title` are required.
But even this fields are required they are still can be missed because they are part of `oneOf` section !!!

**Comment by marcosmarxm** [comment]
Hello @GouthamJM and @Eddonofuture this is something team is working to solve. Hope to have updates soon.

**Comment by marcosmarxm** [comment]
First @GouthamJM the json schema validation team is working please upgrade your version to latest.

The issue in your log is related to Hubspot:
```
  File "/airbyte/integration_code/source_hubspot/streams.py", line 366, in read_records
    raise RuntimeError(f"Invalid permissions for {self.name}. Please ensure the all scopes are authorized for.")
```
looks your api key is missing permssions.

**Comment by marcosmarxm** [comment]
@Eddonofuture please open a specific issue for you problem and use the template given.

**Comment by evantahler** [comment]
As a note to the folks working on this issue - the error `Please ensure the all scopes are authorized for.` seems to also imply that the connector's CHECK command is not sufficiently checking all the permissions that are needed to run the sync.  The CHECK command should also be updated with a more robust check.

**Comment by grubberr** [comment]
@GouthamJM please update `source-hubspot` connector to the latest version `0.1.65`
and re-start sync. I think it will fail again, but new log messages will be much more informative. We will be able to understand what's scopes are missed.

Please also attach new logs for further investigation.
