### ISSUE TITLE
Standardize spec.json for DB connectors that support log-based CDC replication

### ISSUE THREAD

**Issue by ThaliaBarrera** [airbytehq/airbyte#12917]
In the analytics team we are looking for a way to track CDC vs. non-CDC source statistics. For more information, refer to [this issue](https://github.com/airbytehq/airbyte-warehouse/issues/50).

When trying to expose the fields in the warehouse, we realized there's a mismatch in spec.json files between [Postgres](https://github.com/airbytehq/airbyte/blob/09d1c06cff2c5b385eef597d664a8a49db73200f/airbyte-integrations/connectors/source-postgres/src/main/resources/spec.json) and [MySQL](https://github.com/airbytehq/airbyte/blob/09d1c06cff2c5b385eef597d664a8a49db73200f/airbyte-integrations/connectors/source-mysql/src/main/resources/spec.json), for example. The difference in specs makes it difficult to track the fields, so we would like to standardize them.

![image](https://user-images.githubusercontent.com/7718175/168832567-fa9814c6-9d35-4d47-93f7-e76a8757c258.png)

The spec.json of connectors such as MySql should use a `oneOf` called "replication_method" where the method can be selected via a const value of `CDC` instead (follow postgres connector)

**Comment by VitaliiMaltsev** [comment]
To avoid backward compatibility issue should be merged after https://github.com/airbytehq/airbyte/issues/14196

**Comment by VitaliiMaltsev** [comment]
https://github.com/airbytehq/airbyte/pull/14574 was merged. Please proceed
