### ISSUE TITLE
[EPIC] Source Amazon S3 to GA

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#12928]

**Comment by misteryeo** [comment]
@lazebnyi reviewed checklist - LGTM but left a few comments/clarifications highlighted.

**Comment by lazebnyi** [comment]
Successfully certified to GA - https://docs.google.com/spreadsheets/d/1HfNv5iFHUpoLOd31jgVXUlJAPQpWDb5aY9ctHYhhU4U/edit#gid=1700962388
