### ISSUE TITLE
Http connector data object

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#1295]
## Expected Behavior
I would like to select the nested objects of a json api. 

![grafik](https://user-images.githubusercontent.com/44875496/101908828-f2e64600-3bbc-11eb-895c-6e6fdfd63af4.png)

## Current Behavior
There is only a top level data object.

Low

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368078037994) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@awoehrl - thanks for the feedback. i agree, we would like to be able to see the full structure of the object. we plan to do this, but we haven't gotten to it yet.

**Comment by sherifnada** [comment]
HTTP connector has been deprecated
