### ISSUE TITLE
Freshdesk source error - `start date` is malformed 

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#12957]
## Environment
- **Airbyte version**:  0.38.4-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: kubernetes
- **Source Connector and version**: Freshdesk
- **Destination Connector and version**: (na
- **Severity**: Critical
- **Step where error happened**: Setup new connection

## Current Behavior
When trying to  set up Freshdesk as a source, I am getting an error that the start date does not conform to the pattern, but it seems to me like it does.
Same error if I leave it empty.
![Screenshot 2022-05-18 at 16 01 31](https://user-images.githubusercontent.com/91880749/169060201-6c1f2fb5-23e3-4d8c-9189-bb6e2a01a054.png)

## Expected Behavior
Should be able to set up the connection

## Logs
na

## Steps to Reproduce
1. New source
2. Freshdesk
3. Fill in details

## Are you willing to submit a PR?
Probably not, not my area of expertise, sorry ;(.

**Comment by marcosmarxm** [comment]
Hello @jan-benisek I was able to create a connector using our credentials and use the datetime
![image](https://user-images.githubusercontent.com/5154322/171054397-4cc7d67a-012e-404c-b7c1-0844942d41ab.png)

Can you try with latest version of Airbyte?
