### ISSUE TITLE
New sandbox account: LinkedIn Pages

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#12963]
We received a contribution for a new source connector for LinkedIn Pages: https://github.com/airbytehq/airbyte/pull/12894 .
We need a sandbox account to run acceptance test in our CI.
The process to create a sandbox account is described [here](https://github.com/airbytehq/airbyte/pull/12894/files#diff-cee71bc84d14ad85c1b98ef61ec698d1e2e7ac6e269bacebcb89aa7497fa549eR72).

**Comment by igrankova** [comment]
@alafanechere 
Augustin, I see we already have a test account: https://www.linkedin.com/company/setup/new/?src=li-nav&veh=ad%2Fstart%7Cli-nav&trk=n_nav_ads_rr_b
On the LastPass it's name is **linkedin.com** to receive a code on e-mail you can press Resend to all e-mails and this code will be sent to the integration-test@airbyte.io
Let me know if it covers your needs.

**Comment by igrankova** [comment]
@alafanechere, if you need anything else within this task, please, reopen it.
