### ISSUE TITLE
Filter connectors based on Cloud availability 

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#12967]
## Environment
Airbyte Cloud > Settings > Sources/Destinations

## Current Behavior
Connectors not available in Cloud show up on the Sources/Destinations lists.
Example: Shopify is listed on the Sources page but is not available in Cloud yet.

## Expected Behavior
Only the connectors available in Cloud should show up on the Sources/Destinations list.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
