### ISSUE TITLE
Source Hubspot: failed to apply RFC3339 pattern

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#12972]
## Environment
- **Airbyte version**:  0.38.4-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: k8s with helm and kustomize
- **Source Connector and version**: HubSpot 0.1.59
- **Destination Connector and version**: s3 0.35
- **Severity**: High 
- **Step where error happened**: Sync job

## Current Behavior
When syncing data from HubSpot to s3, the sync fails and I see a lot of these in the logs: `2022-05-18 16:33:07 ERROR c.n.s.DateTimeValidator(isLegalDateTime):70 - Failed to apply RFC3339 pattern on 2022-04-17 02:41:46`.

Interestingly, we have two HubSpots and the second one syncs without a problem. Also, we upgraded recently from v0.35.65-alpha and there it worked without problems.

## Expected Behavior
It should sync without problems.

## Logs
```
2022-05-18 16:31:56 [44msource[0m > Syncing stream: companies 2022-05-18 16:31:57 [43mdestination[0m > 2022-05-18 16:31:
57 [32mINFO[m i.a.i.d.r.SerializedBufferingStrategy(lambda$addRecord$0):55 - Starting a new buffer for stream companies (
current state: 51 KB in 1 buffers)2022-05-18 16:32:13 [1;31mERROR[m c.n.s.DateTimeValidator(isLegalDateTime):70 - Failed to 
apply RFC3339 pattern on 2021-02-10 21:38:592022-05-18 16:32:13 [1;31mERROR[m c.n.s.DateTimeValidator(isLegalDateTime):70 - 
Failed to apply RFC3339 pattern on 2021-05-26 14:37:202022-05-18 16:32:13 [1;31mERROR[m c.n.s.DateTimeValidator(
isLegalDateTime):70 - Failed to apply RFC3339 pattern on 2021-02-10 21:38:572022-05-18 16:32:13 [1;31mERROR[m 
c.n.s.DateTimeValidator(isLegalDateTime):70 - Failed to apply RFC3339 pattern on 2021-08-05 07:37:43...2022-05-18 16:33:06 [
32mINFO[m i.a.w.DefaultReplicationWorker(lambda$getDestinationOutputRunnable$7):392 - State in DefaultReplicationWorker from 
destination: io.airbyte.protocol.models.AirbyteMessage@64949138[type=TRACE,log=<null>,spec=<null>,connectionStatus=<null>,
catalog=<null>,record=<null>,state=<null>,trace=io.airbyte.protocol.models.AirbyteTraceMessage@4d28a918[type=ERROR,
emittedAt=1.652891586531E12,error=io.airbyte.protocol.models.AirbyteErrorTraceMessage@7adf89b2[message=Something went wrong in 
the connector. See the logs for more details.,internalMessage=tech.allegro.schema.json2avro.converter.AvroConversionException: 
Failed to convert JSON to Avro: Could not evaluate union, field filters is expected to be one of these: NULL, ARRAY. If this is 
a complex type, check if offending field (path: filters.value) adheres to schema: [[{operator=GT, filterFamily=PropertyValue, 
withinTimeMode=PAST, type=datetime, property=createdate, value=1617314399999}, {operator=SET_ANY, filterFamily=PropertyValue, 
withinTimeMode=PAST, type=enumeration, property=paid_social_source, value=LinkedIn;PPC;Capterra}], [{operator=GT, 
filterFamily=PropertyValue, withinTimeMode=PAST, type=datetime, property=createdate, value=1617314399999}, {
operator=IS_NOT_EMPTY, filterFamily=PropertyValue, withinTimeMode=PAST, type=string, property=marketing_campaign}, {
operator=DOESNT_CONTAIN, filterFamily=PropertyValue, withinTimeMode=PAST, type=string, property=marketing_campaign, 
value=Cart}]],stackTrace=[tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:
129), tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(JsonGenericRecordReader.java:118), 
tech.allegro.schema.json2avro.converter.JsonAvroConverter.convertToGenericDataRecord(JsonAvroConverter.java:95), 
io.airbyte.integrations.destination.s3.avro.AvroRecordFactory.getAvroRecord(AvroRecordFactory.java:39), 
io.airbyte.integrations.destination.s3.parquet.ParquetSerializedBuffer.accept(ParquetSerializedBuffer.java:93), 
io.airbyte.integrations.destination.record_buffer.SerializedBufferingStrategy.addRecord(SerializedBufferingStrategy.java:69), 
io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:
137), io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:50), 
io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:194), 
io.airbyte.integrations.base.IntegrationRunner.lambda$runConsumer$4(IntegrationRunner.java:203), 
io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:232), 
io.airbyte.integrations.base.IntegrationRunner.runConsumer(IntegrationRunner.java:202), 
io.airbyte.integrations.base.IntegrationRunner.lambda$runInternal$1(IntegrationRunner.java:165), 
io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54), 
io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:38), 
io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:165), 
io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:107), 
io.airbyte.integrations.destination.s3.S3Destination.main(S3Destination.java:51)],failureType=system_error,
additionalProperties={}],additionalProperties={}],additionalProperties={}]
```

## Steps to Reproduce
1. Set up destination
2. Set up connection
3. Sync all (as parquet)

## Are you willing to submit a PR?
no

**Comment by marcosmarxm** [comment]
@jan-benisek this problems is happening in the S3 destination side. Does the other sync with Hubspot also sent data to S3 or to another destination? 

Could you try to validate one hypothesis? Create a S3 destination but with Json format and send the Hubspot data to there. Try to query looking for those timestamp malformated values to see if Hubspot is generating them and from what field they are.

**Comment by jan-benisek** [comment]
Hubspot connection 1:
  - to s3, as parquet file, all good.
  - settings:
    - page size: 1024
    - block size: 128
    - compression: snappy
    - padding: 8
    - dict page size: 1024 

Hubspot connection 2
  - to s3, as parquet, bad
  - same connection as the previous one
  - tried with JSON (gzip, block size: 5), same error
  - I was busy today, but I will try to look for the fields! I will keep you posted.

Thank you for your time.

**Comment by jan-benisek** [comment]
@marcosmarxm some examples I found in the JSON files synced (about half of the tables were synced, then it failed):
- table **contacts**
  - "createdate":"2021-02-10 21:38:58"
  - "hs_email_last_open_date":"2021-07-01 14:02:44"
  - "hs_email_first_open_date":"2021-05-26 18:01:00" 
  - "lastmodifieddate":"2022-04-12 21:03:06"
- table **engagement_tasks**
  - "hs_timestamp":"2021-04-28 09:42:31"
  - "hs_createdate":"2021-04-28 09:59:35"  
  - "hs_task_last_contact_outreach":"2021-05-13 12:20:59"

Is this helpful?

**Comment by marcosmarxm** [comment]
I was able to reproduce the problem using integration account. The sync completes with data but prints ERROR which is problematic to users.

**Comment by marcosmarxm** [comment]
@jan-benisek sorry the long delay, I added the issue to connector team roadmap to solve the problem

**Comment by jan-benisek** [comment]
@marcosmarxm Does that mean that full sync completes, but the problematic rows are not loaded. Or they are loaded and the error messages are only "warning"?

Thank for the feedback, much appreciated you took your time and sent it to the right team.

**Comment by jan-benisek** [comment]
Any update on this please?

**Comment by artem1205** [comment]
Hi, @jan-benisek ,
As I can see from the changelog, fields marked as `date-time` are transformed to rfc3339 since version `0.1.60`.
Can you confirm that sync still fails?

**Comment by jan-benisek** [comment]
Hi @artem1205, yes, since recently this works, thanks a lot for following it!
