### ISSUE TITLE
Slack Community Link is expired

### ISSUE THREAD

**Issue by alunarbeach** [airbytehq/airbyte#12971]
### Tell us about the documentation you'd like us to add or update.
The Link to Join Airbyte Slack Community is expired.

### Non Working Link
-  Click the button "[Join the Airbyte Community Slack](https://slack.airbyte.com/?_ga=2.18573241.16053378.1652815759-115854179.1652815759)" in [https://airbyte.com/community#slack](https://airbyte.com/community#slack)
This results in the following error page

```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

**Comment by alunarbeach** [comment]
Is there a way to expedite this request? How are new developers joining the slack?

**Comment by alunarbeach** [comment]
If anybody is still interested, I was able to get a working slack invitation (I could not reuse it after I have used it) thru the chat option in airbyte.io
![sirbyte_slack](https://user-images.githubusercontent.com/494035/169888512-b192ef8a-4c97-409b-8e57-7553cd213b24.png)

**Comment by marcosmarxm** [comment]
Solved try again

**Comment by marcosmarxm** [comment]
Thanks for reporting this @alunarbeach :)
