### ISSUE TITLE
Can't select many streams in Google Ads

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1298]
## Problem
Google Ads has field exclusion rules that specify that when certain fields in a stream are selected, other fields in the same stream cannot be selected. Our UI currently does not support this kind of exclusiviity (and has no way of communicating it) so a user is very likely to make this mistake when choosing streams. This will cause google ads to break when the next sync is run. 

This ticket aims to fix this by determinstically exposing only one exclusive set per stream in the catalog.

**Comment by cgardens** [comment]
@sherifnada - can we add the rules to the documentation on this connector now so that there is at least recourse. obviously we would like to come up with a more bullet proof solution.

**Comment by sherifnada** [comment]
problematic fields will be removed in #1726
