### ISSUE TITLE
[SPEC] APIs for managing per-stream states in the UI

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12991]

**Comment by timroes** [comment]
@benmoriceau @andyjih I don't think we'd want a "per-stream" API from the UI perspective. Given the designs we currently have, this would still be all one form, and I'd expect us to continue calling the `web_backend/connections/update` API, which gets the information about all the streams and saves them (and also resets them as I described in https://github.com/airbytehq/airbyte/issues/12741).
