### ISSUE TITLE
Data missing in Google Ads latest vrsion for `ad_group_ad_report`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#12999]
## Environment
- **Airbyte version**:  0.35.61-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Google Ads 0.1.37
- **Destination Connector and version**: Snowflake 0.4.24
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Latest version of Google Ads is not bringing all campaigns for `ad_group_ad_report`
This is what Google return from querying directly the data:
- Responsive search ad
- Non-skipable in-stream ad
- Discovery ad

But `ad_group_ad_report` only brings campaign of type
- Reponsive search ad

There isn't any info in docs or Google changelog saying something about filtering data from reports.
Using Version with Google v8 brings all records and campaigns.

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
One comparative is: `ad_group_ad_report` and `ad_group_ads` have the same table reference but they bring different campaigns.

**Comment by tinomerl** [comment]
@marcosmarxm we also encountered this behaviour. i replicated the raw http calls and found out that data goes "missing" when the field `segment

**Comment by davydov-d** [comment]
Hi @marcosmarxm have you tried reproducing the issue with version 0.1.39? I tried to reproduce it on versions 0.1.23 (api v8), 0.1.34 and 0.1.39 and the data was not missing. The one thing worth mentioning is that we do not have ads of types `Non-skipable in-stream` and `Discovery` in our test account as they are quite expensive. Instead, we have "Responsive search" ad and "Responsive display ad". I'd be grateful if you provide me with more details on how I can reproduce the issue or give me the access to the account where it persists. Another option is to gain approval for running ad types from report

**Comment by tinomerl** [comment]
Hey @davydov-d, 

i'm sadly not marcosmarxm but i tried replicating the issue with 0.1.39. and it persisted. see the attached screenshots.

![image](https://user-images.githubusercontent.com/35485536/170672628-28c643b9-93ac-4100-a190-46b6113269bc.png)
![image](https://user-images.githubusercontent.com/35485536/170673241-d8d88d99-b2fa-44e6-9a51-c461269bfce2.png)

i dug a bit more in this ad account. the missing campaigns have the campaign type `display network`. and the ads are `responsive display ads`. Hope that helps.

**Comment by davydov-d** [comment]
@ycherniaiev could you please support me and fill in our test account with the data provided by @tinomerl ? that would give me another try to reproduce the issue

**Comment by tinomerl** [comment]
@davydov-d i'm sorry to disappoint you, but that won't be possible. The data shown in my screenshots is from a customer of the place i'm working at in our current test env, that's why it's redacted. i just wanted to chime into the discusion to help you guys a bit out out. i think you will have to wait until @marcosmarxm can give you access to the data. sorry i can't be of any more help.

**Comment by ycherniaiev** [comment]
@davydov-d Discovery and non-skippable test ads are running.Will inform you when we get conversions

**Comment by davydov-d** [comment]
@tinomerl thanks to you and @ycherniaiev I did reproduce it!
you were completely right about the `segments.keyword.ad_group_criterion` field, more on that in the attached PR

**Comment by marcosmarxm** [comment]
Other user is having problem with reports: https://github.com/airbytehq/airbyte/issues/13425

**Comment by tinomerl** [comment]
Hey @davydov-d, thanks for the info. glad i could help you. 👍
