### ISSUE TITLE
Source Acceptance Tests are run using the latest docker image instead of the actual code in the repo

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#13026]
Currently, when we run `/test connector=connectors/source-<connector>`, we run all unit tests against the current code in the branch. However, when we run the source acceptance tests for the specified connector, we pull the latest image from Dockerhub and use that. This might work just fine for code changes to a connector, but its not a good development experience when making changes to the source acceptance tests module itself. It  means we are forced to test locally or we have to publish a new image before we verify the changes using `/test` which is risky. 

Given that we are already running the unit tests on the current source acceptance test code on every `/test` run, we should probably enforce the standard that we build an image of the current branch and not the latest Dockerhub image.

**Comment by sherifnada** [comment]
@brianjlai is this the right flow: 

1. running `/test connector=<something>` should always run `something` from the branch, in order to test those code changes
2. if `something` != SAT then use the Dockerhub SAT else use SAT in the branch

is that right?

**Comment by brianjlai** [comment]
For 1. that is correct yeah. I don't think 2. sounds quite right because `something` will never be SAT in the context of the `/test` command. There might need to be some stuff done behind the scenes if we wanted to figure out when to use the local SAT or the one from Dockerhub

**Comment by sherifnada** [comment]
@brianjlai SAT is tested using `/test connector=bases/source-acceptance-tests` 😁

**Comment by brianjlai** [comment]
Ah got it, I didn't know we still used the same command for SAT. But in this case, I think we still need some way of not always using Dockerhub SAT. Otherwise we're still in the same position where we can't validate new SAT changes against the flow the github actions uses to test connectors. Maybe it can come in the form of an additional argument in the `/test` command or something if we don't want to always defer to the local SAT code.

**Comment by brianjlai** [comment]
Notes from 5/24 grooming:
- The team is aligned that we should be running source-acceptance-tests that are on the current branch instead of the latest Docker image
- The accepted means of doing that is reverting https://github.com/airbytehq/airbyte/pull/3640 which moved away from the `:dev` image
