### ISSUE TITLE
Azure SQL Database Source Connector

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#13035]
## Tell us about the new connector you’d like to have
Azure SQL Database ([official site](https://azure.microsoft.com/en-us/products/azure-sql/database/))

## Describe the context around this new connector
Azure SQL Database is a cloud-based service offered by Microsoft. While it is based on SQL Server, the feature set is different and not fully compatible between the two types of SQL servers. Current MS SQL Source connector does not work for Azure SQL Database and during the investigation into differences, the team realized that the services are different enough to warrant separate connectors.

## Describe the alternative you are considering or using
Tried using MS SQL source connector and that does not work. Original issue filed for MS SQL Source Connector: https://github.com/airbytehq/alpha-beta-issues/issues/54

**Comment by philippeboyd** [comment]
Looking forward to this...

**Comment by charlespickettau** [comment]
We used the standard MS SQL connector with Azure SQL (using sql login) - seems to work

![CleanShot 2022-06-06 at 17 09 15](https://user-images.githubusercontent.com/59814630/172112935-789efe8a-1425-4017-8079-6806fed0ad5c.png)

**Comment by grishick** [comment]
@kimerinn @alexandr-shegeda  as a matter of fact, it does work. I have just tested our alpha connector for MS SQL with my Azure SQL database with incremental deduped + history sync mode and it worked just fine.

**Comment by charlespickettau** [comment]
Great - sounds like this can be closed then!

**Comment by grishick** [comment]
> Great - sounds like this can be closed then!

Not quiet yet :) There is still the issue of CDC possibly not working: https://github.com/airbytehq/airbyte/issues/6339. We need to investigate that before closing.
