### ISSUE TITLE
Destination Google Sheets: obtain scopes to create and edit spreadsheets

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#13049]
## Tell us about the problem you're trying to solve
To properly have permissions to write data to third-party spreadsheets we need obtain thus permission https://www.googleapis.com/auth/spreadsheets
https://www.googleapis.com/auth/drive

## Describe the solution you’d like
Add this scope to app in the Google Cloud Platform and pass verification

**Comment by ycherniaiev** [comment]
@bazarnov @misteryeo  Recorded a demo video for Google Team for scope verification.

**Comment by misteryeo** [comment]
Do we have a sense of how long the process will take @ycherniaiev?

**Comment by ycherniaiev** [comment]
@misteryeo In general they respond to application in one day.One application declined.Expect respond to second application tomorrow.

**Comment by bazarnov** [comment]
@misteryeo we've got this approved by google. The scopes needed for Destination Google Sheets to work are verified, such as: 
- https://www.googleapis.com/auth/spreadsheets
- https://www.googleapis.com/auth/drive

This issue is closed.
