### ISSUE TITLE
Remove service key auth option for Google Sheets source connector

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#13041]
## Environment
Airbyte Cloud > Google Sheets source connector > Authentication

## Current Behavior
For authentication, users can use OAuth or service key auth. Since we want users to use OAuth, we shouldn't provide the option to use service key auth.

## Expected Behavior
Cloud UI only displays OAuth option.

**Comment by sherifnada** [comment]
This is blocked on the ability to do SPEC mutations
