### ISSUE TITLE
Destination Postgres: option to perform normalisation without creation of index

### ISSUE THREAD

**Issue by jimvekemans** [airbytehq/airbyte#13058]
A client of mine uses Greenplum as their warehouse. Greenplum currently uses postgres 9.4.24 which has does not yet support indexing.

Using Airbyte with the destination of postgres, connection tests are succesful and data can be loaded, IF using raw data transfer.
The DBT-project that airbyte generates uses the {{ config() }} block at the top of the models to try and 'create index if not exists' which fails every single time since Greenplum does not understand this keyword.

I've tried exporting the generated DBT-project and running it standalone after removing the index=[...] line from the configs in the models. This does the transformations on the loaded data, exactly as it was supposed to do from within AirByte.

I've also tried to edit the base-normalisation files to skip the mention of index in the config block (with rebuilding the cluster from scratch after completely deleting the images, containers, volumes and network from docker), but the project clearly still generates the index setting in the config block. This is apparent in the generated code under airbyte-server:/tmp/workspace/1/0/...

Now is my request/question:
How do I remove the creation of an index when trying to perform normalizations on data loaded to Greenplum?
Manually extracting and performing custom transformations using practically unchanged files gets very tedious very quickly as the amount of connections increase.

I've forked airbyte to my company's account  where I've been trying to circumvent the creating of the indexes for several days now, without success.

**Comment by misteryeo** [comment]
Hi @jimvekemans, thanks for creating this issue.

Wanted to let you know that we don't have plans to support this as we require [Postgres 9.5 or newer as outlined in our docs](https://docs.airbyte.com/integrations/destinations/postgres#prerequisites). Thanks for your understanding!
