### ISSUE TITLE
Refactor the ServiceForm to not contain connector type

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#13056]
The ServiceForm currently contains the whole form to create a connector including the actual selection of the connector type within one Formik form. This is causing some weird side-effects, that when switching connectors we're basically exchanging all fields of an Formik form, which has several unnice side-effects (e.g. see https://github.com/airbytehq/airbyte/pull/13052#discussion_r878037039).

I suggest we split the connector type selection off that form, and make the formik form to only be the actual connector form (Name and downwards). That way this form will only be initialized once a connector is selected and changing that connector would just render a completely different form, which should solve some of the lifecycle issues we're seeing.

The parent component would just keep track of the selected connector type and would merge it in the form values when sending the request.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This has been attempted in #14526

**Comment by dizel852** [comment]
Notes:
I guess "refactoring the ServiceForm to not contain connector type" it's the first part of refactoring the whole ServiceForm.
I've just got the updated design: https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?node-id=1%3A3 
and  see that we need also move actions buttons outside of the Card component
