### ISSUE TITLE
UI should allow using only the alphanumeric + _ charset when configuring table prefixes on a connection

### ISSUE THREAD

**Issue by sashaNeshcheret** [airbytehq/airbyte#13051]
## Tell us about the problem you're trying to solve
In this [issue](https://github.com/airbytehq/airbyte/issues/6661), the user is using special characters in the target namespace/table name. 

## Describe the solution you’d like
After discussion the more appropriate [solution](https://github.com/airbytehq/airbyte/issues/6661#issuecomment-989200860) is to limit any special characters other than alphanumeric + _ on UI side.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@sashaNeshcheret Could you clarify how the UI would know which fields to limit? Is there some information in the spec about a validation regex or some special limitation for a field?

**Comment by josephkmh** [comment]
Refining notes:
- We're waiting to implement this on the frontend until the SyncCatalog refactor is merged. This will avoid needing to implement it in both Formik and react-hook-form
- @nataliekwong will check with the destinations team to make sure this won't impact anything negatively downstream

**Comment by nataliekwong** [comment]
Updates from my side:

- Agrees with the thoughts laid out by Evan here: https://github.com/airbytehq/airbyte/issues/27336
- There are 28 active connections that currently have patterns that conflict with this convention in Cloud: https://airbyte.metabaseapp.com/question/7712-adhoc-weird-characters-in-prefix

**Comment by MLGitGud** [comment]
Was the impact on other destinations assessed before making this modification?
I was previously using forward slashes ("/") to specify a subdirectory (as a prefix) into Azure Blob Storage. This modification now makes it impossible and all my connections end up in the same directory. Is there any way to bypass this or achieve the same result?

**Comment by tealjulia** [comment]
@MLGitGud thank you for the feedback!  You can bypass the frontend validation that was introduced by updating the connection via the API.  [Here's the documentation](https://reference.airbyte.com/reference/patchconnection) for the connection update endpoint.
