### ISSUE TITLE
Support cron strings in the Connection Settings page

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#13061]
Update the custom replication frequency in the create connection and replication settings pages with a "custom" option that allows the user to add a cron string.

* The form should validate that the cron string is correct before the user can create or update the connection.
* This has a backend dependency #11431. The backend will provide the list of timezones that can be used in the form.
* All APIs consuming the schedule will need to be adjusted to use the new format of the API, the current schedule type will be deprecated
* Should split work into separated PRs: At least one to apply the API changes, and a separate one to introduce the cron string

Figma:
https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=872%3A35119&scaling=min-zoom&page-id=857%3A24319&starting-point-node-id=865%3A52984&show-proto-sidebar=1

**Comment by edmundito** [comment]
Timezones available with PR merge #15666

**Comment by harshithmullapudi** [comment]
@edmundito this is done right?
