### ISSUE TITLE
Source Google Ads: GAQL does not return paused entities ie Campaigns

### ISSUE THREAD

**Issue by bachtsevanis** [airbytehq/airbyte#13068]
## Environment
- **Airbyte version**: 0.38.4
- **OS Version / Instance**: Centos Linux
- **Deployment**: Docker
- **Source Connector and version**: Google Ads 0.1.38
- **Destination Connector and version**:  Big query
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
I am using Google Ads connector in order to sync GAQL and/or Build in reports to Bigquery. Airbyte returns/sync only enabled campaigns. Same query works fine with other tools.

Example query:
SELECT campaign.advertising_channel_sub_type,campaign.advertising_channel_type, campaign.bidding_strategy_type,  campaign.id, campaign.name, campaign.status, metrics.clicks, metrics.cost_micros,
customer.id
FROM campaign WHERE campaign.status = PAUSED

Tool used to compare results: https://www.awql.me/gaql

## Expected Behavior
Return all entries from Google Ads API and not only enabled entities.

## Steps to Reproduce
1. Create a Google Ads source connector
2. Use this GAQL query:  SELECT campaign.advertising_channel_sub_type,campaign.advertising_channel_type, campaign.bidding_strategy_type,  campaign.id, campaign.name, campaign.status, metrics.clicks, metrics.cost_micros, customer.id
FROM campaign WHERE campaign.status = PAUSED
3. Check logs: Airbyte reports that 0 records found in stream and nothing getting synced.

**Comment by midavadim** [comment]
Hi @bachtsevanis,

I was able to reproduce the situation but I do not confirm the problem. Our account has 'PAUSED' campaigns and I was able to run Custom GAQL Query which was mentioned in this issue and it returned all expected records.

The only suggestion I can add is - when new GAQL Query is added, please try to refresh the schema and enable the related stream.

I close this issue, please re-open it if you still have any problems.

Regards,
Vadym
