### ISSUE TITLE
Support Cron Strings in the Connection Settings Page

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#13062]
Figma:
https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?page-id=33740%3A179711&node-id=34344%3A198325&viewport=393%2C-752%2C0.25&scaling=min-zoom&starting-point-node-id=34344%3A198325&show-proto-sidebar=1

**Comment by edmundito** [comment]
Duplicate of #13061
