### ISSUE TITLE
Normalization process does not remove deleted records (CDC Incremental + Dedupe)

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#13077]
## Environment
- **Airbyte version**:  0.38.3 
- **OS Version / Instance**: EC2
- **Deployment**: Docker
- **Source Connector and version**: MySQL (0.5.11) 
- **Destination Connector and version**: Snowflake (0.4.26)
- **Severity**: CRITICAL
- **Step where error happened**: Sync

## Current Behavior
Deleted records appear in the raw table but these are not removed from the SCD and final tables

## Expected Behavior
Deleted records are removed from final table

## Logs
Logs show a normal sync with no errors
<img width="691" alt="Screen Shot 2022-05-23 at 12 49 52 pm" src="https://user-images.githubusercontent.com/33811744/169734095-623e7609-19e1-4516-b475-1ce17c63e987.png">
 
## Steps to Reproduce
1. Connect MySQL source to Snowflake destination
2. Sync
3. Delete a record from source db and sync again.

## Are you willing to submit a PR?
Not familiar with the normalization area

**Comment by danieldiamond** [comment]
Related https://github.com/airbytehq/airbyte/issues/11805

**Comment by danieldiamond** [comment]
Related https://github.com/airbytehq/airbyte/issues/8830

**Comment by danieldiamond** [comment]
Related

**Comment by thisisile** [comment]
I am facing the same issue.

**Comment by edgao** [comment]
@danieldiamond @thisisile can you try updating to the most recent version of airbyte? We're now propagating deletes to the final table. (you'll probably need to reset your data unfortunately, as we're only deleting records from the most-recent sync, so old records won't be retroactively deleted)

We intentionally never delete records from the SCD table (it's intended to be an append-only log). We do, however, update the `_airbyte_active_row` column to reflect that the record is no longer present in the final table.
