### ISSUE TITLE
Kubernetes: how-to use external database

### ISSUE THREAD

**Issue by userbradley** [airbytehq/airbyte#13080]
Howdy,

I am looking at setting up a GKE cluster running Airbyte, but with an external Postgresql cluster.

The documentation currently links to an external Git issue around this, but since that's been completed, it's not beed updated.

[Link to page](https://github.com/airbytehq/airbyte/blob/master/docs/deploying-airbyte/on-kubernetes.md#using-an-external-db)

Are you able to update this please? 

TIA

<3

**Comment by sowla** [comment]
In case they may be helpful to other people, I found these docs helpful :)
https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm
https://docs.airbyte.com/operator-guides/configuring-airbyte-db
