### ISSUE TITLE
Source Salesforce: INVALIDENTITY not supported in Bulk API

### ISSUE THREAD

**Issue by Mikhail-Dem** [airbytehq/airbyte#13088]
## Environment
- **Airbyte version**: 0.36.1-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Salesforce 1.0.9
- **Destination Connector and version**: Snowflake 0.4.24
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
Sync from Salesforce to Snowflake fails due to not supported API call.
Forum thread: [link](https://discuss.airbyte.io/t/failed-to-sync-from-salesforce/1082)

## Expected Behavior
Sync does not fail

## Logs
[logs-47.txt](https://github.com/airbytehq/airbyte/files/8754844/logs-47.txt)

## Steps to Reproduce
I am not sure how the Salesforce object is configured as I have no access to the source

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
@Mikhail-Dem can you check the entity if is not deleted or has any problem in Salesforce side?
```
2022-05-16 12:09:41 [44msource[0m > Giving up for returned HTTP status: 400, body: [{"errorCode":"INVALIDENTITY","message":"Entity '01I0e000000FMSK.Tag' is not supported by the Bulk API."}]
```

**Comment by marcosmarxm** [comment]
Not sure if this is something that our documentation should be more clear that using one type of method to read records from Salesforce you can't bring all type of records?

**Comment by misteryeo** [comment]
What is the ask from the Python team here @marcosmarxm ?

**Comment by Mikhail-Dem** [comment]
@marcosmarxm Sorry for late response
As I said in the original post, I have no access to the Salesforce, so I cannot check if entity was deleted or not. However, I asked the owner and they said the objects are ok

**Comment by marcosmarxm** [comment]
> What is the ask from the Python team here @marcosmarxm ?
Today the connector try to use bulk/rest method automatically. Maybe the connector code is requesting some streams don't allow using bulk.

**Comment by marcosmarxm** [comment]
> @marcosmarxm Sorry for late response As I said in the original post, I have no access to the Salesforce, so I cannot check if entity was deleted or not. However, I asked the owner and they said the objects are ok

What are all streams you are syncing from Salesforce?

**Comment by Mikhail-Dem** [comment]
@marcosmarxm there are 900+ streams, and only tags are causing troubles (the ones ending with `__Tag`)

**Comment by arsenlosenko** [comment]
@Mikhail-Dem sorry for such a late response, I have checked how sync of the connector executes right now, and checked if the error about `INVALIDENTITY` is handled at the moment (currently it is caught, and is logged appropriately). In order to debug this issue further, can you please share the part of your `spec.yaml` file which contains settings for `streams_criteria` value? It might be related to such a behavior of this connector during sync, I would like to compare this with our default settings and see how it affects the sync

**Comment by arsenlosenko** [comment]
Waiting for the response from user, will take this ticket back to work either after response, or when I have completed my current tasks

**Comment by arsenlosenko** [comment]
@erica-airbyte hello, can you (or anybody else from support) please check if any users still have this problem with their sources? Because as far as I can see this issue should be resolved in the latest versions of source-salesforce.

**Comment by erica-airbyte** [comment]
@marcosmarxm are you able to chime in here, I do not have too much context on this but from the comments it looks like there have been been any updates since August. I have not seen this error in cloud for that field.

**Comment by arsenlosenko** [comment]
@marcosmarxm @YowanR can you please confirm, if we should keep this issue open, if this error was not seen in cloud so far (according to @erica-airbyte comment), and re-open it (or open a new issue) once this issue is encountered again?

**Comment by YowanR** [comment]
If no one is impacted by this bug on Cloud at the moment, it's fair to go ahead and close the issue. We can re-open it if the bug re-surfaces again later.

**Comment by arsenlosenko** [comment]
@YowanR understood, closing this issue for now
