### ISSUE TITLE
Update generated api when there's new openapi changes merged to master

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#13089]
We want to integrate our FE client side integration into the general build pipeline for the platform. We should try to achieve the following:

* Do not have the generated code committed into the repository
* During platform builds (and as well as FE development builds) we should generate the client code automatically using orval
* We still would need to wrap new APIs in more high level services/react-query hooks

That way we'd still be able to be notified about APIs that are changing in a way that's breaking the FE. New APIs won't affect the platform build at all, since they'll just add new APIs in the FE code, that are unused.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
