### ISSUE TITLE
develop a plan to improve connection creation and editing

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#13096]
## Tell us about the problem you're trying to solve
Our Replication form on the Connections workflow has had multiple major bugs in the month of May.  We've also seen some buggy behavior during Creation, Transformation, etc.

## Describe the solution you’d like
This process should be revisited and improved.  It is a (the?) core feature of our product and is also high stakes (changes what data ends up in a user's destination)

We need to dive into how this process is currently architected and implemented to identify how we might improve stability.

**Comment by timroes** [comment]
Thoughts:

* `values.connectionConfiguration` plus flattened values are confusing (for a flattened form)
* https://github.com/airbytehq/airbyte/issues/13056

**Comment by tealjulia** [comment]
spec: https://docs.google.com/document/d/1ej4iUk_ccd62hLgRXShe7PwJQ_y3YFybDjj-zdyA_SE/edit#
