### ISSUE TITLE
Apply the 'Documentation' PMD rules

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#13103]
Today we are excluding one Documentation PMD rule that our repo is violating (see gradle/pmd/rules.xml). This ticket is to apply this rule and fix all violations.

1. Remove the rule that is currently excluded within the Design rule under the comment "to be applied eventually", so that it is no longer excluded from pmd analysis. Make sure to continue to exclude the rules that are under the comment "exclude permanently".

2. Run SUB_BUILD=PLATFORM ./gradlew pmdTest and SUB_BUILD=PLATFORM ./gradlew pmdMain to see pmd violations

3. Fix all violations

If this rule cannot or should not be applied in specific instances, add @SuppressWarnings("PMD.RuleName") to the class where the rule is violated (search the repo for examples).

**Comment by davinchia** [comment]
Won't do!
