### ISSUE TITLE
Apply the 'Multithreading' PMD rules

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#13106]
Today we are excluding all of the Multithreading PMD rules that our repo is violating (see gradle/pmd/rules.xml). This ticket is to apply these rules and fix all violations.

1. Remove all of the rules that are currently excluded within the Multithreading rule under the comment "to be applied eventually", so that they are no longer excluded from pmd analysis. Make sure to continue to exclude the rules that are under the comment "exclude permanently".

2. Run SUB_BUILD=PLATFORM ./gradlew pmdTest and SUB_BUILD=PLATFORM ./gradlew pmdMain to see pmd violations

3. Fix all violations

If there are rules that cannot or should not be applied in specific instances, add @SuppressWarnings("PMD.RuleName") to the class where the rule is violated (search the repo for examples).

**Comment by davinchia** [comment]
Won't do!
