### ISSUE TITLE
Apply the 'Design' PMD Rules

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#13102]
Today we are excluding all of the Design PMD rules that our repo is violating (see gradle/pmd/rules.xml). This ticket is to apply these rules and fix all violations.

1. Remove all of the rules that are currently excluded within the Design rule under the comment "to be applied eventually", so that they are no longer excluded from pmd analysis. Make sure to continue to exclude the rules that are under the comment "exclude permanently".

2. Run SUB_BUILD=PLATFORM ./gradlew pmdTest and SUB_BUILD=PLATFORM ./gradlew pmdMain to see pmd violations

3. Fix all violations

If there are rules that cannot or should not be applied in specific instances, add @SuppressWarnings("PMD.RuleName") to the class where the rule is violated (search the repo for examples). The Design rules in particular may require a large amount of refactoring in order to not violate rules. Use your best judgment - if it seems not worth it to try to apply certain rules like 'ExcessiveMethodLength', 'CyclomaticComplexity', or 'CognitiveComplexity' in certain cases, feel free to SuppressWarnings. Or if there are a lot of rule violations that require significant refactoring to fix and you feel they are worth fixing, feel free to break them out into separate tickets to be fixed in separate PRs for easier review.

**Comment by davinchia** [comment]
Won't do!
