### ISSUE TITLE
Edit log link in "Auto-disable warning" customer.io notification

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#13125]
## Current Behavior
The customer.io email "Auto-Disable Connection Warning Notification" contains a broken link to the logs. https://fly.customer.io/env/112679/transactional/8

Clicking on the link results in a "resource not found" page.

![Screen Shot 2022-05-24 at 9 56 31 AM](https://user-images.githubusercontent.com/38087517/170053187-90918fe2-3f29-4449-a9de-33cd98c2b7ff.png)

## Expected Behavior
The link should swap the connection ID and the workspace ID in the URL.

As an example, an email I received goes to: http://cloud.airbyte.io/workspaces/39dc0ef9-766a-4228-b8ce-8a727f970f15/connections/bed3b473-1518-4461-a37f-730ea3d3a848

The correct URL should be  https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/39dc0ef9-766a-4228-b8ce-8a727f970f15/status

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
I think this is Platform?

**Comment by davinchia** [comment]
@terencecho do you know?

**Comment by terencecho** [comment]
Yes, this is a cloud platform issue, related to notifications.

This has already been fixed and deployed as of 3 days ago. This was brought up by some others as well, but seems like Natalie was the first one to catch this with this issue (I didn't know this issue existed until now).

**Comment by terencecho** [comment]
I'll close this issue for now, but feel free to re-open it if it still looks incorrect.

**Comment by nataliekwong** [comment]
Glad it was fixed nevertheless! Thanks @terencecho !
