### ISSUE TITLE
Python CDK: Support new STATE message format

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#13135]
If a connector takes as input a STATE using data, output a STATE using data AND per_stream or global appropriately
At some point in the future, we stop outputting “data” once we have a path for ppl to get off the old protocol version
If a connector takes as input a STATE using only “per_stream” or global, output STATE with that same key (without data)

**Comment by brianjlai** [comment]
Closing this a dupe since we addressed per-stream CDK state in the epic: https://github.com/airbytehq/airbyte/issues/16054
