### ISSUE TITLE
[per-stream cdk] publish all GA API source connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#13136]
Once the CDK has been updated to support per-stream state, we need republish all GA API source connectors so that they use the latest version of the CDK.

For each connector:
- Connectors can opt out of per-stream state by overriding per_stream_state_enabled() and setting it to False. By default, per-stream is enabled for integrations using the latest version of the CDK.
- Optional (but recommended validation steps):
  - Generate expected_records.txt using the existing connector code
  - Add the file to /integration_tests
  - Update basic_read with expect_records in source-acceptance-tests.yaml 
```
expect_records:
  path: "integration_tests/expected_records.txt"
```
- Modify any integration_tests/input_state.json files to use the new STREAM state format
- Validate Source Acceptance Tests from the PR
- Publish a new version of the connector
- Release connector to Airbyte Cloud using the normal process

**Comment by alafanechere** [comment]
# Current migration status

## Cloud

| Connector                        | Release stage       | Migrated |
| -------------------------------- | ------------------- | -------- |
| source-amazon-ads                | generally_available | ✅       |
| source-amplitude                 | generally_available | ❌       |
| source-bing-ads                  | generally_available | ❌       |
| source-facebook-marketing        | generally_available | ✅       |
| source-github                    | generally_available | ✅       |
| source-google-ads                | generally_available | ❌       |
| source-google-analytics-v4       | generally_available | ❌       |
| source-google-search-console     | generally_available | ✅       |
| source-google-sheets             | generally_available | ❌       |
| source-greenhouse                | generally_available | ✅       |
| source-harvest                   | generally_available | ❌       |
| source-hubspot                   | generally_available | ✅       |
| source-instagram                 | generally_available | ✅       |
| source-intercom                  | generally_available | ❌       |
| source-klaviyo                   | generally_available | ✅       |
| source-linkedin-ads              | generally_available | ❌       |
| source-mailchimp                 | generally_available | ❌       |
| source-mixpanel                  | generally_available | ✅       |
| source-notion                    | generally_available | ✅       |
| source-s3                        | generally_available | ✅       |
| source-salesforce                | generally_available | ✅       |
| source-snapchat-marketing        | generally_available | ❌       |
| source-stripe                    | generally_available | ✅       |
| source-surveymonkey              | generally_available | ❌       |
| source-tiktok-marketing          | generally_available | ❌       |
| source-twilio                    | generally_available | ❌       |
| source-zendesk-chat              | generally_available | ❌       |
| source-zendesk-support           | generally_available | ❌       |
| source-chargebee                 | beta                | ✅       |
| source-file-secure               | beta                | ❌       |
| source-freshdesk                 | beta                | ❌       |
| source-iterable                  | beta                | ❌       |
| source-marketo                   | beta                | ✅       |
| source-paypal-transaction        | beta                | ❌       |
| source-pinterest                 | beta                | ✅       |
| source-recharge                  | beta                | ✅       |
| source-sendgrid                  | beta                | ❌       |
| source-sentry                    | beta                | ❌       |
| source-slack                     | beta                | ✅       |
| source-smartsheets               | beta                | ❌       |
| source-youtube-analytics         | beta                | ❌       |
| source-zendesk-talk              | beta                | ❌       |
| source-aws-cloudtrail            | alpha               | ❌       |
| source-airtable                  | alpha               | ❌       |
| source-amazon-sqs                | alpha               | ❌       |
| source-amazon-seller-partner     | alpha               | ❌       |
| source-apify-dataset             | alpha               | ❌       |
| source-azure-table               | alpha               | ❌       |
| source-bamboo-hr                 | alpha               | ❌       |
| source-bigcommerce               | alpha               | ❌       |
| source-braintree                 | alpha               | ❌       |
| source-chartmogul                | alpha               | ❌       |
| source-close-com                 | alpha               | ❌       |
| source-delighted                 | alpha               | ❌       |
| source-dixa                      | alpha               | ❌       |
| source-dockerhub                 | alpha               | ❌       |
| source-exchange-rates            | alpha               | ❌       |
| source-faker                     | alpha               | ❌       |
| source-firebolt                  | alpha               | ❌       |
| source-gitlab                    | alpha               | ❌       |
| source-google-analytics-data-api | alpha               | ❌       |
| source-kustomer-singer           | alpha               | ❌       |
| source-lemlist                   | alpha               | ❌       |
| source-linnworks                 | alpha               | ❌       |
| source-looker                    | alpha               | ❌       |
| source-metabase                  | alpha               | ❌       |
| source-microsoft-teams           | alpha               | ❌       |
| source-monday                    | alpha               | ❌       |
| source-my-hours                  | alpha               | ❌       |
| source-netsuite                  | alpha               | ✅       |
| source-okta                      | alpha               | ❌       |
| source-orb                       | alpha               | ❌       |
| source-orbit                     | alpha               | ❌       |
| source-persistiq                 | alpha               | ❌       |
| source-pokeapi                   | alpha               | ❌       |
| source-posthog                   | alpha               | ❌       |
| source-prestashop                | alpha               | ❌       |
| source-qualaroo                  | alpha               | ❌       |
| source-recurly                   | alpha               | ❌       |
| source-retently                  | alpha               | ❌       |
| source-shopify                   | alpha               | ❌       |
| source-shortio                   | alpha               | ❌       |
| source-square                    | alpha               | ❌       |
| source-tempo                     | alpha               | ❌       |
| source-typeform                  | alpha               | ❌       |
| source-us-census                 | alpha               | ❌       |
| source-webflow                   | alpha               | ❌       |
| source-zendesk-sunshine          | alpha               | ❌       |
| source-zenloop                   | alpha               | ✅       |
| source-zuora                     | alpha               | ❌       |

**Comment by alafanechere** [comment]
SAT is failing for `source-snapchat-marketing`, I preferred to not migrate it to per-stream once this issue is not fixed: 
https://github.com/airbytehq/airbyte/issues/17461

**Comment by alafanechere** [comment]
All GA connectors except `source-snapchat-marketing` are migrated to per-stream state on OSS. I tried to update OSS reference on cloud but I'm facing an error while running the `./tools/bin/update_oss_reference`.

**Comment by brianjlai** [comment]
GL made some recent changes to `source-snapchat-marketing` which fixed the tests and latest published version and on cloud should be using per-stream. Going to close out this ticket out as done since all the GA connectors should now be running per-stream. 

One note is `zendesk-support` is pinned specifically to `0.2.14` for some reason, but i'll give it a look and if it looks okay i'll unpin it to use the latest in the cloud mask
