### ISSUE TITLE
Source MongoDB: doesn't behave as expected when exporting Array fields.

### ISSUE THREAD

**Issue by Gdeba** [airbytehq/airbyte#13147]
## Environment
- **Airbyte version**:  0.39.1-alpha and older ones, not working on any version that I've tested.
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: MongoDB 0.1.14 
- **Destination Connector and version**: Clickhouse 0.1.5 and Postgres 0.3.19 
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
When extracting MongoDB Array fields and inserting them into Clickhouse or Postgres, sync process doesn't create new tables, like with Object fields (using Basic Normalization)

## Expected Behavior
As Airbyte documentation says I expect that: "Basic Normalization attempts to expand any nested arrays or objects it receives into separate tables in order to allow more ergonomic querying of your data."

source: https://docs.airbyte.com/understanding-airbyte/basic-normalization#nesting

## Logs

N/A

## Steps to Reproduce
Using your documentation data here: https://docs.airbyte.com/understanding-airbyte/basic-normalization#nesting
1. Create a collection in Mongo with this JSON:
```
{
  "make": "alfa romeo",
  "model": "4C coupe",
  "limited_editions": [
    { "name": "4C spider", "release_year": 2013 },
    { "name" : "4C spider italia" , "release_year":  2018 }
  ]
}
```
2. Create connections (MongoDB source and Clickhouse/Postgres), create connection between them and set `Transformation -> Normalization` to `Normalized tabular data`.
3. You see that the tables created are not what is expected and only the cars' table is created (apart from the `_airbyte_raw_cars`). There should be another called `limited_editions` with the nested field.

## Are you willing to submit a PR?

Not right now because I think the problem is in the MongoDB connector. In other ones, the behaviour is expected, for example, the PokeAPI connector.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
