### ISSUE TITLE
Prevent broken db state / improve OSS kube deployment process 

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#13144]
## What

OSS was recently migrated to the new temporal scheduler, which included a change that made container-orchestrators the default behavior for OSS kube deployments. 

One of the main benefits of container-orchestrators is that sync jobs can survive a re-deployment of airbyte, as the sync is managed by a separate container that does not get redeployed.

However, when trying to do a rolling/highly-available deployment of kube OSS, other things break today:
- Since the `airbyte-bootloader` pod always has the same name, kubernetes raises an error when trying to deploy a new version of Airbyte to a kube context that already has a completed `airbyte-bootloader` pod, saying that its properties cannot be edited. This should be fixed by either giving all `airbyte-bootloader` pods unique names, or by deleting the `airbyte-bootloader` pod automatically after it completes.
- If a new `airbyte-db` pod is spun up while an existing one is still running, this can cause the underlying postgres database to get into a permanently broken state, with errors like the following when the new pod tries to start up:
  ```
  2022-05-23 18:48:26.032 UTC [22] LOG:  record with incorrect prev-link 6F746F72/500F01C1 at 0/189FDF8
  2022-05-23 18:48:26.032 UTC [22] LOG:  invalid primary checkpoint record
  2022-05-23 18:48:26.032 UTC [22] PANIC:  could not locate a valid checkpoint record 
  2022-05-23 18:48:26.033 UTC [1] LOG:  startup process (PID 22) was terminated by signal 6: Aborted
  2022-05-23 18:48:26.033 UTC [1] LOG:  aborting startup due to startup process failure
  2022-05-23 18:48:26.037 UTC [1] LOG:  database system is shut down
  ```
  - Because of this, we should prevent new airbyte-db pods from spinning up until any existing ones have been terminated completely, possibly through the `recreate` update strategy in kube.

**Comment by davinchia** [comment]
Lake, the bootloader fix is a simple change to using a different Kubernetes yaml tag: https://stackoverflow.com/a/48023670

**Comment by davinchia** [comment]
Using the `recreate` strategy for the Airbyte DB is a good idea.
