### ISSUE TITLE
[Spike] Explore using container-orchestrator for docker-compose

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#13142]
## What

When migrating OSS to the new temporal scheduler, part of the change was to also make using container-orchestrator the default behavior for OSS deployments.

It was discovered during this that the container orchestrator logic currently does not work for docker-compose deployments, as the container orchestrator code seems to make some assumptions that kubernetes is being used.

## How

This ticket involves doing an investigation / spike into the possibility of using container-orchestrator for docker-compose deployments. 

This should involve evaluating the effort of getting container-orchestrator to work with docker-compose.
- If the effort is low, then put up a PR to make this change
- If the effort is large, capture this in a new ticket that notes the tradeoffs of doing so, which we can use to evaluate if this effort is worth doing

**TIMEBOX TO < 2 days**

**Comment by lmossman** [comment]
## Implementation Gaps

This following describes the current gaps in implementation preventing container orchestrator logic from working with docker-compose today:
- The [AsyncOrchestratorPodProcess](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/java/io/airbyte/workers/process/AsyncOrchestratorPodProcess.java) class currently implements the behavior of launching the container orchestrator kube pod. This class uses kubernetes clients to do create the pod and track its status, so this would need to be refactored to use something generic like the airbyte ProcessFactory to do so. 
- The container orchestrator uses a document store to keep track of the status of the async sync process. By default, this uses the local minio pod in kube deployments. However, we currently don't have any docker equivalent of minio, so docker deployments don't currently have anywhere to store these status files, unless GCS/S3 is set up (which not all OSS users do). One solution here could be to add a minio container to docker-compose in order to store these files, though this may have its own difficulties.

## Tradeoffs

The following are benefits of adding container orchestrator support to docker-compose:
- OSS users could potentially perform an upgrade of Airbyte without causing currently-running jobs to fail. 
  - Caveat: it is not clear if this is actually a highly-desired feature for OSS docker users. @andyjih do you have any insight into this?
- Slightly reduces complexity in code by allowing us to remove the [LegacyWorkerFactory](https://github.com/airbytehq/airbyte/blob/bb469418679e1605689d994a57cf59b1095c677d/airbyte-workers/src/main/java/io/airbyte/workers/temporal/sync/ReplicationActivityImpl.java#L186-L218)
  - However, it should be noted that this is only ~30 lines of code that are being executed unique to the non-container-orchestrator path, and this code can likely be easily consolidated with the code in [ReplicationJobOrchestrator](https://github.com/airbytehq/airbyte/blob/bb469418679e1605689d994a57cf59b1095c677d/airbyte-container-orchestrator/src/main/java/io/airbyte/container_orchestrator/ReplicationJobOrchestrator.java#L71-L100), as it is almost identical.

## Conclusion

Based on the following points:
- The complexity in implementing container orchestrators for docker will likely require significant refactoring of AsyncOrchestratorPodProcess as well as determining a way to persist state files
- The desire for this functionality in docker deployments has not been emphasized
- The reduction in code complexity is minimal
it does not seem prudent to work on this in the near future.

**Comment by cgardens** [comment]
Thanks, Lake. Super clear analysis. I agree.

Is there anything we should do just to make it clearer to developers that they need to consider both code paths? Comments or docs?

**Comment by lmossman** [comment]
Created this issue to consolidate the duplicated code and add comments: https://github.com/airbytehq/airbyte/issues/14084

Should be pretty low effort but I wanted to capture it in a ticket so we don't forget.
