### ISSUE TITLE
Support Avro format in S3 source

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#13157]
## Tell us about the problem you're trying to solve

 We are receiving avro files from vendor in s3 and wants to load to warehouse incremental manner 

## Describe the solution you’d like

 Support avro format 

## Describe the alternative you’ve considered or used
 Write spark job

## Are you willing to submit a PR?
  I will try to implement and I need some guidance on solution and best practice

**Comment by misteryeo** [comment]
@sivankumar86 Avro is already a supported format - are you struggling to find it?

**Comment by sivankumar86** [comment]
@misteryeo thanks for reply.  It seems, connector was old and I was able to see avro format after connector upgrade.
