### ISSUE TITLE
Highlight Google Sheets as a destination in the onboarding and new destination pages

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#13160]
* This should only show in the destination connector form (not sources), until a destination type is selected.
* Build a most frequent destination list with BigQuery and Snowflake as destinations. Both should be linked up to LaunchDarkly to be overwritten by an experiment.
* Ignore the "Data Warehouse" in the design and just remove that part of the button
* The bottom box with Google Sheets highlight should be off by default, and any connector can be configured via LaunchDarkly (via its ID) to show up there.
* The bottom box will only show up if there is no destination yet configured.
* Only add the card on the page, do not add it to the destination dropdown (see prototype)

Design: https://www.figma.com/file/2Q6sjFLyylM14RMpkR3TEY/?node-id=1%3A3

Prototype: https://www.figma.com/proto/2Q6sjFLyylM14RMpkR3TEY/02_03_HIGHLIGHT_GOOGLE_SHEET_AS_NEW_DESTINATION?page-id=1%3A3&node-id=301%3A8246&viewport=305%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=301%3A8246&show-proto-sidebar=1

## Context

We now offer Google Sheets as a destination. We expect that users will opt for Google Sheets over a traditional data warehouse because of the lower barrier to authentication.

Rather than showing the dropdown, we can guide the user towards selecting Google Sheets as their first destination.

We would want to show this on /new-destination and /onboarding. It would provide the most value when a user is creating their first destination.

Design from Nico: 

Video link: https://www.loom.com/share/ad30f1c744ca437191880c91ff5747ed

Prototype link: https://www.figma.com/proto/2Q6sjFLyylM14RMpkR3TEY/02_03_HIGHLIGHT_GOOGLE_SHEET_AS_NEW_DESTINATION?page-id=1%3A3&node-id=301%3A8246&viewport=305%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=301%3A8246&show-proto-sidebar=1

File link: https://www.figma.com/file/2Q6sjFLyylM14RMpkR3TEY/?node-id=1%3A3

Other researchs link: https://www.figma.com/file/2Q6sjFLyylM14RMpkR3TEY/?node-id=0%3A1

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
I've updated the issue description to reflect the latest discussion I had with Natalie about this.

**Comment by nataliekwong** [comment]
Hey @vladimir-remar ,

How should we display the item in the scroll area, if there is only one item? Same size as in the design or stretch it to the full width?
Same size as in the design.

I noticed the button "Set up destination" is removed in the design. Should I also remove it from UI?
Yes, it can be removed to reflect the design (the button only needs to show up when a destination is selected)

**Comment by dizel852** [comment]
> Hey @vladimir-remar ,
> 
> How should we display the item in the scroll area, if there is only one item? Same size as in the design or stretch it to the full width? Same size as in the design.
> 
> I noticed the button "Set up destination" is removed in the design. Should I also remove it from UI? Yes, it can be removed to reflect the design (the button only needs to show up when a destination is selected)

Ok, got it! Thanks!

**Comment by edmundito** [comment]
Discussed in planning. Could #13056 help with this?
