### ISSUE TITLE
Source s3: Sync fails if the file is empty although having headers

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13171]
## Environment
Airbyte Version: 0.36.0-alpha
Source: S3 (0.1.10)
Destination: BigQuery (1.1.0)
 
https://discuss.airbyte.io/t/s3-issue-reading-csv-when-only-header-row-present/1155/3 

 I was able to reproduce it.

**Comment by boggdan95** [comment]
+1

I have empty files in the pattern but also I have non empty files, I want that connection only takes the non empty fails, but the connection fails.

**Comment by nguyenluongky** [comment]
+1
I also face the same issue

**Comment by erild** [comment]
+1 
I up this issue since i have it too

**Comment by tolik0** [comment]
I cannot reproduce the issue with the latest version. The CSV library is now used for reading CSV files instead of pyarrow. If you reencounter this error, please reopen the issue and attach your configuration and logs for further investigation.
