### ISSUE TITLE
Source Jira: `issues` stream it's not returning all the fields it should

### ISSUE THREAD

**Issue by Mainara** [airbytehq/airbyte#13175]
## Environment
- **Airbyte version**:  0.28.2-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.2.19 
- **Destination Connector and version**: Postgres 0.3.7 
- **Severity**: Medium
- **Step where error happened**: Update connector

## Current Behavior
I'm trying to get information about the date an issue is completed, in previous versions the `statuscategorychangedate` field was returned in the field object in the `issue` stream, but now I can't get this information and this is very important because I'm using Grafana to query data and create dashboards, and since those attributes are now missing, my dashboards are broken.

## Expected Behavior
The stream issues should return all issue information.

## Steps to Reproduce
1. Create a Jira connection
2. Perform a sync (with the issues stream selected)
3. Try to retrieve the project that issue belongs to:
```
SELECT * FROM issues I
WHERE I.fields -> 'project' ->> 'key' = '<your-project-key>';
```

## Are you willing to submit a PR?

Yes.

**Comment by marcosmarxm** [comment]
update the title to fields instead data, data would imply the records but looks the records are there but there are a few fields missing right?

**Comment by grubberr** [comment]
In this PR https://github.com/airbytehq/airbyte/pull/20128 `source-jira` connector was greatly refined 
now `issues` stream has to return all possible fields using 'field=*all' param

**Comment by grubberr** [comment]
This PR https://github.com/airbytehq/airbyte/pull/20128 has to resolve this issue
