### ISSUE TITLE
Platform build fails due to test DefaultJobPersistenceTest.ListJobStatusAndTimestampWithConnection#testTimestampFiltering

### ISSUE THREAD

**Issue by mkhokh-33** [airbytehq/airbyte#13192]
## Current Behavior
2 asserts it test failing:
 assertTrue(timeAfterFirstJob.getEpochSecond() <= timestampFilteredJobs.get(0).getCreatedAtInSecond());
 assertTrue(timeAfterFirstJob.getEpochSecond() <= timestampFilteredJobs.get(0).getUpdatedAtInSecond());

if happens because timeAfterFirstJob is UTC instance and timestampFilteredJobs.get(0) is instance with timezone

## Expected Behavior
fix it the way when the both date will be in UTC

**Comment by evantahler** [comment]
Closing, because I don't think this is a problem any more
