### ISSUE TITLE
Postgres source: add a check for publications in discover method for CDC

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#13207]
## Tell us about the problem you're trying to solve
- In https://github.com/airbytehq/airbyte/issues/5837 we concluded that under the CDC mode, all tables and only the tables to be synced should be in the publication.
- We should add a check in the discover method for this. The check can only be added to the discover method, not the check method, because the check method does not know the catalog.

## Describe the solution you’d like
- Query the `pg_publication` and `pg_publication_tables` to see which tables are included in the publication.
- Limit the streams in the catalog to only those exist in the publication
    - Should we enforce this? Or just provide a warning message?

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

**Comment by matt-ripple** [comment]
@tuliren It's no longer possible to sync views with a connection that uses CDC replication. This is causing us issues. The only way around this would be to create two sources for each of our postgres databases (We have 10+).
