### ISSUE TITLE
Invalid links in markdown files

### ISSUE THREAD

**Issue by jackielii** [airbytehq/airbyte#13222]
### Tell us about the documentation you'd like us to add or update.

While going through the handbook, I found broken link. Then made a little script that detects the invalid links. 

### If applicable, add links to the relevant docs that should be updated

file: airbyte-integrations/connectors/destination-firestore/README.md 
Broken link: `[the documentation](https://docs.airbyte.io/integrations/destinations/firestore)`

file: airbyte-integrations/connectors/source-appsflyer/README.md 
Broken link: `[documentation](https://docs.airbyte.io/integrations/sources/appsflyer)`

file: airbyte-integrations/connectors/source-appsflyer/README.md 
Broken link: `[the documentation](https://docs.airbyte.io/integrations/sources/appsflyer)`

file: airbyte-integrations/connectors/source-mailgun/README.md 
Broken link: `[documentation](https://docs.airbyte.io/integrations/sources/mailgun)`

file: airbyte-integrations/connectors/source-mailgun/README.md 
Broken link: `[the documentation](https://docs.airbyte.io/integrations/sources/mailgun)`

file: airbyte-integrations/connectors/source-pardot/README.md 
Broken link: `[the documentation](https://docs.airbyte.io/integrations/sources/pardot)`

file: airbyte-integrations/connectors/source-pardot/README.md 
Broken link: `[documentation](https://docs.airbyte.io/integrations/sources/pardot)`

file: docs/career-and-open-positions/senior-software-engineer.md 
Broken link: `[roadmap](https://docs.airbyte.io/roadmap)`

file: docs/contributing-to-airbyte/updating-documentation.md 
Broken link: `[internal guide for deployment lives here](https://github.com/airbytehq/runbooks/blob/master/deploying_and_reverting_docs.md)`

file: docs/contributing-to-airbyte/updating-documentation.md 
Broken link: `[dedicated repo hosting the Github pages](https://github.com/airbytehq/airbytehq.github.io)`

**Comment by Rajakavitha1** [comment]
file: airbyte-integrations/connectors/destination-firestore/README.md
Broken link: [the documentation](https://docs.airbyte.io/integrations/destinations/firestore)
_Related .md file is not located at https://github.com/airbytehq/airbyte/tree/master/docs/integrations/destinations_
file: airbyte-integrations/connectors/source-appsflyer/README.md
Broken link: [documentation](https://docs.airbyte.io/integrations/sources/appsflyer)
_Related .md file is not located at https://github.com/airbytehq/airbyte/tree/master/docs/integrations/sources_

file: airbyte-integrations/connectors/source-appsflyer/README.md
Broken link: [the documentation](https://docs.airbyte.io/integrations/sources/appsflyer)
_[Redundant]_
_Related .md file is not located at https://github.com/airbytehq/airbyte/tree/master/docs/integrations/sources_
file: airbyte-integrations/connectors/source-mailgun/README.md
Broken link: [documentation](https://docs.airbyte.io/integrations/sources/mailgun)
_Related .md file is not located at https://github.com/airbytehq/airbyte/tree/master/docs/integrations/sources_
file: airbyte-integrations/connectors/source-mailgun/README.md
Broken link: [the documentation](https://docs.airbyte.io/integrations/sources/mailgun)
_[Redundant]_

file: airbyte-integrations/connectors/source-pardot/README.md
Broken link: [the documentation](https://docs.airbyte.io/integrations/sources/pardot)
_Related .md file is not located at https://github.com/airbytehq/airbyte/tree/master/docs/integrations/sources_
file: airbyte-integrations/connectors/source-pardot/README.md
Broken link: [documentation](https://docs.airbyte.io/integrations/sources/pardot)
_[Redundant]_
