### ISSUE TITLE
Add stylelint to the webapp

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#13230]
Since we're now switching over to use SCSS modules we should include [stylelint](https://stylelint.io/) into the repository.

We need to figure out how we eventually want to embed this:

* Having separate `npm` tasks to run for linting, that we'd also run as part of the `build` and `start` command. Disadvantage is, that this is not automatically watching the files and relints on the console on changes.
* Having the above also run as part of some pre-commit hooks in git.
* Introduce some create react app config modification tool (like [craco](https://github.com/gsoft-inc/craco)) to modify our webpack config to include the styllint plugin. That would give the options to run it as part of `build` and `start` (including watching) automatically, though requires the introduction of Craco.

**Comment by krishnaglick** [comment]
I'd love it if CI ran our `npm run lint` since I've just included stylelint in that command.
