### ISSUE TITLE
additionalProperties of catalog in discover don't pass to read

### ISSUE THREAD

**Issue by s12f** [airbytehq/airbyte#13255]
## Environment
- **Airbyte version**:  docker compose up on project directory
- **OS Version / Instance**: Arch Linux
- **Deployment**: docker compose
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior

I am writing a java source connector, I don't find the java source connector kit or template, but I found that the source-fafka is using the ``IntegrationRunner`` wrapper class and I used same way to implement the connection, it works well except additionalProperties, after using ``withAdditionalProperty("abc", "abc")`` to add an additionalProperty to catalog, ``discover`` will return:
```
{"type":"CATALOG","catalog":{"streams":[...],"abc":"abc"}}
```
but the additionalProperty is not passed to ``read``. 

I searched other connections(grep ``withAdditionalProperty``), it seems that no one uses the additionalProperties, did I misunderstand it?

## Expected Behavior
the additionalProperty("abc") should be passed to ``read``.

## Steps to Reproduce
1. docker compose up on project directory
2. write a java source connector using ``IntegrationRunner`` 
3. (``discover`` function) add withAdditionalProperty("abc", "abc") in returning catalog
4. (``read`` function) print the input calalog
5. setup a connection in airbyte
6.  check the log

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by alafanechere** [comment]
Hey @s12f do you mind posting this question on our [connector development forum](https://discuss.airbyte.io/c/connector-development/16)? 
It would also be really helpful if you could also share your connector repo so that we can try to reproduce your problem.
