### ISSUE TITLE
Update Python Connectors Docs

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1326]
## Tell us about the documentation you'd like us to add or update
* python connectors [docs](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/python-connectors) is out of date, we don't want to recommend people do multi module stuff anymore.
* these docs should explain how to set up a single python source in intellij / pycharm

**Comment by ChristopheDuong** [comment]
Is it really outdated? 

it seems it could still be useful, no?

**Comment by cgardens** [comment]
> it seems it could still be useful, no?

what is "it" in this context?

I am not suggesting we get rid of these docs. They recommend doing a multimodule setup in intellij / pycharm. That is no longer how we recommend anyone developing on python stuff. we recommend setting up a different project per module. I am pretty sure that what these docs describe doesn't work well. We should document for people one way to setup a good development environment for python.
