### ISSUE TITLE
Invalid message when resetting data 

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1328]
## Expected Behavior
I would expect the message to say: Are you sure you want to reset the data?

## Current Behavior
![image](https://user-images.githubusercontent.com/1154337/102158031-67c3b500-3e35-11eb-9d6b-c29687a40c4a.png)

## Steps to Reproduce
1. Try to reset data by pressing the button in the sync history

## Severity of the bug for you
Low

**Comment by ChristopheDuong** [comment]
Agreed, would be nice to be more explicit that data in the destination will be lost forever

**Comment by cgardens** [comment]
@Jamakase - This problem is that we asked you to reuse the same pop up here as was used in the schema setup screen. The buttons should do the same thing but we would like to have the text altered to match what michel mentioned.
