### ISSUE TITLE
:bug: Destination MsSql : Enable DAT tests for all integration tests

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#13309]
## Current Behavior
Currently, the new DAT tests are enabled only for the tests based on `MSSQLDestinationAcceptanceTest`.

## Expected Behavior
Tests `MSSQLDestinationAcceptanceTest`, `MSSQLDestinationAcceptanceTestSSL`, `SshMSSQLDestinationAcceptanceTest` should be compatible with the new DAT.

**Comment by etsybaev** [comment]
Keep working on it, but now I see another issue also that is kind of a blocker and needs to be fixed. Will do it
![Selection_447.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/c879f4ca-6c7f-4614-b1f4-dac7c9689123)
