### ISSUE TITLE
Missing connectors sources and destination after upgrade from 0.39.1 to 0.39.5 (latest)

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#13301]
Upgraded from `0.39.1-alpha` to `0.39.5-alpha` and... **what happened to most of the connectors!?**

![image](https://user-images.githubusercontent.com/3239656/170827593-d3627020-e8dc-4ffd-9c7e-c13d76b40cf1.png)

![image](https://user-images.githubusercontent.com/3239656/170827577-2d6418b1-bf14-4fff-869c-fbb4b6095c1a.png)

![image](https://user-images.githubusercontent.com/3239656/170827583-b76c9193-b351-42b8-a9ed-0d72e199cc89.png)

**Comment by marcosmarxm** [comment]
Maybe a bug in the upgrade process. @philippeboyd this is only the connectors you're using?

**Comment by marcosmarxm** [comment]
another user reported the same issue: https://airbytehq-team.slack.com/archives/C038KM9NF7Z/p1653987359196879

**Comment by marcosmarxm** [comment]
I wasn't able to reproduce in a simple instance locally @philippeboyd can you give more info about your enviroment?

**Comment by marcosmarxm** [comment]
Another user reported in slack: https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1653982249376419

**Comment by marcosmarxm** [comment]
Other user having the same issue: https://github.com/airbytehq/airbyte/issues/13301

**Comment by marcosmarxm** [comment]
I'm not able to reproduce the problem. But using a custom connector in 0.39.1 and upgrade to 0.39.5 won't show the custom connector in the setting page anymore. 

@philippeboyd do you have any custom connector in your env?

**Comment by philippeboyd** [comment]
@marcosmarxm we have a custom source connector, yes but others are also not showing.

**Comment by philippeboyd** [comment]
it's still a private connector for one of our client's API, so not published to a public docker registry but it's in the format of
`us-docker.pkg.dev/<gcp_project_id>/<company>/source-xyz-api:0.2.13`

**Comment by infina-calvin** [comment]
I reported this issue on slack yesterday: https://airbytehq.slack.com/archives/C021JANJ6TY/p1653982249376419

This issue has been resolved for me with the 0.39.7 update

![image](https://user-images.githubusercontent.com/101394676/171387596-892b7fc7-e3d3-4b37-bea8-d116a0cf9ef8.png)

**Comment by marcosmarxm** [comment]
@philippeboyd can you test upgrade to 0.39.7?

**Comment by nauxliu** [comment]
Upgrading to 0.39.7 fixed the issue for me.

**Comment by philippeboyd** [comment]
@marcosmarxm indeed, updating to 0.39.7 did fix the issue. Weird bug tough... would've been nice to know the source of it.

I'll close the issue.

**Comment by alafanechere** [comment]
@philippeboyd this was the fix https://github.com/airbytehq/airbyte/pull/13341
