### ISSUE TITLE
Destinations : enable DAT for python destinations with java integration tests

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#13311]
## Tell us about the problem you're trying to solve
Some python destinations use java integration tests. These tests don't use the new DAT.
Destination AwsDatalake uses DAT. We need to apply `AdvancedTestDataComparator` and define supported datatypes

## Describe the solution you’d like
Find all python destinations with java tests and enable DAT

**Comment by grishick** [comment]
@DoNotPanicUA could you please list the Python destinations with Java integration tests in this issue?

**Comment by yurii-bidiuk** [comment]
Hi @grishick 
I found that there is only one phyton destination that uses DAT, it's `destiantion-aws-datalake`
