### ISSUE TITLE
The platform resets data in the destination on source fail

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#13312]
Probably the platform should distinguish the source not emitting records because of an exception and the source not emitting records because of absent data and reset the destination only in the latter case.

The issue created based on the bugreport https://github.com/airbytehq/airbyte/issues/11251

## Environment
- **Airbyte version**:  0.35.12-alpha
- **Deployment**: kubernetes
- **Source Connector and version**: mixpanel 0.1.9
- **Destination Connector and version**: bigquery 0.6.1
- **Severity**:  High
- **Step where error happened**: Sync job 

## Current Behavior
The data in the destination is erased

## Expected Behavior
Nothing happens to the data in the destination after the source fails

## Steps to Reproduce
1. Setup any source to any destination sync locally, mode = full_refresh-overwrite
2. Run sync, it should end up successfully
3. Emulate the error in the source locally (`raise Exception()`)
4. Run the sync again and watch the destination: it's empty!

**Comment by misteryeo** [comment]
cc: @andyjih

**Comment by evantahler** [comment]
Is this still happening?

**Comment by andyjih** [comment]
@davydov-d Going to close this, but if it's still happening, please re-open this issue!
