### ISSUE TITLE
Source Klaviyo: need to create data for flows stream

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13321]
Need to create records for flows stream

#11685

**Comment by igrankova** [comment]
Hi, @harshithmullapudi, please find the flows updated. If you need more, just let me know.

**Comment by harshithmullapudi** [comment]
That's fast ⏩. Thanks a lot. 👍🏻

**Comment by igrankova** [comment]
@harshithmullapudi, could you please close the issue if everything is ok?

**Comment by harshithmullapudi** [comment]
Yeah this issue is resolved
