### ISSUE TITLE
Show affected streams in log list

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#13324]
With the per-stream resets there are some jobs that only affect specific streams. The API for that is tracked in #13256. We want to show that information in the job overview list.

Figma available here: https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=1%3A1581&starting-point-node-id=112%3A320

![screenshot-20220531-160422](https://user-images.githubusercontent.com/877229/171192622-90ce0a4d-a7f1-4336-b43c-f7e905602474.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Reviewed with @andyjih and this is ready to be worked on. The API should be available.
