### ISSUE TITLE
Present changes in catalog to the user

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#13329]
When a user uses the "Refresh catalogue" functionality on an existing saved connection, we want to show a modal containing the changes in the catalog that the user need to confirm.

The backend API for this is tracked in #13232 

**Figma mocks**:https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?scaling=min-zoom&page-id=1%3A3&node-id=198%3A3822&starting-point-node-id=112%3A320
^ updated figma link 6/22

The behavior should be as follows:

* The user presses the refresh button, which would do a request towards the `web_backend/connections/get` endpoint, which will return the diff format outlined in the BE issue
* If there is a diff available, the FE will show a modal with just a confirm dialog as shown in the designs. The confirm button will only hide the modal. There is no further BE calls happening.
* The modal currently showing the saving the connection should no longer be shown.
* Should still send the full catalog to the backend

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Bug discovered while working on this: we should improve error handling if the schema refresh fails
https://github.com/airbytehq/airbyte/issues/14096
