### ISSUE TITLE
Freshdesk connection: `It should be a valid date in the 'combined date and time ISO8601' format`

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#13328]
## Environment
- **Airbyte version**:  0.39.5-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: k8s
- **Source Connector and version**: Freshdesk version 0.3.0
- **Destination Connector and version**: s3 0.3.6
- **Severity**:  Critical
- **Step where error happened**: Sync job

## Current Behavior
Syncing Freshdesk to s3 (as JSON, gzip compression) fails:

## Expected Behavior
No error.
## Logs
![Screenshot 2022-05-31 at 13 30 36](https://user-images.githubusercontent.com/91880749/171194067-8252d130-5569-495a-9aa3-75630ae30659.png)
Full logs:
[airbyte-freshdesk-logs.txt](https://github.com/airbytehq/airbyte/files/8805913/airbyte-freshdesk-logs.txt)
## Steps to Reproduce
1. set up s3 destination (JSON, gzip)
2. set up Freshdesk source (with domain, API, no date limit, no rate limit)
3. create connection, sync all (full refresh-append, mirror source structure)

## Are you willing to submit a PR?
Maybe if it is simple.

**Comment by alafanechere** [comment]
Hey @jan-benisek could you please share a screenshot of your Freshdesk source configuration?

**Comment by jan-benisek** [comment]
@alafanechere sure, here it is:
![Screenshot 2022-06-03 at 12 48 01](https://user-images.githubusercontent.com/91880749/171839986-82be5a7f-2fd5-4acb-88df-ae9b20df31be.png)

**Comment by jan-benisek** [comment]
Hi, just want to say thank you, really useful for our team to have data from Freshdesk using Airbyte. Much appreciated 🙏
