### ISSUE TITLE
Highlight removed/added streams when editing connection

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#13326]
When we're editing a connection we want to highlight streams that are added or removed (disabled) from the connection in contrast to the saved state.

The designs for this can be found in https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?node-id=34531%3A202627&starting-point-node-id=34389%3A199739&show-proto-sidebar=1

A newly added stream (compared to the saved state) should be highlighted slightly green and get the plus icon in front of the row. A stream that would be removed compared to the previously saved state would be highlighted red and get a minus in front of it.

![screenshot-20220531-132023](https://user-images.githubusercontent.com/877229/171161907-1be3fd1b-3a39-4c95-b617-275105136247.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
