### ISSUE TITLE
Add a TrialEndTimestamp property to cloudWorkspaces API

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#13338]
In order for us to complete https://github.com/airbytehq/airbyte-cloud/issues/1488 we will need the trial end date from Orb to be exposed to the frontend via the API at `/v1/cloud_workspaces/get`.

If the user is no longer in a trial, this can be returned as `null` or not be specified.

**Comment by andyjih** [comment]
Made a new issue our cloud project, so will close this issue here.
