### ISSUE TITLE
Turn off any legacy unused Sentry connector instrumentation

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#13335]
- [x] Talk to relevant people to figure out if the `airbyte-connectors` or `python-connectors` Sentry projects are being used, and deprecate as appropriate.
- [x] Fix the Sentry error & transaction limit 
  - hopefully deprecating at least some of the above helps here

**Comment by Phlair** [comment]
We can gut the codebase from legacy sentry stuff in python and java :D

**Comment by Phlair** [comment]
Disabled the DSNs which effectively turns them off.

Also ripped out sentry from python cdk.

Rest of the work is to rip out from java, but no real rush to do that before completing the rest of incident management

**Comment by sherifnada** [comment]
@Phlair might it make more sense to ask the DBs team to remove that code at their own pace? up to you

**Comment by Phlair** [comment]
I have a branch that's 80-90% there for java sentry removal so I'll just finish that off and PR it up
