### ISSUE TITLE
Custom connector not showing after successful addition

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#13333]
## Environment
- **Airbyte version**:  0.39.5

## Steps to reproduce
* Create a new source definition in the settings > source page

## Current Behavior
* The call the the `create` endpoint returns a 200
* The new source definition is available in the `actor_definition` table **but with a `public = false` flag.**
* The new source definition is not listed by the `list_latest` or `list_for_workspace` endpoints
* The new source definition is not available in the UI
* Running `UPDATE actor_definition SET public = true WHERE name = '<connectorname>';` fixes the problem.

[This issue was raised on our forum](https://discuss.airbyte.io/t/custom-connector-not-showing-after-successfull-import/1266)

**Comment by git-phu** [comment]
Included in release [v0.39.6-alpha](https://github.com/airbytehq/airbyte/releases/tag/v0.39.6-alpha)

**Comment by Nomad-IC** [comment]
The problem is still reproduced in `v0.40.22`
