### ISSUE TITLE
source google ads: addition of Stream for pulling metrics related to Performance Max Campaign

### ISSUE THREAD

**Issue by pulkit1729** [airbytehq/airbyte#13353]
## Tell us about the problem you're trying to solve
When pulling the data from ad_group_ad_report the campaigns with Performance Max are not being pulled this is expected behaviour of the Google Ads API

## Describe the solution you’d like
Add a separate stream which can pull the metrics and relevant data for Performance Max campaigns

## Are you willing to submit a PR?
Yes

**Comment by alafanechere** [comment]
Hey @pulkit1729, I think this is a duplicate of https://github.com/airbytehq/airbyte/issues/11062
Feel free to assign it to yourself if you want to work on this!

**Comment by pulkit1729** [comment]
Hi Airbytehq/Airbyte,

I am not able to assign the issue myself can you please assign it to me.
