### ISSUE TITLE
Update logos to optimize UX

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#13357]
## Tell us about the problem you're trying to solve
Today, when navigating our in-app experience, logos are either missing, disproportioned or are the variation which includes the vendor name which makes identifying that vendor incredibly difficult in the dropdown.
![Airbyte  New Source 2022-05-31 at 4 50 16 PM](https://user-images.githubusercontent.com/16851149/171301869-aad8c8cc-d9e8-4198-8bc3-f2a9927aaab8.jpg)

## Describe the solution you’d like
Update all logos with the appropriate .svg file in [this library](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/?node-id=2%3A675). And make sure that they are updated to be reflected in production - https://github.com/airbytehq/airbyte/tree/master/airbyte-config/init/src/main/resources/icons

**Comment by igrankova** [comment]
[New logo library:](https://drive.google.com/drive/folders/11BjC1vBFKwXTUPg6gnocqDglVJw76qK-?usp=sharing)
