### ISSUE TITLE
🐛 Source MsSql: Source connection setup failure 

### ISSUE THREAD

**Issue by vamsikurre** [airbytehq/airbyte#13361]
## Environment
- **Airbyte version**:  0.39.7-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mssql:0.4.0 
- **Step where error happened**: Setup new connection

## Current Behavior
![image](https://user-images.githubusercontent.com/12517918/171324531-19d715ab-97ea-4fb4-9014-ba430bcc809c.png)

## Expected Behavior
Connection should be created without error

## Logs
[mssql_check.log](https://github.com/airbytehq/airbyte/files/8810937/mssql_check.log)

## Steps to Reproduce
1. Fill the source connection form and click on 'Set up source' button

## Are you willing to submit a PR?

No

**Comment by pipat-flowacc** [comment]
I also have the same problem with exact airbyte and connector version on aws ec2 deployment.

**Comment by marcosmarxm** [comment]
#13419 will fix the issue

**Comment by pipat-flowacc** [comment]
Thx Marcos! The connector can connect after your patch.

**Comment by vamsikurre** [comment]
Thank you, Connector is working in 0.4.1
