### ISSUE TITLE
Stuck in setting up new connection (source clickhouse, destination postgresql)

### ISSUE THREAD

**Issue by jjdblast** [airbytehq/airbyte#13365]
## Environment
- **Airbyte version**:  0.39.7-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker (docker-compose version 1.27.4, build 40524192)
[scheduler-logs.txt](https://github.com/airbytehq/airbyte/files/8811727/scheduler-logs.txt)
[server-logs.txt](https://github.com/airbytehq/airbyte/files/8811728/server-logs.txt)

- **Source Connector and version**: airbyte/source-clickhouse 0.1.10
- **Destination Connector and version**: airbyte/destination-postgres 0.3.20
- **Step where error happened**: Setup new connection

## Current Behavior
Stuck in setting up new connection

## Expected Behavior
Setup new connection.

## Logs
Attached below.

## Steps to Reproduce
1. clone repo & using `docker-compose up -d` start service
2. set clickhouse source connector, disable ssl connection
3. set postgres destination connector, disable ssl connection
4. set up conneciton, and stucked

My clickhoue is deployed by docker, data size is not very large (about 100-200mb). I noticed that source connector's docker container is running, hunging about 2 hours, but could not fetch log by `docker logs xxx`, error: `Error response from daemon: configured logging driver does not support reading`

## Are you willing to submit a PR?
Sure.

**Comment by marcosmarxm** [comment]
Are you able to create a connection with other source?

**Comment by marcosmarxm** [comment]
Closed due inactivity.

**Comment by munir131** [comment]
I am also getting same error when I used postgres as destination in local setup
