### ISSUE TITLE
Source Zendesk Chat: Make life easier for those who have a lot of data

### ISSUE THREAD

**Issue by RobertoBonnet** [airbytehq/airbyte#13379]
## Tell us about the problem you're trying to solve
It's very hard to process all the data who has a lot of data to process

## Describe the solution you’d like
implementation of state_checkpoint_interval in possible classes and increse limit of requests and pagination limit

## Are you willing to submit a PR?
Yeah

**Comment by harshithmullapudi** [comment]
Hey Looks like this is solved in https://github.com/airbytehq/airbyte/pull/14214
