### ISSUE TITLE
MySQL Destination - create destination failed, reporting SQLSyntaxErrorException

### ISSUE THREAD

**Issue by JianhaoZhang** [airbytehq/airbyte#13376]
## Environment
- **Airbyte version**:  0.39.1-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: N/A
- **Destination Connector and version**: MySQL 0.1.18 
- **Step where error happened**: Setup new destination

## Current Behavior
The destination creation failed the destination check with syntax error
The same configuration does not fail on source creation 
***The MySQL database version is 5.5.62

![image](https://user-images.githubusercontent.com/19567494/171427151-18cb0c5f-2db9-4387-b18c-69fabf78c19a.png)

## Expected Behavior
It should pass the destination check

## Logs
[logs-15cfe01d-00fe-4389-b302-f3519add91d5.txt](https://github.com/airbytehq/airbyte/files/8814947/logs-15cfe01d-00fe-4389-b302-f3519add91d5.txt)

## Steps to Reproduce
1. Create a MySQL database, version 5.5.62
2. Try to connect it on Airbyte as a destination
3. Fail

## Are you willing to submit a PR?

No

**Comment by marcosmarxm** [comment]
Can you check if your MySQL version allow creating the airbyte raw table?
```
"CREATE TABLE IF NOT EXISTS %s.%s ( \n"
            + "%s VARCHAR(256) PRIMARY KEY,\n"
            + "%s JSON,\n"
            + "%s TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6)\n"
            + ");\n",
```

**Comment by JianhaoZhang** [comment]
@marcosmarxm I think it might be the root cause. Trying to run this query throws exactly the same error.

**Comment by marcosmarxm** [comment]
Closing due inactivity.
