### ISSUE TITLE
SAT: Check that dates are valid when using `airbyte_type`

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#13399]
We have multiple connectors that are failing the platform's json schema validation due to providing dates in non-standard formats. Connectors should always emit dates in ISO8601 format to ensure it's handled properly in later stages in the pipeline, so this should be a failing test in the SAT.

The current check in the SAT looks for `format: "date-time"` and tries to parse it with `pendulum`:

https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/asserts.py#L24-L32 

Pendulum is somewhat lenient and allows non-compliant formats to be parsed, but since strictly validating against ISO8601 is hard - this is _okay_.

We should:
- Change `strict=False` to `strict=True` when parsing
- Also validate `format: "date"`
- Also validate date `airbyte_type` usage without `format`
- Turn on `format` checking in our JSONSchema validator to check for valid RFC3339 https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats (validation is not enforced by default)

More concretely, all of the following should be validated:

- `{"type": "string", "format": "date"}`
- `{"type": "string", "format": "date-time"}`
- `{"type": "string", "format": "date-time", "airbyte_type": "timestamp_with_timezone"}`
- `{"type": "string", "format": "date-time", "airbyte_type": "timestamp_without_timezone"}`
- `{"type": "string", "airbyte_type": "date"}`
- `{"type": "string", "airbyte_type": "timestamp_with_timezone"}`
- `{"type": "string", "airbyte_type": "timestamp_without_timezone"}`

Types from this document: https://docs.airbyte.com/understanding-airbyte/supported-data-types/#dates-and-timestamps

**Comment by evantahler** [comment]
This story should be paused until the updates to normalization are made in Q4 - cc @edgao and @bleonard.  We'll be getting some new types, and maybe some stronger ways to validate record properties

**Comment by evantahler** [comment]
The new data types (https://github.com/airbytehq/airbyte/pull/17486) come with regular expressions - Validation just got easier!

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/22193
