### ISSUE TITLE
dbt Normalization Shouldn't Happen If There Are No New Records Found During Sync

### ISSUE THREAD

**Issue by azhard** [airbytehq/airbyte#13395]
## Tell us about the problem you're trying to solve
Right now when Airbyte is orchestrating a connection sync with default normalization enabled, it will always run the normalization (dbt) step regardless of if there are new records included in the sync.

This is especially relevant when using an incremental sync mode because there might not always be new updates that Airbyte finds but execution time is still spent normalizing.

## Describe the solution you’d like
Ideally in the situation described above, normalization doesn't happen because it's not needed as the pre-sync tables should be identical to the post-sync tables.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?

Yes!

**Comment by marcosmarxm** [comment]
This is for a complete sync with no new records OR for each stream?

**Comment by azhard** [comment]
I was specifically talking about complete syncs but extending that to per stream behaviour would also be ideal.
