### ISSUE TITLE
Bug or feature with secrets - question

### ISSUE THREAD

**Issue by knugusbayevps** [airbytehq/airbyte#13407]
## Environment
- **Airbyte version**:  0.38.3-alpha
- **Deployment**: Docker
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
After upgrading airbyte from 0.36.58-version to 0.38.3-alpha I noticed that added new "secrets" table where airbyte stores actor's secret data.
I have found that in this table appeared data, BUT on old actors in "configuration" field secret values is already present.
I checked that on a new actors json schema is different, secret fields stores link to "secrets" table.

My question is: Is it correct that airbyte not update secret values in "configuration" field of "actor" table?
In my case we use some source actors where we manually refresh_token value in airbyte's actor configuration(because airbyte currently not update this value due some limitations with python scripts).

So should I check in my code now that there are string value or object ("_secret" with link to secrets) ?

## Expected Behavior
*Tell us what should happen.*

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
@knugusbayevps did you try latest version of Airbyte?

**Comment by knugusbayevps** [comment]
@marcosmarxm No, I didn't.

**Comment by alafanechere** [comment]
Hey @knugusbayevps do you mind:
* Trying out the newest Airbyte version and check if this question remains
* If you still have questions about how secrets are managed on Airbyte I'd suggest you open a topic on our [forum](https://discuss.airbyte.io/). Our engineering team will try to answer and it will help other users having the same question in the future. It will also help us improve our documentation in the future. 🙏

**Comment by alafanechere** [comment]
> In my case we use some source actors where we manually refresh_token value in airbyte's actor configuration(because airbyte currently not update this value due some limitations with python scripts).

This use case is really interesting and sharing it on our forum would be really valuable too!
