### ISSUE TITLE
New sandbox account for Timely

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#13409]
We need a sandbox account for the [Timely](https://timelyapp.com/) service in order to review [this PR](https://github.com/airbytehq/airbyte/pull/13292)

**Comment by ycherniaiev** [comment]
Trial is on - till 16.06.2022. LastPass: "timely", will try direct communication to create sandbox - otherwise we will need paid plan(8 USD per user per month min)

**Comment by ycherniaiev** [comment]
@alafanechere 14-day trial may be used as test acoount for now. To extend this one we need a parnership ensuring that Airbyte user also uses Timely. Do you have an info who requested this connector?

**Comment by alafanechere** [comment]
All right, thank you @ycherniaiev . I guess @makyash is using Timely and Airbyte as they created the connector in https://github.com/airbytehq/airbyte/pull/13292
