### ISSUE TITLE
Renaming connection name: couple of issues

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#13416]
## Environment
- **Airbyte version**:  0.39.7-alpha
- **OS Version / Instance**: macOS, Chrome 
- **Deployment**: OSS (Docker)

## Current Behavior
- When a user tries to rename the connection name, the text is aligned to the left in edit mode.
![inpup_edit_mode_align_left](https://user-images.githubusercontent.com/20929344/171618217-b9e6bb4e-f831-44b2-aca5-25a14b53a5dc.gif)

- User is unable to remove the whole name, the last character is left
![last_character_connection_name](https://user-images.githubusercontent.com/20929344/171618861-240fb0e6-24d8-4680-90a2-3e2510e3011c.gif)

- User is able to create a connection with an empty name
![empty_connection_name](https://user-images.githubusercontent.com/20929344/171619700-827a0c8e-cbd7-477a-9dae-7a2df19f1236.gif)

## Expected Behavior
- IMO text in edit mode should be aligned to the center also since it's more natural.
- User should be able to remove the whole name
- If a user tries to save a connection name with an empty name - set the name which was before he started editing the connection name (TBD: @timroes )

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
