### ISSUE TITLE
Obtain public developer application for Talk Desk source connector

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#13414]
## Tell us about the problem you're trying to solve
[EPIC] Oauth developer applications airbytehq/airbyte-internal-issues#242

**Comment by ycherniaiev** [comment]
With step in obtaining public app here is to obtain private app. Private app is availbale in account, but setting up account requires direct communication with TalkDesk team

**Comment by ycherniaiev** [comment]
Trial is on - till 16.06.2022. LastPass: "timely", will try direct communication to create sandbox - otherwise we will need paid plan(8 USD per user per month min)

**Comment by airbyteio** [comment]
LastPass name: Primary Talkdesk Developer Account
https://airbyte-dev.mytalkdesk.com/atlas/apps/oauth-clients/65115b8232524c859cf1d7dd64ad5dd2/edit

**Comment by airbyteio** [comment]
After the OAuth integration is implemented, we should send the Project for review: https://airbyte-dev.mytalkdesk.com/atlas/apps/developer/projects

**Comment by alejobs** [comment]
@ycherniaiev what is the status of this?

**Comment by YowanR** [comment]
@alejobs Is this a connector that you would like to work on? We would love to see a contribution here :D
