### ISSUE TITLE
[EPIC] Source Snapchat to Beta

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#13458]
Placeholder

Pre-requisite feature requests: 
- [x] https://github.com/airbytehq/airbyte/issues/10040

**Comment by misteryeo** [comment]
@lazebnyi updated this to be Beta since it's currently in Alpha. Please make sure to pull in any outstanding issues/bugs too.

**Comment by misteryeo** [comment]
@midavadim I don't see the docs in the standard template in prod or in an open PR - can you point me in the right direction?

**Comment by misteryeo** [comment]
LGTM!

---
Andy Yeo
Senior Product Manager
Github <https://github.com/airbytehq/airbyte> | Twitter
<https://twitter.com/AirbyteHQ> | LinkedIn
<https://www.linkedin.com/company/airbytehq/>


We're hiring, come work with me! <https://airbyte.io/careers> [image: 🚀]
