### ISSUE TITLE
Improve usability of email invite form

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#13456]
If a user clicks "Add a New User", they are blocked from submitting the form unless they fill in the additional textbox.  There also isn't any way to go "back" to a valid state if it was clicked by accident.  They either have to cancel the entire form or enter a bogus email in that textbox.  Seems useful to have a way out for users (either loosening validation or having a way to get out of this state without losing data they've already entered)

<img width="636" alt="Screen Shot 2022-06-03 at 12 42 03 PM" src="https://user-images.githubusercontent.com/63751206/171908742-ab387432-5797-4375-98f4-1a4c2c3a1b59.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
