### ISSUE TITLE
Progress Bar for Refresh Source Schema

### ISSUE THREAD

**Issue by erica-airbyte** [airbytehq/airbyte#13461]
## Tell us about the problem you're trying to solve
Sometimes when users select "refresh source schema" the update can take a while but nothing is happening on the page so it is hard to tell if it has been updated or is updating still. 

## Describe the solution you’d like
A progress bar on if the update is still happening. 

## Describe the alternative you’ve considered or used
open up dev tools to see the "update" action is still "pending". 

## Additional context
n/a

## Are you willing to submit a PR?
no

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This has been addressed via https://github.com/airbytehq/airbyte/pull/13388 (and will soon be available in Cloud).
