### ISSUE TITLE
CSV Destination double-quotes records

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1346]
## Expected Behavior
I setup a sync from MySQL to CSV. MySQL contained the following data: 
```
mysql> select * from id_and_name;
+------+---------+
| id   | name    |
+------+---------+
|    1 | picard  |
|    2 | crusher |
+------+---------+
```

after the sync completed, the resulting CSV had the following data: 

```
ab_id,emitted_at,data
38fafb55-bac2-469f-81a1-639a379afa4f,1608105386693,"{""id"":1,""name"":""picard""}"
c2f1d6c8-ac47-4b7e-86bc-407da2e56541,1608105386693,"{""id"":2,""name"":""crusher""}"
```
the `data` column had double-quotes around everything. 

I expect that there wouldn't be this double-quoting in the CSV destination as it changes the underlying JSON data. 
## Severity of the bug for you
Medium

**Comment by cgardens** [comment]
Could you describe what you expect here? To the best of my knowledge this is the correct behavior for quote escaping in CSV. It's clunk but, I believe it's how the standard works. 

https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv

**Comment by ChristopheDuong** [comment]
This is because CSV that are written by destination csv are not real CSVs...

It's a CSV with 3 columns where the last one "data" is actually a nested object

**Comment by cgardens** [comment]
@sherifnada @ChristopheDuong based on the standards we have set for what a "raw" output from airbyte is, can you point out to me where this diverges? What output do you expect from Airbyte in this case (assuming basic normalization is not applied, only talking about the blob version)

**Comment by sherifnada** [comment]
@cgardens thanks for linking the SO answer. I didn't realize this was actually in line with CSV spec. I'm happy with the way this is then. To reiterate my understanding: 

1. In the `data` column we write an object which contains commas, so we enclose the whole field value with `"`
2. to escape the quotes inside the JSON value, we prepend each one with another comma. 

Makes sense. Not an actual issue then. Closing this.

**Comment by ChristopheDuong** [comment]
In terms of CSV, it is correct, but I feel it would be more user-friendly if we stored newline delimited JSON and call it like that instead of a CSV that is hard to work with as a user?

**Comment by cgardens** [comment]
@ChristopheDuong - I agree with you. Can you create a separate issue for the feature you want?
