### ISSUE TITLE
Update logos to optimize UX

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#13491]
## What
#13357

## How
- find and add missing or not appropriate icons to `airbyte-config`
- edited each `source_difinitions.yaml` & `destination_definitions.yaml` with missing icons property
- edited each `seed` with missing icons property

**Comment by ycherniaiev** [comment]
Misssing or inproper logos arem [ here](https://drive.google.com/drive/folders/11BjC1vBFKwXTUPg6gnocqDglVJw76qK-)

**Comment by lazebnyi** [comment]
Closed to https://github.com/airbytehq/airbyte/pull/14496#issuecomment-1317805144
