### ISSUE TITLE
Import configuration fails with foreign key constraint error

### ISSUE THREAD

**Issue by jyates-om1** [airbytehq/airbyte#13498]
## Environment
- **Airbyte version**:  0.39.9-alpha
- **OS Version / Instance**: macOS (x86)
- **Deployment**: Docker
- **Source Connector and version**: source-snowflake:0.1.12
- **Destination Connector and version**: destination-s3:0.3.6
- **Step where error happened**: Import configuration

## Current Behavior
After creating a connection with snowflake as the source and s3 as the destination, I am able to export the configuration from the UI, but get a foreign key constraint error when trying to import the resulting configuration

## Expected Behavior
I should be able to import the configuration without an error

## Logs
Attached to this issue. look for: 
```
ERROR: insert or update on table "connection" violates foreign key constraint "connection_actor_catalog_id_fk"
  Detail: Key (source_catalog_id)=(1d033f52-d6a4-4256-98cc-34c607f2b209) is not present in table "actor_catalog".
```
[scheduler-logs.txt](https://github.com/airbytehq/airbyte/files/8845559/scheduler-logs.txt)
[server-logs.txt](https://github.com/airbytehq/airbyte/files/8845560/server-logs.txt)

## Steps to Reproduce
1. Create a snowflake source
2. Create an s3 destination
3. Create a connection linking the source to the destination
4. go to settings in the ui and export the configuration
5. go to settings in the ui and import the configuration produced by step 4
6. Observe that the import fails, and server logs output a foreign key constraint error

## Are you willing to submit a PR?
Possibly! It would take me some time to understand how the configuration import works and I may need some pointers on where to look for debugging

**Comment by jyates-om1** [comment]
Is anyone able to reproduce this behavior?

**Comment by marcosmarxm** [comment]
I was able to reproduce the same behavior as described by @jyates-om1 in Airbyte 0.39.9-alpha.

Log file: [server-logs (2).txt](https://github.com/airbytehq/airbyte/files/8943510/server-logs.2.txt)

**Comment by marcosmarxm** [comment]
Issue is reproducible using latest version (0.39.18-alpha) @jyates-om1 and @wissevrowl I added the issue to platform team to solve it.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Augustin on 2022-07-01 at 07:31:*

<blockquote><div class="zd-comment" dir="auto">An issue already existed: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/13498">https://github.com/airbytehq/airbyte/issues/13498</a><br></div></blockquote>
