### ISSUE TITLE
Github connector silently fails if the input token does not have required permissions

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1349]
## Description
This was seen in #1082 , point no.3 in the issue created. The GH connector didn't have permissions to access the requested resources (which should have failed the job) but the job succeeded. 

## Acceptance Criteria for this issue: 

1. Reliably recreate the problem (and describe how it can be recreated in this issue)
2. Implement solution

**Comment by vitaliizazmic** [comment]
Root issue doesn't have full log record. But the same issue may arise while syncing collaborators stream. If user isn't one of them Github API v3 will return response 403 forbidden
{
  "message": "Must have push access to view repository collaborators.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-collaborators"
}
In this case Github Singer Tap raises  AuthException error
https://github.com/singer-io/tap-github/blob/2cc18761fa3ed6d3c51da66535fbab68f8102d1e/tap_github/__init__.py#L107
But there isn't handling of error. And Singer Tap fails.
To fix this issue we need change source code of Github Singer Tap.

**Comment by sherifnada** [comment]
closed in #1516
