### ISSUE TITLE
Amplitude stuck in infinite loop generating duplicate events

### ISSUE THREAD

**Issue by b4stien** [airbytehq/airbyte#13500]
## Environment
- **Airbyte version**:  0.39.10-alpha
- **OS Version / Instance**: Ubuntu 20.04.4 LTS
- **Deployment**: Docker
- **Source Connector and version**: `airbyte/source-amplitude:0.1.8`
- **Destination Connector and version**: `airbyte/destination-postgres:0.3.20`
- **Step where error happened**: Sync job

## Current Behavior

Amplitude connector is stuck in an infinite loop recording every event over and over again, hence never finishing a sync and ending up filling all available disk space. It's reproducible 100% of the time in "incremental + deduped history" and "full refresh + overwrite" modes.

```
SELECT COUNT(*), _airbyte_data->>'$insert_id' FROM amplitude2._airbyte_tmp_utw_events GROUP BY _airbyte_data->>'$insert_id' HAVING COUNT(*) > 1;

count  $insert_id
38  27432c06-6751-41e8-b3e6-df68698868b2
38  e1967d9c-5432-4144-9b2c-f7fe5a173f15
38  c0fe1ec7-0fbd-4d4f-a8b4-513c4bb22a71
38  46bab8e1-34bd-4521-b72c-428498450c5d
38  6f40b324-5e56-4451-9521-c6a15d5840c9
38  2a6a7553-9427-4119-826e-16681b821629
38  26b52fcf-49d4-4506-88c2-2cf60d7ebf53
...
```

**Comment by marcosmarxm** [comment]
@b4stien please post the complete log file for the sync. Can you give more information about how much data your source has?

**Comment by b4stien** [comment]
This is one currently running [logs-78093.txt](https://github.com/airbytehq/airbyte/files/8845990/logs-78093.txt).

`SELECT COUNT(*), _airbyte_data->>'$insert_id' FROM amplitude2._airbyte_tmp_gxk_events GROUP BY _airbyte_data->>'$insert_id' HAVING COUNT(*) > 1;` now returns:

```
88  27432c06-6751-41e8-b3e6-df68698868b2
88  c0fe1ec7-0fbd-4d4f-a8b4-513c4bb22a71
88  46bab8e1-34bd-4521-b72c-428498450c5d
88  0dc0cd61-024e-4b5c-89c6-85db7db880c2
...
```

`SELECT MAX(_airbyte_data->>'event_time'), MIN(_airbyte_data->>'event_time') FROM amplitude2._airbyte_tmp_gxk_events;` gives:

```
max  min
2021-01-04T00:59:41.598000+00:00  2021-01-01T00:00:20.822000+00:00
```

`curl --request GET --url 'https://amplitude.com/api/2/export?start=20210101T00&end=20210104T00'` (with the proper headers obv) gives a 2.8MB file, to give you a ballpark of "how much data" is in my source: not much.

**Comment by b4stien** [comment]
Same logs a couple of hours later [logs-78093.txt](https://github.com/airbytehq/airbyte/files/8850343/logs-78093.txt).

**Comment by marcosmarxm** [comment]
You said 2.8Mb but the sync is consuming 30Gb+ data, looks each record is quite huge.

**Comment by b4stien** [comment]
> You said 2.8Mb but the sync is consuming 30Gb+ data, looks each record is quite huge.

The sync is "generating" that much data because it stores every record in an infinite loop, not because each record is big.

The following query: `SELECT COUNT(*), _airbyte_data->>'$insert_id' FROM amplitude2._airbyte_tmp_gxk_events GROUP BY _airbyte_data->>'$insert_id' HAVING COUNT(*) > 1;` exhibits that I have 15491 unique records, each being store 1533 times in DB, hence the amount of data.

**Comment by b4stien** [comment]
After further investigation there is a serious bug in `source-amplitude`. I've read elsewhere you're considering it's GA, you might want to re-consider for a while. If you confirm that no one else is working on it I could draft a PR to fix it.

The gist of the issue is the following:
- Within `source-amplitude` there is two ways to split the data extracted from amplitude: HTTP pagination and stream slices.
- Every "stream" ([as defined here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/source_amplitude/source.py#L39-L43)) except `Events` uses exclusively HTTP pagination without stream slices.
  - For these streams it works great, HTTP pagination with `_get_end_date()`, `next_page_token()` and `request_params()` have the responsability to split HTTP requests into `time_interval` fragments, everything's fine.
- For `Events` both methods (stream slices and HTTP paginations) are used and as they are not aware of each other, it's stuck in an infinite loop.
  - `Event.request_params()` ([here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/source_amplitude/api.py#L200-L204)) doesn't care about a "next page token" hence about HTTP pagination.
  - But a non-empty "next page token" is [generated here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amplitude/source_amplitude/api.py#L200-L204) by it's base class.
  - And with a non-empty "next page token" we loop [in here](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py#L398-L425) with no way to exit this loop.

**Comment by b4stien** [comment]
[The PR](https://github.com/airbytehq/airbyte/pull/13638) fixed my issue, as you can see: [logs-79110.txt](https://github.com/airbytehq/airbyte/files/8873681/logs-79110.txt).

**Comment by b4stien** [comment]
Just so you know, you have the same issue in prod in Airbyte Cloud, see https://cloud.airbyte.io/workspaces/9ac913ae-9364-47a0-a48d-60ab59022fa2/connections/3fe3bca0-c929-4699-a134-ab9fb2cad8dd/status.
