### ISSUE TITLE
Update Iterable connector to support incremental events

### ISSUE THREAD

**Issue by geoffreytran** [airbytehq/airbyte#13504]
## Summary

Iterable connector currently does a full refresh of events. There can be a large amount of events on a production instance, so the events stream should support incremental load similar to the email click/bounce streams. The process to switch to incremental support appears to be simple with the logic from the email click streams as the email clicks are based off the events in Iterable.

**Comment by midavadim** [comment]
Unfortunately, 'events' API does not support the ability to query on specific date range:

https://api.iterable.com/api/docs#export_exportUserEvents
Export all events in JSON format for a user specified by email or userId. One event per line.

so it is not possible to implement incremental sync for 'events' streams.

**Comment by geoffreytran** [comment]
Yes, looking at the exportUserEvents api it doesn't. 

It looks like FiveTran is able to have the incremental functionality by using the https://api.iterable.com/api/docs#export_exportDataJson API instead. They're exporting for all the different eventTypes by start/end time ranges.

**Comment by midavadim** [comment]
Do you mean that under 'events' you want to download all kind of 'dataTypeName' from 

https://api.iterable.com/api/docs#export_exportDataJson

line here:

![image](https://user-images.githubusercontent.com/3889748/186760319-172bc8a5-2aa2-4baf-8496-9f31cbea8dfd.png)

**Comment by geoffreytran** [comment]
Correct, the https://api.iterable.com/api/docs#export_exportUserEvents API downloads all the events listed in dataTypeName from https://api.iterable.com/api/docs#export_exportDataJson.

dataTypeName list is the name of all the possible events that can be sent for a user similar to the list of events here https://fivetran.com/docs/applications/iterable#schemanotes

**Comment by midavadim** [comment]
@geoffreytran 

We have implemented a separate incremental stream for each type of event available in export API since 0.1.17 version.

Regards,
Vadym
