### ISSUE TITLE
Fix integration tests destination-elasticsearch Mac OS

### ISSUE THREAD

**Issue by suhomud** [airbytehq/airbyte#13525]
After updating testcontainers lib to 1.17.1 version integration tests failed for Mac OS with next error:

`java.net.ConnectException: Connection refused`

**Comment by Phlair** [comment]
I am also seeing destination-elasticsearch failing integration tests, both locally and running in github actions.

For me it's failing `testDataTypeTestWithNormalization` on `[2]`. See screenshot below:

<img width="1373" alt="Screenshot 2022-06-20 at 14 00 42" src="https://user-images.githubusercontent.com/27702686/174607310-54021122-3637-4250-bf1d-d299c242afd2.png">

**Comment by suhomud** [comment]
@Phlair it can be not related issues but could you pull latest master and try it locally first?

**Comment by Phlair** [comment]
^ that's what I did, resulting in the fail shown in the screenshot @suhomud

**Comment by suhomud** [comment]
The reason of failed test is dataset which provides a different types in array which is not supported by ElasticSearch by the  default mapper. I'll disable this test until this support will be added 
https://github.com/airbytehq/airbyte/issues/14568
