### ISSUE TITLE
Fix integration tests destination-clickhouse Mac OS

### ISSUE THREAD

**Issue by suhomud** [airbytehq/airbyte#13524]
After updating testcontainers lib to 1.17.1 version integration tests failed for Mac OS with next error: 

```
2022-06-03 05:33:04 destination > 2022-06-03 05:33:04 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
2022-06-03 05:33:04 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.
```

**Comment by alexandr-shegeda** [comment]
@grishick they were passing on CI and Linux at least three weeks ago when this issue was created, but after that bunch of code were modified, and now we are waiting for some fixes from @jdpgrailsdev and @benmoriceau

**Comment by grishick** [comment]
As far as I can see integration tests for Clickhouse Destination are not working on Mac and looks like they are not always working on Linux. They are working on CI though.

Link to CI run on master:  https://github.com/airbytehq/airbyte/actions/runs/2619259149 (all tests pass)

Attaching integration test report on Linux from @[mzitnik](https://github.com/mzitnik): [integrationTestJava.tar.gz](https://github.com/airbytehq/airbyte/files/9050070/integrationTestJava.tar.gz)

On my Mac (Apple M1 Pro, 32GB)  the following tests failed:

- `ClickhouseDestinationAcceptanceTest > testSyncWithLargeRecordBatch(String, String) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testSyncWithLargeRecordBatch(String, String)[1]`
- `ClickhouseDestinationAcceptanceTest > testCheckConnection()`
- `ClickhouseDestinationAcceptanceTest > testIncrementalSync()`
- `ClickhouseDestinationAcceptanceTest > testSync(String, String) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testSync(String, String)[2] `
- `ClickhouseDestinationAcceptanceTest > testDataTypeTestWithNormalization(String, String, TestCompatibility) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testDataTypeTestWithNormalization(String, String, TestCompatibility)[4]`
- `ClickhouseDestinationAcceptanceTest > testDataTypeTestWithNormalization(String, String, TestCompatibility) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testDataTypeTestWithNormalization(String, String, TestCompatibility)[3]`
- `ClickhouseDestinationAcceptanceTest > testDataTypeTestWithNormalization(String, String, TestCompatibility) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testDataTypeTestWithNormalization(String, String, TestCompatibility)[2]`
- `ClickhouseDestinationAcceptanceTest > testDataTypeTestWithNormalization(String, String, TestCompatibility) > io.airbyte.integrations.destination.clickhouse.ClickhouseDestinationAcceptanceTest.testDataTypeTestWithNormalization(String, String, TestCompatibility)[1]` 

also, on my Mac running `./gradlew :airbyte-integrations:connectors:destination-clickhouse:integrationTest` took over an hour and `ClickhouseDestinationAcceptanceTest > testSyncWithLargeRecordBatch(String, String)` seems to be hanging.

**Comment by suhomud** [comment]
Hi @grishick, could check it again on the latest master? I did the change checked on Mac M1 and Intel and CI seems like working now

**Comment by grishick** [comment]
Thank you chasing this down. It works on my M1 Mac now!
