### ISSUE TITLE
Empty space with barely noticeable message if no Setup Guide is found for source/destination

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#13555]
## Environment
- **Airbyte version**:  0.39.13-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Cloud, OSS, Prod
- **Source Connector and version**: Google Ads 0.1.40
- **Step where error happened**: Sources /New Source / Choose Google Ads 
## Current Behavior
If the source/destination does not have the setup guide, the screen remains split with a barely noticeable message "No Setup Guide found for this connector."

## Expected Behavior
If there is no setup guide probably would be better to show some nice placeholder(or "request setup guide" button in order to understand how many users need it)

## Steps to Reproduce
1. Open `Sources` tab
2. Click `New Source` button
3. Choose `Google Ads` source

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/20929344/172402697-ba235fe2-1823-43c7-9fd5-ac3c5892adbd.png">

**Comment by tealjulia** [comment]
This is an interesting issue!  Thanks for surfacing it @dizel852.  A bigger problem here: We _have_ Google Ads docs, but ad-blockers prevent the markdown from rendering.  There are only two connectors without docs and they are pretty lightly used.  The two tasks here are:
1. Create a workaround for Google Ads docs to render (I've outlined a plan with @timroes)
2. Consider adding better design for missing docs state

**Comment by marcosmarxm** [comment]
@tealjulia should I open a different issue to deal with custom connectors?
![image](https://user-images.githubusercontent.com/5154322/172923976-f3a4de30-fe38-4c95-9fcd-52a2b6459335.png)

**Comment by tealjulia** [comment]
@andyjih You had previously approved the simple "No Setup Guide found for this connector" for missing docs (AFAIK currently only Mailgun and Firestore and Firestore (OSS only I believe)).  

Is it worth looking into a redesign of this page for that or should I close the Issue when the Google Ads fix is merged?

**Comment by andyjih** [comment]
@tealjulia Do we know if the adblocker is blocking only Google-related docs pages or pages?

If it's only affecting this Google Ads page, then I don't think we need to redesign the page further as it's still only affecting those 2 plugins.

**Comment by tealjulia** [comment]
@andyjih I tried the other connectors containing "Ad" and "Google" and Google Ads was the only one that I could find.

**Comment by andyjih** [comment]
@tealjulia Cool, then I think it's fine to keep the existing design for now. Thanks!
