### ISSUE TITLE
preserve disk space by setting retention for workspaces/logs 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1355]
## Tell us about the problem you're trying to solve
Airbyte never cleans up workspaces/log files. Over time, this will take more and more disk space.

## Describe the solution you’d like
We should somehow clean up these files in a way that doesn't break the UI.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368077823173) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@jrhizor can this be closed?
