### ISSUE TITLE
Source Mongodb: `mongodb+srv` option as DNS Seed List Connection Format

### ISSUE THREAD

**Issue by cope** [airbytehq/airbyte#13602]
At the moment, the replica set option only accepts the [Standard Connection String Format](https://www.mongodb.com/docs/manual/reference/connection-string/?_ga=2.166037693.2064241928.1654681455-80498819.1654681453#standard-connection-string-format).

However, at my company we use the [DNS Seed List Connection Format](https://www.mongodb.com/docs/manual/reference/connection-string/?_ga=2.166037693.2064241928.1654681455-80498819.1654681453#dns-seed-list-connection-format), which has been available since MongoDB 3.6.

Can you please add this?

**Comment by cope** [comment]
Can you please update us here when issue completed? :)

**Comment by pebabion** [comment]
@marcosmarxm @cope did this ever get picked up and worked on? Or do we want to close it?

**Comment by cope** [comment]
Looks like it is done. It can be close from my perspective.
