### ISSUE TITLE
 Download more (logs) files from workspace using the browser 

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1362]
## Tell us about the problem you're trying to solve
Same as #1297 but not only the logs files, normalization files/folder, and catalog.json too!

For example, I want to be able to download the DBT files for an attempt in the browser by hitting one button. I don't want to have to copy and paste out of the UI or mess around with docker cp to pull those files out of the docker volume myself.

## Describe the solution you’d like
Add a download button in the attempts and the admin page that would create an archive with multiple interesting files. Ideally, secrets could be automatically purged out of the archive.

## Describe the alternative you’ve considered or used
copy and paste out of the UI or mess around with docker cp to pull those files out of the docker volume myself.

## Additional context
Frequent use case when normalization fails because logs from sync workers are not enough content to diagnose errors:

* https://airbytehq.slack.com/archives/C019WJFR1JT/p1608194075143500?thread_ts=1608185832.141600&cid=C019WJFR1JT
* https://github.com/airbytehq/airbyte/issues/1296

Usage when user wants to customize transformations using our DBT models as a starting point

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368137166316) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
done.
