### ISSUE TITLE
`source-github` should use smaller page sizes to prevent OOM issues

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#13629]
In our internal use of the Github source, we've hit some OOM problems, and have measured the github source pod consuming at least 1.6GB of memory.  This is a lot for an API source... so we should perhaps have smaller page sizes for some streams.  I have not yet been able to determine *which* stream(s) is the culprit.

1. Log the start of each stream so we can know which stream caused the problem, if there is an OOM crash.  
2. Decrease the page size for that stream

See https://github.com/airbytehq/oncall/issues/266 for more information

**Comment by evantahler** [comment]
@grubberr did https://github.com/airbytehq/airbyte/pull/13558 perhaps close this issue?

**Comment by grubberr** [comment]
@evantahler I hope yes, I asked @pedroslopez to deploy source-github:0.2.33 on cloud and check it

**Comment by evantahler** [comment]
source-github v0.2.33 now on cloud!
