### ISSUE TITLE
SonarCube download plugin timeout

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#13635]
## Current Behavior
Currently GitHub Action `sonarsource/sonarqube-scan-action@master` FAILED to download `cssfamily` plugin from SonarCube server.

[example](https://github.com/airbytehq/airbyte/runs/6811184918?check_suite_focus=true#step:4:6780)
```
11:15:19.068 INFO: Load plugins index
11:15:19.188 DEBUG: GET 200 http://10.1.0.67:22439/api/plugins/installed | time=120ms
11:15:19.242 INFO: Load plugins index (done) | time=174ms
11:15:19.245 DEBUG: Download plugin 'csharp' to '/opt/sonar-scanner/.sonar/_tmp/fileCache3039595501319349321.tmp'
11:15:19.383 DEBUG: GET 200 http://10.1.0.67:22439/api/plugins/download?plugin=csharp&acceptCompressions=pack200 | time=138ms
11:15:25.418 DEBUG: Download plugin 'cssfamily' to '/opt/sonar-scanner/.sonar/_tmp/fileCache17733311872250046992.tmp'
11:20:25.422 INFO: Load/download plugins (done) | time=306354ms
11:20:25.428 INFO: ------------------------------------------------------------------------
11:20:25.428 INFO: EXECUTION FAILURE
11:20:25.428 INFO: ------------------------------------------------------------------------
11:20:25.428 INFO: Total time: 5:41.160s
11:20:25.448 ERROR: Error during SonarScanner execution
11:20:25.448 INFO: Final Memory: 5M/20M
11:20:25.448 INFO: ------------------------------------------------------------------------
java.lang.IllegalStateException: Fail to request url: http://10.1.0.67:22439/api/plugins/download?plugin=cssfamily&acceptCompressions=pack200
```

We can see that SonarCube action could successfully download first plugin `csharp` but after that for some reason stuck on 2-nd plugin: `cssfamily`.

Using `wget` I can download `cssfamily` plugin successfully:

```
time wget 'http://192.168.88.44:14506/api/plugins/download?plugin=cssfamily&acceptCompressions=pack200'
Connecting to 192.168.88.44:14506 (192.168.88.44:14506)
saving to 'download?plugin=cssfamily&acceptCompressions=pack200'
download?plugin=cssf 100% |**********************************************************| 8113k  0:00:00 ETA
'download?plugin=cssfamily&acceptCompressions=pack200' saved

real	0m10.490s
user	0m0.000s
sys	0m0.073s
```

similar issue:
https://community.sonarsource.com/t/scanner-always-timeout-during-plugin-download/44291/9?utm_source=pocket_mylist

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by supertopher** [comment]
@grubberr did you wget that font from the VM itself?  I do worry there may be an outbound connection issues as I couldn't download packages to the instance

**Comment by grubberr** [comment]
@supertopher yes thanks for question, because I didn't explain clearly.
I did wget from the same docker container where sonarscanner java process was being launched
and what is important - wget worked OK

**Comment by f33r0** [comment]
Hello, we have some problem. 
Does anyone have a solution or workaround?

**Comment by evantahler** [comment]
We've removed the sonarscan/sonarcube workflow from the project via https://github.com/airbytehq/airbyte/pull/17609.  Can this be closed?
