### ISSUE TITLE
CDK did not filter `hapikey` secret from AirbyteTraceMessage

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#13644]
The following stack trace contained the `hapikey` secert.  It should have been filtered away by the `filter_secrets` method, but it wasn't.  Learn more here https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/utils/traced_exception.py#L65

```
403 Client Error: Forbidden for url: https://api.hubapi.com/crm/v3/objects/feedback_submissions?hapikey=blabla-blabla&limit=100&startTimestamp=1577836800000&endTimestamp=1654701268067&archived=false&associations=contacts&properties=hs_agent_email%2Chs_agent_id%2Chs_agent_name%2Chs_all_accessible_team_ids%2Chs_all_assigned_business_unit_ids%2Chs_all_owner_ids%2Chs_all_team_ids%2Chs_chatflow_name%2Chs_chatflow_object_id%2Chs_contact_id%2Chs_conversation_thread_id%2Chs_created_by_user_id%2Chs_createdate%2Chs_lastmodifieddate%2Chs_merged_object_ids%2Chs_object_id%2Chs_ticket_id%2Chs_ticket_owner_avatar_uri%2Chs_ticket_owner_id%2Chs_ticket_subject%2Chs_unique_creation_key%2Chs_updated_by_user_id%2Chs_user_ids_of_all_notification_followers%2Chs_user_ids_of_all_notification_unfollowers%2Chs_user_ids_of_all_owners%2Chubspot_owner_assigneddate%2Chubspot_owner_id%2Chubspot_team_id%2Chs_industry_standard_question_type%2Chs_sentiment%2Chs_survey_id%2Chs_survey_type%2Chs_survey_channel%2Chs_submission_timestamp%2Chs_value%2Chs_response_group%2Chs_content%2Chs_ingestion_id%2Chs_knowledge_article_id%2Chs_visitor_id%2Chs_engagement_id%2Chs_submission_url%2Chs_survey_name%2Chs_form_guid%2Chs_contact_email_rollup%2Chs_submission_name io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
```

**Comment by ChristopheDuong** [comment]
It's been showing up in the logs here: https://cloud.airbyte.io/workspaces/220a6bab-5b4b-45f7-ba03-4d0dc6cedb73/connections/6613f0f8-c794-4307-b8b7-1e000f9c155e/status

**Comment by evantahler** [comment]
@sherifnada adding to the top of the backlog FYI.

**Comment by pedroslopez** [comment]
It looks like this is because our `get_secrets` helper method (see below) is not correctly grabbing all secrets from the spec, specifically when the secrets are in nested properties (hubspot uses a `credentials` block with a `oneOf`)

https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-cdk/python/airbyte_cdk/utils/airbyte_secrets_utils.py#L14-L22

**Comment by evantahler** [comment]
For this project, we don't need to update all users of the CDK, just Hubspot - Hubspot is unique because the APIKey is in the URL.
