### ISSUE TITLE
Facebook marketing API  "You are calling a deprecated version of the Ads API. Please update to the latest version: v14.0"

### ISSUE THREAD

**Issue by bigdatawonders** [airbytehq/airbyte#13643]
## Environment
- **Airbyte version**:  example is 0.35.10-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: 0.2.50 Facebook Marketing
- **Destination Connector and version**: 0.3.1 S3
- 
- When Syncing or testing I get this error message 
"You are calling a deprecated version of the Ads API. Please update to the latest version: v14.0"

## Current Behavior
*When Syncing or testing I get this error message 
"You are calling a deprecated version of the Ads API. Please update to the latest version: v14.0"*

## Expected Behavior
I expect there should be no errors and data retrieved from API.

**Comment by bigdatawonders** [comment]
This is quite urgent since I cannot retrieve clients facebook data anymore.

**Comment by bigdatawonders** [comment]
I know that Facebook Marketing API is GA connector so I hope it will get fixed very soon. Thank you for your amazing tool!

**Comment by marcosmarxm** [comment]
We're waiting https://github.com/facebook/facebook-python-business-sdk/pull/612 OR Facebook update the package with latest version.

**Comment by Qaisarg** [comment]
@cminnov  Thanks for sharing this but in the Advanced Settings of the App, Facebook is now only showing the v14 it is not showing v13.

**Comment by Qaisarg** [comment]
Is there any other solution available right now to be used in Air byte Facebook (Open Source) connectors to avoid this error. I am using Airbyte using docker on Google Cloud @marcosmarxm

**Comment by cminnov** [comment]
> @cminnov Thanks for sharing this but in the Advanced Settings of the App, Facebook is now only showing the v14 it is not showing v13.

If you start by selecting v13 on the left selection "Upgrade all calls" then save, v13 will then appear on the right selection "Upgrade Calls for App Roles". At least on my end...

Hope this can temporarily solve your issue.

**Comment by riceyrice** [comment]
Building on @terrazasrj suggestion I did this in `__init__py` of my module which is executed before it imports from `facebook_business`
```
from facebook_business import apiconfig
apiconfig.ads_api_config['API_VERSION'] = 'v14.0'
for mod in list(sys.modules):
    if mod.startswith('facebook_business') and mod != 'facebook_business.apiconfig':
        del sys.modules[mod]
```
Obviously having a real v14 client would be much better!

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 05:36:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">thank you after i follow those steps and i got this error <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a></p>
<p dir="auto">Response:<br>
{<br>
“error”: {<br>
“message”: “(<span><a href="/agent/tickets/17" target="_blank" rel="ticket">#17</a></span>) User request limit reached”,<br>
“type”: “OAuthException”,<br>
“is_transient”: true,<br>
“code”: 17,<br>
“error_subcode”: 2446079,<br>
“fbtrace_id”: “AKdqUYWyXuOh5TPVezTx0Vv”<br>
}</p> 

 [<a href="https://discuss.airbyte.io/t/facebook-api-error-version/1590/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 12:00:*

<blockquote><div class="zd-comment" dir="auto">Did you follow Airbyte documentation to increase the quota?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-29 at 06:43:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">sure i already have an advanced access, but i use my token to get 3 facebookads account and get ads, ad_insight and campaign data in each</p> 

 [<a href="https://discuss.airbyte.io/t/facebook-api-error-version/1590/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-29 at 11:19:*

<blockquote><div class="zd-comment" dir="auto">Well, you need to ask Meta Support if they can increase even more your quota. This error is throw by their side and not Airbyte.<br></div></blockquote>

**Comment by juferafo** [comment]
Hello. I am also facing this issue. Are there any news on this topic?

Thanks!

**Comment by bigdatawonders** [comment]
I cannot create and test new connectors meanwhile, when I do test I get depreciated version error... Old connectors are working fine.

**Comment by OhnoOhnoOhnononononoo** [comment]
Same problem here, I can't test my new connection.

**Comment by theRoundGreek** [comment]
> API_VERSION

How would i go about implementing this since api v.15 is required for new apps. New to airbyte and don't use python so i'm kinda grasping at straws here. Any help would be greatly appreciated

**Comment by haranesh** [comment]
Same issue for me now for v17.0
