### ISSUE TITLE
Backward compatibility check when publish connector change

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#13656]
## Tell us about the problem you're trying to solve
Today Airbyte updates connector version if there is a patch update when the user upgrade Airbyte version automatically.
IF it's a patch version we consider there isn't a backward compatibility.

A patch update MUST NOT add a backward compatibility. This is a complex topic, but our rule of thumb is if there is a change in specification (spec.yaml) there is a backward compatibility.  

The problem: this is only writing in our docs which allow publish connectors with changes in spec.yaml as patch version.

Upgrading Airbyte should not break my current running connections.

## Describe the solution you’d like

A CI script that blocks publish a patch version if there is a spec.yaml change.

A better solution: runs a previous version, update connector and run again
The best solution: Probably something more manageable with the future cassete tests :) 

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by girarda** [comment]
done. thanks @alafanechere !
