### ISSUE TITLE
Source Salesloft: OAuth Tokens can expire during a rate limit retry loop

### ISSUE THREAD

**Issue by joshzana** [airbytehq/airbyte#13660]
## Environment
- **Airbyte version**:  0.39.17-alpha
- **OS Version / Instance**: Ubuntu 20.04 , AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Salesloft, 0.1.3 
- **Destination Connector and version**: Snowflake 0.1.10
- **Step where error happened**: Setup new connection

## Current Behavior
Salesloft uses very short lived access tokens with only 2 hour expiration.  This means that a long ingestion might require refreshing the token mid-sync.  The way that Airbyte determines when an access token needs to be refreshed is to take the "expires_in" response and wait until that much time has elapsed before refreshing.  While this check happens on every new request, it does NOT happen when retrying due to rate limit responses.  As such, if a token is about to expire and we retry, it will be invalid and fail the run.  I was able to reproduce this with the short-lived Salesloft tokens, but it is also possible with longer-lived tokens as long as the timing works out badly.

## Expected Behavior
The expiration detection should either refresh at a percentage of "expires_in" or should refresh with a buffer of a few minutes.  A pattern I have seen is refresh at the "half-life" of the token.

## Logs
[logs-2908.txt](https://github.com/airbytehq/airbyte/files/8873690/logs-2908.txt)

## Steps to Reproduce
1. Have a short lived access token that expires during a sync
2. Have some requests that retry due to rate limit

## Are you willing to submit a PR?
Yes as long as the maintainers can suggest the refresh behavior they would like.

**Comment by marcosmarxm** [comment]
Thanks for suggesting this @joshzana I added this to connector team backlog

**Comment by yghelmut** [comment]
I feel I'm stuck with the refresh token. I added the ip address of my docker to the list of redirect URIs but always get this error:
Exception('Error while refreshing access token: 401 Client Error: Unauthorized for url: https://accounts.salesloft.com/oauth/token')

is this linked ?

**Comment by marcosmarxm** [comment]
Did you check Salesloft to see how overcome the 401 error?

**Comment by Logicoeur** [comment]
I've encountered this but with Destination-Snowflake + Oauth2.0. I even bumped the connectionTimeout to 300,000ms from the default 30,000ms. It still fails to refresh the accessToken once it gets into a retry loop. My particular loop is the 3x retry for the worker when a sync fails. On the third it just exists with `Oauth access token expired `

**Comment by davydov-d** [comment]
Implemented [here](https://github.com/airbytehq/airbyte/pull/23815) and the CDK version upgrade was made [here](https://github.com/airbytehq/airbyte/pull/22893)
