### ISSUE TITLE
Document how to extract latest snapshot from the append table

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1366]
With the release of incremental updates, I want to know how I can manually create a view with only the current state of the data.

Assume I am using DBT.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368137161123) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Once the user is able to define a primary key for a table, we can provide a DBT macro to generate the latest snapshots of tables

**Comment by avaidyanatha** [comment]
@ChristopheDuong Along with our conversation, can we close this out now?

**Comment by ChristopheDuong** [comment]
yes, the feature is now available in airbyte, related doc could be: https://docs.airbyte.io/understanding-airbyte/connections/incremental-deduped-history
