### ISSUE TITLE
Source Asana: Bad request (400) when syncing stories stream

### ISSUE THREAD

**Issue by isaacharrisholt** [airbytehq/airbyte#13676]
## Environment
- **Airbyte version**:  0.35.47-alpha
- **OS Version / Instance**: Amazon Linux 5.10.102-99.473.amzn2.x86_64, AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Asana 0.1.3
- **Destination Connector and version**: BigQuery 1.1.6
- **Step where error happened**: Sync job

## Current Behavior
When syncing the stories stream, an error 400 is returned by Asana, causing the sync to fail.

## Expected Behavior
The sync should complete normally.

## Logs
[logs-3934.txt](https://github.com/airbytehq/airbyte/files/8878209/logs-3934.txt)

## Steps to Reproduce
1. Set up a connection between Asana and BigQuery (Asana validated with API token)
2. Select all streams for sync with `Full refresh | Overwrite`
3. Select `Normalized tabular data` for transformation settings

## Are you willing to submit a PR?
Not in the near future.

**Comment by alafanechere** [comment]
Thank you @[isaacharrisholt](https://github.com/isaacharrisholt) , I triaged the issue so that it reaches our connector team backlog.

**Comment by isaacharrisholt** [comment]
This is still happening as of version 0.1.4 of the connector

**Comment by YowanR** [comment]
@isaacharrisholt Is it the exact same issue as before? @lazebnyi Can you assign someone to take a look, please?

**Comment by isaacharrisholt** [comment]
Yep, same as before @YowanR

**Comment by YowanR** [comment]
@lazebnyi Just FYI here
