### ISSUE TITLE
Source zendesk support: invalid literal for int() with base 10: '50, 47'

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13673]
Is this your first time deploying Airbyte?: No
OS Version / Instance: Debian
Memory / Disk: 60GB
Deployment: Compute Engine
Airbyte Version: 0.39.8-alpha
Source name/version: Tested all versions >= airbyte/source-zendesk-support:0.2.5
Destination name/version: BigQuery
Step: While syncing satisfaction_ratings from zendesk, this error appears.
022-06-08 14:09:13 source > invalid literal for int() with base 10: '50, 47'

[logs-1320.txt](https://discuss.airbyte.io/uploads/short-url/ezo4u2PIAA0T57spDR6x2sEaaob.txt) (303.2 KB)

https://discuss.airbyte.io/t/zendesk-connector-failing/1353/1

**Comment by grubberr** [comment]
hm strange I could not reproduce but anyway I will improve parser to handle such cases 

debug logs:

```
(Pdb++) response.request.url
'https://d3v-airbyte.zendesk.com/api/v2/satisfaction_ratings?page=1&per_page=100&sort_by=asc&start_time=1577836800'

(Pdb++) response.status_code
429

(Pdb++) print("\n".join([f"{k}: {v}" for k, v in response.headers.items()]))
Date: Fri, 24 Jun 2022 06:24:50 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Retry-After: 49
Cache-Control: no-cache
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=wTFHLc%2FQhLC%2FzC3I4NkpeTCk%2Bd3d7unoyslhAB%2FSkq5rTh%2BX6j%2BIpwrfvEdR24PChuVl5Jnf8rstoJw3717Qshpe%2FBbJjv%2BzuiChwls%2FMHDNgf6qV%2FFv%2F%2Ft7%2FzAVShLXeexR4Bb4rfS4"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
Vary: Accept-Encoding
Server: cloudflare
CF-RAY: 720361fa9de92492-KBP
```
