### ISSUE TITLE
Mssql CDC connector hangs for long time

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13678]
Fails with “Caused by: java.net.SocketException: No route to host”

Attaching the logs here 
[logs-5014.txt](https://github.com/airbytehq/airbyte/files/8880470/logs-5014.txt)

https://discuss.airbyte.io/t/mssql-cdc-connector-hangs-for-long-time/1323/9

**Comment by marcosmarxm** [comment]
I can't download the log file please check it. @harshithmullapudi please use the template to keep easy to understand what you're doing. This came from Discourse or Slack?

**Comment by harshithmullapudi** [comment]
Hey @marcosmarxm give me some time like 30 minutes. I have been debugging this issue since I created 😢. I have replicated this issue in 0.36 but I am not seeing this in 0.39. If I confirm this I will close otherwise I will update the issue with respective information on which instance I am able to replicate.

**Comment by harshithmullapudi** [comment]
Closing this as I have not seen this in 0.39.0 and 0.38.0

**Comment by luke-oa** [comment]
Opened up a discussion of this [here](https://github.com/airbytehq/airbyte/discussions/28830) as the "hanging" issue is happening in `0.50.6`
