### ISSUE TITLE
Image pull policy not applied to replication orchestrator pod

### ISSUE THREAD

**Issue by gfeldman** [airbytehq/airbyte#13686]
## Environment
- **Airbyte version**:  0.39.15-alpha
- **OS Version / Instance**: kubernetes/docker
- **Deployment**: kubernetes
- **Step where error happened**: sync job

## Current Behavior
Image pull policy is not applied to job orchestrator [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/java/io/airbyte/workers/process/AsyncOrchestratorPodProcess.java#L283-L290)

## Expected Behavior
Image pull policy for the main container should be applied.

## Steps to Reproduce
1. trigger a job
2. check the pull policy by inspecting the container orchestrator pod

## Are you willing to submit a PR?
yes

**Comment by davinchia** [comment]
@gfeldman can we close this?

**Comment by evantahler** [comment]
Closing due to lack of response.  We can re-open if needed.
