### ISSUE TITLE
Adding a namespace prefix to datadog metrics

### ISSUE THREAD

**Issue by gfeldman** [airbytehq/airbyte#13684]
## Tell us about the problem you're trying to solve
When sending metrics to datadog, the metrics name start with the worker component. It would be easy enough to add a configuration to add a static prefix to the application name to separate metrics from different airbyte instances going to the same datadog (e.g. airbyte.prod. and airbyte.dev.)

## Describe the solution you’d like
Add an environment variable config like `DD_NAMESPACE_PREFIX` to allow users to set a static prefix that will be set in the datadog metrics client.

## Describe the alternative you’ve considered or used
I considered using a datadog mapper but this seems much simpler 

## Additional context
<img width="409" alt="Screen Shot 2022-06-10 at 10 36 30 AM" src="https://user-images.githubusercontent.com/4413427/173089301-76b3597e-565c-45db-8dd9-5fb1bb7e0309.png">

## Are you willing to submit a PR?
yes.

**Comment by harshithmullapudi** [comment]
Great. @gfeldman let us know if any help is needed here.

**Comment by gfeldman** [comment]
added a pr https://github.com/airbytehq/airbyte/pull/14591

**Comment by harshithmullapudi** [comment]
That's great 🔥

**Comment by evantahler** [comment]
Will be closed by https://github.com/airbytehq/airbyte/pull/14623
