### ISSUE TITLE
Docker Images should not run under root User

### ISSUE THREAD

**Issue by c-thiel** [airbytehq/airbyte#13714]
## Tell us about the problem you're trying to solve
Currently the Docker Images, as they stem from openjdk, run under the root user per-default.
Especially on Kubernetes this is a security issue. Typically in larger deployments it is forbidden to run pods with the root user.

## Describe the solution you’d like
All Dockerimages should run under a non-root user by default.

## Describe the alternative you’ve considered or used
None

## Are you willing to submit a PR?
Generally yes, but currently we don't have the time for it.

**Comment by harshithmullapudi** [comment]
Hey I think this is duplicate of https://github.com/airbytehq/airbyte/issues/11772
