### ISSUE TITLE
Bug: latest version of helm chart does not work

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#13711]
## Environment
- **Airbyte version**:  0.39.5-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: k8s, helm, kustomize
- **Source Connector and version**: not applicable
- **Destination Connector and version**: (not applicable
- **Step where error happened**: Deploy, Upgrade Airbyte

## Current Behavior
When trying to update to the latest version `v0.39.17-alpha` I am getting an error.

## Expected Behavior
Update should work. This always worked with previous versions, so I suspect something change in the recent version

## Logs
```
Last Helm logs:

preparing upgrade for airbyte
resetting values to the chart's original version
  Warning  error  2m18s (x418 over 4d14h)  helm-controller  reconciliation failed: Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 58: mapping key "resources" already defined at line 52
```

## Steps to Reproduce
(this is specific to our setup)
1. we update the version in out gitops repo
2. flux picks it up
3. update

## Are you willing to submit a PR?
no

**Comment by alafanechere** [comment]
Hey @jan-benisek I think this was fixed by https://github.com/airbytehq/airbyte/pull/13816 
Could you please reopen the issue if you are still facing the error after pulling the latest chart?

**Comment by jan-benisek** [comment]
All works now, thank you! 🙏
