### ISSUE TITLE
🐛 Postgres Source: `java.time.format.DateTimeParseException: Text '2022-06-02T21:08:15.122472Z' could not be parsed`

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#13743]
@VitaliiMaltsev this is a continuation of the work you did in https://github.com/airbytehq/airbyte/pull/13655. The new error is :
`java.time.format.DateTimeParseException: Text '2022-06-02T21:08:15.122472Z' could not be parsed`

You can see more details in this oncall issue: https://github.com/airbytehq/oncall/issues/229

**Comment by grishick** [comment]
`java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2055), java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1954), java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494), java.base/java.time.LocalDateTime.parse(LocalDateTime.java:479), io.airbyte.integrations.source.postgres.PostgresSourceOperations.setTimestamp(PostgresSourceOperations.java:121), io.airbyte.integrations.source.postgres.PostgresSourceOperations.setStatementField(PostgresSourceOperations.java:90), io.airbyte.integrations.source.postgres.PostgresSourceOperations.setStatementField(PostgresSourceOperations.java:39), io.airbyte.integrations.source.jdbc.AbstractJdbcSource.lambda$queryTableIncremental$16(AbstractJdbcSource.java:281), io.airbyte.db.jdbc.StreamingJdbcDatabase.unsafeQuery(StreamingJdbcDatabase.java:62), io.airbyte.integrations.source.jdbc.AbstractJdbcSource.lambda$queryTableIncremental$17(AbstractJdbcSource.java:271), io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:37), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:48), io.airbyte.integrations.source.relationaldb.StateDecoratingIterator.computeNext(StateDecoratingIterator.java:18), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:46), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38), com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146), com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141), java.base/java.util.Iterator.forEachRemaining(Iterator.java:132), `

**Comment by grishick** [comment]
The problem seems to be that fields in the catalog are defined as `TIMESTAMP`, which the connector assumes as not having a timezone. However, the actual data type is `timestamptz`. This is likely to be limited to connections created with older versions of the connector.

**Comment by grishick** [comment]
I think the fix is straightfoward. Going to attempt it now.

**Comment by gabrielalmeida** [comment]
> The problem seems to be that fields in the catalog are defined as TIMESTAMP, which the connector assumes as not having a timezone. However, the actual data type is timestamptz

FYI A similar issue regarding `timestamptz` was happening on a Postgres source, I've updated Airbyte to `0.39.18-alpha` when this fix landed and it was still happening:

```
2022-06-15 19:10:31 normalization > 19:09:57.332567 [debug] [Thread-7  ]: Database Error in model mb_compliance_messages_scd (models/generated/airbyte_incremental/scd/public/mb_compliance_messages_scd.sql)
2022-06-15 19:10:31 normalization >   Invalid timestamp: '2022-04-05T16:07Z'
2022-06-15 19:10:31 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/public/mb_compliance_messages_scd.sql
2022-06-15 19:10:31 normalization > 19:09:57.333215 [error] [Thread-7  ]: 27 of 41 ERROR creating incremental model public.mb_compliance_messages_scd............................................. [ERROR in 7.60s]
2022-06-15 19:10:31 normalization > 19:09:57.334234 [debug] [Thread-7  ]: Finished running node model.airbyte_utils.mb_compliance_messages_scd
```

```
Airbyte Version: 0.39.18-alpha
Source: Postgres (0.4.24)
Destination: BigQuery (1.1.8)
```

> This is likely to be limited to connections created with older versions of the connector.

Indeed, recreating the connector under `0.39.18-alpha` fixed this.
