### ISSUE TITLE
Monorepo Python Development is shown twice in navigation links

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#13750]
Monorepo Python development is shown twice in the navigation of our docs - [Monorepo Python Development](https://docs.airbyte.com/contributing-to-airbyte/monorepo-python-development) 

<img width="308" alt="Screen Shot 2022-06-14 at 10 50 01" src="https://user-images.githubusercontent.com/2364589/173536280-59c3cc61-ce3b-4219-8bca-8efe9503025c.png">

**Comment by Rajakavitha1** [comment]
Hi @alexander-marquardt !!! I just checked the documentation on the [website](https://docs.airbyte.com/contributing-to-airbyte/monorepo-python-development/). The left nav seems to have just one occurrence of Monorepo Python Development.
<img width="301" alt="Screenshot 2022-06-18 at 8 29 14 PM" src="https://user-images.githubusercontent.com/37059749/174444206-0ad3dae9-2983-4b98-8830-db23f69d43a6.png">
