### ISSUE TITLE
Facebook Pages calls deprecated feature 'nativeoffers'

### ISSUE THREAD

**Issue by cminnov** [airbytehq/airbyte#13756]
## Environment
- **Airbyte version**:  0.38.2-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker
- **Source Connector and version**: Facebook Pages 0.1.6
- **Step where error happened**: Connecting to new source

## Current Behavior
Currently getting an error while trying to connect to Facebook Graph API:

> The connection tests failed.
"HTTPError('400 Client Error: Bad Request for url: https://graph.facebook.com/v12.0/*****************?access_token=******************&fields=id%2Cabout%2Cad_campaign%2Caffiliation%2Capp_id%2Cartists_we_like%2Cattire%2Cawards%2Cband_interests%2Cband_members%2Cbio%2Cbirthday%2Cbooking_agent%2Cbuilt%2Ccan_checkin%2Ccan_post%2Ccategory%2Ccategory_list%2Ccheckins%2Ccompany_overview%2Cconnected_page_backed_instagram_account%2Ccontact_address%2Ccountry_page_likes%2Ccover%2Cculinary_team%2Ccurrent_location%2Cdelivery_and_pickup_option_info%2Cdescription%2Cdescription_html%2Cdifferently_open_offerings%2Cdirected_by%2Cdisplay_subtext%2Cdisplayed_message_response_time%2Cemails%2Cengagement%2Cfan_count%2Cfeatured_video%2Cfeatures%2Cfollowers_count%2Cfood_styles%2Cfounded%2Cgeneral_info%2Cgeneral_manager%2Cgenre%2Cglobal_brand_page_name%2Cglobal_brand_root_id%2Chas_added_app%2Chas_transitioned_to_new_page_experience%2Chas_whatsapp_business_number%2Chas_whatsapp_number%2Chometown%2Chours%2Cimpressum%2Cinfluences%2Cis_always_open%2Cis_chain%2Cis_community_page%2Cis_eligible_for_branded_content%2Cis_messenger_bot_get_started_enabled%2Cis_messenger_platform_bot%2Cis_owned%2Cis_permanently_closed%2Cis_published%2Cis_unclaimed%2Cis_webhooks_subscribed%2Cleadgen_tos_acceptance_time%2Cleadgen_tos_accepted%2Cleadgen_tos_accepting_user%2Clink%2Clocation%2Cmembers%2Cmerchant_review_status%2Cmessenger_ads_default_icebreakers%2Cmessenger_ads_default_page_welcome_message%2Cmessenger_ads_default_quick_replies%2Cmessenger_ads_quick_replies_type%2Cmission%2Cmpg%2Cname%2Cname_with_location_descriptor%2Cnetwork%2Cnew_like_count%2Coffer_eligible%2Coverall_star_rating%2Cpage_token%2Cparking%2Cpayment_options%2Cpersonal_info%2Cpersonal_interests%2Cpharma_safety_info%2Cphone%2Cpickup_options%2Cplace_type%2Cplot_outline%2Cpreferred_audience%2Cpress_contact%2Cprice_range%2Cprivacy_info_url%2Cproduced_by%2Cproducts%2Cpromotion_eligible%2Cpromotion_ineligible_reason%2Cpublic_transit%2Crating_count%2Crecord_label%2Crelease_date%2Crestaurant_services%2Crestaurant_specialties%2Cschedule%2Cscreenplay_by%2Cseason%2Csingle_line_address%2Cstarring%2Cstart_info%2Cstore_code%2Cstore_location_descriptor%2Cstore_number%2Cstudio%2Csupports_donate_button_in_live_video%2Ctalking_about_count%2Ctemporary_status%2Cunread_message_count%2Cunread_notif_count%2Cunseen_message_count%2Cusername%2Cverification_status%2Cvoip_info%2Cwebsite%2Cwere_here_count%2Cwhatsapp_number%2Cwritten_by%2Cagencies%2Calbums%2Cblocked%2Ccall_to_actions%2Ccanvas_elements%2Ccommerce_merchant_settings%2Cevents%2Cfeed%2Cglobal_brand_children%2Cgroups%2Cimage_copyrights%2Cindexed_videos%2Cinstagram_accounts%2Clikes%2Clive_videos%2Clocations%2Cnativeoffers%2Cpage_backed_instagram_accounts%2Cphotos%2Cposts%2Cproduct_catalogs%2Cpublished_posts%2Cratings%2Croles%2Crtb_dynamic_posts%2Cscheduled_posts%2Csettings%2Ctabs%2Ctagged%2Cvideo_lists%2Cvideos%2Cvisitor_posts')"

## Expected Behavior
No error. After trying the request in the graph API explorer, I was able to get it to work by removing the "nativeoffers" part. It is a deprecated feature that stopped working in sept 2021 for v11+ API. Therefore it should be removed from the request. 

https://developers.facebook.com/docs/graph-api/reference/page/nativeoffers/

## Steps to Reproduce
1. Create FB app
2. Generate access token with all permissions
3. Create new FB page source

## Are you willing to submit a PR?
Don't know Python, so not for now.

**Comment by marcosmarxm** [comment]
It's not possible to test because Airbyte integration account is not creating a new connector, see issue #9349

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1996](https://airbyte7538.zendesk.com/agent/tickets/1996) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-08-18 at 17:56:*

<blockquote><div class="zd-comment" dir="auto">Hey @v_koppen, I think is related to this issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/13756">https://github.com/airbytehq/airbyte/issues/13756</a>.<br>&nbsp;<br>Would you be able to post any AIrbyte server logs?&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-19 at 09:35:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thank you for prompt response.<br>
Regarding the issue you linked, I tested the http request in the Graph API Explorer and get an error related to the nativeoffers part.<br>
However, after removing it I still get an error about missing permissions:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">{
  "error": {
    "message": "(#10) This endpoint requires the 'pages_manage_ads' permission or the 'Page Public Content Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages and https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS for details.",
    "type": "OAuthException",
    "code": 10,
    "fbtrace_id": "AELULZNg3luUmUH7Km3HWjT"
  }
}
</code></pre>
<p dir="auto">This was the original Airbyte log:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">2022-08-19 09:09:59 INFO i.a.w.t.TemporalAttemptExecution(get):105 - Docker volume job log path: /tmp/workspace/d5f62786-3a2d-404a-8c1d-a978a9b8f003/0/logs.log

2022-08-19 09:09:59 INFO i.a.w.t.TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.39.42-alpha

2022-08-19 09:09:59 INFO i.a.c.i.LineGobbler(voidCall):82 - Checking if airbyte/source-facebook-pages:0.1.6 exists...

2022-08-19 09:09:59 INFO i.a.c.i.LineGobbler(voidCall):82 - airbyte/source-facebook-pages:0.1.6 was found locally.

2022-08-19 09:09:59 INFO i.a.w.p.DockerProcessFactory(create):108 - Creating docker job ID: d5f62786-3a2d-404a-8c1d-a978a9b8f003

2022-08-19 09:09:59 INFO i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/d5f62786-3a2d-404a-8c1d-a978a9b8f003/0 --log-driver none --name source-facebook-pages-check-d5f62786-3a2d-404a-8c1d-a978a9b8f003-0-segey --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=false -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_CONNECTOR_IMAGE=airbyte/source-facebook-pages:0.1.6 -e WORKER_JOB_ATTEMPT=0 -e AIRBYTE_VERSION=0.39.42-alpha -e WORKER_JOB_ID=d5f62786-3a2d-404a-8c1d-a978a9b8f003 airbyte/source-facebook-pages:0.1.6 check --config source_config.json

2022-08-19 09:10:00 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):95 - Check failed

2022-08-19 09:10:01 INFO i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...
</code></pre> 

 [<a href="https://discuss.airbyte.io/t/source-facebook-pages-http-error-400/2302/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by keedle** [comment]
Sorry is there any progress on this one @marcosmarxm? As v12 is now depricated :(

**Comment by sajarin** [comment]
@keedle, there's a linked issue/pr that fixes this issue but we're currently blocked because of permissions associated with our integration account. Except an update by the end of the week, thanks for being patient in the meantime.

**Comment by adriennevermorel** [comment]
@sajarin do you have an update on this issue?

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1996](https://airbyte7538.zendesk.com/agent/tickets/1996) has been linked to this issue.

**Comment by sajarin** [comment]
@adriennevermorel unfortunately not, we're still blocked due to our integration account. Will try initiating the conversation again, thanks for asking!

**Comment by artem1205** [comment]
fixed while migrating to Low-code
