### ISSUE TITLE
Create a single SideBar (main menu) component

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#13766]
There's a lot of repeated code between the cloud package [SideBar](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/packages/cloud/views/layout/SideBar/SideBar.tsx) and the [OSS SideBar](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/layout/SideBar/SideBar.tsx).  It makes updates a more cumbersome and prone to human error.

These can be combined such that cloud is able to use the OSS sidebar and pass in the additional components it needs rendered.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
