### ISSUE TITLE
Finalize PRD for Connector Service

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#13760]
Evan worked on the first PRD iteration here: 
https://docs.google.com/document/d/1rZR9fAenpfVze2HIYB3acxPLurLLCoaH7joQ5oAJ1jM/edit#

the next step is to have Pedro revisit this and: 

1. ratify the requirements
2. create a release timeline for the different requirements (q3 vs. beyond)
3. next step would be to start creating the technical design

**Comment by pedroslopez** [comment]
Roadmap doc added https://docs.google.com/document/d/1U9k7GWJSqY3TPrkN3WDcZupEewW8Uq0V2pjBL1vXVU0/edit#
