### ISSUE TITLE
Freshdesk connection does not sync `Message: It should be a valid date in the 'combined date and time ISO8601' format`

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#13785]
## Environment
- **Airbyte version**:  0.39.9-alpha
- **OS Version / Instance**: AWS EKS
- **Deployment**: k8s, helm, kustomize
- **Source Connector and version**: Freshdesk 0.3.1
- **Destination Connector and version**: s3 0.3.7
- **Step where error happened**: Sync job

## Current Behavior
Data from Freshdesk does not sync.

## Expected Behavior
Sync should work

## Logs
![Screenshot 2022-06-15 at 07 07 54](https://user-images.githubusercontent.com/91880749/173741002-3be31820-044e-49ca-8aba-7d1d7c9d7891.png)

[logs-167.txt](https://github.com/airbytehq/airbyte/files/8905838/logs-167.txt)

## Steps to Reproduce
1. set up freshdesk connection (API key, no start date, no request limit)
2. set up destination - s3, as JSON, gzip
3. run the sync - `full refresh | append`, stream `tickets`

**Comment by harshithmullapudi** [comment]
duplicate for [#13328](https://github.com/airbytehq/airbyte/issues/13328)
