### ISSUE TITLE
Support incremetal sync for Hubspot source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1378]
## Tell us about the problem you're trying to solve
Before beginning implementation for this ticket, please first see the Gist describing how to [support incremental sync for singer sources](https://gist.github.com/sherifnada/6970d73d93db52451b0b39fe59002566) in Airbyte.

**Comment by yevhenii-ldv** [comment]
Hello, @sherifnada
I have investigated this issue and found that there is already an incremental implementation for the Hubspot Source, it was implemented in this PR: [airbytehq/airbyte#1290](https://github.com/airbytehq/airbyte/pull/1290)

Modified source file for the Hubspot Singer Source is [here](https://github.com/airbytehq/airbyte/pull/1290/files?file-filters%5B%5D=.java&file-filters%5B%5D=.json&file-filters%5B%5D=.md&file-filters%5B%5D=.py&file-filters%5B%5D=.sh&file-filters%5B%5D=.test&file-filters%5B%5D=No+extension#diff-0c284d213e9eaebdc866679afe2708ce7e40e913598c1f9db8f188b13a72cca4)

I doublechecked manually by running the `read` method according to [here](https://gist.github.com/sherifnada/6970d73d93db52451b0b39fe59002566#testing) and the number of records with `--state` is less than without the `--state`.

The only thing missing is the configuration change for the next version of Dockerfile.
