### ISSUE TITLE
First build of idea tool

### ISSUE THREAD

**Issue by 2370131441** [airbytehq/airbyte#13789]
Gradle build dependency reports this error,the following is the error content:
Build file 'D:\workspace\brand\airbyte\airbyte-cdk\python\build.gradle' line: 3

An exception occurred applying plugin request [id: 'airbyte-docker']
> Failed to apply plugin 'airbyte-docker'.
   > A problem occurred starting process 'command 'docker''

**Comment by marcosmarxm** [comment]
You must use WSL2 to work with Airbyte on Windows.
