### ISSUE TITLE
Expand Sendgrid source support

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1380]
## Tell us about the problem you're trying to solve
Support the following entities from the sendgrid API. 

Contacts 
Global Suppressions
Suppression Groups
Suppression Group Members
Lists
Lists Recipients
Segments
Segment Recipients
Campaigns
Templates
Invalid Emails
Bounces
Blocks
Spam Reports
Campaigns

For this issue, we do not need to support incremental sync on these streams. We'll support incremental sync in the following ticket. (making 2 separate tickets just to break up the work)

Please make sure that: 
1. In the standard tests for this source, _every_ stream is tested (and that every stream outputs records) unless there is a rate limiting issue
2. you create fake data for every stream -- whoever is working on this issue, feel free to reach out to me if you need support

**Comment by yevhenii-ldv** [comment]
Some information on how working streams from Sendgrid:

Contacts - FULL REFRESH
Global Suppressions - FULL REFRESH
Suppression Groups - FULL REFRESH with pagination
Suppression Group Members - FULL REFRESH with pagination
Lists - FULL REFRESH with pagination
Segments - FULL REFRESH
Campaigns - FULL REFRESH
Templates - FULL REFRESH with pagination
Invalid Emails - Incremental with Pagination
Bounces - Incremental with Pagination
Blocks - Incremental with Pagination
Spam Reports - Incremental with Pagination
Stats Automation - FULL REFRESH with pagination
