### ISSUE TITLE
Introduce Databricks personal staging locations

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#13809]

**Comment by johnwasserman** [comment]
Hi @tuliren - hoping to clarify what this is covering. I have a prospect with Databricks hosted on Azure. Would an internal staging API allow them to stage their data in Blobstorage in this instance?

**Comment by tuliren** [comment]
@johnwasserman, sorry about the delayed reply.

> Would an internal staging API allow them to stage their data in Blobstorage in this instance?

The internal staging API won't help in the short term for two reasons:
1. As far as I know, the staging API is currently for S3 only.
2. This staging solution is in preview stage. So it is not generally available yet.

**Comment by evantahler** [comment]
Possibly closed by https://github.com/airbytehq/airbyte/pull/18032
