### ISSUE TITLE
Support incremental sync in Sendgrid

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1382]
## Tell us about the problem you're trying to solve
Blocked by #3255 
The end goal of this ticket is make the Sendgrid source support incremental sync on all streams which support it. 

Before beginning implementation we should: comment on this ticket noting which streams support incremental sync. 

## Acceptance Criteria
1. Sendgrid source supports incremental sync
1. docs are updated to indicate this
1. Use new standard test suite for testing

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368079125479) by [Unito](https://www.unito.io)

**Comment by yevhenii-ldv** [comment]
The following streams can sync incrementally: `Global Suppressions`, `Blocks`, `Bounces`, `Invalid Emails`, `Spam Reports `

**Comment by yevhenii-ldv** [comment]
The comment above is correct. I would like to add that out of 5 streams that can be increment, the data exists only for two (`Global Suppressions` and `Blocks`), and I do not know how to generate data for the remaining streams.

**Comment by sherifnada** [comment]
guesstimating 2 days to get this done atm

**Comment by sherifnada** [comment]
blocked on #3255
