### ISSUE TITLE
Normalization: Incremental update merges last batch of rows even if no inserts/updates happened in source.

### ISSUE THREAD

**Issue by jgrinaveckis** [airbytehq/airbyte#13838]
## Environment
- **Airbyte version**: 0.39.17
- **OS Version / Instance**: GCP e2
- **Deployment**: Docker
- **Source Connector and version**: MySQL 0.5.11
- **Destination Connector and version**: BigQuery 1.1.8
- **Step where error happened**: Sync job

## Current Behavior
Prepared MySQL -> BigQuery connector together with normalization and sync mode "Incremental + Dedup history". After couple of syncs noticed that more than expected rows were merged. After investigation found out that if for example one table from connector hasn't received any updates or any new rows and was still merging from previous incremental sync (identical _airbyte_emitted_at value for all rows). I believe that this situation comes from incremental strategy (airbyte-integrations/bases/base-normalization/dbt-project-template/macros/incremental.sql).
This line includes equals sign and then when normalising it takes previous rows which haven't changed.
```
cast({{ col_emitted_at }} as {{ type_timestamp_with_timezone() }}) >= (select max(cast({{ col_emitted_at }} as {{ type_timestamp_with_timezone() }})) from {{ tablename }}),
```

## Expected Behavior
It should take only new data, as any new data comes from _raw_* table where inserts/updates in source comes as new row.

## Steps to Reproduce
1. Create source/destination (MySQL/BigQuery).
2. Select sync mode "Incremental + Dedup history".
3. Sync connector couple of times.

## Are you willing to submit a PR?
I mean I could, but this is only removing one symbol :D

**Comment by alafanechere** [comment]
@jgrinaveckis thank you for reporting this.
Could you share an example with actual data and show an example of what you would expect? 
I'm not sure I totally understand the problem and what you mean by *merge*.

**Comment by jgrinaveckis** [comment]
Hey,
I'm attaching a screenshot where we can see that _airbyte_emitted_at has one (actually it's an initial date when this whole table was updated, because there aren't no updated/inserted values in source) and _airbyte_normalized_at has latest value. This is intended behaviour, but in every update it keeps taking latest batch from every table based on incremental strategy (see my comment above). For example: initial table update added 34 rows to table A and incremental update happens every hour. So it means that every hour those 34 rows are being picked up and normalised even though they shouldn't as we haven't got new entry in raw table
![Screenshot 2022-06-27 at 10 32 55](https://user-images.githubusercontent.com/23581589/175886473-620bb879-0ebb-4065-9ebb-44caa8a18465.png)

Sorry for not explaining _merge_. This is BigQuery specific statement which combines INSERT/UPDATE statements. I guess google has better explanation of this [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement)

**Comment by alafanechere** [comment]
@jgrinaveckis to reformulate: do you mean than normalization with Incremental Dedup history mode is updating records that were not modified in the latest sync, which is not exactly what is explained [here](https://docs.airbyte.com/understanding-airbyte/connections/incremental-deduped-history):
> Simply put, if you've synced a row before and it has since been updated, this mode will combine the two rows in the destination and use the updated data

This leads to `_airbyte_normalized_at` being always set *on all records* to the latest normalization run. 

From my understanding, it's causing overheads in the normalization process and more costs on BQ but it does not have an impact on the data correctness. Do you confirm?
I'm going to escalate this to our database team to make sure it's a bug and not something intended to cover an edge case.

**Comment by jgrinaveckis** [comment]
Yes, your explanation is on point. Correctness is not impacted, but every sync shows that tables merged x rows even though I know/see that no new/updated entries are in source tables.

**Comment by alafanechere** [comment]
@jgrinaveckis I think the `>=` was added for safety because we favor at least once delivery not to miss records. I think the problem you mention is only really impacting the second sync, but subsequent sync will have marginal overlap hence fewer BQ costs.

**Comment by philippeboyd** [comment]
@alafanechere any news on this?

we have the same kind of issue with Snowflake's normalization However we're not using `Incremental+ Dedup History`; we're simply doing a `Full Refresh - Append` and we do our snapshots later on with custom DBT.

We do a sync every hour at X:55; sync is quick and takes a couple of seconds; `_airbyte_normalized_at` **should not** be set 1 hour later

![image](https://user-images.githubusercontent.com/3239656/207101985-43cbbd42-bc65-420c-aab4-30e8b1d3c8f7.png)

For other records it works well

![image](https://user-images.githubusercontent.com/3239656/207102879-f47dc953-cd9f-4af9-8265-c06265250b15.png)

I'm trying to understand the problem behind this...

**Comment by marcosmarxm** [comment]
Normalization is a deprecated module and won't be updated anymore. @evantahler fyi
