### ISSUE TITLE
Source Greenhouse Full Stream Coverage

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1385]
Support the missing streams from Greenhouse: https://developers.greenhouse.io/harvest.html

Activity Feed
Approvals  
Education  
EEOC  
Email Templates 
Offices 
Prospect Pools  
Scheduled Interviews  
Tags  
Tracking Links  
User Permissions  
User Roles

**Comment by sarunaskas** [comment]
+1

@sherifnada wanted to highlight the importance of the `Activity Feed` endpoint missing. 

Without that endpoint we cannot capture a candidates movement across different stages: e.g. we can't know who and when completed application review or other steps that are not treated as interviews.

Would be great if you could increase the priority.

**Comment by sherifnada** [comment]
@sarunaskas would you be open to creating a PR to add this stream?

**Comment by itaseskii** [comment]
I'll claim this issue. :)

**Comment by misteryeo** [comment]
Update, @itaseskii will be starting on this this week. Depending on number of streams needing to implement, estimates around 2-3 days.

**Comment by sherifnada** [comment]
@misteryeo greenhouse has been migrated to low code -- is it intentional to still assign this issue to ivica?

**Comment by YowanR** [comment]
As discussed, keeping this assigned to @itaseskii.

**Comment by davydov-d** [comment]
hey @YowanR should this issue be a part of the "Certification to GA" Epic?

**Comment by YowanR** [comment]
@davydov-d It's not part of GA certification.

**Comment by YowanR** [comment]
hi @itaseskii, what's the latest on this, please?

**Comment by itaseskii** [comment]
hey @YowanR, the review is done. I'm still waiting for the credentials in order to run the integration tests :)

**Comment by YowanR** [comment]
Hi @itaseskii are we still blocked here? @sajarin can you put in the cred sharing request?

**Comment by itaseskii** [comment]
Hey @YowanR :wave:  I have never received the credentials in order to run the acceptance tests. It would be great If someone can provide me with them.

**Comment by YowanR** [comment]
I just put it in a request. You should receive the creds soon! cc @sajarin
