### ISSUE TITLE
Add Segment call for Connection Delete

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#13863]
We currently have Segment events for deleting sources and destinations, but we do not have one for the deletion of a connection. It should trigger any time a user deletes a connection (Connection > Settings > Delete Connection). 

We should create it according to the naming convention followed here: https://github.com/airbytehq/airbyte/issues/10954

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
