### ISSUE TITLE
Destination Redshift broken integration tests in the master branch

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#13875]
Integration tests are permanently failing on the normalization step
`Error: 2-06-14 11:56:07 normalization > 11:56:05.559977 [error] [MainThread]: Database Error in model array_test_1 (models/generated/airbyte_tables/integration_test_spvsd/array_test_1.sql)`
Please see https://github.com/airbytehq/airbyte/runs/6879607021?check_suite_focus=true

**Comment by bazarnov** [comment]
This PR should be related:
https://github.com/airbytehq/airbyte/commit/2daaf5b4c39976fa2d67c505d0216242492bc7c0
