### ISSUE TITLE
[EPIC] Source Okta to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#13880]
### According to [checklist](https://docs.google.com/spreadsheets/d/1TtUQ8ca6Al-AmH9xCp_mIzBhjM2FYPZwR1-ZmDimfQg/edit#gid=1820065035):

- MLP improvements:
    https://docs.google.com/document/d/1S37m8ebCWysEEKP5ZXPZ9-gjEdwWfcP2whZNAyJ8w5w/edit

- All outstanding bug reports blocking Beta:
   - [ ] 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by YiyangLi** [comment]
@igrankova Hi, this is Yiyang, I added 2 API streams to okta, and it reaches 100% in the source-acceptance-test. However, I am having a hard time to reach out people who can help me review the PRs. can you help? 

https://github.com/airbytehq/airbyte/pull/14380
https://github.com/airbytehq/airbyte/pull/14556

Thank you.

**Comment by igrankova** [comment]
Hi, @YiyangLi, asked our team for review.

**Comment by YowanR** [comment]
LGTM -- thanks!
