### ISSUE TITLE
Support all available entities in JIRA cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1389]
## Tell us about the problem you're trying to solve
Support the following streams in Jira on a full refresh basis: 

Application roles
Audit records
Avatars
Dashboards
Filters
Filter sharing
Group and user picker
Groups
Issues
Issue attachments
Issue comments
Issue comment properties
Issue fields
Issue field configurations
Issue custom field contexts
Issue custom field options
Issue custom field options (apps)
Issue links
Issue link types
Issue navigator settings
Issue notification schemes
Issue priorities
Issue properties
Issue remote links
Issue resolutions
Issue search
Issue security level
Issue security schemes
Issue types
Issue type schemes
Issue type screen schemes
Issue type properties
Issue votes
Issue watchers
Issue worklogs
Issue worklog properties
Jira expressions
Jira settings
JQL
Labels
Myself
Permissions
Permission schemes
Projects
Project avatars
Project categories
Project components
Project email
Project key and name validation
Project permission schemes
Project properties
Project roles
Project role actors
Project types
Project versions
Screens
Screen tabs
Screen tab fields
Screen schemes
Server info
Tasks
Time tracking
Users
User properties
User search
Webhooks
Workflows
Workflow transition rules
Workflow schemes
Workflow scheme project associations
Workflow scheme drafts
Workflow statuses
Workflow status categories
Workflow transition properties
App properties
Dynamic modules

FYI we already support some of these streams. 

Please make sure that:

1. In the standard tests for this source, every stream is tested (and that every stream outputs records) unless there is a rate limiting issue
1. you create fake data for every stream -- whoever is working on this issue, feel free to reach out to me if you need support

This is a humungous API, so you are encourages to break up this task into a few tickets e.g: first support all `Workflow`-related streams, then all `Project`-related streams, etc..

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368079337048) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
The estimate time to complete this task is 24h

**Comment by sherifnada** [comment]
blocked on #2100 and #2101

**Comment by estsauver** [comment]
One thing to know is that we saw different results for jira support projects from jira projects on singer taps with stitch, it might be worth testing against a support project as well. (I think if you get all of the above entities, it *should* pull jira support things as well.)

**Comment by sherifnada** [comment]
thanks for the pointer @estsauver!
