### ISSUE TITLE
Support incremental sync in JIRA cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1390]
Follow up to #1389 

There are a few parts to this: 

1. Identify which streams can sync incrementally, and which bookmark you'll be using
1. Update the catalog generated in `discover` to declare which streams sync incrementally
1. Implement the incremental sync process

To incrementally sync a child entity child entity (e.g: `/customers/{customer_id}/customer_events` ), we will probably need to do a "full read" of the parent entity (get all parents), then look for the child entities that have changed since the last time we read the child entities. For example: if we're syncing `/customers/{customer_id}/customer_events`  then we should read all customers, then for each customer, read all the events we haven't read since the last time we performed a sync. It's probably not practical to keep track of the last event we synced for _each_  customer, so it may make sense to keep track of a global cursor for all customer_events. For example, we may just have to remember that the largest `customer_event.updated_at` value we extracted last time a sync ran was `october 10`. In which case the next sync we read all customers, then for each customer extract all the events where `updated_at >= october 10`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368079337056) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
The estimate time to complete this task is 8h

**Comment by sherifnada** [comment]
blocked on #2100 and #2101

**Comment by sherifnada** [comment]
@vitaliizazmic can we have: 
* list of streams which support incremental
* brief description of how incremental will be supported (how does the JIRA API allow it? How will the code be structured to support it?)

**Comment by vitaliizazmic** [comment]
[Here](https://docs.google.com/spreadsheets/d/1Lasn1teEcZNb1a-HdRC3qso9D--BZO2kXyIBD2qOcXA/edit?usp=sharing) you can find list of all streams including new.  Most of them can't be synced incrementally and even don't have properties, which can be used as bookmark. Issue stream can be synced incrementally by using JQL. But I didn't find information if JQL can be used for syncing incrementally Issue-related streams. The estimate time to complete this task is 8h.

**Comment by brunoffaustino** [comment]
For our use case, for a possible migration to Airbyte, we also need the Jira Software connector to support incremental syncs.

**Comment by sherifnada** [comment]
@brunoffaustino this is a WIP that was put on a hold temporarily. We'll resume work on this soon.

**Comment by brunoffaustino** [comment]
Is it done @sherifnada ? 🙏🏻

**Comment by sherifnada** [comment]
yes! Please let us know if you face any issues
