### ISSUE TITLE
Postgres Source Crash: TIMEOUT_TYPE_HEARTBEAT

### ISSUE THREAD

**Issue by bleonard** [airbytehq/airbyte#13906]
Seen 7 instances of similar crash this month.
```
"java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
 io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
 message='activity timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT
 Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 30009ms."
```

More details on the workspaces here: https://docs.google.com/spreadsheets/d/1ja8deCtFHtFVP3QrWELsMpVCMfPB1kz0QfLG1szns1I/edit#gid=1732290093

**Comment by qisaw** [comment]
I'm currentling running up against this exact error

**Comment by peter279k** [comment]
I also got the same issue using the source CSV file to sync the destination ClickHouse.

After running the 20+ times for the destination ClickHouse, it always is failed.

I'm not sure why this issue is happened to the above connection.

**Comment by grishick** [comment]
@peter279k @qisaw could you post the full log and specify which versions of connections and Airbyte platform you are using?

**Comment by peter279k** [comment]
I guess it's my poor networking connection and it causes the timeout.

After I switch my networking connection, the failed timeout situation often happened now.

**Comment by bleonard** [comment]
Closing for now as it looks like networking issues.

**Comment by congvmit** [comment]
@peter279k have you solved the problem? Any update?

**Comment by peter279k** [comment]
> @peter279k have you solved the problem? Any update?

I switch the faster networking connection and it seems to be solved.
