### ISSUE TITLE
Postgres Source Crash: PSQLException  HikariPool-1 - Connection is not available

### ISSUE THREAD

**Issue by bleonard** [airbytehq/airbyte#13911]
```
"java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
 io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source process exited with non-zero exit code 1
 Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 30001ms."
```
5 instance found this month
Workspace details here: https://docs.google.com/spreadsheets/d/1ja8deCtFHtFVP3QrWELsMpVCMfPB1kz0QfLG1szns1I/edit#gid=1909848124

**Comment by AThilenius** [comment]
I'm unable to add our PSQL DB (running in Dokku/Docker) via an SSH tunnel in Airbyte cloud. I get the error `Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 60001ms.` Expanding logs there is nothing there. Happy to help if it means we can get the connection source added. No interesting logs in the PSQL instance.

**Comment by grishick** [comment]
I have observed this happen when:
 - SSH tunnel is not working
 - Database does not support TLS (with or without SSH tunnel)
 - Other networking issues

**Comment by grishick** [comment]
> I'm unable to add our PSQL DB (running in Dokku/Docker) via an SSH tunnel in Airbyte cloud. I get the error `Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 60001ms.` Expanding logs there is nothing there. Happy to help if it means we can get the connection source added. No interesting logs in the PSQL instance.

Does your PSQL DB support TLS (in addition to running over SSH tunnel)?

**Comment by grishick** [comment]
Sounds like we may need to allow plain connections if SSH tunneling is enabled. However, I don't think the UI can support this sort of conditional configuration. @timroes can this be done: allow toggling SSL setting to off only SSH tunneling is enabled?

**Comment by dudu-monday** [comment]
Are there any updates on this one?

**Comment by grishick** [comment]
So far, this is blocked on https://github.com/airbytehq/airbyte/issues/15809

**Comment by grishick** [comment]
@dudu-monday we added the ability to set SSL mode to `disable` as long as SSH tunnel is enabled and deployed the latest Postgres source connector to Airbyte Cloud.

**Comment by grishick** [comment]
This should be resolved now that `check` method prevents using non-secure SSL modes without SSH tunneling
