### ISSUE TITLE
🎉 Source Github: improve incremental read performance of `workflow_runs` stream

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#13925]
## Current Behavior
Subsequent incremental syncs too slow

https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/a6bfadb7-182a-4766-81fd-1bc70597e594/status

```
1.52 MB | 109 emitted records | 109 committed records | 3h 31m 51s | Sync
3.77 MB | 256 emitted records | 256 committed records | 3h 26m 39s | Sync
752.09 KB | 53 emitted records | 53 committed records | 3h 38m 47s | Sync
```

**Comment by ChristopheDuong** [comment]
It doesn't seem to be only the `workflow_run` stream though:

Here this connection is focusing on comments:
![Screenshot 2022-06-20 at 16 16 11](https://user-images.githubusercontent.com/7718175/174621637-e7188a78-1a7f-416d-ac4a-c36112f2eded.png)

- https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/209101ee-835f-4f20-a1dd-38e4bc5f7896/status 
![Screenshot 2022-06-20 at 16 14 54](https://user-images.githubusercontent.com/7718175/174621525-1c52e9c2-f901-4fa1-9234-8ee7a75417a2.png)

**Comment by grubberr** [comment]
@ChristopheDuong can we please keep track of all problem cases in one issue 
maybe here
https://github.com/airbytehq/alpha-beta-issues/issues/34 ?
because every stream's perfomenace problem completly different in it's nature 
in this issue I just want to close problem with `workflow_runs` stream
