### ISSUE TITLE
Pass namespace through to configured catalog for incremental streams

### ISSUE THREAD

**Issue by jordan-glitch** [airbytehq/airbyte#13922]
## Tell us about the problem you're trying to solve
We would like to create tables from the destination without relying on the records. In order for this to be achieved, we require the `Stream.namespace` property to be present in the configured catalog.

## Describe the solution you’d like
The `Stream.namespace` property should be passed through for the `AbstractSource`, so that it can be used in the destination when creating tables. All that needs to be done is for these two lines to be added to the `Stream.as_airbyte_stream` method. https://github.com/airbytehq/airbyte/blob/ec8e5bccf2f15aab12f401cae4aa5e26f981cfcb/airbyte-cdk/python/airbyte_cdk/sources/streams/core.py#L112

```
if self.namespace:
    stream.namespace = self.namespace
```

**Comment by marcosmarxm** [comment]
Thanks @jordan-glitch we request to connector team review your PR.

**Comment by jordan-glitch** [comment]
Is there any update on this? The associated issue has been merged.

**Comment by marcosmarxm** [comment]
Closed by #13923
