### ISSUE TITLE
Fix list of java connectors that are failing to publish

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#13947]
I recently tried publishing all the java connectors ([in this PR](https://github.com/airbytehq/airbyte/pull/13864)) in order to propagate a change from base-java. 

Here is a list of those that failed to publish (and [here's the action run](https://github.com/airbytehq/airbyte/actions/runs/2530705259)).
We should 1. identify why they're failing and 2. fix them:

- [ ] destination-elasticsearch
- [ ] destination-local-json
- [ ] destination-mongodb
- [ ] destination-mongodb-strict-encrypt
- [ ] destination-mqtt
- [ ] destination-mssql
- [x] destination-mysql
- [ ] destination-mysql-strict-encrypt
- [ ] destination-oracle
- [ ] destination-oracle-strict-encrypt
- [ ] destination-postgres
- [x] destination-rockset
- [ ] source-clickhouse
- [ ] source-clickhouse-strict-encrypt
- [ ] source-cockroachdb
- [ ] source-mongodb-strict-encrypt
- [ ] source-mysql-strict-encrypt
- [ ] source-oracle
- [ ] source-oracle-strict-encrypt
- [ ] source-redshift
- [ ] source-relational-db
- [ ] source-snowflake
- [x] source-tidb

p.s. [the update to the /publish command](https://github.com/airbytehq/airbyte/pull/13864#issuecomment-1160613359) to allow running for multiple connectors in parallel _might_ be useful for working on this

**Comment by evantahler** [comment]
cc @grishick I think this ticket can be closed, because we recently published all destinations for per-stream state https://github.com/airbytehq/airbyte/issues/15224
