### ISSUE TITLE
New sandbox account: Glassfrog

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#13941]
We need a sandbox account to read Glassfrog API in order to run acceptance tests on this [PR](https://github.com/airbytehq/airbyte/pull/13868)

**Comment by harshithmullapudi** [comment]
Hey @igrankova can you help us creating a sandbox account here?

**Comment by igrankova** [comment]
@alafanechere, @harshithmullapudi 
We have a Premium trial for 30 days. I asked the support team for the sandbox account.
LastPass name: glassfrog.com
find an API Key [here](https://app.glassfrog.com/org/29501/api_keys).

**Comment by harshithmullapudi** [comment]
Thanks a lot @igrankova.

**Comment by igrankova** [comment]
@harshithmullapudi I received an email from the support, they moved our organization to Complimentary. That should give us access to everything we need. 
If you need anything else, please reopen this issue.

**Comment by igrankova** [comment]
@harshithmullapudi 
If you need anything else, please reopen the task.
