### ISSUE TITLE
Source Jira: custom fields not returned

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#13961]
## Environment
- **Airbyte version**:  All versions
- **OS Version / Instance**: AWS EC2
- **Deployment**:  Docker
- **Source Connector and version**: JIRA
- **Destination Connector and version**: Redshift
- **Step where error happened**: Sync Job
## Current Behavior
Custom Fields do not appear in the issue stream

## Expected Behavior
Custom fields appear in the issue stream

## Steps to Reproduce
1. Setup custom fields on source config page. customfield_00000, cf[00000], customfield
2. Execute sync
3. Custom fields are not returned in issue stream. I can see these custom fields in the changelog regardless of the custom field config on source. Expectation is that the current value is returned for the customfield in its own field

**Comment by alafanechere** [comment]
@JCWahoo could you please share a screenshot of your jira source setup? Could you also please share the current version of your Jira connector?

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1101](https://airbyte7538.zendesk.com/agent/tickets/1101) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-22 at 17:04:*

<blockquote><div class="zd-comment" dir="auto">It's a bug thanks for opening issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/13961">https://github.com/airbytehq/airbyte/issues/13961</a><br>Any updated I'll return here.<br>&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
(testing update comment)

**Comment by briancstadium** [comment]
Sorry if this is an ignorant question but I'm curious to know if this issue is likely to be prioritized. It's on the critical path for a project I'm working on and I will need to work around it if this won't be fixed in the near-term. I understand your team has many competing priorities and this may not be at the top of the list.

**Comment by briancstadium** [comment]
Thank you @JCWahoo – I tried syncing with the custom field name in the past and it didn't work but I will try again, perhaps I got some detail wrong. I appreciate the response.

**Comment by JCWahoo** [comment]
Same story here :-)

**Comment by IsraarHamid** [comment]
Hi All, I wanted to inquire as to whether anyone has been able to successfully sync in custom fields in the issue stream or if there has been any update to this?

**Comment by JCWahoo** [comment]
I am able to sync using the custom field name only. Multiple custom fields are working. My larger issue is standard fields like "Due Date" are not coming in the issues stream

**Comment by IsraarHamid** [comment]
Could you please provide an example of the format in which you input the custom fields? I've attempted using the custom field names to no success.

> I am able to sync using the custom field name only. Multiple custom fields are working. My larger issue is standard fields like "Due Date" are not coming in the issues stream

**Comment by JCWahoo** [comment]
![image](https://user-images.githubusercontent.com/83980236/192289345-88c3cd54-7bce-4a37-a3d5-f2e3c9624670.png)

**Comment by grubberr** [comment]
I think we can just close this issue because in this PR https://github.com/airbytehq/airbyte/pull/20128 I have removed `additional_fields` param from spec. In new implementation `source-jira` just fetch all possible issue fields.

**Comment by grubberr** [comment]
closed because of https://github.com/airbytehq/airbyte/pull/20128
