### ISSUE TITLE
Source Postgres: Debezium Upgrade introduces default values errors

### ISSUE THREAD

**Issue by adam-bloom** [airbytehq/airbyte#13967]
## Environment
- **Airbyte version**: 0.39.13-alpha
- **OS Version / Instance**: AWS Linux
- **Deployment**: K8s
- **Source Connector and version**: Postgres 0.4.26
- **Destination Connector and version**: Redshift 0.3.40
- **Step where error happened**: Sync Job

## Current Behavior
Debezium fails with the following exception:
```
Caused by: java.lang.NoSuchMethodError: 'java.time.OffsetDateTime org.postgresql.jdbc.TimestampUtils.toOffsetDateTime(java.lang.String)'
	at io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.lambda$createDefaultValueMappers$22(PostgresDefaultValueConverter.java:168)
	at io.debezium.connector.postgresql.connection.PostgresDefaultValueConverter.parseDefaultValue(PostgresDefaultValueConverter.java:77)
	at io.debezium.relational.TableSchemaBuilder.lambda$addField$9(TableSchemaBuilder.java:391)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:391)
	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:147)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
```

## Expected Behavior
No exception was encountered on 0.4.24.

This is resolved in newer versions of pgjdbc (https://github.com/pgjdbc/pgjdbc/issues/2497). I believe upgrading will resolve this, but am not sure where that dependency is declared.

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

If I found where the pgjdbc dependency was... ;)

**Comment by tuliren** [comment]
@subodh1810, FYI.

**Comment by subodh1810** [comment]
@adam-bloom can you share the schema of the table that you are trying to sync which is causing this error. I want to reproduce this locally

**Comment by adam-bloom** [comment]
@subodh1810 not sure how to identify exactly which table from that log - there are quite a few for this connection. However, only 5 of them are configured for incremental sync, so I assume it'd be one of those five that debezium is attempting to setup. Here are two schemas for tables in that 5 that have timestamp columns with default values, so my guess is that it's one of these:

```
                                      Table "public.auth_keys"
     Column     |            Type             | Collation | Nullable |           Default
----------------+-----------------------------+-----------+----------+------------------------------
 id             | character varying(24)       |           | not null | generate_id('kx'::bpchar)
 is_revoked     | boolean                     |           | not null | false
 token          | character varying(128)      |           | not null |
 principal_type | auth_resource_types         |           | not null |
 principal_id   | character varying(64)       |           | not null |
 time_created   | timestamp without time zone |           |          | timezone('utc'::text, now())
 time_expires   | timestamp without time zone |           |          |
 time_last_used | timestamp without time zone |           |          |
 version        | character varying(8)        |           | not null | '1.0'::character varying
 manager_id     | character varying(64)       |           |          | NULL::character varying
 manager_type   | enum_auth_keys_manager_type |           |          |
 type           | character varying(64)       |           | not null | 'default'::character varying
 ip_whitelist   | jsonb                       |           | not null | '[]'::jsonb
```

```
                                     Table "public.account_emails"
    Column     |            Type             | Collation | Nullable |              Default
---------------+-----------------------------+-----------+----------+-----------------------------------
 email         | character varying(256)      |           | not null |
 account_id    | character varying(24)       |           | not null |
 is_anonymous  | boolean                     |           | not null |
 is_confirmed  | boolean                     |           | not null | false
 is_primary    | boolean                     |           | not null | false
 is_archived   | boolean                     |           | not null | false
 time_archived | timestamp without time zone |           | not null | to_timestamp(0::double precision)
```

**Comment by subodh1810** [comment]
@adam-bloom thanks for sharing, I will try to reproduce and update the issue with my findings

**Comment by lucienfregosibodyguard** [comment]
Same issue here

**Comment by mp-pinheiro** [comment]
Seem very similar to this issue https://github.com/airbytehq/airbyte/issues/14064

**Comment by subodh1810** [comment]
Hey guys thanks for reporting the issue and helping me reproduce it. I have raised the [PR](https://github.com/airbytehq/airbyte/pull/14211) to fix it. Please track the PR and look for a new release for postgres source connector after its merged. I will update the issue as well once I release.

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1362](https://airbyte7538.zendesk.com/agent/tickets/1362) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 20:05:*

<blockquote><div class="zd-comment" dir="auto">Team is working in the solution for this issue Felix. Any updates I'll return to you.<br></div></blockquote>

**Comment by adam-bloom** [comment]
@marcosmarxm @subodh1810 I saw the PR was merged, but a new version of the postgres connector wasn't published as a part of that. Are you planning to release a new version with that fix?

**Comment by subodh1810** [comment]
@adam-bloom yes am going to release a new version of the postgres connector soon

**Comment by subodh1810** [comment]
Hey guys a new postgres source conenctor 0.4.29 should be available now with the fix. Am going to close the ticket now but feel free to open a new ticket if you come across any issues. Thanks again

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-30 at 17:45:*

<blockquote><div class="zd-comment" dir="auto">I fix was released, please upgrade connector Postgres to version 0.4.29<br></div></blockquote>
