### ISSUE TITLE
Source Jira: sync all Project Sync Behavior

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#13964]
## Tell us about the problem you're trying to solve
Sync all JIRA projects without selecting them

## Describe the solution you’d like
JIRA source syncs all projects by default. Provide exception list for projects to NOT sync, or selection list to sync.
Sync All Projects
Sync All Except
Sync Only

## Describe the alternative you’ve considered or used
Typing in dozens of JIRA project keys one by one

**Comment by marcosmarxm** [comment]
Today you can sync all projects if you let the Project parameter empty.
![image](https://user-images.githubusercontent.com/5154322/175613193-3ace5856-1827-45ea-a2cd-037155d1815d.png)

Your suggestion is to improve how to select projects?

**Comment by JCWahoo** [comment]
Leaving the field empty syncs no projects

**Comment by grubberr** [comment]
@JCWahoo @marcosmarxm 

I don't see any problems.
Below is example of syncing stream "projects":

projects empty list

```sh
cat secrets/config.json | jq .projects
[]
```

syncing stream "projects"

```sh
python3 main.py read --config secrets/config.json --catalog catalog.json.projects
```

Read 57 records from projects stream


```sh
cat secrets/config.json | jq .projects
["UN"]
```

```sh
python3 main.py read --config secrets/config.json --catalog catalog.json.projects
```


Read 1 records from projects stream


@JCWahoo can you please provide some examples of non-working empty projects?
Maybe it failed on another streams?

**Comment by JCWahoo** [comment]
Will try and test this week, but from I recall - I believe no issues are synced unless you populate the list of project keys. Will need to test if the projects stream behaves the same way, not sure I was sourcing that one.

**Comment by grubberr** [comment]
I have just checked stream `issues` and it also looks ok, with empty `projects = []` I got all issue records.
@JCWahoo it would be good if you would be able to check on your side maybe you will find something interesting.

Thank you

**Comment by grubberr** [comment]
In this PR https://github.com/airbytehq/airbyte/pull/20128 `source-jira` was greatly refined
I have checked with empty `projects = []` connector syncs all projects or all issues for all projects.
