### ISSUE TITLE
Automatically handle non-deterministic temporal errors

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#13973]
## What

One of the conclusions from the Quarantined State discussion (notes [here](https://docs.google.com/document/d/1xpVBCoVfeDfuVVFEdKyICpQl6G3XiFvwq1W7DPKe-cY/edit)) was that we do not want connection manager workflows to be blocked due to non-deterministic errors, as we can always just safely terminate and restart the workflows in that case.

Therefore, the goal of this issue is to modify our temporal logic to automatically terminate and restart connection manager workflows that run into non-deterministic exceptions. 

## How

Some pre-investigation was done on how to do this, and unfortunately it looks like Temporal does not offer much configurability on the behavior that should happen in the case of NonDeterministicExceptions, as these occur at a higher level up than our ConnectionManagerWorkflow code -- these errors happen when Temporal is trying to restore or replay a stored workflow, all of which happens deep inside the temporal library code.

Here are a few potential options for how to mitigate this:
1. Use the [WorkflowImplementationOptions.setFailWorkflowExceptionTypes()](https://www.javadoc.io/static/io.temporal/temporal-sdk/1.0.0/io/temporal/worker/WorkflowImplementationOptions.Builder.html#setFailWorkflowExceptionTypes-java.lang.Class...-) to have temporal automatically set workflows to `Failed` when they run into NonDeterministicExceptions, rather than looping over and over indefinitely. Then, we would need to add some process that finds failed temporal workflows and terminates + restarts them. (Micronaut could help with scheduled tasks here)
2. Fork the temporal library to change what the behavior is in the NonDeterministicException case. This is probably not a great option since we would need to maintain a fork of temporal.
3. Send a signal to all workflows on deploy, causing them to restart. This would need to be tested if it even works in all cases (i.e. could a NonDeterministicException be encountered when processing that signal?) and if the temporal cluster can handle signaling every open workflow at once.
4. Explore other options / ask Temporal folks how we can address this

**From grooming: we have decided to fail workflows that run into non-deterministic exceptions (option 1). This should be done after completing this separate issue to automatically find and fix failed and terminated workflows: https://github.com/airbytehq/airbyte/issues/14043**

**Comment by cgardens** [comment]
I asked on the temporal discourse ([topic](https://community.temporal.io/t/catching-nondeterministicexception/5020)). They haven't responded yet, but they might give us a clear path here.

**Comment by lmossman** [comment]
This will not remove the need for versioning completely - if we never added versioning going forward this could cause every workflow to be failed whenever deploying a change that modifies activity order. Instead, we should still add versioning for these types of changes temporarily, so that workflows can be seamlessly modified without failing everything

**Comment by lmossman** [comment]
@lmossman break out the background process to find and fix failed/terminated workflows from the non-determinism handling behavior

**Comment by cgardens** [comment]
@lmossman I got a response on the temporal discourse ([topic](https://community.temporal.io/t/catching-nondeterministicexception/5020)). Seems pretty much in line with what you were suggesting in option 1.

**Comment by lmossman** [comment]
I have broken this issue down into a few separate issues, as described in this epic: https://github.com/airbytehq/airbyte/issues/14277

The issues should be completed in the following order, which basically achieves the suggestion in option 1 of this issue:
1. https://github.com/airbytehq/airbyte/issues/14970
2. https://github.com/airbytehq/airbyte/issues/14043
3. https://github.com/airbytehq/airbyte/issues/14969
