### ISSUE TITLE
Document batch/bulk edit feature

### ISSUE THREAD

**Issue by johnwasserman** [airbytehq/airbyte#13971]
### Tell us about the documentation you'd like us to add or update.

There is a feature where users can batch update many/all streams within a connection that doesn't seem to be documented. 

Essentially the user can:
1. search/filter streams in bulk using regex
2. select multiple/all streams using the checkboxes
3. Adjust the sync mode and/or cursor field (where applicable) for all selected streams

![Screen Shot 2022-06-21 at 9 12 43 AM](https://user-images.githubusercontent.com/26282337/174848055-32d1450c-6102-43e9-8b2b-22307ae0a793.png)

**Comment by Amruta-Ranade** [comment]
@sophia-wiley Issue for the "Edit configuration" content you're working on

**Comment by sophia-wiley** [comment]
Documentation available [here](https://docs.airbyte.com/cloud/managing-airbyte-cloud#edit-stream-configuration).

**Comment by philippeboyd** [comment]
@sophia-wiley was this feature reverted? it's no longer possible to bulk edit

**Comment by razzeee** [comment]
This is really annoying, when trying to setup something new, with a couple hundredth tables
