### ISSUE TITLE
CI timeout issue: "publish" job takes much more time to run than "test" for the same branch (more than 2-3 times longer)

### ISSUE THREAD

**Issue by etsybaev** [airbytehq/airbyte#14003]
We have an issue with our CI and the "publish" command.

For example, for this PR https://github.com/airbytehq/airbyte/pull/13302
Let's take a look at destination-oracle.
It took 1h 22m to pass the tests (https://github.com/airbytehq/airbyte/actions/runs/2534864411), but it failed by timeout (after 4h) when it comes to the "publish" command for the same (https://github.com/airbytehq/airbyte/actions/runs/2535342165).
So we have some connectors blocked from publishing.

For more information please check this thread in Slack https://airbytehq.slack.com/archives/C02U9R3AF37/p1655898200209919

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/16265
