### ISSUE TITLE
Add Chargebee "custom fields" to Chargebee connector data streams

### ISSUE THREAD

**Issue by remi-denoyer** [airbytehq/airbyte#14002]
## Tell us about the problem you're trying to solve
Add Chargebee "custom fields" to the relevant Chargebee source data streams.

## Describe the solution you’d like
When custom fields are setup on Chargebee entities, Airbyte is syncing them in the data streams.

## Describe the alternative you’ve considered or used
Stitch Chargebee integration.

## Are you willing to submit a PR?
Yes.

**Comment by marcosmarxm** [comment]
Thanks for requesting this @remi-denoyer if you have any more context/information it will help a lot.
I found something here: https://apidocs.chargebee.com/docs/api?prod_cat_ver=2#custom_fields
> You can create custom fields for customers, subscriptions, item families, and items. 

Do you have any example how custom fields return from the API?

**Comment by marcosmarxm** [comment]
Also I added the request to connector backlog to future implementation.

**Comment by remi-denoyer** [comment]
Hello @marcosmarxm! I do have more information: custom fields are returned similarly to other fields with the prefix cf

for example, if you set up a custom field "contract_seats_count" for your customer John Doe, the GET /customers endpoint will return:
`{
  "list": [
    {
      "customer": {
          "id": "93a392c3-35f9-41d8-ab04-49d19893c608",
          "first_name": "John",
          "last_name": "Doe",
          "cf_contract_seats_count": 2
       }
     }
  ]
}`

We do not need to require them: all the properties at the root of the entity (here a customer) with the cf_ prefix are custom fields.

**Comment by marcosmarxm** [comment]
Thanks @remi-denoyer this is really helpful!

**Comment by validumitru** [comment]
@remi-denoyer @marcosmarxm any ETA on this one guys ? We also need Chargebee custom fields synced.

**Comment by marcosmarxm** [comment]
@validumitru Chargebee is an alpha connector so Airbyte team doesn't have an ETA for this feature request.
