### ISSUE TITLE
Upgrade Airbyte Version without losing existing configuration / data

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1402]
## Problem
* Each time we release a new version a user has to delete all of their existing configuration and history and start from scratch. This is one of the most frequently asked questions that we receive.

## Urgency
* Without this feature, a user cannot use us in production, because if they encounter a bug or want to upgrade, they will have to delete all of their configuration and start over.

## Requirements
* When a user upgrades, they do not lose existing configuration.
* When a user upgrades, they do not lose _state_ for a connection. (Note: State is stored in the Jobs table currently).

## Nice to have
* When a user upgrades, they do not lose existing job history.

## Out of scope
* User does not need to do anything manual in order to run the upgrade process.  (in other words, it is okay if users need to run a script or a few commands in order to upgrade).
* No downtime upgrades

**Comment by cgardens** [comment]
Goal for milestone v0.10.0 is just a plan. Not the actual implementation.

**Comment by ChristopheDuong** [comment]
## Internal Postgres Database

- Track current and past Airbyte Database versions in airbyte_metadata table

     Example: Airbyte_DB_VERSION = 0.1.0

- Run a Docker image for applying migrations scripts (pass the current Airbyte DB version as an argument or the script goes and queries the DB to find it out)
  
  - Determine the Migration path to go from current Airbyte DB Version to target version handled by Migration Docker image when handling Database migrations as needed along the path:
    - A db_scripts folder where we store executables to be run and applied when going from one particular version to another
These can be written in any language, PSQL, python, or java, they just need to read the data to migrate from a source schema and output the migrated tables in a destination schema

   - When the migration is done and successful, a transaction that [swaps out atomically the source and destination schema](https://dba.stackexchange.com/questions/100779/how-to-atomically-replace-table-data-in-postgresql/100787#100787) can be run to commit the upgrade
- Log a new triggered Job to Jobs table: migration from Airbyte_DB_VERSION XX to YY 
- With associated logs in Attempt table

## Json File-based configurations
- Handling Configuration file transformations when needed along the path (include connectors latest recommended version)
- Similar to database migration but with files
- A file_scripts folder where we store file migrations shell/python scripts to be applied when going from one particular version to another
- For connectors versions, we migrate to recommended versions (except ones marked as pinned to a specific version)

**Comment by ChristopheDuong** [comment]
Following a discussion with @cgardens, this approach could also allow with this mechanism a scenario in the future where

- take the airbyte instance of my local computer
- start running the migration script to produce temporary files snapshots of my instance's configuration (with credentials) and job history
- put those on git or a server
- start running the migration script from those files to the latest version available of airbyte but specify the destination schema to be a remote server where to replicate the initial airbyte setup from (not my local MacBook)

**Comment by ChristopheDuong** [comment]
link to google docs if the format is better for commenting: https://docs.google.com/document/d/13kZoSwZTKTHAY8ParK4OtbE6tldmliKvRnVNiawIVsw/edit?usp=sharing

**Comment by ChristopheDuong** [comment]
Another use case as described by one user in the community would then be to follow the same process but with tight version control:
- I take the airbyte instance of my local computer
- I configure some pipeline to pull data from some source and write to some destination with test credentials
- I start running the export script to produce temporary files snapshots of my instance's configuration (with test credentials) and job history
- I push those on my team’s git server
- As part of my CI/CD, I am running migration scripts to convert the configuration files to the adequate Airbyte version that is being used in my remote sandbox or production environment.
- I submit some Pull Requests to review changes made to my instance configurations with my team and we are able to clearly read and understand modifications made by the various manual tweaks using Airbyte UI or migrations scripts as diffs.
- As part of my CI/CD, I am also running some custom migration script written by my team that will only change the credentials. The configurations will be modified once again to use credentials from my sandbox or production environment instead. Additionally, I can make other programmatic changes to configurations as I wish.
- When my changes to the configurations are accepted by my team, it is merged and deployed to my production environment where I have an airbyte server running continuously with production credentials.

**Comment by cgardens** [comment]
done
