### ISSUE TITLE
Destination S3: date type written as dictionary for parquet format

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14028]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1152](https://airbyte7538.zendesk.com/agent/tickets/1152)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Kubernetes</li>
<li style="padding-bottom: 10px;">Memory / Disk: unlimited (scalable cluster)</li>
<li style="padding-bottom: 10px;">Deployment: Kubernetes</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.35.64-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: source-google-analytics-v4 0.3.22</li>
<li style="padding-bottom: 10px;">Destination name/version: destination-s3 / 0.3.5</li>
<li style="padding-bottom: 10px;">Step: The issue is happening during sync</li>
<li style="padding-bottom: 10px;">Description: the date column of the Google analytics are written as a dictionnary in parquet file instead of string<br>
<div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/1X/7c4770bf55e13c765830d28f680a94cf8d016c28.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/1X/7c4770bf55e13c765830d28f680a94cf8d016c28.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1067×345 17.4 KB</span>
</div></a></div>
</li>
</ul>
<p dir="auto">I did try to sync to the s3 destination in json format, and it worked (the dates were strings)<br>
is this a bug or this is how parquet encode dates ?</p> 

[<a href="https://discuss.airbyte.io/t/date-type-written-as-dictionnary-for-parquet-format-in-s3-destination/1455/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
I was able to reproduce issue with integration account. Other fields are unnest correctly.

**Comment by blarghmatey** [comment]
I'm wondering if there has been any progress on this issue yet? We are currently using the S3 destination to populate our data lake environment with Parquet files and this is preventing us from being able to execute queries on any tables that contain a datetime value.

**Comment by tuliren** [comment]
This issue is very strange in that:
- If the `date` from Google Analytics is defined as a logical `date` type, the Parquet schema should interpret it as an integer field representing epoch days ([doc](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#date)).
- If the `date` is not defined as a logical type, in Parquet schema it should be string.

The current `{ member0: string, member1: none }` value is very confusing. I don't know how come it can be an object. It's probably something peculiar from the Google Analytics schema.

There is no progress in this issue so far. Unfortunately we currently don't have enough bandwidth for S3. So I also cannot give an estimation when this can be fixed.

**Comment by blarghmatey** [comment]
I've been doing some further debugging to narrow down the potential source of the issue. So far I have the following information:
- The data type that is confounding the writer is a timestamp with timezone in my source Postgres system
- The `_airbyte_emitted_at` column is properly represented in the resulting parquet file
- The Avro file type is able to properly encode the date-time with timezone when accessed via the Python library after downloading the synced file from S3
- The dictionary encoding toggle does not have an impact on whether the date-time records are represented properly

Looking at the code in the S3 connector it seems that Airbyte is relying on the upstream Apache Avro Java library for translating from Avro to Parquet. This suggests that there is either a bug in the upstream implementation, or a bug in how it is being used in Airbyte.

It is entirely possible that there is another source of the problem that I am overlooking, but this is what I have discovered so far.

**Comment by blarghmatey** [comment]
I believe that this change in the upstream Parquet library will resolve this bug, so updating to 1.12.3 will be the necessary fix

https://github.com/apache/parquet-mr/commit/c72862b61399ff516e968fbd02885e573d4be81c

**Comment by blarghmatey** [comment]
@marcosmarxm @tuliren I found what appears to be the necessary fix to this bug and pushed a PR that bumps the upstream Parquet dependency to the latest version. Can you take a look and see about getting a new release pushed so I can test it? Thanks!

https://github.com/airbytehq/airbyte/pull/14502

**Comment by marcosmarxm** [comment]
Thanks @blarghmatey !

**Comment by blarghmatey** [comment]
The block of code in the upstream Parquet library that generates the struct from a Union type is https://github.com/apache/parquet-mr/blob/e990eb3f14c39273e46a9fce07ec85d2edf7fccb/parquet-avro/src/main/java/org/apache/parquet/avro/AvroSchemaConverter.java#L264-L272

It seems that the solution is to modify the Airbyte code that generates the Avro schema from the JSON schema to not include `string` in the union of logical types for the record so that the Parquet conversion doesn't generate the struct. If there is another approach that I'm missing I'm happy for suggestions.

**Comment by felcastro** [comment]
Any updates? Currently trying to sync data from MySQL to S3 Parquet, and Timestamp fields are being converted to struct type.
`{"member0": "2020-02-04T17:01:27.000+0000", "member1": null}`

**Comment by liyin-compass** [comment]
Hi there, will there be an ongoing fix here or it is intentionally written as a struct?
The background is we are building a mysql to s3 sync, then build a Hive table based on the output of this parquet file, we want to have datetime column in Hive metastore but it does not work with the struct.

**Comment by liyinqiu** [comment]
Hi there, will there be an ongoing fix here or it is intentionally written as a struct?
The background is we are building mysql to s3 sync, then build a Hive table based on the output of this parquet file, we want to have datetime column type in Hive metastore but it does not work with this struct in parquet file.
From this [post](https://discuss.airbyte.io/t/datetime-field-saved-as-dictionary-in-s3-parquet/2649), we used a previous version of mysql source and it outputs datetime as string could mitigate the issue.

**Comment by sebas-500** [comment]
Any updates on this? 

I'm trying to copy a Postgres table into S3 but some of the datetime columns contain the aforementioned struct.

**Comment by robertomczak** [comment]
Observed the same during our MySQL to Parquet S3 testing {'member0': datetime.datetime(2016, 9, 25, 19, 57, 31, tzinfo=<UTC>), 'member1': None}

**Comment by sebas-500** [comment]
> Observed the same during our MySQL to Parquet S3 testing {'member0': datetime.datetime(2016, 9, 25, 19, 57, 31, tzinfo=), 'member1': None}

Did you manage to work it around?

**Comment by robertomczak** [comment]
> > Observed the same during our MySQL to Parquet S3 testing {'member0': datetime.datetime(2016, 9, 25, 19, 57, 31, tzinfo=), 'member1': None}
> 
> @robertomczak Did you manage to work it around?

Not directly in Airbyte, current idea is to process data in further ETL using Pandas and extract column from nested object to top level object of pandas data frame. 

It would be nice to fix it, as keeping empty string artifact on intermidiate data lake is not good practice. 🤷‍♂️

**Comment by sebas-500** [comment]
> > > Observed the same during our MySQL to Parquet S3 testing {'member0': datetime.datetime(2016, 9, 25, 19, 57, 31, tzinfo=), 'member1': None}
> > 
> > 
> > @robertomczak Did you manage to work it around?
> 
> Not directly in Airbyte, current idea is to process data in further ETL using Pandas and extract column from nested object to top level object of pandas data frame.
> 
> It would be nice to fix it, as keeping empty string artifact on intermidiate data lake is not good practice. 🤷‍♂️

Aren't the destination files getting bigger? For example in my case a table of 20MB was transformed to two files of 97 and 20MB each. I bet the struct has something to do with it.

**Comment by msaffitz** [comment]
I'm seeing this as well -- I'm curious if this is related to #17010 and  #17011.

In either case, I poked around to see if I could get a fix but unfortunately wasn't able to get my env fully setup to build / run tests.

It'd awesome to get a fix within Airbyte for this  :)

**Comment by tevonsb** [comment]
We have also experienced this using a snowflake connector on any field of type DATE.

Reading to a parquet file in S3. Our data is not large (100k rows) chunked into a single file. So don't think it has to do with data scale.

**Comment by qoqajr** [comment]
Hello,

I'm experiencing the same issue with postgresql timestamptz data being written into s3 parquet files. Any update on tthe issue since 2022...?

**Comment by jamsi** [comment]
Incase it helps anyone, I was processing some of the parquet data in Pyspark through AWS Glue and added this transformation to solve struct.member0 -> DateTime field.

```
def extract_timestamp_from_struct(df: DataFrame) -> DataFrame:
    '''
    This function converts any "structs" that are really datetimes, into datetimes.
    This is documented here: https://github.com/airbytehq/airbyte/issues/14028
    
    Parameters:
    - df: The input DataFrame.
    
    Returns:
    - DataFrame with datetime columns as datetimes
    '''    
    for field in df.schema:
        if isinstance(field.dataType, StructType):
            if any(child.name == "member0" and isinstance(child.dataType, TimestampType) for child in field.dataType.fields):
                df = df.withColumn(field.name, col(f"{field.name}.member0"))
    return df
```

**Comment by qoqajr** [comment]
Thanks @jamsi for sharing, I ended up doing exactly the same in a glue job, but it would be better if it wouldn't be required to add another service in the mix just to fix date formats.

**Comment by lahdirakram** [comment]
any new about this? im facing the same behaviour

**Comment by john-motif** [comment]
I'm also seeing this issue with Snowflake > GCS in Parquet format

**Comment by OMK2186** [comment]
MySQL to S3 connector:
`_airbyte_emitted_at` is in string format, but columns from MySQL table are being converted to Struct
`{'member0': datetime.datetime(2023, 12, 7, 7, 48, 39, tzinfo=<UTC>), 'member1': None}`

**Comment by davidfromtandym** [comment]
This is an insanely frustrating bug

**Comment by nijuyonkadesu** [comment]
I cling to the tinest ember of hope, and rebuid destination-s3 connector with
```gradle
implementation ('org.apache.parquet:parquet-avro:1.13.1') { exclude group: 'org.slf4j', module: 'slf4j-log4j12'}
```
and
```
{'member0': datetime.datetime(2024, 2, 19, 10, 30, tzinfo=<UTC>), 'member1': None}
```
![image](https://github.com/airbytehq/airbyte/assets/85601344/e7208739-f8d3-4baf-b6d9-bf42f0ecdfd5)

 it's still the same ...

**Comment by myonlinecode1988** [comment]
I see the above in both parquet and avro files. Is it on the roadmap to address this?

**Comment by octavia-squidington-iii** [comment]
Zendesk ticket #[5666](https://airbyte1416.zendesk.com/agent/tickets/5666) has been linked to this issue.

**Comment by kahlua-kol** [comment]
Hey! Any hope to get this bug fixed soon? :)

**Comment by johnny-schmidt** [comment]
This will be fixed as part of an upcoming breaking change release.

**Comment by kev-datams** [comment]
do you have any open issue or PR regarding the coming breaking change ? is GCS also concerned by the fixed ? (as based on S3)

**Comment by johnny-schmidt** [comment]
@kev-datams GCS was not in scope for the fix and is not currently planned.

The PR for the specific fix was [here](https://github.com/airbytehq/airbyte/pull/42542) 
It went out as part of a larger breaking change (1.0.0) that includes an extension migration guide [here](https://docs.airbyte.com/integrations/destinations/s3-migrations)
