### ISSUE TITLE
Update Documentation for Deploying on Kubernetes since `bases` has been deprecated in Kustomize

### ISSUE THREAD

**Issue by ct-martin** [airbytehq/airbyte#14036]
### Tell us about the documentation you'd like us to add or update.

I was deploying Airbyte and got an error when trying to modify the configuration using [Customizing Airbyte Manifests](https://docs.airbyte.com/deploying-airbyte/on-kubernetes/#customizing-airbyte-manifests).

While researching, I found the issue I had was related to `bases` [being deprecated in Kustomize](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/bases/) with `resources` being recommended to use instead.

Since this is an easy change, I can open a PR and link it to this issue

### If applicable, add links to the relevant docs that should be updated
- [Deploying Airbyte > On Kubernetes > Customizing Airbyte Manifests](https://docs.airbyte.com/deploying-airbyte/on-kubernetes/#customizing-airbyte-manifests)

**Comment by marcosmarxm** [comment]
Closed by #14037

**Comment by evantahler** [comment]
@lmossman can this again be closed?

**Comment by lmossman** [comment]
@evantahler I don't think so, because as I commented above we reverted the change that closed this issue, and I don't think anything else has been done here

**Comment by cpdeethree** [comment]
Deploying Airbyte with Kustomize is no longer supported.
