### ISSUE TITLE
Source postgres: upgrading to 0.4.19 broke the normalisation

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#14042]
Is this your first time deploying Airbyte?: No
OS Version / Instance: Ubuntu
Memory / Disk: JOB_MAIN_CONTAINER_MEMORY_REQUEST=2Gi, JOB_MAIN_CONTAINER_MEMORY_LIMIT=4Gi
Deployment: Kubernetes v1.22.9
Airbyte Version: v0.39.17-alpha
Source name/version: Postgres v0.4.18
Destination name/version: Snowflake v0.4.20
Step: Sync
Description: We recently upgraded Airbyte to the latest version and wanted to upgrade our connectors to the latest versions as well. We started at Postgres v0.4.14 and had no issues until v0.4.19. There were a few issues there:

    1. We got this error in the normalization: 002108 (22000): SQL compilation error: cannot change column EXPIRY from type VARCHAR(16777216) to TIMESTAMP_NTZ(9) Seems like this version starts to recognize timestamps, but all of our previous values are varchars.
    2. Even on sync failure, the cursor was updated. It was clear because the format of the cursor changed, from “2022-06-22T12:57:03.460945Z” to “2022-06-22T13:01:14.158140”. So some data would be missed if I did not reset the cursor after.
    3. could not downgrade because the cursor format changed. I had to manually edit the state table to return the cursor to its previous format so that v0.4.18 would work again.

Seems like issues 2 and 3 are avoidable if there is some way to get around issue 1. Do you have any recommendations for how to complete this upgrade? I know we could just reset all of our data, but we have hundreds of tables, tens of connections, and some tables > 1TB which are very difficult to get working and we don’t want to go through that again.

I thought that the cursor would not be updated if a sync failed, yet it seems like this happened. Is there a way to ensure that the cursor will not be updated unless the sync succeeds?

For reference, I have attached the logs and a screenshot of the UI for this testing period. I have also attached a table showing the cursor after each sync for each version.
![Screen Shot 2022-06-22 at 3 37 01 PM](https://user-images.githubusercontent.com/17528887/175210430-a6d0de5e-0382-4e8d-93da-5e6188464ca2.png)

https://discuss.airbyte.io/t/upgrading-the-postgres-source-connector-after-v0-4-18/1542

**Comment by grishick** [comment]
Need to check if upgrading from 0.4.18 to 0.4.29 w/o doing a full reset works without errors.

**Comment by VitaliiMaltsev** [comment]
i can confirm that upgrade from 0.4.18 to 0.4.19 is not safe, but upgrade from 0.4.18 to 0.4.29 and 0.4.30(latest) is safe and works without errors during sync

**Comment by grishick** [comment]
@VitaliiMaltsev thank you for confirming!

**Comment by andmosourceability** [comment]
I have attempted to upgrade from 0.4.18 to 0.4.30 and I had mixed results. Two of my connections failed, while one succeeded. Here are my logs. 
Success:
[logs-36853.txt](https://github.com/airbytehq/airbyte/files/9082265/logs-36853.txt)

Failure (both pointing to errors in normalization and timestamp fields):
[logs-36851.txt](https://github.com/airbytehq/airbyte/files/9082262/logs-36851.txt)
[logs-36852.txt](https://github.com/airbytehq/airbyte/files/9082246/logs-36852.txt)

**Comment by VitaliiMaltsev** [comment]
@andmosourceability what version of destination-snowflake are you using?

**Comment by andmosourceability** [comment]
@VitaliiMaltsev v0.4.30

**Comment by tuliren** [comment]
@VitaliiMaltsev, are you still working on this issue?

**Comment by VitaliiMaltsev** [comment]
@tuliren no. I can not reproduce it with latest source-postgres and destination-snowflake
