### ISSUE TITLE
New source: connector InStatus

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#14046]
## Tell us about the problem you're trying to solve
If we need to keep track of uptime from various components.
These metrics can be derived from the status page.

## Describe the solution you’d like
Retrieve those numbers from the InStatus API back to the data warehouse to feed dashboards.

## Describe the alternative you’ve considered or used
Manually update OKR numbers.

**Comment by igrankova** [comment]
**Vetting results:**

**Webhook-based? (no/partially/yes)** 
partially:
https://instatus.com/help/webhooks

**Available authentication modes (API key/Oauth/other)** 
API key
https://instatus.com/help/api

**Has Sandbox environment?** 
no, using free account

**How to populate the account with data** 
UI

**Available streams for sync** 
Status pages
Components
Incidents
Incident updates
Maintenances
Maintenance updates
Teammates
Subscribers
Metrics
User profile
Public data

**Integration supports incremental sync?** 
some streams have date type fields (createdAt, updatedAt, started)

**Other information/blockers**

**Comment by lazebnyi** [comment]
scoping - https://docs.google.com/document/d/1oAyt3Mkn2r4L9R8Zqk9dXX1NksiOgaiBV7wdbS2yzVE/edit
