### ISSUE TITLE
Allow a user to cancel a job from the UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1404]
## Tell us about the problem you're trying to solve
* If a job is failing and I know it has no hope of succeeding, I would like to cancel it so that Airbyte stops retrying that job.

**Comment by jrhizor** [comment]
depends on https://github.com/airbytehq/airbyte/issues/1623, which I'm treating as the backend implementation.

**Comment by jrhizor** [comment]
@johnlafleur we'll need a mockup of cancelling a sync job in the UI for Artem to look at.

**Comment by johnlafleur** [comment]
Here's the design suggestion: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A295

**Comment by jrhizor** [comment]
This is a duplicate of https://github.com/airbytehq/airbyte/issues/2567
