### ISSUE TITLE
Automatically find failed connection manager workflows and restart them

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#14043]
## What

With the plan to automatically set connection manager workflows to failed when they encounter a NonDeterministicException (as described in the [parent epic](https://github.com/airbytehq/airbyte/issues/14277) and in [this issue](https://github.com/airbytehq/airbyte/issues/14969)), we need something that will automatically repair these failed workflows.

The goal of this issue is to implement a background process that runs as part of the platform, which finds failed connection manager workflows and terminates + restarts them automatically.

## How

This can be implemented as a cron in a standalone pod, or a background process/thread in an existing pod. Micronaut's scheduled tasks may be a good candidate here, so that we do not need to manage the scheduling ourselves.

This implementation should utilize the TemporalClient method introduced in https://github.com/airbytehq/airbyte/issues/14970 to perform the find+restart logic.

This process should emit a metric whenever it restarts a workflow, similar to those established in https://github.com/airbytehq/airbyte/issues/13773

**Comment by lmossman** [comment]
If going with the Micronaut approach, we probably want to create a new service (i.e. new kube pod) so that this ticket does not also include the work to convert an existing service into Micronaut

**Comment by lmossman** [comment]
Moving this one back to the backlog, since I have pulled some of the work here out into the other tickets that I linked in the description

**Comment by evantahler** [comment]
This story is pending Micronaut scheduler for the "automatic" part
