### ISSUE TITLE
Error when updating to bigquery destination version 1.1.9

### ISSUE THREAD

**Issue by infina-calvin** [airbytehq/airbyte#14040]
I'm running 0.39.20-alpha, docker deployment on our own machine.

I have been getting this error with bigquery destination version 1.1.9, but I do not have this issue when reverting back to version 1.1.18. This happens no matter what source I use (i've tested google sheets and mongodb)

Verification error(s) occurred for CHECK. Errors: [$.loading_method.method: must be a constant value Standard]
![image](https://user-images.githubusercontent.com/101394676/175209952-9b45f5f4-4e02-435e-bfc8-c8badcfdfbaf.png)

**Comment by SunXGitHub** [comment]
I have same issue. I changed BigQuery connector from 1.1.9 to 1.1.8 and error vanished for now.

**Comment by marcosmarxm** [comment]
I'm not able to reproduce the issue @SunXGitHub @infina-calvin can you give more information about how you got it?
It's a new instance? Did you upgrade it? Is trying to create a destination bigquery?
Also can you try to upgrade latest version of Airbyte and Bigquery?

**Comment by infina-calvin** [comment]
@marcosmarxm  The issue has been resolved with the newest bigquery destination version (1.1.11), so I will mark this issue resolved. Thank you
