### ISSUE TITLE
Incremental sync (deduped+history) creates duplicate rows

### ISSUE THREAD

**Issue by jorinvo** [airbytehq/airbyte#14066]
## Environment
- **Airbyte version**:  0.39.18-alpha
- **OS Version / Instance**: Ubuntu
- **Deployment**: docker-compose
- **Source Connector and version**: Hubspot 0.1.70 and Jira 0.2.20
- **Destination Connector and version**: Postgres 0.3.20

## Current Behavior

When configuring a connector to sync a table as "Incremental | Deduped+history" and there are no changes in the source data, the last entry from the source data will be added again in the destination table.

I could replicate this with both the Hubspot and Jira sources. I came across this when I tried to run the incremental sync with a 5min frequency and I noticed that every 5min exactly 1 row was added. Then I noticed that the most recent data point was duplicated every time.

For now I am using "Full refresh" as alternative, but I wish we could get updates more frequently.

## Expected Behavior

If there is no new data being yielded by an incremental source, I don't expect any rows to be added to the raw destination table.

## Logs

no failure visible in the logs

## Steps to Reproduce

1. Setup Jira/Hubspot  "Incremental | Deduped+history" sync for a table with Postgres as target
2. Sync quickly multiple times without new entries in the source
3. Observe duplicate rows in the raw destination table

Thank you for your help 🙂

**Comment by marcosmarxm** [comment]
This is expected, only final table (the first level) will be deduplicated.
Is the sync ingesting all data again for INCREMENTAL + DEDUP + HISTYR? because this would be a bug.

**Comment by jorinvo** [comment]
Sorry for the late reply :pray: 

Do I understand correctly, that incremental sync produces at least one row in the destination every time it runs? The dedup happens in the transform step then?

I guess incremental is not working for our use case then. We have to use the raw tables and not the normalized ones for now since the normalized ones are recreated each time so we cannot easily create other database views on top of them (sorry another topics, not part of the issue I tried to report here).

Is there any documentation where I can read up on this behavior of the incremental sync and normalization? So far it has all been rather trial and error. I understand that there are technical limitations and tradeoffs that lead to things being implemented in a certain way. This incremental sync behavior feels unexpected to be, so I reported a bug. If it's obviously documented somewhere, that could help so no other people like me open issues for what seems to be expected behavior.

Thank you for your help @marcosmarxm :)

**Comment by sahar10501** [comment]
I was surprised aswell to see that airbyte itself doesnt take care of the duplicates.
https://docs.airbyte.com/understanding-airbyte/connections/incremental-deduped-history#known-limitations
You can see it mentioned in the last paragraph. 
I would advice to factor out the deduplications from the generated dbt sql scripts.. or just write your own

**Comment by jorinvo** [comment]
Thank you for the link @sahar10501! I am closing this issue now since it's not a bug. Sorry for my confusion.

Guess we will try to implement our own dedup some day then. Or we stick to full refresh for the time being. Thank you all!
