### ISSUE TITLE
Halt sync when destination unable to deserialize state JSON

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#14067]
## Tell us about the problem you're trying to solve

The [IntegrationRunner](https://github.com/airbytehq/airbyte/blob/7f982128b0e380dd1aba311042a29f16b63a3630/airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/IntegrationRunner.java#L192), which is responsible for executing the source or destination, continues with the requested sync when the provided `AirbyteMessage` cannot be deserialized from the provided JSON string.  The result is that the sync will continue without any state, potentially resulting in the duplication of data.  In addition, an error is logged stating that an invalid message has been received, but does not provide any additional remediation steps to help the user determine why the message has been rejected.  This is obviously not optimal, as it can lead to data duplication without providing a clear link between the failure and the end result.

## Describe the solution you’d like

The [IntegrationRunner](https://github.com/airbytehq/airbyte/blob/7f982128b0e380dd1aba311042a29f16b63a3630/airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/IntegrationRunner.java#L192) should fail the execution when the incoming `AirbyteMessage` that represents a state message cannot be deserialized.  In addition, it should provide a meaningful error message, indicating possible solutions (e.g. update to the latest source/destination, reset the source, etc).

## Additional context

[It appears that](https://github.com/airbytehq/airbyte/blame/5e2ccaa49bfc6d07fc89fbea58eb0fbd4864cd3b/airbyte-integrations/base-java/src/main/java/io/airbyte/integrations/base/IntegrationRunner.java#L103) this logic has been in place since the initial creation of the `IntegrationRunner` class.  It includes a comment that states "decide if we want to throw here instead", indicating that there may not be any technical reason why the current code just swallows the failure and continues.  Therefore, it should be safe to make the changes proposed in this ticket, provided they are limited to the deserialization of state messages.

**Comment by jdpgrailsdev** [comment]
@davinchia This issue is really orthogonal to the per-stream state changes.  The per-stream work uncovered the issue in the code.  In the case of the destination, it deserializes the message JSON to object only to serialize it back to JSON without modifying it.  When it fails to do the deserialization, we run the risk of emitting a null state.  This exposure is not limited to protocol changes that the destination can't handle:  it could also happen for a third-party source that emits malformed JSON.

We don't have to fix this issue to proceed with per-stream state.  This is just something we uncovered as we work through rolling out the per-stream state.  From a search of the Git history, this issue has been present since the `IntegrationRunner` was created.

**Comment by cgardens** [comment]
How would networking affect this?

**Comment by davinchia** [comment]
Maybe I'm wrong here - to me, networking (in Kube) or early terminated source processes (both Kube and docker) should be the main causes of malformed packets.

**Comment by jdpgrailsdev** [comment]
@davinchia I see the confusion.  This ticket is specifically targeting code that attempts to deserialize the JSON input passed to the runner into an `AirbyteMessage`.  Any sort of network issue would most likely manifest itself before the code in question when it attempts to read in the standard out of the previous sync.  At the point in the code identified in this ticket, there is no networking logic involved and the question is really around whether a sync should continue if the input cannot be deserialized.  The argument is that if we hit that scenario, we run the risk of ending up in a bad state should the code continue on with the sync like it does today.  We are not advocating for the removal of the error or the logging of it -- only that instead of swallowing it, it will be thrown to ensure that the sync halts when we hit this case.

**Comment by jdpgrailsdev** [comment]
After discussion with the team, the plan of attack will be as follows:

* Create a new POJO that contains the same type field as `AirbyteMessage` and allows all other properties (e.g. `additionalProperties: true`
* On failure to deserialize an `AirbyteMessage` in the [IntegrationRunner](https://github.com/airbytehq/airbyte/blob/7f982128b0e380dd1aba311042a29f16b63a3630/airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/IntegrationRunner.java#L192), attempt to deserialize the message into the new POJO
  * If successful, check the type field.  If equal to a state message, throw an exception to halt execution
  * If not successful OR not a state message, maintain current behavior of logging deserialization failure and continuing to the next message.

**Comment by davinchia** [comment]
thanks jonathan! 

for my understanding - the new POJO is so we can set additionalProperties = true, clarify the type and only fail-fast on state messages?

**Comment by jdpgrailsdev** [comment]
> thanks jonathan!
> 
> for my understanding - the new POJO is so we can set additionalProperties = true, clarify the type and only fail-fast on state messages?

Correct.  It will basically be an object with one named field that matches the type field from `AirbyteMessage` and will ignore any other properties so that we can check to see if the deserialization failure is one of the "unrecoverable exceptions" called out above (state message deserialization failures).
