### ISSUE TITLE
[EPIC] Source Survey Monkey to Beta 

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14060]
### According to [checklist](https://docs.google.com/spreadsheets/d/1TtUQ8ca6Al-AmH9xCp_mIzBhjM2FYPZwR1-ZmDimfQg/edit#gid=1820065035):

- MLP improvements: https://docs.google.com/document/d/1oFblLjBd86OL1ofiamy1ElFDqnt5UD9sLX34y9I-tLw/edit?usp=sharing

- All outstanding bug reports blocking Beta:
   - [ ] 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Survey Survey Monkey: Enable in Cloud](https://app.harvestr.io/components/0/list/vW-nAmazX)

**Comment by YowanR** [comment]
LGTM! 
I suggest that code changes and docs should be separated into different PRs in the future.
Thanks!
