### ISSUE TITLE
Not possible to access Connection: `JobResetConnectionConfig.getResetSourceConfiguration()` is null

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#14107]
## Environment
Airbyte Version: 0.39.24-alpha
Destination: Snowflake (0.4.29)

## Current Behavior
When opening some connections like Intercom and Notion, the page shows "Oops! Something went wrong… Unknown error occurred", and I found the following message in the chrome console.

```
VM264 react_devtools_backend.js:4026 Error: Internal Server Error: Cannot invoke "io.airbyte.config.ResetSourceConfiguration.getStreamsToReset()" because the return value of "io.airbyte.config.JobResetConnectionConfig.getResetSourceConfiguration()" is null
    at apiOverride.ts:107:9
    at d (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
```

## Expected Behavior
I should be able to open any connection to view the status and settings.

**Comment by nauxliu** [comment]
<img width="1659" alt="CleanShot 2022-06-24 at 10 57 25@2x" src="https://user-images.githubusercontent.com/9570112/175453204-94e48612-fe5a-43a4-ba45-b76ccb148d5f.png">

**Comment by philippeboyd** [comment]
I get this also on `0.39.26-alpha`...

**Comment by philippeboyd** [comment]
@marcosmarxm yes upgraded from `0.39.21-alpha` to `0.39.26-alpha`. I also added the server logs to my comment ☝️

**Comment by philippeboyd** [comment]
FYI, I just upgraded to `0.39.28-alpha` and issue is resolved on my end... 
Seems like PR https://github.com/airbytehq/airbyte/pull/14202 fixed it.

**Comment by cgardens** [comment]
Fixed! Reopen if it persists.
