### ISSUE TITLE
Feature request: Custom data type mapping

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#14116]
## Tell us about the problem you're trying to solve
Why can't we choose our own datamapping? For example for the postgress connector all the date types are mapped to strings, but Im pretty sure they can be mapped to date types in BigQuery. It would be nice if we can set per table per column a custom mapping. 

## Describe the solution you’d like
In the replication screen set a mapping type per column

**Comment by alafanechere** [comment]
Hey @ro8inmorgan,
You can implement your [own DBT transformation](https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-airbyte/) if you want to achieve this.
The mapping you mention is an evolution of our catalog logic.
From Airbyte's perspective, we want catalogs (where connection streams and their schemas are listed) to be agnostic from the destinations and perform as less data transformation on raw data as possible. This is why we store json blobs in destination raw tables. 
The normalization process is then unnesting these json blobs to create final tables according to JSON schema types and metadata stored in the source catalog. We decided to let the normalization process decide which type is the best on the destination side to host the specific fields that are declared in the catalog. Not exposing this to users eases the experience but indeed might not work perfectly well for all use cases. This is why we offer custom transformation with DBT for advanced transformation and custom typing.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
