### ISSUE TITLE
Source Jira: issues records are missing from issue stream

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#14163]
## Environment
- **Airbyte version**: 0.39.26
- **OS Version / Instance**: AWS EC2
- **Deployment**:Docker
- **Source Connector and version**: JIRA Latest/All
- **Destination Connector and version**: Redshift Latest
- **Step where error happened**: Sync

## Current Behavior
Issues are missing from the issues stream, validated using JQL in JIRA instance vs issues loaded.

## Expected Behavior
All issues created at/after the start date configured in source are loaded to the target

## Logs
Nothing related to this would appear in log files

## Steps to Reproduce
1. JQL Query issues that are type epic and created on/after 1/1/2021 for project key EXAMPLE
2. Sync JIRA to target with Airbyte
3. Review issues stream to see 3 total issues instead of 7 for the same constraints

**Comment by sajarin** [comment]
Hey @JCWahoo thanks for the issue. I know it seems like nothing related to this would be in the log files but can you post them here anyway? It may help our team figure out the issue.

**Comment by JCWahoo** [comment]
The epics appear in the epics stream, but only some epics appear in the
issues stream. Logs contain no errors

**Comment by marcosmarxm** [comment]
@JCWahoo thansks for reporting this, I added the issue in the connector backlog but Jira stills alpha level and maybe took a time until get this corrected.

**Comment by grubberr** [comment]
In this PR https://github.com/airbytehq/airbyte/pull/20128 `source-jira` was greatly refined - a lot of bugs were fixed.

The `epics` stream was removed because it's a full subset of `issues` stream. You can find all Epic issues inside `issues` stream.

I think if you re-test now it has to work.
Double check please `Start date` and `Projects` settings
You can leave projects empty to scan over all projects.

**Comment by grubberr** [comment]
This PR https://github.com/airbytehq/airbyte/pull/20128 has to resolve this problem please re-open if the problem still exists
