### ISSUE TITLE
Sometimes the wrong configuration form appears

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1416]
## Expected Behavior
* Whichever connector I pick from the dropdown should display its configuration form in the UI

## Current Behavior
* If you pick a connector from the dropdown and then change your mind and pick a different one you can sometimes get the form for the wrong connector. Our goal is to guarantee we always display the correct form. 
* It is okay if we do not allow someone to change the connector selection until the form displays though if there's a better way to do it, then great! I mention this because it sounds like this issue is due to some sort of race condition.

**Comment by sherifnada** [comment]
Just had this happen during a client call today as well.
