### ISSUE TITLE
[Epic] Connection Page refactoring

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14174]
- [x]  https://github.com/airbytehq/airbyte/issues/13096 Develop a plan for improving the page
- [x] #15603
- [x] #15605
- [x] #15607
- [x] #15606

**Comment by jnr0790** [comment]
Created issue #14844 with loom recordings for a connection creation bug that resets all table setting changes when editing any of the inputs or drop-downs above the stream settings.

**Comment by tealjulia** [comment]
Other known issues/questions:
- when editing a connection, should unsaved changes be overwritten by source schema refresh/should a user be warned of it
- when creating or editing a connection, make it more obvious how/where to set a cursor field
- should you be able to save a config that has an invalid (but disabled) stream?  currently you can.

**Comment by edmundito** [comment]
@tealjulia Can we declare this epic as done? Can you confirm that what is tracked with Zenhub is correct (and less that what's on the description)?

**Comment by tealjulia** [comment]
What is tracked in the epic is more correct than what is marked in the description.  I'll update the description and close this!
