### ISSUE TITLE
[EPIC] Source Zuora to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14180]
### According to [checklist](https://docs.google.com/spreadsheets/d/1TtUQ8ca6Al-AmH9xCp_mIzBhjM2FYPZwR1-ZmDimfQg/edit#gid=1820065035):

- MLP improvements:

- All outstanding bug reports blocking Beta:
   - [ ] 

<details><summary><strong>Acceptance criteria </strong></summary>

- [x] Create a checklist document that should rbe placed on the [Google Drive](https://drive.google.com/drive/folders/1qOzblo8xiBJc8AiK4AyuDTC1Ilt-GFzu)
- [ ] Checklist filled up by engineering team
- [ ] Collect and list all tech debt-related issues in the section below
- [ ] Create/Revise MLP document and place it [here](https://github.com/airbytehq/airbyte/issues/11287#issue-1175260119)
- [ ] Move checklist to the unblockers team
- [ ] Reviewed/Updated by unblockers team
- [ ] Move checklist to the product team for review
- [ ] Reviewed/Updated by product team
- [ ] Update connector documentation according to the comments in the checklist
- [ ] Certification completed
 
</details>

**Comment by murat-cetinkaya** [comment]
Hi @igrankova ,
Is there a timeline for Zuora beta version? We're using the alpha and would be very happy to see it goes to beta. Thanks.

**Comment by igrankova** [comment]
@YowanR, can you help us with the plans on Beta release? (question above)

**Comment by YowanR** [comment]
Hi @murat-cetinkaya, appreciate your feedback here. We don't have a clear timeline for getting Zuora to Beta yet but make sure to give this GH issue a 👍 so we can better prioritize it. You can track our roadmap [here](https://app.harvestr.io/roadmap/view/pQU6gdCyc/airbyte-roadmap) as well. Hope this helps!
