### ISSUE TITLE
Wrong display in attempts status?

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1419]
## Expected Behavior
I am testing:
- a source setup with ExchangeRateAPI
- a destination with Local CSV
- a frequency of every 5 mins

After letting the scheduler run successfully a few trials, I changed the permission to remove write access to the local directory and observe how the system behaves with failures...

## Current Behavior
I observe 3 attempts and for some reason, the third one is marked with a green check (even though it is still failing without write permissions):

![Screenshot 2020-12-21 at 19 58 19](https://user-images.githubusercontent.com/7718175/102812407-3ca60c00-43c7-11eb-91c6-6ee2f2f3049f.png)

(Sorry i forgot to turn off my "dark" theme mode in my browser for the screenshot..)

**Comment by jrhizor** [comment]
When this happened to me, the 2nd and 3rd attempts shared the same logs in the UI which was weird.

**Comment by Jamakase** [comment]
@jrhizor We talked with @cgardens about that sometime before: I suppose there is an issue on the backend side. I have seen this issue before and backend was sending the same log for different attempts.

On the frontend, we just display what we receive from backend without any processing or normalization.
