### ISSUE TITLE
s3 destination compress files with disabled compression

### ISSUE THREAD

**Issue by kananindzya** [airbytehq/airbyte#14206]
## Environment
- **Airbyte version**: 0.38.3-alpha
- **OS Version / Instance**: docker
- **Deployment**: example are Docker or Kubernetes deploy env
- **Destination Connector and version**: (0.3.5) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
With disabled compression - airbyte compress all files to gz format files.

## Expected Behavior
With disabled compression - airbyte should not compress files.

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by knugusbayevps** [comment]
I found reason, when "compression" field not passed to destination configuration, airbyte applies compression.

**Comment by marcosmarxm** [comment]
@kananindzya can we close the ticket?

**Comment by kananindzya** [comment]
@marcosmarxm , yes. Thanks
