### ISSUE TITLE
After OAuth in connector and switching to a different auth method and back, user is asked to OAuth again

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14226]
## Environment
- **Airbyte version**:  0.39.28-alpha
- **Step where error happened**: Setup new source or destination

## Current Behavior
OAuth button reads "Authenticate your ___ account" when it should read "Re-authenticate...". User can save connection at this point because credentials have been stored in form state.

## Expected Behavior
Button on OAuth confirms that user is already authorized or user has to auth from the start, depending on desired UX.

## Steps to Reproduce
1. Create a new Snowflake Source
2. Set the `Host`
3. Select Authorization method as "OAuth 2.0"
4. Click on "Authenticate your Snowflake account"
5. Select "Username and Password" Authorization method
6. Select "OAuth 2.0" Authorization method again

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
@edmundito What test creds were being used? I can't find the right account.
