### ISSUE TITLE
[Epic] Simplify Connector Configuration

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#14247]
[PRD](https://docs.google.com/document/d/1c2nbjNKnreI7637ZcQi-FJGKW2uxnKzJ29KhehjmgE4/edit#)

Issues:
- [x] #12204
- [x] #13056
- [x] #16469
- [x] #16396

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@misteryeo Followed up on this with @andyjih and @Upmitt.

Looking at the PRD we can cover the improvements to the individual fields (#12204), but still need to discuss how to group them (how to name the groups, what is collapsible, what is considered advanced.) This will require changes to the connector spec files.

One idea is to define the spec for an individual connector, such as postgres, and once we figure out what it is, it can be applied to the rest of the connectors. The frontend team can collaborate to figure out what this spec change should look like.
