### ISSUE TITLE
CDK Speedrun sub-heading has an error 

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#14259]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

### Tell us about the documentation you'd like us to add or update.
[CDK Speedrun](https://docs.airbyte.com/connector-development/tutorials/cdk-speedrun) appears to have an incorrect link as copied from the docs page to the snippet below. I am not sure what this is trying to say ... 

### CDK Speedrun (HTTP API Source Creation [Any%](https://en.wikipedia.org/wiki/Speedrun#:~:text=Any%25%2C%20or%20fastest%20completion%2C,the%20game%20to%20its%20fullest.&text=Specific%20requirements%20for%20a%20100,different%20depending%20on%20the%20game.) Route)

**Comment by Jagrutiti** [comment]
Hey

What is the correct link to the subheading?

Should I change: CDK Speedrun (HTTP API Source Creation [Any%](https://en.wikipedia.org/wiki/Speedrun#:~:text=Any%25%2C%20or%20fastest%20completion%2C,the%20game%20to%20its%20fullest.&text=Specific%20requirements%20for%20a%20100,different%20depending%20on%20the%20game.) Route)

To CDK Speedrun ([HTTP API Source Creation Route](https://en.wikipedia.org/wiki/Speedrun#:~:text=Any%25%2C%20or%20fastest%20completion%2C,the%20game%20to%20its%20fullest.&text=Specific%20requirements%20for%20a%20100,different%20depending%20on%20the%20game))

What is the expectation here?

**Comment by Amruta-Ranade** [comment]
Hey! I think you can remove the hyperlink. So the title would just be "CDK Speedrun (HTTP API Source Creation Any Route)"

**Comment by oreopot** [comment]
I can work on this.
