### ISSUE TITLE
(Resolve) Tech debt of the ConnectorForm

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#14250]
Brainstomring issue about problem with the ServiceForm component. Please feel free to list all issues that should be addressed to make this component more stable and easier to maintain:

- [x] https://github.com/airbytehq/airbyte/issues/13056
- [x] Only render connector form component if the selected connector definition specification is loaded (move loading state and spinner into ConnectorCard) https://github.com/airbytehq/airbyte/pull/20127
- [x] Remove component override for name field and make it a normal field in the schema with title and description https://github.com/airbytehq/airbyte/pull/20132
- [x] Move unfinished flows into local state in ConfirmationControls (reset from the outside if formik state becomes non-dirty) https://github.com/airbytehq/airbyte/pull/20135
- [ ] Remove uiWidgetsInfo state by finding the enum/const field defining the selected oneOf and adding it to the condition form block to check the selected value by looking at the formik state
- [ ] Only do default value calculation once before rendering the formik component the first time (remove `PatchInitialValuesWithWidgetConfig` hack)
- [ ] Build yup schema once by flattening the oneOf conditions into a single object and adding `when` conditions on the found condition key (remove `RevalidateOnValidationSchemaChange` hack)
- [ ] Add https://github.com/airbytehq/airbyte/issues/17352 to default value calculation

* ~Pull out auth field hiding from `FormSection` to a higher level when generating from the spec which fields should be rendered.~
* ~`values.connectionConfiguration` plus flattened values are confusing (for a flattened form)~
* ~Rethink `default` behavior (should it be sending the value if the field is empty?), since it's working different depending on your field type atm~ -> extra issue

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by flash1293** [comment]
Discussed getting rid of re-calculating the yup schema based on the selected conditions for `oneOf` properties, but as there is no straight forward way to encode the logic of "oneOf" using yup we decided against this route for now. This means the `RevalidateOnValidationSchemaChange` hack will need to stay for now.

**Comment by flash1293** [comment]
current selection for `oneOf` does not need additional state because the documentation states that each oneOf has a const property which is the same for each of the conditions (also checked via SAT): https://docs.airbyte.com/connector-development/connector-specification-reference/#using-oneof

Instead of storing this separately we can do the same thing the SAT is doing and search for the shared const field in each condition to determine the currently chosen path. This has the downside of breaking connectors which don't satisfy this SAT rule, but it seems justifiable in this case.

**Comment by flash1293** [comment]
* Only render connector form component if the selected connector definition specification is loaded (move loading state and spinner into ConnectorCard)
* Remove component override for name field and make it a normal field in the schema with title and description
* Move unfinished flows into local state in ConfirmationControls (reset from the outside if formik state becomes non-dirty
* Remove uiWidgetsInfo state by finding the enum/const field defining the selected oneOf and adding it to the condition form block to check the selected value by looking at the formik state
* Only do default value calculation once before rendering the formik component the first time (remove `PatchInitialValuesWithWidgetConfig` hack)
* Build yup schema once by flattening the oneOf conditions into a single object and adding `when` conditions on the found condition key (remove `RevalidateOnValidationSchemaChange` hack)
* Add https://github.com/airbytehq/airbyte/issues/17352 to default value calculation

**Comment by flash1293** [comment]
Last of the stacked PRs is in review and received feedback already, should be merged soon

**Comment by flash1293** [comment]
Approved, waiting for the code freeze
