### ISSUE TITLE
Alignment off on connector status icon

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#14260]
Adding this issue after a pairing session with Nico as it seems we may need to just move this to sass modules and do a little more than a simple tweak.

On `/sources` and `/destinations`, the alignment is off for paused connectors.  This issue may affect other statuses as well, but `play` looks fine.

![Screen Shot 2022-06-29 at 11 49 46 AM](https://user-images.githubusercontent.com/63751206/176480426-3b87a9c5-38ff-4eca-b52a-27509f6802eb.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by fool1280** [comment]
Hi, can I take this issue?
