### ISSUE TITLE
[EPIC] Visibility of connector checkpointing

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#14279]
[PRD Here](https://docs.google.com/document/d/1n9grVSwCmRPiQc6JD53z4mBX9VwY_WXuR3daU5kNVlY/edit?pli=1#)

The goal of this Epic is to categorize all of our connectors and determine if they support checkpointing or not.  In the future, we will label connectors/connections in the UI that support checkpointing.

**Comment by evantahler** [comment]
@salima-airbyte this can be closed! All child-stories are complete.
