### ISSUE TITLE
[EPIC] Auto-Detect Schema Changes

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#14278]
PRD:
https://docs.google.com/document/d/1hvwPXnfi0TMK05dnh4Oy-n5WEDCD9msCbUOLxwnp0Uw/edit

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by evantahler** [comment]
There's some info in the original feature request https://github.com/airbytehq/airbyte/issues/1000

**Comment by edmundito** [comment]
Current status:
- PRD Ready
- Backend work is expected to start in Late August/Early September
- Frontend work may be at risk for EOQ delivery

**Comment by edmundito** [comment]
Followed up with @andyjih:

* PRD is still in-flight and needs more iteration
* There are some designs ready but will change based on PRD changes.

**Comment by grishick** [comment]
Use case: https://github.com/airbytehq/oncall/issues/505

**Comment by jdpgrailsdev** [comment]
Duplicate of #17520
