### ISSUE TITLE
[MOVE EPIC] Airbyte Protocol Versioning

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#14276]
Product Requirements Doc - https://docs.google.com/document/d/1RMCSZKt9GT_RMR0hI4jjb7WBcppkzTTQ87hPqSqzwT8/edit#

> Airbyte does not currently support transitions of the Airbyte Protocol evolution. As a result, we require both the platform and the connectors to always support the same version of the protocol and we lack the ability to clearly delineate which connectors work with which versions of the platform, and communicate this to our users. We want to enable progressive update of the platform and the connectors. 
> … enter Airbyte Protocol Versioning

## Airbyte Protocol Versions

**v0.0.0** - initial version of Airbyte Protocol 
**v0.1.0** - AirbyteTraceMessage - new feature, non breaking, optional 
**v0.2.0** - New State messages introduced (Aug 2022 - here now)
but still backwards compatible with connectors dealing with both versions of STATE
**v1.0.0** - connectors advertise their version of the protocol (or we assume a version)
***v1.1.0** - New datatypes in Protocol (additive change)*
***v1.2.0** - New AirbyteTraceMessage (optional additive change)*
**v2.0.0** - legacy state removed (breaking change - Feb 1, 2023)

**Comment by davinchia** [comment]
This work has been deprioritised.
