### ISSUE TITLE
🎉 Source Sentry: support oauth

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#14293]
## Tell us about the problem you're trying to solve
With the release of Airbyte Cloud, we need to start supporting Oauth for this connector, since it's the recommended way of authenticating users into a SaaS application. 

If this connector doesn't support oauth already (i.e: doesn't accept a client_id and client_secret) then we need to update its spec to accept those parameters. I suggest that this be a oneof nested inside a top-level field called "authentication": 

`
{
  authentication: {
     type: object
     oneOf: [ 
       // api key,
       // oauth
     ] 
  }
}
`

See the connector spec reference in the docs for reference on how a oneof can be implemented.

This should be done in a backwards compatible manner i.e: users currently supplying authentication info in the config's top-level should not be impacted by this change. 

## Acceptance Criteria

1. The connector supports oauth webflow authentication with client_id/client_secret 
2. Oauth properties are annotated properly. See [this PR](https://github.com/airbytehq/airbyte/pull/6022) for an example

**Comment by sherifnada** [comment]
Sentry does not support oauth as far as I can tell: https://docs.sentry.io/product/integrations/integration-platform/#internal-integrations so I don't think we need this ticket

cc @YowanR

**Comment by igrankova** [comment]
@sherifnada 
What about this? https://docs.sentry.io/product/integrations/integration-platform/public-integration/#oauth-process
![image](https://user-images.githubusercontent.com/87977540/184303034-2cd486f4-f1bf-45b8-b7b1-921617748261.png)

cc @YowanR

**Comment by sherifnada** [comment]
ah you are right. ignore me!

**Comment by roman-yermilov-gl** [comment]
Sentry does not have OAuth flow. It only has OAuth for public integrations which require those apps to implement webhook which will be called manually from Sentry Integration page. This is not that OAuth that we are currently support in Airbyte.
@yurii-bidiuk asked Sentry support for more information, so I can do nothing until we receive feedback from them.

**Comment by YowanR** [comment]
@sherifnada Could you take a look at this? Would we ever consider doing the work to support OAuth for Sentry? If so we can create an issue to track it.
