### ISSUE TITLE
Airbyte scheduler on Kubernetes should use native Kubernetes scheduling

### ISSUE THREAD

**Issue by stockymcstockface** [airbytehq/airbyte#14297]
## Tell us about the problem you're trying to solve
I'd like to know why Airbyte is using its own scheduling mechanism in Kubernetes while Kubernetes has everything provided for.
Why not using Job and CronJob to launch tasks ?

**Comment by marcosmarxm** [comment]
Because Airbyte can be deployed in mutiple platforms: docker compose and kubernetes.
