### ISSUE TITLE
Source Tiktok Marketing: parameter `report_granularity` not showing in UI

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14301]
## Environment
- **Source Connector and version**: TikTok Marketing 0.1.14

## Current Behavior
Version 0.1.14
![image](https://user-images.githubusercontent.com/5154322/176695862-90a3ecda-8fe4-4a31-b81f-b5036d752a06.png)

## Expected Behavior
Version 0.1.13
![image](https://user-images.githubusercontent.com/5154322/176696000-0872186e-8a96-4021-9101-5e135d7ec1d8.png)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by bazarnov** [comment]
@marcosmarxm 
The `report_granularity` has `"airbyte_hidden": true` which will hide it from UI. 
We are actually generating all the granular reports while discovering the streams, see the screenshot from Cloud:
<img width="1205" alt="Screenshot 2023-03-28 at 12 45 04" src="https://user-images.githubusercontent.com/22987674/228198893-e664300d-ef07-417d-af6d-cb3630fc3e15.png">

The customers are able to select the streams they need without having to select the `report granularity` directly. It was made to simplify the UI part for this connector.

**Comment by bazarnov** [comment]
Closing this issue.
