### ISSUE TITLE
Job history should display the job type

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1433]
## Tell us about the problem you're trying to solve
I am having a hard time understanding when a reset happened:
![2020-12-22_19-35-16](https://user-images.githubusercontent.com/1154337/102956430-f9ae6c00-448c-11eb-9159-119f9b567368.png)

## Describe the solution you’d like
I would love to see the Sync or Reset label somewhere in the summary

**Comment by cgardens** [comment]
@Jamakase i have put up this PR: https://github.com/airbytehq/airbyte/pull/1722 to make it possible to do this task (per what we discussed on slack today). I can't merge it until you do this task, but is no rush. I know this task isn't too high priority. When you work on this you'll have to work of this PR and we can coordinate merging together.
