### ISSUE TITLE
source-jira: pagination failure, Users stream only returns 50 records

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#14339]
## Environment
- **Source Connector and version**: source-jira 0.2.20

## Current Behavior
The `Users` stream only returns 50 records. This is probably related to `next_page_token` implementation as [the default number](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-users/#api-rest-api-3-users-search-get) of returned values on this endpoint is 50. 

## Expected Behavior
The Users stream should return all available users

## Logs
[Related forum discussion](https://discuss.airbyte.io/t/cant-get-all-jira-users/1664)

**Comment by marcosmarxm** [comment]
Were you able to reproduce the issue with integration account?

**Comment by Hon-badger** [comment]
@marcosmarxm, I am sorry, but what is integration account ?

**Comment by harshithmullapudi** [comment]
That's something internal @marcosmarxm  I can check and get back

**Comment by Hon-badger** [comment]
Hi @harshithmullapudi, are there any updates ?

**Comment by harshithmullapudi** [comment]
Hey yeah I was able to reproduce this with our integration account

**Comment by KrisAnTis-Group** [comment]
Hi all. @harshithmullapudi May I know if there is any progress?

**Comment by antonioneto-hotmart** [comment]
Hey guys, I've provided a temporary solution to the problem by adding a maxResults field in the jira source interface.

https://github.com/antonioneto-hotmart/airbyte/tree/source-jira-custom

Commit https://github.com/airbytehq/airbyte/commit/2211070dbcb835efadd35abb844c4417c09794ae

**Comment by harshithmullapudi** [comment]
Hey @antonioneto-hotmart, do you have time to help us with a PR as a fix?

**Comment by ZBryantOM1** [comment]
A slight adjustment to my previous comment; After reviewing the source code in streams.py for the jira connector, it seems that fixing pagination for Users and Streams would require different approaches. 

While neither class blocks contain references to the next_page_token variable, The Users API doesn't include the paging metadata in the response, and instead might need to be handled differently, such as the temporary solution described above. However, the Sprints API does return pagination metadata, so adding logic that references next_page_token in that class block may solve that pagination issue. Let me know if you'd prefer to make that a separate issue.

**Comment by philippeboyd** [comment]
any news on this issue?
