### ISSUE TITLE
CI credentials for new source Timely

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#14337]
Need CI sandbox credentials for a new community source PR Timely

https://github.com/airbytehq/airbyte/pull/14335

**Comment by harshithmullapudi** [comment]
Could we also generate some data in Events

**Comment by harshithmullapudi** [comment]
@igrankova could you help us here?

**Comment by ycherniaiev** [comment]
@harshithmullapudi  created 3 events on timely Sandbox (lastpass:Source Timely Sandbox)
