### ISSUE TITLE
The problem of backward compatibility of versions when adding fields to a new version of the connector.

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#14345]
Step to reproduce:

1. Open the specification of one of the connectors, at the root of which is the property - "additionalProperties": false.
2. Add a new field of any type to the properties of this specification.
3. Use a new version of the connector. Go to the settings, and add any value to the new field, then save the connector settings.
4. Downgrade the connector version.
5. Try to synchronize with the specified connector without changing anything in its settings.

You will receive the following error message:
![15](https://user-images.githubusercontent.com/88329385/176897288-82f5cdf9-1fb8-4cdc-8801-53767633b7d3.png)

This error appears because in the old version of the container there is a restriction that does not allow ignoring specification fields -
![14 2](https://user-images.githubusercontent.com/88329385/176897627-90a48dd7-7756-4b84-bd52-6c779c8c1ec4.png)

It is necessary to remove this property, or change its value to "true", in those places where it is necessary, for better work of backward compatibility.

Under such cases, it breaks backward compatibility for a large number of connectors, such as: source-postgres, destination-postgres, mysql (source and destination), mssql (source and destination), db2, etc.

**Comment by grishick** [comment]
@andriikorotkov @cgardens @benmoriceau would the following work as a solution. Whenever user updates connector configuration with a newer version of a connector, platform will also save the old version of configuration. Platform will always keep two versions of configuration: current and the last configuration created with the previous version of the connector (this could obviously be extended backwards down to the first version, but that's probably an overkill). Initially, this will allow support to go in and manually revert connector config to the previous one in case we have to downgrade a connector and older version cannot consume newer configs. Eventually, if we find this feature useful, we could add a button in the UI that would allow users to revert to previously saved configs.

**Comment by cgardens** [comment]
I don't follow how this helps us. Can't we just decrement the version by one and get the same effect without any dev work?

**Comment by andriikorotkov** [comment]
@grishick - @edgao  wrote to me and said that he had already created a task on this problem. Here is a link to it - https://github.com/airbytehq/airbyte/issues/14196.

**Comment by andriikorotkov** [comment]
@grishick I don't think it works quite like that. When we save a specification in an old version and then change the version to a new version - the connector will use the old version of the specification until we update it and save it. The same will happen when we do the opposite - in the new version we save the specification, and then switch to the old version and do not save the specification. The specification we kept in the new version of the connector will be used. To sum up - when the connector version is updated, we do not update the specifications of these connectors.

**Comment by edgao** [comment]
@grishick I think that proposal might carry other risk? E.g. if the user made some sort of important config update (maybe they switched to a different DB host after the 0.2 upgrade) then we can't swap back to their v0.1 config, because it's not valid either. The worst case if we _do_ swap back, and the old config succeeds but does the wrong thing (maybe their old DB host is still running, but no longer has accurate data).

I could be convinced that connectors should have methods for upgrading configs from the previous version + downgrading their config to the older version, but that's very heavyweight (and it involves writing _more_ code, which introduces other things we would need to test.... and what happens if the config migration logic has a bug, etc).
