### ISSUE TITLE
Source Postgres: Set up connection - add schema selection

### ISSUE THREAD

**Issue by jacobbaruch** [airbytehq/airbyte#1435]
## Tell us about the problem you're trying to solve
I tried to move data from Postgres DB, now I have several Schemas and wanted to move data from only one schema.
If I want to do it currently, I need to select the required tables one by one

## Describe the solution you’d like
mark the schema that I want to load, by that the checkmark of the tables would be updated

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368203873756) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Hey @jacobbaruch 

Thank you for posting and agreed with your point. Let us look at how we could make it work on our side. 

Let us discuss it internally so we can come up with a suggestion.

**Comment by ChristopheDuong** [comment]
Could this be solved by combining some checkbox lists, select all/unselect all button, and a search field?

This would also be related to the issue described here https://github.com/airbytehq/airbyte/issues/1473

**Comment by cgardens** [comment]
depends on https://github.com/airbytehq/airbyte/issues/1921

**Comment by marcosmarxm** [comment]
We can implement what was made for Oracle in https://github.com/airbytehq/airbyte/pull/5779
