### ISSUE TITLE
Support incremental sync in Salesforce source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1437]

**Comment by brunoffaustino** [comment]
For our use case, for a possible migration to Airbyte, we also need the Salesforce connector to support incremental syncs.

**Comment by sherifnada** [comment]
@bruno I believe this is already supported. Are you not able to configure an incremental sync for salesforce?

**Comment by brunoffaustino** [comment]
Hi @sherifnada we are still evaluation the possibility of considering Airbyte, so we first went through all your documentation and on https://airbyte.io/source/crm/salesforce/ it states that it is "Coming Soon". Is it available already?

**Comment by sherifnada** [comment]
It should be, yes! I think those docs are out of date. @johnlafleur can you fix that page for Salesforce? as you can see in the [developer docs](https://docs.airbyte.io/integrations/sources/salesforce) incremental is already supported. 

Going to close this issue since it is completed.
