### ISSUE TITLE
Update eslint configuration to also follow typescript best guides

### ISSUE THREAD

**Issue by Jamakase** [airbytehq/airbyte#1439]
## Tell us about the problem you're trying to solve
Currently, our eslint config has not the best settings and do not validate all corner cases.

## Describe the solution you’d like
I would like configuration, that will allow us to follow better code practices ( no `any` in code, forbid `!` and etc )

Probably something like next will be better
```
    env: {
      browser: false,
      es2020: true
    },
    extends: [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended",
      "prettier/@typescript-eslint"
    ],
    parser: "@typescript-eslint/parser",
    parserOptions: {
      ecmaVersion: 11,
      sourceType: "module"
    },
    plugins: [
      "@typescript-eslint"
    ]
```

**Comment by cgardens** [comment]
@Jamakase feel free to do this whenever you want. i agree with what you want to do.
