### ISSUE TITLE
How to run BigQuery without Service Account Key JSON on GCE or CKE?

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14407]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1446](https://airbyte7538.zendesk.com/agent/tickets/1446)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I do not want to operate with Service Account Key JSON.</p>
<p dir="auto">Recently, authentication using <a href="https://cloud.google.com/compute/docs/metadata/overview" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Metadata server</a> or <a href="https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Workload Identity</a> is recommended.<br>
Does Airbyte plan to implement these authentication methods in the future?</p>
<p dir="auto">Thanks.</p> 

[<a href="https://discuss.airbyte.io/t/how-to-run-bigquery-without-service-account-key-json-on-gce-or-cke/1709/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-04 at 13:18:*

<blockquote><div class="zd-comment" dir="auto">Could you share links to Google documentation saying these are the recommended way to authenticate?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 00:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a><br>
Of course.<br>
First, the best practices document for application certification is below.</p><div style="border: 5px solid #e9e9e9; margin-bottom: 10px; padding: 12px 25px 12px 12px;">
  <div>
      <img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/a/a37862dc2001d1fde2710e3999bc61d9579ce5cc.png" width="32" height="32" style="height: 16px; margin-right: 3px; width: 16px;">

      <a href="https://cloud.google.com/docs/authentication/best-practices-applications" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Google Cloud</a>
  </div>

  <div style="clear: both;">
    <div><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/f/f74dbc6eb29149f30e5241925000cd050ff4594f_2_690x362.png" width="auto" height="auto" style="height: auto; margin-right: 10px; max-height: 80%; max-width: 20%; width: 60px;" align="left"></div>

<h3 style="font-size: 1.17em; margin: 30px 0 10px;" dir="auto"><a href="https://cloud.google.com/docs/authentication/best-practices-applications" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Best practices to securely authenticate applications in Google Cloud...</a></h3>



  </div>

  <div style="color: #919191;">
    
    
  </div>

  <div style="clear: both;"></div>
</div>

<p dir="auto">Application Default Credentials (ADC) is recommended when using resources on GCP, otherwise Workload Identity is recommended if OpenID Connect is supported.</p>
<p dir="auto">For GKE only, the following documents may be helpful.</p><div style="border: 5px solid #e9e9e9; margin-bottom: 10px; padding: 12px 25px 12px 12px;">
  <div>
      <img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/a/a37862dc2001d1fde2710e3999bc61d9579ce5cc.png" width="32" height="32" style="height: 16px; margin-right: 3px; width: 16px;">

      <a href="https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Google Cloud</a>
  </div>

  <div style="clear: both;">
    <div><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/f/f74dbc6eb29149f30e5241925000cd050ff4594f_2_690x362.png" width="auto" height="auto" style="height: auto; margin-right: 10px; max-height: 80%; max-width: 20%; width: 60px;" align="left"></div>

<h3 style="font-size: 1.17em; margin: 30px 0 10px;" dir="auto"><a href="https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Workload Identity &nbsp;|&nbsp; Kubernetes Engine Documentation &nbsp;|&nbsp;...</a></h3>



  </div>

  <div style="color: #919191;">
    
    
  </div>

  <div style="clear: both;"></div>
</div>

<p dir="auto">Thanks.</p> 

 [<a href="https://discuss.airbyte.io/t/how-to-run-bigquery-without-service-account-key-json-on-gce-or-cke/1709/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 12:33:*

<blockquote><div class="zd-comment" dir="auto">Hello Nakachi, there isn't a plan to migrate from service account to other auth system yet. I created the Github issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/14407">https://github.com/airbytehq/airbyte/issues/14407</a> and added to connector team backlog for future implementation of this feature. I'll return to you when this is done.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-06 at 00:07:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hello marcosmarxm.<br>
Thanks for your reply and for the issue.<br>
I am eagerly awaiting it.</p> 

 [<a href="https://discuss.airbyte.io/t/how-to-run-bigquery-without-service-account-key-json-on-gce-or-gke/1709/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source BigQuery: Support Authentication using Metadata server or Workload Identity](https://app.harvestr.io/components/0/list/PzZg7ggBE)

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-16 at 00:52:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I don’t understand this issue, this is already implemented because on GCE or GKE, BigQuery connector will accept the default credential for the environment, just do not pass the json at all when creating the destination.</p>
<p dir="auto">Is this not working?</p> 

 [<a href="https://discuss.airbyte.io/t/how-to-run-bigquery-without-service-account-key-json-on-gce-or-gke/1709/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-16 at 16:13:*

<blockquote><div class="zd-comment" dir="auto">Latest version of the connector it's possible default credentials:<br>Service Account Key JSON - The contents of the JSON service account key. Check out the <a rel="noopener noreferrer" href="https://docs.airbyte.com/integrations/destinations/bigquery#service-account-key"><u>docs</u></a> if you need help generating this key. Default credentials will be used if this field is left empty.&nbsp;<br>&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-16 at 19:00:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> <a href="https://github.com/airbytehq/airbyte/blob/cb3312a6b5295269621f60720e1b4c8c5af7db05/airbyte-integrations/connectors/source-bigquery/src/main/resources/spec.json#L11" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">airbyte/spec.json at cb3312a6b5295269621f60720e1b4c8c5af7db05 · airbytehq/airbyte · GitHub</a> looks like it is mandatory in the spec.</p> 

 [<a href="https://discuss.airbyte.io/t/how-to-run-bigquery-without-service-account-key-json-on-gce-or-gke/1709/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-16 at 19:59:*

<blockquote><div class="zd-comment" dir="auto">Look this is only available for bigquery as destination: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/blob/cb3312a6b5295269621f60720e1b4c8c5af7db05/airbyte-integrations/connectors/destination-bigquery/src/main/resources/spec.json">https://github.com/airbytehq/airbyte/blob/cb3312a6b5295269621f60720e1b4c8c5af7db05/airbyte-integrations/connectors/destination-bigquery/src/main/resources/spec.json</a><br></div></blockquote>

**Comment by philipherrmann** [comment]
Works. This issue can be closed.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-12-20 at 15:42:*

<blockquote><div class="zd-comment" dir="auto">Can you test latest version of Bigquery connector?<br></div></blockquote>
