### ISSUE TITLE
Source Microsoft SQL to Beta

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14429]

**Comment by matef** [comment]
Is there any timeline for this source to move to Beta?

**Comment by Beibit** [comment]
+1 on Beta

**Comment by grishick** [comment]
We don't have a specific timeline currently (cc @misteryeo )

**Comment by akashkulk** [comment]
Closing in favor of taking Microsoft SQL to GA : https://github.com/airbytehq/airbyte/issues/16596
