### ISSUE TITLE
New source: Appfollow support CI credentials

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#14436]
Need sandbox credentials for https://github.com/airbytehq/airbyte/pull/14418

**Comment by igrankova** [comment]
@harshithmullapudi,
We have a 10-day free trial. Sent a request for obtaining the Sandbox account. 
find Token [here](https://watch.appfollow.io/settings/api).
LastPass name: Appfollow

**Comment by harshithmullapudi** [comment]
Awesome thanks @igrankova

**Comment by igrankova** [comment]
@harshithmullapudi 
hi, I've contacted support and they agree to configure a test account for us. Waiting for the details from them soon.

**Comment by igrankova** [comment]
@harshithmullapudi 
Received the sandbox with API access
