### ISSUE TITLE
[Investigation] Inspect all possible scenarios for BigQuery Denormalized users after upgrade to #14023

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#14440]
The current BigQuery Denormalized destination implementation replaces all incoming arrays to a record with one array field. This feature avoids the BigQuery limitation of nested arrays and gives a possibility to store an array of arrays.
The downside of this solution is an unnecessary replacement of a single array.

Customers requested to keep the incoming schema as close as possible to the original and don't replace a single array. #11109
PR #14023 provides a new behavior that replaces only nested arrays and surrounds the inner array with a record with an array field.

The problem here is that such change doesn't have backward compatibility and might lead to errors for users after the upgrade.
We need to describe all possible scenarios to estimate the possible user effects.
https://github.com/airbytehq/airbyte/pull/14023#discussion_r914187441

**Comment by grishick** [comment]
Any update on this investigation? What are the results?

**Comment by DoNotPanicUA** [comment]
@grishick 
deprioritized by @alexandr-shegeda. 
Instead of that, I'm working on describing possible solutions for cases when we don't have backward compatibility.
