### ISSUE TITLE
Unique name for Airbyte resources (sources, destinations, connections)

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#14448]
## Tell us about the problem you're trying to solve
When creating a resource on the Airbyte console the resource default name is the connector name used.
If user create a second resource with the same connector they will have two resources with the same name.
This is confusing for users to find the exact resource they are looking for.
On the `octavia-cli` side this is causing a problem because we enforce a unique resource name on the octavia project side. This will require users to rename their resource on the console if they want to import it. 

## Describe the solution you’d like
* Enforcing unique resources name on the platform side
* Default name with a suffix e.g `Github 2` of the user does not name the source 
 

## Additional context
The problem on the `octavia-cli` side is described [here](https://github.com/airbytehq/airbyte/issues/14373).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
I'd have some concern of using the name as the unique identifier for a connection. The name (as it is at least used today) is meant to be a human readable representation, and I think trying to enforce uniqueness on a human readable component won't be the best solution. We already have connection IDs that are unique. Shouldn't we use them instead for addressing? If not, is there a specific reason for this?

**Comment by evantahler** [comment]
+1 for using the (already unique) connector IDs for all API requests, and the storage mechanism for the octavia cli.  We talked about this topic a little bit here https://github.com/airbytehq/airbyte/issues/13203 as well

**Comment by davinchia** [comment]
all octavia issues route to me so I'm doing a drive by and saying +1 for using IDs isn't of names.
