### ISSUE TITLE
Test and release per-stream state handling in Postgres Source

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14457]
Once platform is ready with per-stream state, we need to manually test 

- [x] adding/removing tables to Postgres Source
- [x] connections created with older connector version of Postgres Source (current version in Cloud)
- [x] file any issues that we find

Context:
* Partial reset CDC postgres source acceptance tests: https://github.com/airbytehq/airbyte/pull/14551
* Calculate diff to reset streams: https://github.com/airbytehq/airbyte/pull/14477
* [Per-Stream State Developer Community Announcement](https://docs.google.com/document/d/1bekh4ooZB9x02LL0q8wjN23zd2tdiAyHCW1xfywyatk/edit#)
* [Per-Stream State Tech Spec](https://docs.google.com/document/d/1zJVUQkVy8ZJUcqzM_hYPGijr4pI0Xx6I2eqpagJ2r7E/edit#heading=h.fa72b39y2m99)

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/14457?planning-poker) with ZenHub @edgao @ryankfu @subodh1810

**Comment by ryankfu** [comment]
UPDATE: this ticket is mostly taken care of by the OSS platform team with acceptance tests from Lake and Benoit. I do need to provide an update to them on the create a connection with an older version of the Postgres source but I believe their tests currently cover that (_not fully verified_)

I'm going to instead shift this ticket to address the documentation of the logic that was discovered as a result of spectating Benoit and Lake set up a per-stream non-CDC sync locally. I will update the ticket with a living google doc and tag the databases and oss-platform team once it's ready for review. Furthermore, I'm adding in a diagram of how our syncs work prior to `per-stream` changes and after `per-stream` through Whimsical

**Comment by ryankfu** [comment]
OSS platform team merged the `per-stream` changes today https://github.com/airbytehq/airbyte-cloud/pull/2151 which enables `per-stream` changes onto Airbyte Cloud that is useful for testing

Additionally, will be documenting any issues with setup and testing within [Postgres Source GA doc](https://docs.google.com/document/d/1HvJ7nJW4IWVqeVnko6tW4x_QUtI1zYLvsTUIwMtm37M/edit#). Due note that the document is not visible to non-Airbyters while the team continues to work out any refinements in the setup and information sharing process

Platform OSS filed issues related to `per-stream` state handling:
* https://github.com/airbytehq/airbyte/pull/14966 - this addresses the issue where previously the validation logic also applied to full-sync streams when that particular mode does not create a state within `per-stream`

**Comment by ryankfu** [comment]
Document covering the per-stream changes [here](https://docs.google.com/document/d/10WEizoD1thH-XV4dkTiwaso5bgevNdFyu3esB6JyRBU/edit?pli=1#heading=h.jogsgmmv6tjy) with overview of the complications, what is per-stream and protocol changes necessary to get per-stream operational
