### ISSUE TITLE
CDK: Only initialize uncaught exception handler when using AirbyteEntrypoint

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#14453]
## Tell us about the problem you're trying to solve

Currently, the uncaught exception handler used to emit AirbyteTraceMessages for errors encountered in connectors is initialized by calling `init_uncaught_exception_handler()` [here](https://github.com/airbytehq/airbyte/blob/be2d1a865253de4e7aa65ffed1bbfa27bf6f8363/airbyte-cdk/python/airbyte_cdk/entrypoint.py#L23). Because of where it's called, importing the `airbyte_cdk` might unexpectedly change up how your exceptions are handled. This can be the case if you're just using models from `airbyte_cdk` and not actually building a connector with it, like we're doing for normalization.

See this example from the python REPL:
```python
>>> raise RuntimeError("hi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: hi
>>> import airbyte_cdk
>>> raise RuntimeError("hi")
{"type": "LOG", "log": {"level": "FATAL", "message": "hi\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nRuntimeError: hi"}}
{"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1657117935965.3152, "error": {"message": "Something went wrong in the connector. See the logs for more details.", "internal_message": "hi", "stack_trace": "Traceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nRuntimeError: hi\n", "failure_type": "system_error"}}}
```

## Describe the solution you’d like

Initializing the cdk's uncaught exception handler should be done automatically only for connectors. To do this, we can move initialization to within `AirbyteEntrypoint`'s `__init__` or `run` method.

We should still be able to initialize this explicitly if you're not using `AirbyteEntrypoint`.

**Comment by sherifnada** [comment]
Airbyte Entrypoint is only used by sources, but destinations aren't getting the benefit. So we should: 
1. initialize uncaught exception handler olny when using AirbyteEntrypoint
2. initialize uncaught exception handler when running a destination's run_command method
