### ISSUE TITLE
Unable to launch airbyte using helm charts

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14463]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1373](https://airbyte7538.zendesk.com/agent/tickets/1373)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?:  Yes</li>
<li style="padding-bottom: 10px;">OS Version / Instance: MacOS.</li>
<li style="padding-bottom: 10px;">Memory / Disk: 16Gb / 0.5 Tb</li>
<li style="padding-bottom: 10px;">Deployment:  Kubernetes</li>
<li style="padding-bottom: 10px;">Airbyte Version: v0.39.28-alpha</li>
<li style="padding-bottom: 10px;">Source name/version:  -</li>
<li style="padding-bottom: 10px;">Destination name/version: -</li>
<li style="padding-bottom: 10px;">Step: The issue is happening while setting up airbyte using helm chart</li>
<li style="padding-bottom: 10px;">Description:</li>
</ul>
<p dir="auto">Reason for failure : <code style="background-color: #f9f9f9; padding: 2px 5px;">pod airbyte-bootloader failed</code></p>
<p dir="auto">Followed following steps to setup airbyte :</p>
<ol dir="auto">
<li style="padding-bottom: 10px;">
<p dir="auto">Created namespace airbyte :  <code style="background-color: #f9f9f9; padding: 2px 5px;">kubectl create ns airbyte</code></p>
</li>
<li style="padding-bottom: 10px;">
<p dir="auto">Build helm dependencies : <code style="background-color: #f9f9f9; padding: 2px 5px;">helm dependency build --debug -n airbyte</code><br>
LOGS :</p>
</li>
</ol>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 3 charts
Downloading common from repo https://charts.bitnami.com/bitnami
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Downloading minio from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
</code></pre>
<ol dir="auto">
<li style="padding-bottom: 10px;">Install airbyte : <code style="background-color: #f9f9f9; padding: 2px 5px;">helm install airbyte -n airbyte . --debug</code><br>
LOGS :</li>
</ol>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/somitragupta/factly/airbyte/charts/airbyte

client.go:310: [debug] Starting delete for "airbyte-admin" ServiceAccount
client.go:339: [debug] serviceaccounts "airbyte-admin" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-env" ConfigMap
client.go:339: [debug] configmaps "airbyte-env" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-postgresql" Secret
client.go:339: [debug] secrets "airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-postgresql" Service
client.go:339: [debug] services "airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-postgresql" StatefulSet
client.go:339: [debug] statefulsets.apps "airbyte-postgresql" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-postgresql-headless" Service
client.go:339: [debug] services "airbyte-postgresql-headless" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-secrets" Secret
client.go:339: [debug] secrets "airbyte-secrets" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airbyte-bootloader" Pod
client.go:339: [debug] pods "airbyte-bootloader" not found
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Pod airbyte-bootloader with timeout of 5m0s
client.go:568: [debug] Add/Modify event for airbyte-bootloader: ADDED
client.go:627: [debug] Pod airbyte-bootloader pending
client.go:568: [debug] Add/Modify event for airbyte-bootloader: MODIFIED
client.go:627: [debug] Pod airbyte-bootloader pending
client.go:568: [debug] Add/Modify event for airbyte-bootloader: MODIFIED
client.go:627: [debug] Pod airbyte-bootloader pending
client.go:568: [debug] Add/Modify event for airbyte-bootloader: MODIFIED
client.go:629: [debug] Pod airbyte-bootloader running
client.go:568: [debug] Add/Modify event for airbyte-bootloader: MODIFIED
Error: INSTALLATION FAILED: failed pre-install: pod airbyte-bootloader failed
helm.go:84: [debug] failed pre-install: pod airbyte-bootloader failed
INSTALLATION FAILED
main.newInstallCmd.func2
helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
github.com/spf13/cobra@v1.4.0/command.go:902
main.main
helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
runtime/proc.go:250
runtime.goexit
runtime/asm_amd64.s:1571
</code></pre>
<ol dir="auto">
<li style="padding-bottom: 10px;">This leads to pod status :</li>
</ol>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">NAME                       READY   STATUS    RESTARTS   AGE
airbyte-bootloader      0/1     Error         0               18m
airbyte-postgresql-0   0/1     Pending   0               18m
</code></pre>
<p dir="auto">Could someone guide me where exactly I am missing context ?<br>
Thanks in advance.</p> 

[<a href="https://discuss.airbyte.io/t/unable-to-launch-airbyte-using-helm-charts/1654/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by luthes** [comment]
I'm not sure if this is a separate issue, but trying to use a standalone Postgres pod as a dependency in the chart will also cause the Bootloader to hang, and ultimately fail. I have a handful of dependencies that all use Postgres, so the idea was to move them all to their own internal Postgres pod, but Airbyte blocks.

Chart:
```
apiVersion: v2
name: test
description: test
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: postgresql
    version: 11.9.11
    repository: https://charts.bitnami.com/bitnami
    tags:
      - db
      - core
    alias: postgresql
  - name: airbyte
    version: 0.40.33 
    repository: https://airbytehq.github.io/helm-charts
    tags:
      - tool
      - airbyte
    alias: airbyte
```

**Comment by sajarin** [comment]
Hey @luthes, feel free to create a separate issue for your issue with your chart config, not sure that this is active.

**Comment by marcosmarxm** [comment]
Closed bc new Helm deployment.
