### ISSUE TITLE
[Epic] UI component library cleanup

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14478]
This epic encompasses the most important work needed to improve the UI foundation in Q3.

- Provide a way for design to preview components (tbd: upload storybook into chromatic?)
- Update Buttons to match current design
- Update individual form controls to match current design
- Setup common text styles and heading sizes
- Standardize rounded corners
- Fix paddings so that they are using common padding

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
