### ISSUE TITLE
JSON connector silently fails when the destination path doesn't start with /local

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1448]
## Expected Behavior
When I choose the destination path for Local JSON Destination to `/tutorial_json` I expect the data to be written to `/tmp/airbyte_local/tutorial_json/file.json`

## Current Behavior
Sync succeeds but no data appears. I changed the path in the UI to `/local/tutorial_json` and now I see a file `/tmp/airbyte_local/tutorial_json` 

## Steps to Reproduce
1. Create JSON destination with path `/tutorial_json`
1. run a sync from ERIO API
1. no data in ``/local/tutorial_json`

**Comment by cgardens** [comment]
fixed: https://github.com/airbytehq/airbyte/pull/1727
