### ISSUE TITLE
Source File: Urls that expect an User-Agent Header are not working

### ISSUE THREAD

**Issue by tim-werner** [airbytehq/airbyte#14487]
## Environment
- **Airbyte version**:  0.39.29-alpha
- **OS Version / Instance**:  macOS
- **Deployment**: Docker
- **Source Connector and version**: source-file 0.2.10
- **Step where error happened**: Use https://fineli.fi/fineli/en/elintarvikkeet/resultset.csv as url for the source-file connector

## Current Behavior
*The connection test will fail with error code 403*

## Expected Behavior
*Connection test should work*

## Steps to Reproduce
1. Use https://fineli.fi/fineli/en/elintarvikkeet/resultset.csv as url in the source-file connector

## Are you willing to submit a PR?
Yes, I will create a pull request soonish.

**Comment by tim-werner** [comment]
I will work on it

**Comment by marcosmarxm** [comment]
Closed by @14488
