### ISSUE TITLE
🐛 Sync jobs are hanging

### ISSUE THREAD

**Issue by lgomezm** [airbytehq/airbyte#14499]
## Environment
* **Airbyte version:** 0.39.7-alpha.
* **OS Version / Instance:** GCP n2-standard-4.
* **Deployment:** Kubernetes engine on GCP.
* **Source Connector and version:** Any of `BigQuery, Snowflake, Hubspot, Salesforce, Intercom, Zendesk, Outreach, Salesloft`.
* **Destination Connector and version:** Google Pub/Sub 1.0.4
* **Step where error happened:** Sync job.

## Current Behavior
We have ~450 connections. All of them have Google Pub/Sub as destination, but use different sources as listed above. We've seen some of our sync jobs get stuck and Airbyte does not kill/cancel them automatically. Canceling them and then triggering manual sync makes them work again.

## Expected Behavior
Sync jobs don't hang and complete normally. New syncs start when they are expected.

## Logs
[logs-1891060.txt](https://github.com/airbytehq/airbyte/files/9064643/logs-1891060.txt)
[logs-1820114.txt](https://github.com/airbytehq/airbyte/files/9064696/logs-1820114.txt)

## Steps to Reproduce
1. Create a connection using one of the listed sources and Google Pub/Sub as destination (but the issue could have to do with any other combination of source/destination.
2. Sync jobs might get stuck at some point.

## Are you willing to submit a PR?
No.

**Comment by marcosmarxm** [comment]
@lgomezm did you change the .env variables to increase the number of connections in parallel?

**Comment by lgomezm** [comment]
Hi @marcosmarxm. I don't think we did something like that. Could you tell me what env variable are you talking about? @prasrvenkat Do you know if maybe we have changed any variable to do that?

**Comment by prasrvenkat** [comment]
> Hi @marcosmarxm. I don't think we did something like that. Could you tell me what env variable are you talking about? @prasrvenkat Do you know if maybe we have changed any variable to do that?

@lgomezm 
We have not changed, we can try bumping it up. The environment variables he is talking about are
```
SUBMITTER_NUM_THREADS
MAX_X_WORKERS, where X is SPEC, SYNC, CHECK and DISCOVER
```

@marcosmarxm 
But I think our problem is not pending to start (which could be solved by bumping the variables above), but running jobs not stopping somehow and stays running/hung without being cancelled. Would bumping these limits help in that situation too? I am not sure how, but let me know.

**Comment by marcosmarxm** [comment]
This issue was fixed in latest version where Temporal wasn't checking for long-running syncs, @prasrvenkat can you upgrade to latest and test again?

**Comment by prasrvenkat** [comment]
> This issue was fixed in latest version where Temporal wasn't checking for long-running syncs, @prasrvenkat can you upgrade to latest and test again?

Thanks @marcosmarxm , will give it a try. cc @lgomezm

**Comment by evantahler** [comment]
Closing this issue for now - please re-open if you are still having trouble.
