### ISSUE TITLE
source-postgres: make `withConnectionTimeoutMs` configurable

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#14498]
## Tell us about the problem you're trying to solve
The current connection to JDBC database is created with a hardcoded value for `connectionTimeoutMs`of `60000`.
This can cause problems according to specific database setup and context.

## Describe the solution you’d like
We could make the JDBC params override this value. 
The `withConnectionTimeoutMs` builder method that changes the timeout is not used by any connector.

## Additional context
[Related forum conversation](https://discuss.airbyte.io/t/source-psql-hitting-oom-without-doing-anything-with-the-data-and-failing/1715/7)

**Comment by anton-epsagon** [comment]
@grishick no, those seem to be ignored.
I'm currently trying to change the timeout value in airbyte-db/db-lib/src/main/java/io/airbyte/db/factory/DataSourceFactory.java locally to see if that helps

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/14498?planning-poker) with ZenHub @edgao @ryankfu @subodh1810 @tuliren

**Comment by grishick** [comment]
Notes on testing:

- unit test should verify that the timeout is passed onto Hiraki JDBC driver
- we should not be adding an integration test for this, because we are not testing the JDBC driver itself

**Comment by ryankfu** [comment]
Issue has been resolved in this PR https://github.com/airbytehq/airbyte/pull/15226
