### ISSUE TITLE
Destination MSSQL: failing with cannot participate in a columnstore index

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#14493]
- Is this your first time deploying Airbyte?: Yes :+1:
- OS Version / Instance: Almalinux
- Memory / Disk: 4Gb / 20 GB
- Deployment: Docker
- Airbyte Version: v0.39.30-alpha
- Source name/version: Files CSV
- Destination name/version: MS SQL 2016 on Windows
- Step: sync
- Description: syncing does not work and throws various errors - depending on my setting for the CSV file which is: https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/sunshine_duration/regional_averages_sd_year.txt .

https://discuss.airbyte.io/t/csv-files-source-special-settings-needed-to-sync-to-ms-sql/1720

**Comment by harshithmullapudi** [comment]
[logs-35.txt](https://github.com/airbytehq/airbyte/files/9062995/logs-35.txt)
[logs-47.txt](https://github.com/airbytehq/airbyte/files/9062996/logs-47.txt)

Here are the logs

**Comment by mmoole** [comment]
pardon, since this is about MS SQL and not MySQL, would it be possible to adjust the title accordingly?

**Comment by mmoole** [comment]
with a newer version of Airbyte and the connector this error regarding MSSQL seems to be no more reproducible 👍🏼

**Comment by etsybaev** [comment]
Based on provided example (see link below) I see that we have 2 columns with the same name "Jahr;Jahr;"
https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/sunshine_duration/regional_averages_sd_year.txt

The issue may be similar to https://github.com/airbytehq/airbyte/issues/5171
https://github.com/airbytehq/airbyte/issues/5171

**Comment by etsybaev** [comment]
It seems to work now. I assume that previously it failed as we had 2 fields with the same name and different types. But please be aware that there is some minor name transforming that will be done to make names a little bit different. 


![Selection_407.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/569f6b91-5b7c-494d-80cb-348c08e5a01e)
![Selection_408.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/eee65c73-f9b8-4a57-9887-f42e33c986c3)
