### ISSUE TITLE
[low-code connectors] expose expanded config-based connector definition

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#14511]
## Tell us about the problem you're trying to solve
Config-based connector definitions can be difficult to parse when there are a lot of references.

## Describe the solution you’d like
We should log the connector definition to debug after all the references have been dereferenced when the debug flag is enabled

Steps:
- [x] https://github.com/airbytehq/airbyte/issues/3078
- [ ] Update the components factory so it can expand the component definitions without actually instantiating the python objects ([essentially returning the full_definition instead of calling create_partial.create](https://github.com/airbytehq/airbyte/pull/14455/files#diff-4795f61b18fa2fe8c208da8b2c2aa23d5b6674c8e2646588c819c3696839d117R50-R55)). This step will be done as part of https://github.com/airbytehq/airbyte/issues/14484

**Comment by girarda** [comment]
grooming note: can be done as part of https://github.com/airbytehq/airbyte/issues/14633

**Comment by brianjlai** [comment]
@girarda as far as I can tell we should be doing this already as part of the validation work. I ran greenhouse w/ the --debug flag on and we have a fully expanded json dereferenced. Going to close this one out
