### ISSUE TITLE
Source Chargebee: `transaction` stream is broken

### ISSUE THREAD

**Issue by migue-m** [airbytehq/airbyte#14527]
## Environment
- **Airbyte version**:  0.30.18-alpha
- **Source Connector and version**: Chargebee 0.1.11
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Sync job

## Current Behavior
The sync process for the `transaction` stream does not finish correctly, the following error appears in the log:
<img width="1346" alt="chargebee-transaction-error-log" src="https://user-images.githubusercontent.com/92232167/177960002-c74fb623-55b3-4638-a9a3-68355264f9d3.png">

## Expected Behavior
The process should finish without errors, even if no records are processed.

## Logs

[logs-19307-0 (1).txt](https://github.com/airbytehq/airbyte/files/9070699/logs-19307-0.1.txt)

## Steps to Reproduce
1. Starting syncing SourceChargebee
2. Review sync log

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @migue-m I added it to connector backlog. Chargebee is an alpha connector and can take some time until get solved. Also you can submit a PR contribution correcting the issue.

**Comment by mustangJaro** [comment]
[This](https://github.com/airbytehq/airbyte/issues/11249) looks like the same issue

**Comment by marcosmarxm** [comment]
Closed by #14672

**Comment by migue-m** [comment]
@marcosmarxm Thank you very much (all of you) for your help!! 
We have tried launching the synchronization process again and now we get a different error:

![image](https://user-images.githubusercontent.com/92232167/179057295-a093dfbb-aa59-4fb7-bc4a-703b496ff771.png)
...
![image](https://user-images.githubusercontent.com/92232167/179057379-89d84669-86e5-4426-aa44-676b387093e9.png)

**Comment by marcosmarxm** [comment]
Oh this looks a normalization error with the schema. Sorry to ask that, but can you open a new github issue? I think it's easy to fix it!

**Comment by migue-m** [comment]
Sure, no problem! Thank you once again
