### ISSUE TITLE
Source Google Analytics: missing UTM parameters

### ISSUE THREAD

**Issue by sergiworkwize** [airbytehq/airbyte#14537]
## Environment
- **Airbyte version**:  example is 0.35.57-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Google Analytics 0.1.0
- **Destination Connector and version**: Redshift
- **Step where error happened**: Syncing

## Current Behavior
In the current connection some important UTM parameters are missing in the _traffic_sources_ stream such as the Campaign, the Content and the Term data. The Source and Medium are being synced though. 

Is there a reason why this data is missing?

**Comment by harshithmullapudi** [comment]
Hey team will look into this soon. It would be more helpful if you would help with replication steps

**Comment by marcosmarxm** [comment]
Closing because this connector will be deprecated soon.
