### ISSUE TITLE
SATs should verify that all streams have at least one supported sync mode

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#14547]
As discovered in https://github.com/airbytehq/oncall/issues/290, we currently don't check that all streams have at least one supported sync mode. This causes weird things to happen in the UI, and is literally never desirable. SATs should verify that this doesn't happen.

Notes: 
1. Should validate it's an accepted enum value, and there's more than zero

**Comment by sherifnada** [comment]
I wonder if we can get this verification "for free" by adding `minItems` in the json schema

**Comment by alafanechere** [comment]
@sherifnada this SAT test was added in https://github.com/airbytehq/airbyte/pull/14800 (sorry I forgot I already wrote this test while we were planning the sprint)
