### ISSUE TITLE
Remove useRouter hook

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#14557]
As discussed offline, we want to remove the useRouter hook, due to several issues (lose TypeScript types, renaming - and thus teaching - outdated react router methods, weird merging of query parameters and path parameters.

We should do the following:

* Remove the useRouter hook
* Replace all usages of useRouter with the corresponding direct react router hooks (useNavigate, useParams, etc.)
* Add types where required (e.g. we should type the useParams hooks properly, to prevent some any pollution we have at the moment)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
