### ISSUE TITLE
New Source: OpsGenie

### ISSUE THREAD

**Issue by adamschmidt** [airbytehq/airbyte#14566]
## Tell us about the new connector you’d like to have

* Which source and which destination?

We want to source information from OpsGenie into our Snowflake warehouse.

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB?

No. The current cloud platform API version is adequate.

## Describe the context around this new connector

* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.

We ingest a lot of operational data into our data platform using other Airbyte connectors. We want to add OpsGenie data using our existing tools and services to keep our operational life simple.

* How often do you want to run syncs?

Daily

* If this is an API source connector, which entities/endpoints do you need supported?

Priority is Team, User, Alerts, and Incidents.

APIs listed on the [OpsGenie Documentation](https://docs.opsgenie.com/docs/api-overview)

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using

We would need to build custom extract job/s and coordinate with Airflow.

## Are you willing to submit a PR?

Yes

**Comment by harshithmullapudi** [comment]
Hey @adamschmidt thanks for creating the issue. Also during your PR work do let us know if you need some help.
