### ISSUE TITLE
New Source: Amplitude

### ISSUE THREAD

**Issue by dubravcik** [airbytehq/airbyte#1457]
Hi, I'd like to export event data from Amplitude. 
Currently we use a custom script using Export API https://developers.amplitude.com/docs/export-api. Basically it is just one big table. There are two important json columns (event_properties and user_properties), I suggest to keep them as is (as text column) and do not try to expand these columns.
Thanks

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368204144246) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
Hi @dubravcik , 

Thanks for opening this issue. Would you be able to share which destination are you sending your Amplitude data to, and whether you're using the [S3 export feature](https://help.amplitude.com/hc/en-us/articles/360044561111-Amazon-S3-Amplitude-Integration#prerequisites) or exporting directly from the REST API? 

Would you be open to contributing the Amplitude connector to Airbyte? We'd be happy to support with any questions, pairing sessions, code contribution or anything else needed. No worries if not, we can prioritize against our roadmap.

**Comment by dubravcik** [comment]
Currently we use SQL Server datawarehouse #613   Exporting from REST API (but we may consider migration to cloud datawarehouse)

I am not a developer, so probably I won’t be capable to contribute though I’d like to.

**Comment by vitaliizazmic** [comment]
## Integration Vetting
The integration hasn't already been vetted

**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**
Authenticate via basic authentication with the credentials YOUR_API_KEY:YOUR_SECRET_KEY. More information on how to find your API and Secret Keys [here](https://help.amplitude.com/hc/en-us/articles/235649848#project-general-settings).

**Creating an account**
We can try [free account](https://amplitude.com/get-started)

**How to populate the account with data?**
It is need account to answer this question.

**Available streams for sync**

 
**Integration supports incremental sync?**
Yes

**Other information/blockers**
The results are returned as a zipped archive of JSON files, one or multiple files per hour.

**Comment by arhip11** [comment]
Account created under aleksandr@airbyte.io, integration-test@airbyte.io was already taken.
Organization - airbyte.

**Comment by sherifnada** [comment]
@arhip11 my guess is that one of us already signed up for Amplitude but forgot to put credentials in lastpass. I reset that password and replaced aleksandr@airbyte.io with it in lastpass.

**Comment by petterw** [comment]
Seconding this, it would be useful :)

**Comment by sherifnada** [comment]
@petterw roger that!

**Comment by sherifnada** [comment]
FYI Airbyte has an account with Amplitude which contains data. I can generate an API token when we begin implementation.

**Comment by yevhenii-ldv** [comment]
## Task breakdown
- [ ] Create source scaffolding and populate schemas folder (4h)
- [ ] Implement spec, check and discover (2h)
- [ ] Implement FullTable read (5h)
- [ ] Implement Incremental read (3h)
- [ ] Handle rate-limiting and back off (1h)
- [ ] Integrate with acceptance tests (3h)
