### ISSUE TITLE
normalization: handle records > 1MB for redshift SUPER type

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#14573]
## Tell us about the problem you're trying to solve
Redshift's normalization generates SUPER object whose size exceeds the limit of 1MB:
```
022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      error:  Invalid input
2022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      code:      8001
2022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      context:   SUPER value exceeds export size.
2022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      query:     7075389
2022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      location:  partiql_export.cpp:9
2022-07-06 06:17:18 e[42mnormalizatione[0m > 06:17:18      process:   query0_91_7075389 [pid=32005]
```

## Describe the solution you’d like
Normalization should  explicitly drop records > 1MB or restructure these records to make them lower than 1MB.

Seeing a similar issue with [on-call airbytehq/alpha-beta-issues#697](https://github.com/airbytehq/alpha-beta-issues/issues/697)

[SUPER type](https://docs.aws.amazon.com/redshift/latest/dg/r_SUPER_type.html) from Redshift docs

**[Related forum topic](https://discuss.airbyte.io/t/hubspot-normalization-failure/1739/5)**

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Augustin on 2022-07-11 at 13:03:*

<blockquote><div class="zd-comment" dir="auto">I created an [issue](https://github.com/airbytehq/airbyte/issues/14573) on our repo for this error. Please subscribe to receive updates.&nbsp;<br></div></blockquote>

**Comment by validumitru** [comment]
This error is also happening while trying to sync _engagements_ in the Hubspot connector.

**Comment by jan-benisek** [comment]
I encountered the same today (Airbyte 0.40.18, connector version 0.2.3). Any idea when will this be fixed 🙏

**Comment by jena-binay** [comment]
I'm on Airbyte 0.4.27 getting the same error on Jira connector

**Comment by validumitru** [comment]
This error just started breaking the Hubspot sync for us today :(

**Comment by cidraljunior** [comment]
I am getting the same error. Any fix?

**Comment by pranasziaukas** [comment]
Running into this while syncing HubSpot Companies and Contacts.

**Comment by josephbrownskilljar** [comment]
This is a limitation in Redshift and a solution is now in pre-release
https://docs.aws.amazon.com/redshift/latest/dg/limitations-super.html

On 4/18/23, Pranas Ziaukas ***@***.***> wrote:
> Running into this while syncing HubSpot Companies and Contacts.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/airbytehq/airbyte/issues/14573#issuecomment-1513568955
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
Joseph Brown
Database Engineer
***@***.***
206-579-2889

**Comment by evantahler** [comment]
Closing this issue as normalization is going away https://github.com/airbytehq/airbyte/issues/26028

**Comment by pranasziaukas** [comment]
> normalization is going away

Could you expand a bit by any chance @evantahler?

For example, we had issues with HubSpot (source) records that were flowing to Redshift (destination), and because those records were large JSON objects they'd exceed Redshift's SUPER limit (as far as I understand).

What does the end of normalization imply for the above?
