### ISSUE TITLE
Stripe Customer stream fails at normalization

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14572]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1269](https://airbyte7538.zendesk.com/agent/tickets/1269)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu,</li>
<li style="padding-bottom: 10px;">Memory / Disk: you can use something like 4Gb / 1 Tb</li>
<li style="padding-bottom: 10px;">Deployment:  EKS</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.17</li>
<li style="padding-bottom: 10px;">Source name/version:  Stripe 0.1.33</li>
<li style="padding-bottom: 10px;">Destination name/version: Snowflake 0.4.28</li>
<li style="padding-bottom: 10px;">Step: Normalization</li>
</ul>
<p dir="auto">Stripe customer card fails at normalization</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">2022-06-21 23:48:28 normalization &gt; 23:48:28  Completed with 1 error and 0 warnings:
2022-06-21 23:48:28 normalization &gt; 23:48:28  
2022-06-21 23:48:28 normalization &gt; 23:48:28  Database Error in model CUSTOMERS_CARDS (models/generated/airbyte_tables/STRIPE_NEW/CUSTOMERS_CARDS.sql)
2022-06-21 23:48:28 normalization &gt; 23:48:28    100069 (22P02): Error parsing JSON: unknown keyword "list", pos 5
2022-06-21 23:48:28 normalization &gt; 23:48:28    compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/STRIPE_NEW/CUSTOMERS_CARDS.sql
</code></pre>
<p dir="auto">Full logs: <a href="https://discuss.airbyte.io/uploads/short-url/9cDVoTRJC2kMBXxU3yIkj4j0PAt.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-468.txt</a> (2.0 MB)</p> 

[<a href="https://discuss.airbyte.io/t/stripe-customer-stream-fails-at-normalization/1537/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-22 at 13:23:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Comment made from GitHub by marcosmarxm on 2022-06-22 at 13:23:</p>
<p dir="auto">Added issue to connector team backlog.</p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-22 at 14:36:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">This GitHub issue has been closed by marcosmarxm on 2022-06-22 at 14:36.</p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-23 at 12:33:*

<blockquote><div class="zd-comment" dir="auto">Jagannath this version of Airbyte had an issue with normalization, could you try to upgrade to 0.39.20+?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-23 at 15:45:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> , does 0.39.20 have any breaking changes from 0.39.17? We’ve had multiple issues with upgrading in the past so just want to make sure</p> 

 [<a href="https://discuss.airbyte.io/t/stripe-customer-stream-fails-at-normalization/1537/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-23 at 16:59:*

<blockquote><div class="zd-comment" dir="auto">No, the upgrade to 0.39.20 should be only a patch update.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-24 at 23:22:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> I’ve upgraded it to the latest version 0.39.24 and it fails with the same error.</p>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/uljoHILtKJ8IC8LO3I7Glky9G1K.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-9.txt</a> (285.4 KB)</p> 

 [<a href="https://discuss.airbyte.io/t/stripe-customer-stream-fails-at-normalization/1537/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 03:29:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I’ve ran the pipeline multiple times and it fails with the same error.</p> 

 [<a href="https://discuss.airbyte.io/t/stripe-customer-stream-fails-at-normalization/1537/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 12:43:*

<blockquote><div class="zd-comment" dir="auto">Sorry the long delay Jagannath, I wan't able to reproduce your issue. What is the configuration in Snowflake you're using? Internal Staging or using AWS/GCS?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 14:36:*

<blockquote><div class="zd-comment" dir="auto">Jagannath can you update your schema? Click in Refresh Source Schema<br><span style="opacity: 1;"><img src="https://airbyte7538.zendesk.com/attachments/token/JaHGM0fU9C71Xs0M3v5E4qIkT/?name=image.png"></span><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-07 at 18:27:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">We are using Snowflake internal staging and yes, I did refresh the schema multiple times.</p> 

 [<a href="https://discuss.airbyte.io/t/stripe-customer-stream-fails-at-normalization/1537/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by edgao** [comment]
saw this same issue in https://github.com/airbytehq/oncall/issues/568 - I want to say there's something interesting happening with how normalization is unnesting sub-objects. Would be really great to get an example blob from the `_raw` table if we see this happen again.

My very wild-guess hypothesis: something about how normalization-snowflake extracts sub-objects is weird? But I couldn't repro any weird behavior.

for ref: you can exactly repro the error message using this query:
```sql
select get_path(parse_json('list'), '"a"')
```

But that doesn't explain why we're trying to parse `"list"` as json.

**Comment by davydov-d** [comment]
The root cause of this failure is in the logs:
> Schema validation errors found for stream customers. Error messages: [$.cards is of an incorrect type. Expected it to be [null, array]]

The older versions of the Stripe API used to change this field's type several times. Now we have pinned the source API version we're using and the schema is corresponding the data being returned by the API.
