### ISSUE TITLE
Kustomize: S3 external logs not working

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14576]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1350](https://airbyte7538.zendesk.com/agent/tickets/1350)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: Yes</li>
<li style="padding-bottom: 10px;">OS Version / Instance: MacOS</li>
<li style="padding-bottom: 10px;">Deployment:  Kubernetes</li>
<li style="padding-bottom: 10px;">Step: Just setting up Airbyte</li>
<li style="padding-bottom: 10px;">Description: I have been following these directions for configuring logs using a S3 bucket: <a href="https://docs.airbyte.com/deploying-airbyte/on-kubernetes/#configure-logs" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">On Kubernetes (Beta) | Airbyte Documentation</a><br>
However, my S3 bucket doesn’t seem to be populating with logs</li>
</ul> 

[<a href="https://discuss.airbyte.io/t/configuring-custom-s3-logs/1616/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-06-27 at 18:57:*

<blockquote><div class="zd-comment" dir="auto">Hey @soccerbro421, thanks for your post and welcome to the community! Could you describe what your cluster setup looks like? Is it local or did you use something EKS?&nbsp;<br>&nbsp;<br>Secondly are the s3 credentials configured for both read and write access as mentioned in the guide? Finally, were you able to successfully launch a local airbyte instance?&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 14:12:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hey <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a> , Thanks for the response!</p>
<p dir="auto">I’m trying to use EKS to deploy and more specifically following eks blueprints:</p>
<div style="border: 5px solid #e9e9e9; margin-bottom: 10px; padding: 12px 25px 12px 12px;">
  <div>
      <img src="https://a0.awsstatic.com/main/images/site/fav/favicon.ico" width="16" height="16" style="height: 16px; margin-right: 3px; width: 16px;">

      <a href="https://aws.amazon.com/blogs/containers/bootstrapping-clusters-with-eks-blueprints/" rel="noopener nofollow ugc noreferrer" title="04:48PM - 20 April 2022" style="color: #006699; font-weight: bold; text-decoration: none;">Amazon Web Services – 20 Apr 22</a>
  </div>

  <div style="clear: both;">
    <div><img src="https://d2908q01vomqb2.cloudfront.net/fe2ef495a1152561572949784c16bf23abb28057/2022/04/15/EKS-Featured-image-1260x630.png" width="auto" height="auto" style="height: auto; margin-right: 10px; max-height: 80%; max-width: 20%; width: 60px;" align="left"></div>

<h3 style="font-size: 1.17em; margin: 30px 0 10px;" dir="auto"><a href="https://aws.amazon.com/blogs/containers/bootstrapping-clusters-with-eks-blueprints/" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Bootstrapping clusters with EKS Blueprints | Amazon Web Services</a></h3>

  <p dir="auto">Today, we are introducing a new open-source project called EKS Blueprints that makes it easier and faster for you to adopt Amazon Elastic Kubernetes Service (Amazon EKS). EKS Blueprints is a collection of Infrastructure as Code (IaC) modules that...</p>


  </div>

  <div style="color: #919191;">
    
    
  </div>

  <div style="clear: both;"></div>
</div>

<p dir="auto">Yes, I created and tested a IAM user and made sure I was able to update the S3 bucket as the user.</p>
<p dir="auto">Yes I am successfully able to launch a local airbyte instance.</p> 

 [<a href="https://discuss.airbyte.io/t/deploying-on-kubernetes-configuring-custom-s3-logs/1616/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-06-28 at 15:26:*

<blockquote><div class="zd-comment" dir="auto">So if I understand you correctly, you have an s3 bucket set up for logs and you also have another s3 bucket with some data that you want to move somewhere else? Did I get that right?&nbsp;<br>My guess is that something is not configured properly with the s3 bucket you set up for your logs. As a result, it ends up writing the logs to the local minio instance instead of your s3 bucket. Can you check if this is what is actually happening by accessing the logs in minio?<br>&nbsp;<br>And yes, I believe S3_LOG_BUCKET is just the name of the bucket, not the s3 url or the ARN.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-06-28 at 16:06:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Yup that’s right.</p>
<p dir="auto"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/3/30033e268fb2666099ef840d666e86073be60776.jpeg" alt="image" width="auto" height="auto" style="max-width: 100%;"></p> 

 [<a href="https://discuss.airbyte.io/t/deploying-on-kubernetes-configuring-custom-s3-logs/1616/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-05 at 14:02:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I used Kustomize deployment</p> 

 [<a href="https://discuss.airbyte.io/t/deploying-on-kubernetes-configuring-custom-s3-logs/1616/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-11 at 13:30:*

<blockquote><div class="zd-comment" dir="auto">I tried to setup a kustomize using external s3 and faced the same issue. I opened a ticket in Github <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/14576">https://github.com/airbytehq/airbyte/issues/14576</a> for further investigation. Any update I'll return to you.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-03 at 02:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi folks, any update on this issue? We’re running into the same problem where our destination is S3 which is causing this error.</p> 

 [<a href="https://discuss.airbyte.io/t/deploying-on-kubernetes-configuring-custom-s3-logs/1616/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-03 at 17:16:*

<blockquote><div class="zd-comment" dir="auto"><blockquote><p dir="auto">Hi folks, any update on this issue? We’re running into the same problem where our destination is S3 which is causing this error.</p></blockquote>Did you check the latest update in Kuberentes deployment documenqation?<br>&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-09 at 05:53:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks Marco. Is there a specific place you’re pointing to in the Kubernetes deployment documentation. I’ve been reviewing that page once a week and haven’t seen any changes regarding “configuring custom s3 log location”.</p>
<p dir="auto">Unless you’re referring to the known issue of “File sources reading from and file destinations writing to local mounts are not supported on Kubernetes.”. Wasn’t sure if that was the same issue as this.</p> 

 [<a href="https://discuss.airbyte.io/t/deploying-on-kubernetes-configuring-custom-s3-logs/1616/11" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by natalyjazzviolin** [comment]
Closing this issue due to Kustomize being deprecated.
