### ISSUE TITLE
Investigate Airbyte issues on EC2

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1458]
## Current Behavior
* A user reported that he could not get the newest version of airbyte to run on an EC2 instance [here](https://airbytehq.slack.com/archives/C01AHCDHCKE/p1609114187120300?thread_ts=1608652970.115300&cid=C01AHCDHCKE).
* I was not at my laptop so I couldn't debug it with him. The logs he provided did not show anything obvious.
* I think we should sanity check that airbyte is still working on EC2. If it is it should hopefully be a very short amount of time wasted and if it isn't then obviously we should fix.

**Comment by sherifnada** [comment]
User needed to set `API_URL=<IP_ADDRESS>`
