### ISSUE TITLE
octavia-cli: "Does not exist" error when attempting to import or generate

### ISSUE THREAD

**Issue by DustyShap** [airbytehq/airbyte#14582]
## Environment
- **Airbyte version**:  0.39.35-alpha
- **Octavia-CLI version**: 0.39.35-alpha
- **Deployment**: Kubernetes
- **Step where error happened**: `octavia import all`

## Current Behavior
Error returned for import all command:

```🐙 - Octavia is targetting your Airbyte instance running at http://airbyte-webapp:80 on workspace c4612f46-8290-46d2-8975-080f46fd8cff.
Error: Definition decd338e-5647-4c0b-adf4-da0e75f5a750 does not exists on your Airbyte instance.

```
See more notes below.

## Expected Behavior
```
Import all existing sources, destinations and connections to manage them with octavia-cli.
```

## Are you willing to submit a PR?

Potentially

## Notes
The list command lists the resources properly, 
`octavia list workspace sources` 

```🐙 - Octavia is targetting your Airbyte instance running at http://airbyte-webapp:80 on workspace c4612f46-8290-46d2-8975-080f46fd8cff.
NAME              SOURCE NAME  SOURCE ID                             
Payments Backend  Postgres     e8b905df-609c-4ca5-9966-1942a2d1667a  
<Redacted> Hubspot     HubSpot      e49b3312-ef07-42d1-8ef9-fb33ab3bce07  
```
as do the `octavia get` commands.

**Comment by DustyShap** [comment]
I am also seeing this error when attempting to generate a new source.

`octavia list connectors sources | grep postgres`

```Postgres                        airbyte/source-postgres                        0.4.31            decd338e-5647-4c0b-adf4-da0e75f5a750```

`octavia generate source decd338e-5647-4c0b-adf4-da0e75f5a750 postgres_source`


```🐙 - Octavia is targetting your Airbyte instance running at http://airbyte-webapp:80 on workspace c4612f46-8290-46d2-8975-080f46fd8cff.
Error: Definition decd338e-5647-4c0b-adf4-da0e75f5a750 does not exists on your Airbyte instance.
```

**Comment by harshithmullapudi** [comment]
<img width="1485" alt="Screenshot 2022-07-12 at 10 19 14 AM" src="https://user-images.githubusercontent.com/17528887/178410888-449b45cb-5410-4570-bca0-40f11b0fd804.png">
It was working for me could you try some other source to get more understanding

**Comment by DustyShap** [comment]
<img width="1120" alt="Screen Shot 2022-07-12 at 6 41 40 AM" src="https://user-images.githubusercontent.com/11494339/178472402-3a311248-dad6-4346-b9f0-02109fd912d2.png">

**Comment by DustyShap** [comment]
I wasn't sure if my airbyte_url should target the `webapp` or `server`, so I tried both:
<img width="1168" alt="Screen Shot 2022-07-12 at 10 25 28 AM" src="https://user-images.githubusercontent.com/11494339/178513752-2f3bf1bb-f72b-42ed-ba88-26e1cc994c97.png">

**Comment by harshithmullapudi** [comment]
@alafanechere could you help here?

**Comment by DustyShap** [comment]
Any updates on this @harshithmullapudi @alafanechere ?

**Comment by alafanechere** [comment]
Hey @DustyShap I'll try to reproduce ASAP, but I'm on PTO until the end of July.

**Comment by alafanechere** [comment]
Even if we can't reproduce now I can confirm that you're probably not the only one that faces this problem, according to our telemetry.

**Comment by DustyShap** [comment]
Just curious if there has been an update on this? Thanks again!

**Comment by harshithmullapudi** [comment]
Hey didn't get anywhere on this as we are unable to reproduce it, is it possible to get on a call so that we can try debugging this?

**Comment by DustyShap** [comment]
Sure! You can contact me at dusty@rvvup.com.

**Comment by harshithmullapudi** [comment]
Hey have you sent an email?

**Comment by jasonmaddernstudylink** [comment]
I'm facing the exact same issue - can list sources/destinations/connections - but cannot import or generate new

And update would be appreciated

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
