### ISSUE TITLE
Source Postgres (CDC): debezium does not handle era indicators (AD | BC) for 'DATE' type

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#14590]
## Current Behavior
Source-postgres in cdc mode omits era indicator. For example, the values  `1991-02-10 BC` and `1991-02-10` have the same output

## Expected Behavior
Dates with the current era (AD) and before the current era (BC) should have different outputs and era indicators should not be omitted

## Steps to Reproduce
1. Insert 2 date rows to Postgres table with the same value but different eras (e.g `1991-02-10 BC`, `1991-02-10`)
2. Run sync or datatype test
3. The output values are the same

**Comment by grishick** [comment]
This will be fixed in https://github.com/airbytehq/airbyte/issues/14628

**Comment by edgao** [comment]
implemented in https://github.com/airbytehq/airbyte/pull/15187/ - will be published as part of https://github.com/airbytehq/airbyte/pull/14534
