### ISSUE TITLE
SAT: Validate that connector spec schema changes are backwards-compatible

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#14593]
(more context in parent issue https://github.com/airbytehq/airbyte/issues/14097)

In order to ensure that a change to the connector's spec is backwards-compatible, we should add a few assertions in the SAT. 

This ticket focuses on loading the spec for the previous version of the connector, and comparing it to the current spec. The "previous version" is considered to be the latest published version of the connector by default, but should be able to be configured.

## Acceptance criteria

This ticket will be completed if our SAT suite fails when:
- New required properties have been introduced
- Existing optional properties are now required
- An existing property's type has narrowed
  - e.g. used to accept `[null, string]`, now only accepts `string`
- An existing property's enum values have narrowed
  - Used to accept [`orange`, `green`, `blue`], now only accepts [`orange`, `blue`]

We should also be able to:
- Configure which version of the connector we want to compare against (defaulting to latest)
- Skip compatibility tests in general
- Skip compatibility tests against a specific version of the connector (e.g. skip if the previous version is 1.2.3) 

### Previous connector spec

SAT config currently takes in a `connector_image` that looks like `airbyte/source-stripe:dev` - we can swap out the tag with `:latest` to get the last published image (or use whichever tag is explicitly defined in SAT config). If we don’t find an image with the latest tag, assume this is the first publish and we can skip compatibility tests.

Example of current config:

```
connector_image: airbyte/source-stripe:dev
tests:
  spec:
    - spec_path: "source_stripe/spec.yaml"
```

From there we can use the [ConnectorRunner](https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/connector_runner.py#L18) to run the `spec` command for this version.

### Assertions

To compare the specs we will need to traverse the json schema and make the corresponding checks against the other spec at the current path. There are some JSON schema traversal / utilites [here](https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/utils/json_schema_helper.py) that may be helpful.

**Comment by alafanechere** [comment]
I initialized the work on this issue by adding the capability in SAT to retrieve a previous connector spec: https://github.com/airbytehq/airbyte/pull/14954
