### ISSUE TITLE
Source Mixpanel: Wrong configuration field

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#14605]
Today, our Mixpanel source configuration settings has a field called "Project Token". However, this field should actually be "Project Secret" as outlined here: https://developer.mixpanel.com/reference/project-secret.

![image.png](https://images.zenhubusercontent.com/625df338e92f1746e446051e/161fd6fb-c9ab-4d80-b2e4-0b798150f11b)

We should update the field and description (with docs) to reflect this more accurately and confirm that the underlying code respects the Project Secret as the form of connection with this source.

**Comment by YowanR** [comment]
@YuliiaNahoha @lazebnyi This issue is impacting our customers but should be a relatively quick fix. I'll add it to our next sprint. Can you make sure it gets prioritized and tackle upfront, please?
