### ISSUE TITLE
Snowflake source: support key pair authentication type

### ISSUE THREAD

**Issue by sashaNeshcheret** [airbytehq/airbyte#14615]
## Tell us about the problem you're trying to solve
We need to add ability to use snowflake source connector with key pair authentication.

## Describe the solution you’d like
Generated private/public key pair, updated snowflake user with public key, passed path to file with private key as jdbc properties. Updated normalization. Add test for it.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by SoerenStahlmann** [comment]
I'd also need this feature and would be willing to submit a PR. Since I am new to airbyte can someone point me in the right direction where to start?

**Comment by marcosmarxm** [comment]
Closed by #40424
