### ISSUE TITLE
Databases DateTime, Date, Time data type bug (MySQL, Postgres, etc.)

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#14628]
Ref : https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1657271466983419
I was going through some of the data type tests in MySQL and I see that we convert all the time related data type values (TIMESTAMP, DATE TIME, DATE) into TIMESTAMP WITH TIEMZONE values. For instance
```  
  addDataTypeTestData(
        TestDataHolder.builder()
            .sourceType("datetime")
            .airbyteType(JsonSchemaType.STRING)
            .addInsertValues("null", "'2005-10-10 23:22:21'")
            .addExpectedValues(null, "2005-10-10T23:22:21.000000Z")
            .build());
```
^ DATETIME column value 2005-10-10 23:22:21 is being converted into 2005-10-10T23:22:21.000000Z , similarly
```    
addDataTypeTestData(
        TestDataHolder.builder()
            .sourceType("date")
            .airbyteType(JsonSchemaType.STRING)
            .addInsertValues("null", "'2021-01-01'")
            .addExpectedValues(null, "2021-01-01T00:00:00Z")
            .build());
```
^ DATE value 2021-01-01 is being converted into 2021-01-01T00:00:00Z .
The tests can be found in the class [AbstractMySqlSourceDatatypeTest](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/source/mysql/AbstractMySqlSourceDatatypeTest.java#L235)

**Comment by grishick** [comment]
- [ ] Test if we can get rid of debezium converter for data types after upgrading to new version of debezium
- [ ] Fix DataTypeUtils
We could break this down into two tasks, but the first task seems small enough.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/14628?planning-poker) with ZenHub @edgao @ryankfu @subodh1810

**Comment by grishick** [comment]
Related issue that should be fixed when this is fixed: https://github.com/airbytehq/airbyte/issues/14590

**Comment by edgao** [comment]
the converter is still necessary after the 1.9.2 upgrade; debezium converts `date` into epoch days rather than formatted into `2022-01-23` strings

**Comment by edgao** [comment]
source-postgres is completed in https://github.com/airbytehq/airbyte/issues/15259; there's still work remaining for other DB sources.

**Comment by edgao** [comment]
@grishick how do I remove this issue from the postgres epic?

**Comment by grishick** [comment]
> @grishick how do I remove this issue from the postgres epic?

done (clicked on the cogwheel next to Epics in the side bar on the right and unchecked the checkbox next to postgres epic)

**Comment by grishick** [comment]
@subodh1810 
This is still affecting MySQL and Snowflake sources (related [OC issue](https://github.com/airbytehq/oncall/issues/383)). Ideally this can be fixed at a shared class level that will fix this for all JDBC sources. However, if you determine that this approach is not feasible, please scope this issue to MySQL and open a followup issue for Snowflake source.

**Comment by edgao** [comment]
for reference: I was able to repro the issue with source-snowflake; see https://github.com/airbytehq/oncall/issues/383#issuecomment-1204588122 - it looks like timestamp and date columns are both incorrectly treated as timestamptz

**Comment by grishick** [comment]
@edgao @subodh1810 should this be renamed to MySQL scope only now that Postgres is fixed separately?

**Comment by edgao** [comment]
I think the scope of this ticket is any db/dw source, so it covers everything except postgres (e.g. the snowflake thing I mentioned above)

**Comment by grishick** [comment]
If the implementation will require connector-specific change, please file separate issues for each connector, so that we can prioritize accordingly.

**Comment by subodh1810** [comment]
Am closing this cause we have fixed MySQL and Postgres. Also going to re-estimate it. This took longer than expected. WE merged 4 big PRs to fix the two sources. Making sure CDC and non-CDC output was the same was more challenging than expected. Will file separate issues for other db sources

**Comment by dineshkumar-23** [comment]
Hello,
I am currently facing the same issue of the datetime formats as mentioned her with Airbyte. 

I have a aks cluster where airbyte and postgres db are deployed as helm charts. I have a connection in Airbyte where the source is a table in external MSSQL server and the destination is a postgres db running inside the cluster. 

I have few datetime columns in my MSSQL table where the format of value is like "2023-07-31T02:19:10Z". When I do the sync in the connection, the sync is successful and the data is written to the postgres. But the values of datetime columns in the postgres are "2023-07-31T02:19:10.000000Z".

I would like to have the same format of datetime columns as the source in my destination. 

Further details:
I am using helm chart to deploy Airbyte in my cluster.
repo: https://airbytehq.github.io/helm-charts
chart version: 0.47.16
app version: 0.50.12
source: Microsoft SQL Server (MSSQL) ALPHA
destination: Postgres

Please help me with a solution. Thanks.
