### ISSUE TITLE
Confirmation message after selecting "Remove" in Access Management

### ISSUE THREAD

**Issue by sophia-wiley** [airbytehq/airbyte#14654]
Cloud, Settings, Access Management 

When you click "Remove," it removes the user without a warning or confirmation dialog like "Are you sure you want to remove this user?"

I feel like a confirmation dialog could be helpful here because a user could accidentally click Remove. They might not know that they removed someone, or they might not know who they removed. 

<img width="1290" alt="Screen Shot 2022-07-12 at 3 08 22 PM" src="https://user-images.githubusercontent.com/106352739/178605445-a434cfe3-9199-400d-86a7-47f2bcb6774c.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
