### ISSUE TITLE
Add unit test for parsing yaml definition of all components

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#14658]
## Tell us about the problem you're trying to solve
The [test_factory file](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/unit_tests/sources/declarative/test_factory.py) contains tests for parsing and instantiating some declarative components. We should add missing tests for the components that are not covered.

**Comment by sherifnada** [comment]
assuming this is no longer needed with the pydantic move. reopen if incorrect.
