### ISSUE TITLE
Point to the technical support page if getting spec takes too long

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1466]
## Tell us about the problem you're trying to solve
As described in #1462 sometimes connector images take a very long time to download under poor network conditions. This makes it look like something is broken with Airbyte when this might not be the case. 

I'd like to add a hint in the UI that is shown to the user if getting a connector's spec in onboarding takes too long. On the following screen: 

![](https://user-images.githubusercontent.com/6246757/103244955-6e612a80-4913-11eb-9ce5-207dc3e3a27e.png)

If the loading spinner is shown for more than 10 seconds, we should show another text label below the current one which says: 

```
"Taking too long? See <a href="https://docs.airbyte.io/technical-support">here</a> for support." 
```

If it's too hard to correctly show after 10 seconds (accounting for changing connectors or any other interactions the user might have with the page), it's ok to show it from the beginning with the loading spinner. 

@johnlafleur please advise on design if needed.

**Comment by johnlafleur** [comment]
Suggestion of design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=12375%3A0

**Comment by michel-tricot** [comment]
let's make sure we open the link in a new window

**Comment by johnlafleur** [comment]
To be honest, I'm not a big fan of this page https://docs.airbyte.io/technical-support, now that I have seen it. 
I think we should have a forum with a dedicated section for technical issues, where users can browse and search for their issues. This should be a link to a specific question in that forum. 
I don't think having one section "Technical support" in Gitbook provides the best UX.
