### ISSUE TITLE
Destination BigQuery - Naming Default Schema "Default" 

### ISSUE THREAD

**Issue by erica-airbyte** [airbytehq/airbyte#14674]
## Environment
- **Airbyte version**:  cloud
- **OS Version / Instance**: n/a
- **Deployment**: cloud
- **Source Connector and version**:n/a
- **Destination Connector and version**:1.1.11
- **Step where error happened**: Sync job

## Current Behavior
When setting up BiqQuery destination and naming your defaul schema default, the first sync will succeed but the following syncs will fail with `Syntax error: Unexpected keyword DEFAULT`.

if `dataset_id="default"` syncs will fail. 

## Expected Behavior
better handling or if default schema is named default. 

## Logs
please see [this issue]for logs(https://github.com/airbytehq/oncall/issues/325) (in private repo due to Cloud privacy) 

-->

## Steps to Reproduce
1. Set up Bigquery with a default schema named "default"
2. run connection with no namespaces configuration

**Comment by johnwasserman** [comment]
Confirming I am seeing this issue for a trialer:

| Environment | Affected Workspaces | Connection Link | Case/Chat Link | Sentiment | User Data Access | Reporter |
| ---- | ---- | ------------ | --------- | ---------- | ---------- | ---------- |
| cloud | [Div Brands LLC](https://cloud.airbyte.io/workspaces/c65cecb4-1d54-48cc-b2c7-21ba1cc7e949/) | [google_ads](https://cloud.airbyte.io/workspaces/c65cecb4-1d54-48cc-b2c7-21ba1cc7e949/connections/cab846f6-5f6a-4be8-b278-a31128578497/status) | email | :ok: | N | @johnwasserman  |

Seeing this a bunch:
`Syntax error: Unexpected keyword DEFAULT at [6:9]`

switching to `airbyte` fixed it

[logs-406665.txt](https://github.com/airbytehq/airbyte/files/9189637/logs-406665.txt)

fyi @Amruta-Ranade in case it makes sense to update this in the documentation until resolved

**Comment by grubberr** [comment]
I have fixed this in this PR https://github.com/airbytehq/airbyte/pull/14683, need review
