### ISSUE TITLE
Source Jira: worklog replication speed up

### ISSUE THREAD

**Issue by rnagy90** [airbytehq/airbyte#14670]
## Tell us about the problem you're trying to solve
Replicating worklogs from jira source with large amount of issues.

## Describe the solution you’d like
It would be nice to have a separate stream for all worklogs for this API endpoint: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-worklogs/#api-rest-api-3-worklog-list-post
It should use this endpoint to request the worklog ids which is in sync with the previous request (1000 record limitation)
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-worklogs/#api-rest-api-3-worklog-updated-get

## Are you willing to submit a PR?
If this is an acceptable solution and the dev environment is compatible with windows OS without using WSL, yes.

**Comment by natalyjazzviolin** [comment]
Thank you for suggestion this feature, @rnagy90! I've tagged this with the correct team, so someone should get back to you soon!

**Comment by darynaishchenko** [comment]
For now we move this issue to on hold to collect more info from user-side and validate that we really need this kind of endpoint. If it proves that this endpoint takes a very long time to sync we will improve it.

**Comment by darynaishchenko** [comment]
@sherifnada We discussed this issue during certification to GA and decided to wait until we can collect more user data about stream-level sync times. Where I can see this data? And what time we consider as that is stream is slow?

**Comment by darynaishchenko** [comment]
moving to on hold for now, it will be implemented later

**Comment by darynaishchenko** [comment]
related https://github.com/airbytehq/airbyte/issues/30245

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
