### ISSUE TITLE
Airtable connector

### ISSUE THREAD

**Issue by dakotamccarty** [airbytehq/airbyte#1468]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Airtable both as a source and destination, but mostly as a source. For anywhere from an hourly to daily frequency.

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
We use Airtable primarily for our Finance, operations, and Sales department. However, it ties into nearly every part of our company. We use it to store requests, data, info, about anything really. It is our biggest connector of datasources tying together and syncing our Xero, Hubspot, Zendesk, and so much more. It gets a lot of data from many areas, cleans it up and adds some extra needed things, then ships it back out.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Mainly using Airbyte as a backup of data from Airtable to Redshift. But potential other uses related to company operations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368139030802) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Thanks for submitting this.

As a a note on implementation, it looks like there is a jdbc driver for
airtable. If we can use our existing JDBC infra that could make this way
easier to do.

**Comment by jdotjdot** [comment]
The only JDBC driver I'm aware of is the one from CData, which is proprietary and paid.  Do you know of an open-source one?

**Comment by knizhnikov** [comment]
Hey, I would like to look into this as I would really want to contribute.

The JDBC connection may seem to be a bit tricky considering driver limitations. Thought maybe worths to use Airtable API for this?

In my team I use Airbyte to sync data from the Airtable API using the HTTP Request connector. 
* But this doesn't yet support a forming of an Airbyte catalogue with a proper JSON schema. I use Airbyte API to specify the catalog manually though.  
* Airtable API returns only 100 records max by default, ane you have to use pagination to get all the data. 

So a dedicated connector would have much sense.

**Comment by misteryeo** [comment]
Closing this issue as we have an Airtable connector here: https://docs.airbyte.com/integrations/sources/airtable
