### ISSUE TITLE
Provide a way to specify a dataset for each source

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1469]
## Tell us about the problem you're trying to solve
If I have multiple sources for 1 Destination, i would love to specify different datasets for different sources.

**Comment by ChristopheDuong** [comment]
Duplicates https://github.com/airbytehq/airbyte/issues/1119

**Comment by davinchia** [comment]
Closing as duplicate. Feel free to open if I'm mistaken.
