### ISSUE TITLE
Update Destination Connection Manager (Java CDK) to emit legacy State messages in chronological order

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14716]
From https://github.com/airbytehq/oncall/issues/339

Currently, the connection manager used in our Java destinations collects legacy state messages and emits them in alphabetical order.  However, this can result in the merged legacy "data" state property that is saved by the platform not being the most recent version:

```
(user records...)
STATE: {data:{state: {users: cursor123}}, stream: {users: cursor123}}
(order records...)
STATE: {data:{state: {users: cursor123, orders:cursorABC}}, stream: {orders: cursorABC}}

Combined State: 
{
  Orders: [{data:{state: {users: cursor123, orders: cursorABC}}, stream: {orders: cursorABC}}],
  Users: [{data:{state: {users: cursor123}}, stream: {users: cursor123}}]
}

We save from user
 [{data:{state: {users: cursor123}}, stream: {users: cursor123}}] ← Orders legacy state is missing! 
```

In this example, since the "users" state was sent last (alphabetically), the part of the combined state including "orders" was missing.  Since the destination received the "orders" state most recently, that should be the final state returned to the platform by the destination once the records are committed. 

This story requires that we update and re-publish the following destinations.  We [decided](https://docs.google.com/document/d/1_0bZxv4owY7ZXdgAR9iqTGD8OUEHoR2jsJJFGOaJ9cA/edit) that we *do* need to re-publish these destinations because users have an easy time upgrading connectors, and a hard time upgrading the platform.  Updating the platform will also fix the problem (which is what we do for Airbyte cloud), but we currently lack a way to notify users that there is a platform upgrade.

Publishing the updated connectors is done via https://github.com/airbytehq/airbyte/issues/14851

**Comment by evantahler** [comment]
cc @andyjih - another instance where if we had a way in-product to notify users of a bug & upgrade, we could have skipped upgrading all these connectors and relied on an up-to-date platform instead.

**Comment by lmossman** [comment]
This explanation from Subodh is a great summary of the problem here: https://github.com/airbytehq/oncall/issues/339#issuecomment-1184637742

Solution will looking something like the DestStreamStateLifecycleManager class recording the timestamp that it received the state messages it is keeping track of, so that it can emit them ordered by those timestamps instead of ordered alphabetically

**Comment by andyjih** [comment]
@evantahler I'm closing this issue was I believe this was handled in: https://github.com/airbytehq/airbyte/issues/15224

Let me know if I'm mistaken!
