### ISSUE TITLE
Minio secret not found if helm release name is not "airbyte"

### ISSUE THREAD

**Issue by tim-werner** [airbytehq/airbyte#14711]
## Environment
- **Airbyte version**: v0.39.36-alpha
- **Deployment**:  Kubernetes
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Airbyte server and worker pods are stuck in CreateContainerConfigError *

## Expected Behavior
*All pods should be provisioned*

## Logs

│   Warning  Failed       2m16s (x11 over 4m15s)  kubelet, .compute.internal  Error: secret "airbyte-minio" not found                                                                                                  

## Steps to Reproduce
1.  helm install airbyte-test . --namespace airbyte

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Closed by #14713
