### ISSUE TITLE
Name field should get a default value when creating a connection

### ISSUE THREAD

**Issue by SofiiaZaitseva** [airbytehq/airbyte#14726]
## Environment
- **Airbyte version**:  0.39.34-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: OSS
- **Step where error happened**: Setup new connection

## Steps to Reproduce
1. Go to Connections -> Setup source -> Setup destination
2. Check the 'Name' field

## Current Behavior
The name field's value isn't pre-filled-out. Also isn't marked as mandatory.

## Expected Behavior
The name field's value is pre-filled-out and marked as mandatory.

![image](https://user-images.githubusercontent.com/108751383/179064340-19005310-fcc4-4dff-89e6-58f9ff9e4d69.png)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Marking it mandatory has been addressed via https://github.com/airbytehq/airbyte/pull/14946

I'll leave this open to track filling in a default value.
