### ISSUE TITLE
Clearly show that there 3 phases in each sync summary (Source, Raw Destination, Normalized Destination)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14723]
When viewing the summary of a sync, we currently show the count of "rows emitted" and "rows committed".  However, if a sync has normalization enabled, "rows committed" doesn't really mean that the data is in the final normalized table that the user expects.  We can be more clear showing that there are 3 steps to the sync:

1. "records emitted" -> "source records emitted"
2. "records committed" -> "destination raw records committed"
3. (new) -> "destination records normalized"

Before

<img width="1561" alt="Screen Shot 2022-07-14 at 11 28 05 AM" src="https://user-images.githubusercontent.com/303226/179056231-7a0ffb5e-7e7f-4167-b1f3-37f774e6afe2.png">

After

<img width="1561" alt="Screen Shot 2022-07-14 at 11 29 19 AM" src="https://user-images.githubusercontent.com/303226/179056248-985d1b3a-d69c-4fc7-aaaa-47174f1a7a52.png">

Showing both "rows committed" and "rows normalized" also makes it clear that the sync moved the data, but something went wrong in the normalization step.

If normalization is disabled, we could skip that portion of the display

**Comment by evantahler** [comment]
cc @bleonard

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by gosusnp** [comment]
Feels like it’s going in the right direction, this part is a blackbox and it hides details that impact billing and usability differently, we should be clearer about it.

About the change itself, I am thinking of couple of things:
* The visualization feels hard to me. I never really read those, I find it too tiring to read rows of volumes, I’d rather see a graph of the data synced over time at the top.
* normalization is probably a hard concept in its current form. If my memory is correct, I think dedup is part of normalization which makes this number a bit harder to interpret.

**Comment by davinchia** [comment]
Closing this since this is no longer relevant.
