### ISSUE TITLE
Provide better UX to select streams when configuring a connection

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1473]
## Tell us about the problem you're trying to solve
My source has 300 tables, I only want to select 10. Right now it is not easy

## Describe the solution you’d like
Two pieces:

* streams should be ordered
* streams should be searchable

## Describe the alternative you’ve considered or used
Manually searching

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368080944504) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
reported by @ckaiser-graniterock

**Comment by davinchia** [comment]
I also want the ability to mass configure sync modes instead of going configuring them per table.

**Comment by davinchia** [comment]
The chosen sync mode can also be clearer. Feedback from slack user: https://airbytehq.slack.com/archives/C01MFR03D5W/p1623649205486900

**Comment by marcosmarxm** [comment]
This can be closed @timroes ?
