### ISSUE TITLE
Snowflake _SCD table not empty after reset

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#14747]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1527](https://airbyte7538.zendesk.com/agent/tickets/1527)
**Priority:** normal
**Group:** User Success Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px;">Memory / Disk: JOB_MAIN_CONTAINER_MEMORY_REQUEST=1Gi, JOB_MAIN_CONTAINER_MEMORY_LIMIT=1Gi</li>
<li style="padding-bottom: 10px;">Deployment: Kubernetes v1.22.9</li>
<li style="padding-bottom: 10px;">Airbyte Version: v0.39.17-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: Postgres v0.4.18</li>
<li style="padding-bottom: 10px;">Destination name/version: Snowflake v0.4.30</li>
<li style="padding-bottom: 10px;">Step: Reset</li>
<li style="padding-bottom: 10px;">Description: I have a connection with five tables, all incremental + deduped history. I needed to change the key for tracking changes so I reset the data and re-synced. Then I was alerted by my team about duplicates in the data of these tables. I noticed that after running a reset, the _SCD tables were not being emptied and continued to have the old data. I truncated the _SCD tables after a reset and then duplicates did not appear.</li>
</ul>
<p dir="auto">I have attached an image of an _SCD table still having rows after running a reset.<br>
</p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/d/d46480b44bd48ff0f6feb96d93902c3c0495a787.png" title="Screen Shot 2022-07-11 at 3.20.49 PM" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/d/d46480b44bd48ff0f6feb96d93902c3c0495a787_2_690x289.png" alt="Screen Shot 2022-07-11 at 3.20.49 PM" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>Screen Shot 2022-07-11 at 3.20.49 PM</span><span>1636×686 77.7 KB</span>
</div></a></div><p dir="auto"></p> 

[<a href="https://discuss.airbyte.io/t/snowflake-scd-table-not-empty-after-reset/1798/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-15 at 14:24:*

<blockquote><div class="zd-comment" dir="auto">Hello Andrew sorry the long delay tor reply here!<br>I created the issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/14747">https://github.com/airbytehq/airbyte/issues/14747</a> in Github to solve the problem.&nbsp;<br>When this is solved I'll return to you here.<br></div></blockquote>

**Comment by ChristopheDuong** [comment]
sounds like a duplicate of https://github.com/airbytehq/airbyte/issues/5417?

**Comment by marcosmarxm** [comment]
Duplicate of #5417
