### ISSUE TITLE
Zoho CRM: Logo Update

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#14754]
## Tell us about the problem you're trying to solve

The Zoho logo used on the Airbyte website is incorrect [https://airbyte.com/connectors/zohocrm](url)

<img width="1156" alt="Screen Shot 2022-07-15 at 10 43 32 AM" src="https://user-images.githubusercontent.com/26179814/179282046-5642e195-ded4-4e79-a8ce-214d5c8e059f.png">

## Describe the solution you’d like

We should replace the Zoho logo used currently on the website with the new one found here: [https://www.zoho.com/branding-kit.html](url)

The correct logo should look like this:
<img width="179" alt="Screen Shot 2022-07-15 at 10 49 20 AM" src="https://user-images.githubusercontent.com/26179814/179282217-1484fe70-b2ee-4bc7-9d7a-5e90c9fe074a.png">

**Comment by YuliiaNahoha** [comment]
@airbytehq/frontend could someone update this logo? Thanks!

**Comment by misteryeo** [comment]
We've resolved this now - thanks!
