### ISSUE TITLE
Allow disabling raw json tables to save space

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1475]
Storing `_raw` versions of tables effectively double the storage necessary to replicate a table. For many use cases this won't be _that_ expensive, but this concern has been raised by at least one community member.

**I'm creating this ticket to track interest in disabling raw outputs.**
**Please respond/comment if this is important for your use case.**

Since we use raw json tables to compute normalized tables, this would be a non-trivial change. If this is a major pain point, however, we should look into addressing it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368204657430) by [Unito](https://www.unito.io)

**Comment by grishick** [comment]
This will happen implicitly for tabular sources when we implement `fast lane`

**Comment by marcosmarxm** [comment]
@evantahler with Destination v2 this won't be a problem anymore, correct?

**Comment by evantahler** [comment]
Closing this issue.  We are going to keep storing both the raw and typed tables.  This is important for soft resets and error handling.  See https://github.com/airbytehq/airbyte/issues/26028 for more information
