### ISSUE TITLE
Determine minimum checkpointability thresholds for Sources and Destinations

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14769]

**Comment by ChristopheDuong** [comment]
@alex-gron Can we close this issue?

**Comment by alex-gron** [comment]
See Metabase Dashboard here: https://airbyte.metabaseapp.com/dashboard/165-connector-checkpoint-ga-thresholds?source_threshold_(1_msg%252F_x_mins)=5&dest_threshold_(1_msg_%252F_x_mins)=15

**Comment by evantahler** [comment]
cc @alex-gron 
This is completed by the [Connector Checkpoint Metrics Recap](https://docs.google.com/document/d/1bUnvBp9lMjDhnLoStdBn2H0U5qZl2Lw0WduUZKKxa6g/edit#heading=h.b3ufh6ripp74).

In short:
* Sources: Send at least one STATE message every 5 minutes.  Most sources are doing this today
* Destinations: Flush, and echo at least one STATE message at least once every 15 minutes. Many destinations are not doing this today.

**Comment by evantahler** [comment]
ha! we both commented at the same time
