### ISSUE TITLE
Exchange Rates API - set up source ('You have not supplied a valid API Access Key.')

### ISSUE THREAD

**Issue by bigdatawonders** [airbytehq/airbyte#14779]
## Environment
- **Airbyte version**:  0.39-24-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Exchange Rates Api ALPHA 0.2.6
- **Destination Connector and version**: N/A
- **Step where error happened**: Setup new connection

## Current Behavior
*After putting connector inputs I get error You have not supplied a valid API Access Key.*

## Expected Behavior
*Should have passed the test and setup the connector*

This probably due to the new API endpoint for new users. The exchange rates API key is now provided through https://apilayer.com/
Might be that additional parameters in API call are needed to identify the correct service.

RJZ

**Comment by bigdatawonders** [comment]
Hello @sajarin . I am not a great with Airbyte CDK yet. Would be awesome to have more examples and resources. 
Also, I am currently on a big project until end of September, so it would be difficult to find time for the connector :(

**Comment by sajarin** [comment]
Hey @bigdatawonders, no worries! Thanks for letting us know of the issue. I'll try investigating this and pushing a fix myself.

**Comment by bigdatawonders** [comment]
Hey @sajarin, any updates on this connector?

**Comment by sajarin** [comment]
Hey @bigdatawonders, sorry about the delay. I haven't been able to devote much time to this but will prioritize it next week. Thanks for reminding me!

**Comment by jonathanneo** [comment]
Hi there, I'm a community contributor. A PR created to fix this issue can be found here: https://github.com/airbytehq/airbyte/pull/15884

**Comment by sajarin** [comment]
Thanks for your contribution @jonathanneo, one of our maintainers will take a look at it and hopefully get it merged soon! Thanks for jumping on this issue!

**Comment by bigdatawonders** [comment]
@sajarin when we could expect the merge to happen? Thanks a bunch!

**Comment by sajarin** [comment]
@bigdatawonders expect the merge to happen later this week, depending on when we get a new integration account for the API. Sorry for the delay!

**Comment by sajarin** [comment]
@bigdatawonders we have the integration account now, I'll circle back today and get it merged.

**Comment by sajarin** [comment]
@bigdatawonders thanks for the wait, the PR has been merged! This connector should be working with new API keys from APILayer now. Closing this but willing to address any new concerns in new issues. Thanks @jonathanneo for the PR!
