### ISSUE TITLE
octavia-cli: manage custom connectors with octavia

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#14787]
In a config as code project to manage Airbyte it'd be useful to declare custom connectors (source/destination definition) from the CLI and be able to deploy these custom connectors on multiple Airbyte instances.

https://github.com/airbytehq/airbyte-internal-issues/issues/476 must first be implemented because a custom definition UUID is different on each instance).

**Comment by AlexisVLRT** [comment]
Hi! 

Do you happen to have an update on this story? 
We would love to be able to use Octavia to deploy custom sources through our CI/CD.
Is there a workaround we could use in the meantime ?

Thanks for the hard work!

**Comment by isaccavalcante** [comment]
This would be really helpful
