### ISSUE TITLE
Source Shopify: Support Shopify Plus Streams (Gift Cards and Users)

### ISSUE THREAD

**Issue by GabrielGLevine** [airbytehq/airbyte#14797]
## Tell us about the problem you're trying to solve
I would like access to the [User](https://shopify.dev/api/admin-rest/2022-04/resources/user) and [Gift Card](https://shopify.dev/api/admin-rest/2022-04/resources/gift-card) resources, which are only available from Shopify Plus instances.

## Describe the solution you’d like
The Shopify streams to select are [already filtered](https://github.com/airbytehq/airbyte/blob/dd97278a9c9976412f6f96e1762c72d4bff562df/airbyte-integrations/connectors/source-shopify/source_shopify/source.py#L501) by available user_scopes. Because these resources are gated behind Plus [access scopes](https://shopify.dev/api/usage/access-scopes#authenticated-access-scopes)—read_users, read_gift_cards—these resources can be made available when these scopes are present.

## Describe the alternative you’ve considered or used
Currently using a custom fork of the Shopify Singer Tap.

## Additional context
N/A

## Are you willing to submit a PR?
Yes

**Comment by lazebnyi** [comment]
Duplicate - https://github.com/airbytehq/airbyte/issues/26562
