### ISSUE TITLE
Source: Chargebee 0.1.12

### ISSUE THREAD

**Issue by migue-m** [airbytehq/airbyte#14796]
## Environment
- **Airbyte version**:  0.30.18-alpha
- **Source Connector and version**: Chargebee 0.1.12
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Sync job

## Current Behavior
The sync process ends with an error when creating the transaction table with the latest version of the connector.

## Expected Behavior
The process should end without errors and with the transaction stream writing data to BigQuery.

## Logs
![image](https://user-images.githubusercontent.com/92232167/179552576-4ef727e8-da86-45e6-a712-5f017bab2d25.png)
...
![image](https://user-images.githubusercontent.com/92232167/179552682-f4e4dd1c-3b0f-4ac1-9283-1f619ab8300f.png)

## Steps to Reproduce
1. Launch the process
2. Review the logs

**Comment by harshithmullapudi** [comment]
Hey could you share the complete logs file

**Comment by harshithmullapudi** [comment]
Gotcha looks a issue with schema
