### ISSUE TITLE
Google Cloud Storage destination

### ISSUE THREAD

**Issue by pualien** [airbytehq/airbyte#1479]
## Tell us about the new integration you’d like to have
Google Cloud Storage is a massive used destination for building a data lake on GCP. If we can sync to that that would be awesome.

As an idea, the destination should have options to choose bucket and base path destination, and more over file type (parquet, avro) and Hive partitioning mode (so for ex. y=2020/m=12/d=30/data.part1.parquet). 
In combo with an incremental source, the new file names should have something like data.part2.parquet in order not to overwrite existing files.

## Describe the context around this new integration
Saving compressed files in cloud storage,Airbyte could be efficiently used to build a data lake on GCP. So for ex. Reading Hive partitioned tables with DataProc or DataFlow, using Presto, Spark and even Big Query with external partitioned tables, that are also better optimized in terms of costs and performances on partitions.

## Describe the alternative you are considering or using
Custom ETL that reads from Big Query, transforms in Pandas DataFrame, and saves output in Google Cloud Storage in partitioned path.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368080074994) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Hi @pualien, thank you for creating the issue! 

GCS is high on the priority list for us (along with S3 and ABS)

I can definitely see the destination to be implemented with the following options:
- Storage type (GCS/S3/ABS)
  - bucket
  - base path
  - creds
- File type (parquet, avro, jsonl...)
  - file type specific options
- Partitioning scheme
  - pattern to extract subpath from the extraction date

Do you see any other dimensions or options that would be necessary?

**Comment by pualien** [comment]
@michel-tricot no, it seems complete 😊

**Comment by ChristopheDuong** [comment]
And then what about adding an extra option to associate a BigQuery Table to the GCS bucket?
https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-json

It's an overlap with the BigQuery destination that we already support but we would also bypass the need to run the normalization process in DBT in this case...

**Comment by pualien** [comment]
@ChristopheDuong why not, but for me it's kind of an extension besides saving to GCS

**Comment by andreasholmesberge** [comment]
If the plan is to support parquet, maybe also delta lake could be done?

**Comment by sherifnada** [comment]
@andreasholmesberge yup we will work towards delta lake support shortly after this destination!
