### ISSUE TITLE
Upgrade our JSON/Avro converter library

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#14798]
We currently use https://github.com/allegro/json-avro-converter. This project is officially deprecated/maintenance-mode as of 2 weeks ago.

Probably we should either find a different library, or be prepared to do more active dev work in our own [fork](https://github.com/airbytehq/json-avro-converter).

**Comment by tuliren** [comment]
This is the only Json -> Avro library that works in Java.
Our fork is significantly different from the origin one now.
It is almost a new repo.
I think it is totally fine to just rely on our fork.

**Comment by edgao** [comment]
nice, closing this as wontdo :+1:

**Comment by tuliren** [comment]
For records, Greg pointed that this class may be useful: https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/io/JsonDecoder.html

I previously did not know of it. However, it does not have the extra feature we added. So I guess it is not worth the migration.
