### ISSUE TITLE
Zendesk connector 500 error

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#14807]
## Environment

- **Airbyte version**:  Cloud
- **Source Connector and version**: Zendesk version 0.2.12
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Sync job

## Current Behavior

This connector was working just fine until Friday. It is now consistently failing after three attempts. The error it spits is a 500 errors when querying the ticket_metrics endpoint:

https://honeylovehelp.zendesk.com/api/v2/ticket_metrics?start_time=1657864506&page=610&per_page=100

I have tried the exact same request manually and it works. It looks like a request rate issue or the server sporadically being unavailable. 

## Expected Behavior

I would expect the connector to handle these sporadic errors gracefully, retrying the request after some time. I have also observed rate limits exceeded, throwing 4xx errors, which also should be handled gracefully.

## Logs

Logs are attached for reference as they are huge.

## Steps to Reproduce

I don't know. I guess you set up a connector and wait until the issue happens.

## Are you willing to submit a PR?

Potentially, but I am still reasonably inexperienced with Airbyte.

**Comment by lluisgassovillarejo** [comment]
Hello, I apologize, but after checking with the client, it seems there were some timeout issues with Zendesk over the weekend. At this point, I am unsure if this is worth pursuing (I know not all the requests were failing, just frequently enough to break the connector).

You have the connection logs, which I don't understand, so I guess you can know how often the requests were failing and whether it is worth trying to add a fix.

Thanks.

**Comment by harshithmullapudi** [comment]
Cool then will close this issue but yeah feel free to reopen it when it occurs again
