### ISSUE TITLE
Remove `docs/project-overview/changelog`

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14815]
See https://github.com/airbytehq/airbyte/tree/master/docs/project-overview/changelog
We haven't been keeping this portion of the docs up-to-date.  Can it be removed?  

I think this information now more properly lives:
* In each connector's README/changelog
* In the platform [release notes](https://github.com/airbytehq/airbyte/releases)

**Comment by Amruta-Ranade** [comment]
Done! Also, we have monthly release notes now: https://docs.airbyte.com/release_notes/july_2022
