### ISSUE TITLE
Retest source button gets disabled when changing SSL Mode in Postgres Source connector

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14813]
## What's broken
I have noticed the issue with Source Postgres v 0.4.34, but I suspect this applies to all connectors that have SSL Mode selector in their spec.

## Steps to reproduce

1. Set up a connection with SSL
2. Open connection settings in the Airbyte UI
3. Change SSL Mode - notice that "Retest source" button did not get enabled
4. Switch SSL on/off to enable "Retest source" button
5. Change SSL mode - notice that "Retest source" button got disabled

## Expected behavior
On step 3 "Retest source" button should have switched to enabled state
On step 5 "Retest source" button should have remained enabled

**Comment by tealjulia** [comment]
I just tried this out in the UI and the only times I see the button disabled are when I change to an ssl method that requires additional fields to be filled out (ie: `verify-ca`).  Then, even if I disable the `ssl` option, I am still unable to retest/save the connector without filling in the fields required by `verify-ca`.  

@grishick does this sound like what you were seeing too? It seems that it only affects certain ssl methods.

**Comment by tealjulia** [comment]
So two things are going on here:
(1) I've created #15598 as that button should never be disabled as it prevents users from seeing relevant error messaging on their form

(2) @grishick for this particular case, the reason the form is "invalid" is because the oneOf for `ssl-mode` doesn't have the required sub-fields filled out. This form follows exactly what is in the `spec.json` for the connectors.  This part would be a change on the spec side to make the `ssl-mode` sub-fields only required if `ssl` is `true`.

**Comment by grishick** [comment]
> (2) @grishick for this particular case, the reason the form is "invalid" is because the oneOf for `ssl-mode` doesn't have the required sub-fields filled out. This form follows exactly what is in the `spec.json` for the connectors. This part would be a change on the spec side to make the `ssl-mode` sub-fields only required if `ssl` is `true`.

How can this condition be expressed in spec: require `ssl-mode` sub-fields only if `ssl` is `true`?

**Comment by tealjulia** [comment]
Would [dependent schemas](https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required) work?

**Comment by grishick** [comment]
> Would [dependent schemas](https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required) work? Specifically Implication?

Possibly, although I am not sure how we would use dependent schemas in spec to solve this. Do you have an example in mind? I also suggested [here](https://github.com/airbytehq/airbyte/issues/15809) that if/then/else may work, but maybe dependent schemas are a better solution.

**Comment by tealjulia** [comment]
Closing as the frontend piece of this specific issue is handled for now.
