### ISSUE TITLE
Move to a supported base docker image, openjdk docker image is deprecated

### ISSUE THREAD

**Issue by vr** [airbytehq/airbyte#14823]
## Environment
- **Airbyte version**:  v0.39.37-alpha
- **OS Version / Instance**: GKE
- **Deployment**: Kubernetes

## Current Behavior
Our security tools is complaining about the base image airbyte used, because openjdk has a lot of flaws, and is deprecated now.

## Expected Behavior
we should move to a more supported version of this docker base image (like https://hub.docker.com/_/amazoncorretto for example), and probably stick to a release without pinning, to fetch security fixes without modifying anything

## Are you willing to submit a PR?
I could

**Comment by davinchia** [comment]
@vr what specific issues are being raised up? We have moved to OpenJdk 19, which should have most of the critical vulnerabilities patched.

**Comment by cpdeethree** [comment]
We use amazon coretto now.
