### ISSUE TITLE
Problem with local ETL because of new airbyte columns added to source tables

### ISSUE THREAD

**Issue by drgsec1234** [airbytehq/airbyte#14827]
## Environment
- **Airbyte version**:  example is 0.39.34-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Snowflake
- **Destination Connector and version**: BigQuery
- **Step where error happened**: Sync job

## Current Behavior
*extending the raw tables with default Airbyte columns breaks our current ETL
our ETL is set of insert into statements (not using DBT but custom orchestrated set of sql scripts) 
new columns (_AIRBYTE_AB_ID, _AIRBYTE_EMITTED_AT, _AIRBYTE_NORMALIZED_AT, _AIRBYTE_TABLE_NAME_HASHID)*

## Expected Behavior
*source table should not be changed, since even for incremental load we map update_timestamp and unique_id which are used for incremental update
it would be nice if there is a setup to exclude this new columns being added*

## Steps to Reproduce
1. move one table from source to destination
2. try to insert to source by using previously created script
3. number of columns not matched

**Comment by drgsec1234** [comment]
Hi @natalyjazzviolin we have sorted the large amount of data issue with using different Docker container, so the only problem we have at the moment is these 4 fields added to the source table in Snowflake
Can this be avoided?

**Comment by natalyjazzviolin** [comment]
@drgsec1234 I believe those are default fields added by Airbyte and required for the sync to work. I'll look further into this and get back to you shortly though!

**Comment by drgsec1234** [comment]
@natalyjazzviolin thanks, I would expect them to be added to destination table or some bridge table used for comparison, but would never expect them to be added to the source table that is being transfered

**Comment by natalyjazzviolin** [comment]
@drgsec1234, you're absolutely right! I've triaged this to the connectors team, thanks for your patience!

**Comment by drgsec1234** [comment]
@natalyjazzviolin thank you, looking forward to the solution

**Comment by marcosmarxm** [comment]
Please reset and drop your old tables and execute a new sync. I'm closing this due inactivity. Please open a new issue if the problem persist.
