### ISSUE TITLE
MySql as Destination

### ISSUE THREAD

**Issue by lhmviola** [airbytehq/airbyte#1483]
Is it possible to use MySql as Destination? I need to get data from several sources and put on a MySQL Server.

**Comment by michel-tricot** [comment]
Hey @lhmviola 

Should come in the next few weeks! 

Btw, what sources are you planning to replicate in MySQL?

**Comment by lhmviola** [comment]
Hi Michel,
Quick answer. Thanks.

We are going to replicate Google Adds, analytics, GitHub and four or five rest apis.

Regards,
Viola

**Comment by lhmviola** [comment]
@michel-tricot Michael, Quick question. Do you have any idea when it is going to be available?

**Comment by michel-tricot** [comment]
We will have it by the end of the month. When would you want it?

**Comment by lhmviola** [comment]
@michel-tricot , no rush, but if you have any test version I would start to test.

**Comment by michel-tricot** [comment]
Great, will let you know as soon as we have the first version

**Comment by lhmviola** [comment]
Perfect. Thanks Michel.

**Comment by ChristopheDuong** [comment]
For normalization, it's not natively supported by DBT but there's community support here:

https://softwarerecs.stackexchange.com/questions/68848/is-there-a-mysql-adapter-for-dbt

**Comment by quangdatnth** [comment]
Hi @michel-tricot,
First version is available now?
Thanks

**Comment by sherifnada** [comment]
@quangdatnth we weren't able to support this yet -- we are solely constrained by bandwidth. Would you be open to contributing this connector to Airbyte? The easiest way to do this is to write it in Java. Let me know if you are interested and I can provide some pointers.
