### ISSUE TITLE
Kafka source - message format

### ISSUE THREAD

**Issue by Svatopluk-Chalupa** [airbytehq/airbyte#14832]
### Tell us about the documentation you'd like us to add or update.
Hi,
I cannot find any info if there are any prerequisities on the Kafka topic messages on the source side. Should be documented.
It seems like only JSON format is supported currently, but I'm not sure if there is some way how to specify custom schema for other formats.
Especially, we use Confluent protobuf in some Kafka topics formatting, is it possible to read them by Airbyte?
Thanks.

### If applicable, add links to the relevant docs that should be updated
- [Kafka Source Doc](https://docs.airbyte.com/integrations/sources/kafka)
- [Confluent ProtoBufs](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-protobuf.html#)

**Comment by girarda** [comment]
Hi @Svatopluk-Chalupa,

Only JSON format is supported at the moment. We'll update the documentation to reflect the limitation.

**Comment by Svatopluk-Chalupa** [comment]
Great. 
And just linking for others - I also logged a feature request for protobuf message format:
https://github.com/airbytehq/airbyte/issues/15059

**Comment by Amruta-Ranade** [comment]
Updated doc: https://docs.airbyte.com/integrations/sources/kafka
