### ISSUE TITLE
Source Shopify: product_variants table missing product_id field to reference parent product

### ISSUE THREAD

**Issue by galenking** [airbytehq/airbyte#14837]
## Environment
- **Airbyte version**: 0.30.25-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Digital Ocean
- **Source Connector and version**: Shopify 0.1.37
- **Destination Connector and version**: Postgres 0.3.20
- **Step where error happened**: Sync

## Current Behavior
- From what I can determine, because Shopify variants are stored in an array, Airbyte converts this to a jsonb field in Postrgres and creates an additional `products_variants` table
- The problem seems to be that the `products_variants` table does not have a `product_id` field to reference the parent product, which means we can’t create JOINS to connect variants with products

## Expected Behavior
- If there was a `product_id` field in `products_variants` table, we could create JOINS

**Comment by bazarnov** [comment]
@galenking 
Hello, could you please verify the issue again? 

As far as I can see on our test-account:

`
{"type": "RECORD", "record": {"stream": "product_variants", "data": {"id": 40090579927229, "product_id": 6796217811133, "title": "Plastic", "price": 87.0, "sku": "", "position": 1, "inventory_policy": "deny", "compare_at_price": null, "fulfillment_service": "manual", "inventory_management": "shopify", "option1": "Plastic", "option2": null, "option3": null, "created_at": "2021-06-22T18:09:26-07:00", "updated_at": "2022-02-27T23:44:30-08:00", "taxable": true, "barcode": null, "grams": 274, "image_id": null, "weight": 274.0, "weight_unit": "g", "inventory_item_id": 42185194635453, "inventory_quantity": 49, "old_inventory_quantity": 49, "requires_shipping": true, "admin_graphql_api_id": "gid://shopify/ProductVariant/40090579927229", "shop_url": "airbyte-integration-test"}, "emitted_at": 1673872389172}}
`

There is a `"product_id": 6796217811133` in the data, and schema declares it as well:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-shopify/source_shopify/schemas/product_variants.json#L8-L10
```json
"product_id": {
      "type": ["null", "integer"]
    },
```
