### ISSUE TITLE
Connection creation UI resets replication settings anytime there's any text input/edited

### ISSUE THREAD

**Issue by jnr0790** [airbytehq/airbyte#14844]
## Environment
- **Airbyte version**:  Cloud
- **Step where error happened**: Connection creation

## Current Behavior
Replication settings reset after adding or editing inputs or drop-downs above the `Activate the streams you want to sync` settings.

## Expected Behavior
replication settings to stay as the user intends after updating anything

## Logs

[Loom 1](https://www.loom.com/share/1895d7de050f48bbb3adc79a8e45563d)
[Loom 2](https://www.loom.com/share/85395c6c735d471a89de020647fe4c9e)

## Steps to Reproduce
1. Create new connection
2. Change tables and settings
3. Edit any input.

## Are you willing to submit a PR?

Possibly

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
