### ISSUE TITLE
Standardize rounded corners in UI components

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14849]
Rounded corners are inconsistent all over the app. The goal for this task would be to agree with design on what the rounded corner sizes are (e.g. `sm` `md` `lg`) and apply these changes to the webapp.

* Pair with Nico for 30-minutes to 1 hour to resolve the sizes and update code

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
