### ISSUE TITLE
Documentation panel width resets after resizing browser window

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#14845]
## Environment
- **Airbyte version**:  example is 0.39.37-alpha 

## Current Behavior
Documentation panel is reset back to its original width when it first opened

https://www.loom.com/share/a881cccd05244f3da38a020fc8397fb7

## Expected Behavior
Documentation panel should remain the same size

## Steps to reproduce
1. Create a new source
2. Select source type
3. Resize the documentation panel all the way to the right
4. Resize browser window (alternative, open web inspector and resize inspector)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
