### ISSUE TITLE
Investigate hanging syncs from OSS report

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#14843]
## Context

A community member created this discussion post, in which they found that syncs were repeatedly hanging after the upgrade to the temporal scheduler: https://discuss.airbyte.io/t/temporal-scheduler-causing-multiple-syncs-to-hang/1293/10

One thing that seemed to help them was setting `MAX_CHECK_WORKERS` equal to `MAX_SYNC_WORKERS`, which seemed to improve the situation.

However, that thread contains other reports of syncs hanging for days and of the platform getting into a bad state where new syncs repeatedly fail until the whole instance is restarted.

## Goals

- Understand the interaction between `MAX_SYNC_WORKERS` and `MAX_CHECK_WORKERS`. For example, does `MAX_CHECK_WORKERS` still determine the workers used for the "check connection" operations that run before every sync, or is that controlled by `MAX_SYNC_WORKERS`. Based on that, does it make sense for these to be separately configurable, or should they always be equal?
- Dig into why the OSS instance gets into a bad state and needs to be restarted. Where are syncs getting stuck? Should we implement more robust "timeout" logic in our workflows to prevent hung jobs?

**Comment by davinchia** [comment]
I'm closing this since the linked thread has no more reports since mid last year.
