### ISSUE TITLE
Helm chart fails to render template due to syntax issues

### ISSUE THREAD

**Issue by NipunaPrashan** [airbytehq/airbyte#14863]
## Environment
- **Airbyte version**:  0.39.37-alpha
- **OS Version / Instance**: 10
- **Deployment**: Any
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**:Run helm template command

## Current Behavior
`helm template` command fails due to syntax errors,

## Expected Behavior
`helm template` command should output the correct yaml files with updates values.

## Logs
Error: YAML parse error on airbyte/templates/worker/deployment.yaml:

## Steps to Reproduce
1. `helm template airbyte airbyte`

## Are you willing to submit a PR?
Yes

**Comment by harshithmullapudi** [comment]
Closed with https://github.com/airbytehq/airbyte/pull/14817
