### ISSUE TITLE
Source BigCommerce: page stream stuck and copying same id indefinitely

### ISSUE THREAD

**Issue by TimothyZhang7** [airbytehq/airbyte#14861]
## Environment
- **Airbyte version**: 0.39.17-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: BigCommerce (0.1.5) 
- **Destination Connector and version**: BigQuery (0.5.0) 
- **Step where error happened**: Sync job 

## Current Behavior
The source connection, page stream in specific, stuck at an id and does not proceed. 
It keeps getting the same record indefinitely and the records are duplicated by tens of million times. 

## Expected Behavior
The id should increase and there should not be duplicates.

## Logs

[logs-41452.txt](https://github.com/airbytehq/airbyte/files/9145449/logs-41452.txt)
It is just an example, the previous sync continues for over 20 hours and there are over 40 million records claimed in the log.

## Steps to Reproduce
1. Setup a BigCommerce source
2. Setup a BigQuery destination
3. Sync
4. And it will never stop

## Are you willing to submit a PR?
 Yes

**Comment by JianhaoZhang** [comment]
I think I've found the bug. You could assign me the issue if you want.

**Comment by harshithmullapudi** [comment]
Sure feel free to post questions if any

**Comment by JianhaoZhang** [comment]
PR is submitted.

**Comment by marcosmarxm** [comment]
Closed by #14940
