### ISSUE TITLE
Source Bing Ads: add missing reports

### ISSUE THREAD

**Issue by SPTKL** [airbytehq/airbyte#14880]
## Environment
- **Airbyte version**:  0.39.35-alpha
- **OS Version / Instance**: Debian GNU/Linux 10 (buster) on GCP
- **Deployment**: Docker
- **Source Connector and version**: [airbyte/source-bing-ads](https://docs.airbyte.io/integrations/sources/bing-ads)	0.1.8
- **Destination Connector and version**: NA
- **Step where error happened**: Sync job

## Current Behavior
Currently the Bing Ads connector only supports a limited number of reports (hourly/weekly/monthly)
- account_performance_report
- ad_group_performance_report
- ad_performance_report
- campaign_performance_report
- keyward_performance_report

However, based on official documentation and the [Fivetran implementation](https://fivetran.com/docs/applications/microsoft-advertising#microsoftadvertisingschema) of this connector, there are a lot more reports provided via the bing ads api 
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/13207770/179992238-b5e380ab-8ab1-4682-b003-4ac8a703feeb.png">

## Expected Behavior
All missing reports implemented for Source Bing Ads

## Steps to Reproduce
1. NA
2.
3.

## Are you willing to submit a PR?
Maybe? Would love to get some help on this tho!

**Comment by natalyjazzviolin** [comment]
Hello, @SPTKL! Thanks for opening this issue, it looks like this feature request would be useful to a lot of users. To add the missing reports, you would need to add the streams for each report to the connector. [Here's a good place](https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/getting-started) to familiarize yourself with the way connectors are built. We'd love to review your PR if you're still willing to contribute!

**Comment by artem1205** [comment]
Closing as not relevant anymore.
