### ISSUE TITLE
API error when using Facebook Marketing source v0.2.54 

### ISSUE THREAD

**Issue by emily-flambe** [airbytehq/airbyte#14889]
## Environment
- **Airbyte version**:  0.39.35-alpha
- **OS Version / Instance**: Ubuntu VM / GCP n1-standard-2 (2 vCPUs, 7.5 GB memory)
- **Deployment**: Docker
- **Source Connector and version**: problem occurred when using 0.2.54 but not 0.2.51
- **Destination Connector and version**: BigQuery v1.1.11
- **Step where error happened**: while running sync after upgrading version of Airbyte (and therefore also FB Marketing source connector)

## Current Behavior
On 7/13/22, my team experienced a problem with the latest (at that time) version of the Facebook Marketing source connector. We encountered an error while attempting to make a request from the API, and subsequently some of the pre-existing data in the destination (from previous syncs using earlier versions of the FB Marketing source connector) was actually deleted.

We suspect one potential cause might be [this change](https://github.com/airbytehq/airbyte/commit/81572a9cb2d7956712a2fddb9a5f8264809d3568#diff-83675278209ba8850301229922d2fe5bbd7fb65291da91604093a120f5581feaL175) to how end_date is used in the connector. However, even though the description in the source spec states that `end_date` is an optional field, we encountered errors when trying to configure the source with no end_date.

Our team resolved our immediate needs by reverting to v0.2.51 of the source connector - but filing this issue in hopes that it might be addressed for future releases of the source connector.

## Logs
These are the logs my team provided from the incident:
https://gist.github.com/emilycogsdill/d1140589264a2a67b97d97feb92e5291 

## Are you willing to submit a PR?
Not at this time

**Comment by marcosmarxm** [comment]
@emily-flambe closing this because uses an old version of FB Marketing connector. Please open a new issue if the problem persist.
