### ISSUE TITLE
Test that connectors only make network calls to known domains as part of SAT

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#14888]
## Tell us about the problem you're trying to solve
Let's say a random person on the internet creates a connector. We want to make that connector available in Airbyte. How do we know the connector doesn't contain malicious code that siphons data off to a sketchy location? 

One way of making it harder for the connector to do that is by having a concept of allowed domains. For example, a facebook connector should only make network calls to `facebook.com`. Any other network traffic is probably suspicious. 

## Describe the solution you’d like
I want the ability to specify a list of domains which the connector should be allowed to hit, and if it tries to talk to any other domain, fail the test. 

## Describe the alternative you’ve considered or used
This might also be useful functionality to have in the platform itself.

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/20552.  We opted for runtime isolation rather than a test.
