### ISSUE TITLE
Appstore Connector

### ISSUE THREAD

**Issue by Muriloo** [airbytehq/airbyte#1489]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?

I would like to collect data from the [Appstore API](https://developer.apple.com/documentation/appstoreconnectapi) on a daily basis.
The main goal is to use the Appstore API to extract data from their pre-defined reports. The documentation can be found [here](https://developer.apple.com/documentation/appstoreconnectapi/sales_and_finance_reports).

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.

This integration is used by the marketing team from companies that have a subscription-based business model and rely on AppStore data to create reports about Subscription revenue, Free Trials, plans upgrade/downgrade, etc.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Nowadays I'm using [this Singer integration](https://github.com/miroapp/tap-appstore) created by Miroapp's team.
The Singer integration focus on the [Sales and Trend Reports](https://developer.apple.com/documentation/appstoreconnectapi/download_sales_and_trends_reports).

**Comment by michel-tricot** [comment]
Thanks @Muriloo !

Let us look at it. 

Out of curiosity why do you want to move away from the singer integration?

**Comment by Muriloo** [comment]
Hi @michel-tricot,

Actually, I would like Airbyte to support this integration. I'm fine using the existing singer integration inside Airbyte, it's not necessary to create one from scratch using Airbyte's development practices.

**Comment by Muriloo** [comment]
Is it ok if I work on this integration and try to do a PR for you?

**Comment by sherifnada** [comment]
Hi @Muriloo ,

That sounds great -- we love contributions. Also something to note: if you'll be working on this, we're more than happy to fill in any gaps or provide any needed support including Q&A, pairing, or getting on a call to discuss anything you'd like to go over. 

Are you already in our Slack? it's at [this link](slack.airbyte.io) -- feel free to reach out to me in a direct message or on any of the channels.
