### ISSUE TITLE
Destination MongoDB Strict Encrypt Failing Integration Test

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#14895]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: N/A 
- **Destination Connector and version**: MongoDB Strict Encrypt 
- **Step where error happened**: Integration test fails 

## Current Behavior
Process completed with exit code 1.

## Expected Behavior
Zero exit code 

## Logs

`> Task :airbyte-integrations:bases:standard-destination-test:compileJava FAILED
/actions-runner/_work/airbyte/airbyte/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java:1043: error: incompatible types: ConnectorJobOutput cannot be converted to ConnectorSpecification
            .run(new JobGetSpecConfig().withDockerImage(getImageName()), jobRoot);`
            
https://github.com/airbytehq/airbyte/runs/7419226840?check_suite_focus=true

## Steps to Reproduce
1. Go to [integration-test](https://github.com/airbytehq/airbyte/actions/workflows/test-command.yml) within Github actions tab 
2. On the right hand side, click `Run workflow`
3. Within the `Airbyte Connector` field type in `destination-mongodb-strict-encrypt`
4. Click the green `Run workflow` button to execute the integration test, be sure to note the test (#id_number) to verify the failure later

## Are you willing to submit a PR?

No, will assign this to GL to review and see if there's a particular reason the failures exist

**Comment by suhomud** [comment]
Tried to trigger the integration tests action
https://github.com/airbytehq/airbyte/runs/7496868550?check_suite_focus=true
It is failed but with not the same issue as was described in the ticket. 
It looks like it is related to this closed issue: 
https://github.com/airbytehq/airbyte/issues/9962
I'll rewrite MongodbDestinationStrictEncryptAcceptanceTest to use testcontainers
