### ISSUE TITLE
Destination MongoDB Failing Integration Test

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#14896]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: N/A 
- **Destination Connector and version**: MongoDB 
- **Step where error happened**: Integration test fails 

## Current Behavior
Process completed with exit code 1.

## Expected Behavior
Zero exit code 

## Logs

`The following classes needed for analysis were missing:
  accept
  call
  makeConcatWithConstants`
`> Task :airbyte-integrations:connectors:destination-mongodb:spotbugsMain FAILED`
            
https://github.com/airbytehq/airbyte/runs/7420055203?check_suite_focus=true

## Steps to Reproduce
1. Go to [integration-test](https://github.com/airbytehq/airbyte/actions/workflows/test-command.yml) within Github actions tab 
2. On the right hand side, click `Run workflow`
3. Within the `Airbyte Connector` field type in `destination-mongodb`
4. Click the green `Run workflow` button to execute the integration test, be sure to note the test (#id_number) to verify the failure later

## Are you willing to submit a PR?

No, will assign this to GL to review and see if there's a particular reason the failures exist

**Comment by suhomud** [comment]
Seems like issue was resolved. 
Checked on the latest master 
https://github.com/airbytehq/airbyte/pull/15431
