### ISSUE TITLE
Postgres Source: testIncrementalSyncWithState failed 

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#14891]
After today's changes (20/07/2022), the postgres source fails testIncrementalSyncWithState. I found the changes that caused this. I am adding screenshots for more information.

![2022-07-20_19-19](https://user-images.githubusercontent.com/88329385/180037179-33e1a651-64dd-40d8-9fa6-a62e0ab4ba40.png)
![2022-07-20_19-22](https://user-images.githubusercontent.com/88329385/180037216-f5cacddc-a1b5-495b-a1f1-ff919fd2fb9c.png)
![2022-07-20_19-24](https://user-images.githubusercontent.com/88329385/180037241-e5f4ec59-d37c-4c76-8289-3c64a4a7b6fb.png)

**Comment by grishick** [comment]
@andriikorotkov the last change to `SourceAcceptanceTest` is a month old. Do you know which changes started causing the test failure and when?

**Comment by andriikorotkov** [comment]
@grishick, yes, I saw that these changes were added a month ago. Tests for postgres source failed today, and only one test fails for all acceptance tests - `testIncrementalSyncWithState`. Maybe the changes that broke it were added today, or yesterday, after our daily build report ran. 
![2022-07-20_21-10](https://user-images.githubusercontent.com/88329385/180052735-5fe43182-4fba-4399-b7de-b09a05ee6d42.png)

**Comment by grishick** [comment]
@benmoriceau @jdpgrailsdev @subodh1810 are you aware of any recent changes that may have broken the per-stream state test?

**Comment by jdpgrailsdev** [comment]
> PR

@grishick All of the tests were passing when that PR was merged over a month ago.  I suspect something else has changed more recently that is causing the failure.

**Comment by subodh1810** [comment]
Am going to close this since we have been able to publis postgres source multiple times after this!
