### ISSUE TITLE
Source Snowflake Failing Integration Test

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#14901]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: Snowflake 
- **Destination Connector and version**: N/A 
- **Step where error happened**: Integration test fails 

## Current Behavior
Process completed with exit code 1.

## Expected Behavior
Zero exit code 

## Logs

`SnowflakeSourceAuthAcceptanceTest > testCheckConnection() FAILED
    org.opentest4j.AssertionFailedError: Expected check connection operation to succeed ==> expected: <succeeded> but was: <failed>`
            
https://github.com/airbytehq/airbyte/runs/7420881723?check_suite_focus=true

## Steps to Reproduce
1. Go to [integration-test](https://github.com/airbytehq/airbyte/actions/workflows/test-command.yml) within Github actions tab 
2. On the right hand side, click `Run workflow`
3. Within the `Airbyte Connector` field type in `source-snowflake`
4. Click the green `Run workflow` button to execute the integration test, be sure to note the test (#id_number) to verify the failure later

## Are you willing to submit a PR?

No, will assign this to GL to review and see if there's a particular reason the failures exist

**Comment by yurii-bidiuk** [comment]
It's not reproducible now. I guess it was fixed by https://github.com/airbytehq/airbyte/pull/14574
All tests are passed: https://github.com/airbytehq/airbyte/actions/runs/2732438910
