### ISSUE TITLE
New Source: Redis/Hdfs/Hive/HBase

### ISSUE THREAD

**Issue by dadalongvs** [airbytehq/airbyte#14912]
## Tell us about the new connector you’d like to have
* I'd like to be able to pull data from a C instance.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by marcosmarxm** [comment]
Closing because this isn't a single request. Please open individual issues to each source.
