### ISSUE TITLE
Remove `additionalProperties:false` from GA API connectors

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14937]
As discovered in https://github.com/airbytehq/oncall/issues/289, a spec declaring "additionalProperties": false introduces the risk of accidental breaking changes. Specifically, when removing a property from the spec, existing connector configs will no longer be valid.

I am filing a separate issue for GA connectors in order to make and ship these changes modularly and atomically. We can make changes to non-GA connectors first and use whatever we learn doing that when updating GA connectors.

**Comment by alafanechere** [comment]
@grishick I think this was done here for source connectors, let me know if my list of GA connectors is not up to date: https://github.com/airbytehq/airbyte/pull/14924
