### ISSUE TITLE
Update source-clickhouse to use com.clickhouse.jdbc.ClickHouseDriver

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#14945]
We have updated destination-clickhouse to use the new `com.clickhouse.jdbc.ClickHouseDriver` class, but the code that specifies the package name is shared between sources and destinations. We should "unbreak" source-clickhouse now by making it use the new driver as well.

**Comment by suhomud** [comment]
Hi @grishick , this was done in this PR
 https://github.com/airbytehq/airbyte/pull/14701. I need approval from your side and I'll be ready to publish and merge
