### ISSUE TITLE
Frontend should have a general way to display API errors

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1495]
## Tell us about the problem you're trying to solve
I want a general way to make API errors visible to the user

## Describe the solution you’d like
If the API response code is not {2,3}XX I would like the error message to show in the UI.

I had the problem when disabling queuing of tasks. I want to return an error when there is already a sync/reset scheduled but with the current state I can't give the feedback to the user. The temporary solution is to just return the current job but it makes the API contract less than ideal. 

I would love something like this:
![image](https://user-images.githubusercontent.com/1154337/103569249-d2d43a80-4e7b-11eb-94c0-74c66a8ab70e.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368139430566) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
(the screenshot is just to demonstrate the notification system, not meant to be taken as the expected design)

**Comment by johnlafleur** [comment]
Here is some 1st draft: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21397%3A0
The suggestion is:
* have 2 different displays: in-context and general 
* some errors might not be dismissable (API not responding) until a situation is resolved
* In-context should be used for feedback on buttons. The in-context errors should always be displayed in the vicinity of where the action took place (for instance, replacing the button you just clicked). 

Wdyt?

**Comment by michel-tricot** [comment]
Not convince actually about the non-dismissable one. Why not make them all the same? If the api is not responding, it will just write more than one message or if for some reason it disappear, it will re-appear. It makes the logic a lot easier.

**Comment by johnlafleur** [comment]
Fine with me :)

**Comment by cgardens** [comment]
Okay. I am adding this project to the queue of work so should get done in the next couple weeks. The deliverable here is the the ability to do dismissable messages. They disappear when one of the following happens: 1. user dismisses it 2. user goes to a new page? (@michel-tricot @johnlafleur , not clear on what your guys's vision here on this one) 3. a new error message happens.

The first error that will use this functionality will be this [issue](https://github.com/airbytehq/airbyte/issues/2152).

**Comment by johnlafleur** [comment]
Behavior seems fine to me.
