### ISSUE TITLE
Kafka to Snowflake: basic normalization does not work, simply writes null in the "value" column

### ISSUE THREAD

**Issue by jsrcodes** [airbytehq/airbyte#14957]
Is this your first time deploying Airbyte?: No
OS Version / Instance: Ubuntu, Windows or MacOS… are some example remove it with yours
Memory / Disk: you can use something like 8Gb / 1 Tb
Deployment: Kubernetes
Airbyte Version: 0.35.65-alpha
Source name/version: Kafka 0.1.7
Destination name/version: Snowflake (latest)
Step: creating the connection
Description: Raw mode works fine. The Basic Normalization  writes "null" in snowflake
![image](https://user-images.githubusercontent.com/1407979/180361870-235b307a-89fc-43dd-be1f-2e97726d13f1.png)
![image](https://user-images.githubusercontent.com/1407979/180361910-887d24ee-2fbf-46d6-84e0-dfa3bada5eb0.png)
![image](https://user-images.githubusercontent.com/1407979/180441720-9b5b902f-35cb-46b0-8a00-a2031ad9cd10.png)

![image](https://user-images.githubusercontent.com/1407979/180441517-537db998-96f3-41b6-a8b0-d31ba2ae144f.png)

## Steps to Reproduce
1. setup Kafka --> Snowflake connector and sync

**Comment by natalyjazzviolin** [comment]
Hi @jsrcodes, thanks for opening up this issue. Does this happen with other source connectors for you as well?

**Comment by jsrcodes** [comment]
Hi @natalyjazzviolin, no, it happened only with Kakfa source. We have many other stable connectors doing well with Basic normalization. I guess it's because the Kafka source is essentially schema-less (json)

**Comment by natalyjazzviolin** [comment]
Interesting! That's really helpful information, thank you.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
