### ISSUE TITLE
Only validate that incremental streams have state before migrating connection to per-stream 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#14962]
We have a check (https://github.com/airbytehq/airbyte/pull/14599 / https://github.com/airbytehq/airbyte/issues/14519) when migrating syncs to per-stream state that ensures that every enabled stream has state before migrating.  However, this check should only happen for incremental streams

**Comment by lmossman** [comment]
I don't think this ticket is necessary. The validation only checks if the state that was produced at the _end_ of the sync has states for all streams in the catalog, before it writes that state to the destination. So this shouldn't matter if a sync had ran before or not

**Comment by evantahler** [comment]
Title & description updated
