### ISSUE TITLE
correct source/destination configs flash red after successful checks in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1496]
## Expected Behavior
Inputs for sources/destinations should either flash green or not change border color at all when connection checks succeed.

## Current Behavior
Right now, they flash red for a brief moment as it shows the success message, before continuing to the next view.

## Steps to Reproduce
1. Configure the exchange rate api as a source with correct inputs

## Severity of the bug for you
Medium

**Comment by cgardens** [comment]
@jrhizor - i have seen this as well. it is inconsistent for me. it only happens sometimes.

**Comment by michel-tricot** [comment]
![image](https://user-images.githubusercontent.com/1154337/103972935-12708000-5123-11eb-92b5-0d36ea38687b.png)
