### ISSUE TITLE
Expose the restart workflow method so it can be manually executed

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#14972]
## Context

With the completion of https://github.com/airbytehq/airbyte/issues/14970, we will now have a TemporalClient method to restart workflows with a given status.

However, this method needs to be exposed of the internal airbyte-worker app for it to be used by OC engineers. This could be useful in situations such as the OC engineer terminating workflows to prevent noise while working on an issue, and then they need to restart those workflows at a later time.

## How

This method can be exposed in a few ways:
1. Implement an endpoint in the config API like `/temporal/restart_workflows(status)`, which calls the TemporalClient method implemented in the ticket linked above, allowing engineers to make an API request (though this will likely require getting an auth token to be able to perform this request)
2. Implement a docker container that connects to the temporal service and executes that method, allowing engineers to run the docker container with the status as a command-line argument when they need to execute it
3. Another approach suggested by you!

Once this is implemented, documentation should be added to the cloud docs with instructions on how to execute it.

**Comment by salima-airbyte** [comment]
@benmoriceau will this ticket scope change based on the work you're doing on Worker Scheduler?

**Comment by andyjih** [comment]
@benmoriceau - Just wanted to check-- is this still open or did you complete this?

**Comment by davinchia** [comment]
This is handled by self-heal. We don't actually want to expose this to OC engineers.
