### ISSUE TITLE
Hubspot Connector Incremental Sync is broken.

### ISSUE THREAD

**Issue by elliottrabac** [airbytehq/airbyte#14988]
## Environment
- **Airbyte version**: 0.39.37-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Hubspot 0.1.75
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

Infinite loop when 100 objects have been updated at the same time. Hubspot is supposed to be a GA connector.

Issue has been introduced by this PR:
https://github.com/airbytehq/airbyte/pull/14744/files#r928310683

## Expected Behavior
*Tell us what should happen.*

Update state only at the end of the 10k batch.

## Logs

[logs-4549 (1).txt](https://github.com/airbytehq/airbyte/files/9176682/logs-4549.1.txt)

**Comment by natalyjazzviolin** [comment]
The changes are being reverted in #14999
