### ISSUE TITLE
When creating a new connection, changing the connection name edits the unsaved replication settings

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#14989]
Repro Steps
1. Create a new connection
2. Change the replication settings but don't save 
3. Start typing in the connection name
4. See that the replication settings didn't save. 

Video here: ![2022-07-24_15-03-57 (1).gif](https://images.zenhubusercontent.com/6259fa2f135cc77b44d5821f/cbc497b4-72c4-4fa8-b76b-6820d66d4759)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/14844

**Comment by edmundito** [comment]
Not necessarily a duplicate. The fix for #14844 also fixes this.
