### ISSUE TITLE
Helm Chart: Make loadBalancerIP configurable for webapp service

### ISSUE THREAD

**Issue by NipunaPrashan** [airbytehq/airbyte#14991]
## Tell us about the problem you're trying to solve
Currently, loadBalancerIP should be hardcorded in the yaml file, but we can be changed it to a configurable value in the yaml file.

## Describe the solution you’d like
Add a configurable value to values.yaml and change the service yaml accordingly.

## Describe the alternative you’ve considered or used
Hardcode the IP in service yaml.

## Additional context
`loadBalancerIP: xxx.xx.xx.x`

## Are you willing to submit a PR?
yes

**Comment by andyjih** [comment]
cc @supertopher perhaps something for your team?
