### ISSUE TITLE
Disk full from airbyte_workspace filling up

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#15002]
## Environment
Airbyte  0.39.14-alpha
Ubuntu Docker

## Current Behavior
The folder 
/var/lib/docker/volumes/airbyte_workspace/_data 
completely fills up with the transformation directories and is never cleaned up. The folder is already 200GB in size

## Expected Behavior
After transformation this folder should be cleaned up

**Comment by marcosmarxm** [comment]
This is a new instance or a long-running one? How many connectors/connections are you using?

**Comment by gabrielalmeida** [comment]
Same behavior.
Airbyte 0.39.41-alpha.
Just 1 single connection with two connectors.
Postgres to BigQuery, 5min interval sync, no custom transformations.

Is it safe to manually clean it in the meanwhile?

**Comment by marcosmarxm** [comment]
>Is it safe to manually clean it in the meanwhile?

Yes, that folder only keeps logs.

**Comment by marcosmarxm** [comment]
Logs rotation was readded in latest version of Airbyte (0.40+) please upgrade your instance.
