### ISSUE TITLE
Use Airbyte without continious internet access 

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#15004]
Hi I have 3-4 different sources which have different kind of data and I wanted to aggregate this data into a single data source after transformation on it. So The problem is my server does have continious internet access. So for the first time (while configuration), I can arrange the internet access. As during transformation config, It requires git url and docker image name (fishtownanalytics/dbt:1.0.0). Does it requires continious internet access for data transfer or only at time of configuration?

**Comment by harshithmullapudi** [comment]
[#14997](https://github.com/airbytehq/airbyte/issues/14997)
