### ISSUE TITLE
add slack button in UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1501]
## Tell us about the problem you're trying to solve
We should make Slack and Papercups options in the UI for reaching out for support.

UPDATE (2020/01/19):
Let's add the following icon (below) in the left navbar above the help icon. It should link to https://slack.airbyte.io/. The color should match that of the other icons, lmk if you need someone to do that.

![slack](https://user-images.githubusercontent.com/9092207/105081054-8b86a600-5a46-11eb-9be3-0637833bb61d.png)

**Comment by cgardens** [comment]
i like this idea. opinion on where we would display it?

**Comment by michel-tricot** [comment]
We could either add a second "button" with the slack logo or just a link in the papercup chat. WDYT?

**Comment by cgardens** [comment]
I like the idea of the slack button.

**Comment by cgardens** [comment]
@michel-tricot what's the link for the slack button?

**Comment by cgardens** [comment]
assigning self because i want to see if this can get done before launch. still some work needs to happen on our side before we can give it to artem.

**Comment by michel-tricot** [comment]
This is the right link!

**Comment by cgardens** [comment]
I have updated the description of this issue at the top with instructions for what we'd like to do here.
