### ISSUE TITLE
Mysql to Bigquery Incremental Deduped Sync Failure

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15011]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1619](https://airbyte7538.zendesk.com/agent/tickets/1619)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sajarin Dider

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi Everyone,</p>
<p dir="auto">I am facing an Incremental Sync Failure when syncing data from Mysql to Bigquery.</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: Yes</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Debian 11</li>
<li style="padding-bottom: 10px;">Memory / Disk: 64Gb / 35GB</li>
<li style="padding-bottom: 10px;">Deployment:  GCP VM with Docker Compose</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.35-alpha</li>
<li style="padding-bottom: 10px;">Source name/version:  MySQL (0.5.15)</li>
<li style="padding-bottom: 10px;">Destination name/version: BigQuery (1.1.11)</li>
<li style="padding-bottom: 10px;">Bigquery Loading Method: GCS Staging</li>
<li style="padding-bottom: 10px;">BigQuery Client Chunk Size: 15MB</li>
<li style="padding-bottom: 10px;">Step: Sync - Incremental Deduped History</li>
</ul>
<p dir="auto"><strong>Description:</strong><br>
Starting with I am pretty new to using Airbyte.<br>
I setup a manual frequency refresh to sync data incrementally from Mysql source to Bigquery. The sync fails at the initial step where it needs to do the full replication of the source DB.</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">2022-07-15 20:49:11 source &gt; 2022-07-15 20:49:11 ERROR i.d.c.m.AbstractReader(failed):219 - Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `parkplus_fastag_issuance`.`fastag_passbook`': Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@370f5040 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
2022-07-15 20:49:11 source &gt; org.apache.kafka.connect.errors.ConnectException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@370f5040 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries. Error code: 0; SQLSTATE: S1000
</code></pre>
<p dir="auto">Also, I see few records which have been emitted have been inserted into the Bigquery destination partially but I see no committed records count in the error log message.<br>
I let Airbyte run 3 attempts for the pipeline to see if it works.</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/f/fedfccfbdb163d488f18f5648065b00e0721d49a.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/f/fedfccfbdb163d488f18f5648065b00e0721d49a_2_690x168.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1222×299 43.7 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">Attaching Attempt 3 log for reference. (edited out few logs in between to get the size below 8 MB)</p>
<p dir="auto">Thanks !!</p>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/hr1WuT3msFixRDzE9bI4lyU2bFr.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">fpl-Attempt-3-logs.txt</a> (7.5 MB)</p> 

[<a href="https://discuss.airbyte.io/t/mysql-to-bigquery-incremental-deduped-sync-failure/1903/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin Dider on 2022-07-20 at 17:20:*

<blockquote><div class="zd-comment" dir="auto">Hi @mastersam987, thanks for your post. I think this is related to an issue with Debezium, there was a PR that was recently merged in master relating to this: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/14542">https://github.com/airbytehq/airbyte/pull/14542</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-21 at 04:10:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a> , will look into it and update this.</p> 

 [<a href="https://discuss.airbyte.io/t/source-mysql-incremental-deduped-sync-failure/1903/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-22 at 07:05:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a>, we have updated the connector but we are still facing the same issue.</p> 

 [<a href="https://discuss.airbyte.io/t/source-mysql-incremental-deduped-sync-failure/1903/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin Dider on 2022-07-25 at 17:56:*

<blockquote><div class="zd-comment" dir="auto">Hi @mastersam987, thanks for reporting back. I've created an issue on github regarding this, please follow there for any updates. Hopefully, we can get this working for you soon.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-26 at 06:07:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Sure <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a>, Thanks !!</p> 

 [<a href="https://discuss.airbyte.io/t/source-mysql-incremental-deduped-sync-failure/1903/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by grishick** [comment]
@marcosmarxm [@sajarin](https://github.com/u/sajarin) could you share the logs from the latest failed sync? We have updated Debezium version in MySQL Source connector and that may have solved the issue.
