### ISSUE TITLE
AdaptiveStreaming is not utilizing full bandwidth of an ec2 instance

### ISSUE THREAD

**Issue by prashantgolash** [airbytehq/airbyte#15022]
## Tell us about the problem you're trying to solve
I am trying to replicate a large amount of data. It seems airbyte is able to use ~80 MBps network bandwidth  per connection object even when ec2 instance has lot of capacity to scale. I increased the cpu limit to the max.

## Describe the solution you’d like
NA

## Describe the alternative you’ve considered or used
Tried to increase system throughput with compute optimized instances and bigger instances but to no avail.

## Additional context
It looks there is some presigned url bug that gets hit when we reach 6 hr limit on a single connection object. [Link](https://github.com/airbytehq/airbyte/issues/6246). I was trying to see if somehow by tuning system parameters, I can make airbyte sync my data in less than 6 hrs. Data is ~340 GB. After reaching 6 hrs roughly 300 GB is copied and then my sync fails.

## Are you willing to submit a PR?
I have not explored, but given some pointers, would love to contribute.

**Comment by natalyjazzviolin** [comment]
@prashantgolash could you please specify which connectors and versions you are using so I can triage this to the correct team?

**Comment by prashantgolash** [comment]
Snowflake Connector
Airbyte version: 0.39.34-alpha

**Comment by natalyjazzviolin** [comment]
@prashantgolash have you seen the docs on scaling Airbyte?
https://docs.airbyte.com/operator-guides/scaling-airbyte#what-to-scale

As we're making connectors more stable, they may become slower. We are currently looking into making connectors faster, but the implementation date has not been set yet.

**Comment by marcosmarxm** [comment]
This look was created as a feature but must be a bug. I'm closing because of lack of information.
