### ISSUE TITLE
no feedback on launch sync button in UI 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1503]
## Expected Behavior
There is no immediate feedback that the launch sync button performed an action in the UI.

## Current Behavior
There needs to be some instant indication that the button was pressed.

## Steps to Reproduce
1. configure exchangerate -> local csv with manual cadence
1. click launch sync

## Severity of the bug for you
Low

**Comment by cgardens** [comment]
i believe this has been rectified.
