### ISSUE TITLE
create testing sources

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1505]
## Tell us about the problem you're trying to solve
We need to be able to reproduce common errors in the UI and for testing.

## Describe the solution you’d like
I'd like to add a generic "testing source" that allows us to test failure patterns (fail-fail-succeed-fail, always fail, etc.). We could also test slow commands (a source that inserts a 20s delay before each operation, so it's easier to reproduce UI bugs on slow behavior.)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368081461692) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I think we have this is now with the test source: source-e2e-test
