### ISSUE TITLE
SAT: Syntactic validation of catalog update for backward compatibility

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#15057]
## Tell us about the problem you're trying to solve
Context is [here](https://www.notion.so/Preventing-Backwards-Incompatible-Changes-in-Connectors-e05dafd0f1a349dd819b569a8a4564a7#852f500f3920460fa85e3fbe1443b8d0).

We want to prevent backward incompatible connector changes by running a dedicated test suite on SAT. 
Backward incompatible changes can happen on catalog change of a connector. We want to add tests on the `discover` command to ensure the changes made to a connector are backward compatible with the previous connector version.

## Acceptance criteria
Acceptance tests should fail if one of this situation occurs:

* `additionalProperties` is set to `false` (already covered by  https://github.com/airbytehq/airbyte/pull/14878)
* An existing stream property’s type has been changed: we could allow for type expansion, but @sherifnada suggested first being conservative by disallowing any type change.
 * A stream was removed/renamed
 
This work can be considered as an iteration upon https://github.com/airbytehq/airbyte/pull/15194

**Comment by alafanechere** [comment]
grooming note:
* use semver to decide if breaking changes are allowed 
* access connector status from SAT to bypass strict test for alpha (decide on what to do for custom connectors)

**Comment by alafanechere** [comment]
> access connector status from SAT to bypass strict test for alpha (decide on what to do for custom connectors) : if a previous connector version is alpha anything goes.

Created https://github.com/airbytehq/airbyte/issues/15407

**Comment by alafanechere** [comment]
> use semver to decide if breaking changes are allowed

Created https://github.com/airbytehq/airbyte/issues/15408
