### ISSUE TITLE
Google Analytics V4 / Universal Analytics - incorrect Changelog and missing documentation in Airbyte UI

### ISSUE THREAD

**Issue by donatas-jocas** [airbytehq/airbyte#15064]
### Tell us about the documentation you'd like us to add or update.
Hi, looks like there is some bug in the Google Analytics V4 documentation - looks like the Changelog have been switched between this connector and new one - Google Analytics (Universal Analytics).

Also, in Airbyte UI links to documentation for these 2 sources are broken - I see this config snippet instead:

`window.TRACKING_STRATEGY = "segment";
            window.FULLSTORY = "disabled";
            window.AIRBYTE_VERSION = "0.39.38-alpha";
            window.API_URL = "/api/v1/";
            window.IS_DEMO = "false";
            </script><body><noscript><img src="/logo.png" alt="logo" width="90" height="94"/><div class="card">You need to enable JavaScript to run this app.</div></noscript><div id="root"></div></body></html>`

### If applicable, add links to the relevant docs that should be updated
- https://docs.airbyte.com/integrations/sources/google-analytics-v4#changelog
- https://docs.airbyte.com/integrations/sources/google-analytics-universal-analytics#changelog

Airbyte version - 0.39.38-alpha

**Comment by marcosmarxm** [comment]
The issue is only happening with Google Analytics Data API connector. Reason is:
https://github.com/airbytehq/airbyte/blob/a93ea5c95f55040904dc8f070bef8b4e1bdfa3f4/airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/spec.json#L4

**Comment by donatas-jocas** [comment]
Looks like fixed by https://github.com/airbytehq/airbyte/pull/15087
