### ISSUE TITLE
Upgrade exported configuration files to upgrade Airbyte Version

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1507]
## Tell us about the problem you're trying to solve
As part of https://github.com/airbytehq/airbyte/issues/1402:

Write an application script that takes exported data input (from #1502 and #1504)  and produces updated data as output. 

## Describe the solution you’d like

- Maybe for the sake of this project, if we don’t have any migration we need to do yet, we can write a “no-op” script that just increases the version, so that we can sanity check this all works.

- This script upgrades the config database where we store the standard definitions files for recommended connectors versions (latest release of connectors as published in the airbyte-init module in a specific release version of airbyte)

- This script does not modify the versions of connectors chosen and used by the user in the job configuration when they were created

**Comment by ChristopheDuong** [comment]
These migration scripts could also be used as templates to show users how to write custom "migration" scripts that would modify programmatically how airbyte is configured.

**Comment by cgardens** [comment]
completed by https://github.com/airbytehq/airbyte/pull/1533
