### ISSUE TITLE
GET API endpoints should not have side-effects

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15094]

**Comment by evantahler** [comment]
@gosusnp can you please fill this issue out?  We discussed this in our latest retro

**Comment by gosusnp** [comment]
@evantahler, I created [#14646](https://github.com/airbytehq/airbyte/issues/14646) as a result of a previous retro. I grouped them at a time because they may involve reworking some front-end workflows that we may want to bundle to ease the iterations on front-end. What do you think?

**Comment by evantahler** [comment]
👍 I'll close this issue and use yours
