### ISSUE TITLE
Don't change validationSchema based on input

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15108]
Currently our code does change the `validationSchema` of the ServiceForm based on some values, e.g. if the user selects another oneOf value with a sub object the whole validationSchema will change to reflect that.

I think we should try to generate the `validationSchema` once for the connectors spec and not change it based on the form values. Yup supports [`when`](https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema) to actually annotate that specific parts of a schema are only in effect when specific criterias are met. I think we should rather use that functionality to generate one validationSchema, that uses `when` to validate the different choices of a `oneOf` JSONSchema.

Especially since Formik doesn't revalidate the form when the validationSchema changes, we need to have special hacks for that in place.

This would require https://github.com/airbytehq/airbyte/issues/13056 to be solved, so that the formik form actually only contain the individual connectors form, and thus the validationSchema could be kept unchanged while filling the form.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by flash1293** [comment]
part of the last refactoring PR

**Comment by flash1293** [comment]
Approved, waiting for the code freeze
