### ISSUE TITLE
🎉 Destination Databricks: Support Azure storage

### ISSUE THREAD

**Issue by abaerptc** [airbytehq/airbyte#15140]
## Tell us about the problem you're trying to solve
I'd like to use the Databricks destination with Azure storage.

## Describe the solution you’d like
I'd like the option to specify an Azure storage location as an alternative to S3 storage.

## Describe the alternative you’ve considered or used
None.

## Additional context
None.

## Are you willing to submit a PR?
Yes.

**Comment by abaerptc** [comment]
I have a prototype written already and I will open a PR shortly for review.

**Comment by natalyjazzviolin** [comment]
@abaerptc thanks for opening this issue, looking forward to your PR!

**Comment by creativedutchmen** [comment]
Any updates on this? This PR would make the life of Databricks users on Azure so much easier - the current approaches of either using minio or csv files are both suboptimal. Being able to use a CDC source and dedupe straight from Airbyte with Databricks, and having the result as a delta table is a game changer.

**Comment by abaerptc** [comment]
@marcosmarxm @tuliren Any update on getting this merged in? https://github.com/airbytehq/airbyte/pull/15329
