### ISSUE TITLE
mssql connector gives normalisation error

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#15150]
Hi, I was trying to push data from mssql to postgres using airbyte. initail full refresh works perfectly well. But in the incremental dedup mode, it was shows "normalisation failed error". The Data was around 50K rows. Later I tried with less amount of Data 1000 rows it was working perfectly well. Can anyone help whats the problem?

**Comment by marcosmarxm** [comment]
Please share the complete logs and use the template given to use when creating the issue.
