### ISSUE TITLE
Align markdown parser with docusaurus

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15168]
We currently use a standard markdown parser for the docs sidepanel in the UI, while the doc system renders using Docusaurus. This leads to Docusaurus supporting some syntax that will then not render in the UI properly. We should try to build support for this syntax in the UI, by manually parsing (regex) this syntax.

List of unsupported syntax:

- ``:: caution`` blocks

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by zaclittleberry** [comment]
Looks like docusaurus uses MDX v1 as its rendering engine, which is specifically where the :::caution,note,tip,info syntax comes from: https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-react.mdx

I have confirmed that your current docusaurus version is using `@mdx-js/react@1.6.22`. (Published Dec 2020, but even the docusaurus 2.0rc is using MDX 1, :shrug: )

The regex solution may be something like this: regexr.com/6rbu7 . Note, Regexr's "Replace" pane doesn't render until the text area is updated, so you can just throw a space in the text to see an example replace with a pseudo `<info>` component.
- this regex solution would have to be done for each caution,note,tip, and info, or modified.
- this regex solution would not work with nested ::: syntax. I don't know if that is valid or not.
