### ISSUE TITLE
BambooHR Custom Fields Delivered As NULL

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15170]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1613](https://airbyte7538.zendesk.com/agent/tickets/1613)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><h2 dir="auto">
<a href="#this-is-a-repost-of-httpsdiscussairbyteiotbamboohr-custom-fields-not-pulling1580-1" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer"></a>This is a repost of (<a href="https://discuss.airbyte.io/t/bamboohr-custom-fields-not-pulling/1580" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">https://discuss.airbyte.io/t/bamboohr-custom-fields-not-pulling/1580</a>)</h2>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: EC2 t2.large</li>
<li style="padding-bottom: 10px;">Memory / Disk: 16Gb</li>
<li style="padding-bottom: 10px;">Deployment: Docker</li>
<li style="padding-bottom: 10px;">Airbyte Version: 39.16-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: 0.2.0</li>
<li style="padding-bottom: 10px;">Destination name/version: Snowflake 0.4.24</li>
<li style="padding-bottom: 10px;">Step: n/a</li>
<li style="padding-bottom: 10px;">Description:<br>
Trying to figure out how to use the BambooHR custom reports stream. I have a custom field in BambooHR called <strong>Squad</strong> , which I have access to via my API key. I’m able to see this field on the front end. However when I input this field as <strong>squad</strong> into the Airbyte Web UI. I’ve tried every iteration of <strong>squad</strong> (see image below)</li>
</ul>
<p dir="auto"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/d/d72561b016c3383f95bf794deba106d77fe4cdb0.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto">Below is what the results come through as at the destination schema. All <code style="background-color: #f9f9f9; padding: 2px 5px;">NULL</code><br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/b/bceb07cfc04f479a4c509030bfc1476a6c236bf4.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto">This is what it looks like on the front end in BambooHR<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/9/9c786f1057db928e900d2b52af7b644cbff4e3ef.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto">Here are the logs<br>
<a href="https://discuss.airbyte.io/uploads/short-url/teOGDsmwb3L5bV98VMqTOShGG0y.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-10162.txt</a> (35.4 KB)</p>
<p dir="auto">And a sample of the JSON stored in <code style="background-color: #f9f9f9; padding: 2px 5px;">_airbyte_data</code> column</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;"> "acaStatus": "",
"acaStatusCategory": null,
"bestEmail": "",
"city": "Montreal",
"country": "Canada",
"createdByUserId": "2485",
"department": "Engineering",
"displayName": "",
"division": "",
"employeeNumber": "106",
"employmentHistoryStatus": "Full-Time",
"ethnicity": null,
"firstName": "",
"flsaCode": "1",
"fullName1": "",
"fullName2": "",
"fullName3": "",
"fullName4": "",
"fullName5": "",
"hireDate": "2020-05-25",
"homeEmail": "",
"homePhone": "",
"id": "122",
"jobTitle": "",
</code></pre>
<p dir="auto">And here is the catalog.json file as requested previously<br>
<a href="https://discuss.airbyte.io/uploads/short-url/tvW6Ke4Eoqy8lFFo7sLCwxbFD36.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">catalog.txt</a> (18.3 KB)</p> 

[<a href="https://discuss.airbyte.io/t/bamboohr-custom-fields-delivered-as-null/1895/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-19 at 15:59:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> this is how BambooHR shows it on the front end<br>
</p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/e/e6bae982e6208e1c3d752f26bffcc31bc0e087f0.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/e/e6bae982e6208e1c3d752f26bffcc31bc0e087f0_2_690x192.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1088×304 31.7 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">And this is how it is returned when delivered to Snowflake<br>
</p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/0/0eb0d5de5b7df616228c25f9ebfc0b087818be7f.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/0/0eb0d5de5b7df616228c25f9ebfc0b087818be7f_2_690x292.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1122×476 28.1 KB</span>
</div></a></div><p dir="auto"></p> 

 [<a href="https://discuss.airbyte.io/t/bamboohr-custom-fields-delivered-as-null/1895/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-07-28 at 16:12:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> any updates on this?</p> 

 [<a href="https://discuss.airbyte.io/t/bamboohr-custom-fields-delivered-as-null/1895/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-01 at 19:31:*

<blockquote><div class="zd-comment" dir="auto">Unfortunately no, Airbyte integration test account is not working. I escalated the issue to Github <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15170">https://github.com/airbytehq/airbyte/issues/15170</a> any updated I'll return to you.<br></div></blockquote>

**Comment by midavadim** [comment]
@lazebnyi @marcosmarxm 

I was not able to find any tutorials on how to add new custom field in BambooHR.
I tried to create new employees with custom 'bla' field via API, but I was not able to extract it back neither via reports API nor get_employee API.

So, we probably need to ask our client for more information:
1. if possible, please provide us with steps how you added new custom field to BambooHR.
2. provide us with a full link to BambooHR UI page where you can see your custom field and screenshot of the whole page.

Overall, my vision is that custom reports support fields specified on this page only (as it is mentioned in our spec): 
https://documentation.bamboohr.com/docs/list-of-field-names
