### ISSUE TITLE
Source Hubspot: parse nested schemas

### ISSUE THREAD

**Issue by tuanchris** [airbytehq/airbyte#15182]
## Tell us about the problem you're trying to solve
- Currently, some main tables such as `deals`, `contacts`, and `companies` don't parse columns retuned from the API, but have them nested inside a property column.

## Describe the solution you’d like
- Parse these properties into columns for all tables 

## Describe the alternative you’ve considered or used
- Writing custom dbt code to parse these manually can be time consuming

## Additional context
![image](https://user-images.githubusercontent.com/52090179/182265453-dc1cc440-990e-4498-9a0b-750b27b1bd77.png)

## Are you willing to submit a PR?

Yes

**Comment by marcosmarxm** [comment]
Let me know if you need any assistaance here @tuanchris probably is only a lack of mapping those fields.

**Comment by UsmanAli99** [comment]
For the developer test HubSpot account **deals** stream is unavailable.

**Comment by marcosmarxm** [comment]
> For the developer test HubSpot account **deals** stream is unavailable.

@UsmanAli99 where did you saw that?

**Comment by arsenlosenko** [comment]
I have checked if we have ability to select and parse nested properties in `deals`, `companies` and `contacts` streams, properties are not selectable in UI, enabling that would require some changes on platform-side, for more info you can refer to [this comment ](https://github.com/airbytehq/airbyte/issues/23859#issuecomment-1621964033) made to a similar request, for now I'll close this issue.
