### ISSUE TITLE
Worker chart error - toYaml in lowercase

### ISSUE THREAD

**Issue by ksazon** [airbytehq/airbyte#15198]
`toyaml` instead of `toYaml` causes chart installation to fail

https://github.com/airbytehq/airbyte/blob/09d690149882ca586e5abc815b072ff56d7a32b1/charts/airbyte-worker/templates/deployment.yaml#L375

**Comment by ksazon** [comment]
Addressed in https://github.com/airbytehq/airbyte/pull/15197

**Comment by andyjih** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/15199
