### ISSUE TITLE
Cannot setup a new S3 Destination

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#15195]
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**: [debian-10-buster-v20210916]
- **Deployment**: Docker (GCE)
- **Source Connector and version**: N/A
- **Destination Connector and version**: S3 (0.3.11)
- **Step where error happened**: Setup  new connection

## Current Behavior
Connection check fail, when setting up a new S3 Destination.

## Expected Behavior
The destination connection check succeed

## Logs

[2022-08-02 10:02:14 INFO i.a.w.t.Tempora.log](https://github.com/airbytehq/airbyte/files/9241290/2022-08-02.10.02.14.INFO.i.a.w.t.Tempora.log)

## Steps to Reproduce
1. Go to Destinations page
2. Click on + New Destination
3. Select S3
4. Fill Key ID, Access Key, Bucket name, Bucket Path and region fields
5. Click on Set up destination

## Are you willing to submit a PR?
Yes

**Comment by haithem-souala** [comment]
Maybe is linked to #11871

**Comment by haithem-souala** [comment]
I tested the connection using AWS CLI, and it's worked.

**Comment by marcosmarxm** [comment]
I asked the connector team to review your contribution, thanks @haithem-souala for proposing the solution.

**Comment by marcosmarxm** [comment]
Closed by #15207
