### ISSUE TITLE
Amplitude: IndexError when reading ActiveUsers stream

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#15208]
## Current Behavior
The Amplitude connectors is sometimes throwing an index out of bound error when zipping the time series in the ActiveUsers stream.
https://sentry.io/organizations/airbytehq/issues/3418815568

According to the docs at https://www.docs.developers.amplitude.com/analytics/apis/dashboard-rest-api/#response_1 , the length of xValues and the length of an element of the series array should be the same, but the issue occurred twice over the last month so it would be worth handling it better.

The root cause is unknown because I couldn't reproduce it with our test account. It's also possible that this is caused by issues on Amplitude's end.

Created this issue so we don't lose track of it, but I don't think it's high priority because it's only intermittent.

**Comment by sherifnada** [comment]
This happened again (see Sentry for affected cloud workspaces). It appears to be a problem from Amplitude's side because the next sync succeeded.

**Comment by sherifnada** [comment]
cc @YowanR for prioritization

**Comment by bazarnov** [comment]
Hello, the issue in sentry is not available: https://sentry.io/organizations/airbytehq/issues/3418815568/
<img width="725" alt="Screenshot 2023-01-11 at 13 43 59" src="https://user-images.githubusercontent.com/22987674/211798062-419e62fe-d1e5-4d73-b2ec-728a9f126ff7.png">

However, it looks like we receive an empty  `series`  object,  which should be the `[]`, once it doesn't contain any values, but it appears to be `None` instead,  which looks like the API issues.  Still, I've added the additional `len` check for this one and the message that informs the User that the API response is empty.

**Comment by bazarnov** [comment]
The issue should be fixed a present, closing this one.
