### ISSUE TITLE
Streams Permissions Research

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#15217]
[We](url) recently introduced an additional step in our connector certification process which ensures that we're aware of the granular permissions required for a specific stream supported by a connector.

Please retroactively include this information in the research docs for the connectors we are certifying this quarter and our existing GA connectors:

- [x] [Zendesk Support](https://docs.google.com/document/d/179CgrB6Mc6TCad8BoAoYLkEt7BsVdW9boIdvauTg6OQ/edit#)
- [x] [Tiktok Marketing](https://docs.google.com/document/d/1CZ-0H9BfNaP7FQrts2MnpGFkilvLwCqulhnLCrDo0mA/edit)
- [x] [Stripe](https://docs.google.com/document/d/1InuPpJz_K7a0bnH_V0otY_WDeJ3AG8CvTr5vB159QbQ/edit)
- [x] [Salesforce](https://docs.google.com/document/d/1XUgv1CPLlOmGib2GBlyTvYLVCRh6tapZ_BVn7VTxQIE/edit#)
- [x] [S3](https://docs.google.com/document/d/1_pC6WEhFHi1ifDc9GpDbzZCbwSh-FbMyIVnF6zeVi3Y/edit#)
- [x] [Mailchimp](https://docs.google.com/document/d/1SuPoss68t2r5b-6zU2hlWAe34RE1za0sRbGvkAGM04M/edit#)
- [x] [LinkedIn Ads](https://docs.google.com/document/d/1Mb4AATy5am1k-SAhnrBr4d3s9T902_zFHwBZT2XLfb4/edit#)
- [x] [Intercom](https://docs.google.com/document/d/1sKtGFXx_BXTlgdJyvjaZosBScLsTCMmFQ1TRbQucTXc/edit#heading=h.veiujkgt5ou5)
- [x] [Instagram](https://docs.google.com/document/d/15JmLQA_4olCZP8OX3JNT9Ym8iGxFXqs-P3r5eVNH43s/edit#)
- [x] [Hubspot](https://docs.google.com/document/d/1KOiJT6hENQTOdNI2DGgMDRTD2JV0NBLOU3uxRyhE42w/edit?usp=sharing)
- [x] [Google Sheets](https://docs.google.com/document/d/1AWluGBRN125nZ7JSatvQvfMYe6t0MYDXOGw9TAFjhZA/edit?usp=sharing)
- [x] [Google Analytics](https://docs.google.com/document/d/1nQnYUwbg9dOvXLdCc3IajRuWBfhwuyU4NEltOMINFJQ/edit?usp=sharing)
- [x] [Google Ads](https://docs.google.com/document/d/1zOu9rBTHLg3JX3oI770B-WNaEkD88saKqp7PjG1Cqr0/edit#)
- [x] [Github](https://docs.google.com/document/d/1GPrZjW6Y6zL-BE2_id0zCp2AGTWCLzwcYuXVLT2s66A/edit?usp=sharing)
- [x] [Facebook Marketing](https://docs.google.com/document/d/1Hle3k7kWsItRwO3vPfKlZPDQmmDNelsgzsT-upjz2k8/edit?usp=sharing)
- [x] [Bing Ads](https://docs.google.com/document/d/1w_YwRU5UROBpUJkxpnMezjp0IJoneQHfxexiT3GsvRM/edit?usp=sharing)
- [x] [Amplitude](https://docs.google.com/document/d/1paI_5Ct8p-KfSRM2ENNg0lEV7hPIili2O3hN7WhCR90/edit?usp=sharing)
- [x] [Klaviyo](https://docs.google.com/document/d/1aiw92DE1a7PgNiheke6Xuiq_n7UEwkcyLDcVXLuJAfM/edit?usp=sharing)
- [x] [Pipedrive](https://docs.google.com/document/d/1Nx9D3qP-8uqxS8pyyHqd0oA2pqyhMJRyxhxEV7yZ6gE/edit?usp=sharing)
- [x] [Recharge](https://docs.google.com/document/d/1VCx1Z2hvVX2sxK8yip5ZQeFYlV2I_34x3p2lmkTOIGU/edit?usp=sharing)
- [x] [Freshdesk](https://docs.google.com/document/d/194jx0s2QEA_A4PmVkozKXkbuQKATRDcEVrtx6jK3dQ8/edit?usp=sharing)
- [x] [Sendgrid](https://docs.google.com/document/d/1sULDqXO4oc--bryILUBto8UxdW-4R4eX68xBywbq-QU/edit?usp=sharing)
- [x] [Typeform](https://docs.google.com/document/d/1zTKqDs1DeS0ZkYZeuBZF08XhSM8IQvj8Lm7gdzO2lHM/edit?usp=sharing)
- [x] [Slack](https://docs.google.com/document/d/1uMmY22ixpxQbpCX45GpEyn0Rgl5X2jRoMRM89C6ohmY/edit?usp=sharing)
- [x] [Twilio](https://docs.google.com/document/d/1nuuavXvYVd4xtIMOBt_txCvX6-Zdj97F-ne_51LgJNM/edit?usp=sharing)
- [x] [Notion](https://docs.google.com/document/d/1872XyPOQphodIdBqA_ldyyLF6rAdR8narWV6zp9_V-E/edit?usp=sharing)
- [x] [Harvest](https://docs.google.com/document/d/16nnGMT0V4z7foiTXde2qZcpNim1GRvm9uba7gQum4XY/edit?usp=sharing)
- [x] [Zendesk Talk](https://docs.google.com/document/d/1FgZQY_gqEACkkv1Gp-yrdt9rIk_YYOG8T19VhBoDfnM/edit?usp=sharing)
- [x] [Marketo](https://docs.google.com/document/d/16hxgPhnA1c2B4vZY0Sg22pKjh7FyBs00nwQBGtANmSA/edit?usp=sharing)
- [x] [Okta](https://docs.google.com/document/d/1S37m8ebCWysEEKP5ZXPZ9-gjEdwWfcP2whZNAyJ8w5w/edit?usp=sharing)
- [x] [Sentry](https://docs.google.com/document/d/1QWv3ivMgx9IWvrIKrAnjm-kqpdPd6NiJZRW0JMAzQgc/edit?usp=sharing)
- [x] [Paypal Transaction](https://docs.google.com/document/d/1MkKIUjvN4Jse1XyLEkhNDUoAe7l64b47ADkCs8VYGx4/edit?usp=sharing)
- [x] [Iterable](https://docs.google.com/document/d/1kV1t156RaPCyNq0FcOAsV0LR2u5EKWfWwZ-o_ug9KFo/edit?usp=sharing)
- [x] [Greenhouse](https://docs.google.com/document/d/1tmY23gj354sDg2MXgIrBzEgc4Auck6bRD1eQEBQFW2c/edit?usp=sharing)
- [x] [Survey Monkey](https://docs.google.com/document/d/1oFblLjBd86OL1ofiamy1ElFDqnt5UD9sLX34y9I-tLw/edit?usp=sharing)
- [x] [Zendesk Chat](https://docs.google.com/document/d/1gdAB96P2YY4jTuuSthLkn7Hn_EKOwPgLbxOAmIrd-04/edit?usp=sharing)
- [x] [Youtube Analytics](https://docs.google.com/document/d/18DwES70Czqnb4evgJNf6He54cVtpNvogmyeVdcymAAE/edit?usp=sharing)
- [x] [Asana](https://docs.google.com/document/d/1lClC4dIptzvYLvSsg1ZhuboFG-vKviHth1_mlFZV1Uk/edit?usp=sharing)
- [x] [Snapchat Marketing](https://docs.google.com/document/d/1eCZPgUA0ZIYf5M9Zm9bKxwH38BCUed-brToav_AWeeY/edit?usp=sharing)
- [x] [Chargebee](https://docs.google.com/document/d/1yRDI1VItRqDfNKMQukqv0kr4Gx6cgh4Oh_Xh5LnxNo4/edit?usp=sharing)
- [x] [Pinterest](https://docs.google.com/document/d/1c6H7UcPkmdZQZBeIIOJ76k_cFGbT_lovj6k6jQZ2p7M/edit?usp=sharing)
- [x] [BambooHR](https://docs.google.com/document/d/1kLxEdkApPm6Gf57i_iKQ6lGvgJgbtZeYfTeqF2HyLjs/edit?usp=sharing)
- [x] [Monday](https://docs.google.com/document/d/1sjGVVLDXqj1ajTl08T8X0DgTPoTg_EGLsg0oMD5ABfk/edit?usp=sharing)
- [x] [Recurly](https://docs.google.com/document/d/1v5KUenGYJOcyRRQ9cdNYFp8_yd4lUwnTtnhsQ-_d_yc/edit?usp=sharing)
- [x] [Braintree](https://docs.google.com/document/d/1uxSslRm_cHWla2FJZ2NBSJ_hhKKJBMBxd9KzPLLxLrU/edit#)
- [x] [Square](https://docs.google.com/document/d/13n0TUx3AHUVDLxNINiFm0w0s_St8VZkTORXG-9I-5iM/edit?usp=sharing)
- [x] [Delighted](https://docs.google.com/document/d/13aE-FB8ZdqBIQ7Nv-sDs4LBK-1U2NmGPmIKfRMEokfI/edit?usp=sharing)

**Comment by ycherniaiev** [comment]
TikTok: added granular permission research. There are 4 main roles that can access TikTok Ads account and seems like noone has restrictions on retrieving info on ads, campigns, reports etc.

**Comment by misteryeo** [comment]
@YuliiaNahoha Looks like @ycherniaiev has started work on this. Should this be added to the sprint and status updated to `In Progress`?

cc: @YowanR

**Comment by ycherniaiev** [comment]
Braintree oAith is in closed Beta now so closing with no updates

**Comment by YowanR** [comment]
> Braintree oAith is in closed Beta now so closing with no updates

@ycherniaiev Could you clarify what that means? Are API keys available for Braintree as an alternative to OAuth or are we blocked here?

**Comment by ycherniaiev** [comment]
> > Braintree oAith is in closed Beta now so closing with no updates
> 
> 
> 
> @ycherniaiev Could you clarify what that means? Are API keys available for Braintree as an alternative to OAuth or are we blocked here?

@YowanR no, I think we are not blocked, we are blocked on oauth implementation.

**Comment by igrankova** [comment]
@YowanR we finished updating researches. Please review this issue and close if there's nothing to add. Thank you.

**Comment by misteryeo** [comment]
@YowanR My suggestion would be to have issues created for each individual connector where we've identified that there is a need for specific permissions so that the engineering team can go back improve the UX on this. 

@sherifnada can you remind us what needs to be done here? As I recall it was:
1. Update the error message so that it's actionable in fixing up the permissions error for a specific stream and;
2. Update the connector so the rest of the sync continues even if a specific stream fails

**Comment by igrankova** [comment]
@YowanR can you please clarify this task for me?

**Comment by ycherniaiev** [comment]
@misteryeo This issue from unblockers prospective has two dimensions: API key( it rarely has permissions issues, but sometimes like in Stripe, admin can configure keys of different lists of permissions for different users - maybe user should be notified about this).Second: oauth that itself has two parts: app's(here like in Facebook or Instagram we should request access to certain streams separately- here we can help and create issues that either already resolved or will be resolved by unblockers) and user's ( there some roles available in certain connectors like TikTok: one like admin has after aftorization full access, other like standard user has not full access to data - these issues should be said to our user). All above we can do and create issues. Regarding error messages-maybe it is better to consult with devs?CC @igrankova

**Comment by YowanR** [comment]
Thanks @igrankova and @ycherniaiev. I agree with what @ycherniaiev said. As for the error message, I also agree that this should be left to the devs. For now, just making sure that we have the issues created and have some way to know which connectors are impacted by different permission for different streams should be enough. As we go deeper into getting per-stream up and running, we can then actually go and make changes to the connectors as need-be.

**Comment by igrankova** [comment]
[Templates: Source [Source Name] enhancements according to MLP](https://docs.google.com/document/d/1x_gIDLQq9GAJoxEGKAVjWkMAwdB9NIlhEb6hBWUur9g/edit?usp=sharing)

**Comment by igrankova** [comment]
See the task for epics/issue creating [here](https://github.com/airbytehq/airbyte/issues/16857)
