### ISSUE TITLE
Create a self-healing scheduler services (x2)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15218]
Relies on Micronaut

* Clean up jobs table with TTL (https://github.com/airbytehq/airbyte/issues/11869)
* Restart temporal workflows that got stuck/stopped (https://github.com/airbytehq/airbyte/issues/14043)

There will likely be 2 services for each above links.  Keeping separate services per job means that a failure is isolated and the other services can continue to run.   There might be a "talks to our DB & services" service, and then a "talks to temporal" service.

In a [future story](https://github.com/airbytehq/airbyte/issues/15699), we will emit metrics when these jobs run. 

Be sure to add an E2E test for the temporal schedule healer

**Comment by evantahler** [comment]
Note from sprint planning for @jdpgrailsdev: As the temporal work wants a scheduler, this is likely the first Micronaut story to prioritize

**Comment by davinchia** [comment]
Can we also emit a warning/metric when this happens? In theory we should never run into self-determinism error on Temporal. It indicates a big error when this happens, and I think it's worth shouting out to us.

**Comment by evantahler** [comment]
Metrics will be emitted here https://github.com/airbytehq/airbyte/issues/15699

**Comment by evantahler** [comment]
Once this is done, we can then merge https://github.com/airbytehq/airbyte/pull/14758 as well

**Comment by gosusnp** [comment]
Depending on how we handle workflow versioning once we have this change ready, we may want to consider https://github.com/airbytehq/airbyte/issues/16762
