### ISSUE TITLE
unable to connect source with host as localhost

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#15235]
I have been trying to use airbyte locally without internet, but the airbyte could not able to connect the host when i try to add it as a localhost. is it designed such a way that when we add host as localhost it looks inside the container. or any is it some configuration required at my end?

**Comment by marcosmarxm** [comment]
Please check https://docs.airbyte.com/troubleshooting/new-connection#connection-refused-errors-when-connecting-to-a-local-db
Also open questions about Airbyte at https://discuss.airbyte.io/
