### ISSUE TITLE
Replace Scheduler with a Workflow Engine

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1523]
## Tell us about the problem you're trying to solve
* We are rewriting features that exist in any good workflow engine. This is bad because it is slowing us down or making us make trade offs on features in the scheduler that we shouldn't have to make. 
* Existing issue: We want to be able to gracefully cancel a running job. This opens up the ability to greatly simplify the flow for upgrading airbyte versions. But we're gated on writing this feature which would exist in most workflow engines. 
* Existing issue: If airflow is `kill -9`'ed while a job is running it is unclear that it will recover gracefully when it is started back up. That's because our state machine doesn't have anyway of resolving a job that is in state `RUNNING` but isn't actually running. We can add code to handle this case, but again we are re writing functionality that is done in any workflow engine.

## Describe the solution you’d like
* I think airflow is the default choice here, but I'm not picky if there's a good case for some other workflow engine (e.g. cadence).
* tbd list full feature set we are looking for.

**Comment by cgardens** [comment]
Goal for this week is a tech spec.

**Comment by jrhizor** [comment]
todo:
- [ ] demonstrate cancellation 
- [ ] demonstrate attempt identification
- [ ] demonstrate log retrieval
- [ ] set up discovery
- [ ] set up syncing
- [ ] set up resets
- [ ] get job history working in the UI
- [ ] update export/import of workspace

**Comment by jrhizor** [comment]
Planning on working on this over the weekend. Want to finish this out.

**Comment by jrhizor** [comment]
Depends on:
- [ ] https://github.com/airbytehq/airbyte/issues/2169 
- [ ] https://github.com/airbytehq/airbyte/issues/2170 
- [ ] https://github.com/airbytehq/airbyte/issues/2171 
- [ ] https://github.com/airbytehq/airbyte/issues/2172 
- [ ] https://github.com/airbytehq/airbyte/issues/2172 
- [ ] https://github.com/airbytehq/airbyte/issues/2173 
- [ ] https://github.com/airbytehq/airbyte/issues/2175 
- [ ] https://github.com/airbytehq/airbyte/issues/2176 
- [ ] https://github.com/airbytehq/airbyte/issues/2177 
- [ ] https://github.com/airbytehq/airbyte/issues/2178 
- [ ] https://github.com/airbytehq/airbyte/issues/2179 

These are all available under the `temporal` label https://github.com/airbytehq/airbyte/labels/temporal

After that the changes https://github.com/airbytehq/airbyte/pull/2130 should be easy to slot in as an atomic change:
- switching the new interface to Activities/Workflows
- rename the scheduler container to worker
- testing only that functionality
- tune settings
- release temporal
- add cancellation scope
- release cancellation feature
