### ISSUE TITLE
Upgrade MSSQL debezium version to 1.9.6

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#15248]
Required for beta (heading is obvious)

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/15248?planning-poker) with ZenHub @edgao @ryankfu @subodh1810 @tuliren @rodireich

**Comment by grishick** [comment]
@subodh1810 please add a description of how you test the connector to make sure that upgrade is working.

**Comment by grishick** [comment]
Keeping the optimistic estimate at 13 points.

**Comment by tuliren** [comment]
This issue blocks https://github.com/airbytehq/airbyte/issues/13781.
