### ISSUE TITLE
Postgres -> Postgres connection is not capturing deletes

### ISSUE THREAD

**Issue by tim-sauchuk** [airbytehq/airbyte#15241]
## Environment
- **Airbyte version**: 0.39.41-alpha
- **OS Version / Instance**: macOS Monterey Version 12.1
- **Deployment**: Docker Desktop 4.11.0
- **Source Connector and version**: Postgres 0.4.38
- **Destination Connector and version**: Postgres 0.3.21
- **Step where error happened**: Sync job

## Current Behavior
After the initial sync, I deleted a row from a table in the source. However, after I re-synced, the deleted row was still present and not marked as deleted in any of the destination tables:
- `_airbyte_raw_table`
- `table`
- `table_scd`

## Expected Behavior
After I deleted the row, the sync should have updated the following in the destination:
- removed the row from `_airbyte_raw_table`
- removed the row from `table`
- added a non-null `_airbyte_end_at` value in `table_scd`
- changed the `_airbyte_active_row` value for the row to `0`

## Logs
[logs-4.txt](https://github.com/airbytehq/airbyte/files/9253033/logs-4.txt)

## Steps to Reproduce
1. Initially sync a table from Postgres -> Postgres
2. Delete one row from the source-version of the table
3. Re-sync the databases and confirm that the deleted row from the source is still present in the destination

## Are you willing to submit a PR?
The inner-workings of Airbyte are a bit over my head, but if absolutely necessary I can work with our lead data engineer to potentially submit a PR.

**Comment by subodh1810** [comment]
@tim-sauchuk you have configured the connector in non-cdc mode 
```
2022-08-02 20:15:58 [44msource[0m > 2022-08-02 20:15:58 [32mINFO[m i.a.i.s.p.PostgresUtils(isCdc):29 - using CDC: false
2022-08-02 20:15:58 [44msource[0m > 2022-08-02 20:15:58 [32mINFO[m i.a.i.s.p.PostgresUtils(isCdc):29 - using CDC: false
```
If you want deletes to be captured, setup the connector in CDC mode by selecting the replication method as Logical replication
<img width="711" alt="Screenshot 2022-08-03 at 9 52 55 PM" src="https://user-images.githubusercontent.com/28527634/182659646-5610c8b6-8ddc-4862-99fe-ddaee99e6afd.png">

**Comment by tim-sauchuk** [comment]
That makes sense. Would we need to start tracking WALs in our source Postgres DB in order for CDC to capture deletes?

**Comment by subodh1810** [comment]
@tim-sauchuk sorry for the long delay in response but yes thats correct, CDC is required to track CDC and you would have to configure your source database to allow Airbyte to connect and process WAL logs. Refer to our postgres [docs](https://docs.airbyte.com/integrations/sources/postgres/#when-to-use-postgres-with-cdc) to learn more about how to configure your source database to sync in CDC mode. Am going to close this issue
