### ISSUE TITLE
MySQL CDC: keep waiting when the state is completely empty or missing for any table

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#15249]
This is a follow-up of https://github.com/airbytehq/airbyte/issues/14890.

**Comment by edgao** [comment]
sprint update: I didn't make any concrete progress on this issue :/

**Comment by grishick** [comment]
Note from grooming: the change will be universal for all connectors using Debezium 1.9.2

**Comment by grishick** [comment]
Adding to MySQL GA Epic, because this problem shows up in MySQL Source

**Comment by bleonard** [comment]
@rodireich think this is related to https://github.com/airbytehq/airbyte/issues/15040

**Comment by bleonard** [comment]
@rodireich @subodh1810 What you think the status of this is? If there's something to do, can you add a better description?

**Comment by bleonard** [comment]
Duplicate of #23257
