### ISSUE TITLE
Create API endpoints in the server to export and import Airbyte Configuration files for upgrades

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1526]
## Tell us about the problem you're trying to solve
As part of #1402, we need to expose API endpoints to trigger export and import methods from the UI.

## Describe the solution you’d like
- An API endpoint in the airbyte Server to trigger exports 
- An API endpoint in the airbyte Server to trigger imports

The export/import archive files produced by airbyte-migration may contain multiple files but they should be compressed into a single archive file including the VERSION tag in a file.

This tarball would then be downloadable/uploadable through the UI so that migration scripts can be applied on top of it externally with a CLI tool.

**Comment by ChristopheDuong** [comment]
The tarball produced by this endpoint should look like this:
```
├── VERSION
├── AirbyteConfig
│   └── DESTINATION_CONNECTION.yml
│   └── STANDARD_DESTINATION_DEFINITION.yml
│   └── STANDARD_SYNC.yml
│   └── STANDARD_WORKSPACE.yml
│   └── SOURCE_CONNECTION.yml
│   └── STANDARD_SOURCE_DEFINITION.yml
│   └── STANDARD_SYNC_SCHEDULE.yml
└── Jobs
    └── jobs.yml
```

**Comment by cgardens** [comment]
@ChristopheDuong this structure looks good. I think we are missing from the jobs category `attempts.yml` and `airbyte_metadata.yaml`

**Comment by ChristopheDuong** [comment]
I'm bookmarking this for the future, i think I might refer back to this right?
https://swagger.io/docs/specification/2-0/file-upload/
