### ISSUE TITLE
🪟 🐛 "Sign Up" button is disabled after after checking the security checkbox, but become active after clicking on button 

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#15272]
## Environment
- **Airbyte version**:  master

## Current Behavior
After filling in the sign-up form, the "Sign Up" remains disabled. But after clicking on it - becomes active.

<img width="485" alt="Screenshot at Aug 03 17-46-53" src="https://user-images.githubusercontent.com/20929344/182723644-3919c28d-15f9-4706-84ab-4fe0f1832a2a.png">

## Expected Behavior
After filling in the sign-up form, the "Sign Up" should be active at once if the whole form is valid.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
