### ISSUE TITLE
Survey Monkey 0.1.9 Error: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#15295]
## Environment
- **Airbyte version**:  0.39.37-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Survey Monkey 0.1.9
- **Destination Connector and version**: 0.4.34
- **Severity**: High
- **Step where error happened**: Sync

## Current Behavior
Sync files

## Expected Behavior
Sync should succeed

## Logs
[logs-35422 (1).txt](https://github.com/airbytehq/airbyte/files/9259747/logs-35422.1.txt)

## Steps to Reproduce
1.
2.
3.

**Comment by sherifnada** [comment]
cc @YowanR

**Comment by YowanR** [comment]
Will tackle this as part of our GA certification
