### ISSUE TITLE
[EPIC] Preventing backwards incompatible changes in source connectors - Syntactic validation in SAT (a.k.a Phase 0)

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#15290]
[RFC on notion.
](https://www.notion.so/Preventing-Backwards-Incompatible-Changes-in-Connectors-e05dafd0f1a349dd819b569a8a4564a7)
The goal of phase 0 is to introduce assertions in the Source/Destination Acceptance Tests that compare the JSON Schemas from the previous version of the connector to the current schemas and check whether backward-incompatible changes have been introduced.

## Spec validation

The connector’s `spec` command outputs a JSON schema describing how to configure the connector. 

If any of the following are present, acceptance tests should fail:

- `additionalProperties: false` is specified (this guards against errors from existing properties being removed)
- New required properties have been introduced
- Existing properties have been marked as required
- Existing property’s type has changed or narrowed
- Existing property’s enum values have narrowed

In addition to these explicit checks, to validate that the old schema is a subschema of the new schema, we can generate configs with the old schema and ensure they pass validation against the new schema.

## Catalog validation
The connector’s `discover` command outputs the available streams and corresponding JSON schema.

If any of the following are present, acceptance tests should fail:

- `additionalProperties: false` is specified
- Existing streams have been removed/renamed
- An existing stream property’s type has been changed

Note: the`discover` command requires passing a config to produce the catalog. We can use the current config to run this test, but it may or may not be compatible with the old connector. To get around this a config in the old format could be specified in the SAT configuration explicitly.

Issues:
* https://github.com/airbytehq/airbyte/issues/14549
* https://github.com/airbytehq/airbyte/issues/14718
* #15057 
* #14595
* #14593
* #14600 
- [x] #15564 

Late requirements:
* https://github.com/airbytehq/airbyte/issues/15439

**Comment by alafanechere** [comment]
It was decided in grooming that #14718 did not required to be totally done: we remove `additionalProperties: false` from GA/Beta non JDBC source connectors in https://github.com/airbytehq/airbyte/pull/14924

**Comment by sherifnada** [comment]
@alafanechere can this be closed?
