### ISSUE TITLE
Document the development process for Windows

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1531]
## Tell us about the documentation you'd like us to add or update
As a Windows developer who would like to contribute to Airbyte, I'd like to know how I can develop on Windows. Airybte does not work out of the box on Windows. See #1403 for a related PR. 

## Are there any related areas of documentation that currently exist? Could you point to them? 
[Developing locally](https://docs.airbyte.io/contributing-to-airbyte/developing-locally) is the main relevant documentation.

**Comment by jrhizor** [comment]
Maybe we can recommend running on WSL? See https://gitlab.com/meltano/meltano/-/issues/2676
