### ISSUE TITLE
[webapp] Cancelled sync job shows `NaN Bytes`

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#15321]
## Environment
- **Airbyte version**:  v0.39.41-alpha
- **Step where error happened**: Connection status page

## Current Behavior
Showing `NaN Bytes` in UI after sync job is canceled.

![image](https://user-images.githubusercontent.com/168664/182910991-49c3ee2f-0176-4964-98bb-aec945e219f2.png)

## Expected Behavior
Should either show 0 Bytes or no Bytes information since the job was canceled (confirm with product)

## Steps to Reproduce
1. Navigate to an airbyte connection and start sync
2. Click on cancel sync

**Comment by robgleason** [comment]
Hello, I made my first time contributing to Airbyte and I made a PR for this issue. I noticed that the AttemptDetails component was displaying this info, and expecting a number. I made a modification to return a number. I could go deeper into the code and find where it is pulling the data from to prevent a null value from ever being created. Also, would there be more tests that would need to be performed for this issue?
