### ISSUE TITLE
Front-End: Replace deprecated AttemptRead field access with updated fields

### ISSUE THREAD

**Issue by pmossman** [airbytehq/airbyte#15333]
This issue was supposed to be a follow-up from https://github.com/airbytehq/airbyte/issues/3247, but I never actually created it, my bad!

Basically, we updated how we store sync stats on the `AttemptRead` in https://github.com/airbytehq/airbyte/pull/9583, but we didn't remove the existing `recordsSynced` and `bytesSynced` because we wanted to give the front-end a chance to update code to use the new fields.

Well, I never created the issue to update front-end code, so we're still writing both the old field and the new field, and the front-end code is still using one of the old fields [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/components/JobItem/components/AttemptDetails.tsx#L82). 

I don't see any usages of `AttemptRead.recordsSynced`, so we might just need to update `AttemptRead.bytesSynced` to `AttemptRead.totalStats.bytesEmitted`.

Once this is taken care of, we can remove these old fields from the `AttemptRead` schema in our API spec entirely.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
