### ISSUE TITLE
Error message from Microsoft Graph API is not propagated to Microsoft Teams source connector

### ISSUE THREAD

**Issue by moszutij** [airbytehq/airbyte#1536]
## Expected Behavior
If the application permissions not correctly configured for the Microsoft Teams source connector, the connector logs contains an error entry but the entry does not display why the error happened. The log entry should contain details about why the error occurred to make it easier for the user to triage the issue. 

Log entry should contain the following
`{"type": "LOG", "log": {"level": "ERROR", "message": "Get channels error. Error: Authorization_RequestDenied Insufficient privileges to complete the operation."}}`

## Current Behavior
The log entry contains
``{"type": "LOG", "log": {"level": "ERROR", "message": "Get channels error."}}``

## Steps to Reproduce
Register an application in the Azure Portal but don't grant any permissions. Configure the Microsoft Teams source connector to use the application (with no permissions)

## Severity of the bug for you
Low

**Comment by sherifnada** [comment]
Fixed in #1537
