### ISSUE TITLE
Add Refresh Source Schema Button back to Create page

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#15371]
Following up on a Slack discussion here: https://airbytehq-team.slack.com/archives/C02U2SSHP9S/p1659716923213649?thread_ts=1659699405.736889&cid=C02U2SSHP9S

## Current problem:
Currently, if a user creates a source, creates a connection, then adds a new table to their source and goes to create another connection, the old source schema is shown (ie: the new table is not there).  There is no way from the connection creation screen to refresh the source schema currently.  

Here is the issue that prompted us to remove that functionality originally: https://github.com/airbytehq/airbyte/issues/11859

## Proposed solution:
Add back the button for now. 

## Alternatives considered:
Make sure we're fetching/refreshing the source schema each time a connection is created.  
- We would like to end up here.  Given the architecture of this area of the code base, that would be an involved change to implement.  Furthermore, we are in a project to refactor the workflow here, and have auto-detecting schema changes coming up in the roadmap.  This does not seem like the right time to introduce this feature.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Requires some more clarification with @andyjih about whether we want to show "Catalog changes" dialog here.

**Comment by andyjih** [comment]
It sounds like perhaps the Source's schema is being cached. Ideally, when setting up a new Connection with an existing Source, the Source's schema should be re-retrieved.

**Comment by andyjih** [comment]
I think for now, showing the Catalog changes is ok. I'm going on the assumption that users who are setting up multiple connections with the same Source will understand that the schema is tied to the source and not the Connection.

**Comment by dizel852** [comment]
I did some research and found out that adding the "Refresh Source Schema" Button back to Create page won't fix the issue we have.

https://loom.com/share/0ddfb0dd91ed466fb51c97cf2f4c0db1

As you can see, "Refresh schema" button doesn't actually refresh the schema, but if we will do so for the existing connection - it does.
 
Problems I see:
1. `api/v1/sources/discover_schema` request doesn't actually refresh the source schema
2. `catalogDiff` prop which describes changes in source schema is available only for existing connections (via `pi/v1/web_backend/connections/get`) so we can't reuse it during new connection creation

@timroes any thoughts? I guess we need to ask the backend team to extend the API. WDYT?

**Comment by timroes** [comment]
I think when refreshing the schema before the connection has ever been saved we won't need to show a diff modal, since there has never really been any sync run on the previous state. Thus I'd suggest we just don't show the modal since it's not available via the API at the moment (cc @andyjih would that be fine with you?).

For (1) that discover_schema doesn't actually refresh the source schema, that sounds like a bug in the API to me, since I feel this one should really ... well ... discover the source schema :D And thus have a fresh one every time it's called. Can we open an issue for the BE team to look into this, and mark this issue as blocked until then?
