### ISSUE TITLE
Source MySQL should correctly map temporal types to JsonSchema

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#15381]
Currently, source-mysql maps dates, datetimes, and timestamps to string. These should be mapped to date, timestamp_without_timezone, and timestamp_with_timezone respectively.

We should probably do https://github.com/airbytehq/airbyte/issues/14628 first.

See e.g. https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSourceOperations.java#L182 (no explicit date/time handling, so they defaults to STRING) and tests (https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/test-integration/java/io/airbyte/integrations/source/mysql/AbstractMySqlSourceDatatypeTest.java#L237-L238)

**Comment by edgao** [comment]
this issue is a superset of https://github.com/airbytehq/airbyte/issues/3865 (which only mentions DATETIME handling).

**Comment by tuliren** [comment]
Solution: copy what Postgres temporal processing logic to MySQL, and DRY the code if necessary.

**Comment by tuliren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/15381?planning-poker) with ZenHub @ryankfu @edgao @subodh1810 @rodireich

**Comment by tuliren** [comment]
This issue is already covered in https://github.com/airbytehq/airbyte/issues/14628
