### ISSUE TITLE
no 'custom transformation' in normalization page

### ISSUE THREAD

**Issue by yuxh** [airbytehq/airbyte#15400]
## Environment
- **Airbyte version**:   0.39.42-alpha
- **OS Version / Instance**: centos
- **Deployment**:  Docker
- **Source Connector and version**: mongodb
- **Destination Connector and version**: clickhouse
- **Step where error happened**: Setup new connection

## Current Behavior
can not find 'custom transformation' in normalization page or other place.
## Logs

<img width="924" alt="20220808174352" src="https://user-images.githubusercontent.com/1754573/183389460-4e9faacd-833d-4173-a5f4-35a0296bfde2.png">

**Comment by sajarin** [comment]
Hey @yush, what version connectors are you using for mongodb and clickhouse?

**Comment by yuxh** [comment]
> 



> Hey @yush, what version connectors are you using for mongodb and clickhouse?

I just git pull from master without any modification

**Comment by marcosmarxm** [comment]
Closed because of lack of destination version info. Current status of spec.json of Clickhouse support normalization
