### ISSUE TITLE
Source MySQL: Incremental append | Deduped + history not working

### ISSUE THREAD

**Issue by ajatau** [airbytehq/airbyte#15410]
## Environment
- **Airbyte version**:  0.39.42-alpha
- **OS Version / Instance**: Ubuntu 
- **Deployment**: Docker on EC2
- **Source Connector and version**: MySQL 0.6.1
- **Destination Connector and version**: BigQuery 1.1.14
- **Step where error happened**: During Sync when replication is set to Incremental Deduped+history

## Current Behavior
Every hour new sync pulls all the data from source. CDC is set on the MySQL source

<img width="1302" alt="Screenshot 2022-08-08 at 18 30 25" src="https://user-images.githubusercontent.com/9402003/183478080-b79d5ef4-ff3b-4dc2-9ec5-373abda9afde.png">

## Expected Behavior
Each new sync should pull only new data from the source and append it to the destination.

## Logs
These are logs from a previous run 

[logs-32.txt](https://github.com/airbytehq/airbyte/files/9283813/logs-32.txt)

## Steps to Reproduce
1. Add connector and set CDC 
2. Add destination 
3. Sync every hour

## Are you willing to submit a PR?
Yes

**Comment by ajatau** [comment]
All the cursor fields are set to NULL, I think that might be the issue. 

Any way I could solve this?
<img width="1007" alt="Screenshot 2022-08-08 at 18 53 09" src="https://user-images.githubusercontent.com/9402003/183482049-954a7a5d-abfe-4772-b3ff-93585176db58.png">

**Comment by marcosmarxm** [comment]
What is the version of our MySQL database? Could you downgrade the Source connector to version 0.5.0 and try again?

**Comment by ajatau** [comment]
@marcosmarxm its MySQL version 8.0.23
I downgraded and still faced the same issue. 
The connection state says this : 
`{
  "cdc": false,
  "streams": [
    {
      "stream_name": "accounts",
      "cursor_field": [],
      "stream_namespace": "data_production"
    },
    {
      "stream_name": "performances",
      "cursor_field": [],
      "stream_namespace": "moni_production"`

Not sure why it has cdc as false and the cursor fields empty

**Comment by ajatau** [comment]
@marcosmarxm is there a way I can change the cursor field manually and the cdc?

**Comment by marcosmarxm** [comment]
@ajatau no it's not possible.

**Comment by philippeboyd** [comment]
@ajatau yes, it's possible.

navigate inside the postgresql container with `docker exec -ti airbyte-db psql -U docker -d airbyte`

From there you'll be able to get the states from the `state` table

```sql
select state from state where connection_id = '<you_connection_id>';
```

Then simply manually update the state
```sql
update state set state = '{"state":{"cdc":true,"streams":[{"stream_name":"accounts","cursor_field":[],"stream_namespace":"data_production"},...}' where connection_id = '<you_connection_id>';
```

Just make sure the state that you see in the UI is wrapped with the field `state` in the database such as `{"state":<STATE_OBJ_HERE>}`.

**Comment by sajarin** [comment]
Thanks Philippe for the workaround. @ajatau, can you confirm that you're able to manually update the state?

**Comment by ajatau** [comment]
@sajarin yes it worked.

**Comment by grishick** [comment]
The connector is trying to read binlog starting at 
```
'SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin-changelog.001258, currentBinlogPosition=11270, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null]', 
```
but this is no longer available on the server. Forcing the snapshot execution as it is allowed by the configuration.

**Comment by grishick** [comment]
@ajatau the issue is that binlog is being cleaned up. The solution is to increase the retention period for binlogs to longer than the period between syncs.
