### ISSUE TITLE
[Helm][Temporal] Remove hard coded value for DB host

### ISSUE THREAD

**Issue by NipunaPrashan** [airbytehq/airbyte#15432]
## Environment
- **Airbyte version**: 0.39.39-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Kubernetes deploy env
- **Step where error happened**: Deploy

## Current Behavior
Temporal always takes the default value for DB host.

## Expected Behavior
Temporal does not pick the DB host value defined in the values.yaml

## Steps to Reproduce
1. enable external database configurations and define a hostname in the values.yaml
```
 externalDatabase:
  host: ABC
 ``` 
2. run `helm template airbyte-temporal  airbyte-temporal` and see the output

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Thanks for the contribution @NipunaPrashan

**Comment by evantahler** [comment]
Closing - was fixed via https://github.com/airbytehq/airbyte/pull/15510
