### ISSUE TITLE
Source MySQL: Edit connection state or set cursor field rather than source defined

### ISSUE THREAD

**Issue by ajatau** [airbytehq/airbyte#15437]
## Tell us about the problem you're trying to solve

I setup cdc on MySQL and when loading data to BigQuery with incremental (deduped + history) it sets it as false in the connection state. So my connection syncs the full table everytime
<img width="435" alt="Screenshot 2022-08-08 at 21 43 17" src="https://user-images.githubusercontent.com/9402003/183603268-cd0b22c6-7586-4ad3-afaa-65790e0316be.png">

## Describe the solution you’d like
I would like to use CLI to edit the cursor fields or connection state

## Describe the alternative you’ve considered or used
I sync the full table every 6 hours

## Additional context
I just need to be able to set my cursor so I sync the table with less cost

## Are you willing to submit a PR?
No

**Comment by philippeboyd** [comment]
@ajatau see my [comment](https://github.com/airbytehq/airbyte/issues/15410#issuecomment-1211182215) on your other issue

**Comment by grishick** [comment]
@ajatau are you saying that even though you've set up CDC on MySQL Source, every time you run a sync the state gets reset to `cdc:false`?

**Comment by subodh1810** [comment]
The state parameter `cdc:false` is not used by the connector anywhere, its just a minor bug of misinformation but doesn't play any role in the sync process.

**Comment by grishick** [comment]
The solution is to add an FAQ section that explains setting binlog retention to a sufficiently long period, so that binlog does not get deleted between syncs. 
See comment [here](https://github.com/airbytehq/airbyte/issues/15410#issuecomment-1234458981) and [here](https://github.com/airbytehq/airbyte/issues/15410#issuecomment-1234466079)
