### ISSUE TITLE
Bad Info in Connection State `cdc: false` when CDC is true

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15447]
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**: MacOS
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.42
- **Destination Connector and version**: Postgres 0.3.21
- **Step where error happened**: Sync job

## Current Behavior
I'm using a very basic CDC local database to test and I saw that the connection state is saving the wrong information.
Connection State:
```json
{
  "cdc": false,
  "streams": [
    {
      "stream_name": "cars",
      "cursor_field": [],
      "stream_namespace": "public"
    }
  ],
  "cdc_state": {
    "state": {
      "{\"schema\":null,\"payload\":[\"postgres\",{\"server\":\"postgres\"}]}": "{\"transaction_id\":null,\"lsn_proc\":24247192,\"lsn_commit\":24246712,\"lsn\":24247192,\"txId\":742,\"ts_usec\":1659986834030419}"
    }
  }
}
```
![image](https://user-images.githubusercontent.com/5154322/183656913-0d2b94a0-8ccd-4585-90b1-5d631174dbac.png)
![image](https://user-images.githubusercontent.com/5154322/183657013-cc0cf4f5-13e0-42d3-8e7e-66b476b6ac55.png)

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1. create a postgres source with cdc enabled
2. create a destination
3. sync source to destination and check the connectino state page

## Are you willing to submit a PR?

No

**Comment by Phlair** [comment]
<img width="966" alt="Screenshot 2022-08-09 at 15 50 01" src="https://user-images.githubusercontent.com/27702686/183680669-d97cbabc-b6c6-4eb9-a3d9-d3772234a8e1.png">

Copying Subodh's answer from oncall issue. @marcosmarxm think we can close this (or maybe alter the issue to fix the bad info?)

**Comment by marcosmarxm** [comment]
I updated to bad info, I prefer to check and correct that in the future

**Comment by subodh1810** [comment]
I think this is only relevant for LEGACY state and is not a problem for later versions (versions that support GLOBAL state for CDC and switch from LEGACY), am going to close this
