### ISSUE TITLE
Display cursor field when using CDC

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15448]
Display some indication that there's a cursor for source-defined cursors instead of nothing. It can be as simple as a text that reads "Source-defined".

See [this comment below](https://github.com/airbytehq/airbyte/issues/15448#issuecomment-1239687687) on details of how we can identify a source-defined cursor.

How to setup a source with a source-defined cursor:
https://docs.airbyte.com/integrations/sources/postgres/#configuring-postgres-connector-with-change-data-capture-cdc

## Context

When using a change data capture (CDC) source, Airbyte doesn't display the cursor. Airbyte must have a process to validate if a cursor was selected automatically or not, and in the second case shows an error.
![image](https://user-images.githubusercontent.com/5154322/183658523-f6647431-71d8-4125-a33e-fe9b18480b92.png)

**Comment by marcosmarxm** [comment]
Zendesk ticket #[1849](https://airbyte7538.zendesk.com/agent/tickets/1849) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-09 at 13:51:*

<blockquote><div class="zd-comment" dir="auto">I created the issue in Github to implement this feature <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15448">https://github.com/airbytehq/airbyte/issues/15448</a><br></div></blockquote>

**Comment by lmossman** [comment]
@marcosmarxm the reason that no cursor field is shown for streams on a CDC source is because CDC sources use a [source-defined cursor](https://docs.airbyte.com/understanding-airbyte/connections/incremental-append#source-defined-cursor), as CDC sources internally keep track of the current position in the replication log (see docs about that [here](https://docs.airbyte.com/understanding-airbyte/cdc)). Since they don't use an actual column of the stream to do this, there is no "cursor field" set for those streams.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-25 at 02:48:*

<blockquote><div class="zd-comment" dir="auto"><div class="zd-indent" style="margin-left: 0px;"><p dir="auto">The reason that no cursor field is shown for streams on a CDC source is because CDC sources use a <a rel="noopener noreferrer" href="https://docs.airbyte.com/understanding-airbyte/connections/incremental-append#source-defined-cursor">source-defined cursor</a>, as CDC sources internally keep track of the current position in the replication log (see docs about that <a rel="noopener noreferrer" href="https://docs.airbyte.com/understanding-airbyte/cdc">https://docs.airbyte.com/understanding-airbyte/cdc</a>). Since they don't use an actual column of the stream to do this, there is no "cursor field" set for those streams.</p></div>&nbsp;<br></div></blockquote>

**Comment by lmossman** [comment]
During grooming, we discussed adding some placeholder text here when the source is using a source-defined cursor to track incremental state but doesn't have any cursor fields listed. 

For example, here is a snippet of the get connection response for a stream in a CDC source:
```
                    "supportedSyncModes": [
                        "full_refresh",
                        "incremental"
                    ],
                    "sourceDefinedCursor": true,
                    "defaultCursorField": [],
                    "sourceDefinedPrimaryKey": [
                        [
                            "id"
                        ]
                    ],
                    "namespace": "public"
```
In this case, `sourceDefinedCursor` is `true`, but `defaultCursorField` is an empty array, which means the source is using its own internal mechanism to keep track of the incremental progress, but it is not doing this through any specific columns/fields on the stream. This same situation could also happen for other non-CDC sources that define their own cursors that are not based on fields.

The UI currently renders this as a blank cursor, which can be a confusing UX as Marcos pointed out through this ticket. So we should therefore add some placeholder text here, such as `(source-defined)`, which is shown when `sourceDefinedCursor` is `true`, but `defaultCursorField` is empty.

Here is a link to the docs on how to set up a CDC source for anyone who wants to test that out: https://docs.airbyte.com/integrations/sources/postgres

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-26 at 17:56:*

<blockquote><div class="zd-comment" dir="auto">A fix was merged in <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/16999">https://github.com/airbytehq/airbyte/pull/16999</a> which is going to show as source-defined cursor.<br></div></blockquote>
