### ISSUE TITLE
MySQL CDC: Not pulling data incrementally.

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15450]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1850](https://airbyte7538.zendesk.com/agent/tickets/1850)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px;">Memory / Disk: 32Gb / 30 Gb</li>
<li style="padding-bottom: 10px;">Deployment: Docker</li>
<li style="padding-bottom: 10px;">Airbyte Version: 0.39.41-alpha</li>
<li style="padding-bottom: 10px;">Source name/version: MySQL (0.6.1)</li>
<li style="padding-bottom: 10px;">Destination name/version: BigQuery (1.1.14)</li>
<li style="padding-bottom: 10px;">Step: The issue is happening during sync.</li>
<li style="padding-bottom: 10px;">Description: Each sync pull the whole data from the source as if it were a full refresh. I expect it to pull only new records<br>
<div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/9/90647a51767cee1026ae6b243a6fc908fdfd87e1.jpeg" title="Screenshot 2022-08-08 at 17.55.43" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/9/90647a51767cee1026ae6b243a6fc908fdfd87e1_2_551x500.jpeg" alt="Screenshot 2022-08-08 at 17.55.43" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>Screenshot 2022-08-08 at 17.55.43</span><span>1426×1294 56.2 KB</span>
</div></a></div>
</li>
</ul> 

[<a href="https://discuss.airbyte.io/t/incremental-append-and-deduped-history/2160/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-08 at 19:29:*

<blockquote><div class="zd-comment" dir="auto">Please share one log example so it's possible to understand what is causing that, if it's missing a cursor etc.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-08 at 20:36:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">here’s a link to the log</p>
<p dir="auto"><a href="https://github.com/airbytehq/airbyte/files/9283813/logs-32.txt" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://github.com/airbytehq/airbyte/files/9283813/logs-32.txt</a></p> 

 [<a href="https://discuss.airbyte.io/t/incremental-append-and-deduped-history/2160/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-08 at 20:51:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I think it is missing a cursor because it shows null in the logs.<br>
CDC is set on the source<br>
</p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/7/743e85049df74a26495ce013172df7be125d34fa.jpeg" title="183482049-954a7a5d-abfe-4772-b3ff-93585176db58" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/7/743e85049df74a26495ce013172df7be125d34fa_2_690x268.jpeg" alt="183482049-954a7a5d-abfe-4772-b3ff-93585176db58" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>183482049-954a7a5d-abfe-4772-b3ff-93585176db58</span><span>1920×747 322 KB</span>
</div></a></div><p dir="auto"></p> 

 [<a href="https://discuss.airbyte.io/t/incremental-append-and-deduped-history/2160/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-09 at 14:05:*

<blockquote><div class="zd-comment" dir="auto">I escalated the issue to Github to Airbyte team investigate the issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15450">https://github.com/airbytehq/airbyte/issues/15450</a><br></div></blockquote>

**Comment by bleonard** [comment]
@subodh1810 it's using CDC and the [logs](https://github.com/airbytehq/airbyte/files/9283813/logs-32.txt) have this in them:
> {name='xxx', namespace='yyy'}. Cursor Field: null Value: null
Is that expected or not?
I would expect to see the highwater mark from CDC in here but am not sure where to look.

**Comment by subodh1810** [comment]
Oh I know whats going on, take a look at the following lines from the logs attached, so basically by the time the second sync runs, the binlog is purged. We need to ask the customer to increase the retention period of the binlogs in their source database. Our [docs](https://docs.airbyte.com/integrations/sources/mysql/#change-data-capture-cdc) already state this 
```
binlog_expire_log_seconds : This is the number of seconds for automatic binlog file removal. We recommend 864000 seconds (10 days) so that in case of a failure in sync or if the sync is paused, we still have some bandwidth to start from the last point in incremental sync. We also recommend setting frequent syncs for CDC.
```
```
2022-08-07 17:52:10 [44msource[0m > 2022-08-07 17:52:10 [32mINFO[m i.d.c.m.MySqlConnection(availableBinlogFiles):397 - Get all known binlogs from MySQL
2022-08-07 17:52:10 [44msource[0m > 2022-08-07 17:52:10 [32mINFO[m i.d.c.m.MySqlConnectorTask(isBinlogAvailable):328 - Connector requires binlog file 'mysql-bin-changelog.001258', but MySQL only has mysql-bin-changelog.001328, mysql-bin-changelog.001329, mysql-bin-changelog.001330
2022-08-07 17:52:10 [44msource[0m > 2022-08-07 17:52:10 [33mWARN[m i.d.c.m.MySqlConnectorTask(validateSnapshotFeasibility):390 - The connector is trying to read binlog starting at 'SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin-changelog.001258, currentBinlogPosition=11270, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null]', but this is no longer available on the server. Forcing the snapshot execution as it is allowed by the configuration.
```

Am going to close this. Apologies for the delay in response.

**Comment by bleonard** [comment]
Just checking: Is there a way to detect that situation @subodh1810

**Comment by ifun248** [comment]
> 
Adding, in AWS MySQL RDS the binlog file rerention is decided by parameter 'binlog retention hours'. The commands to set this parameter are below:
(1) call mysql.rds_set_configuration('binlog retention hours', 24);
(2) call mysql.rds_show_configuration;
