### ISSUE TITLE
Platform discovers the Airbyte Protocol version of a connector, if a connector doesn’t expose an Airbyte Protocol Version, the platform will assume it supports v0.2.0

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15460]

**Comment by gosusnp** [comment]
Captured in https://github.com/airbytehq/airbyte/issues/15978, https://github.com/airbytehq/airbyte/issues/15979 and https://github.com/airbytehq/airbyte/issues/15980 for each respective use cases.
