### ISSUE TITLE
[low-code connectors] Protect top-level namespace in yaml file

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#15467]
## Tell us about the problem you're trying to solve
Developers can define reusable objects at the top level of the yaml file, which will make it harder to extend the protocol in a backward-compatible way.

## Describe the solution you’d like
We should move top-level definitions from the top-level namespace to a clearly defined structure.

Proposal:
Add a top-level field `definitions` similar what we do in the [airbyte protocol](https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L12).
[Example of what the yaml file would look like](https://github.com/airbytehq/airbyte/pull/15257/files#diff-00b5a1d5732e46d1153c9a60a3738e2a4f0af1b5a8d58fb01abfa1c5e94b10d0R1)

This issue can be broken down into 2 steps:
- [ ] Update the template and the code samples to reflect the structure
- [ ] Prevent developers from defining anything in the top level namespace

## Describe the alternative you’ve considered or used
We could add more structure, but not all components are always defined, so it's not clear to me what the structure would have to be.

**Comment by girarda** [comment]
grooming notes:
* it might be enough at first to only tell people not to define components at the top level
* the top level namespace will 3 fields ["streams", "check", "definitions"]
* we could hack the schema validation to ensure there are no custom top-level fields
* @girarda create a ticket to ensure this gets incorporated into the json schema

**Comment by brianjlai** [comment]
We currently have validation that prevents the developer from adding anything unexpected beyond those three (and version). But that is more to address the hack. [#15543](https://github.com/airbytehq/airbyte/pull/15543) has a test case for it. But leaving this over for the last one.

**Comment by sherifnada** [comment]
@brianjlai is this still needed? please reopen if so

**Comment by brianjlai** [comment]
can leave closed
