### ISSUE TITLE
Airbyte Users can see a changelog for the Airbyte Protocol (docs page)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15465]
[PRD Link](https://docs.google.com/document/d/1RMCSZKt9GT_RMR0hI4jjb7WBcppkzTTQ87hPqSqzwT8/edit#heading=h.5bzrm83il6zx)

As the Airbyte Protocol gains multiple versions, we will need to document what the change are, and what effect those changes have on users and developers.  Do we keep links to the documentation of older version?

(excerpt from the PRD) The versions we predict we will have for the remainder of 2022 are:
```
v0.0.0 - initial version of Airbyte Protocol 
v0.1.0 - AirbyteTraceMessage - new feature, non breaking, optional 
v0.2.0 - New State messages introduced (Aug 2022 - here now)
but still backwards compatible with connectors dealing with both versions of STATE
v1.0.0 - connectors advertise their version of the protocol (or we assume a version)
	This works because the platform speaks v1.x and v0.x at the same time
	We assume all connectors without a version are on v0.2.0
	Airbyte Protocol allows additional properties
v1.1.0 - New datatypes in Protocol (additive change)
v1.2.0 - New AirbyteTraceMessage (optional additive change) 
v2.0.0 - legacy state removed (breaking change - Feb 1, 2023)
legacy state transformer/translator/representer (between legacy and per-stream/global) in platform
```

**Comment by Amruta-Ranade** [comment]
@evantahler If I understand correctly, is this issue about adding a changelog to the [Airbyte Protocol doc](https://docs.airbyte.com/understanding-airbyte/airbyte-protocol)?

**Comment by evantahler** [comment]
Yep! I've updated the description.  It's part of the [epic](https://app.zenhub.com/workspaces/oss-platform-625a01eb010e82001390f49e/issues/airbytehq/airbyte/14276) to add versioning to the Airbyte Protocol

**Comment by gosusnp** [comment]
I think we have another need around the documentation itself https://github.com/airbytehq/airbyte/issues/16024.
We are moving towards versioning with major versions and breaking change. I think the current doc format assumes that we have one evolving up-to-date format. I wonder if we should moved towards a per major version doc with some highlights of the changes from the previous version.
@Amruta-Ranade, do you have a suggestion here?

**Comment by Amruta-Ranade** [comment]
I'm unclear on are we versioning only the protocol and hence only one doc in the docset or are we versioning the product and hence the entire docset.

**Comment by gosusnp** [comment]
We are moving towards a system where we'd have three versions:
* Airbyte Protocol
* Airbyte Platform
* Connectors (each should be versioned independently)

The big change here is that we are going to explicitly version the Airbyte Protocol. The compatibility between connectors and platform should be centered around the protocol. As long as the platform and the connectors use the same version of the airbyte protocol, they should be compatible.

**Comment by Amruta-Ranade** [comment]
Gotcha. Adding a changelog to this [page](https://docs.airbyte.com/understanding-airbyte/airbyte-protocol/) seems like the right start to me
