### ISSUE TITLE
Store database catalog for Debezium

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#15471]
## Summary
- To enable per-stream state for CDC for MySQL and MSSQL, we need to store the database catalog.
  - This was not required for Postgres CDC.
- This blocks https://github.com/airbytehq/airbyte/issues/13781.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/15471?planning-poker) with ZenHub @edgao @rodireich @ryankfu @subodh1810 @tuliren

**Comment by subodh1810** [comment]
This is still in progress, would take 2-3 more days
