### ISSUE TITLE
Documentation: Change all instances of Airbyte OSS to Airbyte Open Source

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#15483]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

**To-Do:** Change all instances of Airbyte OSS to Airbyte Open Source across all Docs

**Comment by nehanawar025** [comment]
Hello . Please assign this to me. I am new to open source .That is why I am willing to start with typos or documentation.

**Comment by Amruta-Ranade** [comment]
Done! Let me know if you need help :)

**Comment by nehanawar025** [comment]
I am confused about  if I have to check all the folders or only the 'docs' folder of airbyte .
Please help.

**Comment by Amruta-Ranade** [comment]
Just the docs folder

**Comment by Skar019** [comment]
Please I want to contribute to an open source project for the first time, can you assign me

**Comment by nehanawar025** [comment]
I have made all the changes. Please consider reviewing. Thank you for assigning this to me.

**Comment by nehanawar025** [comment]
I am sorry as it was my first time . I thought I have to make every Airbyte OSS to Airbyte Open Source in docs folder.

**Comment by Amruta-Ranade** [comment]
@nehanawar025 No worries! Yep, the task is to replace every Airbyte OSS instance with Airbyte Open Source in the docs folder. However, your PR changed the assignment in code files as well. Let me know if you want to give it another try :)

**Comment by Jagrutiti** [comment]
Hey Amruta, is this issue still open?

**Comment by Amruta-Ranade** [comment]
Yes it is!

**Comment by Amruta-Ranade** [comment]
Closed via #15885 
Thanks so much, @Jagrutiti
