### ISSUE TITLE
Apply best practices for Postgres source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1549]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

## Checklist
* [x] Integration tests verifies all sync modes function correctly
* [x] DB Connector verifies all data types can emit data correctly for both `read` and `discover` operations
* [x] Check connection verifies permissions upfront
* [x] Check connection failure emits actionable error messages

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368140166321) by [Unito](https://www.unito.io)

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/1549?planning-poker) with ZenHub @tuliren @edgao @subodh1810

**Comment by grishick** [comment]
This is most likely already implemented. Todo: verify that all conditions outlined by @sherifnada in the original description are satisfied.

**Comment by tuliren** [comment]
TODO item 1 & 2 are likely done. Item 3 & 4 are covered in a separate issue to optimize the connection check to emit actionable messages.

**Comment by etsybaev** [comment]
"Check connection failure emits actionable error messages" is in progress as part of the ticket https://github.com/airbytehq/airbyte/issues/11322 (https://github.com/airbytehq/airbyte/pull/11927)

**Comment by etsybaev** [comment]
Closing this ticket, as all points are already done except one, but it's under implementation on https://github.com/airbytehq/airbyte/issues/11322 ticket
