### ISSUE TITLE
When creating a new source/destination I want to toggle the password to be visible

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1550]
## Tell us about the problem you're trying to solve
Sometime I struggle to understand what I got wrong when setting up my configuration.

## Describe the solution you’d like
When creating a new source/destination I want to toggle the password to become visible just to audit that I input the proper password.

**Comment by ChristopheDuong** [comment]
duplicates https://github.com/airbytehq/airbyte/issues/1411

**Comment by cgardens** [comment]
@michel-tricot @ChristopheDuong do we want to allow making passwords that have already been saved visible? (we made the choice that we never send the password back to the UI once it it saved, so if we need to adjust our protocol if that is in scope)

**Comment by ChristopheDuong** [comment]
It's good If we can distinguish between the scenarios:
- it's the first time we are configuring a password for the source: I just typed (or copy/paste it) I should be able to toggle on/off 
- I come back and edit the password of a connector created in the past, I don't mind if it's kept secret, it's probably more secure so I can't "steal" that info

**Comment by michel-tricot** [comment]
Yep agreed with christophe!
