### ISSUE TITLE
Source Stripe: sync modified objects, not only created

### ISSUE THREAD

**Issue by ilkkapeltola** [airbytehq/airbyte#15509]
## Tell us about the problem you're trying to solve
I want to ensure all of my Stripe data is cloned, up-to-date, in my data warehouse.
But Stripe API doesn't allow records to be filtered based on the date they were modified.
The current Stripe connector allows you to choose N days to always refresh, but we have data that gets updated e.g. 180 days after creation (and more). If I would use 180 in that setting, that'd mean each day I would need to refresh all data from last 180 days.

## Describe the solution you’d like
There is an "Events" stream in the Strip API which has an event every time an object was modified. What I'd like the connector to do is always check the events since previous sync, go through all the modified items and update them individually. This is what the [Singer Tap for Stripe](https://github.com/singer-io/tap-stripe) does and it works fine.

## Describe the alternative you’ve considered or used
My alternative to this solution is honestly to keep running Meltano instead. As I don't want too many tools, it's unlikely I will migrate over to Airbyte if I would any way need to run this in Meltano.

Another alternative would be to do full-refresh every time, but since updating everything from Stripe each time takes forever, we cannot really consider this.

## Are you willing to submit a PR?
Sadly, very unlikely I would be able to.

**Comment by nauxliu** [comment]
I'm surprised that The Stripe Connector is in the GA stage without the support for syncing modified objects.

**Comment by TBernstein4** [comment]
A Cloud User reported frustration with this issue. They are using the Full-Refresh workaround but do not like the lack of efficiency or the cost. @YowanR as reference from our convo

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Stripe: Sync modified objects, not only created ones](https://app.harvestr.io/components/0/list/U4ojH_1bm)

**Comment by killthekitten** [comment]
This is a real problem, and full sync is the only workaround that is _somewhat_ reliable. We use the Subscriptions API heavily, and some of the objects that are related to this API, stick around and receive updates for years and years. 

To give a couple examples where we had run into issues:
- When querying the balance on the customers stream. Older records always show up as if they had a surplus credit.
- When following the subscription lifecycle. Status changes for older subscriptions are unavailable/unreliable.

To fight the issue, at the moment we get this data from Stitch. They are using the events stream thanks to Singer, and it seems to do the trick. The implementation however has its flaws: we regularly see the lookback window data conflicting with the events stream data.

**Comment by andresbravog** [comment]
@YowanR , I’d like to start working on this issue.

**Comment by YowanR** [comment]
Awesome! Assigning it to you, @andresbravog ! 🔥

**Comment by andresbravog** [comment]
Apologies for the delay. I'll get at it this weekend. Thanks

**Comment by andresbravog** [comment]
@YowanR I have failed to find time for this issue, this is quite a significant change if we want to support both the old N days lookback incremental and the events based incremental. Also kickstarting this implementation brought some questions: 

1. `NOTE: Right now, access to events through the [Retrieve Event API](https://stripe.com/docs/api/events#retrieve_event) is guaranteed only for 30 days.` We should tell this to users, as this workflow needs to run every < 30 days not to lose data. After that, we should force a full ingestion.
 
1. Should we have a logic to handle deletions on incremental updates based on events?

1. Not all the streams produce events, they are listed [here](https://stripe.com/docs/api/events/types)

1. There is no batch `id` requests or pagination on Stripe API for list endpoints so this incremental method will produce an API call per updated record, increasing considerably the number of calls to the Stripe API and most likely the ingestion time.

I won't have the time required to find and execute a solution that allows users to switch between both strategies depending on the use case and therefore I'm willing to give the assignment of this issue to some other contributor. Thanks in advance.

**Comment by jrolom** [comment]
Thanks @andresbravog - I've removed you from the assignment

**Comment by sherifnada** [comment]
I want to say we should be able to do this. Using this endpoint, the strategy for syncing a Stripe object incrementally would be:
* first, GET /events?type=<stream_object_type>.*  for example when syncing the charges stream, GET /events?types=[charge.created, charge.expired, charge.failed, ...]  (event types are listed [here](https://stripe.com/docs/api/events/types)) and get all events which were updated since the last updated_at cursor field value
* second, call GET /<stream_object_type> normally to get any new objects which were created (this is what we do today)

Alternatively maybe we just query the dedicated endpoints for the initial load, then query the events endpoint for incremental syncs from there on out 

There are some open Qs:
- I’m not sure if we need to setup webhooks to receive these events, maybe not.
- is there value in querying the dedicated resource endpoints now that we are using this? Maybe just on the initial syncs?
  - are the schemas of resources exactly the same?
- We need to handle a (niche) edge case where, if the last sync was more than 30 days ago, the /events endpoint won’t return data older than 30 days

**Comment by arseniocosta1** [comment]
I just found out about this issue, we currently migrated from another competitor tool to airbyte, and not having support for updated objects is a major block to us 😞

**Comment by sherifnada** [comment]
@arseniocosta1 this will be implemented in the next few weeks. No exact ETA but the goal is to ship it before mid-august

**Comment by arseniocosta1** [comment]
Amazing @sherifnada such good news thanks a lot ⭐

**Comment by davydov-d** [comment]
@sherifnada @lazebnyi 
I have two open questions before the PR gets approved and merged:
- Event based incremental syncs are limited up to 30 days - we need to decide how to handle this. Force a full refresh sync? Ignore it, just mentioning this restriction in the docs? Or we can hypothetically try using regular incremental sync if it is available, but it's not available on all the streams that support events.
- Event based incremental data can not be expanded unlike in common endpoints - we need to decide how to handle this. As an option, we can potentially overcome it by querying the usual endpoint by entity id. Or we can refuse supporting event increments for this kind of streams.

What do you think?
cc @oustynova

**Comment by davydov-d** [comment]
should be closed with https://github.com/airbytehq/oncall/issues/2895

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/30254
