### ISSUE TITLE
Error setting up a github connection

### ISSUE THREAD

**Issue by jlcases** [airbytehq/airbyte#15505]
## Environment

- **Airbyte version**: 0.39.41.alpha
- **OS Version / Instance**: instance in Google Cloud [debian-10-buster-v20220719]
- **Deployment**: Docker in Google Cloud
- **Source Connector and version**: Github 0.2.42
- **Destination Connector and version**: 0.2.9. Google Cloud storage
- **Step where error happened**: Set up new connection

Error: 
Failed to fetch schema. Please try again

Log file
[server-logs (1).txt](https://github.com/airbytehq/airbyte/files/9299162/server-logs.1.txt)

**Comment by sajarin** [comment]
Thanks for the issue @jlcases, can you update the github connector to the latest version and see if that fixes the issue?

**Comment by marcosmarxm** [comment]
Closed due inactivity.
