### ISSUE TITLE
Print what streams have errors in `test_additional_properties_is_true`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15525]
https://github.com/airbytehq/airbyte/blob/f540499f4320ba3719640bfa7383b0d89ddf4438/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_core.py#L322-L333

This test only output the message `When set, additionalProperties field value must be true for backward compatibility.` when some number X of streams have the additionalProperty validation error. Would be better to first map WHAT streams have error and after throw the error.

Something like: `When set, additionalProperties field value must be true for backward compatibility. Streams with error are: {"stream_a", "stream_b"}`

Without this first is very complicate to find the error in sources with a large number of stream. Second if you correct for one stream you don't have any feedback that is correct.

**Comment by evantahler** [comment]
Closing as this has been updated
