### ISSUE TITLE
Support for Kubernetes 1.24+

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15523]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1895](https://airbyte7538.zendesk.com/agent/tickets/1895)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">We’re starting planning for upgrading our kubernetes cluster to version 1.24 and realized that airbyte isn’t compatible quite yet. In k8s 1.24, bound service account tokens become required (introduced in 1.21), as the legacy service account token has been deprecated for a few versions. Airbyte is affected since the k8s library used hasn’t been upgraded with support for handling service account token expirations: <a href="https://github.com/fabric8io/kubernetes-client/issues/2112" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Support for the expiration of the token · Issue #2112 · fabric8io/kubernetes-client · GitHub</a></p>
<p dir="auto">Is there a reason that airbyte is using the fabric8io client, rather than the official k8s client? I can’t find an official doc/changelog entry for it, but I’m assuming/hoping that the official client (<a href="https://github.com/kubernetes-client/java" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">GitHub - kubernetes-client/java: Official Java client library for kubernetes</a>) has support for this feature.</p>
<p dir="auto">What is the current Airbyte roadmap for addresing this limitation? Is the current plan to wait for fabric8io to add support for this?</p>
<p dir="auto">Relevant docs:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;"><a href="https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">enhancements/README.md at master · kubernetes/enhancements · GitHub</a></li>
<li style="padding-bottom: 10px;"><a href="https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">Kubernetes Bound Service Account Tokens | Google Cloud Blog</a></li>
</ul> 

[<a href="https://discuss.airbyte.io/t/support-for-k8s-1-24/2206/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-10 at 18:46:*

<blockquote><div class="zd-comment" dir="auto">I created Github issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15523">https://github.com/airbytehq/airbyte/issues/15523</a> to implement this. Any updates I'll return to you.<br></div></blockquote>

**Comment by cpdeethree** [comment]
We are now on K8s 1.24
