### ISSUE TITLE
Delete `airbyte_scheduler`

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15522]
We haven't used `airbyte-scheduler` in a while - let's remove it!
Removal also includes removing the migration logic, as described here https://github.com/airbytehq/airbyte/issues/12823

Notes: 
- [x] Double check that there are no more helm charts that the cloud repo is using (should be OK)
- [x] Docker images (should be OK)
- [x] The following dependencies will need to be relocated:
  - [x] `DefaultJobCreator`
  - [x] `SyncJobFactory` / `DefaultSyncFactory`
  - [x] `JobPersistence` / `DefaultJobPersistence`
  - [x] `JobNotifier`
  - [x] `WebUrlHelper`
  - [x] `WorksapceHelper`
  - [x] `JobErrorReporter` / `JobErrorReportingClient` / `JobErrorReportingFactory`
  - [x] `OAuthConfigSupplier`
  - [x] `JobTracker`
  - [x] `SentryExceptionHelper`
  - [x] `Job`
  - [x] `Attempt`
  - [x] `EventRunner`
  - [x] `SynchronousSchedulerClient`
  - [x] `SynchronousJobMetadata`
  - [x] `SynchronousResponse`
  - [x] `TrackingMetadata`
- [x] The `airbyte-workers` generated path of [`io.airbyte.schedulers.models`](https://github.com/airbytehq/airbyte/blob/474642868cd8532318c9bbf7a3d394ca6c7f4669/airbyte-workers/build.gradle#L90) will need to change.
  - This is what generates the `JobRunConfig` and `IntegrationLauncherConfig` classes
- [x] Check that we don't mention `airbyte-scheduler` in docs (should be OK)
- [ ] The log-cleaner job will be moved via https://github.com/airbytehq/airbyte/issues/15218
- [ ] Old migrations (https://github.com/airbytehq/airbyte/issues/12823)

**Comment by pedroslopez** [comment]
@evantahler within airbyte-scheduler we currently have tools for tracking jobs to segment, reporting connector job errors to sentry and sending the webhook notifications (via JobTracker, JobErrorReporter and JobNotifier, respectively). I'm not sure if this issue literally means delete all of the `./airbyte-scheduler` module, but just noting that these pieces should remain functional. I think for the most part these are just being defined in airbyte-scheduler but actually used within airbyte-server and airbyte-workers, so it's probably just some moving around that needs to happen.

**Comment by evantahler** [comment]
>  We will need to re-locate some dependencies once we delete the directory


@pedroslopez thanks for the callout! The issue does imply deleting the `airbyte-scheduler` directory, so yep, we've got some modules to move out.

**Comment by colesnodgrass** [comment]
As part of this ticket, I'm making a list of every section of code within the `airbyte-scheduler` that is still is use.  The goal is to not break anything that is currently working while removing the now defunct scheduler.   Anything still in use will be moved to a more appropriate location.

**Comment by evantahler** [comment]
@davinchia can you confirm that the `airbyte-scheduler` service is already removed from Cloud?  I don't see a `cloud-scheduler` service.

**Comment by davinchia** [comment]
Confirmed this is removed from Cloud. 

If I remember correctly, we do use the remaining modules - client, models and persistence. My hunch is moving these will be split out between the airbyte-config module and the airbyte-workers module.

**Comment by davinchia** [comment]
+1 for sweeping code & reorganising!

**Comment by colesnodgrass** [comment]
[first PR is here](https://github.com/airbytehq/airbyte/pull/16758)

**Comment by colesnodgrass** [comment]
This was split into two PRs:
   - https://github.com/airbytehq/airbyte/pull/16831
   - https://github.com/airbytehq/airbyte/pull/17051
   
The approach on this ticket was changed as it was determined that copying the code and modifying it was going to be problematic as the existing code was still being modified.   Instead this issue turned into a _move existing code_ issue.  The `client` code was moved into the `airbyte-server` (as it was the only service using it) and the rest was moved to the new `airbyte-persistence` library.
