### ISSUE TITLE
Source Amazon seller partner: Add support for GET_SALES_AND_TRAFFIC_REPORT

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#15539]
## Tell us about the problem you're trying to solve
Pull report GET_SALES_AND_TRAFFIC_REPORT for Amazon seller partner

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Amazon Seller Partner: Add support for GET_SALES_AND_TRAFFIC_REPORT](https://app.harvestr.io/components/0/list/-qYVJZ8F1)

**Comment by krisjan-oldekamp** [comment]
@harshithmullapudi This report is available now
