### ISSUE TITLE
New Source: Fauna need sandbox account

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15552]
## Tell us about the problem you're trying to solve
PR adds https://github.com/airbytehq/airbyte/pull/15274 Fauna Source. Need sandbox account / credentials to test it.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cleve-fauna** [comment]
@marcosmarxm do you want Fauna to mint a sandbox account for you? Or do you want to self service this here: https://dashboard.fauna.com/accounts/register

**Comment by ycherniaiev** [comment]
@marcosmarxm seems like integration-test account for Fauna has default frmo database that can be used as 'sandbox'. Lastpass: fauna.com. Is that enough?

**Comment by grishick** [comment]
@marcosmarxm we have Fauna credentials for an account with a free plan. I think we can close this issue as done.
