### ISSUE TITLE
Sandbox account for Yandex Metrica

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15553]
## Tell us about the problem you're trying to solve
PR https://github.com/airbytehq/airbyte/pull/15061 adds Yandex Metrica and credentials are needed to run tests.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by igrankova** [comment]
@marcosmarxm 
See the LastPass creds: Yandex metrica
  The API key is generated and saved [here](https://appmetrica.yandex.ru/application/edit?appId=4268989).

**Comment by marcosmarxm** [comment]
Thanks @igrankova

**Comment by igrankova** [comment]
@ernestasga, sorry, I'll remake.

**Comment by igrankova** [comment]
@ernestasga I see that the app I've created is ok, because the docs lead to the same App creation link.

**Comment by ernestasga** [comment]
> @ernestasga I see that the app I've created is ok, because the docs lead to the same App creation link.

Sorry. I suppose auth token creation is the same then.

**Comment by igrankova** [comment]
@ernestasga my fault about the docs lynk. But during the App creation I've checked the Web Service option:
![image](https://user-images.githubusercontent.com/87977540/185375011-e8434706-75e1-4fcb-86da-0f898710b7c2.png)
So, hope everything is ok and we can use it.
