### ISSUE TITLE
Automate closing sentry incidents when github issues are closed

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#15559]
## Tell us about the problem you're trying to solve
Currently Sentry issues are left mostly left unresolved. It is a manual step to close them on top closing the github issue in oncall.

## Describe the solution you’d like
Automate so that closing Github issues automatically closes linked Sentry issues.

## Describe the alternative you’ve considered or used
Doing it manually. Having this process in oncall for a good number of weeks now has shown this is ineffective.

**Comment by pedroslopez** [comment]
I think this is a duplicate of https://github.com/airbytehq/airbyte-cloud/issues/1969 but we can close the other one

**Comment by pedroslopez** [comment]
This is done as part of https://github.com/airbytehq/airbyte-cloud/issues/2379
