### ISSUE TITLE
Source Monday.com: update in Items stream needs to use item id to request

### ISSUE THREAD

**Issue by ktstowell** [airbytehq/airbyte#15569]
## Environment
- **Airbyte version**:  0.39.42-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Monday, 0.1.4
- **Destination Connector and version**: Postgres, 0.3.21
- **Step where error happened**: Sync Job

## Current Behavior
I am hitting [Monday.com rate limits](https://api.developer.monday.com/docs/rate-limits) upon attempting to sync the `items` stream. It appears to be hit even on the first query attempt (see logs). This likely happens because this is a nested query and it is reaching Monday's _query complexity_ limits or the [generic query rate limits](https://api.developer.monday.com/docs/items-queries#additional-rate-limit).
 * The items steam has an additional rate limit applied as well, which mandates that generic queries are [only allowed every 2 minutes](https://api.developer.monday.com/docs/items-queries#additional-rate-limit), however it appears to be retrying every 30 seconds. According to the logs it looks like about every 10 minutes I get another 1000 rows.
 
Sometimes the sync completes and sometimes the job errors out completely.

## Expected Behavior
I would expect the API interaction behavior to be in accordance with the rate limit standards:
 * A single query cannot exceed `10M` complexity _units_, (based on the authentication method). In other words some queries may need to be exploded or broken out into more atomic operations.  A given user's complexity units are reset to their max value every minute.
 * The retry frequency does not exceed 120 seconds. Based on https://github.com/airbytehq/airbyte/pull/14443 I would expect this operation to be working correctly but it seems for me it does not. 

## Logs
[logs-588.txt](https://github.com/airbytehq/airbyte/files/9311608/logs-588.txt)

## Steps to Reproduce
1. Set up a Monday.com source
2. Enable the `items` stream
3. Attempt to sync.

## Are you willing to submit a PR?
Potentially! Time permitting.

----
Thank you!

**Comment by marcosmarxm** [comment]
Let me know if you need any assistance with the PR @ktstowell

**Comment by abankspdx** [comment]
@marcosmarxm Do you think this issue is just a result of the Monday API requiring a 2 minute retry cooldown for the `Items` endpoint, where the connector source looks like it's only using a 30 second `retry_factor` ? Would the solution be as easy as changing a `30` to a `120` ?

**Comment by marcosmarxm** [comment]
@abankspdx probably would the first try to see if the issue is solved.

**Comment by steelcolosus** [comment]
Hi I posted this error on slack and they point me to this issue, I don't know if it's related to the timeout but in the end I'm having a 

`   raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

followed by a lot of rate limit errors, it took almost 10h to do a sync failing at the end with this error


![image](https://user-images.githubusercontent.com/1097590/195740228-a4b50402-f1ad-4d04-907c-8fc5ec8b4eb3.png)

**Comment by marcosmarxm** [comment]
The current query executed by Airbyte:
```
{"type": "LOG", "log": {"level": "INFO", "message": "GRAPHQL QUERY: {'query': 'query { items (limit:99,page:2) { assets{id},board{id},column_values{id,value,additional_info,text,title,type},created_at,creator_id,group{id},id,name,parent_item{id},state,subscribers{id},updated_at,updates{id} } }'}"}}
```
which doesn't include the items.

**Comment by marcosmarxm** [comment]
Looks Monday is returning a 500 error. My recommendation is try to execute the query manually using curl/python to make sure it works or debug properly. Currently Monday is an alpha connector and can have this issues. I added the issue to connector backlog but priorities are GA/Beta connectors; someone from the community can try to solve the issue meanwhile.

```
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.monday.com/v2?query=query+%7B+updates+%28page%3A401%29+%7B+assets%7Bid%7D%2Cbody%2Ccreated_at%2Ccreator_id%2Cid%2Citem_id%2Creplies%7Bid%2Ccreator_id%2Ccreated_at%2Ctext_body%2Cupdated_at%2Cbody%7D%2Ctext_body%2Cupdated_at+%7D+%7D, Response Code: 500, Response Text: {"error_message":"Internal server error","status_code":500}
2022-10-14 21:28:45 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):355 - Source has no more messages, closing connection.
```

**Comment by bazarnov** [comment]
@ktstowell Could you please update us here about your current experience with the `source-monday`  version >= `0.2.0`?
Do you face the same issues described in the Issue Description? 

@marcosmarxm Could you please help to reach out to the Customer for clarification from your side also?

Thank you.

**Comment by bazarnov** [comment]
@lazebnyi I believe the issue should not be present in the latest versions (Low Code), as far as there is no response from the `reporter` (@ktstowell) it may be closed.
