### ISSUE TITLE
Remove the `name` property from HTTPRequester and other CDK components

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#15574]
## Tell us about the problem you're trying to solve
The `name` property is confusing for a developer; i'm not sure what it does or why i need to fill it out. 

## Describe the solution you’d like
Remove the `name` property from HttpRequester and other classes which don't need it

**Comment by girarda** [comment]
@brianjlai we're good to close this right?

**Comment by brianjlai** [comment]
yep!
