### ISSUE TITLE
Rename `limit_option` in `LimitPaginator` to match `page_size`

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#15575]
## Tell us about the problem you're trying to solve
I think the `limit_option` is just how you determine what to do with `page_size`. But the fact that they have different names is a bit confusing. 

## Describe the solution you’d like
Rename `limit_option` to `page_size_option` and maybe move `page_size` definition into that block? @girarda would be curious if you have opinions

**Comment by girarda** [comment]
100% agreed.
It might also make sense to remove the url_base from the paginator and let the retriever select the path from it https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/requesters/paginators/limit_paginator.py#L109-L110

**Comment by girarda** [comment]
`limit_option` and `page_token_option` should either be optional, or we should provide another paginator specific to cursor pagination that does not specify a page size
