### ISSUE TITLE
Source Stripe: Add more detail around stream permissions

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#15585]
### Tell us about the documentation you'd like us to add or update.
On Sentry we've been seeing a handful or errors where customers are configuring their Stripe connector w/ accounts that don't have enough permissions to sync certain streams. We might want to make it more clear what sets of permissions they need so they don't go through with the sync process that will end up failing. 

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.com/integrations/sources/stripe/)

**Comment by Amruta-Ranade** [comment]
@brianjlai Do we have a list of the permissions Stripe users need? Or is compiling the list part of this issue?

**Comment by brianjlai** [comment]
@Amruta-Ranade I'm so sorry I completely missed this email notification. Yes it would be compiling the list of permissions for each stream. Stripe does do a good job of documenting which API resources correlate to each permission in their docs: https://stripe.com/docs/stripe-apps/reference/permissions#object so on our side, we need to correlate the stream back to the permission type, similar to how we do it for Hubspot

**Comment by arsenlosenko** [comment]
this functionality was recently implemented and merged with this PR:
https://github.com/airbytehq/airbyte/pull/29309
[This change](https://github.com/airbytehq/airbyte/pull/29309/files#diff-bc939ec7f5dc075809864e54aca658012af002c91181af90b6b058de17bc4205R85) adds logging warnings in case if some permissions are missing. Closing this issue.
