### ISSUE TITLE
An Alert banner should be placed on the top of the screen 

### ISSUE THREAD

**Issue by matter-q** [airbytehq/airbyte#15594]
An Alert banner should be placed on the top of the screen 

Current behavior:
Alert banner placed above the content 

Expected behavior:
Should be placed on the top of the screen and do not overlap content

![image.png](https://images.zenhubusercontent.com/62beeb7e8ea880aea38f18ed/b22c0b4c-ce06-4049-8cb8-22129f273b8b)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
