### ISSUE TITLE
Rearchitect Connection Forms

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#15606]
In order to simplify the rendering of the Connection Form in both create and edit mode.

- `ConnectionForm` becomes `ConnectionFormFields`
- `RefreshSourceSchemaControl` now becomes its own component, directly implementing methods from the hook (currently, this refresh action is called at the `ReplicationView` level)
  - How the the source schema is refreshed (this should be able to be called from the button directly and then override the form's sync catalog values with the found sync catalog)
- Now that most of the logic is abstracted into the `ConnectionService`, `ReplicationView`'s main job is to render the form containing `ConnectionFormFields` and `RefreshSourceSchemaControl`
- `CreateFormContent` now renders a form containing `ConnectionFormFields` and other relevant operation field components (ie: `NormalizationField`)

See "Approved" diagram on the far right [here](https://whimsical.com/connection-creation-editing-Wa9MbAMkLiKmUCXRqEsHbJ)

Add test coverage to the changes

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
<ReplicationView>
  <Formik>
    <ConnectionName />
    <ConnectionFormFields />
    <RefreshSourceSchemaControls />
    <ConnectionEditControls />
  </ConnectionForm>
</ReplicationView>

**Comment by tealjulia** [comment]
I'm wondering if this work will help the poor performance we have with data sources that have a lot of tables.  I would think the form would be reinitializing a lot less, so it might.  If not, we should file another issue for that.  It was a really bad experience creating a connection using our integrations-test salesforce source!

**Comment by timroes** [comment]
@tealjulia I don't think this will be solved by this. The problem for this is simply the amount of DOM we create for all those tables, and we'll need to add some form of pagination (which can be client side only, since the problem is not loading the data, but rendering it), or some form of virtualization (only render, what's visible in the scroll viewport). We have this tracked via https://github.com/airbytehq/airbyte/issues/11762

**Comment by tealjulia** [comment]
Note: 
Something interesting happens on Replication View when I submit.
There is a loading bar that disables the catalog tree and presents a loading circle.
(1) the loading circle never stops (even when the connection has failed already... though maybe that's to do with it not capturing that error right)
(2) I can still edit the fields above that fold (ie: connection name, frequency, etc.) which was unexpected

**Comment by tealjulia** [comment]
Existing bug: 
Editing the connection name overrides any unsaved changes in the form

**Comment by tealjulia** [comment]
TODO: Replication View has a warning modal before a user refreshes their source schema that they will lose unsaved changes.  Create Connection should have this too.
