### ISSUE TITLE
Create ConnectionFormService and migrate Connection workflow to use it

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#15603]
Currently, there are a number of methods for getting, changing, and sending the connection object during connection creation and editing.  The goal is to get all of that logic within one Service that can be utilized from within the Connection Form.

Create a `ConnectionFormService` that returns methods for and migrate existing calls to use it.

This should be sure to include:

Creating:
- Generating the form’s initial values from specs and source schema
- After form submit, taking the form values and creating the connection (sending it to the database)

Editing:
- Generating the form’s initial values from specs, and existing connection object
- Refreshing the source schema (this should be able to be called from the button directly and then override the form’s sync catalog values with the found sync catalog)
- Updating the saved connection based on the received form values

This Service should be well tested. Depending on the result of the PR, set up a test-it days session.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
