### ISSUE TITLE
Migrate Connection update calls to use PATCH endpoint

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#15607]
Currently, we send the entire connection object including the entire syncCatalog on our Update calls.  Once we are able to use PATCH calls, we should only send the minimum needed information to identify and update the record.

This will be coordinated with the Platform team implementing the new API endpoint.  Create calls will continue to use POST.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
