### ISSUE TITLE
Destination Bigquery: normalization error file not found `/config/profiles.yaml`

### ISSUE THREAD

**Issue by gautam-ergo** [airbytehq/airbyte#15611]
## Environment
- **Airbyte version**:  0.39.42-alpha.
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: [AKS] Kubernetes on Azure
- **Source Connector and version**: Postgres 1.0.2
- **Destination Connector and version**: BigQuery 1.1.14
- **Step where error happened**:  Sync job

## Current Behavior
Normalization Failed.

## Expected Behavior
Synchronization done successfully with the correct mappings on BigQuery corresponding to the source Postgres schema.

## Logs

[Failed_Logs.txt](https://github.com/airbytehq/airbyte/files/9324704/logs-1.txt)

## Steps to Reproduce
1. setup postgres as the source
2. setup BigQuery as the destination
3. select the table stream
4. Specify Normalized tabular Data option
5. No custom transformation specified

## Background:
Running Airbyte sync without the basic normalization gets the data written to destination as one data column with a JSON blob which is not required and running the sync with Normalized tabular Data option throws up error as indicated in the screenshot below
<img width="1284" alt="Screen Shot 2022-08-10 at 6 35 01 PM" src="https://user-images.githubusercontent.com/43657587/184398642-1b84b38a-5416-415c-8527-fe3c1e660f8f.png">

<img width="1054" alt="Screen Shot 2022-08-10 at 6 49 58 PM" src="https://user-images.githubusercontent.com/43657587/184398519-e362bb08-84a6-41c6-84d9-7f51ecff7834.png">

<img width="1135" alt="Screen Shot 2022-08-10 at 6 38 54 PM" src="https://user-images.githubusercontent.com/43657587/184398713-16650682-f435-49c9-abd7-57bd2d6b9a31.png">

Is that a missing config when setting up on an AKS cluster ?
Any advice on the approach that needs to be adopted would be of great help

## Are you willing to submit a PR?
Sure !

**Comment by marcosmarxm** [comment]
Bigquery was migrated to typing-deduping method this issue isn't applicable anymore.
@evantahler fyi
