### ISSUE TITLE
OpenTelemetry: WARNING: Instrument has recorded multiple values for the same attributes

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15623]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1847](https://airbyte7538.zendesk.com/agent/tickets/1847)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><strong>Context</strong></p>
<p dir="auto">Hello!</p>
<p dir="auto">We are using Airbyte <code style="background-color: #f9f9f9; padding: 2px 5px;">0.39.42-alpha</code> with Docker Compose, and are setting it up to send metrics using OpenTelemetry, using information from the following documentation and threads:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;"><a href="https://docs.airbyte.com/operator-guides/collecting-metrics/" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://docs.airbyte.com/operator-guides/collecting-metrics/</a></li>
<li style="padding-bottom: 10px;"><a href="https://discuss.airbyte.io/t/how-can-i-monitor-airbyte-oss-on-kubernetes-using-prometheus/172" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">https://discuss.airbyte.io/t/how-can-i-monitor-airbyte-oss-on-kubernetes-using-prometheus/172</a></li>
<li style="padding-bottom: 10px;"><a href="https://discuss.airbyte.io/t/setup-datadog-monitoring/1270" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">https://discuss.airbyte.io/t/setup-datadog-monitoring/1270</a></li>
</ul>
<p dir="auto">According to the documentation, we have updated the Docker Compose stack to:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">setup the <code style="background-color: #f9f9f9; padding: 2px 5px;">airbyte-metrics-reporter</code> service for OpenTelemetry</li>
<li style="padding-bottom: 10px;">setup the <code style="background-color: #f9f9f9; padding: 2px 5px;">airbyte-worker</code> service for OpenTelemetry</li>
<li style="padding-bottom: 10px;">setup the <code style="background-color: #f9f9f9; padding: 2px 5px;">opentelemetry-collector</code> service to handle OTEL gRPC calls, and expose metrics using the Prometheus exporter</li>
</ul>
<p dir="auto">Additionally, we have setup:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Prometheus to scrape data from <code style="background-color: #f9f9f9; padding: 2px 5px;">opentelemetry-collector</code>
</li>
<li style="padding-bottom: 10px;">Grafana to display Prometheus metrics</li>
</ul>
<p dir="auto"><strong>Issue</strong></p>
<p dir="auto">When the <code style="background-color: #f9f9f9; padding: 2px 5px;">airbyte-metrics-reporter-service</code> emits metrics using the OpenTelemetry SDK, the following warning can be seen:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">airbyte-metrics-reporter  | Aug 08, 2022 3:21:29 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
airbyte-metrics-reporter  | WARNING: Instrument oldest_running_job_age_secs has recorded multiple values for the same attributes.
airbyte-metrics-reporter  | Aug 08, 2022 3:21:29 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
airbyte-metrics-reporter  | WARNING: Instrument num_running_jobs has recorded multiple values for the same attributes.
airbyte-metrics-reporter  | Aug 08, 2022 3:21:29 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
airbyte-metrics-reporter  | WARNING: Instrument oldest_pending_job_age_secs has recorded multiple values for the same attributes.
</code></pre>
<p dir="auto">When sync jobs are running, the gauges corresponding to the number of pending and running jobs do not seem to be updated accordingly, e.g. with two sync jobs running:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">$ curl --silent http://localhost:8889/metrics | rg 'num_running'

# HELP airbyte_num_running_jobs number of running jobs
# TYPE airbyte_num_running_jobs gauge
airbyte_num_running_jobs{job="metrics-reporter"} 0
</code></pre>
<p dir="auto"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/0/05d1a0c4003cabceeda85281f208ccb58cfc88fd.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto">This issue seems to be limited to gauge values, as counters are correctly incremented:</p>
<p dir="auto"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/f/f9b2326d77bb96197552dd6efd1bf2f31a550042.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto"><strong>Configuration details</strong></p>
<p dir="auto">Please find the (curated) configuration related to OpenTelemetry that we used for the different services:</p>
<hr style="background-color: #ddd; border: 1px; height: 1px;">
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">.env</code></p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">VERSION=0.39.42-alpha
PUBLISH_METRICS="true"
METRIC_CLIENT=otel
OTEL_COLLECTOR_ENDPOINT="http://otel-collector:4317"
</code></pre>
<hr style="background-color: #ddd; border: 1px; height: 1px;">
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">docker-compose.yml</code></p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">services:
worker:
environment:
- PUBLISH_METRICS=${PUBLISH_METRICS}
- METRIC_CLIENT=${METRIC_CLIENT}
- OTEL_COLLECTOR_ENDPOINT=${OTEL_COLLECTOR_ENDPOINT}

airbyte-metrics-reporter:
image: airbyte/metrics-reporter:${VERSION}
logging: *default-logging
container_name: airbyte-metrics-reporter
environment:
- CONFIG_DATABASE_PASSWORD=${CONFIG_DATABASE_PASSWORD:-}
- CONFIG_DATABASE_URL=${CONFIG_DATABASE_URL:-}
- CONFIG_DATABASE_USER=${CONFIG_DATABASE_USER:-}
- CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=${CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION:-}
- CONFIG_ROOT=${CONFIG_ROOT}
- DATABASE_PASSWORD=${DATABASE_PASSWORD}
- DATABASE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
- DATABASE_USER=${DATABASE_USER}
- PUBLISH_METRICS=${PUBLISH_METRICS}
- METRIC_CLIENT=${METRIC_CLIENT}
- OTEL_COLLECTOR_ENDPOINT=${OTEL_COLLECTOR_ENDPOINT}

otel-collector:
image: otel/opentelemetry-collector:0.57.2
command: ["--config=/etc/otel-collector-config.yaml"]
ports:
- "8888:8888"   # Prometheus metrics exposed by the collector
- "8889:8889"   # Prometheus exporter metrics
volumes:
- ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
</code></pre>
<hr style="background-color: #ddd; border: 1px; height: 1px;">
<p dir="auto"><code style="background-color: #f9f9f9; padding: 2px 5px;">otel-collector/otel-collector-config.yaml</code></p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">---
receivers:
otlp:
protocols:
grpc: {}

processors:
batch: {}

exporters:
logging: {}
prometheus:
endpoint: 0.0.0.0:8889
namespace: airbyte
send_timestamps: true
metric_expiration: 60m

extensions:
health_check:
pprof:
zpages:

service:
extensions: [health_check, pprof, zpages]
pipelines:
metrics:
receivers: [otlp]
processors: [batch]
exporters: [logging, prometheus]
</code></pre>
<p dir="auto"><strong>Attempts</strong><br>
After seeing the following issue being fixed on the OTEL SDK:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">
<a href="https://github.com/open-telemetry/opentelemetry-java/pull/4466" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://github.com/open-telemetry/opentelemetry-java/pull/4466</a> (available from <a href="https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.15.0" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.15.0</a> )</li>
</ul>
<p dir="auto">I tried bumping the version of the SDK to <code style="background-color: #f9f9f9; padding: 2px 5px;">1.16</code> using Airbyte’s <code style="background-color: #f9f9f9; padding: 2px 5px;">deps.toml</code> and rebuilding the Docker image for <code style="background-color: #f9f9f9; padding: 2px 5px;">airbyte-metrics-reporter</code>:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">$ git clone https://github.com/airbytehq/airbyte
$ cd airbyte
$ vim deps.toml    # set OTEL SDK version to 1.16.0
$ cd airbyte-metrics/reporter
$ ../../gradlew build
</code></pre>
<p dir="auto">but observed the same behaviour: warning messages, gauges stuck to <code style="background-color: #f9f9f9; padding: 2px 5px;">0</code>.</p>
<p dir="auto">The following discussion may provide better insights as to why the emission of the latest value fails for Airbyte gauges:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;"><a href="https://github.com/open-telemetry/opentelemetry-java/discussions/4233" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://github.com/open-telemetry/opentelemetry-java/discussions/4233</a></li>
</ul>
<p dir="auto">Please let me know if you need more information to reproduce the issue, I’ll also be happy to contribute fixes <img src="https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=12" title=":slight_smile:" alt=":slight_smile:" width="20" height="20"></p>
<p dir="auto">Thanks,</p>
<p dir="auto">Aurélien</p> 

[<a href="https://discuss.airbyte.io/t/opentelemetry-warning-instrument-has-recorded-multiple-values-for-the-same-attributes/2158/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-08-12 at 19:39:*

<blockquote><div class="zd-comment" dir="auto">Hey @virtualtam, we really appreciate this post. I made an issue relating to your question on Github, please add your thoughts and follow the discussion over there!&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-13 at 08:42:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a> , thanks for following up!</p>
<p dir="auto">I’ll head over to Github to continue the discussion <img src="https://emoji.discourse-cdn.com/twitter/+1.png?v=12" title=":+1:" alt=":+1:" width="20" height="20"></p>
<p dir="auto">For anyone facing similar behaviour with OpenTelemetry metrics collection, the corresponding issue is <a href="https://github.com/airbytehq/airbyte/issues/15623" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">airbytehq/airbyte#15623 - OpenTelemetry: WARNING: Instrument has recorded multiple values for the same attributes</a></p> 

 [<a href="https://discuss.airbyte.io/t/opentelemetry-warning-instrument-has-recorded-multiple-values-for-the-same-attributes/2158/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by geneyen-chu** [comment]
do we have any update of this ? it seems the number of metrics is not correct.

**Comment by id13** [comment]
Any news on this issue ? We are experiencing it as well on helm chart 0.42.2
