### ISSUE TITLE
Remove demo mode from UI

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15648]
![image.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/8f31175b-30e6-4051-950e-b16dccb4e074)

We currently have the possibility to specify a demo mode (if `window.IS_DEMO` is set to true). This mode is only used to show a banner notification that you're in the demo. We should use any of our third party tools (like google optimize) to show a banner instead.

Long term the demo instance should move to Cloud: https://github.com/airbytehq/airbyte/issues/14765

* Remove demo mode from webapp
* Remove `IS_DEMO` from build configurations and docs.
* Remove any other areas not mentioned here (search for `isDemo` and `IS_DEMO` in code)
* Verify that there are no `IS_DEMO` references in `airbyte-cloud`. Do not remove helm charts
* Coordinate with @nataliekwong to add banner notification - Deploy built version and show banner with third-party tool

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
The banner is ready to be deployed through Google Optimize whenever we get the OK here. Note we also made the following changes to systems: 
1. Added Google Tag Manager to Segment source for the demo
2. Added a trigger to Google Tag Manager to fire Google Optimize on all visits to demo.airbyte.io

Screenshot of the banner in preview (link goes to /signup): 
<img width="1489" alt="Screen Shot 2022-08-15 at 9 23 25 PM" src="https://user-images.githubusercontent.com/38087517/184702885-ea96deb1-410b-430a-bbff-a83537779c3f.png">

**Comment by johnlafleur** [comment]
I don't think the "Try it yourself" is self-explanatory as CTA, and also is visible enough...
Maybe "Try Airbyte Cloud for free with your own data", and make it more visible, purple possibly and bold?

**Comment by nataliekwong** [comment]
How's this @johnlafleur ?

<img width="1378" alt="Screen Shot 2022-08-23 at 7 31 51 PM" src="https://user-images.githubusercontent.com/38087517/186226559-15ed009a-adb6-452f-be80-0519a8041442.png">

**Comment by lmossman** [comment]
@nataliekwong I have merged the PR to remove the demo mode UI code from the app, so you can go ahead and turn on the Google Optimize banner when ready. 

We will also need to redeploy the demo app again so that the old demo banner is not shown anymore. We probably want to do that around the same time that the google optimize banner is applied, so let me know when you want to coordinate that!

**Comment by johnlafleur** [comment]
Looks good in your mockup.

*--*
*John Lafleur*
Co-Founder & COO
LinkedIn <https://www.linkedin.com/in/jeanhenrilafleur/> | Twitter
<https://twitter.com/JeanLafleur>
<http://movedata.airbyte.com>
We're hiring, come work with us! <https://boards.greenhouse.io/airbyte>

**Comment by lmossman** [comment]
The most recent version of airbyte excluding the old demo banner has been deployed to the demo instance, and the Google Optimize banner has been turned on! Going to close this out
