### ISSUE TITLE
"Discover schema" endpoint doesn't return latest schema if it was changed during the new connection creation

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#15652]
## Environment
- **Airbyte version**:  master
- **OS Version / Instance**: macOS
-  **Deployment**: local env
- **Step where error happened**: Connections / Setup new connection /

## Current Behavior
If the source schema was changed during the new connection creation, and the user will click on the "Refresh schema" button, the source schema list won't be updated actually.

https://loom.com/share/e541d34eae7d4631aaca079ccb2858af

## Expected Behavior
User should get the latest(up-to-date) source schema

**Comment by edmundito** [comment]
cc @evantahler - this is currently blocking one of our issues in frontend.

**Comment by evantahler** [comment]
@edmundito can you please link the issue?  Is it a P0/P1?

**Comment by evantahler** [comment]
Note from grooming: 

To check: 
* Do we have more than one schema refresh endpoint?  Do we use different ones when creating vs editing.  If not, maybe we aren't setting flags right when requesting the refresh.

**Comment by edmundito** [comment]
@evantahler to clarify, #5371 is currently a feature not yet available to users and is in progress. While implementing, we realized that this is not working as intended.

**Comment by lmossman** [comment]
@dizel852 have you tried setting `disable_cache` to false?

https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L2799-L2800

**Comment by dizel852** [comment]
> @dizel852 have you tried setting `disable_cache` to true?
> 
> https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L2799-L2800

Gosh, just checked - works like a charm 🤌🏻 🎉  Thanks, @lmossman !
I will close the issue since it's not relevant anymore!
