### ISSUE TITLE
Investigate removing the syncCatalog from web_backend/connections/list

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15669]
Currently the `v1/web_backend/connections/list` API returns the `syncCatalog` as part of each connection. Those can be pretty large if it's a large connection and can cause the whole request to long for a very long time, despite having a very low number of connections only.

We should investigate removing the `syncCatalog` property from the returned connections, since it seems on a first glance (needs checking) that the `syncCatalog` is never used read from this API. We seem to only use it when we get the connection from the `web_backend/connections/get` API. If that's the case we could potentially speed up the API significant by no longer reading it from the database and return it.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This is currently blocked on the update APIs requiring us to pass in the full object. The conection table allows disabling/enabling connections directly via the switch at the end. For that we'll call the update API but need to pass the full connection object back, thus we'll need to use the syncCatalog for now there.

Blocked on https://github.com/airbytehq/airbyte/issues/13698 (and us adopting to only send the required field).

**Comment by salima-airbyte** [comment]
To discuss w Platform FE team

**Comment by davinchia** [comment]
@timroes @salima-airbyte  if I understand correctly, this is already in-flight #16157 by @pmossman

**Comment by pmossman** [comment]
Correct, it's almost ready to go, just nailing down an acceptance test that is failing around partial stream resets under the new patch behavior. I can post here when the PATCH update is live. I'm also working with @krishnaglick on testing the front-end against the changes today

**Comment by timroes** [comment]
Just for clarification. Those comments are likely all related to the blocking issue #13698 not this individual one? This one (removing the syncCatalog from the list API) can be addressed after #16157 is merged and we switched over to the new API.

**Comment by pmossman** [comment]
Ah yes @timroes that's right, my last comment and Davin's last comment refer to the PATCH update connection issue (https://github.com/airbytehq/airbyte/issues/13698)

**Comment by tealjulia** [comment]
@timroes would this contradict the work proposed in #16368 ?

**Comment by timroes** [comment]
Closed via https://github.com/airbytehq/airbyte/pull/17002
