### ISSUE TITLE
adopt connector best practices for FB Marketing source

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1566]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

## Checklist
- [ ] Check connection verifies permissions upfront
- [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
- [ ] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to @sherifnada with the reason to discuss how to move forward. 
- [x] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
- [x] If API connector: implements incremental sync (where possible -- not all streams will allow this)

**Comment by eugene-kulak** [comment]
The estimation:

- [ ]  Check connection verifies permissions upfront - 30m
- [ ]  Check connection failure emits actionable error messages. - 1h
- [ ]  Check if integration tests can be run for every stream - 1h
- [ ]  If API connector: backs off on hitting rate limits (instead of just failing/exiting) - 30m

Dev Total: 2h

**Comment by sherifnada** [comment]
Thanks @eugene-kulak this looks great. Let's make sure we implement it in the right facebook connector 😜

**Comment by sherifnada** [comment]
(the new connector introduced in #1552

**Comment by eugene-kulak** [comment]
#1699 overlapped with this ticket and has all job done there
