### ISSUE TITLE
[EPIC] Cloud Acceptance Tests V2

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#15674]
## Tell us about the problem you're trying to solve
Our acceptance tests in Cloud are very perfunctory. We mainly rely on the OSS acceptance tests--this is a very weak guarantee.

## Describe the solution you’d like
* Certain OSS acceptance tests should also be run on Cloud.
* We should add extended cloud specific acceptance test suite for Cloud.

List of use cases to add and some background info:
https://docs.google.com/document/d/1jHJ9n-1eL79fzt6jAiPvXzM98A3dzhCWxZw3Wv8WGL0/edit#

**Comment by pmossman** [comment]
Revised Quarter goal:
- Basic E2E acceptance test: https://app.zenhub.com/workspace/o/airbytehq/airbyte/issues/12539
- Security E2E test: https://app.zenhub.com/workspace/o/airbytehq/airbyte/issues/15675
- Workspace Security Test: https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte/15943

**Comment by andyjih** [comment]
Closing this epic. Some issues will carry over into our Q4 epic #2981
