### ISSUE TITLE
Logos not displayed for source and destination connectors

### ISSUE THREAD

**Issue by rajaseg** [airbytehq/airbyte#15682]
Hello Team,
I installed Airbyte on Ubuntu 22.04.1 LTS. I am still having the issue of logos not being displayed for sources and destination connectors.

Please find the below images for reference.

![image](https://user-images.githubusercontent.com/633479/184790800-15f8e44e-f308-4c8d-9dd1-13cb1c653460.png)

![image](https://user-images.githubusercontent.com/633479/184790825-bf56859f-61c6-4769-97ce-5fe35aeb849f.png)

**Comment by marcosmarxm** [comment]
I'm using Airbyte 0.40+ and can see logos. Closing because isn't possible to reproduce.
![image](https://user-images.githubusercontent.com/5154322/204913928-7e2367dc-78ec-4c75-a573-216c74c13383.png)
