### ISSUE TITLE
Update page headers to align with the current designs

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#15691]
Update the design of the page heading components to align to the new designs. There are a couple of particular areas that need to be updated:

- **New Source / Destination pages** are in the progress of having a new heading type that does not exist in the webapp yet
- **All other pages** share a common component called [`<PageTitle />`](https://github.com/airbytehq/airbyte/blob/7b837180c1891fbeb47ff79593f57da303f63ee1/airbyte-webapp/src/components/PageTitle/PageTitle.tsx) (rename to `PageHeader`?) that has several combinations of how it can be laid out. Currently, the margin and heading sizes don't quite line up.

These components should be migrated to SCSS if they're still in styled components.

**Designs:** [Headers](https://www.figma.com/file/AxqFXuHo2BoTY0QY12hxm1/00_02_WEB-APP-COMPONENTS?node-id=76%3A2560), [Example](https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?node-id=1%3A3)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
