### ISSUE TITLE
Source Hubspot :  Handle 502 Bad Gateway Error better (Better Error message for customer)

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#15729]
## Current Behavior
When the Hubspot connectors gets a 502 bad gateway from the API, and it takes the full HTML it was seeing and exposed it as an error message. 

## Expected Behavior
We should parse through the error and display something more useful for the user.

## Additional Infomation
See image below for current error message:
![image.png](https://images.zenhubusercontent.com/62c49418a8561882ea2fd091/b34b6d42-44e6-4621-a5a2-198d7f1b6c41)

The UI portion of this bug was fixed in [#15633](https://github.com/airbytehq/airbyte/pull/15633)

**Comment by bazarnov** [comment]
@YowanR do we have the link to this particular workspace? I need to check for retries to take place here.

**Comment by YowanR** [comment]
Let's prioritize this in the next sprint. For now, let's focus our efforts on Q1a roadmap items, please! 🙏

**Comment by bazarnov** [comment]
@lazebnyi cc FYI

**Comment by davydov-d** [comment]
As Maxime [mentioned](https://github.com/airbytehq/airbyte/pull/23337#pullrequestreview-1309755721), we can not limit the length of the error message because the error should remain clear while working with the CLI. Parsing the HTML is also not worth the effort, besides it is rather an edge case.
