### ISSUE TITLE
[low code connectors] Stream slicers can't parse nested cursor fields.

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#15737]
At this moment, stream slicers that use a `cursor_field` that comes in the form of a list or an interpolated string that resolves to a list will fail when it reads a stream_slicer, for example here: https://github.com/airbytehq/airbyte/blob/d3cefacd69ac01cd14571447a750fbfde787fd1f/airbyte-cdk/python/airbyte_cdk/sources/declarative/stream_slicers/datetime_stream_slicer.py#L140

We don't current have any declarative connectors that use nested cursors, but the language should support this or at a minimum not hard fail w/ an `unhashable type 'list'` error.

The changes would roughly entail:

- When reading the `cursor_field`, we perform interpolation if necessary, and based on the resulting type, we either read the unnested (string) field from stream_state, or if its a list (nested cursor), then we use each nested field to read from state.
- Do this for each stream slicer that uses `cursor_field`
- Something else worth looking into is dropping `stream_cursor_field` from the schema. This is actually what identified the bug was a list of str from schema was reaching the slicer. We could just do away with this field for simplicity.

**Comment by sherifnada** [comment]
@brianjlai is this still an issue?

**Comment by brianjlai** [comment]
yep should still be relevant, but for organization I'm going to link it to our post-beta issues epic for now.

**Comment by girarda** [comment]
closing since destinations do not support nested cursor fields anymore

**Comment by girarda** [comment]
@assaadhjb the recommendation is to move the cursor field to the root of the record.
This can be done using a [AddField transformation](https://docs.airbyte.com/connector-development/connector-builder-ui/record-processing#adding-fields).
