### ISSUE TITLE
Config Airflow DB port to avoid conflict with Local Postgres instance running on 5432

### ISSUE THREAD

**Issue by Ace139** [airbytehq/airbyte#1574]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368139489457) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Hi @Ace139 thanks for submitting this issue. I'll talk to the team and figure out when we can get to this. Definitely agree that what you're asking for is important.

**Comment by evantahler** [comment]
Is this still an issue?  Airbyte now runs it's own postgres image within docker.

**Comment by cgardens** [comment]
closed as no long relevant.
