### ISSUE TITLE
Source MySQL: Test and validate support for Azure MySQL + Amazon Aurora MySQL + Amazon RDS

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#15755]
Test and validate support for Azure MySQL + Amazon Aurora MySQL

!!!!!!!!!!!!!!!!!!!TODO!!!!!!!!!!!!!!!!!!
Shutdown test DB once testing is done
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by etsybaev** [comment]
Source-mysql works fine with all of those DBs.
The only issue I had - is a connection to the newly created Azure DB.  But suddenly simple DB reboot did the trick. 
![MySQL_AmazonAurora_testConnection.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/a108780b-c24c-4d62-8796-0fc2df5ecb5a)

![MySQL_AmazonAurora_testSync.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/a7d5ea35-da0d-4a83-ae33-454ef065cd9b)

![MySQL_Azure_testConnection.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/40de5643-89d1-4282-8ad8-0853b6281fb7)

![MySQL_Azure_testSync.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/43dc636a-7759-461f-ac85-072c6f007247)

![MySql_Rds_testConnection.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/796bbdf2-4afd-4a32-94c9-a70af9449ae7)

![MySql_Rds_testSync.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/4cbd5472-e7e9-4e73-be4b-e22c344e10f2)
