### ISSUE TITLE
Add connector build status dashboard

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1577]
## Tell us about the problem you're trying to solve
I would to be able to tell at a glance from visiting a webpage see which connectors a list of all connectors with the following information: name, airbyte certified (y/n), current build status including integration tests(red/green), stability of build (whatever is normal for this, this is the lowest priority piece of information and shouldn't bother if it's going to take forever)

**Comment by jrhizor** [comment]
Available now at https://docs.airbyte.io/integrations/connector-health

**Comment by cgardens** [comment]
❤️ ❤️ ❤️ ❤️ ❤️ ❤️
