### ISSUE TITLE
Replace use of the plus (+) character in webapp buttons with actual icon

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#15792]
There are a lot of buttons in the webapp with buttons that seem to have a `+` icon next to them. For example, `+ New Connection`. However, this is just a `+` character. Instead, the buttons should show an icon.

* Replace all the instances of buttons that use + with just the name
* Consolidate terms in the i18n so that there are no duplicates (for example, are there strings with `New Connection` and `+ New Connection`?

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
