### ISSUE TITLE
Disallow unsecure SSL modes in Postgres source and destination strict encrypt connectors when SSH tunnel is not enabled

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#15808]
All traffic in and out of Airbyte Cloud has to be encrypted. Currently, users can end up with an unencrypted connection if they select "prefer" SSL mode and their destination database does not support SSL.

Also, please fix the descriptions of SSL modes so that 
1. unsupported SSL modes are not displayed in Strict Encrypt connector
2. descriptions of SSL modes for Postgres Destination connector say "destination database" instead of "source database"

![Screen Shot 2022-08-19 at 3 06 03 PM](https://user-images.githubusercontent.com/1310940/185713392-dfbf8264-2771-4b13-91c0-53223ea83ea4.png)

**Comment by tuliren** [comment]
In `strict-encrypt` connector, if SSH is turned off and SSL is disabled, fail the check.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/15808?planning-poker) with ZenHub @edgao @rodireich @ryankfu @subodh1810 @tuliren
