### ISSUE TITLE
Create and expose a read-only instance of airbyte

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1581]
## Tell us about the problem you're trying to solve
Some of our users might want to have a feel of what airbyte looks like without having to run it.

## Describe the solution you’d like
Could we expose a read-only publicly available instance of Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368205872501) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
closed by https://github.com/airbytehq/airbyte/pull/1802
