### ISSUE TITLE
Documentation split view flickering

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15819]
In a specific size the documentation sidepanel is flickering constantly between its two modes (the screen recording uses a weird framerate - in reality this flickers really fast between both of those modes):

https://user-images.githubusercontent.com/877229/185747645-472647e9-0f26-4ef8-8651-8cc4e7f6ce45.mp4

I suspect this happens because of we're checking the width in a way that does not take the scollbar into account and thus with a visible scrollbar we're getting small enough for it to show the warning modal, and as soon as that is shown the scrollbar vanishes which makes it large enough again to switch back to the documentation view, etc.

You should be able to reproduce this on a mac as well, enabling scrollbars manually:

**Firefox**: Go to about:config in your browser. Toggle the widget.gtk.overlay-scrollbars.enabled setting to false.
**Chrome**: Go to about:flags and turn the Overlay Scrollbars to "Disabled" (requires browser restart). chrome://flags/#overlay-scrollbars

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
