### ISSUE TITLE
Obtain public developer application for the Freshcaller source connector

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#15828]
## Tell us about the problem you're trying to solve
Obtain a public developer application for the Freshcaller connector like specified in https://github.com/airbytehq/airbyte/issues/6070

**Comment by igrankova** [comment]
The [Freshcaller OAuth 2](https://developers.freshcaller.com/docs/oauth/) is used to authorize an app to access resources from third-party applications. This is done by using an access token obtained from the third-party when the app is installed. The app should be registered in the third-party developer portal. 
For now we can't implement OAuth on the Freshcaller.
