### ISSUE TITLE
Build CDK incrementally in CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#15826]
## Tell us about the problem you're trying to solve
It takes too long to get feedback from CI on whether my changes to the CDK will succeed a CI build. 

The CDK is currently built as part of the `Connectors Base` Build ([example](https://github.com/airbytehq/airbyte/actions/runs/3880416454/jobs/6627042024)). But that build is not nearly as incremental as it can be i.e: it builds a bunch of stuff which are unrelated even if my PR only changes the CDK and nothing else. 

## Describe the solution you’d like
I would like the connectors-base build to be incremental i.e: `connectors-base` should only build the things which changed. In this situation. 

## Implementation Suggestions
1. Understand what is being built as part of connectors base (the modules included are listed [here](https://github.com/airbytehq/airbyte/blob/master/settings.gradle#L82) and [here](https://github.com/airbytehq/airbyte/blob/master/settings.gradle#L124))
2. Either make that build chain incremental (80/20 approach is fine here, doesn't have to be perfect, let's focus on practical improvements), or split it so that we have a separate build just for Extensibility related work (e.g a build chain which contains only CDK, SAT, connector builder, etc.)

**Comment by sherifnada** [comment]
grooming notes: 
- This already happens as part of connectors base. An issue with it is it's too slow but still, technically this works. 
   -  change this issue to optimize connector base build so it doesn't take 20-30 mins to get CI result of changing CDK 
- would like to run connector test against tentative CDK changes
  - we could install the cdk directly from git
  - it seems like the way to do this would be to build the `.venv` from locally reading the CDK version
  - create a DEV version of the CDK. Change connector docker images to read an env var which tells it whether to use the DEV version of the CDK to build the connector
  - is there such a thing as running a local PyPi so that the connector can "pretend" like it's pulling 
  - could we mount the airbyte-cdk and maybe SAT to `.venv/site-packages` or something so `pip install` doesn't install a new version of the CDK? We could also use a dedicated `dev` Docker image which inherits the prod one

next steps: create issue for second point, and rephrase this issue to be more about optimizing connectors base rather than changing the CDK test pipeline entirely

**Comment by girarda** [comment]
grooming notes specific to :
* is there a way to automatically install the published cdk if a local version does not exist?
* is there a way to avoid needing to modify the docker file (eg use symlink to the connector's module)
* need to look into how to follow symlinks

**Comment by girarda** [comment]
closing because too much has changed in our CI in the last year. we can open new issues as needed
