### ISSUE TITLE
E2E Testing Tool: test MySQL source on MariaDB

### ISSUE THREAD

**Issue by kimerinn** [airbytehq/airbyte#15836]
Prepare following test scenario to be used with e2e-testing-tool:

1) Create MySQL source around mariadb database
2) Create Postgres destination
3) Create connection using source and destination from steps 1-2
4) Perform sync on newly created destination

**Comment by grishick** [comment]
@kimerinn please add the description of test scenarios to the issue.

**Comment by grishick** [comment]
@kimerinn were you able to run the tests?
