### ISSUE TITLE
🪟 🐛 Broken spinner position on job logs loading

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#15845]
Broken spinner position on logs loading

## Current Behavior
<img width="940" alt="Screenshot at Aug 22 16-58-57" src="https://user-images.githubusercontent.com/20929344/185939579-9dd87a38-ee85-47e4-aede-851da651a514.png">

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
