### ISSUE TITLE
Segment `page` calls not firing on Cloud

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15849]
Currently the segment calls for `page` (https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/hooks/services/Analytics/useTrackPageAnalytics.tsx#L15) on Cloud are not firing, since the relevant code is checking for a page URL and only firing if a page name is found, which currently doesn't ever work on Cloud due to workspace ids in the URL.

Talking to Natalie, we should change those human readable page names into a more "id" like format, e.g. `Connection.NewPage`, instead of human readable ones, when fixing this issue. Also we should make sure, that unknown URLs will still trigger a page call. We could for them just use an ID `UnknownPage`, since segment already tracks the URL as an additional parameter anyway.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
