### ISSUE TITLE
Error on time upgrade of some source connectors

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#15850]
## Environment
- **Airbyte version**:  0.40.0-alpha
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker
- **Source Connector and version**: Sendgrid 0.2.10 / Sentry 0.1.3 / Greenhouse 0.2.8
- **Step where error happened**: On time upgrade source connectors

## Current Behavior
Already for a long time we are not able to upgrade these connectors.
getting error: "Sorry. Something went wrong..."
True say, we are not using these connectors but anyway it looks like some issue exists there.

**Comment by luancaarvalho** [comment]
I'm facing theses errors too, but at kubernetes helm deploy and **0.39.9-alpha version** . 
These are the unique logs showed to me:

> Using existing AIRBYTE_ENTRYPOINT: python /airbyte/integration_code/main.py
> Waiting on CHILD_PID 8
> PARENT_PID: 1
> EXIT_STATUS: 1

**Comment by animer3009** [comment]
Looks like solved in new upgrade.

**Comment by luancaarvalho** [comment]
@animer3009 What upgrade, please ?

**Comment by animer3009** [comment]
@luancaarvalho 
I mean Airbyte's last update.
I did git pull.
The Last version has no issue any more.

**Comment by luancaarvalho** [comment]
0.40.1, right ?

**Comment by animer3009** [comment]
@luancaarvalho Yep.
Just review this before:
https://github.com/airbytehq/airbyte/issues/15915

**Comment by luancaarvalho** [comment]
Ok, thank you !
