### ISSUE TITLE
Source Outreach: Request for more streams

### ISSUE THREAD

**Issue by FransDel** [airbytehq/airbyte#15873]
## Tell us about the problem you're trying to solve
For a Data Warehouse project we need to access outreach data. Currently in the outreach source the only tables created are: 
* prospects
* sequence_states 
* sequences 
Ideally we want to also fetch: 
* mailboxes
* accounts
* maillings
* opportunities
* personas
* stages

Also, in addition to the attributes that are already pulled in the tables, we need the relationships between tables to be present as well. 

## Describe the solution you’d like
1. Ability to pull the data from the following endpoints in outreach: 
* mailboxes
* accounts
* maillings
* opportunities
* personas
* stages

2. Relationship data available in addition to attribute data pulled (concerns also the existing endpoints pulled). 

## Describe the alternative you’ve considered or used
Custom code in our orchestrator. 

## Additional context
Right now prospects, sequences and sequence states aren't related between each other in the data pulled. Only the attributes of the API response are used. The idea is also to add relationship data. Using the IDs of the different objects sent back.

## Are you willing to submit a PR?
Yes, I've already started part of the work locally at least concerning adding the additional tables

**Comment by FransDel** [comment]
Related PR: https://github.com/airbytehq/airbyte/pull/17385

**Comment by topefolorunso** [comment]
Resolved in https://github.com/airbytehq/airbyte/pull/17385 @justinbchau
