### ISSUE TITLE
Destination Postgres: Normalization of Local JSON fails

### ISSUE THREAD

**Issue by 3LexW** [airbytehq/airbyte#15871]
## Environment
- **Airbyte version**:  0.40.1
- **OS Version / Instance**: RHEL7.9
- **Deployment**: Docker
- **Source Connector and version**: File 0.2.19
- **Destination Connector and version**: Postgres 0.3.22
- **Step where error happened**: Normalization

## Current Behavior
When I was trying to convert data from JSON file to postgreSQL, the normalization failed and thus only the raw data are imported, without normalization

## Expected Behavior
Normalization should work normally

## Logs
[logs-37.txt](https://github.com/airbytehq/airbyte/files/9400117/logs-37.txt)

## Steps to Reproduce
1. Download source files from [Mockaroo](https://www.mockaroo.com/), use the default schema configuration, and export as JSON (array, include null value are on)
2. Place the json file to folder `/tmp/airbyte_local` if no change in settings
3. Set up connection between file and postgreSQL, the file's dataset name is set to `user_info`
4. Try connection, you should receive the following error message
`KeyError: "'json_schema'.'properties' are not defined for stream user_info"`

## Are you willing to submit a PR?

No

**Comment by marcosmarxm** [comment]
Normalization was migrated to typing-deduping method doesn't use normalization anymore.
