### ISSUE TITLE
Update Metric Reporter Querying SQL to include information about data plane

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#15898]
When reporting metrics from metric reporter, currently it's running many queries against our database and report it directly to datadog.

A lot of job metrics would provide better information if we could group them by data plane - such as num_of_pending_jobs, num_of_running_jobs etc. Could explore if we can just add a tag when reporting the metrics rather than reporting multiple metrics, nevertheless changing the query is necessary.

Proposed metrics to be updated are:

- oldestJobAgeSecs
- oldestPendingJobAgeSecs
- numOfJobsNotRunningOnSchedule
- numberOfPendingJobs
- numberOfRunningJobs

Priority: Not high because oncall/dev person can still run queries and get result in dbeaver if they are curious, and this is supporting outcome for Multi cloud Phase 3 and we are not immediately blocked for onboarding customer on aws.

**Comment by pmossman** [comment]
Refining notes:
- Short term idea: Store which task queue a connection was routed to in the 'attempt' table, so that we're able to query for it and preserve a history of where an attempt was routed.
- Data plane workers don't have a database connection, so they can't run any metrics queries themselves, but Control Plane workers can query and distinguish between different data planes as long as we store that information.

**Comment by pmossman** [comment]
Relates to https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte-cloud/2878

Circle back here once we know where our pain points are around Data Plane observability with real customers

**Comment by pmossman** [comment]
Refining notes:
 - All metrics that we push come from the Control Plane, regardless of where the sync actually ran.
 - Metrics Reporter and the Job status activity are the two key places we push sync metrics. Metrics Reporter don't have any information about where the job ran
   - Once we store connection-level geography in the database, we can update the MetricsReporter to incorporate that in its query
   - Alternative idea: store which task queue an attempt ran on in the attempt metadata in the database
        - Benefit of this is that we get Job State reporting by data plane here: https://app.datadoghq.com/dashboard/e76-ez9-zff/gke-apps-dashboard?from_ts=1664903120426&to_ts=1664904020426&live=false&tile_focus=8559589872314732, seems worth doing

Scope of this ticket: 
 - Figure out how to store the task queue that the attempt ran on in the attempts database table
 - Update MetricsReporter and Worker activity logic to include the task queue in the metrics that we push
 - Create a 'AWS Paris Jobs State' group in DataDog dashboard (like https://app.datadoghq.com/dashboard/e76-ez9-zff/gke-apps-dashboard?from_ts=1664903486781&to_ts=1664904386781&live=false&tile_focus=8559589872314732 but for AWS Paris specifically)

**Comment by xiaohansong** [comment]
Edit dashboard to be like this: 
![Screen Shot 2022-11-02 at 3 26 52 PM](https://user-images.githubusercontent.com/5505742/199614435-26e90bb5-9cca-4b37-8e0d-66707e95e134.png)
