### ISSUE TITLE
Ensure that state is persisted even when connectors crash

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15907]
Part of the [Connector Checkpointing Epic](https://docs.google.com/document/d/1n9grVSwCmRPiQc6JD53z4mBX9VwY_WXuR3daU5kNVlY/edit?pli=1#)

A checkpointing connection is one that is defined to be able to be resumed upon failure without loosing much data.  To that end, we need to ensure that even if a source or destination connector crashes mid-sync, that the platform persist the most recent state data it has received echoed from the destination.  We can assert this with additional tests in the codebase. 

### Test Case 1: The source crashes

* The destination continues to store all the records it got before the source crashed
* The destination will eventually echo the most recent state message it received from the source
* The most recent state message echoed from the destination will be persisted

| Source Emits | Destination Emits | Platform Stores |
|--------------|-------------------|-----------------|
| Records...   |                   |                 |
| State A      |                   |                 |
|              | State A           |                 |
| Records...   |                   |                 |
| State B      |                   |                 |
|              | State B           |                 |
| Crash!       |                   |                 |
|              |                   | State B         |

### Test Case 2: The destination crashes

* Assuming the destination echoed at least one state message, the most recent state message echoed from the destination will be persisted

| Source Emits | Destination Emits | Platform Stores |
|--------------|-------------------|-----------------|
| Records...   |                   |                 |
| State A      |                   |                 |
|              | State A           |                 |
| Records...   |                   |                 |
| State B      |                   |                 |
|              | Crash!            |                 |
|              |                   | State A         |

### Make it work

And then finally, update the platform to store the latest state, even in the event of a connector's crash

**Comment by gosusnp** [comment]
Adding bit more context here, about the test 2.

Our current [implementation](https://github.com/airbytehq/airbyte/blob/f8ebd4f60c3957a409a9f72b568b3ea55b74ad6a/airbyte-workers/src/main/java/io/airbyte/workers/temporal/sync/SyncWorkflowImpl.java#L47) is running sequentially the `replicationActivity` followed by `persistActivity`. It means that in case of crash, depending on the error that is thrown, there is a possibility that the workflow would be aborted and we would not have persisted any states.

**Comment by awillborn** [comment]
We are tracking the most recently received destination state message in the AirbyteMessageTracker (`destinationOutputState`)

If either a source or destination connector fails during a sync, we set that destination state on the StandardSyncOutput, and that is what is saved later. 

We have both an integration test and unit tests to validate this behavior.

**Comment by alovew** [comment]
We are tracking the most recently received destination state message in the AirbyteMessageTracker (destinationOutputState)

If either a source or destination connector fails during a sync, we set that destination state on the StandardSyncOutput, and that is what is saved later.

We have both an integration test and unit tests to validate this behavior.
