### ISSUE TITLE
Add a note about using primary/master DB host for Postgres CDC 

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#15913]
### Tell us about the documentation you'd like us to add or update.
Debezium documentation states that it can work only only with primary servers and not with hot or warm standby replicas. We should add a note about that to our Postgres CDC documentation to help users avoid pointing their connector configuration to replicas and wondering why it doesn't work.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant Airbyte Docs page](https://docs.airbyte.com/integrations/sources/postgres)
- [Relevant Debezium docs](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#debezium-connector-for-postgresql)
- [Oncall issue that was resolved by pointing connection to primary server](https://github.com/airbytehq/oncall/issues/401#issuecomment-1224239390)

**Comment by tyagi-data-wizard** [comment]
Hello @grishick ,
I am a newbie to open source, just did the changes in postgres.md and created a PR.
[pr-24175](https://github.com/airbytehq/airbyte/pull/24175),
Please let me know, if any changes are required.

**Comment by tyagi-data-wizard** [comment]
Thanks @grishick  for merging my PR, it is my very first open source contribution!
Will try to contribute to much major issues in future.

Hope this issue can be assigned and closed, if the requirement got completed
