### ISSUE TITLE
Dockerhub airbyte/scheduler not upgraded

### ISSUE THREAD

**Issue by ramonvermeulen** [airbytehq/airbyte#15918]
For quite a while the airbyte/scheduler image on dockerhub is not upgraded to the latest version (`0.40.2`)

https://hub.docker.com/r/airbyte/scheduler/tags?page=1

It is still on `0.39.11-aplha`

Is there a specific reason for this? Is the deployment of the scheduler container not needed anymore in 0.40.X > ?
Because then I'll remove it out of my helm deployment.

**Comment by evantahler** [comment]
Yep! That's correct - Airbyte no longer uses the `airbyte/scheduler` container, as we've moved our scheduling logic into `airbyte/temporal` instead.
