### ISSUE TITLE
Sync duration issue in case of multiple connections

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#15927]
## Environment
- **Airbyte version**:  0.40.1
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker-compose
- **Source Connector and version**: Amazon Ads 0.1.16
- **Destination Connector and version**: BigQuery 1.1.15

I have multiple connections (about 683) and connectors.
One connector is used in 17 connections. The destination is the same for all.
Issue I have is that, when connections start to sync at the same time, the process is very slow.
I am monitoring VM resources. True say Airbyte uses a lot of cpu resources compared to ram usage, but VM has enough.
In the picture you can compare execution time, in case when a connection executes at the same time with other ones and in cases when it runs single.

![Screenshot at Aug 24 11-31-34](https://user-images.githubusercontent.com/5002551/186463465-7d268b4b-7a2b-4c5e-a1ed-36e20180c2da.png)

**Comment by animer3009** [comment]
In most connectors I see this:
`2022-08-25 03:40:27 INFO i.a.w.t.TemporalAttemptExecution(get):131 - Stopping cancellation check scheduling...`
And looks like they are waiting something.

**Comment by harshithmullapudi** [comment]
Could you share the logs for both the syncs here?

**Comment by animer3009** [comment]
@harshithmullapudi For example you can see this:
[logs-594.txt](https://github.com/airbytehq/airbyte/files/9425049/logs-594.txt)
About 3 hour it was waiting something...

**Comment by animer3009** [comment]
p.s. Web app very slow loading my connection list after refresh...

**Comment by animer3009** [comment]
@harshithmullapudi any idea?

**Comment by harshithmullapudi** [comment]
yeah looks like in the log it was waiting for the resource (sync container). Does this happen regularly? I mean does it take longer time generally?

**Comment by animer3009** [comment]
@harshithmullapudi yep, this happens regularly when a lot of connections start to sync at same time.
If I sync manually one by one, it executes in a few seconds...

**Comment by animer3009** [comment]
P.s is there any limit, how many source/destination containers can be created at same time?

**Comment by animer3009** [comment]
I see it is limited like 5 source and 5 destination container.
How to solve this?

**Comment by natalyjazzviolin** [comment]
Hey @animer3009 the team was out for an off-site meeting last week, I'm working on this and hope to have some info for you soon!

**Comment by natalyjazzviolin** [comment]
@animer3009 the limit can be set in this environmental variable: `MAX_SYNC_WORKERS`

**Comment by animer3009** [comment]
@natalyjazzviolin looks like it helped. Thank you
