### ISSUE TITLE
Add utm_medium to airbyte_ui_cloud.user.create

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#15923]
# Current Behavior
We currently collect the UTM tracking parameters for a user on signup for utm_source, utm_content, utm_term, and utm_campaign.

# Expected Behavior
We also utilize utm_medium to track which channel (like email, cpc, referral) the lead comes from. Add this to the user.create call so that we can populate it in downstream systems.

**Comment by timroes** [comment]
This is strange. We have no hard filter for specific utm parameters, but we're collecting all query parameters that begin with `utm_`. So we'd first need to test why they are not tracked at all (with some reliable data).

**Comment by nataliekwong** [comment]
Would it be helpful to share an example URL?  I see these collected in Google Analytics so I'm inferring from the data there that we are indeed sending a utm_medium. 

GA report:

<img width="1124" alt="Screen Shot 2022-09-05 at 4 24 50 PM" src="https://user-images.githubusercontent.com/38087517/188471024-e581bbd0-9e81-41db-8588-36c42168d59f.png">

**Comment by nataliekwong** [comment]
select min(sent_at) from airbyte_ui_cloud.airbyte_ui_user_create where utm_medium is not null

**Comment by timroes** [comment]
We debugged this, this isn't happening (anymore). Thus closing.
