### ISSUE TITLE
Problems syncing a big table into snowflake

### ISSUE THREAD

**Issue by hudsondba** [airbytehq/airbyte#1592]
## Current Behavior

I'm trying to move a table with 2M of rows from Postgres to Snowflake but the process never ends.

The setup is using an EC2 instance (r5.xlarge) with amazon Linux.

Part of the log:

```
2021-01-09` 19:25:59 INFO (/tmp/workspace/16/1) LineGobbler(voidCall):69 - 2021-01-09 19:25:59 [32mINFO[m i.a.i.d.s.SnowflakeDestination$DestinationImpl(insertBufferedRecords):164 - {} - max size of batch: 500

Process is taking too long to finish. Killing it
Sync worker failed.
io.airbyte.workers.WorkerException: target process wasn't successful
```

## Steps to Reproduce
Try to replicate an fake table with more than 2M rows from postgres to snowflake

## Severity of the bug for you
Medium

**Comment by cgardens** [comment]
@hudsondba submitted this pr for a fix https://github.com/airbytehq/airbyte/pull/1593. I'm suggesting the following for a long term solution https://github.com/airbytehq/airbyte/issues/1600. Would suggest that we close this issue as the immediate issue described has been fixed. @hudsondba what do you think?

**Comment by hudsondba** [comment]
@cgardens Sounds good!! Thanks for letting me know :)
