### ISSUE TITLE
Create a monitor to check if a job has running unusually long

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#15930]
For now, the idea is to compare the historic sync jobs (last X successful runs) and see if the current run time is significant longer than them (X times more than the max run time of last several successful runs). If so we should report this job to a dashboard so oncall could take a look.

**Comment by pmossman** [comment]
Refining notes:
- For a given connection, look at previous job runtimes, compare to current runtime, show a dashboard that lists jobs that are running significantly longer than the historical runtime.
- Sql query from MetricReporter that can push the needed metric, performance should be similar to the missed-schedule query that we already have
  - Should measure performance hit of the query, if it's bad, explore alternatives
- Alternative: Pushing all job runtimes to an external tool that we could set up anomaly detection? 
  - Probably very expensive to do this in DataDog, plus OSS users don't get it for free.

Start with the writing our own query, and if it ends up being much worse than we expect, we can pivot to something else.

Also doesn't need to be query necessarily, the MetricsReporter is java so we can use any java libraries we want if there's a good tool out there.

**Comment by terencecho** [comment]
example of a similar query: https://github.com/airbytehq/airbyte/pull/15740/files

**Comment by pmossman** [comment]
If a job is running for the first time with no historical data, might be a good idea to have a "first-run threshold" of 6 hours or something. 

Let's start somewhere, and then tune once we see how it goes

**Comment by xiaohansong** [comment]
Query will be like:

```


select
	scope as workspace_id,
	avg(extract(epoch from age(updated_at, created_at))) as avg_run_sec,
	extract(epoch from age(max(updated_at), max(created_at))) as latest_run_sec
from
	jobs
where
	updated_at >= NOW() - interval '144 HOUR'
	and (jobs.status = 'failed'
		or jobs.status = 'succeeded'
		or jobs.status = 'cancelled')
group by
	1
having
	count(1) > 4
	and extract(epoch from age(max(updated_at), max(created_at))) > greatest(avg(extract(epoch from age(updated_at, created_at))) * 2, avg(extract(epoch from age(updated_at, created_at))) + 900)
```

**Comment by xiaohansong** [comment]
Added into datadog dashboard.
