### ISSUE TITLE
Source Google Analytics: add ability to sync multiple View IDs per connection

### ISSUE THREAD

**Issue by NAjustin** [airbytehq/airbyte#15936]
## Tell us about the problem you're trying to solve
The Google Analytics (Universal Analytics/GA3) source only currently supports a single View ID being provided despite many analytics use cases involving multiple sites/views. It's possible for both Service Accounts and oAuth clients to have access to multiple accounts/properties/views.

This means that for custom reports, you must copy the same logic repeatedly across connectors—and then manage any changes or new custom reports you need over time. This isn't DRY (Don't Repeat Yourself) and also results in many different tables that you must then re-combine in your data modeling.

Most other data integration platforms allow the provision of multiple view IDs in the same connector, since often a single web property or client may have several views that you would want to sync.

This is particularly useful to larger organizations and agencies who may have hundreds or thousands of views. 

## Describe the solution you’d like
Allow the connector to accept multiple View IDs (either in the form of a comma-separated list or by providing an intuitive selection interface). This would in turn facilitate the selected reports being generated for an arbitrary number of views within the same output tables. There's no risk to data integrity, as the `view_id` is already provided in every report's schema. (and clustering by this value may could provide additional performance benefit)

While the API only syncs one view at a time, the list of View IDs could just be iterated over during the sync process, which is how other platforms like Fivetran (and IIRC Stitch) handle their syncs.

## Describe the alternative you’ve considered or used
Duplicating connectors, custom report logic, and secondary data modeling to combine the disparate destination tables.

## Additional context
This would be similar to how Airbyte already extends the custom report syntax by wrapping it in a JSON array and then iterating it. So there's strong precedent for this type of extension for the same reasons/benefits, and the change would enhance functionality while only minimally impacting the existing codebase and tests.

## Are you willing to submit a PR?
Possibly (time is a bit tight right now, but looking to start contributing too)

**Comment by davydov-d** [comment]
Closing this issue since the Google Analytics v4 is going to be deprecated soon in favour of Google Analytics Data API.
