### ISSUE TITLE
Acceptance tests: User Invite Flow

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#15942]
Basic cloud tests: User Invite Flow

For user invite flow, a Firebase link is generated on the airbyte server and emailed to the invited user. For testing, might be hard to actually complete the entire flow. Probably don't want to inspect the email copy in the test, since we might be changing it frequently. But maybe we can inspect the generated link and see if there's something in it that we can verify.

Two invite flows to test: 1) user already exists in Airbyte, we just grant them access to the workspace and email them that they now have access. 2) user doesn't exist yet, so we create a user and send them the link to sign up.

Estimate for invite: 5 (there's uncertainty with how we'll generate and test the email itself)

**Comment by pmossman** [comment]
Refining notes:
- One idea for testing against a real instance of Firebase: use staging? 
- Whatever we decide for Firebase should also be used for other external integrations (Stripe, Orb, etc)

- Pieces of the flow to test:
  - Firebase (generating a valid user and sign-in link)
    - will need to somehow create a unique user on every run of the test, not sure how bad it is to constantly add new users, might want some sort of cleanup step (maybe an @AfterAll step that cleans out whatever users were added?)
  - Sendgrid (delivering an email containing the link)
  - Airbyte Cloud (once the link is clicked, a user is successfully signed in)
  - We're not sure how to test all of this with just Java code, probably will require some research/experimentation

**Comment by davinchia** [comment]
This is done!
