### ISSUE TITLE
Move Archives helper class to its own module

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1594]
## Tell us about the problem you're trying to solve
We want to be a little careful about adding dependencies to airbyte-commons. airbyte-commons is depended on by every airbyte java module. that means now all of our java modules will include commons-compress even though it is irrelevant for most of them.

## Describe the solution you’d like
Can we isolate the archiving code into a separate module instead?

In addition, we need unit testing of compressing/uncompressing the archives 

## Additional context
We should also add a test case for the following security vulnerability:
https://nakedsecurity.sophos.com/2018/06/06/the-zip-slip-vulnerability-what-you-need-to-know/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368140649616) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
archive helper was removed.
