### ISSUE TITLE
CDK Installation Errror q

### ISSUE THREAD

**Issue by demirbey05** [airbytehq/airbyte#15954]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

When I execute the `pip install -r requirements.txt` for source connector, pip gives an error : 
`ERROR: Could not find a version that satisfies the requirement airbyte-cdk~=0.1.56 `

**Comment by marcosmarxm** [comment]
Please update the issue title and description give complete information and steps to reproduce. I'm closing until there.
