### ISSUE TITLE
Move assets from public/ into appropriate folders

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#15956]
We should move all assets that don't need to be in` public/` closer to the appropriate components/pages using them.

* Import of svg/images would need to happen at the top level (e.g. `import octavia from './octavia.svg'`)
* SCSS images can be imported with the `url()` function relative to the location of the .scss file.
* No need to convert SVG files to react
* ~30 png/svgs need to be moved around to the right place
* Octavia images should be grouped together for an easier way to see what's available and to update in bulk later.
* The only images images left in `public/` are referenced directly from the HTML (e.g. the favicons).
* Should be deployed to a cloud dev instance to verify build loads images correctly

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
