### ISSUE TITLE
E2E Testing Tool : create service account for connection to secret manager 

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#15953]
For further work, the `E2E-testing-tool` application needs to connect to `Google Secret Manager` and read the necessary secrets for connection to differed environments. To connect the application to `Google Secret Manager`, you need to create a new `Service Account` and add its credentials to the application.

**Comment by grishick** [comment]
@supertopher or @davinchia do you know who can help with this?

**Comment by supertopher** [comment]
We can add this to the board.  What timeline are you looking for completion?  I believe tomorrow EOD isn't crazy, but it might be more like monday EOD.

**Comment by supertopher** [comment]
it's linked right above this, but for visibility https://github.com/airbytehq/airbyte-cloud/issues/2496 tracks this for infra
