### ISSUE TITLE
Being able to schedule first sync at a precise hour and minutes

### ISSUE THREAD

**Issue by data-evs** [airbytehq/airbyte#15966]
## Tell us about the problem you're trying to solve
I need to be able to schedule synchonizations at a precise hour and minutes.
Why : to spread all synchronizations over the whole day, in order to avoid overloads.

## Describe the solution you’d like
Add a new optional input field that would be located with "replication frequency". The user would enter there the start hour and minutes of the first sync.

## Describe the alternative you’ve considered or used
I force synchronization of my connections over the whole day in order to simulate the spreading.

## Additional context
The fact is that I add to restart the server Airbyte is installed on. After that, all sync. launched at the same time. As a result, there were a CPU / RAM overload three days later.

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/2170
