### ISSUE TITLE
🐛 Source-Snowflake: Sync times out in v0.1.19 

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#15965]
## Environment
- **Airbyte version**:  0.40.2
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker-compose
- **Source Connector and version**: Snowflake 0.1.19
- **Destination Connector and version**: BigQuery 1.1.15
- **Destination Connector and version**: MySQL 0.1.20

Getting errors:
`2022-08-25 13:59:06 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - The supplied date/time format type does not match the specification, expected: date`
`2022-08-25 13:59:20 source > 2022-08-25 13:59:20 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.`
`1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as `NAME``

> 	1 of 3 ERROR creating table model airbyte_datahawk.SEO_KEYWORD_VOLUME................................................... [ERROR in 5.09s]
> 	Database Error in model SEO_KEYWORD_VOLUME (models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql)
> 	  Invalid date: '2020-09-01T00:00:00Z'
> 	  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql,retryable=<null>,timestamp=1661435996993], io.airbyte.config.FailureReason@219ddad[failureOrigin=normalization,failureType=system_error,internalMessage=1 of 3 ERROR creating table model airbyte_datahawk.SEO_KEYWORD_VOLUME................................................... [ERROR in 5.09s]
> 	Database Error in model SEO_KEYWORD_VOLUME (models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql)
> 	  Invalid date: '2020-09-01T00:00:00Z'
> 	  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql
> 	1 of 3 ERROR creating table model airbyte_datahawk.SEO_KEYWORD_VOLUME................................................... [ERROR in 5.09s]
> 	Database Error in model SEO_KEYWORD_VOLUME (models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql)
> 	  Invalid date: '2020-09-01T00:00:00Z'
> 	  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@24ceef7[additionalProperties={attemptNumber=2, jobId=1547, from_trace_message=true}],stacktrace=1 of 3 ERROR creating table model airbyte_datahawk.SEO_KEYWORD_VOLUME................................................... [ERROR in 5.09s]
> 	Database Error in model SEO_KEYWORD_VOLUME (models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql)
> 	  Invalid date: '2020-09-01T00:00:00Z'
> 	  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql
> 	1 of 3 ERROR creating table model airbyte_datahawk.SEO_KEYWORD_VOLUME................................................... [ERROR in 5.09s]
> 	Database Error in model SEO_KEYWORD_VOLUME (models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql)
> 	  Invalid date: '2020-09-01T00:00:00Z'
> 	  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_datahawk/SEO_KEYWORD_VOLUME.sql,retryable=<null>,timestamp=1661435996993]]]

Full log is attached
[logs-1547.txt](https://github.com/airbytehq/airbyte/files/9425521/logs-1547.txt)
[logs-1548.txt](https://github.com/airbytehq/airbyte/files/9425522/logs-1548.txt)

**Comment by natalyjazzviolin** [comment]
As the errors state, this is a syntax issue, not an issue with Airbyte:

```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as `MONTH`,
```

```
1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RETURNING CHAR) as `NAME`,
```

If you like to debug this further, please make a post in the forum! Closing this as it's not an Airbyte bug.

**Comment by animer3009** [comment]
@natalyjazzviolin
It is not just MySQL issue.
It has issue on case BigQuery as well.

**Comment by animer3009** [comment]
@natalyjazzviolin 

> Additional Failure Information: java.lang.RuntimeException: java.lang.RuntimeException: net.snowflake.client.jdbc.SnowflakeSQLException: Warehouse 'WH_DATAHAWK_SHARE_12211_947678654' cannot be resumed because resource monitor '{1}' has exceeded its quota.
