### ISSUE TITLE
Documentation: Rewrite the Airbyte GCP deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#15969]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte GCP deployment guide](https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by PragatiVerma18** [comment]
I want to work on this, can you please assign it to me?

**Comment by PragatiVerma18** [comment]
Hey @Amruta-Ranade, here's the first [draft](https://docs.google.com/document/d/1pG2dQFNlk9k3SpBcB4MeiKDwR3ASacu5SnSbKhnAfVI/edit?usp=sharing).

**Comment by Amruta-Ranade** [comment]
Feel free to open a PR and assign it to me for review :)

**Comment by PragatiVerma18** [comment]
Here's the PR [#18286](https://github.com/airbytehq/airbyte/pull/18286). Please review.
