### ISSUE TITLE
Liveness check for connectors

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1600]
## Tell us about the problem you're trying to solve
* We do not have a good way to tell if a source / destination is stalled or not.
* We cancel writing to a destination if it takes more than 10 minutes longer than it took to read data. This is a bad assumption to make. Prefer checking that the destination is making progress, and if it is, keep going.

## Describe the solution you’d like
* Allow periodically checking that sources and destinations are still making progress and if they are don't kill the sync.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368206201587) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
I don't think this is something prioritized any time soon. Closing as won't do. @cgardens feel free to reopen if you think this should be reprioritized.

**Comment by cgardens** [comment]
@sherifnada can we icebox it? I feel like this is going to come up again and it might be helpful to have the existing ticket so that people don't gaslight themselves and know that this might be useful. Agreed. We are not likely to work on it soon.
