### ISSUE TITLE
Apply default sync mode logic to new streams after refresh source schema

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#16013]
We currently handle the default sync mode logic in the FE. We though only apply this when the connection is not in edit mode, but created. That means if a user "refreshed source schema" of a connection and new streams are detected those new streams are not getting the default sync mode logic applied, but stay with whatever the config of the backend told us is default (which is not the correct one by the logic we try to go for).

We should make sure that the default sync mode logic in https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/Connection/ConnectionForm/calculateInitialCatalog.ts will apply as well for streams that are new after a "Refresh source schema".

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
@edmundito thinking about how to solve this... it seems like it will involve some degree of merging the diff data into this calculation: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/views/Connection/ConnectionForm/calculateInitialCatalog.ts

I'm wondering if this work is better suited to do alongside integrating the diff with the syncCatalog as part of auto-detect schema changes?

**Comment by tealjulia** [comment]
was closed by #18451
