### ISSUE TITLE
"Stream configuration changed" modal may appear for some streams even when the data has not changed

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16012]
Sometimes the "stream configuration changed" modal appears for some streams, even if the data has not been changed.

![image](https://user-images.githubusercontent.com/168664/186935362-dcfca00e-a7c8-4857-a22d-8398dbc1740e.png)

Cause: When comparing the stream changes, we do not account that the component is pre-sorting the data, so the stream values coming from the form may differ in order from what's in the connection:

https://github.com/airbytehq/airbyte/blob/0e9467624b2e974896ad49527471a74effe6eeaa/airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx#L142-L145

https://github.com/airbytehq/airbyte/blob/0e9467624b2e974896ad49527471a74effe6eeaa/airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx#L183-L186

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
since this touches the submit function, which is being worked on in the connection form service, i've added that issue as a blocker.
