### ISSUE TITLE
Improve LineGobbler output readability

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1602]
## Tell us about the problem you're trying to solve
Line gobbler output is hard to read. This ticket attempts to improve it. 

## Acceptance Criteria
1. Single line logs should always display as a single line (with no wordwrapping)
1. line gobbler java line number prefix (or shortening it. Right now it takes up half the screen)
1. Annotate log lines with the image they are coming from

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368082471847) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
closed as no longer relevant.
