### ISSUE TITLE
Upgrade react-select

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#16023]
Our react-select library is one major version out of date, and we rely on a `@types` library which isn't wholly accurate. Notably we have a `@ts-expect-error` within our usage of it because the types are overly-specific and incorrect.

We should upgrade to the latest react-select (5.4.0 at the time of writing) which does not require an `@types` library and fix the bugs that occur.

We have certain usages wrapped up in styled components and we should remove the usage of styled-components.

I expect this to be a non-trivial upgrade. [Migration guide](https://react-select.com/upgrade)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
Removing styled components from this blew the upgrade well out of scope. See #16439 for that work.
