### ISSUE TITLE
[per-stream cdk] Emit state messages with combined LEGACY and STREAM state

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#16057]
While processing each stream's sync in `_read_incremental()`, we periodically checkpoint the current state by updating the current stream's state value in `data` and emit the new state message. This is done during:

- The start of sync (if there are no slices)
- After the checkpoint interval is exceeded
- After processing a stream slice

Now that the new `ConnectorState` consolidates the legacy, shared, and stream state, we should follow the same checkpoint pattern. We need to update the ConnectorState's `legacy` JSON blob and the respective `stream_states`. Then we need to emit an AirbyteStateMessage in the new format where the `stream` and `data` fields are emitted back to the platform with the newly updated state values.

**Note**: Each stream performing an incremental sync will emit at least one AirbyteStateMessage. And when per-stream state is enabled, each message will always emit both `stream` and `data`. This is required to maintain backwards compatibility when running an upgraded per-stream on a version of the platform or a version of a destination that does not support per-stream.

**Comment by girarda** [comment]
End of sprint update: I did not have time to look into this issue.
