### ISSUE TITLE
Separate raw tables and normalized tables separately in different schemas

### ISSUE THREAD

**Issue by mdhatrika** [airbytehq/airbyte#1607]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I set up an integration from HubSpot into the Postgres database I see the tables being generated but both raw and the normalized tables,  for suppose I have table owners in HubSpot when I made the connection it is getting both owners and owners_raw table this could cause confusion about which one is the correct table to refer to for other users, and we don't want to maintain 2 different tables in one schema which is not clean

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

Separate out the raw tables in another schema like Hubspot_Raw schema and normalized tables in HubSpot schema, so other users can only worry or maintain the tables which are under the Hubspot schema

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368082534600) by [Unito](https://www.unito.io)

**Comment by toandm** [comment]
Yes, please add this in. It's really frustrating when the sync has hundreds of tables. 
For example we have a connection from MySQL to BigQuery that syncs 900 tables, and the destination schema has 900x2 table at least. Not to mention scd and dbt_temp tables as well. Too many

**Comment by MohamedWasfy** [comment]
I need to separate raw airbyte date from normalized in two different schemas and then use a DBT model to build another DWH schema querying from normalized table schema.
in simple I want raw data, normalized , DWH model in three different schemas 
source and destination are postgres

**Comment by grishick** [comment]
@misteryeo FYI, pretty interesting request

**Comment by Svatopluk-Chalupa** [comment]
I completely agree, temp and raw tables separatation is really needed to provide better services to our users. Best solution for me is to have a some kind of "working schema" setting for all airbyte structures which are not the final output. Structures should be identified by some internal ID and decision of schemas and table names should be offered to ETL creator.

**Comment by cgardens** [comment]
Done!
