### ISSUE TITLE
Source-defined primary key should override config primary key

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#16098]
Currently, if a source's source defined primary key changes, it is never saved to the `config` for the stream.  This means it is never applied, which affects users using `dedupe` sync mode. 

If source-defined primary key is changed, the frontend should be copying that into the config/values object and sending it with the API call.

When we refresh source schema, if there is a new `sourceDefinedPrimaryKey`, we should be saving that into the form `values` which then gets saved to the config object on submit.

TODO: look into the same deal for source-defined cursor field... does it have the same buggy behavior?  May want to connect with connectors team to find a way to reproduce this.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
RE: https://github.com/airbytehq/oncall/issues/461
