### ISSUE TITLE
If a destination is not regularly committing, apply backpressure to the source or exit early

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#16109]
Related to https://github.com/airbytehq/airbyte/issues/16031 and https://github.com/airbytehq/oncall/issues/502#issuecomment-1229006683.  

**Overview**

We know that we have destinations that are currently not checkpointing properly (https://github.com/airbytehq/airbyte/issues/14770), and even after this fix, we may always destinations that don't flush/commit rapidly.  To that end, if the worker notices that it has received an *unusually large* number of state messages that haven't been ACKd yet, the source should be paused in some way.  

**Background**

*TO BE VERIFIED*

The worker stores all source-emitted state messages to properly track up-to-which message the destination has ACKd. Once the destination ACKs those messages, the worker removes them from memory. If the destination never ACKS an ever-growing list of state messages, the worker could run out of memory (OOM). 

**Potential Solutions**

Once the worker decides that it is holding too many un-ACKd state messages, action should be taken.  Some options are:
1. A naïve approach would be to terminate the source, allowing the destination to commit the records it has up to now, and then restart the sync.  This only works in the case of well-checkpointing sources doing an incremental sync.
    * As the source is truly exiting, the destination will flush the records it received in the normal way 
    * Care will need to be taken so the source's premature exit doesn't count as a failure of the source
2. The worker can apply backpressure to the source to pause it until the destination ACKs. 
    * If the destination isn't checkpointing, it might never... and the sync would stall indefinitely. 
    * How can we apply backpressure across containers/pods?  I think this might be easier within a K8s deployment than on docker compose.  We may need infrastructure-specific triggers for this... 

At the time of writing, I (@evantahler) think option `1` is the way to go, due to simplicity.

The triggering event to act should be based on the existence of more than 100mb(?) of state messages (we can estimate with string byte length) and be signaled by the receipt of another state message for a fully-incremental sync. This ensures that the source can be resumed. 

**Logging**

As part of this work, the worker should periodically log how many state messages the worker is holding on to, by stream, e.g.
```js
{
  streamA: {count: 1, size: "1mb"},
  streamB: {count: 100, size: "100mb"}
}
```
We should log this every... minute perhaps?

**Comment by evantahler** [comment]
Related to https://github.com/airbytehq/airbyte/issues/16031 and https://github.com/airbytehq/oncall/issues/502#issuecomment-1229006683

**Comment by evantahler** [comment]
cc @salima-airbyte and @cgardens - thanks for brainstorming this!

**Comment by evantahler** [comment]
cc @grubberr relating to https://github.com/airbytehq/airbyte/issues/14770#issuecomment-1230388011

**Comment by gosusnp** [comment]
I wonder if we have a "natural" way to perform option 2. Behind the scene, the workers are writing to local files that are getting piped across the network.

I'd lean towards option 1. One thing that doesn't feel exactly natural is having to terminate the source if the destination stalls. It feels too late in a way since the data has been read and is being piped. That still feels like a good mitigation for the time being.

Longer term, what about looking at this problem as some form of double buffer management? Having the platform manage buffer sizes by telling source to read more data as it gets committed by the destination.

**Comment by alovew** [comment]
Want to comment here for visibility 

> The worker stores all source-emitted state messages to properly track up-to-which message the destination has ACKd. Once the destination ACKs those messages, the worker removes them from memory.

I'm not sure this is true, but maybe there is more information on this somewhere? I thought we were just storing the most recently emitted state message & most recently emitted destination message. If we aren't storing all state messages, then I don't think that can be the source of OOM errors.

**Comment by evantahler** [comment]
Thanks @alovew!  

I think you are right - that's why when implementing per-stream state, the order of messages returned by the destinations mattered so much... because the worker /couldn't/ sort the messages by timestamp. 

I'll close this issue for now assuming that "too many state messages" isn't the culprit that caused https://github.com/airbytehq/airbyte/issues/16031

cc @edgao
