### ISSUE TITLE
Cannot delete a source due to configuration error

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16113]
I am trying to delete a MySQL Source on my localhost and I am getting this error after hitting "Delete" in the confirmation dialog. I understand that my spec is incompatible, but why is the platform trying to validate my spec when I am trying to delete the source?

![Screen Shot 2022-08-29 at 2 23 08 PM](https://user-images.githubusercontent.com/1310940/187301630-d9187bab-84ca-49fe-a7a8-43fb29840fb0.png)

**Comment by salima-airbyte** [comment]
Remove validation upon deletion
