### ISSUE TITLE
Source Salesforce: Implement exclusions from the BULK API for all applicable streams

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#16135]
We recently noticed that the Salesforce BULK API do not support a few streams and we need them to be included from the BULK API entirely.

For reference see [#15901 ](https://github.com/airbytehq/airbyte/pull/15901) and [#16199](https://github.com/airbytehq/airbyte/pull/16119)

**Comment by alafanechere** [comment]
It looks like the updated of unsupported objects is not 💯 accurate:
https://github.com/airbytehq/oncall/issues/776

Updated list here: https://github.com/airbytehq/airbyte/pull/17778
@artem1205 could you share how you built the `UNSUPPORTED_BULK_API_SALESFORCE_OBJECTS` list?

**Comment by YowanR** [comment]
Did we figure out what the issue is here? If we need to manually check the objects/streams, then we can have the Unblocker team help us. Let me know how I can best help fix this issue.

**Comment by lazebnyi** [comment]
cc @artem1205
