### ISSUE TITLE
Sandbox Account for Exchange Rates Data API

### ISSUE THREAD

**Issue by sajarin** [airbytehq/airbyte#16133]
PR #15884 needs a new sandbox account/api key for the Exchange Rates Data API, which has recently moved to [APILayer](https://apilayer.com/marketplace/exchangerates_data-api)

**Comment by igrankova** [comment]
Subscribed to Free Plan. LastPass name: Primary Apilayer Developer account
Docs: https://apilayer.com/marketplace/exchangerates_data-api#documentation-tab

**Comment by igrankova** [comment]
@sajarin Let me know if this free account is ok for PR needs.

**Comment by sajarin** [comment]
Thanks @igrankova! This free account is just what we needed to close out the PR.
