### ISSUE TITLE
broken db-lib scripts

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#16142]
## What

We have a couple helper scripts from the db-libs [README.md](https://github.com/airbytehq/airbyte/blob/master/airbyte-db/db-lib/README.md?plain=1#L27) that are broken.
* Configs database: ./gradlew :airbyte-db:db-lib:runConfigsMigration.
* Jobs database: ./gradlew :airbyte-db:db-lib:runJobsMigration.
* Configs database: ./gradlew :airbyte-db:db-lib:dumpConfigsSchema
* Jobs database: ./gradlew :airbyte-db:db-lib:dumpJobsSchema

They seem to be lacking some configs: `DATABASE_USER`, `DATABASE_PASSWORD` and `DATABASE_URL`.
Passing those still seem to end up with a non-terminating process.

Is this something that we are still using?

**Comment by evantahler** [comment]
Maybe @davinchia knows if we are still using these?

**Comment by davinchia** [comment]
We do need these. It's how we write migrations. We should figure out why they are broken.

**Comment by davinchia** [comment]
Unless this process has changed since I last wrote a migration. @gosusnp how did you write https://github.com/airbytehq/airbyte/blob/master/airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_39_17_001__AddStreamDescriptorsToStateTable.java?

**Comment by gosusnp** [comment]
@davinchia, yes I wrote that migration. I generated the template from the fist command which still works. However I did not try to apply it from those commands, instead of was validating through tests that should be using the same underlying classes to apply the migrations.

I suspect there might be some config mismatch in the runner, for example, it seems to be complaining about missing credentials when executed directly through gradle.

What do you mean by that's how we write migrations? I thought the migration apply part was done through the `DatabaseMigrator` that is being executed from the `BootloaderApp`.

**Comment by davinchia** [comment]
@gosusnp I was referring to https://github.com/airbytehq/airbyte/tree/master/airbyte-db/db-lib#how-to-write-a-migration. I think the run migration command can be skipped, but I'm not sure the dump one can. Iirc, it creates a schema dump used to bootstrap our test database containers.

@tuliren as author, can you confirm?

**Comment by gosusnp** [comment]
Yes, currently, we should still run the command to generate the template. This one is still working modulo a current build issue that is being addressed in https://github.com/airbytehq/airbyte/pull/16146.

The run migrations and dump schema are the pieces that are currently broken from the `ConfigsDatabaseMigrationDevCenter`.
If we want to keep those working, we should at least have a couple tests to avoid catching those issues when we need to write a new migration.

**Comment by davinchia** [comment]
@gosusnp to run commands to double check if still broken

**Comment by gosusnp** [comment]
Looks like the recent jooq migration have fixed this. Just tried all the commands from the how to write a migration section, all good.
