### ISSUE TITLE
Clicking "Cancel" after saving changes reverts workspace general settings form to pre-save initial data

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#16149]
## Environment
- cloud
- Workspace Settings > General Settings (specifically, the `src/packages/cloud/views/workspaces/WorkspaceSettingsView/WorkspaceSettingsView.tsx` component)

## Current Behavior / Reproduction Steps
1) In a cloud-backed airbyte frontend, navigate to "Settings" and then to "Workspace Settings > General Settings"
2) Edit the workspace name
3) Click "save changes"
4) After waiting for the save to resolve successfully, click the "cancel" button
5) the workspace name is reverted to its original, pre-save value

This reversion is only in memory; refreshing the page restores the newly-saved value. Here's a gif I recorded (pay no attention to the "Advanced Mode" toggle, it's in-progress work related to https://github.com/airbytehq/airbyte/issues/15145):
![workspace-general-settings--undoing-saved-change](https://user-images.githubusercontent.com/7516653/187556905-baf0213d-1811-45a1-beea-934f0bd1b221.gif)

## Expected Behavior
Steps 1-4 are identical
5) Clicking the "cancel" button should have no affect on persisted data, regardless of whether it was part of the initial render

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
