### ISSUE TITLE
Add qualitative comment to Onboarding Feedback

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#16150]
# Current Behavior 
We have a survey in the webapp that asks about the experience after the first successful sync. We get about a 11% response rate for this in Cloud and about a 4% on OSS. Outside of the like or dislike, we don't get qualitative information about the response. We compiled the results from the survey over the last year here: https://docs.google.com/document/d/1hrbaQ0fCJ9pH3iTAy7qyKU3mVNnViBYDovuY8BVXnXs/edit

# Ideal Behavior
We should first ensure we collect as much feedback at the moment of survey. This means adding an option for the user to leave a comment if they "dislike" the survey. The Figma associated to the original spec is linked in the document above, but it was not implemented in the original survey.

Alternatively, we can explore third-party survey solutions that can be triggered using backend Segment events. We've looked at Hotjar in the past but there are other options on the market that would allow us greater flexibility in changing or experimenting with language and capabilities over investing more in our in-house solution. 

@letiescanciano

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
This can be solved using Chameleon.io and Hightouch! The model is User Attributes (Trialers & Customers). It sends the following attributes to chameleon.io:
- User ID
- Account Type (In Trial, Customer)
- First Sync Success (timestamp)

Using the First Sync Success, we can show the survey module to users after we see a successful sync and solicit feedback as a follow-up step.

Visual screenshots in the Proposal section of the document here: https://docs.google.com/document/d/1hrbaQ0fCJ9pH3iTAy7qyKU3mVNnViBYDovuY8BVXnXs/edit#heading=h.bc7d136g56ve
