### ISSUE TITLE
Source Zendesk Support: `ticket_metrics` pagination error

### ISSUE THREAD

**Issue by Wolff-Lucas** [airbytehq/airbyte#16163]
## Environment
- **Airbyte version**: 0.40.2
- **OS Version / Instance**: debian 11 bullseye / GCP e2
- **Deployment**: Docker
- **Source Connector and version**: Zendesk Support 0.2.15
- **Destination Connector and version**: BigQuery 1.1.15
- **Step where error happened**: Sync job

## Current Behavior
I want to sync all the zendesk support tables with incremental + dedup when it's available and full refresh overwrite when it's not.
The first sync is working well.
But during the second the ticket metrics start to sync but the following error occurs : 
Response Code: 429, Response Text: Pagination limit reached for offset model
## Expected Behavior
Second sync should succeed

## Logs

[logs-135.txt](https://github.com/airbytehq/airbyte/files/9459720/logs-135.txt)

## Steps to Reproduce
1. Select all tables with incremental + dedup when it's available
2. Do a first sync
3. Launch a second sync

**Comment by natalyjazzviolin** [comment]
Hi @Wolff-Lucas looks like this should have been fixed by [#13757](https://github.com/airbytehq/airbyte/pull/13757/) but is breaking. Thank you for reporting!

**Comment by btkcodedev** [comment]
I would like to work on this

**Comment by btkcodedev** [comment]
Already been solved through https://github.com/airbytehq/airbyte/pull/26945
Check comments in https://github.com/airbytehq/airbyte/pull/27070 for reference
Please close issue

**Comment by marcosmarxm** [comment]
Solved in #26945
