### ISSUE TITLE
Sandbox Account for Opsgenie

### ISSUE THREAD

**Issue by sajarin** [airbytehq/airbyte#16170]
Need a sandbox account for PR #16056. 

https://www.atlassian.com/software/opsgenie

cc: @igrankova (p.s sorry in advance, let me know if there's a better way to request new accounts)

**Comment by igrankova** [comment]
@sajarin, sure, I'll try to help you.

**Comment by igrankova** [comment]
Hi, @sajarin,
I created a 14-days trial account. You can find creds and the API Key in the LastPass: Atlassian Opsgenie trial account.
I asked the Atlassian support for sandbox, waiting for response, will keep you in the loop.

**Comment by igrankova** [comment]
Free account:
Basic Alerting and On-Call Management for Small Teams
$0
up to 5 users
API Request Limits - # of users x1000
"If you decide not to start paying at the end of your 14-day trial, your account will be converted to the Free plan, and features that are not available in Free plan will be disabled." [Pricing](https://www.atlassian.com/software/opsgenie/pricing) - the details of a Free plan.
@sajarin can you please review the Free plan by the [Pricing](https://www.atlassian.com/software/opsgenie/pricing) link, maybe it's enough to have a Free plan account for our testing purposes?

**Comment by igrankova** [comment]
Hi, @sajarin,
Is there anything I can do more or we can close this issue?

**Comment by sajarin** [comment]
Hey @igrankova, 

Sorry for the delay in response. We can close it for now and I'll reopen if there's any further issues or concerns. Thanks for your help with this, I really appreciate it!

**Comment by igrankova** [comment]
@sajarin 
I was glad to help! Have a nice day:)

**Comment by igrankova** [comment]
For the information:
![image](https://user-images.githubusercontent.com/87977540/190624446-8b236b7e-106d-4a7d-ba2d-21401afee3c3.png)
