### ISSUE TITLE
Ensure encryption of connections between Airbyte Cloud and customer resources

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16184]
We make the following [guarantee](https://docs.google.com/document/d/1bN5NtW57umIcsticFqdhuvSQRfMuGQlijFClFQQFqL8/edit#heading=h.jo89nkgtj79l):

> All Airbyte Cloud connectors (APIs, files, databases) pull data through encrypted channels (SSL, SSH tunnel, HTTPS) and the data transfer between our clients' infrastructure and Airbyte infrastructure is fully encrypted.

in the scope of this Epic we need to review all connectors available in Airbyte Cloud and make sure they comply with the requirement emposed by this guarantee.

**Comment by evantahler** [comment]
Love this.  Does this imply that an API source which doesn't use HTTPS cannot be used on Airbyte Cloud?

**Comment by grishick** [comment]
> Love this. Does this imply that an API source which doesn't use HTTPS cannot be used on Airbyte Cloud?

correct
