### ISSUE TITLE
fix webapp tests and run them as part of CI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1620]
## Expected Behavior
`./gradlew test` should pass. `./gradlew build` should run webapp tests.

## Current Behavior
`./gradlew test` does not pass due to failures in the webapp tests, which can be run independently with `npm run test -- --watchAll=false` or `./gradlew :airbyte-webapp:test`. Also, the webapp tests are not connected to `./gradlew build`:
```
→ ./gradlew build  --dry-run | grep webapp
:airbyte-webapp:nodeSetup SKIPPED
:airbyte-webapp:npmSetup SKIPPED
:airbyte-webapp:npmInstall SKIPPED
:airbyte-webapp:npm_run_build SKIPPED
:airbyte-webapp:assemble SKIPPED
:airbyte-webapp:check SKIPPED
:airbyte-webapp:build SKIPPED

→ ./gradlew test  --dry-run | grep webapp
:airbyte-webapp:nodeSetup SKIPPED
:airbyte-webapp:npmSetup SKIPPED
:airbyte-webapp:npmInstall SKIPPED
:airbyte-webapp:npm_run_build SKIPPED
:airbyte-webapp:assemble SKIPPED
:airbyte-webapp:test SKIPPED <-- missing from build, so it isn't run in CI
```

## Severity of the bug for you
Medium

**Comment by Jamakase** [comment]
@jrhizor Actually I am not quite sure whether its a good idea or not to run tests as part of the build. This is how I see, the flow of CI:
- lint
- test
- build

So we won't even run build if tests are failing - that will allow us to fail fast. The build is more of bundling all things together and making a deployment package.

**Comment by jrhizor** [comment]
Right now all of our linting and tests are available under the `./gradlew build` command as well. Since it wouldn't depend on anything it should be able to run early in the scheduling of tasks and fail relatively fast.

The main goal of this issue was to say that we should execute the tests somewhere as part of our build pipeline and fail if they aren't working.

I think we're trying to group everything under `build` just so we don't miss anything for our CI / local workflows of iterating on the project.

**Comment by cgardens** [comment]
fixed.
