### ISSUE TITLE
publish airbyte-integrations/bases images

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1621]
We should push bases. 

From a user:

> To do a ./gradle build does generate a lot of resources on my system i don't need to create new integrations.

The current behavior is somewhat unintuitive since these are the only images that are not available. It also will help when someone is skipping through docs (it isn't obvious just how much `./gradlew build` is responsible for).

**Comment by sherifnada** [comment]
This is also useful because it allows complete isolation of the connector development experience as described in #2360 . Bumping to priority medium and pulling into upcoming milestone.

**Comment by sherifnada** [comment]
closed in #2469
