### ISSUE TITLE
MQTT Destination: Password is not marked as a secret field in spec

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#16219]
The password field of the MQTT destination is not marked as a secret field in the connector specification and thus this field will not show correctly as a password field in the CI, which leads to several potential security drawbacks.

**Comment by grishick** [comment]
@alexandr-shegeda please have your team fix this ASAP.

**Comment by alexandr-shegeda** [comment]
@grishick @timroes published and merged the fix
