### ISSUE TITLE
Documentation: Rewrite the Airbyte AWS deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16228]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte AWS deployment guide](https://docs.airbyte.com/deploying-airbyte/on-aws-ec2) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by Terieyenike** [comment]
Hi, 
Can I work on this?

**Comment by Terieyenike** [comment]
Hey @Amruta-Ranade, here is the first [draft](https://docs.google.com/document/d/1YzG6CI3KVy5hQbtVxUjUB0M7sa7Dk6u8/edit?usp=sharing&ouid=114557752341261267567&rtpof=true&sd=true).

**Comment by Terieyenike** [comment]
Hey @Amruta-Ranade,
Please check the review for my [docs](https://docs.google.com/document/d/1YzG6CI3KVy5hQbtVxUjUB0M7sa7Dk6u8/edit?usp=sharing&ouid=114557752341261267567&rtpof=true&sd=true).

**Comment by Amruta-Ranade** [comment]
Feel free to open a PR and assign it to me for review :)
