### ISSUE TITLE
Documentation: Rewrite the Airbyte local deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16229]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte local deployment guide](https://docs.airbyte.com/deploying-airbyte/local-deployment) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by Bam92** [comment]
I'm on it.

**Comment by Amruta-Ranade** [comment]
@Bam92 Any updates?

**Comment by Bam92** [comment]
@Amruta-Ranade you'll get it later in the end of this week.

**Comment by Amruta-Ranade** [comment]
Thanks. Please follow the instructions in the Docs Contribution Program follow-up email so we can stick to the check-in schedule.
