### ISSUE TITLE
Cleanup font and switch to variable fonts

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#16239]
Our current font usage needs several cleanup and as part of that we should switch over to variable fonts completely as the more modern font type. For this cleanup we should do the following:

1. Switch Inter over to use the variable font of it.
  * Given the wide [browser adoption](https://caniuse.com/variable-fonts) and that we don't support the older browsers I feel, we can drop the support for the non variable font altogether to save putting them into our code at all. For the very rare case a user might not have support for variable fonts, I think it's fine just having them use "Arial, sans-serif" from their system.
2. Remove references to other fonts
  * `Montserrat` font completely from the codebase. It's used only as part of `$highlightFont` which is not used anywhere (?) so we should remove this variable as well.
  * `Shrikhand` font as well as `$italicFont` which are unused.
3. Pick a code font and cleanup
  * Change `$codeFont` to not use `Arial, sans-serif` as a fallback, but instead `monospace`, which would be the correct family name.
  * Since `Courier Prime` has no variable font yet, let's consider switching this over to `Roboto Mono` (and use its variable font variation). cc @Upmitt if you have any preference for a free monospace font we should use? (it's currently only used in the log view)

Because of the OSS product, these fonts must be included as part of the package instead of referencing third-party font files (example: Google Fonts)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
