### ISSUE TITLE
Documentation: Rewrite the Airbyte Oracle Cloud Infrastructure deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16233]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte Oracle Cloud Infrastructure deployment guide](https://docs.airbyte.com/deploying-airbyte/on-oci-vm) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by victor-cody** [comment]
HI, i'd like to take this on :)

**Comment by Amruta-Ranade** [comment]
@victor-cody Any updates on the draft?

**Comment by victor-cody** [comment]
Hi @Amruta-Ranade, sorry for the delay 😄. Here's my first [draft](https://docs.google.com/document/d/1yvJ7Od4RglsRUHJO69MgDlYvuv88xs5kl77Is0gWa-E/edit?usp=sharing)

**Comment by victor-cody** [comment]
Hi @Amruta-Ranade here's a revised [draft](https://docs.google.com/document/d/1yvJ7Od4RglsRUHJO69MgDlYvuv88xs5kl77Is0gWa-E/edit?usp=sharing)

**Comment by victor-cody** [comment]
HI @Amruta-Ranade, here's the [PR](https://github.com/airbytehq/airbyte/pull/18615) 🎉
