### ISSUE TITLE
Documentation: Rewrite the Airbyte Azure deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16230]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte Azure deployment guide](https://docs.airbyte.com/deploying-airbyte/on-azure-vm-cloud-shell) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by sblaizerwize** [comment]
I will be glad to take this section

**Comment by sblaizerwize** [comment]
Hi team, 
Here is the first [draft](https://docs.google.com/document/d/1b4zRSluIuJPmvFusKWfi0EeCrpS2ZCTTr858k8yr1QM/edit#heading=h.2ubgjnf3axu3)

**Comment by sblaizerwize** [comment]
Hi team, 
Here is the [draft](https://docs.google.com/document/d/1lBJUO-8-8Ww_aQz-goCeX3reDcPoCZdfA3YYYWOALDU/edit?usp=sharing) with comments from the first peer review

**Comment by Amruta-Ranade** [comment]
Thanks! Once you work on the comments, feel free to open a PR :)

**Comment by sblaizerwize** [comment]
Hi team, 
Here is the [revised version of the document](https://docs.google.com/document/d/1SEP3VTQ1Fdq6BT26a3mee8Gat0D9f47nSTy0P-NB-Rk/edit?usp=sharing). I will proceed to open a PR.
