### ISSUE TITLE
Documentation: Rewrite the Airbyte DigitalOcean deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16234]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte DigitalOcean deployment guide](https://docs.airbyte.com/deploying-airbyte/on-digitalocean-droplet) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by ikeadeoyin** [comment]
Hello
I woud love to work on this.

**Comment by ikeadeoyin** [comment]
Hi @Amruta-Ranade, here is a revised [draft](https://docs.google.com/document/d/1sQUPOzZsvbgHnNL3iGezN65eSviqODIOR2WjehxG3Fw/edit?usp=sharing).

**Comment by Amruta-Ranade** [comment]
Feel free to open a PR and assign it to me for review :)

**Comment by Amruta-Ranade** [comment]
@ikeadeoyin Any updates on the PR?

**Comment by ikeadeoyin** [comment]
Hi @Amruta-Ranade , here is the[ PR](https://github.com/airbytehq/airbyte/pull/18566).
