### ISSUE TITLE
Documentation: Rewrite the Airbyte Kubernetes deployment guide

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#16231]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Airbyte Kubernetes deployment guide](https://docs.airbyte.com/deploying-airbyte/on-kubernetes) doesn't follow the [Google style guide](https://developers.google.com/style) and overuses screenshots instead of a well-documented procedure. 

Tasks:
- Document the procedure in words instead of screenshots (similar to the [Airbyte Cloud quickstart](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud))
- Ensure it adheres to the Google style guide

**Comment by Amruta-Ranade** [comment]
Related: https://github.com/airbytehq/airbyte/issues/13080

**Comment by Jagrutiti** [comment]
Hey Amruta,

Here is my [first draft](https://docs.google.com/document/d/19A-jYZPgsh4eG6OEI5neKFk_-XIrHEaa076kUcbtXTQ/).

**Comment by Amruta-Ranade** [comment]
Thanks! Feel free to open a PR :)

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/airbytehq/airbyte/pull/18339
