### ISSUE TITLE
webapp crashes with default docker-compose configuration

### ISSUE THREAD

**Issue by mousetree** [airbytehq/airbyte#16274]
## Environment
- **Airbyte version**:  latest docker-compose on master
- **OS Version / Instance**: Debian 5.10.136-1 running on GCP n2
- **Deployment**: Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
webapp container cannot start when running `docker-compose up -d` using default `docker-compose.yaml`. I followed the GCP tutorial.

## Expected Behavior
Everything should start up easily on first use with default configuration

## Logs

```
adam@airbyte:~/airbyte$ docker-compose ps
       Name                     Command                 State                                                          Ports
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
airbyte-bootloader   /bin/bash -c ${APPLICATION ...   Exit 0
airbyte-cron         /bin/bash -c ${APPLICATION ...   Up
airbyte-db           docker-entrypoint.sh postgres    Up           5432/tcp
airbyte-server       /bin/bash -c ${APPLICATION ...   Up           8000/tcp, 0.0.0.0:8001->8001/tcp,:::8001->8001/tcp
airbyte-temporal     ./update-and-start-temporal.sh   Up           6933/tcp, 6934/tcp, 6935/tcp, 6939/tcp, 0.0.0.0:7233->7233/tcp,:::7233->7233/tcp, 7234/tcp, 7235/tcp, 7239/tcp
airbyte-webapp       /docker-entrypoint.sh ngin ...   Restarting
airbyte-worker       /bin/bash -c ${APPLICATION ...   Up
init                 /bin/sh -c ./scripts/creat ...   Exit 0
```

Logs from webapp container

```
airbyte-webapp      | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
airbyte-webapp      | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
airbyte-webapp      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
airbyte-webapp      | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
airbyte-webapp      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
airbyte-webapp      | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
airbyte-webapp      | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
airbyte-webapp      | /docker-entrypoint.sh: Configuration complete; ready for start up
airbyte-webapp      | 2022/09/02 15:24:21 [emerg] 1#1: unknown "fullstory" variable
airbyte-webapp      | nginx: [emerg] unknown "fullstory" variable
```

## Steps to Reproduce
1. git clone https://github.com/airbytehq/airbyte.git
2. cd airbyte
3. docker-compose up

## Are you willing to submit a PR?
Sure

**Comment by keedle** [comment]
same happens when you deploy to DO - fullstory issue. I fixed it by manually copying docker-compose.yaml from git. 
Seems like the one you get via wget has FULLSTORY config line,however, the one on git doesn't.

p.s i assume that fullstroy is fullstory.com ?

**Comment by hellmund** [comment]
To add what @keedle said: as work-around when you have a broken docker setup:
- ensure you have `FULLSTORY=disabled` in .env
- ensure you have `- FULLSTORY=${FULLSTORY:-}` in the environment section of webapp in docker-compose.yaml

**Comment by timroes** [comment]
This will be resolved as soon as the PR for the next release (https://github.com/airbytehq/airbyte/pull/16275) has been merged. This should happen within the next hours from which time this issue should be resolved. I keep updating here as well.

**Comment by timroes** [comment]
This should be resolved by now, when pulling the latest master.
