### ISSUE TITLE
Add ability to enforce SSL in MongoDB Source connector

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16278]
## Tell us about the problem you're trying to solve

- MongoDB does not _always_ enforce SSL
- [ ] we need a test that validates this behavior
- [ ] we need an explanation in the docs about why customers cannot set ssl/tls=false in Airbyte Cloud

## Describe the solution you’d like
Implement configuration for adding `ssl` parameter for MongoDB source

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
[Connection Options](https://www.mongodb.com/docs/manual/reference/connection-string/#connection-options)

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by grishick** [comment]
Mongo URL has `ssl` and `tls` options and we need to check that these parameters are not overwritten in -strict-encrypt version of MongoDB source

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/16278?planning-poker) with Zenhub @akashkulk @edgao @ryankfu @subodh1810 @tuliren

**Comment by tuliren** [comment]
Should also update documentation.

**Comment by tuliren** [comment]
From Subodh, the tls parameter is ignored for ATLAS and REPLICA SET. Need to make sure we don't override it.
