### ISSUE TITLE
Add ability to enforce SSL in DynamoDB Destination connector

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16283]
## Tell us about the problem you're trying to solve
DynamoDB does not _always_ enforce SSL 

## Describe the solution you’d like
Implement configuration for adding `ssl` parameter for DynamoDB destination

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
[Client-side Encryption DynamoDB](https://github.com/aws/aws-dynamodb-encryption-java/)

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by grishick** [comment]
Note from grooming:
HTTPS enforcement is relevant only when connecting to a custom end-point. In this case, the connector should verify that the endpoint is HTTPS, not HTTP when the connector is being used in Airbyte Cloud. Additionally, there may be a way to enforce protocol when instantiating AWS client.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/16283?planning-poker) with Zenhub @edgao @ryankfu
