### ISSUE TITLE
Bulk Edit not functioning

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#16286]
Currently, this feature is broken on prod:

![Screen Shot 2022-09-02 at 2.36.01 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/5d8e20e9-9eb7-41b6-9de2-c876e541325e
)

Expected behavior: When I change the sync mode or enabled/disabled in the bulk edit header (dark purple in the screenshot), it should apply to all streams in the table (light purple in the screenshot)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Disregard.  It looks like there is a cancel/apply button and I did not understand the functionality.
