### ISSUE TITLE
Add SSH tunneling ability to Databricks Destination connector

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16309]
## Tell us about the problem you're trying to solve
Databricks does not have a SSH wrapper when other Java based connectors have this functionality

## Describe the solution you’d like
Add SSH wrapper around Databricks to have feature parity with other Java based connectors

**Comment by grishick** [comment]
cc @tuliren

**Comment by grishick** [comment]
Note from grooming: this also includes making sure that normalization for DataBricks works via SSH tunnel.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/16309?planning-poker) with Zenhub @edgao @rodireich @ryankfu @subodh1810 @tuliren

**Comment by grishick** [comment]
Based on the findings outlined in [this issue](https://github.com/airbytehq/airbyte/issues/16308) there is no need for SSH tunneling for Databricks connector.
