### ISSUE TITLE
SSH Tunnels: Private SSH key not treated as secret by UI

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#16307]
In all connectors that support SSH tunneling, the "SSH Private Key" field is not marked as secret correctly, thus is not considered to be a password field in the frontend. This should be fixed to be a secret field, to be handled properly in the FE.

**Comment by grishick** [comment]
Hm... ssh private key is marked `airbyte_secret:true` in ssh-tunnel-spec.json and I think this file is used in all connectors that offer SSH Tunneling.
<img width="441" alt="Screen Shot 2022-09-02 at 3 48 00 PM" src="https://user-images.githubusercontent.com/1310940/188243893-a8e0ed1e-bbd3-46ba-91bc-50895d28eff3.png">

is this not the correct way to mark this field as secret?

**Comment by timroes** [comment]
Indeed. Sorry for the noice. I only double checked it in the spec for this one. This seems to be a FE issue, that we're not treating this correctly as secret (I assume because of the multiline: true, but needs more investigation).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
