### ISSUE TITLE
octavia-cli: import all cause error: "no attribute 'catalog' at ['['received_data']']['catalog']"

### ISSUE THREAD

**Issue by JackTheMico** [airbytehq/airbyte#16341]
## Environment
- **Airbyte version**:  0.39.23-alpha
- **Deployment**: Kubernetes
- **Octavia-CLI version**: 0.40.4
- **Step where error happened**: `octavia import all`

## Current Behavior
*It looks like octavia-cli raise an error when it was importing a connection which is from Github to Snowflake.
I think this might relate to the Github Source.*

## Expected Behavior
*Import all existing sources, destinations and connections to manage them with octavia-cli.*

## Logs

```python
Traceback (most recent call last):
  File "/usr/local/bin/octavia", line 8, in <module>
    sys.exit(octavia())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 54, in invoke
    raise e
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/base_commands.py", line 51, in invoke
    result = super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/check_context.py", line 91, in wrapper
    f(ctx, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 169, in all
    import_connection(api_client, workspace_id, resource_id)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/_import/commands.py", line 120, in import_connection
    new_configuration_path = connection_renderer.import_configuration(".", remote_configuration)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/renderers.py", line 314, in import_configuration
    rendered = self._render()
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/generate/renderers.py", line 294, in _render
    yaml_catalog = self.catalog_to_yaml(self.source.catalog)
  File "/usr/local/lib/python3.9/site-packages/octavia_cli/apply/resources.py", line 506, in catalog
    return schema.catalog
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 189, in __getattr__
    return self.__getitem__(attr)
  File "/usr/local/lib/python3.9/site-packages/airbyte_api_client/model_utils.py", line 524, in __getitem__
    raise ApiAttributeError(
airbyte_api_client.exceptions.ApiAttributeError: SourceDiscoverSchemaRead has no attribute 'catalog' at ['['received_data']']['catalog']
```
Here are some screenshots that I can share to help with this:
![image](https://user-images.githubusercontent.com/19216598/188533210-935fb4cc-7b5b-4616-94d5-34c1334a54e5.png)
![image](https://user-images.githubusercontent.com/19216598/188533256-fa83604c-b5f2-4931-b23b-bec7e08bf26d.png)

## Steps to Reproduce
1. octavia init
2. octavia import all

## Are you willing to submit a PR?

Potentially.

**Comment by JackTheMico** [comment]
![image](https://user-images.githubusercontent.com/19216598/188575706-0b886ed1-681b-42b1-9345-c82c8a36c536.png)
Update. The github source's version is 0.2.35

**Comment by marcelopio** [comment]
That is generally caused by a connection that the source is failing (go to the source and do a retest). 

From what I remember when I investigated the issue, the best practice would be for octavia to get the output of `/v1/sources/discover_schema` and check the jobInfo object if it succedded or not, and then display the logs for the cause

**Comment by sajarin** [comment]
Thanks for the suggestion @marcelopio. 

@JackTheMico can you test the source connection and report back?

**Comment by alafanechere** [comment]
@marcelopio @JackTheMico , if the root cause is indeed an unreachable source the following issue should help provide a better error message: https://github.com/airbytehq/airbyte/issues/12697

**Comment by marcelopio** [comment]
Hmm, I think it is a different issue. Here we already have a connection and we are importing. I don't think we should run a check. I think we should trust that everything was good to begin with, as the user went through the process on the UI. 

And the problem is that we try to parse the response from `/v1/sources/discover_schema` without checking if the job was successful. That job could fail for other reasons and give the same message. So I think this solution has to be implemented anyway.

I will try to make a PR for this.

**Comment by JackTheMico** [comment]
I tried `/v1/sources/discover_schema` on the Github source and here's the response:
```shell
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, Content-Type, Accept, Content-Encoding
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 414
Content-Security-Policy: script-src * 'unsafe-inline'; worker-src self blob:;
Content-Type: application/json
Date: Thu, 08 Sep 2022 02:28:02 GMT
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
    "jobInfo": {
        "configId": "Optional[ef69ef6e-aa7f-4af1-a01d-ef775033524e]",
        "configType": "discover_schema",
        "createdAt": 1662604078501,
        "endedAt": 1662604082178,
        "id": "4f031e17-3498-4ca6-90ed-bf4fce3a191c",
        "logs": {
            "logLines": [
                "2022-09-08 02:27:58 \u001b[32mINFO\u001b[m i.a.w.t.TemporalAttemptExecution(get):110 - Cloud storage job log path: /workspace/4a8eab98-1ef3-4ceb-a71b-74cb9b3130fe/0/logs.log"
            ]
        },
        "succeeded": false
    }
}
```
It failed due to some misconfiguration of the source. 
But for octavia-cli, I think it shouldn't break the whole `import all` procedure because of users misconfiguration on sources or destinations.
So yeah, I'd say it's necessary to check if `/v1/sources/discover_schema` was successed or not before try to parse its response.

**Comment by togidoto** [comment]
I know it's late to discuss here, but im facing the same issue while using get/import connections on Octavia-cli 0.40.17 and 0.50.4 versions. Therefore i can not import my existing Airbyte connections using Octavia.
