### ISSUE TITLE
Use returned streams when updating/saving connection form

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#16368]
Currently we're not updating the sync catalog the connection form holds as data after we send the request. Since https://github.com/airbytehq/airbyte/issues/14839 has been fixed the APIs now return the full catalog as part of their response.

We should make sure we're updating our local values to the catalog that has been returned, to prevent any divergence between what we show to the user and the backend actually holds. At the moment we already see some divergence, since the Backend does not accept the sync mode correctly for disabled streams and just set them to something else (#15738).

* Override the sync catalog in the connection object (if it's not done)
* Update the replication settings form values to match the connection objects
* Ensure it has test coverage
* Must also be tested thoroughly (most likely manually)
* Ensure that updating connection status, transformation, name does not break the connection configuration

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
> `We should make sure we're updating our local values to the catalog that has been returned`.  

I think we need to map out when we should be reading from `config` (what the user has defined and saved to the db) versus `stream`.  I don't _think_ it's all one or the other.  

I propose we move this work after #15603 (the service refactor), but I don't think there's harm in doing it in tandem with #15606 (the form refactor) as they shouldn't affect each other.

**Comment by tealjulia** [comment]
Re-assigning to KC as this fits within the scope of his latest PR that is addressing submit behavior.
