### ISSUE TITLE
Fix linking directly to jobs with pagination

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#16369]
## What

See slack thread for context: https://airbytehq-team.slack.com/archives/C03088BTMFC/p1662035572680009?thread_ts=1662024825.781549&cid=C03088BTMFC

With the introduction of [pagination in the job list page](https://github.com/airbytehq/airbyte/issues/10323), loading that page now only loads the most recent 25 jobs for the connection, until the user clicks the `Load more` button at the bottom which loads the next 25 and so on.

This means that if someone links directly to a job outside of these first 25 jobs, the UI will only load those first 25, and will not expand the linked job until the user clicks `Load more` enough times to load that job.

## How

The approach we have decided on is to update the list jobs API endpoint to accept a specific job ID to retrieve "up to", which should then return that job and any more recent jobs as well. This way, if someone has linked a specific job, that ID can be passed in and we will be guaranteed to retrieve the right jobs.

This approach is preferred over a frontend-only change to repeatedly request the list jobs endpoint until it finds the right page, as this is slow, complicated, and not a great user experience.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
