### ISSUE TITLE
Source Zendesk Support: Negative IDs / integers for Zendesk Support connection

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#16367]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2071](https://airbyte7538.zendesk.com/agent/tickets/2071)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">
<strong>Is this your first time deploying Airbyte?</strong> No</li>
<li style="padding-bottom: 10px;">
<strong>OS Version / Instance</strong>: Ubuntu / AWS EC2</li>
<li style="padding-bottom: 10px;">
<strong>Memory / Disk</strong>: m5.2xlarge - 8 CPU, 32 GB Memory</li>
<li style="padding-bottom: 10px;">
<strong>Deployment</strong>:  Docker</li>
<li style="padding-bottom: 10px;">
<strong>Airbyte Version</strong>: 0.39.14-alpha</li>
<li style="padding-bottom: 10px;">
<strong>Source name/version</strong>: airbyte/source-zendesk-support:0.2.15</li>
<li style="padding-bottom: 10px;">
<strong>Destination name/version</strong>: airbyte/destination-s3:0.3.14</li>
<li style="padding-bottom: 10px;">
<strong>Step</strong>:</li>
</ul>
<ol dir="auto">
<li style="padding-bottom: 10px;">Create a connection between Zendesk Support and S3, in a parquet format.</li>
<li style="padding-bottom: 10px;">Query the data (in that case, using Athena). It will be possible to see IDs as negative floats when it should be integers. Also, the numbers don’t match the original ID on Zendesk. Example with <code style="background-color: #f9f9f9; padding: 2px 5px;">Zendesk Ticket Comments</code> table:<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/8/8faa31d03f4f9b0123ddc79d6cb20239dcd44a8a.png" alt="image" width="auto" height="auto" style="max-width: 100%;">
</li>
</ol>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">
<strong>Description</strong>: Some additional comments;
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">This doesn’t happen to other sources, apparently only with Zendesk.</li>
<li style="padding-bottom: 10px;">My assumption is that Zendesk provides some big integers for some columns. When the code converts data to a parquet, it “changes” the values.</li>
</ul>
</li>
</ul> 

[<a href="https://discuss.airbyte.io/t/negative-ids-integers-for-zendesk-support-connection/2381/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-09-06 at 17:11:*

<blockquote><div class="zd-comment" dir="auto">Hi @israel.mendes, I think your assumption is correct and if that's the case, we can most likely have a community contribution to fix the error.&nbsp;<br>&nbsp;<br>I escalated the issue to github here: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/16367">https://github.com/airbytehq/airbyte/issues/16367</a>. Please follow there for updates.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-06 at 21:32:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I will follow up on Github then, thanks <a href="/u/sajarin" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@sajarin</a>!</p> 

 [<a href="https://discuss.airbyte.io/t/source-zendesk-support-negative-ids-integers-for-zendesk-support-connection/2381/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by hemanthadawale** [comment]
Hi @sajarin and @marcosmarxm , I am facing exact same issue with MySQL Source. The destination is same as [israel.mendes's]  which is S3 in parquet format. The bigint columns in MySql tables are converted to incorrect negative values in parquet S3.
Can you help me here or guide to any thread?

**Comment by ivanachillee** [comment]
I'm having the exact same issue with Google Ads campaign ID's

**Comment by shrodingers** [comment]
Issue is INT typing on the ids of the zendesk connection, leading to INT overflow on destinations which have a INT typing on 32bits. so any number > MAXINT (2147483647) is being truncated to fit into 32 bits, thus even rewriting the MSB leading to negative numbers being shown. Solution would be to change zendesk id type to string to allow correct arbitrary length numbers. Would gladly submit a pr for that if needed. In the meantime, some trick that works is to recover the correct id using url field and regexp extraction

**Comment by evantahler** [comment]
This should be fixed with the 1.0 version of the destination-s3 connector.
