### ISSUE TITLE
Source Github: get data from workflow jobs

### ISSUE THREAD

**Issue by Mainara** [airbytehq/airbyte#16360]
## Tell us about the problem you're trying to solve
I'm trying to create a dashboard with detailed metrics about Github Actions (workflows, jobs, steps), however, for that I also need data from [workflow jobs](https://docs.github.com/pt/rest/actions/workflow-jobs).

## Describe the solution you’d like
I would like the Github connector to also bring this information.

## Describe the alternative you’ve considered or used
I think that a search could be done on the [workflow jobs](https://docs.github.com/pt/rest/actions/workflow-jobs) endpoint in the Github api and the connector would get this data.

## Are you willing to submit a PR?
I would like to open a PR with this solution. :smile:

**Comment by natalyjazzviolin** [comment]
@Mainara that sounds great, looking forward to your PR!

**Comment by grubberr** [comment]
@lazebnyi 

I think this can be closed, `Source-Github` already has workflow_jobs stream

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/schemas/workflow_jobs.json

**Comment by lazebnyi** [comment]
Added - https://github.com/airbytehq/airbyte/pull/16534
