### ISSUE TITLE
Airbyte Logs should format tabs and line breaks when displayed

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#16372]
Expanding on https://github.com/airbytehq/airbyte/pull/16317#discussion_r963867856, as all messages passed from Airbyte Connector to Airbyte Platform become well-formed JSON messages, the readability of things like stack traces is reduced.  

All `\r` and `\t` special characters should be rendered properly in our logs.  Maybe there's a setting to enable/disable this per-workspace or sync.

**Comment by salima-airbyte** [comment]
Apparently we have logs reasonably formatted

**Comment by evantahler** [comment]
An example of a stacktrace with `\n` and `\t` being formatted properly can be seen here https://github.com/airbytehq/airbyte/pull/15668#issuecomment-1245180159
