### ISSUE TITLE
Don't allow users to sync a disabled connection

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#16379]
There are currently multiple places in the UI that users can trigger a sync on a disabled connection.  They should not be allowed to.

![Screen Shot 2022-09-06 at 5.01.39 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/b798d804-fceb-41dc-a50d-0ac795bbffb7
)

- There should not be a "launch" button (or it should be disabled) on the `/connections` screen for a disabled connection
- Saving a disabled connection should not trigger a reset sync
- There may be other places

#16380 tracks the related back-end changes for this.  It would be better UX if we remove the buttons before they change the backend behavior, but they aren't really blocking each other.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
@andyjih one of the ways a user can trigger a sync on a disabled connection is by editing the connection configuration and saving it.

So the first question for that part should probably be: Should users be able to reconfigure and save a disabled connection at all?

**Comment by andyjih** [comment]
@tealjulia I do think users should be able to make changes and save a disabled connection, personally. Triggering a sync feels like an exception case to me.
