### ISSUE TITLE
Source Pipedrive: Incremental sync `KeyError: 'update_time'`

### ISSUE THREAD

**Issue by ivanarturosantivanezvela** [airbytehq/airbyte#16376]
## Environment
- **Airbyte version**:   0.40.4
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Pipedrive 0.1.12 
- **Destination Connector and version**:  Postgres 0.3.23 
- **Step where error happened**: Sync job

## Current Behavior
Error trying to sync pipedrive with postgres, possibly due to error to some invalid date format

## Expected Behavior
Successful synchronization

## Logs
[logs-1.txt](https://github.com/airbytehq/airbyte/files/9500323/logs-1.txt)

## Steps to Reproduce
1. Start date sync january first 2022
2. Full sync with all the tables/schemas
3.  Use of api key

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by ivanarturosantivanezvela** [comment]
Thanks!!! It worked

**Comment by vidaletti** [comment]
@YowanR I'd like to work on this issue

**Comment by YowanR** [comment]
Hi @vidaletti! I missed this, my apologies! @sajarin @sh4sh Can you please assign this issue? It's bugging on my side

**Comment by YowanR** [comment]
@ivanarturosantivanezvela Are you still running into this issue?

**Comment by grubberr** [comment]
Fixed in this PR https://github.com/airbytehq/airbyte/pull/24282
