### ISSUE TITLE
Verify connector spec fields with sensitive information are marked as secrets as part of certification process

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#16386]
## Tell us about the problem you're trying to solve
We should verify that that fields with sensitive information are marked as `airbyte_secret` in the spec as part of the certification process to ensure we don't accidentally leak secrets.

## Describe the solution you’d like
We should add a step to the alpha certification process to ensure none of our connectors accidentally leak secrets.

**Comment by YowanR** [comment]
@igrankova @ycherniaiev Can you handle this, please? This needs to be in the criteria in both the alpha checklist and the beta checklist.
@lazebnyi @YuliiaNahoha Can you also make sure that we handle this as part of the GA certification effort coming up?

**Comment by grubberr** [comment]
@YowanR @igrankova @ycherniaiev 
about checklist extension

do we need to add 2 separate row (Category/Criterion) for this problems:

1. HTTPS - checking
2. SPEC "airbyte_secret": "true" - checking

or it's sufficient to add one row (Category/Criterion) for both (1) or (2) problems

**Comment by YowanR** [comment]
We should have 2 separate ros added. 
@igrankova @ycherniaiev Can you look into this?

**Comment by igrankova** [comment]
@YowanR Checklists are updated
CC @ycherniaiev, @grubberr

**Comment by igrankova** [comment]
Adding one more criterion: Check that the connector is on the latest CDK/SAT

**Comment by igrankova** [comment]
@YowanR what about the Destinations? Should we update the checklists for them?
cc @ycherniaiev

**Comment by YowanR** [comment]
I'll defer to @misteryeo here. Should the destination checklists be updated as well?

**Comment by igrankova** [comment]
@YowanR 
Finished adding "Check that the connector is on the latest CDK/SAT" criterion to the source checklists. Waiting for the decision about the Destinations.
cc @ycherniaiev

**Comment by igrankova** [comment]
Updated

**Comment by misteryeo** [comment]
Sorry I missed this, yes this should be applied to both source and destination checklists. And since there was still an open question, we shouldn't have closed this issue. cc: @YowanR

**Comment by igrankova** [comment]
@misteryeo, sorry, Andy, you're right. I missed the question with the destinations. Updating just now.

**Comment by igrankova** [comment]
@misteryeo, The destinations checklists are updated as well. Our Java team checked the criteria and I added the statuses to the checklists.
cc @YowanR

**Comment by YowanR** [comment]
Thanks @igrankova. This looks good to me and since there are no more open questions here, you can close it now :)
