### ISSUE TITLE
Group connector form fields by cards

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16396]
Update the connector form to group certain form fields into cards.

![image.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/b5bf0a76-c52b-4376-884b-5fa423e1e176)

This change requires a change on how the connectors are configured in order for the frontend to understand how to group the fields together.

Design: https://www.figma.com/file/mFVUWYYjDm5zz6FFx8hTP6/FORMS-FIELDS

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
