### ISSUE TITLE
Update design of SingletonCard component, rename to `Toast`

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16397]
The `SingletonCard` is the component that is used to show the notification at the bottom of the screen but it needs a design refresh. Once the design is ready, this component should be updated. This component is also commonly known in other design systems as `Toast`, so it should be renamed.

## TODO
- [ ] Design

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by Upmitt** [comment]
@edmundito - here is a first design for the toast messages (only text messages, no action) - https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=1475%3A2667

**Comment by edmundito** [comment]
Replaced by #18631
