### ISSUE TITLE
Airbyte should fail when instance version doesn't match data version

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1639]
## Tell us about the problem you're trying to solve
* If a user upgrades the version of Airbyte but doesn't run the appropriate migration of the underlying data, then the behavior is undefined and potentially will corrupt data.

## Describe the solution you’d like
* Airbyte should not allow starting up when data version and airbyte version are incompatible.

**Comment by ChristopheDuong** [comment]
in order to handle this, I was thinking of relying on either 
- a separate table for auditing migration/imports events 
- or a simple key/value in the metadata table

https://github.com/airbytehq/airbyte/pull/1633#issuecomment-759737803
