### ISSUE TITLE
Improve database & config migration lifecycle

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#164]
## Tell us about the problem you're trying to solve
Today we don't have a good process to apply db migrations or config migrations. As we iterate on the project that will cause issues to user who want to upgrade to the next version.

## Describe the solution you’d like
Not yet defined, but I am thinking of having a version specific container that runs before any others and applies migrations to the db if necessary.

**Comment by ChristopheDuong** [comment]
Duplicate #1402
