### ISSUE TITLE
Source Mailgun: Missing documentation

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#16402]
The document for Mailgun is not showing, https://docs.airbyte.com/integrations/sources/mailgun

**Comment by natalyjazzviolin** [comment]
@nauxliu thank you for bringing this to our attention! It looks like the doc for the Mailgun connector has not been written yet.

**Comment by btkcodedev** [comment]
@jrlom @natalyjazzviolin I would like to work on this issue
