### ISSUE TITLE
Upgrade json-schema-validator

### ISSUE THREAD

**Issue by ypc-faros** [airbytehq/airbyte#16406]
At the time of writing, Airbyte is using version [1.0.42](https://github.com/airbytehq/airbyte/blob/master/airbyte-json-validation/build.gradle#L6) which is 2+ years old.

I currently have a spec which contains a pretty large `oneOf` (~30 subschemas) and I'm being affected by [this bug](https://github.com/networknt/json-schema-validator/pull/361) in the json-schema-validator library.

**Comment by marcosmarxm** [comment]
Thanks @ypc-faros I added the request to team backlog.
