### ISSUE TITLE
clean up: remove onboardingComplete

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1642]
Now that we have the displaySetupWizard flag we don't need onboardingComplete. Need to remove it from UI and API. This issue is for removing it from the UI.

**Comment by Jamakase** [comment]
This will be already handled by merging #1632 and we figured out that there is no need to do clean up later.

**Comment by cgardens** [comment]
I removed this on the backend as well so this should be complete now on both frontend and backend.
