### ISSUE TITLE
Create a simple routing service and logic

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#16425]
The current routing service create from phase 1 essentially reads a list of connection IDs from a config to figure out which task queue to send jobs to.

This ticket is to create a service that will do the routing in a smarter fashion.

### Routing logic
The routing service's input will be a connection ID. From there, we query the database to get the connection's preferred region and provider. If no region or provider exists, we will check if the workspace of the connection has any preferences. With that information, we will use a very elementary routing logic: 

>
If both cloud provider and region preferences are supplied
- put the job in that specific provider-region task queue
If only cloud provider preference is supplied
- Run the job in any region (default to us), and in the preferred cloud provider
Same as above for region, but vice-versa
- Default to GCP
If no preference
- Default to gcp, us for now.

Assume task queue names are `<provider>-<geography>`. this endpoint will replace the logic in `getDataPlaneForConnection(UUID connectionId)`

**Comment by davinchia** [comment]
@pmossman @xiaohansong I think this is done so I'm closing.
