### ISSUE TITLE
Styled Components -> SCSS Modules for react-select components

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#16439]
I intended to switch to scss modules from styled components in this [issue](https://github.com/airbytehq/airbyte/issues/16023) and this [PR](https://github.com/airbytehq/airbyte/pull/16027) however it ended up being more complicated than the react-select upgrade.

We should change over the `DropDown.tsx` component, as well as the react-select [component wrappers](https://github.com/airbytehq/airbyte/blob/de2035e901a1a6d823b042ef7783f36c5e91ed37/airbyte-webapp/src/components/base/DropDown/DropDown.tsx#L30). [Workspace Popout](airbyte-webapp/src/packages/cloud/views/workspaces/WorkspacePopout/WorkspacePopout.tsx) in the Cloud package needs it, as does [ConnectorServiceTypeControl](https://github.com/airbytehq/airbyte/blob/5e9759bbf34c05dd364dbb6dc66dfe96d9cac127/airbyte-webapp/src/views/Connector/ServiceForm/components/Controls/ConnectorServiceTypeControl.tsx), [Sync Settings Dropdown](https://github.com/airbytehq/airbyte/blob/504389af32f92f948b1aa5d2c88c95e09f5e9030/airbyte-webapp/src/views/Connection/CatalogTree/components/SyncSettingsDropdown.tsx), and [Popout](https://github.com/airbytehq/airbyte/blob/42c5265d0d24b4d53aee403c4f0ff1a81688cd40/airbyte-webapp/src/components/base/Popout/Popout.tsx).
[Custom Select](https://github.com/airbytehq/airbyte/blob/e2e6aaeae7e79ed9f36d5a14c4f86a9d9e8ef46e/airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx) should go entirely as it's just a styled wrapper around react-select's Select.

_Alternatively_ we could pull out all of the react-select and instead use [Listbox](https://headlessui.com/react/listbox) from Headless UI.

I feel either option will be an undertaking.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Note: we don't want to switch to Headless for the DropDown component. react-select is significantly more powerful and we're using features like search in the dropdown that Headless UI does not offer. (I adjusted the title accordingly)

**Comment by davinchia** [comment]
@chandlerprall what is the status of this?

**Comment by timroes** [comment]
@davinchia we're still converting over. There's though no hard timeline nor are we trying to focus on this. We're basically converting components whenever we anyway touch them. We're not planning to do any specific pike to get rid of styled components soon.

**Comment by timroes** [comment]
I think we can close this, since the components based on react select are deprecated, and we plan to only use the headlessui components going forward.
