### ISSUE TITLE
🎨 Sticky table headers

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#16435]
When pairing with Nico last week, he asked that we do sticky table headers (IE: when you scroll, you always have the headers visible).  Tried a few things and it looks like it may take some work or creativity to nail this across browsers and with the border-radius we have on the headers.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
@Upmitt this ended up being a bit bigger than the changes we usually pair on, so I've split it into its own issue to get into our backlog.

**Comment by edmundito** [comment]
This work has already been done and now all tables have sticky headers.
