### ISSUE TITLE
Source Okta: Don't mark domain as a secret

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#16459]
## Current Behavior
Okta connector labels the `domain` as a secret
<img width="682" alt="Screen Shot 2022-09-08 at 11 09 31 AM" src="https://user-images.githubusercontent.com/6246757/189194986-fcc45525-5aab-428f-be94-4bcd5c8e7f05.png">

## Expected Behavior
It should not be labelled as a secret.

However, I'm not sure this is a safe operation to do. We need to confirm with the Platform Workflow team if it is safe to revert the status of a field from `secret`, since secrets are stored separately in GSM and are only resolved at sync job runtime.

**Comment by YowanR** [comment]
@evantahler Could you help us here? Is it safe to revert a field from secret? (I'm hoping you are the right person to ask this question). For context, we're pushing this connector to GA by end of Quarter so I'd like to resolve this issue asap.

**Comment by evantahler** [comment]
In the future, @salima-airbyte is the person to tag!  But... I don't personally know the answer, so we'll need to ask the team to look into this.  I also imagine there might be complications on cloud, moving things from the secret store to the regular config database...

**Comment by benmoriceau** [comment]
Hello @YowanR,
Do you know how many connection are using Okta in the source and in OSS? If the number is low enough, we will try to have a manual approach. Otherwise we will need to do an automatic migration.

**Comment by salima-airbyte** [comment]
More follow up Benoit --> YowanR today.

**Comment by YowanR** [comment]
Hi @benmoriceau and @salima-airbyte! Does [this](https://airbyte.metabaseapp.com/question?connector_pattern=okta#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJuYXRpdmUiOnsidGVtcGxhdGUtdGFncyI6eyJjb25uZWN0b3JfcGF0dGVybiI6eyJpZCI6ImUzYTY5MjU2LWY0M2ItNGQzYS1hOWQ0LTUzNGRiZjEyODI3OCIsIm5hbWUiOiJjb25uZWN0b3JfcGF0dGVybiIsImRpc3BsYXktbmFtZSI6IkNvbm5lY3RvciBwYXR0ZXJuIiwidHlwZSI6InRleHQifSwib2ZmaWNpYWxfc3RhdHVzIjp7ImlkIjoiZTEzMDU4ODQtNzVjNi1mYWNkLWMwZDQtOGMyN2NjZWE0YjRmIiwibmFtZSI6Im9mZmljaWFsX3N0YXR1cyIsImRpc3BsYXktbmFtZSI6Ik9mZmljaWFsIHN0YXR1cyIsInR5cGUiOiJkaW1lbnNpb24iLCJkaW1lbnNpb24iOlsiZmllbGQiLDI1NzAwLG51bGxdLCJ3aWRnZXQtdHlwZSI6InN0cmluZy89IiwiZGVmYXVsdCI6bnVsbH19LCJxdWVyeSI6IndpdGhcbnNlbGVjdGVkX3N0YXR1c19kYXRhIGFzIChcbiAgICBzZWxlY3QgZGlzdGluY3Qgb2ZmaWNpYWxfc3RhdHVzIGFzIHNlbGVjdGVkX3N0YXR1c1xuICAgIGZyb20gYGFpcmJ5dGVfd2FyZWhvdXNlLmNvbm5lY3Rvcl9xdWFsaXR5YFxuIFtbIHdoZXJlIHt7IG9mZmljaWFsX3N0YXR1cyB9fSBdXVxuKSxcblxuY29ubmVjdG9yX3F1YWxpdHlfZGF0YSBhcyAoXG4gICAgc2VsZWN0IGNvbm5lY3Rvci4qXG4gICAgZnJvbSBgYWlyYnl0ZV93YXJlaG91c2UuY29ubmVjdG9yX3F1YWxpdHlgIGFzIGNvbm5lY3RvclxuICAgIGlubmVyIGpvaW4gc2VsZWN0ZWRfc3RhdHVzX2RhdGFcbiAgICAgICAgb24gY29ubmVjdG9yLm9mZmljaWFsX3N0YXR1cyA9IHNlbGVjdGVkX3N0YXR1c19kYXRhLnNlbGVjdGVkX3N0YXR1c1xuICAgICAgICAgICAgb3IgY29ubmVjdG9yLnEzX2dvYWwgPSBzZWxlY3RlZF9zdGF0dXNfZGF0YS5zZWxlY3RlZF9zdGF0dXNcbiAgICB3aGVyZSAxID0gMVxuICAgICBbWyBhbmQgKFxuICAgICAgICAgbG93ZXIoY29ubmVjdG9yLmRvY2tlcl9yZXBvc2l0b3J5KSBsaWtlIGNvbmNhdCgnJScsIGxvd2VyKHt7IGNvbm5lY3Rvcl9wYXR0ZXJuIH19KSwgJyUnKVxuICAgICAgb3IgbG93ZXIoY29ubmVjdG9yLmNvbm5lY3Rvcl9uYW1lKSBsaWtlIGNvbmNhdCgnJScsIGxvd2VyKHt7IGNvbm5lY3Rvcl9wYXR0ZXJuIH19KSwgJyUnKSkgXV1cbiAgICBxdWFsaWZ5IHJvd19udW1iZXIoKSBvdmVyIChcbiAgICAgICAgcGFydGl0aW9uIGJ5IGNvbm5lY3Rvci5jb25uZWN0b3JfdHlwZSwgY29ubmVjdG9yLmNvbm5lY3Rvcl9kZWZpbml0aW9uX2lkXG4gICAgICAgIG9yZGVyIGJ5IHNlbGVjdGVkX3N0YXR1c19kYXRhLnNlbGVjdGVkX3N0YXR1cyBkZXNjXG4gICAgKSA9IDFcbilcblxuXG5zZWxlY3RcbiAgICBjb25uZWN0b3JfY2F0ZWdvcnksXG4gICAgY29uY2F0KGNvbm5lY3Rvcl90eXBlLCBcIi1cIiwgY29ubmVjdG9yX25hbWUpIGFzIGNvbm5lY3Rvcl9uYW1lLFxuICAgIHFhX3N0YXR1cyxcbiAgICBwcmVkaWN0ZWRfcWFfc3RhdHVzLFxuICAgIC0tIFRPRE86IGluY2x1ZGUgT1NTIHN0YXR1cyB2cyBjdXN0b20gY29ubmVjdG9yXG4gICAgb2ZmaWNpYWxfc3RhdHVzIGFzIGNsb3VkX3N0YXR1cyxcbiAgICBxM19nb2FsIGFzIHRhcmdldF9zdGF0dXMsXG5cbiAgICBhdmdfc3VjY2VlZGVkX2Nvbm5lY3Rpb25fcmF0aW9fMncsXG4gICAgY2xvdWRfYXZnX3N1Y2NlZWRlZF9jb25uZWN0aW9uX3JhdGlvXzJ3LFxuICAgIGluaXRpYWxfY29ubmVjdG9yX3N5bmNfMndfc3VjY2Vzc19yYXRpbyxcbiAgICBpbml0aWFsX2Nsb3VkX2Nvbm5lY3Rvcl9zeW5jXzJ3X3N1Y2Nlc3NfcmF0aW8sXG5cbiAgICB3b3Jrc3BhY2VfY291bnRfMncsXG4gICAgY2xvdWRfd29ya3NwYWNlX2NvdW50XzJ3LFxuXG4gICAgaW5pdGlhbF9jb25uZWN0b3Jfc3luY193b3Jrc3BhY2VfY291bnRfMncsXG4gICAgaW5pdGlhbF9jbG91ZF9jb25uZWN0b3Jfc3luY193b3Jrc3BhY2VfY291bnRfMncsXG5cbiAgICBvZmZpY2lhbF9zdGF0dXNfY2hlY2ssXG4gICAgcHJlZGljdGVkX29mZmljaWFsX3N0YXR1c19jaGVjayxcbiAgICBjb25uZWN0b3JfZGVmaW5pdGlvbl9pZFxuZnJvbSBjb25uZWN0b3JfcXVhbGl0eV9kYXRhXG5cbm9yZGVyIGJ5XG4gICAgY2xvdWRfd29ya3NwYWNlX2NvdW50XzJ3IGRlc2MsXG4gICAgd29ya3NwYWNlX2NvdW50XzJ3IGRlc2MsXG4gICAgY29ubmVjdG9yX25hbWUgYXNjXG4ifSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInBhcmFtZXRlcnMiOlt7ImlkIjoiZTNhNjkyNTYtZjQzYi00ZDNhLWE5ZDQtNTM0ZGJmMTI4Mjc4IiwidHlwZSI6ImNhdGVnb3J5IiwidGFyZ2V0IjpbInZhcmlhYmxlIixbInRlbXBsYXRlLXRhZyIsImNvbm5lY3Rvcl9wYXR0ZXJuIl1dLCJuYW1lIjoiQ29ubmVjdG9yIHBhdHRlcm4iLCJzbHVnIjoiY29ubmVjdG9yX3BhdHRlcm4ifSx7ImlkIjoiZTEzMDU4ODQtNzVjNi1mYWNkLWMwZDQtOGMyN2NjZWE0YjRmIiwidHlwZSI6InN0cmluZy89IiwidGFyZ2V0IjpbImRpbWVuc2lvbiIsWyJ0ZW1wbGF0ZS10YWciLCJvZmZpY2lhbF9zdGF0dXMiXV0sIm5hbWUiOiJPZmZpY2lhbCBzdGF0dXMiLCJzbHVnIjoib2ZmaWNpYWxfc3RhdHVzIiwiZGVmYXVsdCI6bnVsbH1dLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLnBpdm90X2NvbHVtbiI6Im9mZmljaWFsX3N0YXR1cyIsInRhYmxlLmNlbGxfY29sdW1uIjoiY2xvdWRfY29ubmVjdG9yX3ZlcnNpb24iLCJ0YWJsZS5jb2x1bW5fZm9ybWF0dGluZyI6W3siY29sdW1ucyI6WyJwcmVkaWN0ZWRfb2ZmaWNpYWxfc3RhdHVzX2NoZWNrIl0sInR5cGUiOiJzaW5nbGUiLCJvcGVyYXRvciI6Ij0iLCJ2YWx1ZSI6IkZBSUwiLCJjb2xvciI6IiNFRjhDOEMiLCJoaWdobGlnaHRfcm93IjpmYWxzZX0seyJjb2x1bW5zIjpbInByZWRpY3RlZF9vZmZpY2lhbF9zdGF0dXNfY2hlY2siXSwidHlwZSI6InNpbmdsZSIsIm9wZXJhdG9yIjoiPSIsInZhbHVlIjoiUEFTUyIsImNvbG9yIjoiIzg4QkY0RCIsImhpZ2hsaWdodF9yb3ciOmZhbHNlfSx7ImNvbHVtbnMiOlsib2ZmaWNpYWxfc3RhdHVzX2NoZWNrIl0sInR5cGUiOiJzaW5nbGUiLCJvcGVyYXRvciI6Ij0iLCJ2YWx1ZSI6IkZBSUwiLCJjb2xvciI6IiNFRjhDOEMiLCJoaWdobGlnaHRfcm93Ijp0cnVlfSx7ImNvbHVtbnMiOlsib2ZmaWNpYWxfc3RhdHVzX2NoZWNrIl0sInR5cGUiOiJzaW5nbGUiLCJvcGVyYXRvciI6Ij0iLCJ2YWx1ZSI6IlBBU1MiLCJjb2xvciI6IiM4OEJGNEQiLCJoaWdobGlnaHRfcm93Ijp0cnVlfSx7ImNvbHVtbnMiOlsib2ZmaWNpYWxfc3RhdHVzIiwicTJfZ29hbCIsInFhX3N0YXR1cyIsImNsb3VkX3N0YXR1cyIsInRhcmdldF9zdGF0dXMiLCJwcmVkaWN0ZWRfcWFfc3RhdHVzIl0sInR5cGUiOiJzaW5nbGUiLCJvcGVyYXRvciI6Ij0iLCJ2YWx1ZSI6IkFscGhhIiwiY29sb3IiOiIjRUY4QzhDIiwiaGlnaGxpZ2h0X3JvdyI6ZmFsc2V9LHsiY29sdW1ucyI6WyJvZmZpY2lhbF9zdGF0dXMiLCJxMl9nb2FsIiwicWFfc3RhdHVzIiwiY2xvdWRfc3RhdHVzIiwidGFyZ2V0X3N0YXR1cyIsInByZWRpY3RlZF9xYV9zdGF0dXMiXSwidHlwZSI6InNpbmdsZSIsIm9wZXJhdG9yIjoiPSIsInZhbHVlIjoiQmV0YSIsImNvbG9yIjoiIzUwOUVFMyIsImhpZ2hsaWdodF9yb3ciOmZhbHNlfSx7ImNvbHVtbnMiOlsib2ZmaWNpYWxfc3RhdHVzIiwicTJfZ29hbCIsInFhX3N0YXR1cyIsImNsb3VkX3N0YXR1cyIsInRhcmdldF9zdGF0dXMiLCJwcmVkaWN0ZWRfcWFfc3RhdHVzIl0sInR5cGUiOiJzaW5nbGUiLCJvcGVyYXRvciI6Ij0iLCJ2YWx1ZSI6IkdBIiwiY29sb3IiOiIjODhCRjREIiwiaGlnaGxpZ2h0X3JvdyI6ZmFsc2V9XSwidGFibGUuY29sdW1ucyI6W3sibmFtZSI6ImNvbm5lY3Rvcl9jYXRlZ29yeSIsImZpZWxkUmVmIjpbImZpZWxkIiwiY29ubmVjdG9yX2NhdGVnb3J5Iix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY29ubmVjdG9yX25hbWUiLCJmaWVsZFJlZiI6WyJmaWVsZCIsImNvbm5lY3Rvcl9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoicWFfc3RhdHVzIiwiZmllbGRSZWYiOlsiZmllbGQiLCJxYV9zdGF0dXMiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJwcmVkaWN0ZWRfcWFfc3RhdHVzIiwiZmllbGRSZWYiOlsiZmllbGQiLCJwcmVkaWN0ZWRfcWFfc3RhdHVzIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY2xvdWRfc3RhdHVzIiwiZmllbGRSZWYiOlsiZmllbGQiLCJjbG91ZF9zdGF0dXMiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJ0YXJnZXRfc3RhdHVzIiwiZmllbGRSZWYiOlsiZmllbGQiLCJ0YXJnZXRfc3RhdHVzIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiYXZnX3N1Y2NlZWRlZF9jb25uZWN0aW9uX3JhdGlvXzJ3IiwiZmllbGRSZWYiOlsiZmllbGQiLCJhdmdfc3VjY2VlZGVkX2Nvbm5lY3Rpb25fcmF0aW9fMnciLHsiYmFzZS10eXBlIjoidHlwZS9GbG9hdCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY2xvdWRfYXZnX3N1Y2NlZWRlZF9jb25uZWN0aW9uX3JhdGlvXzJ3IiwiZmllbGRSZWYiOlsiZmllbGQiLCJjbG91ZF9hdmdfc3VjY2VlZGVkX2Nvbm5lY3Rpb25fcmF0aW9fMnciLHsiYmFzZS10eXBlIjoidHlwZS9GbG9hdCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoid29ya3NwYWNlX2NvdW50XzJ3IiwiZmllbGRSZWYiOlsiZmllbGQiLCJ3b3Jrc3BhY2VfY291bnRfMnciLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJjbG91ZF93b3Jrc3BhY2VfY291bnRfMnciLCJmaWVsZFJlZiI6WyJmaWVsZCIsImNsb3VkX3dvcmtzcGFjZV9jb3VudF8ydyIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6Im9mZmljaWFsX3N0YXR1c19jaGVjayIsImZpZWxkUmVmIjpbImZpZWxkIiwib2ZmaWNpYWxfc3RhdHVzX2NoZWNrIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoicHJlZGljdGVkX29mZmljaWFsX3N0YXR1c19jaGVjayIsImZpZWxkUmVmIjpbImZpZWxkIiwicHJlZGljdGVkX29mZmljaWFsX3N0YXR1c19jaGVjayIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImNvbm5lY3Rvcl9kZWZpbml0aW9uX2lkIiwiZmllbGRSZWYiOlsiZmllbGQiLCJjb25uZWN0b3JfZGVmaW5pdGlvbl9pZCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImluaXRpYWxfY29ubmVjdG9yX3N5bmNfMndfc3VjY2Vzc19yYXRpbyIsImZpZWxkUmVmIjpbImZpZWxkIiwiaW5pdGlhbF9jb25uZWN0b3Jfc3luY18yd19zdWNjZXNzX3JhdGlvIix7ImJhc2UtdHlwZSI6InR5cGUvRmxvYXQifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImluaXRpYWxfY2xvdWRfY29ubmVjdG9yX3N5bmNfMndfc3VjY2Vzc19yYXRpbyIsImZpZWxkUmVmIjpbImZpZWxkIiwiaW5pdGlhbF9jbG91ZF9jb25uZWN0b3Jfc3luY18yd19zdWNjZXNzX3JhdGlvIix7ImJhc2UtdHlwZSI6InR5cGUvRmxvYXQifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImluaXRpYWxfY29ubmVjdG9yX3N5bmNfd29ya3NwYWNlX2NvdW50XzJ3IiwiZmllbGRSZWYiOlsiZmllbGQiLCJpbml0aWFsX2Nvbm5lY3Rvcl9zeW5jX3dvcmtzcGFjZV9jb3VudF8ydyIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImluaXRpYWxfY2xvdWRfY29ubmVjdG9yX3N5bmNfd29ya3NwYWNlX2NvdW50XzJ3IiwiZmllbGRSZWYiOlsiZmllbGQiLCJpbml0aWFsX2Nsb3VkX2Nvbm5lY3Rvcl9zeW5jX3dvcmtzcGFjZV9jb3VudF8ydyIseyJiYXNlLXR5cGUiOiJ0eXBlL0ludGVnZXIifV0sImVuYWJsZWQiOnRydWV9XSwiY29sdW1uX3NldHRpbmdzIjp7IltcIm5hbWVcIixcInFhX3N0YXR1c1wiXSI6eyJjb2x1bW5fdGl0bGUiOiJRQSBTdGF0dXMgKDJ3KSJ9LCJbXCJuYW1lXCIsXCJwcmVkaWN0ZWRfcWFfc3RhdHVzXCJdIjp7ImNvbHVtbl90aXRsZSI6IkZ1dHVyZSBTdGF0dXMgKDNkKSJ9LCJbXCJuYW1lXCIsXCJjbG91ZF9zdGF0dXNcIl0iOnsiY29sdW1uX3RpdGxlIjoiT2ZmaWNpYWwgQ2xvdWQgU3RhdHVzIn0sIltcIm5hbWVcIixcInRhcmdldF9zdGF0dXNcIl0iOnsiY29sdW1uX3RpdGxlIjoiVGFyZ2V0IFN0YXR1cyJ9fX0sIm9yaWdpbmFsX2NhcmRfaWQiOjMxNH0=) help?

**Comment by benmoriceau** [comment]
Thanks @YowanR, yes it is helping. If I understand well there is only one client using it, right? If so, is it ok to ask for a manual action once we make this field a non secret field

Is it possible to have a similar data for OSS users?

**Comment by benmoriceau** [comment]
Turns out it was done already
