### ISSUE TITLE
[Dup] Move connector create/save button outside of the card

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16469]
In the source or destination create pages, the submit button is placed inside the card:

![image.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/789bc71f-a810-48a4-b817-5e370b0c98c9)

The change proposed is to move the button outside of the card to match the current design:
![image.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/c4152e83-648c-4368-bbfc-f28279c07591)

Prototype:
https://www.figma.com/proto/mFVUWYYjDm5zz6FFx8hTP6/FORMS-FIELDS?page-id=1%3A4&node-id=301%3A10567&viewport=606%2C64%2C0.16&scaling=min-zoom&starting-point-node-id=301%3A10567

In the source settings, the save and delete buttons also move. See in design:
https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?node-id=222%3A2479

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
