### ISSUE TITLE
Appsflyer Connector

### ISSUE THREAD

**Issue by Muriloo** [airbytehq/airbyte#1649]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
The goal is to integrate data from Appsflyer reports on a daily basis. Fetching data until D-1

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
The Appsflyer integration is used by the marketing team to analyze the performance of marketing campaigns, for example: how many install and purchases each campaign is bringing for the mobile apps.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
I want to use the current [Singer tap](https://github.com/singer-io/tap-appsflyer) in Airbyte.

**Comment by Muriloo** [comment]
Hi Airbytem team! I'm gonna work on this integration, and I send you a PR, ok?

**Comment by cgardens** [comment]
nice! go for it.

**Comment by cgardens** [comment]
closed by: https://github.com/airbytehq/airbyte/pull/2544
