### ISSUE TITLE
[Cloud Onboarding UI] Update font colour for Authentication confirmation copy

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16507]
<img width="1476" alt="189242057-57faf827-87ff-4f1c-b792-ba83b35f4368" src="https://user-images.githubusercontent.com/7691812/189245569-30b6ba58-f691-43d2-9c81-6d1f38379acd.png">

**Suggestion:**
“Authentication succeeded!” (#67DAE1) could have its font color updated to the Airbyte purple (#615EFF)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
This color is at the moment our success color. Cc @Upmitt in case you want to do a change to our color palette, but will close this issue as an individual place to update, and of you want to change the color palette please feel free to open a more general issue for a color palette update.

**Comment by edmundito** [comment]
Forwarded this to @Upmitt in Asana to see if there's some improvement to this.
