### ISSUE TITLE
[Cloud Onboarding UI] Enlarge source list

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16506]
<img width="809" alt="CleanShot 2022-09-08 at 16 12 32@2x" src="https://user-images.githubusercontent.com/7691812/189241582-a9ddd8d4-df92-4f32-9db5-da7f804ab49d.png">

**Suggestion:**
This dropdown could be longer (there is vertical space on the page) and could also be “embedded” into the page rather than a small dropdown window (saving initial click to trigger dropdown) (GH issue)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Onboarding UI has been removed.
