### ISSUE TITLE
[Cloud Onboarding UI] Vertically align stream setting columns

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16508]
<img width="1355" alt="CleanShot 2022-09-08 at 09 18 09@2x" src="https://user-images.githubusercontent.com/7691812/189242295-a0f02e16-1624-4690-9081-b6cc930306c7.png">

![CleanShot 2022-09-08 at 09 19 34@2x](https://user-images.githubusercontent.com/7691812/189242408-0486d709-0395-4573-bd8f-8d5d1c63bc9e.png)

**Suggestion:**
Column titles could be aligned vertically with each other also...not sure **this many rows of titles is necessary**?

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
We're doing at the moment a full redesign of that connection page. Going to close this in favor of the overall redesign of that page.
