### ISSUE TITLE
[Frontend] Tables should be full width on all pages

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16512]
Example of Vertically Aligned (good)
![CleanShot 2022-09-08 at 10 12 05@2x](https://user-images.githubusercontent.com/7691812/189243530-122aade1-294b-48cf-b493-b9a9920c5b6a.png)

Example of Not Vertically Aligned (bad)
![CleanShot 2022-09-08 at 10 15 47@2x](https://user-images.githubusercontent.com/7691812/189243577-acdaaadf-6cfd-4bfc-ac94-ed4be3a7357f.png)

UI nitpick: There are UI components vertically aligned with the tables in some views (Sources/Sources Overview) -  but not in other views (Sources plus others). These should be consistently vertically aligned.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
