### ISSUE TITLE
[Cloud Onboarding UI] Ensure tab placement consistent across all Cloud UI views

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16511]
![CleanShot 2022-09-08 at 09 49 44@2x](https://user-images.githubusercontent.com/7691812/189243151-a3b11324-4eca-41e9-b9cd-674ff4d56c0d.png)

![CleanShot 2022-09-08 at 09 33 29@2x](https://user-images.githubusercontent.com/7691812/189243161-54ef39c1-f087-4394-83dc-ec19af71f7d3.png)

UI nitpick: Tabs at top of screen for Sources & Destination details view, but not at top of screen within Connection details view.

**Suggestion:** Keep the tabs at top of screen, across all views.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
@Upmitt I'll close this for now as not planned. Please feel free to reopen with some Figmas if we would like to do a redesign of those pages.
