### ISSUE TITLE
[Settings] Enhance information details for "Advanced Mode"

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#16516]
![CleanShot 2022-09-08 at 10 23 22@2x](https://user-images.githubusercontent.com/7691812/189244591-70044ef6-6ea7-442d-be89-d94e0c6c4b38.png)

Tooltip for "Advanced Mode" reads: "...certain views will display additional technical information" - which could leave a user wondering: “_okay…but what kind of additional technical information?_”

**Suggestion**: Could be an opportunity to insert a “Learn more” link to documentation (within the tooltip). That documentation would explain what additional information is populated by "Advanced Mode", and what views that information will be populated in.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@Amruta-Ranade For us to add this, we'd need to create a new page in the docs to explain what advanced mode is. Could you help us with this?

**Comment by Amruta-Ranade** [comment]
@edmundito Happy to help! Should we set up some time to discuss it?

**Comment by matter-q** [comment]
After the conversation with @Amruta-Ranade, we decided to move the task to on hold 

_"Advanced mode doesn't have much to show yet, only that it shows the state of the connection in the connections settings. Don't think we need docs for it just yet"_

**Comment by edmundito** [comment]
No longer needed because of #21914
