### ISSUE TITLE
Source Paypal: TypeError("__init__() missing 2 required positional arguments: 'client_id' and 'client_secret'")

### ISSUE THREAD

**Issue by awoehrl** [airbytehq/airbyte#16524]
## Environment
- **Airbyte version**:  0.40.3
- **OS Version / Instance**: Ubuntu
- **Deployment**: Docker
- **Source Connector and version**: Paypal Transactions 0.1.9
- **Destination Connector and version**: ---
- **Step where error happened**: Setup Source

## Current Behavior
When trying to setup the source, I get an error. Both arguments are set correctly in the UI though

`TypeError("__init__() missing 2 required positional arguments: 'client_id' and **'client_secret'")`**

## Expected Behavior
Source setup should work.

## Steps to Reproduce
1. New Source Paypal
2. Put your credentials in
3. Click Test Connection

**Comment by YowanR** [comment]
@arsenlosenko Can you look into this bug? We need to fix this before we can move to GA -- thanks! 🙏 
cc @lazebnyi @YuliiaNahoha

**Comment by arsenlosenko** [comment]
@awoehrl Hello, I have tried to reproduce your issue, but was not able to do so, can you please try to set up this connector on the latest version of Airbyte (I see that version where you reported the issue is 0.40.3, while the latest version of Airbyte OSS is 0.40.10). Please let me know, if you managed to test the setup of connector, or if you have any other questions.

**Comment by awoehrl** [comment]
Hi,
I just tried to set it up with a new source connector being on Airbyte 40.0.10 and Paypal 0.1.9. The error persists however. I can't setup a source because of the type error.

What works on the other hand is using Paypal 0.1.6 for the setup and upgrading this connector then to 0.1.9.

**Comment by arsenlosenko** [comment]
@awoehrl thanks for testing and giving your feedback, it is really helpful, going to debug this issue using those versions. Will come back to you if there are any updates.

**Comment by YowanR** [comment]
@awoehrl It seems that we had a fix that should solve this issue. Can you let us know if you're unblocked now? cc @arsenlosenko

**Comment by arsenlosenko** [comment]
@awoehrl please use the latest version of this connector, which is 0.1.10, and please reach out to us back if the fix works for you

**Comment by awoehrl** [comment]
@arsenlosenko thank you very much, I can confirm it works now as expected.

**Comment by arsenlosenko** [comment]
@awoehrl awesome, glad we have helped you
