### ISSUE TITLE
Update JDBC driver for Snowflake source

### ISSUE THREAD

**Issue by ryjabe** [airbytehq/airbyte#16552]
## Current Behavior
Per this [build](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/build.gradle), Airbyte is currently using version 3.13.9 of the JDBC drive for Snowflake.  That driver is almost a year old and should be updated to the latest version 3.13.22, as of the creation of this ticket.   We should consider updating our driver as well as putting in a mechanism to keep it updated on an ongoing basis.  

Link for the repo with all of the drivers:
https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/16552?planning-poker) with Zenhub @akashkulk @edgao @ryankfu @subodh1810 @tuliren
