### ISSUE TITLE
Helm Chart: duplicated minio resources

### ISSUE THREAD

**Issue by milesarmstrong** [airbytehq/airbyte#16586]
## Environment
- **Airbyte version**:  [0.40.4](https://github.com/airbytehq/airbyte/releases/tag/v0.40.4)
- **Helm Version**: [0.42.0](https://github.com/airbytehq/helm-charts/blob/main/airbyte-0.42.0.tgz)
- **Deployment**: Kubernetes (with Helm chart via ArgoCD)

## Current Behavior
Since https://github.com/airbytehq/airbyte/pull/16131, there is a new [set of minio resources](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/minio.yaml) in the main airbyte helm chart that:

- Can't be disabled, they are always deployed - this causes conflicts with the bitnami minio chart.
- Aren't suitably configurable to be used as a replacement for the bitnami minio chart, e.g. I need to set annotations on the minio Service, which the bitnami chart supports but the new resources don't.

## Expected Behavior
I should be able to choose whether to run the bitnami minio chart, or the bundled minio deployment, so that they don't conflict.

New enabled-by-default resources shouldn't be included in Helm chart releases if they conflict with existing resources, without a documented migration path.

## Steps to Reproduce
1. In https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/Chart.yaml, replace `placeholder` versions with `0.42.0`
2. Run `helm dependency build`
3. Run `helm template airbyte . --values values.yaml`
4. Observe that even though [`global.logs.minio.enabled`](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/values.yaml#L41) is true, enabling the bitnami minio chart, its Deployment isn't present in the output, it is overwritten by [this Deployment.](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/minio.yaml)

## Are you willing to submit a PR?
No, I think https://github.com/airbytehq/airbyte/pull/16131 should be reverted as it appears there were [concerns about it](https://github.com/airbytehq/airbyte/pull/16131#pullrequestreview-1101651108), and it has caused other issues, e.g. https://github.com/airbytehq/airbyte/issues/16535, https://github.com/airbytehq/airbyte/issues/16586

**Comment by marcosmarxm** [comment]
@xpuska513 this is solved?

**Comment by marcosmarxm** [comment]
This was tested in latest version and minio is not duplicated. Please open a new issue if you face the problem again.
