### ISSUE TITLE
Helm Chart: duplicated postgres resources

### ISSUE THREAD

**Issue by milesarmstrong** [airbytehq/airbyte#16587]
## Environment
- **Airbyte version**:  [0.40.4](https://github.com/airbytehq/airbyte/releases/tag/v0.40.4)
- **Helm Version**: [0.42.0](https://github.com/airbytehq/helm-charts/blob/main/airbyte-0.42.0.tgz)
- **Deployment**: Kubernetes (with Helm chart via ArgoCD)

## Current Behavior
Since https://github.com/airbytehq/airbyte/pull/16131, there is a new [set of postgres resources](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/airbyte-db.yaml) in the main airbyte helm chart that:

- Are [enabled](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/airbyte-db.yaml#L1) by the `postgresql.enabled` flag in [values.yaml](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/values.yaml#L1192).
- Conflict with the bitnami postgresql chart which is also [enabled](https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/Chart.yaml#L32-L35) by the `postgresql.enabled` flag.

This conflict appears to cause the airbyte database to be wiped on every startup. On upgrading to this version of the Helm chart it appears our existing airbyte database was wiped.

## Expected Behavior
I should be able to choose whether to run the bitnami postgresql chart, or the bundled postgresql deployment, so that they don't conflict.

Breaking changes that have a risk of data loss should have clear migration instructions and be clearly communicated.

## Steps to Reproduce
1. In https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/Chart.yaml, replace `placeholder` versions with `0.42.0`
2. Run `helm dependency build`
3. Run `helm template airbyte . --values values.yaml`
4. Observe that there is both an `airbyte-db` Deployment, and an `airbyte-postgresql` StatefulSet.

## Are you willing to submit a PR?
No, I think https://github.com/airbytehq/airbyte/pull/16131 should be reverted as it appears there were [concerns about it](https://github.com/airbytehq/airbyte/pull/16131#pullrequestreview-1101651108), and it has caused other issues, e.g. https://github.com/airbytehq/airbyte/issues/16535, https://github.com/airbytehq/airbyte/issues/16586

**Comment by rcheatham-q** [comment]
If there is a way to upvote this, I would. #16131 should never have been merged, it also wrecked my deployment - fortunately it was a staging deployment, but it sounds like people are suffering data loss as a result of that bad merge.

**Comment by milesarmstrong** [comment]
**Update**: our existing database wasn't wiped, airbyte was just switched to use the new, empty, `airbyte-db` Deployment. When we rolled back to an older helm chart which used the `airbyte-postgresql` StatefulSet the data was still there.

I do however think that the `airbyte-db` Deployment was being wiped on every deployment, as we'd see the welcome screen that asks for email and analytics every time we re-deployed.

**Comment by navi86** [comment]
@milesarmstrong 
yes, I have the same issue, therefore basically is not possible to migrate from chart version 0.40.4 to any higher.

**Comment by xpuska513** [comment]
Hi @milesarmstrong , this issue was already addressed and published in latest release of 0.40.14

**Comment by xpuska513** [comment]
Can you try to migrate from the old one to the latest release?

**Comment by navi86** [comment]
@xpuska513 
sorry, how this is fixed here:
https://github.com/airbytehq/airbyte/pull/17516/files
it's basically removed old postgresql and create a new one. so it means during upgrade user from old version chart will lose all of it's old configuration. Correct me if I am wrong, pls

**Comment by navi86** [comment]
@xpuska513 
moreover, airbyte-deb fails to start with error
```
2022-10-04 09:18:15.262 UTC [52] STATEMENT:  GRANT ALL ON
	DATABASE airbyte TO docker;
psql:/docker-entrypoint-initdb.d/000_init.sql:12: ERROR:  role "docker" does not exist
```
how to properly upgrade without creating this role manually ?

**Comment by navi86** [comment]
@xpuska513 
have you had chance to discuss it ?

**Comment by navi86** [comment]
@xpuska513 do you have any update ?

**Comment by xpuska513** [comment]
Hi!
You can use `0.40.20` version as it contains all latest updates.
We just moved everything into StatefulSet(DB + Minio) so it'll preserve data just in case.
Also removed bitnami deps(except the `common` since it's just a library chart)

**Comment by xpuska513** [comment]
FYI: @navi86

**Comment by navi86** [comment]
@xpuska513 
this issue was opened because bitnami database was not used anymore and therefore after update airbyte is empty
can you explain, how it was solved in latest chart ?

**Comment by navi86** [comment]
@xpuska513 
I was trying last chela chart with old bitnami Postgresql service and got the following error
```
2022-10-19 17:17:26 ERROR o.f.c.i.l.s.Slf4jLog(error):57 - Migration of schema "public" to version "0.40.12.001 - AddWebhookOperationColumns" failed! Changes successfully rolled back.
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration failed !
```
in pod "airbyte-bootloader". How properly upgrade to latest version with old database/external database ?

**Comment by xpuska513** [comment]
I'll work on a solution for migrating data from old one to a new one, I'll let you know once it's ready.
In a meantime you can try pg-migrate or just simply dumping db from old deployment and then restoring it on the new one(using postgres built-in tools)

**Comment by marcosmarxm** [comment]
@xpuska513 this is solved?

**Comment by marcosmarxm** [comment]
Latest version of Airbyte Helm chart doesn't duplicated the postgres resouce. @milesarmstrong feel free to open a new issue if you face the problem again.
