### ISSUE TITLE
Service Form should not say "Re-Authenticate" for new connectors

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#16599]
I'd already Oauthed in to Google to create a google sheets source.  I went to create another one and it said "re-authenticate" so I assumed it would re-use the auth token.

Connection test failed.

![Screen Shot 2022-09-12 at 12.35.47 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/d3bbc5a0-20e1-44d1-979b-6faa08fc5030
)

1. this should not say "re-authenticate" for a new source
2. we should show a better error for this situation
3. this should apply to other oauth connectors as well.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
[Relevant PR](https://github.com/airbytehq/airbyte/pull/15615)
Looks like we may need to dig in further to see what's happening in this fail-case.

**Comment by edmundito** [comment]
Reviewed with team, see the PR above. Could it be related to a caching issue in react query?

**Comment by tealjulia** [comment]
@timroes is this addressed by the auth work you've been doing recently?

**Comment by timroes** [comment]
It won't be as far as I could tell when testing it, but we should still be waiting on this to be merged before picking this up.

**Comment by tealjulia** [comment]
currently only able to reproduce with Google Ads.  It looks like there may be some more work to be done with the authentication hook as well before this can be tackled.  I'm going to unassign myself for now.
