### ISSUE TITLE
Allow date variable in namespace (fka Additional Sync mode to snapshot data)

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#16611]
## Tell us about the problem you're trying to solve
When running a sync in `Incremental - deduped history` sync mode, data loads are stored as Type 2 SCDs in `*_scd` tables with `_airbyte_start_at` and `_airbyte_end_at` date columns.
Storing data in this way saves on storage space, but it puts more burden on users to query data correctly to see what the data looked like on a particular day in SQL.
 
As Maxime Beauchemin describes in [functional data engineering](https://maximebeauchemin.medium.com/functional-data-engineering-a-modern-paradigm-for-batch-data-processing-2327ec32c42a), since storage is cheap, we could simplify this process and store data in a way that is easier for end users to query. (Join queries become easier once you can normally join using the same partitions for all your tables)

## Describe the solution you’d like
I would like an additional sync mode for `Full refresh - snapshots history`. 

This could also be done by implementing "dynamic" format options in the custom format for a namespace with date timestamps:
If the destination namespace is set to `result_<date>` on a daily sync, then the output of my sync will be written in a different partition folder every day. (I can play with the desired granularity/frequency by changing the date format)

Now the data is stored in a way that can be more easily queried to see how the data looked on a particular date.

The sync mode could also produce an additional view that would always return data from the latest partition (equivalent to a view deduped to the last snapshot)

This mode is slightly different from `full refresh - append` since the data is split into multiple "partitions" folders/datasets/schemas automatically.

Note that this described strategy with some `incremental - snapshot history` option would allow capturing only the incremental delta data every time it runs and separate each batch in a separate folder. (I'm not sure how useful that could be)

**Comment by nataliekwong** [comment]
I just stumbled on this issue @alex-gron. I like the proposed solution here - to allow dynamic parameters in the custom namespace.

**Comment by alex-gron** [comment]
I think Chris added a lot of detail here, so I am trying to remember the use case for this.

I agree that allowing for a date in the namespace would be a nice feature, although I don't have an immediate need for it.

I also think that `full refresh - append` could be enhanced to be a little smarter, and make sure it is partitioned by date (maybe it already is?). I don't fully agree with needing a brand new sync mode anymore 😄

**Comment by nataliekwong** [comment]
Ah gotcha. I agree on not doing a sync mode, I edited the title to suggest adding the date variable as an option. I'm not sure if partitioning happens. You could check our only Full Refresh | Append sync - the SFDC opportunity historical snapshot to see if it does?

**Comment by alex-gron** [comment]
Looks like it is already partitioned by `_airbyte_extracted_at` ! (both the raw and final tables) 
<img width="309" alt="Screenshot 2023-09-28 at 7 50 34 PM" src="https://github.com/airbytehq/airbyte/assets/109167606/a71577c3-0652-4956-a6f8-a89075383882">

**Comment by nataliekwong** [comment]
Woot! It sounds like we could close this issue completely if there isn't a great use case for this. But we could leave it open if you want it to be discoverable for others in the future.

**Comment by alex-gron** [comment]
I'm in favor of closing :) Will do that now!
