### ISSUE TITLE
BigQuery Destination should meet Partner Attribution requirements

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16615]
To enable the reporting, partners should update Google Cloud Storage and BigQuery API calls with the User Agent string. See the document linked below for specifics:

https://docs.google.com/document/d/1RyV6xAB96HY6uZgxHnHZdviiosKfe-nBpqS2KFeDPqM/edit?resourcekey=0-v5vzXikM_GhqnCTRdi1QJQ

**Comment by yurii-bidiuk** [comment]
From my understanding, in the scope of this ticket we need to:
- add an optional field to spec.json (e.g `partner_string`)
- if `partner_string` is present in the config, add the header `"user-agent" `to BigQuery service builder and GCS Storage builder:
```
StorageOptions.newBuilder()
          .setProjectId(config.get(BigQueryConsts.CONFIG_PROJECT_ID).asText())
          .setCredentials(credentials)
          .setHeaderProvider(new FixedHeaderProvider() {
            @Nullable
            @Override
            public Map<String, String> getHeaders() {
              return ImmutableMap.of("user-agent", config.get("partner_string").asText());
            }
          })
          .build().getService();
```
```
bigQueryBuilder
          .setProjectId(projectId)
          .setCredentials(credentials)
          .setHeaderProvider(new FixedHeaderProvider() {
            @Nullable
            @Override
            public Map<String, String> getHeaders() {
              return ImmutableMap.of("user-agent", config.get("partner_string").asText());
            }
          })
          .build()
          .getService();
```

**Comment by grishick** [comment]
For `company_name` - let's use Airbyte, e.g. `(GPN:Airbyte)`

For `Product_name` - is it possible to use the name and version of the connector that is using the code? I know there is a lot of code sharing between destination connectors, so I am not sure if there is a way for the code to know at runtime or at compile time which connector it is - could you try and figure this out?
