### ISSUE TITLE
Source Google Sheets: Handle shorter URL for Google sheet URL

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#16627]
It seems that there are shorter URL for google sheet that the connector does not handle today. See [this issue](https://github.com/airbytehq/oncall/issues/520) for more details. Ideally, we should handle shorter URLs as well.

**Comment by YowanR** [comment]
@YuliiaNahoha @grubberr We should fit this into our next sprint.

**Comment by YowanR** [comment]
@YuliiaNahoha  @lazebnyi  This issue might blow-up so let's be proactive about fixing it.

**Comment by machariamuguku** [comment]
+1 we experienced this today. Took us a long time to figure it out
