### ISSUE TITLE
Modify workspace API endpoints to be PATCH-style (in preparation for setting Geography)

### ISSUE THREAD

**Issue by terencecho** [airbytehq/airbyte#16648]
Assumes a migration was already ran to add a geography column to the workspace.

Modify the /workspace/update handler to take in an optional field for setting a Geography that will be used as a default for all connections within that workspace.

Modify the /workspace/create handler to persist 'Auto' value for the preferred Geography. This sets us up for future improvements where we might be able to detect a good default geography based on the user's IP, etc. The Routing Service can see 'Auto' and then decide where best to route the connection.

We would need to decide what to show in the UI if we're storing 'Auto' - do we show the user what the Routing Service will likely use when the connection runs? This could be a can of worms, maybe we can revisit this in the future and keep things simple for now. 

Today, let's keep the UX simple, we want to capture information for the future so that when we add intelligent routing, we're able to apply that to old connections. We can do an announcement to affected users when that time comes. 

If we persist 'Auto' to the database by default, we need to decide what we want to show in the UI.
What we show today in the UI: perhaps 'Auto (US)'? @andyjih can follow up to figure this out, do we need more docs, info icon, etc?
What we show when we add intelligent routing: 'Airbyte Decides' (or something)

Part of this issue is to make calls to update the workspace safer by updating it to support a PATCH style update just like what we did for connections.

We want this to be done to help the frontend safely update workspaces with a to be created new fields for geography (this will be the default geography for all connections in a certain workspace).

Some more background for this work can be found in this ticket: https://github.com/airbytehq/airbyte-cloud/issues/2278

There should also be a previous PR that converts a connection to allow for PATCH style updates, which we can use as an example.

**Comment by mfsiega-airbyte** [comment]
https://github.com/airbytehq/airbyte/pull/16739 to make workspaces update patch-style.

**Comment by pmossman** [comment]
Planning notes:
- We'll default to 'Auto' on the backend when the user hasn't selected a specific preference. User should be able to select between 'Auto', 'US', and 'EU' for the first iteration of multi-cloud general-availability
