### ISSUE TITLE
A long discovery request causes a timeout in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1664]
## Description
Salesforce catalogs can be quite large and discovery can take a long time (>2m) to complete, which causes a timeout in the UI. When catalogs will take a long time to discover, we need a way to get around this. 

## Steps to Reproduce
1. TODO -- need to figure out how big is "big enough" to cause this timeout

## Severity of the bug for you
High -- it prevents using the connector for users with many resources in Salesforce

**Comment by michel-tricot** [comment]
if bumping the timeout is enough for now, let's just do it. We can focus on a nicer solution in the future

**Comment by sherifnada** [comment]
Closed with #1674
