### ISSUE TITLE
RecordSchemaValidator: log actual type

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#16640]
When debugging schema validation issues, it can be useful to know what type we actually got. We should include this information when logging.

We are performing the validation and building up the message here:

https://github.com/airbytehq/airbyte/blob/555efd53604b89e24d746080a546033e00c15329/airbyte-workers/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L40-L73

**Comment by evantahler** [comment]
closing in favor of https://github.com/airbytehq/airbyte/issues/16128
