### ISSUE TITLE
Source BigCommerce: Add Channel and Store Stream

### ISSUE THREAD

**Issue by roisinbolt** [airbytehq/airbyte#16649]
## Tell us about the new connector you’d like to have
* Which source and which destination?

This will include the `channels` and `store` endpoint for the existing `bigcommerce` source

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

The `store` endpoint is only support by `v2` of the BigCommerce API

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.

We want to enrich our bigcommerce pipelines with store and channel metadata. 

* How often do you want to run syncs?

Daily 

* If this is an API source connector, which entities/endpoints do you need supported?

`Store Information` - https://developer.bigcommerce.com/api-reference/bb1daaaeccae0-get-store-information
`Channels` - https://developer.bigcommerce.com/api-reference/d2298071793d6-get-all-channels

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

N/A

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Calling the API in another way

## Are you willing to submit a PR?

Yes!

**Comment by YowanR** [comment]
Hi @roisinbolt! I saw that you would be willing to submit a PR for this one! We would love for you to contribute to Airbyte ! 🙏

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source BigCommerce: Add Channel and Store Stream](https://app.harvestr.io/components/0/list/OAjRBExNq)

**Comment by roisinbolt** [comment]
Hey @YowanR , yes for sure! I actually have a PR open [here](https://github.com/airbytehq/airbyte/pull/16647) for this change - I am just awaiting a review :)
