### ISSUE TITLE
Bump and publish all python sources 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1665]
## Tell us about the problem you're trying to solve
A placeholder ticket to bump and publish all connectors before the v0.12.0 release.

EDIT with more context: base-python and base-singer had some updates in #1654 and #1552 that while some sources don't strictly need, we. should bump to anyways to make sure everything is up to date.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368141374940) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
why?

**Comment by sherifnada** [comment]
@cgardens updated with context

**Comment by cgardens** [comment]
@sherifnada what's the status on this? closable?

**Comment by jrhizor** [comment]
Closing since this is way out of date now.
