### ISSUE TITLE
Airbyte Server/Worker: gradual increase in memory usage

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#16652]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1949](https://airbyte7538.zendesk.com/agent/tickets/1949)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px;" dir="auto">
<li style="padding-bottom: 10px;">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px;">OS Version / Instance: Ubuntu - 20.04</li>
<li style="padding-bottom: 10px;">Memory / Disk:  64GB/ 200GB</li>
<li style="padding-bottom: 10px;">Deployment:  Docker</li>
<li style="padding-bottom: 10px;">Airbyte Version: 39.28</li>
</ul>
<p dir="auto">When we start Airbyte, the memory usage of airbyte-worker is around 1.5GB.  Memory usage increase as time passes. Currently, it uses around 4GB.  Is this expected?   How to handle it efficiently?<br>
PS: I know that we can limit the resources of each of the containers but wanted to understand what’s causing the memory increase to go up in the first place.</p> 

[<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-15 at 22:31:*

<blockquote><div class="zd-comment" dir="auto">Did you create more connectors &amp; connections or keep the same as the begining?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-16 at 07:15:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a>  we have the same number of connectors and connections. The memory usage went by 300mb since the time I asked the question. So it’s now almost 4.3GB.  Memory usage won’t come down even if there is a  long after jobs stopped running.</p>
<p dir="auto">And airbyte-server memory usage is also slowly increasing but at a slower pace, 5-10MB per day.</p> 

 [<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-16 at 20:13:*

<blockquote><div class="zd-comment" dir="auto">Do you mind sharing the output of <code>docker stats</code> ?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-17 at 07:01:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/9/9bda805392ec343c02bab0762a99def058a7d25a.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/9/9bda805392ec343c02bab0762a99def058a7d25a_2_690x42.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1261×77 12 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">Here</p> 

 [<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-22 at 07:00:*

<blockquote><div class="zd-comment" dir="auto">Sorry the delay here Prudhvi, did the memory increase again or become steady now?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-23 at 08:17:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">It is increasing. Current screenshot</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/1/1f512e86734a01f0c48fa9fa8b44118fb5f748e7.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/1/1f512e86734a01f0c48fa9fa8b44118fb5f748e7_2_690x40.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1244×73 11.9 KB</span>
</div></a></div><p dir="auto"></p> 

 [<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-23 at 21:43:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Seems potentially related to <a href="https://discuss.airbyte.io/t/resource-leak-in-airbyte-worker/2309" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">Resource leak in airbyte-worker</a></p> 

 [<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-08-25 at 02:58:*

<blockquote><div class="zd-comment" dir="auto">Pudhvi and Adam I request the engineer team to check for what is the expected resources needed and if maybe a bug exists.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 09:58:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a>   just wanted to check if there are any updates on this.</p>
<p dir="auto">And here is current resource usage. It keeps on increasing:</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/9/979637b401fdefce8af97ad93310b962e1662872.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/9/979637b401fdefce8af97ad93310b962e1662872.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>951×78 9.74 KB</span>
</div></a></div><p dir="auto"></p> 

 [<a href="https://discuss.airbyte.io/t/gradual-increase-in-memory-usage/2249/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 17:36:*

<blockquote><div class="zd-comment" dir="auto">The team is investigating a possible issue with memory leaky in the logging system. Until a solution is merged the workaround is to restart airbyte-server and airbyte-worker containers. I created the issue to track the issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/16652">https://github.com/airbytehq/airbyte/issues/16652</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
Zendesk ticket #[2223](https://airbyte7538.zendesk.com/agent/tickets/2223) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 17:37:*

<blockquote><div class="zd-comment" dir="auto">Hello Arash, the team is investigating a possible issue with memory leaky in the logging system. Until a solution is merged the workaround is to restart airbyte-server and airbyte-worker containers. I created the issue to track the problem: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/16652">https://github.com/airbytehq/airbyte/issues/16652</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 19:30:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hello Marcos,<br>
I restarted these containers, but the awful slowness still exists. I cannot even switch between pages. Are you sure this is the workaround?</p> 

 [<a href="https://discuss.airbyte.io/t/long-loading-time/2536/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 21:33:*

<blockquote><div class="zd-comment" dir="auto">Yep, it should work. How is the frequency of your connections? 5min?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 21:33:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Comment made from GitHub by marcosmarxm on 2022-09-13 at 21:33:</p>
<p dir="auto"><em>Comment made from Zendesk by Marcos Marx on 2022-09-13 at 21:33:</em></p>
<p dir="auto">&lt;blockquote&gt;&lt;div class="zd-comment" dir="auto"&gt;Yep, it should work. How is the frequency of your connections? 5min?&lt;br&gt;&lt;/div&gt;&lt;/blockquote&gt;</p></div></blockquote>

**Comment by salima-airbyte** [comment]
@salima-airbyte figure out which Q4 work item this belongs to and assign appropriately

**Comment by marcosmarxm** [comment]
@salima-airbyte please talk to @davinchia about it

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-18 at 04:55:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">The frequence is 1 hour.</p> 

 [<a href="https://discuss.airbyte.io/t/long-loading-time/2536/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 14:51:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Sorry the delay here <a href="/u/arashlayeghi" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@arashlayeghi</a> no updates besides the workaround suggested. Probably upgrading to latest version can help.</p> 

 [<a href="https://discuss.airbyte.io/t/long-loading-time/2536/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by programmeddeath1** [comment]
I had similar issues with increase in RAM with time. Could this be a docker issue? I have faced similar increase in RAM utilization for heavy Deep Learning API's that seemed to cache or  incrementally store data in the RAM

**Comment by apostoltego** [comment]
hey @marcosmarxm We've seen this happen alongside the server itself on 0.40.32 still. In the screenshot attached is the airbyte worker memory usage, and you can see it dropping after manually trigger the worker's garbage collection manually. 
<img width="1737" alt="Screenshot 2023-02-24 at 11 45 08" src="https://user-images.githubusercontent.com/16501677/221159881-5c09764f-f556-4a9f-b87d-3498cdecb130.png">

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-02-27 at 20:03:*

<blockquote><div class="zd-comment" dir="auto">Hello Prudhvi Raj, it's been a while without an update from us. Are you still having problems or did you find a solution?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-02-27 at 20:03:*

<blockquote><div class="zd-comment" dir="auto">Hello Arash Layeghi, it's been a while without an update from us. Are you still having problems or did you find a solution?<br></div></blockquote>

**Comment by totheroh** [comment]
In case it helps: We were seeing a similar constant increase in memory consumption over time. I noticed that the culprit actually looked to be the Linux disk cache. I cleared it with `sudo sh -c "/usr/bin/echo 3 > /proc/sys/vm/drop_caches"` and the issue was immediately resolved. We're just doing this in a cron task for now. Unsure at this point if it's an Airbyte issue or some bad host config.

**Comment by apostoltego** [comment]
hey @totheroh were you doing that on the worker or the server? If on the worker have you noticed any increased failures rates or any other "side effects"?

**Comment by totheroh** [comment]
@apostoltego On the Linux VM itself. I think the worst possible side effect of clearing these caches would be some less efficient reads (grain of salt there because I can't say I have deep Linux expertise). So far we haven't seen any noticeable downside. Another grain of salt there though because the cron task hasn't existed for very long.

**Comment by apostoltego** [comment]
@totheroh ah we tried the garbage collection on the worker pods and it wasn't quite working well but will give this a try. Appreciate your quick reply!

**Comment by szicari-farmobile** [comment]
For what it's worth, we are experiencing the same issue w/ Airbyte running on EKS. We just restarted the worker process today, so memory usage is low. However, there is a clear trend emerging already.

<img width="680" alt="Screenshot 2023-03-15 at 13 33 13" src="https://user-images.githubusercontent.com/32775099/225409957-03ed4641-5737-43f6-b681-dfe93fcf1ce1.png">

We have a single sync task running every minute; we have to restart the worker almost daily or jobs will simply _stop_ being scheduled after an indeterminate amount of time. It is clear there is some sort of resource leak in the worker (or elsewhere?), as the error messages talk about not being able to allocate a resource before the Airbyte platform halts altogether.

Is this your first time deploying Airbyte?: **No**
OS Version / Instance: **linux (amd64) / Amazon Linux 2**
Memory / Disk: **t3a.large (x2 nodes)**
Deployment: **EKS via Helm**
Airbyte Version: **0.41.0**

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:16:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:19:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:19:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by alexnikitchuk** [comment]
we observe the same issue with the worker
And @totheroh suggestion does not work for us.
![image](https://github.com/airbytehq/airbyte/assets/8694829/83f8c158-eca8-4eac-b10e-6fd86a4b3b1e)

OS Version / Instance: Amazon Linux 2 
Memory / Disk: 8 vCPU, 32 GB RAM (t3.2xlarge)
Deployment: docker compose
Airbyte Version: 0.44.4

**Comment by alexnikitchuk** [comment]
> hey @marcosmarxm We've seen this happen alongside the server itself on 0.40.32 still. In the screenshot attached is the airbyte worker memory usage, and you can see it dropping after manually trigger the worker's garbage collection manually. <img alt="Screenshot 2023-02-24 at 11 45 08" width="1737" src="https://user-images.githubusercontent.com/16501677/221159881-5c09764f-f556-4a9f-b87d-3498cdecb130.png">
> 
> Here's the same happening with the server, but in this instance the memory consumption grows only when we open the UI. We have 106 connections active. This situation got worse only as the connection count increased.
> 
> <img alt="Screenshot 2023-02-24 at 11 49 29" width="1264" src="https://user-images.githubusercontent.com/16501677/221160553-218d41af-0869-463e-a3ad-9aecf2d36873.png">
> 
> To handle the server problem we periodically run the java GC but doing so on the worker seems to be causing issues with the syncs themselves so it's not a solution there. Ultimately what we see happening is that services eventually run out of resources on the nodes and they get restarted or evicted etc.

hey @apostoltego could you pls share the details on how to trigger GC manually

**Comment by cgardens** [comment]
@alexnikitchuk what is the problem you are trying to solve? Java is generally very conservative in GC because it "stops the world". It is pretty typical for a Java application to slowly consume more memory until it hits it's max heap size. I am not seeing here that seems particularly surprising. Is there a specific issue that you are seeing that is memory related?

**Comment by alexnikitchuk** [comment]
> @alexnikitchuk what is the problem you are trying to solve? Java is generally very conservative in GC because it "stops the world". It is pretty typical for a Java application to slowly consume more memory until it hits it's max heap size. I am not seeing here that seems particularly surprising. Is there a specific issue that you are seeing that is memory related?

well, the problem we have is that the worker suddenly dies.

**Comment by vitas-pm** [comment]
Hi there.
I deployed airbyte using helm on Kubernetes.
After setting a single connection between a mysql source and a postgres destination the memory usage rose to more than half the available Memory of our cluster and has not decreased since. 
The sync is only once per day.
This needs to be adressed.
<img width="1440" alt="image" src="https://github.com/airbytehq/airbyte/assets/99405144/99f1f52a-06a2-46b4-86a3-5c4381c4f15b">

**Comment by ro8inmorgan** [comment]
We are seeing exactly the same problem on kubernetes, eventually the worker will just go over its memory limit and crash. Causing syncs to fail..

**Comment by ro8inmorgan** [comment]
This mostly seems to be a problem when postgres is used as a source connector, we also noticed a lot of log entries with the following
[1;31mERROR[m c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information: 2017-01-20T17:29:46.882

I have a feeling its 1000's of logs like these spawning in seconds that's causing the memory increase. But we have not found a way to stop these validation logs. Setting the workers logs to OFF still produces these.

**Comment by chargui-yassine** [comment]
We are encountering the same issue. After conducting an investigation, I believe it stems from non-heap memory consumption in Java. To resolve this, we need to update the default JAVA_OPTS for both the worker and server.
`DEFAULT_JVM_OPTS='"-XX:+ExitOnOutOfMemoryError" "-XX:MaxRAMPercentage=75.0"'`
Do you have a solution to overwrite this env set in the startup file ?

**Comment by marcosmarxm** [comment]
Hello folks, I have escalated this to our engineering team to investigate and return an update.

**Comment by rowanmoul** [comment]
This issue was originally reported over a year ago. I'm really glad to hear it is finally being addressed, but just curious what took so long. Surely you've been having similar issues in Airbyte Cloud?

**Comment by dgokeeffe** [comment]
Hey - I'm running just a simple CSV replication to Motherduck, the sync is failing because I'm reaching the Docker resource limit. However, if I look at how much memory the worker is consuming, it's stable at 1GB.

![image](https://github.com/airbytehq/airbyte/assets/17697537/6fe16b75-f544-408f-b292-a626c684f4ba)
![image](https://github.com/airbytehq/airbyte/assets/17697537/4d5bfe68-5bf8-4613-b41d-d980cf5241fb)

**Comment by fbuzila-g2** [comment]
any update on this? 
we are having the same issue, postgres to postgres sync, the worker pod memory increasing up to the limit and k8s kills it and then the job dies with "message='activity Heartbeat timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT" error
also  the worker logs are full with: "ERROR c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information:"

**Comment by dtiesling** [comment]
I'm having the same issue running airbyte on an EC2 with docker compose. I'm attempting a sync from postgres to snowflake and the postgres read container steadily consumes memory until it hits an OOM and kills the job. Currently at 17GB

![image](https://github.com/airbytehq/airbyte/assets/7133255/a626dd4d-5059-4e4b-a752-c09adf4eb51a)

**Comment by rcnavas** [comment]
Same issue, running Airbyte 0.50.44 on Google Compute engine instance using Docker Compose.
Only have 1 sync Job from PostgreSQL to BigQuery and the worker container can exhaust all memory available (8Gb) during sync... This is a small job moving 350Mb of data.
I suspect this issue has to do with ERRORs related to "invalid date time: no timezone information" which happens with every row...
Only remedy I found so far is to run `jcmd 1 GC.run` (java Garbage collector) on the `worker` container every hour. to avoid crashing due to Out of memory.

**Comment by marcosmarxm** [comment]
@rcnavas the work is OOO, do you have screenshots of GCP monitor of your instance?

**Comment by bioticinteractions** [comment]
i have the same issue: the memory of the worker will increase to the limit and then the worker will restart and the sync will fail and there will be another attempt at running the sync.

it doesn't matter what i set the memory allocation to (up to 32GB). the worker will go until it is out-of-memory. i have tried it on K8s (I have tried up to 36GB so far), I get the same result: memory usage of the worker pod will increase to the new limit and then restart the pod.

source: postgres v14
destination: snowflake

![Uploading Screenshot 2024-01-26 at 1.28.34 PM.png…]()

**Comment by hubertsl** [comment]
Same issue here, on EC2 large machine and having to reboot the machine and docker compose up

**Comment by walker-philips** [comment]
Also seeing this behavior, have workers set at 40GB. Monitoring the Workers container using docker stats is showing a 1GB memory usage however htop is showing multiple outofmemory exceptions. Not sure what is going on but there are a ton of airbyte processes listed with OOM errors

**Comment by ConsciousML** [comment]
Same issue on a GCE instance.

A few weeks ago, everything was running fine. The maximum RAM that a sync would take was around ~50% of the RAM (8 Gb / 16).

Yesterday it crashed ;(

**Comment by killthekitten** [comment]
Same on GCE, a flood of these messages crashes the instance:
- Increased memory consumption (had to bump the instance to 32GB)
- Increased disk usage (fills out 50 gb in under a week)

This has revealed itself after we updated from v0.44.0 to v0.57.1.

**Comment by sheralim012** [comment]
We are using version 0.63.4 and getting the same issue 
Using AWS EC2 xlarge instance
Source is Google Analytics and destination is Postgresql v15
All of the CPUs are at 100% all of the time and continuously seeing ExitOnOutOfMemoryError

**Comment by ChirangaL** [comment]
Hi @sheralim012, I was facing the same issue with S3 on 0.63.15. Once I updated the S3 connector to 1.0.1, the memory overflow issue, seems to have stabilized.

**Comment by ChirangaL** [comment]
@marcosmarxm 
We are using the version 0.63.15 and still facing the problem. As shown below, the worker hits max allocated memory and hangs.

```
destination > INFO pool-2-thread-1 i.a.c.i.d.a.b.BufferManager(printQueueInfo):94 [ASYNC QUEUE INFO] Global: max: 3.48 GB, allocated: 10 MB (10.0 MB), %% used: 0.00280620522129559
destination > INFO pool-2-thread-1 i.a.c.i.d.a.b.BufferManager(printQueueInfo):94 [ASYNC QUEUE INFO] Global: max: 3.48 GB, allocated: 2.33 GB (2390.0044717788696 MB), %% used: 0.6706843027625672 
destination > INFO pool-2-thread-1 i.a.c.i.d.a.b.BufferManager(printQueueInfo):94 [ASYNC QUEUE INFO] Global: max: 3.48 GB, allocated: 3.05 GB (3120.006585121155 MB), %% used: 0.8755378769643608
destination > INFO pool-2-thread-1 i.a.c.i.d.a.b.BufferManager(printQueueInfo):94 [ASYNC QUEUE INFO] Global: max: 3.48 GB, allocated: 3.48 GB (3563.53125 MB), %% used: 1.0
```

This ia BigQuery -> S3

**Comment by nickzombolas** [comment]
I've been experiencing similar behavior syncing source-instagram to snowflake. Seems like garbage collection wasn't working properly. A workaround for me was to downgrade airbyte-cdk from version `4.5.4`  to `4.1.0`
