### ISSUE TITLE
Twilio > S3 failing, and twilio refresh source schema not finishing

### ISSUE THREAD

**Issue by resford** [airbytehq/airbyte#16658]
## Environment
OS Version / Instance: amazon-linux-2
Memory / Disk: you can use something like 8GB memory / 200GB disk
Deployment: docker
Airbyte Version: 0.40.3
Source name/version: twilio 0.1.8
Destination name/version: S3 0.3.15
Step: The issue is happening during sync
Description: I just updated to airbyte v 0.40.3 and Twilio started failing. I am seeing the following errors.
2022-09-02 18:26:14 INFO i.a.v.j.JsonSchemaValidator(test):71 - JSON schema validation failed.
and
2022-09-02 18:27:03 ERROR i.a.w.g.DefaultReplicationWorker(run):184 - Sync worker failed.
When I try to refresh source schema to see if anything has changed it never finishing fetching.

## Discussion 
https://discuss.airbyte.io/t/twilio-s3-failing-and-twilio-refresh-source-schema-not-finishing/2462

## Current Behavior
Twilio <> S3 job fails. 

## Expected Behavior
Successful run. 

## Logs
[logs-2459.txt](https://github.com/airbytehq/airbyte/files/9559872/logs-2459.txt)

## Steps to Reproduce
1. Do a normal run with airbyte version 0.40.3

## Are you willing to submit a PR?
No

**Comment by artem1205** [comment]
Hi @resford,
it looks like there was a problem with the update, please try to [upgrade](https://docs.airbyte.com/operator-guides/upgrading-airbyte/) Airbyte to the latest version, and let me know if the problem still exists.

**Comment by YowanR** [comment]
Hi @resford, are you still blocked on this?

**Comment by YowanR** [comment]
@artem1205 Feel free to close this issue and re-open if it occurs again or someone else reports the same issue. Thanks!
