### ISSUE TITLE
Document how to set up secure connections in Postgres Source docs

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16666]
Users are not aware of how we enforce encryption in transit, so we should add an explanation of how we do that and which modes are allowed w/ and w/o SSH tunneling

**Comment by grishick** [comment]
Question for grooming: does it make sense (would it get us to a better result faster) if someone on the DBs & DWs team pairs up with @Amruta-Ranade to add documentation on setting up secure connections in Airbyte Cloud for

- [Postgres Source](https://github.com/airbytehq/airbyte/issues/16666) (this ticket)
- [Postgres Destination](https://github.com/airbytehq/airbyte/issues/16672)
- [MySQL Source](https://github.com/airbytehq/airbyte/issues/16653)
- [MySQL Destination](https://github.com/airbytehq/airbyte/issues/16654)

**Comment by Amruta-Ranade** [comment]
On it!

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/airbytehq/airbyte/pull/16782
