### ISSUE TITLE
Wrong link https://docs.airbyte.io/architecture/basic-normalization.md in destination settings

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1666]
The right link should be https://docs.airbyte.io/architecture/basic-normalization

@cgardens

**Comment by ChristopheDuong** [comment]
We fixed the docs in https://github.com/airbytehq/airbyte/issues/1277 but we haven't published new docker images so they are not actually fixed for users yet!

The latest docker image for Postgres for example is still from Dec 4th whereas the PR was made on Dec 12th:
https://hub.docker.com/r/airbyte/destination-postgres/tags?page=1&ordering=last_updated

**Comment by Jamakase** [comment]
@johnlafleur As stated above - this is not a frontend issue.
