### ISSUE TITLE
Add a note about setting GTID_MODE in Postgres Source for CDC

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16674]
### Tell us about the documentation you'd like us to add or update.
Some customers are running into the error documented in [this issue](https://github.com/airbytehq/alpha-beta-issues/issues/158). The error is caused by incompatible setting of GTID_MODE in their source database. It might make sense to add a note to the  documentation of our Postgres Source connector, in CDC section that explains that Debezium only supports On and Off modes for GTID_MODE, but not ON_PERMISSIVE or any other modes.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.com/integrations/sources/postgres)

**Comment by Upendra-Singh-Karmiyal** [comment]
Hi, I am going to pick this up.
