### ISSUE TITLE
Data types protocol proposal - second async + synchronous review

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#16679]
Finish https://github.com/airbytehq/airbyte/pull/17486:
* [x] Receive approvals
* [ ] Update documentation
* [ ] Finalize regexes/etc

**Comment by edgao** [comment]
protocol PR - https://github.com/airbytehq/airbyte/pull/17486

**Comment by edgao** [comment]
no further comments. I want to polish some of the regexes etc and update docs, then this is good to close + unblock all the implementation tickets

**Comment by grishick** [comment]
ping @edgao what's left here?

**Comment by edgao** [comment]
gah, I will never remember to close issues >.> thanks for the ping
