### ISSUE TITLE
Log warnings instead of raising errors in StateDeltaTracker and StateMetricsTracker

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#16681]
The StateDeltaTracker is raising StateDeltaTrackerExceptions and the StateMetricsTracker is raising StateMetricsTrackerOomExceptions and StateMetricsTrackerNoStateMatchExceptions. The AirbyteMessageTracker is catching these exceptions and logging a warning, but these exceptions still show up in the logs, which could be confusing to users.

We should remove these exceptions and refactor the code so we can still keep track of the exception events within the AirbyteMessageTracker without actually raising an exception.

**Comment by davinchia** [comment]
The underlying code should be rewritten. This issue is out of date.
