### ISSUE TITLE
[per-stream state] Migrate GA connectors that implement custom read()

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#16687]
Most API source connectors should be able to start emitting per stream state by just updating to the latest version of the CDK once the changes are released on a version. 

However, for any connectors that override the existing `abstract_source.read()` method, we explicitly continue to send them state in the legacy object format so that we don't break compatibility when it pulls the latest version of the CDK. For reference: https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/source.py#L80-L81

As part of migrating the connectors to per stream format, a couple connectors will require some changes to become compatible with the new format. The following GA connectors will be affected:

- [source-google-sheets](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/google_sheets_source.py#L127-L129)
- [source-hubspot](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py#L139-L141)
- [source-instagram](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-instagram/source_instagram/source.py#L61-L63)
- [source-salesforce](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/source.py#L101-L107)

**Comment by alafanechere** [comment]
I won't migrate `source-google-sheets` because it's not using state in its `read` as it's not managing any incremental stream.

**Comment by alafanechere** [comment]
[source-hubspot PR](https://github.com/airbytehq/airbyte/pull/17120)

**Comment by alafanechere** [comment]
[source-instagram PR](https://github.com/airbytehq/airbyte/pull/17110)

**Comment by alafanechere** [comment]
source-salesforce was already migrated in this [PR](https://github.com/airbytehq/airbyte/pull/17001)
