### ISSUE TITLE
Source MySQL: DefaultAirbyteStreamFactory - Validation failed

### ISSUE THREAD

**Issue by ayyoubmaulana** [airbytehq/airbyte#16691]
## Environment
- **Airbyte version**:  0.36.4-alpha
- **OS Version / Instance**: CentOS
- **Deployment**: Docker
- **Source Connector and version**: MySQL connector version : 0.6.8
- **Step where error happened**: Sync job

## Current Behavior
I got this error while sync data from MySQL to BigQuery, the anomaly happen just in one dataset

## Logs
[logs-32509.txt](https://github.com/airbytehq/airbyte/files/9564479/logs-32509.txt)
[logs-32513.txt](https://github.com/airbytehq/airbyte/files/9564480/logs-32513.txt)

**Comment by sajarin** [comment]
@ayyoubmaulana can you upgrade to the latest version for the MySQL connector? We are on version 0.6.13 now. You may also want to consider upgrading Airbyte as well, we are out of alpha now (0.40.9)

**Comment by ayyoubmaulana** [comment]
will try to update connector first

**Comment by sajarin** [comment]
@ayyoubmaulana any update on whether the upgrade worked?

**Comment by misteryeo** [comment]
@ayyoubmaulana closing this due to no response but please reopen and let us know if the problem persists after upgrading!
