### ISSUE TITLE
Use Micronaut Environment to control ProcessFactory conditional bean selection

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#16700]
## Tell us about the problem you're trying to solve

There are too many environment variables in place to control the configuration of services.  This leads to potential issues with misconfiguration due to untested combinations of configuration options and due to lack of documentation for said configuration.  

## Describe the solution you’d like

Leverage [Micronaut environments](https://docs.micronaut.io/latest/guide/#environments) to select the proper configuration of the `ProcessFactory` bean used by `airbyte-workers` to launch and manage containers.  This can be done by explicitly enabling a `control` or `data` environment AND by leveraging the built in [auto-deduced "kubernetes" environment](https://docs.micronaut.io/latest/guide/#cloudConfiguration) provided by Micronaut.  For example, the conditional bean declaration should look something like this:

```
  @Singleton
  @Requires(notEnv = "kubernetes")
  @Requires(notEnv = "data")
  @Named("checkProcessFactory")
  public ProcessFactory checkDockerProcessFactory(
                                                  @Named("checkWorkerConfigs") final WorkerConfigs workerConfigs,
                                                  @Value("${docker.network}") final String dockerNetwork,
                                                  @Value("${airbyte.local.docker-mount}") final String localDockerMount,
                                                  @Value("${airbyte.local.root}") final String localRoot,
                                                  @Value("${airbyte.workspace.docker-mount}") final String workspaceDockerMount,
                                                  @Value("${airbyte.workspace.root}") final String workspaceRoot) {
    return createDockerProcessFactory(
        workerConfigs,
        Path.of(workspaceRoot),
        workspaceDockerMount,
        localDockerMount,
        localRoot,
        dockerNetwork);
  }
```

Environments can be set via the `MICRONAUT_ENVIRONMENTS` environment variable as a comma separated list.

## Acceptance Criteria

- [ ] `ProcessFactory` beans are conditionally created using environment instead of separate configuration properties
- [ ] Docker compose configuration is updated to set appropriate environments for `airbyte-workers`
- [ ] Helm charts (OSS and Cloud) are updated to set appropriate environments for `airbyte-workers`

**Comment by gosusnp** [comment]
Another option would be to do #17005 instead.
If process for docker and kube are aligned, it might change the requirements for this story.
