### ISSUE TITLE
Update error state in stream reset job

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#16701]
Currently, the reset stream job uses the existing error state as the rest of the jobs, but it does not show which streams were reset and that the job itself was a reset job. This is because the design for this was missing at the time of the implementation. The goal is to apply the updated design and show the streams that may be reset.

Followup to #13324 based on [this comment](https://github.com/airbytehq/airbyte/pull/16600#issuecomment-1246619620).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This change will be included as part of #13324
