### ISSUE TITLE
[Source FB Marketing] Concurrent synchronization 

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1671]
## Tell us about the problem you're trying to solve
Synchronization for some streams could be really long
The original singer tap had some optimization to download streams concurrently (AdsInsight)
https://github.com/singer-io/tap-facebook/blob/15ea4a6ca7a0d9b4aa89aa1ea66818df6b3a23fd/tap_facebook/**init**.py#L498

## Describe the solution you’d like
To keep the same performance we should at some point think about implementing something like this.
The exact solution is TBD.

## Describe the alternative you’ve considered or used
`facebook-marketing-api-singer` connector

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368083508004) by [Unito](https://www.unito.io)

**Comment by mlavoie-sm360** [comment]
I believe this issue was closed with PR https://github.com/airbytehq/airbyte/pull/3743
