### ISSUE TITLE
Remove direct database access from airbyte-workers

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#16732]
## Tell us about the problem you're trying to solve

Reduce the configuration and dependencies required to run the `airbyte-workers` service by removing direct access to the database(s).  Currently, the direct database access not only means that additional configuration is required to set up the database connection(s), but it also impacts the running of `airbyte-workers` in the different modes for multi-cloud applications.

## Describe the solution you’d like

Remove/replace any direct calls, configuration and checks of the database(s) with calls to API endpoints exposed by the `airbyte-servers` module.  This includes the conditional creation of the API client in modes that will perform database operations vs modes that do not require database access (e.g. data plane mode).

This may require defining/exposing new endpoints in `airbyte-server` to accommodate the operations currently performed by `airbyte-workers` against the database(s)

## Acceptance Criteria

- [ ] `airbyte-workers` no longer directly accesses the database(s)
- [ ] All unit/acceptance/functional tests still pass

**Comment by davinchia** [comment]
@tryangul @gosusnp this is an older ticket I believe should already be done as part of Q3B.

**Comment by davinchia** [comment]
This was done as part of Q3B.
