### ISSUE TITLE
Break dependency between airbyte-workers and airbyte-container-orchestrator

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#16731]
## Tell us about the problem you're trying to solve

The `airbyte-container-orchestrator` service module depends on source code stored in the `airbyte-workers` service module.  The result of this is that all of `airbyte-workers` transitive dependencies are polluting `airbyte-container-orchestrator`'s classpath.  As we convert [Micronaut](https://micronaut.io), this also means that any and all Micronaut annotated classes in `airbyte-workers` will automatically be discovered by `airbyte-container-orchestrator`.  This is obviously less than desirable, as it means things like any initializers/event listeners will also be created and executed as part of the other service.

## Describe the solution you’d like

Extract any shared classes used by both `airbyte-container-orchestrator` and `airbyte-workers` to shared module(s) to avoid direct dependency between the two services.

## Acceptance Criteria

- [ ] `airbyte-container-orchestrator` no longer depends on `airbyte-worker`
- [ ] Both `airbyte-container-orchestrator` and `airbyte-worker` build and run with extracted code/module

**Comment by salima-airbyte** [comment]
Related to #16730
