### ISSUE TITLE
Source Instagram: Ensure that sandbox account has every media_type and media_product_type available for testing.

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#16750]
**What**
Make sure our Instagram sandbox account has every media_type and media_product_type available for testing and also double-check metrics validity against all media_type and media_product_type. We know that we were missing Reel media test data in the past.

**Why**
This would help us better debug issues such as the one we encountered [here](https://github.com/airbytehq/oncall/issues/552).

**Comment by YowanR** [comment]
@igrankova @ycherniaiev Could you take a look at this and make sure that we are covered here?
cc @alafanechere as FYI

**Comment by ycherniaiev** [comment]
@YowanR @igrankova  So, there are three media types: IMAGE, VIDEO and CAROUSEL_ALBUM. now - they are all present for instagram(airbytehq) . Regarding media_product_types - in waht sream is this field? I cannot check what is already present from: AD, FEED, STORY or REELS.
