### ISSUE TITLE
Document how Airbyte handles database secrets.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#16757]
### Tell us about the documentation you'd like us to add or update.
As contributor or Airbyte employee, I want to understand:
- [x] how Airbyte masks secrets, either in the database or in a secret store a.k.a GSM.
- [x] how I would implement adding a new secret to be used by the platform (since this is automatically done for connectors)

### If applicable, add links to the relevant docs that should be updated
- probably a new page under the Understanding Airbyte section

**Comment by davinchia** [comment]
fyi @benmoriceau @git-phu @mfsiega-airbyte from our conversation.

**Comment by davinchia** [comment]
Dependant on https://github.com/airbytehq/airbyte-cloud/issues/2690.

**Comment by gvillafanetapia** [comment]
As far as I saw, Airbyte does not mask secrets at all. They just sit in plain text on the `secrets` table in the database. I'm not sure if there is an open issue about this, but its a major problem. 🔥

**Comment by gvillafanetapia** [comment]
https://github.com/airbytehq/airbyte/issues/1971

**Comment by davinchia** [comment]
This is actually do here: https://docs.airbyte.com/operator-guides/security#credential-management.

I am going to close this for now.
