### ISSUE TITLE
Start persisting the states from the ReplicationActivity instead of persisting them in a subsequent activity.

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#16762]
## What

Start persisting the states from the ReplicationActivity instead of persisting them in a subsequent activity.

We currently persist states in a subsequent activity, it has a couple of downside.
* In case of a non-deterministic error from temporal, if this happens during a sync, it means that we would not persist the state of what has been committed so far by the destination. This should not happen frequently, however, if we decide to rely less on versioning and more on the ability to automatically restart failed workflows, this would become more common.
* In a case of a long running sync, we won't actually persist states until the whole replication (source->dest) is done. It affects some of our checkpointing metrics since we actually have a bigger delay and a bigger chance of not being able to actually commit. (For example, OOM exceptions in the worker/orchestrator)

**Comment by gosusnp** [comment]
@pmossman, @davinchia, any thoughts/concerns about this? (In general and with multi-cloud in mind)

**Comment by pmossman** [comment]
I don't think there are any particular multi-cloud concerns, as long as we persist state by calling the API then Data Plane workers can do that during replication without issue. It seems like persisting state on Airbyte's side as soon as we know the state was persisted on the destination is a good idea in general so I'm in favor

**Comment by salima-airbyte** [comment]
As part of this work, change from depending on DB calls to calling APIs. 
Will we achieve more realtime metrics for sync operations? TBD.

**Comment by gosusnp** [comment]
From https://github.com/airbytehq/oncall/issues/731, we confirmed that there is a cap by temporal cloud of 2Mb on the IO. This could be an issue for us currently because we are passing all the states through temporal. In cases of connections with a big states, we may hit this limitation.
Persisting states from the replication would remove this need of passing all the states through temporal.
Note that to solve this completely, we should also probably read the state from the ReplicationActivity instead of passing all the current states in the input of the activity.

**Comment by evantahler** [comment]
Some additional thoughts in a duplicate (but now closed) issue https://github.com/airbytehq/airbyte/issues/20457

**Comment by gosusnp** [comment]
Addressed by https://github.com/airbytehq/airbyte/issues/23042
