### ISSUE TITLE
Removing the first item from a connector field array causes form to be submitted

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#16765]
## Current Behavior
When the first item is removed from a field array that contains multiple items in a connector form, the form is submitted. It is unclear why this happens. 

See this screen recording for a demonstration. The field array in this example is the `Schemas` field on the Postgres source form. Watch what happens when the `public` value is removed:

https://user-images.githubusercontent.com/22731524/190284120-607978cc-0193-4e6c-8347-044aa3182e6c.mov

One other slightly related issue here is that the UI around removing field array items is pretty unclear - you currently need to click a very small area on the right side of an item in order to remove it. There is probably supposed to be an `x` there, but that is currently missing.

## Expected Behavior
The expected behavior is that removing one of the field array items should not cause the form to be submitted. The form should only be submitted when the `Set up source` button at the bottom is clicked.

And, the UI around removing items should also be improved (e.g. add an `x` in the clickable area of the item).

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by lmossman** [comment]
Closing this since the bug no longer exists
