### ISSUE TITLE
Snowflake Destination should use Connection String Identifier Best Practices

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#16767]

**Comment by etsybaev** [comment]
@grishick could you please add a bit extended description of what needs to be done there?
Thanks

**Comment by etsybaev** [comment]
@grishick so should it be a hardcoded value to should be configurable on UI but with default values as "Airbyte_Connector"?

**Comment by grishick** [comment]
It should be hardcoded

**Comment by etsybaev** [comment]
https://github.com/airbytehq/airbyte/pull/17115
