### ISSUE TITLE
Update documentation to describe CDC vs non-CDC table source approach

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#16761]
## Tell us about the problem you're trying to solve
- Previously the Postgres connector supported reading tables through CDC and views in one sync.
- However, this feature was removed when we were working on CDC optimization.
  - I could not remember if doing pure CDC in one sync was beneficial. So this could be a regression.
- We should consider add this feature back and not compromise the CDC at the same time.

## Describe the solution you’d like
N/A

## Describe the alternative you’ve considered or used
N/A

## Additional context
- PR that removed view from the catalog under CDC mode: https://github.com/airbytehq/airbyte/pull/14447

**Comment by matt-ripple** [comment]
@tuliren / @grishick Is this scheduled for an upcoming sprint by any chance? This is a blocker for us to upgrade and we need to upgrade to fix the postgres CDC date bug.

**Comment by bleonard** [comment]
Option A: Show al tables and views (and only allow full refresh if they are not in the publication)
Option B: Show only tables in publication - enable incremental CDC or full refresh (current version)
Option C: Show only tables in publication and only allow incremental (CDC or bust! Maybe future make it's own connector)
Option D: Show everything and nuances in incremental when you can choose CDC or cursor (many UI changes)

For Option B or C, they would make another source to be able to sync non-publication tables or views.

**Comment by bleonard** [comment]
Let's look at the document and make sure it's clear that CDC sources only affect the tables that are in the publication. If they want other tables, make another Postgres source.
