### ISSUE TITLE
Source Intercom: takes 30 hours to sync 200K records

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#16808]
## Environment

- **Airbyte version**:  0.40.6
- **OS Version / Instance**: EKS 1.23
- **Deployment**: Kubernetes
- **Source Connector and version**: Intercom 0.1.26
- **Destination Connector and version**: Snowflake 0.4.36
- **Step where error happened**: Sync job

## Current Behavior

It took 30 hours to sync 200K records. the time was spent mostly on the conversation object, per my research, the intercom can sync at a maximum of 150 records per page

Simple math: `200,000 records` / `150 per page` = 1,333 pages (API calls)

The intercom API rate limit is 1,000 per minute, then why does 1,333 API call takes 30 hours? This does not make sense.

## Expected Behavior

The sync should be much faster than 30 hours

## Logs

```
Syncing stream admins 0:00:00.758520
Syncing stream companies 0:00:00.551362
Syncing stream company_attributes 0:00:00.271076
Syncing stream company_segments 0:00:01.118670
Syncing stream contact_attributes 0:00:00.770751
Syncing stream contacts 0:30:55.630675
Syncing stream conversations 1 day, 4:27:52.095893
```

The full logs:

[logs-6588.txt](https://github.com/airbytehq/airbyte/files/9584272/logs-6588.txt)

**Comment by natalyjazzviolin** [comment]
Hi @nauxliu , you're deploying on Kubernetes, is that correct? Could you please include that information in your initial post as per the template we provide?

**Comment by nauxliu** [comment]
@natalyjazzviolin Yes, It was running on Kubernetes. I have updated the issue information per your reqeust.

**Comment by bazarnov** [comment]
The `company-segments` are still slow because of their parent/child nature, we should fetch the whole companies first, then iterate over each company_id and fetch the segments. There is no way to fasten the process because of the Intercom API. It's expected the situation will change in the future and we will be able to use Export API for all streams available.

Closing this for now. re-open once needed.
