### ISSUE TITLE
Ingress in Helm chart broken

### ISSUE THREAD

**Issue by as42sl** [airbytehq/airbyte#16800]
Activating the ingress breaks the helm chart:

`{"level":"error","ts":"2022-09-15T12:52:48.137Z","msg":"reconciliation failed: Helm upgrade failed: template: airbyte/charts/webapp/templates/ingress.yaml:53:33: executing \"airbyte/charts/webapp/templates/ingress.yaml\" at <.Release.Name>: nil pointer evaluating interface {}.Name","name":"airbyte","namespace":"data-warehouse-airbyte","reconciler kind":"HelmRelease","annotations":{"helm.toolkit.fluxcd.io/revision":"0.40.6"}}`

Test with: webapp.ingress.enabled: true

It used to work with v '0.41.0'

Here is the culprit: https://github.com/airbytehq/airbyte/blob/master/charts/airbyte-webapp/templates/ingress.yaml#L53
It should be `{{ $.Release.Name }}` instead of`{{ .Release.Name }}` because it is inside a range

**Comment by DustyShap** [comment]
I am also seeing this error, thanks for opening the issue.  Do you have a current workaround for latest charts?

**Comment by sajarin** [comment]
Thanks @as42sl for the issue. Are you willing to submit a PR? If not, someone from our team will try to resolve this issue when they're able to. Thanks.

**Comment by DustyShap** [comment]
I have opened a PR @sajarin , would love some 👁️ on this so I can get Airbyte deployed!

https://github.com/airbytehq/airbyte/pull/16931

**Comment by sajarin** [comment]
Thanks for the PR @DustyShap, someone will review it soon and we'll get it merged!
