### ISSUE TITLE
Broken links in FB docs

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1682]
I deleted some links out of the facebook docs in this PR: https://github.com/airbytehq/airbyte/pull/1681. The links were broken and causing the build to fail. Looks like when the FB source got updated ([commit](https://github.com/airbytehq/airbyte/commit/fb7262dfa8a76233a4a924b650b9a00594e2423e)) some screenshots didn't get included in source. We should add those back so that the docs make sense.

**Comment by cgardens** [comment]
heads up @sherifnada  and @eugene-kulak

**Comment by eugene-kulak** [comment]
it looks like the original FB connector had this issue as well, but it was fixed after I started my work on non-singer version, so need to add any files, just update links.

**Comment by eugene-kulak** [comment]
fixed in #1699
