### ISSUE TITLE
Fail `check` when user has incorrect permission to target Snowflake warehouse

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#16833]
## Tell us about the problem you're trying to solve
Follows along with [oncall issue](https://github.com/airbytehq/oncall/issues/443) where user is getting an error message of 
```
No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.
```

## Describe the solution you’d like
Fail the `check` method when invalid permissions to a target Snowflake warehouse is accessed

## Describe the alternative you’ve considered or used
Add documentation informing users that this error when seen is due to insufficient permissions

## Are you willing to submit a PR?

Yes

**Comment by edgao** [comment]
Related, and I think should be implemented as part of this issue: https://sentry.io/organizations/airbytehq/issues/3483174197/?project=6527718&referrer=slack

```
net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Schema 'PUBLIC' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
```

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Destinations-6332532d6893ce001c7a56a7/issues/airbytehq/airbyte/16833?planning-poker) with Zenhub @edgao @etsybaev @ryankfu @suhomud

**Comment by grishick** [comment]
Notes from grooming:

- the connections in original OC ticket are turned off, so it is unlikely that we'll be able to troubleshoot those
- issue mentioned in [this comment](https://github.com/airbytehq/airbyte/issues/16833#issuecomment-1253902932) is still prevalent 
- the problem may have been fixed. if so, we need to understand what code changes have addressed the problem before closing this issue
- it may make sense to ask TCS for more recent failures that look similar (e.g. CHECK did not catch permission errors in Snowflake)

**Comment by edgao** [comment]
also, noticed in OC that we should check the `_airbyte_blah` schema - https://github.com/airbytehq/oncall/issues/805#issuecomment-1284288465. Normalization creates a separate schema for some internal stuff, which we probably don't verify in the destination `check` operation

though there's also a philosophical question around whether the connector _should_ verify permissions for something happening in normalization. Especially since that schema doesn't actually exist until normalization runs...

**Comment by edgao** [comment]
also also, submitted https://github.com/airbytehq/airbyte/issues/18312 - we probably want to track this separately since it's more about GCS access, but it seems like dest-snowflake's `check` behavior has a lot of blind spots

**Comment by erica-airbyte** [comment]
This issue will close: https://github.com/airbytehq/oncall/issues/805
