### ISSUE TITLE
Destination BigQuery (denormalized typed struct): long integer values issue

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#16841]
## Environment
- **Airbyte version**:  0.40.10
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker 
- **Source Connector and version**: Amazon Ads 0.1.22
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where error happened**: BigQuery (denormalized typed struct) Destination connector store data

## Current Behavior
It is damaging long integer values.
for example you can see profile ids.

![Screenshot at Sep 16 20-27-43](https://user-images.githubusercontent.com/5002551/190833166-2353ad8d-a9bc-41e3-ba1d-cc3cf40f6459.png)

must be:
![Screenshot at Sep 16 20-28-13](https://user-images.githubusercontent.com/5002551/190833178-4f519fa5-5869-4001-a4c2-ca72b65cd382.png)

**Comment by marcosmarxm** [comment]
Hello @animer3009 sorry the delay in reply here. First edit this issue to represent only one problem and open other as need. Team works solving one thing each time.

**Comment by animer3009** [comment]
@marcosmarxm
Thank you for your response.
I separated them :)
