### ISSUE TITLE
JSON not being copied on incremental sync

### ISSUE THREAD

**Issue by mackro-rocky** [airbytehq/airbyte#16849]
## Environment
- **Airbyte version**:  0.40.6
- **OS Version / Instance**: Amazon Linux 2 / AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.7
- **Destination Connector and version**: Snowflake 0.4.35
- **Step where error happened**: After initial sync

## Current Behavior
We have a column which contains json data, but of type text in postgres. We're using wal2json plugin for logical replication.

On the INITIAL sync, the "colA" which is json is captured and loaded into Snowflake **without** issue. However on **subsequent** incremental changes, this column is NULL. All other columns are captured without issue. Should we switch to using pgoutput, even though documentation recommends using wal2json when large JSON is involved?

```postgres_database=> select id, colA from sometable where id = 210000000;
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id   | 210000000
colA | {"x":"","approvalInfo":{"y":"FULL","amount":"0","tAmount":"0","tBaseAmount":"0"},"response":"FAIL","duration":"177","funded":"true","RequestSent":"true","balances":{"x":"0","y":"0","z":"0","limit":"0","auth":"0","promo":"0"},"match":"NOT_PRESENT","duration":"123","lowrisk":"","securityLevel":"","ucf":"","collection":"NOT_PRESENT"}

Table definition:
                             Table "public.sometable"
         Column          |            Type             | Collation | Nullable | Default
-------------------------+-----------------------------+-----------+----------+---------
 id                      | bigint                      |           | not null |
 colA                    | text                        |           |          |
```

## Steps to Reproduce
1. Do an initial sync
2. Have some data go into table
3. Perform CDC and watch as column is null

**Comment by natalyjazzviolin** [comment]
@mackro-rocky let's take this over to the forum for debugging:
https://discuss.airbyte.io/

I'll close this for now and we can reopen it once we have a more concrete idea of what is causing the issue.

**Comment by mackro-rocky** [comment]
> @mackro-rocky let's take this over to the forum for debugging: https://discuss.airbyte.io/
> 
> I'll close this for now and we can reopen it once we have a more concrete idea of what is causing the issue.

Created topic [here](https://discuss.airbyte.io/t/json-not-being-copied-on-incremental-sync/2727)

**Comment by arch-android** [comment]
> > @mackro-rocky let's take this over to the forum for debugging: https://discuss.airbyte.io/
> > I'll close this for now and we can reopen it once we have a more concrete idea of what is causing the issue.
> 
> Created topic [here](https://discuss.airbyte.io/t/json-not-being-copied-on-incremental-sync/2727)

@natalyjazzviolin @mackro-rocky did you ever happen to find a solution to this?

**Comment by mackro-rocky** [comment]
> > > @mackro-rocky let's take this over to the forum for debugging: https://discuss.airbyte.io/
> > > I'll close this for now and we can reopen it once we have a more concrete idea of what is causing the issue.
> > 
> > 
> > Created topic [here](https://discuss.airbyte.io/t/json-not-being-copied-on-incremental-sync/2727)
> 
> @natalyjazzviolin @mackro-rocky did you ever happen to find a solution to this?

No - I'm told this is a known issue and a fix is being worked on. That was a few months ago, no update or timeline has been provided since.
