### ISSUE TITLE
 Sandbox Account for Airship

### ISSUE THREAD

**Issue by Nmaxime** [airbytehq/airbyte#16848]
Need a sandbox account for PR https://github.com/airbytehq/airbyte/pull/16573

https://www.airship.com/

**Comment by Nmaxime** [comment]
@sajarin , I don't have the rights to set the expected labels, as you did [here](https://github.com/airbytehq/airbyte/issues/16171).

**Comment by evantahler** [comment]
cc @YowanR

**Comment by YowanR** [comment]
@igrankova @ycherniaiev Could you help us get an sandbox account for airship, please? thanks!

**Comment by igrankova** [comment]
@Nmaxime 
Please find creds on the LastPass: Primary Airship Dev Account
Free account with prod and test projects.

**Comment by YowanR** [comment]
@sajarin can you put in a request to share the creds?

**Comment by igrankova** [comment]
Closing this issue. If there's a need to add something here, please, reopen.
