### ISSUE TITLE
Source Square: new stream Cash Drawers

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16852]
## Tell us about the problem you're trying to solve
Cash drawer shifts track cash transactions so that the total money in the cash drawers can be reconciled for a specific period of time (a cash drawer shift), for a particular device, in a particular location. 

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by btkcodedev** [comment]
@ycherniaiev @bmcgilli I would like to work on this issue, all the other issues has been raised with PRs

**Comment by btkcodedev** [comment]
Raised PR https://github.com/airbytehq/airbyte/pull/31065 😄
