### ISSUE TITLE
Source Square: new stream Bank Accounts

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16856]
## Tell us about the problem you're trying to solve
Returns a list of [BankAccount](https://developer.squareup.com/reference/square/objects/BankAccount) objects linked to a Square account.

## Describe the solution you’d like
Research pros and cons for implemeting this stream.
For this stream BANK_ACCOUNTS_READ scope is obligatory

**Comment by avirajsingh7** [comment]
@bmcgilli @justinbchau can you assign me this one?

**Comment by archangelic** [comment]
Just want to be clear that this was completed by @avirajsingh7 and I just merged it in another PR.
