### ISSUE TITLE
Oracle source connector

### ISSUE THREAD

**Issue by ghost** [airbytehq/airbyte#1685]
## Tell us about the new integration you’d like to have
Oracle 11g R2 and up, replication to Snowflake and/or snapshots to Azure Data Lake blob storage, hourly frequency or lower.

Since the source is a high-traffic ERP system, log-based data capture for incremental updates would be ideal to reduce load on the source.

## Describe the context around this new integration
This is (and incremental updates for SQL Server) is the main blocker for our org being an early adopter. Most of our standard enterprise-y applications are backed by either Oracle or mssql

## Describe the alternative you are considering or using
Hand-rolled or Azure Data Factory

Note that there's already a [Singer tap](https://github.com/singer-io/tap-oracle) ([docs](https://www.stitchdata.com/docs/integrations/databases/oracle)) that appears to also support log-based replication

**Comment by michel-tricot** [comment]
Thank you @jared-noynaert ! 100% agreed on the Oracle piece. it is top of our mind.

Are you using your own Oracle license/instance or one provided by Azure?

**Comment by jared-noynaert** [comment]
Thanks @michel-tricot, we are using our own on-prem instance. Actually just ended up discussing this more extensively with Srif and John with a call to follow

**Comment by rabel** [comment]
I'm also interested in an Oracle source (and destination)
