### ISSUE TITLE
Source Zendesk Support: new stream Articles

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16859]
## Tell us about the problem you're trying to solve
[Articles](https://developer.zendesk.com/api-reference/help_center/help-center-api/articles/#content) are content items such as help topics or tech notes contained in [sections](https://developer.zendesk.com/api-reference/help_center/help-center-api/sections/).

[Allowed for:](https://developer.zendesk.com/api-reference/help_center/help-center-api/articles/#allowed-for)
- Agents
- End users
- Anonymous users

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
We expect this stream to be incremental! :)

**Comment by artusiep** [comment]
@jrolom I would like to work on that issue

**Comment by bmcgilli** [comment]
@jrolom can we reassign back into the pool? It would be great to get this stream addded

**Comment by oustynova** [comment]
@bmcgilli we were planning to take this issue to the next sprint.

**Comment by artem1205** [comment]
added in https://github.com/airbytehq/airbyte/pull/29998
