### ISSUE TITLE
Source Square: new stream Location

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16853]
## Tell us about the problem you're trying to solve
Provides details about all of the seller's [locations](https://developer.squareup.com/docs/locations-api), including those with an inactive status.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
For this stream MERCHANT_PROFILE_READ scope is obligatory

**Comment by avirajsingh7** [comment]
@bmcgilli I can see locations stream is available in Source Square [here](https://github.com/airbytehq/airbyte/blob/5d6597e5b6b663eecdb5b781575edaaae93b882f/airbyte-integrations/connectors/source-square/source_square/manifest.yaml#L203)

**Comment by justinbchau** [comment]
Thank you for calling this out @avirajsingh7 ! Closing this.
