### ISSUE TITLE
Source Square: new stream Loyalty

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16854]
## Tell us about the problem you're trying to solve
A Square loyalty program maintains a ledger of events that occur during the lifetime of a buyer's loyalty account. Each change in the point balance (for example, points earned, points redeemed, and points expired) is recorded in the ledger. Using this endpoint, you can search the ledger for events.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
For this stream LOYALTY_READ scope is obligatory

**Comment by btkcodedev** [comment]
I would like to work on this issue

**Comment by btkcodedev** [comment]
Raised PR https://github.com/airbytehq/airbyte/pull/31106 😄
