### ISSUE TITLE
Source Square: new stream Inventory

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16855]
## Tell us about the problem you're trying to solve
Retrieves the current calculated stock count for a given [CatalogObject](https://developer.squareup.com/reference/square/objects/CatalogObject) at a given set of [Location](https://developer.squareup.com/reference/square/objects/Location)s.

Responses are paginated and unsorted. For more sophisticated queries, use a batch endpoint.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
NOTE: for this stream INVENTORY_READ scope is obligatory

**Comment by btkcodedev** [comment]
I would like to work on this issue

**Comment by btkcodedev** [comment]
Raised PR https://github.com/airbytehq/airbyte/pull/31107
