### ISSUE TITLE
Source Zendesk Support: new stream Brands

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16869]
## Tell us about the problem you're trying to solve
[Brands](https://developer.zendesk.com/api-reference/ticketing/account-configuration/brands/) are your customer-facing identities. They might represent multiple products or services, or they might literally be multiple brands owned and represented by your company.
The default brand is the one that tickets get assigned to if the ticket is generated from a non-branded channel.

[Allowed for:](https://developer.zendesk.com/api-reference/ticketing/account-configuration/brands/#allowed-for)
- Admins, Agents

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova Source Zendesk Support has already stream brands 
PS: https://github.com/airbytehq/airbyte/blob/5575d86f68279ef452558a34bbf151cebf0313c6/airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py#L711

Please close the issue

**Comment by davydov-d** [comment]
Closing as already implemented
