### ISSUE TITLE
Source Zendesk Support: new stream Custom Agent Roles

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16870]
## Tell us about the problem you're trying to solve
[Custom Agent Roles](https://developer.zendesk.com/api-reference/ticketing/account-configuration/custom_roles/). Zendesk Support accounts on the Enterprise plan or above can provide more granular access to their agents by defining custom agent roles.

**Availability: Accounts on the Enterprise plan or above**

[Allowed for:](https://developer.zendesk.com/api-reference/ticketing/account-configuration/custom_roles/#allowed-for)
- Agents

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova Source Zendesk Support has already stream brands 
PS: https://github.com/airbytehq/airbyte/blob/5575d86f68279ef452558a34bbf151cebf0313c6/airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py#L715

Please close the issue

**Comment by davydov-d** [comment]
Closing as already implemented
