### ISSUE TITLE
Source Zendesk Support: new stream Organization Fields

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16871]
## Tell us about the problem you're trying to solve
You can use this API to add fields to the Organization page in the Zendesk user interface. Basic text fields, date fields, as well as customizable drop-down and number fields are available. The fields correspond to the [Organization Fields](https://developer.zendesk.com/api-reference/ticketing/organizations/organization_fields/) that admins can add using the Zendesk admin interface. 

**The fields are only visible to agents and admins.**

[Allowed for:](https://developer.zendesk.com/api-reference/ticketing/organizations/organization_fields/#allowed-for)
- Agents

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
I would like to work on this issue, Please assign it to me

**Comment by artem1205** [comment]
added in https://github.com/airbytehq/airbyte/pull/30031
