### ISSUE TITLE
Source Zendesk Support: new stream Posts

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16883]
## Tell us about the problem you're trying to solve
A post represents content that a user shares with the community. [Posts](https://developer.zendesk.com/api-reference/help_center/help-center-api/posts/). 

[Allowed for:](https://developer.zendesk.com/api-reference/help_center/help-center-api/posts/#allowed-for)
- Agents
- End users
- Anonymous users

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
I would like to work on this issue

**Comment by jrolom** [comment]
All yours @btkcodedev  fyi @igrankova
