### ISSUE TITLE
Update link of Help section in left column to open GitHub's Discussions tab

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1688]
In the web app, when a user clicks on Help, it opens a new tab towards https://airbyte.io/community
But this page is not very useful, it should open https://github.com/airbytehq/airbyte/discussions/categories/q-a (in a new tab)

cgardens @michel-tricot

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368207218950) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
@cgardens if you agree, I let you prioritize that with Artem, shouldn't take long ;).

**Comment by johnlafleur** [comment]
Actually, if we put the Slack section in the left bar, I'd rather remove the "Help" section from the left bar. 
We will have Settings soon there, and "Help" doesn't bring value, as we bring help through Slack. 
Will rename this issue accordingly.

**Comment by timroes** [comment]
No longer relevant, since there is now a new support menu with more explicit links.
