### ISSUE TITLE
Source RKI (Robert Koch-Institut): Add streams for states.

### ISSUE THREAD

**Issue by Zawar92** [airbytehq/airbyte#16892]
## Tell us about the problem you're trying to solve
In the connector [source-rki-covid](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-rki-covid) we want to add streams for the states that include `history data`, `incidence rate`, `cases`, `deaths`, `hospitalization`

## Describe the solution you’d like
Adding the **streams**, that would cover all these **metrics** using **states** streams.

## Are you willing to submit a PR?
Yes.

**Comment by YowanR** [comment]
Hi Zawar92, we would love to see a contribution from you on this connector! 😄 
cc @sajarin

**Comment by marcosmarxm** [comment]
Closed by #17607
