### ISSUE TITLE
I want a way to be notified when a connection or a job fails.

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1689]
## Tell us about the problem you're trying to solve
Users are not currently notified when connection fails, so they might end up becoming aware of the stale data after a few days. They might want to have the option to become notified by email when a connection fails. 

## Describe the solution you’d like
3 things to build:
* In the onboarding, when users specify their preferences, they should have the option to opt for email notifications when a connection fails
* There should be some settings access in the left column of the web app, where, as a user, I'd be able to change my email notifications
* When a connection fails, I should receive an email. 

There will be other related issues for the settings (https://github.com/airbytehq/airbyte/issues/1690) and for the email (https://github.com/airbytehq/airbyte/issues/1691). 

@cgardens @michel-tricot

**Comment by johnlafleur** [comment]
Here's a suggestion of design for the onboarding preference step: 
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A0

**Comment by michel-tricot** [comment]
Ability to send emails isn't that straight forward. we need a SMTP server open which is risky (spam wise).

We can change the issue to be about the problem we want to solve instead of a possible solution.

`I want a way to be notified when a connection or a job fails.`

**Comment by johnlafleur** [comment]
Fine with me. Updated title. 
Regarding notification means, there are not many we could have: desktop notifications, browser ones or email ones. 
Desktop and browser ones don't seem ideal as you might easily miss any. Wdyt?

**Comment by ChristopheDuong** [comment]
> Fine with me. Updated title.
> Regarding notification means, there are not many we could have: desktop notifications, browser ones or email ones.
> Desktop and browser ones don't seem ideal as you might easily miss any. Wdyt?

If you can easily customize depending on your urgency/critical in your infra:
- Email
- Hipchat
- Slack
- SMS
- Telephone
- etc

Notifications can also be tricky to implement if you have to handle the frequency and avoid being spammy...
- Do you need to escalate your notifications? 
- Should you notify each sync failure? each attempt? 
- possibly generating an email every 5 min? Should you stop at some point? 

What about looking at solutions (open-source?) such as https://cabotapp.com/ for example?

Then we need to focus on what to notify and when and leave the how (channel/medium) to another specialized tool

**Comment by cgardens** [comment]
Scope for what we want from this issue:
1. Send notifications just to slack sync jobs fail.
