### ISSUE TITLE
Settings UI

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1690]
## Tell us about the problem you're trying to solve
In the onboarding, we ask the user about what preferences he'd lke to have (email notifications, anonymization), but he hasn't got any easy way to change them in the UI. 

## Describe the solution you’d like
Let's build a UI for Settings to make it easy for users to change any preferences they might have. 

@cgardens @michel-tricot

**Comment by johnlafleur** [comment]
Here's a suggestion of design for the UI: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A0

A note here: we need to change the icon for "Admin" so we can use the cog for settings.

**Comment by cgardens** [comment]
Per discussion today:
1. if no email is set, then the toggle should be gray out (same behavior as onboarding page). ([issue](https://github.com/airbytehq/airbyte/issues/2643))
2. add email address field to the settings page. behavior: If email is already set, then this field should be grayed out and immutable. if the email field is not set then the user can add an email. in other words the email field is a "set once" behavior.
3. `anonymousDataCollection` - i think you had a question with this but i must have misunderstood it. we already allow setting it in the onboarding page. it's the same field as this one. was there some other question here?
![Screen Shot 2021-03-29 at 1 12 58 PM](https://user-images.githubusercontent.com/9092207/112894467-c1708800-9090-11eb-84dd-592eb2c18728.png)

**Comment by cgardens** [comment]
@Jamakase you should be unblocked now!
