### ISSUE TITLE
Cannot Cancel a Running Sync When You Disable a Connection

### ISSUE THREAD

**Issue by kyle-cheung** [airbytehq/airbyte#16905]
## Environment
Is this your first time deploying Airbyte: No
OS Version / Instance: EC2 t2.large
Memory / Disk: 16Gb
Deployment: Docker
Airbyte Version: 0.40.7

## Current Behavior
We want to reset a connection  and we just upgraded to 0.40.7. If you cancel a running sync it will start to auto-resync. So our first thought was to disable the connection. But once you disable the connection the cancel sync button disappears

<img width="944" alt="image" src="https://user-images.githubusercontent.com/42597757/191127310-008464df-ee0c-4c0a-bb8e-170f10a43439.png">

## Expected Behavior
If you cancel a sync it should not auto re-trigger the sync

**Comment by nataliekwong** [comment]
Hi there! Thanks for your feedback.

As of today, this issue is resolved and the sync will stop once you disable your connection. Let me know if you have any persistent issues. I'll close the issue for now.
