### ISSUE TITLE
Source Chargebee: new stream Credit Note

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16916]
## Tell us about the problem you're trying to solve
A [Credit Note](https://www.chargebee.com/docs/credit-notes.html) is a document that specifies the money owed by a business to its customer. The seller usually issues a Credit Note for the same or lower amount than the invoice, and then repays the money to the customer or set it off against other 'due' invoices.

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688
