### ISSUE TITLE
Facebook Ads: You are calling a deprecated version of the Ads API v15

### ISSUE THREAD

**Issue by ball-hayden** [airbytehq/airbyte#16911]
## Environment
- **Airbyte version**:  0.40.6
- **OS Version / Instance**: Official Docker
- **Deployment**: Kubernetes
- **Source Connector and version**: Facebook Marketing (0.2.63)
- **Destination Connector and version**: BigQuery
- **Step where error happened**: Setup new connection

## Current Behavior

```
FacebookAPIException('Error: 2635, (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v15.0.')
```

## Expected Behavior

Successful Setup

## Logs

N/A

## Steps to Reproduce
1. Create a new Facebook App (as per docs)
2. Add the Facebook Marketing connector
3. See error.

## Are you willing to submit a PR?

Yes, with guidance.

**Comment by vladimir-remar** [comment]
Hi, @ball-hayden, Airbyte uses `FacebookAdsApi` from Facebook, so till they(Facebook) does not update their version,  probably we have to wait. You can see here https://github.com/facebook/facebook-python-business-sdk/blob/main/facebook_business/apiconfig.py which version is use by their SDK, API.

**Comment by ball-hayden** [comment]
Classic. Thanks @vladimir-remar.
I would open an issue upstream, but they have disabled issues. Thanks @facebook.

**Comment by digibeet305** [comment]
I am seeing the same issue. Went from connector 2.63 -> 2.64 -> 2.65, but the problem persists. Any news from FB on their SDK?

**Comment by ball-hayden** [comment]
I didn't open anything upstream with Facebook - it might be worth doing that @digibeet305

**Comment by sh4sh** [comment]
Fyi all, work on this issue is being tracked in https://github.com/airbytehq/airbyte/issues/18167
