### ISSUE TITLE
Source Chargebee: new stream Quote

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16913]
## Tell us about the problem you're trying to solve
A quote is an estimate of the invoice with the charges likely to occur when customers buy an item. A quote can be converted to a regular invoice once the customer accepts it.

The line items of a quote are grouped by charge events and are available as a separate [resource](https://apidocs.chargebee.com/docs/api/quote_line_groups). This resource can be retrieved using the [List quote line groups](https://apidocs.chargebee.com/docs/api/quotes#list_quote_line_groups) endpoint. Note that the first quote line group is available within the quote resource itself and parsing the quote line groups object is not required.

## Describe the solution you’d like
Reserch pros and cons for implementing this stream

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688
