### ISSUE TITLE
Source Zendesk Support: new stream Votes

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16910]
## Tell us about the problem you're trying to solve
[Votes](https://developer.zendesk.com/api-reference/help_center/help-center-api/votes/) represents positive and negative opinions of users about [articles](https://developer.zendesk.com/api-reference/help_center/help-center-api/articles), [article comments](https://developer.zendesk.com/api-reference/help_center/help-center-api/article_comments), [posts](https://developer.zendesk.com/api-reference/help_center/help-center-api/posts) or [post comments](https://developer.zendesk.com/api-reference/help_center/help-center-api/post_comments). 

[Allowed for:](https://developer.zendesk.com/api-reference/help_center/help-center-api/votes/#allowed-for)
- Agents
- End users

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
We expect this stream to be incremental :)

**Comment by haithem-souala** [comment]
Hey @YowanR @justinbchau, i would like to work on this one!

**Comment by justinbchau** [comment]
You got it! @haithem-souala

**Comment by jrolom** [comment]
Hi @haithem-souala  - are you still working on this one? Thanks

**Comment by haithem-souala** [comment]
@jrolom yes, ill push a MR in couple days!
Can you share please the api credentials?

**Comment by jrolom** [comment]
@haithem-souala apologies for the delay here - we have shared the credentials via LastPass, let me know if you can't see them
