### ISSUE TITLE
Source Chargebee: new stream Gift

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16912]
## Tell us about the problem you're trying to solve
Gift represents a subscription of a customer(recipient) to a 'gift plan' which has been gifted by another customer(gifter). It may also have addons and coupons. Gift will be created only on immediate successful payment collection from the gifter's payment method.

Gift is initially created in 'scheduled' state. The gift can be scheduled to be notified on a particular date to the recipient by passing 'scheduled_at'. If not, the recipient is notified immediately. Gift will be moved to 'unclaimed' state on the date of notification. If you pass auto_claim as true, gift status will be moved to ‘claimed’ immediately, otherwise, the gift will remain 'unclaimed' till the recipient claims the gift.

If the gift is not claimed before the claim_expiry_date, it will be moved to the 'expired' state.

## Describe the solution you’d like
Research pros and cons for implementing this stream

NOTE: this stream available only for Sacle and Enterprise Plans

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688
