### ISSUE TITLE
Source Chargebee: new stream Promotional Credits

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16924]
## Tell us about the problem you're trying to solve
These credits can be provided to the customer for promoting the product. You can use Promotional Credits to offer referral bonuses, cash back offers and more. When a customer has promotional credits, it is automatically applied whenever a new invoice is created.

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688
