### ISSUE TITLE
Source Mailchimp: Get Member activities

### ISSUE THREAD

**Issue by philipherrmann** [airbytehq/airbyte#1693]
We would like to have the Mailchimp Member Activities available as an entity in the Mailchimp connector.

## Describe the solution you’d like
After reading the Mailchimp API docs for a while, I think it would be good to have the connector looping over all (recent) campaigns and get the activity feed via
https://mailchimp.com/developer/marketing/api/email-activity-reports/list-email-activity/
on a per campaign basis. Since this endpoint allows for delta loads by using the since parameter.

## Describe the alternative you’ve considered or used
Other endpoints are available (https://mailchimp.com/developer/marketing/api/list-member-activity-feed/ or https://mailchimp.com/developer/marketing/api/list-member-activity/view-recent-activity-50/ ) but harder to query in a well performing way for large user bases.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368083463210) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thanks @philipherrmann! we will take a look at it

**Comment by michel-tricot** [comment]
@philipherrmann Out of curiosity, is it something you would want to contribute to? We could guide you through the process.

**Comment by vitaliizazmic** [comment]
@sherifnada I think this task should be divided into two tasks. First one for checking and comparing three described API endpoints. Second for implementing stream via the most appropriate method.

**Comment by sherifnada** [comment]
There are also batch endpoints available, more context will be in #1936

**Comment by sherifnada** [comment]
@eugene-kulak  Recommending that we go with the first endpoint: https://mailchimp.com/developer/marketing/api/email-activity-reports/list-email-activity/ because it's the least nested
