### ISSUE TITLE
Source Amplitude: uses incorrect `cursor_field`

### ISSUE THREAD

**Issue by myles-novick** [airbytehq/airbyte#16943]
# Environment
- **Airbyte version**:  0.40.7
- **Source Connector and version**: Amplitude 0.1.13
- **Step where error happened**: Sync job

## Current Behavior
According to [Amplitude documentation](https://www.docs.developers.amplitude.com/analytics/apis/export-api/#considerations) (see: first bullet point under "Considerations"), the intended cursor field for the Export API is `"server_upload_time"`. Currently, `cursor_field` in the Amplitude source is set to `"event_time"`

## Expected Behavior
`cursor_field` in the Amplitude source should be set to `"server_upload_time"`

## Are you willing to submit a PR?
Yes

**Comment by sajarin** [comment]
Thanks for the issue @myles-novick, we'd be happy to review the PR if you're still willing to work on it. Thanks!

**Comment by myles-novick** [comment]
> Thanks for the issue @myles-novick, we'd be happy to review the PR if you're still willing to work on it. Thanks!

Great! Just opened a PR here: https://github.com/airbytehq/airbyte/pull/17268

**Comment by artem1205** [comment]
@jnr0790 , This issue will be solved in [PR](https://github.com/airbytehq/airbyte/pull/22362), which is ready to be merged.

Unfortunately, required changes are breaking changes, so customers should refresh source schema and reset `events` stream.

**Comment by amaliaroye** [comment]
@artem1205 Just sent out the outreach to affected Cloud customers for the update to be released next Thursday, April 13th

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/22362
