### ISSUE TITLE
Source Chargebee: new stream Hosted Pages

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#16946]
## Tell us about the problem you're trying to solve
Hosted pages are the easiest and most secure way to integrate chargebee with your website. By using hosted pages, you can avoid the sensitive card information passing through your server and be compliant with most of the PCI DSS requirements.

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/21688
