### ISSUE TITLE
Secrets record tab as password.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1695]
## Expected Behavior
* Using tab should bring me to the next field. 

## Current Behavior
* Instead it inserts Tab as password.

gif of the behavior (a little hard to tell from the gif, but i'm just hitting tab over and over again):
![Screen Cast 2021-01-18 at 10 15 25 AM](https://user-images.githubusercontent.com/9092207/104951088-be616900-5976-11eb-927e-7461cd85f983.gif)

corresponding http request made if i submit the form from the gif:
![Screen Shot 2021-01-18 at 10 17 44 AM](https://user-images.githubusercontent.com/9092207/104951052-a8ec3f00-5976-11eb-80ff-9873b133c223.png)

**Comment by cgardens** [comment]
Similar actually is if i click into a field with an existing password and hit backspace once it records the backspace.

gif (in this gif, i delete the entire password field and then enter abc1 as the password, then reload the page click in the password field and hit back space once. below are the http requests that are made.

![Screen Cast 2021-01-18 at 10 30 20 AM](https://user-images.githubusercontent.com/9092207/104952020-89eeac80-5978-11eb-9c30-a826e0440225.gif)

http requests:
![Screen Shot 2021-01-18 at 10 31 25 AM](https://user-images.githubusercontent.com/9092207/104952030-91ae5100-5978-11eb-8245-2b3e48bb6caa.png)

![Screen Shot 2021-01-18 at 10 30 59 AM](https://user-images.githubusercontent.com/9092207/104952039-96730500-5978-11eb-8b91-2fcd2f5cafed.png)

**Comment by cgardens** [comment]
Discussed during the sync yesterday. @Jamakase is going to explore what we can do to make this a little more robust.

**Comment by jrhizor** [comment]
Extra characters get added for me almost every time I paste something, even if I clicked in the field directly. This causes probably 80% of preventable configuration issues for me personally. 

I imagine this is a huge contributor to onboarding dropoff.

**Comment by cgardens** [comment]
Agreed. We are hoping to push something out for this today.
