### ISSUE TITLE
Source Stripe: new stream Application Fees

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16955]
## Tell us about the problem you're trying to solve
[Application Fees](https://stripe.com/docs/api/application_fees)
When you collect a transaction fee on top of a charge made for your user (using [Connect](https://stripe.com/docs/connect)), an Application Fee object is created in your account. You can list, retrieve, and refund application fees. 

[Permission](https://stripe.com/docs/security/permissions) _application_fee_read, application_fee_write_ Grants access to [Application Fees](https://stripe.com/docs/api/application_fees)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova The mentioned PR will solve the issue, Please assign the issue to me
