### ISSUE TITLE
Source Stripe: new stream Application Fee Refunds

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16956]
## Tell us about the problem you're trying to solve
[Application Fee Refunds](https://stripe.com/docs/api/fee_refunds)
Application Fee Refund objects allow you to refund an application fee that has previously been created but not yet refunded. Funds will be refunded to the Stripe account from which the fee was originally collected.

[Permission](https://stripe.com/docs/security/permissions)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
Note: We expect this stream to be incremental.

**Comment by btkcodedev** [comment]
I would like to work on this one

**Comment by igrankova** [comment]
@sherifnada, @bmcgilli, FYI 
we have a contributor, who wants to take this issue.

**Comment by igrankova** [comment]
@btkcodedev, hi!
thank you for taking this issue to work, I kindly ask you to update expected records to match newly generated sandbox data as well.
@jrolom, FYI

**Comment by btkcodedev** [comment]
Thanks, Can I get the sandbox credentials if there is one stored in LastPass?

**Comment by btkcodedev** [comment]
Update: This application fee refunds needs a parent stream fee which doesn't support post, so it could not be seeded via cURL, I could add it as empty stream with parent

**Comment by btkcodedev** [comment]
Please assign this to me to start working :)

**Comment by igrankova** [comment]
@btkcodedev you're assigned:)
