### ISSUE TITLE
Source Stripe: new stream Prices

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16967]
## Tell us about the problem you're trying to solve
[Prices](https://stripe.com/docs/api/prices)
Prices define the unit cost, currency, and (optional) billing cycle for both recurring and one-time purchases of products. [Products](https://stripe.com/docs/api/prices#products) help you track inventory or provisioning, and prices help you track payment terms. Different physical goods or levels of service should be represented by products, and pricing options should be represented by prices. This approach lets you change prices without having to change your provisioning scheme.
For example, you might have a single "gold" product that has prices for $10/month, $100/year, and €9 once.

[Permission](https://stripe.com/docs/security/permissions)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova @jrolom
I would like to work on this issue

**Comment by btkcodedev** [comment]
It's under review, will be available soon
