### ISSUE TITLE
Source Stripe: new stream Person

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16965]
## Tell us about the problem you're trying to solve
[Person](https://stripe.com/docs/api/persons)
This is an object representing a person associated with a Stripe account.
A platform cannot access a Standard or Express account's persons after the account starts onboarding, such as after generating an account link for the account. See the [Standard onboarding](https://stripe.com/docs/connect/standard-accounts) or [Express onboarding documentation](https://stripe.com/docs/connect/express-accounts) for information about platform pre-filling and account onboarding steps.

[Permission](https://stripe.com/docs/security/permissions)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova, I would like to work on this issue

**Comment by btkcodedev** [comment]
Please assign it to me
