### ISSUE TITLE
Source Stripe: new stream Credit Note

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16960]
## Tell us about the problem you're trying to solve
[Credit Note](https://stripe.com/docs/api/credit_notes)
Issue a credit note to adjust an invoice's amount after the invoice is finalized.

[Permission](https://stripe.com/docs/security/permissions) _credit_note_read, credit_note_write_ Grants access to [Credit Notes](https://stripe.com/docs/api/credit_notes). This permission also implies the following permissions: _invoice_read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by mrhallak** [comment]
Hey @airbyteio I submitted a [PR](https://github.com/airbytehq/airbyte/pull/24666) for this, can someone take a look/assign me to this issue? 🙌🏻
