### ISSUE TITLE
Source Stripe: new stream Plans

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16966]
## Tell us about the problem you're trying to solve
[Plans](https://stripe.com/docs/api/plans)
You can now model subscriptions more flexibly using the [Prices API](https://stripe.com/docs/api/plans#prices). It replaces the Plans API and is backwards compatible to simplify your migration.
Plans define the base price, currency, and billing cycle for recurring purchases of products. [Products](https://stripe.com/docs/api/plans#products) help you track inventory or provisioning, and plans help you track pricing. Different physical goods or levels of service should be represented by products, and pricing options should be represented by plans. This approach lets you change prices without having to change your provisioning scheme.
For example, you might have a single "gold" product that has plans for $10/month, $100/year, €9/month, and €90/year.

[Permission](https://stripe.com/docs/security/permissions) _plan_read, plan_write_ Grants access to [Plans](https://stripe.com/docs/api/plans)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@igrankova Please assign this to me

**Comment by btkcodedev** [comment]
Update @igrankova Source Stripe has already stream - Plans 
PS: https://github.com/airbytehq/airbyte/blame/7de6e9322f2cd17672847b389a3f038d2eb3afb0/airbyte-integrations/connectors/source-stripe/source_stripe/streams.py#L416
Please close the issue


Unassigning this.

**Comment by btkcodedev** [comment]
Update @igrankova @jrolom  Source Stripe has already stream - Plans 
PS: https://github.com/airbytehq/airbyte/blame/7de6e9322f2cd17672847b389a3f038d2eb3afb0/airbyte-integrations/connectors/source-stripe/source_stripe/streams.py#L416

Please close the issue

Unassigning this, and taking other :)

**Comment by igrankova** [comment]
Already implemented
