### ISSUE TITLE
Source Stripe: new stream Sources

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16979]
## Tell us about the problem you're trying to solve
[Sources](https://stripe.com/docs/api/sources)
Source objects allow you to accept a variety of payment methods. They represent a customer's payment instrument, and can be used with the Stripe API just like a Card object: once chargeable, they can be charged, or can be attached to customers. 

[Permission](https://stripe.com/docs/security/permissions) _source_read, source_write_ Grants access to [Sources](https://stripe.com/docs/api/sources)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by artem1205** [comment]
Deprecated, will use [Payment Methods](https://github.com/airbytehq/airbyte/issues/16963)
![image](https://github.com/airbytehq/airbyte/assets/36314070/d2f5d9f3-de1a-46d1-a3b3-c6b6f8da50fc)
