### ISSUE TITLE
When Discover Schema fails we should show logs

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1697]
## Expected Behavior
* when discover schema fails we should allow user to retry _and_ we should show the logs.

## Current Behavior
* we allow retrying and say that if fails but don't show logs. We should show logs at the bottom just like we do for check connection.
![Screen Shot 2021-01-18 at 10 52 34 AM](https://user-images.githubusercontent.com/9092207/104953625-9b858380-597b-11eb-9bd2-bc35b54656d0.png)

**Comment by Jamakase** [comment]
@cgardens Looks like there is a problem on backend side for this one.

- I created source and destination with bad params.
- do discover_schema  request in 2 ways:
1. make request on `/v1/scheduler/sources/discover_schema`
Body:
```{
  connectionConfiguration: {
    key_id: "1", 
    vendor: "1", 
    key_file: "1", 
    issuer_id: "1", 
    start_date: "2020-11-11T00:00:00Z"
  },
  sourceDefinitionId: "53a5a3ea-f52f-44e3-8b7d-6a7cc94e5395"
}
```
Response:

```
{ message: "Could not find configuration for STANDARD_SOURCE_DEFINITION: 53a5a3ea-f52f-44e3-8b7d-6a7cc94e5395." }
```
2. do request on `/v1/sources/discover_schema`
Request body:
```
{
  sourceId: "53a5a3ea-f52f-44e3-8b7d-6a7cc94e5395"
}
```
Response:
```
{ message: "internal server error" }
```


So as you see - there is no `jobInfo` returned from backend.

Though, I was able to receive logs via `/v1/scheduler/sources/discover_schema` for a good source only once and that time `jobInfo` was displayed correctly. Do not know how to force backend send `jobInfo` again, but when it is present in payload - we display it.

**Comment by cgardens** [comment]
Suggestion for what we should do here: https://github.com/airbytehq/airbyte/pull/1821

**Comment by Jamakase** [comment]
Checked after the PR above is merged - works as a charm
