### ISSUE TITLE
Source Stripe: new stream SetupIntents

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16978]
## Tell us about the problem you're trying to solve
[SetupIntents](https://stripe.com/docs/api/setup_intents)
A SetupIntent guides you through the process of setting up and saving a customer's payment credentials for future payments. For example, you could use a SetupIntent to set up and save your customer's card without immediately collecting a payment. Later, you can use [PaymentIntents](https://stripe.com/docs/api/setup_intents#payment_intents) to drive the payment flow.

[Permission](https://stripe.com/docs/security/permissions) _setup_intent_read, setup_intent_write_ Grants access to [SetupIntents](https://stripe.com/docs/api/setup_intents). This permission also implies the following permission: _mandate_read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by jhajajaas** [comment]
@YowanR Hi, I would like to work on this one!

**Comment by YowanR** [comment]
Sounds good, @jhajajaas! Looking forward to your contribution!

**Comment by YowanR** [comment]
Quick update here: we expect this stream to be incremental. @jhajajaas Any updates from you?

**Comment by jhajajaas** [comment]
I’m working on it! Almost done! However, I’m on holidays right now - will
be back on 27th Feb
