### ISSUE TITLE
Source Stripe: new stream Usage Records

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16982]
## Tell us about the problem you're trying to solve
[Usage Records](https://stripe.com/docs/api/usage_records)
Usage records allow you to report customer usage and metrics to Stripe for metered billing of subscription prices. 

[Permission](https://stripe.com/docs/security/permissions) _usage_record_read, usage_record_write_ Grants access to [Usage Records](https://stripe.com/docs/api/usage_records)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by artem1205** [comment]
working on it
