### ISSUE TITLE
Marketo Connector Does Not Work At All

### ISSUE THREAD

**Issue by kyle-cheung** [airbytehq/airbyte#16986]
## Environment
Is this your first time deploying Airbyte: No
OS Version / Instance: EC2 t2.large
Memory / Disk: 16Gb
Deployment: Docker
Airbyte Version: 0.40.7
Source name/version: Marketo 0.1.7
Destination name/version: Snowflake 0.4.36
Step: Source connector fail
Description:

Marketo sync does not work at all, there is something wrong with the source connector

## Current Behavior
```
The above exception was the direct cause of the following exception:Traceback (most recent call last): File "/airbyte/integration_code/main.py", line 13, in <module> launch(source, sys.argv[1:]) File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 123, in launch for message in source_entrypoint.run(parsed_args): File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 114, in run for message in generator: File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 128, in read raise e File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 114, in read yield from self._read_stream( File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 179, in _read_stream for record in record_iterator: File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 222, in _read_incremental slices = stream_instance.stream_slices( File "/airbyte/integration_code/source_marketo/source.py", line 194, in stream_slices export = self.create_export(param) File "/airbyte/integration_code/source_marketo/source.py", line 169, in create_export return next(MarketoExportCreate(self.config, stream_name=self.stream_name, param=param).read_records(sync_mode=None), {})

```

See Discourse https://discuss.airbyte.io/t/marketo-connector-does-not-work-at-all/2657

## Expected Behavior
Sync should run

## Logs
[logs-14100 (1).txt](https://github.com/airbytehq/airbyte/files/9617784/logs-14100.1.txt)

## Steps to Reproduce
1. Connect Marketo to Snowflake
2. Press sync
3.

## Are you willing to submit a PR?
Not technical enough :(

**Comment by davydov-d** [comment]
this has been fixed in https://github.com/airbytehq/airbyte/pull/16930, please use latest version of the connector
