### ISSUE TITLE
Source Stripe: new stream Transfer Reversals

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#16981]
## Tell us about the problem you're trying to solve
[Transfer Reversals](https://stripe.com/docs/api/transfer_reversals)
[Stripe Connect](https://stripe.com/docs/connect) platforms can reverse transfers made to a connected account, either entirely or partially, and can also specify whether to refund any related application fees. Transfer reversals add to the platform's balance and subtract from the destination account's balance.

Reversing a transfer that was made for a [destination charge](https://stripe.com/docs/connect/destination-charges) is allowed only up to the amount of the charge. It is possible to reverse a [transfer_group](https://stripe.com/docs/connect/charges-transfers#transfer-options) transfer only if the destination account has enough balance to cover the reversal. 

[Permission](https://stripe.com/docs/security/permissions)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by artem1205** [comment]
working on it
