### ISSUE TITLE
Destination BigQuery: Full Refresh Append does not remove __tmp_dbt tables

### ISSUE THREAD

**Issue by ciklista** [airbytehq/airbyte#16994]
## Environment
- **Airbyte version**: 0.40.7
- **Deployment**: Docker
- **Destination Connector and version**: BigQuery 1.2.1
- **Step where error happened**: Sync job

## Current Behavior
We are running an airbyte connection between a Postgres and BigQuery. We use the Full Refresh Append mode and have the tabular data normalization enabled. If I am correct, when normalizing airbyte raw data dbt is used under the hood. 
When the sync job is done, we see that for every table loaded to BigQuery, we get a `TABLE_NAME__dbt_tmp` table in our BigQuery dataset. These don't get removed after the sync job is complete. 
This might be related to this dbt issue: https://github.com/dbt-labs/dbt-bigquery/issues/184

## Expected Behavior
I would expect these tmp tables to be removed once the sync job successfully completed. 

## Steps to Reproduce
1. Set up a connection to BigQuery that supports Full Refresh Append

## Are you willing to submit a PR?
happy to help.

**Comment by rodireich** [comment]
[Oncall issue #1068](https://github.com/airbytehq/oncall/issues/1068) is seeing this
