### ISSUE TITLE
Source postgres CDC state messages missing

### ISSUE THREAD

**Issue by shrodingers** [airbytehq/airbyte#16991]
## Environment
- **Airbyte version**:  0.40.7
- **OS Version / Instance**: AWS EC2
- **Deployment**:  Docker
- **Source Connector and version**: Postgres 1.0.7
- **Destination Connector and version**: S3 0.3.15
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

Randomly, on some connections (the ones that usually have the most load), the source and destination does not output any state message, even though some rows were committed, resulting on a late state, and making a full refresh to be triggered afterwards, since WAL cursor (confirmed_flush_lsn) has been updated but not persisted to state

## Expected Behavior

The state of the connection should be up to date with the state of confirmed_flush_lsn, and there should never be some full refresh implicitely (cause huge bloat on 300 GB databases replicated multiple times)

## Logs
[logs-125690.txt](https://github.com/airbytehq/airbyte/files/9618071/logs-125690.txt)

## Steps to Reproduce
1. Setup postgres CDC -> S3 replication on an active table with quite huge amounts of data
2. Wait for some sync no to emit state message

## Are you willing to submit a PR?
With great pleasure ! But I need more context on the state messages handling. Seeing the randomness of the happening, I can but guess this could be some kind of unsync between airbyte-worker and connectors images

**Comment by shrodingers** [comment]
Investigated a bit further, and compiled a custom connector image with more debug to trace, but seems to me that it is caused by the code here never reaching the end
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/AirbyteDebeziumHandler.java#L142
and thus https://github.com/airbytehq/airbyte/blob/550dfb9827de38970004d15e0afc98e6f0337f13/airbyte-integrations/bases/debezium-v1-9-2/src/main/java/io/airbyte/integrations/debezium/AirbyteDebeziumHandler.java#L132
never to be called.
But i have little knowledge in Java, and not at all in the AutoCloseableIterators behaviour

**Comment by harshithmullapudi** [comment]
Thanks a lot this helps. The team will look into this soon.

**Comment by shrodingers** [comment]
Have more details on this kind of failure as I just saw it happen : 
Here you'll find two logs (consecutive runs), with the LSN details on each : 
First run : 
[logs-127051 (1).txt](https://github.com/airbytehq/airbyte/files/9635124/logs-127051.1.txt)
Which ends with a state of : 

`{"{\"schema\":null,\"payload\":[\"production-service-emitter\",{\"server\":\"production-service-emitter\"}]}":"{\"transaction_id\":null,\"lsn_proc\":25948141915240,\"lsn_commit\":25948141960760,\"lsn\":25948141915240,\"txId\":1254060275,\"ts_usec\":1663920429158773}`

The state is correctly persisted to the jobs database for the connection as : 

`{
  "state": {
    "{\"schema\":null,\"payload\":[\"production-service-emitter\",{\"server\":\"production-service-emitter\"}]}": "{\"transaction_id\":null,\"lsn_proc\":25948141915240,\"lsn_commit\":25948141960760,\"lsn\":25948141915240,\"txId\":1254060275,\"ts_usec\":1663920429158773}"
  }
}`

But on the second run it fails to recover the proper lsn and thus fully resyncs the connection (had to zip because log was too large): 

[logs-127086.txt.zip](https://github.com/airbytehq/airbyte/files/9635149/logs-127086.txt.zip)

I really don't get what is going on here, since it finds this state : 

`{transaction_id=null, lsn_proc=25948141915240, lsn_commit=25948141915240, lsn=25948141915240, txId=1254060275, ts_usec=1663920429158773}` when recovering the offsets, which does not match the state persisted in the jobs database. 

Hope this helps, since i'm a bit stuck on investigating this, as it don't really makes sense to me (and is quite annoying when its makes you sync 300GO of useless data everyday)

**Comment by shrodingers** [comment]
Omg, found the issue for the latter problem, it comes from debezium itself, which did not use the correct lsn in such case... [https://github.com/debezium/debezium/commit/38cd6907ae10eda404933c9d395b77e9cea34217](ref here), found out while scrolling through the responsible code. it's fixed in v2.0 but in the meantime idk what shall be done if debezium update is too huge (maybe emitting a modified state with lsn_proc = lsn_commit). At leats i think that is what i'll do locally to fix immediate issues

**Comment by subodh1810** [comment]
Closing this, see https://github.com/airbytehq/airbyte/issues/14932#issuecomment-1275295753

**Comment by shrodingers** [comment]
@subodh1810 , sorry to reopen this but the main goal of this issue was a third situation : sometimes everything goes fine but the Postgres CDC source does not output any state message (as per the initial log). This also causes a full refresh, but not because of an error and lsn ack, only because the source did not output state message, so the initial state is persisted and next run is a full refresh.
Imo this situation shall not appear, since source il always supposed to emit a state message at the end (or multiple ones throughout the sync for long ones)

Hope it's clearer regarding what this issue is about :)
