### ISSUE TITLE
State is saved for 1 stream (out of 3) only (after Airbyte upgrade)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17003]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2354](https://airbyte7538.zendesk.com/agent/tickets/2354)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Pretty much as titled. I had this connector developed, which was working fine for more than a month now. After upgrading Airbyte, however, it started saving state for 1 out of 3 streams - for others it does full resync everytime.</p>
<p dir="auto">The state message I see in the UI is this:</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/e/e9b60bf1069ec803db4c7857564c59b50a979b1c.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/e/e9b60bf1069ec803db4c7857564c59b50a979b1c.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>819×333 8.26 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">However, using</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">python main.py read --config secrets/config.json --catalog integration_tests/configured_catalog.json | grep STATE | tail -n 1 | jq .state.data &gt; integration_tests/sample_state.json</p>
</blockquote>
<p dir="auto">command in terminal (locally), as per tutorial, outputs  me a proper state, which I’d expect in the Airbyte’s instance as well:</p>
<p dir="auto"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/1/15d7c0afb4e9088c414e0c031ee0db7338a28517.png" alt="image" width="auto" height="auto" style="max-width: 100%;"></p>
<p dir="auto">Any advice?</p> 

[<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-19 at 16:02:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">These, btw, are two logs files for two consecutive streams. It seems that transactions state was updated, and thus it was not resynced fully. Order and Customers streams were resynced from the beginning.</p>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/x4V1Tlk1uXiDTkU2Uzsu2Fi7M6I.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-532.txt</a> (364.1 KB)<br>
<a href="https://discuss.airbyte.io/uploads/short-url/qP6rI1RK5hQJ2wYNhqxS85WqDlj.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">logs-538.txt</a> (282.2 KB)</p>
<p dir="auto">It seems that correct state was captured (see, e.g., line 1502 in logs-532). However, it somehow wasn’t saved (?)</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/2" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-19 at 18:02:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 12:17:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">UPDATE.</p>
<p dir="auto">It seems to do indeed with airbyte version. This is from a test on the latest version:</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/2/27b33c6faf0864ef247fedf0d3074dcd5b4c004e.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/2/27b33c6faf0864ef247fedf0d3074dcd5b4c004e_2_690x349.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1907×965 49.2 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">This is a test on an older version of Airbyte:</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/c/c40215e53d9a4d3222d5f578be0014874cff1c45.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/c/c40215e53d9a4d3222d5f578be0014874cff1c45_2_690x341.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1897×940 55.8 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">All other settings are identical.</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 16:47:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">OK, I am pretty sure it has to do with this response:</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">State capture: Updated state to: Optional[io.airbyte.config.State@396c01f1[state=[{“type”:“STREAM”,“stream”:{“stream_descriptor”:{“name”:“transactions”},“stream_state”:{“dateCreated”:“2022-09-20 18:48:30”}},“data”:{“transactions”:{“dateCreated”:“2022-09-20 18:48:30”},“customers”:{“dateCreated”:“2022-09-20 18:48:14”},“order”:{“dateCreated”:“2022-09-20 18:48:35”}}}]]]</p>
</blockquote>
<p dir="auto">(this is from sync logs).</p>
<p dir="auto">Comparing to other active connectors, I believe it should not include thi weird looking part:</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">…[{“type”:“STREAM”,“stream”:{“stream_descriptor”:{“name”:“transactions”},“stream_state”:{“dateCreated”:“2022-09-20 18:48:30”}}</p>
</blockquote>
<p dir="auto">(which is then followed with expected :</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">“data”:{“transactions”:{“dateCreated”:“2022-09-20 18:48:30”},“customers”:{“dateCreated”:“2022-09-20 18:48:14”},“order”:{“dateCreated”:“2022-09-20 18:48:35”}}}]]]</p>
</blockquote>
<p dir="auto">)</p>
<p dir="auto">Any inights - anybody?</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 19:08:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Another update:</p>
<p dir="auto">complete rewrite of the connector, using ABC instead of IncrementalMixin and different state saving logic, had no effect. State still seems to be in a wrong format.</p>
<p dir="auto">I am completely lost at this point.</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 19:29:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Can confirm that the rewritten connector:</p>
<ol dir="auto">
<li style="padding-bottom: 10px;">Results in proper state in Airbyte 0.39.30 alpha</li>
<li style="padding-bottom: 10px;">Results in wrong state in Airbyte 0.40.7</li>
</ol>
<p dir="auto">As this remains a solo thread, my only choice remains downgrade.</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sajarin on 2022-09-21 at 19:54:*

<blockquote><div class="zd-comment" dir="auto">Hey @Albinas_Plesnys,&nbsp;<br>&nbsp;<br>Thanks for making this post. I'm sorry to hear your previously working connection is now only partially working as expected. I believe we did make some changes with state since version 39.30 alpha but I'm not entirely sure what the culprit could be. I made an issue on Github about your issue here: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17003">https://github.com/airbytehq/airbyte/issues/17003</a><br>&nbsp;<br>Please follow the discussion there for the latest updates.&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-22 at 10:17:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks, I appreciate that!</p> 

 [<a href="https://discuss.airbyte.io/t/state-is-saved-for-1-stream-out-of-3-only-after-airbyte-upgrade/2643/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
@sajarin for what source this happens?

**Comment by sajarin** [comment]
@marcosmarxm looks like this is a custom connector for konnectivecrm (based on the logs)

**Comment by marcosmarxm** [comment]
I don't think is an issue possible to solve. There are a lot of examples of connectors saving the state.
Probably it is a problem of implementation of the custom connector. 
I'm closing it because we don't have access to user custom code.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-12-06 at 18:06:*

<blockquote><div class="zd-comment" dir="auto">Albinas, you must share the custom of your connector. Airbyte has a lot of sources saving multiple states.&nbsp;<br></div></blockquote>
