### ISSUE TITLE
Source Amazon S3: new file type .tsv

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17019]
## Tell us about the problem you're trying to solve
[API Reference](https://arrow.apache.org/docs/python/api.html)
Implement .tsv for Amazon S3

## Describe the solution you’d like
Research pros and cons for implementing this file type.

**Comment by tolik0** [comment]
TSV files are supported in the connector, but due to this issue (https://github.com/airbytehq/airbyte/issues/31018), they are not accessible via the UI.
