### ISSUE TITLE
UI caching does not evict modified records

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1701]
## Expected Behavior
I created a source (named "sf") then deleted it. However, when I visit the "sources" page in the UI, the source is still there. I suspect this is because of caching in the UI not evicting this source even though it was removed. 

![Screen Shot 2021-01-18 at 3 29 09 PM](https://user-images.githubusercontent.com/6246757/104970969-1d88a300-59a2-11eb-9c8b-7f7d1bd6d41c.png)

the screenshot is from when I clicked the source tab _after_ deleting the source. I have to use cmd-shift-r to bust the chrome cache, then the source disappears.

**Comment by sherifnada** [comment]
@cgardens assigning to you for prioritization with artem

**Comment by cgardens** [comment]
ok

**Comment by Jamakase** [comment]
@sherifnada can't reproduce this one. Do you still have this problem?

**Comment by cgardens** [comment]
reassigning to @sherifnada to either confirm this still exists and give new steps for reproducing or close.

**Comment by sherifnada** [comment]
Unable to repro. Will reopen if this appears agian.
