### ISSUE TITLE
Source Mailchimp: new stream Reports

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17026]
## Tell us about the problem you're trying to solve
[Reports](https://mailchimp.com/developer/marketing/api/reports/)
Manage campaign reports for your Mailchimp account. All Reports endpoints are read-only. Mailchimp's campaign and automation reports analyze clicks, opens, subscribers' social activity, e-commerce data, and more. Note: Campaign IDs for A/B Testing Campaigns are available through the Campaign API Endpoint's Read method.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
We expect this new stream to be incremental! :)

**Comment by haithem-souala** [comment]
Ill work on this

**Comment by YowanR** [comment]
Just assigned this issue to you! Looking forward to your PR 💪

**Comment by haithem-souala** [comment]
@YowanR, PR pushed, i cannot run the /test cmd, is there a new process to run cmds for maintainers/contributors?

**Comment by YowanR** [comment]
I believe that only members of Airbyte can run these commands now. @sh4sh @natalyjazzviolin Can you please confirm and also review the PR? Thanks 🙏

**Comment by YowanR** [comment]
Looks like this PR was merged! Thanks @haithem-souala ! 🙏
