### ISSUE TITLE
Source Mailchimp: new stream Automations

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17024]
## Tell us about the problem you're trying to solve
[Automations](https://mailchimp.com/developer/marketing/api/automation/)
Mailchimp's classic automations feature lets you build a series of emails that send to subscribers when triggered by a specific date, activity, or event. Use the API to manage Automation workflows, emails, and queues. Does not include Customer Journeys.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
I'll like to work on this one

**Comment by btkcodedev** [comment]
@YowanR Done with incremental behaviour
https://github.com/airbytehq/airbyte/pull/23290
