### ISSUE TITLE
Source Google Analytics: new stream Advanced reports feature

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17036]
## Tell us about the problem you're trying to solve
[Advanced reports feature](https://developers.google.com/analytics/devguides/reporting/data/v1/advanced)
This document describes several advanced features of the Google Analytics Data API v1.

[Access and data-restriction management](https://support.google.com/analytics/answer/9305587?visit_id=637970324634256599-4110973024&rd=1#zippy=%2Cgoogle-analytics)

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
@YowanR @igrankova 
Is the URL correct?
It redirects to Google Analytics instead of Stripe? 
Is there a mismatch?

**Comment by igrankova** [comment]
@btkcodedev I guess something went wrong. I'll update the link. Sorry for this.

**Comment by igrankova** [comment]
Covered by Custom Reports
