### ISSUE TITLE
Source Hubspot: new stream Email Subscriptions

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17034]
## Tell us about the problem you're trying to solve
[Email Subscriptions](https://legacydocs.hubspot.com/docs/methods/email/email_subscriptions_overview)
The Email Subscriptions API can be used to build integrations with other Business Intelligence (BI) systems for reporting.

[Scopes](https://legacydocs.hubspot.com/docs/methods/oauth2/initiate-oauth-integration#)
Content scope provides access to _All CMS APIs, Calendar API, Email and Email Events APIs_. Account types that can access the scope - _Marketing Professional_, or _Enterprise_.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by Alcadeus0** [comment]
@YowanR I'd like to take up this issue :)

**Comment by YowanR** [comment]
Just assigned it to you, @Alcadeus0! Looking forward to your contribution! 💪 🚀

**Comment by Alcadeus0** [comment]
The Email Subscription API stream can be implemented fairly easily similar to the Email Events API that has already been implemented.
Stream in my opinion should only support OAuth as Hubspot API keys will soon be depreciated
Scope for Email Subscription API is "content".
The base stream to be implemented is the Email subscription types for a particular Hubspot ID
The stream will be subject to the normal rate limit set by hubspot (free plan allows 250k reqs daily)

The stream can be implemented using the Python cdk and can be incremental.
It is also possible to support other streams from the subscription stream such as the subscription timeline and subscription email status streams

**Comment by Alcadeus0** [comment]
@igrankova is the above sufficient enough research to get started working on the stream?

**Comment by YowanR** [comment]
@Alcadeus0 Thank you for sharing your research! While I agree with the API keys getting deprecated, I'm wondering if we can still support it so that all streams are at parity. We'll deprecate Api keys at the connector level once the depreciation goes into effect. What do you think?
Other than that, I'm looking forward to this contribution! Cc @sajarin/ @natalyjazzviolin

**Comment by Alcadeus0** [comment]
@YowanR Thanks for the feedback. While Hubspot has indicated that the API keys can be deactivated anytime since Nov 30, 2022, we should still be able to support provided the keys still work at the time. In total there are 4 streams to be implemented with this API.
