### ISSUE TITLE
airbyte-webapp ingress has wrong context

### ISSUE THREAD

**Issue by Patrick-Boerzel-Qunis** [airbytehq/airbyte#17049]
## Environment
- **Airbyte version**:  0.40.8
- **OS Version / Instance**: AKS
- **Deployment**: Kubernetes / Helm
- **Step where error happened**: Deploy

## Current Behavior
While deploying airbyte to K8s on AKS with webapp.ingress configured, an error is shown.

## Expected Behavior
The ingress should work with existing setup.

## Logs
`Error: UPGRADE FAILED: template: webapp/templates/ingress.yaml:53:33: executing "webapp/templates/ingress.yaml" at <.Release.Name>: nil pointer evaluating interface {}.Name`

## Comment

The given chart iterates (via range) over paths and this changes the context ('.') to the current item. On line 53 .Release.Name is accessed but now . is the wrong context.

https://github.com/airbytehq/airbyte/blob/bb39b36016ca32baba3a762ee2a56fe3da358bcc/charts/airbyte-webapp/templates/ingress.yaml#L45-L60

**Comment by koconder** [comment]
Same as https://github.com/airbytehq/airbyte/issues/16800

**Comment by koconder** [comment]
@sajarin duplicate PR and issue, already merged pending roease of the helm charts
