### ISSUE TITLE
Support CockroachDB as a new source connector

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1705]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084037114) by [Unito](https://www.unito.io)

Use postgresql jdbc driver and refer postgres source.

**Comment by cgardens** [comment]
cool. i've always wanted to try out cockroachdb.

**Comment by sherifnada** [comment]
FTR Testcontainers offers something for cockroach, and it is JDBC compatible.

**Comment by etsybaev** [comment]
Notes:
In CockroachDB, every table requires a primary key. If one is not explicitly defined, a column called rowid of the type INT is added automatically as the primary key, with the unique_rowid() function used to ensure that new rows always default to unique rowid values. The primary key is automatically indexed. (https://www.cockroachlabs.com/docs/stable/create-table.html)
