### ISSUE TITLE
Flaky acceptance test

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#17053]
## What

When running `./tools/bin/acceptance_test.sh` (End-to-End Acceptance Tests from the Build step), from the logs, looks like we can get stuck on `Waiting for docker deployment..`.

Looking at the [acceptance_test.sh](https://github.com/airbytehq/airbyte/blob/master/tools/bin/acceptance_test.sh#L20), it seems like `/api/v1/health` is not returning 200.
```
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/api/v1/health)" != "200" ]]; do echo "Waiting for docker deployment.."; sleep 5; done
```

**Comment by gosusnp** [comment]
Happened twice within 8h
https://github.com/airbytehq/airbyte/actions/runs/3101796637/jobs/5023512597
https://github.com/airbytehq/airbyte/actions/runs/3103257737/jobs/5026417637

**Comment by gosusnp** [comment]
This doesn't show up as test failure but as build being cancelled for running too long instead.

**Comment by davinchia** [comment]
Closing this as out of date.
