### ISSUE TITLE
JDBC Sources: Consolidate putDate behavior, and potentially other methods

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17068]
Multiple sources override the default putDate implementation (https://github.com/airbytehq/airbyte/blob/00927128459cf5d77aea9bf375163e347974d994/airbyte-db/db-lib/src/main/java/io/airbyte/db/jdbc/AbstractJdbcCompatibleSourceOperations.java#L126-L128), because it's incorrect. Specifically, it produces a full ISO8601 timestamp, when dates should just be `YYYY-MM-DD`.

Postgres and Mysql currently have the exact same implementation (https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java#L214-L217), and we intend to add that to Snowflake as well. Would be good to just modify the base class and fix this for all JDBC sources.

---

We should probably also check for other methods in a similar situation, and consolidate them too.

**Comment by VitaliiMaltsev** [comment]
@edgao i have made a small investigation into DATE datatype in different databases
For the most of them `YYYY-MM-DD` is a valid pattern for DATE but also we have exceptions like OracleDb
DATE in OracleDb could contain not only year/month/day but also time so for Oracle `yyyy-MM-dd'T'HH:mm:ss` is a valid pattern
1. Should we use the common putDate for all jdbc sources with pattern `YYYY-MM-DD` and override it for OracleDb?
2. Which is a correct way to handle DATE column if it is a cursor field in incremental sync and all of previously synced records have full ISO8601 timestamp pattern?

**Comment by edgao** [comment]
if an oracle `DATE` column can include a timestamp... shouldn't we just discover it as a timestamp without timezone?

**Comment by VitaliiMaltsev** [comment]
> if an oracle `DATE` column can include a timestamp... shouldn't we just discover it as a timestamp without timezone?

yes, we can do it. Do I understand you correctly that it is necessary to do what I described in paragraph 1?

**Comment by edgao** [comment]
yeah, that sounds right. I.e. most DB sources would continue to discover `date` fields, and write `YYYY-MM-DD` values; only source-oracle would discover `timestamp_without_timezone` and write full timestamp values

for previously-synced data - wouldn't the time component always be `00:00:00`? so we can always just ignore it

**Comment by VitaliiMaltsev** [comment]
blocked by https://github.com/airbytehq/airbyte/pull/20634
