### ISSUE TITLE
Update Notification Settings design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17087]
Update the design in the OSS notification settings page with `Scenario #5` in the prototype:

https://www.figma.com/proto/SBtckxQGXX9V1jXLUgwRYp/01_02_NOTIFICATIONS?page-id=0%3A1&node-id=120%3A1522&viewport=865%2C929%2C0.15&scaling=min-zoom&starting-point-node-id=120%3A1812&show-proto-sidebar=1

* Move the save button under the card
* Leave the test button visible (and disable when webhooks is empty)
* Improve documentation panel
* Ensure switches are disabled when webhook is blank

**Comment by matter-q** [comment]
@edmundito, where can i find documentation links?

![image.png](https://images.zenhubusercontent.com/62beeb7e8ea880aea38f18ed/32fc05e3-1683-4cd3-8a6a-d75e34dc6c9d)

**Comment by edmundito** [comment]
Discussed with @matter-q on standup. Need to follow up with @Amruta-Ranade to create documentation. In the meantime, update and release page without the documentation panel.

**Comment by edmundito** [comment]
I followed up with @Amruta-Ranade on slack. It looks like we have a doc for this here:

https://docs.airbyte.com/operator-guides/configuring-sync-notifications/#set-up-slack-notifications-on-sync-status
And the video:
https://www.youtube.com/watch?v=NjYm8F-KiFc

@andyjih Can you confirm that these two cover what's intended in the design help?

**Comment by Amruta-Ranade** [comment]
Note: The doc doesn't show up on our Docs sidebar nav yet. I need to investigate why and fix the issue. Waiting until we confirm that's the content we need

**Comment by andyjih** [comment]
Confirming that those links are correct!
