### ISSUE TITLE
Source Facebook Marketing: populate test account with insight data

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1709]
## Tell us about the problem you're trying to solve
Both FB Marketing sources (singer and non-singer) don't have a reliable way to test `ads_insights*` stream because there is no tracking data. Because of this issue #1699 had to comment-out all Insight streams.

## Describe the solution you’d like
It is still not clear if there is a way to populate test account with insights, which means we need somehow provide tracking events.
### Create ads, creatives and generate tracking events (how?).
https://www.facebook.com/business/learn/lessons/how-to-capture-events-with-facebook-pixel

### Using sandboxes
From https://developers.facebook.com/ads/blog/post/v2/2016/10/19/sandbox-ad-accounts/:

> Simulated insights data will be available in future releases of Sandbox mode. This data will have correct formatting, but otherwise it is simply artificial data which represents the type of information you would get. We do not guarantee that this data represents real-world logical conditions, you should not make any assumptions from these mock metrics.

### Upload offline tracking
https://www.facebook.com/business/help/155437961572700?id=565900110447546
This might require a business account.

## Describe the alternative you’ve considered or used
N/A

**Comment by sherifnada** [comment]
Conclusion of this ticket: 
* Facebook sandbox accounts do not support insight data. Facebook support confirmed this [here](https://developers.facebook.com/support/bugs/244870917177079/). 
* I created a real advertising campaign on our Facebook account to populate the account with data. The account now has data in all insights streams. 

With this the ticket is considered closed.
