### ISSUE TITLE
Create a data set that includes all available data types for Postgres

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#17091]

**Comment by etsybaev** [comment]
![Selection_497.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/ee993c54-9805-4463-8809-80347f271506)

**Comment by grishick** [comment]
Where can I find this dataset?

**Comment by grishick** [comment]
@evantahler this data set might be useful (if we can access it and use it in tests)
