### ISSUE TITLE
Source FacebookPages: getting page access_token error

### ISSUE THREAD

**Issue by grubberr** [airbytehq/airbyte#17099]
When connector tries to exchange Oauth2.0 `access_token` on page `access_token`:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/source.py#L40

it gets an error:

```
{'error': {'message': '(#100) Tried accessing nonexisting field (access_token) on node type (User)', 'type': 'OAuthException', 'code': 100, 'fbtrace_id': 'A4nSbHjsD_BVbkjB35rMxHY'}}
```

**Comment by YowanR** [comment]
Let's try to tackle this one in the next sprint. @YuliiaNahoha @grubberr

**Comment by YowanR** [comment]
@YuliiaNahoha @lazebnyi I had tagged you in this one a month ago. Can we take look, please?

**Comment by lazebnyi** [comment]
@artem1205 take a look on this please

**Comment by artem1205** [comment]
@YowanR, this bug should be solved after [migration to low-code](https://github.com/airbytehq/airbyte/pull/19788)

**Comment by grubberr** [comment]
@ycherniaiev please look on this issue maybe it will clarify your problem with `access_token`

**Comment by artem1205** [comment]
fixed while migrating to Low-code
