### ISSUE TITLE
Create data set with dummy data

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#17092]
## Tell us about the problem you're trying to solve
Our main goal is to collect benchmarks in order to improve connectors' reliability and performance. 
It will help us to identify the limits and find a way to make them wider.

## Describe the solution you’d like
We should create a set of tables within a single schema, that could be used for different testing scenarios.
We should start with 5GB/10GB/15GB/25GB which in total will allow us to test a 50GB load.

[ ] - Create a group of tables with a total size of 5GB
[ ] - Create a group of tables with a total size of 10GB
[ ] - Create a group of tables with a total size of 15GB
[ ] - Create a group of tables with a total size of 25GB

## Additional context
We are going to run different scenarios to sync one large table with many columns and records in it (up to 1GB in total).
Also, it coud be great to have smaller tables with up to 20 columns and up to 5m records in each, but with total size more than 10GB.

**Comment by evantahler** [comment]
You could use an existing airbyte connector to generate this king of data - I like `source-faker` or `source-e2e`

**Comment by evantahler** [comment]
@akashkulk I'm closing this issue - you've got newer work in the same topic
