### ISSUE TITLE
DATs should verify non-default namespace behavior

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17105]
from https://docs.google.com/document/d/15xLW97ZqPnttLluP80ZCqXxCHHzB-vn8bhBBpUmjGMI/edit#

Apparently it's possible for a destination to only write data into its default namespace and still pass our DATs. We should add a test case that verifies it can write to a non-default namespace. I.e. if the catalog looks like:
```json
{
  "streams": [
    {
      "stream": {
        "name": "whatever",
        "namespace": "some_non_default_namespace",
        "json_schema": {...}
      }
    }
  ]
}
```

Then the DATs should verify that after a sync, a table called `some_non_default_namespace.whatever` was created.

## Details

It looks like this test case already exists - https://github.com/airbytehq/airbyte/blob/09154f3351fadcaa799edb29169d09e3daed8f0a/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java#L950

Let's look into why it wasn't failing prior to https://github.com/airbytehq/airbyte/pull/17054, and fix that. (A likely avenue of investigation: should this [`sourcenamespace`](https://github.com/airbytehq/airbyte/blob/09154f3351fadcaa799edb29169d09e3daed8f0a/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java#L960) be randomized per test run?)

In order to run `BigQueryGcsDestinationAcceptanceTest` locally, you'll need to manually create `airbyte-integrations/connectors/destination-bigquery/secrets/credentials.json`, using the contents [here](https://console.cloud.google.com/security/secret-manager/secret/SECRET_DESTINATION-BIGQUERY_CREDENTIALS__CREDS/versions?project=dataline-integration-testing).

And you can explore our integration test BigQuery instance [here](https://console.cloud.google.com/bigquery?project=dataline-integration-testing&ws=!1m4!1m3!3m2!1sdataline-integration-testing!2ssourcenamespace).

**Comment by jbfbell** [comment]
Continued Investigating this with @edgao today and discovered that the integration testing for the big query destination does not cover the standard inserts mode and only covers staging (GCS). The Bug from the [original oncall issue](https://github.com/airbytehq/oncall/issues/653) only affected the standard inserts mode, thus the test is passing because we are not executing the code which contained the bug (which has since been [resolved](https://github.com/airbytehq/airbyte/pull/17054)
