### ISSUE TITLE
[Helm] Helm chart broken on latest 0.41.2: INSTALLATION FAILED: deployments.apps "airbyte-minio" already exists

### ISSUE THREAD

**Issue by rotemtam** [airbytehq/airbyte#17117]
Error: 

## Environment
- **Airbyte version**:  chart v0.41.2
- **OS Version / Instance**:EKS
- **Deployment**: Kubernetes

## Current Behavior
INSTALLATION FAILED: deployments.apps "airbyte-minio" already exists
## Expected Behavior

*Tell us what should happen.*
Installation on default options should succeed. 

## Steps to Reproduce
1. kubectl create ns data-eng
2. helm install -n data-eng airbyte  airbyte/airbyte

## More info

Installing with `minio.enabled=false` works.
Appears that minio is installed from both the airbyte chart and as a subchart.

**Comment by rotemtam** [comment]
Further issues:

It appears that `mini.enabled: false` does allow for airbyte to load, but I cannot add sources. 

Any source added (including PokeAPI) in this situation errors with:
```
Internal Server Error: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.
```
Further inquiry of the logs shows that the issue isn't network to the service comes from:
```
Cannot start publish with com.van.logging.aws.S3PublishHelper@2f290206 due to error: Cannot start publishing: Unable to execute HTTP request: airbyte-minio-svc: Name or service not known
```
So broken setup here.

**Comment by mnotti** [comment]
Experiencing same issue here.

**Comment by juan-calvo-datatonic** [comment]
The same is true here.

**Comment by DustyShap** [comment]
Same issue here as well

**Comment by sh4sh** [comment]
Hey @rotemtam @mnotti @juan-calvo-datatonic @DustyShap , I was able to deploy v0.40.12 and v0.40.13 successfully with default values. Can you try deploying a newer version and see if the behaviour changes?

**Comment by DustyShap** [comment]
Still getting this:
```Internal Server Error: Unable to execute HTTP request: Connect to airbyte-minio-svc:9000 [airbyte-minio-svc/172.20.12.230] failed: Connect timed out```

**Comment by nzeugaa** [comment]
Experiencing the same issue

**Comment by dinigo** [comment]
After upgrading helm
```
helm repo update airbyte
```
It appears that the main airbyte chart `airbyte/airbyte` was rolled back from `0.41.2` to `0.40.16`. I just deployed it and it seems to be working correctly

**Comment by benpankow** [comment]
I am encountering this issue with the `0.14.16` Helm chart. I see the `airbyte-minio-svc` but no corresponding pods. The service has no endpoints:

```
❯ k describe svc -n airbyte airbyte-minio-svc
Name:              airbyte-minio-svc
Namespace:         airbyte
Labels:            app.kubernetes.io/instance=airbyte
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=airbyte-minio
                   app.kubernetes.io/version=0.40.10
                   helm.sh/chart=airbyte-0.40.16
Annotations:       helm.sh/hook: pre-install,pre-upgrade
                   helm.sh/hook-weight: -1
Selector:          app.kubernetes.io/instance=airbyte,app.kubernetes.io/name=airbyte-minio
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                172.20.14.162
IPs:               172.20.14.162
Port:              <unset>  9000/TCP
TargetPort:        9000/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

```
❯ k get pods -n airbyte
NAME                                                              READY   STATUS      RESTARTS   AGE
airbyte-airbyte-bootloader                                        0/1     Completed   0          3m31s
airbyte-db-0                                                      1/1     Running     1          3m35s
airbyte-pod-sweeper-pod-sweeper-6685c669b-ljpr2                   1/1     Running     0          3m7s
airbyte-server-55f548d999-szsjp                                   1/1     Running     0          3m7s
airbyte-temporal-7d75d4b96d-kpxxr                                 1/1     Running     0          3m7s
airbyte-webapp-5b99866bf4-k5zc7                                   1/1     Running     0          3m7s
airbyte-worker-c75f5474c-bcr69                                    1/1     Running     0          3m7s
ingress-nginx-controller-7d98fb5bd-rhh6n                          1/1     Running     0          3m29s
oauth2-proxy-8c656b4dd-t49nf                                      1/1     Running     0          3m44s
urce-pokeapi-check-46ad1f50-c4a9-4b0a-a39c-c48c7d82a268-0-wmnbu   0/4     Completed   0          53s
```

**Comment by nzeugaa** [comment]
@rotemtam @benpankow chart `0.40.17` fixed this issue

**Comment by benpankow** [comment]
Confirming that this has been fixed for me on `0.40.17` - thanks!

**Comment by marcosmarxm** [comment]
I'm closing as resolved. Let me know if the issue persists

**Comment by rotemtam** [comment]
@sh4sh @marcosmarxm 

Thanks a lot! I will test later to confirm. Can you shed some details on the issue? 

Airbyte seems very promising, but honestly, this experience makes me think that it is not quite ready for real use. Is there some sort of integration testing that is verifying this kind of issue doesn't occur? 

Appreciate all your work, and well done!

**Comment by marcosmarxm** [comment]
>Airbyte seems very promising, but honestly, this experience makes me think that it is not quite ready for real use. Is there some sort of integration testing that is verifying this kind of issue doesn't occur?

The team is working to improve the experience using Helm chart adding it to them main release process. It will be unstable for a couple of days.
