### ISSUE TITLE
UI should trim namespace custom format string

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17113]
On the connection replication settings, if you select "custom format" as the destination namespace, you can enter a custom format string with leading/trailing spaces. There's no reason to ever do that, because destinations/normalization will just remove those spaces anyway (and/or replace them with underscores).

This is causing papercuts, where destinations and normalization sanitize the input differently. That's a bug in connector code, but we can also just solve it once and for all by doing a `.trim()` on this input field. (connectors should also be fixed, but that requires oneoff work per connector, e.g. https://github.com/airbytehq/airbyte/issues/17067)

seen in https://github.com/airbytehq/oncall/issues/638

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
