### ISSUE TITLE
Source SurveyMonkey: new stream Collectors

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#17126]
## Tell us about the problem you're trying to solve
Collectors allow you to collect survey responses with a link to your survey. Many types of collectors are available through the API such as sms, weblink, email and general popup collectors. [Weblink collectors](http://help.surveymonkey.com/articles/en_US/kb/Web-Link-Collector) collectors give you a survey URL, [email invitation collectors](https://help.surveymonkey.com/articles/en_US/kb/Email-Invitation-Collector) and [sms invitation collectors](https://help.surveymonkey.com/articles/en_US/kb/Text-Message) send survey invite messages with a survey URL via the /messages endpoints, [popup collectors](https://help.surveymonkey.com/articles/en_US/kb/Website-Collector) let you embed surveys on your website. A variety of [collector options](http://help.surveymonkey.com/articles/en_US/kb/Collector-Options#List) are accepted as arguments to /surveys/{id}/collectors. All collectors except for weblink collectors and some collector options, for example, is_branding_enabled=False require a [SurveyMonkey paid plan](https://www.surveymonkey.com/pricing/?ut_source=dev_portal&ut_source2=docs).

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by btkcodedev** [comment]
Source SurveyMonkey has already stream Collectors
Ref:- https://github.com/airbytehq/airbyte/blob/9dae0d3c2102a65ce258e3c7215b4da671d46d41/airbyte-integrations/connectors/source-surveymonkey/source_surveymonkey/streams.py#L290
