### ISSUE TITLE
Update Google Analytics Data API custom report doc

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#17141]
### Tell us about the documentation you'd like us to add or update.
Custom reports need to be in Json Format:
[{“name”: “AirbyteForum”,“dimensions”: [“date”,“deviceCategory”,“firstUserSource”,“firstUserMedium”],“metrics”: [“activeUsers”,“totalUsers”,“newUsers”,“sessions”,“transactions”,“totalRevenue”,“userEngagementDuration”,“screenPageViews”]}]

Pointed out in this forum post:
https://discuss.airbyte.io/t/google-analytics-data-api-custom-report-0-0-3-not-working-like-in-0-0-2/2351/5

### If applicable, add links to the relevant docs that should be updated
- [Google Analytics 4 (GA4) source connector](https://docs.airbyte.com/integrations/sources/google-analytics-v4)

**Comment by kdcyberdude** [comment]
Hi @natalyjazzviolin ,
I'm not able to fetch custom reports from GA4 that involve custom dimensions. I can successfully retrieve reports with the default dimensions supported by GA, but when I attempt to add a custom dimension, such as "customEvent:content_type", it fails.
Here's a sample of what I'm trying:
```
[
  {
    "name": "articles",
    "dimensions": [
      "date",
      "pageLocation",
      "customEvent:content_type"
    ],
    "metrics": [
      "screenPageViews"
    ]
  }
]
```
Can you assist me in understanding the correct structure or direct me to the appropriate documentation?

**Comment by lazebnyi** [comment]
Will be fixed with https://github.com/airbytehq/airbyte/issues/23874
