### ISSUE TITLE
Database Sources: Handle when a cursor value is NULL

### ISSUE THREAD

**Issue by bleonard** [airbytehq/airbyte#17150]
[This PR](https://github.com/airbytehq/airbyte/pull/17131) adds the ability for nullable columns to be the cursor. This is to handle the case where the user doesn't really have control over the schema there (or is a view). However, we still need actual values in these columns to reliably sync.

For example, Airbyte sorts the table based on the cursor field and have a where clause `> lastCursorValue`, and different SQL databases put null values differently in sorting. Postgres puts them after non-null values, while SQL Server and MySQL puts them before non-null values.
So it means if there are new null values:
* Postgres connector can sync them, at the price of duplicating all null values each time.
* SQL Server and MySQL cannot sync them, because of the “>” where clause will filter them all out.

We should consider throwing an error to be less surprising and prevent users from getting into a bad state.

**Comment by bleonard** [comment]
Understand current behavior for Postgres when there are null values kin the cursor column
Make a proposal: what should we do?
1. docs?
2. errors at the beginning (check ahead of time or when we come across it)
3. undo our choice

Possible issues I see with NULL:
1. The last row we get has a NULL vlaue, so now the state is NULL and that's not good because it will.... be resyncing everything again? Or will it say > NULL (also not good. crash?)
2. Different systems handle NULL in different ways when we say `> lastCursor` ---- Postgres will _always_ include the NULL ones (so we are sycning them each time. MysQL will _never_ include the NULL ones.

Probably just just don't want it to happen.

For example, is it expensive to do 
`SELECT COUNT(*) FROM table WHERE cursorColumn = NULL LIMIT 1`
That might be expensive for calculated views and a bad idea says @tuliren

**Comment by tuliren** [comment]
> 1. The last row we get has a NULL vlaue, so now the state is NULL

We don't emit NULL state. So this should not be a concern.

**Comment by bleonard** [comment]
can live in the same place where we validate cursor fields. The most interesting thing is probably understanding if there are any danger in the simple query. Throw a config error.

**Comment by subodh1810** [comment]
Re-opening this cause after the [PR](https://github.com/airbytehq/airbyte/pull/19889) was merged and deployed a bunch of connectors started breaking so it was decided that we are going to first just merge a PR which throws warning log and then query logs to figure  out which customers in the cloud would be impacted and then once we reach out to the customers to let them know that they need to fix their data, bring back the config error again

**Comment by rodireich** [comment]
Status update: waiting to put change back. Schedule to 1/24/23
