### ISSUE TITLE
Certify MySQL Source for Beta

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#17162]
- [x] [Create a certification spreadsheet](https://docs.google.com/spreadsheets/d/1PIHkHKeIG-uW2kkHYf3uSjC0H-o9rgtDa89FDu7ll_k/edit#gid=1700962388)
- [x] Link spreadsheet in the issue description
- [x] Checklist filled up by engineering team
- [x] Move checklist to the product team for review
- [x] Reviewed/Updated by product team
- [x] Update connector documentation according to the comments in the checklist
- [ ] Update connector label to Beta
- [ ] Deploy beta connector version to Airbyte Cloud

**Comment by bleonard** [comment]
This one done @grishick ?

**Comment by bleonard** [comment]
This one done @grishick ?
