### ISSUE TITLE
Remove hard-coded optional/required text from connector specifications

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17182]
## What

There are currently a lot of connector specifications that hard-code things like `(Optional)` or `*` on the end of field names. Here are some (non-exhaustive) examples:
https://github.com/airbytehq/airbyte/blob/bbb59d8675603e708736717b461d3ce562266abf/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L716
https://github.com/airbytehq/airbyte/blob/bbb59d8675603e708736717b461d3ce562266abf/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L3400
https://github.com/airbytehq/airbyte/blob/bbb59d8675603e708736717b461d3ce562266abf/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L783
https://github.com/airbytehq/airbyte/blob/bbb59d8675603e708736717b461d3ce562266abf/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L685
- This example is especially confusing, as the hard-coded `*` doesn't even align with which fields are marked as `required` for this connector -- so is this field actually optional or required?

https://github.com/airbytehq/airbyte/blob/e30476e4fd8168684323b3cad7aa83f9336be4e2/airbyte-config/init/src/main/resources/seed/destination_specs.yaml#L457
- It is less clear how this one should be handled. Ideally we would have separate connectors/specs for cloud and for OSS, with this marked properly as optional/required in both

### Why is this bad
This is bad because it is an inconsistent and unreliable way to communicate to users which fields are optional and which are required. We already have a mechanism for doing this, which is to add a field to the `required` section of the spec schema, e.g. here: https://github.com/airbytehq/airbyte/blob/bbb59d8675603e708736717b461d3ce562266abf/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L3153-L3156

This method of marking fields as required is what the UI uses to decide to add an `Optional` tag to the end of a field. So, when a field is not included in the `required` section, and it also has a string in the field name like `(Optional)`, it leads to redundancy in the UI like this:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/22731524/192394387-0229c49e-1655-4f8e-8b6b-4eded47c92e2.png">

## How

All source and destination connector specs should be audited for this issue, any such `(Optional)` or `*` text should be removed from field titles across all connector specs, and these connectors should be re-published so that they are updated in cloud.

**Comment by lmossman** [comment]
FYI @evantahler

**Comment by evantahler** [comment]
@YowanR is this something we can get GL to help us with?

**Comment by evantahler** [comment]
Grooming: 
* We will publish GA and Beta connectors as part of this work

**Comment by YowanR** [comment]
Sorry, I missed this earlier. Will your team be handling this for beta/GA connectors?
Adding @lazebnyi and @YuliiaNahoha as FYI -- this is something we need to take care of going forward.

**Comment by evantahler** [comment]
It's ok - I'll take care of it!
