### ISSUE TITLE
Source Facebook Marketing: new stream Custom Conversions

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17237]
## Tell us about the problem you're trying to solve
[Custom Conversions](https://developers.facebook.com/docs/marketing-api/reference/custom-conversion)
Optimize ads delivery based on online and offline conversion events that you define. Track activity without adding new events Meta Pixel. Custom conversions objects are associated with an [Ad Account](https://developers.facebook.com/docs/marketing-api/reference/ad-account). Use them to describe events you want to measure and events you want to track to optimize ads delivery.

[Permission](https://developers.facebook.com/docs/marketing-api/overview/authorization/) 
You want to read ads reports for ad accounts you own or have been granted access to by the ad account owner. Permission: _ads_read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
Note: We expect this stream to be incremental :)

**Comment by artem1205** [comment]
Added in https://github.com/airbytehq/airbyte/pull/15724
