### ISSUE TITLE
Source BingAds - Campaigns stream misses Audience and Shopping campaigns

### ISSUE THREAD

**Issue by rach-r** [airbytehq/airbyte#17252]
## Environment
- **Source Connector and version**: Bing Ads `0.1.12` 
- **Step where error happened**: After sync job (which is successful), when data modelling for report 

## Current Behavior
While `campaign_performance_report_daily` stream has data for all campaign types (Search, Audience, Shopping), `campaigns` only retrieves Search campaigns type. So the `campaigns` stream is technically incomplete and, for example, we can't get the CampaignType in campaign reports with a simple join.

## Expected Behavior
The `campaigns` stream should include Search, Audience and Shopping campaigns.

## Additional information
- According to the [Bing API docs](https://learn.microsoft.com/en-us/advertising/campaign-management-service/getcampaignsbyaccountid?view=bingads-13#request-body), the `GetCampaignsByAccountId` service only retrieves Search campaigns by default. To get Shopping and Audience campaigns, we need to explicit them in the request
- Change should probably occur [here](https://github.com/airbytehq/airbyte/blob/9dacd5df4dbb49c4fb473b6dd8a1330fdeb23ddc/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/source.py#L205)

## Steps to Reproduce
1. Run a successful job for `campaigns` and `campaign_performance_report_daily` streams
2. If you look at distinct CampaignType in `campaigns`, you only get "Search"
3. If you try to do a left join (main table is `campaign_performance_report_daily` and joined table is `campaigns`) to get CampaignType in the reports then you'll have NULL for campaigns that are not "Search" campaigns

## Are you willing to submit a PR?
Not right away but probably in the future!

**Comment by birdieorbust** [comment]
A list of possible campaign types can be found [here](https://learn.microsoft.com/en-us/advertising/campaign-management-service/campaigntype?view=bingads-13
). Perhaps an iterable for campaign type like how the Ad Groups stream can be set up to collect all types.
