### ISSUE TITLE
New Destination: DuckDB

### ISSUE THREAD

**Issue by sspaeti** [airbytehq/airbyte#17256]
## Tell us about the new connector you’d like to have
* [DuckDB](https://duckdb.org/) is an in-process SQL OLAP database management system and well suited for:
  * Processing and storing tabular datasets, e.g. from CSV or Parquet files
  * Interactive data analysis, e.g. Joining & aggregate multiple large tables
  * Concurrent large changes, to multiple large tables, e.g. appending rows, adding/removing/updating columns
  * Large result set to transfer to client

> Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
 
  * No

## Describe the context around this new connector

> Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.

It would work well with local files such as Excels, CSV, and Parques, which need to be processed and accessed via SQL. I'm sure there are many more use-cases, but to build up a [personal data warehouse](https://overcast.fm/+w94WYoAHg/44:35) for my finance, importing all my bank transactions on credit card bills.

> How often do you want to run syncs?

 Every hour 

## Describe the alternative you are considering or using
> What are you considering doing if you don’t have this integration through Airbyte?

I'd write some dagster transformation or python script that imports data into DuckDB.

## Are you willing to submit a PR?
Yes :)

**Comment by sspaeti** [comment]
Started PR: https://github.com/airbytehq/airbyte/pull/17494

**Comment by sspaeti** [comment]
Update:
- [ ] store DuckDB file locally outside of the docker container
- [ ] Unit Tests

It works:
![image](https://user-images.githubusercontent.com/689199/195713653-1809ab21-a898-4d0e-94ec-911e6b6851ac.png)

**Comment by sw-yx** [comment]
https://github.com/airbytehq/airbyte/pull/17494
