### ISSUE TITLE
Connection form Yup validation schema Typescript improvements

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#17279]
The yup validation schema for the forms related to connection creation/editing need better typing.  Currently we have some typecasting going on.  Ideally, we should not.

Separated this out of the "main" connection form refactor PRs to keep the deliverables smaller.

Part of the fix will be the schedule type:
```
    scheduleType: new yup.StringSchema<ConnectionScheduleType>().oneOf([
      ConnectionScheduleType.manual,
      ConnectionScheduleType.basic,
      ConnectionScheduleType.cron,
    ]),
```

For clarification, this ticket should cover this [TODO](https://github.com/airbytehq/airbyte/pull/16748/files/ddc15733cd724685937a93ec099cf92fd6e1a1c4#diff-1dcd8cef75eb629fd1a5e4c1de7aa3f58bbcb1071e9c687302fb740cb6bf2b1aR37)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by dizel852** [comment]
Seems like this one can be fixed in scope of https://github.com/airbytehq/airbyte/issues/29585
