### ISSUE TITLE
Destination Bigquery (maybe also denormalized): find limits of standard inserts

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17282]
We should provide users some guidance for when users should switch from standard inserts to GCS staging. This is especially true for BigQuery, where an insert-based upload can time out (https://github.com/airbytehq/oncall/issues/575).

Using the [benchmark connection](https://cloud.airbyte.io/workspaces/f4bbed8e-8533-4d14-82dd-277b672164d8/connections/28a4c33f-192d-40cd-9d7d-4d3e7d39dcf0/status) (might need to duplicate the mock source and make a new connection), and try to find a point where syncs start failing. Some dimensions to explore:
* number of streams
* number of fields within a stream
* number of records within a stream

The mock source provides some utilities to make this easier: (see https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1664308805140129?thread_ts=1664304081.205679&cid=C03C4AVJWG4)
* Increase `Duplicate the stream N times` to make more tables
* Add entries to `Stream schema` to get more fields
* Increase `Max records` to make more records

**Comment by etsybaev** [comment]
May be related to https://github.com/airbytehq/airbyte/issues/19196

**Comment by edgao** [comment]
yeah let's just close this as a dup
