### ISSUE TITLE
Upgrade to @tanstack/react-table

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17290]
We're currently using `react-table` (v7) for our `Table` component. The typings we use in there are not properly generic and with the upgrade to React v18 will fail in several places. Rewriting those types will take some time, such I suggest we should directly also upgrade `react-table` to its successor [`@tanstack/react-table`](https://tanstack.com/table/v8/) v8. That way we won't need to adjust typings for v7 now and later on once we would want to upgrade to a newer version again, but instead should just try to fix the types for the newer version directly.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This work was already done in #17941. Closing...
