### ISSUE TITLE
Google Ads incompatible fields syncing error

### ISSUE THREAD

**Issue by vitaliizazmic** [airbytehq/airbyte#1730]
## Current Behavior
Much of the report types in Ads API have fields which is not compatible with another. E.g, field AbsoluteTopImpressionPercentage in AD_PERFORMANCE_REPORT is not compatible whith ClickType, ConversionAdjustment, ConversionAdjustmentLagBucket, ConversionCategoryName, ConversionLagBucket, ConversionTrackerId, ConversionTypeName, ExternalConversionSource, Slot. It leads to sync error.

Tap Adwords has custom metadata key [fieldExclusions](https://github.com/singer-io/tap-adwords/tree/d70cf858389ae70ed342213bc9633561dd119318#metadata-reference) to indicate which other fields may not be selected when this field is selected. If you invoke the tap with selections that violate fieldExclusion rules, the tap will fail.

Syncing incompatible fields was disabled in #1726

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084086061) by [Unito](https://www.unito.io)

**Comment by cetchells** [comment]
I have adwords setup and syncing successfully, with Postgres destination. However the table names suffixed with PERFORMANCE_REPORT are always empty as are the airbyte raw tables. I assume this is therefore related to this issue, incompatible fields. The report tables are probably the most useful data for me for collating ad spend etc. over time as they are the ones that contain costs. Would be great to get a fix for this. Happy to do any testing if needed.

**Comment by cgardens** [comment]
@sherifnada this issue has been around for a long time now and it seems like it is hard to fix. is there a reason that we aren't at least documenting it in the adwords docs, until we can fix it permanently, to avoid user confusion in the short term?

**Comment by sherifnada** [comment]
closing as won't do since we are deprecating adwords in favor of google ads api
