### ISSUE TITLE
Source Greenhouse: new stream Offices

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#17305]
## Tell us about the problem you're trying to solve
List all of an organization’s offices.
HTTP Request
GET https://harvest.greenhouse.io/v1/offices

Retrieve an office by its ID.
HTTP Request
GET https://harvest.greenhouse.io/v1/offices/{id}

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

**Comment by igrankova** [comment]
Already implemented
