### ISSUE TITLE
Source Greenhouse: new stream User Permissions

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#17307]
## Tell us about the problem you're trying to solve
<html>
<body>
<p style="margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(84, 88, 90); font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">List the job permissions for a given user.</p><h3 id="http-request" style="font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 15px; font-weight: bold; margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; margin-top: 2.5em; margin-bottom: 0.8em; color: rgb(84, 88, 90); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP Request</h3><p style="margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(84, 88, 90); font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="prettyprint" style="font-family: Consolas, Menlo, Monaco, &quot;Lucida Console&quot;, &quot;Liberation Mono&quot;, &quot;DejaVu Sans Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, &quot;Courier New&quot;, monospace, serif; font-size: 12px; line-height: 1.5; word-break: break-word; hyphens: auto; background-color: rgba(0, 0, 0, 0.05); padding: 3px; border-radius: 3px;">GET https://harvest.greenhouse.io/v1/users/{id}/permissions/jobs</code></p><h3 id="url-parameters" style="font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 15px; font-weight: bold; margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; margin-top: 2.5em; margin-bottom: 0.8em; color: rgb(84, 88, 90); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">URL Parameters</h3>

Parameter | Description
-- | --
id | The ID of the user whose job permissions to retrieve

<p style="margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(84, 88, 90); font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Note: This endpoint is only intended for use with Job Admin and/or Interviewer users, as these roles are assigned on a per job basis. Users that are Site Admins have permissions on all public jobs and will return an empty array. Basic users cannot be assigned to any jobs and will also return an empty array.</p><p style="margin-right: 506.667px; padding: 0px 28px; box-sizing: border-box; display: block; line-height: 1.6; margin-top: 0px; color: rgb(84, 88, 90); font-family: LLAkkuratWeb-Regular, Helmut, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This endpoint supports pagination. See the<span> </span><a href="https://developers.greenhouse.io/harvest.html#pagination" style="background-color: transparent;">Pagination</a><span> </span>section for more detail.</p>
</body>
</html>

## Describe the solution you’d like
Research pros and cons for implementing this stream.

**Comment by igrankova** [comment]
Already implemented
