### ISSUE TITLE
Import Data does not delete config records that are not present in the imported data

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1731]
## Steps to Reproduce
1. Export data
1. Create a new source or destination
1. Import data
1. We would expect that that source or destination would no longer exist, but it is still there.

Looks like the importer just doesn't handle wiping out existing records first

**Comment by ChristopheDuong** [comment]
We didn't say that you have to run some deletion of docker volumes yourself though?

7. Delete the existing Airbyte docker volumes. _Note: Make sure you have already exported your data (step 3). This command is going to delete your data in Docker!_
```bash
docker volume rm $(docker volume ls -q | grep airbyte)
```

**Comment by cgardens** [comment]
Discussed offline. This behavior is still a little weird, if you import data onto an instance that you haven't wiped, but not inexplicable. We can leave this as if for now.
