### ISSUE TITLE
Destination BigQuery (normalization): Investigate "pickling client objects is not supported" error

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17327]
see https://github.com/airbytehq/oncall/issues/417

Normalization fails with this error:
```
2022-09-20 18:26:17 normalization > Unhandled error while executing model.<redacted>.<redacted>
Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
2022-09-20 18:26:17 normalization > 2 of 2 ERROR creating incremental model <redacted>.<redacted>............................................... [ERROR in 0.64s]
```

Enabling GCS staging on the bigquery destination config apparently helps, but it's unclear why that would change anything. Possibly actually a permissions problem, since they also switched the dataset ID.

---

my original theorizing: (https://github.com/airbytehq/oncall/issues/417#issuecomment-1226588642)

> This error is pretty weird - I suspect it's actually hiding some other error message, which we don't have a great way to recover. That would explain why resetting streams resolved it. (ref: similar-looking issue on a completely unrelated github repo https://github.com/PrefectHQ/prefect/issues/2178; the tl;dr is that Google's bigquery library returns an error object that behaves weirdly, so it gets logged in a useless way)

**Comment by noviceanalyst** [comment]
Hi,

I am getting this exact error while trying to connect hubspot to big query for the first time. Specifically, I get errors that look like this for any tables that I try to transfer, whether contacts, campaign, e-mail, etc.

```
Unhandled error while executing model.airbyte_utils.contacts
Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
1 of 2 ERROR creating table model Marketing.contacts.................................................................... [ERROR in 0.43s]
Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
Unhandled error while executing model.airbyte_utils.contacts
Pickling client objects is explicitly not supported.
Clients have non-trivial state that is local and unpickleable.
1 of 2 ERROR creating table model Marketing.contacts.................................................................... [ERROR in 0.43s]
Pickling client objects is explicitly not supported.

```
When we sync with raw json instead of tabular normalization, the records do transfer to big query as json entries in the resultant table. I am new to Airbyte so any suggestions in the right direction are welcome.

**Comment by edgao** [comment]
can you post the full log file from the sync? I was looking into this recently and it looked like the source actually failed, which led to some  `_raw` tables not being created (https://github.com/airbytehq/airbyte/issues/17926) - would be great to confirm/deny that theory.

**Comment by noviceanalyst** [comment]
HI @edgao please find attached the error log.


[huspot_bq_errorlog.txt](https://github.com/airbytehq/airbyte/files/9788714/huspot_bq_errorlog.txt)

**Comment by edgao** [comment]
interesting - so it sounds like e.g. `Marketing._airbyte_raw_contact_lists` exists and is non-empty? (the sync in your logs produced 0 records, I'm guessing there was a previous sync that did actually process data?)

That's certainly different behavior from what I ran into. Doesn't seem like a dataset ID mismatch either (destination and normalization both referenced the `Marketing` dataset) so presumably normalization is looking for raw tables in the right location.

**Comment by killthekitten** [comment]
We're getting the same error on two very different connections: PostgreSQL CDC -> BigQuery and Stripe -> BigQuery. 

What's interesting, identical connections run just fine when not using the GCS staging area. Previously we haven't used the staging area at all, so it might be related to the staging bucket or service account configuration.

While I won't be comfortable sharing the entire log, I could share parts of it that are relevant to investigation is needed. For example, I've seen this happening a lot in the log (but not with all streams):

```
2022-10-27 12:33:52 [43mdestination[0m >  For more details see Big Query Error collection: BigQueryError{reason=accessDenied, location=null, message=Access Denied: File gs://<staging_area_name_redacted>/<name_redacted>/<name_redacted>_checkout_sessions/2022/10/27/03/c4a35eda-05aa-4703-b03f-6ab1d223649d/1.avro: Access Denied}:
2022-10-27 12:33:52 [43mdestination[0m > 2022-10-27 12:33:52 [32mINFO[m i.a.i.d.b.BigQueryGcsOperations(cleanUpStage):152 - Deleting staging files for stream checkout_sessions (dataset <name_redacted>): [1.avro]
2022-10-27 12:33:52 [43mdestination[0m > 2022-10-27 12:33:52 [32mINFO[m i.a.i.d.s.S3StorageOperations(cleanUpBucketObject):290 - Storage bucket <name_redacted>/<name_redacted>_checkout_sessions has been cleaned-up (0 objects were deleted)...
2022-10-27 12:33:52 [43mdestination[0m > 2022-10-27 12:33:52 [1;31mERROR[m i.a.i.d.b.BufferedStreamConsumer(close):199 - Close failed.
2022-10-27 12:33:52 [43mdestination[0m > java.lang.RuntimeException: Failed to upload data from stage <name_redacted>/<name_redacted>_checkout_sessions/2022/10/27/03/c4a35eda-05aa-4703-b03f-6ab1d223649d/
```

**Comment by killthekitten** [comment]
^ Update, it was indeed a misconfiguration. There was two service accounts involved:
- Default service account; can access BigQuery, can't access to the staging bucket
- Custom staging area service account; can't access BigQuery, can access the bucket

The destination was configured to use the default account (no JSON uploaded) and the HMAC key of the bucket account. I figure this means the data could be written to the bucket, but couldn't be loaded to BigQuery.

I fixed this by adding the bucket account JSON to the destination and updating the permissions of that account to also have access to BigQuery.

**Comment by edgao** [comment]
@killthekitten nice debugging, and thanks for the detailed report! There's also got an issue open to improve `check` behavior, because the connector should catch that sort of thing when you hit the save+retest button (https://github.com/airbytehq/airbyte/issues/16992#issuecomment-1290942921)

just to be super explicit - once you solved the permissions problems, your syncs were able to run successfully?

**Comment by killthekitten** [comment]
@edgao that's right, the sync completed correctly and the errors are not present in the log.

Thanks for referring the check discussion, that one actually helped me diagnose the issue, I just forgot to mention it.

**Comment by edgao** [comment]
got it. I think the general statement is that the service account needs to have both bigquery write and GCS read permissions - if GCP didn't require GCS read permissions, then malicious actors could circumvent GCS permissioning by running a bigquery load operation. I'll update our docs to make that more explicit.

**Comment by killthekitten** [comment]
@edgao agreed! The confusing part is that service accounts are mentioned in multiple places, in different context.

In the pre-requisites section: 
> (Required for Airbyte Cloud; Optional for Airbyte Open Source) A Google Cloud [Service Account](https://cloud.google.com/iam/docs/service-accounts) with the [BigQuery User](https://cloud.google.com/bigquery/docs/access-control#bigquery) and [BigQuery Data Editor](https://cloud.google.com/bigquery/docs/access-control#bigquery) roles and the [Service Account Key in JSON format](https://cloud.google.com/iam/docs/creating-managing-service-account-keys).

In the storage bucket guide:
> 2. [Create an HMAC key and access ID](https://cloud.google.com/storage/docs/authentication/managing-hmackeys#create).
> 3. Grant the [Storage Object Admin role](https://cloud.google.com/storage/docs/access-control/iam-roles#standard-roles) to the Google Cloud [Service Account](https://cloud.google.com/iam/docs/service-accounts).

And in the connector setup guide:
> For Service Account Key JSON (Required for cloud, optional for open-source), enter the Google Cloud [Service Account Key in JSON format](https://cloud.google.com/iam/docs/creating-managing-service-account-keys).

The bit from the storage bucket is especially confusing (and probably dangerous). When I followed the [Create HMAC key and access ID guide]((https://cloud.google.com/storage/docs/authentication/managing-hmackeys#create)), I've actually created a service account on the spot, as it was a part of the GCS interoperability settings wizard. It didn't occur to me that I could specify the service account already used by airbyte (we run our instance on GCP).

I'd say the doc needs a bit of restructuring and deserves a separate section talking about service accounts, and their possible combinations. The reader might have either one or two service accounts configured, and whether they've attached the JSON in the destination settings or not, would define how this combination behaves.

**Comment by noviceanalyst** [comment]
> interesting - so it sounds like e.g. `Marketing._airbyte_raw_contact_lists` exists and is non-empty? (the sync in your logs produced 0 records, I'm guessing there was a previous sync that did actually process data?)
> 
> That's certainly different behavior from what I ran into. Doesn't seem like a dataset ID mismatch either (destination and normalization both referenced the `Marketing` dataset) so presumably normalization is looking for raw tables in the right location.

@edgao I did create Dataset ID, but not tables. I assumed that airbyte would create the required tables from the json files. Is this assumption wrong?

**Comment by noviceanalyst** [comment]
@edgao I was able to resolve my issue with the tabular normalization today. I am not sure what really changed, but I created a new destination connection to BigQuery and made sure that my destination during setup in BQ and in Airbyte were the same (for example both have location as us central 1) just picking US in Airbyte and is going to throw a destination error. Also, for the GCS Bucket name and Bucket path was confusing for me in the beginning , but I ended up not creating a folder in the bucket, thus the name of the bucket and the bucket path are the same this time around. Finally I got a new service account key json for the bucket project I created. I had done all these in the past so I cannot point out specifically that this was what solved the issue. I started out with just 2 streams (raw json) and when that sync succeeded, I then tried the normalization and it worked. If I figure out what caused the sync to work this time around I will be sure to return and share my findings. Thank you @edgao  for taking time to read the error log.

Regards,
Noviceanalyst

**Comment by bloodyburger** [comment]
I get the same error "Pickling client objects is explicitly not supported.", moving data from Postgresql to BigQuery in Standard Mode.

**Comment by haithem-souala** [comment]
+1 
MSSQL -> BQ (GCS staging)

**Comment by goldengrisha** [comment]
Using `Raw data (JSON)` in the transformation tab solved the issue.

**Comment by edgao** [comment]
we've released bigquery under destinations v2, which replaces normalization. DV2 doesn't use dbt under the hood, so we'll never see this error again. Closing this issue.

**Comment by PaxonF** [comment]
> we've released bigquery under destinations v2, which replaces normalization. DV2 doesn't use dbt under the hood, so we'll never see this error again. Closing this issue.

@edgao I'm on the latest BigQuery Destination Connector (2.3.16) and still get the "pickling client objects is not supported" error on quite a few of my source connectors...

Is it still in progress of being released, or does it only work with some sources? (I'm using Airbyte Open Source btw)

**Comment by edgao** [comment]
that's surprising - normalization shouldn't launch at all with bigquery 2.x. What version of platform are you using? DV2 destinations [require](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2/#quick-start-to-upgrading) platform version 0.50.24+

**Comment by PaxonF** [comment]
I just upgraded to 0.50.34

**Comment by PaxonF** [comment]
@edgao Here are some example logs from Postgres to BigQuery, both on the latest versions of their connectors too: 
[4f5991c5_c655_4d64_b680_583b3ae5e02e_job_22846_attempt_5_txt.txt](https://github.com/airbytehq/airbyte/files/13419937/4f5991c5_c655_4d64_b680_583b3ae5e02e_job_22846_attempt_5_txt.txt)

**Comment by PaxonF** [comment]
I realize now that the reason this was failing is because the "Normalized Tabular Data" option was checked. Switching to "Raw data (JSON)" fixes the issue AND results in normalized tables as needed as long as I delete the schema and do a hard reset (even though the settings are a bit confusing). So, user error on my part.

**Comment by edgao** [comment]
interesting - I'd thought we turned off the ability to use normalization with bigquery 2.x. Glad you figured it out, but I've got some more investigation to do now :) 

(so... user error sort of, but ideally we wouldn't give you the option at all)
