### ISSUE TITLE
DBT is dropping views that depend on normalized tables in Postgres

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1732]
## Current Behavior
* When running a sync if I have a view that depends on a raw table, that view is retained each time a sync runs. (good)
* When running a sync if I have a view that depends on a normalized table, that view gets dropped each time a sync runs. (bad)

## Expected Behavior
* We want views on normalized tables to survive syncs.

## Steps to Reproduce
1. Run a sync into PG with normalization.
1. Create a view on the normalized table.
1. Run sync again
1. Your view is gone!

## Context
Looks pretty similar to the problem described in [this question ](https://discourse.getdbt.com/t/why-are-my-views-being-dropped-when-the-incremental-model-it-refs-is-being-updated/689/11) on the dbt site.

@ChristopheDuong - I'm going to hold off going any further on this for now in case there's some easy thing for you that makes this easy to fix.

**Comment by ChristopheDuong** [comment]
Following recommendations here from DBT:
https://github.com/fishtown-analytics/dbt/issues/2185#issuecomment-595929972

> consider building your dbt project in a separate schema (say, analytics_new), then swap the analytics schema for the analytics_new schema at the end of the run (this is called a blue/green deployment)

**Comment by ChristopheDuong** [comment]
I tried running manual tests to rename schemas without affecting views...

But it seems to be more complex than just renaming schemas since views are updated to point to the new schema name:
https://dba.stackexchange.com/questions/87220/postgresql-rename-table-without-updating-view-definitions

**Comment by cgardens** [comment]
Unfortunately it seems like we don't have a good option here with postgres due to eager binding of views. Our workaround is the following:

Before any query that relies on the view you have to guarantee the view exists. The simplest way of doing this that we know of is to use the postgres `CREATE OR REPLACE VIEW` syntax. Without using other tools on top of postgres, a user needs to fall back on this option or something equivalent when creating views on airbyte normalized tables that are created via full refresh.

e.g. contrived example of making a view of all of the records in the target table
```
CREATE OR REPLACE VIEW airbyte.deduped_orders AS SELECT * FROM foo;
```
