### ISSUE TITLE
Create a data set that includes all available data types for MSSQL

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#17332]
- create benchmark DB
- added tables with all possible datatypes

**Comment by etsybaev** [comment]
![Selection_508.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/1e88a664-420f-41fb-b8d1-0e75a90ffbab)

**Comment by grishick** [comment]
How can I access this data set?
