### ISSUE TITLE
SAT verifies that an incremental stream with no data still produces a state message

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17338]
After an OC issue, we added this to the CDK - https://github.com/airbytehq/airbyte/pull/17296.  However, for connectors which don't use the CDK we should check this assertion

```
In an incremntal sync
if the cursor is already at the highwatermark
(records might be emitted)
but the same state message as before should be re-emitted in the sync
```

We already have a test for "abnormal state" - start looking here

This story is not to make all 200 connectors pass this test, but probably test with one or 2 connectors

**Comment by alafanechere** [comment]
This test is already existing [here](https://github.com/airbytehq/airbyte/blob/515f1e567848775a42a86253d63f827fc8c3494f/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/tests/test_incremental.py#L249).

```python
    def test_state_with_abnormally_large_values(self, connector_config, configured_catalog, future_state, docker_runner: ConnectorRunner):
        configured_catalog = incremental_only_catalog(configured_catalog)
        output = docker_runner.call_read_with_state(config=connector_config, catalog=configured_catalog, state=future_state)
        records = filter_output(output, type_=Type.RECORD)
        states = filter_output(output, type_=Type.STATE)

        assert (
            not records
        ), f"The sync should produce no records when run with the state with abnormally large values {records[0].record.stream}"
        assert states, "The sync should produce at least one STATE message"
```
But this test is optional if `future_state_path` is not declared in `acceptance_test_config.yaml`. 
I'm suggest to:
* add unit-tests for this test
* list all GA/Beta connectors that do not have this test
* Add `future_state_path` to GA/Beta connectors missing it

**Comment by evantahler** [comment]
Planning Notes: 
* Why did notion pass the test?  It should have failed - @alafanechere to investigate. Maybe we are missing some test data or the stream isn't tested?  - It is not.  Only 3 streams are tested.
