### ISSUE TITLE
Create a data set that includes all available data types for Oracle

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#17333]
- create benchmark DB
- added tables with all possible datatypes

**Comment by etsybaev** [comment]
New DB created? creds in Secret manager:: "SECRET_SOURCE_ORACLE_PERFORMANCE_TEST_CREDS"

**Comment by etsybaev** [comment]
![Selection_001.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/03fc7a49-fecc-4e08-91f6-45360b147368)
