### ISSUE TITLE
Create a data set that includes all available data types for MySQL

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#17331]
- create benchmark DB
- added tables with all possible datatypes

**Comment by etsybaev** [comment]
![Selection_506.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/70849fe6-5c42-4f2e-9f57-27d8150d3e4e)

**Comment by grishick** [comment]
How can I access this dataset?

**Comment by grishick** [comment]
@evantahler this data set might be useful (if we can access it and use it in tests)
