### ISSUE TITLE
Remove Connection prop drilling, use Connection Edit Service

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#17345]
Looking at ConnectionItemPage, the TransformationView, StatusView, and SettingsView have the connection object prop-drilled. They should use the ConnectionEditService instead and this change should be propagated downwards where appropriate.

Example: StateBlock.tsx has the connectionId prop-drilled. Can just pull it out of the service.

Please verify that every component changed in this way is not used in places not wrapped with the service!

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Similar to #15609 ?

**Comment by krishnaglick** [comment]
Oh, you're right!
