### ISSUE TITLE
MinaSession error using MySQL and an SSH tunnel

### ISSUE THREAD

**Issue by jbn** [airbytehq/airbyte#17346]
## Environment
- Is this your first time deploying Airbyte?: Yes
- OS Version / Instance: Ubuntu 20.04
- Memory / Disk: 128Gb / 1 Tb
- Deployment: Docker
- Airbyte Version: What version are you using now? 0.40.2
- Source name/version: MySql 0.6.5
- Destination name/version: BigQuery 0.2.0
- Step: Initial Sync
- **MySQL using SSH**

## Current Behavior

First, I couldn't use an `ed22151` key because of `BouncyCastle`. I reverted to `ECDSA` but it kept failing with what I finally realized was the relevant, 

```
2022-08-27 16:51:24 e[44msourcee[0m > 2022-08-27 16:51:23 e[33mWARNe[m o.a.s.c.u.l.LoggingUtils(warn):610 - exceptionCaught(MinaSession[local=/127.0.0.1:37121, remote=/127.0.0.1:46620]) WriteTimeoutException: null
```
Using a locally set up host tunnel was my solution.

## Expected Behavior

It should not fail.

## Logs

[REDACTED]

## See Also

https://discuss.airbyte.io/t/minasession-writetimeoutexception-for-mysql-to-bigquery-sync/2410

**Comment by grishick** [comment]
This should be resolved now

**Comment by rodireich** [comment]
[7198: SSH Tunnel: allow using OPENSSH key format](https://github.com/airbytehq/airbyte/pull/15833)
and
[Publish base-normalization](https://github.com/airbytehq/airbyte/pull/16545)

**Comment by rodireich** [comment]
@jbn The version of mysql you were trying with didn't support the types of keys you are trying to set your tunnel with.
Can you please try with the latest version of mysql. Both ed22151 and ECDSA should be acceptable now.

**Comment by rodireich** [comment]
Closing this as we have no further information. 
Please reopen if there's still an issue.
