### ISSUE TITLE
Create Tech Spec for Decouple normalization from platform version 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17347]
* We are going to skip the PRD, but still include some of the reasons for doing this work
PRD Template  - https://docs.google.com/document/d/1GycFYbt572BrX8szKSkrAhsp_7KeoPyLlaj0lspcgxY/edit
* [Epic](https://github.com/airbytehq/airbyte/issues/16671)

GOAL:
* Releasing a new version of a connector self-defines the normalization container it uses.
* we should be able to write all the stories and get to work

See the Epic for the project overview

**Comment by tuliren** [comment]
https://docs.google.com/document/d/18g3RrOOoMqlXHlgvSJazeq_X-vJ_vlnx7ky0dV-c9r4/edit#
