### ISSUE TITLE
🐛 Netsuite source connector Date Issue

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17357]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2405](https://airbyte7538.zendesk.com/agent/tickets/2405)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sunny

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px">OS Version / Instance:  MacOS</li>
<li style="padding-bottom: 10px">Memory / Disk: you can use something like 4Gb / 1 Tb</li>
<li style="padding-bottom: 10px">Deployment:  Docker</li>
<li style="padding-bottom: 10px">Airbyte Version: 40.7</li>
<li style="padding-bottom: 10px">Source name/version:  netsuite</li>
<li style="padding-bottom: 10px">Destination name/version: Snowflake</li>
<li style="padding-bottom: 10px">Step: The issue is happening in all the scenario of interface. Incremental or Full.</li>
<li style="padding-bottom: 10px">Description: Date format is not matching with Netsuite recent updates.</li>
</ul>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">2022-09-22 17:51:16 e[44msourcee[0m &gt; Stream `customer`: cannot read or find the object. Skipping, full error message: Invalid search query. Detailed unprocessed description follows. Search error occurred: Parse of date/time "01/01/2022" failed with date format "yy-MM-dd" in time zone America/Los_Angeles
Caused by:
java.text.ParseException: Unparseable date: "01/01/2022".
2022-09-22 17:51:16 e[44msourcee[0m &gt; Stream `customer`: cannot read or find the object. Skipping, full error message: Invalid search query. Detailed unprocessed description follows. Search error occurred: Parse of date/time "01/15/2022" failed with date format "yy-MM-dd" in time zone America/Los_Angeles
Caused by:```</code></pre> 

[<a href="https://discuss.airbyte.io/t/netsuite-source-connector-date-issue/2691/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-22 at 21:03:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sunny on 2022-09-28 at 21:30:*

<blockquote><div class="zd-comment" dir="auto">Hey, could you create a github issue about this? The template is here: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/new?assignees=&amp;labels=type%2Fbug%2C+needs-triage&amp;template=bug-report.md&amp;title=">https://github.com/airbytehq/airbyte/issues/new?assignees=&amp;labels=type%2Fbug%2C+needs-triage&amp;template=bug-report.md&amp;title=</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sunny on 2022-09-28 at 21:40:*

<blockquote><div class="zd-comment" dir="auto">Nevermind, issue created: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17357">https://github.com/airbytehq/airbyte/issues/17357</a><br></div></blockquote>

**Comment by i-zaykov** [comment]
Is there a workaround for this at the moment, @marcosmarxm? As far as I can see,https://github.com/airbytehq/airbyte/pull/17470 is being worked on, but I am concerned that it is still in the review process after a month. 🤔

**Comment by bazarnov** [comment]
Hello, @i-zaykov,

Could you please follow up the last comment from https://github.com/airbytehq/airbyte/pull/17470 and answer the question from your side to speedup the process?
