### ISSUE TITLE
Enable workspace creation/deletion

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1735]
## Tell us about the problem you're trying to solve
Some users want to use namespaces to segment configurations in a multi-tenant setup.

## Describe the solution you’d like
Expose the feature. Right now we only rely on a default workspace

## Describe the alternative you’ve considered or used
Some manual segmentation with one namespace

**Comment by gordalina** [comment]
Our use case is one where we're:
- Hosting multiple users in airbyte 
- Users do not have access to airbyte web UI nor to the API, we proxy and handle all calls for them.
- We are currently creating named destinations and connections, it works, but when we're querying the API there's no field to filter either by name.

**Comment by anibalaguirre** [comment]
Hi

We've being testing airbyte for some days and works great .

We also would need to segment configuration data across different customers. Customers will use the airbyte UI .

Thanks
