### ISSUE TITLE
Source Bing Ads: new stream GoalsAndFunnelsReportRequest

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17383]
## Tell us about the problem you're trying to solve
[GoalsAndFunnelsReportRequest](https://learn.microsoft.com/en-us/advertising/reporting-service/goalsandfunnelsreportrequest?view=bingads-13)
Hourly
Daily
Weekly
Monthly
Defines a goals and funnels report request. Use this report to discover whether your audience completes each step through the land, browse, prospect, and conversion pages of your website. For example, you can use this report to determine the step that users leave the conversion funnel, so that you can improve or remove that step to increase the chance that the user will continue to the next step.

[User Roles and Permissions](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#user-roles-permissions)
Your application might only need to support one Super Admin user on a known account. Even with such a relatively simple permission structure you'll want to understand the actions available for each [user role](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#user-roles), how [users are provisioned](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#assign-user-roles) on an account, how you can [discover their current access rights](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#get-user-roles), and how you can [act on behalf of an authenticated Microsoft Advertising user](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#access-developer-token) with the Bing Ads API.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by amrael** [comment]
👍

**Comment by artem1205** [comment]
Moving to on hold as no data in sandbox
