### ISSUE TITLE
Source Bing Ads: new stream GeographicPerformanceReportRequest

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17382]
## Tell us about the problem you're trying to solve
[GeographicPerformanceReportRequest](https://learn.microsoft.com/en-us/advertising/reporting-service/geographicperformancereportrequest?view=bingads-13)
Hourly
Daily
Weekly
Monthly
Defines a geographic performance report request. Use this report to see where your traffic is coming from: the physical location of the people searching for your ad or the locations people are searching for. You can then validate whether your location targeting strategy is successful and identify opportunities to improve.

[User Roles and Permissions](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#user-roles-permissions)
Your application might only need to support one Super Admin user on a known account. Even with such a relatively simple permission structure you'll want to understand the actions available for each [user role](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#user-roles), how [users are provisioned](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#assign-user-roles) on an account, how you can [discover their current access rights](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#get-user-roles), and how you can [act on behalf of an authenticated Microsoft Advertising user](https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13#access-developer-token) with the Bing Ads API.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by jpmmcneill** [comment]
@igrankova this is something that I'd like to contribute if that is ok with you? 😄

**Comment by igrankova** [comment]
@YowanR, FYI, we have a contributor for this issue (above).

**Comment by YowanR** [comment]
Hey @jpmmcneill, we would love to see your contribution to this connector. Thank you! 🙏 
cc @sajarin as FYI

**Comment by tthias** [comment]
@igrankova 

Nice to see that you are working on the Microsoft Ads connector.
Can't wait to use the Geographic splitting !
Do you have any news on it ?

Thanks

**Comment by jpmmcneill** [comment]
Hey @tthias 

I volunteered to do this but haven't had a chance yet!

I might get a chance to do it in the next few weeks.

**Comment by tthias** [comment]
@jpmmcneill 
Nice !

**Comment by jpmmcneill** [comment]
@tthias feel free to take it off my hands if you want to do it instead 😉

**Comment by artem1205** [comment]
Added in #29526
