### ISSUE TITLE
Source Pipedrive: new stream Activity_types

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17396]
## Tell us about the problem you're trying to solve
[Activity_types](https://developers.pipedrive.com/docs/api/v1/ActivityTypes)
Activity types represent different kinds of activities that can be stored. Each activity type is presented to the user with an icon and a name.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _admin_, _recents:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
