### ISSUE TITLE
Source Klaviyo: new stream Templates

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17392]
## Tell us about the problem you're trying to solve
[Templates](https://developers.klaviyo.com/en/reference/get-templates)
Returns a list of all the email templates you've created. The templates are returned in sorted order by _name_.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by YowanR** [comment]
Note: we expect all new streams for this connector to be incremental.

**Comment by geekwhocodes** [comment]
@YowanR I can start working on this. 
#17548 is blocked for now, waiting on response from the author.

**Comment by YowanR** [comment]
I missed this earlier but assigned it to you! :D

**Comment by marcosmarxm** [comment]
Closed by #23236
