### ISSUE TITLE
Source Klaviyo: new stream Profiles

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17393]
## Tell us about the problem you're trying to solve
[Profiles](https://developers.klaviyo.com/en/reference/get-profile)
Returns a list of all the email templates you've created. The templates are returned in sorted order by _name_.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by Dmusulas** [comment]
Hello, are there any plans to implement this stream in the future?

**Comment by igrankova** [comment]
@YowanR we have a request here.

**Comment by BalciunasDominykas** [comment]
+1, would be useful!

**Comment by Dmusulas** [comment]
A month ago Klaviyo updated their API (v2022-10-17) which makes this new stream and some other extremely straightforward. However, other Klaviyo streams are requesting data from legacy version (v1-v2) of Klaviyo API. I suggest to bump other streams to the new version along with inclusion of this one. 

Main benefit of then new version are the following:

- All endpoints now follow the [JSON:API](https://jsonapi.org/) standard
- All endpoints have been rigorously vetted to ensure adherence to consistent URL, request, and response syntactical standards
- The URL topology has been reorganized to promote strong-typing, clear resource separation, and consistency with the Klaviyo UI
- There are now explicitly-documented [rate limits](https://developers.klaviyo.com/en/docs/rate_limits_and_error_handling) for all endpoints with standard, informative HTTP headers for retry control-flow

**Comment by YowanR** [comment]
Note: we expect all new streams for this connector to be incremental.

**Comment by Dmusulas** [comment]
Hey, @jgrinaveckis and me have finished developing this Profiles stream, it works (we are already using it) and it is incremental. @YowanR, could you point out what are the additional steps before we can submit PR?

**Comment by YowanR** [comment]
@sajarin @natalyjazzviolin can you please help get this merged, please?

**Comment by YowanR** [comment]
@sh4sh @natalyjazzviolin Bump here, please!

**Comment by sh4sh** [comment]
@Dmusulas please submit the PR whenever you can, tag me and we can take a look! No worries if it isn't perfect, we can work together to merge it.

**Comment by Wittiest** [comment]
@sh4sh Hi, our team at Nutrisense is interested in using Airbyte to constantly sync all of the profiles from Klaviyo to our destination. Is this the right ticket to track or contribute on usage of the [get_profiles](https://developers.klaviyo.com/en/reference/get_profiles) endpoint?

**Comment by sh4sh** [comment]
@Wittiest yes, this issue will track implementation although there is not yet an open pull request - once that has been submitted, it will be linked to this ticket. If you're interested in developing this feature, the [Contribute to Airbyte](https://docs.airbyte.com/contributing-to-airbyte/) doc has a high level overview of the contribution process and feel free to ping me here or on Slack if you have any questions.

**Comment by Wittiest** [comment]
Hi @sh4sh! I've submitted a PR which should handle this. Do you know the general timeline for reviews and eventually having something go live?
