### ISSUE TITLE
Source Jenkins: error using depth field during connector configuration

### ISSUE THREAD

**Issue by EdsonJuniorPD** [airbytehq/airbyte#17400]
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**:  jenkins-source 0.1.23 
- **Destination Connector and version**: Postgres 0.3.21
- **Step where error happened**: Setup new connection to source connector

## Current Behavior
Error using depth field to create source connection.

Depth field is recognizing values ​​as string instead of numbers

## Expected Behavior

Being able to use the depth field when setting up a new source connection

## Logs

![Airbyte_ERROR](https://user-images.githubusercontent.com/99834582/193082273-d2d46600-4d9a-49c7-b53e-8a6369bc1519.png)

## Steps to Reproduce
1. Create a source connection to jenkins source and use the depth field

## Are you willing to submit a PR?

Yes

https://github.com/airbytehq/airbyte/pull/17086

**Comment by marcosmarxm** [comment]
Jenkins is a source created by Faros.ai CDK. Please report the issue in their repo to get a fix.
