### ISSUE TITLE
Additional timing information is needed for sync analysis

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17407]
Right now, we only have the notion of "attempt duration" which is a measure of all the replication phases. However, when considering the performance of a specific section/activity within the replication workflow, additional timing information is needed.  For example, the [dashboard of source speed](https://airbyte.metabaseapp.com/question/699-source-connector-speed?days_ago=90&min_samples=10) is using "records_synced/attempt_duration" but the source may have completed long before the destination.

[whimsical link](https://whimsical.com/replication-timing-diagram-WPAdPzQMw2yitKP2Rd2GGS)
<img width="714" alt="Screen Shot 2022-10-11 at 3 51 11 PM" src="https://user-images.githubusercontent.com/303226/195212666-3498eec5-9c9e-4be1-bf86-d418c4acd31b.png">

This information should be:
1. Added to the sync summary
2. Uploaded to Segment/Bigquery/Metabase for analysis
3. (future work) This timing diagram can be drawn in the UI to help explain the sync performance to the UI 

Ideally, this information should include the following timestamps:

1. Attempt Start
2. Attempt End
4. Source Start
5. Source End
6. Destination Start
8. Destination End
9. Normalization Start
10. Normalization End

**Comment by ChristopheDuong** [comment]
we had a similar [issue](https://github.com/airbytehq/airbyte-warehouse/issues/66) but thinking of making it from a connector. But if it's native to the platform, that's probably better!

The connector version could be cool to share with OSS users maybe? if they needed such information from airbyte-cloud for example only on their own workspaces?

**Comment by evantahler** [comment]
@ChristopheDuong AFAIK, we don't have this per-container timing information anywhere in the platform, so you'll get it in the syncSummary as soon as we have it!

**Comment by evantahler** [comment]
Data will get to the data warehouse via https://github.com/airbytehq/airbyte-warehouse/issues/558
