### ISSUE TITLE
Validate AirbyteProtocol Migrations and SerDe available in the bootloader

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#17411]
## What

We should prevent the platform from starting if we are missing migrations/serializers/deserializers to avoid runtime failures due to what should be considered an invalid config.

## How

In the bootloader, given that we have the range of supported versions of the airbyte protocol
* Verify that we have migrations to cover the whole spectrum
* Verify that we have serializers and deserializers for the all the supported versions

**Comment by davinchia** [comment]
Won't do.
