### ISSUE TITLE
Source Pipedrive: new stream Files

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17439]
## Tell us about the problem you're trying to solve
[Files](https://developers.pipedrive.com/docs/api/v1/Files)
Files are documents of any kind (images, spreadsheets, text files, etc.) that are uploaded to Pipedrive, and usually associated with a particular deal, person, organization, product, note or activity. Remote files can only be associated with a particular deal, person or organization. Note that the API currently does not support downloading files although it lets you retrieve a file’s meta-info along with a URL which can be used to download the file by using a standard HTTP GET request.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _deals:read_, _activities:read_, _contacts:read_, _products:read_, _recents:read_, _search:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
