### ISSUE TITLE
Source Pipedrive: new stream Filters

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17430]
## Tell us about the problem you're trying to solve
[Filters](https://developers.pipedrive.com/docs/api/v1/Filters)
Each filter is essentially a set of data validation conditions. A filter of the same kind can be applied when fetching a list of deals, leads, persons, organizations or products in the context of a pipeline. Filters are limited to a maximum of 16 conditions. When applied, only items matching the conditions of the filter are returned. Detailed definitions of filter conditions and additional functionality is not yet available.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _deals:read_, _activities:read_, _contacts:read_, _recents:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
