### ISSUE TITLE
Source Pipedrive: new stream Products

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17432]
## Tell us about the problem you're trying to solve
[Products](https://developers.pipedrive.com/docs/api/v1/Products)
Activity types represent different kinds of activities that can be stored. Each activity type is presented to the user with an icon and a name.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _products:read_, _deals:read_, _contacts:read_, _recents:read_, _search:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/issues/17432
