### ISSUE TITLE
Source Pipedrive: new stream Roles

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17434]
## Tell us about the problem you're trying to solve
[Roles](https://developers.pipedrive.com/docs/api/v1/Roles)
Roles are a part of the Visibility groups’ feature that allow the admin user to categorize other users and dictate what items they will be allowed access to see.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _users:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
