### ISSUE TITLE
Source Pipedrive: new stream Leadlables

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17437]
## Tell us about the problem you're trying to solve
[Leadlables](https://developers.pipedrive.com/docs/api/v1/LeadLabels)
Lead labels allow you to visually categorize your leads. There are three default lead labels: hot, cold, and warm, but you can add as many new custom labels as you want.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
