### ISSUE TITLE
Source Pipedrive: new stream Notes

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17435]
## Tell us about the problem you're trying to solve
[Notes](https://developers.pipedrive.com/docs/api/v1/Notes)
Notes are pieces of textual (HTML-formatted) information that can be attached to deals, persons and organizations. Notes are usually displayed in the UI in chronological order – newest first – and in context with other updates regarding the item they are attached to. The maximum note size is approximately 3,000,000 characters (or 3MB per note).

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _recents:read_, _contacts:read_, _deals:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
