### ISSUE TITLE
Source Pipedrive: new stream Mailbox

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17436]
## Tell us about the problem you're trying to solve
[Mailbox](https://developers.pipedrive.com/docs/api/v1/Mailbox)
Mailbox was designed to be the email control hub inside Pipedrive. Pipedrive supports all major providers (including Gmail, Outlook and also custom IMAP/SMTP). There are 2 options for syncing user emails: 2-way sync: Mail Connection is established with the mail provider (example Gmail). There can be only 1 active Mail Connection per user in company. 1-way sync: SmartBCC feature which stores the copies of email messages to Pipedrive by adding the SmartBCC specific address to mail recipients.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _mail:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by brookpetit** [comment]
Will be super helpful to be able to get all emails. Should work e.g. with this endpoint: https://developers.pipedrive.com/docs/api/v1/Mailbox#getMailMessage

But as a variable, the user should be able to give an id-range. E.g. extract all mail with IDs between 1 and 100 000.

**Comment by topefolorunso** [comment]
@brookpetit @igrankova Not sure if providing an id range would be ideal. Consider the following options:

1. getting all mails for an organization as in https://developers.pipedrive.com/docs/api/v1/Organizations#getOrganizationMailMessages 
2. getting all mails for a person as in https://developers.pipedrive.com/docs/api/v1/Persons#getPersonMailMessages

For option 1, we can get each organization id by partitioning the organization streams. Same goes for option 2 but I would recommend option 1. Let me know what you think

**Comment by topefolorunso** [comment]
Assign this to me next @justinbchau. PR raised for other issues. Please confirm
