### ISSUE TITLE
Destination Snowflake: prevent unnecessary queries

### ISSUE THREAD

**Issue by Tybot204** [airbytehq/airbyte#17444]
## Tell us about the problem you're trying to solve

I currently have a connector setup in Airbyte that uses a Postgres database with CDC enabled as my source, and a Snowflake warehouse as the destination. I am seeing queries run in Snowflake to create / drop staging tables every time the Airbyte sync runs, regardless of whether new data has actually been changed or showed up in the CDC logs. This charges credits in Snowflake for essentially no work done. 

## Describe the solution you’d like

I may not fully understand how Airbyte determines if changes should be replicated, but can we remove the need to query Snowflake at all unless there is data available to replicate from the CDC logs in Postgres? I am trying to save cost when no changes are being made in our master Postgres database, while keeping a short sync interval to check for changes.

## Describe the alternative you’ve considered or used

AWS DMS is the current alternative I use. This appears to only make queries to the destination connection only if new changes are picked up by the CDC logs in Postgres.

## Are you willing to submit a PR?
Willing, yes absolutely. It's more a matter of whether I have time to learn the inner workings of Airbyte and make the needed changes! I will update this issue if I begin work on a change, but until then assume no. 😦

**Comment by sh4sh** [comment]
Hey @Tybot204 thanks for reporting this. Could you share full logfiles from Airbyte or elsewhere from when you notice this behaviour occurring? Also could you share the Airbyte version and Postgres/Snowflake connector versions you're using, for reference?

**Comment by Tybot204** [comment]
Hey @sh4sh, attached is a recent logfile from a job I just ran where there were 0 changes discovered from the Postgres source replica slot, but Snowflake was still queried to build / teardown staging tables that were never used, causing credit usage.

**Airbyte:** 0.40.0
**Postgres Source Connector:** 1.0.14
**Snowflake Destination Connector:** 0.4.38

I think the preferred workflow here would be to check the source connection for changes in the WAL logs prior to creating staging tables in Snowflake. It would be best if Airbyte was able to only create staging tables for the data that changed instead of the entire schema as well. This would just cut down on work done in Snowflake and overall cost associated with syncing data.

[4bc3aab0_2655_411a_859c_a42dcfee6c65_logs_5_txt.txt](https://github.com/airbytehq/airbyte/files/9748518/4bc3aab0_2655_411a_859c_a42dcfee6c65_logs_5_txt.txt)

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
