### ISSUE TITLE
Source Pipedrive: new stream Organizations

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17441]
## Tell us about the problem you're trying to solve
[Organizations](https://developers.pipedrive.com/docs/api/v1/Organizations)
Organizations are companies and other kinds of organizations you are making deals with. Persons can be associated with organizations so that each organization can contain one or more persons.

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 
**Scope** _deals:read_, _mail:read_, _activities:read_, _contacts:read_, _recents:read_, _search:read_

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
This stream is already implemented
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-pipedrive/source_pipedrive/streams.py#L126
