### ISSUE TITLE
Source Pipedrive: new stream PermissionSets

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17440]
## Tell us about the problem you're trying to solve
[PermissionSets](https://developers.pipedrive.com/docs/api/v1/PermissionSets)
Permission sets define what users in the account can do: which actions they are allowed to perform and which features they can access. Permission sets are app-specific, where apps are large parts of functionality, e.g., sales app, which allows accessing sales data, global permissions, which oversee cross-product features (for example contacts, insights, products) or account settings, which provides access to billing, user management, company settings and security center. Some permission sets with types such as admin and regular are pre-created for the account, while other custom ones can be created by users (depending on the tier the account is on).

[Permission](https://pipedrive.readme.io/docs/marketplace-scopes-and-permissions-explanations#list-of-scopes) 

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/23789
