### ISSUE TITLE
Source Freshdesk: new stream Business Hours

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17448]
## Tell us about the problem you're trying to solve
[Business Hours](https://developers.freshdesk.com/api/#business-hours)
Business Hours refer to the working hours of your company. When configured, anything outside your working hours will not be timed by Freshdesk. You can specify working hours for weekdays and weekends, as well as include a list of holidays on which your company will be closed.

[Permission](https://support.freshdesk.com/en/support/solutions/articles/96909-controlling-agent-access-with-roles) 

**Only users with admin privileges can access the following APIs.**

By default, Freshdesk lets you choose between 4 roles for your team members:
**Agents:** Can view, respond to and assign tickets, as well as modify ticket properties.
**Supervisors:** Can view and respond to tickets, generate reports and can also enable automatic ticket assignment of the member groups under the Admin tab.
**Admins:** Can access everything and edit configurations under the Admin tab, but cannot view or modify billing information. 
**Account Admins:** Have complete access to everything, including billing and account management.
Furthermore, Freshdesk may have custom roles. Note, that custom role may not have access to all resources.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
Source Freshdesk has already stream Business Hours
Ref:
https://github.com/airbytehq/airbyte/blob/33ca41b737909df39240194edb2ca36ded272ce7/airbyte-integrations/connectors/source-freshdesk/source_freshdesk/streams.py#L160
