### ISSUE TITLE
Source Freshdesk: new stream Products

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17451]
## Tell us about the problem you're trying to solve
[Products](https://developers.freshdesk.com/api/#products)
If you offer multiple products, you can have a separate support portal for each product. You can give these portals different URLs and hide irrelevant forums and solution articles by restricting access to specific categories but have agents support all these products from a single helpdesk.

[Permission](https://support.freshdesk.com/en/support/solutions/articles/96909-controlling-agent-access-with-roles) 

**Only users with admin privileges can access the following APIs.**

By default, Freshdesk lets you choose between 4 roles for your team members:
**Agents:** Can view, respond to and assign tickets, as well as modify ticket properties.
**Supervisors:** Can view and respond to tickets, generate reports and can also enable automatic ticket assignment of the member groups under the Admin tab.
**Admins:** Can access everything and edit configurations under the Admin tab, but cannot view or modify billing information. 
**Account Admins:** Have complete access to everything, including billing and account management.
Furthermore, Freshdesk may have custom roles. Note, that custom role may not have access to all resources.

## Describe the solution you’d like
Research pros and cons for implementing this stream.
_Research should contain: what stream should be implemented, permissions and scopes (if needed), paid plan (if needed)._

**Comment by btkcodedev** [comment]
Source Freshdesk has already stream products
https://github.com/airbytehq/airbyte/blob/33ca41b737909df39240194edb2ca36ded272ce7/airbyte-integrations/connectors/source-freshdesk/source_freshdesk/streams.py#L247
