### ISSUE TITLE
Display airbyte version in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1749]
## Tell us about the problem you're trying to solve
We would like users to be able to quickly tell us which version of Airbyte they're running. to make this easy for them, we would like to display the current airbyte version on every page of the UI. Some inspiration from other apps: 

![image](https://user-images.githubusercontent.com/6246757/105252447-4770cf80-5b32-11eb-9b30-69e49da20b74.png)
![image](https://user-images.githubusercontent.com/6246757/105252463-4f307400-5b32-11eb-90ac-08c06d8320a6.png)

these images are just to convey what this ticket is asking for and are not design suggestions. @johnlafleur you may want to suggest a design.

**Comment by johnlafleur** [comment]
We can either display the version number in the left column, or in the future settings UI (https://github.com/airbytehq/airbyte/issues?q=is%3Aissue+is%3Aopen+settings+ui). 
I have a personal preference for the 2nd option, but can design for the 1st option, until we got the settings. Wdyt?

**Comment by michel-tricot** [comment]
I like to have a discreet version number on every single page in the corner of the webapp.

**Comment by johnlafleur** [comment]
2 suggestions then:
- Option 1: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=17309%3A277
- Option 2: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=11542%3A1349

I have a personal preference for option 1, it looks pretty good just under the icon :)

**Comment by cgardens** [comment]
I am in favor of on every page so people don't need to hunt for it.

Keep in mind that the left nav doesn't exist in the onboarding wizard. I
think the left nav is a good place for it in other cases, but need to
figure out what we do in onboarding flow.

**Comment by michel-tricot** [comment]
Can we put it at the bottom center so it works on both the onboarding and regular webapp:
![image](https://user-images.githubusercontent.com/1154337/105406086-ce7c8100-5be0-11eb-96ba-72bde7108f3f.png)

**Comment by johnlafleur** [comment]
It could work, but when there is a long list that requires to scroll down, the version number should be displayed at the bottom of the list, so with some margin. 
Here is how it could look like: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A0

I personally prefer it to be in the left column, but if we want the same consistent behavior between onboarding and general, then that may be the way to go.

**Comment by cgardens** [comment]
I also like option 1. Let's do that.  

> Option 1: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=17309%3A277

For the onboarding wizard _only_ let's also added it at the bottom (since there is no left nav bar there).

> Here is how it could look like: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A0
