### ISSUE TITLE
Replace React Select with Headless UI menu in the destination page `add source` button

### ISSUE THREAD

**Issue by matter-q** [airbytehq/airbyte#17501]
Replace `React Select` with a `Headless UI` menu in the destination  `add source` button

![image.png](https://images.zenhubusercontent.com/62beeb7e8ea880aea38f18ed/65ffb774-4187-4c10-9d55-cd7c798de8ca)

**Current behavior**:
Menu implemented by `React Select`

**Expected behavior:**
The menu should be refactored and replaced with a `Headless UI menu`

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Should also update the source page "add destination" menu
