### ISSUE TITLE
`Source Cannot Be Stopped` Error

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17509]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2508](https://airbyte7538.zendesk.com/agent/tickets/2508)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Is this your first time deploying Airbyte?: Yes</li>
<li style="padding-bottom: 10px">OS Version / Instance: Linux (Amazon)</li>
<li style="padding-bottom: 10px">Memory / Disk: you can use something like 16Gb / 8 Gb</li>
<li style="padding-bottom: 10px">Deployment:  Docker</li>
<li style="padding-bottom: 10px">Airbyte Version: 0.40.10</li>
<li style="padding-bottom: 10px">Source name/version:  Zuora alpha 0.1.3</li>
<li style="padding-bottom: 10px">Destination name/version: Snowflake</li>
<li style="padding-bottom: 10px">Step: The issue is happening during sync</li>
<li style="padding-bottom: 10px">Description:</li>
</ul>
<p dir="auto">Hello All. I’m a new Airbyte user. I’m trying to load the <code style="background-color: #f9f9f9; padding: 2px 5px">notificationhistorycallout</code> object from Zuora but getting the <code style="background-color: #f9f9f9; padding: 2px 5px">Source cannot be stopped</code> error. I tried both <code style="background-color: #f9f9f9; padding: 2px 5px">full refresh truncate</code> and <code style="background-color: #f9f9f9; padding: 2px 5px">full refresh append</code> but the result didn’t change. I can sync the other objects successfully.<br>
Any idea about this error?</p>
<p dir="auto">Error:</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">2022-09-30 21:52:47 e[43mdestinatione[0m &gt; Preparing staging area in destination completed for schema AIRBYTE stream notificationhistorycallout
2022-09-30 21:52:47 e[43mdestinatione[0m &gt; Preparing tmp tables in destination completed.
2022-09-30 21:52:49 e[44msourcee[0m &gt; Cursor 'UpdatedDate' is not available. Switching cursor to 'CreatedDate'
2022-09-30 21:52:49 e[44msourcee[0m &gt; Cursor 'CreatedDate' is not available. Fetching whole object
2022-09-30 21:52:49 e[43mdestinatione[0m &gt; Starting a new buffer for stream notificationhistorycallout (current state: 0 bytes in 0 buffers)
2022-09-30 21:52:51 e[32mINFOe[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):352 - Records read: 1000 (16 MB)
2022-09-30 21:52:51 e[32mINFOe[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):352 - Records read: 2000 (17 MB)
2022-09-30 21:52:51 e[32mINFOe[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):352 - Records read: 3000 (18 MB)
2022-09-30 21:52:52 e[44msourcee[0m &gt; Cursor 'CreatedDate' is not available. Fetching whole object
2022-09-30 21:52:52 e[44msourcee[0m &gt; Encountered an exception while reading stream SourceZuora
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 104, in read
internal_config=internal_config,
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 134, in _read_stream
for record in record_iterator:
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 206, in _read_full_refresh
for record in records:
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records
yield from self.parse_response(response, stream_state=stream_state, stream_slice=stream_slice)
File "/airbyte/integration_code/source_zuora/source.py", line 156, in parse_response
yield from response
File "/airbyte/integration_code/source_zuora/source.py", line 127, in _send_request
yield from self.get_zuora_data(date_slice=request_kwargs, config=self._config)
File "/airbyte/integration_code/source_zuora/source.py", line 119, in get_zuora_data
yield from ZuoraGetJobResult(list(job_data_url)[0]).read_records(sync_mode=None)
File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
response = self._send_request(request, request_kwargs)
File "/airbyte/integration_code/source_zuora/source.py", line 452, in _send_request
raise ZOQLQueryFieldCannotResolveAltCursor
source_zuora.zuora_errors.ZOQLQueryFieldCannotResolveAltCursor: None
</code></pre> 

[<a href="https://discuss.airbyte.io/t/source-cannot-be-stopped-error/2771/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 14:02:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 14:22:*

<blockquote><div class="zd-comment" dir="auto">I'd just tried using our integration test credential:<br><span style="opacity: 1"><img src="https://airbyte7538.zendesk.com/attachments/token/4GtQUpQK12eb0pGfIVDaxm5xr/?name=image.png"></span><br>&nbsp;<br><span style="opacity: 1"><img src="https://airbyte7538.zendesk.com/attachments/token/d496EcsDIbSAjsFcp8uxJv0AN/?name=image.png"></span><br>&nbsp;<br>&nbsp;<br>It must be a firewall configuration from your network. Could you try from other server or network?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 14:49:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a> ,<br>
Thank you for the answer. But I’m getting the error only for one of the objects.  I can sync the other objects successfully. I believe the network is not he issue here.<br>
Best,<br>
Murat</p> 

 [<a href="https://discuss.airbyte.io/t/source-cannot-be-stopped-error/2771/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 16:33:*

<blockquote><div class="zd-comment" dir="auto">Sorry Murat the replied I gave was to another topic.<br>I tried to test using integration credentials but wasn't able to connect to Zuora.<br>&nbsp;<br>I created the issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17509">https://github.com/airbytehq/airbyte/issues/17509</a> to solve the issue!<br>&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 16:52:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">No worries. Thank you.</p> 

 [<a href="https://discuss.airbyte.io/t/source-cannot-be-stopped-error/2771/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by aryangarg1109** [comment]
i am  also facing the same issue....  earlier i was using 0.6.8 version of mysql but when i downgraded to 0.4.9 version i faced this issue
