### ISSUE TITLE
Postgres hits the max table name length

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1750]
## Expected Behavior
We should properly take into account destination limitations when creating tables.

## Current Behavior
Daniel Fraser had the following issue while replicating data into PG:

```
“Runtime Error in model” … “Relation name ‘xyz.abc__dbt_backup’ is longer than 63 characters
```

This is a problem that we can encounter for several reasons:

* we prefix table names
* DBT seems to be creating maintenance tables

## Steps to Reproduce
(Not tested)

1. Try replicating a table of 63 char into PG

## Severity of the bug for you
Medium

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368142865634) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Related to https://github.com/fishtown-analytics/dbt/issues/2869

**Comment by ChristopheDuong** [comment]
Since #1737, we rename destination tables with `_airbyte_raw` suffixes, we should probably make sure that table names have to be less than 51 characters (63 -12 from the added suffix) on Postgres destinations
