### ISSUE TITLE
Source MySQL - upgrade from 0.6.12 to 1.0.1 creates "Numeric value 'true' is not recognized in the SCD normalization process" errors

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17510]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2519](https://airbyte7538.zendesk.com/agent/tickets/2519)
**Priority:** high
**Group:** Community Assistance Engineer
**Organization:** Airbyte
**Assignee:** Sajarin

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I’ve just upgraded the mysql source from 0.6.12 to 1.0.1 (GA i believe) and running into production syncing issues now</p>
<p dir="auto">Numeric value 'true' is not recognized in the SCD normalization process. Created issue here: <a href="https://discuss.airbyte.io/t/mysql-1-0-1-ga-source-normalization-failure/2773" rel="noreferrer">https://discuss.airbyte.io/t/mysql-1-0-1-ga-source-normalization-failure/2773</a></p>
<p dir="auto">However, the most pressing issue is that we can’t revert back to 0.6.12 without still experiencing the same issue across all connectors<br>
[via Slack] Open original slack thread in #public-airbyte-help channel: <a href="https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1664768105368939" rel="noreferrer">https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1664768105368939</a></p></div></blockquote>

**Comment by sajarin** [comment]
@grishick can we move this up the backlog queue?

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 16:51:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] Hey @user_id, I created an issue on our Github with this ticket: <a href="https://github.com/airbytehq/airbyte/issues/17510" rel="noreferrer">https://github.com/airbytehq/airbyte/issues/17510</a></p>
<p dir="auto">The MySQL connector is not in GA, it’s just about to be in beta.</p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 20:07:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] i think this one is actually an issue with the destination - snowflake</p></div></blockquote>

**Comment by grishick** [comment]
I suspect that the underlying problem is that MySQL stores boolean as TINYINT(1) and somewhere between 0.6.1 and 1.0.1 we changed how MySQL source returns booleans. The simplest way to fix this is to run a reset. 
cc @edgao could we handle this gracefully in destinations without a reset? I.e., can we run `alter table` on scd and destination tables?

**Comment by edgao** [comment]
is the theory that:
* in an older source-mysql version, we discovered `type: int` and produced data like `{foo_column: 1}`
* in the newer source-mysql version, we now discover `type: boolean` and produce `{foo_column: false}`
* this user upgraded source-mysql, but didn't refresh their schema, so now they have a catalog which expects integers, but the source is reading booleans
* and so normalization is blowing up?

(that sounds reasonable to me, maybe worth tagging someone from db-sources to confirm)

quick research:
* snowflake can [implicitly convert](https://docs.snowflake.com/en/sql-reference/data-types-logical.html#conversion-to-boolean) int to boolean (0 -> false, everything else -> true) - so the existing data should be OK
* BUT: alter table [might not work](https://docs.snowflake.com/en/sql-reference/sql/alter-table-column.html) (int -> boolean). Not 100% sure here, maybe an experiment (create table with int column, try to alter to boolean) would be useful

If alter table works, then this is easy: user should refresh schema and choose not to reset; their next sync will automatically run the `ALTER TABLE` and everything will be fine.

If alter table does _not_ works, then it's a little more complicated. Assuming they still have their `_raw` tables:
1. User needs to refresh their schema + choose not to reset
2. User should manually delete the SCD and final tables
3. Next sync will still be incremental (since we didn't reset the connection)
4. Next sync's normalization run will effectively do a soft reset (https://github.com/airbytehq/airbyte/issues/17095) and recreate all the normalized tables

**Comment by grishick** [comment]
I also just double checked that current version of MySQL Source treats `TINYINT(1)` columns as boolean

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-05 at 19:48:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] Hi! do you have any update regarding this issue, i am also getting Cannot drop column '_AIRBYTE_UNIQUE_KEY</p></div></blockquote>

**Comment by edgao** [comment]
for continuity of discussion: asked user here (https://github.com/airbytehq/airbyte/pull/14424#issuecomment-1266351233) if they upgraded platform version at some point, to try and rule out a normalization bug

**Comment by marcosmarxm** [comment]
Zendesk ticket #[2744](https://airbyte7538.zendesk.com/agent/tickets/2744) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-12 at 13:51:*

<blockquote><div class="zd-comment" dir="auto">First a few questions:<br><br>1. What is the field type for the value causing the error, is it Boolean or TINYINT?<br><br>2. What version of the MySQL connector were you using before this that did not cause errors?<br><br>And some information:<br><br>1. There is a GitHub issue for this here, it is not resolved yet:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17510">https://github.com/airbytehq/airbyte/issues/17510</a><br><br>2. We changed how the MySQL source connector returns booleans some time between 0.6.1 and 1.0.1.<br><br>3. A potential workaround would be to roll back the version to 0.6.15.<br><br>4. Another two workarounds are described here:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17510#issuecomment-1266107416">https://github.com/airbytehq/airbyte/issues/17510#issuecomment-1266107416</a><br><br>This is actively being worked on :) let me know if any of those 3 workarounds pan out for you!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-13 at 01:41:*

<blockquote><div class="zd-comment" dir="auto"><ol dir="auto">
<li style="padding-bottom: 10px">The field in MySQL source is <code style="background-color: #f9f9f9; padding: 2px 5px">tinyint(1) unsigned</code> and in the staging view it’s</li>
</ol>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">cast(MY_FIELD as 
    bigint
) as MY_FIELD
</code></pre>
<ol start="2" dir="auto">
<li style="padding-bottom: 10px">i <em>think</em> the MySQL connector version was <code style="background-color: #f9f9f9; padding: 2px 5px">0.6.12</code>
</li>
</ol> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-normalization-issue-all-latest-versions/2883/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by danieldiamond** [comment]
I edited the above comment: 
and in the RAW AIRBYTE table the JSON is `"MY_FIELD": false`

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-13 at 14:25:*

<blockquote><div class="zd-comment" dir="auto">Got it, thanks!<br><br>Could you try rolling back to a pre 1.x.x version, using one of the work arounds listed in the link below, or doing a total reset? The reset obviously would be a last resort option.<br><br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17510#issuecomment-1266107416">https://github.com/airbytehq/airbyte/issues/17510#issuecomment-1266107416</a><br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-13 at 22:39:*

<blockquote><div class="zd-comment" dir="auto"><blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin: 0 0 10px; padding: 12px 25px 2px 12px">

<img alt="" width="20" height="20" src="https://sea2.discourse-cdn.com/business7/user_avatar/discuss.airbyte.io/danieldiamond/40/160_2.png" style="height: 20px; margin-right: 5px; vertical-align: middle; width: 20px"> danieldiamond:
<p style="padding: 0" dir="auto">This is a fresh new deployed airbyte instance, this is the latest source and destination versions and the first sync for this table.</p>
</blockquote>
<p dir="auto">Is the suggestion to migrate to pre 1.X OR reset the connector? Because this is a brand new connector, never been synced. Resetting doesn’t resolve this issue</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-normalization-issue-all-latest-versions/2883/7" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-14 at 13:39:*

<blockquote><div class="zd-comment" dir="auto">Oh, I see I wasn't aware that there was already a discussion happening on GitHub! I see that one of our engineers is looking for more info for you here:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/14424">https://github.com/airbytehq/airbyte/pull/14424</a><br><br>Sorry for the confusion - in this case please try rolling back to <code>0.6.15</code> or below, that should be the temporary workaround. Let me know if that helps! Otherwise I'd say to keep an eye on that GitHub thread!<br></div></blockquote>

**Comment by subodh1810** [comment]
see https://github.com/airbytehq/airbyte/pull/14424#issuecomment-1293917212

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-30 at 21:48:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Issue has been reproduced and is being resolved here: <a href="https://github.com/airbytehq/airbyte/pull/18619" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">mysql-source:fix tinyint unsigned handling by subodh1810 · Pull Request #18619 · airbytehq/airbyte · GitHub</a></p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-normalization-issue-all-latest-versions/2883/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-03 at 12:34:*

<blockquote><div class="zd-comment" dir="auto">Hey Daniel, it looks like the issue has been solved! Let me know if you need any further info!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-03 at 13:33:*

<blockquote><div class="zd-comment" dir="auto">Wonderful to hear!<br></div></blockquote>
