### ISSUE TITLE
MySQL to Snowflake incremental loading fails

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17512]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2471](https://airbyte7538.zendesk.com/agent/tickets/2471)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px">OS Version / Instance: EC2 Linux AMI 2</li>
<li style="padding-bottom: 10px">Memory / Disk: M6a.xlarge instance - 4 vCPUs, 16 GiB memory, 60 Gb storage</li>
<li style="padding-bottom: 10px">Deployment:  Docker</li>
<li style="padding-bottom: 10px">Airbyte Version: 0.40.9 (latest as of writing)</li>
<li style="padding-bottom: 10px">Source name/version:  MySQL 0.6.14 (latest as of writing) connected through SSH tunnel</li>
<li style="padding-bottom: 10px">Destination name/version: Snowflake 0.4.38 (latest as of writing) internal staging</li>
<li style="padding-bottom: 10px">Step: During incremental sync</li>
<li style="padding-bottom: 10px">Description:</li>
</ul>
<p dir="auto">Hi.</p>
<p dir="auto">I am trying to sync moodle data sitting in Amazon Aurora to Snowflake. I was able to do so successfully in a previous Airbyte version 0.39.19-alpha.</p>
<p dir="auto">Syncing 7.21Gb of data (about 40 tables) is successful on the initial run.<br>
All subsequent syncs are failing. See image below.</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/a/ab87d0b2c21fd7de2036abb527efbaf07b725eb4.png" title="historical-success-incremental-fail" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/a/ab87d0b2c21fd7de2036abb527efbaf07b725eb4_2_690x435.png" alt="historical-success-incremental-fail" width="auto" height="auto" style="max-width: 100%"><div style="display: none">
<span>historical-success-incremental-fail</span><span>1493×943 67.8 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto">Here is the log for the successful initial sync:<br>
<a href="https://discuss.airbyte.io/uploads/short-url/2Tud15TexlxX7Xb9V4VGJggJVsn.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">success-logs.txt</a> (7.0 MB)<br>
Errors/warnings in the log that may be of interest:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">JSON schema validation failed</li>
<li style="padding-bottom: 10px">Signalling close because record’s binlog file : mysql-bin-changelog.002503 , position : 75169383 is after target file : mysql-bin-changelog.002503 , target position : 75125447</li>
<li style="padding-bottom: 10px">The main thread is exiting while children non-daemon threads from a connector are still active. Ideally, this should not happen</li>
</ul>
<p dir="auto">Here is the log for the first failed sync:<br>
<a href="https://discuss.airbyte.io/uploads/short-url/7JmUomae5tbeMucpn97dAMO3Zq0.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">failure-logs.txt</a> (5.3 MB)<br>
Errors/warnings in the log that may be of interest:</p>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">2022-09-28 19:47:53 - Additional Failure Information: ScheduleActivityTaskCommandAttributes.Input exceeds size limit.</li>
<li style="padding-bottom: 10px">Repeat of the errors/warnings found in successful.logs</li>
</ul>
<p dir="auto">Even with the warnings, the initial sync is successful. However, subsequent syncs are failing. I believe there is enough CPU and RAM for this sync. The error:</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">ScheduleActivityTaskCommandAttributes.Input exceeds size limit.
</code></pre>
<p dir="auto">seems to be related to temporal, but it makes no sense that the initial sync ran without an issue.</p>
<p dir="auto">Please could someone assist me on this issue. Thank you.</p> 

[<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-28 at 23:17:*

<blockquote><div class="zd-comment" dir="auto">Hi @jamo, looks like there are type errors in your sync. Let me look into this more and I'll have some more ideas for you tomorrow!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-29 at 12:05:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a> Thank you. I just wonder why it succeeds in the initial run.</p>
<p dir="auto">Not sure if this helps but, I’ve also run another test with 9 tables that are a few Mb in size. The incremental loading syncs take much longer that the initial, historical load, which I find odd.<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/d/db25fce0bb4865571956795731b41f1b322093ff.png" alt="airbyte-incremental-times-are-long-2" width="auto" height="auto" style="max-width: 100%"></p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-29 at 12:42:*

<blockquote><div class="zd-comment" dir="auto">OK a few questions -&nbsp;<br>1. Does your cursor field have trailing zeroes?<br>2. Do you have normalization enabled?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-30 at 05:24:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a></p>
<p dir="auto">I am not 100% sure though if the cursor field is timemodified as I am using CDC and don’t have the option of selecting the cursor field.</p>
<p dir="auto">Interestingly, this link describes that the source does not necessarily need a suitable cursor field.</p><div style="border: 5px solid #e9e9e9; margin-bottom: 10px; padding: 12px 25px 12px 12px">
  <div>
      <img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/1X/d9878ecb4e87bf365699b78a9854d8374ebebaa5.png" width="32" height="32" style="height: 16px; margin-right: 3px; width: 16px">

      <a href="https://airbyte.com/tutorials/incremental-change-data-capture-cdc-replication" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">airbyte.com</a>
  </div>

  <div style="clear: both">
    <div><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/b/b5c8cf8d2df4a0f5abd35c2111c20d8efcc18561_2_690x436.png" width="auto" height="auto" style="float: left; height: auto; margin-right: 10px; max-height: 80%; max-width: 20%; width: 60px" align="left"></div>

<h3 style="font-size: 1.17em; margin: 30px 0 10px" dir="auto"><a href="https://airbyte.com/tutorials/incremental-change-data-capture-cdc-replication" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">Airbyte's incremental Change Data Capture (CDC) replication</a></h3>

  <p dir="auto">Learn how Airbyte’s Change Data Capture (CDC) replication works.</p>


  </div>

  <div style="color: #919191">
    
    
  </div>

  <div style="clear: both"></div>
</div>

<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px">
<p style="margin-bottom: 0; margin-top: 0; padding: 0" dir="auto">“On the other hand, CDC incremental replication reads a log of the changes that have been made to the source database and transmits these changes to the destination. Because changes are read from a transaction log when using CDC, it is not necessary for the source data to have a suitable cursor field.”</p>
</blockquote>
<p dir="auto">I’ve also tested the same connection on a bit older Airbyte 0.39.19-alpha instance with source MySql 0.5.11, destination Snowflake 0.4.28, and the incremental loading works.</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-30 at 14:07:*

<blockquote><div class="zd-comment" dir="auto">It is really odd that you're having this issue with only 7Gb of data. Let me get some input from my team and I'll get back to you shortly!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-09-30 at 14:52:*

<blockquote><div class="zd-comment" dir="auto">Could you update to Airbyte <code>0.40.10</code>? I'm getting input from my team, and we're thinking updating could possibly fix the problem.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-02 at 21:56:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a> I’ve tried, same issue. Initial historical run works, but the following incremental syncs fail.</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 11:56:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a><br>
Hope you had a great weekend.</p>
<p dir="auto">The incremental syncs are still failing after upgrading to Airbyte 0.40.10. Connectors are the latest versions.<br>
The initial historical sync also succeeded after failing once.</p>
<p dir="auto"><strong>Here is a screenshot of the UI:</strong><br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/5/567e2e7ee8bca3efcb32a3b316a7b7195b00cdea.png" alt="historical-pass-incremental-fail" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto"><strong>Here is the historical sync log that failed:</strong> (/tmp/workspace/46/0)<br>
<a href="https://discuss.airbyte.io/uploads/short-url/6RIfLme1jpKcvEYwXWWgilY1SVu.log" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">historical-0-fail.log</a> (4.1 MB)</p>
<p dir="auto"><strong>Here is the historical sync log that succeeded:</strong> (/tmp/workspace/46/1)<br>
<a href="https://discuss.airbyte.io/uploads/short-url/loYjkkONaaxOqCOhuKTkyuZLngZ.log" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">historical-1-success.log</a> (7.6 MB)</p>
<p dir="auto">Here is the incremental sync log that fails:<br>
<a href="https://discuss.airbyte.io/uploads/short-url/sm6tV4B9z8Gcj25k3bIH5MBV6iV.log" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">failure-logs.log</a> (5.0 MB)</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/10" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-03 at 13:34:*

<blockquote><div class="zd-comment" dir="auto">Could you share your schema please?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 15:36:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a> It also appears on the historical success logs in this format:</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px">
<p style="margin-bottom: 0; margin-top: 0; padding: 0" dir="auto">For table ‘uctohsDB.mdl_glossary’ using select statement: ‘SELECT’ <code style="background-color: #f9f9f9; padding: 2px 5px">id</code>, <code style="background-color: #f9f9f9; padding: 2px 5px">course</code>, <code style="background-color: #f9f9f9; padding: 2px 5px">name</code>, <code style="background-color: #f9f9f9; padding: 2px 5px">intro</code>…</p>
</blockquote>
<p dir="auto">Hope this is what you’re looking for.</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/13" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-03 at 17:16:*

<blockquote><div class="zd-comment" dir="auto">After discussing this with the team, I've escalated this to GitHub. You can follow the issue here:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17512">https://github.com/airbytehq/airbyte/issues/17512</a><br><br>This looks like it is failing because of the <code>StandardSyncInput</code>&nbsp; which contains the full catalog and the state. It is hard to estimate what will be the size for this specific connection. The state is only added on the second sync, which is why the initial sync works.<br><br>Could you try a few things? These could be fixes in the short term, but we will work on making a longterm fix.<br><br>1. Split the tables into 2 or more connections so as not to hit the maximum message size.<br>2. Tweak the dynamic.config and build temporal with a bigger BlobSize<br><br>Let me know if this helps!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-03 at 22:08:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I have about 65 tables of interest that are about 21 Gb in size.<br>
To split the tables into 2 or more connections, I have selected only a few tables that add up to 1.74 Gb, which I believe is small, yet the incremental sync keeps failing.<br>
</p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/b/bd0493ec5ac21774d342253797e788660753a8db.png" title="mysql-sync-failure" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/b/bd0493ec5ac21774d342253797e788660753a8db_2_690x440.png" alt="mysql-sync-failure" width="auto" height="auto" style="max-width: 100%"><div style="display: none">
<span>mysql-sync-failure</span><span>1354×865 48.3 KB</span>
</div></a></div><p dir="auto"></p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/15" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-07 at 08:27:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a></p>
<p dir="auto">I have a critical critical issue. The connections are passing but there is a huge data integrity issue.<br>
The counts of the records are significantly off. I assume maybe, that the incremental loads are overwriting the historical loads. Please could you and the team look into this urgently.</p>
<p dir="auto">And thank you for all the help thus far.</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/17" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-07 at 13:56:*

<blockquote><div class="zd-comment" dir="auto">Hi! Please make a GitHub issue with all the details and we'll be able to look into it!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-09 at 15:11:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">hey <a href="/u/jamo" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@jamo</a> there is a workaround for the issue <a href="https://github.com/airbytehq/airbyte/issues/16236#issuecomment-1237755415" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">Sync hangs with error: ScheduleActivityTaskCommandAttributes.Input exceeds size limit. · Issue #16236 · airbytehq/airbyte · GitHub</a></p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/19" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-11 at 06:11:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks <a href="/u/alexnikitchuk" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@alexnikitchuk</a> I’ve updated to the latest version and I no longer get that error</p>
<p dir="auto"><a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a> I can’t seem to replicate the previous issue, but after updating to the latest version the incremental syncs still aren’t fully reliable</p>
<p dir="auto">The syncs work at times<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/1/161ba77d3f0640f9ad2ebdedd58e6c7e43be7538.png" alt="ui-sync-sc" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto">And fails/retries at times even though it looks like it is successful<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/7/7532904ef1e7645820101e7d21e155d0419053e6.png" alt="ui-sync-error-sc" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto">Logs:<br>
<a href="https://discuss.airbyte.io/uploads/short-url/pPS3UGeMYmv0UvXEU7OTW41AnDQ.log" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">fail-logs.log</a> (7.8 MB)</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/20" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-12 at 15:07:*

<blockquote><div class="zd-comment" dir="auto">I've found an issue for the latest error you're encountering. Looks like it happens sporadically just like in your case, and the only current fix is to reset the data and start a new sync, unfortunately.&nbsp;<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17372">https://github.com/airbytehq/airbyte/issues/17372</a><br><br>My suggestion would be to update the MySQL source to 1 or higher! As the user in the issue is also on a 6.x version.<br><br>We stick to one issue per forum post for documentation purposes. If you'd like to discuss this further, please start a new thread!&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-17 at 07:03:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thank you <a href="/u/natalyjazzviolin" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@natalyjazzviolin</a>. It seems I am still facing the same issue. Will continue on that github thread <img src="https://emoji.discourse-cdn.com/twitter/+1.png?v=12" title=":+1:" alt=":+1:" width="20" height="20"></p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/22" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-17 at 14:37:*

<blockquote><div class="zd-comment" dir="auto">Sorry to hear it's still happening! I'll ask one of the engineers on the databases team for their input and will post in the GitHub thread as well when I get new info!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-31 at 03:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I’m all of a sudden experiencing this as well</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">airbyte 0.40.17
airbyte/source-mysql:1.0.8
airbyte/destination-snowflake:0.4.38
</code></pre>
<p dir="auto">CDC and incremental+dedupe</p> 

 [<a href="https://discuss.airbyte.io/t/mysql-to-snowflake-incremental-loading-fails/2740/24" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-01 at 12:09:*

<blockquote><div class="zd-comment" dir="auto">Sorry to hear that! Please upvote and comment on that GitHub thread!<br></div></blockquote>

**Comment by danieldiamond** [comment]
Bumping here. There seems to be something not quite right with CDC incremental syncs...

**Comment by danieldiamond** [comment]
Sharing a similar discourse thread in the hopes of providing additional context. 

https://discuss.airbyte.io/t/mysql-to-snowflake-fails-normalization-doesnt-build-raw-table/2991/18

**Comment by prateekmukhedkar** [comment]
@grishick this looks like an issue on Destination or Normalization. Can you confirm?

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:10:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:12:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:15:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:20:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by prateekmukhedkar** [comment]
@marcosmarxm can we have the customer get on the latest MySQL connector version, and are you ok if I close this issue?
