### ISSUE TITLE
New Notifications Temporal Workflow

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#17529]
* Define the new workflow (interface)
* Create the workflow implementation
* Define the required activities (interface)
  * Fetch data for the notification
  * Send the notification
* Implement the activities

**Comment by jdpgrailsdev** [comment]
This is only via Slack to start.  There is already a notification client in OSS that can be re-used.

**Comment by jdpgrailsdev** [comment]
@andyjih This ticket is also blocked on the design for the notification.
