### ISSUE TITLE
Implement refreshSourceSchema method

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#17527]
This method will go in the RefreshSchemaActivity

The refreshSourceSchema method will call the updated discoverSchema endpoint in the SchedulerHandler and return a boolean value as to whether to continue with the sync or not. The discoverSchema endpoint disables connections that should not continue, so the boolean logic will simply be:

`shouldRunSync = connection.enabled?`

**Comment by jdpgrailsdev** [comment]
@alovew Split into to separate tickets

**Comment by jdpgrailsdev** [comment]
This will be in the SyncWorkflowImpl.
