### ISSUE TITLE
Source Marketo: new stream Segments

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#17547]
## Tell us about the problem you're trying to solve
Retrieves a list of segments inside the target segmentation. Required Permissions: Read-Only Assets, Read-Write Assets

## Describe the solution you’d like
research pros and cons for implementing this stream

**Comment by YowanR** [comment]
We expect this stream to be incremental. Thank you!

**Comment by Alcadeus0** [comment]
I'd like to work on this issue

**Comment by YowanR** [comment]
Assigned to you, @Alcadeus0! Looking forward to this contribution!
