### ISSUE TITLE
Webapp doesn't pass GCP IAP credentials into the api calls

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1756]
## Expected Behavior
If I have IAP enabled in front of the webapp, I want the webapp to properly work.

## Current Behavior
Webapp can load but api calls don't work because we don't pass IAP creds

## Steps to Reproduce
1. setup airbyte behind IAP

## Severity of the bug for you
Low

## Additional context
On GCP deployment

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084449907) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
After https://github.com/airbytehq/airbyte/issues/3647 this should work as expected.
