### ISSUE TITLE
Segment's Identify event should include the email address when available, if not anonymized

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#1757]
Right now, only the user id is added in the Identify, and we cannot know who did what (apart from Specified preferences). 

cgardens

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084595310) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
discussed / explored offline. we think it is possible the UI doesn't report email address. the backend definitely does though and the identity all get merged in amplitude so it shouldn't be adversely affecting any of the analytics reporting. it does mean that tests run on the UI for the `identify` action don't include email.

worth following up on next week to just get it all cleaned up but it does not appear to be breaking the analytics story so going to wait until then.

**Comment by cgardens** [comment]
I checked the frontend side. It indeed does _not_ send the email address because after that form is submitted it doesn't have access to it anymore. If it's helpful we can give it access, but we should only bother if it fixes something in our analytics which i don't think we know that it does yet.

**Comment by michel-tricot** [comment]
I wonder if we should store the email in the workspace when it is not anonymized. It will also make it easier to tie users in papercups.

**Comment by johnlafleur** [comment]
Can we move forward on that soon? It makes it harder to analyze active companies' behavior.

**Comment by johnlafleur** [comment]
Email should be put as a trait, as in the screenshot:
![Uploading Screen Shot 2021-02-12 at 6.44.14 PM.png…]()

**Comment by cgardens** [comment]
i'm still confused why we need this. it seems like something is broken in segment or amplitude if this is needed. the identities should get merged (the one with the email and the one without). if that is not happening then we have big problems. injecting the email from the UI is just going to be treating a symptom.

**Comment by johnlafleur** [comment]
Thanks for the clarification. Let's put it on hold in that case.

**Comment by timroes** [comment]
@nataliekwong Is this issue still relevant? We still don't log the mail of users in segment calls, but I haven't heard this being a problem anytime recently, so want to check if this can be closed?

**Comment by nataliekwong** [comment]
I don't have context on the original issue - redirecting to @johnlafleur for input

**Comment by johnlafleur** [comment]
We can close it. thanks!
