### ISSUE TITLE
Platform may exceed temporal limits

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#17581]
## What

Temporal cloud has a 2MB size limit (https://docs.temporal.io/kb/temporal-platform-limits-sheet/) that we may be hitting in some cases.
This came up as part of https://github.com/airbytehq/oncall/issues/731.
A first mitigation has been applied to reduce the payload.

We identified a few areas that may cause the payload to grow
* Size of state messages (mitigated by https://github.com/airbytehq/airbyte/pull/17538)
* The size of the catalog, sources will many streams and complex definitions will count up towards this
* Payload contains Error messages that we then pass to reporting

A few options for discussion:
* Monitor the size of the payload: we should be aware of our usage here
* Start Persisting states from the replication activity https://github.com/airbytehq/airbyte/issues/16762

**Comment by gosusnp** [comment]
Similarly, we ran into issues due to big catalogs on the discover schema command (https://github.com/airbytehq/airbyte/pull/17394)
In the current implementation, those catalogs would be added to the payload of the Sync and could result in a message that is too big.

**Comment by ifun248** [comment]
Similarly, on the Airbyte Open Source, I face the similar problem when integrate data from MySQL RDS to S3:ERROR i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):160 - Sync ouput exceeds the max temporal message size of 2097152, actual is 2423981.

**Comment by tryangul** [comment]
With moving the last bits of catalog and state out of temporal and trimming error messages, we no longer expect to see this issue. 

We are still subject to the temporal limit (4mb, and maybe 10mb in some instance) so can still shoot ourselves in the foot down the line, so we have to continue to be vigilant about payload size.

Nonetheless, we feel confident we can close this out.
