### ISSUE TITLE
New Source: Railz

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#17604]
## Tell us about the new connector you’d like to have
https://docs.railz.ai/docs/quickstart-overview

## Describe the context around this new connector

**Comment by igrankova** [comment]
Related to
Sandbox Account for Railz source #17603

**Comment by igrankova** [comment]
Vetting results:
**Webhook-based?** (no/partially/yes) 
partially
https://docs.railz.ai/reference/webhooks

**Available authentication modes** (API key/Oauth/other) 
API keys:
https://docs.railz.ai/reference/authentication

**Has Sandbox environment?** 
Yes,
https://dashboard.railz.ai/?sandbox=true

**How to populate the account with data** 
API:
https://docs.railz.ai/docs/railz-sandbox#supported-integrations--data-in-sandbox

**Available streams for sync** 
COMMON ENDPOINTS
Businesses
Businesses Info
Connections
Data Push Status
Data Sync Status
Data Types
ACCOUNTING ENDPOINTS
Accounting Transactions
AR Aging Reports
AP Aging Reports
Attachments
Bank Transfers
Bills
Bill Credit Notes
Bill Payments
Chart of Accounts
Customers
Deposits
Estimates
Balance Sheets
Cashflow Statements
Income Statements
Inventory
Invoices
Invoice Credit Notes
Invoice Payments
Journal Entries
Purchase Orders
Refunds
Tax Rates
Tracking Categories
Trial Balances
Vendors
BANKING ENDPOINTS
Bank Accounts
Bank Transactions
ANALYTICS ENDPOINTS
Bank Reconciliation
Financial Benchmarking
Tax Benchmarking
Credit Ratings
Credit Scores
Business Valuations
Financial Forecasts
Fraud Risk Metrics
Financial Ratios
Portfolio Metrics
Probability of Default
COMMERCE ENDPOINTS
Commerce Disputes
Commerce Orders
Commerce Products
Commerce Transactions
REPORTS ENDPOINTS
Reports Invoices
Reports Bills
Reports Revenue
Reports Expenses
Reports Cashflow Statements
Reports Income Statements
Reports Balance Sheets
Reports Financial Ratios
Reports Railz Score
Reports Credits

**Integration supports incremental sync?** 
Maybe (some streams have data type fields like startDate, endDate)

**Other information/blockers** 
Rate Limits - not found
Sandbox docs: https://docs.railz.ai/docs/railz-sandbox

**Comment by grubberr** [comment]
@sherifnada @lazebnyi  - [scoping docs](https://docs.google.com/document/d/1myhbkqzsMQwrmWwz5IhYRo7q6BwKl25c-SmXaWRmef0/edit#heading=h.84uu0ym2sjtf)

**Comment by grubberr** [comment]
@igrankova @lazebnyi @sherifnada I see that new connector named: "Railz.ai"
is this the right name? maybe just "Railz"? 

What do you think?

**Comment by igrankova** [comment]
@grubberr 
It is just Railz on their site:
![image](https://user-images.githubusercontent.com/87977540/213122244-2fa5e12a-b785-432d-8be9-4d70e285c4e8.png)

**Comment by YowanR** [comment]
Looks like @igrankova is right! Let's go for Railz.
