### ISSUE TITLE
Discover schema endpoint: disable connections as needed after refreshing schema

### ISSUE THREAD

**Issue by alovew** [airbytehq/airbyte#17633]
Disable connections as needed:
1. syncs with breaking schema changes
2. syncs with non-breaking schema changes whose users have opted to have connections disabled when there are schema changes

Details here: https://docs.google.com/document/d/1u333RpXQ1yHv3TK_4cjDjvGnaJeHtvkjxrq3oY5IT1E/edit#heading=h.uqbexni35qq1

This ticket should not be released until FE changes showing users that their connections are broken have been implemented. This can be released before we ship the functionality for users to pause non-breaking schema changes -- it will just mean that when we ship, no connections will be paused for non-breaking schema changes.

**Comment by andyjih** [comment]
Already done per @alovew
