### ISSUE TITLE
Update destination-s3 to handle the new data types protocol

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#17645]
See https://github.com/airbytehq/airbyte/issues/17637.

Definition of done:
 - destination-s3 accepts the new protocol messages
 - destination data does not change when protocol message version changes (should write a test for this)

**Comment by grishick** [comment]
Notes from grooming: unknown how this will affect BigQuery and Snowflake destinations that depend on `base-s3` code

**Comment by ryankfu** [comment]
Notes from planning:
*

**Comment by grishick** [comment]
Remaining work in https://github.com/airbytehq/airbyte/pull/20088
