### ISSUE TITLE
Source Amazon Seller Partner: new report types

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#17659]
## Tell us about the problem you're trying to solve
Add new report types:

GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA
GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_PROMOTION_DATA
GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA
GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA
GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA
GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA
GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA
GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
GET_FBA_SNS_FORECAST_DATA
GET_FBA_SNS_PERFORMANCE_DATA
GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE
GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE
GET_MERCHANT_CANCELLED_LISTINGS_DATA
GET_MERCHANT_LISTINGS_DATA
GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT
GET_MERCHANTS_LISTINGS_FYP_REPORT
GET_MERCHANT_LISTINGS_INACTIVE_DATA
GET_STRANDED_INVENTORY_UI_DATA
GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL
GET_LEDGER_DETAIL_VIEW_DATA

**Comment by marcosmarxm** [comment]
I added your request to team backlog. Do you want to try to implement those reports?

**Comment by animer3009** [comment]
@marcosmarxm Yes please. 
I will try and in case success I wish to add all Report API missing report types.

**Comment by animer3009** [comment]
@marcosmarxm 
here is changes:
https://github.com/airbytehq/airbyte/pull/18279

**Comment by animer3009** [comment]
DONE.
