### ISSUE TITLE
Source Iterable hits rate limit on initial sync, even after greatly reducing the total count & size of streams

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17654]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2505](https://airbyte7538.zendesk.com/agent/tickets/2505)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Sunny

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Is this your first time deploying Airbyte?: No</li>
<li style="padding-bottom: 10px">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px">Memory / Disk: 64GB disk, t3.2xlarge, 32 GiB of Memory, 8 vCPUs, 64-bit platform</li>
<li style="padding-bottom: 10px">Deployment:  Docker</li>
<li style="padding-bottom: 10px">Airbyte Version: 0.40.10</li>
<li style="padding-bottom: 10px">Source name/version:  Iterable</li>
<li style="padding-bottom: 10px">Destination name/version:  Snowflake</li>
<li style="padding-bottom: 10px">Step: Initial sync</li>
<li style="padding-bottom: 10px">Description: Iterable fails on initial sync, even after greatly reducing the total count &amp; size of streams</li>
</ul>
<p dir="auto">I’ve tried several times and have not finished the initial sync of Iterable data. This includes both on the SaaS and the self-hosted versions of Airbyte. The problem appears related to rate-limiting by Iterable, and Airbyte eventually not being to take so much rejection.</p>
<p dir="auto">I have turned off all but 11 (out of 44) streams, set most of the active streams to full sync w/overwrite, and set the time window to just 5 days. All to no avail.</p>
<p dir="auto">It seems that the larger streams, e.g. <code style="background-color: #f9f9f9; padding: 2px 5px">user</code> and <code style="background-color: #f9f9f9; padding: 2px 5px">list-user</code> are the main culprits. I’ve attached the log from the most recent failure (on self-hosted Docker-based Airbyte).</p>
<p dir="auto">Here is a snippet of the latest failure from the logs:</p>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">2022-09-30 06:05:54 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):301 - failures: [ {
"failureOrigin" : "source",
"failureType" : "system_error",
"internalMessage" : "Request URL: https://api.iterable.com/api/lists/getUsers?listId=1659364, Response Code: 500, Response Text: {\"msg\":\"An error occurred. Please try again later. If problem persists, please contact your CSM\",\"code\":\"GenericError\",\"params\":null}",
"externalMessage" : "Something went wrong in the connector. See the logs for more details.",
"metadata" : {
"attemptNumber" : 0,
"jobId" : 2,
"from_trace_message" : true,
"connector_command" : "read"
},
"stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in &lt;module&gt;\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 123, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 114, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 128, in read\n    raise e\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 114, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 179, in _read_stream\n    for record in record_iterator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 277, in _read_full_refresh\n    for record in records:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 421, in read_records\n    response = self._send_request(request, request_kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 339, in _send_request\n    return backoff_handler(user_backoff_handler)(request, request_kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 297, in _send\n    raise UserDefinedBackoffException(backoff=custom_backoff_time, request=request, response=response)\nairbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.iterable.com/api/lists/getUsers?listId=1659364, Response Code: 500, Response Text: {\"msg\":\"An error occurred. Please try again later. If problem persists, please contact your CSM\",\"code\":\"GenericError\",\"params\":null}\n",
"timestamp" : 1664517894149
}
</code></pre>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/f/f55778898496d965040dd9ca2923d7b80cdb53c8.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/f/f55778898496d965040dd9ca2923d7b80cdb53c8_2_690x232.png" alt="image" width="auto" height="auto" style="max-width: 100%"><div style="display: none">
<span>image</span><span>1332×448 62.5 KB</span>
</div></a></div><p dir="auto"></p>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/ttzg4H63sO3rnLuM8BZ9D7rC8Ss.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">c48fb6ce_7a0b_45f8_a009_c62667781496_logs_2_txt.txt</a> (2.7 MB)</p> 

[<a href="https://discuss.airbyte.io/t/iterable-fails-on-initial-sync-even-after-greatly-reducing-the-total-count-size-of-streams/2769/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-01 at 00:01:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sunny on 2022-10-06 at 00:45:*

<blockquote><div class="zd-comment" dir="auto">I've created a Github issue to request improvement around this: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17654">https://github.com/airbytehq/airbyte/issues/17654</a><br><br>It sounds like you have taken many steps to try and get around this, but I'm going to see if there is anything else that can be done. Maybe restricting by <code>start_date</code>?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Sunny on 2022-10-06 at 00:47:*

<blockquote><div class="zd-comment" dir="auto">It does look like <code>end_date</code> has been added as well in v0.40.11 <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/17573">https://github.com/airbytehq/airbyte/pull/17573</a><br></div></blockquote>

**Comment by bazarnov** [comment]
@marcosmarxm 
Looks like the `https://api.iterable.com/api/lists/getUsers?listId=1659364` is invalid since there is no `List Id` is requested: `1659364`. In this case, should we bypass the record with status_code = `500`.  It could also be the code 400 - bad request. 
I've managed to reproduce the issue, but not sure if that's the best workaround.

**Comment by bazarnov** [comment]
Update: Working on it.

**Comment by bazarnov** [comment]
Updates: 
The retry fix is on the go. I'll attach the PR asap.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:15:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:16:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:20:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>
