### ISSUE TITLE
Generate config menu modal from yaml connector spec block

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17674]
## Tell us about the problem you're trying to solve
As described in the [Tech Spec](https://docs.google.com/document/d/11HrieUnA7oa6YsDhOVZpAVkOoZt2RWQQWJLPf7xQodY/edit#heading=h.x4dhu0sbkibe), something that is needed for the testing of a connector is a place to enter the "config" values, i.e. fill out the user inputs required to run the connector, as described in the connector spec.

## Describe the solution you’d like
The frontend should pull the connector specification out of the yaml editor contents, and use that schema to generate an input form, similar to how connector forms are generated from connector specifications today (in the ConnectorForm component)

Many parts of the ConnectorForm can likely be reused for the purpose, but there will undoubtedly be some changes required to port it over to this other part of the application, which is where most of the complexity in this issue will be.

## Acceptance Criteria
- A button exists that opens the Config menu in a modal, which contains a form generated from the connector specification
- When the connector specification is modified, the Config menu form is also updated
- Changes to the config menu form update the connector builder state that is keeping track of the config

**Comment by lmossman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Connector-Extensibility-6257455decf3920012f4e872/issues/airbytehq/airbyte/17674?planning-poker) with Zenhub @girarda

**Comment by flash1293** [comment]
PR is ready to review, but stacked on top of the refactoring PR
