### ISSUE TITLE
Source Shopify: cannot be stopped! error

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#17673]
## Environment
- **Airbyte version**:  0.40.10
- **OS Version / Instance**: Debian 11 Bullseye
- **Deployment**: GCP deployment as per the [guide](https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine/)
- **Source Connector and version**: Shopify 0.1.37
- **Destination Connector and version**: BigQuery denormalized 1.2.4
- **Step where the error happened**: Initial Sync job

## Current Behavior
The connector returns an error and keeps running before it stops. The error is Source cannot be stopped!, but I don't know what causes it. Logs attached

## Expected Behavior
The connector to finish successfully

## Logs
Attached

## Steps to Reproduce
1. Connect Shopify
2. Set BigQuery as the destination
3. Chose Incremental loads on all the possible streams

## Are you willing to submit a PR?
I don't have a sandbox 
for Shopify data that I can use, and the data belongs to a customer.

[b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_8_txt.txt](https://github.com/airbytehq/airbyte/files/9726407/b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_8_txt.txt)

**Comment by bazarnov** [comment]
@lluisgassovillarejo 
Seems like a connection issues, have you tried later on?

**Comment by bazarnov** [comment]
@YowanR This issue is not confirmed yet. Please do not add issues to the active Epics taken in work, as we cannot plan it properly and finish in time. Thanks.

**Comment by lluisgassovillarejo** [comment]
HI @bazarnov, it keeps failing with the same messages on every synch. I have scheduled every 8 hours and I always get the same result.
Thanks!

**Comment by bazarnov** [comment]
@lluisgassovillarejo please share the latest logs here, thank you.

**Comment by lluisgassovillarejo** [comment]
Here they are. Thanks! It seems related to the customers table, but I don't really understand the logs very well.
[b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_96_txt.txt](https://github.com/airbytehq/airbyte/files/9764424/b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_96_txt.txt)

**Comment by bazarnov** [comment]
```
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

This error occurs frequently, this is low level error caused by server empty response. In order to reproduce the issue you can try to use local Airbyte instance instead of GCP deployment just to reproduce the issue with customers stream. 
Otherwise, you can reach out our customer support and share the insights of this communication along with share your credentials, so we could reproduce the issue for you and fix it, once successully reproduced.

**Comment by lluisgassovillarejo** [comment]
I have the open-source version of Airbyte, so no customer support for me.
Shouldn't this be fixed at a connector level instead of on a user-by-user level? There is nothing special about our Shopify instance.

**Comment by bazarnov** [comment]
@lluisgassovillarejo any updates for far?

**Comment by philippeboyd** [comment]
@bazarnov Shopify as a source no longer seem to work (in Incremental) loading from scratch. I just set two of them and both are having the same `Response Code: 502` error as mention by @lluisgassovillarejo

It seems to be syncing with Full Refresh

**Comment by lluisgassovillarejo** [comment]
Hi,
thanks for following up. My connector is still running after 2 days, so no
updates so far.
I will keep you posted.

**Comment by bazarnov** [comment]
> @bazarnov Shopify as a source no longer seem to work (in Incremental) loading from scratch. I just set two of them and both are having the same `Response Code: 502` error as mention by @lluisgassovillarejo
> 
> 
> 
> It seems to be syncing with Full Refresh

Could you please, provide the latest logs, in a meanwhile, please switch back to the previous version, as a workaround.

**Comment by philippeboyd** [comment]
@bazarnov here are the logs

[default_logs_8147_txt.txt](https://github.com/airbytehq/airbyte/files/9789014/default_logs_8147_txt.txt)

**Comment by bazarnov** [comment]
> @bazarnov here are the logs
> 
> [default_logs_8147_txt.txt](https://github.com/airbytehq/airbyte/files/9789014/default_logs_8147_txt.txt)

@philippeboyd 

Please verify whether the link is valid or not. Is `Store_name` your real store name?
`https://<STORE_NAME>-store.myshopify.com/admin/api/2021-07/checkouts.json?`

**Comment by philippeboyd** [comment]
@bazarnov `<STORE_NAME>` means the real store name is redacted

Also, it cannot be a permission issue since the error is back-end (HTTP 502 and not 403) like I've specified in my [comment](https://github.com/airbytehq/airbyte/issues/17673#issuecomment-1279287003) as it was syncing with Full Refresh but not Incremental

**Comment by bazarnov** [comment]
@philippeboyd have you reproduced the same issue locally, not on GCP?

**Comment by erica-airbyte** [comment]
@bazarnov this is an OSS user, we do not have any other means of reaching out to OSS users other than at mentioning them in the issues they create. 

@lluisgassovillarejo are you able to assist with Baz's question? 

> Could you please, provide the latest logs, in a meanwhile, please switch back to the previous version, as a workaround.

**Comment by bazarnov** [comment]
> @bazarnov this is an OSS user, we do not have any other means of reaching out to OSS users other than at mentioning them in the issues they create. 
> 
> 
> 
> @lluisgassovillarejo are you able to assist with Baz's question? 
> 
> 
> 
> > Could you please, provide the latest logs, in a meanwhile, please switch back to the previous version, as a workaround.
> 
> 

@lluisgassovillarejo 
Once you're set with the connector, let me know, if any issue occurs.
