### ISSUE TITLE
Source Amazon Seller Partner: tech.allegro.schema.json2avro.converter.AvroConversionException

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#17689]
## Environment
- **Airbyte version**:  0.40.12
- **OS Version / Instance**:  Ubuntu 22.04, GCP
- **Deployment**: Docker 
- **Source Connector and version**: Amazon Seller Partner 0.2.27
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where error happened**: On time sync

## Current Behavior
I am regularly getting error like:

```
2022-10-06 08:21:33 - Additional Failure Information: tech.allegro.schema.json2avro.converter.AvroConversionException: Failed to convert JSON to Avro: Could not evaluate union, field quantity_for_local_fulfillment is expected to be one of these: NULL, DOUBLE. If this is a complex type, check if offending field (path: quantity_for_local_fulfillment) adheres to schema: 1216
```

The full log is attached. 
[aa3da8b6_08cd_4400_9354_85ad1f3c8606_logs_123_txt.txt](https://github.com/airbytehq/airbyte/files/9727780/aa3da8b6_08cd_4400_9354_85ad1f3c8606_logs_123_txt.txt)

**Comment by askarpets** [comment]
Hello @animer3009,
Field `quantity_for_local_fulfillment` is a part of `GET_AFN_INVENTORY_DATA_BY_COUNTRY` stream and the actual type returned for this field is a `string`. This is now reflected in corresponding schema.
Could you please upgrade to the latest connector version (`3.0.0`), refresh the schemas and try again?

Please let me know if this helped.
Thank you!

**Comment by askarpets** [comment]
Closing the ticket for now as no response from the customer. Please reopen if the issue still persists.
