### ISSUE TITLE
Documentation: Edit the Chargebee source connector doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#17687]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [Chargebee source connector doc](https://docs.airbyte.com/integrations/sources/chargebee/) needs to be edited for consistency per our [Writing Guidelines](https://hackmd.io/Bz75cgATSbm7DjrAqgl4rw#Writing-guidelines)

Good examples to follow:
https://docs.airbyte.com/integrations/sources/amplitude
https://docs.airbyte.com/integrations/sources/bing-ads

**Comment by digambar-t7** [comment]
Hey there,
I'd like to go for this.Is this still open?

**Comment by Amruta-Ranade** [comment]
@digambar-t7 Yep!

**Comment by digambar-t7** [comment]
Hey @Amruta-Ranade I went through all the references.I just need the clarity as to what type of alteration is expected.What does it require : rephrasing,restructuring or just formatting or something else.

**Comment by Amruta-Ranade** [comment]
Restructuring and reformatting as per the linked Writing guidelines. The linked examples should give you an idea for the tone/content approach we're looking for. You can write the first draft in a google doc and share it here.

**Comment by Amruta-Ranade** [comment]
The document still needs some work. Will provide detailed feedback next week

**Comment by Amruta-Ranade** [comment]
Updated during Hack Days
