### ISSUE TITLE
source-file check command does not work for YAML files

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#17688]
When attempting to perform a sync that extracts data from a YAML file, it fails on the sync on the perquisite check before the sync states. In the latest change, the `check()` method now makes use of the `load_dataframes()` which does not actually support YAML. We have a dedicated `load_yaml()` method which is used in the original `read()` method. 

```
Traceback (most recent call last):
  File "/airbyte/integration_code/source_file/source.py", line 95, in check
    next(client.load_dataframes(f))
  File "/airbyte/integration_code/source_file/client.py", line 318, in load_dataframes
    raise ConfigurationError(error_msg) from err
source_file.client.ConfigurationError: Reader yaml is not supported
Traceback (most recent call last):
  File "/airbyte/integration_code/source_file/client.py", line 314, in load_dataframes
    reader = readers[self._reader_format]
KeyError: 'yaml'
```

**Comment by YowanR** [comment]
@lazebnyi We should look into this before getting File to GA.

**Comment by brianjlai** [comment]
I would make the case that fixing this be prioritized as an OC issue rather than GA certification because any inadvertent change to `source-file` to bump to a new version beyond `0.2.23` will result in this breaking for us again.

**Comment by davydov-d** [comment]
as of version 0.2.33, both `check`, `read` and `discover` make use of `load_yaml`
