### ISSUE TITLE
Normalization & Transformation do not have a loading state

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#17692]
Adding a custom transformation or changing normalization does not have a loading state associated with the save button. We can probably wrap the appropriate calls in a `useAsyncFn` and use the loading state from that.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by matter-q** [comment]
@krishnaglick are you talking about this?

![image](https://user-images.githubusercontent.com/66960359/210648598-5f27dc46-eeb3-45fd-8759-65f49db3660e.png)

**Comment by krishnaglick** [comment]
> @krishnaglick, are you talking about this?
> 
> ![image](https://user-images.githubusercontent.com/66960359/210648598-5f27dc46-eeb3-45fd-8759-65f49db3660e.png)

Yes
