### ISSUE TITLE
NORMALIZATION_JOB_MAIN_CONTAINER_* environment variables missing in stable-with-resource-limits overlays

### ISSUE THREAD

**Issue by ogusak** [airbytehq/airbyte#17714]
## Environment
- **Airbyte version**:  0.40.9
- **OS Version / Instance**: EKS EC2 nodes on AL2_x86_64
- **Deployment**: Kubernetes (EKS)
- **Step where error happened**: Upgrade Airbyte to 0.40.9 from 0.39.37-alpha using stable-with-resource-limits overlays

## Current Behavior
airbyte-worker container fails to start reporting config error

## Expected Behavior
airbyte-worker-container should start and be healthy

## Logs
Error: couldn't find key NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST in ConfigMap <>/airbyte-env-....

## Are you willing to submit a PR?

https://github.com/airbytehq/airbyte/pull/17713

**Comment by cpdeethree** [comment]
Closing as the pull request was merged. Please reopen if you still see this issue
