### ISSUE TITLE
Source Pinterest: TypeError argument of type 'DateTime' is not iterable

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#17721]
## Environment
- **Airbyte version**: 0.40.10
- **OS Version / Instance**: Debian 11
- **Deployment**: Open Source On GCP as per the documentation. The machine has 2 CPUs and 16 Gb
- **Source Connector and version**: 0.1.7
- **Destination Connector and version**: BigQuery (denormalized typed struct) 1.2.4
- **Step where the error happened**: Initial Sync job

## Current Behavior
The connection errors out and gives the TypeError: argument of type 'DateTime' is not iterable. Logs attached for reference

## Expected Behavior
The connection to succeed.

## Logs
[b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_38_txt.txt](https://github.com/airbytehq/airbyte/files/9733345/b4906a66_196e_47e3_8c8a_2f83ca066f8f_logs_38_txt.txt)

## Steps to Reproduce
1. Connect Pinterest getting the client id, client key, and refresh token
2. Create a connection to BigQuery (I don't know if this happens with other destinations)
3. Run a sync job

## Are you willing to submit a PR?
Not for this particular connector, as the data belongs to a client.

**Comment by grubberr** [comment]
This problem was already fixed in this PR https://github.com/airbytehq/airbyte/pull/18285 `airbyte/source-pinterest:0.1.8`
