### ISSUE TITLE
Documentation: Edit the S3 destination connector doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#17749]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [S3 destination connector doc](https://docs.airbyte.com/integrations/destinations/s3) needs to be edited for consistency per our [Writing Guidelines](https://hackmd.io/Bz75cgATSbm7DjrAqgl4rw#Writing-guidelines)

Good example to follow:
https://docs.airbyte.com/integrations/destinations/snowflake

**Comment by saifrkhan** [comment]
👋 Hi @Amruta-Ranade 
I would love to work on this 😍

**Comment by Amruta-Ranade** [comment]
As discussed on Slack, reassigning the issue due to lack of bandwidth
