### ISSUE TITLE
OAuth button in connector is no longer required before checking

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17753]
Currently you can send a check of any connector using OAuth before actually signing up via the OAuth button.

This is a regression and we should prevent sending a check unless the OAuth login has happened.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Also affecting Hubspot

**Comment by timroes** [comment]
The primary reason for this is that the code that runs for `authSpecification` connectors that will mark the actual OAuth parameter fields as hidden, also removes the required status from them: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/core/jsonSchema/utils.ts#L40-L42 (Why so isn't clear anymore).

Even removing this though will not show the error beside the field, because the code in `serviceFormContext` which calculated `authErrors` only does so for the new `advancedAuth` method, but not the old `authSpecification`. We'd need to align that (and ideally align more code between those) to get errors properly working for `authSpecification` connectors.
