### ISSUE TITLE
Documentation: Edit the LinkedIn Ads source connector doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#17750]
**Note:** If you'd like to work on this issue, please read the [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation) and comment on the issue to confirm it is still up for grabs.

The current [LinkedIn Ads source connector doc](https://docs.airbyte.com/integrations/sources/linkedin-ads/) needs to be edited for consistency per our [Writing Guidelines](https://hackmd.io/Bz75cgATSbm7DjrAqgl4rw#Writing-guidelines)

Incorporate feedback from Technical Cloud Support:  
Authorize App: make the URL step more clear, highlight was needs to be different in the URL (re-order). Maybe make this more step based. 

Good example to follow:
https://docs.airbyte.com/integrations/sources/salesforce

**Comment by avinash28196** [comment]
Hi @Amruta-Ranade 
I would like to work on this

**Comment by sammychris** [comment]
Hi @Amruta-Ranade, I would love to work on this.

**Comment by Amruta-Ranade** [comment]
@sammychris any updates on this?

**Comment by sammychris** [comment]
@Amruta-Ranade Still on it. Hopefully you will get feedback from me by Friday.

**Comment by sammychris** [comment]
Hello @Amruta-Ranade, sorry for the delay. First, I had to take the time to learn more about the platform and how to make good use of connectors. The past weeks has been so intense for me, hopefully things are getting better now.

Here is my link to the article. 
https://docs.google.com/document/d/1xvLplfNPePRoMSImuysdc8uFYpX-kdQBSEekiCbCbz0/edit?usp=sharing

Please, just in case there are any issues or suggestions, I'm open to feedback. Thanks

**Comment by Amruta-Ranade** [comment]
Thank you! Can you give me commenting permission on the doc please?

**Comment by sammychris** [comment]
Hello @Amruta-Ranade, permission granted. Thanks

**Comment by sammychris** [comment]
Hello @Amruta-Ranade, I have updated the doc. Just a quick review. I'm open to feedback. Thanks

**Comment by Amruta-Ranade** [comment]
Thanks! Feel free to open a PR :)
