### ISSUE TITLE
Gracefully handle `UnknownHostException` as a config

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#17756]
## Tell us about the problem you're trying to solve
Add validation check for `UnknownHostException` within `check` stage. Currently, there's error handling that is caught within the `discover` phase and that later in the lifecycle for Airbyte. Preferably Airbyte catches this earlier. This follows after the conversation from [here](https://github.com/airbytehq/oncall/issues/708)

## Describe the solution you’d like
Add a validation check for pinging host within the check stage of Airbyte lifecycle

## Additional context
N/A

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by bleonard** [comment]
Investigate if this is error in their setup. If so and we can reliably catch it, then:

1. return instructions for user
2. stack trace as a config_error
3. See if there is something to add to `check` - it has to be fast.

**Comment by akashkulk** [comment]
This is actually handled as a `ConnectionErrorException`
Which is handled at the top-level as a config-error. I think this can be closed - there is no action to take here. This would not create a Sentry crash. In addition, the workspace in question was Liren's test workspace
