### ISSUE TITLE
Orchestrator repl pod pool for better init times

### ISSUE THREAD

**Issue by obastemur** [airbytehq/airbyte#17776]
Hey folks, this is a very cool product and community, keep up the good work!

I've been strictly measuring the time spent prior to actual replication task. It's pretty stable around 30 to 36 seconds on a pricey AWS host I'm running the tests.  Perhaps this number is different on each host... Long story short, it's a bit overkill for the couple of minute jobs. 

Curious if there is a plan for.. i.e.. pod pool? or alternative approaches?

If this or similar task is not on the list (which I failed to find one), what would be the process for collaboration on the details? (as this might be a breaking change for some)

**Comment by davinchia** [comment]
Hi, we don't have plans for this. We want pod isolation for logical and physical separation of data. We are planning to make several big improvements to the general architecture, so cost should go down in general. 

In terms of collaboration, feel free to reach out on Slack!
