### ISSUE TITLE
Airbyte does not use state from last attempt

### ISSUE THREAD

**Issue by marcelopio** [airbytehq/airbyte#17774]
## Environment
- **Airbyte version**:  0.40.14
- **OS Version / Instance**: Arch Linux
- **Deployment**: docker
- **Source Connector and version**: any
- **Destination Connector and version**: (any
- **Step where error happened**: Sync Job

## Current Behavior
If an error occurs during first attempt but the connector submited an state message, Airbyte does not use that state message on the second attempt.

If I run another sync, after the first one failed all 3 attempts, it continues from where the first attempt of the first sync failed.

## Expected Behavior
Airbyte should continue from where the first attempt stopped. I do think this is an extremely urgent bug 

## Logs

[First job](https://github.com/airbytehq/airbyte/files/9742752/a977e1f0_1275_47c8_9995_70be8c2bb76d_logs_22_txt.txt)

[Second job](https://github.com/airbytehq/airbyte/files/9742791/a977e1f0_1275_47c8_9995_70be8c2bb76d_logs_24_txt.txt)

## Steps to Reproduce
1. Use this source:
```python
#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#


import json
import typing
from datetime import datetime
from typing import Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type, AirbyteStateMessage, AirbyteStateType, AirbyteStreamState, StreamDescriptor, AirbyteStateBlob, SyncMode,
)
from airbyte_cdk.sources import Source


class SourceStateBug(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        try:
            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        streams = []

        stream_name = "Test"
        json_schema = {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {"test": {"type": "string"}}
        }

        streams.append(AirbyteStream(name=stream_name, json_schema=json_schema, supported_sync_modes=[SyncMode.full_refresh, SyncMode.incremental]))
        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: typing.List[AirbyteStateMessage]
    ) -> Generator[AirbyteMessage, None, None]:

        stream_name = "Test"
        fail_on_number = config["fail-on-number"]

        last_number = 1 if not state else state[0].stream.stream_state.dict()['last_number']
        print(f"Last number: {last_number}")

        for i in range(last_number, 10):
            print(f"Loop variable: {i}")
            if last_number == 1 and fail_on_number == i:
                raise Exception("Stopping for expected exception")
            yield AirbyteMessage(
                type=Type.RECORD,
                record=AirbyteRecordMessage(stream=stream_name, data={"test": f"Number: {i}"}, emitted_at=int(datetime.now().timestamp()) * 1000),
            )
            yield AirbyteMessage(
                type=Type.STATE,
                state=AirbyteStateMessage(
                    type=AirbyteStateType.STREAM,
                    stream=AirbyteStreamState(stream_descriptor=StreamDescriptor(name="Test"), stream_state=AirbyteStateBlob.parse_obj(
                        {"last_number": i}))
                )
            )

```
spec:
```yaml
documentationUrl: https://docsurl.com
connectionSpecification:
  $schema: http://json-schema.org/draft-07/schema#
  title: State Bug Spec
  type: object
  required:
    - fail-on-number
  properties:
    fail-on-number:
      type: number
      description: Number to fail on
      default: 5
```
2. Run a connection, the second attempt should continue from the number 5

## Are you willing to submit a PR?

Yes, but I think this is a design issue, so I would need to discuss a solution

**Comment by marcosmarxm** [comment]
Airbyte only will save and reuse the state IF your destination had flushed the records to there. If not it will continue use the start or previous one.

**Comment by marcelopio** [comment]
Yes, the records were flushed, but airbyte does not continue from the previous one. Airbyte will only load the state when starting the job, not at the start of the attempt. You can check that the second sync logs that I attached continued from where it left of.

Basically everything will work if I configure Airbyte to have only one attempt. But that is not a good solution.

**Comment by marcosmarxm** [comment]
Oh sorry @marcelopio I understood wrongly here. Probably the reason is the source reads from the `input_state.json` and reuses it every attempt instead of reading from the updated state.
```
2022-10-11 23:52:33 INFO i.a.w.p.DockerProcessFactory(create):163 - Preparing command: docker run --rm --init -i -w /data/180/0 --log-driver none --name source-test-flush-read-180-0-nefob --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_JOB_ATTEMPT=0 -e WORKER_CONNECTOR_IMAGE=airbyte/source-test-flush:dev-2 -e AIRBYTE_VERSION=0.40.14 -e WORKER_JOB_ID=180 airbyte/source-test-flush:dev-2 read --config source_config.json --catalog source_catalog.json --state input_state.json
```

@benmoriceau / @evantahler can you help me here, if this is behavior is expected for the state update?

**Comment by evantahler** [comment]
cc @salima-airbyte this seems like a bug between sync attempts

**Comment by benmoriceau** [comment]
Hello,
I think that the issue is that the source become unresponsive that for that reason we don't persist any state.
Either because we don't reach the persist state step in the temporal workflow or because the state is not added to the sync output because it is bypass because of the exception as well. 

@marcosmarxm Could you help reproducing? 

On our side, we are planning to do https://github.com/airbytehq/airbyte/issues/16762 which should save the state once emitted (maybe with a buffer).

**Comment by marcelopio** [comment]
I don't think that is the issue. You can check the logs that I sent. The state was persisted ( I checked before the sync was finished) and the second sync uses the state that was persisted on the first one. @marcosmarxm is right, `input_state.json` is not updated between attempts. That is because we only get the current state at the start of the job, not at the start of the attempt

**Comment by marcelopio** [comment]
We only get the state here:
https://github.com/airbytehq/airbyte/blob/c6519430daeac5d2384d5817228ab2a32a2325a7/airbyte-persistence/job-persistence/src/main/java/io/airbyte/persistence/job/DefaultJobCreator.java#L134

Afterwards, the `input_state.json` is created from the job database, not from the connection, so it is never updated with current state

**Comment by marcelopio** [comment]
Can I help with any more details?

I was trying to think in a solution and what I think is that we should update the database attempt schema to also have the state, and do when the attempt starts, we get the current state from it, and not from the job. That way we have the traceability of what the attempt used as a state.
