### ISSUE TITLE
source-airtable: `discover` generates incomplete schema

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#17794]
## Environment
- Source-connector: `source-airtable:0.1.2`

## Current Behavior
The generated catalog misses some fields on Airtable stream if these fields are `null` in the first row of a table.
It breaks downstream normization

## Expected Behavior
The discovered catalog is complete

**Comment by bazarnov** [comment]
@alafanechere here is the explanation of what is happening during the discovery stage with this connector: 
https://github.com/airbytehq/airbyte/issues/11757#issuecomment-1141156148

This problem could be resolved only by accessing `Metadata API`, otherwise, we will have an incomplete or broken schema.

**Comment by alafanechere** [comment]
@bazarnov I opened a PR to suggest a small improvement that could mitigate the problem a bit: https://github.com/airbytehq/airbyte/pull/18491

**Comment by bazarnov** [comment]
I think this one could be closed for now, until we decide to use `Metadata API`

**Comment by YowanR** [comment]
Hey all, FYI that there's some update on the [Metadata part ](https://airtable.com/developers/web/api/changelog?utm_ID=recebVmIxYe5ut93c&utm_source=lifecycle_team&utm_medium=email&utm_campaign=it_ss_api_auth_public_beta&utm_content=email_waitlist-users&utm_extra5=metadata-api-users#anchor-2022-11-15). It's in Beta but might be sufficient to unblock.
cc @lazebnyi can we just see if the changes from Airtable are enough to unblock? Probably work for Q1 2023 :)
