### ISSUE TITLE
Multi-Cloud Documentation

### ISSUE THREAD

**Issue by sophia-wiley** [airbytehq/airbyte#17795]
Earliest users in November(?) -- will need some sort of documentation for them. 

**Cloud**
Not exactly sure when it will be available on Cloud. (?) 

Upcoming changes (so far):
* Pages that will change:
    * Connection settings
    * Settings 
    * New connection
    * Onboarding
* Users will be able to change their data residency
* Default setting is United States
    * Users can choose a different default data residency location in settings.
* Data residency location options:
    * United States
    * Australia 
    * Canada
    * Europe 
    * India 
    * United Kingdom

Internal documentation for reference: [2764](https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte-cloud/2764)

User-facing changes: [2653](https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte-cloud/2653)

Figma mockup: https://www.figma.com/file/Xa2bg6dg5AoxA1mFJ3HXsG/MULTI-CLOUD?node-id=374%3A9485

Multi-Cloud Epic Phase 3: [2259](https://app.zenhub.com/workspaces/cloud-platform-6259ee50ab53b4001d625d79/issues/airbytehq/airbyte-cloud/2259)

**Comment by andyjih** [comment]
We'll want to update the IP addresses listed in this page as well: https://github.com/airbytehq/airbyte-cloud/issues/2425

**Comment by josephkmh** [comment]
Timeline: our plan is to have an internal EU release by **November 4th** (behind a feature flag) and a full EU cloud launch on **November 9th**

**Comment by sophia-wiley** [comment]
Multi-cloud doc updates are available here:
[Choose your default data residency](https://docs.airbyte.com/cloud/managing-airbyte-cloud/#choose-your-default-data-residency)
[Set up a connection](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud#set-up-a-connection)
[Choose the data residency for a connection](https://docs.airbyte.com/cloud/managing-airbyte-cloud/#choose-the-data-residency-for-a-connection)
[Allowlist IP addresses](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud/#allowlist-ip-address)
