### ISSUE TITLE
Source Intercom: is reading records even without state changes generating duplicates (can affect other connectors)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#17797]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2655](https://airbyte7538.zendesk.com/agent/tickets/2655)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi, I am trying to run incremental append mode with Intercom stream “contacts”. I have 9 contacts in my account. Upon the first sync it replicates all 9 but when the second sync it should not append any data as no change is made but it still replicates 1 contact.</p>
<p dir="auto">Logs are attached.<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/0/0d620b47d68f75e24339301f26499c62676edf16.png" alt="image" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto">Airbyte Version : 0.40.06<br>
Destination : Redshift/0.3.49<br>
Source: Intercom/0.1.26<br>
Stream  : contacts.<br>
Cursor field : Source defined [updated_at]<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/2/2e635c314247df154aad38e37fbacd0a1260a0ba.png" alt="image (6)" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto">Data At destination with repeated entry after 2nd sync<br>
<img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/3/3da5c9e0c493fa065ff787450f1b1e89e8703b53.png" alt="image (7)" width="auto" height="auto" style="max-width: 100%"></p>
<p dir="auto">Logs sync 01<br>
<a href="https://discuss.airbyte.io/uploads/short-url/sWyYClh6EBRl1OvUqrIfJsix3Qu.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">logs-865.txt</a> (55.9 KB)</p>
<p dir="auto">Logs sync 02<br>
<a href="https://discuss.airbyte.io/uploads/short-url/h9NrtnKtXdj6gAMFQBG3rba4F64.txt" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">logs-866.txt</a> (55.6 KB)</p> 

[<a href="https://discuss.airbyte.io/t/incremental-mode-is-not-working-correct-for-stream-contacts-of-source-connector-intercom/2834/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-07 at 16:03:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
This is also happening to Freshdesk: https://discuss.airbyte.io/t/freshdesk-connector-incremental-sync-mode-not-working/2828

And Zendesk: https://github.com/airbytehq/airbyte/issues/16460

**Comment by marcosmarxm** [comment]
Airbyte guarantees at least one record, but this is causing problems to user. 
1. Fix it
2. Improve our documentations to become very clear to users what hppens when using incremental sync mode.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-10 at 18:57:*

<blockquote><div class="zd-comment" dir="auto">I created the issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17797">https://github.com/airbytehq/airbyte/issues/17797</a> to investigate and solve the issue! ANy updates I'll return to you.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-10 at 19:02:*

<blockquote><div class="zd-comment" dir="auto">Hello! I created one issue to investigate what is causing this error (other connectors are reporting the same problem).&nbsp;<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17797">https://github.com/airbytehq/airbyte/issues/17797</a><br>Any updates I'll return to you!<br></div></blockquote>

**Comment by Wolff-Lucas** [comment]
I have the same issue but with bigquery destination.

**Comment by marcosmarxm** [comment]
@Wolff-Lucas are you using the same source?

**Comment by Wolff-Lucas** [comment]
Yes @marcosmarxm , i'm using Zendesk
