### ISSUE TITLE
Source Jira: add Oauth2.0 access token support

### ISSUE THREAD

**Issue by naren-experienceflow** [airbytehq/airbyte#17818]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**:  Docker
- **Source Connector and version**: Jira
- **Destination Connector and version**: Elastic Search

## Current Behavior
Currently only api token is supported for jira

## Expected Behavior
Like github, Jira should also support access token

**Comment by lazebnyi** [comment]
duplicate - https://app.zenhub.com/workspaces/python-connectors-6262f8b593bb82001df56c65/issues/gh/airbytehq/airbyte/7481
