### ISSUE TITLE
Slow Response from Reset Table button

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1781]
## Expected Behavior
When I click on the "reset your data" button on the sync page, I expect some feedback that something will happen and my table will be reset... and maybe when it is done?

## Current Behavior
It works fine but as shown in the video below, it takes a few seconds to react... Not very user friendly...

https://www.loom.com/share/5f410c721b4f45269529984235e72703

Maybe some sort of [spinner](https://loading.io/css/)?

## Severity of the bug for you
Low (but confusing!)

## Airbyte Version
0.13.0

**Comment by cgardens** [comment]
Fixed by: https://github.com/airbytehq/airbyte/pull/2246
