### ISSUE TITLE
Generate Typescript connector builder API client code 

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17812]
## Tell us about the problem you're trying to solve
As described in the [Tech Spec](https://docs.google.com/document/d/11HrieUnA7oa6YsDhOVZpAVkOoZt2RWQQWJLPf7xQodY/edit#heading=h.i0wxd065dtfh), the connector builder server API that will back the UI is defined in an OpenAPI specification, so that server and client code can be auto-generated from the API spec.

## Describe the solution you’d like
This ticket involves configuring the airbyte-webapp to auto-generate typescript classes from the connector-builder-server OpenAPI spec on build, so that the webapp always has the most up-to-date classes available for the API.

This will look similar to how we generate client classes from the Airbyte API spec: https://github.com/airbytehq/airbyte/blob/62500af93b8a0747011fffc27c636bbe817d6349/airbyte-webapp/orval.config.ts#L5

## Acceptance Criteria
- Typescript classes are auto-generated in the airbyte-webapp module from the connector-builder-server API spec on build
- Ignore the generated classes, similar to [AirbyteApiClient](https://github.com/airbytehq/airbyte/blob/ec5496840df4b0af93afa341d820268d0212c7e9/airbyte-webapp/.gitignore#L32-L33)

**Comment by sherifnada** [comment]
blocked on tim review who is PTO
