### ISSUE TITLE
Add auto-detect schema changes flow to connection replication settings page

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17828]
When changes are auto-detected:

1. Show banner below connection widget
2. Block the streams table
3. User clicks on review changes to look at diffs
4. User can save or cancel the changes

Prototype - Click on "Slack Community" to see the flow:

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A37260&scaling=min-zoom&page-id=972%3A36208&starting-point-node-id=972%3A36212&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
