### ISSUE TITLE
Show auto-detect schema changes status in connection list view

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17829]
Show that changes were detected on the connections list.

Prototype:
https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=857%3A25233&scaling=min-zoom&page-id=857%3A24319&starting-point-node-id=857%3A25233&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
