### ISSUE TITLE
Stripe integration's account / secret regex should support test accounts

### ISSUE THREAD

**Issue by savv** [airbytehq/airbyte#1782]
## Expected Behavior
Possible to add a connector for Stripe's test environment.

## Current Behavior
![image](https://user-images.githubusercontent.com/747519/105514334-a7eb4280-5cd3-11eb-8999-17b78109e797.png)
![image](https://user-images.githubusercontent.com/747519/105514384-b8032200-5cd3-11eb-9076-f6f826138714.png)

## Severity of the bug for you
Medium

## Airbyte Version
0.13.0-alpha

## Additional context
quickstart tutorial

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084920801) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
To handle this, we probably need to adjust the regex patterns used in the[ Stripe spec.json](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-stripe-singer/source_stripe_singer/spec.json)

**Comment by sherifnada** [comment]
@savv You can still use your Stripe test data by supplying a test secret key. The account ID remains the same in either case. Is there a reason to prefer the private publishable key to the account ID?
