### ISSUE TITLE
[Epic] New UX refresh flow for auto-detect schema changes

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17825]
[Figma](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=1048%3A46434&scaling=min-zoom&page-id=972%3A36208&starting-point-node-id=972%3A36212)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
I've added questions RE: what states are possible (and thus background shading) in #19092

**Comment by edmundito** [comment]
Discussed with the team at FE sync. This covers only the diff support on the table but may need more issues to support the rest of the changes. We will need to figure out the timeline of when this will be released (with and without auto-detect schema changes)

**Comment by edmundito** [comment]
I split this off from the table redesign and made it into a separate epic to be discussed separately
