### ISSUE TITLE
Extract stream fields table into detail view panel

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17824]
Move the stream fields table from expand/collapse into its own panel as shown in the design:

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=857%3A24319&node-id=865%3A52984&viewport=124%2C-519%2C0.25&scaling=min-zoom&starting-point-node-id=865%3A52984&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@ambirdsall we originally discussed assigning this to the cloud team but it's already done as part of #17823 because it wasn't too much of an extra effort.
