### ISSUE TITLE
Export secrets separately from the rest of the configuration

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1783]
## Tell us about the problem you're trying to solve
Following-up on #1402, it would be nice when exporting to separate sensitive data from the rest of the configurations.

## Describe the solution you’d like
Fields marked as secrets in the spec.json of connectors should not be included in the archive. 
(but in a separate secret archive? that can be merged with the config archive?)

## Additional context
Example of an archive with sensitive passwords included:
[airbyte_archive.tar.gz](https://github.com/airbytehq/airbyte/files/5857357/airbyte_archive.tar.gz)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368084948597) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
done
