### ISSUE TITLE
Update new streams table to edit namespace and stream name options with modals 

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17831]
1. Add modals for editing stream name and namespaces
2. Remove options from connection (?) and replication settings

Prototype - Click on the gear icon next to namespace and stream names on the streams table

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=865%3A52984&scaling=min-zoom&page-id=857%3A24319&starting-point-node-id=865%3A52984&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
