### ISSUE TITLE
Update settings to toggle auto-detect schema changes notifications

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17830]
Update the connections settings page to enable/disable notification for auto-detect schema changes.

Design:
https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=2062%3A60213&t=EAjh7xtF8vK5jde6-1

Backend changes:
API: #18636
Impl: #18735

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by jdpgrailsdev** [comment]
@andyjih We need updated UX design for notification preferences for auto-detect schema changes.
