### ISSUE TITLE
Improve styling of react-select

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17846]
We should improve the styling of our react-select a bit:

* Add a better `:focus-visible` outline (similar to other input fields). Currently only the caret is slightly darker when the select is focused.
* Show the currently keyboard highlighted option in the react-select. Actually our react-select does support keyboard navigation (up/down and enter), but there is no indication which element is currently highlighted and will be selected, why this is nearly invisible to users. We should properly highlight that element.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
