### ISSUE TITLE
Saving a refreshed source schema does not save the updated source schema

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#17858]
## Environment
- **Airbyte version**:  0.40.14
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: MSSQL 0.4.20
- **Destination Connector and version**: Snowflake 0.4.38
- **Step where error happened**: Refresh source schema

## Current Behavior
When refreshing source schema, we see the newly added columns
![image](https://user-images.githubusercontent.com/3239656/195202520-8cb7f81d-c478-407f-ab8f-d2821939ba1f.png)

Which will appear in the schema definition on the UI

![image](https://user-images.githubusercontent.com/3239656/195202687-029d7013-699c-4524-8b6f-452b7ace299d.png)

But once we save the changes, those columns are gone and refreshing source schema will still show the missing columns

![image](https://user-images.githubusercontent.com/3239656/195202857-3c4f874b-f09b-4433-81da-4eabd8cc23fe.png)

## Expected Behavior
Airbyte should save the new schema and not the old one

## Steps to Reproduce
1. Setup a MSSQL Source
2. Setup Snowflake Destination
3. Create a MSSQL table
4. Create a connection
5. Update table by adding a new column
6. Update Airbyte connection source schema

**Comment by mfsiega-airbyte** [comment]
In addition to confirming the diff, the connection also has to be saved (the button is at the bottom of the form). It appears that the diff was confirmed but the connection wasn't actually updated.

We've opened https://github.com/airbytehq/airbyte/issues/26348 to improve the overall UX here.
