### ISSUE TITLE
Retesting a connector in the UI has no feedback

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17860]
When using the "Retest" button on a saved connector, the retest will run, but there is no visual feedback if the restest was actually successful (and maybe even not when failed -need to validate that).

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Looked through the code and did notice that when testing a connection succeeds there is no implementation to show a message. Currently, a message only appears when there is an error.

**Comment by flash1293** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/15731
