### ISSUE TITLE
If Airbyte is closed during a sync the running job is not marked as failed

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1788]
## Expected Behavior
* stop the job

## Current Behavior
* job stops but is not marked as failed. when start back up that connection is permanently unusable because the state machine can't heal itself.

**Comment by michel-tricot** [comment]
As long as we have threading for workers, that will be a hard problem to fix.

**Comment by cgardens** [comment]
I am in favor of cleaning this up when airbyte is restarted.

**Comment by cgardens** [comment]
Specifically when the scheduler starts up, I think.
