### ISSUE TITLE
Source Google Search Console: OAuth flow deprecated

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#17890]
## What
Google has [deprecated some OAuth](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) flows as of October 3, 2022 and this might be affecting the [Google Search Console source connector](https://docs.airbyte.com/integrations/sources/google-search-console). Our OAuth test credentials work, but OAuth credentials created after February 28, 2022 are blocked.

## Expected Behavior
- Users should be able to authenticate with OAuth.
- Or the OAuth flow should be removed, leaving the service account authentication option.

**Comment by marcosmarxm** [comment]
Zendesk ticket #[2749](https://airbyte7538.zendesk.com/agent/tickets/2749) has been linked to this issue.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-10-12 at 14:18:*

<blockquote><div class="zd-comment" dir="auto">We've created an issue to keep track of updates and investigate this further:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/17890">https://github.com/airbytehq/airbyte/issues/17890</a><br></div></blockquote>

**Comment by YowanR** [comment]
@grubberr @YuliiaNahoha We need to prioritize this one issue for the next sprint.

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-30 at 16:32:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by roman-yermilov-gl** [comment]
Hi @natalyjazzviolin 
Spent some time on investigating of what may affect the connector when OAuth is used for login. As I understand there are some restrictions related to `redirect_url` for verified accounts, such as loop-back url is not allowed or desktop apps must login a user through system browser. I didn't find what may cause our flow to fail and I also checked OAuth for the connector on `cloud.airbyte.io` and it was successful. Could you please provide us with more details of what exactly may affect the flow or what accounts are blocked? For now I am not sure why we should turn the OAuth authorization off
