### ISSUE TITLE
Destination crash with empty schemas

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1789]
## Expected Behavior

I expect a simple pipeline from Exchange Rate to Postgres to sync without error.

## Current Behavior
The sync fails because I manage to configure my destination with an empty schema:

https://www.loom.com/share/e9d9192322cf4355b025b65feef9703d

## Steps to Reproduce
1. When creating a destination
1. delete the "public" string in the schema field but don't input anything else (public still shows up in the field and form validates successfully)
1. run a sync 
1. crash

## Severity of the bug for you
High

## Airbyte Version
0.13.0

**Comment by ChristopheDuong** [comment]
If you export to archive, you can notice the empty schema on the Postgres destination

[airbyte_archive_empty_schema.tar.gz](https://github.com/airbytehq/airbyte/files/5858022/airbyte_archive_empty_schema.tar.gz)

**Comment by cgardens** [comment]
is this actually a frontend issue?
