### ISSUE TITLE
The Airbyte Platform can accept and store updated configurations from syncs

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17909]
_Part of the [Single Use Refresh Tokens](https://github.com/airbytehq/airbyte/issues/3990) Epic_

The Protocol Change to add `AirbyteControlMessage.ConnectorConfig` was done via https://github.com/airbytehq/airbyte/pull/17907. 

```js
{
  type: CONTROL,
  emitted_at: 123456,
  connectorConfig: {
    config: : {
       "oAuthToken": "abc123"
    }
  }
}
```

Now, we need to use these messages to store updated configurations sent by the connector:

1. Update the AirbyteMessageTracker to process the new messages; release a new version of Airbyte OSS & Cloud
    * ~~Config updates should be stored in-memory until the end of the sync~~
    * We should only write config updates once (to avoid undo stress on the database)
    * We should write config updates regardless of if the sync was successful or not 
2. Ensure that AirbyteConnectorConfigMessage is checked for all types of activities - CHECK, DISCOVER, and READ/WRITE

Follow the pattern for STATE updates to be persisted at the end of the sync. There is some nuance for workers running on Cloud (e.g we don't have database access in the middle of a sync).  The risk here is that if the worker crashes the update is lost... but that's OK for now. We can resist this in later work. 

Look here - https://github.com/airbytehq/airbyte/blob/b05a5b2a6a7c01fe4ee8f3c627fa8f31a02332fa/airbyte-commons-worker/src/main/java/io/airbyte/workers/internal/AirbyteMessageTracker.java#L236-L245

**Comment by evantahler** [comment]
Currently in AirbyteMessageTracker, the method `handleEmittedOrchestratorConnectorConfig()` exists and is passed all the ConnectorConfig messages.  Feel free to use or remove as needed.

**Comment by evantahler** [comment]
cc @davinchia 

In our hack day project, we made internal APIs so the worker would persist data mid-sync rather than waiting until the end. https://github.com/airbytehq/airbyte/pull/18630.  Since we 
1. really need to persist new configs even if the sync fails
2. don't want to write user secrets to a file
we probably should the internal-API route

**Comment by bazarnov** [comment]
@evantahler @pedroslopez 
cc  @davinchia 

As for this:

> 1) really need to persist new configs even if the sync fails
> 2) don't want to write user secrets to a file we probably should the internal-API route

2. We also should consider how to test the actual connector work while on local testing, since the `SingleUseRefreshToken` returns a `CONTROL` type message, but doesn't update the actual `secrets/config.json` we have issues are testing connectors processed locally.

**Comment by evantahler** [comment]
@bazarnov at least for `/test` command, we do have the plumbing in place to update the GCS secrets - https://github.com/airbytehq/airbyte/pull/20076

**Comment by alafanechere** [comment]
> We also should consider how to test the actual connector work while on local testing, since the SingleUseRefreshToken returns a CONTROL type message, but doesn't update the actual secrets/config.json we have issues are testing connectors processed locally.

@bazarnov Local SAT testing should now update local config on control message output. Testing on `/test` and `/publish` do update GSM secrets after a test run. Feel free to ping me if the behavior does not match your expectation.
