### ISSUE TITLE
Syncing from stripe source to two different redshift schemas truncates data from the first schema

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1790]
## Steps to Reproduce
1. Setup stripe source
1. Sync from stripe to redshift to any schema
1. Setup another connection from the same source to a new redshift destination and run a sync. Now the data in the first schema is empty. 

## Severity of the bug for you
Medium

## Airbyte Version
v0.13.0-alpha

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368208753711) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Are you trying to replicate a source simultaneously into 2 schemas and expect to keep both locations up to date?
