### ISSUE TITLE
API Connector Memory leaks

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#17919]
_From a [slack thread](https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1665590452984999)_
We've got connectors (like `source-github) that seem to be running out of memory constantly.   This is a substream whose parent (pullrequests) has caching enabled and that cache may be growing too large.

![image.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/c07190f5-3afc-45a1-b112-d94a461c4a9e)

The CDK uses VCR for caching requests... but maybe that's not working right?

---

Some interesting links
* for some reason it uses a custom vcr implementation, but it's doing the same thing in use_cassette - https://github.com/airbytehq/airbyte/blob/3894134d1115b7c9ba181684f1aba66bec500a63/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/cache.py#L39
* Maybe we want "once" rather than - "new_episodes" https://vcrpy.readthedocs.io/en/latest/usage.html#once

**Comment by evantahler** [comment]
Evan's theory - while VCR is persisting request responses to disk (in YAML), it is still storing every request it made in memory for matching.  https://vcrpy.readthedocs.io/en/latest/advanced.html (`Cassette.requests()`) seems to indicate we can retrive this list. 

Some ideas:
* we monkey patch VRC to use sqlite (on disk) rather than memory to store the list of requests it has made
* if we hit (N=1,000,000) request URLs in memory, the source should exit.  Incremental syncs will continue on the next run, but full-refresh sources will be out of luck.

cc

**Comment by evantahler** [comment]
I think https://requests-cache.readthedocs.io/en/stable/ rather than VRC might be better for our use-case anyway

**Comment by evantahler** [comment]
cc @sherifnada and @bleonard

**Comment by bleonard** [comment]
Maybe we flush and/or delete files if we are hitting some memory / file limit?

**Comment by sherifnada** [comment]
Agreed with your analysis here evan: https://github.com/airbytehq/airbyte/issues/17919#issuecomment-1276822001

It's probably easier to solve this in VCR if possible but if not, I have no issue with replacing VCR with the other lib. 

Not sure how we make the call if Ops handles this or extensibility. Off the cuff I'd say this is ConEx but won't say no if Ops wants it!

**Comment by evantahler** [comment]
@grubberr is investigating:
> ok I will syncing pull_request_commits stream with memory profiler using VCR vs requests-cache+sqlite and update result to that issue

**Comment by YowanR** [comment]
@lazebnyi @YuliiaNahoha Just FYI that this is getting prioritized

**Comment by evantahler** [comment]
moving over to `requests-cache` seems like a HUGE win!   
* ~ 75% memory saving
* ~ 2x faster (21min -> 12min)

So... we should make this change!

**Comment by bleonard** [comment]
very exciting. do we have a good idea of the number of connectors this affects? (I assume a lot)

**Comment by evantahler** [comment]
> very exciting. do we have a good idea of the number of connectors this affects? (I assume a lot)

... All of the API connectors that use the CDK?

**Comment by YowanR** [comment]
Both low-code and python connectors are impacted? Can we consider a platform level fix or do we need to fix individual connectors? cc @sherifnada

**Comment by pedroslopez** [comment]
@YowanR this should be a change to how the CDK handles cached streams, so connectors using caching that would benefit from this would just have to update to the latest CDK version.

I did find some custom caching implementations that we may need to look out for, such as BingAds:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/cache.py

**Comment by grubberr** [comment]
https://github.com/airbytehq/airbyte/pull/17990 passed on airbyte review

**Comment by grubberr** [comment]
```
root@source-github-read-736618-1-mkumr:/config# ps aux | grep -i python
root          10  0.6  0.3  76308 65536 ?        S    17:01   1:13 python /airbyte/integration_code/main.py read --config source_config.json --catalog source_catalog.json --state input_state.json

root@source-github-read-736618-1-mkumr:/config# cat /sys/fs/cgroup/memory/memory.usage_in_bytes 
708075520
```

We can see that RSS size of python process is pretty low = 65Mb
But metric `memory.usage_in_bytes` is high = 675Mb

I did a little research
and it seems kubernetes take into account not only RSS memory but also I/O buffer(s).
For example if process entensivly use I/O, the buffers start to grow 
and container can also be killed by OOM.

But it's only my assumption we need more proofs of such bahaviour

**Comment by grubberr** [comment]
DataDog "Memory Usage by Pod" is incorrect 
----------------------------------------------

### Pod configuration:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell-mem-test-7
  namespace: default
spec:
  containers:
  - name: ubuntu-shell-mem-test-7-ctr
    image: ubuntu
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "500Mi"
    command: ["bash"]
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
```

### Python script:

```python3
#!/usr/bin/env python3

import time
import string
import random

with open("file.data", "w") as fp:
    for _ in range(500000):
        buff = "".join(random.choices(string.ascii_lowercase, k=1024))
        fp.write(buff)
    print("Done")
    time.sleep(60000)
```

After running python script and waiting when it finish writing to file.

### Memory usage by `kubectl top`
```
kubectl top pod ubuntu-shell-mem-test-7
NAME                      CPU(cores)   MEMORY(bytes)   
ubuntu-shell-mem-test-7   0m           36Mi  
```

### Memory usage by DataDog "Memory Usage by Pod" metric

<img width="1100" alt="Screenshot 2022-10-22 at 12 56 15" src="https://user-images.githubusercontent.com/195743/197333192-94189546-47ec-4b16-8dab-da920358d377.png">


### Resume:

We have a k8s pod with a 500Mb limit, we run the python script which intensively writes to file.
Python script almost does not consume RSS memory but because of intensively writing to file, system I/O cache buffers start to grow.
Usually, I/O buffer(s) is not taken into account by memory stats tools because I/O buffer(s) can consume all free memory on a machine and can be freed if more RSS memory is needed by processes.

If we run `kubectl top` we see  `36Mb` - it looks reasonable.

But if we go to DataDog dashboard we see that Pod started to consume all available memory `500Mb`
which in my opinion is not correct information.

**Comment by JWCook** [comment]
> moving over to `requests-cache` seems like a HUGE win!
> 
> * ~ 75% memory saving
> * ~ 2x faster (21min -> 12min)

Hi, requests-cache maintainer here, this made my day.

There may be some more room for optimizing the cache for your use case, depending on which resources are most important to you (memory, CPU time, I/O, or disk storage). For example, on the SQLite end, [memory-mapped I/O](https://www.sqlite.org/mmap.html) and other [pragma settings](https://www.sqlite.org/pragma.html) would be worth experimenting with. On the python end, a custom serializer could reduce on-disk cache size in exchange for slightly more CPU usage, or possibly other tradeoffs that would mainly depend on your access patterns.

If you need help or have any feature requests, you're more than welcome to start an issue or discussion on the [requests-cache repo](https://github.com/requests-cache/requests-cache).

**Comment by evantahler** [comment]
@grubberr do you want to try out these suggestions, or should we move that to the backlog?

**Comment by artem1205** [comment]
@evantahler, @grubberr ,

FYI, I've rerun the script on kubernetes, and I can see that Datadog shows us `memory_usage` which is not the right metric, but not the one we expect.
It will be better for us to monitor the memory as on latest screen (real one).

![IMAGE 2023-02-17 19:15:15](https://user-images.githubusercontent.com/36314070/219745731-60c87ad4-42e1-4813-8ca6-1633fc395179.jpg)



![IMAGE 2023-02-17 19:15:21](https://user-images.githubusercontent.com/36314070/219745763-d0bc47aa-7879-42f8-b024-44fa02193e0a.jpg)


![IMAGE 2023-02-17 19:16:15](https://user-images.githubusercontent.com/36314070/219746153-1d2d4118-a366-499f-b865-109db175e111.jpg)

![IMAGE 2023-02-17 19:16:21](https://user-images.githubusercontent.com/36314070/219746207-f31f786f-33b9-49e9-a06c-dd1f207a3d7c.jpg)
