### ISSUE TITLE
Stream testing side panel MVP

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17917]
## Tell us about the problem you're trying to solve
As described in the [Tech Spec](https://docs.google.com/document/d/11HrieUnA7oa6YsDhOVZpAVkOoZt2RWQQWJLPf7xQodY/edit#heading=h.gk6ds4twspkk), the Connector Builder's testing side-panel needs to contain a display for the stream's URL, a button to initiate a test, and a panel displaying the results of the test read.

## Describe the solution you’d like
Developing against a mocked connector-builder-server API (since that is still to-be-developed), implement the side-panel with a button that submits a request containing the YAML configuration, a "config" JSON blob (with the user inputs as defined by the connector spec, e.g. API key), and a stream name to the server, then displays the results and the HTTP requests/responses in the tab views.

Since the first version of this server will just fetch all pages and slices for the stream, this testing panel should allow the user to click through each page in each slice, which will update the content in those tabs.

## Acceptance Criteria
- Users can submit read requests for a specific stream in their connector
- Users can provide a json blob with the config values to be used in the read command
- Results and raw HTTP requests/responses for each page are displayed upon successful response from the server

**Comment by sherifnada** [comment]
blocked on code review from Tim who is currently on PTO
