### ISSUE TITLE
New connection streams table design pass

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17937]
Update the connection streams table design to match the updated design [seen in the prototype](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=857%3A24319&node-id=865%3A52984&viewport=124%2C-519%2C0.25&scaling=min-zoom&starting-point-node-id=865%3A52984&show-proto-sidebar=1)

All the foundational work should be done in #17823. This is to match the table row design to match what's in Figma.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
@edmundito should this work include implementing tooltips for fields within the row as well, or is that part of a different Issue?

**Comment by tealjulia** [comment]
Items remaining after #18908 : 
- Table header alignment (both the `Source --> Destination` header and the header with column titles)
- Icon sizing within the `Source --> Destination` heading.  The sizing matches the Figma, but disparate sizing with the icon files themselves make many of them appear skewed or too small to recognize as is.
