### ISSUE TITLE
Add E2E tests for auto-detect schema changes frontend

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#17936]
Blocked by:
- [x] #19878

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
adding a note to include a test case that covers [this OC issue](https://github.com/airbytehq/oncall/issues/789) when a schema is refreshed.

**Comment by tealjulia** [comment]
adding another note to include the field added in #19734
