### ISSUE TITLE
Enable access to Stripe customer portal for paying customers

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#17948]
Stripe has a customer portal that allows users to easily access their transaction history and manage the credit card on file.  This should be accessible within the UI itself.

This allows for Cloud customers to easily access and understand their payments to Airbyte over time and removes the friction of needing to reach out to the Finance team to manually pull this information each time. 

We would only want to allow for users to be able to do these functions: 
- Read & edit payment information
- See history of receipts, invoices, and transactions
- Read & edit customer information (billing details like address)

Any functions related to editing subscriptions should not be allowed (which is configurable in Stripe itself)

Example of what it looks like:
<img width="812" alt="Screen Shot 2022-10-13 at 9 19 14 AM" src="https://user-images.githubusercontent.com/38087517/195622456-c1506bb4-ecdd-45cd-9627-5f2000b3f7c0.png">

**Comment by nataliekwong** [comment]
@tealjulia I'd like to close this out but am having trouble finding the PR related to the addition of the portal to the billing page. Could you help share it here just so I can trace back to it later on? Thank you!

**Comment by tealjulia** [comment]
PR: https://github.com/airbytehq/airbyte-platform-internal/pull/5241
Duplicate issue: https://github.com/airbytehq/airbyte/issues/23695

**Comment by nataliekwong** [comment]
Thank you!!
