### ISSUE TITLE
Migrate Table UI component to react-table v8

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17941]
The Table component we're having has pretty broken types at the moment. It does not know about any `cell.value` type (they are all `any`), also there are a lot of generic types from `react-table` used which never gets a generic parameter passed in and defaulting to `any`.

The types of this component should get a complete cleanup, since it's at the moment very dangerous to change anything around it, since the types are not giving much type-safteyness.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
@tealjulia @edmundito @dizel852  is the work we're doing on the new Connection table handling this topic?

**Comment by edmundito** [comment]
@andyjih This is for the standard table component we use in other pages:
https://63053d1047904393cf8d8faa-juyiyqrszv.chromatic.com/?path=/story/ui-table--primary

**Comment by edmundito** [comment]
Work on new react-table v8 was started on #19219
