### ISSUE TITLE
After import UI needs to update segment tracking

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1797]
## Tell us about the problem you're trying to solve
* after data is imported in the admin configuration, the customer id will be different than it was at start up. 

## Describe the solution you’d like
* the UI needs to do 2 things: 1. fetch the new customer id from the API and run segment `identify` again. 2. segment `alias` so that the newly imported id takes over for the id that was the previously. (old id is child, newly imported id is the primary).

## Context
This is the same task as we did on the API but for the UI. [API PR](https://github.com/airbytehq/airbyte/pull/1791).

**Comment by Jamakase** [comment]
Discussed in chat: nothing needs to be done on the Frontend side for this task.

After the import of config, we reload the page on frontend to invalidate caches, as a result, all new data will be also populated during those process and `identify` will be called with new id.
