### ISSUE TITLE
Show descriptions of oneOf field choices in connector setup form

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#17975]
## Tell us about the problem you're trying to solve
As a result of [this OC issue](https://github.com/airbytehq/oncall/issues/740), it was discovered that for `oneOf` fields in a connector spec, we currently only display the description of the `oneOf` field in the connector form, but don't display descriptions of the actual choices themselves anywhere.

For example, the Replication Method field in the Postgres source spec has the following (simplified) structure:
```
"replication_method": {
  "type": "object",
  "title": "Replication Method",
  "description": "Replication method for extracting data from the database.",
  "oneOf": [
    {
      "title": "Standard",
      "description": "Standard replication requires no setup on the DB side but will not be able to represent deletions incrementally.",
      ...
      }
    },
    {
      "title": "Logical Replication (CDC)",
      "description": "Logical replication uses the Postgres write-ahead log (WAL) to detect inserts, updates, and deletes. This needs to be configured on the source database itself. Only available on Postgres 10 and above. Read the <a href=\"https://docs.airbyte.com/integrations/sources/postgres\">docs</a>.",
      "properties": {
        "plugin": {
          "type": "string",
          "title": "Plugin",
          "description": "A logical decoding plugin installed on the PostgreSQL server. The `pgoutput` plugin is used by default. If the replication table contains a lot of big jsonb values it is recommended to use `wal2json` plugin. Read more about <a href=\"https://docs.airbyte.com/integrations/sources/postgres#step-2-select-a-replication-plugin\">selecting replication plugins</a>.",
          ...
        },
        "replication_slot": {
          "type": "string",
          "title": "Replication Slot",
          "description": "A plugin logical replication slot. Read about <a href=\"https://docs.airbyte.com/integrations/sources/postgres#step-3-create-replication-slot\">replication slots</a>.",
        },
        ...
      }
    }
  ]
}
```

But in the UI, we only have a tooltip showing the `Replication Method`'s description:
<img width="500" alt="Screen Shot 2022-10-13 at 2 24 27 PM" src="https://user-images.githubusercontent.com/22731524/195715330-f55a9278-be14-49cd-95ee-8ccac4d6de05.png">
and tooltips on the _properties_ of the `Logical Replication (CDC)` object:
<img width="500" alt="Screen Shot 2022-10-13 at 2 36 10 PM" src="https://user-images.githubusercontent.com/22731524/195715504-7a79275d-b0c4-40d6-83af-7e9ba3dfe759.png">

We don't currently have any place to show the description of the `Logical Replication (CDC)` choice itself. We should figure out a way to display these oneOf-choice descriptions, as they are helpful for users and could help us avoid OC issues like the one linked above.

## Describe the solution you’d like
For oneOf fields in connector specs, display the descriptions of the oneOf-choices somewhere in the connector form UI.

Ideally, these descriptions would be viewable even before a user actually chooses one of the options in the dropdown, so that they can use the descriptions to help them decide which option to choose. This may require us to put InfoTooltips on each choice in the dropdown menu itself, so that users can hover over them and read descriptions of each choice.

**Feedback from design**: Render out the descriptions in the overall field tooltip, similar to how this connector description is set up
![image](https://user-images.githubusercontent.com/22731524/197843817-1f39c7f3-87fb-4513-adb1-68d469481737.png)

## Acceptance Criteria
- Descriptions of oneOf field choices in connector specs are displayed somewhere in the connector setup form UI

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
