### ISSUE TITLE
Audit database indexes

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#17983]
Some queries to database use `where` clause to filter on certain columns but these columns are not necessary indexed properly.

For example, https://github.com/airbytehq/airbyte-cloud/blob/master/cloud-config/cloud-config-persistence/src/main/java/io/airbyte/cloud/config/persistence/configs/CloudRepository.java#L120-L122 filter by billing_user_id but billing_user_id is not indexed in CLOUD_WORKSPACE table yet.

We should go through CloudRepository.java file and make sure for all conditional queries we have corresponding index in db.

**Comment by pmossman** [comment]
Refining notes:
- Can use [DataDog APM ](https://app.datadoghq.com/apm/services/postgresql/operations/postgresql.query/resources?env=prod&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3A%215%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Cerrors%3Acount%2Chits%3Acount&start=1666109489842&end=1666113089842&paused=false)to investigate postgres queries, copy/paste them into DBeaver, add an `EXPLAIN` to see if there's an index being used
- Scope of this ticket: go through our Cloud API queries and note any missing indices. 
- Follow up ticket(s) for writing the migration to actually add the missing indices once we've found them
