### ISSUE TITLE
Destination Postgres: connection failing after SSL requirement

### ISSUE THREAD

**Issue by valleybay** [airbytehq/airbyte#17989]
## Environment
- **Airbyte version**:  Airbyte Cloud
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: Not applicable
- **Destination Connector and version**: 0.3.26
- **Step where error happened**: Testing connection to destination

## Current Behavior
<img width="845" alt="image" src="https://user-images.githubusercontent.com/10939013/195803783-9bae9e97-109d-4d27-abb7-261a0a673cc1.png">

## Expected Behavior
Destination test should pass.

## Logs
State code: 08001; Message: The connection attempt failed.

## Steps to Reproduce
1. Set up Postgres destination
2. Add verify-ca requirement
3. Connection test fails

## Are you willing to submit a PR?
No experience solving these kinds of issues, but would be open to try.

**Comment by sh4sh** [comment]
Hey there, are you able to connect to this database by other methods? Can you confirm that you have a `hostssl` entry for the user with `clientcert=verify-ca` authentication option in your pg_hba.conf?

**Comment by valleybay** [comment]
Hi @sh4sh! I have tested connecting to this DB with verify-ca using DataGrip, also verified just now.

**Comment by sh4sh** [comment]
@valleybay thanks for checking the db configuration! Can you try pinging the db from the airbyte instance to check whether it is a networking connectivity issue?

**Comment by valleybay** [comment]
@sh4sh we're actually running on your cloud so I'm not able to ping. I can however say that we've already had the source/destination work before (with sync working perfectly fine over a number of weeks). It stopped working when cloud changed from allowing Postgres ```prefer``` to requiring ```verify-ca```.

**Comment by sh4sh** [comment]
Thanks for reporting this and running through some troubleshooting @valleybay! I've tracked down an internal ticket in the team's backlog and have ensured this report is linked to it. If the behaviour changes or you have any other updates please let us know.

**Comment by valleybay** [comment]
Hi @sh4sh! Is there any way for us to find some updates on this on GH or other places? This is a critical feature for us to continue using AirByte cloud. The alternative would be hosting it ourselves, I think.

**Comment by sh4sh** [comment]
Hey @valleybay, currently it appears to be in backlog but I'll check and see if there are any further updates. In general contacting Cloud Support will probably be your best option as they originally reported the issue.

**Comment by grishick** [comment]
Note: w/o any more information the only thing we can do is verify that `verify-ca` mode is working

**Comment by marcosboscariol** [comment]
Hi! Let me try to help, I was having the same issue and this video helped:

https://www.youtube.com/watch?v=gNebJ6c59JY

I start a docker with a postgres image and it worked.

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
