### ISSUE TITLE
Source Google Sheets: slugify column names

### ISSUE THREAD

**Issue by air-rick** [airbytehq/airbyte#18006]
## Tell us about the problem you're trying to solve

Spreadsheets (including Google Sheets) often have non sql compliant column names. Even if columns are technically compliant, they often are cumbersome with spaces and special characters in them.

## Describe the solution you’d like

I'd like to see an option to essentially slugify the column names of the Google Sheet. This can be an option and does not need to be the default behavior.

## Describe the alternative you’ve considered or used

One other option is to do this downstream with sql, but that adds another step to the workflow. Other options include using paid platforms. Fivetran automatically does this with every connector, including Google Sheets. Adding this feature to Airbyte would also help people who are wanting to migrate from Fivetran to Airbyte without requiring them to change their downstream code.

## Are you willing to submit a PR?

Sure, I think I have most of the use cases covered already. I went based off Fivetran's naming standards. Again this makes a migration easy for users rather than reinventing the wheel

https://fivetran.com/docs/getting-started/core-concepts#tableandcolumnnamingruleset

**Comment by grubberr** [comment]
I have added new config option "names_conversion" which if turned on allows to do such name conversions as proposed
