### ISSUE TITLE
Source Amazon Ads: missing metrics `Sponsored Display`

### ISSUE THREAD

**Issue by dfagnan** [airbytehq/airbyte#18025]
## Tell us about the problem you're trying to solve
I noticed that columns seem to be listed explicitly for the Amazon Ads (being new to airbyte I'm unsure if this is common). As a result - key columns needed to correctly calculate ad performance are missing (Example - https://advertising.amazon.com/API/docs/en-us/reporting/v2/metrics#viewAttributedSales14d)

## Describe the solution you’d like
A quick fix would be adding these columns into the data request. A better solution would be requesting all metrics from Amazon (which I assume is supported?).

**Comment by Shishir-rmv** [comment]
I would like to work on this.

**Comment by marcosmarxm** [comment]
Solved by https://github.com/airbytehq/airbyte/pull/25412
