### ISSUE TITLE
Source Smartsheets: add support for metadata data

### ISSUE THREAD

**Issue by jeanluciano** [airbytehq/airbyte#18038]
## Tell us about the problem you're trying to solve

I want to be able to get back my metadata from my smartsheets connectors. On one of the fields for a smartsheets source I want to be able to write a list of columns I want metadata from.

## Describe the solution you’d like

I want to choose whether I want to include metadata from my smartsheets or not.  If a list of metadata fields is specified on the source, then the connector should grab them.

## Describe the alternative you’ve considered or used

Separate data workflow for grabbing the metadata. Using the airbyte cdk.

## Are you willing to submit a PR?

Yes.

**Comment by sh4sh** [comment]
Hey @jeanluciano this sounds great! Let us know if you need any assistance with the PR.

**Comment by masonmenges** [comment]
Hey @sh4sh I've been working with @jeanluciano to build this out would someone be able to take a look at the PR we have opened?

**Comment by sajarin** [comment]
Hey @masonmenges, sorry for the long delay. I will take a look at the PR.

**Comment by masonmenges** [comment]
No worries, Thanks 😄

**Comment by marcosmarxm** [comment]
Solved in https://github.com/airbytehq/airbyte/pull/22382
