### ISSUE TITLE
[low-code connectors] Substream slicer should not yield stream slices if there are no parent records

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#18046]
## Current Behavior
Thread for context: https://airbytehq-team.slack.com/archives/C0450PCSDB2/p1665569372781649

The `SubstreamSlicer` tries to process data even if the parent stream does not produce any records. This leads to it trying to process data with an id=None, which is erroneous.

## Expected Behavior
The substream slicer should not yield a stream_slice if there were no parent records
Note: this might have to be an optional parameter because 
> If a parent slice contains no record, emit a slice with parent_record=None

**Comment by subhamX** [comment]
Hi @girarda, I just noticed that it's marked as completed. Did we make changes, or took some other decision? If possible, could you please refer me to the PR (if any) which fixes it.

**Comment by girarda** [comment]
Hi @subhamX, this is has been released as part of [0.4.1](https://github.com/airbytehq/airbyte/pull/18529/files#diff-e13a40c5efaf769c152f9f1052fccc834a0bb9488dd5887c4cd6798a4b714900L140-L141)
