### ISSUE TITLE
Documentation: Fix the Amplitude Doc Issue Link

### ISSUE THREAD

**Issue by SarojWasti** [airbytehq/airbyte#18056]
### Tell us about the documentation you'd like us to add or update.
The `Create an issue` link in [Amplitude](https://docs.airbyte.com/integrations/sources/amplitude) documentation is redirected to `airbyte/issues` Section instead of `airbyte/issues/new/choose`. I would like to fix that.

### If applicable, add links to the relevant docs that should be updated
- [Amplitude doc: Prerequisites](https://docs.airbyte.com/integrations/sources/amplitude#performance-considerations)

**Comment by Amruta-Ranade** [comment]
@SarojWasti Feel free to open a PR
