### ISSUE TITLE
🪟 🔧 Remove "serviceType" prop from Formik's formValues (<ServiceForm/> refactoring part 2)

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#18051]
## Tell us about the problem you're trying to solve
In [part 1](https://github.com/airbytehq/airbyte/pull/17597) we moved `<ConnectorServiceTypeControl />` outside the Formik(context and components).
But `serviceType` prop is still part of Formik's formValues.

## Describe the solution you’d like
Remove `serviceType` from Formik's formValues and handle it on upper level

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
