### ISSUE TITLE
Update header connector pages with editable name component

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18059]
## Context
Update the Source and Destination header in create and edit mode to reflect the updated design:

https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?node-id=1%3A3

## Acceptance Criteria:
Create mode
* New Source heading is centered, orange
* Name is still set from the card

Edit mode
* Name is editable from the heading instead of the card

The editable name component in edit mode should be the same as the one used for the connection. The component should be made generic in `components/ui` and used in both places.
Note: the generic editable name component should also be used in the connector builder, as it has a similar input for the global and stream views

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
@natalyjazzviolin Just checking if this is something you're still working on?

**Comment by natalyjazzviolin** [comment]
@andyjih I am not, just unassigned myself!

**Comment by tealjulia** [comment]
saw this as i was poking through issues in our project... is this something we should tag connectors team for?

**Comment by andyjih** [comment]
@tealjulia Yes!

**Comment by andyjih** [comment]
@lmossman Pretty sure I put the right team tags for you, but holler if this is incorrect!

**Comment by lmossman** [comment]
Looks right to me, thanks for tagging!

**Comment by flash1293** [comment]
The connection header is being redesigned at the moment, let's wait for this change until we finished the redesign because it's not super simple to change the source/destination page layout like this

**Comment by timroes** [comment]
This issue is outdated by now and not the plan to redesign it as those designs. I'll close this for now, and we should open a new one, once we have new header designs.
