### ISSUE TITLE
Support SSL for database connections (Sources & Destinations)

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1806]
## Tell us about the problem you're trying to solve
My database only support connections via SSL, right now Airbyte connectors don't enable ssl

## Describe the solution you’d like
I would like to either have an automated detection of ssl or an option to configure it.

**Comment by armandfarr** [comment]
Same issue for me. Airbyte is the ideal user-friendly solution for my business' use case, but we require a SSL connection for our MySQL database, so I cannot use it.

**Comment by michel-tricot** [comment]
I added it to our next milestone. I assume that since we are using the jdbc drivers it should already be supported. Might just be a matter surfacing the option.

**Comment by marcosmarxm** [comment]
@cgardens someone is doing this? 
First, only allow SSL connections and in the future enable certificate client/server validation?

**Comment by cgardens** [comment]
no one is currently working on this. it would be great to get it done!

yes, theplan you described sounds good to me!
