### ISSUE TITLE
Dropdown(conditional selector) moves out of the form

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#18061]
<img width="1464" alt="Screenshot at Oct 17 16-45-56" src="https://user-images.githubusercontent.com/20929344/196217976-8c7cda99-9755-4042-9110-3b565fc81fef.png">

## Current Behavior
The dropdown (selector) moves out of the form

## Expected Behavior
The dropdown(selector) should be adjusted to the parent's width

## Steps to Reproduce
1. Open the "Create new destination" page
2. Choose the "End-to-End Testing" connector
3. Increase the width of the doc panel

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
