### ISSUE TITLE
source-google-ads: 🎉  Add fields to the campaign stream

### ISSUE THREAD

**Issue by mutt-santiago-stachuk** [airbytehq/airbyte#18070]
## Tell us about the problem you're trying to solve

- There are some missing key metrics, such as 
- Records in campaigns lack granularity since it doesn't include the "segment.hour" field.

## Describe the solution you’d like

- Add segments.hour field to increase granularity
- Add key metric fields to the stream such as metrics.ctr, metrics.conversions and metrics.conversions_value

## Describe the alternative you’ve considered or used
 
If its not that feasible, we could make a new stream with the new granularity?

## Are you willing to submit a PR?

Yes! number of PR is #18069

**Comment by harshithmullapudi** [comment]
Thanks a lot for bringing it up and also for the contribution. Team will look into it
