### ISSUE TITLE
[Kubernetes/Azure VM] Temporal deployment failling to connect with External Azure Postgres DB

### ISSUE THREAD

**Issue by MarcosWendell** [airbytehq/airbyte#18071]
## Environment
- **Airbyte version**:  0.40.14
- **Deployment**: Azure VM & Kubernetes
- **Step where error happened**: Deploy

## Current Behavior
I was trying to configure an external Azure Postgres DB to Airbyte using k8s, but temporal deployment somehow does not have access to the database. All .env and .secret variables are set, I also allowed all hosts in the Azure Postgres DB firewall. Airbyte-bootloader was able to connect and create main tables, but temporal deployment is having issues creating/accessing temporal and temporal_visibility databases (I have already created them manually, but it didn’t change the log output).

## Expected Behavior
Temporal deployment should be able to connect with DB and configure initial setup.

## Logs

[airbyte-temporal.txt](https://github.com/airbytehq/airbyte/files/9803332/airbyte-temporal.txt)

## Steps to Reproduce
1.Setup variables params according to [docs](https://docs.airbyte.com/operator-guides/configuring-airbyte-db/#connecting-to-an-external-postgres-database)
```
.env
DATABASE_HOST=XXXX.postgres.database.azure.com
DATABASE_PORT=5432
DATABASE_DB=airbyte
DATABASE_URL=jdbc:postgresql://<HOST>:<PORT>/<DB>?user=<USER>&password=<PASSWORD> (according to the other params)
CONFIG_DATABASE_USER=
CONFIG_DATABASE_PASSWORD=
CONFIG_DATABASE_URL=
```
```
.secret
DATABASE_USER=airbyte
DATABASE_PASSWORD=*********
```
2. Configure [kubernetes](https://docs.airbyte.com/deploying-airbyte/on-kubernetes)
3. `kubectl apply -k kube/overlays/stable` then monitor logs from airbyte-temporal pods

**Comment by MarcosWendell** [comment]
Azure PostgreSQL require a SSL certificate that wasn't available for temporal deployment, now that we have configured it, it works.

**Comment by sajarin** [comment]
Thanks for the issue and happy to hear that it works now! Feel free to raise more issues as you encounter them.
