### ISSUE TITLE
Source Zendesk Sell: New Sandbox

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#18078]
We need a Zendesk Sell account for the [Zendesk Sell CRM](https://www.zendesk.com/lp/sales-crm/) service, re: https://github.com/airbytehq/airbyte/pull/17888

It does look like there's a free 14-day trial we can use in the meantime

**Comment by ycherniaiev** [comment]
@sh4sh seems like we have enterprise plan on Zendesk Sell
![image](https://user-images.githubusercontent.com/94798230/197960388-0cc7fb45-05ff-4f9a-8ff5-5ff8c7c6ac80.png)
Use this link
https://app.futuresimple.com/dashboards/main
Und cred from lastpass: Primary Zendesk Dev Account chat, talk, support

**Comment by sh4sh** [comment]
Oh awesome, thanks so much!

**Comment by sh4sh** [comment]
Hmm... password in lastpass doesn't seem to work. Asked for a pw reset link, still haven't received it so I'm gonna reopen until I can confirm access

**Comment by ycherniaiev** [comment]
@sh4sh you can try the other way. Go to LAstpass: Primary Zendesk Dev Account chat, talk, support. After login choose Sell Product: 
![image](https://user-images.githubusercontent.com/94798230/199676916-d3d1716e-58cd-46e8-b40b-7b4588ed9809.png)
