### ISSUE TITLE
Documentation - Airbyte CDK Protocol Architecture link not working

### ISSUE THREAD

**Issue by TanveshT** [airbytehq/airbyte#18102]
### Tell us about the documentation you'd like us to add or update.

This [link](https://docs.airbyte.com/architecture/airbyte-protocol) has been specified within the README files under the Airbyte CDK and no longer working. It is the link for the Airbyte's protocol architecture.

Readme files for which it was noticed:
1. https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/README.md
2. https://github.com/airbytehq/airbyte/tree/master/airbyte-cdk/python/docs/concepts/README.md

There may be more occurrences of the same.

It also might be that the architecture is now supposed to be hidden so an alternative link can be given for the same as following

1. https://docs.airbyte.com/understanding-airbyte/airbyte-protocol/
2. https://docs.airbyte.com/understanding-airbyte/high-level-view/

### If applicable, add links to the relevant docs that should be updated
- [Airbyte Protocol Architecture](https://docs.airbyte.io)

**Comment by sajarin** [comment]
Thanks for the issue @TanveshT, are you willing to make a PR for this?

**Comment by TanveshT** [comment]
sure will make the PR using this [link](https://docs.airbyte.com/understanding-airbyte/high-level-view/)
