### ISSUE TITLE
JIRA connector doesn't pull all issues/tickets

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1811]
## Issue description
reported by @thomas-vl via Slack. 

When a JIRA account has more than 50 projects, it seems like the JIRA source connector does not pull all of them. We expect all projects to be replicated during the sync. 

Here is the public slack thread for more information on the issue: https://airbytehq.slack.com/archives/C01AHCDHCKE/p1611418575016000

## Severity of the bug for you
High -- this is basic functionality that the connector should support

## Airbyte Version
N/A

**Comment by thomas-vl** [comment]
Hi @sherifnada, the update of version 0.1.1 for the Jira connector works for projects I'm now able to retrieve all projects only now I get only 50 Jira Issues. I will look into this today.

**Comment by sherifnada** [comment]
@thomas-vl thanks a lot for looking into this! We're also happy to take any piece of it on if you don't have the time to look into it.

**Comment by vitaliizazmic** [comment]
Jira dev account already has 50+ projects. Syncing returns all of them.

**Comment by sherifnada** [comment]
Guesstimating 4-5hr for fixing

**Comment by thomas-vl** [comment]
@sherifnada @vitaliizazmic 
version 0.1.0 returns all issues but 50 projects.
version 0.1.1 returns all projects but 50 issues.

I don't have time to look into this myself soon.

**Comment by sherifnada** [comment]
@vitaliizazmic we'll need to release a hotfix for this earlier than the full JIRA branch -- can we cherry pick the change needed to fix this problem into master before the rest of the code in #1968 ?
