### ISSUE TITLE
Report affected connectors CI fails if no change applies to connector.

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#18113]
Example: [Report affected connectors](https://github.com/airbytehq/airbyte/actions/runs/3270200437/jobs/5388096941#logs)

If a PR is submitted with no changes to connector there is a Github Action it will fail. It is not a good experience to contributors and reviewers.

**Comment by evantahler** [comment]
‘’’

remotes/origin/master...origin/patch-1 -- airbyte-integrations/
‘’’

these origins and patches could be in the fork, not the main repo

**Comment by pedroslopez** [comment]
Note:

> If a PR is submitted with no changes to connector

From the example in the main post and https://github.com/airbytehq/airbyte/pull/18075, it seems like it's due to the PR coming from a fork, rather than because of there being no changes
