### ISSUE TITLE
Source GitHub: workflow stream only captures workflows recently created or updated

### ISSUE THREAD

**Issue by thomas-gerber** [airbytehq/airbyte#18173]
## Environment
- GitHub community source, version 0.3.6

## Current Behavior
The workflow stream only captures workflows created or modified after `start_date`, which could lead to recent workflow_runs belonging to long-ago created workflows to be captured while their corresponding workflow is not.

## Expected Behavior
Capture all Workflows, i.e. make the stream independent of start_date. This ensures that all captured workflow_runs will have their workflow captured.

## Steps to Reproduce
1. Configure a 0.3.6 GitHub source to capture `faros-ai/faros-community-edition` with start_date of `2022-09-19T00:00:00Z`
2. Sync workflows and workflow_runs
3. Only the [`CLA`](https://github.com/faros-ai/faros-community-edition/actions/workflows/cla.yml) workflow is captured, even though workflow_runs from the PR and Release workflows are captured as well.

**Comment by grubberr** [comment]
`workflows` and `workflow_runs` are two distinct streams. Airbyte source connectors have been implemented in such a way that all streams are fully independent of one another. Each stream starts producing records from the `start_date` parameter onward.

However, in cases where the `workflow_runs` stream refers to objects from the `workflows` stream that were created prior to the specified `start_date`, it is possible to decrease the `start_date` parameter to fetch all necessary objects from the `workflows` stream.

**Comment by lazebnyi** [comment]
@grubberr It appears that the parent stream for `workflow_runs` is not functioning correctly. We require additional logic to synchronize all `workflow_runs` starting from the specified `start_date`.

**Comment by artem1205** [comment]
@thomas-gerber, this is an expected behaviour for this connector, `start_date` is applied for all streams. As a workaround you can create another connection with earlier `start_date` and use it for this stream.
