### ISSUE TITLE
Helm chart update triggers connector update

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#18178]
## Environment
- **Airbyte version**:  0.40.6
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: 
- **Source Connector and version**: source-mssql:0.4.20
- **Step where error happened**: Updating helm chart

## Current Behavior
Every time the user does a new helm release, for instance upping the helm chart version from one version to another (happend from 0.40.24 to 0.40.27) the MSSQL destination updates to the latest version if manually set to a different version before the update.

Reference:
https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1666205113391589?thread_ts=1665994683.268019&cid=C021JANJ6TY

## Expected Behavior
The connector version persists after helm chart update.

## Steps to Reproduce
1. Set connector version to a previous (not latest) version
2. Update helm chart
3. See that the connector was updated to latest

**Comment by ramonvermeulen** [comment]
Had this 2 times after upgrading to a newer helm chart version, felt a bit like the change of the MSSQL source version wasn't committed towards the airbyte database yet.

**Comment by andyjih** [comment]
@supertopher Tagging you in case your team might be able to look into this topic

**Comment by evantahler** [comment]
Re-assigning to prod-end.  Connector ops doesn't know anything about helm charts 😅

**Comment by ramonvermeulen** [comment]
> Since we no longer manage helm charts in the same repository as connectors, this seems like it's no longer an issue. @ramonvermeulen can you please verify this is the case?

Yes, I think this can be closed.

**Comment by cpdeethree** [comment]
Great, thanks @ramonvermeulen !
