### ISSUE TITLE
Create new dropdowns components for new connection new streams table

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18186]
Create a new dropdown style to be used in the new connection streams table
<img width="540" alt="Screen Shot 2022-10-20 at 15 07 22" src="https://user-images.githubusercontent.com/168664/197036256-bda4fc64-5913-4799-9926-f3fdbe502f33.png">

Figma:
https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=2060%3A47239

There are 3 types in the design:

* Default
* Info
* Input 

Please ignore the `Input` type because it is not used in the design.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
