### ISSUE TITLE
Bulk Edit Panel for new connection streams table

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18188]
Update Bulk Edit Panel to match the design in Figma:

![Screen Shot 2022-10-19 at 17.02.57.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/4200d2c0-3456-42b2-bfcc-e396a464758d)

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=857%3A24319&node-id=865%3A53840&viewport=124%2C-519%2C0.25&scaling=min-zoom&starting-point-node-id=865%3A52984

When the Bulk Edit Panel is open, the connection actions (save, cancel should be hidden)

All components should work as expected, should also add testing for the component.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by salima-airbyte** [comment]
@edmundito please close the loop with @Upmitt in regards to the sync drop down. Thanks!
