### ISSUE TITLE
Get normalization image from the connector definition file

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#18232]
Get normalization image from the connector definition file and read the information from both the definition file and the spec and add logs if have difference.

**Comment by evantahler** [comment]
Can you please link the PR that's related to this story?

**Comment by pedroslopez** [comment]
@andriikorotkov Is this a duplicate of https://github.com/airbytehq/airbyte/issues/18235 ?

**Comment by andriikorotkov** [comment]
@pedroslopez, yes, I added a description to this task, and closed the one you specified.
