### ISSUE TITLE
User won't get "Unsaved changes" modal after moving to another page if testing connector has failed

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#18246]
## Environment
- **Airbyte version**:  0.40.15
- **OS Version / Instance**: all
- **Deployment**: all
- **Step where error happened**: Source / Create new source / Set up source

## Steps to repro:
1. Go to the "Sources" tab
2. Click the "New source" button
3. Choose "Poke API" in the dropdown
4. Fill in the `Pokemon Name` field with a random string
5. Click the "Set up source" button  - Testing connector should fail
6. On the left sidebar click on the "Destinations" tab

## Current Behavior
The "Destinations" page is opened

## Expected Behavior
The "Unsaved changes" modal appears

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
