### ISSUE TITLE
Update new connection streams table dropdowns

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18243]
New look for the sync mode:
![Screen Shot 2022-11-09 at 16 54 28](https://user-images.githubusercontent.com/168664/200949959-b18aa213-eb1f-4b81-9e4d-431312d8381d.png)

When small, should truncate the text:
![Screen Shot 2022-11-09 at 16 54 57](https://user-images.githubusercontent.com/168664/200950048-4bd31872-8da0-4ad2-a761-7ef83feb69a3.png)

"Disabled" mode used for bulk edit mode:
![Screen Shot 2022-11-09 at 16 55 24](https://user-images.githubusercontent.com/168664/200950112-c75aea5b-f0b9-42b2-b0f6-0ae7806757b1.png)

Figma:
https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=2060%3A47239

Bulk edit:
https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=2732%3A60474

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
@andyjih one tricky part is what happens when you change a source sync mode that is incompatible with the currently selected destination, or vice versa. Can we come up with some rules on how this should work?

**Comment by colesnodgrass** [comment]
Discussed in grooming session on 20221026, follow-ups:
- [ ] @edmundito to update this issue as he identified it as needing to be revisited

**Comment by edmundito** [comment]
Some of this work has been done in #18627, the part that is missing is to finalize the design

**Comment by tealjulia** [comment]
I've addressed this as part of #18908, aside from the color variations which will come when we incorporate the diff, I believe.
Were there other pieces beyond implementing the new SyncModeSelect dropdown?

**Comment by tealjulia** [comment]
Relevant: https://github.com/airbytehq/airbyte/pull/18908#issuecomment-1308890967
