### ISSUE TITLE
Stream Details Panel in new streams table

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18242]
Update the new streams table fields panel to match the functionality and look of the design. Ensure that it works as expected and add testing around the component.

On the table:
* The checkboxes and the Sync column should be excluded because field sync will be added separately.
* The Primary Key and Cursor columns only appear depending on the sync mode that supports those modes.
* The selection for primary key and cursor is the same as before (checkboxes or radios depending on multi. In the prototype, click on the sync mode in the panel header to see the different configurations)

![Screen Shot 2022-10-20 at 10.47.52.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/9bca453d-5ad5-4397-925c-1675ae0fae6a)

Figma:
https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=972%3A36208&node-id=972%3A36212&viewport=446%2C338%2C0.09&scaling=min-zoom&starting-point-node-id=972%3A36212

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
