### ISSUE TITLE
🐛 Remove Microsoft Dynamics GP doc: connector does not exist

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#18249]
### Tell us about the documentation you'd like us to add or update.
The documentation for the [Microsoft Dynamics GP](https://docs.airbyte.com/integrations/sources/microsoft-dynamics-gp/) source connector needs to be removed because the connector does not exist!

**Comment by marcosmarxm** [comment]
Users can sync data to Microsoft Dynnamics GP using a database backend connector.
