### ISSUE TITLE
Investigate python server-side frameworks

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#18259]

**Comment by girarda** [comment]
notes from initial investigation:
* [PR for fast api](https://github.com/airbytehq/airbyte/pull/18410)
* [PR for flask](https://github.com/airbytehq/airbyte/pull/18140)

both frameworks were pretty easy to setup. I'm leaning towards fastapi but either should work. Next step should be to try and generate the python code from the openapi spec

@sherifnada FYI

**Comment by sherifnada** [comment]
One more consideration: the framework should be able to handle a ton of requests at the same time e.g: 1000 concurrent users.

**Comment by sherifnada** [comment]
Retroactively looked up signals for project health here: https://docs.google.com/spreadsheets/d/1iFBVWqIEGVzXngtdrCIEQA0PYrZUNHoSGitCe_SgR04/edit?usp=drivesdk

The TL;DR is we like FastAPI's DX since it enforces strong typing via Pydantic, and its mindshare is on par with django and flask, historically the two largest python frameworks. The risk with Fast is it's maintained mainly by one person whereas Django has had 15 long-term committers (>10 commits in lats year). But it seems unlikely that it will fizzle out given the large mindshare it has.
