### ISSUE TITLE
I would like to be able to run "dev" version of normalization locally w/o changing worker code

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#18278]
Currently, to run a local Airbyte instance with "dev" version of normalization I have to change `NormalizationRunnerFactory::NORMALIZATION_VERSION` and rebuild platform. I would like to avoid this and either set version of normalization via Airbyte UI or via environment variable.

**Comment by evantahler** [comment]
@grishick do you think that https://github.com/airbytehq/airbyte/issues/16671 would solve your need (change things in this file and reboot)?

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/16671
