### ISSUE TITLE
Add search capability for existing sources

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#18276]
On the /new-connection page, the user is prompted to select an existing source or create a new one.

When selecting an existing source, the user is unable to search to find the relevant existing source. They should be able to search similar to the connector type selection. Same applies for the destination. 

<img width="637" alt="Screen Shot 2022-10-20 at 4 09 59 PM" src="https://user-images.githubusercontent.com/38087517/197075999-773b8bda-6309-4438-91c4-442d6413e285.png">

cc @andyjih  @edmundito

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by nataliekwong** [comment]
Edited to tag @edmundito and removed @lmossman as it relates to connections rather than extensibility

**Comment by colesnodgrass** [comment]
Discussed in grooming session on 20221026, follow-ups:
Hoping that @YatsukBogdan1 and team would be able to pick this up.
