### ISSUE TITLE
don't show number of records synced during a sync

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1827]
## Tell us about the problem you're trying to solve
When someone is trying to sync data and the sync takes a non-trivial amount of time (>1 min) it is confusing to see that 0 records have been replicated, and it makes you think that your sync is actually failing. This is actually not failing, we just don't have during-job reporting of metrics, so it's only updated at the end of the successful sync. 

## Describe the solution you’d like
Remove any reference to record count until the sync has succeeded.

**Comment by cgardens** [comment]
this should wait until figure out workflow engine stuff imo.

**Comment by cgardens** [comment]
fair enough. we can just call this don't show records, bytes, time elapsed until at least one attempt for the job has succeeded or failed.
