### ISSUE TITLE
improve styling of oneOf in connector configuration

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1828]
Hubspot for example:
![Screen Cast 2021-01-25 at 11 24 17 AM](https://user-images.githubusercontent.com/120362/105755524-422fce00-5f00-11eb-9652-9127293bd70a.gif)

The selection isn't clearly referring to the fields below. They should contain the fields and it should be obvious that the dropdown is going to change the state of those options below. Also, the name of the dropdown isn't visible at all. In the hubspot case it's  "credentials".

**Comment by cgardens** [comment]
@johnlafleur do you have a suggestion for what this might look like?

**Comment by michel-tricot** [comment]
I wonder if having some sort of indentation on the fields would work.

**Comment by johnlafleur** [comment]
It should just be a toggle:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=19804%3A0

**Comment by michel-tricot** [comment]
I believe the problem is that it isn't clear what fields are associated to the selected option. @jrhizor is that correct?

**Comment by johnlafleur** [comment]
From my tests, the fields below this option depend on which option you take between API key vs Oauth.

**Comment by johnlafleur** [comment]
Just had a discussion with @michel-tricot 
Will iterate on that. The toggle could be a solution for this exact page, as there is no other oneOfs, but it doesn't work for other cases. Will keep you posted.

**Comment by cgardens** [comment]
We have oneOfs in the file source i believe and it has more than 2 options

**Comment by jrhizor** [comment]
This is what I was thinking of for the design:
https://www.w3schools.com/code/tryit.asp?filename=GN3W8QCNIGBS

Something like a field set outline where it has the name of the oneOf field (like creds) and has a dropdown of the different options. When selected, it would change the contents to whatever fields are part of that oneOf. The important things for me are the fact that it would explicitly say "credentials" and that there is a line containing the inputs that are credential-specific.

**Comment by michel-tricot** [comment]
Like it as well!

**Comment by johnlafleur** [comment]
Design suggestion then: 
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=19804%3A915

**Comment by cgardens** [comment]
works for me!
