### ISSUE TITLE
Source Bing Ads: Add other CampaignTypes

### ISSUE THREAD

**Issue by claireviland** [airbytehq/airbyte#18303]
## Tell us about the problem you're trying to solve
The Bing Ads source only pulls search campaigns, however, we'd like to also pull shopping campaigns, as most of our Bing Ads account spend/revenue stems from this campaign type. Not being able to pull other campaign types gives us an incomplete picture of Bing Ads performance.

## Describe the solution you’d like
We'd like our AirByte Bing Ads connector to pull all campaign types, not just search.

## Describe the alternative you’ve considered or used
We've considered using other pipeline platforms like Fivetran or building our own custom solution to push Microsoft Data to BigQuery. But we'd prefer to use AirByte rather than explore these alternatives.

**Comment by natalyjazzviolin** [comment]
Hi @claireviland , we don't currently have a Microsoft Ads source. Did you mean Bing Ads?

**Comment by claireviland** [comment]
Hi @natalyjazzviolin, yeah I meant Bing Ads.

**Comment by claireviland** [comment]
Any update on this? @YowanR @natalyjazzviolin

**Comment by natalyjazzviolin** [comment]
@claireviland the issue has been triaged to the appropriate team and added to their backlog. As this is a feature request, it is not something that will be prioritized at this point. If you have the ability to contribute a PR, please do so!

**Comment by himanshuc3** [comment]
@natalyjazzviolin For confirmation, is this in progress or up for grabs?

**Comment by natalyjazzviolin** [comment]
@himanshuc3 it is up for grabs!

**Comment by himanshuc3** [comment]
It seems that "shopping" is allready present in "campaign_types" for "bing ads source". I'll need to verify if it's working as well locally.

**Comment by himanshuc3** [comment]
It seems that "shopping" is allready present in "campaign_types" for "bing ads source". I'll need to verify if it's working as well locally.

**Comment by himanshuc3** [comment]
@natalyjazzviolin I may need to connect with the developer since the source seems to failing to setup even though correct credentials/tokens are being passed locally. 
I am getting the following error while trying to setup:
```
Server raised fault: 'Invalid client data. Check the SOAP fault details for more information
```
So, I'll put this on hold for now. The documentation definitely needs to be improved in order to guide to get tokens that don't expire for extended periods as well.

**Comment by YowanR** [comment]
Note of this issue: All new streams should ideally support incremental syncs :)

**Comment by YowanR** [comment]
Looks like you're right! Thanks @rach-r 
Closing this as duplicate :)
