### ISSUE TITLE
Destination Snowflake: check does not verify GCS staging behavior

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#18312]
It's totally possible to set up a connector successfully and then get this error in sync:
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
GET https://storage.googleapis.com/storage/v1/b/airbyte-edgao-test?fields=name&projection=full
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "edgao-test@airbyte-edgao-test-proj.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.",
    "reason" : "forbidden"
  } ],
  "message" : "edgao-test@airbyte-edgao-test-proj.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket."
}
```

related questions:
* does S3 staging have this same problem?
* does internal staging have this same problem?
* do other staging destinations (bigquery, redshift) have this same problem?

**Comment by grishick** [comment]
Note from grooming: might need to check that we are trying to write to the region configured in the destination during the sync and during the `CHECK`

**Comment by edgao** [comment]
sample workspace (this is my cloud workspace, feel free to mess around with it) https://cloud.airbyte.io/workspaces/46b4844a-94a3-496f-af53-2050bf4141af/connections/82fccdd4-5699-494e-99ce-58927e25da7a/status#737032::2
