### ISSUE TITLE
Streams disappear when turning them off in the UI

### ISSUE THREAD

**Issue by victorksuper** [airbytehq/airbyte#18318]
## Environment
- **Airbyte version**:  0.40.14
- **OS Version / Instance**: AWS EC2

## Current Behavior
When turning off a stream within a connector via the ui settings, the stream disappears from the replication page

## Expected Behavior
The stream should be greyed out, indicating that it's turned off, but should stay visible in the event that people want to turn it back on

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by natalyjazzviolin** [comment]
Hi @victorksuper, were you previously running on `0.40.12`? If so, @tealjulia would be able to help you resolve the issue!

**Comment by victorksuper** [comment]
Hello!
Sorry for the delay,
Yes, I believe we were using `0.40.12` but we switched to `0.40.14` before I ran into this issue

**Comment by andyjih** [comment]
I believe this issue should be resolved, but do please re-open this issue if you're still encountering the issue! And perhaps we're misunderstanding what you're seeing. Scrubbed screenshots would be super helpful if you're able to share them. Thanks!
