### ISSUE TITLE
Osano logs infinite messages in browser console

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#18321]
In the browser console, with verbose logging enabled, the following debug message is logged in a seemingly infinite loop:

```Cookie blocked by Osano: _dd_s```

![image](https://user-images.githubusercontent.com/7550957/197287542-8215268b-574f-44c5-89fb-3e4395deb59f.png)

The source of the log call is here: https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/utils/dataPrivacy.ts#L71-L73

User impact is likely very low, if at all noticeable. But this message should not be repeatedly logged!

Slack thread: https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1666376312806899

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by josephkmh** [comment]
My suspicion is that datadog is repeatedly trying to set a cookie `_dd_s`, failing to do so, and retrying. I tried testing locally, but ran into issues getting datadog and osano to run together like they do in prod. Maybe @edmundito can provide some tips about initializing datadog RUM locally?

**Comment by timroes** [comment]
@letiescanciano could you enable this cookie as essential in Osano while I'm out? Datadog is used for crash analytics and we can classify it such as essential same as we did sentry.

**Comment by letiescanciano** [comment]
Done! Sorry I didn't create an issue, I just solved it yesterday!

**Comment by letiescanciano** [comment]
Done! Sorry I didn't create an issue, I just solved it yesterday!
