### ISSUE TITLE
Duplicate logic for PostgresSourceStrictEncrypt in postgres-source module

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#18361]
Due to future connector adaptability based on deployment mode PostgresSourceStrictEncrypt.java and source-postgres-strict-encrypt module will be removed in future in favour of source-postgres module

Therefore, it is necessary to duplicate
PostgresSourceStrictEncrypt.java from the source-postgres-strict-encrypt module to
PostgresSourceStrictEncrypt.java in the source-postgres module.

Acceptance criteria:

1. Postgres Source tests should pass
2. Postgres Source Strict Encrypt tests should pass
3. AlloyDb tests should pass

**Comment by bleonard** [comment]
I assume @evantahler @tuliren and team will take of this one.

**Comment by evantahler** [comment]
We have a goal (https://github.com/airbytehq/airbyte/issues/16676) of removing strict-encrypt entirely in favor of a single container which can have it's spec mutated to require some options in cloud

**Comment by VitaliiMaltsev** [comment]
this issue is currently related mostly to AlloyDB strict encrypt, cause it's an instance of PostgresSourceStrictEncrypt(from postgres-source module). So if PostgresSourceStrictEncrypt allows currently unecrypted traffic AlloyDBStrictEncrypt allows as well what is incorrect
