### ISSUE TITLE
Source BambooHR: History support for inactive employees 

### ISSUE THREAD

**Issue by KrasowskiMichal** [airbytehq/airbyte#18373]
## Tell us about the problem you're trying to solve
We are currently using Airbyte connector to use your data for reporting purposes. (link: https://docs.airbyte.com/integrations/sources/bamboo-hr/) 
Unfortunately, when the employees are turned inactive we are no longer able to see their properties (like Supervisor).
Currently, when the employee turns inactive we can see its attributes “disappearing” from the data source. (that makes historical analysis difficult) . 

## Describe the solution you’d like
We are wondering if there is a way to distinguish inactive employees based on a flag that is available in the connector or API or setting a record validity dates.
Is there any flag to be set (instead of this disappearing behaviour or on top of it) that would 100% differentiate inactive employees and report using their parameters after deactivation?

## A clear and concise description of what you want to see happen, or the change you would like to see
I would like to get the response:
- is solution technically feasible only on Airbyte connector perspective
- if yes, what is complexity/effort?
- are there any chances that anybody would have time to do it in next months?

## Describe the alternative you’ve considered or used
We are currently setting the reporting required fields to "inactive" group manually on the warehouse model level.
Alternative, a history record keeping could be implemented on the warehouse level.

## Additional context
We wrote, to BambooHR, they told us this is a third party connector, that they do not support.
"I took a look and this integration between BambooHR and Airbyte looks to be a custom integration. Because it is custom, I do not have access to the details of the integration. I recommend reaching out to Airbyte to see what they are willing to do with this connection, as it will be something that they control."

## Are you willing to submit a PR?
Well, if you would highlight in technical terms how to implement such a change, we could consider implementation with our own, limited programming skills/resources.

**Comment by sh4sh** [comment]
It looks like this information should be provided by the `status` field: https://documentation.bamboohr.com/docs/list-of-field-names

@KrasowskiMichal the connector's config has a `custom_reports_include_default_fields` for including these default fields. Can you verify if that setting is enabled and working for you when you're setting up the source? 

Alternately, if you don't want to enable all default fields, you should be able to add `status` in `custom_reports_fields` to get it to sync.

![Screen Shot 2022-10-26 at 10 08 11 AM](https://user-images.githubusercontent.com/6833405/198048511-d969da3a-8dcd-49dd-809c-ffd409a537c2.png)

**Comment by sh4sh** [comment]
Hey @KrasowskiMichal were you able to check this?

**Comment by KrasowskiMichal** [comment]
Hi @sh4sh ,
Yes we were able to solve this by using "custom report". What was needed were a few extra fields to become visible for a service account used in this integration.
Sorry for a late reply and thank you for your indication how to solve a problem.

Thanks,
