### ISSUE TITLE
Microsoft Teams source connector flaky tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1839]
## Expected Behavior
I expect the Microsoft teams source connector CI to consistently succeed. 

## Current Behavior
Seems to be flaky, ~60% success rate: https://github.com/airbytehq/airbyte/runs/1766246384

## Acceptance Criteria
1. Understand where the flakiness is coming from and implement a fix for it

**Comment by vitaliizazmic** [comment]
The estimate time to complete this task is 5h
