### ISSUE TITLE
Destination JDBC: rename tables instead of copying on the first load

### ISSUE THREAD

**Issue by marcelopio** [airbytehq/airbyte#18399]
## Tell us about the problem you're trying to solve
Big tables when the destination is a JDBC destination take a long time to be moved from the tmp table to the definitive _raw table

## Describe the solution you’d like
Instead of creating the table first, and then executing: 
https://github.com/airbytehq/airbyte/blob/25292b7891ab6f0b17da8204a4b811dd98d3cd04/airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java#L90-L92

For the first load we could just rename the tables, using the destination rename function, which would take far less time to do. Incremental loads from there on can use the current aproach

## Describe the alternative you’ve considered or used
Continue with what we have today

## Are you willing to submit a PR?
Maybe, I just need to discuss a solution on how to do that

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/19612
