### ISSUE TITLE
Issues connecting to Azure Synapse

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#18408]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#2439](https://airbyte7538.zendesk.com/agent/tickets/2439)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Is this your first time deploying Airbyte?: Yes</li>
<li style="padding-bottom: 10px">OS Version / Instance: Ubuntu</li>
<li style="padding-bottom: 10px">Memory / Disk:  8Gb / 100Gb</li>
<li style="padding-bottom: 10px">Deployment:  Docker</li>
<li style="padding-bottom: 10px">Airbyte Version: 0.40.4</li>
<li style="padding-bottom: 10px">Source name/version:</li>
<li style="padding-bottom: 10px">Destination name/version: MS SQL Server</li>
<li style="padding-bottom: 10px">Step: Setting destination.</li>
<li style="padding-bottom: 10px">Description: Hi, I’m triying to set Azure Synapse as destination but I got</li>
</ul>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px">
<p style="margin-bottom: 0; margin-top: 0; padding: 0" dir="auto">Could not connect with provided configuration. Enforced unique constraints are not supported. To create an unenforced unique constraint you must include the NOT ENFORCED syntax as part of your statement.</p>
</blockquote>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/6/6b4a905fdb26987e0c1640847764c9cf5c827e59.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/6/6b4a905fdb26987e0c1640847764c9cf5c827e59.png" alt="image" width="auto" height="auto" style="max-width: 100%"><div style="display: none">
<span>image</span><span>949×346 13.1 KB</span>
</div></a></div><p dir="auto"></p> 

[<a href="https://discuss.airbyte.io/t/issues-connecting-to-azure-synapse/2720/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-26 at 22:02:*

<blockquote><div class="zd-comment" dir="auto">Hello there! You are receiving this message because none of your fellow community members has stepped in to respond to your topic post. (If you are a community member and you are reading this response, feel free to jump in if you have the answer!) As a result, the Community Assistance Team has been made aware of this topic and will be investigating and responding as quickly as possible.<br>Some important considerations that will help your to get your issue solved faster:<br>* It is best to use our topic creation template; if you haven’t yet, we recommend posting a followup with the requested information. With that information the team will be able to more quickly search for similar issues with connectors and the platform and troubleshoot more quickly your specific question or problem. <br>* Make sure to upload the complete log file; a common investigation roadblock is that sometimes the error for the issue happens well before the problem is surfaced to the user, and so having the tail of the log is less useful than having the whole log to scan through. <br>* Be as descriptive and specific as possible; when investigating it is extremely valuable to know what steps were taken to encounter the issue, what version of connector / platform / Java / Python / docker / k8s was used, etc. The more context supplied, the quicker the investigation can start on your topic and the faster we can drive towards an answer. <br>* We in the Community Assistance Team are glad you’ve made yourself part of our community, and we’ll do our best to answer your questions and resolve the problems as quickly as possible. Expect to hear from a specific team member as soon as possible.<br><br>Thank you for your time and attention.<br>Best,<br>The Community Assistance Team</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-09-29 at 18:31:*

<blockquote><div class="zd-comment" dir="auto">Boggdan the file uploaded doesn't have any error. This is happening in creating a new Destination? Are you able to follow the request in the Network tab?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-21 at 11:38:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi, I think this is primarily because Azure Synapse do not support enforced primary key</p>
<div style="border: 5px solid #e9e9e9; margin-bottom: 10px; padding: 12px 25px 12px 12px">
  <div>

      <a href="https://github.com/airbytehq/airbyte/blob/7fcadf433c9dcecfbc86b69ca9ccc77ad84b32ab/airbyte-integrations/connectors/destination-mssql/src/main/java/io/airbyte/integrations/destination/mssql/SqlServerOperations.java#L33" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">github.com</a>
  </div>

  <div style="clear: both">
    <h4 style="color: #222; font-size: 1.17em; margin: 10px 0" dir="auto"><a href="https://github.com/airbytehq/airbyte/blob/7fcadf433c9dcecfbc86b69ca9ccc77ad84b32ab/airbyte-integrations/connectors/destination-mssql/src/main/java/io/airbyte/integrations/destination/mssql/SqlServerOperations.java#L33" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">airbytehq/airbyte/blob/7fcadf433c9dcecfbc86b69ca9ccc77ad84b32ab/airbyte-integrations/connectors/destination-mssql/src/main/java/io/airbyte/integrations/destination/mssql/SqlServerOperations.java#L33</a></h4>



    <pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px; white-space: normal">
      <ol start="23" style="counter-reset: li-counter 22" dir="auto">
          <li style="padding-bottom: 10px; white-space: pre">      schemaName);</li>
          <li style="padding-bottom: 10px; white-space: pre">  database.execute(query);</li>
          <li style="padding-bottom: 10px; white-space: pre">}</li>
          <li style="padding-bottom: 10px; white-space: pre">
          </li>
<li style="padding-bottom: 10px; white-space: pre">@Override</li>
          <li style="padding-bottom: 10px; white-space: pre">public void createTableIfNotExists(final JdbcDatabase database, final String schemaName, final String tableName) throws Exception {</li>
          <li style="padding-bottom: 10px; white-space: pre">  database.execute(createTableQuery(database, schemaName, tableName));</li>
          <li style="padding-bottom: 10px; white-space: pre">}</li>
          <li style="padding-bottom: 10px; white-space: pre">
          </li>
<li style="padding-bottom: 10px; white-space: pre">@Override</li>
          <li style="padding-bottom: 10px; white-space: pre">public String createTableQuery(final JdbcDatabase database, final String schemaName, final String tableName) {</li>
          <li style="padding-bottom: 10px; white-space: pre">  return String.format(</li>
          <li style="padding-bottom: 10px; white-space: pre">      "IF NOT EXISTS (SELECT * FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id "</li>
          <li style="padding-bottom: 10px; white-space: pre">          + "WHERE s.name = '%s' AND t.name = '%s') "</li>
          <li style="padding-bottom: 10px; white-space: pre">          + "CREATE TABLE %s.%s ( \n"</li>
          <li style="padding-bottom: 10px; white-space: pre">          + "%s VARCHAR(64) PRIMARY KEY,\n"</li>
          <li style="padding-bottom: 10px; white-space: pre">          + "%s NVARCHAR(MAX),\n" // Microsoft SQL Server specific: NVARCHAR can store Unicode meanwhile VARCHAR - not</li>
          <li style="padding-bottom: 10px; white-space: pre">          + "%s DATETIMEOFFSET(7) DEFAULT SYSDATETIMEOFFSET()\n"</li>
          <li style="padding-bottom: 10px; white-space: pre">          + ");\n",</li>
          <li style="padding-bottom: 10px; white-space: pre">      schemaName, tableName, schemaName, tableName, JavaBaseConstants.COLUMN_NAME_AB_ID, JavaBaseConstants.COLUMN_NAME_DATA,</li>
          <li style="padding-bottom: 10px; white-space: pre">      JavaBaseConstants.COLUMN_NAME_EMITTED_AT);</li>
      </ol>
    </code></pre>



  </div>

  <div style="color: #919191">
    
    
  </div>

  <div style="clear: both"></div>
</div>

<p dir="auto">It is allowed to use PRIMARY KEY NOT ENFORCED</p> 

 [<a href="https://discuss.airbyte.io/t/issues-connecting-to-azure-synapse/2720/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-10-24 at 23:20:*

<blockquote><div class="zd-comment" dir="auto">Thanks for informing this chte, I created the issue <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/18408">https://github.com/airbytehq/airbyte/issues/18408</a> to solve in the future ths.<br></div></blockquote>

**Comment by grishick** [comment]
@marcosmarxm there is an issue for creating new Azure Synapse connector: https://github.com/airbytehq/airbyte/issues/2149. Please direct comments about Azure Synapse into that issue

**Comment by marcosmarxm** [comment]
Closing because this issue is a duplicate of #2149

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:10:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:13:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:14:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:15:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:16:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:19:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:21:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2023-04-03 at 23:23:*

<blockquote><div class="zd-comment" dir="auto">Closed due to no response from requester.<br></div></blockquote>
