### ISSUE TITLE
Source MsSQL Add SSL support to CDC

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#18419]
MsSQL Source connector currently does not support SSL setup for CDC replication
[docs](https://debezium.io/documentation/reference/stable/connectors/mysql.html#:~:text=database.history.-,producer,-.security.protocol%3DSSL)
We have a similar example already implemented in MySqlCdcProperties.java class

**Comment by prateekmukhedkar** [comment]
Closed with https://github.com/airbytehq/airbyte/issues/30004
