### ISSUE TITLE
Environment name inconsistency leads to State Storage Configuration Failure

### ISSUE THREAD

**Issue by gfeldman** [airbytehq/airbyte#18412]
## Environment
- **Airbyte version**:  0.40.16
- **OS Version / Instance**: kubernetes
- **Deployment**: EKS
- **Step where error happened**: Sync Job

## Current Behavior
The [application yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/resources/application.yml#L49) looks for an environment variable called `STATE_STORAGE_S3_BUCKET_REGION` while the [EnvConfig model](https://github.com/airbytehq/airbyte/blob/182f2c6fba1bdc1050a2e20fb8402c5bf26f0bfb/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L111) looks for a variable called `STATE_STORAGE_S3_REGION`.

## Expected Behavior
Environment variable names should be consistent.

## Steps to Reproduce
1. Deploy airbyte using the standard helm chart
2. Enable the container orchestrator and use s3 state storage
3. Container orchestrator will fail to boot.

## Are you willing to submit a PR?
yes.

**Comment by sajarin** [comment]
Thanks for the issue and the contribution. Hopefully someone on our team will review it and merge the PR.

**Comment by jasonicarter** [comment]
Hi. This is still an issue in 0.40.29

**Comment by cpdeethree** [comment]
Hi, this was recently fixed: https://github.com/airbytehq/airbyte-platform/commit/34ecd83d5ccc769d66c8fdbb06dd442c590f2dfe

Please reopen if you still see the issue
