### ISSUE TITLE
Listview Performance

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#18453]

**Comment by krishnaglick** [comment]
![Screenshot 2023-01-03 at 2 57 15 PM](https://user-images.githubusercontent.com/4967694/210432298-cc512acf-9ab8-4757-8d97-df1597a9d526.png)
![Screenshot 2023-01-03 at 2 57 03 PM](https://user-images.githubusercontent.com/4967694/210432300-3899dab3-bf89-4cf0-9359-c433623a4b9a.png)
![Screenshot 2023-01-03 at 2 56 47 PM](https://user-images.githubusercontent.com/4967694/210432302-f19830f6-965c-4fa0-9cbf-39bb9039e08c.png)
Here's the current Lighthouse scores for the Connections, Sources, and Destinations List Pages. Capturing here so we have a clear diff once all this work is merged.

**Comment by krishnaglick** [comment]
Closing this as the work was completed.
