### ISSUE TITLE
Source Bing Ads - Add CampaignLabels report column in campaign performance report

### ISSUE THREAD

**Issue by achaussende** [airbytehq/airbyte#18476]
## Environment

- **Source Connector and version**: Bing Ads 0.1.16 

## Current Behavior
Bings Ads Reporting API allow to include more columns when getting a `campaign_performance_report`. One that is missing from this list is `CampaignLabels`.

## Expected Behavior
The field `CampaignLabels` is present in the `campaign_performance_report` stream.

## Additional Information
- `CampaignLabels` field is [only available in a campaign performance report](https://learn.microsoft.com/en-us/advertising/guides/report-attributes-performance-statistics?view=bingads-13#attributes)
- The column should be added in the `report_columns` list [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/source.py#L368).
- Update [the stream schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/schemas/campaign_performance_report.json) accordingly by adding this new field

## Are you willing to submit a PR?

Not for now

**Comment by YowanR** [comment]
Note: We expect this stream to be incremental :)

**Comment by trowacat** [comment]
@YowanR I can work on this

**Comment by YowanR** [comment]
Assigned this one to. your, @trowacat! Looking forward to your PR! 🚀
