### ISSUE TITLE
Optimize OrbClient getCreditBalance to avoid lengthy page loads

### ISSUE THREAD

**Issue by cpdeethree** [airbytehq/airbyte#18478]
Duplicated from https://github.com/airbytehq/oncall/issues/885

This ticket is for the longer term fix for the oncall issue, which was resolved by adding credits.

## Affected Workspace Details:  

| Environment | Affected Workspaces | Connection Link | Case/Chat Link | Sentiment | User Data Access | Reporter |
| ---- | ---- | ------------ | --------- | ---------- | ---------- | ---------- |
| cloud/oss | [workspace](https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/settings/account) |  | [chat](https://airbytehq-team.slack.com/archives/C0309PV2WCD/p1666381435275099) | 👍 :ok: 👎 😠 | Y/N (did you ask?!?!) | Alex G |

Alex Gronemeyer (Airbyte)
Hey TCS... I'm having some issues loading Airbyte Cloud today. Is this specific to me and/or our internal workspace? Or potentially a broader issue?
Note: It does eventually load at the end... but I've had this experience a few times today.
Loom video: https://www.loom.com/share/3455ece2c0cf41c2a6f4da4099f41e52
Airbyte Workspace: https://cloud.airbyte.io/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/settings/account

## Current Behavior
Intermittent 502 timeout

## Logs
Logs(https://console.cloud.google.com/logs/query;query=httpRequest.status%3D502%0A;timeRange=2022-10-21T19:07:53.358Z%2F2022-10-21T20:07:53.358Z;cursorTimestamp=2022-10-21T20:07:53.357421Z?project=prod-ab-cloud-proj)

As stated in the slack thread linked above, the root cause appears to be how our billing service handles certain logic:

_Alright, for everyone watching this thread, I just added 100k credits to the internal workspace so that their balance would be positive. It turns out that things only get really bad when a customer carries a negative balance for a very long time, because they keep building up decrements that we search through via paginated API calls. Basically, it takes the page a very long time to find a ledger entry that meets this filter: https://github.com/airbytehq/airbyte-cloud/blob/master/billing/src/main/java/io/airbyte/billing/orb/OrbClientImpl.java#L173_

**Comment by mfsiega-airbyte** [comment]
Alternative - break the credit balance stuff out into a separate API. This would mean that the Orb loading wouldn't block everything.
