### ISSUE TITLE
Source Hubspot: review authentication methods due to upcoming API Key sunset

### ISSUE THREAD

**Issue by roman-yermilov-gl** [airbytehq/airbyte#18484]

**Comment by YowanR** [comment]
Thank you for creating this! One question we had from our customer is "Will changing auth method have any impact on my data? I currently use API keys but I'm worried that changing to a different authentication method, will impact my data. Can you confirm that it will not". 
Let's try to address this question during this exercise as well @roman-yermilov-gl  -- thanks!!

**Comment by roman-yermilov-gl** [comment]
API Key authentication is no longer available as well as Quotes stream. These changes are not backward compatible but they are not related to data/state structure.  A customer should switch authentication method to `Private App` or `OAuth` and that's it.

**Comment by YowanR** [comment]
I see. We should update this in our docs. Can you share the link to Quotes stream getting deprecated, please?

**Comment by roman-yermilov-gl** [comment]
This is link to updated documentation which contains not any `Quotes` stream except mentions in changelog:
https://github.com/airbytehq/airbyte/blob/83891de2193d7b9cda4ff7a1e3e6ead9c9f1d4c0/docs/integrations/sources/hubspot.md

**Comment by Rahulborserb** [comment]
Hi @roman-yermilov-gl , I am trying to setup hubspot source in airbyte OSS. Here I am only getting api key configuration not the oauth. Can you check.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/18594603/199177128-f7ac5d5f-69a9-43ad-af62-760827b6296d.png">

**Comment by lazebnyi** [comment]
Hi @Rahulborserb 
Thanks for your comment!
Could check master version and updated to the last one.

**Comment by bmikaili** [comment]
Private apps does not work at all.

**Comment by YowanR** [comment]
Hi @bmikaili, can you share which type of auth are you using, please? 
cc @roman-yermilov-gl @lazebnyi

**Comment by bmikaili** [comment]
@YowanR It seemed to work again. Looked like an error on hubspot side, after talking with their support.

**Comment by lazebnyi** [comment]
@YowanR Can we close this issue? 

cc @roman-yermilov-gl

**Comment by YowanR** [comment]
Yes, I think we should be good here. Thanks @roman-yermilov-gl and @lazebnyi

**Comment by lazebnyi** [comment]
Will be closed after Nov 28 according to this - https://github.com/airbytehq/airbyte/pull/18546#issuecomment-1320390894
