### ISSUE TITLE
DB sources and destinations: Catch timeout exceptions in check as config error

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#18517]
Seen in many issues, e.g. https://github.com/airbytehq/oncall/issues/900, https://github.com/airbytehq/oncall/issues/854

```
SshTunnel.java
Function: openTunnel
Type: org.apache.sshd.common.SshException

DefaultConnectFuture[ubuntu@ec2-13-246-26-119.af-south-1.compute.amazonaws.com/13.246.26.119:22]: Failed to get operation result within specified timeout: 15000
```

If we get a timeout error, then either:
* our network is bad
* the user's config is bad

In the first case, we probably have bigger problems (and other alerts would trigger). In the latter case, we shouldn't be reporting the issue to sentry. This sort of error should be caught as a config error.

Tagging this as both sources and destinations but might need to split up - iirc there's some shared code somewhere so we might be able to get some extra leverage here.

**Comment by bleonard** [comment]
https://github.com/airbytehq/oncall/issues/720
