### ISSUE TITLE
[google search console] invalid dimensions in custom report should be identified during check instead of discover

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#18528]
## Current Behavior
When a customer specifies an invalid dimension in their custom report, it will currently fail during the `discover` with an invalid key in the map as per: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-search-console/source_google_search_console/streams.py#L329-L342

## Expected Behavior
Since the custom report is defined as a config option on the connector, we can verify the validity of their custom report dimensions during the check instead of during discover. This could be done by invoking the self.get_json_schema() for the `SearchAnalyticsByCustomDimensions` stream as part of the `check_connection()` method whenever a custom report is defined as a config option.

**Comment by grubberr** [comment]
I have improved `custom_reports.dimension` validation
