### ISSUE TITLE
Source GitHub: Use pagination to create incremental stream

### ISSUE THREAD

**Issue by mmmaia** [airbytehq/airbyte#18527]
## Tell us about the problem you're trying to solve

Only 4 streams are pure incremental because the endpoint supports `since`, `sort`, and `direction` parameters.

Other immutable streams, like [Issue events](https://docs.github.com/en/rest/reference/issues#list-issue-events-for-a-repository), could become fully incremental by using pagination parameters.

## Describe the solution you’d like

Use [pagination parameters to traverse](https://docs.github.com/en/rest/guides/traversing-with-pagination) immutable streams and make them pure incremental.

## Are you willing to submit a PR?

Yes.

**Comment by grubberr** [comment]
@mmmaia usually pagination does not help to implement incremental feature.
For incremental feature  we need some filtering params like "startDate", etc

**Comment by mmmaia** [comment]
@grubberr That's also my understanding, but for streams of Events, this could be possible.

Looking [into the code](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/streams.py#L296), Airbyte already stops reading records when the API returns a record that is older than the last record we have stored.

GitHub Event streams don't have sorting parameters because they are always `desc`. So we could use the same logic.

Do you think that changing the `cursor_field` to `updated_at` and adding `is_sorted = "desc"` to `IssueEvents` would work?

**Comment by grubberr** [comment]
I don't see `updated_at` field on stream `IssueEvents`

```
python3 main.py read --config secrets/config.json --catalog catalog.json.issue_events | grep RECORD | jq .record.data.updated_at
null
null
null
null
null
null
null
```

**Comment by grubberr** [comment]
`is_sorted=["asc"|"desc"]` - it's just additional optimization for semi  incremental (not pure incremental)

If stream `IssueEvents` is naturally `is_sorted="desc"`,
yes we can mark this stream as `is_sorted="desc"` to improve semi incremental

**Comment by mmmaia** [comment]
> I don't see `updated_at` field on stream `IssueEvents`

Right! I confused it with the `updated_at` field of the inner `issue` object.

> If stream IssueEvents is naturally is_sorted="desc",
> yes we can mark this stream as is_sorted="desc" to improve semi incremental

Cool. I'll work on a PR

**Comment by mmmaia** [comment]
@grubberr while looking into this I found that `IssueMilestone` has the wrong `sort` field name. I opened a [PR](https://github.com/airbytehq/airbyte/pull/18583) to fix it.

If you review it, I can use the same logic for the other streams.

**Comment by YowanR** [comment]
@sajarin Can you review this?

**Comment by artem1205** [comment]
Closing as not relevant
