### ISSUE TITLE
:bug: Source File Secure: fix SAT tests

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#18541]
Based on this `publish` run: https://github.com/airbytehq/airbyte/actions/runs/3337276955
the SAT is failing, they are also failing locally with the latest sAT container version. 
In order to keep the `source-file-secure` up to date, the SAT tests should be fixed.

**Comment by YowanR** [comment]
@lazebnyi Can you take a look, please?

**Comment by YowanR** [comment]
@lazebnyi Can you take a look, please?

**Comment by lazebnyi** [comment]
fixed in - https://github.com/airbytehq/airbyte/pull/21012
