### ISSUE TITLE
New Destination: Kafka

### ISSUE THREAD

**Issue by michaelandrepearce** [airbytehq/airbyte#1855]
## Tell us about the new integration you’d like to have
It would be great to be able to have kafka as a source and destination 

## Describe the context around this new integration
Integrate the same data pipeline tool with kafka adoption so we have a single tool rather than a mash up of many.

## Describe the alternative you are considering or using
Streamsets, it has kafka connections for source and destination

## Help us understand how to build the best connector for your usecase
If you are a user or community member interested in this connector, help us build the best connector possible by answering the following questions: 
* What volume of data do you anticipate replicating? bytes or number of records estimate is helpful to know.
* What data format would you like to write to the connector? Airbyte natively uses JSON. Is this usable for you? If not, can you help us understand why and what data format you need? 
* Should the connector partition the output data? What partitioning scheme do you need?
* How will you use the data once its written? 
* What is the UX you want for interacting with the connector? What inputs/configuration do you want to give it, and how do you want the output to look like? Should all input Airbyte streams be written to the same place, different places, etc.?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368209363636) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Thanks for sharing! Can you speak to what size of data you're dealing with? Kafka is obviously a distributed system and Airbyte is not (yet). I want to make to figure out if there's value in creating these sources and destinations before we have a distributed data replication solution.

**Comment by jwarlander** [comment]
I can't speak for @michaelandrepearce, but we definitely have a growing variety of Kafka topics with fairly reasonable volumes (anything between a few thousand up to a million messages or so / day).

**Comment by sherifnada** [comment]
@jwarlander @michaelandrepearce could you comment on the UX you would expect here? Some questions:

* How would the kafka destination connector know which topics to write to? Would all messages go to a single topic, or would you want to create a topic per stream, or some other way of multiplexing the output? 
* Which sources would you be interested in using this with? 

Separately, I created #2655 to track creating a Kafka source connector. Feel free to add any relevant context to that one.

**Comment by marcosmarxm** [comment]
bringing info from slack [convo](https://airbytehq.slack.com/archives/C01AHCD885S/p1621536877010800):
> Several millions per day. No partitioning, raw Airbyte JSON messages would be good enough for me. Avro format also would work.
UI should be pretty simple. Topic to publish, secrets and that’s it

**Comment by noah-goodrich** [comment]
* What volume of data do you anticipate replicating? bytes or number of records estimate is helpful to know.
10s of millions of rows a day

* What data format would you like to write to the connector? Airbyte natively uses JSON. Is this usable for you? If not, can you help us understand why and what data format you need?
JSON is fine.

* Should the connector partition the output data? What partitioning scheme do you need?
Not so much partitioning as being able to utilize multiple topics

* How will you use the data once its written?
We would need to connect to Kafka as well and have Airbyte flush data to S3.

* What is the UX you want for interacting with the connector? What inputs/configuration do you want to give it, and how do you want the output to look like? Should all input Airbyte streams be written to the same place, different places, etc.?
One thing for sure would be the ability to point the config to Kinesis as opposed to Kafka.
We should be able to turn on Kafka/Kinesis for a given subset of data.
In this case, the ability to optimize the number of topics being used, but it seems like best practice to identify some sane defaults.
I don't see these as being an either or situation. Looking at what debezium has recently done with Kinesis, it seems like we should be able to have our cake and eat it too.

**Comment by sherifnada** [comment]
@noah-goodrich we're going to begin implementation soon and would love to understand how you would like to utilize multiple topics. Would you like Airbyte to write different streams to different topics (e.g: replicating a `users` table would end up in the `users` topic in kafka)? or would you like some other way of routing data to topics?
