### ISSUE TITLE
Refactor <ConnectorCard /> (<ServiceForm> refactoring part 3) 

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#18553]
## Tell us about the problem you're trying to solve
The next chapter of <ServiceForm /> refactoring series
Previous parts:
[Part 1](https://github.com/airbytehq/airbyte/pull/17597)
[Part 2](https://github.com/airbytehq/airbyte/pull/18168)

## Describe the solution you’d like
- In [Part 2](https://github.com/airbytehq/airbyte/pull/18168) was found that <ConnectorCard /> still needs to be improved, since some of the props are just prop-drilled:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/20929344/198325014-934add5f-8e12-4abf-a143-9fc587d0d89e.png">

- Also, we have implicit props drilling, for example:
```
<ConnectorForm
          {...props}
          .........
          <FormRoot
               {...props}
       
```

On each level of nesting we pull out props we need, and the rest we pass further. That makes it unclear what king of props component actually needs.
_Note:_ This one, probably will be fixed in [PR](https://github.com/airbytehq/airbyte/pull/18229), but I mention it hear to keep it tracked.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/20929344/198328569-66b75570-91c0-4c1e-a891-d010c957f16d.png">

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by sherifnada** [comment]
@flash1293 is this still needed? please reopen if so
