### ISSUE TITLE
Github source connector doesn't seem to work

### ISSUE THREAD

**Issue by dogma0** [airbytehq/airbyte#1856]
## Expected Behavior
*Tell us what should happen.*
When a Github source connector and local csv file destination are set up, there should be data syncing. I'd only set up to sync Github's `commit` object.

## Current Behavior
*Tell us what happens instead of the expected behavior.*
I set frequency to Manual. When launched, despite there are many error logs and warnings, the job reported success and there is no data nor `/tmp/airbyte_local` created.

Error log snippet where the log reports success for the sync:
`2021-01-27 07:32:38 INFO (/tmp/workspace/47/0) LineGobbler(voidCall):69 - 2021-01-27 07:32:37 [32mINFO[m i.a.i.b.FailureTrackingConsumer(close):64 - {} - hasFailed: false.`

## Steps to Reproduce
1. Set up Github for source, CSV for local (path is `/local`); the schema to only include commit, as screenshoted below
2. Run the sync manually

## Severity of the bug for you
Low

## Airbyte Version
Found in the .env file in the root of the project.
```
VERSION=0.14.0-alpha
DATABASE_USER=docker
DATABASE_PASSWORD=docker
DATABASE_DB=airbyte
CONFIG_ROOT=/data
WORKSPACE_ROOT=/tmp/workspace
DATA_DOCKER_MOUNT=airbyte_data
DB_DOCKER_MOUNT=airbyte_db
WORKSPACE_DOCKER_MOUNT=airbyte_workspace
# todo (cgardens) - when we are mount raw directories instead of named volumes, *_DOCKER_MOUNT must
# be the same as *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/578
LOCAL_ROOT=/tmp/airbyte_local
LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
TRACKING_STRATEGY=segment
# todo (cgardens) - hack to handle behavior change in docker compose. *_PARENT directories MUST
# already exist on the host filesystem and MUST be parents of *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/577
HACK_LOCAL_ROOT_PARENT=/tmp
```

## Additional context
*Environment, version, integration...*
- Connection set up:
<img width="1115" alt="Screenshot 2021-01-26 at 11 42 06 PM" src="https://user-images.githubusercontent.com/10555996/105959003-32afa280-6030-11eb-8c51-80983c64568d.png">

- Log file:
[logs-47-0.txt](https://github.com/airbytehq/airbyte/files/5878460/logs-47-0.txt)

**Comment by ChristopheDuong** [comment]
Thanks for the report!

All the warning messages are coming from the singer source that is used underneath because some fields exposed by github API are not being recognized in the catalog but that should be safely ignored i think.

However i do notice this behavior where nothing is being written in the local file at the end...
Even though when I run this command:
`docker run --rm -i -v airbyte_workspace_dev:/data -v /tmp/airbyte_local_dev:/local -w /data/6/0 --network host airbyte/source-github-singer:0.1.7 read --config tap_config.json --catalog catalog.json` 

(where i need to replace the `/data/6/0` by the correct workspace ID, in @dogma0 's case, it would be `/data/47/0`)

I get the following output:

```
{"type": "LOG", "log": {"level": "ERROR", "message": "\tnode_id\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "WARNING Removed paths list: ['author', 'commit.verification', 'committer', 'node_id']\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "WARNING Removed 4 paths during transforms:\n"}}
{"type": "RECORD", "record": {"stream": "commits", "data": {"sha": "51920f229ab220ca1e6bd0be74e43db467cdf24f", "commit": {"author": {"name": "Michel Tricot", "email": "michel@dataline.io", "date": "2020-08-04T18:20:46.000000Z"}, "committer": {"name": "Michel Tricot", "email": "michel@dataline.io", "date": "2020-08-04T18:20:46.000000Z"}, "message": "Add initial project structure + CI", "tree": {"sha": "ce8b1ad916037d1ef1b3483c06722fe57bb34ca9", "url": "https://api.github.com/repos/airbytehq/airbyte/git/trees/ce8b1ad916037d1ef1b3483c06722fe57bb34ca9"}, "url": "https://api.github.com/repos/airbytehq/airbyte/git/commits/51920f229ab220ca1e6bd0be74e43db467cdf24f", "comment_count": 0}, "url": "https://api.github.com/repos/airbytehq/airbyte/commits/51920f229ab220ca1e6bd0be74e43db467cdf24f", "html_url": "https://github.com/airbytehq/airbyte/commit/51920f229ab220ca1e6bd0be74e43db467cdf24f", "comments_url": "https://api.github.com/repos/airbytehq/airbyte/commits/51920f229ab220ca1e6bd0be74e43db467cdf24f/comments", "parents": [{"sha": "dbacb9727d11b6987fb1f17120bdb77b27d55a68", "url": "https://api.github.com/repos/airbytehq/airbyte/commits/dbacb9727d11b6987fb1f17120bdb77b27d55a68", "html_url": "https://github.com/airbytehq/airbyte/commit/dbacb9727d11b6987fb1f17120bdb77b27d55a68"}], "_sdc_repository": "airbytehq/airbyte"}, "emitted_at": 1611739136000}}
{"type": "LOG", "log": {"level": "ERROR", "message": "\tauthor\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "\tcommit.verification\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "\tcommitter\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "\tnode_id\n"}}
```

So I should expect to get some record messages being written but it is not the case... we'll have to look closer into this

**Comment by sherifnada** [comment]
@dogma0 are you able to verify if commits are being written to the destination, and if this is an issue?

**Comment by jrhizor** [comment]
This is likely a duplicate. @sherifnada will take a look.
