### ISSUE TITLE
Docs:Add Restack as a way to deploy Airbyte on kubernetes

### ISSUE THREAD

**Issue by kuberaspeaking** [airbytehq/airbyte#18569]
### Tell us about the documentation you'd like us to add or update.
I will add Restack as a way to deploy Airbyte on your own AWS on kubernetes in the docs. 
@Amruta-Ranade please share the relevant resources. 

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.com/category/deploy-airbyte-open-source)

**Comment by Amruta-Ranade** [comment]
Hey Shruti! Here are some resources:

- [Docs Contributor guide](https://docs.airbyte.com/contributing-to-airbyte/updating-documentation)
- [Google style guide](https://developers.google.com/style) 
- [Good example](https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine)

**Outline:**

- Setup the environment
- Install and launch Airbyte
- Connect to Airbyte
- Troubleshooting

**Some pointers:**
- The important thing to remember is that this is an official Airbyte doc and not a content tutorial
- We're moving away from using screenshots in our docs
