### ISSUE TITLE
Performance: enhance initial snapshot in source postgres 

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#18573]
## Tell us about the problem you're trying to solve
Taking the initial snapshot on source postgres is a lengthy process corresponding to the size of the db.
Were seeing at a customer that even with bumped memory taking the initial snapshot of a 500GB db takes around 30 hours.
In addition, while taking the snapshot, debezium is not reading or acknowledging any logical log which accumulate disk space over the entire time - customer reported that logs files used 500GB after we migrated only 153GB of initial snapshot (about 1/3).

## Describe the solution you’d like
We need to find ways to improve the performance of initial snapshot taking.

## Describe the alternative you’ve considered or used
Two alternatives

1. Do the initial snapshot ourselves with direct connector (standard replication) and not rely on debezium.
2. Debezium seem to be able to do initial snapshot while reading streaming logical changes - they call it [incremental snapshot](https://debezium.io/blog/2021/10/07/incremental-snapshots/). This can help with accumulated disk space for logical logs

**Comment by rodireich** [comment]
It looks like the debezium approach is a non-starter as it is only for subsequent snapshots - not the initial one

>Currently, the execute-snapshot action type triggers [incremental snapshots](https://debezium.io/documentation/reference/stable/configuration/signalling.html#debezium-signaling-incremental-snapshots) only.

[Debezium connector for PostgreSQL](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-snapshots)

**Comment by bleonard** [comment]
fyi @subodh1810 - is this a duplicate with another one?

**Comment by bleonard** [comment]
Problems
1. WAL building up during long snapshot phase
2. We can't recover with error in middle of snapshot

Debezium incremental snapshots solves both of these by:
1. processing WAL in parallel
2. chunking snapshot for tables by sort ASC primary key.

For debezium, we need a signal table, which means we need write access to it.

Option A: lean into debezium incremental and enable write to the signal table (user change, current approach)
Option B: Implement incremental using our logic with parallel/context-switching between incremental and wal (no customer change, more work)

let's start with A. try it out. update the airbyte ste to be able to pick back up at that spot.

**Comment by subodh1810** [comment]
May be related?
https://github.com/airbytehq/airbyte/issues/13793
