### ISSUE TITLE
Improve onboarding UX: default sync frequency

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1858]
## Tell us about the problem you're trying to solve
When onboarding on Airbyte for the first time, it is not always clear why I can't go to the next step.

After (maybe?) struggling with setting up the right Infos to connect to both source and destination (finding the right hostnames, expected credentials, etc), I arrive on the final set up connection page, the button to finalize is grayed out until I select a "Sync frequency"

## Describe the solution you’d like
Can we select by default a "Sync frequency"? Maybe "Manual" or "24h"? (whatever)
So if I don't know what I am expected to do on this page for the moment, I can still click "Next" to be done and try airbyte out?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368144202575) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
i think i would prefer to focus on the UX to make it clear that this is a required field. i'm not sure there's a sane default to put in here.

sounds like maybe you should be able to click next but if the drop down hasn't been updated then it shows red and says you have to do that first?

what do you think?

**Comment by ChristopheDuong** [comment]
I've just observed a couple of users spending some time scrolling up and down on that page (they had a lot of tables in their source too) and seem to be taking quite long before doing the right thing to go to the next screen...

**Comment by cgardens** [comment]
@Jamakase - for this page, would it be possible to always allow the "save" button to be clickable but if sync frequency isn't set it gets highlighted in red?

**Comment by timroes** [comment]
This field has nowadays a default value. Closing this issue.
