### ISSUE TITLE
Source Klaviyo - Empty Event Properties

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#18601]
## Environment
- **Airbyte version**: 0.40.10
- **OS Version / Instance**: Debian 11 Bullseye in GCP
- **Deployment**: Google Compute Engine e2-highmem-2
- **Source Connector and version**: Klaviyo 0.1.10
- **Destination Connector and version**: BigQuery denormalized, version 1.2.4
- **Step where error happened**: Empty Columns

## Current Behavior
We are trying to work with the columns belonging to event_properties in events table, but they are all empty. We do not obtain any information from them.

## Expected Behavior
Know the root of the problem in order to solve it.

## Logs
![image](https://user-images.githubusercontent.com/10463486/198580943-cf222e5e-1a38-470c-ad5b-717d9c288464.png)

![image](https://user-images.githubusercontent.com/10463486/198581073-671e44de-346c-415c-8de1-e3e4e9caf5ee.png)

## Are you willing to submit a PR?
I don't dare.

**Comment by MoralesPablo** [comment]
Hi, any update here?
