### ISSUE TITLE
Epic: Destination+Source Snowflake + normalization: set application ID JDBC param

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#18626]
as described in https://airbytehq-team.slack.com/archives/C046LMDDY6N/p1666972075127309

source and destination should set the JDBC URL param `application` to  `airbyte_cloud` or `airbyte_oss`

normalization should figure out how to do this - maybe described in https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup#all-configurations

**Comment by evantahler** [comment]
All the sub-stories here are closed - can this be closed?

**Comment by akashkulk** [comment]
Yes
