### ISSUE TITLE
Simplify logic for comaprison of LSN stored in debezium state and confirmed_flush_lsn on Postgres source DB

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#18623]
Right now at the beginning of the sync we try to parse debezium state, extract the LSN stored and compare it with the `confirmed_flush_lsn` on the DB server to determine if the WAL logs still exist in the database. This is complicated and the code to parse debezium state is also difficult to understand. Instead there is a simpler way to do this. We can just query the `confirmed_flush_lsn` at the end of the sync and store it as part of the state and then at the beginning of a new sync compare it with whats stored in the DB. This will make the implementation simpler and easier to understand.

**Comment by rodireich** [comment]
This may have implications on our usage of heartbeats in #15040, because among other things we're also going to be looking at the reported heartbeat LSN

**Comment by bleonard** [comment]
We decided this is fine for now. The crazy parsing s just in that one method.
