### ISSUE TITLE
Update Toast component design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18631]
Update the Toast component design to match the new design in Figma:

https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=1475%3A2667

* Ensure that the toast looks good as expected in areas where it's being used
* Areas that use a title and description should consolidate to just using the description
* Reduce the bottom margin of the page (`$spacing-page-bottom` in scss) to be enough for the toast + Intercom badge (>= 88px) - [Design](https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=1701%3A44970)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
