### ISSUE TITLE
Source Stripe: Slow Initial Replication

### ISSUE THREAD

**Issue by robert-put** [airbytehq/airbyte#18638]
## Environment
- **Airbyte version**: 0.40.17
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: stripe 0.1.40
- **Destination Connector and version**: snowflake 0.4.38
- **Step where error happened**: Setup new connection

## Current Behavior
I just seems very slow to be replicating this long?

## Expected Behavior
Initial replication should be going faster than 1000 records a minute

## Logs
[d5778ff6_aa12_4502_b422_20323ade5c1e_logs_1028_txt.txt](https://github.com/airbytehq/airbyte/files/9892281/d5778ff6_aa12_4502_b422_20323ade5c1e_logs_1028_txt.txt)

## Steps to Reproduce
Just setup a new connection

Lookback Window in days: 0
Data request time increment in days: 365
Incremental Append Mode

## Are you willing to submit a PR?
sure?

**Comment by robert-put** [comment]
This just finished
```
22.09 GB10,296,684 emitted records10,296,684 committed records138h 3m 42s
```
If I'm doing something wrong please let me know, I will have to re-replicate at some point in the future and would love for it to not take ~6days.

**Comment by BenjaminMcC** [comment]
+1 for this, It currently takes us 13hours to pull 2gbs of data from the `charges` object. 

> Sync Succeeded
2.02 GB949,976 emitted records949,976 committed records12h 50m 54s

**Comment by davydov-d** [comment]
@YohanGrember @robert-put @BenjaminMcC could you please share your start date and slice range from the connector config? this would help me debug the issue. thanks!

**Comment by techieshark** [comment]
Just cross-linking to another issue/comment related to speed of fetching Stripe Charges - https://github.com/airbytehq/airbyte/issues/29575#issuecomment-2301210229
