### ISSUE TITLE
Low-code CDK: Autogenerated docs incomplete

### ISSUE THREAD

**Issue by scottleechua** [airbytehq/airbyte#18658]
## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Step where error happened**: Locally generating source connector project

## Current Behavior
Upon running
```
cd airbyte-integrations/connector-templates/generator
./generate.sh
```
and selecting `Configuration Based Source`, a new connector folder is created.

1. The newly-generated `README.md` is **missing the sample command** of how to run integration tests with docker:

```
#### Acceptance Tests

...

If your connector requires to create or destroy resources for use during acceptance tests create fixtures for it and place them inside integration_tests/acceptance.py.

To run your integration tests with docker

< LINE IS MISSING>

### Using gradle to run tests
...
```

2. Also, the documentation URL is not auto-generated for `spec.yaml`:

```
documentationUrl: https://docsurl.com
```
even though it is auto-generated in `README.md`:
```
#### Create credentials
**If you are a community contributor**, follow the instructions in the [documentation]
(https://docs.airbyte.io/integrations/sources/<source_name>) to generate the necessary credentials. 
```

## Expected Behavior
1. The docker command should be in `README.md`.
2. The proper documentation URL should also be templated into `spec.yaml`.

## Steps to Reproduce
1. Follow the steps on [this tutorial page](https://docs.airbyte.com/connector-development/config-based/tutorial/create-source).

## Are you willing to submit a PR?
Yes

**Comment by scottleechua** [comment]
# Additional Bug

* The documentation URL generated in `README.md` still points to `docs.airbyte.io` instead of `docs.airbyte.com`.

**Comment by sajarin** [comment]
@scottleechua thanks for finding these bugs, any chance you'd be willing to make a PR?

**Comment by scottleechua** [comment]
Yep! Could I ask for some direction --- which subfolder has the code for the document autogenerator?

**Comment by sajarin** [comment]
Hey @scottleechua sorry for the delay, the related file would be this: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/source-configuration-based/README.md.hbs

Were you able to find it?
