### ISSUE TITLE
No enum constant io.airbyte.config.DataType.BOOL in Files connector

### ISSUE THREAD

**Issue by danpolites** [airbytehq/airbyte#1865]
## Expected Behavior
CSV source files containing "true" or "false" values should not result in an error.

## Current Behavior
CSV files containing "true" or "false is causing the Files connector to throw the following error: java.lang.IllegalArgumentException: No enum constant io.airbyte.config.DataType.BOOL

## Steps to Reproduce
1. Upload a CSV file, to s3, containing a header row and a row of data containing the values "true" and "false.
1. Set up a new file connector, using s3fs.
1. Set up a new source and destination.
1. Failure message is displayed and exception is thrown.

## Severity of the bug for you
Medium

## Airbyte Version]
0.14.1-alpha

## Additional context
The issue seems to be in convert_dtype in source.py. Returning "boolean" instead of "bool" seems to clear it up.
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-file/source_file/source.py#L448

**Comment by sherifnada** [comment]
@danpolites thanks for filing this bug report. Will look into it shortly and get back to you.

**Comment by sherifnada** [comment]
@danpolites this issue was fixed and was released

**Comment by sherifnada** [comment]
The issue has been fixed in #1873 and will be released shortly.

**Comment by sherifnada** [comment]
@danpolites the fix has been released. Please upgrade your file source connector version to `0.1.9` from the Admin UI in Airbyte and you should have the fix running!
