### ISSUE TITLE
Source Shopify: remove read_checkout scope

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#18680]
## Tell us about the problem you're trying to solve
The application must not request permissions for unused scopes:
•	For the `read_checkout` permissions, this is only allowed when building an app with the Sales Channel SDK. 
Our app cannot have this scope/permission as it is not a Sales Channel.

**Comment by YowanR** [comment]
For this one, let's detail the issue that results from it, please

**Comment by igrankova** [comment]
[Checkouts docs](https://shopify.dev/api/admin-rest/2022-10/resources/checkout)

**Comment by igrankova** [comment]
@bazarnov, can you please add more details about the read_checkout scope removal, does it affect the implemented streams?
