### ISSUE TITLE
Source Monday: Migrate connector from Alpha (Python) to Beta (YAML)

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#18694]
MLP: https://docs.google.com/document/d/1sjGVVLDXqj1ajTl08T8X0DgTPoTg_EGLsg0oMD5ABfk/edit
CI creds: Primary Monday Dev Account

**Comment by lazebnyi** [comment]
duplicate - https://github.com/airbytehq/airbyte/issues/18703
