### ISSUE TITLE
Create an embeddable  Agent 

### ISSUE THREAD

**Issue by MChorfa** [airbytehq/airbyte#1869]
## Tell us about the problem you're trying to solve
Pull data from IoT devices and BrownFilled applications 

## Describe the solution you’d like
Create an  embeddable agent with a  small footprint to enable wir-byte pulling data from the target

Agent: 

* Rust lang (small binary no JVM)
* NATS

## Describe the alternative you’ve considered or used
NiFi-mini 

## Additional context
Allow pulling data from IoT on scheduled time

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368209786093) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@MChorfa I'm closing this issue as stale. We don't have a clear path forward. If you have more thoughts on the value of this, please feel free to re-open it.
