### ISSUE TITLE
Tag input in connector configuration no longer matches the styles of the rest of the inputs

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#18692]
## Environment
- **Airbyte version**:  0.40.17

## Current Behavior
Tag input no longer matches the style of the rest of the inputs. Some things I noticed:

* Placeholder text with "Select..."
* Focus state has thick border
* Background is not grey

![Screen Shot 2022-10-31 at 10 06 37](https://user-images.githubusercontent.com/168664/199027688-d49f965e-e40a-4019-b055-b5e3511c3e83.png)

Likely caused by #16027

## Expected Behavior
Tag input should match the style of the rest of the inputs

## Steps to Reproduce
1. Create a new Postgres source
2. Scroll down to the schemas component

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
