### ISSUE TITLE
[SAT] Test Spec: Check for duplicate values under `enum`

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#18740]
We should have a Source acceptance test running on all sources that will ensure that a spec fails, that contains a duplicate `enum` entry, e.g. as the Kafka Destination does at the moment: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-kafka/src/main/resources/spec.json#L192-L194

**Comment by erohmensing** [comment]
This seems similar enough to `test_oneof_usage` to check during spec validation
