### ISSUE TITLE
Research Genesys source connector

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#18786]
## Complete the following exercise for Genesys source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:

[EPIC] GA & Beta Connector Research #9675

**Comment by YowanR** [comment]
@ycherniaiev Do we have an issue for this connector? Can't find it on GH

**Comment by ycherniaiev** [comment]
@YowanR sure. https://docs.google.com/document/d/1o1Q4fA5MaAPetFpqYa9l8qLRe6HufQn9QHW5seQseQ4/edit

**Comment by ycherniaiev** [comment]
Or sorry, you meant issue

**Comment by ycherniaiev** [comment]
If I am not mistaken we create issue when all the preliminary work is done. Genesys has only paid sandbox and we not decided how to proceed with it
