### ISSUE TITLE
Create Link component

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#18825]
We currently don't have a fully working `Link` component in the app. We should create a component `Link`, that does the following things:

* Applies our regular link styling, that we want (underlining, color, etc.)
* Accepts either a `to`, `href` or `onClick` property, if
  * `to` is specified rendering a react-router link that will lead to the `to` page
  * `href` is specifies, treat it as an external link and render a `a` element. Also set `noopener noreferer` if it's an external domain not under our control
  * `onClick` render `button` element (that just looks like a link), triggering the `onClick`.
* Should support `openInNewWindow` to set `target="_blank"` for the `to` and `href` case.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
