### ISSUE TITLE
Ensure that secrets are marked secret

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#18824]
From https://github.com/airbytehq/airbyte-cloud/issues/2576 and https://github.com/airbytehq/airbyte/pull/16390

We need to be sure that config fields in a connector that should be marked "secret" are so we store that information appropriately. 

Ideas:
* The SAT can import this test (but then destinations won't be tested)
* We can continue to use a stand-alone script, and add it to our `/test` and `/publish` workflows

https://github.com/airbytehq/airbyte/blob/7b9a0970817c9e9399a033531bdfada2ca89254f/tools/bin/scan_all_spec_airbyte_secret.py#L19-L36

Be sure to also remove or update the script added in https://github.com/airbytehq/airbyte/pull/16390

**Comment by davydov-d** [comment]
closing this regarding Evan's [comment](https://github.com/airbytehq/airbyte-cloud/issues/2576#issuecomment-1306184585)
