### ISSUE TITLE
Source Postgres: Cannot add new connection in 0.40.18 with Postgres to Bigquery

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#18869]
When I try to add a new connection once at the replication settings screen I get invalid JSON when I try to click Save and  test

Happens with Postgres to bigquery connection in Airbyte 0.40.18

**Comment by harshithmullapudi** [comment]
Hey, thanks for reaching out but I feel this post will be more relevant at https://discuss.airbyte.io could you create a post so that team can help you out?

**Comment by ro8inmorgan** [comment]
Why? This is an actual bug in Airbyte, not some user error. Try it yourself, you can’t add new connections anymore.

**Comment by harshithmullapudi** [comment]
Hey sure I just tried it and it is working for me, can you help with more information? 
1. Can you share the screenshot of the error?
2. Can you check the API call and share the created connection's screenshot or response?

**Comment by stephane-airbyte** [comment]
Closing. It's 1 year old, on a very old connector version, and there's been no update from the reporter
