### ISSUE TITLE
Run SAT tests on Destination's CHECK command

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#18866]
1. SAT is a bad name - Time to rename to Connector Acceptance Test? Protocol Acceptance Test?
2. This could be added to /test for destinations
3. This could be added to /publish (which also runs /test)

There is a DAT? What does that do? I think it's just for Java destinations? We should learn more.

**Comment by flash1293** [comment]
This is unblocked, further work is tracked here: https://github.com/airbytehq/airbyte/issues/22847
