### ISSUE TITLE
Collect trace message on failed connection_status 

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#18865]
When there is a failed connection status (CHECK), sometimes the connector also emits an AirbyteTraceMessage with a failure reason.  Right now, we don't use the TraceMessage to build the failure reason like we do in a running sync.  We should!  

These errors are not presisted to the DB, but are sent to Sentry in https://github.com/airbytehq/airbyte/issues/19898

To reproduce this error:
* exit 0 (container didn't crash)
* The connector returned success=false + a TraceMessage.

We *do* properly capture trace messages with failures if the connector exited with a non-0 code.

**Comment by pedroslopez** [comment]
https://github.com/airbytehq/airbyte/blob/ef08d8845558661199c98aed9a20fd378ba088ab/airbyte-commons-worker/src/main/java/io/airbyte/workers/general/DefaultCheckConnectionWorker.java#L100

**Comment by evantahler** [comment]
Check in with @akashkulk to learn which DB sources we can use to confirm the fixed behavior and see the Trace message content
