### ISSUE TITLE
Source Netsuite: Resolve Issue faced by early adopter 

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#18885]
We had a discussion with a customer around the issues they faced while trying to use Netsuite. This epic is to collect all the data we have and try to resolve this issue asap.

More details can be found in this [doc](https://docs.google.com/document/d/10-oVrmx-145edlg1IePeQQEFhuXb5UCq0ElsjMU3LEI/edit?usp=sharing).

**Comment by YowanR** [comment]
Note that the error that we see in the video seems different from the ones here. I'd suggest that we start from the issues listed in the video (within the doc attached above)

**Comment by YowanR** [comment]
@lazebnyi @oustynova @YuliiaNahoha  This is a high pri ask so we have to prioritize this for the next sprint.
Thanks!

**Comment by YowanR** [comment]
Bump on this one -- @lazebnyi @YuliiaNahoha

**Comment by YowanR** [comment]
Please take a look at this @lazebnyi @YuliiaNahoha

**Comment by lazebnyi** [comment]
Hi @YowanR 
@bazarnov start working on it after Asana certification.

**Comment by bazarnov** [comment]
Waiting for code freeze dismissal before merging this down. Moved to On Hold.

**Comment by bazarnov** [comment]
@YowanR Yes, we just need to `publish` and `merge` here.
