### ISSUE TITLE
Obtain public developer application for the Auth0 source connector

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#18897]
## Tell us about the problem you're trying to solve
Obtain a public developer application for the Auth0 connector like specified in airbytehq/airbyte-internal-issues#242

###Requirements to obtain public developer application
[Auth methods docs docs](https://auth0.com/docs/api/authentication#authentication-methods)
For public applications (applications that cannot hold credentials securely, such as SPAs or mobile apps), there are some endpoints that can be accessed using only the Client ID. 
LAstpass Oauth creds: Pivotal Tracker OAuth

**Comment by kyle-cheung** [comment]
+1 on this would love an auth0 connector
