### ISSUE TITLE
Notifications settings page: unneeded scroll appears on hover "Test" button 

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#18906]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: macOS, Chrome
- **Deployment**: local
- **Step where error happened**: Settings / Notifications / Notification Settings

## Current Behavior
An unneeded scroll appears on the hover "Test" button on Notification settings page.

![CPT2211031545-1087x600](https://user-images.githubusercontent.com/20929344/199737388-73a6e17e-ff40-4f17-8e9d-02099153d73b.gif)

## Expected Behavior
No extra scroll

## Steps to Reproduce
1. Open the Settings page from the left side bar
2. Choose "Notifications"
3. Hover the "Test" button

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
