### ISSUE TITLE
Basic Normalization is not working without the schema

### ISSUE THREAD

**Issue by siddhant3030** [airbytehq/airbyte#18904]
## Environment
- **Latest**
- **MacOS**
- **Deployment**
- **SurveyCTO beta**:
- **Postgres latest**
- **Sync job**

## Current Behavior
- We are developing a custom source connector for Survey CTO (surveycto.com) where we are pulling data from its API's. SURVEYCTO has an api to pull data for each form_id. We can pass different form_ids in our connector as an array of form_id initially so it can pull data from different forms. For every forms we create a new stream with the name of the form_id.

- Raw JSON ingestion works well and we can create raw tables in Postgres destination but we would like to use basic normalization on top of it so it can flatten the data for us. But in the docs it is mentioned that it doesn't need a schema -
https://docs.airbyte.com/understanding-airbyte/basic-normalization#destinations-that-support-basic-normalization.

- In source definitions for a connector it mentions we must provide a schema - https://airbytehq.github.io/connector-development/cdk-python/schemas/. If you look into our schema we have hardcoded the schema to test it and in which case it's working. So we are little confused about it from the docs.

## Expected Behavior
we should be able to do basic normalization without having to specify a source stream schema.

## Logs
<img width="1076" alt="Screenshot 2022-11-03 at 1 30 52 PM" src="https://user-images.githubusercontent.com/9019958/199703898-9612f044-cc90-40b3-b306-f64da959d327.png">

FileNotFoundError: [Errno 2] No such file or directory: '/airbyte/integration_code/source_surveycto/schemas/baseline_ig.json'

## Steps to Reproduce
1. Create a source for Surveycto
2. Create a destination for Postgres
3. Run the basic normalization

**Comment by sh4sh** [comment]
Hey, can you please attach the full log? Also, can you try rebasing your fork as it's out of date and there have been many changes!

The Airbyte protocol does require connectors to have a jsonschema for each stream: https://airbytehq.github.io/connector-development/cdk-python/full-refresh-stream#defining-the-streams-schema

**Comment by siddhant3030** [comment]
@sh4sh Hey. 
Then why it is mentioned here https://docs.airbyte.com/understanding-airbyte/basic-normalization/
that it can do it automatically and doesn't need a schema. Do we need to update this documentation? Because things are not clear here

**Comment by sh4sh** [comment]
@siddhant3030 please provide the full sync log, it is very difficult to debug something without logs.

The log lines visible in the screenshot appear to show the source connector running `discover. The destination connector and normalization step have not run yet. There's more info on the `discover` method here: https://docs.airbyte.com/understanding-airbyte/airbyte-protocol#discover

**Comment by siddhant3030** [comment]
@sh4sh Sorry we were under the impression that the source connector doesn't need a schema. We have not used the schema for the source connector that's why we are getting this error. 

I'm trying to communicate to you that from the documentation for basic normalization it's not clear if we need a schema for the source connector.
