### ISSUE TITLE
ELK stack integration?

### ISSUE THREAD

**Issue by StevenGallagher** [airbytehq/airbyte#1890]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Elasticsearch and Logstash - as both Source and Destinations.
Realtime (if that's possible)

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.
Many teams use ELK stack for monitoring application logs and metrics.
Would be nice to push this into DWH, or pull out of DWH and build Kibana dashboard's.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Using Kafka + Confluent Kafka Connect - but that's a lot of platforms to maintain.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368143625092) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
>  Realtime (if that's possible)

What is an acceptable delay for replication lag that you would accept?

(at the moment, Airbyte is not real-time but still has a batch approach)

**Comment by stefanondisponibile** [comment]
hey @ChristopheDuong  I would be interested in this too.
Real time is nice-to-have, but can be lagged, in my case (few hours).

Mostly, it would be interesting having Elasticsearch as a Destination.

Probably I should open a separate issue for this, but is there any guide or possibility of contributing to add custom destinations?

Thank you!

**Comment by ChristopheDuong** [comment]
> hey @ChristopheDuong I would be interested in this too.
> Real time is nice-to-have, but can be lagged, in my case (few hours).
> 
> Mostly, it would be interesting having Elasticsearch as a Destination.
> 
> Probably I should open a separate issue for this, but is there any guide or possibility of contributing to add custom destinations?
> 
> Thank you!

Hello,
Thanks for your interest!

Unfortunately, contributing custom destinations is not well documented yet.

You could follow/comment on the following ticket:
https://github.com/airbytehq/airbyte/issues/2755

**Comment by stefanondisponibile** [comment]
thank you @ChristopheDuong ! ✨

**Comment by ChristopheDuong** [comment]
you can also have a look at this PR: https://github.com/airbytehq/airbyte/pull/3021

**Comment by marcosmarxm** [comment]
ElasticSearch is supported.
