### ISSUE TITLE
Destination S3 Parquet: int4 falsely becomes double

### ISSUE THREAD

**Issue by PierreKerschgens** [airbytehq/airbyte#18922]
## Environment
- **Airbyte version**:  0.40.14
- **OS Version / Instance**: Ubuntu 20.04.4 LTS on AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.16
- **Destination Connector and version**: S3 0.3.16
- **Step where error happened**: Sync Job

## Current Behavior
Hey everybody,

I have a question regarding the data types of the parquet format in the S3 destination.
As source I want to sync data from a PostgreSQL database.

The PostgreSQL DDL looks like this:
```
CREATE TABLE public.task_events (
	id serial4 NOT NULL,
	task_id int4 NULL,
	event_name varchar(20) NULL,
	ts timestamp NOT NULL,
	CONSTRAINT task_events_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_task_events_task_id ON public.task_events USING btree (task_id);
CREATE INDEX ix_task_events_ts ON public.task_events USING btree (ts);
```

When I obtain the jsonschema from Airbyte API I receive these types (looking good to me):
```
print(json_schema['properties']['id'])
{'type': 'number', 'airbyte_type': 'integer'}
```

```
print(json_schema['properties']['ts'])
{'type': 'string', 'format': 'date-time', 'airbyte_type': 'timestamp_without_timezone'}
```

```
print(json_schema['properties']['task_id'])
{'type': 'number', 'airbyte_type': 'integer'}
```

```
print(json_schema['properties']['event_name'])
{'type': 'string'}
```

Now I check the .parquet files written to S3 by Airbyte in AWS Glue and it has these types:
```
id double
ts struct
task_id double
event_name string
```

So I guess the S3/Parquet destination converted `task_events.id` and `task_events.task_id` to `double` instead of `int`. 
This leads to IDs like “4.2108168E7” instead of “42108168"

I hope someone can help with this.

Thanks in advance! :)

(thanks to @natalyjazzviolin for reacting to this in Slack)

## Expected Behavior
Airbyte's S3/Parquet destination should handle int4 data type as int instead of double.

## Logs
I didn't find logs to this.

## Steps to Reproduce
1. Create PostgreSQL table with int4 data type field
2. Update the field with this value: 42108168
3. Sync PostgreSQL table with Airbyte and write to S3 in Parquet format
4. Download parquet file and inspect the value (or create AWS Glue database on that Parquet file) -> 4.2108168E7

## Are you willing to submit a PR?
Would love to contribute but I'm not familiar with Java.

**Comment by evantahler** [comment]
This should be fixed with the 1.0 version of the destination-s3 connector.
