### ISSUE TITLE
Amazon Ads Source - make lookback window customizable 

### ISSUE THREAD

**Issue by klsoper** [airbytehq/airbyte#18929]
## Tell us about the problem you're trying to solve
I want to be able to always resync the past 30 days of data on each sync with this source without having to change the start date each time

## Describe the solution you’d like
Make the lookback window customizable for Amazon Ads source 

## Describe the alternative you’ve considered or used
Changing the start date each sync as the day changes 

## Additional context
-
## Are you willing to submit a PR?
-

**Comment by dandpz** [comment]
I would add that the lookback value set to 3 does not take in account the restatement process that, documentation says, it can take up to 28 days to update.
Ref: https://advertising.amazon.com/API/docs/en-us/reporting/v2/faq#how-long-does-it-take-for-sponsored-ads-reporting-data-to-become-available

**Comment by dandpz** [comment]
I created a PR here: https://github.com/airbytehq/airbyte/pull/19491
