### ISSUE TITLE
Local JSON destination folder empty

### ISSUE THREAD

**Issue by modnar1226** [airbytehq/airbyte#1895]
## Expected Behavior
Salesforce Connector with local JSON destination file at /tmp/airbyte_local should have files or folders

## Current Behavior
Syncing seems to work and the UI says that records have synced.
After sync the folder at local /tmp/airbyte_local is empty, instead of containing the json files.

## Steps to Reproduce
1. On ubuntu 18.04 set up Salesforce connector
2. Set local file destination to default, with a Local JSON destination
3. Sync records, check file system and folder is empty

## Severity of the bug for you
High

## Airbyte Version
version 0.14.0-alpha

**Comment by michel-tricot** [comment]
@modnar1226 how did you configure the output path in the destination?

We simplified the behavior in https://github.com/airbytehq/airbyte/pull/1882

**Comment by modnar1226** [comment]
I put the path to my user's home directory /home/<username> The path that was found was /tmp/airbyte_local not what I put in

I tried editing the .env file and relaunching the docker container with LOCAL_PATH = /home/<username> the file path changed to /temp/home/<user>

**Comment by michel-tricot** [comment]
What were the options you configured for the file destination?

can you try configuring your `.env`
```
LOCAL_PATH=/home/user
```

and when you configure the file path in the destination put: `/local/my_data`

**Comment by modnar1226** [comment]
This is what I've done so far.
LOCAL_ROOT=/home/user
LOCAL_DOCKER_MOUNT=/tmp/airbyte_local

I setup a new destination set to use LOCAL_JSON using the path: local/sfbackup_json
The files are indeed populated but the backup file were located at /tmp/airbyte_local/sfbackup_json.

I suspect that I need to set the LOCAL_DOCKER_MOUNT variable instead of the LOCAL_ROOT.

Looks to be a promising change.
I will let you know the results in a day or so. The backup is currently running and I would like to have a full snapshot before I kill the container and restart.  Thanks for your help so far!

**Comment by michel-tricot** [comment]
@modnar1226 any success?

**Comment by modnar1226** [comment]
Yes, I just confirmed that setting the LOCAL_DOCKER_MOUNT=/home/user var in the .env file, as well as using the configuration path in the destination setup of local/sfbackup_json resulted in the backup files being present in /home/user/sfbackup_json/

Thanks again!!

**Comment by michel-tricot** [comment]
Great!!
