### ISSUE TITLE
Source Amazon Seller Partner: GET_SALES_AND_TRAFFIC_REPORT with incremental sync mode does not update last data

### ISSUE THREAD

**Issue by dandpz** [airbytehq/airbyte#18958]
## Environment
- **Airbyte version**:  example is 0.40.18-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker env
- **Source Connector and version**: Amazon Seller Partner 0.2.28
- **Destination Connector and version**: n.a.
- **Step where error happened**: Sync job

## Current Behavior
After setting up the sync mode to `Incremental | append` the job correctly runs, but according to Amazon documentation reports may take up to a week to populate data after a reporting periods closes, so with cursor field set to queryEndDate fresh data are missing and the last reports are all with traffic equals 0.

## Expected Behavior
When downloading stream with incremental sync mode the connector should use a rolling time window containing also the last week already processed. 

## Logs
/

## Steps to Reproduce
1. Configure Amazon Selling Partner connector
2. Enable GET_SALES_AND_TRAFFIC_REPORT replication stream with sync mode set to Incremental | Append
3. Verify data in time against Amazon seller central reports

## Are you willing to submit a PR?
I can work on it, but some help would be great

**Comment by krisjan-oldekamp** [comment]
@dandpz I can fix this. Indeed I can reproduce that the session data is not processed / made available by Amazon within a day. However it seems that within 2 days the data is there, so I can change the availability SLA to two days for this specific report?

**Comment by dandpz** [comment]
> @dandpz I can fix this. Indeed I can reproduce that the session data is not processed / made available by Amazon within a day. However it seems that within 2 days the data is there, so I can change the availability SLA to two days for this specific report?

It would be great. Actually in the past I saw a delay of also 3 days, unfortunately I cannot find a value in the documentation for this delay. I cannot recall a delay greater than 3 days, so maybe we can put it equals to 3.
