### ISSUE TITLE
BigQuery DATE and TIMESTAMP source fields are synced as TEXT

### ISSUE THREAD

**Issue by torkjel** [airbytehq/airbyte#18957]
## Environment
- **Airbyte version**:  v0.40.26-helm
- **OS Version / Instance**: GCP GKE
- **Deployment**: Kubernetes
- **Source Connector and version**: BigQuery 0.2.2
- **Destination Connector and version**: Postgres 1.0.15
- **Step where error happened**: Sync job

## Current Behavior
BigQuery columns with type DATE or TIMESTAMP end up as TEXT type columns in Postgres. When syncing the other direction the fields retain their expected type. 

## Expected Behavior
Columns retain their type, as far as can be reasonably expected. Ideally, I'd like table schemas to roundtip intact. 

## Steps to Reproduce
1: Create a BigQuery table with a DATE column
2: Sync this table to Postgres
3: Observe thet the synced column is of type TEXT.

## Are you willing to submit a PR?
Time permitting, yes. 
This looks like a fairly trivial change to make. I expect this this is to blame: https://github.com/airbytehq/airbyte/blob/v0.40.18/airbyte-db/db-lib/src/main/java/io/airbyte/db/bigquery/BigQuerySourceOperations.java#L124

**Comment by steven1u** [comment]
Hey any update on this one?
Would be really nice to have a proper typing

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
