### ISSUE TITLE
Source Typeform

### ISSUE THREAD

**Issue by flpezet** [airbytehq/airbyte#1897]
## Tell us about the new integration you’d like to have
_Which source and which destination? Which frequency?_
I'd like to fetch data from Typeforms. Every 1h would be a good start. 

## Describe the context around this new integration
_Which team in your company wants this integration, what for? This helps us understand the use case._
We send a lot of automatic customer surveys via Typeform.

## Describe the alternative you are considering or using
_What are you considering doing if you don’t have this integration through Airbyte?_
We currently use the Typeform tap from Singer. But the integration is broken, we lose a lot of data. The Singer team doesn't really care about this tap. They don't want to merge the PR that has been opened to fix the issue.

Note: I'd like to work on this connector.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368210494121) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@flpezet thanks for opening the issue and proposing to work on the connector! We're happy to help however we can. Some pointers to help you get started: 

1. Our [connector docs](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector) are a good starting point for contribution
2. Have you joined our [Slack](slack.airbyte.io)? We're always available to support in any way over there. 
3. We're also happy to pair/hop on a call to chat about any questions you have
