### ISSUE TITLE
Source Google Search Console - provide the ability to optionally set aggregationType to "byPage" or "byProperty"

### ISSUE THREAD

**Issue by dancook-doxo** [airbytehq/airbyte#18975]
## Tell us about the problem you're trying to solve
Provide the ability to optionally set aggregationType to "byPage" or "byProperty". As it currently stands the GSC connector presumably uses the default setting, which is "Auto". Results can differ pretty substantially when choosing between the other types. Please see these links:
https://developers.google.com/webmaster-tools/v1/searchanalytics/query
https://support.google.com/webmasters/answer/7576553?visit_id=638031145198833195-1658800878&rd=1#urlorsite

## Describe the solution you’d like
Add an option on a per-report basis, in custom reports and in the built-in ones, to set the aggregation type.

## Describe the alternative you’ve considered or used
It *might* be possible to set up a custom report which can be aggregated later, in SQL, by the relevant dimension. But it would presumably blow up the row counts to add pagePath/URI as a dimension.

Another alternative is that the GSC connector provides the equivalents of Fivetran's KEYWORD_SITE_REPORT_BY_PAGE and KEYWORD_SITE_REPORT_BY_SITE, with the relevant aggregation built in.
(and similarly SITE_REPORT_BY_PAGE vs. SITE_REPORT_BY_SITE)

**Comment by sherifnada** [comment]
@dancook-doxo those streams are coming soon! See the issues for this connector here https://github.com/airbytehq/airbyte/issues?q=is%3Aopen+is%3Aissue+label%3Aconnectors%2Fsource%2Fgoogle-search-console and LMK if you'll be needing more

**Comment by bazarnov** [comment]
I like this idea, it's a more comprehensive solution:

```
Another alternative is that the GSC connector provides the equivalents of Fivetran's KEYWORD_SITE_REPORT_BY_PAGE and KEYWORD_SITE_REPORT_BY_SITE, with the relevant aggregation built in.
(and similarly SITE_REPORT_BY_PAGE vs. SITE_REPORT_BY_SITE)
```

**Comment by bazarnov** [comment]
The `KEYWORD_SITE_REPORT_BY_PAGE` already exists.
The `KEYWORD_SITE_REPORT_BY_SITE` will be added in this PR: https://github.com/airbytehq/airbyte/pull/29750
