### ISSUE TITLE
Source-postgres-strict-encrypt 1.0.22 fails to set up connection w/o SSL

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#18992]
The issue came from support. One of the customer connection stopped working after we upgraded postgres source strict encrypt from 1.0.19 to 1.0.21 (October 27). Their connection is set up with SSSH tunnel and with ssl_mode=disable. On October 26, after the connector was upgraded, their syncs started failing with this error `the the server does not support ssl`. Check method was failing as well on the connector setup page with the same error. After I downgraded the postgres source connector in cloud back to 1.0.19, the error went away.

See **p1-ssl-required-with-ssh-setup** Slack channel for more info.

Connection: https://cloud.airbyte.io/workspaces/be5b52e2-0e25-44a4-841c-30f875406568/connections/f8ac541a-614c-436a-af25-09f669580db0/status

**Comment by tuliren** [comment]
Actually it’s possible that `1.0.19`’s check method is not working.
If I change the SSH port from `22` to `23`, and retest the connection, the check will pass!
Given that `1.0.20` changed the visibility of the SSH exception, maybe `1.0.19` was just hiding this exception.

Also it looks like we are still always enforcing SSL. Here is the code to get default JDBC params:
```java
if (JdbcUtils.useSsl(config)) {
  return SSL_JDBC_PARAMETERS; // <- include "ssl = true & sslmode = require"
} else {
  return Collections.emptyMap();
}
```
And the definition of useSsl is:
```
public static boolean useSsl(final JsonNode config) {
  return !config.has(SSL_KEY) || config.get(SSL_KEY).asBoolean();
}
```
So if there is no `SSL_KEY`, which is the case for strict-encrypt, Postgres will enforce SSL, which matches the exception message.

**Comment by VitaliiMaltsev** [comment]
created [PR](https://github.com/airbytehq/airbyte/pull/19025) with a fix

**Comment by grishick** [comment]
@VitaliiMaltsev don't forget to unpin Postgres source version in Airbyte Cloud.

**Comment by VitaliiMaltsev** [comment]
cloud version updated and unpined for source-postgres-strict-encrypt and source-mysql-strict-encrypt
