### ISSUE TITLE
Salesforce <-> Airbyte full sync blocked to 14900 records for OpportunityLineItems

### ISSUE THREAD

**Issue by louisdauvois** [airbytehq/airbyte#19014]
Is this your first time deploying Airbyte?: No
OS Version / Instance: MacOS
Memory / Disk: 500GO
Deployment: Docker
Airbyte Version: What version are you using now?
Source name/version: 0.40.18
Destination name/version:
Step: Create a new connection between Salesforce and CSV, run a full sync
Description:
When we try to do a full sync on our Salesforce Objects the sync stop at 14900 records but when we do in in salesforce or via api we get 49000+ records.

Seems to have the problem only on OpportunityLineItems since we get approx good number for the account object.

**Comment by birdieorbust** [comment]
I am seeing the same issue when doing a full sync on the Account object and not all records being returned.

**Comment by arsenlosenko** [comment]
fix for this issue will be in scope of this PR: https://github.com/airbytehq/airbyte/pull/24888

**Comment by roman-yermilov-gl** [comment]
@louisdauvois Could you provide us with any logs so we can investigate the process?

**Comment by roman-yermilov-gl** [comment]
My recommendation would be to use incremental sync as it has checkpointing. Actually full-refresh sync is also using smaller batches now so it worth to try it again. And it also important to check start date because if it's not set, then sync will be for last 2 years
