### ISSUE TITLE
HI. I try to insert my CSV file into my database using airbyte. The CSV file is changeable and has some extra space in the format. Is it...

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#19031]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3291](https://airbyte7538.zendesk.com/agent/tickets/3291)
**Priority:** high
**Group:** Community Assistance Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">HI. I try to insert my CSV file into my database using airbyte. The CSV file is changeable and has some extra space in the format. Is it possible to edit my CSV file using  airbyte ..?
<br> [via Slack] Open original slack thread in #public-airbyte-help channel: <a href="https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1667295199687039" target="_blank" rel="nofollow noreferrer">https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1667295199687039</a></p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-01 at 12:08:*

<blockquote><div class="zd-comment" dir="auto">Hi Godlin, it is not possible to edit your CSV using Airbyte, but it's possible to use dbt. What connectors are you trying to use?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-11-02 at 05:35:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] Hello Nataly Merezhuk, it's a file connector but our file is on digital ocean spaces...</p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-02 at 14:03:*

<blockquote><div class="zd-comment" dir="auto">Take a look at this docs:<br><a rel="noopener noreferrer" href="https://airbytehq.github.io/operator-guides/transformation-and-normalization/transformations-with-dbt/">https://airbytehq.github.io/operator-guides/transformation-and-normalization/transformations-with-dbt/</a><br><br>Let me know if this helps!<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-11-04 at 07:36:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] I am facing another error when I try to up airbyte using the docker its shows Oops! Something went wrong… I check docker logs on airbyte server its shows Waiting for namespace default to be initialized in temporal...could you please help me....</p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-11-04 at 07:38:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] Attachments:
<br>Attached file : <a href="https://airbytehq-team.slack.com/archives/C021JANJ6TY?thread_ts=1667295199.687039" target="_blank" rel="nofollow noreferrer">https://airbytehq-team.slack.com/archives/C021JANJ6TY?thread_ts=1667295199.687039</a></p></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Nataly Merezhuk on 2022-11-04 at 14:13:*

<blockquote><div class="zd-comment" dir="auto">Hey! Usually we have one question per thread, so in the future please start a new thread :) it helps our team stay organized and do our job better.<br><br>I'll need a few more details to understand where this issue is coming from. Did you recently update Airbyte? Where is it hosted? What system are you using?<br></div></blockquote>

**Comment by marcosmarxm** [comment]
*Comment made from Zendesk by Marcos Marx on 2022-11-05 at 03:42:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">[via Slack] Oh ok, sorry for that. I update almost 1 month back. it is hosted by Digital Ocean and we are using ubuntu</p></div></blockquote>

**Comment by natalyjazzviolin** [comment]
Created by mistake.
