### ISSUE TITLE
New Destination: ClickHouse

### ISSUE THREAD

**Issue by josepowera** [airbytehq/airbyte#1903]
## Tell us about the new integration you’d like to have
Which source and which destination? 
ClickHouse  (https://clickhouse.tech/)  - https://github.com/ClickHouse/ClickHouse
Clickhouse goes in same direction as Snowflake, but is OpenSource. Handles billinons of rows without problem.

JDBC driver is available  (https://github.com/ClickHouse/clickhouse-jdbc)

Integration as Source and as Destination would be highly welcome.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368209992120) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thank you @josepowera !

Agreed that it would make great addition to the connectors. The fact that it has a jdbc driver should make the first version trivial to create since we have an existing Jdbc base for both destinations & sources.

Would you be interested in taking a crack at it? We can guide you through the process of creating a new connector.

**Comment by kunaldawn** [comment]
need the same!

**Comment by subodh1810** [comment]
@josepowera @kunaldawn hey can you share which clickhouse version are you using?

**Comment by subodh1810** [comment]
I have created https://github.com/airbytehq/airbyte/issues/3317 to track clickhouse source integration. 
We will have a separate issue for clickhouse destination integration

**Comment by subodh1810** [comment]
hey @josepowera thanks for letting me know the version. I just merged the PR for implementation of clickhouse as a source 
Ref : https://github.com/airbytehq/airbyte/pull/3361 and https://github.com/airbytehq/airbyte/pull/3375
Look for it in the next release cycle. Keep tracking this current issue for updates on clickhouse as destination

**Comment by bindu29** [comment]
need clickhouse has destination connector

**Comment by sajanpummer** [comment]
Looking for this connector.
