### ISSUE TITLE
Document how to upgrade a connector version

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1905]
## Tell us about the documentation you'd like us to add or update
As a user, I'd like to know how to upgrade the version of a connector I'm using without upgrading all of Airbyte.

**Comment by cgardens** [comment]
Yeah this is somewhat acute because with the new migration path there is no auto upgrade of connectors path right now either. To upgrade connectors on an existing instance it just has to be done one-by-one manually in the UI which is not good.

**Comment by davinchia** [comment]
@cgardens this is pretty easy to do so now with the new UI changes yes?
