### ISSUE TITLE
Call list_latest only when needed

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#19081]
The FE code at the moment calls whenever we want the source (or destination) definitions the `/v1/source_definitions/list_latest` as well as the `/v1/source_definitions/list` API (see https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/services/connector/SourceDefinitionService.ts#L40).

We only use the values from the later API to figure out the latest docker version of the connector to know if it has an update available. We need that information barely in any place - as far as I can tell only the connector update settings page and only in OSS.

Given that the `list_latest` APIs return rather large JSON (sources' `list_latest` is at 2.3MB at the moment at cloud), we should not call `list_latest` every time we want connector specifications, but instead pull that logic into a separate method/hook that will only be called if we actually need to have that information because we care about updating/outdated connectors.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
Excessive calls should be gone!
