### ISSUE TITLE
Create APIAcceptanceTest suite in cloud and oss

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#19087]
Currently we don't have any test on if our path are accessible or not. This is an issue because we can change a path that will lead to errors in the API without us noticing.

We need to add an acceptance test that will check all the API path.

**Comment by cpdeethree** [comment]
A test suite such as this would have prevented a recent p0 that occurred in 11-01-2023. 

It also would have prevented [this issue](https://airbytehq-team.slack.com/archives/C03AS1GAQV6/p1673293733534519).

The ask here is, in both cloud and oss, create a test suite that hits a range of api endpoints and ensures that they respond as expected. At the bare minimum, they should return an expected response code. Ideally we could also check and ensure that the performance/responsiveness of said api's is within expectation as well, but shouldn't be considered as a hard requirement in the scope of this issue.

**Comment by davinchia** [comment]
This is done.
