### ISSUE TITLE
Make git SHA of published connector versions discoverable for `git diff`ing

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#19090]
## Tell us about the problem you're trying to solve
We want an easy way to see the diff between published versions of a connector

## Describe the solution you’d like
Publish the git SHA somewhere as part of the `/publish` command so that users can use these to compare files 

This SHA could live e.g.
- in the connector code itself, similar to a version file (guaranteed coupled to published code) 
- in the changelog (easy access for people looking for version differences, don't need connector code installed)
- in the comment output by `/publish` (probably not what we want, as from the PR the sha is quite easy to find)

## Describe the alternative you’ve considered or used
Connectors living in their own repos and being version tagged that way for easy diff comparison (does not scale - already wouldn't)

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/17532
