### ISSUE TITLE
[Connector Builder UI] Configurable Stream Slicers

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#19107]
## Tell us about the problem you're trying to solve
Add UI field to the stream view to allow configuration of stream slicers.

## Describe the solution you’d like
Acceptance Criteria:
- An input exists in the stream view allowing users to configure stream slicer for that stream
- The input is optional and defaults to not being configured
- The input's fields are auto-generated from the json schema of the Stream slicer component
- The values entered into this element is propagated to the underlying JSON connector manifest source of truth

**Comment by lmossman** [comment]
Implementation complete. Just need a final review from Joe before merging into the feature branch, which will be merged into master after code freeze

**Comment by flash1293** [comment]
Final review done, just waiting for the code freeze

**Comment by flash1293** [comment]
Merged - cartesian product and substream slicers are split out into its own ticket
