### ISSUE TITLE
[Connector Builder UI] Configurable Pagination

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#19106]
## Tell us about the problem you're trying to solve
Add UI field to the stream view to allow configuration of pagination

## Describe the solution you’d like
Acceptance Criteria:
- An input exists in the stream view allowing users to configure the pagination strategy used for that stream
- The input's fields are auto-generated from the json schema of the Paginator component
- The values entered into this element is propagated to the underlying JSON connector manifest source of truth

**Comment by lmossman** [comment]
Implementation complete. Just need a final review from Joe before merging into the feature branch, which will be merged into master after code freeze

**Comment by flash1293** [comment]
Final review done, just waiting for the code freeze

**Comment by flash1293** [comment]
Merged
