### ISSUE TITLE
[Connector Builder UI] Display errors from the server

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#19101]
## Tell us about the problem you're trying to solve
If the connector builder server encounters an error when processing an API request, this error should be surfaced to the user of the connector builder UI.

For example, the server may throw an error like:
```
{ ERROR: Config validation error: 'access_key' is a required property }
```

## Describe the solution you’d like
If the connector builder server returns an error to the UI, this error should be displayed in the testing panel instead of the results.

**Comment by Upmitt** [comment]
@lmossman is it possible in that case to automatically open the logs, with the error?

**Comment by lmossman** [comment]
Yes that should be doable!

**Comment by lmossman** [comment]
Error types:
- Error in the logs (e.g. underlying API has a failure, such as exceeding rate limit)
  - Successful request to source API which did not lead to a successful read
  - Ideas: 
    - Display exception at the top of the logs drawer, with logs in time order underneath
    - Scroll logs drawer to bottom automatically where exception is
    - Display exception elsewhere (e.g. instead of record display)
- Explicit 400/422 error response (bad user input)
- Internal 500 server error (uncaught server exceptions)
