### ISSUE TITLE
Adopt best practices for Zendesk Support 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1911]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

Since this connector is Singer based, for each of the below items please verify whether:

* the singer tap already implements it
* the singer tap does not implement it and would require forking the tap to implement
* it's something we can implement easily on top of the Singer tap without forking it

**If implementing any of the below items would require forking the Singer tap, please notify sherifnada and move on to the next issue.**

## Checklist
* [ ] Check connection verifies permissions upfront
* [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
* [ ] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to sherifnada with the reason to discuss how to move forward. 
* [ ] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
* [ ] If API connector: implements incremental sync (where possible -- not all streams will allow this)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368210582279) by [Unito](https://www.unito.io)

**Comment by yevhenii-ldv** [comment]
Scoping report:
1) Backoff is not present for Singer `tap_zendesk` library.
2) Incremental sync is implemented.
3) There is no data for the following streams: `satisfaction_ratings`, `tags`, `sla_policies`
4) It is necessary to update the `configured_catalog.json` to support all streams (indicate which `incremental` and which `full refresh`)
5) Сan update and minify the connector code by inheriting from BaseSingerSource and from DefaultStandardSourceTest for tests.

**Comment by sherifnada** [comment]
estimating 8h

**Comment by danieldiamond** [comment]
Assuming this is no longer applicable given we now have a native connector?

**Comment by sherifnada** [comment]
Yes. @danieldiamond did something prompt your question? :) will close this issue

**Comment by danieldiamond** [comment]
haha yeah disabled zendesk connector a while ago because of long normalization times and was curious if it had been updated
