### ISSUE TITLE
[source-facebook-marketing] Add level parameter to custom Ads Insights in source connector facebook-marketing

### ISSUE THREAD

**Issue by carlonuccio** [airbytehq/airbyte#19119]
## Summary
(Choose one of the two below.)
- [X] Update existing type source-facebook-marketing

## TODOs
  - [X] [Issue] support level in custom Ads Insights in source facebook marketing
 
## Desired Timeline
PR opened: https://github.com/airbytehq/airbyte/pull/19116

**Comment by natalyjazzviolin** [comment]
Hey @carlonuccio could you please fill out the standard Issue template we use and edit your original comment to include it?

**Comment by midavadim** [comment]
This feature has been already implemented in PR https://github.com/airbytehq/airbyte/pull/19141
