### ISSUE TITLE
Source LinkedIn Ads: Very slow sync of analytics streams

### ISSUE THREAD

**Issue by darian-heede** [airbytehq/airbyte#19128]
## Environment
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-linkedin-ads:0.1.12
- **Step where error happened**: Sync job

## Current Behavior
Syncing the analytics streams, e.g. the `ad_creative_analytics` stream takes a very long time. Around an hour for syncing 78 records. The logs don't show any rate limiting issues.

## Expected Behavior
I expect the analytics syncs to run way faster than they currently are.

**Comment by sajarin** [comment]
Hey @darian-heede thanks for the issue. Can you share the logs?

**Comment by darian-heede** [comment]
Hi @sajarin , thank you for your quick reply, Here's a sync [log](https://github.com/airbytehq/airbyte/files/9981038/fc3879b8_5ed3_4e51_85aa_9ac01b78e994_logs_1.txt) file.

**Comment by darian-heede** [comment]
Hey @sajarin , do you have any news on this?

**Comment by darian-heede** [comment]
I've looked into this a little closer and can explain why the runtime performance of the `ad_creative_analytics` stream is very slow.

There are two parent streams that are required: first the `campaigns` stream is required to get the campaign id, which in turn is used in the `creatives` stream to get the creative id, which is then finally used in the `ad_creative_analytics` to get the analytics data. 

This process is required by the API design and is what it is. There might be a performance gain by using [[caching](https://docs.airbyte.com/connector-development/cdk-python/http-streams/#nested-streams--caching)](https://docs.airbyte.com/connector-development/cdk-python/http-streams/#nested-streams--caching) when the `campaigns` and `creatives` streams are fetched anyway.

However, the main issue is the following: The two parent streams `campaigns` and `creatives` are no time series streams, which means that the `start_date` configuration is not applied and they will always return all campaigns and all creatives in the given accounts. This also implies campaigns and creatives that have run years ago and do not generate any current data anymore. For these two streams this is fine and expected.

The problem starts when all of these historical campaigns and creatives are used to fetch the `ad_creative_analytics` data. Irrespective of the configured `start_date`, the connector will slice through every historical campaign and creative and execute a call against the API, mostly returning no data.

If the API were quick, we could probably live with this. Unfortunately, the LinkedIn API takes around 2 seconds to process a call. Even if the response is empty because the creative is old and hasn't generated data since the given `start_date`.

I've broken the issue down for my use case:

* we have 3000 creatives in total
* For a `start_date = 2022-12-29` we have 15 creatives that actually return data
* Runtime for the `ad_creative_analytics` is ~45 minutes for what should actually be ~30 seconds.

#### Ideas to solve this

Currently, I see two possible ways of solving this. The `campaigns` stream generates the two dimensions `run_schedule_start` and `run_schedule_end`, which could be used to filter out the campaigns that are relevant to the configured `start_date`:

* Either all campaigns are fetched as they are right now, but filtered based on the `run_schedule` and configured `start_date` dimensions before the campaign ids are passed to the `ad_creative_analytics` stream. For my use case only 12 campaigns would have been passed instead of ~2000.
* Or the `campaigns` stream already filters the `run_schedule` dimensions in the API call, only returning the campaigns that are active since the `start_date` configuration.

I would rather prefer the first option, as the second would imply a breaking change.

**Comment by artem1205** [comment]
It should be much faster, because Connector uses API version `202305` since `0.2.0` without any parent/child relations in `ad_creative_analytics` stream, see https://github.com/airbytehq/airbyte/pull/26372 for more info.

**Comment by bgadrian** [comment]
I am not sure this issue has been solved, and it is even more accentuated when you try to get the historic data, going in the past, the source connector requests for all data points even when the campaign did not existed.

**Comment by onurmus** [comment]
> I am not sure this issue has been solved, and it is even more accentuated when you try to get the historic data, going in the past, the source connector requests for all data points even when the campaign did not existed.

I am having the same problem. These streams take hours to finish.
