### ISSUE TITLE
Source Zendesk-Support - Add new stream user_fields

### ISSUE THREAD

**Issue by gpandolfino** [airbytehq/airbyte#19123]
## Summary
- [ ] Support new stream user_fields 

## TODOs

- [Issue] Allow users to extract data also from user_fields stream using the Zendesk-support connector

## doc Zendesk
https://developer.zendesk.com/api-reference/ticketing/users/user_fields/

**Comment by sajarin** [comment]
@gpandolfino are you willing to create a PR for this new stream?

**Comment by dheerendravarma** [comment]
@sajarin I will work on this new stream for Zendesk support. Can you assign this to me?

**Comment by btkcodedev** [comment]
I would like to take this @jrolom
