### ISSUE TITLE
Adopt best practices for Slack source connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1912]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

Since this connector is Singer based, for each of the below items please verify whether:

* the singer tap already implements it
* the singer tap does not implement it and would require forking the tap to implement
* it's something we can implement easily on top of the Singer tap without forking it

**If implementing any of the below items would require forking the Singer tap, please notify sherifnada and move on to the next issue.**

## Checklist
* [ ] Check connection verifies permissions upfront
* [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
* [ ] Check that every stream has data to read.
* [ ] Check that integration tests validate that every stream outputs data.
* [ ] Check that connector implements backoff logic on hitting rate limits (instead of just failing/exiting)
* [ ] Check if incremental sync works for all stream that declares its support

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368087014848) by [Unito](https://www.unito.io)

**Comment by yevhenii-ldv** [comment]
Scoping report:
1) Backoff is present for Singer `tap_slack` library
2) Incremental works for supported streams (e.g. users)
3) There is no data for the following streams: `user_groups`, `teams`, `remote_files`

**Comment by sherifnada** [comment]
Ticket scope now becomes: 
1. add data for unpopulated streams (may need help from an Airbyter to create them)
2. update configured catalog
3. test

**Comment by sherifnada** [comment]
blocked on #1945

**Comment by sherifnada** [comment]
#1945 has been resolved. This is no longer blocked.

**Comment by davydov-d** [comment]
The connector is no more Singer based, it is now CDK based and adopted to the connector best practices
