### ISSUE TITLE
Drop unnecessary auto-formatting

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1914]
## Tell us about the problem you're trying to solve
Currently, we have two places that auto-formats the code:

* `gradlew format`
* `gradlew build` (probably same as `gradlew <connector>:build`)

Our CI has two places to check if files were changed, after `format` and after `build`.
Even though sometimes I have different results (conflicting) after both commands, it is also contr-productive for developers to have such check-in CI after long-running tasks. 
There should be one command to format code, it should run fast and produce the same result every time. Then it makes sense to put as early as possible in CI and even make a hook for commit (developer's decision). The `build` command, as opposed to the word `fast`, should not modify source code.

## Describe the solution you’d like
Use only `format` to format code.
Build command doesn't modify source code.
CI doesn't check if files have been modified after the build.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368145436430) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
We're not focusing on this for now. Now that the buggy behavior for unit tests has been resolved for formatting this seems like less of an issue.

However, doing a format hook + removing it out of the build step does seem like a good nice-to-have, it's just not high priority right now.
