### ISSUE TITLE
Guide to updating existing connectors

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1919]
## Tell us about the documentation you'd like us to add or update
Received a piece of feedback from someone try to use the tool that the process for making changes to a connector is very easy once you know how to do it, but getting there is hard because we don't document it anywhere. We document how to start from scratch but not how to tweak existing stuff. I think we can add a pretty simple set of docs that will meet the needs of this sort of developer.

> the way I develop alternative plugins is I increase scope of change, so first I hello world into an existing plugin to see if I can impact finished product, then I make a meaningful change, then I start on a new plugin by copying in the scaffolding of the old one, then eventually I make a fresh one devoid of history.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368087169846) by [Unito](https://www.unito.io)

**Comment by YohanGrember** [comment]
Hello team, this is one of the first pages I encounter when I Google "airbyte improve an existing connector"
Does such a documentation exist now?

I'd like to add a few streams to the Stripe Source connector. 😃

**Comment by LuliRib** [comment]
Hi @YohanGrember, did you manage to do so? I need to add one field to the google ads source connector and one to the bing ads source connector, and I have no idea where to start
