### ISSUE TITLE
BigQuery should inform user when user is trying to load too much data via direct upload and not fail

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19196]
BigQuery direct upload API limits data amounts to 10MB per insert. Currently, the connector will fail by running into a timeout trying to upload data to BQ. We should be able to prevent this behavior by identifying that the data amount is too large and chunking it down into 10MB parts and we should also report a warning to the user explaining that they should use staging for the amounts of data that they are pushing through.

Some examples of users having trouble with large inserts:
* https://github.com/airbytehq/airbyte/issues/3549
* https://github.com/airbytehq/oncall/issues/575

**Comment by edgao** [comment]
I’m actually not sure this issue is accurate? I inserted a few gigantic records into a snowflake table (2x 10MB, and 1x 16.7MB), and synced that via standard inserts to bigquery. Sync looks fine, and data looks correct. https://cloud.airbyte.io/workspaces/46b4844a-94a3-496f-af53-2050bf4141af/connections/744e3521-f37c-4a2b-a37e-eebf590d5f3b/status

**Comment by grishick** [comment]
I was referring to this documentation: https://cloud.google.com/bigquery/quotas#streaming_inserts where it says that maximum row size is 10MB:
![Screen Shot 2023-01-03 at 1 15 59 PM](https://user-images.githubusercontent.com/1310940/210442680-8aa20808-87b3-4d04-8180-3f2fa02c8983.png)

**Comment by grishick** [comment]
Notes from grooming:
 - need to reproduce this in a controlled environment to know the exact exception
 - we may be running into a timeout if it takes too long to upload data

**Comment by grishick** [comment]
Could not reproduce the issue. Closing until it comes up again.
