### ISSUE TITLE
how to update schema before  connection is setup between source and destination. 

### ISSUE THREAD

**Issue by siddhant3030** [airbytehq/airbyte#19203]
## Environment
Latest
MacOS
Deployment
SurveyCTO beta:
Postgres latest
Sync job

## Current Behavior
source code is here
https://github.com/DevDataPlatform/airbyte/blob/3dd9d9ac6b4713e4bbf0566bcc0a7218430c2e53/airbyte-integrations/connectors/source-surveycto/source_surveycto/source.py

I have a custom connector as a source and with that source, we are trying to pull the data from the API and push that to Postgres which is our destination. So because we are just pushing the JSON raw into DB we want to do basic normalization. But we need to make it dynamic so that we are doing as soon as we get the data we create a schema out of it. and then we try to update the get_json_schema function.

 But the problem I’m facing is if at the start we make a connection as empty properties later we cannot change that. So how do I update the get_json_schema to take my schema instead of the empty one after making the connection or during the sync it can update it.
 
 So we tried two solutions:-

1. First if you look at the get_json_schema function we are waiting for the data to come in response.json then we pull the schema out of it and now what we want when the normalization runs needs to update the dump_schema empty onto the schema it just got.

 ```
 def get_json_schema(self):
        if hasattr(self, 'response_json'):
            generator = SchemaGenerator(input_format='dict', infer_mode='NULLABLE',preserve_input_sort_order='true')
            data = self.response_json
            schema_map, error_logs = generator.deduce_schema(input_data=data)
            schema = generator.flatten_schema(schema_map)     
            schema_json = converter(schema)
            dump_schema=schema_json['definitions']['element']['properties']

        else:
            dump_schema = {} 
            print(f'---------empty------------------{dump_schema}')
        
        return {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "additionalProperties": True,
            "type": "object",
            "properties": dump_schema,
        }
```

2. For Another solution I'm doing the same API call again and get the data then from that data we create schema out of it and then pass it to the stream. But API doesn't support parallel requests which we are using in the source. 

So I want to understand when we make a connection why it's calling the source API at the start. Because of that, I'm not able to make another call just before the stream. 

You can check the code here

https://github.com/DevDataPlatform/airbyte/blob/3dd9d9ac6b4713e4bbf0566bcc0a7218430c2e53/airbyte-integrations/connectors/source-surveycto/source_surveycto/source.py#L129

<img width="1077" alt="Screenshot 2022-11-09 at 12 41 50 PM" src="https://user-images.githubusercontent.com/9019958/200763149-7cdb7d51-3a90-405a-b448-4acd31a92f74.png">

3. the Third solution which I figured out is to put a time delay of 10 seconds between them. Which works somehow but not that smoothly. Sometimes it fails. But that time it validates the schema and schema which we are using its not letting us use that. 

and we get an error like this 

`2022-11-09 08:51:45 ERROR i.a.w.i.DefaultAirbyteStreamFactory(validate):84 - Validation failed`

<img width="1233" alt="Screenshot 2022-11-09 at 2 24 21 PM" src="https://user-images.githubusercontent.com/9019958/200785402-80b5c41a-6885-4749-a014-ecca2cbcd3f6.png">

## Expected Behavior
update the schema when we do the normalization

**Comment by natalyjazzviolin** [comment]
@siddhant3030 as this is a question and not a specific bug you are running into, this would be more appropriate to ask in the forum or Slack channel. I'm closing this issue, please make a post in either one of those resources!
