### ISSUE TITLE
Destination Meilisearch: incomplete data indexed

### ISSUE THREAD

**Issue by CaroFG** [airbytehq/airbyte#19205]
## Environment
- **Airbyte version**:  0.40.18 
- **OS Version / Instance**: macOs
- **Deployment**: Docker
- **Source Connector and version**: MySQL v1.0.11 
- **Destination Connector and version**: Meilisearch v1.0.0 
- **Step where error happened**: Sync job (although it says 'succeeded')

## Current Behavior
The operation appears as successful: "Sync Succeeded" but only one table of my database is synced (the first on the list). 
All the indexes are created in Meilisearch (each corresponding to a MySQL table) but only one contains documents.
I have checked Meilisearch tasks, and only one task of type `documentAdditionOrUpdate` exists.

## Expected Behavior
All data should have been indexed in Meilisearch.

## Logs

[airbyte_sync_4a59f152_262a_40ed_b27a_83f029b8a05e_logs_1.txt](https://github.com/airbytehq/airbyte/files/9969485/airbyte_sync_4a59f152_262a_40ed_b27a_83f029b8a05e_logs_1.txt)

## Steps to Reproduce
1. Create a connexion between MySQL and Meilisearch
2. Try to sync several tables of a database
3. When sync says 'succeeded' check Meilisearch, all indexes corresponding to the tables have been created, but only one contains documents. Check Meilisearch tasks, only one documentAddition task exists.

**Comment by davidbaselj** [comment]
Did anyone looked at this issue or found solution to this because I have exact same problem ?

I have tested:
MsSQL -> Meilisearch
MsSQL -> Typesense

In both cases all the indexes are created but then all rows from all tables are thrown (indexed) in single index/collection

**Comment by sajarin** [comment]
@davidbaselj, I believe this issue still exists. It's on the team's backlog but it may be some time before we're able to fix it.

**Comment by pengdaqian2020** [comment]
I use:
PgSQL  -> Typesense

In both cases all the indexes are created but then all rows from all tables are thrown (indexed) in single index/collection

@sajarin

**Comment by alallema** [comment]
Hi,
I'm looking into this issue. 😊
