### ISSUE TITLE
Postgres Source Strict Encrypt: Allow connections with sslmode allow and prefer if SSH tunnel established

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#19211]
## Tell us about the problem you're trying to solve
In _strict-encrypt_ connector, if SSH is turned on and _ssl_mode_ is **prefer** or **allow** check connection will fail in case of Postgres Server does not support SSL connections

this happens for the reason that we have a hard-coded 
```
  static final Map<String, String> SSL_JDBC_PARAMETERS = ImmutableMap.of(
      "ssl", "true",
      "sslmode", "require");
```
and even if the user chooses _ssl_mode_  **allow** or **prefer**  during connector setup, the ssl_mode **require** will always be used, which will lead to a connection error 

## Describe the solution you’d like

If SSH tunnel established we should enforce correct ssl mode chosen by user and the connection must be successful both for servers that support SSL and for those that do not support SSL

[Postgres docs](https://www.postgresql.org/docs/current/libpq-ssl.html#:~:text=SSL%20Mode%20Descriptions-,sslmode,-Eavesdropping%20protection)

**Comment by bleonard** [comment]
Make sure the tests are legit!

**Comment by klsoper** [comment]
Just wanted to check, this issue could be causing this error?

`State code: 08004; Message: The server does not support SSL."` for postgres source setup

**Comment by VitaliiMaltsev** [comment]
> Just wanted to check, this issue could be causing this error?
> 
> `State code: 08004; Message: The server does not support SSL."` for postgres source setup

@klsoper yes, exactly

**Comment by klsoper** [comment]
thank you!

**Comment by erica-airbyte** [comment]
@VitaliiMaltsev has the fix been pushed?

**Comment by klsoper** [comment]
looks like its still being worked on- [not merged yet](https://github.com/airbytehq/airbyte/pull/19551)

**Comment by VitaliiMaltsev** [comment]
@erica-airbyte @klsoper it wasn't merged due to code freeze, master branch is locked, i can't merged it yet

**Comment by VitaliiMaltsev** [comment]
@klsoper merged

**Comment by klsoper** [comment]
![Screen Capture error](https://user-images.githubusercontent.com/100706692/204858862-f1a9b1e2-43ce-408b-b140-eb47b6ec6901.png)
Hey @VitaliiMaltsev I have a customer still seeing this- is it the same issue? Do they need to do anything on their end to get this successful or is it a seperate issue I need to create?

**Comment by VitaliiMaltsev** [comment]
@klsoper it is expected behaviour because he used ssl mode require. In this case Postgres server reject all non-ssl connection
Option 1
User should choose one of _disable, allow, prefer_ ssl modes and setup SSH tunnel for secure connection
Option 2
User should enable SSL on Postgres Server

**Comment by klsoper** [comment]
Thank you @VitaliiMaltsev !
