### ISSUE TITLE
Connection name is still active after clicking outside and the name has not been changed

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19229]
## Actual 

When clicking outside the connection name without editing, it stays in the edit mode.

## Expected

When clicking outside the connection name without editing, it should leave the edit mode.

## Steps to reproduce

1. Navigate to a connection
2. Click on the name
3. Click outside of the name

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
