### ISSUE TITLE
Source-Pinterest: Check method returns error while using access token authentication in config

### ISSUE THREAD

**Issue by kavyabharathappa** [airbytehq/airbyte#19235]
## Environment
- **OS Version / Instance**: macOS
- **Deployment**: Docker 
- **Source Connector and version**: source-pinterest:0.1.9
- **Step where error happened**: Setup new connection 

## Current Behavior
Returns failure status with an error message

## Expected Behavior
Returns `{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "SUCCEEDED"}}`

## Logs
```
{"type": "LOG", "log": {"level": "ERROR", "message": "Check failed"}}
{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "FAILED", "message": "TypeError(\"unsupported operand type(s) for +: 'NoneType' and 'str'\")"}}

```
## Steps to Reproduce
1. Create config file for pinterest with access_token authentication type
2. Run the check method

**Comment by erohmensing** [comment]
+1, I see this still in version 0.2.1.

**Comment by Alihassanc5** [comment]
@kavyabharathappa @marcosmarxm After investigating this issue, I realized that this code only checks for OAuth2.0 authentication, not access token authentication. Additionally, this error occurs when the optional fields, client_id and client_secret, are empty. This can be resolved by making them required fields or by refactoring some of the logic to handle this scenario.

**Comment by dromix** [comment]
Hello guys, any updates according to this bug?
