### ISSUE TITLE
Enabling Basic Normalization yields JSON syntax error

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#1923]
## Expected Behavior
When I turn on Basic Normalization, clicking [Save changes] should save the settings with Basic Normalization enabled.

## Current Behavior
The message `com.fasterxml.jackson.core.JsonParseException`... appears.  See the screenshot below.

## Steps to Reproduce
1. Create a BigQuery destination with "Basic Normalization" off.
1. Open the Settings for the BigQuery destination you just created.
1. Turn on the "Basic Normalization" switch.
1. Click [Save changes].

## Severity of the bug for you
High

## Airbyte Version
VERSION=0.14.1-alpha

## Additional context
Running on an Amazon EC2 instance (Amazon Linux 2 AMI).

![image](https://user-images.githubusercontent.com/236086/106515231-39a04000-648a-11eb-8df9-bb80ecdf0511.png)

**Comment by zestyping** [comment]
When I expand "Failed Logs", here's what I see:

![Uploading image.png…]()

**Comment by zestyping** [comment]
Further testing revealed that this error also happens when flipping "Basic Normalization" from on to off.  It does not happen when I create a new destination with "Basic Normalization" on; it only seems to happen when I edit the settings for an existing BigQuery destination.

Thanks for looking into this!

**Comment by michel-tricot** [comment]
@zestyping you need to copy and paste the whole key file into the field.

The content looks like that:
```
{
  "type": "service_account",
  "project_id": "redacted",
  "private_key_id": "redacted",
  "private_key": "-----BEGIN PRIVATE KEY-----redacted\n-----END PRIVATE KEY-----\n",
  "client_email": "redacted@redacted.iam.gserviceaccount.com",
  "client_id": "redacted",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/demo-bigquery%40redacted.iam.gserviceaccount.com"
}
```

**Comment by michel-tricot** [comment]
I am going to close, feel free to re-open if it doesn't fix it.

**Comment by zestyping** [comment]
Hey @michel-tricot, thanks for looking at this so fast!

I didn't touch the credentials field at all — but thanks for pointing that out, as I think it explains the cause of the problem.  When I open the Settings page, the credentials field is getting prefilled with `**********` (which I assume is done to avoid sending sensitive credentials back over to the browser), and yet `**********` is rejected upon submission.

I think the form should keep track of whether the user has touched the credentials field, and if it hasn't been touched, then it should leave the existing credentials unchanged without attempting to parse the field value.

**Comment by zestyping** [comment]
@michel-tricot It looks like GitHub won't allow me to re-open this issue because I'm not a collaborator on the project. Could you re-open it?

Thanks!

**Comment by michel-tricot** [comment]
You're right @zestyping, you should be able to update and we've made changes recently to enable it. @cgardens do you know if we've released it?

In the meantime to unblock you, you can delete and recreate your destination.,

**Comment by zestyping** [comment]
Yep, that workaround is good for now.  Thanks!
