### ISSUE TITLE
Show affected connections/sources/destinations on delete

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#19237]
A [p0](https://airbytehq-team.slack.com/archives/C03AS1GAQV6/p1668014071550469) popped up where a user deleted a very important destination.
A helpful way to mitigate that would be to show affected sources/destinations/connections before allowing the delete.

**Comment by colesnodgrass** [comment]
If the data is not available, talk to Andy and go from there.

**Comment by edmundito** [comment]
There is already a modal that warns the user before deletion but does not list out the connectors that will be impacted by the deletion.
