### ISSUE TITLE
Updates for edit password field in connector:

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19233]
Requested by @Upmitt 

* Cancel button should be on the left side
* There should be a gap between buttons
* Edit button should be outline
* Edit button height should match text input height

Current:

![Screen Shot 2022-11-09 at 11.47.21.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/fabda91a-8d98-472e-94aa-3f2efa458195)

![Screen Shot 2022-11-09 at 11.47.28.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/0ae93e68-b0c7-46b3-9ed6-28ca4238c2f9)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by natalyjazzviolin** [comment]
@edmundito , Sherif assigned this one to me as part of the low-code framework effort.
I have a few questions before I dive in, could you clarify these? I used an API key field as an example as it looks like it has the same functionality as a password field.

Cancel/Done buttons:

Does this look like the correct approach?

<img width="391" alt="Screen Shot 2022-11-21 at 9 59 53 AM" src="https://user-images.githubusercontent.com/65251165/203087120-37c913af-695c-470f-bf37-8f43ed3e90e7.png">

Edit button:
1. We don't have a primary outline style for the button component. Would the secondary be appropriate here?
2. The button component does not have a height prop. Would it be better to adjust the height for all buttons so they are uniform? Would it be cleaner to implement a prop? ( I was estimating height in devtools, so apologies that it's slightly off!)

<img width="392" alt="Screen Shot 2022-11-21 at 9 57 29 AM" src="https://user-images.githubusercontent.com/65251165/203086524-4615ff4f-aa93-45eb-9529-f51c5174c2ee.png">

**Comment by edmundito** [comment]
@natalyjazzviolin I was unaware that the API key and Password field had different edit modes. both should look the same, and API has the correct approach. From the screenshot above, there should be a gap between the input and the cancel button.

For the Edit button:
1. The secondary is what we want, just like the API key
2. Height: Let's review this with Nico to confirm what is intended.
