### ISSUE TITLE
Normalization should set application ID in JDBC param

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19251]
as described in https://airbytehq-team.slack.com/archives/C046LMDDY6N/p1666972075127309

Normalization should set the JDBC URL param application to airbyte_cloud or airbyte_oss when talking to Snowflake. Relevant docs: https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup#all-configurations

**Comment by jwertherUM** [comment]
Hey is this still up for grabs? I'm pretty new to open source but I'd love to give it a shot

**Comment by evantahler** [comment]
When this issue is closed, we can complete the epic https://github.com/airbytehq/airbyte/issues/18626

**Comment by evantahler** [comment]
Closing this issue as https://github.com/airbytehq/airbyte/issues/26028 removes normalization as we know it
