### ISSUE TITLE
Redshift destination treats destination tables as having significant case, but Redshift is case-insensitive

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#1926]
## Expected Behavior

Redshift destination connector is aware of the fact that:

> ASCII letters in standard and delimited identifiers are case-insensitive and are folded to lowercase in the database

and so the 'cleaned name' is always lowercased.

## Current Behavior

The initial sync will succeed because it thinks it made the case-sensitive name `ApprovedUsers` but on further attempts it will find `approvedusers` present when looking for `ApprovedUsers` and log the following and fail.

```
2021-02-02 00:21:12 INFO (/tmp/workspace/496/2) LineGobbler(voidCall):69 - When searching for a relation, dbt found an approximate match. Instead of guessing
2021-02-02 00:21:12 INFO (/tmp/workspace/496/2) LineGobbler(voidCall):69 - which relation to use, dbt will move on. Please delete "placekey"."public"."approvedusers", or rename it to be less ambiguous.
```

## Steps to Reproduce
1. Create a Google Sheets worksheet with a sheet named something case-significant like ApprovedUsers
1. Use the Google Sheets connector as a source for that sheet
1. Use the Redshift destination connector as a destination for that data

## Severity of the bug for you
Low - I worked around it by renaming my sheet

## Airbyte Version
I'm using an off-`master` version by @cgardens with rev `e463fa7dbff516f619c02d752d81307c5ee1b20c`.

## Additional context
No additional context should be required to reproduce

**Comment by sherifnada** [comment]
@roshan thanks for reporting this issue, we'll release a fix shortly.

**Comment by ChristopheDuong** [comment]
The Name Transformer class for Redshift is theoretically handling this as it always lowercase table names whether it is `standard or delimited identifiers`:

https://github.com/airbytehq/airbyte/blob/5dfd81a1cd78f11e1e2c8f91a76d01fca14b2ced/airbyte-integrations/connectors/destination-redshift/src/main/java/io/airbyte/integrations/destination/redshift/RedshiftSQLNameTransformer.java#L33

I am guessing the bug is on the normalization side where this logic doesn't exist for Redshift

**Comment by cgardens** [comment]
This is code complete, but may conflict with changes that @ChristopheDuong is making for supporting nesting. The nesting issue is higher priority, so this PR https://github.com/airbytehq/airbyte/pull/2023 is going to be on hold until that is merged.

**Comment by cgardens** [comment]
This should now be fixed by https://github.com/airbytehq/airbyte/pull/2044
