### ISSUE TITLE
Hubspot Missing Cursors

### ISSUE THREAD

**Issue by ryjabe** [airbytehq/airbyte#19265]
## Expected Behavior
As a GA connector, Hubspot should have a cursor enabled for all possible streams.  From some cursory scoping it appears a few streams are missing cursors.  Below is that list for Hubspot (stream_name:cursor_name)

Streams with possible Cursors:
**campaigns**: lastUpdatedTime
**deal_pipelines**: updatedAt
**form_submissions**: updatedAt
**forms**: updatedAt
**owners**: updatedAt
**ticket_pipelines**: updatedAt
**workflows**: updatedAt

The request here is if possible to add cursors for the above streams. 
@YowanR FYI

**Comment by YowanR** [comment]
Thanks Ryan! I'm wondering what's the urgency on this?
@lazebnyi Since this is a GA connector, could the team do a quick vet on this issue as well as [this one](https://github.com/airbytehq/airbyte/issues/19266)? Ideally < 30 mins, but not more than 1 hour max to understand the issue (was it an omission or can we not support them?) and report back? We can then prioritize accordingly.

**Comment by ryjabe** [comment]
Probably medium to medium-low (if that's a thing)?  I don't think it's worth bumping timelines, but given its GA we want to make sure it's optimized and running efficiently for all of our users.

**Comment by ryjabe** [comment]
Since this was posted we had someone reach out with this being a blocker/problem for them.  I'd say let's dial up the urgency a little bit as a result.   Would love to see an update if there is one.

**Comment by YowanR** [comment]
Cc @lazebnyi @YuliiaNahoha let's target next sprint as part of our on going GA work.

**Comment by YowanR** [comment]
@lazebnyi @YuliiaNahoha Bump on this one -- can we make sure we fit this into our sprint? adding to our backlog.

**Comment by YowanR** [comment]
@lazebnyi @YuliiaNahoha Bump on this one -- can we make sure we fit this into our sprint? adding to our backlog.

**Comment by ryjabe** [comment]
Adding a few more:
property_history
contacts_list_memberships

@YowanR can we get an update here.  

@rsharp200 fyi

**Comment by YowanR** [comment]
The code freeze is currently in progress so I'd suggest we try to land this early January. @lazebnyi @YuliiaNahoha can we slot this into the current sprint ?

**Comment by rsharp200** [comment]
@YowanR Is there an ETA on when these streams will be updated?

**Comment by rsharp200** [comment]
The customer who requested these streams be updated did so because Fivetran is able to do incremental syncs on these streams. How are they doing it if we can't?

**Comment by YowanR** [comment]
Hmm, this is surprising. It seems that this issue will require further investigation but at this point, this feels more like an enhancement that we are not able to support rather than a bug. @lazebnyi can you comment on @rsharp200's comment above?

**Comment by YowanR** [comment]
@lazebnyi Can you please follow-up here? Would like to get to the bottom of this issue

**Comment by lazebnyi** [comment]
@YowanR Ok, we will plan it to the next sprint.

**Comment by YowanR** [comment]
Let's do a high level research just to understand what could be done to enable this. We'll discuss implementing it in Q1b. Thanks!

**Comment by lazebnyi** [comment]
@YowanR I was check Fivetran [doc](https://fivetran.com/docs/applications/hubspot) and didn't find that it support incremental sync for those streams. Maybe user mean Capture deletes feature wich we doesn't sopport.

**Comment by YowanR** [comment]
@ryjabe @rsharp200 can you take a look at this? We did our research and it seems that fivetran doesn't support incremental.

**Comment by rsharp200** [comment]
Thanks for looking into this! Yep, I will ask the customer to double check these streams...

**Comment by artem1205** [comment]
Incremental support added in https://github.com/airbytehq/airbyte/pull/24711/
