### ISSUE TITLE
Scope lowcode UI v1 backend items

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19263]
# Acceptance Criteria
- A scoped list of the backend tickets required to power the v1 PRD requirements (https://docs.google.com/document/d/1gbZufczSsR2VuUw6z6oDn7iDmG7xt06_GiZ6wYrrmk4/edit#heading=h.agrxfsjj7zsy)

**Comment by sherifnada** [comment]
only two issues we can think of atm: 
- only returning specific pages/slices
- Get alignment on if & how the openAPI spec evolves for v1

**Comment by sherifnada** [comment]
I reviewed the PRD v1 requirements. The issues I think we will need to support v1: 

**hard requirements**
- [ ] Support for specifying stream schemas in the UI and sending it to the backend
       The current frontrunner approach is bundling schema definitions into the manifest, but it doesn't have to be implemented that way. 
- [ ] support limiting number of pages / records retrieved from connector builder server

**later**
* Support fetching a specific single page and/or slice, to allow users to test read page-by-page for better performance

**Comment by sherifnada** [comment]
@lmossman I'd like to close this issue with the above comment. LMK if you have any feedback by thursday sprint planning please.

**Comment by lmossman** [comment]
@sherifnada I left a comment on #19500 but otherwise I think this looks good

**Comment by sherifnada** [comment]
responded there, thanks for the response!
