### ISSUE TITLE
Destination ClickHouse: doesn't have a logo

### ISSUE THREAD

**Issue by mshustov** [airbytehq/airbyte#19283]
- **Airbyte version**:  Airbyte cloud
- **OS Version / Instance**: macOS
- **Deployment**: Airbyte cloud
- **Destination Connector and version**: 0.2.0
- **Step where error happened**: Create a new ClickHouse destination

## Current Behavior
The ClickHoise logo is not rendered. 
![2022-11-10_14-03-02](https://user-images.githubusercontent.com/3198181/201098699-083d4fbc-e83e-4159-b3e0-228f4f4d7c20.png)

I expected https://github.com/airbytehq/airbyte/pull/17483 to fix the problem.
@grishick  Shouldn't it be updated automatically as per https://github.com/airbytehq/airbyte/pull/16970#pullrequestreview-1120805057 ?
Should we add an icon here? https://github.com/airbytehq/airbyte/blob/1b134d866fe69b6ae7a148b2d328416749f86031/airbyte-config/init/src/main/resources/seed/destination_definitions.yaml#L67-L72

## Are you willing to submit a PR?
Yes, if someone helps me to understand what should be changed.

**Comment by juweins** [comment]
I figured out there was a missing icon attribute and a typo in the relevant files.
(Excuse the mess in that commits, I had to get rid of another issue which I have not yet solved)

**Comment by mshustov** [comment]
fixed
