### ISSUE TITLE
`source-github` has many timestamps as strings that should really be "date-time"

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#19298]
In `source_github/schemas/events.json`
* `created_at` should gain `"format": "date-time"`

In `source_github/schemas/workflow_runs.json`
* `created_at` should gain `"format": "date-time"`
* `updated_at` should gain `"format": "date-time"`

**Comment by evantahler** [comment]
FYI @alex-gron

**Comment by alex-gron** [comment]
@evantahler  What does this mean for our existing Github connections? Will they continue to ingest timestamps as strings until we update the schema and/or trigger a reset?

**Comment by evantahler** [comment]
> @evantahler What does this mean for our existing Github connections? Will they continue to ingest timestamps as strings until we update the schema and/or trigger a reset?

Yep - things will remain as strings until (A) reset (B) we manually adjust the column type & values
