### ISSUE TITLE
Destination: S3 - Extraction from File to S3 - Failed to convert JSON to Avro: Could not evaluate union

### ISSUE THREAD

**Issue by jkleinkauff** [airbytehq/airbyte#19300]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: File 0.2.30
- **Destination Connector and version**: Destination 0.3.17
- **Step where error happened**: Sync job / Extraction
## Current Behavior

I'm trying to read a csv file(gz) and extract to S3 as a parquet file.
Extraction is failing with the following error:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/58440667/201185086-a15a5e4a-a8e9-4c41-8f55-7107a9519183.png">

## Expected Behavior

The extraction to complete without errors.

## Logs
[db2555aa_ef01_48cc_aac0_9ea00a4cec65_logs_56_txt.txt](https://github.com/airbytehq/airbyte/files/9983952/db2555aa_ef01_48cc_aac0_9ea00a4cec65_logs_56_txt.txt)

## Steps to Reproduce
1. Set a new File Source with the following config
<img width="547" alt="image" src="https://user-images.githubusercontent.com/58440667/201182622-f2d880c3-deeb-470a-ad33-66249fe1baf8.png">
2. Set a S3 destination with the following config
<img width="565" alt="image" src="https://user-images.githubusercontent.com/58440667/201184118-e99fd540-afec-49db-9bb7-32aa875d9115.png">

## Are you willing to submit a PR?
<!--- 
We accept contributions! 
Don't feel pressured, but if you want to contribute we can help you by giving some tips, 
highlighting the necessary code change or explaining any relevant point your feature will impact.
You can also send questions on #dev Slack channel.

We understand if you can't submit a PR and we're tremendously grateful
that you've already contributed by suggesting a new feature.
Yes

**Comment by artem1205** [comment]
Seems to be a destination problem, see https://github.com/allegro/json-avro-converter/issues/59
