### ISSUE TITLE
[Source-MSSQL] Invalid binary data 

### ISSUE THREAD

**Issue by kuleshov01** [airbytehq/airbyte#19337]
## Environment
- **Airbyte version**:  latest
- **OS Version / Instance**: ubuntu 20.04.1
- **Deployment**:  Docker
- **Source Connector and version**: Microsoft SQL Server (MSSQL) latest
- **Destination Connector and version**: Clickhouse latest
- **Step where error happened**: Converting binary data to string from source connector

## Current Behavior
![image](https://user-images.githubusercontent.com/62784748/201276879-8372f506-7920-4c9c-b31e-960d6116d928.png)

That 's what mssql shows me

![binary](https://user-images.githubusercontent.com/62784748/201270448-9b101b1b-6e9d-4834-86d4-10db8c2a0bff.jpg )
And this is the received data already in clickhouse

![clickhouse](https://user-images.githubusercontent.com/62784748/201270424-b46707a9-282b-4fc8-9e96-49544e825a31.jpg )

As a result, I get the same string values _IDRRef, although they should be different

In general, I do not understand the translation of airbyte binary data into a string, if you use a regular hex editor, you should get these characters
![image](https://user-images.githubusercontent.com/62784748/201276438-cf3ff026-351d-41d7-97bb-4b36ae933776.png )
But it turns out this line: ��\u0000PV�w�\u0011�}$e\u001A�

## Expected Behavior
The data in the _IDRRef column should be different

## Logs
[f2c30996_e3f4_464b_8dfb_fb642b7f10d9_logs_10_txt.txt](https://github.com/airbytehq/airbyte/files/9986476/f2c30996_e3f4_464b_8dfb_fb642b7f10d9_logs_10_txt.txt)

## Steps to Reproduce
1. Create a source connector for mssql tables with binary data
2. Set up transmission to any clickhouse location
3. Compare the data

## Are you willing to submit a PR?
No

## Decision.
Most likely the problem is the length of the binary used to convert to a string

**Comment by NipunaPrashan** [comment]
I am having the same issue.
Airbyte version: 0.40.32

**Comment by NipunaPrashan** [comment]
@natalyjazzviolin @sherifnada do you have any update for this issue?

**Comment by NipunaPrashan** [comment]
This issue is not occurring in MSSQL 0.3.8 connector.
Seems like 0.3.9 version is the culprit.

@djshura2008 @natalyjazzviolin @sherifnada

**Comment by NipunaPrashan** [comment]
@sajarin @rodireich @marcosmarxm for your attention as the PR to fix this issue is closed without any response.

**Comment by xiaohansong** [comment]
Current implementation is to convert `byte[]` read from DB to String using the following statement:

```
 final byte[] bytes = resultSet.getBytes(index);
 final String value = new String(bytes, Charset.defaultCharset());
```

We might need to discuss the best way to do this. In our doc we did not call out specifically how we want to handle binary fields so we need a definition before proceeding the fix.
 
https://docs.airbyte.com/understanding-airbyte/supported-data-types#the-types
