### ISSUE TITLE
Google Search Console - Service Account Key Authentication Failure

### ISSUE THREAD

**Issue by sbrickel-nimble** [airbytehq/airbyte#19343]
## Environment
- **Airbyte version**:  0.40.16
- **OS Version / Instance**: Debian GNU/Linux 10 VM instance
- **Deployment**: Docker
- **Source Connector and version**: Google Search Console	0.1.18
- **Destination Connector and version**: BigQuery 1.2.5
- **Step where error happened**:   Setup new connection  
- 
## Current Behavior
The connection tests failed.
"Unable to connect to Google Search Console API with the provided credentials - KeyError('siteEntry')"

## Expected Behavior
Setting up connection

## Logs
NA

## Steps to Reproduce
1. Setup GSC as described in Setup Guide
2. Click "Setup source"
3.

## Are you willing to submit a PR?
Sure

**Comment by sbrickel-nimble** [comment]
In the end the issue is due to a mistake in the connector help info. It says 

> Website URL Property
> The URLs of the website property attached to your GSC account. Read more here.
> Example values
> https://example1.com/ https://example2.com/

This should be changed to

> Website URL Property
> The URLs of the website property attached to your GSC account. Read more here.
> Example values
> https://example1.com/ sc-domain:example2.com

and maybe also link this [site](https://developers.google.com/webmaster-tools/v1/sites/add)

Important to note is that as a prerequisites one has to enable enable Google Search Console API.

**Comment by sbrickel-nimble** [comment]
Ok, so in the end it seems that the confusion is due to a mistake in the info window of the connector it says:

> Website URL Property
> The URLs of the website property attached to your GSC account. Read more here.
> Example values
> https://example1.com/ https://example2.com/

should be changed to

> Website URL Property
> The URLs of the website property attached to your GSC account. Read more here.
> Example values
> https://example1.com/ sc-domain:example2.com

and maybe also link this [site](https://developers.google.com/webmaster-tools/v1/sites/add)

Prerequisites:
Enable Google Search Console API

I can claim this issue and submit a PR

**Comment by natalyjazzviolin** [comment]
@sbrickel-nimble looking forward to the PR!

**Comment by dictcp** [comment]
We encountered similar troubleshooting steps and would like to contribute on the documentation to save new comers' troubleshooting time.

**Comment by dictcp** [comment]
it would be great if either @natalyjazzviolin or @marcosmarxm can visit the PRs
