### ISSUE TITLE
Jira stream issues always is 0

### ISSUE THREAD

**Issue by Arthurlandia** [airbytehq/airbyte#19347]
## Environment
- **Airbyte version**:  example is 0.40.18
- **OS Version / Instance**: macOS Monterey 12.2.1
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.3.0
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**:  Sync job

## Current Behavior
I am executing all tables, but in issues and issue_worklogs always I am getting 0 rows. In other tables I am getting info and is working fine.

## Expected Behavior
Should be getting info and registering into PostgreSQL.

## Steps to Reproduce
1. Choose the tables in any mode (Full refresh, overwrite), the number of rows got always is 0.
2. Execute "Sync now" button

## Are you willing to submit a PR?
No

**Comment by bala-ceg** [comment]
@marcosmarxm i would like to work on this issue

**Comment by natalyjazzviolin** [comment]
@bala-ceg feel free to take it on!

**Comment by grubberr** [comment]
closed because of https://github.com/airbytehq/airbyte/pull/20128
