### ISSUE TITLE
Fix Source Google Ads: Change type of data in fields `metrics.conversions` and metrics.conversions_value` from `integer` to `double`

### ISSUE THREAD

**Issue by mutt-santiago-stachuk** [airbytehq/airbyte#19355]
## Tell us about the problem you're trying to solve

I've submitted a PR for Google Ads source connector but @pietrobon found this:

#https://github.com/airbytehq/airbyte/pull/18069#issuecomment-1310331728

## Describe the solution you’d like
Change type of data in fields `metrics.conversions` and metrics.conversions_value` from `integer` to `double`

## Describe the alternative you’ve considered or used
-

## Are you willing to submit a PR?

Yes!

**Comment by sajarin** [comment]
@mutt-santiago-stachuk thanks for the issue, we'd be happy to review your PR!

**Comment by sherifnada** [comment]
@tolik0 are you addressing this as part of cert?

**Comment by tolik0** [comment]
Fields **_metrics.conversions_** and  **_metrics.conversions_value_** have type - **_number_** in all schemas
