### ISSUE TITLE
Prestashop sync job "freeze" after a few hundred thousand rows processed

### ISSUE THREAD

**Issue by marcuslind90** [airbytehq/airbyte#19362]
## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**: macOS
- **Deployment**: Kubernetes (Helm Chart)
- **Source Connector and version**: Prestashop 0.2.0
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Sync Job

## Current Behavior
Sync job runs for anywhere between 1-3 hours and suddenly stop processing anything, and essentially "Freeze". Log are updated every few seconds until moment where it freeze, and log output is frozen for hours with no error or additional debug information appended to it.

I've re-run the sync many times, I've also tried deactivating some of the feeds but it still happens. E.g. it has happened while syncing Addresses, Orders, Carts etc. It's not just a single dataset failing.

## Expected Behavior
That Sync Job completes and continuously give me updates.

## Logs

[a0701d96_531c_4b18_9314_c15b076cd883_logs_1_txt.log](https://github.com/airbytehq/airbyte/files/9995883/a0701d96_531c_4b18_9314_c15b076cd883_logs_1_txt.log)

## Steps to Reproduce
1. Install Docker Desktop + Kubernetes on localhost.
2. Deploy Airbyte Helm Chart ~0.40.40
3. Setup Prestashop Source
4. Setup Postgres destination
5. Trigger sync job
6. After a few hundred thousands rows are synced, job stop progressing without raising error, until manually canceled.

**Comment by marcuslind90** [comment]
This was unrelated to the Prestashop connector. The issue was that the `PersistentVolumeClaim` of the postgres Kubernetes pod was not large enough to fit some of these larger datasets, instead of raising an error, Airbyte was just frozen for hours.

I would expect it to raise an "No space left on device" error.

**Comment by natalyjazzviolin** [comment]
@marcuslind90 glad you got this resolved and thanks for the update. Please open a feature request for that error message!
