### ISSUE TITLE
Adopt connector best practices for Google Analytics

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1937]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

Since this connector is Singer based, for each of the below items please verify whether:
- the singer tap already implements it
- the singer tap does not implement it and would require forking the tap to implement
- it's something we can implement easily on top of the Singer tap without forking it

**If implementing any of the below items would require forking the Singer tap, please notify @sherifnada and move on to the next issue.** 

## Checklist
- [ ] Check connection verifies permissions upfront
- [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
- [ ] Check that every stream has data to read.
- [ ] Check that integration tests validate that every stream outputs data.
- [ ] Check that connector implements backoff logic on hitting rate limits (instead of just failing/exiting)
- [ ] Check if incremental sync works for all stream that declares its support

**Comment by yevhenii-ldv** [comment]
Scoping report:
1) Backoff is present for Singer `tap_google_analytics` library, it works with non-critical errors and makes 9 repeated requests and only then returns an error.
2) For this connector, Singer Tap does not support incremental. The Singer library can accept the `state` config as input, but then does not process it in any way.
3) There is data for all streams.
4) Сan update and minify the connector code by inheriting from BaseSingerSource.
