### ISSUE TITLE
Octavia CLI no-reset feature

### ISSUE THREAD

**Issue by lucienfregosibodyguard** [airbytehq/airbyte#19375]
## Tell us about the problem you're trying to solve
It's extremely important for us to not reset/delete our files in our datalake

## Describe the solution you’d like
We want to be able to disable the reset action automatically made by octavia

## Describe the alternative you’ve considered or used
Hitting the reset button as fast as possible when making an apply

## Are you willing to submit a PR?
Could be possible .. Do you have a pointer where the reset is done in the airbyte code ?

**Comment by marcelopio** [comment]
Already made a PR #18337
