### ISSUE TITLE
Significance of airbyte metadata columns

### ISSUE THREAD

**Issue by Rahulborserb** [airbytehq/airbyte#19379]
Hi Team,

What is the significance of airbyte metadata columns like _airbyte_ab_id, _airbyte_emitted_at, and If I don't want these columns into my destination we can achieve it writting custom connector. Since sync mode will be FullRefresh - Overwrite for all our sync operations so removing these field will impact anything? I have gone through the below document and I could not see impact..

https://docs.airbyte.com/understanding-airbyte/basic-normalization/#Rules

Please help me out with it.

**Comment by natalyjazzviolin** [comment]
Hi @Rahulborserb , as this is a question and not an issue it would be more appropriate to ask this in the forum or Slack channel. I am closing this issue.
