### ISSUE TITLE
Source Zoom: Adopt connector best practices

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1938]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

## Checklist
* [ ] Check connection verifies permissions upfront
* [ ] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
* [ ] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to sherifnada with the reason to discuss how to move forward. 
* [ ] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
* [ ] If API connector: implements incremental sync (where possible -- not all streams will allow this)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368145215002) by [Unito](https://www.unito.io)

**Comment by htrueman** [comment]
1. Check method runs read on `users` stream. Default [permission scopes](https://marketplace.zoom.us/docs/guides/using-apps/permissions#user-managed-scopes) should be enough to read all the steams we have.
2. Connector is handled with the default backoff flow. Checked with our LastPass creds.

**Comment by htrueman** [comment]
1. Check method runs read on `users` stream. Default [permission scopes](https://marketplace.zoom.us/docs/guides/using-apps/permissions#user-managed-scopes) should be enough to read all the steams we have.
2. Connector is handled with the default backoff flow. Checked with our LastPass creds. 
We get JSONDecodeError if JWT is incorrect, has wrong format or is null. 
3. Acceptance tests config yml file same as state files should be created. We should config integration tests for all the streams. 
4. Backoff works fine. Retries are working properly.
5. There are no incremental streams at the moment. It's not possible to implement incremental for the implemented streams.

Also for now it's only possible to setup the connector with docker. So virtualenv support should be fixed.
