### ISSUE TITLE
Clear invalid primary key or cursor when field is removed after schema refresh

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19387]
Update the connection streams table to invalidate the primary key or cursor mode after the schema is refreshed and the field has been removed.

Currently, the field that was removed will remain selected as primary key or cursor as it was before. This is because the refreshed schema response still returns the field as the selected value, even though it has been removed.

There are two options to make this possible:

1. Update the backend to remove the fields from the updated syncCatalog. This may be the ideal solution because the backend should manage this logic and the frontend should just render what it's given
2. Have the frontend cleanup the syncCatalog when there's a diff. This is the easier solution

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by YatsukBogdan1** [comment]
@edmundito can you please provide a use case for this, so I can reproduce the flow
