### ISSUE TITLE
Single-source allowlist IPs content

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#19393]
Individual connector pages list IP addresses to be allowlisted. Instead, they should link to this section: https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud/#allowlist-ip-addresses

**Comment by juweins** [comment]
@Amruta-Ranade Let me handle this! Just to make sure: You want sections like this to simply reference the mentioned link?

https://docs.airbyte.com/integrations/sources/alloydb#prerequisites

**Comment by Amruta-Ranade** [comment]
We're working on restructuring the docs -- we'll most likely have a new section to link to. I'll update this issue when we're done :)
