### ISSUE TITLE
🎉 Source Asana: migrate to `high` strictness SAT

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#19413]
Migrate SAT to new format: 
https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/testing-connectors/source-acceptance-tests-reference.md#strictness-level

**Comment by alafanechere** [comment]
Cool! 
@bazarnov please ask @airbytehq/connector-operations for a review once a related PR is opened.
