### ISSUE TITLE
Interest in upstreaming Rust CDK

### ISSUE THREAD

**Issue by yagehu** [airbytehq/airbyte#19435]
## Tell us about the problem you're trying to solve
I started experimenting with writing connectors in Rust. I wrote a Python CDK-like library to make that easier. It exposes an async stream interface with a few conservative blanket implementations. I just want to gauge the interest of the Airbyte team about us upstreaming it before I get buy-in from my employer.

## Describe the solution you’d like
Airbyte monorepo to contain Rust CDK.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?
Yes, but will need buy-in from my employer.

**Comment by sh4sh** [comment]
Thanks for the interesting suggestion!

**Comment by sherifnada** [comment]
@yagehu we don't have any Rust devs in-house and so would likely not be good stewards of a Rust CDK. However, we'd be happy to feature your CDK repo on our docs if it's OSS. Would you be open to that direction?

**Comment by omid** [comment]
Python and Java are very bad languages to run them one time in docker. (As far as I understood, connectors and DBTs are one time docker executions, right?)
Atm, Airbyte is so memory consuming, which makes us thinking to rewrite it or switch to another solution (if there is any!).

Java is OK for long runs, but still consuming a lot of memory.
Python is not OK for any of these!

**Comment by yagehu** [comment]
@omid I would love to hear about your pain points around memory usage and how a Rust CDK can help you. I also started working on a Airbyte connector protocol compatible orchestrator in Rust in a personal capacity. I'll reach out separately.

Since there's no interest from Airbyte folks I'll close the issue for now.

**Comment by omid** [comment]
@yagehu sure, you can find me as `omidmr` in gmail!

**Comment by yagehu** [comment]
> [@yagehu](https://github.com/yagehu) do you have a link to your Rust CDK work? I'm interested in this and was considering writing one, but happy to contribute to some ongoing work.

Unfortunately, I left the company in which I worked on this and I'm not using Airbyte anymore, so I don't have any interest in working on it in a personal capacity.
