### ISSUE TITLE
Add dark variant to Button

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19445]
Add the dark variant to the Button component.

![image.png](https://images.zenhubusercontent.com/55f362704f7a08fbb7f4d9d8/7d04a6ca-c3ba-4d80-8c68-9c2b162b38b7)

Figma:
https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=58%3A126&t=P2Yj2X7p11KjiHq4-1

Needed for to finalize the design of #17828

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
