### ISSUE TITLE
Adopt connector best practices for Freshdesk source connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1944]
## Tell us about the problem you're trying to solve
We'd like to follow [the published connector development best practices ](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/best-practices-for-connector-development) on this connector. 

## Checklist
- [x] Check connection verifies permissions upfront
- [x] Check connection failure emits actionable error messages. This will probably require you to think about the failure modes that can occur (e.g: timeout, permission not granted, token does not exist, etc.. -- make sure that you add custom integration tests to verify each of these failure modes, or unit tests if you can mock the HTTP requests involved)
- [x] If API connector: integration tests validate that every stream outputs data (you may need to seed the underlying API with fake data). This will establish a baseline confidence that the connector works correctly on every data stream. If this is not possible, please reach out to @sherifnada with the reason to discuss how to move forward. 
- [x] If API connector: backs off on hitting rate limits (instead of just failing/exiting)
- [x] If API connector: implements incremental sync (where possible -- not all streams will allow this)

**Comment by vitaliizazmic** [comment]
1. Not Singer based source
2. Source does not handle API calling errors
3. Streams  "skills", "surveys", "time_entries" require checking fake data
4. Configured catalog does not contain all streams
5. Hitting rate limits isn't handled, backoff isn't installed.
6. According to issue #1388 source requires implementing incremental sync

**Comment by sherifnada** [comment]
created tickets for 2/5 and 3/4, incremental sync no longer in scope and will come in future ticket

**Comment by eugene-kulak** [comment]
@sherifnada I think we can close this one, as all items are done
