### ISSUE TITLE
Source Google Ads: ad_groups stream does not have cost_micros field

### ISSUE THREAD

**Issue by rytis-molecule** [airbytehq/airbyte#19455]
Hello,

Could you please add additional fields in ad_groups stream. cost_micros.
There are some campaigns that do not have ads (max_performance type) I would like to get at least ad group granularity.
https://developers.google.com/google-ads/api/fields/v12/ad_group#metrics.cost_micros

Currenly working with v 0.2.4 google ads connector.

Thanks!

**Comment by sh4sh** [comment]
Thanks for the suggestion, I've assigned it to the team's backlog to review.

**Comment by darynaishchenko** [comment]
on hold, will be merged after code freeze
