### ISSUE TITLE
Resolve ❌ items in connector dependency workflow

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#19451]
## Tell us about the problem you're trying to solve
RIght now, the connector dependency workflow tells us some helpful information about dependent connectors. If there are big issues (version mismatch, missing changelog), it will un-collapse the list, so that the users will be sure to look at the issues. 

In practice, because there were already big issues, the list always comes un-collapsed and since this is a regular occurence, is ignored. Since the comment is updated on every commit, even if you collapse it, it opens again, leading to the initial issue of lots of scrolling. 

## Describe the solution you’d like
1. For now, make it always start collapsed. 
2. Go in and fix any ❌ issues on sources and connectors so that "the build is green", so to say. This will hopefully make it much more likely that any new ❌ issues are actually caught.

**Comment by evantahler** [comment]
I'll be working from the list here: https://github.com/airbytehq/airbyte/pull/19848#issuecomment-1329785174
