### ISSUE TITLE
Create frontend route that redirects to speakeasy

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#19477]
As part of the [Public Cloud API](https://docs.google.com/document/d/1FjYyeSqCGcUW2EO0PJ5p7j5afsodM9GLSI3WBwtQHKo/edit#heading=h.5vsepilo0o5q), we need a frontend route that does the following:

1. Displays a loading state
2. Sends a request to a new Airbyte endpoint, `/speakeasy_callback_url` (authenticated request wrapped with our normal overrides)
3. Redirects the browser to the `redirectUrl` returned by the Airbyte API
4. Handles possible error states

Since the cloud API will be stood up as a new service, we need to generate a new request client using Orval based on the working OpenAPI spec:

<details>
<summary>working OpenAPI spec</summary>

```yaml
---
openapi: 3.0.2
info:
  title: Speakeasy
  version: 1.0.0
paths:
  /speakeasy_callback_url:
    summary: This Endpoint will generate a JWT that can be used to login to the Speakeasy
      developer portal. The URL that is generated from the GET contains where the
      user should be redirected to and has the JWT as in the speakeasyAccessToken
      query parameter.
    get:
      tags:
      - Speakeasy
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedirectUrlResponse'
          description: Returns a valid RedirectUrlResponse
        "403":
          description: If a valid JWT was not found then return a Forbidden.
      security:
      - JWT: []
      operationId: getSpeakeasyCallbackUrl
      summary: Get the Speakeasy Callback URL
      description: Return a JSON datastructure that contains the URL that should be
        redirected to in the redirectUrl field.
components:
  schemas:
    RedirectUrlResponse:
      title: Root Type for RedirectUrlResponse
      description: ""
      type: object
      properties:
        redirectUrl:
          format: url
          type: string
      example:
        redirectUrl: https://airbyte.portal.speakeasyapi.dev?speakeasyAccessToken=eydas.ad45.1234
  securitySchemes:
    JWT:
      scheme: bearer
      type: http
```

</details>

We will also need to add the service/app that provides `/speakeasy_callback_url` to the [nginx reverse proxy](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/nginx/default.conf.template)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
