### ISSUE TITLE
Issue with GCS logging

### ISSUE THREAD

**Issue by mertkayhan** [airbytehq/airbyte#19475]
## Environment
- **Airbyte version**:  0.40.18
- **Deployment**: Google Kubernetes Engine
- **Source Connector and version**: PokeAPI 0.1.5 
- **Destination Connector and version**: E2E Testing 0.2.4 
- **Step where error happened**: Sync job 

## Current Behavior

I recently updated Airbyte to version 0.40.18 and use Google Cloud Storage to store logs. Since the update, when I trigger a sync job, the job fails with the following error for every connection I have: 

> The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

## Logs

[d8b366e7_0921_484b_8036_e002bd523d1d_logs_9911_txt.txt](https://github.com/airbytehq/airbyte/files/10021897/d8b366e7_0921_484b_8036_e002bd523d1d_logs_9911_txt.txt)

## Steps to Reproduce
1. Install Airbyte version 0.40.18 on GKE and use GCP as storage

**Comment by sajarin** [comment]
@mertkayhan thanks for the issue, are you still experiencing this issue with 0.40.22?

**Comment by mertkayhan** [comment]
Thanks, we just upgraded directly to 0.44.2 and the issue seems to be solved
