### ISSUE TITLE
Source MySQL: Additional sessionVariable parameters failing parsing

### ISSUE THREAD

**Issue by kmagida110** [airbytehq/airbyte#19487]
## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: N/A - source configuration error
- **Destination Connector and version**: MySQL 1.0.13
- **Step where error happened**: Testing connector

## Current Behavior
Tried to use `sessionVariables=wait_timeout=600` as a parameter received the error:
```
Could not connect with provided configuration. Error: jdbc_url_params must be formatted as 'key=value' pairs separated by the symbol '&'. (example: key1=value1&key2=value2&key3=value3). Got sessionVariables=wait_timeout=600
```

## Expected Behavior
This variable should be allowed as a valid JDBC param as it is how MySQL takes in [session variables](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-session.html). The parsing should allow `wait_timeout=600` (and other session variables) to be a valid key for `sessionVariable`.

## Logs
N/A

## Steps to Reproduce
1. Add `sessionVariables=wait_timeout=600` to active MySQL connection for JDBC URL Parameters (Advanced)
2. Save and test

## Are you willing to submit a PR?
If needed

**Comment by sh4sh** [comment]
Hey @kmagida110, I was able to get this working by specifying it as `wait_timeout=600` instead of `sessionVariables=wait_timeout=600` in the jdbc params field. Could you try it on your end and see if it's working?

**Comment by kmagida110** [comment]
Yeah, that does actually work, we thought we had tried that either was with an older version or we didn't actually try it.
