### ISSUE TITLE
Update to latest version of connector

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1950]
## Tell us about the problem you're trying to solve
When Airbyte releases new versions of connectors, as a user, I can easily discover them in the UI. I need to know somehow what the new version is and manually put it in the admin page.

## Describe the solution you’d like
* For any given connector, I would like to be able to update it to the newest version with one click.
* I would like to be able to update all versions of connectors to the newest version with one click.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368087775036) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
@cgardens this should be done yes?

**Comment by cgardens** [comment]
yes. done.

**Comment by espoirMur** [comment]
@cgardens, can we know where this is implemented?

**Comment by anil-inito** [comment]
Hi @cgardens 
As this is done and I can see option of upgrading connector in UI. But is it safe to upgrade the connector which is already getting used in a pipeline? Specifically I want to use Postgres source connector but somehow it is not appearing in source list although I have used it earlier and it's running in pipeline. So I thought upgrading the connector can solve this issue.
