### ISSUE TITLE
Destination Databricks: Does not work with Unity Catalog

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#19531]
Is this your first time deploying Airbyte?: No
OS Version / Instance: MacOS Montery 12.6
Memory / Disk: 8Gb
Deployment: Docker
Airbyte Version: 0.40.18
Source name/version: -
Destination name/version: databricks / 0.3.1
Step: The issue is happening during sync

i have tried to replicate data into databricks. unfortunately, the connector only uses the old two-part namespace (schema.table), so i cannot replicate data into my databricks account for which the unity catalog is enabled. in the unity catalog, a third level has been added to the namespace, so the objects are now referenced in the format catalog.schema.table. the tutorial at https://airbyte.com/tutorials/load-data-into-delta-lake-on-databricks-lakehouse states that the connector works with the unity catalog, but this is not the case according to my tests.

I just did a quick test and the sync fails when creating the table.CREATE TABLE public._airbyte_tmp_yhm_orders USING parquet LOCATION 's3://<bucket-xyz>/data/6fed6526-b350-40a6-8719-1907a58cfe65/orders'.

## Current Behavior
The sync fails because of the missing catalog namespace during table creation

## Expected Behavior
 I would have expected that it would be possible to specify the catalogue in the configuration, but currently I don’t know in which catalogue the table would be created. and the catalog is missing in table creation statement

## Steps to Reproduce
1. create a databricks e2 account
2. create a databricks connection to this account within airbyte
3. sync tables or files

**Comment by oynek** [comment]
I can confirm the bug. Would **love** to see this sorted out since I like to use the connector in a quite big project.

**Comment by mcfuhrt** [comment]
The connector does seem to work with the Unity Catalog. Our expectation was simply different, so we thought a new catalogue would be created with the configured database and table name of the stream. However, the connector puts the new database and table in the root bucket. 

The ticket can therefore be closed, as the general functionality with the Unity Catalog is given.

**Comment by grishick** [comment]
@mcfuhrt how did you get the connector to work around the errors that you were running into?

**Comment by mcfuhrt** [comment]
@grishick The problem was a lack of rights on the executing cluster. We host Databricks on AWS and after I assigned the cluster an appropriate instance role with access to the bucket, the tables could be created.

**Comment by misteryeo** [comment]
@oynek can you confirm that the same applies in your case too?
