### ISSUE TITLE
Obtain public developer application for the Qonto source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#19548]
Public developer app
[Docs](https://api-doc.qonto.com/docs/business-api/ZG9jOjg0MjE3NzE-introduction)

[EPIC] Oauth developer applications https://github.com/airbytehq/airbyte/issues/6070

**Comment by ycherniaiev** [comment]
applied for sandbox and oauth app

**Comment by ycherniaiev** [comment]
Sandbox with oauth creds is done
LastPass: Qonto Primary Developer Account
