### ISSUE TITLE
Display "Credits" in the left hand sidebar

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#19571]
We've received questions from users about how to convert to a paid account, and we want to add clarity to users where they can buy credits. The "coin" icon in the left hand sidebar shows the current balance of the workspace:
<img width="88" alt="Screen Shot 2022-11-17 at 1 54 02 PM" src="https://user-images.githubusercontent.com/38087517/202568022-63d002b4-ce02-4062-b5b9-70347188df9d.png">

Instead of showing the balance, replace the balance with the word "Credits".  (Alternative options considered but not chosen: Billing, Usage as they are less indicative of the content on that page and the intent of the change)

if a workspace falls below 20 credits, add a small yellow/orange/red notification dot to the icon in the menu, so that the user is drawn to take action by clicking on the icon.

From there, the user would then be directed to /credits, where we show an info box near the top of the page (where we currently show the email verification info box) letting the user know they are low on credits and should buy more credits to ensure their syncs continue to run successfully. 

If the workspace falls below the threshold where we stop all syncs, we make the info box with a red background color and modify the messaging to indicate their syncs have been automatically stopped and they need to buy more credits to enable the connections again.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
