### ISSUE TITLE
Source freshdesk: Support conversations and satisfaction rating streams

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1957]
## Tell us about the problem you're trying to solve
We'd like to support the following entities on our Freshdesk source connector: 
* conversations (also known as ticket notes): https://developers.freshdesk.com/api/#list_all_ticket_notes
* satisfaction ratings: https://developers.freshdesk.com/api/#view_ticket_satisfaction_ratings

Both of these are sub-entities of the ticket resource.

**Comment by sherifnada** [comment]
blocked on #1974

**Comment by eugene-kulak** [comment]
Conversations can be retrieved as:
- an embedded field of a ticket (up to 10)
- a substream of a ticket (/api/v2/tickets/<id>/conversions) 

Satisfaction ratings can be retrieved as:
- a stream /api/v2/surveys/satisfaction_ratings
- a substream of a ticket (/api/v2/tickets/[ticket_id]/satisfaction_ratings)
-

**Comment by eugene-kulak** [comment]
After tiring to use Surveys endpoint I got this error
```
freshdesk.v2.errors.FreshdeskAccessDenied: The Surveys feature(s) is/are not supported in your plan. Please upgrade your account to use it.```

**Comment by eugene-kulak** [comment]
For conversations stream, we need to implement support of child (nested) streams

**Comment by sherifnada** [comment]
@eugene-kulak this should be unblocked - we upgraded our freshdesk account to the Garden plan which allows satisfaction surveys. Can you confirm that you are able to leverage that resource in the API and that no further action is needed on my part?
