### ISSUE TITLE
Source Zendesk Support: Subscription Plan Does not Support Sandboxes

### ISSUE THREAD

**Issue by IzioDev** [airbytehq/airbyte#19582]
## Environment
- **Deployment**: docker
- **Source Connector and version**: latest zendesk

## Current Behavior
* `/api/v2/account/subscription.json` is not supported by zendesk sandboxes, and hence, cannot use airbyte for sandboxe

## Expected Behavior
* a workaround for testing airbyte in sandboxes

Bug introduced since `v0.2.15` of the connector `2022-08-03`

**Comment by natalyjazzviolin** [comment]
Hi @IzioDev , which zendesk connector does this refer to? We have 5 different ones currently.

**Comment by IzioDev** [comment]
Hello @natalyjazzviolin, you are totally correct, mistake of mine, I assumed it was implicit, because `source-zendesk-support` is the only one using User Subscription.

The one we are using is this one `source-zendesk-support`

For information:
- source-zendesk-talk does not use user subscription currently (so it should work on sandboxes)
- source_zendesk_chat does not use user subscription
- source_zendesk_sell does not use user subscription
- source_zendesk_sunshine does not use user subscription

**Comment by natalyjazzviolin** [comment]
@IzioDev thanks! Just needed to know to label the issue clearly.

**Comment by btkcodedev** [comment]
@IzioDev Could you please clarify the issue once more
Currently zendesk-support doesn't have a stream called user subscription
Is the issue is for adding new stream?

Also please clarify the context with sandboxes.

**Comment by btkcodedev** [comment]
Also the endpoint for user subscription is
/api/v2/help_center/users/{user_id}/user_subscriptions
which has a conflict with the mentioned issue description
Is that the same you intended to mention?

**Comment by artem1205** [comment]
not relevant, will reopen after more context provided
