### ISSUE TITLE
Source Bing Ads: missing keywords & Microsoft Click ID

### ISSUE THREAD

**Issue by LuliRib** [airbytehq/airbyte#19580]
Hi all, I´m connecting to the Bing Ads source.

## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**:  Windows  10, 
- **Source Connector and version**: Bing Ads
- **Destination Connector and version**: Redshift, with S3 copy

## Current Behavior
I have a connection that syncs the following streams:

- accounts (full refresh | overwrite)
- ad_group_performance_report_daily (Incremental | Deduped+history)
- ad_groups (full refresh | overwrite)
- campaign_performance_report_daily (Incremental | Deduped+history)
- campaigns (full refresh | overwrite)
- keyword_performance_report_daily (Incremental | Deduped+history)

## Expected Behavior
The syncs passes successfully.
In the keyword_performance_report_daily I receive the keyword and the keywordstatus, BUT I can´t find anywhere the keyword itself.

Another issue is the msclkid: We enabled the auto-tagging everywhere in Bingads. But I can´t find it in any report.

**Comment by LuliRib** [comment]
Hi, attached the logs of the inital upload. Therefore, it´s like a full refresh overwrite.
In the keyword_performance_report_daily I get KeywordId and KeywordStatus fields, But I need also the keyword itself. Can you add it to the report?? It´s really importanta, as I can´t show any keywords insights without the word used (the text).

Regarding the msclkid, it´s the equivalent to the google ads gclid. It contains the information regarding the click. We have implemeted the msclkid in all the campaigns, which means that we record the msclkid. BUT I don´t have it in any report.

The first thing is crucial (the keyword text)

[9d9aea6f_8f2e_4ef1_9c3e_0bbf57935780_logs_446_txt.txt](https://github.com/airbytehq/airbyte/files/10087012/9d9aea6f_8f2e_4ef1_9c3e_0bbf57935780_logs_446_txt.txt)

**Comment by LuliRib** [comment]
Hi, hereby is the list of columns that can be included in the [KeywordPerformanceReportRequest](https://learn.microsoft.com/en-us/advertising/reporting-service/keywordperformancereportrequest?view=bingads-13).
I need the keyword to be added for the keyword_performance_report_daily.
As shown in the image, it´s just to add the keyword column to the list.
![image](https://user-images.githubusercontent.com/74010842/204805217-a146f093-6ab4-4459-8e3a-f531a5875566.png)

Can someone help me with that??

**Comment by marcosmarxm** [comment]
Using the integration account the Keyword field is in the schema but it is always NULL
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/5154322/215727862-3f9350d9-90ef-4b43-8e56-2417ab0054ae.png">

**Comment by darynaishchenko** [comment]
Hi, @LuliRib! I'm working on this issue now. Could you please add more specific information about Microsoft Click ID. What kind of info about Microsoft Click ID you want to see in reports? 
Also you use outdated version of connector, you can update to newest and see the reports. 
CampaignPerformanceReport, AdPerformanceReport, AdGroupPerformanceReport KeywordPerformanceReport and AccountPerformanceReport have `Clicks`, `LowQualityClicks`, `LowQualityClicksPercent` and `LowQualitySophisticatedClicks` columns. Is this what you want to see in reports?

**Comment by darynaishchenko** [comment]
Hi, @LuliRib! Any updates about Microsoft Click ID?

**Comment by lazebnyi** [comment]
Now close. If need will re-open.
