### ISSUE TITLE
Obtain public developer application for the Xero source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#19602]
Public developer app
[Docs](https://developer.xero.com/documentation/guides/oauth2/overview/)

[EPIC] Oauth developer applications https://github.com/airbytehq/airbyte-internal-issues/issues/242

**Comment by ycherniaiev** [comment]
Done: Xero Primary Public App on LastPass.

**Comment by igrankova** [comment]
Reopened to work on publishing on a Marketplace and partner program. 
[Docs](https://developer.xero.com/documentation/getting-started-guide/)

**Comment by igrankova** [comment]
We need you to complete the following before you can progress through to certification: 
1.        Implement Sign Up with Xero (see resources and tips below)
2.        Complete the Self Integration Review - form here (~30 minutes) https://forms.gle/3eC92KdJ28o81PWZ9
3.        Ensure you have at least 3 active (beta) Xero customers connecting to your app (excluding your own test connections) - Yes (https://airbyte.metabaseapp.com/dashboard/127-by-connector-success-rate-dashboard?is_cloud=true&date_filter=past14days&connector_status=&connector_name=Xero)
4.        Where multiple versions of your app has been set up via the Developer Centre for the same/similar usage so far, please ensure that there is now only one instance of your (prod) app and any customers are connected correctly, to align with the Xero Developer Platform Terms and Conditions (clause 7b https://developer.xero.com/xero-developer-platform-terms-conditions
5.        Complete onboarding steps outlined on your App Store Setup page found in the Developer Centre https://developer.xero.com/app/manage, by providing billing information (for the Commercial Billing arrangement - see scenario 2 here https://developer.xero.com/documentation/xero-app-store/app-partner-guides/xero-app-store-subscriptions/#referral-and-subscription-flow and clause 4 of the terms https://developer.xero.com/xero-app-store-terms-and-conditions#xero-app-store-terms-and-conditions for more information). If your team would like a meeting to discuss this, please allow them to

**Comment by igrankova** [comment]
The UNLISTED App is submitted for review. Apps are currently being reviewed within two weeks of submission.

**Comment by igrankova** [comment]
Waiting for a decision to implement requirements for the Public app.

**Comment by buildwithdan** [comment]
assuming the above, is why the xero app is no longer in the sources list?

**Comment by natikgadzhi** [comment]
@buildwithdan, I might be speaking out of turn here, but nope. We (Airbyte) ran into issues with OAuth for _new_ users of the Xero source connector, so we feature flagged and pulled Xero connector from Airbyte Cloud.

I'm looking into fixing the problem now, so I hope we can make it available on Airbyte Cloud again soon.

**Comment by buildwithdan** [comment]
@natikgadzhi thanks so much for the update, do drop a note when its back on cloud again.

**Comment by yuanminglee** [comment]
Hey @natikgadzhi! Any chance this could be available on Cloud again soon?

**Comment by natikgadzhi** [comment]
Alright, I'll close this one, but as for Xero, let me make another issue with what we need to make to make the connector available.

**Comment by natikgadzhi** [comment]
Okay, here we go: #42126. Once we get this done, Xero will be back online.
