### ISSUE TITLE
Source Amplitude: Enable region selection

### ISSUE THREAD

**Issue by mariamthiam** [airbytehq/airbyte#19605]
## Tell us about the problem you're trying to solve
I'm trying to use Airbyte Amplitude connector to extract our AB testing data but our Amplitude project is hosted on region `EU Residency Serve`  instead of `Standard Server`  which means Amplitude connector need to use https://analytics.eu.amplitude.com/api as base endpoints (as describe in [Amplitude API documentation ](https://www.docs.developers.amplitude.com/analytics/apis/chart-annotations-api/)) that is not possible right now. Current Amplitude's connector use only base endpoint https://amplitude.com/api  for `Standard Server`. 

## Describe the solution you’d like
Add possibility to select region for amplitude connector (`Standard Server` or  `EU Residency Serve`) 

## Describe the alternative you’ve considered or used
Modify the connector locally,  use custom connector with docker image to extract Amplitude data without sharing. Non maintainable and not ideal solution

## Are you willing to submit a PR?

Yes I want to contribute with a PR containing the proposed solution

**Comment by YowanR** [comment]
Thanks for your contribution! @sajarin Can you take a look and see if someone can review the PR, please?

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Amplitude: Enable region selection](https://app.harvestr.io/components/0/list/imZgSFHLe)
