### ISSUE TITLE
Source page which displays destinations should provide some indication of how many destinations are active

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#1960]
## Tell us about the problem you're trying to solve
When looking at my sources, there is an indicator of the number of destinations and no way to tell how many are active until I click through. I would like to see how many are active. This lets me do things like:

* Swap out destinations for sources easily by walking down the list and viewing the ones that have fewer than the others 
* Identify sources that are not syncing to any destination

## Describe the solution you’d like
Some sort of visual indicator of the number of active sources - even a circular progress bar around the number of total sources will suffice

## Describe the alternative you’ve considered or used
Clicking through each like a human version of `xdotool`.

**Comment by johnlafleur** [comment]
Here is a suggestion for a design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21161%3A0
It would give a good view of what is the status for all the connections for sources, but also for destinations (same suggestion for that section).

**Comment by cgardens** [comment]
Thanks. These mock ups makes sense to me and are definitely an improvement over what we have.

**Comment by cgardens** [comment]
@Jamakase points out that API doesn't expose enough information to support green, red, and gray. What we should do in the short term is just have green and gray. green means status active. gray means status inactive. connectors with status deprecated should be ignored.

@Jamakase suggested adding `lastSyncStatus` to `WbConnectionRead`. I like this idea. As a separate [issue](https://github.com/airbytehq/airbyte/issues/2332) for the API we will add this field. When that is done the rules will be. For now we should close this issue once the first part mentioned above is complete.
green: active + last job success
red: active + last job failure
gray: inactive
