### ISSUE TITLE
Moving data from `airbyte_tmp_*` to `airbyte_raw_*` is slow and can be skipped on initial syncs

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#19612]
For database sources using SQL, a few tables are created:
* `airbyte_tmp_{id}_tbl` - storage for the raw JSON of this sync
* `airbyte_raw_tbl` - storage for the raw JSON of all syncs
* `airbyte_scd_tbl` - (optional, if table is deduped)
* `tbl` - the table the user actually wants

For initial syncs, the `airbyte_tmp_{id}_tbl` will be very large.  The Sql to populate the raw table from the tmp table, e.g. `SELECT * INTO 'airbyte_raw_tbl' FROM 'airbyte_tmp_{id}_tbl'` literally reads and copies all the data that was just synced.  This is observed to:
* On destination-postgres testing locally with ~10GB of data crash the postgres process
* On destination-snowflake with ~1GB of data take ~30% of the whole sync's duration (2:30 of a 7min sync)

We can optimize this for initial syncs!
* Check if the `airbyte_raw_tbl` does not exist or has 0 records.
  * If the table does not exist or has 0 records, delete `airbyte_raw_tbl` and rename `airbyte_tmp_{id}_tbl` to be `airbyte_raw_tbl` - renames are fast!
  * Otherwise, continue with the insert we do today

**Comment by marcelopio** [comment]
Kinda duplicated of #18399, no?

**Comment by evantahler** [comment]
@ryankfu can this issue and https://github.com/airbytehq/airbyte/issues/18399 be closed by your checkpointing changes?

**Comment by evantahler** [comment]
Ping @ryankfu - can we close this issue?
