### ISSUE TITLE
Update low-code tutorial to use the connector builder UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19615]
### Tell us about the documentation you'd like us to add or update.
Context [here](https://github.com/airbytehq/airbyte/pull/19588/files#r1026632515) -- we now have a UI which we believe is a strictly better development experience for writing YAML. To encourage people to use it more widely we should have the tutorial use the UI. 

### If applicable, add links to the relevant docs that should be updated
https://docs.airbyte.com/connector-development/config-based/tutorial/getting-started

**Comment by girarda** [comment]
closing because we have the connector builder tutorial
