### ISSUE TITLE
[Connector Builder UI] show HTTP request method in the test panel request tab

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19622]
## Tell us about the problem you're trying to solve
The test panel request tab does not show the HTTP method (GET/PUT/etc..) of the outgoing request

<img width="449" alt="Screen Shot 2022-11-18 at 1 56 30 PM" src="https://user-images.githubusercontent.com/6246757/202809811-83ff6e92-66ab-4cdb-ba20-02a16773d297.png">

## Describe the solution you’d like
I would like to see the HTTP method used in the request.

This issue builds on top of the changes of another issue https://github.com/airbytehq/airbyte/issues/19735 which handles updating the log messages emitted during a sync to a low code connector. 

## Implementation Approach
This will require changes to the `airbyte-connector-builder-server`. 

When the `airbyte-connector-builder-server` receives request log messages with the added `method` field, we'll need to translate it into response output by the server. We need to update the `open_api.yaml` HttpRequest object to include a field for `method`. We use the OpenAPI spec to generate the server input/output models used by the server code. We then need to generate new models using `./gradlew :airbyte-connector-builder-server:generateOpenApiPythonServer` And finally update how we parse the LOG message to extract the HTTP method and include it in the outbound server response.

## Acceptance Criteria

- [ ] The open_api.yaml spec reflects the additional request method field
- [ ] The newly generated models should reflect the updated spec
- [ ] When making server requests, the HTTP response includes the request method
- [ ] The newly generated client should reflect the updated spec
- [ ] The request method should be reflected in the connector builder UI sidebar panel

**Comment by sherifnada** [comment]
cc @brianjlai could be a good first issue

**Comment by brianjlai** [comment]
this is a good one. i'll flesh this out and add this to grooming

**Comment by brianjlai** [comment]
grooming notes:

- add acceptance criteria
- - log message output is updated
- - open api spec updated
- - server emits new method in request object
- - reflected in the UI
- look up if a UI change is required
