### ISSUE TITLE
Source Freshdesk: enable fine tuning rate limiting configurations

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1962]
## Tell us about the problem you're trying to solve
I'd like to be able to control how many requests per second the Freshdesk connector uses in order to guarantee that syncs from Airbyte do not block other applications reading from Freshdesk. 

## Acceptance Criteria
1. Add a `requests_per_second` parameter which, when set, throttles requests made per second by airbyte

**Comment by eugene-kulak** [comment]
@sherifnada question,
do want to have a new parameter in `spec.json`?
isn't it too technical for regular user?
maybe we can have `advanced` section in UI or `internal_config.json` + `config.json`?

**Comment by eugene-kulak** [comment]
https://pypi.org/project/ratelimit/
