### ISSUE TITLE
Facebook source with daily ad metrics and breakdowns

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#1963]
## Tell us about the problem you're trying to solve
We'd like to collect the daily ad performance metrics (such as impressions, clicks, and so on) from our Facebook ads, broken down by impression_device and publisher_platform, and also broken down by age and gender.  These are available through the Facebook Ad Insights API by sending a `POST` to `/act_123/insights` and specifying the desired breakdowns in the `breakdowns` parameter.

## Describe the solution you’d like
Ideally, the existing Facebook Marketing connector would add an option for including daily performance metrics, with selections for the desired types of breakdowns.  Each breakdown would produce one table.

Alternatively, this could be done in a separate, new connector, specifically for providing daily performance metrics.  Again, the settings for the connector would include the selection of breakdowns to use, and each breakdown would produce one table.

## Describe the alternative you’ve considered or used
The way we do this today is to run a Python script making exactly the `POST` query described above, collect the results as JSON, and then upload the JSON files to Google Cloud Storage.  The script takes a very long time to run (many days) because each query is limited to returning only a small set of values, and Facebook enforces a rate limit on API requests.  It would be far more efficient and reliable for Airbyte to do this.

## Additional context
Here's a screenshot of the BigQuery table produced by our existing, slow, Python script.  You can see that some of the fields are nested within other fields, which exactly reflects the structure of the JSON returned by Facebook.

![image](https://user-images.githubusercontent.com/236086/106959753-f6470b00-66ef-11eb-995d-af6c7027b945.png)

**Comment by sherifnada** [comment]
This feature is ready on #1990 . However, the main hangup is writing a reliable test to guard against regressions. This should be done EOD tomorrow, with the compromise being that we will not test the new streams as part of standard tests but will write custom test cases for it.
