### ISSUE TITLE
Helm Chart should be able to specify Minio Image / tag 

### ISSUE THREAD

**Issue by si-te** [airbytehq/airbyte#19636]
## Tell us about the problem you're trying to solve

When using the 0.41.0 helm chart to deploy airbyte, it is not possible to fix the version of the deployed internal minio image, as it is hard-wired to deploy minio/minio:latest. This means there is no reproducability of the deployment, as the minio version might change in between deployments. Furthermore it is not possible to pull from private image registries (as might be required in some enterprise contexts for security reasons). 

## Describe the solution you’d like
It should be possible to specify the image in the values something like this:

```
minio:
  image:
    repository: someprivaterepo/minio
    pullPolicy: IfNotPresent
    tag: something
```

## Describe the alternative you’ve considered or used

Alternative is to resort to external minio, not using the integrated one. But this entails additional complexity.

## Additional context

https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/minio.yaml#L35

## Are you willing to submit a PR?
currently not.

**Comment by cpdeethree** [comment]
This should be now supported here: https://github.com/airbytehq/airbyte-platform/blob/93cd829293c3c0362fca803bcf38f6c04b6749b5/charts/airbyte/templates/minio.yaml#L35

Can you please verify?

**Comment by si-te** [comment]
Thanks for the reply, this should do it. Closing the issue.
