### ISSUE TITLE
Sandbox Account for Teradata Vantage Destination

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#19656]
## Tell us about the problem you're trying to solve
Request/create a sandbox account for implementing/testing new connector [Teradata Vantage Destination](https://github.com/airbytehq/airbyte/pull/19420)

**Comment by igrankova** [comment]
@natalyjazzviolin hi!
I filled the contact form and asked for a sandbox. I'll let you know if they reply. 
There's no possibility to create a free trial account.

**Comment by igrankova** [comment]
@natalyjazzviolin Still no answer from support

**Comment by misteryeo** [comment]
@SatishChGit do you think you could help here?

**Comment by SatishChGit** [comment]
@misteryeo let me check with my team and get back you. Do you any reference no/id for filled form?

**Comment by SatishChGit** [comment]
@misteryeo @natalyjazzviolin can you check the possibility of setting vantage on gcp using https://quickstarts.teradata.com/vantage.express.gcp.html

**Comment by SatishChGit** [comment]
> ## Tell us about the problem you're trying to solve
> Request/create a sandbox account for implementing/testing new connector [Teradata Vantage Destination](https://github.com/airbytehq/airbyte/pull/19420)

FYI, https://github.com/airbytehq/airbyte/pull/21160 - teradata vantage destination connector pr
