### ISSUE TITLE
Consolidate update/delete custom definitions to regular update/delete definitions

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#19669]
FE should use the same API when user wants to update or delete their source or destination definition.

This ticket requires to consolidate 4 custom APIs into the original API (FE will use the one without `custom` in it, such as updateSourceDefinition)

Also as part of the effort we should remove the legacy creation path to avoid misuse:

POST /v1/source_definitions/create
POST /v1/destination_definitions/create

**Comment by pmossman** [comment]
Refining notes:
- Before removing any routes, we should check to see if there are other places that call them. For instance, does Octavia CLI call `POST /v1/source_definitions/create` or `POST /v1/destination_definitions/create`? @alafanechere perhaps you know the answer to this?

**Comment by marcelopio** [comment]
octavia do not call it yet, and my implementation was using the custom prefix

https://github.com/airbytehq/airbyte/pull/15058

**Comment by pmossman** [comment]
Closing this as a duplicate in favor of https://github.com/airbytehq/airbyte/issues/19670
