### ISSUE TITLE
Add OSS-only Connectors to Connector Dropdown in Cloud

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#19671]
In Cloud, he connector (source / destination) dropdowns only show the connectors that are available in Cloud, even if we support the connector in OSS.

As an example, JIRA returns no results: 
![Screen Shot 2022-11-21 at 10 53 14 AM](https://user-images.githubusercontent.com/38087517/203136477-27f75a48-8f5c-45e8-9596-69c344a2dd31.png)

Ideally, we show the connectors that are available in our OSS catalog even if we do not offer them in Cloud. We could use the label "OSS Only". Alternatively, if we are able to pull in connectors we plan to bring to Cloud in the next quarter, we can use a "Soon" label. 

I'm not that opinionated on whether the user should 1) be able to actually click the connector and preview a greyed-out version of the setup form as it shows up in OSS or 2) not click on the connector at all. But, if their interest is there, we should be able to capture that so that we notify them when the connector is released in Cloud.

cc @misteryeo @timroes

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by sherifnada** [comment]
@nataliekwong can you share your thinking behind the value of this feature? Wouldn't we be able to capture someone's searches anyways regardless of whether we have this feature?

**Comment by nataliekwong** [comment]
Sure, this would ease user confusion. We see when users are searching for sources or destinations that are only available in OSS and not in Cloud.  They see material on our website (https://airbyte.com/connectors) and connections pages (e.g.https://airbyte.com/connections/Shopify-to-BigQuery) that imply it's available, then search for that connector specifically and don't find it.

As a result, we see inbound Intercom chats that ask why it isn't showing up for them (they wonder if it's a permissions issue or maybe an error on their end) and repeated searches. If the user saw the search result return the connector, but that it was only available in OSS, it makes it clear which product/route they need to use in order to use that connector.

**Comment by misteryeo** [comment]
@nataliekwong with [the discussion here](https://docs.google.com/document/d/1ATj7ly_jXkidiCobJkB-APT3_S-ihaPxdNZnKTmQ3Ug/edit#) meaning that we should get to largely parity at any point in time, would that mean this issue would be moot?

**Comment by nataliekwong** [comment]
Yes! That is indeed true @misteryeo . This is only an issue if we don't have parity between OSS and Cloud.

**Comment by sherifnada** [comment]
closing for now, please reopen if still needed
