### ISSUE TITLE
Prepare update/delete definition endpoints for custom connectors in Cloud

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#19670]
In https://github.com/airbytehq/airbyte/issues/19637#issuecomment-1322485100, we captured notes from a discussion about these API endpoints between FE and BE.
> Synced offline about this. Our outcome and action items
> 
> * createCustomSource/DestinationDefinition should be used (with workspaceId)
> * Once in UI, we want to remove the old (non workspace scoped) create APIs
> * updateSource/DestinationDefinition (does not need workspaceId)
>   
>   * Cloud will check if the passed connector ID, is actually assigned to a workspace that the user has access to, if not throws 404 in cloud if connector ID
> * Same logic as for `update` should apply for the `delete` endpoint
> * No migration will be needed, we accept orphaned rows in the actor table for the rare cases users ran into that case

In order to achieve this, we'll perform the following steps:
- Remove the custom-specific blocks from config.yaml for update/delete
  - source_definitions/update_custom: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L472-L493
  - destination_definitions/update_custom: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L994-L1015
  - CustomSourceDefinitionUpdate: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L2683-L2692
  - CustomDestinationDefinitionUpdate: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L3053-L3062
  - source_definitions/delete_custom: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L494-L512
  - destination_definitions/delete_custom: https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L1016-L1034
- Remove the custom-specific update/delete handler methods:
  - updateCustomSourceDefinition method in handler: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/SourceDefinitionsHandler.java#L283-L291
  - updateCustomDestinationDefinition method in handler: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java#L284-L292
  - deleteCustomSourceDefinition method in handler: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/SourceDefinitionsHandler.java#L310-L318
  - deleteCustomDestinationDefinition method in handler: https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationDefinitionsHandler.java#L312-L320

On the Cloud side, we will:
- Remove the `<update/delete>Custom<Source/Destination>Definition` methods from the wrapped handler, since they won't exist in OSS anymore.
- Update the `<update/delete><Source/Destination>Definition` methods in the wrapped handler to make sure the custom definition can be updated/deleted by the current user.
  - There is no workspaceId in the request, so really this check is that the current user has permission to at least one workspace that has a grant for the custom definition.

**Comment by pmossman** [comment]
Refining notes:
- This is an action item coming out of discussion w/ Tim and front-end around making the OSS connector endpoints more sensible. 
- Rather than letting a user pass in an arbitrary workspace ID as part of the request, we can authenticate requests in Cloud by using the current workspace from the logged in session. In OSS, the request can just go through without auth because we don't have RBAC in OSS.

**Comment by pmossman** [comment]
This issue captures the contents of this other issue: https://github.com/airbytehq/airbyte/issues/19669
