### ISSUE TITLE
Custom connector related jobs should run in a different node pool

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#19684]
For all activities, we want to create a bit to indicate if that's custom connector related; and if so, in KubeProcessFactory.java we should assign a different node selector to run the jobs.

The custom connector bit could also be useful for metrics tracking purpose.

**Comment by pmossman** [comment]
Refining notes:
- Kube process factory controls our node selectors, which is called for every Temporal workflow. We need to pass in a flag that indicates if the source or destination is a custom connector. There are 16 different Temporal job types that will need this flag, so the work here involves updating the 16 different job configs to have a flag for isCustom.
