### ISSUE TITLE
Custom connector disappear after adding successfully

### ISSUE THREAD

**Issue by toandm** [airbytehq/airbyte#19695]
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: GCP n2-standard-2
- **Deployment**: Docker

- **Step where error happened**:  Setup new Source custom connector

## Current Behavior
I follow the instructions here to add a new Source custom connector: https://airbytehq.github.io/integrations/custom-connectors#adding-your-connectors-in-the-ui
After adding it, the custom connector shows up in the list of Sources. However, after waiting for 5 seconds, it disappears. I cannot find it in the Settings > Sources UI, or create a new Source with my custom connector

[Access Airbyte DB](https://airbytehq.github.io/operator-guides/configuring-airbyte-db/#accessing-the-default-database-located-in-docker-airbyte-db) and run `UPDATE actor_definition SET public = true WHERE name = '<connectorname>';` fixes the problem.

## Expected Behavior
Custom connector shows up in the list of Sources, and can be used to create a new Source

## Steps to Reproduce
* Create a custom connector docker image
* Follow the steps in this link to add a new Source custom connector: https://airbytehq.github.io/integrations/custom-connectors/#adding-your-connectors-in-the-ui

Note: likely to be the same as #13333

## Are you willing to submit a PR?
No

**Comment by NahidOulmi** [comment]
Hi @toandm I have the same issue.
Can you explain a bit more on the `UPDATE actor_definition SET public = true WHERE name = '<connectorname>'; fixes the problem. ` workaround ? When do I need to run it ? Thanks

**Comment by toandm** [comment]
@NahidOulmi you need to access the Airbyte DB first to run that query. Updated that part in my description with the instruction link
