### ISSUE TITLE
Build fails at task airbyte-webapp:npm_run_build

### ISSUE THREAD

**Issue by GLaDOS9000** [airbytehq/airbyte#19699]
## Environment
- macOS Big Sur 11.6.8
- python 3.9.13 (local env with pyenv)
- Gradle version: 7.4
- java version 17.0.5
- node version 16.18.1
- Jq version 1.6
- Docker version 20.10.17

## Current Behavior
Build fails at this step: 
- Task :airbyte-webapp:npm_run_build FAILED

Process 'command '/Users/username/Documents/GitHub/airbyte/airbyte-webapp/.gradle/nodejs/node-v16.15.1-darwin-x64/bin/npm'' finished with non-zero exit value 1

## Logs

airbyte-webapp:npm_run_build FAILED |  
-- | --
  |   |  
  | > airbyte-webapp@0.40.18 prebuild |  
  | > npm run generate-client |  
  |   |  
  |   |  
  | > airbyte-webapp@0.40.18 generate-client |  
  | > orval |  
  |   |  
  | node:internal/modules/cjs/loader:361 |  
  | throw err; |  
  | ^ |  
  |   |  
  | Error: Cannot find module '/Users/username/Documents/GitHub/airbyte/airbyte-webapp/node_modules/esutils/lib/utils.js'. Please verify that the package.json has a valid "main" entry |  
  | at tryPackage (node:internal/modules/cjs/loader:353:19) |  
  | at Function.Module._findPath (node:internal/modules/cjs/loader:566:18) |  
  | at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27) |  
  | at Function.Module._load (node:internal/modules/cjs/loader:778:27) |  
  | at Module.require (node:internal/modules/cjs/loader:1005:19) |  
  | at require (node:internal/modules/cjs/helpers:102:18) |  
  | at Object.<anonymous> (/Users/username/Documents/GitHub/airbyte/airbyte-webapp/node_modules/orval/dist/chunk-W5UA6U5A.js:4:2379) |  
  | at Module._compile (node:internal/modules/cjs/loader:1105:14) |  
  | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) |  
  | at Module.load (node:internal/modules/cjs/loader:981:32) { |  
  | code: 'MODULE_NOT_FOUND', |  
  | path: '/Users/username/Documents/GitHub/airbyte/airbyte-webapp/node_modules/esutils/package.json', |  
  | requestPath: 'esutils' |  
  | }

## Steps to Reproduce
I followed [airbyte tutorial](https://docs.airbyte.com/contributing-to-airbyte/developing-locally/) : 

I have succesfully installed esutils with 'npm install esutils' with no results on build succes

## Are you willing to submit a PR?

no, I don't feel confident about solving this on my own

**Comment by sh4sh** [comment]
Hey @GLaDOS9000, this issue has come up before and it was resolved by removing your `airbyte-webapp/node_modules` folder and trying again. Can you run that and let us know if it helps?

**Comment by GLaDOS9000** [comment]
Hey @sh4sh, it worked like a charm ! Thank you !
