### ISSUE TITLE
Onboarding UX: Stuck in the onboarding set-up connection with Failed to fetch Schema. Please try Again

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1970]
## Tell us about the problem you're trying to solve
When setting up a connection for the first time, I am unable to skip the onboarding or go back to correct things in case of errors.

## Describe the solution you’d like
- Always have the possibility to `Skip Onboarding`so i can go access the Admin Pages to update connectors to newest versions for example
- Navigate back to setting up my connectors to fix whatever I did wrong earlier

## Describe the alternative you’ve considered or used
- Otherwise, I would have to shutdown my instance while deleting whatever configurations I made so far: `docker-compose down -v`
- Then restart my instance `docker-compose up`

## Additional context
![Screenshot 2021-02-05 at 14 04 18](https://user-images.githubusercontent.com/7718175/107037667-ae8db580-67bb-11eb-8b8e-eba6096cd9d5.png)

**Comment by cgardens** [comment]
Weird. Did the underlying discover schema call fail or succeed? Noticing it says "Succeeded Logs".


> Always have the possibility to Skip Onboardingso i can go access the Admin Pages to update connectors to newest versions for example

I agree though, it is better if someone can skip out of it. I would be a proponent of adding the "skip onboarding" button. I think the navigation stuff is less necessary.

**Comment by ChristopheDuong** [comment]
> Weird. Did the underlying discover schema call fail or succeed? Noticing it says "Succeeded Logs".

It succeeded but it was an expected Failing case because I was using my branch with the Catalog API refactoring and the UI doesn't know how to read the new schema I guess.

But it reminded me that the "skip onboarding" button was missing on that page and I remember people on the chat support getting stuck on this step of onboarding too...

**Comment by cgardens** [comment]
Got it. So there's not an actual bug here. But it would still be nice to be able to skip onboarding in this case. 👍
