### ISSUE TITLE
Add more detail to data residency help text when creating a new connection

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#19729]
When creating a connector on cloud, we currently display a section on "Data residency" but don't provide much context on what that actually means:

![image](https://user-images.githubusercontent.com/7550957/203395787-c4e6785d-37b8-4a02-882e-cdc40ac2df9b.png)

We should update the help text to better clarify what "Data residency" actually means:

> Choose where the data for this connection will be processed. Depending on your network configuration, you may need to [add IP addresses](https://docs.airbyte.com/cloud/getting-started-with-airbyte-cloud/#allowlist-ip-address) to your allowlist. [Learn more](https://docs.airbyte.com/cloud/managing-airbyte-cloud/#choose-the-data-residency-for-a-connection).

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
