### ISSUE TITLE
Run connector acceptance tests in the PR CI to get Github Status Checks

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#19723]
To enable automatic publishing of connectors to DockerHub from master we first want to make sure acceptance tests are successful before merging.
We can currently run acceptance tests on PR with `/test` command.

We should also run these tests automatically on a PR modifying (a) connector(s) on each new commit.
This could be added to the existing [Connectors Ops CI workflow](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/connector_ops_ci.yml#L1)

**Comment by evantahler** [comment]
There's some interesting logic to work out about how a common change effects many connectors

We have this in actions already, so we need to think about this.

**Comment by evantahler** [comment]
Grooming:
* Don't test all N connectors when the SAT has chaged
* Don't test all N API connectors when the CDK has chaged
* ?? run all Java connectors when something shared has changed (e.g. abstract JDBC classes). 
  * Maybe this is hard to detect.  We might be ok just looking at folder changes for the connector. 

Developers can still manually run `/test` when they want to test more connectors if they want.

If there really are multiple connectors changed, run the test suite in parallel (if possible)

As part of this, we should change our changed-connector logic to not consider all python connectors changed when the SAT is updated (check `requirements -e`)
