### ISSUE TITLE
Source freshdesk: seed API with data for integration tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1973]
## Tell us about the problem you're trying to solve
1. verify if Streams "skills", "surveys", "time_entries" are available for API access in our sandbox account
2. seed with fake data if so

**Comment by vitaliizazmic** [comment]
Stream 'Surveys' isn't available for current plan of test account. Syncing of it leads to error. Stream 'Skills' according to [documentation](https://support.freshdesk.com/support/solutions/articles/222692-setting-up-skill-based-ticket-assignment-matching-tickets-to-agents-with-expertise-) should be unavailable in this plan too, but it works. I created Skill record via API and it was received while syncing.
