### ISSUE TITLE
[CDK] Refactor reading JSON inputs for syncs under one shared method

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#19733]
## Tell us about the problem you're trying to solve
This ticket is a precursor to https://github.com/airbytehq/airbyte/issues/18946 . We currently attempt to read in JSON file inputs during connector syncs like configs, configured catalogs, and state. Before tackling that issue, we should clean up the code related to file reads and improve code reuse. The naming of the `BaseConnector.read_config()` is also not accurate since it is currently being used to read other types of inputs too since its a generic json file reader.

## Describe the solution you’d like
We should rename `BaseConnector.read_config()` to `read_json_file()` to accurately reflect what it is doing. The existing usages of `read_config()` should be updated.

The `Source.read_state()` method should start using this newly renamed `read_json_file()` to read the state JSON file instead of duplicating all the same file reading logic.

## Acceptance Criteria

- [ ] When running a `check` operation on a connector, the operation succeeds with valid json
- [ ] When running a `read` operation on a connector, the operation succeeds with valid json
- [ ] When running a `read` where the configured catalog doesn't exist, an error should be thrown

**Comment by maxi297** [comment]
This has been solved as part of https://github.com/airbytehq/airbyte/pull/20019
