### ISSUE TITLE
[Low Code CDK] the http method of the request should be included for LOG messages emitted during a sync when debug is enabled

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#19735]
## Tell us about the problem you're trying to solve
In the Connector Builder UI, we are not displaying the HTTP method used by the request. The changes to the builder server will be handled as part of https://github.com/airbytehq/airbyte/issues/19622 along with more context. This issue will be used to track the `airbyte-cdk` changes needed. When logging some field of the PreparedRequest we are not including the HTTP method (GET/PUT/etc..), but we should be.

## Describe the solution you’d like
During a `read` of a connector, for each outbound request made to a partner API, I would like to see in the request LOG message emitted that it also includes the HTTP method used. 

## Implementation Approach
This will require a change to low code framework of the `airbyte-cdk` package which is responsible for processing syncs to based on a developer configured connector manifest.

In the `airbyte-cdk` `SimpleRetriever`, we need to update how we create LOG messages for outbound requests to include the method of the PreparedRequest. The `airbyte-cdk` Python package will then need to have a new version published.

## Acceptance Criteria

- [ ] When running a sync with the `--debug` flag enabled will include request LOG messages where the method is populated
- [ ] A new minor version of the airbyte-cdk Python package should be published

**Comment by girarda** [comment]
sample command: `python main.py read --config secrets/config.json --catalog integration_tests/configured_catalog.json --debug`
