### ISSUE TITLE
Klaviyo Source Connector - Schema validation errors found for stream events

### ISSUE THREAD

**Issue by christo-olivier** [airbytehq/airbyte#19743]
## Environment
- **Airbyte version**:  0.40.9
- **OS Version / Instance**: debian-11, GCP e2-custom-4-8192
- **Deployment**: Docker
- **Source Connector and version**: Klaviyo 0.1.10 
- **Destination Connector and version**: BigQuery 1.2.7
- **Step where error happened**: Sync job

## Current Behavior
When processing the Klaviyo Events entity a message is reported on the `source` saying that a JSON number data type could not be converted to an integer data type.

> Failed to transform value 45.5 of type 'number' to 'integer', key path: '.event_properties.items.1.price'

## Expected Behavior
JSON data types of number should be converted to FLOAT or NUMERIC as conversion to INTEGER will cause data loss at best and failures at worst.

## Logs
Not provided as the sync does not fail, it simply warns about the conversion issue.

## Steps to Reproduce
1. Connect to Klaviyo
2. Sync data to BigQuery
3. Watch for messages where a Klaviyo event has a price that has decimal values

## Are you willing to submit a PR?
Not able to at the moment.

**Comment by christo-olivier** [comment]
Just some additional information. I have also received the following error message 

`Schema validation errors found for stream events. Error messages: [$.event_properties.items[0].price is of an incorrect type. Expected it to be integer]`

This happened after syncing roughly 65 million records. No idea what the value was that caused the error as this is not pushed out into the logs.

here is an extract of the log when the failure occured:
[b0dee4ab_0051_4517_9cb9_3bb55e10b43b_logs_24_txt.txt](https://github.com/airbytehq/airbyte/files/10085815/b0dee4ab_0051_4517_9cb9_3bb55e10b43b_logs_24_txt.txt)

**Comment by sh4sh** [comment]
Thanks for reporting this issue. I tried reproducing it with our test data but I am not getting any `Failed to transform` or `Schema validation errors` messages. I can't confirm, but I expect the source connector [events.json](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/events.json) schema probably needs to be updated as the value you're indicating is indeed listed as `integer`.

Could you provide the full sync log to help our investigation? Also, a couple questions to narrow down scope:
 - Do you have normalization enabled for the destination connector? Could you try with normalization off, or a different destination connector if you are able to? (Might be helpful to use a recent start_date and only sync the `events` table)
- If the sync completed at any point, could you double check whether `.event_properties.items.1.price` was synced to the destination raw tables?

Docs may also need an update depending on resolution. Our [Klaviyo docs](https://docs.airbyte.com/integrations/sources/klaviyo#data-type-map) say that the connector has a 1:1 data type conversion to Airbyte types, so the Klaviyo datatype `NUMBER` should be extracted as the Airbyte datatype `NUMBER`. Then the [BigQuery destination connector](https://docs.airbyte.com/integrations/destinations/bigquery#data-type-map) processes Airbyte datatype `NUMBER` into BigQuery datatype `FLOAT`. This behaviour would have prevented the issue.
