### ISSUE TITLE
Source Twilio: new stream roles

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#19744]
## Tell us about the problem you're trying to solve
The Role resource of Programmable Chat represents what a user can do within a Chat Service instance. Roles are scoped to either a [Service](https://www.twilio.com/docs/api/chat/rest/services) or a [Channel](https://www.twilio.com/docs/api/chat/rest/channels).

[Users](https://www.twilio.com/docs/chat/api/users) are assigned a role at the Service scope, which determines what they are can do within the Chat Service instance, such as create and destroy channels.

[Members](https://www.twilio.com/docs/chat/api/members) are assigned a role at the Channel scope. This determines what they are able to do within a particular channel, such as invite users to be members of the channel, post messages, and remove members from the channel.
## Describe the solution you’d like
Research rpos and cons for implenting this stream

**Comment by YowanR** [comment]
Note: We expect any new streams added to this connector to be incremental

**Comment by btkcodedev** [comment]
Conformation: https://chat.twilio.com/v2/Services/{ServiceSid}/Roles
https://www.twilio.com/docs/chat/rest/role-resource
Is this the endpoint which we are trying to integrate?

**Comment by btkcodedev** [comment]
I would like to do it

**Comment by YowanR** [comment]
@ycherniaiev Can you confirm @btkcodedev's question?

**Comment by ycherniaiev** [comment]
> Confirmation: https://chat.twilio.com/v2/Services/{ServiceSid}/Roles
> 
> https://www.twilio.com/docs/chat/rest/role-resource
> 
> Is this the endpoint which we are trying to integrate?

I confirm-it is exactly this stream

**Comment by btkcodedev** [comment]
Yes

**Comment by btkcodedev** [comment]
Update: Just got the api with postman right, will start adding stream soon

**Comment by btkcodedev** [comment]
Update:
Parent Stream: Services
https://www.twilio.com/docs/chat/rest/service-resource
Child Stream: Roles
https://www.twilio.com/docs/chat/rest/v1/roles
