### ISSUE TITLE
Source Twilio: new stream Trunk

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#19746]
## Tell us about the problem you're trying to solve
The Trunk resource represents a SIP Trunk in your Twilio account. A Trunk can have associated [Credential Lists](https://www.twilio.com/docs/sip-trunking/api/credentiallist-resource), [IP Access Control Lists](https://www.twilio.com/docs/sip-trunking/api/ipaccesscontrollist-resource), [Origination URLs](https://www.twilio.com/docs/sip-trunking/api/originationurl-resource), and [Phone Numbers](https://www.twilio.com/docs/sip-trunking/api/phonenumber-resource).
GET https://trunking.twilio.com/v1/Trunk

## Describe the solution you’d like
Research pros and cons for implemnting this stream

**Comment by btkcodedev** [comment]
I would like to work on the issue

**Comment by btkcodedev** [comment]
:)

**Comment by jrolom** [comment]
You got it @btkcodedev ! Looking forward to your PR
