### ISSUE TITLE
Oauth Authenticator expiry date format

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#19752]
## Tell us about the problem you're trying to solve
DeclarativeOauth2Authenticator expects `expires_in` in seconds (in get_access_token method). New feature makes it possible to specify date format (if not seconds)

## Describe the solution you’d like
add to OAuth authenticator field token_expiry_date_format, e.g.
```
oauth_authenticator:
    type: OAuthAuthenticator
    token_expiry_date_format: ""YYYY-MM-DDTHH:mm:ss[Z]"""
```

**Comment by lazebnyi** [comment]
PR - #19718
