### ISSUE TITLE
🐛 Source TikTok Marketing - Error while converting `mobile_app_id` column to int in AudienceReports streams

### ISSUE THREAD

**Issue by achaussende** [airbytehq/airbyte#19757]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **Source Connector and version**: TikTok Marketing version 0.1.17
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Sync job

## Current Behavior
When syncing `*_audience_reports` streams, I got an error while converting the `mobile_app_id` column to integer. The value it contains is a string. The sync job thus fails because of the conversion error.

## Expected Behavior
The conversion is successful for this column and the sync job is in success when syncing `audience_reports` streams.

## Logs
[logs-999.txt](https://github.com/airbytehq/airbyte/files/10076113/logs-999.txt)

## Steps to Reproduce
1. Set up a connection using TikTok Marketing source. My use case is with a BigQuery destination. Not sure if there is the same thing with other destinations.
2. In Replication, select at least one `audience_reports` streams like `ads_audience_reports_daily`.
3. Sync

## Are you willing to submit a PR?

Yes 😄

**Comment by marcosmarxm** [comment]
@achaussende I saw you open the PR already, thanks!
