### ISSUE TITLE
0.40.22 webapp won't start with Docker! after upgrade in .env

### ISSUE THREAD

**Issue by naxels** [airbytehq/airbyte#19750]
## Environment
- **Airbyte version**:  0.40.22 (update in .env from 0.40.21)
- **OS Version / Instance**: RHEL 7 64bit
- **Deployment**: Docker
- **Step where error happened**: docker compose up

## Current Behavior
The airbyte/webapp container won't start, it keeps saying: restarting with a timer when running `docker ps`
other containers start up normally.
When going to the web interface, there is an nginx 503 error from the airbyte proxy (I think)

## Expected Behavior
The web app to start normally & be available.

## Steps to Reproduce
1. First run/setup 0.40.21 or earlier
2. docker compose down
3. change .env to 0.40.22
4. start with docker compose up

**Comment by marcosmarxm** [comment]
Did you get latest version of `.env` too just update the version?

**Comment by naxels** [comment]
You are correct, I didn't git pull, just updated .env
After git pull, it works, thanks!
