### ISSUE TITLE
show example inputs for specs in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1976]
## Tell us about the problem you're trying to solve
This sort of screen is very confusing: 
![Screen Shot 2021-02-05 at 10 27 12 AM](https://user-images.githubusercontent.com/120362/107073867-c0139500-679c-11eb-8f96-3230adbf9e5e.png)

I imagine a ton of users won't be able to or won't bother to transform this regex into a usable input like `2020-11-22T20:32:05Z` in this case.

## Describe the solution you’d like
We already have `examples` for a lot of specs, we should actually display them on the UI. I don't have a proposed design for this. Maybe something like:

----

**start date (required)**

Date from which to start pulling data.

Example: 
```
2020-11-16T00:00:00Z
```
[ input box ]

---

In this design we should probably support multiline descriptions and showing multiple examples (and multi-line examples). 

This probably also would require a change to where the error message displays.

## Describe the alternative you’ve considered or used
We could just allow multiline descriptions that include the HTML for examples, but it feels better to do this in a first-class way.

**Comment by cgardens** [comment]
Agreed. That error message is not human useable. 

Here's one proposal that leverages the examples array as you mentioned:
```
"${spec.description} (e.g. ${spec.examples.join(",")"
```

Maybe there's something better. If we do go with this approach, then I'm actually not sure if it's any better than just saying, put the examples in the description in the first place. It's the same from the end user's point of view, and from the connector creator's point of view it's a weird templating thing you need to learn about. 

I think I'm leaning slightly towards saying, that by convention you should put an example of what a valid input should look like in the description. We do this for timestamps in some places and it has been intuitive to me. @jrhizor wdyt? If you feel strongly that we should leverage the examples array, we can definitely do it pretty trivially. My preference is slight.

**Comment by jrhizor** [comment]
I think we could just say to put everything in the description if we allowed markdown. 

Multi-line examples (like our pasted file contents) are one complication. Descriptions could work for this if we supported markdown or html in descriptions.

Maybe we just do `"${spec.description} (e.g. ${spec.examples.join(",")"` for now since it's almost a one line change? And then longer term we settle on description-only w/formatting or a more customized UI.

**Comment by cgardens** [comment]
@jrhizor we actually do support html in descriptions. does that change anything?

**Comment by jrhizor** [comment]
Oh yeah we do with links, I've actually seen it...

I don't have a strong preference on this at all. Want just to nuke examples and use HTML descriptions? To do this we probably will want the description to be under the name but other than that it's just modifying some spec files.

**Comment by cgardens** [comment]
let's go with @jrhizor 's suggestion: `"${spec.description} (e.g. ${spec.examples.join(","))"` we can then change examples and descriptions however we see fit.
