### ISSUE TITLE
Tutorial for deploying Airbyte on Digital Ocean

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1977]
## Tell us about the documentation you'd like us to add or update
* I would like instruction on how to deploy Airbyte on Digital Ocean

## Are there any related areas of documentation that currently exist? Could you point to them? 
* We now provide a tutorial for how to connect Airbyte with MeiliSearch. MeiliSearch's docs recommend DigitalOcean (because of the price). It would be nice if our tutorial could also describe the digital ocean version that we provide a nice budget option for the slack => meilisearch tutorial.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368146627946) by [Unito](https://www.unito.io)

**Comment by harshithmullapudi** [comment]
Closing this as we have added deployment doc. #7192
