### ISSUE TITLE
MySQL Source hits OOM while snapshotting or reading a large table

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19779]
At the time of creating this issue I don't have much details unfortunately. The issue came up through oncall for a customer, who is trying to add a large table to a CDC sync job. The source connector runs out of memory after reading about 500MB or records although the pod has 3GB memory allocation. 

I tried using the same source in non-CDC mode and the connector has hit OOM after reading 100MB.

See [OC issue #1044](https://github.com/airbytehq/oncall/issues/1044) for details

**Comment by lmartinezruizit** [comment]
Hi, I have this problem and I wanted to know if there is any solution or any new information that can help me.

**Comment by eugen-korentsov** [comment]
Same issue
