### ISSUE TITLE
can't create /etc/nginx/conf.d/default.conf: Read-only file system

### ISSUE THREAD

**Issue by ASchmidtGit** [airbytehq/airbyte#19787]
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: Ubuntu
- **Deployment**: Docker Swarm - Portainer
- **Step where error happened**: Deploy

## Current Behavior
While deploying the WebApp service does not start and throws the following error:

`
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.d/20-envsubst-on-templates.sh: line 33: can't create /etc/nginx/conf.d/default.conf: Read-only file system
`

And because the WebApp cant start, the proxy service also throws an error:

`
BASIC_AUTH_USERNAME is set, requiring auth for user '""'
Adding password for user ""
starting nginx...
nginx version: nginx/1.23.2
2022/11/23 12:48:06 [emerg] 12#12: host not found in upstream "airbyte-webapp" in /etc/nginx/nginx.conf:15
nginx: [emerg] host not found in upstream "airbyte-webapp" in /etc/nginx/nginx.conf:15
`

## Expected Behavior
The services should start normally 

## Steps to Reproduce
1. Copy the docker-compose.yml and .env from airbyte git into portainer
2. Add the airbyte_development.yaml to the airbyte-temporal service with:

`    
configs: 
      - source: airbyte_development.yaml
        target: /etc/temporal/config/dynamicconfig/development.yaml
`

3. Add the nginx config (from airbyte git) to WebApp Service:

`    configs: 
      - source: airbyte_default.conf
        target: /etc/nginx/conf.d/default.conf
`

Do i need a running nginx service in my Swarm or should the config in webapp be enough?

**Comment by ASchmidtGit** [comment]
I added nginx as service in my swarm now im at the same error as here

https://github.com/airbytehq/airbyte/issues/19642

**Comment by ASchmidtGit** [comment]
I added nginx as serivce in my swarm and now i get this error:

`
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/11/25 11:58:43 [emerg] 1#1: host not found in upstream "airbyte-server:8001" in /etc/nginx/conf.d/default.conf:2
nginx: [emerg] host not found in upstream "airbyte-server:8001" in /etc/nginx/conf.d/default.conf:2
`

**Comment by ASchmidtGit** [comment]
Adding nginx was not the way to go.

If Airbyte needs to be deployed over docker compose as swarm the following needs to be done:

- Remove all instances of "container_name" every service in the compose file
- Rename "Server" to "airbyte-Server" and "db" to "airbyte-db"
- in .env change:
  - DATABASE_HOST from "db" to "airbyte-db"
  - DATABASE_URL from "jdbc:postgresql://db:5432/airbyte" to "jdbc:postgresql://airbyte-db:5432/airbyte"

Also if necessary all ports exept - 8000:8000 under airbyte-proxy can be removed

**Comment by linuxs** [comment]
Your mentioned docker-compose is actually broken based on my tests, the `airbyte-proxy` service is dependent on `webapp` and `server` which need to be renamed to `airbyte-webapp` and `airbyte-server` respectively.

**Comment by polmonso** [comment]
We're trying to deploy on portainer with a docker swarm and I believe we're facing the same issue. With your docker-compose it complains it can't locate airbyte_development.yaml. How were you deploying yourself?

**Comment by ASchmidtGit** [comment]
@polmonso We deployed with .env, so the production version. I assume you used the dev version?

I edited the port in airbyte-proxy from 8004 to the original value of 8000 and renamed webapp and server to airbyte-webapp and airbyte-server in my docker-compose posted above.
Then restarted the stack and everything booted and runs without any problems.

Here my .env also:

```
# This file only contains Docker relevant variables.
#
# Variables with defaults have been omitted to avoid duplication of defaults.
# The only exception to the non-default rule are env vars related to scaling.
#
# See https://github.com/airbytehq/airbyte/blob/master/airbyte-config/config-models/src/main/java/io/airbyte/config/Configs.java
# for the latest environment variables.
#
# # Contributors - please organise this env file according to the above linked file.


### SHARED ###
VERSION=0.40.22

# When using the airbyte-db via default docker image
CONFIG_ROOT=/data
DATA_DOCKER_MOUNT=airbyte_data
DB_DOCKER_MOUNT=airbyte_db

# Workspace storage for running jobs (logs, etc)
WORKSPACE_ROOT=/tmp/workspace
WORKSPACE_DOCKER_MOUNT=airbyte_workspace

# Local mount to access local files from filesystem
# todo (cgardens) - when we are mount raw directories instead of named volumes, *_DOCKER_MOUNT must
# be the same as *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/578
LOCAL_ROOT=/tmp/airbyte_local
LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
# todo (cgardens) - hack to handle behavior change in docker compose. *_PARENT directories MUST
# already exist on the host filesystem and MUST be parents of *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/577
HACK_LOCAL_ROOT_PARENT=/tmp

# Proxy Configuration
# Set to empty values, e.g. "" to disable basic auth
BASIC_AUTH_USERNAME=REMOVED
BASIC_AUTH_PASSWORD=REMOVED

### DATABASE ###
# Airbyte Internal Job Database, see https://docs.airbyte.io/operator-guides/configuring-airbyte-db
DATABASE_USER=docker
DATABASE_PASSWORD=docker
DATABASE_HOST=airbyte-db
DATABASE_PORT=5432
DATABASE_DB=airbyte
# translate manually DATABASE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB} (do not include the username or password here)
DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.29.15.001

# Airbyte Internal Config Database, defaults to Job Database if empty. Explicitly left empty to mute docker compose warnings.
CONFIG_DATABASE_USER=
CONFIG_DATABASE_PASSWORD=
CONFIG_DATABASE_URL=
CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.35.15.001

### AIRBYTE SERVICES ###
TEMPORAL_HOST=airbyte-temporal:7233
INTERNAL_API_HOST=airbyte-server:8001
CONNECTOR_BUILDER_API_HOST=airbyte-connector-builder-server:80
WEBAPP_URL=http://localhost:8000/
# Although not present as an env var, required for webapp configuration.
API_URL=/api/v1/
CONNECTOR_BUILDER_API_URL=/connector-builder-api

### JOBS ###
# Relevant to scaling.
SYNC_JOB_MAX_ATTEMPTS=3
SYNC_JOB_MAX_TIMEOUT_DAYS=3
JOB_MAIN_CONTAINER_CPU_REQUEST=
JOB_MAIN_CONTAINER_CPU_LIMIT=
JOB_MAIN_CONTAINER_MEMORY_REQUEST=
JOB_MAIN_CONTAINER_MEMORY_LIMIT=

NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT=
NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST=
NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT=
NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST=

### LOGGING/MONITORING/TRACKING ###
TRACKING_STRATEGY=segment
JOB_ERROR_REPORTING_STRATEGY=logging
# Although not present as an env var, expected by Log4J configuration.
LOG_LEVEL=INFO


### APPLICATIONS ###
# Worker #
WORKERS_MICRONAUT_ENVIRONMENTS=control-plane
# Cron #
CRON_MICRONAUT_ENVIRONMENTS=control-plane
# Relevant to scaling.
MAX_SYNC_WORKERS=5
MAX_SPEC_WORKERS=5
MAX_CHECK_WORKERS=5
MAX_DISCOVER_WORKERS=5
MAX_NOTIFY_WORKERS=5
SHOULD_RUN_NOTIFY_WORKFLOWS=false
# Temporal Activity configuration
ACTIVITY_MAX_ATTEMPT=
ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS=
ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS=
WORKFLOW_FAILURE_RESTART_DELAY_SECONDS=

### FEATURE FLAGS ###
AUTO_DISABLE_FAILING_CONNECTIONS=false
FORCE_MIGRATE_SECRET_STORE=false

### MONITORING FLAGS ###
# Accepted values are datadog and otel (open telemetry)
METRIC_CLIENT=
# Useful only when metric client is set to be otel. Must start with http:// or https://.
OTEL_COLLECTOR_ENDPOINT="http://host.docker.internal:4317"

USE_STREAM_CAPABLE_STATE=true
AUTO_DETECT_SCHEMA=false
```

**Comment by tiagosiebler** [comment]
Thank you @ASchmidtGit - had some problems getting this running in portainer and your posts here and on the forum helped figure out the missing pieces. This was probably slightly harder than usual since I'm still new to some of the portainer and docker concepts (such as docker configs, as silly as it may be).

For anyone else, here's what worked for me in portainer using the latest compose & .env from the repo:
https://github.com/tiagosiebler/portainer/tree/master/stacks/airbyte
