### ISSUE TITLE
Source Shopify: inventory_item table is missing data (essential for product cost)

### ISSUE THREAD

**Issue by unityanalytics** [airbytehq/airbyte#19782]
## Environment
- **Airbyte version**: 0.40.17
- **OS Version / Instance**: example macOS
- **Deployment**: Docker
- **Source Connector and version**: Shopify connector version is 0.1.39
- **Step where error happened**: Sync job

## Current Behavior
The connection runs without error, however there is only a default product shown in the table. 
This is missing key data for other added products and suggests the api is not working correctly.

## Expected Behavior
This should pull in a list of all product variants.

## Logs
Not an error - no logs

## Steps to Reproduce
1. Add several new products to a Shopify store with costs.
2. Connect through Airbyte to Shopify 
4. View the inventory_item table

**Comment by sh4sh** [comment]
Thanks for reporting this, I've added it to the team's backlog for review.

**Comment by bazarnov** [comment]
@unityanalytics Hello, could you please be more specific about which data that is not [listed here](https://shopify.dev/api/admin-rest/2022-10/resources/inventoryitem#resource-object) is missing for you?

**Comment by bazarnov** [comment]
No reply from the user. Closing this now, re-open once needed.
