### ISSUE TITLE
not setting the source name has confusing behavior

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#1978]
## Expected Behavior
~After filling out the fields for a source, I should be able to set up the source.~ see below

## Current Behavior
![Screen Shot 2021-02-05 at 10 41 40 AM](https://user-images.githubusercontent.com/120362/107075330-d0c50a80-679e-11eb-8411-1a1181f4e661.png)

Occasionally, the button is grayed out and I can't click it. There isn't any information in the console either.

## Steps to Reproduce
~I can't regularly reproduce this.~ see below

## Severity of the bug for you
Medium

## Airbyte Version
0.14.1-alpha

**Comment by jrhizor** [comment]
I figured out how to reproduce! Let me add a video!

**Comment by jrhizor** [comment]
![Uploading Screen Cast 2021-02-05 at 10.44.57 AM.gif…]()

**Comment by jrhizor** [comment]
The source name is required, but it doesn't show ***** as required. It seems like it would make more sense to allow the set up button and show an error next to the source name.

Definitely just a dumb error on my end but it's confusing. I went over the fields like 10 times and recorded this video before noticing.

**Comment by michel-tricot** [comment]
I wonder if we can make it less confusing by always letting people click the button and instead flash the fields that aren't passing validation. @johnlafleur @Jamakase what you think?

It is not the first time we're faced with that problem. Last time with was with the frequency (https://github.com/airbytehq/airbyte/issues/1858).

**Comment by johnlafleur** [comment]
The "Name" field should have a * to indicate it's compulsory. 
For missing fields, we should use the error state as in the following design:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A0

**Comment by michel-tricot** [comment]
So much better!

**Comment by cgardens** [comment]
okay! i will queue this up for next week.
