### ISSUE TITLE
Source Facebook Marketing: connector when used for ingestion into AWS S3, column cost_per_conversion in `ads_insights` is missing

### ISSUE THREAD

**Issue by azaveri7** [airbytehq/airbyte#19780]
## Environment
- **Airbyte version**:  0.32.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: AWS S3
- **Step where error happened**: No error appears. The ingestion from FB(meta) to S3 is successful. But the column is missing in the destination AWS S3 and Athena table.

## Current Behavior
*The tables and views from FB(meta) pipeline are ingested into AWS S3 successfully. But the column cost_per_conversion which is present in the schema REST call of Airbyte REST call is missing in AWS S3 destination.

The connector is present in the repository at location airbyte/tree/main/airbyte-integrations/connectors/source-facebook-marketing

*

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
I tested using Airbyte integration account but all records from the column `cost_per_conversion` of the `ads_insights` stream are null. I used Postgres destination.

**Comment by davydov-d** [comment]
@marcosmarxm @azaveri7 FB Marketing API does not return a field if it is missing a value. It means that there are no conversions.
I can confirm our test account has no conversions so it's an expected behavior. @azaveri7 can you please make sure you do have a conversion in the FB UI? Otherwise we should close this issue.
