### ISSUE TITLE
Cannot access Airbyte  at localhost:8000

### ISSUE THREAD

**Issue by toandm** [airbytehq/airbyte#19790]
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: GCP n1-standard-2 Debian 10
- **Deployment**: Docker
- **Step where error happened**: Deploy

## Current Behavior
After deploy Airbyte successfully, airbyte/proxy container is up, and I can access Airbyte at localhost:8000. However, after turning off and turning on the VM, airbyte/proxy container is not automatically started with Docker service. So I cannot access Airbyte at localhost:8000

## Expected Behavior
When restart VM, I should be able to access Airbyte at localhost:8000 normally.

## Steps to Reproduce
1. Deploy Airbyte version 0.40.22 following instructions here: https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine/
2. Turn off VM and turn it back on
3. SSH and port forward port 8000 to port 8000 in local machine
4. Open browser and access localhost:8000 > No info returned

Alternatively: 3. SSH and run command `curl localhost:8000`. No data is returned

## Are you willing to submit a PR?
Yes

**Comment by evantahler** [comment]
Closed via https://github.com/airbytehq/airbyte/pull/19791
