### ISSUE TITLE
Incorrect page title displayed on the Create Connection page

### ISSUE THREAD

**Issue by SofiiaZaitseva** [airbytehq/airbyte#19796]
## Environment
- **OS Version / Instance**: macOS
- **Deployment**: OSS
- **Step where error happened**: Setup new connection 

## STR
Go to Destination
Select existing Destination
Click "add source" button
Select existing source
Check page title

## Current Behaviour
Page title - New Source
<img width="1307" alt="Screenshot 2022-11-24 at 19 08 54" src="https://user-images.githubusercontent.com/108751383/203837500-9df2efa1-4fa9-4630-9adc-7d9c2aa8c3d9.png">

## Expected Behaviour
Page title - New Connection

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
