### ISSUE TITLE
Source Slack: new integration

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1980]
## Tell us about the new integration you’d like to have
We'd like to implement an Airbyte-native version of the Slack connector. The current singer-based connector uses a singer tap which does not receive many updates and is breaking in non trivial ways (#1932 #1945 #1979). We'd like to support the following resources: 

* channels (conversations https://api.slack.com/methods/conversations.list)
* channel members (conversation members https://api.slack.com/methods/conversations.members) 
* messages (https://api.slack.com/methods/conversations.history)
* users (https://api.slack.com/methods/users.list)
* threads (https://api.slack.com/methods/conversations.replies)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368087647099) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
TODO items remaining: 
1. Allow configuring lookback windows (threads lookback window and start_date for when the connector should start pulling data)
2. Allow configuring whether to join all channels or to sync data only from channels the bot is already in 
3. publish & update the current connector

**Comment by po3na4skld** [comment]
@sherifnada Do I still need to add these sources?

- channels (conversations https://api.slack.com/methods/conversations.list)
- channel members (conversation members https://api.slack.com/methods/conversations.members)
- messages (https://api.slack.com/methods/conversations.history)
- users (https://api.slack.com/methods/users.list)
- threads (https://api.slack.com/methods/conversations.replies)

**Comment by po3na4skld** [comment]
@sherifnada Do I still need to add these sources?

- channels (conversations https://api.slack.com/methods/conversations.list)
- channel members (conversation members https://api.slack.com/methods/conversations.members)
- messages (https://api.slack.com/methods/conversations.history)
- users (https://api.slack.com/methods/users.list)
- threads (https://api.slack.com/methods/conversations.replies)

**Comment by sherifnada** [comment]
They are already added in the current source-slack implementation, no need
