### ISSUE TITLE
Source Postgres CDC – inconsistent state in the BigQuery destination followed by a full sync

### ISSUE THREAD

**Issue by killthekitten** [airbytehq/airbyte#19801]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Debian 11, GCP e2-standard-4
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.22
- **Destination Connector and version**: BigQuery 1.2.7
- **Step where error happened**: Sync job

## Current Behavior

Our Postgres source is configured for CDC and the destination is using the "Insert" strategy. The syncs happen every hour, and all tables are set to incremental deduped + history.

We have detected a small number of rows that were incorrectly replicated to BigQuery – the record in the destination remained outdated, even after multiple successful syncs throughout the day. Eventually, a full sync was triggered and fixed the problem. 

The record has changed around 11:16AM UTC, the partial sync happened at 11:30AM UTC and the full sync came through at 5:30PM UTC (the screenshot below is CET):  

![image](https://user-images.githubusercontent.com/1201569/203853925-6b2b5ac6-d44b-406f-b940-a51de851397e.png)

During an investigation, I've noticed that the corresponding sync generated two records with the same timestamp in the `_raw` table, and the wrong one ended up being applied to the destination:

```sql
select 
    json_value(_airbyte_data, '$.status'),
    *
from 
    airbyte_live._airbyte_raw_faulty_table 
where 
    _airbyte_emitted_at > '2022-11-24' 
    and json_value(_airbyte_data, '$.id') = '131ecd44-1e2c-46ca-b1b5-b4772c7ce8f0'  
```

![Pasted Graphic](https://user-images.githubusercontent.com/1201569/203854192-0ec022fa-e43e-4ff5-aeca-30bd9a21769d.png)

We keep a history of application-level transactions in the source database, and only one transaction was recorded there for this row for that date, so I am confident the duplicate transactions in `_raw` were not coming from Postgres, and rather were generated by the sync process:

![image](https://user-images.githubusercontent.com/1201569/203854917-d3daf14f-de41-431b-a0b2-22caef4be892.png)

As expected, the row in the destination references the stale record from `_raw`.

```sql
select 
    _airbyte_ab_id
from 
    airbyte_live.faulty_table 
where 
    id = '131ecd44-1e2c-46ca-b1b5-b4772c7ce8f0'
```  

The full sync fixed the issue, after which the `_raw` table query showed one more record, this time with the correct data:

![airbyte ab id](https://user-images.githubusercontent.com/1201569/203855993-f1af1ef3-ce96-44ce-afa0-184feab6e481.png) 

## Expected Behavior

* I would expect the sync process to apply the correct change from `_raw` to the final data. 
* Also, I would like to avoid full syncs like this one, ideally. I've been seeing similar full syncs every now and then in the past, and it feels they are connected to the issue.

## Logs

I wouldn't be comfortable sharing the logs in the open, but I can send them to the airbyte team upon request.

## Steps to Reproduce

I'm not sure yet whether it is reproducible.

**Comment by bleonard** [comment]
@subodh1810 can you look into this?

**Comment by subodh1810** [comment]
Based on initial details : 
1. Postgres connector emits the records
2. The records seem to have the same primary key, emitted_at timestamp and LSN
3. Normalization doesn't process them in the right order

**Comment by bleonard** [comment]
There's an issue where if the same reocrd is in the same batch, then end up with the same emitted_at, which could cause a problem with normalization.

Because we are processing them in order, let's make the `emitted_at` Instant.now()

**Comment by killthekitten** [comment]
@subodh1810 your summary looks correct, however I can't confirm whether the LSNs are the same or not.

**Comment by killthekitten** [comment]
@bleonard do you have an idea as to how these records ended up in the same batch? The transactions that produced the rows were committed on different days, and that's what is puzzling me.

**Comment by bleonard** [comment]
@killthekitten  Are you saying the two changes to any given row were on different days and tere were many syncs in between and somehow they ended up with the same emitted_at? That definitely does not make sense to me.

**Comment by killthekitten** [comment]
@bleonard yes, that's what I see. Here are the changes to the same row that should have been replicated on different days (as it appears in the version tracker in the source database):

![Two changes to the same row on different days](https://user-images.githubusercontent.com/1201569/203854917-d3daf14f-de41-431b-a0b2-22caef4be892.png)

The older change is so old in fact, that it predates the connection, and must've been added during the initial full sync, or more likely during one of the connection resets.

**Comment by killthekitten** [comment]
@bleonard @subodh1810 I hope the last comment of mine hadn't stalled the investigation 😅 Let me know if there's anything else I can help with!

**Comment by bleonard** [comment]
Well, it's very confusing! @killthekitten 
But that's reality for you. 

Was the first sync you did _before_ or _after_ August 15? That is to say, were both of these part of the initial sync or just the earlier one?

**Comment by killthekitten** [comment]
@bleonard the initial sync happened somewhere mid September, so after August 15. The earlier version should have been added around that time. It's probably worth mentioning that since the initial sync we reset and reconfigured the connection a couple of times.

**Comment by killthekitten** [comment]
@bleonard I looked at the `_raw` table again, and the duplicate rows are now gone. After all, it could be that the initial sync is out of the picture, as table was probably emptied many times since the initial sync took place.

**Comment by evantahler** [comment]
Our connectors have changed dramatically since this issue was originally filed.  If this issue still exists, can you please file a new issue with a new sync log using the latest connectors and platform?
