### ISSUE TITLE
Source HubSpot: not pick up archived entities

### ISSUE THREAD

**Issue by mdibaiee** [airbytehq/airbyte#19838]
## Environment
- **Airbyte version**:  N/A
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: HubSpot 0.2.3
- **Destination Connector and version**: N/A
- **Step where error happened**: Sync job

## Current Behavior

- HubSpot connector relies on `hs_lastmodifieddate` to recognise changes to entities such as `deals`, however, when an item is archived in HubSpot, `hs_lastmodifieddate` does not  change, while another property, `archivedAt` reflects the timestamp of the entity being archived. So archiving an entity in HubSpot is not being picked up by the connector.

## Expected Behavior
- The connector can recognise updates to `archivedAt` and emit the updated document

## Logs
N/A

## Steps to Reproduce
1. Setup a HubSpot connector
2. Archive a Deal
3. The deal will not be updated in your materialization to reflect `archived: true`

## Are you willing to submit a PR?
Maybe

**Comment by YowanR** [comment]
@mdibaiee We would absolutely love to see a PR from you to tackle this issue!

**Comment by artem1205** [comment]
Hi, @mdibaiee ,
I've added new stream `Deals Archived` in https://github.com/airbytehq/airbyte/pull/24980
I'd recommend You to use it in Incremental mode to collect all deleted `deals`, as Hubspot saves archived records only for 90 days
