### ISSUE TITLE
Trim Connection List Endpoint

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#19849]
The connections/list endpoint has some fields that are unnecessary for the frontend. To improve performance we should slim down this endpoint to be closer to _just_ what the frontend needs.

1. Remove `sourceId` and `destinationId` from the response since they are not used for the primary use case of this endpoint, and can be found in the attached source and destination objects.
2. Scope down the source portion of the response to only `sourceId`, `sourceName`, `name`, and `icon`.
3. Scope down the destination portion of the response to only `destinationId`, `destinationName`, `name`, and `icon`.
4. **The connectionConfiguration should be removed from the source and destination objects.**
5. [LOW] Remove `latestSyncJobCreatedAt` from the response. It's only used on Source and Destination list pages. This should be done after [getEntityTableData](https://github.com/airbytehq/airbyte/issues/19852) is migrated to the backend.

Depends on #20264, need to create PR against the branch in this PR.

**Comment by krishnaglick** [comment]
We should try to do https://github.com/airbytehq/airbyte/issues/19875 before this.

**Comment by krishnaglick** [comment]
After a conversation with Jimmy, the connectionConfiguration should be removed from the source and destination objects.

**Comment by gosusnp** [comment]
Clarification question: is trimming the `/web_backend/v1/connections/list` enough?

**Comment by krishnaglick** [comment]
Are you asking if these changes should only apply to the `/v1/web_backend/connections/list` endpoint? If so, yes.

If it could be done in tandem with https://github.com/airbytehq/airbyte/issues/19850, that would be optimal but it should be fine to do in any order.

**Comment by dizel852** [comment]
Changes described in the issue description(1-3) were made and pushed to https://github.com/airbytehq/airbyte/pull/20264
