### ISSUE TITLE
Display connector maturity level in the UI

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1984]
## Tell us about the problem you're trying to solve
A connector is an evolving piece of software. We want to set the proper expectations for an Airbyte user when using a connector.

## Describe the solution you’d like
When selecting a connector, a user should see if it is an early, not super tested connector or very mature one (# of levels to be defined).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368088111297) by [Unito](https://www.unito.io)

**Comment by timroes** [comment]
Closing this since we show nowadays the GA/Beta/Alpha status in the UI.
