### ISSUE TITLE
web_backend/v1/connections/list should allow filtering by source or destination

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#19850]
There are several places in the frontend where we do a full connections list call _just_ to filter connections against sources or destinations.

Ideally we can provide a `workspaceId` and a `sourceId` or a `destinationId` to get a list of connections associated with that source or destination.

**Comment by gosusnp** [comment]
Is the response the same? If yes, could we have optional filters on `connections/list`?
For example, `connections/list?destination_ids=A&destination_ids=B&destination_ids=C`? (querystring param not necessarily the actual syntax)

**Comment by krishnaglick** [comment]
Clarified the ticket, we'll add filtering by source or destination id to the connections list endpoint.

**Comment by dizel852** [comment]
Need to create separate FE issue

**Comment by krishnaglick** [comment]
Closing this as completed since the backend work was done.
