### ISSUE TITLE
Allow turning off a destination for all sources

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#1985]
## Tell us about the problem you're trying to solve
I want to sometimes perform maintenance on a database. I don't want to attempt to sync to the database during this time. If this database is a destination, I don't want any writes attempted to it. Clicking each entry in the Airbyte UI is tedious.

## Describe the solution you’d like
I would like a button to turn off a destination for all sources. It would be nice to be able to toggle them all back on afterwards.

Alternatively, provide a safe classname for all destination connection checkboxes so that I'm not doing something risky with the workaround below (which assumes there aren't any other random checkboxes on the page - there aren't at this time).

## Describe the alternative you’ve considered or used
Go to the page for the destination and run:

```
[...document.getElementsByTagName('input')].filter(x => x.type == "checkbox").map(x => x.click())
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368088173705) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Great idea @roshan !
