### ISSUE TITLE
Move getEntityTableData logic into the backend

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#19852]
The frontend has a method called [getEntityTableData](https://github.com/airbytehq/airbyte/blob/a8c72121f8fd50407425250d3a6ddc3756db8b55/airbyte-webapp/src/components/EntityTable/utils.tsx#L17). It takes a set of sources or destinations, connections, and a source or destination definitions (which are a combined list of source or destination definitions along with their respective latest calls and data).
That's 4 API calls all to combine their data for frontend usage, as well as a lot of iteration. Moving all this logic into the backend lets us get that information in a single API call, and the data processing will be better places.

This should replace the sources/list or destinations/list calls for the sources list or destinations list pages.

**Comment by gosusnp** [comment]
Check feasibility and improvement on the backend beforehand to make sure we are tackling the right problem
