### ISSUE TITLE
Don't skip reset when saving and resetting disabled connection

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19861]
Allow disabled connections to reset. Just need to remove the check from here:

https://github.com/airbytehq/airbyte/blob/5755dd84b9809b6851a05492f02b771a484c0cb6/airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionReplicationTab.tsx#L124

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
