### ISSUE TITLE
Resetting a destination for a connection is synchronous in the browser and displays no feedback

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#1986]
## Tell us about the problem you're trying to solve
When I click the 'Reset' button in the 'Reset My Data' dialog, I want to know if something has happened. Currently, the UI displays no feedback until the Reset has completed (which can be a long long time) and then it suddenly displays the 'Reset' as another entry in the log (which is great). 

## Describe the solution you’d like
Clicking the 'Reset' button drops you back to the page for the connection and lists the 'Reset' operation with the logs, just like with 'Sync Manually'.

## Describe the alternative you’ve considered or used
I keep the 'Network' tag open in Chrome DevTools to be sure things are working.

**Comment by michel-tricot** [comment]
Indeed, https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/src/main/java/io/airbyte/scheduler/client/DefaultSchedulerJobClient.java#L101 is waiting for reset synchronously to finish

**Comment by ChristopheDuong** [comment]
Duplicates of https://github.com/airbytehq/airbyte/issues/1781

**Comment by jrhizor** [comment]
We should check to see if this is fixed. If it is we can resolve this and #1781

**Comment by cgardens** [comment]
fixed by: https://github.com/airbytehq/airbyte/pull/2246
