### ISSUE TITLE
Connection streams vertical and right margin do not align with other cards

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19874]
Seen in master, the top, bottom, and right margin of the streams card is too large and does not align with the rest of the

![Image](https://user-images.githubusercontent.com/168664/204559011-3d98b23d-a571-47ab-860a-51ee213dd45f.png)

This is related to the changes in #18187

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
