### ISSUE TITLE
Add failure reason to Test Failure Segment events

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#19898]
There are two events related to setup failures:
- Airbyte UI Source Test Failure
- Airbyte UI Destination Test Failure

We see some common errors that users receive, and we'd like to offer specific help around common errors that is more specific to the error they see. This would require passing the error message into the Segment event as an additional attribute. 

Examples of places we could address common errors: 
- In Docs for that connector, we could add common errors to the Troubleshooting section, like on the Postgres doc
- In emails, when the user is unable to resolve the error, we can suggest they pass that error to their peer (for example, in the case it's a db config issue)
- In product, we can start a chat with the relevant error message and share it with Support, so that Support doesn't need to ask for it again. We can also potentially utilize help articles if we find users want to self-serve troubleshooting information using help articles in Intercom.
- In Analytics, we can parse the error message to determine commonalities to direct which ones we should address first on the product side, and how to improve those error messages.

Examples of errors we see:
<img width="574" alt="Screen Shot 2022-11-29 at 12 19 34 PM" src="https://user-images.githubusercontent.com/38087517/204640369-867d36c9-a22d-45a8-8b84-a65bfbb4d7de.png">
<img width="342" alt="Screen Shot 2022-11-29 at 12 17 27 PM" src="https://user-images.githubusercontent.com/38087517/204640370-b77a772e-0d66-4606-9e70-20e0aaabf561.png">
<img width="330" alt="Screen Shot 2022-11-29 at 12 14 48 PM" src="https://user-images.githubusercontent.com/38087517/204640375-7bf2e498-ae82-479e-84f2-3fc115c994c1.png">
<img width="331" alt="Screen Shot 2022-11-29 at 12 14 01 PM" src="https://user-images.githubusercontent.com/38087517/204640376-40e830bd-df4d-4e6e-b4c8-0c2b736704c3.png">
<img width="330" alt="Screen Shot 2022-11-29 at 12 04 18 PM" src="https://user-images.githubusercontent.com/38087517/204640377-1db24dfd-0683-4f19-8b45-eb1bf4cdbbd7.png">

**Comment by pedroslopez** [comment]
+1!

This probably involves updating the track calls in https://github.com/airbytehq/airbyte/blob/cf28f7a01f55d13c64515e2ea4ee7a9a4300b78b/airbyte-server/src/main/java/io/airbyte/server/scheduler/DefaultSynchronousSchedulerClient.java#L201 with the FailureReason. FailureReasons are already a part of the JobOutputs and we're sending them to Sentry at this spot (take a look at the [reportError method](https://github.com/airbytehq/airbyte/blob/cf28f7a01f55d13c64515e2ea4ee7a9a4300b78b/airbyte-server/src/main/java/io/airbyte/server/scheduler/DefaultSynchronousSchedulerClient.java#L230) in that same file), so it should just be a matter of passing it along to segment as well.

**Comment by nataliekwong** [comment]
@letiescanciano this is the issue I was referencing earlier in our live chat. Worth checking with @evantahler 's team on where we stand on this!

**Comment by erohmensing** [comment]
@nataliekwong There's an [open PR](https://github.com/airbytehq/airbyte-platform-internal/pull/5033) about ready to be merged! Would love to know what you were chatting about to make sure it gives you the info you need

**Comment by erohmensing** [comment]
Here is an example of what they will look like - the message you currently see in the pop up is actually a "message" coming from the connection_status - that will be stored in `check_connection_message`. If we get a separate `failureReason` object, we'll store that separately. 

![image](https://user-images.githubusercontent.com/22333512/223873848-14a3bf01-f017-4f90-9352-5668efde0c39.png)

from [comment](https://github.com/airbytehq/airbyte-platform-internal/pull/5033#issuecomment-1461014242)

**Comment by erohmensing** [comment]
Note - this is actually added to the backend segment events, not the frontend ones - so this data lives in the `api.connector_jobs` table

**Comment by letiescanciano** [comment]
thanks @erohmensing.
@nataliekwong  I think we need for analytics having that info in the BE events will work but if we want to make decisions on the product (open support chat) or trigger behaviors in external tools (emails) we need the to have the error in the FE.
I was checking this, and we are showing the error to the user, so we have access in the FE and it's easy to add it to the events

**Comment by nataliekwong** [comment]
@erohmensing appreciate the update and I think this will be very valuable for downstream analytics in the backend events!

 @letiescanciano thanks! Agreed for triggering chameleon or in-app support we would need it in the FE events as well.  Could you add to FE events?

**Comment by letiescanciano** [comment]
Of course!

**Comment by letiescanciano** [comment]
@erohmensing do you know if we categorized error types somehow? I was thinking it would be interesting to have this info as well as the error message so we can bucket error types and maybe offer different suggestions to users (in the future)
