### ISSUE TITLE
Freshdesk source documentation does not list all supported streams

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#19890]
@lgomezm has added support for more streams in this [PR](https://github.com/airbytehq/airbyte/pull/13332), but the PR did not update the documentation. Currently documentation for Freshdesk source still lists only these sources:

- [Agents](https://developers.freshdesk.com/api/#agents)
- [Companies](https://developers.freshdesk.com/api/#companies)
- [Contacts](https://developers.freshdesk.com/api/#contacts) (Native Incremental Sync)
- [Conversations](https://developers.freshdesk.com/api/#conversations)
- [Groups](https://developers.freshdesk.com/api/#groups)
- [Roles](https://developers.freshdesk.com/api/#roles)
- [Satisfaction Ratings](https://developers.freshdesk.com/api/#satisfaction-ratings)
- [Skills](https://developers.freshdesk.com/api/#skills)
- [Surveys](https://developers.freshdesk.com/api/#surveys)
- [Tickets](https://developers.freshdesk.com/api/#tickets) (Native Incremental Sync)
- [Time Entries](https://developers.freshdesk.com/api/#time-entries)

but the source connector now supports the following sources:
```
Agents,
    BusinessHours,
    CannedResponseFolders,
    CannedResponses,
    Companies,
    Contacts,
    Conversations,
    DiscussionCategories,
    DiscussionComments,
    DiscussionForums,
    DiscussionTopics,
    EmailConfigs,
    EmailMailboxes,
    Groups,
    Products,
    Roles,
    SatisfactionRatings,
    ScenarioAutomations,
    Settings,
    Skills,
    SlaPolicies,
    SolutionArticles,
    SolutionCategories,
    SolutionFolders,
    Surveys,
    TicketFields,
    Tickets,
    TimeEntries,
```

**Comment by juweins** [comment]
@grishick Let this be my 3rd contribution. I will handle this!
