### ISSUE TITLE
Update form field labels in connection form to match design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#19900]
Update label design to match the latest in Figma:

* Description should be shown in tooltip
* Required fields no longer marked with *

Current:
![image](https://user-images.githubusercontent.com/63751206/204642491-a296ad08-0c96-43ea-b733-fe983457aa5f.png)

Proposed:
![image](https://user-images.githubusercontent.com/168664/204644345-41521c39-191f-4fcd-83e7-373013471402.png)

Figma:
https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=857%3A24319&node-id=865%3A52984&viewport=124%2C-519%2C0.25&scaling=min-zoom&starting-point-node-id=865%3A52984&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
