### ISSUE TITLE
Case sensitive postgres table names

### ISSUE THREAD

**Issue by blocka** [airbytehq/airbyte#1991]
## Expected Behavior
When a source postrges table has capital letters, it should not error

## Current Behavior
There is an error like `Exception in thread "main" java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "public.address" does not exist`

public.address does not exist but public."Address" does

## Steps to Reproduce
1. Create source database with tables with capital letters
2. Select tables
3. Try to sync

## Severity of the bug for you
Critical

## Airbyte Version
0.14.1-alpha

**Comment by cgardens** [comment]
we think this issue is going to be resolved by work done on this issue: https://github.com/airbytehq/airbyte/issues/2007. once that work is done we will verify that this issue has been fixed as well. if it is not fixed we will then fix this as well.

**Comment by cgardens** [comment]
i think this actually been fixed already. @blocka what version of the postgres source are you using? https://github.com/airbytehq/airbyte/issues/2007
