### ISSUE TITLE
Source Postgres: Don't misparse "infinity" timestamps

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#19952]
Seen in https://github.com/airbytehq/oncall/issues/1124

Postgres supports certain special values for dates and times - https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-VALUES

Of these, `infinity` and `-infinity` pose a special challenge, because they're actually persisted into the db (the other values get converted to normal timestamps). `source-postgres` handles `-infinity` poorly today; it's read as `+292269055-12-02T23:00:00.000000 BC`. At minimum, it should not have the leading `+` prefix. Arguably, it should actually set the value to `Instant.ofEpochMilli(Long.MAX_VALUE)` / `Instant.ofEpochMilli(Long.MIN_VALUE)`.

If this feature exists across other sources: maybe we should update WellKnownTypes to accept +/-infinity as valid date/timestamp values? I think it would be cool to do that research as part of this issue.

**Comment by akashkulk** [comment]
Some very initial research shows that this is actually happening at the JDBC driver level: 
- https://www.postgresql.org/message-id/4D557EC7CC2A544AA7C1A3B9CBA2B36724E70E5374@exchange03.epbs.com
- https://docs.teradata.com/r/Teradata-Aster-Client-Guide/May-2017/Connect-Using-Database-Drivers/Configure-Aster-Database-SQL-Settings/JDBC-Troubleshooting-and-Limitations/Infinity-and-Negative-Infinity-Timestamp-Conversion

Either two options here : 
- Convert this value to a reasonable(?) timestamp by checking if `resultSet.getString()` is equal to infinity. 
- Add to WellKnowntypes and handle it in dst as part of data types v2

Probably some additional research is needed to see whether +/- infinity are valid for other databases, as that makes a more compelling argument for Option 2

**Comment by seanglynn-thrive** [comment]
@edgao @bleonard has there been any traction / alternative solutions on this?
We're currently blocked while trying to parse the `infinity` value within a postgres timestamp field. It seems to get rendered by Airbyte as: `+292278994-08-16T23:00:00.000000Z`

We've already tried without any joy :( 
+ Updating the stream schema via the Airbyte API (changing field type from `date-time` -> `string`)
+ ALTERing the destination table (changing the **BigQuery** datatype from `TIMESTAMP` -> `STRING`)

We're still getting an exception within the Normalization phase when we try to normalize the raw data in the `_airbyte_raw*` table into tabular format. Exception logs:

```
2023-04-11 16:16:11 normalization > Database Error in model problematic_model (models/generated/airbyte_incremental/problematic_model.sql)
2023-04-11 16:16:11 normalization >   Invalid timestamp: '+999999999-12-31T23:59:59.999999-18:00'
2023-04-11 16:16:11 normalization > Done. PASS=39 WARN=0 ERROR=1 SKIP=0 TOTAL=40
```

**Comment by edgao** [comment]
This is also touching on a separate issue, which is that bigquery and postgres impose different restrictions on valid timestamps. bigquery's max timestamp is `9999-12-31 23:59` (https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type).

Airbyte doesn't currently do anything to make data fit in the destination, but this is coming up on our roadmap soon. I'm actually curious - what do you _want_ to happen in this case? A couple options that we've been thinking about (but definitely open to other suggestions!): 
* error out (i.e. current behavior)
* clamp values to their valid range (so in this case, we'd write `9999-12-31 23:59`)
* do a "minimal edit" to get the value into a valid range (e.g. `9999-08-16`, i.e. only modify the year, and preserve the month/date/hh/mm/ss)
* write a sentinel value (e.g. `null`) and dump the raw string value to an `error` column (whether that's one `error` column per stream, or one error column per source field)
* write a sentinel value (e.g. `null`) and dump the raw string value to another table

(fyi @evantahler since you've also been thinking about this)

**Comment by evantahler** [comment]
@seanglynn-thrive I'd love to hear more about what Infinity means to you, in your dataset, and if any of @edgao's suggestions above (adding a limit (year 9999 max), nulling it out) would be OK?

**Comment by stephane-airbyte** [comment]
I think as far as the source is concerned, we should thrive for maximum accuracy, meaning that we should return `"+infinity"` or `"-infinity"`. This way, a postgres->postgres sync will leave the data unchanged. As you've already explained, different databases have different constraint WRT date ranges, and so the destinations should be the ones doing the clamping
