### ISSUE TITLE
Refactor ConfiguredCatalog from protocol to mirror AirbyteCatalog in the API

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#1996]
## Tell us about the problem you're trying to solve
* In the Airbyte Protocol, we have AirbyteCatalog and ConfiguredCatalog
* In the API, we have only a AirbyteCatalog object that contains a stream of two fields:
  * AirbyteStream
  * AirbyteStreamConfiguration

We should mirror and unify our object representation

## Describe the solution you’d like
We should refactor the ConfiguredCatalog to be part of AirbyteCatalog with default values as it is done in the API and use the `selected` boolean to toggle a stream on and off.
So it would be easier to generate a Catalog from a source and pipe it to forward it to a destination.

## Additional context
See comment: https://github.com/airbytehq/airbyte/pull/1934#discussion_r570445415

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368211874499) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@timroes is this issue still relevant / causing pain for FE? Or should we close it?

**Comment by timroes** [comment]
I don't think this issue was coming from any requirements or issues in the frontend, so there is nothing from my side preventing closing it.

**Comment by cgardens** [comment]
closed as no longer relevant.
