### ISSUE TITLE
Source Sendgrid: date-times processed as string

### ISSUE THREAD

**Issue by attaxia** [airbytehq/airbyte#19969]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Debian
- **Deployment**: Docker
- **Source Connector and version**: Sendgrid 0.2.16
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Sync job

## Current Behavior
The Sendgrid source handles date-times as Strings, which means they're saved as strings in the destination which causes issues in our BI tool later down the line. For example, the ``messages`` model has a column called ``last_event_time`` which will hold string values such as ``2022-10-17T09:54:26Z``.

## Expected Behavior
Use the appropriate data type which should result in the correct column type in my destination.

## Steps to Reproduce
1. Run any Sendgrid integration

## Are you willing to submit a PR?
I looks like it may be a simple fix by editing this file:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-sendgrid/source_sendgrid/schemas/messages.json

And changing 
```
    "last_event_time": {
      "type": "string"
    }
```
to:
```
    "last_event_time": {
      "type": "date-time"
    }
```

But I'm not sure it's that simple nor do I have the resources to test it. If it is that simple, I can of course open a PR (this applies to multiple schemas for this integration)

**Comment by marcosmarxm** [comment]
Let me know if you need assistance to create the pull request @attaxia

**Comment by attaxia** [comment]
Hi @marcosmarxm,

If you can confirm that resolving the issue is indeed as simple as making the change like I suggested in the appropriate schema files, then no, I can manage.

But if there are other code changes needed, or test cases to be updated then that's outside my realm of expertise and I cannot make the PR.

**Comment by marcosmarxm** [comment]
Should be something like:
```json
"last_event_time": {
  "type": "string",
  "format": "date-time"
}
```
