### ISSUE TITLE
Destination Snowflake: Emit STATE message after each commit operation

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#19991]
The ticket here is for Destination Snowflake to emit STATE message after a commit operation. The action items for this ticket are to:
* update the functionality of `stateManager` to mark the STATE message as `committed`
* validate that a STATE message was received by platform

**Comment by grishick** [comment]
Notes from grooming:
once this is implemented, verify that platform starts subsequent attempts from the last  `STATE` message emitted by the destination. If this is not happening - file an issue for platform and make sure it gets prioritized. The desired effect of implementing this is that incremental sync jobs can resume from the last `STATE` message emitted by the destination.
