### ISSUE TITLE
PRD: Exporting connectors from connector-builder to workspace

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#19994]
## Tell us about the problem you're trying to solve
* the connector extensibility developed a connector builder
* the UI is already part of the webapp (/connector-builder)
* the server is implemented in python and runs in a docker container

## Sample open questions
* How can users add their custom connector to their workspace?
* How does versioning work?
* How do we incentivize developers to share their connector?

## Acceptance criteria
* PRD describing the desired user user flow for exporting a connector from the connector-builder to their workspace
* Connector developers can export a connector to their workspace on OSS
* Connector developers can export a connector to their workspace on Cloud
* PRD ratified by an engineer from the Cloud team

## Out of scope
* Do we need to migrate to micronaut / what are the implications

**Comment by girarda** [comment]
Link to PRD: https://docs.google.com/document/d/1_SntxDHADkd4tWLjrZEQO_Hs_xhCVXwP6exfSz4lXXw/edit?usp=sharing
