### ISSUE TITLE
Provide better documentation on how to set up Snowflake account for Snowflake destination

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#20003]
Fivetran documentation provides SQL script that the user can run to create all necessary roles grant all necessary permissions on Snowflake. We should add similar instructions to simplify this for the user.

**Comment by Asrst** [comment]
hi @grishick, 

i see the setup script for snowflake destination is already available in this [docs page](https://docs.airbyte.com/integrations/destinations/snowflake/?__hstc=27854691.8fcca31460a0a680354e0dbbc40b985a.1672760490662.1672760490662.1672760490662.1&__hssc=27854691.1.1672760490663&__hsfp=1871955199&_ga=2.247913295.959615829.1672757441-1926423595.1672757441). Can you elaborate what more instructions you are looking to add?
