### ISSUE TITLE
Source Snowflake - connector Schema not used

### ISSUE THREAD

**Issue by sheshan-doye-konvergeai** [airbytehq/airbyte#20018]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Snowflake source 0.1.24
- **Step where error happened**:Setup new connection

## Current Behavior
schema is one of the credentials while configuring snowflake source.
but it discovers all the tables from all the schema's in the current database.

## Expected Behavior
only tables in provided schema should get discovered.

## Steps to Reproduce
1. configure Snowflake source for particular schema for a database with multiple schemas
2. during discover_schema , we get streams/tables from all the schemas in that database

**Comment by rodireich** [comment]
A cloud customer is seeing this issue as well: specifying a schema in the [connector settings](https://cloud.airbyte.io/workspaces/2293a3fe-8228-4a50-b522-7788abcbcc76/source/a2c77226-faf2-47b4-8dbf-5552dd00df64/settings) doesn't get reflected in the connection and all schemas that the user has access to is pulled.

**Comment by bleonard** [comment]
if schema is filled out, we would filter the `discover` to just tables in that schema.
In other conenctors, I think we also comma separated list.

**Comment by rodireich** [comment]
Looks like we can tweak the JDBC url to pull a certain schema only. This will also help speeding up certain calls. See https://docs.snowflake.com/en/sql-reference/parameters.html#client-metadata-request-use-connection-ctx .

We can make the following change in snowflake-source:
- The Schema field will become optional.
- In case a schema is specified, Only tables from matching schema will be pulled to catalog.
- Not specifying a schema will pull all tables from all allowed schemas, in case replication needs to traverse more than a single schema - this is essentially how it behaves today as the schema field is redundant.

Snowflake jdbc does not allow specifying multiple schemas in a comma separated value. So unless we implement filtering ourselves, the API is build to allow a single schema at a time.

**Comment by rodireich** [comment]
One thing to be careful about with this change - all existing snowflake source connections will be affected as they all specify a schema (a required field today)

**Comment by rodireich** [comment]
A workaround customers can implement before we publish this fix:
Add to the JDBC param field the following:
`CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX=true`

This should make the catalog only discover the specified schema and not any table from another schema.
