### ISSUE TITLE
Support legacy MySQL versions

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2004]
## Tell us about the problem you're trying to solve
One of our users was unable to replicate MySQL 5.1 data using Airbyte.

This the error, which does appear to reflect the issue:

```
- \tat io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:90) [io.airbyte.airbyte-integrations.bases-base-java-0.11.2-alpha.jar:?]","2021-02-08 19:11:28 INFO (/tmp/workspace/142/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - \tat io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:76) [io.airbyte.airbyte-integrations.connectors-source-mysql-0.11.2-alpha.jar:?]","2021-02-08 19:11:28 INFO (/tmp/workspace/142/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - Caused by: java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required","2021-02-08 19:11:28 INFO (/tmp/workspace/142/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - \tat com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) 
```

The user said this was not a critical use case for them.

## Describe the solution you’d like
Should we add a legacy mysql connector (or allow swapping drivers for different versions in the current source)?

I'm mostly creating this ticket just to track the demand for this feature.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368147039934) by [Unito](https://www.unito.io)

**Comment by tweinreich** [comment]
I encountered this today with a legacy MySQL 5.1 DB and I would appreciate this feature.

**Comment by misteryeo** [comment]
Closing this as [JDBC doesn't support this legacy version](https://docs.oracle.com/cd/E17952_01/connector-j-5.1-en/connector-j-versions.html) and supporting 5.6+ is sufficient.
