### ISSUE TITLE
Low Code Connector tutorial example config update

### ISSUE THREAD

**Issue by ethanbrown3** [airbytehq/airbyte#20047]
### Tell us about the documentation you'd like us to add or update.
I am going through the tutorial for the low-code connectors. There is an error with the `datetime_format` in the example `exchange_rates_tutorial.yaml` file (see [here](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/config-based/tutorial/5-incremental-reads.md)).  The `end_datetime` object has `datetime_format: "%Y-%m-%d %H:%M:%S.%f"`. If you run `python main.py read --config secrets/config.json --catalog integration_tests/configured_catalog.json` with this config you will get the following error:
```
...
raise ValueError(\"unconverted data remains: %s\" %\nValueError: unconverted data remains: +00:00\n", "failure_type": "system_error"}}}
```
If you 
update the datetime to include the `+00:00` offset ie `datetime_format: "%Y-%m-%d %H:%M:%S.%f+00:00"`. It will work.

### If applicable, add links to the relevant docs that should be updated
- https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/config-based/tutorial/5-incremental-reads.md

**Comment by juweins** [comment]
Hi! I just went through the tutorial and was able to reproduce the error. Likewise, I made adjustments to the documentation as per your suggestion.

**Comment by ethanbrown3** [comment]
Awesome thanks!
