### ISSUE TITLE
Source Postgres - Incremental sync Postgres (Aurora) to Redshift fails: `Invalid date-time: No timezone information`

### ISSUE THREAD

**Issue by jan-benisek** [airbytehq/airbyte#20059]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: EKS
- **Deployment**: k8s with helm
- **Source Connector and version**: Postgres 1.0.30
- **Destination Connector and version**: Redshift 0.3.51
- **Step where error happened**: Sync job

## Current Behavior
- when syncing data from Aurora (postgres) to Redshift, I get an error

## Expected Behavior
- sync should work

## Logs
- `2022-12-05 10:04:44 ERROR c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No timezone information: 2022-10-11T15:34:15.102435`
[log.txt](https://github.com/airbytehq/airbyte/files/10153144/log.txt)
- The incremental columns, for example: `created_at`, are `TIMESTAMP WITHOUT TIME ZONE NOT NULL,`

## Steps to Reproduce
1. Create Postgres source (Require SSL, Standard Replication Method, no tunnel. All schemas)
2. Create Connection. Some streams are "Full refresh | Overwrite", other are "Incremental | Append" with cursor field. No transformation, syncing Raw data (JSON)
3.

## Are you willing to submit a PR?
Maybe, if easy to fix.

**Comment by prateekmukhedkar** [comment]
Notes from sprint planning - related to JSON validation. Source writes the schema, platform validates the json and we get a warning there.
