### ISSUE TITLE
Destination: Azure Blob Storage - spill to new object after X data size

### ISSUE THREAD

**Issue by jfox-teine** [airbytehq/airbyte#20051]
## Tell us about the problem you're trying to solve
For the Azure Blob Storage destination, large objects on Full Overwrite, Incremental Append and Full Append get at least initially written to a single blob object. This decreases potential downstream read time compared to if we spilled the table over many objects.

## Describe the solution you’d like
Spill JSONL writer for Azure Blob Storage to new file after X size to facilitate downstream reading of the table for large objects. Writer would need to both check the size of the current output vs the current buffered output stream but also check the size of the current object being written to, and if larger than X, start a new object.

X should be a variable in the destination setup. Suggested default of 500 MB.

## Describe the alternative you’ve considered or used
The alternative workaround I've used is to create many views on a large object and load them separately. I then modify the cursor field value in the db for the table after moving those blobs into the folder for the large object. It's very hack and slash and not recommended.

## Additional context
This would also help get around the maximum limit of 50,000 file operations on a single blob for large table objects. With greater than 244 GB of destination JSONL size and the default stream buffer rate of 5 MB, a user would be hit with the 50,000 file operation error. Starting a new file after X size would essentially eliminate the possibility of this happening.

## Are you willing to submit a PR?
I am willing to submit a PR but this connector is written in Java and that's not my area of expertise. It would likely be a modification to the AzureBlobStorageJsonlWriter function.

**Comment by itaseskii** [comment]
Hey @jfox-teine :wave:  the fix for this issue is available at #21467. If you have the time feel free to  look into the code and provide feedback if any.

**Comment by jfox-teine** [comment]
Hey @itaseskii I'll review this tomorrow morning. Thanks!

**Comment by jfox-teine** [comment]
Reviewed. Seems to cover exactly what I'm looking for. Even cleaned up a few spelling and grammar errors.

**Comment by ttilberg** [comment]
Before creating an issue, I thought I'd ask here:

Am I misunderstanding this feature?

I just set up an Azure Blob Destination with limit set to `200`. I'm currently loading an initial sync from SQL Server, and it's at 820 MB and counting. This should be splitting the file in realtime, and not after the fact or some such, right?

<img width="1208" alt="image" src="https://github.com/airbytehq/airbyte/assets/7969650/bafe2aff-845d-4a4c-a129-2483600b4b6c">

<img width="622" alt="image" src="https://github.com/airbytehq/airbyte/assets/7969650/c84566d9-f25c-469a-9c8c-89d6c2d72497">

Is this worth filing a new issue, or am I just misunderstanding something?

**Comment by ttilberg** [comment]
I've come to realize this PR _only_ changes the JL format output, though the UI doesn't specify that. I'll create an issue.
