### ISSUE TITLE
SAT: Add tests for all JSON schema features that are not supported by UI

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20063]
JSON schema is more flexible than what the current connector form UI can handle. However, it's currently not clearly documented what will work and what won't, so a connector developer is left with trial and error.

The SATs should check whether the spec is "UI-compliant" and the documentation should mention that test.

Tasks
* Find all features not supported today. List so far:
   * Pattern properties https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties
   * allOf https://json-schema.org/understanding-json-schema/reference/combining.html#allof
   * anyOf https://json-schema.org/understanding-json-schema/reference/combining.html#anyof
   * not https://json-schema.org/understanding-json-schema/reference/combining.html#not
   * if-then-else https://json-schema.org/understanding-json-schema/reference/conditionals.html#if-then-else
   * dependentSchemas https://json-schema.org/understanding-json-schema/reference/conditionals.html#id5
   * special date and date-time cases (there should be a pattern defined along with the format)
* Extend SATs
* Reference in documentation

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by flash1293** [comment]
Some additional requirements copied over from https://github.com/airbytehq/airbyte/issues/12330

We would it as one of the standard tests for each connectors so that before publishing a connector the developer could bring the spec into compliance.

So far the subset I have in mind is:
* don't use `not`, `anyOf`, or `allOf`.
* `type` MUST be set. for pure JSONSchema there are reasons why you might want to leave it unset, but for our use case, doing that is just a headache. See the long conversation Benoit and I had in the linked issue.
* the `oneOf`s stuff that is mentioned in the [docs you linked](https://docs.airbyte.com/connector-development/connector-specification-reference/#using-oneofs).
* When `airbyte_secret` can be used. I think the only types that should have `airbyte_secret` added to it are `string`, `number`, `array<string>` , and `array<number>`. But we have to do all of this other bonkers stuff right now to cover our behinds because theoretically someone could naively stick that flag anywhere. A compile time loud failure saves a lot of confusion at runtime.
* Honestly saying that the `type` field for a spec must either be a value (i.e. `type: string`) or an array with 1 or 2 values. If 2 values, one of them must be null (i.e. `type: [string]` or `type: [string, null]`). Having to reason about `type: [object, array, string]` is very scary for secrets. 
* all of the possible values for a `oneOf`s should be of the same type. i.e. no `oneOf`: object, string, array. Again just super scary to deal with clearly especially for secrets. if you're using `oneOf`, let it be of a `oneOf` multiple objects and then nest whatever fields you need inside that object.

**Comment by flash1293** [comment]
Changes:
* Only strings, integers and numbers can be secrets, arrays and objects do not work correctly in the UI
* Fail on non_secrets hidden as they will cause weird behavior in the UI
* "type" can't be an array, except for the case where it's two values and the second one is "null" - all other cases are not handled by the UI
* The array "items" type can't be an array
* The array "items" type either needs to be string, array or has an enum defined (just regular number won't work in UI)
* type can either be a value directly or an array with two values with the second one being null (only the first one is respected by the UI)
* arrays can only have a single "items" definition, with its type either being object or string or an enum
* airbyte_secret can't be used on arrays and objects
* not, anyOf, patternProperties, allOf, if, then, else, dependentSchemas and dependentRequired is not allowed as it won't be rendered as expected
* If `format: date/date-time` is specified, it should have the corresponding pattern set as well
* If a date/date-time like pattern is set, it should have the corresponding format as well

**Comment by evantahler** [comment]
cc @flash1293 & @erohmensing - Does this PR close https://github.com/airbytehq/airbyte/issues/19725 ?
