### ISSUE TITLE
Resolve ❌ destinations in connector dependency workflow

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20075]
Just like https://github.com/airbytehq/airbyte/issues/19451, we've got a number of destinations that currently have problems in the connector dependency workflow.  A good list to work from is here: https://github.com/airbytehq/airbyte/pull/19993#issuecomment-1336456298.

<img width="801" alt="Screenshot 2022-12-05 at 8 37 48 AM" src="https://user-images.githubusercontent.com/303226/205692453-fb75fb90-53bb-4f4f-a07d-728fe67a1eb6.png">

Of note, the strict-encrypt connectors should not be in the seeds, so we should adjust the python code to know this.

**Comment by erohmensing** [comment]
I think that may be why they are ⚠️ and not ❌ , but I'd be down to check that extra and make it `✅ (not in seed) (expected)`

**Comment by evantahler** [comment]
We could make a new status emoji, like 🔵 for "not there, but expected"
