### ISSUE TITLE
ListBox: Allow passing custom footer element

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#20098]
Step no.3 for https://github.com/airbytehq/airbyte/issues/19359

* Create a footer prop for the ListBox component

[Figma](https://www.figma.com/proto/Xa2bg6dg5AoxA1mFJ3HXsG/MULTI-CLOUD?node-id=374%3A9541&scaling=min-zoom&page-id=374%3A9485&starting-point-node-id=374%3A9486&show-proto-sidebar=1) example:
<img width="632" alt="Screen Shot 2022-12-05 at 4 05 52 PM" src="https://user-images.githubusercontent.com/65251165/205742670-79a06814-41ae-43fb-a964-a4931271b348.png">

**Comment by timroes** [comment]
Discussed this. We're no longer planning to do this, since there is no proper accessible way to build this.
