### ISSUE TITLE
New Source: Posthog

### ISSUE THREAD

**Issue by robbertbrouwers** [airbytehq/airbyte#2010]
## Tell us about the new integration you’d like to have
Source: https://posthog.com/
open source product analytics

I want to be able to move events from posthog ( stored in postgresql or clickhouse and accessible through api: https://posthog.com/docs/api/overview) into file storage and/or DWH (Snowflake, Synapse, Redshift, Bigquery).

## Describe the context around this new integration
I am helping a client setting up a new product analytics infrastructure and expect to do this more often in the future. Event data should be available outside of the source tool, in order to apply analytics and other data related use cases (recommender systems, reminder notification for abonded carts etc)

## Describe the alternative you are considering or using
I'm afraid it'll be a custom integration, which i will write in python.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368088624825) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@robbertbrouwers thanks for opening this issue and giving context. We'd love to support Posthog for sure. One question though: would this rely on a webhook to pull data from Posthog or is it possible to pull data in batch? Airbyte currently doesn't support webhooks.

**Comment by robbertbrouwers** [comment]
As far as I can tell, the general API provides access to all data stored in the application: 

_The other API is more powerful and allows you to perform any action as if you were an authenticated user utilizing the PostHog UI. It is mostly used for getting data out of PostHog, as well as other private actions such as creating a feature flag. This uses a 'Personal API Key' which you need to create manually (instructions below). This API Key is private and you should not make it public nor share it with anyone. It gives you access to all the data held by your PostHog instance, which includes sensitive information._

(explained on: https://posthog.com/docs/api/overview). 

The common objects (Elements, Events, People,  _Trends, Feature Flags_ ) all have their own endpoint with pagination support. 

I don't expect Events to change after they have been created. I do expect this behavior for the people table (according to the docs, one person can have multiple ids, which i guess are added over time), so there would be a need for some sort of CDC logic on (some of) the tables. 

Does this answer your question @sherifnada ?

**Comment by sherifnada** [comment]
@robbertbrouwers yup this is awesome information. Thanks for the context! Looks like we can totally support Posthog then. Some questions: 

1. Will you need all the available endpoints? (elements, events, people, trends, user, feature flags)
2. Which destinations will you need this for? 
3. What timeline are you looking for on this connector? Is this blocking for you to be able to use Airbyte? 
4. Would you be able/open to contributing this connector? Not required at all, but we are currently a couple of weeks away from beginning implementation assuming we pick this up next, so it would move up the timeline potentially depending on your availability.

**Comment by timgl** [comment]
Hey, Tim here (CTO of PostHog). Super cool you want to integrate with us.

The easiest way of doing this is probably [our plugins](https://posthog.com/docs/plugins/overview). They'll trigger on every event (or created user), and from there you'll be able to call an airbyte endpoint to send the data on. Let me know if you have any questions about that.

**Comment by robbertbrouwers** [comment]
@sherifnada, 

1. I can see potential value in all of them, but my priority would be for events and people. 
2. Snowflake would be my main destination and/or they could land in any blob storage (in preferred order: Azure, AWS, GCP) and i would pick them up from there. 
3. Not in too much of a rush; i'd rather wait a couple of weeks/months and have a robust solution provided by you; i have some other work i can focus on first, while using an occasional 'dump' of the current posthog events to develop and test. 
4. At this moment not, as i've got a couple of projects going. I would like to follow the development where possible to see how this is done; that way I can contribute in the future and already be familiar with the process.

**Comment by sherifnada** [comment]
@timgl thanks for the pointer! At the moment Airbyte doesn't support webhook-style ingestion (though we will be working on that in Q2 most likely). It looks like we could still get a lot of mileage out of the "private API" mentioned here: https://posthog.com/docs/api/overview. Are there any gotchas we should be aware of when using it? 

One question I have from reading the private-API docs is: is it possible to filter requests by date? e.g: in Airbyte, syncs run periodically, so to extract data efficiently we need a way to extract only the relevant data from the source. Is there any way for a sync to extract only the data generated in the last 24hrs but not before? there's a `cursor` field in the API responses, but is that persistent across different requests to the API, or is it not re-usable?

**Comment by timgl** [comment]
@sherifnada So there's no way of posting events into an API currently?

Your altnerative is to use the events API, so you can call `/api/events?date_from=2020-05-25T14:06:33.584171Z`, then iterate 100 at a time to get all the events. You won't be able to get newly created users this way

**Comment by sherifnada** [comment]
@timgl correct, there is currently no way of posting events into an API but it's on our roadmap since a number of sources/interesting use cases rely on it. Thanks for the pointers!

**Comment by keu** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**
_if partially, mention which endpoints are webhook-based_

**Available authentication modes (API key/Oauth/other)**
[API Key](https://posthog.com/docs/api/overview#personal-api-keys-recommended)

**Creating an account**
_self-service free account available? yes

**How to populate the account with data?**
Annotations and Cohorts can be created through API.
Also, there is a client [library](https://github.com/posthog/posthog-python) to generate the rest of entities

**Available streams for sync**

- [Elements](https://posthog.com/docs/api/elements)
- [Events](https://posthog.com/docs/api/events) (incremental)
- [People](https://posthog.com/docs/api/people)
- [Trends](https://posthog.com/docs/api/trends) need extra parameters
- [Feature flags](https://posthog.com/docs/api/feature-flags)
- [Annotations](https://posthog.com/docs/api/annotations)
- [Cohorts](https://posthog.com/docs/api/cohorts)
 
**Integration supports incremental sync?**
Events

**Other information/blockers**
