### ISSUE TITLE
Source MySQL: Add "Data to Sync" CDC Parameter

### ISSUE THREAD

**Issue by adammacleod** [airbytehq/airbyte#20112]
## Tell us about the problem you're trying to solve

We are trying to sync a 10B+ row table from MySQL to Snowflake. We have successfully synced 1B rows from MySQL but it took 24~ hours. We only have 3 days of binlogs available and we can't increase the retention. This means that a 10B row sync won't complete before we run out of binlogs to continue the CDC incremental load.

## Describe the solution you’d like

I would like to be able to start a CDC job and sync new changes only, opting to not take a snapshot when the job is first run. This is the same as the "New Changes Only" option which is present in the MSSQL connector: https://airbytehq.github.io/integrations/sources/mssql/#cdc-config

Using this I could create one job to sync the changes, and another job which does a one-off load of a view in the source DB which contains the amount of history I'd like. It would also give me the flexibility to divide the source table into multiple views and sync smaller chunks of history.

## Describe the alternative you’ve considered or used

I would be open to hearing how other people load such large tables in Airbyte. Other options I have considered:

- A filter option for connections, so I could filter the source dataset (eg: `where date_created >= date '2020-01-01'`).
- Parallel loads which are able to achieve higher throughput than a single source container.

## Are you willing to submit a PR?

Yes, dependant on the size / scale of the change.

**Comment by akashkulk** [comment]
Closing, not on the roadmap for now
