### ISSUE TITLE
Connectors excluded from cloud should be set to private

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20116]
## What
A few connectors cannot be used in Cloud for a reason or another.

We've been excluding them by adding the connector ID to a [list of excluded connectors in the webapp](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/core/domain/connector/constants.ts#L19).

This hack isn't needed anymore now that connectors can be scoped to specific workspaces.

## How
For each connectors, [follow these instructions](https://internal-docs.airbyte.io/runbooks/enable-private-connectors-for-workspace).
* the `public` field should be false (this should be done in the mask yaml file, not by modifying the db)
* insert a actor_definition_workspace_grant if a workspace should be able to use the connector
* there should be no grants for connectors that should be completely hidden

## Acceptance criteria
- [ ] [getExcludedConnectorIds](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/core/domain/connector/constants.ts#L19) is deleted from the webapp
- [ ] Connectors that should be hidden are still hidden
- [ ] Connectors visible to individual workspaces are still scoped to those workspaces (youtube analytics and shopify)
- [ ] New process for hiding connectors is documented

**Comment by brianjlai** [comment]
grooming notes:
- this will make it more difficult to know which connectors are hidden/private. need to query to db to get the full picture
- for the purpose of this ticket: hidden == private
- need to document how to access the list of private connectors for less technical consumers

**Comment by girarda** [comment]
this can be controlled through the connector manifests
