### ISSUE TITLE
Obtain public developer application for the Pardot source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#20122]
Public developer app
[Docs](https://developer.salesforce.com/blogs/2020/11/setting-up-salesforce-oauth-for-pardot-api-authentication)

[EPIC] Oauth developer applications https://github.com/airbytehq/airbyte/issues/6070

**Comment by ycherniaiev** [comment]
according to docs seems like Pardot uses Salesforce developer app to authneticate the users
