### ISSUE TITLE
Each streams download status

### ISSUE THREAD

**Issue by sheshan-doye-konvergeai** [airbytehq/airbyte#20129]
## Tell us about the problem you're trying to solve

Currently, Airbyte shows a combined status of connection (pending, running, succeeded).
I would like to have a more granular status i.e. status of each stream individually.

## Describe the solution you’d like
airbyte-worker logs the info regarding which stream is being currently getting download, So airbyte already have the information it need to show status of each stream.
it can be used to reflect  in the connection status api response.

**Comment by marcosmarxm** [comment]
Thanks @sheshan-doye-konvergeai I added the request to platform backlog.

**Comment by davinchia** [comment]
The stream UI now supports this.
