### ISSUE TITLE
Create documentation for Destination namespace example settings

### ISSUE THREAD

**Issue by matter-q** [airbytehq/airbyte#20137]
Create documentation for Destination namespace example settings (button "Learn more")

![image](https://user-images.githubusercontent.com/66960359/205943267-2510b08b-8055-422e-a4d2-606bd02fd044.png)

https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=865%3A52984&scaling=min-zoom&page-id=857%3A24319&starting-point-node-id=865%3A52984&show-proto-sidebar=1

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
