### ISSUE TITLE
upgrade to dbt 0.19.x

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2013]
We're on 0.18.1. Upgrading caused build problems resulting in us [downgrading](https://github.com/airbytehq/airbyte/pull/2012).

This ticket is for safely upgrading to the latest versions of dbt and making sure that from-scratch installs work properly.

**Comment by davinchia** [comment]
Done with https://github.com/airbytehq/airbyte/pull/2987!
