### ISSUE TITLE
Share common eslint rules between airbyte-webapp and airbyte-webapp-e2e-tests

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20140]
Follow up to #20134

Create a common set of base eslint rules shared between airbyte-webapp and airbyte-webapp-e2e-tests. Each project will extend or override the rules based on what makes sense for each, but at the base, many of the rules should be common.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by ambirdsall** [comment]
This issue will be effectively addressed by https://github.com/airbytehq/airbyte/issues/24464
