### ISSUE TITLE
Update configuration from control messages in synchronous commands

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#20145]
Following https://github.com/airbytehq/airbyte/issues/17909, which introduced the capability for the platform to update connector configuration during syncs, we also want to update configuration during the other commands (e.g. check, discover)

We can use the UpdateConnectorConfigHelper introduced in the previous PR to perform the updating, which already handles things like masking secrets.

This will involve initializing the AirbyteApiClient in airbyte-server, as well as updating inputs to the jobs as required to have the right information for calling the endpoints (e.g. source or destination id)

**Comment by bazarnov** [comment]
@pedroslopez Is there any ETA for this one?

**Comment by pedroslopez** [comment]
@bazarnov The PR is in review https://github.com/airbytehq/airbyte/pull/20894
