### ISSUE TITLE
Todoist: New Sandbox

### ISSUE THREAD

**Issue by delenamalan** [airbytehq/airbyte#20160]
We need a need sandbox account for [Todoist](https://todoist.com/) for https://github.com/airbytehq/airbyte/pull/20046 please.

**Comment by delenamalan** [comment]
I can't edit the labels, unfortunately. @sajarin would you perhaps be able to assist in adding the `team/connectors-python`, `unblockers` and `connectors/source/todoist` labels please? 🙏

**Comment by igrankova** [comment]
Created an account: Todoist free trial account
API Token is saved to the LastPass
Opened a ticket for obtaining a sandbox: https://get.todoist.help/hc/en-us/requests/724207

**Comment by igrankova** [comment]
@delenamalan The support team added a year of Pro time to the account so we have access to all features and can use this free account for testing purposes.
