### ISSUE TITLE
Source Facebook Marketing: add new enumeration action_report_time to AdInsights stream class

### ISSUE THREAD

**Issue by pnavarromuttdata** [airbytehq/airbyte#20197]
## Tell us about the problem you're trying to solve
In the `AdInsights` [class](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py) is not available the `action_report_time` enumeration as the [Facebook Marketing docs](https://developers.facebook.com/docs/marketing-api/reference/adgroup/insights/#:~:text=value%20is%20%5B%22action_type%22%5D.-,action_report_time,-enum%7Bimpression%2C%20conversion) suggest. 

## Describe the solution you’d like
Add the  `action_report_time` enumeration into the  `AdInsights` class.

## Describe the alternative you’ve considered or used
-

## Additional context
-

## Are you willing to submit a PR?
Yes, I'm working on it

**Comment by marcosmarxm** [comment]
I added the request to connector backlog.

**Comment by midavadim** [comment]
@pnavarromuttdata 

I have checked the documentation for [Facebook Marketing docs](https://developers.facebook.com/docs/marketing-api/reference/adgroup/insights/#:~:text=value%20is%20%5B%22action_type%22%5D.-,action_report_time,-enum%7Bimpression%2C%20conversion)

and 'action_report_time' is not in the list of Fields of "AdInsights" class.

'action_report_time' is used only as request parameter.

@pnavarromuttdata could you please clarify this request if you have more information, becuase I am willing to close this issue as invalid.

**Comment by pnavarromuttdata** [comment]
maybe the changelog description and issue name is not clear at all, I understand that is not a field, you are right, but think about all request parameters are defined into adinsights class into the facebook marketing source connector, if you check the class, you will see another request parameters defined there like breakdowns, time_increment, or actions_breakdowns that into the facebook docs are defined as request parameters also.

So, I don't think that this issue is invalid... maybe the issue description or the changelog description could be improved

**Comment by pnavarromuttdata** [comment]
The [PR](https://github.com/airbytehq/airbyte/pull/26345/files) merged

**Comment by midavadim** [comment]
I close this Issue because the requested feature has been already implemented .
