### ISSUE TITLE
Connection name label in connection create page is larger than other labels

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20194]
## Current Behavior
![Screen Shot 2022-12-07 at 11 14 52](https://user-images.githubusercontent.com/168664/206270312-7ba5e162-22c3-4b88-b3b5-920ed7d4582a.png)

## Expected Behavior
The size of the connection name label should be the same as the rest of the labels in the form

## Steps to Reproduce
1. Go to Create a new connection
2. Select a source and a destination
3. Look at the name field at the top

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
