### ISSUE TITLE
Timeplus destination connector: send data to Timeplus for real-time analysis/visualization/alerting

### ISSUE THREAD

**Issue by jovezhong** [airbytehq/airbyte#20195]
## Tell us about the new connector you’d like to have
![Timeplus Overview](https://timeplus.io/timeplus.overview.png)
It'll be great to have a **destination connector** for Timeplus, so that as a developer they can collect data from database/file/social and send them to Timeplus with Airbyte. http://timeplus.com/ is an end-to-end streaming analytics platform, offering both fully-managed cloud service as well as on-prem deployment. Users can load real-time data from Kafka/Pulsar/Ably/etc and explore them visually, run streaming SQL to gain real-time insights, and visualize them with real-time charts and take actions with real-time alerts.

* **Which source and which destination?** Destination
* **Do you need a specific version?** The connector just needs to work with the latest Timeplus version (in public beta, biweekly release)

## Describe the context around this new connector
* **Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.**
Airbyte is a great platform to move data from A to B. In Timeplus, only a limited number of streaming data sources are supported. When the user needs to run a query to enrich real-time data with data in database or file, they need to push the data to us with the ingest REST API. With the new timeplus destination connector, our users can access hundreds of sources on airbyte ecosystem and push those data to Timeplus for analysis/visualization/alert
* **How often do you want to run syncs?**
Ideally as soon as possible, even sub-second. But the current 5-minute minimal sync interval is fine. We are looking forwards to the new streaming support from AirByte, so that more amazing use cases can be done, such as once a new contacts in HubSpot, in the next minute, the data will update the chart/alert in Timeplus 
* **If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name?** 
Timeplus Cloud now is in public beta, free to sign up and use. Feel free to sign up one on https://beta.timeplus.cloud with Google/Microsoft social account or use an email to create password. At `Timeplus`, we will be more than happy to partner with AirByte

## Describe the alternative you are considering or using
**What are you considering doing if you don’t have this integration through Airbyte?**
Data could be collected by Airbyte then sent to Kafka or Pulsar, but this will require extra configuration effort, infra cost. I also found the current AirByte doesn't work well with Confluent Cloud or StreamNative Cloud.

## Are you willing to submit a PR?
Yes, this is the plan. I just forked the code and created a branch for that. https://github.com/timeplus-io/airbyte/blob/feature/timeplus-destination/airbyte-integrations/connectors/destination-timeplus/destination_timeplus/destination.py Hopefully to get the PR ready later this month.

**Comment by sh4sh** [comment]
Thanks so much for your contribution, looking forward to seeing the new connector in action!
