### ISSUE TITLE
Prevent the user from editing stream if there is a breaking schema change

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20201]
When the user has a breaking schema change, they should not be allowed to break the schema ([Figma](https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A37260&t=FCfVs1rpFzu3Yk62-1))

![image](https://user-images.githubusercontent.com/168664/206292748-1a205367-fb2c-4805-8acc-87521fb17bec.png)

* Needs to be supported in both the old table and new table design

**Comment by tealjulia** [comment]
For v1, we are blocking the entire form on Replication Tab.  Users will only be able to edit the name or click "review changes".

The ideal state would be that users can edit their non-breaking changes preference and also the replication frequency even if there is a breaking change.
