### ISSUE TITLE
Stream Details panel - update predefined cursor and primary fields behavior

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#20227]
## Tell us about the problem you're trying to solve
At the moment, we don't show the selected cursor field in the new details panel(https://github.com/airbytehq/airbyte/pull/19219) if it was predefined and we can't change it.

## Describe the solution you’d like
After discussing possible UX solutions with @edmundito and @Upmitt we agreed:
- Fill in the Cursor column with disabled `<RadioButtons>'s`
- Select the cursor field which is predefined
- - Fill in the Primary Key column with disabled `<CheckBox>'s`
- Select the primary key field which is predefined

~~Since we don't have a "selected disabled" state in the current implementation of `<RadioButtons>', so need to update it first:
https://github.com/airbytehq/airbyte/issues/20089~~

Not relevant for `<RadioButton>`, the desired state is supported.
But still relevant for `<CheckBox>` component: https://github.com/airbytehq/airbyte/issues/20246 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by dizel852** [comment]
After adding a storybook for `<RadioButton />` turned out that we support the "disabled selected" state:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/20929344/206478237-98274055-d9ac-4e3b-8223-5bd7d98f09d6.png">
