### ISSUE TITLE
Can create a woocommerce source using API with the wrong "api_key" and "api_secret".

### ISSUE THREAD

**Issue by wasantha-dsg** [airbytehq/airbyte#20222]
## Environment

Deploying Airbyte 0.40.15 on our server through the docker image.

## Current Behavior

- Create a woocommerce source using API with the wrong "api_key" and "api_secret".
- But the response is always a success with response code 200. It creates a source using the wrong "api_key" and "api_secret" which is unable to connect.

## Expected Behavior

The response should fail with some error code.

## Logs
![postman](https://user-images.githubusercontent.com/64017551/206431380-d56ad67d-5d86-461b-ab78-e9bc082a8e1f.PNG)
![test_img_2](https://user-images.githubusercontent.com/64017551/206431453-3a62fe96-e338-4476-9783-63a6780279d1.PNG)

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/19903
