### ISSUE TITLE
Migrate connector builder to micronaut

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20221]
## Tell us about the problem you're trying to solve

The connector builder server is currently implemented in Python using the FastAPI framework.
The platform team made a stance that all services running as part of the platform should be built on top of Micronaut.

The main benefits are:

- The more we can lean on the platform team for infra, the less we need to worry about it
- Single OpenAPI -> server pipeline
- Single framework to define APIs

What problems migrating to micronaut will not fix:

- standard build pipeline: the service will still need Python, which is not part of the build pipeline for the existing micronaut services
- offload OC responsibilities: ConnExt will still need to support the service because the platform team won't have much context on what the service does
- OpenAPI generator for JavaXRS does not support anyOf, oneOf, and other advanced schema structures

Con: This introduces a potentially brittle interface between micronaut (running on the jvm) and the CDK (running in Python vm)

### Part 1: Setting up a micronaut service
The following files need to be updated to instantiate a micronaut service
1. build.gradle
   1. Generate Java classes from openapi spec. [airbyte-api module has an example of generating Java classes from an openapi specification](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/build.gradle#L55-L98)
   2. Build and run a java application. [airbyte-cron is an example of a simple service running on micronaut](https://github.com/airbytehq/airbyte/blob/master/airbyte-cron/build.gradle)
2. Dockerfile
   1. [The Docker container needs both Java and Python3.9](https://github.com/airbytehq/airbyte/pull/20393/files#diff-c471dfde5ea669b6ad3ed2f4744c3fe7a8acaec412b53bac30c9dfae0123ac7dR1-R31)
3. Micronaut configuration
   1. [airbyte-cron has a good starting point for application configuration](https://github.com/airbytehq/airbyte/blob/master/airbyte-cron/src/main/resources/application.yml#L1)
   2. [The endpoints need to be enabled](https://github.com/airbytehq/airbyte/pull/20393/files#diff-a7e204aa7f24f419112102367b27545e56901ef736db29d0f4a47307a5b16d72R2-R26)
5. CI/CD:  [It's important that the build pipeline still runs format and tests on the python code](https://github.com/airbytehq/airbyte/blob/master/buildSrc/src/main/groovy/airbyte-python-docker.gradle)
6. Controller:
  * Forwards the requests to Python
  * Should use `@executesOn` to avoid reading from the source on the main threadpool
### Part 2: Shelling out to python
   1. Shelling out can be done using a ProcessBuilder

   ```
        final ProcessBuilder processBuilder = new ProcessBuilder("python3.9", "connector_builder/entrypoint.py", command, argumentAsJsonString);
        processBuilder.redirectErrorStream(true);

        final Process process = processBuilder.start();

        final List<String> results = IOUtils.readLines(process.getInputStream());
   ```

   2. The interface is a list of string from stdout instead of structured data.
      *  stdout will include stacktraces on error and log messages
      *  Need a reliable way to extract the response we need to return to the FE
      * Need a reliable way to detect and forward failures
   3. The Python entrypoint is a CLI script. Pseudo-code that should really be using argparse or Click
  ```
op = sys.argv[1]
arg = sys.argv[2]

api = DefaultApiImpl()

if op == "read":
    print(api.read(arg))
elif op == "list":
    print(api.list(arg))
elif op == "manifest_template":
    print(api.manifest_template())
else:
    print(error)
   ```

## Describe the alternative you’ve considered or used
* Keep using FastAPI
* Reimplement the connector builder in Java and only shell out when calling the read operation

## Acceptance criteria
* The connector builder server runs on top of micronaut
* The API endpoint boilerplate is generated from the openapi spec
* The manifest, streams/list, and stream/read endpoint behave identically as they currently do from the FE perspective
* CI fails if the python or java tests fail
* CI fails if any python or java files are not properly formatted

## Open questions
* What is the load the connector builder needs to support?
* Should the connector builder's release cycle be decoupled from the platform release cycle?

## Additional context
* [Spike](https://github.com/airbytehq/airbyte/pull/20393)
* [How to Micronaut](https://docs.google.com/document/d/1CYHg8gNWcCRoqQienfQ5I0p1Lk56HEiCgfelZJfl1kk/edit#)

**Comment by brianjlai** [comment]
(alex)
grooming notes:
- is the team comfortable with supporting a Java system?
- alternative: only use the CDK read command and implement the connector builder logic in java
  - cleaner line between the Python and Java / CDK and connector builder
  - ^this will require rewriting some logic of the connector builder (one time cost) 
- where will additional features go? (eg limiting the number of pages)
- alternative: can we forward the requests to a python service?

next steps:
- document trade off / missing features from implementing the server in python
- example of 2-3 features we may add in the next 6 months (incremental reads, max number of pages, specific stream slice, etc.)

- @girarda to update investigation ticket
acceptance criteria:
- what do we gain/lose from moving to micronaut?
- what is the interface with the CDK?
- any performance/load considerations?
- example of 2-3 features we may add in the next 6 months (incremental reads, max number of pages, specific stream slice, etc.)
- signed off from platform team

**Comment by girarda** [comment]
closing as duplicate
