### ISSUE TITLE
Connector form: Improve logs rendering on failing connection test

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20238]
With advanced mode enabled, the logs from the connection test job are shown below the form together with the error message:
<img width="484" alt="Screenshot 2022-12-08 at 17 19 15" src="https://user-images.githubusercontent.com/1508364/206504670-5c4ec146-5223-45b7-b2fc-8134abcad654.png">

This UI is confusing users because it looks like it failed and worked at the same time. By replacing the standard collapsable with a more subtle "Show logs" button, this UI can be cleaned up. In this case it also makes sense to always show this button even in non-advanced mode.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
