### ISSUE TITLE
OpenAPI Fast-api python generator does not support unions, allOf, anyOf, or oneOf

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20248]
See generator documentation here: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-fastapi.md

See relevant slack thread here: https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1670470677250839?thread_ts=1670469267.630799&cid=C02TL38U5L7

This means that we cannot directly reference the Connector Manifest json schema in our connector builder server spec, as it contains oneOfs. We will therefore need to do a workaround where the connector builder server endpoints take in a generic "object"

**Comment by girarda** [comment]
closing because we don't use the fast-api python generator anymore
