### ISSUE TITLE
Airbyte favicon is a bit blurry

### ISSUE THREAD

**Issue by Jamakase** [airbytehq/airbyte#2025]
## Current Behavior
![image](https://user-images.githubusercontent.com/3767150/107438812-b9519d00-6b63-11eb-85f4-2637afd3e86c.png)

## Steps to Reproduce
Open page in chrome from MacBook with Retina display

## Severity of the bug for you
Very low

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368147344068) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
fixed.
