### ISSUE TITLE
[Connector Builder] Pull in labels and descriptions of fields from manifest JSON schema

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20271]
As discussed in [this PR thread](https://github.com/airbytehq/airbyte/pull/20008#discussion_r1043695431), the labels and tooltips of the fields in the Builder UI are currently hard-coded in the typescript code, and they are not added to our internationalization framework.

This was done to keep the effort of maintaining these fields and adding new ones low, and because the plan is to eventually pull these values in from the manifest JSON schema itself.

This ticket is meant to address that latter point, once the schema has been decoupled from the python backend, and is integrated more tightly into the builder frontend. 

Depends on #23837 - load the descriptions and examples of individual components in the UI for tooltips and labels where-ever possible.

## Acceptance Criteria:
- A helper function exists in the webapp to pull descriptions, titles, and examples from a path in the connector manifest json schema

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
