### ISSUE TITLE
Set up the mysql source, encounter a problem non-json response

### ISSUE THREAD

**Issue by ruanliang-hualun** [airbytehq/airbyte#20290]
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**: Windows 10, I use WSL to run docker-compose 
- **Deployment**: Docker 
- **Source Connector and version**: airbyte/source-mysql:1.0.15
- **Destination Connector and version**:
- **Step where error happened**: Setup new connection

## Current Behavior
Set up a mysql connection, use standard Replication Method

## Expected Behavior
should not report error 

## Logs
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/88dedaab-c7a6-450f-919b-e3cf822386da/0/logs.log
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.40.25
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.a.c.AirbyteApiClient(retryWithJitter):172 - Attempt 0 to save workflow id for cancellation
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.c.i.LineGobbler(voidCall):114 -
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.c.i.LineGobbler(voidCall):114 - ----- START CHECK -----
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.c.i.LineGobbler(voidCall):114 -
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.c.i.LineGobbler(voidCall):114 - Checking if airbyte/source-mysql:1.0.15 exists...
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.c.i.LineGobbler(voidCall):114 - airbyte/source-mysql:1.0.15 was found locally.
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.w.p.DockerProcessFactory(create):120 - Creating docker container = source-mysql-check-88dedaab-c7a6-450f-919b-e3cf822386da-0-kkmrq with resources io.airbyte.config.ResourceRequirements@2526e309[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=]
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.w.p.DockerProcessFactory(create):164 - Preparing command: docker run --rm --init -i -w /data/88dedaab-c7a6-450f-919b-e3cf822386da/0 --log-driver none --name source-mysql-check-88dedaab-c7a6-450f-919b-e3cf822386da-0-kkmrq --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e WORKER_JOB_ATTEMPT=0 -e WORKER_CONNECTOR_IMAGE=airbyte/source-mysql:1.0.15 -e AUTO_DETECT_SCHEMA=false -e AIRBYTE_VERSION=0.40.25 -e WORKER_JOB_ID=88dedaab-c7a6-450f-919b-e3cf822386da airbyte/source-mysql:1.0.15 check --config source_config.json
airbyte-worker                      | 2022-12-09 11:51:58 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):97 - Reading messages from protocol version 0.2.0
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - integration args: {check=null, config=source_config.json}
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedSource
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Command: CHECK
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
airbyte-worker                      | 2022-12-09 11:52:00 WARN i.a.w.i.DefaultAirbyteStreamFactory(internalLog):117 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
airbyte-worker                      | 2022-12-09 11:52:00 WARN i.a.w.i.DefaultAirbyteStreamFactory(internalLog):117 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - Starting connection with method: NO_TUNNEL
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - HikariPool-1 - Starting...
airbyte-worker                      | 2022-12-09 11:52:00 INFO i.a.w.i.DefaultAirbyteStreamFactory(internalLog):120 - HikariPool-1 - Start completed.
airbyte-server                      | 2022-12-09 11:52:01 INFO i.a.s.RequestLogger(filter):112 - REQ 172.19.0.6 GET 200 /api/v1/health
airbyte-webapp                      | 172.19.0.10 - airbyte [09/Dec/2022:11:52:01 +0000] "GET /api/v1/health HTTP/1.0" 200 18 "http://localhost:8000/workspaces/2ca688c3-f799-4ca4-8a86-68a4a503371d/connections/new-connection" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "172.19.0.1"
airbyte-proxy                       | 172.19.0.1 - airbyte [09/Dec/2022:11:52:01 +0000] "GET /api/v1/health HTTP/1.1" 200 18 "http://localhost:8000/workspaces/2ca688c3-f799-4ca4-8a86-68a4a503371d/connections/new-connection" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

**Comment by natalyjazzviolin** [comment]
Hey @ruanliang-hualun - this came up while setting up the connection, right? I've encountered this before, do you have MySQL setup to except outside connections?

**Comment by natalyjazzviolin** [comment]
Could you make a thread about this on Slack/the forum or include replication steps? Let's debug it there, and then if we have concrete replication steps, I'll reopen the issue.
