### ISSUE TITLE
Source Commcare: New Sandbox

### ISSUE THREAD

**Issue by geekwhocodes** [airbytehq/airbyte#20302]
We need a sandbox account for the [commcare](https://www.commcarehq.org/a/sc-baseline) service to review this [PR](https://github.com/airbytehq/airbyte/pull/20220).

**Comment by igrankova** [comment]
Requested access to a free account. Waiting for reply by email. In parallel I'm trying to reach the support to ask a sandbox.

**Comment by igrankova** [comment]
Had a call yesterday, they are ready to provide us a 60-day time-limited trial on our Advanced+ tiers, which gives you full access to APIs and other integration functionality.

**Comment by igrankova** [comment]
Created an account, LastPass name: Commcare Test Account
Waiting for the sandbox plan setup on the Commcare side.

**Comment by igrankova** [comment]
@geekwhocodes 
Commcare accounts team has confirmed that OAuth & CommCareHQ API Access have been granted to the Airbyte domain. 
Do you need anything else from me? I see the PR is finished already.

**Comment by geekwhocodes** [comment]
Hi @igrankova The pull request is already reviewed. Thanks for all your help :)
