### ISSUE TITLE
prevent connectors from filling up all space on build workers

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2033]
## Tell us about the problem you're trying to solve
Right now, during a build we build images for every connector. Each venv for a Python connector is 300-500mb and each image is similar in size. Since we just build them all in sequence, it just fills up the disk space. We're close to hitting the limit, so https://github.com/airbytehq/airbyte/pull/2032 functions as a temporary workaround to delete images that aren't used for the acceptance tests. However, as soon as we add like 5 more connectors we'll be out of space.

## Possible solutions
One naive solution would be to list out which connectors to build, build them sequentially, and then clean up after each run. This will probably have a lot of overhead.

Another solution would be to have some build option that auto cleans up integrations after their builds if that option is set (like `VERIFY_ONLY`).  <-- I think this sounds the best to me right now

Another solution would be to offload these builds to some other workers.

One potential caveat if we start to need to clean up the workspaces themselves (venvs) instead of just images is that we'll start to impact our ability to cache.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368212923622) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
This might be higher priority than I originally thought... 

https://github.com/airbytehq/airbyte/runs/1928413246

**Comment by jrhizor** [comment]
- [ ] revert https://github.com/airbytehq/airbyte/pull/2133 as part of the work for issue

**Comment by davinchia** [comment]
No longer applicable.
