### ISSUE TITLE
Confirmation modal is shown upon connector setup if the connector type was changed

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20332]
## The issue
A confirmation modal is currently being shown after clicking `Set up source` if the source type was changed at any point. Here is how to reproduce:
1. Go to Sources > New Source
2. Choose a source type from the dropdown (e.g. Google Ads)
3. Change the source type to a different one (e.g. Poke API)
4. Type in a Pokemon name (e.g. `ditto`)
5. Click `Set up source`
6. After connection tests pass, a couple seconds later the `Discard changes` confirmation modal will show up

It looks like the source is still being created in this case, so this issue is really just that the confirmation modal is appearing when it shouldn't.

## Expected behavior

Confirmation modal should not appear when saving a connector.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
