### ISSUE TITLE
Exchange rates source description needs update

### ISSUE THREAD

**Issue by Ezziddeen-Abdulwahhab** [airbytehq/airbyte#20340]
## Environment
- **Airbyte version**:  v0.40.25
- **OS Version / Instance**: Centos 7 VM
- **Deployment**: NA
- **Source Connector and version**:  Exchange rates 1.2.7 (Sorry if this version is inaccurate, I'm still new here)
- **Step where error happened**: Setup new connection

## Current Behavior
I wanted to setup a data source using the "Exchange rates API". I followed the steps in the connector's description (right pane in the image) 
![image](https://user-images.githubusercontent.com/109301179/206839586-e086b3d5-7569-4f38-8e38-c7ebc7d38bee.png)
I generated a token from "https://exchangeratesapi.io/" and I tried to continue setting up the data source but I got the following error:
`The connection tests failed.
'Invalid authentication credentials'`

I investigated to see what the problem was and it turns out "https://exchangeratesapi.io/" is no longer in use. It was updated to another data source("https://apilayer.com/marketplace/exchangerates_data-api") in the following PR https://github.com/airbytehq/airbyte/pull/15884 , but the description was not updated. I generated a new token, this time from "https://apilayer.com/marketplace/exchangerates_data-api" and it worked.
The following links also need to be updated due to the data source change from exchange-api to apilayer:
- https://docs.airbyte.com/integrations/sources/exchangeratesapi/
- https://github.com/airbytehq/airbyte/blob/e378d40236b6a34e1c1cb481c8952735ec687d88/docs/quickstart/getting-started.md 

There could be other links/areas that need update that I'm unware of.

## Expected Behavior
The description should be changed to match the new data source which is "apilayer.com".

## Logs
NA

## Steps to Reproduce
1. Go to setup new connection
2. Use "Exchange rates" API as a source
3. Follow the source setup guide on the right pane
4. Use a token generated from "https://exchangeratesapi.io/"

## Are you willing to submit a PR?
I wanted to submit a PR for this and make it my first contribution(I'm new here, I'm trying to get into open-source), but unfortunately, I couldn't get the following guide to work in time
https://docs.airbyte.com/contributing-to-airbyte/developing-locally/
Now something else came up and it'll be some time before I come back to this. Wish you the best.

**Comment by juweins** [comment]
@Ezziddeen-Abdulwahhab Thanks for pointing out this issue! How are you doing so far? Are you planning fixing this issue soon?

**Comment by nataliekwong** [comment]
Thanks for creating this issue! It has now been addressed in https://github.com/airbytehq/airbyte/pull/31566
