### ISSUE TITLE
Facebook Marketing Source generates thousands of these log entries `Got Invalid URL 'None': No scheme supplied.`

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#20345]
While investigating unrelated outages I came across this [connection](https://cloud.airbyte.io/workspaces/7aab2682-7646-4d92-bbe6-501fbb4d0101/connections/315c8213-51b7-4657-b25e-afb1b9260cc3/status) which has thousands of identical log entries:
```
source > Got Invalid URL 'None': No scheme supplied. Perhaps you meant http://None? while requesting thumbnail image.
```

I am not sure if this is pointing to a change in Facebook marketing API that needs an adjustment in our connector or to a bad config on customer's part, but 1000s of these log entries are non-informative and make it harder to read logs.

**Comment by grubberr** [comment]
Closed in this PR https://github.com/airbytehq/airbyte/pull/25003
