### ISSUE TITLE
New Bulk Edit Panel changes

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20372]
List of items related to the bulk edit panel. ([Figma](https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=2732%3A60474&t=fMqpOXfEj3pHRloD-1))

Sync switch needs to be updated to match the design:
![image](https://user-images.githubusercontent.com/168664/207102897-5f80661b-1319-4f86-9740-84e113864263.png)

Should have a border and whit text color for source-defined cursors or primary keys:
![image](https://user-images.githubusercontent.com/168664/207102055-738719ff-b757-49c2-98ba-fe23917562c4.png)

Should say "not available" when the cursor or primary key is not available for the mode:
![image](https://user-images.githubusercontent.com/168664/207102682-173fe0eb-c5b7-4886-89fb-25260dfddddd.png)

Other: 
* When Selecting sync modes that don't need the cursor field or the primary key, it should clear
* When canceling, it should reset all the fields to empty instead of saving the previous ones
* Add unit tests to the component to ensure the functionality works as expected

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
