### ISSUE TITLE
Source Google PageSpeed Insights : New Sandbox

### ISSUE THREAD

**Issue by cptjacky** [airbytehq/airbyte#20398]
We need a PageSpeed Insights API key in order to review [this PR](https://github.com/airbytehq/airbyte/pull/19813).

The API is free to obtain for any Google Cloud Project and does not incur any cost.

Documentation:  https://developers.google.com/speed/docs/insights/v5/get-started?hl=en_US#APIKey

(I don't have access to update the labels yet, cc @sajarin)

**Comment by ycherniaiev** [comment]
If you're just trying out the PageSpeed Insights API, you don't need an API key. If you plan on using the API in an automated way and making multiple queries per second, you'll need an API key. 
Visit LastPass to view key: PageSpeed Insights creds
@cptjacky @natalyjazzviolin @igrankova

**Comment by ycherniaiev** [comment]
Closing as no updates
