### ISSUE TITLE
Connector form: Multiline secret field styles don't match other fields

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20394]
The multiline secret field in the connector form currently has styles which don't match the styles of other inputs in the connector form:
![Screen Shot 2022-12-12 at 2.09.03 PM.png](https://images.zenhubusercontent.com/6269bd44b04db403a70af8df/aca126ea-9fc9-4e4b-8a01-54e6e34c7a6f)

- When hovering over the multiline secret, the background becomes a darker grey instead of just the border
- When there is an error in the multiline secret field, the background becomes a darker grey instead of staying the lighter default color

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
