### ISSUE TITLE
Add user-configurable fields

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#20414]
## Context

In order to allow users to make their connectors built with the Connector Builder reusable, they need to have a place to specify user input fields, which they can then reference in other inputs in the UI.

The designs for this can be found in Figma [here](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=2643%3A109882&scaling=min-zoom&page-id=2634%3A108623&starting-point-node-id=2634%3A108627&show-proto-sidebar=1).

This UI will be used to build out the `spec` block of the connector manifest, which is then consumed by the Test inputs menu to render fields for users to fill out.

## Acceptance Criteria
- User Input view select button exists in the sidebar
- User Input view has a button to add a new input, which opens a modal allowing them to configure the type and other metadata about the field, along with a preview of what the rendered input will look like
- The fields in the User Input view can be reordered to determine the order in the Test Inputs screen
- All other input fields have an embedded button which lets them select a user input field to use, adding the `{{config['<field-name>']}}` interpolated string value to the input upon selection

**Comment by flash1293** [comment]
Currently in progress

**Comment by flash1293** [comment]
Approved and merged into integration branch, waiting for the code freeze

**Comment by flash1293** [comment]
Merged
