### ISSUE TITLE
Create test data sets of varying sizes (10GB/100GB/1TB)

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#20410]
## Tell us about the problem you're trying to solve
As part of improving performance for database sources, we need to quickly be able to spin up different size databases to test how our connectors fare against higher loads.  

We currently have a a test DB loaded defined [here](https://console.cloud.google.com/sql/instances/speed-benchmarks/system-insights?cloudshell=false&project=dataline-integration-testing) with 1TB of data fed in by Faker. Sync : https://cloud.airbyte.io/workspaces/8b2fefd8-6bc6-4a58-9dd2-1764d1dfb8b4/connections/0adb76df-ac25-4070-875b-ff2415600c18/status

We can extend this to create different sized data sets. Relevant slack thread for how Faker data relates to different data sizes : https://airbytehq-team.slack.com/archives/C048E3BK1KM/p1670888249221849

## Describe the solution you’d like
Quickly be able to spin up (or create) sample data for different data volumes (10GB/100GB/1TB).

**Comment by bleonard** [comment]
End goal
3 tables in 1 db or multiple
* 10 GB
* 100 GB
* 1 TB

Way to make the above in as short of time as possible if we need another one.

**Comment by evantahler** [comment]
With https://github.com/airbytehq/airbyte/pull/20741, Faker gets much faster, and could be the path forward to making reasonable datasets in the future

**Comment by akashkulk** [comment]
This work was done and tracked in https://github.com/airbytehq/airbyte/issues/20556
