### ISSUE TITLE
Investigation : Improve LIMIT size calculation to increase DB source syncs

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#20417]
## Tell us about the problem you're trying to solve
Currently, we optimize our batch sizes/limits based on current row size. As this [PR](https://github.com/airbytehq/airbyte/pull/19514) showed, there are some major gains in performance from increasing batch size while executing queries. 

## Describe the solution you’d like
Investigate if it is possible to make additional gains in performance by further modifying this strategy while not OOMing

**Comment by bleonard** [comment]
The previous PR changed the parameters in the current model fairly conservatively.

We are totally opn to changing the model drsatically or incrementally is that's what makes sense.

When testing out other data loading tools (BEAM), we were seeing it query 100x what we are doing on a skinny table on a test that @grishick did.

**Comment by bleonard** [comment]
1. Let's update the logs to say what we are setting as the fetch size.

2. Let's fix the bug we found about the ratio.
