### ISSUE TITLE
Create benchmark for Postgres source connector

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#20427]
Let's do the work needed to run the Faker dataset in a predictable instance. This should use the harness that @davinchia created. We will automate this later in another issue.

**Comment by bleonard** [comment]
More of a CI / CD platofmr.
Running against `master` every N days.
Make it do I can run it against a branch via clicking in github actions (take a branch as n input).

**Comment by bleonard** [comment]
Open questions: How to persist the data? Just in slack might be ok (we are sycning slack to our warehouse), but there could be something better.

**Comment by bleonard** [comment]
Create gradle command the raun the read method with crecentails from an `.env` files that has username/host/password and the expceted size of the database.

Freak out if there is an exception.
log the time it took and the throughput.

**Comment by prateekmukhedkar** [comment]
Performance harness is available on CI.
