### ISSUE TITLE
Profile Postgres Source Connector

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#20424]
We should profile Postgres source connector in a complete isolation (no platform related process running, just the read method being triggered and the records that are being output should be discarded) in both CDC and non-CDC mode with a bunch of different data sets to identify which part of the code is taking how much amount of time. We could use profiling tools like [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) or [visual-vm](https://visualvm.github.io/) and do a cpu profiling.

**Comment by bleonard** [comment]
Output of this issue: list of hotspots and severity with issues created on ones that we should fix.

**Comment by subodh1810** [comment]
Update : Getting rid of the line
```
// Temporarily include legacy state for backwards compatibility with the platform
            .withData(Jsons.jsonNode(StateGeneratorUtils.generateDbState(pairToCursorInfoMap)))
```
from `toState` and `StreamStateManager` class and changes from PR https://github.com/airbytehq/airbyte/pull/21523 combined do improve the performance by ~9-10%. Have been in touch with platform team on how we can get rid of the legacy state. Will raise a PR shortly for it. 

Next regarding the Garbage collectors, I have been playing with different Garbage collectors. I ran the test with 2 new Garbage collectors, the `-XX:+UseZGC` GC and `-XX:+UseShenandoahGC` but both of em didn't make any difference. The default GC is G1GC.

**Comment by subodh1810** [comment]
https://docs.google.com/document/d/1MQGLHvYTUrd3HovSqeR0rQUm8ZHKApoqPACeZG1hCuw/edit
