### ISSUE TITLE
Migrate Invite User email to Customer.io

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#20426]
The invite user email (triggered when a user invites another user to Airbyte) is generic and is not designed to be user-facing. 

We should replace the Sendgrid implementation by calling the customer.io API (https://www.customer.io/docs/api/#operation/sendEmail). Customer.io will then send the email, whose design will be implemented and maintained by the GTM / Growth team.  

The current email is implemented here: https://github.com/airbytehq/airbyte-cloud/blob/master/cloud-server/src/main/java/io/airbyte/cloud/server/email/SendGridImpl.java#L32-L87

cc @timroes

**Comment by nataliekwong** [comment]
I've created two emails in customer.io for the migration.

1) invite User (No existing login): ID: 11
Dynamic parameters: inviter name, workspace name, invite URL

2) invite User (Existing login): ID: 12
Dynamic parameters: inviter name, workspace name

**Comment by nataliekwong** [comment]
Hey @davinchia is this a mini project you could help us with? Or let me know if there's another person to redirect to!

**Comment by timroes** [comment]
A note for implementation here: I think it would be really nice if we can have a more generic "CustomerIO" service available with this in the backend. We know that we want to send out notifications for more events from the backend, and would be nice to already have an easy to use infrastructure in place for that, so we can easily trigger CustomerIO templates with parameters in different places.

**Comment by xiaohansong** [comment]
https://github.com/airbytehq/airbyte-platform-internal/pull/6789 merged
