### ISSUE TITLE
Strip down connector configuration to minimal fields

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#20425]
We should try to aim for writing specs for our connectors that have at less fields as mandatory as possible, to make setting up those connectors as easy as possible. If we can make reasonable assumptions for default values in the connector we should rather have the field optional and make those assumptions.

A couple of examples:

* Do we need a `start_date` field mandatory, or could we just assume we're using 1 year ago by default?
* Does the Google Spreadsheet connector need a link to a spreadsheet mandatory? Couldn't we just create a spreadsheet in the user's drive if they don't provide a link?

We should try to evaluate several of our specs (specifically some we see high setup dropout rates, or failure rates) and try to evaluate which fields we could consider as optional and change the specs accordingly.

**Comment by evantahler** [comment]
@timroes I'm not really sure how to act on this idea.  
In the `start_date` case, are you suggesting that we default to "one year ago" from the time of configuration, or something like that?  Would it be surprising to have an arbitrary start time for your data like this?   

Perhaps the path forward is for @timroes and @YowanR to put together a hypothesis for what defaults like this could look like and test it out with a few users?

**Comment by girarda** [comment]
closing because this is an old issue we're not acting on. we can open specific issues as needed
