### ISSUE TITLE
Improve database sources integration tests

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#20436]
## Tell us about the problem you're trying to solve
Currently, integration tests for source-mysql and source-postgres run quite slowly, which reduces developer productivity.

Need to investigate how to reduce runtime of integration tests. Some ideas
- In the past changing CDC configuration times has helped us speed up integration tests. Understand if there are other configurations (e.g. heartbeat wait time) that can be changed to speed up integration tests. 
- Audit existing integration tests to remove redundant tests which may be adding to wait time.

**Comment by prateekmukhedkar** [comment]
Closing this with the testing speed improvements @sergio-ropero has done.
