### ISSUE TITLE
editing a connector with secrets requires re-entering secret

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2043]
## Expected Behavior
When I edit a non-secret field on a source or destination settings page, I expect the edit to go through when I modify just that field. For example, on Postgres if I want to toggle basic normalization and click "Save changes" I would expect this to work. 

## Current Behavior
If you modify a non-secret field, even though the secret has a`**********` values making it look like it is filled properly, the authentication fails. Looking at the actual request that's being sent, it is actually sending `**********`.

So unintuitively, the behavior is that to edit a non-secret field you have to edit the non-secret field, edit the secret, and then save.

Marking this as medium because I imagine this would be incredibly confusing to many users.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368089413687) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
Retry after @ChristopheDuong's changes go in.

**Comment by timroes** [comment]
This is fixed nowadays. If the FE sends a masked secret (whether or not that is the best implementation would be up for discussions) the backend uses the original backend. I am going to close this for now as it's working and further refactoring can be discussed in new issues.
