### ISSUE TITLE
Git repository URL of the custom transformation project fields requires that a ".git" is in it

### ISSUE THREAD

**Issue by chesterc314** [airbytehq/airbyte#20458]
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**: Ubuntu 18.04 LTS
- **Deployment**: Docker

## Current Behavior
*In Custom Transformations when adding a transformation, cannot save it because my git url is not valid anymore. The error message is "Please enter a valid Git repository URL" problem is I use Azure DevOps and their urls do not have .git in them e.g. https://[ORG]@dev.azure.com/[ORG]/[PROJECT]/_git/[REPO]*

## Expected Behavior
*I would expect it to save my repo url without any error because it worked with a previous version of Airbyte.*

## Steps to Reproduce
1. Navigate to Custom Transformations on a connection
2. Add a transformation
3. Enter in a Azure DevOps url into the field named "Git repository URL of the custom transformation project"
4. The you'll see an error message

## Are you willing to submit a PR?
- I'm willing to contribute to fixing it, I even know where the code is https://github.com/airbytehq/airbyte/blob/373b6f7472dd2dbb34debe2d0289cb962c6febf2/airbyte-webapp/src/views/Connection/TransformationForm/utils.ts#L7 I'm just not sure if there is validation in the backend as well.

Thanks.

**Comment by chesterc314** [comment]
For the time being I have downgraded to v0.40.7 so that I'm unblocked with this validation issue.

**Comment by maks1798** [comment]
@chesterc314 We are having the same issue right now, have you found any solution other then using older version ?

**Comment by marcosmarxm** [comment]
Use a generic valid git repo to pass the frontend step
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5154322/219649601-261aada3-1961-440c-8ae8-06c6d7387eb4.png">

After update the database entry:
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/5154322/219649911-b5c79ad4-4894-4b95-b4a7-2ab721a1ebc1.png">

In my case: 
```sql
airbyte=# update operation set operator_dbt='{"gitRepoUrl": "my_azure_link_repo", "dockerImage": "fishtownanalytics/dbt:1.0.0", "dbtArguments": "run"}' where id='eeb5cf72-0028-48e6-8623-ec31d19158e5';
```

<img width="989" alt="image" src="https://user-images.githubusercontent.com/5154322/219650237-6ed05c3b-070e-4b33-9c21-90d6320997f9.png">


From my sync logs:
```
2023-02-17 12:10:53 INFO i.a.w.p.DockerProcessFactory(create):170 - Preparing command: docker run --rm --init -i -w /data/2/0/transform --log-driver none --name normalization-normalize-2-0-kaatd --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e AIRBYTE_VERSION=0.40.32 airbyte/normalization:0.3.0 configure-dbt --integration-type postgres --config destination_config.json --git-repo my_azure_link_repo
```

**Comment by maks1798** [comment]
How exactly can I connect to db ?
I was able to connect to postgres in airbyte-db, but I got:
```
psql: error: FATAL: role "root" does not exist
```

I also tried role postgres and some other roles, but all didn't work.

Could you pleas eprovide instruction how to connecct to db ?

**Comment by marcosmarxm** [comment]
@maks1798 you don't need to change to root or anything. Just run the command or chck the user you have used to login.

**Comment by VincentCotineau** [comment]
Hello, is there any work in progress regarding this issue ? I am also willing to submit a PR if needed

**Comment by em-jones** [comment]
@dizel852 - in what way has this been `completed`? I'm on v. 0.50.34 and I'm running into this issue.
![image](https://github.com/airbytehq/airbyte/assets/8015161/3d8f1d7a-f186-4d40-8fbf-2a10e6119b94)
![image](https://github.com/airbytehq/airbyte/assets/8015161/5b97ac55-4f40-45dc-ae0a-437a722b99cd)


Please advise.

**Comment by dizel852** [comment]
👋  Hi  @em-jones, sorry for late response. 
Please try to use the latest one - v0.50.35 . 
I'm sure the fix you're looking for is already there 🙂
