### ISSUE TITLE
A double-quote within a database name causes the psql source to throw an exception

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20456]
## Environment
- **Airbyte version**:  0.40.25
- **Source Connector and version**: Postgres 1.0.33
- **Step where error happened**: Setup new connection / Setup source

## Current Behavior
Error in log

## Expected Behavior
It should be able to handle name with escaped double-quote

## Logs
```
Exception occurred while getting the delegate read iterator, closing SSH tunnel
Stack Trace: org.postgresql.util.PSQLException: ERROR: zero-length delimited identifier at or near """"
Position: 209
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675
```

## Steps to Reproduce
1. Create a postgres table with an escaped name in a column
2. Create a source from the table

**Comment by bleonard** [comment]
something to add to test case

**Comment by rodireich** [comment]
The escaping I fixed I made as part of column selection touched table and column names. (#20055)
Maybe need to apply to db name as well.
@edmundito do you know if other characters (e.g plus sign, comma, asterisk etc.) present a problem or is it just double quote?
