### ISSUE TITLE
All cells in streams/fields tables should have ellipses and tooltips for text overflow

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#20450]
Per design pass with Nico.  Any cell with truncated text should have a tooltip (including the dropdown for sync mode, destination namespace, etc.)

I do not believe this needs to be hidden behind the new table feature flag.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by krishnaglick** [comment]
I just went ahead and used our tooltip component. I think it covers most of the use-cases we want. Tried to utilize CSS container queries but they're too raw.

Here's a loom of what it looks like: https://www.loom.com/share/711bed4eb0434808a3f736cb861833ca
