### ISSUE TITLE
Add missing info tooltips to new streams table headers

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#20451]
![Image](https://user-images.githubusercontent.com/168664/210625422-b2e36059-14eb-4960-b6c0-2ead88bdff89.png)

All headers except "Sync" should have info tooltips. We need them on Namespace, Stream name, and Primary Key.

All text is already contained in the localization file but may need to be split for the new table (do not change the existing tooltips).

Here's an example for the destination tooltip in the old table that can be split into the destination namespace and stream name:
![Image](https://user-images.githubusercontent.com/168664/210625884-52e20029-6eb4-4f09-830f-eafd55b6da81.png)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by tealjulia** [comment]
Out of curiosity -- I'm wondering if we also want some in the fields panel?  Users can set a cursor and primary key there sometimes as well...
