### ISSUE TITLE
When switching from source/destination list to source/destination page, the pages look too much alike and it's confusing

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2046]
## Tell us about the problem you're trying to solve
* Users are confused about where they are when switching from source/destination list to source/destination page
* The list is named "Destinations", while clicking on one of the cells will bring you to the connection page, not th4 e destinations

## Describe the solution you’d like
* Putting title of the page in big
* Putting "Connections" instead of destinations as the title of the table
* Status for the connections should be displayed in the page, so you understand those are connections

@cgardens

**Comment by johnlafleur** [comment]
Suggestion of design here: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A295

@cgardens I let you prioritize

**Comment by cgardens** [comment]
updated figma link: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21205%3A3079
