### ISSUE TITLE
Tech Spec for "Improve Check Error Reporting"

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20462]
We are going to add CHECK and DISCOVER failure reasons to the API and UI.

We need a shared [tech spec](https://docs.google.com/document/d/1GycFYbt572BrX8szKSkrAhsp_7KeoPyLlaj0lspcgxY/edit) which describes the API schema which will be returned.  The Connectors Extensibility team will work on the Front End, and Connector Ops will work on the API.

Some interesting topics to consider:
* What does the API look like?
* What are the cases where there might be a failure but no FailureReason (e.g. no AirbyteTraceErrorMessage) object.  How will those be represented.
 * Should the UI present all the data we have, or be "expandable" in some way?
* consider the heiercy of messages which could be shown:
  * status message, then failure.external_message, then failure.internal_message, then failure.stack_trace

**Comment by evantahler** [comment]
Grooming:

* There's a similar API for showing failure reasons in jobs/syncs.  Should we copy this API? FailureReason objects are being returned here too

**Comment by alafanechere** [comment]
@erohmensing provided valuable interrogations around the `check` flow here: https://github.com/airbytehq/airbyte/pull/20721#pullrequestreview-1246677467

**Comment by erohmensing** [comment]
Link to the ratified tech spec [here](https://docs.google.com/document/d/16N5NAs9ahPTUEEebbij9fkny4vnjE4QnjkTuCqJKXbk/edit#)!
