### ISSUE TITLE
Source postgres Number(38,0) is translated to a destination Double

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#20466]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
On a Postgres <> Postgres replication
Reading from source a column of `NUMBER(38, 0)` is translated on destination to a `DOUBLE PRECISION` type. 
This is an extra information in type as the `0` in the number is the scale (=places after decimal point),

## Expected Behavior
The most correct way to create the type is an Integer with the same range.
a Snowflake <> Postgres replication will create a destination BigInt, which is correct.

**Comment by akashkulk** [comment]
Do you happen to know a good way to get precision out of a Column ResultSet? It's not exposed in the `DatabaseMetaData` API : https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

Strangely enough - that capability exists in the `getProcedureColumns` method. https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getProcedureColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

**Comment by bleonard** [comment]
Similar to snowflake #19776

**Comment by bleonard** [comment]
Probably currently just seeing. DECIMAL -> FLoat
but we could check the precision == 0 to know it's an INT.

**Comment by akashkulk** [comment]
First steps : Check what airbyte_type a NUMERIC(38,0) is currently converted to. 

1. Create a Postgres table w/ NUMERIC(38,0) type
2. Trace the process of how this is converted to an airbyte type (which is the type we send over the wire) : https://docs.airbyte.com/understanding-airbyte/supported-data-types
3. Check what type this ends up being discovered us. Check the catalog that is returned by discover()
4. Explore this via unit tests. The class that contains the logic for mapping DB types to airbyte types is `PostgresSourceOperations.getAirbyteType`
