### ISSUE TITLE
WIHP / meta-io-api.readme.io API Source

### ISSUE THREAD

**Issue by cachatj** [airbytehq/airbyte#20461]
## WIHP / meta-io-api.readme.io API Source
* I am trying to connect to WIHP Hotel Meta-Search reporting API as a source - documentation @ [WIHP / meta-io-api.readme.io API Source](https://meta-io-api.readme.io/reference/accounts_list)
* would like to import data from that API into BigQuery

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
Stitch & Segment.com seem to make it rather easy to connect to a generic OpenAuth API - I am not seeing where a generic API connector is a source in airbyte?

## Are you willing to submit a PR?
Yes, am either going to use the Python CDK or would love to get access to Connector Builder UI, is that available in AirBytes Cloud accounts? 

Along those lines, if I am able to successfully develop a custom connector on my own - how can I add that to my Airbyte Cloud account (rather than Airbyte Open Source)??

**Comment by natalyjazzviolin** [comment]
@cachatj custom connectors are not available in Airbyte Cloud, unfortunately. The API you linked is password protected - is it proprietary? Could you please edit your comment to clarify what source this connector will be for with a link to documentation. Closing until that edit is made, thanks!
