### ISSUE TITLE
Add unit tests for normalization.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2048]
## Tell us about the problem you're trying to solve
* The normalization code is essentially untested except for collateral testing by the destination standard tests.

## Describe the solution you’d like
* There's a lot of edge cases in this problem and we need more specific unit testing to ensure that we're fixing them. They require more specific tests than the standard tests can provide. This will help use the whack-a-mole problem, where we fix a bug in one destination only to cause another in a different one.

**Comment by cgardens** [comment]
i think this was closed by the recently merged PR?

**Comment by ChristopheDuong** [comment]
> i think this was closed by the recently merged PR?

I kept this issue open as I was going to add more tests on normalization too

**Comment by cgardens** [comment]
kk, please leave that update in a comment at the end of the week in the future please.
