### ISSUE TITLE
Integrate new table design with Launch Darkly

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#20482]
- Add the flag to launch darkly as a Feature
--> In our webapp, should be an experiment _not_ a feature, as we will roll this out to all users (OSS and Cloud) 
- Should use the useExperiment() hook (not the feature service) in our webapp

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Already tracked in #20196
