### ISSUE TITLE
Source S3: support for empty columns array 

### ISSUE THREAD

**Issue by piyushdatazip** [airbytehq/airbyte#20509]
## Environment
- **Source Connector and version**:  Source-S3:v0.1.27
- **Step where error happened**: Sync job 

## Current Behavior
I am working with S3 connector where I added `"columns":[]` in my config for connector. It syncs nothing from S3. I am syncing `parquet` file from S3
However when removing the field `columns` works well and ingest my data correctly.

## Expected Behavior
I think connector code is only looking up to the values of columns to be nil and considering default conditions and syncing all data. However it should also consider that array could be empty as well.

**Comment by piyushdatazip** [comment]
Mentioning previous contributors here: @artem1205 @koconder @davydov-d

**Comment by koconder** [comment]
@piyushdatazip do you have links to commits/PR that introduced this bug as you linked me to this, I don’t have any recognition of such changes

**Comment by piyushdatazip** [comment]
Thanks for quick reply @koconder. I mentioned previous contributors if they can help fixing this issue, I am ready to raise a PR if few pointers could be given. Though I am no good at Python.

**Comment by sh4sh** [comment]
Hey @piyushdatazip where did you add `"columns":[]` into your config?

**Comment by piyushdatazip** [comment]
```
{"dataset":"shubham","format":{"batch_size":65536,"buffer_size":2,"filetype":"parquet","unexpected_field_behavior":""},"path_pattern":"testing_124/main_2.parquet","provider":{"aws_access_key_id":"XXXX","aws_secret_access_key":"XXX","bucket":"XXX"},"schema":"{}"}
```

This is my config now, but if I add the field columns like this
```
{"dataset":"shubham","format":{"batch_size":125536,"buffer_size":20,"columns":[],"filetype":"parquet","unexpected_field_behavior":""},"path_pattern":"testing_124/output_new2.parquet","provider":{"aws_access_key_id":"XXXXX","aws_secret_access_key":"XXXX","bucket":"XXX"},"schema":"{}"}
```

it syncs nothing but basic case should be if nothing has been passed sync all the columns

**Comment by sh4sh** [comment]
The oncall team has taken a closer look at this request, and noted that the field description does specify to "Leave it empty to sync all columns": https://github.com/airbytehq/airbyte/blob/511d2b00a8d98d0e1ab2b93462a85357d0d0f4f9/airbyte-integrations/connectors/source-s3/integration_tests/spec.json#L130

If configured in the UI, the empty field would be excluded from the config. The [Source S3 docs](https://docs.airbyte.com/integrations/sources/s3/#parquet) confirm the behaviour as well:

>`columns` : If not None, only these columns will be read from the file.

So the field is working as expected, but I see how it could be misleading when working directly with config.json. In this case we want to avoid overengineering with code changes, but maybe there's a way to improve the field description? @piyushdatazip what do you think, would something like "Leave out this field to sync all columns" make the behaviour clearer?

**Comment by piyushdatazip** [comment]
UI does that, I figured that out when I faced this issue, as you said when I was working with config.json directly it took time to understand the expected format of config file, adding a length check would be easier and is good considering this to be edge-case.
