### ISSUE TITLE
Investigate using toasts to show errors instead of failing silently on the connection edit page

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#20538]
Currently on the connection edit page if a response returns an error it silently fails (outside of the connection edit form itself)
We should look into capturing the error, putting it into a toast, and letting the user try again.

https://www.loom.com/share/eb9926c51d31438d937e763bfb0c606c

**Comment by krishnaglick** [comment]
@andyjih Would love your thoughts on this!

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by andyjih** [comment]
@krishnaglick Do you have a screenshot to show the current behavior?

**Comment by krishnaglick** [comment]
The error state I was thinking of was only when the connection failed to load. Looks like modifying the connection does show an error but if you toggle the connection enable or other actions it silently fails. I'll update the ticket to reflect this.

**Comment by tealjulia** [comment]
This has been resolved.  We have a generic toast for failed connection updates.
