### ISSUE TITLE
Regularly test all alpha connectors that are available on Airbyte Cloud

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20551]
Regardless of where we land on https://github.com/airbytehq/airbyte/issues/20442, now that we are moving more and more Alpha connectors to Airbyte Cloud, we should also be testing these connectors with some regularity.  Perhaps we test them weekly rather than daily, but we should test them _often_, and report their status to `#connector-health`.

To decide as part of this project:
* Test frequency
* What we would like GL to do when they see a failure (alpha connectors should be a lower priority than GA or Beta connectors)

**Comment by evantahler** [comment]
cc @sherifnada and @YowanR - do you have any thoughts on this topic?  Can you share some of the history on why don't we test alpha connectors today?

**Comment by sherifnada** [comment]
do we actually skip the test? I think we just said it's not a goal to get their builds working/wouldn't actively fix the build if it's broken (because it was too much overhead for an alpha connector).

**Comment by erohmensing** [comment]
We do this! (weekly)
