### ISSUE TITLE
Normalization Unnesting and table name collision

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2055]
## Tell us about the problem you're trying to solve
Handle table name collision better when creating tables for nested children of a stream.

Today this is randomly adding a number after the table name and this may change from one run to the other if the catalog is changed.

## Describe the solution you’d like
Produce a consistent child name for nested tables (Hash depend on path in the catalog?)

**Comment by ChristopheDuong** [comment]
Especially when dealing with table name collisions, we can also add to this ticket a better docs on generated schema/table/columns using this feature:
https://docs.getdbt.com/reference/resource-configs/persist_docs/

**Comment by cgardens** [comment]
My suggestion would be:
1. `<parent name>_<table name>` (makes it very clearly what parent a table belongs to and a parent's children will all be grouped together with the parent visually)
2. when such a scheme runs into character limits `<table name>_<deterministic hash of parent name>` (potentially we could do `<parent name truncated to fit the other fields>_<table name>_<deterministic hash of parent name>`. dunno if the second part of this suggestions is too cure.

**Comment by ChristopheDuong** [comment]
> when such a scheme runs into character limits <table name>_<deterministic hash of parent name> 

Character limits or collision:
- In the stream `Charges`:
  - Nested field `Charges.invoices`
- Another stream called `charges_invoices`

Then we would have to adapt to add a deterministic hash

**Comment by ChristopheDuong** [comment]
In https://github.com/airbytehq/airbyte/issues/1896 there are examples of name collisions of fields because they are too long and truncates to the same substring, for example:
- `property_hs_line_item_global_term_recurringbillingfrequency_enabled`
- `property_hs_line_item_global_term_recurringbillingfrequency`

**Comment by cgardens** [comment]
To make sure it is clear, in your last example we would truncate
`property_hs_line_item_global_term_recurringbillingfrequency_enabled`
to 
`property_hs_line_item_global_term_recurringbi_enabled_f0ec1`
instead of
`property_hs_line_item_global_term_recurringbillingfrequency`

**Comment by cgardens** [comment]
have we run into the `Charges.invoice` / `charges_invoices` problem that you described in your previous comment already? or this this just a thing that could happen?

**Comment by ChristopheDuong** [comment]
> have we run into the `Charges.invoice` / `charges_invoices` problem that you described in your previous comment already? or this this just a thing that could happen?

Yes, If I remember correctly I did run into it

**Comment by cgardens** [comment]
got it. how do you think we should handle it?
