### ISSUE TITLE
Fix integration test files for Spotless 

### ISSUE THREAD

**Issue by suhomud** [airbytehq/airbyte#20569]
Spotless failed to format next files: 
`airbyte-integrations/connectors/**/integration_tests/expected_records.json`,
With: 
* What went wrong:
```
Execution failed for task ':spotlessStyling'.
> Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting: SyntaxError: Unexpected token (2:1)
    1 | {"stream": "sat_basic_dataset", "data": {"id": 1, "test_column_1": -128, "test_column_10": -128, "test_column_11": -128, "test_column_12": -128.0, "test_column_13": true, "test_column_15": "2021-10-20T00:00:00Z", "test_column_16": "2021-10-20T11:22:33Z", "test_column_17": "2021-10-20T11:22:33Z", "test_column_19": "qwe", "test_column_2": -128, "test_column_21": "15:30:00", "test_column_3": -128, "test_column_4": -128, "test_column_5": -128, "test_column_6": -128, "test_column_7": -128, "test_column_8": -128, "test_column_9": -128 }, "emitted_at": 1669643054045 }
  > 2 | {"stream": "sat_basic_dataset", "data": {"id": 2, "test_column_1": 127, "test_column_10": 127, "test_column_11": 127, "test_column_12": 127.0, "test_column_13": false, "test_column_15": "9999-12-31T00:00:00Z", "test_column_16": "9999-12-31T11:22:33Z", "test_column_17": "2021-10-20T11:22:33Z", "test_column_19": "\u0439\u0446\u0443", "test_column_2": 127, "test_column_21": "15:30:00", "test_column_3": 127, "test_column_4": 127, "test_column_5": 127, "test_column_6": 127, "test_column_7": 127, "test_column_8": 127, "test_column_9": 127 }, "emitted_at": 1669643054045 }
      | ^
```

As a workaround it was excluded from Spotless check (https://github.com/airbytehq/airbyte/blob/master/build.gradle#L131 ): 
```
            '**/integration_tests/expected_records.json',
```
### Expected result 
The `./gradlew --no-daemon format --scan` should not fail for `/integration_tests/expected_records.json` files.

**Comment by edgao** [comment]
those `expected_records.json` should probably actually be renamed to `expected_records.jsonl` - the linter failing on them feels correct.

**Comment by edgao** [comment]
also, removed the sql files from the descriptoin - those were fixed by https://github.com/airbytehq/airbyte/pull/20570/commits/899fa56e2d180cdc4f25e7281693365685bf8d62

**Comment by evantahler** [comment]
@suhomud can you share a little more about what success looks like here?  I agree that expected records probably should be a `.jsonl` file.  Do you want to be able to lint it?  Is excluding the file from linting OK?

**Comment by suhomud** [comment]
@edgao the description is updated with expected result. Theoretically `.jsonl` could fix formatting problem
