### ISSUE TITLE
Source Mailchimp: fails in incremental append sync mode

### ISSUE THREAD

**Issue by sbrickel-nimble** [airbytehq/airbyte#20571]
## Environment
- **Airbyte version**:  0.40.23
- **OS Version / Instance**:     n1-standard-2
- **Deployment**:  Docker
- **Source Connector and version**: Mailchimp 0.2.15 
- **Destination Connector and version**: BigQuery 1.2.8 
- **Step where error happened**:  Sync job

## Current Behavior
Mailchimp connector keeps failing after trying to sync for about 24h in incremental append

## Expected Behavior
Mailchimp connector achieves sync, preferably in less than 24h

## Logs

see [Slack](https://airbytehq.slack.com/files/U03T8LQ107R/F04F6SGC71C/22b8b65b_bd02_45d5_ba52_32865c1fba9e_logs_2132_txt)

## Steps to Reproduce
1. Setup mailchimp
2. Set sync mode to incremental append
3. Wait (might be depended on the volume, we have a lot of data in Mailchimp going many years back. The Mailchimp connector unfortunately does not have a date window that would allow me to easily select only recent data.)

## Are you willing to submit a PR?

Not at the moment

**Comment by marcosmarxm** [comment]
Some info from Slack discussion:
* probably the reason is `email_activity` stream (lot of data);

I wasn't able to reproduce the error using Integration Test account due the size of data.

**Comment by sbrickel-nimble** [comment]
To summarize

The issue is related to the large amount of data in the ```email_activity``` stream. Changing ```page_size``` can help, however in my case I run into the execution-time limit of my destination Bigquery.
A new issue has been opened for that: [#20814](https://github.com/airbytehq/airbyte/issues/20814)

I will close this issue in favor of the new one.
