### ISSUE TITLE
Connector builder: Inputs management UX improvements

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20579]
## Context

Split out of https://github.com/airbytehq/airbyte/issues/20414

Editing user inputs to a connector should be a nice experience. To achieve that, it should be possible to reorder existing inputs to better control the final form. Also, when editing an input, it should preview how the input will eventually look like in the form to better understand what individual settings mean.

## Acceptance criteria

* List of inputs can be reordered via drag and drop
* Pre-order inferred inputs in a sensible order (e.g. username then password, put these at the top by default), can still reorder these inferred inputs if you want
  * This should be a very small change, so we could knock this out very quick in its own PR

**Comment by lmossman** [comment]
Splitting these off since they are less important: 
* In the input modal a preview of the current input in edit is shown (like a connector form with just that input rendered)
* Show type of input next to the title in light grey and italic
