### ISSUE TITLE
Add column selection UI to new stream table

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#20584]
There is a new stream table in the works: https://github.com/airbytehq/airbyte/issues/18187

Currently the column selection UI is only implemented in the "old" stream table. We need to integrate column selection into the new stream table before it can be rolled out.

Figma designs: https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A36212&scaling=min-zoom&page-id=972%3A36208&starting-point-node-id=972%3A36212&show-proto-sidebar=1

**Comment by pmossman** [comment]
Refining notes: not exactly a blocker for the column selection rollout since we're going with the old design initially. Removing from column selection epic and tracking through the stream table redesign epic
