### ISSUE TITLE
Disable deselection of cursor field/primary key

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#20586]
1. The toggle for a primary key should be disabled, with a tooltip reading `The primary key cannot be deselected`
2. The toggle for a cursor field should be disabled, with a tooltip reading `The cursor field cannot be deselected`
3. If a user changes the primary key or cursor field, that field is automatically selected (if it was deselected before) and then disabled

**Comment by pmossman** [comment]
Refining notes:
- Making sure we all agree on the steps above, sounds like we do so we're good to go ahead with this
