### ISSUE TITLE
Use React Lazy to code-split

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#20604]
React gives us code splitting through [React Lazy](https://reactjs.org/docs/code-splitting.html).
We should utilize the output of the performance work (lighthouse reports notably) and attempt some bundle splitting to see where performance can be improved.

Baseline (Prod build, served statically locally):
![Screenshot 2022-12-16 at 2 51 56 PM](https://user-images.githubusercontent.com/4967694/208178171-761f16cd-d1cf-4d13-921a-e91ae83f9423.png)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
