### ISSUE TITLE
Provide in-line feedback in slash commands if input format was invalid

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2061]
## Tell us about the problem you're trying to solve
If I invoke a slash command with invalid input e.g: `/test connectorrr=source-freshdesk` then i get no feedback the I mistyped `connector` and have to dig up the action URL. would be nice if this was faster.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368148175082) by [Unito](https://www.unito.io)

**Comment by oustynova** [comment]
Connectors team is moving away from using slash comments
