### ISSUE TITLE
Support variable input fields in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2063]
## Tell us about the problem you're trying to solve
I would like users to be able to input a variable-length list of objects in the UI. For example, the Google Analytics connector can accept any number of object inputs that conform to the schema `{name: string, dimensions: array<string>, metrics: array<string>}`. We'd like the user to be able to specify as many of these as needed in the UI in a clean way. 

## Describe the solution you’d like
One suggestion is that there can a plus button which when clicked, spawns a form with the specified schema. If the plus button is clicked again, another such form is rendered, etc.. the forms should also be deletable. 

## Describe the alternative you’ve considered or used
The alternative would be to have a user specify the objects as JSON text.

**Comment by sherifnada** [comment]
@cgardens we should discuss this on monday

**Comment by cgardens** [comment]
@sherifnada and I talked about this one. we agreed that it is something we would want to support in the UI. no definites on when.

**Comment by cgardens** [comment]
@sherifnada do you want to work with @johnlafleur to get a mock up of this?

**Comment by eugene-kulak** [comment]
https://github.com/rjsf-team/react-jsonschema-form

**Comment by johnlafleur** [comment]
Here's a suggestion for the design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A295
A lot of features in there. Some may not needed as intermediary steps (dropdown for instance).

**Comment by cgardens** [comment]
Note: We will support Lists of numbers, strings, and objects. We will NOT support Lists of booleans or lists of lists.
