### ISSUE TITLE
document session authenticator

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20646]
### Tell us about the documentation you'd like us to add or update.
SessionAuthenticator is not well documented

**Comment by juweins** [comment]
Hey @girarda ! Can you please provide some more details about the referenced documentation? What is your desired state?

Is this issue about: [Low-Code CDK | Authentication](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/authentication/)? I am not able to find SessionAuthenticator.
