### ISSUE TITLE
Marketo sync is failing 

### ISSUE THREAD

**Issue by CyprienBarbault** [airbytehq/airbyte#20641]
## Environment
- **Airbyte version**:  0.40.11
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: source-marketo 0.1.11
- **Destination Connector and version**: destination-redshift 0.3.50 
- **Step where error happened**:  Sync job

## Current Behavior
Sync of leads, programs and campaigns fails with 
```
Additional Failure Information: '>' not supported between instances of 'str' and 'NoneType'
````
even if some data is written, also the connection state is incomplete:
```
[ 
  {
    "streamDescriptor": {
      "name": "campaigns"
    },
    "streamState": {}
  }
]
```

## Expected Behavior
The connection should complete, all records should be synced and state should be completely set. 

## Logs
[27960fb9_f0c0_414c_bda4_792667d7d031_logs_1274_txt.txt](https://github.com/airbytehq/airbyte/files/10260034/27960fb9_f0c0_414c_bda4_792667d7d031_logs_1274_txt.txt)

## Steps to Reproduce
1. Create a new source-marketo
2. Create a new connection (marketo to redshift)
3. marketo leads data has to have Vietnamese characters (ex: "Nguyễn Trãi", "Nguyễn Văn Quyết",… cf https://en.wikipedia.org/wiki/Vietnamese_name)
5. Sync data

## Are you willing to submit a PR?
Depending on the complexity of the task

**Comment by sh4sh** [comment]
This contribution is awesome!! Thank you so much for your efforts, looking forward to getting the PR merged!
