### ISSUE TITLE
Source Amazon Seller Partner: check connection fails without orders

### ISSUE THREAD

**Issue by animer3009** [airbytehq/airbyte#20669]
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**: Ubuntu 22.04
- **Deployment**: Docker 
- **Source Connector and version**: 0.2.29
- **Step where error happened**: On step check source connection

## Current Behavior
So... I created connection with short start/end date range (using airbyte api).

When I tried to check connection, getting error:
> "2022-12-19 19:55:43 \u001b[1;31mERROR\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):116 - Could not check connection without data for Orders stream. Please change value for replication start date field."
> "2022-12-19 19:55:43 \u001b[1;31mERROR\u001b[m i.a.w.i.DefaultAirbyteStreamFactory(internalLog):116 - Check failed"

### check_connection method
>         try:
>             config = AmazonSellerPartnerConfig.parse_obj(config)  # FIXME: this will be not need after we fix CDK
>             stream_kwargs = self._get_stream_kwargs(config)
>             orders_stream = Orders(**stream_kwargs)
>             next(orders_stream.read_records(sync_mode=SyncMode.full_refresh))
> 
>             return True, None
>         except Exception as e:
>             if isinstance(e, StopIteration):
>                 logger.error(
>                     "Could not check connection without data for Orders stream. Please change value for replication start date field."
>                 )

## Expected Behavior
Not all accounts have orders and not all reports are orders based.
So checking connections by checking existing orders is incorrect.

I can fix this, just not sure how.
I mean I am not sure how I can check the connection instead.
But this anyway MUST be fixed, as myself faced issues cuz it.

**Comment by animer3009** [comment]
@lazebnyi @davydov-d
can you recommend how to fix this?

**Comment by Hvuj** [comment]
Hi.
The fix can be done by altering the code.
Instead of:
 ```
try:
        config = AmazonSellerPartnerConfig.parse_obj(config)  # FIXME: this will be not need after we fix CDK
        stream_kwargs = self._get_stream_kwargs(config)
        orders_stream = Orders(**stream_kwargs)
        next(orders_stream.read_records(sync_mode=SyncMode.full_refresh))

    return True, None
except Exception as e:
    if isinstance(e, StopIteration):
        logger.error(
            "Could not check connection without data for Orders stream. Please change value for replication start date field."
        )
```
            
Create new static method that gets the config file and checks the credentials (api key, etc...) by given account i.e. initiate the api call to see if you can access the api at all
if yes return True else False or the response of the api if you need it

(if this is order based)
some thing like this:
```
        stream_kwargs = self._get_stream_kwargs(config)
        health_check = self.get_auth_client(**stream_kwargs )
        if health_check:
            orders_stream = Orders(**stream_kwargs)
            etc...
        return False ,None
```
(if not order based)
instead of Orders(**stream_kwargs)  create a stream that will handle the correct logic

hope this helps

**Comment by animer3009** [comment]
@Hvuj 
I guess it does not need any extra codes/steps.
This is a connection check and not a data check.
So if we just simply validate the StopIteration case, I guess this will be ok. As in case of incorrect connection variables we get separate errors.
So we can just simple do this:

>             # Validate Orders stream without data
>             if isinstance(e, StopIteration):
>                 return True, None

**Comment by animer3009** [comment]
Done
https://github.com/airbytehq/airbyte/pull/20896
