### ISSUE TITLE
Remove calls to "list_by_workspace" and "list_latest" from Sources and Destination list pages

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#20667]
[getEntityTableData](https://github.com/airbytehq/airbyte/blob/a8c72121f8fd50407425250d3a6ddc3756db8b55/airbyte-webapp/src/components/EntityTable/utils.tsx#L17) currently makes calls to `list_by_workspace` and `list_latest` solely to get the connector icon. The connector icon is available on the source or destination object directly so the calls should be removed and the icon retrieved from the source or destination object.

**Comment by dizel852** [comment]
Need to create separate FE issue

**Comment by krishnaglick** [comment]
This should be the frontend issue? It's a small change iirc.
