### ISSUE TITLE
[connector builder design] Delete a connector definition

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20673]
[Initial proposed flow](https://docs.google.com/document/d/1o_RatpUBdmXLWhVoook96kk8lzhrwNtUKAMF5o3Hv0Y/edit):
1. User goes to Settings > Sources
2. User clicks delete on custom connector
3. If there are configured sources using it, they are listed in the confirmation modal
4. If the user confirms, they are deleted along with the custom builder connector itself

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/209172371-78c86137-8d41-47de-8567-221478ec9feb.png)
