### ISSUE TITLE
[connector builder design] Exporting a custom low-code connector as new a new Source definition

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20674]
[Initial flow proposal](https://docs.google.com/document/d/1o_RatpUBdmXLWhVoook96kk8lzhrwNtUKAMF5o3Hv0Y/edit):
1. User goes to Settings > Sources
2. Clicks “New builder connector”
3. Empty connector builder UI loads (or a wizard to guide them through the process)
4. User configures connector and tests
5. Clicks save draft (connector will now show up in the list of “Custom builder connectors”, but without a released version)
6. Maybe the first click to save will also auto-release a first version to make it easier to use?
7. Toast is shown “Your connector is now available on the Settings > Sources” page
8. User can now go away and come back later to continue editing the draft (Settings > Sources, “Edit” on the listed builder connector)
9. One the connector is ready to be used, the user clicks “Release new version”
10. Picks a version number (we suggest a suitable one)
11. This version of the manifest is now saved and can’t be edited anymore. It also shows up as “latest” in the list of custom builder connectors
12. The connector can be used as any other connector when configuring a source and a connection

**Comment by Upmitt** [comment]
https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3404%3A119487&node-id=3426%3A122505&viewport=905%2C475%2C0.5&scaling=min-zoom&starting-point-node-id=3426%3A122505&show-proto-sidebar=1
