### ISSUE TITLE
[connector builder design] Updating an existing low-code connector definition

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20672]
1. User goes to Settings > Sources
2. Clicks edit on existing connector
3. The latest version is loaded in the connector builder UI (if there is already a draft, the draft version is loaded)
4. User makes changes, saves the draft from time to time
5. Once the change is ready, user clicks “Release new version”
6. Picks a version number larger than the latest (we suggest a suitable one)
7. User can click checkbox to use the new version in the workspace right away (if they don’t they can upgrade later on the Settings > Sources page like any other connector)
8. Maybe check for incompatible changes to the spec? Not sure
9. New version of the connector is used for all connections

https://docs.google.com/document/d/1o_RatpUBdmXLWhVoook96kk8lzhrwNtUKAMF5o3Hv0Y/edit

**Comment by Upmitt** [comment]
https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3404%3A119487&node-id=3426%3A122505&viewport=905%2C475%2C0.5&scaling=min-zoom&starting-point-node-id=3426%3A122505&show-proto-sidebar=1

**Comment by girarda** [comment]
Notes from today's sync:
When saving a connector, connector developers should have the option to either
 - Create a new source definition
 - Overwrite an existing source definition (for a custom low-code connector). The connector developer should be able to choose which source definition to overwrite

This mechanism can be used to control release
1. Create a new connector "pokeapi dev"
2. Test and update the "pokeapi dev"
3. Load "pokeapi dev" in the connector builder
4. Publish as "pokeapi prod" to update the existing production connection

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/214308359-006b253e-cc5f-470c-b1a6-0419fb61af38.png)
![Image](https://user-images.githubusercontent.com/29780098/214308360-e5c60cd8-b048-4101-86bd-6914c51563c2.png)

prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3697%3A128255&node-id=3712%3A128033&viewport=583%2C647%2C0.17&scaling=min-zoom&starting-point-node-id=3712%3A130280

**Comment by Upmitt** [comment]
question : If a user is editing "connector_dev" then click on "override existing connector" and override "connector_prod" > Does it also release a new version for "connector_dev" ? (or just save the draft for "connector_dev")

**Comment by Upmitt** [comment]
We decided to remove the override option on 01/24
