### ISSUE TITLE
[connector builder design] Schema auto detection

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20686]
* what is the UI experience if the user runs their first test, before they ever specified the stream schema?
* What is the experience if they run a request whose schema does not exactly match the currently defined schema? 
* How can connector developer amend the detected schema?

[Link to prototype](https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3589%3A124527&t=781Ic54RMnrYfkJm-0)

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/208696196-5add9d12-dc9e-429a-82bb-88a35e115e52.png)

**Comment by Upmitt** [comment]
Schema detection research: https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3589%3A124527

**Comment by girarda** [comment]
comments from today's sync:
- it would be useful to add a warning in the defined schema text box when there is a diff with the inferred one

**Comment by Upmitt** [comment]
Is it a warning we should also display in the left menu, next to the stream name?

**Comment by girarda** [comment]
Update from today's sync:
- We should only add a warning to the left-side and middle panels if the user's schema is incompatible with the detected schema
- The right-side testing panel can always have a warning if the user schema does not match the detected schema

**Comment by Upmitt** [comment]
Figma updated: https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3589%3A124527

**Comment by lmossman** [comment]
Update from today's sync:
- Make the schema difference warning "info" color instead of "warning" color, since it might be wanted by the user
- Only show an icon for schema differences on the left-sidebar once we have the ability to determine if the declared and detected schemas are actually incompatible. Don't show the icon if the declared schema is just broader than the detected.

**Comment by girarda** [comment]
closing in favor of https://github.com/airbytehq/airbyte/issues/25321
