### ISSUE TITLE
Importing a connector manifest from local system

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20680]
Current solution is to copy/paste the content of a YAML file in the connector builder's editor. Is this the long-term design?

**Comment by Upmitt** [comment]
Ability to load a YAML file -  https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3404%3A119487&node-id=3426%3A122505&viewport=905%2C475%2C0.5&scaling=min-zoom&starting-point-node-id=3426%3A122505&show-proto-sidebar=1
