### ISSUE TITLE
Connector builder: Render results as table instead of json blobs

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20684]
Experiment with rendering records as table rows instead of json blobs. Then make a decision on which one is more appropriate (or if both should be supported)

**Comment by girarda** [comment]
[Link to initial prototype](https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3538%3A124449&t=781Ic54RMnrYfkJm-0)

Moving to ice box so we can focus on higher priority issues

**Comment by Upmitt** [comment]
https://www.loom.com/share/d915e73179ea41928fd45fce97d54bfc

**Comment by flash1293** [comment]
Decisions made in meeting:
* Render the table single-row with ellipsis text truncation
* On hover show the expand button
* When clicked it opens a modal with a nicely formatted object
* Do this as part of the builder testing panel (not in UI components)
