### ISSUE TITLE
[connector builder design] Remove Connector name & Connector Icon from the onboarding

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20681]
The connector name and icon are only needed when exporting the connector. 

We should defer them to a later step so connector developers can see data in the test panel ASAP.

The specific solution might depend on the design we come up with for https://github.com/airbytehq/airbyte/issues/20674

**Comment by Upmitt** [comment]
I removed connector name & Icon from the onboarding on this prototype : https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3404%3A119487&node-id=3426%3A123290&viewport=386%2C356%2C0.05&scaling=min-zoom&starting-point-node-id=3426%3A123290&show-proto-sidebar=1 - User can now set name and icon after the onboarding, or in the modal when they click "release new version"

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/211514923-387c6595-0740-4ed2-a4d5-021fd9f2b9c5.png)
