### ISSUE TITLE
Update airbyte protocol migration

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#20695]
## What

We have two types of objects at the top level of the Airbyte protocol: `AirbyteMessage` and `ConfiguredAirbyteCatalog`.
In order to support migrations for all objects, we should add the migration layer for `ConfiguredAirbyteCatalog`

Some migrations of AirbyteMessage need the Configured catalog for a better upgrade/downgrade. `AirbyteMessageMigration::{downgrade,upgrade}` should take an extra `ConfiguredAirbyteCatalog`

## How

* Add `ConfiguredAirbyteCatalogMigration` similar to `AirbyteMessageMigration`.
* `AirbyteMessageMigration::{downgrade,upgrade}` should take an extra `ConfiguredAirbyteCatalog`

**Comment by davinchia** [comment]
@gosusnp what is the status of this? should this go back into the Icebox?
