### ISSUE TITLE
🎉 Source Airtable: Implement OAuth2.0 authentication

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#20708]
Based on the official docs: https://airtable.com/developers/web/api/oauth-reference
the Oauth flow is also supported and could be implemented to access Airtable resources.

**Comment by bazarnov** [comment]
Moving this one to `On  Hold`, because Oauth is not critical to have for Cloud Release.

**Comment by bazarnov** [comment]
@YowanR 
For Airtable, the OAuth is not strictly required, but still, an option to have, the implementation is here, it's using `SingleUseRefreshToken`, and it's tested and working. 
Should we merge that in for Airbyte Cloud to provide the customers with OAuth in addition to the `Personal Access Token` auth option? (it's easier for the user to correctly obtain the key and minimize the effort to do so manually)
PR: https://github.com/airbytehq/airbyte/pull/20934

**Comment by YowanR** [comment]
If we've already done the work for OAuth for Airtable, then definitely let's go ahead and merge it and offer both options to our users.

**Comment by bazarnov** [comment]
The PR is here: https://github.com/airbytehq/airbyte/pull/20934
