### ISSUE TITLE
Follow-up advanced normalization cases with combining JSON schema nodes

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2070]
## Tell us about the problem you're trying to solve
Following up on #2044 we still don't fully handle all JSON Schemas nodes, especially when using combining nodes (AnyOf, AllOf, OneOf...)

## Describe the solution you’d like
Handle catalogs with combining json schema nodes

## Describe the alternative you’ve considered or used
those special cases are output as a string column

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368089744610) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Closing as stale.
