### ISSUE TITLE
Source Gong: answeredScorecards does not work

### ISSUE THREAD

**Issue by wallies** [airbytehq/airbyte#20702]
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: GKE
- **Deployment**: Kubernetes
- **Source Connector and version**: Gong - 0.1.0
- **Step where error happened**: Sync

## Current Behavior
*Tell us what happens.*
Synced with answeredScorecards stream with startDate: 2018-02-18T08:00:00Z. I get the following error. 

[default_logs_3682.txt](https://github.com/airbytehq/airbyte/files/10266374/default_logs_3682.txt)
This looks to be as the response is a 404

I tried changing the startDate to further back, but then I get responses with an error
```
raise TypeError(f'Object of type {o.__class__.__name__} 'TypeError: Object of type bytes is not JSON serializable"
```

## Expected Behavior
*Tell us what should happen.*

## Are you willing to submit a PR?
Not sure

**Comment by marcosmarxm** [comment]
@girarda maybe would be better improve the Response error for low-code CDK. It isn't clear what caused the issue here.

**Comment by marcosmarxm** [comment]
@wallies I added the issue to connector backlog. Could you run the `read` command locally with `--debug` flag?

**Comment by wallies** [comment]
@marcosmarxm Strange thing is the read seems to work fine. It still doesnt like the 404, from answeredScorecards

```
File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 326, in parse_response\n    raise ReadException(error_message)\nairbyte_cdk.sources.declarative.exceptions.ReadException: Request to https://api.gong.io/v2/stats/activity/scorecards?limit=100 failed with status code 404 and error message No answered scorecards found corresponding to the provided filters.\n", "failure_type": "system_error"}}}
````

So i guess two questions, whats the best way to deal with 404 from an endpoint?
Second why would the read and the low code connector builder be returning different outputs?

**Comment by marcosmarxm** [comment]
Looks you don't have data in this endpoint correct?
```
 No answered scorecards found corresponding to the provided filters.
```
Workaround for now: disable this stream from your connection


The solution is to add https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/error-handling to the Gong requester.

**Comment by wallies** [comment]
> Looks you don't have data in this endpoint correct?
> 
> ```
>  No answered scorecards found corresponding to the provided filters.
> ```
> 
> Workaround for now: disable this stream from your connection
> 
> The solution is to add https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/error-handling to the Gong requester.

Excellent. Will put a PR up in the new year with this fix and the calltranscripts stream

**Comment by btkcodedev** [comment]
@marcosmarxm Raised PR #32559 for this issue

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
