### ISSUE TITLE
Wrong hover color on "Sync now" button

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#20728]
## Current Behavior
Wrong hover color on the "Sync now" button

<img width="843" alt="Screenshot at Dec 20 19-12-53" src="https://user-images.githubusercontent.com/20929344/208726269-b3edf433-6bfd-46f2-bfd9-7478bed301cf.png">

![CPT2212201912-340x91](https://user-images.githubusercontent.com/20929344/208726292-412f5258-e46c-47a1-b7fd-3f5b5388df2c.gif)

## Expected Behavior
The button should have`red` hover color

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
