### ISSUE TITLE
Clean up matchers in webapp e2e testing

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#20722]
current problems with our e2e tests:

- matchers are matching to any element containing certain text, not necessarily whatever we're looking for (maybe should always be test-id)
- ~~function names are describing their expected outcome rather than what they are doing
resolve these~~ (moved to separate [issue](https://github.com/airbytehq/airbyte/issues/21245))

to avoid scope creep, if other issues are found, please file a new issue for them

**Comment by tealjulia** [comment]
current problems with our e2e tests:
- matchers are matching to any element containing certain text, not necessarily whatever we're looking for (maybe should always be test-id)
- function names are describing their expected outcome rather than what they are doing 

resolve these
to avoid scope creep, if other issues are found, please file a new issue for them

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by dizel852** [comment]
After syncing with the team agreed to split the issue on multiple ones
