### ISSUE TITLE
No feedback after launching the sync manually from `Connections` tab

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#20729]
## Current Behavior
There is no feedback after launching sync manually.
https://www.loom.com/share/09a4ce52fdd94f40bf5562807378c8f6

## Expected Behavior
The button should change the state to "In progress"

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
Looking at the code, the button calls to sync the connection, and nothing is done about it. It does return the jobs list, but it doesn't update the current connection object nor it invalidates the connections list. The goal should be to do something to get an updated status.
