### ISSUE TITLE
Source MailChimp: set up a Sandbox Account

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#20726]
In order to enable expected_records test for the Source Mailchimp we need to set up a sandbox account, since the current one seems to be disclosing Airbyte's internal data. See https://github.com/airbytehq/airbyte/pull/20720#discussion_r1053479814

**Comment by davydov-d** [comment]
cc @igrankova @ycherniaiev

**Comment by alex-gron** [comment]
@davydov-d  which team should this be assigned to? I don't believe analytics can help here. 

cc @evantahler  since I saw you commented on the original PR

**Comment by davydov-d** [comment]
@alex-gron I'm sorry I must have mixed up the team names. Yurii and Iryna from the comment above are the ones to be assigned

**Comment by alex-gron** [comment]
No problem! Thanks for confirming!

**Comment by ycherniaiev** [comment]
Sandbox with not sensitive info created (LastPass: MailChimp second Test Acocount). Data is populated

**Comment by ycherniaiev** [comment]
Primary account with data - Primary Mailchimp Sandbox
