### ISSUE TITLE
Update source defined cursor and primary key to match selected color

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20731]
Figma:
https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A36208&t=gUgiRjka8M752UGy-1

Add color to the source-defined primary key or cursor that is not editable. These match the text colors of the pill button text:

![image](https://user-images.githubusercontent.com/168664/204811374-1d6681d8-ec0a-4028-96e7-2544648c895f.png)

These colors appear when the stream row is:

* Standard
* Selected
* Adding
* Removing

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
