### ISSUE TITLE
New destination: Databricks Delta Lake 

### ISSUE THREAD

**Issue by bclipp** [airbytehq/airbyte#2075]
## Tell us about the new integration you’d like to have
I would like to see Delta Lake support through Apache or Databricks Spark

## Describe the context around this new integration
Outputting CDC , Kafka topics ect.. to a data lake. 

## Describe the alternative you are considering or using
At the moment Fivetran supports this feature so I will use both products as needed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368148044757) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@bclipp Thanks for creating the issue. Some questions: 

* what sources would you use with DL? 
* what data scale do you anticipate replicating? ballpark/order of magnitude is fine

**Comment by bclipp** [comment]
@sherifnada 
* I have used it with CDC, but I could see pulling data from API sources, and salesforce for sure. 
* Size I would not honestly expect to see "big data", with CDC the initial full load might be large depending on the source table size. 
* The goal I have is to have the data located in a Delta Lake table. https://delta.io/

**Comment by mcfuhrt** [comment]
> @bclipp Thanks for creating the issue. Some questions:
> 
> * what sources would you use with DL?
> * what data scale do you anticipate replicating? ballpark/order of magnitude is fine

Why limit the connector to sources? We currently use Fivetran and can target any source (Google Ads, Facebook, ... ) in combination with Azure Data Lake / Delta Tables (through Databricks). Such an option would be desirable for Airbyte as well :)

**Comment by sherifnada** [comment]
@mcfuhrt I believe the request was for Delta Lake as a destination, so i was trying to understand the context by asking which sources they would like to use with this destination :)

**Comment by oynek** [comment]
We use Delta Lake a lot and frequently in our corporate context, so this integration would be a huge step towards replacing the current software with AirByte.

**Comment by sherifnada** [comment]
some questions for Airbyte to answer (feedback from anyone else on the issue is also welcome!): 
1. deliverable date
2. creating a sandbox account/credentials for testing
3. features that should be included in the MVP. We potentially should write a small tech spec to declare the scope of this connector. Sections should be: inputs, outputs, expected file formats, expected scale that should be handled, rough outline of implementation plan.

**Comment by michel-tricot** [comment]
Working on it with Databrick's team!

**Comment by michel-tricot** [comment]
They are finalizing the agreement!

**Comment by michel-tricot** [comment]
We got access to the documentation & a sandbox account! Project is ready to roll

**Comment by bclipp** [comment]
The original use case was as a destination, but for a source, I could see that being useful also.

**Comment by sherifnada** [comment]
We've received access to a sandbox account over the weekend. Will begin spec'ing out this week.

**Comment by davinchia** [comment]
The deadline for this has been shifted to June. This is being moved out of this week's sprint.

**Comment by MGRashed** [comment]
Any update on this? Will this support Delta Lake in Azure Data Lake Gen 2?

**Comment by sherifnada** [comment]
@MGRashed currently no firm ETA. As things stand, we are implementing destinations for S3/Azure/GCS in July and from there it will be a very light addition to support DL, so I'm guessing delivery can be expected in August though it's not confirmed. Will update here as things take more shape.
