### ISSUE TITLE
Source Posthog: API batch size increase to improve Sync Speed

### ISSUE THREAD

**Issue by guillaume-chech** [airbytehq/airbyte#20751]
## Tell us about the problem you're trying to solve
I'm currently not able to use the Posthog connector to sync my Poshtog data in Snowflake. The reason for that is that no matter how big I scale my instance, sync speed remain unchanged and sync cannot keep up with how much data is produced eventually falling behind.

## Describe the solution you’d like
Currently the source [uses a 100 events per requests batch size](https://github.com/airbytehq/airbyte/blob/16e890aee1c9456f7dd22c61abd12214c02d131e/airbyte-integrations/connectors/source-posthog/source_posthog/components.py#L25) which is really small given the big volumes such source can produce (Over 10M events per day on our side). Increasing this limit to 10k or letting the user set it up at the source set up level would be nice.

## Describe the alternative you’ve considered or used
No alternative found

## Additional context
I've made some test on Postman modulating the limit parameter used to define batch size and drastically improved the query speed by reducing the number of API calls.

## Are you willing to submit a PR?
Yes I could simply change the limit from 100 to 10000. However I have trouble setting up my dev env to run airbyte locally, I've got discourse post opened to solve that other issue.

**Comment by haithem-souala** [comment]
I would like to work on this one

**Comment by justinbchau** [comment]
Just assigned it to you @haithem-souala ! Thanks for taking it.

**Comment by haithem-souala** [comment]
Hey @justinbchau, The PR (#24084)  is ready for review.

**Comment by jrolom** [comment]
@sajarin  I think we can close this issue as PR is closed #25603
