### ISSUE TITLE
Source TikTok Marketing: add advertiser ID to connect to when using the OAuth 2.0 Authorization method

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#20757]
## Tell us about the problem you're trying to solve
Add this so that the data coming through the streams is specific to only one account. This is important because users may have TikTok email accounts that have access to multiple advertiser accounts, we want to be able to be specific to only the account for which they want their data displayed.

## Describe the solution you’d like
add advertiser ID to connect to when using the OAuth 2.0 Authorization method

## Additional context
This is an OSS support request from cart.com

**Comment by davydov-d** [comment]
Solved in https://github.com/airbytehq/airbyte/issues/23378. Closing as duplicate
