### ISSUE TITLE
Remove stream name from onboarding view

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20806]
- infer the name from the path
- allow the developer to modify the stream name from the stream view

**Comment by Upmitt** [comment]
user interviews prototype updated : https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=2634%3A108623&node-id=2634%3A108627&viewport=146%2C476%2C0.08&scaling=min-zoom&starting-point-node-id=2634%3A108627&show-proto-sidebar=1
