### ISSUE TITLE
Only support latest draft instead of one draft per version

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20804]
- Only use the latest draft instead of one draft per version
- Remove save draft button since the draft can be saved automatically on local storage

**Comment by Upmitt** [comment]
Figma updated - https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3404%3A119487&node-id=3454%3A123180&viewport=386%2C356%2C0.05&scaling=min-zoom&starting-point-node-id=3426%3A123290&show-proto-sidebar=1

**Comment by girarda** [comment]
comments from today's sync:
- Draft should always point to the next version being developed
- Can mention which version it is based on
