### ISSUE TITLE
Source getLago - new streams - customer current usage and wallets

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#20822]
## Tell us about the new connector you’d like to have
Add customer current usage and wallets streams.

## Describe the context around this new connector
N/A

## Describe the alternative you are considering or using
There is no workaround. 

## Are you willing to submit a PR?

Yes!

**Comment by haithem-souala** [comment]
@YowanR, I’d like to start working on this issue.

**Comment by YowanR** [comment]
@haithem-souala Happy to assign this one to you but please note that this is not part of the Contributor Program. If you want to tackle items from the program, please take a look at our [board](https://github.com/orgs/airbytehq/projects/13/views/38). Let me know if you want to continue with this PR -- we always welcome community contributions!

**Comment by avirajsingh7** [comment]
I will take this one
