### ISSUE TITLE
Exclude unsupported value types from V1 test cases

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#20824]
- NaN
- Infinity
- (- Infinity)
- Era dates (BC/AD)

**Comment by suhomud** [comment]
@grishick , I checked current implementation. 
`NaN, Infinity, -Infinity` are not the issue since it's has a special flag in test and checks: 
```
    if (getProtocolVersion().equals(ProtocolVersion.V0) || !numericTypesSupport.isSupportNumberInfinity()) {
      return;
    }
```
It is false by default.  So only Era dates should be excluded for now
