### ISSUE TITLE
Database Backups

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2082]
## Tell us about the problem you're trying to solve
As a Database Manager, I want to be able to store back ups of my database (that I can use to restore the db in case of problems).

## Describe the solution you’d like
It is easy to take the destination output of Airbyte and use it to restore my data source database.

## Additional context
While this is already well supported for cloud managed db solutions (RDS, cloudSQL, etc), there are fewer "dead simple" options for self-hosted databases.

[slack convo](https://airbytehq.slack.com/archives/C01AHCDHCKE/p1613495243119400)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368148499781) by [Unito](https://www.unito.io)

**Comment by evantahler** [comment]
While not backing up the /whole/ database, the Octavia CLI does back up your connections at least so you can recover rather quickly and get syncing again.
