### ISSUE TITLE
Enable substream slicers and Cartesian product slicers in connector builder

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#20835]
Both substream slicers and cartesian product slicers should be supported in the UI.

## Acceptance criteria

* Substream slicer should be selectable from the list of slicing options
* Parent stream should select reference to another stream in the UI
* Circular dependencies should be caught
* Cartesian product slicers should be selectable from the list of slicing options
* Any slicers should be able to be added to the list of sub-slicers for cartesian product slicers

**Comment by sherifnada** [comment]
@flash1293 to fill in the details of this ticket

**Comment by flash1293** [comment]
Implementation notes:
* add stable id to each stream in the builder values
* Use it to reference the parent stream
* before mapping to the manifest, check for cycles in the references - if there are some, set an additional error state and hide the stream test panel like if the listing call fails
* On building manifest, recursively inline stream definitions into each other

**Comment by flash1293** [comment]
In review, however it's unclear how to handle some weird part about how substream slicers properties are managed on the CDK level.
