### ISSUE TITLE
Runbook: How to troubleshoot oAuth when on call

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20840]
As an On Call engineer, I need to know how to troubleshoot problems with oAuth.  This could be in the connector or platform codebase

**Comment by pedroslopez** [comment]
We should include info about:
- How to view oauth errors in Datadog
- Common errors
    - "Oauth is not available" -> oauth parameters have not been configured for the connector
- Enabling OAuth buttons locally (turn on the `AllowOAuthConnector` feature flag)
- Link to documentation on the OAuth spec (how connectors define oauth inputs and outputs)

**Comment by evantahler** [comment]
There is probably some great content to borrow in https://docs.google.com/document/d/19XQFHV23cdAP7UhSCCLGKFUjGU3lgKBwmNL59zAC7Dw/edit#
