### ISSUE TITLE
Connector builder: Add event tracking

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20863]
To be able to tell how users are working with the connector builder UI, there should be events for common interactions:
* Trigger stream test
* Test success / failure
* Add stream
* Remove stream
* Copy stream
* Copy component
* Enable/disable component
* Switch to YAML/UI
* Export manifest

Events can be tracked using the analytics service (`useAnalyticsService`)

**Comment by lmossman** [comment]
Some more ideas:
- Reset all
- Switch to different views (Global configuration, User inputs, streams)
- Open Schema tab on a stream
- Open connector logs in testing panel
- Switch to Request / Response tabs in testing panel
- Open Inputs menu in testing panel
- Add a new user input
- Insert a user input value using the embedded button

**Comment by flash1293** [comment]
Once auto schema detection is ready:
* click import  schema
* Click overwrite schema
* Click merge properties

**Comment by lmossman** [comment]
List of events to track and naming are currently being finalized by the growth team. See slack thread for context: https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1673412295608609?thread_ts=1672943304.389659&cid=C02TL38U5L7
Once finalized, I will work on implementation of tracking these events in the builder
