### ISSUE TITLE
Enable to choose non-AWS regions in S3 Connector

### ISSUE THREAD

**Issue by dtonda** [airbytehq/airbyte#20860]
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**:  Ubuntu 22.10
- **Deployment**: Kubernetes deploy env via helm
- **Destination Connector and version**: S3
- **Step where error happened**: Destination Creation

## Current Behavior
When creating a destination to a S3 bucket that is not on AWS, it allows to provide a custom endpoint, but it forces you to select a region from AWS.
In my specific example Im trying to create a connection a OVHcloud S3 bucket (https://www.ovhcloud.com/en/public-cloud/object-storage/) with endpoint https://s3.gra.io.cloud.ovh.net/ where the region is "gra" (Graveline).

Error message is :

## Expected Behavior
Interface should allow to either choose a non-AWS region, or not propose a fixed list (which may become quickly obsolete each time AWS adds a region) or bypass the selected region if custom endpoint is entered (and contains the region).

## Logs
_

> the connection tests failed.
> Could not connect to the S3 bucket with the provided configuration. The authorization header is malformed; the region '' is wrong; expecting 'gra' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: txbf1ce5f2a868480aac030-0063a5ac34; S3 Extended Request ID: null; Proxy: null)

_

## Steps to Reproduce
1. Start creating a connection to a  S3 destination
2. See that you can only choose a Region from a limited list of AWS region.
3. See that even if you enter a non-aws end point, the connection fails due to wrong region (see error message).

## Are you willing to submit a PR?
No, simply because I do not have the competence to code the solution.

**Comment by marcosmarxm** [comment]
Thanks for requesting this @dtonda, are you able to build the dev version using #19427?

**Comment by dtonda** [comment]
> 

I tested the latest Airbyte version today with S3- **destination**-s3:0.3.20 : there is now a "Endpoint" Optional for non-AWS connections but when I tested, it still sends an error message linked to the region.

Important to note that the **SOURCE** connector seems to work with the same configuration (no error message / All connection tests passed!)

Error message :
"Could not connect to the S3 bucket with the provided configuration. The authorization header is malformed; the region '' is wrong; expecting 'gra' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: txb072acbc823846d7a1285-006405ea1e; S3 Extended Request ID: null; Proxy: null)"

Endpoint used is : https://s3.gra.io.cloud.ovh.net/

**Comment by longwei66** [comment]
I there some news on this topic? 
I am exactly in the same situation as @dtonda, try again today.

Having the possibility to input an arbitrary region instead of the fixed aws list would fix the issue.

**Comment by LinU777** [comment]
This issue is about **destination** S3 regions, but closed by PR for source S3

**Comment by gillesgw** [comment]
Would it be acceptable to just transform the enum that lists the (AWS-specific) regions into a simple enum-less string field? This simple change would unlock the possibility of using this connector with any S3-compatible api.
