### ISSUE TITLE
Helm Upgrade v0.43.6 Fails

### ISSUE THREAD

**Issue by Tybot204** [airbytehq/airbyte#20870]
## Environment
- **Airbyte version**:  0.40.25
- **OS Version / Instance**: AWS EC2 Linux
- **Deployment**: AWS EKS via Helm
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
I am upgrading from Helm chart v0.43.3 to v0.43.6. The upgrade process completes and prints the "Happy Helming!" message as with previous successful deploys. However, the airbyte-temporal pods get stuck in a crash loop (error logs below).

My current helm deployment is using all default settings for `values.yml`. I did not pass my own when creating this instance, and attempting to upgrade using `--reset-values` also produces the same error in airbyte-temporal pods. I have also tried first upgrading to helm chart v0.43.5 and see the same issue.

## Expected Behavior
I expect helm upgrade to perform any needed migrations and updates to configuration so that Airbyte continues to function after upgrade.

## Logs

```
+ DB=postgresql
+ SKIP_SCHEMA_SETUP=false
+ KEYSPACE=temporal
+ VISIBILITY_KEYSPACE=temporal_visibility
+ CASSANDRA_SEEDS=
+ CASSANDRA_PORT=9042
+ CASSANDRA_USER=
+ CASSANDRA_PASSWORD=
+ CASSANDRA_TLS_ENABLED=
+ CASSANDRA_CERT=
+ CASSANDRA_CERT_KEY=
+ CASSANDRA_CA=
+ CASSANDRA_REPLICATION_FACTOR=1
+ DBNAME=temporal
+ VISIBILITY_DBNAME=temporal_visibility
+ DB_PORT=5432
+ MYSQL_SEEDS=
+ MYSQL_USER=
+ MYSQL_PWD=
+ MYSQL_TX_ISOLATION_COMPAT=false
+ POSTGRES_SEEDS=airbyte-db-svc
+ POSTGRES_USER=airbyte
+ POSTGRES_PWD=airbyte
+ ENABLE_ES=false
+ ES_SCHEME=http
+ ES_SEEDS=
+ ES_PORT=9200
+ ES_USER=
+ ES_PWD=
+ ES_VERSION=v7
+ ES_VIS_INDEX=temporal_visibility_v1_dev
+ ES_SCHEMA_SETUP_TIMEOUT_IN_SECONDS=0
+ TEMPORAL_CLI_ADDRESS=10.0.148.192:7233
+ SKIP_DEFAULT_NAMESPACE_CREATION=false
+ DEFAULT_NAMESPACE=default
+ DEFAULT_NAMESPACE_RETENTION=1
+ SKIP_ADD_CUSTOM_SEARCH_ATTRIBUTES=false
+ '[' false '!=' true ']'
+ validate_db_env
+ '[' postgresql == mysql ']'
+ '[' postgresql == postgresql ']'
+ '[' -z airbyte-db-svc ']'
+ wait_for_db
+ '[' postgresql == mysql ']'
+ '[' postgresql == postgresql ']'
+ wait_for_postgres
+ nc -z airbyte-db-svc 5432
+ echo 'PostgreSQL started.'
+ setup_schema
+ '[' postgresql == mysql ']'
PostgreSQL started.
+ '[' postgresql == postgresql ']'
+ echo 'Setup PostgreSQL schema.'
Setup PostgreSQL schema.
+ setup_postgres_schema
+ SCHEMA_DIR=/etc/temporal/schema/postgresql/v96/temporal/versioned
+ '[' temporal '!=' airbyte ']'
+ temporal-sql-tool --plugin postgres --ep airbyte-db-svc -u airbyte -p 5432 create --db temporal
2022-12-23T18:34:23.555Z	ERROR	Unable to create SQL database.	{"error": "pq: database \"temporal\" already exists", "logging-call-at": "handler.go:97"}
2022/12/23 18:34:23 Loading config; env=docker,zone=,configDir=config
2022/12/23 18:34:23 Loading config files=[config/docker.yaml]
{"level":"info","ts":"2022-12-23T18:34:23.571Z","msg":"Updated dynamic config","logging-call-at":"file_based_client.go:143"}
{"level":"info","ts":"2022-12-23T18:34:23.571Z","msg":"Starting server for services","value":["history","matching","frontend","worker"],"logging-call-at":"server.go:123"}
Unable to start server. Error: sql schema version compatibility check failed: version mismatch for keyspace/database: "temporal". Expected version: 1.6 cannot be greater than Actual version: 1.4
```

## Steps to Reproduce
1. Deploy Airbyte using helm chart v0.43.3
2. Upgrade Airbyte using helm chart v0.43.6
3. List pods and see airbyte-temporal pods failing

## Are you willing to submit a PR?

Yes I would love to contribute, but my helm chart knowledge is pretty slim at the moment. I don't know where to begin debugging the issue at the moment.

**Comment by rnonnon** [comment]
Seems to be the same issue as #16437

**Comment by rnonnon** [comment]
Not really clean but I'm not yet in production so I dropped temporal & temporal_visibility database and it's fine.
Hope this help.

**Comment by marcosmarxm** [comment]
Close because its outdated.

**Comment by lydialimsetel** [comment]
I have tried the drop table method before deploying the new temporal version 1.13, and can confirm it works. You'll need to force a drop if you don't want to go cancel connections one by one. I did it via `psql`:


```
postgres=> DROP DATABASE IF EXISTS TEMPORAL_VISIBILITY WITH (FORCE);
postgres=> DROP DATABASE IF EXISTS TEMPORAL WITH (FORCE);
```
