### ISSUE TITLE
Source MYSSQL - Primary and Foreign Keys not migrated from SQL Server to Postgres

### ISSUE THREAD

**Issue by GQAdonis** [airbytehq/airbyte#20876]
When using the open source version of Airbyte to migrate SQL Server tables to Postgres, the primary and foreign key relationships are not preserved.  As a result the migrated database is useless for all practical purposes.

Is there an answer for this?

## Environment
- **Main Branch**:  
- **Linux / Kubernetes on AWS**
- **Source Connector: MSSQL**
- **Destination Connector Postgres**
- **Standard deployment**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Tables and data are migrated to Postgres, but all keys and relationships are missing.

## Expected Behavior
When the data is migrated I would expect the primary and foreign keys to be preserved.

**Comment by jfox-teine** [comment]
Are you losing the value or just the key constraints? Airbyte is extract load, not clone.
