### ISSUE TITLE
Extract SQLs for Java source test datasets. 

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#20885]
| Source name | Dataset type | SQL |
|---|---|---|
| clickhouse | - | [clickhouse.txt](https://github.com/airbytehq/airbyte/files/10307749/clickhouse.txt) |
| cockroachdb | Basic | [cockroachDb_basic.txt](https://github.com/airbytehq/airbyte/files/10308493/cockroachDb_basic.txt) |
| cockroachdb | Full | [cockroachDb_full.txt](https://github.com/airbytehq/airbyte/files/10308492/cockroachDb_full.txt)  |
| cockroachdb | Full without nulls | [cockroachDb_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10308490/cockroachDb_full_nonull.txt) |
| db2 | Basic | [db2_basic.txt](https://github.com/airbytehq/airbyte/files/10307922/db2_basic.txt) |
| db2 | Full | [db2_full.txt](https://github.com/airbytehq/airbyte/files/10307924/db2_full.txt) |
| db2 | Full without nulls | [db2_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10307926/db2_full_nonull.txt) |
| mssql | Basic | [mssql_basic.txt](https://github.com/airbytehq/airbyte/files/10308157/mssql_basic.txt) |
| mssql | Full | [mssql_full.txt](https://github.com/airbytehq/airbyte/files/10308159/mssql_full.txt) |
| mssql | Full without nulls | [mssql_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10308160/mssql_full_nonull.txt) |
| mysql | Basic | [mysql_basic.txt](https://github.com/airbytehq/airbyte/files/10308587/mysql_basic.txt) |
| mysql | Full | [mysql_full.txt](https://github.com/airbytehq/airbyte/files/10308589/mysql_full.txt) |
| mysql | Full without nulls | [mysql_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10308591/mysql_full_nonull.txt) |
| oracle | Basic | [oracle_basic.txt](https://github.com/airbytehq/airbyte/files/10308579/oracle_basic.txt) |
| oracle | Full | [oracle_full.txt](https://github.com/airbytehq/airbyte/files/10308581/oracle_full.txt) |
| oracle | Full without nulls | [oracle_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10308582/oracle_full_nonull.txt) |
| postgres | Basic | [postgres_basic.txt](https://github.com/airbytehq/airbyte/files/10308729/postgres_basic.txt) |
| postgres | Full | [postgres_full.txt](https://github.com/airbytehq/airbyte/files/10308730/postgres_full.txt) |
| postgres | Full without nulls | [postgres_full_nonull.txt](https://github.com/airbytehq/airbyte/files/10308731/postgres_full_nonull.txt) |
| tidb | - | [tidb_basic.txt](https://github.com/airbytehq/airbyte/files/10308754/tidb_basic.txt) |

**Comment by DoNotPanicUA** [comment]
Hi @evantahler,
Here you can find all SQL Java source scripts for making test datasets.
You may notice that usually there there is a source:
- Basic - contains simple types and there is not null values
- Full - all possible types
- Full without nulls - all possible types, but without nulls in the data

**Comment by evantahler** [comment]
👍 

https://github.com/airbytehq/airbyte/pull/20955 will store them in the project
