### ISSUE TITLE
csv discovery takes too much memory

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2089]
## Expected Behavior
Discovery should work with memory requirements scaling based on number of columns, not the number of rows.

## Current Behavior
On a t2.large instance, discovering a 5gb CSV file freezes and gets killed as OOM.

## Severity of the bug for you
High

We probably need to mess with how our loaded file is stored in memory or change the type inference process to scan rows without storing them all in memory.

**Comment by yevhenii-ldv** [comment]
To read data from the `csv`, we use **Pandas** `read_csv`, and we use it in such a way that we immediately read the full file and keep it in memory.
However, we can use the `chunsize` parameter for the `read_csv` function and read the file with batches of 500 lines, for example.

_Guesstimating 4-5hr for fixing_
