### ISSUE TITLE
Source Snapchat Marketing: extend metrics in basic report 

### ISSUE THREAD

**Issue by iberchid** [airbytehq/airbyte#20895]
## Tell us about the problem you're trying to solve
We found below metrics missing in the connector:
- `story_opens`
- `story_completes`

## Describe the solution you’d like
Add the missing metrics to the `METRICS` List in the `source.py` file

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Thanks for doing this cntribution @iberchid !

**Comment by marcosmarxm** [comment]
Closed by #20897
