### ISSUE TITLE
Airbyte Normalization issue while loading data

### ISSUE THREAD

**Issue by dugyalavinay** [airbytehq/airbyte#20890]
Hi There,

I have been trying to load data from MSSQL Server to Snowflake by using Airbyte open source tool. 
So while loading Json data from Airbyte I can see the data is populating in snowflake.
Facing Issue while loading data in normalized format through Airbyte.

[logs.txt](https://github.com/airbytehq/airbyte/files/10309741/logs.txt)
![airbytelog](https://user-images.githubusercontent.com/121508842/209698790-65b01fc1-28ef-4fa6-88d4-ed6bd768f08d.PNG)

**Comment by marcosmarxm** [comment]
Somehow the normalization container is considering the instructions invalid.
```
.
2022-12-27 15:06:31 [42mnormalization[0m > /airbyte/entrypoint.sh: line 116:    14 Illegal instruction     dbt ${dbt_additional_args} run --profiles-dir "${PROJECT_DIR}" --project-dir "${PROJECT_DIR}"
2022-12-27 15:06:31 [42mnormalization[0m > /airbyte/entrypoint.sh: line 116:    16 Illegal instruction     dbt debug --profiles-dir "${PROJECT_DIR}" --project-dir "${PROJECT_DIR}"
```

What OS are you running Airbyte server? There are other connections to the destination? Are they working?

**Comment by dugyalavinay** [comment]
We are running this on a windows server. Yes, I have tried with another duplicate connection but facing the same issue . Let us know if reinstalling the docker setup will work? Thanks for your response.

**Comment by marcosmarxm** [comment]
My question is if you have other connections besides that one and if they are working. I'd suggest to try using another OS besides Windows.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
