### ISSUE TITLE
Updating a Source / Destination does not allow updating its name

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2090]
## Current Behavior
* changing the name in the UI and hitting save does not change the name

## Expected Behavior
* it should change

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368090047486) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
FE is sending the correct payload but looks like the backend API is not updating the source and destination name (I tested for both).
I try to trigger the API using swagger and get the same response: no changing and name.
![image](https://user-images.githubusercontent.com/5154322/116685335-8b247200-a988-11eb-8944-014772b50a6b.png)


![image](https://user-images.githubusercontent.com/5154322/116685592-fd955200-a988-11eb-9d17-0b5b76fa0ad3.png)

I'll try to correct this, another user report this error again

**Comment by marcosmarxm** [comment]
https://github.com/airbytehq/airbyte/pull/3176 solved the issue.
