### ISSUE TITLE
Source Postgres: REPLICA IDENTITY DEFAULT causing JSON columns to update errors

### ISSUE THREAD

**Issue by gouravd** [airbytehq/airbyte#20929]
## Environment
- **Airbyte version**:  example is 0.40.25
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 1.0.34 
- **Destination Connector and version**: BigQuery 1.2.9 
- **Step where error happened**: Sync job, Transformation

## Current Behavior
I am using Postgres 14 with REPLICA IDENTITY DEFAULT on table having 1 JSON column which contains large objects mostly. In Dedupe mode, the json column in final table is getting updated as "__debezium_unchanged_value" instead of original value JSON value. This happens when we update any column in row except json column. As per https://debezium.io/blog/2019/10/08/handling-unchanged-postgres-toast-values/, this is expected value. I also see in raw tables that the value is incoming as "__debezium_unchanged_value". Setting REPLICA IDENTITY FULL (as a test) solves this but not an option for us.

## Expected Behavior
When the raw value is "__debezium_unchanged_value", the transformation should not update the json column to "__debezium_unchanged_value" but rather keep it at original value. 

## Logs
NA

## Steps to Reproduce
1. Create Table with JSON column and another two other columns. 
2. Add JSON values > 8KB
3. SET REPLICA IDENITY DEFAULT
3. Edit any column other than JSON and see json column get updated to "__debezium_unchanged_value"

## Are you willing to submit a PR?
Yes

**Comment by rodireich** [comment]
Part of better support for Toast and large columns
