### ISSUE TITLE
Connector Request

### ISSUE THREAD

**Issue by shivaanii23** [airbytehq/airbyte#20949]
As per our requirement , we need mongodb as source and google cloud storage as the destination for creating data warehouse.

**Comment by sh4sh** [comment]
Hey @shivaanii23 , this is possible using our current connectors! Please give them a try, and feel free to post in [Slack](https://slack.airbyte.io/) if you have any more questions.

MongoDB source connector: https://docs.airbyte.com/integrations/sources/mongodb-v2/
Google Cloud Storage destination connector: https://docs.airbyte.com/integrations/destinations/gcs

**Comment by nataliekwong** [comment]
Hi there, since it's been a while since the last response, I'll go ahead and close this issue.
