### ISSUE TITLE
Low code CDK: Remove single slice from manifest

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#20958]
The `SingleSlice` slicer is an implementation detail of the default components of the low code CDK. As there is no reason to explicitly configure it in the manifest yaml, it should be removed from the API to keep it as simple as possible.

Ideally this change is done before the next stable release.

cc @brianjlai

**Comment by brianjlai** [comment]
@flash1293 I think we did this right? A cursory glance through our repo and i don't see it in the manifest schema and a search for `SingleSlice` is only an intercom custom component. I'll close this and if this is actually not done we can reopen
