### ISSUE TITLE
Destination Databricks: Replicate data into new catalog instead of metastore

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#20953]
## Tell us about the problem you're trying to solve
Currently, a new schema and the corresponding stream are created as a table in Metastor. I would like to store the replicated data in a dedicated catalogue and schema and thus use the three-level namespace.

In my opinion, this would allow use case or department related data to be better organised within databricks.

## Describe the solution you’d like
To ensure backwards compatibility with databricks accounts that do not have unity catalog enabled, I would add a boolean to the configuration to enable the new logic. Once enabled, the streams will be replicated to a new catalog including the specified schema. Which catalogue is used can also be configured.

## Are you willing to submit a PR?
Yes, PR is on the way

<img width="660" alt="Bildschirmfoto 2023-01-02 um 21 49 53" src="https://user-images.githubusercontent.com/39857259/210277119-59f56e0d-de65-472f-bd4c-9177e009c3fe.png">

<img width="708" alt="Bildschirmfoto 2023-01-02 um 21 47 33" src="https://user-images.githubusercontent.com/39857259/210276973-05edce93-27d7-4d72-8735-094fd7de0530.png">

**Comment by evantahler** [comment]
Closing, as I believe this was fixed by https://github.com/airbytehq/airbyte/pull/24657
