### ISSUE TITLE
Cannot deselect primary key or cursor field when switching from incremental to full refresh

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#20952]
When a user selects an incremental sync mode (append or deduped history) they might define a cursor or primary key. These fields are persisted as part of the `AirbyteStreamConfiguration`. When switching the connection from one of these incremental modes back to a full refresh mode (overwrite or append), the cursor and primary key remain persisted in the `AirbyteStreamConfiguration`. If a user subsequently deselects either the cursor or (one of the) primary key(s), the backend rejects the payload with e.g. `"The provided configuration does not fulfill the specification. Errors: Cursor field cannot be de-selected"`

I can imagine two possible solutions to this problem:
1. On the frontend or backend, clear both the `primaryKey` and/or `cursorField` fields from the `AirbyteStreamConfiguration` when a user switches to a non-incremental sync mode.
2. On the backend, only validate the `primaryKey` and/or `cursorField` if they are necessary for the selected sync mode.

I have a slight preference for 2, since we could still persist the previously selected PK and cursor if a user wants to switch back to an incremental mode later.

To reproduce, assuming field selection is enabled:
1. Create a connection with a postgres source
2. Set the connection to `Incremental | Append`, define a cursor, save the connection
3. Change the connection to `Full refresh | Overwrite`, deselect the previously selected cursor field
4. Save the connection, observe a 422 error

https://user-images.githubusercontent.com/7550957/210261590-b4ee6dc3-d5dd-4064-baf1-149b8d855958.mov

**Comment by pmossman** [comment]
Refining notes: approach 2 sounds good, backend only change that should be pretty straightforward

**Comment by josephkmh** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/21117
