### ISSUE TITLE
Reinstate Deleted Connections

### ISSUE THREAD

**Issue by wjmolina** [airbytehq/airbyte#20972]
As per the recommendation of @natalyjazzviolin:
> Hi Jeremy, unfortunately there's no way to currently reinstate a deleted connection! This sounds like a really useful feature and something that we should have, please make a feature request on GitHub for this. Thanks!

I discovered that it is possible to reinstate deleted sources and destinations by updating the `tombstone` column of the relevant row in the `actor` table of the Airbyte database from `true` to `false`.

However, although updating the `status` column of a connection's row in the `connection` table from `deprecated` to `active` brings it back to the UI, the connection cannot sync due to an error related to an invalid workflow ID.

It would be useful if connections could be reinstated analogously.

**Comment by mfsiega-airbyte** [comment]
The intention of deletion is that it cannot be reversed; the record is preserved with a tombstone for audit/history purposes.

If the intention is to turn a connection off in a reversible manner, it can be disabled. Does that cover the use case here? If not, feel free to re-open and let us know what you have in mind.
