### ISSUE TITLE
Disabled streams in streams table collapse their checkboxes

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#20974]
![image](https://user-images.githubusercontent.com/168664/208943274-56017636-a8ae-4ebf-91a3-c8d69337419b.png)

When you disable a stream it collapses the checkbox to start bulk-editing that stream. The checkbox should hold it's size.

This issue applies to both the current and new streams table.

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend
