### ISSUE TITLE
Tech Spec for "Deploy all eligible OSS connectors to cloud"

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#20982]
Start with this [PRD](https://docs.google.com/document/d/1ATj7ly_jXkidiCobJkB-APT3_S-ihaPxdNZnKTmQ3Ug/edit#heading=h.agrxfsjj7zsy)

Some topics to consider:
* The goal is to promote as many OSS connectors to cloud
  * ...Provided they match the safety requirements in the PRD (SAT testing, use HTTPs, etc).  Is this the full collection of safety requirements?   How can we automate this testing?
* How are connectors physically added to cloud?  Is it still a human operation, or should we automate it?
  * Does this apply to new connectors, or just our existing catalog?
* Now that there are alpha connectors on Cloud, should we be testing them (#connector-health) and should we be responsible for ensuring that they still work?
  * https://github.com/airbytehq/airbyte/issues/20551 has been added to this epic for consideration

**Comment by alafanechere** [comment]
Tech spec available here: https://docs.google.com/document/d/1RilopS3vALagXivs_cyXjduj4_xQGLp7WiI1DgstAZ8/edit#
