### ISSUE TITLE
Feedback when adding a source or destination

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#21]
When adding a source or destination, from the Onboarding or New source, we should test the connections before moving on. 
Here are the screens showcasing the feedback:
- Testing connections: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5894%3A39
- Positive results (with redirection to next step after 2s): https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5894%3A345
- Negative results (with error message and button to resubmit):  https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5894%3A661

@cgardens

**Comment by cgardens** [comment]
i believe this is done. going to close.
