### ISSUE TITLE
CDC : Emit state messages more frequently 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#21009]
Currently in CDC mode for all the databases we emit a state message at the end of the sync. With checkpointing coming in the destination connectors, we should change our CDC  implementation to emit state messages more frequently so that we get the benefits of checkpointing.

**Comment by bleonard** [comment]
Let's emit our LSN state when either of the follow occurs
1. It's been 10 minutes since we last did it
2. ~1000 (you pick) have been emitted.

Consider doing it in the heartbeat for the timing component, but don't overcomplicate things if that's not easy.

**Comment by prateekmukhedkar** [comment]
Plan to release this on week of April 17.
