### ISSUE TITLE
Change the default replication type from "Mirror Source Structure" to "Destination Default" on UI

### ISSUE THREAD

**Issue by etsybaev** [airbytehq/airbyte#21030]
Change the default replication type from "Mirror Source Structure" to "Destination Default" on UI. This would be a workaround to decrease onCall issues related to this issue: https://github.com/airbytehq/airbyte/issues/20561

Additionally, we may add some notification warn msg for a user that he needs to make sure that the destination doesn't already contain the same schema name as source is going to replicate as part of the "Mirror Source Structure" sync approach. 

Currently, we have a "Check" connection stage in destination connectors, but we check the connection for the schema provided in the connector's config. 

Having the "Mirror Source Structure" by default we may end up with the case when we passed the "Check" connection stage, but then fail because will try to write to another schema that may be not allowed for us. 

Thanks

![Selection_189](https://user-images.githubusercontent.com/4688354/210617929-f66e34af-2a09-47b0-9f50-967ad3d1edab.png)

**Comment by octavia-squidington-iv** [comment]
cc @airbytehq/frontend

**Comment by grishick** [comment]
This is probably a one line change that will have a significant impact on activation experience.
