### ISSUE TITLE
dead link for ConnectorSpecification in docs for cdk python tutorial

### ISSUE THREAD

**Issue by leo-schick** [airbytehq/airbyte#21052]
### Tell us about the documentation you'd like us to add or update.
There the first link [ConnectorSpecification](https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L257) in the first paragraph is dead.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/tutorials/cdk-tutorial-python-http/define-inputs.md)

**Comment by juweins** [comment]
Hey, thanks for the hint! I will quickly fix this 👍🏼

**Comment by juweins** [comment]
@sajarin @leo-schick : I assume it is supposed to forward to this page: https://github.com/airbytehq/airbyte/blob/master/docs/understanding-airbyte/airbyte-protocol.md#spec

**Comment by juweins** [comment]
@marcosmarxm This issue closes with PR #21081

**Comment by sajarin** [comment]
Thanks @juweins for the fix!
