### ISSUE TITLE
Allow modification of the Webapp URL in the OSS Slack notification

### ISSUE THREAD

**Issue by mackenzie-oa** [airbytehq/airbyte#21068]
This WEBAPP_URL env variable is used by the Slack webhook notification for successful/failed jobs, and is currently hardcoded to the internal Kubernetes service (eg `http://airbyte-airbyte-webapp-svc:80`). This means we can't click the link, as the URL is unroutable outside Kubernetes.

The `WEBAPP_URL` is not configurable and is set in `airbyte/templates/env-configmap.yaml` to:

`http://{{ .Release.Name }}-airbyte-webapp-svc:{{ .Values.webapp.service.port }}`
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/env-configmap.yaml#L55

Can this be made configurable/overridable in the Helm chart?

**Comment by GKTheOne** [comment]
I've installed in Kubernetes and all the slack links are using the cluster internal service name/port instead of the ingress host/ssl-port, so I would love to see an ability to modify the base url used for links in notifications.

**Comment by lucianmoldovanu** [comment]
Is there any resolution/roadmap classification for this item? The notifications hook feature is annoying and practically unusable due to this issue.

**Comment by domzae** [comment]
FYI this has been resolved in #23269, and works with at least chart v0.48.2 (maybe something earlier?)

**Comment by mfsiega-airbyte** [comment]
Closed by https://github.com/airbytehq/airbyte/issues/23269.
