### ISSUE TITLE
UI for free connector components

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#21074]
New/updated UI components:
- status pill variants with "free" overlay for alpha and beta
- banners:
  - big showy marketing banner, images, the whole shebang
  - more subtle/interstitial banner for mid-connection-creation workflow
- signup modal with marketing images and stripe setup payment CTA

This new UI should all be conditionally-rendered, but the conditions can be hardcoded booleans behind a sensible API boundary during initial development. Similarly, clicking the stripe setup payment CTA can be a noop until the new endpoint it will hit is ready.
 
![image](https://media.tenor.com/faPfYg--3D0AAAAC/indiana-jones-harisson-ford.gif)

**Comment by pmossman** [comment]
Refining notes:
- Alex can split out more granular tickets from this to divide up the work
