### ISSUE TITLE
Setup branch & process for merging lowcode breaking changes

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#21075]
Set up some of the basic pieces so that it will be procedural how multiple developers will commit their low-code breaking changes to the repository w/o releasing them to developers until we are ready to bump the version all at once

## Acceptance Criteria

- [x] Create the `low_code_cdk_to_beta` branch and push it to the remote repo
- [x] Document the process for how to make and commit breaking changes to the `low_code_to_beta` branch

**Comment by brianjlai** [comment]
the refactor is merged to master and the new branch has been pushed to the repo
