### ISSUE TITLE
Source S3: NPE during API call when optional field is not provided

### ISSUE THREAD

**Issue by showbufire** [airbytehq/airbyte#21131]
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: S3 0.1.27
- **Destination Connector and version**: Not Applicable
- **Step where error happened**: Set up source then check source connection (using rest API)

## Current Behavior
When creating S3 source using rest API, If not specifying `quote_char`, which defaults to `"`, connection check will returns an error `TypeError: object of type 'NoneType' has no len()`. After explicitly specifying it in the rest call, the source connection check succeeded, and I was able to do a successful sync later. 

I also tried tweak it in the UI afterwards, it seems the problem would persist and other fields, like encoding, has similar issue. 

## Expected Behavior
Non-required fields should be optional in the API request. It also works fine on Source S3 0.1.26.

## Logs
```
airbyte-worker                    | 2023-01-06 19:26:12 ERROR i.a.w.i.DefaultAirbyteStreamFactory(internalLog):116 - Traceback (most recent call last):
airbyte-worker                    |   File "/airbyte/integration_code/source_s3/source_files_abstract/source.py", line 62, in check_connection
airbyte-worker                    |     stream.fileformatparser_class(stream._format)._validate_config(config)
airbyte-worker                    |   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 64, in _validate_config
airbyte-worker                    |     self._validate_field_len(config, "quote_char")
airbyte-worker                    |   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 55, in _validate_field_len
airbyte-worker                    |     if len(config.get("format", {}).get(field_name)) != 1:
airbyte-worker                    | TypeError: object of type 'NoneType' has no len()
```

## Steps to Reproduce
1. api call to create sources
http://localhost:8000/api/v1/sources/create

json data: 
```
{
"sourceDefinitionId":"69589781-7828-43c5-9f63-8925b1c1ccc2",
"connectionConfiguration":{
  "dataset":"default",
  "format":{
     "filetype":"csv",
     "delimiter":","
  },
  "path_pattern":"**",
  "provider":{
     "aws_access_key_id":"YOUR_AWS_KEY",
     "aws_secret_access_key":"YOUR_AWS_KEY",
     "bucket":"YOUR_BUCKET",
     "path_prefix":"YOUR_PREFIX"
  },
  "schema":"{\"title\":\"string\",\"movieId\":\"integer\",\"timestamp\":\"integer\",\"genres\":\"string\"}"},"
  workspaceId":"eb7d12d0-3a5a-4ba6-a244-33c0e63d822e",
  "name":"some name"
}
```

2.
api call http://localhost:8000/api/v1/sources/check_connection

json data
```
{"sourceId":"SOURCE_ID_RETURNED_FROM_THE_CREATE_CALL_ABOVE"}
```

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/25067
