### ISSUE TITLE
Airbyte Native Hubspot connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2114]
## Tell us about the problem you're trying to solve
We've recently received a few requests to support replicating more entities from our Hubspot connector. The connector is currently Singer-based and replicates the following entities: 
* "subscription_changes"
* "email_events"
* "forms"
* "workflows"
* "owners"
* "campaigns"
* "contact_lists"
* "contacts"
* "companies"
* "deals"
* "deal_pipelines"
* "engagements"
* "contacts_by_company"

We've received requests to support the following entities: 
* tickets
* products
* line_items
* quotes

Plus some extra fields in various entities (Contacts, Deals, Companies): 

property_country.updatedByUserId
property_country.versions
property_createdate.updatedByUserId
property_createdate.versions
property_d_u_n_s_number_c.updatedByUserId
property_d_u_n_s_number_c.versions
property_description.updatedByUserId
property_description.versions
property_dnb_business_name.updatedByUserId

## Describe the solution you’d like
We'd like to have a hubspot source which: 
* replicates the current set of entities 
* replicates the new requested entities and properties
* replicates data in an incremental fashion

Preferably this connector is written from scratch for the Airbyte protocol rather than forked from the singer hubspot tap. 

## Describe the alternative you’ve considered or used
Fork tap-hubspot, which is what our current connector is based on, to add support for these entities. The upside is that it's probably less work. The downside is that it'll carry Singer baggage in the code.

**Comment by sherifnada** [comment]
@eugene-kulak has volunteered to scope and provide breakdown (and implement). Initial breakdown: 
- [ ] Populate the `schema/` folder
- [ ] Make sure all streams in the API have data
- [ ] implement all current streams as full refresh. Eugene will provide better breakdown of this point. 
- [ ] implement incremental on those streams
- [ ] implement incremental for extra streams and properties

**Comment by sherifnada** [comment]
@eugene-kulak will create tickets and populate in the connector roadmap Project

**Comment by sowla** [comment]
Hi, I see `contacts_by_company` listed in this and similar tickets (#2150, #2160), but I don't see it anywhere in the code or the [Hubspot source documentation](https://docs.airbyte.com/integrations/sources/hubspot#step-2-configure-the-scopes-for-your-streams). I was wondering if there are plans to add this stream too?
