### ISSUE TITLE
custom python destination error

### ISSUE THREAD

**Issue by sheshan-doye-konvergeai** [airbytehq/airbyte#21146]
## Environment
- **Airbyte version**:  VERSION=0.40.26
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**:  Docker
- **Step where error happened**: New custom destination creation

## Current Behavior
Trying to create a python custom destination.
testing of **spec** and **check** works fine, but
while testing **write** functionality I get below error:

```
(.venv) sheshan@sheshan:~/Documents/Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-destination$ cat messages.jsonl | docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/sample_files:/sample_files peeyushweav/weav_destination-custom-python:c4prod write --config /secrets/config.json --catalog /sample_files/configured_catalog.json
{"type": "LOG", "log": {"level": "INFO", "message": "Begin writing to the destination..."}}
{"type": "LOG", "log": {"level": "FATAL", "message": "write() missing 1 required positional argument: 'logger'\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 11, in <module>\n    DestinationWeavDestination().run(sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 108, in run\n    for message in output_messages:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 103, in run_cmd\n    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 47, in _run_write\n    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)\nTypeError: write() missing 1 required positional argument: 'logger'"}}
```

## Expected Behavior
write function should not give error related to functions from airbyte_cdk.

## Logs

```
`(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ cat messages.jsonl | python main.py write --config secrets/config.json --catalog sample_files/configured_catalog.json
{"type": "LOG", "log": {"level": "INFO", "message": "Begin writing to the destination..."}}
{"type": "LOG", "log": {"level": "FATAL", "message": "write() missing 1 required positional argument: 'logger'\nTraceback (most recent call last):\n  File \"main.py\", line 11, in <module>\n    DestinationWeavCsv().run(sys.argv[1:])\n  File \"/home/sheshan/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv/.venv/lib/python3.8/site-packages/airbyte_cdk/destinations/destination.py\", line 108, in run\n    for message in output_messages:\n  File \"/home/sheshan/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv/.venv/lib/python3.8/site-packages/airbyte_cdk/destinations/destination.py\", line 103, in run_cmd\n    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)\n  File \"/home/sheshan/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv/.venv/lib/python3.8/site-packages/airbyte_cdk/destinations/destination.py\", line 47, in _run_write\n    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)\nTypeError: write() missing 1 required positional argument: 'logger'"}}
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 

If I add "logger" argument in airbyte_cdk function,
@abstractmethod
    def write(
        self, config: Mapping[str, Any], **logger:logger,** configured_catalog: ConfiguredAirbyteCatalog, input_messages: Iterable[AirbyteMessage]
    ) -> Iterable[AirbyteMessage]:
        """Implement to define how the connector writes data to the destination"""
It succeeds within python testing.

(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ cat messages.jsonl | python main.py write --config secrets/config.json --catalog sample_files/configured_catalog.json
{"type": "LOG", "log": {"level": "INFO", "message": "Begin writing to the destination..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file1.csv, ['file1', '{\"d1\": 1, \"d2\": 2}', 423]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file1.csv,['file1', '{\"d2\": \"2\"}', 4523]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file2.csv, ['file2', '{\"d1\": 1, \"d2\": 2}', 423]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file1.csv,['file1', '{\"d2\": \"2\"}', 4523]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file2.csv,['file2', '{\"d3\": 3, \"d2\": \"2\"}', 4523]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file2.csv,['file2', '{\"d4\": 4, \"d2\": 2}', 4423]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file1.csv,['file1', '{\"d3\": 3, \"d2\": \"2\"}', 4523]"}}
{"type": "LOG", "log": {"level": "INFO", "message": "row written :/tmp/data/airbyte3/file2.csv,['file2', '{\"d4\": 4, \"d2\": 2}', 4423]"}}
{"type": "STATE", "state": {"data": {}}}
{"type": "LOG", "log": {"level": "INFO", "message": "Writing complete."}}
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
```

But after building docker image and testing,
It throws same error for write function.

```
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ docker build . -t peeyushweav/weav_destination-custom-python:c4prodnew
Sending build context to Docker daemon  23.04kB
Step 1/18 : FROM python:3.9.11-alpine3.15 as base
 ---> df5be861e65d
Step 2/18 : FROM base as builder
 ---> df5be861e65d
Step 3/18 : WORKDIR /airbyte/integration_code
 ---> Using cache
 ---> f0017ace6360
Step 4/18 : RUN apk --no-cache upgrade     && pip install --upgrade pip     && apk --no-cache add tzdata build-base
 ---> Using cache
 ---> 9398fbfb21d3
Step 5/18 : COPY setup.py ./
 ---> Using cache
 ---> 127338a2f666
Step 6/18 : RUN pip install --prefix=/install .
 ---> Using cache
 ---> 90679bdae3f3
Step 7/18 : FROM base
 ---> df5be861e65d
Step 8/18 : WORKDIR /airbyte/integration_code
 ---> Using cache
 ---> f0017ace6360
Step 9/18 : COPY --from=builder /install /usr/local
 ---> Using cache
 ---> 970dd7cd88bb
Step 10/18 : COPY --from=builder /usr/share/zoneinfo/Etc/UTC /etc/localtime
 ---> Using cache
 ---> 3e35ebf23209
Step 11/18 : RUN echo "Etc/UTC" > /etc/timezone
 ---> Using cache
 ---> 316c15c8006d
Step 12/18 : RUN apk --no-cache add bash
 ---> Using cache
 ---> 0a5e0f27b638
Step 13/18 : COPY main.py ./
 ---> Using cache
 ---> 6083568d9679
Step 14/18 : COPY destination_weav_csv ./destination_weav_csv
 ---> Using cache
 ---> ed0db5b61cbe
Step 15/18 : ENV AIRBYTE_ENTRYPOINT "python /airbyte/integration_code/main.py"
 ---> Using cache
 ---> fd3e50dda2e3
Step 16/18 : ENTRYPOINT ["python", "/airbyte/integration_code/main.py"]
 ---> Using cache
 ---> 5aa05e0c0b41
Step 17/18 : LABEL io.airbyte.version=0.1.0
 ---> Using cache
 ---> 10ee2b251c36
Step 18/18 : LABEL io.airbyte.name=airbyte/destination-weav-csv
 ---> Using cache
 ---> 2c5d1a96cd8d
Successfully built 2c5d1a96cd8d
Successfully tagged peeyushweav/weav_destination-custom-python:c4prodnew
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ cat messages.jsonl | docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/sample_files:/sample_files peeyushweav/weav_destination-custom-python:c4prod write --config /secrets/config.json --catalog /sample_files/configured_catalog.json
{"type": "LOG", "log": {"level": "INFO", "message": "Begin writing to the destination..."}}
{"type": "LOG", "log": {"level": "FATAL", "message": "write() missing 1 required positional argument: 'logger'\nTraceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 11, in <module>\n    DestinationWeavDestination().run(sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 119, in run\n    for message in output_messages:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 113, in run_cmd\n    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 49, in _run_write\n    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)\nTypeError: write() missing 1 required positional argument: 'logger'"}}
{"type": "TRACE", "trace": {"type": "ERROR", "emitted_at": 1673239293204.68, "error": {"message": "Something went wrong in the connector. See the logs for more details.", "internal_message": "write() missing 1 required positional argument: 'logger'", "stack_trace": "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 11, in <module>\n    DestinationWeavDestination().run(sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 119, in run\n    for message in output_messages:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 113, in run_cmd\n    yield from self._run_write(config=config, configured_catalog_path=parsed_args.catalog, input_stream=wrapped_stdin)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/destinations/destination.py\", line 49, in _run_write\n    yield from self.write(config=config, configured_catalog=catalog, input_messages=input_messages)\nTypeError: write() missing 1 required positional argument: 'logger'\n", "failure_type": "system_error"}}}
(.venv) sheshan@sheshan:~/Documents/Airbyte/New_Airbyte/airbyte/airbyte-integrations/connectors/destination-weav-csv$ 
```

## Steps to Reproduce
1. generate python destination template with generate.sh script
2. complete the destination **spec**, **check**, and **write** functions
3. while testing **write** function gives an error.

**Comment by sheshan-doye-konvergeai** [comment]
below is my custom destination .py file content.
`#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#

import os, json, shutil
from typing import Any, Iterable, Mapping
import csv
from airbyte_cdk import AirbyteLogger
from airbyte_cdk.destinations import Destination
from airbyte_cdk.models import AirbyteConnectionStatus, AirbyteMessage, ConfiguredAirbyteCatalog, Status


class DestinationWeavCsv(Destination):
    def write(
        self, config: Mapping[str, Any], logger: AirbyteLogger, configured_catalog: ConfiguredAirbyteCatalog, input_messages: Iterable[AirbyteMessage]
    ) -> Iterable[AirbyteMessage]:

        """
        TODO
        Reads the input stream of messages, config, and catalog to write data to the destination.

        This method returns an iterable (typically a generator of AirbyteMessages via yield) containing state messages received
        in the input message stream. Outputting a state message means that every AirbyteRecordMessage which came before it has been
        successfully persisted to the destination. This is used to ensure fault tolerance in the case that a sync fails before fully completing,
        then the source is given the last state message output from this method as the starting point of the next sync.

        :param config: dict of JSON configuration matching the configuration declared in spec.json
        :param configured_catalog: The Configured Catalog describing the schema of the data being received and how it should be persisted in the
                                    destination
        :param input_messages: The stream of input messages received from the source
        :return: Iterable of AirbyteStateMessages wrapped in AirbyteMessage structs
        """

        try:
            path = "/local/"+config["output_directory"]
            # path = "/tmp/"+config["output_directory"] #Local path
            if os.path.isdir(path):
                shutil.rmtree(path)
                os.makedirs(path)
            # with open(path, 'w+') as csvfile:
            #     csvwriter = csv.writer(csvfile)
            #     csvwriter.writerow(["stream","data","emitted_at"])
            # for itm in configured_catalog.streams:
            #     stream_path = path+f"/{itm.stream.name}.csv"
            #     if os.path.exists(stream_path):
            for msg in input_messages:
                if str(msg.type)=="Type.RECORD":
                    stream = msg.record.stream
                    stream_path = path+f"/{stream}.csv"
                    if os.path.exists(stream_path):
                        with open(stream_path, 'a') as csvfile:
                            csvwriter = csv.writer(csvfile)
                            data = json.dumps(msg.record.data)
                            emitted_at = msg.record.emitted_at
                            csvwriter.writerow([stream,data,emitted_at])
                            logger.info(f"row written :{stream_path},{[stream,data,emitted_at]}")
                    else:
                        with open(stream_path, 'w+') as csvfile:
                            csvwriter = csv.writer(csvfile)
                            csvwriter.writerow(["stream","data","emitted_at"])
                            data = json.dumps(msg.record.data)
                            emitted_at = msg.record.emitted_at
                            csvwriter.writerow([stream,data,emitted_at])
                            logger.info(f"row written :{stream_path}, {[stream,data,emitted_at]}")
                elif str(msg.type)=="Type.STATE":
                    yield msg
        except Exception as e:
            logger.info(f"Error in destination write function - {str(e)}")
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"Error in destination write function: {str(e)}")

    def check(self, logger: AirbyteLogger, config: Mapping[str, Any]) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the destination with the needed permissions
            e.g: if a provided API token or password can be used to connect and write to the destination.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this destination, content of this json is as specified in
        the properties of the spec.json file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        path = "/local/"+config["output_directory"]
        # path = "/tmp/"+config["output_directory"]
        try:
            os.makedirs(path)
            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            msg = f"Cannot create output directory at {path}. The following error occurred: {e}"
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {msg}")
`

**Comment by sajarin** [comment]
Hey @sheshan-doye-konvergeai thanks for the issue and sorry for the delay. I know you've been asking around for help with this question a few times already. If you've already solved this problem let me know. 

If not, would it be possible for you create a branch with the current state of the connector and share it? It'd make it easier to test and debug. Let me know if this helps.

**Comment by natikgadzhi** [comment]
Closing for now.
