### ISSUE TITLE
[kustomize install] missing metadata.name in object

### ISSUE THREAD

**Issue by cyrgimyos** [airbytehq/airbyte#21148]
## Tell us about the problem you're trying to solve
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/airbytehq/airbyte/master/kube/overlays/stable/kustomization.yaml
```
ends up with an error `missing metadata.name in object`

## Describe the solution you’d like
What would be the way to be able to build all the resources from our repository without cloning your repo & cd in the repo & build?
At the moment, and if I'm not missing something, it seems complicated to build the yaml from a CD solution like argocd. It could be done adding directly the kustomize plugin, but then is inconvenient to apply patches and such from our own `kustomization.yaml` file.

## Describe the alternative you’ve considered or used
Argocd proposes it this way: https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.2/manifests/ha/install.yaml

and it can be used:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.2/manifests/ha/install.yaml
```

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Kustomize is a deprecated K8s installation. Please migrate to Helm.
