### ISSUE TITLE
Source Google Analytics v4 (GA4): Subtract two days from start_date to ensure data is golden

### ISSUE THREAD

**Issue by mutt-santiago-stachuk** [airbytehq/airbyte#21153]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
 The Google Analytics v4 source (GA4) may be missing some data, since [here](https://support.google.com/analytics/answer/9333790?hl=en) says that reports takes up to 48 hours to proccess data

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see
In the `stream_slices` method, add a timedelta subtraction of two days to ensure data is golden

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Yes! [here it is
](https://github.com/airbytehq/airbyte/pull/21152)

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/26283/files
