### ISSUE TITLE
Link from the main app to the connector builder

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#21168]
We need to link from the main application to the connector builder.

Possible entry points:
- New Source page
- Settings/source

**Comment by girarda** [comment]
Notes from today's sync:
- There should be a top-level entrypoint to the connector builder. Eg. a sidebar button linking to the “how do you want to start building your connector?” page

Summary of the user flows:
1. Add a new source connector → Builder a new connector
2. Manage connector settings 
→ Upload a Docker image
→ Build a new low code connector
3. Build a new connector
→ Using a template for existing connector
→ Edit an existing low code connector
→ Upload an existing YAML file

**Comment by Upmitt** [comment]
proto: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3697%3A128255&node-id=3712%3A128773&viewport=583%2C647%2C0.17&scaling=min-zoom&starting-point-node-id=3712%3A130280

**Comment by flash1293** [comment]
Implemented and merged behind a feature flag
