### ISSUE TITLE
Show component reference docs

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#21167]
- Creating a new connector from scratch is still a complex task. We should link to a setup guide to help the user through the process
- Many components are complex and require reading the documentation to be configured. There should be a way to link or display the reference docs from the connector builder

[Link to prototype](https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3589%3A126196&t=781Ic54RMnrYfkJm-0)

**Comment by Upmitt** [comment]
link to prorotype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3589%3A126196&node-id=3591%3A126754&viewport=420%2C561%2C0.39&scaling=min-zoom&starting-point-node-id=3591%3A126754&show-proto-sidebar=1

**Comment by Upmitt** [comment]
https://github.com/airbytehq/airbyte/issues/14340

**Comment by Upmitt** [comment]
Tooltip + learn more link to the documentation : https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3589%3A126196&node-id=3879%3A130293&viewport=-1090%2C687%2C0.5&scaling=min-zoom&starting-point-node-id=3879%3A130293&show-proto-sidebar=1
