### ISSUE TITLE
CreditProcessingCronJob is constantly failing

### ISSUE THREAD

**Issue by cpdeethree** [airbytehq/airbyte#21177]

**Comment by cpdeethree** [comment]
Since December 26, CreditProcessingCronJob has been failing looking for what appears to be the wrong table name:

https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aprod%20-status%3Aok%20resource_name%3A%22SELECT%20prod-cloudapi.public%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&index=trace-search&messageDisplay=inline&sort=desc&spanType=service-entry&spanViewType=errors&viz=timeseries&start=1669874400000&end=1673157540000&paused=true


It doesn't appear to be impacting failures but is probably contributing to alerts being triggered and creating a ton of apm noise:


https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aprod%20-status%3Aok&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanID=14453556598664221379&spanType=service-entry&spanViewType=errors&timeHint=1673299205571&trace=AgAAAYWYZ53DaMLAZgAAAAAAAAAYAAAAAEFZV1laNk8wQUFBQzFaeDBRUGluTmVXTQAAACQAAAAAMDE4NTk4NjktOWQwYS00ODAwLWE2ZTEtYjllOWFlZmNkNTNm&traceID=10152547125887541010&start=1673213208141&end=1673299608141&paused=false

**Comment by cpdeethree** [comment]
Incidentally it looks like the temporal errors are related to that same change: https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aprod%20-status%3Aok&agg_m=count&agg_q=&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&index=trace-search&messageDisplay=inline&sort=desc&spanType=service-entry&spanViewType=errors&step=auto&top_n=10&viz=timeseries&start=1669874400000&end=1673157540000&paused=true

**Comment by cpdeethree** [comment]
I don't see a deploy happening on or around december 26, so this looks to be unrelated to a deployment

**Comment by malikdiarra** [comment]
Closing this as it has not been observed for a while.
