### ISSUE TITLE
Source Shopify - not pulling data before 2020

### ISSUE THREAD

**Issue by wangjoshuah** [airbytehq/airbyte#21173]
## Environment
- **Airbyte version**:  0.40.9
- **OS Version / Instance**:  GCP VM Ubuntu
- **Deployment**: Docker
- **Source Connector and version**: Shopify [Alpha] 0.1.37
- **Destination Connector and version**: Bigquery
- **Step where error happened**: Sync Job

## Current Behavior
It says airbyte synced all historical data, but we don't have orders data on any orders that were modified before 2020

## Expected Behavior
We get all of our order data even back to 2015 into bigquery

## Logs
The sync isn't failing, but it is only pulling data back until 2020.

## Steps to Reproduce
1. Connect Shopify Source
2. Connect Bigquery Destination
3. Create a connection between Shopify -> Bigquery
4. Start import 
5. after import finishes, it will look like we have correct data, but nothing will be there before 2020

## Are you willing to submit a PR?
No

**Comment by sajarin** [comment]
Thanks for the issue @wangjoshuah are you setting a start date when you're setting up the connector?

**Comment by bazarnov** [comment]
@wangjoshuah Hello, this source-connector behavior should be investigated. Are you able to share access to the data you've been working with so we could proceed with tests?

**Comment by bazarnov** [comment]
Closing this issue. The new version was released `0.3.1`. @wangjoshuah please use it, instead.
