### ISSUE TITLE
[Connector Builder] Configurable Record Filter

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#21188]
## Context

Add a forms to the Connector Builder UI to allow users to configure a Record Filter component for a given stream in their connector.

Open Question: it seems like this currently just includes a `backoff_time_in_seconds` field. Is that expected, or should this have more options to configure? If it is expected, then that `backoff_time_in_seconds` field can probably just be exposed directly in the UI
  - This will be fixed by: https://github.com/airbytehq/airbyte/pull/21050/files#diff-0b89fc73ec03c3a68720d8130993a19002036ff67c8e9e201cb1567fa25507a7R855

## Acceptance Criteria
- Users can configure a record filter for a given stream in the connector builder UI
- Configuring this in the UI sets the record_filter on the stream's `requester.record_selector` in accordance with the manifest schema

**Comment by imrehg** [comment]
Would be very interested in a record filter to be configurable in the UI.

Would also be good if a sub-stream's parent stream can be filtered like this too (ie. not all parent entries should be used to run the requests for the the sub-streams). Happy to give some example, if this is not clear.

I would also be happy to help with this as well, if there's anything possible. The Connector Builder UI is pretty neat and definitely speeds things up!
