### ISSUE TITLE
Source Airtable: Normalisation error

### ISSUE THREAD

**Issue by patygold** [airbytehq/airbyte#21196]
## Environment
- **Airbyte version**:  0.40.26
- **OS Version / Instance**: Amazon Linux 2 AMI
- **Deployment**: Docker
- **Source Connector and version**:  Airtable ([airbyte/source-airtable](https://docs.airbyte.io/integrations/sources/airtable)) 1.0.0
- **Destination Connector and version**:  BigQuery ([airbyte/destination-bigquery](https://docs.airbyte.io/integrations/destinations/bigquery)) 1.2.9
- First upgraded Source connector Airtable to 1.0.0
- Then created a new connection between Airtable and Bigquery with the new API key (scopes: data.records:read, data.recordComments:read, schema.bases:read; permissions: All workspaces)
- Added the tables needed, and synced -> No errors
- But all of the columns on the final tables are "null", even though the values are correct in the "_airbyte_raw" table
- Example:
Joining the _airbyte_raw table with the real table (after normalisation), the column is empty, even though the value exists in the _airbyte_raw._airbyte_data as shown in this query bellow.
The query:
```
SELECT
  airtable._airbyte_ab_id,
  JSON_EXTRACT_SCALAR(airtable_raw._airbyte_data, "$.Status"),
  airtable.Status
FROM `airtable.p_e___paid_parking_rental_sync` airtable
JOIN `airtable._airbyte_raw_p_e___paid_parking_rental_sync`  airtable_raw ON airtable._airbyte_ab_id = airtable_raw._airbyte_ab_id

```

The results: 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/8875581/211537271-c4abaa31-c8aa-43b7-b291-93b120f581d3.png">

## Current Behavior
- The normalized table only has `null` values

## Expected Behavior
- The normalized table has all the values that the raw table have

## Logs

[12cde809_e760_4c5e_93f9_16e8776afd71_logs_9712_txt.txt](https://github.com/airbytehq/airbyte/files/10382033/12cde809_e760_4c5e_93f9_16e8776afd71_logs_9712_txt.txt)

## Steps to Reproduce

1. Create a source connector Airtable v1.0.0
2. Then created a new connection between Airtable and Bigquery with the the appropriate API key (scopes: data.records:read, data.recordComments:read, schema.bases:read; permissions: All workspaces) with normalisation
3. Sync at least one table from Airtable to BigQuery
4. Check the normalised table -> they contain values, or if all the columns are null

## Are you willing to submit a PR?
No

**Comment by sherifnada** [comment]
cc @natalyjazzviolin FYI issues related to individual source API connectors should to go `team/connectors-python` ;) relabelled

**Comment by natalyjazzviolin** [comment]
@sherifnada got it! Thank you, noted! :)

**Comment by patygold** [comment]
Hey! This is solved by me with this new Pull Request https://github.com/airbytehq/airbyte/pull/21215/files, so I'm closing it.
