### ISSUE TITLE
Source Apple Search Ads Reports: New Sandbox

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#21192]
A [PR](https://github.com/airbytehq/airbyte/pull/19557) is ready for this connector. We would need a test account to run acceptance tests.

**Comment by igrankova** [comment]
I received an answer from the support: Please be advised search ads is an option available to members of the paid Apple Developer Program.
First I've submitted a request for the D-U-N-S Number which is needed for the Developer Program enrollment.
Now I'm searching for the pricing for making a decision.

**Comment by igrankova** [comment]
@YowanR, 
Completing your enrollment The **Apple Developer Program annual fee** is **99 USD** and the **Apple Developer Enterprise Program annual fee** is **299 USD**, in local currency where available. Prices may vary by region and are listed in local currency during the enrollment process.

**Comment by igrankova** [comment]
@sherifnada, Hi!
Is it possible to access the old sms channel to pass 2F verification on our Apple account? We can't use the new sandbox without a Developer Program enrollment and we can't enroll because we are already members with our old account. So we need to add the new sandbox to the development team using the old account. 
I received a reply from Apple:
![image](https://user-images.githubusercontent.com/87977540/215038493-b10ad2f4-2f7b-435b-aa19-eb9706d8c175.png)
cc @YowanR

**Comment by igrankova** [comment]
Our D-U-N-S number:
117938176

**Comment by sh4sh** [comment]
Hey @sherifnada please check this when you have a chance, currently blocking https://github.com/airbytehq/airbyte/pull/19557

**Comment by igrankova** [comment]
I've paid for the dev program: https://secure5.store.apple.com/shop/order/detail/10078/W1031292472?_si=000010
and added Sandbox to the dev program: [https://appstoreconnect.apple.com/access/user](https://appstoreconnect.apple.com/access/users)
LastPass name: Apple Sandbox Account

**Comment by igrankova** [comment]
![image](https://user-images.githubusercontent.com/87977540/224023267-30f732c9-25a4-48a7-9f16-7c28d061e6f3.png)

**Comment by sh4sh** [comment]
Nice!! Thanks so much!

**Comment by YowanR** [comment]
LGTM!

**Comment by alafanechere** [comment]
Thank you @igrankova , I've opened this issue to seed the account with data to actually test the connector: 
https://github.com/airbytehq/airbyte/issues/24355
