### ISSUE TITLE
Update UI Dropdown design to match Figma

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21204]
Update the current dropdown design to match what's in [Figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=654%3A670&t=wLYvgYKI4AcH27GI-1) ([Prototype](https://www.figma.com/proto/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?page-id=654%3A670&node-id=2256%3A5035&viewport=513%2C-798%2C1&scaling=min-zoom&starting-point-node-id=2256%3A5035&show-proto-sidebar=1).)

Changes include:
* Border radius and drop shadow match for the menu container
* Margins, colors, and borders match the current hover/selected item
* Add ability to add info text
* Add status states
* Icon has a white box background
* "Request new ___" matches the design

Ensure that it's updated for these dropdowns:
- Source/Destination type
- Region selection

Exclude
* Default mode (tracked in separate issue)

**Comment by josephkmh** [comment]
Closing because we are deprecating `DropDown` for `ListBox`
