### ISSUE TITLE
Add a default section to the dropdown menu

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21205]
Add a default section to the dropdown menu. [Figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=654%3A670&t=wLYvgYKI4AcH27GI-1)

* Add an ability to specify the default value
* Have it appear as the first item in the menu, with the word "Default" and the info text showing the value.
* The same value should still appear in the list in the same order
* Update region selection to use the default value

Example: Region selection, the default is "US"
![image](https://user-images.githubusercontent.com/168664/211603743-0748e941-b7bf-4cde-8688-98e9c1e8e733.png)

**Comment by josephkmh** [comment]
Closing because we are deprecating `DropDown` for `ListBox`
