### ISSUE TITLE
[Epic] UI Dropdown improvements

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21203]
## Goals

* Update the current design of the dropdown to match what's in [Figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=654%3A670&t=wLYvgYKI4AcH27GI-1) ([Prototype](https://www.figma.com/proto/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?page-id=654%3A670&node-id=2256%3A5035&viewport=513%2C-798%2C1&scaling=min-zoom&starting-point-node-id=2256%3A5035&show-proto-sidebar=1))
* Clean up any bad code issues for the current Dropdowns

## Design

Current:
![Image](https://user-images.githubusercontent.com/168664/211601009-5cd53409-6398-40e5-b2d2-493abbbf099b.png)

Target:
![Image](https://user-images.githubusercontent.com/168664/211601172-03999a4e-f977-44b7-968a-2d167c7a3482.png)

```[tasklist]
- [ ] #16439
- [ ] #21249
- [ ] #21204
- [ ] #21205
- [ ] #21206
- Refactoring issues: TBD
```

**Comment by timroes** [comment]
As discussed offline, the `DropDown` component is deprecated and should no longer be used. The open tasks at ListBox are tracked here: https://github.com/airbytehq/airbyte/issues/19359

@flash1293 Could you please link your tickets once created for the Dropdown/Listbox here, so we can keep them tracked and linked.

**Comment by flash1293** [comment]
Issues tracking migration

#24393
#24391
#24390

**Comment by flash1293** [comment]
Issue tracking creation of the Menu component: #24394
