### ISSUE TITLE
Add small dropdown menu variants

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21206]
Implement the small dropdown menu variants as seen is [Figma](https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=654%3A670&t=wLYvgYKI4AcH27GI-1) ([Prototype](https://www.figma.com/proto/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?page-id=654%3A670&node-id=2256%3A5035&viewport=513%2C-798%2C1&scaling=min-zoom&starting-point-node-id=2256%3A5035&show-proto-sidebar=1)) and apply to the Pill Selects used in the new streams table.

![image](https://user-images.githubusercontent.com/168664/212337721-619b2a35-2b1a-4a7c-8f9c-e25f3e7d85f6.png)

**Comment by josephkmh** [comment]
Closing because we are deprecating `DropDown` for `ListBox`
