### ISSUE TITLE
Source Open Exchange Rates : New Sandbox

### ISSUE THREAD

**Issue by cptjacky** [airbytehq/airbyte#21217]
We need a Open Exchange Rates API key in order to release https://github.com/airbytehq/airbyte/pull/19434

The API key is free to obtain and has high enough rate limits for integration testing. We just need to create an account on https://openexchangerates.org/

**Comment by igrankova** [comment]
Created a Free Account, LastPass name: Open Exchange Rates Sandbox Account
Generated an [App ID](https://openexchangerates.org/account/app-ids)
[Docs](https://docs.openexchangerates.org/reference/api-introduction)

**Comment by igrankova** [comment]
@cptjacky hi, can you please check the Id and let me know if you need any other support from unblockers here.
