### ISSUE TITLE
Destination Postgres: improve normalization performance with jsonb_to_record

### ISSUE THREAD

**Issue by michelgalle** [airbytehq/airbyte#21213]
## Tell us about the problem you're trying to solve
Using Airbyte I am running backfill of some ingests which have huge tables and the normalization step that unnest the raw json into the scd table takes forever. I actually cancelled the job after 5 hours of dbt running for one table.

## Describe the solution you’d like
Better performance on dbt normalization

## Describe the alternative you’ve considered or used
Looking at the query generated by airbyte and it is using `jsonb_extract_path_text` to extract data from the json blob. Using `jsonb_to_record` is more performant since it will parse the json only one time instead of parsing `number of columns` times.

I actually updated some dbt code we had at the company and the saw a big improvement in performance using `jsonb_to_record`

### Generated by Airbyte:
```
with __dbt__cte__events_ab1 as (
select
    jsonb_extract_path_text(_airbyte_data, 'id') as "id",
    jsonb_extract_path_text(_airbyte_data, 'uuid') as uuid,
    jsonb_extract_path_text(_airbyte_data, 'object') as "object",
    jsonb_extract_path(table_alias._airbyte_data, 'person') as person,
    jsonb_extract_path_text(_airbyte_data, 'flow_id') as flow_id,
    jsonb_extract_path_text(_airbyte_data, 'datetime') as datetime,
    jsonb_extract_path_text(_airbyte_data, 'timestamp') as "timestamp",
    jsonb_extract_path_text(_airbyte_data, 'event_name') as event_name,
    jsonb_extract_path_text(_airbyte_data, 'campaign_id') as campaign_id,
    jsonb_extract_path_text(_airbyte_data, 'statistic_id') as statistic_id,
    jsonb_extract_path_text(_airbyte_data, 'flow_message_id') as flow_message_id,
    jsonb_extract_path(table_alias._airbyte_data, 'event_properties') as event_properties,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    now() as _airbyte_normalized_at
from <redacted>._airbyte_raw_events as table_alias
where 1 = 1
)
```
Updated Snippet:
```
with __dbt__cte__events_ab1 as (
select
    j.id as "id",
    j.uuid as uuid,
    j.object as "object",
    j.person as person,
    j.flow_id as flow_id,
    j.datetime as datetime,
    j.timestamp as "timestamp",
    j.event_name as event_name,
    j.campaign_id as campaign_id,
    j.statistic_id as statistic_id,
    j.flow_message_id as flow_message_id,
    j.event_properties as event_properties,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    now() as _airbyte_normalized_at
from <redacted>._airbyte_raw_events as table_alias, 
     jsonb_to_record(table_alias._airbyte_data) as j(
       "id" text,
       "uuid" text,
       "object" text,
       "person" text,
       "flow_id" text,
       "datetime" text,
       "timestamp" text,
       "event_name" text,
       "event_properties" text,
       "campaign_id" text,
       "statistic_id" text,
       "flow_message_id" text )
where 1 = 1
)
```
With more columns to parse, the difference in performance is bigger.
Another suggestion would be to at the parse of json already cast to correct datatype but that I guess would break the dbt standards used.

## Are you willing to submit a PR?
In the future perhaps. I am new to airbyte and on a tight schedule, don't have the time to setup everything and catchup with all the standards to submit code.

**Comment by marcosmarxm** [comment]
Normalization was migrated to typing-deduping method doesn't use normalization anymore.
