### ISSUE TITLE
[Free connectors] create inline enrollment banner

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#21222]
Part of https://github.com/airbytehq/airbyte/issues/21074. For airbyte employees, a figma mockup of this banner can be found [here](https://www.figma.com/file/wihAJg5mkp61I7lLHs0IpV/FREE-CONNECTOR-PROGRAM?node-id=1104%3A27380&t=hrTg5KcB2XPdZQAV-0); it looks like this (apologies for the grey overlay, technical issue with the screenshot)
![2023-01-10_11-16](https://user-images.githubusercontent.com/7516653/211641551-78f5f86e-d315-4e95-bf80-8ba86be1c227.png)

Clicking on this will trigger displaying the enrollment modal; until that exists, an empty placeholder is fine.

**Comment by tealjulia** [comment]
Is this also supposed to be rendered for source/destination setup of an alpha or beta connector?  Or only on the connection page of a connection with an alpha or beta connector?
