### ISSUE TITLE
Migration of ConfiguredCatalog

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#21234]
## What
For the new data types, we need to migrate the `ConfiguredAirbyteCatalog` that we currently store in the database to v1 objects of the protocol.

## How
Define a Flyway Migration that will
* backup existing configs
  * `connection.catalog` is a `ConfiguredAirbyteCatalog`
  *  `jobs.config` is a `JobConfig` which contains a field that can be a `ConfiguredAirbyteCatalog` if it is a reset or sync
  *  `actor_catalog.catalog` is an `AirbyteCatalog`, do we need to migrate for data types?
* migrate existing configs

Document steps to restore or have a draft PR ready?

**Comment by krishnaglick** [comment]
Groomed, to be mob'd by platform-move backend team.

**Comment by gosusnp** [comment]
Platform has been updated to support on the fly migration of persisted objects instead.
