### ISSUE TITLE
Expose normalization fields when adding custom connectors

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#21257]
When creating a new connector, one often wants to add it manually to a local airbyte instance to see that things are working. After the change to move normalization information into the definitions, these custom connectors that aren't part of the definitions lost the ability to run normalization. 

We should add the normalization / supportsDbt fields to the UI/API for [adding a custom connector](https://docs.airbyte.com/integrations/custom-connectors#adding-your-connectors-in-the-ui) in OSS.

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/21310
