### ISSUE TITLE
Source Amazon Ads: Migrating from version 2 to version 3 of the reporting API

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#21252]
## Tell us about the problem you're trying to solve
Amazon will be deprecating the version 2 Sponsored Products endpoints (version 2) on March 30th, 2023, so they recommend upgrading as soon as possible. The new version (3) adds upgraded historical data and date range functionality that could meet the data needs better.

## Describe the solution you’d like
The current version 2 reporting endpoints for Sponsored Products will be deprecated on March 30th, 2023. 
Sponsored Brands and Sponsored Display reports on version 2 will continue to work after March 30th, 2023.
See the [Migration guide](https://advertising.amazon.com/API/docs/en-us/reporting/v3/migration-guide) and [FAQ](https://advertising.amazon.com/API/docs/en-us/reporting/v3/faq) for details.

## Are you willing to submit a PR?
Yes

**Comment by igrankova** [comment]
@YowanR, the issue is ready for the prioritization.

**Comment by YuliiaNahoha** [comment]
@YowanR will do.

**Comment by YowanR** [comment]
We are blocked on not having Clicks for our Ads -- need to fill up our sandbox account with that data.
