### ISSUE TITLE
Unable to clear the hook url from the notification settings

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21256]
![image](https://user-images.githubusercontent.com/168664/211859415-e08fb294-2169-4223-937b-434d05f43a31.png)

Actual:
When trying to remove the URL from the notification settings and saving, the user gets an error.

Expected:
The user should be able to clear the notification settings when removing the URL.

Steps to reproduce:
1. Go to notification settings
2. Add URL and save
3. Remove URL and save

**Comment by krishnaglick** [comment]
Likely just need to remove the frontend validation if no value is provided.
