### ISSUE TITLE
Document how to enable normalization for a new destination  

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21264]
Check out the steps that Simon needed in this thread https://airbytehq-team.slack.com/archives/C03AS1GAQV6/p1671639716608029 to get normalization working for DuckDB

While making a new destination & adding normalization is something that we only expect Airbyte to do (not OSS users), recent changes have made setting up a new connector difficult - as you need to get the connector correct and the actor definitions.  We should document this.  This information can live on docs.airbyte.com.

**Comment by evantahler** [comment]
cc @sspaeti thanks for being the lab rat!

**Comment by sspaeti** [comment]
FYI: I'm writing a blog post about [How to write an Airbyte Python Destination: DuckDB](https://docs.google.com/document/d/1K5R55sFfkDt3_H_l6PRvLsMwwcRgAiI32dnycroiwhk/edit?usp=sharing) (still in progress, planning on a first draft this week). Maybe some of these could be part of the docs, and I'd love to have a review as soon as the first draft is done.

**Comment by evantahler** [comment]
The steps:
* Add connector to actor definitions
* List normalization fields + normalization versions 
* Add the connector to the destination specs
* Make a new normalization container (or use the generic version)
