### ISSUE TITLE
Clickhouse strict encrypt destination should allow turning off SSL when SSH tunnel is enabled

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#21262]
Currently, destination-clickhouse-strict-encrypt connector removes SSL toggle from spec, but it should instead check that either SSL or SSH tunnel are turned on.

Add disabled to SSL mode.

**Comment by StellaMaUCI** [comment]
Can I be assigned to this issue and attempt to resolve it? I will RP if successful within one week.
