### ISSUE TITLE
Do not depend on configRepository in Discover worker

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#21279]
In https://github.com/airbytehq/airbyte/blob/master/airbyte-commons-worker/src/main/java/io/airbyte/workers/general/DefaultDiscoverCatalogWorker.java#L112 we use configRepository to write to db about the discovered result. As part of Hybrid Cloud effort, we need to move away from depending DB in discover/check workflow in addition to sync workflow, which was already implemented.

This ticket is to create an internal API interface to replace the dependency on configRepository in this linked file.

**Comment by mfsiega-airbyte** [comment]
Notes:
- This is a pre-req for running discover and check jobs in data plane.
- **The scope for this ticket: design and implement an API to store the result of discovery, and use it from the discover workflow.**
- Plan to sync up with @bgroff about internal routes and (internal) API design.

**Comment by mfsiega-airbyte** [comment]
Note: include metrics/alarms etc in DoD.
