### ISSUE TITLE
Prep Instagram business account for implementation

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2127]
## Tell us about the problem you're trying to solve
To unblock #1814 we need to link our business account to our instagram account and FB page. Also need to create a token.

**Comment by sherifnada** [comment]
This has been pretty complicated to setup. We need to do the following: 

1. Link our [instagram business account](instagram.com/airbytehq) to our [Facebook page](https://www.facebook.com/AirbyteHQ). @johnlafleur will need to do this because our insta account is already linked to Anaxi, which only John can edit. 
2. Once this has been done, visit https://developers.facebook.com/tools/explorer/ to create an access token with the following permissions: 
```
ads_management
ads_read
business_management
instagram_basic
instagram_manage_insights
pages_read_engagement
pages_show_list
public_profile
```
This might only be doable by me, but you should try anyways -- the FB docs are really unclear about what's required to be able to generate these permissions on our FB page and instagram account. 

3. At this point you _should_ be able to develop using the token generated from step 2.

**Comment by sherifnada** [comment]
I've generated an access token which can access our instagram account and added it to lastpass under "source instagram insight test creds".

**Comment by eugene-kulak** [comment]
@sherifnada I don't see "source instagram insight test creds" in the LastPass, could you please confirm that you shared the access to zazmic team?
