### ISSUE TITLE
Delete interpolated user input value from input

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#21282]
See slack thread for context: https://airbytehq-team.slack.com/archives/C03TP6W8081/p1673398007886539

Ask is for a way to delete a {{config[]}} value from an input field in a simple way, so that users don't need to manually delete each character

**Comment by girarda** [comment]
We discussed two potential solutions today:
- Solution 1: cross on top of it
- Solution 2: from the dropdown

We decided to go with the first solution because the dropdown solution makes it seem like the user input will be deleted instead of only removed from the field

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/214311210-b1f5ae27-e333-4ab4-8571-2dbe5f1c02eb.png)
