### ISSUE TITLE
Add navigation links to the connector builder in the Airbyte UI

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#21288]
## Context

After completion of https://github.com/airbytehq/airbyte/issues/21284, the connector builder will be reachable by going to https://cloud.airbyte.io/connector-builder

In order to make this more discoverable, we should add links to the connector builder from other places in the Airbyte UI.

## Acceptance Criteria
- Builder is integrated into the MainView of the webapp (i.e. airbyte sidebar is shown even when in the builder)
- Buttons exist in the New source page and in its the dropdown that link to the connector builder, as shown in the [design](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3683%3A129068&scaling=min-zoom&page-id=3404%3A119487&starting-point-node-id=3426%3A123290&show-proto-sidebar=1)
- Add custom connector button in Settings > Sources gives users option between Adding docker container and building a new connector, as shown in the [design](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3426%3A122505&scaling=min-zoom&page-id=3404%3A119487&starting-point-node-id=3426%3A123290&show-proto-sidebar=1)
- A new Builder button is added to the airbyte sidebar, as shown in [the design](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3712%3A128773&scaling=min-zoom&page-id=3697%3A128255&starting-point-node-id=3712%3A130280)
- All of the above places take the user to the Connector Builder Landing Page as implemented in https://github.com/airbytehq/airbyte/issues/21490
- All of the above additions are hidden behind a feature flag for now so that we can control who sees this. Potentially use the same feature flag as the custom connectors flag.
  - We should use a separate feature flag, since the customer connectors will likely already be rolled out to many customers by the time we get to this

**Comment by sherifnada** [comment]
If custom connectors are behind a feature flag, we might need to gate this behind the same feature flag

**Comment by lmossman** [comment]
Notes from builder sync: add a sidebar button, which opens the 3-tile screen in the design here: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?node-id=3426%3A123290&scaling=min-zoom&page-id=3404%3A119487&starting-point-node-id=3426%3A123290&show-proto-sidebar=1
