### ISSUE TITLE
Infra - Create quick job node pool in data plane (AWS)

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#21280]
![imagine more data planes](https://media0.giphy.com/media/XH4nHVEIn8UckcrVVC/giphy.gif?cid=ecf05e47dhrnn5qgtqdvros45kbfesyzwqgcqg6vmu889grp&rid=giphy.gif&ct=g)

*topher edited*

# We need more node pools for AWS both in prod and for dev environments. 

Since we are planning to enable check and discover workflow on dataplane, we need to enable quick job node pool on data plane - those node pools should have higher CPU limits.

this should look like GKE prod's node pool

You will know you are done when:
- [ ] AWS Prod Data Plane has a quick job node pool
- [ ] AWS Dev Data plane has a quick node pool or a story exists to add dev data planes
- [ ] You have contacted the `compose` team to inform the of the availability of this pool

**Comment by mfsiega-airbyte** [comment]
@supertopher 

DoD: the data plane deployment should include a quick job node pool.

**Comment by supertopher** [comment]
@mfsiega-airbyte I edited the above with a DoD. make sure that checks out please.  and I won't notice @ mentions here.  please do me the favor of a slack DM if you need me quickly

**Comment by supertopher** [comment]
There is another issue in cloud to track this on our end.  it's done now.  give us a yell if you need more https://github.com/airbytehq/airbyte-cloud/issues/4118
