### ISSUE TITLE
Create routing logic for discover and check workflow

### ISSUE THREAD

**Issue by xiaohansong** [airbytehq/airbyte#21291]
Now these workflow use the following logic to define the task queue name (simply looking up the job type and translate that to string).

https://github.com/airbytehq/airbyte/blob/master/airbyte-commons-temporal/src/main/java/io/airbyte/commons/temporal/TemporalWorkflowUtils.java#L52

To separate these two workflows into dataplane level we need to implement a routing logic to determine which queue it needs to go based on job id. Once that helper function is implemented, change these functions to make sure when we start the workflow we used this routing logic:

https://github.com/airbytehq/airbyte/blob/master/airbyte-commons-temporal/src/main/java/io/airbyte/commons/temporal/TemporalClient.java#L339-L373

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- In the sync workflow we determine the appropriate queue routing as a task in the connection manager workflow. However, the discover/check workflows don't have this, so we need to do this before we dispatch to a task queue.
