### ISSUE TITLE
Source MSSQL: Support primitive data type on data schema definition

### ISSUE THREAD

**Issue by oidiegobarros** [airbytehq/airbyte#21314]
## Tell us about the problem you're trying to solve
I try get a full schema from database SQL Server, but the AirByte don't capture specific types on my tables.
Points:
   - I have a legacy database SQL Server with specifics datatypes
   -  This datatypes have a inheritance from old migrations
   - I need get all data types from this tables, but AirByte not recognize it.
   - I need others types like 262, 263, 264....
 
![image](https://user-images.githubusercontent.com/104917806/212087078-02e245eb-1ec5-4ffc-bf16-87bcb2bb24fd.png)

## Describe the solution you’d like
A possible solution is allow describe my schema data type when i select my connections

**Comment by mp-pinheiro** [comment]
Can anyone knowledgeable about the codebase confirm if the solution would be along these lines: https://github.com/airbytehq/airbyte/pull/14449 ?  We have a somewhat urgent need of getting this working.

Alternative solutions are also very much welcome.

**Comment by mp-pinheiro** [comment]
We found a solution to this. Turns out the SQL Server expects custom permissions for the custom types, you need to grant them individually to the user that will be used by airbyte to perform the syncs.

i.e:
```sql
GRANT EXEC ON TYPE::[dbo].[266] TO user;
```

With this done to each custom type field, airbyte correctly fetches the schema and syncs normally.

**Comment by mp-pinheiro** [comment]
@sh4sh We can close this issue!

**Comment by sh4sh** [comment]
Thanks for sharing the answer!
