### ISSUE TITLE
Performance issue when updating airbyte catalog

### ISSUE THREAD

**Issue by Jamakase** [airbytehq/airbyte#2132]
There is a performance issue when working with TreeView - all of the rows are rerendered instead of updated one.

## Expected Behavior
Only updated part of the tree is rerendered

## Current Behavior
All the tree is rerendered

## Steps to Reproduce
1. Set up source with a lot of possible streams
1. Set up destination
1. Start setting up a connection
1. Select and unselect streams

## Severity of the bug for you
Low

## Airbyte Version
0.14.4-alpha

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368090716721) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I've had a couple users mention slow performance when interacting with the catalog, so I'm adding this to the queue. Not super high priority but we should deal with it when we can.

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/11762
