### ISSUE TITLE
Create a sandbox account for `source-amplitude`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#21320]
We need a sandbox account for testing `source-amplitude`.

**Comment by YowanR** [comment]
Hey @alafanechere, just for my understanding, what's in the Amplitude account linked integration-test? Is it a live account?

**Comment by alafanechere** [comment]
According to our internal credentials on LastPass I believe our account is indeed using the `integration-test@airbyte.io` email. But according to @bazarnov [here](https://github.com/airbytehq/airbyte/pull/21244/files#r1068231539) the account is live.
For data privacy concerns and test stability and frozen sandbox account with fake data is better.

**Comment by YowanR** [comment]
I see! Got it! Asking because we're compiling a list of all connectors using customer data. Iryna as you work on this, please add it to the list as well. Thanks!
Cc @igrankova

**Comment by evantahler** [comment]
Referencing https://github.com/airbytehq/airbyte/pull/21244#pullrequestreview-1245773047 - I've deleted the existing amplitude information in LastPass and GSM, so until a new sandbox account is created and new secrets added, SAT will fail for `source-amplitude`

**Comment by ycherniaiev** [comment]
@YowanR It quite tricky sandbox.
First i created a free account, and organization(testing)
Then wee need to fill it with fake data. And seems like i found they way how to do this - I made integration with Google Ads  - so all the data from our Google Ads will be availbale for analysis in Amplitude

**Comment by evantahler** [comment]
Keep in mind that our google ads data could have information about our real ad performance that we don't want to make public

**Comment by ycherniaiev** [comment]
These ads have quite little business value (i generated them with very limited budget, low quality - just for some events). Do not think that revealing this info is problmatic

**Comment by evantahler** [comment]
Oh! They are new / sandbox ads (not real ones)!  Then 👍!

**Comment by igrankova** [comment]
@YowanR, as we agreed, we consider the ads that Yurii created to fill this account with test data as fake (sample) data. We can continue using this account for the testing purposes.

**Comment by igrankova** [comment]
Primary Amplitude Iive and Sandbox Orgs
