### ISSUE TITLE
Source Intercom: Migrate connector from Python to YAML

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#21335]

**Comment by bazarnov** [comment]
Updates:
- as far as the QA process is not clear / parts are missing - I'll move this to `On Hold` until it's resolved.

**Comment by bazarnov** [comment]
Back to implementation, since QA Checks are passed.

**Comment by bazarnov** [comment]
Merged into OSS https://github.com/airbytehq/airbyte/pull/23013
