### ISSUE TITLE
Source Pipedrive - normalization fails when syncing data because of the format of date fields

### ISSUE THREAD

**Issue by marcNY** [airbytehq/airbyte#21377]
## Environment
- **Airbyte version**:  0.40.17
- **OS Version / Instance**: GCP n2
- **Deployment**: Docker
- **Source Connector and version**: Pipedrive ALPHA  0.1.13
- **Destination Connector and version**: BigQuery 1.2.9
- **Step where error happened**:  Sync job 

## Current Behavior
The Sync Job is failing during the normalization stage

## Expected Behavior
The Sync Should finish successfully
## Logs

[5ea0e06e_6fbf_4423_ad86_b288e6f329a4_logs_17_txt.txt](https://github.com/airbytehq/airbyte/files/10410824/5ea0e06e_6fbf_4423_ad86_b288e6f329a4_logs_17_txt.txt)

## Steps to Reproduce
1. Create the connector with "Normalized tabular data" transformation
2. Start the Sync
3. The sync will fail

## Are you willing to submit a PR?
Sure If I am able to find the error

**Comment by grubberr** [comment]
similar problem https://github.com/airbytehq/airbyte/issues/18785

I suspect the problem can be here
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/deals.json#L166

Airbyte testing data have "null" for all records for this field and I cannot reproduce this problem for now.

Keeping an eye on this problem ...

**Comment by grubberr** [comment]
Fixed in this PR https://github.com/airbytehq/airbyte/pull/23789
