### ISSUE TITLE
Source GitLab: unit tests missing dependency `mocker`

### ISSUE THREAD

**Issue by pgollangi** [airbytehq/airbyte#21372]
Source GitLab unit tests are failing 

## Environment
- **Airbyte version**:  main
- **OS Version / Instance**: macOS
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 

## Current Behavior
Couldn't run GitLab connector unit tests

## Expected Behavior
Unit tests should pass

## Logs

```
/airbyte/airbyte-integrations/connectors/source-gitlab/unit_tests/conftest.py:8
_____________________________________________________________________________________ ERROR at setup of test_should_retry ______________________________________________________________________________________
file /airbyte/airbyte-integrations/connectors/source-gitlab/unit_tests/test_streams.py, line 22
  def test_should_retry(mocker, requests_mock):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, config, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

```

## Steps to Reproduce
1. Navigate to folder `airbyte/airbyte-integrations/connectors/source-gitlab`
2. Install dependencies
3. run unit tests `python -m pytest unit_tests`, they are failing

## Are you willing to submit a PR?

Yes

**Comment by davydov-d** [comment]
Verified for version 1.2.1 - works fine
