### ISSUE TITLE
Rename SAT to Connector acceptance tests

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#21382]
After https://github.com/airbytehq/airbyte/issues/20063 will be done, the spec part of the SATs are a very useful tool beyond only source connectors as they do basic checks about whether the spec is confirming to all documented requirements and will not cause problems in the UI as well.

The SATs are operating on the docker interface which means the spec test can be run without any changes against destination connector images. However, the name "source acceptance tests" is confusing in the context of destination connectors. As there are already multiple test suites for connectors which can be confusing for novices (e.g. standard destination tests), the source acceptance tests should be renamed to connector acceptance test to better reflect their more general nature. This should be done before spec acceptance tests are rolled out for destination connectors.

## Acceptance criteria

* Source acceptance tests (SAT) are renamed to connector acceptance tests in all places
  * Directory/file names
  * Python classes
  * Documentation
  * Groovy plugin
* Documentation page is adjusted to document new structure
* https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference/ links to new `connector-acceptance-tests-reference` page

**Comment by sherifnada** [comment]
Confirmation: @flash1293 talked w Greg and confirmed that it will be leveraged by destinations team, hence this refactor makes sense
