### ISSUE TITLE
Amplitude

### ISSUE THREAD

**Issue by antohasv** [airbytehq/airbyte#2141]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**Comment by sherifnada** [comment]
@antohasv thanks for creating the request. Can you give us some context to help understand how to prioritize this connector: 
- What is your use case for the amplitude connector?
- Which destination would you like to send your amplitude data to?
- Which entities from the amplitude api would you like Airbyte to support?

**Comment by sherifnada** [comment]
duplicate of #1457 -- @antohasv feel free to comment on that issue with any responses!
