### ISSUE TITLE
🐛 [Epic] Source Shopify: pre-Cloud bugfixes

### ISSUE THREAD

**Issue by YowanR** [airbytehq/airbyte#21412]

**Comment by YowanR** [comment]
@bazarnov I've identified a few errors in OSS than might repo on our Cloud instance. Same feedback as Airtable. Take a look and if you think they won't repro, just leave a comment and close. But this needs to be done as Shopify is the most requested connector. This connector will probably be at the top of the leaderboard for Cloud usage so we need to make sure we're doing this right. cc @lazebnyi @YuliiaNahoha

**Comment by YowanR** [comment]
@bazarnov If we're done with this epic, I think we can release Shopify to Cloud today. Everything is lined up so please let me know once it's been released! 🙏

**Comment by bazarnov** [comment]
> @bazarnov If we're done with this epic, I think we can release Shopify to Cloud today. Everything is lined up so please let me know once it's been released! 🙏 

@Yowan Ramchoreeter (Airbyte) we are waiting for new OSS Release for Shopify to show in Cloud, i’ve consulted with @Augustin Lafanechere (Airbyte) about this, he confirmed.
