### ISSUE TITLE
Snowflake Normalization Fails with DEFAULT as Column Name

### ISSUE THREAD

**Issue by aniljava** [airbytehq/airbyte#2142]
Tested on latest master (0.14.4-alpha) and with verification of commits from #2128 and #2129. 

Could not re-open the #2128 so creating new instead. 

Problem persists with no change in generated SQL. Can some one comment on #2129's expected behavior as well. Having a word defined as keyword ?, does it make quote the column names or change the column name? 

#Problem SQL Generated
    cat ./workspace/6/0/build/compiled/airbyte_utils/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_ADDRESSES_1.sql

 
    select
        _AIRBYTE_CUSTOMERS_HASHID,
        cast(ID as
        int
    ) as ID,
        cast(ZIP as
        varchar
    ) as ZIP,
        cast(CITY as
        varchar
    ) as CITY,
        cast(NAME as
        varchar
    ) as NAME,
        cast(PHONE as
        varchar
    ) as PHONE,
        cast(COMPANY as
        varchar
    ) as COMPANY,
        cast(COUNTRY as
        varchar
    ) as COUNTRY,
        cast(default as boolean) as DEFAULT,
        cast(ADDRESS1 as
        varchar
    ) as ADDRESS1,
        cast(ADDRESS2 as
        varchar
    ) as ADDRESS2,
        cast(PROVINCE as
        varchar
    ) as PROVINCE,
        cast(LAST_NAME as
        varchar
    ) as LAST_NAME,
        cast(FIRST_NAME as
        varchar
    ) as FIRST_NAME,
        cast(CUSTOMER_ID as
        int
    ) as CUSTOMER_ID,
        cast(COUNTRY_CODE as
        varchar
    ) as COUNTRY_CODE,
        cast(COUNTRY_NAME as
        varchar
    ) as COUNTRY_NAME,
        cast(PROVINCE_CODE as
        varchar
    ) as PROVINCE_CODE,
        _airbyte_emitted_at
    from "OPENBRIDGE_DATABASE"._AIRBYTE_AIRBYTE."AB1_ADDRESSES_1"

cat ./workspace/6/0/normalize/models/generated/airbyte_views/_AIRBYTE_AIRBYTE/AB2_ADDRESSES_1.sql
    select
        _AIRBYTE_CUSTOMERS_HASHID,
        cast(ID as {{ dbt_utils.type_int()  }}) as ID,
        cast(ZIP as {{ dbt_utils.type_string()  }}) as ZIP,
        cast(CITY as {{ dbt_utils.type_string()  }}) as CITY,
        cast(NAME as {{ dbt_utils.type_string()  }}) as NAME,
        cast(PHONE as {{ dbt_utils.type_string()  }}) as PHONE,
        cast(COMPANY as {{ dbt_utils.type_string()  }}) as COMPANY,
        cast(COUNTRY as {{ dbt_utils.type_string()  }}) as COUNTRY,
        {{ cast_to_boolean('default')  }} as DEFAULT,
        cast(ADDRESS1 as {{ dbt_utils.type_string()  }}) as ADDRESS1,
        cast(ADDRESS2 as {{ dbt_utils.type_string()  }}) as ADDRESS2,
        cast(PROVINCE as {{ dbt_utils.type_string()  }}) as PROVINCE,
        cast(LAST_NAME as {{ dbt_utils.type_string()  }}) as LAST_NAME,
        cast(FIRST_NAME as {{ dbt_utils.type_string()  }}) as FIRST_NAME,
        cast(CUSTOMER_ID as {{ dbt_utils.type_int()  }}) as CUSTOMER_ID,
        cast(COUNTRY_CODE as {{ dbt_utils.type_string()  }}) as COUNTRY_CODE,
        cast(COUNTRY_NAME as {{ dbt_utils.type_string()  }}) as COUNTRY_NAME,
        cast(PROVINCE_CODE as {{ dbt_utils.type_string()  }}) as PROVINCE_CODE,
        _airbyte_emitted_at
    from {{ ref('AB1_ADDRESSES_1') }}

**Comment by michel-tricot** [comment]
Thank you @aniljava, we will take a look a it!

**Comment by ChristopheDuong** [comment]
The PR #2129 was merged to master but normalization is still not released with that fix so you don't see the corrected behavior yet (even if you are using master branch)

Another big PR on normalization is on its way and will ship the previous fix along with its release here: https://github.com/airbytehq/airbyte/pull/2104 whenever that one will be merged to master.
