### ISSUE TITLE
Hubspot <> Snowflake: Incremental dedup + history not deleting records

### ISSUE THREAD

**Issue by mattimoller** [airbytehq/airbyte#21471]
## Environment
- **Airbyte version**: 0.40.27
- **OS Version / Instance**: AWS EC2
- **Deployment**: AWS EC2 with RDS Postgres DB
- **Source Connector and version**: Hubspot 0.3.0
- **Destination Connector and version**: Snowflake 0.4.42
- **Step where error happened**: Sync job
## Current Behavior
When running Company sync with incremental | Deduped + history, deleted records in Hubspot are not shown as deleted in Snowflake. When running full re-sync the company is deleted as expected.

## Expected Behavior
The company should be successfully marked with an end_at timestamp in the destination SCD-table, and not be present in the regular destination table.

## Logs
[hubspot_snowflake_incremental_logs.txt](https://github.com/airbytehq/airbyte/files/10433341/hubspot_snowflake_incremental_logs.txt)

## Steps to Reproduce
1. Deploy Airbyte on EC2 with the version as described above (0.40.27)
2. Set up a Hubspot <> Snowflake connection and settings as described above
3. Delete a company in Hubspot and run incremental sync

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Normalization will remove if the record is removed or you're using CDC and there is the metadata `deleted_at`. @edgao what your opinion here?

**Comment by mattimoller** [comment]
@marcosmarxm I checked both the normalized and non-normalized tables and the records which are deleted in Hubspot are present in both. As far as I can tell Hubspot doesn't return a deleted_at column or something similar indicating the record is deleted, fetching the record from Hubspot API after deletion returns a 404 Not found. May not be relevant since the Hubspot connector doesn't use CDC.

**Comment by edgao** [comment]
yep, we currently only support deletions for CDC sources, because they're able to emit "tombstone" records (i.e. records that just say "id=42 was deleted at cursor=1234"). source-hubspot doesn't do that, and I'm not sure how feasible it would be. (cc @sherifnada - are we thinking about deletions in API sources right now?)

As you noted, full-refresh overwrite syncs might be a workaround, if your data volume isn't too large.

**Comment by sherifnada** [comment]
@edgao if an API already supports tombstoning (e.g: Salesforce) it's included by default. Other APIs use webhooks separate from their REST APIs (which we use to pull the data) to indicate deletions. Connectors for those APIs currently don't support propagating deletions (when using incremental syncs) and there is currently no timeline on when those would be implemented. 

cc @misteryeo @YowanR  we likely need to start thinking about adding deletions to API connectors, especially big ones like Hubspot, Shopify, Stripe, etc.. where possible. Flagging this for prioritization/product discovery.

**Comment by edgao** [comment]
> tombstoning

ah nice, that makes sense. We might also want to improve how normalization propagates deletions then, since it currently is hardcoded to only work with CDC's `_ab_cdc_deleted_at` column. cc @grishick @misteryeo

**Comment by arsenlosenko** [comment]
Hubspot API still does not support functionality that was discussed here, closing this issue for now.
