### ISSUE TITLE
allow invalidating spec cache for specific images

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2147]
## Tell us about the problem you're trying to solve
We have a spec cache `CachingSchedulerJobClient` which contains a method `invalidateCache` which invalidates the whole cache wholesale. It would be nice to have a method `evictFromCache` which invalidates a specific cache entry to allow invalidating portions of the cache.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368090858910) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@sherifnada What's the problem you're trying to solve? Can we remove the `good first issue` tag or add some clarity on what problem we are trying to solve.
