### ISSUE TITLE
Update local webapp development instructions

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#21482]
### Tell us about the documentation you'd like us to add or update.
[Local webapp development.](https://docs.airbyte.com/contributing-to-airbyte/developing-locally#develop-on-airbyte-webapp)
Add `nvm install` command prior to `npm install`

### If applicable, add links to the relevant docs that should be updated
- [Develop on airbyte-webapp](https://docs.airbyte.com/contributing-to-airbyte/developing-locally#develop-on-airbyte-webapp)

**Comment by timroes** [comment]
@natalyjazzviolin I'm at the moment working on https://github.com/airbytehq/airbyte/pull/22053 which will switch over to use `pnpm` as a package manager. I'll anyway need to document how to use that in this file, so I'll take this over if you don't mind.
