### ISSUE TITLE
Listbox: add a `multiple` property

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#21483]

**Comment by tealjulia** [comment]
Refining notes:
- no longer needed for cursor/primary key selection
- let's check with @flash1293 RE: where this component is needed

**Comment by dizel852** [comment]
Found related issues I was talking about on refinement sync:
https://github.com/airbytehq/airbyte/issues/24391
https://github.com/airbytehq/airbyte/issues/24390

**Comment by tealjulia** [comment]
Great!  I'll close this issue. #24391 sounds like something to keep an eye on as we migrate those forms to `react-hook-form`
