### ISSUE TITLE
Source Trello: ixUpdate field has wrong datatype

### ISSUE THREAD

**Issue by zilehuda** [airbytehq/airbyte#21480]
## Environment
- **Airbyte version**:  v0.40.28
- **OS Version / Instance**: macOS

## Current Behavior
In trello connector, there is a field called ixUpated which has the wrong data type i.e ["null", "integer"] in board stream in discovery whereas from the backend API response, ixUpdated is returning as string.

## Expected Behavior
In discovery of board stream, ixUpated should be ["null", "string"]

## Are you willing to submit a PR?

Yes, I am submitting the PR for this issue.

**Comment by zilehuda** [comment]
I am working on this PR

**Comment by sajarin** [comment]
Hi @zilehuda thanks for the issue, feel free to push a PR and we'd be happy to review the PR.

**Comment by zilehuda** [comment]
Hi @sajarin - please review the PR

**Comment by marcosmarxm** [comment]
See comment https://github.com/airbytehq/airbyte/pull/21881#discussion_r1088734523

**Comment by grubberr** [comment]
Fixed in this PR https://github.com/airbytehq/airbyte/pull/24045
