### ISSUE TITLE
Source MSSQL: CDC job is getting failed due to OOM error

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#21498]
Issue: 

     We have few tables which gets updated bulk hence, we get influx of cdc records (400k) with in hour however, CDC job could not handle as it seems, it is keeping all the records in list/memory before writing to disk 

workaround: 
     Create a seperate connection with one table and added extract memory to containers 

Solution :
   1. Add option to max record limit on each run 
   2. Or, handle the OOM error in the connector

**Comment by sivankumar86** [comment]
[c810ba10_3e93_4c4c_976f_8605746e4520_logs_133898_txt.log](https://github.com/airbytehq/airbyte/files/10671659/c810ba10_3e93_4c4c_976f_8605746e4520_logs_133898_txt.log)
Added error log

**Comment by rodireich** [comment]
Currently the allocated queue size used to buffer debezium event is hard coded to 10,000.
Similar to mongodb-v2 this can be a configurable field.

**Comment by rodireich** [comment]
Hi @sivankumar86 
source mssql connector v4.0.0 is out now with this fix along with many other addtions.
Let me know how it works for you
