### ISSUE TITLE
Performance - logging improvements

### ISSUE THREAD

**Issue by colesnodgrass** [airbytehq/airbyte#21496]
During the performance analysis work it was discovered that our logging implementation can block whenever it uploads the logs. This ticket is to determine if an async logger would be a better choice, especially when uploading the logs to a provider.

**Comment by davinchia** [comment]
@colesnodgrass did we decide how to proceed with this?

**Comment by colesnodgrass** [comment]
@davinchia With the loss of location information (file, class, line) when moving to async-logging, this was put on hold. As, after discussions with the team, location information was deemed too important.

**Comment by davinchia** [comment]
ok! Have we confirmed this is a Log4J2 characteristic? i.e. this is not because of the current way we've tried to do this, and is because the logger itself doesn't support it. I remember we weren't clear on this when we last spoke.

**Comment by davinchia** [comment]
@colesnodgrass since we aren't going to do this, should we close this for now?

**Comment by davinchia** [comment]
Closing this as part of issue clean up.
