### ISSUE TITLE
Source Postgres : Use fast select to get table size estimate in Postgres 

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#21499]
While calculating the estimated rows to be synced for Source Postgres connector the `count()` operation is currently used. However, this is not optimal as : 
- This operation locks the table, so it cannot be performed while reading the data
- This operation can result in a full table scan (slow)

There is a faster way to get a very rough estimate : 
`select reltuples::int8 as count from pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace where nspname='20m_users' AND relname='users';`

However, the issue is that this is wildly incorrect (have seen it return -1) for smaller tables. We'd like to try the fast query and fall back to the slow count if it is negative. 

See discussion : https://github.com/airbytehq/airbyte/pull/20783

**Comment by bleonard** [comment]
It seems like this not get the right number when incremental because we aren't fetching to full table. is that right or am I missing something?

**Comment by akashkulk** [comment]
No, this query is just an estimation. So, for extremely small tables this query returns invalid results (e.g. -1 rows). 

For incremental mode, we do calculate the right number of rows and bytes based on the 
`select count(*) where cursor_field > cursor_value` query
