### ISSUE TITLE
Credentials for NVD API

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#21536]
## Tell us about the problem you're trying to solve
Cannot run integration tests for https://github.com/airbytehq/airbyte/pull/20647 due to missing credentials

## Describe the solution you’d like
Get test credentials for[ NVD API](https://nvd.nist.gov/developers)

**Comment by igrankova** [comment]
NVD API Key Activated

**See the API Key in the LastPass: NVD**

To request a new API key, please resubmit an [API Key Request](https://nvd.nist.gov/developers/request-an-api-key). Please note that activating a new key will deactivate the old key.

**Comment by haithem-souala** [comment]
Hey @igrankova, 
Thank you for your action.
Is the key deployment tooks time to be available, because the CI keeps failling:
```
> Run source venv/bin/activate
[23/01/2023 12:14:13.659740] - WARNING - [site-packages/ci_credentials/secrets_manager.py:170] # not found any secrets of the connector 'source-nvd'
0 secret files were written: 
```

**Comment by igrankova** [comment]
@haithem-souala, the email said that the API key is activated. Maybe you should share the technical details with support? nvd@nist.gov

**Comment by haithem-souala** [comment]
It seems like the CI cannot find the secret of the connector 'source-nvd'.

**Comment by igrankova** [comment]
@haithem-souala, asked our developers for help, they helped me to add the API key to the GCP. Please try again, I hope this time the secrets will be found.
My work is just to add it to the LastPass, usually dev team ads the creds to the Secret Manager by themselves.

**Comment by haithem-souala** [comment]
Looks good, thank you @igrankova!
