### ISSUE TITLE
Clipped namespace, source-defined primary key & cursors in new streams table

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#21545]
See how the source-define primary key is not visible when the cell is small:

![image](https://user-images.githubusercontent.com/168664/213276311-45859205-86b5-40f5-abe9-447ed6f13756.png)

Public is clipped
![Screen Shot 2023-01-18 at 14 31 46](https://user-images.githubusercontent.com/168664/213276724-44c4f259-d2e3-4173-add0-24dc4b1a2631.png)

**Comment by YatsukBogdan1** [comment]
recently talked to @josephkmh and @dizel852 regarding both issues and seems like this https://github.com/airbytehq/airbyte/pull/21253 PR fixed both issues. so lets close this one

**Comment by edmundito** [comment]
Fixed by changes in #21253
