### ISSUE TITLE
Handle protocol v1 data types in UI

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#21542]
Protocol v1 will introduce a new style of declaring schemas, which mostly relies on a set of [predefined primitives](https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/protocol-models/src/main/resources/airbyte_protocol/well_known_types.yaml) rather than relying on JsonSchema's primitive types.

The UI should be updated to display those types correctly (i.e. on the replication tab of a connection). After v1, the UI will no longer need to handle v0 types (so e.g. it would _not_ need to support things like `{"type": "string", "format": "date-time"}`).

**Comment by edgao** [comment]
(fyi @grishick this is a requirement that I missed)

**Comment by gosusnp** [comment]
@edgao, I think the UI is directly getting the datatypes info from the catalog today: https://github.com/airbytehq/airbyte/blob/21b5eabc965a6d85cc5fe33ce15f0bed65e43959/airbyte-server/src/main/java/io/airbyte/server/handlers/helpers/CatalogConverter.java#L39
Following the data type updates, currently the UI should be getting all v1 schemas, I do not know what would be the preferred representation from a front end perspective.

**Comment by gosusnp** [comment]
For context, UI should be using https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/utils/useTranslateDataType.ts today to map the received data type to what is being shown in the UI
