### ISSUE TITLE
Source Appstore: Create a sandbox account

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2155]
## Tell us about the problem you're trying to solve
We currently have no way of testing that our appstore integration works reliably. It's based on a Singer tap which has its own tests, so it's not like we have 0 guarantees, but we need an account with Apple to have full confidence that it works. 

## Acceptance Criteria

1. Create an Apple account that can be used to test the appstore connector
2. Populate this account with data. If it's necessary to run a marketing campaign or something, we should do that. 
3. Get the credentials for the account and add them to CI/integration tests

**Comment by sherifnada** [comment]
High priority because we currently have no way of verifying that this integration works.

**Comment by sherifnada** [comment]
This is blocked on enrolling in the Developer program, which is blocked on obtaining a DUNS number for Airbyte. I applied for one -- @michel-tricot should receive it and will update me when he does. Until then this issue is blocked.

**Comment by michel-tricot** [comment]
Should be good to go now! @sherifnada can I close?

**Comment by sherifnada** [comment]
Yes thank you!
