### ISSUE TITLE
Custom Transformation fails to install MySQL dbt adapter

### ISSUE THREAD

**Issue by BenjaminGK** [airbytehq/airbyte#21579]
## Environment
- **Airbyte version**:  0.40.28
- **OS Version / Instance**:  Windows 11 -> wsl2
- **Deployment**: Docker
- **Source Connector and version**: Zendesk (0.2.20)
- **Destination Connector and version**: MySQL (0.1.20)
- **Step where error happened**: Sync Job

## Current Behavior
When using custom transformation with and without normalization in MySQL destination, the transformation fails because it can't find the  'dbt.adapters.mysql' with the following error: `Error importing adapter: No module named 'dbt.adapters.mysql'`
Running a simple `deps` throw the error
## Expected Behavior
Running custom transformations should use the mysql adapter and dockerimage 

## Logs
[b9567bc6_d2e9_474a_bc57_c8e94f6224db_logs.txt](https://github.com/airbytehq/airbyte/files/10454195/b9567bc6_d2e9_474a_bc57_c8e94f6224db_logs.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?
No

**Comment by natalyjazzviolin** [comment]
Hi! Let's continue discussing this in Slack for now, once we come up with steps to reproduce I will reopen.
