### ISSUE TITLE
`ci_credentials` should not run its own test suite when testing connectors

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21578]
From this [Slack Thread](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1674065875820589)

Consider the following CI failures:

* https://github.com/airbytehq/airbyte/actions/runs/3952365893/jobs/6767377778
* https://github.com/airbytehq/airbyte/actions/runs/3952353866/jobs/6767348269
* https://github.com/airbytehq/airbyte/actions/runs/3952395143/jobs/6767441257

These all were triggered by a connector `/test` command.  The Github Action, before running `ci_credentials` ran it's test suite, which isn't necessary here.  The action failed because within that test suite, we attempt to read and write a secret to GSM, and we observe conflicts.

**Comment by alafanechere** [comment]
I think the tests suite are run with `tox`.
I don't understand yet why the tests are failing: no actual GSM interaction should happen as GSM is mocked in these tests. I can't locally reproduce.
I'll first disable the test run on the tooling which is indeed not required in the context of testing a connector.
