### ISSUE TITLE
Remove legacy server code from airbyte-server

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#21599]
## Tell us about the problem you're trying to solve
After converting both the OSS and Cloud versions of airbyte-server to Micronaut, there will be some legacy code left behind that will make it more difficult to maintain the module.

## Describe the solution you’d like
Remove any/all logic from the custom server framework, including the `ServerApp`, `ServerFactory` and any other classes that are vestiges of the previous custom framework.  Also remove any build dependencies that are no longer necessary.

**Comment by DevPJ9** [comment]
Hello @jdpgrailsdev . I would like to work on this task.
