### ISSUE TITLE
Fix Snowflake tests on master

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#21607]

**Comment by grishick** [comment]
![4CCD3770-CBA2-40BA-9011-25CE62C6FD53](https://user-images.githubusercontent.com/1310940/213508828-7b99fc47-ecc5-475b-a5b6-75ac69528ba5.png)

**Comment by etsybaev** [comment]
Fixed as part of https://github.com/airbytehq/airbyte/pull/21450
