### ISSUE TITLE
Source Hubspot: ensure that every stream has a data to read

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#2160]
## Tell us about the problem you're trying to solve
Please check that all following streams have data:

- subscription_changes
- email_events
- forms
- workflows
- owners
- campaigns
- contact_lists
- contacts
- companies
- deals
- deal_pipelines
- engagements
- contacts_by_company
- tickets
- products
- line_items
- quotes

if data is not there try to populate either with API or manually, if none will work contact @sherifnada

**Comment by eugene-kulak** [comment]
STREAM | NESTED | INCREMENTAL | API | HAS DATA (2020-01-01)
-- | -- | -- | -- | --
subscription_changes | ?? | yes |   | no
email_events |   | yes |   | yes
forms |   |   | marketing | yes
workflows |   |   | automation | yes
owners |   |   | crm | yes
campaigns |   |   |   | ?? encoding or quotes
contact_lists |   |   | crm | yes
contacts |   |   | crm | yes
companies |   |   | crm | yes
deals |   |   | crm | yes
deal_pipelines |   |   |   | yes
engagements |   |   | crm | yes
contacts_by_company | yes (company) |   |   | yes
tickets |   | ? | https://api.hubapi.com/crm-objects/v1/objects/tickets/paged?hapikey=demo | no
products |   | ? | https://api.hubapi.com/crm-objects/v1/objects/products/paged?hapikey=demo | no
line_items |   | ? | https://api.hubapi.com/crm-objects/v1/objects/line_items/paged?hapikey=demo | no
quotes |   | ? | crm | no

**Comment by eugene-kulak** [comment]
unfortunately because some required APIs (marketing and automation) are in beta (not supported by the official client), it makes sense to implement the native client from the scratch

**Comment by eugene-kulak** [comment]
only `subscription_changes` stream don't have data yet, I tried few things, but nothing worked so far. Taking into account that this stream is not new I propose to move on with client implementation.

**Comment by sherifnada** [comment]
sounds good @eugene-kulak
