### ISSUE TITLE
Source Iterable - fill streams with data

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#21603]
Currently, we have the following situation:

45 streams totally
15 streams with data 
    from which, 4 streams with sensitive data (contains airbyte integration test email and email of one airbyte developer)
    
    campaigns
    campaigns_metrics
    channels
    email_bounce
    email_click
    email_open
    email_send
    email_subscribe
    email_unsubscribe
    events
    lists
    list_users
    message_types
    metadata
    users
    templates

So we have expected records for 11 stream only.

API does not allow to fullfil empty streams, and it can be difficult to do it on live account, because it requires the setup of a real 'campaign' and proper interaction from customers.

**Comment by ycherniaiev** [comment]
@midavadim campiagns are available.Lists also. Found only one email (from Zazmic) breaching PII. We are looking at the same account - Primary Dev Iterable from LastPAss

**Comment by igrankova** [comment]
After the sync I see the next empty streams:
email_complaint
email_send_skip
push_send
push_send_skip
push_open
push_uninstall
push_bounce
web_push_send
web_push_click
web_push_send_skip
in_app_send
in_app_open
in_app_click
in_app_close
in_app_delete
in_app_delivery
in_app_send_skip
inbox_session
inbox_message_impression
sms_send
sms_bounce
sms_click
sms_received
sms_send_skip
sms_usage_info
purchase
hosted_unsubscribe_click

@YowanR, we have y.kurochkin@zazmic.com, john@iterable.com emails in the data, should we consider them PII, how do you think? I'm not sure we can edit these records, but I'll find out whether we can delete them.

**Comment by igrankova** [comment]
Created a new issue for the empty streams: Source Iterable: fill streams with test data #22496
