### ISSUE TITLE
Collect info on where to update callback URLs for Oauth sources

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#21609]
In order to migrate airbyte cloud from cloud.airbyte.io to cloud.airbyte.com, all of the callback URLs for our Oauth connectors need to be updated to approve the .com url. 

Pedro provided a list of connectors currently in cloud that use Oauth: 
```
- Amazon Ads
- Amazon Seller Partner
- Bing Ads
- Facebook Marketing
- GitHub
- Google Ads
- Google Analytics (Universal Analytics)
- Google Analytics 4 (GA4)
- Google Directory
- Google Search Console
- Google Sheets
- Harvest
- HubSpot
- Instagram
- Intercom
- LinkedIn Ads
- Mailchimp
- Microsoft teams
- Monday
- Notion
- Pinterest
- Retently
- Salesforce
- Shopify
- Slack
- Smartsheets
- Snapchat Marketing
- Snowflake
- Square
- SurveyMonkey
- TikTok Marketing
- YouTube Analytics
- YouTube Analytics Business
- Zendesk Chat
- Zendesk Sunshine
- Zendesk Support
- Zendesk Talk
```

We should also keep an eye on connectors that are newly implementing Oauth, i.e.:
* We should regenerate this list upon picking up the issue
* During/after the switch, new Oauth connectors will need to use the .com (hopefully it will be obvious if the .io isn't working anymore) 

In order to do so, for each of these, we need to find out where the Callback URL lives and what credentials we need in order to log in to change them. Some of them are bound to be the same - for example, all "Oauth with Google" sources are already taken care of as we added the .com URL to the list in gcloud.

**Comment by evantahler** [comment]
cc @YowanR - the infra team is blocked on moving cloud.airbyte.io to cloud.airbyte.com until we update all of our oAuth apps.   We need a list of:
* Which ones allow multiple URLs and we can make the change today
* which ones only allow one oAuth callback url and we have to wait
* What are the URLs to manage our oAuth apps?
* What are the credentials we need to manage our oAuth apps?

**Comment by evantahler** [comment]
This [spreadsheet](https://docs.google.com/spreadsheets/d/1STtaljp2iAW-khnLyv1iNnbHKmJxW0LcRoXH2igY3s4/edit#gid=0) will have the answers

**Comment by erohmensing** [comment]
@igrankova can you lay out what the next steps are to fill out the red parts of the spreadsheet? Is there anything you need from Airbyte that you don't have access to? 

As a reminder, we are targeting next monday, february 6th for the changeover. 

Grooming: 
- Not that many need to be switched over in real time - we can start on adding the new callback urls now
- Especially those for which the callback URL needs to be reviewed by support - should start with those (luckily all of those support mulitple urls)

**Comment by YowanR** [comment]
Hi @erohmensing, just to clarify, when you're talking about connectors in the red, you're only talking about LinkedIn Ads, Retently, Snowflake, TikTok Marketing and the Zendesk Connector (4 of them), correct? I've marked them as bright yellow so we know exactly what we need to focus on.

**Comment by igrankova** [comment]
@erohmensing, @YowanR 
I'm not sure I can add something in this list. The red connectors are not in the LastPass and I never had an access to the accounts.

**Comment by erohmensing** [comment]
@YowanR yes thanks for clarifying - also the google connectors. I meant the ones for which we don't have access or don't know account details! :)

Let me see if any of the people who were around in the early days know anything about these connectors ...
