### ISSUE TITLE
Source Appstore: Invalid vendor ID error

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2162]
## Expected Behavior
When I create credentials for the Appstore source connector according to the [documentation](docs.airbyte.io/integrations/sources/appstore), I expect that it will work as expected and that I can sync all streams. 

## Current Behavior
* Check connection fails with a "invalid vendor ID" error message
* Pulling Sales reports succeeds
* Pulling any other report fails

## Steps to Reproduce
1. Follow [the documentation](https://docs.airbyte.io/integrations/sources/appstore) to create an app key with the Finance role
1. create a config.json matching the appstore spec and store it in some directory e.g `/tmp/config.json`
2. Navigate to the appstore connector directory and activate the virtual environment: `cd airbyte-integrations/connectors/source-appstore-singer && python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt && pip install .[main]` 
1. `python main_dev.py check --config /ab_tmp/config.json`
2. The check will fail with an error saying the vendor is invalid
3. change the code in `source_appstore_singer/source.py`'s `check_config` method to make the `reportType: "SALES"` and `version: 1_0` and run the check again, it will succeed

## Severity of the bug for you
High - blocking a user from using airbyte

## Airbyte Version
This is happening on all published versions of the connector

**Comment by sherifnada** [comment]
@Muriloo as someone who frequently uses this connector, have you ever seen this issue before?

**Comment by sherifnada** [comment]
This could maybe be explained if the app doesn't offer subscriptions. Confirming with the user.

**Comment by sherifnada** [comment]
the user confirmed they don't offer subscriptions on their app.

**Comment by sherifnada** [comment]
with this info, it seems like the Apple API returns wrong exception messages e.g invalid vendor when the real problem is that subscriptions aren’t enabled for the account. The fix will be to probe the API for all reports it can generate then offer to the user which reports they can sync based on which ones didn’t throw an exception. Silly but I think that’s what can be done with the tools the API gives us.

**Comment by oseh-stake** [comment]
Also interested
