### ISSUE TITLE
Periodic Buffer Flush in Destination Staging Connectors (15 min intervals)

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#21626]
## Tell us about the problem you're trying to solve
Destination's should flush records periodically to the destination table so as to not lose valuable work. The reason being is if a connection takes a long time to sync and each record takes a long time to be received (e.g. slow connection, slow API, etc) then it would still be valuable for the customer to have their data within their destination

## Describe the solution you’d like
Introduce a time component for each destination connector that uses `staging area` with an environment variable so this can be handled across _all_ connectors. At the moment, we want to limit the configurability for the user in favor of a general broad stroke. Later down the line, we can consider how we may want to add a value that can be configured by the user with bounds

## Describe the alternative you’ve considered or used
As mentioned above, a change on the spec for each connector so each user can configure the interval between buffer flushes

## Additional context
Add tests as necessary:
- [ ] Use LOG_CONNECTOR_MESSAGE env variable to see the periodicity of when a flush occurs

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by grishick** [comment]
Notes from grooming:
 - will need to encapsulate `shouldThisFlush`/`shouldThisCommit` logic that decides if records are ready to flush/commit
 - may need to change the mechanism that triggers flushing to not depend (or not only depend) on receiving a new record - TODO: figure out if we can rely on platform to send a message to destination at least once every 15 minutes. Can the platform keep a job hanging if there are no messages for 15 minutes.
 - testing may take longer than implementation
