### ISSUE TITLE
Source Bing Ads: update test creds

### ISSUE THREAD

**Issue by darynaishchenko** [airbytehq/airbyte#21636]
Now the account belongs to someone else, so there is no way to update the access token. Need to update the data to restore the account and update the access token, because now we get an error because the access token is out of date.
Thread in [slack](https://airbytehq.slack.com/archives/C02UF50V9HA/p1673598678876279)
![image](https://user-images.githubusercontent.com/80129833/213662513-a7db349d-698a-4f33-9bee-ca3ccc6f6c0f.png)
![image](https://user-images.githubusercontent.com/80129833/213662565-a81e457a-0bd2-4bf8-a05d-787963d32314.png)

**Comment by igrankova** [comment]
Creds are restored
