### ISSUE TITLE
RUN_DATABASE_MIGRATION_ON_STARTUP config not passed to airbyte-bootloader

### ISSUE THREAD

**Issue by lihan** [airbytehq/airbyte#21638]
Helm chart version

## Environment
- **Airbyte version**:  0.40.27
- **Deployment**: Helm Chart 0.43.18

## Current Behavior
RUN_DATABASE_MIGRATION_ON_STARTUP not passed to `airbyte-bootloader` Pod.
This causes the Airbyte upgrade to fail

## Are you willing to submit a PR?

Yes

Merge Request https://github.com/airbytehq/airbyte/pull/21639

**Comment by marcosmarxm** [comment]
This is fixed. Please upgrade and use latest version of the Helm Chart to use this feature.
