### ISSUE TITLE
Log users who created a connection in Orbit, when not anonymized

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2163]
## Tell us about the problem you're trying to solve
For now, I was trying to be as autonomous as possible to log everything on Orbit, but I'm hitting a wall now. 
Using Zapier, the only way to get the email used in the Segment event is if the email is part of the event sent, as it currently is for the event "Specified Preferences". 
Unfortunately, one important information we're missing on Orbit to better leverage the tool (understand which companies are using us on prod, vs not) is to log "New Connection - Action" with the email, when not anonymized. As it's not part of the event (only indirectly through the "Identify"), Zapier doesn't know who triggered the event.

## Describe the solution you’d like
There are 2 possible solutions:
1. Exceptionally for this particular event "New Connection - Action", we add the property "email" when available. In that case, I will be autonomous to send Slack notifications + Orbit activities. I've discussed with a dev advocate, and that was their workaround (as they faced the same issue)
2. When user triggers event "New Connection - Action", we send another event to [Orbit's API](https://www.orbit.bio/orbit-api/). This would enable me to get the information in Orbit, however, I won't be able to do as I please for the other tools, and for any change, it will require to go through engineering again. 

## Describe the alternative you’ve considered or used
I have a preference for option 1, honestly. It seems a simpler task and gives me more autonomy

**Comment by cgardens** [comment]
okay. I didn't see this until just now. I have added it to the sprint as as stretch. we can try to prioritize it properly next week.

**Comment by michel-tricot** [comment]
Why are we doing it in the frontend and not in the API?

**Comment by cgardens** [comment]
I don't think anything about the implementation has been decided. Just committing to us looking at it next week.

**Comment by johnlafleur** [comment]
A note here: It should be done only when a new connection is created, not at every sync, or it will overflow Orbit and render their love indicator not usable.

**Comment by johnlafleur** [comment]
@ChristopheDuong here's the Segment tracking spreadsheet: https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit?usp=sharing

You need to check the tab "Track" and the event "New Connection - Backend". 
Happy to jump on a call if you need any explanation.

**Comment by ChristopheDuong** [comment]
Is it a bad thing if I add the email to the "Connector Jobs" event too?

or can both "Connector Jobs" and "New Connection - Backend"  events share the same "identity" fields (userId and email)?
