### ISSUE TITLE
Allow selecting previous unselected streams in a source without requiring a reset of existing streams in Microsoft SQL Server and Snowflake connection

### ISSUE THREAD

**Issue by narenkadiri** [airbytehq/airbyte#21642]
I created a connection with SQL Server as source and Snowflake as Destination. In this connection, initially I'm trying to ingest 3 tables from source, later when I trying to select/de-select one table then the connection is getting reset. it is impact all other tables and trying to import data again.

I would like to have a feature, whenever I make changes to this connection (SQL Server connector). it should not import data again.
I see one the issue opened which is very similar but that was related to Postgress and looks like it is implemented already to resolve this issue.

if this feature is something not in pipeline for SQL Server, I would like to know alternate options that it supports so that I will not end up in extracting data all again whenever I make changes to connection.

Currently I'm using below version of airbyte and connectors
Airbyte 0.40.28
Microsoft SQL Server Source - 0.4.27
Snowflake Destination - 0.4.42

**Comment by narenkadiri** [comment]
I just overlooked reset all option. My issue got resolved. thanks team.

**Comment by sajarin** [comment]
Happy you were able to get this resolved @narenkadiri!
