### ISSUE TITLE
How to change sidecar CPU requests

### ISSUE THREAD

**Issue by hakuno** [airbytehq/airbyte#21653]
I can't find a way to set CPU requests.

I can change the pod's main container. But I can't change the sidecar containers.

The sidecar containers have 100m of CPU request. How can I change that?

It's about the connection pods like Source-* and Destination-*.

Please, can any one help me out?

### more info

The source and destination connections pods are requiring more than 400m of CPU per pod. Because it sums the containers requests inside. So my Kubernetes cluster is scaling nodes based on CPUs in an expensive way.

**Comment by hakuno** [comment]
Does It have some constants like these?
```
  private static final String DEFAULT_CPU_REQUEST = "0.1";
  private static final String DEFAULT_CPU_LIMIT = "0.2";
```
https://github.com/airbytehq/airbyte/pull/10759/files#diff-be3c5f5544310ca55f284848493a7afe72533bd82a737a044d3f58e9c82d71abR105-R106

If so, how to override?

**Comment by hakuno** [comment]
I found that.

```
SIDECAR_KUBE_CPU_LIMIT
SIDECAR_KUBE_CPU_REQUEST
SIDECAR_MEMORY_REQUEST
SIDECAR_KUBE_MEMORY_LIMIT
```

**Comment by fabianofpena** [comment]
@hakuno have you found a solution?

I added these variables in the env-configmap.yaml:

```
  SOCAT_KUBE_CPU_REQUEST: "0.2"
  SOCAT_KUBE_CPU_LIMIT: "0.5"
  SIDECAR_KUBE_CPU_REQUEST: "0.2"
  SIDECAR_KUBE_CPU_LIMIT: "0.5"
  DEFAULT_SIDECAR_KUBE_CPU_REQUEST: "0.2"
  DEFAULT_SIDECAR_KUBE_CPU_LIMIT: "1.5"  

```
but relay-stderr is still setting cpu limits to 2:

```
  relay-stderr:
    Container ID:  containerd://b0e48687c4b39138c0f308ae771ef34f52434c6ec798f3b78990fceb934e0863
    Image:         621936395696.dkr.ecr.us-east-1.amazonaws.com/airbyte-socat:1.7.4.3-r0
    Image ID:      621936395696.dkr.ecr.us-east-1.amazonaws.com/airbyte-socat@sha256:d04e9f8a2b858e655e5568142267a34ee31a6cca9ecf3748f9ae2c07da41e4f0
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      cat /pipes/stderr | socat -d -d -t 60 - TCP:10.9.2.173:9029
    State:          Running
      Started:      Wed, 22 Nov 2023 18:01:42 -0300
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  50Mi
    Requests:
      cpu:        250m
      memory:     25Mi

```

**Comment by hakuno** [comment]
@fabianofpena If you use Helm Chart to deploy into Kubernetes, so you should look for the right values like `global.jobs.resources.limits` and `global.jobs.resources.requests`.

But some time ago the Airbyte had some bug to apply these resource settings. Please, check it out if they fixed it.

Ps. I no longer play with Airbyte.
