### ISSUE TITLE
Bug with S3 Path Patterns.  Redirect link is broken

### ISSUE THREAD

**Issue by ryjabe** [airbytehq/airbyte#21665]
### Tell us about the documentation you'd like us to add or update.
This issue is for the S3 docs.  The "path patterns" link appears to append a variable to the URL and redirect you. This works while in the "docs" pages, but not when you click it while configuring a new source.
Example of bad path (from cloud source): https://cloud.airbyte.io/workspaces/2d579cd3-813d-45fb-bbd0-79e20e048f49/source/s3.md#path-patterns
Example of good path (from docs): https://docs.airbyte.com/integrations/sources/s3/#path-patterns

### If applicable, add links to the relevant docs that should be updated
[- [Link to relevant docs page](https://docs.airbyte.io)
](https://docs.airbyte.com/integrations/sources/s3)
![image](https://user-images.githubusercontent.com/9613935/213762621-2f628fcb-ed15-4b27-bc52-8173065d8523.png)

**Comment by timroes** [comment]
I thought we actually had code in place that made sure that `#fragment-only` links are when loaded in the product be forwarded to the full doc in a new tab to the appropriate place, but it seems to not exist (anymore?). @flash1293 @lmossman Could you maybe have a look at that in your next sprint?

**Comment by flash1293** [comment]
Not immediately aware of changes, but we can take a look for sure!

**Comment by girarda** [comment]
Closing because I can't reproduce. This is an old issue so the bug might have been fixed since. Feel free to re-open if this is still a problem.
