### ISSUE TITLE
New Integration Request: Coda.io tables

### ISSUE THREAD

**Issue by jim-barlow** [airbytehq/airbyte#2167]
## Tell us about the new integration you’d like to have
[Coda](https://coda.io/) is a pretty awesome tool which we have used for a number of things, but has always been limited for our use-cases as we couldn't get data out (and into BigQuery, in our case) in a non-hacky way. 

## Describe the context around this new integration
IMHO the only data you actually want out of Coda is anything stored in tables, and they provide a pretty clean API and awesome documentation [here](https://coda.io/developers/apis/v1).  We use it for multiple things but the structured data is in the tables.

## Describe the alternative you are considering or using
I spent an hour testing it this morning and I will probably spin something up pretty quickly as a Cloud Function which would stream JSON into BQ upon invocation (probably on a schedule, or maybe via HTTP request from a button in Coda)  - I'd then deal with JSON decoding and deduplication downstream in BigQuery.  However since it seems like such a simple API to interact with (i.e. no real need for a client library in this instance, and only ), I'd be keen on using this as a learning case for one of my guys to build an Airbyte connector.

Let me know what you think, my python code is below (no pagination as the test tables are small).  You get the API key `coda_token` from your admin dashboard, simples.

```
import requests

# get this from coda account settings at https://coda.io/account
coda_token = "YOUR_API_KEY"

# get owned docs
headers = {'Authorization': f'Bearer {coda_token}'}
docs_uri = 'https://coda.io/apis/v1/docs'
docs_params = {'isOwner': True}
docs_response = requests.get(docs_uri, headers=headers, params=docs_params).json()

# get doc_ids
for doc in docs_response['items']:
    doc_id = doc['id']
    tables_uri = f'https://coda.io/apis/v1/docs/{doc_id}/tables'
    tables_response = requests.get(tables_uri, headers=headers).json()
    
    # get table_ids in docs and get rows 
    for table in tables_response['items']:
        table_id = table['id']

        rows_params = {'useColumnNames': 'true' , 'valueFormat': 'simpleWithArrays'} 
        rows_uri = f'https://coda.io/apis/v1/docs/{doc_id}/tables/{table_id}/rows'
        rows_response = requests.get(rows_uri, headers=headers, params=rows_params).json()

        print(rows_response)




```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368091383079) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thank @jimbeepbeep! I love their tag line :)

Adding it to our list of connectors to build.

Out of curiosity in what context do you need coda's data replicated?

**Comment by jimbeepbeep** [comment]
All good, let me know when you need some input.  We're actually using Coda as a simple way of maintaining master data (with one-to-many connections very straightforward), as well as planning out (and in the process, documenting) sets of cloud resources for various data augmentation functions.  Syncing to BigQuery then enables us to access the metadata about these connections/dependencies and supports automated monitoring.

**Comment by sherifnada** [comment]
@jimbeepbeep thanks for creating this issue! you mentioned you'd be interested in having someone from your team build it. What can we do to help?

**Comment by jimbeepbeep** [comment]
Great stuff, @sherifnada can you add @joseignaciorm to this issue please (I don't have permissions) as he'll be working on this from our side.

**Comment by sherifnada** [comment]
@joseignaciorm hello! 

To get started, take a look at our [documentation on developing connectors](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector). 

The "golden path" for writing connectors is Python or Java, but Airbyte supports any language. See our [Python connector tutorial](https://docs.airbyte.io/tutorials/building-a-python-source) for a walkthrough of writing a connector.

Once you've taken a look, please let me know if you have any questions or feedback. I'm happy to setup a call to support however I can.

**Comment by joseignaciorm** [comment]
I really thank you @sherifnada for the support. I have been following the "Building a Toy Connector" days before but I haven't finished it yet. It has help me a lot for context. Anyway, I'm already following your recommendations above and I'll be writing to you later for any question or am getting stuck.

**Comment by sherifnada** [comment]
great! Talk soon.

**Comment by joseignaciorm** [comment]
I will be away on parental leave. So we'll talk when I'm back. Regards.

**Comment by sherifnada** [comment]
@joseignaciorm congrats! 👶🏼 👶🏼  enjoy your leave

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/18675
