### ISSUE TITLE
GA4 docs: Add note that email of the service account needs to be added on the account level

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#21670]
### Tell us about the documentation you'd like us to add or update.
A user [reported an issue](https://discuss.airbyte.io/t/ga4-connector-connection-test-fails/3439) with the GA4 docs:
> The error message I receive is:
> ‘403 Client Error: Forbidden for url: https://analyticsdata.googleapis.com/v1beta/properties/xxxxxxxxx/metadata’
> 
> I am using a json service account to connect to the service.
> I gave viewer permission to the email of the service account (Property level not account level).

Solve:
>The email of the service account needs to be added on the account level. When it’s added on the property level it doesn’t work.

### If applicable, add links to the relevant docs that should be updated
- https://docs.airbyte.com/integrations/sources/google-analytics-v4/

**Comment by juweins** [comment]
Hey there, I would like to address this issue. I need some time to figure out the adjustments that have to be made.

**Comment by marcosmarxm** [comment]
Closed by #22416
