### ISSUE TITLE
pod-sweeper not cleaning completed job pods in 0.40.28

### ISSUE THREAD

**Issue by alexopenline** [airbytehq/airbyte#21689]
## Environment
- **Airbyte version**:  example is 0.40.28
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
worker pods are not removed from kubernetes after completion of failure

## Expected Behavior
worker pods to be removed after finished

## Logs
NA

## Steps to Reproduce
1. Deploy airbyte 0.40.28 to k8s with stable-with-resource-limits kustomization
2. Run sync
3. Check completed pods removed after 2 hours

## Root cause
In pod-sweeper.yaml check is done for pods with label `airbyte=worker-pod` while in revision 54c0ef12b1acc59348480e86a4f080206a833ca7 label was updated as following:
`static final String WORKER_POD_LABEL_VALUE = "job-pod";`
one of the 2 to be updated.

**Comment by davinchia** [comment]
This might be a regression for that version. This is fixed in the current version so please upgrade and try again.
