### ISSUE TITLE
Remove Sentry from webapp

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#21700]
We currently rely mostly on datadog for any insights and error tracking. We can remove our Sentry integration from the code. This should likely be done after https://github.com/airbytehq/airbyte/pull/21456 is merged, so we're not running into too many conflicts around the config properties.

cc @josephkmh

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- We need to clean up bits of config
- Also remove the actual code from the webapp
- https://github.com/airbytehq/airbyte/pull/21456 is merged so this is unblocked
