### ISSUE TITLE
New connection - stream sync multi-select toggle not working

### ISSUE THREAD

**Issue by rpmcoding** [airbytehq/airbyte#21718]
## Environment
- **Airbyte version**:  v0.40.28
- **OS Version / Instance**: Ubunti 20.04 / Digitalocean
- **Deployment**: Docker
- **Source Connector and version**: MySQL 1.0.19
- **Destination Connector and version**: BigQuery 1.2.11
- **Step where error happened**: Setup new connection

## Current Behavior

at ***/connections/new-connection

Under the Activate the streams you want to sync heading you have a table of your datasource tables.

1) select all rows using the checkbox
2) click on the toggle in the heading of the table - nothing happens

## Expected Behavior

Expecting the toggle in the table header to change on ALL selected rows of the table.

## Logs
n/a

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/59533498/214099909-7ae66559-879f-48c9-b3e0-8133b1e551a5.png)

## Are you willing to submit a PR?

sorry, no

**Comment by natalyjazzviolin** [comment]
Hey @rpmcoding , this is not a bug, just bad UX. The toggle works:

https://user-images.githubusercontent.com/65251165/214373587-bc1aed0a-866f-4459-9bfd-6816185673e0.mov


We're working on refactoring that whole component, I don't have the correct issue to link right now, but it's in the works!
