### ISSUE TITLE
Source S3: Add zip file compression support

### ISSUE THREAD

**Issue by d-miranda** [airbytehq/airbyte#21716]
## Tell us about the problem you're trying to solve
S3 source does not support reading files inside zip folders. 

## Describe the solution you’d like
Add support to read files inside zip folders.

## Are you willing to submit a PR?
Yes. PR soon.

**Comment by marcosmarxm** [comment]
Thanks for the request @d-miranda let me know if you need any assistance here.

**Comment by YowanR** [comment]
@d-miranda We would love to see this contribution from you! Please let us know if you need any help! 🙏

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
