### ISSUE TITLE
 Change BE/FE interface for syncs to only have an async call

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2171]
Initial creations of syncs shouldn't respond with a `OutputAndStatus`. The sync should be created and then have the regular job loading system view the status of the sync.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150210621) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Do we actually need any changes to the API? Can't it just continue to return a JobInfo that has status pending or whatever?

**Comment by jrhizor** [comment]
That `JobInfo` won't have an id yet if the workflow run is only scheduled in the future. 

- Scheduled Workflow (available at creation of sync)
   - Workflow run (Job)
      - Attempt (Attempt)

**Comment by cgardens** [comment]
So what will we return when work is submitted? It seems odd that I can submit work to a work queue and not be given back some sort of handle to look up that work later.

**Comment by cgardens** [comment]
closed by https://github.com/airbytehq/airbyte/issues/2244

**Comment by cgardens** [comment]
this was done.
