### ISSUE TITLE
Write StandardSyncSummary and State from sync jobs into a persistence

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2172]
`StandardSyncSummary` and `State` should be written via a persistence object to the DB at the end of the job instead of being stored as part of the job output.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150084310) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
this was done. https://github.com/airbytehq/airbyte/pull/7219
