### ISSUE TITLE
QA Engine: retrieve connector build status

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#21720]
## Tell us about the problem you're trying to solve
Depends on https://github.com/airbytehq/airbyte/issues/20442
We want to know per connector and version if their latest build is successful.

## Describe the solution you’d like
We can parse the HTML results from `https://dnsgjos7lj2fu.cloudfront.net/tests/summary/{connector_technical_name}/index.html`
 
Sample from the spike (not per version):
```python
def latest_build_is_successful(status_page_url) -> bool:
    # TODO how to make sure the latest build matches the OSS catalog connector version?
    # Parse raw logs from S3?
    response = requests.get(status_page_url)
    if response.status_code != 200:
        return False
    page = response.text

    history = []
    for row in re.findall(r"<tr>(.*?)</tr>", page):
        cols = re.findall(r"<td>(.*?)</td>", row)
        if not cols or len(cols) != 3:
            continue
        history.append(
            {
                "date": cols[0],
                "status": re.findall(r" (\S+)</span>", cols[1])[0],
                "link": re.findall(r'href="(.*?)"', cols[2])[0],
            }
        )
    return history[0]["status"] == "success"
```

## Describe the alternative you’ve considered or used
Build reports are also stored on S3. It can give us access to the rawest data that could help define for which connector version the build was run.

**Comment by evantahler** [comment]
Grooming:

Ideas: 
* Also build a `https://dnsgjos7lj2fu.cloudfront.net/tests/summary/{connector_technical_name}/{version}/index.html` in addition to `https://dnsgjos7lj2fu.cloudfront.net/tests/summary/{connector_technical_name}/index.html`
  * Tweak the build script to upload the summary file to upload the HTML 2x - once for 'latest' and once for 'version'.

**Comment by evantahler** [comment]
Hey @bechurch I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by evantahler** [comment]
cc @bechurch this will be your first story!

**Comment by alafanechere** [comment]
@bechurch https://github.com/airbytehq/airbyte/pull/21776/files bootstraps the QA engine logic. Feel free to review :) I think this additional check will likely be added to the `validations` module.
