### ISSUE TITLE
PostgreSQL source should stop supporting the legacy state format

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#21738]
## What

PostgreSQL source supports both legacy states and per stream states. This support temporarily added to support the transition of legacy states to per stream states for syncs.
This support comes with a performance cost that could be addressed by modifying how we handle the transition.

More context on [slack](https://airbytehq-team.slack.com/archives/C048E3BK1KM/p1673978611140589)

## Describe the solution you’d like

* Remove the implicit support of legacy states in the PostgreSQL source, if the connector sees a legacy state, it means that the platform is running an older version, fail with a clear message telling users to upgrade the platform to version > X if they wish to be able to use the newer version of this connector. Otherwise, downgrading the connector should remain a viable option.
* We should have some documentation about this upgrade process, the error described above could refer to it.
* This change should be highlighted to the community

**Comment by cgardens** [comment]
We should figure out what the error message that will happen if the source is upgraded and the platform is not and make sure we put that in discourse and have CAT signal amplify it.

**Comment by subodh1810** [comment]
Rough draft PR https://github.com/airbytehq/airbyte/pull/21691 (needs work to be done)

**Comment by subodh1810** [comment]
This is blocked by https://github.com/airbytehq/airbyte/issues/22945 and https://github.com/airbytehq/airbyte/issues/22946
cc @bleonard 

Slack thread : https://airbytehq-team.slack.com/archives/C048E3BK1KM/p1675767418825829?thread_ts=1673978611.140589&cid=C048E3BK1KM
