### ISSUE TITLE
Attempts should run on the same input

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2173]
Right now there is no guarantee that between attempts Airbyte (or connectors) do not modify the working directories used for the sync or that the versions of the connectors/Airbyte are the same. 

Ideally, only the exact same inputs are used for every attempt at running a job. This change will be more ergonomic once we have cancellation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368215263877) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
this was fixed.
