### ISSUE TITLE
[SAT]  ignored_fields key for basic read test

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#21737]
Sometimes sources change data in records for each read, like a `last_refresh_time ` column.

See https://github.com/airbytehq/airbyte/pull/21419, https://github.com/airbytehq/airbyte/pull/21593 and https://github.com/airbytehq/airbyte/pull/21775 for examples

**Comment by erohmensing** [comment]
Grooming - 
This is supported for [Test full refresh sync](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference/#test-full-refresh-sync) - we think we want it for all tests (not just adding it to basic read test)? Is it only necessary for tests with expected records? It's a bit confusing what the support for `ignored_fields` in test full refresh sync is for

**Comment by alafanechere** [comment]
>  It's a bit confusing what the support for ignored_fields in test full refresh sync is for

You are right, I think we could either merge full_refresh test into basic read (or the opposite). In any case, `ignored_fields` for full refresh and `ignored_fields` for basic read should serve the same purpose and can be the same pydantic model field. I think we shall add a `bypass_reason` to explain why we're ignoring this field.

**Comment by erohmensing** [comment]
> I think we shall add a bypass_reason to explain why we're ignoring this field.

+1
