### ISSUE TITLE
BigQuery normalization fails with reserved column name

### ISSUE THREAD

**Issue by ridem** [airbytehq/airbyte#2174]
I tried to replicate a Postgres source into BigQuery. Replication failed on two of my tables that had a column named `current`.
Similar: #1692

## Expected Behavior
Replication from Postgres to BigQuery is expected to work when a column is named `current`.

## Current Behavior
Replication fails. Here's the relevant part of the error log.
```
INFO (/tmp/...) LineGobbler(voidCall):69 - [31mCompleted with 2 errors and 0 warnings:[0m
INFO (/tmp/...) LineGobbler(voidCall):69 - 
INFO (/tmp/...) LineGobbler(voidCall):69 - [33mDatabase Error in model ab2_public_TableOne (models/generated/airbyte_views/_airbyte_my_dataset/ab2_public_TableOne.sql)[0m
INFO (/tmp/...) LineGobbler(voidCall):69 -   Syntax error: Unexpected keyword CURRENT at [34:10]
INFO (/tmp/...) LineGobbler(voidCall):69 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_views/_airbyte_my_dataset/ab2_public_TableOne.sql
INFO (/tmp/...) LineGobbler(voidCall):69 - 
INFO (/tmp/...) LineGobbler(voidCall):69 - [33mDatabase Error in model ab2_public_TableTwo (models/generated/airbyte_views/_airbyte_my_dataset/ab2_public_TableTwo.sql)[0m
INFO (/tmp/...) LineGobbler(voidCall):69 -   Syntax error: Unexpected keyword CURRENT at [31:10]
INFO (/tmp/...) LineGobbler(voidCall):69 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_views/_airbyte_my_dataset/ab2_public_TableTwo.sql
INFO (/tmp/...) LineGobbler(voidCall):69 - 
INFO (/tmp/...) LineGobbler(voidCall):69 - Done. PASS=30 WARN=0 ERROR=2 SKIP=4 TOTAL=36
DEBUG (/tmp/...) DefaultNormalizationRunner(close):97 - Closing tap process
ERROR (/tmp/...) DefaultSyncWorker(run):117 - Normalization Failed.
```

## Steps to Reproduce
1. Set up a Postgres table with a column named `current`
2. Start syncing that source into a BigQuery destination with normalization on.

## Severity of the bug for you
High: can't replicate tables that have columns with this reserved keyword

## Airbyte Version
`0.14.4-alpha`

## Additional context
- Postgres -> BigQuery

**Comment by ChristopheDuong** [comment]
Could you try again with the latest version?

Normalization went through quite some refactoring recently and I see from your logs that it is not that newest version.

Since "current" is part of the special keywords of normalization for BigQuery, this should be properly quoted so If you could confirm this is still happening with Airbyte version 0.15.0-alpha, that would be great.

Thanks

**Comment by ridem** [comment]
Thanks for your response! After upgrading, I confirm that this issue isn't present anymore in `0.15.0-alpha`.
