### ISSUE TITLE
Display error stacktrace

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#21750]
Follow up issue on https://github.com/airbytehq/airbyte/issues/21627

## What
When the connector builder returns an error, the UI shows the error message, but it does not show the stacktrace.

Showing the stacktrace will provide more context on the error and will help the connector developers troubleshoot issues with their manifest. 

Note that we used to show the stacktrace with the error message, but the resulting message was overwhelming.
<img width="1627" alt="Screen Shot 2023-01-13 at 5 27 16 PM" src="https://user-images.githubusercontent.com/1451943/212444810-26febc57-f664-4d33-bad0-fa7bd1500f52.png">

We should find a better way to show additional error information when needed

**Comment by Upmitt** [comment]
first researches: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3538%3A124449&node-id=3812%3A130388&viewport=1582%2C62%2C0.5&scaling=min-zoom&starting-point-node-id=3812%3A130388&show-proto-sidebar=1 - preference for flow 002 (selection of the flow in the left column)

**Comment by Upmitt** [comment]
new iteration of the flow 002 : https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3538%3A124449&node-id=3812%3A130388&viewport=734%2C315%2C0.28&scaling=min-zoom&starting-point-node-id=3812%3A130388&show-proto-sidebar=1

**Comment by lmossman** [comment]
The server is already returning the stack trace in the `exceptionStack` field, whereas we are only showing the `message` field. So this should be fairly straightforward to extract from the server response:
```
{
    "exceptionStack": "Traceback (most recent call last):\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py\", line 163, in _validate_source\n    validate(self._source_config, declarative_component_schema)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/jsonschema/validators.py\", line 934, in validate\n    raise error\njsonschema.exceptions.ValidationError: 'DeclarativeStrea' is not one of ['DeclarativeStream']\n\nFailed validating 'enum' in schema['properties']['streams']['items']['properties']['type']:\n    {'enum': ['DeclarativeStream'], 'type': 'string'}\n\nOn instance['streams'][0]['type']:\n    'DeclarativeStrea'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/main.py\", line 74, in <module>\n    print(handle_request(sys.argv[1:]))\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/main.py\", line 68, in handle_request\n    source = create_source(config, limits)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/connector_builder_handler.py\", line 47, in create_source\n    return ManifestDeclarativeSource(\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py\", line 67, in __init__\n    self._validate_source()\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py\", line 165, in _validate_source\n    raise ValidationError(\"Validation against json schema defined in declarative_component_schema.yaml schema failed\") from e\njsonschema.exceptions.ValidationError: Validation against json schema defined in declarative_component_schema.yaml schema failed\n",
    "exceptionClassName": "io.airbyte.protocol.models.AirbyteTraceMessage",
    "message": "Error handling request: Validation against json schema defined in declarative_component_schema.yaml schema failed"
}
```

**Comment by ambirdsall** [comment]
This is slightly more involved than it seems on the surface: 
1) on parsing/resolution errors, the connector builder server responds with an http error status
2) errors are caught and used to populate a`CommonRequestError` object which gets re-thrown
3) `CommonRequestError` discards the http payload and the `exceptionStack` with it

I don't think there's any reason not to include the response payload as a property of `CommonRequestError`, though, so the way forward is clear at least.
