### ISSUE TITLE
Source TikTok Marketing: Need new sandbox account 

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#21752]
Old test account has PII data. Need create new with fake test data.

**Comment by igrankova** [comment]
@YowanR, as we agreed, we consider the connected Google ads that Yurii created to fill this account with test data as fake (sample) data. We can continue using this account for the testing purposes.
cc @lazebnyi, @ycherniaiev

**Comment by igrankova** [comment]
LastPass name: tiktok ad account
