### ISSUE TITLE
Enable Amazon Seller Partner on cloud 

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#21755]

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Amazon Seller Partner : Enable on Cloud](https://app.harvestr.io/components/0/list/Fnk-yzOBb)

**Comment by TBernstein4** [comment]
@lazebnyi I had a customer ask when this will be ready on Cloud, do you have an ETA?

**Comment by lazebnyi** [comment]
@TBernstein4 Unfortunately we block on public account for OAuth and we wait when Amazon approve our request.

**Comment by TBernstein4** [comment]
I see, thank you for the update.

**Comment by nataliekwong** [comment]
@roman-yermilov-gl I believe this issue can now be closed as the PR has been merged to enable Amazon Seller Partner on Cloud.
