### ISSUE TITLE
improving logging interface for workers

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2175]
1. Separate the logging interface for workers to have a stored mapping of job id to log output path instead of handling MDCs in different locations on the fly.
1. Ensure all the logic for constructing and running a worker is captured. The construction of integration launchers, for example, should be contained in the worker's log file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150274991) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
not sure I understand #1. Just want to make sure we don't go in the direction of not using a normal logger.

**Comment by jrhizor** [comment]
This isn't changing the use of `Logger` to anything else. It's about changing what is between setting the MDC and clearing the MDC.

**Comment by cgardens** [comment]
closed as stale
