### ISSUE TITLE
use exceptions for job error reporting and outputs for the actual job output

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2176]
Change interface for reporting errors and logs for spec/check/discover.

Exceptions should propagate log locations + readable short messages for the UI instead of wrapper responses.

The internal code will have fewer try/catches (currently it’s very difficult to understand the “correct” level at which to throw/rethrow. This would also make it easier to have more reasonable defaults for error messages. 

The exception read-side code will be much simpler if it doesn't have to interpret job output objects.

Refactor `DefaultSchedulerJobClient` to exclude `Job` object-level details for synchronous jobs and to only interface in terms of job ids (not `Job` objects)

**Comment by cgardens** [comment]
🧠 💣 ❗

**Comment by cgardens** [comment]
PR is up. But probably going to wait on merging as I think we have a more direct way to getting to running on temporal. https://github.com/airbytehq/airbyte/issues/2177

**Comment by cgardens** [comment]
Planning to get this out in the next couple days. No work happened on it last week as I was focused on other parts of the temporal migration. I think we are in a good place to move forward with this now.
