### ISSUE TITLE
Add selected field count to new streams table

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#21772]
The number of selected fields in each stream should be displayed in a new column on the streams table:

![Screenshot 2023-01-24 at 9 40 22 AM](https://user-images.githubusercontent.com/7550957/214246534-d629abc5-7a1e-4c39-8915-800afb2c43ef.png)

Figma designs :https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=972%3A36212&scaling=min-zoom&page-id=972%3A36208&starting-point-node-id=972%3A36212&show-proto-sidebar=1

The rest of the selection UI is being added in this PR: https://github.com/airbytehq/airbyte/pull/21058

**Comment by edmundito** [comment]
@dizel852 assigned this to you. You can work with @josephkmh to understand how column counts work. There is already some placeholder code in the table that can be uncommented as a starting point.

**Comment by dizel852** [comment]
Will leave some questions here:
1. Is it a Pill button component? I see the same style as the Sync Mode dropdown has
<img width="481" alt="image" src="https://user-images.githubusercontent.com/20929344/221642896-1575b41f-805b-4c35-9e52-c4e03810c5c5.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/20929344/221643075-c18aeab6-cdc2-42e3-a622-ea6405c2894f.png">

2. Does the counter should have the same styles as Sync Mode dropdown has for cases - changed(light blue background), removed(light blue background) 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/20929344/221643666-4a679e65-602b-4d1f-8903-fa074ec013cb.png">

4. If all fields are selected, do we need to show a counter like "10/10"?
<img width="250" alt="image" src="https://user-images.githubusercontent.com/20929344/221643974-a89a2ecc-b6cf-460d-ae4c-fba1da849c62.png">

**Comment by dizel852** [comment]
Seems like I've found the answers 😅 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/20929344/221988596-9140dc58-405f-4e53-b68d-4a5e62ee474c.png">
