### ISSUE TITLE
Source Braze: additional endpoints

### ISSUE THREAD

**Issue by ni-aschuler** [airbytehq/airbyte#21774]
## Tell us about the problem you're trying to solve
Thanks a lot for this connector, highly appreciated. We would make a good use of additional endpoints available in the Braze API 

## Describe the solution you’d like
Especially the details endpoints, such as:
- https://www.braze.com/docs/api/endpoints/export/canvas/get_canvas_details/
- https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaign_details/
- https://www.braze.com/docs/api/endpoints/export/segments/get_segment_details/

## Describe the alternative you’ve considered or used
Without this Airbyte integration we currently have to fetch the list of ids from the lists endpoints (such as https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/) and then loop through each results and retrieve each details one by one with a python operator in Airflow. 
This Airbyte connector would really simplify our Braze pipeline. 

## Additional context
Let me know if clarification is needed.

## Are you willing to submit a PR?
I would be happy to contribute with some guidance or exemples where similar thing has been done with other sources :)

**Comment by topefolorunso** [comment]
I will work on this issue next. Please assign to me @justinbchau

**Comment by TejaswiKarasani** [comment]
> I will work on this issue next. Please assign to me @justinbchau

I'm still working on it and I want to complete this by this weekend
