### ISSUE TITLE
Move scheduling (i.e. getNextJob) logic outside of JobPersistence

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2178]
* Try to isolate with other scheduling-specific logic
* This is temporary. Ultimately the scheduler will have no `getNextJob` or equivalent.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150317303) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
not relevant anymore.
