### ISSUE TITLE
Refactor JobSubmitter/JobCreator/JobPersistence interface

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2179]
* It’s fine for the `JobPersistence` to be used to update the state of the jobs, but allowing other entities that aren’t limited to just within the actual job runs makes it incredibly difficult to have an external framework manage the state of the job runs automatically.
* The goal of this step is to only allow job-internal code to modify state in `JobPersistence` with the exception of the `JobRetrier`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150381939) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
not relevant anymore with scheduler 2 project
