### ISSUE TITLE
make timestamps available in saved worker logs

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#218]
Current singer tap/target logs do not include timestamps in the UI. This would be useful for someone trying to debug exact issues in the UI logs.

**Comment by cgardens** [comment]
I think this is done. If not, re open and put in v0.2.0 milestone.

**Comment by jrhizor** [comment]
Reopening and updating so it's more clear.

**Comment by jrhizor** [comment]
This is working now, not sure when it was introduced. Log files are written by `Airbyte` with the correct timing prefix.
