### ISSUE TITLE
Source Jira: Issue with Board stream and dependent streams

### ISSUE THREAD

**Issue by anamargaridarl** [airbytehq/airbyte#21802]
## Environment

- **Airbyte version**:  0.40.27
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: Jira 0.3.2
- **Step where error happened**: Sync job

## Current Behavior
Data fetch fails trying to access an unexisting field

## Expected Behavior

Read data from the board stream as well as all dependent on it

## Steps to Reproduce
1. Activate Board/BoardIssues/Sprints... stream
2. Sync job

## Are you willing to submit a PR?

Yes

**Comment by anamargaridarl** [comment]
Contribution: https://github.com/airbytehq/airbyte/pull/21524

Having issues with this PR action

**Comment by marcosmarxm** [comment]
Sorry the delay Ana, left some comments there.

**Comment by anamargaridarl** [comment]
Thanks! @marcosmarxm

**Comment by artem1205** [comment]
@anamargaridarl, can we close this issue ?

**Comment by artem1205** [comment]
closing this issue due to no response.
