### ISSUE TITLE
Create a visualization of how Postgres connector works

### ISSUE THREAD

**Issue by bleonard** [airbytehq/airbyte#21808]
In preparation to do some refactoring, it would be good to have an artifact to help understand the key decision points and layers of whats happening.

My main guess to what would be helpful is to list out the "streaming" approach. We are passing around these iterators. Let's call them out for each step in the "pipeline" and what they do.

It can be a picture (Whimsical) or a simplified pseudo-code or whatever you think is best.

Mostly talking about the `read` method.
Branch or make separate artifacts as needed for CDC/Standard or Incremental/Full Refresh.

**Comment by akashkulk** [comment]
First draft : https://docs.google.com/document/d/1yIsPLqjdhES_HHzIeJ3jI5d4R47vdNL8_d-yQ20vMgg/edit
