### ISSUE TITLE
Create modular standard test suite v2 scaffolding

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2180]
## Tell us about the problem you're trying to solve
Per the [tech spec](https://docs.google.com/document/d/1pFLR8eLP5VOj6vDtWe69KZL0aWWHEA6Vkbod6NYJon4/edit#), create the scaffolding for a modular standard test suite. It should take as input a configuration on which tests should run and run the appropriate tests.

**Comment by sherifnada** [comment]
This is WIP -- expect to put up a PR later today.

**Comment by sherifnada** [comment]
This was implemented in #2384 in Java, but we're going to close that PR and pivot to implement in Python for a few reasons: 

1. More accessible to the community 
2. (and therefore) enables more contributions

**Comment by keu** [comment]
Scoping:

- [ ] Implement python package with base class for testing (3h)
- [ ] Implement docker tools to parse connector output and save inputs/outputs of each run (2h)
- [ ] Implement configuration fixture that parse yaml and apply it to test context (2h)
- [ ] Implement skip fixture to select only specific tests (30m)

Total dev estimation 7-8h
