### ISSUE TITLE
Implement v2 test suites

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2181]
## Tell us about the problem you're trying to solve
As described in the [tech spec](https://docs.google.com/document/d/1pFLR8eLP5VOj6vDtWe69KZL0aWWHEA6Vkbod6NYJon4/edit#)

**Comment by keu** [comment]
Scoping:

- [ ] Implement core tests (2h)
- [ ] Implement full refresh tests (2h)
- [ ] Implement incremental tests (3h)

Total dev estimate: 7h
