### ISSUE TITLE
Standard Tests: Update docs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2182]
## Tell us about the problem you're trying to solve
It must be easily consumable by a contributor with 0 context on testing. 

Depends on all other tickets with the standard test suite label.

**Comment by keu** [comment]
dev estimation is 3-4h

**Comment by sherifnada** [comment]
relevant: 
https://github.com/airbytehq/airbyte/pull/2702#discussion_r607235922

**Comment by keu** [comment]
implemented in #2937
