### ISSUE TITLE
connector builder FE should consume a versioned artifact of declarative_component_schema.yaml

### ISSUE THREAD

**Issue by cpdeethree** [airbytehq/airbyte#21830]
## Tell us about the problem you're trying to solve
Currently the platform frontend build needs a file called declarative_component_schema.yaml to build. This lives in the connector sdk subfolder. This hard dependency should be updated to consume a pinned version of that schema instead.

## Describe the solution you’d like
A version of the file already gets published as part of the airbyte-cdk pypi package. We could simply update the frontend build to download a pinned version of that pypi package, extract the tar, and go grab the yaml file in the subfolder - rather than referencing the hardcoded file

## Describe the alternative you’ve considered or used
We also consider putting this file in the "shared" code that is shared between connectors and platform. However, this approach should be discouraged because we are in the middle of decoupling and removing as many hard dependencies as possible in shared code.

## Additional context
This was discovered as part of a larger effort of refactoring the split between airbyte platform and airbyte connectors. However, Alex G. noted it probably should be done under any circumstance because currently it's possible that the server can use a different version from the webapp.

**Comment by timroes** [comment]
Cc @flash1293 @lmossman for information

**Comment by flash1293** [comment]
Agree with the described solution! I took a quick look at this and it should be really simple to add the loading to the existing `generate-client` script in the webapp package.json loading it in a pre-determined location like this:
```
curl -L https://pypi.python.org/packages/source/a/airbyte-cdk/airbyte-cdk-${version}.tar.gz | tar -xzO airbyte-cdk-${version}/airbyte_cdk/sources/declarative/declarative_component_schema.yaml > build/lowcode_manifest.yaml
```

Ideally we also find a way to always keep this in sync with the version in the connector builder server: https://github.com/airbytehq/airbyte/blob/ca8cdc40aae629945e08d465871352235f5d53b5/airbyte-connector-builder-server/setup.py#L44

**Comment by flash1293** [comment]
Grooming note:
* Make sure this version is in sync with what the connector builder server does

**Comment by cpdeethree** [comment]
Thank you guys for the quick turnaround on this!
