### ISSUE TITLE
Add link to Harvestr Roadmap in the Resources menu

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#21841]
We should add a link to the public roadmap, found here: https://go.airbyte.com/roadmap

This will help with discoverability of the platform features and connectors planned to bring to Airbyte. 

The link should be linked from the "Resources" tab in the left-side bar
<img width="464" alt="Screenshot 2023-01-26 at 11 33 12 AM" src="https://user-images.githubusercontent.com/633226/214932383-8f3a92aa-72b9-487a-aaa8-0f3bec6b0194.png">

cc @andyjih

**Comment by andyjih** [comment]
@nataliekwong Actually, any reason we shouldn't link to the roadmap from OSS as well?

**Comment by nataliekwong** [comment]
Makes sense to add to OSS! Increases visibility for OSS releases and what we're working on for Cloud.

**Comment by nataliekwong** [comment]
Closing as we've now added the new webpage to Cloud
