### ISSUE TITLE
Standard Tests: store/display contexts on test failures

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2184]
## Tell us about the problem you're trying to solve
If a standard test fails, I want to know all the inputs that led to it failing, the outputs produced by the connector, and the logs.

**Comment by sherifnada** [comment]
Blocked on the outcome of #2180 - unassigning from myself and will be handled by the connectors team

**Comment by keu** [comment]
Dev estimation is 2h as the main part of it already a part of #2181
