### ISSUE TITLE
Standard Tests: allow specifying exact record matches

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2186]
## Tell us about the problem you're trying to solve
standard tests are currently smoke tests which don't allow verifying that exact records were produced. We want to have this functionality so we can write more robust tests.

**Comment by keu** [comment]
for this we should provide files with expected records,
test options are:

| Options  | Default Value | Meaning | Estimation |
| ------------- | -------|------ |----|
| `exact_order` | False  | Ensure that records produced in exact same order | 2h |
| `extra_fields` |  True | Allow records to have other fields | 1h |
| `extra_records` | True | Allow connector to produce extra records, but still enforce all records from the expected file to be produced | 1h |

by default test configured to be as much flexible as possible.

base implementation - 2h
Total dev estimation - 6+h

**Comment by keu** [comment]
some initial match was implemented in the first version of Standard Tests
