### ISSUE TITLE
Destination Databricks - Destination process message delivery failed

### ISSUE THREAD

**Issue by omerk-kaltura** [airbytehq/airbyte#21860]
Is this your first time deploying Airbyte?: Yes
OS Version / Instance: MacOS
Deployment: Docker
Airbyte Version: 0.40.28
Source name/version: ChargeBee/Tempo
Destination name/version: Databricks
Step: The issue is happening during sync
Description: Whenever I’m running the process after Reset it ‘Succeeded’ but when I run a ‘Sync now’ it fails. this is bizarre behavior. This happens for 2 different sources (ChargeBee/Tempo).
Attached is a screenshot and log file.
![62cd7ab59a70c08e9634031541179d625aefe91d](https://user-images.githubusercontent.com/69112500/214632445-b9a1f6c5-67c0-44a0-a1f4-60492a8b205a.png)

Adding logs as well - 
[b52b95b1_ab71_48ca_8af0_41ea026e26cf_logs_24_txt.txt](https://github.com/airbytehq/airbyte/files/10501753/b52b95b1_ab71_48ca_8af0_41ea026e26cf_logs_24_txt.txt)

**Comment by omerk-kaltura** [comment]
any updates here?

**Comment by evantahler** [comment]
Is this problem still occuring?

**Comment by philk1991** [comment]
This is still an issue for me. Seems to happen every time I add a new stream to an existing connector

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
