### ISSUE TITLE
Destination Snowflake: allow configuration of `data_retention_time_in_days` so we can set values greater than 0

### ISSUE THREAD

**Issue by abakula1** [airbytehq/airbyte#21879]
## Tell us about the problem you're trying to solve
Discussed in the Airbyte community slack server here: https://airbytehq.slack.com/archives/C021JANJ6TY/p1674512554893089

We have a handful of cases where we have just-in-time availability snapshots of data that we are storing in Snowflake using `Incremental - Append` and `Full Refresh - Append` load types to maintain history. Sometimes this data is highly important and we cannot accept the risk of losing the historical information. 

However, this data is currently at risk. Connections allow you to "Reset" the data via UI and API and there don't seem to be any restrictions on that (nor can you configure restrictions on this). We have concerns on our end that we will lose the history we have built up, causing permanent and unacceptable data loss.

One solution to this is to set up time travel in snowflake so that we can recover the data in the event of a random reset. We were hoping to do 1 or more days so that we have a recovery option in case of data loss. Additionally, time travel as you might imagine might be handy in other cases as well. Maybe a developer iterates on a custom connector and we have a dev error that writes faulty data that we need to rewind to a previous state.

In the thread it was suggested that Airbyte defaults to 0 days and disables time travel to reduce costs.
The data in our case is not very large. Meaning there is very little storage cost impact on our side. So the cost saving measure, while thoughtful, is far less important to us than having the potential for data recovery.

## Describe the solution you’d like
The snowflake destination connector allows configuration of the data_retention_time_in_days [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-snowflake/src/main/java/io/airbyte/integrations/destination/snowflake/SnowflakeSqlOperations.java#L33)

It can be as simple as enabling or disabling this snowflake table configuration (data_retention_time_in_days = 0) so that we enforce the settings set at the schema level. This can even be enabled by default to support backward compatibility. 

## Describe the alternative you’ve considered or used
Today we are using a manual script to iterate over every airbyte raw table across our schemas to set the retention_time to the value we need. This is not sustainable since we need to remember to do this for every airbyte raw table created. This is especially painful as we are ramping up our usage of Airbyte and migrating pipelines / creating new pipelines so we are adding multiple tables per week.

**Comment by marcosmarxm** [comment]
@airbytehq/jdbc-connectors please check this feature!

**Comment by guillaume-chech** [comment]
We're in the same situation as the one described by @abakula1 , we'd be really happy if this could be made real . 
Any update on the status of that @marcosmarxm ?

**Comment by edgao** [comment]
destination-snowflake 3.7.0 adds a config option for data retention time. It'll only affect any new tables, so you'll probably want to manually alter any existing tables. But if you e.g. add new streams to your connection, they'll be created with the appropriate retention time.
