### ISSUE TITLE
Connector builder: Allow format configuration for start/end time in dateslicer

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#21927]
A lot of existing manifests use different formats for the start and end time in the date slicer component. Right now this can't be configured in the UI (it will always inherit the format from the slicing component itself which enforces consistent formats used in the API response and the configuration which can be problematic). It's possible to work around this by doing date formatting within jinja templates, but this case is common enough to provide it as a top-level UI element.

<img width="957" alt="Screenshot 2023-02-02 at 10 58 08" src="https://user-images.githubusercontent.com/1508364/216293337-dd278b45-c661-47fc-8c8b-59c8f054cd87.png">

## Acceptance criteria

* It's possible to specify an optional format only for the end date / start date of the date stream slicer component which is different than the main format
* The default behavior is still the same as before
* Remove the default value for the Datetime Format field, as that will now be only the format used for API requests

**Comment by lmossman** [comment]
Technically speaking I think we can achieve this by always using the MinMaxDatetime component for start_ and end_datetime, which allows you to optionally specify a format. 

And in the UI, we can just have one optional format field under the start datetime input, and another under the end datetime input

**Comment by flash1293** [comment]
Hypothesis:
* The separate format for the start and end date is not something that's absolutely required, but it allows a connector developer to decouple the config format from the API format
* It's super rare (and almost never required) to have _different_ formats for start and end time
* Start date time is almost always a user input
* End date time is almost always "now", sometimes a user input

Suggestion:
* Make start date time a dropdown with two options: "user input" or "custom"
* Make end date time a dropdown with three options: "user input", "now" or "custom"
* If custom is selected, the start datetime can be defined using jinja macros like right now 
* If user input is selected, an implicit user input (like for auth) is added which is referenced using the jinja marco logic correctly under the hood (also taking into account format conversions, see below)
* Add an additional input "start/end date time format" which is optional (applied to both start and end time)

**Comment by flash1293** [comment]
Set start datetime's default to "user input" and end datetime to "now"

**Comment by flash1293** [comment]
@lmossman follow-up on this:

> Does the main datetime format also dictate how the date is injected?

Yes, it does, tested this like this:
<img width="1030" alt="Screenshot 2023-04-05 at 09 54 08" src="https://user-images.githubusercontent.com/1508364/230017154-95b545ef-5371-4eb2-997f-28706d4f8c1b.png">

As you can see the start date is specified in the German format, but what's sent to the API is subject to the slicer-level format with the XXX suffix.

**Based on this, adjusted suggestion:**

* Make start date time a dropdown with two options: "user input" or "custom"
* Make end date time a dropdown with three options: "user input", "now" or "custom"
* If custom is selected, the start datetime can be defined using jinja macros like right now
* If user input is selected, an implicit user input (like for auth) is added which is referenced using the jinja marco logic correctly under the hood (also taking into account format conversions, see below)
* No matter the configuration, the format for start and enddate is hardcoded to `%Y-%m-%d %H:%M:%S.%f+00:00` **and can't be changed in the UI**
  * Alternative: If this is too harsh, we could allow another optional date format input if the user picks "custom" for start datetime
* The implicit user input is setting `format: date` so in the connector form a datetime picker is rendered which makes it very easy for a user to select such a value

**Comment by lmossman** [comment]
@flash1293 got it, thanks for testing that out and writing it up here.

I agree with all of your points above. Since the only thing that affects what is sent to/received from the API is the slicer-level `datetime_format`, and the start/end-level formats only affect the connector user inputs, then I think being very opinionated here about the format of the datetime so that it matches the format that the Datepicker component generates makes sense.

**Comment by girarda** [comment]
+1 to @flash1293 's solution

I like the pattern of
1. Being more opinionated around formats for anything that we control
2. Providing reasonable defaults and hiding the more advanced features behind a "custom" option

**Comment by lmossman** [comment]
Another idea here: I added a datetime_format suggestions dropdown in https://github.com/airbytehq/airbyte-platform-internal/pull/5625 - it would be nice to implement logic that auto-set the cursor_granularity value to the one that corresponds to the datetime_format value whenever the user chooses an option from that suggestion list, so that they don't have to enter it manually.

If they enter a custom value, we don't need to do this since it is high-effort to implement a general solution for calculating the granularity from the datetime_format. But for selecting the suggested values, this should be a simple 1 to 1 mapping.

**Comment by flash1293** [comment]
Sounds like a good idea @lmossman 👍
