### ISSUE TITLE
Show logs in the UI if a connection check fails

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2192]
## Tell us about the problem you're trying to solve
If a check connection operation fails, I'd like to have access to the full logs and not just the message field that is returned from the `check` operation response.

**Comment by cgardens** [comment]
@sherifnada can you screenshot what you're talking about? I thought this had been addressed already.

**Comment by sherifnada** [comment]
@cgardens you're right, this already exists. I must have missed it. Closing.
