### ISSUE TITLE
Low-Code Beta CDK in Connector Builder UI

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#21926]
## Tell us about the problem you're trying to solve
We are working on bringing the Low-Code CDK to beta. Since the Connector Builder heavily depends on this lib and would be block from further CDK changes if we do nothing, it should be updated as part of the initiative. 

## Describe the solution you’d like
Here are the issues that have been worked on. Some are already part of the `low_code_cdk_to_beta` branch.

Low Code Issue | Low Code PR | Merged in low_code_cdk_to_beta? | Fixed in FE?
-- | -- | -- | --
https://github.com/airbytehq/airbyte/issues/19410 | https://github.com/airbytehq/airbyte/pull/21403 | ✅ | ✅
https://github.com/airbytehq/airbyte/issues/19408 | https://github.com/airbytehq/airbyte/pull/21632 | ✅ | no change needed
https://github.com/airbytehq/airbyte/issues/19409 | https://github.com/airbytehq/airbyte/pull/21434 | ✅ | no change needed
https://github.com/airbytehq/airbyte/issues/19698 | https://github.com/airbytehq/airbyte/pull/21832 | ✅ | no change needed
https://github.com/airbytehq/airbyte/issues/21866 | https://github.com/airbytehq/airbyte/pull/21878 | ✅ | no change needed
https://github.com/airbytehq/airbyte/issues/21559 | https://github.com/airbytehq/airbyte/pull/21823 | ✅ | ✅
https://github.com/airbytehq/airbyte/issues/21560 | https://github.com/airbytehq/airbyte/pull/21891 | ✅  
https://github.com/airbytehq/airbyte/issues/21561 | https://github.com/airbytehq/airbyte/pull/22294 | ✅ | no change needed
https://github.com/airbytehq/airbyte/issues/21576 | https://github.com/airbytehq/airbyte/pull/21990 | ✅ | ✅
https://github.com/airbytehq/airbyte/issues/21239 | https://github.com/airbytehq/airbyte/pull/22120 | ✅
https://github.com/airbytehq/airbyte/issues/19961 | https://github.com/airbytehq/airbyte/pull/22225 | ✅ 
https://github.com/airbytehq/airbyte/issues/20792 https://github.com/airbytehq/airbyte/issues/21095 | https://github.com/airbytehq/airbyte/pull/22398 | ✅ 

Basic outline of the work to be done:
* Backend
    * Update the version: This will only be possible once the `low_code_cdk_to_beta` branch is merged in `master` and published. In the meanwhile, you can `pip install -e $ROOT_DIR/airbyte/airbyte-cdk/python/` before running the `uvicorn` command
    * Fix the tests
* Frontend
    * Regenerate files relying on `declarative_component_schema.yaml`
    * Update the convertToManifest function to properly set the updated fields
    * Update the manifestToBuilderFormValues function to properly extract the updated fields (and tests)
    * PR explaining how to test the frontend with a local cdk: https://github.com/airbytehq/airbyte/pull/22375

**Comment by lmossman** [comment]
Fixed some of the changes for the frontend in this PR: https://github.com/airbytehq/airbyte/pull/22375

There have been a few more changes since then which I will try to address today/tomorrow, but the stream slicer refactor is still not merged

**Comment by flash1293** [comment]
Plan for handling the "incremental" refactoring:
* New section "Incremental" for datetime stream slicer
* Always have an implicit cartesian slicer for slicers (just have an "add" button)

**Comment by flash1293** [comment]
FYI @Upmitt @misteryeo  about the above as it re-arranges a bit the components

**Comment by flash1293** [comment]
@brianjlai Looks like this can get closed?

**Comment by brianjlai** [comment]
we'll leave this to track the split out PR for the merge
