### ISSUE TITLE
Make connector builder server build incremental

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#21933]
## problem
`SUB_BUILD=PLATFORM ./gradlew :airbyte-connector-builder-server:build` does the same build steps every time. Even if no code changed, running that command twice runs the exact same build steps. Gradle easily supports incremental build steps. 

## Solution clues
Specifying incremental is most likely only a matter of specifying the input files. See [this link](https://docs.gradle.org/current/userguide/performance.html#enable_incremental_build_for_custom_tasks). 

## Acceptance Criteria
- [ ] Running `SUB_BUILD=PLATFORM ./gradlew :airbyte-connector-builder-server:build` twice in a row should not run the build twice if no input files changed. The second build should be fast/`UP-TO-DATE`
- [ ] If we modify a source file or a dependency (or anything "upstream" changes), the whole thing should rebuild.

**Comment by maxi297** [comment]
Migrated to https://github.com/airbytehq/airbyte-platform/pull/110

**Comment by maxi297** [comment]
I wanted to close the PR, not the issue. Oops!!!

**Comment by maxi297** [comment]
The build hasn't been made fully incremental. However, partially incremental builds are 4s so it's good enough for now. See https://github.com/airbytehq/airbyte/pull/22548#issuecomment-1435118108 for more information

**Comment by sherifnada** [comment]
@maxi297 I think we can close this issue for now. Once we move to the java server it should be incremental "by default"

**Comment by sherifnada** [comment]
I didn't realize this PR was not merged, apologies. Reopening
