### ISSUE TITLE
Connector builder add string before API key in Authentication

### ISSUE THREAD

**Issue by martindlarsson** [airbytehq/airbyte#21940]
Using connector builder UI I would like to be able to add the string 'Token' before {{ config['api_key'] }} in the Authentication section and the API key field. It needs to render the following yaml:
`authenticator:
      type: ApiKeyAuthenticator
      header: "Authorization"
      api_token: "Token {{ config['api_key'] }}"`

Thanks for the amazing work! I love it. 👍

**Comment by marcosmarxm** [comment]
Thanks reporting this @martindlarsson

**Comment by marcosmarxm** [comment]
Did you try editing using the YAML editor?

**Comment by martindlarsson** [comment]
Yes but when I switched over to the UI it said it wasn't accepted. This what it says:

Your YAML manifest is not compatible with the Connector Builder UI, due to the following error:

Authenticator's api_token value must be of the form {{ config['key'] }}

**Comment by marcosmarxm** [comment]
Got it, I added the issue to connector builder backlog!

**Comment by martindlarsson** [comment]
Thanks!

**Comment by martindlarsson** [comment]
Is there any progress on this?

**Comment by martindlarsson** [comment]
Any news?

**Comment by martindlarsson** [comment]
Please add this feature soon! @timroes @marcosmarxm

**Comment by martindlarsson** [comment]
ping @timroes and @marcosmarxm

**Comment by martindlarsson** [comment]
Anything?

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
