### ISSUE TITLE
Source Pipedrive: Connection check fails if you don't have any deals

### ISSUE THREAD

**Issue by jtruty** [airbytehq/airbyte#21944]
## Environment
- **Airbyte version**:  example is 0.40.29
- **OS Version / Instance**: example macOS
- **Deployment**: local docker-compose
- **Source Connector and version**: Pipedrive 0.1.13
- **Step where error happened**: Setup new connection

## Current Behavior
All credentials are valid, adding a source fails with `StopIteration` error. I looked at the source and found this is because the connection code relies on there being at least a single deal present in the Pipedrive instance. I had no deals, so this failed. When I added a single deal, the connection was successfully added.

## Expected Behavior
Connection check should pass because all credentials are valid, even if there are no deals in the instance.

## Steps to Reproduce
1. Remove all deals from Pipedrive instance
2. Attempt to connect with valid credentials

## Are you willing to submit a PR?

Yes, I plan to fix and allow success if the deal request is successful, but there are no deals.
StopIteration is raised here due to no deals and no default given to `next`:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-pipedrive/source_pipedrive/source.py#L35:L36

**Comment by grubberr** [comment]
Fixed here https://github.com/airbytehq/airbyte/pull/23539
