### ISSUE TITLE
Source Postgres: non-string data types sent to destination as strings

### ISSUE THREAD

**Issue by adam-bloom** [airbytehq/airbyte#21986]
## Environment
- **Airbyte version**:  0.40.28 (but this has existed for at least 6+ months)
- **OS Version / Instance**: AWS EC2
- **Deployment**: k8s EKS
- **Source Connector and version**: Postgres 1.0.38
- **Destination Connector and version**: Redshift 0.3.53
- **Step where error happened**: Sync job

## Current Behavior
Potentially related to #21695.

All numeric data types in postgres are sent to the destinations as strings. We're using raw loading, no normalization. It doesn't make much sense that normalization would need to convert strings back to numeric types, since numeric types can be loaded directly in the destinations. 

## Expected Behavior
I expect the _airbyte_data object to hold numeric values for columns that are numeric in the source.

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Maybe

**Comment by natalyjazzviolin** [comment]
@adam-bloom I'm double checking, but I believe this is expected behavior without normalization?

**Comment by adam-bloom** [comment]
@natalyjazzviolin why would this be expected? With raw loading, there’s no reason every value in the loaded object would be a string - numerical and Boolean values can be serialized as json without issue.

**Comment by VitaliiMaltsev** [comment]
@adam-bloom tested today postgres-source 1.0.42 with **bigint, bigserial, boolean, float, int, numeric, decimal, real, smallint, smallserial, serial** datatypes and cannot reproduce an issue from description. All values loaded to the proper JsonNodes in _airbyte_data(**int** to IntNode, **float** to DoulbleNode, **null** to NullNode, **bool** to BooleanNode, etc)
<img width="1154" alt="json-nodes-values" src="https://user-images.githubusercontent.com/39538064/215751060-b52219ba-d1a7-4e6d-8ec1-d8ed13dd3882.png">

Do you have any more additional tips how to reproduce it?

**Comment by adam-bloom** [comment]
@VitaliiMaltsev thanks for confirming. I took another look again today - this appears to be something internal to redshift SUPER handling and not an airbyte issue. Sorry for the false report!
