### ISSUE TITLE
Connector version management

### ISSUE THREAD

**Issue by set5think** [airbytehq/airbyte#22000]
## Environment
- **Airbyte version**:  example is 0.40.29
- **OS Version / Instance**: Amazon Linux 2, ec2
- **Deployment**: Docker orchestrated by Nomad
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where error happened**: Specified connector version for destination-redshift, but it reverted back to previous connector at some point.
 
## Current Behavior
I'm noticing behavior where the connector version you specify can revert back to the suggested version, and when that happens, switching the version back to the desired one is not enough.  I had to deleted the connector and start over.

## Expected Behavior
airbyte should honor the version you specify in the connectors page.

## Logs

I haven't captured logs of this occurring yet.

## Steps to Reproduce
1.  Specify a version on a connector 
2. Check back at some point and see if it's changed back
3. Try changing it to desired version and running a sync, and notice it doesn't use the version you specified.

## Are you willing to submit a PR?
Sure

This is behavior I have noticed.  I specifically was using the destination-redshift connector, I specified it to use 0.3.28.  I ran it once against a connection and it worked as I had hoped, and the logs showed it was using that version.  I reran the sync a little while later, and it failed.  When I looked at the logs, I noticed it was using a more recent version of the destination-redshift connector.  My last observation was that changing the version number on the destinations connector page was not enough to have the connections using destination-redshift to switch.  I had to deleted all connections related to that, update the version, and then recreate the connections.

While it'd be great to understand if this is an issue, the real question I came here to ask was regarding pinning connectors to specific versions as part of the airbyte deployment?  I think that would give more confidence any time we upgrade/deploy that we are honoring the versions we specify in as part of configuration.

Thanks,

-Hassan

**Comment by natalyjazzviolin** [comment]
@set5think steps to reproduce need to be more exact. Please try to track down what exactly causes the connector to be reverted back, we need to make sure it's not specific to your setup only. I will reopen the issue when there are exact steps to reproduce.
