### ISSUE TITLE
Source Google Spreadsheet: charts in a separate google sheet break syncing

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2202]
## Expected Behavior
If a Google spreadsheet has two pages:

1. data
1. dashbaord

Airbyte should be able to sync data from the first page. 

## Current Behavior
Currently the second page prevents the sync from taking place.

## Airbyte Version
This happened about 1mo ago, but it doesn't look like there have been any changes that would impact this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368091924107) by [Unito](https://www.unito.io)

**Comment by bazarnov** [comment]
We'll try to reproduce the issue first. 
Could you please describe what are the steps to reproduce the issue? (example: create a sheet, append data, do something else.....start to fetch the data....fail)

**Comment by jrhizor** [comment]
In order to attempt to reproduce:
- create a google sheet with a simple table that can be ingested (maybe use the table used for the google sheet integration test?)
- perform a sync from that source into any destination (it should succeed)
- then, click `+` to add a new page at the bottom left corner of the google sheet app
- in this second tab, go to `Insert` -> `Chart` and create any chart.
- in Airbyte, create a new sync from this sheet to the destination

If this issue still exists, you shouldn't be able to successfully sync the first page into any destination.

If you are able to sync that first page we can just close this issue. If you can't sync that page then we'll need to fix the underlying issue.
