### ISSUE TITLE
Source Intercom: extend `Contacts` schema with `opted_out_subscription_types`

### ISSUE THREAD

**Issue by KayakinKoder** [airbytehq/airbyte#22043]
## Tell us about the problem you're trying to solve
In Intercom source, contacts can subscribe/unsubscribe to marketing emails. This information is stored in an `opted_out_subscription_types` prop on each contact

## Describe the solution you’d like
Add the `opted_out_subscription_types` prop to contacts

## Describe the alternative you’ve considered or used
NA

## Additional context
A future issue should list subscription types present (https://developers.intercom.com/intercom-api-reference/v2.7/reference/list-all-subscription-types). This will require updating Intercom api to v2.7 or higher, which includes some potentially breaking changes.

## Are you willing to submit a PR?
Yes, working on one now

**Comment by sajarin** [comment]
Thanks for the issue, let us know when the PR is ready to review!

**Comment by KayakinKoder** [comment]
Thanks @sajarin it is ready, although tests need to be run by an airbyter: https://github.com/airbytehq/airbyte/pull/22095

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Intercom: extend `Contacts` schema with `opted_out_subscription_types`](https://app.harvestr.io/components/0/list/RmX4YKN7f)
