### ISSUE TITLE
Move build status reports to GCP instead of AWS

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#22074]
# Problem
Currently we output a few of our build logs to `AWS`.

Specifically the `airbyte-connector-build-status` logs and the `airbyte-ci-ac-tests-logs`.

Ideally these artifacts should be in GCP alongside all of our other data.

# Solution
1. Create new buckets in GS for `airbyte-ci-ac-tests-logs` and `airbyte-connector-build-status`
2. Update all write instances for the AWS buckets to point at the new GS buckets
3. Migrate the cloudfront references to [Google Cloud CDN](https://cloud.google.com/cdn/docs/).
4. Update the builds.md file to point to these new CDN'd buckets

**Comment by sherifnada** [comment]
I'd like to suggest an additional acceptance criterion: document how this whole process is rigged up so the next person trying to figure out how these magical banners populate is able to so
