### ISSUE TITLE
Update ER Diagram in internal docs to include instructions on how to generate a most recent copy

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#22080]
# Problem

Currently the ER diagrams are static ludic chart diagrams in the [internal docs](https://internal-docs.airbyte.io/DBs/DB-Schemas/)

This makes them out of date by definition.

# Solution

Provide the instructions to generate the docs yourself by
1. Starting the project in dev mode
2. connecting to the db
3. generating the ER diagrams

**Comment by bechurch** [comment]
Up for review here: https://github.com/airbytehq/airbyte-platform-internal/pull/4290

**Comment by evantahler** [comment]
I think this is done!
