### ISSUE TITLE
[Helm] Airbyte deploy with external database stucks on bootloader initilization

### ISSUE THREAD

**Issue by empeekdev** [airbytehq/airbyte#22094]
## Environment
- **Airbyte version**:  v0.40.26
- **Deployment**: Kubernetes ( Helm)
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Hi all, we tried to install airbyte in our Kubernetes cluster with helm, the following values were provided:

```
postgresql.enabled=false

global.database.secretName = airbyte-postgresql-secret

global.database.host= foo.bar.com

global.database.port= 5432

externalDatabase.host= foo.bar.com

externalDatabase.user= airbyte

externalDatabase.existingSecret= airbyte-postgresql-secret

externalDatabase.existingSecretPasswordKey= DATABASE_PASSWORD

externalDatabase.database= db-airbyte

externalDatabase.port= 5432
```
During chart deploying boot loader stuck and doing nothing, there are boot loader logs:

```
2023-01-29 19:53:42,136 main INFO Loading mask data from '/seed/specs_secrets_mask.yaml

2023-01-29 19:53:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1161 - Using default value for environment variable CONFIG_DATABASE_USER: 'airbyte'

2023-01-29 19:53:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1161 - Using default value for environment variable CONFIG_DATABASE_PASSWORD: '*****'

2023-01-29 19:53:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1161 - Using default value for environment variable CONFIG_DATABASE_URL: 'jdbc:postgresql://foo.bar.com:5432/db-airbyte'

2023-01-29 19:53:42 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting...

2023-01-29 19:53:42 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed.

2023-01-29 19:53:42 INFO c.z.h.HikariDataSource(<init>):80 - HikariPool-2 - Starting...

2023-01-29 19:53:42 INFO c.z.h.HikariDataSource(<init>):82 - HikariPool-2 - Start completed.

2023-01-29 19:53:42 INFO i.a.c.EnvConfigs(getEnvOrDefault):1161 - Using default value for environment variable SECRET_PERSISTENCE: 'TESTING_CONFIG_DB_TABLE'
```
RDS instance is accessible from boot loader logs, username, password, connection string etc is correct.

I’ve thought first the problem is that I tried to connect deployment to database with existing data (dumped and restored from different air byte deployment), but then I tried on clean database and issue still persists.

Am I missing something in chart configuration or is it bug?

## Expected Behavior
Airbyte should be successfully deployed to Kubernetes cluster with external database connected

## Steps to Reproduce
1.  Use EKS 1.24
2. Install helm chart version 0.43.9 with the values provided above

**Comment by jensjohansen** [comment]
We are having the same issue. DAATABASE_PASSWORD is not being set in the {release}-airbyte-secrets secret, and bootloader is failing
We are also using Kubernetes 1.24, and almost the exact same values.yaml, except we are also passing DATABASE_PASSWORD in secrets: (per the values.yaml example, but not working) and trying to preset the secret before helm install gets deleted during the helm upgrade.

**Comment by jensjohansen** [comment]
Found the issue:
In secret.yaml, there is an if statement that prevents storing the DATABASE_PASSWORD in the secret:

```
  {{ if eq .Values.externalDatabase.existingSecret "" -}}
  DATABASE_PASSWORD: {{ .Values.externalDatabase.password | default .Values.postgresql.postgresqlPassword | quote }}
  {{ end -}}
```
Work-around: remove the existing secret specs from the overrides to value.yaml. Down-side: you have to use the secret created by the airbyte installer instead of using an existing secret.

Our installation is now working.

**Comment by empeekdev** [comment]
Closing issue since latest helm chart release ( v0.43.24) fixed this issue

**Comment by hongbo-miao** [comment]
Hmm, we are using Airbyte v0.63.1 and Helm chart v0.199.0, and still have this issue. I posted the question at https://stackoverflow.com/questions/78636116/error-couldnt-find-key-database-user-in-secret-airbyte-airbyte-secrets 😔

**Comment by hongbo-miao** [comment]
Hmm, we are using Airbyte v0.63.1 and Helm chart v0.199.0, and still have this issue 😔
I posted a workaround solution at https://stackoverflow.com/a/78644975/2000548

**Comment by hongbo-miao** [comment]
I found a clean solution. I posted at https://stackoverflow.com/a/78644975/2000548 😃
