### ISSUE TITLE
Postgres destination copies all source data into a single column

### ISSUE THREAD

**Issue by varunbpatil** [airbytehq/airbyte#2209]
## Expected Behavior
When running Postgres → Postgres sync, I expected the destination table to be exactly the same as the source table with a few additional columns for the Airbyte metadata.

## Current Behavior
All data from the source table is being dumped into a single column called `_airbyte_data`. Also, the table name `_airbyte_raw_public_users` doesn't match the [documentation](https://docs.airbyte.io/tutorials/postgres-replication#4-check-if-the-syncing-actually-worked).

This is what the source table looks like:
![image](https://user-images.githubusercontent.com/1353218/109114968-60d5ee80-7764-11eb-9396-0937f8de40c4.png)

This is what the destination table looks like:
![image](https://user-images.githubusercontent.com/1353218/109115034-79de9f80-7764-11eb-8ac6-84e42dad6e35.png)

## Steps to Reproduce
1. Setup Postgres source.
2. Setup Postgres destination.
3. Setup full-refresh connection.

## Severity of the bug for you
High

## Airbyte Version
0.14.4-alpha

## Connector Version (if applicable)
Postgres 0.1.13

## Additional context
*Environment, version, integration...*

**Comment by varunbpatil** [comment]
Ah! I had "basic normalization" disabled. With it enabled, the destination table looks fine although the table name on the destination doesn't match the [documentation](https://docs.airbyte.io/tutorials/postgres-replication#4-check-if-the-syncing-actually-worked).

**Comment by michel-tricot** [comment]
You're right. we are actually right in the middle of strengthening our naming logic for tables, schemas & namespace.
