### ISSUE TITLE
Speed up Testing & Publishing a connector

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#22130]
The goal of this story is to speed up our `/test` and `/publish` comands. 

Say you are [publishing a python connector](https://github.com/airbytehq/airbyte/actions/runs/4051035949/jobs/6969001007).  The `/publish` task takes over 10 minutes, and most of that time is spent on sub-tasks that are not relevant to the connector.  There are some strange dependencies in our grade tasks. 

For example, running the SAT test for a connector (e.g. `./gradlew :airbyte-integrations:connectors:source-faker:integrationTest`) tests normalization (`:airbyte-integrations:bases:base-normalization:checkPython`), and builds and tests all of SAT locally, including SAT's own test suite (`:airbyte-integrations:bases:source-acceptance-test:_unitTestCoverage`).  

This issue is to think about our gradel DAG and look for improvements:
* Why is normalization involved at all?  I'll bet we build the normalization imagage in-case the connector is a destination needs normalization.  Can we be smarter and only build normalization for destinations?
* If there are no changes to the local SAT directory, can we use the `#latest` docker tag, or at the very least, skip SATs own internal tests?
* Should the publish command's `manage.sh` script use `gradle --scan` so we can better track/time these things?

**Comment by sherifnada** [comment]
great minds think alike. Just created https://github.com/airbytehq/airbyte/issues/22128 which should fix some of these problems

> Should the publish command's manage.sh script use gradle --scan so we can better track/time these things?
yes -- free win!

**Comment by evantahler** [comment]
> great minds think alike. Just created https://github.com/airbytehq/airbyte/issues/22128 which should fix some of these problems
> 
> > Should the publish command's manage.sh script use gradle --scan so we can better track/time these things?
> 
> yes -- free win!

Nice! I'll close this and we can keep your issue - the memes are better

**Comment by alafanechere** [comment]
I'm re-opening because I think there are test specific optimization a bit different from the one mentioned in `SUB_BUILD=CONNECTOR_BASE` #22128

**Comment by alafanechere** [comment]
https://github.com/airbytehq/airbyte/pull/23332 was also an improvement in speeding up connector testing.

**Comment by alafanechere** [comment]
Connector /test are not testing and building connector-acceptance-test anymore. 
We should perceive a speed improvement of ~10mn on /test .
