### ISSUE TITLE
document or have a script for running airbyte as a systemd service

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2214]
## Tell us about the problem you're trying to solve
`docker-compose up -d` is not a particularly robust solution for keeping Airbyte alive on a production install for something like an EC2 instance.

## Describe the solution you’d like
We could [wrap Airbyte's docker-compose as a systemd service](https://community.hetzner.com/tutorials/docker-compose-as-systemd-service) and either document how to do this/operate or offer a script that sets this up for something like an EC2 instance.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368092334502) by [Unito](https://www.unito.io)

**Comment by friendofasquid** [comment]
I found this as Googled how to set this up before attempting. But since there's nothing here, here's what I came up with that seems to be working on Amazon Linux:

Paste the following file into  `/etc/systemd/system/airbyte.service`, e.g.

```bash
sudo nano  /etc/systemd/system/airbyte.service
```

```ini
[Unit]
Description=Airbyte
After=network.target docker.service

[Service]
Type=simple
ExecStart=/bin/bash /srv/airbyte/run-ab-platform.sh
ExecStop=/usr/bin/docker compose -f /srv/airbyte/docker-compose.yml down

[Install]
WantedBy=multi-user.target
```

followed by the following commands:

```
sudo systemctl daemon-reload
sudo systemctl start airbyte
sudo systemctl enable airbyte
```

To see the logs:

```bash
sudo journalctl -u airbyte
```

**Comment by dmvianna** [comment]
**NixOS**

NixOS aims to be immutable. Airbyte is designed as self-updating. So that's how I went about drilling a hole in NixOS:

1. Create a [derivation](https://github.com/NixOS/nixpkgs/pull/282806/files) for `run-ab-platform.sh`. I think I went overboard with this, I'm sure just getting that file would do;

2. Create a script that copies `run-ab-platform.sh` and the other important files into a **systemd** cache directory:
```nix
let
  airbyte = pkgs.callPackage ./airbyte/default.nix { };
  airbyte-service-name = "airbyte";
  airbyte-service-start = pkgs.writeScriptBin "airbyte-service-start" ''
    #!${pkgs.bash}/bin/bash

    set -euox pipefail
    cd $CACHE_DIRECTORY
    ${pkgs.rsync}/bin/rsync -rtu ${airbyte}/ ./
    ./run-ab-platform.sh
  '';
in
```

3. Write your **systemd** unit.
```nix
  systemd.services.${airbyte-service-name} = {
    description = "Airbyte";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" "docker.service" "docker.socket" ];
    requires = [ "network-online.target" ];
    environment = {
      # Proxy Configuration
      # Set to empty values, e.g. "" to disable basic auth
      BASIC_AUTH_USERNAME = "airbyte";
      BASIC_AUTH_PASSWORD = "password";
    };
    serviceConfig = {
      Type = "notify";
      User = airbyte-service-name;
      SupplementaryGroups = "docker"; # without it you can't run `docker compose`
      DynamicUser = true;
      CacheDirectory = "${airbyte-service-name}";
      CacheDirectoryMode = 755; # make the cache directory mutable
      ExecStart = "${airbyte-service-start}/bin/airbyte-service-start"; # copy the files into it and start
      ExecStop = ''
        ${pkgs.docker}/bin/docker compose -f ./docker-compose.yaml down
      '';
      Restart = "on-failure";
      TimeoutSec = "10min"; # it takes quite a while to stand up airbyte
    };
    # curl and tput (in ncurses) are required by the airbyte script
    path = with pkgs; [ curl docker docker-compose ncurses ];
  };

  virtualisation.docker.enable = true;

```

**Comment by natikgadzhi** [comment]
@bgroff do you want those above in our docs, or close this?

**Comment by davinchia** [comment]
Stale.
