### ISSUE TITLE
Allow starting "create connection" workflow halfway through, defining the source via url

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#22156]
The primary technical blocker to https://github.com/airbytehq/airbyte-cloud/issues/4217.

Enrolling in the Free Connector Program in done via a round trip to a stripe domain; which means restarting from a fresh page load; so we lose any in-progress UI state.

Trouble is, the current create connection _UI_ is totally stateful, so showing a banner when it could be presented as "oh, you're currently making a connection from an alpha/beta source? Want it to be free?" would currently wipe out the session and force the user to re-select their source.

But each step of the creation workflow re-queries the backend to reflect the actual persisted data, which means the frontend already has everything it needs to resume a session in place. So:
1) add code to check the create connection url for a `sourceId`; a query param would be least intrusive, but a path parameter would also work
2) when loading the create connection top-level route component, check the url for a `sourceId`; if one is present, jump to the mid-creation step with the correct source loaded
3) add the `sourceId` to the url as soon as the source is defined and saved
4) now we can show the enrollment banner without making users redo any work after leaving the Airbyte page for the Stripe one.
5) :tada:

**Comment by timroes** [comment]
I'm trying to understand how that helps users getting back "mid creation" into their source?We only can save a source/destination config if it passes tests, i.e. if it's "complete and validated". At that point the form is pretty much done. We can't really save a config on the backend that isn't fully complete yet, so we can't navigate back to some "mid creation" of a connector config that way. Could you maybe clarify for me, if we're expecting this to be mostly used to jumping back to an already saved connector (i.e. "mid creation" means "mid creation of your connection setup", but not "mid creation of your connector setup") or if we plan to make any BE changes for this to support jumping back to "mid creation of your connector setup"?

**Comment by ambirdsall** [comment]
Apologies for the late answer, @timroes!

> I'm trying to understand how that helps users getting back "mid creation" into their source?We only can save a source/destination config if it passes tests, i.e. if it's "complete and validated". At that point the form is pretty much done. We can't really save a config on the backend that isn't fully complete yet, so we can't navigate back to some "mid creation" of a connector config that way.

This is all 100% correct; the ticket will make much more sense when I edit it in a few seconds to read **connection**, rather than **connector**.
