### ISSUE TITLE
Stale build info reported to slack build status reports

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#22179]
# Problem
The [build_report.py](https://github.com/airbytehq/airbyte/blob/2c97aa379aade9121c6b6905affb90d1bafdb926/tools/bin/build_report.py#L33) script pulls reports from cloudflare instead of the bucket directly.

This leads to an issue where the CDN can be behind the latest build status report for a significant amount of time. Which means the slack report can be inaccurate when run

# Possible solutions
1. Change cache time (Low effort)
2. Change the script to reference the bucket directly (Low effort)
3.  Bust cache on upload (Medium effort)

**Comment by evantahler** [comment]
Maybe we can change the TTL on the CDN to only be 1 min?

**Comment by erohmensing** [comment]
Grooming: 

Try hardcoding defaults to a minute

We could potentially later follow up with moving build reports to the domain Conor gave us for the metadata project.
