### ISSUE TITLE
Allow testing a source

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#2217]
## Tell us about the problem you're trying to solve
A source has gone dead since I set it up and I open the source page. I want to see if it would pass whatever default validation is going on as if I had just set it up. On Zapier, for instance, you can click a 'Retest' button and a 'Retest and continue'.

## Describe the solution you’d like
I click a button and I'm told whether the settings on this thing will function

## Describe the alternative you’ve considered or used
Inspect the 'Save Changes' button, remove the `disabled` attribute. Click it.

## Additional context
![A screenshot with minimal utility](https://user-images.githubusercontent.com/7322596/109226865-44da4900-7774-11eb-8bfe-8c42f41ea290.png)

**Comment by cgardens** [comment]
@johnlafleur what do you think about this? I like the idea. Would it work with the design to just add an additional button?

**Comment by johnlafleur** [comment]
So it would be at the source or destination connector level. Not at the connection level (as it would be equivalent to "Sync now"). Can you confirm?

**Comment by roshan** [comment]
Yeah, just a health check on the source/destination to see that it's fine, not at the source<->destination pair.

Even if the 'Save Changes' button were turned into 'Test and Save' and not ever disabled, that would be great.

**Comment by johnlafleur** [comment]
2 possible suggestions on the design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21501%3A1
The difficult is to have a standardized feedback after requesting the test. 
I think I have a preference for option 2

**Comment by cgardens** [comment]
Nice! I have no strong preference. Maybe slight lean towards option 2 as well.

**Comment by michel-tricot** [comment]
Same here!

I think the retest button is confusing it can mean two things:
- I made some changes, I want to test them without saving
- I want to test the current configuration

**Comment by johnlafleur** [comment]
Oh indeed. So it would be less confusing if the button was at the top then. Let's go for option 2 then!

**Comment by Jamakase** [comment]
@johnlafleur What if the user has changed some settings - should we make that button disabled? It could be a bit confusing which configuration is currently connector using if I change some fields and press test even if the button is at the top.

@cgardens don't we already have some status in API that says whether syncs are successful or not? What if we just always call check_connection when we open the page? So the user will know that some credentials do not fit ASAP?

**Comment by cgardens** [comment]
> don't we already have some status in API that says whether syncs are successful or not?

True (or at least we're adding it). That being said, I think it is a bit separate. The idea is that you want immediate feedback on whether if you ran a sync right now things would succeed. A use case might be if the user is rotating passwords on a database or something. The last run succeeding doesn't mean the next one will.

> What if we just always call check_connection when we open the page? So the user will know that some credentials do not fit ASAP?

it can be a little expensive to run the check_connection (more in terms of time than compute), so I think it might make sense to only run it 1. when we need to 2. if the user explicitly requests. that's how i've been thinking about it anyway. Otherwise, I don't have a strong counter argument. Just that'll it will be slow and require us to schedule work that's not strictly necessary.

**Comment by johnlafleur** [comment]
> What if the user has changed some settings - should we make that button disabled? It could be a bit confusing which configuration is currently connector using if I change some fields and press test even if the button is at the top.
I would think that the state of the "Save changes & test" and "Enable" buttons should be separate from the "Retest source" experience. So if I update a field and those buttons are enabled, then if I click on "retest source", the buttons will disappear during the test, and reappear as enabled after the test is done. Does that make sense?

**Comment by cgardens** [comment]
Ended up going with option 1 here, because of a technical reason why option 2 was going to be headache. I don't think based on the level of opinion between the 2 options it was worth handling the technical thing.
