### ISSUE TITLE
Check Images Exist action incorrectly reporting successful status

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#22170]
## Current Behavior

An error in the check_images_exist.sh script is causing all checks to be reported as successful. 

This was originally reported in[ this slack thread ](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1675197085141189), where a normalization image had not been published but the check was still being reported as successful.

## Expected Behavior

The check should fail if the image tag does not exist on docker hub. We should also modify the script to report a failure if there was any sort of error when executing the script (such as these expected integer errors)

## Logs

```
URL: https://hub.docker.com/v2/repositories/airbyte/connector-builder-server/tags/0.40.32
./tools/bin/check_images_exist.sh: line 67: test: -lt: unary operator expected
./tools/bin/check_images_exist.sh: line 62: test: : integer expression expected
	STATUS: found
./tools/bin/check_images_exist.sh: line 67: test: -lt: unary operator expected

	airbyte/proxy: 0.40.32
	URL: https://hub.docker.com/v2/repositories/airbyte/proxy/tags/0.40.32
./tools/bin/check_images_exist.sh: line [62](https://github.com/airbytehq/airbyte/actions/runs/4058177408/jobs/6984795147#step:3:63): test: : integer expression expected
./tools/bin/check_images_exist.sh: line 67: test: -lt: unary operator expected
	STATUS: found

Checking Normalization images exist...
Checking normalization images with version 0.3.2 exist...
	airbyte/normalization: 0.3.2
	URL: https://hub.docker.com/v2/repositories/airbyte/normalization/tags/0.3.2
./tools/bin/check_images_exist.sh: line 62: test: : integer expression expected
./tools/bin/check_images_exist.sh: line [67](https://github.com/airbytehq/airbyte/actions/runs/4058177408/jobs/6984795147#step:3:68): test: -lt: unary operator expected
	STATUS: found
```

Example run https://github.com/airbytehq/airbyte/actions/runs/4058177408/jobs/6984795147

**Comment by erohmensing** [comment]
Grooming: likely just a bug in the shell script, a "unit test" on an always existing/always missing docker image might help narrow things down 

grep for figuring out rate limiting might return null?

**Comment by evantahler** [comment]
Moving this to the `Pipelines` epic - maybe this bash script should be moved to Dagger?
