### ISSUE TITLE
Improve the visibility of running connector tests

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#22172]
# Problem
Getting visibility into how many Connector Integration tests are running and for which specific connector is poor.

Some acute areas are:
1. When you run the `Run Integration Test` github action from the github UI, there is no indication on the job as to which connector and commit its being run. This results in being unsure at a glance what tests are currently running
1. The above issue is compounded by nightly integration runs. The octavia bots kicks off all the builds, but its unclear which have been triggered, which have failed, which have succeeded.
1. When you run the `/test` command in a PR and the rocket appears, there is no link to the specific Github Action. Making it difficult to know when the test may be complete.

# Possible solutions
## Low effort
Use github action `run-name` to apply the commit and connector name to the integration test title. [Link](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name)

## High effort
1. Create a simple web app that reports current status of all connectors builds, in addition to information of all pending builds

**Comment by evantahler** [comment]
Closing this issue because the Dagster pipeline solves it!
