### ISSUE TITLE
Update Connector Versions

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2218]
## Tell us about the problem you're trying to solve
As an operator, I want to be able to:
* See what is the newest official version of any given connector.
* In "one-click" upgrade from my current version to the new version.

Depends on https://github.com/airbytehq/airbyte/issues/1983

**Comment by johnlafleur** [comment]
Here are 2 suggestions of design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21397%3A2488
Preference for option 1, but maybe more complicated to implement.

**Comment by michel-tricot** [comment]
Just added some comments on Figma

**Comment by davinchia** [comment]
@Jamakase can we sneak this into the sprint? this is now possible with the merging in of https://github.com/airbytehq/airbyte/pull/2323 - `list_latest` is now available on the `SourceDefinition` and `DestinationDefinition` routes.

I believe we want to go with option 2 in the linked Figma doc. 

@cgardens to keep me honest.

**Comment by cgardens** [comment]
Yup. Let's go with Option 2 from the mockups.

@Jamakase going to add this into the current sprint to be done in front of other low priority issues. But it's the middle of the week, so it's okay if this doesn't get worked on until next week.

To give just a little more explanation, the list_latest should give you the ability to see what the latest version of a connector is (as compared to source_definitions/list, which just gives you the version that is currently configured for the deployment). Let us know if anything is unclear.
