### ISSUE TITLE
Source Hubspot: schema should load properties dynamically

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#2219]
## Tell us about the problem you're trying to solve
Hubspot entities have dynamic schema, to retrieve a list of available (default and custom) properties we need to call 
https://api.hubapi.com/properties/v2/ticket/properties<entity>?hapikey=demo (see `StreamAPI.properties` method).

## Describe the solution you’d like
We should have a basic schema in `schemas` folder for each entity, retrieve `properties` at run time, merge it with basic and return during `discover`. Basically, we will reproduce logic in the singer tap (but will make it simpler).
Note: we need this only for entities, i.e. not for streams like `contact_lists` or `data_pipelines`

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by keu** [comment]
implemented as part of #2215
