### ISSUE TITLE
Source Pinterest: Extend metrics in analytics stream

### ISSUE THREAD

**Issue by iberchid** [airbytehq/airbyte#22206]
## Environment
OS Version / Instance: Ubuntu
Deployment: Docker
Source Connector and version: source-pinterest:0.1.9

## Current Behavior
We found below metrics missing in the connector:

- VIDEO_P0_COMBINED_1
- VIDEO_P100_COMPLETE_1
- VIDEO_P25_COMBINED_1
- VIDEO_P50_COMBINED_1
- VIDEO_P75_COMBINED_1
- VIDEO_P95_COMBINED_1
- VIDEO_3SEC_VIEWS_1
- VIDEO_MRC_VIEWS_1
- APP_INSTALL_COST_PER_ACTION
- CLICKTHROUGH_2
- CLICKTHROUGH_1
- ENGAGEMENT_2
- ENGAGEMENT_1
- TOTAL_CLICK_ADD_TO_CART

## Are you willing to submit a PR?
Yes

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Pinterest: Extend metrics in analytics stream](https://app.harvestr.io/components/0/list/uw-oTAE3F)

**Comment by YowanR** [comment]
Note: We expect all new streams for this connector to be incremental.

**Comment by artusiep** [comment]
@YowanR ,  I’d like to start working on this issue.

**Comment by YowanR** [comment]
@artusiep Assigned it to you! Looking forward to your contribution!! 🚀

**Comment by artusiep** [comment]
@YowanR issue has been solved
