### ISSUE TITLE
Add HttpAvailabilityStrategy to low-code cdk

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#22219]
We want to make this availabilitystrategy available in the low-code CDK - currently the low code doesn't use HttpStreams by their class, so it won't affect them. 

In doing so, we want to take a look at current implementations of sources that subclass the HttpAvailabilityStrategy to add custom behavior
* Are there common errors that are being added to many sources that we could make part of the default?
* Is there extra functionality that is common or could also be parametrized in the initialization of the httpavailabilitystrategy?

The end goal here is to restructure this availabilitystrategy so that it can be initialized based on a set of low-code parameters, instead of needing to subclass in python code to achieve anything other than the default functionality. For exmaple, right now, we could have users choose an `availability_strategy: HttpAvailabilityStrategy` for their stream and pass in a dict of `code: error message to show user` pairs. Before we do so, we want to see if there are other aspects we want to make configurable from the user's end.

We'd like to get this finalized for the 1.0 of the low-code CDK.

**Comment by evantahler** [comment]
I think this project belongs with @team/extensibility.

**Comment by erohmensing** [comment]
I'll close this in favor of this already open issue: https://github.com/airbytehq/airbyte/issues/21654
