### ISSUE TITLE
groovy-gradle-plugin not found

### ISSUE THREAD

**Issue by zuodh** [airbytehq/airbyte#2225]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**Comment by cgardens** [comment]
@zuodh can you give a bit more context on the issue here? there's not really enough information here for us to help you out.

**Comment by davinchia** [comment]
Closing as stale. Please reopen if this issue still persist!
