### ISSUE TITLE
Allow a user to filter fields/columns from a table

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2227]
## Tell us about the problem you're trying to solve
As an operator, I want to be able to select a subset of the fields in my table to be replicated.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368150710590) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
Created a duplicate, will just add my description: 

## Tell us about the problem you're trying to solve
Users currently cannot select which fields (columns) they want to sync from their streams -- if you pick a stream, it's all or nothing. However, users want the ability to project which fields they want. A simple use case is sensitive data like described in #2463 . We can do this at the Airbyte level without having to do it separately for every connector by filtering the incoming records to contain only the selected fields in the catalog.

Sources can still implement projection as needed (e.g: a DB source will still want to select only the relevant columns for efficiency reasons), but this can be implemented "for free" outside the connectors.

## Describe the alternative you’ve considered or used
Projection at the destination level

**Comment by olivermeyer** [comment]
Bumping this issue as it's very relevant to us (and probably most users affected by GDPR or similar local legislation). In our case, we're pulling data from Salesforce which contains sensitive information and writing it to S3 where it should be considered immutable, so preventing the sensitive stuff from entering our systems at all would be a big plus.

**Comment by ashishgupta-97065** [comment]
Fairly important for our use cases too. For many of our key tables less than 30-40% of the columns are actually required for analytics use cases. Selecting all significantly adds to trasfer load and warehouse size

**Comment by jamesutton** [comment]
+ 1 for this request!   Same issue as @olivermeyer called out, we would rather not ingest PII data at all rather than having to mask it at the destination.   This is accomplished through other integration methods (custom python scripts or stitch) by being able to select columns.

**Comment by agrass** [comment]
Very important for us too, would be really great to be able to select specific fields the same way We select models.

**Comment by kyle-cheung** [comment]
+1 for this too, I want to bring Airbyte to our org but cannot if we can't deselect extreme sensitive fields as we don't want those living in our Snowflake warehouse

**Comment by sotte** [comment]
Related https://github.com/airbytehq/airbyte/issues/4400

**Comment by b4stien** [comment]
Another reason why this feature would be useful: my source (as well as my destination) is Postgres and I have a column whose type is not understood by Airbyte (it's `bit(343)`) and causes a sync failure. For now I have to exclude the whole table to have a successful sync (ideally I'd just have to exclude the faulty column).

**Comment by kyle-cheung** [comment]
Just want to comment again as this has become very important for us. We're trying to setup HR/People analytics and using the BambooHR and Greenhouse source connectors, however, there is some extremely sensitive information especially from Bamboo including SSN, salaries, addresses, etc. We don't need this information and as it is we can't setup this connection if we have to replicate the full table.

Thanks!

**Comment by olivermeyer** [comment]
I'm happy someone is bumping this - I'm a bit concerned that this issue has been open for a year now, especially since it's the 3rd-most (and until recently, 2nd-most) upvoted issue.

> Just want to comment again as this has become very important for us. We're trying to setup HR/People analytics and using the BambooHR and Greenhouse source connectors, however, there is some extremely sensitive information especially from Bamboo including SSN, salaries, addresses, etc. We don't need this information and as it is we can't setup this connection if we have to replicate the full table.
> 
> Thanks!

@kyle-cheung we also pull data from BambooHR and, luckily, Bamboo allows to restrict which fields the API token can access. We use that to avoid pulling sensitive data. Might be a solution in your case.

**Comment by kyle-cheung** [comment]
@olivermeyer thanks for the insight! So you're using Airbyte's BambooHR connector, and within the Employees stream you can select which fields the API can view? Does this cause any errors in Airbyte's replications? Greenhouse's sync errors out if it doesn't have access to the required streams

**Comment by sherifnada** [comment]
Hi all, thanks for bumping this and agreed we should be giving better viability into target landing date for the feature. It is currently planned for implementation in Q2. We'll be able to give a more concrete timeline as time progresses.

**Comment by olivermeyer** [comment]
> @olivermeyer thanks for the insight! So you're using Airbyte's BambooHR connector, and within the Employees stream you can select which fields the API token can view? Does this cause any errors in Airbyte's replications? Greenhouse's sync errors out if it doesn't have access to the required streams

That's right. API tokens in BambooHR are attached to users, and as I understand it's possible to restrict which fields each user can access - I haven't actually done that part since I'm not in HR : ). No errors in Airbyte, just a looot of null fields in the normalized table.

> Hi all, thanks for bumping this and agreed we should be giving better viability into target landing date for the feature. It is currently planned for implementation in Q2. We'll be able to give a more concrete timeline as time progresses.

Good to hear, and really looking forward to this feature. Thanks for the update.

**Comment by judahrand** [comment]
Another big +1! Was looking at Airbyte but this is one of the major issues blocking adoption.

**Comment by b4stien** [comment]
FWIW it's possible to manually edit the schema in DB and remove the unwanted parts (that's what we're currently doing). You can edit the `airbyte_config.connection` table, the data is in the `catalog` column.

You'd have to do this each time you edit your schema though, at my company we have a mini-script specifically doing that...

**Comment by HaithemSouala** [comment]
+1

**Comment by kyle-cheung** [comment]
hey @olivermeyer sorry to message you here! Couldn't find another place to ping you. I've tried to follow your steps with restricting access to the user in Bamboo, it's kind of working but kind of not working. I shot you a message in Airbyte, please let me know if you're able help or connect me with someone in your HR to see if our setup is similar. Weird thing is it's pulling in some stuff that we hid and pulling in `NULL`s for things we didn't hide

**Comment by cesar-vigario-knok** [comment]
+1

**Comment by jzhang-georgian** [comment]
> FWIW it's possible to manually edit the schema in DB and remove the unwanted parts (that's what we're currently doing). You can edit the `airbyte_config.connection` table, the data is in the `catalog` column.
> 
> You'd have to do this each time you edit your schema though, at my company we have a mini-script specifically doing that...

Hi @b4stien Bastien, would it be possible to share that mini-script on gist? Thank you :)

**Comment by b4stien** [comment]
@jzhang-georgian [here is the gist](https://gist.github.com/b4stien/5e32d4a91512378b1c189905fabe613a), sorry for the delay.

**Comment by moreaupascal56** [comment]
Hello all and @sherifnada, I was just wondering if you had a new timeline for this feature ? I did not found it on Airbyte roadmap. 
Thank you and have a great day :)

**Comment by misteryeo** [comment]
This is something we currently have slotted for Q4 exploration: https://app.harvestr.io/roadmap/view/pQU6gdCyc/airbyte-roadmap?p=lymTZInr0. 

cc: @andyjih

**Comment by moreaupascal56** [comment]
> This is something we currently have slotted for Q4 exploration: https://app.harvestr.io/roadmap/view/pQU6gdCyc/airbyte-roadmap?p=lymTZInr0.
> 
> cc: @andyjih

Thank you @misteryeo 👍

**Comment by jablonskijakub** [comment]
> FWIW it's possible to manually edit the schema in DB and remove the unwanted parts (that's what we're currently doing). You can edit the `airbyte_config.connection` table, the data is in the `catalog` column.
> 
> You'd have to do this each time you edit your schema though, at my company we have a mini-script specifically doing that...

I tried that solution and realised that the unwanted columns are still being synced in the raw table (they are removed in the normalised version). Is there a way to tackle that problem?

**Comment by andyjih** [comment]
Hi @jablonskijakub -- not currently, but we'll be tackling column filtering in the upcoming months!

**Comment by YohanGrember** [comment]
Hello team 👋 
I'm also interested in this field filtering for GDPR reasons.

I'd also like to be able to add fields that are not mentioned in the default catalog.
For example, for stripe connectors, our AM unlocked fields that are not mentioned in the catalog.
We are able to ingest these fields through our legacy Python stack but as the Airbyte Stripe catalog is hardcoded, theses fields are not retrieved during Airbyte ingestion.
Will the filtering feature giving more control on the catalog also enable to add fields?

**Comment by will-gp** [comment]
> 

This is a real pain point for us. If we're selecting only certain columns to sync, we don't want them filtered after they get to us. They should never reach Airbyte in the first place.

**Comment by mattppal** [comment]
Same here— this has pretty big implications for security and PII

**Comment by annafedotova** [comment]
We are on the self-hosted version and we really need this functionality to keep using Airbyte because of the PII implications and security

**Comment by grishick** [comment]
AFAIK this is already implemented and released

**Comment by will-gp** [comment]
> AFAIK this is already implemented and released

@grishick can you show me where this is the case? I just tried running the latest Airbyte version (0.40.32) with a connection from a postgres database to a file. When setting up the connection, I don't have the option to filter fields/columns (see screenshot).
![airbyte_sync](https://user-images.githubusercontent.com/89144621/216706467-9812b50b-2815-4b43-bcdb-283b0fed34a4.png)

**Comment by sherifnada** [comment]
@andyjih can you update this ticket with the status of the feature?

**Comment by andyjih** [comment]
Hi all, this feature isn't yet available, but it's actively being worked on. We'll follow up on this issue when there's an update. Sorry for the confusion!

**Comment by olivermeyer** [comment]
> Hi all, this feature isn't yet available, but it's actively being worked on. We'll follow up on this issue when there's an update. Sorry for the confusion!

Hi @andyjih, do you have a timeline for this feature? It's been repeatedly pushed back in the roadmap, which is unfortunate given that it's been the 2nd-most popular issue for a long time now (and the 1st has been delivered).

**Comment by piyushsingariya** [comment]
This feature is much needed!

**Comment by yuvaraj91** [comment]
> `airbyte_config.connection` table, the data is in the `catalog`

Hi @b4stien , could you please let know where I can find the objects `airbyte_config.connection` and `catalog` ?

**Comment by flowritetiina** [comment]
Would appreciate this feature a lot

**Comment by catkins** [comment]
Apologies for adding to the pile-on here, but this is an issue for our team as well. Poking around in the catalog feels a bit brittle, so something baked-in to airbyte would excellent.

**Comment by jefferson-roth-mayd** [comment]
> > `airbyte_config.connection` table, the data is in the `catalog`
> 
> Hi @b4stien , could you please let know where I can find the objects `airbyte_config.connection` and `catalog` ?
> 
> Edit: I found this was in the Airbyze metadata db.

Can you show us one example of how you're editing it?
Thanks

**Comment by adolitos** [comment]
This feature would help my squad and team to address GDPR, PII and other regulations!

**Comment by constah** [comment]
Very important feature  to address data protection and also allow ability to only load what is needed.

**Comment by dro248** [comment]
This is **extremely** important for us.

**Comment by malikdiarra** [comment]
Indeed, you can now select which field you want to replicate when setting up a new connection.

**Comment by walker-philips** [comment]
@malikdiarra are the selected columns available to the source despite being applied by the infrastructure workers? I have a 900 column (yes, I know, unfortunately its a third party vendor platform) that blows open any approach at quickly reading from it. If I could pass through the selected columns from the UI, I could significantly lessen the size of the data being processed from the database.
