### ISSUE TITLE
Support FB Marketing API v10

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2230]
## Tell us about the problem you're trying to solve
For a user to use Airbyte's FB connector, they need to create a FB app. Access tokens generated from FB Apps can only be used with the latest API version present at the time of creating the FB app. 

Facebook just released [v10 of the marketing API](https://developers.facebook.com/docs/graph-api/changelog/version10.0#graph-api), and a user just reported being unable to use the FB connector since their app only supports v10. 

We should upgrade to FB marketing API v10 so we do not have this issue. We should verify that apps were initialized on older API versions will not be impacted.

**Comment by yevhenii-ldv** [comment]
**Scoping report**:

At the moment, the [facebook-business](https://pypi.org/project/facebook-business/) library (which we use to work with Facebook Marketing) version `10.0.0` is already available, which supports the Graph version `10`.
Referring to the [link](https://developers.facebook.com/docs/graph-api/changelog/version10.0#graph-api), the updates should not have an impact on the previous API (unless it may slightly affect the Ads Insights API, this will need to be rechecked).


Also, these changes will need to be applied to the Instagram connector, I will do it today while working on the task: [Source Instagram: Ensure best practices](https://github.com/airbytehq/airbyte/issues/2276)

Approximate estimate for updating the library version and retesting all Facebook Marketing streams: **3h**
