### ISSUE TITLE
[Low-Code CDK] Review low-code to beta changes once all changes have been merged

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#22330]
## What

We have had a lot of changes added into the `low_code_cdk_to_beta` branch. We review PRs before they merge into that branch, but we should collectively review things one more time to ensure that this is validated and smoothly released. It is a little hard to point this since it could be a lot or a little work.

We should also prepare a post to socialize to both our open source contributors and the global logic teams with the following information
- We have promoted the low-code CDK language to beta
- What this means for developers and the next steps they should take
- A list of all the language changes that are being made
- Examples of each change

## Acceptance Criteria
The following checks should be made against the latest version:
- [x] Sanity check that `spec` works for all low-code connectors: Run `./gradlew validateSourceYamlManifest`
- [x] Verify that we can construct all the stream components from a manifest (we can temporarily insert `self.streams({}` into spec to easily test this in the previous script mentioned
- [x] Verify 3 connectors that use `incremental_sync` successfully sync and are emitting state messages. Validated: [ `source-greenhouse`, `source-close-com`, `source-zenloop` ]
- [x] Verify that a connector implementing substream `partition_router` works for at least 2 connectors. Validated: [ `source-braze`, `source-close-com`, `source-square` ]
- [x] Verify that a connector implement list `partition_router` works for at least 1 connector. Validated: [ ~~source-google-pagespeed-insights~~ `source-survey-sparrow` ]
- [x] Verify a connector that inherits a field like `url_base` for a paginator from another node. Validated: [ `source-tempo` ]
- [x] Verify that unit tests pass for all declarative connectors
- [x] Verify CAT tests pass for at least 8 connectors. Validated: 
  - `source-chartmogul` - All passed
  - `source-delighted` - All passed
  - `source-greenhouse` - All passed
  - `source-monday` - All passed
  - `source-posthog` - `master` currently has 2 failing incremental tests, same for this branch
  - `source-prestashop` - Local runs of `master` and the branch fail the CAT schema validation. I checked the data types and records by running syncs on both and the data matches. Suspicious why it passes on the CI run, but this might be an issue w/ my local env since the same thing happens on master
  - `source-square` - All passed
  - `source-tempo` - All passed
  - `source-woocommerce` - All passed
  - `source-zenloop` - All passed
- [x] Verify that a connector built from the local CDK can be run successfully in a local instance of Airbyte [ `source-greenhouse` full refresh + incremental tested ]
- [x] Verify that a connector that there are no low-code manifests that contain the following fields or components: `request_options_provider`, `$options`, `*ref(`, `JsonSchema`, `stream_cursor_field`, `checkpoint_interval`, `inject_into: path`, `stream_slicer`
- [x] Verify that the following component + field do not exist: `DpathExtractor.field_pointer`, `DefaultPaginator.url_base`, `SimpleRetriever.primary_key`, `SimpleRetriever.name`, `HttpRequester.name`
- [ ] A post is written and communicated to the community and to the GL teams about the list of changes.

**Comment by svlada** [comment]
Which version of **airbyte-cdk** should we set in **setup.py** if we want to support the **0.28.0** manifest version that the UI connector builder makes?

Also, what needs to be defined in the Docker file for the **LABEL io.airbyte.version** to make sure **0.28.0** of manifest is working.

**Comment by brianjlai** [comment]
Hi @svlada 

For convenience, we usually just specify in `setup.py` as `"airbyte-cdk~=0.1",` which will always pull the latest minor version. So at this point we're well into the `0.40+`

As for the Dockerfile, I don't think `LABEL io.airbyte.version` has any bearing on which CDK version we use. As long as you specify `~=0.1`, you should be pulling the latest CDK version we have because we have not bumped the major version yet. You could use `>=` for `0.28` if you want to extra careful.
