### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by radaniba** [airbytehq/airbyte#22357]
Hi everyone,

Just started a fresh install of airbyte on a mac, everything worked fine but while I was configuring a postgres connector my computer crashed, started again, tried to start airbyte again but I have a full white page with this message 

`Upgrade Required` 

It is a fresh install, removed all the docker compose, images and volumes, started again, but still have this error message, cleared the cache, but still got the same one

Something happened that prevents airbyte from starting, on the `docker compose up` command everything looked Ok though, any idea ?

**Comment by sajarin** [comment]
Hey @radaniba are you still experiencing this issue?

**Comment by nataliekwong** [comment]
Hi there, since it's been a while since the last response, I'll go ahead and close this issue.
