### ISSUE TITLE
Invalid interpolation format for "environment"

### ISSUE THREAD

**Issue by prudhviagility** [airbytehq/airbyte#2235]
Hello,

I have cloned the project on to my machine and I am trying to start the project using docker-compose up.  It is giving the following error. 

Invalid interpolation format for "environment" option in service "scheduler": "AIRBYTE_ROLE=${AIRBYTE_ROLE:-}"

Docker compose version :  1.28.5 

I am not able to find anything about this error on the installation steps. 

Thank you

**Comment by michel-tricot** [comment]
Not normal (obviously). It seems version `1.28.5` was released 3 days ago, I wonder if they introduced some kind of regression.

Are you on mac/linux/windows? 

Any chance you can rollback to an earlier version?

**Comment by prudhviagility** [comment]
It was my mistake, I had two installations of docker-compose on my system. So when I was running sudo docker-compose. It was using old version of docker-compose hence the error. Once I update the docker-compose version of sudo user, it worked it out any problem.
