### ISSUE TITLE
CustomRecordExtractor: field_pointer should not be required

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#22368]
CustomRecordExtractor does not work without field_pointer. You may find 3 redundant `field_pointer` in 3 custom components in [Amplitude migration](https://github.com/airbytehq/airbyte/pull/22362).
It looks like json_schema tries to validate it with standard DpathExtractor schema
```
jsonschema.exceptions.ValidationError: 'field_pointer' is a required property
Failed validating 'required' in schema['allOf'][1]['properties']['extractor']['allOf'][1]:
    {'properties': {'config': {'type': 'object'},
                    'decoder': {'$ref': '#/definitions/JsonDecoder',
                                'default': {}},
                    'field_pointer': {'items': {'anyOf': [{'$ref': '#/definitions/InterpolatedString'},
                                                          {'type': 'string'}]},
                                      'type': 'array'}},
     'required': ['field_pointer', 'config'],
     'type': 'object'}

On instance['extractor']:
    {'$options': {'name': 'events',
                  'path': '/2/export',
                  'primary_key': 'uuid',
                  'stream_cursor_field': 'server_upload_time'},
     'config': {},
     'name': 'events',
     'path': '/2/export',
     'primary_key': 'uuid',
     'stream_cursor_field': 'server_upload_time',
     'type': 'CustomRecordExtractor'}
```

**Comment by brianjlai** [comment]
The current workaround is to simply add a dummy `field_pointer` to make it pass validation. It can be removed once we release the changes as part of Beta.

This is a known issue w/ the old way that we performed schema validation. As part of the low-code to beta epic https://github.com/airbytehq/airbyte/issues/18068, we are getting rid of the old schema validator in favor of the new one based on the handwritten schema so this should no longer be an issue.

Going to close this one as we have a fix in progress on the aforementioned epic.
