### ISSUE TITLE
Source google analytics: stream selection does not work

### ISSUE THREAD

**Issue by baumgaro** [airbytehq/airbyte#2236]
## Expected Behavior
When setting up a connection and only selecting several "tables" -the selection should be used.

## Current Behavior
The selection is ignored and all "tables" are configured. This happens when using the source Google Analytics.

## Steps to Reproduce
1. Use Source Google Analytics
1. Only select "pages"
1. Start sync and check on the "Settings tab" and also in the destination schema - all "tables" are synced.

## Severity of the bug for you
Medium

## Airbyte Version
0.15.0-alpha

## Connector Version (if applicable)
Google Analytics 0.1.8

## Additional context
![Image 424](https://user-images.githubusercontent.com/3285310/109411932-8ef64100-79a5-11eb-986e-7e001c3e5884.png)

**Comment by sherifnada** [comment]
@baumgaro thanks for reporting the issue, we'll take a look soon.

**Comment by ChristopheDuong** [comment]
I think this bug is also happening from Postgres Source to some destinations.

Actually it might not be tied to a specific source connector.

**Comment by jrhizor** [comment]
Looks like a frontend issue since the `/connections/create` call contains `"selected": true` when the streams are deselected. I flagged this with Artem as a high priority issue.
