### ISSUE TITLE
Source LinkedIn Pages: source connector not working

### ISSUE THREAD

**Issue by gabricc** [airbytehq/airbyte#22386]
hey guys!

## Environment
- **Airbyte version**: 0.40.27
- **Deployment**: EKS
- **Source Connector and version**: airbyte/source-linkedin-pages 0.1.0
- **Destination Connector and version**: clickhouse
- **Step where error happened**: Setup new source

## Current Behavior
When I try to set up the connector it just fails with a generic error:
![image](https://user-images.githubusercontent.com/42014588/216797339-3b0a7047-3193-43ca-b15d-99be082dd7ad.png)
In one of the attempts I went to the log path described in the UI and found this:
![image](https://user-images.githubusercontent.com/42014588/216797376-297eaef3-4440-4817-9adb-98d42c24c823.png)

## Expected Behavior
Connector set up should've finished successfully.

## Logs
Aside from the logs I mentioned above there is no other relevant message.

## Steps to Reproduce
1. Go to Airbyte UI
2. Set up new LinkedIn Pages connector
3. Fill the credentials and try

**Comment by harshmange44** [comment]
Hey can I work on this?
CC: @octavia-squidington-iii

**Comment by natalyjazzviolin** [comment]
@harshmange44 feel free to work on this!

**Comment by ireyna-modo** [comment]
I had this error and solved it by upgrading to 1.0.2. I was using 0.1.0

**Comment by lazebnyi** [comment]
Solved in 1.0.2
