### ISSUE TITLE
Source MSSQL - basic normalization failed using Incremental | Deduped + history

### ISSUE THREAD

**Issue by lkqbi2023** [airbytehq/airbyte#22385]
## Environment
- **Airbyte version**:  0.40.28
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**:  Microsoft SQL Server (MSSQL) ALPHA
- **Destination Connector and version**: Microsoft SQL Server (MSSQL) ALPHA

## steps:

Airbyte basic nomalization failed when using reset using sqlserver connector using Incremental | Deduped + history

I have found 2 issues when running airbyte using sqlserver connector:
in Incremental | Deduped + history mode:
1 when there are 0 new rows detected, it will take the same amount of time to sync even there is nothing change. this will create big performance issue when the target table is big
2 after pressing "Reset your data" button, it will fail

1  create target schema and pupulate sample data

-- test airbyte
-- test_stg.dbo.t_stg --> test_stg.ab.t_stg   (src tableName == dest tableName)
use test_stg
create schema ab  
GRANT  SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: ab TO public;                       -- grant sqlserver user           

if object_id('dbo.t_stg'  )              is not null   DROP TABLE dbo.t_stg              ;  
if object_id('ab._airbyte_raw_t_stg'  )  is not null   DROP TABLE ab._airbyte_raw_t_stg  ;  
if object_id('ab.t_stg_scd'  )           is not null   DROP TABLE ab.t_stg_scd           ;  
if object_id('ab.t_stg'  )               is not null   DROP TABLE ab.t_stg               ;  

CREATE TABLE dbo.t_stg(
    ETL_CREATE_DATE datetime ,
    ETL_MODIFIED_DATE datetime ,
    ETL_YEAR_MONTH int ,
    ETL_PROCESSED_FLAG varchar(1) ,
    SEQUENCE_NO int ,   -- ** CDC key=cursor field
    YrPrd int ,         
    item_no varchar(30) ,
    location_id int ,
    rev float ,
    cost float ,
	--primary key (item_no,location_id,YrPrd)   -- * DONT USE. will fail somehow. 
)
create unique index idx01 on dbo.t_stg(sequence_no)               -- muse use sequence_no for cdc cursor

-- generate random 10K rows in dbo.t_stg  PK=(item_no,location_id,YrPrd)
--  Sqlserver: 2" for 100K rows  
SET NOCOUNT ON;  
declare @nMax   int=10;   -- **
declare @nBatch int=10000;
declare @nRowID int=0;

truncate table dbo.t_stg
begin tran
WHILE (@nRowID < @nMax)
BEGIN
    insert into dbo.t_stg 
	values (getdate(),null,null,'N',            -- ETL_CREATE_DATE,ETL_MODIFIED_DATE,ETL_YEAR_MONTH,ETL_Process_Flag,
	        @nRowID,                            -- SEQUENCE_NO
			202200+ floor(RAND()*(12-1)+1),     -- YrPrd       int         *PK
			'i-' +cast(@nRowID as varchar(10)), -- item_no     varchar(30) *PK 
			floor(RAND()*(100-1)+1),            -- location_id int         *PK 
			100,90            -- rev,cost
			)
    
	if (@nRowID % @nBatch =0)
    begin
        RAISERROR ('Inserted rows  %i', 0, 1, @nRowID) WITH NOWAIT
        commit;
        begin tran
    end

    SET @nRowID = @nRowID + 1
END
commit;   -- last commit

SET NOCOUNT OFF;

2 create source and destination  and create connection
src        : test_stg   schema: dbo
destination: test_stg schemo: ab

create connection using above src and destination,
create new stream t_stg
   syc mode: INcremental | Deduped + history
   cursor field : SEQUENCE_NO
   primark key  : item_no,location_id,yrprd

save 
it will take 13" to sync the table.
    1.58 KB  10 emitted recordsno records   14s                     ---- *** first time insert 10 rows for 14s

select * from ab.t_stg   -- we can see 10 rows have been populated
so far so good

3. manually sync again, it will succeed, but took too long time
0 Bytesno recordsno records 13s                           -----***** this  bug#1 , 2nd time , even there is no records changed, it will take same amount of time to sync. when we have 100K rows alreay exist in target table, it will take 1' 

4. "Reset your data", success
select * from ab.t_stg   -- this will be Null

5. press Sync now, it will fail. this is the error msg
Failure Origin: normalization, Message: Normalization failed during the dbt run. This may indicate a problem with the data itself.

-- this is the error
2023-02-05 01:02:18 [42mnormalization[0m >   ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name '_airbyte_unique_key'. (207) (SQLExecDirectW)")

[airbyte_log_cb74ba67_7f11_4cee_8e74_6970d34406be_logs_200_txt.txt](https://github.com/airbytehq/airbyte/files/10610031/airbyte_log_cb74ba67_7f11_4cee_8e74_6970d34406be_logs_200_txt.txt)

**Comment by nguyenaiden** [comment]
@lkqbi2023 Can you try and rerun your sync with the latest `source-mssql` version and a different destination as well to see if the problem still persists? We want to isolate the issue to a specific source or destination.

**Comment by evantahler** [comment]
Normalization is being removed in favor of typing and deduping in V2 destinations
