### ISSUE TITLE
Connectors should use the StreamName namespace & name fields

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2240]
## Tell us about the problem you're trying to solve
Following-up on #2228, sources and destinations should use the new namespace and stream name from the AirbyteStreamName object to determine the source/final destination location of data that is being replicated.

This StreamName would potentially be altered by #2239 in the middle while being in transit from the source to the destination

## Describe the solution you’d like
Instead of using `AirbyteStream.getName()`, destination connectors should rely on `AirbyteStream.getStreamName().getNamespace()` and `AirbyteStream.getStreamName().getName()` 

(we should remove usage of methods based on `AirbyteStream.name`

## Additional context
This should be the final step to implement #1921 (before implementing the UI part to override final destinations)

**Comment by davinchia** [comment]
Closing as we've chosen a different approach to doing this.
