### ISSUE TITLE
New table should use switches instead of checkboxes

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#22429]
Currently the new table design uses checkboxes for allowing users to enable/disable which fields to sync:

![screenshot-20230206-214536](https://user-images.githubusercontent.com/877229/217081275-037f0f98-c124-4594-8887-cf7bbe85620b.png)

We should switch them to Switches (no pun intended), since we use checkbox in the connection page otherwise for bulk edit, and using the very same pattern suddenly on the same page for enableing/disabling (which we do on a stream level with switches) wouldn't be great usability.

At this point we could potentially also remove the word "Sync" from the table header, which is currently causing a bit weird spacing between the checkbox and the title, that looks like there might be some content that could go there (while there isn't; it's just because of the word "Sync" needing more space in the header).

**Comment by josephkmh** [comment]
@timroes I think using switches here unfortunately creates a couple more problems:

1. The "stream enabled" switch at the top of the panel looks identical to others (maybe it needs a label?)
2. Without a header label, I don't think it's clear what these switches are doing

![image](https://user-images.githubusercontent.com/7550957/217310128-64a290f7-84cb-4a6a-8df0-f7f1abb36a06.png)

WDYT? We might need another design pass here.

**Comment by timroes** [comment]
Good points, my 2 cents:

* Maybe we could label the switch on top as "Sync Stream" I feel there the label wouldn't be that problematic.
* Could we try using the even smaller switches for the fields?
* Would a tooltip over the switch for the fields help explaining what it does? I feel just "sync" on top didn't do a super great job explaining this either :D So I think maybe a tooltip might be the bestter solution? Or we could maybe replace the switch in the header (do we really need a toggle all here?) by a questionmark icon with a tooltip explaining column selection?

**Comment by josephkmh** [comment]
Here's another example:

![image](https://user-images.githubusercontent.com/7550957/217498898-9010eb36-8385-4b88-b538-f9561bba8e64.png)

I added `Sync Field` in the header, which I think is kind of necessary and follows the example of all other headers having a text value. I actually think that looks pretty good, but interested to hear what you and @Upmitt have to say!

I'm against using more tooltips generally (I see them as kind of an escape hatch) and in this case specifically because disabled switches already have a tooltip explaining why they're disabled. I feel like we could have a tooltip overload if they all have one.

**Comment by timroes** [comment]
No tooltips sound fine for me, I have a preference for `xs` siwtches, and like the label in the header. happy to hear Nico's input.

**Comment by Upmitt** [comment]
<img width="1247" alt="Screenshot 2023-02-08 at 11 45 25" src="https://user-images.githubusercontent.com/29780098/217508038-f6cc84f6-2104-481f-8626-1c7a238c8149.png">

Hi @timroes  & @josephkmh ! I like your solution, we already had this discussion about checkboxes / switches and I think what you suggest works well :) Here is a draft I did trying to remove the gap between the switch and the field name
