### ISSUE TITLE
Connector nightly builds should run on a single instance

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#22421]
## Tell us about the problem you're trying to solve
How the nightly builds are run today:
* A cron action dispatch one `/test` command per connector, which are run in separate action on different EC2 runner

The problem is that it's poorly optimized because spinning one github action per build workflow incurs a LOT of overhead. We are talking burning 5 minutes of machine time per job to spin up runners. Also fetching dependencies, because we don’t bake a lot on the machine, is terribly optimized, so a ton of time gets lit on fire redownloading the same dependency over and over and over and over.

## Describe the solution you’d like
I would like nightly connector to builds to run on a single instance. 

## Additional context
High CI costs. Convo [here](https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1675702812496639)

**Comment by erohmensing** [comment]
This might be a stupid question, but does running them on a single instance also mean running them in a queue vs in parallel? I'd worry that it wouldn't even finish in 24h 😄 

I'm sure we can run more than one at once, but it might be a measure of seeing how many can consistently run concurrently with the resources on the ec2 instance

**Comment by evantahler** [comment]
I *think* this is possibly also getting at the need for a more general connector publishing and testing orchestrator, which the Metadata PRD speculates about.

Also... /why/ do we spin up custom AWS images, and not use github actions with [larger](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners) runners?

**Comment by alafanechere** [comment]
Replaced by #23581
