### ISSUE TITLE
Declarative connectors runtime: Extend CDK publish process to update docker base image

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22442]
When publishing a new version of the CDK, the docker base image implemented as part of https://github.com/airbytehq/airbyte/issues/22438 should be re-built with the new version and published as well.

## Acceptance criteria

* There is a process in place that ensures there is a version of the `airbyte/source-declarative-manifest` docker image for every released CDK version with matching version numbers
* Docker image should only publish if publish to PyPI also succeeded

## Implementation Hints
1. there is a script `tools/integrartions/manage.sh` which builds & publishes docker images for connectos. we can reuse that. 
2. we might also need to modify the CI `.github` yaml files to push that image

**Comment by maxi297** [comment]
https://github.com/airbytehq/github-workflow-test-repo-base repo can be used to perform some tests
