### ISSUE TITLE
Connector builder projects: Add list API for builder projects

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22445]
Introduce API for listing builder projects of the current workspace

```
POST /v1/api/connector_builder_projects/list
{
    "workspaceId": "<workspace>"
}
```

Response
```
{
  "builderProjects": [
    {
        "builderProjectId": "<id>",
        "name": "My draft-only connector“,
        "hasDraft": false,
    },
    ...
  ]
}
```

If possible do not fetch the actual draft from the database into java memory but only a boolean column whether it is set to null or not.

For all apis the following constraints apply:
* Builder project doesn’t exist in workspace 404
* Name needs to be non-empty
* Draft can be “null” as well to unset it completely

## Acceptance criteria

* All APIs are functional as described above
* All APIs are unit-tested
* All introduced APIs need to be wrapped in cloud with Editor permission for workspace

**Comment by lmossman** [comment]
Grooming notes:
- Estimate for just one endpoint: 3
- @flash1293 to split up into one issue per endpoint
