### ISSUE TITLE
Declarative connectors runtime: Inject json into job configs on scheduling

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22440]
When a sync/schema/check job is scheduled, the source definition is checked whether it has a config injection attached. If this is the case, the json blob (in case of declarative definitions, the manifest) from the table is injected into the source configuration JSON object under the specified key (in case of declarative definitions, “__injected_declarative_manifest”) when building the job config. All layers below (temporal client, activity implementation, docker runner) work unchanged, passing down the manifest to the actual docker container which is running the specified CDK docker base image.

The injection path should just define a top-level property where the json value should be set. If the key already exists, this should throw an exception.

The config injection mechanism can later be used for other purposes besides injecting declarative manifests. 

For example:

Original configuration from the actor:
```
{
  "api_key": “...”,
  "start_time": "..."
}
```

JobDiscoverCatalogConfig:

```
{
  "connectionConfiguration": {
    "api_key": “...”,
    "start_time": "...",
    "__injected_declarative_manifest": { ... } // manifest json blob from declarative_manifest
  }
  "dockerImage": "airbyte/source-declarative-manifest:1.2.3",
  "sourceId": "<id>",
  // ...
  "isCustomConnector": true
}
```

In all places job configs for sync, discover and check jobs are built, the helpers introduced in https://github.com/airbytehq/airbyte/issues/22439 are used to look up all config injections for the current definition id and inject them into the config.

This should be moved into a utility class as it will need to be called from multiple places (similar to the `WorkspaceHelper`)

There should be unit tests and it should be manually tested to verify nothing breaks from this change.

**Comment by lmossman** [comment]
@flash1293 to create an issue to split out the acceptance tests. Keep the unit tests and manual tests as part of this issue.
