### ISSUE TITLE
Add declarative definition auto-updater

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22453]
Build a helper like `ApplyDefinitionsHelper` to fetch a separate seed file for docker repository and docker image tag that should be used for all declarative sources. This new routine should be run as part of `airbyte-cron` and execute the following steps:
* Fetch current seed file from a remote provider which fetches a GCS bucket that looks like this:
```
GET https://storage.googleapis.com/storage/v1/airbyte-seed-declarative.yaml
```

Contents:
```
dockerRepository: airbyte/source-declarative-manifest
dockerImageTag: 1.2.3
```

* Load all source definitions that have a linked active declarative manifest
* Update the docker repository and image tag with the values from the provider
* This should only run for cloud

Once the connector builder server is migrated to micronaut and docker, it should look up the same file to determine which CDK version to use.

**Comment by sherifnada** [comment]
@flash1293 to create a separate issue for handling this on the OSS side

**Comment by flash1293** [comment]
TOdo: Move this to the "
Connector builder open beta on cloud" epic and also use the same rollout for the connector builder server

**Comment by flash1293** [comment]
Closing this for now as we have a way to ship CDK updates as part of the platform build. Completely decoupling CDK updates for the platform lifecycle is a larger change that needs to happen separately
