### ISSUE TITLE
LinkedIn: currently used API is being deprecated

### ISSUE THREAD

**Issue by mdibaiee** [airbytehq/airbyte#22474]
## Environment
- **Airbyte version**:  N/A
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: LinkedIn Ads (and probably LinkedIn Pages)
- **Destination Connector and version**: N/A
- **Step where error happened**: N/A

## Current Behavior

- LinkedIn is sunsetting the API endpoints being used by the airbyte connectors, see:

> Legacy (unversioned) Marketing APIs using the base path https://api.linkedin.com/v2/ will be available for 9 months before they are sunset

Source: [LinkedIn Versioning](https://learn.microsoft.com/en-us/linkedin/marketing/versioning?view=li-lms-unversioned)

## Expected Behavior

- Connectors need to switch to the new endpoints.

**Comment by zilehuda** [comment]
@mdibaiee - any update on this issue?

**Comment by artem1205** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/26107
