### ISSUE TITLE
🎨 Design: Placeholder for empty stream table

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#22504]
## Tell us about the problem you're trying to solve
Currently, we don't inform the user that the source is empty and doesn't have any streams.
Also, we don't show any message if the stream search results are empty.

<img width="926" alt="image (1)" src="https://user-images.githubusercontent.com/20929344/217312931-0a1a92c2-3495-41dc-b1d0-22f4a2a89009.png">

## Describe the solution you’d like
We need to show a placeholder when the source doesn't have any streams(or table just empty)

**Comment by edmundito** [comment]
Closing. Design requests are tracked outside Github
