### ISSUE TITLE
Source GitHub: Add label name in issue_events stream

### ISSUE THREAD

**Issue by max-tobelem** [airbytehq/airbyte#22510]
## Tell us about the problem you're trying to solve
I am trying to track how fast specific labels are added to Pull Requests of a repo I am working on. In order to achieve this, I am relying on the `issue_events` stream that record, among others, labelling events. Unfortunately, the label associated to events are not stored.

## Describe the solution you’d like
I would like the label name added to the `issue_events` stream.

## Describe the alternative you’ve considered or used
I tried to see if the label name was available in another stream but I couldn't find one.

## Additional context
- [Github documentation about issue events](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28#list-issue-events-for-a-repository)
- [Current schema for `issue_events` stream](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/schemas/issue_events.json)

## Are you willing to submit a PR?

Yes I do, actually I think the addition would look like this:

```
      "label": {
        "type": ["null", "object"],
        "properties": {
            "name": {
                "type": ["null", "string"]
            }
        }
      }
```

**Comment by marcosmarxm** [comment]
Thanks @max-tobelem for reporting this. Let me know if you need any assistance to submit the pull request.

**Comment by grubberr** [comment]
I hope we close this PR https://github.com/airbytehq/airbyte/pull/24523
in that PR we extend schema for `issue_events` stream adding "label" key

https://github.com/airbytehq/airbyte/blob/bcec4bca540c5a4b072cc0f8755da9f404086e6c/airbyte-integrations/connectors/source-github/source_github/schemas/issue_events.json#L36

**Comment by grubberr** [comment]
Done in this PR https://github.com/airbytehq/airbyte/pull/24523
