### ISSUE TITLE
Relook needing JQ for build.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2253]
## Tell us about the problem you're trying to solve
`Jq` is currently required to build Airbyte. This is used in the `image_exists.sh` script.

This manifests as `DockerProcessBuilderFactoryTest` failures and requires manual log inspection to verify, so although the solution - `brew install jq`

* is pretty simple, the error is confusing.

## Describe the solution you’d like
`Jq` is either removed, or documentation is updated to specify need for install.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368216183199) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
we now document the jq dependency here: https://docs.airbyte.io/contributing-to-airbyte/developing-locally
