### ISSUE TITLE
Destination Weaviate: Support array of known type

### ISSUE THREAD

**Issue by samos123** [airbytehq/airbyte#22530]
Currently this will be thrown when using Slack as source and Weaviate as destination:
```
{'error': [{'message': "invalid string property 'pending_shared' on class 'Channels': not a string, but []interface {}"}]}
```

I will fix this in the Weaviate destination by supporting an array of unkonwn types.

Example where is this happening: https://github.com/airbytehq/airbyte/blob/8d1a027c86b228bdb8dd4894427b04d87b4fdc6b/airbyte-integrations/connectors/source-slack/source_slack/schemas/channels.json#L50..L53

**Comment by marcosmarxm** [comment]
Thanks @samos123 I'll review soon your contribution
