### ISSUE TITLE
Relook needing Postgresql for build.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2254]
## Tell us about the problem you're trying to solve
Our python builds currently require `pg_config` from the Postgresql libraries in order to build `psycopg2`.

This manifest as the following error message:

```
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH

or specify the full executable path with the option:



    python setup.py build_ext --pg-config /path/to/pg_config build ...



or with the pg_config option in 'setup.cfg'.

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build/psycopg2
```

Easily solved by installing Postgresql e.g. `brew install postgresql` (Mac), however confusing/annoying.

## Describe the solution you’d like
Postgresql is either removed, or documentation is updated to specify need.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368216198153) by [Unito](https://www.unito.io)

**Comment by supertopher** [comment]
@davinchia is this meant to focus on outside users and is it still a current priority?

**Comment by davinchia** [comment]
Outside users. Not a priority.
