### ISSUE TITLE
Source Facebook Marketing -  failing asking for upgrade to v16

### ISSUE THREAD

**Issue by ulfsjostrom** [airbytehq/airbyte#22549]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: GCP n2
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.84
- **Destination Connector and version**: 
- **Step where error happened**: Setup new connection

## Current Behavior
The connection tests failed, with an error message "
```
The connection tests failed.
FacebookAPIException('Error: 2635, (#2635) Your app has been upgraded to version v16.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.')
```

It is no longer possible to create Facebook Apps with v15.0 (that Facebook Marketing 0.2.84 supports). It is also not possible to downgrade new Facebook Apps from v16.0 to v15.0.

## Expected Behavior
The connection tests should succeed

## Logs
```
  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v15.0/act_<id has been removed by ticket poster>/
  Params:  {}
  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) Your app has been upgraded to version v16.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "<id has been removed by ticket poster>"
      }
    })
```

## Steps to Reproduce
1. Create a connector with Facebook Marketing
2. Test the connection

## Are you willing to submit a PR?
No

For additional details, please refer to to https://github.com/airbytehq/airbyte/issues/18167, which is a ticket for the last version update.

Image showing the result of a connection test
![image](https://user-images.githubusercontent.com/1234450/217484528-59a62b1a-46ba-4277-ae39-b3fa0e4cfc16.png)

Image showing that it is no longer possible to select v.15.0 as the version in newly created Facebook Apps
![image](https://user-images.githubusercontent.com/1234450/217483721-29df6aa1-ec27-492b-8806-1efd121b0d65.png)

**Comment by sajarin** [comment]
@girarda @grubberr pinging ya'll due to prior discussion on https://github.com/airbytehq/airbyte/issues/18167 (and because it's a GA connector)

**Comment by girarda** [comment]
@YowanR @artem1205 @darynaishchenko I just added this issue to GL's backlog. Can someone upgrade the connector to use v16.0?

**Comment by darynaishchenko** [comment]
working on it
