### ISSUE TITLE
Destination Iceberg: add AWS Glue Catalog support

### ISSUE THREAD

**Issue by rnonnon** [airbytehq/airbyte#22552]
## Tell us about the problem you're trying to solve
The Iceberg connector is currently supporting Hive/Jdbc/Hadoop catalog. 
I'd like this connector to support the AWS Glue Catalog.

## Describe the solution you’d like
Regarding the Iceberg documentation (https://iceberg.apache.org/docs/latest/aws/) and what the current connector code looks like, I guess we already include the mandatory dependencies :
```
implementation 'org.apache.iceberg:iceberg-spark-runtime-3.3_2.13:1.0.0'
implementation "software.amazon.awssdk:bundle:2.17.131"
implementation "software.amazon.awssdk:url-connection-client:2.17.131"
```

We probably should only have to add a new entry into CatalogType + adding an Implementation of IcebergCatalogConfig interface

## Are you willing to submit a PR?
I'm not yet enough experienced about Airbyte and Apache Iceberg to do so. But will do it if nobody does 😄

**Comment by GalvFionic** [comment]
Do you have any plans to offer support for this?

**Comment by kahlua-kol** [comment]
Would be really interested as well!

**Comment by sidharrth2002** [comment]
We are also very interested, looking forward to this support!

**Comment by saifmahamood** [comment]
Very interested in this. Looking forward to having this use case supported!

**Comment by gisripa** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/45707
