### ISSUE TITLE
Source Amazon Seller Partner: empty reports after connector update

### ISSUE THREAD

**Issue by ASchmidtGit** [airbytehq/airbyte#22555]
Is this your first time deploying Airbyte?: No
OS Version / Instance: Ubuntu
Memory / Disk: 100 GB
Deployment: Docker
Airbyte Version: 0.40.30
Source name/version: Amazon Selling Partner v. 0.2.31
Destination name/version: MySQL v. 0.1.20
Step: The issue is happening during sync

## Current Behavior
I updated the ASP connector to the newest version and tried to sync the report ‘GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL’ but the sync passes after a minute or two without any data beeing synced:

## Expected Behavior
GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL should return data, usually over 6GB

## Logs
[7ec40cb4_5316_4ebc_9fd9_96e2e7dc4af9_logs_20_txt.txt](https://discuss.airbyte.io/uploads/short-url/pcckw9EBywFoJS8yh48FmLBAD3L.txt) (29.5 KB)

## Steps to Reproduce
1. Setup a fresh installation of Airbyte v 0.40.30
2. Update ASP Connector to v. 0.2.31
3. Select GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL as report to sync
4. Start syncing and wait for about 2 Minutes

**Comment by ASchmidtGit** [comment]
Awesome, i used version 0.2.29 of the ASP connector before

**Comment by artem1205** [comment]
Hi, @ASchmidtGit, from your logs:
```log
2023-02-08 09:04:54 [44msource[0m > The report for stream 'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL' was cancelled or there is no data to return
```
it means that your report job has "processingStatus" == "CANCELLED", possibly automatically by Amazon due to no data.
Could you try with the latest version of connector and provide config or your sync?

**Comment by krisjan-oldekamp** [comment]
@artem1205 / @ASchmidtGit Same error here for the GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL report > No records returned (using v.1.5.1 / Airbyte 0.50.30). It's still working correctly in version 0.2.27 (Airbyte 0.40.14) of the connector,

**Comment by askarpets** [comment]
Hello @ASchmidtGit,
Have you tried to run the sync using the latest version of connector?

@krisjan-oldekamp, could you please confirm you're using the same date range and account and the only difference is the version? Could you share the config and logs of your sync?

**Comment by krisjan-oldekamp** [comment]
@askarpets I ran the sync on the newest version of the connector (2.5.0) on Airbyte 0.50.30. Still getting 0 results for GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL > It's still working on correctly in version 0.2.27 (Airbyte 0.40.14) with exactly the same credentials. See logs + screenshot attached. The GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL is the only stream configured in the connection. 
![image](https://github.com/airbytehq/airbyte/assets/4049344/3f69547b-b41f-42d9-997b-fc762b5d5f58)

[elho_job_1519_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13578711/elho_job_1519_attempt_1_txt.txt)

**Comment by askarpets** [comment]
@krisjan-oldekamp, could you please upgrade the connector to version `3.0.0` and try again?

**Comment by askarpets** [comment]
@krisjan-oldekamp, have you been able to check the connector with version `3.0.0`?

**Comment by askarpets** [comment]
Closing the ticket for now. Please reopen if needed.
