### ISSUE TITLE
New Source: Elasticsearch 

### ISSUE THREAD

**Issue by kixxalot** [airbytehq/airbyte#2255]
## Tell us about the new integration you’d like to have
Elasticsearch to Neo4j (daily/weekly)

## Describe the context around this new integration
Data in Elastic can be transactions or messages between users. In aggregate form, this data needs to be used by data scientists in a Neo4j database.

## Describe the alternative you are considering or using
Custom Python code or other ETL tools (KNIME? Talend?)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368151146507) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thanks @kixxalot !

What volume do you want to handle with your usecase?

**Comment by kixxalot** [comment]
10-100 million of Elastic documents

**Comment by mohamed-mubeen** [comment]
Hi Team,
Any tentative date for the availability of Elastic Search connector in Airbyte.
Data Movement: ES to Snowflake

**Comment by mohamed-mubeen** [comment]
Hi Team,
Any tentative date/month this year? for the availability of Elastic Search connector in Airbyte.
Data Movement: ES to Snowflake

**Comment by haithem-souala** [comment]
Hey,
Any ETA for this request?

**Comment by vsnuvt** [comment]
this is interesting use case.

**Comment by michel-tricot** [comment]
Someone from Elastic mentioned that we should be using the new client: https://github.com/elastic/elasticsearch-java when we start implementing this connector

**Comment by marcosmarxm** [comment]
Closed by: https://github.com/airbytehq/airbyte/pull/14118
