### ISSUE TITLE
Wrong env variables doc in octavia-cli README.md

### ISSUE THREAD

**Issue by danidelvalle** [airbytehq/airbyte#22567]
## Environment
- **Airbyte version**: 0.40.32
- **Component**: octavia-cli 

## Current Behavior
Current docs are showing a wrong env variable for `--airbyte-username` and `--airbyte-password`:

![image](https://user-images.githubusercontent.com/4973542/217581222-798cc5e2-a14a-484b-8d97-abe00504e9a7.png)

## Expected Behavior
* Fix these 2 env vars.

**Comment by sh4sh** [comment]
Nice catch!
