### ISSUE TITLE
Transformation toggle in UI does not persist as expected

### ISSUE THREAD

**Issue by happythenewsad** [airbytehq/airbyte#22564]
## Environment
- **Airbyte version**:  0.40.23
- **OS Version / Instance**: GCP n2
- **Deployment**: standard Docker deployment
- **Source Connector and version**: Postgres 1.0.28
- **Destination Connector and version**: BigQuery 1.2.8
- **Step where error happened**: Sync job

https://user-images.githubusercontent.com/90669/217577879-76725dfc-66fd-42d3-b18e-9e481fe71554.mov

## Current Behavior
In the Airbyte UI, the `Transformation` behavior will revert back to `Raw data (JSON)` after `Normalized tabular data` is toggled. See attached screengrab.

## Expected Behavior
I expect whichever transformation choice I toggle manually to stay toggled, before, during, and after any given sync.

## Logs
Github says that my logfile is too big to upload. Please advise.

## Steps to Reproduce

1. Starting state: normalized tabular data is toggled; tables are fully synced.
2. I edit the Transformation settings and remove a stream from my connection
3. A few minutes later, observe that Raw data (JSON) is toggled in the Transformation tab.

This is concerning because I don't know the state of my data (whether it's normalized or not), or why the transformation setting has reverted to Raw data (JSON). 

## Are you willing to submit a PR?
Not at this time.

**Comment by natalyjazzviolin** [comment]
@happythenewsad I was not able to replicate the issue, it works as expected on the latest version. Closing.
