### ISSUE TITLE
Looking for a document for Mixpanel to Redshift migration with CDC

### ISSUE THREAD

**Issue by sharath-rama** [airbytehq/airbyte#22592]
### Tell us about the documentation you'd like us to add or update.
It can be as pedantic as a typo or as titanic as an entire tutorial request.

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by marcosmarxm** [comment]
Only databases sources today has support to make CDC syncs.
Mixpanel doesn't have this feature today.

I'm closing the issue because is not a valid request.
