### ISSUE TITLE
Clean up EntityTable utils

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#22600]
In [EntityTable/utils.tsx](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/components/EntityTable/utils.tsx) we have a lot of connection properties that are drilled down deep into the tables. Instead, we should pass through the connection read object and rename/modify its underlying properties as needed in the consumer.

See PR comment here: https://github.com/airbytehq/airbyte/pull/22369#discussion_r1100517921

**Comment by josephkmh** [comment]
A refactoring PR could also close this issue at the same time: https://github.com/airbytehq/oncall/issues/1473#issuecomment-1422922696

**Comment by ambirdsall** [comment]
Making this simpler and less coupled will have _tons_ of benefits: I hit quite a lot of unnecessary development friction from those deeply-drilled props while working on free connector program stuff.
