### ISSUE TITLE
Have our own implementation of Slack Activity dashboard

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2261]
## Tell us about the problem you're trying to solve
We've built a tutorial about how you can use Airbyte and Superset to build some activity dashboard on Slack: https://docs.airbyte.io/tutorials/build-a-slack-activity-dashboard
But we're not currently tracking those metrics. We should have a running instance of this dashboard.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368092884173) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Actually, @DominusKelvin already set up the Slack Activity dashboard on his own workstation. We just need to sync with him so he can set it up on our server @cgardens.

**Comment by DominusKelvin** [comment]
Cool. When will you need me on this?

**Comment by cgardens** [comment]
not relevant anymore.
