### ISSUE TITLE
Have our own implementation of Slack Search interface

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2262]
## Tell us about the problem you're trying to solve
We're currently on a premium Slack plan in trial until beginning of April. But after that, we'll revert back to the free plan with limited access to the history. 
We should implement our own tutorial: https://docs.airbyte.io/tutorials/slack-history
and have the saving part running asap so we store the full history before switching back to the free plan.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368216014491) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
As for #2261 , @DominusKelvin could help us on that point. I would suggest to sync with him on that point, so he can set that up on our own server.

**Comment by cgardens** [comment]
not relevant anymore.
