### ISSUE TITLE
Make create connection / replication settings Configuration card collapsible

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#22625]
Update the card used for the Configuration settings to be collapsible and also match the design.

[Figma](https://www.figma.com/proto/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?page-id=5134%3A72488&node-id=5149%3A76110&viewport=379%2C572%2C0.13&scaling=min-zoom&starting-point-node-id=5149%3A76110&show-proto-sidebar=1)

# Blocked by
- [x] #22624

**Comment by flash1293** [comment]
@edmundito there is the "Collapsible" component - can it be leveraged here by putting a `Collapsible` in a `Card`? It should be fully accessible as well which is nice.

**Comment by flash1293** [comment]
Done already
