### ISSUE TITLE
[Bug] Can scroll content behind the stream details panel

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#22627]
User can scroll the content when the stream details panel is open.

## Steps to reproduce
1. Go to connection replication settings
2. Click on stream to open details panel
3. Use the mouse wheel (or equivalent) in the overlay behind the panel

**Comment by krishnaglick** [comment]
I'm unable to replicate.

**Comment by dizel852** [comment]
Wasn't able to repro it, probably the issue is fixed.
