### ISSUE TITLE
Source AHA.io -  adding source issue with lower plans

### ISSUE THREAD

**Issue by Upgreydd** [airbytehq/airbyte#22645]
## Environment
- **Airbyte version**:  v0.40.32
- **OS Version / Instance**: AWS EC2
- **Deployment**: docker
- **Source Connector and version**: aha.io 1.0.0
- **Step where error happened**: Setup new connection

## Current Behavior
*Tell us what happens.*
When creating aha.io integration on a lower plan then it fails to add integration with a good API key. The reason is airbyte checks the connection while adding integration based on the first element on the streams list. In this case stream name is `features`. `features` and `goals` are not available in lower plans so checking connection based on `features` fails. Changing order in `check -> stream_names` fix the issue. I propose to use `products` as a first element in the list.

## Expected Behavior
Possible to add aha.io source

## Steps to Reproduce
1. Take lower plana aha.io API where's no goals and features available
2. Try to add connector

## Are you willing to submit a PR?
I already did: https://github.com/airbytehq/airbyte/pull/22475

**Comment by topefolorunso** [comment]
This has been fixed here https://github.com/airbytehq/airbyte/pull/26666 @justinbchau
