### ISSUE TITLE
OSS & Cloud Platform no longer consumes actor definitions yamls

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#22653]
As part of the monorepo project, the platform codebase and the connectors will be moved into different Github repos. As part of this switch, the OSS platform should moved to consume the published [JSON Connector Catalog](https://storage.googleapis.com/prod-airbyte-cloud-connector-metadata-service/oss_catalog.json) rather than [`source_definitions.yaml`](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml) and [`destination_definitions.yaml`](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/destination_definitions.yaml) yaml files (nor should it use the `destination_specs.yaml` or `source_specs.yaml`).  

The JSON Connector Catalog is already built and published any time a connector change is merged to master - for both OSS and Cloud.  This will continue to work after the monorepo switch.

There are 3 parts to this story.
1. At build time, download the latest version of `oss_catalog.json` and store it within the platform docker images so it is available a fallback for air-gapped users.  @cpdeethree started this work in https://github.com/airbytehq/airbyte/pull/22376. 
2. At boot (`airbyte-bootloader`) will load in new versions of the connectors via [`LocalDefinitionsProvider`](https://github.com/airbytehq/airbyte/blob/evan/docker-snyk/airbyte-config/init/src/main/java/io/airbyte/config/init/LocalDefinitionsProvider.java#L17).  We only reference the local versions of files at boot, so we can continue to do this.  Instead of loading the YAMLs, this class should be changed to load from the local copy of the JSON which was download in step 1.
    * Note: There is a `RemoteDefinitionsProvider`, but that's only used to generate the JSON catalog today (`CombinedConnectorCatalogGenerator`).  We don't use this at application boot.
    * Remove [`AirbyteGithubStore`](https://github.com/airbytehq/airbyte/blob/master/airbyte-commons-server/src/main/java/io/airbyte/commons/server/services/AirbyteGithubStore.java#L31).  This is currently in use for the /settings page to load what the "latest" oss connector are.  We should change this to use the `RemoteDefinitionsProvider`.
3. Airbyte Cloud may also has the same fallback in which if if can't reach it's GCS connector catalog, it will also look at it's local version of the connector YAML definitions (which are moving away).  For Airbyte Cloud, if the `RemoveDefinitionsProvider` cannot be found, we should throw an error (Cloud should _always_ be able to reach GCS). 
    * Investigate if this is the case and make this change if needed.

Also, as part of this work, @cpdeethree is going to give us a fancy subdomain to front the JSON connector catalog file with.  Use this, and not the path to the direct GCS bucket/file - this will help us move the file in the future if needed.

Closes https://github.com/airbytehq/monorepo/issues/7

**Comment by bnchrch** [comment]
Placing this here so other can follow along.

I put together a diagram for my own knowledge [here]( https://whimsical.com/connector-release-flow-YCELhfNKfH9YtkV6eucj7J) and to have a better understanding of the system to avoid unexpected issues on release.

**_Warning there is serious [Charlie Day vibes](https://media.tenor.com/4LvAD8hD5tcAAAAM/charlie-day.gif) inside._**


My current plan of attack as far as individual PR's go are

- [ ] At build time download `oss_platform.json`
- [ ] Update LocalDefinitionsProvider to reference `oss_catalog.json` instead of the underlying yaml
- [ ] Replace AirbyteGithubStore with Remote Definitions Provider
