### ISSUE TITLE
[Low-Code CDK] Connector commands should fail when the low-code manifest version does not match the current airbyte-cdk version

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#22668]
## Problem

Source connectors are versioned independently from one another using the version specified in setup.py A simple way of ensuring that the defined manifest is always running on a compatible version of the low-code framework version is to compare them against each other when processing a connector operation. At runtime, after parsing the manifest, we can compare the airbyte-cdk major version (which adheres to semantic versioning) against the one defined on the manifest’s version field.

## Solution

Low-code manifests specify under the `version` field what major version of the low code CDK is being run. When attempting to parse a declarative low-code manifest, we should verify that the major version matches the version of the `airbyte-cdk` package that is being run. The reason why we are gating on major version is because in a low-code connectors `setup.py` we pin to the major but get the latest minor + patch at all times which fits with the paradigm of a specified major version in the manifest.

If the major versions do not match, then we should throw an error.

We can use the `from importlib.metadata import version` which is a built in Python library to derive the running version because we're on Python 3.9.

## Acceptance Criteria

- [ ] Running a connector whose major  matches the version specified in `setup.py` should run `spec` + `read` correctly
- [ ] Runnng a connect whose major version specified in `setup.py` should fail w/ an error when `spec` is run
- [ ] The flow should work when running a sync where the connector is build against the local version of the CDK (though this should already work)

**Comment by flash1293** [comment]
We are currently still on `0.x` which does contain breaking changes so implementing this as proposed will not have any effect until we published `1.0` while still leaving the potential for breaking changes.

We did all of our planned breaking changes in `0.29`, what about introducing a check to see whether a manifest is before or after this threshold and fail on that?

Another thing that's not covered is if the manifest is referencing a higher version than the CDK - as the manifest schema is not forward compatible, this could break behavior.

The check would be if the version in the manifest is `>= 0.29` and `<= {CURRENT_VERSION}` and fail if that's not the case.

Once we have a `1.0`, we can switch to the proposed check whether the major version matches plus `<= {CURRENT_VERSION}` as we don't guarantee forward compatibility.
