### ISSUE TITLE
Missing STRICT_COMPARISON_NORMALIZATION_WORKSPACES and STRICT_COMPARISON_NORMALIZATION_TAG from configmap helm chart

### ISSUE THREAD

**Issue by Utwo** [airbytehq/airbyte#22687]
## Environment
- **Airbyte version**:  helm-chart-0.43.33
- **OS Version / Instance**: GCP
- **Deployment**: Kubernetes

## Current Behavior
When I'm trying to install airbyte using the Helm Chart I get an error that `STRICT_COMPARISON_NORMALIZATION_TAG` and `STRICT_COMPARISON_NORMALIZATION_WORKSPACES` are missing from configmap airbyte/airbyte-airbyte-env but required by airbyte-worker.

## Expected Behavior
Helm chart should be installed successfully.

## Steps to Reproduce
Install the helm chart 0.43.33 with the default values.
Check the worker deployment.
```
$ kubectl describe deployment airbyte-worker
```
You should see an error similar to:
```
couldn't find key STRICT_COMPARISON_NORMALIZATION_TAG in ConfigMap airbyte/airbyte-airbyte-env
```

## Are you willing to submit a PR?
Of course

**Comment by yuriolive** [comment]
Having the same issue here.

**Comment by yuriolive** [comment]
Temporary solution is to use Helm chart version **0.43.29**
