### ISSUE TITLE
Source Helpscout: New Sandbox

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#22686]
Need a new sandbox for this new connector merged from here: https://github.com/airbytehq/airbyte/pull/21489

**Comment by igrankova** [comment]
We have a sandbox in the LastPass: helpscout.net, but it is expired. I've sent a Sandbox Request to the support team, maybe we could restore it or get a new one. I'll let know about the results.

**Comment by igrankova** [comment]
Created an account, LastPass name: HelpScout Primary Dev Account
Created app.

**Comment by igrankova** [comment]
we received the **developer account promotion** plan on the Helpscout account.
The details from the support:
_With this promo, you are limited to 3 Users for that account and it should only be used for the purpose of integration development, testing, and demonstrations.
Please note that a charge will be applied to the account if the number of Users is exceeded or if the account is used for any other purpose. If a charge is incurred for one of the reasons above, a credit card will be required to keep the account active._
