### ISSUE TITLE
Destination Weaviate: Store original ID as a property

### ISSUE THREAD

**Issue by samos123** [airbytehq/airbyte#22685]
Currently a string ID will get hashed into md5 and then converted into UUID because Weaviate only supports UUID based IDs. However, Weaviate users will need the original ID to create cross references between classes. So the original ID should be stored as a property.

Please assign this issue to me @samos123

**Comment by natalyjazzviolin** [comment]
@samos123 please edit your initial comment using the issue template. Closing for now.
