### ISSUE TITLE
Facebook source with a new api version v16.0

### ISSUE THREAD

**Issue by eduardo-menezes** [airbytehq/airbyte#22698]
I'm getting the following problem. Anything about it? 

Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v15.0/act_XXXX/
  Params:  {}
  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) Your app has been upgraded to version v16.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.",
        "type": "OAuthException",
        "code": 263
}

![image](https://user-images.githubusercontent.com/47368400/218013885-14982f8e-c187-42b7-ac34-d030718ff316.png)

Even when a set the api version it is not able to connect.

![image](https://user-images.githubusercontent.com/47368400/218014731-431f43e7-1b11-4deb-8760-683f6d9b2d6a.png)

**Comment by pablo-espeso** [comment]
I've been also dealing with this FacebookAPIException error for the last few days with a new Facebook app we are testing, but this issue is duplicated as it is already opened in #22549.

As of today, the Facebook connector seems unusable until a new version is released.

**Comment by sajarin** [comment]
Thanks for the issue, closing due to duplicate
