### ISSUE TITLE
Error checking out code

### ISSUE THREAD

**Issue by danths** [airbytehq/airbyte#2271]
Cloning into 'D:\XXX\git\GitHub\airbyte'...
remote: Enumerating objects: 215, done.        
remote: Counting objects: 100% (215/215), done.        
remote: Compressing objects: 100% (98/98), done.        
remote: Total 46024 (delta 94), reused 139 (delta 65), pack-reused 45809        
Receiving objects: 100% (46024/46024), 34.65 MiB | 12.21 MiB/s, done.
Resolving deltas: 100% (21256/21256), done.
**error: invalid path **'docs/faq/differences-with.../README.md'****
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by michel-tricot** [comment]
oh this is real bad. It means we have a bad casing in git. Let me check how we can fix it. I hope we can without re-writing history...

**Comment by michel-tricot** [comment]
@danths I tried to change the directory structure. can you try again?

**Comment by davinchia** [comment]
Drive-by: I blew my local repo away and successfully cloned the new repo this. This works for me.

**Comment by davinchia** [comment]
Closing this as stale. @danths please reopen if this issue still persist!
