### ISSUE TITLE
Source Jira: Mark datefields in properly as dates

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#22739]

**Comment by arsenlosenko** [comment]
changes for this issue were already made in scope of this PR:
https://github.com/airbytehq/airbyte/commit/a5bbbc3005c3ce89cceca236d991c35b08a64b47#diff-82ed7aab817cc5d670d55b4c17a77bc3a8654d473b68cb10027a6305548678d2R47
