### ISSUE TITLE
Source Postgres -> S3: Array contains a null element at 0

### ISSUE THREAD

**Issue by cesar-loadsmart** [airbytehq/airbyte#22807]
## Environment
- **Airbyte version**:  0.40.29
- **OS Version / Instance**: AWS EKS
- **Deployment**:  Kubernetes deploy
- **Source Connector and version**: source-postgres 1.0.42
- **Destination Connector and version**: S3 0.3.19
- **Step where error happened**: Running a connection between Postgres and S3

## Current Behavior
Airbyte runs smoothy for all tables except one, an error message is reported:
```
"internalMessage" : "java.lang.NullPointerException: Array contains a null element at 0. Set parquet.avro.write-old-list-structure=false to turn on support for arrays with null elements.",
"externalMessage" : "Something went wrong in the connector. See the logs for more details.",
```
I've also tested several destination configurations, doesn't matter the Encoding or Compact configuration, the problem persists.

## Expected Behavior
Airbyte should ingest this final table from this source, just like it is doing for other tables within the same database or among different databases.

## Logs
[26204905_8ef0_47c4_a86a_a3e8cc3950aa_logs_2363_txt.txt](https://github.com/airbytehq/airbyte/files/10707634/26204905_8ef0_47c4_a86a_a3e8cc3950aa_logs_2363_txt.txt)

## Steps to Reproduce
1. Create a source Postgres connection
2. Create an s3 destination (doesn't matter the Encoding or Compact configuration, the problem persists).
3. Create a table with a similar structure:
![image](https://user-images.githubusercontent.com/89807801/218097196-3a04382b-4325-4b5e-a57a-a9091d75925a.png)
4. Run the connection and check the error. 

## Are you willing to submit a PR?
Sure! I would love to.

**Comment by marcosmarxm** [comment]
Thanks @cesar-loadsmart the issue was added to connector roadmap.

**Comment by VitaliiMaltsev** [comment]
Valid steps to reproduce:

1. Create a source Postgres connection
2. Create an s3 destination (Parquet).
3. Create a table and populate with a following queries:
```
CREATE TABLE test_pg_array(id INTEGER PRIMARY KEY, test_column varchar []);
INSERT INTO test_pg_array values (1, '{"test_string", null}');
```
4. Run sync

This issue is persists due to org.apache.parquet.hadoop.ParquetWriter can not handle arrays with null elements

@grishick tagging you since this issue should be handled by the destinations team

**Comment by grishick** [comment]
This error message has a hint to how this can be fixed:
`"internalMessage" : "java.lang.NullPointerException: Array contains a null element at 0. Set parquet.avro.write-old-list-structure=false to turn on support for arrays with null elements.",
`

**Comment by etsybaev** [comment]
It seems like the supposed straight forward approach from logs "Set parquet.avro.write-old-list-structure=false to turn on support for arrays with null elements.", doesn't work. Whatever I tried to set - just ignored and it keeps fails

**Comment by cesar-loadsmart** [comment]
Hey folks! 

I saw that you merged a PR, just updating my Postgres Connector will contemplate your solution?

If not, how can I get it?

![image](https://user-images.githubusercontent.com/89807801/226423628-c43a7385-199d-44ef-8fe5-8772386e5a32.png)
