### ISSUE TITLE
Source Facebook Marketing: populate Ads Insight stream

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#22816]
We need some data in the `Ads Insights` stream of the `Facebook Marketing` source to unblock the oncall issue. This data must include `conversions`, `conversion_values`, `cost_per_conversion` fields with values in at least one record.

**Comment by YowanR** [comment]
@davydov-d which on-call issue is this for?

**Comment by davydov-d** [comment]
@YowanR this one https://github.com/airbytehq/oncall/issues/1240

**Comment by igrankova** [comment]
@YowanR can't create or edit ads - no permissions, see the screenshot
![Facebook Marketing permissions](https://user-images.githubusercontent.com/87977540/220112821-f87843db-4f21-4c14-a6a8-d5fcc05d3973.png)

**Comment by igrankova** [comment]
@YowanR,
Found out that we need to configure the Pixel on our web-site to get leads. 
In our Ad the pixel is not activated:
![image](https://user-images.githubusercontent.com/87977540/224711808-9c6b0c51-d963-4017-a491-f843dec75986.png)
It means we need to add the code to our web-site with this Pixel to make Facebook identify that the user who clicked our Ad was redirected on our web-site. This is the code we prepared for it:
[Pixel.txt](https://github.com/airbytehq/airbyte/files/10957715/Pixel.txt)
The [Docs](https://blog.hootsuite.com/facebook-pixel/) describes the steps to configure the Ad.

**Comment by YowanR** [comment]
I'm following up with @ilana-airbyte here

**Comment by nataliekwong** [comment]
@igrankova Can you try testing the conversion now to see it it appears in Facebook? I have added the pixel.txt to fire anytime someone sees the facebook ad and then visits our homepage.

**Comment by igrankova** [comment]
@nataliekwong I don't have a new password, on the LastPass there's an expired one. Can't authorize to test it.

**Comment by igrankova** [comment]
@nataliekwong conversions are empty:
![image](https://user-images.githubusercontent.com/87977540/231496703-f063fcf7-0dc0-4465-959e-7269660367fb.png)

**Comment by nataliekwong** [comment]
@igrankova Are you saying there are conversions in Facebook, but not moving through Airbyte and therefore there is a gap with Airbyte? Or that Facebook does not record any conversions?

**Comment by igrankova** [comment]
@nataliekwong Facebook does not record any conversions.

**Comment by igrankova** [comment]
@nataliekwong the campaign was created by Yowan, it was set up for 3 days only, 2 of them - weekend. I saw several likes in the instagram and facebook account, tried to click, but it didn't redirect me on Aitbyte.com. As far as I know the campaign wasn't prolonged for more days and I don't have permissions to update it. 
![image](https://user-images.githubusercontent.com/87977540/231979860-308c5c8d-6800-4720-94f3-6ca1829d0a6e.png)
![image](https://user-images.githubusercontent.com/87977540/231980062-268e81a7-a186-4549-92d9-5e6d15bd16fd.png)

**Comment by midavadim** [comment]
Data has been populated
