### ISSUE TITLE
Invalid / saving / saved indicator for auto-saving

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22828]
Related to issue https://github.com/airbytehq/airbyte/issues/22446

It should always be clear to the user whether the current draft is saved already, is currently in progress of saving or is currently invalid and can't be saved

**Comment by Upmitt** [comment]
You can see the different status by clicking on "saved draft" on this prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3697%3A128255&node-id=3712%3A128033&viewport=-2853%2C1130%2C0.5&scaling=min-zoom&starting-point-node-id=3712%3A130280 - it also work in YAML view

**Comment by flash1293** [comment]
Done and implemented
