### ISSUE TITLE
Configure name in yaml mode

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#22836]
Related issue: #22467

It should be possible to see and edit the name of a connector even if the user is currently in yaml mode

**Comment by Upmitt** [comment]
You can click on the connector name in this prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3697%3A128255&node-id=3901%3A130960&viewport=-2853%2C1130%2C0.5&scaling=min-zoom&starting-point-node-id=3712%3A130280
