### ISSUE TITLE
Add a field to input a sync/connection name

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2285]
## Tell us about the problem you're trying to solve
On the Sync/connection page, the user needs to type and input a name for the connection/sync.

This name can be used as a prefix to the stream name when destinations are outputting the sync data to avoid conflicts as described in #1921. However, this is an intermediate solution (used as a prefix)

In the future, this namespace field will actually define the final namespace where the destination will write data to.

So if I have setup:
- a Postgres source replicating table "table_name" from "schema_name"
- a BigQuery destination with final destination schema "airbyte_data"
- a connection named "my_connection"

The data will be synced and written to:
- Bigquery dataset "airbyte_data" 
- table named "my_connection_schema_name_table_name"

After implementations of #1921, it will be written to (this depends on other tickets that need to be better scoped/defined):
- Bigquery dataset "my_connection_schema_name" 
- or Bigquery dataset "my_connection" (depending on if the user choose to keep the source schema in the destination naming or not)
- table named "table_name"
- The destination schema "airbyte_data" will be removed from the destination settings

## Describe the solution you’d like
- A new text field to write a sync name (using alpha numeric and `_` characters only preferably) 
- This new field should be read/written in the connectionCreate / connectionUpdate / connectionRead objects (we'll transfer copy it over to StandardSync objects in the backend)

**Comment by cgardens** [comment]
Before we pass this artem, @ChristopheDuong can you:
1. make sure we have a mock up for this. You can work with @johnlafleur to get this done.
2. specify where the information that is relevant for this issue will be read and written in the API? essentially how is the UI getting this info and where is it posting it?

**Comment by ChristopheDuong** [comment]
@johnlafleur can confirm but there was this mock up, right?

For this ticket, the field that is needed is the "Namespace Prefix":

![Screenshot 2021-03-03 at 18 30 06](https://user-images.githubusercontent.com/7718175/109846556-9a1fca00-7c4e-11eb-8510-76edea814171.png)

https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A296

**Comment by cgardens** [comment]
@Jamakase for now we will only do the namespace prefix part. The other changes we will address in a separate issue. We are splitting it because the name space prefix part is pretty high priority while the other stuff is not.

**Comment by johnlafleur** [comment]
Yup, that's the design!

**Comment by ChristopheDuong** [comment]
This is a PR still in draft but it introduces the new field "connectionName" where we could store this new field to
https://github.com/airbytehq/airbyte/pull/2298
