### ISSUE TITLE
Source Adwords: Failing CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2288]
Source Adwords is [repeatedly failing CI](https://docs.airbyte.io/integrations/connector-health). This ticket is to identify the issue and implement a solution.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093226270) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
I checked Google Adwords CI failing logs and found out that syncing failed on report streams. I reproduced  same behavior when run reading command:
{"type": "LOG", "log": {"level": "ERROR", "message": "CRITICAL Type: RateExceededError.RATE_EXCEEDED\n"}}
{"type": "LOG", "log": {"level": "ERROR", "message": "Trigger: Basic Access Daily Reporting Quota\n"}}
According to [documentation](https://developers.google.com/adwords/api/docs/guides/rate-limits) there are two types of access levels: Basic and Standard. A Basic access level account has limits of 1,000 report downloads per day.

**Comment by vitaliizazmic** [comment]
- [Fri Mar 12 01:31:18 UTC 2021](https://github.com/airbytehq/airbyte/runs/2091368409?check_suite_focus=true#step:10:4323)
- [Fri Mar 12 00:53:25 UTC 2021](https://github.com/airbytehq/airbyte/runs/2091183091?check_suite_focus=true#step:10:4314)
- [Fri Mar 12 00:22:31 UTC 2021](https://github.com/airbytehq/airbyte/runs/2091001056?check_suite_focus=true#step:10:4730)
- [Thu Mar 11 23:58:10 UTC 2021](https://github.com/airbytehq/airbyte/runs/2090853221?check_suite_focus=true#step:10:3918)
- [Thu Mar 11 06:34:29 UTC 2021](https://github.com/airbytehq/airbyte/runs/2083780304?check_suite_focus=true#step:10:3933)

**Comment by sherifnada** [comment]
Thanks @vitaliizazmic -- I've applied for Standard Access to the Google Adwords API and will follow up if I hear anything back.

**Comment by sherifnada** [comment]
Our rate limit increase request has been granted!
