### ISSUE TITLE
Source greenhouse: failing CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2289]
The greenhouse source is [repeatedly failing CI](https://docs.airbyte.io/integrations/connector-health). This issue is to understand the problem and implement a fix.

**Comment by vitaliizazmic** [comment]
@sherifnada I checked Greenhouse CI failing logs and found out that Greenhouse API return "Invalid Basic Auth credentials" errors while syncing. I reproduced same behavior when run reading command:
grnhse.exceptions.HTTPError: 401 ***"message":"Invalid Basic Auth credentials"***

E.g. [Fri Mar 12 00:13:44 UTC 2021 ](https://github.com/airbytehq/airbyte/runs/2091001815?check_suite_focus=true#step:10:3310)

I tried to restore api_token via integration-test@airbyte.io account, but after sign in got next error:
"Sorry, your organization is disabled.
Your free trial expired.
Email us if you would like help."

**Comment by sherifnada** [comment]
@vitaliizazmic I reached out to Greenhouse.

**Comment by arhip11** [comment]
Hey @sherifnada! Should I send partnership request to Greenhouse from zazmic.com email address?
(I can't send as or setup reply-to: integration-test@airbyte.io).

**Comment by sherifnada** [comment]
@arhip11 great question. I created an Airbyte email address for you titled `Sasha's airbyte email` in Lastpass and added it to the `integration-test@airbyte.io` email address

**Comment by arhip11** [comment]
I have contacted Partnerships support

**Comment by sherifnada** [comment]
thanks @arhip11

**Comment by arhip11** [comment]
@vitaliizazmic - can you please confirm that Greenhouse is working?

**Comment by vitaliizazmic** [comment]
@arhip11 it works. I've [created](https://support.greenhouse.io/hc/en-us/articles/115000521723-Manage-Harvest-API-key-permissions) new token and updated lastpass creds. But we also should update creds for Github CI.

**Comment by sherifnada** [comment]
@vitaliizazmic I've updated the Github CI creds. can you publish a new version of this connector?
