### ISSUE TITLE
🐛 Source Stripe: Missing field cancel_at in Stripe connector

### ISSUE THREAD

**Issue by mrhallak** [airbytehq/airbyte#22897]
## Environment
- **Airbyte version**: 0.40.26
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker-compose
- **Source Connector and version**: Stripe (1.0.1)
- **Destination Connector and version**: Snowflake (0.4.47)
- **Step where error happened**: Sync job

## Current Behavior
The `cancel_at` field from the subscriptions stream doesn't exist in the final tables, it only exists as part of the JSON fetched from Stripe.

**Note**: This field is not the same as the `canceled_at` field

<img width="894" alt="Screenshot 2023-02-13 at 12 53 40" src="https://user-images.githubusercontent.com/16711801/218451080-6d208406-ba26-4b6b-bb18-d102d009f9a8.png">

The field also doesn't show on the Airbyte UI.

## Expected Behavior
The `cancel_at` field should be present in the final table and be shown on the Airbyte UI.
<img width="646" alt="Screenshot 2023-02-13 at 13 11 51" src="https://user-images.githubusercontent.com/16711801/218454602-ccec9171-7395-4248-ad56-c5dcaed12bdf.png">

## Logs
The operation is not failing

## Steps to Reproduce
1. Run a sync for the subscriptions stream

## Are you willing to submit a PR?
Done https://github.com/airbytehq/airbyte/pull/22898

**Comment by sajarin** [comment]
Thanks for the PR and the issue here @mrhallak someone will review it soon!

**Comment by sergio-ropero** [comment]
@sajarin Coul you ping someone to review it?
The PR looks so simple although it has conflicts.

@mrhallak Could you review the conflicts or rebase from latest state of `master` branch?

**Comment by mrhallak** [comment]
Hey @sergio-ropero fixed the conflicts, thanks 🙌🏻
