### ISSUE TITLE
Source Mixpanel: Failing CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2291]
## Expected Behavior
Source mixpanel is [repeatedly failing CI. ](https://docs.airbyte.io/integrations/connector-health). This issue is to implement a fix.

**Comment by vitaliizazmic** [comment]
@sherifnada  Mixpanel API returns "Date range exceeds 90 days into the past" error while syncing only Annotation Stream. For Revenue Stream all works properly. I can either add checking for start date config option or set custom start date for Annotation stream.  In first case date range will be restricted for all streams. In second case it is required change Singer Tap and create fork.

**Comment by sherifnada** [comment]
@vitaliizazmic could you create a ticket for this task so we can track separately?
