### ISSUE TITLE
Source Instagram: user_lifetime_insights stream fails due to KeyError: 'end_time'

### ISSUE THREAD

**Issue by phani2410** [airbytehq/airbyte#22929]
## Environment
- **Source Connector and version**: Instagram - 1.0.1
- **Step where error happened**:  Sync job 

## Current Behavior
When a connection is created and data sync is triggered. While streaming ```user_lifetime_insights``` the sync job fails because the stream records are expected to have end_time field present. But  as per the [documentation](https://developers.facebook.com/docs/instagram-api/guides/insights/), lifetime insights wouldn't have that field. Hence, its throwing an error and job fails.

## Expected Behavior
That field should not be parsed from the graph api response, instead the datetime at which the record was fetched, that can be used as end_time.

## Logs
Yes. 
[workspace_logs_117_txt.txt](https://github.com/airbytehq/airbyte/files/10723482/workspace_logs_117_txt.txt)

## Steps to Reproduce
1. Create a connection for instagram ads.
2. Make sure user_lifetime_insights stream is selected for sync.
3. Sync the data. 
4. You will see the sync failing when it tries to sync the user_lifetime_insights stream.

## Are you willing to submit a PR?
Yes. 
https://github.com/airbytehq/airbyte/pull/22928

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @phani2410 I'll take a look in your PR later this week!
