### ISSUE TITLE
Source Bing Ads - No rollback window for conversions 

### ISSUE THREAD

**Issue by thibault-latrace** [airbytehq/airbyte#22930]
## Environment
- **Airbyte version**:  0.39.42-alpha
- **OS Version / Instance**: AWS EC2 (Amazon Linux)
- **Deployment**: Docker
- **Source Connector and version**: Bing Ads 0.1.16
- **Step where error happened**: connector behaviour

## Current Behavior
There are data discrepancies on a few fields between Bing Ads API and Bing Ads data ingested on our data warehouse (BigQuery) through the Airbyte stream `ad_group_performance_report_daily`. The concerned fields are related to _conversions_ marketing concept (see _References_ section to learn more about marketing conversions):

- `AllConversions`
- `Conversions`
- `ConversionsQualified`

The ingested data reported **fewer conversions** than the one reported on Bing Ads API.

## Expected Behavior
Conversion field values are accurate. They are the same as the one of the API.

## Logs
I don't have any relevant logs to provide. The job succeeds but its behavior is not the one expected.

## Steps to Reproduce
1. Setup Bing Ads source (_Replication start date_ set to `2022-01-01`)
2. Setup BigQuery destination (_Loading method_ set to `Standard Inserts` & _Transformation Query Run Type_ set to `batch`)
3. Setup the connector (_Replication frequency_ set to `24 hours`) by enabling stream `ad_group_performance_report_daily` in `Incremental | Deduped + history` mode with `TimePeriod` as cursor field (for the record, this field has a daily granularity)
4. Setup conversion window of 30 days on Bing Ads UI

## Explanations
I deep-dived into Bing Ads and Airbyte documentation to find the issue's root cause and I came up with an explanation for the unexpected behavior.

In short, the **cursor field** is not appropriately implemented as it doesn't have any **rollback window** to take into account conversions that could happen during the attribution window.

### Example

Initial state:
- Attribution window: 30 days
- `TimePeriod` cursor field value: `15/10/2022`

Event:
- A conversion related to `5/10/2022` happens on `20/10/2022`. As the conversion happens within the 30 days attribution window, it should be counted for the day `5/10/2022`. The `conversions` field value for the date `5/10/2022` should be incremented by 1 after the next job run.

Job run:
- Run date: `25/10/2022`
- As `TimePeriod` cursor field value is set `15/10/2022`, only data with a `TimePeriod` after `15/10/2022` (included) will be ingested. The rest will be skipped, e.g. data from `5/10/2022`. So the conversion related to `5/10/2022` which happened on the `20/10/2022` won't be counted.

### Conclusion

If a marketing conversion related to a `TimePeriod` before the cursor field value happens after the cursor field value, this conversion is currently not taken into account.

## Note

A similar conversion issue pattern has already been reported and fixed on Twilio Source. See the history of its [source.py file](https://github.com/airbytehq/airbyte/blob/d32cec811331e280a46dcb01fdeef153e8d86379/airbyte-integrations/connectors/source-twilio/source_twilio/source.py#L57) for more information.

## References
- [About Bing Ads conversions](https://help.ads.microsoft.com/#apex/ads/en/56710/2)
- [Airbyte incremental sync](https://docs.airbyte.com/connector-development/tutorials/cdk-tutorial-python-http/read-data/)
- [Twilio source connector with implemented rollback window](https://github.com/airbytehq/airbyte/blob/d32cec811331e280a46dcb01fdeef153e8d86379/airbyte-integrations/connectors/source-twilio/source_twilio/source.py#L57)

## Are you willing to submit a PR?
Yes.

**Comment by YowanR** [comment]
Thanks @thibault-latrace for looking into this! We would love to see a PR from you to fix this issue! Looking forward to your contribution!

**Comment by tlatrace** [comment]
Hey @YowanR 👋  Here is the [PR](https://github.com/airbytehq/airbyte/pull/23663) fixing the bug

**Comment by thibault-latrace** [comment]
Fixed by #25259 (original PR: #23663)
