### ISSUE TITLE
Source Tempo: failing CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2295]
## Expected Behavior
Source Tempo is [repeatedly failing CI](https://status-api.airbyte.io/tests/summary/source-tempo/). This issue is to find the problem and implement a fix.

**Comment by vitaliizazmic** [comment]
@sherifnada Api token expired. I'v generated new one. It was updated in lastpass and for CI. After this CI tests was successful

**Comment by sherifnada** [comment]
@vitaliizazmic SGTM -- why is the ticket marked as blocked?

**Comment by sherifnada** [comment]
@vitaliizazmic can you create a bogus branch to publish the connector? there have been updates to the codebase that required publishing a new version but because CI was failing we couldn't publish.
