### ISSUE TITLE
Source Postgres: Integer fields being written as strings in JSONL data after Protocol V1 upgrade

### ISSUE THREAD

**Issue by blarghmatey** [airbytehq/airbyte#22951]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: AWS EC2 running Debian 11
- **Deployment**: Docker Compose
- **Source Connector and version**: Postgres 1.0.44
- **Destination Connector and version**: S3-Glue 0.1.2
- **Step where error happened**: Sync Job

## Current Behavior
Integer fields that are properly identified in the replication configuration are being written as quoted strings in the JSON files that are generated from the sync job. This only happens after upgrading from 0.40.30 -> 0.40.32 which includes the upgrade to Airbyte Protocol v1

## Expected Behavior
The fields in the replicated stream should have the proper data types in the JSON data that is written to the generated files. In particular, integer fields should not be quoted as strings.

## Logs
There are no error events because the sync job succeeds but the generated data is incorrect.

## Steps to Reproduce
Configure any connection that contains integer fields to write to an S3 JSONL destination running on Airbyte > 0.40.30. Read the records in the generated JSON files and see that the integers are written as JSON strings.

## Are you willing to submit a PR?
I am willing to submit a PR if someone can point me at a likely location where the invalid logic is occurring.

**Comment by evantahler** [comment]
Is this problem still occuring?

**Comment by blarghmatey** [comment]
I am not seeing it happen on my instance running v0.44.4, but I believe that is because the protocol change was reverted. I haven't checked to see if it was reimplemented.

**Comment by evantahler** [comment]
Yep! We reverted the dataatype change
