### ISSUE TITLE
Define connector builder's interface with the CDK

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#22961]
## Tell us about the problem you're trying to solve
Define the interface for the connector builder implemented in Java to interact with the Python CDK. 

The [tech spec](https://docs.google.com/document/d/1qt_g_V4_J2YDaDBwtRoJc23rCcYKZP9vzxWUh1Vqi3Q/edit#heading=h.wmqojg8r6rsh) loosely defines what the interface should look like, but the implementation is very much up in the air.

## Describe the solution you’d like
- The interface must be based off AirbyteMessages
- The same entrypoint.py should be used for Sources, Destinations, and the connector builder. This will involve some refactoring
  - Currently: sources use the [CDK's entrypoint.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/entrypoint.py) and the destination's run method is embedded in `Destination`
  - We should design this such that the Connector can defined the operations and the parameters that can be used for that one connector
- The entrypoint should use [Click](https://click.palletsprojects.com/en/8.1.x/) instead of argparse

Implementation note:
- The Java world only interfaces with Python using AirbyteMessage
- The existing types might not cover all our needs (eg we can't express requests, responses, and resolved manifests as airbyte messages). This might be a good time to introduce new types to the protocol https://github.com/airbytehq/airbyte/issues/18878 ?
- `infer_schema` and `list` should return an AirbyteMessage of type catalog

Sample commands for the connector builder:
```
@click.command()
@click.option('--manifest', help='The connector manifest')
@click.option('--config, help='The connection config)
@click.option('--streams, help='The names of the streams to read')
@click.option('--record-limit', default=1000, help='Maximum number of records to return')
@click.option('--slice-limit', default=5, help='Maximum number of stream slices to read')
@click.option('--page-limit', default=1000, help='Maximum number of pages to request')
@click.option('--state', default=None, help='Input state')
def read(manifest, record_limit, slice_limit, page_limit, state) -> Iterable[str]:
    pass

@click.command()
@click.option('--manifest', help='The connector manifest')
@click.option('--config, help='The connection config)
@click.option('--streams, help='The names of the streams to read')
@click.option('--record-limit', default=1000, help='Maximum number of records to return')
@click.option('--slice-limit', default=5, help='Maximum number of stream slices to read')
@click.option('--page-limit', default=1000, help='Maximum number of pages to request')
@click.option('--state', default=None, help='Input state')
def infer_schema(manifest, record_limit, slice_limit, page_limit, state) -> Iterable[str]:
    pass

@click.command()
@click.option('--manifest', help='The connector manifest')
@click.option('--config, help='The connection config')
def list_streams(manifest, config) -> Iterable[str]:
    pass

@click.command()
@click.option('--manifest', help='The connector manifest')
def manifest_resolve(manifest) -> Mapping[str, Any]:
    pass
```

Sample commands for destination
```
@click.command()
def spec():
    pass

@click.command()
@click.option('--config')
def check(config):
    pass

@click.command()
@click.option('--config')
@click.option('--catalog')
def write(config, catalog):
    pass
```

Sample commands for source:
```
@click.command()
def spec():
    pass

@click.command()
@click.option('--config')
def check(config):
    pass

@click.command()
@click.option('--config')
def discover(config):
    pass

@click.command()
@click.option('--config')
@click.option('--catalog')
@click.option('--state', required=False)
def discover(config, catalog, state):
    pass
```

## Dependency
- https://github.com/airbytehq/airbyte/issues/22438
  - this is the (partial) source connector the connector builder will use
  - Not a hard dependency, but we'll want to take this in mind during the design

## Acceptance criteria
- Groomed implementation issue (+ tech spec or spike as needed)
  - The CDK's entrypoint yields `AirbyteMessage`s
  - Sources, Destinations, and the connector builder share a unifed entrypoint
  - The new entrypoint uses [Click.py](https://click.palletsprojects.com/en/8.1.x/)
  - Requests and responses must not be persisted by the platform because they can contain user data

### Open questions
- Is it time to introduce new types to the protocol? (https://github.com/airbytehq/airbyte/issues/18878)

## Alternative
- turn this into an implementation issue with a high degree of uncertainty

**Comment by clnoll** [comment]
Tech spec in progress.
