### ISSUE TITLE
Destinations Databricks: Support SQL Warehouse

### ISSUE THREAD

**Issue by plenti-jacob-roe** [airbytehq/airbyte#22962]
## Tell us about the problem you're trying to solve
Currently we are running on a older version of the databricks connector as it supported sql warehouses in datarbricks as well as computer clusters. In our case it doesn't make sense to run a dedicated compute cluster for airbyte given the cost involved. 

## Describe the solution you’d like
We would like the public databricks connector to support both compute custers and sql warehouses as per the databricks jdbc documentation https://docs.databricks.com/integrations/jdbc-odbc-bi.html

## Describe the alternative you’ve considered or used
As of now we are stuck using a out of data version of the databricks connector from before it was publicly available. https://github.com/airbytehq/airbyte/issues/6043 

## Are you willing to submit a PR?
I am unable to submit a PR at this time

**Comment by evantahler** [comment]
Closing as not something we will support.
