### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /opt/airbyte/flags.yml

### ISSUE THREAD

**Issue by geekyouth** [airbytehq/airbyte#22971]
## Environment
- **Airbyte version**:  0.40.32 | 0.40.31
- **OS Version / Instance**: Centos7
- **Deployment**: Docker
...
...
- **Step where error happened**:  
```
git clone https://github.com/airbytehq/airbyte.git
cd airbyte
docker compose up -d; docker compose logs -f
```

## Current Behavior
*Tell us what happens.*

```
[+] Running 10/10
 ⠿ Network airbyte_airbyte_internal            Created                                                                                                                                                   0.2s
 ⠿ Network airbyte_default                     Created                                                                                                                                                   0.3s
 ⠿ Network airbyte_airbyte_public              Created                                                                                                                                                   0.2s
 ⠿ Volume "airbyte_workspace"                  Created                                                                                                                                                   0.0s
 ⠿ Volume "airbyte_data"                       Created                                                                                                                                                   0.0s
 ⠿ Volume "airbyte_db"                         Created                                                                                                                                                   0.0s
 ⠿ Container airbyte-db                        Created                                                                                                                                                   0.2s
 ⠿ Container airbyte-temporal                  Created                                                                                                                                                   0.2s
 ⠿ Container init                              Created                                                                                                                                                   0.2s
 ⠿ Container airbyte-bootloader                Created                                                                                                                                                   0.1s
 ⠋ Container airbyte-webapp                    Creating                                                                                                                                                  0.0s
 ⠋ Container airbyte-server                    Creating                                                                                                                                                  0.0s
 ⠋ Container airbyte-connector-builder-server  Creating                                                                                                                                                  0.0s
 ⠋ Container airbyte-worker                    Creating                                                                                                                                                  0.0s
 ⠋ Container airbyte-cron                      Creating                                                                                                                                                  0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /opt/airbyte/flags.yml
WARN[0000] The "NEW_SCHEDULER" variable is not set. Defaulting to a blank string.
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string.
```

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by geekyouth** [comment]
0.40.28 boot done by docker compose.

**Comment by marcosmarxm** [comment]
This was fixed in https://github.com/airbytehq/airbyte/issues/22144
The current path is: https://github.com/airbytehq/airbyte/blob/f93fa724aeb25036bf7088482ab755433c5a4fc5/docker-compose.yaml#L284-L286

**Comment by pcooper19** [comment]
Airbyte version: 0.44.4
OS Version / Instance: 22.04.2 LTS (Jammy Jellyfish)
Deployment: Shell script 
...
...
Step where error happened:

root@0ba297d0125f:/airbyte/airbyte# ./run-ab-platform.sh 


 █████╗ ██╗██████╗ ██████╗ ██╗   ██╗████████╗███████╗
██╔══██╗██║██╔══██╗██╔══██╗╚██╗ ██╔╝╚══██╔══╝██╔════╝
███████║██║██████╔╝██████╔╝ ╚████╔╝    ██║   █████╗  
██╔══██║██║██╔══██╗██╔══██╗  ╚██╔╝     ██║   ██╔══╝  
██║  ██║██║██║  ██║██████╔╝   ██║      ██║   ███████╗
╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝    ╚═╝      ╚═╝   ╚══════╝
                                            Move Data

Downloading docker-compose.yaml
Downloading docker-compose.debug.yaml
Downloading .env
Downloading .env.dev
Downloading flags.yml
Loading Shell Variables from .env...
Loading Shell Variables from .env.dev...

Starting Docker Compose
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REMOTE_CONNECTOR_CATALOG_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TEMPORAL_HISTORY_RETENTION_IN_DAYS" variable is not set. Defaulting to a blank string. 
WARN[0000] The "UPDATE_DEFINITIONS_CRON_ENABLED" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CDK_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PYTHON_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DEPLOYMENT_MODE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LOG_CONNECTOR_MESSAGES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "APPLY_FIELD_SELECTION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FIELD_SELECTION_WORKSPACES" variable is not set. Defaulting to a blank string. 
WARN[0000] The "NEW_SCHEDULER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SECRET_PERSISTENCE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JOB_ERROR_REPORTING_SENTRY_DSN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "WORKER_ENVIRONMENT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GITHUB_STORE_BRANCH" variable is not set. Defaulting to a blank string. 
[+] Running 87/22
 ✔ airbyte-temporal 21 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled              87.5s 
 ✔ worker 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                        132.9s 
 ✔ airbyte-proxy 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                          69.1s 
 ✔ airbyte-cron 1 layers [⣿]      0B/0B      Pulled                                      102.3s 
 ✔ server 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                     103.6s 
 ✔ db 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                          69.9s 
 ✔ airbyte-connector-builder-server 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled           55.0s 
 ✔ init 3 layers [⣿⣿⣿]      0B/0B      Pulled                                              3.4s 
 ✔ webapp 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                     43.8s 
 ✔ bootloader 1 layers [⣿]      0B/0B      Pulled                                        100.7s 
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
                                                                                                
[+] Running 7/7
 ✔ Volume "airbyte_data"                       Created                                     0.0s 
 ✔ Volume "airbyte_db"                         Created                                     0.0s 
 ✔ Volume "airbyte_workspace"                  Created                                     0.0s 
 ✔ Container init                              Created                                     0.6s 
 ✔ Container airbyte-temporal                  Created                                     0.6s 
 ✔ Container airbyte-db                        Created                                     0.6s 
 ✔ Container airbyte-bootloader                Created                                     0.3s 
 ⠋ Container airbyte-worker                    Creating                                    0.0s 
 ⠋ Container airbyte-server                    Creating                                    0.0s 
 ⠋ Container airbyte-webapp                    Creating                                    0.0s 
 ⠋ Container airbyte-cron                      Creating                                    0.0s 
 ⠋ Container airbyte-connector-builder-server  Creating                                    0.0s 
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /airbyte/airbyte/flags.yml

**Comment by marcosmarxm** [comment]
This is now outdated. Please use the latest version of the platform. If the problem continues, open a new issue.

**Comment by dan-r95** [comment]
For me this worked:
https://github.com/airbytehq/airbyte/issues/33845#issuecomment-2133715252
