### ISSUE TITLE
Update lowcode CDK demo video

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#23019]
### Tell us about the documentation you'd like us to add or update.
The video (commented out on [this page](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/config-based/connector-builder-ui.md)) currently references the old yaml-based UI whereas now we have the form-based connector builder. It should be re-recorded using the new UI.

**Comment by girarda** [comment]
closing as duplicate of https://github.com/airbytehq/airbyte/issues/24953
