### ISSUE TITLE
Allow deleting (or at least removing) dbt Cloud service token from workspace

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#23018]

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- We'll definitely pick up the frontend change ~immediately
- Implementation: post `{}` to the workspace webhook config table
- When a proper delete endpoints shows up, we'll use it

**Comment by ambirdsall** [comment]
This logic is written and working in https://github.com/airbytehq/airbyte-platform-internal/pull/4890; the only holdup is resolving some UI issues "upstream" of the http call that does the (pseudo-)deletion.
