### ISSUE TITLE
JSON objects separated in different columns in the resulting table

### ISSUE THREAD

**Issue by coquej** [airbytehq/airbyte#2301]
## Tell us about the problem you're trying to solve
When getting data from APIs (HTTP request connector) we can get information (in the destination) either normalized or not normalized, but we get the JSON object in only one column. Our team would like to have the results in a table with JSON data distributed in different columns.

## Describe the solution you’d like
For example, from the source we are receiving a JSON object like:
`{ 
   [
    "user": {
                   "name":"peter",
                    "id":"2342321x"
                 },
   "date":"20201201"
  ]
}`

We would like to have the possibility of receiving that information in a table with columns: user.name, user.id, date.

If my point is not clear, please ask.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368151085636) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
@coquej the normalisation is how the json data is distributed in different columns. Is there a reason you don't want to use it?

**Comment by coquej** [comment]
Hi @davinchia, this is an issue from more than a year ago, now we are using the normalization with json schema, so this is not a problem anymore. Thanks anyway! I'm clossing the issue.

**Comment by davinchia** [comment]
Thanks!
