### ISSUE TITLE
Source Salesforce - Unknown data type in stream 

### ISSUE THREAD

**Issue by shaidar** [airbytehq/airbyte#23025]
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**:  Salesforce 2.0.1
- **Destination Connector and version**: S3 Glue 0.1.2
- **Step where error happened**:  Sync job

## Current Behavior
Sync from Salesforce fails with the following stack trace:
```
  "stacktrace" : "java.lang.NullPointerException: Cannot invoke \"com.fasterxml.jackson.databind.JsonNode.get(String)\" because the return value of \"com.fasterxml.jackson.databind.JsonNode.get(String)\" is null\n\tat io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchemaRecursive(GlueOperations.java:138)\n\tat io.airbyte.integrations.destination.s3_glue.GlueOperations.lambda$transformSchema$0(GlueOperations.java:116)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)\n\tat java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat io.airbyte.integrations.destination.s3_glue.GlueOperations.transformSchema(GlueOperations.java:117)\n\tat io.airbyte.integrations.destination.s3_glue.GlueOperations.upsertTable(GlueOperations.java:87)\n\tat io.airbyte.integrations.destination.s3_glue.S3GlueConsumerFactory.lambda$onCloseFunction$3(S3GlueConsumerFactory.java:170)\n\tat io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9)\n\tat io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:227)\n\tat io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)\n\tat io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:149)\n\tat io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:98)\n\tat io.airbyte.integrations.destination.s3_glue.S3GlueDestination.main(S3GlueDestination.java:37)\n",
```
Upon further inspection of the data streams, noticed that the data type on some of the fields is `Unknown` which we suspect is the reason behind the above issue. Sifting through the Airbyte logs, noticed the following earlier error which is logged but doesn't interrupt the sync however I'm wondering whether that is what leads to the data type being labeled as `Unknown`:
```
2023-02-14 15:51:59 ERROR c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: Invalid timezone offset: +0000
```

## Expected Behavior
The sync runs through successfully.

## Logs
[7f17cc8d_2d97_454c_b840_e6711ba67cca_logs_1605_txt.txt.zip](https://github.com/airbytehq/airbyte/files/10736040/7f17cc8d_2d97_454c_b840_e6711ba67cca_logs_1605_txt.txt.zip)

## Steps to Reproduce
1. Setup an Airbyte connection using Salesforce as source and S3 Glue as destination
2. Run a sync

**Comment by arsenlosenko** [comment]
@shaidar Hi, I have tried to reproduce the issue you were having with Salesforce/S3 Glue sync on latest version of Salesforce connector, but didn't receive any errors related to date-time fields, right now it seems that this issue does not appear. 

Can you please test your sync again with latest version of Salesforce, and confirm if you still have this issue? Until then I'll close this issue for the time being, but if you are still having problems with the sync feel free to leave a message here.
