### ISSUE TITLE
Source Instagram: pull data from all IG business accounts linked to FB pages

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2304]
## Tell us about the problem you're trying to solve
We want the WIP IG source to pull data from all IG business accounts available to it. It should do this by looking at every FB Page linked to the input credentials, get every IG account ID linked to that page*, then sync data for every IG account available to it. 

I must be able to link the output data back to the instagram account which generated it i.e: an entry in the `users` table. 

*:  I'm not sure if an FB page can be linked to more than one IG business account. @yevhenii-ldv you might want to double check this.

**Comment by yevhenii-ldv** [comment]
@sherifnada, If I understood correctly, then [ this document](https://en-gb.facebook.com/business/help/345675946300334?id=419087378825961) says that a user can link only one Instagram Business Account to a Page, but he can create several Pages and link one Instagram Business Account to each.

We can get all Pages, and check each one for an Instagram Business Account.

**Comment by sherifnada** [comment]
Yup that's exactly right @yevhenii-ldv
