### ISSUE TITLE
Source: Gitlab

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2305]
## Tell us about the new integration you’d like to have
I'd like to be able to pull data from the [Gitlab API](https://docs.gitlab.com/ee/api/README.html). The main streams I need to pull from are: 

* [Branches](https://docs.gitlab.com/ee/api/branches.html)
* [Commits](https://docs.gitlab.com/ee/api/commits.html)
* [Issues](https://docs.gitlab.com/ee/api/issues.html)
* [Pipelines](https://docs.gitlab.com/ee/api/pipelines.html)
* [Jobs](https://docs.gitlab.com/ee/api/jobs.html)
* [Projects](https://docs.gitlab.com/ee/api/projects.html)
* [Project milestones](https://docs.gitlab.com/ee/api/milestones.html)
* [Project Merge Requests](https://docs.gitlab.com/ee/api/merge_requests.html)
* [Users](https://docs.gitlab.com/ee/api/users.html)
* [Groups](https://docs.gitlab.com/ee/api/group_milestones.html)
* [Group Milestones](https://docs.gitlab.com/ee/api/users.html)
* [Group and Project members](https://docs.gitlab.com/ee/api/members.html)
* [Tags](https://docs.gitlab.com/ee/api/tags.html)
* [Releases](https://docs.gitlab.com/ee/api/releases/index.html)
* [Group Labels](https://docs.gitlab.com/ee/api/group_labels.html)
* [Project Labels](https://docs.gitlab.com/ee/api/labels.html)

There seems to exist a good Singer tap [here](https://gitlab.com/meltano/tap-gitlab)  that we can use. 

We'll need to create a Gitlab account and populate it with data to be able to test the API.

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

_if the integration has already been vetted in https://docs.google.com/spreadsheets/d/1CUkw5ha0zPGJT1-vhe2rT3oIWt_6rVieH40J9fVrLJM/edit#gid=0 copy the vetting information from there and delete the row for that connector_

**Webhook-based? (no/partially/yes)**

no

**Available authentication modes (API key/Oauth/other)**

Could use Access Tokens like with Github Source

**Creating an account**

I can only create my own account, it's free. But I have no corporate credentials to create a corporate account at Gitlab.

**How to populate the account with data?**

I think I can fill the account with all the necessary entities using API and UI if I have access to a corporate account.

**Available streams for sync**

I checked, we can use tap-gitlab for sync data with Gitlab.
Singer Tap supports all the streams that we need (see the description of the issue)

**Integration supports incremental sync?**

Tap supports incremental for each project/group separately

**Other information/blockers**

**Comment by sherifnada** [comment]
@yevhenii-ldv I updated the Blaze template with the email address you can use to create an account

**Comment by sherifnada** [comment]
@yevhenii-ldv can you please post the credentials to the Gitlab in the company Lastpass account?

**Comment by yevhenii-ldv** [comment]
@sherifnada credentials was added in the company Lastpass account

**Comment by sherifnada** [comment]
thanks!
