### ISSUE TITLE
Source Facebook Marketing: start date is required

### ISSUE THREAD

**Issue by natalyjazzviolin** [airbytehq/airbyte#23068]
### Tell us about the documentation you'd like us to add or update.
In step number 6 for setting up the connector it states the Start Date field can be left blank:

For Start Date, enter the date in the YYYY-MM-DDTHH:mm:ssZ format. The data added on and after this date will be replicated. If this field is blank, Airbyte will replicate all data.

It is currently required
<img width="662" alt="01E19776-390B-4D75-8A6C-2C11D4664245" src="https://user-images.githubusercontent.com/65251165/219045662-df17635b-8384-4bc8-bb8f-e2658b4af401.png">
:

### If applicable, add links to the relevant docs that should be updated
- [Link](https://docs.airbyte.com/integrations/sources/facebook-marketing/)

**Comment by ChristoGrab** [comment]
Closed, start date is optional as of [#29994](https://github.com/airbytehq/airbyte/pull/29994).
