### ISSUE TITLE
Source Amazon Seller Partner: Action Required: Rotate LWA Credentials

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23072]
## Tell us about the problem you're trying to solve
Login With Amazon (LWA) Client secret for your application(s) will expire in less than 30 days. Review the LWA credentials column to identify applications that require client secret rotation. Choose View to generate new credentials, and remember to update your application.
**LastPass name:** Primary Amazon Ads Dev Account
**Screen with app:** [Developer Console](https://sellercentral.amazon.com/sellingpartner/developerconsole#) 
[Docs](https://developer-docs.amazon.com/sp-api/docs/rotating-your-apps-lwa-credentials)

**Comment by YowanR** [comment]
Let's make sure this gets prioritized! cc @YuliiaNahoha @oustynova

**Comment by igrankova** [comment]
Сreds rotated.
