### ISSUE TITLE
New source: Recharge

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2308]
I'd like to be able to pull data from the [Recharge API](https://rechargepayments.com/developers/) for the following streams:

 - [Addresses](https://developer.rechargepayments.com/#list-addresses)
  - [Charges](https://developer.rechargepayments.com/#list-charges)
  - [Collections](https://developer.rechargepayments.com/#list-collections-alpha)
  - [Customers](https://developer.rechargepayments.com/#list-customers)
  - [Discounts](https://developer.rechargepayments.com/#list-discounts)
  - [Metafields for Store, Customers, Subscriptions](https://developer.rechargepayments.com/#list-metafields)
  - [One-time Products](https://developer.rechargepayments.com/#list-onetimes-alpha)
  - [Orders](https://developer.rechargepayments.com/#list-orders)
  - [Products](https://developer.rechargepayments.com/#list-products-beta)
  - [Shop](https://developer.rechargepayments.com/#retrieve-shop)
  - [Subscriptions](https://developer.rechargepayments.com/#list-subscriptions)

**Comment by vitaliizazmic** [comment]
## Integration Vetting

The integration has already been vetted in https://docs.google.com/spreadsheets/d/1CUkw5ha0zPGJT1-vhe2rT3oIWt_6rVieH40J9fVrLJM/edit#gid=0

**Webhook-based? (no/partially/yes)**

No

**Available authentication modes (API key/Oauth/other)**

API Token

**Creating an account**

need request API Token via support, 
this requires shopify URL

**How to populate the account with data?**

Account can be populated with data? Yes

**Available streams for sync**

- api.Address
- api.Charge
- api.Checkout
- api.Customer
- api.Order
- api.Subscription

**Integration supports incremental sync?**

docs not accessible without Token

**Other information/blockers**

Blocked on Airbyte: Account Needed

**Comment by sherifnada** [comment]
@arhip11 can you request an API token from support so we can move forward with this integration?

**Comment by arhip11** [comment]
Started 60-day trial.
Waiting for support to contact.
"A member of our team will be following up with you shortly to make sure you have everything you need in order to get started on ReCharge."

**Comment by arhip11** [comment]
Requested API token from support via "Contact us" form.

**Comment by arhip11** [comment]
Support refers to Partnership program. Requested to become a partner.

**Comment by sherifnada** [comment]
thank you for the update @arhip11 !

**Comment by arhip11** [comment]
Still waiting for the reply regarding partnership program.
Submitted "Contact Us" form again.

**Comment by sherifnada** [comment]
thanks @arhip11

**Comment by arhip11** [comment]
Getting some feedback from the support.
Documentation could be accessed via entering magic token `abc123`.
@vitaliizazmic - FYI.

**Comment by sherifnada** [comment]
@arhip11 magic token works for docs, but is it possible to use some sandbox account yet, or are we still waiting to hear from partnerships?

**Comment by arhip11** [comment]
@sherifnada - the last thing Recharge is looking for from us is Store URL and we can get the token.
I've just replied them asking to elaborate.
Do you have an idea how we can go about the Store URL?

**Comment by sherifnada** [comment]
I suspect they mean shopify? Please use this URL: https://jolicookie.com/

**Comment by arhip11** [comment]
Current application form: https://docs.google.com/forms/d/e/1FAIpQLSfHHtQKD4G9zkv6iMPpwVpDNdVlu1b8OFAroDnbNYUotFjIZg/viewform

Manifesto for tech partners: https://docs.google.com/document/d/1CTTtB-xexh7Wr7d1drtXgSfZ8NJcLvS2CFkWnX-M5Ic/edit

**Comment by arhip11** [comment]
Token for the shop https://airbyte.myshopify.com/ created and added to Lastpass.

**Comment by sherifnada** [comment]
@arhip11 FYI we were able to get a token for an account containing data from one of our design partners so this is not a hard blocker for the time being. 

We should be ready to begin implementation on this connector now

**Comment by yevhenii-ldv** [comment]
## Task breakdown
- [ ] Populate source with data (4h)
- [ ] Create source scaffolding and populate schemas folder (lots of manual work, 4h)
- [ ] Implement spec, check and discover (1h)
- [ ] Implement FullTable read (5h)
- [ ] Implement Incremental read (3h)
- [ ] Handle rate-limiting and back off, add unit tests for it (3h)
- [ ] Integrate with acceptance tests (3h)
