### ISSUE TITLE
connector-acceptance-test: incremental tests failures on java sources

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#23098]
We have failing incremental tests for `source-postgres` and `source-snowflake`. 
They are both failing at running `test_two_sequential_reads`.

I suspect the root cause of it to be that the `records_with_state` function can't handle per-stream state.
I think it went under the radar because API connectors emit legacy + per_stream states while java sources only emit per-stream state. 

Related PR: https://github.com/airbytehq/airbyte/pull/23014

These failure happened after the addition of this new (legit) assertion in https://github.com/airbytehq/airbyte/pull/22353.
````
 assert parsed_records_1, "At least one valid state should be produced, given a cursor path"
````

I suspect this assertion highlighted a silenced failures and unexpected behavior in `test_two_sequential_reads`

**Comment by bnchrch** [comment]
A little more investigation on my side

I ran the tests locally against source-postgres and set a breakpoint in `test_two_sequential_reads`.

Below is the result of the failing values for records, state, stream path etc.

https://app.warp.dev/block/Q3yKgMkN7NomlmVm68NuRj
```py

(Pdb++) records_1
13[AirbyteMessage(type=<Type.RECORD: 'RECORD'>, log=None, spec=None, connectionStatus=None, catalog=None, record=AirbyteRecordMessage(namespace='public', stream='id_and_name', data={'id': 1, 'name': 'picard'}, emitted_at=1676580707185), state=None, trace=None, control=None), AirbyteMessage(type=<Type.RECORD: 'RECORD'>, log=None, spec=None, connectionStatus=None, catalog=None, record=AirbyteRecordMessage(namespace='public', stream='id_and_name', data={'id': 2, 'name': 'crusher'}, emitted_at=1676580707185), state=None, trace=None, control=None), AirbyteMessage(type=<Type.RECORD: 'RECORD'>, log=None, spec=None, connectionStatus=None, catalog=None, record=AirbyteRecordMessage(namespace='public', stream='id_and_name', data={'id': 3, 'name': 'vash'}, emitted_at=1676580707185), state=None, trace=None, control=None)]


14(Pdb++) latest_state
15{'id_and_name': {'cursor_record_count': 1, 'stream_name': 'id_and_name', 'stream_namespace': 'public', 'cursor_field': ['id'], 'cursor': '3'}}

16(Pdb++) stream_mapping
17{'id_and_name': ConfiguredAirbyteStream(stream=AirbyteStream(name='id_and_name', json_schema={'type': 'object', 'properties': {'name': {'type': 'string'}, 'id': {'type': 'number', 'airbyte_type': 'integer'}}}, supported_sync_modes=[<SyncMode.full_refresh: 'full_refresh'>, <SyncMode.incremental: 'incremental'>], source_defined_cursor=None, default_cursor_field=[], source_defined_primary_key=[['id']], namespace='public'), sync_mode=<SyncMode.incremental: 'incremental'>, cursor_field=['id'], destination_sync_mode=<DestinationSyncMode.append: 'append'>, primary_key=None, user_defined_primary_key=['id'])}

18(Pdb++) cursor_paths
19{'id_and_name': ['id']}

```

@sergio-ropero @rodireich Let me know if this helps at all

**Comment by rodireich** [comment]
Assuming the state message is an input, it looks like the format is not what source-postgres would expect.
Just like in an unrelated CAT failure in #23014 , what the connector expects is 
```
    "type": "STREAM",
     "stream": {
       "stream_state": {
         "stream_name": "id_and_name",
         "stream_namespace": "public",
         "cursor_field": ["id"],
         "cursor": "3",
         "cursor_record_count":1
       },
       "stream_descriptor": {
         "name": "id_and_name",
         "namespace": "public"
       }
     }
   }
```
also, whatever starts the connector, make sure that it passes the `USE_STREAM_CAPABLE_STATE=true` env. variable

**Comment by bnchrch** [comment]
Small update:
1. Finally got integration tests running locally early today (the integration DB was off, went on a goose chase before discovering that)
2. There have been some new changes to source-postgres and its cursors. @rodi and I are meeting Monday to discuss what that means for these tests.

https://github.com/airbytehq/airbyte/issues/26729

**Comment by bnchrch** [comment]
Pulling this back into grooming as I have some concerns about these tests that ive addressed in this PR
https://github.com/airbytehq/airbyte/pull/27872

And would love to ensure a review by all of connector ops

**Comment by evantahler** [comment]
Don't forget to publish - although legacy publish is busted.  @alafanechere might know how
