### ISSUE TITLE
Implement the connector builder's resolve_manifest endpoint in Java

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23108]
## Tell us about the problem you're trying to solve
Implement the connector builder's `/manifest/resolve` endpoint in Java

## Describe the solution you’d like
- The server will launch a python process with the `read` command and a `--config arg`.
- The config will include:
```
{... 
  "__command": "resolve_manifeset",
  "__command_config": {}
}
```
- The CDK will return the response as a list of AirbyteRecordMessages in the structure of the server's [`ResolveManifest`](https://github.com/airbytehq/airbyte-platform/blob/4911d653323122e85f3ed0a2772b96dfab47e80c/airbyte-connector-builder-server/src/main/openapi/openapi.yaml#L273) object.

Other details:
- The controllers should be as thin as possible because they can be difficult to test. They should delegate their logic to another module
- The interface between the core logic and the CDK should be flexible enough to support synchronous temporal jobs in the future
  - This can be done by creating an interface with two implementations - one directly shelling out to the CDK and one creating temporal jobs
  - The interface's parameters will be the manifest, the stream, the config, the workspace ID, and the docker image to use

- Reading AirbyteMessages from a process can be done using a `Process` and a `StreamFactory`:
```
      process = processFactory.create(/* parameters */ );

      LineGobbler.gobble(process.getErrorStream(), LOGGER::error);

      final Map<Type, List<AirbyteMessage>> messagesByType = WorkerUtils.getMessagesByType(process, streamFactory, timeoutInMinutes);
```

## Acceptance criteria
- [ ] For any inputs, the manifest_resolve endpoint returns the same output as the existing manifest_resolve endpoint
- [ ] The server shells out to the CDK entrypoint defined in https://github.com/airbytehq/airbyte/issues/22961

## Out of scope
- Submitting Temporal jobs

**Comment by clnoll** [comment]
Depends on infrastructure for launching python process from https://github.com/airbytehq/airbyte/issues/22965

**Comment by clnoll** [comment]
points=2
