### ISSUE TITLE
Remove Python implementation of the connector builder

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23127]
## What
Use the Micronaut server instead of the Python server. Right now, cloud and oss run different versions of the Connector Builder backend

## How
- Delete connector-builder-server module
- Rename connector-atelier-server module to connector-builder-server
- `git grep connector-atelier-server` and either delete the instance or replace them to `connector-builder-server`

## Acceptance criteria
- [ ] The module for the Python connector builder server is deleted from repo
- [ ] The platform is deployed with the Micronaut implementation of the server
- [ ] The webapp can reach the server
- [ ] Webapp E2E tests pass
- [ ] The server is upgraded as part of an OSS release
  - [ ] The image published is the Java server
- [ ] Wrapped server used for cloud uses the new java server

**Comment by girarda** [comment]
PR to use the atelier server in docker compose: https://github.com/airbytehq/airbyte-platform-internal/pull/6371

This does not include removing the code for the Python server. This can be done as a later step.

**Comment by girarda** [comment]
@brianjlai why was this issue closed? the python implementation is still in the repo https://github.com/airbytehq/airbyte-platform-internal/tree/master/oss/airbyte-connector-builder-server/connector_builder

**Comment by girarda** [comment]
@brianjlai why was this issue closed? the python implementation is still in the repo https://github.com/airbytehq/airbyte-platform-internal/tree/master/oss/airbyte-connector-builder-server/connector_builder

**Comment by brianjlai** [comment]
i think i closed this by mistake. reopening you're right

**Comment by girarda** [comment]
putting back to the ice box until we decide whether we want to use a sidecar approach or not

**Comment by flash1293** [comment]
Done by @brianjlai
