### ISSUE TITLE
Source ElasticSearch: connection loads only nulls in target

### ISSUE THREAD

**Issue by gautam-ergo** [airbytehq/airbyte#23140]
## Environment
- **Airbyte version**:  0.39.42-alpha.
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: [AKS] Kubernetes on Azure
- **Source Connector and version**: ElasticSearch **ALPHA**
- **Destination Connector and version**: BigQuery 1.1.14
- **Step where error happened**:  Sync job

## Current Behavior
Loads only nulls in to BigQuery, failed to load rows in the expected format in to Big Query

## Expected Behavior
Synchronization done successfully with the correct data and mappings on BigQuery corresponding to the source ElasticSearch schema.

## Logs
Source ElasticSearch index mapping:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/43657587/219375204-cb340679-a85f-4db5-a389-4396235e46eb.png">

Target BQ ouput:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/43657587/219375344-67ee9c0b-ab12-4df0-815b-65bf0d67c563.png">

Tried loading the data using RAW JSON option and Normalized tabular Data option 

Logs - 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/43657587/219375894-6e151272-2ca8-431c-9ea7-e3a538c7c7e7.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/43657587/219376072-f1a149c7-6491-49a3-910c-ff17c6ae257d.png">

## Steps to Reproduce
1. setup ElasticSearch as the source
2. setup BigQuery as the destination
3. select the table stream
4. Specify Normalized tabular Data option or Raw JSON option
5. No custom transformation specified

## Are you willing to submit a PR?
Happy to help :)

Please let me know if you need additional info.

Is that a missing config when setting up on an AKS cluster ?
Any advice on the approach that needs to be adopted would be of great help

Thanks.

**Comment by marcosmarxm** [comment]
I added the issue to connector backlog.

**Comment by akashkulk** [comment]
Closing out for now due to this being uncertified.
