### ISSUE TITLE
Write raw tables and normalized tables to different schemas

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#23147]
## Tell us about the problem you're trying to solve
To keep the data warehouse clean, I would like to write `_airbyte_raw` tables and final normalized tables to different schemas.

## Describe the solution you’d like
The ability to set 2 different schemas in the Connection UI - one for raw data, and one for normalized data.

## Describe the alternative you’ve considered or used
The only option that seems feasible today is to skip normalization and write only the `_airbyte_raw` data to a specified schema.
Then, run a custom normalization to save the final tables in a different schema. 

## Additional context
This has been requested by Cloud customers
See relevant slack thread [here](https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1676500507785899)

**Comment by nataliekwong** [comment]
I believe this is now addressed as a part of Destinations V2 and can be closed! But let me know if not.

**Comment by alex-gron** [comment]
Yes! 👏
