### ISSUE TITLE
Snowflake destination should verify hostname

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#23172]
In this OC issue a user typed in an invalid hostname (included spaces), which caused oAuth to fail: https://github.com/airbytehq/oncall/issues/1259. If we want to prevent this in the future, we should add hostname validation to the UI. This is already possible in specs by adding pattern validation. Here is an example: 
https://github.com/airbytehq/airbyte/blob/b6c6b7affb67c29d16efd203b7a18c019c075c06/airbyte-integrations/connectors/source-google-pagespeed-insights/source_google_pagespeed_insights/spec.yaml#L26

**Comment by rodireich** [comment]
I've reopened issue after reverting code change.
I see a fix is getting worked on in https://github.com/airbytehq/airbyte/issues/24409.
