### ISSUE TITLE
Allow deleting connector definitions

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2319]
## Tell us about the problem you're trying to solve
I added a custom connector definition and would like to delete it from the UI.

## Describe the solution you’d like
I want a button in the UI to be able to do it

My guess is we'll need to add an API endpoint and a UI change to enable this

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093595101) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
we have a new issue to track this that is being actively worked on. closing this one as a duplicate: https://github.com/airbytehq/airbyte/issues/8732
