### ISSUE TITLE
Source TikTok Marketing: doesn't match value reported in Tiktok platform

### ISSUE THREAD

**Issue by theRoundGreek** [airbytehq/airbyte#23209]
## Environment
- **Airbyte version**:  example is 0.40.30
- **OS Version / Instance**: Ubuntu 22.04
- **Deployment**: Docker Compose from git pull
- **Source Connector and version**: TikTok Marketing 2.01
- **Destination Connector and version**: Postgres 0.3.26
- **Step where error happened**: Sync job 
  
## Current Behavior
ad_groups_reports_daily, ad_groups_reports_hourly, campaigns_reports_daily, campaigns_reports_hourly metrics do not match tiktok dashboard, manual api pull or whats being reported in a third party tracker.
The only thing that stands out in the sync log is this for all affected streams:
ERROR c.n.s.DateTimeValidator(tryParse):82 - Invalid date-time: No zone offset information found

## Expected Behavior
Spend, reach, cpc, ctr, cpm etc should reflect data provided by TikTok.

## Logs
https://pastebin.com/cfhXLSDB

## Steps to Reproduce
1. Setup TikTok Source
2. Setup Postgres destination
3. Select one of the hourly or daily report breakdowns
4. Sync

## Are you willing to submit a PR?
No

**Comment by arsenlosenko** [comment]
@theRoundGreek hi, I tried to reproduce the issue that you had with your sync on the latest versions of both connectors and didn't find any possible causes for discrepancy of metrics before and after syncs of report-related streams. One thing that I would like to highlight that reports streams sometimes have data latency for up to 11 hours (more on that [here](https://ads.tiktok.com/marketing_api/docs?id=1738864894606337)). Also [documentation for this connector](https://docs.airbyte.com/integrations/sources/tiktok-marketing/) has a notice of that and suggests to increase value of attribution window for 3 days at least. If you still experience this issue on latest version of Source TikTok Marketing, can you please tweak the value for attribution window and sync again to see if this resolves this issue? Thanks!
Until then, I am closing this issue, and will re-open it if the issue still remains.

**Comment by sajarin** [comment]
@arsenlosenko I have a user who's experiencing similar issues with data discrepancies particularly with spend and click metrics. Their attribution window is set to 180 days. 

Logs attached: 
[default_logs_477993_06_24_2023.txt](https://github.com/airbytehq/airbyte/files/11918265/default_logs_477993_06_24_2023.txt)

**Comment by arsenlosenko** [comment]
@sajarin thanks for the logs, taking a look

**Comment by arsenlosenko** [comment]
@sajarin looked at logs you shared, errors listed there are a bit different, so I created a separate issue for this case, and moved it to backlog:
https://github.com/airbytehq/airbyte/issues/27966
closing this issue
