### ISSUE TITLE
Connector-specific changelogs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2321]
## Tell us about the problem you're trying to solve
As a user I have no way of tracking the changes made to a single connector without looking directly at the git history for this connector.

## Describe the solution you’d like
I would like each connector to have a `CHANGELOG.md` file which tells me what changed with each version. Ideally this is also propagated to each image's Docker hub page's README.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093475301) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Airflow has a very nice way of exposing it: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/index.html

**Comment by marcosmarxm** [comment]
@michel-tricot airflow use `.rst` files and there some external python modules to build this is not wrong, and they build entire documentation when releasing new versions. is more complex than using `.md` but you have a lot more features.

**Comment by davinchia** [comment]
Is this different from the current `Changelog` section we have in connector documentation?

**Comment by sherifnada** [comment]
Nope
