### ISSUE TITLE
Sweep old Docker images from the Airbyte node

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2322]
## Tell us about the problem you're trying to solve
We implemented a fix in #1529 to prevent logs from filling up disk. However, due to Airbyte's usage of Docker, it can take up a lot of disk space when cycling through images (e.g: if I update a connector version 5 times, then I use 5x the size of that connector). 

## Describe the solution you’d like
I would like Airbyte to remove unused connector images from my machine without me having to manually run `docker system prune` after my node runs out of space

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093726102) by [Unito](https://www.unito.io)

**Comment by kyle-cheung** [comment]
+1 on this we're running out of disk space after 2 days of use

**Comment by danieldiamond** [comment]
+1

**Comment by Maxsabran** [comment]
+2 it is becoming critical the more connector we use and update

**Comment by alafanechere** [comment]
Hey @Maxsabran I know it's not ideal but you can schedule a `cron` job with `docker system prune` to perform schedule this periodic cleanup.

**Comment by evantahler** [comment]
In https://github.com/airbytehq/airbyte/issues/15218 we are building an airbyte cron service (`airbyte/cron`) for cleaning up logs and other things.  This would be a great addition to that service.

**Comment by evantahler** [comment]
This seems a little dangerous.  There's `docker image prune` and `docker container prune`, but running that on a schedule from within a docker image will require elevated permissions.  However, it is easy to [set up cron to do this for you](https://alexgallacher.com/prune-unused-docker-images-automatically/).

K8s deployments already handle this kind of thing automatically.

@sherifnada I suggest we add a note about how to use cron to run `docker system prune` to https://docs.airbyte.com/operator-guides/scaling-airbyte, and then close this issue.

**Comment by supertopher** [comment]
[Made an issue](https://github.com/airbytehq/airbyte/issues/27020) to track updating the docs.  I'll DM Evan about whose team can do this

part of closing the issue will be to close this one.

**Comment by davinchia** [comment]
Stale.
