### ISSUE TITLE
airbyte-config:init becomes its own package & repo

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#23223]
# The issue
There are two issues
1. For the foreseeable future there will be a `airbyte-config:spec` project in both the platform and the connectors repos.  These have been new changes!
2. After the cut over commits were made to the `platform` specs project, that would be useful in the `connectors version.

Namely
- The introduction of a top level common constants folder
- Changes to how masked data interceptor makes use of the catalog

# The solution
Once the dust has settled do an audit of both spec files:
1. remove any unused files
2. Port any concepts over that may be useful back to connectors from platform

**Comment by evantahler** [comment]
This story could be called:

* Remove `airbyte-config:init` from the connectors repo.  This means that java connectors can't rely on it.
