### ISSUE TITLE
Refactor check_images.sh to no longer reference the spec.yaml files

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#23220]
## The problem
In the new platform repo the [check_images.sh](https://github.com/airbytehq/airbyte-platform/blob/delete-local-src-catalogs/tools/bin/check_images_exist.sh#L99) script pulls docker images out of the old spec files.

There is also an issue where the connector images can only be checked in the OSS repo.

And the platform and normalization images can only be checked in the platform repo

```[tasklist]
## Solution
- [ ]  Pull the data from the oss_catalog.json which has data in the same place. ([Here is an example](https://github.com/airbytehq/airbyte-platform/pull/15/files#diff-33e2bac6d5e7cf9a2ecb361dbcecca191e17e58323265ff49275ae252bf42cf9R63) of how were doing this to get secrets values)
- [x] Update the check image script in oss to only concern itself with the connector images
- [ ] Update the check image script in platform to only concern itself with the normalization and platform images
```

**Comment by cpdeethree** [comment]
https://github.com/airbytehq/airbyte/pull/23214/commits/e6f704dc6ed905fcdf6c9695f5197facaa075a5d

Connectors repo updated in above commit
