### ISSUE TITLE
How to start the project now 

### ISSUE THREAD

**Issue by rakesh-kumar-ks** [airbytehq/airbyte#23243]
Hi Team I need to airbyte project  in the documents we are giving a guide to run the project using the docker-compose command but now we are not seeing the docker files in the master branch, now how can I run the project on my local machine

**Comment by LEEDASILVA** [comment]
Hey I'm testing airbyte on locally as well, and having the same issue, but looks like the script `run-ab-platform.sh` takes care of downloading and running Airbyte on docker.

But in the script, it is missing the `shebang` or `hashbang` (ex: `#!/usr/bin/bash`).
Once the shebang is added, the script is runnable.

It worked for me. Hope this helped.

**Comment by cpdeethree** [comment]
PR to update README.md with new process: https://github.com/airbytehq/airbyte/pull/23250

**Comment by cpdeethree** [comment]
PR to update getting started guide with new process: https://github.com/airbytehq/airbyte/pull/22947
