### ISSUE TITLE
UI changes around namespacing stream names

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2324]
## Tell us about the problem you're trying to solve

Following up on https://github.com/airbytehq/airbyte/issues/2285

I will edit and link to a PR with the appropriate change to API objects where to read/write these new fields.

The user should be able to tweak, edit and override the new fields "namespace" and "name" for each stream with the UI in order to customize where/how the final namespace and each table should be stored/named.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

Following the mock-up design here: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity

- We want a dest_namespace field and a dest_table_name field in front of each stream from the source.
- The default value of the `dest_namespace` at the stream level should be by default the same as the "global" `defaultNamespace` from #2285. 
- Thanks to these fields, the user is now able to edit and customize it for a particular stream at a time 
- When the source provides a namespace information, the default value of the `dest_namespace` at the stream level should be by default the concatenated string: `defaultNamespace` + `source_namespace`
- For validation of this page, the `defaultNamespace` field can be left empty as long as each AirbyteStream ends up with a non-empty `dest_namespace`. (ie the nonnull validation should be on each resulting `dest_namespace` for each stream)

![Screenshot 2021-03-05 at 14 13 51](https://user-images.githubusercontent.com/7718175/110125084-37037400-7dc3-11eb-89fb-a8b7e76d0fb8.png)

## Additional context

More complete docs here: https://docs.google.com/document/d/1EWBHuZ524K2Z9HJGlT-I9fqf0ba_pVh26NwMICHAqfs/edit#

Related comment/thread here too:
https://github.com/airbytehq/airbyte/pull/2298#discussion_r587852174

**Comment by davinchia** [comment]
We've decided to deprioritise this for now. Closing.
