### ISSUE TITLE
Ability to update the WEBAPP_URL env in the Airbyte helm chart

### ISSUE THREAD

**Issue by seanglynn-thrive** [airbytehq/airbyte#23269]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Within the Airbyte Kubernetes/Helm chart, we currently do not have the ability to specify some [airbyte services configurations ](https://docs.airbyte.com/operator-guides/configuring-airbyte/#airbyte-services) like the `WEBAPP_URL` as recommended here:
https://github.com/airbytehq/airbyte/issues/10598#issuecomment-1174429934

## Describe the solution you’d like

We would like to have the ability to update the `WEBAPP_URL` and if possible, other configuration parameters that exist within the shared configmap: [env-configmap.yaml](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/env-configmap.yaml)

## Describe the alternative you’ve considered or used

As there was no way to programmatically update the configmap values via helm, we have reverted to manually updating the kubernetes files as we deploy to our environment (hack level 1000).

## Additional context
Related issue: https://github.com/airbytehq/airbyte/issues/10598

## Are you willing to submit a PR?
Yes!

**Comment by MartinCura** [comment]
👋🏼  Is there currently a way to do this?

**Comment by pmossman** [comment]
Addressed by https://github.com/airbytehq/airbyte-platform/pull/260 and will be available in the next published helm chart version. Thanks Andrea!
