### ISSUE TITLE
How to write and test the basic normalization for a new connector

### ISSUE THREAD

**Issue by hantmac** [airbytehq/airbyte#23267]
### Tell us about the documentation you'd like us to add or update.

Hi team, I have wrote a new connector - databend-connector and want to impl the basic normalization for it. After I write some normalization code and build the normalization image, I can not find a way to open the switch of `Transformation` on the UI. 

And I can not find any docs about this, very poor development experience.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/7600925/220296921-c63defd2-19eb-47c8-be01-552d56bb207c.png">

**Comment by sajarin** [comment]
Hey @hantmac thanks for the issue. Have you taken a look at this section of our docs? https://docs.airbyte.com/understanding-airbyte/basic-normalization/#extending-basic-normalization

We'd love to hear your suggestions on what you feel is missing and needed to improve the developer experience.

**Comment by hantmac** [comment]
@sajarin Thanks for your help. And I have read the docs include [adding-normalization-to-a-connector](https://docs.airbyte.com/connector-development/#adding-normalization-to-a-connector). And  I have done this according to the docs, But still can't enable the normalization.

![image](https://user-images.githubusercontent.com/7600925/220511466-ba7b74fc-5fb6-4ce7-9ad3-287dcef247e6.png)

Any other steps need I to do?

**Comment by marcosmarxm** [comment]
Normalization is deprecated and will be removed from the codebase in future releases. This issue isn't applicable anymore.
