### ISSUE TITLE
Low code template doesnot work

### ISSUE THREAD

**Issue by ddenysov** [airbytehq/airbyte#23260]
## Environment
- **Airbyte version**:  example is 0.40.32
- **OS Version / Instance**:macOS
- **Deployment**: local
- **Source Connector and version**: low code new connector
- **Destination Connector and version**: N/A
- **Step where error happened**: Spec operation after installing dependencies

## Current Behavior
- Go to documentation and do all steps https://docs.airbyte.com/connector-development/config-based/tutorial/install-dependencies
- Run command on new Low Code Connector: **python main.py spec**
-
`jsonschema.exceptions.ValidationError: 'CustomRecordExtractor' is not one of ['DpathExtractor']

Failed validating 'enum' in schema[1]['properties']['type']:
    {'enum': ['DpathExtractor'], 'type': 'string'}

On instance['type']:
    'CustomRecordExtractor'`

## Expected Behavior
Validation should works without errors.

## How I fixed this
manifest.yaml 
Line: 8 - replace 'field_pointer' to 'field_path'

**Comment by girarda** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/23397. Thanks @maxi297 !
