### ISSUE TITLE
Tutorial is missing: Airbyte Config Persistence

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#2327]
## Expected Behavior
https://docs.airbyte.io/tutorials/airbyte-config-persistence

## Current Behavior
Link is broken

## Severity of the bug for you
Very low / Low / **Medium** / High / Critical

**Comment by ChristopheDuong** [comment]
This was deleted because we split the tutorials in smaller pieces, where did you find the link pointing to this?

**Comment by marcosmarxm** [comment]
@ChristopheDuong https://airbyte.io/tutorials/

**Comment by johnlafleur** [comment]
Fixed! Thanks @marcosmarxm
