### ISSUE TITLE
CDK: remove unexpected error swallowing on abstract source's `check` method

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23281]
As part of the improve synchronous job error reporting tech spec, the following improvement to the CDK was identified: 

Connectors output trace messages instead of failed check connection statuses for unexpected errors
The current implementation of many connectors, including CDK sources and destinations, involves excepting any unhandled exception during the check method, and returning a connection_status message with status=failure. This effectively turns a failed check job into a successful check job with a failed connection test. It does so without sending a trace message. 

In order to be able to provide more information to the user than can be contained only in the ‘message’ portion of the connection status message, connectors should output trace messages when they run into unhandled errors, instead of output connection status messages.  In this project, we will add this as the default behavior for abstract sources in the CDK.  It is not in scope for this project to update existing connectors that override this default behavior. 

The CDK already has code to be able to handle this if general catch-all error handling is not in place. [This error handling](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/exception_handler.py#L11) which outputs trace messages for uncaught exceptions, is currently not being used in the check method because uncaught exceptions are being caught [here](https://github.com/airbytehq/airbyte/blob/2e099acc52aeddc172c5ee66ed98426c69449a4a/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L86-L87). This not only makes us lose information when going back to the API, but also stops us from doing our normal error handling for uncaught exceptions, which reports errors to sentry. For example, there was no sentry error for [this P0](https://docs.google.com/document/d/1c6H50vpIOT8eQEj5i8fYsndgMB0kM19s21n_BGr2gVc/edit) due to the fact that the error was caught and output as a connection status failure.

**Comment by evantahler** [comment]
Grooming:
* Reminder - we are going to update the CDK, but not all existing connectors.  That's out-of-scope
* We may want to add a CAT test to alert/fail when there isn't a trace message when CHECK fails.  A connection_status_message is not enough for **UNEXPECTED** errors (which this story is talking about)
