### ISSUE TITLE
UI displays collapsible info for different error cases for check and discover failures

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23302]
Discover: 

Currently, frontend component comes from the [SchemaError](https://github.com/airbytehq/airbyte-platform-internal/blob/436a1455d8254cc8c011760af247148f3cec8309/oss/airbyte-webapp/src/components/connection/CreateConnectionForm/SchemaError.tsx) component. This will likely have to be refactored to share code with the [TestCard](https://github.com/airbytehq/airbyte-platform/blob/8866a3c1316c1dfa8781054aed924159adf6907e/airbyte-webapp/src/views/Connector/ConnectorCard/components/TestCard.tsx), which is used to show errors when testing the source (performing Check). 

Check: rework TestCard to implement the new designs in #23301

**Comment by erohmensing** [comment]
@flash1293 You might have more specific grooming to add here 😄 happy to go over it tomorrow in our sync.

**Comment by erohmensing** [comment]
Grooming:
- Create a new component to use on both check and discover
- What to do about "Cancel" functionality on check? Do we need it? If we keep it we should probably hide it in discover
- What to do about "Retry" button for schema page. 
  - Should we 
  - For now, put in top right corner always 
- Width of discover error component should match width from previous steps

**Comment by flash1293** [comment]
Designs: https://www.figma.com/file/gMNRYVJav25pdsoxAyW7Qp/00_01_WEB-APP-LIBRARIES?node-id=2561%3A4596

**Comment by flash1293** [comment]
Build on top of this PR: https://github.com/airbytehq/airbyte-platform-internal/pull/4739#event-8639732409
