### ISSUE TITLE
Design: Updated error components for check + discover failures

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23301]
Work with Nico to solidify a design for adding FailureReason info to the frontend component for failures during the check and discover jobs. 

[Tech spec](https://docs.google.com/document/d/16N5NAs9ahPTUEEebbij9fkny4vnjE4QnjkTuCqJKXbk/edit#)

Existing: 

![image.png](https://images.zenhubusercontent.com/5c9df18c8ddfda53adf61cc8/4d6b63dc-3ac0-41c2-983b-4704c9d443b2)

Very rough outline: 

### Check failure case 1: Connection status message (check job success, connection check failure, no extra info) 

Similar to what we currently have. 
```
The connection tests failed. 
<Connection status message> 
<Downloadable logs>
```
### Check failure case 2: Connection status message (check job success, connection check failure + trace message for connection check failure) 

```
The connection tests failed. 
<Connection status message> 
# TODO: what goes here? @erohmensing to see which parts of failureReason coming out of check failures in jdbc sources(?) are most pertinent to the user 

<collapsible>
  <internal message>
  <failure type>
  <traceback in a monospace font block>
  <logs (downloadable)>
<end collapse>
```

### Check failure case 3: Trace message (check job failure) 

```
Failed to perform connection check.
<failure origin> <externalmessage>

<collapsible>
  <internal message>
  <failure type>
  <traceback in a monospace font block>
  <logs (downloadable)>
<end collapse>
```

### Check failure case 3 - job failure w/ no trace message 

In this case we have zero information to give the user. Therefore probably something like 
```
"Failed to perform connection check."
"Check the logs for more information."

<logs (downloadable)>
 ```

### Discover failure w trace message 

Same as check failure case 3, but with "Failed to retrieve source schema." instead of "Failed to perform connection check" 

### Discover failure w/ no trace message 

Same as check failure case 4, but with "Failed to retrieve source schema." instead of "Failed to perform connection check"

**Comment by flash1293** [comment]
Design is linked in https://app.zenhub.com/workspaces/connector-extensibility-6257455decf3920012f4e872/issues/gh/airbytehq/airbyte/23302
