### ISSUE TITLE
Follow-up: Issues for potential future improvements after check error reporting epic

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23303]
Create follow up issues for whatever projects in "Potential future improvements" still sound like legit improvements. From the [Improve Synchronous Job Error Reporting tech spec](https://docs.google.com/document/d/16N5NAs9ahPTUEEebbij9fkny4vnjE4QnjkTuCqJKXbk/edit#)

**Comment by evantahler** [comment]
Moving to the icebox

**Comment by erohmensing** [comment]
* [Improved error messages: Infer error messages from container exit codes](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/issues/gh/airbytehq/airbyte/24616)
* [Improved error messages: Connector improvements for better UX of check errors](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/issues/gh/airbytehq/airbyte/24617)
* [Improved error messages: Categorize existing check failures and trace messages](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/issues/gh/airbytehq/airbyte/24618)
* [Trace messages! How else can we leverage them (especially for synchronous jobs)? Should we?](https://app.zenhub.com/workspaces/connector-operations-6318ede5eda32e0010ef8566/issues/gh/airbytehq/airbyte/24619)

**Comment by evantahler** [comment]
These are great ideas! Thank you for capturing them
