### ISSUE TITLE
Quickstart for running Airbyte are not up-to-date

### ISSUE THREAD

**Issue by alexander-marquardt** [airbytehq/airbyte#23324]
### Tell us about the documentation you'd like us to add or update.
Instructions for running Airbyte locally have changed as documented: https://docs.airbyte.com/deploying-airbyte/local-deployment/#setup--launch-airbyte

However, the Quickstart still refers to the old process: https://docs.airbyte.com/quickstart/deploy-airbyte/

**Comment by Amruta-Ranade** [comment]
Addressed in https://github.com/airbytehq/airbyte/pull/23339
