### ISSUE TITLE
CDC for Clickhouse

### ISSUE THREAD

**Issue by bvaisakh** [airbytehq/airbyte#23322]
We need to implement Point in Time recovery for clickhouse database. We prefer the solution to be based on CDC. We have tried out other solutions (like backups) but their cumbersome. Will airbyte be able help on this matter?

**Comment by marcosmarxm** [comment]
@bvaisakh does Clickhouse support CDC? Can you point to their documentation?

**Comment by marcosmarxm** [comment]
Airbyte has some sources which has support to read using CDC. Like Postgres, MySQL and other databases and you can send the data to Clickhouse. If you have question please start reading the documentation https://docs.airbyte.com/

**Comment by bvaisakh** [comment]
Ok. Airbyte's clickhouse export solutions are also not CDC based. I couldn't find the solution internals in the doc.
