### ISSUE TITLE
Expose outcome of last job for a connection

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2332]
## Tell us about the problem you're trying to solve
* We want to be able to give an overview of the health of connectors. We currently can't display this in the UI because in the `WbConnectionRead` we do not expose the outcome of whatever the last job was. See [issue](https://github.com/airbytehq/airbyte/issues/1960) that discovered this.

## Describe the solution you’d like
* Add `lastSyncStatus` (or equivalent) to `WbConnectionRead`

## Follow up.
When this task is complete, we should create an issue for the frontend to do the second part of the UX described in this [issue](https://github.com/airbytehq/airbyte/issues/1960).

**Comment by davinchia** [comment]
Closing as done!
