### ISSUE TITLE
Source Zendesk Support:  connector suddenly started failing at normalisation step

### ISSUE THREAD

**Issue by validumitru** [airbytehq/airbyte#23336]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: AWS EC2
- **Deployment**: Doecker
- **Source Connector and version**: Zendesk 0.2.23
- **Destination Connector and version**: Redshift 
- **Step where error happened**: Sync job, normalization step

## Current Behavior
The Zendesk sync suddenly started failing at normalization step. The error seems to be in the process_catalog function but it's not entirely clear where the error is from the logs. Attaching logs.
[ee85716a_cad6_45bb_954b_34c8500e95b5_logs_3951_txt.txt](https://github.com/airbytehq/airbyte/files/10805491/ee85716a_cad6_45bb_954b_34c8500e95b5_logs_3951_txt.txt)

## Expected Behavior
*Tell us what should happen.*

## Logs
Logs attached.

**Comment by roman-yermilov-gl** [comment]
Hi @validumitru 
Are you still experiencing the problem with normalization?
