### ISSUE TITLE
Show warning if the record selector points to a field that does not exist

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23351]
## What
The connector builder should show a warning if the record selector points to a field that does not exist in the response

## Acceptance Criteria
- If the record selector points at a field which doesn't exist in the response, show an error in the sidebar
- The error message contains a `Modify` button which focuses the record selector input when clicked

**Comment by Upmitt** [comment]
We could also use the default error message to highlight the Record Selector field

**Comment by lmossman** [comment]
Not doing this since we already have this warning:
<img width="606" alt="Screenshot 2023-07-18 at 10 25 00 AM" src="https://github.com/airbytehq/airbyte/assets/22731524/a09cf9e6-0983-4da9-b1e9-1dd8f86d7203">
