### ISSUE TITLE
Auto-detect Schema Changes: Do not prompt user to update an inactive stream

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#23361]
## Tell us about the problem you're trying to solve
If a stream is disabled, the user still gets notified when there are schema changes. This is disruptive and confusing.

## Describe the solution you’d like
Do not prompt users to update schemas for streams that are disabled. 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
Related conversations:

- [Slack Convo 1](https://airbytehq-team.slack.com/archives/C042ABK94FR/p1674666812082819)
- [Slack Convo 2](https://airbytehq-team.slack.com/archives/C042ABK94FR/p1677097322534329)

**Comment by alovew** [comment]
@alex-gron & @ryjabe What if the user reenables their stream? Are we thinking we don't want to have any of the schema change behavior if there is a change, including if there are breaking changes?

**Comment by alex-gron** [comment]
My expectation is that we would check for any schema changes at the time that the stream is re-enabled.
Without knowing how all of the back-end logic works, is this feasible?

**Comment by ryjabe** [comment]
I think there are a few ways we could handle it.  I like Alex's suggestion as I think it would be the cleanest way. 

Alternatively, we could keep the flag internal and when the user goes to reenable, run a check, then prompt them with a warning asking them to refresh the schema before enabling the stream.

**Comment by flutra-osmani** [comment]
The fix for this issue is now implemented. It will go with the next OSS release. I will provide another update when that occurs.

**Comment by flutra-osmani** [comment]
The fix is now part of the new OSS release.
