### ISSUE TITLE
Source TikTok Marketing: migrate to v1.3 API

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23375]
## Tell us about the problem you're trying to solve
The latest version for TikTok API For Business is v1.3.
Please note that though TikTok will support both v1.2 and v1.3 until August 2023, new major features will be only available in v1.3.
Please use the following useful resources to start migration:  
•	To find out the major updates in v1.3, see [V1.3 updates](https://suggestions.tiktok.com/g/ZS8u6HJXQ/). 
•	To find out the detailed versioning strategies and timelines, see [Versioning](https://suggestions.tiktok.com/g/ZS8u6tj9c/). 
•	To find out the differences between v1.2 and v1.3 for each API, see the comparison table in each API article in the [API Reference Guide](https://suggestions.tiktok.com/g/ZS8u69Ch7/). 
•	To quickly test v1.3 API endpoints, use [TikTok API for Business v1.3 Postman Collection](https://www.postman.com/tiktok/workspace/tiktok-api-for-business/collection/23207567-be0eb380-8a45-4bd4-95a4-d1698f3ff99e).

**Comment by davydov-d** [comment]
@YowanR @sherifnada shouldn't we create new connector for the 1.3 api version according to [this comment](https://github.com/airbytehq/oncall/issues/402#issuecomment-1224905901)?

**Comment by YowanR** [comment]
It seems that we'll need to land a whole new connector. @sherifnada can you please confirm? We have a little bit of time so maybe we can tackle this in Q1a, depending on our capacity.

**Comment by YowanR** [comment]
Conclusion: not top priority for now (see this slack [thread](https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1677606094026219)). We'll revisit this in Q2A

**Comment by grubberr** [comment]
Hello @erica-airbyte, 
I want to bring your attention to this issue and [PR](https://github.com/airbytehq/airbyte/pull/24630) related to this issue
We are migration to a new version of API `1.2 -> 1.3` for tiktok marketing

The new version of the connector will be `source-tiktok-marketing:3.0.0`
This migration introduces **incompatibility schema changes** to customers
Customers will be needed to refresh the source schema to proceed

**Comment by erica-airbyte** [comment]
Thanks @grubberr. 

@jnr0790 as TCS OC, can you pick a good time with Serhii to push this and then send out comms [to customers](https://airbyte.metabaseapp.com/question?source_connector_name=TikTok%20Marketing&last_event=past15days#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJuYXRpdmUiOnsicXVlcnkiOiJ3aXRoIGNvbm5lY3Rpb25fZGF0YSBhcyAoXG4gICAgc2VsZWN0ICogZnJvbSBgYWlyYnl0ZV93YXJlaG91c2UuY2xvdWRfY29ubmVjdGlvbl9zeW5jYFxuICAgIHdoZXJlIDEgPSAxIFxuICAgICAgICBhbmQgaXNfYWN0aXZlIGlzIHRydWVcbiAgICAgICAgYW5kIHt7IHNvdXJjZV9jb25uZWN0b3JfbmFtZSB9fVxuICAgICAgICBhbmQge3sgZGVzdGluYXRpb25fY29ubmVjdG9yX25hbWUgfX1cbiAgICAgICAgYW5kIHt7IGxhc3RfZXZlbnQgfX1cbiAgICAgICAgYW5kIHt7IHVzaW5nX3NvdXJjZV9zeW5jX21vZGVfaW5jcmVtZW50YWwgfX1cbiAgICAgICAgYW5kIHt7IHVzaW5nX2Rlc3RpbmF0aW9uX3N5bmNfbW9kZV9hcHBlbmRfZGVkdXAgfX1cbiksXG5cbnBlcm1pc3Npb24gYXMgKFxuICAgIHNlbGVjdCAqIGZyb20gYGFpcmJ5dGUtZGF0YS1yYXcuYWlyYnl0ZV9wcm9kX2Nsb3VkYXBpLnBlcm1pc3Npb25gXG4pLFxuXG51c2VyIGFzIChcbiAgICBzZWxlY3QgKiBmcm9tIGBhaXJieXRlLWRhdGEtcmF3LmFpcmJ5dGVfcHJvZF9jbG91ZGFwaS51c2VyYFxuKSxcblxuc2FsZXNmb3JjZV9hY2NvdW50IGFzIChcbiAgICBzZWxlY3Qgd29ya3NwYWNlX2lkLCBhY2NvdW50X2lkIGZyb20gYWlyYnl0ZV93YXJlaG91c2Uud29ya3NwYWNlXG4pLFxuXG5yYXdfZGF0YSBhcyAoXG5zZWxlY3QgXG4gICAgdXNlci5lbWFpbCxcbiAgICBjb25uZWN0aW9uX2RhdGEud29ya3NwYWNlX2lkLFxuICAgIGNvbm5lY3Rpb25fZGF0YS5jb25uZWN0aW9uX2lkLFxuICAgIHdvcmtzcGFjZV9uYW1lLFxuICAgIF9zb3VyY2VfY29ubmVjdG9yX25hbWUsXG4gICAgX2Rlc3RpbmF0aW9uX2Nvbm5lY3Rvcl9uYW1lLFxuICAgIGNsb3VkX3VybCxcbiAgICBhY2NvdW50X2lkXG5mcm9tIGNvbm5lY3Rpb25fZGF0YVxubGVmdCBqb2luIHBlcm1pc3Npb25cbiAgICBvbiBjb25uZWN0aW9uX2RhdGEud29ya3NwYWNlX2lkID0gcGVybWlzc2lvbi53b3Jrc3BhY2VfaWRcbmxlZnQgam9pbiB1c2VyXG4gICAgb24gcGVybWlzc2lvbi51c2VyX2lkID0gdXNlci5pZFxubGVmdCBqb2luIHNhbGVzZm9yY2VfYWNjb3VudFxuICAgIG9uIGNvbm5lY3Rpb25fZGF0YS53b3Jrc3BhY2VfaWQgPSBzYWxlc2ZvcmNlX2FjY291bnQud29ya3NwYWNlX2lkXG4pXG5cbnNlbGVjdCBkaXN0aW5jdCBcbiAgICBlbWFpbCxcbiAgICAtLWNvbm5lY3Rpb25faWQsXG4gICAgLS13b3Jrc3BhY2VfaWQsXG4gICAgd29ya3NwYWNlX25hbWUsXG4gICAgLS1jbG91ZF91cmwsXG4gICAgLS1jb25jYXQoXCJodHRwczovL2FpcmJ5dGUubGlnaHRuaW5nLmZvcmNlLmNvbS9saWdodG5pbmcvci9BY2NvdW50L1wiLCBhY2NvdW50X2lkLCBcIi92aWV3XCIpIGFzIHNhbGVzZm9yY2VfYWNjb3VudF9saW5rXG5mcm9tIHJhd19kYXRhXG53aGVyZSBlbWFpbCBub3QgbGlrZSAnJWFpcmJ5dGUuaW8lJ1xuICAgIGFuZCBlbWFpbCBub3QgbGlrZSAnJWdsb2JhbGxvZ2ljLmNvbSUnXG5vcmRlciBieSB3b3Jrc3BhY2VfbmFtZVxuIiwidGVtcGxhdGUtdGFncyI6eyJzb3VyY2VfY29ubmVjdG9yX25hbWUiOnsiaWQiOiI1N2YzYjg4OC0wZGIyLTljZWEtZjk4Zi0yNWJlOGI2NjE1NjAiLCJuYW1lIjoic291cmNlX2Nvbm5lY3Rvcl9uYW1lIiwiZGlzcGxheS1uYW1lIjoiU291cmNlIGNvbm5lY3RvciBuYW1lIiwidHlwZSI6ImRpbWVuc2lvbiIsImRpbWVuc2lvbiI6WyJmaWVsZCIsNjkxNzYsbnVsbF0sIndpZGdldC10eXBlIjoic3RyaW5nLz0iLCJkZWZhdWx0IjpudWxsfSwiZGVzdGluYXRpb25fY29ubmVjdG9yX25hbWUiOnsiaWQiOiJlM2ZlZmIzZC0xNDhhLTZiYmEtZDZkMi04MWFhOTQ0MDI1ZjIiLCJuYW1lIjoiZGVzdGluYXRpb25fY29ubmVjdG9yX25hbWUiLCJkaXNwbGF5LW5hbWUiOiJEZXN0aW5hdGlvbiBjb25uZWN0b3IgbmFtZSIsInR5cGUiOiJkaW1lbnNpb24iLCJkaW1lbnNpb24iOlsiZmllbGQiLDY5MTYzLG51bGxdLCJ3aWRnZXQtdHlwZSI6InN0cmluZy89IiwiZGVmYXVsdCI6bnVsbH0sImxhc3RfZXZlbnQiOnsiaWQiOiIzZTFkN2E5MC02M2FhLTVmMGItOWRkYi1hNzE2ZGRjZjJmMWQiLCJuYW1lIjoibGFzdF9ldmVudCIsImRpc3BsYXktbmFtZSI6IkRhdGUgUmFuZ2UiLCJ0eXBlIjoiZGltZW5zaW9uIiwiZGltZW5zaW9uIjpbImZpZWxkIiw2OTE0MCxudWxsXSwid2lkZ2V0LXR5cGUiOiJkYXRlL2FsbC1vcHRpb25zIiwiZGVmYXVsdCI6bnVsbH0sInVzaW5nX3NvdXJjZV9zeW5jX21vZGVfaW5jcmVtZW50YWwiOnsiaWQiOiIwODBiMTExMi0wZWI5LWNlMjgtOTMzNi0xYWYxZWU1MDRmMzAiLCJuYW1lIjoidXNpbmdfc291cmNlX3N5bmNfbW9kZV9pbmNyZW1lbnRhbCIsImRpc3BsYXktbmFtZSI6IlVzaW5nIHNvdXJjZSBzeW5jIG1vZGUgaW5jcmVtZW50YWwiLCJ0eXBlIjoiZGltZW5zaW9uIiwiZGltZW5zaW9uIjpbImZpZWxkIiw2OTE1MCxudWxsXSwid2lkZ2V0LXR5cGUiOiJzdHJpbmcvPSIsImRlZmF1bHQiOm51bGx9LCJ1c2luZ19kZXN0aW5hdGlvbl9zeW5jX21vZGVfYXBwZW5kX2RlZHVwIjp7ImlkIjoiM2QzZmJmMzktNjBjZi1lNDg5LTc4ZmItNTMwMjU0NDM4MmQ5IiwibmFtZSI6InVzaW5nX2Rlc3RpbmF0aW9uX3N5bmNfbW9kZV9hcHBlbmRfZGVkdXAiLCJkaXNwbGF5LW5hbWUiOiJVc2luZyBkZXN0aW5hdGlvbiBzeW5jIG1vZGUgYXBwZW5kIGRlZHVwIiwidHlwZSI6ImRpbWVuc2lvbiIsImRpbWVuc2lvbiI6WyJmaWVsZCIsNjkxNTEsbnVsbF0sIndpZGdldC10eXBlIjoic3RyaW5nLz0iLCJkZWZhdWx0IjpudWxsfX19LCJ0eXBlIjoibmF0aXZlIn0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6W3siaWQiOiI1N2YzYjg4OC0wZGIyLTljZWEtZjk4Zi0yNWJlOGI2NjE1NjAiLCJ0eXBlIjoic3RyaW5nLz0iLCJ0YXJnZXQiOlsiZGltZW5zaW9uIixbInRlbXBsYXRlLXRhZyIsInNvdXJjZV9jb25uZWN0b3JfbmFtZSJdXSwibmFtZSI6IlNvdXJjZSBjb25uZWN0b3IgbmFtZSIsInNsdWciOiJzb3VyY2VfY29ubmVjdG9yX25hbWUiLCJkZWZhdWx0IjpudWxsfSx7ImlkIjoiZTNmZWZiM2QtMTQ4YS02YmJhLWQ2ZDItODFhYTk0NDAyNWYyIiwidHlwZSI6InN0cmluZy89IiwidGFyZ2V0IjpbImRpbWVuc2lvbiIsWyJ0ZW1wbGF0ZS10YWciLCJkZXN0aW5hdGlvbl9jb25uZWN0b3JfbmFtZSJdXSwibmFtZSI6IkRlc3RpbmF0aW9uIGNvbm5lY3RvciBuYW1lIiwic2x1ZyI6ImRlc3RpbmF0aW9uX2Nvbm5lY3Rvcl9uYW1lIiwiZGVmYXVsdCI6bnVsbH0seyJpZCI6IjNlMWQ3YTkwLTYzYWEtNWYwYi05ZGRiLWE3MTZkZGNmMmYxZCIsInR5cGUiOiJkYXRlL2FsbC1vcHRpb25zIiwidGFyZ2V0IjpbImRpbWVuc2lvbiIsWyJ0ZW1wbGF0ZS10YWciLCJsYXN0X2V2ZW50Il1dLCJuYW1lIjoiRGF0ZSBSYW5nZSIsInNsdWciOiJsYXN0X2V2ZW50IiwiZGVmYXVsdCI6bnVsbH0seyJpZCI6IjA4MGIxMTEyLTBlYjktY2UyOC05MzM2LTFhZjFlZTUwNGYzMCIsInR5cGUiOiJzdHJpbmcvPSIsInRhcmdldCI6WyJkaW1lbnNpb24iLFsidGVtcGxhdGUtdGFnIiwidXNpbmdfc291cmNlX3N5bmNfbW9kZV9pbmNyZW1lbnRhbCJdXSwibmFtZSI6IlVzaW5nIHNvdXJjZSBzeW5jIG1vZGUgaW5jcmVtZW50YWwiLCJzbHVnIjoidXNpbmdfc291cmNlX3N5bmNfbW9kZV9pbmNyZW1lbnRhbCIsImRlZmF1bHQiOm51bGx9LHsiaWQiOiIzZDNmYmYzOS02MGNmLWU0ODktNzhmYi01MzAyNTQ0MzgyZDkiLCJ0eXBlIjoic3RyaW5nLz0iLCJ0YXJnZXQiOlsiZGltZW5zaW9uIixbInRlbXBsYXRlLXRhZyIsInVzaW5nX2Rlc3RpbmF0aW9uX3N5bmNfbW9kZV9hcHBlbmRfZGVkdXAiXV0sIm5hbWUiOiJVc2luZyBkZXN0aW5hdGlvbiBzeW5jIG1vZGUgYXBwZW5kIGRlZHVwIiwic2x1ZyI6InVzaW5nX2Rlc3RpbmF0aW9uX3N5bmNfbW9kZV9hcHBlbmRfZGVkdXAiLCJkZWZhdWx0IjpudWxsfV0sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUucGl2b3RfY29sdW1uIjoid29ya3NwYWNlX2lkIiwidGFibGUuY2VsbF9jb2x1bW4iOiJ3b3Jrc3BhY2VfY2xvdWRfdXJsIiwidGFibGUuY29sdW1ucyI6W3sibmFtZSI6IndvcmtzcGFjZV9uYW1lIiwiZmllbGRSZWYiOlsiZmllbGQiLCJ3b3Jrc3BhY2VfbmFtZSIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImVtYWlsIiwiZmllbGRSZWYiOlsiZmllbGQiLCJlbWFpbCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sImVuYWJsZWQiOnRydWV9XSwiY29sdW1uX3NldHRpbmdzIjp7IltcIm5hbWVcIixcImNsb3VkX3VybFwiXSI6eyJ2aWV3X2FzIjoibGluayIsImxpbmtfdGV4dCI6ImxpbmsifX19LCJvcmlnaW5hbF9jYXJkX2lkIjoxMzgzfQ==). Let me know if you need help :)

**Comment by grubberr** [comment]
@grubberr @jnr0790 I am waiting your approval for pushing

**Comment by jnr0790** [comment]
@grubberr let's get it out on Thursday, April 6th at 10 am EST. I'll send comms to the customers.

**Comment by jnr0790** [comment]
@grubberr are we still good to get this on cloud at 10am?

**Comment by jnr0790** [comment]
@grubberr what's happening with the release for this?

**Comment by jnr0790** [comment]
cc @brianjlai as current OC can this be pushed to cloud? I'd like to communicate with users again to let them know this is going out at a later date or letting them know it went out later than expected.

**Comment by grubberr** [comment]
@jnr0790 I am working on it now, I am trying to pass CAT tests

**Comment by grubberr** [comment]
@jnr0790 

There was a lot problems with connector
finally tests passed
please let me know when we can publish / merge

**Comment by grubberr** [comment]
I have re-opened until we publish `source-tiktok-marketing:3.0.x` on cloud

**Comment by jnr0790** [comment]
@grubberr to give users enough warning we should wait til Wednesday (April 12th 10am). I'll send out the email to users.

**Comment by jnr0790** [comment]
email sent to users

**Comment by grubberr** [comment]
@jnr0790 @lazebnyi @bazarnov 
I have created PR https://github.com/airbytehq/airbyte-platform-internal/pull/5716 which unpin Source Tiktok 2.0.6 on cloud 
and new 3.0.1 will be deployed
