### ISSUE TITLE
Deduplicate records in an incremental sync

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2337]
## Tell us about the problem you're trying to solve
As a user, I want to be able to see a de-duplicated version of my records in the destination.

## Describe the solution you’d like
* A user can configure a sync to that does incremental syncs so that the final data that user sees is de-duplicated. 
* If a user chooses this configuration, then they have to configure a primary key for their data (or the source has to set it--similar to what we do with source-defined or user-defined cursor fields).
* This project includes planning, designing, and executing the end-to-end user experience (including the UI).

## Out of scope
* CDC

**Comment by ChristopheDuong** [comment]
The main piece that is missing for this feature is the front-end to select the destination sync mode per stream.

In the meantime, I will try to look at sources and how they can make it easier to select primary keys

**Comment by ChristopheDuong** [comment]
Last pieces that may still be missing are:
- Back-end exposing which destination sync modes are supported by destinations https://github.com/airbytehq/airbyte/issues/2603
- Front-end using the supportedDestinationSyncModes field to restrict UI actions accordingly
- Destination Sync Mode docs

**Comment by Ariyo05** [comment]
1. Why is all my datatime column change to string on the destination table? Can you look into this.
2. Can you guys enable source column to be mapped manually or automatically to the destination column without changing the data type on the destination table.
3. How to handle updated column.
