### ISSUE TITLE
Source dv 360: Migrate from Bid Manager API v1.1 to v2

### ISSUE THREAD

**Issue by marianabispo** [airbytehq/airbyte#23387]
## Tell us about the problem you're trying to solve
Migrate to v2 to avoid service interruption, Bid Manager will support  v1.1 until April 27, 2023.

Please use the following useful resources to start migration:
• To find out the major updates in v2, see [V2 Migrate](https://developers.google.com/bid-manager/how-tos/v2-migration).

**Comment by ducnva** [comment]
Hi @sajarin  
Have you migrated the connector to v2 yet?
Thank you.

**Comment by topefolorunso** [comment]
Assign this to me next @justinbchau, PR raised for the other issue

**Comment by andremacola** [comment]
Any update on this? DV360 connector is not working without the update to V2
