### ISSUE TITLE
Source S3: implement availability strategy

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#23385]
We [need](https://github.com/airbytehq/airbyte/pull/23189/files#r1112006711) to create a custom availability strategy for the S3 source connector because the default one seems to not meet the requirements of this connector.

**Comment by davydov-d** [comment]
@YowanR FYI

**Comment by YowanR** [comment]
Let's create an Epic to track all these great suggestions! We should talk and see if we have the bandwidth to tackle some or all of it this quarter.
cc @lazebnyi @YuliiaNahoha @oustynova

**Comment by YuliiaNahoha** [comment]
@YowanR do you mean to create "S3 enhancements/refactoring" and add there https://github.com/airbytehq/airbyte/pull/23189? Just want to check. Thanks.

**Comment by artem1205** [comment]
In my opinion, Availability strategy can not be efficiently used for this type of connector.
From my point of view, the fact that we can open a file and read a random line does not guarantee us that we can successfully read the whole file(s), as we can potentially face different config errors, e.g.:
- Schema-related errors (we could  initially make a wrong “guess” about field type during discovery)
- Encoding errors (some encodings use the same character set, which cannot be discovered in right way until we read the whole file)
