### ISSUE TITLE
🐛 Source Stripe: Missing field customer_tax_ids in Stripe connector (invoices stream)

### ISSUE THREAD

**Issue by mrhallak** [airbytehq/airbyte#23388]
## Environment
- **Airbyte version**: 0.40.26
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker-compose
- **Source Connector and version**: Stripe (2.0.0)
- **Destination Connector and version**: Snowflake (0.4.47)
- **Step where error happened**: Sync job

## Current Behavior
The `customer_tax_ids` field from the invoices stream doesn't exist in the final tables, it only exists as part of the JSON fetched from Stripe.
<img width="741" alt="Screenshot 2023-02-23 at 15 24 16" src="https://user-images.githubusercontent.com/16711801/220934805-6f61f9a2-3d74-44d5-a941-1a02900904ad.png">

The field also doesn't show on the Airbyte UI.

Stripe API [docs](https://stripe.com/docs/api/invoices/object)
## Expected Behavior
The `customer_tax_ids` field should be present in the final table and be shown on the Airbyte UI.
<img width="769" alt="Screenshot 2023-02-23 at 15 08 59" src="https://user-images.githubusercontent.com/16711801/220931246-cde569d1-6c63-44c5-a244-f9677515fbb4.png">

## Logs
The operation is not failing

## Steps to Reproduce
1. Run a sync for the invoices stream

## Are you willing to submit a PR?
#23389

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/23389/files
