### ISSUE TITLE
Remove duplicate execution on Postgres source tests

### ISSUE THREAD

**Issue by sergio-ropero** [airbytehq/airbyte#23390]
## Tell us about the problem you're trying to solve
Based on issue [22968](https://github.com/airbytehq/airbyte/issues/22968)

Looking on the following image, we see that some of the test are executed twice (all tests in `test` are executed in `integrationTestJava`).
<img width="1032" alt="Screenshot 2023-02-23 at 15 40 44" src="https://user-images.githubusercontent.com/42538006/220938945-c49da81c-09cf-461d-b954-6370909c5c60.png">
This ends into a waste of time and resources that slow down Postgres velocity.

## Describe the solution you’d like
Remove redundancy on the test being executed, so `integrationTest` will not contain the tests that run under `test`.

**Comment by prateekmukhedkar** [comment]
@sergio-ropero so the end result would be that `integrationTest` will not contain the tests that run under `test`?
