### ISSUE TITLE
Bulk edit set the sync to "off" in all cases

### ISSUE THREAD

**Issue by Upmitt** [airbytehq/airbyte#23425]
## Current Behavior
In connection > replication - when I select 1 or several streams, the toggle to sync the stream is always set to "off" - even if all the streams I selected are set to "on". 

If a user don't check the toggle state and only set the sync mode, then he will switch off all the selected streams

## Expected Behavior
The sync toggle status should reflect my selection:
- if all my selection is on>toggle should be on
- if all my selection is off>toggle should be off
- if there are both on & off settings, toggle state should be "mixed"

Idem for sync mode column:
The sync mode column should reflect my selection:
- if all my selection is XX>dropdown should display XX
- if there are several settings, the dropdown should be empty

**Comment by edmundito** [comment]
As discussed with @Upmitt, the last case is missing, so reopening:
> * if there are both on & off settings, toggle state should be "mixed"

**Comment by edmundito** [comment]
Tested and it works! Will follow up with @Upmitt to see if there is an edge case

**Comment by dizel852** [comment]
Closing, since all work as should
