### ISSUE TITLE
Consolidate file format parser

### ISSUE THREAD

**Issue by tim-werner** [airbytehq/airbyte#23423]
## Tell us about the problem you're trying to solve
There are several source connectors such as s3, file, sftp, sftp-bulk that allow to fetch different files (csv, json, parquet etc.). All of them implement different parsers for the same file formats. 

## Describe the solution you’d like
In my opinion, it would make much more sense to have a file parser utility that can be used in all connectors. This will simplify the maintenance and reduce the number of bugs. 

## Describe the alternative you’ve considered or used
---

## Additional context
---

## Are you willing to submit a PR?

I would also submit a PR

**Comment by natalyjazzviolin** [comment]
Hey @tim-werner please complete the above comment according to our template:

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context
Add any other context or screenshots about the feature request here.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by erohmensing** [comment]
This was a great idea! In June 2023 we added a [FileBasedSource](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/file_based/file_based_source.py#L54) class in the python CDK that our file connectors (s3, google drive, one drive, etc) sources now use.
