### ISSUE TITLE
Tiktok source - Removing end date or start date causes error

### ISSUE THREAD

**Issue by herbertstos** [airbytehq/airbyte#23460]
Hello
I’m trying to create a connection with the api to tiktok using airbyte, but whenever I remove the start date or end date that are marked as optional fields cause error, can anyone help me please?

Connection with end date and start date
![image](https://user-images.githubusercontent.com/31415553/221328311-c42f71fc-74e4-4558-a202-048dc811c41e.png)

Connection without end date

![image](https://user-images.githubusercontent.com/31415553/221328350-9c0f9b46-8e49-4a59-8cac-1df51e807e54.png)

Error:

The connection tests failed.
The provided configuration does not fulfill the specification. Errors: json schema validation failed when comparing the data to the json schema. Errors: $.end_date: does not match the regex pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ Schema: { "type" : "object", "title" : "TikTok Marketing Source Spec", "properties" : { "end_date" : { "type" : "string", "order" : 2, "title" : "End Date", "pattern" : "^[0-9]{4}-[0-9]{2}-[0-9]{2}$", "description" : "The date until which you'd like to replicate data for all incremental streams, in the format YYYY-MM-DD. All data generated between start_date and this date will be replicated. Not setting this option will result in always syncing the data till the current date." }, "start_date" : { "type" : "string", "order" : 1, "title" : "Replication Start Date", "default" : "2016-09-01", "pattern" : "^[0-9]{4}-[0-9]{2}-[0-9]{2}$", "description" : "The Start Date in format: YYYY-MM-DD. Any data before this date will not be replicated. If this parameter is not set, all data will be replicated." }, "credentials" : { "type" : "object", "oneOf" : [ { "type" : "object", "title" : "OAuth2.0", "required" : [ "app_id", "secret", "access_token" ], "properties" : { "app_id" : { "type" : "string", "title" : "App ID", "description" : "The Developer Application App ID.", "airbyte_secret" : true }, "secret" : { "type" : "string", "title" : "Secret", "description" : "The Developer Application Secret.", "airbyte_secret" : true }, "auth_type" : { "type" : "string", "const" : "oauth2.0", "order" : 0, "title" : "Auth Type" }, "access_token" : { "type" : "string", "title" : "Access Token", "description" : "Long-term Authorized Access Token.", "airbyte_secret" : true } } }, { "type" : "object", "title" : "Sandbox Access Token", "required" : [ "advertiser_id", "access_token" ], "properties" : { "auth_type" : { "type" : "string", "const" : "sandbox_access_token", "order" : 0, "title" : "Auth Type" }, "access_token" : { "type" : "string", "title" : "Access Token", "description" : "The long-term authorized access token.", "airbyte_secret" : true }, "advertiser_id" : { "type" : "string", "title" : "Advertiser ID", "description" : "The Advertiser ID which generated for the developer's Sandbox application." } } } ], "order" : 0, "title" : "Authentication Method", "default" : { }, "description" : "Authentication method" }, "report_granularity" : { "enum" : [ "LIFETIME", "DAY", "HOUR" ], "type" : "string", "order" : 3, "title" : "Report Aggregation Granularity", "description" : "The granularity used for aggregating performance data in reports. See <a href=\"https://docs.airbyte.com/integrations/sources/tiktok-marketing/#report-aggregation\">the docs</a>.", "airbyte_hidden" : true } } }

**Comment by marcosmarxm** [comment]
What version of Airbyte are you using?
