### ISSUE TITLE
Source Mongodb: Unable to connect to Airbyte -> Mongodb

### ISSUE THREAD

**Issue by itswadesh** [airbytehq/airbyte#23461]
![image](https://user-images.githubusercontent.com/1191896/221335016-f4af8fa2-14ad-437f-a0bd-63d23e28550d.png)

**Comment by sajarin** [comment]
Hey @itswadesh thanks for the issue. Can you double check to make sure you have the right hostname/connection string?

**Comment by RaguramanH** [comment]
This might sound weird but can u try connecting without the password?
