### ISSUE TITLE
Unable to install airbyte on GCP

### ISSUE THREAD

**Issue by minhajpasha** [airbytehq/airbyte#23463]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: GCP n2.
- **Deployment**:  
- 
- 
- https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine
- steps given as below mkdir airbyte && cd airbyte
curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte-platform/main/{.env,flags.yml,docker-compose.yaml}
docker compose up -d

## Logs
  # to read this volume to copy their configs to the database
  data:
    name: ${DATA_DOCKER_MOUNT}
  db:
    name: ${DB_DOCKER_MOUNT}
configs:
  flags:
    file: ./flags.yml
networks:
  airbyte_public:
  airbyte_internal:
mi1987@airbyte-demo:~/airbyte$ docker compose up -d
no configuration file provided: not found
mi1987@airbyte-demo:~/airbyte$ 

## Steps to Reproduce
1. just follow the link to install airbyte on gcp
2.
3.

## Are you willing to submit a PR?
<!--- 
No

**Comment by natalyjazzviolin** [comment]
Hey @minhajpasha, let's debug this first. Please make a post in the Slack channel or forum. We will reopen if there's a clear way of replicating this, closing for now.
