### ISSUE TITLE
Source MySQL -> BQ sync fails - "Could not find image: airbyte/source-mysql"

### ISSUE THREAD

**Issue by MattApril** [airbytehq/airbyte#23481]
## Environment
- **Airbyte versions**:  0.40.32
- **OS Version / Instance**: Debian 11
- **Deployment**: Docker CE
- **Source Connector and version**: MySQL
- **Destination Connector and version**: Google Big Query
- **Step where error happened**: Sync

## Current Behavior
I run weekly syncs, the first week or two it works, but then after 1-2 weeks/syncs I get the following errors:

1. Attempt 1: `Failure Origin: normalization, Message: Something went wrong during normalization` ([log](https://pastebin.com/Ez3GZiyP))
2. Attempt 2: `Failure Origin: airbyte_platform, Message: Something went wrong within the airbyte platform` ([log](https://pastebin.com/1WNCKYej))

# How to reproduce
Restarting the containers (`docker compose restart`) fixes the issue (manual and automatic syncs will work again for a week or two), but then the problem starts over. I was originally on v0.40.23 and the problem happened there as well.

**Comment by postamar** [comment]
Closing because this is an old issue, please to re-open if the problem persists.
