### ISSUE TITLE
Source ZohoCRM: Enable in Cloud

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23484]
## Tell us about the problem you're trying to solve
Enable in Cloud ZohoCRM source connector.
LastPass: Zoho CRM

**Comment by midavadim** [comment]
@YowanR 
This connector is not eligible for low code becuase 
- it has dynamic schemas
- current implementation support multithreading
@lazebnyi

**Comment by YowanR** [comment]
We should only aim to enable it in Cloud for Q1B -- thanks!

**Comment by rajeshDrivex** [comment]
why am i getting this error when im trying to make a connection, with same credentials im able to fetch the data using postman method.
error: "code":"OAUTH_SCOPE_MISMATCH","details":{},"message":"invalid oauth scope to access this URL","status":"error"
