### ISSUE TITLE
Source QuickBooks: Enable in Cloud

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23499]
## Tell us about the problem you're trying to solve
Enable in Cloud QuickBooks source connector.
LastPass: intuit.com quickbooks

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Quickbooks: Enable in Cloud](https://app.harvestr.io/components/0/list/aulgrPJzQ)
