### ISSUE TITLE
define a strategy for handling bad rows

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2352]
We need to define a strategy for how to address bad data in unstructured sources.

For example, in Google sheets, we have issues like https://github.com/airbytehq/airbyte/issues/2202 and the fact that a blank line (or any other bad lines of data) completely stop a sync. 

However, we also don't want to just fail silently if we are unable to read from a data source.

Ideally we define and document the expected behavior around cases like this so it's clear to connector developers what is the standard here and how to handle error cases.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093871521) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
We may need to output bad records into some sort of "bad records" location (like a cloud storage bucket).

We could also have functions to do things like custom truncations for large records for Redshift.

**Comment by cgardens** [comment]
handled in subsequent issues
