### ISSUE TITLE
Document mac special dns for localhost

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2353]
## Tell us about the documentation you'd like us to add or update
When running docker on mac, a container cannot reach a service exposed on the host machine by invoking `localhost`, it has to use the [special docker-mac dns](https://docs.docker.com/docker-for-mac/networking/) `host.docker.internal`. We have a few users who have been stuck on this and if you're not very familiar with docker, you don't think to do this and its hard to debug because the error is pretty generic. We should figure out how to make this as obvious as possible to our users.

## Are there any related areas of documentation that currently exist? Could you point to them? 
* Unclear if we should just be adding a warning about this in every database source / destination since that is the most common place it crops up. It's a very generic docker problem though, so it really could apply to alot of connectors. The problem is if we do a generic "how to handle localhost when running Airbyte on mac" how do we make it discoverable enough to users who don't know to look out for the problem.

**Comment by jrhizor** [comment]
It is here: https://docs.airbyte.io/faq/technical-support#connection-refused-errors-when-connecting-to-a-local-db but might be useful in more places. I think this is a general problem where it's hard to find the FAQ/what to do when there's a problem.

**Comment by cgardens** [comment]
eh. i think that's good enough for now.
