### ISSUE TITLE
Source Gitlab: 404 Client Error Not Found for url https://git.REDACTEDURL.com/api/v4/groups/1844/epics?per_page=50

### ISSUE THREAD

**Issue by itspooya** [airbytehq/airbyte#23541]
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: Debian 11
- **Deployment**: Kubernetes
- **Source Connector and version**: Gitlab Sync 1.0.1
- **Destination Connector and version**: PostgreSQL 0.3.26
- **Step where error happened**: Sync GitLab

## Current Behavior
GitLab Sync fails when there is some empty repository or milestone or group with Error 404 Not found
Failure Origin: source, Message: 404 Not Found

## Expected Behavior
I except it to just skip that part and continue syncing

## Logs
[f71d7e48_58a9_43f3_a964_2433e8695dbb_logs_14_txt.zip](https://github.com/airbytehq/airbyte/files/10849316/f71d7e48_58a9_43f3_a964_2433e8695dbb_logs_14_txt.zip)

## Steps to Reproduce
1. Setup source as Gitlab
2. Setup any destination
3. Have an empty repo(without branches) or group or milestone or something like that
4. Click sync
5. It fails with 404 not found

**Comment by marcosmarxm** [comment]
I added the issue to backlog. Are you able to try manually the request and see it works?

**Comment by itspooya** [comment]
I tried syncing manually and it didn't work
