### ISSUE TITLE
Source Freshsales: Enable in Cloud

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23555]
## Tell us about the problem you're trying to solve
Enable in Cloud Freshsales source connector.
LastPass: Freshsales

**Comment by bazarnov** [comment]
Based on [Will it Low-Code?](https://docs.google.com/document/u/0/d/1E5o3rRLVkOJ6YaluJzYKu6LtpRauJ3lc4exMYtfj5B0/edit),  `source-freshsales` could be migrated to Low-Code with no additional components.
