### ISSUE TITLE
Publish pre-release versions for connectors

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#23575]
## Tell us about the problem you're trying to solve

In the Multiple Connector Versions project we will enable the ability to override which version of a connector can run. This overridden version can be for unreleased changes that we want to validate within a controlled environment or for specific customers in prod.

Currently our publish workflow is meant to release the new version to everyone. 

## Describe the solution you’d like

Add a new `prerelease` flag to the `/publish` command to enable publishing to docker hub without updating the catalog.

This should do a few things:
1. Don't make changes to source_definitions or destination_definitions yamls.
2. Append some information to the published tag
    - This should be in the format `-preview.[commit]`
    - Example: `airbyte/source-faker:1.2.3-preview.b3a2b0` where `1.2.3` comes from the Dockerfile as usual, and `b3a2b0` is the commit hash.
3. Don't set the `latest` docker tag to this version

### Notes

- Bumping the definitions is currently controlled by the publish command's `auto-bump-version` flag. 

## Additional context

This is part of phase 1 from [[Tech Spec] Multiple Connector Versions](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI/)

Look in `manage.sh` script + Github Action

**Comment by evantahler** [comment]
Grooming
* How does `check-image-exists` come into play?  If docker tags are unique (using the commit hash) then it should not have a problem

FUTURE (when merge to master happens)
* a manual dispatch action! (pick the branch/PR and it will run)
