### ISSUE TITLE
Look up or create actor definition versions when processing overrides

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#23579]
## Tell us about the problem you're trying to solve

In preparation for LaunchDarkly support, we'll need to start using the versions from the actor_definition_version table. For now we can apply this logic for the static overrides.

## Describe the solution you’d like

Using the new method introduced in #23573, we can consider these overrides to determine the version to use. When reading the version:
- If it's not present in the actor_definition_version_table, fetch the spec for the connector and store an entry for this version.
- If it's present, return the information stored in the actor_definition_version table.

For more details on what this looks like, see tech spec.

## Additional context

This is phase 3 of[ [Tech Spec] Multiple Connector Versions](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI/)

**Comment by pedroslopez** [comment]
To tackle this we'll need to sync up with Cole to add a new context that allows us to target based on actor definition IDs

**Comment by pedroslopez** [comment]
This flow will look something like this

![image.png](https://images.zenhubusercontent.com/62585178f8599f85447ea63f/5d5fe7ae-e56b-4130-8bed-d1be398069da)

**Comment by evantahler** [comment]
Grooming:

* Eventually the YAML overrides will go away.  
*

**Comment by bnchrch** [comment]
Example url to retrieve version specific metadata info

https://connectors.airbyte.com/files/metadata/airbyte/source-s3/2.1.4/metadata.yaml
