### ISSUE TITLE
Don't call list_latest if not needed

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#23595]
We currently call a wild mix out of `list_latest` and `list_for_workspace` APIs when trying to get source/destination definitions.

We should evaluate in which places we really need the `list_latest` and in all other places only request from `list_for_workspace`.

Likely nothing outside the Source/Destinations page need to call `list_latest`.

**Comment by evantahler** [comment]
Here's the only(?) valid use case I know - OSS only. I'm running `source-github@0.3.11` but I could be running `source-github@0.4.1` and there's a button to make the change 
<img width="1518" alt="Screenshot 2023-02-28 at 1 11 31 PM" src="https://user-images.githubusercontent.com/303226/221981701-3dec85c1-2d05-49ac-bdad-aacda876e7a0.png">

**Comment by josephkmh** [comment]
Just double checked, indeed we only need `list_latest` on the settings pages, both for individual source/destination updates and the "Upgrade all" button.

If no one is working on this already, we can pick it up in the Compose team, since it's in "our" slice of the UI.

**Comment by evantahler** [comment]
Hi @josephkmh / @timroes! I'm just checking that this issue found a home.  We think that after this change, we won't need to make any platform changes as there should be no need for Cloud to call list_latest. (re: https://github.com/airbytehq/airbyte/issues/23597)

**Comment by josephkmh** [comment]
PR needs one more fix that I won't get to until Thursday, but I imagine it will go out on the daily deploy on Thursday.
