### ISSUE TITLE
Source Xero: Enable in Cloud

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23615]
## Tell us about the problem you're trying to solve
Enable in Cloud Xero source connector.
LastPass: Xero Sandbox Account
Predefined demo
OAuth app LastPass: Xero Primary Public App
Docs:
[Predefined demo](https://central.xero.com/s/#democoguide)
[Guide](https://developer.xero.com/documentation/getting-started-guide/)

**Comment by grubberr** [comment]
airbyte/source-xero:0.2.0 on cloud
