### ISSUE TITLE
Stream status page "Stream Details" action

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#23638]
Figma's linked in [the epic](https://github.com/airbytehq/airbyte/issues/23345)
Blocked by https://github.com/airbytehq/airbyte/issues/23637

The streams table action menu `Open details` should take the user to the replication page and open the stream details panel for that stream.

**Comment by edmundito** [comment]
@krishnaglick I think this was removed from v1

**Comment by krishnaglick** [comment]
Since we have the "go to stream on replication page" it made sense to extend that to this, where we move over and open the details panel on that page.

**Comment by edmundito** [comment]
To confirm, the v2 scope is that the stream details opens in the existing details page and the stream can be saved directly from the panel. But this only covers v1, which is open the stream int he replication settings page.
