### ISSUE TITLE
Create a Postgres RDS destination

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#23641]
Initially, this can be a wrapper around destination-postgres, similar to how we wrap source-postgres in source-alloydb. In the long run, we will add RDS specific features such as AIM authentication and S3 staging.

**Comment by evantahler** [comment]
We do not want to make any more 'wrapper' connectors.  Instead, we will make a way for the same connector to have 'aliases' (e.g. multiple names), so we don't have extra connectors to manage.

**Comment by itaseskii** [comment]
Hey @evantahler this is not a simple wrapper for the Postgres connector. The new connector contains support for IAM authentication https://github.com/airbytehq/airbyte/issues/23643 and the ability to stage data in S3 https://github.com/airbytehq/airbyte/issues/23517 so there is quite a bit of modification on it.

**Comment by evantahler** [comment]
Ah ha!  Ok - reopening!
