### ISSUE TITLE
Source Github: if teams stream doesn't exist, don't fail sync because of it

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2365]
## Expected Behavior
in cases like #2361 the Teams stream doesn't exist for the given repository. In this case, we shouldn't fail the whole sync. Instead, we should just sync no records and move along to the next stream, outputting a warning message. We should also document this in the github connector docs. 

## Severity of the bug for you
medium -- this is a recurring issue that users ask about

**Comment by marcosmarxm** [comment]
@sherifnada I saw this [PR](https://github.com/singer-io/tap-github/pull/107) in singer-tap Github probably correcting this. It's a small change.
