### ISSUE TITLE
Source Mixpanel: data is being loaded, but the airbyte says sync failed

### ISSUE THREAD

**Issue by sharath-rama** [airbytehq/airbyte#23662]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: Mac Ventura 13.1
- **Deployment**: Docker on ec2
- **Source Connector and version**:  Mixpanel 0.1.30
- **Destination Connector and version**:  Redshift 0.3.56
- **Step where error happened**: Sync

## Current Behavior
In the Mixpanel connector details, I left the End Date to blank, so that it captures the data whatever latest is available.
Sync is running, I see the records are being read. 
At the end, it says to-date cannot be greater date and it fails.
Surprisingly, I see the data is being loaded even though the job is failed.

I have slack notifications enabled, even though the data is being loaded, getting a notification that job is failed is troubling me.

## Expected Behavior
Should load whatever latest data is there for that moment and sync job should be successful.

## Steps to Reproduce
1.
2.
3.

[d059fece_e814_41f4_a343_90b248c5e32f_logs_195_txt.txt](https://github.com/airbytehq/airbyte/files/10869863/d059fece_e814_41f4_a343_90b248c5e32f_logs_195_txt.txt)

**Comment by davydov-d** [comment]
hey @sharath-rama did you fill the project time zone in the input config? is it the same that's in your mixpanel project settings?
