### ISSUE TITLE
Source File: integer column is given as string for large files.

### ISSUE THREAD

**Issue by rishabh-cldcvr** [airbytehq/airbyte#23683]
## Environment
- **OS Version / Instance**: macOS
- **Source Connector and version**:airbyte/source-file:0.2.33
- **Step where error happened**: discover source

## Current Behavior
When we have very large file with over 10k records in csv, integer column for csv file is depicted as string where all columns are integer in my file. This works when we have file with less than 10k records.

## Expected Behavior
All number columns should be number.

## Steps to Reproduce
1. Run discover for csv file over 10k records with column as integer

##Solution
![image](https://user-images.githubusercontent.com/65937969/222509924-c850f3e9-3ccc-4d9f-8078-4305cfd444cd.png)
 this line here will never get true for subsequent batch run and fallback to string.
## Are you willing to submit a PR?
yes

**Comment by marcosmarxm** [comment]
@rishabh-cldcvr let me know if you need any assistance to submit a fix
