### ISSUE TITLE
Make the Delete button work properly in the UI

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#23685]
![Screenshot 2023-03-02 at 1.22.53 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/e1f7bf8f-f752-49a0-9fbf-68a84e535777)

Currently clicking on the "delete" button does not have any UI feedback, although it does tombstone the cloud workspace. We should improve the UX here by making some adjustments to the frontend.

Acceptance criteria:
- Clicking on Delete opens a modal where a user is prompted to type in the name of the workspace to confirm
- Once the user fills in the workspace name and clicks Delete in the modal, the delete request is sent
- The delete button enters a loading state while delete request is pending
  - If success, redirect user to /workspaces after workspace deletion request
  - If error, display a toast message indicating something went wrong with the workspace deletion request
- User is redirected to /workspaces if they try to manually enter the URL of a deleted workspace

**Comment by harshmange44** [comment]
This is already done ig?

**Comment by tealjulia** [comment]
> This is already done ig?

I've updated the issue description.  OSS does not have a Workspace Settings page, but our Cloud offering does.

**Comment by tealjulia** [comment]
Related issue from oncall backlog https://github.com/airbytehq/oncall/issues/540

**Comment by josephkmh** [comment]
Refining notes:
- Deletion endpoint actually sees to be working correctly (workspace is tombstoned), but connections are not marked as deprecated. This is not expected behavior, so we should escalate this to oncall @mfsiega-airbyte 

- Pending investigation, we should split this into two tickets:
  - Make sure deletion works properly
  - Currently it's a little dangerous, a simple button click could delete a workspace. We should add a "type workspace name to confirm" mechanism
- Related issue: https://github.com/airbytehq/airbyte-platform-internal/issues/2671

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- We should make sure delete workspace behaves as expected.
- TODO: figure out what exactly works unexpectedly.
- One proposal - eliminate the `includeTombstoned` workspaces flag, split it into two methods, go through the non-compiling callsites and review them all.
- We want to pick this up next sprint.

**Comment by josephkmh** [comment]
Findings from a quick test:

1. I created this workspace, ran a sync, then deleted it: https://cloud.airbyte.com/workspaces/aebcbcae-0e0b-45d7-b017-e64f146d9714
2. `workspace.tombstone` is correctly set to `true`
3. It's still accessible when you enter the URL directly, but it does not show up in the workspace list
4. Running a sync works even if the workspace is tombstoned: https://cloud.airbyte.com/workspaces/aebcbcae-0e0b-45d7-b017-e64f146d9714/connections/97a74071-0e41-40fb-95b5-0e76f13e0618/status
5. Setting up a source still works even if the workspace is tombstoned https://cloud.airbyte.com/workspaces/aebcbcae-0e0b-45d7-b017-e64f146d9714/source/a343792b-6116-455b-bef1-357f60bc2cec
6. Updating the workspace still works even if it's deleted (e.g. changing workspace name or settings)

**Comment by tealjulia** [comment]
Sounds great, feel free to replace!

I do wonder if we, in addition to redirecting, want to show a "success" toast upon success.

**Comment by tealjulia** [comment]
Do we have an issue tracking the backend work/do we want one?

It sounds like if a workspace is "tombstoned", we would want the server to 404, and for the "tombstone" state to cascade to connections, sources, and destinations.  It also sounds like the backend work is (currently) a lower priority than the frontend work.  But I don't want it getting lost.

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- Check out https://github.com/airbytehq/airbyte-platform-internal/issues/2671
- High-level: workspace and any resources tied to it should 404 (sharp corner: billing).
- For now, see if we can achieve ^ in the front-end.
