### ISSUE TITLE
FE: Allow filtering of credits usage by date period

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#23694]
Allow filtering of data by date range:
30 days
6 months
1 year

Applying a filter will make an API call. The results will affect the entire page.

Figma: https://www.figma.com/proto/568DVwWXTcagwhoB2r1Qke/01_01_BILLING?node-id=714%3A8936&scaling=min-zoom&page-id=714%3A7293&starting-point-node-id=714%3A8936

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- Backend changes are ready to review.
