### ISSUE TITLE
Add MongoDB as Destination

### ISSUE THREAD

**Issue by Squeeezeee** [airbytehq/airbyte#2369]
## Tell us about the new integration you’d like to have
Which source and which destination? Which frequency?
Couple of projects that we are working on usually have an HTTP Request as Source (classic API) where we are collecting terabytes of data (news articles, posts, crawled websites content...). Of course the size is of request is defined via parameters and frequency may differ but for this case lets say its on a daily base.

Now as you all know each API is different, schema of API is different, we could build our own connector which would collect all of that RAW data and store it in NoSQL (i.e. MongoDB) as it is without formatting or use AirByte which already does a job ( and if I may say it does it very well! ).

We would like to have a MongoDB as destination, where I would be able to enter MongoDB credentials (i.e. get them from MongoDB atlas and connect via that) and have multiple sources (http requests) feed in data to MongoDB, each http request would be a collection and data coming in from same request would be stored in those collections.

## Describe the context around this new integration
Which team in your company wants this integration, what for? This helps us understand the use case.

Currently all the jobs described above are done by our backend/data team, where we are creating custom pipeline scripts to get the data from APIs and store them in monogodb or mysql (depending if its schema depended). Another case that I would like to mention is following:

S3 Bucket as source with CSV and JSON files, some of the APIs offers that you can download mass data through CSV or JSON so that could be a potential source also and MongoDB would be a destination.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Well really its that you build your own pipeline scripts and let them run. Why I like Airbyte solution is because it offers us dynamic approach i.e. tomorrow new source comes in we just plug n play. Same goes for destinations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368094137561) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@Squeeezeee Thanks for creating this request! We would definitely love to support MongoDB as a destination. 

if I'm understanding this correctly, types are not a first class citizen in Mongo, right? Meaning, I can just write JSON to a Collection without specifying a schema upfront and Mongo would just "figure it out". 

If so, I think writing a Mongo destination should be fairly straightforward, as the Airbyte protocol communicates using JSON records. So all we'd be doing in the Mongo destination would be basically piping records from the source into the destination. 

Would you be interested in contributing this? FWIW currently the easiest way to write a destination is in Java.

**Comment by Squeeezeee** [comment]
> @Squeeezeee Thanks for creating this request! We would definitely love to support MongoDB as a destination.
> 
> if I'm understanding this correctly, types are not a first class citizen in Mongo, right? Meaning, I can just write JSON to a Collection without specifying a schema upfront and Mongo would just "figure it out".
> 
> If so, I think writing a Mongo destination should be fairly straightforward, as the Airbyte protocol communicates using JSON records. So all we'd be doing in the Mongo destination would be basically piping records from the source into the destination.
> 
> Would you be interested in contributing this? FWIW currently the easiest way to write a destination is in Java.

Hello @sherifnada, Thank you for quick reply. Yes indeed your understanding is correct.
You can write any schema upfront and if lets say there is new data with changed schema it will be written in same collection without breaking down. Hence the beauty of MongoDB as destination. Just the point is if let say there are multiple sources for same destination (same mongoDB which would be great to be compatible with MongoDB atlas) that each source is a new collection or at least you can choose collection from UI or create new one, so you have some control of flow.

Re contribution, I am myself a PHP programmer (last line of code written 4-5 years ago :( dont blame, went to other waters).
But I am more than willing to pay for contribution or effort what ever makes really sense. So if there is a person willing to do this I am willing to sponsor this issue.
Please do let me know?

**Comment by andriikorotkov** [comment]
Hello **@sherifnada**. I am currently working on mongodb destination. I have a question about normalizing data that was taken from a relational database (MySQL, Postgres, ect.). It is better to explain with an example.
 I have two tables in the source that are linked as many-to-many through another table (For example _"students", "classes"_ and "_students_classes"_ tables). 
Now I have made a new destination, which for each such table will create a new collection in monogodb. Three such tables in the source will be converted to three collections in mongodb. Does it work correctly? 
Or does the mongodb destination need to process three streams, and collect them into one document and write this document into one collection? Something like this - _"studens"_ collection
`{
		"id":3,
		"f_name":"John",
		"l_name":"Doe",
		"classes": [{
			"id":1,
			"name": "some_class"
		}, ....
		]
	}`

**Comment by sherifnada** [comment]
@andriikorotkov three collections is the right way to go here.
