### ISSUE TITLE
Diff is shown after refreshing schema to restored field or stream

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#23702]
This is a case when using discover_schema (or connections/get withRefreshedCatalog) where the response contains a diff for a field that has not changed.

## Steps to reproduce
1. Create a connection with a postgres source
2. Remove a column from one of the postgres tables
3. Refresh the connection schema (don't save)
4. Re-add the same column back to the postgres table
5. Refresh the connection schema

## Expected
Toast with "No changes were detected"

## Actual
Diff modal appears with no diffs

**Comment by pmossman** [comment]
@nataliekwong we skipped this one for today but let us know if you want to discuss it async in Slack

**Comment by nataliekwong** [comment]
Thanks @pmossman , I was triaging several issues and didn't realize this ended up in the view. 

I'll close this for now since we have another issue for the Frontend about schema diffs.
