### ISSUE TITLE
Front-end support destination sync modes

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2371]
## Tell us about the problem you're trying to solve
As part of #2337, we would like to introduce a new configuration enum for sync modes on the destination side.
This would include the different deduplication options and should be configurable on the Sync/Connection page for each stream (similar to the source sync mode: Full refresh/incremental and how to select the required cursor fields when it is incremental)

## Describe the solution you’d like

The mock-up shows the options of how to select one of the values for a single sync mode in the UI.

This is translated into two enums on the back-end:
- source `sync_mode`
- `destination_sync_mode`

The supported combinations of source x destination sync modes are:
- Full Refresh x overwrite: same as before
- Full Refresh x append: source is transmitting the full content of the stream and destination keep appending to the same table (useful to detect deletions from one sync to the next, until CDC is supported with incremental)
- Incremental x append: same as before
- Incremental x append_dedup: the final table is deduplicated by the primary key but a new table with suffix `_scd` is also created and retain the full history (same as Incremental - Append)

(can we make sure to have a `?` button or some texts to link to a documentation page where we will write more about the different modes and their behaviors)

These are configurable in the API on the `AirbyteStreamConfiguration` object (already merged in master) and is later translated into  `ConfiguredAirbyteStream` from `ConfiguredAirbyteCatalog` objects.

For some of the options, extra fields are sometimes required such as `cursorField` or `primaryKey` (same locations in the API object as the sync modes.

Note that `AirbyteStream` objects in the API also provides metadata from sources to inform about default `cursorField` and it now has also default `primaryKey` (the fields are present but that work is not done on the source side yet, so they would always be empty for the moment). However, whenever those metadata will surface, the UI should be able to make use of them to pre-fill the forms.

Pre-requisites for the deduplicating functionality are:
1. In the case of dedupe options, we require the selection of primary keys for a stream (this should be one or multiple columns from a stream).
1. It is also mandatory to define cursor fields for deduping (to order rows of data for the same primary key and identify which is the latest one)
1. Note that only destinations that have basic normalization capabilities (enabled?) would be able to dedupe data for the moment.

For incremental mode, the pre-requisite is still to have a cursor field defined

- [x] Mock-up of UI where we separate the source sync modes and destination sync modes
- [x] Depends on #2370 
- [ ] Front-end implementation to read/write to the new API objects

![Screenshot 2021-03-15 at 20 02 42](https://user-images.githubusercontent.com/7718175/111207200-99c9ec00-85c9-11eb-9114-22adde2e63b4.png)

## Additional context
https://docs.google.com/document/d/1uHGz-soEdGcAe4Mgf0nqUpst6NszkTGL5aJivJ4qxpM/edit#

**Comment by ChristopheDuong** [comment]
Draft of mock up is done here: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=22837%3A22

**Comment by ChristopheDuong** [comment]
@johnlafleur, on the back-end side, we are separating the `source_sync_mode` and `destination_sync_mode` in two separate enums, so you would be able to combine them as you want independently.

For example, it is possible to do "Full Refresh" on the source with "Append" in the destination: 

One of the use case could be:
![Screenshot 2021-03-10 at 11 40 01](https://user-images.githubusercontent.com/7718175/110617246-bca56c00-8195-11eb-9a72-78bf1ac1b012.png)
![Screenshot 2021-03-10 at 11 39 14](https://user-images.githubusercontent.com/7718175/110617264-c202b680-8195-11eb-9947-0f188688d666.png)

- If Andrey were to use "incremental - Append" then he wouldn't know when some users have been deleted/dropped from the source tables (unless we support CDC).
- But if he goes with "Full Refresh", the data will be dropped from the destination at every run, whereas he doesn't want to drop old data rows.

So a "full refresh" every-day will produce a full snapshot of the directory and thanks to "Append", he would have a view of both add/deletions/updates/etc with their history through time.

**Comment by ChristopheDuong** [comment]
Another valid example would be to do "Full Refresh" with "dedupe" too...

If your source has a history view of events (primary key event_id) but in the destination, you somehow want to keep only the latest row per user (per user_id).

Then it's also a debate of if you want to support that ELT logic in Airbyte's UI or in post-processing Transformation in a dedicated T tool that you run on your own...

**Comment by ChristopheDuong** [comment]
Another comment is on the "primary key" selection:
>  (this should be one or multiple columns from a stream). A proposed solution would have to display a checkbox in front of each column.

So instead of a drop-down button, it might be better to have a list of column names for the stream and the ability to select/unselect checkboxes to include/exclude the ones that form the primary key?

**Comment by ChristopheDuong** [comment]
Mock-ups are ready for "Destination Sync Mode" with pop-ups style widgets to select cursor-fields and primary keys

**Comment by ChristopheDuong** [comment]
John also added the next level UI improvement too (for when you have to edit hundreds of streams for example) with batch- edit:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=23230%3A746 

Maybe we can separate that one in a second front-end issue?

**Comment by cgardens** [comment]
@Jamakase For this issues let's do option 3 in the mock up: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=23450%3A44

**Comment by cgardens** [comment]
To clarify the expected values in the drop down. up to 3 values might be present. it can be less depending on the what the stream supports.

![Screen Shot 2021-03-22 at 11 43 46 AM](https://user-images.githubusercontent.com/9092207/112041697-ecdcfb00-8b03-11eb-9bc6-f8d02fd2d86e.png)

**Comment by ChristopheDuong** [comment]
> To clarify the expected values in the drop down. up to 3 values might be present. it can be less depending on the what the stream supports.
> 
> ![Screen Shot 2021-03-22 at 11 43 46 AM](https://user-images.githubusercontent.com/9092207/112041697-ecdcfb00-8b03-11eb-9bc6-f8d02fd2d86e.png)

Yes, for the UI "Incremental - deduped + story"

> only destinations that have basic normalization capabilities (enabled?) would be able to dedupe data for the moment.
