### ISSUE TITLE
Slack link in the README requires '@airbyte.io' email

### ISSUE THREAD

**Issue by BubbaJoe** [airbytehq/airbyte#23717]
Hello,

I am trying to join the slack channel but it requires me to have a specific email. Is this on purpose?

Purpose of join:
I am trying to join slack to get support on testing custom connectors in the UI, but I didn't want to open an issue on github at first.

**Comment by sajarin** [comment]
Hey @BubbaJoe, does the link on our community page work: https://airbyte.com/community?

**Comment by sajarin** [comment]
Closing this for now, if other users report the same issue will reopen. Welcome to the community!

**Comment by neeraj-ec** [comment]
@sajarin Even the links on https://airbyte.com/community requires you to sign-in using airbyte email.
I didn't find any way to join the slack channels.
