### ISSUE TITLE
Unable to open Airbyte public API Documentation

### ISSUE THREAD

**Issue by Sahith-8055** [airbytehq/airbyte#23720]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**: macOS

## Current Behavior
*When trying to open the Public API documentation hosted on AWS, I get "Error Loading the Spec"*.

I'm using Microsoft Edge as my browser. Other browser which I had tried opening in includes Safari and Google Chrome.

## Expected Behavior
*The URL of Airbyte API Documentation which is publicly available should open.*

## Logs

<img width="1508" alt="Screenshot 2023-03-03 at 2 35 14 PM" src="https://user-images.githubusercontent.com/41897310/222694398-f83801e3-28ae-4301-8fea-57ced23446ac.png">

## Steps to Reproduce
1. Get the link from Airbyte Docs.
2. Try opening it in Microsoft Edge / Safari / Google Chrome (Either in Incognito or normal browsing window).
3. We should be able to see the log mentioned above.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
From what Airbyte documentation are you getting this file?

The API docs are 
https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/source_definitions/list
<img width="985" alt="image" src="https://user-images.githubusercontent.com/5154322/222695215-61fb1b26-b3a6-4bc5-9c53-8cd162ae2ea0.png">

**Comment by Sahith-8055** [comment]
Thanks @marcosmarxm for pointing out the URL. But, I was using the same URL and tried to open the same. Still, I don't see any difference in the behaviour.

**Comment by Sahith-8055** [comment]
Can anyone help me in overcoming this issue of not able to access the Documentation?

**Comment by marcosmarxm** [comment]
@Sahith-8055 where did you found this url? Can you point it so we can fix it?
Airbyte move the platform to `airbyte-platform` the file now is located here: https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-api/src/main/openapi/config.yaml

**Comment by Sahith-8055** [comment]
I've found the URL from the below mentioned link -
[Airbyte API Documentation](https://docs.airbyte.com/api-documentation/)

After opening that link, I went to Documentation row and clicked on the link (which was the same that you've provided) which redirected me to the below link -
[Public API Documentation](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html)

**Comment by Sahith-8055** [comment]
Hi, can anyone help me overcome this issue?
