### ISSUE TITLE
Links on docs for comparing airbyte seems broken

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2374]
## Expected Behavior
*Tell us what should happen.*

Links (with gitbook?) from https://docs.airbyte.io/faq/differences-with should bring visitors to the right comparison page.

## Current Behavior
*Tell us what happens instead of the expected behavior.*

![Screenshot 2021-03-09 at 14 20 21](https://user-images.githubusercontent.com/7718175/110476803-b2766580-80e2-11eb-84ec-5a72204d14f4.png)
 
even though the page on GitHub works fine:
https://github.com/airbytehq/airbyte/blob/master/docs/faq/differences-with/singer-vs-airbyte.md

**Comment by michel-tricot** [comment]
I must have broke it with my recent change to the doc. I will fix it.
