### ISSUE TITLE
Destination-Snowflake : TMP table is not getting cleaned up

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#23751]
Hi Team,
Issue:
    Numerous tables has been created and it is not getting cleaned up upon job complete.

Usecase:
We are using airbyte to sync more than 200 tables to snowflake and I can see TMP table are empty however, it is not getting dropped.

Example:

_AIRBYTE_TMP_<tablename>

Workaround:
     Run a script to delete the TMP tables daily using airflow.

**Comment by grishick** [comment]
Starting with `destination-snowflake-0.4.46` destination-snowflake no longer creates tmp tables.
