### ISSUE TITLE
Google Ads: deprecated v11 API (Sunset March 31 2023)

### ISSUE THREAD

**Issue by jacobHclarkson** [airbytehq/airbyte#23774]
## Tell us about the problem you're trying to solve
Google Ads V11 is going to be sunset soon: https://developers.google.com/google-ads/api/docs/sunset-dates

## Describe the solution you’d like
Airbyte should use a newer version (ideally V13).

**Comment by sajarin** [comment]
Thanks for the issue @jacobHclarkson, upgrading to v12 or v13 will likely require a significant refactor of the Google Ads connector and will likely break backwards compatibility. Nonetheless, the upgrade is inevitable. Thanks for making this issue!

**Comment by vitormd** [comment]
Since this is a "verified" connector, I won't touch it until there is a positioning from the airbyte team, but me and another person from my company could try to give this PR a try since we can have Google Ads off for a few days in any case

**Comment by YowanR** [comment]
Hi everyone! Thanks for bringing this to our attention. We're actively working on this issue and we should have an update for you next week :)
