### ISSUE TITLE
Airbyte not overwriting data when changing 'Destination Stream Prefix' to platform created folder

### ISSUE THREAD

**Issue by gabe-martins** [airbytehq/airbyte#23780]
I would like to understand why when I change the 'Destination Stream Prefix' of the root of **Blob Storage** to a folder created by the platform, Airbyte stops overwriting and performs the task as if it were **"Full Refresh | Append"** even though I am using **"Full Refresh | Overwrite"**?

**Comment by nataliekwong** [comment]
Hey @gabe-martins , since it's been a while since we last heard from you on this issue, I'll go ahead and close it. If you have more questions on why this is happening, feel free to reach out or re-open the issue.
