### ISSUE TITLE
Source Google Search Console: Sync "Discover" Data

### ISSUE THREAD

**Issue by llmuculusll** [airbytehq/airbyte#23784]
Google search console has important data about "Search Result" and "Google Discover".
But Google Search Console Airbyte Source only has "Search Result" data, I think it is important to sync "Google Discover" data by     Search Console Source too.

![Screenshot from 2023-03-06 23-53-39](https://user-images.githubusercontent.com/883346/223222394-9f624d9b-ad03-4af0-82d8-bd3b6b0b6bbe.png)

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Google Search Console: Add Discover Stream](https://app.harvestr.io/components/0/list/hQr5umSAQ)

**Comment by llmuculusll** [comment]
I created a pull request for this issue:
https://github.com/airbytehq/airbyte/pull/23883
