### ISSUE TITLE
migration should not upgrade base64 schema to BinaryData

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#23802]
we saw some failures in the binarydata type, where we assumed that any source declaring `{type: string, encoding: base64}` could be upgraded to `{$ref: BinaryData}`. This caused failures in normalization - figure out why, and fix it.

decision: modify migration to make this `{$ref: string}`

**Comment by grishick** [comment]
Notes from grooming:
 - these changes are for upgrade/downgrade code that performs schema migrations in platform
 - these changes are not in normalization, but in `airbyte-platform-internal`
 - this is required for v1 rollout

**Comment by grishick** [comment]
Notes from grooming:
 - these changes are for upgrade/downgrade code that performs schema migrations in platform
 - these changes are not in normalization, but in `airbyte-platform-internal`
 - this is required for v1 rollout

**Comment by etsybaev** [comment]
Aa agreed with @grishick  - created a draft PR. Greg, should we move this ticket to "onHold" ? Thanks

**Comment by edgao** [comment]
closing this for now, let's revisit later. The world will probably look very different when we get back to this.
