### ISSUE TITLE
Update WellKnownTypes to make all types explicitly nullable

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#23803]
replace all the `type: foo` with
```yaml
type:
- "null"
- foo
```

and verify that the schema validator doesn't trigger on explicit null values.

**Comment by grishick** [comment]
Notes from grooming:
 - this is not required for v1 rollout
 - this is needed to reduce noise from JSON Schema validator
 - this is a protocol change that will have to go through review process

**Comment by edgao** [comment]
protocol change process https://www.notion.so/Protocol-Change-Process-64877a3d60564884bda07dc5dea8b4af
