### ISSUE TITLE
Phase 1 of DB sources refactoring

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#23808]
Can find the tech spec here : https://docs.google.com/document/d/15xFQ0EX9K_IfX_bPt-wCfhYYwkVqW2IvvbTvWKgyYRg/edit#heading=h.eds8ikoyuyn1

Some cleanup ideas
- Move methods into utility classes
- Figure out which methods are only used in a couple of sub-classes and pull them up to their subclasses
- Some code may be duplicated in `AbstractJdbcSource` and `AbstractDbSource` since the former would no longer inheirit from the former

**Comment by prateekmukhedkar** [comment]
Refactoring change. Impact: Reduce blast radius when making a change.

**Comment by akashkulk** [comment]
closing in favor of epic : https://github.com/airbytehq/airbyte/issues/24430
