### ISSUE TITLE
Add Customer Satisfaction to Freshservice connector

### ISSUE THREAD

**Issue by aroder** [airbytehq/airbyte#23804]
## Tell us about the problem you're trying to solve
Please add customer satisfaction survey results as a stream

## Describe the solution you’d like
Customer satisfaction survey results as a new stream

## Describe the alternative you’ve considered or used
Not sure

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source Freshservice: Add Customer Satisfaction stream](https://app.harvestr.io/components/0/list/tdncyGJ0E)
