### ISSUE TITLE
Transformations page overhaul

### ISSUE THREAD

**Issue by jeff-skoldberg-ct** [airbytehq/airbyte#23807]
## Tell us about the problem you're trying to solve
I think the Transformations page needs some love!

- You should be able to re-order transformations. Right now they all add to the bottom, so you may have to re-do everything if you need to add a step at the beginning.
- There should be parameters for environment variables, target name, default schema, etc. when filling out the form.
- You should be able to run just the transformations to see if your config is correct without running the entire sync.
- You should be able to see the entire DAG, connector, Tables made by the connector, plus your transformations on top.  Fivetran just rolled out a nice DAG - would like to see similar in Airbyte.

**Comment by jeff-skoldberg-gmds** [comment]
> Hey @jeff-skoldberg-gmds ! Chiming in from the product side here - to be transparent, we haven't seen much adoption for a native integration with dbt. As our platform team is currently developing core features for Airbyte Enterprise and enhancements to features like schema propagation, we aren't able to prioritize enhancing the dbt transformation feature today as it doesn't directly relate the core product (extract & load).
> 
> These suggestions are certainly valuable, which is why we'll keep this open! It's certainly sparked a conversation internally around when we can deliver improvements for this feature.
> 
> For more details on what we're working on, you can always reference our roadmap [here](https://github.com/orgs/airbytehq/projects/37/views/1).

That's awesome.  Thank you so much for the reply, @nataliekwong !!

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated the custom dbt transformation feature](https://github.com/airbytehq/airbyte/discussions/34860).
