### ISSUE TITLE
Share communication guidelines on new connector OC issues

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#23812]
We want OC engineers to follow the communication guidelines we've declared [here](https://github.com/airbytehq/oncall/blob/main/docs/team_specific/connectors/communication_guidelines.md).
These are not always follows. I suggest making the Octavia bot post on each new issue to remind the expected communication guidelines. This will be easier for engineers to copy and paste the expected template.

This will probably require an addition to the Worfklow actions repo [here](https://github.com/airbytehq/workflow-actions).

**Comment by evantahler** [comment]
Grooming:

* Bot Comment vs New Issue Template?
  * Templates are likely easier to modify/add
* Should only appear for new connector issue
* Sentry-created issues don't use the template.  But, we want this applied there too.
* probably don't use workflow-actions for this, use a one-off github action to add the comment.
