### ISSUE TITLE
Add helpful `description`s and `example`s to every field in the declarative_component_schema

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#23837]
## Context

We would like to show more helpful tooltips in the Connector Builder, instead of the brief descriptions that are currently hardcoded into the webapp.

In order to keep these descriptions close to the implementation so that they don't get out of sync with the field structure, these descriptions should be added to the [declarative_component_schema.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml)

## Acceptance criteria:
- Every field in the declarative_component_schema has each of the following:
  - `title` - a human-readable title that can be displayed in the builder as the label for that input
  - `description` - a helpful description explaining what the field is, why a user may want to use it, what the consequences of setting it are, etc.
  - `examples` - an array of example values that can be displayed in the tooltip, similar to the [examples provided in connector specs](https://github.com/airbytehq/airbyte/blob/f25f9eccc57930ba4bad49326c0766192d57948b/airbyte-config/init/src/main/resources/seed/source_specs.yaml#L853-L855)
- The above descriptions are reviewed by the docs team / solutions engineering to ensure they are clear and helpful

**Comment by lmossman** [comment]
Grooming notes:
- A lot of the python code already has these descriptions, so that can be used as a basis

**Comment by girarda** [comment]
feedback from last build a connectors session:
> Update Path URL tooltip to make it clear that user inputs are safe to use, just can’t hardcode actual secret values there

**Comment by brianjlai** [comment]
Doc for guidelines and the process for updating the schema documentation:
https://docs.google.com/document/d/1L0IZwiDL_NVHU_TwehZZgptoE_U0t1ppNAqu0D-7j1I/edit#heading=h.ze9rfx2mih7s

**Comment by flash1293** [comment]
Done and merged
