### ISSUE TITLE
Setup guides not working for sources and destinations on 0.41.0

### ISSUE THREAD

**Issue by sestupinan** [airbytehq/airbyte#23846]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**: GCP n2
- **Deployment**: docker compose
- **Step where error happened**: Setup new connection / Upgrade Airbyte

## Current Behavior
I upgraded airbyte to 0.41.0 and the documentation/setup guides for the connectors stopped working. Now, the panel only shows the message "No Setup Guide found for this connector" for every single connector.

## Expected Behavior
The setup guides for sources and destinations should appear on the right panel when creating a new one.

## Logs

![image](https://user-images.githubusercontent.com/47406477/223550753-0ba2a956-9448-49f4-a2b5-c120077ffc91.png)
![image](https://user-images.githubusercontent.com/47406477/223550810-c703bc60-8545-48c0-a7fe-975d68bce29d.png)

## Steps to Reproduce
1. Downloaded and deployed airbyte 0.40.32
2. Upgraded to airbyte 0.41.0
3. Tried to create a new source

**Comment by cgkournelos-rf** [comment]
It is resolved in 0.42.1
