### ISSUE TITLE
Connector builder: Simplify state management

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#23866]
Current state management is working like this:
* For UI mode, there is a react-hook-form state which is reflected into a state service context doing saving and manifest generation
* For yaml mode, this state service context is taking care of state management from the start, except for the name input
* Other aspects (currently visible view in the connector builder, the switch between UI and yaml itself) are managed in a separate state hook in the state service

It seems like it would be cleaner if the yaml mode would also use react-hook-form (with a state shape like this:
```ts
{
  mode: "ui" | "yaml";
  view: "global" | "auth" | number;
  name: string;
  state: BuilderFormValues | { yaml: string };
  version: number | "draft";
  testInputJson: [key: string]: any;
}
```
Then we could always keep everything in the form state and derive the project (name + manifest) in a more stable way:

* No separation between builder state service state and react-hook-form state
* One hook for all validation

TBD: Clarify if this might also help cleaning e2e tests where we wait 3 seconds for the debounce for every update

**Comment by lmossman** [comment]
As a result, the following should be removed from ConnectorBuilderStateService:
- builderFormValues / setBuilderFormValues
- formValuesValid
- yamlManifest
- yamlIsValid / setYamlIsValid (maybe not? This may not be easy to do in RHF since this is determined when converting to json)
- selectedView / setSelectedView
- editorView / setEditorView
- displayedVersion / setDisplayedVersion

**Comment by lmossman** [comment]
Grooming notes:
- Remove the resolve call every time a form value changes - this is unnecessary once we remove the URL display in the testing panel
- Resolve call is still needed in the YAML view, in order to know what the streams are and for validating the manifest
