### ISSUE TITLE
Source Confluence: stream Audit requires permission from paid plan

### ISSUE THREAD

**Issue by darynaishchenko** [airbytehq/airbyte#23862]
Now we receive an error `Cannot make this request because you are on Free edition. Please upgrade to standard or premium.` while syncing stream Audit, because we use free plan.
[Audit](https://developer.atlassian.com/cloud/confluence/rest/v1/api-group-audit/)
[Permissions](https://confluence.atlassian.com/x/_AozKw) required: 'Confluence Administrator' global permission.
[Manage global permissions](https://support.atlassian.com/confluence-cloud/docs/manage-global-permissions/)
Global permissions aren’t customizable on the [Free plan](https://support.atlassian.com/confluence-cloud/docs/learn-about-confluence-cloud-plans/). To edit them, you’ll need to [upgrade to a paid plan](https://www.atlassian.com/try/cloud/signup?bundle=confluence&edition=standard).

**Comment by igrankova** [comment]
https://admin.atlassian.com/s/1c0dae30-3d8d-4388-9db0-63066479cce0/billing/applications
Started free trial on Standard plan, 1 user, $5.75/month,
![image](https://user-images.githubusercontent.com/87977540/223689970-2f60b619-af00-41fa-a0a7-3b12d42c6dfe.png)

Bill estimate
Apr 4, 2023 - May 4, 2023
