### ISSUE TITLE
Destination Clickhouse: Timeout clickhouse-dbt  v1.4.0

### ISSUE THREAD

**Issue by lfrodrigues** [airbytehq/airbyte#23880]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Destination Connector and version**: clickhouse-dbt  v1.4.0
- **Step where error happened**: Normalization 
- 
## Current Behavior
We're getting a timeout error after we upgraded airbyte to 0.41.0. It looks like it's because of the clickhouse-dbt read timeout being set to 300s. I tried changing the timeout settings in the clickhouse JDBC URL Params but it had no impact. 

## Expected Behavior
Timeout should not happen or be possible to configure clickhouse-dbt for a longer timeout 

## Logs
```08:43:24.689355 [error] [Thread-1 (]: 1 of 1 ERROR creating sql table model mydb_dw.dwh_accounts_user .................................................. [ERROR in 300.83s]
08:43:24.717266 [error] [MainThread]: Database Error in model dwh_accounts_user (models/generated/airbyte_tables/mydb_dw/dwh_accounts_user.sql)
08:43:24.717452 [error] [MainThread]:   Error HTTPConnectionPool(host='xx.xx.xx.xx', port=8123): Read timed out. (read timeout=300) executing HTTP request http://xx.xx.xx.xx:8123
08:43:24.717626 [error] [MainThread]:   compiled Code at ../build/run/airbyte_utils/models/generated/airbyte_tables/mydb_dw/dwh_accounts_user.sql,retryable=<null>,timestamp=1678265007483], io.airbyte.config.FailureReason@62cad312[failureOrigin=normalization,failureType=system_error,internalMessage=[0m08:43:24.717452 [error] [MainThread]:   Error HTTPConnectionPool(host='xx.xx.xx.xx', port=8123): Read timed out. (read timeout=300) executing HTTP request http://xx.xx.xx.xx:8123,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@6b7d920e[additionalProperties={attemptNumber=2, jobId=5520, from_trace_message=true}],stacktrace=AirbyteDbtError: 
08:43:24.689355 [error] [Thread-1 (]: 1 of 1 ERROR creating sql table model mydb_dw.dwh_accounts_user .................................................. [ERROR in 300.83s]
08:43:24.717266 [error] [MainThread]: Database Error in model dwh_accounts_user (models/generated/airbyte_tables/mydb_dw/dwh_accounts_user.sql)
08:43:24.717452 [error] [MainThread]:   Error HTTPConnectionPool(host='xx.xx.xx.xx', port=8123): Read timed out. (read timeout=300) executing HTTP request http://xx.xx.xx.xx:8123
08:43:24.717626 [error] [MainThread]:   compiled Code at ../build/run/airbyte_utils/models/generated/airbyte_tables/mydb_dw/dwh_accounts_user.sql,retryable=<null>,timestamp=1678265007483]]]
```

## Steps to Reproduce
1. Configure a large replicated table into clickhouse
2. Activate "Normalized tabular data"
3. Start Sync

**Comment by tobiassteenweg** [comment]
Suggestion to fix the issue: The property **send_receive_timeout** in the profiles.yaml should be set to longer duration. This has to be made in the transform.py file: [https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py)

Quick fix:
```python
    @staticmethod
    def transform_clickhouse(config: Dict[str, Any]):
        print("transform_clickhouse")
        # https://docs.getdbt.com/reference/warehouse-profiles/clickhouse-profile
        dbt_config = {
            "type": "clickhouse",
            "driver": "http",
            "verify": False,
            "host": config["host"],
            "port": config["port"],
            "schema": config["database"],
            "user": config["username"],
            "send_receive_timeout":3600
        }
        if "password" in config:
            dbt_config["password"] = config["password"]

        # ssl is an optional configuration and is not present in strict-encrypt config
        # if ssl option is not present in the config - default to True
        dbt_config["secure"] = config.get("ssl", True)

        return dbt_config
``` 

Another better approach, in my opinion, would be to inherit the send_receive_timeout value from the JDBC parameter.

**Comment by leftklick** [comment]
I've been running into the same issue. +1 for getting this fixed soon!

**Comment by leftklick** [comment]
@marcosmarxm / @tobiassteenweg  are you guys ok with me submitting a PR with the fix recommended by @tobiassteenweg ?

**Comment by leftklick** [comment]
@tobiassteenweg , Is there a way to verify that it works (hack it into the container)?

**Comment by tobiassteenweg** [comment]
@leftklick checkout this doc https://docs.airbyte.com/contributing-to-airbyte/developing-locally#connector-infrastructure. Have not tested it myself, but I am confident that the snippet will fix the issue.

**Comment by fgarci03** [comment]
@leftklick did you have any luck with this?

**Comment by tobiassteenweg** [comment]
@fgarci03 thx!
