### ISSUE TITLE
[EPIC] Source Airtable: create issues to cover MLP enhancements

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23894]
## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/document/d/1l6sIE_SkKXgKJylt814JtQK_kaTPcRBZ-R1mQuokymI/edit?usp=sharing)
Support Enterprise level accounts, [DOCS](https://airtable.com/developers/web/api/list-views).

## Describe the solution you’d like
Check the box when the stream is supported by Airbyte. Note: If you want a particular stream to be supported, upvote the linked GH issue:
**ENTERPRISE Plan:**
- [ ] Views
- [ ] Collaborators
- [ ] Shares
- [ ] Enterprises
- [ ] Users
- [ ] User groups
- [ ] Audit logs
- [ ] Extensions
- [ ] SCIM

**Comment by igrankova** [comment]
Started negotiation with the Airtable sales team to obtain Enterprise access on the test account.

**Comment by igrankova** [comment]
**Pricing details:**
I'll be sure to share a detailed description of Enterprise below with pricing. it is a minimum of 20 users to upgrade.
Regards,
joseph.incorvaia@airtable.com
 
Enterprise Benefits
•	Partner with Enterprise Support: Drive business outcomes by consulting on custom solutions and new workflows, guide successful adoption and implementation, reduce time to value, and reduce organizational inefficiencies for the entirety of your partnership with Airtable via the Enterprise Support team. 
•	More Storage: Unlimited workspaces, 250K records1TB of attachment storage per base, 3-year revision history, and 500k automation runs per month
•	Enterprise Security: Company data sovereignty,* centralized admin management via [Admin Panel](https://protect-us.mimecast.com/s/Ug9DCpYmPXcr2465FPiO9W?domain=support.airtable.com) ([video](https://protect-us.mimecast.com/s/W41eCqxn9MiAQYw9cX_Yku?domain=loom.com)), enhanced deletion recovery, Single Sign-On (SSO), 2FA
•	Data Ownership: On the Pro level, the end user is who owns the data (so, in theory, if they ever leave, they could technically take the data with them). Whereas, on Enterprise, [airbyte.io](https://protect-us.mimecast.com/s/AVg1Cxkxm7c6lENZfWtEHm?domain=airbyte.io) is who would own the data, therefore ensuring full company data sovereignty)
•	Enterprise features: Enterprise API (to interact with account settings) and Metadata API (to interact with base schema and programmatically create bases and tables), Webhooks API, [External Source Sync](https://protect-us.mimecast.com/s/35p5Crko6McKqQJxs4Wa3O?domain=support.airtable.com), Early access to beta features, [Salesforce Sync](https://protect-us.mimecast.com/s/gnVnCv2vk9tm9wVvcA0p4a?domain=support.airtable.com)
•	Invoicing: Annual payment via invoice, with optional bi-annual or quarterly payments
Pricing
We recently rolled out a new Enterprise pricing structure. I wanted to specifically flag the update for your team since you may find it particularly valuable given your usage. Previously, enterprise users all paid the same per-seat cost, no matter their permission or usage level. Now, we offer 3 different types of users, with different levels of access, at different price points.
•	Builders: *Full Price* ($70/user/month) - the standard Airtable licenses - these users can create workspaces and bases, add records, construct views, build automations and apps, and bring data in with syncs (aligns with Owner or Creator permission level) 
•	Contributors: *Half Price* ($35/user/month) - these users can add/edit views and records to existing bases only, share link views, leave comments (aligns with Editor permission level) 
•	Viewers: (*Free*) - lowest level Airtable access - these users can view existing work and leave comments (aligns with Commenter and Read-only permission level) 
The per-seat cost is determined based on the total number of paid users (Builders + Contributor). Basically, more users = a high discount. The minimum annual fee for this plan would be $10,080 ARR (4 builders & 16 contributors).

**Comment by Diana-Vait** [comment]
It was decided that we should not pay for Airtable Enterprise at this point in time. If larger customers start requiring those streams, we can revisit later.

**Comment by Diana-Vait** [comment]
It was decided that we should not pay for Airtable Enterprise at this point in time. If larger customers start requiring those streams, we can revisit later.
