### ISSUE TITLE
Add failure reason to tracking to Discover

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23916]
* Add FailureReason reporting of discover, following the process from https://github.com/airbytehq/airbyte-platform-internal/pull/5033
* Should be simple to implement, but some tests need a little more work than those for check -- we don't currently distinguish failure vs success in the tracking, and trackDiscover calls are also verified separately as part of 3 other tests in the ExecuteSynchronousJob class, so the output would have to be declared there.

This is also the time to decide whether we still want to ignore tracking for the spec command - we previously decided to ignore it because it was noisy. However, AFAIK we rarely run spec, since we cache them.

**Comment by erohmensing** [comment]
@evantahler do you have an idea if when if at all in the platform we'd be running spec? At the moment I can only think of 
- custom connectors 
- OSS user who has upgraded a connector to a different version not cached

**Comment by erohmensing** [comment]
If low code connectors also don't have specs cached, then I feel like we might want to track at least the failures! WDYT?

**Comment by evantahler** [comment]
> If low code connectors also don't have specs cached, then I feel like we might want to track at least the failures! WDYT?

Agree!  Maybe this is something that @airbytehq/connector-extensibility might want to pick up sooner

**Comment by girarda** [comment]
@erohmensing why is testing the spec noisy? I wouldn't expect it to fail for non-custom connectors since it should be tested by the CATs and the command should be idempotent.
