### ISSUE TITLE
Source: Jira - Sync all Sprint Board types, not just `scrum` boards

### ISSUE THREAD

**Issue by tybernstein** [airbytehq/airbyte#23915]
## Tell us about the problem you're trying to solve
Currently the Jira connector only syncs data from `scrum` boards in the sprints stream, we want all board types to be synced. Specifically `simple` boards

## Describe the solution you’d like
Jira connector syncing all board types

## Are you willing to submit a PR?
No

**Comment by artem1205** [comment]
Added in #25798
