### ISSUE TITLE
Move Cloud API config.yaml into oss

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#23952]
We want to move our `cloud-api/src/main/openapi/config.yaml` into the oss/ folder. This will allow us to generate the client for the cloud APIs in the frontend code automatically (as we do for the config API already), and highly increases therefore maintenance and stability of the cloud API query code.

This has already been discussed offline with @cgardens who is on board for moving this into the oss folder.

**Comment by pmossman** [comment]
A P1 issue occurred that would have been caught if this issue were completed, so another data point to emphasize the priority of this! https://airbytehq-team.slack.com/archives/C0503TUS8SY
@mfsiega-airbyte I think we should make sure this happens next sprint
