### ISSUE TITLE
[Question] About Scaling instances for airbyte worloads

### ISSUE THREAD

**Issue by TalhaNaeem101** [airbytehq/airbyte#23969]
I have airbyte deployed on k8s. I have a separate node group for the airbyte-related workload. What do you suggest, how to scale the airbyte nodes, either vertically or horizontally? Want to know if there's any recommendation from airbyte team for this?

**Comment by sajarin** [comment]
Hey @TalhaNaeem101 thanks for the question. You can find our recommendations for how to deploy and scale your kubernetes instance in our docs: https://docs.airbyte.com/operator-guides/scaling-airbyte/#on-kubernetes

Also for further questions, feel free to post on our community slack: https://airbyte.com/community

**Comment by TalhaNaeem101** [comment]
@sajarin Thank you as you made the update on my issue.

**Comment by TalhaNaeem101** [comment]
@sajarin   Thank you as you made the update on my issue.

Actually I had already gone through this documentation. And there it is recommended to[ tune the instance size based on the need](https://docs.airbyte.com/operator-guides/scaling-airbyte/#on-kubernetes:~:text=and%20gradually%20tuning%20instance%20size%20to%20your%20workload.). BUT In our case, we need to have our k8s nodes in different availability zones, like one node in `us-east-2a` and the other node in `us-east-2b`. I want to have some insights about this. Please share your thoughts, as I did not find anything in the airbyte docs. PS: Please keep the issue open unless It is answered. Thanks
