### ISSUE TITLE
Source Azure SQL Server Basic - Add option to disable columnstore in dbt normalization

### ISSUE THREAD

**Issue by umarhussain88** [airbytehq/airbyte#23962]
## Tell us about the problem you're trying to solve
I want the option to disable `columnstore` compression for the lower tier versions of SQL Server - this is acheivable by adding `+as_columstore: False` at the top level of the dbt project that will apply to all the models. 

it would be ideal if this could be controlled when creating a MS-SQL destination in the UI or via the CLI. 

the lower tiers of Azure SQL do not support column_store indexes so the dbt normalization always fails as it tries to enable this by default (this is a dbt issue I've faced before) 

## Describe the solution you’d like
an option in the UI to change this that changes the default option for the `mssql` base normialzation variant to be false. the default should be true.

## Describe the alternative you’ve considered or used
manually adding this into the `dbt-projects.yml` files inside the base github image.
## Are you willing to submit a PR?

yes of course, but would not know how to push this up the chain into the UI and how to test this across your entire suite to ensure nothing else breaks.

just to add - for smaller business that use a managed db for self-hosted analytics the basic tiers of Azure SQL are usually enough.

**Comment by sajarin** [comment]
Hey @umarhussain88 thanks for the feature suggestion. I've gone ahead and forwarded this to our team.

**Comment by umarhussain88** [comment]
> Hey @umarhussain88 thanks for the feature suggestion. I've gone ahead and forwarded this to our team.

you absolute legend - let me know if you need someone to test it out. Happy to help and/or pair with the team.

**Comment by Simon-Collinson** [comment]
This feature would also be useful for MSSQL - specifically for teams using SQL Server <2017 as the destination, since 2016 and earlier don't support columnstore indexes either.

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated the custom dbt transformation feature](https://github.com/airbytehq/airbyte/discussions/34860).

**Comment by RichardCain** [comment]
Is there a workaround for this? I can't move data to our Azure SQL database because it doesn't support columnstore.
