### ISSUE TITLE
I would like to be able to deactivate slack notifications for schema changes

### ISSUE THREAD

**Issue by YohanGrember** [airbytehq/airbyte#23974]
## Tell us about the problem you're trying to solve
Hello team 👋 
I use slack notifications to alert my team on sync failures.
Without me asking for it, Airbyte also sends schema change messages which creates a lot of noise in my alerting channel.
I would like to be able to deactivate alerting for schema changes :) 

## Describe the solution you’d like
I would like to deactivate slack alerting for schema changes, ideally using a new toggle button in the 'Notify me' part
![Capture d’écran 2023-03-13 à 12 17 41](https://user-images.githubusercontent.com/22528531/224686872-63186f2a-55ba-44e4-b962-fae3b6883dcb.png)

I would also be okay to parametrize it at the connection level but it would be less convenient for me

## Describe the alternative you’ve considered or used
I considered setting up an intermediate layer between airbyte and slack to be able to filter out these logs, but it feels not pragmatic to me

## Additional context
Since I started using Airbyte slack notifications, my alerting channel is filled with messages such as 
![Capture d’écran 2023-03-13 à 12 20 04](https://user-images.githubusercontent.com/22528531/224687386-e82441ff-726a-4b0e-911c-737c8472b702.png)
This is a problem for my team, because it creates an alerting fatigue and could prevent us from detecting real issues

## Are you willing to submit a PR?
I've never created a PR on Airbyte so I need to ramp up but as a regular user I'd be happy to start contributing 😄

**Comment by YohanGrember** [comment]
Hello @krishnaglick @edmundito :wave:
It seems you have worked on similar use cases. Would you know how to move forward with this feature request?

**Comment by benmoriceau** [comment]
Hello @YohanGrember, which version of airbyte are you running? On v0.41.0 it was activated by default which has been changed in https://github.com/airbytehq/airbyte-platform/commit/d2aa6179d51eeb49b29348819e0f5c171573fe5d and should be integrated to v0.42.0. Another possibility instead of doing an upgrade would be to set the variable `AUTO_DETECT_SCHEMA` to false, but that will disable the auto detection of schema change entirely, not only the notification part of it.

**Comment by YohanGrember** [comment]
Thanks a ton @benmoriceau! 
We are indeed running v0.41.0, will do the upgrade to v0.42.0 then 😃
