### ISSUE TITLE
connectors-ci: write tests to test Dagger pipelines

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#23972]
## Tell us about the problem you're trying to solve
Our current connectors-ci codebase is not tested.
We should implement at least a couple of tests to assess whether the pipeline behavior is correct in the following scenario:
* A single connector pipeline failure should not prevent the other connector pipelines to run
* A failure in unit / integration / format / qa checks / CAT should be correctly handled and reported and not make the pipeline execution failed
* While running a pipeline in the CI context a GitHub commit status should be sent when:
1. The global pipeline start
2. A connector test pipeline start
3. A connector test pipeline stopped due to an error
4. A connector test pipeline failed because of a test failure
5. The global pipeline finishes
6. The global pipeline fails due to an unexpected error

* For each connector tests a report should be uploaded to S3 when running in the CI context.

**Comment by bnchrch** [comment]
Grooming
- Lets not be dependant on existing unit tests (we dont want flaky tests because our other non related tests are failing)
- choose a test case that has the best oppourtunity to show off Daggers test story
- Focus on testing the pipeline specifically

**Comment by bnchrch** [comment]
Note from today: @alafanechere to pick out the test that fits the criteria for next planning meeting

**Comment by alafanechere** [comment]
Closing this as we're now adding unit tests on for each pipeline iterations
