### ISSUE TITLE
Source Hubspot: add timedelta fields

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#2397]
## Tell us about the problem you're trying to solve
This #2215 PR removes few fields because they break comparison in tests.

```python
    def _filter_dynamic_fields(self, records: Iterable) -> Iterable:
        """ Skip certain fields because they are too dynamic and change every call (timers, etc)"""
        for record in records:
            if isinstance(record, Mapping) and "properties" in record:
                for key in list(record["properties"].keys()):
                    if key.startswith("hs_time_in"):
                        record["properties"].pop(key)
            yield record
```

## Describe the solution you’d like
We should restore deleted fields after we implement a feature to exclude fields from a comparison in tests

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368153217091) by [Unito](https://www.unito.io)

**Comment by augan-rymkhan** [comment]
@keu The method `_filter_dynamic_fields` was removed in PR [8329](https://github.com/airbytehq/airbyte/pull/8329/files#diff-37c875e03f2e65ea1423534b0b634e18eaca797135f8d9df32360407b1d0ccb9L223)
The dynamic fields were included in `ignored_fields` in acceptance-test-config.yaml.
This issue can be closed.
