### ISSUE TITLE
connectors-ci: split `ci-connector-ops` in multiple packages.

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#23975]
## Tell us about the problem you're trying to solve
We originally stuffed a lot of different tooling in the ci-connector-ops package.
* QA checks
* QA engine
* CI pipelines declared with Dagger
* Acceptance test configuration validation (high test strictness level)
* Allowed host checks

It has the following problems:
* The tools do not have the same requirements in terms of python version (dagger pipeline requires Python 3.10). It means we have to rely "[extras_requires](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/setup.py#L58)" to make sure `dagger-io` (requiring Python 3.10) is only installed when we install the "pipelines" extra. (e.g pip install .\[pipelines\])
* Some tools require libraries that are not light and always easy to containerize due to their dependency to some system C system dependencies (`pandas`) that are not always available on python alpine image. But we need to containerize this tool in the CI context. Again, playing with `extra_requires` in `setup.py` is the [workaround](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/setup.py#L58) so far. 
* We also have other ci_* packages (`ci_common_utils`, `ci_credentials`) which are not in `ci_connector_ops`, which makes the `tools` directory structure no clear at all.

## Suggestion:
* Follow's Ben suggestion to move these Python packages under an airbyte-ci top directory: 

![image](https://user-images.githubusercontent.com/5551758/224691530-4e80cc59-ab21-4304-8766-501438a5aa80.png)

@bnchrch I might challenge the legitimacy of a `common` / `connectors_ci` directory.

I think we should have something like:
- ci-credentials: to download/upload secrets to GSM
- ci-code-validator: perform static code analysis (QA checks, acceptance-test-config checks, allowed host checks)
- ci-qa-engine: generate QA report for all our connectors in our catalog + opens PR on the internal repo to promote
- ci-pipelines: holds our CI pipelines logic, and can call the containerized packages listed above.

**Comment by bnchrch** [comment]
Notes from a huddle with @alafanechere 

### What we decided
1. projects/libraries/services in `airbyte-ci` should be responsible for their own dependencies
2. We should be able to import between these systems and have the dependencies resolve automatically
3. This is a good oppourtunity to start using Poetry
4. But the first phase should be get the directory structure and imports working before we do any refactoring of dependency management for existing projects.


### Outstanding questions
1. Can we easily import a local package that isnt using poetry from poetry (and vice versa) We think yes.
2. What is the best directory structure to manage the external and internal dependencies between
  1. Dagger Pipelines
  2. Dagster Orchestrator
  2. Shell scripts and command line tools used in GHA
  3. QA-engine
  4. Checks
  5. CI Credentials
  6. Other CI tooling

**Comment by cpdeethree** [comment]
Briefly chatted with Evan and Augustin about this. Overall I think this is great and a much needed step forward to unifying tooling for CI. I'll do a deep dive on the proposal itself, but basically I think platform builds should share this repository and structure as well.

Eventually I think the setup should look like this:

airbyte-ci folder becomes its own repository, "airbyte-ci" or "airbyte-actions"

The existing internal [repository](https://github.com/airbytehq/workflow-actions) is renamed to "airbyte-ci-internal" or "airbyte-actions-internal"

**Comment by alafanechere** [comment]
We've brainstorm with @cpdeethree how we could have global approach (OSS + Cloud) at declaring Dagger pipelines by exposing a common python package each CI project should use.
A WIP is available https://github.com/airbytehq/airbyte_actions/pull/1 and draft diagram is available [here](https://whimsical.com/reusable-dagger-components-architecture-LRbj21LmXD64aaLW1SXScG).

**Comment by alafanechere** [comment]
After our yesterday's brainstorm and your new pipeline addition to test the metadata lib I'm not sure if we should make this issue mandatory for phase 0 of the metadata project.

**Comment by cpdeethree** [comment]
agree, we may have to iterate on the above pr for a bit to get it into a state we are happy with before we port the connectors pipeline code to use it.
