### ISSUE TITLE
Improvements to ci_credentials package for using GSM secrets locally

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#23987]
- [ ] Add ability to authenticate via `gcloud auth login` instead of generating a service account
- [x] Instructions on creating read-only (`write-to-storage`) service accounts for those who don't want the ability to accidentally `update-secrets` - we shouldn't do this - we need write-to-storage to update single use oauth tokens 
- [ ] Make it easy to grab all secrets at once instead of just a specific connector - already supported! Just needs to be documented
- [ ] Look into improving the security by copying to encrypted volumes - https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1678473840779329?thread_ts=1678388327.168099&cid=C03C4AVJWG4 from Joe Bell for context

**Comment by jbfbell** [comment]
Random thoughts on [the current way](https://github.com/airbytehq/airbyte/pull/23100/files)

- `Owner` is too broad a permission set for the service accounts, Secret Accessor is probably enough for accessing secrets (but that assumes its only needs to access secrets) 
``` 
gcloud iam roles describe  roles/secretmanager.secretAccessor
description: Allows accessing the payload of secrets.
etag: AA==
includedPermissions:
- resourcemanager.projects.get
- resourcemanager.projects.list
- secretmanager.versions.access
name: roles/secretmanager.secretAccessor
stage: GA
title: Secret Manager Secret Accessor
```
FWIW `Owner` is _almost always_ too broad, at the very least `Editor` is slightly better as the lazier "I'm not sure what permissions I need" option, but we should strive for least privileged access
- Everyone doesn't need to create a new service account for this, we could create one with the permissions needed and their is a gcloud command flag `--impersonate-service-account <service account email>` which will run the gcloud command with the permissions of that service account. Benefit here is that you don't need a service account key. You just need to have permissions to "act as" the service account
- We should grant the "act as" permission to a google group and use that to manage access
- The current tool is making api requests to google with the python requests library, is probably easier to use [the library google provides](https://cloud.google.com/secret-manager/docs/reference/libraries#client-libraries-install-python)

**Comment by bnchrch** [comment]
Epic grooming:
Does this have more or less value given how the new pipelines function?

**Comment by evantahler** [comment]
Grooming

* Airbyte CI downloads the secrets into an ephemeral docker container now, so they aren't as _easy_ to find any more (not on your real file stystem)
* Airbyte CI made a lot of this better...


Security:

* replace service accounts with GSM login (made own story)
