### ISSUE TITLE
Unclear to users where to set the api key

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23996]
## What

After choosing the right authentication method, the API key field is uneditable and it is not clear to the user that they need to click on "Inputs" to set the API key

## Ideas
- Open the inputs screen if they. click the uneditable field

**Comment by Upmitt** [comment]
My suggestion is maybe to use an other wording that "inputs" - In the video example I suggest something like "Testing values" but this is open to other suggestions :) I would also not use input fields for the uneditable API key line, but the latest design we did. And finally, when hovering the "user input" icon, I would suggest to have a ling, in the tooltip, to set the value for testing. > see video, or test the prototype:

loom video: https://www.loom.com/share/d8c95735d61446368bb4c8e797e17c9b
prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4158%3A134196&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4158%3A134196&show-proto-sidebar=1

**Comment by Upmitt** [comment]
When clicking in the header input in the proto, I tested a way to display user inputs as a tag -

**Comment by girarda** [comment]
approved and closing. this is already implemented 🚀
