### ISSUE TITLE
Copy stream feature is difficult to discover

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#23997]
## What
The copy stream feature enable connector developers to copy an existing stream's components when setting up a new stream. This is useful as different streams for an API usually use the same pagination mechanism.

So far, early users haven't seen this feature, so they implemented each streams from scratch

## Ideas to make this more discoverable:
- Add option to use an existing stream in the modal when user clicks on "new stream"

**Comment by Upmitt** [comment]
loom video: https://www.loom.com/share/4f58d4a63b674b559cceb6bee12068e7
prototype: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4158%3A133832&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4158%3A133832&show-proto-sidebar=1

**Comment by girarda** [comment]
🚀

**Comment by lmossman** [comment]
Created frontend issue: https://github.com/airbytehq/airbyte/issues/24116
