### ISSUE TITLE
Version mismatch on scheduler persistence ( Version mismatch between 0.17.0-alpha and 0.16.1-alpha.)

### ISSUE THREAD

**Issue by drumcircle** [airbytehq/airbyte#2399]
## Expected Behavior
Docker should come up no problem first time

## Current Behavior
Creating Scheduler persistence...
airbyte-scheduler   | Exception in thread "main" java.lang.IllegalStateException: Version mismatch between 0.17.0-alpha and 0.16.1-alpha.
airbyte-scheduler   | Please upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte
airbyte-scheduler   |   at io.airbyte.commons.version.AirbyteVersion.assertIsCompatible(AirbyteVersion.java:112)
airbyte-scheduler   |   at io.airbyte.scheduler.SchedulerApp.main(SchedulerApp.java:204)
airbyte-server      | Exception in thread "main" java.lang.IllegalStateException: Version mismatch between 0.17.0-alpha and 0.16.1-alpha.

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
Installed Windows WSL2/Debian
Started docker-compose up

## Severity of the bug for you
Medium

## Airbyte Version
VERSION=0.17.0-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

**Comment by ChristopheDuong** [comment]
> Docker should come up no problem first time

If it's the first time and you don't have a previous installation/configurations of airbyte that you care to keep around, you can run the following command that will wipe your internal airbyte database and configuration files:
```
docker-compose -v down
```

Then you should be able to `docker-compose up` without exceptions.
The exceptions that you are reporting about occurs when configurations are found with `0.16.1-alpha` but you are running airbyte's code version `0.17.0-alpha`

**Comment by davinchia** [comment]
This seems solved. Closing for now. Please reopen if there are more questions!
