### ISSUE TITLE
`source-github` should support self-hosted Github instances

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24007]
Right now, `source-github` only connects to `api.github.com`.  To support self-hosted instances, we should:
* add an optional option to the connectors SPEC, `api_url ` which has a default value of `api.github.com` (to make this change backwards compatible).
* Update the code to use the new config option
* Add `"${api_url}"` to the connector's allowed_hosts

**Comment by erohmensing** [comment]
The person impleemnting this can take inspiration from source-gitlab, which [supports users providing their own api_url](https://github.com/airbytehq/airbyte/blob/bb8823ff32d05fe42dc1e5d0c3e5daea8ece1e98/airbyte-integrations/connectors/source-gitlab/source_gitlab/spec.json#L76-L82). In the case of gitlab it's required (not sure if it should be actually), but it shouldn't be in the case of github - api.github.com should remain the default value if the user. doesn't provide one.

**Comment by btkcodedev** [comment]
Also one small clarification on https://github.com/airbytehq/airbyte/issues/24007#issue-1622357174
Could you please specify where the allowed_hosts reside?

**Comment by btkcodedev** [comment]
Please assign it to me @YowanR

**Comment by YowanR** [comment]
Assigning it to you @btkcodedev ! This should be a good one! 🚀

**Comment by evantahler** [comment]
> Also one small clarification on [#24007 (comment)](https://github.com/airbytehq/airbyte/issues/24007#issue-1622357174) Could you please specify where the allowed_hosts reside?

Allowed hosts live [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L701-L703) and tell the airbyte server which hosts a connector should be allowed to access.  You'll be adding something like `"${api_url}"` which would pluck the value from the connector's configuration

**Comment by btkcodedev** [comment]
Thanks for the quick response @evantahler 🚀

**Comment by evantahler** [comment]
^ this is the PR https://github.com/airbytehq/airbyte/pull/24095

**Comment by btkcodedev** [comment]
Unassigning due to higher complexity than expected.
Community members are free to take this issue for assignment :)

**Comment by patkaehuaea** [comment]
@btkcodedev Would you be able to assign this issue to me? I opened PR [#30076](https://github.com/airbytehq/airbyte/pull/30076).
