### ISSUE TITLE
When creating a new stream it should be possible to set a user input value in the URL

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#24015]

**Comment by Upmitt** [comment]
![Image](https://user-images.githubusercontent.com/29780098/225078482-2fe131da-488b-4e0b-8fe9-7720b6090e15.png)

**Comment by girarda** [comment]
@Upmitt it's a good idea to offer that option when the connector developer is starting a new stream. Would there be a dropdown with the existing streams after selecting the checkbox?

**Comment by lmossman** [comment]
FE issue: https://github.com/airbytehq/airbyte/issues/24120
