### ISSUE TITLE
Add a job to generate spec_secrets_mask.yml

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#24025]
Add a job that is triggered on registry change that generates a spec_secrets_mask.yml file

**Comment by evantahler** [comment]
Grooming:

* List of secrets should be generated from metadata.  No need for cloud vs oss - let's have one large list of secrets to hide
* YAML file is uploaded to GCS bucket
* (story) exists for the platform to consume this YAML vs generating and using a local version
