### ISSUE TITLE
Automatically scroll to first form error

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#24033]
## Tell us about the problem you're trying to solve
If there are errors in the form, the "Test" button doesn't work and shows that the user "Cannot test while there are form errors", but the form errors are not highlighted. The user needs to scroll through the form to find them.

[Link to loom showing the issue](https://www.loom.com/share/73fa7621e17b40b6abe14badc1fc416f)

## Describe the solution you’d like
When clicking test, automatically scroll to the first form error if there are any

## Acceptance criteria
- [ ] When clicking test with a form with errors, the UI automatically scrolls to the first error
- [ ] If there are no errors, the "Test" button works as expected

**Comment by flash1293** [comment]
Grooming notes:
* Have a `ScrollToErrorContext` that holds the field that should be scrolled to
* The builder field subscribes to it - if it gets changed to the current field, the builder field scrolls itself into view, then unsets
* When triggering a test on an invalid form, the `ScrollToErrorContext` is set to the first error which will be picked up by the appropriate builder field after it's rendered
