### ISSUE TITLE
Add the -k ability to the airbyte-ci test command

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#24061]
# Problem
Test commands are slow, particularly when you want to show just one new/updated tests is changing

# Solution
Update the `airbyte-ci connector test` command to expose the `-k` command from Pytest

# Implementation Recommendation
Once https://github.com/airbytehq/airbyte/pull/32188 is merged we will have the `StepToRun` class which has
1. string id's per step
2. dynamic args passed to a step that can change at run time

This should support a pattern like so
```bash
airbyte-ci connector --name=source-faker test --arg-build-k test_specific
```

Where
1. click allows for extra arguments

2. our test command parses the extra click arguments to a dictionary

```py
extra_args = {
    "build": ["-k",  "test_specific"]
}
```

3. Our `run_steps` function passes these extra args to the step at run time
4. Our steps are equipped to use `extra_args` as an optional value of `run`

```py
    async def _run(self, command=None, extra_args=None) -> StepResult:
        if additional_args:
            command += extra_args

        container_to_run = await self.init_container()
        return await self.get_step_result(container_to_run.with_exec(command))
```

**Comment by bnchrch** [comment]
Grooming
- pass the flag to where ever we call `intergration_tests.acceptance`

**Comment by alafanechere** [comment]
Thank you for the writeup :pray:
I'm inline with the fact that connectorS is :thumbsup::skin-tone-2: but I can't figure a clean way to pass the extra args:
let's say we test both a java and python connectors, how would we expose an option which would apply just for python unit tests ?


If we keep `connectors` what's your opinion on the "test suite subcommands": e.g:
`airbyte-ci connectors --name=source-faker --name=source-postgres test unit-test -k`
I don't think it clashes with:
> Which means we should have a solution where
The pipeline has to do no more than use a step, for the step to be passed additional arguments
In otherwords the CLI side of the implementation should be generic for all pipelines, and the implementation of how additional args are used is up to the individual step.

Please share if you have any CLI example in mind 🙏 I think I'm confused by the `build` term in your original example.

**Comment by bnchrch** [comment]
> how would we expose an option which would apply just for python unit tests ?

I was thinking we use a format like `{step-id:arg value}`

We would have to enable extra args on our click commands for connectors and the interface would look like
```
airbyte-ci connectors --name=source-faker --name=source-postgres test --unit-test-k some_test_name
```


> If we keep connectors what's your opinion on the "test suite subcommands": e.g: airbyte-ci connectors --name=source-faker --name=source-postgres test unit-test -k

I think that would be fine? It might not be optimal since it applies to both but the dev is still free to run two tests in a row.

and its useful if you want to only run one cat test for N connectors
