### ISSUE TITLE
Source Facebook Marketing: Retry pattern not working

### ISSUE THREAD

**Issue by NahidOulmi** [airbytehq/airbyte#24066]
## Environment
- OS Version / Instance: Debian
- Memory / Disk: 32GB memory / 50GB disk
- Deployment: docker-compose
- Airbyte Version: 0.40.26
- Source name/version: Facebook Marketing Source connector
- Destination name/version: bigquery
Step: schema discovery in webapp
## Current Behavior

The `reduce_request_record_limit` function that is in the `streams.common.py` package is not working as expected.

When the connector requests too much data and the call failed, this function should divide the `limit` param by 2 and try again with the lowered parameter. 
However, the `details` object do not contain such param, so it never gets in the `if` condition and perform that division:  

```
    def reduce_request_record_limit(details):
        _, exc, _ = sys.exc_info()
        if (
            details.get("kwargs", {}).get("params", {}).get("limit")
            and exc.http_status() == http.client.INTERNAL_SERVER_ERROR
            and exc.api_error_message() == "Please reduce the amount of data you're asking for, then retry your request"
        ):
            details["kwargs"]["params"]["limit"] = int(int(details["kwargs"]["params"]["limit"]) / 2)
```

## Expected Behavior
The `details.param` dict should have a `limit` param for this to work.

## Logs

You can see here that the `limit` param is never divided by 2

```
{"type": "LOG", "log": {"level": "INFO", "message": "Starting syncing SourceFacebookMarketing"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Syncing stream: activities "}}
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off call(...) for 5.0s (facebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v15.0/act_xxxx/activities?access_token=****&fields=actor_id%2Cactor_name%2Capplication_id%2Capplication_name%2Cdate_time_in_timezone%2Cevent_time%2Cevent_type%2Cextra_data%2Cobject_id%2Cobject_name%2Cobject_type%2Ctranslated_event_type&summary=true&since=1677628800&after=cHVtYV9hbmNob3I6TVRZAM09EZA3hNRGt6TnpRNE5TTTBOV1UxWlRreE1UVTRaV1V5TW1SbU5XTmlNelEwTURBNE5XUTFOelZArTW1WbE16azBNVFpqTXpjME9XRmtOak00WTJSaU1UZA3pObUpqTURNMk5UQTQjNjYZD&limit=100\n  Params:  {'summary': 'true'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"An unknown error occurred\",\n        \"error_subcode\": 99\n      }\n    })"}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v15.0/act_892520001410300/activities?access_token=****&fields=actor_id%2Cactor_name%2Capplication_id%2Capplication_name%2Cdate_time_in_timezone%2Cevent_time%2Cevent_type%2Cextra_data%2Cobject_id%2Cobject_name%2Cobject_type%2Ctranslated_event_type&summary=true&since=1677628800&after=cHVtYV9hbmNob3I6TVRZAM09EZA3hNRGt6TnpRNE5TTTBOV1UxWlRreE1UVTRaV1V5TW1SbU5XTmlNelEwTURBNE5XUTFOelZArTW1WbE16azBNVFpqTXpjME9XRmtOak00WTJSaU1UZA3pObUpqTURNMk5UQTQjNjYZD&limit=100\n  Params:  {'summary': 'true'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"An unknown error occurred\",\n        \"error_subcode\": 99\n      }\n    }\n"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error after 1 tries. Waiting 5 more seconds then retrying..."}}
{"type": "LOG", "log": {"level": "INFO", "message": "\n\n  Message: Call was not successful\n  Method:  GET\n  Path:    https://graph.facebook.com/v15.0/act_892520001410300/activities?access_token=****&fields=actor_id%2Cactor_name%2Capplication_id%2Capplication_name%2Cdate_time_in_timezone%2Cevent_time%2Cevent_type%2Cextra_data%2Cobject_id%2Cobject_name%2Cobject_type%2Ctranslated_event_type&summary=true&since=1677628800&after=cHVtYV9hbmNob3I6TVRZAM09EZA3hNRGt6TnpRNE5TTTBOV1UxWlRreE1UVTRaV1V5TW1SbU5XTmlNelEwTURBNE5XUTFOelZArTW1WbE16azBNVFpqTXpjME9XRmtOak00WTJSaU1UZA3pObUpqTURNMk5UQTQjNjYZD&limit=100\n  Params:  {'summary': 'true'}\n\n  Status:  500\n  Response:\n    {\n      \"error\": {\n        \"code\": 1,\n        \"message\": \"Please reduce the amount of data you're asking for, then retry your request\"\n      }\n    }\n"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error after 2 tries. Waiting 10 more seconds then retrying..."}}
```

## Steps to Reproduce
1. Ask for a synchronous sync of a big amount of data (the "Activities" stream seems a good candidate) or create a Test case (the existing one called `test_limit_error_retry` is not specific enough)
2. Observe that the `reduce_request_record_limit` function never divides the limit by 2 

## Are you willing to submit a PR?

I don't know how to fix it yet.

**Comment by davydov-d** [comment]
fixed [here](https://github.com/airbytehq/airbyte/pull/24600)

**Comment by NahidOulmi** [comment]
Thank you @davydov-d ! I have a question though : 

The retry pattern has this condition in `common.py` : 
`exc.api_error_message() == "Please reduce the amount of data you're asking for, then retry your request"
` for dividing the limit by 2.

However, sometimes I have the following error : `"An unknown error occurred"` and I noticed that decreasing the limit also fixed the API error in that case. So I added the case in the retry_pattern : 

`exc.api_error_message() == "Please reduce the amount of data you're asking for, then retry your request"
or exc.api_error_message() == "An unknown error occurred"
`

But if I do that, the `limit` parameter gets decreased for all next API calls. And I want it to reset the limit to the default value (usually 100) whenever the API call worked and not stay at, let's say limit=3 because the next calls will take far too long. 

For some reason, the limit parameter is rightly reset in the condition `exc.api_error_message() == "Please reduce the amount of data you're asking for, then retry your request"
`

but not if I add the condition `exc.api_error_message() == "An unknown error occurred"`

Could you give a heads up ?

**Comment by NahidOulmi** [comment]
So I hardcoded the reset in the `load_next_page` function in the `patches.py` file :

`self.params["limit"] = 100`

and it seemed to fix my issue on my Airbyte instance but it will not be accepted in a PR.

I will create an Issue for that.

**Comment by davydov-d** [comment]
hey @NahidOulmi thanks for the feedback and sorry for the long delay. I believe your case is a kind of an edge case which should be handled in a specific way. I just wanted to suggest you open the issue, I believe the team will find the right approach to resolving it!
