### ISSUE TITLE
Source MSSQL :  _AB_CDC_UPDATED_AT is incorrect for few records 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#24079]
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: k8s
- **Source Connector and version**:  2.0.0
- **Step where error happened**: CDC

    Sometime, _AB_CDC_UPDATED_AT comes incorrectly . we are sorting by lsn to find out the latest records and end the old record using _AB_CDC_UPDATED_AT (valid_from, valid_to)

4049440	2023-03-13T07:16:01.940Z	1678691761940	002016ce:000e3430:0005	002016ce:000e3430:0002	2
4049440	2023-03-13T07:16:01.943Z	1678691761943	002016ce:000e3429:0009	002016ce:000e3429:0002	2
4049440	2023-03-13T07:16:01.547Z	1678691761547	002016ce:000e30e5:0005	002016ce:000e30e5:0002	2
4049440	2023-03-13T07:11:07.993Z	1678691467993	002016c9:000da986:0006	002016c9:000da986:0002	2

as you can see, latest record timestamp is less than previous record (2nd column)

## Current Behavior
 _AB_CDC_UPDATED_AT is incorrect

## Expected Behavior
  latest record should contain latest timestamp 

It could be debezium bug

**Comment by prateekmukhedkar** [comment]
We tested this with a newer version (soon to be released) and did not see this happening. Closing this and ok to reopen.
