### ISSUE TITLE
shell scripts don't work with default shell `sh` and keyword `source`

### ISSUE THREAD

**Issue by leo-schick** [airbytehq/airbyte#24073]
In may shell files in the airbyte repository the shell file is initiated with

``` shell
#!/usr/bin/env sh
```

See for example [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/connector-acceptance-test/acceptance-test-docker.sh#L1)

Ubunut and Debian uses as their default shell dash. See [here](https://wiki.ubuntu.com/DashAsBinSh#source).

```
$ ls -alh /bin/sh
lrwxrwxrwx 1 root root 4 Dec 10  2020 /bin/sh -> dash
$
```

Dash **does not support calling `source <shell_file.sh>`** as it is done in many shell scripts.

For example [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/connector-acceptance-test/acceptance-test-docker.sh#L6)

Because of that, running my acceptance tests locally breaks with error
```
(.venv) $ ./acceptance-test-docker.sh
./acceptance-test-docker.sh: 3: source: not found
(.venv) $
```

There are two options to fix this:
1. Do not use `source <script_file>` but `. <script_file>`. See also [Stackoverflow](https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell)
2. Enforce using bash by initiating the files with `#!/usr/bin/env bash`

This change should be applied to all shell scripts in the airbyte repository.

**Comment by marcosmarxm** [comment]
You should use `airbyte-ci` to run connector tests and not the shell itself.
