### ISSUE TITLE
Show selected/enabled streams first in Connection Settings

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#24106]
Users today see all their streams, regardless of whether the stream has been enabled or disabled. The current logic does not allow a user to quickly understand what streams are already selected.  They need to either scroll through the entire list of tables or search individually for each one. 

**Acceptance criteria**:
- A checkbox is visible that lets the user show/hide disabled streams

![image.png](https://images.zenhubusercontent.com/633f049bfac5d1a38c1061cc/48f5868c-199b-4947-bf49-349f073ef2b4)

**Comment by nataliekwong** [comment]
Hey @chandlerprall - tagging you as a heads up as a UX improvement. I believe it lands in your area.

**Comment by josephkmh** [comment]
Could we also solve this by having a "Hide disabled streams" checkbox somewhere above the table?

**Comment by nataliekwong** [comment]
Yeah, open to that. Could it be placed next to "refresh source schema" button on the top right? 

Worth including this in the broader connection settings redesign project!
