### ISSUE TITLE
Add option to copy existing stream when adding new stream

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#24116]
## Context
The copy stream feature enable connector developers to copy an existing stream's components when setting up a new stream. This is useful as different streams for an API usually use the same pagination mechanism.

So far, early users haven't seen this feature, so they implemented each streams from scratch

## Solution
Add an option to the New Stream modal which when checked allows users to select an existing stream to copy the configuration from.

See designs here: https://github.com/airbytehq/airbyte/issues/23997#issuecomment-1468446459

## Acceptance Critera
- A checkbox is added to the New Stream modal with a label and tooltip explaining what it does
- When checked, a dropdown is rendered allowing the user to pick an existing stream whose configuration should be copied into the new stream upon creation

**Comment by flash1293** [comment]
I've seen this too late, sorry - copied over the context to https://github.com/airbytehq/airbyte/issues/24651
