### ISSUE TITLE
Fix support for external tables on S3 in DatabBricks destination

### ISSUE THREAD

**Issue by grishick** [airbytehq/airbyte#24153]
Definition of done:
 - demo of setting up destination-databricks with external tables starting from Databricks set-up and ending with a working Airbyte connection
 - documentation on how to configure all settings for using destination-databricks with external tables in S3

**Comment by grishick** [comment]
Rescoping to S3-only, because Azure support is more complicated

**Comment by evantahler** [comment]
https://github.com/airbytehq/airbyte-platform-internal/issues/2540#issuecomment-1232321422
