### ISSUE TITLE
🐛 Source S3: The current versions date validation is too strict causing connections to fail

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#24168]
# Overview
This is the outcome of the [Source S3 P0](https://github.com/airbytehq/oncall/issues/1669#issuecomment-1472738586) that had 6 workspaces fail due to an error parsing the cursor field

![image](https://user-images.githubusercontent.com/1325608/225754973-ad6980b7-97ee-4e58-882b-815f678f9d00.png)

```sh
time data '2023-02-10T14:00:08+0000' does not match format '%Y-%m-%dT%H:%M:%SZ'
```
[Sentry link](https://airbytehq.sentry.io/issues/4011917199/?project=6527718&referrer=slack)

# The quick fix already applied
We rolled `source-s3` in cloud back from `2.0.1` to `2.0.2`

# Ongoing impact
Currently we still have the following problems
1. OSS users of source-s3 likely will have failure issues
2. source-s3 in cloud is pinned to an old version

# Solution Requirements
1. We understand the underlying cause and have a recommendation for if we should attempt to migrate customers off the old timezone format
1. The s3 connector works with the new format and the old format
1. The s3 connector is unpinned in cloud

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/pull/24178
