### ISSUE TITLE
can't update connector version without refreshing

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2417]
## Expected Behavior
If I want to update a connector version (to `dev` for example) I should be able to do so when running the UI for the first time.

## Current Behavior
Right now, if you set the value in the UI it doesn't work until you refresh.

![Screen Cast 2021-03-11 at 10 41 16 AM](https://user-images.githubusercontent.com/120362/110837849-9d224800-8256-11eb-8db5-727b17c6591e.gif)

## Airbyte Version
0.17.0-alpha

**Comment by Jamakase** [comment]
@jrhizor Looks like you are running it either on some outdated version or on an old UI.

I will check on a newer version and close the issue if not able to reproduce

**Comment by Jamakase** [comment]
Was not able to reproduce @jrhizor. Probably this was already fixed some time ago.

**Comment by jrhizor** [comment]
Thanks for checking!
