### ISSUE TITLE
Add release stage badges to usage per connection table

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#24176]
[figma](https://www.figma.com/file/568DVwWXTcagwhoB2r1Qke/01_01_BILLING?node-id=1012-17863&t=FFsK68JECqbKyAWy-0)

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- "Release stage" here means alpha/beta/GA connectors.
- API updates are in ready-to-review PR.
