### ISSUE TITLE
Source Monday: Boards stream only replicating 25 items

### ISSUE THREAD

**Issue by tanderson-hp** [airbytehq/airbyte#24194]
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: Windows 11
- **Deployment**:Docker Compose
- **Source Connector and version**: Monday 0.2.3
- **Destination Connector and version**: Snowflake 0.4.53
- **Step where error happened**: Sync Job
## Current Behavior
Boards stream pulls only 25 items and does not seem to attempt to access more.

## Expected Behavior
Boards endpoint pulls all available boards.

## Logs
[b415f4d2_da64_457a_8d61_39d7156b998f_logs_8_txt.txt](https://github.com/airbytehq/airbyte/files/11003222/b415f4d2_da64_457a_8d61_39d7156b998f_logs_8_txt.txt)

## Steps to Reproduce
1. Have a Monday.com account with more than 25 boards
2. Authenticate via API Token
3. Create a full refresh replication for the boards object.
4. Run the sync.

FYI, it seems like other objects paginate beyond the limit (like users or items)

## Are you willing to submit a PR?
Unfortunately, I cannot at this time.

**Comment by deanmorin** [comment]
I'm also seeing the 25 board limit (I'm using Airbyte Cloud, also syncing to Snowflake). 

Additionally, I'm also only able to sync 100 items per board. My `items` table has > 400 rows, but only 100 rows for boards that should have much more than that.

```sql
select board:id::int, count(*) from airbyte.monday.items group by board:id::int order by 2 desc;
```

![image](https://user-images.githubusercontent.com/416052/232337189-d7aeae10-7cae-425d-94a7-8e46065c7262.png)

**Comment by TBernstein4** [comment]
@deanmorin are you still experiencing this?

> Additionally, I'm also only able to sync 100 items per board. My items table has > 400 rows, but only 100 rows for boards that should have much more than that.

**Comment by deanmorin** [comment]
@TBernstein4 I am still. I'm not sure how connector releases work, but if they're just bundled up with the main airbyte release then there hasn't been a new version since the fix was merged.

**Comment by TBernstein4** [comment]
@deanmorin If you go to your workspace's settings page and then click sources you will see what version of every source is currently on Cloud. It looks like this fix went out in version 0.2.5

**Comment by deanmorin** [comment]
@TBernstein4 I'm on 0.2.4, I'm able to sync more boards now, but still having the 100 items per board issue. I opened a new issue for this https://github.com/airbytehq/airbyte/issues/25683

**Comment by TBernstein4** [comment]
Thank you confirming and thank you for creating a new issue!
