### ISSUE TITLE
Do not show Free Connector Program banner on GA connections

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#24211]
We show the free connector program on connections where both the source and destination are in GA. This should be excluded from having a banner as there is no benefit to the user to enrolling in FCP for those connections.

**Comment by nataliekwong** [comment]
Per @tealjulia 's suggestion, if we are going to only be showing this for Free Connector-eligible connections, the verbiage on this banner when displayed on a Connection's page can be modified to:

Enroll in the Free Connector Program to use this connector for free. 

![Screenshot 2023-04-17 at 11.46.51 AM.png](https://images.zenhubusercontent.com/626812a7b4a6641d50c1d488/813ce6d8-3087-4122-abf2-7c390ba71423)

**Comment by tealjulia** [comment]
See also this Slack message

**Comment by josephkmh** [comment]
Currently the enrollment banner is only shown on eligible connections, so I'm not quite sure what we want to do here? Is this related to the connection setup flow, or do we not want to show the FCP banners there at all? (as they might distract from completing the connection setup)

**Comment by tealjulia** [comment]
> Currently the enrollment banner is only shown on eligible connections, so I'm not quite sure what we want to do here?

Reopening the Slack thread with @nataliekwong might be worthwhile to ensure we've hit all the pieces she was hoping for.  That said, the initial intent was fulfilled after merging [this PR to fix the bug where I removed the enrollment banner from the connection page entirely.](https://github.com/airbytehq/airbyte-platform-internal/pull/6597)

**Comment by nataliekwong** [comment]
Yep, the crux of the issue is solved already by removing the banner from GA connections. Two small improvements that could be done: 

![Screenshot 2023-05-22 at 8 50 49 AM](https://github.com/airbytehq/airbyte/assets/38087517/ae6cb993-b876-43a1-bf44-3721d2220d88)
With the new header on connections, we no longer show the Alpha/Beta of the source/destination, so people see the banner only for FCP-eligible connections, but it doesn't indicate to them here why that banner shows up. Support also raised that it would be nice to bring back the alpha/beta badges here in some way and I think this is another reason why.

We also don't show the FCP banner on source/destination pages. Below I have a destination that is in beta, but no CTA for enrollment in FCP here.  I think it would be consistent to show the banner on connections, sources, and destinations. 
![Screenshot 2023-05-22 at 8 47 58 AM](https://github.com/airbytehq/airbyte/assets/38087517/df2e044b-23d8-41bc-aa82-a091ff4034c0)
And small nit here: under "Overview" it says "connection" - should that be "Connections"?

**Comment by josephkmh** [comment]
Refining notes:
- Show enrollment banner on Source / Destination pages (Alpha & Beta)
- Remove enrollment banner during connection setup
- Fix pluralization issue with single connection under Source/Destination overview https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-webapp/src/locales/en.json#L539
