### ISSUE TITLE
Source MongoDB: Support connecting to replicaSets

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2421]
## Tell us about the problem you're trying to solve
ReplicaSets (aka mongo clusters) are a very common way of deploying MongoDB instances as they  ensure better uptime for your Mongo DB instance since they can failover etc... They are the default on mongo.com's free tier. This means many users will want to connect to Mongo using them. 

There are two ways to sync data from replicasets: 
1. Connect to only one of the nodes running in the replicaset by directly using its ugly DNS name e.g: `cluster0-shard-00-01.uow6z.mongodb.net:27017`. To connect using this way, one needs to set the `replicaSet` flag to true on the connection string to Mongo. 
2. Connect to the RS loadbalancer using its pretty DNS name e.g: `cluster0.uow6z.mongodb.net`. This does not require setting `replicaSet=true` but it does typically require setting the flag `ssl=true` which is tracked in #2420. 

## Describe the solution you’d like
I would like to be able to connect to a cluster directly using its "pretty" DNS name. 

This is doable by passing the `replicaSet` flag described in https://docs.mongodb.com/ruby-driver/v2.2/tutorials/ruby-driver-create-client/. Ideally this is exposed in the connector's `spec.json` as a boolean flag which sets the underlying flag according to the input value from the user. 

To do this one needs to 
(all files are in the [`airbyte-integrations/connectors/source-mongodb`](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mongodb/) directory)
1. Add this as a boolean flag to `spec.json`
2. Edit `lib/mongodb_source.rb` to look at this boolean value and pass in the correct flag accordingly
3. Write a test case for this behavior

**Important note:** this flag automatically sets `ssl=true`. However, if we independently want to expose the `ssl` flag as a boolean flag, it could be confusing for the user. We'll need to make sure to update the descriptions in `spec.json` to tell the user about how those two flags interact.

**Comment by yevhenii-ldv** [comment]
blocked by https://github.com/airbytehq/airbyte/issues/2420#issuecomment-823214250

**Comment by arvindsaraf** [comment]
Hi - we are facing the same challenge of reading MongoDB OpsLog collection purely as a Mongo collection through Airbyte. Any idea when we can fix it?

**Comment by marcosmarxm** [comment]
@arvindsaraf could you open an issue to discuss this?
