### ISSUE TITLE
Change wording of Free Connector Program CTA

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#24215]
The small CTA added to the empty state pages has few different text styling and does not have a clear CTA. A hyperlink (not colored as a link), bold type, and then a colored blue word (not a link), causing it to be confusing to read. 

<img width="352" alt="Screenshot 2023-03-16 at 5 51 55 PM" src="https://user-images.githubusercontent.com/38087517/226067018-1e164dd8-4590-4c40-893a-804006aea663.png">

Suggestion to change to:
Join the Free Connector Program to use Alpha and Beta connectors for free [Enroll Now](hyperlink to Stripe CC page)

**Comment by nataliekwong** [comment]
Hey @dizel852 - I noticed that it looks like the font size is smaller for this banner compared to the text above and below it. It looks like the font-weight is 500 for the banner above and the buttons below. Could the banner text be adjusted to align with the rest of the page?

![Screenshot 2023-05-16 at 4 42 31 PM](https://github.com/airbytehq/airbyte/assets/38087517/0bec1776-ce4d-4cce-a479-19c861307446)

**Comment by dizel852** [comment]
> Could the banner text be adjusted to align with the rest of the page?

Sure, here is the PR - https://github.com/airbytehq/airbyte-platform-internal/pull/6639
