### ISSUE TITLE
Coda.io Connector Completion

### ISSUE THREAD

**Issue by apolo-damasco** [airbytehq/airbyte#24220]
## Tell us about the problem you're trying to solve
Last year the Coda integration was implemented into Airbyte. However, even though this integration is functional, is missing the functionality to read rows from databases, which is in my opinion the main reason for its existence.

Points to consider:
- Integration is already funcional so the work is probably already halfway there
- Airbyte is already advertising that it has the capability to add coda.io as a datasource which at this time is a half truth
- Coda's traction justifies this as a valuable connector.

## Describe the solution you’d like
The completion of the development of this connector so that it is capable of syncing rows of databases.

@YowanR here it is. https://github.com/airbytehq/airbyte/pull/18675#issuecomment-1474328880

**Comment by YowanR** [comment]
Thanks @apolo-damasco!

**Comment by bala-ceg** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by justinbchau** [comment]
Just assigned to you @bala-ceg !

**Comment by apolo-damasco** [comment]
@bala-ceg Any news on this?

**Comment by himanshuc3** [comment]
I'll take this up and complete this.

**Comment by btkcodedev** [comment]
@marcosmarxm 
Issue already resolved 
Ref: https://github.com/airbytehq/airbyte/pull/27797
