### ISSUE TITLE
Allow users to toggle visibility of deleted connections on Billing page

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#24236]
https://www.figma.com/proto/568DVwWXTcagwhoB2r1Qke/01_01_BILLING?node-id=1012-17863&scaling=min-zoom&page-id=1012%3A17863&starting-point-node-id=1046%3A14852

Awaiting design/product input on comments

1. Allow users to toggle the display of deleted connections (tbd: does this affect the table AND the graph?)
2. Show deleted connections as greyed out in the list view

**Comment by mfsiega-airbyte** [comment]
Refining notes:
- A few open questions on design, @tealjulia following up.
- Question: what is actually the use-case here? Answer: not _totally_ clear, but understanding is that this is to allow filtering out noise if you want to focus on current/future usage.
- Maybe include a `deleted` badge here as well? (Or instead?)
- To follow up.

**Comment by mfsiega-airbyte** [comment]
Refining notes: closing as Not Planned, went with an alternative approach here.
