### ISSUE TITLE
[EPIC] Replace Formik with react-hook-form

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#24246]
[Tech Spec](https://docs.google.com/document/d/1kU8CpqNKZQY91gTKc2BtcKRA021Kc9mrwgPrbvXhgoQ/edit)

```[tasklist]
### Tasks
- [ ] https://github.com/airbytehq/airbyte/issues/24303
- [ ] https://github.com/airbytehq/airbyte/issues/24304
```

**Comment by timroes** [comment]
Reopening this. This should be closed once we have the Formik dependency removed.

**Comment by josephkmh** [comment]
Refining notes:
- @dizel852 has a branch ready with the removal of formik
- We're still finalizing rollout, should ready to merge the removal PR in 1-2 weeks
