### ISSUE TITLE
Docker image octavia-cli version is not aligned with the documentation

### ISSUE THREAD

**Issue by VincentCotineau** [airbytehq/airbyte#24256]
Hi,
The documentation on how to install octavia-cli points to version 0.42.0, but only version 0.42.1 is available on https://hub.docker.com/r/airbyte/octavia-cli/tags
So the installation fails if we don't update the version targetted !

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive more updates.
