### ISSUE TITLE
Prompt the user to add a stream after global configuration

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#24264]
## Context

It is not obvious to users today what the next step is after configuring the base API url and authentication.

## Solution

See design issue here: https://github.com/airbytehq/airbyte/issues/23998

To make this clearer, we will be updating the testing side panel with an image of the sidebar showing the add stream button glowing and an explanatory note, and animating the add stream button after the global inputs have been configured.

[Design](https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=4145%3A141716&node-id=4145-184554&viewport=695%2C224%2C0.14&scaling=min-zoom&starting-point-node-id=4145%3A184554&show-proto-sidebar=1):
![Screen Shot 2023-03-20 at 5.14.19 PM.png](https://images.zenhubusercontent.com/6269bd44b04db403a70af8df/99e3a8cf-7d38-4a13-a5e5-67d8d728643a)

## Acceptance criteria
- If no streams exist, the testing side panel shows an image of the sidebar with an arrow and note explaining that is how to add a stream
- After the base API Url has been set, an authentication method has been selected, required fields filled out in both the global config view and the testing inputs, then the add stream button is highlighted as in the prototype. This goes away once a stream is added
- The `Inputs` button in the testing side panel is renamed to `Test values`

**Comment by flash1293** [comment]
Grooming notes:
* Always show the screenshot in the testing panel if there are no streams
* Condition to make the button pulsate:
  * Auth is set to something else than no auth
  * There are no streams configured
  * There are no errors in the global part of the form values

**Comment by flash1293** [comment]
Set `validateOnMount` to true to be able to rely on the formik errors object
