### ISSUE TITLE
Airbyte 0.41.0 worker memory leak in k8s

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#24269]
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**: ContainerD
- **Deployment**: Kubernetes GKE

## Current Behavior
The worker services keeps using more and more memory over time. 

## Expected Behavior
Some sort of memory cleanup, garbage collection? Not sure why it keeps going up. Currently at 15GB RAM usage in about 5 days of running

## Logs
The only errors being displayed in the worker log are the following
[
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "nqw39xn3wyz57wxv",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "namespace_name": "default",
        "cluster_name": "airbytecluster",
        "location": "europe-west3",
        "pod_name": "airbytecluster-worker-6bb9dff46-ldmzq",
        "container_name": "airbyte-worker-container",
        "project_id": "datasyncsystem"
      }
    },
    "timestamp": "2023-03-21T07:46:19.270823893Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/app_kubernetes_io/name": "worker",
      "k8s-pod/pod-template-hash": "6bb9dff46",
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster",
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-0b411a1d-mcsk"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:46:20.213316928Z"
  },
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "ekjraig3ssj1un5i",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "location": "europe-west3",
        "project_id": "datasyncsystem",
        "pod_name": "airbytecluster-worker-6bb9dff46-j6fcf",
        "cluster_name": "airbytecluster",
        "container_name": "airbyte-worker-container",
        "namespace_name": "default"
      }
    },
    "timestamp": "2023-03-21T07:44:15.542672655Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/pod-template-hash": "6bb9dff46",
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-9aefc0b2-7s6x",
      "k8s-pod/app_kubernetes_io/name": "worker",
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:44:17.549509661Z"
  },
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "vfg4afzjlusu9cna",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "pod_name": "airbytecluster-worker-6bb9dff46-ldmzq",
        "project_id": "datasyncsystem",
        "location": "europe-west3",
        "namespace_name": "default",
        "container_name": "airbyte-worker-container",
        "cluster_name": "airbytecluster"
      }
    },
    "timestamp": "2023-03-21T07:43:19.238774962Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/app_kubernetes_io/name": "worker",
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-0b411a1d-mcsk",
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster",
      "k8s-pod/pod-template-hash": "6bb9dff46"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:43:20.162768464Z"
  },
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "qsm0cl5qoz4h74hp",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "container_name": "airbyte-worker-container",
        "cluster_name": "airbytecluster",
        "namespace_name": "default",
        "location": "europe-west3",
        "project_id": "datasyncsystem",
        "pod_name": "airbytecluster-worker-6bb9dff46-ldmzq"
      }
    },
    "timestamp": "2023-03-21T07:42:19.323748136Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-0b411a1d-mcsk",
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster",
      "k8s-pod/app_kubernetes_io/name": "worker",
      "k8s-pod/pod-template-hash": "6bb9dff46"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:42:20.242007111Z"
  },
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "4cb5yughzx852qro",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "cluster_name": "airbytecluster",
        "location": "europe-west3",
        "project_id": "datasyncsystem",
        "container_name": "airbyte-worker-container",
        "namespace_name": "default",
        "pod_name": "airbytecluster-worker-6bb9dff46-9lqd7"
      }
    },
    "timestamp": "2023-03-21T07:40:20.319984584Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster",
      "k8s-pod/pod-template-hash": "6bb9dff46",
      "k8s-pod/app_kubernetes_io/name": "worker",
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-44fa2def-zdv6"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:40:25.258253922Z"
  },
  {
    "textPayload": "Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.",
    "insertId": "uc4z6r3ypt3vymtx",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "container_name": "airbyte-worker-container",
        "namespace_name": "default",
        "project_id": "datasyncsystem",
        "location": "europe-west3",
        "pod_name": "airbytecluster-worker-6bb9dff46-st87k",
        "cluster_name": "airbytecluster"
      }
    },
    "timestamp": "2023-03-21T07:40:20.319937626Z",
    "severity": "ERROR",
    "labels": {
      "k8s-pod/pod-template-hash": "6bb9dff46",
      "compute.googleapis.com/resource_name": "gke-airbytecluster-pool-1-44fa2def-zdv6",
      "k8s-pod/app_kubernetes_io/instance": "airbytecluster",
      "k8s-pod/app_kubernetes_io/name": "worker"
    },
    "logName": "projects/datasyncsystem/logs/stderr",
    "receiveTimestamp": "2023-03-21T07:40:25.325431833Z"
  }
]

**Comment by ro8inmorgan** [comment]
> 

My work around currently is to run multiple worker replications and impose a memory limit on kubernetes. It will restart the pods who are over their limit and as of now it seems to not be any problems for the running syncs. So yeah we can continue  using Airbyte. But would be nice if this could be figured out as it is very unwanted behaviour. 
We currently are running about 20 syncs ranging from 3GB to 60GB of data. 

We use Prefect to orchestrate our syncs and I have GKE setup to manage the cluster mostly automatically by scaling up when needed and restart pods that go over their limits.

**Comment by HMubaireek** [comment]
Any update on this issue? We face the same problem

**Comment by philippeboyd** [comment]
Same here when starting an Oracle -> Snowflake sync (Running 0.44.4 outside K8s though)
![image](https://github.com/airbytehq/airbyte/assets/3239656/a2c56589-b651-43a3-8b0c-20451fae33a9)

**Comment by natikgadzhi** [comment]
Worker had a big rewrite in worker v2 —try this again, should be fixed now.
