### ISSUE TITLE
Source Drift: hide connector in UI

### ISSUE THREAD

**Issue by arsenlosenko** [airbytehq/airbyte#24270]
Source Drift is currently blocked from enabling in Cloud, so it should be hidden in UI for the time being.
**Reason for hiding in UI**: during seeding of `accounts` stream we found out that the developer account that is needed to access this stream is [too expensive](https://www.drift.com/pricing/), because of that it was hidden in UI.

**Comment by bnchrch** [comment]
@arsenlosenko Im reopening this. Could you link the issue for whats preventing this from being enabled in cloud?

**Comment by arsenlosenko** [comment]
@bnchrch I don't have exact link to the issue which explains why this source was blocked from enabling on cloud, as far as I remember we were blocked here because `accounts` stream was relying on an expensive paid plan in order to be properly seeded, thus we were not able to proceed with it.

**Comment by bnchrch** [comment]
Ok thats at least useful context! @arsenlosenko Would you be able to create a ticket for GL to track that? (or let me know who to ping :))

No pressure to do the work to update this connector.

I just want to make sure the next time someone looks at our list of Hidden connectors they can know if the connector should still be hidden :)

**Comment by arsenlosenko** [comment]
@bnchrch yep, makes sense, I'll see if there are any tickets which explain the situation better or create one if I won't find anything

**Comment by arsenlosenko** [comment]
@bnchrch I didn't find a proper ticket with explanation of blocking for Drift, most likely we had a discussion about this somewhere in Slack but I couldn't find anything there either, so I updated the description of this issue with short explanation why this source was hidden. 
Please let me know if this is clear for now, and if I can close this issue, thanks!

**Comment by bnchrch** [comment]
@arsenlosenko seems good enough!

Notes for future readers: If we want this in cloud we need to find a way to make the integration test sandbox inexpensive, or have a discussion around paying the high cost or ignoring testing
