### ISSUE TITLE
Source code compilation error:Execution failed for task ':tools:code-generator:airbyteDocker'.

### ISSUE THREAD

**Issue by gongzexin** [airbytehq/airbyte#24274]
I wanted to compile the source code locally, executed command `gradle clean build -x test`, but encountered an error, here is my environment information and compile log.

![env](https://user-images.githubusercontent.com/63918706/226566655-ed223f2f-7933-4dcc-bdf8-863b2705dd7c.jpg)

[build.log](https://github.com/airbytehq/airbyte/files/11026796/build.log)

**Comment by marcosmarxm** [comment]
Gradle was removed and now you need to use `airbyte-ci` tool to build connectors.
