### ISSUE TITLE
Populate the "differences with" documentation page

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2429]
## Tell us about the documentation you'd like us to add or update
I went to the ["differences with X"](https://docs.airbyte.io/faq/differences-with) page because I'm between Fivetran and Airbyte. However, the pages were blank, so I'm going to Fivetran. Just thought you should know!

**Comment by sherifnada** [comment]
@johnlafleur could you kickstart this and I/the team will be happy to help with any technical details?

**Comment by michel-tricot** [comment]
I think the doc is broken #2374
