### ISSUE TITLE
Convert move forms to react-hook-form

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24303]
Tech spec: https://docs.google.com/document/d/1kU8CpqNKZQY91gTKc2BtcKRA021Kc9mrwgPrbvXhgoQ/edit#heading=h.fa72b39y2m99

All forms owned by the move team should be converted from formik to react-hook-form.

~~This is blocked on https://github.com/airbytehq/airbyte/issues/24292~~

List of forms:
* [x] NormalizationCard https://github.com/airbytehq/airbyte-platform-internal/pull/7943
* [x] CustomTransformationsCard https://github.com/airbytehq/airbyte-platform-internal/pull/7943
* [x] TransformationForm https://github.com/airbytehq/airbyte-platform-internal/pull/7943
* [x] DbtJobsForm https://github.com/airbytehq/airbyte-platform-internal/pull/8296
* [x] DestinationNamespaceModal https://github.com/airbytehq/airbyte-platform-internal/pull/8076
* [x] DestinationStreamNamesModal https://github.com/airbytehq/airbyte-platform-internal/pull/8076
* [ ] CreateConnectionForm https://github.com/airbytehq/airbyte/issues/29585
* [x] ~~ConnectionEditFormCard~~ - it's just a form wrapper for `NormalizationCard` and `CustomTransformationsCard` forms. Can be removed after [PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7943) will be successfully rolled out
* [x] ~~ExistingEntityForm~~ - obsolete component, can be removed https://github.com/airbytehq/airbyte-platform-internal/pull/7951

**Comment by josephkmh** [comment]
@dizel852 I think we can... close this issue?! 🎉

**Comment by dizel852** [comment]
> @dizel852 I think we can... close this issue?! 🎉

Hm... technically, yes. We have another specific [CreateConnectionForm](https://github.com/airbytehq/airbyte/issues/29585) epic where only one task remains to be done (clean up).

So, closing it ✅
