### ISSUE TITLE
Convert compose forms to react-hook-form

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24304]
Tech spec: https://docs.google.com/document/d/1kU8CpqNKZQY91gTKc2BtcKRA021Kc9mrwgPrbvXhgoQ/edit#heading=h.fa72b39y2m99

All forms owned by the compose team should be converted from formik to react-hook-form.

~~This is blocked on https://github.com/airbytehq/airbyte/issues/24292~~

### List of forms:
- [x] oss/SetupForm https://github.com/airbytehq/airbyte-platform-internal/pull/7215
- [x] cloud/AcceptEmailInvite https://github.com/airbytehq/airbyte-platform-internal/pull/7600
- [x] cloud/ResetPasswordConfirmPage https://github.com/airbytehq/airbyte-platform-internal/pull/7687
- [x] cloud/LoginPage https://github.com/airbytehq/airbyte-platform-internal/pull/7687
- [x] cloud/ResetPasswordPage https://github.com/airbytehq/airbyte-platform-internal/pull/7687
- [x] cloud/SignupForm https://github.com/airbytehq/airbyte-platform-internal/pull/7687
- [x] cloud/InviteUsersModal https://github.com/airbytehq/airbyte-platform-internal/pull/7466
- [x] SettingsPage/AccountForm https://github.com/airbytehq/airbyte-platform-internal/pull/6238
- [x] SettingsPage/CreateConnectorModal https://github.com/airbytehq/airbyte-platform-internal/pull/7160
- [x] SettingsPage/VersionCell https://github.com/airbytehq/airbyte-platform-internal/pull/7294
- [x] cloud/DbtCloudSettingsView https://github.com/airbytehq/airbyte-platform-internal/pull/6876
- [x] cloud/CreateWorkspaceForm https://github.com/airbytehq/airbyte-platform-internal/pull/6922
- [x] cloud/DataResidencyView https://github.com/airbytehq/airbyte-platform-internal/pull/6815
- [x] cloud/EmailSection https://github.com/airbytehq/airbyte-platform-internal/pull/6696
- [x] cloud/PasswordSection https://github.com/airbytehq/airbyte-platform-internal/pull/6696
- [x] cloud/NameSection https://github.com/airbytehq/airbyte-platform-internal/pull/5937
- [x] cloud/WorkspaceSettingsView https://github.com/airbytehq/airbyte-platform-internal/pull/6706
- [x] ~~SettingsPage/WebHookForm~~ - can be skipped, as the form will be rewritten here anyway: https://github.com/airbytehq/airbyte/issues/25941
- [x] ~~Settings/PreferencesForm~~ - can be skipped (nothing to migrate)

**Comment by dizel852** [comment]
@josephkmh I guess `Settings/PreferencesForm` it's  actually `Cookie Preferences` [osana side drawer](https://github.com/airbytehq/airbyte-platform-internal/blob/ef957bd37abcb0fe7a5b4e224de1da3bc455b89a/oss/airbyte-webapp/src/packages/cloud/views/settings/CloudSettingsPage.tsx#L43).
And can be skipped since it's not related to Formik forms. 
Please, confirm 🙂 

<img width="635" alt="image" src="https://github.com/airbytehq/airbyte/assets/20929344/05717153-f59e-4067-9db3-c4bdc350565f">

**Comment by josephkmh** [comment]
@dizel852 yes I think that's correct! But that reminds me that there is also the OSS instance setup form (`SetupForm`) which I just added to the list too.
