### ISSUE TITLE
Timestamp type is not being updated in the airbyte UI

### ISSUE THREAD

**Issue by siddhant3030** [airbytehq/airbyte#24302]
![screenshot_2023-03-17_at_5](https://user-images.githubusercontent.com/9019958/226847437-4ddebd79-b5d6-40e8-978a-6a354541228a.png)
## Current Behavior
So currently when we create the connection between source and destination it discovers the schema. In that schema, UI is not being updated for the timestamp field and it shows us an Unknown field for the timestamp. 

You can see here CreatedDate as unknown and other fields too. 

Replication Step
1.  Add a Source
2. Add a destination 
3. Make a connection between the source and destination 
4. Check the cursor field data type. 

Updating the issue with the latest changes

<img width="1306" alt="Screenshot 2023-04-05 at 12 15 05 PM" src="https://user-images.githubusercontent.com/9019958/230001972-0ceeb2e6-0349-4a1e-9549-e9aad5e66726.png">

## Expected Behavior
It should give the type of timestamp correctly. It looks confusing otherwise

## Logs

**Comment by sajarin** [comment]
Hey @siddhant3030 it looks like you uploaded an image of some private information, I edited your post to remove it to protect your privacy. Please be more careful when uploading images next time.

Thanks for the issue, can you include the relevant screenshots of the issue in the UI?

**Comment by siddhant3030** [comment]
@sajarin Sorry for that. Thanks for doing that. I have updated the image.

**Comment by siddhant3030** [comment]
this is not a airbyte issue so I'm closing this
