### ISSUE TITLE
Auto-update our singer tap forks when upstream changes

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2431]
## Tell us about the problem you're trying to solve
We have a number of singer taps forked which contain bugfixes and other goodies (see all repositories which start with `tap-` in https://github.com/airbytehq) . But when upstream changes we have no way of knowing. We would like to know when upstream changes, using something like: https://github.com/wei/pull

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368218108882) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@sherifnada closing this as we don't do singer taps anymore.
