### ISSUE TITLE
Deprecated - Zoom JWT - June  2023

### ISSUE THREAD

**Issue by jcolinger3** [airbytehq/airbyte#24333]
The Zoom JWT looks to be deprecated starting in June 2023.
https://marketplace.zoom.us/docs/guides/build/jwt-app/

[Documentation](https://docs.airbyte.com/integrations/sources/zoom/) should be updated for the connector.

**Comment by lazebnyi** [comment]
Duplicate - https://github.com/airbytehq/airbyte/issues/23268
