### ISSUE TITLE
Improving UI Jobs / Sources / Destinations

### ISSUE THREAD

**Issue by juan-meister** [airbytehq/airbyte#2435]
## Tell us about the problem you're trying to solve
The UI/UX is not very clear concerning the Jobs / Sources / Destinations

## Describe the solution you’d like
On the left sidebar, having "Jobs" / "Sources" / "Destinations"

## Describe the alternative you’ve considered or used
No alternative

**Comment by sherifnada** [comment]
@juan-meister could you elaborate on what the "Jobs" tab would contain?

**Comment by juan-meister** [comment]
@sherifnada 

I jobs you would have :
- The source - the destination - Status (running or next scheduled run) - Last run

Sources
- The sources that you already setup
- A button tu modify the setup 
- No destination information

Destinations 
- Your destinations
- Setup the destinations
- No information about the sources

**Comment by sherifnada** [comment]
Got it so "jobs" is kind of like a connections view. CC @johnlafleur as our designer.

**Comment by johnlafleur** [comment]
Hey @juan-meister!
We're about to upgrade the visibility you have from "Sources" and "Destinations" section on the liveliness of your connectionrs with the following: https://www.figma.com/file/pO3Ob5W0yKUFOQzvg8TR3z/Airbyte?node-id=1997%3A2498
Is your issue about visibility on connection liveliness? And if so, would those new designs address your issue?
Or is it about something else?

**Comment by juan-meister** [comment]
Hello @johnlafleur 
Yes, [this](https://p479.p0.n0.cdn.getcloudapp.com/items/04uJXnXd/1815701c-8b45-4dfc-b5c3-a77af8d6e4c5.jpg?v=a4dcb63435c52677334bd6696c6ff420) is more like it, because [this](https://p479.p0.n0.cdn.getcloudapp.com/items/ApuR0q0p/031c0b6d-5de4-427b-8edf-e83857aec5e6.jpg?v=a5fa6fd0517e38120d9936645dbbe5d7) UX very confusing.

**Comment by johnlafleur** [comment]
Hi @juan-meister,
I understand your point, but when looking at a source, you want to see the associated destinations. 
So in this [screenshot](https://p479.p0.n0.cdn.getcloudapp.com/items/ApuR0q0p/031c0b6d-5de4-427b-8edf-e83857aec5e6.jpg?v=a5fa6fd0517e38120d9936645dbbe5d7), we can't display the detail of the sources and have the "Connections" section in the left column highlighted at that point. It would be more confusing. Are you at the source level or at the connections? Are those settings the source ones or the connection ones?

I can't see how we can improve the navigation when you start from a source (or a destination). Unless you see one?

That said, you're saying then that you want a "Connections" section in the left column, not for visibility but for more understandable paths and UX?

**Comment by juan-meister** [comment]
@johnlafleur 
Correct. 
There's a lot of information to unpack in the "Source" tab, it's not necessary to put also the connections. Mainly the configuration (see the singer variables in config + catalog)
If you want to know to which destinations it is connected, you can go to the "Connections" tab and filter by connector and voilà. There you have the information. And if you have a lot of data, you can give some stats. How many times is this connector used ? Is the same connector used in all the pipelines (cf variants of the connector as they called it in Meltano)?
I think that my 2nd screenshot is pretty self-explanatory about the fact that the wording used in the current UI is far from straightforward for me.

**Comment by johnlafleur** [comment]
I think you will need to see the associated destinations at the source level. This is actually possibly the most important information, and it makes it easier to add a new connection for a said source. So this part can't be removed. But it can be improved. 

We'll think about the "Connections" tab, and see how other users feel about it. Thanks!

**Comment by johnlafleur** [comment]
Here's a suggestion of design:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=23938%3A3079
Is this what you had in mind @juan-meister

**Comment by juan-meister** [comment]
Yes
But I still think that putting "add destination" in the Sources tab is weird. But I noticed that Fivetran does it too

**Comment by johnlafleur** [comment]
Segment too...I feel it's pretty convenient to see the destinations there and be able to add one from that page too.

**Comment by johnlafleur** [comment]
Here is the proposal for the detailed designs: https://www.figma.com/file/pO3Ob5W0yKUFOQzvg8TR3z/Airbyte?node-id=1903%3A823

**Comment by juan-meister** [comment]
It makes a lot of sense but [there's a little "bug"](https://p479.p0.n0.cdn.getcloudapp.com/items/Blu4g795/5e852248-7b06-423b-a9ff-5ae0671e442e.jpg?v=d7cb395cf812ad1f641814c9d0785634). At the left you have the connections tab that is present at the right one.

**Comment by johnlafleur** [comment]
It's okay. It's just a component across all mockups, so that we're more efficient in UI design. 
We'll have the connections tab in the left column, once we've implemented this issue.

**Comment by cgardens** [comment]
I believe this has been addressed by: https://github.com/airbytehq/airbyte/issues/2642. LMK if there are any outstanding concerns here!
