### ISSUE TITLE
Source Dixa - Add missing fields for conversation export

### ISSUE THREAD

**Issue by natalia-miinto** [airbytehq/airbyte#24357]
## What
The conversation_export table coming from Dixa is missing 2 fields - transferee_number and custom_fields.

## How
Update the JSON schema file for the Dixa source connector to include transferee_number and custom_fields.

**Comment by btkcodedev** [comment]
@jrolom Source Dixa has fields transferee_number and custom_fields already
ref - 
1) https://github.com/airbytehq/airbyte/blob/47e01208be5f7a031008cb9cd757a8cc0389aada/airbyte-integrations/connectors/source-dixa/source_dixa/schemas/conversation_export.json#L196
2) https://github.com/airbytehq/airbyte/blob/47e01208be5f7a031008cb9cd757a8cc0389aada/airbyte-integrations/connectors/source-dixa/source_dixa/schemas/conversation_export.json#L163
