### ISSUE TITLE
connectors-ci: use local CDK when CDK change were made on the branch 

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#24374]
## Tell us about the problem you're trying to solve
The /test command allows developers to run CAT on connectors using the local CDK.
This is achieved with this [script](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/scripts/build-connector-image-with-local-cdk.sh#L1).
We need to re-implement this script in the dagger pipeline to install connectors with the local CDK version.

## Suggestion:

A. (Preferred) Always build connectors with the local CDK when modified files in the branch touch the CDK. **This is convenient to not introduce a dedicated slash command and keep the current automatic testing behavior.** We should add a `cdk_version` attribute to the connector context and propagate its value to the test report so that developer can know if the local cdk was used or not.

B. Add a flag like `airbyte-ci connectors --local-cdk --name=source-pokeapi test` to run test/publish with the local CDK version.

**Comment by bnchrch** [comment]
Closing as `--local-cdk` flag exists 
https://github.com/airbytehq/airbyte/issues/28428
