### ISSUE TITLE
Destination Snowflake: support configuration of the number of threads utilised by DBT for normalisation run

### ISSUE THREAD

**Issue by bittercoder** [airbytehq/airbyte#24388]
## Tell us about the problem you're trying to solve

When synchronising a database with many tables in the source to snowflake (though I'm sure this also applies to other destinations) utilising dedupe + history, a significant amount of time is spent executing the DBT normalisation step (10+ minutes) even when there is very little data in each table.  This is largely limited by the rate of concurrency (`threads` in the dbt config) being hard coded to 5 threads.

```
dbt_config = {
            "type": "snowflake",
            "account": account,
            "user": config["username"].upper(),
            "role": config["role"].upper(),
            "database": config["database"].upper(),
            "warehouse": config["warehouse"].upper(),
            "schema": config["schema"].upper(),
            "threads": 5, <----
            ...
```

## Describe the solution you’d like

I would like there to be a way to customise the number of threads DBT utilised to perform normalisation when there is a large number of tables, or where the snowflake warehouse being utilised is larger and able to execute more concurrent operations without experiencing queuing.

## Describe the alternative you’ve considered or used
I have considered using `DBT_PROFILES_DIR` environment variable to override, but I believe the `--profiles-dir` command line option being utilised will take precedence.

## Additional context
In my experience with small but numerous tables, DBT apply times can be significantly improved by setting the threads count quite high (32 or even 64 threads).

## Are you willing to submit a PR?
I would be happy to supply a PR to address this - but might need some guidance - ideally being able to override the number of threads used by DBT for normalisation for any destination (not just snowflake) feels like it would provide the most utility.

**Comment by sh4sh** [comment]
I wonder if it'd make sense to add it into the connector config similar to https://github.com/airbytehq/airbyte/pull/7118?

The value is set here: https://github.com/airbytehq/airbyte/blob/388e157543142cdf169510947de304172d026a44/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py#L213-L234

**Comment by bittercoder** [comment]
I feel like that does make sense @sh4sh - I'm still getting to grips with how to how the CDK etc. works - what's the process for exposing a new config option in the UI for a connection?

**Comment by bittercoder** [comment]
Closing this now the architecture of destinations has changed such that DBT based normalisation is no longer a thing.
