### ISSUE TITLE
Convert DropDown to ListBox (move team)

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24391]
The `DropDown` component is deprecated and should be replaced by the `ListBox` component.

For the compose team the following places should be replaced:
* [x] oss/airbyte-webapp/src/components/connection/CatalogTree/SyncSettingsDropdown.tsx https://github.com/airbytehq/airbyte-platform-internal/pull/8982
* [x] oss/airbyte-webapp/src/components/connection/ConnectionForm/NamespaceDefinitionField.tsx - fixed in scope of https://github.com/airbytehq/airbyte-platform-internal/pull/8685)
* [x] oss/airbyte-webapp/src/components/connection/ConnectionForm/NonBreakingChangesPreferenceField.tsx - fixed in scope of https://github.com/airbytehq/airbyte-platform-internal/pull/8685)
* [x] oss/airbyte-webapp/src/components/connection/ConnectionForm/ScheduleField.tsx - fixed in scope of https://github.com/airbytehq/airbyte-platform-internal/pull/8685)
* [x] oss/airbyte-webapp/src/components/connection/TransformationForm/TransformationForm.tsx - fixed in scope of https://github.com/airbytehq/airbyte-platform-internal/pull/8685)
* [x] ~~oss/airbyte-webapp/src/pages/connections/CreateConnectionPage/ExistingEntityForm.tsx~~ - obsolete and was removed https://github.com/airbytehq/airbyte-platform-internal/pull/7951

**Comment by josephkmh** [comment]
This will be resolved once the react-hook-form migration is completed

**Comment by dizel852** [comment]
This issue can be closed after https://github.com/airbytehq/airbyte-platform-internal/pull/8835 is merged since all changes from https://github.com/airbytehq/airbyte-platform-internal/pull/8685 are behind the feature flag.
