### ISSUE TITLE
Convert Dropdown to Listbox (compose team)

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24390]
The `DropDown` component is deprecated and should be replaced by the `ListBox` component.

For the compose team the following places should be replaced:
* [x] components/common/DataGeographyDropdown/DataGeographyDropdown.tsx (https://github.com/airbytehq/airbyte-platform-internal/pull/6004)
* [x] packages/cloud/views/users/InviteUsersModal/InviteUsersModal.tsx - https://github.com/airbytehq/airbyte-platform-internal/pull/7466

**Comment by flash1293** [comment]
@josephkmh could you check whether the list for compose vs move (#24391) is right?

**Comment by josephkmh** [comment]
Yes that looks good to me!

**Comment by dizel852** [comment]
Closing this one since all mentioned components in the description already use the `<ListBox />` component
