### ISSUE TITLE
Source MySQL: exception while closing

### ISSUE THREAD

**Issue by antonapua** [airbytehq/airbyte#24451]
## Environment
- **Airbyte version**:   0.41
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: mysql  2.0.8
- **Destination Connector and version**: 0.3.26
- **Step where error happened**: Sync Job

## Current Behavior
It seems the source connector is not stopping and destination connector seems to be proceeding and gets stuck

## Expected Behavior
source connector completes job smoothly and sync job completes as usual

## Logs
[a157f284_c811_4c38_86bb_e988950fcdd5_logs_56_txt.txt](https://github.com/airbytehq/airbyte/files/11060064/a157f284_c811_4c38_86bb_e988950fcdd5_logs_56_txt.txt)

## Steps to Reproduce
1. Standard Sync mysql to postgres

Additional information
There could be some data in the table I'm synching that could be causing this, as I've sync another table with this connection and runs smoothly

## Are you willing to submit a PR?
I'm not technically inclined/capable in resolving the issue

**Comment by prateekmukhedkar** [comment]
@antonapua please try upgrading the MySQL source connector to the latest version (3.x) where we have made reliability improvements in the connector. I am closing this issue for now and in case you still see errors reopen it.
