### ISSUE TITLE
[blocked] User should be able to apply all possible sync modes in bulk edit

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#24467]
Followup to #21029

- [ ] User should be able to select any sync mode that is supported by the source/destination from the dropdown, but when applied it only applies to the streams that can support it
- [ ] Update design to indicate whether the selection is supported or it will be partially applied:

Design: [Figma](https://www.figma.com/file/liLQhcbpVHiEDW18kiXQe3/01_03_CONNECTIONS?node-id=6543-124195&t=XdOOJvtYI50bOAT4-0)

**Comment by edmundito** [comment]
The "supported" wording needs to be updated in the design, this is still being verified.

**Comment by dizel852** [comment]
Blocked by https://github.com/airbytehq/airbyte/issues/25014

**Comment by josephkmh** [comment]
Closing as we are going to remove the bulk edit panel
