### ISSUE TITLE
Move cypress test to `airbyte-webapp`

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#24464]
- [ ] Cypress folder, deps and scripts should be part of `airbyte-webapp`
- [ ] Ensure that both cypress and the src share a standard lint file
- [ ] Gradle scripts and CI workflows are updated to run e2e tests from `airbyte-webapp`
- [ ] Remove `airbyte-webapp-e2e-tests`

**Comment by ambirdsall** [comment]
Also move the new cloud test suite from the closed-source cloud repo's `cloud-webapp/` directory
