### ISSUE TITLE
Connector builder: Date format suggestions

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24474]
Suggestions for date formats which can be used in date formatting fields (and point to them from tooltips or show them directly in tool tips) as auto-suggestion in the UI

Also maybe date picker for start date once we have a valid format

Requires combobox component like https://github.com/airbytehq/airbyte/issues/24119

**Comment by girarda** [comment]
closing because we have suggestions now
<img width="663" alt="Screen Shot 2023-04-26 at 7 20 47 PM" src="https://user-images.githubusercontent.com/1451943/234743308-4306c001-345d-4830-b90a-7c5d393223d7.png">
