### ISSUE TITLE
Ensure all source-mysql datatypes are represented correctly in airbyte datatypes

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#24470]
All possible [mysql datatypes](https://dev.mysql.com/doc/refman/8.0/en/data-types.html) need to convert correctly to both airbyte datatype v0 ~and v1~.
Ensure and file issues for any work that needs to be done.

~V1 Ref: https://docs.google.com/document/d/1FupBVPMlDTU2QnEOxN42BKvdWk-Yha8604MnU5EmDRQ/edit?usp=sharing~

Airbyte protocol datatype ref: https://docs.airbyte.com/understanding-airbyte/supported-data-types
MySql types to JDBC ref: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-type-conversions.html

**Comment by prateekmukhedkar** [comment]
Create MySQL table with all datatypes. (see if we can use Faker)

**Comment by rodireich** [comment]
Looks like this was previously done:
A previous [issue](https://github.com/airbytehq/airbyte/issues/7726) and its [PR](https://github.com/airbytehq/airbyte/pull/7970) with a similar goal.

We need to see where to what improvements, if any, are needed.

**Comment by rodireich** [comment]
Summary:
I created a unit test going over all datatypes and validates the expected behavior.
Two issues that I see:

1. Translation of a `Decimal(M, 0)` (zero decimal points) is giving us a double rather than an integer. #25027 
2. Need to revisit behavior of `YEAR` - translated to a `STRING` rather than an integer/date type. #8722 

Having this test will also help us notice breaking changes in future release of mysql or in JDBC driver upgrades.

**Comment by rodireich** [comment]
Summary:
I created a unit test going over all datatypes and validates the expected behavior.
Two issues that I see:

1. Translation of a `Decimal(M, 0)` (zero decimal points) is giving us a double rather than an integer. #25027 
2. Need to revisit behavior of `YEAR` - translated to a `STRING` rather than an integer/date type. #8722 

Having this test will also help us notice breaking changes in future release of mysql or in JDBC driver upgrades.

**Comment by rodireich** [comment]
We should also discuss support of no standard charsets: [ticket 1](https://github.com/airbytehq/airbyte/issues/9938) and [ticket 2](https://github.com/airbytehq/airbyte/issues/3340).
I did not see any immediate or breaking problem in source.
