### ISSUE TITLE
Source Hubspot: Support OAuth 

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#2449]
## Tell us about the problem you're trying to solve
Airbyte will soon support Oauth in the UI. We want to start supporting it for connectors which require it. 

## Describe the solution you’d like
update spec to

```json
"credentials": {
        "type": "object",
        "oneOf": [
          {
            "title": "api key",
            "required": ["api_key"],
            "properties": {
              "api_key": {
                "description": "Hubspot API Key. See our <a href=\"https://docs.airbyte.io/integrations/sources/hubspot\">docs</a> if you need help finding this key.",
                "type": "string",
                "airbyte_secret": true
              }
            }
          },
          {
            "title": "oauth",
            "required": [
              "redirect_uri",
              "client_id",
              "client_secret",
              "refresh_token"
            ],
            "properties": {
              "redirect_uri": {
                "description": "Hubspot API Key. See our <a href=\"https://docs.airbyte.io/integrations/sources/hubspot\">docs</a> if you need help finding this key.",
                "type": "string",
                "examples": ["https://api.hubspot.com/"]
              },
              "client_id": {
                "description": "Hubspot client_id. See our <a href=\"https://docs.airbyte.io/integrations/sources/hubspot\">docs</a> if you need help finding this id.",
                "type": "string",
                "examples": ["123456789000"]
              },
              "client_secret": {
                "description": "Hubspot client_secret. See our <a href=\"https://docs.airbyte.io/integrations/sources/hubspot\">docs</a> if you need help finding this secret.",
                "type": "string",
                "examples": ["secret"],
                "airbyte_secret": true
              },
              "refresh_token": {
                "description": "Hubspot refresh_token. See our <a href=\"https://docs.airbyte.io/integrations/sources/hubspot\">docs</a> if you need help generating the token.",
                "type": "string",
                "examples": ["refresh_token"],
                "airbyte_secret": true
              }
            }
          }
        ]
      }
```

## Describe the alternative you’ve considered or used
Use API Token authentication

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368153792222) by [Unito](https://www.unito.io)

**Comment by htrueman** [comment]
## Scoping Report ##

For the Hubspot oauth flow we need the following credentials:
- `client id`
- `client secret`
- `redirect url`
- `scope` (see https://github.com/airbytehq/airbyte/issues/3011)
- `access_token`
- `refresh_token`

We may found `client_id` and `client_secret` in the application settings. Then we should send a request to hubspot with `client_id` and `client_secret` query params to obtain the `access_token` and the `refresh_token`. None that `scope` param is also required at this step.

After the `access_token` and the `refresh_token` obtained it's possible to use our CDK authenticators to make API calls. It also would be really good to have some periodic job to obtain the new `access_token`/`refresh_token` pair. We should to that to keep our connector sample creds up to date as after the `refresh_token` is expired, the only way to get the new pair is to use the frontend interface again.

Also I think it's not really usable to store the `access_token`/`refresh_token` pair in the LastPass. And the better way to get them is to add the docs to connector, so developer would obtain them when needed.

Hubspot oauth docs: https://developers.hubspot.com/docs/api/working-with-oauth
