### ISSUE TITLE
Source TikTok Marketing: Add undeclared columns to spec

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#24504]
## What
In this [PR](https://github.com/airbytehq/airbyte/pull/23985), `BasicReadTest.test_read` test in the Connector Acceptance Tests was updated to fail if the connector produces
stream records which contain columns that haven't been declared in the spec.

TikTok Marketing currently fails the updated test. Its `acceptance-test-config.yml` was edited with the
`fail_on_extra_columns: false` parameter in order to avoid this change from making the connector fail CAT.

We want to add the undeclared columns to the spec.

**How this will help**:
- Column selection is currently blocked for connectors that don't declare all columns that they pass. This
  is because turning on column selection will stop these undeclared columns from being sent, when they were
  previously being sent. Doing this allows us to enable column selection for TikTok Marketing!
- Users will better understand the shape of the data they'll receive, since the columns will match the spec.

## How
The following descriptions of streams that pass undeclared columns come from results of the failed connector acceptance test:

```
columns.txt:./source-tiktok-marketing.txt-88-The advertisers stream has the following schema errors:
columns.txt:./source-tiktok-marketing.txt:89:Additional properties are not allowed ('promotion_center_city', 'license_city', 'telephone', 'license_province', 'display_timezone', 'promotion_center_province', 'brand' were unexpected)
columns.txt:./source-tiktok-marketing.txt-146-The ads stream has the following schema errors:
columns.txt:./source-tiktok-marketing.txt:147:Additional properties are not allowed ('brand_safety_vast_url', 'creative_type', 'external_action', 'viewability_postbid_partner', 'identity_id', 'avatar_icon_web_uri', 'viewability_vast_url', 'product_ids', 'brand_safety_postbid_partner', 'identity_type' were unexpected)
columns.txt:./source-tiktok-marketing.txt-258-The ad_groups stream has the following schema errors:
columns.txt:./source-tiktok-marketing.txt:259:Additional properties are not allowed ('keywords', 'enable_search_result', 'display_mode', 'conversion_id', 'category', 'feed_type', 'scheduled_budget', 'automated_targeting', 'app_type', 'campaign_name', 'is_share_disable', 'ios14_quota_type', 'bid_display_mode', 'daily_retention_ratio', 'schedule_infos' were unexpected)
columns.txt:./source-tiktok-marketing.txt-481-The campaigns stream has the following schema errors:
columns.txt:./source-tiktok-marketing.txt:482:Additional properties are not allowed ('roas_bid', 'is_smart_performance_campaign' were unexpected)

```

1. Add the missing properties indicated by the `Additional properties are not allowed ('<column>', 'column' were unexpected)` logs to the connector's spec.
2. Remove `fail_on_extra_columns: false` from the `acceptance-test-config.yml` file.
3. Commit changes to spec and `acceptance-test-config.yml` and open a PR.
4. Run tests on the connector, either automatically via CI or manually via the `/test` command
5. Profit!

Definition of done: TikTok Marketing passes CAT without declaring `fail_on_extra_columns: false`. If the
API starts sending over extra columns in the future, we will catch and fix them as part of the #connector-health
movement.

**Comment by evantahler** [comment]
When this issue is picked up, please also consult our [DataDog Dashboard](https://app.datadoghq.com/dashboard/hq4-ush-fht/connector-problems) for `Record Unexpected Fields` for this connector.  The API might be returning even more record properties that need to be added to the catalog.

**Comment by grubberr** [comment]
The latest 

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-tiktok-marketing/acceptance-test-config.yml

already works without `fail_on_extra_columns: false`

But TikTok schema recently  significantly changed 
I think DataDog will catch some new fields 
We need to gather statistics a little bit

**Comment by erohmensing** [comment]
Nice! In this case maybe I'd maybe just push this one to the bottom of the pile and check datadog when that comes around - if there are no new fields in addition by then, can close the issue

**Comment by davydov-d** [comment]
Solved in https://github.com/airbytehq/airbyte/pull/24630
