### ISSUE TITLE
Destinations: Not all available connectors are shown in UI

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#24517]
## Current Behavior
Missing connectors within the `settings/destination` and `destination/new-destination` webpage

## Expected Behavior
Should show the entire list of available connectors that can be created within Airbyte Cloud

Example `Rockset`

## Steps to Reproduce

![Screen Shot 2023-03-24 at 10 45 48](https://user-images.githubusercontent.com/108309971/227601555-41d0b272-c1ed-4a83-8177-50afb3f0add8.png)

![Screen Shot 2023-03-24 at 10 46 17](https://user-images.githubusercontent.com/108309971/227601587-18895464-c344-45c6-8fae-ac480506fe3f.png)

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by evantahler** [comment]
@ryankfu can you share more about this list?  It's in the OSS platform I take it... what version are you running on?  When did you last pull `master`?   Are you having any errors with `airbyte-bootloader` (that's where the list of actors gets loaded into the DB).  

OSS Doesn't pull a new list of connectors until a platform upgrade.  Cloud pulls new connectors all the time.  It's confusing

**Comment by girarda** [comment]
Closing because I can't reproduce. This is an old issue so the bug might have been fixed since. Feel free to re-open if this is still a problem.
