### ISSUE TITLE
Docs: Error in the File Source doc

### ISSUE THREAD

**Issue by Amruta-Ranade** [airbytehq/airbyte#24521]
[From Slack]:

We provide the example of:
{ "sep" : "\t", "header" : 0, "names": "column1, column2"}
But it should be:
{ "sep" : "\t", "header" : 0, "names": ["column1", "column2"]}

**Comment by tyagi-data-wizard** [comment]
Hey @Amruta-Ranade ,
I have started working on it, could you please assign it to me

**Comment by tyagi-data-wizard** [comment]
Hi @Amruta-Ranade ,
Created a [PR](https://github.com/airbytehq/airbyte/pull/24525) for fixing this. 
Please review this and let me know it any thing else is needed.
