### ISSUE TITLE
Failed syncs endlessly loop in 0.17.0-alpha

### ISSUE THREAD

**Issue by Moofasax** [airbytehq/airbyte#2452]
## Expected Behavior
Should stop trying to sync if the sync fails at least 3 times like in previous versions

## Current Behavior
Failed syncs keep happening and never stop

## Steps to Reproduce
1. pull 0.17.0-alpha and launch a sync with a known failure

## Severity of the bug for you
Medium

## Airbyte Version
0.17.0-alpha

## Connector Version (if applicable)
GitHub | airbyte/source-github-singer | 0.2.0

**Comment by sherifnada** [comment]
@Moofasax thanks for reporting, we'll take a look!

**Comment by cgardens** [comment]
@Moofasax i think i got to the bottom of this. I will be merging a [fix](https://github.com/airbytehq/airbyte/pull/2502) shortly and will make sure we do a patch release to get it in the stable version.
