### ISSUE TITLE
Github source fails to sync when you check teams and issue_events in the schema

### ISSUE THREAD

**Issue by Moofasax** [airbytehq/airbyte#2453]
## Expected Behavior
Expect a successful sync from source: Github and destination: Postgres

## Current Behavior
If you leave "teams" and "issue_events" checked in the schema when setting up this integration, the sync will fail.

Github sync will work if you remove "teams" and "issue_events" from the schema.

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. Create source github
1. Create destination Postgres
1. Leave "teams" and "issue_events" checked in the schema

## Severity of the bug for you
Critical

## Airbyte Version
0.17.0-alpha

## Connector Version (if applicable)
GitHub | airbyte/source-github-singer | 0.2.0

**Comment by sherifnada** [comment]
@Moofasax thanks for reporting the issue. Could you help us with debugging by providing the log from the failing sync job? you can find it by going to the sources page, clicking on the github source, then on postgres, then find the failing sync job and click the "download logs" button on the top right of the logs console. 

We already have #2365 for the Teams stream in the case that the repo being replicated is not an organization. But the issue_events one is new, so having logs would help us debug.

**Comment by Moofasax** [comment]
[logs-51-0.txt](https://github.com/airbytehq/airbyte/files/6144620/logs-51-0.txt)
![Screen Shot 2021-03-15 at 5 23 00 PM](https://user-images.githubusercontent.com/25934977/111223340-62e8db80-85b3-11eb-8cc2-8aee818d1cb5.png)


Attached are the logs, the sync never stops failing as well, so hope i let it run long enough for you to get the logs (see this issue as well: https://github.com/airbytehq/airbyte/issues/2452

**Comment by sherifnada** [comment]
@Moofasax the issue with `issue_labels` has been fixed and should be released on version `0.17.2-alpha` very soon (tomorrow or Wednesday). The fix for the issue with teams is currently WIP in #2472 and will likely be released by EOW .

**Comment by Moofasax** [comment]
Oh nice man, by issue_labels do you mean issue_events? Just checking! And thanks man!

**Comment by sherifnada** [comment]
@Moofasax yup I meant issue_events, mb

**Comment by sherifnada** [comment]
Also, version 0.17.2-alpha containing the bugfix has been released. To upgrade Airbyte: 

1. pull the latest version of the github repository using `git pull`
2. From the repo root, run `docker-compose down` to turn off the running instance of Airbyte
3. Run `docker-compose up` to turn it on. You should see that some the newest Airbyte images are being downloaded

Once the server is running you should be good to go.

**Comment by vitaliizazmic** [comment]
@Moofasax 

We just merged this bugfix and into master a released a new version of the connector. 

Upgrade your connector to version 0.2.1 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
