### ISSUE TITLE
Source Notion: Add undeclared columns to spec

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#24560]
## What
In this [PR](https://github.com/airbytehq/airbyte/pull/23985), `BasicReadTest.test_read` test in the Connector Acceptance Tests was updated to fail if the connector produces
stream records which contain columns that haven't been declared in the spec.

Notion currently fails the updated test. Its `acceptance-test-config.yml` was edited with the
`fail_on_extra_columns: false` parameter in [this PR](https://github.com/airbytehq/airbyte/pull/24552) in order to avoid this change from making the connector fail CAT.

We want to add the undeclared columns to the spec.

**How this will help**:
- Column selection is currently blocked for connectors that don't declare all columns that they pass. This
  is because turning on column selection will stop these undeclared columns from being sent, when they were
  previously being sent. Doing this allows us to enable column selection for Notion!
- Users will better understand the shape of the data they'll receive, since the columns will match the spec.

## How
The following descriptions of streams that pass undeclared columns come from results of the failed connector acceptance test:

```
columns.txt:./source-notion-2177-2023-03-26T03:19:20.8276807Z The databases stream has the following schema errors:
columns.txt:./source-notion:2178:2023-03-26T03:19:20.8277731Z Additional properties are not allowed ('description' was unexpected)
columns.txt:./source-notion-2837-2023-03-26T03:19:20.8691049Z The pages stream has the following schema errors:
columns.txt:./source-notion:2838:2023-03-26T03:19:20.8691667Z Additional properties are not allowed ('created_by', 'icon', 'last_edited_by' were unexpected)
columns.txt:./source-notion-3266-2023-03-26T03:19:20.8930751Z The blocks stream has the following schema errors:
columns.txt:./source-notion:3267:2023-03-26T03:19:20.8931130Z Additional properties are not allowed ('last_edited_by', 'created_by', 'parent' were unexpected)
columns.txt:./source-notion-4751-2023-03-26T03:21:51.4323870Z The databases stream has the following schema errors:
columns.txt:./source-notion:4752:2023-03-26T03:21:51.4324908Z Additional properties are not allowed ('description' was unexpected)
columns.txt:./source-notion-5411-2023-03-26T03:21:51.4785392Z The pages stream has the following schema errors:
columns.txt:./source-notion:5412:2023-03-26T03:21:51.4786103Z Additional properties are not allowed ('icon', 'last_edited_by', 'created_by' were unexpected)
columns.txt:./source-notion-5840-2023-03-26T03:21:51.5055136Z The blocks stream has the following schema errors:
columns.txt:./source-notion:5841:2023-03-26T03:21:51.5055513Z Additional properties are not allowed ('last_edited_by', 'created_by', 'parent' were unexpected)
columns.txt:./source-notion-7324-2023-03-26T03:24:06.3162835Z The databases stream has the following schema errors:
columns.txt:./source-notion:7325:2023-03-26T03:24:06.3163809Z Additional properties are not allowed ('description' was unexpected)
columns.txt:./source-notion-7984-2023-03-26T03:24:06.3623606Z The pages stream has the following schema errors:
columns.txt:./source-notion:7985:2023-03-26T03:24:06.3624201Z Additional properties are not allowed ('last_edited_by', 'created_by', 'icon' were unexpected)
columns.txt:./source-notion-8413-2023-03-26T03:24:06.3873864Z The blocks stream has the following schema errors:
columns.txt:./source-notion:8414:2023-03-26T03:24:06.3874238Z Additional properties are not allowed ('last_edited_by', 'created_by', 'parent' were unexpected)

```

1. Add the missing properties indicated by the `Additional properties are not allowed ('<column>', 'column' were unexpected)` logs to the connector's spec.
2. Remove `fail_on_extra_columns: false` from the `acceptance-test-config.yml` file.
3. Commit changes to spec and `acceptance-test-config.yml` and open a PR.
4. Run tests on the connector, either automatically via CI or manually via the `/test` command
5. Profit!

Definition of done: Notion passes CAT without declaring `fail_on_extra_columns: false`. If the
API starts sending over extra columns in the future, we will catch and fix them as part of the #connector-health
movement.

**Comment by evantahler** [comment]
When this issue is picked up, please also consult our [DataDog Dashboard](https://app.datadoghq.com/dashboard/hq4-ush-fht/connector-problems) for `Record Unexpected Fields` for this connector.  The API might be returning even more record properties that need to be added to the catalog.

**Comment by ChristoGrab** [comment]
Should be resolved by [this PR](https://github.com/airbytehq/airbyte/pull/30587).
