### ISSUE TITLE
When i use bitbucket repository for custom transformation it gives me error

### ISSUE THREAD

**Issue by jeevanjoyappa** [airbytehq/airbyte#24568]
Hi,

When i use bitbucket repository for custom transformation it gives me error. When i check below offical document it mentions only GitHub/GitLba/Azuredevops.Does that mean bitbucket is not supported?

https://user:token@bitbucket.org/abcd/abcd.git

https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-airbyte

Please let me know your inputs on the same.

Thanks,
Jeevan

**Comment by timroes** [comment]
Given that custom dbt transformations in Airbyte are now deprecated (https://github.com/airbytehq/airbyte/discussions/34860) I'll close this as not planned to be worked on anymore.
