### ISSUE TITLE
Use manifest schema descriptions and examples in the builder UI

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24574]
Depends on https://github.com/airbytehq/airbyte/issues/23837 - load the descriptions and examples of individual components in the UI for tooltips and labels where-ever possible.

This includes bundling the schema as part of the webapp (right now only derived types are used during the build phase) and providing a helper function to easily load description, title and examples in the react components in the appropriate places. Ideally trying to load description/title/examples from a non-existing component (e.g. due to changes in the manifest) is causing a Typescript error.

## Acceptance criteria

* In all possible places, field label and tooltip are sourced from the schema title, description and example fields

**Comment by girarda** [comment]
additional acceptance criteria:
- [ ] Render examples of type object [example](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml#L1108-L1114)
