### ISSUE TITLE
Convert Callout to Message

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24572]
The Callout component is deprecated and should be migrated to Message. The following instances remain:
* [x] InlineEnrollmentCallout
* [x] LargeEnrollmentCallout
* [x] EnrollmentModalContent
* [x] EmailVerificationHint
* [x] LowCreditBalanceHint
* [x] StreamStatusPage/ErrorCallout

**Comment by flash1293** [comment]
FYI @josephkmh

**Comment by flash1293** [comment]
@josephkmh are you working on this or did you put it in progress because you expect me to take care of that? Fine both ways, just making sure

**Comment by josephkmh** [comment]
@flash1293 in progress because I thought you were working on it. I'll make sure to assign any tickets I'm working on to myself to make that clear!
