### ISSUE TITLE
Source PostgreSQL: data sync takes 32h in the discovery/initialization phase, before actually starting to replicate data

### ISSUE THREAD

**Issue by YohanGrember** [airbytehq/airbyte#24597]
## Environment
- **Airbyte version**:  v0.42.0
- **OS Version / Instance**: ?
- **Deployment**: Google Kubernetes Engine
- **Source Connector and version**: Postgres 2.0.6
- **Destination Connector and version**: BigQuery 1.2.17
- **Step where error happened**: Sync job

## Current Behavior
Hello Airbyte community!
My PostgreSQL data sync takes 32h in the discovery/initialization phase, before actually starting to replicate data

## Expected Behavior
I would expect the initialization of the job to take no more than a few minutes, and then the actual replication to start

## Logs
You can see the sync starts at 2023-03-25 23:00:00 and the replication doesn't start before 2023-03-27 07:47:44
[4d4a12d1_4adc_4e96_b384_90eb8238fd18_logs_15676_txt (1).txt](https://github.com/airbytehq/airbyte/files/11080950/4d4a12d1_4adc_4e96_b384_90eb8238fd18_logs_15676_txt.1.txt)

I tried to fix the issue by upgrading to 2.0.12, unfortunately this did not work - here are the logs
[4d4a12d1_4adc_4e96_b384_90eb8238fd18_logs_15981_txt.txt](https://github.com/airbytehq/airbyte/files/11087640/4d4a12d1_4adc_4e96_b384_90eb8238fd18_logs_15981_txt.txt)

## Steps to Reproduce
1. Launch a PostgreSQL sync on my data source

## Are you willing to submit a PR?
Willing to help, but this problem currently goes beyond my understanding

**Comment by rodireich** [comment]
If this is still relevant, try adding more memory to your pod / container - looks like it's running out of memory.
