### ISSUE TITLE
Improve jobs usage around stream status contexts

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#24601]
The `StreamStatusPage` and `ConnectionJobHistoryPage` both load jobs and then pass them to the `ConnectionSyncContextProvider`. Additionally the `StreamStatusPage` also passes the jobs to the `StreamsListContextProvider`.
We should consider a higher level context to consolidate these things. Potentially consider moving them even higher to the `ConnectionEditContext` though that means jobs will continually be loaded on pages that don't need it, but sharing the data would be useful for the UX.

**Comment by chandlerprall** [comment]
This is now done.
