### ISSUE TITLE
MySQL table extract to S3 Issue with MonthOfYear equal to 0 (Zero)

### ISSUE THREAD

**Issue by cnx-lucaspassos** [airbytehq/airbyte#24603]
Hi guys, I`m having issues to migrate data from mysql to s3. We got an error everytime we try to export a specific table in our database.

## Environment
- **Airbyte version**:  0.40.31
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: MySQL (2.0.10)
- **Destination Connector and version**: S3
- **Step where error happened**: Sync Job

## Current Behavior
During the sync with a specific table we got the following error:  Additional Failure Information: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0

We are using the standard MySQL model. I have tried to use it in Full Overwrite and Incremental model. Both of them fails. 
I also have tried to change the destination format (json and parquet)

## Expected Behavior
It should Sync the data - like any other table in the same database.

## Logs
Attached the Sync Logs
2023-03-27 18:47:43 - Additional Failure Information: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0

## Steps to Reproduce
1. Configure Source (MySQL)
2. Configura Destination (S3)
3. Sync Job

## Are you willing to submit a PR? No
[659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_388_txt.txt](https://github.com/airbytehq/airbyte/files/11082169/659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_388_txt.txt)

**Comment by cnx-lucaspassos** [comment]
Hi @prateekmukhedkar, thanks. I just have checked. There's an specific column with a wrong datetime (using invalid 00 month). For any reason, someone disabled the mysql constraint check and allowed this value. The only thing that scares me is that this column is not a pointer. It's a birth date. Thanks again for your support. I`m closing the issue

**Comment by prateekmukhedkar** [comment]
Sounds good @cnx-lucaspassos . Could you also update here if you were able to sync successfully after fixing the wrong datetime value?

**Comment by cnx-lucaspassos** [comment]
Yes, were able to sync the data after fixing the datetime. Thanks

**Comment by prateekmukhedkar** [comment]
Thanks for your reply.
