### ISSUE TITLE
destination-postgres normalization intermittently taking 2-3 hours to complete

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#24613]
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: cloud
- **Source Connector and version**: facebook-marketing 0.3.0 
- **Destination Connector and version**: postgres-0.3.26 
- **Step where error happened**: Sync job

## Current Behavior
On the following [connection](https://cloud.airbyte.com/workspaces/4a89021d-49eb-4330-8cec-80d5939a9231/connections/24724a54-29fb-498f-9664-c5174d7a6104/status) it sometimes take normalization 2-3 to complete, causing in some instances platform to time out and shut sync down.
```
2023-03-14 04:55:26 �[42mnormalization�[0m > 37 of 696 OK created incremental model airbyte.facebook_us_ads_insights_region_scd...................................... [�[32mINSERT 0 16221�[0m in 7719.15s]
```
What I see in logs is that a single table `ads_insights_region_scd` hold normalization for 2-3 hours intermittently.
But on other syncs it only take a few seconds. doesn't seem to correspond with the number of records synced for that table.

## Expected Behavior
Sync including normalization should complete in a timely manner.

## Logs
refer to https://github.com/airbytehq/alpha-beta-issues/issues/1120.

**Comment by erry-takumi** [comment]
We have the same issue. Sometimes resetting the whole build from scratch (which deletes all the data and runs a fresh run from scratch) fixes it for a few weeks/months, but that isn't really a good solution.
