### ISSUE TITLE
Source MSSQL: Support date during data type mapping with MSSQL

### ISSUE THREAD

**Issue by TobiasLaving** [airbytehq/airbyte#24637]
## Tell us about the problem you're trying to solve
We are currently using airbyte to copy data from a azure mssql database to google bigquery. This is working very well!
We recently saw that the date columns are translated as strings, something we overlooked in the documentation. This makes working the the data in bigquery needlessly cumbersome.

## Describe the solution you’d like
Supporting datetime as mapping would be great. Recommended ways of working with strings are also welcome, for example, perhaps we could setup a custom transformation instead?

## Describe the alternative you’ve considered or used
None

## Additional context
N/A

## Are you willing to submit a PR?
Sure thing, if someone could guide me to where I should start looking I'd love to contribute.

**Comment by nguyenaiden** [comment]
@igrankova We've addressed this issue with `source-mssql:3.0.0` or later. Please reach out and reopen the ticket if the problem still persists.
