### ISSUE TITLE
Implement field projection

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2464]
## Tell us about the problem you're trying to solve
Users currently cannot select which fields (columns) they want to sync from their streams -- if you pick a stream, it's all or nothing. However, users want the ability to project which fields they want. A simple use case is sensitive data like described in #2463 . We can do this at the Airbyte level without having to do it separately for every connector by filtering the incoming records to contain only the selected fields in the catalog. 

Sources can still implement projection as needed (e.g: a DB source will still want to `select` only the relevant columns for efficiency reasons), but this can be implemented "for free" outside the connectors. 

## Describe the alternative you’ve considered or used
Projection at the destination level

**Comment by ChristopheDuong** [comment]
same as https://github.com/airbytehq/airbyte/issues/2227 ?

**Comment by sherifnada** [comment]
@ChristopheDuong yes, I'll copy the context into the original ticket and close this one.
