### ISSUE TITLE
Source Younium: Accounts and Bookings streams are needed

### ISSUE THREAD

**Issue by hhagblom** [airbytehq/airbyte#24654]
## Tell us about the problem you're trying to solve
There are two streams that we need to get from the Younium connector that currently has no support. These are Accounts and Bookings.

## Describe the solution you’d like
The solution is to add these two streams with their schemas to the younium source connector.

## Are you willing to submit a PR?
I am about to submit an PR for this issue.

**Comment by btkcodedev** [comment]
@jrolom I would like to work on this issue

**Comment by btkcodedev** [comment]
Unassigning this in favor of https://github.com/airbytehq/airbyte/pull/30258#issuecomment-1736198460
Thanks :)

**Comment by sajarin** [comment]
Solved by #31064
