### ISSUE TITLE
Provide direction to users in the setup of new sources and destinations

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#24678]
Today, once a user sets up a source or destination, they land on an empty page with an image of Octavia looking to the top right to connect the source to a destination (or destination to a source).

A user will then have to click on the button to see a dropdown of the existing sources/destinations if any exist. 

The empty state page with Octavia should be removed - and replaced with a more clear directive to connect the Source or Destination to the other in order to create a connection. We should also display the existing sources/destinations outside of a dropdown.

The lack of guidance during setup means users end up with a source or destination but not a connection. The concept of a connection is new for users coming from other tools that only have a concept of sources and destinations. 

Design: https://www.figma.com/proto/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?page-id=1%3A4&node-id=1232-38639&viewport=2638%2C246%2C0.13&scaling=min-zoom&starting-point-node-id=1232%3A38639

EDIT: Updated designs https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?type=design&node-id=2452-90807
EDIT: Updated Designs

**Comment by tealjulia** [comment]
@nataliekwong it looks like in the prototype, there is no separate empty state, the page simply shows the "select a destination" step instead.  Is that correct?
(https://www.figma.com/proto/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?node-id=1367-36938&scaling=min-zoom&page-id=1%3A4&starting-point-node-id=1232%3A38639)

**Comment by nataliekwong** [comment]
Yeah. The empty state pages go away and you'll be directed to set up a destination since we need the other part to set up a connection. 

It removes them needing to click to the dropdown and select existing/create new, but is more aggressive in pushing them into a flow. 

We could explain this more clearly in the header with text, like "To start syncing data with {{source}}, you'll need to connect it to a destination. Choose from an existing destination or set up a new one"

**Comment by josephkmh** [comment]
Refining notes:
- Not clear whether redirecting the user to the connection flow would be good UX, will open a thread in the project channel

**Comment by josephkmh** [comment]
Refining notes round 2:
- We will implement the new "Empty screens" designed here: https://www.figma.com/file/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?type=design&node-id=2452-90807&t=usnstCPgyoQG63X0-0
