### ISSUE TITLE
Support incremental syncs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#247]
## Tell us about the problem you're trying to solve
Dataline currently only supports dumping the entire data source into the destination. I want to only sync the data that has changed since the last sync, not dump the entire dataset every time. 

## Describe the solution you’d like
When configuring a connection from the UI, I'd like to be able to configure it to be incremental instead of full refresh.

**Comment by cgardens** [comment]
We have launched this feature.
