### ISSUE TITLE
low-code: Access partition router's values using stream_partition variable 

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#24723]
We're trying to remove the concept of stream_slice from the connector builder.

The last reference to stream_slice is the variable used in jinja macros to access the partition router and incremental_sync values.

**Comment by flash1293** [comment]
This is already renamed in the UI, the only part that's left is renaming the `stream_slice` object in the YAML to something else (maybe `stream_partition`?)

Problem: `stream_slice` is also used for the incremental sync slices (maybe that should have a separate object? or is it fine to keep that on `stream_partition` as well?)

**Comment by flash1293** [comment]
Grooming notes:
* Splitting it up is a lot of effort
* Having `stream_partition` as an alias to `stream_slice` can easily be added

**Comment by girarda** [comment]
@flash1293 just as a heads up - I renamed the issue and changed the description to better match what we groomed on Tuesday - rename the `stream_slice` jinja variable.

The original issue was about renaming a field in the schema. I created a new issue since that's different: https://github.com/airbytehq/airbyte/issues/25375
