### ISSUE TITLE
Cannot test a stream if another stream is invalid

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#24725]
## What
The test button switches to stream with an error even if the currently selected stream doesn’t have an error

## Acceptance Criteria
- A stream with no errors can be tested even if other streams have errors.
- Errors in global configuration will still prevent testing of any stream

**Comment by lmossman** [comment]
Grooming notes:
- When sending manifest for test read, build it to only include the stream being tested
- Refactor hasErrors hook to only check the selected stream
