### ISSUE TITLE
Source Google Analytics 4 (GA4): Add the ability to select multiple property id when setting up a GA4 connector

### ISSUE THREAD

**Issue by ahvozdov** [airbytehq/airbyte#24739]
## Tell us about the problem you're trying to solve
To get all the data about all our sites, I need to add 100+ GA4 property IDs, which means at this point I need to create 100+ threads with similar queries.

## Describe the solution you’d like
Allow the GA4 connector to accept and process my property identifiers in comma or other format (json, array, etc.) when configured.

## Describe the alternative you’ve considered or used
Creating 100+ threads with the same query parameters.

## Are you willing to submit a PR?
Yes, but as soon as we have votes for this work to prioritize.

**Comment by Riya-gupta-8** [comment]
I have also integrated 350+ google analytics4 customers creating single single connection.Is it possible to get the data of the multiple property ids together through a single connection?
