### ISSUE TITLE
Show connector builder promo in connector grid selection

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24747]
The connector type dropdown features a promo for the connector builder:

![Screenshot 2023-03-31 at 16.16.53.png](https://images.zenhubusercontent.com/6388e4bf14ef75774e60c581/82f77d55-b115-4b45-a14e-9973968f1968)

However it's not shown in the new connector selector grid: ![Screenshot 2023-03-31 at 16.16.14.png](https://images.zenhubusercontent.com/6388e4bf14ef75774e60c581/0f40b943-97be-4928-a397-1a84d71fc385)

To make users aware of the new functionality, a tile with the same content should be added to the grid:![Screenshot 2023-03-31 at 16.18.09.png](https://images.zenhubusercontent.com/6388e4bf14ef75774e60c581/496e67cc-8070-4932-b7c9-b06f85093528)

**Comment by flash1293** [comment]
Nico will provide design

**Comment by Upmitt** [comment]
https://www.figma.com/proto/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?page-id=1%3A4&node-id=1367-35445&viewport=11067%2C480%2C0.5&scaling=min-zoom&starting-point-node-id=1232%3A38639&show-proto-sidebar=1

**Comment by flash1293** [comment]
Grooming notes:
* Keep the existing wording
