### ISSUE TITLE
Configure Airbyte through a declarative DSL 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2474]
## Tell us about the problem you're trying to solve
In line with DataOps best practices, I would like to configure Airbyte through a declarative DSL that can be version controlled and reviewed by my team. 

## Describe the solution you’d like
Roughly speaking we probably have two avenues: 

1. Create our own DSL from scratch
1. Piggyback on an existing tool like Terraform Provider

We should explore which of these makes sense to do and decide on a path forward.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368093555340) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
some related information in https://github.com/airbytehq/airbyte/issues/1860

**Comment by jreslock** [comment]
I am throwing my vote in here for option 2 mentioned above.

As an operator/administrator I need a way to reliably tear down and spin up Airbyte.  

A terraform provider that wraps the existing API would be extremely valuable for operators responsible for managing Airbyte installations.

For example, we use RDS and Snowflake and already manage both of these via terraform.  If there were an Airbyte provider for terraform we could very easily wire outputs from the RDS or Snowflake modules to inputs for Airbyte sources and destinations.  

The existing export/import of configuration is a good start but it still requires initial manual setup of sources and destinations via the UI after spinning up an Airbyte instance the first time.  Subsequent iterations can then import configuration that was previously exported.

I can see that there are already API's for source and destination configurations.  Wrap those API's with a terraform provider and the entire Airbyte system can be managed via code.

**Comment by davidoh9** [comment]
We would love having this as well

**Comment by thetimbecker** [comment]
We are currently evaluating Airbyte and I am hesitant to use it without this.

In addition to the more obvious benefits of configuration as code, it is a lot easier to document **_why_** things are configured the way that they are. With Git history, code comments, and other things, you can see why choices were made and which are important.

We have other tools that haven't been configured with code, and it's hard to tell what is actually needed and what is just leftover from experimentation.

**Comment by awilliamsOM1** [comment]
I generated a go client for the airbyte api using the openapi generator. Hopefully it will make creating a terraform provider much easier. https://github.com/awill1/airbyte-client-go

**Comment by sherifnada** [comment]
@alafanechere should this be closed since we have released the Octavia CLI?
