### ISSUE TITLE
Source Postgres: does not add nullable property to catalog

### ISSUE THREAD

**Issue by Steffen911** [airbytehq/airbyte#24743]
## Environment
- **Deployment**: Docker
- **Source Connector and version**: source-postgres:2.0.8
- **Step where error happened**: Discover schema

## Current Behavior

I run the source-postgres connector with the `discover` command against a postgres database. It detects the columns and types correctly, but gives no indication if a field is nullable. 
It returns a field like
```json
{
  "streams": [
    {
      "name": "rna",
      "json_schema": {
        "type": "object",
        "properties": {
          "seq_long": {
            "type": "string"
          }
        }
      }
    }
  ]
}
```

## Expected Behavior

Given that the column is nullable I would expect 
```json
{
  "streams": [
    {
      "name": "rna",
      "json_schema": {
        "type": "object",
        "properties": {
          "seq_long": {
            "type": ["string", "null"]
          }
        }
      }
    }
  ]
}
```

## Steps to Reproduce

I'm using a public postgres database from https://rnacentral.org/help/public-database as an example.

1. Create config as 
```json
{
  "host": "hh-pgsql-public.ebi.ac.uk",
  "port": 5432,
  "database": "pfmegrnargs",
  "username": "reader",
  "password": "NWDMCE5xdipIjRrp"
}
```
2. Run discovery via `docker run -v ./config.json:/tmp/config.json airbyte/source-postgres:2.0.8 discover --config /tmp/config.json`
3. Observe the output for `rnacen.rna`. `seq_long` among others should be marked as nullable.

**Comment by Steffen911** [comment]
Probably related to https://github.com/airbytehq/airbyte/issues/24987. If everything _can_ be null that could also be documented centrally. In the current state I would still expect explicit `null`  types in the catalog.

**Comment by prateekmukhedkar** [comment]
Notes from team grooming meeting - Implementation wise this change is not big but as this is a catalog change, we will need to check for rollback. This adds the effort to roll out.

**Comment by evantahler** [comment]
There has been no progress on this issue for over a year.  Closing.
