### ISSUE TITLE
Destination Postgres: S3 to Aurora PostgreSQL (nested JSON data)

### ISSUE THREAD

**Issue by professorshabs** [airbytehq/airbyte#24749]
- **Destination Connector and version**:  Aurora PostgreSQL 
- ** If I put unexpected behaviour as `initialised stream with format: {'filetype': 'jsonl', 'block_size': 0, 'newlines_in_values': False, 'unexpected_field_behavior': 'error'}` or infer it fails but when I use ignore it loads with object/dict fields being all nulls.

## Current Behavior
*If I put unexpected behaviour as `initialised stream with format: {'filetype': 'jsonl', 'block_size': 0, 'newlines_in_values': False, 'unexpected_field_behavior': 'error'}` or `infer` it fails but when I use `ignore` it loads but all object/dict fields are nulls..

I thought I can solve this by defining a JSON nested schema with properties. For example: 
`"DevelopmentEnquiry":{"type":"object","properties":{"DevelopmentId":{"type":"integer"},"ToAccountHolderId":{"type":"integer"}}}` 
but I get an error that says: `ConfigurationError('Invalid schema provided, all column names and datatypes must be in string format')`*

## Expected Behavior
*I need to ensure that nested data does not come as nulls when synced to the destination (PostgreSQL).*

## Steps to Reproduce
1. logs:
[cc7b23f9_2b0f_43f9_861b_103c3b0932f9_logs_172_txt.txt](https://github.com/airbytehq/airbyte/files/11123775/cc7b23f9_2b0f_43f9_861b_103c3b0932f9_logs_172_txt.txt)

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
