### ISSUE TITLE
Decoupling Platform Acceptance Tests

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#24755]
Tests are long
Tests are flaky

Solution: 
* Decouple these tests so that they can be run independently
* Trigger those decoupled tests only when a change requires it

In the end, acceptance tests other than connector-builder should not be executed if changes are scoped to the connector builder

**Comment by girarda** [comment]
closing the epic because it's not actively being worked on. feel free to re-open if you think this should be prioritized
