### ISSUE TITLE
track API calls made to the UI from the API vs calls made directly

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2476]
## Tell us about the problem you're trying to solve
We don't have a good idea of how many users are using our API vs our UI for different tasks, like for configuring sources.

## Describe the solution you’d like
It'd be great if we could track queries by API call and record the user agent. This would also allow us to see how common different endpoints are used so we can make decisions on how to approach API changes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368095558236) by [Unito](https://www.unito.io)

**Comment by evantahler** [comment]
Closing this for now, as we have this information from our load balancer for Airbyte Cloud users
