### ISSUE TITLE
Frequency shouldn't be the time between the end of a sync and the beginning of the next one, but the time between the beginning of both

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2478]
## Expected Behavior
If I set hourly as a frequency and it starts at 1.06pm, I expect it to stay X.06 on the hour. 

## Current Behavior
Right now, if it takes 2 min to sync, the next one will start 2.08pm, and then 3.10pm, etc. 

## Severity of the bug for you
Low

See screenshot
<img width="821" alt="Screen Shot 2021-03-16 at 2 14 36 PM" src="https://user-images.githubusercontent.com/68561602/111252651-b6b3fd00-8665-11eb-928f-cf185fbc0573.png">

**Comment by cgardens** [comment]
ok! I'd like to add one caveat here, which is we should not schedule the next job until the previous one is finished.

For example, let's say it is scheduled to run every 5 minutes, but one of the sync job takes 6 minutes. I would suggest that we do not schedule the next job until the previous job has completed. It can be scheduled immediately after the previous job has completed.

Example for clarity... scheduled for every 5 minutes
3:00: job 1, completes in 1 min.
3:05: job 2, completes in 1 min.
3:10: job 3, completes in 6 minutes.
3:15: nothing happens! job 3 is still running.
3:16: job4, completes in 1 min.
3:21: job5, completes in 1 min.
etc...

**Comment by johnlafleur** [comment]
Completely agree!

**Comment by jrhizor** [comment]
related to https://github.com/airbytehq/airbyte/issues/1965
