### ISSUE TITLE
Source Hubspot: No data retrieved for marketing emails

### ISSUE THREAD

**Issue by Houssem1Ab** [airbytehq/airbyte#24783]
On every Sync i got "Sync Succeeded
0 Bytes no records no records 28s" unless i have more than 8000 rows in hubspot !! 
Any help ?

**Comment by aballiet** [comment]
`marketing_emails` stream is working fine for me, can you describe your issue ?

**Comment by arsenlosenko** [comment]
@Houssem1Ab Hi, can you please clarify what version of Source Hubspot did you use, and what destination you are using to store these records? This is needed to get a better picture of this issue, so it could be reproduced, and see what may cause this. Thanks!

**Comment by davydov-d** [comment]
@Houssem1Ab is this still an issue for you? could you please provide more details so we could investigate and fix the root cause?
