### ISSUE TITLE
Source MySQL: UTC TIMEZONE ERROR IN MYSQL CONNECTOR CDC

### ISSUE THREAD

**Issue by devkapadia02** [airbytehq/airbyte#24781]
Here's the current error we get from the airbyte logs.
java.sql.SQLException: The server time zone value 'Coordinated Universal Time' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'connectionTimeZone' configuration property) to use a more specific time zone value if you want to utilize time zone support.

after adding UTC IN the CDC timezone "Configured server timezone for the MySQL source (Advanced)Optio"

It is still showing this error 

Please help on this issue

**Comment by prateekmukhedkar** [comment]
@devkapadia02 are you using Airbyte cloud? Can you send me a link to your connection and if possible exception logs?

**Comment by prateekmukhedkar** [comment]
Should be fixed with #24659. @devkapadia02 please try upgrading to latest MySQL connector and re-open the issue if you are still failing the timezone related error.
