### ISSUE TITLE
Source Postgres: detect prepared statement issues

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#24796]
pgbouncer seems to interact weirdly with how source-postgres queries for data, which results in errors like `prepared statement "S_2" already exists`. In these cases, we can add a JDBC parameter `prepareThreshold=0` to disable prepared statements.

* [ ] Understand how this impacts performance (if at all)
* [ ] When source-postgres receives this error, handle it gracefully:
    * automatically reconnect with the `prepareThreshold=0` param?
    * emit a config message to update the config?
    * some other option?

**Comment by prateekmukhedkar** [comment]
1. We need to evaluate impact of this change
2. We will surface this a config error so that our sync success metrics are not impacted. Code change needed to configure this error statement.

**Comment by bleonard** [comment]
It seems that we want to be careful just marking this as a config error. "config error" means "this will not work until the user changes their configuration (on our platform or their infra)"  --- I don't think that's the case here. it's more like a transient network error and should be retried (eitehr through us catching it can trying again or through the platform retry mechanisms and checkpointing).

**Comment by bleonard** [comment]
I think that means. "What's the best way to try again if certain errors occur?" Is that something our JBDC setup makes easy?

**Comment by akashkulk** [comment]
We should hold off on marking as a config error until : 
- We have a detailed understanding of what causes this
- What the effects of disabling this (by the setting `prepareThreshold=0` is). Will recreate this using Rodi's performance harness
- Can add the workaround to the docs as a first step

**Comment by akashkulk** [comment]
Stages of query processing on the DB side:
- Query Parsing
- Query Planning (determining which indexes to use, which scans to perform, etc)
- Query Execution (actually doing the things in the plan)

Benefits of prepared statements
- Client side : Prevent SQL injection and limit allocation of objects
- Server-side : For frequently issued statements, stages 1 and 2 above are cached

Side-effects of setting JDBC param=0
- No server-side caching of query plans. Still have the client side benefits.

What does this mean for Airbyte’s use case? This will not affect us too much as
- We rarely issue the same query again and again
- Even if we do in the future - the bottleneck for our queries is the query execution stage. As an [example](https://www.loom.com/i/b427122f1cd04e5e847eb9552682a03e), for our 300MB data set, about ~0.25% percent of the query processing time is spent in query planning, rest is in execution. This percentage only decreases the larger the size of data we are processing on is.


Recommendation 
- As a stop-gap, setting prepareThreshold=0  in the JDBC param is safe (and might even be faster for our use case). This will prevent these errors in the future
- Separately, the DB sources team will just add this parameter by default in the connectors.

**Comment by prateekmukhedkar** [comment]
@nguyenaiden before closing lets verify if the number of instances of this error have dropped.

**Comment by nguyenaiden** [comment]
I searched on [Sentry](https://airbytehq.sentry.io/issues/?query=message%3A%22%2AERROR%3A+prepared+statement%22+&referrer=issue-list&statsPeriod=90d&utc=true) to see if there has been any errors containing `*Error: prepared statement` and looks like it hasn't happened for 2 months. 
cc: @akashkulk. Let me know if I'm still missing something
