### ISSUE TITLE
Jira source to support oauth instead of just API key

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2479]
## Tell us about the problem you're trying to solve
I am using airbyte in a multi-tenant product and I want to enable auth with Jira with OAuth.

Current implementation uses the API key only.

## Describe the solution you’d like
I can select either API Key or OAuth

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368154201722) by [Unito](https://www.unito.io)

**Comment by lazebnyi** [comment]
Duplicate https://github.com/airbytehq/airbyte/issues/7481
