### ISSUE TITLE
Add versioning, indexed fields to db source connector logging

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#24794]
Currently, we don't have any visibility into:  
- The version of a DB a source connector is running against (e.g. Postgres 9.5.x)
- Current indices on the source schema. 

These would be helpful to debug problems in connectors as some of the bugs are version specific. Knowing what the DB has indexed on would help in debugging slow syncs (e.g. incremental sync with cursor might keep doing full table scans)

**Comment by prateekmukhedkar** [comment]
notes from grooming:
Is there a standard way to get this information? JDBC sources gets ResultMetadata which should have this information. 

Acceptance criteria: Log the version and indexes on source schema.

**Comment by akashkulk** [comment]
Reopening this one. Couple of things here : 
- Currently, we are logging for all configured streams. However, the configured stream can be deleted/out of sync with the actual database. This can happen if the user has not refreshed their catalog in a while. In this case, we should also check if the underlying stream exists in the table.
- A MySQL specific issue. The theory is it might have to do with formatting/escaping MySQL stream name, but haven't had time to investigate :  https://github.com/airbytehq/airbyte/issues/25660


Notes: 
- Disabling logging in MySQL, MsSQL in https://github.com/airbytehq/airbyte/pull/25740
- Issue with access denied crash for MySQL : https://github.com/airbytehq/airbyte/issues/25660
- Another instance of a MySQL crash :  https://github.com/airbytehq/airbyte/pull/25729#issuecomment-1530517374

**Comment by akashkulk** [comment]
Closing
