### ISSUE TITLE
Remove "dot" notification from left sidebar

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#24799]
Update Nov 6 2023:
- Current state: only the red button shows (for any balance under 20 credits)
- We can just remove this notification for all users from the sidebar
- We already are removing this for PbA users on billing in-arrears: https://github.com/airbytehq/airbyte-platform-internal/pull/9687

---
Original issue:
Within this PR, we added a notification that would alert users to go to /billing if they were low (20 credits) or had 0 credits.

It stopped showing up due to this update: https://github.com/airbytehq/airbyte-platform-internal/commit/b735183a0481675b1f07145bb7efc6b0ad2395db

Could we add it back?

cc @tealjulia @josephkmh

**Comment by nataliekwong** [comment]
When the user has <=20 credits, the notification color should be yellow, but is red: 
 
<img width="235" alt="Screenshot 2023-05-08 at 1 51 59 PM" src="https://user-images.githubusercontent.com/38087517/236932394-3740543c-cc9c-4937-99eb-6edacf9026a7.png">

**Comment by nataliekwong** [comment]
I think we can remove this notification in the sidebar if we don't think there are other use cases to utilize this style of notification!

**Comment by chandlerprall** [comment]
Refining notes:

- want design input, does this make sense to keep / with a different design?

**Comment by nataliekwong** [comment]
@nora-airbyte this was one of those issues that got stuck in design-less purgatory the last few months. Not urgent at all, but it came up here: https://github.com/airbytehq/airbyte-platform-internal/pull/9687 where we started removing it for PbA workspaces and I was reminded of this issue.

Curious if you have an opinion here on whether this notification style (the dot) could be altogether removed from the app given it's used sparingly.

**Comment by nora-airbyte** [comment]
I think we can remove this dot. The current "out of credits" banner does a good job of linking the user to the Billing tab. 

Eventually I'd like to centralize all notifications in a notification center, so removing this one-off pattern is a step in the right direction.

**Comment by nataliekwong** [comment]
Sounds good. Sending back to incoming so we can find a better place than Triage for this one.

**Comment by nataliekwong** [comment]
@nora-airbyte Linking some external user feedback on the use of the red dot in OSS: https://github.com/airbytehq/airbyte/issues/19968 (you can see it on demo.airbyte.io as that is the OSS version). It sounds like 

Just confirming - we would remove it for both the /credits (Cloud only) and /settings (OSS and PbA only)?

**Comment by nora-airbyte** [comment]
Yep, just from /credits and /settings for now!

**Comment by tealjulia** [comment]
Refining notes:
- will be completed as part of https://github.com/airbytehq/airbyte-platform-internal/issues/9792
