### ISSUE TITLE
Updates to new connector/existing connector cards in connection workflow

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#24804]
- Existing connections show in a table like their list view
- New connectors uses the grid view
  - The search should use `<input type="search">`
  - A magnifying lens icon should be added to the search input

[Figma](https://www.figma.com/proto/8aM4gBoW95whyshI5kwVct/01_06_SOURCES?page-id=1%3A4&node-id=1363-29149&viewport=2638%2C246%2C0.13&scaling=min-zoom&starting-point-node-id=1232%3A38639)

**Comment by tealjulia** [comment]
@josephkmh this work was split out into two tickets:
[This issue](https://github.com/airbytehq/airbyte/issues/24677) to add the top card with the "create new" and "select existing" radios
and this issue (24804) to add the table/grid components.

I think #24677 should probably come before this one, though it looks like I didn't list it as a dependency.  Just calling that out because I am not entirely sure upon re-reading that the intent was super clear!

I'm not vehemently against the two issues being tackled together, just wanted to try and keep each piece small and easily reviewable.

**Comment by josephkmh** [comment]
Thanks for pointing that out, I was not aware of #24677. Happy to tackle them both, but I can do them separately and start with the other one to keep the PRs small 🙂
