### ISSUE TITLE
Erroneous state associated with unsuccessful initial non-CDC incremental sync

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#24808]
There is currently a bug with the initial full refresh sync while performing a non-CDC incremental sync. 

The logic for emitting intermediate state for incremental syncs currently depends on the fact that the records are returned by the iterator in order. In fact, it's disabled for certain sources (BigQuery and MongoDB) due their inability to order records from an incremental sync by the cursor field. 

In all of our JDBC sources, the way an initial full refresh sync is performed is by a ``select * from table``. Subsequent syncs do order by the cursor field. Crucially, the results are never ordered by the cursor field. As a result, the emitted intermediate and final state is wrong. 

Consider the following table (with a configured intermediate state emission frequency of 1)
| ID(cursor)  | name |
| ------------- | ------------- |
| 5  | Duy  |
| 1  | Subodh  |
| 3  | Akash  |
| 2  | Rodi  |
| 4  | Prateek  |

With the given ``select *`` query, we're not guaranteed to get the results in order. This can be problematic if there is an unsuccessful sync, which can lead to data loss.
e.g. If the source connector processes row 1 and fails, it will have emitted one state which is ``{ cursor_value : 5 (Duy) }``. Subsequent syncs will skip all values with ``cursor_value < 5`` with no path to recovery. This may explain some of the data loss for incr syncs. However, it would only correspond to data in the initial load.  

Some of the reasons we may not be seeing more of these issues is : 
1. Sync completed successfully. 
2. The cursor is indexed and somehow the `select *` query returned everything in order.

The fix here is to : 
1. Order the initial load by cursor field. One potential drawback here is that if the source database is not indexed by cursor field, sorting could take a long time. 
2.  Change the state emitting logic to only return one state at the end for the initial load (which is the max value seen so far). The drawback of this approach is that we won't have any real checkpointing during the initial load - arguably when we need it the most. 

Am inclined to go with option 1

**Comment by bleonard** [comment]
Definitely Option 1!

**Comment by prateekmukhedkar** [comment]
For the drawback of option 1, technically during `discover` we can check if the source database is not indexed by cursor field and surface a warning to user that incremental syncs will be slower. This is not in the scope of this fix but a potential improvement later.
