### ISSUE TITLE
Update favicons to match designs

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#24801]
Icons we should be using can be found in https://drive.google.com/drive/u/0/folders/1KM78PUXt9VIhGK09-jIyG9p6bo67MFJa

Update the favicons in `/public` as well as the accompanying manifest.

**Comment by josephkmh** [comment]
Refining notes:
- If possible, we should content hash these assets in `/public`. If it's non-trivial, we can punt on that

**Comment by josephkmh** [comment]
@dizel852 another one you could jump on if you're looking for a ticket 🙂

**Comment by dizel852** [comment]
🕙 Requested access to https://drive.google.com/drive/u/0/folders/1KM78PUXt9VIhGK09-jIyG9p6bo67MFJa

**Comment by josephkmh** [comment]
@dizel852 shared with you!
