### ISSUE TITLE
Newly generated connector failed with JSONSchema version mismatch

### ISSUE THREAD

**Issue by maver1ck** [airbytehq/airbyte#24829]
## Environment
- **Airbyte version**:  master
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: docker
- **Step where error happened**: Create new connector

## Current Behavior
Newly created Airbyte source based on Singer tap-mambu failed installation

## Expected Behavior
I should be able to generate proper sources based on Singer taps

## Logs
```
INFO: pip is looking at multiple versions of source-mambu-singer to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install source-mambu-singer and tap-mambu because these package versions have conflicting dependencies.

The conflict is caused by:
    airbyte-cdk 0.1.56 depends on jsonschema~=3.2.0
    singer-python 5.8.0 depends on jsonschema==2.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

## Steps to Reproduce
1. Run generate.sh
2. Choose Python Singer Source
3. Use 'tap-mambu'
4. Run ./acceptance-test-docker.sh in newly generated source-mambu-singer directory

**Comment by maver1ck** [comment]
This is probably related:
https://github.com/singer-io/singer-python/pull/161

**Comment by natikgadzhi** [comment]
Unfortunately, we won't actively support singer taps in generators moving forward. You are still welcome to use them, but we'll remove the generator, you'd have to manually add `singer-python` as a dependency.
