### ISSUE TITLE
Schema validation error collection refactor

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#24853]
## Tell us about the problem you're trying to solve
The schema validation code has undergone a lot of changes made on some assumptions, and I find it both confusing and don't think it achieves what we want it to.

## Current solution

Our [current schema validation method](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L103):

1. tries to validate a schema
2. excepts a `JsonValidationException` by not using that exception at all, but rather re-calling the validator in order to access the args that were used to create the single `JsonValidationException.message` containing multiple error messages
3. Uses those args to create our own validation messages, one per `ValidationMessage` in the `JsonSchemaValidator`
4. Throws a `RecordSchemaValidationException` containing the validation messages and the original `JsonValidationException`

We then [handle the exceptions](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L78) by keeping a map of:
`stream (key): (concatenated set of error messages, # of record validatons total that make up the errors in that list)`. We keep this updated so that after we've gotten validaton errors for 10 records of a given stream, we stop running validation on that stream

## Issues
~**By not using the `JsonValidationException` directly and instead re-calling the validator in order to access the args that were used to create the single `JsonValidationException.message`, we are losing information and inserting incorrect information:**~
1. ~[We make the assumption that every error thrown by the validator is about incorrect types](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L115), when that's not the case.~
2. ~This led us to previously assume that every message would come with 2 args,[ `invalidRecordDataAndType`](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L104). The 2 args in the case of type mismatch errors are actually expected type and actual type, not record data and actual type. Not grabbing this info [here](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-commons-worker/src/main/java/io/airbyte/workers/RecordSchemaValidator.java#L110-L111) is where we lose the expected type.~
3. ~Sometimes the `JsonValidationException` does not come with args, for example in the case of when additional properties are not allowed (0 arguments). We currently make extra checks against this, instead of handling different types of errors that the schema validator is trying to send us. We mask these potential errors as "__ is of an incorrect type" errors with no more information (and the type information is incorrect)~

Crossed out the above as it was fixed [here](https://github.com/airbytehq/airbyte-platform-internal/pull/5648) - however one issue i didn't raise before is that we were previously calling validate 3 times to get the info we need, now we only do it twice, but should be able to do it in just one go.

**By limiting ourselves to 10 total validation failures, we lose some info:**
1. We may not be getting all of the type mismatch errors, so if someone fixing types fixes all the reported types, there may be new errors reported once the previous ones are fixed
2. ~Since all validation errors are reported as type errors, 10 type errors could stop us from seeing other completely different types of schema validation errors on further records~

## What are we trying to achieve? From my understanding: 
- We want to collect and report schema validation errors 
    - Ideally all of them, not just type mismatches
- We want to collect the number of records with schema validation errors per stream in order to limit the amount of validating we do 
    - ❓ previously this was due to the amount of logging and performance (I think). Is this solved by moving it to a separate thread?
- In the case of type mismatches, we want the args (expected, actual types, path to the field) - we should be passing these around as objects and not within strings

## Describe the solution you’d like
- Refactor this in the way that we would if we were implementing it with datadog first in mind before logging. 
- Keep the `JsonSchemaValidationError` as the source of truth for what the errors are. 
  - ❓ Can we access the `ValidationMessage`s directly instead of relying on the `JsonSchemaValdiationError` raised? This would be the easiest way to know exactly what the error is and the relevant arguments. [This comment](https://github.com/airbytehq/airbyte-platform-internal/blob/b34f2fcdb3f1b3f541344632c62f40fa6a1f6f9b/oss/airbyte-json-validation/src/main/java/io/airbyte/validation/json/JsonSchemaValidator.java#L216-L217) makes me think it might not be possible, though 🤔 
- Remove regeneration of log messages and `RecordSchemaValidationException`s. 
- Either remove the max count of logs, or only max count type mismatch errors, so that other potential errors are still logged

## Additional context
A brief history of the schema validator: 
- https://github.com/airbytehq/airbyte/pull/12231
- https://github.com/airbytehq/airbyte/pull/13351
- https://github.com/airbytehq/airbyte/pull/13393
- https://github.com/airbytehq/airbyte/pull/13457
- https://github.com/airbytehq/airbyte-platform-internal/pull/4758

**Comment by evantahler** [comment]
Grooming Notes:

* Other types of issues that might appear: missing require properties, ranges, additional properties when addtionalProperties is false, ENUM values that aren't in the list, etc.  These are also "schema validations" according to JSONSchema. 
* The code for all of this is more or less in 2 places (RecordSchemaValidator and ReplicationWorker for counting / totals)
* Now that we are in the background thread, we probably can `ensure()` on all records and build a map of all the errors (per stream).  But... don't log anything in the thread. Ask @davinchia about this.  The object
* A note on the limit: there's a lot.  Don't log them.  We can log once at the end showing all of the errors that happened in the sync.

**Comment by evantahler** [comment]
Schema validation errors found for stream _wrong_products. Error messages: [$.year is of an incorrect type. Expected it to be string, $.id is of an incorrect type. Expected it to be string]

**Comment by erohmensing** [comment]
Do we terminate the thread we spin up? Should we? What's the timeout on it?
