### ISSUE TITLE
Allow `/connector-performance` command to measure source-mysql

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#24862]
## Tell us about the problem you're trying to solve
The performance harness (`/connector-performance`) currently only wired to measure source-postgres.
As part of getting source-mysql to GA, we need to be able to continuously measure performance.

## Describe the solution you’d like
Add datasets and supporting configs to allow running harness on connector=source-mysql

**Comment by prateekmukhedkar** [comment]
Scope of this change is only to include source-mysql and not for other source connectors.

**Comment by evantahler** [comment]
There's a pattern that @alafanechere uses to put JSON files into GCS, and then load them into BQ/Metabase via the GCS Airbyte Source
