### ISSUE TITLE
Install dbt stuff inside destination-bigquery dockerfile (python, dbt, etc)

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#24877]
dbt has a ton of dependencies.... and we're fetching them from a deprecated docker image (https://hub.docker.com/r/fishtownanalytics/dbt). Figure out the right way to do this now, and install whatever things we need into the `destination-bigquery` docker image.

**Comment by evantahler** [comment]
It might be possible to skip the 'install' manually, and do a multi-stage build (e.g. `FROM airbyte/integration-base-java` and later `FROM dbt`).  If that works, and both base images are mutli-core, it may safe a lot of hassle.  

BUT... I think our base images fedora-based (`yum install`) and the dbt [base images](https://github.com/dbt-labs/dbt-core/blob/main/docker/Dockerfile) are Ubuntu (`apt-get install`) are so... 🤷
