### ISSUE TITLE
Update DATs to not run external normalization for destination-bigquery

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#24880]
* port existing base-normalization tests into DATs
* modify methods (e.g. testSyncWithNormalization - or anything that calls `runSyncAndVerifyStateOutput` with `runNormalization = true`) to _not_ run the normalization container, and instead just set the env var
* (maybe?) modify existing data types tests to also check normalized tables? (how does this fit with the existing normalization data type tests?)
* keep an eye on test runtime?

after completion:
* `/test connector=connectors/destination-bigquery` doesn't run any `airbyte/normalization` containers
* `/test connector=connectors/destination-bigquery` includes all test cases from `/test connector=bases/base-normalization`

**Comment by evantahler** [comment]
Grooming:

* Should we test a destination with both normalization and not (ENV flag)?  <-- test only with normalization enabled
    * Long term, we will always be typing and deduping, so eventually, we should test only with normalization on
    * Testing with normalization will help make tests more reliable
* This story is just about merging the existing tests, not making any new tests
   * if you find gaps in the test suite, make new issues we can groom
* We are PORTING python tests into Java.  
    * Maybe, there's a way to keep the tests in python and still run them?  Spend a little time investigating this.

**Comment by edgao** [comment]
for posterity - `/test` doesn't cover normalization, but normalization is code frozen so we can focus on 1s1t anyway.
