### ISSUE TITLE
Define Platform Stream Status Enum

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#24899]
## Tell us about the problem you're trying to solve
The platform will be responsible for mapping/translating connector level stream status into a more meaningful representation for the API/UI.  This will be the canonical list of statuses for the system.

## Describe the solution you’d like
Define an enumeration that contains the platform statuses for a stream:

* **NO_STATUS** - The default/empty state that indicates that the platform has not collected any status for the stream within a connection
* **PENDING** - The stream is part of a connection synchronization job but has yet to start moving data
* **RUNNING** - The stream is actively moving data/taking part in normalization/taking part in a reset
* **SUCCEEDED** - The stream has completed the synchronization/normalization/reset
* **FAILED** - The stream has finished due to an error in the synchronization/normalization/reset process
* **CANCELED** - The stream has finished due to cancellation of the synchronization/normalization/reset process.

In addition, the platform should also define the job types that are associated with the status:

* **DESTINATION_SYNCHRONIZATION** - the status is for a stream taking part in a normal data synchronization job from the destination connector’s point of view
* **SOURCE_SYNCHRONIZATION** - the status is for a stream taking part in a normal data synchronization job from the source connector’s point of view
* **NORMALIZATION** - the status is for the normalization that runs across all data associated with each stream
* **RESET** - the status is for a reset job associated with the stream

The platform status enum should also maintain the mapping between connector statuses and the platform statuses to ensure this logic doesn't get duplicated throughout the platform.

**Comment by davinchia** [comment]
@jdpgrailsdev does this refer to a database enum or java enum?

**Comment by gosusnp** [comment]
Not going to do.
