### ISSUE TITLE
User feedback when exporting data

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2490]
## Tell us about the problem you're trying to solve
I have an instance that has been running for a while and when I try to export data, it takes a lot of time to create the export. On demo.airbyte.io, I waited for at least 1minute.

## Describe the solution you’d like
We should have something in the UI to indicate that the export is being created

**Comment by cgardens** [comment]
Artem, can we reuse the same spinner strategy we have for reset data?
