### ISSUE TITLE
Add test coverage for interacting with deleted + disabled connections

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#24913]
Pulled out of https://github.com/airbytehq/airbyte-platform-internal/pull/5622

We have _many_ times now fixed and refixed how folks are able to interact with deleted and/or disabled connections.  Let's test it, shall we?

Deleted connections cannot:
- sync
- edit
- refresh schema
- reset
(basically anything besides viewing + renaming are a no-no)

Disabled connections cannot:
- sync 
- reset 
(check that this is true both with inline buttons in the table(s) and in the connection page itself)
but can:
- edit
- refresh schema

**Comment by josephkmh** [comment]
Refining notes:
- e2e tests are probably most resilient to change
- OSS test suite is correct place for this

**Comment by tealjulia** [comment]
I'm wondering if this should wait for https://github.com/airbytehq/airbyte-platform-internal/pull/6339

**Comment by tealjulia** [comment]
include a test case that the yellow deleted connection banner shows!
