### ISSUE TITLE
Snowflake destination quality of life improvement: default hostname postfix if not entered

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2491]
## Tell us about the problem you're trying to solve
From https://airbytehq.slack.com/archives/C019WJFR1JT/p1615925659006000

If a user enters `<account_name>.ust-east-1` it would be nice if the connector autocompleted the host name.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368154212492) by [Unito](https://www.unito.io)

**Comment by Adovenmuehle** [comment]
Found this in Snowflake connector code: https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/util_text.py#L229-L256

**Comment by sashaNeshcheret** [comment]
@sherifnada please take a look for [scoping doc](https://docs.google.com/document/d/1miU4frcz3p1zMtWo0qlRpW2Jojgukr89SGZVnDo6Xz0/edit)

**Comment by misteryeo** [comment]
@sashaNeshcheret added a comment and proposal in the doc.

**Comment by sashaNeshcheret** [comment]
@misteryeo agree with you proposition, i updated our solution, please, confirm it.

**Comment by misteryeo** [comment]
@sashaNeshcheret LGTM!

**Comment by sashaNeshcheret** [comment]
@misteryeo please help with assigning #9787 to someone from UI team

**Comment by tuliren** [comment]
Wait, this proposed solution here is incorrect. Snowflake can be hosted in not only AWS, but other cloud as well. See the doc [here](https://docs.snowflake.com/en/user-guide/intro-regions.html). We should not assume the suffix is always `aws.snowflakecomputing.com`.

One possible simplification is to use this URL format ([link](https://docs.snowflake.com/en/user-guide/jdbc-configure.html#syntax)):

> <account_identifier>.snowflakecomputing.com

But is it actually necessary? This feels like an unnecessary optimization.

**Comment by misteryeo** [comment]
Thanks @tuliren for pointing that out!

@sashaNeshcheret let's deprioritize this for now. This added information adds further complexity to the possible implementation so let's wait to see how many other users encounter this as an area of friction. Thanks!

**Comment by cgardens** [comment]
closing as stale
