### ISSUE TITLE
We should not be able to start a sync for a disabled connection

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#24926]
## Tell us about the problem you're trying to solve

`/api/v1/connections/sync` still attempts to start a sync for a disabled connection.

## Describe the solution you’d like

`/api/v1/connections/sync` should fail if the connection is disabled and the platform shouldn't start a sync.

**Comment by terencecho** [comment]
PR: https://github.com/airbytehq/airbyte-platform-internal/pull/5660

**Comment by terencecho** [comment]
this was done by https://github.com/airbytehq/airbyte-platform-internal/pull/5713
