### ISSUE TITLE
Investigate the use of Context for Micronaut

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#24927]
# What

Some of the Objects we currently use are "Context-Aware": they may be requiring `connectionId`, `jobId`, `attemptNumber`, etc.
Some of those instances are also not meant to be reused across syncs.

While it can be an implementation choice, it causes issues when it comes to dependency injection:
* How to pass some of the contextual values through the injection hasn't been yet identified.
* Scope vary, `@Prototype` fit most of the cases, however we may want to share some instances for a given sync (`SyncPersistence` for example is used directly and passed down to the `AirbyteMessageTracker`). The closest behavior currently in micronaut should be `@Request` however, this part of the system doesn't have the notion of an http request.

# How

A few leads to get started:
* play with `ApplicationContext`
* `CustomScope` which seems to be what's behind `@Request` or `@Refreshable`

The outcome of this task is to figure out either if there is a viable implementation or if we should rewrite some of our existing

**Comment by colesnodgrass** [comment]
We can create a custom-scope annotation for Micronaut by defining a specific `@Singleton` class and a matching annotation:
> Additional scopes can be added by defining a @Singleton bean that implements the [CustomScope](https://docs.micronaut.io/latest/api/io/micronaut/context/scope/CustomScope.html) interface.

However there are almost [no custom-scoped implementations that exist](https://github.com/search?q=import+io.micronaut.context.scope.CustomScope+-org%3Amicronaut-projects+-is%3Afork+-path%3Ahttp-client%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicronaut%2F+-path%3Aruntime%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicronaut%2F+-path%3Ainject%2Fsrc%2Fmain%2Fjava%2Fio%2Fmicronaut%2F+-path%3Amicronaut-core-2.5.5-master%2F&type=code) (at least on github or elsewhere that I could find). Leading me to believe this feature (outside of micronaut itself) is not well understood or truly useful.

Additionally, we would need a way to populate the values behind this custom-scoped annotation, and this is where I don't see an easy path forward.  The [ThreadLocal](https://github.com/micronaut-projects/micronaut-core/blob/2785a8d2e5a49a7187d107a18818304842b20797/context/src/main/java/io/micronaut/runtime/context/scope/ThreadLocal.java) annotation uses java's [java.lang.ThreadLocal](https://github.com/micronaut-projects/micronaut-core/blob/2785a8d2e5a49a7187d107a18818304842b20797/context/src/main/java/io/micronaut/runtime/context/scope/ThreadLocalCustomScope.java#LL36C92-L36C113). The [RequestScoped](https://github.com/micronaut-projects/micronaut-core/blob/2785a8d2e5a49a7187d107a18818304842b20797/http/src/main/java/io/micronaut/runtime/http/scope/RequestScope.java) annotation uses a [ServerRequestContext](https://github.com/micronaut-projects/micronaut-core/blob/2785a8d2e5a49a7187d107a18818304842b20797/http/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java#LL73C45-L73C65).

If we were going to go down this path, I think we would need to mimic how the `@RequestScope` annotation works by creating a `JobRequestContext`.  Possibly configuring the `JobRequestContext` prior to starting up the Micronaut application itself.

---

I do wonder if it would be simpler to refactor this section of code to live inside a web-service (at least for the job start functionality) and then utilize the tools that Micronaut already provides for handling request-scoped information.

The more custom complexity we add the more we end up managing and maintaining in the end.
