### ISSUE TITLE
Log View: filter log messages by origin

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#24922]
The origin of a log message is printed at the beginning of the log message, just after the timestamp:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/7550957/230200795-12487d65-e504-4426-94b3-7f09f9b6511e.png">

It would be useful to provide a UI dropdown that allows the user to filter for one or more of these origins, hiding messages that do not match those origins. This would make finding and grouping logs from a specific origin easier.

Unfortunately not all log lines are prefixed, for example:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/7550957/230201068-eb432c40-7609-41d6-b41f-d01580433aa5.png">

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/7550957/230201181-caeacf71-0994-4bc1-849a-98e8aa870311.png">

In these cases it would be sufficient to group them with the last log message that does have an origin. In the previous screenshot, this would mean _including_ the non-prefixed log lines if the user filtered for `replication-orchestrator`

**Comment by josephkmh** [comment]
Refining notes:
- We would like to get the source of logs from the backend so we don't have to parse the text on the frontend, so putting in the icebox for now until the API is adjusted

**Comment by nataliekwong** [comment]
Sharing from internal Slack: would also be nice to get a summary of how many errors are in each section when Move implements this

**Comment by davinchia** [comment]
> source of logs from the backend so we don't have to parse the text on the frontend

@josephkmh I don't quite understand ^, can you say more?

**Comment by josephkmh** [comment]
Sure! The frontend currently receives the log lines as an array of strings:

```
[
  "2023-10-04 21:56:53 \u001b[46mreplication-orchestrator\u001b[0m > ",
  "2023-10-04 21:56:53 \u001b[46mreplication-orchestrator\u001b[0m > Writing async status SUCCEEDED for KubePodInfo[namespace=jobs, name=orchestrator-repl-job-5064482-attempt-0, mainContainerInfo=KubeContainerInfo[image=airbyte/container-orchestrator:dev-9b6b1e92c9, pullPolicy=IfNotPresent]]...", 
  "2023-10-04 21:56:10 \u001b[32mINFO\u001b[m i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: dev-9b6b1e92c9-cloud"
]
```
One way for us to categorize these on the client side would be to parse each string and look for one of a set of well-known substrings. For example, `\u001b[46mreplication-orchestrator\u001b` indicates this line came from the `replication-orchestrator`. We could then apply a filter to only display log lines from a particular origin.

This is of course brittle, because we don't know exactly which origins might exist. With multi-line logs, not every line contains the prefix. I also see log lines that I cannot attribute to a particular origin, because they don't have a prefix. All in all, it seems unreliable to try parsing this on the client side with the current array of strings.

For example, I can imagine another data structure that would allow us to filter/group logs on the frontend without parsing the strings client-side:
```
[
  {
    origin: "replication-orchestrator",
    log: "2023-10-04 21:56:53 \u001b[46mreplication-orchestrator\u001b[0m > "
  },
  {
    origin: "replication-orchestrator",
    log: "2023-10-04 21:56:53 \u001b[46mreplication-orchestrator\u001b[0m > Writing async status SUCCEEDED for KubePodInfo[namespace=jobs, name=orchestrator-repl-job-5064482-attempt-0, mainContainerInfo=KubeContainerInfo[image=airbyte/container-orchestrator:dev-9b6b1e92c9, pullPolicy=IfNotPresent]]..."
  }, 
  {
    origin: "somewhere-else",
    log: "2023-10-04 21:56:10 \u001b[32mINFO\u001b[m i.a.w.t.TemporalAttemptExecution(get):129 - Executing worker wrapper. Airbyte version: dev-9b6b1e92c9-cloud"
  }
]
```

I'm not sure if this is the best approach, but something along these lines is what I had in mind. I'm happy to discuss further!

**Comment by josephkmh** [comment]
If changing the structure of the log response is too big a lift, we could also just define a list of well-known log line prefixes/substrings in the open API spec. We could still parse each line on the frontend, but at least that way we would have some certainty about the substring we're looking for.

**Comment by davinchia** [comment]
Got it, thanks!

Do we still want to support the current display of all logs sequentially with the origin?

If we do, 
- the new data structure would require a timestamp and the FE would have to do some sorting.
- or we continue sending the current file over.

There isn't an obvious solution for me, which makes me think perhaps it's easier for the FE to do the filtering. However I don't understand FE filtering complexity. Would it be easier to schedule a quick sync up?

**Comment by davinchia** [comment]
Open questions:
- will people get more confused with filters?
- in the long term, do we want to expose all the logs? what if we had a separate summarised event view, with the entire log only available on 'power mode'?

**Comment by josephkmh** [comment]
> Do we still want to support the current display of all logs sequentially with the origin?

Yes, we should keep the option of showing all the logs sequentially with the origin. I think we want filtering by origin _in addition_ to the full view.

Sounds like it might be worth syncing up in a call to go through our options.

> will people get more confused with filters?

This is more of a feature for power users, so I wouldn't worry too much about the average cloud user being confused. Logs are already confusing for users who don't have a good understanding of how airbyte works.

> in the long term, do we want to expose all the logs? what if we had a separate summarised event view, with the entire log only available on 'power mode'?

I think in the long term, _no_. Ideally we can show actionable error messages without exposing so many of the sync internal logging. But with the current state of error reporting from failed syncs, I think we are a long way away from this. I suspect power users (TCS, connector devs) will always appreciate having the full log output available for inspection. Curious if @nataliekwong has anything to add here.

**Comment by davinchia** [comment]
Met with Joey.

Next steps:
* Davin to find out if we can add origin to logs from the worker and sync up with Joey.
* Joey will polish out the naive filtering solution he currently has.
* Davin to sync up with Natalie on long term logging north star.
