### ISSUE TITLE
[MOVE EPIC] Unify Container Orchestrator Code Path

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#24925]
# What

The container orchestrator is a core piece of the Platform. Today the code has varying branches and object lifecycles depending on whether it's Docker/Kube. Clean this up to make future modifications easy.

# How

Leverage Micronaut for Bean initialization and context specific implementation selection.
At the end of the project, we should no longer have duplicated code related to the initialization of the `DefaultReplicationWorker` and the `ReplicationActivityImpl` should no longer need to be aware of the environment (Kube vs Docker)

Also, to keep the scope of the refactoring under control, we should avoid as much as possible to refactor what's in the `DefaultReplicationWorker` as this is mostly business logic that shouldn't be impacted by the current task.

# Definition of Done

* Abstraction exists in the various workers that make it easy to kickoff running an orchestrator process without needing to know implementation details e.g. Docker or Kube.
* After the refactor, object lifecycle and creation should be identical regardless of Docker/Kube.

**Comment by davinchia** [comment]
This is done.
