### ISSUE TITLE
Number of attempts should be configurable

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#2493]
## Tell us about the problem you're trying to solve
I am looking for low-latency from configuration to sync. So if I add a new table to the sync and mess it up for whatever reason, I don't want to sit there waiting ages for some retries to complete before I can unbork my borkery. I use a low sync frequency so retries aren't particularly useful (instead of the 3rd retry finishing 15 mins after the first attempt starts, I can just count on the next fresh sync to do the job 5 min later).

## Describe the solution you’d like
A way to configure the number of retries.

## Describe the alternative you’ve considered or used
I'm going to set local tries at 1.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368095885577) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
This is configurable now at deployment level:
https://github.com/airbytehq/airbyte/blob/39ab9a20c932c300703e9458a255cc3f9e0a47c9/.env#L63
