### ISSUE TITLE
Clarify current Temporal Exception handling + figure out consistent path forward.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2497]
## Expected Behavior
When `TemporalJobException` is thrown, the exception is not propagated to the client. Instead it's caught in the temporal worker itself and the job is restarted within temporal. The client just waits. This might be related to #2452 .

## Current Behavior
I expect the exception to propagate to the client after X attempts. Any other reasonable manner of handling this is fine - as long as it's consistent and surfaces errors.

## Steps to Reproduce
1. Check out this [branch](https://github.com/airbytehq/airbyte/blob/davinchia/bad-temporal-example/airbyte-workers/src/main/java/io/airbyte/workers/temporal/CheckConnectionWorkflow.java#L92) and run the workflow.
2. Observe logs.

## Severity of the bug for you
Low - don't think this is affecting anyone in particular. Chanced upon this while investigating tracking handling. 

## Airbyte Version
0.17.0 onwards

**Comment by cgardens** [comment]
should be fixed by this https://github.com/airbytehq/airbyte/pull/2502
