### ISSUE TITLE
Source JIRA: Add boardId to sprint stream

### ISSUE THREAD

**Issue by eschrock** [airbytehq/airbyte#24981]
## Tell us about the problem you're trying to solve

Here is my post on the topic over at discuss.airbyte.io:

https://discuss.airbyte.io/t/how-to-map-sprints-to-boards/4128

The Jira connector exposes a sprints stream, but there is no way to determine which board(s) a sprint is a part of. The `originBoardId` is not the same as the current board(s).

## Describe the solution you’d like

When we query for the sprint, we have the board ID in hand:

```
    def path(self, stream_slice: Mapping[str, Any], **kwargs) -> str:
        return f"board/{stream_slice['board_id']}/sprint"
```

However, we don't include this board ID in the data we send back. In the `BoardIssues` stream, we have the same API structure but explicitly include the board ID into the payload:

```
    def transform(self, record: MutableMapping[str, Any], stream_slice: Mapping[str, Any], **kwargs) -> MutableMapping[str, Any]:
        record["boardId"] = stream_slice["board_id"]
        record["created"] = record["fields"]["created"]
        record["updated"] = record["fields"]["updated"]
        return record
```

The `Sprints` stream should apply the same logic and add `boardId`.

## Describe the alternative you’ve considered or used

You can manually join `BoardIssues` with `Sprints`, but this seems unnecessarily complex, and won't catch cases where there aren't any issues assigned (however unlikely that may be).

## Are you willing to submit a PR?

Yes, though I may need help with tests & documentation.

**Comment by pabloescoder** [comment]
I want to work on this issue, please assign it to me.
