### ISSUE TITLE
Destination Postgres: Failure Origin: destination, Message: Something went wrong within the destination connector

### ISSUE THREAD

**Issue by prensgold** [airbytehq/airbyte#24986]
## Environment
- **Airbyte version**:  Airbyte version: 0.42.1
- **OS Version / Instance**: Red Hat Enterprise Linux release 8.7 (Ootpa)
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mysql:2.0.12
- **Destination Connector and version**: airbyte/destination-postgres | 0.3.27
- **Step where error happened**: Sync job 

## Current Behavior
While doing cdc replication from mysql to postgresql, I get the following error.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/118886124/230641690-7e1d83c4-0b6c-4142-ac6c-4b8cff6944ba.png">

## Logs
[logs.log](https://github.com/airbytehq/airbyte/files/11180106/logs.log)

**Comment by evantahler** [comment]
Closing - this destination has been updated significantly since this issue was posted.
