### ISSUE TITLE
Source Retently: v0.1.3 missing streams defined in code

### ISSUE THREAD

**Issue by henriblancke** [airbytehq/airbyte#24996]
The retently connector source defines [8 streams](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-retently/source_retently/source.py#L53-L60), the UI only shows 6:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1708162/230666439-047e3aa4-4f51-4004-9fd2-b00bd29945ec.png">

## Environment
- **Airbyte version**:  0.43.1
- **OS Version / Instance**: macOS
- **Deployment**: docker
- **Source Connector and version**: `source-retently==0.1.3`
- **Step where error happened**: Setup new connection

## Current Behavior
The code [defines 8 streams](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-retently/source_retently/source.py#L53-L60). The UI only shows 6. Missing streams: `outbox` and `templates`

## Expected Behavior
`outbox` and `templates` are available as streams in the UI. [For version 0.1.3](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-retently/Dockerfile#L37)

## Steps to Reproduce
1. Set up the retently source
2. Create a connection to any destination
3. See 6 streams listed in screenshot, missing `outbox` and `templates`

## Are you willing to submit a PR?
Yes

**Comment by henriblancke** [comment]
I think this was caused by competing PRs that were created/merged close to each other:
* https://github.com/airbytehq/airbyte/pull/19381
* https://github.com/airbytehq/airbyte/pull/19456

I also noticed that https://github.com/airbytehq/airbyte/pull/19381 introduced an invalid json schema for `nps`. I will open a PR to fix that.

**Comment by kurayami07734** [comment]
I would like to work on this

**Comment by justinbchau** [comment]
all yours @kurayami07734

**Comment by ashanviii** [comment]
Hey is it done? if not @justinbchau can you assign it to me ?

**Comment by justinbchau** [comment]
@kurayami07734 are you still going to be working on this?

**Comment by kurayami07734** [comment]
Yes

**Comment by Katyayani2610** [comment]
Hey @justinbchau will you please assign  this issue  to me ?

**Comment by topefolorunso** [comment]
This issue is fixed here https://github.com/airbytehq/airbyte/pull/25714
