### ISSUE TITLE
Clean up the CreateConnectionPage routing/workflow logic

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#25001]
## The problem: an idiosyncratic, hard-to-understand flow with an overloaded god component
Right now, the entire flow is managed within a single god component, `CreateConnectionPage.tsx`. Within that component, the different UI subtrees for various views are selected and dispatched internally via an idiosyncratic, fairly opaque `renderStep` function. To navigate between views, the internal state of the god component is mutated. This is confusing, inefficient (all the UI code for every step must be fully parsed and loaded to render any step), and extremely unconventional. Although the free connector program required adding some workflow state to the URL to enable navigating to Stripe checkout and back without wiping all in-progress work, the legacy implementation's brittle and invisible use of `location.state` as the storage mechanism for source/destination connector ids remains. The legacy state/view transitions have structural differences between exactly parallel supported workflows:
- selecting a source, then a destination (when creating a connection "from scratch" or when coming from the CTA on a specific source connector's detail page)
- selecting a destination, then a source (when coming from the CTA on a specific destination connector's detail page)

## Overview of the high-level goals
- Improve component and route structure :: create simpler, self-contained components for each distinct sub-page of this flow, with all user progress/page transitions reflected in the url
- Simpler, more explicit state transitions between sub-pages, with an API that supports source-first and destination-first user flows equally 
- Removing all usage of `location.state` when tracking a user's progress through the create connection flow

## Implementation and release
The current implementation is all tangled up in itself. Rather than trying to untangle that Gordian Knot in order to migrate it to a cleaner implementation, I recommend we create the new components and routes afresh, leaving the legacy implementation untouched, and release the improved version via the Indiana Jones method:
![](https://media.tenor.com/eqLNYv0A9TQAAAAC/swap-indiana-jones.gif)

## Improve component and route structure
Here are the different logical steps, with a suggested component name and route. Details are of course negotiable, so long as the structure is coherent and users can enroll in the free connector program or refresh the page without losing all progress.

Component name and route suggestions will use the `.../` prefix to represent, respectively, the parent directories and the url segments they are nested under.

#### Steps 1 & 2 :: Selecting the source and destination connectors
The UI and UX for selecting a source or destination is nearly identical, so code sharing and colocation of those two sub-pages is pragmatic; but there should be distinct top-level components for source vs destination.

*Suggested component names and routes:*
- `.../SelectSource.tsx` :: `.../connections/new` and `.../connections/new?destinationId=<UUID>`
- `.../SelectDestination.tsx` :: `.../connections/new?sourceId=<UUID>`

#### Step 3 :: Fetching the schema once source and destination have both been selected
This is a glorified loading spinner, tbh, but it's a distinct stage of the connection creation process.

*Suggested component name and route:*
- `.../FetchSchema.tsx` :: `.../connections/new/fetch-schema?sourceId=<UUID>&destinationId=<UUID>`

#### Step 4 :: Configuring the soon-to-be-persisted connection
This is the form where we specify configuration details like name, replication frequency, and cursor field for the connection-to-be. This component will likely need to be able to redirect back to 

*Suggested component name and route:*
- `.../ConfigureConnection.tsx` :: `.../connections/new/configure?sourceId=<UUID>&destinationId=<UUID>`

## Simpler, more explicit state transitions between sub-pages
Here is a flow chart of the different states a user can be in:
![Screenshot 2023-04-17 at 12 22 37 PM](https://user-images.githubusercontent.com/7516653/232589765-9df8eaa7-e291-49c6-aa94-b12eb24ec2a0.png)
Because the "select source" and "select destination" sub-pages can either come first or second, depending on how the user entered the create connection flow, we have a choice to make:
1) Both components need to contain conditional logic to determine whether they should send users to the other or to the fetch schema sub-page
2) We create a little state machine with `useReducer` to handle the transitions, so each component can dispatch an action when it's done without needing any knowledge of external context

I think option 2 is much cleaner. The components' behavior can be completely self-contained and context-independent, and the reducer's decision tree is extremely simple:
![Screenshot 2023-04-17 at 12 41 27 PM](https://user-images.githubusercontent.com/7516653/232593375-5bf5b49e-9baa-45f4-8e29-c3b7957d0cb5.png)

## Remove all usage of `location.state` when tracking a user's progress through the create connection flow
I feel like this one is pretty self-explanatory, tbh. We need to reflect user progress in the url to avoid breaking free connector enrollment, and doing so also enables page refreshes (for example, by clicking the CTA that pops up when an updated version of the webapp is deployed) and power user hacks like bookmarking or sharing links to a partially-completed flow for free. If we never make the rewritten create connection flow dependent on`location.state`, it will vanish with the rest of the legacy create connection flow in the post-rollout cleanup.

There is one nuance worth calling out, though: the routing logic of the "add destination"/"add source" CTAs respectively found on the source and destination detail pages will need to be feature-flagged just like the routing of the "+ New connection" CTA on the connections list. (This is true regardless of what we do with `location.state` so long as the rewritten flow uses different client-side routes than the legacy one, to be fair.)

## Open questions/judgement calls/points of discussion
1) using query params for connector ids instead of path parameters
We could well use urls like `.../connections/new/source/<UUID>/destination/<UUID>` and achieve all of the same things, but, well, I think it's ugly and its ordering would imply a hierarchy between source and destination when they are logically peers. Open to other opinions, though, there may be a third option I overlooked.
2) ?

**Comment by ambirdsall** [comment]
@josephkmh @tealjulia sure thing, [here's the google doc version](https://docs.google.com/document/d/1a1bazfWmxVnSgykVJTpyXJ2sFwtxfIZ4lqxzkNNvtHY/edit#heading=h.otxvrnw8u2u8)

**Comment by josephkmh** [comment]
Suggested additional query params:
- `?sourceType=<new | existing>`
- `?destinationType=<new | existing>`

This would allow us to show the correct option (new vs. existing) in this piece of UI:

![image](https://user-images.githubusercontent.com/7550957/234233193-698e66bf-4d17-4bda-b292-85ec62c7bc78.png)

That's relevant when we link from the sources or destinations page, where a user might click "+ add a new source":

![image](https://user-images.githubusercontent.com/7550957/234232894-4bc2820c-746a-467c-bedd-95d331565884.png)
