### ISSUE TITLE
Destination MySQL: Sorting by last sync fails when there is a no sync connector present

### ISSUE THREAD

**Issue by Skorkmaz88** [airbytehq/airbyte#25000]
## Environment
**Airbyte version: 0.42.1
**OS Version / Instance**: Ubuntu 22.04
**Deployment**: Docker

- **Step where error happened**: 
Listing jobs and sorting by last sync time

## Current Behavior
Last sync sorting does 

## Expected Behavior
connectors should be sorted in correct order

## Logs
<img width="705" alt="Screen Shot 2023-04-08 at 00 54 21" src="https://user-images.githubusercontent.com/1834237/230684316-63285250-3226-40b8-a171-d401f35b37cf.png">

## Steps to Reproduce
1. have multiple connectors with at least one of them being manual 
2. Never sync the manual
3. Have several others synced
4. Sort by last sync

**Comment by timroes** [comment]
This has been fixed in the meantime, and is working now correctly.
