### ISSUE TITLE
Slack Webhook: Notification Error

### ISSUE THREAD

**Issue by blueband** [airbytehq/airbyte#25007]
## Environment
- **Airbyte version**:  example is 0.43.0
- **OS Version / Instance**:  Ubuntu 18.04, GCP n4. 
- **Deployment**: Docker
- **Step where error happened**: Setting Up Slack Notification

## Current Behavior
*I was seeing up slack notification by filling the webform meant to save Slack web hook url, but hen I filled the form with generated url from slack, and click test button, I got following error  **"Webhook test failed. Please verify that the webhook URL is valid."**

## Expected Behavior
*Slack web hook url should indicated successful test and send text message "Hello world " to the slack channel.*

## Steps to Reproduce
1. Launch Airbyte UI
2. Navigate to **Settings**
3. Click on **Notification**
4. Paste generated Slack web hook from **https://api.slack.com/** (**Incoming webhook**)

-->

**Comment by k0t3n** [comment]
Same for me

**Comment by BernalCarlos** [comment]
I'm facing the same issue on version 0.50.7

**Comment by iainad** [comment]
I can confirm it's an issue with 0.50.7, 0.50.8 and 0.50.10. Reverting to 0.50.6 works fine.

**Comment by marcoruizv** [comment]
Same.  v`0.50.7`

**Comment by josephkmh** [comment]
I tested upgrading from `0.43.0` to `0.50.7` and can reproduce that the webhook test is always failing. Upgrading to `0.50.8` fixed this, when a new notification form was rolled out:

<img width="1253" alt="image" src="https://github.com/airbytehq/airbyte/assets/7550957/e120dfef-f0e1-4175-81a8-123f8108481c">

If anyone is still having issues testing/saving webhook notifications, please let me know what version you are using. Closing for now, as the issue appears to be resolved.
