### ISSUE TITLE
Low-code CDK: support cursor field in nested field

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#25008]
### Component Description

Components that update the cursor value should be able to extract it from the nested fields of the records.
For instance,
```
{
   "id": "id",
   "Metadata": {
      "LastUpdatedTime": "<DateTime>"
   }
}
```
currently there is now way we can get the `DateTime` value from the object since we can not use jinja to evaluate two or more consequent `get()`s:
`last_record_value = last_record.get(self.cursor_field.eval(self.config)) if last_record else None` 

### Proposed YAML schema

We should provide a way to specify a path to the cursor value in the record like
```yaml
cursor_field: ["Metadata", "LastUpdatedTime"]
```
or
```yaml
cursor_field: "Metadata.LastUpdatedTime"
```

### Connector API Docs URL

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account

**Comment by girarda** [comment]
Putting this on the icebox because there's a discussion about only supporting cursor fields at the top level. [See this docs for more details](https://docs.google.com/document/d/1T77e4V54g7-RiG02fm406iDa6PO-kkLJU0c6wJRyZhg/edit#heading=h.o1818g385kxc)

**Comment by girarda** [comment]
closing as per my last comment
