### ISSUE TITLE
dbt error grouping should be better

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#25017]
Consider these 4 issues:

* https://github.com/airbytehq/alpha-beta-issues/issues/1154
* https://github.com/airbytehq/alpha-beta-issues/issues/1158
* https://github.com/airbytehq/alpha-beta-issues/issues/1159
* https://github.com/airbytehq/alpha-beta-issues/issues/1161

They all have errors like: 
```
connection to server at "{HOST}" ({IP}), port 5432 failed: timeout expired
```

Can these errors be grouped by sentry?

**Comment by evantahler** [comment]
Consider these 4 issues:

* https://github.com/airbytehq/alpha-beta-issues/issues/1154
* https://github.com/airbytehq/alpha-beta-issues/issues/1158
* https://github.com/airbytehq/alpha-beta-issues/issues/1159
* https://github.com/airbytehq/alpha-beta-issues/issues/1161

They all have errors like: 
```
connection to server at "{HOST}" ({IP}), port 5432 failed: timeout expired
```

Can these errors be grouped by sentry?

**Comment by evantahler** [comment]
Grooming:

* This is a known problem :/. We don't have a stack trace.  Whatever Sentry is doing by default isn't that smart without a stack trace
* dbt does have a JSON log format... which might have more structured output?  George was looking into it back in the day.  (FIND OLD TICKET)

**Comment by evantahler** [comment]
Tagging @pedroslopez to see if the old issue can be found

**Comment by edgao** [comment]
I was actually tracking down this earlier (it's related to the normalization-in-connectors work) - original PR was https://github.com/airbytehq/airbyte/pull/14790, plus there were some followups that I didn't dig through

(still agree that we should icebox this for now - my current plan is to just wrap normalization logs into airbytelogmessages where necessary, and I'm not planning to try and improve those log/trace messages in any way)
