### ISSUE TITLE
On every keystroke an network request is made

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2501]
## Current Behavior
It seems like on every keystroke in the connector form a network request is made to fetch a logo.

![Screen Cast 2021-03-17 at 10 17 56 AM](https://user-images.githubusercontent.com/9092207/111509836-5f1b9d00-870a-11eb-8887-30a385ca9f60.gif)

**Comment by Jamakase** [comment]
Duplicate https://github.com/airbytehq/airbyte/issues/2330
