### ISSUE TITLE
Shopify doesn't accept full store name URL

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#25026]
# high give up rate on Shopify connector

We watched fullstory sessions after noticing a high give up rate. In the shop name field, people copy paste the full URL even though we just accept the shop name itself. This fails the setup. Example: full store URL could be e.g: “airbyte.myshopify.com” but the field expects only the name portion i.e: “airbyte”. 

@lazebnyi can you recommend a solution?

**Comment by lazebnyi** [comment]
answered - https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1681163367318529
