### ISSUE TITLE
Repository field on GitHub connector doesn't accept full URL

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#25025]
Need to improve setup success rate on GitHub connector
# problem
We watched fullstory sessions after noticing a high give up rate. In the repository field, most people input the full URL e.g “https://github.com/openai/gpt-3.git” and even though the error message said specifically what the correct format is, they didn’t know what to fix. We require just the repository name, not the full URL, so it fails to setup. 

 @lazebnyi how do you recommend we fix?

**Comment by lazebnyi** [comment]
answered - https://airbyte-globallogic.slack.com/archives/C02U9R3AF37/p1681163367318529

**Comment by grubberr** [comment]
I can propose such approach. We can re-implement spec to be  `"type": "array"` with strict regex on every item like this:

```
"type": "array", 
"items": {
  "type": "string",
  "pattern": "^(?:[\\w.-]+/)+(?:\\*|[\\w.-]+)$"
}
```

![Screenshot 2023-05-04 at 18 25 57](https://user-images.githubusercontent.com/195743/236256902-d140e4b8-9ab4-4c0b-9db7-cf07c7d9123c.png)

if customer starts to enter something  wrong, there will be error message like this:

![Screenshot 2023-05-04 at 18 28 25](https://user-images.githubusercontent.com/195743/236257086-ed7dff3b-f2f0-455c-958b-bf34b05d49c2.png)

**Comment by lazebnyi** [comment]
@grubberr For me look good, but be carefully it's look like breaking changes. And may be we need think how to improve error message. 

@flash1293 Could you assist us in enhancing the error message? Currently, it seems that custom error messages are not supported in the specification.

**Comment by lmossman** [comment]
Yes, I will work on fixing this as part of removing the experiment

**Comment by grubberr** [comment]
https://github.com/airbytehq/airbyte/pull/25778 - Merged
