### ISSUE TITLE
[Low-code CDK] Raise error on passing unsupported value formats as query parameters

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25032]
## Context

As discussed in [this slack thread](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1681165885984729?thread_ts=1681159224.845049&cid=C02TL38U5L7), the url library used in the low-code CDK doesn't support passing arrays as query parameters, and there is no standard way to format objects in query parameters.

Therefore, the low-code CDK should throw an explicit and helpful error message if an array or object is passed into a query parameter, so that the user isn't confused as to why this doesn't work.

(Note: the low-code CDK should throw this error instead of the builder UI so that behavior is consistent across both, and because the builder cannot tell if an interpolated value would result in an array or object.)

## Alternatives considered
Alternatively we could switch to a different library that supports arrays as query params, and decide on a format to use for objects in query params or let the developer decide that. 

However, since this is an edge case that we haven't seen strong demand for, and deciding on a format is not very helpful if the API doesn't support it, then we are opting for an error instead.

## Acceptance Criteria
- An error is thrown by the low-code CDK if an array or object is attempted to be passed in as a query parameter to the request

## Open question
- Should the exception be thrown from HttpStream or should this be scoped to low-code?

**Comment by girarda** [comment]
grooming notes:
- let's fix this at the HttpStream level for all connectors
points: 2
