### ISSUE TITLE
Write spec for 1 stream = 1 table + rough execution plan

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#25031]
* what does the 1 table look like?
    * 1 raw + 1 top-level table
* what CATs do we need? other guidance for sources?
    * pk + cursor must be top-level fields
    * "important" fields must be top-level fields
* execution plan:
    * v0 via dbt + modded base-normalization?
    * v0 via java? (https://github.com/airbytehq/airbyte/pull/24973)

**Comment by edgao** [comment]
doc is https://docs.google.com/document/d/12iQv2G7rQMdNWPik973l8B5U3aGLnnlK4u4zi1Xcji0/edit#heading=h.x2swcqu05bat

in review, targeting ratification by next wednesday.

**Comment by evantahler** [comment]
Pretty sure this is done!
