### ISSUE TITLE
Update Dagster Cloud agent to v1.0.17 or later OR move to Dagster cloud

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25035]
## What
To add environment variable to Dagster Hybrid Cloud we need the agent in the dagster-cloud GKE namespace to be updated to `v1.0.17` or later
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/e9e48f09-09ae-409a-bde7-e7f2c602cd17)

## How
This should be 
1. Updating the GKE cluster in ab-analytics to be available through tailscale
1. Updating the `dagster-cloud` agent version in the helm chart for `private-cluster-0` in the `ab-analytics-dagster` GCS project
1. Restarting the agent

## Docs
https://docs.dagster.io/dagster-cloud/deployment/agents/kubernetes/configuring-running-kubernetes-agent#step-3-start-the-agent
https://artifacthub.io/packages/helm/dagster-cloud/dagster-cloud-agent

**Comment by evantahler** [comment]
Grooming:
* Maybe we update our K8s scrips and rebuild it, or we move to Dagster cloud.  TBD
  * Check Tim's [doc](https://docs.google.com/document/d/18iLD1I3-4-JjPvKS9wtGjaUzi20wIpnekjkhhukgaCM/edit#heading=h.hg6wrczfl6kz) to learn why we picked daggster cloud
* The outcome if this story involves investigating Dagster cloud to skip this whoule thing
