### ISSUE TITLE
Allow notifications to time out

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#25040]
Currently notifications will stick around until they are explicitly removed via its id or removed from the user.

In some cases it is preferable for notifications to disappear after some time. This should be configurable via a timeout option on the method registering the notification

**Comment by josephkmh** [comment]
@flash1293 in this PR I introduced a 5-second timeout: https://github.com/airbytehq/airbyte-platform-internal/pull/7508

Do you think there are use-cases where individual notifications should have different length timeouts? It would be pretty easy to implement, I just couldn't think of a scenario where it's required.

**Comment by flash1293** [comment]
@josephkmh Happy to go with a universal timeout for now and see whether it even comes up
