### ISSUE TITLE
docker image airbyte/connector-atelier-server:0.42.1 manifest not found

### ISSUE THREAD

**Issue by amjadseera** [airbytehq/airbyte#25042]
## Environment
- **Airbyte version**:  0.42.1 
- **OS Version / Instance**: AWS EC2 EKS NODE
- **Deployment**: kubernetes
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Tell us what happens.*
seems like the docker image version `airbyte/connector-atelier-server:0.42.1`  is missing and I'm getting this error:
```
Error response from daemon: manifest for airbyte/connector-atelier-server:0.42.1 not found: manifest unknown: manifest unknown
```
## Expected Behavior
*Tell us what should happen.*
docker image pull should work without any issues.
## Steps to Reproduce
1.`docker pull airbyte/connector-atelier-server:0.42.1`

**Comment by vrfn** [comment]
related: https://github.com/airbytehq/airbyte/issues/24920

**Comment by marcosmarxm** [comment]
At Airbyte, we seek to be clear about the project priorities and roadmap. This issue has not had any activity for some period, suggesting that it's not as critical as others. It's possible it has already been fixed. I'm closing as it reports a problem with an old version of Airbyte. Please upgrade and use latest version, if the problem still there open a new issue. Thanks
