### ISSUE TITLE
Update actor definition seeding logic to create actor definition version entries

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#25060]
## Overview

After #25059 adds the actor_definition_version table to the database, we'll need to start populating this table when loading definitions. This happens in the bootloader and in airbyte-cron at an interval.

The general logic is:
1. Read latest information from the DefinitionProvider.
2. Update any actor_definition-level fields (e.g. name)
3. Create/update actor_definition_version

When adding an actor_definition_version, we should ensure that protocol versioning is respected and the same rules still apply.

We'll need to identify the default version of the connector the should be used. For this, we can add a new default_version_id column to the actor_definition and ensure it points to the latest version we've updated.

The old behavior of updating the per-version fields  on the actor definition itself should remain at this stage.

## Additional context

This is part of phase 2 of [[Tech Spec] Multiple Connector Versions ](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI)

**Comment by evantahler** [comment]
Grooming:

* Keep the old behavior the same, and this story is additive to make a row in the new `actor_definition_version` version
* OSS and Cloud do things differently!
  * Cloud is simple 
  * OSS is fancier `ActorDefinitionMigrator`
  * As part of this work, we should unify how we process new definitions as they are read

**Comment by erohmensing** [comment]
Bonus: we should update the bootloader test to seed in the same way that we actually seed (i.e. using the ApplyDefinitionsHelper) - see comment https://github.com/airbytehq/airbyte-platform-internal/pull/5849#discussion_r1166917062
