### ISSUE TITLE
Update catalog naming to be registry

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25069]
## Overview
We need to start calling our catalogs registry instead.

This ticket is concerned with updating the new dagster system to output the appropriate file paths and use the correct naming in code

## What needs to be updated
1. The names of our `catalog` files and functions in dagster to `registry`
1. The output of `oss_catalog.json` should now be `oss_registry.json`
1. The output of `cloud_catalog.json` should now be `cloud_registry.json`
1. registry files should be output to `registry/` instead of `catalog/`
1. The catalog field in the metadata file should now be registry

## What is out of scope
1. Updating the platform to use the new registry files
1. Updating the platform to use the new registry file names

**Comment by pedroslopez** [comment]
@bnchrch Are we planning on removing all the `catalog` references from platform-internal as part of this?
