### ISSUE TITLE
Determine and Implement an error collection "channel"

### ISSUE THREAD

**Issue by jcowanpdx** [airbytehq/airbyte#25071]
Implement a universal error collector or error channel mechanism. 

Errors generated during an async “stage and load” phase of operation will no longer be observable by the consumer thread as is the case in a synchronous connector. These errors should be observed by the main consumer thread, recorded, and cause a failure of the sync as works with synchronous connectors today.

**Comment by evantahler** [comment]
Grooming:

* service / error channel that can be used by child-threads.  (poll a shared data structure, message-channel, queue, etc).  This story is to choose the right way to share data between threads,
* parent thread then throws proper AirbyteTraceMessages and then exits the process
