### ISSUE TITLE
[SPIKE] Refactor State Handling

### ISSUE THREAD

**Issue by jcowanpdx** [airbytehq/airbyte#25072]
Refactor the State handling mechanism in order to separate the State from State management and acknowledgement. 

During a sync, State messages are arriving in-stream with data. Periodically, we flush the buffered data to our staging destinations. I call this "stage and load". This can occur for a variety of reasons: buffers are "full", a timer has expired, or at the very end of the source data.

At the next “stage and load” operation, and only upon successful completion, the latest State should then be acknowledged back to the platform. Once we introduce asynchronous “stage and load”, the State _at the time_ that the async job is enqueued needs to be captured as a part of the async context and then acknowledged at the time of successful completion of the job. Meanwhile, additional State messages may be arriving in the consumer thread and must not be conflated with the State at the time of the async job creation. Otherwise, a particular flush may acknowledge a more recent State message that it's data represents. 

A further nuance is that global flush operations (all streams are being flushed), the State acknowledgement must occur after ALL streams are flushed,

Definition of done:
* Present the plan to the team (doesn't need a formal spec, can be a PR or whimsical)
* Write up following stories from the below

Original DoD
* Upon flush, the State at the time of the flush gets bound to the flush job and acknowledged after the flush.
* If there is no State at the time of flush, no State is acknowledged.
* This work covers both per-stream flushes and global flushes.
* For a multi-stream global flush, state acknowledgement occurs after all buffers are flushed.
* If there is an error during a flush, no state is acknowledged.

Tests:
* Single stream global flush with no state
* Single stream global flush with state
* Multiple stream global flush with no state
* Multiple stream global flush with state
* Single stream per-stream flush with no state
* Single stream per-stream flush with state
* Failed Flush with state does not acknowledge State

**Comment by evantahler** [comment]
## Grooming:

**Notes**
* STATE message are determined by the sources, each source creates their own format for how they want to read STATE messages
* The State Management classes are `DestDefaultLifecycleManager` and associated classes.  
  * Are we making a new type of LifecycleManager?  There's Global and per-stream now... maybe a new AsyncStateManager is what we need.  This could reduce the risk. 
  * This might be a BIG PR.

**Implementation**
* This probably needs a plan (mini-spec).  The key is that it doesn't effect other destinations (this is done in )
* Then we do make it.
