### ISSUE TITLE
Perform any "code isolation" work necessary

### ISSUE THREAD

**Issue by jcowanpdx** [airbytehq/airbyte#25076]
This work is happening in parallel with an effort to isolate async changes in the Snowflake connector from other connectors that use the same base classes. It may be necessary to perform temporary isolation of changes into the Snowflake connector while this refactoring is taking place. This story accounts for that. This story may be moot depending on the timing of this work.

**Comment by ryankfu** [comment]
This works has been isolated in part to the `base-java` and `bases-destination-jdbc` split https://github.com/airbytehq/airbyte/pull/25649
