### ISSUE TITLE
Develop and execute a rollout plan for incremental release

### ISSUE THREAD

**Issue by jcowanpdx** [airbytehq/airbyte#25078]
Once ready for release, we need a way of rolling these changes out incrementally.

The current solution involves a feature flag. Implement a feature flag or use a mechanism provided by connector ops to accomplish this. We want something like:
* Add verbose logging tells us what we need for debugging
* Be sure we can rollback if the connector doesn't work.  Be sure we can reset user data if needed or rollback state.  
* Set up a sync in our own workspace to Snowflake using the old and new connector at the same time.  Compare the resulting tables and make sure they match.  Confirm that the new connector is faster.
* Single workspace for 3 days
* Small (<10) number of workspaces for 1 week
* Remove verbose logging
* All workspaces

We want to monitor throughput, errors and sync success/failure rates as a minimum. We will also use Sentry to capture errors as usually.

**Comment by evantahler** [comment]
## Grooming

Notes:
* Check out the S&S Rollout plan (Sync with @edgao)
* We want a list of _active_ workspaces which use snowflake to choose from (get that list from TCS)
   * Can segment by connection type in LaunchDarkly? no, but we can apply the flag manually as needed
*

**Comment by evantahler** [comment]
The plan is to do https://github.com/airbytehq/airbyte/issues/26795 and then slowly ramp up the %.
