### ISSUE TITLE
One Java One Publish: Move `destination-jdbc` into `base-java`

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#25070]
## What
There is a tight coupling between the `destination-jdbc` components (`StagingConsumerFactory`, `JdbcConsumerFactory`) and the buffering components that exist in `base-java` (`BufferedStreamConsumer` and `BufferingStrategy`). This causes issues now that the buffer needs to be aware of _how_ buffered data is flushed and written to the destination storage in an async world

The goal of this change is to bundle the coupled components into the same package/folder _and then_ break the package into an `old` and `new` version which would be representative of `sequential` and `async` respectively

What this also unlocks is the ability for users to create a better interface for _how_ JDBC destination connectors should be built. The problems we see right now are that buffers are coupled with _how_ a destination connector loads data, which tables are created, deleted, truncated, and causes difficulty upgrading functionality without affecting other connectors. While this change will _not_ completely decouple the connector buffer/state management changes it will allow for an easier path to move JDBC connectors one at a time to async reading/writing

# How
1. Move `connectors:destination-jdbc` modules into `bases` folder
2. Version the aggregated `base-java` into `new`/`old` or `sequential`/`async`

## Definition of Done
1. All 16 connectors that use `destination-jdbc` should be able to pass integration tests (or if already failing to fail on same tests)

**Comment by evantahler** [comment]
Grooming:

* We don't need to republish connectors
* We do need to run integration tests to make sure things still work
