### ISSUE TITLE
Disable connector OAuth buttons in workspaces with OAuth parameter overrides

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#25088]
Some workspaces have OAuth parameter overrides that take precedence over the default Airbyte OAuth parameters for specific source definitions. In these workspaces, using the UI to do OAuth authorization in the connector form will not work for that specific source definition:

![image](https://user-images.githubusercontent.com/7550957/231274090-81d661de-a99b-4c52-910b-99fd9c3e7a1a.png)

Instead of having this footgun in the UI, we should instead disable OAuth buttons in the connector form for source definitions in workspaces where OAuth parameter overrides have been set up.

Slack context: https://airbytehq-team.slack.com/archives/C044QMHSLKT/p1680895289552369

**Comment by flash1293** [comment]
@JonsSpaghetti @josephkmh Am I understanding correctly that there is no indication in the spec / source configuration that there are oauth overrides going on?

I can see two approaches how to handle this:
* Adding a new property `oauth_override: true` to the `api/v1/destinations/get` / `api/v1/sources/get` endpoints to tell the UI oauth is handled downstream (we could render a disabled button and some message or so.
* We already have logic in place to change the spec per workspace / actor via `api/v1/destination_definition_specifications/get_for_destination` / `api/v1/source_definition_specifications/get_for_source` - what about keeping this logic serverside and changing the spec of the connector that receives oauth overrides server-side to completely exclude the authentication section for these workspaces?

I would prefer the second one as this logic is already in place client side and would allow the frontend to be oblivious to this particular bit of business logic. However I might miss something here - @pedroslopez do you think this would be a good use of the `api/v1/destination_definition_specifications/get_for_destination` / `api/v1/source_definition_specifications/get_for_source` endpoints?

**Comment by JonsSpaghetti** [comment]
@flash1293 You're correct, there is no indication in the spec/source config that there are oauth overrides for a given source.

I think either of your bullet points make sense, it might make more sense to do this on the backend given our discussion today around needing to be able to hide this not only in the cloud UI but also in the PbA UI.

**Comment by JonsSpaghetti** [comment]
@pedroslopez had a good suggestion for the above ticket which is to return a 404 from get_consent_url if OAuth param overrides are set for the workspace & source definition so that we display the generic "connector.oauthCredentialsMissing": "OAuth login is temporarily unavailable for this connector. Please try again later.", message.
He also pointed out we can return a more specific status or message if we want but right now volume is low enough the existing message should be fine

**Comment by JonsSpaghetti** [comment]
@flash1293 If you have no objections about the above, feel free to just reassign this ticket to Platform Enablement & assign it to me

**Comment by josephkmh** [comment]
That sounds good to me 👍

**Comment by flash1293** [comment]
@JonsSpaghetti 

> a good suggestion for the above ticket which is to return a 404 from get_consent_url on the backend if OAuth param overrides are set for the workspace & source definition so that we display the generic "connector.oauthCredentialsMissing"

I think the hidden fields for oauth (e.g. `access_token`) are set as required in the spec - are they filled with the "*****" string in this scenario? If not the UI will block the user from submitting. If the "*****" is present then I agree that this is a simple stopgap solution
