### ISSUE TITLE
Source SurveyMonkey: Stream Surveys always perform a full sync.

### ISSUE THREAD

**Issue by leo-schick** [airbytehq/airbyte#25111]
## Environment
- **Airbyte version**:  0.42.0
- **OS Version / Instance**: Debian GNU/Linux 11 (bullseye)
- **Deployment**: Docker
- **Source Connector and version**: SurveyMonkey 0.1.15 (current version)
- **Destination Connector and version**: Azure Blob Storage 0.1.6
- **Step where error happened**: Sync job

## Current Behavior
The stream `surveys` can be setup with sync. mode `Incremental | Append`. But when looking into the source code, it clearly shows that a full sync. is executed everytime you call it:

* class `Surveys` is based on `SurveyIDSliceMixin` which calls the internal stream class `SurveyIds` in the method `SurveyIDSliceMixin.stream_slices` with parameter `sync_mode=SyncMode.full_refresh`. See [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-surveymonkey/source_surveymonkey/streams.py#L158)

## Expected Behavior
I would expect the stream `surveys` either perform actually an incremtal sync. or do not provide the option to sync. incremental at all.

There would be then two possible options I have in my head to fix this:
1. disable incremental sync. for stream `surveys` by changing the base class from `SurveyIDSliceMixin, IncrementalSurveymonkeyStream` to `SurveyIDSliceMixin, SurveymonkeyStream`. I guess this is not preferred because the Source SurveyMonkey is already in General Availability and this option would be a breaking change...
1. Implement incremental sync. for stream `surveys` e.g. by using the incremental sync. mode [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-surveymonkey/source_surveymonkey/streams.py#L158). I did not test if that really then works as expected...

## Logs
/

## Steps to Reproduce
 /

## Are you willing to submit a PR?
No. I don't see currently any benefit for me fixing this

**Comment by lazebnyi** [comment]
@leo-schick Thank you for conducting the investigation. But the Survey API consists of two endpoints: `/survey` returns basic information without any `datetime` fields, and `/surveys/{survey_id}/details` provides detailed information with `datetime` fields. To accommodate the incremental sync functionality, we have implemented a process that initially functions as a full refresh. However, if the user selects the incremental option, the survey stream applies filtering based on the cursor field, effectively transforming the process into an incremental sync.
