### ISSUE TITLE
Orval does not pick up changes to declarative_component_schema locally

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25134]
To reproduce:
1. Check out current master branch of `airbyte-platform-internal`
2. Modify the `oss/airbyte-webapp/src/services/connectorBuilder/connector_manifest_openapi.yaml` file so that the last line says `$ref: "../../../build/declarative_component_schema-0.33.1.yaml". This will force orval to generate the typescript for version 0.33.1 of the schema.
3. In the `/oss/airbyte-webapp` directory, run `CDK_VERSION=0.33.1 pnpm run generate-client` to generate the typescript. In this version (0.33.1), there is correctly no `SingleUseRefreshTokenOAuthAuthenticator`, as that gets added in 0.34.1, so you shouldn't see that in the `oss/airbyte-webapp/src/core/api/generated/ConnectorManifest.schemas.ts` file that orval generated.
4. Undo the change to `oss/airbyte-webapp/src/services/connectorBuilder/connector_manifest_openapi.yaml`, and run `CDK_VERSION=0.33.1 pnpm run generate-client` one more time. The generated file should still look the same as before since `build/declarative_component_schema.yaml` will have been set to the 0.33.1 version.
5. Now, run `CDK_VERSION=0.34.1 pnpm run generate-client`
    - If you look at the command line output, you can see it say `ConnectorManifest.ts is up-to-date`, even though the `../../../build/declarative_component_schema.yaml` file referenced in `connector_manifest_openapi.yaml` was updated to the 0.34.1 version
    - If you search for `SingleUseRefreshTokenOAuthAuthenticator` in the generated `oss/airbyte-webapp/src/core/api/generated/ConnectorManifest.schemas.ts`, you will see that it does not exist which is unexpected

What seems to be going on here is that orval uses the contents of the `connector_manifest_openapi.yaml` to decide if it needs to re-generate any typescript, and since that file did not actually change between steps 4 and 5 (only the _referenced_ file changed), orval doesn't think it needs to regenerate anything so it doesn't try.

This means that simply running `pnpm generate-client` or `pnpm start` will not actually pick up any declarative component schema changes, which is confusing for local development.

This problem doesn't seem to affect cloud, since it generates all these files from scratch every time.

**Comment by lmossman** [comment]
A couple of ideas for how to solve this:
- Make `load-declarative-schema.sh` actually modify the `connector_manifest_openapi.yaml` file to include the version number, but that feels bad because that means it is modifying files that are checked into git
- Make `load-declarative-schema.sh` add the openapi structure around the declarative component schema, so that the output file of the script is a valid openAPI spec, and just have orval point to that build output file

**Comment by timroes** [comment]
At that point I'd like to maybe open the discussion if we just remove the caching of the orval generation. Generation takes (on my machine) 2.5s. Given we have seen multiple times this not working properly while we change things around generation, and the caching logic is growing more and more complex () I personally would prefer adding 2.5s to start up time, over trying to extend all that logic around generation more and more (which ultimatively also makes it harder to maintain eventually). Also cc @ambirdsall since I know he build that and had stronger feelings than me around caching this, so would appreciate your opinion, given the amount of edge-cases we need to handle by now to keep this working.

**Comment by flash1293** [comment]
+1 for removing the caching

**Comment by lmossman** [comment]
Removing makes sense to me, it feels hard to solve every edge case in this caching mechanism and feels like it may end up being more effort than it is worth
