### ISSUE TITLE
Source Clickhouse: Enable dbt normalizations

### ISSUE THREAD

**Issue by riyandharne-123** [airbytehq/airbyte#25147]
## Tell us about the problem you're trying to solve
I am trying to use dbt transformations with myql as the source and clickhouse as the destination.

## Describe the solution you’d like
I would like to use dbt transformations with clickhouse

## Describe the alternative you’ve considered or used
tried using the older versions but did not work

## Additional context
this feature was enabled in the older versions

**Comment by snikch** [comment]
Related:

Historic request closed as completed (which it isn't) https://github.com/airbytehq/airbyte/issues/9522
PR for this, closed without explanation: https://github.com/airbytehq/airbyte/pull/10550

**Comment by nailele** [comment]
Hello, any update on when would custom dbt transformation be enabled for clickhouse destination?
We would need this feature.

**Comment by snikch** [comment]
FYI @nailele we've ended up using Dagster in combination with Airbyte to solve this problem in the meantime. It's quite a nice solution.

**Comment by john9x** [comment]
Why DBT custom transformations still unavailable for clickhouse ?
