### ISSUE TITLE
Incorrect value for `order` field for `Square` source connector specification.

### ISSUE THREAD

**Issue by whereistejas** [airbytehq/airbyte#25158]
https://github.com/airbytehq/airbyte/blob/23c9a299e5d7e247dbff120f36869f496755a320/airbyte-integrations/connectors/source-square/source_square/spec.yaml#L70

This value should be `order: 2`?
The comma in the value, causes the `order` field to be interpreted as string instead of an integer, invalidating the type constraints.

**Comment by erohmensing** [comment]
@whereistejas seems legit to me. Would you be willing to open a PR to fix it? 

Curious, where are you seeing the validation fail?
