### ISSUE TITLE
Gracefully handle backwards incompatible connector upgrades

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2516]
## Tell us about the problem you're trying to solve
If a new version of a connector contains a backwards incompatible change, the Ui/API will happily let the user upgrade to that connector version without prompting them to reconfigure the connector.

We have two ways around this: 

1. release a new connector definition for each backwards incompatible change (basically prevent major version semver bumps)
1. prompt the user to re-enter their configuration before. The UI can handle this completely by comparing specs and diffing required fields, reprompting if there are new ones. 
2. Create a mechanism in SAT/DAT which prevents backwards incompatible spec changes to connectors altogether, as a stop-gap. This is covered in #14097

I think in the long-run we'll want number 2, but it is not urgent if we apply 1. Right now we don't strictly apply either of them (it's a case-by-case thing)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368219462441) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
It seems like one piece of metadata we are missing in general is that a connector should not only specify its current version but what versions of airbyte it is compatible with.

**Comment by davinchia** [comment]
Is my understanding correct that a change is backwards compatible if 1) an existing field is renamed? 2) a new required field is added?

How are connector versions coupled to Airbyte core versions? The only thing I can think of is normalisation?

**Comment by cgardens** [comment]
> Is my understanding correct that a change is backwards incompatible if 1) an existing field is renamed? 2) a new required field is added?

Yeah. That's how I think about it davin.

> How are connector versions coupled to Airbyte core versions? The only thing I can think of is normalisation?

right now it's totally decoupled.

**Comment by davinchia** [comment]
@sherifnada I think this is still an open issue. can you confirm?

**Comment by grishick** [comment]
Here's the issue with more context: https://github.com/airbytehq/airbyte/issues/5396

**Comment by sherifnada** [comment]
closing in favor of #5396
