### ISSUE TITLE
Setup recurring billing for Dagster

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25165]

**Comment by bnchrch** [comment]
@evantahler Whats the process for setting up recurring billing? I looked in notion but came up empty handed

**Comment by evantahler** [comment]
I'll figure it out! make me an admin

**Comment by bnchrch** [comment]
Already are :)

**Comment by bnchrch** [comment]
Hmm so this may be a good question for the Dagster channel

But in the absense of a chat from them, lets assume polling time IS compute time.

Which reading their FAQ I bet thats true

![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/173b7755-6f5b-4f33-921d-2b507744cd56)

Above is a breakdown that shows catalog gen will likely cost $18 a month. Where as nightly orchestration $10,800

But! Theres a silver lining here.

@alafanechere  and I were already discussing that perhaps the nightlies work as so

1. A cron schedule triggers them (Github action or Dagster)
2. airbyte-ci (Dagger) is the "orchestrator" here
3. When done, writes the test results to GCS
4. Dagster is watching GCS for new test results to appear and writes any report needed.

This should bring the worst case pricing back down to single digits.

**Comment by evantahler** [comment]
Closing the issue because I've added a payment method... but we still should sort out our usage :D 

Note: I'm the billing contact now for Dagster
