### ISSUE TITLE
Set a default timeout in standard tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2517]
## Tell us about the problem you're trying to solve
If there is an infinite loop in one my methods, I would like standard tests to short circuit and print some helpful output. Additionally, I would to be able to set the timeout on standard tests to make it configurable (some tests should take 5m some should take 30m). 

## Describe the solution you’d like
A default timeout for standard tests which can be overridden by the user. These two things can be delivered as separate increments.

**Comment by keu** [comment]
We can implement a timeout check during our loop of reading output from docker. if we reach the maximum allowed time we stop with `pytest.fail("Timeout")`.

Another possible option could be using plugin like https://pypi.org/project/pytest-timeout/.

Dev estimation is 2h

**Comment by keu** [comment]
implemented in #2792
