### ISSUE TITLE
Export connectors.md information file to GCS for data team

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#25190]
## Tell us about the problem you're trying to solve
I would like to map GitHub oncall issues to specific connectors. 
The best way to do this is by mapping the GitHub label to a connector id. 

## Describe the solution you’d like
@evantahler Has created this mapping [here](https://github.com/airbytehq/airbyte/blob/master/connectors.md) 🎉 
(Thanks Evan!)

The next step is to export this file, possibly as json, to a GCS bucket so that we can use it in the data warehouse.
Ideally, the GitHub label could be an attribute on the Connector Metadata json file that we already have in the warehouse.
Open to any other ideas here!

## Describe the alternative you’ve considered or used
We've tried parsing the GH label and joining on connector name, but it is not reliable. 

## Additional context
The primary use case is for tracking connector issues on a dashboard that @AnilEMaharjan  is working on

**Comment by evantahler** [comment]
This is blocked by a few other metadata stories, but we will get to this in Q2

**Comment by alex-gron** [comment]
Thanks!

FYI - Another pattern we used recently is to just ingest a file via the Airbyte file connector into BigQuery. 
That may be another option here if it doesn't make sense to add this info to the metadata file.

**Comment by AnilEMaharjan** [comment]
I have another use case for this data that came up today. It is specific to
GL prioritization work so I'd love to try to make this work in the near
term!
