### ISSUE TITLE
How do you rerun failed connector tests with dagger?

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25216]

**Comment by alafanechere** [comment]
Pipelines will be retriggerred if you: 
* Push a new commit to the branch
* Close/Reopen the PR
* Pass the PR from draft to ready for review

A cool trick to write an empty commit: `git commit --allow-empty -m "Empty-Commit"`

I think its a good enough solution. If pipelines are failing transiently it's our job to make fix it and I'd prefer to take a fix first approach and not expose other manual easy way to re-run a failed pipeline.
