### ISSUE TITLE
Tell alpha/beta users how to enable free (FCP) connections

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#25219]
A user is not able to enable any syncs if 1) the trial period is over and 2) they are not enrolled in FCP.

Suggestion to tell users explicitly that if they want to enable Alpha/Beta connections, they need to enroll in FCP or purchase credits.

https://www.loom.com/share/54829b9684824ddea29bd04df623f637

**Comment by ambirdsall** [comment]
I think that the messaging about this error case either needs to go in the free connector program enrollment banner or in an inline dialog to be rendered directly under the toggle when re-enabling the connection fails: the credits banner across the top is just completely outmatched in terms of visual importance.

**Comment by tealjulia** [comment]
One point I don't think we discussed in refining:

What should we do about users who fit that criteria and are creating their first non-GA connection?  It would be nice to somehow indicate to them "hey, we're going to disable this and it won't run its first sync when you hit save... you should go buy credits!" (though, be mindful that if we navigate users away from and back to the replication step, the schema would need to be re-fetched and any configuration a user had started would be cleared)

**Comment by josephkmh** [comment]
Refining notes:

- We don't know why connections have been disabled, so it is currently very difficult to know _why_ a user might not be able to enable a connection
- To push this forward, we need to start storing the reason why a connection has been disabled (out of credits, failed too many times, user disabled, etc)

**Comment by nataliekwong** [comment]
Closing as we're ending FCP
