### ISSUE TITLE
Source Postgres: connector should support SSL cert & client key when configuring with `require` SSL mode

### ISSUE THREAD

**Issue by emily-flambe** [airbytehq/airbyte#25234]
## Tell us about the problem you're trying to solve

I need to include an SSL certificate and private key when configuring a Postgres source connector in `require` mode. Currently this is not supported, and it should require a very straightforward change (see below).

## Describe the solution you’d like

[This gist](https://gist.github.com/dannyboy15/4f11c9bd037565f442008b0d1b158328) shows the patch (all credit to @dannyboy15 !) used to successfully implement this change in his local Airbyte deployment. It seems like a very simple modification to a spec file. See also this screenshot he shared from when he got the connector running with this configuration:

 ![image](https://user-images.githubusercontent.com/47834372/232324867-b43f6e84-49f6-4f6d-8684-2321daa40eb1.png)

## Describe the alternative you’ve considered or used

N/A at this time.

## Are you willing to submit a PR?

I am unfortunately not set up to do Java-based development. If this is not something Airbyte will be able to implement within the span of a couple of months, then I would be willing to try and figure out submitting a PR myself, though I am hoping someone with the right setup will be able to submit a PR with much less effort.

**Comment by prateekmukhedkar** [comment]
@emily-flambe sorry for the delay in acknowledging this issue. Can you use `verify-full` in SSL mode dropdown when setting up the Postgres source connector? From the [documentation](https://docs.airbyte.com/integrations/sources/postgres/#step-2-set-up-the-postgres-connector-in-airbyte):

`verify-full to always require encryption and verify the identity of the source`

**Comment by stephane-airbyte** [comment]
this has been completed a while ago. No answer from customer. Closing
