### ISSUE TITLE
Measuring throughput of connectors

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2524]
## Tell us about the problem you're trying to solve
We have no/little visibility on the throughput of our connectors. 

## Describe the solution you’d like
Add properties duration / volume_rows / volume_MB for Connector Jobs when job_type=SYNC. 

Here's the updated Segment spreadsheet: https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

**Comment by johnlafleur** [comment]
Actually, I wonder if we shouldn't have a property to indicate whether it's a full refresh or an incremental sync. 
The 1st sync of an incremental refresh would then be a full refresh.
But as we can set up full refresh/incremental differently according to the tables, maybe that doesn't make sense. And we're computing throughput. Any thoughts on this @cgardens ?

**Comment by ChristopheDuong** [comment]
Note that DBT exposes statistics after being ran in a json file too.
So these could also be picked up and send along after normalization step (to separate it from the destination connectors writing the raw tables)
See https://docs.getdbt.com/reference/artifacts/run-results-json

**Comment by cgardens** [comment]
it's a good point. there was something lingering in the back of my head about why this was hard but it wasn't coming to me on monday.

what would it take to do throughput separately for source and destination? @sherifnada this actually might be easier if we went with the idea you were describing of moving the queue into the worker. then we could separately track throughput of records being written to the queue and consumed by the queue to make these stats more granular.
