### ISSUE TITLE
Destination S3 Parquet: can't handle with BigInt Date Types

### ISSUE THREAD

**Issue by cesar-loadsmart** [airbytehq/airbyte#25243]
Hey folks! 

I'm currently replicating data from a Postgres DB to S3 parquet using Airbyte. My problem is, the source database uses epoch timestamp with milliseconds (**bigint as data type)**, for instance: 
**_1648218655338_**
Becames:
**_Friday, March 25, 2022 2:30:55.338 PM_**

When replicating those **Integer date fields**, Airbyte uses int8[19] as shown below:
![image](https://user-images.githubusercontent.com/89807801/232524034-f573230d-ac84-4986-bb38-a471db846178.png)

Which should be able to handle my epoch timestamp: 
![image](https://user-images.githubusercontent.com/89807801/232524286-c68185da-2c8e-43ce-ac7f-3bad4bdd81ad.png)

But for some reason I'm losing accuracy, as shown below: 
* Source DB: 
![image](https://user-images.githubusercontent.com/89807801/232528573-e9b03ff5-88fe-4023-bc2b-20732ec3c2c2.png)

* Same record replicated via Airbyte to Parquet: 
 ![image](https://user-images.githubusercontent.com/89807801/232527801-8fbe7f1f-d33e-472e-b5f5-18f9ea7b0f5d.png)

* However, when using the same source but writing to CSV it works: 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/89807801/232532194-ec3ebb19-557b-4481-9cdf-a5a662a1e66f.png">

## Environment
- **Airbyte version**:  0.41.12
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes Deploy
- **Source Connector and version**: PostgresDB 1.0.42
- **Destination Connector and version**: S3 Parquet 0.3.23
- **Step where error happened**:  Sync job 

## Current Behavior
Airbyte replicates the data but loses accuracy for the epoch timestamps fields: 
![image](https://user-images.githubusercontent.com/89807801/232527801-8fbe7f1f-d33e-472e-b5f5-18f9ea7b0f5d.png)

## Expected Behavior
It should replicate the records with consistency as it exists at the source:
![image](https://user-images.githubusercontent.com/89807801/232528573-e9b03ff5-88fe-4023-bc2b-20732ec3c2c2.png)
And as it happens for CSV destination: 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/89807801/232532194-ec3ebb19-557b-4481-9cdf-a5a662a1e66f.png">

## Logs
[26204905_8ef0_47c4_a86a_a3e8cc3950aa_logs_42105_txt.txt](https://github.com/airbytehq/airbyte/files/11251946/26204905_8ef0_47c4_a86a_a3e8cc3950aa_logs_42105_txt.txt)

## Steps to Reproduce
1. Create a source Postgres DB
2. Create a table with at least one bigint field for epoch timestamps with milliseconds precision
3. Create a connection to move this data to S3 Parquet Destination (I'm not using any codec compression)
4. Download the generated parquet ( at this moment you will different numbers) 
5. Try to convert the same field back to human readable date format 
6. You should see a totally different date

## Are you willing to submit a PR?
Sure! I can try!

**Comment by the4thamigo-uk** [comment]
We are suffering from this issue also

**Comment by evantahler** [comment]
This should be fixed with the 1.0 version of the destination-s3 connector.
