### ISSUE TITLE
Noindex the https://status-api.airbyte.io/tests/summary/.... pages

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2525]
## Tell us about the problem you're trying to solve
All the pages https://status-api.airbyte.io/tests/summary/... are being indexed by Google right now, which takes on our crawling quota. We should put them in noindex.

This is a very low priority task.

**Comment by jrhizor** [comment]
This is probably just putting a `User-agent: * Disallow: /` robots.txt file in the root of the bucket.

**Comment by jrhizor** [comment]
https://status-api.airbyte.io/robots.txt is live (I just created and uploaded to S3).

Tested https://status-api.airbyte.io/tests/summary/source-github-singer/ with the Googlebot on https://technicalseo.com/tools/robots-txt/ and it shows as disallowed.
