### ISSUE TITLE
RESTful API Source needed

### ISSUE THREAD

**Issue by adymilk** [airbytehq/airbyte#25262]
Hi there, I want to connect RESTful API Source ,Can you support a standard generic source with RESTful API？

**Comment by girarda** [comment]
Hi @adymilk, we do not have a generic source. We recommend using the [connector builder](https://docs.airbyte.com/connector-development/connector-builder-ui/overview) or the [low-code CDK](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview) to implement a connector for a RESTful API
