### ISSUE TITLE
Cannot save changes because the webhook test failed. Please verify that the webhook URL is valid | settings>notifications

### ISSUE THREAD

**Issue by amjadseera** [airbytehq/airbyte#25266]
## Environment
- **Airbyte version**:  0.42.1
- **OS Version / Instance**: AWS EC2 EKS NODE
- **Deployment**: Kubernetes deploy env
- **Source Connector and version**: N/A
- **Destination Connector and version**: N.A
- **Step where error happened**: Airbyte notification settings

## Current Behavior
*Tell us what happens.*
i'm trying to configure webhook in settings>notification settings>webhook url 
I get an error saying that the webhook test failed
Note: this is a working webhook and tested it with using curl commands
<img width="1720" alt="Screen Shot 2023-04-18 at 12 18 38 PM" src="https://user-images.githubusercontent.com/121865927/232718821-d2c1f39c-5923-4bbf-9794-3b7d1f31835c.png">
## Expected Behavior
*Tell us what should happen.*
it should test and save the webhook
## Logs
since the error seems to be completely from the frontend. no logs are there

## Steps to Reproduce
1. open airbyte console
2. navigate to settings> notifications settings
3. enter the webhook url and click on test

**Comment by Ytipytiman** [comment]
I have the same problem on version v0.43.1.
After i upgrade version to v0.44.1 problem is gone.

**Comment by amjadseera** [comment]
thanks @Ytipytiman i will try this

**Comment by davinchia** [comment]
Closing since this seems resolved.
