### ISSUE TITLE
Notion OAuth requests by employee

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#25265]
When a user tries to Authenticate via Okta for the Notion source, they are presented with this popup modal:

![Screenshot 2023-04-17 at 10 42 00 PM](https://user-images.githubusercontent.com/38087517/232681734-fcd576d6-8486-4c33-8c6d-2053bbe70d12.png)

This refers to an employee that no longer works at Airbyte. Ideally this would be migrated to use Airbyte as the requestor, not the individual employee. 

cc @bmcgilli

**Comment by nataliekwong** [comment]
@sherifnada are we okay to close this now that it's migrated to a common email?

**Comment by sherifnada** [comment]
this was fixed!
