### ISSUE TITLE
Hubspot Source Failing to sync successfully into Snowflake

### ISSUE THREAD

**Issue by stammi922** [airbytehq/airbyte#2527]
## Expected Behavior
Connected the Hubspot Source to Airbyte. Using the HAPI-key.
Connected Snowflake Destination, double-checked all the permissions necessary for the role. 

## Current Behavior
The connection makes 3 attempts, but all of them seem to fail.
Some data is being synced, but all the deal history data is not being shown. In particular when checking the retrieve fields in Snowflake that should show `PROPERTY_HS_TIME_IN_******` 

## Logs
[error_log.txt](https://github.com/airbytehq/airbyte/files/6171820/error_log.txt)

## Steps to Reproduce
1. Host docker version on GCP
2. Setup Hubspot Source Connector
1. Setup Snowflake Destionation 

## Severity of the bug for you
Medium

## Airbyte Version
0.15.0-alpha

## Connector Version (if applicable)
0.2.0

## Additional context
* Google Cloud 
* Happed to localhost `gcloud beta compute ssh airbyte -- -L 8000:localhost:8000 -L 8001:localhost:8001 -N -f`

**Comment by ChristopheDuong** [comment]
Hello @stammi922,

Could you please try to upgrade your Airbyte instance to 0.17.2-alpha and try again?
You can follow instructions here: 
https://docs.airbyte.io/tutorials/upgrading-airbyte

Especially there was significant work made on the normalization step (where your sync is failing) in version 0.16.0.

Thanks

**Comment by stammi922** [comment]
Hi @ChristopheDuong,
We could update our Instance, which fixed the failing sync. What it did not fix is the fact that some data is missing that is associated with the `Deals` entity. 
What version of the Hubspot API is being used? Because I can see that the history parameter should be set on the API request in order to get the full trace for a Deal transferred. I am specifically validating the data arrival by looking at the table that is successfully created by Airbyte. `select * from "HUBSPOT_AIRBYTE"."HS_TIME_IN_QUALIFIEDTOBUY"`

I am sure we have deals that have moved past that stage, but the table remains empty. 
Other non-dealhistory related fields have successfully been transferred.

Do you have any hints?

**Comment by ChristopheDuong** [comment]
Can you post new logs and indicate which hubspot connector / version is this?

We've recently published new hubspot work as you can see on these issues: https://github.com/airbytehq/airbyte/issues/2114

**Comment by stammi922** [comment]
Sure here is the log file, just with our hapi-key anonymized.
[logs-32-0.txt](https://github.com/airbytehq/airbyte/files/6237356/logs-32-0.txt)

**Comment by sherifnada** [comment]
@stammi922 glad to hear the upgrade fixed the issue! Can you point us to the endpoint in the Hubspot API which provides deal history?
