### ISSUE TITLE
Create in-app survey for feedback

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#25294]
We want to gather user feedback on the stream centric ui.

**Comment by timroes** [comment]
cc @nataliekwong just wanting to make sure, this is no overlap on what you're working on, and rather the issue to track your work on the feedback survey in the UI (since it's assigned to Chandler atm?)

**Comment by nataliekwong** [comment]
Thanks @timroes ! Chandler and I are coordinated on this. I built the survey and published the first version but Chandler has access to Chameleon if he wants to make any edits / improvements.
