### ISSUE TITLE
Connector builder: Allow to revert draft to latest released version

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#25322]
When working with the connector builder I often find myself in the situation that I want to test around a bit, but right now that's always "dangerous" because it auto-saves the draft and there is no easy way to get back to the previous state.

Having proper undo/redo would solve the problem as well but is pretty large in scope while adding a "revert draft to released version" dropdown in the UI is simple to do and would provide a big part of the value

**Comment by lmossman** [comment]
@lmossman to ask Nico about the last point

**Comment by Upmitt** [comment]
@lmossman I would not introduce an 'unsaved" state - I think the most important in what @flash1293 describes is to let users load a specific version when they want, so they can do some tests but easily load the initial version if the tests are not concluant. What is important in that case is to let them know the actual draft will be lost (I suggest the Warning message in the modal). Then we have 2 ways of doing it, the actual draft can be lost as soon as the user loads a version, or as it is in [this video](https://www.loom.com/share/c921f2327c3c464399671a739a5dd580), the draft can be overwritten as soon as the user load a version and do a first modification.

**Comment by flash1293** [comment]
Works for me
