### ISSUE TITLE
Better UX when importing the schema

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25321]
## Context
As identified in the most recent Build-a-connector session, the UX around importing a schema has some areas that can be improved:
- Its not clear what is happening when you import from the testing panel, since the only thing that changes is that the Import button goes away, unless the user happens to already have the Declared Schema tab open
- Users always have to manually import schema changes, which can be cumbersome as the schema continues to change while they are developing the connector
- Detected schema sets fields to `null` if that is the only value seen for these fields in the response, which is likely incorrect and is easy for the user to miss

## Acceptance Criteria
- Users are only asked to review the schema when publishing. If the schema of a stream has not changed since the last publish, exclude that stream from this "review" step
- Detect when a stream is "dirty" (i.e. has not been tested since changes were made to it), and prevent publishing if there are any dirty streams
  - Alternative: run the tests on the dirty streams with the current testing values 
- When reviewing a stream with a changed schema, require the user to change the type of any fields which were detected to be `null` type
- Add link to schema docs page somewhere in the new "review" component

**Comment by lmossman** [comment]
Grooming notes:
- Allow users to toggle between "Automatic detection" and "Manual" mode, default to Automatic
- If there is a field that can't be inferred (e.g. `null`), force the mode to be manual
- When publishing, if any stream has not done a test read, we run the test read for them and update the schema if in automatic mode

- Alternative: Only ask the user to review the schema when they are publishing. If the schema hasn't changed since the last publish, ignore that stream during this step.
  - Use the last detected schema from the last test read
  - Detect if a stream has not been tested since the last time a change was made to it - if so test the stream on publish or have an error on the publish button requiring the user to test before publishing

**Comment by lmossman** [comment]
Grooming notes:
- The above approach is fairly high effort and introduces several new concepts
- A more incremental approach to get most of the value here would be the following:
  - Default to automatically import the detected schema as the declared schema (store a flag in the schema, e.g. `automatic_detection: true`), but allow the user to manually edit the schema as well by switching this automatic mode off
  - On publish, detect if the new schema of a stream is incompatible with the schema from the last published manifest. If so, warn the user that this will cause issues in the destination if they just publish.
  -  Ignore the `null` type fields, i.e. don't include them in the schema

**Comment by lmossman** [comment]
I have tested out the case where some records returned by the API have `null` value for some field, while other records have a string value for the same field. I tested setting the type of this field in the schema to each of the following:
- `"type": "null"`
- `"type": "string"`
- `"type": ["null", "string"]`
- removed the field from the schema completely

For each of those tests, I synced the records to an empty postgres database, and in every case the type of the column was set to `jsonb` and the null/string values were persisted and normalized without issue.

Therefore, my conclusion is that leaving the column type set to `null` even if some records can have strings won't cause huge issues, since our normalization logic seems to ignore the type in the schema in this case and just set the destination column type to `jsonb` regardless.

**Comment by lmossman** [comment]
Design: https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3589%3A124527&type=design&node-id=4409-141994&viewport=1732%2C27%2C0.5&scaling=contain&starting-point-node-id=4409%3A141994&show-proto-sidebar=1

**Comment by flash1293** [comment]
Quick comment: the 
> Omit the null types from the auto-detected schema

part is done as part of the general “improve scheme detection” issue
