### ISSUE TITLE
New Source: Twitter tweets

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2535]
## Tell us about the new integration you’d like to have
I would love to be able to use Airbyte to pull data from Twitter for analysis. Typically I would look for questions in a particular tag or topic (e.g: if I want to keep track of issues related to Airbyte) 

Note this is NOT for Twitter Ads -- it is for the "normal" twitter API to pull tweets

## Describe the context around this new integration
Various applications need to scrape social media to perform studies, aggregation, or sentiment analysis. Usually, this must be done by writing a custom client. But I would love for it to "just work"

## Describe the alternative you are considering or using
Writing my own

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368155136309) by [Unito](https://www.unito.io)

**Comment by cheyura** [comment]
`Integration Vetting`
Webhook-based? (no/partially/yes)
No

Available authentication modes (API key/Oauth/other)
API keys - for own Twitter Ads Account (single account use case)
OAuth - to use another Twitter Ads Account

CONSUMER_KEY = 'your consumer key'
CONSUMER_SECRET = 'your consumer secret'
ACCESS_TOKEN = 'access token'
ACCESS_TOKEN_SECRET = 'access token secret'
ACCOUNT_ID = 'account id'
By default, each Twitter developer application contains a static access token that can be used to make Ads API requests for the account that owns the application. These credentials are ideal for single-account use cases without requiring a 3-legged or PIN-based OAuth flow. If you aren't accessing another Twitter Ads Account, use these single-user credentials

Creating an account
Require these steps:

Twitter Developer account (require approval) https://developer.twitter.com/en/apply-for-access
Apply for access to the Ads API (require approval) https://developer.twitter.com/en/docs/twitter-ads-api/apply
Has Sandbox environment ?
Yes. https://developer.twitter.com/en/docs/twitter-ads-api/ads-api-sandbox

How to populate the account with data?
It can be done through the UI, API, Sandbox API.

Available streams for sync
https://developer.twitter.com/en/docs/twitter-ads-api/api-reference-index

Integration supports incremental sync?
Yes, API has pagination support , so it's possible to save cursor id for future use
https://developer.twitter.com/en/docs/twitter-ads-api/pagination
https://developer.twitter.com/en/docs/pagination

Other information/blockers
Require approval from Twitter to create account.

To perform actions on behalf of another user, you'll need to obtain their access tokens via 3-legged OAuth flow.
https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

Twitter ads account (not sandbox) require payment: https://business.twitter.com/en/help/account-setup/ads-account-creation.html
Billing - https://business.twitter.com/en/help/account-setup/billing-basics/credit-limits.html

API call limits - https://developer.twitter.com/en/docs/twitter-ads-api/rate-limiting
Python SDK - https://github.com/twitterdev/twitter-python-ads-sdk

**Comment by sherifnada** [comment]
@andrewm4894 I think this was closed by accident. reopened it.

**Comment by piyushdatazip** [comment]
Hey @cheyura can you update what's the update here?

**Comment by ycherniaiev** [comment]
**DOCS**
[Twitter API reference](https://developer.twitter.com/en/docs/twitter-api)

**Sandbox Account Creds**
LastPass: Twitter - @AirbyteHQ - for integration tests

*OAuth 2.0 creds*
LastPass: Twitter Public App

**Vetting**
- [ ] #2535 

**MLP**
[Document](https://docs.google.com/document/d/1hB2H6eLwSMw2Upg3rJ3zz_CDyEf5diHi6Q3KC5nLcek/edit#heading=h.22fd5raysmm3)
Partially done (implementation of the Twitter source connector to Alpha needed)
