### ISSUE TITLE
Source Salesforce: converts strings containing only digits into mangled numeric variants before storing again as string

### ISSUE THREAD

**Issue by dancook-doxo** [airbytehq/airbyte#25350]
## Environment
- **Airbyte version**:  Airbyte Cloud
- **Source Connector and version**:  Salesforce 2.0.9, as of today
- **Destination Connector and version**:: Snowflake 0.4.61, as of today
- **Step where error happened**:  reading string columns which appear like numbers

## Current Behavior
We have custom columns in our Salesforce objects (who doesn't?) and sometimes these are string columns containing only digits, with values like "821580693639061174". Unfortunately the Salesforce connector is fooled into thinking these strings are bigints or similar, and what ends up in our warehouse is the _string_ "8.215806936390611e+17". Not only is it wrong to assume this is a number when the source schema explicitly calls out the column as a string, but worse yet some of the characters are truncated from the end when the string is longer than 17 characters, therefore information is lost. This problem happens on both full syncs and incremental/de-dupe syncs.

A similar problem happens with number-like strings which are left-padded with zeros, like a US East Coast ZIP code value of "01234", which ends up in Snowflake as "1234.0". Similarly a string like "000012345" will end up as "12345.0".

## Expected Behavior
A string is a string, even if it looks like a number, and no characters are removed from the string. Also no scientific notation gobbledygook or false decimal representation is appended to the string.

## Steps to Reproduce
1. have a column in a synced Salesforce object which is classified as a string, but put only digits in the value. Example strings are "821580693639061174" and "01234"
2. Sync that object to Snowflake or other CDW, using either full or incremental sync
3. Inspect the string value once it lands in your CDW, notice that it has been run through the "Excel number mangler" and then put back in as a string.

## Business Impact
We are forced to duplicate affected columns in our Salesforce objects, for example a column called "User_ID__c" gets a sibling column called "User_ID_String__c" and this column is nothing more than the data from the original column with a pre-pended apostrophe. The apostrophe (or any character which is not a digit) forces the Airbyte Salesforce connector to properly treat the column as a string. Then when we query over the data we have to remove any pre-pended special character. In addition to the hassle of stripping the apostrophe when querying, this also leads to "schema bloat". Salesforce schema bloat is enough of an out-of-the-box problem without adding gas to that fire.

## Are you willing to submit a PR?
No

**Comment by dancook-doxo** [comment]
It also appears that the Salesforce-to-Snowflake pipeline described above converts the string value "n/a" to NULL. But if "01234" and 1234 are fundamentally different, then certainly "n/a" and NULL are even _more_ different.

**Comment by jeremySrgt** [comment]
I got the same problem with ID's explicitly marked as String in Salesforce :/

Hopefully I will find a fix and submit a PR if i got time

**Comment by jeremySrgt** [comment]
I have submitted a PR to fix the problem: https://github.com/airbytehq/airbyte/pull/25794

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/25794
