### ISSUE TITLE
mongodb source connector hangs at schema detection

### ISSUE THREAD

**Issue by tfriedel** [airbytehq/airbyte#2539]
## Expected Behavior
Adding a mongodb source should take a couple of minutes and then display the collections.

## Current Behavior
Adding a mongodb source, in this case quite a big collection of about 30 million documents and 45 GB results in a long running (~1 hour) map-reduce op on the mongodb that in the end doesn't succeed. I tested it with a much smaller database and here it worked. 

## Steps to Reproduce
1. set up a big mongodb collection 
2. start onboarding with this mongodb db

## Severity of the bug for you
Critical
I won't use airbyte if it can't handle this mongodb source.

## Airbyte Version
0.17.2-alpha

## Connector Version (if applicable)
0.2.0

## Additional context
I tried it with a mongodb server in my LAN. I watched the progress with db.currentOp() and the map reduce operation was taking about an hour and was almost finished, but in the end I got an error "Failed to fetch schema. Please try again". In the docker-compose logs I saw an exception saying the operation was either terminated or a timeout occurred. It might very well be that you have a one hour timeout and it just barely didn't succeed. In any case I think it shouldn't take one hour. 
There might be better ways to infer the schema. See for example tools like https://github.com/mongoeye/mongoeye

**Comment by sherifnada** [comment]
@tfriedel Thanks for reporting the issue! We haven't tested mongo at this scale yet. Unfortunately we don't have the bandwidth to take this on at the moment, but we love contributions if you are interested in creating a PR! LMK and we can talk about next steps.

**Comment by tfriedel** [comment]
sorry I also don't have the time unfortunately.

**Comment by davinchia** [comment]
@tfriedel we recently improved MongoDB schema discovery #2900. do you want to give this another shot?

**Comment by sherifnada** [comment]
Please reopen the issue if the problem persists but I believe it should be good to go now!

**Comment by nathan-protempo** [comment]
I'm experiencing what appears to be the same issue on a Mongodb Atlas database of about 20Gb (M10 cluster), including some collections that have several million records. I can set up and validate the source OK but when trying to create the connection it hangs at the step "We are fetching the schema of your data source" and this process does not complete within any reasonable amount of time. 

Is there a way of skipping this step and manually defining the schema? We already know what it is, so we don't necessarily need Airbyte to discover it.

**Comment by sherifnada** [comment]
@nathan-protempo which connector version are you using?

**Comment by nathan-protempo** [comment]
According to the settings section of the UI, version 0.1.0

**Comment by nathan-protempo** [comment]
It's using the image airbyte/source-mongodb-v2
