### ISSUE TITLE
New integration for airbyte

### ISSUE THREAD

**Issue by ronakbaps** [airbytehq/airbyte#2540]
**Sources** : MSFT Bing Ads, LinkedIn Ads, Zoho CRM, Google Ads
**Destination** : mySQL (AWS RDS), Amazon Aurora, Hadoop/Hive, MongoDB

In absence of these, I would go looking for outside availability. 

## Tell us about the new integration you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**Comment by sherifnada** [comment]
@ronakbaps thanks for creating the issue! We have issues for all the above sources and destinations: 
Linkedin #2589 -- no target date yet, this is the first request
Bing #2508 -- targeting delivery in April
Zoho #2585 -- no target date yet
Google Ads is already available today. 

Destinations:
MySQL #1483 
Aurora #2590 
Mongo #2369 
Hive #1877 

we currently don't have target dates for these destinations yet, but will update the issues with any estimates. Would you be open to contributing on any of these connectors? The easiest way to contribute destinations is in Java, but it can be done in any language.

**Comment by davinchia** [comment]
I'm going to close this issue since relevant issues have been created.

Thanks @ronakbaps !
