### ISSUE TITLE
Connector Issue: Google Ads connector support dynamic start_date

### ISSUE THREAD

**Issue by jerryan999** [airbytehq/airbyte#25414]
### Connector Name

Google Ads

### Connector Version

new

### What step the error happened?

Other

### Revelant information

Google ads connector has a configure field named start_date, does it suppoort given by string statement like {{n_days_ago(7) }}

I would be great to support this feature: statement like {{today_date-days(7)}} to populate the start_date field. We always don't want to query starting from the fixed start_date because it will be inconvenient for daily tasks.

### Contribute

- [X] Yes, I want to contribute

**Comment by tolik0** [comment]
Unfortunately, such an option is not available yet. You can use incremental sync for syncing only new data.
