### ISSUE TITLE
Broken docs link: Admin > Configuration > Export

### ISSUE THREAD

**Issue by ffabss** [airbytehq/airbyte#2541]
## Steps to Reproduce

1. Go to **Admin > Configuration**.
2. Click on on the link [**configuration archive**](https://docs.airbyte.io/architecture/configuration-archive) within **Export**.

![image](https://user-images.githubusercontent.com/37747351/111880857-0b30e280-89ae-11eb-93e0-2f5600171e7a.png)

## Expected Behavior
Some kind of documentation about the configuration should be opened.

## Current Behavior
A **Page not found** message is displayed.

## Severity of the bug for you
Very low

## Airbyte Version
0.17.2-alpha

**Comment by michel-tricot** [comment]
thanks @ffabss for reporting!

@ChristopheDuong, I don't think this page exist anymore. Should it be replaced by something else or should we kill the link from the UI?

**Comment by ChristopheDuong** [comment]
it should be pointing to: https://docs.airbyte.io/tutorials/upgrading-airbyte
