### ISSUE TITLE
Destination Postgres: normalization is slow (CPU-bound, using 1 core)

### ISSUE THREAD

**Issue by ggam** [airbytehq/airbyte#25426]
## Tell us about the problem you're trying to solve

I'm replicating some Oracle tables to Postgres destination. One of them has 160 columns and normalization becomes a bottleneck as Postgres only uses one core to process it. 

Normalizing 930k records took more that 24 minutes:
`2023-04-23 14:38:06 [42mnormalization[0m > 16 of 16 OK created table model xxxx.xxxx................................................................. [[32mSELECT 930527[0m in 1445.07s]`

## Describe the solution you’d like
Postgres won't parallelize the query as it's a full table select, so I guess the easiest solution would be to:
- Convert the raw source table into multiple staging tables, so dbt can execute concurrently.
- Combine the temporary tables into the final one.
- Drop the staging tables

## Describe the alternative you’ve considered or used

If and when https://github.com/airbytehq/airbyte/issues/25194 gets done, that should solve the root problem.

## Additional context
I can privately send the workspace dir and more information about the tables if needed.

## Are you willing to submit a PR?

I don't realistically think I could offer my help on this one.

**Comment by evantahler** [comment]
Closing this issue because normalization as we know it is going away shortly - learn more @ https://github.com/airbytehq/airbyte/issues/26028
