### ISSUE TITLE
Source Github: Support ProjectV2 structure

### ISSUE THREAD

**Issue by MathieuLamiot** [airbytehq/airbyte#25438]
## Tell us about the problem you're trying to solve
Github projects (classic) are being deprecated and now, ProjectV2 structure is used when creating new projects. This allows much more flexibility, but it seems it is not supported yet by Airbyte. Therefore, all projects of type ProjectV2 are not retrieved by the Github connector, which prevents using the data.

## Describe the solution you’d like
The GitHub connector should retrieve the data related to the ProjectV2 structure (including items, fields, etc.) and provide the related streams in Airbyte.

## Describe the alternative you’ve considered or used
Manual implementation of GraphQL queries to access ProjectV2 structure on Github and manually get the data. However, this is poorly integrated.

## Additional context
[ProjectV2](https://docs.github.com/en/graphql/reference/objects#projectv2) from the GraphQL API documentation of GitHub.

## Are you willing to submit a PR?
I'm not skilled enough to contribute :(

**Comment by artem1205** [comment]
added in #30731

**Comment by ball-hayden** [comment]
@artem1205 thanks for the PR adding V2 projects.

Can I check - are items for V2 projects covered?
I can see the stream for `projects_v2`, but this doesn't seem to include any project items?

**Comment by artem1205** [comment]
@ball-hayden,
`items` are not included in this stream.
I feel like`projectV2_items` should be in a [separate stream](https://docs.github.com/en/graphql/reference/objects#projectv2item). I would ask you to create a feature request for this stream.
