### ISSUE TITLE
`Link` component not in tab order

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#25430]
Our `Link` component does not put the `<a>` tag in the tab order.

Example of what our tab order is on a random page:

![Screenshot 2023-04-24 at 11.29.59 AM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/a8e094f8-c2d5-444c-9e0d-833bb419b8fb)

(the navlinks that are shown here as tabbable are dropdowns that have a button as a control)

**Comment by tealjulia** [comment]
@flash1293 looks like they are tabbable in Chrome, but not Firefox.

**Comment by flash1293** [comment]
I see - I looked into this and it seems like this is a mac thing - Firefox respects this setting:
<img width="662" alt="Screenshot 2023-05-22 at 10 55 23" src="https://github.com/airbytehq/airbyte/assets/1508364/5e56ffc4-3ba4-4a70-8a42-48b7d078e84b">

Once you turn it on (it's off by default), links will become tab-able. While this is not super obvious, I think we can file this under "works as expected"
