### ISSUE TITLE
Webapp does not refresh itself after Source name is updated.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2545]
## Expected Behavior
After changing a source's name, I expect the changed name to be reflected in the UI.

## Current Behavior
The name is not reflected. Furthermore, 'save changes' button remains lit, giving the impression no save has occurred. 

However I know this has successfully saved since I see this in the logs:

```
airbyte-server      | 2021-03-22 00:56:13 INFO i.a.s.RequestLogger(filter):107 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.18.0.1 OPTIONS 200 /api/v1/sources/update
airbyte-server      | 2021-03-22 00:56:13 DEBUG i.a.s.c.SpecCachingSchedulerJobClient(createGetSpecJob):58 - {workspace_app_root=/tmp/workspace/server/logs} - cache hit: airbyte/source-postgres:0.2.1
airbyte-server      | 2021-03-22 00:56:13 DEBUG i.a.s.c.SpecCachingSchedulerJobClient(createGetSpecJob):58 - {workspace_app_root=/tmp/workspace/server/logs} - cache hit: airbyte/source-postgres:0.2.1
airbyte-server      | 2021-03-22 00:56:13 INFO i.a.s.RequestLogger(filter):107 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.18.0.1 POST 200 /api/v1/sources/update - {"name":"airbyte-source-test","sourceId":"2f820a5f-953a-41a4-9617-84b58d1e86eb","connectionConfiguration":"REDACTED"}
```

## Steps to Reproduce
1. Navigate to a source in the UI and try to change it's name.

## Severity of the bug for you
 Medium - very obvious something is not working 

## Airbyte Version
0.17.2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368220222091) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
this is an API bug actually.

**Comment by hoanghapham** [comment]
I also encountered this with the latest version

**Comment by sayowayah** [comment]
Just wanted to note that at least for me, the source name doesn't seem to actually update, regardless of the immediate UI feedback. Even after saving, refreshing, and docker-compose down/up, the new source name is not reflected.
