### ISSUE TITLE
Create migration to add a default version for existing actor definitions

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#25453]
As part of the move to using data from the actor_definition_version table rather than actor_definitions to get the necessary fields for running a connector, we'll need to make sure that the data is present in this table for all connectors.

While #25060 should generally resolve this for connectors provided by airbyte (in the bootloader and in cron we would be filling version information and setting default versions at runtime), this does not cover the case for custom connectors that may have been added to the installation.

Because of this, we should add a migration that ensures the data is migrated to this new table. More concretely, we should:
- Look for any actor_definition that does not have a default_version_id set.
- Create an actor_definition_version entry for this actor_definition using the values from the fields present in the actor_definition. 
- Set default_version_id to the version we just created. 

This will affect both custom connectors and those provided in the registry, but it should all work out.

**Comment by evantahler** [comment]
Grooming:
* This migration will land AFTER the update for custom connectors to add their own actor_definition_version.  The migration needs to check if the actor_definition_version already exists or not
* Migration can be done entirely in SQL.. probably.
