### ISSUE TITLE
Add Actor Definition Context to LaunchDarkly

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#25455]
## What

In order to apply feature flags for overriding connector versions, as described in the [Multiple Connector Versions tech spec](https://docs.google.com/document/d/1sMbAN9oumZxswnsyd2rGYwvsfOO4y8EQ_4m-WIs82hI/edit#heading=h.d32qb0f2g2j3), we'll need to be able to target based on the actor definition IDs. These IDs refer to connectors available in our Registry, are stored in the airbyte database's actor_definition table and are referenced internally usually via StandardDestinationDefinition and StandardSourceDefinition.

Since we have a similar internal representation for Source / Destination (actors) and there are already corresponding Feature Flag contexts for these ([Source](https://github.com/airbytehq/airbyte-platform-internal/blob/ee86f36045610342d19caa167ad552b82aeddabc/oss/airbyte-featureflag/src/main/kotlin/Context.kt#L132), [Destination](https://github.com/airbytehq/airbyte-platform-internal/blob/ee86f36045610342d19caa167ad552b82aeddabc/oss/airbyte-featureflag/src/main/kotlin/Context.kt#L148)), I would suggest adding two new contexts:

- SourceDefinition context
- DestinationDefinition context

These just need a UUID to be used as key.

**Comment by pedroslopez** [comment]
Alternatively, we could extend the current Source and Destination contexts with the source definition id and destination definition id, respectively.

**Comment by colesnodgrass** [comment]
@pedroslopez Adding `SourceDefinition` and `DestintationDefinition` contexts seems like the best approach.

A potential issue will adding the `definition-id` to the existing `Source` and `Destination` contexts-types is that the context-kind for `Source` and `SourceDefinition` would be identical. This would force us to differentiate between them based on the `attribute` defined in the LD rule to determine which would context be used. I.e. `key` for `Source` and `definition` for `SourceDefinition`, which isn't incorrect but differs enough from the current way we have implemented contexts that I believe it would only cause confusion.  The last thing we want is for feature-flags to be confusing. 
---
There is one additional step (besides the PR adding these new context types) that is necessary to ensure these context-types are actually supported. These contexts will need to be _manually_ added to the [LD Context list](https://app.launchdarkly.com/default/production/contexts/kinds) by someone that has LD administrative privileges.  Make sure whatever `kind` value you define in the code matches the kind value defined in LD.
