### ISSUE TITLE
Platform Issue: 

### ISSUE THREAD

**Issue by KILLYOUGUTSXXX** [airbytehq/airbyte#25464]
### Platform Version

1.0.0

### What step the error happened?

On deploy

### Revelant information

hello guys, maybe here someone had ever to solving this problem ..
i got an error when deploying the airbyte in VPS when i try the custom transformations data of using the DBT options, where is the messages is telling me like this :

_**dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in ../dbt-packages. Run "dbt deps" to install package dependencies**._

i hope someone can helping me for this cases... 
thank's for youu sir ..

**Comment by marcosmarxm** [comment]
Title not following pattern.
