### ISSUE TITLE
Implement in-destination normalization for redshift

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#25499]
same process as https://github.com/airbytehq/airbyte/issues/25495

**Comment by edgao** [comment]
done in https://github.com/airbytehq/airbyte/pull/26165

**Comment by edgao** [comment]
derp. still pending the platform stuff. reopening.

**Comment by cynthiaxyin** [comment]
good to close since no more platform changes required?

**Comment by cynthiaxyin** [comment]
Redshift variation and rule added https://app.launchdarkly.com/default/production/features/connectors.normalizationInDestination/targeting
