### ISSUE TITLE
Implement in-destination normalization for clickhouse

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#25495]
* Update the connector (e.g. https://github.com/airbytehq/airbyte/pull/26165)
* Add a new variation to the LD flag at https://app.launchdarkly.com/default/production/features/connectors.normalizationInDestination/targeting with the destination version that will support in-connector normalization. Also add a new rule with the destination definition ID, pointing to this new variation (start at 0% rollout).
* ~Create an LD flag (example https://app.launchdarkly.com/default/production/features/connectors.normalizationInDestination.bigquery/targeting)~
* ~Add platform hooks to consume that flag (e.g. https://github.com/airbytehq/airbyte-platform-internal/pull/6349)~

Testing methodology:
1. Publish a pre-release image of the connector with [airbyte-ci](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md#connectors-publish-command) or the [Github Action](https://github.com/airbytehq/airbyte/actions/workflows/publish_connectors.yml).
2. Add a new variation to the LD flag at https://app.launchdarkly.com/default/production/features/connectors.versionOverrides/targeting with the pre-release version from step 1. Also add a new multi-context rule with the destination definition ID and workspace ID you are testing, pointing to this new variation.
4. Add a new multi-context rule to the LD flag at https://app.launchdarkly.com/default/production/features/connectors.normalizationInDestination/targeting with the destination definition ID and workspace ID you are testing. It should point to the new variation you added in bullet point 2.
5. ~`./gradlew build` the platform stuff + `VERSION=dev docker-compose up`~
6. ~`airbyte-ci connectors --name destination-clickhouse build`~
7. ~Configure your OSS instance to use the `dev` tag of destination-clickhouse~
8. Run a sync with normalization enabled. Verify:
    * The sync succeeds
    * Normalization runs inside the connector
    * Normalization does _not_ run as a separate container

**Comment by edgao** [comment]
@jbfbell can you add some details to the last bullet in the description once https://github.com/airbytehq/airbyte-platform-internal/pull/6122 is merged?

(and maybe the 2nd bullet, since you're picking up the DATs piece)

**Comment by cynthiaxyin** [comment]
Updated the description with steps on how to interact with the feature flags after #6349
