### ISSUE TITLE
Platform Issue: normalization fails when db password contains special characters

### ISSUE THREAD

**Issue by eschrock** [airbytehq/airbyte#25505]
### Platform Version

0.42.0

### What step the error happened?

During the Sync

### Revelant information

The platform appears to create the dbt `profiles.yaml` file using unquoted strings. For example, using a snowflake destination:

```
config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      account: ***
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 15
      database: ***
      password: aB@C?e=$>P{9%x+4%
      query_tag: normalization
      retry_all: true
      retry_on_database_errors: true
      role: ***
      schema: ***
      threads: 5
      type: snowflake
      user: ***
      warehouse: ***
  target: prod
  ```
  
  YAML support quoted strings, but when you use unquoted strings you can't use certain special characters. In this case, this will generate an error such as:

```
Could not render aB@C?e=$>P{9%x+4%: Encountered unknown tag 'x'.
```
  
This is extremely limiting given common production password requirements to include special characters. Enclosing any user-provided parameters in quotes should be the standard practice.

### Relevant log output

```shell
2023-04-25 15:18:58 normalization >   ERROR: Runtime Error
  Compilation Error
    Could not render aB@C?e=$>P{9%x+4%: Encountered unknown tag 'x'.
      line 1
        aB@C?e=$>P{9%x+4%
2023-04-25 15:18:58 normalization > Defined profiles:
2023-04-25 15:18:58 normalization >  - normalize
2023-04-25 15:18:58 normalization > 
For more information on configuring profiles, please consult the dbt docs:
https://docs.getdbt.com/docs/configure-your-profile
2023-04-25 15:18:58 normalization > Encountered an error:
Runtime Error
  Could not run dbt
```

**Comment by evantahler** [comment]
Closing this issue as we are removing cbt-based normalization in the near future. See https://github.com/airbytehq/airbyte/issues/26028 for more information
