### ISSUE TITLE
Source Facebook Pages: migrate API to v19.0

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#25515]
## Tell us about the problem you're trying to solve

Origin: https://github.com/airbytehq/oncall/issues/1888

The latest version for Facebook Pages Graph API  is v19.0.  Newly created apps can use only latest API version.

## Describe the solution you’d like
We need to migrate connector to the new version (current is v15.0).

Migration checks:

- [ ] Fields in graphQL requests
- [ ] Fields in schemas

**Comment by marvin-lg** [comment]
v17.0 was released two days ago see https://developers.facebook.com/docs/graph-api/changelog/

**Comment by awoehrl** [comment]
v18.0 would be the latest version now. We can't create facebook apps with older versions, so the connector doesn't work.

**Comment by AbramNaum** [comment]
v15.0 was deprecated yesterday (https://developers.facebook.com/docs/graph-api/changelog/version15.0#graph-api) – guessing that's why this source isn't working:
![Screenshot 2023-09-21 at 16 32 00](https://github.com/airbytehq/airbyte/assets/35600322/487ed4da-0488-43db-b968-24022e04dc40)

**Comment by GautamGottipati** [comment]
I would like to work on this issue.

**Comment by GautamGottipati** [comment]
Hi @justinbchau 
This is the only place where I need to change the version from v15.0 to v18.0, am I correct ([airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/manifest.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/manifest.yaml#L11))

   ` url_base: "https://graph.facebook.com/v15.0"`

Do I need to take care of any other things.

**Comment by justinbchau** [comment]
If the base url of the new API points to that, it would get you access but you must ensure you can reach the API when making any check calls.

**Comment by Banana-97** [comment]
Trying to use this API.. But im getting timeout (502) error
![image](https://github.com/user-attachments/assets/4f450990-c2a2-4359-bb84-57f01b04594d)

**Comment by maZahaca** [comment]
Is there any work planned in here or a reason why this issue was closed?

**Comment by smdraeger** [comment]
Is there any chance that this issue us beeing fixed soon? thanks

**Comment by marcosmarxm** [comment]
This issue was solved by https://github.com/airbytehq/airbyte/pull/36015

**Comment by meyerovb** [comment]
@marcosmarxm why is [the connector](https://docs.airbyte.com/integrations/sources/facebook-pages) still linking a warning to this issue?
