### ISSUE TITLE
Reconsider logic/implementation of updating OSS users connectors based on usgae 

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#25512]
Existing logic from [this code](https://github.com/airbytehq/airbyte-platform-internal/blob/b34f2fcdb3f1b3f541344632c62f40fa6a1f6f9b/oss/airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ActorDefinitionMigrator.java#L244-L280): 

![image.png](https://images.zenhubusercontent.com/5c9df18c8ddfda53adf61cc8/4c75cf3f-a0d0-4453-b08b-ef3775fd6345)

Main questions: 
* does it makes sense to not update the spec? In cloud, we always update the spec even for patches, we just need to enforce non-breaking changes in non-major version bumps in specs. 
* Do we think it was intentional that we add new fields to existing definitions in the case of major/minor version bumps in OSS? This is the main difference in the logic tree created by my trying to better understand the logic (from [this code](https://github.com/airbytehq/airbyte-platform-internal/blob/461e33dd327521201c5cad951665d2a16e98a10c/oss/airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ActorDefinitionMigrator.java#L247-L267)): 

![image.png](https://images.zenhubusercontent.com/5c9df18c8ddfda53adf61cc8/e08e6f72-3065-4d9d-a7fb-9f58583f073a)

* Should we always update the existing definition/adv if we get new fields we didnt have before? (probably)
* We almost certainly shouldnt add new fields from _new_ versions to existing versions. Instead, if we're pinning people to older versions, we should create an ADV for the new version, but not update the default(?) version used 

... therefore, should we be using the mechanism of static version overrides for "pinning" OSS users to a compatible patch and not updating majors/minors? 

... do we even want to keep this behavior of keeping OSS users on patches? Do they want the behavior that cloud users have? @evantahler and @nataliekwong might be looking into this

exploring via [this whimsical](https://whimsical.com/PDvA3mtP5GhD29xc15xKpN)

**Comment by evantahler** [comment]
Grooming:

* Specs should be immutable.
* "new fields" might have things like new names, new icons, allowed_hosts, etc so this is still valuable. BUT, we shouldn't do this, because Specs should be immutable!  If there's not a version change, don't update the spec.
   * This is less important as new information like this should be in metadata, not the spec!
   * this may have been from when doc links were broken

Should we always update the existing definition/adv if we get new fields we didnt have before?
* Global changes yes, per-version changes no.

Migration Goals (WE THINK)
* OSS: Users know about new versions, but they don't upgrade unless they choose to do so (even patch versions).  This can be done with pinning. 
* Cloud: Users know about new versions, but they don't upgrade unless they choose to do so (even patch versions).  This can be done with pinning.

**Comment by erohmensing** [comment]
Closed in https://github.com/airbytehq/airbyte-platform-internal/pull/6123

Conclusions: 
> does it makes sense to not update the spec? In cloud, we always update the spec even for patches, we just need to enforce non-breaking changes in non-major version bumps in specs.

This was removed, `spec` is handled the same as any other existing or new field. This was legacy code from when `spec` was originally added into the definitions and we didn't want the new specs to break the old ones users had previously.

> Do we think it was intentional that we add new fields to existing definitions in the case of major/minor version bumps in OSS? This is the main difference in the logic tree created by my trying to better understand the logic (from [this code](https://github.com/airbytehq/airbyte-platform-internal/blob/461e33dd327521201c5cad951665d2a16e98a10c/oss/airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ActorDefinitionMigrator.java#L247-L267)):

I believe it was unintentional. I removed that branch. 

> Should we always update the existing definition/adv if we get new fields we didnt have before? (probably)

We do this now! 

> We almost certainly shouldnt add new fields from new versions to existing versions. Instead, if we're pinning people to older versions, we should create an ADV for the new version, but not update the default(?) version used

This wasn't relevant for the refactor PR, but is indeed how we want to handle pinning older versions (in the case of e.g. the quarantine prd)

> do we even want to keep this behavior of keeping OSS users on patches? Do they want the behavior that cloud users have?

This is unchanged for now, and is still a wider question we're trying to address in the "updating connector versions" project.
