### ISSUE TITLE
Remove Redshift migration code for tmp tables

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#25519]
No longer relevant after checkpointing.

See #25517 which addresses an associated integration test.

**Comment by evantahler** [comment]
## Grooming:

**History**
* Redshift used to use VARCHAR and then we moved to SUPER type for RAW DATA.  This was 1 year+ ago.  Code still in the connector (normalization).

**Notes:**
* Shouldn't be any merge conflicts with work to move normalization into connector
* The team voted 100% to remove this migration code.

Links:
* https://github.com/airbytehq/airbyte/pull/12064/files#diff-b56901306056faa1794c13d1b28f5aa720703aedb76ad01d3bcc790b0d8e74beR38
