### ISSUE TITLE
Destinations: Fix integration tests referring to `format: datetime`

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#25564]
JsonSchema only accepts `"format": "date-time"` (https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times)

some of our integration test configured_catalogs are declaring `"format": "datetime"` (note the missing hyphen):
https://github.com/airbytehq/airbyte/blob/31baedaa41ff03035b980a146fbc45de363e5f88/airbyte-integrations/connectors/destination-convex/integration_tests/configured_catalog.json#L19

find and replace those with `date-time`, then verify that tests continue passing

affected destinations as of 2023/04/26:
* convex
* cumulio
* duckdb
* firebolt
* sqlite

(other context: some sources actually `discover` datetime; convo with the api sources team to get those fixed https://github.com/airbytehq/oncall/issues/1848#issuecomment-1523614372)

**Comment by evantahler** [comment]
**Grooming**

These are alpha connectors, so we can just find/replace the bad format out, /test, and be done.

**Comment by evantahler** [comment]
Update - the list of connectors in the description includes bad type for those connector's tests.  That's not a big deal.  What is a big deal is that the following connectors actually have schema or code problems and are using `datetime` 

source-file
source-firebolt
source-google-ads
source-stripe 

Addressing this in https://github.com/airbytehq/airbyte/pull/25965
