### ISSUE TITLE
Alert when connector CI fails repeatedly

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2557]
## Tell us about the problem you're trying to solve
We currently need to proactively check the [connector health](https://docs.airbyte.io/integrations/connector-health) to find if connector builds are repeatedly breaking. We should have proactive alerting for all of these. Ideally the alerting works as follows

If the latest build is a failure, trigger an alert if any of the following conditions are true: 

1. The last 3 builds (including this one) failed
1. more than 5 out of the last 10 builds (including the current one) have failed

Alerts should be piped to to the `#connector_builds` slack channel.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368155383563) by [Unito](https://www.unito.io)

**Comment by girarda** [comment]
@sherifnada are the daily slack messages good enough?

**Comment by sherifnada** [comment]
yup!
