### ISSUE TITLE
Sandbox account for Source Convex

### ISSUE THREAD

**Issue by archangelic** [airbytehq/airbyte#25571]
We need a sandbox account for Convex to run integration tests for Convex source connector.

**Comment by igrankova** [comment]
LastPass: Convex Free Account
logins with GitHub account creds
Connected GitHub account
airbyteio

**Comment by igrankova** [comment]
@archangelic, please try this free account and let me know if you need any other help.

**Comment by igrankova** [comment]
Contacted to the Convex Team on Discord

**Comment by igrankova** [comment]
@archangelic I received an answer from the Convex community team in Discord:
Airbyte Team , I've added integration-test@airbyte.io as a member to a team which has a project that is pre-popuated with a good variety of relational data spread across a few tables
the sync key for the airbyte connector can be found here: https://dashboard.convex.dev/t/airbyte-test-team/airbyte-test-project/glorious-squirrel-442/settings
once you accept the team invite and log in you'll be able to navigate there to retrieve a key to sync the data out.

Generated a Deploy Key for airbyte-test-team/airbyte-test-project with the test data. See in LastPass: Convex Sandbox Account
