### ISSUE TITLE
Source Stripe: Missing field cancellation_details in Stripe connector

### ISSUE THREAD

**Issue by ruer98** [airbytehq/airbyte#25584]
### Connector Name

airbyte/source-stripe

### Connector Version

3.3.0

### What step the error happened?

During the sync

## Environment
- Airbyte version: 0.44.1
- OS Version / Instance: AWS EC2
- Deployment: Docker-compose
- Source Connector and version: airbyte/source-stripe (3.3.0)
- Destination Connector and version: airbyte/destination-bigquery (1.3.1)
- Step where error happened: Sync job

## Current Behavior
The `cancellation_details` field from the subscriptions stream doesn't exist in the final tables, it only exists as part of the JSON fetched from Stripe.

## Expected Behavior
The `cancellation_details` field should be present in the final table and be shown on the Airbyte UI.

## Steps to Reproduce
1. Run a sync for the subscriptions stream

### Contribute

- [ ] Yes, I want to contribute

**Comment by davydov-d** [comment]
fixed in https://github.com/airbytehq/airbyte/pull/28776
