### ISSUE TITLE
Consider Upgrading DBT dependencies

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#25580]
From a [Slack Thread](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1682532718125089) there was unexpected dependency on normalization when building a source connector. A few things came out of this investigation

- The CONNECTORS_BASE is building everything in the `airbyte-integrations/bases` directory which includes base normalization, hopefully this goes away if we move these into the destination containers. If we still have shared code we should move it to a separate subdirectory than the standard connectors base code and make sure that it is excluded for source builds
- The dbt docker image we're using [has been deprecated for at least a year](https://hub.docker.com/r/fishtownanalytics/dbt) if we're going to keep dbt around we should update that

This is related to other Dockerfile changes tracked in #25492

**Comment by edgao** [comment]
the good thing about the dbt docker image is that we won't have runtime dependencies on it - the destination connector build only copies our normalization code from the normalization image, it installs all the dbt stuff separately (https://github.com/airbytehq/airbyte/blob/a38af089e91cb2b958e553f2c1c7c1c34c508882/airbyte-integrations/connectors/destination-bigquery/Dockerfile#L22-L28)

though if the normalization images are still in our integration test path, we still might want to make that better

**Comment by edgao** [comment]
we're planning to remove dbt from the destination connector code path, so we shouldn't bother with this.
