### ISSUE TITLE
Connector builder shows unknown error when list streams request returns 400

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#25581]
### What
The UI kicked me out of the connector builder when the list streams request returned a 400.
For context, the 400 error was caused by me trying to use interpolation with a variable that does not exist (`{{ stream_partition['key'] }}`)

I tried going back to edit the connector, but it kept on crashing. 

Loom video: https://www.loom.com/share/932a8dcc020645a4ae1fa9d2031c59a6

This happened on Cloud. Not sure if it's also a problem on OSS.

Edit: I'm able to edit the connector now. Maybe this is related to caching?

**Comment by lmossman** [comment]
Fixed by https://github.com/airbytehq/airbyte-platform-internal/pull/6155
