### ISSUE TITLE
Better documentation for cursor_field

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25595]
The Incremental Sync `Cursor Field` documentation is lacking:
- It should explain that nested cursor fields are not supported and how this can be worked around
- It should list the interpolation context values that are supported

This should be put into the declarative schema, and updated in the docs if more explanation is needed (i.e. for the workaround)

**Comment by girarda** [comment]
closed with https://github.com/airbytehq/airbyte/pull/25696
