### ISSUE TITLE
Add tests to verify pairwise compatibility of sources and destinations

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#256]
## Tell us about the problem you're trying to solve
We want an automated way to verify that any pair source/destination pair can be used for sync. Current integration tests do not provide a strong enough guarantee since the input to each target in those tests is not necessarily representative of the input that might come from any supported Singer tap. 

This problem is partially due to inconsistencies within the Singer ecosystem. For example, the Postgres tap outputs messages not officially contained in the Singer spec, which caused us to have [too broad a scope](https://github.com/datalineio/dataline/pull/229/files#r487304819) in the tap's integration test. 

## Describe the solution you’d like
Tests which give a strong degree of confidence that all pairs of taps and targets will work well together. A suggested approach is to have a "golden list" of records which is representative of all messages that a tap might output, and use that list in all destination integration tests.

**Comment by cgardens** [comment]
Our testing story as evolved from here. We have provided the guarantees that this asks for (though it is not pair-wise).
