### ISSUE TITLE
improve log readability

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2562]
Carries the unimplemented piece of https://github.com/airbytehq/airbyte/issues/652 over.

* have the job run page stretch the width of the page
* have side scrolling inside the log view (no word-wrap, so exceptions are actually readable)
* respect log color formatting like `\033[0;31m`, etc.

Currently I never debug logs in the UI. I have to download them and look at them elsewhere because they're completely unreadable without the above.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368155438439) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Another point is we have to scroll a lot through the logs page too... 
if we could have always visible buttons to jump to the top or bottom of the log page, that would be nice...

Some auto-scroll functionality while job is running as described here could also be great:
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/39109

**Comment by cgardens** [comment]
Going to suggest for the first iteration that we just go with what @jrhizor suggested in the description as that is more clearly defined. Let's not worry about auto scroll or jump to bottom of page for now.
