### ISSUE TITLE
Implement the handler for the Stream Status API

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#25637]
## Tell us about the problem you're trying to solve
Provide access to create and retrieve individual stream status within a condition, job and attempt.

## Describe the solution you’d like
Implement the endpoints created by the [generated stream status API endpoints](#24898)

## Acceptance Criteria

* Endpoint implemented to create a stream status
* Endpoint implemented to update a stream status
* Endpoint implemented to query for stream status
* Acceptance tests updated to verify stream status after a sync for the different cases (success, failure, cancel)

**Comment by tryangul** [comment]
Broke out acceptance tests to [this ticket](https://github.com/airbytehq/airbyte/issues/25821)
