### ISSUE TITLE
Connector builder: Improve schema detection

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#25669]
Currently, the schema detection of the connector builder is differentiating between `integer` and `number`. As we are working with small sample sets, there is a high chance to recognize a number as an integer on accident because the test read did only yield integers by chance.

To increase the chance for a successful first sync, all numeric values should be detected as "number" in the schema.

It should also not produce `anyOf` or `oneOf` but instead a type union (but if it can't be avoided it should be `oneOf`):
```
 oneOf: [{type: string}, {type: integer}] vs ["string", "integer"]
```

**Comment by flash1293** [comment]
Strip out `type: null` fields

**Comment by sherifnada** [comment]
should detecting `date` and `date-time` be part of this too?

**Comment by flash1293** [comment]
@sherifnada we discussed this in the grooming and decided to split it out
