### ISSUE TITLE
octavia-cli release job needs a new home

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#25671]
The [docker image](https://hub.docker.com/r/airbyte/octavia-cli/tags) for octavia-cli has not been published since March 14 😔

It looks like when we moved OSS releases in https://github.com/airbytehq/airbyte-platform-internal/pull/4997, we did not include octavia-cli (probably since it still lives in this repo). Consequently we stopped running the workflow with Octavia's releases in it.

We need to find a new home for the `release-octavia` job:

https://github.com/airbytehq/airbyte/blob/4912cc607870184de6c4ceba3bece1271a4789fb/.github/workflows/release-airbyte-os.yml#L174-L222

Related: https://github.com/airbytehq/airbyte/issues/24256, https://github.com/airbytehq/airbyte/issues/25303

**Comment by Santhin** [comment]
Maybe It would be a good idea to migrate octavia cli to separate repository? For example `octavia-cli`?
