### ISSUE TITLE
Connector Issue: Seller Partner Source Test Failure

### ISSUE THREAD

**Issue by nicksaroki** [airbytehq/airbyte#25674]
### Connector Name

Amazon Seller Partner

### Connector Version

1.1.0

### What step the error happened?

Configuring a new connector

### Revelant information

https://github.com/airbytehq/airbyte/pull/23980/files/0ee15e2d5b76f79681185fe7e98d29a2af2240a8#diff-7e5570008f15df59d5cfe23de524a9ee2ed85c05755bf61d69517242f74e6e65

Since this change was implemented, SOME of our Seller Partner accounts fail to connect with the following error:

```
Configuration check failed
HTTPError('400 Client Error: Bad Request for url: https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports')
```

What's odd is that some seller accounts work just fine. We are not adding new accounts, these are all ones that existed and were working normally before upgrading past this change.

I don't see anything here that indicates `GET_VENDOR_SALES_REPORT` is a report is good for sellers and vendors:

https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports

### Relevant log output

```shell
Configuration check failed
HTTPError('400 Client Error: Bad Request for url: https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports')
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by nicksaroki** [comment]
Yeah, I don't see anything here that indicates `GET_VENDOR_SALES_REPORT` is a report is good for sellers and vendors:

https://developer-docs.amazon.com/sp-api/docs/report-type-values#vendor-retail-analytics-reports

**Comment by nicksaroki** [comment]
Confirmed that if I downgrade to `0.2.33` everything works normally with these connections.

**Comment by sh4sh** [comment]
Hey @nicksaroki is this only impacting `check` or does this fail syncs too?

**Comment by nicksaroki** [comment]
It only impacts `check`.

**Comment by nicksaroki** [comment]
Bump? Not sure how more users aren't running into this.

**Comment by trivialzero** [comment]
We're running into the same issue with 1.0+ of this connector - have to downgrade to 0.2.33 to connect. We're having other issues with this connector as well, such as hitting 429's on reports that the connector isn't backing off properly for

**Comment by askarpets** [comment]
Closing the ticket since the [PR](https://github.com/airbytehq/airbyte/pull/27050) is merged.
