### ISSUE TITLE
Categorize Facebook Marketing config errors

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#25686]
A user can receive the following errors due to the setup of their config, which are currently categorized as system errors.

These all should be categorized as config errors. 

For this error, the error message indicates we cannot verify the Account ID. The external error message should read: "The Account ID is invalid. Refer to Facebook Marketing's [docs](https://www.facebook.com/business/help/1492627900875762) to find your Account ID"

There should also be a change to the connector spec which validates that the Account ID follows the format of only containing numbers, and should not accept any text.

- Error: 100, Missing permissions. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_1288784415293272;1181817321833895' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_1288784415293272,1181817321833895,454424629048340,102471553244411,468318420850703,1692250867457202' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
- Error: 100, Unsupported get request. Object with ID 'act_act_05768070981957' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.

The error message below should instead read, "The custom field `unique_clicks` is not a valid configuration for `metrics_by_account'. Review Facebook Marketing's [docs](https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/) for valid breakdowns.
- Please remove Following fields from the Custom metrics_by_account fields list due to possible errors on Facebook side: {'unique_clicks'}

**Comment by alafanechere** [comment]
@lazebnyi do you confirm you're actively working on this issue? The following error leads to abusive paging on the OC side:
```
Error: 100, Missing permissions. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
```

(see airbytehq/oncall#1966)

**Comment by lazebnyi** [comment]
@alafanechere Yes, @artem1205 start working on it.
