### ISSUE TITLE
Connector Issue: 

### ISSUE THREAD

**Issue by darshilshahquantive** [airbytehq/airbyte#25715]
### Connector Name

Delighted

### Connector Version

0.2.2

### What step the error happened?

Configuring a new connector

### Revelant information

Hello everyone,

I have successfully deployed Airbyte on our Kubernetes infrastructure using the Helm chart provided by the Airbyte team, available at https://github.com/airbytehq/airbyte-platform.

In our use case, we need to move all of the Docker images used by Airbyte to our own registry due to compliance reasons. While I have successfully moved all of the images, my main concern now is that whenever we try to make a new connection using Airbyte with any data source, it uses the public Docker image only. I believe this image is hard-coded or set up somewhere in the Airbyte code.

Can someone help me find all of the data source and destination images? Also, is there any environment variable available that we can use to specify custom images for data sources? and if not what can be steps to use this custom private docker images of destination and data source .

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed https://docs.airbyte.com/operator-guides/using-custom-connectors
