### ISSUE TITLE
connectors-ci: allow to run `airbyte-ci`commands from subdirectories:

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#25716]
## Tell us about the problem you're trying to solve
Feedback from @edgao 

> My dev flow is generally to cd into a connector directory (e.g. cd airbyte-integrations/connectors/destination-bigquery). It would be nice if airbyte-ci traversed up the directory tree to find the git root. (similar to how [gng](https://github.com/gdubw/gng) does that for gradlew)

## Describe the solution you’d like
You should be able to run `airbyte-ci` command as long as you are running the `airbyte-ci` from the `airbyte` directory or a **subdir*

**Comment by evantahler** [comment]
Grooming: 
* We can probably use `pygit` to find the top-level dir and then maybe `chpwd` at the start of the app?
* check paths and such (run a few commands)
