### ISSUE TITLE
Allow configuring jdbc url containing an equal to sign `=` character

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#25734]
## Tell us about the problem you're trying to solve
In #25386 we allowed configuring a jdbc url if the user added a mysql `sessionVariables`.
e.g
```sessionVariables=MAX_EXECUTION_TIME=123456666```

The solution is adhoc and doesn't address
a. The problem in general of adding a jdbc url param containing `=`
b. Even for the particular case of mysql sessionVariables, adding multiple such variables separate by a comma of semicolon [as allowed according to documentation](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-session.html#cj-conn-prop_sessionVariables) won't work.

## Describe the solution you’d like
We need to find a general solution for all connectors.
This is tricky as mysql doesn't seem to correctly parse a url encoded equal to sign `%3D`.

**Comment by evantahler** [comment]
Closing this issue, as it looks like it was fixed (see comments in https://github.com/airbytehq/airbyte/pull/25386)
