### ISSUE TITLE
Enable Xmin option in the UX

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#25749]

**Comment by akashkulk** [comment]
Add xmin in the UX by adding it to the `spec.json` file. It should show up as a third option, in addition to Standard and CDC. 

This should be the last step to be completed

**Comment by akashkulk** [comment]
Note that this will also be the step when we can merge the integration tests. They have been written and validated locally - but need to be merged in with the spec change

**Comment by prateekmukhedkar** [comment]
@Hesperide @prateekmukhedkar to review the release documentation.

**Comment by akashkulk** [comment]
[Here](https://docs.google.com/document/d/1INszgbc6yulPkfntmgZqR-jB2uc9n1dXOhx83T0QARE/edit?pli=1) is the draft of the release statement
