### ISSUE TITLE
Add a tags field to the metadata files and registry

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25741]
## Overview
We would like to have a tags field in the metadata of a connector to enable easy searching of the connector registry

https://github.com/airbytehq/airbyte/issues/25139

## Proposed solution
1. Add an optional `tags` field to metadata which is an arbitrary array of strings
2. Copy these tags fields to the final connector registry

**Comment by evantahler** [comment]
**Grooming**

* Arbitrary array of strings
* We need a reference guide for what the taxonomy/types are

Tags Taxonomy:
* `type:*` (e.g. `type:databases`, `type:API`)
* `language:*` (e.g. `language:python`)
* `low-code`
* `keyword:*` (e.g. `keyword:aws`, `keyword:postgres`, `keyword:cms`) - for user search

In the future, we can promote some of these tags to a top-level typed metadata field once we know more about the usage.
