### ISSUE TITLE
Xmin Phased Rollout strategy

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#25754]

**Comment by akashkulk** [comment]
Put a good rollout strategy in place. There are 2 options: 
1. Use the multiple connectors override system to slowly rollout out this feature
2. Rollout the spec.json using the same framework as the SSH/SSL improvements

**Comment by prateekmukhedkar** [comment]
We have started the xmin pilot and depending on the results it will influence the rollout strategy. https://docs.google.com/document/d/1frTnfRlcMPECD9FP1YHee2k3ssHgEsRbcqWJNasbZLA/edit

**Comment by akashkulk** [comment]
Closing this out as we have rolled this out to 100% of users
