### ISSUE TITLE
Google Cloud test environment: Migrate to Kubernetes Generally Available API versions before upgrading to GKE v1.26

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#25760]
## Tell us about the problem you're trying to solve
**[Action Required] Migrate to Kubernetes Generally Available API versions before upgrading to GKE v1.26**
The automatic upgrades from Kubernetes v1.25 to v1.26 will start on or after **May 25, 2023**. For this reason, we recommend updating all your clusters to use GA API before v1.25 reaches End of Life on **February 29, 2024**, to ensure continued API functionality.
What do you need to know?
[Kubernetes project’s lifecycle](https://notifications.google.com/g/p/ACUgQrEXvbOixEf_UusY3OgyqnoaZI6e_xJuTL46D4GKti1Kl17lb6v7hq6G7fWih8fmyhlJk54I7BPqPyo2Yo-7OGBZgENCZj4QpZR9Yvvj82nwTqOPwzLzd5U-VO45M9enk5Qt7rNgzGPjxHVpMKjuKvUSVoVHnZkgqzl3zhEP4O5-RSakWT3djY_ylOHWiRdiAk9VmiAW-VuXMzGeKNxixUj_1LKbteIPC22t9fUiIQ) states that once the APIs graduate to general availability, previous alpha and [beta APIs](https://notifications.google.com/g/p/ACUgQrGu4z_hEW-z1-wIem1lQKqFOo7xKLqX3JPuLuJHd-sJJAJlODD__lFNgYZwAhSjJdI1h6k8qqBsfNgR7M1Yqy4A_SXZbhHUw0l2MfSaf3ioOVTzUjHChcJzZStQPJ7ULsYcUsgxn6vmztmfGdnB1km7JnTgp-s9GUFU5yI7HHVnERqQCo8kRKaLY69YnQ8DruBTER1RQhFbWplgVfHBe4fMDtmXroIZcFGpbKYrGy-EDFx-6jpp) are eventually removed. Once beta APIs have been [removed from Kubernetes v1.26](https://notifications.google.com/g/p/ACUgQrGLeGukNMMupLzBt8ChjiZZ08_0g9AdM3D0yu9GW2Ebk8otAY02VHcpI7O8leUadCCFzx31soyROF4aA1XM5-s2fWwYQQr8culallDEbBQGX9AJU2u0GVC7wV_ye-ohn8dJeYrpH8jxSmDjKWCJK2nQEaNDDCzB4Rxcc_I_uoH68WmU5b95HtmMJreD9GZ3yYqGwNP4Ndronfx-3ArrSNkspQdg5xfATNsZDZuxd1G5nnhy1J0), you can expect to experience some of the following behaviors:

- If GKE detects usage of the removed beta APIs in your clusters before upgrading to Kubernetes v1.26, Google will [pause automatic minor upgrades ](https://notifications.google.com/g/p/ACUgQrEkep0S-DjeyqT_GBhoacLW1kFMnGV6hXe7VsnfkOEAs69dyNEahFxnafQn2QfzAj76yqvHotzHMYSU89exaQnBhJ72yqgvlJpSLbErj_ca_Ym-3zUXjcbtPh9-VEw3BQWhrwPMZRgFXGMlLyybKOvhYNBzF_1ZhV5XrUmYeZJAtQPrntquz2MpYRdUFVTfqNsqboyviI9xrxdRA44pcgkyCKYTFhiRRp79jFwIUYZFn3liOsOitDaYh4Pms4Y)until Kubernetes v1.25 reaches EoL for GKE clusters on that version. The minor upgrade pause is intended to let you perform a timely and nondisruptive transition from beta APIs removed in Kubernetes v1.26 to their newer supported versions.

- API clients won’t be able to use the removed beta APIs in v1.26.

- [Manifests](https://notifications.google.com/g/p/ACUgQrHc4nDdrVGWoT0UioFCzUaohJu0S0hyiqcqI-L3-aMOy0dPW4ZSafhg6hk9SkUz65abqhQuuG5l6Qkbzo2E0HwnxJt8_hNNWtk1tJBTuBxvE6tL7Nhom9nS0PRfAVtj_w9JmIXoM9Ptqw9ihOyvNT2oWGME5rLri-E0x22OrWyGC_Z4FxGKf_oBzpC8P2QrXT2tqYTrBnSu4RZG-VKOliBEDzvJQqK6J1baC_hC-FmiYJ852YBa57uG-8By) using the removed beta APIs removed in Kubernetes v1.26 can no longer be applied.

- Previously persisted objects will remain functional and can be viewed and updated using the new API versions before and after upgrading to Kubernetes v1.26.

What can you expect after Kubernetes v1.25 reaches EoL?
We will automatically upgrade your clusters remaining on Kubernetes v1.25 to Kubernetes v1.26. Optionally, you can configure [maintenance windows and exclusions](https://notifications.google.com/g/p/ACUgQrFTNcksxMVINE4Wuf7Up7K9Jmf52MoAVcDXUhQMYFFvLCIeGnUeh0kQnZSn3DryH9BtnmI8GHb3sX_ezeDV7z2q341yRRIS8Pjf2_WxZbP6bKojodEpoheCGrTcYAdXRsKSc11cG1cKuA2bob5slcs5NAo9q8RufiI07CgU_tPob8GCZRlW-4Rz4Yb8FEuCW9oXAcXLyJZRtBbecLlUAtfEiu1Uu6ZNP9CmQT1rY24XK4Nrl2vKICQ6KbLow1aUQ6rTIo5-RAUyMLHS) to control scope and timing of automatic upgrades or to temporarily pause them. Cluster control planes are [upgraded regularly](https://notifications.google.com/g/p/ACUgQrHxBqGCAzvglhByCDxtRae9DSz30Rf_do5En_maGvTElzB7rdUdkXkgE0zL7WMgaG5pubLDLAgVLsbouA-W2aUmzuXbk3-ulZMlrilq15afv5FOqF7-5JEt0GPgygsfxVVjqmKtg9LT0dGc0YBJNMxurOv0OtP6xMzjB5LXO6ATNVxjf_2w3lkreAmeCQk_vPGkAmvchLh1ophZ6W6CHL9rveJvz2YMLJ0aVkUrMEpnt3wWXAQ7xSE).
Please be advised that once Kubernetes v1.25 reaches [EoL](https://notifications.google.com/g/p/ACUgQrHZDPL1mGxyIUxV-WtRs1LFQeaQ0aqTghubHcADGq-4PyGlZv7vSFs5vrEbfb1kFJSYCaTueyqlnMNaDMLXNBRRYxPO8jfryClsUfCzFF-F3TMrM-viQ9_Wd_H4iaIWsnjG2AyEY99U2TKg3x76e7kpQuHYYfc0x_KrgCvvn5Cw8a00BpXajd9EVVx7bSaKqJXZLp11IkwHfxSCOtOBSpMwVkV-n5J_B0wD1OMMCRle8fWyUodjRJ85HhNmgoz5s6XAZIkmePFc7o7SWBw) and Google upgrades your clusters to Kubernetes v1.26, you will no longer be able to access the removed beta API versions. Any remaining dependencies on these APIs may stop working.
The GKE [release schedule](https://notifications.google.com/g/p/ACUgQrGMx2DfjFGXTPzhCqB5r_VLB4slDxVouXXZKCGqI9J94DqYDmpiKGtjAdU0XJ8YOSucCdHDTDvSgHwojERS08ffwd09BcicUQ1wCvC2zqDoHhXumvljmuaK0JVquUxN907_1g0vWweeSU835XTFIaZv98YcaFAPOn368Tqs1xwkBpEJIm8z5Q8BBppFWC36qTPgB7pAvPRcFYIZCLozg6MRkt3YQSQwCQnMzFraIBw) outlines the cluster upgrade schedule for Kubernetes v1.26. Please note the automatic upgrade start dates for the release channels and for clusters on a static version.
What do you need to do?
We recommend updating your software to use [supported](https://notifications.google.com/g/p/ACUgQrGLeGukNMMupLzBt8ChjiZZ08_0g9AdM3D0yu9GW2Ebk8otAY02VHcpI7O8leUadCCFzx31soyROF4aA1XM5-s2fWwYQQr8culallDEbBQGX9AJU2u0GVC7wV_ye-ohn8dJeYrpH8jxSmDjKWCJK2nQEaNDDCzB4Rxcc_I_uoH68WmU5b95HtmMJreD9GZ3yYqGwNP4Ndronfx-3ArrSNkspQdg5xfATNsZDZuxd1G5nnhy1J0) GA API versions. Updating your software before upgrading your clusters to Kubernetes v1.26 will ensure your API clients and resource manifests can continue to access and update API resources without disruption.
**Note:** To assess the use of the removed APIs in your clusters, you can use [Admin Activity log query](https://notifications.google.com/g/p/ACUgQrGLeGukNMMupLzBt8ChjiZZ08_0g9AdM3D0yu9GW2Ebk8otAY02VHcpI7O8leUadCCFzx31soyROF4aA1XM5-s2fWwYQQr8culallDEbBQGX9AJU2u0GVC7wV_ye-ohn8dJeYrpH8jxSmDjKWCJK2nQEaNDDCzB4Rxcc_I_uoH68WmU5b95HtmMJreD9GZ3yYqGwNP4Ndronfx-3ArrSNkspQdg5xfATNsZDZuxd1G5nnhy1J0) with Google Cloud’s operations suite enabled, to show the Kubernetes v1.26 APIs in use.
Your projects below use the beta APIs removed in v1.26 and will require you to migrate to the newer API versions before your clusters are upgraded to v1.26:

- [dataline-integration-testing (dataline-integration-testing)](https://notifications.google.com/g/p/ACUgQrFfjkkEDsfk7ERS9UnGeJdujfTQDfIYBNCsYRtlYKjLw-h_c-cP_eO0umAKgQFaplNxefMj4vHkLsUPlaSNJMI-29b3boNlikd4yJSeuATzDYxtD8bKSSptXqNB-bpmtILXddgdoOWkJjLUvPEEusBtQohCgqcw8vr_YhNsWaiBY7nDmdbbdQCzn9bHWo1FZSXi2nfkxq2RTQvpRAHyG14KgDm5-5ofcClUfkIKc7goDX1few)

> - us-central1-airbyte-airflow-6320911c-gke
> - airbyte-demo-gke
> - marcos-cluster

We’re here to help
If you wish to learn more about how Kubernetes works, we suggest reading:

- [How cluster upgrades work](https://notifications.google.com/g/p/ACUgQrENh0fooJQH3BnCEtWS4Q4dP9i9zvx6BGFQuDt7Sv7ivLyHr9YwVNZMZizsmyANXWpa6Egx2aRRg8LADj0ReJqV2bO69JpPuY7VF7wfIvVqxS0or53_VQMeQ6M61FSySIQdCiNS8Dvxo2yw_go5GTdkgjDSwKbXVLEMMo9jrv9Dof4BJIKZalnHRWkz7bDN6Uik46EKIidpK_fgmTAW1Ryu73l47QgRie8SEojf9pXINerOXalQ8qg)
- [How Kubernetes deprecations work with GKE](https://notifications.google.com/g/p/ACUgQrEMvW2U9LWMpc-W4A0Q8hkhkRPFmVr_7b0wuog0Ik0lNFWzWrN-HEapLchlNXRWajhLt6cK_Rbk8S404c4Gad8t221ZJIy7Eeea2u3Gy0EunrkuUKX2fADuWSXrZgUFfKvmxaD2i27GtLoIqhg96MUsGpduWd5o94Pb56weC2-W9TnUH3emYNqbvXEfwlESwHivF_DfyTYuaSglYw3HIxxeRAG4HL8U3HNFRta4g0K-dbdoJj0MeVynRArIU3eh3TjKi-brsaUNQrCjSG1mk94S)
- [Deprecated API migration guide for Kubernetes](https://notifications.google.com/g/p/ACUgQrGu4z_hEW-z1-wIem1lQKqFOo7xKLqX3JPuLuJHd-sJJAJlODD__lFNgYZwAhSjJdI1h6k8qqBsfNgR7M1Yqy4A_SXZbhHUw0l2MfSaf3ioOVTzUjHChcJzZStQPJ7ULsYcUsgxn6vmztmfGdnB1km7JnTgp-s9GUFU5yI7HHVnERqQCo8kRKaLY69YnQ8DruBTER1RQhFbWplgVfHBe4fMDtmXroIZcFGpbKYrGy-EDFx-6jpp)

**Comment by cpdeethree** [comment]
Acceptance criteria:

- [ ] Investigate the potential impact here on our existing clusters
- [ ] determine, what, if any, immediate action needs to be taken to alleviate auto-upgrading issues

**Comment by perangel** [comment]
No action needed. Deprecated API does not appear to be in use
