### ISSUE TITLE
Source Amazon Seller Partner: problems with the 'Authenticate Seller Partner account' stage (Alpha version)

### ISSUE THREAD

**Issue by streveg** [airbytehq/airbyte#25773]
### Connector Name

Amazon Seller Partner

### Connector Version

Alpha

### What step the error happened?

Configuring a new connector

### Revelant information

I'm having problems with the 'Authenticate Seller Partner account' stage.

I have an app set up in Amazon Developer Central and on my first attempts to authenticate my seller partner account, an 'MD9000' error code was displayed with the message 'Something went wrong. The developer is currently not eligible to receive new authorisations'. 

I did Google this message which led me to this Github page (https://github.com/amzn/selling-partner-api-docs/issues/342#issuecomment-767957906) that I wasn't sure how to interpret but I did try Airbyte support and they pointed me to the same article. 

The advice was to add login and redirect URI information so I tried a few different options for both which seemed to get me past the initial error but I now get error code 'MD5101 - Invalid redirect URL received. Please validate redirect URL used.'

I have tried Amazon Seller Support but they tell me to authorize the Airbyte app via the Seller App Marketplace which is completely different to the approach advised in the Airbyte documentation so I'm assuming it's incorrect.

If anyone out there is successfully using the alpha version of the Amazon Selling Partner connector, would you be able to share how you authorised the app, in particular what you used for the login and redirect URI's?

Thanks very much in advance for your help!

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Please upgrade the title and the connector version.

**Comment by MadronaB** [comment]
I've been continually coming back to this connector since July 2022 in hopes that it will work. I want it to work and I'm willing to pay for it. I've seen work being done but I have never been able to get the cloud version to authenticate my seller account. I was also getting the "MD5101 - Invalid redirect URL received. Please validate redirect URL used." for a while and banged my head against the wall trying to figure out what to input into the fields in seller central and then realized those don't need to be filled out by the end users of the app. I haven't had to fill in those fields to have other software connect to my amazon seller account. I agree with Streveg that from a users stand point we should be connecting through Airbytes app that is posted on amazon's third party marketplace and not via our own self-authorized app we created. 

The current error I get when trying to authenticate my account is "OAuth login failed: Internal Server Error: java.io.IOException: Missing 'refresh_token' in query params from https://api.amazon.com/auth/o2/token"

I think Airbyte needs to continue hearing there are customers wanting this app to work and putting some dev resources into it to get it to the next stage. I'll try and continue testing it every few months and provide helpful feedback when I can.

**Comment by streveg** [comment]
I'm glad to hear I'm not the only having this problem @MadronaB! 
It's really frustrating when I know there must surely be some people using it successfully, especially if it has been around since before July 2022! 

However, I have been liaising with Juan at Airbyte Support who is incredibly helpful so I am really hoping we'll get to the bottom of this soon. Like you, I'd love to get this working and would be happy to pay for it if we can get it beyond the Alpha and Beta phases.

**Comment by MadronaB** [comment]
I talked to one support rep who said he didn't see any customers using the
connector yet. This made me feel better for not being able to figure things
out but also worse because it might be a while before the Alpha is even
functional. If someone knows otherwise, please correct what I was told.

**Comment by bazarnov** [comment]
This could be also related: https://github.com/airbytehq/oncall/issues/2017

Going to work on it starting next week  (Tue, June 6th)

**Comment by streveg** [comment]
That's great news! Thanks for the update @bazarnov

**Comment by Blochergroup** [comment]
Thats great to hear! @bazarnov 

I also tried authenticating a few weeks ago and got a similar error even though I provided an app id and the other credentials (which shouldn't be necessary according to this issue https://github.com/airbytehq/airbyte/issues/26629)

**Comment by bazarnov** [comment]
The updates are merged. Please try to proceed with the authentication, thank you.

**Comment by streveg** [comment]
@bazarnov , the Aamzon Seller Partner connector does not seem to be available in Airbyte. It was removed a couple of weeks ago and it doesn't look like it's been restored?

**Comment by bazarnov** [comment]
@alafanechere @pedroslopez Could you please help check whether the `source-amazon-seller-partner` `1.3.0` was deployed to Cloud as of yesterday's push to OSS master? 

The reference PR is here: 
https://github.com/airbytehq/airbyte/pull/27110

**Comment by pedroslopez** [comment]
@bazarnov Yes, the version was deployed to cloud but a frontend check is hiding it from being used. Re-enabling in this PR https://github.com/airbytehq/airbyte-platform-internal/pull/7296.

**Comment by bazarnov** [comment]
@pedroslopez I didn't realize we hide it there, my bad. Thanks for the quick fix.

**Comment by xrossdock** [comment]
Not sure if anyone else is having issues with their Amazon Seller Partner source. My connection is currently failing, attempt to re-authenticate the source results in:

"OAuth login failed: Internal Server Error: java.io.IOException: Missing 'refresh_token' in query params from https://api.amazon.com/auth/o2/token"

<img width="498" alt="image" src="https://github.com/airbytehq/airbyte/assets/124578341/f2692575-449c-47cb-a889-4a5964b77594">

**Comment by streveg** [comment]
Did you actually manage to get it working? I never managed to get it working myself last year and gave up on it.

**Comment by xrossdock** [comment]
> Did you actually manage to get it working? I never managed to get it working myself last year and gave up on it.

Yep it was working fine November and December of 2023. It started failing this week. Very odd.

@streveg are you using a different solution for the Amazon Seller Partner source?

**Comment by klunejko** [comment]
@xrossdock Just signed up for airbyte cloud and tried setting up Amazon SP and getting the same error.
