### ISSUE TITLE
Platform Issue: non-json response error after refresh Salesforce source schema

### ISSUE THREAD

**Issue by jack-fireworkhq** [airbytehq/airbyte#25788]
### Platform Version

0.39.23-alpha

### What step the error happened?

During the Sync

### Revelant information

I have a Salesforce to Snowflake connection which was stuck at syncing for a really long time:
![image](https://user-images.githubusercontent.com/80802145/236152147-7ae24f8a-5065-490f-b458-3118980d7afe.png)
I assume its because there was a big schema change in Salesforce, so I refreshed the source schema and tried to `save changes & reset data`.But I got an error like below shows:
![image](https://user-images.githubusercontent.com/80802145/236152782-3967cdd7-e2ab-48ef-82ae-e35ae2f7e52f.png)
![image](https://user-images.githubusercontent.com/80802145/236152790-167dc9e8-05ce-430d-b04f-f599b8b0f696.png)

How am I supposed to fix this?

### Relevant log output

```shell
Unfortunately, there was no log for this.
```

**Comment by mfsiega-airbyte** [comment]
We've updated this behaviour to better surface errors, so updating to a newer version should help with this. If it persists, feel free to re-open!
