### ISSUE TITLE
Octavia CLI Issue: Elements re-created when executed via GitHub action with no state files

### ISSUE THREAD

**Issue by CoDanny** [airbytehq/airbyte#25787]
### Octavia CLI Version

0.42.1

### Revelant information

I'm trying to apply AirByte settings using GitHub actions as part of a CI/CD pipeline. As per the instructions [here](https://airbyte.com/tutorials/version-control-airbyte-configurations), I'm not adding the state files to my repo, therefore every time the apply command is done, the CLI doesn't have any state files. 

The issue is that, the source, destination and connections and re-created every time the GitHub actions is executed.

According to the document linked above:

> After you apply some changes, Octavia creates a state.yaml file in the resource directory with the checksum of the latest configuration applied and the generation timestamp. The state files are instance and workspace specific so they are only useful when multiple users or Octavia CLI processes work on the same instance and workspace. If you apply the same configuration across multiple instances, then **you don’t need to commit state files in your Git repository**.

Keep in mind that adding these files to the repo would not be ideal as they're created as part of the apply command which is executed when code is merged into the main branch. At this point, the GitHub action would need to push the state files to main also. This could result in a great mess IMO.

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
