### ISSUE TITLE
Fix default SSL Mode value for postgres destination on cloud

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25804]
Set the default value of SSL Mode to `require` on destination-postgres on cloud

**Comment by sherifnada** [comment]
note: @lmossman will advocate for prioritizing this with the relevant teams (sources dbs & destinations)

**Comment by lmossman** [comment]
Replaced by:
https://github.com/airbytehq/airbyte/issues/25896
https://github.com/airbytehq/airbyte/issues/25897

To be taken on by the databases teams
