### ISSUE TITLE
[Connector Builder] Better default behavior for Step

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25803]
As discussed on slack, we should set the step to 1000 years by default so that the connector builder doesnt end up requesting a lot of duplicate records, if APIs do not support setting an end date.

In the UI, this should be shown as an optional field that is empty by default, and if not filled out it should set the step to P1000Y in the yaml manifest

**Comment by girarda** [comment]
This was implemented in the CDK. The step field defaults to `datetime.timedelta.max`
