### ISSUE TITLE
Sandbox account for Medallia

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#25806]
We need a sandbox account for Medallia to run integration tests for Medallia source connector. 

This is for the developer week hackathon, where a contributor is trying to build it in this [issue](https://github.com/airbytehq/DeveloperWeek-Connector-Contest/issues/7)

@igrankova can you please help?

**Comment by igrankova** [comment]
@bmcgilli sure, I'm taking this issue.

**Comment by igrankova** [comment]
Registered to the Medallia Partner Program, waiting for response.

**Comment by benlienart** [comment]
Up @igrankova

**Comment by benlienart** [comment]
> @benlienart, sorry, no news about the sandbox account. They don't answer.

Thanks @igrankova . Me neither ;). Medallia does not seem to cooperate. Maybe you should check with who requested the connector in the first place ? If you decided to include the issue into the bounties with @RealChrisSean , it must be aligned with Airbyte's priorities, so it should be doable :)

**Comment by igrankova** [comment]
@benlienart, I don't see any contributor who asked for this connector, so I've asked our Business Development Team for help.

**Comment by igrankova** [comment]
@benlienart I've sent an email to the standard partner auto-respond email and received an answer from the partner team! So I'm starting the conversation about our sandbox request:)
The reason they didn't answer was: "We received 2 enquiries from Airbyte, one using a gmail account and other using a generic "integration-test"@ email. We typically don't respond to these enquiries with those types of emails, so glad you have reached out directly."

**Comment by igrankova** [comment]
@benlienart, hi!
Medallia is ok with providing a sandbox for us after we go through the partnership steps and sign the docs. Also they want to know if we have any mutual customers, I'll try to find out this information.

**Comment by benlienart** [comment]
Awesome @igrankova thanks !

**Comment by igrankova** [comment]
@benlienart UPD: we are working on the partner docs signing for obtaining a sandbox.

**Comment by igrankova** [comment]
LastPass name: Medallia Partner Account
[OAuth docs](https://docs.medallia.com/en/medallia-experience-cloud/administration/security/oauth)

**Comment by igrankova** [comment]
The Medallia team is still working on out sandbox setup. They will contact us soon with update.

**Comment by Diana-Vait** [comment]
Received reply from Kevin: 
Hi Diana,
I have set you up and whitelisted your IP
Static IP: 37.53.87.234
