### ISSUE TITLE
use "title" and "description" for oneOf spec fields in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2580]
Right now the drop down label is just `some_field_here` for the example below, while it should be `My Title` and only fall back to `some_field_here` if the `title` field doesn't exist.

Also, the description doesn't show anywhere (we probably need a mockup for this). The use case I'm thinking is for something like CDC where we want to explain the pros and cons of different approaches before someone selects the replication type. 

```
"some_field_here": {
        "title": "My Title",
        "description": "Here is a description",
        "type": "object",
        "default": "Public Web",
        "oneOf": [
          {
            // whatever
          },
          {
            // whatever
          }
        ]
      }
```

It'd also be great to specify the order of the oneOf dropdown.

**Comment by cgardens** [comment]
@jrhizor why do we need mockups for the description? can we not use the existing description logic / rendering?

**Comment by jrhizor** [comment]
We may not, but oneOf uses the custom border so there isn't an automatic place to put the description. Maybe inside?

**Comment by cgardens** [comment]
Got it. Will assign to @Jamakase and let him see where it makes sense to put it.
