### ISSUE TITLE
Proposal to generify Low-code components

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#25811]

**Comment by sherifnada** [comment]
@maxi297 to add acceptance criteria

**Comment by maxi297** [comment]
- [X] Classify custom components related to stream slicing
- [ ] Create and get approved Tech Spec for top priorities (if Tech Spec is overkill, GitHub issues are just fine)

Based on the classification, we have establish the priority as following with @brianjlai :
- [Must] Nested stream slicers
- [Must] Only one slice with startdate (without enddate)
- [Should] Semi incremental (including substreams so might be dependant on “Nested stream slicers”)
- [Could] Support cursor_field in nested objects
- [Could] ListStreamSlicer if defined in config else SubstreamSlicer
- [Could] API response with multiple datetime formats
- [Could] Stream to flatten record based on list field
- [Could] Group substream records

**Comment by maxi297** [comment]
Current tech specs:
* [Nested stream slicers](https://docs.google.com/document/d/1igmtuuaefR5NQfmrVl4WHwn-sLTt-zp2TdArumfzRfM/edit#heading=h.8io22ll8bylc)
* [Only one slice with startdate (without enddate)](https://docs.google.com/document/d/1MnuVgwUeKxVKg05oT8FpaXeblnLN4S0yqtw8D5I5JIQ/edit#heading=h.oduy3wvay53)
* [Semi incremental](https://docs.google.com/document/d/14HB67V7XCBhM46UCXLlZxWLuDuXbHzbbIzcqAl_Cvt4/edit#)
