### ISSUE TITLE
Release /publish notes

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#25810]
TODO
1. Add one hour time out to all dagger (carve out timeout for nightly)
2. slack messages from dagger for job start, fail, success (@dagger-ops if fail)

Question
1. Do we have a limit on nodes
2. Can we view the k8s queue

**Comment by alafanechere** [comment]
@bnchrch I'm closing this issue as I've created separate issues following our IRL discussions. The list of requirements to remove the /publish in favor of publish on merge should now be up to date with explicit dependencies.
