### ISSUE TITLE
MYSQL CDC: Enable frequent state emission during incremental runs

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#25834]
In this PR https://github.com/airbytehq/airbyte/pull/24582 we enabled the feature for Postgres. We should do the same for MySql as well.

**Comment by cgardens** [comment]
@subodh1810 is this behavior different that postgres? my understanding is we have shared code for all CDC so shouldn't the behavior be the same? or does postgres all not emit frequently enough?

**Comment by subodh1810** [comment]
There are two things:
1. Checkpointing during initial sync (snapshot) : When we grab the existing data from the tables using select query. This doesn't exist for any CDC connector today i.e. if we fail during snapshot phase we have to start from scratch. In our current ongoing project with Postgres ctid this would be taken care of. We would do snapshot of streams via ctid and this would introduce checkpointing as well (draft [PR](https://github.com/airbytehq/airbyte/pull/27652)). But this implementation is specific for Postgres and can not be extended to MySQL.
2. Checkpointing during incremental syncs : This is when we start processing the logs (WAL for Postgres, Binlog for MySQL, etc.) This has checkpointing support for Postgres i.e. every 15 minutes or 10K records we emit a state. This is not there for MySQL (we emit a state only at the end of the sync) but the code is shared and we just need to implement a couple of methods and it should be up and running for MySQL as well.

The scope of this ticket is to build support for 2nd point in MySQL

**Comment by prateekmukhedkar** [comment]
@nguyenaiden can you add some thoughts on the release and testing plan for this change?

**Comment by nguyenaiden** [comment]
[Testing plan doc.](https://docs.google.com/document/d/1m9ycIYE4zjnfxNOXWLFPB38p02RAoH2LNlZ5KKdRfhs/edit)
Since it's going to be a silent change functionally, we can release and roll this out at 100% from the start.
