### ISSUE TITLE
Allow to use a different schema for normalization

### ISSUE THREAD

**Issue by ggam** [airbytehq/airbyte#25841]
## Tell us about the problem you're trying to solve
I'm using postgres destination with normalization enabled. Both `_airbyte_raw_` and normalized tables end up in the same schema.
I don't want to mix Airbyte internal tables with normalized objects. Also, since I don't plan to use the Airbyte internal tables, I might even drop them after synchronization. Having them in a separate schema would be cleaner and easier to manage.

## Describe the solution you’d like
I'd like to be able to select the destination schema for the normalized tables, in addition to the raw schema that's customizable today.

The new field would be available on the replication screen, only when normalization is enabled. Something like:
![Proposed design](https://user-images.githubusercontent.com/2109040/236467833-e654d07e-12cc-4bda-804f-cbca5bebe537.png)

## Describe the alternative you’ve considered or used
I can customize the Airbyte generated dbt script, but I prefer not to, so it handles schema upgrades automatically for me.

**Comment by davinchia** [comment]
Please see https://github.com/airbytehq/airbyte/issues/26028
