### ISSUE TITLE
Auto-schema Import and null-type detection

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#25857]
The current schema import UX is not ideal, as users are required to manually import schemas for each stream whenever they change, even though the schema doesn't have any visible effect on the behavior of the Testing panel.

To make this easier for users, we want to make the following changes:
1. Automatically import the detected schema of the stream on every Test
2. Allow users to disable the automatic importing, in which case they are allowed to manually edit the Declared Schema again and the warnings for differences between declared and detected schema are shown as they are today
3. Before publishing, check if the declared schemas for any stream have any field in which the `type` is set to `null`. If so, require that the user adds another type to it, e.g. changing it from `type: null` to `type: [null, string]`. The connector should only be allowed to be published if every occurrence of `type: null` in every stream has been manually corrected

The design for (3) will likely be the most complicated part here, since it requires users to fix potentially multiple occurrences in multiple streams. Here is one example: for this stream, the type of the `primary_group_name` was detected as `null`, because every record returned by the API had a `null` value for that field:
<img width="600" alt="Screen Shot 2023-05-05 at 4 12 39 PM" src="https://user-images.githubusercontent.com/22731524/236583371-701dad7e-cc39-404b-9440-2aa004a886fc.png">
In order for this stream to be valid and publishable, that field's type in the schema would need to be corrected to something like this:
<img width="600" alt="Screen Shot 2023-05-05 at 4 13 05 PM" src="https://user-images.githubusercontent.com/22731524/236583476-bcb88f30-47a1-4728-baf9-a346c3ba8a39.png">

And if there are more fields with the same issue, they all need to be corrected. Ideally, the UI would direct the user to each of these occurrences and give the user a quick and easy way to specify an additional type for each one.

Relates to https://github.com/airbytehq/airbyte/issues/25321

**Comment by Upmitt** [comment]
https://www.figma.com/proto/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?page-id=3589%3A124527&type=design&node-id=4409-141994&viewport=650%2C570%2C0.22&scaling=min-zoom&starting-point-node-id=4409%3A141994&show-proto-sidebar=1
