### ISSUE TITLE
Source MySQL: MySQL CDC to S3 Loop Stream Buffer

### ISSUE THREAD

**Issue by cnx-lucaspassos** [airbytehq/airbyte#25872]
### Connector Name

source-mysql

### Connector Version

2.0.20

### What step the error happened?

During the sync

### Revelant information

The MySQL CDC Incremental sync are failing after a looong time trying to sync the data. When we look at the logs, we clearly see a loop (like a streaming process) to capture new streams from the binlog buffer. After hours running the mysql disconnects the airbyte process. I don't think this is the normal behaviour for a sync using MySQL CDC.

When we look at our S3 bucket we seee hundreds of small files there - for each stream.

The scenario:
AWS EC2 Airbyte Instance running 0.44.4 version
Source: AWS Aurora MySQL Cluster - Using CDC
Destination: AWS S3

I'm attaching a sample log.

### Contribute

- [ ] Yes, I want to contribute

**Comment by cnx-lucaspassos** [comment]
[659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_893_txt.txt](https://github.com/airbytehq/airbyte/files/11413820/659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_893_txt.txt)
[659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_891_txt.txt](https://github.com/airbytehq/airbyte/files/11413821/659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_891_txt.txt)

Sync Logs

**Comment by prateekmukhedkar** [comment]
@cnx-lucaspassos Can you try with the latest version of MySQL connector (3.x)? We made some improvements to how we sync incremental changes in CDC mode, including checkpointing, so in case of any failures we don't start reading the binlog from the beginning. 

Do note that we announced a breaking change to MySQL - as you are on 2.0.20 you will need to apply the changes that we communicated on Aug 8 before upgrading to 3.x. Please let me know if you need more info about upgrading to latest version of the connector.

**Comment by cnx-lucaspassos** [comment]
@prateekmukhedkar,

I have upgraded the version. But it seems the loop still happens. For the logs, it seems the connector does not stop after flush all updates, it checks for new ones and start all over again the process for the tables with any new record.

**Comment by cnx-lucaspassos** [comment]
[659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_2036_txt.txt](https://github.com/airbytehq/airbyte/files/12537066/659329d4_3ad9_4168_9cdc_0cf5c71bf15e_logs_2036_txt.txt)

**Comment by akashkulk** [comment]
Closing as we won't be working on this anytime soon
