### ISSUE TITLE
Display Connector Certification status in the UI, API, and connector documentation

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2588]
## Tell us about the problem you're trying to solve
As much as possible, Airbyte tries to ensure a minimum (high) quality bar all connectors. Typically this requires us to do the following: 

1. Create a test/sandbox account for the underlying service in question. This is sometimes tedious (requires multiple conversations with a sales team) or expensive (requires paying a large annual subscription). 
1. Populate the account with data such that all the streams the Airbyte connector syncs can be tested. Again, this can also be expensive (e.g: need to perform monetized action) or tedious (requires a lot of actions in the UI or API) or both. 
1. Test the data in the account in CI/integration tests

In some cases, it's difficult to do all of the above. For example, some connectors like Appsflyer (#1650) or AppStore (#2229 ) require creating an actual iOS or Android application, publishing it on the appstore, implementing some features in it, etc.. This requires a lot of investment on Airbyte's side. 

Stepping back, we want to have the following categorization of connectors: 

1. "most important" connectors should be completely supported and certified by Airbyte. These are the "big" connectors e.g: Postgres, Google, Facebook etc... For these connectors, nothing about the above process will change: because they are crucial to a large subset of Airbyte users, these connectors and their quality will be completely guaranteed by Airbyte. 
1. "niche" connectors that are highly valuable to a small subset of users. These connectors are not guaranteed completely by Airbyte (but can still be made available to all Airbyte users via the UI etc.. but they will just come with the caveat that it's not guaranteed by Airbyte). 

Some concrete things we'd like to do here are: 

1. Setup a clear delineation of which connectors are Airbyte certified and which are not/community supported. Something like [DBT's adapters page](https://docs.getdbt.com/docs/available-adapters). 
1. Make this distinction visible in the UI, API, and connector documentation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368097330091) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
We need to have a plan on how to reply to users when having problems with those "niche" connectors. WDYT @sherifnada?

**Comment by misteryeo** [comment]
Closing this as we've implemented certification statuses
