### ISSUE TITLE
UI enhancement: Change the default SSL method to required in all supported major source connectors

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#25896]
A work that was done for source-postgres had shown significant improvement in give-up rate when UI has the require ssl option selected by default.
Copy this learning to all relevant major source connectors. namely mysql, mssql and their flavors (e.g alloy-db) and their strict encrypt versions.

**Comment by nataliekwong** [comment]
I checked Postgres, MySQL, and Alloy and it looks like the default is set to 'require', so it seems like the change has been made. Should this remain open?
