### ISSUE TITLE
New Destination: Amazon Aurora 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2590]
## Tell us about the new integration you’d like to have
I would like to push data to Amazon Aurora DB.

**Comment by brunoffaustino** [comment]
For our use case, for a possible migration to Airbyte, we also need Aurora supported by Airbyte

**Comment by sherifnada** [comment]
@brunoffaustino we support postgres, and users have successfully reported being able to use it for aurora . Does the Postgres connector fulfill your use case or does it not work with your version of aurora?

**Comment by brunoffaustino** [comment]
Thanks @sherifnada i noticed later on that you do, that is why i hid the comment. Thank you for your reply 🙏🏻

**Comment by sherifnada** [comment]
I'll close this issue for now, please reopen if you run into any problems!

**Comment by sherifnada** [comment]
@vsayer we support MySQL as a source -- I recommend giving that connector a try and letting us know if you face any issues. It should work with the generic mysql connector!

**Comment by vsayer** [comment]
@sherifnada Thanks! Tried the MySQL connector and looks like it's working okay so far!

**Comment by hendrikfiskhjarna** [comment]
I try to do CDC from Aurora MySQL with the standard connector, but it complains that the `log_bin` variable is set to `OFF`. Binary logging is enabled and working on our DB instance, but Aurora MySQL does not seem to use the `log_bin` variable, so I can't set it to `ON`. Are there any workarounds?
