### ISSUE TITLE
Snowflake Performance: Understand cost (in time) for `COPY` vs `PUT` query

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#25933]
## What 

Currently, the staging connector will flush data using a combination of two operations, PUT & COPY

There's no firm belief on whether COPY is performant while uploading only one file. This ticket is to spike out a branch that should confirm if:
* PUT + COPY (10 times) == PUT 10x & COPY 10 files is roughly the same

What this will confirm is whether we can gain some level of performance already with offsetting the COPY operations after a set of files have been loaded into staging

## Definition of Done

* Get a rough idea for each operation and what they look like compared to each other (10 files)
* Log more information about each step

**Comment by evantahler** [comment]
**Grooming**

* Copy - insert the data from the file into the DB
* Put - upload the file

**Comment by evantahler** [comment]
Check https://docs.snowflake.com/en/user-guide/data-load-considerations-load for learning that parallelism of COPY INTO scales with compute size (aka $)

**Comment by ryankfu** [comment]
This was not as valuable of an investigation and overall work here was largely ignored in favor of tuning the Batch size of the records, the number of records and reducing the memory overhead of deserializing a JSON strong to a JsonNode object
