### ISSUE TITLE
BigQuery integration on Segment doesn't work

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2594]
As you can see here: https://app.segment.com/airbyte/warehouses/thPpAvZLdE3VywtR39yNfP/sources/5V9hV7RVkLce3QnrphhC2r/sync-history
It seems the check_connection doesn't go through

**Comment by davinchia** [comment]
I've reset all the configuration following the instructions: https://app.segment.com/airbyte/warehouses/2Z669pBru6z6CESbdhaZmk/overview

I am currently waiting for the first sync to confirm this works.

**Comment by davinchia** [comment]
confirmed with Marcos this is working - resolving
