### ISSUE TITLE
detect when a version upgrade process needs to happen

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2595]
We get a lot of support requests on Slack that are due to not running migrations. This is inevitable because I think most people wouldn't think to check documentation to see if they can upgrade instead of just running `docker-compose down` -> `git pull` -> `docker-compose up` and then running into hard to debug errors.

It should be easy to freeze the UI on a loading screen with instructions to run the upgrade process.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368155806882) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Currently, a check is made in `ServerApp` and `SchedulerApp` (not in the UI) and throws an exception with links to the docs for upgrading:
https://github.com/airbytehq/airbyte/blob/a3bc54bee7f6e2c63d2aa2d97ad8cbf797a74315/airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteVersion.java#L114

**Comment by cgardens** [comment]
Good point. I guess we should have a static page fo r this just like we do for server isn't up yet and javascript enabled?

**Comment by cgardens** [comment]
@jrhizor @ChristopheDuong any idea for how the UI can detect this? If I recall, the server never starts up successfully, so the UI can't rely on a message from the server in this case. How can the UI figure this out?

**Comment by ChristopheDuong** [comment]
> @jrhizor @ChristopheDuong any idea for how the UI can detect this? If I recall, the server never starts up successfully, so the UI can't rely on a message from the server in this case. How can the UI figure this out? I want to prioritize this, but we should figure out a reasonable approach so that we don't send @Jamakase on a wild goose chase.

Maybe, we should stop throwing exceptions during start-up on the server-side? and have an API call for version check that the web app can query at the start to see if it needs to keep starting up or abort on the upgrade static page?

Can the server somehow shut down its other API endpoints?

The scheduler should still be able to raise an exception and dies just in case so no workers can start with a mismatched version?

**Comment by cgardens** [comment]
We might be able to get something like that to work. I wonder if we can't just have nginx return the version. I'll ask @Jamakase during our sync.

**Comment by michel-tricot** [comment]
As a header?

**Comment by cgardens** [comment]
Talked with @Jamakase about this one. Sounds like the preferred way of doing this is to allow the server to start up, but if it is in this bad state with data all endpoint will return an error response that states the problem. 

Essentially we don't want any of the application code to execute (no side effects) we want this filter to run first determine if the versions are okay and if they are not immediately return an exceptional response, skipping the rest of the stack. Maybe possible with jersey?

**Comment by jrhizor** [comment]
I'm unassigning myself now that the backend piece is done: https://github.com/airbytehq/airbyte/pull/3069

**Comment by cgardens** [comment]
@Jamakase The backend now returns an error when there is a server mismatch. All requests sent to the backend will have this error. Like we do with server is not ready yet and no javaascript, we want to have a screen in the UI that says that there is a version mismatch! and refers people to this page in the docs: https://docs.airbyte.io/tutorials/upgrading-airbyte
