### ISSUE TITLE
Source: Mixpanel - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mixpanel.com/api/2.0/engage/properties?project_id=... (via Sentry)

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#25954]
### Topic

Config error for GA connector

### Revelant information

Original issue - https://github.com/airbytehq/oncall/issues/1839

## Affected Workspace Details:  

| Environment | Affected Workspaces | Connection Link | Case/Chat Link | Sentiment | User Data Access | Reporter |
| ---- | ---- | ------------ | --------- | ---------- | ---------- | ---------- |
| cloud | a@miti.ai | [workspace](https://cloud.airbyte.io/workspaces/d2f39693-6e84-4b1f-9a8c-3a1fd6403454) | N/A | 👍 :ok: 👎 😠 | Y/N (did you ask?!?!) | Automated from Sentry |
| cloud | m.vasilev@immigram.io | [workspace](https://cloud.airbyte.io/workspaces/6b852d8f-ab50-4886-9591-ea83bb29e910) | N/A | 👍 :ok: 👎 😠 | Y/N (did you ask?!?!) | Automated from Sentry |
| cloud | istvan.meszaros.88@gmail.com | [workspace](https://cloud.airbyte.io/workspaces/fc1429ab-ac6d-415b-aedc-440b2557d65a) | N/A | 👍 :ok: 👎 😠 | Y/N (did you ask?!?!) | Automated from Sentry |

## Blast Radius
Please fill in: _Could this issue be impacting other users? if so, how many?_

## Can this issue be fixed by reverting to a previous commit or connector version?
Human: **please fill this in.**

## Steps to reproduce
When running: discover

More details in [Sentry issue](https://airbytehq.sentry.io/issues/3919607690/)
First seen: 2023-02-06T12:50:24.541000Z

## Current Behavior
*Describe what is the problem user is having.*

## Logs
```
/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py
Function: _send
Type: requests.exceptions.HTTPError

400 Client Error: Bad Request for url: https://mixpanel.com/api/2.0/engage/properties?project_id=2961067
```

## On Call Summary

| Date | Start Status | Next Step | End Status |
| ---- | ------------ | --------- | ---------- |
| 2023-04-13 | New Issue | ... | Waiting |

This issue was created by the [Sentry automation workflow](https://github.com/airbytehq/workflow-actions).

**Comment by davydov-d** [comment]
This does not look like a config error to me, rather expired credentials that are not handled properly. https://developer.mixpanel.com/reference/service-accounts#service-account-expiration
In this case, API returns error 400 which is exactly what was caught by Sentry. I'll prepare a PR to fix it
