### ISSUE TITLE
Source Oracle DB: connection test failing with non-json response in k8s

### ISSUE THREAD

**Issue by ni-jkhanna** [airbytehq/airbyte#25989]
### Connector Name

source-oracle

### Connector Version

0.3.24

### What step the error happened?

Configuring a new connector

### Revelant information

We recently configured Airbyte to run on a GKE cluster. 

When configuring an Oracle DB source, the connection tests fail with the following message - 
```
The connection tests failed.

non-json response
```

I have double checked that the cluster has connectivity to the Oracle DB, as confirmed by connecting with the Oracle client running in a pod, so the issue is likely on the Airbyte side. Worth noting, however, that there are hundreds of schemas and tables in the Oracle source, and the connection test takes quite long till it fails. But I doubt it is a timeout issue, since another Airbyte instance running in a different environment is able to successfully connect to the source.

### Relevant log output

I noticed that there is a new pod created for testing the connection - `ource-oracle-check-c54fe90c-9412-4d30-850a-573c0b522242-0-rvlii`

There are several error messages in the pod logs - 

<img width="964" alt="Screenshot 2023-05-11 at 15 57 22" src="https://github.com/airbytehq/airbyte/assets/108531284/5bbdd747-d993-48c9-a397-89b776dfed20">

### Contribute

- [ ] Yes, I want to contribute

**Comment by stephane-airbyte** [comment]
There's no actionable info. Closing for now
