### ISSUE TITLE
"default" instead of source name in breadcrumb within header of Sources detail page

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#260]
## Expected Behavior
*Tell us what should happen.*
In the header of a source detail page, the source name should be displayed instead of "default"

## Current Behavior
*Tell us what happens instead of the expected behavior.*
Instead of displaying the source name, we see "default"

<img width="1792" alt="Screen Shot 2020-09-15 at 9 28 40 AM" src="https://user-images.githubusercontent.com/68561602/93144567-0442c200-f736-11ea-95d3-faa5ab6b9758.png">

**Comment by Jamakase** [comment]
Should be already addressed in PR #257
