### ISSUE TITLE
I would like to be able to add repositories in python where I can transform any output

### ISSUE THREAD

**Issue by leandroluk** [airbytehq/airbyte#26029]
### What area the feature impact?

Connectors

### Revelant Information

My company currently uses Hevodata to perform the data injection process. We are migrating to airbyte but unfortunately there is no post transformation code that can be used.

It would be very good if it were possible to create post-transformations dependent on python code, so anyone could build their transformation however they want, including if necessary accessing other data sources to do validations, etc.

I imagine a repository with one `main.py` and an `requirements.txt` like this:

```shell
# requirements.txt
example_python_package==123
```

```python
# main.py
import uuid
from datetime import datetime

def transform(record): -> any:
    """
    do any transformation on record here like this
    """
    record['uid'] = str(uuid.uuid4())
    record['timestamp'] = datetime.now().isoformat()
    return record
```

And in the configuration like this

![image](https://github.com/airbytehq/airbyte/assets/8602982/1e2f2803-9a45-48f2-8254-31c6cdf73abf)

With this simple integration enabled for any source/destination, we can create infinity possibilities to airbyte users...

**Comment by marcosmarxm** [comment]
Bem-vindo ao projeto @leandroluk e obrigado pela contribuição!

> we are migrating to airbyte but unfortunately there is no post transformation code that can be used.

Today you can achieve this using custom transformation with dbt to transformation your data after it land to your destination. Is it your expectation to transform after or during the ingestion phase? If it's the second one... the overall recommendation as been a ELT tool to not do this during the reading-writing data but its possible to achieve overriding the `parse_response` function.

**Comment by davinchia** [comment]
Let us know if we can provide more information!
