### ISSUE TITLE
Google Analytics 4 (GA4): incremental sync on daily_active_users not fetching recent updates

### ISSUE THREAD

**Issue by alonBlyp** [airbytehq/airbyte#26054]
### Connector Name

source - google analytics 4

### Connector Version

0.0.3

### What step the error happened?

During the sync

### Revelant information

I have defined a new source: Google Analytics 4 with Postgres as destination. 
 I have tried many different configurations for it, and it all results in the same way: the incremental syncs are not collecting the data from the source properly. They are either returning partial (less data than there should be, or empty. 

Its very easy to reproduce, as it happens also with the "out of the box" streams. 
steps to reproduce:
1. Define a Google Analytics 4 source for some property that has users activity. 
2. Define the Postgres destination 
3. look into the stream that is already defined: daily_active_users
4. Give the connector to run over the next couple of days and compare it with the source - the data is partial, as in the number of active1dayusers is less than when you go to google analytics and compare the number swith the source of trurth.
5. I assume that it happens because if you collect the report at 15:00 of the previous days, and then dont refetch it again, you will not see the numbers aggregated after 15:00 (I think thats where the bug is...)

6. This bug is reproducing in custom reports as well, with various definitions of the primary keys and curosr fields
7. It also reproduces with incremental append syncs .
8. Log of the lsat sync :
[92777992_355a_4dcc_9268_ad2b87294007_logs_47190_txt.txt](https://github.com/airbytehq/airbyte/files/11471909/92777992_355a_4dcc_9268_ad2b87294007_logs_47190_txt.txt)
9.  log of the initial sync: 
[92777992_355a_4dcc_9268_ad2b87294007_logs_46445_txt.txt](https://github.com/airbytehq/airbyte/files/11471910/92777992_355a_4dcc_9268_ad2b87294007_logs_46445_txt.txt)

  10. Current data from the DB that shows the diff:
  
![image](https://github.com/airbytehq/airbyte/assets/86244085/31f8e590-404d-416e-bb59-f3bbc7a3d2fd)

11. Current data from  GA4 itself:
<img width="719" alt="image" src="https://github.com/airbytehq/airbyte/assets/86244085/2679691e-0f71-4abc-8c5d-87ecba0392fc">

12. I will be super happy to come up online and help reproduce the issues and help to solve it !

### Contribute

- [ ] Yes, I want to contribute

**Comment by alonBlyp** [comment]
I'd be happy to 
How could  I control the timing of the sync, I see I only have control over the intervals 
Should I pause it maybe and resume it at 11:59pm ?

**Comment by alonBlyp** [comment]
hey @sh4sh ,
I've resumed the connector work just before 11:59pm of the 17th according to the google analytics property timezone and indeed got much more accurate results for the 15th .
<img width="1238" alt="image" src="https://github.com/airbytehq/airbyte/assets/86244085/3b4abcbf-02d4-4096-9407-9ecf10fd514b">

Now let's see what will happen on the 16th an onward for the next couple of days.

@sh4sh I still have the remaining question of controlling the sync times, mind you that I have now 100+ connectors, and soon I'm going to be going to 500+.
I control the connectors via API and I constantly shut connectors off and create new ones programmatically

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/26283
