### ISSUE TITLE
Source Zendesk Support: ticket_metrics stream pagination limit

### ISSUE THREAD

**Issue by williamangelo** [airbytehq/airbyte#26055]
### Connector Name

source-zendesk-support

### Connector Version

0.2.29

### What step the error happened?

During the sync

### Revelant information

`TicketMetrics` stream is defined as cursor pagination (https://github.com/airbytehq/airbyte/pull/13757) in order to avoid rate limits of the Zendesk API. This behaviour is currently not working as intended, the api calls are still paginated via offset mode.

Syncs that fetch more than 100k records will still reach pagination limits and return `Response Text: Pagination limit reached for offset model`. According to the [Zendesk documentation on cursor pagination](https://developer.zendesk.com/api-reference/introduction/pagination/#using-cursor-pagination) the correct parameter for page size is `page[size]` (instead of the current `per_page`), omitting this parameter will default to offset pagination.

### Contribute

- [ ] Yes, I want to contribute

**Comment by lideke** [comment]
same issue : https://github.com/airbytehq/airbyte/issues/26748

**Comment by btkcodedev** [comment]
I would like to work on this

**Comment by btkcodedev** [comment]
Already been solved through https://github.com/airbytehq/airbyte/pull/26945
Check comments in https://github.com/airbytehq/airbyte/pull/27070 for reference
Please close issue
