### ISSUE TITLE
Source AWS: setup source creates 2 keys in AWS KMS and keys are not deleted where source is deleted

### ISSUE THREAD

**Issue by anna-lisniak** [airbytehq/airbyte#26064]
### Topic

AWS KMS

### Revelant information

Hello,

When I create a new source I can see that 2 new keys are constructed in AWS KMS.

Keys look like `airbyte_workspace_{workspace_id}_secret_{uuid}`
The first key has correct workspace_id, but the second key has `workspace_id = 00000000-0000-0000-0000-000000000000`

Also, when I delete the source, the keys are not deleted in KMS.

Is there any hidden logic I didn't notice, or is it a bug?

**Comment by davinchia** [comment]
This is not a bug. We do not delete secrets in the secret store today. Unfortunately we probably won't take this on in the near future.
