### ISSUE TITLE
No octavia-cli version 0.44.3 available

### ISSUE THREAD

**Issue by Ouuumar** [airbytehq/airbyte#26062]
### Octavia CLI Version

0.44.3

### Revelant information

Currently installing octavia cli with `curl -s -o- https://raw.githubusercontent.com/airbytehq/airbyte/master/octavia-cli/install.sh | bash` 

- Then command octavia do not exist in my terminal.

- I have checked the docker hub, https://hub.docker.com/r/airbyte/octavia-cli/tags#! last version is 42.1
 
- So I have modified in the install.sh file the octavia VERSION=0.44.3 to VERSION=42.1 https://github.com/airbytehq/airbyte/blob/master/octavia-cli/install.sh here line 6

The version need to bu updated in the install.sh file or the image of octavia-cli should be pushed to the docker hub

**Comment by shashanksinghfd** [comment]
I think its same issue as https://github.com/airbytehq/airbyte/issues/26206

**Comment by rileybrook** [comment]
The Octavia image will be updated to 0.44.4 later today or early next week 🙂

**Comment by Ouuumar** [comment]
> I think its same issue as #26206

Yes thanks we opened as nearly as the same time the issue. It has been closed, so closing mine alsotahnk you !
