### ISSUE TITLE
Source Google Analytics (GA4): Fix Pagination

### ISSUE THREAD

**Issue by mpetrykin** [airbytehq/airbyte#26066]
### Connector Name

source-google-analytics-data-api

### Connector Version

0.2.2

### What step the error happened?

Other

### Revelant information

Right now the connector does not handle pagination. The **next_page_token** method checks whether **offset** and **limit** parameters are present in the response, but it does not return them according to the [documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/RunReportResponse).
You can see only the **row_count** field come from response.
![image](https://github.com/airbytehq/airbyte/assets/40140203/527ff7df-585a-41f8-95a2-e480244f297c)

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@mpetrykin please update the title to follow the convention `Source Google Analytics: issue`

**Comment by marcosmarxm** [comment]
The PR was escalated to GL Team.

**Comment by mpetrykin** [comment]
The issue was resolved by https://github.com/airbytehq/airbyte/pull/26126
