### ISSUE TITLE
Improve RetryWithJitter

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#26084]
## Context

RetryWithJitter is static which makes testing hard.

RetryWithJitter swallows API exceptions (all non-200 resp's are considered API exceptions by the generated clients) and retries even when it's not ideal (e.g. why retry a 404? What if the caller wants that information).

RetryWithJitter's last retry has 10 minutes of backoff. Sometimes you want to opt into retries, but can't afford to block for 10 minutes.

## Background
Some original context for why this was added/designed is [here](https://github.com/airbytehq/airbyte/pull/19693)

## Proposed solution

Find a better pattern, one candidate could be to add a Singleton that handles the retry wrapping that could be injected for tests.

[EDIT: added new line items and background]

**Comment by davinchia** [comment]
The right pattern here is https://github.com/airbytehq/airbyte-platform-internal/pull/8329.
