### ISSUE TITLE
dagger: corrupted image being published?

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#26085]
I face an occasional problem while publishing an image with the code [here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/publish.py#L62)

1. I build a connector container successfully
2. I can run commands again this container successfully (the `spec` command)
3. The image is pushed successfully to DockerHub

When I try to pull the image to test it out I face the following error:
`failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header`

It happens for the following image:
`docker pull  --platform linux/arm64 airbyte/destination-postgres-strict-encrypt:0.3.27-dev.bd80936152`
`docker pull  --platform linux/amd64  airbyte/destination-postgres-strict-encrypt:0.3.27-dev.bd80936152`

I tried to pull both image architecture and faced the same problem.
[Pipeline](https://github.com/airbytehq/airbyte/actions/runs/4983199283) that led to the publication of this image.

I suspect something wrong happens on call to the Dagger publish function.
**I could not reproduce this problem locally nor on subsequent run of the same pipeline in the CI.**

**Comment by alafanechere** [comment]
@sipsma thank you for trying out.

The `failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header` is the output of my local `docker pull` command. Nothing looks suspicious during the dagger execution.

I also tried to use this image in Dagger code:
```python
import anyio
import dagger

async def main():
    async with dagger.Connection() as client:
        ctr = (
            client.pipeline("test")
            .container()
            .from_("airbyte/destination-postgres-strict-encrypt:0.3.27-dev.bd80936152")
            .with_exec(["spec"])
        )
        output = await ctr.stdout()
        print(output[:300])

anyio.run(main)
```

and face the following error:
```
dagger.exceptions.QueryError: runtime error: index out of range [0] with length 0
```

**Comment by alafanechere** [comment]
Thank you @sipsma for the deep investigation and the clear explanations!
You're right that we can't easily force our users to upgrade their Docker engines and more flexibility on the Dagger side would be appreciated. Nevertheless, we currently do not require a specific Docker version [here](https://docs.airbyte.com/quickstart/deploy-airbyte) and I think it'd be great to require a recent version that matches these new performance features. @cpdeethree what's the docker version used in our production Kubernetes clusters?


@sipsma after re-running the same pipeline on the same connector, without code change, I did not face the original problem. So it would mean different buildkit layers are used and it characterizes in inconsistency in our pipeline code?
Finally, I think it's more reasonable to wait for the follow ups on your side before pushing this specific pipeline to production.

**Comment by sipsma** [comment]
@alafanechere 
> after re-running the same pipeline on the same connector, without code change, I did not face the original problem. So it would mean different buildkit layers are used and it characterizes in inconsistency in our pipeline code?

Not necessarily, whether you get a cache hit is not easy to control and reproduce in practice. If there is any difference in any input (even miniscule stuff like timestamps on files, which especially impacts use of local dirs) then you won't get a cache hit. Depending on what these layers are, it's also possible for them to exist in both gzip and zstd formats in buildkit's local state, in which case it may be hard to repro which one gets chosen.

> Finally, does pinning Docker 20 on our CI Cluster would guarantee that no ztsd compressed layer make their way into our images?

No, I think the only way is for Dagger to address the issue. It's quite easy since buildkit already supports the feature we need (force a certain compression), we just need to expose it. I will let you know when it's ready, should be very soon.

**Comment by cpdeethree** [comment]
So after some investigation:

actions-runner-controller uses two container images. These are defined in the helm chart (or manifests, if you do it that way)

The first one, "runner", we already build/publish our own runner images for and it uses the correct docker 20 (airbyte/actions-runner:latest)

The second, "dind", is the problem child. It uses latest right now (simply docker:dind). There is a docker:dind that targets 20, but it has some very nasty looking CVE's: https://hub.docker.com/layers/library/docker/20-dind/images/sha256-11a8556b63283fb6edb98fc990166476bc2e14b33164039ab6132b27d84882d8

As a theoretical short term fix, I could try to see what it would take to patch these and run our own version, but that would be a very short term thing only, we don't want to be in the business of maintaining ancient, scary versions of dind where new CVE's could pop up at a moment's notice

**Comment by alafanechere** [comment]
On the pipeline side I've added a step to make it fail if it contains zstd compressed layers:
https://github.com/airbytehq/airbyte/pull/26138

**Comment by cpdeethree** [comment]
After checking and noticing that docker:dind has the exact same cve as docker:20-dind went ahead and made the temporary change to use this instead as it's not a regression from current behavior

**Comment by alafanechere** [comment]
I upgraded our publish pipeline to use Dagger 0.5.4 to use the `force_compression=Gzip` flag: https://github.com/airbytehq/airbyte/pull/26291
The check on publish asserting that all our image layers are Gzip is passing.
I'm considering this issue as solved. Thank you so much @sipsma for the quick improvement.
