### ISSUE TITLE
Indicate a user should sync after a reset

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26092]
Within the stream view:
- The message in the UI shows that the connection is Up to date
- The stream says the Last Record Committed was X minutes ago (the time of the Reset)

This is confusing because it sounds like a sync ran, and I have fresh data, but it is actually the opposite (I have no data)

Suggestion:
- Guide the user to sync the data. The last record committed timestamp is not correct. 

![Screen Shot 2023-04-26 at 1 15 11 PM](https://github.com/airbytehq/airbyte/assets/38087517/eefafc7f-357f-46e4-8bb7-d80242f49587)

![Screen Shot 2023-04-26 at 1 11 28 PM](https://github.com/airbytehq/airbyte/assets/38087517/09f6731b-f168-4b1b-b12b-0181ceca7df1)

From this Slack thread: https://airbytehq-team.slack.com/archives/C04JRD0BY4B/p1682532927081619
cc @chandlerprall

**Comment by josephkmh** [comment]
Refining notes:
- Solution idea: new icon that indicates that the most recent action was that the stream was reset
- Should be clear that the user (probably) needs to take action to sync it
- Resets can basically be treated as a stream that has never been synced

**Comment by nataliekwong** [comment]
Another piece of feedback worth considering is that the concept of "success" for a reset isn't necessarily intuitive, or at least the way that we show it can be confusing.

If the goal to successfully sync data, then a reset that doesn't sync data means something different to ths user, even though it has the same icon and looks in the job history the same as the other sync jobs. 

A user might expect that data should have been synced (because the history with other attempts shows those stats). 

Questions from me:

**Comment by nataliekwong** [comment]
Closing for now, as we scope for 1.0 what actual changes we want here, and will have Nora share designs if needed.
