### ISSUE TITLE
Source LinkedIn Ads: Breaking Changes to the LinkedIn Ads Connector starting 30.06.2023

### ISSUE THREAD

**Issue by vincent-el** [airbytehq/airbyte#26107]
### What area the feature impact?

Connectors

### Revelant Information

see https://learn.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes?view=li-lms-2023-05

especially changes in Base URLs will break the current connectors

**Comment by artem1205** [comment]
Connector uses API version `202305` since 0.2.0, see https://github.com/airbytehq/airbyte/pull/26372 for more info
