### ISSUE TITLE
Connector builder: Improve display of array example values

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#26116]
### What area the feature impact?

None

### Revelant Information

In connector builder tooltips, array example values are shown like this:

![Screenshot 2023-05-15 at 1 02 57 PM](https://github.com/airbytehq/airbyte/assets/1508364/22e40c1d-f938-4f08-a297-e6666c37704d)

It's not clear how these should be entered into the tag input below - it's easy to think it should look like this:
![Screenshot 2023-05-15 at 1 08 31 PM](https://github.com/airbytehq/airbyte/assets/1508364/ac79acf3-592e-4171-b931-c29a4b187533)

There should be a special display (maybe grouped pills or something like this) for array example values specifically.

**Comment by lmossman** [comment]
Grooming notes:
- If the example is an array, don't simply stringify. Don't render the brackets and quotes, but _do_ render the commas in between each item
- Stretch goal: see if there is a simple way to get the nicer array value [design](https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?type=design&node-id=2652-115353&t=onxGQQjqMWHmvx5A-0)
