### ISSUE TITLE
Track the connector version for syncs in Segment

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#2615]
##Tell us about the problem you're trying to solve
When we identify issues with connectors, it could be interesting to know which connector version they are. 

Describe the solution you’d like
Add properties connector_version for Connector Jobs when job_type=SYNC.

Here's the updated Segment spreadsheet: https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

@cgardens

**Comment by ChristopheDuong** [comment]
@johnlafleur 

Since there are 2 connectors during sync, shouldn't we call them `connector_source_version` and `connector_destination_version` instead?

Would you need the versions when new connection are created too? (`New Connection - Backend` event)

**Comment by johnlafleur** [comment]
Yes for the names.

Regarding "New Connection - Backend", no need :). Thanks!

**Comment by ChristopheDuong** [comment]
Re-opening as it doesn't seem to properly print it yet
