### ISSUE TITLE
Align the colors of the "schema changes detected" banner in stream-centric view

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26170]
We have two different colors for the same banner on the stream-centric view:
We use this color for the header banner: --color-yellow-50
And this color for the alert banner: --color-blue-50

We also have an indicator on the Connections.List page (exclamation icon) that appears in yellow. We should align the banners with the same message to the same color, and I lean towards yellow to align it to the Connections.List alert icon and differentiate it from the Free connector program banner. 

Example:
![Screenshot 2023-05-16 at 4 43 36 PM](https://github.com/airbytehq/airbyte/assets/38087517/ac5db7e2-9c86-4485-b3ee-311beff89fe8)

cc @chandlerprall

**Comment by josephkmh** [comment]
Refining notes:
- The non-breaking schema updates detected banner should be yellow
- The banner in the header has been removed in the new design, so the banner will only appear once on the page

**Comment by nataliekwong** [comment]
Same feedback also was noted here: https://github.com/airbytehq/airbyte/issues/26349

**Comment by josephkmh** [comment]
Thanks! @chandlerprall I'm closing this issue in favor of https://github.com/airbytehq/airbyte/issues/26349 FYI
