### ISSUE TITLE
Source S3 - Do not recognize the right data type of column

### ISSUE THREAD

**Issue by quangdvn-sun** [airbytehq/airbyte#26181]
### Connector Name

S3

### Connector Version

0.1.29

### What step the error happened?

During the sync

### Revelant information

When syncing a stream (CSV column) with `float` data value and `infer_datatypes` set to ON
S3 connector auto detect the stream (Column) data type as integer, which causes the sync flow failed

### Relevant log output

```shell
In CSV column #40: CSV conversion error to int64: invalid value '1.5'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by girarda** [comment]
closing because the s3 source has been revamped in the last year. feel free to reopen if this is still an issue
