### ISSUE TITLE
 Add support for validate the destination or source When performing an octavia apply.

### ISSUE THREAD

**Issue by hansh0801** [airbytehq/airbyte#26185]
### What area the feature impact?

Airbyte Platform

### Revelant Information

Currently, we're trying to do this with the octavia cli in a github action.

I would like to do a dry run to make sure the configuration is valid before proceeding with the octavia apply, but there is no such feature.

I would like to see some logic added to dry run or validate in the octavia cli.

ex ) octavia apply --file name {PATH} --dry-run

It would be nice to have such logic configured.

**Comment by marcosmarxm** [comment]
Octavia was removed from the main repo and won't receive updates anymore.
