### ISSUE TITLE
Link to tutorial

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#26201]
We have a nice tutorial for the connector builder, but it's kind of hard to discover. We should link to it from the UI somehow

**Comment by Upmitt** [comment]
https://www.figma.com/file/F1ljvrJerLoVbNvtejBWid/LOW-CODE-CONNECTOR-BUILDER?type=design&node-id=4510-143993&t=mEqdKeH4F67Ma1WQ-4

**Comment by Upmitt** [comment]
https://www.loom.com/share/04c0de6cc2d446788d71c9d7b4253309
