### ISSUE TITLE
Ingest files from a directory

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2622]
## Tell us about the problem you're trying to solve
* I have a directory on S3. New files are added to that directory on some cadence. Whenever a new file is added to the directory I want to sync that data to a destination. The names of the files are monotonically increasing and could be used as cursor fields.

## Describe the solution you’d like
* This is either a new feature in the file source or a new connector altogether.

heads up sherifnada

requested by SG. tagging roshan

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368221003608) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@roshan would all the files have the same schema/contribute to the same stream?

**Comment by roshan** [comment]
Yes, they represent a group of new records into the same stream.

**Comment by roshan** [comment]
If you would like, it is possible to arrange it so that each prefix represents a stream. I am happy to work with whatever method you think is most general.

**Comment by sherifnada** [comment]
related: 

https://github.com/airbytehq/airbyte/issues/1874
https://github.com/airbytehq/airbyte/issues/2512
https://airbytehq.slack.com/archives/C019WJFR1JT/p1616080620015200

**Comment by harshithmullapudi** [comment]
wouldn't it be good to solve independently for sources like S3, Google Storage as the s3-csv tap

**Comment by harshithmullapudi** [comment]
We have a usecase for which we need to solve this for S3. Thinking of bringing that tap-s3-csv to airbyte any thoughts here

**Comment by Phlair** [comment]
Brainstorm & MVP definition:
https://docs.google.com/document/d/1YbY9Css9e_4jRiKkkB60CfrUNkdr1Sx72ElPmANy0gU/edit#

**Comment by cgardens** [comment]
@Phlair can we close this?

**Comment by Phlair** [comment]
There's still outstanding work to extend this across formats / storage providers but those are all separate issues so this can be closed.
For sake of creating a trail back to this issue:
https://github.com/airbytehq/airbyte/issues/5116 https://github.com/airbytehq/airbyte/issues/5115 https://github.com/airbytehq/airbyte/issues/5113 https://github.com/airbytehq/airbyte/issues/5111 https://github.com/airbytehq/airbyte/issues/5110 https://github.com/airbytehq/airbyte/issues/5109 https://github.com/airbytehq/airbyte/issues/5108 https://github.com/airbytehq/airbyte/issues/5107 https://github.com/airbytehq/airbyte/issues/5106 https://github.com/airbytehq/airbyte/issues/5105 https://github.com/airbytehq/airbyte/issues/5103 https://github.com/airbytehq/airbyte/issues/5102
