### ISSUE TITLE
Source Harvest: new stream Users

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26221]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Users](https://help.getharvest.com/api-v2/users-api/users/users/)
**Required permissions**
[⚭](https://help.getharvest.com/api-v2/users-api/users/users/#required-permissions)
You must be an Administrator or Manager with assigned teammates in order to interact with the `/v2/users` endpoint, except when retrieving the currently authenticated user. Managers cannot edit emails, roles, or permissions, nor can they archive, restore, or delete assigned temmates. Managers with permission to see billable rates will have access to their teammates’ default hourly rates. Insufficient permissions will result in a` 403 Forbidden` status code.

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by btkcodedev** [comment]
Analysis: Source Harvest has already stream Users
Ref:- https://github.com/airbytehq/airbyte/blob/33ca41b737909df39240194edb2ca36ded272ce7/airbyte-integrations/connectors/source-harvest/source_harvest/streams.py#L253
