### ISSUE TITLE
Source Youtube Analytics: Migrate to advancedAuth

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#26250]

**Comment by nataliekwong** [comment]
Hey @lazebnyi - I'm working on the improvement of error messages shown during source checks.

This is the most common error message by far that the error emits today:
"The Youtube account is not valid. Please make sure you're trying to use the active Youtube Account connected to your Google Account."

I myself have run into this error, despite being a manager of Airbyte's YouTube account. Will this PR address the authentication issue and error I'm seeing?

**Comment by lazebnyi** [comment]
Hey @nataliekwong 
I guess better separate your issue from this one, because this issue about refactoring to new structure to support advancedAuth.

**Comment by nataliekwong** [comment]
Got it, thanks!
