### ISSUE TITLE
Destination: Clean up Integration Test tables

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#26276]
### Connector Name

destination-snowflake

### Connector Version

latest

### What step the error happened?

Other

## What

This applies to Snowflake and all destination integration tests that use a shared resource for testing purposes. In the `tearDown` process of the tests it doesn't clean up the tables it written to

##
At minimum write logic to delete tables after each test is completed for destination since there's state (aka records) stored within the destination storage. Examples of this would be `BigQueryDestinationTestUtils#tearDownGcs` which deletes the object within the GCS bucket

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
If you find yourself looking at this issue because there are too many schemas in snowflake again, because we haven't done this story yet, there's a hack!

```sql
USE DATABASE INTEGRATION_TEST_DESTINATION;
SHOW SCHEMAS;

-- hack to load scheams which have a cetain owner
SHOW SCHEMAS LIKE 'AIRBYTE_SOURCE_NAMESPACE%';
SELECT 'DROP SCHEMA ' || "name" || ';'  FROM TABLE(result_scan(last_query_id())) WHERE "owner" = 'INTEGRATION_TESTER_DESTINATION';
-- then download the results of a CSV and paste them in below the line and run them all by highlighting them all
```

**Comment by evantahler** [comment]
There's an infra/GHA version of this story we will do instead
