### ISSUE TITLE
Periodically checkpoint state during syncs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2627]
## Tell us about the problem you're trying to solve
Today if a sync fails or is cancelled, Airbyte doesn't store the latest state output from that sync. State is only updated when the sync is successful. 

This is a problem for halfway failures or cancellations e.g: 

* there is more data in the source than the rate limit allows the connector to pull
* a transient failure happens after a large % of data has been replicated

in these cases, because the sync worker doesn't store the latest state output from the connector, the next time the sync runs, it runs from the beginning rather than picking up where it left off. In the first case in particular, the user cannot use Airbyte for syncs because it will fail, not save state, then sync from the very beginning and fail again etc.

## Describe the solution you’d like
I would like Airbyte to store the latest state output from the connector. 

The solution is complex because we only want to persist state if we are sure it was written to the destination, otherwise we could drop records. So the solution involves two things: 

1. Change destinations so that they ACK messages that they wrote2. 
1. Sync worker should persist state based on destination ACKs

For reference, Singer does this as follows: 

1. The destination receives STATE and RECORD messages. Those are expected to be ordered: if messages 1-3 are RECORDs and message 4 is a STATE message, then beginning a new sync using the state from m4 should pull message 5 onwards. 
1. Once the destination has persisted all RECORD messages, it outputs the next STATE message on stdout i.e m4 from the example above
1. The consumer is expected to monitor a destination's stdout for STATE messages and always save the latest STATE message as the most up-to-date state

## Acceptance Criteria
1. Sync workers periodically save state
1. Airbyte protocol documentation is updated as needed to indicate this

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368221318596) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
spec was created: https://docs.google.com/document/d/1Shwpsi8XKzuVRSkKkzYLu2dIP4NFtXia3jFf70vLjMY/edit

**Comment by harshithmullapudi** [comment]
@cgardens any update on this. If this is not picked by your team can I pick this up?

**Comment by cgardens** [comment]
@harshithmullapudi - hi! I'm still working on it. my hope is to have it working for at least postgres by the end of the week. as I've dug into it, I've found a host of other things that it has made sense to clean up along the way, which is why it's going closer than expected.

**Comment by cgardens** [comment]
Getting close to the end here. Focused on getting testing working. Testing is (of course) revealing some issues, so working through those.
