### ISSUE TITLE
dagger: enable `--trace`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#26295]
The Dagger team has enabled a new flag to capture more details on our pipeline execution:

https://github.com/dagger/dagger/pull/5143

> This PR will help debug the issue you are hitting requires enabling trace logs on the dagger-engine itself. I think this would be good for your dev cluster, but maybe not your prod one, at least initially. Reason being that trace results in so many logs that it most likely actually has a small but meaningful performance impact. The update to enable trace is very easy (just append --trace to the args or put trace=true in the config.toml), can give more details if needed.

**Comment by cpdeethree** [comment]
I pushed these changes to the configmap, and newly rolled daemonsets should pick them up for both dev and prod pipelines
