### ISSUE TITLE
Source Facebook Marketing: Airbyte Cloud Facebook Marketing Sync Worker fails with "Source didn't exit properly - check the logs!"

### ISSUE THREAD

**Issue by vincent-el** [airbytehq/airbyte#26290]
### Connector Name

source-facebook-marketing

### Connector Version

0.3.7

### What step the error happened?

During the sync

### Revelant information

[logs.txt](https://github.com/airbytehq/airbyte/files/11514001/logs.txt)

already tried resetting the stream, deleting the schema in the database manually and retrying several times

### Contribute

- [ ] Yes, I want to contribute

**Comment by Saicheg** [comment]
I can confirm that we are seeing similar issue as well! ✋

**Comment by bazarnov** [comment]
Hello, @vincent-el and @Saicheg, I'm currently looking at the provided `logs.txt` and the issue you've faced with should  be related to the recent platform core changes. Could you please confirm you still have the issue present? As far as I know it should be already fixed  (including the latest OSS master). Please double-check on your latests syncs as  well as make sure you  use the latest `master` (if OSS is used) and the latest `source-facebook-marketing` connector, which is `0.5.0`.
The one that mentioned earlier:  `0.3.7` is a little bit outdated and might cause unexpected issues.

**Comment by bazarnov** [comment]
I'm closing this for now, the new version of `source-facebook-marketing` is available currently: `1.0.0` which is the major update, please consider using it.
