### ISSUE TITLE
Page to select schema should have a refresh schema button.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2633]
## Tell us about the problem you're trying to solve
When selecting tables while setting up a sync, I have to either refresh the page or leave the page and come back to refresh the discovered schema. This is annoying if I'm on the page and the schema changes. My hunch is this affects people who are testing Airbyte more than production users, but is one of those small things that will help the product feel more polished.

## Describe the solution you’d like
The UI should have a 'update schema' button similar to the 'update schema' button we have on on the connection settings page.

**Comment by cgardens** [comment]
Let's call the new button "refresh schema". Otherwise, I think this is a nice idea. All the button needs to do is call discover again.
