### ISSUE TITLE
Source Zendesk Support: notification

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#26353]
### Topic

Zendesk cursors

### Revelant information

Hi,
We received a notification from Zendesk warning us that they are adding limits to the Offset based pagination to steer users to use the cursor-based pagination instead.
Here is the message:

"Hello,

Starting August 22, 2023, Zendesk is [introducing stricter limits](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59802&elqTrackId=87af7cd2303d487fa08f6151e2f52628&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) on API requests made using offset-based pagination (OBP). You are receiving this email because according to our API usage data, your account will be affected by these upcoming limits. To minimize potential disruption to your business, we want to share additional details.

**Why is Zendesk making this change?**
Zendesk currently offers both [offset-based pagination](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59801&elqTrackId=1b98444ff5e84f039b20e476ace5b3ed&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) (OBP) and [cursor-based pagination](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59799&elqTrackId=a7b0730875144e9a8463d96dbaf8e3be&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) (CBP) for most API endpoints. CBP offers many [advantages](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59800&elqTrackId=05aa85ba74f64d799a5dcb593af8a918&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) over OBP and will be the primary method of pagination offered at Zendesk in the near future. In an effort to provide a better, faster experience for our customers we are taking steps to encourage a transition to CBP.

**What does this mean for me?**
The first phase of this effort involves introducing stricter limits on high-offset OBP requests. After August 22, 2023, requests made beyond the first 10,000 records (100 pages) will result in an error message: “400 Bad Request.” In order to request data sets larger than 10,000 records, you will need to [transition to CBP](https://app.hello.zendesk.com/e/er?s=2136619493&lid=59799&elqTrackId=b8c06e1d0bb84aab8ffb96643506fdab&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1).

Please note that OBP requests for fewer than 10,000 records will not be affected, nor will requests made using the CBP model.

What do I need to do?
We strongly encourage you to make the switch to CBP as soon as possible to avoid being affected by these limits – both now and in the future. If you do not know which integrations or applications may be going over the limit, we suggest partnering with your team responsible for managing Zendesk integrations and apps to investigate and determine what this change means for you.

Should you have questions or need additional support, please [contact us](https://app.hello.zendesk.com/e/er?s=2136619493&lid=55652&elqTrackId=3c8dac44f0714b3783707370c389a630&elq=4b27e1779c1f487dba2fbfb639c36e76&elqaid=78755&elqat=1) and we’ll be happy to help.

Thanks for being a valued customer,

The Zendesk team"

Since we are only using Airbyte to access Zendesk data, we assume this is related to how it pulls data from its API.

There are still several months to the deadline, but I believe it is worth having this in mind to have enough time.

**Comment by clnoll** [comment]
Reopening because we had to revert this connector back to 0.10.0, which still uses offset pagination. See https://github.com/airbytehq/oncall/issues/2530.

**Comment by clnoll** [comment]
When we're ready to roll out a fix for this issue we should create a prerelease version of the connector and test it against one workspace to verify that the number of records synced matches the expected number. We can update the Joko connector version override in [LaunchDarkly](source-zendesk-support for OC https://github.com/airbytehq/oncall/issues/2530) (called "source-zendesk-support for OC https://github.com/airbytehq/oncall/issues/2530") to test the prerelease version before doing a full rollout.

**Comment by artem1205** [comment]
@clnoll , rule in launchdarkly added: version `source-zendesk-support:0.10.2-dev.b55468cc6e` set for JOKO workspace

**Comment by artem1205** [comment]
Update
test results on customer's connection: 
![image](https://github.com/airbytehq/airbyte/assets/36314070/8181d239-b92d-4a2e-bd4a-89bb2c967ce6)

**Comment by potatozerg** [comment]
@artem1205 Me and another user face the same issue
https://github.com/airbytehq/airbyte/issues/28764
My connectors messed up after upgrading to 0.10.1
