### ISSUE TITLE
Refresh the source schema and save the stream changes from the Airbyte API / Octavia

### ISSUE THREAD

**Issue by gpodevijn** [airbytehq/airbyte#26399]
### What area the feature impact?

Airbyte Platform

### Revelant Information

When a stream schema changes, one must refresh the source, visualise the changes and save them from the UI (even though Airbyte checks for schema changes once a day, it still requires manual actions to update the stream schemas). 

Ideally, we should be able to perform these steps from the Airbyte API and from Octavia. Moreover, the option to perform a "data reset" or not (after we save the changes), should also be an API option (in our case, for instance, resetting the data is not necessary because our destination supports schema evolution). 

Benefits: It would allow users to perform schema updates from the CICD, or from an orchestration tool. 

It is possible to achieve the above from the Configuration API, but as stated in the documentation, the Configuration API is not meant to be used by end-users to the possibility of the API to change in the future releases.

**Comment by nataliekwong** [comment]
Hey @gpodevijn ,

Would our automatic schema propagation feature work for what you're looking to do? It will automatically propagate all column changes to your destination. It is able to be set through the Airbyte API: https://reference.airbyte.com/reference/patchconnection

<img width="412" alt="Screenshot 2023-11-16 at 10 58 14 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/7beb64f2-4e94-4dd7-b088-dfc629c741da">

**Comment by GKTheOne** [comment]
Hi @nataliekwong. Unfortunately the feature only looks for schema changes every 24 hours, and in my testing does not work for incremental connections. (last tested with 0.50.33. I did find mention about this in the docs, but can't locate it any more)
I too would like to be able to have my connection fetch all fields at the time of the sync, which means refreshing/updating the catalog before every sync. I would prefer it to "Just Work™", but happy to write a scheduled script to poke an API to achieve the same result. If I must poke the API myself, I would prefer to use a stable API and not an internal one 😄
(I work with rapidly changing schemas, and will soon be looking to do multiple syncs per day)

Hi @gpodevijn. You mention that the Configuration API can be used to refresh schemas, can you please tell me which calls I should be looking at to refresh the schema for a connection? I'm looking into this now and wondering if you can save me some research time 🙏

**Comment by GKTheOne** [comment]
Hi again. I was able to perform a manual `propagate_columns` schema update via Airbyte API.

Using the Airbyte API,
1. [Get Connection details](https://reference.airbyte.com/reference/getconnection), using the `connectionId`
2. [Get stream properties](https://reference.airbyte.com/reference/liststreams), using the `sourceId` and `destinationId` from the connection details result. Set `ignoreCache` to `true`
3. [Update Connection details](https://reference.airbyte.com/reference/patchconnection), (using the same `connectionId` from 1), providing only the `.configurations` object from the connection details json result.

@gpodevijn, can you please verify?

I would like to be able to get a catalog diff (and schema change type) similar to the Configuration API `/v1/web_backend/connections/get` call (haven't looked at that one myself), but I should be able to log a diff by first using the _Get stream properties_ call with `ignoreCache` as `false` and comparing the result when `ignoreCache` is `true`.

I also imagine that this can be expanded to the `propagate_fully` case by programmatically changing the `.configurations` object sent in the _Update Connection details_ call. I would also expect that this _could_ be challenging in practice, (especially for incremental syncs if the stream properties does not include a default source defined cursor field).

**Comment by GKTheOne** [comment]
I should also note, that this updates the schema cache for a source-destination pair. So if you have multiple connections for a source-destination pair, ie different tables at different schedules, then getting a connection specific schema change diff would be complicated 😄

**Comment by dantonbertuol** [comment]
> Hi again. I was able to perform a manual `propagate_columns` schema update via Airbyte API.
> 
> Using the Airbyte API,
> 
> 1. [Get Connection details](https://reference.airbyte.com/reference/getconnection), using the `connectionId`
> 2. [Get stream properties](https://reference.airbyte.com/reference/liststreams), using the `sourceId` and `destinationId` from the connection details result. Set `ignoreCache` to `true`
> 3. [Update Connection details](https://reference.airbyte.com/reference/patchconnection), (using the same `connectionId` from 1), providing only the `.configurations` object from the connection details json result.
> 
> @gpodevijn, can you please verify?
> 
> I would like to be able to get a catalog diff (and schema change type) similar to the Configuration API `/v1/web_backend/connections/get` call (haven't looked at that one myself), but I should be able to log a diff by first using the _Get stream properties_ call with `ignoreCache` as `false` and comparing the result when `ignoreCache` is `true`.
> 
> I also imagine that this can be expanded to the `propagate_fully` case by programmatically changing the `.configurations` object sent in the _Update Connection details_ call. I would also expect that this _could_ be challenging in practice, (especially for incremental syncs if the stream properties does not include a default source defined cursor field).

Hi, this didn't work for me.
The connection cannot identify a new field added in postgres, even making a call to update connection.

Any other solution? :(

**Comment by dantonbertuol** [comment]
> > Hi again. I was able to perform a manual `propagate_columns` schema update via Airbyte API.
> > Using the Airbyte API,
> > 
> > 1. [Get Connection details](https://reference.airbyte.com/reference/getconnection), using the `connectionId`
> > 2. [Get stream properties](https://reference.airbyte.com/reference/liststreams), using the `sourceId` and `destinationId` from the connection details result. Set `ignoreCache` to `true`
> > 3. [Update Connection details](https://reference.airbyte.com/reference/patchconnection), (using the same `connectionId` from 1), providing only the `.configurations` object from the connection details json result.
> > 
> > @gpodevijn, can you please verify?
> > I would like to be able to get a catalog diff (and schema change type) similar to the Configuration API `/v1/web_backend/connections/get` call (haven't looked at that one myself), but I should be able to log a diff by first using the _Get stream properties_ call with `ignoreCache` as `false` and comparing the result when `ignoreCache` is `true`.
> > I also imagine that this can be expanded to the `propagate_fully` case by programmatically changing the `.configurations` object sent in the _Update Connection details_ call. I would also expect that this _could_ be challenging in practice, (especially for incremental syncs if the stream properties does not include a default source defined cursor field).
> 
> Hi, this didn't work for me. The connection cannot identify a new field added in postgres, even making a call to update connection.
> 
> Any other solution? :(

Hi, it was my mistake, the process is working! Thanks, this will save me.

**Comment by GKTheOne** [comment]
Thanks @dantonbertuol, for checking my process and giving me feedback about it 👍
Do you have any more specific feedback? ie, Is there anything that I didn't mention, (or was unclear)? Did you do anything different, or have ideas, that make things easier/worse/better?

**Comment by dantonbertuol** [comment]
> Thanks @dantonbertuol, for checking my process and giving me feedback about it 👍 Do you have any more specific feedback? ie, Is there anything that I didn't mention, (or was unclear)? Did you do anything different, or have ideas, that make things easier/worse/better?

Hello. The process I needed to do was exactly the same as what you went through.
I tried to patch the connection without passing the streams in the body but it didn't work.

I did some tests and they all worked:

* New field -> OK
    * Incremental -> OK
    * Full Refresh -> OK
    * CDC -> OK
* Field deletion -> OK
    * Incremental -> OK
    * Full Refresh -> OK
    * CDC -> OK
* Adding new table -> OK
* Table deletion -> OK
* CDC table inclusion -> OK
* Adding new schema -> OK

**Comment by stim371** [comment]
Step 2 for this is a broken link. I think the replacement would be https://reference.airbyte.com/reference/getstreamproperties

**Comment by kev-datams** [comment]
hello @marcosmarxm , why did you closed this issue ? do you consider the "3 steps" expressed above as a viable solution to "simply" force a refresh of a schema ? thank you

**Comment by kev-datams** [comment]
> Step 2 for this is a broken link. I think the replacement would be https://reference.airbyte.com/reference/getstreamproperties
> 
> Update: After switching my connection's "Detect and propagate schema changes" from "Manually approve" to "Propagate fields only", it appears that `GET /streams` and `POST /discover_schemas` both kick off a full schema refresh from the source, regardless of whether you pass `ignoreCache=true`.

hello @stim371 , where is the `discover_schemas` endpoint you mentioned ?
Is it now sufficient to force a refresh of fields and streams and we do not need the 3 steps from above ?
Thanks ! :)

**Comment by stim371** [comment]
@kev-datams https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/sources/discover_schema

it's in the old docs

**Comment by kev-datams** [comment]
> [@kev-datams](https://github.com/kev-datams) https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/sources/discover_schema
> 
> it's in the old docs

@stim371 thanks 🙏 
so you just use this endpoint to perform the update of stream schema, or the 3 steps from above ?
