### ISSUE TITLE
Source Amazon Ads: Advertised Product reports

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#26405]
### What area the feature impact?

Connectors

### Revelant Information

https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#/advertised-product-reports

**Comment by lazebnyi** [comment]
Implemented - https://github.com/airbytehq/airbyte/blob/a5eb24e2fcd61dbd2b1166fe2f84465cd6dfdec2/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/products_report.py#L154
