### ISSUE TITLE
Source Amazon Ads: new stream Campaign Rpeorts

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#26406]
### What area the feature impact?

Connectors

### Revelant Information

https://advertising.amazon.com/API/docs/en-us/reporting/v2/report-types#campaign-reports

**Comment by tolik0** [comment]
Already implemented in:
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/products_report.py#L281
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/sponsored_brands.py#L24
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/sponsored_display.py#L24
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/sponsored_products.py#L24
