### ISSUE TITLE
Source Amazon Ads: new stream purchased product report

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#26407]
### What area the feature impact?

Connectors

### Revelant Information

https://advertising.amazon.com/API/docs/en-us/reporting/v3/report-types#purchased-product-reports

**Comment by tolik0** [comment]
@ycherniaiev Can you please, create a new campaign for testing this issue, it can only be tested with the active campaign.

**Comment by ycherniaiev** [comment]
@tolik0 no way. because for this report we need our product purchased but it is possible for real pitems only
