### ISSUE TITLE
Source Amazon Ads: new stream Suggested keywords

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#26400]
### What area the feature impact?

None

### Revelant Information

https://advertising.amazon.com/API/docs/en-us/sponsored-products/keywords/suggestions

**Comment by midavadim** [comment]
@ycherniaiev 

We need to create a campaign with not "Auto Targeted" after that API will work for us

Now we get the following error:
    {
    "code": "400",
    "details": "Getting keyword recommendations for AD Group in Auto Targeted Campaign is not supported",
    "requestId": "32S2DM298NMCS5R7JRQQ"
}

    https://advertising.amazon.com/API/docs/en-us/sponsored-products/keywords/suggestions
    
    {{api_url}}/v2/sp/adGroups/183961953969922/suggested/keywords
