### ISSUE TITLE
Document how to write a destination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2641]
## Tell us about the documentation you'd like us to add or update
I would like to add a destination to Airbyte

## Are there any related areas of documentation that currently exist? Could you point to them? 
there are docs for writing sources, but not for destinations. I would like to know how to write a destination in Python or Java.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368098121015) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
can we close this one given? https://github.com/airbytehq/airbyte/pull/4384
