### ISSUE TITLE
Default sync mode should not be Full Refresh | Append

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26432]
Observation:
- During connection creation, the default sync mode is set to Incremental | Dedupe + History if a cursor field & primary key exist. If it does not, it selects Full Refresh | Overwrite.
- If a user does not select all the tables to sync, then the configuration will update the sync mode to be "Full Refresh | Append" as the sync mode for the disabled table
- If a user returns to the replication settings for that connection, they observe a mix of sync modes across "Incremental | Dedupe + History", "Full Refresh | Overwrite", and "Full Refresh | Append". (screenshot below)
- For each table they want to now stream, they need to also select a new sync mode that does not follow the same defaulting behavior we show in the connection creation flow

Suggestion:
- Never fallback to Full Refresh | Append for a sync mode
- Ideally, we should use the same default-setting logic as we do during connection creation. Any sync method with "Append" is an uncommon sync method and should not be chosen as a default.

Example: 
![Screenshot 2023-05-23 at 10 06 32 AM](https://github.com/airbytehq/airbyte/assets/38087517/60bd3f78-cd64-475d-8e79-956e26d4ab86)

**Comment by josephkmh** [comment]
Refining notes:
- It's not possible to persist a sync mode for a disabled stream (backend does not persist it) but we can use the same logic to determine the default sync mode for disabled streams

**Comment by alex-gron** [comment]
@mfsiega-airbyte is it possible to default to `Incremental` if it exists?

**Comment by nataliekwong** [comment]
Closed by https://github.com/airbytehq/airbyte-platform-internal/pull/8118
