### ISSUE TITLE
"No streams selected" warning missing

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26446]
There is a live experiment that disables all streams by default when setting up a new connection (controlled by FF https://app.launchdarkly.com/default/production/features/connection.syncCatalogConfig.disabledStreams/targeting)

Observations:
- A user selects any source and any destination when setting up a new connection
- A user doesn't enable any streams to sync
- The "Set up connection" button shows as purple (clickable)
- No error message is returned when a user tries to click the button

Suggestion:
- Show the error message "Select at least 1 stream to sync." under the table when no streams are selected
- Disable the "Set up connection" button until at least 1 stream is enabled.

I'm not sure if this is caused by the experiment implementation (which was done several months ago) and the issue will be resolved when this is merged: https://github.com/airbytehq/airbyte-platform-internal/pull/6525.

**Comment by nataliekwong** [comment]
@tealjulia I saw you were reviewing https://github.com/airbytehq/airbyte-platform-internal/pull/6525 so I'm tagging you here, but feel free to redirect. I'd like to make sure that we display the error message correctly about selecting at least 1 stream if we're going to be rolling this out to everyone. Would you be able to look into why it's not showing up?

**Comment by tealjulia** [comment]
@nataliekwong and/or @timroes  How can I try this feature out in a dev environment? I believe I know what is happening there.  

Also I want to be sure I understand the desired outcome:
- user loads page, all streams are disabled by default, there are no errors on the screen but the submit button is clickable
- user doesn't do anything and clicks the button
- frontend validation should fire and prompt them to select at least 1 stream

correct?  I imagine we don't want red errors showing on the page load.

**Comment by nataliekwong** [comment]
Hey @tealjulia sorry for the late reply - I quickly checked with @timroes before responding.

In this case the error message is subtle and visible only towards the bottom of the page, so I'd prefer to show the error message and grey out the button so that users don't waste a click on this page before seeing the error.

@timroes feel free to chime in if I missed anything.

**Comment by josephkmh** [comment]
Refining notes:
- We should avoid showing an error message if the user has not taken any action
- In any case the form should show an error message when there are invalid fields (e.g. no selected streams)
- @Upmitt will mock up this flow to think about the UX a bit more

**Comment by Upmitt** [comment]
@josephkmh @nataliekwong @tealjulia My suggestion would be to change the wording "Select at least 1 stream to sync." > "Activate at least 1 stream to sync." - because we don't provide a way to "select" streams and it is more consistent with the bloc title.

For the message error, what do you think about using the toast messages. In the loom video, you can see one with the cross to close it, and the second one disapearing after a delay. I would use the second one, disappearing after a delay

https://www.loom.com/share/833865f68c6d49d89a3cecc55b5653a0

**Comment by tealjulia** [comment]
Resolved by @ambirdsall in https://github.com/airbytehq/airbyte-platform-internal/pull/7785
