### ISSUE TITLE
Debezium - set an upper bound on the size of the queue containing records to be processed

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#26454]
### Topic

Set an upper bound on the size of the Debezium queue containing records to be processed.

### Revelant information

We have seen instances when a CDC incremental sync terminates because of an OOM error. 
Job sync [link](https://cloud.airbyte.com/workspaces/51861bf9-5e9f-49bc-bee3-0328250e1c29/connections/743f9991-e29d-4cb5-81b0-1a895892bfbc/job-history#2293285::0)

```
2023-05-22 18:20:18 [44msource[0m > Terminating due to java.lang.OutOfMemoryError: Java heap space
2023-05-22 18:20:18 [46mreplication-orchestrator[0m > Source has no more messages, closing connection.
2023-05-22 18:20:19 [46mreplication-orchestrator[0m > (pod: jobs / source-postgres-strict-encrypt-read-2293285-0-touue) - Closed all resources for pod
```

Debezium allows controlling the maximum volume of the queue size in bytes, we are not setting this in code currently thereby allowing the queue to grow unbounded. 

Set this Debezium property in **source-postgres**: [max.queue.size.in.bytes](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-max-queue-size-in-bytes)

We need to set this value and calculate it dynamically so that it changes with the allocated heap memory. I think we can set a value of 60% of the total heap size in bytes that a connector has.

**Comment by postamar** [comment]
This has been done, this property has been set to 256MB.
