### ISSUE TITLE
Source Bing Ads: new stream Responsive Search Ad

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26470]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Responsive Search Ad](https://learn.microsoft.com/en-us/advertising/bulk-service/responsive-search-ad?view=bingads-13&viewFallbackFrom=bingads-12#description).  [new link](https://learn.microsoft.com/en-us/advertising/bulk-service/responsive-search-ad?view=bingads-13)
Defines a responsive search ad format for text ads in the Search network that can be downloaded and uploaded in a bulk file.
If you are using the [Bing Ads SDKs](https://learn.microsoft.com/en-us/advertising/guides/client-libraries?view=bingads-13) for .NET, Java, or Python, you can save time using the [BulkServiceManager](https://learn.microsoft.com/en-us/advertising/guides/sdk-bulk-service-manager?view=bingads-13) to upload and download the BulkResponsiveSearchAd object, instead of calling the service operations directly and writing custom code to parse each field in the bulk file.

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by darynaishchenko** [comment]
this type of ad present in Ads [stream](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/streams.py#L304), closing for now
