### ISSUE TITLE
Source Stripe: new stream Files

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26479]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Files](https://stripe.com/docs/api/files)
This is an object representing a file hosted on Stripe's servers. The file may have been uploaded by yourself using the [create file](https://stripe.com/docs/api/files#create_file) request (for example, when uploading dispute evidence) or it may have been created by Stripe (for example, the results of a [Sigma scheduled query](https://stripe.com/docs/api/files#scheduled_queries)).
[The file object](https://stripe.com/docs/api/files/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by artem1205** [comment]
working on it
