### ISSUE TITLE
ctid sync: Define state for user cursor

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26488]
Define a state model for all potential sync modes: standard user cursor sync, xmin, CDC).
State will support:
1. Syncing normally as we do today without ctid - saving user cursor checkpoint.
2. Saving ctid checkpoint to allow subsequent attempt restorability.
3. Identifying when a cancel and start over of sync is needed (e.g full vacuum).
4. Ensure single and multiple streams are supported.
5. Able to switchover when ctid read is done to the respective sync mode state.

**Comment by prateekmukhedkar** [comment]
Deliverable: update the existing yaml file that we use for state.

**Comment by rodireich** [comment]
Suggestion for state change: https://docs.google.com/document/d/1PtoZBXMHhyGsDiuAWilfJK_1EE2G079FIwTHFEiJO1s/edit?usp=sharing
