### ISSUE TITLE
Source Stripe: new stream Shipping Rates

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26481]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Shipping Rates](https://stripe.com/docs/api/shipping_rates)
Shipping rates describe the price of shipping presented to your customers and can be applied to [Checkout Sessions](https://stripe.com/docs/payments/checkout/shipping) and [Orders](https://stripe.com/docs/orders/shipping) to collect shipping costs.
[The shipping rate object](https://stripe.com/docs/api/shipping_rates/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by btkcodedev** [comment]
I would like to work on this @igrankova 
Update: seeded the stream
