### ISSUE TITLE
Source Stripe: new stream Transactions

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26483]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Transactions](https://stripe.com/docs/api/issuing/transactions)
Any use of an [issued card](https://stripe.com/docs/issuing) that results in funds entering or leaving your Stripe account, such as a completed purchase or refund, is represented by an Issuing `Transaction` object.
[The Transaction object](https://stripe.com/docs/api/issuing/transactions/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by btkcodedev** [comment]
@igrankova 
Is it open for community? 
Can I get it assigned for me?

**Comment by btkcodedev** [comment]
Update: The test creds doesn't allow using the issuing URL
Returns error:
`{
  "error": {
    "message": "Your account is not set up to use Issuing. Please visit https://dashboard.stripe.com/issuing/overview to get started.",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_**********?t=1686329879",
    "type": "invalid_request_error"
  }
}`

But I could still add it as empty stream

**Comment by igrankova** [comment]
@btkcodedev 
I tried to setup Issuing, I can't apply to the Apple Pay only. Not sure will it help you or not.
![image](https://github.com/airbytehq/airbyte/assets/87977540/61a0525b-b9e5-4303-8342-b67419c3848f)

**Comment by btkcodedev** [comment]
Okayu Thanks for the help @igrankova 🚀

**Comment by btkcodedev** [comment]
Unassigning this, maintainers could reopen this to community😄
