### ISSUE TITLE
Source Stripe: new stream SetupAttempts

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26480]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[SetupAttempts](https://stripe.com/docs/api/setup_attempts)
A SetupAttempt describes one attempted confirmation of a SetupIntent, whether that confirmation was successful or unsuccessful. You can use SetupAttempts to inspect details of a specific attempt at setting up a payment method using a SetupIntent.
[The SetupAttempt object](https://stripe.com/docs/api/setup_attempts/object)

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by artem1205** [comment]
working on ot
