### ISSUE TITLE
ctid sync: Define state for CDC

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26492]
Define a state model for CDC sync.
State will support:
1. Syncing normally as we do today without ctid - saving Debezium state as before.
2. Saving ctid checkpoint to allow subsequent attempt restorability - this will allow us to know whether we should continue with ctid or switch to WAL log sync.
3. Identifying when a cancel and start over of sync is needed (e.g full vacuum).
4. Ensure single and multiple streams are supported - CDC is always a global state (single LSN value per db).

**Comment by prateekmukhedkar** [comment]
Sequentially happens after #26488

**Comment by rodireich** [comment]
Existing state for CDC (pre-ctid)
```
{
  "shared_state": {
    "state": {
      "[\"postgres\",{\"server\":\"postgres\"}]": "{\"transaction_id\":null,\"lsn\":5440977592,\"txId\":2797886,\"ts_usec\":1684875175198480}"
    }
  },
  "streamStates": [
    {
      "streamDescriptor": {
        "name": "id_and_name",
        "namespace": "public"
      },
      "streamState": {
        "stream_name": "id_and_name",
        "cursor_field": [],
        "stream_namespace": "public"
      }
    }
  ]
}
```
@subodh1810 If a new stream is added to sync, how is that reflected in state?
Assume new table "users" now added to a CDC sync. On the first sync attempt the state above doesn't include a "users" stream.
I'm trying to understand how the case is identified since it will trigger a snapshot read of the new stream only before reading from WAL can resume, correct?

**Comment by subodh1810** [comment]
@rodireich at the beginning of the sync we compare the catalog and state. Any stream that's present in the catalog and not present in state is a new stream and a snapshot is triggered for the stream. [Here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L467) is the logic for it. Once the snapshot is completed, we add the new streams into state and emit a state message.

**Comment by rodireich** [comment]
State defined in https://docs.google.com/document/d/1PtoZBXMHhyGsDiuAWilfJK_1EE2G079FIwTHFEiJO1s/edit?usp=sharing
