### ISSUE TITLE
Improve HubSpot source connection errors

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26515]
These errors are emitted during connection sync attempts.

The full list of error responses are here: https://legacydocs.hubspot.com/docs/faq/api-error-responses

The suggestions would be emitted in the external message of the log. 

Type of error: bad URL endpoint
> 400 Client Error: Bad Request for url: https://api.hubapi.com/properties/v2/ttp_payments/properties\nSource didn't exit properly - check the logs!
> 401 Client Error: Unauthorized for url: https://api.hubapi.com/contacts/v1/lists/all/contacts/all?limit=100&vidOffset=17549902&showListMemberships=True
> 403 Client Error: Forbidden for url: https://api.hubapi.com/marketing/v3/forms...

Suggestion: The authenticated user does not have permissions to access the URL {{example endpoint}}. Verify your permissions to access this endpoint. 

Type of error: Oauth token expired
> The OAuth token used to make this call expired 0 second(s) ago.
> This oauth-token is expired! expiresAt: 1684892453714, now: 1684892453813\nSomething went wrong within the source connector
> Exception('Error while refreshing access token: 400 Client Error: Bad Request for url: https://api.hubapi.com/oauth/v1/token')
OAuth Credentials' was expected\nio.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!

Suggestion: The authentication to HubSpot has expired. Re-authenticate to restore access to HubSpot.

Type of error: stream removed from source
>io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!\n\The requested stream feedback_submissions was not found in the source. Available streams: dict_keys(['campaigns', 'companies', 'contact_lists', 'contacts', 'contacts_list_memberships', 'deal_pipelines', 'deals', 'email_events', 'engagements', 'engagements_calls', 'engagements_emails', 'engagements_meetings', 'engagements_notes', 'engagements_tasks', 'forms', 'form_submissions', 'line_items', 'marketing_emails', 'owners', 'products', 'property_history', 'subscription_changes', 'tickets', 'ticket_pipelines', 'workflows'])\"\njava.lang.RuntimeException: java.io.UncheckedIOException: java.net.SocketException: Socket closed"

Suggestion: The stream {stream_name} is no longer available in the source. Remove this stream from syncing or verify your permissions to this stream. 

Type of error: Rate limited
> HubspotRateLimited('429 Rate Limit Exceeded: API rate-limit has been reached until None seconds. See https://developers.hubspot.com/docs/api/usage-details')

Suggestion: You have reached your Hubspot API limit per Hubspot's [API usage guidelines](https://developers.hubspot.com/apps/api_guidelines). We will resume replication once the limit has elapsed.

**Comment by arsenlosenko** [comment]
as I am currently working on certification for Source Hubspot, I'll start working on this issue, as it corresponds with one of the stages of certification. @nataliekwong thanks for detailed description of known errors, I'll use that as a starting point 👍
