### ISSUE TITLE
Improve Salesforce source connection errors

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26520]
These are suggestions on improvements to the external message emitted in the connection logs when the error is due to the Salesforce source.

Type of error: Insufficient permissions
> We can't complete the action because enabled transaction security policies took too long to complete. 

Suggestion: A transient authentication error occurred. To prevent future syncs from failing, assign the "Exempt from Transaction Security" user permission to the authenticated user. 

Relevant issue: https://github.com/airbytehq/oncall/issues/1758

Type of error: Rate limit
> Max bulk v2 query jobs (10000) per 24 hrs has been reached (10021).
> API Call limit is exceeded

Suggestion: Your API key for Salesforce has reached its limit for the 24-hour period. We will resume replication once the limit has elapsed.

Relevant issue: https://github.com/airbytehq/oncall/issues/1735

Type of error: user permissions
> Implementation restriction: EntitySubscription only allows security evaluation for non-admin users when LIMIT is specified and at most 1000

Suggestion: Unable to sync EntitySubscription. To prevent future syncs from failing, ensure the authenticated user has "View all Data" permissions.

Relevant issue: https://github.com/airbytehq/oncall/issues/1628#issuecomment-1462811351

**Comment by artem1205** [comment]
@nataliekwong , I would kindly ask you to provide me more context about these error in order to handle them properly. It will be useful if you could share logs (or connection links you've found them)
