### ISSUE TITLE
Source Airtable: fix the data types in formula, rollup, lookup fields

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26528]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
For our Airtable Source, Integration Data Type: `Formula`, `Rollup` and `Lookup` is displayed as an `array<any>` type.  
By the [Airtable API](https://airtable.com/developers/web/api/field-model#formula) can return a type of the result.

## Describe the solution you’d like
Change the type to number or string depending on the result type for the  `Formula`, `Rollup` and `Lookup` fields.

**Comment by kev-datams** [comment]
I confirm this would be very useful :)
