### ISSUE TITLE
Destination S3: Fix docker build

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#26521]
https://github.com/airbytehq/airbyte/pull/26489 adds the ability for airbyte-ci to run additional scripts in the docker build. This is important for destination-s3, which needs to install the lzo compression library. Its script currently does not work (see https://github.com/airbytehq/airbyte/pull/26489/files#r1204221382). We should fix it so that destination-s3 can be published.

[Timebox this research to 1 day]

**Comment by evantahler** [comment]
Grooming:

You know you are done when `airbyte-ci build` works for `destination-s3`
