### ISSUE TITLE
Source Shopify: new stream Collection

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26539]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Collection](https://shopify.dev/docs/api/admin-rest/2023-04/resources/collection)
A collection is a grouping of products that merchants can create to make their stores easier to browse. For example, a merchant might create a collection for a specific type of product that they sell, such as Footwear. Merchants can create collections by selecting products individually or by defining rules that automatically determine whether products are included.
## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by lazebnyi** [comment]
Added in - https://github.com/airbytehq/airbyte/pull/17962/files
