### ISSUE TITLE
Source Shopify: new stream Checkout

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26538]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Checkout](https://shopify.dev/docs/api/admin-rest/2023-04/resources/checkout)
If you're building an app with the [Sales Channel SDK](https://shopify.dev/docs/apps/channels), then you can use the Checkout API to let customers purchase products from Shopify stores that have installed your sales channel.

Shopify uses the Checkout resource to manage a user's cart as it transitions to a paid order. This process includes specifying which line items are included in the checkout, attaching a customer's shipping and payment details, and calculating tax and shipping rates. Credit card payments can be attached to a Checkout using the [Payment](https://shopify.dev/docs/api/admin-rest/current/resources/payment) resource.
## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by igrankova** [comment]
UPD:
We need to create a separate Sales Channel App and list it on a Marketplace to be unblocked:
![image](https://github.com/airbytehq/airbyte/assets/87977540/dbfa7d44-4deb-4992-9612-5b1bb63d6777)
![image](https://github.com/airbytehq/airbyte/assets/87977540/9630ba62-322a-44b6-8ed5-03f6a099d847)

**Comment by bazarnov** [comment]
It was decided to proceed with certification without this stream being implemented. Closing this for now.
cc @bmcgilli @oustynova @lazebnyi @sherifnada
