### ISSUE TITLE
Source Shopify: new stream Gift Card

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26557]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Gift Card](https://shopify.dev/docs/api/admin-rest/2023-04/resources/gift-card)
A gift card is an alternative payment method. Each gift card has a unique code that is entered during checkout. Its balance can be redeemed over multiple checkouts. Optionally, a gift card can assigned to a specific customer. Gift card codes cannot be retrieved after they're created—only the last four characters can be retrieved.
Shopify Plus

The Gift Card resource is available for [private apps](https://shopify.dev/concepts/apps#private-apps) installed on [Shopify Plus](https://help.shopify.com/en/manual/intro-to-shopify/pricing-plans/shopify-plus) stores. As of API version 2021-04, the Gift Card resource is also available for [custom apps](https://shopify.dev/concepts/apps#custom-apps) installed on Shopify Plus stores.

Your app must request the write_gift_cards and read_gift_cards [access scopes](https://shopify.dev/docs/admin-api/access-scopes). Merchants that want to sell or issue gift cards also need to [activate the gift card feature](https://help.shopify.com/en/manual/products/gift-card-products/add-update-gift-card-products#activate-the-gift-card-feature) in the Shopify admin.
## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by bazarnov** [comment]
It was decided to proceed with certification without this stream being implemented. Closing this for now.
cc @bmcgilli @oustynova @lazebnyi @sherifnada

**Comment by nickjoanis** [comment]
I came across this issue while searching for any open discussions on implementing the stream. I have developed a working example for the gift card stream in my fork, with straightforward modifications based on the existing ShopifyIncrementalStream class.

Should there be any interest in revisiting and reopening this issue, I am prepared to contribute my implementation as my first official contribution to the project. I would appreciate your feedback on whether you see value in this addition. Thank you

**Comment by bazarnov** [comment]
@nickjoanis Hello and thank you for your interest in enhancing the `Source Shopify`. This stream is quite useful to have. We are interested in your contribution for sure. We now working on delivering the BULK Api version of the connector, as of here: https://github.com/airbytehq/airbyte/pull/32345, all the improvements for this source are frozen until it's merged.

Feel free to make the PR and put me to the reviewers.
