### ISSUE TITLE
Source Shopify: new stream TenderTransaction

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26561]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[TenderTransaction](https://shopify.dev/docs/api/admin-rest/2023-04/resources/tendertransaction)
Each tender transaction represents money passing between the merchant and a customer. A tender transaction with a positive amount represents a transaction where the customer paid money to the merchant. A negative amount represents a transaction where the merchant refunded money back to the customer. Tender transactions represent transactions that modify the shop's balance.
## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by lazebnyi** [comment]
Added in - https://github.com/airbytehq/airbyte/pull/10449
