### ISSUE TITLE
Source Shopify: new stream User

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26562]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[User](https://shopify.dev/docs/api/admin-rest/2023-04/resources/user)
The User resource lets you retrieve information about staff on a Shopify shop, including [staff permissions](https://help.shopify.com/manual/your-account/staff-accounts/staff-permissions).

Shopify Plus
The User resource is available for [private apps](https://shopify.dev/concepts/apps#private-apps) and [custom apps](https://shopify.dev/concepts/apps#custom-apps) installed on [Shopify Plus](https://help.shopify.com/en/manual/intro-to-shopify/pricing-plans/shopify-plus) stores. You need to contact Shopify Plus Support to request the read_users [access scope](https://shopify.dev/api/usage/access-scopes) for your app.
## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by igrankova** [comment]
See more information about Blocked status in **Source Shopify: upgrade sandbox account to Shopify Plus subscription** #26912

**Comment by bazarnov** [comment]
It was decided to proceed with certification without this stream being implemented. Closing this for now.
cc @bmcgilli @oustynova @lazebnyi @sherifnada
