### ISSUE TITLE
Change options in the "Discard changes" modal

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26584]
Observation: Users don't understand they need to apply changes to schema refreshes.

Branched off of: https://github.com/airbytehq/airbyte/issues/26348 as an interim solution until we can more significantly improve this feature. 

Currently there are two options: `Cancel` (secondary button) and `Discard changes` (red danger button)
![image.png](https://images.zenhubusercontent.com/633f049bfac5d1a38c1061cc/800a2bb0-d902-4ca1-9646-d77107ec48d3)

Proposal is to change the options to `Discard changes` (red **secondary** button)  and `Close and continue editing` (blue primary button)

cc @timroes

**Comment by josephkmh** [comment]
@Upmitt will update figma to give us the new `danger-secondary` button variant

**Comment by nataliekwong** [comment]
To summarize from the doc, revisions proposed:

Header: Unsaved changes will be lost
Subtitle: Your changes will be lost if you navigate away from this page. Are you sure you want to leave?

Two buttons: 
Cancel (no background)
Leave page (red background)
