### ISSUE TITLE
Typo 'Dedupted'

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2658]
## Expected Behavior
Should read `Incremental - Deduped`
![2021-03-29_14-35-57](https://user-images.githubusercontent.com/1154337/112914298-81b99880-90b0-11eb-9e29-91f454a78239.png)

## Severity of the bug for you
Low

## Airbyte Version
0.18.0

**Comment by cgardens** [comment]
closed by @ChristopheDuong 's fix.

**Comment by ChristopheDuong** [comment]
> closed by @ChristopheDuong 's fix.

I only fixed it in the docs, the UI is still having the typo
