### ISSUE TITLE
Source Google Search Console: new stream Keyword Site Report by site

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26590]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Keyword Site Report by site](https://support.google.com/webmasters/answer/7576553?visit_id=638206297718857492-4041485698&rd=1)
KEYWORD_SITE_REPORT_BY_SITE: Search traffic data of the site based on the query strings user searched for on Google. Each record shows how the site appeared in the search result for a particular search query. The metrics are aggregated by Property. Dimensions include:
- Date
- Country
- Device
- Keyword
- Query
- Search Type (web/image/video/news)

_Keyword 
Applies to the key terms used in the written content of the  website pages. These terms are the most significant keywords and their  variants that Google found when crawling your site. When reviewed along  with the Search queries report and your site's listing in actual search  results for your targeted keywords, it provides insight into how Google  is interpreting the content of your site._

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by darynaishchenko** [comment]
closing this issue, because aggregation by Property is not available with SearchAppearance(keyword) dimension.
