### ISSUE TITLE
Service icons are missing

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#266]
For the moment, we're displaying only the default icons for the service. 

<img width="857" alt="Screen Shot 2020-09-15 at 9 32 12 AM" src="https://user-images.githubusercontent.com/68561602/93147597-6ce16d00-f73d-11ea-95c1-d855edda5957.png">

Do we need to have a library of such icons in SVG for all services supported? @cgardens @jamakase

**Comment by cgardens** [comment]
yeah. we need to collect the icons and add them to the project.

**Comment by cgardens** [comment]
Action Items:
* Add the logos to the API interface for integrations.
* Copy them from the unblock product and store them on the backend.
* After these 2, FE can consume them.
