### ISSUE TITLE
Source Amazon Seller Partner: Improve OAuth on Cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#26629]
### Connector Name

source-amazon-seller-partner

### Connector Version

latest

### What step the error happened?

Configuring a new connector

### Revelant information

As described in https://github.com/airbytehq/oncall/issues/2017 the OAuth flow for this connector is lacking. The user should be able to just click a single OAuth button to authenticate, without having to input a bunch of extra params, like any other OAuth connector cloud. 

In addition, [the docs](https://docs.airbyte.com/integrations/sources/amazon-seller-partner/) for this connector should be adjusted to make it very clear that setting up a dev app is only needed if you are using OSS and not Airbyte cloud. 

Once this issue is completed we should re-enable Amazon Seller Partner on Cloud. 

### Contribute

- [ ] Yes, I want to contribute

**Comment by LuliRib** [comment]
Hi, when I clicke d"Authenticate account", it takes me to the developer and doesn´t responds afterwards..
