### ISSUE TITLE
New Source: Zuora

### ISSUE THREAD

**Issue by brunoffaustino** [airbytehq/airbyte#2664]
## Tell us about the problem you're trying to solve
In our use case, a possible change to Airbyte would require support to read from Zuora.

## Describe the solution you’d like
Be able to do full and incremental syncs from Zuora.

## Describe the alternative you’ve considered or used
We currently use Fivetran.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368220974268) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@brunoffaustino thanks for the request. Can you share which endpoints on the [Zuora API](https://www.zuora.com/developer/api-reference/) you would like to sync?

**Comment by brunoffaustino** [comment]
Hi @sherifnada 
The ones supported by Fivetran: https://fivetran.com/docs/applications/zuora

**Comment by yevhenii-ldv** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**

No

**Available authentication modes (API key/Oauth/other)**

[API Credentials](https://www.zuora.com/developer/api-reference/#section/Authentication)

**Creating an account**

@sherifnada 
Zuora supports the [Trial period](https://www.zuora.com/trial-agreement/), which lasts 14 days, and after it need to switch to the paid version. 
I could not find a pricing for Zuora anywhere, but I found information on the forums that indicate that after registering the Trial period, user can see these pricing in his personal account.

Zuora also supports [Sandboxes](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/D_Zuora_Environments), but as far as I understand, you need to have a production account to use them.

**How to populate the account with data?**

Using the API and UI

**Available streams for sync**

* ACCOUNTING CODES
* ACCOUNTING PERIODS
* CATALOG
* CHARGE METRICS
* Credit memos
* Credit memo items
* Credit memo parts
    * Credit memo part items
* Data Query Jobs
* Debit memos
* Debit memo application parts
* Debit memo items
* Entities
* Entity connections
* Event triggers
* HOSTED PAGES
* Invoices
* Notification definitions
* Email Templates
* Callout notification histories
* Email notification histories
* Orders
* Payment Gateaway
* Payments
* Payment parts
  * Payment part items
* Refunds
* Refund parts
  * Refund part items
* Sequence sets
* Settings


**Integration supports incremental sync?**

some

**Other information/blockers**

Can be used [Singer Tap](https://github.com/singer-io/tap-zuora)

**Comment by sherifnada** [comment]
Before beginning implementation, we should create a production account with Zuora. Please reach out to me to discuss any pricing questions

**Comment by bazarnov** [comment]
The list of streams that could be implemented: https://fivetran.com/docs/applications/zuora/changelog
