### ISSUE TITLE
Destination Databricks: connector should support schema evolution (schemaMerge)

### ISSUE THREAD

**Issue by gpodevijn** [airbytehq/airbyte#26658]
### What area the feature impact?

Connectors

### Revelant Information

Databricks and its delta tables support schema evolution via the `COPY INTO` command parameter's `mergeSchema=true`. The connector should provide a parameter to enable or disable schema evolution.

In https://github.com/airbytehq/airbyte/pull/26942, we added an option in the connector configuration interface to enable or disable schema evolution:
<img width="691" alt="image" src="https://github.com/airbytehq/airbyte/assets/16660/3995bd84-f82f-43fd-b305-a43b2ec5c166">

This option, once enabled, sets the following parameter to the [COPY INTO](https://docs.databricks.com/sql/language-manual/delta-copy-into.html#parameters) statement used to load the data into the destination table (set to `false` by default): `COPY_OPTIONS ('mergeSchema' = 'true')`

We conducted some tests locally and it works great so far. We planned on running it in production in the coming weeks.

**Comment by evantahler** [comment]
Nice!  How's the work going internally?

**Comment by gpodevijn** [comment]
Thanks @evantahler ! 
The team reviewed the PR before we opened it here. We made several tests locally but it's not yet running in production (because we don't run Airbyte in production yet), but it's planned for the up coming weeks.
