### ISSUE TITLE
Source Monday: new stream Boards

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26665]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Boards](https://developer.monday.com/api-reference/docs/boards)
monday.com [boards](https://support.monday.com/hc/en-us/articles/115005317249-The-Basics-of-a-Board) are where users input all of their data, making them one of the core platform components. [Items](https://support.monday.com/hc/en-us/articles/115005319105-The-basics-of-items) (rows), [groups](https://support.monday.com/hc/en-us/articles/360011472320-The-basics-of-groups) (groups of rows), and [columns](https://support.monday.com/hc/en-us/articles/115005466609-The-basics-of-columns) comprise the board's structure, and the board's data is stored in items and their respective [updates](https://support.monday.com/hc/en-us/articles/115005900249-The-Updates-Section) sections. We support three types of boards that come with different sets of permissions: main, shareable, and private.

As a developer working with monday.com, it is important to familiarize yourself with the boards API so you know how to access board data. This document will walk you through the available queries and mutations to read and modify the boards object via the API.
Required scope: `boards:read`

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by bazarnov** [comment]
The `Boards` stream is already a part of the connector. See this code part: 
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-monday/source_monday/manifest.yaml#L73-L78
