### ISSUE TITLE
Source Salesforce Commerce Cloud: vetting for a new connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26708]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Analyze connector documentation and answer the questions:
- Webhook-based?   (no/partially/yes)
- Available   authentication modes (API key/OAuth/other)
- Has Sandbox environment?
- How to populate the account with data?
- Available streams for sync (Streams with filters are preferable)
- Integration supports incremental sync? (If there're streams with date parameters - the incremental sync could be)
- Other information/blockers (Rate Limits: Yes/No, etc.)

## Describe the solution you’d like
Add the results check-list to the comments section

**Comment by ycherniaiev** [comment]
**Webhook-based? (no/partially/yes)**
Partially
**Available authentication modes (API key/OAuth/other)**
JWT Access Token
**Has Sandbox environment?**
Yes (on demand or part of Partner Program)
**How to populate the account with data?**
UI
**Available streams for sync (Streams with filters are preferable)**
assignmentsSearch
POST
https://{shortCode}.api.commercecloud.salesforce.com/pricing/assignments/v1/organizations/{organizationId}/assignments
campaignsSearch
POST
https://{shortCode}.api.commercecloud.salesforce.com/pricing/campaigns/v1/organizations/{organizationId}/campaigns
**Integration supports incremental sync? (If there're streams with date parameters - the incremental sync could be)**
**Other information/blockers (Rate Limits: Yes/No, etc.)**
