### ISSUE TITLE
Define state for xmin

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26724]
Define a state model for xmin based cursor sync (no CDC)
State will support:
1. Syncing normally without ctid - saving xmin checkpoint.
2. Saving ctid checkpoint to allow subsequent attempt restorability.
3. Identifying when a cancel and start over of sync is needed (e.g full vacuum).
4. Ensure single and multiple streams are supported.
5. need to also support global state?

**Comment by rodireich** [comment]
Existing suggestion for xmin state (pre-ctid)
```
[
  {
    "streamDescriptor": {
      "name": "users",
      "namespace": "200m_users"
    },
    "streamState": {
      "num_wraparound": 0,
      "xmin_raw_value": 1349200,
      "xmin_xid_value": 1349200
    }
  }
]
```
@akashkulk can you please help me understand:
1. If it makes sense, Which of the two values is the equivalent to cursor value? 
2. What value(s) we would need to save when ctid sync start to allow switchover to xmin upon completion?

**Comment by rodireich** [comment]
State defined in https://docs.google.com/document/d/1PtoZBXMHhyGsDiuAWilfJK_1EE2G079FIwTHFEiJO1s/edit?usp=sharing

**Comment by rodireich** [comment]
Goal of this work is to define a state model and classes to support the states needed to perform an xmin incremental sync with initial sync using ctid.
State defined in [XMIN state with ctid](https://docs.google.com/document/d/1PtoZBXMHhyGsDiuAWilfJK_1EE2G079FIwTHFEiJO1s/edit#bookmark=id.78mcgpn0octf)
Description of how values in xmin state are calculated and db query used to acquire: [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java#L51).

**Comment by subodh1810** [comment]
Will be closed by this PR https://github.com/airbytehq/airbyte/pull/27302
