### ISSUE TITLE
Query current txid for xmin

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26726]
Upon the beginning of a first ctid read attempt (starting with null state),
If sync is xmin, we will read and save the current transaction id (txid) state of the database.
When ctid read is completed successfully, the value will allow switching over to reading incrementally using xmin.
If the first ctid attempt failed, subsequent ctid attempts will keep the saved txid value taken on the 1st attempt.

**Comment by subodh1810** [comment]
I think we already have this query in place. See the method `getXminStatus` in `PostgresQueryUtils` class [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresQueryUtils.java#LL83C28-L83C41) 

cc @akashkulk

**Comment by subodh1810** [comment]
Confirmed with Akash that its already there so closing this
