### ISSUE TITLE
Query current LSN

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26725]
Upon the beginning of a first ctid read attempt (starting with null state), 
If sync is CDC, we will read and save the current LSN state of the database.
When ctid read is completed successfully, the value will allow switching over to reading incrementally using WAL.
If the first ctid attempt failed, subsequent ctid attempts will keep the saved LSN value taken on the 1st attempt.

**Comment by subodh1810** [comment]
Already exists
