### ISSUE TITLE
Keep saving the initial max cursor or LSN value to state.

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#26731]
On a second, third, forth ctid read attempt there is no need to update the max cursor value taken on 1st attempt:
Make sure the saved max cursor value (xmin, LSN or user cursor) is not changing from its saved value taken on 1st attempt.
There is no need to query for the value either.

**Comment by subodh1810** [comment]
This is already merged for xmin. 
For CDC this is taken care by PR https://github.com/airbytehq/airbyte/pull/27652/files
