### ISSUE TITLE
Source Zendesk Support: New limits for offset-based pagination

### ISSUE THREAD

**Issue by gustavohwulee** [airbytehq/airbyte#26748]
### Connector Name

source-zendesk-support

### Connector Version

0.3.0

### What step the error happened?

None

### Revelant information

The new limit that will be implemented on August 15, 2023 will break exiting OBP streams with over 10,000 records.

```
What is changing?

Beginning on August 15, 2023, OBP requests over the first 10,000 records (100 pages) 
will result in an error message: “400 Bad Request.” In order to request data sets larger than 10,000 records,
customers will need to transition to CBP.

OBP requests for fewer than 10,000 records will not be affected, nor will requests made using the CBP model.
```
https://support.zendesk.com/hc/en-us/articles/5591904358938-New-limits-for-offset-based-pagination

I'm not 100% sure which streams on zendesk connectors will be impacted because it looks like time-based extraction won't be limited by this change:

```
Time based Incremental Export is a special case and not considered either OBP or CBP. 
The new page 100 limit is not applicable to it.

You can export tickets using cursor-based exports or time-based exports. 
However, Zendesk strongly recommends using cursor-based exports for better performance.
```

### Contribute

- [X] Yes, I want to contribute

**Comment by btkcodedev** [comment]
I would like to work on this

**Comment by jrolom** [comment]
@igrankova: @btkcodedev  will pick this one and related issues #26055  and #16163

**Comment by artem1205** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/26945
