### ISSUE TITLE
Prefix option is not clear in connection page

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2674]
## Tell us about the problem you're trying to solve
![2021-03-30_11-31-15](https://user-images.githubusercontent.com/1154337/113040246-723c5d00-914d-11eb-8a6e-a6e085ae95cc.png)

## Describe the solution you’d like
- The placeholder could be empty: `/configured-setting` doesn't ring a bell to me
- Should the title be: "Destination stream prefix"
- and the description: Prefix so streams with the same names from different sources don't clobber eachother

**Comment by jrhizor** [comment]
Also `/configured-setting` implies a path-style prefix in files, which doesn't make sense for dbs. It also isn't clear if you should be doing `prefix-`/`prefix_` or `prefix`

**Comment by cgardens** [comment]
Mostly fixed by @davinchia in this PR: https://github.com/airbytehq/airbyte/pull/2704. the rest in this one: https://github.com/airbytehq/airbyte/pull/2772
