### ISSUE TITLE
File CDK: Implement JSONL-specific options

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#26764]
Support the "Allow newlines in values" (T/F) option, which is supported in the existing `source_files_abstract`.

The existing [`source_files_abstract` JSONL parser](https://github.com/airbytehq/airbyte/blob/776f650e9cc8abe25206e96de861c8202fd6fed6/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/jsonl_parser.py#L67) should be helpful, as it includes this option.

For details on the adoption of this option see the [appendix of the File-Based CDK Proposal](https://docs.google.com/document/d/1f9rlYK27onB2dqjS40YKXdKbCytG1Xh0q_mMUP-_Ceg/edit#heading=h.yoaiqhjxe8te).

#### Acceptance Criteria
- [ ] Thorough test coverage.
- [ ] User input is validated during the connection check. Bad input values are surfaced in appropriate error messages.

**Comment by maxi297** [comment]
Follow-up
* Specifying newlines_in_values does not change the behavior i.e. having this True or False still allows for multiline JSON. It means that we would not only have to confirm if actor where configuration->'format'->>'newlines_in_values' = 'true' but all the actors with JSONL files
* The drawback block_size issues using pyarrow seems too annoying for now as it broke stream before
* We agreed on supporting multiline jsonl by brute force in the CDK and adding log to see if users actually have this. We will add a reminder to search for this log after the release. Unfortunately, we will only know this once V4 is installed though
