### ISSUE TITLE
Source Jira: connector does not expand nested fields in issues.fields

### ISSUE THREAD

**Issue by matveykortsev** [airbytehq/airbyte#26778]
### Connector Name

source-jira, destination-clickhouse

### Connector Version

0.3.10, 0.2.3

### What step the error happened?

During the sync

### Revelant information

Im launching Airbyte on AWS EKS using helm chart, expecting that after sync in table, jira_issuess_fields will be untested fields from issues.fields but instead of that I have the following structure without any errors during sync.
<img width="430" alt="Снимок экрана 2023-05-30 в 18 40 45" src="https://github.com/airbytehq/airbyte/assets/78414814/8d1fb253-58af-44c9-81ab-c5fe97289eac">
Tried with incremental and full sync but the result is the same.
[c6def73f_f83c_4281_9fc0_f1f75aa28a40_logs_43_txt.txt](https://github.com/airbytehq/airbyte/files/11602354/c6def73f_f83c_4281_9fc0_f1f75aa28a40_logs_43_txt.txt)
Source connector settings
<img width="649" alt="Снимок экрана 2023-05-30 в 18 45 29" src="https://github.com/airbytehq/airbyte/assets/78414814/f3fcd9fa-eff2-43eb-b17b-970cfe12705f">

### Contribute

- [ ] Yes, I want to contribute

**Comment by artem1205** [comment]
@matveykortsev, IssueFields stream is getting populated with the data from [this endpoint](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-fields/#api-rest-api-3-field-get).

Which specific field or streams are you interested in?

**Comment by artem1205** [comment]
closing this issue due to no response.
