### ISSUE TITLE
Move release version to github actions

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2678]
## Tell us about the problem you're trying to solve
* To release a new version, I need to stop developing for 15 minutes while I wait for dockerfiles to upload from my local machine.

## Describe the solution you’d like
* I want to be able to trigger releases from github actions.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368156844015) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
This is done with the release OSS action.
