### ISSUE TITLE
[Roadmap] 🔐 SSO support and RBAC for Airbyte Cloud

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#26788]
Make Single-Sign On (SSO) and Role-Based Access Control (RBAC) available in Airbyte Cloud. This will allow you to connect your own identity provider (e.g. Okta) to Airbyte Cloud to let all your users log into your Airbyte account and manage their permission via RBAC.

You can stay up-to-date on Airbyte's latest announcements [here](https://airbyte.com/blog-categories/company-updates).

**Comment by ricardosouzamorais** [comment]
Why shouldn't we add this to OSS ?

**Comment by timroes** [comment]
@ricardosouzamorais We just had separate roadmap items for those. The roadmap item for [SSO on premise](https://github.com/airbytehq/airbyte/issues/26786) has already been closed. You can get in [touch with us](https://airbyte.com/company/talk-to-sales) if you require this. RBAC support for on prem is tracked here: https://github.com/airbytehq/airbyte/issues/26787

**Comment by timroes** [comment]
SSO and RBAC support is now available on Cloud. Please get in [touch with us](https://airbyte.com/company/talk-to-sales) if you want to enable this feature.
