### ISSUE TITLE
[Roadmap] 🔐 RBAC support for Airbyte Enterprise

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#26787]
Role-Based Access Control (short RBAC) allows you to give more fine grained access to users for you self-hosted Airbyte instance (this won't be available on Airbyte Cloud initially). Users can have read-only permissions, write permissions or admin permissions.

You can stay up-to-date on Airbyte's latest announcements [here](https://airbyte.com/blog-categories/company-updates).

**Comment by mvgijssel** [comment]
Would this include the ability to give groups and/or users selective write permissions to pipelines? For example engineering can start/stop/view their own pipelines, but not those of the sales department?

**Comment by timroes** [comment]
@mvgijssel You will be able to do this by leveraging multiple workspaces. There won't be a concept of "connection level security" (as for now), but you can specify permissions based on individual workspaces, so you would give your Sales department one workspace and your Engineering one, and make sure they only have permissions to the appropriate workspaces.

**Comment by mvgijssel** [comment]
Sounds perfect! Can’t wait! As this is related to Enterprise, does that mean there will also be SCIM/SAML integration?

**Comment by timroes** [comment]
@mvgijssel We're currently not having SCIM support in our roadmap (you might find a separate item for that later, if we plan to add it). SAML won't be supported in the first release of SSO either, at the moment we only support Okta as an upstream Identity Provider, but plan to add more (like SAML) in the future. Please feel free to reach out to us [here](https://airbyte.com/company/talk-to-sales) if you want to discuss more about your specific use-case.

**Comment by nataliekwong** [comment]
An update here: we have shipped workspace-level access, which allows users to access specific workspaces within your organization.

However, we have yet to build read-only roles, and are continuing to work on the feature. We expect to deliver this in the Feb - April quarter.

**Comment by timroes** [comment]
RBAC support (with Reader roles for now) is available in Enterprise as of now.
