### ISSUE TITLE
Improve error messages for Shopify source 

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26799]
Improve the error messages we emit when users set up Shopify source.

For reference, here is a list of the error codes from Shopify: https://shopify.dev/docs/api/usage/response-codes

Type of error: The Shopify Store is incorrect/doesn't exist, but the Shopify API token is correct. Seen during setup of the connector.
> IndexError('list index out of range')

Suggestion: Failed to access the Shopify store "xxxxxx". Verify the entered Shopify store.

Type of error: Shopify API token is incorrect
> HTTPError('401 Client Error: Unauthorized for url: https://xxx.myshopify.com/admin/api/2022-10/shop.json?limit=250&order=updated_at+asc&updated_at_min=xxx')

Suggestion: Failed to access the Shopify store "xxx" with the entered API token. Verify your API token is valid.

Type of error: Either the Shopify store or the API token is incorrect.
> HTTPError('400 Client Error: Bad Request for url: https://xxx.myshopify.com/admin/api/2022-10/shop.json?limit=250&order=updated_at+asc&updated_at_min=xxx')

Suggestion:  Failed to access the Shopify store "xxx" with the entered API token. Verify the entered Shopify store matches your Shopify URL and your API token is valid.

Type of error: Not sure - need more information. Only shows up on connector check.
> ConnectionError(MaxRetryError("HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /xxx.myshopify.com.myshopify.com/admin/api/2022-10/shop.json?limit=250&order=updated_at+asc&updated_at_min=2023-04-01 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f78cba524c0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))"))

Suggestion: I need assistance looking into this error, as I do not understand why this is happening. I'm unable to reproduce. 

Type of error: Don't have the appropriate scopes
> 403 Client Error: Forbidden for url: https://xxx.myshopify.com/admin/api/2022-10/price_rules.json?limit=250&order=updated_at+asc&updated_at_min=2023-04-09\

Suggestion: Unable to access Shopify endpoint for {stream name}. Check that you have the appropriate access scopes to read data from this endpoint.

Type of error: Not sure - need more information.
> Source didn't exit properly - check the logs!\n'>' not supported between instances of 'str' and 'NoneType'

Suggestion: I need assistance looking into this error, as I do not understand why this is happneing. Example: https://cloud.airbyte.io/workspaces/551f87fc-c58f-4488-85c6-b8eedee40735/connections/d8bda749-5704-474a-8270-9c52b8f3aa19/job-history#1885927::2

**Comment by bazarnov** [comment]
@nataliekwong If fact, this connection uses the `source-shopify` version `0.3.2`, which is very old, because the latest is `0.5.0` This should be fixed starting from: `0.3.3`. They need just to start another sync, they should be good with the latest version.

Please check the `changelog` for the `source-shopify` for more info about the issues fixed.

**Comment by nataliekwong** [comment]
Thanks @bazarnov for the update!
