### ISSUE TITLE
[Call for early adopters] Postgres cursorless incremental syncs

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#26803]
To participate as an early adopter please fill out this [Google Survey](https://docs.google.com/forms/d/e/1FAIpQLSdmFpoM3NZA12OUFTsJIPzd3ufcGa1VqkXpjH0rT_eSnvEkpQ/viewform).

Cursorless syncs allow you to setup Standard Replication to sync new or updated rows without explicitly chosing a cursor for incremental replication. To track inserts and updates, we use a system column xmin available on all Postgres databases as a natural built-in cursor.

**Comment by akashkulk** [comment]
Closing
