### ISSUE TITLE
Sync hangs indefinitely instead of retrying

### ISSUE THREAD

**Issue by leecheeaun** [airbytehq/airbyte#2680]
## Expected Behavior
Sync should retry by itself instead of hanging indefinitely

## Current Behavior
Sync hangs indefinitely, with no option to cancel sync. Attempting to click the "Sync now" button to reset the sync doesn't work as well

## Logs
[logs-1630-0.txt](https://github.com/airbytehq/airbyte/files/6232856/logs-1630-0.txt)

## Steps to Reproduce
1. Configure sync source, destination and frequency
2. Let the sync run

## Severity of the bug for you
Critical

## Airbyte Version
0.17.3-alpha

## Connector Version (if applicable)
SQL Server 0.2.3
BigQuery 0.2.0

**Comment by sherifnada** [comment]
@leecheeaun 

Can you upgrade to the latest version of Airbyte (`0.18.2-alpha`) and see if the issue persists? 

To upgrade Airbyte while retaining all your configuration, follow [this tutorial](https://docs.airbyte.io/tutorials/upgrading-airbyte). 

Alternatively, if you are ok losing all your Airbyte configuration, run this from the Airbyte repository root: 
	1. `docker-compose down -v`
	2. `git pull`
	3. `docker-compose up`

This will create a fresh instance of Airbyte on the latest version.
