### ISSUE TITLE
Destination Snowflake: `check` connection sometimes OOM's

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#26804]
Destination Snowflake was observed to sometimes fail on setup while testing the connection.

@edgao observed this in production on 5/21.

I observed varying behavior on dev instances on 5/26 and 5/30 depending on which credentials were used.

- [`SECRET_DESTINATION_SNOWFLAKE_CREDS`](https://console.cloud.google.com/security/secret-manager/secret/SECRET_DESTINATION_SNOWFLAKE_CREDS/versions?project=dataline-integration-testing) OOM'ed on dev, and actually failed locally with a schema privilege error (so these credentials are probably out-of-date/invalid).
- [`SECRET_DESTINATION_SNOWFLAKE_INTERNAL_STAGING_CREDS`](https://console.cloud.google.com/security/secret-manager/secret/SECRET_DESTINATION_SNOWFLAKE_INTERNAL_STAGING_CREDS/versions?project=dataline-integration-testing) OOM'ed on dev, but succeeded locally.
- `Snowflake Performance Benchmark` credentials succeeded on dev.

From this last data point, the issue seems to be correlated with the Snowflake resource.

Other notes:
- Is this issue just with Snowflake? - Yes, destination Redshift (randomly chosen) works fine.
- Is this an issue with `check`? - Should not be, since this is working properly in some cases.
- Is this a memory issue? - Not sure, the `main` container for the `on-snowflake-check` pod in dev has 200 MB which is approximately what's expected (~300 MB total split among `main` and 3 other containers?). I imagine more memory (like when running Airbyte locally, running `/test`, etc.) can only help.
- Is this an issue with the shared Snowflake resource? - Possibly, the Snowflake Performance Benchmark credentials use a different warehouse than the other 2 credentials (all still on the same host). I dropped ~2k tables from the `INTEGRATION_TEST_WAREHOUSE_DESTINATION` warehouse but that didn't help (perhaps I didn't drop enough to make a difference). But `check` should just be creating and dropping a new table, so the number of tables in the warehouse shouldn't be an issue?
- We have not heard of customers running into this issue. 🤞

**Comment by evantahler** [comment]
We believe that this was due to over 8K schemas and even more tables existing in our test database.  We cleared them out manually using the technique described [here](https://github.com/airbytehq/airbyte/issues/26276#issuecomment-1569321067), and now it appears to be OK.  We should be better about clearing out test tables.
