### ISSUE TITLE
Source Amazon Seller Partner: new stream Catalog Items

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#26826]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
[Catalog Items](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference)
The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.
[catalog](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#item)
[item_classification_sales_rank](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemclassificationsalesrank) 
[item_dimension](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemdimensions)
[item_display_group_sales_rank](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemdisplaygroupsalesrank) 
[item_identifier](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemidentifier) 
[item_image](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemimages) 
[item_product_type](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemproducttypes)
[item_relationship](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemrelationships) 
[item_summary](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemsummaries) 
[item_variation_theme](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemvariationtheme) 
[item_vendor_details](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemvendordetails)

## Describe the solution you’d like
Research pros and cons for implementing this stream

**Comment by lazebnyi** [comment]
implemented or irrelevant endpoints
