### ISSUE TITLE
Source JIRA: Source is not extracting leads from project

### ISSUE THREAD

**Issue by jkleinkauff** [airbytehq/airbyte#26851]
### Connector Name

source-jira

### Connector Version

0.3.8

### What step the error happened?

None

### Revelant information

Our extraction is working ok apparently. The problem is, the connector is not extracting the leads information from the project endpoint.  Here, https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-projectidorkey-get

I believe it's  a json configuration from Airbyte perspective - not sure where tho.

I can contribute, I just need to know if the problem makes sense or if it may be some sort of configuration/permission from my side.

### Contribute

- [X] Yes, I want to contribute

**Comment by artem1205** [comment]
Added in https://github.com/airbytehq/airbyte/pull/26920
