### ISSUE TITLE
Sync Settings field should display the entire text.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#2685]
## Expected Behavior
When setting up a new connection, I expect to clearly see what kind of sync setting I am selecting.

## Current Behavior
Right now, the field truncates part of the option text, making it seem like users are selecting `Full Refresh` when they were actually selecting `Full Refresh - append`. This is confusing.

![](https://files.slack.com/files-pri/T01AB4DDR2N-F01TA71RG2V/image.png)

## Steps to Reproduce
Check out the latest airbyte server and try to set up a connection. 

## Severity of the bug for you
 Medium

**Comment by Jamakase** [comment]
@davinchia right now we set to be default what we already receive from backend for destinationSyncMode. Right now most of the streams has append set on the backend by default. So if it is returned as overwrite from the backend - we will set it.
