### ISSUE TITLE
Destination Redshift: Rollout 10%

### ISSUE THREAD

**Issue by ryankfu** [airbytehq/airbyte#26876]
Completed and rolled out by Jun 9th

Implementation - delete this custom size check code from Redshift and async-ify

Monitor for bugs and fix (make new stories) as needed

**Comment by evantahler** [comment]
Grooming

Redshift is special because we test the size of every entry in the JSON object to make sure it will fit.  DeSer effects RAM.  What do we do here?  Redshift might need a different logic about what % of memory to reserve.  More memory management is needed

**Comment by evantahler** [comment]
The current implementation may violate our [principals](https://docs.google.com/document/d/1oETYBlih3CIP9l89Ht56elXAPMc74MrTJnQT1bxOv0A/edit#heading=h.xshzdpoa9tzn) because we are saying the sync succeeded but dropping records which are too big.   - Team votes yes on this

**Comment by evantahler** [comment]
This seems safe to remove, we [haven't logged this message in the last week](https://console.cloud.google.com/logs/query;lfeCustomFields=labels%252F%2522k8s-pod%252Fconnection_id%2522,labels%252F%2522k8s-pod%252Fjob_id%2522;query=%22were%20invalid%20and%20were%20ignored%22;summaryFields=labels%252F%2522k8s-pod%252Fconnection_id%2522,labels%252F%2522k8s-pod%252Fjob_id%2522:false:32:beginning;timeRange=P7D?project=prod-ab-cloud-proj)
