### ISSUE TITLE
Bug: Airbyte Cloud Connection Screen sometimes shows empty list of connections

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#26872]
### Revelant information

Occasionally on Airbyte Cloud, I am shown the Connections stream and no connections load, making it look like I have no connections set up. 

I can't figure out what actually causes this bug. Sometimes it happens when I update a connection. Sometimes it happens when I delete a connection. I will make sure to document the steps to reproduce next time it happens.

**Comment by chandlerprall** [comment]
Took at a look at the session; the call to `/api/v1/web_backend/connections/list` took 20.7 seconds, but the connections list page apparently doesn't distinguish between data-is-loading and no-data states.

**Comment by alex-gron** [comment]
Additional details from Slack convo:

- I think the Airbyte loading icon is what typically shows on the connection page, but for some reason, it occasionally shows me the empty page.

- It seems to happen after I make changes to connections, but I couldn’t figure out how to get it to happen again today, so I guess it is intermittent.

- This probably happens more often to me because we have so many connections in our workspace, so it might be an edge case, but could be more prevalent as we get more API and PbA users.

**Comment by chandlerprall** [comment]
#### Reproduction

* open a workspace with 0 connections
* goto workspace selection page
* open a workspace with 1+ connections
* observe the 0 connections screen while the query re-fetches in the background

https://github.com/airbytehq/airbyte/assets/313125/af6aa476-c480-4217-998d-e3e202f7b7ce

#### Cause

`useConnectionHook`'s query keys [are scoped to](https://github.com/airbytehq/airbyte-platform/blob/71803037535af7f95ea35b668ca2ebf1aaf26fb5/airbyte-webapp/src/hooks/services/useConnectionHook.tsx#L39) `["scope:workspace", "connections", ...]` with no unique identifier for the connection. When the connections page is re-mounted the existing data is re-used while a new query is kicked off to update the stale data.

**Comment by chandlerprall** [comment]
Introduced by https://github.com/airbytehq/airbyte-platform/commit/559e84c5c5c42151108ea2a51265f490b0da65b0 which converted the workspace selection from a button to a link so workspaces could be opened in a new tab. The button version cleared workspace-scoped query caches.
