### ISSUE TITLE
Add feedback to manual launches in the UI

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2689]
## Tell us about the problem you're trying to solve
![image](https://user-images.githubusercontent.com/1154337/113172369-39f45780-91fd-11eb-9466-854cab9215e3.png)

There is no UI feedback when pressing launch.

## Describe the solution you’d like
Would love to have something similar to the `sync now`
![2021-03-31_08-44-55](https://user-images.githubusercontent.com/1154337/113172563-6019f780-91fd-11eb-9418-41a39864b9f0.png)

**Comment by jrhizor** [comment]
Maybe it should also say `Sync now` too

**Comment by cgardens** [comment]
agreed with both things.

**Comment by Jamakase** [comment]
@michel-tricot What is meant as feedback here? Do you mean that you want loading state for button displayed while sync request is sent or that connection info should also be changed?

Currently, this button is a sort of fire and forget. If we want to have here real-time updates without webhook - we will need to add polling, but I do not think it is a good idea as we will poll all of the connections quite often.

Do you want just to see short loader for button when the launch is pressed or we want also to see job status updated in real time?

**Comment by michel-tricot** [comment]
@Jamakase can we have a similar behavior as when we press 'Sync Now' on the connection page? (which is also a fire and forget)

Right now it is hard to know if the click did anything
