### ISSUE TITLE
Pass control message to connector builder frontend

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#26909]
### What area the feature impact?

Connectors

### Revelant Information

As a connector developer developing for single use refresh token API, I don't want to enter a new refresh token every time I do a test read

## Context
Some APIs invalidate the refresh token once it's used (for example, quickbooks and GitLab). The platform and the CDK already have a mechanism to support this where a control message is emitted with the new configuration. We need to replicate this mechanism.

## Gap
Today, the connector builder is silencing those messages. We need to return the latest one to the frontend so that it updates its config. In order to do that, we will:
* Return the most recent AirbyteControlConnectorConfigMessage as part of the API
* Frontend will use this information to update it's config

## Acceptance criteria
- [ ] A connector developer developing for single use refresh token API only needs to enter the refresh token once when opening the connector builder project. Do an example with an API
- [ ] Disable testing values menu while request is in flight to avoid race condition

**Comment by flash1293** [comment]
I'll move this back to the sprint backlog for now as it depends on the refresh token authenticator being available in the UI

**Comment by flash1293** [comment]
Un-assigning myself for the next week
