### ISSUE TITLE
File CDK: investigate block_size argument to pyarrow

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#26923]
The existing `source_files_abstract` CSV, JSONL, and Parquet parsers all use pyarrow for schema inference. They pass a [`block_size` argument](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html) to pyarrow, which determines what size chunk will be read from the file. If this size is too small, we may not get a chunk big enough to read, e.g., the first row of data from a CSV, making the header unparsable for CSVs; it's not clear whether a too-small block size impacts JSONL or Parquet files.

When no `block_size` parameter is used, pyarrow [uses the maximum integer](https://github.com/apache/arrow/blob/f5a57292e5187b1a1640b04303e9f6b63135892a/c_glib/arrow-glib/reader.cpp#L1975) allowed by the system.

We'd like to remove `block_size` as a configuration option for users. We have two options for doing this: 1) letting pyarrow use the default `block_size` of `G_MAXINT`, or 2) intelligently setting the block size (e.g. if we get errors due to it being too small we increase it).

Ideally we'd like to do 1 because it's much simpler. However, before we can do this, we want to verify that pyarrow isn't reading the entire file into memory solely for the purpose of reading the header (in the case of CSV) or the metadata (in the case of Parquet).

This ticket it is for confirming whether we can use 1 and if not, recommend a path forward for 2.

#### Acceptance Criteria
- [ ] Recommend a path forward for deprecating `block_size`.

**Comment by clnoll** [comment]
Grooming notes: time box this so if it's difficult to know whether we can do 1, we just do 2 instead.

**Comment by girarda** [comment]
closing since we're not using `block_size` fields in the fcdk
