### ISSUE TITLE
Source LinkedIn Ads: Is there any way to extract `impression_device_type` via LinkedIn Ads Marketing API? 

### ISSUE THREAD

**Issue by Escen13** [airbytehq/airbyte#26934]
### Topic

Request a dimension breakdown

### Revelant information

According to their **Ad Analytics API**, starting with the 202304 version, we should be able to get `IMPRESSION_DEVICE_TYPE` pivot, and the results will be grouped by the device type the ad made an impression on, such as MOBILE_APP and DESKTOP_WEB .

![image](https://github.com/airbytehq/airbyte/assets/117926861/9cfe6131-453a-4d85-9bc7-30935a9561c2)

![image](https://github.com/airbytehq/airbyte/assets/117926861/63bc70b0-dd5b-4b2e-8a06-657d27ea5f21)
reference link: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/ads-reporting?view=li-lms-2023-05&tabs=http&#:~:text=IMPRESSION_DEVICE_TYPE

**Comment by Escen13** [comment]
Hi...would it possible to receive an update? It has been raised since a few weeks ago and your update is very important to me. Thanks..

**Comment by artem1205** [comment]
@Escen13 , New streams added in https://github.com/airbytehq/airbyte/pull/29175

**Comment by Escen13** [comment]
> @Escen13 , New streams added in #29175

Good day @artem1205, I have encounter some issues in the `..ad_impression_device_analytics` table and hope you may check it out.
- I found that the data in `_airbyte_raw_ad_impression_device_analytics` is not consistent, e.g., some of the objects in the json data is missing. Please refer ss below:
![image](https://github.com/airbytehq/airbyte/assets/117926861/36744172-2a72-4ad3-9509-e7cf92cb1489)

the json data in **1** has 48 objects whereas the data in **2** only has 18 objects, as below:
[1]
![image](https://github.com/airbytehq/airbyte/assets/117926861/0184edd4-9681-4a84-a30f-63b612112f3e)

[2]
![image](https://github.com/airbytehq/airbyte/assets/117926861/3c2b08f1-6c76-4af0-9f2a-2df483812036)

- I also noticed that there's an empty value in the device column (i.e., `pivotValues`), please refer the ss below:
![image](https://github.com/airbytehq/airbyte/assets/117926861/55f04f83-140a-4ab6-a447-fe8345506c27)


Besides, I'm not sure if  the value in the `pivotValues` object is missing, because I only get one record in one date, if not mistaken I should get 3 row in the same date.. please refer the ss below:
[Query result]
![image](https://github.com/airbytehq/airbyte/assets/117926861/f03fa40d-4f95-49eb-bf09-21e2ecf0caf9)

[Linkedin Campaign Manager]
![image](https://github.com/airbytehq/airbyte/assets/117926861/383870e5-7a1f-4e4f-903e-558dbf5c440c)

E.g., please consider 5/29/2022, as you can see that I only get 'Mobile Web' on that day but I should get 3 device breakdown, i.e. 'Desktop Web', 'Mobile App', 'Mobile Web', which shown in the Linkedin Campaign Manager. The sum value is correct, the problem is the other device breakdown is missing. Other than that, I'm not sure if you noticed that the query result only show one record per date and If I'm not wrong, I should get 3 row per date.

Much appreciate if you could help identify the exact issue. Look forward to your feedback.
