### ISSUE TITLE
Deprecated Metabase API Endpoint 'Activity'

### ISSUE THREAD

**Issue by luis-settle** [airbytehq/airbyte#26959]
### Connector Name

source-metabase

### Connector Version

0.3.1

### What step the error happened?

Configuring a new connector

### Revelant information

Metabase has deprecated the 'activity' endpoint. Airbyte's Metabase source connector is still looking to hit this endpoint that no longer exists, and as a result, the test connection in the source configuration window is failing. Airbyte needs to update the source connector to only look for card, collections, dashboard, and user endpoints. 

It would also be great if when configuring the source connector, the user could select which endpoints to hit so that when updates from Metabase are made, the user can pivot quickly without the connection breaking. Airbyte does offer the user the ability to select which streams to set up, but this is only after the connection is made. This option needs to be available when configuring the source connector. 

### Relevant log output

```shell
Configuration check failed. Unable to connect to stream activity - Request to https://settle.metabaseapp.com/api/activity failed with status code 404 and error message None
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/27777
