### ISSUE TITLE
Show a Source/Destination "Settings" instead of it's connections

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26968]
When users navigate to a Source or Destination, they first see the list of Connections that source/destination has, with "Settings" as an option to the right.

2/3 of users navigate to "settings" for both sources & destinations. 
https://app.fullstory.com/ui/13AXQ4/funnels/details/lP6zCputD2dV?step=3&completed=false&completeSessions=false

Since most of our users are actually looking for the "Settings", we could change the navigation so that when a user clicks on a Source/Destination from Sources.List or Destinations.List, they actually go to the settings first, as that is more commonly what they are looking for. It could also help with the confusion users might have when navigating their connections, sources, and destinations lists.

Some other considerations:
- "Overview" isn't actually an overview, it's a list of connections. Should that be renamed to "Connections"? 
- "connections" is not capitalized under the "Overview" header. Do we need to keep that text if we rename the tab? 

How it looks today: 
![Screenshot 2023-06-02 at 9 34 56 AM](https://github.com/airbytehq/airbyte/assets/38087517/a78c0fdd-3b68-4e12-b8ba-713c03278a23)

cc @tealjulia

**Comment by josephkmh** [comment]
Refining notes:
- "Settings" should be the first tab, "Connections" can be the second tab
- OK to change the URL here (`sources/<uui>` leads to the connector settings, `sources/<uuid>/connections` leads to the overview of connections).
