### ISSUE TITLE
dagger: `TransportQueryError: ***'message': 'failed to solve: unknown blob` 

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#26963]
We transiently and very occasionnaly face the following error:
```
TransportQueryError: ***'message': 'failed to solve: unknown blob sha256:815b010d35f3c0bbd78e7b89f7410445ec93f f9a75a8e7ad94a557e9d55d1194 in history
```
It happened to the `source-linkedin-ads`in this workflow:
https://github.com/airbytehq/airbyte/actions/runs/5149952905/jobs/9273557661

**Comment by vito** [comment]
Maybe wrong link? :) Looks like a successful run, can't find any of the mentioned terms in the logs.

**Comment by vito** [comment]
Looks like there's an issue for this upstream in Buildkit: https://github.com/moby/buildkit/issues/3921 - but they're asking for a minimal repro, which seems tricky. Will look deeper and try to come up with some theories.

**Comment by alafanechere** [comment]
> Maybe wrong link? :) Looks like a successful run, can't find any of the mentioned terms in the logs.

I confirm the link is correct, if you grep for "unknown blob" in the full log you should find it.
The workflow is successful because I made connector specific errors handle Daggers errors gracefully.

**Comment by vito** [comment]
In a stroke of luck, I hit this error while running Dagger's own tests. Full logs [here](https://gist.githubusercontent.com/vito/ab62e34fe0b31a5143b4b5db05adb12f/raw/419704a4cf18a409c088c0b9768541b9a0fa72af/unknown-blob.txt).

Ctrl+F `f1ad8732d84648b393bd4cc17b9b3741912318330bb8d106c7ed651b3f797eec`

You can see from the Dagger engine logs (`exec dagger-entrypoint.sh /bin/sh`) that the blob was removed within the same second that the error occurred:

```
time="2023-06-05T23:51:44Z" level=debug msg="removed content" digest="sha256:f1ad8732d84648b393bd4cc17b9b3741912318330bb8d106c7ed651b3f797eec"

# ...

time="2023-06-05T23:51:44Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = unknown blob sha256:f1ad8732d84648b393bd4cc17b9b3741912318330bb8d106c7ed651b3f797eec in history"
unknown blob sha256:f1ad8732d84648b393bd4cc17b9b3741912318330bb8d106c7ed651b3f797eec in history
14 v0.0.0+unknown /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml --network-cidr=10.88.0.0/16 --network-name=dagger-dev /bin/sh
github.com/moby/buildkit/solver/llbsolver.(*HistoryQueue).addResource
```

Seems like a race condition to me. (Will relay this comment to the upstream issue.)

**Comment by vito** [comment]
A fix has been merged in Buildkit and bumped in this commit: https://github.com/dagger/dagger/commit/db00a4c5a4ff28e1354256e991edadccc03ad299

Dagger engine version:

```
registry.dagger.io/engine:main@sha256:935a9df9d9480f1f6a3f41c4caa65ad4304c99e4371610f45748b16ab46cfc7c
```

Since this is a Buildkit fix, no CLI bump is necessary, but I guess you could anyway (`db00a4c5a4ff28e1354256e991edadccc03ad299`).

**Comment by alafanechere** [comment]
Thank you Vito, I faced this error again in https://github.com/airbytehq/airbyte/actions/runs/5211403648/jobs/9403656736
I upgraded the daemonset to use the new image. I'll let you know if it happens again!
