### ISSUE TITLE
Source Mailchimp: Get data from endpoints List

### ISSUE THREAD

**Issue by jrolom** [airbytehq/airbyte#26965]
### Revelant information

Get information about list members from these two endpoints:
[1] [List Member info](https://mailchimp.com/developer/marketing/api/list-members/list-members-info/)
[2] [Get Member info](https://mailchimp.com/developer/marketing/api/list-members/get-member-info/)

**Comment by jrolom** [comment]
@igrankova  added this issue to get data for two endpoints for Mailchimp source connector. I will find a contributor to work on these, would you mind though adding any clarification comments in the issue description please?

**Comment by fev4** [comment]
Hey there @jrolom,

I'm not the person who first suggested this issue, but we are finding ourselves in need of the information provided by these two endpoints. What we need is a table following the next structure:

- List Id
- Member Email
- MD5 Id
- Unique Email Id
- Web id
- Contact id
- Source
- Status ("subscribed", "unsubscribed", "cleaned", "pending", "transactional", or "archived")
- Merge fields (this should include First Name, Last Name, and any other business-defined merge field)
- Tags
- IP signup
- Timestamp signup
- IP opt-in
- Timestamp opt-in
- Last changed
- Unsubscribed reason
- Consent to 1-1 messaging
- Location information
- VIP status
- Avg open rate
- Avg click rate

This would solve several issues we are having with the current connector.

**Comment by jrolom** [comment]
Hi @fev4 !  Are you open to work on this to add these endpoints to the connector?

**Comment by Alcadeus0** [comment]
I'd like to take this issue up :)

**Comment by fev4** [comment]
Hey @jrolom, I don't think I'll be able to help in this aspect. I'll read the docs about how to create a connector though - in a couple of weeks once I'm more free. I'm totally new in that aspect.

Thanks for taking this @Alcadeus0

**Comment by Alcadeus0** [comment]
Hey @jrolom for the [Get member Info](https://mailchimp.com/developer/marketing/api/list-members/get-member-info/) we add a "subscriber hash" to the url. The "subscriber hash" is The MD5 hash of the lowercase version of the list member's email address. This endpoint also accepts a list member's email address or contact_id. Should the spec file have a separate parameter to allow the user to enter the subscriber hash value? I think it's possible to retrieve it from the parent stream but then in my opinion it defeats the purpose of having a separate member info stream if we are implementing the first endpoint. Your thoughts?

**Comment by jrolom** [comment]
hey @Alcadeus0 - the preferred solution would be to get email address from _list-members-info_ endpoint and use it for _Get member Info_. Let me know if that solves your question

**Comment by aazam-gh** [comment]
@jrolom Yep gotcha, so it will be like a nested stream of the list-members-info endpoint.
