### ISSUE TITLE
Change `bash` shell to `sh` to all Airbyte Platform containers

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#26960]
### What area the feature impact?

Airbyte Platform

### Revelant Information

Started the proposal here: https://github.com/airbytehq/airbyte-platform/pull/240/files

**Comment by cpdeethree** [comment]
As per #26958, this ask originates from using Alpine. Since we determined that the end user didn't actually want Alpine itself, just what it offered for security, we are moving to close this issue since we are tackling the security problem from another angle
