### ISSUE TITLE
Improve Bing Ads connection error messages

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26973]
Error type: Refresh token expired
> OAuthTokenRequestException('invalid_grant', 'xxx: The user could not be authenticated as the grant is expired. The user must sign in again.

Suggestion: The refresh token expires after 90 days. Repeat the authorization process to get a new refresh token. The full authentication process is described [here](https://docs.airbyte.com/integrations/sources/bing-ads/). Please be sure to authenticate with the email (personal or work) that you used to sign in to the Bing Ads/Microsoft Ads platform.

Relevant oncall issue: https://github.com/airbytehq/oncall/issues/2091

**Comment by darynaishchenko** [comment]
fixed in https://github.com/airbytehq/airbyte/pull/30834
