### ISSUE TITLE
Update Hubspot API v3 connectio

### ISSUE THREAD

**Issue by stammi922** [airbytehq/airbyte#2699]
## Tell us about the new integration you’d like to have
Additions to the new [Hubspot connector](https://docs.airbyte.io/integrations/sources/hubspot).
The Hubspot Deals API Endpoint does not return the deal's history, which means information regarding the deal:

* Enter date of a deal into a pipeline stage
* Exit date of a deal into a pipeline stage
* Overall time spend in seconds of a deal spend in a pipeline stage

This relates to the already opened issue #2114 

## Describe the context around this new integration
The way the new Hubspot API v3 handles the fetching of deal history is a little more cumbersome compared to the previous API Version. 

You need to fetch all [Deal Stages](https://legacydocs.hubspot.com/docs/methods/pipelines/pipelines_overview) before being able to fetch the history on the deals themselves. 
The name of the Deal Stage can then be used as a property query parameter for requesting deals with their history. 

This means that the api-call to the `/crm/v3/objects/deals` need

* `hs_date_entered_{{DEAL_STAGE_ID}}`
* `hs_date_exited_{{DEAL_STAGE_ID}}`
* `hs_time_in_{{DEAL_STAGE_ID}}`
for every Deal Stage you want to fetch the history of, which ideally would be all of them. 

Example:
`https://api.hubapi.com/deals/v1/deal/paged?hapikey=demo&includeAssociations=true&limit=100&properties=dealname&properties=hs_date_entered_qualifiedtobuy&properties=hs_date_exited_qualifiedtobuy&properties=hs_time_in_qualifiedtobuy&properties=hs_date_entered_contractsent&properties=hs_date_exited_contractsent&properties=hs_time_in_contractsent...`

As far as I could figure out, there is currently no easier way than expanding the list of properties appended to the request URL.

## Describe the alternative you are considering or using
Have made a small script myself. Otherwise, making a complex structure in something like Integromat, which works not very well for iterations.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368098850798) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
thanks for creating the issue @stammi922 . Would you be interested in opening a PR to contribute this feature? No worries if not.

**Comment by stammi922** [comment]
Hi @sherifnada,
No worries. Sadly I am a little short of time these days, so I'll not be able to write the script. 
Could you put these adjustments into the pipeline or is that entirely out of your scope right now?

**Comment by sherifnada** [comment]
We're prioritizing a number of highly requested new integrations for the next few weeks over this, but if we get a lot of interest in the meantime we'll definitely reprioritize. I'll keep this in mind as we do roadmapping for the next few weeks and will keep you posted!

In the meantime, if you're curious about what it'd take to contribute this, see the connector module here: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py

**Comment by jacob-a6** [comment]
> This means that the api-call to the `/crm/v3/objects/deals` need
> 
> * `hs_date_entered_{{DEAL_STAGE_ID}}`
> * `hs_date_exited_{{DEAL_STAGE_ID}}`
> * `hs_time_in_{{DEAL_STAGE_ID}}`
>   for every Deal Stage you want to fetch the history of, which ideally would be all of them.

Two possible solutions are:

1. fetch and inject `dealstage` history from `/deals/v1/deal/paged` (one `timestamp` per version)
2. refetch all stageIDs from the `/crm-pipelines/v1/pipelines/deals` and inject those as `propertiesWithHistory` to `/deals/v1/deal/paged` as @stammi922 described. Note that `hs_date_entered`, etc are "hubspot-internal" pseudoproperties. This logic would differ greatly from the [current source's abstractions](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/api.py).

The [pseudoproperies in approach (2) might get deprecated in the future](https://community.hubspot.com/t5/APIs-Integrations/Please-ensure-deal-stage-history-is-available-via-the-API/m-p/349987/highlight/true#M34303). Also, https://github.com/airbytehq/airbyte/issues/2397 flags that `hs_time_in` values are omitted to prevent test flakes.

I was working on a PR for approach (1) (it injects `dealstage` histories from `/deals/v1/deal/paged` into records returned by `/crm/v3/objects/deals`). If each `timestamp` in a `dealstage`'s history array corresponds to a `hs_time_entered`, then `hs_time_in` values can be derived via subtraction (version[i].time minus version[i-1].time). This is simple to implement, but only retrieves `dealstage` timestamps. 

@stammi922, is making multiple API calls for `hs_time_exit/in` values necessary or would the `dealstage` timestamps from approach (1) be sufficient for your [sales funnel analysis](https://github.com/airbytehq/airbyte/issues/2527#issuecomment-811119202)?
