### ISSUE TITLE
File CDK: Packaging decisions

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#27018]
Investigate build times of the CDK with the addition of libraries required to support the file module. If we're impacting build times (>10% increase?), reorganize the dependencies as needed and document the steps required to created a file-based CDK Python package variant, to avoid bloating the CDK pip package size.

Note: if we do use a file-based CDK variant, all file-based sources will use this package variant, and code for that variant will be in the main CDK. Any additional dependencies that sources have will be specified in the individual source’s setup.py.

#### Acceptance Criteria
- [ ] Documentation for using the file-based CDK (as a package variant or as part of the main CDK) exists, and dependencies are organized as appropriate.

**Comment by clnoll** [comment]
Grooming notes: 
- On hold until needed.

**Comment by girarda** [comment]
we had to move the [pyarrow dependency to a variant package](https://github.com/airbytehq/airbyte/pull/28413/files) because most connector's docker image couldn't install it

Installing the CDK with either `dev` or `file-based` will install the right dependencies

**Comment by girarda** [comment]
closing because it's packaged as a CDK variant. feel free to re-open if the packaging requires further enhancements
