### ISSUE TITLE
Add notification webhook URL field to settings page UI

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#2701]
## Tell us about the problem you're trying to solve
Following up on https://github.com/airbytehq/airbyte/issues/1690 and https://github.com/airbytehq/airbyte/issues/1689, a user should be able to set up an optional notification webhook URL that will be triggered whenever a connection/sync fails.

(if the setting is not set, the notification is not sent)

## Describe the solution you’d like
Following the mock-up here: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A784

- [x] Mock up ready
- [x] Back-end ready for notifications settings in workspace
- [x] API to try/test notification settings `api/v1/notifications/try`
- [ ] Front-end work to enable notification settings

## Additional Context
Spec document:
https://docs.google.com/document/d/1H4Uas2cO2XLt1Hh0I7kF_3tJyHiNbYPqEMq0PkciSc8/edit#

**Comment by johnlafleur** [comment]
Draft for design: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=24422%3A126887
