### ISSUE TITLE
Simplified sync catalog table row design

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#27023]
* "Data destination" = whatever the user has configured for their Destination namespace
* Stream name = source stream name
    * Discussed: If there is more than one source namespace, it should _also_ have the source namespace (ie: `public/users`)
* Streams column goes to end of row
* Cursor and primary key are no longer configurable in this view (only configurable in the stream details panel)
* Engineer to confirm with Nico how columns should resize with screen sizes + to determine if this issue should be split into multiple issues + flagged

https://www.figma.com/file/AxqFXuHo2BoTY0QY12hxm1/00_02_WEB-APP-COMPONENTS?type=design&node-id=1315-9150&t=u5JMQKClczqg4U7N-0

**Comment by josephkmh** [comment]
Notes from assemble meeting:
- https://docs.google.com/document/d/1wV1rESthTEe4Qj0o1dP9L3EtX6j75DNyo4CgqiRyXcw/edit#heading=h.5c82myw97yrt
