### ISSUE TITLE
[OSS issue] Update OSS documentation for docker prune

### ISSUE THREAD

**Issue by supertopher** [airbytehq/airbyte#27020]
#maybe don't fill up the whole disc with old images!

![imagine another one](https://media4.giphy.com/media/tgZyQetNWP4cZjwUlx/giphy.gif?cid=ecf05e47riu8at6b3evgwm10xvp8pra9k5e6dffof4mbrthz&ep=v1_gifs_search&rid=giphy.gif&ct=g)

Docker doesn't murder old images.  Lets's clear up an old issue and update the documentation to show people how to use docker prune with cron for the people who are using docker as a production or at least long term solution

[this will close this issue](https://github.com/airbytehq/airbyte/issues/2322)
[resolve the line item in this doc] when complete(https://docs.google.com/document/d/1BxcupwKvel9CPVVksf1U9PRLz0Dwy7AkEWVjrjkLcdk/edit?usp=sharing)

[location of the document to update](https://github.com/airbytehq/airbyte/blob/master/docs/operator-guides/scaling-airbyte.md)

**Comment by supertopher** [comment]
angel has context on a sketch part of docker prune for live runs

**Comment by cpdeethree** [comment]
The outcome is that Evan's team will take care of this documentation
