### ISSUE TITLE
Breaking change metadata validation: validate metadata existence and correctness 

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#27065]
Add a new validators to [metadata_validator.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-ci/connectors/metadata_service/lib/metadata_service/validators/metadata_validator.py) that validate:

1. If the version in the metadata file is a major version (n.0.0), the `releases` dict exists and contains a breakingChanges entry for `n.0.0`

Notes: 
2. We're relying on the new version being a major (n.0.0) - this wouldn't trigger on a major version bump that isn't n.0.0, e.g. if you for some reason bumped from 1.0.1 to 2.0.1 instead of bumping to 2.0.0. This is potentially something we could try to validate (or maybe we already do?), that the only valid version bumps are one patch, one minor, or one major. But the auto-bump version project will probably make that moot anyway. 
3. when working on auto bump version, we need to run these validations where we expect to perform a version bump, not once the bump has already happened (since by then the code is already merged and the connector dev cannot add the info - the build will just fail i guess)

**Comment by erohmensing** [comment]
Grooming: Socialize and agree upon point 3

**Comment by erohmensing** [comment]
Grooming: the conventional commit will cause an auto-commit on the branch that performs the major version bump, which kicks off the validation on the branch, before merge. so all good

**Comment by evantahler** [comment]
More Grooming notes:
* We should manually validate this rather than relying on Pydanic so we can keep our Java classes and Pydantic models 1-1 with the schema

**Comment by erohmensing** [comment]
> If breakingChanges exists, docs/integrations/{destination_type}/{connector_name}/migration_guide.md must also exist

This was was covered in another PR!

> f the version in the metadata file is a major version (n.0.0), the breakingChanges array exists and contains an entry for n.0.0

This one is the one left on this ticket. adjusting accordingly
