### ISSUE TITLE
Environment level telematics control during installation (enable/disable)

### ISSUE THREAD

**Issue by mhensley-cls** [airbytehq/airbyte#2707]
## Tell us about the problem you're trying to solve
Prevention of sensitive data like protected health information being improperly disclosed into Airbyte's analytics tooling.

## Describe the solution you’d like
Would like to disable all telematics (paperclips, segment, etc) during initial bootstrapping of Airbyte via an environment variable. Selection should persist system upgrades

## Additional context
Might be helpful to make more clear that the tooling is enabled by default, I only noticed while digging around in the Kubernetes config.

**Comment by michel-tricot** [comment]
Hey @mhensley-cls 

It is possible today by modifying the `.env` and add the following:
```
TRACKING_STRATEGY=logging
PAPERCUPS_STORYTIME=disabled
```

It should probably be in the doc, what do you think?

**Comment by mhensley-cls** [comment]
Hey @michel-tricot - yes, I noticed that config when reviewing the Kubernetes implementation. Jared asked me in slack to put this into an issue for further maturation. Clarity in docs would be awesome.

**Comment by michel-tricot** [comment]
Thanks! will work on it

**Comment by cgardens** [comment]
deliverable: add to FAQ
