### ISSUE TITLE
Source Github: New Stream Contributors

### ISSUE THREAD

**Issue by cesar-loadsmart** [airbytehq/airbyte#27074]
### Connector Name

source-github

### Connector Version

0.4.11

### What step the error happened?

Other

### Revelant information

The github connector ingests data from many different github rest api endpoints: 
`comments, commit_comment_reactions, commit_comments, commits, deployments, events, issue_comment_reactions, issue_events, issue_milestones, issue_reactions, issues, project_cards, project_columns, projects, pull_request_comment_reactions, pull_requests, pull_requeststats, releases, review_comments, reviews, stargazers, workflow_runs, workflows.`

However, it does not read data from the Contributors endpoint. This endpoint contains important metrics, such as: 
a - Number of additions
d - Number of deletions
c - Number of commits

More details can be seen: https://docs.github.com/en/rest/metrics/statistics?apiVersion=2022-11-28#get-all-contributor-commit-activity

### Relevant log output

```shell
There is no log output since the endpoint is not available to be selected.
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
I change the issue type from bug to enhancement.

**Comment by cesar-loadsmart** [comment]
Hey @marcosmarxm, I managed to solve this problem by using the no-code builder. I believe we can close this ticket.
