### ISSUE TITLE
DBT to Java Translation - BigQuery

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27076]
Since we're removing DBT and writing the typing and deduping logic ourselves, we need to catalog and understand this effort, ensuring that we are not degrading the quality of typing an deduping.

Definition of Done:
* look though dbt code and audit
* write Java interfaces
* write per-destination docs to capture what each implementation will do that is special. 

TODO: Write the same ticket for each other destination.

**Comment by edgao** [comment]
+1 to closing, we have separate issues to fix the various bugs that we're still aware of.
