### ISSUE TITLE
Airbyte API: Add Auto-Propagate Schema options

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#27082]
### What area the feature impact?

None

### Revelant Information

When the new feature to auto-propagate schema changes is rolled out, there will be 4 options in the UI:
<img width="310" alt="Screen Shot 2023-06-06 at 12 49 06 PM" src="https://github.com/airbytehq/airbyte/assets/109167606/56f194d9-8f4c-4c62-9b6b-b48ce6ef7783">

These options should also be available in the [Airbyte API](https://reference.airbyte.com/reference/patchconnection):
![Screen Shot 2023-06-06 at 12 49 38 PM](https://github.com/airbytehq/airbyte/assets/109167606/accd1f9a-12af-43be-bb5b-e064fe32d7f0)

**Comment by nataliekwong** [comment]
These are now available in the API!

<img width="635" alt="Screen Shot 2023-09-27 at 4 06 59 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/c48d0512-1ace-444e-ac36-ef8e7fc54fe9">
