### ISSUE TITLE
handle postgres cdc table name selection with better quote handling

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2710]
Until we store schemas and stream names separately, we cannot reconstruct and quote them for cdc table selection in all cases.

Example:
schema name: `a.b`
table name: `c.d`
stream name: `a.b.c.d`

Ideally we'd want to quote this for table selection as something like: `"a.b.""c.d"`, but that isn't possible until namespacing.

This specifically would mean improving the `getTableWhitelist` function.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368157474245) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
I just saw this - this is currently possible via #2869 .

**Comment by grishick** [comment]
Fixed here: https://github.com/airbytehq/airbyte/pull/2869

**Comment by edgao** [comment]
@davinchia @grishick is this issue still open?

**Comment by davinchia** [comment]
@edgao this should be possible to my knowledge. i haven't explicitly tested this specific case out.
