### ISSUE TITLE
Check if all conditions allow ctid sync

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#27114]
Verify that a ctid is necessary and possible.
Things that car prevent us from being able to use ctid:
1. An older version of postgres.
2. Ongoing `VACUUM FULL`.
3. A `VACUUM FULL` ran between the last ctid session and current one.
4. Saved state is of different type - meaning initial read is done.
5. Any other setting that indicates ctid cannot work such as a feature flag.

**Comment by prateekmukhedkar** [comment]
Not adding a check for Postgres version - because CDC has similar requirements with PG ver 9.x and we haven't faced customers using older version.

Checking for views is done in a separate PR.
