### ISSUE TITLE
Source Google Analytics v4 (GA4): dimensions and metrics filters

### ISSUE THREAD

**Issue by mpetrykin** [airbytehq/airbyte#27119]
### What area the feature impact?

Connectors

### Revelant Information

GA4 API has useful fields **dimensionFilter** and **metricFilter** according to [runReport documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport). Usage of these parameters will help users to receive certain data and save the API quota. To do this, we need to add the fields from this [FilterExpression documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/FilterExpression).
```[tasklist]
### Tasks
```

**Comment by mpetrykin** [comment]
I want to contribute this issue

**Comment by kdcyberdude** [comment]
Any update on this?

**Comment by tybernstein** [comment]
Closed via https://github.com/airbytehq/airbyte/pull/30460
