### ISSUE TITLE
Combine Admin and Settings page

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2712]
## Tell us about the problem you're trying to solve
I don't have data to back it but I foresee that it will be confusing what is settings and what is admin

![image](https://user-images.githubusercontent.com/1154337/113375733-e67d2900-9324-11eb-8564-43f7a971d087.png)

## Describe the solution you’d like
We could:

* rename Admin to something more connector specific
* move the import/export to settings
* not sure what to do with logs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368099067258) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Suggestion of new name for Admin: Config?
But happy to merge Settings and Admin, I do think it makes sense.

**Comment by michel-tricot** [comment]
I wonder if everything related to connectors should be called catalog instead

and the rest in settings

**Comment by jrhizor** [comment]
Catalog is also overloaded...

Maybe `Connectors` and `Settings`/`Admin`?

**Comment by johnlafleur** [comment]
What about an approach like this? https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=24453%3A1365

**Comment by jrhizor** [comment]
💯  perfect

**Comment by michel-tricot** [comment]
Yes, I like it way better!

**Comment by michel-tricot** [comment]
It solves one problem I had with the previous UI: Source & Destination where not that visible at the top. now it is super clear!

**Comment by johnlafleur** [comment]
Ok finalized a full version. Let me know if you see any changes to do

**Comment by johnlafleur** [comment]
If Artem doesn't have much on his plate, this could be a frontend only issue to do. @cgardens

**Comment by cgardens** [comment]
@Jamakase this one is ready to go.

Providing zoomed in link to mock ups. https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=24453%3A748
