### ISSUE TITLE
Source Shopify: api version needs to be upgraded

### ISSUE THREAD

**Issue by ynorenko** [airbytehq/airbyte#27121]
### Topic

Shopify source

### Revelant information

I see that source_shopify source.py currently uses api_version = "2022-10" which needs to be upgraded to 2023-04 or later.
There is a warning on shopify website stating that calls to deprecated apis are being made and it needs to be updated to version 2023-04 or later by UPDATE DEADLINE: JAN 1, 2024. 
From shopify:
The gateway, payment_details, and processing_method fields on the Order resource have been removed.
The `orders/transactions.json` REST endpoint, and the `transactions` GraphQL connection provide correct information per transaction set. View change

**Comment by ynorenko** [comment]
Hello, could you please address this issue? Thank you.

**Comment by ynorenko** [comment]
Do you have an estimate when this will be upgraded? Thank you!

**Comment by bazarnov** [comment]
Closing this as duplicate on behalf of : https://github.com/airbytehq/airbyte/issues/28127
