### ISSUE TITLE
source-file: abusive debug log outputs

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27128]
### Connector Name

source-file

### Connector Version

0.3.9

### What step the error happened?

Other

### Revelant information

When running integration tests the source-file connector outputs a lot of logs like:
```
{"type": "DEBUG", "message": "{'uri': 's3://aws_access_key_id:aws_secret_access_key@my_bucket/my_key', 'mode': 'r', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None}", "data": {}}
```

It can potentially leak secrets.

### Contribute

- [ ] Yes, I want to contribute

**Comment by lazebnyi** [comment]
When working with source files, we utilize the "open()" method from the smart open library to open files - [here](https://github.com/airbytehq/airbyte/blob/9335a4d5101dd5ebecdb5f73781510d4737ff4fa/airbyte-integrations/connectors/source-file/source_file/client.py#L234). However, this method also logs local variables before opening the file - [here](https://github.com/RaRe-Technologies/smart_open/blob/7ab4dda19a34014199cba13fdfaa0794a071adad/smart_open/s3.py#L283) and [here](https://github.com/RaRe-Technologies/smart_open/blob/7ab4dda19a34014199cba13fdfaa0794a071adad/smart_open/smart_open_lib.py#L166). Simultaneously, we employ the pyproject.toml configuration file with the debug log level enabled to execute our unit/coverage/integration tests - [here](https://github.com/airbytehq/airbyte/blob/9335a4d5101dd5ebecdb5f73781510d4737ff4fa/pyproject.toml#L85). As a result, all the arguments passed to the "open()" method will be displayed in the output.

Possible solution: To ensure that our credentials are not exposed, we need to run all public view tests without debug mode.
