### ISSUE TITLE
Source Salesforce: Missing records in Salesforce incremental synchronization

### ISSUE THREAD

**Issue by Nakachi-S** [airbytehq/airbyte#27146]
### Connector Name

Salesforce

### Connector Version

2.0.12

### What step the error happened?

During the sync

### Revelant information

I am currently working with a Salesforce Contact table.
The synchronization method is Incremental Sync - Deduped History

The Contact table is heavily updated and pulls in tens of thousands of records daily.
So I found that some records are missing.

1. Synchronization started on 2023-05-28 21:00:00 (State is {SystemModstamp": "2023-05-27T21:15:08.000+0000} at this time)
2. after synchronization, State is updated to {“SystemModstamp”: “2023-05-28T21:10:08.000+0000”}.
3. next synchronization, it was found that a few records were missing, records for which SystemModstamp had the following values: {“SystemModstamp”: “2023-05-28T21:10:08.000+0000”}.(I checked the raw table)
  - 2023-05-28 21:15:07 UTC
  - 2023-05-28 21:15:06 UTC

I can see why it is missing because the value of SystemModstamp, which is indeed a curl field, is the value after that at step2.
This is probably a bug on the Salesforce side.
There is a maximum value of cursor filed that can be obtained from the API requested at a given point in time.
It seems that for missing records, the cursor filed is updated below that maximum value.

A similar problem seems to have been faced by Insightly.
(This was shared with me by kapa.ai. [here](https://airbytehq.slack.com/archives/C021JANJ6TY/p1685614165798229?thread_ts=1685614100.623989&cid=C021JANJ6TY))

[Insightly source changelog](https://docs.airbyte.com/integrations/sources/insightly/#changelog) seems to have a inclusive cursor filed.
However, looking at the recent [Salesforce changelog](https://docs.airbyte.com/integrations/sources/salesforce/#changelog), I am concerned that the optimization has been done to eliminate duplicates and that doing this would be the opposite of an improvement.

How can this be resolved?

### Contribute

- [ ] Yes, I want to contribute

**Comment by erica-airbyte** [comment]
@Nakachi-S there was an update to the connector in the last couple weeks that we believe might have fixed this issue but have not been able to confirm. If you update to version 2.1.0, are you still seeing this issue?

**Comment by tdebroc** [comment]
I have the same problem with 2.1.0
There is still a lot of missing records.

I can't rollback on 2.0.5, because I have Timeout (issue here https://github.com/airbytehq/airbyte/issues/27969)
So I need the evolution with stream_slices and the variable STREAM_SLICE_STEP that arrives in new versions.

**Comment by wwfch-cyrill** [comment]
We can confirm this issue with >=2.0.10. Downgrading to 2.0.9 solves the issue for us. We suspect that the regression was introduced in 2.0.10.

**Comment by artem1205** [comment]
Please, check the latest version: `2.1.2`

**Comment by wwfch-cyrill** [comment]
> Please, check the latest version: `2.1.2`
@artem1205 Could you link the change/ commits please that fix the issue?

**Comment by tdebroc** [comment]
Hello the fix for 2.1.X fix this issue for us (we tested with a volumetrie of 90 Million of lines and no missing records). IMO, we can close the ticket
