### ISSUE TITLE
Sandbox Account for Source Klaus

### ISSUE THREAD

**Issue by sajarin** [airbytehq/airbyte#27160]
Need a sandbox account to run tests for https://github.com/airbytehq/airbyte/pull/27058

**Comment by sajarin** [comment]
Hey @igrankova can I also get you to look at this if possible. Would really appreciate any assistance!

**Comment by marcosmarxm** [comment]
@igrankova can we get crdentials for Klaus API?

**Comment by igrankova** [comment]
@sajarin , @marcosmarxm 
Please see the account and Token in the Lastpass: Klaus API Free Trial Account
Token screen: https://kibbles.klausapp.com/settings/connections
Token name: Airbyte
AI Suite (Trial) Expires in 14 days from 15.06.2023, €38 per user / month after trial period

**Comment by sajarin** [comment]
Thank you @igrankova!
