### ISSUE TITLE
The connection tests failed.....HTTP error 403: forbidden

### ISSUE THREAD

**Issue by rajatariya21** [airbytehq/airbyte#2716]
Try to create setup the source with Exchange Rate connector but it shows "the connection tests  failed.
![airbyte error](https://user-images.githubusercontent.com/81608796/113392688-24289300-93b3-11eb-84d4-2d6f337d7838.jpg)

If anyone knows the solution for this issue, please tell us the solution.

**Comment by michel-tricot** [comment]
Hi @rajatariya21! I am able to reproduce. I wonder if there was a change with the external service.

**Comment by jrhizor** [comment]
The connection tests for the exchange rates api simply make a request to https://api.exchangeratesapi.io/ and it looks like they changed the behavior.

**Comment by jrhizor** [comment]
@rajatariya21 If you upgrade the source version to `0.2.2` in the Admin page of the UI it should work now.

**Comment by rajatariya21** [comment]
> @rajatariya21 If you upgrade the source version to `0.2.2` in the Admin page of the UI it should work now.

Thanks jrhizor. I upgraded the source version. Now able to setup successfully.

And thanks all of your for your help.
