### ISSUE TITLE
Source Google Ads: expand stream Cutomer (account_performance)

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#27188]
### What area the feature impact?

Connectors

### Revelant Information

https://developers.google.com/google-ads/api/fields/v14/customer
Add this device dimension to stream:  https://developers.google.com/google-ads/api/fields/v14/customer#segments.device

**Comment by bazarnov** [comment]
As far as I can see, this stream already has the `segments.device` dimension added to the schema, thus the stream itself, based on the connector logic of managing the fields for the target stream.

https://github.com/airbytehq/airbyte/blob/a924142791404405233fa8dd699b7a7860814a85/airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/account_performance_report.json#L108C1-L110C7

@lazebnyi @ycherniaiev 

Correct me if I'm wrong, please.
