### ISSUE TITLE
Source Google Ads: expand new stream keyword_view

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#27185]
### What area the feature impact?

Connectors

### Revelant Information

Expand stream with new dimensions and metrics: https://developers.google.com/google-ads/api/fields/v13/keyword_view
Metrics:
- [x] active_view_impressions
- [x] active_view_measurability
- [x] active_view_measurable_cost_micros
- [x] active_view_measurable_impressions
- [x] active_view_viewability
- [x] conversions
- [x] conversion_value
- [x] interactions
- [x] interactions_event_types
- [x] view_through_conversions

Dimensions:
- [ ] device
- [ ] ad_network_type

**Comment by artem1205** [comment]
~~Dimensions~~ Segments:
- [ ] device
- [ ] ad_network_type

Can not be added due to conflict with `metric.historical_quality_score`
