### ISSUE TITLE
Link that looks like a Button

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#27203]
We have a Button variant "link" that makes a button that looks like a link.

We also have at least a few places where we are rendering a <Link /> or <ExternalLink /> and applying the button styles directly by forwarding the stylesheet.  

Let's make a "button that is actually a link" option.

It should probably:
- be able to use any Button variant
- be able to be leverage ExternalLink or Link

**Comment by josephkmh** [comment]
we have another issue open for this here: https://github.com/airbytehq/airbyte/issues/23206

closing in favor of that one!
