### ISSUE TITLE
Replace existing "clock" icon with a clearer "clock" icon

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27227]
We have some user feedback the existing "clock" icon is too close to an "L", which causes user confusion around if that means something. We can replace this with a different clock icon that looks more like "4 o'clock" than "3 o'clock". 

Example from internal workspace: 
![Screenshot 2023-06-09 at 4 53 22 PM](https://github.com/airbytehq/airbyte/assets/38087517/e814c683-85cc-4473-b244-3d28f39f7a1d)

Slack thread: https://airbytehq-team.slack.com/archives/C04JRD0BY4B/p1686248244281449

cc @chandlerprall

**Comment by PunitBasarkod** [comment]
can i work on this issue
