### ISSUE TITLE
Slack notification issue since update to 0.5.1

### ISSUE THREAD

**Issue by bjm1244** [airbytehq/airbyte#27228]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.5.1

### What step the error happened?

During the Sync

### Revelant information

After updating Airbyte to 0.5.1, I set the notification to come to Slack if connector sink fails or succeeds, but the test is successful, but it will not be sent to Slack after success when I actually do connection sink. Please check if it's a bug.

**Comment by zubairov** [comment]
I can confirm that we don't see any notifications too

**Comment by josephkmh** [comment]
Could you let me know what version you were on previously, before you upgraded to 0.50.X?

**Comment by bjm1244** [comment]
@josephkmh I updated v0.44.12 to v0.50.1 to v0.50.4, but the same problem occurs.

**Comment by josephkmh** [comment]
Please upgrade to the latest release, v0.50.5. a bug has been fixed in this release that should resolve this issue.

**Comment by bjm1244** [comment]
@josephkmh I updated it and it's resolved. Thank you!
