### ISSUE TITLE
rename "streams" to "configured_streams" in AirbyteConfiguredCatalog

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2724]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368099196094) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
This is done. See https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L250.
