### ISSUE TITLE
Create a new Sync workflow

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#27246]
In Order to fix https://github.com/airbytehq/oncall/issues/1734, we need to create a new sync workflow.

Compare to the existing workflow, it will need to regenerate the thesync input within the sync workflow instead of doing it in the ConnectionManagerWorkflow. This will put us in a transition step where we have 2 sync workflows running instead of one.

**Comment by davinchia** [comment]
We'll revisit this with Workflow 2.0 initiative.
