### ISSUE TITLE
improve table/column selection UX

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2727]
From [a user on Slack](https://airbytehq.slack.com/archives/C019WJFR1JT/p1617247091057300):

1. Sort Columns Alphabetically within a stream
1. Figure out a better way to display long Table and Column names.
1. Search for Column names would be nice.
1. The Manual selection UI is really slow to respond when you have a large collection of tables (40 tables / 15 columns).

From my perspective, 1), 2), and 4) are necessary. 3 is just a nice to have.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368222791954) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
* For 2 I would suggest we add tooltips. In other words, if you hover over it for a second or so you can see the full thing
* Unless 3 is easy, let's skip it. 
* 4 may be the same issue as https://github.com/airbytehq/airbyte/issues/2132

**Comment by Jamakase** [comment]
- 2 is already addressed in master.
- 3 needs some clarification how we actually see it. I would prefer to have a separate task for it.
- 4 is indeed a duplicate
