### ISSUE TITLE
run-ab-platform.sh installation script fails because it is improperly referencing docker-compose

### ISSUE THREAD

**Issue by wonkyto** [airbytehq/airbyte#27296]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.1

### What step the error happened?

On deploy

### Revelant information

On line https://github.com/airbytehq/airbyte/blob/master/run-ab-platform.sh#L143 an attempt to retrieve the version of docker compose is made using  `docker compose version` where it should be `docker-compose version`.

Because of this error, it is not possible to run the this script and the installation fails. 

Changing from `docker compose version` to `docker-compose version` fixes the script.

Thanks.

### Relevant log output

```shell
$ ./run-ab-platform.sh -b

 █████╗ ██╗██████╗ ██████╗ ██╗   ██╗████████╗███████╗
██╔══██╗██║██╔══██╗██╔══██╗╚██╗ ██╔╝╚══██╔══╝██╔════╝
███████║██║██████╔╝██████╔╝ ╚████╔╝    ██║   █████╗
██╔══██║██║██╔══██╗██╔══██╗  ╚██╔╝     ██║   ██╔══╝
██║  ██║██║██║  ██║██████╔╝   ██║      ██║   ███████╗
╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝    ╚═╝      ╚═╝   ╚══════╝
                                            Move Data

docker compose v2 not found! please install docker compose!
```

**Comment by marcosmarxm** [comment]
You're using a old version of Docker. Please upgrade to v2 as the error message says: 
`docker compose v2 not found! please install docker compose!`
