### ISSUE TITLE
connectors-ci: automatic code formatting

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27314]
We should expose a `format` command like to format the connector code:
`airbyte-ci connectors format` 

Local execution behavior:
* The formatted code is exported back the local airbyte repo

CI execution behavior:
* The formatted code is committed and pushed to the current branch
* The formatting job should run in the same GHA workflow as tests but in a different and upstream step.
* If tests locally have the formatted code commit the commit message can skip CI by using the `[skip ci]` commit message prefix.

For Python connectors the code will be formatted with `black` and `isort` 
For Java connectors the code will be formatted with `./gradlew format`
We also add the copyright header to the connector code if missing.

Code formatting happens at the connector level.
The modified files should only belong to the connector code, not to other project.

**Comment by alafanechere** [comment]
Re-opening because we had to disable auto format. Especially because Java formatter was removing code while formatting... See https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1687370336899669

**Comment by bnchrch** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/31247
