### ISSUE TITLE
Bug: speedy first connection banner link and missing Orb increment

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27324]
We have a banner in the Cloud app that shows up when a user first signs up (get 100 additional credits if you activate within 24h). I noticed two things with this banner:

1) The link no longer works and redirects to an "oops" page
2) The call to Orb to increment the workspace with 100 credits does not work any longer.  Tested with this workspace ID: 1e964b50-9856-4db1-a02c-df266b6f3dbb. My understanding of how this is done is through Segment fired as a function of the Connection.Create event.

**Comment by tealjulia** [comment]
[Relevant Segment action](https://app.segment.com/airbyte/destinations/next-js-api_z6mahble/sources/airbyte_ui_cloud/instances/634013eccfc9f47a63c00987/delivery-overview?endTime=1686679776516&isLive=false&showMetricsAs=percentage&startTime=1685470176516).  It looks like that call to /add_trial_credits has about the same success rate in the past 24 hours as it does in the past 2 weeks.

**Comment by tealjulia** [comment]
Bug is [in this line](https://github.com/airbytehq/airbyte-web-experiments/blob/aa3edce57da8843a72f942af2235d29489ec9478/pages/api/add_trial_credits/index.ts#L90) and an action item has been added for Leti to look into a fix

**Comment by josephkmh** [comment]
Closing as this has been fixed
