### ISSUE TITLE
Bug: asked to confirm discard changes when selecting destination

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27326]
In the new connection flow, a user will be prompted with the "Discard changes"  modal even though they are going through the setup experience. This shouldn't be showing up and I believe it's a bug, as the user isn't asked to do this when setting up a source.

Steps to reproduce:
- Create source
- Select the existing source
- Create destination
- Select the existing destination
- Modal pops up

<img width="729" alt="Screenshot 2023-06-13 at 10 27 51 AM" src="https://github.com/airbytehq/airbyte/assets/38087517/459a4ab4-702e-4466-a49c-5f7bbcbb4d8f">
cc @tealjulia

**Comment by tealjulia** [comment]
@nataliekwong do you have a loom?  I tried following what you explained to reproduce, but I'm missing something.
You shouldn't have to select the source you're creating during the new workflow. 🤔

**Comment by nataliekwong** [comment]
Yep, here you go! https://www.loom.com/share/e3e69eb2930e431fa9389ddd08ecc8fa

I went through it again, but this time it did indeed auto-advance me to use the existing source, so I must have just clicked it in impatience earlier.

It looks like as soon as I select a destination, it serves the modal.

**Comment by tealjulia** [comment]
No that's super wrong, you shouldn't even get sent back to that page before the redirect!  Taking a look.

**Comment by nataliekwong** [comment]
Thank you @tealjulia !!
