### ISSUE TITLE
Update Launch Darkly overrides to use Registry Entry Cache

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27333]
## Overview
When we apply a LD connector override we should get the actor definition data from

https://connectors.airbyte.com/files/metadata/<DOCKER-IMAGE>/<VERSION>/<PLATFORM>.json

For example

https://connectors.airbyte.com/files/metadata/airbyte/destination-bigquery/1.2.19/cloud.json

## Extra things to consider
1. We should error LOUDLY when not found
2. but We should continue to run with the default when not found

**Comment by evantahler** [comment]
Split into 2 PRs
* new RDP functionality + refactoring (oss catalog)
* use the RDP
