### ISSUE TITLE
Destination Big Query Denormalized: Shopify products stream has missing values in variants array

### ISSUE THREAD

**Issue by loris** [airbytehq/airbyte#27349]
### Connector Name

source-shopify

### Connector Version

0.3.4

### What step the error happened?

During the sync

### Revelant information

We face a strange behavior when syncing some Shopify streams to BQ using the bigquery-denormalized destination connector in Airbyte Cloud:

The `products` stream is supposed to have a property `variants` which is an array of objects with multiple properties. When looking at the result in the BQ raw tables, those properties are set but most of them are `null` except the ones which are typed as number in the json schema (`price` and `compare_at_price`):

```
[{
    "presentment_prices": [],
    "inventory_management": null,
    "requires_shipping": null,
    "old_inventory_quantity": null,
    "created_at": null,
    "title": null,
    "updated_at": null,
    "inventory_item_id": null,
    "price": "16.0",
    "option3": null,
    "option1": null,
    "id": null,
    "option2": null,
    "sku": null,
    "grams": null,
    "barcode": null,
    "inventory_quantity": null,
    "compare_at_price": "16.0",
    "taxable": null,
    "fulfillment_service": null,
    "weight": null,
    "inventory_policy": null,
    "tax_code": null,
    "weight_unit": null,
    "admin_graphql_api_id": null,
    "position": null,
    "image_id": null
}]
```

- The properties seem correctly defined in the [products.json schema](https://github.com/airbytehq/airbyte/blob/6879cdf5d6284fa5b77c8bf9b198287468dd7106/airbyte-integrations/connectors/source-shopify/source_shopify/schemas/products.json#L153-153)
- We don't have the issue with the same source and destination connectors on other streams where we have the same kind of array of objects structure (for instance `customer.addresses` or `order.line_items` where all properties are properly synced)
- The issue (missing values) is already present in the avro files staged in GCS

We are not sure were to look at. Any help would be appreciated.

### Contribute

- [X] Yes, I want to contribute

**Comment by loris** [comment]
@sh4sh Can you tag this issue as `connectors/destination/bigquery-denormalized`. After doing some more checks, it looks like `source/shopify` is emitting the correct stream values. It looks like the issue is in the way the destination connector load/transform the data

**Comment by loris** [comment]
@bazarnov sorry to hit you up on this one, but I have no clue. As you are the main contributor on the Shopify connector I’m wondering if you had some hints? I’m still not sure the issue has something to do with the Shopify or BQ-denormalized connector.

**Comment by bazarnov** [comment]
@edgao Could you please advice here?

@loris 
- please send the examples for both working and non-working array?
- do you use both product_graph_ql and product streams at the same time? did you tried only 1 at a time?

**Comment by evantahler** [comment]
Hi @loris - `destination-bigquery-denormalized` is going away soon, and will be replaced by regular `destination-bigquery`, once our new [destination format](https://github.com/airbytehq/airbyte/issues/26028) has landed.  Are you able to switch to the regular `destination-bigquery`?

**Comment by loris** [comment]
Hi @evantahler Good news the Destination v2 is going ahead and will probably fix this issue.
We will be able to switch to the main destination, but we don’t know how long it will take to migrate our existing connections. It depends on how different the schema will be from actual bigquery-denormalized (my understanding is that the main difference is that nested records will be formatted as JSON string instead of STRUCT records, right?).
We filled in the V2 destination beta form a while back but did not hear back yet. It could be great to test the new BQ v2 destination on Shopify schema soon to start migrating.

Thanks

**Comment by loris** [comment]
@bazarnov Thanks for looking into it. As @evantahler said, maybe we should not try to fix the issue if we are sure the issue is related to `destination-bigquery-denormalized` which will be deprecated.
Anyway, to answer your question:

- Yes sure, inside the `products` stream, here are two array of objects:
  - `options` is being synced as expected, all nested fields are properly filled
  - `variants` is the one having issue, all nested fields have a `null` value inside BQ, except the float values (`compare_at_price` and `price`)
- We don't use the `product_graph_ql` stream. So all my tests were done syncing only the `products` stream.

Here is an example row from the `products` table in BQ (converted to JSON and removed some properties for brevity):

```
[{
  ...
  "created_at": "2023-01-09 17:49:50.000000 UTC",
  "variants": [{
    "presentment_prices": [],
    "inventory_management": null,
    "requires_shipping": null,
    "old_inventory_quantity": null,
    "created_at": null,
    "title": null,
    "updated_at": null,
    "inventory_item_id": null,
    "price": "12.0",
    "option3": null,
    "option1": null,
    "id": null,
    "option2": null,
    "sku": null,
    "grams": null,
    "barcode": null,
    "inventory_quantity": null,
    "compare_at_price": "20.0",
    "taxable": null,
    "fulfillment_service": null,
    "weight": null,
    "inventory_policy": null,
    "tax_code": null,
    "weight_unit": null,
    "admin_graphql_api_id": null,
    "position": null,
    "image_id": null
  }, {
    "presentment_prices": [],
    "inventory_management": null,
    "requires_shipping": null,
    "old_inventory_quantity": null,
    "created_at": null,
    "title": null,
    "updated_at": null,
    "inventory_item_id": null,
    "price": "12.0",
    "option3": null,
    "option1": null,
    "id": null,
    "option2": null,
    "sku": null,
    "grams": null,
    "barcode": null,
    "inventory_quantity": null,
    "compare_at_price": "20.0",
    "taxable": null,
    "fulfillment_service": null,
    "weight": null,
    "inventory_policy": null,
    "tax_code": null,
    "weight_unit": null,
    "admin_graphql_api_id": null,
    "position": null,
    "image_id": null
  }],
  ...
  "options": [{
    "values": ["40", "42", "44", "46", "48"],
    "product_id": "7572076658866",
    "name": "Taille",
    "id": "9730737406130",
    "position": "1"
  }],
  "id": "7572076658866",
  "published_at": "2023-01-09 17:49:50.000000 UTC",
  "status": "active",
  "_airbyte_ab_id": "b9223fba-91e3-43fe-a662-16ff95c0e085",
  "_airbyte_emitted_at": "2023-06-23 16:33:30.055000 UTC"
}]
```

**Comment by bazarnov** [comment]
@loris Please try the `destination-bigquery` instead, sync only 1 stream, and provide us with the result. Thank you.

**Comment by loris** [comment]
> @sh4sh Can you tag this issue as `connectors/destination/bigquery-denormalized`. After doing some more checks, it looks like `source/shopify` is emitting the correct stream values. It looks like the issue is in the way the destination connector load/transform the data

@bazarnov as stated above, the issue is `destination-bigquery-denormalized` only. We don't have any issue with the `destination-bigquery` destination, the `variants` field is synced as expected (but of course, is a JSON string, instead of denormalized Struct record like we expect from `destination-bigquery-denormalized`)

**Comment by loris** [comment]
I'm closing the issue as we switched to `destination-bigquery `v2 (with `use_1s1t_format=true`), thanks!
