### ISSUE TITLE
Ability to kickoff one stream at a time (per-stream syncs)

### ISSUE THREAD

**Issue by nicklubbers** [airbytehq/airbyte#27354]
### What area the feature impact?

Connectors

### Revelant Information

I would love to be able to kickoff one stream (or a subselection of streams) instead of all streams. Currently, if I reset one stream, then I am only able to starts all streams of a connection while I only need to re-sync that one stream.

**Comment by nataliekwong** [comment]
I will close this issue in favor of this similar one: https://github.com/airbytehq/airbyte/issues/23067, as the other was created earlier. We will keep this feature in scope for our future roadmap!
