### ISSUE TITLE
Source Shopify: incorrect cursor state for metafields streams

### ISSUE THREAD

**Issue by loris** [airbytehq/airbyte#27355]
### Connector Name

source-shopify

### Connector Version

0.3.4

### What step the error happened?

During the sync

### Revelant information

We found out an issue when triggering incremental sync on a Shopify to BQ connection, with the following basic streams:
- `customers`
- `metafield_customers`

Each incremental sync correctly fetched a few number of `customers` (the ones created or updated since the last sync), but fetched way too many `metafield_customers`. After looking at the connection state, it looks like the timestamp stored for the `metafield_customers` stream is incorrect:  

```
[
  {
    "streamDescriptor": {
      "name": "customers"
    },
    "streamState": {
      "updated_at": "2023-06-14T09:40:41+02:00"
    }
  },
  {
    "streamDescriptor": {
      "name": "metafield_customers"
    },
    "streamState": {
      "customers": {
        "updated_at": "2023-03-30T05:32:13+02:00"
      },
      "updated_at": "2021-09-01T17:57:41+02:00"
    }
  }
]
```

Maybe I don't understand how the state is used for child stream, but IMO we should have the same `updated_at` values in the `customers` object (both parent and at the metafields level).
Actually, given the way metafields work at Shopify, i'm wondering why there are any state persisted for `metafields` stream. The connector logic should basically be: sync newly created or updated `customers` (based on the `updated_at` state of the `customers` stream), and then for each fetched `customers` entry, go fetch the associated `customer_metafields`.

### Contribute

- [X] Yes, I want to contribute

**Comment by bazarnov** [comment]
According to this research: https://github.com/airbytehq/airbyte/pull/17962#issuecomment-1679367740 the cursor values are correct, @loris if you have any objections, fell free to comment back, otherwise, I'd close this issue within 2 days.
