### ISSUE TITLE
Add pagination or lazy loading to the connections UI

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#27364]
### What area the feature impact?

Frontend / airbyte-webapp

### Revelant Information

When there are a lot of connections set up, loading the full list can take a very long time and cause performance degradation.

It would be awesome if the list of connections could be loaded in chunks, maybe through pagination or lazy loading.

**Comment by josephkmh** [comment]
@chandlerprall is looking into this!

**Comment by tealjulia** [comment]
Refining note:
- sort the rows by something
- maybe virtualizing this is a better call than pagination
- moving to the backlog for now

**Comment by nataliekwong** [comment]
@alex-gron Tagging you here since you shared feeling the pain on this. It also came up today during the Compose planning.

**Comment by nataliekwong** [comment]
I believe there's an effort to migrate some parts of this page to micronaut, which means we can't touch it until that is done? ( please chime in if I'm mistaken!)

I created a [query](https://airbyte.metabaseapp.com/question/8235-adhoc-active-workspaces-with-high-number-of-connections) that shows how many other workspaces are facing at least a similarly high issue as our own internal workspace. The two groups shown are how many workspaces have as many or more connections as our internal workspaces or have less connections. I don't have a great alternative way to figure out blast radius other than to use our own workspace as an example.

**Comment by josephkmh** [comment]
To add a little more data here, I used this query in datadog: `service:airbyte-server env:prod operation_name:netty.request resource_name:"POST /api/v1/web_backend/connections/list"`

To pull data on loading time by percentiles:
- 90th percentile: 800ms
- 95th percentile: 1.5 seconds
- 99th percentile: 7 seconds

So only about 10% of requests to the connections list endpoint are what I would call "super slow". Unfortunately datadog doesn't have data about workspace IDs, so I can't see what percent of actual workspaces are slow, just of total requests.

**Comment by luiz-cesa** [comment]
Hello friends, any news on this?

**Comment by chandlerprall** [comment]
Looking at averages, the trend for `POST /api/v1/web_backend/connections/list` has continued to go down. Datadog's [APM traces](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aprod%20service%3Aairbyte-server%20resource_name%3A%2APOST%5C%20%5C%2Fapi%5C%2Fv1%5C%2Fweb_backend%5C%2Fconnections%5C%2Flist%2A%20&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&sort_by=%40duration&sort_order=desc&spanType=service-entry&spanViewType=databases&traceQuery=&view=spans&start=1707234551830&end=1707407351830&paused=false) for that endpoint appear to flag 2 SQL queries that can spike quite a bit and can be looked into. I don't think we get specific workspace IDs from those traces though, which could make them harder to optimize.

**Comment by cesar-loadsmart** [comment]
Hey folks, any news on this topic? 

Airbyte landing page is basically not functional for us.

**Comment by cesar-loadsmart** [comment]
Hey @josephkmh we run Airbyte Open Source. We have around 102 Active connections, some of them run on short intervals, so our `jobs` table has ~800K records. Every time we load the Airbyte landing page we can see our Postgres database struggling, even though queries continue to run within a reasonable time in the database.

**Comment by ericsalesdeandrade** [comment]
We have around 2500 connections and the UI is practically unusable. 

It's because we've made a connection for every table in the database as we found it hard to club together streams in a single connection due to the high variability of table size / # of rows, causing sync failures. If anyone has any advice for me that would be greatly appreciated. Thanks a lot :)

**Comment by pai911** [comment]
For our company, if we're gonna adopt Airbyte fully, this is a must-fix issue.
Per Airbyte's design, it's normal to have a large number of connections.

Like right now, we want to use Airbyte to track 7000+ hashtags on a social platform, but the fear of this large number will render the UI useless stopped us.

**Comment by chandlerprall** [comment]
We have now taken multiple passes at UI performance issues for the connections list including optimizing DOM, improved response to user actions on the page, and a couple days ago enabled table virtualization.

I'm going to let this sit for a couple days and then check metrics again. My expectation is we will see improved performance on the page, with some spikes still coming from API response times, and we can re-asses those endpoints without a ton of extra noise introduced by the UI.

**Comment by dizel852** [comment]
@chandlerprall it seems like this one can be closed, right?

**Comment by chandlerprall** [comment]
The numbers look much better overall

* 75th percentile of timings to load&show the connections table is pretty good
* 95th percentile is reasonable
* long tail 5% shows loading this view can still be occasionally terrible, but the worst spikes appear to me to be transient

I want to do a little more digging on the API side before closing, to have a better understanding of that side of the story
