### ISSUE TITLE
[API] add `PATCH sources/{sourceId}` endpoint to update source partially

### ISSUE THREAD

**Issue by bibimorlet** [airbytehq/airbyte#27366]
### Topic

Airbyte Configuration API

### Revelant information

In the API, there is already an `POST /v1/sources/update` endpoint in order to FULLY update a source.

It would be great to have a `PATCH /v1/sources/{sourceId}` (or something like that) in order to PARTIALLY update a source. 
I believe there is and endpoint like this on the Airbyte API for Airbyte Cloud (see [here](https://reference.airbyte.com/reference/patchsource))

**Comment by pmossman** [comment]
We don't support the Airbyte Configuration API for direct external use. The Airbyte API can be called in OSS as well as Cloud, so that should cover your use case. Let us know if that isn't the case
