### ISSUE TITLE
don't allow using the source namespace if the source doesn't have a namespace

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#27380]
It seems odd that we allow users to configure their namespaces to use the source namespace option for sources that don't have that concept.  

We currently follow the backend's fallback logic for this for displaying the configured destination namespace:
- if there isn't a source namespace, then we use `""` anywhere the placeholder `${SOURCE_NAMESPACE}` is
- if that means the namespace string ends up completely empty, we fall back to `<destination namespace>`

**Comment by josephkmh** [comment]
Refining notes:
- We should remove the `Mirror source namespace` option and indicate why it's disabled with a tooltip

**Comment by tealjulia** [comment]
Hmm.  Didn't consider this until I started into it... how should we handle the (MANY) connections that already have this option selected 😅.  

My thinking is that we should then default them to `destination default` (for new and existing connections) as that is (a) the path of least choices for the user and (b) the behavior the platform does under the hood anyways.
