### ISSUE TITLE
Source Mailgun: Invalid Date Field Validation on `start_date`

### ISSUE THREAD

**Issue by padala** [airbytehq/airbyte#27385]
### Connector Name

source-mailgun

### Connector Version

0.1.1

### What step the error happened?

Configuring a new connector

### Revelant information

Conflicting pattern & format on `start_date` for the mailgun connector because of which the user is unable to enter the start date.
Currently, the pattern is `"pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$",` which accepts input as `2020-10-01 00:00:00` but the format `"format": "date-time"` needs the pattern as `"pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$",`  which accepts input as `2021-03-01T00:00:00Z`.

Reference image:
<img width="667" alt="Screenshot 2023-06-14 at 1 20 29 AM" src="https://github.com/airbytehq/airbyte/assets/4698090/e9f3e54c-fbc0-436f-97a6-46c388ad4175">

Updating the pattern & its usage should fix the issue.

### Contribute

- [ ] Yes, I want to contribute

**Comment by btkcodedev** [comment]
@jrolom I would like to take this issue

**Comment by btkcodedev** [comment]
@marcosmarxm Issue was fixed while migration ref - https://github.com/airbytehq/airbyte/pull/29122
