### ISSUE TITLE
Airbyte UI: Update Syncing Status on Connection Page

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#27405]
### What area the feature impact?

Airbyte Platform

### Revelant Information

The Airbyte UI shows plaintext `Syncing...` on the Connection Page when a sync is running 
This doesn't really match the the rest of the UI styling

Discussed with @chandlerprall  that we should probably change this to be the `button-with-spinner state` for the entire duration of the sync (but open to other solutions here)

<img width="1811" alt="Screen Shot 2023-06-14 at 5 34 52 PM" src="https://github.com/airbytehq/airbyte/assets/109167606/deca18b2-de7c-45be-b88e-b0ff53071949">

**Comment by nataliekwong** [comment]
Maybe a good "Small" candidate @josephkmh ?
