### ISSUE TITLE
Connector Test Failure reported as success on failure

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27425]
# Problem
source-firebase-realtime-database was reported as passing in the github comment when it had failed
https://github.com/airbytehq/airbyte/pull/27420
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/b7911f05-5c99-4b25-8256-8169327aa4aa)
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/389f0083-6ee9-49ac-9e32-ef816e456298)

**Comment by evantahler** [comment]
![https://imgflip.com/i/7pzsyc](https://imgflip.com/i/7pzsyc)

**Comment by bnchrch** [comment]
Grooming:
- this is related to @marcosmarxm having a passing test report but failing unit tests: https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1689628075772669
-  the pytest success/failure reporting is a bit brittle because it relies on stdout parsing and not exit code: if "failed" in last_log_line or "errors" in last_log_line: If the stdout structure changes we can have unexpected results.
- This stdout parsing was originally introduced because Dagger raised errors without details when exit code > 0. We made pytest always exit with 0 and rely on stdout parsing to assess success or failure.
This will be solved by upgrading to the latest dagger version, if a with_exec returns a non 0 exit code the error object now has stdout and stderr attribute. 

Also likely a related issue: https://github.com/airbytehq/airbyte/issues/27770

**Comment by alafanechere** [comment]
For the false positive with test results: we need to change how we parse CAT output and transform it to StepResult: replace the use of pytest_logs_to_step_result with `get_step_result` . 
For the false positive without test result: to reproduce you should raise a an unhandled exception inside the pipeline, and I think the report wrongly states a success.

**Comment by bnchrch** [comment]
Grooming
- We want to update the code to use `get_step_result`
- We want to update the reporting in `__aexit__` so on error we can see still see what steps were run and not run
- We want the results of a step to be available to our error reporting even on a hard exit.

**Comment by alafanechere** [comment]
> For the false positive with test results: we need to change how we parse CAT output and transform it to StepResult: replace the use of pytest_logs_to_step_result with get_step_result .
For the false positive without test result: to reproduce you should raise a an unhandled exception inside the pipeline, and I think the report wrongly states a success.

This is addressed in #28767
