### ISSUE TITLE
Remove old sync catalog row code, show new sync catalog by default

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#27435]
Flag was turned on for the new sync catalog row + sync catalog header on June 16.  

After we've determined it's safe to do so, we can:
- remove code references to the flag
- remove old components
- get e2e passing again (since, for instance, the pk/cursor can no longer be configured here, and the namespace column will likely have different content)

**Comment by josephkmh** [comment]
Refining notes:
- There are a few visual bugs to fix before this can be done

**Comment by josephkmh** [comment]
Sorry for the vague comment 🙂 yes I think that was the only change I was referring to
