### ISSUE TITLE
DatetimeBasedCursor: support datetime format that do not sort alphabetically

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#27447]
### What area the feature impact?

None

### Revelant Information

DatetimeBasedCursor should not order alphabetically but using datetime as if the datetime format is something like "%d-%m-%Y", "01-01-2023" is smaller than "20-01-1970"

https://github.com/airbytehq/airbyte/blob/8be753df02cc16bbf3aadb311e603aca0cb796d8/airbyte-cdk/python/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py#L114
https://github.com/airbytehq/airbyte/blob/8be753df02cc16bbf3aadb311e603aca0cb796d8/airbyte-cdk/python/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py#L120

**Comment by girarda** [comment]
alternative solution: always store the cursor as ISO 8601

**Comment by maxi297** [comment]
Closed as part of https://github.com/airbytehq/airbyte/pull/27475
