### ISSUE TITLE
Quickbooks authentication broken on content-type header

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#27461]
### What area the feature impact?

None

### Revelant Information

It seems like https://github.com/airbytehq/airbyte/pull/27225/files broke authentication for the quickbooks connector.

Even though the request body is encoded as json, the API rejects it with a
```
415 Client Error: Unsupported Media Type for url: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer - Traceback (most recent call last):
```

error

This is not manifesting because the quickbooks connector is not using the most recent version of the CDK yet.

**Comment by flash1293** [comment]
Grooming notes:
* Do a quickfix now to buy some time: Try the request with the content-type header. If it fails with 415, retry without
* Document this in code
* Long term plan: Remove this behavior as soon as there's a generic way to implement the authenticator in the way the API  works

**Comment by girarda** [comment]
We'll revert [the](https://github.com/airbytehq/airbyte/pull/27225/)[https://github.com/airbytehq/airbyte/pull/27225/](https://github.com/airbytehq/airbyte/pull/27225/files) and spike a potential solution before deciding on what hack to introduce since this will affect many GA connectors

**Comment by flash1293** [comment]
we also need to revert https://github.com/airbytehq/airbyte/pull/27350 as these changes go together

**Comment by flash1293** [comment]
Fixed by revert
