### ISSUE TITLE
Source Google Ads: new streams to cover MLP enhancements

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#27477]
### What area the feature impact?

Connectors

## Tell us about the problem you're trying to solve
Following our market research and analysis, we've identified the streams and enhancements that would help make our connectors more competitive as detailed [here](https://docs.google.com/spreadsheets/d/1WbXFcsXghRvmp-O5f6vZ6mogF1Fa5WnN/edit#gid=687471646)

## Describe the solution you’d like
NEW STREAMS:
- [ ] [CallAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/CallAdInfo)
- [ ] [CampaignCriterion](https://developers.google.com/google-ads/api/fields/v13/campaign_criterion)
- [ ] [CustomParameter](https://developers.google.com/google-ads/api/reference/rpc/v13/CustomParameter)
- [ ] [DisplayUploadAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/DisplayUploadAdInfo)
- [ ] [DynamicSearchAdsSetting](https://developers.google.com/google-ads/api/reference/rpc/v13/Campaign.DynamicSearchAdsSetting)
- [ ] [ExpandedDynamicSearchAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ExpandedDynamicSearchAdInfo)
- [ ] [ExpandedTextAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v14/ExpandedTextAdInfo)
- [ ] [GeoTargetConstant](https://developers.google.com/google-ads/api/reference/rpc/v13/GeoTargetConstant)
- [ ] [GeoTargetTypeSetting](https://developers.google.com/google-ads/api/reference/rpc/v13/Campaign.GeoTargetTypeSetting)
- [ ]  [HotelAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v12/HotelAdInfo)
- [ ] [ImageAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ImageAdInfo)
- [ ] [LegacyAppInstallAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v12/LegacyAppInstallAdInfo)
- [ ] [LegacyResponsiveDisplayAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v12/LegacyAppInstallAdInfo)
- [ ] [ListingGroupInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ListingGroupInfo)
- [ ] [LocalAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v14/LocalAdInfo)
- [ ] [NetworkSettings](https://developers.google.com/google-ads/api/reference/rpc/v13/Campaign.NetworkSettings)
- [ ] [OperatingSystemVersionConstant](https://developers.google.com/google-ads/api/reference/rpc/v12/OperatingSystemVersionConstant?hl=en)
- [ ] [PolicyTopicConstraint](https://developers.google.com/google-ads/api/reference/rpc/v13/PolicyTopicConstraint)
- [ ] [PolicyTopicEntry](https://developers.google.com/google-ads/api/reference/rpc/v13/PolicyTopicEntry)
- [ ] [PolicyTopicEvidence](https://developers.google.com/google-ads/api/reference/rpc/v12/PolicyTopicEvidence)
- [ ] [ProximityInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ProximityInfo)
- [ ] [RealTimeBiddingSetting](https://developers.google.com/google-ads/api/reference/rpc/v12/RealTimeBiddingSetting)
- [ ] [ResponsiveDisplayAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ResponsiveDisplayAdInfo)
- [ ] [ResponsiveSearchAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ResponsiveSearchAdInfo)
- [ ] [ShoppingComparisonListingAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ShoppingComparisonListingAdInfo)
- [ ] [ShoppingProductAdInf](https://developers.google.com/google-ads/api/reference/rpc/v13/ShoppingProductAdInfow)
- [ ] [ShoppingSetting](https://developers.google.com/google-ads/api/reference/rpc/v13/Campaign.ShoppingSetting)
- [ ] [ShoppingSmartAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/ShoppingSmartAdInfo)
- [ ]  [SmartCampaignAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v12/SmartCampaignAdInfo)
- [ ] [TargetingSetting](https://developers.google.com/google-ads/api/rest/reference/rest/v13/TargetingSetting?hl=ru)
- [ ] [TextAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/TextAdInfo)
- [ ] [TopicConstant](https://developers.google.com/google-ads/api/reference/rpc/v13/TopicConstant)
- [ ] [TrackingSetting](https://developers.google.com/google-ads/api/reference/rpc/v13/Campaign.TrackingSetting)
- [ ] [VideoAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v13/VideoAdInfo)
- [ ] [VideoResponsiveAdInfo](https://developers.google.com/google-ads/api/reference/rpc/v12/VideoResponsiveAdInfo)

**Comment by sherifnada** [comment]
@ycherniaiev we don't need to cover every last performance report. However we do need to output the following information about the very core assets (account, campaign, adGroup, AdGroupAd):
1. Resource metadata
1. Performance reports 


For example [if you look at Fivetran](https://docs.google.com/presentation/d/1f16zOPxwT1AXoOcNkvwT82ApKqU1yhtJ04f-73M91nw/edit#slide=id.gf947d52420_0_0), any table which ends with _history is a metadata table related to the core resource types:
* Campaign has campaign_bidding_strategy, campaign_budget, campaign_label, campaign_*_setting, etc..
* The same is true for AdGroup and other core resources

**Comment by ycherniaiev** [comment]
@sherifnada core metadata and corresponding reports already I parity![image](https://github.com/airbytehq/airbyte/assets/94798230/1fe32907-0334-4712-ab88-3e99c1296b4e)

**Comment by sherifnada** [comment]
I think we don't sync ad_group performance and metadata fields campaign_bidding_strategy, campaign_budget, campaign_label, campaign_*_setting


see the screenshot linked from the ERD above

**Comment by ycherniaiev** [comment]
Maybe I ve missed something but ad_ group stream in current implementation combines metadata and metrics. But I need check

**Comment by ycherniaiev** [comment]
I see now. Your reasoning makes a lot of sense

**Comment by ycherniaiev** [comment]
But on the other hand I see a lot of confusion. For stream ad_group we have the following Schema:

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "ad_group.ad_rotation_mode": {
      "type": ["null", "string"]
    },
    "ad_group.base_ad_group": {
      "type": ["null", "string"]
    },
    "ad_group.campaign": {
      "type": ["null", "string"]
    },
    "ad_group.cpc_bid_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.cpm_bid_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.cpv_bid_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.display_custom_bid_dimension": {
      "type": ["null", "string"]
    },
    "ad_group.effective_target_cpa_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.effective_target_cpa_source": {
      "type": ["null", "string"]
    },
    "ad_group.effective_target_roas": {
      "type": ["null", "number"]
    },
    "ad_group.effective_target_roas_source": {
      "type": ["null", "string"]
    },
    "ad_group.excluded_parent_asset_field_types": {
      "type": ["null", "array"],
      "items": {
        "type": "string"
      }
    },
    "ad_group.optimized_targeting_enabled": {
      "type": ["null", "boolean"]
    },
    "ad_group.final_url_suffix": {
      "type": ["null", "string"]
    },
    "ad_group.id": {
      "type": ["null", "integer"]
    },
    "ad_group.labels": {
      "type": ["null", "array"],
      "items": {
        "type": "string"
      }
    },
    "ad_group.name": {
      "type": ["null", "string"]
    },
    "ad_group.percent_cpc_bid_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.resource_name": {
      "type": ["null", "string"]
    },
    "ad_group.status": {
      "type": ["null", "string"]
    },
    "ad_group.target_cpa_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.target_cpm_micros": {
      "type": ["null", "integer"]
    },
    "ad_group.target_roas": {
      "type": ["null", "number"]
    },
    "ad_group.targeting_setting.target_restrictions": {
      "type": ["null", "array"],
      "items": {
        "type": "string"
      }
    },
    "ad_group.tracking_url_template": {
      "type": ["null", "string"]
    },
    "ad_group.type": {
      "type": ["null", "string"]
    },
    "ad_group.url_custom_parameters": {
      "type": ["null", "array"],
      "items": {
        "type": "string"
      }
    },
    "segments.date": {
      "type": ["null", "string"],
      "format": "date"
    }
And for me it has a bundle of metrics as well as metadata
@sherifnada

**Comment by sherifnada** [comment]
@davydov-d could you record this information about deprecation in the MLP doc for google ads?

**Comment by davydov-d** [comment]
@sherifnada sure, do you mean google-ads?
