### ISSUE TITLE
Connector builder does not validate schema when pasted in

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#27489]
To reproduce:
1. Create a new customer connector in the builder
2. Copy a test manifest ([example](https://gist.github.com/flash1293/bd75b6a343ff5f70cb224d77ff328b04))
3. Select all in the YAML editor, then paste in the content of the test manifest
4. Observe that the test panel does not update
5. A single keystroke will get the test panel to revalidate and parse the manifest correctly

https://github.com/airbytehq/airbyte/assets/7550957/bbbdd008-62e0-46e0-8af9-f57838e2f99f

**Comment by flash1293** [comment]
This happens only if the following things hold true:
* YAML mode is already selected before the builder is opened
* Connector is fresh from scratch
* Manifest is pasted in without doing any change before
