### ISSUE TITLE
SAT should verify that if PK is set in catalog it is never null for all output records

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2748]
## Tell us about the problem you're trying to solve
Add testing in the _source_ standard tests to verify PK incremental functionality.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368157885506) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@ChristopheDuong, @sherifnada suggested that he have the zazmic team handle this, which I think is a great idea. 

@ChristopheDuong , can you please add to this issue what info they need in order to do this. 

@sherifnada can you review the details chris adds and make sure it's the right level of detail for zazmic to work on it, please?

**Comment by ChristopheDuong** [comment]
The tests on the source side should produce `sourceDefinedPrimaryKeys` that would be filled up in the airbyte protocol for `AirbyteStream` objects (similar to `default_cursor_field` with the exception that you can have multiple/composite primary keys, so a list, but only one cursor field)

**Comment by sherifnada** [comment]
@ChristopheDuong what assertions would the test case be making here? could you describe some test cases?

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong what assertions would the test case be making here? could you describe some test cases?
> 
> if I'm understanding you correctly it's that if the `primarykey` is set in the catalog then the output records should all contain that field?

Ensuring a constraint of records from the source always containing the primary key fields (making sure it is never NULL) could probably be a good thing, yes!

(in the case of cursors, I've seen people asking to support NULL values in the cursor column though)

**Comment by sherifnada** [comment]
We should also just set the PK property as required in JSON schema but that is much higher effort (to backfill on existing connectors) so for now we will do this task and create follow up for other connectors.
