### ISSUE TITLE
Source Amazon Seller Partner: error message for missing AWS credentials is unclear

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#27496]
### Connector Name

amazon-seller-partner

### Connector Version

1.3.0

### What step the error happened?

Configuring a new connector

## Description:
Currently, when specifying only the `role_arn` parameter without providing the `aws_access_key` and `aws_secret_key`, an error is thrown: `NoCredentialsError('Unable to locate credentials')`. While this error indicates that credentials are missing, it would be beneficial to provide a more specific and informative error message.

### Contribute

- [ ] Yes, I want to contribute

**Comment by andreyAtBB** [comment]
I am seeing the same error with the latest connector version 1.5.1 on Airbyte Cloud with authorizing via oAuth:

2023-08-23 15:18:42 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):117 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@28cf655c[status=failed,message=NoCredentialsError('Unable to locate credentials'),additionalProperties={}]

<img width="1628" alt="Screen Shot 2023-08-24 at 4 24 17 PM" src="https://github.com/airbytehq/airbyte/assets/135266396/2976ccac-42f8-4b36-b7bc-460fd44b2500">
