### ISSUE TITLE
Source Amazon Seller Partner: error when `role_arn` is not specified

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#27495]
### Connector Name

amazon-seller-partner

### Connector Version

1.3.0

### What step the error happened?

Configuring a new connector

## Description:
When using the source Amazon Seller Partner connector, the role_arn parameter is marked as optional. However, if this parameter is not specified, an error occurs when attempting to `split` a `None` value in the `get_sts_credentials` method.

## Expected Behavior:
The `role_arn` parameter should truly be optional, allowing users to omit it if they don't require a specific role. The code should handle the absence of the `role_arn` gracefully, without causing an error.

## Current Behavior:
If the `role_arn` parameter is not provided, an error occurs during the execution of the `get_sts_credentials` method due to an attempt to split a None value. This results in an unexpected error message and prevents the proper functioning of the Amazon Seller Partner connector.

### Steps to Reproduce:
1. Try to setup the Amazon Seller Partner connector.
2. Do not provide a value for the `role_arn` parameter.
3. Trigger an check connection.

### Contribute

- [ ] Yes, I want to contribute

**Comment by andreyAtBB** [comment]
JFYI: Issue that duplicates this one https://github.com/airbytehq/airbyte/issues/28727

**Comment by andreyAtBB** [comment]
This issue is fixed

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/29255
