### ISSUE TITLE
connectors-ci: better connector test debugging experience

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27497]
## Current status
On PR and on nightly build we batch the connector test run: a single workflow logs captures tests output from multiple connector. As tests are executed in parallel it can be hard to follow the test execution of a specific connector. Especially for nightly builds where >80 connectors are tested ([example](https://github.com/airbytehq/airbyte/actions/runs/5317126142)).

## Suggestion
1. Create per connector HTML report pages like **what's demoed [here](https://www.loom.com/share/b6e68012e1ad4127bdc66a25c211d848)**
2. Host these reports in the `airbyte-ci-reports` GCS bucket. With a retention of 45 days (like GHA logs)?
E.G: `gs://airbyte-ci-reports/airbyte-ci/connectors/test/nightly_builds/master/1686655046/25ef3a2686617fe0549871d7453b6da70a546db6/source-file/0.3.11/output.html`
3. Make these URL public
4. Add the URL to the html report to the `output.json` file
5. In bot comments on PR we share links to these report page and not to the GHA workflow logs
6. In the daily #connector-health channel reports we share links to connector specific test reports.

**Comment by evantahler** [comment]
Grooming:

* GHA has a 45 day retention period for logs... do we want a retention period?
* Could we use Cloudflare Login to protect the logs?
  * Needs a custom subdomain
* GHA logs are _already_ public... so maybe this isn't an additional risk?
  * We have leaked secrets in the past...  so maybe we need to be a little worried
 
TODO: 
* Whole bucket `airbyte-ci-reports` should be made private.
* Upload these new HTML reports to the `airbyte-ci-reports` bucket
* Make a subdomain to put in front of this bucket and then setup cloudflare auth

**Comment by evantahler** [comment]
cc @supertopher who knows about cloudlfare auth

**Comment by alafanechere** [comment]
> Whole bucket airbyte-ci-reports should be made private. This will contain logs, which might contain secrets.

After discussion with @supertopher the Cloudflare auth is probably not safe enough because it protects access domain, not to direct IP address access.
I suggest to use GCP cookie based authentication:
1. Remove the `allUsers` permission that are not Storage Object Viewers.
2. Make our internal email group and GL email group   Storage Object Viewers.

☝️ This will allow simple access through Google Auth to the report files.

**Comment by alafanechere** [comment]
Moreover please note that I implemented a 45 days file retention on the `airbyte-ci-reports-multi` GCS bucket
