### ISSUE TITLE
For manual syncing sources, Launch button instead of a toggle in source list

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#275]
## Expected Behavior
User should be able to launch a manual source from the sources list directly. 
See specs: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5856%3A0
After clicking on Launch, there should be a feedback "In progress", see specs: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5906%3A810

## Current Behavior
We see the ENABLED toggle that doesn't fit the case for a manual source. 

@cgardens

**Comment by cgardens** [comment]
Just for my own sanity, you just added this to mockups, right? it's not how it originally was?

Yeah, I agree we can make this better. Let's do it post MVP.

**Comment by Jamakase** [comment]
@cgardens We need to add some sort of a flag `isSyncing` in `/v1/web_backend/connections/list` and `/v1/web_backend/connections/get` . Also, we need some sort of getting updates for it. I suppose we still have to do it via polling, right?
