### ISSUE TITLE
Tests for Normalization

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2750]
## Tell us about the problem you're trying to solve
* The testing on our DBT / Normalization code remains spotty. We should improve this. The urgency of this is increased since we will be investing in custom DBT transformations this coming month.
* The goal is to use tests to solidify the expected behavior from normalization. We should test basic cases and known edge cases. We should also set ourselves up so that we can add future edge cases to the tests as well.
* The goal is that anyone on the team should be able to come in and make changes to the normalization code with confidence that they aren't accidentally changing behavior because they can verify it with tests.

**Comment by ChristopheDuong** [comment]
I'm thinking about adding tests cases with some generated DBT models to git from some selected catalog.json
and try having DBT compile them maybe too

**Comment by cgardens** [comment]
I want to provide a more measurable way to determine when the goals of this ticket have been achieved. 

We should be able to ask a new hire (e.g. Davin or Mason) a question about the rules of normalization. They should be able to know how to answer that question. It is okay if not all questions have answers yet (we are not worried about full completeness / every single edge case yet). But if the answer does exist, then it should be easy to discover. If the answer does not exist, it should be easy to add the answer (once we figure out what it is).
