### ISSUE TITLE
Source Salesloft: Add new streams (call data records, call dispositions, call sentiments, custom fields, meetings, searches)

### ISSUE THREAD

**Issue by markortleb-dice** [airbytehq/airbyte#27504]
### Connector Name

source-salesloft

### Connector Version

1.1.0

### What step the error happened?

None

### Revelant information

Can we add the following new streams to the Source Salesloft connector? You can find details about these streams here in the Salesloft API Docs: https://developers.salesloft.com/docs/api. 

Here are the streams we want to add:
* Call Data Records
* Call Dispositions
* Call Sentiments
* Custom Fields
* Meetings
* Searches

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/27505
