### ISSUE TITLE
connectors-ci: use new node pools

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27511]
@cpdeethree is provisionning new node pools for isolation, cost control and tracking.
We should migrate the following workflow to the new runners:
* https://github.com/airbytehq/airbyte/blob/master/.github/workflows/connectors_tests.yml
* https://github.com/airbytehq/airbyte/blob/master/.github/workflows/publish_connectors.yml
* https://github.com/airbytehq/airbyte/blob/master/.github/workflows/connectors_nightly_build.yml
* https://github.com/airbytehq/airbyte/blob/master/.github/workflows/connectors_weekly_build.yml

**Comment by evantahler** [comment]
I think this is done perhape?

**Comment by alafanechere** [comment]
Yep, done!
