### ISSUE TITLE
DefinitionsUpdater cron seeds actor_definition_breaking_changes table

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#27513]
This ticket handles the writing of breaking_changes coming in from metadata. This will require: 

1. Add `releases` property to `ConnectorRegistryDestinationDefinition` and `ConnectorRegistrySourceDefinition` classes
   - type: specific type that contains a `breakingChanges` entry of `"$ref": ActorDefintionBreakingChange.yaml`
   - not required
3. Add new method `toActorDefinitionBreakingChanges` to `ConnectorRegistryConverters.java`
  - for a given `ConnectorRegistrySourceDefinition` or `ConnectorRegistryDestinationDefinition`, turn the dictionary of `breakingChanges` into a list of `ActorDefinitionBreakingChanges`
4. Introduce a new feature flag, `breakingChanges.ingestBreakingChanges`
  - temporary, platform scoped i.e. anonymous workspace
  - Feature flag can default to serving true
  - this is only there so that we can easily turn it off if necessary
5. Update ActorDefinitionMigrator logic to seed breaking change versions (behind a feature flag) 
  - Since the breaking change information is global, not versioned, it should be written always
  - I.e. both when we write the actordefinition and default version, and when we update the actor definition
  - Put the writing of this behind a feature flag

**Comment by erohmensing** [comment]
Grooming: Do we want to store the high level migrationDocumentationUrl anywhere?

**Comment by erohmensing** [comment]
Grooming:
- ConnectorRegistryXDefinition classes should always be updated to reflect what's coming out of the platfomrm

**Comment by pedroslopez** [comment]
was going to pick this up, but I think it's blocked by @erohmensing 's refactor of the actor definition migrator here https://github.com/airbytehq/airbyte-platform-internal/pull/7415
