### ISSUE TITLE
Source Okta: `group_members` not syncing all records properly

### ISSUE THREAD

**Issue by eschrock** [airbytehq/airbyte#27516]
### Connector Name

source-okta

### Connector Version

0.1.14

### What step the error happened?

During the sync

### Revelant information

There is a `group_members` stream in the Okta connector. It is attempting to use this API:

https://developer.okta.com/docs/reference/api/groups/#list-group-members

We have 170+ users, 400+ groups, but only 72 rows returned in this stream. There are two issues:

- The stream doesn't propagate the slice group ID. So there is no actual way to know what users are associated with what group. The 'group_id' field should be propagated into the child stream (similar to what I've seen done with Jira issues)
- I think (?) the fact that the primary_key is declared as 'id' means there's only ever one entry per user, even though users can be part of multiple groups. If there needs to a be a primary key at all, it would be the combination of (group_id, user_id).

### Contribute

- [ ] Yes, I want to contribute

**Comment by eschrock** [comment]
The stream also declares a `cusor_key` of `id`, which doesn't make much sense. For an incremental sync, the only way to do it properly is to look at the 'lastMembershipUpdated' timestamp of the parent group. Using the id field of the group member record doesn't make much sense.

**Comment by eschrock** [comment]
This doesn't really make sense as an incremental stream. There is no way to request only new records, and no way to filter to only new records. You could filter the parent stream to only be groups with recently updated memberships, but you'd still have no way of detecting deleted entries. This should really be a full stream only (similar to other child streams like GroupRoles). Here's a quick and dirty diff:

`diff --git a/airbyte-integrations/connectors/source-okta/source_okta/source.py b/airbyte-integrations/connectors/source-okta/source_okta/source.py
index b80f3dbbed5..a1616a09532 100644
--- a/airbyte-integrations/connectors/source-okta/source_okta/source.py
+++ b/airbyte-integrations/connectors/source-okta/source_okta/source.py
@@ -60,12 +60,20 @@ class OktaStream(HttpStream, ABC):
             **(next_page_token or {}),
         }
 
-    def parse_response(
-        self,
-        response: requests.Response,
-        **kwargs,
-    ) -> Iterable[Mapping]:
-        yield from response.json()
+    def parse_response(self, response: requests.Response, **kwargs) -> Iterable[Mapping]:
+        response_json = response.json()
+        if isinstance(response_json, list):
+            for record in response_json:
+                yield self.transform(record=record, **kwargs)
+        else:
+            yield self.transform(record=response_json, **kwargs)
+    
+    def transform(
+        self, record: MutableMapping[str, Any],
+        stream_slice: Mapping[str, Any],
+        **kwargs
+    ) -> MutableMapping[str, Any]:
+        return record
 
     def backoff_time(self, response: requests.Response) -> Optional[float]:
         # The rate limit resets on the timestamp indicated
@@ -115,9 +123,9 @@ class Groups(IncrementalOktaStream):
         return "groups"
 
 
-class GroupMembers(IncrementalOktaStream):
+class GroupMembers(OktaStream):
     cursor_field = "id"
-    primary_key = "id"
+    primary_key = ["group_id", "id"]
     use_cache = True
     min_id = "00u00000000000000000"
 
@@ -130,16 +138,9 @@ class GroupMembers(IncrementalOktaStream):
         group_id = stream_slice["group_id"]
         return f"groups/{group_id}/users"
 
-    def request_params(
-        self,
-        stream_state: Mapping[str, Any],
-        stream_slice: Mapping[str, any] = None,
-        next_page_token: Mapping[str, Any] = None,
-    ) -> MutableMapping[str, Any]:
-        params = super(IncrementalOktaStream, self).request_params(stream_state, stream_slice, next_page_token)
-        latest_entry = stream_state.get(self.cursor_field) if stream_state else self.min_id
-        params["after"] = latest_entry
-        return params
+    def transform(self, record: MutableMapping[str, Any], stream_slice: Mapping[str, Any], **kwargs) -> MutableMapping[str, Any]:
+        record["groupId"] = stream_slice["group_id"]
+        return record
 
 
 class GroupRoleAssignments(OktaStream):`
 
 On the surface this seems much better (we get 4800 group membership records instead of 72), I'll do some additional testing to validate the data and look into updating unit and acceptance tests to reflect this change.

**Comment by erica-airbyte** [comment]
Zendesk ticket #[23](https://airbyte1416.zendesk.com/agent/tickets/23) has been linked to this issue.

**Comment by marcosmarxm** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/27533
