### ISSUE TITLE
1s1t (secret) config option + spec feature branch

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27528]
We Should be able to release a version of the BigQuery connector which contains the new 1s1t logic but is only active for internal worksapces. This should also be the mechanism which enables beta testers to use 1s1t.

**Comment by evantahler** [comment]
Choice to make:
a. merge all the new code to master, and enable with a feature flag for some workspaces
b. keep all the new code on a long-running feature branch and publish a new connector version, feature flag opts into the new connector version

Decision
* Up-until we bump to v2, use a (per-connection) feature flag. 
  * does not work for OSS
* After that, users can opt-in by choosing the new connector version

**Comment by cynthiaxyin** [comment]
Created a new branch: https://github.com/airbytehq/airbyte/tree/destinations-v2-beta

Added the spec option for beta: https://github.com/airbytehq/airbyte/commit/0f7a9e695a245161ba3bf2d2e42cb542a2b41c84
