### ISSUE TITLE
Source MongoDB: Deduplication Support for MongoDB

### ISSUE THREAD

**Issue by ChrisMDriveYello** [airbytehq/airbyte#27538]
### What area the feature impact?

Connectors

### Revelant Information

Having a MongoDB connector currently allows only the following Sync Modes:
 - Full Refresh | Overwrite
 - Incremental | Append
 - Full Refresh | Append
![image](https://github.com/airbytehq/airbyte/assets/88639882/703623db-a2ea-415d-8659-6da2b191cc6b)

Add `Incremental | Deduped History` for MongoDB
Remove duplicated from MySQL destination if mongoDB is the source.

it would be awesome to have CDC 
https://docs.airbyte.com/understanding-airbyte/cdc/#current-support

**Comment by postamar** [comment]
Closing as this has been implemented with source-mongodb-v2.
