### ISSUE TITLE
Create a template for writing a python destination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2755]
## Tell us about the problem you're trying to solve
This ticket tracks creating a plop template for boostrapping writing a python template

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368158086388) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Here is an example of destination implementation in this PR: https://github.com/airbytehq/airbyte/pull/3021
