### ISSUE TITLE
KYVE source logo is missing

### ISSUE THREAD

**Issue by cgkournelos-rf** [airbytehq/airbyte#27562]
### Connector Name

source-kyve

### Connector Version

0.1.0

### What step the error happened?

Other

### Revelant information

The logo svg file of [KYVE source](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-kyve) is not rendered as shown in the image below.

![image](https://github.com/airbytehq/airbyte/assets/123638870/d846d702-b2e2-4ed4-86d4-55bf9657b289)

Will this be fixed with the [future plan updates](https://docs.airbyte.com/connector-development/connector-metadata-file)? 

### Contribute

- [X] Yes, I want to contribute

**Comment by abhishekpatel946** [comment]
@cgkournelos-rf This should be ` icon: icon.svg` instead of ` icon: kyve.svg`

**Comment by kurayami07734** [comment]
Please assign me to this issue

**Comment by cgkournelos-rf** [comment]
> @cgkournelos-rf This should be ` icon: icon.svg` instead of ` icon: kyve.svg`
> 
> https://github.com/airbytehq/airbyte/blob/6c0406739d5a3f31070d7b96e674dd680173ce9d/airbyte-integrations/connectors/source-kyve/metadata.yaml#L9

thanks @abhishekpatel946 we have changed this and we are waiting to see if this will resolve the issue in the next PR.

**Comment by kurayami07734** [comment]
![screenshot-2023-10-05_17:38:27](https://github.com/airbytehq/airbyte/assets/60501848/c1c81700-9f58-4ebe-936e-473884151c02)

It still is not showing up

**Comment by btkcodedev** [comment]
Logo added during update
Ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-kyve/icon.svg
![image](https://github.com/user-attachments/assets/7b3a5ac4-6add-4770-9e33-cf05ec25cc96)
