### ISSUE TITLE
toDialect Tests

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27566]
There are likely slight differences where we need to inject destination specific dialect logic - we should test that this behaves correctly.

**Comment by cynthiaxyin** [comment]
toDialectType unit tests complete for BQ

For other destinations (BQ doesn't need this), we've concluded that will be able to inject destination-specific logic in the `extractAndCast` method of  `FooSqlGenerator.java`. See https://docs.google.com/document/d/1pX4koj-Dxl0Hu75S4x9dv8adSea13GfIUqjps-mvbW0/edit#heading=h.50fam4b639fh
