### ISSUE TITLE
1s1t Performance Testing

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27571]
We should validate that the performance of 1s1t is better than the old version, whilst being not obviously inefficient. For this test we should be able to Easily iterate on SQL statements which are generated for timing e2e runtime to answer the following:

- ​​Does the time for each execution get worse as the data considered gets larger?
- Does the time for each execution get worse as the data considered gets wider?
- Can we brainstorm alternative ways to craft each step of the query?  Maybe at some scale it is better to materialize the tmp table rather than use with CTE as (...)
- Start confirming that the E2E time for the old sync + normalization is slower than the new type+deduplication code

**Comment by jbfbell** [comment]
@edgao brought up a concern where the typing and deduping logic is using full table scans. Is this a concern that we want to address now? Are there ways which we can improve performance?

**Comment by jbfbell** [comment]
While looking at the [BigQuery Docs](https://cloud.google.com/bigquery/docs/clustered-tables), it seems like we could make improvements to how we're using BigQuery's Clustering feature. Today we're clustering on the `_airbyte_extracted_at` column, but it seems like clustering on all columns (theres only 4) could potentially add some benefits? Seems like a good candidate to test if there is time.

**Comment by evantahler** [comment]
Grooming:

* Make a new workspace
* Make a new BQ project (to isolate billing stats)
* Wire up 2 syncs:
  * faker -> BQ-old-normalization
  * faker ->BQ-1s1t
* run syncs every 2 hours for both, but offset so we can look at billing stats (e.g. cron even hours vs cron odd hours)
* Confirm we are faster by making charts in metabase

Phase 2:
* Find some really wide CSV sources and repeat

**Comment by evantahler** [comment]
New BigQuery project created: `destinationsv2-perf-testing`
New Airbyte Cloud workspace created: `b61bc266-ef3c-460c-af2f-f70da4a2993c` ("Destinations V2 Performance Testing")

**Comment by evantahler** [comment]
Doc about performance testing new new workspace: https://docs.google.com/document/d/1mCZnKkva6Huj1NxEQ2Bchk_aVpNLUfOgB6w9z1vOA-U/edit

**Comment by evantahler** [comment]
Closing this story, doing https://github.com/airbytehq/airbyte/issues/28380 as followup
