### ISSUE TITLE
assertQueryResult Error

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27572]

**Comment by jbfbell** [comment]
From @edgao 

> if anyone wants to dip their toes into the sqlgenerator code (and also tell me how they feel about the assertQueryResult output) - I just found an interesting bug in the type-cast-error-detection code, but want to take some time today to get situated with OC stuff.
specifically, the error detection logic probably needs to look something like this:
```
JSON_QUERY(...) IS NOT NULL
AND JSON_QUERY(...) != null
AND SAFE_CAST(JSON_VALUE(...) AS whatever_type) IS NULL
```
because `json_value(JSON'{"foo": {}}', '$.foo')` always returns `null` in bigquery >.>

https://github.com/airbytehq/airbyte/pull/27268/commits/bebe0decc902f0bcf551c47e8a81aacd0572e3af has a rough sketch of the test case, but I didn’t get the expected records right. They’re apparently all failing right now

**Comment by edgao** [comment]
more details:
* the json_query vs json_value thing is true
* and also the sql doesn't currently verify the specific json type (e.g. a `{type: object}` column will accept any json value, not just objects)

the current test failure:
```
Mismatched row: id=4; updated_at=2023-01-01T01:00:00Z; 
  _airbyte_meta expected ObjectNode {"errors":["Problem with `string`","Problem with `number`","Problem with `integer`","Problem with `boolean`","Problem with `timestamp_with_timezone`","Problem with `timestamp_without_timezone`","Problem with `time_with_timezone`","Problem with `time_without_timezone`","Problem with `date`"]}, got ObjectNode {"errors":[]}
  array expected null, got ObjectNode {}
  struct expected null, got ArrayNode []
```

i.e. the `_airbyte_meta` column has no errors, and array/struct both accepted invalid data.

**Comment by edgao** [comment]
fixed in https://github.com/airbytehq/airbyte/pull/27268/commits/a09fda9175d0ecbe5e7acc86113858fe65a1a19e
