### ISSUE TITLE
Extract logic from onClose and startTracked Functions to shared library

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27575]
Grooming:
* Make a new class
* Invoke that class from within the (destination)RecordConsumer
  * Only BQ should change at this time.  Probably touching ~3 files

**Comment by edgao** [comment]
marking as blocked by https://github.com/airbytehq/airbyte/issues/27581 - I think we should clean up all the catalog/record-modifying stuff before trying to extract these things. lmk if you feel otherwise though

**Comment by evantahler** [comment]
Unblocked!
