### ISSUE TITLE
Standard Inserts does not work with Incremental Typing and Deduping (and checkpointing doesn't work)

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27586]
As the title says, the standard inserts sync mode for BigQuery does not support incremental typing and deduping. The reason for this is that the transaction is not committed until all the records have been processed. We would need to non trivially refactor the standard inserts code to achieve incremental typing and deduping. 

An ok outcome for this ticket is to choose not to include incremental typing and deduping for standard inserts for the initial launch of Destinations v2

TODO:
* Each batch insert (in the async world) should be it's own transaction, and then type+dedupe can be a second transaction.  Every stream should have it's own transaction(s)
* However, the async BQ is far out... so we need to get this working before the async work is complete
* Learn how BQ+StandardInserts checkpoints.  Is it saying records are committed without the transaction being commited?

**Comment by jbfbell** [comment]
We should not assume that each batch should type and dedupe. In performance testing we found that these queries can slow down a sync and cost users money. We should do them periodically, but not necessarily in sync with the loading of data into the raw table.

**Comment by evantahler** [comment]
Grooming: wait until we have async standard inserts and revisit

**Comment by edgao** [comment]
I confirmed yesterday that we are acknowledging state without committing records to the raw table in standard inserts mode.

**Comment by evantahler** [comment]
This will be closed by https://github.com/airbytehq/airbyte/pull/29812
