### ISSUE TITLE
BigQuery and Snowflake do not allow alter table statements which change a columns data type

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#27590]
we should handle schema changes similarly to normalization. figure out how to do that.

**Comment by jbfbell** [comment]
@edgao has a sketch PR for a potential way to solve this https://github.com/airbytehq/airbyte/blob/64340c913f61b7a4c69f258f7e0ee9a464994bd4/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L166

**Comment by edgao** [comment]
@jbfbell is this issue about altering the raw tables (i.e. as part of the migration) or altering the final tables (i.e. in case of schema change)? or both?

**Comment by jbfbell** [comment]
@edgao I think we can scope it to the latter. If we want to also use it for migrations I'm not opposed, but since the migration is a one time operation I am ok with using the "soft reset" approach. WDYT?

**Comment by edgao** [comment]
mildly opinionated, but will keep that discussion in your doc. edited this issues description to remove the reference to raw tables for now.

**Comment by evantahler** [comment]
List of desired outcomes for various alter table scenarios (Schema changes propagation) https://docs.google.com/spreadsheets/d/1Rz5IBXAFV7caCr8_2UzwWx1t1jDCxz6BccWob66WoJI/edit#gid=0
