### ISSUE TITLE
Improve Oracle Test performance

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#2759]
## Tell us about the problem you're trying to solve
Oracle tests are very slow.

## Describe the solution you’d like
Tests run faster.

## Additional context
One point it's the Oracle database docker image take a long time to be ready.
But JdbcStandardTest use the same image and take ~20 min to run all tests. Compare to Postgres runs max 2 min.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368223115460) by [Unito](https://www.unito.io)

**Comment by etsybaev** [comment]
Performed some investigation:

From what I see now - the main reason is the time required for test-container start. 
For example, it takes 1-2 seconds for the Postgres test-container to become up and running, meanwhile, it takes 40+ seconds for Oracle DB.
So there is nothing we can do there,


Here are some test run comparisons.
Legend: 
o - oracle run
p - postgres run
First digit - time required to start the container
Second digit - time requires to start the container and run the test.
Example:
testGetSpec - {o41,45}, {p1,3}} - 
- Oracle run: 41 seconds to start test container and 45 seconds to start the container and run the test (i.e. 49-45=4 seconds for the test itself)
- Postgres run: 1 second to start test container and 3 seconds to start the container and run the test (i.e. 3-1=2 seconds for the test itself)

Destination:
testEntrypointEnvVar = {o33, 37}, {p4,4}
testCheckConnectionInvalidCredentials = {o34, 100), {p1,64}
TestDataTypeWithNormalization:
1. {o29, 37}, {p1,13}
2. {o32, 39}, {p1,12}
3. {o41, 48}, {p1,12}
4. {o41, 49}, {p1,14}
testSyncVeryBigRecords - {o38, 39}, {p1,2}
testSync - {o41,50, 41, 50}, {p1,4,1,4}
testSyncWithNormalization- {o41,44, 41,44}, {p1,14,1,17}
testNamespaces - {o41,42}, {p1,1}
testIncrementalDedupSync - {o42,44}, {p1,4}
testGetSpec - {o41,45}, {p1,3}
testSecondSync - {o42,58}, {p1,10}
testCustomDbtTransformationsFailure - {o41,44}, {p1,12}
testSyncNotFailsWithNewFields - {o43,55}, {p1,8}
testIncrementalSync - {o42,53}, {p1,8}
testCheckConnection - {o42,45}, {p1,4}
specDBTValueShouldBeCorrect - {o41,44}, {p1,3}
testSyncWithLargeRecordBatch - {o41,56,42,63}, {p1,4,1,5}
testSyncWriteSameTableNameDifferentNamespace - {o41,50}, {p1,4}
specNormalizationValueShouldBeCorrect - {o40,42}, {p1,3}
testLineBreakCharacters - {o40, 47}, {p1,3}
testSyncUsesAirbyteStreamNamespaceIfNotNull - {o41,49}, {p1,4}
testCustomDbtTransformations - {o41,43}, {p1,23}
testNoneEncryption - {o42,43}, {p - no test}




-------------------------------------------------
Source:
testIdenticalFullRefreshes - {o32,45}, {p3,11}
testEntrypointEnvVar - {o30, 36}, {p1,2}
testIncrementalSyncWithState - {o34,45}, {p1,6}
testEmptyStateIncrementalIdenticalToFullRefresh - {o40,51}, {p1,8}
testGetSpec - {o41,48}, {p2,3}
testFullRefreshRead - {o41,47}, {p1,4}
testCheckConnection - {o41,49}, {p1,3}
testDiscover - {o41,50}, {p1,4}
