### ISSUE TITLE
For manual syncing sources, no ENABLED toggle in summary cell in Source > Status

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#276]
## Expected Behavior
Manual sources shouldn't have an ENABLED toggle in the summary cell at the top of the Status tab in source detail page
See specs: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5906%3A1233
Users can click on Sync now to launch a syncing. 

## Current Behavior
We currently see a ENABLED toggle that doesn't fit the case of the manual source.

@cgardens

**Comment by cgardens** [comment]
completed.
