### ISSUE TITLE
santa: improve performance

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2764]
## Tell us about the problem you're trying to solve
Source Stripe currently takes ~4x as much time as the singer counterpart. Investigate and understand what can be done.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368099499442) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Out of curiosity, this is compared to using the raw singer tap? or the airbyte-wrapped singer tap (without santa)?

**Comment by michel-tricot** [comment]
The default page size for stripe is 10. Have you increased it?

**Comment by sherifnada** [comment]
this is compared to the airbyte-wrapped singer tap. And yes, we are using max page size (100) in the current impl.
