### ISSUE TITLE
Google Analytics Universal Connector - start date config is flawed

### ISSUE THREAD

**Issue by hukedd** [airbytehq/airbyte#27661]
### Connector Name

source-google-analytics-v4

### Connector Version

0.1.36

### What step the error happened?

Other

### Revelant information

The connector source only has a replication start date. The problem with this is that there is then no option to control the data window (e.g. window_in_days parameter), and the Google API appears to be limiting the data that it will offer up each day to 14 months.

In practice this means that when running an export, there is no way to export > 14 months worth of data from your GA account. 

The connection will run, and end up with a 'last sync' streamState based on ga_date; the connector will then assume that any further incremental sync's don't need any data prior to that (even though you may only the last 14 months & have 10+ years missing). 

Running a Full Refresh sync mode does not help either - again it will be limited to only 14 months.

To allow a user to export data in chunks based on date ranges, the connector requires a configuration option for replication start date AND replication end date

This will allow a user to export arbitrary data and have access to their full dataset (e.g. export 12 months / day each day over time)

If I have misunderstood this and there is a strategy to make the connector export a full dataset, please inform me :)

### Contribute

- [X] Yes, I want to contribute

**Comment by hukedd** [comment]
Looks like the end date is fixed to the current date here;

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/source.py#L258

Would be great if an additional field 'end date' could be added to the UI that overrides the default 'now' date if present. That way the user has the option to specify ranges / chunks at a time and has access to their full GA3 dataset via AirByte.

**Comment by jrolom** [comment]
@hukedd can you confirm if this is different from this PR?

https://github.com/airbytehq/airbyte/pull/27985

**Comment by hukedd** [comment]
@jrolom thanks for replying.

It's very similar except https://github.com/airbytehq/airbyte/pull/27985 is for the GA4 connector, whereas the issue I raised here is for Google Analytics Universal Connector.

It wasn't clear to me how the PR end date config field is shown in the UI unless this is generated automatically.

**Comment by efimmatytsin** [comment]
Hello everyone! We have the same problem, it's so critical, I will ask support to push that PR.

**Comment by girarda** [comment]
closing as UA is being deprecated.
