### ISSUE TITLE
Source github: timeout error with pull_request_stats and workflows_runs stream enable

### ISSUE THREAD

**Issue by jaorr95** [airbytehq/airbyte#27677]
### Connector Name

source-github

### Connector Version

1.0.1

### What step the error happened?

During the sync

### Revelant information

I am facing some issues with source github when i enable pull_request_stats and workflow_runs stream. These streams are configured with incremental sync. Also we set up the connection with more than 100 repositories. 

The errors that i getting is 502 timeout, github support tell us that the problem is that request are taking longer than 10 seconds to response. 

We would like to know the best practices to avoid this. Split connector with fewer repositories? or is it a bug that can be optimized?

### Relevant log output

```shell
2023-06-22 00:13:12 source > Backing off _send(...) for 5.0s (airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException: Request URL: https://api.github.com/graphql, Response Code: 502, Response Text: {
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXX:XXXX:XXXXXX:XXXXXX:XXXXXXXX` when reporting this issue."
      }
   ]
})
2023-06-22 00:13:12 source > Caught retryable error 'Request URL: https://api.github.com/graphql, Response Code: 502, Response Text: {
   "data": null,
   "errors":[
      {
         "message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `XXXX:XXXX:XXXXXX:XXXXXX:XXXXXXXX` when reporting this issue."
      }
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by artem1205** [comment]
- `pull_request_stats` : GraphQL 502 error is fixed in https://github.com/airbytehq/airbyte/pull/30731
- `workflows_runs` uses standard REST API, and no errors were found
