### ISSUE TITLE
Formatting issues in airbyte-ci pass in PR but fail in master

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#27675]
If we only change metadata validator code, we rightfully skip Octavia CLI: Build Airbyte CDK: Build and Connectors Base: Build

however those builds run format which formats the metadata validator code, which means that the PR succeeds but the build fails on master. 

Ideally: 
- ~~none of those steps would run format on airbyte-ci code, since they're separate~~ 
- something _would_ run format on airbyte-ci code when airbyte-ci code changes

**Comment by evantahler** [comment]
Who formats the formatter?!

**Comment by evantahler** [comment]
Grooming:

* Remove format checks from gradle.yaml workflow (base build).  Don't check the format of AirbyteCI
* Create a custom workflow to run the python formatters (black) for all PRs that touch any .py file
*

**Comment by bnchrch** [comment]
Notes from [slack discussion](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1695160802353479):
- This is also an issue for individual connectors.
- 

Honestly I wonder if we simply need a formatter per type globally

You edit a python file -> run black, flake, isoformat etc
You edit a java file -> run gradle

If the config files are at the top level then its no big deal for your editor to do it automatically

and if we are autoformatting on branches speed doesnt matter

**Comment by bnchrch** [comment]
Moved the larger task to: https://github.com/airbytehq/airbyte/issues/30635
