### ISSUE TITLE
Source Clockify: does not support enterprise version with subdomain

### ISSUE THREAD

**Issue by ezra-quemuel** [airbytehq/airbyte#27688]
### Connector Name

source-clockify

### Connector Version

0.1.0

### What step the error happened?

Configuring a new connector

### Revelant information

Normally, an enterprise version of Clockify will have a company subdomain in order to access it (i.e. `mycompany..clockify.me`). The current implementation does not account for this possibility and hardcodes the api url to be `https://api.clockify.me` (see [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-clockify/source_clockify/streams.py#L16)).

Attempting to setup the source to an enterprise version will result in an error. There should be a parameter exposed to allow specifying the api url.

### Contribute

- [X] Yes, I want to contribute

**Comment by sajarin** [comment]
Completed with the merge of #28622
