### ISSUE TITLE
Update Alpha, Beta, GA to follow new guidelines (core & community)

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27712]
## Overview
We are introducing new external and internal levels of support.

https://docs.google.com/document/d/161FF__wOjwS6j-1fVyHexDD1cJCQ5RJ2LMC8FI2N6yI/edit

## Question
1. How should we update the metadata to reflect community vs certififed?
2. How should we represent (if at all) the internal levels?

---

Things we certainly need to change:

* Metadata:
  *   New external stages
  *   New internal support levels
 
And then...

* Strictness level <--> Certification stage mapping
*  Product
   *   Badges in-app
   *   New levels shown in docs 
* OC issues?
* Free Connector Program? (I think this is going away)  
* Datadog
* ... other places we need to discover?
* Automatic cloud releases (exclude paper?)
* Update "release stages" blog post?
* Nightly/Weekly build logic
*

**Comment by evantahler** [comment]
cc @sherifnada - we are taking notes about what we think will need to be updated in this ticket.

**Comment by bnchrch** [comment]
Closing in favour of
#28713
#28714
#28715
