### ISSUE TITLE
Facebook Marketing API App now is version 17.0.0

### ISSUE THREAD

**Issue by phucdee** [airbytehq/airbyte#27746]
### Connector Name

source-facebook-marketing

### Connector Version

0.5.0

### What step the error happened?

Configuring a new connector

### Revelant information

Seems like Meta has been upgrade their API to v17.0, therefore, when we create new App in Meta Developer Pages, the App get default version as v.17.0
While Airbyte Facebook Marketing Source is using library 16.0

### Relevant log output

```shell
Configuration check failed
Error: 2635, (#2635) Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Change will be release next week https://github.com/airbytehq/airbyte/pull/27563
