### ISSUE TITLE
Helm: previous job-logging removed when minio pod restarting

### ISSUE THREAD

**Issue by jx2lee** [airbytehq/airbyte#27750]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.45.17-helm

### What step the error happened?

During the Sync

### Revelant information

[https://github.com/airbytehq/airbyte-platform/blob/cdd5a7de7cc59094071b056eed65150498307c43/charts/airbyte/templates/minio.yaml#L50](https://github.com/airbytehq/airbyte-platform/blob/cdd5a7de7cc59094071b056eed65150498307c43/charts/airbyte/templates/minio.yaml#L50)

Referring to the code above, it seems that the volumeMounts in minio is set to `/data`, which causes the job-logging folder in `/storage` to remove when restarting.

I have noticed that if change the volume mount point to `/storage`, the logs exist on restart,
so I would like to change it to `/storage`, but is there a case for using the `/data` internally?

i found `/data` as an environment variable CONFIG_ROOT, and wondering if it's fine to change it(to `/storage`). Also, if there's any way to permanently archive only job-logging, please let me know if that's a problem.

```[tasklist]
### Tasks
```

**Comment by jx2lee** [comment]
and then, i found CONFIG_ROOT def in docs.
would you do me a favor? 🥹

[https://github.com/airbytehq/airbyte/blob/1a8e85d050ddf0eb406185914064eb6090e2b959/docs/operator-guides/configuring-airbyte.md?plain=1#L44](https://github.com/airbytehq/airbyte/blob/1a8e85d050ddf0eb406185914064eb6090e2b959/docs/operator-guides/configuring-airbyte.md?plain=1#L44)

**Comment by rootindex** [comment]
I would estimate the easiest solution here would be:

mountPath: "/data" becomes  mountPath: "/storage"

**Comment by jx2lee** [comment]
> I would estimate the easiest solution here would be:
> 
> mountPath: "/data" becomes mountPath: "/storage"

thanks for reply.
in my case, I'm using it by changing the mountPath like you said. I opened an issue to see if the application logic is okay when mountPath is changed.
