### ISSUE TITLE
Source Github: Sync failing due to check operation

### ISSUE THREAD

**Issue by vivekin** [airbytehq/airbyte#27753]
### Connector Name

source-github

### Connector Version

1.0.1

### What step the error happened?

During the sync

### Revelant information

Trying to sync data from ~14k repositories using Github connector.
But facing issue while saving the source when trying configure all repositories (ORG/*).
assuming it is not able to complete the check operation and getting timed out.

So as a workaround, configured only for one repo (ORG/sample-repo), so that the check passes. And then configured the destination and created a connection.
After that, accessed Airbyte configuration database and change it to all repos(ORG/*).

But when running sync job, there is a Github check operation that is being executed in some of the jobs. Whenever the check is executed the sync job results in failure.

Executed the check operation on local and it takes ~12 minutes to complete for all repos .
Changed the timeouts in Airbyte to 15 minutes and restarted the sync, but the check operation didn't get invoked.
 ACTIVITY_MAX_TIMEOUT_SECOND=900
 ACTIVITY_CHECK_TIMEOUT=15
 
Not able to understand why the Github check connection operation is executed in some sync jobs and not in others. Is there any other timeout to be configured?

### Relevant log output

```shell
2023-06-24 23:15:19 INFO i.a.w.p.DockerProcessFactory(create):192 - Preparing command: docker run --rm --init -i -w /data/220/1 --log-driver none --name source-github-check-220-1-isvii --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local
 -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-github:1.0.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER
 -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317
 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.44.12 -e WORKER_JOB_ID=220 airbyte/source-github:1.0.1 check --config source_config.json 2023-06-24 23:16:09 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):231 - Running sync worker
 cancellation...
2023-06-24 23:16:09 WARN i.a.w.g.DefaultCheckConnectionWorker(run):108 - Check connection job subprocess finished with exit code 143
2023-06-24 23:16:09 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):235 - Interrupting worker thread...
2023-06-24 23:16:09 INFO i.a.w.t.TemporalAttemptExecution(lambda$getCancellationChecker$6):238 - Cancelling completable future...
2023-06-24 23:16:09 ERROR i.a.w.g.DefaultCheckConnectionWorker(run):125 - Unexpected error while checking connection: 
java.io.IOException: Stream closed
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by arsenlosenko** [comment]
Hi @vivekin the delay you are having with check operation is due to validation of repositories, before syncing anything source validates if all of repositories are valid. Considering that you have ~14k repository you would like to sync it would take some time to complete, and tweaking ACTIVITY_CHECK_TIMEOUT should help you with that, as you already mentioned. In terms of any other settings related to timeout, there are no additional settings related to that (at least as far as I understand after I investigated this). Can you please clarify if you still have this issue even after increasing these timeouts? Thanks!

**Comment by arsenlosenko** [comment]
closing this issue due to no response, will re-open it if it still relevant
