### ISSUE TITLE
Investigate missing failing test logs in HTML reports

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#27770]
## Problem 1
We are missing output of the Unit test step in the HTML report

[slack thread](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1687820604245189)
[example report](https://storage.googleapis.com/airbyte-ci-reports/airbyte-ci/connectors/test/pull_request/edgao_better_namespace_handling/1687819690/8b1eb950c3c0ef372ce11e0aa249e5eca71c7679/destination-bigquery/1.5.0/output.html)
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/05ce0007-5018-4c9a-a6a5-76678c3c350e)

**Comment by alafanechere** [comment]
Re-opening as we had to revert Dagger version due to https://github.com/airbytehq/airbyte/issues/27970

**Comment by alafanechere** [comment]
Confirming that the update to Dagger 0.6.4 solved this problem:
* [Destination mysql test report before update](https://ff6af5c20bd41603ddad56f65f5db1bb58fa6b27cec08ea95122b93-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fnightly_builds%2Fmaster%2F1689726279%2F4c54e34bd7ef6f46b00e1b59fc941360701244e2%2Fsource-mysql-strict-encrypt%2F2.1.0%2Foutput.html?jk=AYvHSRHiUYiRbcBKc21TtpwC_jyshTRt7_oGOJrUPdCFhj4iwwKdr-mc6YzkyN_91X9AXlap_SpGIldUHpDdDTkBm8QNkslocDcIxT7LPQWFS3y9C4KCnzKHX50WEuknYlGca5Q96r7ub_PeD_vYSpMbM4naDfGd3mkTgRI8hwaa-AuLbGwHWZ7MALOCaOvmeG4uOh63iREuhDev3SNrQs8AshcNpbX5yEmKwSB4eJ9Aem2FTVVy-UIoiJ4EhteLSKHUM2xyDw3GN_Q1ssIJRnvjNSHSqJV_Vgq3ur88q1_vlkPXIVKrulv88bH4pr5PH0i00sNgm2kvaDSy6qdjNoZRCaDehKn6-JzoPXHLp_xAw_TUi-xbzwZzuRo56MpUXWKXVCqEyKWr1z-z7CZWHyylWKiYuiqgXhnmGK1mC_O9Rv3rIM0TSrqeBACAiBadbCUR4BcbpL0xewsDQqOEPfWu8llBEhGx61xPPljy7JuJR8BWzdPsnMM6OxNp4fXOYJLTpD9N1wyiu6cvqcoAMrMYFpleugWtE7R2bCTad5jhd561skm9UCyQoTWKMkwGuLUXfvzfvimtRL6BJa06cH1mKoePK7gPUd4GybpZ9E8FntNaH8XSR8s3XR24gC_AQ2yxH0GgMyzX8ILzErGLeZo8zjcKceDtNgXYVUNfgjD5jQYwnP7bhDqGxdK1MWO2IDDn-NOiHQwNzW1d1vW8J3bbzEr1HfxmK31wdIyJdpcaVOMU94LBSwXcFO8MIh3q2LH5FR84YpZdbFpq9v122zIFfesD_UzxKO9mCvdtX_8-PJNq0MLhclBWtC1V_KhNh4WcdLE2stBf8tC75Oxt_8nYBpUIEhGEGTWGQnHjkRDJohNCWX9p-lm0V1vwLFh5RE8OdWmcTI1yJeX6XTTGOs30oVyUtIdUJao4rZwiCanquvu25eX0qRGUjEL7QyOJoW20to9WQOmnig08Z7kF4KAuqwDmLbWddRgqD5fCstjmqQKvpP9vas-iQmvWQFxlG_JJZV_OsiDjKPJ7kLvTnApL1SfRvV80l8jlg1UbAHW58nA0LmYTBO0PMo6beqcOE25J3ggATjy3uDu1mgmfYlCvyTr4FlHKO-UdkkaUTvuZ4LiYBUBzyoUzjR24El9ZssUzD2kSyy82eX_PcZP09HGB7Wx4t4Tw6_WmdAaf1JrOLffAsSx5UpYVXtok6srO00X8YhyLQjVrP3vNWUZjoUaDXg5nDT0RxyzPAeTkH2U_760oETh9NIKHU8Y32XkCgDLYdlvQefxpojKzavt6_gE6YaiNjlqhMLoIiIKVRjx26J8FNhhtL0xHvu-tmj5pQoUyepqclnQjFlJaBxZ3ZOnlTvlmmSqh8dUSDVZ1HFh2lNxA&isca=1): truncated error message on the gradle integration test
* [Destination mysql test report after update](https://ff6c4194e81a5dd480c1307d18e5f8e90d31b5e3b97834ee7e7324f-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fnightly_builds%2Fmaster%2F1689812326%2Fbaf510b619bfd3beae0223d3a73104d7d67a3075%2Fsource-mysql-strict-encrypt%2F2.1.0%2Foutput.html?jk=AYvHSRGcbGNxBIh6967KH13uIYBBLBVpc1DJfUYSSbYI5iWpZ_AtSpnUvkJ1dHrUEcMej30yjfCBRYDguNq7VsizLh3ELHx2K9tDykFKTsh2q3j7DMulvBFVl8eYviLRWWRFBtlcTTldZvn9gb2e92qErC0uptMyg0-oI0_MebiLq-ploCbVPbeVQyw3W5rcIXyJIrAex9ERm6wDDucfJXJlDArX3uRsU5FjiyfKDSJ5lZiV2TcYniRpxJahMQihroPcNfp-pxMgri9EsW-oNhNh_sTVDDZ4nBbhoBpL79SQggm9cKzyN4wnoznWElcMouoNQ6CWt9pvq3tItez5BeU2qV4Es8IJ-xtem_rBu20GJ4tfg_p2BGIs4jA8HwrG1JkSeS--jkEYAcc5t-SlDPzl4g1M4kXzGiu1956ZP-TVOJ5bID0Ax2BhmGeMK6N4EKvZlVCidPqgr0ZJOdoGb22DEj9WzBNFhGHPmAweFXicR2k1EtnAgWeLU1fb_GSzOUpkUAEZQLRFyRWZXHucbXLYwOh1uqOf9zmxb4pqsxONNUiM-ha55c87EgPFuxYPS2kDkx-dVciHF377b-zbHCfPfHNf3_Vb7j7c-QH1bxWtG90u9VGj9nI0redLGnmIPa_slCccbI68C2G7rhw3E7vDzu3P66ARzjAupO5nhpy6VIpZgpEUg3txMO-V4OmPeualxJDPNzy0cFxRY6SvZr-Fhl1vgGwCmtHe9a1hmSqzCZ62I8XBqpv0iESHO3TC7UQ-z02dwL70m4AVpX4f_Y3onwhvxDSoEa4-crK_KvEs1CqbqQGyM05IXuXrPzbqRY9ksfmaMan7P3Kcqh_uBBt78lTfvIjbLyOYDDY1cxmVWqlU96kFym9C8op-HgXVd7hAUIoEqIBYGek45nR8VcHpyWKsekaIx9P7pPfsg-kRyJ3rOokEKL6CVbqtV3Vf7foAm-qOATPHWKrcBkgcycX7pQOTHoEq1caHUTSPWaDnpJvvMFIRMCUEh0WaursBw8mcqu4bx3Crp0yDO9vbN8SnlN46GbVHySIvcjbuKnTaEdNrlT3PyaFcNOqIg0rzVQrqWhHa7WSd_ucoeFReaOk3_gaDQ9OCQWRrT5NdDX2Fi8q81WaDj1t2v3FffEGl9KKXLI5dSgBBRufuDMoXxW9sfb-GuGjJCOod7ZbIdlV7hw-2IrZHwFnA-KeZDpp4_K1PveoJGDqX9f5RQtzETyM8VtMeIKN5rc2CcD4JaGfe-r-WJRZVsI3HF5ECz83pmhnrnqoVHNFcrBNKNn3F7Yfwzxs0_RyehUVzzsD7ET9-S-dICNGD8Hwehtg9lULDiMyCXOOZPsMc2AGtujwD7l87KHe9aiYArlKwaV4anslxIG-E&isca=1): full gradle logs on the gradle integration tests
