### ISSUE TITLE
Denote "notification email(s)" for the workspace

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27791]
Suggestion: add a notification email(s) to the workspace, so that any number of users can be sent notifications.

When a workspace is created, we denote a "Workspace Email" on the workspace. 

This is the email used for communications from Support and any email notifications.  This mostly serves the email to the correct user, but it can be that the owner leaves the company ([Support pain](https://airbytehq-team.slack.com/archives/C050FT1L2SF/p1687896891851299)) or isn't the end-user of the platform. This means the message can get lost in the wrong email inbox or worse, never seen.

Some considerations: 
- A workspace must have at least one notification email (ie the field cannot be blank). This means the field should not be able to cleared out. It by default (on workspace creation) can be the user that created the workspace.
- The notification email input can contain 1 or multiple emails (comma separated).
- The user need not be a user in the workspace itself. For example, I may want a mailing list to receive notifications (ie data@airbyte.io). (This seems potentially dangerous - someone entering the wrong email domain and sending information about their connections to a third-party because of a typo)

**Comment by malikdiarra** [comment]
This fits the scope of the work we are going to do on user management and RBAC.
We somewhat have a concept of workspace admin but it is not exposed right now.

**Comment by nataliekwong** [comment]
Updated to reflect the new scope from our PRD here: https://docs.google.com/document/u/1/d/14aDWKxPZ-3JSk7LdhDJvWOdemVqwzxkKNfPitStWOvo/edit#heading=h.agrxfsjj7zsy

The approach has changed to add a new workspace attribute instead.

**Comment by nataliekwong** [comment]
Solved by enabling editing of the workspace email. 
Closing, created follow up here https://github.com/airbytehq/airbyte/issues/31673
