### ISSUE TITLE
Source HubSpot: Missing archived owners in Hubspot connector

### ISSUE THREAD

**Issue by gastonrey** [airbytehq/airbyte#27799]
### Connector Name

Hubspot

### Connector Version

latest

### What step the error happened?

Other

### Revelant information

We are using the Hubspot connector and realised that we need to include archived records when retrieving the Owners. Hubspot API by default do not include this so I asume a new flag needs to added in order to be able to include those.
I see you did it in other connectors like this one:

https://github.com/airbytehq/airbyte/pull/17371/files

Am I right and Owners is not including archived by default? 

This is the link to updated documentation from hubspot (There you can see that archived flag is FALSE by default):
https://developers.hubspot.com/docs/api/crm/owners

### Contribute

- [ ] Yes, I want to contribute

**Comment by arsenlosenko** [comment]
@gastonrey Hi, I have added a separate stream to receive archived Owners in PR that I connected to this issue, I'll add this stream to latest version of source today, can you please confirm if it covers your case? Thanks!

**Comment by gastonrey** [comment]
Thanks @arsenlosenko. Looking at the PR as long as I have the ability on Airbyte to set the flag enable_archived=true it's gonna be ok. Is this already available at Airbyte's configuration UI?

**Comment by arsenlosenko** [comment]
@gastonrey right now syncing of archived owners could be done via the stream `OwnersArchived`, not with `enabled_archiged=true` as it is done in  `source-facebook-marketing`, this way you can fetch records of archived owners. Could you please clarify if syncing of this stream covers your case? Thanks!

**Comment by gastonrey** [comment]
Sorry I don't get it. Right now I use hubspot connection and in the list of streams I do not see OwnersArchived, is there anything I have to do to reflect this change in my actual Hubspot connection?

**Comment by gastonrey** [comment]
Oh I already re-synced, checking the stream owners_archived, wait

**Comment by gastonrey** [comment]
Works like a charm! Thanks
