### ISSUE TITLE
Source Square: streams missing link to customer stream

### ISSUE THREAD

**Issue by juftin** [airbytehq/airbyte#27806]
### Topic

square-source streams missing link to customer stream

### Revelant information

A couple streams in the `square-source` connector are missing connections to the `customer` stream (they have a top-level JSON field called `customer_id`)

Ideally this JSON value would be promoted to a top level field on the `payments` and `orders` streams. 

Here is the SQL we're currently using to extract that field:
```sql
select
    p.id,
    p.order_id,
    rp._airbyte_data:customer_id::varchar as customer_id
    p.status,
    p.location_id,
    p.created_at,
    p.updated_at
from airbyte_prod.square.payments p
left join airbyte_prod.square._airbyte_raw_payments rp
        on rp._airbyte_ab_id = p._airbyte_ab_id;
```

I'm still not fully familiar enough with Airbyte to submit a fix myself, but I believe the `customer_id` field needs to be surfaced on the `orders` and `payments` schemas here: [airbyte-integrations/connectors/source-square/source_square/schemas](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-square/source_square/schemas)

**Comment by topefolorunso** [comment]
I will work on this @justinbchau, PR raised for other issues
