### ISSUE TITLE
API endpoint for per stream resets

### ISSUE THREAD

**Issue by ameyabhope** [airbytehq/airbyte#27810]
### What area the feature impact?

Airbyte Platform

### Revelant Information

The airbyte UI currently has an option of resetting a subset of streams per connection. 
I'd like to request an endpoint which does something similar - allowing a list of streams as part of the request body, resetting only those streams for the connection_id.

**Comment by davinchia** [comment]
Hi, 

The UI is powered by the an API endpoint as is, so I'm not sure what additional endpoint you are asking for here. Can you provide more detail?

**Comment by ameyabhope** [comment]
Hi, it seems [/v1/connections/reset/stream](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/connections/reset/stream) is a new addition that didn't exist previously. 
Thanks, closing the issue.
