### ISSUE TITLE
Failure to fetch connectors feed breaks Airbyte

### ISSUE THREAD

**Issue by waynevanheerden** [airbytehq/airbyte#2782]
## Expected Behavior
Failure when fetching connectors shouldn't break airbyte and should instead lead to a degraded experience.

A potential solution could be:
- if the internal of fetching the feed fails, just return the list as it was when core was released.
- tag the response with a last updated at so that the UI can display a little warning if it is too old and that the list of connectors and version isn't up-to-date

## Current Behavior
Extracted from the conversation:
When the airbyte server fails to fetch the list of connectors, the UI stops working. 
One valid scenario when that happens is if your environment has firewall rules that prevents fetching the connector feed from GitHub.

## Steps to Reproduce
`docker-compose up` in an environment that can't connect to Github

## Severity of the bug for you
Critical

## Airbyte Version
1.18.2

## Additional context
*Environment, version, integration...*

**Comment by michel-tricot** [comment]
Hi @waynevanheerden, thank you for reporting. 

What OS are you on?

**Comment by waynevanheerden** [comment]
Hi Michel,
The OS is Ubuntu. The issue is that Airbyte tries to connect to the
internet to get the latest configuration or something and that is blocked
by our firewall. It would be great it that was configurable.

Thanks,
Wayne

**Comment by michel-tricot** [comment]
Hum indeed, we didn't think about this particular case. 

@davinchia what do you think? we could ship with a default file instead and fallback on it if we can fetch the stream from github. We should have some warning somewhere though.

**Comment by davinchia** [comment]
Shipping with a default file makes sense. We can start with returning a `203` and defaulting to the file if we cannot retrieve the list for any reason. The frontend can use the 203 to display a warning that the list might be out of date.

**Comment by waynevanheerden** [comment]
That would be great as I would not be able to get internet access in our
production environment. I have three clients and two of them would have
this same issue.

**Comment by waynevanheerden** [comment]
Also, is this a once off connection at install, or will it
continuously check for updates?

**Comment by davinchia** [comment]
If I remember correctly, the webapp will check for updates whenever it loads the home screen. Are you thinking about a specific condition in particular?

**Comment by waynevanheerden** [comment]
Was hoping that it was a one off and I could hack a work around till we
have a good solution.

**Comment by michel-tricot** [comment]
Unfortunately no :(

I will change the title of that issue and summarize our conversation so we can work on it

**Comment by michel-tricot** [comment]
@waynevanheerden out of curiosity:  I assume the firewall doesn't prevent pulling images from dockerhub?

**Comment by waynevanheerden** [comment]
Hi Michel,
The setup and system is as follows. We have a single server that allows
internet access. The images are pulled to that machine, security checked
and then pushed to our artifactory server which has a docker repository.
From within the network we pull from Artifactory.

It is painfull, but not uncommon when security is a huge focus.

Thanks,
Wayne

**Comment by davinchia** [comment]
Interesting. @waynevanheerden how does the update flow happen today? is it manual?

**Comment by waynevanheerden** [comment]
Yes it is
