### ISSUE TITLE
Server temporarily unavailable

### ISSUE THREAD

**Issue by walker-philips** [airbytehq/airbyte#27837]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.44.12

### What step the error happened?

Other

### Revelant information

Error occurred after upgrading to 0.44.12. Error happens when trying to refresh source schema OR reviewing "Non breaking schema updates" on a custom connector. The connector's discovery step is essentially iterating through a series of local files and identifying the column headers and data types within the columns. Recently we added a column to a file and wanted to pick up this new file structure, but cannot refresh our connector at all.

**Comment by marcosmarxm** [comment]
Closing because no other user has reported the same issue since this was opened.
