### ISSUE TITLE
Endpoint support for connection status

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#27849]
We've encountered some difficulties with implementing the updated connection status representation. The pain point is using the `jobs/list` data to determine status, and we request the most recent 10 jobs as we potentially need the historical job information to make a determination.

**_tl;dr browsers and networking are hard problems and we should collate the necessary data via a new endpoint or optimize jobs/list (via omitting values on the returned objects?)_**

### Endpoint thoughts

If the existing jobs/list endpoint can be sped up enough, that would be great for many reasons. I suspect it can't (or the effort should be spent elsewhere) enough to handle the connections list. Using the existing jobs/list does not help resolve spawning many simultaneous requests, unless somehow we added support for multiple connections, but that would also require stamping the returned objects with their `connectionId`.

A new endpoint could be added, similar to `/v1/stream_statuses/latest_per_run_state`, that returns each latest Job+Status combination. This should be batched, my preference would be by an array of `connectionId`s.

### Background

I see _jobs/list_ respond within 0.5s (median), 1s (75th percentile), and 1.5s (95th percentile), which is manageable on the connection's status page - where this logic has been working for over a month. However, we would like to use this same logic in the connections list tables on _/connections_, _/source/:sourceId/connections_, and _/destination/:destinationId/connections_.

Initial attempt at adding the status worked fine locally even with 50+ [contrived] connections, adding well less than half a second to the page load time. Enabling in a production workspace with ~60 connections was a different story, as the _jobs/list_ endpoint does not behave predictably across different connections and can take upwards of minutes.

Blocking the connections lists for so long doesn't make sense, so the next approach was with async requests allowing them to render as the requests come back. This worked but introduced a new challenge: browsers limit http/1.x connections to 6 per origin, meaning only 6 connections can be processed at a time while the rest sit in a queued state. Additional interactions with the webapp, like navigating to a new page, remain blocked until the existing queue is drained. _But!_ We can cancel pending requests on navigation, like this: (continued under the embedded video)

https://github.com/airbytehq/airbyte/assets/313125/b184a29b-6d79-4fd3-b332-7676d07f2598

Unfortunately this only works for http/1.x connections. Chrome establishes an http/3 connection with cloud, and I assume other browsers do the same or at least negotiate http/2 connections. With multiplexing in these protocols there is no queuing, new tcp handshake, etc, to delay new requests and they are fired off within microseconds of being created. This prevents our ability to cancel the requests - they can be cancelled, chrome devtools shows them as such, and network packet activity correlates with the multiplexed connections closing before returning, but the server still processes these requests and they end up interfering with other active requests.

For testing, in devtools I copied the fetch request for a cloud `jobs/list` request that normally returns in 1.0s to 1.5s. I then made N requests and results indicate that they all compete for the multiplexed connection's resources.

|# requests|min|max|median|avg|
|---|---:|---:|---:|---:|
|5|1165|1309|1220|1241|
|10|1795|6215|5975|4768|
|20|3941|5528|5120|4978|
|50|2915|14730|7946|9295|

and I was curious how this is affected by aborting requests, so a second test used 25 requests but broken into different groupings & timings of cancellations. Each test cancelled 20 requests leaving 5 to complete.

|description|min|max|median|avg|
|---|---:|---:|---:|---:|
|(of 25, aborted **first** 20 requests **immediately**)|6773|8881|7412|7744|
|(of 25, aborted **first** 20 requests **almost immediately**)|6093|14865|14865|11328|
|(of 25, aborted **first** 20 requests **after 1 second**)|2463|7134|6848|5852|
|(of 25, aborted **last** 20 requests **immediately**)|2846|5399|4994|4417|
|(of 25, aborted **last** 20 requests **almost immediately**)|1282|4059|3715|3270|
|(of 25, aborted **last** 20 requests **after 1 second**)|5908|8204|8203|7436|

so they don't block - devtools waterfall graph shows microseconds of preprocessing/queuing and then a large _waiting for server_ block comprising 95%+ of the requests' total time - but certainly interfere with other requests. This interference carries over to other user actions in the webapp, such as navigation, effectively causing them to queue.

**Comment by malikdiarra** [comment]
Refining notes:
- Could the issue also be that we return a lot of information in the message (logs for example)
- Should we create a new API or provide the connection status as part of the regular connection one?
- We can either compute the stream status information on the fly or persist it after each sync.

**Comment by malikdiarra** [comment]
Following our discussion, let's go with a new API

`/connection/status`, for example, that takes a list of `connectionId` as a parameter. It returns an array of elements with the following properties:
- connectionId
- lastSyncJobStatus
- lastSuccessfulSync
- nextSync
- isRunning
