### ISSUE TITLE
Publish metadata and spec on prerelease

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27854]
## Problem
We have to remember to upload the spec of a prerelease when using the image in a LD connector override

## Solution
1. On prerelease Upload metadata to the metadata service bucket
2. Upload the spec to the spec cache

Once these are uploaded the orchestrator will naturally turn them into registry entries which can be used when applying LD overrides

**Comment by erohmensing** [comment]
- we already upload to the spec cache on prerelease publish
- we still need to add the metadata publish (only to versioned, not to latest)
