### ISSUE TITLE
On schedule, send slack message about which connector images have not been published

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27853]
Goals:
* Every hour, send a slack message if there are connectors with new versions on master that have not been published.  
  * @ connector ops
  * Run the cron from Dagster
  * Compare the metadata files on master with the latest registry.  If there's a diff, send the message
* Don't worry about pre-release failures (there are tools already to see failures in this case)

---

Brought up in this [slack thread](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1688079253723319)

Would it be better to have a cron job that runs to catch all unpublished connector images / metadata

0. Would prevent github action outages from not publishing connectors
1. Could naturally work in small batches and frequently. 
2. Could paralellize dagger engine connections

**Comment by alafanechere** [comment]
My suggestion would be to:
1. Keep the current "publish on merge" logic
2. Add a dagster cron job that checks if all the connectors `metadata.yaml` files on master have a corresponding hosted `metadata.yaml` file on GCS. An hosted `metadata.yaml` file means publish happened.
3. Make the dagster job report the missing connectors in a Slack message on #publish-on-merge-updates
3. If we realize it is a widespread problem we can make this job trigger publish pipelines GHA workflow.

**Comment by bnchrch** [comment]
No **Strong** opinion on this! Happy to go the reporting route to save time!

**Comment by evantahler** [comment]
+1 to what @alafanechere said.  Let's report first.  Also, getting the check right and cron working... is 1/2 way to doing a CRON publish anyway!  if we do need to go that route, I would still suggest both - we _try_ to publish on merge, and have a cron come by periodically as a backup.
