### ISSUE TITLE
connectors-ci: The Dagger UI url is not displayed in logs

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27863]
All pipeline using dagger in our CI generate a Dagger Cloud run url that is helpful to debug pipeline execution and check what's cached or not.

This URL is only shared in the dagger logs that we persist at the end of the pipeline run to GCS.
It'd be great to get this url in the HTML report and in the GHA logs because it's helpful to track what's going on during pipeline execution.

We have two options to retrieve this url:
* Hacky: Read the dagger logs at runtime in airbyte-ci and parse it when we find the log line "Dagger Cloud run url"
* Ask the Dagger team if we can retrieve this url in a more elegant way with their SDK

**Comment by bnchrch** [comment]
Grooming
* Lets output the dagger dashboard url filtered to the git commit of the run at the end of the logs and in the html

**Comment by alafanechere** [comment]
Definition of done:
* The dagger cloud run url is logged to the GHA logs
* It's also shared in the HTML report
