### ISSUE TITLE
Recognize connection setup completion and offer additional resources

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#27874]
When users create connections successfully, we redirect them back without any success message or additional information. Having next steps allows users to feel confident that they've done enough (and Airbyte will now start working in the background and sync your data), while also giving additional resources so they aren't sitting and waiting for the sync.

These could make sense for the first connection set up as onboarding content/education: 
Option 1: How will my data show up?
Understand our [core concepts](https://docs.airbyte.com/cloud/core-concepts) and understand how data will appear in your destination.
Option 2: Connector documentation
Learn more about your [source](dynamic link to source connector docs) source and find more sources like it
Option 3: Verify notification settings
Check the [notification settings](dynamic link to connector notifications) to ensure you get notified of sync successes or errors.

Design suggestion: https://www.loom.com/share/b032221215ac4221a4b3a1f9073ec4d7

@Hesperide Given your work around destinations, are there any resources we should try to educate users on about how their data will show up?

**Comment by josephkmh** [comment]
Moving to backlog as something we will discuss at the offsite this week

**Comment by nataliekwong** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/29896 where we have final designs on the approach!
