### ISSUE TITLE
Source LinkedIn Ads: `ad_creative_analytics` not retrieving data after upgrade to version `0.2.1`

### ISSUE THREAD

**Issue by monik-a** [airbytehq/airbyte#27873]
### Connector Name

source-linkedin-ads

### Connector Version

0.2.1

### What step the error happened?

During the sync

### Revelant information

There's an issue with replicating the ad_creative_analytics stream. In the connector version 0.1.16 all works well (logs attached) and rows get fetched.
After upgrading to the new version (0.2.1) there's not much being fetched. The logs provided are from subsequent runs.
How they were produced:
- I upgraded the connector to 0.2.1 and reset the stream
- I ran the sync resulting in 0 rows
- I downgraded the connector back to 0.1.6 and reset the stream to verify if it's because of the upgrade
- I reran the stream just to fetch >7000 records

[412fc5ca_ba6e_4810_8e73_5b444d644a41_logs_2975_txt.txt](https://github.com/airbytehq/airbyte/files/11918533/412fc5ca_ba6e_4810_8e73_5b444d644a41_logs_2975_txt.txt)
[412fc5ca_ba6e_4810_8e73_5b444d644a41_logs_2977_txt.txt](https://github.com/airbytehq/airbyte/files/11918535/412fc5ca_ba6e_4810_8e73_5b444d644a41_logs_2977_txt.txt)

The stream is supported in the connector and it wasn't decomissioned, yet the new version doesn't seem to be able to sync the data. Please investigate 🙏 

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
I updated your issue title to follow the convention described in the template and also added the labels to further investigation.

**Comment by artem1205** [comment]
Hi, @marcosmarxm, I would suggest to close this issue as it works in our sandbox and breaking change migration was introduced in `0.2.0`.
WDYT?

**Comment by artem1205** [comment]
Closing for now, will reopen if needed
