### ISSUE TITLE
Buffer data in the sync worker instead of the destination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2788]
## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368158427648) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
we do this now with backpressure.
