### ISSUE TITLE
Onboarding steps should be clickable, once completed

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#279]
During onboarding experience, user should be able to go back to previous steps, in the case they made a mistake. 
That means in the screenshot below, user should be able to click on step 1 and step 2. 
<img width="526" alt="Screen Shot 2020-09-15 at 12 13 45 PM" src="https://user-images.githubusercontent.com/68561602/93153447-fea4a680-f74c-11ea-891c-eb0bbe1e1343.png">

However, user shouldn't be able to future steps if not already completed. 

@cgardens

**Comment by cgardens** [comment]
yeah. i agreed. @Jamakase - is this something that is easy to do from your point of view?

**Comment by johnlafleur** [comment]
We had a chat with Artem about the following question: When we return to the previous step (from _Set up the destination_ to _Set up the source_) we show update form. In update form, we can change name and configurations fields. But can we change the connector during onboarding steps?

My reply suggestion (@cgardens): if that doesn't add any complexity, yes. And changing connector will change and reset all the fields. The reasoning behind is that we should as much as possible enable users to undo what they did, just following HCI 101 there. Plus, in onboarding, we want users to have a WOW effect asap, and enabling undoing might help them as they might have connected a wrong source for instance.

**Comment by cgardens** [comment]
> HCI 101

what does HCI 101 mean in this context?

**Comment by cgardens** [comment]
I am fine with it appearing like the connector type is changing to the user on the frontend. This would have to be done by deleting the original source or destination and creating a new one. We can do this on the frontend or by adding a web backend endpoint. @Jamakase whatever your preference he is fine with me, but my inclination is that the web backend here is probably the right choice. Does that work for you?

The only thing that I we should _not_ do is add `sourceSpecificationId` as an input field to `source_implementations/update` (same for destination implementation). The connector type of a source or destination should be immutable in the internal data model for monitoring and backend purposes.

(There may be a world in which we don't have to delete the original source or destination, but instead just ignore it, but I haven't through that one through and it seems kinda tricky).

**Comment by Jamakase** [comment]
Ok, so as I understand it - update of the source is actually next:

- create new source_implementation with values provided
- check it
- if check passed - delete old implementation
- if not - delete the new one

And it's indeed better to handle it on backend.

**Comment by cgardens** [comment]
What you described works and is fine with me. I was thinking of it like this though, but maybe I missed an edge case:

```
click on the previous step
pick a new connectors and fill out the fields.
as soon as they hit submit, delete the old implementation and create the new one
then it is the same flow as before. you don't get to move on to the next step until the connection is passing.
```

**Comment by Jamakase** [comment]
> What you described works and is fine with me. I was thinking of it like this though, but maybe I missed an edge case:
> 
> ```
> click on the previous step
> pick a new connectors and fill out the fields.
> as soon as they hit submit, delete the old implementation and create the new one
> then it is the same flow as before. you don't get to move on to the next step until the connection is passing.
> ```

Yeah, this is also a possible way to solve it - but it is more error-prone. I think from user perspective it is better to have update failed and old values stored than update failed and somehow everything was deleted.

What is more, it will need additional logic on frontend to handle such edge cases. So I would better go with creating new and deleting old one, if possible. Are you fine with that?

**Comment by cgardens** [comment]
yup! works for me.
