### ISSUE TITLE
SQL Server sync have started failing ingestion CDC incremental

### ISSUE THREAD

**Issue by dbbcosta** [airbytehq/airbyte#27918]
### Connector Name

source-mssql

### Connector Version

1.0.19

### What step the error happened?

During the sync

### Revelant information

Tools and Infos:

Deployment: Using a instance on VM cloud
Airbyte Version: * 0.50.5
Source name/version: SQL Server(mssql)
Destination name/version: BigQuery

Description(Points):
1 - I have a SQL Server conection Airbyte on cloud that run every day at 05:00 AM
2 -The first sync(using JDBC) works 100%
3 - The second sync(using change data capture) works 100%

![image](https://github.com/airbytehq/airbyte/assets/132381863/e084fba6-e228-410f-b359-18269e7c6048)

4 - From now nothing has updated more, but i have a fake positive execution status.
![c0df7fa16ab24d438796fd2244ebf4575bd9d174_2_690x417](https://github.com/airbytehq/airbyte/assets/132381863/a2e95d34-5260-4601-9853-a68a296e7623)

I dont now if this problem is because my table has a biggest volume of data(283 GB) or because my Airbyte isnt supporting collect the CDC logs data
![b5794055d94235dbdd552312d0e5a8ba4756ae2b](https://github.com/airbytehq/airbyte/assets/132381863/bcd3222c-466b-440d-bdfe-f10e58451038)

Looking for the job log i see a message: Producer failure com.microsoft.sqlserver.jdbc.SQLServerException: The result set is closed.
![a4f9e045c21b223bd344fa7e0062814ccc65ef47_2_690x191](https://github.com/airbytehq/airbyte/assets/132381863/be461f18-d941-4b23-867d-7b70d056a220)

and other message: The main thread is exiting while children non-daemon threads from a connector are still active.

![73b6d24e62304481be5a8a1d16a64e75b41d29aa_2_690x191](https://github.com/airbytehq/airbyte/assets/132381863/d4272529-3f8f-49fa-9dfe-6d9182be4b1f)

Just complementing, i have many others conections using CDC and working.

Does anyone know what must be the cause of this? I appreciate any help!

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This report highlights a problem with an older version of the MSS connector. Please upgrade to the latest version, `4.0.21`, as it offers numerous improvements over the reported version.
