### ISSUE TITLE
Source Chartmogul: `Interval` input should follow pattern of one stream per interval

### ISSUE THREAD

**Issue by ChristoGrab** [airbytehq/airbyte#27953]
### Topic

Interval pattern

### Revelant information

The `Interval` input field in the Chartmogul source connector currently consists of a dropdown menu with time interval options (ie, day, month, year) for the CustomerCount stream.
 
As per @sherifnada's recommendation, this could instead follow the pattern found in other connectors ([example](https://docs.airbyte.com/integrations/sources/tiktok-marketing/#supported-streams-and-sync-modes)) of having one stream per interval.

**Comment by shubhamvrs** [comment]
Please assign this to me, I want to give it a shot

**Comment by justinbchau** [comment]
Hi @shubhamvrs , I already assigned you one issue so to give others a fair chance, I will leave this issue open. 

If you submit a PR for the other issue and this is still available, let me know and I can assign this to you!

**Comment by shubhamvrs** [comment]
ok @justinbchau

**Comment by topefolorunso** [comment]
@justinbchau Please assign this to me next. PR raised for other issue
