### ISSUE TITLE
Add additional information on add connector failure.

### ISSUE THREAD

**Issue by fwdolegp** [airbytehq/airbyte#2795]
## Tell us about the problem you're trying to solve
Failure of adding connector using UI do not give good amount of info why connector cannot be added.
Same on API level

## Describe the solution you’d like
Provide clear message to the user or developer about actual problem.
Example: Connector cannot be registered. Method "spec" not implemented or not accessable.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368158749785) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@fwdolegp thanks for reporting this! we will look into doing this. 

if you are able to pull any logs manually when you get this error we'd also be happy to help you debug it.

**Comment by cgardens** [comment]
UI shares a lot more info now. clsing.
