### ISSUE TITLE
[platform] Add private container registry as option to pull connector

### ISSUE THREAD

**Issue by fwdolegp** [airbytehq/airbyte#2796]
## Tell us about the problem you're trying to solve
If airbyte planning to be used by enterprises then you will face a limitations with custom connectors development and private container registries access (most likely enterprises will not open their code)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368158728895) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@fwdolegp would it make more sense to add the private registry via the `docker` CLI tool on the node running Airbyte? Or is there a reason to do this via Airbyte itself?

**Comment by fwdolegp** [comment]
Docker cli always there :) But it requires access to the terminal(which may be an issue when in prod). Also, think about airbyte user experience. The person who configures it may not have required skills. It could be QA, Sales or others who just need to get it going without calling some one for help.  Simplicity is a key. That was my point.

**Comment by sherifnada** [comment]
@fwdolegp great point and definitely agree that the UX would be better this way. We'll put any updates here about prioritization!

**Comment by jdclarke5** [comment]
Thumbs up to this. 

Adding a docker registry via the UI and then specifying that registry at the "Add Connector" time would be a good flow IMO.

**Comment by ramonvermeulen** [comment]
Big up for this one, I think it would be more user friendly to be able to add a private docker registry through the UI.

**Comment by devhmars** [comment]
would also be massive for PetsAtHome who are looking to implement airbyte on a large scale we want to use google cloud registry

**Comment by jyates-om1** [comment]
I wanted to point out this comment for anyone who needs to use AWS ECR as a private docker repo for their custom connectors: https://github.com/airbytehq/airbyte/issues/4866#issuecomment-884843042

This works if you are hosting on EC2 and have an instanceprofile IAM role that grants access to the ECR you are trying to pull from. I still think that the UI feature would be great.

**Comment by marcosmarxm** [comment]
Good news, everyone! This task is already completed and will be released in Airbyte version 1.4.0.
