### ISSUE TITLE
Add configurable option for HTTP request on what to consider success status code for response.

### ISSUE THREAD

**Issue by fwdolegp** [airbytehq/airbyte#2797]
When dealing with large number of REST APIs would be nice to ask user what is actually the success status code for their API end point response.
I think currently it is hard coded as 200. But it is not always a true. (200 can be default)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368223568491) by [Unito](https://www.unito.io)

**Comment by girarda** [comment]
the HttpClient's error handler supports configurable success criteria
