### ISSUE TITLE
Check usages of test catalog json in `standard-destination-test` in a Destinations V2 world

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#27997]
See catalog schema here:
- https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/standard-destination-test/src/main/resources/v0
- https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/standard-destination-test/src/main/resources/v1

Referenced in `ArgumentsProvider`s:
- https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/argproviders

Used in https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/standard-destination-test/src/main/java/io/airbyte/integrations/standardtest/destination/DestinationAcceptanceTest.java and other destination-specific DAT's.

**Comment by evantahler** [comment]
Grooming:
1. We can pull these schemas into new type parsing tests (move them)
2. Look at where these schemas are used - if another destination won't test this, we should update it (e.g. normalization test).  per-destination tests, we will hit later (e.g. clickhouse).
