### ISSUE TITLE
Source Chargify: Add additional streams to chargify

### ISSUE THREAD

**Issue by richardlam-quotapath** [airbytehq/airbyte#28026]
### What area the feature impact?

Connectors

### Revelant Information

Our company is using airbyte to sync data to our database but we want to sync additional data from chargify such as transactions, invoices, and coupons.

**Comment by topefolorunso** [comment]
I will work on this next @justinbchau, raised PR for other issues

**Comment by aashalabi** [comment]
I'm new to Airbyte and Interested to learn how to create connector. It is possible collaborate on this one ?

**Comment by aashalabi** [comment]
@topefolorunso
