### ISSUE TITLE
Get rid of false positives on schema changes

### ISSUE THREAD

**Issue by mfsiega-airbyte** [airbytehq/airbyte#28046]
Today, we detect the presence of schema changes by comparing a hash of the old schema with a hash of the new schema. However, for some reason the hashes aren't stable (theory: JSON maps aren't guaranteed to be in-order). This means we sometimes think that the schema has changed when it really hasn't. As a result, users see the notice banner that they have schema changes, but the diff is actually empty.

It's probably possible to guarantee stable hashing, but since it's difficult to reproduce, we should look for a short-term solution. Proposal - when we discover a new schema, diff it against the most recent version. Only save the new schema if there is a real diff.

**Comment by flutra-osmani** [comment]
1. If we compare it against the most recent version and only save it if there is a real difference between the two, this means that  the entire schema will have to be loaded each time and compared. This could be a bit inefficient if the schema is large. But it should work for the short term.

**Comment by flutra-osmani** [comment]
This has been merged. Being rolled out gradually using a FF. Will create another ticket to clean up feature flags. Closing this one.
