### ISSUE TITLE
Long-lived log loading & downloads can use some user feedback

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#28053]
Looking at the resource loading times for _jobs/get_debug_info_ endpoint, the majority of logs are downloaded within ~2.5s, but the 75th percentile sees spikes to 10s and 99th shows 30s to 5m. We should add a spinner or some other indication that the download is happening.

I was going to propose some method(s) to display the amount downloaded, but the logs show the vast majority of time is Time To First Byte, not downloading; download time peaks under 2s at the 99th percentile. Downloads in the last 2 weeks have not exceeded 1gb, with a median well under 100mb.

**Comment by josephkmh** [comment]
Refining notes:
- Not clear exactly where in the UI a spinner is missing?
