### ISSUE TITLE
1s1t: cleanup+refactoring in AirbyteType/Utils

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28054]
do @jbfbell 's comments

* this entire review https://github.com/airbytehq/airbyte/pull/27936#pullrequestreview-1515105919
* https://github.com/airbytehq/airbyte/pull/27936#discussion_r1253589757

**Comment by cynthiaxyin** [comment]
@jbfbell Just saw your comments 👍 I can pick this up if no one else gets to it first since I wrote most of that code.
