### ISSUE TITLE
[Roadmap] Shopify to GA

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#28061]

**Comment by bazarnov** [comment]
Awaiting this one to be closed before certifying to GA: https://github.com/airbytehq/airbyte-platform-internal/issues/7392

**Comment by bazarnov** [comment]
Closing on behalf of https://github.com/airbytehq/airbyte/issues/25318 as duplicate.

**Comment by nickisobrien** [comment]
👋 what does GA mean? Google Analytics?

**Comment by bazarnov** [comment]
Of course.

**Comment by nickisobrien** [comment]
> @nickisobrien GA means Generally Available

Ah, heh, that makes more sense. Thanks!
