### ISSUE TITLE
Source Apple Search Ads: Create an iOS and Android apps for account seeding purposes

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#28080]
### What area the feature impact?

Connectors

## Description
To test this https://github.com/airbytehq/airbyte/pull/19557 we need to run a campaign to seed the account with data. 
For this purpose we need an iOS and Android apps on the Apple App Store to run a campaign with can give us the data for our sandbox.

## To Do
Create a test Airbyte iOS app which can be added to our Airbyte App Store.

## How to implement
Please try to use [Best no-code app builder](https://zapier.com/blog/best-no-code-app-builder/#softr) to build and publish the app.

**Comment by Diana-Vait** [comment]
I'm closing this task as 'Done'.
