### ISSUE TITLE
Sandbox Account for Google Play Reports

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#28086]
### What area the feature impact?

Connectors

### Revelant Information

Create an account for New Source: Google Play Reports #2974

**Comment by igrankova** [comment]
LastPass name: Google Pay Console Sandbox Account
Paid 25$ for developer account registration on the Play Console.
To publish applications the identity needs to be verified. Asked Otto for help in the [partner-integrations](https://airbytehq.slack.com/archives/C03PDQ9S51U) channel.

**Comment by Diana-Vait** [comment]
I'm closing this task as 'Done'.
