### ISSUE TITLE
Retently

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28118]

**Comment by masyagin1998** [comment]
Looks like a type: maybe Retently?

**Comment by avirajsingh7** [comment]
@RealChrisSean it will take a time to get a api token or account for outreach.
for that time I want to work on retently issue, can you assign it to me

**Comment by RealChrisSean** [comment]
> Looks like a typo: maybe Retently?

Thank you. It was a typo.

**Comment by RealChrisSean** [comment]
Sure thing @avirajsingh7

**Comment by avirajsingh7** [comment]
@RealChrisSean just for future it counts for hackathon [link](https://github.com/airbytehq/airbyte/pull/29040#issuecomment-1669974190)

**Comment by RealChrisSean** [comment]
Please submit your merged PR here :) 

https://docs.google.com/forms/d/1LHRfP-6ULCFIngrh-gj-J5Iv3CuiLceILui4Bx31RgQ/edit
