### ISSUE TITLE
BigCommerce

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28111]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by Gungz** [comment]
Hi @RealChrisSean, would like to try it, can you assign this to me ?

**Comment by RealChrisSean** [comment]
Good luck :)

**Comment by Gungz** [comment]
Hi @RealChrisSean, is there any BigCommerce account I can use for this development ? 
I am trying to create new account but I got this error when doing so from BigCommerce: An error has occurred, please contact support.

![Image](https://github.com/airbytehq/airbyte/assets/442523/067b4401-c555-4f37-9d9a-1b8d44b9c741)

If I get an existing dummy account, probably I can finish over the weekend.
However, feel free to assign to someone else in case an existing BigCommerce is prerequisite to do this task.

**Comment by RealChrisSean** [comment]
Hey Gungz was this only when creating the account? Not when trying to retrieve API keys?

**Comment by Gungz** [comment]
Hi @RealChrisSean, how could I get API key if can't create account ?

**Comment by RealChrisSean** [comment]
Please work on a different issue if you’re unable to create an account.

**Comment by topefolorunso** [comment]
If Hellobaton #29139 is not available, I can work on this @RealChrisSean

**Comment by RealChrisSean** [comment]
Congrats!

**Comment by topefolorunso** [comment]
@RealChrisSean PR not merged yet, so still In Progress
