### ISSUE TITLE
Datadog

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28112]
https://docs.airbyte.com/integrations/sources/datadog

**Comment by sarafonseca-123** [comment]
Hi! I would like to do this issue 😄

**Comment by RealChrisSean** [comment]
Good luck!! :)

**Comment by tovbinm** [comment]
We have a source ready to go - https://github.com/faros-ai/airbyte-connectors/tree/main/sources/datadog-source

**Comment by RealChrisSean** [comment]
Hey @sarafonseca-123 how's it going? Anything I can help with? :)

**Comment by RealChrisSean** [comment]
This has been unassigned due to inactivity. I can reassign this to you later if you're still interested :).

**Comment by btkcodedev** [comment]
I would like to work on this issue @RealChrisSean

**Comment by btkcodedev** [comment]
@RealChrisSean Raised PR #29885
