### ISSUE TITLE
:sparkles: Source us-census : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28122]
https://docs.airbyte.com/integrations/sources/us-census

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by adnanjmi21** [comment]
Hi @RealChrisSean  , I would like to work on this

**Comment by RealChrisSean** [comment]
Hello this has been assigned to you. Good luck!

**Comment by RealChrisSean** [comment]
Hey how's it going? Anything I can help with? :)

**Comment by adnanjmi21** [comment]
Hi Chris ,
Thanks for asking, I started working today on this will reach out to you
incase of any issues.

Best,
Adnan

**Comment by RealChrisSean** [comment]
Awesome thanks for the update 🙏

**Comment by RealChrisSean** [comment]
Hey @adnanjmi21 how's it going bud? :)

**Comment by adnanjmi21** [comment]
Hi @RealChrisSean ,

I am building this source using UI builder , 
how to add query parameters dynamically as the no of query parameter changes for each type of datasets ,
In the UI builder I have made it to take the query parameters to be entered as user input , 
Basically want the highlighted query list to be dynamic in the source creation page ,
any idea how to achieve this
![image](https://github.com/airbytehq/airbyte/assets/54715558/b7b93571-ecf3-4079-8dca-283d82838c41)

**Comment by adityagoel28** [comment]
hey @RealChrisSean , can I take up this issue?

**Comment by justinbchau** [comment]
all yours! @adityagoel28

**Comment by justinbchau** [comment]
I am unassigning this as there has been no progress for 2 weeks. Now open for the taking!

**Comment by mit-27** [comment]
I would like to work on this could you please assign this to me @RealChrisSean ?

**Comment by shivam096** [comment]
Hey @justinbchau ,

I would like to take this up. Since weekend is coming I am hoping to complete it in weekend

**Comment by mit-27** [comment]
Hello @justinbchau, I already started to implement it. Could you please reassign this to me ? It will be completed in two days.
