### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28120]

**Comment by tuanchris** [comment]
I'll take this one

**Comment by RealChrisSean** [comment]
Excellent! This has been assigned to you. Good luck!

**Comment by tuanchris** [comment]
@RealChrisSean Hmm it looks like Trello uses OAuth 1.0 instead of 2.0 as supported by both low code and no code SDK. I'm stuck here. Do you know if anyone from the team can help me? If not I may pick a different connector.

**Comment by RealChrisSean** [comment]
Hey @tuanchris I apologize. I totally missed that with this. Yes please feel free to choose another connector. We have other connectors available that are not displayed. You just need to remove the "hackathon" label from the filter.

**Comment by topefolorunso** [comment]
@RealChrisSean I can make this work with the low code CDK. Please assign to me and move to In Progress

**Comment by RealChrisSean** [comment]
@topefolorunso go for it.
