### ISSUE TITLE
File CDK: add start_date config option

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#28136]
The new file-based CDK does not offer the `start_date` configuration option, but it seems particularly useful and will also give us backwards compatibility with the [existing S3 connector](https://github.com/airbytehq/airbyte/blob/f79aa72d64de412c2710ab806cd1148df7314133/airbyte-integrations/connectors/source-s3/source_s3/source.py#L51).

When `start_date` is set, we should only sync files whose `last_modified` is equal to or greater than that date.

**Comment by brianjlai** [comment]
This should be pretty straightforward to add in and the InMemoryFilesSource has a sample Pydantic field defined that I was using for testing. It should hopefully be as simple as adding a new field to the `AbstractFileBasedSpec` which is part of this PR: https://github.com/airbytehq/airbyte/pull/28139/files#diff-350520aab49a744e977546bc24f69c609e1564e3078839395d0394d86d6d0d47R15-R27
