### ISSUE TITLE
File CDK: S3 config adapter (Parquet options)

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#28135]
The S3 connector offers a `columns` option for [Parquet files](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/parquet_spec.py). It [does not appear to be in use by any connectors](https://airbyte.metabaseapp.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3RcbiAgICAqXG5mcm9tIGFjdG9yIHdoZXJlIGFjdG9yX2RlZmluaXRpb25faWQgPSAnNjk1ODk3ODEtNzgyOC00M2M1LTlmNjMtODkyNWIxYzFjY2MyJyBBTkQgY29uZmlndXJhdGlvbiAtPiAnZm9ybWF0JyAtPj4gJ2ZpbGV0eXBlJyA9ICdwYXJxdWV0JzsiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjo3Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=), but this should be verified. If any connectors are using it, we should update the file-based CDK to handle this option.

#### Acceptance Criteria
- [ ] The existing Parquet config options are mapped and handled appropriately by the file-based CDK.
- [ ] Any options that we cannot support are identified, along with the connectors that will be impacted.

**Comment by clnoll** [comment]
Grooming notes:
- Verify that column selection would be a good replacement for this.
- We'll deprecate the `columns` option (after verifying nobody from cloud is using it) and if any OS users write in we'll tell them to use column selection.

**Comment by maxi297** [comment]
Closing as there are only two customers on cloud using this option (one of which has never been synced and the other was a one time thing) and there is a path forward i.e. the customer can use column selection. This path forward could have a hit on performance but we can re-evaluate when it arises

**Comment by maxi297** [comment]
It was the right issue... So closing because of :

Closing as there are only two customers on cloud using this option (one of which has never been synced and the other was a one time thing) and there is a path forward i.e. the customer can use column selection. This path forward could have a hit on performance but we can re-evaluate when it arises
