### ISSUE TITLE
Add QA check output to the html report

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#28169]
Currently if QA checks fail, the HTML report only gets the following  (https://github.com/airbytehq/airbyte/pull/27752#issuecomment-1631344746). 
![image.png](https://images.zenhubusercontent.com/5c9df18c8ddfda53adf61cc8/ceaf82ae-cf44-4ac0-baae-74ee88d7f235)

Ideally, QA check outputs would be written to stdout instead of only being logged so that users can see what went wrong. 

This is the desired output for the HTML report: 
```
#15 2.622 Running QA checks for source-mixpanel:0.1.37
#15 2.622 QA checks failed for source-mixpanel:0.1.37:
#15 2.622 ✅ - check_documentation_file_exists
#15 2.622 ✅ - check_migration_guide
#15 2.622 ❌ - check_changelog_entry_is_updated
#15 2.622 ✅ - check_connector_icon_is_available
#15 2.622 ✅ - check_connector_https_url_only
#15 2.622 ✅ - check_connector_has_no_critical_vulnerabilities
#15 2.622 ✅ - check_metadata_version_matches_dockerfile_label
```
(from dagger logs)

**Comment by alafanechere** [comment]
Closing as duplicate of #27770
Will be solved by upgrading to the latest Dagger version #28422
