### ISSUE TITLE
Source Zendesk Support: potentially missing records on tickets stream

### ISSUE THREAD

**Issue by williamangelo** [airbytehq/airbyte#28173]
### Connector Name

source-zendesk-support

### Connector Version

0.10.0

### What step the error happened?

During the sync

### Revelant information

Current version of the connector makes every API call with the `start_time` parameter and uses `datetime.now()` to infer this value for subsequent requests. This can potentially lead to records not being fetched since `datetime.now()` is very likely larger than the value provided for pagination in the API response.

According to Zendesk's [documentation](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/#cursor-based-incremental-exports) on cursor-based incremental exports, only the first request should contain the `start_time` parameter. Subsequent requests must contain the `cursor` parameter, using the value provided in the `after_cursor` field from the previous response. It is this value that indicates the next set of records.
A new subsequent request with `datetime.now()` as `start_date` after the first one will skip all records that were updated between the last record of the first request and `datetime.now()`.

### Contribute

- [ ] Yes, I want to contribute

**Comment by wmcguinn-octave** [comment]
We're only experiencing it on version 0.10.1, rolling back to 0.10.0 fixed it. We only get 1,000 records for Tickets and Users. Seems to also affect Ticket Metric Events, we only get 10,000 records.

**Comment by artem1205** [comment]
Please try the latest version.
According to Zendesk's [documentation](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/#cursor-based-incremental-exports) start_time is a required parameter in query and should be passed every time.

**Comment by williamangelo** [comment]
> Please try the latest version. According to Zendesk's [documentation](https://developer.zendesk.com/documentation/ticketing/managing-tickets/using-the-incremental-export-api/#cursor-based-incremental-exports) start_time is a required parameter in query and should be passed every time.

I believe it explicitly says otherwise, as in: 

_"With cursor-based incremental exports, each page of results includes a cursor pointer to use as the starting point for the next page or the next export. **You don't need a start time for the next page or export and the API doesn't provide one**."_

Also, further down on the Cursor-based incremental exports:

_"After using the start_time parameter in the initial request, use the cursor parameter for all subsequent results pages as well as for all subsequent exports:"_

Please let me know if I misinterpreted anything. I ran another sync tool alongside Airbyte (version 0.10.0) for several weeks and can confirm that the Airbyte sync does not fetch the entirety of data. I will replicate the test with the newer version.
