### ISSUE TITLE
Seed 'disputes' stream in Shopify integration testing account

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#28171]
In order to complete https://github.com/airbytehq/airbyte/pull/28083 we need to seed sample data. It looks like it requires a credit card to set up disputes in the account.

Can we add some disputes to the airbyte-integration-test shopify account?

Doc: https://shopify.dev/docs/api/admin-rest/2022-10/resources/dispute

**Comment by efimmatytsin** [comment]
Hello everyone! any updates here?

**Comment by efimmatytsin** [comment]
@sh4sh @igrankova ?

**Comment by marcosmarxm** [comment]
Hello @efimmatytsin sorry the delay. I'm going to get an update and return to you this week.
