### ISSUE TITLE
Controlled rollout of source-postgres with ctid

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#28189]
### Revelant information

Issue to track our controlled gradual rollout of source-postgres with ctid.
ctid is now implemented for all 3 replication types: user cursor (standard), CDC and xmin.

**Comment by prateekmukhedkar** [comment]
Rollout template https://docs.google.com/spreadsheets/d/14c5UzNlxba8-5hMdl2rKwIa6A0QhQbmG4Bjuwu5GYGc/edit#gid=915404461
