### ISSUE TITLE
Initial load for cursor based syncs in MySQL fall back to a select * from table query for streams with no primary key

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#28188]

**Comment by akashkulk** [comment]
Depends on https://github.com/airbytehq/airbyte/issues/28187. If a stream that is synced does not have a primary key, we should fall back to a `select * from table` query. 

This can be done by : 
1. Setting INTERMEDIATE_STATE_EMISSION_FREQUENCY = 0 for the MySQL 
2. Fallback into default sync mode if no primary key is detected for an incremental cursor-based sync

**Comment by prateekmukhedkar** [comment]
Address it when doing Standard(cursor) based syncs.

**Comment by prateekmukhedkar** [comment]
@nguyenaiden set up a standard sync with a table does not have a primary key and verify that we are able to sync.
