### ISSUE TITLE
Persist connector filter choices in local storage

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#28193]
We recently added filters to the connector grid:

<img width="714" alt="image" src="https://github.com/airbytehq/airbyte/assets/7550957/aa8b243a-825e-4098-9681-d613a600ce4a">

If the user makes any changes to the default filters, the changes will be reset when the component mounts again. To improve the UX here, we could store the filter state in local storage so that they are persisted for a single user in their browser.

@lmossman

**Comment by tealjulia** [comment]
Related: https://github.com/airbytehq/airbyte/issues/27457
