### ISSUE TITLE
Truncate failure reason in job log viewer

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#28192]
Currently the entire failure reason is displayed in the log viewer. This is usually 2 or 3 lines maximum, which is not a problem. In rare cases the failure reason is very long, which takes up the entire modal.

As a solution, we should truncate the failure reason at 3 lines. Users will still be able to copy it (by triple clicking to select all) and paste it into an external editor to see the whole message. We could also build in an expand/hide UI, but that feels like a lot of work for this kind of edge case scenario.

Slack context: https://airbytehq-team.slack.com/archives/C05ALB3J52N/p1689149400599409

**Comment by tealjulia** [comment]
Refining notes:
- May not be clear to users that they can triple-click to select all.  Consider adding a "copy" button or helper text here.
