### ISSUE TITLE
[EPIC] Source Shopify to Silver

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#28207]
## What 

We need to upgrade our Shopify certification to the Silver. Checklist teamplate - https://docs.google.com/spreadsheets/d/1v2sRGFxzLgD4JGZ-mTmxctPq1uV1gnxyUcYTM9Ks7nk/edit?usp=drive_link

Doc with Breaking Change for `0.7.0`: https://docs.google.com/document/d/13tMPUGC7aw6lY3VcYQfZu3s34VzF6VvthCo6EarmyGg/edit?pli=1

Checklist: https://docs.google.com/spreadsheets/d/1swnLDznJn-ujZhMRJLmbPnzk_9Uln22enq4r7C1YbIU/edit#gid=1700962388

**Comment by bazarnov** [comment]
https://github.com/airbytehq/airbyte/pull/30246
