### ISSUE TITLE
[EPIC] Source Stripe to Silver

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#28206]
## What 

We need to upgrade our Stripe certification to the Silver. Checklist teamplate - https://docs.google.com/spreadsheets/d/1v2sRGFxzLgD4JGZ-mTmxctPq1uV1gnxyUcYTM9Ks7nk/edit?usp=drive_link

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/pull/29950
