### ISSUE TITLE
Disable appending schema name to table name in destination database PostgreSQL

### ISSUE THREAD

**Issue by swanandvk** [airbytehq/airbyte#2822]
Is there any way to disable changing table names in target db ?Currently it appends schema name to table name while
syncing source and destination PostgreSQL database

Attaching the screenshot
Using the example from the documentation
https://docs.airbyte.io/tutorials/postgres-replication

![](https://user-images.githubusercontent.com/14261123/114145265-d9b79100-9933-11eb-97d9-9c6f1c6a9d4a.png)

Expected behaviour:
It should create the table with same name and schema into destination db

Actual behaviour:
Creates a table with schema name appended to it by default

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368159043660) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
yes, it's coming soon!!
See this for example: https://github.com/airbytehq/airbyte/pull/2807 (and related work around this topic)

**Comment by davinchia** [comment]
@swanandvk the latest version's current behaviour has changed from appending the schema to the table name to mirroring the source layout. Does this fix things?

**Comment by davinchia** [comment]
This should be done, so I'm closing it. Pls reopen if it's still an issue.
