### ISSUE TITLE
Status page: refine how "Pending" is determined

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28222]
There are a few cases where "Pending" should be used for a connection's status and is not currently:

1) Reset occurred and failed (currently Delayed)
2) A single stream is reset
3) A stream is enabled and has no history

branched from: https://github.com/airbytehq/airbyte/issues/27892

**Comment by tealjulia** [comment]
Refining notes:
- 1 may need more discussion/clarification
- 2 and 3 are likely already addressed, if not there is a bug
