### ISSUE TITLE
Show duration per attempt in log viewer

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#28224]
In case a job has multiple attempts, we currently only show the duration of the latest attempt:

![Image](https://github.com/airbytehq/airbyte/assets/7550957/fac2e590-1ee9-4c69-8274-5ebbded244c3)

We should also add the attempt duration for each individual attempt in the log viewer:

![Image](https://github.com/airbytehq/airbyte/assets/7550957/5b228055-6fdb-43f5-8118-830f8e3a5f03)

**Comment by tealjulia** [comment]
Refining notes:
- data is already present, no need to add another query, just show it
