### ISSUE TITLE
Cannot set temporal retention on Kubernetes

### ISSUE THREAD

**Issue by Martelloti** [airbytehq/airbyte#28235]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.44.4

### What step the error happened?

On deploy

### Revelant information

We are getting full disk issues on our Airbyte infrastructure deployed on EKS. I already set the TEMPORAL_HISTORY_RETENTION_IN_DAYS to a different value in both airbyte-cron, airbyte-worker and airbyte-server deployments and it doesn't look like the application is taking this environment variable in consideration. Also, I tried to change the retention date directly on the airbyte-temporal application - both when the DB is being generated and after that - but it seems like some service is changing it back to the 30 days default.

**Comment by justenwalker** [comment]
I suspect this is a bug here:

https://github.com/airbytehq/airbyte-platform/blob/7fc220942c798fb122629c3addd63f9776d8a9fa/airbyte-commons-temporal/src/main/java/io/airbyte/commons/temporal/TemporalUtils.java#L84-L85

```java
                       @Property(name = "${temporal.retention}",
                                 defaultValue = "30") final Integer temporalRetentionInDays) {
```

I suspect this should be set to:

```java
@Property(name = "temporal.retention",
                                 defaultValue = "30") final Integer temporalRetentionInDays) {
```

cc: @davinchia, @sajarin

**Comment by justenwalker** [comment]
Also, it seems this is only called from the workers; so I guess you may only need to set it on the worker configuration?

\https://github.com/airbytehq/airbyte-platform/blob/7fc220942c798fb122629c3addd63f9776d8a9fa/airbyte-workers/src/main/java/io/airbyte/workers/ApplicationInitializer.java#L361
