### ISSUE TITLE
OSLC

### ISSUE THREAD

**Issue by Rots** [airbytehq/airbyte#2825]
## Tell us about the new integration you’d like to have
* OSLC producers and consumers https://open-services.net/specifications/

## Describe the context around this new integration
* syncing requirements from one authoritative tool to a secondary representation
* minutes to hours
* If this is an API source connector, which entities/endpoints do you need supported?
* I don't understand the question

## Describe the alternative you are considering or using
* use some OSLC browser to create the mappings from source types and fields to target entities

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368224097995) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@Rots thanks for your request! This is my first time hearing about OSLC, so please prepare for some naive questions 😄 

1. Are you suggesting that we create a single connector that takes an OSLC service definition and is able to interact with it? Or that we create a code framework (e.g: in python) for pulling data from OSLC services? 
2. Are there some examples of how you'd want to use this connector? 
3. What is the interface you would expect for this connector e.g: what are the inputs you expect to provide it, what is the output you expect, and what should the schema of the data be?

**Comment by Rots** [comment]
1. Ideally, a single connector
I do understand that this might be quite complex as even though OSLC is restricting the generic REST specification, there is still a lot of freedom an OSLC provider has.
That said, there's still potential for automatic UI generation, e.g. if provided by the server, the [OSLC shapes](https://archive.open-services.net/bin/view/Main/OSLCCoreSpecAppendixA.html#oslc_ResourceShape_Resource) can be used to discover available fields of resources
or [delegated UI](https://archive.open-services.net/wiki/core/Delegated-User-Interface-Dialogs-3.0/index.html) can potentially be used to select the target resources.
2. Example import case
Provide an OSLC endpoint (with authentication) and query (e.g. oslc.where clause)
Choose the relevant source fields and mappings to the destination database tables
Run the synchronisation.
Output would be new entries in the destination database

Another example would be the other way round to export to an OSLC provider e.g.
Select Jira issue types, JQL filter, etc
Choose the mappings from Jira fields to target OSLC shape
Run the sync to create (or update) resources on the OSLC server

3. I imagine the complexity would mostly be on creating the UI for the mappings from source to destination. Simple type conversions of properties can probably be handled automatically, but links and relationships to other OSLC resources may complicate this.
Schema of the data, of course will need to be quite flexible, but the low hanging fruit would be get a flat list of resources with selected fields.

I'm not familiar with the AirByte tool at all, so I'm afraid I can't provide too much insight in that context.

**Comment by Rots** [comment]
Is this really completed? I don't see anything mentioning oslc in the connectors list
