### ISSUE TITLE
Source Instagram:  It does not capture media_product_type column #28180

### ISSUE THREAD

**Issue by ext-herbert-santos** [airbytehq/airbyte#28260]
### What area the feature impact?

Connectors

### Revelant Information

Connector Name
source-instagram

Connector Version
1.0.9

What step the error happened?
Configuring a new connector

Revelant information
The Instagram connector is currently not capturing the media_product_type field because of this it is not possible to distinguish the media type. Therefore, it is necessary to add this field to capture this information.

Current output
![image](https://github.com/airbytehq/airbyte/assets/124854335/07bb5319-de07-4326-8985-eda59c8bd743)

Currently, the Airbyte connector is searching for the parameter "media_product_type," but the correct parameter to use is "media_type," as shown in the official Facebook documentation.

Expected output
![image](https://github.com/airbytehq/airbyte/assets/124854335/802156ec-660d-4745-932d-468e1c891fdb)

https://developers.facebook.com/docs/instagram-api/reference/ig-user/media

Output airbyte on aws athena, using o dbeaver to connect.

media_product_type: Surface where the media is published. Can be AD, FEED, STORY or REELS.

**Comment by ext-herbert-santos** [comment]
I already developed the solution, now I need this issue to leave triage to open the pull request

**Comment by Aliya-Tariq** [comment]
Please assign this issue to me

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/issues/31649

**Comment by pabloescoder** [comment]
I can make a PR for this, working on it now.
