### ISSUE TITLE
Full refresh option missing from Postgres source

### ISSUE THREAD

**Issue by nszoni** [airbytehq/airbyte#28280]
### Connector Name

source-postgres

### Connector Version

2.1.1

### What step the error happened?

During the sync

### Revelant information

We just upgraded from `0.40.x` to `0.50.6` of Airbyte running on a Docker container. Using the latest version of the connector.

We noticed that when we set up a new Postgres connection (from on-prem to Azure managed), full-refresh is not among the dropdown menu of sync mode anymore. Even though this work initially, we want to stick with full refresh on the long run to accommodate schema changes. The replication type is in `Standard` mode. We might want to full refresh on certain tables because there are regular schema changes.

![image](https://github.com/airbytehq/airbyte/assets/47299073/dc7eecfa-9fef-44dc-ac5a-ffc228fafaa9)

### Contribute

- [ ] Yes, I want to contribute

**Comment by prateekmukhedkar** [comment]
@nszoni we re-introduced full refresh as part of Standard xmin based syncs on July 18. For Standard cursor based replication modes, Full refresh should always be a choice. Can you upgrade to the latest Postgres source connector version and try? Keep in mind ver 3.x was a breaking change, only if you used CDC mode.

**Comment by nszoni** [comment]
hey @prateekmukhedkar! works as expected now! Thank you!:)
