### ISSUE TITLE
Show CTA to connector settings when error message is related to a failed check

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28286]
When we have a failures due to a failed check, take the user to the connector configuration directly to resolve it, not to see logs.

![image (1)](https://github.com/airbytehq/airbyte/assets/38087517/35e62c89-7cce-48d7-97aa-6ec25864129f)

Shared by Pedro: https://airbytehq-team.slack.com/archives/C03088BTMFC/p1687479863988319

**Comment by chandlerprall** [comment]
Already implemented 🎉 https://github.com/airbytehq/airbyte-platform-internal/pull/7741
