### ISSUE TITLE
Feedback from a Airbyte-ci user

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28304]
## Overview
In a discussion with Akash a few things were pointed out, that I was hoping to raise with the team
1. Alphas tests are failing, we know about it, so can we have a way to skip them in CI
1. Source-postgres passing on aha failing locally
1. The logs are broken in the HTML and thats confusing
1. If a pipeline hard fails we loose log output
1. We should love everything to stdout by default when running locally
1. Can we have a way to skip steps in airbyte-ci?

**Comment by alafanechere** [comment]
> 1. Alphas tests are failing, we know about it, so can we have a way to skip them in CI

#28459

> 2. Source-postgres passing on GHA failing locally

#28460

> 3. The logs are broken in the HTML and thats confusing

#27770

> 4. If a pipeline hard fails we loose log output

#27770

> 5. We should love everything to stdout by default when running locally

#28423

**Comment by alafanechere** [comment]
@bnchrch I'm closing it as all feedback items are now mapped to existing issues.

**Comment by bnchrch** [comment]
Thank you!
