### ISSUE TITLE
Airbyte UI: Inconsistent Names on Job History

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#28317]
We call it the `Job History` tab,  but then we name the list `Sync History` 

A couple of ideas:

- We could just name them the same - either Job History or Sync History
- Ideally, in the not so distant future, we would have other information in this tab, like schema change history. With that in mind, maybe the tab should be called something like `Logs` ? 

<img width="1450" alt="Screen Shot 2023-07-14 at 10 04 13 AM" src="https://github.com/airbytehq/airbyte/assets/109167606/ed1a89a1-e08b-4e48-aff5-0f6db13a91b5">

**Comment by tealjulia** [comment]
related: https://github.com/airbytehq/airbyte/issues/28267

**Comment by josephkmh** [comment]
Refining notes:
- Let's fix the mismatched title, using `Job History` as the title of the list as well
- The "connection timeline" feature is still a ways away
