### ISSUE TITLE
Issue with upgrading Source Connectors

### ISSUE THREAD

**Issue by khoadaniel** [airbytehq/airbyte#28314]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.7

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

**We just upgrade Airbyte from v0.44.6 to v0.50.7 and we now faced issues with upgrading Source Connectors. We actually faced this issue before.**
- For example: from Airbyte console, we changed the version of Postgres Source Connector to the LATEST 3.0.0 :arrow_right: changed saved :arrow_right: we refresh the page :arrow_right: backed to 2.1.0.
- The same problems with other Sources (e.g. Zendesk Support, etc.).

**We could resolve this once in the past by**:
docker-composer down and up again ➡️  then the upgrading issue is gone

Could you please tell us why did upgrade via Console did not work well for us? Any further diagnosis step we can take?

Thank you.

**Comment by khoadaniel** [comment]
The upgrade of Postgres Source seemed to work here:
![image](https://github.com/airbytehq/airbyte/assets/84840546/c4f0e4b3-c0bb-4c54-a960-61086b047146)
Then it's back to the older version.
![image](https://github.com/airbytehq/airbyte/assets/84840546/5430dcd3-e023-487b-9e3d-99ca82ff8925)

**Comment by pmossman** [comment]
This is a pretty old issue, is this reproducible? We've made many improvements to connector version handling since this issue was opened so it may be resolved by now. Feel free to re-open if that isn't the case!
