### ISSUE TITLE
Write tests for bigquery reserved words

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28323]
... and genericize that for other destinations.

Normalization has a list of namespace/name/column names that have caused us trouble in the past - https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/reserved_keywords.py

We should probably write some integration tests to verify that these all work.  We believe that with good quoting we can still use these words for column/schema names.  Test this. 

Move the list of words to the Java codebase.

**Comment by evantahler** [comment]
This seems related to this page: https://airbytehq.sentry.io/issues/4398228154/?project=6527718 / [sync](https://cloud.airbyte.com/workspaces/c67963ed-2c60-4fde-a83b-72dc7de2c245/connections/bdbad1c8-f484-40ef-b1cb-666c4e838db6/job-history#4473759::4):

```
Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: JavaScript execution error: Uncaught Execution of multiple statements failed on statement "CREATE OR REPLACE TABLE "HORAC..." (at line 3, position 0).
SQL compilation error: error line 17 at position 1
.invalid column definition name 'CURRENT_DATE' (ANSI reserved) in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace: 
SYSTEM$MULTISTMT line: 10
```
