### ISSUE TITLE
Handle rename to cursor_based for customer

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#28324]
Yes.
Discussed with Duy.
We used `one_two` in other two words keys/values. Camel case seems off.
This will affect only a [single customer](https://cloud.airbyte.com/workspaces/295bf192-9fa7-4b25-ba04-d1855541c6fe/connections/676f445a-4123-4d87-9429-7a22486bb105/job-history#3154175::0) which I will manually take care of before deploying.

_Originally posted by @rodireich in https://github.com/airbytehq/airbyte/pull/28068#discussion_r1263154719_

**Comment by rodireich** [comment]
I made sure that all their state objects are set correctly and they can sync successfully.
