### ISSUE TITLE
New Destination: Apache Iceberg

### ISSUE THREAD

**Issue by kainoa21** [airbytehq/airbyte#2833]
## Tell us about the new integration you’d like to have
[Apache Iceberg](https://iceberg.apache.org/) is an ideal destination as it represents an open source, file based table format.

## Describe the context around this new integration
Iceberg powers our file based data warehouse at Netflix and we would like to be able to leverage the Airbyte ecosystem of source connectors to ease the burden of data engineers writing bespoke ingestion pipelines.

## Describe the alternative you are considering or using
Bespoke data ingestion pipelines (primarily python) and Spark data sources and data frames.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368159072003) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@kainoa21 thanks for the suggestion! What data scale do you anticipate moving into Iceberg?

**Comment by kainoa21** [comment]
Mostly this would be for the long tail of external or vendor product data ingestion.  Examples are Zendesk, Anaplan, Jira and the like.  So not massive datasets.

**Comment by vikkes** [comment]
any progress here?

**Comment by Leibnizhu** [comment]
I'm working on it.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Support for Iceberg](https://app.harvestr.io/components/0/list/84NDxUjXM)
