### ISSUE TITLE
First github sync does not show history of issue state

### ISSUE THREAD

**Issue by Moofasax** [airbytehq/airbyte#2835]
## Expected Behavior
On the very first sync pulling from a GitHub source to postgres destination, the records within the issue_events_012_issue table would be expected to show a history of the previous state changes of an issue. If i created an issue, closed it, and reopened it, all three records show "open" state.

## Current Behavior
On the very first sync pulling from a GitHub source to postgres destination, the records within the issue_events_012_issue table all have the latest state of the issue, and not the state at that particular time in history. If i created an issue, closed it, and reopened it, i would expect 2 open records, and one closed, but they all show open.

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. Open a github issue in your target repo
2. Close the issue, and then Open the issue
3. Create a job in airbyte (Source Github, Destination Postgres) and kick off the sync for the first time.

## Severity of the bug for you
High

## Airbyte Version
0.19.0-alpha

## Connector Version (if applicable)
Github 0.2.2

**Comment by sherifnada** [comment]
@Moofasax I created an issue, closed it, reopened it, then closed it again (#2866) . Here is the log I found: 

[records.log](https://github.com/airbytehq/airbyte/files/6300912/records.log)

There are 5 events: 

1. "labeled"
2. "closed"
3. "reopened"
4. "added to project"
5. "closed"

is this different from what you are seeing? Unfortunately github doesn't have an "opened" event but apart from that I'm not seeing anything out of the expected?

**Comment by Moofasax** [comment]
Ah ok i was mistaken it creates only 2, not 3, but does not track the history of the state changes, "closed" state. I was expecting to see at least one "closed" record in this table.

I tested this on 0.20.0-alpha just now btw!

```
SELECT * FROM public.issue_events_012_issue
WHERE title = 'your-issue';
```
![image](https://user-images.githubusercontent.com/25934977/114764322-d0626600-9d31-11eb-9d79-d2960dd78a55.png)

**Comment by sherifnada** [comment]
@moosfax the table you are looking at is the `issue` sub-object found inside the `issue_event` response object. From https://docs.github.com/en/rest/reference/issues#events you'll see that this refers to the state of the issue at the time it was synced. If you want to know the state change history, that information is found in the `issue_events.event` column. Does that fix the concern?

**Comment by Moofasax** [comment]
yes i believe it does! We can close!
