### ISSUE TITLE
Be able to choose the cursors of the github source, specifically for issues and PRs

### ISSUE THREAD

**Issue by Moofasax** [airbytehq/airbyte#2836]
## Tell us about the problem you're trying to solve
Using the Github source, and postgres destination, we are trying to just track the state changes of issues and pull requests overtime, but it seems like almost any event always creates new records in the issues table database.

## Describe the solution you’d like
It would be nice for the incremental tables if we could select the field the cursor points to. Ideally we would be able to select the "state" field for both issues and PRs.

## Describe the alternative you’ve considered or used
No alternatives yet

**Comment by sherifnada** [comment]
@Moofasax thanks for the feedback and context! is the concern here a UX one (you'd rather get only specific event types without having to do much work on the destination side) or a performance/cost one on the destination side (you're replicating too much data)? 

I think the most realistic way to do this would be to sync the "Events" stream in Github then filter by event type as described here: https://docs.github.com/en/developers/webhooks-and-events/github-event-types#issuesevent

Would this fulfill the need?

**Comment by Moofasax** [comment]
hmm ok, we were avoiding the events stream since it brought in way to much data in, and is not really meaningful for our perspective.

I think our main concern is that there is no way to link the child elements back to the parent from what i can see. For instance, there is no linking field between an issue, and the issue events.

A meaningful question we would like to answer is: How long does it take to close an issue after it has been reopened? i.e how long did it take to patch what we thought was a completed feature? I don't yet see how we can answer that data within the issue events table.

We did take a look at the ```issue_events_012_issue``` table, and that a looked promising, but it relates to what i opened here: https://github.com/airbytehq/airbyte/issues/2835


I think being able to link the child json record back to its parent seems key for our reporting needs.

**Comment by sherifnada** [comment]
By syncing the "issue_events" stream you get a sub-object `event.issue` which contains the ID of the parent issue in the `issue_events_012_issue.id` column. You can perform a join between that and the issues table via that column. Would that help with the join you are describing?

**Comment by Moofasax** [comment]
Hey im sorry man i dont seem to have the event.issue table, do you man issue.events? also the IDs in these tables are not the same, the ID in the issue.events table is the event ID, and the ID in the issue_events_012_issue table is the issue ID.

**Comment by Moofasax** [comment]
Do you have simple example join i could use? maybe i am looking at the wrong things.

**Comment by sherifnada** [comment]
based on your previous comment:

>  For instance, there is no linking field between an issue, and the issue events.

I'm suggesting that there is such a field: `issues.id` and `issue_events_012_issue.id` refer to the same thing i.e: the github issue ID. So if you wanted to link events to an issue you should be able to do that by doing a SQL `JOIN` on that field. 

Also, just to clarify, the `event.issue` is a nested object returned from the Github API. See how Airbyte normalizes nested objects [here ](https://docs.airbyte.io/architecture/basic-normalization#objects) to understand how the API concepts map to the tables in your destination. 

I think one thing that would be helpful to keep in mind here is that you should always be starting with the [Github API Reference](https://docs.github.com/en/developers/webhooks-and-events/github-event-types#issuesevent) to plan how you should consume the data. The Airbyte Github connector is just moving whatever data that API exposes from the GH API to your destination. In this case, as far as I can tell, the connector is transferring all the fields correctly, it's just a matter of knowing how to consume the data to answer the analytics questions you would like to answer.

**Comment by Moofasax** [comment]
Thanks @sherifnada appreciate all the help you provide, i think we can close, sorry for the scope creep on this issue! For anyone interested, within [postgres you can drill into jsonb columns](https://www.postgresql.org/docs/10/functions-json.html) which helps us for some of our reporting!

Example:
```
SELECT * FROM public.issue_events
WHERE issue -> 'id' = 'issue_id';
```
