### ISSUE TITLE
KPI: Connector publish success rate (e2e)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28362]
We need the _official_ way to measure this for KPIs.

We should have an 'official' KPI dashboard for this.   We want to look at this per-day or per-week.

**Comment by evantahler** [comment]
Grooming notes:
* Data also in Data Dog! 
* Metabase/BQ - we should re-work table.

**Comment by alafanechere** [comment]
New charts with publish success rate added to this [dashboard]( https://airbyte.metabaseapp.com/dashboard/1029-connectors-ci-nightly-build-performance)

**Comment by evantahler** [comment]
also moved to https://airbyte.metabaseapp.com/dashboard/189-connector-operations-kpis
