### ISSUE TITLE
Improve error messages for connector configs

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28379]
How we handle an error message emitted on the FE for a bad connector input can be improved.  As an example, for the Facebook Marketing connector: 
![Screen Shot 2023-07-17 at 11 37 21 PM](https://github.com/airbytehq/airbyte/assets/38087517/e1095f16-765f-45b7-846a-09b412901c8b)

Some suggestions on how this could be improved: 
- Edit the error message so that it is human readable (don't reference "connectionConfiguration.insights_lookback_window", instead say "The Insights Lookback Window should be.."
- Set a max value on the field (so the user can't select a higher value than 28)

fyi @flash1293 @lmossman

**Comment by lmossman** [comment]
Thanks for creating this @nataliekwong, I'll try to get it groomed and in soon since this seems like some high-value low hanging fruit

**Comment by lmossman** [comment]
Proposed acceptance criteria:
- All error messages that contain a field's path will have that path removed (seems unnecessary to re-state the name of the field when the error is already attached to it

**Comment by nataliekwong** [comment]
Thank you @lmossman !!
