### ISSUE TITLE
Fix dest-bigquery gcs staging behavior

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28372]
two (possibly related) things:
* [getStagingRootPath](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/BigQueryGcsOperations.java#L62) is using the dataset ID, not the stream namespace. Raw tables are always written to the `airbyte` dataset, so two streams with the same name but different namespace might fight each other.
* If you run two instances of GCS staging DATs at the same time, one of them will delete the staging files of the other. (or at least, I've seen this happen. Didn't figure out why.)
  * best guess: the connector is deleting the entire stagingPath directory at the end of a sync. But I have no idea where that's actually happening. There's no `gs://airbyte-integration-test-destination-gcs/test_path` directory at all right now, which lends some credence to this theory...
    * but I tried creating `gs://destinationsv2-perf-testing/v2-gcs-staging/edgao_test.txt` while a sync was running, and it [still exists](https://console.cloud.google.com/storage/browser/_details/destinationsv2-perf-testing/v2-gcs-staging/edgao_test.txt;tab=live_object?project=destinationsv2-perf-testing) even after that sync completed

Once this is done, revert https://github.com/airbytehq/airbyte/pull/28520.

**Comment by evantahler** [comment]
cc @benmoriceau did your redshift fix to use UUIDs solve this?

**Comment by edgao** [comment]
https://github.com/airbytehq/airbyte/pull/30599 suggests that destination-bigquery is actually behaving fine... closing this issue until we get actual user reports of error
