### ISSUE TITLE
Airbyte enabling Basic Normalization though it is disabled when Custom Transformation support is added to a destination connector

### ISSUE THREAD

**Issue by SatishChGit** [airbytehq/airbyte#28388]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.6

### What step the error happened?

During the Sync

### Revelant information

I tried to add support only custom transformations for Teradata destination connector 0.1.1. Modified supportsDbt to true in both metadata.yaml and oss registry file. Normalization support was not added to Teradata destination connector. normalizationConfig is not defined in metadata.yaml and supportsNormalization is defined as false. But Airbyte is enabling/displaying Normalized tabular data option in UI along with Custom Transformations option even though normalization support is disabled.

### Relevant log output

```shell
oss registry used for this configuration 
https://github.com/SatishChGit/AirbyteEnv/blob/main/oss_registry.json and 
metadata.yaml file content of Teradata destination connector
data:
  connectorSubtype: database
  connectorType: destination
  definitionId: 58e6f9da-904e-11ed-a1eb-0242ac120002
  dockerImageTag: 0.1.1
  dockerRepository: airbyte/destination-teradata
  githubIssueLabel: destination-teradata
  icon: teradata.svg
  license: MIT
  name: Teradata Vantage
  registries:
    cloud:
      enabled: false
    oss:
      enabled: true
  releaseStage: alpha
  documentationUrl: https://docs.airbyte.com/integrations/destinations/teradata
  supportsDbt: true
  tags:
    - language:java
metadataSpecVersion: "1.0"
```

**Comment by evantahler** [comment]
Possibly related to https://github.com/airbytehq/airbyte/issues/28325

**Comment by evantahler** [comment]
@SatishChGit check out https://github.com/airbytehq/airbyte/issues/28325 - I was unable to reproduce this problem.  Can you confirm that in the database's actor_definition_version table for the latest teradata destination, all the normalization columns are null? 

Here's what I see now:

<img width="948" alt="Screenshot 2023-08-11 at 5 00 43 PM" src="https://github.com/airbytehq/airbyte/assets/303226/4434d405-aa4b-4a13-aed1-13e87380d15b">

I've confirmed in other destinations that these columns properly adjust the dbt and normalization behavior

**Comment by evantahler** [comment]
Either way, if you have a PR to enable just `supportsDbt=true`, let's merge it in!  
It would require a new connector version (also done in metadata.yaml + docs)

**Comment by SatishChGit** [comment]
> @SatishChGit check out #28325 - I was unable to reproduce this problem. Can you confirm that in the database's actor_definition_version table for the latest teradata destination, all the normalization columns are null and `supportsDbt` is true?
> 
> Here's what I see now:
> 
> <img alt="Screenshot 2023-08-11 at 5 00 43 PM" width="948" src="https://user-images.githubusercontent.com/303226/260171873-4434d405-aa4b-4a13-aed1-13e87380d15b.png">
> I've confirmed in other destinations that these columns properly adjust the dbt and normalization behavior
@evantahler this is screenshot when supportsDBT true. I initially configured normalization and dbt and later removed normalization config but this is not reflecting even with fresh gradle build and docker tag. 
![image](https://github.com/airbytehq/airbyte/assets/23031170/ee92dfa9-175a-48c3-8d51-ada62fefdeea)

I resetup airbyte environement and enabled only supportsDBT to true but this time all fields are null. Below is the screenshot of same. Not sure what's going wrong but anyway created PR for it.
![image](https://github.com/airbytehq/airbyte/assets/23031170/be4ed316-73b3-4bc8-a454-10d45d5ea7da)

**Comment by evantahler** [comment]
Can you try setting the normalization options to `null`?

**Comment by SatishChGit** [comment]
> I tried with null in metadata.yaml but no effect.  with manual update on supportsDbt  with true in table actor_definition_version, its working as expected.

**Comment by evantahler** [comment]
This should now be fixed
