### ISSUE TITLE
BigQuery start date different than Universal GA replication start date

### ISSUE THREAD

**Issue by jessica1023hsieh** [airbytehq/airbyte#28384]
### Connector Name

source-Universal google analytics, destination-bigquery

### Connector Version

0.50.7

### What step the error happened?

Other

### Revelant information

I connected Universal GA as my source and BigQuery as my destination. During the configuration process, I set replication date to 2023-07-01 and started the sync. However, the earliest date shown in my BigQuery data was 2023-06-29. I experimented several times, and the results were that the earliest date in BigQuery seemed to be 2 days earlier than the replication start date. Not sure if it was a bug, or probably time zone difference issue? Is there any way to resolve this issue? 
Thanks!

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This issue report a problem with multiple connectors. Please open an issue to a single connector.
