### ISSUE TITLE
T&D Queries should analyze less data where possible by only considering recently emitted rows

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28380]
Datawarehouses bill based on how much data is analyzed in the query.  If we can add more WHERE clauses to limit which rows are considered, that will help. 

See https://github.com/airbytehq/typing-and-deduping-sql/pull/23/files for some ideas of what to do.  Also, read this [slack thread](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1689364727121419).

Add a test case for this:
* a sync crashing and having un-typed data from a previous run

**Comment by edgao** [comment]
potentially relevant past issue about legacy normalization partition pruning https://github.com/airbytehq/airbyte/issues/14070

**Comment by evantahler** [comment]
^ tldr - save the results of `MAX(foo)` queries so we don't have to ask it over and over again

**Comment by edgao** [comment]
putting this down for now to focus on async standard inserts. there's a loose pr where I sketched out the interface diff (https://github.com/airbytehq/airbyte/pull/31191), but I didn't get time to modify/add any test cases for this.

**Comment by evantahler** [comment]
@edgao I think you started this story perhaps?
