### ISSUE TITLE
connectors-ci: PyYaml 0.5.4 is incompatible with Cython 3 -> broken connector build

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#28391]
Cython 3 was just released, an PyYaml 5.4.0 depends on Cython but is incompatible with Cython 3.
This leads to Python connector build error like: `AttributeError: cython_sources` on `pip install`.

PyYaml released a fix for compatibility with Cython 3 but its on a different major version (6) that has dependency conflict with `pyarrow`

## Solutions

A. Upgrade PyYaml to 6 in Airbyte CDK and fix the dependency conflict with PyArrow. Potential regression if some connector make direct use of PyYaml.
B. Patch the connector Dockerfile at build time to install Cython < 3.0 before the other dependencies.

**Comment by sryabkov** [comment]
> Cython 3 was just released, an PyYaml 0.5.4 depends on Cython but is incompatible with Cython 3.

Should be PyYaml 5.4, right?

**Comment by mfractal** [comment]
any updates on this ?

**Comment by bnchrch** [comment]
This has been resolved
