### ISSUE TITLE
Change Default Airbyte Internal Schema name and Allow Overrides

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#28403]
In the current Destinations V2 implementation, we have chosen the schema name `airbyte` as the schema we use for all of our "raw" tables. With some quick searches, we found the their are 36 cloud users who are already using that namespace for their final tables. We should make two changes:

1. change the default from `airbyte` to `airbyte_internal`
2. Add (back?) a spec option of the destination which allows this internal namespace to be overwritten.

**Comment by jbfbell** [comment]
If allowing overrides of the namespace adds significant effort, we should not do it now.

**Comment by edgao** [comment]
pausing pending raw table name discussion to avoid double-breaking the raw tables https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1690392744204789?thread_ts=1689634682.768709&cid=C04VDANQN7P
