### ISSUE TITLE
Update Destinations v2 Documentation to explain the airbyte internal namespace

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#28404]
Related to #28403 before we make Destinations V2 we should update our documentation to explain what the `airbyte_internal` namespace is and how people should interact with it.

Generally, people should not delete tables here or store unrelated tables here. It is meant to be our staging namespace.

We would expect some power users to use the raw tables for their own DBT transformations.

**Comment by evantahler** [comment]
Is what was added in https://docs.airbyte.com/understanding-airbyte/typing-deduping sufficent?
