### ISSUE TITLE
Determine if we need to handle table name prefix reservations in BQ

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28418]
And there's some new logic to handle unusual column name prefixes https://github.com/airbytehq/airbyte/blob/fa4a278a2d496e666ddb39325b1b219c48a464e9/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L54

TODO: 
* check on Cloud if there are real streams/columns using these prefixes.
* If there are less than 5 instances, ignore this story, but confirm that BQ will throw when creating a table with these bad prefixes
* If there are more than 5 instances, reimplement the python name mangling logic.

**Comment by edgao** [comment]
ran this query:
```sql
with streams as (
  select
    jsonb_array_elements(catalog -> 'streams') as stream_objects
  from connection
), column_names as (
  select
    jsonb_object_keys(stream_objects -> 'stream' -> 'json_schema' -> 'properties') column_name
  from streams
  where jsonb_typeof(stream_objects -> 'stream' -> 'json_schema' -> 'properties') = 'object'
)
select distinct column_name
from column_names
where
  lower(column_name) like '\_table\_%'
  or lower(column_name) like '\_file\_%'
  or lower(column_name) like '\_partition\_%'
  or lower(column_name) like '\_row_timestamp\_%'
  or lower(column_name) like '\_\_root\_\_%'
  or lower(column_name) like '\_colidentifier\_%'
```

returned no results. Removing the logic to handle these cases + writing a test to verify that we throw an error.

**Comment by edgao** [comment]
(I have no idea why there's a schema whose `properties` is not an object. problem for a different day)
