### ISSUE TITLE
[Spike] Start on destintaion-snowflake Destination V2

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28416]
* Features come from spreadsheet: https://docs.google.com/spreadsheets/d/1BqtlcUIaAMAMTqZAO5M__Zwdp7kPqiiQ2ITQYIwd72k/edit#gid=0
* Set up release/beta PR for DestinationsV2 toggle
* Keep a guide about how to move the next destination to V2

**Comment by edgao** [comment]
doc exists here, I'll continue editing it as I do more stuff https://docs.google.com/document/d/1O955bwB-W5q9ukX-yPyC-rVtLrTQgGtmQndbYJo2ePA/edit

**Comment by edgao** [comment]
snowflake 1s1t EA is released; closing
