### ISSUE TITLE
Ensure Pipeline Unit tests run on Pipeline change

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28426]
## Problem
Our unit tests are not run automatically

**Comment by alafanechere** [comment]
The unit test are here https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/tests/test_pipelines/__init__.py#L4
They're probably not up to date.
Coverage is low but it's not the scope of this issue to add more tests.
We'll add more unit tests in the future, as needed.
