### ISSUE TITLE
rename tap/target references in code to source/destination

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2842]
We have a lot of tap/target naming conventions left from early on. This would move us closer to using uniform naming schemes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368224207989) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I think the major outstanding offenders are just `StandardTapConfig` and `StandardTargetConfig`
