### ISSUE TITLE
Plan next phase of airbyte-ci

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28429]
## Problem
There is a few structural improvements we can make to our pipelines code base (ideas listed below).

There is also the `aircmd` util released by @cpdeethree we can consider using if we feel that it will address theses issues

## Outcome
We should decide next steps, likely via a small tech spec recommendation

### Pipeline Caching is hard to understand
What is cached? When? And Where?

Is there anything we can do about this?
**Possible Solution(s)**
1. Document the different caching levels (buildkit, cache volume, gradle cache)
2. The buildkit cache hits can be seen in the Dagger logs / UI
3. 

### Steps do not relate to results
In the code the results array and the steps ran are not directly related.

This leaves us open to subtle bugs where steps can silently skip, fail or succeed.

**Possible Solution(s)**
I believe we should tighten the coupling between PipelineContext, Step and StepResult.

We could assign the expected steps to run to the context with a “NOT RAN” status.
The functions running the test/publish pipeline would just call “run()” on the steps. 
Step.run() would assign a StepResult attribute to the Step object (success/failure/skip) and a StepStatus (“RAN”).
The reporting function would iterate through the Steps assigned to the context and their results to generate the report.

### You cannot run individual steps
When debugging a failing step, you cannot tell the airbyte-ci to run only one step in a pipeline

### Steps do not have a standard interface/type
There is no standard interface/type that defines how you construct a Step, evaluate it and the resulting return value.

This prevents composability and generalizing common/aggregate functions like logging

### Steps do not declare their dependencies
Barrier to running steps on their own.

Led to some error states not being found until late in the runtime which is expensive given these are long running programs

### Debugging and Tracing is difficult
We have a few patterns that work against us
1. Inheritance/Instantiation adds Indirection, which adds layers to hold in your head while debugging.
2. More than one successful exit state per function can make it hard to know when and in what state a function exited

**Possible Solution(s)**
1. Test results should be a view based on the step list
2. List of Steps should be able to be nested and dynamic
3. Results of previous step should be accessible by a step at runtime, the consuming step should be responsible for retrieving the values it needs. See Context Object Pattern
4. Have steps register an ID
5. 

Example taken from an Aircmd discussion
```py
steps = [
        Step(),
        [Step(), Step(), Step()]
        [Step(id="dockerImageCheck"), Step()]
        {runCondition: onFail(), pipeline: Step()}
        {runCondition: onFail(id="dockerImageCheck"), pipeline: Step()}
    ]

run_steps(dagger_client, steps)

class Step:
    id: str
    name: str
    runCondition: Optional[callable]

    def run(self, sibling_results = {}):
        some_prev_result = sibling_results["some_prev_step"]
        result = some_execute_function(some_prev_result)
        sibling_results[self.id] = result
        return sibling_results
    

def run_steps(dagger_client, steps):
    ran_steps = [eval_step(step, steps) for step in steps]
    return generate_reports(ran_steps)
```

**Comment by evantahler** [comment]
Done.
