### ISSUE TITLE
Error starting airbyte-temporal (Apple Silicon)

### ISSUE THREAD

**Issue by Noobzik** [airbytehq/airbyte#28462]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.8

### What step the error happened?

None

### Revelant information

Local deployment with an Apple Silicon device (Macbook pro M1 PRO)
Followed the local deployment guide : 
* clone the repository
* `cd airbyte`
* `git checkout v0.50.8`
* then run the `./run-ab-plateform.sh`

Docker : 
* Desktop version 4.20.1 (110738)
* Engine : 24.0.2
* Compose : v2.18.1
* Credential Helper : v0.7.0
* Kubernetes : v1.25.9

log link :
https://gist.github.com/Noobzik/ce8038c69a79f8cbd97447f5160e632a

**Comment by Noobzik** [comment]
The issue started from 0.50.8 and it is still here at 0.50.9

I have just tested with 0.50.7 and it runs fine.

**Comment by tom-haines** [comment]
@Noobzik I have same issue.
fyi the issue doesn't present on master branch (i.e. `wget https://raw.githubusercontent.com/airbytehq/airbyte/master/run-ab-platform.sh`).

**Comment by davinchia** [comment]
Please try on our latest version!
