### ISSUE TITLE
Source Postgres: normalization operation is performed after dbt custom transformations

### ISSUE THREAD

**Issue by axelwas** [airbytehq/airbyte#28463]
### Connector Name

source-postgres

### Connector Version

2.0.34

### What step the error happened?

During the sync

### Revelant information

We ingest data from a Postgresql database to Snowflake. Here's how we do it :

- data is loaded into Snowflake by Airbyte into a datalake database
- data is normalized by Airbyte
- normalized table is cloned into a warehouse database using a custom dbt transformation that calls a dbt macro

Everything works as expected 99% of the time.
However, for an unknown reason Airbyte randomly changes the order of operations and performs the dbt transformation before normalization, resulting in cloning old data into the warehouse database.

We have 27 Postgres - Snowflake connections synced daily and this issue occurred 5 times already.
To fix the issue we have to manually delete the connection and recreate it using octavia.

### Contribute

- [ ] Yes, I want to contribute

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated this feature](https://github.com/airbytehq/airbyte/discussions/34860).
