### ISSUE TITLE
SQL Server CDC

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2848]
Interested user in slack: https://airbytehq.slack.com/archives/C01A4CAP81L/p1615233737129300

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368100919677) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
blocked by 2021/06/18

**Comment by Phlair** [comment]
Implemented in #4689
