### ISSUE TITLE
Connection UIs assume 'active' jobs are always running

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#28523]
The move team has recently added backoff to job attempts when there are failures but progress is being made, creating a temporary pause in a job that the UI does not know how to handle. This state has been possible in a race condition, but very unlikely and either entirely missed or at least not reproducible.

It appears (based on page UI, not looking at data) that the job's status moves into `incomplete` 

This materializes on the status page as a Pending connection (perhaps with accompanying Pending stream statuses, but unsure if the connection I saw had per-stream status). It also manifests on Job History by showing the job as _Status Unknown_. Neither page indicates that the job is still being worked.

We (Ryan and I) believe the data on hand is enough to detect this state, job[status=incomplete], and should be represented to the user as running/in-progress. The connection sync/reset/cancel buttons should also reflect that a job is in-progress, allowing cancellation.

Requirements to resolve:
* [ ] update connection status's `isRunning` determination
* [ ] make Job History page aware of this condition and represent it better than the current `Unknown Status`
* [ ] Status page's connection & stream statuses may need some attention if they are in a Pending state - feels weird to have a Pending state with isRunning
* [ ] connection list table should show running state

**Comment by nataliekwong** [comment]
+1!

**Comment by tealjulia** [comment]
Refining notes:
- endpoints already have data we need
- testability: use e2e source "legacy exception after N" and set a number
- in incomplete state, show in progress on status page, connections list page, job history page
