### ISSUE TITLE
Move excluded connectors to LD feature flag

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#28547]
In https://github.com/airbytehq/airbyte-platform-internal/pull/7933 we introduced a way to hide connectors via LaunchDarkly.

This does the same thing as the fixed list checked into the frontend here:

https://github.com/airbytehq/airbyte-platform-internal/blob/a064a7afad7b47ee5400a2eb23e83a2479c8f2fc/oss/airbyte-webapp/src/core/domain/connector/constants.ts#L19-L40 

We should remove the list from the frontend, check if things still need to be hidden, and if so add them to the [feature flag](https://app.launchdarkly.com/default/production/features/connectors.hideActorDefinitionFromList/targeting).  Maybe we can also remove `area/connector/utils.ts`

Also, share that this change with the FE team.

**Comment by erohmensing** [comment]
We should also document this as the "canon way" of hiding connectors from end users in cloud!

**Comment by erohmensing** [comment]
LaunchDarkly rules: https://app.launchdarkly.com/default/production/features/connectors.hideActorDefinitionFromList/targeting

All of the destinations seem legit to still be excluded. Salesforce Singer... makes no sense. the other source is probably still fine to be there?

**Comment by evantahler** [comment]
Grooming: 

Dev: What's the point of feature flags?
Staging: Use the same feature flags as prod?

@erohmensing to check with FE chapter later this week.
