### ISSUE TITLE
Unable to Install airbyte version 0.39.36-alpha using helm

### ISSUE THREAD

**Issue by yash-ghelani-dsw** [airbytehq/airbyte#28555]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.39.36-alpha

### What step the error happened?

On deploy

### Revelant information

I was trying to shift airbyte version - 0.39.36-alpha from docker to kubernetes using helm chart, but it is facing issue in installing dependencies related to postgres version (bitnami postgres 10.x.x is not present). 

### Relevant log output

```shell
Downloading common from repo https://charts.bitnami.com/bitnami
Save error occurred:  could not find : no matching version
Error: could not find : no matching version
```

**Comment by davinchia** [comment]
Please try again with the latest version!
