### ISSUE TITLE
FE hook to check permissions

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#28571]
From the Q3A planning doc: 

> Create frontend utility for checking roles at different scopes (instance, org, workspace) and levels (admin, editor, reader)
The API to power this utility will need to be mocked until the backend exists

**Comment by tealjulia** [comment]
Refining notes:
- @chandlerprall has a doc started here (link)

**Comment by josephkmh** [comment]
`useIntent()` is now merged 🎉
