### ISSUE TITLE
StreamDetailsPanel performance issues with streams that have many columns

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#28574]
customer issue captured here: https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1689954465149749

When there are a lot of fields, interacting with streams in the StreamDetailsPanel becomes unmanageable.

One part of a solution might be a filter similar to how we filter streams in the main SyncCatalog.  Another solution might include table virtualization.

**Comment by tealjulia** [comment]
Refining notes:
- let's see what filtering alone gets us
- may be some DOM cleanup that can happen in here too

**Comment by josephkmh** [comment]
Refining notes:
- RHF migration will probably not help this issue, but the migration is ongoing
- We could try virtualizing this table and seeing if that helps
- We should also virtualize the streams list, as there are performance issues there (e.g. with Salesforce)
