### ISSUE TITLE
Point the "See instructions on how to install <integration>" to the right URL

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#286]
## Tell us about the problem you're trying to solve
![Screen Shot 2020-09-15 at 9 03 50 AM](https://user-images.githubusercontent.com/6246757/93235493-803b0b00-f732-11ea-956d-484a62c7c2e5.png)

The URL in the screenshot should point to `docs.dataline.io` instead of `dataline.io`

**Comment by michel-tricot** [comment]
@sherifnada I don't think this PR closes the issue. what we actually want here is the link to the integration page.

**Comment by sherifnada** [comment]
Discussed offline. The ideal end state is: 
1. This anchor points to the exact URL of the documentation instead of `docs.dataline.io`
1. If the link is broken, the user is redirected to `docs.dataline.io`
1. Eventually, we should have a linter that detects broken docs links

**Comment by cgardens** [comment]
I'm closing this. Integrations that have documentation now use the link in the UI. No linting for invalid links and no handling of of broken links.
