### ISSUE TITLE
Destinations v2: Snowflake: Think about identifier quoting

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28638]
Snowflake treats quoted and unquoted identifiers differently:
* `CREATE TABLE foo` - `foo` is case-insensitive, and treated internally as `FOO`. You can query as `SELECT * FROM FOO`, `SELECT * FROM Foo`, `SELECT * FROM foo`, etc.
* `CREATE TABLE "foo"` - `foo` is case-sensitive. `SELECT * FROM foo` throws an error. You _must_ query with quotes: `SELECT * FROM "foo"`.
* `CREATE TABLE "FOO"` - identical behavior to unquoted

Column names behave similarly:
* `CREATE TABLE ... (id INTEGER)` - `SELECT id`, `SELECT ID`, `SELECT Id`, etc. are all valid
* `CREATE TABLE ... ("id" INTEGER)` - you _must_ use `SELECT "id"`
* `CREATE TABLE ... ("ID" INTEGER)` - identical behavior to unquoted

Legacy normalization is using unquoted identifiers. Do we want to keep that behavior?

If yes:
* Revert the RecordDIffer changes in https://github.com/airbytehq/airbyte/pull/28618/files#diff-746815fa1e930704a59cc0fffbb0486f2b4cc3b2f5f1a1ab1f27b9ef926c2121
* RecordDiffer should handle up/downcased column names
* what should we do about column name collisions? (maybe check how normalization handles this?)

If no: (WE CHOSE THIS)
* document this for snowflake beta users

**Comment by evantahler** [comment]
Grooming:
1. See if there are snowflake docs with a best-practice telling us what to do
2. if not, we voted /slightly/ for quotes + case-sensitivity.  Why?
  * won't loose data (e.g foo and FOO columns exist)
  * closely matches the source better
  * matches what BQ does

**Comment by edgao** [comment]
added notes in https://www.notion.so/Database-Facts-4a68926d3acf46d2a65890f60f767472?pvs=4#926b79634db448b19da90c9a0abf89cd
