### ISSUE TITLE
Destinations v2: Snowflake: RecordDiffer should ignore timestamp precision

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28636]
Snowflake returns all timestamps with microseconds precision (`1970-01-01T00:00:01.000000Z`), but our expected_records are just using seconds precision (`1970-01-01T00:00:01Z`). Figure out how to make this situation happier.

ideas:
* TypingDedupingTest implementations can mutate expected records?
* RecordDiffer becomes schema-aware, and parses timestamp columns? (+ date/time/number/etc)
* Override expected_records per destination?
* ??

**Comment by evantahler** [comment]
Grooming:
* This is a change to the DAT framework
* Override expected_records per destination seems like a great idea - so we can visualize each destination's output (snapshot test)

**Comment by edgao** [comment]
done in https://github.com/airbytehq/airbyte/pull/28752 and https://github.com/airbytehq/airbyte/pull/28677/commits/18a651d5b1b056af5623943c92aed1f23ab0e909
