### ISSUE TITLE
[destination-databricks] Incorrect argument order

### ISSUE THREAD

**Issue by igsaf2** [airbytehq/airbyte#28642]
### Connector Name

destination-databricks

### Connector Version

1.1.0

### What step the error happened?

Configuring a new connector

### Revelant information

![image](https://github.com/airbytehq/airbyte/assets/125440361/b5f0bf94-fc5d-4a5d-879f-2bda8ac1ed77)

https://github.com/airbytehq/airbyte/blob/e53034921ebdf406a05a449f9838ada9500c8a01/airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/DatabricksDestinationConfig.java#L20

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
