### ISSUE TITLE
Universal analytics replication end date

### ISSUE THREAD

**Issue by jessica1023hsieh** [airbytehq/airbyte#28650]
### Topic

universal analytics replication date

### Revelant information

Airbyte is able to configure the replication start day, however, I could not find a place to configure the end date. I think the system automatically set the end date as today. Is it able to customize the report date range?

**Comment by marcosmarxm** [comment]
Please use correct template. This is a [connector bug](https://github.com/airbytehq/airbyte/issues/new?assignees=&labels=type%2Fbug%2Carea%2Fconnectors%2Cneeds-triage&projects=&template=1-issue-connector.yaml)
