### ISSUE TITLE
Universal analytics limitation

### ISSUE THREAD

**Issue by jessica1023hsieh** [airbytehq/airbyte#28652]
### Topic

Universal analytics limitation

### Revelant information

Does anyone know if universal analytics has any limitations when exporting to bigquery via airbyte? Like time, or data size, or number of rows limitations?
Because using google sheet add ons to run the reports in UA has a limitation of 10 million cells, so I am trying to export them through airbyte.

**Comment by marcosmarxm** [comment]
Please use correct template. This is a [connector bug](https://github.com/airbytehq/airbyte/issues/new?assignees=&labels=type%2Fbug%2Carea%2Fconnectors%2Cneeds-triage&projects=&template=1-issue-connector.yaml)
