### ISSUE TITLE
Don't build all connectors by default when running ./gradlew build

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2865]
## Tell us about the problem you're trying to solve
If a connector has an esoteric dependency as in #2340 then a user building Airbyte core should not have to worry about it, unless they are specifically developing on that connector. Currently `./gradlew build` builds connectors by default unless the `CORE_ONLY` flag is passed like so: `CORE_ONLY=true ./gradlew build` in which case only the core module is built. See `settings.gradle` for how its used. To see usages of `CORE_ONLY` grep the codebase. 

## Describe the solution you’d like
I would like to invert the behavior of `./gradlew build` in `settings.gradle` such that `CORE_ONLY=true` is the default, and instead use differently named env flag like `BUILD_ALL` to build everything including connectors.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368224595681) by [Unito](https://www.unito.io)

**Comment by noahkawasakigoogle** [comment]
I gave this a shot here: https://github.com/airbytehq/airbyte/pull/9368/files

Was not as straight forward as I initially thought it would be, requires a bit of a hack to invert the behavior but _also_ add the ability to target a specific connector Gradle project without also including all the other connectors.
