### ISSUE TITLE
Source Zendesk Support: Rate Limit 429 after page 101

### ISSUE THREAD

**Issue by nazifishrak** [airbytehq/airbyte#28653]
### Topic

Zendesk Rate Limit Reach

### Revelant information

Here is the log file. Can anyone guide what can I do to fix this?
[cdn.fbsbx.com_v_t59.2708-21_363484258_820677993068507_8315624097524355775_n.txt_8d411951_e0a2_4d4c_a0a6_0e4604b17ccc_job_110_attempt_1_txt.txt__nc_cat=104&ccb=1-7&_nc_sid=0cab14&_nc_ohc=xzA_cKcuixMAX9r3QLx&_nc_ht=cdn.fbsbx.com&oh=03_AdRxxN5seiicwte6en.txt](https://github.com/airbytehq/airbyte/files/12158083/cdn.fbsbx.com_v_t59.2708-21_363484258_820677993068507_8315624097524355775_n.txt_8d411951_e0a2_4d4c_a0a6_0e4604b17ccc_job_110_attempt_1_txt.txt__nc_cat.104.ccb.1-7._nc_sid.0cab14._nc_ohc.xzA_cKcuixMAX9r3QLx._nc_ht.cdn.fbsbx.com.oh.03_AdRxxN5seiicwte6en.txt)

**Comment by marcosmarxm** [comment]
@nazifishrak I'm closing this issue. Use [bug report](https://github.com/airbytehq/airbyte/issues/new?assignees=&labels=type%2Fbug%2Carea%2Fconnectors%2Cneeds-triage&projects=&template=1-issue-connector.yaml) one.
