### ISSUE TITLE
Source Stripe: OOM exception

### ISSUE THREAD

**Issue by davydov-d** [airbytehq/airbyte#28654]
A couple of syncs failed due to 137 error (OOM) for this connection:
https://cloud.airbyte.com/workspaces/6ddc9e0a-b53b-4a72-8acc-52ab0c8b3286/connections/9b861a3f-1275-4f6f-b841-03b1dec21a6c/job-history

Need to investigate and fix

**Comment by davydov-d** [comment]
@amaliaroye I'm investigating a failed connection which is a cause of a low first sync success rate metric. I see this connection has self healed but also, the source connector config had been updated between the failed and successful syncs which, very likely, is the key to healing the sync. May I ask you to contact the user and ask what specifically was changed in the config? thanks!

cc @erica-airbyte

**Comment by erica-airbyte** [comment]
@amaliaroye let me know if you have the bandwidth to tackle this outreach

**Comment by amaliaroye** [comment]
@davydov-d Reached out to the user, I'll let you know once I hear back!

**Comment by amaliaroye** [comment]
@davydov-d The user got back to me and said they reached out to support and @jnr0790 bumped up the memory to the max after trying a couple of times. It's currently at 8gb (on this tracking list, it's the third to the bottom)

They said they may have adjusted the lookback window from 28 to 7, as well, but it seems likely the memory bump was what fixed this

**Comment by davydov-d** [comment]
@amaliaroye thank you!

**Comment by davydov-d** [comment]
Could not reproduce this issue using customer's config, catalog and connector version. The most resident set size I had during the sync was ~65MB (python, not docker). This does not seem to be out of ordinary bounds. Closing the issue for now, will reopen if it occurs again.
