### ISSUE TITLE
Connector version override creation and visibility improvements

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#28678]
Overrides are getting a ton of use, which is great, but comes with some painpoints:

On creation:
1. Multiple ways of configuring things in launch darkly and the button to add new being at the bottom of the page can lead to folks configuring overrides in the wrong spot.
2. Ergonomics of having to set up a variation before the rule isn't great.
3. We want to enforce writing who / why / what we're overriding in description/comment fields for tracking.
4. Ordering is important (more general rules need to come after more specific rules), which gets harder to deal with with so many rule.
5. Not all context kinds are supported, but LD lets you configure it even though it wont work (e.g. setting up an override for Connection context)

On visibility:
1. Having so many overrides, it's hard to find the versions in use
2. 

## Potential solutions

- We can use terraform to configure the overrides. This will give us tracking and a specific way to configure things. 
- Set up a Retool frontend to controll this

**Comment by evantahler** [comment]
A great doc from @nataliekwong is [here](https://docs.google.com/document/d/1GNZyRacvNY1nZ1t6Y-_zR0pwbzoS3TtFi-uQfjz4fY4/edit)

**Comment by pedroslopez** [comment]
See epic https://github.com/airbytehq/airbyte/issues/32938
