### ISSUE TITLE
Modify default "Detect and Propagate schema changes" to "Propagate all changes"

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28676]
There was some confusion between myself and Alex G when we discussed the rollout of the "Detect and Propagate schema changes" feature.

For all new connections, the default should be "Propagate all changes".

Slack thread: https://airbytehq-team.slack.com/archives/C052L0PSYJV/p1690303015941629

**Comment by nataliekwong** [comment]
@mfsiega-airbyte Saw this was moved to Icebox - are we blocked or waiting on anything to make this change? (I thought this was a FE change, but would it be BE?)

**Comment by nataliekwong** [comment]
Thanks! Will wait for @malikdiarra to return to clarify next steps.

**Comment by nataliekwong** [comment]
Chatted with @malikdiarra today, and we're in agreement to move forward with the new default. @josephkmh I had originally labelled this with area/frontend - is it both BE and FE?

**Comment by josephkmh** [comment]
I think this is only a FE change. We just want this dropdown to default to `Propagate all chages`, correct?

![image](https://github.com/airbytehq/airbyte/assets/7550957/c7068e0c-fc02-4c3a-8d06-d1a69e2f0643)

**Comment by nataliekwong** [comment]
@josephkmh Yep, that's right - users pick 'fully' more often than 'column changes only' 

Would API-created connections still default to 'ignore'?

**Comment by josephkmh** [comment]
Correct, this will not change anything about API-created connections. That would require a BE change (probably an equally trivial one).

**Comment by nataliekwong** [comment]
@josephkmh Support recommended we set the default to "Propagate column changes only", since people aren't aware of increasing costs from new streams. Could we modify the default to that option instead? 

Sorry for the double work :(

**Comment by nataliekwong** [comment]
Could we also edit the tooltip for this field?
> Automatically reflect source schema changes in your destination. Propagating all changes will incur costs for new streams.
