### ISSUE TITLE
[Spike] Determine at what size (data volume) Destinations V2 is more expensive than old normalization

### ISSUE THREAD

**Issue by Hesperide** [airbytehq/airbyte#28680]
Assumption: 
* DestV2 is more expensive than legacy normalization especially for large syncs.
* The reason for this is because we run T&D frequently during the sync (currently every 15 minutes).
* Customers are possibly unhappy because their huge Postgres -> BigQuery syncs are more expensive now.
 
The value of incremental T&D can be broken into:
1. Seeing a sample of the data in your destination early. This gives you reassurance that Airbyte is actually working, and maybe allows you to start writing your dbt transformations.
2. Checking the progress of your sync. You can check your destination and see progress in terms of how many records were synced.
3. If there's an issue with T&D (shouldn't be frequent), it happens earlier, instead of at the end of your sync.

Even if we were to do T&D twice (once after 15 minutes, once at the end), we would still get most of the benefits of (1) and (3). Should we:
* Test the other extreme?
* Leave as is?
* T&D less frequently for initial snapshots?

**Comment by evantahler** [comment]
Grooming:
* we will do

**Comment by evantahler** [comment]
We need to get better numbers, and will be working on that next week.  But the rough way to think about it is:
* We are saving money by not making or dealing with SCD tables (and better queries)
* We are spending money by doing type&dedupe more often (every 15 minutes vs once at the end of the sync)
* We have some optimization ideas for the queries which we want to do first.  They won't solve the problem, but will make it less severe

So, as the sync time increases there's some point when the new spend outweighs the savings.  We need to figure out where that inflection point is.

The good news is that this won't be a fundamental change if we learn that inflection point is "early" - we'll either:
* give users an option how often to type&dedupe ([once, every hour, every 15 min, etc]
* decouple checkpointing from type&dedupe - we wanted checkpointing to correlate with "data appears in its final format (e.g. final tables)" but we can revisit that if it feels too expensive.
