### ISSUE TITLE
[Roadmap] 🔌 Source MySQL to Certified

### ISSUE THREAD

**Issue by Hesperide** [airbytehq/airbyte#28681]
##  Announcing General Availability of Airbyte’s MySQL Database Connector

We're thrilled to bring you a host of robust updates to our MySQL source connector. These changes significantly augment its scalability and reliability, especially for large databases:
* Unlimited Size Initial Snapshots: We're introducing support for syncing MySQL tables larger than 1 TB. This means no matter how large your MySQL database is, Airbyte has you covered.
* Change Data Capture (CDC) as Default: We’ve found that CDC is the most accessible and reliable method of maintaining an up-to-date copy of your MySQL tables. We've also refined our capacity to handle large incremental updates to your tables. CDC will now be the default chosen method of updating your data for new connections.

Behind the scenes, these changes close the gap with our most reliable database source, Postgres. Reliable initial snapshots of > 1 TB tables require [checkpointing sync state](https://docs.airbyte.com/understanding-airbyte/airbyte-protocol/#state--checkpointing), chunking read size and intelligent retries. Similarly, large incremental updates need this logic to guarantee data freshness in your data warehouse. Together, your syncs are now always resumable, and shielded against network hiccups that can arise when syncing massive data volumes.

These updates represent a significant stride forward in our mission to provide the most user-friendly, scalable, and reliable data integration platform. We're excited for you to experience these upgrades!

______

Looking ahead, we're planning further improvements to our MySQL connector, directly influenced by your feedback and open GitHub issues:
* Replicating MySQL tables on Amazon Aurora: You’ve shared that replicating MySQL workloads deployed on Amazon Aurora can be more challenging. We're committed to enhancing this to match the reliability of replicating MySQL tables hosted on other platforms.
* Selectable Sync Start Dates: We're aware of your interest in choosing start dates for MySQL syncs, particularly for extensive databases covering multiple years of data. We're keeping an eye on this - if large syncs failed before and this is why you wanted this feature, we invite you to try syncing these datasets again with our newly improved MySQL connector.

Stay connected for more updates!

**Comment by ifun248** [comment]
Hi Hesperide, I have a question ref https://github.com/airbytehq/airbyte/issues/28968 before marking Souce MySQL to GA. Thanks to Airbyte team.

**Comment by dduran28** [comment]
Hi @Hesperide & @prateekmukhedkar Is it still planned for this to be released this quarter?

**Comment by prateekmukhedkar** [comment]
@dduran28 yes, and you can already try out the latest version of MySQL source connector that have these improvements related to Unlimited size initial snapshots. Announcement coming very soon!
