### ISSUE TITLE
Possibility to copy existing source/destination configurations

### ISSUE THREAD

**Issue by saynomoo** [airbytehq/airbyte#2868]
## Tell us about the problem you're trying to solve
When adding a new connection to an existing destination that has slightly different configuration variables (In my case big query dataset id), you need to create a completely new destination. That means that you have to get all the possible tokens again, which would actually be readily available in airbyte configs. 

## Describe the solution you’d like
I'd like to be able to browse existing connections, and create a copy of existing sources and destinations. A simple copy button on the configuration tab would do it

## Describe the alternative you’ve considered or used
AFAIK, the only viable alternative is currently to create a new destination from scratch.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101123336) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
related to https://github.com/airbytehq/airbyte/issues/2657

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/9296

**Comment by timroes** [comment]
@JustGitting This feature has not been added yet. Due to some issue management, the "duplicate issue above" ended up being private, sorry for that, so my comments there were not visible here: We decided to close it since we have no plans for the near term future of adding this feature, since there hasn't been any reasonable high enough demand and we've been focusing on other work. In terms of keeping our issues manageable it was closed therefore.

**Comment by JustGitting** [comment]
Thanks for the update @timroes.

I'd love to have this feature! 

I just had to manually add a dozen source connectors for a collection of CSV files... it was a bit tedious. :roll_eyes:

**Comment by eugenekim-orrum** [comment]
Also requesting exactly for the same reason.

**Comment by JacekHebda** [comment]
Requesting the same. It is absolutely crucial for efficient work

**Comment by mabodo** [comment]
+1

**Comment by mabodo** [comment]
Main problem here on is on re-authenticate every source. 
If at least authenitifcations would be it's own object (similar to what happens within zapier) that you can re-share work would be much faster

**Comment by caileyfitzgerald** [comment]
Agreed! This would make my work so much easier!

**Comment by pepina-rouvy** [comment]
+1

**Comment by matblissim** [comment]
would love to be able to duplicate sources  . managing a lot of countries and each country has its own DB.

**Comment by snorrehu** [comment]
Also requesting!!

**Comment by jrbarkin** [comment]
Would be very helpful, perhaps even a template system.
