### ISSUE TITLE
Determine the correct primary key field when the primary key is a composite index

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#28699]

**Comment by akashkulk** [comment]
MySQL can have composite primary keys, which can be created as follows : 
```CREATE TABLE employees (
    department_id INT,
    employee_id INT,
    name VARCHAR(50),
    PRIMARY KEY (department_id, employee_id)
);```

**Comment by akashkulk** [comment]
While [building](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-jdbc/src/main/java/io/airbyte/integrations/source/jdbc/AbstractJdbcSource.java#L271) the list of primary keys in `AbstractJdbcSource`, we use the getPrimaryKeys [method](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys-java.lang.String-java.lang.String-java.lang.String-). We need to modify this code to sort the list returned by this method by `KEY_SEQUENCE_NUMBER` and not by `COLUMN_NAME`, which is the default

**Comment by prateekmukhedkar** [comment]
Notes from backlog grooming on 8/2 - edge case, addressed after GA.
