### ISSUE TITLE
Update docs for using a custom remote catalog

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#28702]
We should update the instructions at https://docs.airbyte.com/connector-development/testing-connectors/testing-a-local-catalog-in-development/ since in https://github.com/airbytehq/airbyte-platform-internal/pull/7995 we removed the `REMOTE_CONNECTOR_CATALOG_URL` env var in favor of `CONNECTOR_REGISTRY_BASE_URL`.

It should reflect that you need a specific directory structure in whatever url you give it that mimics the way our registry is set up (e.g. at least `/files/registries/v0/oss_registry.json` for the full registry`)

**Comment by evantahler** [comment]
Grooming: 
* remove public docs, move to notion
* do the update to the docs (above) + difference in behavior (you need all the registry entries files in the whole registry, path structure from base URL).  e.g. you need a full registry now. 
*
