### ISSUE TITLE
Show "Records read" and "Records written" in Job History

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28732]
Jobs currently list "records emitted" and "records committed". This can be modified to be more human-readable for users: 

- Records emitted -> Records Read
- Records committed -> Records written

<img width="1323" alt="Screen Shot 2023-07-26 at 3 06 09 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/c47aad98-ac99-4adf-984d-7160f1951838">

This was chosen as the verbiage originally because of the way we think about the orchestrator - sharing an explanation from Parker (Slack thread here: https://airbytehq-team.slack.com/archives/C02UR8ZMV8R/p1648854668740049): 

> So a record is counted as ‘emitted’ as soon as a message is sent from the source to the platform orchestrator process. A record is ‘committed’ once the destination has received the record from the platform orchestrator and successfully persisted it to permanent storage. If a destination is unreachable, but the source is able to send records to the platform orchestrator, the ‘emitted’ record count can be very high while the ‘committed’ record count may be zero, for instance

Supporting documentation here: https://docs.airbyte.com/cloud/managing-airbyte-cloud/review-sync-summary/

Note: Competitors call this "Extract" and "Load" [link](https://fivetran.com/docs/getting-started/syncoverview)

**Comment by josephkmh** [comment]
Refining notes:
- Maybe "Extract" and "Load" are more widely recognized terms for "Read" and "Written"? Joey will open a Slack thread to get feedback
