### ISSUE TITLE
Reflect Partial Success as a job outcome

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#28740]
We will start to charge for partially successful syncs, and should define them differently in the UI so that it's clear this is not a failure or success.

Example:
<img width="1339" alt="Screen Shot 2023-07-26 at 6 53 34 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/d5cc352a-23f3-4283-a9e1-5476a1b638aa">

Suggestion: Change the header of this job to be "Sync Partially Succeeded". 

Example Link: https://cloud.airbyte.com/workspaces/40c277bb-2120-45ae-aacd-dc2dfdf7a365/connections/45b6d3e9-e87c-46ec-8ea7-779fd39f6c9c/job-history#2070628::2

**Comment by josephkmh** [comment]
Refining notes:
- We have `AttemptFailureSummary.partialSuccess` which tells us if any records are committed
- Maybe it would look better with grey text instead of read (optional)
