### ISSUE TITLE
deduping on a float column fails on bigquery 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2879]
## Expected Behavior
I expect the append dedupe sync mode to work correctly when the column being deduped is a float. 

## Current Behavior
A sync from PG to BQ seems to break on Airbyte 0.19.0-alpha. 

## Logs
[logs-failed_incr.txt](https://github.com/airbytehq/airbyte/files/6307307/logs-failed_incr.txt)

## Steps to Reproduce
TBD

## Severity of the bug for you
medium

## Airbyte Version
found in the logs

## Connector Version (if applicable)
found in the logs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101500294) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
This is related to https://github.com/airbytehq/airbyte/issues/2684 and should be fixed in 0.20.0.

I'll add another fix for edge cases in the next release with #2941 too (fails if the column chosen as primary key is being quoted)
