### ISSUE TITLE
Transient build errors should be retried

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#28796]
Errors like `failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": EOF` and `failed to load cache key: Get "https://dtdg.co/latest-java-tracer": stream error: stream ID 3; INTERNAL_ERROR; received from peer` should not cause builds or connector tests to fail.  We should sleep for a few seconds and try again, up to 5 times.

Some examples:
* https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1690451195/9cee15b4db7988ceb7e9bbd4b85bcc26fface76e/destination-redshift/0.6.1/output.html
* https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1690451195/9cee15b4db7988ceb7e9bbd4b85bcc26fface76e/destination-bigquery/1.5.8/output.html

**Comment by pedroslopez** [comment]
Could also look into this one from Sentry as part of this https://airbytehq.sentry.io/issues/4345060727/?project=4505596642983936
