### ISSUE TITLE
Final T+D should run in parallel

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#28812]
At the end of a sync, we execute a round of T+D for every stream. This currently happens in series. That's pointlessly slow. We should run those concurrently.

`DeafultTyperDeduper.commitFinalTables` should also be parallelized.

This is especially visible when resetting a connection with >10 streams - v2 takes a long time to do what should be a very quick operation.

**Comment by evantahler** [comment]
Related slack thread https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1693420008032499

Looking at timing:
* The source ended `2023-08-30 01:06:25 source > INFO i.a.i.s.p.PostgresSourceStrictEncrypt(main):71 completed source: class io.airbyte.integrations.source.postgres_strict_encrypt.PostgresSourceStrictEncrypt`
* The final T&D Starts: `2023-08-30 01:06:38 destination > INFO i.a.i.d.b.t.BigQueryDestinationHandler(execute):56 Executing sql 026d8293-dbc5-414a-a48c-5f40da33a022`
* The final T&D ends: `2023-08-30 01:38:44 destination > INFO i.a.i.d.b.t.BigQueryDestinationHandler(execute):71 Root-level job 1f1e5239-0145-41f3-8065-5a5aa70abfdf completed in 15595 ms; processed 1510660 bytes; billed for 73400320 bytes`

So the final T&D took 32 minutes
It used to take less than 10

**Comment by evantahler** [comment]
cc @tybernstein

**Comment by edgao** [comment]
This shipped in https://github.com/airbytehq/airbyte/pull/30020 (destination-bigquery 2.0.5, destination-snowflake 3.1.2). Thanks @jbfbell !
