### ISSUE TITLE
Source MongoDB: CDC/Log based replication

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#2881]
## Tell us about the problem you're trying to solve
Periodic  MongoDB database replication without full syncs and relying on replication keys 

## Describe the solution you’d like
It would be great to add MongoDB change streams support to the existing MongoDB source. https://docs.mongodb.com/manual/changeStreams/

## Describe the alternative you’ve considered or used
Replication key based syncs but it has certain schema requirements, which is not always convenient.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368159918076) by [Unito](https://www.unito.io)

**Comment by beeshalrizal** [comment]
Just a bit of add-on for this point:

**Tell us about the problem you're trying to solve**
Understand how certain objects in MongoDB change over time, meaning every update is captured and appended to our destination.
Using change streams would be ideal here as there are scenario's/use cases where there is no specific key (e.g. updated_at) that may have changed in the source database, even though the underlying data did change. This causes drift between the source and destination.

**Describe the solution you’d like**
It would be great to add MongoDB change streams support to the existing MongoDB source. https://docs.mongodb.com/manual/changeStreams/

**Describe the alternative you’ve considered or used**
Replication based on certain key's such as an updated_at field, however we found drift between the source and sink as described above.
Stitch + Fivetran can both consume the change stream / op log.
