### ISSUE TITLE
Source Google Analytics (universal): UA replication end date

### ISSUE THREAD

**Issue by jessicahsieh1023** [airbytehq/airbyte#28818]
### Connector Name

universal analytics

### Connector Version

0.2.63

### What step the error happened?

Configuring a new connector

### Revelant information

Airbyte is able to configure the replication start day, however, I could not find a place to configure the end date. I think the system automatically set the end date as today. Is it able to customize the report date range?

### Contribute

- [ ] Yes, I want to contribute

**Comment by hukedd** [comment]
same as my issue https://github.com/airbytehq/airbyte/issues/27661 but this one is more concisely written.

If this issue is being handled here, maybe mine could be closed to avoid noise?

**Comment by girarda** [comment]
closing as the UA connector is being deprecated
