### ISSUE TITLE
Airbyte worker 0.51.0 does not exist for real but is in the docker registry

### ISSUE THREAD

**Issue by vr** [airbytehq/airbyte#28825]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.11

### What step the error happened?

None

### Revelant information

you need to delete airbyte/worker:0.51.0 in the registry because renovate think it is the latest and it is not.

**Comment by alberttwong** [comment]
what worked for me to delete all the local generated config files and then run `./run-ab-platform.sh` again.

```
found docker-compose.yaml locally!
found docker-compose.debug.yaml locally!
found .env locally!
found .env.dev locally!
found flags.yml locally!
found temporal/dynamicconfig/development.yaml locally!
Loading Shell Variables from .env...
Loading Shell Variables from .env.dev...
```

**Comment by marcosmarxm** [comment]
The newest platform version doesn't have this issue. Please update to the latest version.
