### ISSUE TITLE
Destination Postgres: allow to specify tablespace

### ISSUE THREAD

**Issue by ggam** [airbytehq/airbyte#28838]
### What area the feature impact?

Connectors

### Revelant Information

I want to separete raw data from reporting tables in differente storage devices. For that I have two tablespaces, but I can't tell Airbyte other than the default.

It'd be very useful if I could specify the tablespace for all tables at destination level (don't need to do it at stream level). My use case is Postgres specifically but I guess this would also work for the other databases.

As a workaround, one can set the default tablespace for the AIrbyte user:
```
alter role <airbyte_user> set default_tablespace to '<specific tablespace>';
```

**Comment by evantahler** [comment]
This will be happening as part of [1-stream,1-table](https://github.com/airbytehq/airbyte/pull/27845)!  Raw tables will be moved to a new schema.

**Comment by ggam** [comment]
Note that I'm not talking about schemas but tablespaces (https://www.postgresql.org/docs/current/manage-ag-tablespaces.html)

Anyway, I see this issue is a duplicate of https://github.com/airbytehq/airbyte/issues/28838 so it's fine to keep it closed.
