### ISSUE TITLE
Facing problem with deploy airbyte on AWS EKS

### ISSUE THREAD

**Issue by rajatariya21** [airbytehq/airbyte#2884]
Hi,
I had tried to deploy airbyte on eks cluster but I was not able to deploy it.
I was able to create aws eks by eksctl cli command according to airbyte document.
But when run this command:
**kubectl apply -k kube/overlays/stable**

I got following error.
**error: absolute path error in 'kube/overlays/stable' : evalsymlink failure on 'kube/overlays/stable' : lstat /home/rajesh/airbyte/kube: no such file or directory**

Please suggest me what am I doing wrong?

**Comment by rajatariya21** [comment]
Now I am facing following issue while run this command: **kubectl apply -k kube/overlays/stable**
**error: json: unknown field "envs"**
I have installed kustomize version 4.0.5.

What is problem that I am got above error?

**Comment by jrhizor** [comment]
Looks like this may be related to https://github.com/airbytehq/airbyte/pull/2854

What kubectl version are you on?

**Comment by rajatariya21** [comment]
I am using kubectl version 1.18.19.

**Comment by jrhizor** [comment]
If you change your local files to revert https://github.com/airbytehq/airbyte/pull/2854/files by using `env: .env` instead of
```
    envs: 
      - .env
```
does it work for you?

**Comment by rajatariya21** [comment]
Thanks @jrhizor for your suggestion.
Execute kustomization.yaml file by following command and airbyte deployed successfully.
kustomize build |  kubectl apply -f -
