### ISSUE TITLE
klaviyo

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28867]

**Comment by topefolorunso** [comment]
Hi @RealChrisSean! Please assign this to me. I'd like to work on this for the hackathon.

**Comment by RealChrisSean** [comment]
This has been assigned to you :). Good luck!

**Comment by marcosmarxm** [comment]
Not possible to migrate Klaviyo to lowcode because it needs a Custom Check function not supported by the lowcode framework today.
