### ISSUE TITLE
source github: pull_requests stream only runs incremental syncs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2886]
## Expected Behavior
the pull_requests stream seems to be running in incremental mode even though it is only configurable as full_refresh. we should: 

1. verify if the stream runs as full refresh or incremental
2. output the correct sync mode from the catalog

below is a screenshot of 3 successive syncs from the github source

![Screen Shot 2021-04-14 at 9 04 41 AM](https://user-images.githubusercontent.com/6246757/114742298-75644b00-9d00-11eb-9355-ab27f227f971.png)

**Comment by Zirochkaa** [comment]
For `pull_requests` stream we have custom incremental meaning that we request all data from GitHub API, filter it in python and update only necessary records (look at [this](https://github.com/airbytehq/tap-github/blob/99c556e25f3258007513378c8978cc707eab3b5c/tap_github/__init__.py#L653) code). So I'll just mark `pull_requests` stream as incremental.
