### ISSUE TITLE
Syncing large tables from postgres to postgres takes a long time

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2888]
from https://airbytehq.slack.com/archives/C01MFR03D5W/p1618239543415800

## Expected Behavior
I expect to be able to sync data from a large postgres table (50m+ rows) to another large postgres table

## Current Behavior
 the process slowed to a big halt after running for a number of hours.  I've setup 11 tables to move with two of them having a very large number of rows.  55mil+  After almost 6 hours it looked like the system was only processing 10k records per minute.  (one batch per minute) with 44+mil records remaining. 

The sync then hits a timeout and terminates. 

## Logs
[logs-48-1.txt](https://github.com/airbytehq/airbyte/files/6312754/logs-48-1.txt)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101580965) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
Is this resolvable?

**Comment by waskelton4** [comment]
I originally asked about this issue on Slack causing the ticket to be generated.

I recently created another sync on two tables (4mil+ rows and 6mil+ rows) ,
The sync seems very very fast at the beginning but does noticeably slow as it gets past a few million rows.  

I set the sync as "Incremental - Append" thinking that it might simply start from the current location of the data (using timestamp column as a cursor).  It instead attempted to get all of the data.   

Would there be a way to run separate syncs starting at the minimum value of the cursor column and moving some number of rows (e.g. 100k) at a time?  I'm not familiar with the architecture of Airbyte but **it seems possible to implement something similar to an incremental sync that enables syncing of batches of older data, until it reaches the cursor value that was the max when the first sync ran.**

I'd be very interested in hearing the thoughts of those who are more familiar with the software.

**Comment by grishick** [comment]
We have made multiple improvements to the sync speed on both source and destination sides. I think, the next step here should be to measure sync times for a data set as large as the one mentioned in the description. Once we have a repeatable test and metrics, we can start looking for bottlenecks and define the desired perf targets.

**Comment by evantahler** [comment]
Closing as we'll tackle things like this with the E2E testing framework
