### ISSUE TITLE
Registry entries for connector variants

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#28884]
## What

To look up a registry entry, we use the following url pattern `/files/metadata/[dockerRepository]/[dockerImageTag]/[registry].json`

For example, to get the cloud registry entry for github verison 1.0.2, you can go to https://connectors.airbyte.com/files/metadata/airbyte/source-github/1.0.2/cloud.json.

As of https://github.com/airbytehq/airbyte-platform-internal/pull/7965, we now use these registry entries when loading overrides to get all relevant metadata for the version.

However, this does not work for strict-encrypt. Let's take source-mysql for example. Cloud has the dockerRepostory as `source-mysql-strict-encrypt`, but the registry does not generate an entry for the strict-encrypt variant. Instead, we're handling these as registry overrides for the regular variant, `source-mysql`. This means that no registry entries exist under `/files/metadata/airbyte/source-mysql-strict-encrypt/`, and when we try getting the versioned registry entry for -strict-encrypt overrides, it 404s. 

## Workaround

For readers that need to set an override before this is solved, there's a manual workaround.

1. Find the cloud.json registry entry for the regular variant (e.g. /files/metadata/airbyte/source-mysql/2.1.0/cloud.json`, and download it.
2. Modify the `dockerImageTag` on it to the pre-release version.
3. Upload it to e.g. `/files/metadata/airbyte/source-mysql-strict-encrypt/2.1.0-dev. 16a1b9b8ab/cloud.json`

Cloud should now be able to find the relevant registry entry.

**Comment by bnchrch** [comment]
Good catch. So there are two possible solutions

The first is we have the metadata -> registry entry conversion also write registry entries to any `dockerRepository` overrides

The second is the metadata prerelease upload also upload the metadata file to any `dockerRepository` locations.

Im thinking the first solution is the best one.

**Comment by pedroslopez** [comment]
@bnchrch agree with the first approach since this doesn’t only affect pre-releases. It’s totally valid to make an override for a mainline version.
