### ISSUE TITLE
File CDK: add partitioning testing for parquet parser

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#28899]
S3 CATs identified an issue where the parquet parser wasn't handling partitions. We should add test coverage for this case to the file-based CDK itself.

**Comment by girarda** [comment]
[we added tests since this issue was written](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/unit_tests/sources/file_based/scenarios/parquet_scenarios.py#L217-L372). feel free to re-open if you think we nee more and we can prioritize them
