### ISSUE TITLE
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 5 ms: Connection refused

### ISSUE THREAD

**Issue by ChenpiDog** [airbytehq/airbyte#28896]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

Docker Desktop: Docker version 20.10.24, Docker Compose version v2.17.2

### What step the error happened?

On deploy

**Comment by ChenpiDog** [comment]
Unable to access the address: https://raw.githubusercontent.com/airbytehq/airbyte-platform/v0.50.12/

**Comment by ChenpiDog** [comment]
![image](https://github.com/airbytehq/airbyte/assets/55483982/fabcaa8f-733f-49dc-8bab-91c03858f463)

**Comment by marcosmarxm** [comment]
@ChenpiDog can you try again? It looks a transient problem with Github server.

**Comment by ChenpiDog** [comment]
![image](https://github.com/airbytehq/airbyte/assets/55483982/56ce7d8f-995a-4597-b35e-97524cb84445)
I still can't access the service here. Is there a direct docker image so that I can experience the functions of airbyte.

**Comment by ChenpiDog** [comment]
@marcosmarxm Okay, thank you!

**Comment by ChenpiDog** [comment]
Resolved

**Comment by ciciElisabeth** [comment]
How to solve it？

**Comment by karonluo** [comment]
I access url: `https://raw.githubusercontent.com/airbytehq/airbyte-platform/v0.57.3/`  on browser , the web return : 403
