### ISSUE TITLE
run metadata service tests with `airbyte-ci test`

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#28919]
We just exposed a new `airbyte-ci test` command to run a pytest test suite on a poetry package declared in `airbyte-ci` directory.
This command is triggered in our CI when any file modification is made on a PR in the `airbyte-ci/**` path

Adding new jobs to [`.github/worfklows/airbyte-ci-tests.yml`](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/airbyte-ci-tests.yml) could replace [the metadata service specific workflow](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/metadata_service_tests_dagger.yml)

**Comment by alafanechere** [comment]
Relates to https://github.com/airbytehq/airbyte/issues/28919

**Comment by bnchrch** [comment]
done
