### ISSUE TITLE
Source Shopify: product_variant uses id instead of updated_at as cursor field

### ISSUE THREAD

**Issue by apd-bscally** [airbytehq/airbyte#28926]
### Connector Name

source-shopify

### Connector Version

0.5.1

### What step the error happened?

Configuring a new connector

### Revelant information

`product_variant` stream should use `updated_at` instead of `id` for incremental configuration

### Contribute

- [ ] Yes, I want to contribute

**Comment by bazarnov** [comment]
@apd-bscally Hello, could you please describe the actual issue you've faced or give some motivation behind this request?

**Comment by xavier-lai** [comment]
Hi,

Yes, I have the same concern about the stream fulfillment_orders. The cursor field is id, but if the order line is updated, then the sync will not fetch the line, and the sync will not update the row at the destination.

Why has the Airbyte team set id as the cursor?

**Comment by bazarnov** [comment]
Both cases are fixed in: https://github.com/airbytehq/airbyte/pull/32345

**Comment by xavier-lai** [comment]
> Both cases are fixed in: #32345

Hi @bazarnov, Thanks for your great contribution to this PR! Do you have any idea of when your release might be pushed into production?

**Comment by bazarnov** [comment]
@xavier-lai We are actively working on this. Realistically speaking - start of the next week.
