### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28922]

**Comment by natayadev** [comment]
Hi, I want to work on this connector, please :)

**Comment by tovbinm** [comment]
We have a source for GitLab CI - https://github.com/faros-ai/airbyte-connectors/tree/main/sources/gitlab-ci-source

**Comment by natayadev** [comment]
Thanks!

**Comment by RealChrisSean** [comment]
Hi @natayadev how's it going? Anything I can help with? :)

**Comment by RealChrisSean** [comment]
This has been unassigned due to inactivity. I can assign this back to you later if you're still interested :).

**Comment by marcosmarxm** [comment]
Closing
