### ISSUE TITLE
yahoo-finance-price

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28920]

**Comment by fool1280** [comment]
Hi I would like to give this a go!

**Comment by RealChrisSean** [comment]
Hi we only allow folks to work on one issue at a time. Would you prefer to work on this or the plaid issue? :)

**Comment by fool1280** [comment]
I prefer this one :D

**Comment by RealChrisSean** [comment]
Good luck!

**Comment by masyagin1998** [comment]
Hey @RealChrisSean !
It's inactive more than 5 days, so can you assign it to me and mark my Plaid & BrainTree PRs submitted?

**Comment by RealChrisSean** [comment]
Hey @fool1280 how's it going? Anything I can do to help? :)

**Comment by masyagin1998** [comment]
Hey @RealChrisSean looks like he is inactive (checked by commit activity) :(

**Comment by RealChrisSean** [comment]
This has been assigned to you.

**Comment by masyagin1998** [comment]
Thank you!!
I'll push first update on it tomorrow :)
P.S. Plaid is ready for review, BrainTree is going to be completed tomorrow)

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by masyagin1998** [comment]
Hey @RealChrisSean !
Done: https://github.com/airbytehq/airbyte/pull/29355

**Comment by RealChrisSean** [comment]
Awesome!
