### ISSUE TITLE
Slack message text is blank when there is an image included in the slack message

### ISSUE THREAD

**Issue by Moofasax** [airbytehq/airbyte#2892]
## Expected Behavior
Sync slack -> postgres Slack message text should still be taken even if there is an image in the text.
[logs-2-0.txt](https://github.com/airbytehq/airbyte/files/6313256/logs-2-0.txt)
[logs-2-0.txt](https://github.com/airbytehq/airbyte/files/6313258/logs-2-0.txt)

## Current Behavior
If a slack message has both text and an image in the message, the text is not taken and you end up with a blank text column in the messages table.

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._

## Steps to Reproduce
1. Post a message to a slack channel that has both text and an image in it
1. Run a sync and look at the messages table
1. The text will be black

## Severity of the bug for you
High

## Airbyte Version
0.20.0-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101595234) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
Thanks for reporting it @Moofasax . We will update here as we prioritize this.

**Comment by cgardens** [comment]
@sherifnada fyi

**Comment by davydov-d** [comment]
@Moofasax hi! the connector you're using is Singer-based (out of date) and not supported anymore. Please upgrade your Airbyte instance and set up a new connection using CDK-based Slack Source. I could not reproduce this issue using the up-to-date connector:
![image](https://user-images.githubusercontent.com/7703835/186606248-a21d9516-4e89-4021-81a6-ae2aabe4fb04.png)
![image](https://user-images.githubusercontent.com/7703835/186606429-ff873074-0ab4-4bb0-87b3-451d5348f986.png)
