### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28921]

**Comment by Azanul** [comment]
May I work on this?

**Comment by natayadev** [comment]
Hi, I want to work on this connector, please :)

**Comment by RealChrisSean** [comment]
Hi I will assign this to the person who requested it first. Good luck! :)

**Comment by RealChrisSean** [comment]
Hey how's it going? Anything I can help with? :) @Azanul

**Comment by RealChrisSean** [comment]
Wow amazing!! 😎

**Comment by marcosmarxm** [comment]
Close
