### ISSUE TITLE
Source Asana: Add the real Story stream (Not StoryCompact)

### ISSUE THREAD

**Issue by cbeauch** [airbytehq/airbyte#28939]
### What area the feature impact?

Connectors

### Revelant Information

Hi, the Asana connector currently supports the Story endpoint, however, it is only using StoryCompact. The current Airbyte implementation makes it so we are missing a large amount of useful information for analytics. 

https://developers.asana.com/reference/stories

Any chance we could get the current Airbyte stream renamed to "StoryCompact" and have the real "Story" stream added? 

Thanks!

**Comment by cbeauch** [comment]
For example, we want to link Stories and Tasks together. Currently impossible so we are writing our own pipeline

**Comment by topefolorunso** [comment]
I want to work on this next @justinbchau. PRs raised for other issues

**Comment by cbeauch** [comment]
Thanks for doing that. The Story stream is missing a ton of data still however. Makes it hard to match stories to tasks

**Comment by jdbranham** [comment]
Anyone have luck this with this? We're also trying to match stories to tasks.
