### ISSUE TITLE
plaid

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28935]

**Comment by fool1280** [comment]
Hi I would like to give this a go!

**Comment by RealChrisSean** [comment]
This has been assigned to you good luck!

**Comment by RealChrisSean** [comment]
This has been unassigned with you working on the plaid connector.

**Comment by masyagin1998** [comment]
Hi can you assign this connector to me @RealChrisSean if it was unassigned from @fool1280 ?

**Comment by RealChrisSean** [comment]
Sure :) It has been assigned to you @masyagin1998

**Comment by masyagin1998** [comment]
Hey @RealChrisSean !
PR: https://github.com/airbytehq/airbyte/pull/29127
Looks like I found a bug, so I need support of someone like you or @marcosmarxm .

**Comment by RealChrisSean** [comment]
Amazing! Congrats!!
