### ISSUE TITLE
:sparkles: Source LinkedIn Ads : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28934]
https://docs.airbyte.com/integrations/sources/linkedin-ads

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by Atharvat** [comment]
Hi @RealChrisSean please assign this to me.

**Comment by RealChrisSean** [comment]
Good luck! :)

**Comment by RealChrisSean** [comment]
Hey how's it going? Anything I can help with? :)

**Comment by rizwan-io** [comment]
Hi @RealChrisSean 
I would like to work on this issue. Can you please assign this to me?

**Comment by justinbchau** [comment]
you got it @rizwan-io
