### ISSUE TITLE
[SPIKE] Redshift Destinations V2

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#28930]
SqlGenerator
CatalogParser
~~Normalization into container~~ (but we need to roll it out)
V1->V2 migrator
Make it work
...?

**Comment by jbfbell** [comment]
Opting to Pause redshift v2 development in favor of any tasks which are needed for the Snowflake + BigQuery release

**Comment by evantahler** [comment]
note: re https://github.com/airbytehq/airbyte/issues/30101, we should make both the raw and final tables in Redshift lowercase

**Comment by evantahler** [comment]
Grooming: This story should become an epic with sub stories:
* migration (v1-->v2)
* full refresh
* incremental

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/31223
