### ISSUE TITLE
Fix and standardize numeric rounding behavior across destinations (async)

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#28940]
See airbytehq/oncall#2076 and [Slack discussion](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1690834297388829).

### Source-to-Destination Behavior

Take this source postgres table where `col1` is type VARCHAR and `col2` is type NUMERIC:
```
 id |            col1             |         col2          
----+-----------------------------+-----------------------
  1 | 955031734.1681486901        |                      
  2 | 955031734.1681486901        |                      
  3 | GA1.1.1046373168.1684259460 |                      
  4 | 1878352336.1681147245       |                      
  5 |                             |  955031734.1681486901
  6 |                             | 1878352336.1681147245
```

We observe different rounding behavior for the NUMERIC data across destinations:

Redshift
![Redshift.png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/6b2e792e-5519-4624-938a-5460af500083)

Snowflake
![Snowflake.png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/2630b09c-41d3-46ef-ad66-b6ca00339932)

BigQuery
![BigQuery.png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/a25f0b53-86e2-44a0-aed0-7488ed752d29)

E2E Testing
![E2E Testing.png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/a40d4a62-4080-4529-be7d-9c356f7fc926)

### In-Destination Behavior

We should also cross-check how the destinations themselves handle numbers (independent from Airbyte destinations code):

Redshift
![image (2).png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/92a0b43e-d6fd-4df2-aa8f-60305a43777f)

Snowflake
![image (3).png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/c663e7aa-c34f-4589-93a0-80aa51ccda34)
![image (4).png](https://images.zenhubusercontent.com/64349f97437312c1933e8d32/a72ba468-1d5f-4cee-a6c7-291d5cd1d73e)

### Possible Root Cause & Solution

This may be happening due to deserializing + reserializing these long numbers.

So we may have to do something like this whenever we deserialize AirbyteRecordMessages:
```
    final ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS);
    final JsonNode jsonNode = objectMapper.readTree("1826941036.1684242748");
    String serialized = Jsons.serialize(jsonNode);
    System.out.println(serialized);
```

Also see similar issue #19776 fixed by #20407.

**Comment by evantahler** [comment]
Grooming:
* We need to test if the problem is occurring in both the platform and/or the destination... could be both
* Fix the destination, if it is a destination problem
* If it is a platform problem, talk to @davinchia

**Comment by edgao** [comment]
adding a Jsons.deserializeExact method here https://github.com/airbytehq/airbyte/pull/29590/files#diff-bf95afdc0dd77c7ba4c000468ba17e5b3f0f4deb0812781972bd6f4aba89c160

(for unrelated reasons, but probably reusable for this issue)

**Comment by evantahler** [comment]
Grooming:
* We need a chart to share all the scenarios which are in play (async or not, V1/v2, JSON serialization flags, etc)
* We could split this work into 2 stories - one about the raw tables, and one about Dv2
* Does the platform JSON serialization do something here?  
  * We think the platform isn't breaking anything - to confirm

**Comment by cynthiaxyin** [comment]
Opened up #31299 for the non-async work. This ticket will just cover closing out the platform + async work.
