### ISSUE TITLE
:sparkles: Source Outreach : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28953]
https://docs.airbyte.com/integrations/sources/outreach

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by avirajsingh7** [comment]
@RealChrisSean Can you assign me this issue?

**Comment by RealChrisSean** [comment]
Good luck!

**Comment by avirajsingh7** [comment]
@RealChrisSean Not able to get credentials for this

**Comment by RealChrisSean** [comment]
Noooo I'll check with the team on  Monday. 😭

Is there another issue you want to work on for now while we work through this?

**Comment by avirajsingh7** [comment]
Can't get credentials unassigning this issue, best of luck to others

**Comment by DulceCoder** [comment]
can you assign this to me? thank you

**Comment by gauriimaheshwarii** [comment]
Hey @justinbchau, I would like to work on this issue if @DulceCoder is okay with it.

**Comment by ChristoGrab** [comment]
Closing, resolved by https://github.com/airbytehq/airbyte/pull/36954
