### ISSUE TITLE
openweather

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28951]

**Comment by jhajajaas** [comment]
Can I work on this one?

**Comment by RealChrisSean** [comment]
This has been assigned to you. Good luck!

**Comment by topefolorunso** [comment]
Hi @jhajajaas, still working on this? If not, I would love to work on it @RealChrisSean

**Comment by jhajajaas** [comment]
Yes I’m

**Comment by RealChrisSean** [comment]
Awesome anything I can help with? :)

**Comment by RealChrisSean** [comment]
Please feel free to go for this @shivam096

**Comment by shivam096** [comment]
Hey @RealChrisSean ,

The configured API requires paid service - https://openweathermap.org/api/one-call-3#current. The one that is available for free is - https://api.openweathermap.org/data/2.5/weathe. Though I have configured most of the code according to it. It would be great if I you could share any API to test the code.

**Comment by shivam096** [comment]
Hey @RealChrisSean ,

Submitted the PR - #29963 . Waiting for upgrades or comments on the same

**Comment by shivam-agarwal4** [comment]
Hey @RealChrisSean  the PR has been merged :)

**Comment by shivam096** [comment]
Hey @RealChrisSean ,

This PR has been merged 🎉

**Comment by RealChrisSean** [comment]
Amazing!! Congrats :)
