### ISSUE TITLE
Source Mysql: cdc replaces null value for a column with the default value of that column

### ISSUE THREAD

**Issue by ifun248** [airbytehq/airbyte#28968]
### Connector Name

source-mysql

### Connector Version

2.0.24 and 2.1.0

### What step the error happened?

During the sync

### Revelant information

When init syncing data from MySQL to S3, the data syncing by cdc is different to data by stardard methord. 

The example data syncing by cdc is below:
`{"_airbyte_ab_id":"39c449b5-aa4c-4d49-ad31-457e3057206b","_airbyte_emitted_at":1690966456190,"_airbyte_data":{"receipt_line_id":60001,"claim_method":"MANUAL CLAIM","_ab_cdc_updated_at":"2023-08-02T08:55:04Z","_ab_cdc_log_file":"mysql-bin.002425","_ab_cdc_log_pos":14830445,"_ab_cdc_deleted_at":null}}`

The example data syncing by stardard is below:
`{"_airbyte_ab_id":"452fdfed-6cde-4bd6-8f71-5fe58c622606","_airbyte_emitted_at":1690950556212,"_airbyte_data":{"receipt_line_id":60001}}`

The data syncing by stardard is right as there is no field named claim_method which is same to MySQL source. And I guess the problem maybe is from debezium reading MySQL binlog.

### Relevant log output

```shell
The syncing process is normal without error logs.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by ifun248** [comment]
I have found the reason why cause this problem as claim_method filed in table DDL sets a default value 'MANUAL CLAIM', when the claim_method value is null, the claim_method value syncing by cdc method will be 'MANUAL CLAIM'.

So Airbyte team how to think of it? I think maybe keep the claim_method value being null is better.

**Comment by subodh1810** [comment]
Hey @ifun248 can you share the entire schema structure of the table that you are syncing?

**Comment by subodh1810** [comment]
Also can you walk us through step by step on how you tested this. And what does Mysql return when you run a query directly against it for the record with receipt_line_id 6001. Does it show `claim_method` to be null or does it have a value?

**Comment by ifun248** [comment]
Hi @prateekmukhedkar, I have tested syncing manny times by cdc method, and value for claim_method is always 'MANUAL CLAIM' in S3 file but in fact the claim_method value is null in MySQL source table.

**Comment by ifun248** [comment]
Hi @subodh1810, the whole steps of causing this problem are below:

**Comment by subodh1810** [comment]
@ifun248 thank you so much for providing the steps to reproduce this! I will get back to you on this ticket after trying this out and with next steps.

**Comment by prateekmukhedkar** [comment]
@ifun248 just providing a quick update that we could repro. As you mentioned before, this looks related to how Debezium is reading the binlog and whether a binlog entry is created after the `UPDATE claim_method = null  ` statement which we have not been able to verify. Hold on for more updates.

**Comment by nguyenaiden** [comment]
@ifun248 we were able to reproduce the behavior and have identified the issue. This isn't an issue with the Airbyte MySQL connector but rather a deficiency in the underlying `kafka-connect` library that Debezium CDC platform is built on. The fix for `kafka-connect` has been shipped, but that version is currently only tested and built with Debezium v2.4.0.Alpha1. (We're currently on v2.2.0)

Since it is an alpha release, we will have to wait until Debezium ships the GA version before upgrading.

**Comment by theyueli** [comment]
we believe we have fixed this issue. Please reopen if it happens again.

**Comment by mariana-s-fernandes** [comment]
@theyueli can you please link the PR where this has been fixed, for reference? Thank you

**Comment by theyueli** [comment]
@mariana-s-fernandes I think Debezium has fixed this issue in the recent versions as mentioned in the discussion [above](https://github.com/airbytehq/airbyte/issues/28968#issuecomment-1693857270)

Last month, we have upgraded DBZ to 2.5.4 for MySql which shall contain the fix. 
https://github.com/airbytehq/airbyte/pull/39144

But if you could, please do another test, and feel free to reopen this issue if it occurs again.
