### ISSUE TITLE
connectors-ci: revisit gradle caching approach

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#28983]
Conor implemented a simpler and working caching approach for gradle in the infra pipes, we shall port it to `airbyte-ci`

**Comment by edgao** [comment]
once this is done, you should be able to remove the input/output declarations on airbyteDocker https://github.com/airbytehq/airbyte/pull/28817/files#diff-f721c4502ee77813d43d58b2a96c2a4f5a73413be5057a28abe251b0fa227aacR200-R201

**Comment by edgao** [comment]
and possibly also the `dependsOn project.assemble`? Does airbyte-ci depend on the host machine's gradle build output?

**Comment by postamar** [comment]
@alafanechere could you provide a reference for Conor's caching approach please? I'm curious. Thanks!

**Comment by alafanechere** [comment]
@postamar :
https://github.com/airbytehq/aircmd/blob/adecadc66ad0352afd6660c8fe9ab91150ac7eeb/aircmd/actions/environments.py#L314
https://github.com/airbytehq/airbyte-platform-internal/blob/6d1c4435cde1c0284f317e322d95eb8eb05e4528/ci/cloud/tasks.py#L41

**Comment by postamar** [comment]
I thin we can close this now in favour of #30708
