### ISSUE TITLE
chargify

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28988]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by topefolorunso** [comment]
Hi @RealChrisSean! I'd like to work on this for the hackathon but I am unable to get an api key for testing.

**Comment by topefolorunso** [comment]
I'd like to work on this now @RealChrisSean

**Comment by topefolorunso** [comment]
Waiting to be assigned to this @RealChrisSean

**Comment by RealChrisSean** [comment]
Yooo congrats and good job on this!
