### ISSUE TITLE
braintree

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28987]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by masyagin1998** [comment]
Hey @RealChrisSean !
I'd like to write braintree connector, because my Plaid work looks to be done (just waiting for review).
I've already connected to their Sanbox)

**Comment by RealChrisSean** [comment]
Amazing! Good luck :)

**Comment by masyagin1998** [comment]
Thank you!
Also could you answer a question in Slack about reposting to linkedin and potential bug about Plaid? :)

**Comment by masyagin1998** [comment]
@RealChrisSean https://github.com/airbytehq/airbyte/pull/29200 - it's mostly completed, so I'd like to take new connector. Waiting reviews for this one and for Plaid :)

**Comment by RealChrisSean** [comment]
Go for it :)

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by RealChrisSean** [comment]
Amazing! Congrats @masyagin1998!!
