### ISSUE TITLE
confluence

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28989]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by topefolorunso** [comment]
Hi @RealChrisSean! Please assign this to me. I'd like to work on it for the hackathon.

**Comment by RealChrisSean** [comment]
This has been assigned to you. Good luck!

**Comment by RealChrisSean** [comment]
Amazing congrats!
