### ISSUE TITLE
freshservice

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28992]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by avirajsingh7** [comment]
@RealChrisSean I want to work on this issue, Can you assign me this?

**Comment by RealChrisSean** [comment]
This has been assigned to you :)

**Comment by avirajsingh7** [comment]
@RealChrisSean  can you create a issue for [this](https://github.com/airbytehq/airbyte/tree/1219e66fb966f03620db5a2157148e8a5b28abdb/airbyte-integrations/connectors/source-public-apis) and assign this to me?
