### ISSUE TITLE
Jira

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28991]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

Connectors must include all streams.

**Comment by wumadeline** [comment]
I'd like to give this one a shot 😄

**Comment by RealChrisSean** [comment]
This has been assigned to you! Good luck!

**Comment by marcosmarxm** [comment]
I'm closing this for now.
