### ISSUE TITLE
flexport

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28995]
Please use the [connector builder](https://docs.airbyte.com/connector-development/config-based/low-code-cdk-overview/?_gl=1*13hxonw*_gcl_au*MTI0NTMzNjM3OS4xNjkwODM4MzE0*_ga*MTg2NTc3OTc0Ni4xNjUxNTk0NTQw*_ga_HDBMVFQGBH*MTY5MTAwNDEzMy4yNzIuMC4xNjkxMDA0MTMzLjAuMC4w&_ga=2.197654767.1978878.1690818922-1865779746.1651594540) for this.

**Comment by topefolorunso** [comment]
Can I work on this next @RealChrisSean?

**Comment by RealChrisSean** [comment]
We only allow participants to work on one issue at a time. Did you submit a PR for the other issue? :)

**Comment by topefolorunso** [comment]
Yes I've submitted PR for it already here #29130

**Comment by RealChrisSean** [comment]
Amazing!! Good luck with this one :)

**Comment by RealChrisSean** [comment]
working on getting credentials for this

**Comment by RealChrisSean** [comment]
Hello just to keep you updated @topefolorunso it may take a bit to get a sandbox for Flexport. Thanks for your patience in advance :)
