### ISSUE TITLE
hubspot

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#28990]
```[tasklist]
### Tasks
```

**Comment by shivam096** [comment]
Hey @RealChrisSean , I would like to take this up. Though I am pretty new but would be glad to participate in the hackathon

**Comment by RealChrisSean** [comment]
This has been assigned to you good luck!

**Comment by RealChrisSean** [comment]
Hey how's it going? Anything I can help with? :)

**Comment by sherifnada** [comment]
@RealChrisSean hubspot is incompatible with lowcode due to complex HTTP requesting behavior, closing this one
