### ISSUE TITLE
Chroma

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29007]
https://www.trychroma.com/

Total swag credits for this connector: 75

**Comment by topefolorunso** [comment]
@RealChrisSean Can you point me to a resource on how to create destination connectors using python? A tutorial maybe? The info in the docs is not clear enough for me. Thanks

**Comment by RealChrisSean** [comment]
Hey @topefolorunso I apologize for the late reply. Here's a guide from one of our engineers :D

https://transparent-trout-f2f.notion.site/How-to-implement-vector-database-destinations-dd3f5f020e0943ee93ca76e42d0a494a

I hope this helps!

**Comment by RealChrisSean** [comment]
I will assign this to you for now. Please let me know later if you're not interested.

**Comment by topefolorunso** [comment]
@RealChrisSean Having a hard time with this, I will work on a source connector for now.

**Comment by teetop2** [comment]
Ready to give this a shot now @RealChrisSean

**Comment by topefolorunso** [comment]
I want to work on this now @RealChrisSean

**Comment by topefolorunso** [comment]
> Hey @topefolorunso I apologize for the late reply. Here's a guide from one of our engineers :D
> 
> [transparent-trout-f2f.notion.site/How-to-implement-vector-database-destinations-dd3f5f020e0943ee93ca76e42d0a494a](https://transparent-trout-f2f.notion.site/How-to-implement-vector-database-destinations-dd3f5f020e0943ee93ca76e42d0a494a)
> 
> I hope this helps!

@RealChrisSean can you provide the updated link. This one seems to be broken

**Comment by yogesch** [comment]
> Hey [@topefolorunso](https://github.com/topefolorunso) I apologize for the late reply. Here's a guide from one of our engineers :D
> 
> https://transparent-trout-f2f.notion.site/How-to-implement-vector-database-destinations-dd3f5f020e0943ee93ca76e42d0a494a
> 
> I hope this helps!

This link is no longer available.
