### ISSUE TITLE
Connection State should be Editable

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29016]
This story is to make connection state editable.

<img width="1537" alt="257944887-7e4c9916-266d-4c64-a170-32e5630ca884" src="https://github.com/airbytehq/airbyte/assets/303226/e8e22e57-d95e-49a8-8f0b-50234fcf5cdf">

This is good for _many_ reasons, including:
* Doing partial re-syncs.  Many states are dates or numeric.  Rolling back to "yesterday" before an outage or error occurred is a great way to reload data that had a problem without needing to do a full reset.
* Copying a connection to try out a new connector version.  As users are prompted to upgrade from version X to version Y of a connector, they will want to try out a sync with both versions, to compare them and see what has changed.  Copying existing state between 2 connections is important to that process so both syncs will load the same data.  Learn more [here](https://docs.google.com/document/d/1unzAlWUoHVuJ3b3Y3Z1ycWPaaiZ-VlC1RvUucwFwbNY/edit#heading=h.9zlmxwjicade) and [here](https://docs.google.com/document/d/13nW4TpWO5RHpRGGd1vdXhut2w5umRdI3kD1ZaYPvIFU/edit#heading=h.j2uaix84p807) - phase 1

```[tasklist]
### Requirements
- [ ] A new state-edit API endpoint
- [ ] Users can make changes to state and save them
- [ ] The form is disabled (and API will not accept updates) while a sync is running
- [ ] Scary warnings on the form that remind folks that if they change their state and don't know what they are doing, they can break their syncs.
- [ ] The new state is validated as many ways as reasonably possible.  JSON validation, stream-name validation, etc
```

```[tasklist]
### Bonus features (not requirements, but nice-to-have if there is time)
- [ ] A prettier code-viewer in the form (colors, line numbers, etc)
```

**Comment by erohmensing** [comment]
Took a look at what it would take to get an endpoint available. It looks like we already have a `[/api/v1/state/create_or_update](https://github.com/airbytehq/airbyte-platform-internal/blob/592667d75a7f7a6dcefb47921b0b098fc2d79475/oss/airbyte-server/src/main/java/io/airbyte/server/apis/StateApiController.java)` endpoint. It's secured to ADMIN right now, but if we change that I'm hoping that this endpoint is already available to us!

**Comment by erohmensing** [comment]
I'm not sure about the permissions, in my local dev setup it worked fine secured to admin. This is with the cloud deployment from `make dev.up` and using credentials `airbyte:password`. 

Full curl example: 
```
❯ curl -X POST -u airbyte:password -H "Content-Type: application/json" -d '{                                                                                   ─╯
  "connectionId": "46609299-9c0b-4cdd-ad7f-fec08e0392e5"
}' https://local.airbyte.dev/api/v1/state/get | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   474  100   414  100    60   6856    993 --:--:-- --:--:-- --:--:--  8777
{
  "stateType": "stream",
  "connectionId": "46609299-9c0b-4cdd-ad7f-fec08e0392e5",
  "streamState": [
    {
      "streamDescriptor": {
        "name": "products"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "users"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "purchases"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    }
  ]
}
```


```
❯ curl -X POST -u airbyte:password -H "Content-Type: application/json" -d '{                                                                                   ─╯
  "connectionId": "46609299-9c0b-4cdd-ad7f-fec08e0392e5", "connectionState": {
  "stateType": "stream",
  "connectionId": "46609299-9c0b-4cdd-ad7f-fec08e0392e5",
  "streamState": [
    {
      "streamDescriptor": {
        "name": "products"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "users"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "purchases"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-04T14:47:19+00:00"
      }
    }
  ]
}
}' https://local.airbyte.dev/api/v1/state/create_or_update | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1135  100   414  100   721   6349  11058 --:--:-- --:--:-- --:--:-- 18306
{
  "stateType": "stream",
  "connectionId": "46609299-9c0b-4cdd-ad7f-fec08e0392e5",
  "streamState": [
    {
      "streamDescriptor": {
        "name": "products"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "users"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-03T14:47:19+00:00"
      }
    },
    {
      "streamDescriptor": {
        "name": "purchases"
      },
      "streamState": {
        "seed": -1,
        "updated_at": "2023-08-04T14:47:19+00:00"
      }
    }
  ]
}
```
confirmed that this updates the state in the UI (changed the date for the last updated_at)

**Comment by erohmensing** [comment]
Grooming: 
* What do we need to authenticate from the frontend?
  * Client requests are being made with the user's JWT token from firebase
  * Set up a request in the frontend to see if hitting that endpoint works 

* How do we restrict the changing of state during a sync? -> this is bad 
  * minimum: button to edit state is disabled during sync (frontend already has this information) 
  * ideal: /create_or_update endpoint should fail if a sync is currently running
    * but only if it's called by the user -> platform call for state flushing needs to still work
    * StateAPIController (calls the StateHandler): called by frontend/ from the endpoint
    * generated StateAPI class (platform flushing) -> called from StatePersistenceImpl

**Comment by erohmensing** [comment]
Iceboxing in our team's zenhub since @lmossman will be taking this on (i'll let him assign when he's ready to pick it up)

**Comment by lmossman** [comment]
Validations to perform on state updates:
- JSON is valid
- The shape and keys of the value do not change (?)
