### ISSUE TITLE
✨ Add Destination Vectara

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29012]
https://docs.vectara.com/docs/
https://docs.vectara.com/docs/api-reference/api-overview

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

## Some explanation of how this connector should work

For this destination connector, incoming records should be loaded into Vectara using the indexing API: https://docs.vectara.com/docs/api-reference/indexing-apis/indexing

Airbyte's unit of data is a "record", which is a JSON object with very little additional structure (in most cases there is a defined primary key that's guaranteed to be unique per record, but not always). A destination connector in the Airbyte sense receives records and needs to load them into the destination somehow.

OTOH, Vectara's unit of data is a "document". It has an id which can be mapped to the primary key of an Airbyte record, but there are no natural title/description/sections concepts in Airbyte.

To map a record to a document, the user should configure text fields and metadata fields as part of the connector configuration.

For each text field, create a corresponding section of the document, and copy the text of the field into that section.
Set metadata on the section, e.g. source_type with the value being the name of the text field.

Ideally, the corpus needs to be created with source_type specified as a filterable column. This will allow customers to run searches over some columns, and exclude others.

Fields specified as metadata field will be attached to the document as metadata.

**Comment by RealChrisSean** [comment]
😎

**Comment by aazam-gh** [comment]
this one wont be counted towards the migrated ones right for the hack?

**Comment by aazam-gh** [comment]
nice! working on it asap :D

**Comment by aazam-gh** [comment]
@RealChrisSean the REST APIs of vectara are all post request only https://docs.vectara.com/docs/rest-api
I don't think it's possible to make a connector right?

**Comment by RealChrisSean** [comment]
Hi @aazam-gh this is for a vector db destination :D. 

Here's a guide from our engineering team. Hopefully this helps :D 

https://transparent-trout-f2f.notion.site/How-to-implement-vector-database-destinations-dd3f5f020e0943ee93ca76e42d0a494a

**Comment by aazam-gh** [comment]
@RealChrisSean  thanks will have look into it!

**Comment by RealChrisSean** [comment]
How's it going? :D

**Comment by aazam-gh** [comment]
A bit on the hard side actually 😬

**Comment by RealChrisSean** [comment]
This is not an easy destination to build whatsoever. If you'd like I could try to see if one of our engineers can meet with you? :)

**Comment by aazam-gh** [comment]
That would be very helpful. I was planning to inquire more during office hours today too

**Comment by flash1293** [comment]
Airbyte's unit of data is a "record", which is a JSON object with very little additional structure (in most cases there is a defined primary key that's guaranteed to be unique per record, but not always). A destination connector in the Airbyte sense receives records and needs to load them into the destination somehow.

OTOH, Vectara's unit of data is a "document". It has an id which can be mapped  to the primary key of an Airbyte record, but there are no natural title/description/sections concepts in Airbyte.

To map a record to a document, the user should configure text fields and metadata fields as part of the connector configuration.

For each text field, create a corresponding section of the document, and copy the text of the field into that section.
Set metadata on the section, e.g. source_type with the value being the name of the text field.

Ideally, the corpus needs to be created with source_type specified as a filterable column. This will allow customers to run searches over some columns, and exclude others.

Fields specified as metadata field will be attached to the document as metadata.

**Comment by flash1293** [comment]
@aazam-gh are you still interested in picking this up? See the comment from above for a guidance on how to implement the connector

**Comment by aazam-gh** [comment]
@flash1293 Thanks for the information on implementing it. I would love to take it up but  would this be counted towards the ongoing hackathon?

**Comment by flash1293** [comment]
@aazam-gh sure, go for it! I assigned you to the issue. Please let me know if you can't work on it anymore or if you have any questions about the implementation. Once you have a PR up please ping me on it and I will take a look.

**Comment by aazam-gh** [comment]
Will be working on it today. :)

**Comment by aazam-gh** [comment]
@flash1293 This issue seems beyond my scope for now. Someone else can take it up :)

**Comment by flash1293** [comment]
Thanks for the message, I will put it back into the pool

**Comment by topefolorunso** [comment]
I will give this a shot @flash1293. Please assign to me

**Comment by RobLucchi** [comment]
Hello, 
could you assign this to me as well ?

**Comment by topefolorunso** [comment]
Raised PR @flash1293 @justinbchau

**Comment by flash1293** [comment]
Sorry @RobLucchi , @topefolorunso was a little faster here. Could you look for another open issue?

**Comment by aaronsteers** [comment]
Resolved today in:

- #33616 

Huge thanks to @ofermend and @topefolorunso for bringing this to life!

Connector docs are here:
- https://docs.airbyte.com/integrations/destinations/vectara
