### ISSUE TITLE
[destination-snowflake] query_tag is overwritten by default settings instead of params given in destination

### ISSUE THREAD

**Issue by u-sahin** [airbytehq/airbyte#29036]
### Connector Name

destination-snowflake

### Connector Version

1.2.4

### What step the error happened?

During the sync

### Revelant information

Hi,

I've realized that the profiles.yml for the normalization doesn't take the query_tag given in the destination query parameter into the  file.
It is always overwritten with "normalization".
Could you please take a look at this issue?

![image](https://github.com/airbytehq/airbyte/assets/16067962/fe39a308-67cb-4926-ae91-d2769736e0f0)
![image](https://github.com/airbytehq/airbyte/assets/16067962/861cc1f9-9b5d-4630-8355-4859f353355d)

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Normalization is removed - closing this issue
