### ISSUE TITLE
No clear way to migrate from kustomize to helm deployments

### ISSUE THREAD

**Issue by dis-sid** [airbytehq/airbyte#29032]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

0.40.32

### What step the error happened?

None

### Revelant information

I understand that I can't upgrade Airbyte because I deployed it using kustomize back then and now the supported way is Helm.

But since it has been deprecated I assume a way to migrate has been proposed and I can't find any documentation on how to migrate to Helm safely.

Is there any instructions somewhere ?

**Comment by marcosmarxm** [comment]
It won't be possible to provide a guide on migrating from the deprecated Kustomize to Helm at this time.
