### ISSUE TITLE
Google Ads Connector says it supports multiple customer ids but only accepts one.

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2903]
## Expected Behavior
* Google Ads allows taking in multiple customer ids at once.
* Google Ads connector allows taking multiple customer ids at once

## Current Behavior
* Google Ads connector _says_ it allows multiple customer ids at once
* Google Ads connector does not allow taking multiple customer ids at once

## Steps to Reproduce
<img width="796" alt="Screenshot 2021-04-15 at 15 50 13" src="https://user-images.githubusercontent.com/9092207/114908380-e5da9d00-9dd0-11eb-84bb-83b87adb5544.png">

## Airbyte Version
0.19.0-alpha

## Connector Version (if applicable)
Adwords: 0.2.1

**Comment by cgardens** [comment]
@sherifnada fyi

**Comment by Jamakase** [comment]
Isn't it better to handle such case as array of strings as we already have component for that?

**Comment by cgardens** [comment]
yes. i agree artem. that sounds like the better approach.

**Comment by sherifnada** [comment]
agreed that this should be a string list. I'm not sure there is a way of changing this type without breaking backwards compatibility. 

should be a simple fix to change the [spec pattern](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-adwords-singer/source_google_adwords_singer/spec.json) from `^[0-9]{10}$` to `^[0-9]{10}(,[0-9]{10})*$`

**Comment by michel-tricot** [comment]
I think we should break backward compatibility here. We will need a strategy to handle that in the future.

**Comment by keu** [comment]
@sherifnada so what will the fix? are we going for list or string?

**Comment by po3na4skld** [comment]
> @sherifnada so what will be the fix? are we going for a list or string?

As I understood, UI supports list so we will use it and not a string

**Comment by po3na4skld** [comment]
During integration testing I got one test failed thus, I wasn't be able to publish a new version of connector. Test is failing due to the fact that the stream is actually empty when trying to do testIncrementalSyncWithState. 

The problem is also described in this issue: #2929 
Blocked for now.
