### ISSUE TITLE
Source Hubspot: rename state fields and change format to match format in records

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#2907]
## Tell us about the problem you're trying to solve
subscription_changes and email_events have mismatches in format and field names between states and records.

## Describe the solution you’d like
rename and keep the same format as in records

discovered during #2792

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368159962632) by [Unito](https://www.unito.io)

**Comment by augan-rymkhan** [comment]
@keu I have checked cursor_field name and its format (timestamp or date-time). It's fixed in PR [#10177](https://github.com/airbytehq/airbyte/pull/10177)
