### ISSUE TITLE
Destination Snowflake v2: doublecheck type mapping

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#29072]
couple things from https://docs.google.com/document/d/1DyI8-V0H8fisEowhnmfpfXXbAQqhsAbaGkkvcbRd2S8/edit#heading=h.f9wnipto58qj

* time with timezone - we map to varchar, is there a better type?
* timestamp_tz / timestamp_ltz
  * make sure we're not changing the TZ to UTC (iirc this was happening in source-postgres, not the destination)
  * map to timestamp_ltz instead of timestamp_ntz? (what's the difference?)
* number/integer/decimal - map to better types?
  * integer should be integer, obviously
  * for numeric columns - what should we do about precision/scale?

**Comment by evantahler** [comment]
I think I would prefer to keep time-with-zone a timestamp-ish type, even if it is forced to UTC.  Not having functions like `DAY(...)` work seems rough.

**Comment by evantahler** [comment]
> we explicitly got dinged for remapping timestamp_tz to UTC for all records though

In slack, I gather that this might be a [source](https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1691165641148919) problem, not a destination problem.  If that's the case, we can go back to writing the right data type, and solve the timezone thing on the sources?

**Comment by evantahler** [comment]
@aaronsteers recently [looked into this](https://airbytehq-team.slack.com/archives/C046LMDDY6N/p1697505265676529?thread_ts=1695064900.052369&cid=C046LMDDY6N)... I think things are OK.
