### ISSUE TITLE
1s1t: SQL query logs are truncated

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#29086]
connector log messages are truncated beyond a certain length. This means that (for streams with a lot of columns) we don't log the full query. We want to log the full query, so do something about this.
![image](https://github.com/airbytehq/airbyte/assets/5741425/bc0b1ccf-3d33-4add-9bff-4c07dc481788)

**Comment by evantahler** [comment]
Split the line into multiple maybe?

**Comment by edgao** [comment]
sounds right to me. just need to find the max log length, and then write some sort of "repeatedly split this string at the last newline before X characters" loop

**Comment by evantahler** [comment]
I'm going to close this for now.  We'll remove the logs at some point soon anyway (https://github.com/airbytehq/airbyte/issues/29956)
