### ISSUE TITLE
Gradle not cached, installed on every run

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#29111]
## Problem
We install gradle everytime we build java connectors

## Why
Gradle is dumb and reinstalls itself

## Solutions
1. in `with_gradle` prerun `./gradlew` to get it to install itself
2. set `gradle/wrapper/gradle-wrapper.properties` based on this [forum post ](https://discuss.gradle.org/t/why-does-gradle-try-to-download-itself-when-i-execute-gradlew-bat-run-even-though-i-already-have-gradle-installed-and-gradle-home-set/5867/2)

## Appendix
1. [slack convo](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1691184919176449)

**Comment by postamar** [comment]
https://github.com/airbytehq/airbyte/pull/30384 effectively implements solution 1, and the gradle cache ensures that it's not downloaded more than one. This isn't ideal, so feel free to reopen if more needs to be done.
