### ISSUE TITLE
Source Stripe: to Bigquery: no per stream state ?

### ISSUE THREAD

**Issue by dis-sid** [airbytehq/airbyte#29124]
### Connector Name

source-stripe

### Connector Version

3.17.0

### What step the error happened?

Other

### Revelant information

Airbyte version: 0.50.12

Hi,

I have three connections feeding my BigQuery data warehouse on a fresh 0.50.12 install (on k8s using Helm). For the two Stripe connections every time I add a new stream or modify an existing one in any way I'm asked to reset all my streams.

![demo](https://github.com/airbytehq/airbyte/assets/9008952/86af300c-97a6-4271-980f-6b8ca1637f81)

We had a previous install of Airbyte and I don't remember having to reset/resync all the data everytime we added or changed a stream what could be the cause ?

### Contribute

- [ ] Yes, I want to contribute

**Comment by Jgerardopine** [comment]
@dis-sid  I think is a bit late. I think the bug was removed in the new versions. I am using 0.50.54, and al lis good. You should upgrade to the newest version.

![stripe_per_stream](https://github.com/airbytehq/airbyte/assets/20849578/21218f79-b9bd-4305-a227-54af535618bb)

I am closing the issue
