### ISSUE TITLE
google sheets

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29138]

**Comment by axxander** [comment]
@RealChrisSean I would like to give this a go

**Comment by RealChrisSean** [comment]
This has been assigned to you. Good luck!

**Comment by axxander** [comment]
@RealChrisSean Hey, just wanted to check my understanding. Is it possible to migrate this connector to the low/no-code version? We can handle OAuth, but I'm not sure we can handle service account credentials this way. WDY?

**Comment by RealChrisSean** [comment]
You're right this may not work. :( Please feel free to work on another issue!
