### ISSUE TITLE
Connector build failed 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#29131]
### Topic

building connector task failed

### Revelant information

**Steps:**

1. Remove all the images in local repo

 docker image prune -a

2. run docker build 

 gradle :airbyte-integrations:connectors:source-mssql:build

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-integrations:bases:base:airbyteDocker'.
> Process 'command '/Users/sivakumarramaswamy/projects/airbyte/tools/bin/build_image.sh'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 15s

**Workaround/fix:**

 Create a airbyte directory in base image . (cd airbyte/airbyte-integrations/bases/base)

RUN mkdir /airbyte

**Comment by marcosmarxm** [comment]
Gradle was deprecated, use `airbyte-ci` instead.
