### ISSUE TITLE
[source-mysql] connection to BigQuery succeeded but no new data uploaded

### ISSUE THREAD

**Issue by alvarogracia** [airbytehq/airbyte#29154]
### Connector Name

source-mysql

### Connector Version

2.0.1

### What step the error happened?

During the sync

### Revelant information

We stop syncing a big table because we had a duplicate issue but since then we have not succeeded to sync any of the daily syncs or manual syncs either.
Many times the sync raises an error Failure Origin: replication, Message: Something went wrong during replication and the logs raise:
`ERROR i.a.w.g.DefaultReplicationWorker(replicate):257 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.internal.exception.SourceException: Source cannot be stopped!`
However there has been 1 successful sync but the data hasn't been uploaded to BigQuery. I attach the logs from the failing syncs.

[failed_sync.txt](https://github.com/airbytehq/airbyte/files/12279025/failed_sync.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
We've made dramatic improvements in checkpointing and reliability since this issue was written.  Closing... please try your sync again!
