### ISSUE TITLE
Don't ask for "Reset" when only adding/deleting streams

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29159]
When saving the catalog for a connection, the user is always presented with the "reset affected streams" dialog. If the only diff in the catalog, the user should not need to reset anything, and therefore should not see the dialog box.

<img width="694" alt="Screen Shot 2023-08-07 at 4 07 59 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/66136048-697f-4ef8-8eb1-ffb61cc17733">

Across the different actions a user/Airbyte can take for a connection, the add/remove stream case is the only one that clearly does not need a reset. https://docs.google.com/spreadsheets/d/1lQlm4j8FS8nD6lKRR_YrNsmqcm04NQl-4wrLrjQEE5Q/edit?usp=sharing

And (can create another issue if it makes sense): some user feedback we received around showing the streams that will be reset: 
> The customer would appreciate more specific schema change notifications that detail which streams will be reset: “The popup that says ‘reset affected streams’ is less anxiety-inducing if you said which streams. In theory it says what schema changes, which of those schema changes require a refresh, when I'm clicking a button" highlights this requirement.”

**Comment by josephkmh** [comment]
Refining notes:
- We already have some logic in `ConnectionReplicationPage:onFormSubmit()` that decides whether to set `skipReset` to `true` or `false`. We just need to extend that logic.
