### ISSUE TITLE
Postgres Source - Unable to handle jsonb[] (regression)

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#29172]
### Connector Name

destination-bigquery

### Connector Version

1.7.2

### What step the error happened?

During the sync

### Revelant information

Normalization: raw data (json)
Source: Postgres v3.0.2

In table A (at Postgres) we have a field `tags` (jsonb[]), so the data stored, looks like this: 
```
{"{\"key\": \"xxx_field\", \"value\": \"DEFAULT\", \"yyy_field\": true}","{\"key\": \"zzz_field\", \"value\": \"obfuscated\", \"rrr_field\": false}"}
``` 

Or like this:

```
{"{\"key\": \"xxx_field\", \"value\": \"DEFAULT\", \"yyy_field\": true}"}
```

The BigQuery Destination v2 connector, write the data in the `_airbyte_data ` like this: 

```
{
  "tags": "{\"{\\\"key\\\": \\\"origin\\\", \\\"value\\\": \\\"obfuscated\\\"}\"}"
}

```

In the final destination table, airbyte is unable to handle the `tags` field content, so it will be ignored with this message in the `_airbyte_meta `: 

{"errors":["Problem with `tags`"]}

**Expected bahaviour:**
Just set the field content in the final destination table.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Grooming:
* we will research sources sending JSONB[]s and see what destinations V1 does.  destinations v2 is different, we will fix it, if not, we will wait until our JSONB project in the next few months. 
*

**Comment by evantahler** [comment]
@haithem-souala - can you please share some examples of what this JSONb[] output looks like in BigQuery for both Destinations V1 and V2?  Ideally, both a screenshot and CSV dump would be helpful, as we want to be very careful with escaping and quotes.   Email would also work - I'm {firstname}@airbute.com

**Comment by haithem-souala** [comment]
Fyi, in destination v1, it's working fine.

**Source (Postgres):**
```
                                                                                             tags                                                                                              
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"selected_carrier\", \"value\": \"obfuscated_val\", \"applyToOrchestration\": false}"}
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"selected_carrier\", \"value\": \"obfuscated_val\", \"applyToOrchestration\": false}"}
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"pricing\", \"value\": \"obfuscated_val\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"carrierMethod\", \"value\": \"obfuscated_val\", \"applyToOrchestration\": true}"}
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}","{\"key\": \"selected_carrier\", \"value\": \"obfuscated_val\", \"applyToOrchestration\": false}"}
 {"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}

```


**Destionation V1**

> _airbyte_raw_table_a:
```
{
    "tags": [
        "{\"key\": \"installation_date\", \"value\": \"2019-09-20\", \"applyToOrchestration\": false}"
    ]
}
```
  
> table_a:
```
[{
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"obfuscated_val\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\"}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"obfuscated_val\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"obfuscated_val\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"obfuscated_val\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\""]
}, {
  "tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\""]
}]
```
//Screenshot
![Capture d’écran 2023-08-09 à 10 22 34](https://github.com/airbytehq/airbyte/assets/75131226/59e755a7-538c-4da8-afe7-0bb8bf0bb500)

**Comment by haithem-souala** [comment]
Any ETA? This issue prevent us from migrating the last DB.

**Comment by cynthiaxyin** [comment]
We were able to repro this issue in BigQuery and Snowflake and are investigating what the fix should be.

It looks like Postgres arrays are defined with curly braces instead of brackets, and v2 is not recognizing this syntax? And maybe there is a discrepancy in when the data is deserialized?
- source data (curly brace annotation + all single quotes) `{"{\"key\": \"pricing\", \"value\": \"DEFAULT\", \"applyToOrchestration\": true}"}`
- v1 raw data (bracket annotation + still single quotes) `{"tags": ["{\"key\": \"installation_date\", \"value\": \"2019-09-20\", \"applyToOrchestration\": false}"]}`
- v1 normalized data (bracket annotation + inner triple quotes) `{"tags": ["\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"obfuscated_val\\\", \\\"applyToOrchestration\\\": true}\""]}`
- v2 raw data (curly brace annotation + inner triple quotes) `{"tags":"{\"{\\\"key\\\": \\\"pricing\\\", \\\"value\\\": \\\"DEFAULT\\\", \\\"applyToOrchestration\\\": true}\"}"}`

Running the SQL that gets output in the V2 logs e.g. <code>JSON_QUERY(\`_airbyte_data\`, '$.tags'))</code>, the result does seem to be better (actually an array) by switching out the curly braces for the brackets.
<img width="962" alt="Screenshot 2023-08-16 at 9 49 54 AM" src="https://github.com/airbytehq/airbyte/assets/22702693/8c38e03a-5ea9-4808-86ec-d33d7874d37e">

Normalization seemed to previously convert arrays to strings around here:
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py#L729-L730
- https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/dbt-project-template/macros/cross_db_utils/type_conversions.sql#L15-L18
- Also see https://www.postgresql.org/docs/9.1/functions-array.html

**Comment by edgao** [comment]
@haithem-souala are there any differences (other than the destinations v2 toggle) between your v1 and v2 connections? Specifically is the v1 connection using CDC and the v2 connection using standard replication?

I ran a v1 sync in standard replication and got the same behavior you're seeing in v2:
![image](https://github.com/airbytehq/airbyte/assets/5741425/1b982fbf-d6cf-479a-be55-751ed3dcc7c2)

![image](https://github.com/airbytehq/airbyte/assets/5741425/b76368f9-117d-431c-8b06-9de118bdb8cd)

And ran a v2 sync with CDC, which seems to have worked:
![image](https://github.com/airbytehq/airbyte/assets/5741425/d5023ee6-e6ac-434d-8bbf-3d2e73394559)
![image](https://github.com/airbytehq/airbyte/assets/5741425/7ef55daf-daa7-42b7-91a2-7e1399edd892)

I think this is a bug in source-postgres, trying to find the relevant issue.

**Comment by edgao** [comment]
couldn't find an existing issue; submitted https://github.com/airbytehq/airbyte/issues/29551

**Comment by haithem-souala** [comment]
The V1 and V2 are both standard replication.
V1: cursor based replication
V2: Xmin

The source-postgres version in V2 -> 3.0.2
The source-postgres version in V1 -> 1.0.30

I hope that will help debugging the bug.

**Comment by edgao** [comment]
interesting! This looks like a source-postgres regression between those versions; can you try downgrading the v2 connection to source-postgres:1.0.30? I ran a cursor-based sync with 1.0.30 + bigquery v2 and got some good results:
![image](https://github.com/airbytehq/airbyte/assets/5741425/3b7b2e12-2eaa-45f6-b7aa-6ef4ca8e48fb)
![image](https://github.com/airbytehq/airbyte/assets/5741425/af0d02b9-1436-401f-bb99-309013549242)

And I'll update the source-postgres issue to note that this is a regression.

**Comment by edgao** [comment]
looks like 1.0.42 is the highest version of source-postgres that supports `jsonb[]` correctly, if you want to give it a try

**Comment by haithem-souala** [comment]
Unfortunately, i cannot downgrade source-postgres to 1.0.42, as it might affect other streams.

**Comment by haithem-souala** [comment]
> > might affect other streams
> 
> can you explain some more on this? My understanding is that the two major releases between 1.x and 3.x were upgrading the underlying debezium library in 2.0.0 (which shouldn't affect non-CDC syncs) and changing how source-postgres's cursor works in CDC mode in 3.0.0 (which, again, only affects CDC syncs).
> 
> also tagging in @prateekmukhedkar for DB sources expertise, in case I missed something in the changelog.

Hey @prateekmukhedkar, we're migration the syncs to V2 destination, and this issue blocking us to migrate the last two sources.

**Comment by haithem-souala** [comment]
Yes, it's working fine, thank you @edgao!
