### ISSUE TITLE
Preview sql in source and destination

### ISSUE THREAD

**Issue by ying-w** [airbytehq/airbyte#29170]
### What area the feature impact?

Connectors

### Revelant Information

In sources and destination, often times there are many options for how to get high water mark (ex. in postgres we have Xmin and choosing a cursor column).

In situations where we would be sending a sql query, can we have preview of based on this schema, what sql query would be sent based off of cursors selected (as a sanity check).

An additional bonus would be the ability to modify the query that's used.

**Comment by evantahler** [comment]
This could be something that is added to the source's documentation if you are interested.
