### ISSUE TITLE
Support to configure `configured_window_days`

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#2917]
## Tell us about the problem you're trying to solve
I need to configure the configured_window_days for Google AdWords tap through config 

## Describe the solution you’d like
There is already support from singer AdWords tap as it can take this from config

## Describe the alternative you’ve considered or used
I have created a fork of google ads connector and used it for now

**Comment by harshithmullapudi** [comment]
#2918

**Comment by cgardens** [comment]
@sherifnada fyi
