### ISSUE TITLE
Stripe connections Internal Server Error: json schema nodes should always be object nodes

### ISSUE THREAD

**Issue by dis-sid** [airbytehq/airbyte#29181]
### Connector Name

source-stripe

### Connector Version

3.17.2

### What step the error happened?

Other

### Revelant information

Airbyte version is 0.50.12.

When refreshing the schema or saving any modifications on one of my stripe connections I get the following error: 

`Internal Server Error: json schema nodes should always be object nodes. path: [FieldNameOrList{fieldName='amount_details', isList=false}, FieldNameOrList{fieldName='atm_fee', isList=false}] actual: ["null","integer"]`

![swappy-20230807_212713](https://github.com/airbytehq/airbyte/assets/9008952/59132748-2dbf-45ff-b269-8d673b687a0f)

### Contribute

- [ ] Yes, I want to contribute

**Comment by davydov-d** [comment]
fixed with 
https://github.com/airbytehq/airbyte/pull/29309
https://github.com/airbytehq/airbyte-platform-internal/pull/8306
https://github.com/airbytehq/airbyte-protocol/pull/44
