### ISSUE TITLE
customer-facing raw table migration sql queries

### ISSUE THREAD

**Issue by Hesperide** [airbytehq/airbyte#29196]
https://github.com/airbytehq/airbyte/pull/29195

* Auto-populate target_stream value based on our naming of raw tables
* Edit Snowflake example
* Make sure it works in practice :)

**Comment by evantahler** [comment]
Grooming:
* given that the user wants to leave an old v1 sync running and not migrate that data, they need a guide to copy the v1 raw data to a v2 raw table non-destrucivley.
  * Maybe what we do is instruct them to make the new v2 connection first are reset so we will have the tables present and named right, then `insert into (select * from)...` 
  * Alternatively, we could make a table name generator in the docs(*) and help them create the new raw table from the old v1 stream names and namespace

Do this 2x - once for BQ and once for snowflake

**Comment by jbfbell** [comment]
Javascript equivalent of raw table naming function

```javascript
function concatenateRawTableName(namespace, name) {
    let plainConcat = namespace + name;
    // Pretend we always have at least one underscore, so that we never generate `_raw_stream_`
    let longestUnderscoreRun = 1;

    for (let i = 0; i < plainConcat.length; i++) {
        // If we've found an underscore, count the number of consecutive underscores
        let underscoreRun = 0;
        while (i < plainConcat.length && plainConcat.charAt(i) === '_') {
            underscoreRun++;
            i++;
        }
        longestUnderscoreRun = Math.max(longestUnderscoreRun, underscoreRun);
    }

    return namespace + "_raw" + "_".repeat(longestUnderscoreRun + 1) + "stream_" + name;
}
```
