### ISSUE TITLE
Allow configuring Facebook Marketing insights buffer days

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2920]
## Tell us about the problem you're trying to solve
Today the Facebook marketing source always defaults to 28 for the buffer_days parameter. We want to make this configurable by the user. We should: 
* Add a parameter to spec.json called `insights_lookback_window` with the title `Insights Lookback Window` and an appropriate description that tells the user what this parameter controls. It should be an optional parameter. 
* This parameter should be used instead of 28 if the user has specified it.

**Comment by po3na4skld** [comment]
Hello @cgardens, what is the maximum value of insights_lookback_window should be?
