### ISSUE TITLE
Connector builder server fails with unactionable error message if the message returned by the CDK is too long

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#29228]
## What
The connector builder server fails with a non actionable error message if the CDK message is too long to be parsed
`The CDK command `test_read` completed properly but no records nor trace were found. Logs were: 0.`

The actual error is swallowed by the `AirbyteMessageDeserializer`. The root of the error is:

```airbyte-connector-builder-server  | Failed to deserialize {}com.fasterxml.jackson.databind.JsonMappingException: String length (5033887) exceeds the maximum length (5000000) (through reference chain: io.airbyte.protocol.models.AirbyteMessage["record"]->io.airbyte.protocol.models.AirbyteRecordMessage["data"])```

- We can fix this by introducing an optional validator to the VersionedAirbyteStreamFactory.
- VersionedAirbyteStreamFactory.toAirbyteMessage will call the validator, which will throw an exception if the String is too long.
- By default, there shouldn't be a validator so the move worker isn't impacted
- The exception will need to be caught so the server can return an actionable error message

[Use this project to reproduce the issue](https://cloud.airbyte.com/workspaces/6dcda098-c47b-4613-87cd-8253b65fb039/connector-builder/edit/5db81577-49c5-420b-8486-82960074d499)

While this will show a better error message, this won't solve the underlying issue, which is that the AirbyteMessage sent by the CDK is too large. This could be solved by changing the interface between the CDK and the connector builder. This can be kept out of scope for this issue.

## Acceptance Criteria
- [ ] The connector builder tells the user it failed to process the request because the response was too large if that was the case
- [ ] The move flow is not affected

**Comment by girarda** [comment]
grooming notes:
- @girarda to create a follow up issue to update the interface between the CDK and Java
- ^would also be useful to allow users to submit test_requests with more records

**Comment by lmossman** [comment]
This was also ran into by Alex Gronemeyer when building for the DoiT API: https://airbytehq-team.slack.com/archives/C03TP6W8081/p1693518590124089?thread_ts=1693516393.919009&cid=C03TP6W8081

**Comment by girarda** [comment]
@lmossman the reason it fails on the connector builder, but not in a normal sync is in the connector builder, we aggregate the request, response, and records per slice so they can be passed to the frontend. The resulting message can be too large to be deserialized. That's not a problem with syncs because we only send the records one at a time.

**Comment by wakewalker** [comment]
I'm running into what I believe to be the same issue here and don't want to create an unnecessary duplicate issue if it is.  I detailed the issue I'm running into in Discussions [here](https://github.com/airbytehq/airbyte/discussions/34239).

I see that this issue remains unassigned.  Has it been triaged?  Is there a sense of when this issue will be picked up?

**Comment by natikgadzhi** [comment]
@wakewalker, triaged, but not picked up yet. We're looking into it now, though.
