### ISSUE TITLE
Source Postgres initial load with ctid sends incorrect state message

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#29237]
### Connector Name

source-postgres

### Connector Version

3.1.3

### What step the error happened?

During the sync

### Revelant information

Initial load for incremental postgres syncs is done via ctid.
We chunk the work to sub queries, each reading 1GB.
The issue: each chunk ends with emitting a "final" state message which indicates that we're done with ctid load and switched over to incremental sync (xmin, cdc, cursor - whichever is configured),
If the sync were to fail between sending this erroneous final message and before the next chuck sent a correct "ctid" type state message, then the next attempt will do an incremental sync.
This window of failure is not very big, but we should not send the final state message until the last chunk actually finished.

(h/t @akashkulk for pointing out this problem)

### Contribute

- [ ] Yes, I want to contribute

**Comment by prateekmukhedkar** [comment]
Each chunk should only send its state message and not the final message.

**Comment by rodireich** [comment]
This is a false alarm. 
Sub queries are actually two level below state iterator. 
The design works as expected
