### ISSUE TITLE
[source-Outreach] `sequenceSteps` incorrect data

### ISSUE THREAD

**Issue by Michae94** [airbytehq/airbyte#29247]
### Connector Name

outreach

### Connector Version

0.4.0

### What step the error happened?

During the sync

### Revelant information

Small issue detected during the sync of sequenceSteps of outreach data: sequenceStates data are retrieved instead.   
The issue has been identified: https://github.com/airbytehq/airbyte/pull/26211/files#diff-c249d04a489454204a039380623ffaf7649fb1fd4aef889d0ddd9222fe6eca92R138

Here, there was a typo in the source.py file: `return "sequenceStates"` should be replaced by `return "sequenceSteps"`

### Contribute

- [X] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
