### ISSUE TITLE
:sparkles: Source Convex : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29267]
https://docs.airbyte.com/integrations/sources/convex

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by Krishnan-Raghavan** [comment]
Hello. I want to give this a shot though I am unfamiliar with exactly what needs to be done and would be obliged if someone could guide me a bit regarding the same. @RealChrisSean, could you please assign this to me?

**Comment by donjne** [comment]
@RealChrisSean Hello, I'd be thrilled to elaborate on Convex's data management capabilities. With Full Refresh, Incremental Sync, and Change Data Capture support, Convex is indeed a powerful data landscape. I'd love to discuss more on how it can elevate user's data strategy. Thankyou for considering!

**Comment by justinbchau** [comment]
@Krishnan-Raghavan you already have an issue assigned to you so I will leave this open to give others a chance. If you rasie a PR for your issue and this one is still open, let me know and I can assign to you.

**Comment by marcosmarxm** [comment]
It uses dynamic schema and it isn't possible to migrate to low-code.
