### ISSUE TITLE
customer.io

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29269]
https://docs.airbyte.com/integrations/sources/customer-io

**Comment by btkcodedev** [comment]
I would like to work on this issue,
Also it is within Faros AI repo, so it will be like a new connector to airbyte src,
Should raised PR to master branch of Airbyte right?

**Comment by btkcodedev** [comment]
@RealChrisSean Raised PR https://github.com/airbytehq/airbyte/pull/29385

**Comment by RealChrisSean** [comment]
Amazing!
