### ISSUE TITLE
Cockroachdb

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29263]
https://docs.airbyte.com/integrations/sources/cockroachdb

**Comment by mihir-k9** [comment]
Hi @RealChrisSean, please assign this to me.

**Comment by mihir-k9** [comment]
Hi @RealChrisSean , I can't work on this, thought it was new requirement. Didn't know you already had code in Java. Tested the connection using the UI, that works. What else did you need on this?

**Comment by RealChrisSean** [comment]
Hey @mihir-k9 you were able to get this to work successfully with the connector builder?

**Comment by mihir-k9** [comment]
Yes, but could not run the unit test / integration test.
