### ISSUE TITLE
:sparkles: Source Fauna : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29278]
https://docs.airbyte.com/integrations/sources/fauna

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by AsaoluElijah** [comment]
Hi @RealChrisSean I’d love to work on this.

**Comment by justinbchau** [comment]
you got it @AsaoluElijah
