### ISSUE TITLE
Consume new connection status endpoint

### ISSUE THREAD

**Issue by chandlerprall** [airbytehq/airbyte#29274]
Being added in https://github.com/airbytehq/airbyte-platform-internal/pull/7793 , the platform will compute some inputs needed in `useConnectionStatus` instead of the webapp pulling in the last 10 jobs and doing our own calculation.

This is a drop-in replacement for the values in `useConnectionStatus`, but to power statuses in the connection list table we ~need to~ strongly should batch the individual requests together to the new endpoint.

**Comment by josephkmh** [comment]
Refining notes:
- Chandler working on this
- New endpoint required is already merged
- Only for the connection status page, not for the connection list table

**Comment by tealjulia** [comment]
Refining notes:
- we _can_ consume it, but we need to sync with BE engineers on some more data (config error data) that we need to deprecate the old one
