### ISSUE TITLE
Exchange Rates Api

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29276]
https://docs.airbyte.com/integrations/sources/exchangeratesapi

**Comment by btkcodedev** [comment]
I would like to work on this :)

**Comment by btkcodedev** [comment]
@RealChrisSean Raised PR #29299

**Comment by RealChrisSean** [comment]
You are too fast. Let people catch up lol.

**Comment by btkcodedev** [comment]
Oops. It didn't get assigned I think :p

**Comment by btkcodedev** [comment]
@RealChrisSean Its not blocked, all test are passing in local :)
