### ISSUE TITLE
Gridly

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29282]
https://docs.airbyte.com/integrations/sources/gridly

**Comment by btkcodedev** [comment]
Copper api will take time, I've requested free trail, will take other issue until that

**Comment by btkcodedev** [comment]
Please assign this to me :)

**Comment by btkcodedev** [comment]
@RealChrisSean Raised PR https://github.com/airbytehq/airbyte/pull/29647

**Comment by RealChrisSean** [comment]
Amazing!

**Comment by sajarin** [comment]
Closed - see issue [comment](https://github.com/airbytehq/airbyte/pull/29647#issuecomment-1703025624)
