### ISSUE TITLE
:sparkles: Source Firebolt : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29280]
https://docs.airbyte.com/integrations/sources/firebolt

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by shivam096** [comment]
Hey @RealChrisSean ,

I would like to take this up. Will I be provided with the credentials of firebolt ?

**Comment by RealChrisSean** [comment]
Hello this has been assigned to you good luck!

**Comment by shivam096** [comment]
Hey @RealChrisSean ,

Can you provide me with the credentials to access a Firebolt instance?

**Comment by shivam096** [comment]
Need credentials to work on this application
Currently blocked as it requires a subscription via AWS which is paid
