### ISSUE TITLE
Destination snowflake v2: skip T+D if no records have been loaded for the stream?

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#29291]
there's some interaction between async + T+D that causes us to run T+D even though no records have been committed to the raw table. E.g. for [this sync](https://cloud.airbyte.com/workspaces/b61bc266-ef3c-460c-af2f-f70da4a2993c/connections/a54f466c-83a6-40e7-ae86-6e79961040d5/job-history#3934938::0), this T+D run accomplished nothing:

```
2023-08-09 16:55:15 destination > INFO i.a.i.b.d.t.DefaultTyperDeduper(typeAndDedupe):96 Attempting typing and deduping for v2-internal-staging.products
```

**Comment by evantahler** [comment]
Closing this - I think we always want to run T&D in case there were left-over records from a previously failed sync.  https://github.com/airbytehq/airbyte/issues/28380 should make T&D more efficient in this case
