### ISSUE TITLE
Send Orbit event after setting preferences

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#293]
## Tell us about the problem you're trying to solve
We need to know when a community member has deployed Dataline from within Orbit, so we can address this person differently, or send an email / swag / etc. 
The issue is we can only know if a person deployed Dataline if they give us their email address when setting up their preferences. Otherwise, we won't be able to link a community member to a deployment.
That's why this event to Orbit should be sent when user clicks on "Continue" in the preference onboarding page.

## Describe the solution you’d like
Here is the JSON that we should send:

```json
curl -X POST “https://app.orbit.love/orbit/activities?api_key=ob_6gypZ9Vmosyuvj9dXnpG” 
	-H “accept: application/json” -H “Content-Type: application/json” 
	-d “{ \”description\”: \”Deployed and input email address\”, \”score\”: 3, \”title\”: \”Deployed Dataline\”, \”occurred_at\”: \”YYYY-MM-DD\”}”
```

`occurred_at` should be a valid ISO 8601 date. All times UTC. 

**If user doesn't input their email address, nothing should be sent to Orbit unfortunately. 
If user chooses to anonymize their data, nothing should be sent too.**

cgardens

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368225081245) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@johnlafleur is this still needed or is it done?

**Comment by johnlafleur** [comment]
This one is done indeed.
