### ISSUE TITLE
Update Connector CI to report status to Github Status Checks not comments

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29300]
Some connector developers are wary of pushing often to Github because CI spams comments onto their PRs, especially if you are working on multiple connectors.  This makes seeing PR reviews and comments hard.

Right now, CI leaves both a comment and a Github Status check (1,2) for every test (from https://github.com/airbytehq/airbyte/pull/29213) 

<img width="936" alt="Screenshot 2023-08-09 at 12 13 17 PM" src="https://github.com/airbytehq/airbyte/assets/303226/778ff302-341a-4e0a-8856-6cd252973531">
<img width="894" alt="Screenshot 2023-08-09 at 12 13 13 PM" src="https://github.com/airbytehq/airbyte/assets/303226/dcd7528a-8b56-46f1-8ff2-69a6d9ca2eeb">

Now that we have excellent CI reports ([e.g.](https://ff2e9b0faf2538f560688912502dce1da66d5d28ab8531a0b70ed7f-apidata.googleusercontent.com/download/storage/v1/b/airbyte-ci-reports-multi/o/airbyte-ci%2Fconnectors%2Ftest%2Fpull_request%2Fedgao_faker_schema%2F1691538991%2Fc1e8cf503fbc8710da43995f83f6162815599395%2Fsource-faker%2F5.0.0%2Foutput.html?jk=ATmLuOH1vZ_uWOTfKiL4wULjpiMYD283YR3L99ZlGOP1I85v_Em6-GIreBi-xShiG37RnokCGjfw3pS2je_noyWr7a1YzSwmaio0LV6As6Rb8omtwKc_oApLU6YpGLwb_bwDII8ihFijPrIuKmGwi96x8tdXp6RXrg7Lf4ngQ_dhaAKek8sDkeoO_pcA_7YpgSuJci9pKAVcP42xSUrSjxunuBDQEDN_C_BkG4FeBCpbQRTy_-n4tfTipv0ArOE3qE3v6lHagVOqaYsbTVowZQxIxLs4ic7y9MpdFJJIiu3MwawVAzCshur19p9JPnt8hmT_lD5APP5QsysQxgUWeI4MxJYYYuS1EhW37lBRkQkiKzkErmLW4_VOvEtLHdmg9SuoFJKw5Y3zyuZBrGfQdlp1q6Ywh99jfYMZKV1eeqQ3t66zsWQ1Fpfh_WWilexKLxaiHOGD5-HPKJTP4mCMdDeypCdSTRCfPqHuivBnn21r6afifYlLD2WVztCxBMiF1v5riUmTvW24rtfDIO8Hg7AnjozE-gRVdghgG8tk1__x13a5MlB_eSIjR3dYYzHY_hRFKgPwi7NfsyyJTFT7nazEplOtOzJQUiufPtUkSCDj5T8cd9dXIZWSHEmu_ckfeCKotgQRnrnFO3r-BgipNYWSN3EIEUBh6mmf2TzjXFgt0apurd-_esy_1CCVq6PtxCr9UVVTYBPQL2fBlIwxImrdpSE19ntxKTHKJdtsllZzfuyNwhz562dpOkgMUQUqXKz7CEA9b99ywBE1hIARJoAb48iOwrQbgzeGC-sXUqcU6tOqf4yiikdGcQexieEBLEulV7uieWakOhfTo-Fn8olsbvGzZREyhlpGFCis2229-BV7rK78g7dNsdezoWAJmNRhJkzabCc1U01N8VahnMHsSKWuWnapN1icU2xz6wj-MR9gcKZAQlLB47ZrskzWQxXq5qRbY3Hghb319xJ0PwYhyvKjqPex1ilMRwhpiexCbCOMh-OzC-5cL1LywBwlgWsJYW-01anl91ii-7_v8cc4hmRTXWAgtEJXg74sF5vj0Sl1dsAXY_4UYiIPsRbQqdxzUQwxiydfTvMnn7gHGvKYQDpmxj4oszN5tegdzMnyFvI1c6tQWZc5-3-TpED8bPp6X_88gtFO8nZAqPr177ZnjpIBOQhaCospc5RiZce4GM0vNbZWh9qLuv768_YUfm_rsQ7UZAWXhfXSsjET4aNn8GSu47UCvzGQq3kYCZBM8-VFW7P7b2t87-3kbOUP2s2BfWX07csz2FMCARrGgdeWEIcujThNHUMFaJ_XvffOcX3rxwXRpbxhbxkLAIRqBxKppychPjQsrhFBXrn9gW-AYMEHN97vjBkMwNibKcOgsGMNmyqJZQx_32priXpSKxeGB6OT&isca=1)), I believe that the need for the Github comment is less than it used to be.  We should change the URL in the Github status to point to this report, rather than the action.  This gives the connector developer the information they need to investigate a failure, without clogging up the PR history.

If we cannot change the status report URL, then we should be updating the existing CI comment rather than making a new one.  This would serve the same goal of spam reduction.

**Comment by pedroslopez** [comment]
grooming:
- Connectors CI test details -> Dagger Cloud
- Individual test step details -> HTML report
- HTML report continually updated upon step start/completion
- Check status should go red immediately upon a failure

**Comment by evantahler** [comment]
I'd like to bring this back as part of the DX work we are doing in Q4 if there's time (cc @bnchrch / @alafanechere ).  It's still rather annoying to get an email/slack for every test run

**Comment by evantahler** [comment]
Grooming:
* Remove the comments
* Update the GHA per-connector status links to point to a new root HTML report that links to all the sub-connector builds

**Comment by alafanechere** [comment]
I disable test reports in comments in PR #31871 .
I'll open a different issue to create a global html reports.
It's a bit more complex to implement currently because we don't have a GlobalContext , reports are attached to PipelineContext that are per connector. PipelineContext are not attached to a higher level object that can gather all of them (and their reports).
