### ISSUE TITLE
Upgrade normalization DBT version to 19.1

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2931]
## Tell us about the problem you're trying to solve
DBT released a new version containing some bugfixes and performance improvements. It's not critical to upgrade to this since none of the features impact us directly. But probably good not to fall behind too much. https://github.com/fishtown-analytics/dbt/releases

## Describe the solution you’d like
Upgrade normalization's [setup.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/setup.py) to use the new DBT version.

**Comment by MarcBuch** [comment]
I'll take it as my first contribution! 🚀

**Comment by michel-tricot** [comment]
Thank you @MarcBuch !!!
