### ISSUE TITLE
How to get `airbyte-app.tar` file for `airbytehq/airbyte-platform`?

### ISSUE THREAD

**Issue by 5ylar** [airbytehq/airbyte#29318]
### Revelant information

I tried to build `airbyte-worker` on my mac via [docker compose](https://github.com/airbytehq/airbyte-platform/blob/main/docker-compose.build.yaml), and failed because there is no `airbyte-app.tar` file which is needed in Dockerfile.

The question is how to get that file?

https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-workers/Dockerfile 
<img width="1128" alt="image" src="https://github.com/airbytehq/airbyte/assets/119652856/133b3ad5-ac78-4f2c-81fa-606b13bc81db">

**Comment by marcosmarxm** [comment]
Don't use the tar directly. Instead, use the Docker container that was built during the process.
