### ISSUE TITLE
Update Hubspot source schema for DestinationsV2

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29345]
With DestinationsV2, whatever is a top-level property becomes a column. This issue suggests denesting some essential top-level properties so the elements within become top-level properties.

The columns names that are generated would be prefixed by the top-level property.  For example, if the JSON is called `counters`, holding values for `bounce`, `click`, the resulting columns would be named `counters_bounce`, `counters_click`

| Stream Name  | Suggestion | Example of fields within top-level property that become columns |
| ------------- | ------------- | ------------- |
| campaign_members | `properties` should be denested by 1 level | all custom fields depending on customer |
| campaigns | `counters` should be denested by 1 level | bounce, click, deferred, delivered, dropped
| companies | `properties` should be denested by 1 level | all custom fields depending on customer
| contact_lists | `metaData` should be denested by 1 level | error, lastProcessingStateChangeAt, lastSizeChangeAt
| contacts | `properties` should be denested by 1 level | all custom fields depending on customer
| contacts_list_memberships | no changes needed | none
| contacts_merged_audit | 'merged_from_email, `merged_to_email` should be denested by 1 level | selected, source-id, source-label
| deal_pipelines | no changes needed | none *note this would ideally be a unioned table of all stage dates (one stage per pipelineID per row) but that is out of the scope of this issue
| deals | `properties` should be denested by 1 level | all custom fields depending on customer
| deals_archived | `properties` should be denested by 1 level | all custom fields depending on customer
| email_events | no changes needed | none
| email_subscriptions | no changes needed | none
| engagements | `associations` and 'metadata' should be denested by 1 level | dealIds, marketingeventIds
| engagement_calls | `properties` should be denested by 1 level | all custom fields depending on customer
| engagement_emails | `counters` should be denested by 1 level | bounce, click, deferred, delivered, dropped
| engagement_meetings | `properties` should be denested by 1 level | all custom fields depending on customer
| engagement_notes | `properties` should be denested by 1 level | all custom fields depending on customer
| engagement_tasks | `properties` should be denested by 1 level | all custom fields depending on customer
| form_submissions | no changes needed | none
| forms | no changes needed | none
| goals | `properties` should be denested by 1 level | all custom fields depending on customer
| line_items | `properties` should be denested by 1 level | all custom fields depending on customer
| marketing_emails  | no changes needed | none
| owners |  no changes needed | none
| products | `properties` should be denested by 1 level | all custom fields depending on customer
| property_history | `properties` should be denested by 1 level | all custom fields depending on customer
| subscription_changes  | no changes needed | none
| ticket_pipelines | no changes needed | none
| tickets | `properties` should be denested by 1 level | all custom fields depending on customer
| workflows | `contactListIds` should be denested by 1 level | active, completed, enrolled, succeeded

**Comment by lazebnyi** [comment]
Hey @nataliekwong 
Can you help me understand the profit of this changes, because the result of forcibly updating the schema seems to introduce unnecessary dependencies.

**Comment by nataliekwong** [comment]
My understanding is that with the breaking change to destinations, the normalization that typically takes place after the sync will not be available to users any longer. That means their schemas will change from what they are used to seeing, and we should support those users in migrating easily to Destinations V2 by ensuring their schemas remain consistent with what they already have. This means the connector (Hubspot) will need to support the normalization that was previously handled by dbt. Hubspot is one of our more commonly used API sources, with a larger amount of data flowing through it, so mitigating churn from this group of users should be a priority.

cc @sherifnada @bmcgilli

**Comment by lazebnyi** [comment]
@nataliekwong Thank you for the update. If I understand correctly, we intend to modify the schema and map fields with values so that we don't perform normalization for Hubspot and potentially other sources in the future?

**Comment by bmcgilli** [comment]
Update: we just discussed with Sherif. We will proceed with Hubspot to start, and try to observe patterns with the first few connectors before making a blanket change/process for all sources. @lazebnyi let us know if you have any other questions!

**Comment by davydov-d** [comment]
@nataliekwong just to make sure we're on the same page: you're saying we need to make some of our top-level properties denested for the users to make sure their schemas in DV2 remain consistent with what they already have. As far as I know, as of now, each top-level property, if it is an object, is denormalized into another *table*. On the other hand, we're now denesting some data to represent it in *columns* which is contradictory. Did I get it right?

**Comment by davydov-d** [comment]
@nataliekwong also a couple of questions regarding the table above:
- `CampaignMembers` is a custom stream with a custom (though predictable at high level) schema - do we need to unnest it's `properties`? Same for all custom streams?
- `Deals`, `DealsArchived`, `Goals` have default fields in `properties` as well as custom. Unnest them all?
- `EngagementEmails`:
> counters should be denested by 1 level

did you mean `properties` instead of counters?
- Do we have to unnest custom properties in all the streams? The table does not contain them all based on what I see in the code.
-  I also can't find some of the fields provided as examples, this could be just a typo though. Do you mind double-checking? (engagements - marketingeventIds; engagement_emails - bounce, click, deferred, delivered, dropped; workflows - completed, succeeded)

**Comment by davydov-d** [comment]
@nataliekwong and one more question - does this apply to the fields under the `properties` entry?
> The columns names that are generated would be prefixed by the top-level property.

**Comment by nataliekwong** [comment]
Hey, thanks for your patience. I'll try to address all the questions.

> you're saying we need to make some of our top-level properties denested for the users to make sure their schemas in DV2 remain consistent with what they already have. As far as I know, as of now, each top-level property, if it is an object, is denormalized into another table. On the other hand, we're now denesting some data to represent it in columns which is contradictory. Did I get it right?

You're correct in that prior to Destinations V2, these were separate tables for each nested field. With Destinations V2 we are now expanding the single table to be wider by creating more columns. The core difficulty for the user is the SQL required to access the nested data. It is much simpler and faster to access the data using SQL when it is columns, compared to when it is a JSON field within a column. Iterating through JSON is not easy in SQL. 

> CampaignMembers is a custom stream with a custom (though predictable at high level) schema - do we need to unnest it's properties? Same for all custom streams?

I think it makes sense to treat both non-custom and custom schemas the same. In that case, we would unnest for both in the same way.

> Do we have to unnest custom properties in all the streams? The table does not contain them all based on what I see in the code.

Similarly to above, ideally we handle them in the same predictable way, so users are not surprised. I may have missed some, as I was using our internal connection to list examples and other user's schemas may be different. 

> I also can't find some of the fields provided as examples, this could be just a typo though. Do you mind double-checking? (engagements - marketingeventIds; engagement_emails - bounce, click, deferred, delivered, dropped; workflows - completed, succeeded)

If you cannot find them, then it could be they are unique to our internal Hubspot, as I was looking at the data emitted from our own connection to create the examples. I trust you have the more complete knowledge of the schema here.

**Comment by nataliekwong** [comment]
> does this apply to the fields under the properties entry? "The columns names that are generated would be prefixed by the top-level property."

Yes, it should be consistently treated. The reason I added this comment was to avoid potential duplication of a column name from the original schema and the unnested schema. Also, this convention would follow the way we had previously done normalization, where the new table for an unnested property was prefixed by the original table's name. See below for an example: "engagements" had a field called "associations", which then became a table called "engagements_associations".
<img width="239" alt="Screen Shot 2023-09-13 at 1 42 23 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/1253aa28-88d3-401d-928e-b0ad5b5c48e9">
