### ISSUE TITLE
Notion: Incremental sync, duplicated rows

### ISSUE THREAD

**Issue by PierreCom** [airbytehq/airbyte#29357]
### Connector Name

source-notion

### Connector Version

1.1.1

### What step the error happened?

During the sync

### Revelant information

Environment
Airbyte version: 0.50.13
OS Version / Instance: Ubuntu
Deployment: docker-compose
Source Connector and version: Notion 1.1.1
Destination Connector and version: BigQuery 1.7.2

# Current Behavior

When configuring a connector to sync Notion (pages stream) with BigQuery as "Incremental | Append" and there are changes in the source data, the last entry from the source data is always added to my destination table.
The default cursor is used (_last_edited_time_)

# Expected Behavior

If there is no new data, I don't expect any rows to be added to the raw destination table.

# Steps to Reproduce

Setup Notion/Bigquery "Incremental | Append"
Sync multiple times and change with new entries in the source for each sync.
Observe the last entry row in the raw destination table

Thanks 🌞 

### Contribute

- [ ] Yes, I want to contribute

**Comment by lazebnyi** [comment]
The duplication is expected since the data is requested with a "greater than or equal to" condition for the state value. To prevent duplicates, please use the Incremental | Dedup method.
