### ISSUE TITLE
Failure post sync within dbt custom transformation

### ISSUE THREAD

**Issue by jasonmaddernstudylink** [airbytehq/airbyte#29352]
### Topic

missleading failures

### Revelant information

Hi folks, 

I have many connections all running a custom DBT transformation AFTER it does the regular incremental sync + stock normalisation.

So essentially:

1. Pipeline with incremental sync
2. DBT Normalisation post sync
3. DBT custom run post sync

When the DBT custom normalisation in step 3 fails, airbyte will retry the entire connection 3 times. However, it also re-does all of step 1 & 2, essentially re-syncing all the data and eating 3x the warehouse credits. 

Given this is a specific post step, there is no need to retry the sync again when it has already been successful. Can we look at in the event a POST sync error occurs, only retrying that post sync action (not everything).

Thanks, Jason

**Comment by cgardens** [comment]
We aren't going to pick this up. We want to stay away from orchestrating dbt. We recommend using Airflow or Dagster to do this orchestration. [Docs](https://docs.dagster.io/integrations/airbyte).

**Comment by jasonmaddernstudylink** [comment]
Do you have a timeframe for when the current DBT transformations will be sunset/removed @cgardens?
