### ISSUE TITLE
Datetime column format changes between source and destination

### ISSUE THREAD

**Issue by dineshkumar-23** [airbytehq/airbyte#29367]
### Topic

datetime column issue

### Revelant information

Hello,
I am currently facing the same issue of the datetime formats with Airbyte.

I have a aks cluster where airbyte and postgres db are deployed as helm charts. I have a connection in Airbyte where the source is a table in external MSSQL server and the destination is a postgres db running inside the cluster.

I have few datetime columns in my MSSQL table where the format of value is like "2023-07-31T02:19:10Z". When I do the sync in the connection, the sync is successful and the data is written to the postgres. But the values of datetime columns in the postgres are "2023-07-31T02:19:10.000000Z".

I would like to have the same format of datetime columns as the source in my destination.

Further details:
I am using helm chart to deploy Airbyte in my cluster.
repo: https://airbytehq.github.io/helm-charts
chart version: 0.47.16
app version: 0.50.12
source: Microsoft SQL Server (MSSQL) ALPHA
destination: Postgres

**Comment by evantahler** [comment]
Closing - this conncetors have been updated significantly since this issue was posted.
