### ISSUE TITLE
Source Hubspot: Insufficient scopes were provided error message

### ISSUE THREAD

**Issue by wei-kortx** [airbytehq/airbyte#29375]
### Connector Name

source-hubspot

### Connector Version

1.4.0

### What step the error happened?

Configuring a new connector

### Revelant information

Encountered during Oauth after selecting the account error message. 
<img width="586" alt="Screen Shot 2023-08-11 at 3 21 58 PM" src="https://github.com/airbytehq/airbyte/assets/38010670/fb6713b9-dc3e-4e3f-ab7d-29cabe3d8d6c">

### Contribute

- [ ] Yes, I want to contribute

**Comment by arsenlosenko** [comment]
work on this issue will be done in scope of this ticket:
https://github.com/airbytehq/oncall/issues/2741
when issue will be resolved there I will notify about that here, closing for now.
