### ISSUE TITLE
Auto-refresh schemas before every sync

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29373]
Automatically refresh the schema before every sync. Today, it's run every 24 hours. 

This makes it difficult to understand when the schema update will be propagated, and causes some additional downstream quirks, as shared by @mfsiega-airbyte in Slack (link below):
https://airbytehq-team.slack.com/archives/C05LPRV4Z88/p1691745438242189

Suggestion is to have both running (prior to every sync and every 24 hours), to solve for faster detections but also detect for manual or periodic (weekly/monthly) connections.

**Comment by GKTheOne** [comment]
This! When schema changes at source I want the sync to at least capture any new data in the raw tables. Otherwise it's lost (forever, at worst, or for incremental syncs. At best until next full sync, when you now have a different extract time)

**Comment by GKTheOne** [comment]
FYI, I was able to achieve the result (of schema refresh before a sync) by scripted poking of the Airbyte API before triggering a sync via the API ([using this basic process](https://github.com/airbytehq/airbyte/issues/26399#issuecomment-1876460531)).
However I would like it to be an official feature and not just a lucky hack of API methods 😛

**Comment by nataliekwong** [comment]
Related: https://github.com/airbytehq/airbyte/issues/27460

**Comment by dantonbertuol** [comment]
Hi @nataliekwong , how are you?
I would like to better understand what this functionality will be like. My need today would be that through the API I could activate the "refresh source schema" option, which is present in the connection's replication tab. Will this be available?
![image](https://github.com/airbytehq/airbyte/assets/32557284/fe482f24-0fe9-4baa-b658-b5790c707cae)

**Comment by nataliekwong** [comment]
Hi there, we won't be making any changes to the API for now. We are planning to implement the refresh of the source schema before every sync when auto-propagation is enabled (for the two options we have available: propagation of both fields and stream changes or propagation for field changes).

**Comment by nataliekwong** [comment]
This is now available for all Airbyte Cloud users. There is currently no planned date for the release to OSS. It is dependent on another larger project's release first.

To determine if `discover` was run during the sync, you can see a log added to the sync log. The log will start with the text " ----- START DISCOVER ----- "

**Comment by dantonbertuol** [comment]
> This is now available for all Airbyte Cloud users. There is currently no planned date for the release to OSS. It is dependent on another larger project's release first.
> 
> To determine if `discover` was run during the sync, you can see a log added to the sync log. The log will start with the text " ----- START DISCOVER ----- "

Thanks for the feedback. Where will this be published when it arrives for the OSS version?

**Comment by nataliekwong** [comment]
We'll keep this issue open until it is released to OSS, and post an update here when it is.
