### ISSUE TITLE
Pilot with SM

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#2939]
We will help SM manage their Airbyte install.

They will provide a server and we will install and manage the updates of Airbyte

In core they will need:

* [ ] cron scheduling (https://github.com/airbytehq/airbyte/issues/2170)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368225463928) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Gorgias (#2940)
Judge Me
Recharge (#2308)
Bold (#2345)
Everflow
Tune

**Comment by michel-tricot** [comment]
For the configuration of the server we should leverage terraform so we can easily reproduce the install.

We can get in touch with him on slack.

**Comment by davinchia** [comment]
@michel-tricot is this still relevant?
