### ISSUE TITLE
Add more datetime format options (or ability to perform operations) to CDK cursor config

### ISSUE THREAD

**Issue by davidfromtandym** [airbytehq/airbyte#29398]
### What area the feature impact?

None

### Revelant Information

The CDK allows for flexibility in defining the format for outgoing cursor datetimes. However, there are still some limitations. For example, [this API](https://docs.rutter.com/rest/2023-02-07/timestamps) requires timestamps formatted as a UNIX timestamp in milliseconds.

The feature request is to enable additional timestamp formats, specifically related to UNIX timestamps, or to allow simple operations. For example, it should be possible to transform a UNIX seconds timestamp into a milliseconds timestamp by using `%s * 1000`.

![image](https://github.com/airbytehq/airbyte/assets/99083780/8f74a0c4-f492-404e-b08f-929ff7594cf4)

**Comment by girarda** [comment]
@davidfromtandym you can use `%ms` to format the time as milliseconds since the unix epoch if you upgrade your platform to `v0.50.19`

**Comment by girarda** [comment]
closing because ms are available. Feel free to open a new issue if you need more formats
