### ISSUE TITLE
Send Orbit event after implementing connection

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#294]
## Tell us about the problem you're trying to solve
We need to know when a community member has added a new connection so we can better personalize how we address them. 
This event should be sent after clicking on "Set up connection", only if email address was added and data not anonymized. 

## Describe the solution you’d like
Here is the JSON that we should send:

```json
curl -X POST “https://app.orbit.love/orbit/activities?api_key=ob_6gypZ9Vmosyuvj9dXnpG” 
	-H “accept: application/json” -H “Content-Type: application/json” 
	-d “{ \”description\”: \”[SOURCE CONNECTOR] to [DESTINATION CONNECTOR]”, \”score\”: 2, \”title\”: \”Added New Connection\”, \”occurred_at\”: \”YYYY-MM-DD\”}”
```

`occurred_at` should be a valid ISO 8601 date. All times UTC. 

If user doesn't input their email address, nothing should be sent to Orbit unfortunately.
If user chooses to anonymize their data, nothing should be sent too.

cgardens

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368160678734) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Ideally sending to segment would be enough and segment is somehow connected to orbit

**Comment by cgardens** [comment]
Agreed with @michel-tricot. @johnlafleur can you pull this out of segment?
