### ISSUE TITLE
Add a CAT test to ensure the catalog has valid JSON nodes

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#29422]
First noticed: https://github.com/airbytehq/oncall/issues/2703
Sibling Issue: https://github.com/airbytehq/airbyte-platform-internal/issues/8350

## Problem
We do not validate if the catalog emitted from a connector is valid json schema

As a result a catalog was persisted and used for months until the error was eventually caught by the Catalog Diff Method which throws an exception in this case
https://www.jsonschemavalidator.net/s/HU2gflxO
## Quick Fix
We loosened the check of the catalog diff: https://github.com/airbytehq/airbyte-protocol/pull/44

## Long term fix
We add a CAT test that checks that all property nodes are valid json objects

**Comment by lazebnyi** [comment]
PR Merged - https://github.com/airbytehq/airbyte/pull/32787
