### ISSUE TITLE
support index creation on normalization output

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#2945]
Normalization tables are recreated during the current DBT process, which prevents them from maintaining indices that were manually created by the user. For large datasets this can be an expensive process to recreate regularly.

In terms of implementation this may just work after we have incremental DBT support, but it's an important enough issue to track separately.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368225654391) by [Unito](https://www.unito.io)

**Comment by jdclarke5** [comment]
I am interested in this feature. Did you have any ideas on how you see it working mechanically?

It seems natural to me that indexes should be treated on par with the `primary_key` field in the [ConfiguredAirbyteStream](https://github.com/airbytehq/airbyte/blob/479f0d7c8d91b8f609e705417c357c48750010f4/airbyte-protocol/models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L171). Then, in the same way that `primary_key` affects the resulting normalized tables when `destination_sync_mode == *_dedup`, we might have an `indexes` field which gives a way for users to define indexes at configuration time and normalization can then create/propagate. Similarly, the sources themselves can define indexes per-stream; much like `source_defined_primary_key` there could be `source_defined_indexes`. This would give a natural way for indexes to propagate through from some source to the normalized tables without users having to do anything manually.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
