### ISSUE TITLE
Source Salesforce: Extract of history object with incremental append on CreatedDate is duplicating rows

### ISSUE THREAD

**Issue by chancekbarkley** [airbytehq/airbyte#29455]
### Connector Name

source-salesforce

### Connector Version

2.1.0 on platform version 0.50.7

### What step the error happened?

Other

### Revelant information

When syncing some of the History objects from Salesforce to Snowflake, the output seems to be duplicating rows.

We have tried to "reset" the data and resync without luck.

In the screenshot, the ID field should be unique per row.  As you can see the airbyte hash also isn't unique.  The replication settings are configured for Incremental Append based on Created Date, but the created date is the same across all 3 records.
![image](https://github.com/airbytehq/airbyte/assets/16479310/e9b40ce8-ade3-45f6-a219-e6e81347daae)

It is worth noting that the manually triggered first sync failed, the automatic retry succeeded, and the scheduled sync also succeeded, and there is a record row for a single history record corresponding to each of the 3 sync jobs.

I will attempt to update the source and target connector versions now and reset the tables again tonight to see if it makes any difference.

### Contribute

- [x] Yes, I want to contribute

**Comment by maxi297** [comment]
Hi @chancekbarkley ! It is expected that the source might produce duplicate records. If you want to make sure that there is no duplication, incremental [Append + Deduped](https://docs.airbyte.com/using-airbyte/core-concepts/sync-modes/incremental-append-deduped) is the sync mode you would like to use. Is there a reason you wouldn't be able to use that mode?
