### ISSUE TITLE
lemlist

### ISSUE THREAD

**Issue by RealChrisSean** [airbytehq/airbyte#29452]
[public-apis](https://github.com/airbytehq/airbyte/tree/1219e66fb966f03620db5a2157148e8a5b28abdb/airbyte-integrations/connectors/source-public-apis)

**Comment by RealChrisSean** [comment]
@avirajsingh7 for some reason it wont let me assign this to you.

**Comment by RealChrisSean** [comment]
[public-apis](https://github.com/airbytehq/airbyte/tree/1219e66fb966f03620db5a2157148e8a5b28abdb/airbyte-integrations/connectors/source-public-apis)

**Comment by avirajsingh7** [comment]
@RealChrisSean migrating this is more important
