### ISSUE TITLE
Create Sandbox Shopify account

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2946]
## Tell us about the problem you're trying to solve
1. investigate what is needed to create an Airbyte shopify shop. We can make this an Airbyte-specific shop w tshirts and mugs etc. if needed. 
1. let me know what is needed to create the account, I will unblock as needed
1. we're going to want create fake data which may require actually making purchases of some sort
1. now we have a sandbox that can be used for integrating w shopify tools like recharge

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102235791) by [Unito](https://www.unito.io)

**Comment by bazarnov** [comment]
It's already created and used.
the sore name is : `airbyte-integration-test`
The creds are available in LastPass and GSM once needed.
Closing this.
