### ISSUE TITLE
[destination-snowflake] `_airbyte_active_row` wrong calculation due to _AB_CDC_UPDATED_AT typed as varchar

### ISSUE THREAD

**Issue by Fszta** [airbytehq/airbyte#29472]
### Connector Name

destination-snowflake

### Connector Version

1.2.4

### What step the error happened?

Other

### Revelant information

I have established a connection from PostgreSQL to Snowflake, utilizing CDC incremental sync. This job is scheduled to run every 5 minutes.

I have identified an issue within the `_scd` table where the calculation of the `_AIRBYTE_ACTIVE_ROW` field becomes erroneous when two rows for a same record are emitted / normalized simultaneously and when _ab_cdc_updated_at has milliseconds difference. This discrepancy results in a row that does not represent the latest version of a record in the final table.

Here is an example : 

| _AB_CDC_UPDATED_AT       | _AIRBYTE_EMITTED_AT             | _AIRBYTE_NORMALIZED_AT         | _AIRBYTE_ACTIVE_ROW |
|--------------------------|---------------------------------|-------------------------------|--------------------|
| 2023-07-15T10:24:34Z     | 2023-07-15T10:25:17.221+02:00   | 2023-07-15T10:32:00.668Z     | 1                  |
| 2023-07-15T10:24:34.701Z | 2023-07-15T10:25:17.221+02:00   | 2023-07-15T10:32:00.668Z     | 0                  |

In this example, we can see that both records have been emitted and normalized at the same time, and the first row has been flag as being the current version. However, in reality, the current version should be attributed to the second row, as indicated by the slightly higher timestamp value in the `_AB_CDC_UPDATED_AT` column.

**After few investigation, i discover that `_AB_CDC_UPDATED_AT` is typed as VARCHAR(16777216) in snowflake scd table , this can be the root cause, `2023-07-15T10:24:34.701Z` and `2023-07-15T10:24:34Z` as varchar will not be properly ordered, it can explain why the active row is wrong (in case `_AB_CDC_UPDATED_AT` is used in the implementation)**   

**Additional informations**
- Airbyte v0.44.7 running on kube
- destination-snowflake v1.2.4
- source-postgres v3.0.2

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
We've dramatically changed how Snowflake writes data with [destinations v2](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2/) - closing this issue.
