### ISSUE TITLE
Show versioned connector documentation in UI

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#29486]
## Context

In https://github.com/airbytehq/airbyte/issues/29400, we started publishing versioned connector documentation to GCS as part of the connector publishing pipeline.

This issue is about pulling those versioned docs into the UI, so that the correct version of documentation is shown when setting up a connector.

## Acceptance Criteria
- Add an endpoint to the backend API to retrieve docs for a connector
- When loading connector documentation in the UI, first attempt to load the versioned `doc.md` or `inapp.md` from the `prod-ab-connector-docs` GCS bucket based on the current connectors active version
- If that fetch fails, use the bundled `/build` docs as we do today

**Comment by lmossman** [comment]
@lmossman to check if CORS will be an issue

**Comment by josephkmh** [comment]
> If that fetch fails, use the bundled /build docs as we do today

I would hope we can remove the bundled `/build` docs if we're hosting versioned docs on GCS. Is there a valid reason why this fetch might fail? Or is it a "just in case" fallback? I'd suggest removing the bundled docs altogether if possible!

**Comment by lmossman** [comment]
@josephkmh great points, I actually had a similar conversation with Tim today and he had similar thoughts which I agree with
- We should remove the bundled docs from the webapp build so that we don't need to have docs in two places and improve build times
- If GCS cannot be hit for whatever reason (e.g. airgapped environment) then we will just render a link to the docs.airbyte.com page instead
- About every version vs latest version, I don't think I was very clear here before:
  - As part of this project, we will be publishing versioned docs for every new version of every connector as part of the publish step
  - My comment about was more about wanting to avoid having to go back and published versioned docs for every past version of every connector as well; though, since that is basically the value of this project, maybe that effort to write a script for this would actually be worth it
  - Either way, if we do not have the doc for a specific version, we can just fall back to the "latest" doc on GCS rather than falling back to `/build`, so no need to keep that around

**Comment by lmossman** [comment]
Request from Natalie/Amalia - we should actually always render the link to the full connector documentation, even if we successfully retrieve the connector docs to display in the app, since it is still useful to have a link to the full documentation
