### ISSUE TITLE
Stream prefix ignored for tmp tables

### ISSUE THREAD

**Issue by Hesperide** [airbytehq/airbyte#29496]
When syncing a stream called users, if I see right we create a table called `users_airbyte_tmp`. That errors out with SQL compilation error: `Object 'ALEXC_TEST_SCHEMA."users_airbyte_tmp"' already exists. , even though I added a destination stream prefix.`

Should we be creating {prefix}_users_airbyte_tmp instead to reduce the number of collisions?

Failing job: https://cloud.airbyte.com/workspaces/64be1440-f86a-4b99-9326-7f96b793a660/connections/0b48f9bd-2546-4789-894e-8d20c1bc699d/job-history#4055531::4 (this is a reset).

I resolved this issue by dropping the existing tmp table in my destination.

**Comment by edgao** [comment]
looks like platform just didn't set the stream prefix on the first reset attempt. closing as not a dv2 issue. https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1692227246427719?thread_ts=1692159916.255779&cid=C03C4AVJWG4
