### ISSUE TITLE
[source-MongoDB] Schema discovery is limited by the use of "$limit" rather than "$sample" in large collections

### ISSUE THREAD

**Issue by FarisSquared** [airbytehq/airbyte#29512]
### Connector Name

source-MongoDB

### Connector Version

0.2.5

### What step the error happened?

Other

### Revelant information

Schema discovery is limited by the use of "$limit" rather than "$sample" in large collections

Missing critical keys (fields) that only exist in 6% of documents in the collection. 

MongoDB's Compass client can see these fields because it uses $sample in it's schema discovery aggregation pipeline 

### Contribute

- [X] Yes, I want to contribute
- https://github.com/airbytehq/airbyte/pull/29511

**Comment by FarisSquared** [comment]
https://github.com/airbytehq/airbyte/pull/29511

**Comment by evantahler** [comment]
Since this issue was written, we've dramatically revamped the connector.  Please try your sync again with the latest connectors and platform!
