### ISSUE TITLE
Destinations v2: Verify that all values can be written to string columns

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#29524]
https://github.com/airbytehq/airbyte/issues/29365 showed that writing array values to a `{type: string}` column results in a null column + airbyte_meta error in bigquery. We should support converting any value to a string, and write a test that enforces this behavior. More generally, we should support stringifying any value.

## Write a new test case
[BaseSqlGeneratorTest](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-typing-deduping-test/src/main/java/io/airbyte/integrations/base/destination/typing_deduping/BaseSqlGeneratorIntegrationTest.java#L390) is effectively contract-testing the SqlGenerator interface. Add a new test case based on `allTypes`, which verifies that any JSON value (string, number, integer, boolean, null, object, array) can be written successfully to the `string` column.

Ask @edgao to explain what raw/final tables are. The short summary is that raw tables contain entire records as a single JSON blob `_airbyte_data`, and the final tables expand out that data column into real SQL columns. "Typing and deduping" is the process of doing that expansion, and is the system that we'll be testing/modifying in this ticket.

## Run the test and see that it fails
You can run these tests locally. The sqlgenerator tests are pretty straightforward:
1. Use the `ci_credentials` tool to fetch integration test credentials from [GSM](https://console.cloud.google.com/security/secret-manager?project=dataline-integration-testing) (e.g. `VERSION=dev ci_credentials destination-bigquery write-to-storage`)
2. Run your new test from inside intellij:
   ![image](https://github.com/airbytehq/airbyte/assets/5741425/12e51573-5dad-46b2-af19-b7b955623a4a)
   ![image](https://github.com/airbytehq/airbyte/assets/5741425/7971d8e9-7b07-4cf3-9bfe-ce5eeb11063a)
3. It should fail for bigquery, because we know that destination-bigquery doesn't correctly write array values to string columns.
5. Try running your test on Snowflake as well! We don't actually know what will happen :)

## Make the test pass
The code being tested is `BigQuerySqlGenerator.updateTable`, which generates a massive SQL statement. Ask @edgao to explain what this SQL does! (feel free to read it yourself, but it's a lot to understand)

When you run the test, it actually logs the entire sql statement, though it takes a little effort to extract:
![image](https://github.com/airbytehq/airbyte/assets/5741425/76d0f2c4-a22f-4775-89bf-3bfa4ffbd285)

If you trace through BigQuerySqlGenerator, you'll eventually find a method called `extractAndCast`. As the name suggests, this method generates a SQL expression that extracts a field from the raw table's JSON blob, and casts it to the appropriate type. Unfortunately, `JSON_VALUE` returns `null` if it tries to extract an array or object. Update this method to use `JSON_TYPE` / `JSON_QUERY` to detect array/object values and handle them separately, something like this:
```sql
CASE
  WHEN JSON_TYPE(JSON_QUERY(`_airbyte_data`, '$."${column_name}"')) IN ('object', 'array')
    THEN TO_JSON(JSON_QUERY(`_airbyte_data`, '$."${column_name}"'))
  ELSE JSON_VALUE(`_airbyte_data`, '$."${column_name}"')
END
```

If Snowflake's test is also failing, figure out how to make it pass as well :)

## Verify that other tests continue to pass
We have other tests that rely on a Docker image existing. Try running `airbyte-ci connectors --name destination-bigquery build` to build that image. Then try running the `BigQueryGcsTypingDedupingTest` test class. It should succeed.

**Comment by evantahler** [comment]
[Held for Gireesh]
