### ISSUE TITLE
Metadata should be validated that 'regular' and 'strict-encrypt' connectors match

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29561]
See thread: https://airbytehq-team.slack.com/archives/C056HGD1QSW/p1692302895206549

We think the problem occurred because https://github.com/airbytehq/airbyte/pull/28756 was published, but the strict-encrupt metadata didn't match the regular metadata.  That was quickly rectified by https://github.com/airbytehq/airbyte/pull/29545, but by then maybe it as too late?  We should check that these metadata files match in some way.

This problem was also confounded by GHA rate limiting around the same time

**Comment by evantahler** [comment]
Evan's Thesis: 
* The second PR to update the strict-encrypt metadata would have made everything fine, if we didn't have a github action failure (rate limited)
* Re-materializing the failed Dagster `registy_entry` assets was the fix we needed... did the re-run of the github action matter?
*

**Comment by bnchrch** [comment]
closing as no longer relevant
