### ISSUE TITLE
Migration to Certified/Community labels

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29565]
Context: https://airbyte.com/blog/introducing-certified-community-connectors

Full list of changes: https://docs.google.com/document/d/1BjXx4S_P76qgLV2Z4xEcNSJJ_asWeZIW2bjn4YG0ocs/edit#heading=h.gkf8odxw0e10

- The icons should change from “Alpha/Free” and “Beta/Free” to a “Community” icon
- The Source/Destination catalog filters should reflect “Certified”, “Community” and “Custom (if applicable)”
- Modify the warning shown for Alpha/Beta connectors to reflect new Community connector language:
- Connection Page headers should reflect “Community/Certified” 
- Settings pages for sources/destinations should reflect “Community/Certified” 
- Billing Page should show Certified/Community 
- New Source/Destination forms should show Certified/Community

**Comment by josephkmh** [comment]
Refining notes:
- These should all be pretty easy, assuming we have a design for the community icon and the connector registry is updated with new release stages accordingly:
 - Connection Page headers should reflect “Community/Certified”
 - Settings pages for sources/destinations should reflect “Community/Certified”
 - Billing Page should show Certified/Community
 - New Source/Destination forms should show Certified/Community

**Comment by nataliekwong** [comment]
@bnchrch is the point person on Connector Ops (removal of releaseStage and migration to a new field)

**Comment by bnchrch** [comment]
Hey all!

Excited to see you come in.

So to date we have added `supportLevel` to our metadata files, which populate the connector registry, which is ingested by the platform.

I have one final PR in review which will add and backfill these fields in the database and expose them in the UI
https://github.com/airbytehq/airbyte-platform-internal/pull/8316

Once in you should be all set to go

**Comment by lmossman** [comment]
@josephkmh I was about to create a similar issue in the extensibility backlog, since I was under the impression that my team would be taking on this work. Sounds like there may have been a miscommunication on who was working on this?

I'm happy to take on this ticket (likely next sprint) if your team has not already started on it!

**Comment by josephkmh** [comment]
@lmossman no complaints from my side if you want to pick this up, but we need to coordinate this with the [sunsetting of the FCP](https://github.com/airbytehq/airbyte-platform-internal/issues/8456) which has a number of other UI changes. So I think we need to feature flag this and plan to only roll it out (at least on cloud) on Sept 18th with the rest of the FCP changes.

**Comment by lmossman** [comment]
@josephkmh That makes sense, a feature flag definitely sounds useful for coordinating the rollout of these changes.

I will plan to pick this issue up then and put the changes behind a feature flag! Thanks
