### ISSUE TITLE
During reset, clarify actions and add stream details

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29592]
Today we tell users to "reset affected streams" when a schema changes. This is pretty scary because it requires the data to be erased. To help reduce this anxiety and validate why we need to reset the data, we can:
- Say explicitly WHICH streams will be reset (required)
- Explain why (ex. primary key changed, cursor field changed, column added, column dropped, data type changed) (optional, as it likely requires BE work?)

The opt-out function is not clear either.  I don't understand first that I can actually "uncheck" the box but ALSO save changes. A suggestion I'm not married to: 

Have three buttons instead of two, and remove the checkbox option: 
- Save without reset
- Save with reset
- Discard changes

For reference, adding some user feedback we received around showing the streams that will be reset:

- The customer would appreciate more specific schema change notifications that detail which streams will be reset: “The popup that says ‘reset affected streams’ is less anxiety-inducing if you said which streams. In theory it says what schema changes, which of those schema changes require a refresh, when I'm clicking a button" highlights this requirement.”

**Comment by josephkmh** [comment]
Refining notes:
- Instead of three buttons, maybe we could have two radio buttons (unselected) to force the user to make a choice
- We could relatively easily list the streams where we detected a change (this is done on the frontend in `ConnectionReplicationPage.tsx`
- A list of changed streams could get very long. We might need to cap the displayed streams (e.g. `Products, Users, Invoices and 5 others`)

**Comment by chandlerprall** [comment]
refining notes:
- future world we'd like to allow opting in at a stream level instead of all affected streams
- confirm with design when changes/PR is ready

**Comment by nora-airbyte** [comment]
Thought this was worth a pass after all. @josephkmh is the second option similar to what you were thinking with the radio buttons?

![Image](https://github.com/airbytehq/airbyte/assets/146028830/5630637c-67ec-43cd-b480-086c8f62d26e)

**Comment by josephkmh** [comment]
Ooh looks great! Yes the second option is what I was thinking - it seems more clear that the user has exactly two options and must choose one to proceed.

**Comment by josephkmh** [comment]
Refining notes:
- Because we are doing the calculation of which streams are to be reset, we sometimes show this modal in cases when no reset is needed (because the logic on the FE and BE is not exactly the same)
- Is there a way of determining whether the source supports per-stream resets? This probably depends on how the state is being stored (globally vs. per-stream)
- To check with BE: what is the current logic for which streams are reset? Can we get a dedicated API for this, so we don't have to calculate this on the FE and risk drifting again?
- On hold until compose backend devs can help refine

**Comment by guillaume-chech** [comment]
Adding a comment from an heavy user for what it's worth. We're using Airbyte to replicate our PG DB to Snowflake using CDC which is a very common use case. 
We're using CDC for 2 reasons : 
- It's reliable
- We're keeping history of the changes reliably
Problem is, in case of a schema update I have 2 choices : 
- Reset the stream : Fetching all the data again and propagate the schema change -> Clean data but we lose history
- No reset of the stream : No fetching of all the data again but with schema change -> Not clean data but we lose history

What we actually do before propagating a schema change is , Cloning airbyte_internal table of the stream , reseting the stream and then merging back the cloned table in the new stream table. This way we keep the history AND we have fresh data. 

So this leads to 2 questions : 
- Why deleting history or airbyte_internal in case of stream reset ? I understand the philosophy of keeping airbyte internal for yourself ,but using it as a changelog on our side is just too useful not too leak into it . Simply appending new data to past data should have the same impact result isn't ? 
- Maybe we could add a third option of "Soft" stream reset, simply refetching all data but appending it to historical fetches in airbyte_internal.

**Comment by josephkmh** [comment]
@guillaume-chech thanks for chiming in and sharing your feedback!

> Why deleting history or airbyte_internal in case of stream reset ? I understand the philosophy of keeping airbyte internal for yourself ,but using it as a changelog on our side is just too useful not too leak into it . Simply appending new data to past data should have the same impact result isn't ?

We indeed keep `airbyte_internal` as an internal implementation detail that we cannot make any guarantees about. So while what you're doing sounds like it should work, you should be aware that the structure and contents of `airbyte_internal` might change without warning.

> Maybe we could add a third option of "Soft" stream reset, simply refetching all data but appending it to historical fetches in airbyte_internal.

We are aware that some sources (like postgres with CDC) will not be able to provide a full historical record in the case of a stream reset. Currently airbyte does not have a good solution for this use case, but we do have it on our internal roadmap and want to provide support for it. I've added your feedback to our internal doc.

**Comment by nataliekwong** [comment]
Will close this in favor of https://github.com/airbytehq/airbyte-internal-issues/issues/6986

**Comment by guillaume-chech** [comment]
@nataliekwong Any update on the potential soft delete feature? I can't follow the favored issue 😬

**Comment by nataliekwong** [comment]
Hey @guillaume-chech , you can follow on the discussion around soft deletes for CDC here: https://github.com/airbytehq/airbyte/discussions/31242

**Comment by guillaume-chech** [comment]
@nataliekwong Sorry about that, I made a typo issue. I'm not talking about soft delete but soft stream reset. Today stream reset delete data in airbyte internal so all changelogs of records, I'm hoping for a way for reset to fetch a fresh version of each record and append it to the existing changelog for incremental streams.

**Comment by nataliekwong** [comment]
@guillaume-chech If you are using the `Incremental | Append` sync mode, you should be able to use Refreshes to achieve this. A Refresh will pull in all historical data and append it to the existing data. You can see our docs here: https://docs.airbyte.com/operator-guides/refreshes.

It is currently only supported for BigQuery destination, with more coverage coming to additional destinations in the coming months.
