### ISSUE TITLE
New Destination: Oracle DB

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2962]
## Tell us about the new integration you’d like to have
I'd like to be able to send data into Oracle DB, with normalization. 

## Describe the context around this new integration
Oracle is one of the most popular databases in the world and so Airbyte should support it :) 

## Describe the alternative you are considering or using
singer target or in-house integration

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368160931461) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
There is a community maintained DBT connector for Oracle which we can use: https://docs.getdbt.com/docs/available-adapters

**Comment by masonwheeler** [comment]
Fixed by #3872
