### ISSUE TITLE
Support for incremental syncs without a cursor

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29633]
re: https://github.com/airbytehq/oncall/issues/2770
re: https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1692391346460389

There exist incremental syncs which do not have a cursor, like xmin postgres sources.  The relevant entries in the configured catalog looks like:
`sourceDefinedCursor=true,defaultCursorField=[],sourceDefinedPrimaryKey=[]`  and the intention was actually to get xmin to show up as an incremental sync.  Otherwise, the platform would deny the source the ability to sync incrementally, because there would not be a cursor.

The relevant destinations code to change is [here](https://github.com/airbytehq/airbyte/blob/752b42aaabea3d2761e7065ed6aa591a4328e485/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L342) and [here](https://github.com/airbytehq/airbyte/blob/752b42aaabea3d2761e7065ed6aa591a4328e485/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L488-L498), plus the equivalents for Snowflake.

First, we need to be safer about `stream.cursor().get()`, because that might not exist.
Then, the `DELETE FROM` SQL needs to be adjusted to remove `${cursor_name} DESC NULLS LAST,` if there is no cursor name.  We can rely on only `extracted_at` in this case.

This change is needed for all V2 destinations.

**Comment by evantahler** [comment]
With https://github.com/airbytehq/airbyte/pull/29637 merged, I think this is closed maybe?

**Comment by edgao** [comment]
I'd planned to leave it open until we actually release a new version including this fix (should happen today)

**Comment by edgao** [comment]
this has been released; closing.
