### ISSUE TITLE
Postgres Connector dropping connection error: SQLSTATE(08006), ErrorCode(0)

### ISSUE THREAD

**Issue by antonia-villa** [airbytehq/airbyte#29632]
Connector Name

Postgres

### Connector Version

3.1.3

### What step the error happened?

None

### Revelant information

**Date of Initial Failure:** 08/10/2023

We are using the standard replication method to copy three different postgres database regions into bigquery nightly. The databases are read replicas. Each stream is set up to use `Full Refresh - Overwrite` to avoid duplicate data and having to filter by Airbyte emitted date. On 08/10/2023, the largest of the 3 database regions started failing with the error seen below. 

Job statistics for the last success to gauge the size of the transfer:
86.06 GB | 192,173,204 records extracted | 192,173,204 records loaded | 4h 57m 53s

We have checked the following things in our Postgres configuration:
`statement_timeout` is not set defaulting to 0
`idle_in_transaction_session_timeout` is not set defaulting to 0

Additionally, we have tweaked our config to allow for the appropriate memory:
`JOB_MAIN_CONTAINER_MEMORY_REQUEST=2g`
`JOB_MAIN_CONTAINER_MEMORY_LIMIT=12g`

We have tried many trouble shooting steps including adding a jdbc url parameter of `connectTimeout=0` and are still experiencing intermittent failures across all regions with the same error message. We are hoping your team  can help shed some light on the issue and come to a resolution. 

```
Postgres engine version: 15.3 (for replica DBs)
Postgres Connector version: 3.1.3
BigQuery Connector version: 1.7.6
Airbyte version: 0.50.18
```

Error Message:

```
2023-08-14 00:56:37 [32mINFO[m i.a.w.g.ReplicationWorkerHelper(getReplicationOutput):289 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 11298,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
``` (continued below)

### Relevant log output

See attached file

[postgres_failure_logs.txt](https://github.com/airbytehq/airbyte/files/12384028/postgres_failure_logs.txt)

**Comment by CyberHippo** [comment]
Hi, we are also facing the same issue with a much smaller job (~3GB).

**Comment by marcosmarxm** [comment]
Not clear if the issue is about source or destination. Please open an new issue if the problem persists in latest version of the connector.
