### ISSUE TITLE
Intermittent build failures due to test timeouts

### ISSUE THREAD

**Issue by masonwheeler** [airbytehq/airbyte#2963]
## Expected Behavior
Tests should run successfully

## Current Behavior
Tests usually run successfully, but from time to time fail.  Re-running the build process generally fixes it.

## Logs
```
AirbyteGithubStoreTest > getFile > testReturn() FAILED
    java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at io.airbyte.server.services.AirbyteGithubStore.getFile(AirbyteGithubStore.java:77)
        at io.airbyte.server.services.AirbyteGithubStoreTest$getFile.testReturn(AirbyteGithubStoreTest.java:64)
```

## Steps to Reproduce
`CORE_ONLY=1 ./gradlew build`

## Severity of the bug for you
Low

## Airbyte Version
0.20.0-alpha

## Additional context
Build is taking place in a VMWare VM running Ubuntu, on a Windows 10 host system, in case that makes any difference.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368160989962) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
this looks related to the change for pulling latest connector version. @masonwheeler maybe you can tackle this since you'll be in that area of the codebase for #2782 ?

**Comment by cgardens** [comment]
how frequently does this happen?

**Comment by cgardens** [comment]
oh. the weberser it set up statically
```
  @BeforeAll
  public static void setUp() {
    webServer = new MockWebServer();
    githubStore = AirbyteGithubStore.test(webServer.url("/").toString());
  }
```

so if the tests run in a certain order then one test can affect another.

**Comment by masonwheeler** [comment]
@cgardens You think it's a race condition then?

**Comment by cgardens** [comment]
yeah. that's my guess. but i haven't been able to reproduce it on my machine. even when i force the test with the timeout to run first.

**Comment by davinchia** [comment]
Old and not relevant anymore.
