### ISSUE TITLE
Create Chroma destination

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#29668]
Based on https://github.com/airbytehq/airbyte/issues/29657 , create a new destination for Chroma using their chroma client: https://docs.trychroma.com/api-reference

Configuration:
* Mode (oneOf persistent, http)
   * In case of persistent (which only runs on local docker compose)
       * destination path
   * In case of http
       * URL
       * list of objects for headers (key/value with the value being a secret)
* Collection name

## Acceptance criteria

* Connector is published and available
* Connector has CATs and basic integration tests
* Add spec mutator that only allows http with an additional regex enforcing https on cloud

**Comment by topefolorunso** [comment]
@flash1293 I created a PR for this here #30023 for the August hackathon issue #29007. Please review as I am enthusiastic about creating a vector db integration and the PR needs to be merged by 15/09 to count toward the hackathon. Thanks.
