### ISSUE TITLE
Implement MongoDB incremental CDC sync

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#29673]
## Tell us about the problem you're trying to solve

Implement the ability to perform an incremental sync of data from MongoDB using CDC/Debezium

## Describe the solution you’d like

* Create a CDC Initializer 
* Create Debezium State Utility 
* Validate if the offset position that we have in the Airbyte state still exists on the MongoDB server or not. If not, trigger a full sync/initial snapshot again
* Logic to identify any new stream that has been added to the catalog of an already running connector
* Create CDC Properties class to set specific Debezium MongoDB connector properties
* Create CDC Target Position class to determine if incremental sync is done
* Create CDC Metadata Injector implementation to add metadata to the catalog required by sync 
* Create CDC State Handler implementation to save Airbyte state from Debezium offset information
* Identify any stream that might have not finished it's initial snapshot and before doing CDC, complete it's initial snapshot
* Provide a source defined cursor for Destinations v2

**Comment by DevBey** [comment]
Hello @jdpgrailsdev,
