### ISSUE TITLE
New Source: Survey Monkey

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2968]
## Tell us about the problem you're trying to solve
I would like to pull my survey response data and insights from the [Survey Monkey API](https://developer.surveymonkey.com/?ut_ctatext=Developers&ut_source=homepage&ut_source3=footer)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368225985964) by [Unito](https://www.unito.io)

**Comment by vovavovavovavova** [comment]
Completed the Vetting and wrote the source "Survey Monkey API: https://www.surveymonkey.com" in the google doc.

**Comment by vovavovavovavova** [comment]
## Integration Vetting
**Webhook-based:**
	No
**Available authentiation models:**
	access token
	Oauth
**Free account available:**
	Yes
	* Draft app (90 days)
	Public apps: require SurveyMonkey review
	Private: paid
**Account can be populated with data?**
	It's better to have ready account with some data.
	Manual data adding may not reflect end-user behaviour.
	
	* Can it be done entirely through the API? Yes but there is a request limit 500 requests a day,To create the survey with 1 question I need at least 3 requests. If the survey has more questions, the amount of requests will be increased.
		It seems this amount is low, so it looks like work with UI will be required. 
		To inrease the limit "contact support / 5 business days" is required
	* Will it require some work through the UI? If so, what is required?
		Probably yes due to request limitation 
		What to do within UI:
			* create app https://developer.surveymonkey.com/apps
			* create surveys "My Surveys => Create Survey" "My Surveys => Get Additional Insites"
			* Need to share it, someone (better few persons) should respond them to get the collectors
	* Public apps require rewiew. Private apps are also under limitation.
Available streams for sync:
	# MOST IMPORTANT: surveys, collectors
	users
		* users/workgroups
		* users/shared
	groups
		* groups/members
		* groups/members/id
		* groups/activities
		* groups/activities/activity_type
	
	surveys (!)
		* surveys/{id}/details
		* surveys/{id}/pages
		* surveys/{id}/pages/id
		* surveys/{id}/pages/id
		* surveys/{id}/pages/id/questions
		* surveys/{id}/pages/id/questions/id
		* surveys/{survey_id}/languages
		* surveys/{survey_id}/languages/{language_code}
		* surveys/{id}/collectors
		* surveys/{id}/responses
		* surveys/{id}/responses/bulk
		* surveys/{id}/responses/{id}
		* surveys/{id}/responses/{id}/details
		* surveys/{id}/rollups
		* surveys/{id}/pages/{id}/rollups
		* surveys/{id}/pages/{id}/questions/{id}/rollups
		* surveys/{id}/trends
		* surveys/{id}/pages/{id}/trends
		* surveys/{id}/pages/{id}/questions/{id}/trends
	benchmark_bundles
		* benchmark_bundles/{id}
		* benchmark_bundles/{id}/analyze
		* surveys/{id}/pages/{id}/questions/{id}/benchmark
	workgroups
		* orkgroups/{workgroup_id}
		* workgroups/{workgroup_id}/members
		* workgroups/{workgroup_id}/members/bulk
		* workgroups/{workgroup_id}/members/{member_id}
		* workgroups/{workgroup_id}/shares
		* workgroups/{workgroup_id}/shares/bulk
		* workgroups/{workgroup_id}/shares/{share_id}
	roles
		
	survey_categories
	survey_template
	survey_languages
	question_blank/questions
	survey_folders
	contact_lists
		* contact_lists/id
		* contact_lists/{id}/contacts
		* contact_lists/{id}/contacts/bulk (same as above but with with all available fields)
	contacts
		* contacts/bulk
		* contacts/id
	contact_fields
		* contact_fields/id
	collectors (!)
		* collectors/{id}
		* collectors/{id}/messages
		* collectors/{id}/messages/{id}
		* collectors/{id}/messages/{id}/recipients
		* collectors/{id}/messages/{id}/recipients/bulk
		* collectors/{id}/recipients
		* collectors/{id}/recipients/{id}
		* collectors/{id}/stats
		* collectors/{id}/messages/{id}/stats
		* collectors/{id}/responses
		* collectors/{id}/responses/bulk
		* collectors/{id}/responses/{id}
		* collectors/{id}/responses/{id}/details

**Comment by sherifnada** [comment]
Let's implement the following streams: 

1. Surveys
2. survey pages
3. survey questions
4. survey responses

We should implement incremental where possible. Of course we should get the actual data, some endpoints return links to the responses -- we want the actual data in the surveys, responses, etc..
