### ISSUE TITLE
New source: Delighted by Qualtrics

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2969]
## Tell us about the new integration you’d like to have
https://delighted.com/

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102460001) by [Unito](https://www.unito.io)

**Comment by rparrapy** [comment]
I'd love to have this too! Mainly survey responses and people.

**Comment by cheyura** [comment]
Webhook-based? (no/partially/yes)
Partially https://app.delighted.com/docs/api/webhooks

Available authentication modes (API key/Oauth/other)
To use the Delighted API, you’ll need a private API key that is linked to your account.
https://app.delighted.com/docs/api

Creating an account
Self-service free(Basic up to 1000 responses) or paid (up to 20000 responses)


Has Sandbox environment ?
Creating a testing “sandbox” Delighted account is possible in just two steps:

Set up a new account: Create a new trial account using an email not associated with your main Delighted account
Grab your API key: Once logged into the new trial account, head to the API page to find your test project’s API key
This is a live account, so be sure to set the sending parameter to false (more details below), or only use internal or dummy emails.


How to populate the account with data?
UI, API,Sandbox API


Available streams for sync
People, Responses, Metrics


Integration supports incremental sync?
No

Other information/blockers
No

**Comment by sherifnada** [comment]
Streams to support: 

* People
* Bounced People
* Unsubscribed People
* Survey Responses

Wherever possible we should support incremental sync.

**Comment by kyle-cheung** [comment]
+1

**Comment by kyle-cheung** [comment]
+1!

**Comment by marcosmarxm** [comment]
@kyle-cheung restart Airbyte server to fetch the new sources, this one is in the official connector list.
