### ISSUE TITLE
[FCP sunset] Billing page UI changes

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#29695]
“Free Connector Program” can be relabelled to “Free” wherever it is referenced on the billing page (including tooltips/chart hovering effects). We are making all historical syncs free, so we will reuse the existing Orb plan for those syncs. We still want to be able to show Free usage alongside charged usage, so nothing about the Usage breakdowns below the graph need to change.

The `useBillingPageBanners()` hook can (and should!) be simplified with the removal of FCP.

![image](https://github.com/airbytehq/airbyte/assets/7550957/e2d98443-9b66-4876-859d-7b3bb8636f8c)

**Comment by tealjulia** [comment]
Noticed when I was in here that we mistakenly only show the usage in the graphs if the user is currently enrolled.  That should be fixed here, too!  Any free usage should be shown regardless of enrollment.

**Comment by tealjulia** [comment]
Refining notes:
- This is fine to do now, but flag it so we can toggle it on Sept. 18
