### ISSUE TITLE
New Source: Zendesk Sunshine

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2971]
## Tell us about the new integration you’d like to have
https://developer.zendesk.com/rest_api/docs/sunshine/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368226050804) by [Unito](https://www.unito.io)

**Comment by vovavovavovavova** [comment]
## Integration Vetting
**Webhook-based? (no)**
**Available authentication modes (API key/Oauth/other)**
	email and api_token 

**Connecting to the data source**
	- requests Session auth - as session.auth = `(f'{email_address}/token', api_token)`
	
**Creating an account**
	Existing account with token stored at lastpass::`source zendesk support test creds`.
	However, we need to use additional param `email`, can be fond at lastpass::zendesk (site login info)
	No need to register new account, I enabled custom object in the settings. Existing one can be used.
	
**How to populate the account with data?**
	We how almost zero data, but it can be populated with the API. Long description how/what to insert is here
	https://developer.zendesk.com/documentation/custom-data/custom-objects/custom-objects-handbook/
	
	HOWEVER, some endpoints has only get (like early access (*5*) from below)). 
	Some non APIcall actions will be required to populate this stream
	
**Available streams for sync**
	1) List Object Types `GET /api/sunshine/objects/types`
	Note: after data population we can call the GET /api/sunshine/objects/types/schema/report once to check if everything ok.
	2) List Object Records. Example `/api/sunshine/objects/records?type={object_type}`
		A child stream for types. Require parent element parent.json()['data']['key'][i]
	3) List Relationship Types `GET /api/sunshine/relationships/types`.
	4) List Relationship Records by Type `GET /api/sunshine/relationships/records?type={type}`
		Child stream to (*4*). There are another type of filters, ( https://developer.zendesk.com/api-reference/custom-data/custom-objects-api/relationships/ )
		but this one looks the most reasonable.
	5) List Custom Object Events. `GET /api/sunshine/objects/events`. 
	Warning: population way is not described in docs!.
	6) Show Object Type Policies (Object permissions) `GET /api/sunshine/objects/types/{object_type_key}/permissions`
		It should probably contain a small amount of data.
	7) List Jobs `GET /api/sunshine/jobs`
	8) List Limits for the Account `GET /api/sunshine/limits`
		I dont know if this should be a stream, it should contain the small amount of data, but we can use it.

**Do any streams support incremental sync?**
	List Object Types
	List Object Records
	List Relationship Types
	List Relationship Records (has `created_at` and cannot be modified after create.)
	List Jobs
	

**Preparation scope & blockers**
	have limits 
		*(250 to 1000 requests per minute depending on acc type). 
		This is not a blocker, but maybe we need to handle / autohandle delays
		
		* have a limit on data size we can store - this shouldn't matter for us but I have to note.

**Comment by vovavovavovavova** [comment]
Are the account test credentials available in Lastpass? Yes

##Task breakdown
 0) Read the doc to understand the sunshine data model - it is important to do if the executor didnt do it.
 1) Populate source with data - mostly API calls. Prerequisite - insert schemas to List Object Types (schemas without `$json_schema` similar to ones we have in `schema folder` as a part of data population), then insert some valid object accordinately to that schema. Also, some manual stuff will be required for *List Custom Object Events* stream. Some stuff will be required with input data validation, everything should match the schema.
(estimation X1)

 2) Create schemas, source with streams, implement streams both incremental + full_refresh, ensure data is collected and correct,  (estimation X2)
 3) Test the data, apply response data transformation if / where required (estimation X3)
 3) Apply changes / best practices / cover unexpected cases (estimation X4)
