### ISSUE TITLE
New Source: Front 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2972]
## Tell us about the new integration you’d like to have
https://frontapp.com/api

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102629258) by [Unito](https://www.unito.io)

**Comment by karinakuz** [comment]
**Integration Vetting**

**Webhook-based? (no/partially/yes)**
if partially, mention which endpoints are webhook-based
_Partially (https://dev.frontapp.com/docs/webhooks-1). For each Event (https://dev.frontapp.com/reference/events-1) happening in Front webhook will receive a POST HTTP request with the event preview JSON representation in the request body._

**Available authentication modes (API key/Oauth/other)**
_Private resource access and OAuth access (https://dev.frontapp.com/docs/core-api-getting-started). For creation an OAuth application we should send a letter to support._

**Connecting to the data source**
what kind of API is it? (SOAP/GraphQL/REST/other)
_Front’s platform is made up of three primary APIs: Core API, Plugin SDK, and Channel API_ 

is there an SDK available? Can we connect with HTTP requests directly?
_SDK is available for several specific events_ 


_no_

**Creating an account**
Select one of the below options
self-service free account available?_ If yes then create it using integration-test@airbyte.io (you should be getting emails sent to this email address)
 _7 day free trial_

self-service paid account available? Please mention the cost of the various tiers and any recommendation about which tier we should buy_. Don't create the account right now.
_Plan: Starter $19 USD (per person, per month, billed annually)_

account only available through email, application, or call? If you can fill out the application online (email or form) please do so and note that on the ticket. If a call is needed, please reach out to sherif to have him arrange the call
_no_

**How to populate the account with data?**
Can it be done entirely through the API?
_API that allows you to read, create, update, and delete a wide range of data across Front’s various entities, from Contacts to Comments to Tags._  

Will it require some work through the UI? If so, what is required?
_no_

Will it require performing some paid action like running an Ad campaign? If so, please note the action needed, estimated cost, and estimated effort in hours. If a task will take more than 4 hours, please break it down into smaller tasks each of which take no more than 4 hours
_no_

Do you need any actions from Airbyte to populate the account with data? If so, please tag @ sherifnada for support_→>
_no_

**Comment by karinakuz** [comment]
**Preparation**

**Creating the account**
* [ ] create an account, get API Secret and API token for Private resource access, send letter to support to receive Client ID and Client Secret to get API token for OAuth access. (1h)

For information:

_Private resource access_
By default, individual resources are private and the API does not let you interact with them nor with their content.
However, a user has the ability to allow access to their individual resources from the API in their settings (Settings > My preferences > "Allow access to my individual resources via the API").

_OAuth access_
Integrations relying on OAuth all have the same scope: “Shared resources”, and at this time cannot request more permissive scopes. This means that integrations that use OAuth will be able to access all team resources

**Comment by karinakuz** [comment]
Get correct data in responses for GET requests:
Get Events https://api2.frontapp.com/events
Get Responses https://api2.frontapp.com/responses
Get Contacts https://api2.frontapp.com/contacts
Get Channels https://api2.frontapp.com/channels
Get Inboxes https://api2.frontapp.com/inboxes
Get Comments (get data for certain conversation only) https://api2.frontapp.com/conversations/conversation_id/comments
Get Conversations https://api2.frontapp.com/conversations
Get Messages (get data for certain conversation only) https://api2.frontapp.com/conversations/conversation_id/messages
Get Rules https://api2.frontapp.com/rules
Get Tags https://api2.frontapp.com/tags
Get Teams https://api2.frontapp.com/teams
Get Teammates https://api2.frontapp.com/teammates
Get Topics https://api2.frontapp.com/topics

**Comment by karinakuz** [comment]
JSON Schemas https://drive.google.com/drive/folders/1TTUlOWNq-s81pRcK1oVqBBVlOg1i-7QV?usp=sharing

**Comment by sherifnada** [comment]
@karinakuz could you reach out to Front to ask for an oauth developer application so we can begin implementation?

**Comment by lharries** [comment]
Hi @karinakuz and @sherifnada is there an estimated date when this integration would be completed?

**Comment by sherifnada** [comment]
@lharries no ETA as we've scaled back work on new connectors to focus on reliability and features on existing connector, atm the fatest way to get this into the product is to submit a PR.

**Comment by lharries** [comment]
Understood, thank you

**Comment by natikgadzhi** [comment]
Shipped!
