### ISSUE TITLE
Nest "Reset your data" under "Sync Now" as a secondary action

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#29736]
As we introduce additional banners into the UI (the latest is breaking changes), we are more commonly seeing several buttons on top of one another that look disjointed when combined. Are all buttons valuable to keep on the page?

From Fullstory, 7% of users who visit the Status page use the "Reset your data" button, whereas 33% use the "Sync now". The users who do reset seem to be power users who seem pretty familiar with our platform as they're also fiddling with replication settings and mostly have pretty full workspaces.

Some options proposed to hide "Reset", since it's used less commonly:
- Using three grey dots to hide less common actions. This would be pre-emptive (we don't have enough actions to warrant a drop-down)
- A split button, keeping “Sync now” as the primary action and "Reset your data" as a secondary action

Slack conversation: https://airbytehq-team.slack.com/archives/C03088BTMFC/p1692716368887809

Two examples: 
<img width="1418" alt="Screen Shot 2023-08-22 at 4 04 31 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/a055a284-6c08-4a55-bc7c-c0ffaa50702a">

![image (2)](https://github.com/airbytehq/airbyte/assets/38087517/5f449ddf-9b80-4be1-ac24-9a92fa60e21a)

**Comment by tealjulia** [comment]
Refining notes:
- breaking changes should definitely still have prominence, but maybe non-breaking shouldn't
- the split-button (button/dropdown) from the slack thread will take some thinking RE: the expected action (IE: when I select, does the action happen immediately or does it just change the value of the button... probably the former)

**Comment by nataliekwong** [comment]
some thoughts in this GitHub issue on the banner bloat problem cc @nora-airbyte

**Comment by nora-airbyte** [comment]
Two things happening here: 1) there are multiple CTAs on the sync itself and 2) too many (some unnecessary) messages are being shown.

**Proposed changes:**

For 1), let's move "Reset your data" to an overflow menu. Given only 7% of users have ever used this button, I think the extra click is ok, and it's worth it to remove clashing CTAs.
[MOCKS](https://www.figma.com/file/vqUPT4d9oIi7EDinWOZsyr/Banners-on-status-page?type=design&node-id=628%3A4319&mode=design&t=u2rUlZrQLky3htvZ-1)

For 2), a few related changes:
[#31076](https://github.com/airbytehq/airbyte/issues/31076)
[#31077](https://github.com/airbytehq/airbyte/issues/31077)
[#31078](https://github.com/airbytehq/airbyte/issues/31078)
[#31081](https://github.com/airbytehq/airbyte/issues/31081)

**Comment by nataliekwong** [comment]
I spotted this version of nested actions in Stripe and thought it was a neat way to implement multiple actions via icons at the top level, but also have nested actions. Just a consideration for the future if we end up having enough actions to take here (and if we move to ever using just icons without text).

![Image](https://github.com/airbytehq/airbyte/assets/38087517/57387944-0803-4c9e-9cc0-ced4ae04d5a7)

**Comment by nataliekwong** [comment]
Thanks @dizel852!
