### ISSUE TITLE
New Source: IBM DB2

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2975]
## Tell us about the new integration you’d like to have
https://www.ibm.com/analytics/db2

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368226088171) by [Unito](https://www.unito.io)

Todo:
1. Generate (use a template generator) jdbc connector and implement connections 
(https://www.ibm.com/docs/en/db2-for-zos/11?topic=samples-example-simple-jdbc-application, 
https://www.ibm.com/docs/en/db2-for-zos/11?topic=hjacds-connecting-data-source-using-drivermanager-interface-data-server-driver-jdbc-sqlj) 
2. Create unit test 
3. Create Integration test (container for tests https://www.testcontainers.org/modules/databases/db2/) 
4. Create Comprehensive test:
    - Investigate and prepare use cases (https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0008483.html?pos=2): 
    - Implement comprehensive tests.
    - Prepare pull request, pass all checks.

**Comment by irynakruk** [comment]
[IBM Db2 Built-In Data Types](https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0008483.html?pos=2)


Data Type | Category of edge case | Example values | Comment | Common test result
-- | -- | -- | -- | --
SMALLINT | -32768, 32767 | null,&nbsp;-32768,&nbsp;32767| &nbsp; | ok
INTEGER | -2147483648, 2147483647 | null,&nbsp;-2147483648,&nbsp;2147483647| &nbsp; | ok
BIGINT | -9223372036854775808, 9223372036854775807 | null,&nbsp;-9223372036854775808,&nbsp;9223372036854775807| &nbsp; | ok
DECIMAL(NUMERIC) | -0, 0 | null,&nbsp;-0,&nbsp;0| &nbsp; | ok
REAL | null, -3.4028234663852886e+38, -1.1754943508222875e-38, 1.1754943508222875e-38, 3.4028234663852886e+38| null,&nbsp;-3.4028234663852886e+38,&nbsp;-1.1754943508222875e-38| &nbsp; | ok
DOUBLE(FLOAT)| null, -1.7976931348623158e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623158e+308| null,&nbsp;-0,&nbsp;0| &nbsp; | ok
DECFLOAT | -0, 0 | null,&nbsp;-0,&nbsp;0| &nbsp; | ok
BOOLEAN | null | null,&nbsp;t,&nbsp;true,&nbsp;y,&nbsp;yes,&nbsp;on,&nbsp;1,&nbsp;f,&nbsp;false,&nbsp;n,&nbsp;no,&nbsp;off,&nbsp;0| &nbsp; | ok
CHAR | null | null,&nbsp;a,&nbsp;' ',&nbsp;*| &nbsp; | ok
VARCHAR | null | null,&nbsp;тест| &nbsp; | ok
NCHAR | null | null| &nbsp; | ok
NVARCHAR | null| null| &nbsp; | ok
GRAPHIC |null | null,&nbsp;3=3| &nbsp; | ok
VARGRAPHIC |null | null,&nbsp;3=3| &nbsp; | ok
VARBINARY | null | null,&nbsp;3=3| &nbsp; | ok
BLOB | null | null,&nbsp;3=3| &nbsp; | ok
CLOB | null | null,&nbsp;3=3| &nbsp; | ok
NCLOB | null | null,&nbsp;3=3| &nbsp; | ok
XML | null| null,&nbsp;<?xml version="1.0"?><book><title>Manual</title><chapter>...</chapter></book>| &nbsp; | ok
DATE | null,&nbsp;0001-01-01,&nbsp;9999-12-31| null,&nbsp;0001-01-01,&nbsp;9999-12-31| year:0001-9999,&nbsp;month:1-12,&nbsp;day:1-31| ok
TIME | null,&nbsp;00:00,&nbsp;23:59 | null,&nbsp;00.00.00,&nbsp;1:59 PM,&nbsp;23.59.59| &nbsp; | ok
TIMESTAMP | null | null,&nbsp;2018-03-22-12.00.00.123,&nbsp;20180322125959,&nbsp;20180101 12:00:59 PM|  milliseconds values are erased | ok
