### ISSUE TITLE
Destination: DBT Custom Transformation - Specify the current git_repository folder

### ISSUE THREAD

**Issue by leonardotfrancis** [airbytehq/airbyte#29775]
### Topic

DBT

### Revelant information

I am using Custom Transformation to apply three steps of transformation: 1) Normalization based on the DESTINATION. 2/3) Custom Transformation based on specific DESTINATION. Every time synchronization starts, the transformation occurs in a folder and gets a git clone from the repository. In this case, I would like to specify the specific path of the profiles-dir to be the same of the project-dir which is followed by git_repo. But every time I set the --profile-dir $(pwd)/git_repo the value don't get translated to the real path and gives me an error.  

If I don't set the --profiles-dir or --project-dir in the entrypoint arguments, it gets generated automatically according to the following image. However, as the number presented in the path is generated automatically, I would like to get the path of the folder using a function, for example, $(pwd) or any other. Thus It can allow me to set the same path of the --profile-dir as the --project-dir, so I can use my specific profile file.

![image](https://github.com/airbytehq/airbyte/assets/5081890/d6331b3a-c260-4df6-b473-74b22e8a2546)

Errors:

![image](https://github.com/airbytehq/airbyte/assets/5081890/6e36e443-9530-40bc-a9d1-74f22acf99e9)
![image](https://github.com/airbytehq/airbyte/assets/5081890/291839fd-5131-48e6-bfd5-c2472f0543f5)

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated this feature](https://github.com/airbytehq/airbyte/discussions/34860).
