### ISSUE TITLE
New Source: Pendo

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2977]
## Tell us about the new integration you’d like to have
https://developers.pendo.io/docs/

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368161277962) by [Unito](https://www.unito.io)

**Comment by cheyura** [comment]
Webhook-based? (no/partially/yes)
Yes
https://support.pendo.io/hc/en-us/articles/360032285012-Webhooks

Available authentication modes (API key/Oauth/other)

Pendo provides the following APIs and integration kits for customers:

- The Pendo Agent API allows developers to programmatically interact with Pendo’s Agent, the JavaScript client that collects user interactions and displays in-app messaging.
- The Pendo v1 API is a RESTful API used to query, update, and reset Pendo data primarily by running Aggregation queries or modifying Guide resources.
- The Pendo Resource Center Integration Kit provides an integration framework that allows third party developers to create applications that Pendo customers can activate and provide to their users.

Authentication of requests is handled by an integration key

To create an Integration Key:

- Login to the Pendo Application as an Admin user.
- Visit the Integrations section in the Pendo App, and then click on Integration Keys.
- Click on the Add Integration Key button at the top right-hand side of the screen.
- Give your new key an appropriate description.
- If a read-write key is needed, tick the box marked Allow Write Access.
- Click on Create to finish.
- 

Creating an account
Free up to 1000 users monthly


Sandbox account?
No

How to populate the account with data?
App is needed and then UI interaction


Available streams for sync
Browser Interactions
Functions
Debugging
Events
Track Events
Guide Events
Options

Integration supports incremental sync?


Other information/blockers
Most obviously, an app is needed.
Once installed in your application, visitor activity is collected automatically by the Pendo Agent and sent via Image Beacons to Pendo for data processing. Pendo accepts these events immediately but ingests and processes visitor data asynchronously. So visitor events sent by the Agent are not immediately available via the API but usually within 5 minutes of receipt.

**Comment by dannob** [comment]
Just adding a +1 to this request.

**Comment by sherifnada** [comment]
@dannob which data would you like to pull from pendo? this helps us know which endpoints to support

**Comment by lionelmoi** [comment]
I would like to be able to pull anything under the aggregation category https://developers.pendo.io/docs/?bash#aggregation

Being able to define an aggregation and pull data out of Pendo this way would be a huge time saver.

**Comment by tym-xqo** [comment]
We are currently using Fivetran's Pendo connector, which mostly pulls event-level data and is described at https://fivetran.com/docs/applications/pendo. A similar connector in Airbyte would make it much easier for us to consider switching.

**Comment by pmamarques** [comment]
> We are currently using Fivetran's Pendo connector, which mostly pulls event-level data and is described at https://fivetran.com/docs/applications/pendo. A similar connector in Airbyte would make it much easier for us to consider switching.

Same here.

**Comment by cheyura** [comment]
No Sandbox available and real Application (where Pendo Agent is installed) is needed to retrieve data through API

**Comment by lionelmoi** [comment]
Hey @cheyura how can we unblock this connector?

**Comment by cheyura** [comment]
> Hey @cheyura how can we unblock this connector?

@lionelmoi @sherifnada  Since Pendo has no sandbox we are unable to test this connector (we need a real app where we install Pendo). All the connectors that need a real application are currently blocked

**Comment by sherifnada** [comment]
@lionelmoi would you be open to sharing your pendo credentials with us to help us build the connector?

**Comment by lionelmoi** [comment]
I could ask my contacts at pendo to setup an environment for you. Would this work?

**Comment by adayNU** [comment]
I just opened a request with Pendo for a test API key

**Comment by kerbam** [comment]
Since the sources for Airbyte can use Singer taps maybe their Pendo tap might be helpful along the way to getting this built out on the Airbyte side: https://github.com/singer-io/tap-pendo

**Comment by everettttt** [comment]
Any update on this?

**Comment by YowanR** [comment]
I believe we're still blocked on this one. Waiting for Pendo to reply. @igrankova Can you confirm?

**Comment by igrankova** [comment]
@YowanR yes, we don't have any answer from Pendo.

**Comment by fortynachos** [comment]
Hey folks, Pendo employee here 👋.  I lead our Engineering Services team.  I can likely get you hooked up with an integration key, stay tuned while I check some things on my end.

**Comment by YowanR** [comment]
Thanks @fortynachos! 
@igrankova can you follow up, please?
@YiyangLi is this something you'd like to work on?

**Comment by igrankova** [comment]
@YowanR 
We accepted the invitation to the sandbox, LastPass: Pendo Sandbox Account
API Key saved in the LastPass
The account is already seeded!
Thanks a lot for help, @fortynachos

**Comment by YowanR** [comment]
@YiyangLi Any updates on this one? 🙏

**Comment by YiyangLi** [comment]
@YowanR Yes, I just created a PR https://github.com/airbytehq/airbyte/pull/24081 I run the integration tests locally, it works fine. I only added 4 streams. 

I used the same credential you shared with me, please setup the CI so that the integration tests are run successfully. Thanks.
