### ISSUE TITLE
New Source: Salesforce Pardot

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2978]
## Tell us about the new integration you’d like to have
https://www.pardot.com/

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368161299229) by [Unito](https://www.unito.io)

**Comment by po3na4skld** [comment]
## Integration Vetting

**Webhook-based?**

No

**Available authentication modes**

OAuth, Bearer token

**Connecting to the data source**

All requests to the API must:

- Use either HTTP GET or POST. Version 5 also supports PUT and DELETE requests.
- Pass access token in an HTTP Authorization header.
- Pass Pardot Business Unit ID in an HTTP Pardot-Business-Unit-Id header.
- Use the correct URL for your Pardot environment.

**Creating an account**

The Essentials Edition does not allow for API access. You will only be able to integrate with apps available in our AppExchange for the Essentials edition. You can find more info [here](https://appexchange.salesforce.com/appxstore?mktcoll=a593A000000PWXwQAO) To access the API, you'll need to [upgrade](https://www.salesforce.com/editions-pricing/sales-and-service-cloud) your edition to Professional or Enterprise. @sherifnada 

Ability to register 14-days trial account, pricing plans:
<img width="723" alt="Screenshot 2021-06-10 at 15 50 50" src="https://user-images.githubusercontent.com/36486349/121527943-a3fe5980-ca03-11eb-84e3-749aed2256ef.png">

**How to populate the account with data?**


_Can it be done entirely through the API?_

Yes

_Will it require some work through the UI? If so, what is required?_

No

_Will it require performing some paid action like running an Ad campaign? If so, please note the action needed, estimated cost, and estimated effort in hours. If a task will take more than 4 hours, break it down into smaller tasks each of which take no more than 4 hours_

No

_Do you need any actions from Airbyte to populate the account with data?_

There are basic samples for introduction purposes

**Available streams for sync**

All endpoints have sync read method and XML as responses

[Accounts](https://developer.pardot.com/kb/api-version-3/accounts/)
[Campaigns](https://developer.pardot.com/kb/api-version-3/campaigns/)
[Custom Fields](https://developer.pardot.com/kb/api-version-3/custom-fields/)
[Custom Redirects](https://developer.pardot.com/kb/api-version-3/custom-redirects/)
[Dynamic Content](https://developer.pardot.com/kb/api-version-3/dynamic-content/)
[Emails](https://developer.pardot.com/kb/api-version-3/emails/)
[Email Clicks](https://developer.pardot.com/kb/api-version-3/batch-email-clicks/)
[Email Templates](https://developer.pardot.com/kb/api-version-3/email-templates/)
[Forms](https://developer.pardot.com/kb/api-version-3/forms/)
[Lifecycle History](https://developer.pardot.com/kb/api-version-3/lifecycle-histories/)
[Lifecycle Stage](https://developer.pardot.com/kb/api-version-3/lifecycle-stages/)
[Lists](https://developer.pardot.com/kb/api-version-3/lists/)
[List Membership](https://developer.pardot.com/kb/api-version-3/list-memberships/)
[Opportunity](https://developer.pardot.com/kb/api-version-3/opportunities/)
[Prospects](https://developer.pardot.com/kb/api-version-3/prospects/)
[Prospect Account](https://developer.pardot.com/kb/api-version-3/prospect-accounts/)
[Tags](https://developer.pardot.com/kb/api-version-3/tags/)
[TagObjects](https://developer.pardot.com/kb/api-version-3/tag-objects/)
[Users](https://developer.pardot.com/kb/api-version-3/users/)
[Visitors](https://developer.pardot.com/kb/api-version-3/visitors/)
[Visitor Activities](https://developer.pardot.com/kb/api-version-3/visitor-activities/)
[Visits](https://developer.pardot.com/kb/api-version-3/visits/)


**Do any streams support incremental sync?**

almost all streams can be queried by created_before, created_after, updated_before, updated_after fields.
almost all streams have sort orders by date or id

Those that cannot support incremental sync:

- Accounts
- Emails
- Email Clicks
- Email Templates
- Visits

**Preparation scope & blockers**

Buy an account as trial lasts only for 14 days

To access the API, you'll need to upgrade your edition to Professional or Enterprise: https://www.salesforce.com/editions-pricing/sales-and-service-cloud.

**Other information/blockers**

Source also supports OAuth2.0, has three vesrions of API: 3, 4, 5. The newer the api the less endpoints there are
API interface written in XML

[Error codes description](https://developer.pardot.com/kb/error-codes-messages/)

**Comment by sherifnada** [comment]
@po3na4skld [this page](https://www.salesforce.com/products/sales-cloud/pricing/) says professional pricing is $175/mo -- where did you get the screenshot above?

**Comment by po3na4skld** [comment]
> @po3na4skld [this page](https://www.salesforce.com/products/sales-cloud/pricing/) says professional pricing is $175/mo -- where did you get the screenshot above?

@sherifnada when I had registered and logged in from this https://www.pardot.com/ link, they asked me to buy a plan and gave this pricing plan

**Comment by po3na4skld** [comment]
@sherifnada to login into pardot dashboard, you need to open lastpass and go to the url that specified there, pass credentials and login, they can ask you for a mobile number but you are open to skip this step.

**Comment by kyle-cheung** [comment]
+1! Would love to see this source

**Comment by kyle-cheung** [comment]
any update on this? would be huge in my org and im sure for many others as well!

**Comment by dubravcik** [comment]
Hi, this looks as it was merged and released half a year ago but I can't access docs [](https://docs.airbyte.com/integrations/sources/pardot) mentioned in the release log [](https://docs.airbyte.com/project-overview/changelog/connectors/), nor I don't see it in Airbyte as a source. I am using 0.36.6

**Comment by igrankova** [comment]
@dubravcik I see the issue with sandbox is blocked on Salesforce side: https://github.com/airbytehq/airbyte/issues/7276
They provide a Pardot provisioned Salesforce Developer Org only to partners. We still in progress with the partner program.

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/7091
