### ISSUE TITLE
Source Amazon Seller Partner: unable to finish set up after successful account authorization via oAuth

### ISSUE THREAD

**Issue by andreyAtBB** [airbytehq/airbyte#29797]
### Connector Name

amazon-seller-partner

### Connector Version

1.5.1

### What step the error happened?

Configuring a new connector

### Revelant information

Steps:

1. Create a new Amazon Seller Partner source on Airbyte Cloud.
2. Click "Authenticate your Amazon Seller Partner account" button.
3. Finish oAuth process in the popped up screen.
4. Enter correct Start Date
5. Click "Set up source" button

_**Actual Result:**_ 
An error is displayed:
Configuration check failed
PartialCredentialsError('Partial credentials found in explicit, missing: aws_secret_access_key')

_**Expected Result:**_ Connection test passes and the new source is saved.

<img width="1722" alt="Screen Shot 2023-08-24 at 4 41 01 PM" src="https://github.com/airbytehq/airbyte/assets/135266396/c479855f-961e-4767-acac-8e9f1d20ffb0">
<img width="900" alt="Screen Shot 2023-08-24 at 4 41 09 PM" src="https://github.com/airbytehq/airbyte/assets/135266396/e36d5bee-2dbc-4baf-b674-c08c4fbaf2f7">

Note the AWS Access Key that was set automatically during oAuth process.
If that field is cleared and an attempt to finish set up is made this errors is displayed:
`NoCredentialsError('Unable to locate credentials')`

### Contribute

- [ ] Yes, I want to contribute

**Comment by Webmasterei** [comment]
I just ran into this problem. When will this be fixed?
