### ISSUE TITLE
Source Jira: not syncing deleted issue worklogs

### ISSUE THREAD

**Issue by cad-dmendel** [airbytehq/airbyte#29796]
### Connector Name

source-jira

### Connector Version

0.3.12

### What step the error happened?

None

### Revelant information

Hello! I'm using the Jira source connector and I've noticed that whenever someone updates their issue worklog, Airbyte syncs it correctly. However, when someone deletes their worklog, the old data is not deleted from the database and it doesn't reflect the true worklog allocation.

The issue worklogs sync mode is currently "Append + Deduped". I wasn't looking to use Overwrite because we have lots of worklogs and syncing all of them everytime would take a long time.

### Contribute

- [ ] Yes, I want to contribute

**Comment by lazebnyi** [comment]
We cannot modify the data that has already reached your destination with "Append + Deduped" mode. Therefore, any new data will be added to the existing data, including any old data that was previously synced.
