### ISSUE TITLE
Source Amplitude: `Stream_state` saved in wrong format

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#29800]
### Connector Name

source-amplitude

### Connector Version

0.2.4

### What step the error happened?

During the sync

### Revelant information

`Stream_state` saved in wrong format

see https://github.com/airbytehq/oncall/issues/2629 for more info

### Contribute

- [ ] Yes, I want to contribute

**Comment by roman-yermilov-gl** [comment]
It has already been fixed in this PR: https://github.com/airbytehq/airbyte/pull/28942
