### ISSUE TITLE
Syncs are paused in cloud when the support state is set to unsupported

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#29803]
* We are going to pause with no 'reason', and no auto-unpause once the upgrade happens.
* Users can unpause, and we don't care
* UI copy updates for cloud

Implementation
* pause syncs when the actor becomes unsupported.  This means users could unpause syncs... that's fine :shrug: 
    * this is a DB update.  There's not a batch update - new SQL
    * Don't pause LD override connections
    * 
* API update to prevent syncs from unpausing if the ADV is unsupported (and no LB overrides are in use).
~~* Disable button to run sync when paused if ADV is unsupported (might need extra info in API response)~~ 
    * We will revisit this when syncs are paused + reasons (billing vs supportState etc)

Re: https://airbytehq-team.slack.com/archives/C03A8CSANPQ/p1690816967251309

**Comment by erohmensing** [comment]
This ticket should also come with copy updates in the frontend. See the designs where we tell the user what will happen/what happened with regards to their syncs being automatically paused
