### ISSUE TITLE
In OSS when upgrading the connectors to latest an error is thrown for each new connector

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#29809]
## Reproduction
1. Start a fresh OSS instance
2. Navigate to settings > sources
3. Open your network tab
4. In the UI click upgrade all

**Expected**
No errors

**Actual**
An internal error is thrown per all net new connectors and the upgrade all button shows a very small error
> Internal Server Error: Could not find configuration for STANDARD_SOURCE_DEFINITION
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUE0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee9d744081a19b28b76a056bcc2b57bc8fac6449/image.png)

## Impact
Uses briefly see some red text that is truncated around the upgrade all button

## Likely Cause
https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java#L552

We query based on actor id during the upgrade but at this time the new actor is not part of the db so we throw an error

**Comment by erohmensing** [comment]
> An internal error is thrown per all net new connectors 

Which connectors are "net new" in this case? Are these new versions or new connectors?

**Comment by erohmensing** [comment]
I guess it seems like the frontend is getting the list of connectors from the latest list and then calling "update" on all of them, which fails if there's a new connector in the registry that wasn't in the list on boot.

Not sure if the expected behavior of "update all" is "only update what I have" or "get the latest including new stuff" but the logic for either one should be pretty easy for the frontend to do based on the list of connectors they already have vs the latest list.

**Comment by lmossman** [comment]
@bnchrch Why is it that when you start a fresh OSS instance, it is missing some connectors from the registry and some connectors are not already on the latest version?

I expected as a user that if I start up a fresh OSS instance, it is initialized with all of the connectors in the registry and they are all set to the latest versions, but that doesn't seem to be the case.

**Comment by erohmensing** [comment]
@lmossman we bake in the connector registry at version build time. I assume it is due to some "we can't be certain that the newest connectors will work on the old version" legacy thought - though we now have `protocolVersion` which should hypothetically define that interaction for us
