### ISSUE TITLE
Destination Typesense: data written to single index

### ISSUE THREAD

**Issue by gmanninglive** [airbytehq/airbyte#29816]
### Connector Name

destination-typesense

### Connector Version

`>=0.1.0`

### What step the error happened?

Configuring a new connector

### Revelant information

Destination typesense suffers the same bug as #19205. Indexes are created for all streams but all records are written to the first index.

I have a fix that I will add in the comments.

### Contribute

- [X] Yes, I want to contribute

**Comment by RaphaPlato** [comment]
I have the same issue. Can we move that resolution forward? It's been idle for almost 2 months.

**Comment by mbrimmer83** [comment]
Seeing the same behavior. 😞
