### ISSUE TITLE
New source: Apple Search Ads Reports

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2982]
## Tell us about the new integration you’d like to have
https://searchads.apple.com/advanced/

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368161100890) by [Unito](https://www.unito.io)

**Comment by cheyura** [comment]
Webhook-based? (no/partially/yes)

Available authentication modes (API key/Oauth/other)


Creating an account

Has Sandbox environment ?

How to populate the account with data?


Integration supports incremental sync?

Other information/blockers

**Comment by cheyura** [comment]
@sherifnada Unable to create a sandbox account due to two-factor authorization

**Comment by sherifnada** [comment]
@cheyura is it possible to advertise for an app that we do not own? or does it have to be our app? 

For 2FA, can you use the phone number listed in the integration test sms slack channel?

**Comment by cheyura** [comment]
> @cheyura is it possible to advertise for an app that we do not own? or does it have to be our app?
> 
> For 2FA, can you use the phone number listed in the integration test sms slack channel?

@sherifnada 1. seems like we need an app 
2. Account for integration-test@airbyte.io already exists with unknown number 
![image](https://user-images.githubusercontent.com/84457236/122937657-d2245780-d37a-11eb-8ae4-ca71997037e3.png)
3. test sms slack channel does not display any number (checked on Amazon)

**Comment by sherifnada** [comment]
@cheyura I see. I will fix the phone number issue.

**Comment by cheyura** [comment]
No Sandbox available and real app is needed to retrieve data through API

**Comment by YowanR** [comment]
Is this going to be similar to Amazon Seller Partner where we need to have real data flowing? If so, this might be quite painful.

**Comment by shashanksinghfd** [comment]
Heya, I am new to airbyte codebase, any pointers on where I can contribute to this connector?

**Comment by grubberr** [comment]
@YowanR @lazebnyi scoping docs here
https://docs.google.com/document/d/1E-vKNJ6s8j0F9ilVHM0aYCzwSnYnJorBEWJq2I1D3BM/edit#heading=h.84uu0ym2sjtf

**Comment by igrankova** [comment]
hi, @sherifnada 
Can you please update the phone number in 2F auth?
I want to try to sing up to the Apple Ads. Created a new Apple ID but it doesn't work, trying to find out why.

**Comment by alafanechere** [comment]
@igrankova a [PR](https://github.com/airbytehq/airbyte/pull/19557) is ready for this connector. We would need a test account to run acceptance tests. Were you apple to create one?
(cc. @sherifnada)

**Comment by igrankova** [comment]
@alafanechere I'll try to help. I've created an account, but need some time to set up everything.
LastPass: Apple Search Ads test account

**Comment by igrankova** [comment]
@alafanechere 
hi, Augustin, I'm not sure how to setup a test campaign on our new account to obtain some test data. Trying to find out how to set up the account, created an [issue](https://github.com/airbytehq/airbyte/issues/21192).

**Comment by igrankova** [comment]
@alafanechere,
I received an answer from the support: Please be advised search ads is an option available to members of the paid Apple Developer Program.
First I've submitted a request for the D-U-N-S Number which is needed for the Developer Program enrollment.
Now I'm searching for the pricing for making a decision.
cc @YowanR

**Comment by YowanR** [comment]
@igrankova Any follow-ups here, please?

**Comment by igrankova** [comment]
@sherifnada, Hi!
Is it possible to access the old sms channel to pass 2F verification on our Apple account? We can't use the new sandbox without a Developer Program enrollment and we can't enroll because we are already members with our old account. So we need to add the new sandbox to the development team using the old account. 
I received a reply from Apple:
![image](https://user-images.githubusercontent.com/87977540/215038493-b10ad2f4-2f7b-435b-aa19-eb9706d8c175.png)
cc @YowanR

**Comment by YowanR** [comment]
@sherifnada Bump here -- we just need you to update the 2F of the account to #connector-sms
