### ISSUE TITLE
Sync hubspot deal association with company/contact

### ISSUE THREAD

**Issue by erichartono** [airbytehq/airbyte#2983]
## Tell us about the problem you're trying to solve
I would like to sync hubspot deal associations with company/contact so that I can analyse deal with segmented company/contact. Destination that I am after is Redshift.

## Describe the solution you’d like
On HubSpot API, there's GET …/objects/deals?associations=[deal,company,contact] 
I would like to sync into destination (redshift) under deals_assocations table. I only need deal id, company id and contact id.

We also need to add another association between line item and deal
GET /crm/v3/objects/line_items/{lineItemId}/associations/{toObjectType}

## Describe the alternative you’ve considered or used
None

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368102826960) by [Unito](https://www.unito.io)

**Comment by keu** [comment]
Hi @erichartono, quick question about line_items associations.

Would the following query be sufficient?

`https://api.hubapi.com/crm/v3/objects/deal/?hapikey=demo&limit=100&associations=deals,contacts,companies,line_items`

If yes, then this would be relatively to implement, just to modify the associations list and fix the schema so the destination knows what to expect.
