### ISSUE TITLE
New source: Google Display & Video 360

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2984]
## Tell us about the new integration you’d like to have
https://marketingplatform.google.com/about/display-video-360/

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368226284507) by [Unito](https://www.unito.io)

**Comment by karinakuz** [comment]
After corresponding with Google Marketing Platform Sales Support (Aug 10 - Sep 13) we still don't have any letters from Google Partners who should reach out to assist with scheduling an overview of Google platform solutions.
