### ISSUE TITLE
CDC sync deletes many rows, sometimes

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#29880]
We're seeing some inconsistent behavior on Snowflake CDC syncs, where some records are being deleted.

So far we think we've narrowed it down to

- asynchronous destinations (snowflake)
- Typing and Deduping

Potential stop gap fixes are:
- do not use async
- only type and dedupe at the end of a sync

**Comment by edgao** [comment]
closed in https://github.com/airbytehq/airbyte/pull/29881
