### ISSUE TITLE
Source: Shopify: Error loading data into 2 tables and causing syncing failures

### ISSUE THREAD

**Issue by Barry-LeeLodewyks** [airbytehq/airbyte#29889]
### Connector Name

Shopify

### Connector Version

0.1.37

### What step the error happened?

None

### Revelant information

Hi there

Having an issue with my SHOPIFY connector, I know it’s only Alpha but been syncing without issue for the past 2 weeks.

It’s only attempted to load 3 records but blowing up space resources in my warehouse.

The sync errors out when trying to load records into these 2 table
shopify.shopify_orders_refunds_refund_line_items_line_item_discount_allocations_amount_set_shop_money 
shopify.shopify_orders_refunds_refund_line_items_line_item_discount_allocations_amount_set_presentment_money

- The orders stream is set to Incremental/append
- Destination: Redshift
[logs-4598.txt](https://github.com/airbytehq/airbyte/files/12515090/logs-4598.txt)

 

### Contribute

- [X] Yes, I want to contribute

**Comment by bazarnov** [comment]
Outdated. Closing.
