### ISSUE TITLE
Create 2 email templates for breaking change notifications

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#29921]
Add customer.io templates here: https://fly.customer.io/workspaces/112679/journeys/transactional

There should be two templates:
1. breaking change released / syncs became deprecated
2. breaking change upgrade deadline passed / syncs disabled

Run this by @erica-airbyte

**Comment by pedroslopez** [comment]
Current template:

```
TEMPLATE:
Hello,
 
We are reaching out because your workspace has an active connection using the [CONNECTOR NAME] connector.

A pending update to the connector will require action from you.

About the new version [VERSION NUMBER]: [MESSAGE FROM METADATA]


[Optional: If the migration guide details much longer steps the user will have to take, detail those here]

The update will be available on [DATE] and you will have until [DATE] to upgrade your connector to the version x.x.x. 
 
Please reach out to Airbyte Cloud support if you have any questions. To open a ticket, select the “Support” icon in the Cloud platform, or by visiting our Help Center. 
 
Best, 
Airbyte Team
```

**Comment by evantahler** [comment]
We can ask @Hesperide for help with the copu.

**Comment by pedroslopez** [comment]
@bnchrch Note that in order to simplify using broadcasts with this template, we should avoid including any customer-specific details in the messaging. 

We can still include information that's common to all users, such as what the connector / breaking change is.

**Comment by erica-airbyte** [comment]
@pedroslopez sorry just getting through all my GH notifications, were there templates I needed to look at or edit?

**Comment by bnchrch** [comment]
@erica-airbyte Just put the copy up for review here: https://docs.google.com/document/d/1b_rJQfjjywdIckaDoiAHLCcl0Xq41aRGrd0YMC2C5rQ/edit?usp=sharing

**Comment by bnchrch** [comment]
Customer.io templates created
* pending: https://fly.customer.io/workspaces/112679/journeys/composer/transactional/21/templates/198
* required: https://fly.customer.io/workspaces/112679/journeys/composer/transactional/21/templates/199
