### ISSUE TITLE
NotificationClient get methods to send breaking change notifications

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#29922]
## What

We need to be able to send notifications for breaking changes from elsewhere in the platform. This is done by calling methods in the NotificationClient.

## How

1. Add to [NotificationClient](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-notification/src/main/java/io/airbyte/notification/NotificationClient.java) a method for:
- `notifyBreakingChangeWarning`
- `notifyBreakingChangeDisabled`
2. Add implementations on the CustomerioNotificationClient to render the CustomerIO template.
3. Add implementations on the SlackNotificationClient.

**Comment by pedroslopez** [comment]
These should be bulk methods and work off sending broadcasts as opposed to sending individual emails

**Comment by bnchrch** [comment]
Customer.io templates created
* pending: https://fly.customer.io/workspaces/112679/journeys/composer/transactional/21/templates/198
* required: https://fly.customer.io/workspaces/112679/journeys/composer/transactional/21/templates/199
