### ISSUE TITLE
Add breaking change notification settings

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#29920]
## What

The user should be able to configure whether they get breaking change notifications. This should be turned on by default.

### Backend

- Add `sendOnBreakingChangeWarning`/`sendOnBreakingChangeSyncsDisabled` to [NotificationSettings](https://github.com/airbytehq/airbyte-platform-internal/blob/master/oss/airbyte-config/config-models/src/main/resources/types/NotificationSettings.yaml)
- Handle the new setting in workspace update endpoint

### Frontend

Add the option to the notification settings page:

Name: **Breaking Changes Warning**
Description: A connection is affected by a breaking change and will be disabled soon if required action is not taken.

Name: **Breaking Change Connection Disabled**
Description: A connection was disabled due to a breaking change 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjlHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a645ec0d38a24418f86d017f433fd3fb2a3ab01e/image.png)

## Alternatives

There are two notification options that we could piggy back off of here:

- `sendOnSyncDisabled` / "Sync Disabled - A connection was automatically disabled due to repeated failures" -> could be used for when we disable the sync. We should update the description to mention breaking changes.
- `sendOnConnectionUpdateActionRequired` / "Connection Updates Requiring Action - A connection update requires you to take action (ex. a breaking schema change is detected)" -> could be used for notifications about upcoming breaking changes

## Acceptance criteria
- We have a way to configure notifications for breaking changes
- The notifications are on by default

**Comment by evantahler** [comment]
Grooming:

* When a new breaking change enters the platform - make a new notification category
  *   can't disable email
* When an upgrade deadline has passed and your syncs have been paused - share the 'Sync Disabled' notification 
  * already can't disable
  * we will need to redo the description copy
  *

**Comment by pedroslopez** [comment]
Because we can't do bulk slack messages properly, we should not allow turning on slack notifications for these
