### ISSUE TITLE
Source Mailgun:  test connection fail after upgrading to 0.2.0 

### ISSUE THREAD

**Issue by sc-yan** [airbytehq/airbyte#29985]
### Connector Name

Mailgun

### Connector Version

0.2.0

### What step the error happened?

Configuring a new connector

### Revelant information

with 0.2.0, an error happens during test connection. 
“Unable to connect to stream events - time data ‘’ does not match format ‘%Y-%m-%dT%H:%M:%SZ’”
0.1.1 has no problem.

### Relevant log output

```shell
“Unable to connect to stream events - time data ‘’ does not match format ‘%Y-%m-%dT%H:%M:%SZ’”
```

### Contribute

- [ ] Yes, I want to contribute

---------
there is another source connector issue opened, https://github.com/airbytehq/airbyte/issues/27385 , not sure if it's related. if so, feel free to close this issue.
![image](https://github.com/airbytehq/airbyte/assets/39505577/d18bdfac-1082-4be4-9cdb-764d05c019c0)

**Comment by marcosmarxm** [comment]
Can you confirm you have a start date in the connector configuration?

**Comment by sc-yan** [comment]
you mean the `Replication Start Date` field? that's optional right?
it's working with 0.1.0 connector without setting `Replication Start Date`

![image](https://github.com/airbytehq/airbyte/assets/39505577/d18bdfac-1082-4be4-9cdb-764d05c019c0)

**Comment by sc-yan** [comment]
interesting. I filled in the field `Replication Start Date` with connector 0.2.0, and the test connection succeeded.

maybe the `optional` property should be removed since it says "if omitted, default to 3 days ago"
![image](https://github.com/airbytehq/airbyte/assets/39505577/c0ce5fea-63c9-4736-bcc7-f8cf358890fc)

**Comment by ariesgun** [comment]
Would like to work on this one

**Comment by ariesgun** [comment]
PR #31405

**Comment by sc-yan** [comment]
thank you for fixing this ❤️
