### ISSUE TITLE
Source MSSQL (SQL Server) SSL implementation not complete

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#30004]
### Connector Name

source-mssql

### Connector Version

2.0.0

### What step the error happened?

Configuring a new connector

### Revelant information

The implementation of SSL in source-mssql is lacking some of the features that exist on the server.
Bring this connector to the same level of SSL implementation as other major DB connectors such as mysql and postgres.
[[mssql driver ref]](https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-with-ssl-encryption?view=sql-server-ver16).

### Contribute

- [ ] Yes, I want to contribute

**Comment by rodireich** [comment]
An implementation of general utility functions for SSL flow are used by other source connectors:
https://github.com/airbytehq/airbyte/pull/15993

**Comment by prateekmukhedkar** [comment]
We want the MS-SQL options to look familiar to an ms-sql expert (and so they will not similar to postgres or mysql options)
