### ISSUE TITLE
Prevent FeatureFlag % rollouts for connectors.  It's dangerous

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#30042]
Previous title: FeatureFlag % rollouts should only be applied for connector versions of the same major version

**Comment by erohmensing** [comment]
Alternative title: We only blue/green non-breaking changes

**Comment by evantahler** [comment]
We’ll need to modify the platform code to compare major versions of the connectors when being suggested a override, but we don’t have the info we need from LD to know if the override is a % based one or exact pin, which we seem to want to be handled differntly

**Comment by evantahler** [comment]
Grooming:
* Maybe % rollouts should only apply to those connections which are on 'latest'
* We probably need to split the feature flags so they can have different precedence (exact-pins vs % pins)
* Maybe we full-on disable % rollouts for connectors - you should do more analysis (white-glove, internal/external, support).  Launch Darkly doesn't have enough information.

**Comment by evantahler** [comment]
Put doc here https://www.notion.so/Connector-Version-Overrides-f1060408423d435887096f76b4a9854d

**Comment by evantahler** [comment]
https://www.notion.so/Connector-Version-Overrides-f1060408423d435887096f76b4a9854d?pvs=4#2e29ef9bec7b4d2691d4b50322babd6a
