### ISSUE TITLE
[source-stripe] does not support Incremental Sync Mode for `invoice_line_items`

### ISSUE THREAD

**Issue by satyanash** [airbytehq/airbyte#30073]
### Connector Name

source-stripe

### Connector Version

3.17.4

### What step the error happened?

During the sync

### Revelant information

There are two streams in the Stripe Source:
- `invoices`
- `invoice_line_items` which is a "sub-stream" of invoices.

<img width="986" alt="Screenshot 2023-09-01 at 9 14 53 AM" src="https://github.com/airbytehq/airbyte/assets/1559596/73aef0f7-0ec0-4024-8337-9becd11ac159">

The `invoice_line_items` does not support the "Incremental | Append" sync mode, even though its parent stream `invoices` supports it. Any of the two remaining options cause a Full Refresh on the `invoices` stream to happen on every sync, even if that parent stream is set to "Incremental | Append" mode. I have attached the relevant log lines which indicate that Airbyte does two separate syncs, and fetching a super-set of the data when syncing the `invoice_line_items` from the parent stream.
This also defeats the purpose of having "Incremental | Append" on the parent stream, since the sub-stream causes a "Full Refresh ..." of the parent stream anyway and takes a much longer time.

### Relevant log output

```shell
{
  "streamStats" : [ {
    "streamName" : "invoices",
    "stats" : {
      "bytesCommitted" : 147562,
      "bytesEmitted" : 147562,
      "recordsEmitted" : 32,
      "recordsCommitted" : 32
    }
  }, {
    "streamName" : "invoice_line_items",
    "stats" : {
      "bytesCommitted" : 194884577,
      "bytesEmitted" : 194884577,
      "recordsEmitted" : 129096,
      "recordsCommitted" : 129096
    }
  } ]
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by davydov-d** [comment]
Incremental sync mode added to InvoiceLineItems in version 4.0.0

**Comment by maxi297** [comment]
It seems like this issue was closed while the InvoiceLineItems stream had never been incremental. Hence, I'll re-open the issue

**Comment by enkeboll** [comment]
I'd like to call out that SubscriptionItems is also not incremental, as of version v5.3.9

![image](https://github.com/airbytehq/airbyte/assets/4869523/ff320e57-e93c-4281-bca7-f4aeaa9b071d)

`SubscriptionItems` and `InvoiceLineItems` represented 99% of our billed rows per sync, so we had to separate them into separate connections to sync on different schedules than the incremental tables.

**Comment by FilahAnas** [comment]
Hello, Here is a PR to resolve this issue: [43711](https://github.com/airbytehq/airbyte/pull/43711/ )

**Comment by williamkaper** [comment]
I put up a PR that adds incremental support to both invoice line items and subscription items: https://github.com/airbytehq/airbyte/pull/45860

**Comment by AnaisI01** [comment]
I also encounter this problem, for these tables:
accounts,
invoice_line_items,
subscription_items

**Comment by williamkaper** [comment]
> I also encounter this problem, for these tables:
> accounts,
> invoice_line_items,
> subscription_items

@AnaisI01 I have PRs up for all these. One pr deals w invoice items and subscription items, one deals with accounts, customer balance transactions, and transfer reversals, and one adds a payouts_balance_transactions table

Re-pinging this. I have a bunch of PRs that are still waiting for review:

Stripe:
https://github.com/airbytehq/airbyte/pull/45860
https://github.com/airbytehq/airbyte/pull/46499
https://github.com/airbytehq/airbyte/pull/46864

If you ping these PRs and tag sone of the devs and/or go to the airbyte Slack and comment on my thread it will hopefully help get it reviewed

https://airbytehq.slack.com/archives/C054V9JFTC6/p1729858758916829?thread_ts=1728139487.241329&cid=C054V9JFTC6
