### ISSUE TITLE
Propagate all changes option does not add new streams or columns

### ISSUE THREAD

**Issue by Auric-Manteo** [airbytehq/airbyte#30093]
### Topic

Propagate all changes option does not add new streams or columns

### Revelant information

Expected behavior: New streams or columns should be activated automatically on the next sync.
Actual behavior: New streams or columns are ignored meaning that the new streams are inactive and new columns do not show.

https://github.com/airbytehq/airbyte/assets/112462529/1f43c36c-dcee-430f-b12f-a08a6350b0b7

**Comment by Auric-Manteo** [comment]
Still the same behavior with the newest version. 
I reproduced it by setting up an entirely new connection (MySQL->Redshift).

**Comment by flutra-osmani** [comment]
Refining notes:
- a feature flag was blocking the addition of the new stream in the next sync cycle. Already fixed.

**Comment by flutra-osmani** [comment]
Changes are now available with the new release [v0.50.36](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.36)
