### ISSUE TITLE
Change Google Analytics 4 "Custom Reports" to be multi-line

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#30110]
The "Custom Reports" field in Google Analytics 4 is 1 line, making it difficult to debug and use for JSON.

![239085234-4b613c93-e1ad-4d3c-8790-dcc8d39ad0d5](https://github.com/airbytehq/airbyte/assets/38087517/45fa6f02-155d-4754-858e-33e0b4a9c39b)

Suggestion: make this a multi-line field.

**Comment by lazebnyi** [comment]
Duplicate - https://github.com/airbytehq/airbyte/issues/23874
