### ISSUE TITLE
Source Hubspot: Add required scopes

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#3011]
## Tell us about the documentation you'd like us to add or update
For each stream check with API docs and add the required scopes.

## Are there any related areas of documentation that currently exist? Could you point to them?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368226633735) by [Unito](https://www.unito.io)

**Comment by htrueman** [comment]
List of streams with required scopes:
Stream - Required Scope
- `campaigns` - `content`
- `companies` - `contacts`
- `contact_lists` - `contacts`
- `contacts` - `contacts`
- `deal_pipelines` - either the `contacts` scope (to fetch deals pipelines) or the `tickets` scope.
- `deals` - `contacts`
- `email_events` - `content`
- `engagements` - `contacts`
- `forms` - `forms`
- `line_items` - `e-commerce`
- `owners` - `contacts`
- `products` - `e-commerce`
- `quotes` - no required scope
- `subscription_changes` - `content`
- `tickets` - `tickets`
- `workflows`- `automation`

**Comment by htrueman** [comment]
NOTE: merge https://github.com/airbytehq/airbyte/pull/5864 once Oauth support is added to the connector.

**Comment by misteryeo** [comment]
Closing as this was merged.
