### ISSUE TITLE
useIntent should not throw for missing organization id

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#30124]
I broke staging with [this pr](https://github.com/airbytehq/airbyte-platform-internal/pull/8668) because our staging workspace doesn't have an org -- which is great that it broke there and not for users!

Let's consider how to handle the interim state where not all workspaces have an org a bit better.

**Comment by josephkmh** [comment]
Refining notes:
- If `organizationId` is null, `useIntent()` should return false instead of throwing
- In some cases it might still make sense to throw, e.g. if you're on `/workspaces` and try to use something like `useIntent(Workspace.ReadWorkspace)`
