### ISSUE TITLE
allow users to access both the api and webapp from the same port

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3014]
## Tell us about the problem you're trying to solve
We have a lot of users that run into problems when dealing with separate ports. There are two main cases:

1. Confusion when setting up tunnels
1. Problems dealing with setting `API_URL`

I've personally run into at least five instances of these types of issues. I imagine there are more cases I haven't been involved in.

## Describe the solution you’d like
We could separate nginx into its own container and use it to proxy from both the webapp and the server on a shared port. This also might make it slightly easier to document how a user can add basic auth at the nginx level. 

## Describe the alternative you’ve considered or used
We could also bundle the apps together and offer them on the same image.

- - -
I'm putting this at a medium priority instead of low just because we've seen this come up frequently.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368161850714) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
That's a great idea!
