### ISSUE TITLE
Fail metadata validation on extraneous fields

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#30169]
* Disable top-level extra fields
  * allow-list known properties
 
Top-level allowExtra was enabled when fighting with underscores.

What do we do about old files with `_ab...`.  Might need special-case handing. We could store them in the allow-list for historical reasons.  These problems go away with V2 of metadata spec.   Could we remove those old versions from the registries?
  * let's remove old metadata versions them! 
  * These can be identified by metadata entries with `_ab_.**` fields
     * we can find them by certain dates... (PLAN A)
     * could we delete everything before this date?  Seems scary... but... maybe? (PLAN B)

**Comment by evantahler** [comment]
Be sure to run metadata service validate on all metadata files when this is done

**Comment by bnchrch** [comment]
Ran a small script to change the old metadata files from _ab_internal to ab_internal
