### ISSUE TITLE
Ddestination Snowflake: giving errors for BigQuery source when RECORD type with REPEATED mode

### ISSUE THREAD

**Issue by rengler-noodle** [airbytehq/airbyte#30179]
### Connector Name

destination-snowflake

### Connector Version

3.1.0

### What step the error happened?

During the sync

### Revelant information

BigQuery -> Snowflake

airbyte/source-bigquery:0.3.0
airbyte/destination-snowflake:3.1.0

Prior to the dv2 rollout in our airbyte cloud account, there weren't issues loading these columns from BigQuery.

Presently when syncing (even after full table deletion, connector reset, and full re-sync), the `_AIRBYTE_META` column is presenting the following message:

```
{
  "errors": [
    "Problem with `user_properties`",
    "Problem with `event_params`",
    "Problem with `items`"
  ]
}
```

The consistent thing between these columns is that they are `RECORD` types in BigQuery with `REPEATED` mode.

The problematic Snowflake columns are `Object` columns. I *believe* they were formally `Variant` columns.

Here is an example of the BigQuery schema (this is google analytics 4 raw data):

<img width="517" alt="image" src="https://github.com/airbytehq/airbyte/assets/94383622/b8a11848-6ef2-48a8-a6b4-ac3855d97987">

The result in Snowflake is that the entire column now has null values. The sync completes successfully.

Hopefully this is enough to work with, I want to avoid pasting any logs or data since this is sensitive data. Happy to try to provide more if needed.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Are you able to provide a sample record in BigQuery that has this problem?

**Comment by evantahler** [comment]
Reclassifying this as a sources bug (cc @prateekmukhedkar). 
As `source-bigquery` is an Alpha connector, we will not be able to prioritize fixing this any time soon... @rengler-noodle are you interested in changing how Discover works for `source-bigquery` (check out the `discoverInternal` method)?

**Comment by rengler-noodle** [comment]
> are you interested in changing how Discover works for `source-bigquery` (check out the `discoverInternal` method)?

Sorry I won't have the time to attempt a fix

**Comment by shmf** [comment]
@evantahler i might be interested in having a look at this but as far as i can see the problem is not in `discoverInternal` - the table is discovered correctly as a repeated struct.
any idea where else i can look?

**Comment by shmf** [comment]
The above PR is mine.
