### ISSUE TITLE
Either Quote, mangle, or directly prevent column names with reserved words (SNOWFLAKE)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#30190]
Related to this [page](https://airbytehq.sentry.io/issues/4398228154/?project=6527718), [sync](https://cloud.airbyte.com/workspaces/c67963ed-2c60-4fde-a83b-72dc7de2c245/connections/bdbad1c8-f484-40ef-b1cb-666c4e838db6/job-history#4473759::4), and [slack thread](https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1693986349800509):

```
Stack Trace: net.snowflake.client.jdbc.SnowflakeSQLException: JavaScript execution error: Uncaught Execution of multiple statements failed on statement "CREATE OR REPLACE TABLE "(truncated)" (at line 3, position 0).
SQL compilation error: error line 17 at position 1
.invalid column definition name 'CURRENT_DATE' (ANSI reserved) in SYSTEM$MULTISTMT at '    throw `Execution of multiple statements failed on statement {0} (at line {1}, position {2}).`.replace('{1}', LINES[i])' position 4
stackstrace: 
SYSTEM$MULTISTMT line: 10
```

We either need to:
* Figure out how to allow columns with these reserved words, possibly by quoting them
   * `create or replace table RESERVED_COLS (ID NUMBER, "CURRENT_DATE" TIMESTAMP);` (with quotes) still fails.  Is there another way to quote this column?
   * `create or replace table RESERVED_COLS (ID NUMBER, "current_date" TIMESTAMP);` (lower case was OK)
   * Why did this stream use to be OK in v1/normalization?  [This](https://github.com/airbytehq/airbyte/blob/evan/reomve-bigquery-denormalized/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/destination_name_transformer.py#L171), which is called when `is_reserved_keyword() ==True` implies with the right amount of quoting, reserved column names would be OK... 
* Mangle the name of the columns to be valid, e.g. `CURRENT_DATE` could become `_CURRENT_DATE`
* Fail the syncs early with a clear error message (e.g. `column CREATED_AT is not allowed`)

Snowflake clearly lists it's reserved words here: https://docs.snowflake.com/en/sql-reference/reserved-keywords

**Comment by evantahler** [comment]
This story is likely related to https://github.com/airbytehq/airbyte/issues/28323

**Comment by tybernstein** [comment]
The user disabled the problematic stream and is now succeeding.

**Comment by evantahler** [comment]
Grooming:
Step 1 is to make a table with a CURRENT_DATE column and run Destination V1 + normalization and see what happens.  Does it really succeed?  Does it skip the column?

**Comment by cynthiaxyin** [comment]
So normalization actually does something bad which is it retains the `CURRENT_DATE` column but then fills it with the actual current date rather than keeping the values from the source. The sync does succeed, but this behavior is wrong so we shouldn't aim to replicate it.

There is another option: drop the column and log an error but still complete the sync

I think we're leaning towards preserving the column but modifying the name (ex: add `_` in front), so the customer can still have that data.
