### ISSUE TITLE
Destination V2 Snowflake: normalization error using V1 tables

### ISSUE THREAD

**Issue by dimoschi** [airbytehq/airbyte#30212]
### Connector Name

destination-snowflake

### Connector Version

3.1.1

### What step the error happened?

During the sync

### Revelant information

On a new connection between MySQL and Snowflake utilising Destinations V2, it tries to normalize data using dbt, which as I understand it shouldn't. For a new connection, the V2 Destination shouldn't bother looking for any `_AIRBYTE_RAW_<stream>` table as they shouldn't exist at all. Even though the sync fails, data exist in Snowflake.
[a0117286_6815_4c3a_8575_98b3b5ac8274_job_5162_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/12540556/a0117286_6815_4c3a_8575_98b3b5ac8274_job_5162_attempt_1_txt.txt)

### Relevant log output

```shell
1 of 3 ERROR creating view model _AIRBYTE_CTF_V2.CTFS_STG............................................................... [ERROR in 0.81s]
Database Error in model CTFS_STG (models/generated/airbyte_views/CTF_V2/CTFS_STG.sql)
  002003 (42S02): SQL compilation error:
  Object 'AIRBYTE_DATABASE.CTF_V2._AIRBYTE_RAW_CTFS' does not exist or not authorized.
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_views/CTF_V2/CTFS_STG.sql,retryable=<null>,timestamp=1694013024186,additionalProperties={}]],additionalProperties={}]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by edgao** [comment]
what version of platform are you running? You might need to manually disable normalization if it's too old - I know @evantahler released a new version of platform recentishly with the "skip normalization for dv2 connectors", but can't remember which version number that was

Just to confirm though - the dv2 tables are getting created correctly? Your logs are saying that the destination ran successfully, so (other than the sync history looking weird) I would expect that your data exists in the destination

**Comment by evantahler** [comment]
The minimum version of the platform required for Destinations v2 is 0.5.24 ([docs](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2))

**Comment by evantahler** [comment]
@dimoschi are you running your Airbyte server in an air-gapped environment?  What should have happened when you clicked on the settings page to select the new connector version is that you would have downloaded new connector metadata that tells the platform not to run (or allow) normalization for destination-snowflake >= v3.  If that download failed, you would be in this position.

Can you confirm the above by dumping the contents of the `actor_definition_version` table on your airbyte database to a file and commenting it here?

Either way, toggle off normalization for your sync and things should be OK.

**Comment by dimoschi** [comment]
@edgao I'm using the following versions
* Airbyte v0.50.27
* Snowflake v3.1.1
* MySQL v3.0.3

As you can see for yourself in the following images I don't have any option to skip normalization.
![Screenshot 2023-09-07 at 12 03 53 PM](https://github.com/airbytehq/airbyte/assets/13113025/19d7db4c-ef25-4e4f-aab4-b9cec4d9a44b)

> Just to confirm though - the dv2 tables are getting created correctly? Your logs are saying that the destination ran successfully, so (other than the sync history looking weird) I would expect that your data exists in the destination
Tbh, I'm not sure what to expect anymore from Dv2 syncs. So far trying to set a new sync doesn't work and for the old ones that got updated I have in Snowflake lower-case, upper-case, old raw tables and new raw tables and none of them is updated with the latest data.

@evantahler No, it's not air-gapped. Please find attached the file.
[actor_definition_version.csv](https://github.com/airbytehq/airbyte/files/12546994/actor_definition_version.csv)

As for the normalization, I cannot toggle it off. Either I select "Raw data (JSON)" or "Normalized tabular data", which none works for me.

**Comment by dimoschi** [comment]
As I said in another issue, stopping Airbyte, removing all containers and images and restarting it, resolved most of the issues.

**Comment by edgao** [comment]
interesting. Choosing the `raw json` option _should_ have been enough to disable normalization (though the name is a bit confusing). DV2 always runs typing+deduping, regardless of what that option is set to.

and yeah, destination-snowflake has gone through a few changes in response to user feedback. The uppercased tables should have been updated. I'm seeing typing and deduping run for the `CTF_V2.CTFS` table in your logfile - it sounds like you've gotten it into good state, but if you remember what it looked like yesterday, that would be helpful for understanding what happened.

we're continuing to investigate why normalization wasn't automatically disabled though.

**Comment by edgao** [comment]
also - do you remember how you upgraded platform/destination-snowflake? Specifically: did you upgrade to destination-snowflake 3.1.1 before or after upgrading platform? And what version of platform were you running before the upgrade?

We have a guess for what happened - if you upgraded the connector before upgrading platform, and you were running a sufficiently-old version of platform, then that would put you in a weird state. If that's what happened, then we'll update the upgrade guide to tell users to upgrade platform first.

**Comment by dimoschi** [comment]
@edgao, we are in a much better state than yesterday indeed, although we still encounter some weird issues. Choosing the `raw json` didn't work as you described.

As for the upgrade path, unfortunately, I upgraded the connector first and then upgraded the platform to the latest version. Before I was running Snowflake on version `v2.1.x` I don't remember exactly and the platform was running on `v0.42.x`, again don't remember the exact version.

Updating the documentation would be nice, I would suggest also implementing something in the platform to disallow upgrading connectors if the platform is not on a compatible version. I understand this is not an easy task, but would be a great quality of life improvement.

Thank you very much for your help, both you and @evantahler, I appreciate it.

**Comment by evantahler** [comment]
Happy to help, @dimoschi!
We'll get those docs updated soon (https://github.com/airbytehq/airbyte/pull/30264).  We've got a future project we'll be working on about connector/platform/protocol version compatibility - it's definitely something we need!

If things are OK for you now, please close the issue.  Thanks!
