### ISSUE TITLE
Logs window interferes with upgrade message

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#30224]
tiny UI nit - the logs window appears behind the `Destination upgraded successfully` message, but it actually blocks mouse interaction with upgrade message. I can’t click the `guide` link or hit the x-button until I close the logs

![image](https://github.com/airbytehq/airbyte/assets/5741425/189ef42e-ab27-429f-885c-cc63b7ae9977)

**Comment by josephkmh** [comment]
We've got an issue open here: https://github.com/airbytehq/airbyte/issues/26757

So I'll go ahead and close this one
