### ISSUE TITLE
Make `airbyte connectors list` output version of base image in use

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#30244]
For auditing the progress of our base image adoption we should make our `airbyte-ci connectors list` command output the value of `connectorBaseImage` for all connectors + if a pre/post build hook is declared for a connector

**Comment by alafanechere** [comment]
Listing all the connectors using a specific base image can probably be already be done with the metadata query option.

**Comment by alafanechere** [comment]
I'm able to list the connector with the `baseImage` field set with:
`airbyte-ci connectors --support-level=certified --metadata-query="data.connectorBuildOptions.baseImage is not None" list`

But I can't find a way to select the connectors without this field..
`airbyte-ci connectors --support-level=certified --metadata-query="data.connectorBuildOptions.baseImage is None" list` outputs all the certified connectors (even those with the `baseImage` field set.

**Comment by bnchrch** [comment]
@alafanechere try 
```
airbyte-ci connectors --support-level=certified --metadata-query="not data.connectorBuildOptions.baseImage" list
```

**Comment by bnchrch** [comment]
@alafanechere This one should work
airbyte-ci connectors --metadata-query="data.supportLevel == 'certified' and 'connectorBuildOptions' not in data.keys()" list
