### ISSUE TITLE
Organization-centric workspace creation in OSS/Enterprise

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#30260]
Update the workspace creation flow to take organizations into account.

If a user is an organization_admin or greater in 0 organizations, they cannot create one.

If they are an organization_admin or greater in 1 organization, they should see it listed on the workspace create modal.

If they are an organization_admin in >1 organization, they should be able to select which one they create the new workspace in.

[whimsical](https://whimsical.com/creating-a-workspace-4hRd9bCTFdkUBjmHfRgnD4)

discussion about `organizations/list_by_user` [here](https://github.com/airbytehq/airbyte-platform-internal/issues/8525#issuecomment-1710535760)

**Comment by josephkmh** [comment]
Refining notes:
- This depends on all users having an organization, which is being done as a part of this migration: https://docs.google.com/document/d/1yVGdmExENXmBi5kzvnHE5us3SP2zPugXBvo_zOtAHQk/edit#heading=h.fa72b39y2m99

**Comment by tealjulia** [comment]
> In OSS there is no use case for multiple organizations. If there's only one organization, it should auto-select

Yes.  For users with only one organization (most users), I was planning to show the organization name as `Text` rather than utilize `ListBox`.

Was just thinking on this -- we likely want a ListBox that supports pagination and search. Otherwise, this will be virtually unusable for `instance_admin` on cloud.
