### ISSUE TITLE
Update spec cache on connector version update to dev (Allow ADV Upserts)

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#30277]
When developing a connector and testing in the UI, the following process needs to be followed to change the spec:
* Build the new docker image with a new tag
* Go to Settings>Sources/Destinations and update the connector
* Go to the source/destination config view

This is happening because the spec is cached and not updated until the docker tag of the connector is changed.

As spec commands are mostly fairly fast for locally available images and working with the most recent version of the spec is often very important, the behavior should be changed to always re-fetch the spec when changing the docker tag to dev, even if it is dev already..

This is roughly a revert of https://github.com/airbytehq/airbyte-platform-internal/pull/7093

---

This will re-enabled special SPEC handling for DEV versions

---

This spec workflow reflected in [Evan's connector developer guide](https://www.notion.so/Evan-s-Connector-Development-Process-94183a4b7fb04d05b78c91e598f7d9c1)

**Comment by flash1293** [comment]
cc @pedroslopez

**Comment by erohmensing** [comment]
Specifically, we are fetching the ADV from the database for any tag that has been previously used, instead of refetching the spec

**Comment by evantahler** [comment]
cc @gisripa - this should make working on connector specs a little better

**Comment by bnchrch** [comment]
grooming
* We have the code that writes ADVs copied to 3 locations.
* Indicates that we need to start merging source and destination defs
* May add some refactoring work to our next quarter when updating how ADVs get created
