### ISSUE TITLE
Create a contributor bootstrap script

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3028]
## Tell us about the problem you're trying to solve
As a contributor I want to run a single bash command that verifies that I have all the necessary commands to get started: 

* Docker
* Java 14
* pip 20.1
* Python 3.7.9
* jq
* 

## Describe the solution you’d like
A single bash script that makes this process as seamless as possible by verifying that I have the right version of all software installed. 

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368103577755) by [Unito](https://www.unito.io)

**Comment by nclsbayona** [comment]
Hi! Not sure if this is what you meant, maybe it is, please let me know.
[check_requirements.txt](https://github.com/airbytehq/airbyte/files/6362162/check_requirements.txt)

**Comment by sherifnada** [comment]
@nclsbayona thanks for creating this! This is a great start. some comments: 

1. Could you create a PR so we can review/merge afterwards?
2. could you put this into a bash script in `./tools/bin/` ?

**Comment by nclsbayona** [comment]
#3058

**Comment by cgardens** [comment]
@sherifnada i merged @nclsbayona 's script. Do we want to add it as part of the build or should we just add it to the docs as a pre requ?

**Comment by sherifnada** [comment]
We should definitely add it to the getting started docs and maybe to the build if we can get any error messages to display nicely. Will close this ticket once that's done.

**Comment by noahkawasakigoogle** [comment]
Related PR: https://github.com/airbytehq/airbyte/pull/9230

**Comment by supertopher** [comment]
I believe that we have solved this problem through this PR

if you disagree please come in.  closing the issue
