### ISSUE TITLE
source-mssql: improve error handling for CDC syncs with source schema changes

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#30283]
### What area the feature impact?

Connectors

### Revelant Information

Source schema changes are [not supported for CDC connections](https://docs.airbyte.com/understanding-airbyte/cdc/#limitations), but sometimes syncs impacted by this are still marked "Successful" despite data not being synced.

This can be misleading to Airbyte users who aren't aware of this gotcha with CDC.

1. Can we add better log messages so users know they need to reset data?
2. Does it make sense to mark syncs as "Successful" if the source schema changed, causing some/no data to be synced?

**Comment by luis-settle** [comment]
Curious if with CDC streams users can stop stream runs when there is a detected schema change?

**Comment by evantahler** [comment]
Should be fixed in the latest versions of mssql
