### ISSUE TITLE
Source Salesforce: Salesforce invalid start date

### ISSUE THREAD

**Issue by StuartMiddleton** [airbytehq/airbyte#30293]
### Connector Name

source-salesforce

### Connector Version

2.1.4

### What step the error happened?

Updating the connector

### Revelant information

We had an existing Salesforce source that was configured with a start date of format YYYY-MM-DD. After updating to the latest connector version, the sync failed. Testing the connection failed with an invalid date error, and this was resolved by replacing the existing date format of YYYY-MM-DD with one of format YYYY-MM-DDTHH:mm:ssZ.

On-screen documentation states the following formats are valid: YYYY-MM-DD or YYYY-MM-DDTHH:mm:ssZ.

### Contribute

- [ ] Yes, I want to contribute

**Comment by StuartMiddleton** [comment]
These similar issues may also be related:
https://github.com/airbytehq/airbyte/issues/23781
https://github.com/airbytehq/airbyte/issues/14523

**Comment by maxi297** [comment]
Hey @StuartMiddleton!

This is because the type has been changed from a date to a datetime. Is there something preventing you to update the config to the next datetime format?

**Comment by StuartMiddleton** [comment]
@maxi297 
It's been a while since I raised this, but I suspect that it was more a documentation issue than a connector issue based upon your response. As I indicated;

> On-screen documentation states the following formats are valid: YYYY-MM-DD or YYYY-MM-DDTHH:mm:ssZ.

From your comment, I guess that text needs to be updated.
