### ISSUE TITLE
Source Square: Customers object not paginating

### ISSUE THREAD

**Issue by juftin** [airbytehq/airbyte#30309]
### Connector Name

source-square

### Connector Version

1.1.2

### What step the error happened?

During the sync

### Revelant information

The `customers` stream returns a maximum 100 responses because it is not paginating https://developer.squareup.com/reference/square/customers-api/list-customers#query__property-limit

### Contribute

- [X] Yes, I want to contribute
```[tasklist]
### Tasks
- [ ] https://github.com/airbytehq/airbyte/pull/30315
```

**Comment by topefolorunso** [comment]
PR raised for this here https://github.com/airbytehq/airbyte/pull/30315 @justinbchau @marcosmarxm

**Comment by juftin** [comment]
FWIW there's some issues on paginating `payments` and `refunds` as well. For those objects airbyte is returning tons of duplicates. I'm just performing a `select distinct` on them downstream to resolve this but the `square` connector needs some work.

**Comment by topefolorunso** [comment]
@justinbchau Maybe move to In Progress instead as the PR is still open, it hasn't been merged yet.

**Comment by topefolorunso** [comment]
> FWIW there's some issues on paginating `payments` and `refunds` as well. For those objects airbyte is returning tons of duplicates. I'm just performing a `select distinct` on them downstream to resolve this but the `square` connector needs some work.

@juftin Can you open a separate issue in this regard? CC: @marcosmarxm
