### ISSUE TITLE
Source Asana: Add the real Section stream (Not SectionCompact)

### ISSUE THREAD

**Issue by ffesseler** [airbytehq/airbyte#30304]
### Topic

Asana connector improvement

### Revelant information

Hi, the Asana connector currently supports the Section endpoint, however, it is only using SectionCompact. The current Airbyte implementation makes it so we are missing a large amount of useful information for analytics.

https://developers.asana.com/reference/section

Any chance we could get the current Airbyte stream renamed to "SectionCompact" and have the real "Section" stream added?

Thanks!

**Comment by ffesseler** [comment]
Another similar issue with the story stream : https://github.com/airbytehq/airbyte/issues/28939

**Comment by topefolorunso** [comment]
I will work on this @justinbchau

**Comment by ffesseler** [comment]
Thanks for the improvement !
