### ISSUE TITLE
Platform: Enforce Catalog Correctness

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#30341]
We are running into cases with Custom Sources where the discovered catalog is incorrect. Specifically, the returned catalog contains Primary Keys or Cursors the schema doesn't have.

e.g:
```
{
  streams: [ {
    name: foo,
    json_schema: {
      properties: {
        id: {type: integer},
        updated_at: {type: string}
      }
    },
    default_cursor_field: inserted_at, (this cursor needs to contain a field present in the json_schema)
    source_defined_primary_key: [email] (all the fields in this primary key need to be present in the json_schema)
  } ]
}
```

Definition of Done:
- enforce the returned catalog does not have a cursor that isn't present in the schema.
- enforce the returned catalog does not have a primary key that isn't present in the schema.
- in both cases, we want to fail discover schema.
- we should be able to catch this in the discover schema operation.

Seen in https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1694524129206439.

**Comment by evantahler** [comment]
Note: this is differnt than the xmin case (https://github.com/airbytehq/airbyte/issues/29633) because xmin doesn't declare a cursor, this connector does

**Comment by jbfbell** [comment]
To add a little scope creep to this ticket, we should also throw a config error for primary key columns found not in the schema per https://github.com/airbytehq/oncall/issues/2989
