### ISSUE TITLE
2-stage syncs strategy for more efficient copying.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3035]
## Tell us about the problem you're trying to solve
A [user](https://airbytehq.slack.com/archives/C01MFR03D5W/p1619158994214100) is ran into an issue with the Redshift destination where he was trying to upload a table of 115GB - the current per-table limit we support is 100GB. This is because the maximum parts an S3 multipart upload can contain is 10k. We currently have each size to be 10MB, giving us 10 * 10l ~= 100GB. This size is somewhere arbitrary, and was a sane default at that time as most of our users do not deal with table sizes greater than tens of GB. The trade off here is in-memory requirements and replication speed - the smaller the part size, the less in-memory requirements and the faster each part begins uploads.

This exposes two potential issues for the future we should think about:
1) Users should be able to configure the part size equivalent for the cloud storage (and by extension warehouse) destinations they are deliver-ing data to.
2) The initial sync for incremental syncs should have configurations more appropriate for the large initial dump. Subsequent syncs should switch to a configuration more appropriate for incremental syncs.

## Describe the solution you’d like
We should discuss this and come to a consensus on how to approach this.

## Describe the alternative you’ve considered or used
None. We should brainstorm this.

## Additional context
I will address the initial Redshift issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368160357594) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
FYI: GCS uses composite objects instead of parts https://cloud.google.com/storage/docs/composite-objects

**Comment by sherifnada** [comment]
@evantahler @davinchia should this still be open?

**Comment by davinchia** [comment]
This is done.
