### ISSUE TITLE
How to set heartbeat / stdin / stdout limit

### ISSUE THREAD

**Issue by edge7** [airbytehq/airbyte#30377]
### Topic

Resource limit setting 

### Revelant information

Hi,
When I run my job, I see:

`ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@373b5c13[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}], heartbeat=io.airbyte.config.ResourceRequirements@204c3fbe[cpuRequest=0.1,cpuLimit=2.0,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdErr=io.airbyte.config.ResourceRequirements@77b049cf[cpuRequest=0.25,cpuLimit=2,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdIn=io.airbyte.config.ResourceRequirements@747fdf36[cpuRequest=0.1,cpuLimit=2.0,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdOut=io.airbyte.config.ResourceRequirements@747fdf36[cpuRequest=0.1,cpuLimit=2.0,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}]] and allowedHosts null`

the main requirements are not set, but the heartbeat/stdIn/stdOut are.
We suspect that might create an issue for one of our big Job.
How can those be set up, we don't see anything in the doc.

Cheers

**Comment by davinchia** [comment]
Unfortunately it's not possible to inject these for now. We aren't likely to make this injectable since they are currently tuned for performance sizes.
