### ISSUE TITLE
Source MongoDb: Missing date data type

### ISSUE THREAD

**Issue by tzing** [airbytehq/airbyte#30385]
### What area the feature impact?

Connectors

### Revelant Information

I'm using latest Mongo source (`airbyte/source-mongodb-v2:0.2.5`) and found date and time field are not properly mapped.

I think it's caused by this code, which intentionally converts date time to string type:

https://github.com/airbytehq/airbyte/blob/3fec3cc7b68a320e38d2eb6586f5ef5f46f87919/airbyte-db/db-lib/src/main/java/io/airbyte/db/mongodb/MongoUtils.java#L100-L109

Is there a reason for not using date type?

**Comment by girarda** [comment]
closing because the mongodb source has been revamped in the last year. feel free to reopen if this is still an issue
