### ISSUE TITLE
bump testcontainers version to latest

### ISSUE THREAD

**Issue by postamar** [airbytehq/airbyte#30392]
### Topic

bump testcontainers version to latest 

### Revelant information

Bumping testcontainers to the latest version breaks all db-sources integration tests except for source-postgres. This seems to happen only in airbyte-ci. This seems due to a combination of a networking issue, and dagger shutting down the docker-in-docker container too early. Fix this at least for source-mysql.

Related:
https://github.com/airbytehq/airbyte/pull/30280
https://github.com/airbytehq/airbyte/pull/30032
https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1694015739924069
https://github.com/airbytehq/airbyte/pull/30384

**Comment by prateekmukhedkar** [comment]
Definition of done: CI tests work for source-mysql.
