### ISSUE TITLE
airbyte-ci: make dagger stream logs consistently

### ISSUE THREAD

**Issue by postamar** [airbytehq/airbyte#30394]
### Topic

make dagger stream logs consistently

### Revelant information

Dagger does not stream logs consistently. Why does it sometimes chunk them so aggressively? This is visible when running the connector tests for a java connector. Notice how integration tests logs come in an all-or-nothing fashion.

We should ask about this on the dagger discord. ~Is this happening client side, server side, both?~

edit: the issue has since been identified and a workaround has been made in the form of https://github.com/airbytehq/airbyte/pull/30438 . As this is a workaround and not a fix, we should still contact the dagger maintainers with a request to improve their scrubbing. The improvement could be something as simple as detecting whether all secrets are non-multiline, and if that's the case apply the scrubbing on a line-by-line basis and flush the streams correspondingly.

**Comment by alafanechere** [comment]
Closing as dagger worked on  https://github.com/dagger/dagger/issues/5792 and https://github.com/dagger/dagger/issues/5791 . We'll benefit from these fixes on the upgrade to Dagger 0.9.4 (#33429)
