### ISSUE TITLE
[source-mysql] CDC incremental sync failing with OOM error

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#30396]
Line 8479 `2023-08-30 20:48:09 source > Terminating due to java.lang.OutOfMemoryError: Java heap space`

https://cloud.airbyte.com/workspaces/db595480-6b90-4b89-8374-a5d8a8ff3792/connections/c8bd5d9f-8158-4d25-8731-521c97336d43/job-history#4340755::4

**Comment by subodh1810** [comment]
We have reached out to the customer and asked them to re-enable the connector to see if our compression changes around schema history will make any difference

**Comment by subodh1810** [comment]
The user has stopped using Airbyte. Going to close this.

**Comment by shmf** [comment]
Hey, I am facing the same issue on the self hosted instance.

Airbyte version is 0.51
MySQL version is 3.3.10 (but tried with 3.3.13 too)
