### ISSUE TITLE
[source-mysql] Syncs failing with State code: 08S01

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#30393]
Root cause failure message 
`Failure Origin: source, Message: State code: 08S01; Message: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
`

Workspaces https://cloud.airbyte.com/workspaces/dd866550-52e8-4d00-8be9-9e623e7faf8c/connections/41c7e3d5-6df2-4aa0-bdc7-cc4bb7b86c95/job-history#4559667::0

https://cloud.airbyte.com/workspaces/8da841dc-0c08-4715-a16c-98b7b262e4eb/connections/51359dfb-14c1-4b2f-b99a-18093f481ed2/job-history#4611986::0

**Comment by nguyenaiden** [comment]
@prateekmukhedkar, do I have permission to recheck the connection? The error seems to be related to connection issues to the source db.

**Comment by subodh1810** [comment]
Same for the other [connector](https://cloud.airbyte.com/workspaces/8da841dc-0c08-4715-a16c-98b7b262e4eb/source/46d397f1-7181-4902-bd51-67f187509c41) as well. 

We should ask TCS to reach out to both these users and ask them if they have removed the IPs and double check if all our IPs are whitelisted
