### ISSUE TITLE
Remove scheduler/server logs download buttons, configuration page

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#30429]
The configuration page (OSS only) has two buttons for downloading logs:

![image](https://github.com/airbytehq/airbyte/assets/7550957/a1fd2bbe-275e-49b9-94a4-01717b1d8224)

These are very, very rarely clicked according to our [metrics](https://airbyte.metabaseapp.com/dashboard/1689-scheduler-server-logs-downloads). We should remove them! We're starting to add more settings pages, so we should reduce clutter.

**Comment by josephkmh** [comment]
Refining notes:
- It should be clear in the docs how to download server logs and scheduler logs. Check APIs to see what exactly they're returning, and confirm that they can be accessed some other way (no special handling in API). 
- Change metabase dashboard to control for airbyte version
- We should remove APIs if we are removing the buttons

**Comment by mfsiega-airbyte** [comment]
Refining notes: check with @davinchia who might have context.

**Comment by davinchia** [comment]
Looking at email when I saw the tag: these were initially put in place for easy 1-click download for OSS users that aren't technical enough/don't have access to the underlying instance. I think it's fine to get rid of them + clean up the apis. Easy to bring them back if not!

**Comment by davinchia** [comment]
@marcosmarxm to sanity check, does TCS use the server logs as a debugging mechanism? If not, let's give removing a shot.

**Comment by davinchia** [comment]
Separate thought: might be interesting to explore what a similar mechanism looks like for Enterprise.

**Comment by marcosmarxm** [comment]
@davinchia already discussed with @josephkmh we can remove the buttons. The server logs and scheduler the UI download aren't helpful today.
