### ISSUE TITLE
Source Apify Dataset: version 1.0.0 break `Dataset` stream

### ISSUE THREAD

**Issue by hoangnm** [airbytehq/airbyte#30427]
### Connector Name

apify-dataset 

### Connector Version

1.0.0

### What step the error happened?

During the sync

### Revelant information

After syncing, the main data from the dataset is not available in the item_collection stream. It has only 4 fields: `#debug`, `#error`, `pageTitle`, `url`.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @hoangnm we identified the bug and we're working to fix it. Right now the workaround is rollback to previous version.

**Comment by eniayejudaniel** [comment]
Hello Everyone, 

I want to pick up this issue and resolve it. @hoangnm Could you specify your destination?

**Comment by hoangnm** [comment]
I tried to use S3 for a destination.

**Comment by topefolorunso** [comment]
This has been fixed here https://github.com/airbytehq/airbyte/pull/30428 @justinbchau

**Comment by marcosmarxm** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/30428
