### ISSUE TITLE
[source-mysql] Failed connection from MariaDB to Snowflake

### ISSUE THREAD

**Issue by asterios-pantousas** [airbytehq/airbyte#30430]
### Connector Name

source-mysql

### Connector Version

3.0.3

### What step the error happened?

None

### Revelant information

Hello Team,

While attempting to synchronize a large table (approximately 1.5 million rows) with Snowflake, we encountered an error: `java.io.IOException: HTTP/1.1 header parser received no bytes`. Although the data was transferred to Snowflake, the entire sync process was unsuccessful.

### Contribute

- [ ] Yes, I want to contribute

**Comment by asterios-pantousas** [comment]
[a0117286_6815_4c3a_8575_98b3b5ac8274_job_5440_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/12608070/a0117286_6815_4c3a_8575_98b3b5ac8274_job_5440_attempt_1_txt.txt)

**Comment by asterios-pantousas** [comment]
Further information: We're still facing persistent issues transferring data from Mysql source to Snowflake. The size of the connection state prevents us from copying and pasting it, hindering our ability to fetch data incrementally.

**Comment by evantahler** [comment]
Since this issue was written, we've dramatically revamped the connector.  Please try your sync again with the latest connectors and platform!
