### ISSUE TITLE
Troubleshoot transient Timeout and Concurrency errors in BQ

### ISSUE THREAD

**Issue by tryangul** [airbytehq/airbyte#30448]
15% of attempts in test connections are failing

**Transient errors we are seeing**

BigQueryException: Job execution was cancelled: Job timed out after 1 min 0 sec
BigQueryException: Read timed out
Rare OOM
Rare null pointer — concurrent access rehash?

**Comment by sajarin** [comment]
hey @tryangul, I've got an OSS customer who's experiencing the `Job execution was cancelled: Job timed out after 1 min 0 sec` BigQuery exception when trying to sync about 500gb of data from Postgres to BigQuery (both are at the latest version at the time of the comment). 

Is there any more information about these issues or what you might have learned from troubleshooting them? Seems like the customer's syncs always end up timing out and crashing during subsequent retries.
