### ISSUE TITLE
Allow users to opt-out of Destinations V2 Typing and Deduping

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#30454]
~~We will not work on this until we first improve the performance of Typing and Deduping (T&D), e.g. https://github.com/airbytehq/airbyte/issues/30418 and https://github.com/airbytehq/airbyte/issues/28380.~~ We believe that the majority of Airbyte users do want typed final tables, and the features we are building against them (better error handling, sync metadata, etc).  We are also not yet ready to commit to the format/schema of the raw tables as a interface that customers can rely on.   More detail in [Slack](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1694729010987059?thread_ts=1694636555.635669&cid=C03C4AVJWG4).

When we do bring back the option to skip T&D, it will be a spec/config option set on the destination connector, not a per-sync option provided by the platform.  We endeavor to remove the concept of 'normalization' from Airbyte entirely.  We should note that this use case is "advanced" and "unstable".  We can comment that the format of `_airbyte_data` column JSON is _likely_ stable, but users should not rely on any other columns at this time. 

The steps are:
* add new config option (behind advanced section)
* Default is to use  real T&D
* use NoOpTypeerDeduper if the option is selected
* don't forget testing
* don't forget connector docs

**Comment by andnig** [comment]
Great feature, would love to see this.
For our use case, relying on typed and deduped tables is too error prone. Having the old "raw JSON" way was nice, as we could rely on data being inserted as string blob, no matter what crazy things our API partners did. And they did a lot of them.
During upgrading to V2 Destinations we had several connectors which did not produce final table data, as the schema changed quite significantly from when we created them. However this was never an issue with the raw JSON option, as we simply could react accordingly downstream.
(I'm aware that this is not an ideal situation and that such significant API model changes should not be a daily thing - unfortunately in our business they are)

**Comment by evantahler** [comment]
This would also solve a problem where the T&D query is too large for streams that have > 1000 columns:

```
  "internalMessage" : "com.google.cloud.bigquery.BigQueryException: The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.",
```

**Comment by BFreeNashville** [comment]
This feature would be a huge win for me and my org! I'll echo all the reasons @andnig mentioned. I completely understand it as an "advanced" feature. It'll greatly speed up long-running syncs and put the control back in the data engineer's hands to react when necessary - for Stripe we recently had to work off-label and backfill some tables in the Airbyte T&D data model in multiple places due to the data being available and apparent in the raw tables, but unavailable in the typed final tables. If without issues, we end up re-modeling the data anyhow. It'd cut out a lot of bloat for us to be able to go straight from raw. ➕ 1 on this!

**Comment by evantahler** [comment]
Grooming:  Note that we still want the v1->v2 migration to happen even if you are using the `NoOpT&D`

**Comment by evantahler** [comment]
A relevant slack thread to this [topic](https://airbytehq-team.slack.com/archives/C02U6CXJQFN/p1697753907397609)
