### ISSUE TITLE
[Jira] Unable to get data from Jira stream "Sprint issues" and replicate it in Redshift

### ISSUE THREAD

**Issue by MahakUrooj656** [airbytehq/airbyte#30464]
### Connector Name

source-jira

### Connector Version

0.2.21

### What step the error happened?

None

### Revelant information

Concern: I've all the admin rights of my jira, but still i am unable to get the data, this is blocker for me as i'm working on usecase for our project.

Steps:
3. Created connection with only 1 stream selected i.e. sprint issues
4. Ran the sync which is successful
5. No data is emitted from source, therefore nothing is dumped in the destination. I've the organization admin rights but still i am unable to fetch any data from it.

Airbyte Version: 0.40.6

COnnection Details
<img width="1680" alt="Screenshot 2023-09-15 at 12 32 42 PM" src="https://github.com/airbytehq/airbyte/assets/104346569/a36ee5ee-191c-46ec-85e6-9bded8cde9ff">

Jira permission:
![image](https://github.com/airbytehq/airbyte/assets/104346569/dc250071-4d2b-42f1-b6c5-cd73dc0ab262)

Logs file
[logs-18182.txt](https://github.com/airbytehq/airbyte/files/12617161/logs-18182.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by MahakUrooj656** [comment]
<img width="1680" alt="image" src="https://github.com/airbytehq/airbyte/assets/104346569/73678d55-87c7-4ee1-ae5b-f26bc9516849">

**Comment by MahakUrooj656** [comment]
I'm observing the same issue with stream issue. even though i am able to get the data if i directly hit the jira api

**Comment by MahakUrooj656** [comment]
@marcosmarxm Hi is there any update around this issue?

**Comment by MahakUrooj656** [comment]
I've not tried it on the latest version but this issue is persistent even when i was using 0.35.0, this issue used to come too @darynaishchenko

**Comment by darynaishchenko** [comment]
> i am able to get the data if i directly hit the jira api

@MahakUrooj656 can you share your request via jira api?

**Comment by MahakUrooj656** [comment]
<img width="1680" alt="Screenshot 2023-09-20 at 4 03 44 PM" src="https://github.com/airbytehq/airbyte/assets/104346569/4ffffb8a-5fee-4971-9bb4-b291a81f15d0">
Here's the request I'm sending, we can observe that i am getting response for the request

**Comment by MahakUrooj656** [comment]
I'm using Basic Authentication, 
Here's the image for headers I'm using
<img width="1011" alt="Screenshot 2023-09-20 at 4 08 13 PM" src="https://github.com/airbytehq/airbyte/assets/104346569/bdc8a270-822c-4786-841b-2a0cded75242">

**Comment by darynaishchenko** [comment]
@MahakUrooj656, stream sprint issues uses another endpoint https://developer.atlassian.com/cloud/jira/software/rest/api-group-sprint/#api-rest-agile-1-0-sprint-sprintid-issue-get, if you want to sync using endpoint that you provide you need to sync stream Issues (not Sprint Issues)

**Comment by MahakUrooj656** [comment]
the issue is reproducible for both streams 
issues
sprint issues

Here's a screenshot for api end point i used for sprint issues, these end points are the one's that airbyte documentation refers to.
@darynaishchenko 
<img width="1011" alt="Screenshot 2023-09-20 at 4 20 38 PM" src="https://github.com/airbytehq/airbyte/assets/104346569/ec343bd7-2368-498c-b883-138ef9931e5d">

**Comment by darynaishchenko** [comment]
ok, I got it, do you use start date in your connector set up?

**Comment by darynaishchenko** [comment]
@MahakUrooj656 any updates?

**Comment by MahakUrooj656** [comment]
<img width="420" alt="Screenshot 2023-09-22 at 10 05 38 AM" src="https://github.com/airbytehq/airbyte/assets/104346569/943cbb5f-4d17-43ba-90ae-fb5e55c4ae38">
@darynaishchenko 
Here's the connector setup that i am using, I have not used start date

**Comment by darynaishchenko** [comment]
@MahakUrooj656  Can you please [update](https://docs.airbyte.com/integrations/custom-connectors/#upgrading-a-connector) to the latest version of the connector (0.7.1), ran a sync and share the logs? 
Also you can get your data via postman using actual request that connector performs.(Just to be sure that this request is working for you)
`https://yourdomain.atlassian.net/rest/api/3/search?maxResults=50&fields=*all&jql=project in (projectId)`

**Comment by MahakUrooj656** [comment]
@darynaishchenko 
I am trying with latest version of Jira connector, will get back to you in a while

**Comment by darynaishchenko** [comment]
@MahakUrooj656 Hi, any updates?

**Comment by MahakUrooj656** [comment]
Hi @darynaishchenko ,  i updated the connector version to latest, and it worked fine for me,
Thank you for helping out!
