### ISSUE TITLE
Apify dataset stream schema is not accurate

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#30478]
### Connector Name

source-apify-dataset

### Connector Version

1.0.0

### What step the error happened?

During the sync

### Revelant information

The schema of the dataset is static and thus does not include relevant fields from the dataset.

As it only specifies url and pageTitle here: https://github.com/airbytehq/airbyte/blob/646ccdf22dcfe8dabb753991724f32b56594dd76/airbyte-integrations/connectors/source-apify-dataset/source_apify_dataset/schemas/item_collection.json#L7

all other fields are dropped during the sync.

### Contribute

- [ ] Yes, I want to contribute

**Comment by natehouk** [comment]
@flash1293 - thank you for reporting this issue which we are encountering. Looking forward to having this integration tested and fixed.

**Comment by flash1293** [comment]
Fixed by https://github.com/airbytehq/airbyte/pull/31333
