### ISSUE TITLE
Add migration to backfill breaking change notification settings

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#30495]
We need to add something like this https://github.com/airbytehq/airbyte-platform-internal/blob/854c832d6452eb385cd3628be36018b01f42cf0f/oss/airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_50_5_003__NotificationSettingsSendOnFailureBackfill.java

**Comment by evantahler** [comment]
Grooming:
* Don't forget to bump `updated_at`!
* This is a JSON blob to update, that might be weird.
