### ISSUE TITLE
Improve sentry alerting outcomes

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#30502]
current state of the world 2023-10-23
* bigquery has a custom sentry fingerprint rule, which includes the exception message in the fingerprint
  * this results in sentry creating many issues for the same problem (e.g. `table_1 does not exist`, `table_2 does not exist`, etc)
  * see https://airbytehq.sentry.io/settings/projects/connector-incident-management/issue-grouping/
* snowflake _could_ do the same for SnowflakeSqlException, but is currently using the default grouping rule (i.e. all SnowflakeSqlExceptions get grouped together into a single sentry issue)

Ideally we want to get somewhere in the middle: one sentry issue per actual problem.

---

full context https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1694816133066939?thread_ts=1694810121.452749&cid=C03C4AVJWG4

Destinations, in many cases, don't submit exceptions that are useful for sentry. For example:
```
com.google.cloud.bigquery.BigQueryException: Already Exists: Table sandbox-392522:edgao_parallel_td_test.purchases_ab_soft_reset at [24:1]
        at com.google.cloud.bigquery.Job.reload(Job.java:419)
        at io.airbyte.integrations.destination.bigquery.typing_deduping.BigQueryDestinationHandler.execute(BigQueryDestinationHandler.java:70)
        at io.airbyte.integrations.base.destination.typing_deduping.DefaultTyperDeduper.lambda$typeAndDedupeTask$2(DefaultTyperDeduper.java:218)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is an exception that can be thrown during T+D. Unfortunately, we have sentry configured to ignore the exception message (`Already Exists: Table sandbox-392522:edgao_parallel_td_test.purchases_ab_soft_reset at [24:1]`), because it's not great at grouping together similar messages. Furthermore, all our exceptions have the same stacktrace, because we're just calling typeAndDedupeTask -> execute.

As a result, this exception is grouped together with completely unrelated errors, e.g. `com.google.cloud.bigquery.BigQueryException: Raw table has 0 rows missing a primary key at [14:3]`.

How can we force sentry to group these errors separately?
* manually define new exception classes for each message
* remove dynamic elements from the error message (e.g. replace the `sandbox-392522:edgao_parallel_td_test.purchases_ab_soft_reset` with `<table>`) + configure sentry to group based on exception message
     * this probably makes the UI error less useful though
* inject something based on the error message into the stacktrace before throwing it 🌶️ 
* reflectively define a new exception class at runtime based on the message 🌶️🌶️

**Comment by evantahler** [comment]
I think I like `manually define new exception classes for each message` best.  In this example, the new class would be `getStackTrace().getLines()[0].split(":")[1]`, so `Already Exists`

**Comment by edgao** [comment]
that sounds more like the `reflectively define a new exception class at runtime` option? unless I'm misunderstanding

by `manually define` I literally meant committing a file called `TableAlreadyExistsException.java`, and then something like `if (e.getMessage().startsWith("Already exists")) { throw new TableAlreadyExistsException()) }`. So we'd be constantly chasing these down, and if bigquery ever changes their exception message then we would need to fix our code to handle that new message

**Comment by evantahler** [comment]
I think maybe you did this @edgao https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1695415423509889

**Comment by edgao** [comment]
I only did this for bigquery. iirc snowflake throws runtimeexception in some cases, so need to change that before changing the sentry fingerprint config. (or need to disconfirm that.)

**Comment by evantahler** [comment]
See https://github.com/airbytehq/oncall/issues/3328 for sentry's current over-grouping

**Comment by edgao** [comment]
added a "current state of the world" section at the top of the issue description. afaict sentry doesn't support what I _really_ want, which is (approximately) regex parsing on the exception message... we might need to be doing this manually in-connector.

the sentry sdk also supports custom fingerprint values, but my understanding is that lives in platform, and I'd rather keep this logic contained within each connector

**Comment by edgao** [comment]
or... maybe we can do some matcher like this?
```
error.type:"com.google.cloud.bigquery.BigQueryException" error.message:"Not found: Table * was not found *"-> {{default}}, table-not-found
```

(I don't think there's any way to avoid the whackamole problem, but this maybe at least avoids us needing to release a bunch of new connector versions purely with exception message mangling)

**Comment by evantahler** [comment]
Grooming:
* Write up a doc with the options.  
   *  Destinations mangle the log stack trace string (e.g. remove data like table name, schema name)
   *  Platform mangles the stack traces before sending to sentry
   *  We mess with the sentry error grouper

**Comment by pedroslopez** [comment]
copying this over from DMs w/ evan:

> The reason why things are getting grouped is because it's the same exception being raised from the same code. If we can throw our own exceptions for issues we know about then that would be best and we can get the opportunity to do things like tagging them as config errors fi appropriate.
> 
> If this is too cumbersome or these exceptions really are hard to discern, then playing with the issue grouping configuration [here](https://airbytehq.sentry.io/settings/projects/connector-incident-management/issue-grouping/) to re-group things might be the way to go without adding a bunch of code just to deal with sentry /baking in these rules in the platform. This is like what ed suggested doing at the end there.

I will add one more thing relating to the `remove dynamic elements from the error message` option, which is if sentry has the message with params stripped it can group based on that (see [docs](https://develop.sentry.dev/sdk/event-payloads/message/)), but I'm not sure this would be easy to do at scale.

To recap, my preference would be:
1. If it's "easy" or relatively low-effort to discern different exceptions at the connector level and raise a different exception, we should do that. This way we can mark things as config error or give users better messages as needed. Maybe we only do this for the most important or common exceptions, again having the ability to give a user-facing message that enhances their experience, in addition to having better grouping.
2. If it's hard to do and would be more of a tedious string-matching thing for a bunch of exceptions, then using custom fingerprint rules on the sentry side sounds ok.

I would vote against doing something connector-specific on the platform side if possible.

**Comment by edgao** [comment]
nice. that lines up with what I'm thinking (and strong +1 on not doing connector stuff in platform). Currently leaning towards sentry rules since we'd probably just be doing string-matching everywhere (and if bigquery/snowflake ever change their error messages then our string-matching would break, and I don't want to have to release a new connector version just to fix it). Will tag you on the doc once it's done, probably late tomorrow

**Comment by edgao** [comment]
summarizing [doc](https://docs.google.com/document/d/1z_LfvTyJd_Sl7MpG1PhIgJdgMOzCcr2zYV_24Z970S8/edit):

* emit a trace message with externalMessage set to the original exception message, internalMessage set to a "deinterpolated" exception message, and no stacktrace
  * not including the stacktrace allows Sentry to work out of the box (i.e. matches on exception class + message), without additional configuration (i.e. we don't need to add any fingerprint rules)
* deinterpolating the error message means:
  * at sync start, gather a list of all dynamic strings that could show up in errors (table names, config options, etc.)
  * catch the exception, iterate through that list, replace the strings with a placeholder character
