### ISSUE TITLE
Sync failure with message='activity Heartbeat timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT

### ISSUE THREAD

**Issue by damiencamilleri** [airbytehq/airbyte#30559]
### Topic

Sync failure with message='activity Heartbeat timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT

### Revelant information

While syncing from MSSQL to Redshift, get error message
Sync failure with message='activity Heartbeat timeout', timeoutType=TIMEOUT_TYPE_HEARTBEAT

Can I adjust any setting for this? What does it mean?

**Comment by vamsikurre** [comment]
Any update here, I was also facing same issue

I set `destination-timeout.failSync` to false as mentioned in the below doc  
https://docs.airbyte.com/understanding-airbyte/heartbeats#configuration-1 

then the job successfully loaded the data and no failures in the log but job was in failure state
![Uploading image.png…]()

**Comment by marcosmarxm** [comment]
Closing the issue as it lack logs to further debugging. @vamsikurre please open a new issue describing your env and share the complete sync log.

**Comment by bedwards95** [comment]
I am facing an identical issue @vamsikurre using Airbyte version 0.50.3. Did you find a resolution?

**Comment by vamsikurre** [comment]
Try setting heartbeat.failSync in flags.yml file to false, That was changed to be default as false in v0.50.49

**Comment by amirhosseinTohidi** [comment]
I have the same error. Have you found a solution yet?

**Comment by marcosmarxm** [comment]
@amirhosseinTohidi please report a new issue. Make sure to use latest version of the platform.

**Comment by amirhosseinTohidi** [comment]
@marcosmarxm  Thank you, my problem two days ago was solved when I used version 1.4.0.
