### ISSUE TITLE
Connector Salesforce: Include ContentDocumentLink saleforce object in sync

### ISSUE THREAD

**Issue by alexopenline** [airbytehq/airbyte#30565]
### What area the feature impact?

Connectors

### Revelant Information

In salesforce link between document / content and object against which the note or document was created is kept in [ContentDocumentLink](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_contentdocumentlink.htm)

In Saleforce connector it looks that **ContentDocumentLink** is excluded.

`# The following objects have certain WHERE clause restrictions so we exclude them.
QUERY_RESTRICTED_SALESFORCE_OBJECTS = [
    "Announcement",
    "AppTabMember",
    "CollaborationGroupRecord",
    "ColorDefinition",
    "ContentDocumentLink",
    ...
    ...`
    
Will it be possible to include and sync **ContentDocumentLink**

**Comment by maxi297** [comment]
Hey @alexopenline ! Have you tried [version 2.2.1](https://github.com/airbytehq/airbyte/pull/33342) and higher? This is now be supported
