### ISSUE TITLE
Error Running DBT (Dbt Transformation Failed)

### ISSUE THREAD

**Issue by felipemarques-rec** [airbytehq/airbyte#30610]
### Topic

error running dbt

### Revelant information

Description:
I'm encountering an issue while attempting to use dbt 1.0 with Airbyte (latest version) for data transformation.

Steps to Reproduce the Error:

Clone the repository using the following command: git clone <repository URL>.
Execute the command to start dbt: dbt run.
The error occurs, indicating that profile.yaml cannot be found.

Error Log Output:
![image](https://github.com/airbytehq/airbyte/assets/70415183/61a44893-ae52-4355-a929-1c2a0d936854)
![image](https://github.com/airbytehq/airbyte/assets/70415183/8cbb6574-d1cc-40bc-a17c-3df00e66c456)
![image](https://github.com/airbytehq/airbyte/assets/70415183/62f07def-1a13-4e10-bbbe-db13f0a3efeb)

DBT Logs:

============================== 2023-09-19 14:08:48.480139 | 523cf3e3-d733-433e-abc8-671ff6a6303e ==============================
14:08:48.480139 [info ] [MainThread]: Running with dbt=1.0.0
14:08:48.480600 [debug] [MainThread]: running dbt with arguments Namespace(record_timing_info=None, debug=None, log_format=None, write_json=None, use_colors=None, printer_width=None, warn_error=None, version_check=None, partial_parse=None, single_threaded=False, use_experimental_parser=None, static_parser=None, profiles_dir='/data/114194/4/normalize', send_anonymous_usage_stats=None, fail_fast=None, event_buffer_size=None, project_dir='/data/114194/4/normalize', profile=None, target=None, vars='{}', log_cache_events=False, config_dir=False, defer=None, state=None, cls=<class 'dbt.task.debug.DebugTask'>, which='debug', rpc_method=None)
14:08:48.480801 [debug] [MainThread]: Tracking: tracking
14:08:48.485183 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff57f8d83a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff57f8d8190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff57f8d8310>]}
14:08:48.486420 [debug] [MainThread]: Executing "git --help"
14:08:48.489971 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone             Clone a repository into a new directory\n   init              Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add               Add file contents to the index\n   mv                Move or rename a file, a directory, or a symlink\n   restore           Restore working tree files\n   rm                Remove files from the working tree and from the index\n   sparse-checkout   Initialize and modify the sparse-checkout\n\nexamine the history and state (see also: git help revisions)\n   bisect            Use binary search to find the commit that introduced a bug\n   diff              Show changes between commits, commit and working tree, etc\n   grep              Print lines matching a pattern\n   log               Show commit logs\n   show              Show various types of objects\n   status            Show the working tree status\n\ngrow, mark and tweak your common history\n   branch            List, create, or delete branches\n   commit            Record changes to the repository\n   merge             Join two or more development histories together\n   rebase            Reapply commits on top of another base tip\n   reset             Reset current HEAD to the specified state\n   switch            Switch branches\n   tag               Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch             Download objects and refs from another repository\n   pull              Fetch from and integrate with another repository or a local branch\n   push              Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""

Environment:
Operating System: CentOS
dbt Version: 1.0
Airbyte Version: Latest Version
Other relevant environment details.

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated the custom dbt transformation feature](https://github.com/airbytehq/airbyte/discussions/34860).
