### ISSUE TITLE
Decouple AvailabilityStrategy from Stream

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#30616]
## What

edit: 
The stream is also used for reading the first record...
This is also true for the default implementation
----

The `AvailabilityStrategy` interface is coupled with the `Stream` interface, which makes it difficult to integrate with the new stream interface introduced as part of the concurrent CDK.

There are two reasons why `AvailabilityStrategy.check_availability` has a stream parameter:
1. The stream name is used for logging purposes
2. The `HttpAvailabilityStrategy` uses the stream's `parse_response_error_message` method to extract an error message from a response.

Solution one:
Since the stream's lifecycle is the same as the `AvailabilityStrategy`, we can remove the argument from the interface by moving it to the `HttpAvailabilityStrategy`'s `__init__` method without any loss in functionality. 

```
    def __init__(self, stream_name: str, response_parser: ResponseParser):
        ...
```

Note: we could do the same with `Source` and remove it from the `check_availability` interface

Solution two:
We can completely remove the dependency between `AvailabilityStrategy` and `Stream` by extracting the  `parse_response_error_message` out of `HttpStream` into a `ResponseParser` object, which would also be passed to the `HttpAvailabilityStrategy` `__init__` method.

```
    def __init__(self, stream_name: str, response_parser: ResponseParser):
        ...
```

**Comment by erohmensing** [comment]
> There are two reasons why AvailabilityStrategy.check_availability has a stream parameter:

> The stream name is used for logging purposes
> The HttpAvailabilityStrategy uses the stream's parse_response_error_message method to extract an error message from a response.

What about the default behavior, which calls `stream_slice = get_first_stream_slice(stream)` and `get_first_record_for_slice(stream, stream_slice)`? 

I'll admit I think I'm a bit lost as to the suggestion, but as long as
- there is a good default behavior defined for the HttpAvailabilityStrategy that is per-stream
- the functionality is still overridable per stream 

Then whatever solution is good to me!

**Comment by girarda** [comment]
closing in favor of https://github.com/airbytehq/airbyte/issues/30951, which has a smaller scope
