### ISSUE TITLE
CAT: Tests can set a deployment_mode

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#30627]
## What

We have CAT tests that assert the result of spec. Now that we are removing strict-encrypt connectors via environment-sensitive connectors, CAT needs to be updated to be able to test that the cloud spec is output as intended.

We should add a new `deployment_mode` option to the spec test so we can assert the contents depending on the deployment mode.

The two options are OSS and CLOUD.  If users don't provide a deployment_mode, the ENV is undefined in tests

## Questions

* Should we support deployment_mode on other tests (other than spec) as well? (YES)
* Should we run SPEC tests with both deployment modes, in all cases? (NO)
* In some future story, we'll add QA checks that assert that any cloud connector really is testing both deployment_modes

**Comment by evantahler** [comment]
Grooming:
* maybe for SPEC, we should test both deployemnt_modes of deployment_mode is null.  If OSS and CLOUD have different specs, and you don't have other tests for both deployment modes... fail
*
