### ISSUE TITLE
Proposal: Standarize Formating into `airbyte-ci

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#30635]
https://docs.google.com/document/d/1X8KVmomXT5EwiNuwyvO5oQGMTMrZbt1nyBxWsSpDEo8/edit

**Comment by evantahler** [comment]
Added as a [roadmap item ](https://docs.google.com/spreadsheets/d/1K4TIv0Oc4_jYkLkmIAE1im9hA3_3VFryXuT2Ts5vYkM/edit#gid=0)- "Fix connector formatting"
