### ISSUE TITLE
Java cdk support for airbyte-ci

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#30637]
* ✅ build with local CDK (we do this for python)
    *  There's a `-snapshot`(gradle option) which can be used to pull from local registry??
* ✅ test with local CDK (we do this for python)
    *  There's a `-snapshot`(gradle option) which can be used to pull from local registry??
* ❓ publish local CDK (we don't do this for python)
  * we might have [support already](https://github.com/airbytehq/airbyte/blob/15e0a8f34e978a0f3431f10018af2e4a393ab6d2/airbyte-ci/connectors/pipelines/pipelines/gradle.py#L140)

We need to talk with @aaronsteers to learn more about what is needed

**Comment by aaronsteers** [comment]
@bnchrch - Thanks for logging this. Can we add a publish operation for the CDK? That's the next big thing we need to tackle.

**Comment by aaronsteers** [comment]
There's a big difference between building connectors with the Python and Java CDK. If I understand correctly, building with local CDK requires injecting the CDK into the built virtual env. 

As we have it now, we're looking at using the live folder definition, so Gradle should build it automatically without an extra step. 

How do python connectors in CI know to use local CDK today, when run responsive to a commit and not invoked manually?

**Comment by bnchrch** [comment]
Hey @aaronsteers !

Thanks for replying.

Let me answer the off hand question first then jump into cdk support context.

> How do python connectors in CI know to use local CDK today, when run responsive to a commit and not invoked manually?

For reference for regular development of python connectors
1. the cdk is published as a standalone pypi package
2. the connector then references that like any other external dependency

If a Python CDK develop would like to build a connector, or test a connector with their local cdk changes they can run
```sh
airbyte-ci connectors --use-local-cdk --name=source-faker build
airbyte-ci connectors --use-local-cdk --name=source-faker test
```

The mechanism at place behind the scenes of `--use-local-cdk` is essentially
```sh
# from the connector folder
# after installing python dependencies
pip install --no-deps {path to local cdk}
```

**Now onto java cdk support**

As I understand it We have a deadline for releasing the java cdk early next week and it seems like theres some things to be done in the airbyte-ci to help out

Also Im not sure if I understood your last message but to me it read as
> For launch all java cdk connectors will reference the local cdk and their will be no external package repository on day 1

Is that fair?

In the absense of an answer to that question I just have a few generic ones
    1. Whats on the other side of the deadline? and if its a soft deadline or a hard one?
    2. Do java connectors reference a specific java cdk version by default? and if so where is the package repository?
    3. How often are we expecting to publish new packages? 
    4. What is the best gradle mechanism to point to a local dependency instead of a remote? Is this a flag we cna specify or do we need to edit a gradle file?

**Comment by aaronsteers** [comment]
Super helpful - thanks!

For the Python side, I think that makes sense. But does that imply that co-developing a python connector and the CDK will always fail when CI is responsive to a commit in GitHub actions?

**Comment by bnchrch** [comment]
Notes from call with AJ

In the near term (1+ weeks)
- @aaronsteers  will update gradle to implement a local cdk flag/env var that toggles if the connector uses the local java cdk
- @bnchrch will update airbyte-ci to implement `--use-local-cdk` for java connectors by
    - Including the local cdk directory in the build container
    - triggering gradle to build with the local gradle path

This will leave java cdk developers with a manual step to ensure they publish any cdk changes they make while developing a java connector

If time allows @bnchrch will move the publish command for the java cdk into an airbyte ci command, accessable by github actions

**Comment by evantahler** [comment]
Done!
