### ISSUE TITLE
Jira Issue History

### ISSUE THREAD

**Issue by yeedster** [airbytehq/airbyte#3064]
## Tell us about the problem you're trying to solve
Trying to find how to track jira issue history through the tables created by airbytes.  There doesn't seem to be any data for issue history currently.

## Describe the solution you’d like
Have the issue history table be included in the json data or have a seperate table for event/issue history.

## Describe the alternative you’ve considered or used
No clear alternative right now

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368227597748) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@yeedster would this be the issue changelogs? There's a few issue "history" endpoints like comments, resolutions, changelogs, etc.. 

could you say more about which of these you'd be looking for? 

API reference https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-changelog-get

**Comment by flexe-jwdalton** [comment]
I would be interested in the data from the issue changelogs endpoint. For reporting on Jira, we need to be able to report on trends in the issues (ticket counts per day per project per status, etc.).

**Comment by tigitz** [comment]
Just to bring awareness to this issue, my company had to switch to stitchdata.com to extract these https://www.stitchdata.com/docs/integrations/saas/jira#changelogs

It's mandatory to retrieve these changelogs if we want to compute the time between different ticket status (from ToDo to Done for example) and the history of story points modifications.

**Comment by JCWahoo** [comment]
Changelogs are available in the issue stream, I can share a model that builds the start/end time for each status

**Comment by grubberr** [comment]
Can you please try to synchronize `issue` stream with "Expand Issue Changelog" turned on?

**Comment by grubberr** [comment]
closed because of https://github.com/airbytehq/airbyte/pull/20128
