### ISSUE TITLE
Track the actual schema change detected

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#30668]
When we alert users of a schema change, we only tell them it occurred, not the details of what changed.

We should say what the changes were. Some additional details are listed here: https://docs.google.com/document/d/1Le7LZRIjlEJQWDsuGaz6J08czbzz9Bc7cgSv4G7njhM/edit#heading=h.jp04r0p05jfz

cc @mfsiega-airbyte

**Comment by pmossman** [comment]
@malikdiarra is this something you had in the works already? Should we assign to you?

**Comment by nataliekwong** [comment]
I tried to turn on the feature flag over the weekend for our internal workspace, and I believe the email was just not sent (I did a schema change but didn't get an email). Just sharing in case it's helpful for testing @malikdiarra

**Comment by nataliekwong** [comment]
I believe this is @flutra-osmani 's hands now!

**Comment by flutra-osmani** [comment]
Yes, we tried some initial end-to-end tests but haven't yet found the reason why notifications are being emailed.

**Comment by pmossman** [comment]
Refining notes:
- Not sure where this currently stands, last thing was that Slack notification formatting needed some work. Will check with @malikdiarra if this is still being iterated on
- We are sending empty 'schema changes detected' notifications, seems like a bug that we just need to fix

Extension of this: bringing these notifications into the UI directly

**Comment by malikdiarra** [comment]
Regarding the message format, the PR should be merged this week. The fix for the empty notification will be released right after.

**Comment by malikdiarra** [comment]
The change introduced a bug where users [could no longer deactivate schema propagation notifications on a connection](https://github.com/airbytehq/airbyte-platform-internal/issues/10748). This is fixed now, progressive roll-out starts today.
