### ISSUE TITLE
Source Stripe: updated field is not filled properly

### ISSUE THREAD

**Issue by kev-datams** [airbytehq/airbyte#30677]
### Connector Name

source-stripe

### Connector Version

4.1.1

### What step the error happened?

During the sync

### Revelant information

Hello,

While running the sync, independently from sync mode, the output `updated` field has always the same value as `created` field, instead of taking the last event date value coming from Stripe events.

It looks like the v4.0.0 does not work as expected regarding the the output `updated` field.
This is very problematic for payments that last more than few seconds (up to several days !), where we have a gap between real payment date (expected in `updated` field) and the first try (in `created` field).

It is quite easy to replicate the issue:
1. Create a payment on Stripe, that will be initiated first, then validated (=> update event)
2. Enable sync for Charges stream (+ Events stream if you want)
3. Check for values in target output
=> you will see that `created` is equal to `updated`

Thanks for your help :) 

### Contribute

- [ ] Yes, I want to contribute

**Comment by kev-datams** [comment]
Can somebody add the tag `connectors/source/stripe` please ?

**Comment by nataliekwong** [comment]
cc @katmarkham

**Comment by davydov-d** [comment]
@kev-datams hello, and thank you for reporting this issue!
Indeed, value of the `updated` field is filled with the value of `created` field in two cases:
 - Full refresh sync
 - Initial incremental sync
The reason for this is Stripe does not provide the date of last update in the regular API and even more, some entities do not have any date-time fields at all. Despite this fact, we have to remain consistent and provide a starting point for the subsequent incremental updates which utilise different API - the Events API which provides us with the date/time of last update. Please check the values of the `updated` field after a subsequent incremental sync and let me know if it works for you. Thanks!

**Comment by kev-datams** [comment]
Hello @davydov-d, thank you for your answer :)

Do you mean I have to perform:
1. full refresh sync or initial incremental sync
2. subsequent incremental sync (even just after the first one)

and I should have `updated` field properly filled for ALL rows where at least 1 event occurred in the last 30 days ? (as event should be available in the `events` flow)

Complementary question: do we need to enable the `Event` stream to have this behavior or can we leave it disabled ?

Thanks for precision 🙏

**Comment by davydov-d** [comment]
> Hello @davydov-d, thank you for your answer :)
> 
> Do you mean I have to perform:
> 
> 1. full refresh sync or initial incremental sync
> 2. subsequent incremental sync (even just after the first one)
> 
> and I should have `updated` field properly filled for ALL rows where at least 1 event occurred in the last 30 days ? (as event should be available in the `events` flow)
> 
> Complementary question: do we need to enable the `Event` stream to have this behavior or can we leave it disabled ?
> 
> Thanks for precision 🙏

@kev-datams no, unfortunately that's not how it works. After running a subsequent sync, you'll get the correct "updated" values for the records that had an event occurring since last run.

The Events stream has nothing to do with it, you may leave it disabled

**Comment by kev-datams** [comment]
Hello @davydov-d,

I tried what you proposed without success: all rows have `created == updated` for all streams (eg: charges, customers, disputes)
So updates are not taken into account. NB: I can see updates events in the events stream output table.

Any idea to solve this issue ?
Thank for help !

**Comment by davydov-d** [comment]
@kev-datams what is the exact sync mode you are using?

**Comment by kev-datams** [comment]
@davydov-d, `Incremental with deduplication + history`
![Capture d’écran 2023-10-16 à 11 24 30](https://github.com/airbytehq/airbyte/assets/104839813/0b9d2707-2d4b-4b10-befb-4a23570f768a)

**Comment by kev-datams** [comment]
@davydov-d , if it can help, we are currently using the Airbyte v0.50.5
Does new versions implies changes on source/target connectors ?

**Comment by davydov-d** [comment]
@kev-datams no, Airbyte version should not affect the connector functionality. However, if I'm not mistaken, upgrading Airbyte also leads to upgrading versions of the connectors you are using. There are new versions of the Stripe connector which include bugfixes that could possibly affect you. Please try again after upgrading to the latest connector version - 4.4.0.
Also, please make sure records in the Events stream share the same IDs with records you expect to be updated in the customers/charges/disputes stream in case the problem persists.

**Comment by kev-datams** [comment]
@davydov-d thanks for your help, last version properly manages `updates` :)
