### ISSUE TITLE
Remove airbyteDocker and all java dockerfiles for connectors

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#30708]
## Problem
Its confusing that
1. we have dockerfiles
2. and airbyteDocker
3. but dont use them for building and testing any more
4. 

## Solution
Remove them.

[slack conversation](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1695417277750759)

**Comment by bnchrch** [comment]
Related PR: https://github.com/airbytehq/airbyte/pull/30743/files

**Comment by evantahler** [comment]
cc @postamar and @aaronsteers

**Comment by evantahler** [comment]
Grooming - there are still some Java connector Dockerfiles to delete...

**Comment by postamar** [comment]
IIRC these are required for the base-normalization build.

**Comment by evantahler** [comment]
cc @edgao maybe it's time to never build normalization images ever again... and just use the images we have?

**Comment by edgao** [comment]
> normalization

sgtm. with [this](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1697652897706699?thread_ts=1697583573.340729&cid=C03C4AVJWG4) plan (or something similar) we shouldn't need to build normalization ever again.
