### ISSUE TITLE
Custom DBT transformation fails for BigQuery (Destination)

### ISSUE THREAD

**Issue by Aamir185** [airbytehq/airbyte#30716]
### Connector Name

destination-bigquery

### Connector Version

2.0.9

### What step the error happened?

During the sync

## Brief Inital Steps
1. Set up airbyte locally on Windows (WSL 2)
2. Set up a source connection with Covid Data from Airbyte [Docs](https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-sql) - [Source ](https://storage.googleapis.com/covid19-open-data/v2/latest/epidemiology.csv)
3. Setup destination as Bigquery

**Note: The Normalization section is missing in Configure Connections page**

![image](https://github.com/airbytehq/airbyte/assets/50237393/480f9b1c-e435-4f84-a35b-3b2406d8df91)

### First run
1. Run the sync as is (without custom transformation)
> This runs successfully and replicates the tables in bigquery
![image](https://github.com/airbytehq/airbyte/assets/50237393/f008f7f5-0fab-40a0-b7b5-1c9d4ad66e4a)

2. Apply basic dbt normalization
> This cause the sync to fail with the error message saying 'Something went wrong with DBT transformation', with no info on what. Inspecting the cmd logs indicate a server error occuring as soon as the dbt transformation starts and DefaultNormalizationRunner.java is invoked. It uses a string normalizationIntegrationType which is passed as NULL causing the error on Line 95 normalizationIntegrationType.toLower() (NullPointException)
![image](https://github.com/airbytehq/airbyte/assets/50237393/da4ea04b-44a6-479c-81a3-98a83b8fcd8f)
![image](https://github.com/airbytehq/airbyte/assets/50237393/db565b77-0721-4306-bd31-76a9539cda50)

> Transformation
![image](https://github.com/airbytehq/airbyte/assets/50237393/83889fc1-a60d-4eef-abf3-6008bede24a7)

> Git Repo for DBT Tranformation: https://github.com/Aamir185/dbt-postgres-custom.git

> Server log:
![image](https://github.com/airbytehq/airbyte/assets/50237393/00822a0b-7339-4d10-bc47-729d7e541d8f)

### Relevant log output

```shell
[failed_sync_log.txt](https://github.com/airbytehq/airbyte/files/12711117/3bc9391d_e86d_4659_b32e_45bf5619222c_logs_26_txt.txt)
```

### Contribute

- [X] Yes, I want to contribute

**Comment by davinchia** [comment]
Closing this in lieu of the linked issue.
