### ISSUE TITLE
[source-postgres] Include value of xmin as metadata in extracted data

### ISSUE THREAD

**Issue by craunas** [airbytehq/airbyte#30721]
### What area the feature impact?

Connectors

### Revelant Information

Hello!

Just started using the xmin method for our Postgres sources and it works great.

However, when deduplicating data it would be helpful to have some kind of value indicating the order of the updates/changes.

Im thinking the value of the xmin column could be used for that, assuming that value is incrementing.

If my assumption is correct then we'd like to be able to include the xmin value in the extracted data. Either as its own field or as metadata somehow.

Thanks!

**Comment by evantahler** [comment]
What destination are you syncing to?  You should have both emitted_at and loaded_at to help you order the data logically

**Comment by craunas** [comment]
@evantahler Im syncing to Azure Blob Storage. Does you answer mean that data is emitted in the same order they occured?

**Comment by evantahler** [comment]
> @evantahler Im syncing to Azure Blob Storage. Does you answer mean that data is emitted in the same order they occured?

Ah.  In datawarehouse/database destinations you gain 2 columns, literally `_airbyte_emitted_at` and `_airbyte_extracted_at`.  Yes, the data written to the files in your GCS destination are kept ordered they way they were emitted from the source (within the same stream).  Row 1 always was emitted before row 2.

**Comment by craunas** [comment]
> > @evantahler Im syncing to Azure Blob Storage. Does you answer mean that data is emitted in the same order they occured?
> 
> Ah. In datawarehouse/database destinations you gain 2 columns, literally `_airbyte_emitted_at` and `_airbyte_extracted_at`. Yes, the data written to the files in your GCS destination are kept ordered they way they were emitted from the source (within the same stream). Row 1 always was emitted before row 2.

Ok, thanks for the information! This should solve our problem then, closing this ticket.
