### ISSUE TITLE
low-code cdk: add support for DefaultSchemaNormalization

### ISSUE THREAD

**Issue by sh4sh** [airbytehq/airbyte#30737]
### What area the feature impact?

Low code CDK

### Revelant Information

The Python CDK supports schema transformations using [`TypeTransformer`](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/utils/transform.py), including `DefaultSchemaNormalization` which applies default typecasting across an entire schema. This feature is used to blanket enforce consistent datatypes on all fields in received records when datatypes are out of sync with the schema declared for a stream.

Can we add schema level transformations, and in particular `DefaultSchemaNormalization` to the low code framework?

blocking https://github.com/airbytehq/airbyte/pull/29287 and https://github.com/airbytehq/airbyte/pull/28981 (will be closed for now, but adding for reference)

`DefaultSchemaNormalization` is currently used in 16 certified connectors:
<details>

<summary>List of connectors using DefaultSchemaNormalization</summary>

### Certified connectors:
```
source-airtable
source-facebook-marketing
source-freshdesk
source-google-ads
source-hubspot
source-jira
source-linkedin-ads
source-mixpanel
source-pinterest
source-recharge
source-salesforce
source-amazon-seller-partner
source-stripe
source-tiktok-marketing
source-twilio
source-zendesk-support
```
### Community connectors:
```
source-appsflyer
source-close-com
source-freshsales
source-looker
source-pardot
source-paystack
source-surveycto
source-youtube-analytics
```
</details>

**Comment by girarda** [comment]
## Implementation details
- The transformer is defined at the stream level
- The transformation is applied from the [abstract source](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L345)

Open questions:
- should this be configurable as a transformation or as a stream option?
- is it enough to only allow `NoTransformation` and `DefaultSchemaNormalization`?

**Comment by maxi297** [comment]
Grooming notes:

> should this be configurable as a transformation or as a stream option?

Not a concern as we will only support `DefaultSchemaNormalization` for now

> is it enough to only allow NoTransformation and DefaultSchemaNormalization?

Yes. CustomSchemaNormalization is out of scope for this

> Is the order important? 

Yes and this is creating a weird UX. We were thinking about adding a `schema_normalization` field to the `RecordSelector` instead. We will wait a little bit to see if anyone has a better idea

**Comment by girarda** [comment]
additional notes:
- Manifest schema is defined in this file: `airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml`
