### ISSUE TITLE
Modernize Acceptance Test Docs and remove old tools

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#30767]
We should update https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/testing-connectors/connector-acceptance-tests-reference.md to stop talking about docker build and ./acceptance-test-docker.sh... and use airbyte-ci instead.  @gisripa  is building a connector the hard way as part of his onboarding, and this was rather confusing

---

We daggerized CAT and it can now be run inside `airbyte-ci`
It also can be run directly from its poetry package with: 
`poetry run pytest  -p connector_acceptance_test.plugin --acceptance-test-config=../../connectors/source-postgres`

But I believe we have stale docs and scripts that can make running CAT confusing.
E.G: we still have `acceptance-test-docker.sh` scripts.

Definition of done:
* The one or two good ways to run CAT are documented
* We delete the CAT dockerfile
* The `acceptance-test-docker.sh` scripts are gone

**Comment by gisripa** [comment]
[This](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/tutorials/adding-incremental-sync.md#run-the-incremental-tests) needs update too, along with the yaml structure.  the generated yaml has `incremental->tests->config_path` structure but the example in the link shows a different structure for `acceptance-test-config.yml`

**Comment by evantahler** [comment]
Grooming:
* Maybe remove the old acceptance-test-docker.sh entirely?  It's going to stop working when docker files are removed from the repo soon
*
