### ISSUE TITLE
🐛 Large log message in java connectors can lead to loss of records

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#30781]
### Topic
Unsafe logging can lead to loss of AirbyteMessages in java connectors

### Revelant information

This is an issue observed in source-postgres, but the issue is low level and shared among all java connectors.

A log message that is:
a. longer than 8KB
b. sent from a secondary thread.

May be written partially to stdout and in case another AirbyteMessage such as a `Record` is written at the same time, may cause both message interleaving.
In the case of source this may lead to a loss of records as stdout emits
`{"type":"LOG","log":{"level":"INFO","message":"partial log line … {"type":"RECORD","record":…}`
Because the two interleaved messages are written in a single line, the receiver of the message - platform orchestrator - cannot decode a valid json and the messages get omitted.
On source this will lead to a loss of record
On destination this may lead to a loss of a checkpoint ack for example.

See [repro code](https://github.com/airbytehq/airbyte/commit/4c758df35c188bea2b0e39f2ecc2fd7730500a5e)
Running sync with source postgres will cause a loss of records.

A real [connection](https://cloud.airbyte.com/workspaces/b79f07e0-0575-4ed5-93bb-6ef9c6396646/connections/ba7b1ada-7168-4ef6-9df6-bffb7e20aa46/job-history#4770161::0) in which we see the issue

**Comment by rodireich** [comment]
A few directions:
1. increase the log buffer size: the [log4j.encoder.byteBufferSize](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/util/Constants.html#ENCODER_BYTE_BUFFER_SIZE) log4j param seems to be related.
2. Truncate Log line to max 8K
3. Create a custom log4j appender for log lines which can write safely to std output
4. create a custom log4j appender that will send all log lines to main thread to ensure no race condition.

**Comment by sh4sh** [comment]
🤔 a user reported this issue with source-postgres:3.2.13 which includes the fix for this issue. Records are still printed in logs, and lines are well over 8K (also crashing the UI) despite upgrading the connector. Their platform version is v0.50.30.

Meanwhile https://github.com/airbytehq/airbyte/issues/31178 on v0.50.29 reports similar behaviour and was resolved by upgrading to source-postgres:3.1.13.

I'm stumped. Is there something in the platform version that matters here?
