### ISSUE TITLE
CDK: add flag to turn on debugging mode

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3078]
## Tell us about the problem you're trying to solve
It would be nice to have a flag `--debug` which outputs a bunch of extra logs like: 

* what the stream slices are
* which URL endpoints/params/etc.. are being hit
* etc. basically various information that can give me visibility about what's happening in the connector

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368227754448) by [Unito](https://www.unito.io)

**Comment by girarda** [comment]
few additional things that would be useful to expose for troubleshooting:
* raw response (need to make sure the secrets are scrubbed)
* fully expanded config (for low-code)
* cursor value
