### ISSUE TITLE
Facebook Marketing docs: improve detail about required permissions

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#30849]
### Page URL

docs.airbyte.com/integrations/sources/facebook-marketing

### Description

A customer was failing the setup process because the account they used an account with insufficient permission to oauth into the FB API. Specifically, the customer didn't know: 

1. all the permissions that the authenticated oauth account needed to have
2. how to grant those permissions if an account doesn't already have them

more detail from the user
> can we add permissions to the prereq needs more detail as to where to find this information in Facebook. I went to [Competitor docs](https://fivetran.com/docs/applications/facebook-ads/setup-guide) :grimacing: to help one of our customers with their permissions needs. I really like how they link where to find the information within Facebook too

**Comment by nataliekwong** [comment]
@ChristoGrab do you know if we require all the exact same permissions as competitor? If so.. I can just create a PR for this.

**Comment by ChristoGrab** [comment]
@nataliekwong Thanks for reminding me of this, and sorry! Got stuck in my backlog and I forgot to come back around to it.
