### ISSUE TITLE
[source-dynamodb] expression attribute names don't handle colons correctly

### ISSUE THREAD

**Issue by apalmer1377** [airbytehq/airbyte#30842]
### Connector Name

source-dynamodb

### Connector Version

0.1.2

### What step the error happened?

During the sync

### Revelant information

When columns in DynamoDB have special characters in them, the DynamoDB source allows you to define expression attribute names for them, so Airbyte can still refer to those columns in the load. However, the DynamoDB connector only removes periods and dashes when creating the expression attribute names, so any column with a colon in it (like the `aws:rep:deleting`, `aws:rep:updatetime`, and `aws:rep:updateregion` columns AWS adds automatically) do not get processed correctly, which leads to a sync error.

### Relevant log output

```shell
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: ExpressionAttributeNames contains invalid key: Syntax error; key: \"#dyndb_aws:rep:updatetime\" (Service: DynamoDb, Status Code: 400
```

### Contribute

- [X] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
