### ISSUE TITLE
:sparkles: Source Timely : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30876]
https://docs.airbyte.com/integrations/sources/timely

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by topefolorunso** [comment]
I will work on this next @justinbchau. Please assign to me

**Comment by justinbchau** [comment]
Hi @topefolorunso , it looks like you have been assigned an issue already. To keep the Hackathon fair and give others a chance, I'm gonna keep this open until a PR is submitted for the issue you already have! 

If you submit a PR and this issue is still free, please ping me here. Thanks!

**Comment by topefolorunso** [comment]
I have submitted a PR already for it @justinbchau

**Comment by Utkarshn10** [comment]
Hey @justinbchau, if this issue is not assigned to anyone then I would like to pick this up. Thanks and have a great day !
