### ISSUE TITLE
 :sparkles: Source Unleash : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30880]
https://docs.airbyte.com/integrations/sources/unleash

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by topefolorunso** [comment]
Already in low code https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-unleash/source_unleash/unleash.yaml @bmcgilli

**Comment by marcosmarxm** [comment]
Thanks for bringing the info @topefolorunso
