### ISSUE TITLE
:sparkles: Source Webflow : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30884]
https://docs.airbyte.com/integrations/sources/webflow

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by Arjunhg** [comment]
Good evening @bmcgilli ,
I want to work on this issue. Can you please assign it to me?

**Comment by justinbchau** [comment]
You got it! @Arjunhg

**Comment by Arjunhg** [comment]
> You got it! @Arjunhg 

Thank you.

**Comment by marcosmarxm** [comment]
Collections are mutable and dynamic. Not possible to migrate to low-code
