### ISSUE TITLE
:sparkles: Source Zendesk Sell : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30887]
https://docs.airbyte.com/integrations/sources/zendesk-sell

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by aazam-gh** [comment]
I would like to work on this one instead of Okta
