### ISSUE TITLE
:sparkles: Source Zenefits : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30889]
https://docs.airbyte.com/integrations/sources/zenefits

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by masterismail** [comment]
Hi ! can i get credentials for Zenefits?

**Comment by justinbchau** [comment]
Please message @marcosmarxm on Slack for this!

**Comment by masterismail** [comment]
okay!

**Comment by marcosmarxm** [comment]
Send credentials!

**Comment by pabloescoder** [comment]
I've made a PR for my previous issue, please assign this one to me.
