### ISSUE TITLE
:sparkles: Source Smartsheets : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30899]
https://docs.airbyte.com/integrations/sources/smartsheets

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by parthiv11** [comment]
this source requires dynamic schema to be generated, as of now i don't think that low code is capable to work with dynamic schema generation.


Is there any other way or technique which can help then please let me know about it because i would love to work on this.

**Comment by farheenfathimaa** [comment]
I would like to give this a shot

**Comment by justinbchau** [comment]
I don't believe there is any other way to make this work so I will go ahead and close this issue @parthiv11
