### ISSUE TITLE
Source name not updating

### ISSUE THREAD

**Issue by ifokeev** [airbytehq/airbyte#3089]
## Expected Behavior
Expecting that source name is updated

## Current Behavior
It's the same after update, looks like regression, because worked in previous versions

## Logs

<img width="1755" alt="Screen Shot 2021-04-27 at 21 38 33" src="https://user-images.githubusercontent.com/2017148/116294690-edbb1980-a7a0-11eb-88d6-d7cbc42b57a1.png">

## Steps to Reproduce
1. Go to added source
2. Go to settings
3. update source name

## Severity of the bug for you
Medium

## Airbyte Version
0.19.0-alpha

**Comment by marcosmarxm** [comment]
Hi @ifokeev thanks for reporting this, currently there already an open issue #2090 related to this.

**Comment by marcosmarxm** [comment]
@ifokeev I'll close this issue as duplicated but will raise it to the team because is not the first issue open related to this.
