### ISSUE TITLE
:sparkles: Source Open Exchange Rates : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30906]
https://docs.airbyte.com/integrations/sources/open-exchange-rates

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by btkcodedev** [comment]
@bmcgilli Hi there 😃
One of the hackathon participant here 👋 
Please assign this issue to me

**Comment by justinbchau** [comment]
All yours @btkcodedev ☺️
