### ISSUE TITLE
:sparkles: Source DynamoDB : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30914]
https://docs.airbyte.com/integrations/sources/dynamodb

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by sivankumar86** [comment]
is it possible to add stream listener for incremental instead of SCAN API ?
https://medium.com/pageup-tech/dynamodb-incremental-backups-bb9e0c3db8f2

**Comment by marcosmarxm** [comment]
It isn't possible to migrate dynamodb to lowcode because its a database and uses Java today.
