### ISSUE TITLE
:sparkles: Source Amazon SQS : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30912]
https://docs.airbyte.com/integrations/sources/amazon-sqs

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by aweash** [comment]
can i work on this?

**Comment by pranjaljn97** [comment]
Can I work on this if it's still up for grab?

**Comment by justinbchau** [comment]
@aweash was first so I will assign to them!
