### ISSUE TITLE
:sparkles: Source BambooHR : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30913]
https://docs.airbyte.com/integrations/sources/bamboo-hr

Rules for the Connectors Hackathon
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by aazam-gh** [comment]
I would like to work on this issue :)

**Comment by marcosmarxm** [comment]
BambooHR is not possible to migrate to low-code. As already said and discussed in previous attempt [here](https://github.com/airbytehq/airbyte/pull/29123#pullrequestreview-1578638346)

I'm closing this.
