### ISSUE TITLE
Google Analytics connector is failing

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3098]
## Expected Behavior
CI with status success and no problem configuring GA connector.

## Current Behavior
Looks that Google Analytics connector CI is failing.
https://status-api.airbyte.io/tests/summary/source-googleanalytics-singer/

An user had problem trying to use the connector and link the status-api also.
see [convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1619514514278200)
(will try take more information related to user problem and update here)
![image](https://user-images.githubusercontent.com/5154322/116331910-1c3bf300-a7a7-11eb-8f69-a5fcf7b0e630.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368162951909) by [Unito](https://www.unito.io)

**Comment by ifokeev** [comment]
Same here, stopped to work after 0.2.0

**Comment by marcosmarxm** [comment]
@ifokeev can you post your log errors?

**Comment by ifokeev** [comment]
It is looping
<img width="937" alt="Screen Shot 2021-04-30 at 17 32 21" src="https://user-images.githubusercontent.com/2017148/116713642-a9688d00-a9dd-11eb-8ea8-a98ef72cf53c.png">


Same in the tests:
https://github.com/airbytehq/airbyte/issues/3098

**Comment by ifokeev** [comment]
I tried airbyte `0.22.0-alpha` with versions: `0.1.5, 0.2.0, 0.2.1, 0.2.2, 0.2.3`. Seems like there is no compatibility with `0.1.5` and other versions are broken (?)

**Comment by sherifnada** [comment]
@ifokeev would you be able to post the entire log for a failing job?

**Comment by ifokeev** [comment]
@sherifnada it's not failing, it's looping on `batchGet`

**Comment by ifokeev** [comment]
same logs like in the tests:
https://github.com/airbytehq/airbyte/runs/2473478780?check_suite_focus=true

**Comment by sherifnada** [comment]
@ifokeev so the sync is succeeding but just looping for a long time? FWIW these log messages are incorrectly labelled as `ERROR` they are INFO messages.

**Comment by marcosmarxm** [comment]
logs from user using Airbyte 0.22.0-alpha shared on Slack convo [here](https://airbytehq.slack.com/archives/C01MFR03D5W/p1619514514278200) waiting info about connector version
[logs-1-0.txt](https://github.com/airbytehq/airbyte/files/6424279/logs-1-0.txt)

**Comment by vitaliizazmic** [comment]
Limits and Quotas on [Analytics Reporting API v4](https://developers.google.com/analytics/devguides/reporting/core/v4/limits-quotas):

- Number of requests per day per project: 50,000
- Number of requests per view (profile) per day: 10,000 **(cannot be increased)**
- Number of requests per 100 seconds per project: 2,000
- Number of requests per 100 seconds per user per project: 100 (can be increased in Google API Console to 1,000).

Usually daily quota is exiting.

**Comment by rparrapy** [comment]
Is this being worked on? I am getting the mentioned 429 errors and wanted to know if there is a fix on the horizon.

**Comment by pinkasey** [comment]
I see the same thing, when trying to sync UA->BigQuery, on AirByte 0.50.7:
<img width="1418" alt="image" src="https://github.com/airbytehq/airbyte/assets/1780369/ffec00db-1c6a-43c5-83f2-41008fd4af42">

To be precise -
the sync works fine, until I reach the quota. At this point, the log looks like this repeated line.
Expected behavior -
AirByte should detect this error message, and realize there's no point going continueing - stop the sync with some informative message. I think this should be marked as failure, even if some rows were synced.

**Comment by pinkasey** [comment]
I see now that there's a code exactly for that, in the connector:
https://github.com/airbytehq/airbyte/blob/ee168471b8f38d515451c1434a6bc478bcb27632/airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/source.py#L149C9-L149C21
and the doc says:
> When the daily request limit reached, the connector ignores an error with 429 code and
> 'has exceeded the daily request limit' error massage to finish successfully sync and
> inform the user about an error in logs with an error message and link to google analytics docs.
This was merged [a year ago](https://github.com/airbytehq/airbyte/pull/14949).  

Perhaps when this was merged, Google didn't have their "punishment mechanism" for retrying too much.
