### ISSUE TITLE
Oracle connector for Destination

### ISSUE THREAD

**Issue by zkiffli** [airbytehq/airbyte#3103]
## Tell us about the new integration you’d like to have
* Which source and which destination?
+++ Oracle for Destination.
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
+++ We are using multiple oracle DB version (11 to 19)

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
+++ This is part of our ETL /ELT features for Network Division.
* How often do you want to run syncs?
*+++ We have multiple run sync schedules (hourly, daily, weekly and monthly depending on use cases)
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
+++ Apache Airflow

**Comment by marcosmarxm** [comment]
Hi @zkiffli thanks for open the issue! We already have issue #2962 to discuss this. Can you comment on your case on that? 
I think using the base jdbc-destination and the community version of Oracle dbt to normalize data adding the Oracle destination is something doable.

Closing as duplicate.

**Comment by zkiffli** [comment]
Thanks @marcosmarxm thought that previous case just to resolve for source only. Btw, thanks for your assist.
