### ISSUE TITLE
Multiple workspaces in enterprise feature flag

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#31035]
Multiple workspaces in oss will be scoped to enterprise.  Use the featureservice `featureSetFromInstanceConfig` to set this up.

**Comment by josephkmh** [comment]
Refining notes:
- @tealjulia created two small BE PRs that should be merged before we release this (please add links)
- We can merge the FE work independent of the BE PRs if they will take longer than a few days
