### ISSUE TITLE
Source Postgres: making worker pod use a lot of memory

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#31041]
### Connector Name

source-postgres

### Connector Version

3.1.9

### What step the error happened?

During the sync

### Relevant information

The worker pod increases in memory usage insanely when syncing from a postgres source. I really can't figure out what's going on. When syncing from other sources this doesn't happen. But with Postgres source this always happends and eventually the worker pod runs OOM and crashes, causing syncs to fail. 

### Contribute

- [ ] Yes, I want to contribute

**Comment by ro8inmorgan** [comment]
When I force a java garbage collection with jcmd 7544 GC.run on the Node running the worker the memory usage goes down again. It seems there is some kind of memory leak?

**Comment by evantahler** [comment]
Closing as stale - we've updated the platform/worker code significantly since this issue was filed.  Please open a new issue if this still persists.
