### ISSUE TITLE
Show error toast when user attempts to re-enable sync with no credits

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#31077]
This is a very sad case that [happens a lot](https://app.fullstory.com/ui/13AXQ4/segments/everyone/people:search:OX8nEg103Clz?completeSessions=false): a user tries to re-enable a sync, they don't have enough credits, the sync does not re-enable but we don't tell the user why. Not building trust :/

**Proposed changes:** 
Trigger an error toast when the user tries to re-enable sync with no credits.
Toast message: "You're out of credits! Add more to re-enable your sync."
Toast CTA: "Add credits"
Toast CTA link: https://cloud.airbyte.com/workspaces/<workspace-id>/billing

[MOCKS](https://www.figma.com/file/Vd7CoZtM1B4pvodsowxP7c/No-credits-error-toast?type=design&node-id=1%3A1102&mode=design&t=2cbmr5L0c6urLpin-1)

**Comment by Dhairyash-1** [comment]
@nora-airbyte can you assign me this issue I want to work on this issue.

**Comment by josephkmh** [comment]
Refining notes:
- PR open for a quick solution here
- We need backend error codes to better tailor the frontend UX

**Comment by josephkmh** [comment]
Re-opening this, because the https://github.com/airbytehq/airbyte-platform-internal/pull/9161 does not include the correct message or an "Add credits" button
