### ISSUE TITLE
Unnesting array fields results in empty unnested columns

### ISSUE THREAD

**Issue by vitoravancini** [airbytehq/airbyte#3108]
## Expected Behavior
I have an use case where data gets extracted with the following schema:

`{"type": "RECORD", "record": {"stream": "exchange_rate_nested_currencies", "emitted_at": 1602637589000, "data": { "id": 1, "currencies": [{"short_name": "NZD", "value": 1.14},{"short_name": "HKD", "value": 2.13}], "date": "2020-08-29T00:00:00Z"}}}
`

and the catalog is the following:
 
` 
{
  "streams": [
    {
      "stream": {
        "name": "exchange_rate_nested_currencies",
        "json_schema": {
          "type": ["null", "object"],
          "properties": {
            "id": {
              "type": "integer"
            },
            "currencies": { 
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "short_name": {
                    "type": "string"
                  },
                  "value": {
                    "type": "number"
                  }
                }
              }
            },
            "date": {
              "type": "string"
            }
          }
        },
        "supported_sync_modes": ["incremental"],
        "source_defined_cursor": true,
        "default_cursor_field": []
      }
    }
  ]
}

`

I would expect a table with the following format:

![image](https://user-images.githubusercontent.com/4209575/116399719-98fabb80-a7ff-11eb-9247-a7cf2d8ea51b.png)

## Current Behavior

When I run my extraction with postgres destination all values of 'short_name' and 'value' fields are empty

## Steps to Reproduce
1. Create the catalog as shown here at the base-normalization integration tests catalog.json file.
2. Create a message as shown here at the base-normalization integration tests messages.txt.
3. Create a schema test like the following:

```
  - name: test_normalization_e__urrenc_f41_currencies
    columns:
      - name: short_name
        tests:
          - not_null
      - name: value
        tests:
          - not_null
```
at base-normalization/integration_tests/resources/test_primary_key_streams/dbt_schema_tests/schema_test.yml

4. Run the tests

## Severity of the bug for you
Medium

## Airbyte Version
0.21.1-alpha

## Additional context
I've already wrote code to fix it with integration tests, should I proceed with a PR?

Thank you!

**Comment by marcosmarxm** [comment]
> I've already wrote code to fix it with integration tests, should I proceed with a PR?

Absolutely :partying_face: nice contribution btw this will helps a lot transferring API data to data warehouses
