### ISSUE TITLE
Connector builder UI: Allow configuring page number injection on first request

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#31101]
### What area the feature impact?

Airbyte Platform

### Relevant Information

With https://github.com/airbytehq/airbyte/pull/30978 merged, the low code CDK now supports to inject the page number on the first request as well.

This should be exposed as a an additional flag in the connector builder UI as well (in the "advanced options" section)

**Comment by flash1293** [comment]
+1 from a customer

**Comment by lmossman** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/30987
