### ISSUE TITLE
How can I run Airbyte without any docker and vary apps?

### ISSUE THREAD

**Issue by mustafaulukaya** [airbytehq/airbyte#31159]
Hi,

I want to use Airbyte for simpliest way. On open source version, we must use docker for Airbyte. But I want to use it on my server, and I can't virtualize the server, so I cannot use docker or else. How can I use it?

P.S: Server is Windows machine

**Comment by marcosmarxm** [comment]
This isn't possible @mustafaulukaya Airbyte is developed using Docker containerization as a fundamental paradigm.
