### ISSUE TITLE
Cannot view bigger logs or download them

### ISSUE THREAD

**Issue by mrhallak** [airbytehq/airbyte#31178]
### Topic

logging performance

## Environment
- **Airbyte version**: 0.50.29
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker-compose
- **Source Connector and version**: Postgres (3.1.9) with XMIN replication
- **Destination Connector and version**: Snowflake (3.1.16)

When extracting data from Postgres, Airbyte seems to print some data in the logs causing the logs to be quite big (~3.0GB and more). 

### Issue 1
This causes us to just see a loader on the screen when we click on view logs and the logs never load

### Issue 2
We are not able to download the logs

## How I've debugged this
1. Start the job
2. Copy the path of the logs
3. Go into the worker container 
4. Run `tail -f logs` to monitor the logs (this is where I found out that Airbyte prints data in the logs)
5. Check the size of the logs when the job ends (this is where I found out that the size of the logs could be the reason why this is not loading in the UI)

**Comment by mrhallak** [comment]
I'm not sure if this was fixed with https://github.com/airbytehq/airbyte/pull/30806 is there any way to test this?

**Comment by sh4sh** [comment]
This sounds similar to https://github.com/airbytehq/airbyte/issues/30781. Can you try source-postgres v3.1.11?

**Comment by mrhallak** [comment]
Closing this as it looks good on v3.1.13, thanks @sh4sh  🙌🏻
