### ISSUE TITLE
Create a script to make working with contributions easier

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3118]
## Tell us about the problem you're trying to solve
When a contributor creates a pull request from a fork, secrets are not accessible for them via the fork. Secrets are needed to run integration tests for a connector. Therefore, we can't tell whether CI will succeed if we merge their code. Our flow then becomes: 

1. locally check out master and pull latest changes
1. create a branch `git checkout merge-pr-123`
1. pull changes from the contributor's branch
1. push to origin, creating the new branch `merge-pr-123`
1. create a PR
1. comment `/test connector=<connector_name>` to run the connector's integration tests
1. contributor iterates on the code. To re-run tests, I need to review the changes from the contributor's branch, repeat steps 3,4, and 6
1. repeat 7 until checks are passing
1. merge contributor's branch into `merge-pr-123`, apply any needed changes on top of it for publishing the new connector, then merge it to master. 

## Describe the solution you’d like
This is a super tedious workflow. I would love to have a single script which performs steps 1-5 so the workflow then becomes: 

1. When I've reviewed the PR and want to run CI checks, I invoke the script `./tools/github/contributions.sh connector <branch_name> <connector_name>`. This would perform steps 1-6 above. 
1. if they fail, the contributor iterates, I review their changes, then run the same command
1. Repeat step 2 until checks are successful
1. I can do step 9 manually,

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368104780005) by [Unito](https://www.unito.io)

**Comment by Phlair** [comment]
Should also solve this: https://github.com/airbytehq/airbyte/issues/3580

**Comment by davinchia** [comment]
This is solved by https://github.com/airbytehq/airbyte/pull/9742. We can now run the test command on external contributions.
