### ISSUE TITLE
Source Jira: Normalization is failing when i try to sync data from Jira to Redshift

### ISSUE THREAD

**Issue by MahakUrooj656** [airbytehq/airbyte#31180]
### Connector Name

Jira

### Connector Version

0.2.21

### What step the error happened?

During the sync

### Relevant information

 Syncing a pipeline from jira to redshift but it fails at normalization step and only raw table is created.
Airbyte version: 0.40.6
[logs-10.txt](https://github.com/airbytehq/airbyte/files/12845641/logs-10.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by MahakUrooj656** [comment]
i tried with Jira version 0.7.1 but still the normalization fails

**Comment by MahakUrooj656** [comment]
i tried the same on Airbyte version 0.50.30 and it results in the same error, normalization fails and only raw table is created in destination,
Here are the logs for the 3 attempts airbyte did to sync it.
[Attempt_1.txt](https://github.com/airbytehq/airbyte/files/12857339/Attempt_1.txt)

**Comment by girarda** [comment]
closing because normalization was removed from the airbyte product
