### ISSUE TITLE
In the UI we are showing type=unknown for `date-time`s without `airbyte_type `

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#31195]
[Consider Hubpot's schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/schemas/contacts.json)

```json
    "createdAt": {
      "type": ["null", "string"],
      "format": "date-time"
    },
```

This is a valid [Airbyte Type](https://docs.airbyte.com/understanding-airbyte/supported-data-types) because an optional `airbyte_type` means `Timestamp with timezone`.  However, in the UI we are calling these "unknown"

<img width="1137" alt="Screenshot 2023-10-09 at 2 50 18 PM" src="https://github.com/airbytehq/airbyte/assets/303226/f62ac8ea-294d-42aa-aeca-d75ca0890a7d">

Or... is `airbyte_type` not optional for `date-time`?

**Comment by evantahler** [comment]
Tagging @lmossman and @ambirdsall to prioritize

**Comment by lmossman** [comment]
This page actually falls under frontend-compose's domain, so tagging @josephkmh to prioritize

**Comment by josephkmh** [comment]
Easy fix - looks like we were just incorrectly matching `datetime` instead of `date-time` - PR is up 🔧
