### ISSUE TITLE
Source WooCommerce: Add incremental load for Customers Stream 

### ISSUE THREAD

**Issue by Dimi727** [airbytehq/airbyte#31202]
### What area the feature impact?

Connectors

### Relevant Information

I am not sure why, but the current customers stream only has full-load. This lead to a lot of costs and a long loading time.

Looking at the [endpoint documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#customers) I dont see a reason why this endpoint is not incremental?

**Comment by strosek** [comment]
This endpoint does have an `date_modified_gmt` that would be a good cursor, but cannot be filtered by modified date, as is the case for example with Customers, which can be filtered by `modified_after/before`. We need the filtering capability for [incremental syncs](https://docs.airbyte.com/connector-development/connector-builder-ui/incremental-sync).

**Comment by Dimi727** [comment]
Hey @strosek !

Yes indeed, I only explored that after asking for this feature 😄 I asked the WooCommerce team to add that (its weirds that this is the only main object that does not support it):
https://github.com/woocommerce/woocommerce/issues/41371
