### ISSUE TITLE
Redshift connector now crashes if the ingested data is over Redshift's limits

### ISSUE THREAD

**Issue by CataldoTractable** [airbytehq/airbyte#31216]
### Connector Name

destination-redshift

### Connector Version

0.6.5

### What step the error happened?

During the sync

### Relevant information

I was on connector version 0.3.54, and then I updated to 0.6.5. After the update, in ingesting a stream from Postgres to Redshift, the connection now crashes. The error varies each time, but it just says `Broken pipe` most of the times. After investigation and looking at the worker logs, I discovered that the load was failing on the redshift side when the COPY command was issued by Airbyte. The reason, one of the records was over the 65k char string limit.

In version 0.3.54, there was a check called  isValidData that was checking for records being the correct size. I don't see this in the new connector. When this function was there in the sync I would see logs like:

`A total of 6 record(s) of data from stream <stream_name> were invalid and were ignored.`

Now I don't see this any longer.

this was the `isValidData()` function:

```
public boolean isValidData(final JsonNode data) {
    // check overall size of the SUPER data
    final String stringData = Jsons.serialize(data);
    final int dataSize = stringData.getBytes(StandardCharsets.UTF_8).length;
    boolean isValid = dataSize <= REDSHIFT_SUPER_MAX_BYTE_SIZE;

    // check VARCHAR limits for VARCHAR fields within the SUPER object, if overall object is valid
    if (isValid) {
      final Map<String, Object> dataMap = Jsons.flatten(data);
      for (final Object value : dataMap.values()) {
        if (value instanceof String stringValue) {
          final int stringDataSize = stringValue.getBytes(StandardCharsets.UTF_8).length;
          isValid = stringDataSize <= REDSHIFT_VARCHAR_MAX_BYTE_SIZE;
          if (!isValid) {
            break;
          }
        }
      }
    }
    return isValid;
  }
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by sh4sh** [comment]
@CataldoTractable can you try the latest version of destination-redshift? In particular I'd be interested in seeing if [0.6.6](https://docs.airbyte.com/integrations/destinations/redshift#changelog:~:text=jvm%20GC%20retries-,0.6.6,-2023%2D10%2D06) changes anything, looks like we reduced block size in the async buffer which sounds like it could help.

**Comment by evantahler** [comment]
This is a result of https://github.com/airbytehq/airbyte/pull/27993.
Prior to that change, as you call out, we were silently dropping data that was too large to fit in redshift, but saying the sync is successful.  Now, the syncs fail.  This at least makes the problem visible to you so you can act acordingly (deselect a column, create a view to truncate/trim data in the source, etc).

In the future, once Redshift is migrated to [DestinationsV2](https://github.com/airbytehq/airbyte/issues/26028), we will have the ability to upload a partial record (PK+cursor), and a message indicating which columns we've NULLed so the row can fit

**Comment by sh4sh** [comment]
Thank you @evantahler for the quick reply! Your explanation makes sense. The `Broken pipe` message threw us off here since it wasn't obvious what happened (and, well, it's a scary message but it's great to hear it is expected.

@CataldoTractable It looks like this change was made in an effort to improve consistency between what users choose to sync and the loaded data (i.e. nothing is silently dropped). As suggested, the sync will succeed if you deselect the applicable columns or create a view that doesn't include the incompatible records. Can you confirm if that works for you, and let us know if something else is awry?

**Comment by evantahler** [comment]
Closing as fixed
