### ISSUE TITLE
1s1t for Redshift

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#31223]
* Redshift gets the Dv2 treatment
* Also include price data in perf dashboard(s)
* Speed and Cost fit perf constraints above across many sizes of sync
* manage rollout (3 beta users)

---

SqlGenerator
CatalogParser
Normalization into container (but we need to roll it out)
V1->V2 migrator
Make it work

---

migration (v1-->v2)
full refresh
incremental

**Comment by pranasziaukas** [comment]
> manage rollout (3 beta users)

Is it still possible to participate in the upcoming beta rollout @evantahler? cc @cynthiaxyin 

I filled some form in the summer stating that we'd be interested in trying out the Redshift destination V2.

**Comment by cynthiaxyin** [comment]
@pranasziaukas Thanks for your interest! Yes, it is still possible and you can track the progress of this project on this issue. #31575 is likely where we will add updates about the beta rollout. cc @evantahler

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

:white_check_mark: **What’s been completed:**

- [draft PR](https://github.com/airbytehq/airbyte/pull/32326/) being collaborated on
- Cynthia, Ed, and Gireesh met to walk through the code and generate a shortlist of TODO's
- 23 beta users contacted with a ["coming soon" email](https://docs.google.com/document/d/1mCXgipFV36tQtizzye8JqdhNX6R6vqA6Z6SadByGNqg/edit#heading=h.l22n75ymemag)

:books: **Learnings and hurdles:**

- beta users are [excited](https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1699911267983729)!
- some of the existing destinations code structure could be better organized
  - Gireesh documented some of the current flow

:no_entry_sign: **Blockers:**

- folks got sick

:seedling: **Looking ahead:**

- more collaboration and progress on the code (SqlGenerator, migration code, etc.)
- Cynthia working on [documenting our process](https://github.com/airbytehq/airbyte/issues/32276) for future implementations of Destinations V2

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

**:white_check_mark: What’s been completed:**
- lots of progress on the Dv2 implementation!
  - RedshiftSqlGenerator and migration code are complete
  - Redshift Dv2 and T&D test suites are all passing

**:books: Learnings and hurdles:**
- the Dv2 test suites are pretty high-effort to set up, but they pay off very quickly in terms of leverage

**:no_entry_sign: Blockers:**
- minimal dev time last week due to hack days + holidays

**:seedling: Looking ahead:**
- move Redshift standard inserts onto the async framework to reduce duplicate/throwaway work
- plug T&D into the rest of the connector (standard inserts and S3 staging)
- release the first beta image once one loading method is working (targeting next week)
- beta user group will receive comms and be added to a private Slack channel when the first beta image is released

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

:white_check_mark: **What’s been completed:**
- moved Redshift standard inserts onto the async framework
- Dv2 is ready for beta testing (both standard inserts and S3 staging) with green build and passing tests

:books: **Learnings and hurdles:**
- [preliminary performance testing](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1701465783792839?thread_ts=1701454810.478009&cid=C065B1LSTL7) shows Dv2 on par with Dv1 speed
- Metabase is [missing data](https://github.com/airbytehq/airbyte-warehouse/issues/1642) around Redshift loading methods

:no_entry_sign: **Blockers:**
- none

:seedling: **Looking ahead:**

- investigating memory consumption footprint after switching Dv1 standard inserts to async
- final PR review and performance testing
- release the beta!
  - beta user group will receive comms and be added to a private Slack channel

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

:white_check_mark: **What’s been completed:**

- launched the beta! :tada:
- invited ~20 users to try it out #ext-destinations-v2-redshift-beta 

:books: **Learnings and hurdles:**

- beta user has already given us valuable feedback around data types, permissions, and optimizations

:no_entry_sign: **Blockers:**

- none

:seedling: **Looking ahead:**

- continue sourcing feedback from beta users (goal is 3, ideally covering both loading methods)
- road to GA and certification
- further improvements as we prepare for Postgres and MySQL V2

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

:white_check_mark: **What’s been completed:**

- [PR campaign](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1702671346494479?thread_ts=1702663305.283799&cid=C065B1LSTL7) via many tools to source more beta testers
- identified additional improvements around error reporting and timeouts

:books: **Learnings and hurdles:**

- refined our speed measurements which [look good](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1702933192310149?thread_ts=1702486594.354599&cid=C065B1LSTL7)

:no_entry_sign: **Blockers:**

- waiting for 2 more beta testers to give us feedback

:seedling: **Looking ahead:**

- fix outstanding bugs
- tentative timeline
  - 1st week of Jan - GA
  - middle of Jan - set up Redshift cost dashboard
  - Feb 1 - certification
  - Mar 1 - breaking change deadline

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

**:white_check_mark: What’s been completed:**

- ~3 more beta users gave feedback

**:books: Learnings and hurdles:**

- OSS users [need to select](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1703119308433109) `Raw data (JSON)` as their Normalization method under the Transformation tab
- beta users have helped us discover error cases to address

**:no_entry_sign: Blockers:**

- none

**:seedling: Looking ahead:**

- fix remaining bugs for GA
- write up summary of beta program
- tentative timeline
  - 2nd week of Jan - GA
  - 2nd half of Jan - set up Redshift cost dashboard
  - Feb 1 - certification
  - Mar 1 - breaking change deadline

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

**:white_check_mark: What’s been completed:**

- completed bug fixes/tasks for GA

**:books: Learnings and hurdles:**

- [reflections on beta program](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1704400161158579)

**:no_entry_sign: Blockers:**

- none

**:seedling: Looking ahead:**

- 3 remaining bugs/tasks, aiming to GA this week
- subsequent timeline
  - 2nd half of Jan - set up Redshift cost dashboard
  - Feb 1 - certification
  - Mar 1 - breaking change deadline

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

**:white_check_mark: What’s been completed:**

- bug fixes ([1](https://github.com/airbytehq/airbyte/issues/33552), [2](https://github.com/airbytehq/airbyte/issues/33983))
- GA code changes are [ready](https://github.com/airbytehq/airbyte/pull/34077)

**:books: Learnings and hurdles:**

- more beta user [feedback](https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1705307423270339)

**:no_entry_sign: Blockers:**

- [CI issues](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1704830772375909)
- OC

**:seedling: Looking ahead:**

- this week
  - [one open bug](https://github.com/airbytehq/airbyte/issues/34273)
  - breaking change release doc
  - GA by end of week
- then
  - 2nd half of Jan - set up Redshift cost dashboard
  - mid Feb - certification
  - mid March - breaking change deadline

**Comment by cynthiaxyin** [comment]
[Redshift Destinations V2](https://github.com/airbytehq/airbyte/issues/31223) weekly update:

**:white_check_mark: What’s been completed:**

- [we GA'd!](https://airbytehq-team.slack.com/archives/C04VDANQN7P/p1706057513293409) :tada:
- [breaking change release doc](https://docs.google.com/document/d/1Daik2rWJOt4vUiPMDO-R_LomI5rY8njiYFhuY1OoR3U/edit)

**:books: Learnings and hurdles:**

- `use_1s1t_format` continues to [rear its head](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1705955612536839)
- also the CDK

**:no_entry_sign: Blockers:**

- n/a

**:seedling: Looking ahead:**

- Redshift cost dashboard
- [certification!](https://github.com/airbytehq/airbyte/issues/33869)
- breaking change deadline March 15

**Comment by cynthiaxyin** [comment]
onward to certification! #33869
