### ISSUE TITLE
Setup connected account tests for Airbyte-native stripe connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3122]
## Tell us about the problem you're trying to solve
#3121 added support for reading data from stripe connected accounts. 

However, we don't have adequate test coverage for testing data from Stripe Connected Accounts. To have that we'll need to do the following: 
1. Use the lastpass creds "Stripe Connected Account Test Creds"  (put them in `secrets/connected_account_config.json`)
2. Use the credentials to populate the connected account with data for all possible streams (see all streams in `schemas/` folder)
3. Migrate source-stripe to start using the new Source Acceptance tests (reach out to Eugene K so he can point you to the docs and examples)
4. In the Source Acceptance Tests, run the test configs using _both_ configs (config.json and connected_account_config.json)
5. Add the credentials to github CI and `ci_credentials.sh`, `test_command.yml` and `publish_command.yml`
6. Add the connector to `source_definitions.yml` and remove the singer connector
7. Modify the connector health page to point to the new build page
8. If any code changes are required, publish a new version of the connector
9. Modify the connector documentation (`airbyte/docs/integrations/sources/stripe.md`) to mention the additional streams it syncs (bank_accounts and refunds)

**Comment by Zirochkaa** [comment]
@sherifnada I have a question about item number 5 from issue description (`Add the credentials to github CI and ci_credentials.sh, test_command.yml and publish_command.yml`):

I found `ci_credentials.sh` file - it's located in `tools/bin/` folder. But I didn't find `test_command.yml` and `publish_command.yml` files (I was using a search in PyCharm and VSCode).
Could you please wrote in which folders these files can be found?

**Comment by Zirochkaa** [comment]
Also there is no `Stripe Connected Account Test Creds`creds in LastPass (at least I don't see them).
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/19872253/116885270-5fc3b080-ac30-11eb-9242-d0ce296aee7c.png">
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/19872253/116885549-ac0ef080-ac30-11eb-8579-650197147799.png">

**Comment by sherifnada** [comment]
@Zirochkaa  my mistake -- will update lastpass

**Comment by Zirochkaa** [comment]
> @sherifnada I have a question about item number 5 from issue description (`Add the credentials to github CI and ci_credentials.sh, test_command.yml and publish_command.yml`):
> 
> I found `ci_credentials.sh` file - it's located in `tools/bin/` folder. But I didn't find `test_command.yml` and `publish_command.yml` files (I was using a search in PyCharm and VSCode).
> Could you please wrote in which folders these files can be found?

Those "missing" files are in [workflows](https://github.com/airbytehq/airbyte/tree/master/.github/workflows) folder.

**Comment by sherifnada** [comment]
@Zirochkaa added connected account credentials to lastpass
