### ISSUE TITLE
Source Square: Payments and Refunds streams are duplicated

### ISSUE THREAD

**Issue by juftin** [airbytehq/airbyte#31237]
### Connector Name

source-square

### Connector Version

1.1.2

### What step the error happened?

During the sync

### Relevant information

There's some issues on paginating payments and refunds. For those streams airbyte is returning tons of duplicates.

### Contribute

- [ ] Yes, I want to contribute

**Comment by juftin** [comment]
Mentioned in #30309

**Comment by topefolorunso** [comment]
Can you add this issue to the hacktoberfest 2023 project please? @justinbchau. See comments below for reference

- https://github.com/airbytehq/airbyte/issues/30309#issuecomment-1750977762
- https://github.com/airbytehq/airbyte/issues/30309#issuecomment-1751689249

Also, if you can add it, please assign it to me. I would like to work on it. Thanks.

**Comment by justinbchau** [comment]
@marcosmarxm

**Comment by topefolorunso** [comment]
@justinbchau Can you add this issue to the Hactoberfest project?

**Comment by topefolorunso** [comment]
PR raised for this one @justinbchau
