### ISSUE TITLE
Destination Performance Dashboard

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#31238]
* make a good perf dashboard showing warehouse cost and speed
* be within 10% of v1 normalizatoin's T&D cost; 30% of v1 speed
* consider both initial sync and subsequent deduped syncs; consider differnet sizes of data (cols/rows/bytes) 
* query DWs and get sync pricing and send to metabase so we can analyze

**Comment by evantahler** [comment]
Don't forget to point this story!

**Comment by jbfbell** [comment]
The initial performance dashboard [is available](https://airbyte.metabaseapp.com/dashboard/2152-destination-performance?relative_date=past7days&is_cloud=true&job_status=succeeded&is_pba=false&internal_user=false&minimum_data_volume_mb=10) This dashboard is based on the available data which relates mostly to speed.
