### ISSUE TITLE
Add makefile to install / uninstall internal tools

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#31257]
## Problem
It is difficult with internal tools to ensure every developer environment is the same

## Solution
A makefile (at the root of the repo) with the following commands
* `make internal-tools.install`
* `make internal-tools.uninstall`
* update pipeline docs to tell folks to use makefike instead of pipx stuff

What will we install?
* pyenv (+python v3.10)
* pipx
* poetry
* ci-credentails
* connector pipelines

Notes:
* This is just for local development, not CI?  Maybe we will want this for CI... that's later

### Implementation
~~We may be able to leverage ansible here?~~
~~Setup for precomit hooks~~

**Comment by evantahler** [comment]
Grooming:
* we need to setup pyenv, pipx, etc.  We can automate this.
* un-install is crazy
* We can then use this with ansible (dev laptop setup)
