### ISSUE TITLE
source-mysql : Investigate how user could end up in an invalid security configuration 

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#31291]
User ended up in a situation for the MySQL connection where the connector's config is : 
1. SSL mode = preferred
2. No SSH tunnel 

https://cloud.airbyte.com/workspaces/6a47f1b1-4a23-4a39-87ed-46a71bd5d5b2/source/e9bf7dd7-e263-4d49-97f6-b5b752f9e7ad 

This config should have never allowed to pass the check phase. So it's not clear how the user ends up in this situation : https://cloud.airbyte.com/workspaces/6a47f1b1-4a23-4a39-87ed-46a71bd5d5b2/connections/726ae129-982b-4407-ac90-8da25055257b/job-history#4934329::0

**Comment by prateekmukhedkar** [comment]
Hypothesis - was the connection created using API? UX does not allow the combination called out in description

**Comment by akashkulk** [comment]
That hypothesis is correct. Synced with @terencecho related to this and confirmed that this source was created via API - so not a regression with the source-mysql check method. 
Couple of options here : 
1. The create API calls `check()` similar to the the experience on the web app. However, this introduces a TON of latency and there might be some bulk import/export workflows for which this may not be feasible?
2. Dev enablement team can add a hook for the user to immediately call check after creating a source (though this won't necessarily solve the problem at hand, only encourage users of the API to check the source and fix it if it fails check())
