### ISSUE TITLE
[Source-MsSQL] Investigate missing datatypes and provide correct conversion for standard and CDC Mode

### ISSUE THREAD

**Issue by nguyenaiden** [airbytehq/airbyte#31296]
Currently, Source-MSSQL is still missing datatypes such as `datetime2` that is still incorrectly recognized as a string. Task is to go through all the current datatype mapping that currently exists for source-mssql and fill in the missing ones.

**Comment by prateekmukhedkar** [comment]
Definition of Done: Test(s) that cover all MS-SQL datatypes and validates the output Airbyte Records. 
Need to be done for CDC and Standard mode.
