### ISSUE TITLE
[Source-MsSQL] Stand up benchmarkDBs

### ISSUE THREAD

**Issue by nguyenaiden** [airbytehq/airbyte#31293]
Similar to Postgres and Mysql, we will need to set up a benchmark DB for MsSQL in order to test, verify, and benchmark our changes and improvements to the Source-MSSQL Connector.

Acceptance criteria: Standup a 1gb, 10gb, 100gb, and 1tb benchmark db. Look into a generic method to do this if possible.

**Comment by prateekmukhedkar** [comment]
CDC will be enabled on the database.
