### ISSUE TITLE
Source Acceptance Tests: explicitly opt-out of testing all streams output by discover operation

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3132]
## Tell us about the problem you're trying to solve
In some cases it is easy to forget to include streams in the test catalog. This can cause issues to go undetected in streams. The user should explicitly opt-out of verifying that all streams should be tested (or find some other way to guard against this sanely).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368163170650) by [Unito](https://www.unito.io)

**Comment by keu** [comment]
@sherifnada is n't discovery test doing that?

**Comment by sherifnada** [comment]
@keu meant for reading streams. What prompted me to create this issue is that I forgot to include a stream in my configured_catalog (out of like 18 streams in the stripe connector). And of course, that one stream had a bug that was undetected because standard tests didn't test output from it. This ticket is trying to solve for that kind of problem.

**Comment by keu** [comment]
well, if we assume that we use the same file for both tests - the problem solved
if not, then there is only one reason - separate streams that passes all read tests from streams that don't, in that case I don't see how we can force user to specify all streams.

**Comment by keu** [comment]
ok, gave this soome thought, I think this can be solved with changing basic read test:
- deprecate `validate_output_from_all_streams`, make it always ON
- introduce new config var `empty_stream' - a list of streams that can be empty
- basic read will verify that all streams from discovery included in the configured catalog for basic read.
