### ISSUE TITLE
Improve Snowflake Native Apps documentation

### ISSUE THREAD

**Issue by ambirdsall** [airbytehq/airbyte#31362]
### Page URL

https://docs.airbyte.com/snowflake-native-apps/linkedin-ads/#snowflake-native-app-authorizations

### Description

Notes on the connection setup docs:
- the documentation should be consistent about either using the `<app_name>` placeholder or hardcoding the default app name (hardcoding the default is my preference: it makes the common case a simple copy/paste, and for renamed apps the default name is no harder to replace than the placeholder)
![image](https://github.com/airbytehq/airbyte/assets/7516653/15f7e26b-d4da-48bf-a0d0-02c14fc29a64)
![image](https://github.com/airbytehq/airbyte/assets/7516653/5f451a77-b84d-40a8-9131-93c874d7b4e4)
- nit: the gif uses a different name for the db's oauth secret than the instructions above it
- it would be nice if the field notes on Output Schema gave the format with placeholders in the same way that the field notes on Secret do (e.g. `<output_database>.<your_schema>`). I had to re-watch the gif here because I wasn't sure if I was supposed to namespace it with the db name or just provide the schema name per se
- super trivial nit: it might be nice to specify the date format with both format and example instead of just an example, i.e. "UTC date in the format `YYYY-MM-DD` (e.g. 2020-09-17)"

**Comment by brianjlai** [comment]
fixed this in various docs and PR improvements over the past month. closing as complete
