### ISSUE TITLE
Source Facebook Marketing: Data Doesn't sync in postgres no data sync in it 

### ISSUE THREAD

**Issue by Prabal231997** [airbytehq/airbyte#31374]
### Connector Name

Postgres v0.4.0

### Connector Version

0.4.0

### What step the error happened?

During the sync

### Relevant information

I synced the FB Data from Facebook marketing Connector to the destination Postgres but the data is does not sync into the Postgres , When I Checked the table in Postgres then table is empty , Please have a look into this.

### Contribute

- [X] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
