### ISSUE TITLE
Source MySQL: BinLog to Snowflake SCD _SCD History tables no longer updating

### ISSUE THREAD

**Issue by alandmorford** [airbytehq/airbyte#31392]
### Connector Name

source-mysql

### Connector Version

3.1.1

### What step the error happened?

During the sync

### Relevant information

Using the Sync Mode `Incremental + Deduped` is no longer updating History Tables as it was on prior versions.
https://docs.airbyte.com/understanding-airbyte/connections/incremental-append-deduped) 

In Snowflake previous syncs have been maintaining table pairs: (Orders, Orders_scd) 
after nearly a week of syncs on source-mysql 3.1.1 the _scd tables have no new data and seem to be no longer updating.

Does source-mysql connector have tests that verify producing _SCD table data? 

It was working, now is not.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Closing as SCD tables have been removed
