### ISSUE TITLE
[Roadmap] Automatic Backfills for Schema Propagation

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#31420]
Automatic schema propagation does not currently backfill any existing data values for column changes. 

This feature allows you to optionally decide if a reset should be done after a schema change is detected. When enabled, the stream will be reset automatically in order to backfill the data for all rows when the schema change is propagated.

You can stay up-to-date on Airbyte's latest announcements [here](https://airbyte.com/blog-categories/company-updates).

**Comment by rileybrook** [comment]
@flutra-osmani is this still the correct status for this item (still in-progress during Nov-Feb period). If not correct, can you update the status, and move to released column 🙏

**Comment by sam2schwab** [comment]
@nataliekwong When can we expect this to be done? We are forced to reset the streams manually and it can't even be automated with the API as it does not support resetting streams.

**Comment by nataliekwong** [comment]
Hey @sam2schwab - we can manually enroll workspaces in the feature for now, since the configuration is not yet available through the UI and will be coming in the next few weeks. I'll be in touch via email to confirm the enrollment.
