### ISSUE TITLE
Source MongoDb: connector 1.0.1

### ISSUE THREAD

**Issue by khzakii** [airbytehq/airbyte#31429]
### Connector Name

source-MongoDb

### Connector Version

1.0.1

### What step the error happened?

During the sync

### Relevant information

I have an issue with new connector of mongodb and I have documents I want to sync to bigquery and there is a type like the following "
id : UUID('0bbc3c36-4c2c-44c8-a882-298e7c80b4b2')"

but when syncing I got the following error :
java.lang.RuntimeException: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.
 and I can't fix this config in the connector

### Relevant log output

```shell
Failure reason: Something went wrong in the connector. See the logs for more details.
See more
java.lang.RuntimeException: org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Closing as fixed in the latest version
