### ISSUE TITLE
source-postgres: improve test setup and teardown to make them faster

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#31438]
Java tests (unit / integration) rely on services like Debezium and testcontainers. A lot of runtime is spent waiting for these services to be available. E.G: in unit tests wait 1mn for debezium to start. For testcontainers: a lot of database containers are started (one by test): it’s resource intensive and might be optimizable with clever container reuse. 

Furthermore, in Java tests, a lot of tests are effectively skipped by early exits, because those tests are defined in connector-agnostic base classes. However, we still pay the price of doing setups and teardowns. 

Finally, on CAT very simple tests like spec take a couple of minutes to run. This can be due to a CAT daggerization overhead

**Comment by alafanechere** [comment]
> Finally, on CAT very simple tests like spec take a couple of minutes to run. This can be due to a CAT daggerization overhead

This is addressed in https://github.com/airbytehq/airbyte/pull/31699

**Comment by postamar** [comment]
See https://github.com/airbytehq/airbyte/issues/31298 for profiling results.

**Comment by postamar** [comment]
https://github.com/airbytehq/airbyte/issues/31818 covers the testcontainers aspect of this issue and is the only outstanding thing remaining here.

**Comment by bnchrch** [comment]
@postamar Just wanted to checkin if this is able to be considered done and closed?

**Comment by postamar** [comment]
Oh yes!
