### ISSUE TITLE
source-postgres: reduce the coverage overlap between unit tests, integration tests and CAT 

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#31437]
We believe that unit and integration tests overlap: the same kind of test is executed in unit and integration tests. 
The single difference is that unit tests directly call connector entrypoints through the java code while integration tests call the built connector container. This leads to coverage overlap hence redundant testing.

We also believe that integration tests overlap with what can be tested by CAT. 
CAT can test correct behavior of syncs with multiple configurations (e.g CDC vs standard). 
We believe a lot of Java AcceptanceTest can be replaced by CAT. 

We believe that CAT should be used in priority because its test suite is global to all our connectors.

**Comment by postamar** [comment]
I'm closing this because it should be made irrelevant by tests being fast. We like all the tests.
