### ISSUE TITLE
source-postgres: evaluate the test performance boost of using real database vs testcontainers

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#31441]
The use of `testcontainers` in Java DB tests has overheads: the orchestration and provisionning of containers has a resource impact that can make the test slower and hard to run locally.
We should evaluate if running integration tests agains a real hosted DB improves the test performances compared to the use of `testcontainers`.

Definition of done:
- We know how much faster (or slower) tests run when using a remote postgres database
- If tests are faster using the remote database: an issue is created to migrate the tests to use the remote database.

**Comment by postamar** [comment]
Won't do. We like testcontainers when used properly.
