### ISSUE TITLE
[Roadmap] Concurrent CDK

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#31473]
Airbyte will release a concurrent module within the [Python CDK](https://airbyte.com/solutions/connector-development-kit) for implementing and configuring API source connectors that can read data from multiple resources in parallel. This module will enable the creation of connectors that can send multiple concurrent requests, leading to faster syncs.

You can stay up-to-date on Airbyte's latest announcements [here](https://airbyte.com/blog-categories/company-updates).

**Comment by girarda** [comment]
Closing as a first version of the concurrent cdk has been released. We recommend developers install the CDK >=0.60.1.

This is still considered experimental, but [source-stripe](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-stripe/source_stripe/source.py), and [source-salesforce](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/source.py) can serve as good templates to model.

Feel free to direct any questions or feedback to our slack #help-connector-development or to [start a discussion](https://github.com/airbytehq/airbyte/discussions).

**Comment by meyerovb** [comment]
what's the model to use concurrent for only one endpoint.  source-shopify transactions need to be pulled one call per order, shopify plus customers get 20 calls per second, but it's only pulling 3/second for me so its gonna take 2 weeks to backfill.

**Comment by girarda** [comment]
@meyerovb 
source-shopify is an interesting case. we won't be using concurrency for this connector. We'll instead use the bulk api to speed up the connector. it should be released soon

**Comment by meyerovb** [comment]
@girarda thanks, any comment [on this](https://github.com/airbytehq/airbyte/discussions/34787)?
