### ISSUE TITLE
Source Github: TypeError breaks sync

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3150]
## Expected Behavior
the  [demo instance's github connector](https://demo.airbyte.io/connections/a745d135-0ab7-4b3c-b12b-b6a8a799f563) is failing due to a TypeError. We should diagnose the issue and fix it. 

Here are the logs from the failing sync. [logs-901-2.txt](https://github.com/airbytehq/airbyte/files/6402964/logs-901-2.txt)

**Comment by keu** [comment]
side note, it also makes sense to change log level of some error messages in the logs.
Errors is something that prevents successful finish, those errors that we have in a logs should be warnings.

**Comment by keu** [comment]
Breakdown:
- [ ] Investigate why some record in milestones don't have due_on (3h)
- [ ] depending on the outcome of prev item, either just ignore records or use some other field instead (`completeness`, etc)(1h)
- [ ] lower error message level to warning (30m)

Total: 4-6hours

**Comment by grebessi** [comment]
The problem was related to tap-github trying to convert a none value to a date.
The PR for this fix is here:
airbytehq/tap-github#3
After it gets approved and released, we will be able to upgrade the package.

**Comment by grebessi** [comment]
#3314 solved this issue.
