### ISSUE TITLE
Clarify connectors licence

### ISSUE THREAD

**Issue by AnneWL** [airbytehq/airbyte#31503]
### Page URL

https://docs.airbyte.com/project-overview/licenses/license-faq

### Description

Hello,

I try to find the licence for few connectors and I'm not sure where to find the real answer.

In the [FAQ](https://docs.airbyte.com/project-overview/licenses/license-faq), I can read `Airbyte Connectors are open sourced and available under the MIT License.`.

In the [root integrations](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations) folder there is a MIT License.

And directly in the connector, for example [Postgres](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-postgres) there is no LICENCE file but I also found [this PR](https://github.com/airbytehq/airbyte/pull/27737) that seems to change the licence from MIT to Elv2.

If I follow [the rule here](https://github.com/airbytehq/airbyte/blob/master/LICENSE) then the `postgres` connector licence is `MIT` because `First LICENSE found when exploring parent directories up to the project top level directory` ? Am I missing something ?

Can you help me ? Thanks !

**Comment by nataliekwong** [comment]
Hi @AnneWL, great sleuthing! Postgres is actually under Elv2 now, and that change occurred in the PR you shared. It looks like our docs are not up to date and we will take care of updating the FAQ and work with the appropriate Engineering team to add a license to the file.

**Comment by evantahler** [comment]
We'll get those docs clarified - https://github.com/airbytehq/airbyte/pull/32575
