### ISSUE TITLE
[source-MongoDB] Connector throwing memory limit exceeded error during schema discovery

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#31514]
When setting up the MongoDB connector, user is running into an issue related to memory limit exceeded.

Workspace link https://cloud.airbyte.com/workspaces/f7e560e1-c7fc-4931-a354-813ac699cf37/source/81fa9d40-6824-40ae-9400-0dd2f73267e5

Error recieved
![image](https://github.com/airbytehq/airbyte/assets/123108018/8e4c6805-9ef4-49f1-8f21-dd931b3781a5)

**Comment by prateekmukhedkar** [comment]
![image](https://github.com/airbytehq/airbyte/assets/123108018/bed06741-03d6-4756-b749-66c0dbe3a201)

**Comment by prateekmukhedkar** [comment]
Options:
1. Allow user to pass in `allowDiskUsage` when setting up connector
2. Default `allowDiskUsage : true` in connector
cc @rodireich

**Comment by aaronsteers** [comment]
Can we extract the schema scanning sample without applying a sort?

**Comment by rodireich** [comment]
Simply adding `.allowDiskUse()` is returning `null` for some reason.

**Comment by wmikemoon** [comment]
@prateekmukhedkar @rodireich The user wrote back and said they had the same error:

![image](https://github.com/airbytehq/airbyte/assets/41408069/886e89ca-5280-4150-9e49-d8a9c782b1df)
