### ISSUE TITLE
BigQuery documentation not updated with V2 destination changes

### ISSUE THREAD

**Issue by ignaciovi** [airbytehq/airbyte#31549]
### Page URL

https://docs.airbyte.com/integrations/destinations/bigquery?_gl=1*zxo4wi*_gcl_au*MTgxOTM3MzEzNy4xNjkwMjgzNTA3#gcs-staging

### Description

Due to changes in the BigQuery destination (version 2.0.0+) some parts of the BigQuery documentation are outdated.

I've created a PR with the changes here https://github.com/airbytehq/airbyte/pull/31548

**Comment by nataliekwong** [comment]
Thank you for contributing! I'm closing this issue as the PR has been merged.
