### ISSUE TITLE
Add analytics messages to job tracker

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#31546]
### What area the feature impact?

Platform

### Relevant Information

https://github.com/airbytehq/airbyte-platform-internal/pull/9307 adds the first low-level handling of analytics messages by simply logging them.

To be able to properly use them for analytics purposes, these messages should be added to the tracking event:
* In `oss/airbyte-commons-worker/src/main/kotlin/io/airbyte/workers/internal/bookkeeping/AirbyteMessageTracker.kt`, keep track of at max 50 analytics messages emitted from source and destination as an array (similar to the errors)
* In `oss/airbyte-commons-worker/src/main/kotlin/io/airbyte/workers/general/ReplicationWorkerHelper.kt`, add the arrays of analytics messages to the ReplicationAttemptSummary object
* In `oss/airbyte-persistence/job-persistence/src/main/java/io/airbyte/persistence/job/tracker/JobTracker.java`, add these arrays to the tracking metadata so it's send out as part of the existing sync tracking object

**Comment by davinchia** [comment]
@flash1293 is this still relevant?

**Comment by flash1293** [comment]
No, that's done. Closing
