### ISSUE TITLE
Pinecone does not use correct stream identifier

### ISSUE THREAD

**Issue by hwaxxer** [airbytehq/airbyte#31550]
### Connector Name

destination-pinecone

### Connector Version

0.0.16

### What step the error happened?

During the sync

### Relevant information

The document processor in the vector_based_db CDK uses a stream identifier: https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/destinations/vector_db_based/document_processor.py#L96-L100

The Pinecone destination does not use this identifier when deleting records so if a namespace is set, records will not be deleted properly when resetting a stream: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-pinecone/destination_pinecone/indexer.py#L41

### Contribute

- [X] Yes, I want to contribute

**Comment by flash1293** [comment]
Reopening as it's not released yet
