### ISSUE TITLE
Redshift V2: handle breaking change release

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#31592]
See [template](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cpwXaY8QxEgzw/edit#heading=h.r2xzw0kclodc) and [BQ + Snowflake doc](https://docs.google.com/document/d/1p9PnS4LOmzSGZsNP2b-WUdoH6HjXBO4uPwEXMOtgsUQ/edit#heading=h.r2xzw0kclodc).

This includes (non-exhaustive):
- `metadata.yaml` entry
- Migration guide in docs
- Remove `Raw data (JSON)` and `Normalized tabular data` radio buttons

**Comment by jbfbell** [comment]
Push Breaking Change release out from 3/1 because this is the Friday of Assemble 3.
