### ISSUE TITLE
Source Snapchat Marketing: does pull newest data from ad stats daily (3 days lag)

### ISSUE THREAD

**Issue by rytis-molecule** [airbytehq/airbyte#31641]
### Connector Name

source-snapchat-marketing

### Connector Version

0.3.0

### What step the error happened?

During the sync

### Relevant information

We have noticed that for the last several days we do not get ad stats daily correctly. For some reason it slices only up to the 16th of October (now it is the 20th). Every day there is spend. Timezone Berlin of the account. Tried to reset the connection but it did not work...

### Relevant log output

LOGS:
[job_13081_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13050355/job_13081_attempt_1_txt.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by rytis-molecule** [comment]
@Diana-Vait any updates on this one? I tried to reset the stream but it seems that the date slicing is done incorrect in the connector... The latest values I get are 3 days old :( Thanks!

**Comment by rytis-molecule** [comment]
also the date_start is shown as optional but the connector won't work without it.

**Comment by rytis-molecule** [comment]
Since it is GA connector thought it might be something for your team to look at  @marcosmarxm @alafanechere

**Comment by rytis-molecule** [comment]
@octavia-squidington-iii @Diana-Vait could anyone help me with this?

**Comment by marcosmarxm** [comment]
duplicated of https://github.com/airbytehq/airbyte/issues/34282
