### ISSUE TITLE
Destination BigQuery: temporary tables are not deleted

### ISSUE THREAD

**Issue by keurcien** [airbytehq/airbyte#31660]
### Connector Name

destination-bigquery

### Connector Version

2.1.5

### What step the error happened?

Other

### Relevant information

Temporary tables are created in the `airbyte_internal` dataset when the sync runs, but are not deleted after the sync completes.

### Contribute

- [X] Yes, I want to contribute

**Comment by keurcien** [comment]
Sorry, maybe I have not been clear enough. I know the `airbyte_internal` dataset stores the raw data, from which are derived the "final" tables. I was actually talking about the temporary tables used to generate these raw tables (see below). Few days after our migration to Destination v2, I had hundreds of these tables in the `airbyte_internal` dataset, along with the final "raw data".

<img width="461" alt="Capture d’écran 2023-10-26 à 15 17 09" src="https://github.com/airbytehq/airbyte/assets/11570911/0ffc8824-1e5d-4d80-86da-9c518f90633d">

I was expecting to have only this "raw" data in the `airbyte_internal` schema:

<img width="495" alt="Capture d’écran 2023-12-05 à 22 41 57" src="https://github.com/airbytehq/airbyte/assets/11570911/80804893-34a7-4750-bd48-8e01bda3ef5d">

Is this normal? If it is, it is kinda problematic because I can't imagine how much storage it is going to cost in the long run.

**Comment by evantahler** [comment]
Thanks for the clarification! Yes... those raw tables _should_ be removed.  Can you confirm that:
1. Your syncs are all succeeding.  
2. What version of the Airbyte platform you are using.  
3. What version of the destination-biguery connector you are using (still 2.1.5?). Have you tried the latest version (2.3.17)?

**Comment by evantahler** [comment]
Grooming Note:

We should be deleting all tmp tables which remain in `airbyte_internal` at the conclusion of a successful sync.

**Comment by keurcien** [comment]
> Thanks for the clarification! Yes... those raw tables _should_ be removed. Can you confirm that:
> 
> 1. Your syncs are all succeeding.
> 2. What version of the Airbyte platform you are using.
> 3. What version of the destination-biguery connector you are using (still 2.1.5?). Have you tried the latest version (2.3.17)?

1. Yes all syncs were successful.
2. Airbyte version: 0.50.33
3. Destination BigQuery 2.1.5. Will try to update the connector by the end of the week!

**Comment by keurcien** [comment]
I updated the destination connector to the latest version 2.3.8 and confirm that we observe the same behaviour (I reset the connection before syncing).

<img width="412" alt="Capture d’écran 2023-12-07 à 15 04 19" src="https://github.com/airbytehq/airbyte/assets/11570911/7ccda394-72e4-45a6-b520-ca84cf273432">

**Comment by jbfbell** [comment]
Think this is [the line](https://github.com/airbytehq/airbyte/blob/49043b570f699879e2c7bf4fb6b15312c685c365/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/uploader/BigQueryUploaderFactory.java#L61) that is creating the temp tables

**Comment by evantahler** [comment]
@jbfbell please link the PR and new version of the connector that has the fix.

**Comment by jbfbell** [comment]
[PR](https://github.com/airbytehq/airbyte/pull/33697)

Destination BigQuery Version [2.3.24](https://hub.docker.com/layers/airbyte/destination-bigquery/2.3.24/images/sha256-e2cba0f17dd8d213bde12886537c60944f4e4703599fd614e3b341c62a1302c9?context=explore)
