### ISSUE TITLE
Source Connector for FreshService

### ISSUE THREAD

**Issue by saneel-bidaye** [airbytehq/airbyte#3167]
## Tell us about the new integration you’d like to have
* Which source and which destination? 
   Freshservice source  & Redshift destination
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

https://api.freshservice.com/v2/

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case. 

IT team. FreshService is our helpdesk ticketing application.  There is a significant lack of capability on reporting within the templates that are provided in Freshserivce.  We are interested in analyzing our data to better understand what our top issues /requests are.

* How often do you want to run syncs?

Daily

* If this is an API source connector, which entities/endpoints do you need supported?
https://api.freshservice.com/v2/
* "List All Tickets": https://api.freshservice.com/v2/#view_all_ticket
* "View A Ticket": https://api.freshservice.com/v2/#view_a_ticket

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

Build a python based http conenctor

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368228626142) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@saneel-bidaye thanks for the request! Would you be interested in creating this connector using the [Python CDK](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/bases/base-python)?

Feel free to join the "airbyte_cdk" channel on our [Slack](slack.airbyte.io) or respond here and we can get started!

**Comment by grebessi** [comment]
## Integration Vetting

**Webhook-based? (no/partially/yes)**
no

**Available authentication modes (API key/Oauth/other)**
API Key/Basic Authentication

**Creating an account**
Self service paid account available. It is $19.00 per month. (There is a free account, but it only lasts for 21 days).

**How to populate the account with data?**
I think we'll need to create some fake users and simulate events for them through the UI.

**Available streams for sync**
Full list available in the API docs https://developers.freshdesk.com/api/

**Do any streams support incremental sync?**
Most of them yes. There are cases where the filter params do not have incremental fields.

**Comment by YowanR** [comment]
Closing as this connector was already released
