### ISSUE TITLE
Add Enterprise badges

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#31672]
### Topic

Add badge to Enterprise instances

Mocks: https://www.figma.com/file/MxkoXZ0UwQN12tSSnCrra0/Design-system?type=design&node-id=46%3A4258&mode=design&t=h8yY4g6q4nrf1k6V-1

### Relevant information

Display on Enterprise login page:
![Frame 8 11 21 00 AM](https://github.com/airbytehq/airbyte/assets/146028830/1fbfda16-07dc-4282-92b4-e037e70c9296)

And in the sidebar under the Airbyte logo:
![Frame 10](https://github.com/airbytehq/airbyte/assets/146028830/7c3d5021-8e15-4e42-8b44-3e1a05d90779)

**Comment by josephkmh** [comment]
Refining notes:
- Only necessary to show this in the sidebar for now, since it's pretty difficult to style the keycloak login page
