### ISSUE TITLE
Version mismatch between 0.22.0-alpha and 0.22.0-alpha

### ISSUE THREAD

**Issue by tuanchris** [airbytehq/airbyte#3168]
## Expected Behavior
* Airbyte should boot up normally without error. 

## Current Behavior
* Restarting server running Airbyte version 0.22.0-alpha leads to version mismatch error.

## Logs
```json
{"error":"Version mismatch between 0.22.0-alpha and 0.22.0-alpha.\nPlease upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte"}
```

## Steps to Reproduce
1. Create a VM Google Compute Engine
2. Have the script below as metadata_startup_script. The UI works fine for the first time the instance startup.
3. Reboot the instance and was met with the error above. 

Startup script:
```bash
#! /bin/bash
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add --
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -a -G docker $USER

sudo apt-get -y install wget
sudo wget https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m) -O /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version

cd
if [[ ! -e airbyte ]]; then
    git clone https://github.com/airbytehq/airbyte.git
elif [[ ! -d airbyte ]]; then
    echo "airbyte already exists but is not a directory" 1>&2
fi
cd airbyte
docker-compose up -d

EOF
```

## Severity of the bug for you
Critical

## Airbyte Version
0.22.0-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
GCE instance running on Ubuntu 20, e2-medium instance

**Comment by marcosmarxm** [comment]
@tuanchris thanks for reporting this! I had the same issue deploying locally
