### ISSUE TITLE
Tutorial to deploy Airbyte on Azure VM

### ISSUE THREAD

**Issue by geekwhocodes** [airbytehq/airbyte#3170]
## Tell us about the documentation you'd like us to add or update
I saw tutorial available to deploy Airbyte on different cloud providers, it would be great if we have tutorial to deploy Airbyte on Azure too.

## Are there any related areas of documentation that currently exist? Could you point to them? 
https://docs.airbyte.io/deploying-airbyte

**Comment by marcosmarxm** [comment]
thanks for opening this and already create PR #3171. I'll close as duplicated and we keep the discussion on #1367
