### ISSUE TITLE
Update BigQuery and Snowflowke test/secret configs to remove references of `use_1s1t_format` property when removed from actual spec

### ISSUE THREAD

**Issue by gisripa** [airbytehq/airbyte#31720]
Integration tests still have `use_1s1t_format` populated where as the actual spec does not having it leading to disparity in the actual code run vs code run in integration tests.   We need to remove this from the configs in Google Secret Manager.

A recent P0 because of this https://github.com/airbytehq/airbyte/pull/31717

**Comment by evantahler** [comment]
Thanks @gisripa! 

I /think/ that there aren't any functional uses in the codebase https://github.com/search?q=repo%3Aairbytehq%2Fairbyte%20use_1s1t_format&type=code

**Comment by evantahler** [comment]
Grooming:
* We could make it so that the strongly-typed Java object representing the JSON config should only include properties present in _this version's_ SPEC.  The JSON can keep old properties (e.g. for rollbacks), but in Java they won't be available.
