### ISSUE TITLE
Implement Orchestrator suicide

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#31732]
When the orchestrator fails to heartbeat, it needs to terminate in order to stop the sync.

In order to have an error message as explicit as possible, we need to create a new Exception specific to the workload heartbeat failure. This exception needs to be thrown if the workload status is not canceled.
If the workload status is not CANCELLED, the workload status needs to be updated to FAILURE and the returned failure reason needs to be updated accordingly (in the `ReplicationWorker.kt`)

**Comment by davinchia** [comment]
If code is too messy, we might want to centralise Source/Destination heartbeat killing with this.
