### ISSUE TITLE
Specify a specific date / date range in the job history

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#31754]
We've gotten some feedback on how we can improve navigation of the job history to enable looking at specific jobs in the past:

> It would be great if we could jump to a specific date. For connections that sync hourly or even more frequently, it’s very difficult to find a specific sync from even a week ago if you don’t know the job id. It would actually be helpful to be able to search or filter for specific jobs (resets, failed syncs, partial successes) too

**Comment by josephkmh** [comment]
Refining notes:
- Backend appears to already have filters for dates, so this might already be possible without any backend work

**Comment by nataliekwong** [comment]
Yay!!

**Comment by cynthiaxyin** [comment]
I just noticed this in cloud, this is great! It's something I brought up recently in Connector OC Retrospective, cc @bnchrch (my use case was I had to scroll far down to find bad syncs in order to write up a postmortem). Thanks @josephkmh!
