### ISSUE TITLE
Audit sources with multiple primary keys and confirm that this is representative 

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#31757]
From https://docs.google.com/document/d/1pIUwLiVrg4HwmynZuosinJjJA6mZ8ENUnJLqOqMdOQo/edit 

These sources have streams with multiple PKs, but they are not always non-null.  How can that be?  Is this intended to be a composite PK? 

* Facebook Marketing
* Google Ads
* Mixpanel

Report the results of this audit on https://github.com/airbytehq/airbyte/issues/31758

**Comment by lazebnyi** [comment]
For Facebook Marketing we have multiple PK for insights streams - `["date_start", "account_id", "ad_id"] + self.breakdowns` and look like sometimes Facebook can return None for those fields. For example `action_type` is breakdown field for `AdsInsightsActionType` and we expect that Facebook must return it as non-null value. 

The same logic for Google Ads. We have multiple PK for streams with field that must be present in records. 


For Mixpanel we have only two streams with multiple PK: 

Export (export events data) - ["distinct_id", "event", "time"]
Funnels (return list of funnels) - ["funnel_id", "date"]

And it look like all field must be non-null value. So, may be present unexpected bug from Mixpanel side.

**Comment by bnchrch** [comment]
Resolved as of https://github.com/airbytehq/airbyte/issues/31758
