### ISSUE TITLE
Database credentials are logged in plain text

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#3177]
## Expected Behavior
Credentials should be masked

## Current Behavior
Currently source DB credentials are printed in plain text (checked with PGSQL)
isCdc config: {"ssl":false,"host":"localhost","port":3106,"database":"mydb","password":"myPass","username":"someUser"}

## Steps to Reproduce
1. Set up a PGSQL source
1. Start syncing

## Severity of the bug for you
High

## Airbyte Version
0.22.0-alpha

## Connector Version (if applicable)
Postgres 0.3.1

**Comment by jrhizor** [comment]
Thanks for bringing this to our attention. 

I made a [PR](https://github.com/airbytehq/airbyte/pull/3179) to fix this that we'll get merged today. After that's merged, upgrading to the newest version of the Postgres source will fix the problem.

I also created an [issue](https://github.com/airbytehq/airbyte/issues/3181) to make sure we automate detecting cases like this in the future.

**Comment by jrhizor** [comment]
Should be ready to go if you upgrade your connector in the admin panel of the UI @akoshterek
