### ISSUE TITLE
Java represenations of Configs only include current SPEC properties (+strong types)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#31795]
We could make it so that the strongly-typed Java object representing the JSON config should only include properties present in this version's SPEC. The JSON can keep old properties (e.g. for rollbacks), but in Java they won't be available.

We would have a new Spec object per connector, e.g. `BigQueryDestinationConfig < AirbyteConnectorConfg (AirbyteteSpec)`. 

This would have prevented https://github.com/airbytehq/airbyte/pull/31717 which would have been caught because the property was removed from the connector's spec.  Also, we hate JSON nodes.

Phase 1 Deliverables:
* Add this to v2 destinations to start
* Write a plan to add this to all other destinations + sources. 

Implementation:
* This should happen magically from the spec
* Check out how the platform APIs work - building interfaces from YAMLs/jsons

**Comment by evantahler** [comment]
@gisripa It looks like you've got a PR ready for BigQuery. Please write up a companion story for Snowflake and Redshift as well, since it looks like there needs to be per-connector work done for each implementation

**Comment by gisripa** [comment]
We will split this into individual destination tickets. We had to rollback Bigquery due to a p0 due to misrepresentation of test json.
