### ISSUE TITLE
Freshdesk sync fails when destination normalisation is turned on

### ISSUE THREAD

**Issue by apostoltego** [airbytehq/airbyte#3180]
## Expected Behavior

Freshdesk data should land in the destination and be normalised

## Current Behavior
The sync currently fails throwing an IndexError. 

## Logs

2021-05-03 11:06:36 ERROR (/tmp/workspace/156/0) LineGobbler(voidCall):69 - File "/usr/local/lib/python3.7/site-packages/normalization/transform_catalog/stream_processor.py", line 238, in extract_column_names
2021-05-03 11:06:36 ERROR (/tmp/workspace/156/0) LineGobbler(voidCall):69 - if field in self.cursor_field[0] or field in [f[0] for f in self.primary_key if len(f) == 1]:
2021-05-03 11:06:36 ERROR (/tmp/workspace/156/0) LineGobbler(voidCall):69 - IndexError: list index out of range

## Steps to Reproduce
1. Create a freshdesk source
2. Create a postgres destination with normalisation turned on
3. Use the configured catalog below

## Severity of the bug for you
Medium

## Airbyte Version
0.19.0-alpha

## Connector Version (if applicable)

Freshdesk: 0.2.1
Postgres: 0.2.4

## Additional context
Configured catalog: 

        {
	        "streams": [{
		        "stream": {
			        "name": "freshdesk_agents",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "type": {
						        "type": "string"
					        },
					        "contact": {
						        "type": "object",
						        "properties": {
							        "name": {
								        "type": "string"
							        },
							        "email": {
								        "type": "string"
							        },
							        "phone": {
								        "type": ["string", "integer", "null"]
							        },
							        "active": {
								        "type": "boolean"
							        },
							        "mobile": {
								        "type": ["string", "integer", "null"]
							        },
							        "language": {
								        "type": "string"
							        },
							        "job_title": {
								        "type": ["string", "null"]
							        },
							        "time_zone": {
								        "type": "string"
							        },
							        "created_at": {
								        "type": "string"
							        },
							        "updated_at": {
								        "type": "string"
							        },
							        "last_login_at": {
								        "type": ["string", "null"]
							        }
						        }
					        },
					        "available": {
						        "type": "boolean"
					        },
					        "signature": {
						        "type": ["string", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "occasional": {
						        "type": "boolean"
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "ticket_scope": {
						        "type": "integer"
					        },
					        "last_active_at": {
						        "type": ["string", "null"]
					        },
					        "available_since": {
						        "type": ["string", "null"]
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_companies",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "name": {
						        "type": "string"
					        },
					        "note": {
						        "type": ["string", "null"]
					        },
					        "domains": {
						        "type": "array",
						        "items": {
							        "type": "string"
						        }
					        },
					        "industry": {
						        "type": ["string", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "description": {
						        "type": ["string", "null"]
					        },
					        "account_tier": {
						        "type": "string"
					        },
					        "health_score": {
						        "type": ["number", "null"]
					        },
					        "renewal_date": {
						        "type": ["string", "null"]
					        },
					        "custom_fields": {
						        "type": "object"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_contacts",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "name": {
						        "type": "string"
					        },
					        "email": {
						        "type": "string"
					        },
					        "phone": {
						        "type": ["string", "integer", "null"]
					        },
					        "active": {
						        "type": "boolean"
					        },
					        "mobile": {
						        "type": ["string", "integer", "null"]
					        },
					        "address": {
						        "type": ["string", "null"]
					        },
					        "language": {
						        "type": "string"
					        },
					        "job_title": {
						        "type": ["string", "null"]
					        },
					        "time_zone": {
						        "type": "string"
					        },
					        "company_id": {
						        "type": ["integer", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "twitter_id": {
						        "type": ["integer", "null"]
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "csat_rating": {
						        "type": ["integer", "null"]
					        },
					        "description": {
						        "type": ["string", "null"]
					        },
					        "facebook_id": {
						        "type": ["integer", "null"]
					        },
					        "custom_fields": {
						        "type": "object"
					        },
					        "preferred_source": {
						        "type": "string"
					        },
					        "unique_external_id": {
						        "type": ["integer", "null"]
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_conversations",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "body": {
						        "type": "string"
					        },
					        "source": {
						        "type": "integer"
					        },
					        "private": {
						        "type": "boolean"
					        },
					        "user_id": {
						        "type": "integer"
					        },
					        "category": {
						        "type": "integer"
					        },
					        "incoming": {
						        "type": "boolean"
					        },
					        "body_text": {
						        "type": "string"
					        },
					        "cc_emails": {
						        "type": ["array", "null"]
					        },
					        "ticket_id": {
						        "type": "integer"
					        },
					        "to_emails": {
						        "type": ["array", "null"]
					        },
					        "bcc_emails": {
						        "type": ["array", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "from_email": {
						        "type": ["string", "null"]
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "attachments": {
						        "type": ["array", "null"]
					        },
					        "support_email": {
						        "type": ["string", "null"]
					        },
					        "source_additional_info": {
						        "type": ["object", "null"]
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_groups",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "name": {
						        "type": "string"
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "group_type": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "description": {
						        "type": "string"
					        },
					        "escalate_to": {
						        "type": ["integer", "null"]
					        },
					        "unassigned_for": {
						        "type": ["string", "null"]
					        },
					        "business_hour_id": {
						        "type": ["integer", "null"]
					        },
					        "auto_ticket_assign": {
						        "type": "boolean"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_roles",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "name": {
						        "type": "string"
					        },
					        "default": {
						        "type": "boolean"
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "description": {
						        "type": "string"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_satisfaction_ratings",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "ratings": {
						        "type": "object"
					        },
					        "user_id": {
						        "type": "integer"
					        },
					        "agent_id": {
						        "type": "integer"
					        },
					        "feedback": {
						        "type": "string"
					        },
					        "group_id": {
						        "type": "integer"
					        },
					        "survey_id": {
						        "type": "integer"
					        },
					        "ticket_id": {
						        "type": "integer"
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_skills",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "name": {
						        "type": "string"
					        },
					        "rank": {
						        "type": "integer"
					        },
					        "agents": {
						        "type": "array",
						        "items": {
							        "type": "object",
							        "properties": {
								        "id": {
									        "type": "integer"
								        }
							        }
						        }
					        },
					        "conditions": {
						        "type": "array",
						        "items": {
							        "type": "object",
							        "properties": {
								        "value": {
									        "type": "array",
									        "items": {
										        "type": "string"
									        }
								        },
								        "operator": {
									        "type": "string"
								        },
								        "field_name": {
									        "type": "string"
								        },
								        "resource_type": {
									        "type": "string"
								        }
							        }
						        }
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "match_type": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_surveys",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "title": {
						        "type": "string"
					        },
					        "active": {
						        "type": "boolean"
					        },
					        "questions": {
						        "type": "array",
						        "items": {
							        "type": "object",
							        "properties": {
								        "id": {
									        "type": "string"
								        },
								        "label": {
									        "type": "string"
								        },
								        "default": {
									        "type": "boolean"
								        },
								        "accepted_ratings": {
									        "type": "array",
									        "items": {
										        "type": "integer"
									        }
								        }
							        }
						        }
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_tickets",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "spam": {
						        "type": "boolean"
					        },
					        "tags": {
						        "type": "array"
					        },
					        "type": {
						        "type": "string"
					        },
					        "due_by": {
						        "type": "string"
					        },
					        "source": {
						        "type": "integer"
					        },
					        "status": {
						        "type": "integer"
					        },
					        "subject": {
						        "type": "string"
					        },
					        "group_id": {
						        "type": ["integer", "null"]
					        },
					        "priority": {
						        "type": "integer"
					        },
					        "cc_emails": {
						        "type": "array"
					        },
					        "fr_due_by": {
						        "type": "string"
					        },
					        "nr_due_by": {
						        "type": ["string", "null"]
					        },
					        "to_emails": {
						        "type": ["array", "null"],
						        "items": {
							        "type": "string"
						        }
					        },
					        "company_id": {
						        "type": ["integer", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "fwd_emails": {
						        "type": "array"
					        },
					        "product_id": {
						        "type": ["integer", "null"]
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "description": {
						        "type": "string"
					        },
					        "fr_escalated": {
						        "type": "boolean"
					        },
					        "is_escalated": {
						        "type": "boolean"
					        },
					        "nr_escalated": {
						        "type": "boolean"
					        },
					        "requester_id": {
						        "type": "integer"
					        },
					        "responder_id": {
						        "type": "integer"
					        },
					        "custom_fields": {
						        "type": "object"
					        },
					        "email_config_id": {
						        "type": ["integer", "null"]
					        },
					        "reply_cc_emails": {
						        "type": "array"
					        },
					        "association_type": {
						        "type": ["integer", "null"]
					        },
					        "description_text": {
						        "type": "string"
					        },
					        "ticket_cc_emails": {
						        "type": "array"
					        },
					        "associated_tickets_count": {
						        "type": ["integer", "null"]
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }, {
		        "stream": {
			        "name": "freshdesk_time_entries",
			        "json_schema": {
				        "type": "object",
				        "$schema": "http://json-schema.org/draft-07/schema#",
				        "properties": {
					        "id": {
						        "type": "integer"
					        },
					        "note": {
						        "type": "string"
					        },
					        "agent_id": {
						        "type": "integer"
					        },
					        "billable": {
						        "type": "boolean"
					        },
					        "ticket_id": {
						        "type": "integer"
					        },
					        "company_id": {
						        "type": ["integer", "null"]
					        },
					        "created_at": {
						        "type": "string"
					        },
					        "start_time": {
						        "type": "string"
					        },
					        "time_spent": {
						        "type": "string"
					        },
					        "updated_at": {
						        "type": "string"
					        },
					        "executed_at": {
						        "type": "string"
					        },
					        "timer_running": {
						        "type": "boolean"
					        }
				        }
			        },
			        "supported_sync_modes": ["incremental"],
			        "source_defined_cursor": true,
			        "default_cursor_field": [],
			        "source_defined_primary_key": []
		        },
		        "sync_mode": "incremental",
		        "cursor_field": [],
		        "destination_sync_mode": "append_dedup",
		        "primary_key": [
			        ["id"]
		        ]
	        }]
        }

**Comment by ChristopheDuong** [comment]
This exception seemed to be fixed in here:
https://github.com/airbytehq/airbyte/pull/2776/

**Comment by ChristopheDuong** [comment]
The freshdesk source is defining a source defined cursor but never shares what the cursor actually is in the catalog.json:
(other source connectors may do the same btw)

"source_defined_cursor": true,
(...)
"cursor_field": [],

So when normalizaiton is trying to use the cursor field for deduping, it failed to do so and crashed.

The exception should now be fixed in normalization but it would default to the `_airbyte_emitted_at` column... which might not be the correct answer.

Solutions:
1. The UI should probably let the user (re)define a cursor field even if it's marked as `source_defined_cursor` so normalization can use that info to dedupe
2. the source should share what is the actual cursor field even if `"source_defined_cursor": true`

**Comment by sherifnada** [comment]
@ChristopheDuong easiest fix is to do no.2 for now. Will prioritize

**Comment by apostoltego** [comment]
@sherifnada  confirming that upgrading to 0.22.0 fixed this particular problem. 

The problems arising after are different and raised here #3252
