### ISSUE TITLE
Improve `<StreamDetailsPanel />` update  implementation

### ISSUE THREAD

**Issue by dizel852** [airbytehq/airbyte#31820]
### Topic

`<StreamDetailsPanel />`

### Relevant information

In the current implementation of `<StreamDetailsPanel />`, each change of stream properties (such as enabling/disabling fields, changing the cursor, or modifying the primary key) triggers an immediate update of syncCatalog(table behind the `<StreamDetailsPanel />`) and extra rerender.

To prevent this behavior, it would be great to collect all the changes we'd like to make to the stream and then apply them all upon closing.

![CPT2310251711-861x666](https://github.com/airbytehq/airbyte/assets/20929344/16a6561d-d632-448d-bcfb-9eb859c42143)

**Comment by josephkmh** [comment]
Refining notes:
- We should think about navigation blocking if we use a second form. Navigation blocking probably currently only works with a single form on the page.
- Probably not worth rewriting form change tracker and/or modal service to allow for multiple forms/modals on this page. We can use the existing conditional rendering of the stream details panel.
