### ISSUE TITLE
Require GL review for silver+ python connectors

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#31827]
## What

We currently have a required review from GL on GA connectors. Aside from moving away from release stages and into support/quality levels, we've received a request from @katmarkham to require GL's review for silver connectors, as GL has most context on these and we're receiving more contributions from other contributors external to GL.

As part of this we should make sure we only do this if it's a python source connector.

In addition, it's been noted that it's easy to skip over the required review check. It currently shows up as a "pending" status check if required reviewers haven't approved, and it is not marked as a required check.

We can swap the status to report as "failed" rather than "pending" so that it's more obvious, while keeping it to non-required to give engineers the autonomy to decide to skip it without having to /approve-and-merge.

**Comment by evantahler** [comment]
Grooming

* Remove our checks from "release stage" to "quality level".  The mandatory reviews check today probably looks at all connectors (vs just python ([slack](https://airbytehq-team.slack.com/archives/C03VDJ4FMJB/p1698252633835269)))
* Be sure to add this only for python connectors
* Review checks that aren't done yet should be red not yellow
