### ISSUE TITLE
Sync on breaking change improvements

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#31841]

**Comment by erohmensing** [comment]
We synced on this and added our feedback to Natalie's doc [here](https://docs.google.com/document/d/1GNZyRacvNY1nZ1t6Y-_zR0pwbzoS3TtFi-uQfjz4fY4/edit). After talking to @evantahler, I think this doc (and Alex C's, and probably more) are probably input to a connector ops tech spec before working on the improvements next demiquarter... but for the sakes of this action item I think it is achieved!

Will leave @katmarkham to confirm and close
