### ISSUE TITLE
[source-mysql] Incremental Append / Incremental Sync - Append + Deduped options aren't there when using mysql - view as a source

### ISSUE THREAD

**Issue by sudh33ra-c** [airbytehq/airbyte#31859]
### Connector Name

source-mysql-community

### Connector Version

3.0.8

### What step the error happened?

Configuring a new connector

### Relevant information

<img width="773" alt="Screenshot 2023-10-26 at 2 01 22 PM" src="https://github.com/airbytehq/airbyte/assets/103478971/50207cd0-0776-41ca-bca4-481bad2dff14">

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Please update to the latest connector version for both source and destination. If the problem continues, open a new issue and tell us your destination.
