### ISSUE TITLE
Source S3: Add IAM Role Authentication

### ISSUE THREAD

**Issue by tolik0** [airbytehq/airbyte#31865]
### What area the feature impact?

Connectors

### Background:
The S3 connector, implemented using the AWS Python SDK (Boto3), currently supports authentication through access and secret keys. In many AWS environments that prioritize security and manageability, IAM roles are often preferred over static access keys for granting permissions to resources.

### Objective:
Enhance the S3 connector source to support IAM role-based authentication, allowing users to utilize IAM roles for more granular control over permissions and to eliminate the need for managing static access keys.

### References:
[AWS IAM Roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html)
[Boto3 Credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#aws-iam-identity-center)

**Comment by AmareshB** [comment]
Hi team,

Any updates on this? 
We are planning to write data into s3 as well and would love to have role based authentications.

**Comment by tolik0** [comment]
@AmareshB We are actively working on this issue. I'll make sure to keep you updated and let you know once it's ready for use.

**Comment by tolik0** [comment]
Move to "On Hold" while awaiting further guidance from @wennergr regarding the procedure for accessing Airbyte's AWS credentials to establish the IAM role trust relationship.

**Comment by therji-motif** [comment]
I saw this was removed from the documentation recently: https://github.com/airbytehq/airbyte/pull/35190

Is this feature rolled back?
