### ISSUE TITLE
Add Segment event: failed to discover schema

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#31892]
We have a gap in our activation metrics: we don't track how often people run into this while setting up a connection.

We have Connections.New, but nothing is triggered if a user gets to this page. We should track this, especially by source, to understand why people aren't making it to Connection creation.

We are tracking this in Fullstory via a watched element, but this doesn't give us visibility into the source and historical reporting.

![Screenshot 2023-10-26 at 12 36 37 PM](https://github.com/airbytehq/airbyte/assets/38087517/06d0039b-25d8-4040-96bc-631db29759ac)

For reference, here is the documentation we have on existing Segment events: https://docs.google.com/spreadsheets/d/1lGLmLIhiSPt_-oaEf3CpK-IxXnCO0NRHurvmWldoA2w/edit#gid=1043472212

**Comment by josephkmh** [comment]
Refining notes:
- Attach as much auxiliary info as possible (`sourceId`, `destinationId`, etc)
