### ISSUE TITLE
Slack Webhook "Webhook test failed. Please verify that the webhook URL is valid."

### ISSUE THREAD

**Issue by iciric** [airbytehq/airbyte#31902]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

Airbyte version 0.50.7

### What step the error happened?

Other

### Revelant information

I was testing slack webhooks in airbyte and got an error - `Webhook test failed. Please verify that the webhook URL is valid.`
I'm sure the webhook is valid because we're still getting the alerts when connections fail. After some investigation I found this github issue saying that there are problems with this on some airbyte version, more particular our version 0.50.7 :sweat_smile: https://github.com/airbytehq/airbyte/issues/25007
this is preventing us from adding the new webhook because we're not able to save changes in case the test fails - `Cannot save changes because the webhook test failed.` Please verify that the webhook URL is valid.
There are multiple people complaining on official Airbyte Slack channel about hook test not working on this version and it seems there isn't any resolution on this issue.

**Comment by josephkmh** [comment]
@iciric can you upgrade to v0.50.8 or newer and let us know if you are still facing this issue?

**Comment by josephkmh** [comment]
I'm going to close this, because as far as I can tell upgrading to v0.50.8 will fix this issue. A similar report was made here: https://github.com/airbytehq/airbyte/issues/25007#issuecomment-1805338388 

Please feel free to reopen if your issue is not resolved!
