### ISSUE TITLE
Cannot reach server. The server may still be starting up.

### ISSUE THREAD

**Issue by MC1-RicardoLeka** [airbytehq/airbyte#3191]
Hi All,

After a blue screen on my Windows 10, when I restart the airbyte, on the web interface he was stuck with:
"Cannot reach server. The server may still be starting up."

on the shell looks like he is stuck on the same thing:
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobRetrier(run):58 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running Job Retrier...
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobRetrier(run):74 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job Retrier...
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobRetrier(run):75 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Retrier Summary. Incomplete jobs: 0, Job set to retry: 0, Jobs set to failed: 0
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobScheduler(run):81 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-scheduler...
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobScheduler(scheduleSyncJobs):103 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job-Scheduler Summary. Active connections: 1, Jobs scheduler: 0
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobScheduler(run):85 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Scheduler...
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobSubmitter(run):66 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-submitter...
airbyte-scheduler   | 2021-05-03 21:08:51 INFO i.a.s.a.JobSubmitter(run):76 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Submitter...

On the shell show´s a message:
 ERROR Version mismatch between 0.22.0-alpha and 0.22.0-alpha.
Please upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte

I already try startup just the "db" "server" and "webapp" but still the same issue.

**Comment by marcosmarxm** [comment]
hey @MC1-RicardoLeka thanks for reporting this, actually we're working to solve this error. PR #3169 solves this and we're releasing a patch version soon.

**Comment by MC1-RicardoLeka** [comment]
> hey @MC1-RicardoLeka thanks for reporting this, actually we're working to solve this error. PR #3169 solves this and we're releasing a patch version soon.

Tnks !

**Comment by wtdwang** [comment]
@johnlafleur I had this problem,This problem needs to be solved urgently.  I need help

**Comment by johnlafleur** [comment]
Hey @wtdwang! Did you upgrade to Airbyte's latest version, to benefit from the fix?
The best is to join our [Slack](https://slack.airbyte.io) and post on #issues to get the team to assist you.
