### ISSUE TITLE
Source MSSQL: Change automatic conversion of datetime to varchar in MSSQL destination database

### ISSUE THREAD

**Issue by martinbolco** [airbytehq/airbyte#31961]
### Relevant information

Hello. We have an issue when the Airbyte automatically converts data types in our mssql destination database (for example Datetime -> Varchar). 

I know that using custom dbt transformation is not possible in kubernetes deployment of the Airbyte. This is really show stopper for us. We were able to find this python script that we consider is responsible for conversion of types: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py and if I understand correctly, this is the container image used for normalization https://hub.docker.com/r/airbyte/normalization/ 

Is it correct? Our aim is to us use this image as base and change python code responsible for conversion. Is it possible? Is there easy way how to change the open source code to tell the Airbyte to keep datetime as datetime?

**Comment by nguyenaiden** [comment]
@martinbolco, datetime datatype conversion patch was recently shipped in `source-mssql:3.0.0`. Please reach out if it the problem still persists after the upgrade

**Comment by nguyenaiden** [comment]
@martinbolco This issue was fixed with `source-mssql:3.0.0`. Please reach out and open a new ticket if the problem persists.
