### ISSUE TITLE
Cannot upgrade from version 0.35.12-alpha to version 0.50.33 directly

### ISSUE THREAD

**Issue by shubhamqua** [airbytehq/airbyte#31992]
### Discussed in https://github.com/airbytehq/airbyte/discussions/31957

<div type='discussions-op-text'>

<sup>Originally posted by **shubhamqua** October 30, 2023</sup>
I am trying to upgrade Airbyte deployment from 0.35.12-alpha to latest version using helm charts, while trying to apply upgrades, I am getting the following error in airbyte-bootloader pod:
`2023-10-30 07:50:39 ERROR i.a.b.Bootloader(assertNonBreakingMigration):148 - Cannot upgrade from version 0.35.12-alpha to version 0.50.33 directly. First you must upgrade to version 0.37.0-alpha. After that upgrade is complete, you may upgrade to version 0.50.33.
2023-10-30 07:50:39 ERROR i.a.b.Application(main):25 - Unable to bootstrap Airbyte environment.
java.lang.RuntimeException: Cannot upgrade from version 0.35.12-alpha to version 0.50.33 directly. First you must upgrade to version 0.37.0-alpha. After that upgrade is complete, you may upgrade to version 0.50.33.`

Can someone tell me how can i upgrade to the latest verion.? I tried using helm command:
`helm upgrade airbyte airbyte/airbyte -f Values_org_airbyte.yaml --version 0.37.0-alpha --debug`

but it looks like there is no chart present with that version in the helm repo:
`Error: chart "airbyte" matching 0.37.0-alpha not found in airbyte index. (try 'helm repo update'): no chart version found for airbyte-0.37.0-alpha
helm.go:84: [debug] no chart version found for airbyte-0.37.0-alpha`

I also confirmed the same using:
`helm search repo airbyte --versions | grep 0.37.0-alpha`

Can someone please help me with this.??</div>

**Comment by shubhamqua** [comment]
@octavia-squidington-iii  Any updates on this.?

**Comment by marcosmarxm** [comment]
There are some required versions you **must upgrade** before going to 0.50.13
Also, always is good practice keep the version close to latest one.

**Comment by marcosmarxm** [comment]
Pay attention the Helm Chart version is different from the Platform version. You need to match the platform version and not the chart.
