### ISSUE TITLE
Add copy button for failure message stack trace

### ISSUE THREAD

**Issue by josephkmh** [airbytehq/airbyte#32007]
Right now the failure message on a failed attempt sometimes produces a very long log line:

![image](https://github.com/airbytehq/airbyte/assets/7550957/bbe84df3-9efc-4560-b9f8-a670656827e2)

(they can get much longer than this!)

We should consider adding a "Copy text" button so that it's easy for a user to extract the whole message. Alternatively, we could consider wrapping the error message so it's all visible at once. This might conflict with the rest of the UI.

**Comment by nataliekwong** [comment]
Rarely happens, but these can get quite long. Wrapping it without a row limit might end up most of the whole page.

**Comment by josephkmh** [comment]
Refining notes:
- We could get rid of "See more" and always show the internal error message
- A "Copy text" button could replace "See more"
