### ISSUE TITLE
DV2 BigQuery hitting rate limits during v1->v2 migration / sync startup

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#32003]
Consider this following [sync](https://cloud.airbyte.com/workspaces/b9f6df08-12b3-4e66-97fd-32909d201331/connections/714a0908-0a0f-43f0-ae81-b455fa9e045c/job-history#5611158::4) and related to https://github.com/airbytehq/oncall/issues/3462

It is failing to migrate from V1 to V2 Bigquery due to a mix of errors:
* `Caused by: com.google.cloud.bigquery.BigQueryException: Not found: Dataset xxx-analytics:airbyte_internal was not found in location EU`
* `Caused by: com.google.cloud.bigquery.BigQueryException: Exceeded rate limits: too many dataset metadata update operations for this dataset. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors at [1:1]`

It does appear that we are running multiple table migrations at the same time... maybe we really are hitting rate limits?

**Comment by jbfbell** [comment]
there aren't a ton of dataset specific quotas - my suspicion (to confirm) is that we are naively including the `CREATE SCHEMA` statement for the `airbyte_internal` dataset in each table migration and you can only do this [5 times every 10 seconds](https://cloud.google.com/bigquery/quotas#dataset_limits)

**Comment by jbfbell** [comment]
[confirmed](https://github.com/airbytehq/airbyte/blob/45505dd45c5772529931fe0889db644907304e6e/airbyte-integrations/connectors/destination-bigquery/src/main/java/io/airbyte/integrations/destination/bigquery/typing_deduping/BigQuerySqlGenerator.java#L786) so I think we should pull out this statement from each table migration and just run it once

**Comment by evantahler** [comment]
We can also load multiple CSVs into BQ at one (e.g. it takes an array for URIs) https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#sql

**Comment by evantahler** [comment]
Grooming:
* There are many places where we do `create if not exists ...` (migrations, full refresh, etc).  
* We should remove all  `create if not exists ` where we try to create the schemas from anything that can be threaded and do it once at the start of the sync.
