### ISSUE TITLE
Prepare and warm up redshift Dv2 early-access user group

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#32023]

**Comment by cynthiaxyin** [comment]
I think everyone is [accounted for](https://docs.google.com/spreadsheets/d/1tP9tkL4c90MnzqgE0Nff3q16lq0hOBr2K9JRbGvv7CU/edit#gid=1522533277) except for @jensiti's prospect who I don't see has filled out [the interest form](https://docs.google.com/forms/d/e/1FAIpQLSeb8OZDwwsNxqUwSItQvzgEXdaWG6_dDI4sS-avCHfCINkS3w/viewform).

**Comment by cynthiaxyin** [comment]
I also have the BQ beta email which we can update and re-use.

**Comment by evantahler** [comment]
Grooming: Let's email everyone now with a "coming soon" message to get they hyped and ready

**Comment by cynthiaxyin** [comment]
Doc for comms: https://docs.google.com/document/d/1mCXgipFV36tQtizzye8JqdhNX6R6vqA6Z6SadByGNqg/edit

**Comment by cynthiaxyin** [comment]
TODO: create a channel for beta users in the community Slack

**Comment by jbfbell** [comment]
- make private community channel in either slack workspace, invite someone (customer or internal) from other group
- will keep open for duration of q4b

**Comment by chrishronek** [comment]
Did ya'll create that channel? I would love an invite if you did.
