### ISSUE TITLE
Sort connector definitions alphabetically in admin UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3202]
## Tell us about the problem you're trying to solve
It would be easier to read connector definitions if they are alphabetically sorted in the admin UI

![image](https://user-images.githubusercontent.com/6246757/116949037-f34bb000-ac35-11eb-8419-0e74bcf7c4c5.png)

**Comment by sherifnada** [comment]
@cgardens fyi

**Comment by marcosmarxm** [comment]
@sherifnada https://github.com/airbytehq/airbyte/issues/3166 :( can i close as duplicated?

**Comment by sherifnada** [comment]
my bad, i didn't notice. closed.
