### ISSUE TITLE
Connector Ops Listening Tour (Survey)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#32030]
We should visit with all Connector Teams + GL and learn what their top pain points / requests are.   This will be input into our Q4/Q1 roadmaps.

* What can we do to speed you up?
* What do you spend the most the most time on?
* What annoys you the most?
* What can't you measure that you wish you could?
* How do you deploy and test your connectors?
* Do you think your job is easier than it was last year, or 6 months ago?

We should have an open-ended convo as to not pre-bias our users.  Then, we can share the spreadsheet and see if they agree with the stack-ranking

@bnchrch and @alafanechere did this recently with GL.  I'm most interested in what Sources and Destinations have to say.  The goal is to be able to produce a stack-ranked spreadsheet of issues based on pain for our connector developers.

**Comment by evantahler** [comment]
Results - https://docs.google.com/spreadsheets/d/1t1b-B5X-OH4jZZoJ-teyQ37Z5Vwx0P7oUcs_SZ3cDQc/edit#gid=1369209755

**Comment by alafanechere** [comment]
I curated responses. Considering this as done.
