### ISSUE TITLE
airbyte-ci: doesn't work when not on a branch

### ISSUE THREAD

**Issue by postamar** [airbytehq/airbyte#32067]
### Relevant information

When the repo is in a detached head state, airbyte-ci doesn't work.
I blame
```
@click.option("--git-branch", default=get_current_git_branch, envvar="CI_GIT_BRANCH")
```
where `get_current_git_branch` tries to resolve the current git branch.

I believe that this value and others like it should be evaluated lazily instead of eagerly.

**Comment by postamar** [comment]
Thanks @stephane-airbyte for bringing this up.

**Comment by erohmensing** [comment]
Merging into https://github.com/airbytehq/airbyte/issues/32196
