### ISSUE TITLE
Source-mysql : Db history topic missing

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#32066]
Context : https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1698687956584249

**Comment by akashkulk** [comment]
Notes : 
1. The first issue here seems to be that the mysql_db_history (schema history) field is empty. 
2. The second issue here is that reading the schema in SCHEMA_RECOVERY_MODE in the initial sync is empty for some reason, causing debezium to fail. 
3. Asking the debezium community, if returning an empty schema is expected in certain cases : https://debezium.zulipchat.com/#narrow/stream/348104-community-mysql/topic/SCHEMA_RECOVERY_MODE.20returning.20empty.20schema.20history

**Comment by teubanks** [comment]
I'm facing this same issue. Any updates or workarounds?

**Comment by nguyenaiden** [comment]
@teubanks, let me confirm a few things. Also are you on cloud? or are you on OSS? Please send me your connection if you're on cloud, or upload your sync logs here if you're on OSS so I can take a look at your issue.
