### ISSUE TITLE
airbyte-ci: add a DockerHub rate limit check before running pipelines

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#32089]
We occasionally face DockerHub rate limit on image pull in our `test` pipelines.
[We authentified our `dockerd`to Dockerhub with `docker login` but continue to face](https://github.com/airbytehq/airbyte/pull/31718/files#diff-d40249eb99e1032e94b872d433c46a4996c0e845a6af70929859ff548444bfb8R58):
```
{"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
```

[Failure example
](https://dagger.cloud/runs/5eabe3e0-5658-46ff-89ad-ac5690d389e8)

It's hard to understand if we've reached our DockerHub plan pull limit (5000 pulls per day) or if we did not perform a `docker login` at the right place.

I'd love a check before all `airbyte-ci` run on the CI that would immediately fail the workflow if our pull request limit is reached.
We can check our current consumption level with HTTP request to Dockerhub api:
https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/

**Comment by evantahler** [comment]
Grooming:
* The docker API is bad.
* Maybe we move to Amazon container service one day.
* Can we write to docker support?
