### ISSUE TITLE
Concurrent CDK: have source-salesforce full_refresh be concurrent

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#32099]
### What area the feature impact?

Connectors

### Context

We would like to reduce the duration of source read for source-salesforce. 

Why source-salesforce? The variety of streams is pretty low (hence we assume the complexity for concurrent is pretty low as well) and it is a critical connector that would benefit from being faster. Also, state is not per-partition which ease the incremental part later on.

Why only full_refresh? This is a first step for delivering value. Incremental first sync and all increment syncs should follow next. We have a couple of workspaces scheduling syncs periodically that would benefit from this:
```
prod-configapi=> select count(distinct(workspace_id)) from connection join jobs on connection.id::text = jobs.scope join actor on connection.source_id = actor.id join actor_definition on actor.actor_definition_id = actor_definition.id where actor_definition.id = 'b117307c-14b6-41aa-9422-947e34922962' and catalog::text not like '%"sync_mode": "incremental"%' and actor.tombstone = 'f' and connection.status = 'active' and schedule_type != 'manual' limit 10;
 count
-------
    12
(1 row)
```

### TODO
* Set up concurrency (see source-stripe for an example) when all streams are full_refresh 
    * During https://github.com/airbytehq/airbyte/issues/30950, we identified one part that is not thread safe and it's the writing/deleting of tmp files as their name may overlap. 
* Investigate how many workers would make sense
* Ensure throughput respect API rate limits (https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm)
    * This might not be important as the sliding window is quite big (24 hours). The current source just gives up when hitting `REQUEST_LIMIT_EXCEEDED`
    * The number of API calls varies depending on this instance of Salesforce the user has. Should we everyone has Enterprise Edition? The answer to the point above might render this point irrelevant if we just give up.

Progressive rollout at the dev's discretion

### Acceptance criteria
* [ ] source-salesforce in production is using concurrent CDK for full refresh syncs (**grooming question**: instead of checking for all stream to be full_refresh, can we be concurrent for each stream that is full refresh?)
* [ ] salesforce read duration is reduced

**Comment by girarda** [comment]
grooming notes:
- can use the facade when all streams are running in full refresh like we do in source-stripe 
- rate limit: need to make sure the rate limiting is enforced and the connector bails instead of waiting until the end of the day
- rate limit depends on the user's license. one option is to leave the limit high and bail on 429
  - we might also be able to get the limit from API responses
-  the source writes files to disk. running multiple partitions in parallel means we'll use more disk space. we should make sure this won't be an issue
