### ISSUE TITLE
Normalization should be configurable at the Connection-level instead of the Destination-level

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3209]
The boolean settings on the destination's settings page should be moved to the sync/connection page instead.

Additionally, when a stream is configured on the connection page with the sync mode "dedupe history", then basic normalization should be automatically enabled.

(or the UI shouldn't let the user select the dedup history sync mode if normalization is not enabled on this connection)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368164428277) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
This is the beginning of using Connections as a descriptor for steps orchestration. Can't wait to see where that leads us!

**Comment by cgardens** [comment]
done!
