### ISSUE TITLE
When setting up connection, if no schema to select, we shouldn't display the label

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#321]
## Expected Behavior
When setting a connection (last step), sometimes there might not be any schema displayed, in this case, we shouldn't display the label "Select the data you want to sync - You'll be able to change this later on".

## Current Behavior
Right now, we always display this label even if empty below. See screenshot. 

<img width="722" alt="Screen Shot 2020-09-17 at 11 55 04 AM" src="https://user-images.githubusercontent.com/68561602/93407742-9259ac80-f8de-11ea-8a15-f30803a37663.png">

**Comment by cgardens** [comment]
I think this was because there was an error. There should always be a schema of some sort. That bug should be fixed. Going to close this.
