### ISSUE TITLE
New source: Oracle Netsuite Analytics

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3212]
## Tell us about the new integration you’d like to have
We've received requests for integrating with [Oracle Netsuite Analytics](https://www.netsuite.com/portal/products/analytics.shtml). 

## Describe the context around this new integration
The use case described was getting financial transaction information from ONA and syncing it to Snowflake. The purpose is to reconcile financial transactions coming from different sources. 

## Describe the alternative you are considering or using
Using stitch data which currently supports this connector, but it has some shortcomings: 

* It does not always pick up updates. For example, when a charge is updated, its parent entity (invoice) cursor field (e.g: `updated_at`) is not always updated so the connector does not pick it up. 
* Netsuite allows overwriting all account information by uploading a CSV. When this happens, we'd like to mark previous records as deleted (if they were in fact deleted). Stitch does not currently provide this functionality. 

stitch connector: https://www.stitchdata.com/docs/integrations/saas/netsuite-suite-analytics

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368106162752) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
I've applied to Netsuite for a developer account

**Comment by GAV1N** [comment]
@sherifnada can you provide an update on the NetSuite source?

**Comment by sherifnada** [comment]
@GAV1N we anticipate scoping this soon! Would you be interested in a chat to understand your requirements for the Netsuite connector?

**Comment by GAV1N** [comment]
Thanks, @sherifnada. Unfortunately I don't have much to share in that regard just yet, as we haven't begun our NetSuite implementation. We're looking to do so this year, and so I'm factoring NetSuite connectivity into my evaluation of ETL/data integration tools. Thanks!

**Comment by JCWahoo** [comment]
@sherifnada  let me know if you want to chat on this... actively looking to replace Stitch

**Comment by tuliren** [comment]
Databricks told us today that they would like to have a Netsuite source connector. They may build one themselves if they decide to use Airbyte for data integration.

**Comment by MaxVTurcan** [comment]
Hi everyone. My team is investigating potential use of Airbyte. We need a Netsuite source connector though. Is there any progress on this new source? Thanks.

**Comment by misteryeo** [comment]
Hi folks, following this thread - we're planning to release an alpha of a Netsuite connector **latest** by September and will keep this issue updated.

**Comment by olvgrolle** [comment]
@bazarnov Baz - I have a question regarding closing this source request. 
An Oracle Netsuite Analytics connector is very different than a netsuite Rest API connector. 
Netsuite Analytics allows you to pull any data persisted in the Netsuite schema, while the REST API connector only allows to interrogate objects exposed by the rest API. 

A netsuite analytics connector is basically 'just' a jdbc connector - which feels like very straightforward to implement - and would get you the actual netsuite deep data access that cusotmers are looking for. 

Can you reconsider closing this source request? 
best regards,
Olv from Airship

**Comment by bazarnov** [comment]
@sherifnada @misteryeo @YowanR @lazebnyi 
Did we consider Netsuite had a JDBC implementation on their side while scoping was taking place? 

@olvgrolle Could you please provide us with more info and an official documentation link of its capabilities? Thanks!

**Comment by olvgrolle** [comment]
Absolutely: general documentation for SuiteAnalytics is at: https://www.netsuite.com/portal/products/analytics.shtml 

Netsuite Actual Docs always require a login into their system.

Here is the Netsuite Analytics JDBC driver that Netsuite provides:
[NetSuiteJDBCDrivers.zip](https://github.com/airbytehq/airbyte/files/10134173/NetSuiteJDBCDrivers.zip)

With examples embedded in the file. 
A jdbc connection string for this Netsuite source would look like: 

`jdbc:ns://<NetsuiteAccountID>.[connect.api.netsuite.com](http://connect.api.netsuite.com/):<port typically 1708>;ServerDataSource=[NetSuite2.com](http://netsuite2.com/);Encrypted=1;CustomProperties=(AccountID=<NetsuiteAccountID>;RoleID=<role of the user used for connecting>)`

Authentication then can be either database native with username  / password or Token Based. 

And some documentation attached as PDFs: 


[NetSuite Help Center-opensample.pdf](https://github.com/airbytehq/airbyte/files/10134184/NetSuite.Help.Center-opensample.pdf)
[NetSuite Help Center-sample.pdf](https://github.com/airbytehq/airbyte/files/10134185/NetSuite.Help.Center-sample.pdf)
[NetSuite Help Center-prop2'.pdf](https://github.com/airbytehq/airbyte/files/10134186/NetSuite.Help.Center-prop2.pdf)
[NetSuite Help Center-properties.pdf](https://github.com/airbytehq/airbyte/files/10134187/NetSuite.Help.Center-properties.pdf)
[NetSuite Help Center-access.pdf](https://github.com/airbytehq/airbyte/files/10134188/NetSuite.Help.Center-access.pdf)
[NetSuite Help Center.pdf](https://github.com/airbytehq/airbyte/files/10134189/NetSuite.Help.Center.pdf)

**Comment by bazarnov** [comment]
Also, I've found this one: https://docs.oracle.com/en/cloud/paas/analytics-cloud/acsds/connect-remote-data-using-generic-jdbc.html#GUID-93DD9541-37A8-4947-AF3E-BDF1E108A678

**Comment by olvgrolle** [comment]
Hi Baz,

That is though Oracle’s Analytics (not Oracle Netsuite Analytics) - which means an oracle database can connect to remote data sources via jdbc. (Which is of course true). 

What we are looking for is the Netsuite Analysitcs ability to be used as a Airbyte Source! (Via the Netsuite Analytics JDBC driver). 
Best regards,
Olv
