### ISSUE TITLE
Show summary on connections page

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#32121]
### Relevant information

We'd like to add a count of each status of connection on the top of the connections page. This is to give the user an at-a-glance idea of what's going on with their connections.

In addition, we'd like to add filters to the connections table so the user can quickly isolate connections by status, source, and destination.

[MOCKS](https://www.figma.com/file/nUvo0EgGBuShxYiFHEUXpE/Connections-page-summary?type=design&node-id=1%3A3&mode=design&t=cHxOHADrDl2kuNxO-1)
[Slack thread](https://airbytehq-team.slack.com/archives/C061M060RDE/p1698257649616659)

@nataliekwong Are there any other statuses you think would be helpful to show in the summary? Right now it's just active, failed, and paused for simplicity, but I know there are technically several more.

**Comment by chandlerprall** [comment]
> Right now it's just active, failed, and paused for simplicity, but I know there are technically several more.

The other status types are not currently available outside of the connection detail pages (status, job history, etc). "Failed" here unfortunately pushes that boundary already, many connections will show failed on /connections before they show the Error state on /status - that's an existing issue with this page and not something we'd be introducing with this design change.

**Comment by nataliekwong** [comment]
> We don't know what the changes are, but we do know if there are schema changes and/or breaking changes for each connection in the workspace on /connections. (https://airbytehq-team.slack.com/archives/C061M060RDE/p1698259739240169?thread_ts=1698257649.616659&cid=C061M060RDE)

I thought we had the ability to categorize if there are breaking changes or non-breaking changes here? I do think that it's weird to be able to filter for something you can't actually SEE on the page itself, so I'm okay leaving this out until we have the breaking change icons on /connections. 

Let's start with this for now and see if we get any feedback! When we launch, we can place a Chameleon somewhere on the page to see if we can get feedback.

**Comment by josephkmh** [comment]
Refining notes:
- We can probably reuse some of the UI for filtering the Job History tab by status/date

**Comment by nataliekwong** [comment]
Just turned this on for the internal workspaces! Love it 🙌 

A few minor things:
- Filtering for "Failed" gave me a paused connection whose last sync was failed. This is confusing, especially since the rollup at the top doesn't say I have any failed syncs
- "Clear all" is in red, but can it be in grey instead?

**Comment by alex-gron** [comment]
I love this too!! The filtering is awesome! 

One suggestion: It would be nice to see how many syncs are running
Example:
<img width="616" alt="Screenshot 2023-12-01 at 10 08 43 AM" src="https://github.com/airbytehq/airbyte/assets/109167606/47f81ed0-5fcc-47ef-a010-6ea488d3dbe9">

**Comment by AnilEMaharjan** [comment]
> * "Clear all" is in red, but can it be in grey instead?

Also, definitely agree with this comment

**Comment by nora-airbyte** [comment]
@chandlerprall Would we want to 

1) add a "Running" option to the status dropdown and 
2) make the "clear all" grey instead of red 
3) exclude paused connections with failed syncs from the "Failed" status filter

as part of this project? Or should we create a separate ticket for these updates.

**Comment by nataliekwong** [comment]
To address the suggestions around multi-select: we had a more recent[ Slack thread](https://airbytehq-team.slack.com/archives/C061M060RDE/p1700667165012909?thread_ts=1700578197.880089&cid=C061M060RDE) about this and I think @chandlerprall was going to try implementing it (maybe in a subsequent PR since it was after the original discussion!)

**Comment by chandlerprall** [comment]
Continuing with this same issue sounds good to me; the merged items are all behind a disabled flag so it feels like the same unit of work.

> To address the suggestions around multi-select: we had a more recent[ Slack thread](https://airbytehq-team.slack.com/archives/C061M060RDE/p1700667165012909?thread_ts=1700578197.880089&cid=C061M060RDE) about this and I think @chandlerprall was going to try implementing it (maybe in a subsequent PR since it was after the original discussion!)

+1, that's right
