### ISSUE TITLE
Re-run tests as part of connector publish

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#32144]
Now that we've got Dagger caching working(*), running tests before connector publication should be fast and cheap, as nothing in the connector directories should have changed between the PR branch and the merge to master.   If something did change, the test will be slower... but then we should probably run tests :D

Initially, we didn't want to run tests as part of publish because:
* They were slow (solved by caching), and this slowness would increase the drift between what is on master and what users would see
* We lacked visibility into the publish pipeline to know if something went wrong (solved by #connector-publish-updates and new metrics)
*

**Comment by evantahler** [comment]
Grooming:
* ⚠️ confirm that tests really are cached and this doesn't slow things down ⚠️
   *  do not do this story unless >=90% of publishes would successfully resolve the cache and not really run tests. 
* do our API limits (sandbox, docker, etc) make this brittle?
    * Still one GHA, so no Github Change 
    * API rate limits could be real, but if tests are cached, tests won't run (same with docker)

**Comment by evantahler** [comment]
I'm worried about how if tests are failing you can't publish any more.  /approve-and-merge to skip flaky tests mean you can't actually publish any more

**Comment by bnchrch** [comment]
@evantahler I agree. Would be for closing this.
