### ISSUE TITLE
Replicaiton page on a connection won't show columns

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#32156]
At the very least stream selection screen should only show the fields we sync - `_id` and `data`.
Use schemaless s3 mode as an example.

**Comment by akashkulk** [comment]
This would be a side effect of returning a fixed catalog - no extra work would be required

**Comment by akashkulk** [comment]
Closing as it is covered by https://github.com/airbytehq/airbyte/issues/32160
