### ISSUE TITLE
don't log archive import binary

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3215]
You get something like this when importing an archive:

    airbyte-server      | 2021-05-04 19:01:59 INFO i.a.s.RequestLogger(filter):107 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.19.0.1 POST 200 /api/v1/deployment/import - +��`�]͏$GV��.��J�������,rOw��]ό=�^��Pod|t����Ye{,��'��b�+np�+�p�#wn��Y�Y�Y]�5^w>MuNeF����{ux��NS�eqL0�Frd�#�'�%�7v"��¸9>J1>b��c �x�p�9#LI��D
    airbyte-server      | �M���j4ʆ:�[�4�n�OW��bޯi'�9=��Я�֯6�j4�i�|�j�i��p

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368106264112) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
What's the fix here? is it just special handling for logging for this specific endpoint?

**Comment by jrhizor** [comment]
yep

**Comment by marcosmarxm** [comment]
@jrhizor the log should only be suppressed/omitted when submit the import endpoint?

**Comment by jrhizor** [comment]
yes
