### ISSUE TITLE
Amazon Redshift - schema creation

### ISSUE THREAD

**Issue by MC1-RicardoLeka** [airbytehq/airbyte#3216]
I create a ETL from SQL server to AWS Redshift.
Most part of the tables are on dbo schema and a few others on other schema.
I selected all the tables on all schemas to sync, but no table was created on redshift.
After I create the schemas on Redshift and request a new sync the Airbyte create the tables with the issue #2889 .

I can´t find on the logs a error of the schema creation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368106296365) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@MC1-RicardoLeka can you share the Airbyte/connector/destination version? I saw that you share some information on #2889 this will help us a lot! Thanks

**Comment by MC1-RicardoLeka** [comment]
> @MC1-RicardoLeka can you share the Airbyte/connector/destination version? I saw that you share some information on #2889 this will help us a lot! Thanks

Hi @marcosmarxm ,
I´m running the Redshift Connector 0.3.3, SQL connector 0.3.0

**Comment by marcosmarxm** [comment]
closing due inactivity; @MC1-RicardoLeka please open a new issue using the template given if continue the problem.
