### ISSUE TITLE
Initial read: query to get all fields

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#32161]
Formulate a query or API call to retrieve all fields in document.

**Comment by akashkulk** [comment]
I believe we are already querying all the fields in the document - and then filtering them out based on the fields in the catalog. This change would just involve NOT filtering these fields out in packed mode
- Initial Snapshot : [Code Link](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mongodb-v2/src/main/java/io/airbyte/integrations/source/mongodb/InitialSnapshotHandler.java#L64C50-L64C50). Then, we use [this](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mongodb/MongoDbCdcEventUtils.java#L126) method to strip the fields not in the catalog. However, there is an override already defined to allow all fields. 
- Incremental Load (from the OpLog) : Unlike in Relational mode, there is [no filtering](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mongodb/MongoDbDebeziumPropertiesManager.java#L79) of data fields through debezium. The codepath to parse this data into an airbyte type is [similar](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mongodb/MongoDbCdcEventUtils.java#L119) to the initial snapshot case.
