### ISSUE TITLE
Source Salesforce: constantly timeout when replicating large tables (>40M records, 400 columns each)

### ISSUE THREAD

**Issue by r0b3rt24** [airbytehq/airbyte#32166]
### Connector Name

source-salesforce

### Connector Version

2.1.5

### What step the error happened?

During the sync

### Relevant information

# Context
We use `source-salesforce` and `destination-s3` to run `increamental-append` sync for a few large salesforce table.

Our airbyte cluster is running in EKS. 

# Issue
The sync never succeed due to timeouts. We had some experience building such connectors in other platform. The main issue was the the distribution of number of records on `systemModStamp` is not even. So when the salesforce connector runs query against a time range contains too many records, salesforce won't return result given that salesforce connector has a fixed time range for slices. 

# How to reproduce
Use the same setup and try to sync SObject that has >30M records ~400 columns to s3 in parquet format.

cc: @yuyangverkada

### Relevant log output

```
2023-11-03 17:16:47 source > Backing off _send_http_request(...) for 15.0s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
2023-11-03 17:16:47 source > ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-11-03 17:16:47 source > Caught retryable error after 1 tries. Waiting 15 seconds then retrying...
```

### Contribute

- [X] Yes, I want to contribute

**Comment by r0b3rt24** [comment]
In detail here is my plan:


the slice size is 30days fixed [here](https://github.com/airbytehq/airbyte/blob/4d5d259fb65c91a68d7f2d59f9536590f0a84b69/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L621C1-L621C1) 
```
STREAM_SLICE_STEP = 30
```

This is problematic since we could have millions of rows in 30 days. In such case, the slice will also timeout and the sync will stall and eventually fail.

I would recommend adding dynamic slice size:

In the `stream_slices` [function](https://github.com/airbytehq/airbyte/blob/4d5d259fb65c91a68d7f2d59f9536590f0a84b69/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L636), we add probing: count the row numbers in the slices. Exponentially reduce the interval if the row counts are too large.

for example:
we first run
```
select count() from account where systemModStamp > start_time and systemModStamp < end_time
```

if count is larger than 1M rows

we change end_time = start_time + (end_time-start_time)/2

repeat until count is lower than a threshold. 

By implementing such strategy, we can ensure our sync can always proceed.

I understand that this would add overhead to sync, and for most tables this is unnecessary. We can add another flag to turn it on or off for different tables.

Please let me know if you think this wouldn't work or there are better solutions.

Thanks for any help in advance.

**Comment by yuyangverkada** [comment]
Adding more context to the issue:   We have a few salesforce tables that have > 20 million rows in a timespan of 30 days, with each row can have up to >400 columns in some of those tables.  Our salesforce instance only allows us to read about 30k rows every 90 seconds. It will take about 45 minutes to fetch 1 million rows through salesforce API.   >8 million records were updated on a few days. Because of that, the current salesforce source consistently hit timeout when we try to take a full snapshot of the salesforce table. 

As @r0b3rt24  mentioned earlier, we would like to add an optional field to allow salesforce source to check the # of records in a given time range, and dynamic adjust the data fetching time range.  please let us know if you have any suggestions on this.

**Comment by maxi297** [comment]
@r0b3rt24 @yuyangverkada 

There are two fixes that have been released that can help you:
* In version 2.3.2, we've added the ability to configure the slice step. This is not dynamic based on the count (idea which we like and might work on in the future) but it should be enough to unblock you
* In version 2.4.1, we have done resiliency work on the connector as we've seen that connection errors are often transient.

Can you test with version >2.4.1 and let us know if it helps? If not, we can check your case specifically and see what are the other next steps
