### ISSUE TITLE
Keep table selection on modify

### ISSUE THREAD

**Issue by MC1-RicardoLeka** [airbytehq/airbyte#3218]
When I edit a existing ETL, to add more table or modify something, the airbyte unmark all the tables.
It´s possible keep the selected tables after we click on edit?

**Comment by marcosmarxm** [comment]
@MC1-RicardoLeka is something similar to #3206 ?

**Comment by MC1-RicardoLeka** [comment]
@marcosmarxm yes, it´s similar.
I´ll close this one.
