### ISSUE TITLE
source-mongodb to skip records deemed as too big

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#32185]
### What area the feature impact?

Connectors

### Relevant Information

source-mongodb-v2 is running into an issue with customer having records that are bigger than our current max handled size of 20mb.

It is suggested that in this case (configurable) source-mongodb can handle records that are too big by a) sending a records containing only the id of this records and b) indicating in a visible way in log that a record was skipped due to size.
Currently such a record will cause the sync to fail without a way to remediate other than removing records from db.
This will be applicable in schema or schemaless mode.

[[ref thread]](https://airbytehq-team.slack.com/archives/C05FX7UEYNT/p1699037494505239?thread_ts=1698878250.637729&cid=C05FX7UEYNT)

**Comment by akashkulk** [comment]
Based on https://airbytehq-team.slack.com/archives/C05FX7UEYNT/p1700248714840849?thread_ts=1700242738.059269&cid=C05FX7UEYNT, Regorra doesn't currently have any large records. We can icebox this for now
