### ISSUE TITLE
[destination-mysql] replace `-` character with `_` in dbname

### ISSUE THREAD

**Issue by fsanchez-auronix** [airbytehq/airbyte#32182]
### Connector Name

destination-mysql

### Connector Version

0.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

A database is configured with the name api-metrics and when performing the test it indicates the error api_metrics by changing the - to the character _

engine version:
8.0.mysql_aurora.3.02.2

### Relevant log output

```shell
Configuration check failed
State code: 42000; Error code: 1044; Message: Access denied for user 'airbyte'@'%' to database 'api_metrics'
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
I *think* this is fixed now in the latest version of the connector - can you conirm?

**Comment by evantahler** [comment]
Closing, as this bug was from a very old version of the connector
