### ISSUE TITLE
Update information on Web Interface for Last Sync

### ISSUE THREAD

**Issue by MC1-RicardoLeka** [airbytehq/airbyte#3219]
Hi,
if we stay with the Web Interface open on "Connections" the information on the column "Last Sync" stay incremmental, even when the ETL already executed in the main time.
![image](https://user-images.githubusercontent.com/67108329/117070793-9e2a9f80-ad04-11eb-8761-9ec42425a263.png)

It´s possible change the information to "Last Sync" from the last execution? or add a column with the "Date of the last execution" ?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368164682750) by [Unito](https://www.unito.io)

**Comment by andyjih** [comment]
Closing this issue. Not clear what the enhancement is here and the issue quite old.
