### ISSUE TITLE
Caret on the right is too thick when hovering a cell in Source > Status > Logs

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#322]
See screenshot. This is too thick, it should be in "Light". 

<img width="874" alt="Screen Shot 2020-09-17 at 11 54 24 AM" src="https://user-images.githubusercontent.com/68561602/93407826-ccc34980-f8de-11ea-9389-7901b6d783e8.png">

**Comment by Jamakase** [comment]
@johnlafleur We use font awesome only free version. Caret “Light” is PRO font https://fontawesome.com/icons/chevron-right?style=solid

**Comment by johnlafleur** [comment]
oh ok, then I will close this issue.
