### ISSUE TITLE
Helm Chart: `Running the launcher replication-orchestrator failed` after upgrade

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#32203]
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

All Helm chart versions later than 0.49.6

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

Myself and others in Slack are reporting a variety of issues on Helm charts newer than 0.49.6.  For each person, downgrading to 0.49.6 resolved the issues and Airbyte is stable.  On later versions than 0.49.6, Airbyte is not stable.  Connectors, tests, etc. fail with various errors.  Slack thread: https://airbytehq.slack.com/archives/C021JANJ6TY/p1698930804469959

### Relevant log output

```shell
message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Running the launcher replication-orchestrator failed', type='java.lang.RuntimeException', nonRetryable=false
```

**Comment by tanderson-hp** [comment]
Confirmed that I experienced the same, and downgrading to 0.49.6 resolved my issue.

**Comment by tobiastroelsen** [comment]
Same as above! Worked for me as fix as well

**Comment by cappadona** [comment]
Confirming that we were unable to deploy Airbyte when upgrading beyond `0.49.6`.

Also came across this other issue which may be related:
* #31988

**Comment by GKTheOne** [comment]
still bad: 0.49.21

**Comment by heruscode** [comment]
Same here, I can't upgrade to the latest version

**Comment by PurseChicken** [comment]
Same issue here. Had to roll the chart back to 0.49.6.

**Comment by storytel-siudzinskim** [comment]
2 weeks ago I also reported a bug here: https://github.com/airbytehq/airbyte/issues/32544

It looks the issue came with Airbyte 0.50.33 and is present in 0.50.34.

**Comment by marcosmarxm** [comment]
Hello all 👋  the team made some investigation and found a workaround

For now this is the step to fix the issue:
`kubectl exec -it airbyte-minio-0 bash -n <your-namespace>`

After run the following commands:
```bash
mc alias set myminio http://localhost:9000 minio minio123
mc mb myminio/state-storage
```

This will create a missing bucket. The team is working to release a fix for future upgrades. Thanks for the patience.

**Comment by davinchia** [comment]
Hi guys, we figured out what was happening:
- previously the minio and database pods were reconfigured to always recreate on every helm deployment, be it an install or an upgrade. However, we were not correctly creating the bucket on an upgrade. This resulted in syncs failing.
- this behaviour has been fixed as of 0.50.3.
- the minio and database pods are now only created on install (not upgrade), and we always attempt to create the required default buckets, regardless of install/upgrade. This should result in an overall more stable Airbyte experience.
- please give it a shot and let me know!

**Comment by davinchia** [comment]
@DSamuylov interesting, can you show me how you are deploying 0.50.3?

**Comment by DSamuylov** [comment]
Do you mean the environment variable `STATE_STORAGE_S3_BUCKET_NAME ` from here?

```terraform
  set {
    name  = "worker.extraEnv[2].name"
    value = "STATE_STORAGE_S3_BUCKET_NAME"
  }
  set {
    name  = "worker.extraEnv[2].value"
    value = var.aws_bucket
  }
```

The variable `var.aws_bucket` is set to my bucket name, something like: "my-project-name". Should I provide it in a different format?

**Comment by davinchia** [comment]
@DSamuylov 

Yes that was what I was referring to.

Follow up questions:
1) Were you using the orchestrator before this? We turned on the orchestrator by default in 0.49.7. This allows jobs to survive between updates and does so via a middle job state storage location. The charts default to the `state_storage` bucket hosted on minio.
2) If you were, what kind of state storage configuration were you doing? e.g. was it S3? We support using S3 and GCS as the state storage layer.

**Comment by DSamuylov** [comment]
@davinchia

Sorry for the delay in my reply, last days were extremely busy.

1. Do you mean triggering jobs and successfully syncing data? In this case, yes. Otherwise likely not. Does it require setting up some variables in `values.yaml`? I only set up the values as in my previous message, for example I think I completely disable `minio`with this:

```terraform
  set {
    name  = "minio.enabled"
    value = false
  }
  set {
    name  = "global.logs.minio.enabled"
    value = false
  }
```

So if some pods require access to it, they will fail.

2. I use AWS S3, but maybe I do not customise some of the variables that I should customise? I sent you the full list of what I customise in the previous message. I would highly appreciate if you could take a look and let me know if I should try to define some additional variables and I will report you back the results.

**Comment by sebaap** [comment]
We are also facing this issue after upgrading to `0.50.20`, all jobs failed to start with the same error. Our instance is deployed on GKE using helm and minio is configured to GCS.
Tried the workaround [here](https://github.com/airbytehq/airbyte/issues/32203#issuecomment-1832627982) but didn't work.
Everything worked fine after downgrading to `0.49.6`

**Comment by yorjaggy** [comment]
We were facing the same issue, we updated to Airbyte 0.50.43 with the Chart 0.50.21 and the error comes up, this time the error log was more detailed:
```
Caused by: io.temporal.failure.ApplicationFailure: message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Running the launcher replication-orchestrator failed', type='java.lang.RuntimeException', nonRetryable=false
	at io.airbyte.commons.temporal.HeartbeatUtils.withBackgroundHeartbeat(HeartbeatUtils.java:62) ~[io.airbyte-airbyte-commons-temporal-core-0.50.43.jar:?]
	...
Caused by: io.temporal.failure.ApplicationFailure: message='Running the launcher replication-orchestrator failed', type='io.airbyte.workers.exception.WorkerException', nonRetryable=false
	at io.airbyte.workers.sync.LauncherWorker.run(LauncherWorker.java:262) ~[io.airbyte-airbyte-commons-worker-0.50.43.jar:?]
	...
Caused by: io.temporal.failure.ApplicationFailure: message='The specified bucket does not exist (Service: S3, Status Code: 404, Request ID: 17AD5DF2AB182273, Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)', type='software.amazon.awssdk.services.s3.model.NoSuchBucketException', nonRetryable=false
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125) ~[sdk-core-2.20.162.jar:?]
	...
```

We checked the Minio version and updated to the latest, and then executed the workaround mentioned by @marcosmarxm, and it worked.

Thanks @marcosmarxm 

> Hello all 👋 the team made some investigation and found a workaround
> 
> For now this is the step to fix the issue: `kubectl exec -it airbyte-minio-0 bash -n <your-namespace>`
> 
> After run the following commands:
> 
> ```shell
> mc alias set myminio http://localhost:9000 minio minio123
> mc mb myminio/state-storage
> ```
> 
> This will create a missing bucket. The team is working to release a fix for future upgrades. Thanks for the patience.

**Comment by sg-danl** [comment]
I've been pinning version 0.49.6 to get around this for the past month and a half.  
(Running Airbyte OSS on AWS EKS cluster, default values.yaml for ease of replication while trying to fix.)  
  
Trying the fix suggested by @marcosmarxm doesn't fix for me. After attempting upgrading from 0.49.6 -> latest since mid Jan (so 0.50.22+) it has never fixed the issue.  
  
Running the minio config in bash returns:  
  
```

helm % kubectl exec -it airbyte-minio-0 bash -n default
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-5.1# mc alias set myminio http://localhost:9000 minio minio123
mc: Configuration written to `/tmp/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/tmp/.mc/share`.
mc: Initialized share uploads `/tmp/.mc/share/uploads.json` file.
mc: Initialized share downloads `/tmp/.mc/share/downloads.json` file.
Added `myminio` successfully.
bash-5.1# mc mb myminio/state-storage
mc: <ERROR> Unable to make bucket `myminio/state-storage`. Your previous request to create the named bucket succeeded and you already own it.

```  
  
Not an expert in any of this at all, but it looks like the creation of the bucket isn't entirely the issue. Just wanted to provide additional info as this has been a long-open issue!

**Comment by marcosmarxm** [comment]
Folks everyone having this issue. Please open a new issue and report what values and version you're using.
