### ISSUE TITLE
`gradlew format` fails if there is no import statement

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#3221]
## Expected Behavior
Running `./gradlew format` should work even if there are no import statements at the beginning of a file. 

## Current Behavior
The Spotless license check doesn't accommodate for files that don't have import statements (e.g. constant files) and cannot find the start of the file. 

To replicate:
1) Create file without import statement
2) Run `./gradlew format`
3) Fail

## Additional context
To fix this issue, we just need to do a quick fix to the regex statement here: https://github.com/airbytehq/airbyte/blob/fa33c9c1268b3968c8bc3b67ac1634742442b190/build.gradle#L108

**Comment by sherifnada** [comment]
worth noting: this breaks specifically for files which are either empty or start with a variable e.g: 

`file.py`
```
my_list = ['hi','there']
```

would break

**Comment by avaidyanatha** [comment]
Turns out there is an existing workaround for this, but it needs to be documented :) Just opened a PR for that!
