### ISSUE TITLE
Stuck in creating the Yaml manifest to build the connector

### ISSUE THREAD

**Issue by prk2331** [airbytehq/airbyte#32217]
### Relevant information

Team, Im stuck in creating the Yaml manifest 
1. for Source (Mysql) out-of-the-box To destination (postgres) out-of-the-box
2.(Mysql) out-of-the-box To S3 bucket (out-of-the-box)
3. and in this manifest how can we configure the workflow like (replications, streams, sync mode, settings..... etc).

Please guide me

Thanks

**Comment by prk2331** [comment]
is it not possible through Yaml manifest (which is in our airbyte UI builder section) ?
i read somewhere about octavia CLI, to do this we need octavia ?

**Comment by marcosmarxm** [comment]
@prk2331 you can use the Terraform or Octavia CLI.
