### ISSUE TITLE
Destination S3: switch back to using incrementing part numbers

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#32229]
After https://github.com/airbytehq/airbyte/pull/29640/files, destination-s3 is now generating files with a UUID in the filename. For example, where we previously generated `your_stream_0.csv`, we now generate `your_stream_<uuid>.csv`.

Cloud  is now pinned to an old version of the s3 destination https://github.com/airbytehq/airbyte/pull/32228

It's probably easy to switch back to the old behavior - we can create a `Map<String objectPath, AtomicInteger partId>` instead of generating the partId inside `loadDataIntoBucket`. (see https://github.com/airbytehq/airbyte/blob/9dd7d7ea83a7e909eeb4f4d982507313e8ab5b45/airbyte-cdk/java/airbyte-cdk/s3-destinations/src/main/java/io/airbyte/cdk/integrations/destination/s3/S3StorageOperations.java#L159)

Make this change, verify that all downstream destinations still work (S3, Redshift... bigquery maybe?) and unpin destination-s3 (i.e. remove the metadata change from https://github.com/airbytehq/airbyte/pull/32228).

Also figure out why our destination-s3 tests didn't catch this.

**Comment by evantahler** [comment]
Counter-proposal: Don't change anything in the code and make a breaking change + docs saying that we use UUIDs now, so we'll be ready for the async framework when that comes early next year

**Comment by evantahler** [comment]
From Slack:

we don’t even need an explicit global lock. AtomicInteger provides a threadsafe incrementAndGet method. (which maybe locks under the hood, idk) So if we have an atomicinteger per stream, we would just need to to partId = counters.get(stream).incrementAndGet() instead of partId = UUID.randomUuid()

**Comment by evantahler** [comment]
Grooming:
* Use AtomicInteger to create unique file name parts per stream (and go back to the original behavior)
* Also... why didn't tests fail when the file names changed.  We should have a test that checks the file names are what we expect them to be. 
   * Let's timebox the test writing part of this story to 1 day?

**Comment by edgao** [comment]
oss pin + changelog updated in https://github.com/airbytehq/airbyte/pull/32278/files?diff=unified&w=1

**Comment by evantahler** [comment]
We will need to unpin destinaton-s3 for https://github.com/airbytehq/airbyte/pull/33703 to take effect for users
