### ISSUE TITLE
Improve UX of source Amazon Seller Partner

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#32225]
Suggestion to improve the setup success rate of Amazon Seller Partner:

- Make the following fields required in the connector spec (AWS Access Key, AWS Secret Access Key, Role ARN
- Add an example value in the tooltip for the AWS Access Key
- Add an example value in the tooltip for the AWS Secret Access Key
- Add an example value in the tooltip for the Role ARN

I believe these three are not required for Cloud when using OAuth, but I'm not sure: LWA Client ID (LWA App ID), LWA Client Secret, Refresh token.  If these are not editable on Cloud, then we should remove those fields from showing as requirements in the in-app docs.

**Comment by nataliekwong** [comment]
@lmossman Are you still the best contact for ensuring some fields get shown outside of the optional section? Amazon Seller Partner is one where we nested three fields (AWS Access Key, AWS Secret Access Key, Role ARN) into the optional fields section but it appears that successful connections all contain it and they are not marked as optional in the docs.

**Comment by lmossman** [comment]
@nataliekwong yes this would be a straightforward change. We have 2 options here:
1. Make the fields required, by adding them to the `required` array [here](https://github.com/airbytehq/airbyte/blob/4f9b877bee64bbe9a719d4708792a291fab9db67/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.json#L7)
2. Keep the fields optional but always show them, by setting `always_show: true` on each of the fields

From your description it sounds like we may want to go with option 1, but calling out that this would technically be a breaking change. But if all connectors that haven't set those are failing then it probably wouldn't hurt anyone to make that breaking change.

@artem1205 looks like this is assigned to you, so I'll leave it to you to make one of those changes based on Natalie's feedback. But don't hesitate to reach out if you need assistance.
