### ISSUE TITLE
Source Amazon Seller Partner: add new GET_VENDOR reports 

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#32232]
Add GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT, GET_VENDOR_REAL_TIME_INVENTORY_REPORT, GET_VENDOR_TRAFFIC_REPORT

**Comment by artem1205** [comment]
Moving to on hold as these streams are empty and cannot be accessed using our sandbox credentials:
```json

{"errors": [{"code": "Unauthorized", "message": "Access to the resource is forbidden", "details": ""}]}

```
We need to set [Amazon Brand Analytics](https://www.webfx.com/blog/marketing/amazon-brand-analytics/) and enable Brand Analytics role in our app settings.

cc @Diana-Vait @lazebnyi @oustynova

**Comment by askarpets** [comment]
These streams have been added as a part of certification process.
