### ISSUE TITLE
CDK: use makefile for running tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3224]
## Tell us about the problem you're trying to solve
There will likely be long commands that should be run regularly as part of our build process. For example to run tests we want `pytest --cov=airbyte_cdk -s unit_tests` for running unit tests, similar commands for mypy and style checks etc..

It might be a good addition to have a makefile which encodes these things by default so instead we just invoke it via 

```
make test
```

and it's a done deal

Example makefile https://github.com/litl/backoff/blob/master/Makefile
This would go in the `airbyte-cdk/python` directory

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368164755590) by [Unito](https://www.unito.io)

**Comment by noahkawasakigoogle** [comment]
is this still something people want?
