### ISSUE TITLE
Make our feature-flagging system foolproof (e.g. stop using launchdarkly)

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#32269]
from this P1 https://docs.google.com/document/d/1vSW1seujyprqaQ5mhwpMXrY2jtMb_AcWaZjRyVdZWUI/edit

it's currently quite easy to target the wrong workspaces/etc, and we don't have many (any?) guardrails against doing things wrong.

**Comment by bnchrch** [comment]
Just tagging @pedroslopez and @evantahler in this.

Pedro is currently working on a tech spec for this as we speak

**Comment by bnchrch** [comment]
@edgao Do you feel this is a problem specific to Connector pinning and feature flags, or launch darkly as a whole?

**Comment by edgao** [comment]
probably both? the connector pinning flag is _especially_ hard to use, but launchdarkly as a whole is difficult:
* confusing UI (e.g. the error I made in the pomo linked above)
* hard to request review (due to our account setup), which makes the confusing UI more punishing
* hard to navigate/explore - lack of org-wide conventions around variant naming, etc.
* poor audit logs (exacerbated by our lack of conventions) - e.g. if I want to find all flag modifications that affect a specific workspace.... :shrug:
