### ISSUE TITLE
Connector Config attached to Sentry

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#32302]
## Problem
We have no context as to what config was used for a sentry issue.

i.e. P2 tickets take a long time to get to, and we cannot be certain if the config in the db today is what was used at the time the sentry issue was created

## Impact
We will effectively be able to address issues that have been in the backlog for longer that 1 month.

## Solutions
1. We store state for every attempt, can we do that for config?

**Comment by edgao** [comment]
pulling from zoom chat:
* `attempts` table, `attempt_sync_config` already contains state + (dehydrated) config blob at the start of the sync attempt
* we should expose this in a better way

**Comment by katmarkham** [comment]
https://pypi.org/project/traceback-with-variables/

**Comment by katmarkham** [comment]
synced with @pedroslopez last week.  We apparently used to have this information available in the UI.  I don't think we want to reenable it there, but we would like to grab the user configs and config params for these Sentry alerts.  Not sure what the implications are for storing user data in tickets.  Perhaps we include a link in the tickets that goes to logs that can only be accessed by people with appropriate credentials?

**Comment by pedroslopez** [comment]
We are attaching the failure reason to Sentry events currently as extra context:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42c7510ebd2f4678986fc0e33306276a0c58c1b7/image.png)

([link](https://airbytehq.sentry.io/issues/4373798948/?project=6527718&query=is:unresolved&statsPeriod=14d&stream_index=0#context-Failure%20Reason))

We can do the same and pass along attempt config information, including (masked) config and state

**Comment by bnchrch** [comment]
Grooming:
1. This is likely something we can get 80% of the benefits by using sentry context
2. All we would have to do is attach the config
3. Roadblock potentially on having access to config
4. 3. Roadblock potentially on size limits
5. we can also tack on state
6. @bnchrch to prioritize in OC

**Comment by bnchrch** [comment]
grooming:
- The secrets may change over time and make this less useful
- We have historic job config but not connection
-
