### ISSUE TITLE
source-stripe: Run streams configured as full refresh with concurrent cdk

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#32308]
## What
If a Stripe stream is full refresh in the configured catalog, run it as concurrent

## Acceptance criteria
- [x] All stripe streams configured as full refresh run using the concurrent cdk
- [ ] Verify that the streams that do not have CAT coverage still work as expected

**Comment by maxi297** [comment]
Streams I could not test:
* application_fees_refunds
* authorizations
* external_account_cards
* payment_methods
* persons
* reviews
* transactions

Reasons I could not test was either one of:
* Could not find streams with records in the last 7 days
* Stream name was shared with other sources and I timeboxeds manually mapping from log to a stripe sync with records after 5 minutes for each stream

Note that testing for `early_fraud_warnings` yielded only one record.

**Comment by maxi297** [comment]
New graphs have been added to Metabase dashboard https://airbyte.metabaseapp.com/dashboard/2085-concurrent-cdk?date_filter=past30days~
