### ISSUE TITLE
source - Instagram README.md is mistake ?

### ISSUE THREAD

**Issue by prameelareddi** [airbytehq/airbyte#32336]
### Connector Name

source-instagram

### Connector Version

1.0.2

### What step the error happened?

Updating the connector

### Relevant information

Encountering an issue in the Airbyte source-instagram repository where the README for Salesloft source appears instead of the expected content. Seeking assistance to rectify this discrepancy

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Latest version of the file is correct https://github.com/airbytehq/airbyte/blob/ba4dd5e238815ea4ff7fc4c97c43bab9b1988405/airbyte-integrations/connectors/source-instagram/README.md
