### ISSUE TITLE
 Custom Transformations: Create UI Mock-up

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3234]
## Tell us about the problem you're trying to solve
As part of project https://github.com/airbytehq/airbyte/issues/2959, this ticket should track progress on the UI Mock-up part of the work

## Describe the solution you’d like
In terms of UI, it would be nice to design a dedicated Connection-Transformation page or section attached to a connection page, where you can define a sequence of transformations. Each transformation can have the following fields:
- name of the transformation step
- a type of transformation from: 
  1. normalization
  2. custom dbt transformation
  3. later, we'll support more types

If the user selects a normalization transformation type 
  - this would turn airbyte's normalization on as described in https://github.com/airbytehq/airbyte/issues/3209
  - in the future we may need to add more configuration options on the behavior of normalization: for example choose to unnest and explode them into their own table or not
  - it would be nice to have some export generated normalization project button here too (to start their custom dbt project from the normalization-generated one)
  
If the user selects custom transformations type, we can only specify for a dbt transformation that requires:
  1. String input field for Docker image URL with dbt installed, typically one from [fishtownanalytics/dbt](https://hub.docker.com/r/fishtownanalytics/dbt/tags?page=1&ordering=last_updated)
  2. String input field for Git repository URL of the custom transformation project 
  3. String input field for Entrypoint arguments for dbt cli to run the project 

Note, these configurations are at the connection level, not at the stream level

## Additional context:
[Google Doc - Tech Specs](https://docs.google.com/document/d/1hut8_hPujBddvwAtGOA5DdQyKsG4kNB30mlMcQ_dZ9M/edit?usp=sharing)

**Comment by johnlafleur** [comment]
Here's a suggestion of design:
https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25296%3A0
Please don't hesitate to leave comments in Figma
