### ISSUE TITLE
Make descriptions shorter when possible

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#324]
Some descriptions are too long. For instance, when adding a BigQuery destination:
<img width="697" alt="Screen Shot 2020-09-17 at 11 47 28 AM" src="https://user-images.githubusercontent.com/68561602/93408003-43604700-f8df-11ea-8024-7d7c557be0fa.png">

**Comment by cgardens** [comment]
Yeah. I think the issue right now is alot of these descriptions are being written before the documentation page in gitbook is getting written (just a side effect of scrambling to get to launch). I agree though, lengthier explanations should be in the docs and we should just link to their when things are complicated.

**Comment by cgardens** [comment]
Now that we have docs for all of our integrations, I'm going to go back and try to prune these descriptions today.
