### ISSUE TITLE
Cannot reach server. The server may still be starting up.

### ISSUE THREAD

**Issue by rajeshjatavkonvergeai** [airbytehq/airbyte#3240]
Hi,
I have tried to deployed Airbyte on local kubernetes cluster. It is deployed successfully. All pods are running properly. But when I try to open the url, get this error.
**Cannot reach server. The server may still be starting up.**

Why am I getting this error? What should I do?

Thanks,
Rajesh

**Comment by cgardens** [comment]
hiya! feel free to reopen if you are still having this issue.
