### ISSUE TITLE
Stream Centric UI: Connection & Stream Status do not show "Pending" during first sync after reset is running

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#32417]
The connection & stream status on the Status page show "On time" when the first sync is running after a reset. This is not actually true as the data has been removed from the destination, so we cannot say the data is on time as it doesn't exist. 

I believe it's this combination of the last job being a reset and the current job as incomplete that should make the status "Pending" instead of "On time". ([source](https://whimsical.com/unified-connection-and-stream-status-logic-data-flow-VWUTi1SbzsJfmDiQcepSJj))

<img width="562" alt="Screenshot 2023-11-09 at 9 34 26 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/f8fdb404-844c-4470-8bc9-37ed3993dc10">

Example screenshots of the job history and the observed status during the first sync after reset: 
<img width="942" alt="Screenshot 2023-11-09 at 9 32 04 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/5ace8960-ce5d-4e3e-8664-9ec4060e64bb">
<img width="921" alt="Screenshot 2023-11-09 at 9 32 00 PM" src="https://github.com/airbytehq/airbyte/assets/38087517/d7094e1e-f4b9-410c-953c-89a063ce9e49">

**Comment by josephkmh** [comment]
Refining notes:
- Will be fixed by an upcoming "in_progress" status
- @chandlerprall has a branch

**Comment by chandlerprall** [comment]
Related to https://github.com/airbytehq/airbyte/issues/26642 , which should also be resolved by having a top-level In Progress status

**Comment by nataliekwong** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/26642
