### ISSUE TITLE
Docs formatting issue on cloud.airbyte.com

### ISSUE THREAD

**Issue by askarpets** [airbytehq/airbyte#32419]
### Topic

Formatting of source connectors docs doesn't match what's expected

### Relevant information

Hello,

We have an issue rendering source connector-specific markdown documents on cloud platform. Fox example, for [Klaviyo](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/klaviyo.md?plain=1#L20) we expect this to be rendered like below:
![image](https://github.com/airbytehq/airbyte/assets/22576627/a52562df-7483-43db-88c9-36eb96060fbc)

However, on the platform, we see the following:
![image](https://github.com/airbytehq/airbyte/assets/22576627/fef78d19-de0b-41aa-9e11-a16c6511e3d3)

Other known affected connectors:

- [Gitlab](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/gitlab.md?plain=1#L45)
- [Facebook Marketing](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/facebook-marketing.md?plain=1#L38)
- [Google Analytics](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/google-analytics-v4.md?plain=1#L40)
- [Google Ads](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/google-ads.md?plain=1#L61)

Please let me know if I can assist.

CC: @brianjlai @maxi297 @lazebnyi

**Comment by maxi297** [comment]
Instagram is also affected

**Comment by lmossman** [comment]
I have opened a PR to fix this issue in the webapp, so we shouldn't need to modify any connector docs: https://github.com/airbytehq/airbyte-platform-internal/pull/9871
