### ISSUE TITLE
Source Instagram: User Insights stream error

### ISSUE THREAD

**Issue by yevhenii-ldv** [airbytehq/airbyte#3241]
## Expected Behavior
Completed sync.

## Current Behavior
Failed sync.
![image](https://user-images.githubusercontent.com/34103125/117161155-5d955980-adca-11eb-9799-eac6bfa4b1b2.png)

## Logs
Logs below (access token redacted).

Attempt 1: [logs-52-0.txt](https://github.com/airbytehq/airbyte/files/6420764/logs-52-0.txt)
Attempt 2: [logs-52-1.txt](https://github.com/airbytehq/airbyte/files/6420763/logs-52-1.txt)
Attempt 3: [logs-52-2.txt](https://github.com/airbytehq/airbyte/files/6420766/logs-52-2.txt)

## Steps to Reproduce
1. Add new Instagram source 
2. Enable "User Insights" stream 
3. Run sync

## Severity of the bug for you
High

## Airbyte Version
Airbyte 0.19.0-alpha

## Connector Version (if applicable)
airbyte/source-instagram 0.1.4

**Comment by yevhenii-ldv** [comment]
##My investigate
The reason was determined, it is in the `user_insights` stream, and more specifically in getting the Insight of the `online_followers` metric for the `lifetime` period.
For some reason, it began to receive an error when we try to get data for the near 2 days before now (for today it is from 2021-05-04 00:00:00 to 2021-05-05 00:00:00 and from 2021-05-05 00:00:00 to 2021-05-06 00:00:00).
I did not find in the Facebook documentation why this began to happen, because before that everything worked fine. The rest of the User Insight metrics work perfectly.

**Comment by htrueman** [comment]
@sherifnada found that the exception described in issue disappeared. But now there is no online_followers field in the records for the last 2 days. So it seems that instagram has updated their API.
To avoid this issue appearing in future we may update our incremental sync to exclude last 2 days from sync. 
Or maybe it's better to just leave it as it is?
Se read output: [read.txt](https://github.com/airbytehq/airbyte/files/6460721/read.txt)

**Comment by VasylLazebnyk** [comment]
@sherifnada as I get these ticket shall be closed as not relevant for now? thanks

**Comment by jimbeepbeep** [comment]
I can confirm that syncs are no longer failing, which is great from our perspective!

**Comment by sherifnada** [comment]
super weird, but good news indeed. It seems like there was a bug in the Instagram API then. Let's close this and reopen if the issue reappears. Thanks @htrueman !
