### ISSUE TITLE
[source-mongodb] certain fields are not showing in source sample data when creating schema

### ISSUE THREAD

**Issue by ChrisMDriveYello** [airbytehq/airbyte#32415]
### Connector Name

airbyte/source-mongodb-v2

### Connector Version

1.0.7

### What step the error happened?

Other

### Relevant information

When setting up a new connection:
I am not getting the same fields for the schema, I believe there is something wrong with the sample data which it gets to create the schema from. The new mongodb source connector(v1.0.7) is not getting the same values as what I get from the mongo source connector v0.2.5.

I am running airbyte 0.50.30 in a test environment with mongo source connector (v0.2.5) and syncing data to a postgres database. When setting up the connection I had the values as show in the screenshot 
<img width="1385" alt="image" src="https://github.com/airbytehq/airbyte/assets/88639882/7bee6bd0-62ea-48cb-9a6d-add0e6737104">

I have the same airbyte running in a different environment with mongo source connect (v1.0.7) and syncing data does not produce the correct schema when scanning the source db:
<img width="1376" alt="image" src="https://github.com/airbytehq/airbyte/assets/88639882/20e5ef00-6911-40d2-ab2f-e35e759c2bb8">

As you can see that not all the data showing up in the new version and I have increased the sample size of the connect to various amounts with no change in this.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Closing this issue as we've made significant changes to the connector since it was created.  Can you please try again with the latest Airbyte platform and connector?
