### ISSUE TITLE
Source S3: no longer supports tab-delimited (TSV) configurations

### ISSUE THREAD

**Issue by dashirov** [airbytehq/airbyte#32447]
### Connector Name

source-s3

### Connector Version

4.2.0

### What step the error happened?

Configuring a new connector

### Relevant information

The connector no longer honors '\t' (`tab`) into delimiter control of the configuration user interface. This was previously addressed in a workaround pull request #9163. When configuring the connector for TSV files:
1. Documentation insists on use of a two character sequence \t
2. UI Configuration modal accepts a two character sequence \t
3. JSON-serialized configuration states the delimiter is serialized as a string "\\t" 
4. An attempt to test configuration fails with error "Configuration check failed Something went wrong in the connector. See the logs for more details."

[check_connection_source-failure-e1256f04-27d5-4218-9ad2-3b789e07be1e.txt](https://github.com/airbytehq/airbyte/files/13323649/check_connection_source-failure-e1256f04-27d5-4218-9ad2-3b789e07be1e.txt)

5. Integration tests do not feature tab-separated files as use cases

### Relevant log output

```shell
unexpected value; permitted: 'parquet' (type=value_error.const; given=csv; permitted=['parquet'])
streams -> 2 -> format -> filetype
  unexpected value; permitted: 'unstructured' (type=value_error.const; given=csv; permitted=['unstructured'])
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 42, in <module>
    launch(source, _args)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 209, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 109, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.check(source_spec, config))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 133, in check
    check_result = self.source.check(self.logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 82, in check
    check_succeeded, error = self.check_connection(logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_based_source.py", line 63, in check_connection
    streams = self.streams(config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_based_source.py", line 114, in streams
    raise ConfigValidationError(FileBasedSourceError.CONFIG_VALIDATION_ERROR) from exc
airbyte_cdk.sources.file_based.exceptions.ConfigValidationError: Error creating stream config object. Contact Support if you need assistance.
```

### Contribute

- [x] Yes, I want to contribute
```[tasklist]
### Tasks
```

**Comment by dashirov** [comment]
<img width="1607" alt="Screenshot 2023-11-10 at 5 40 39 PM" src="https://github.com/airbytehq/airbyte/assets/1753399/dac1a648-2ff8-4176-b993-cafcef05857c">

**Comment by dashirov** [comment]
I would say a patch may look like this:

```
Index: airbyte-integrations/connectors/source-s3/source_s3/v4/source.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/airbyte-integrations/connectors/source-s3/source_s3/v4/source.py b/airbyte-integrations/connectors/source-s3/source_s3/v4/source.py
--- a/airbyte-integrations/connectors/source-s3/source_s3/v4/source.py	(revision e67543cb66b18cefb5c5ac3a9cee16466844f725)
+++ b/airbyte-integrations/connectors/source-s3/source_s3/v4/source.py	(date 1699673822308)
@@ -27,6 +27,8 @@
         validate the config against the new spec.
         """
         config = super().read_config(config_path)
+        if config.get("format", {}).get("delimiter") == r"\t":
+            config["format"]["delimiter"] = "\t"
         if not self._is_v4_config(config):
             parsed_legacy_config = SourceS3Spec(**config)
             converted_config = LegacyConfigTransformer.convert(parsed_legacy_config)

```
But I'm not too familiar with airbyte_cdk and how things are done here.

**Comment by sharon-clue** [comment]
i have the same issue
does anyone work on it already?

**Comment by dashirov** [comment]
The only workaround I found was to manually update the connector configuration directly in the airbyte database backend

**Comment by dtiesling** [comment]
Also effected by this issue. 

Is downgrading the source a workaround? I've tried several versions but haven't found a version where \t works.

Is this bug scheduled for a fix at all or @dashirov are you already working on contributing a fix?

**Comment by dtiesling** [comment]
Hi @Diana-Vait, it looks like you triaged this issue, I was hoping you could provide some feedback. 

I put a quick draft PR in with a unit test that reproduced the error and a fix. I've run out of time to build and test locally at the moment.

Is this an acceptable PR to submit? Or is there a core engineer with better knowledge of the codebase that could give this a glance to see if it really is this simple of a fix?

If not I'll try to carve out more time later to fully verify the fix and pull the PR out of draft status.

**Comment by spra85** [comment]
👍 here
