### ISSUE TITLE
[source-appsflyer] 0.1.0 is obsolete, AppsFlyer API is requesting migration to V2 tokens

### ISSUE THREAD

**Issue by dashirov** [airbytehq/airbyte#32446]
### Connector Name

connector-appsflyer

### Connector Version

0.1.0

### What step the error happened?

Configuring a new connector

### Relevant information

AppsFlyer API is rejecting V1 authentication and authorization tokens. It requires an immediate switch to V2 tokens.

### Contribute

- [X] Yes, I want to contribute

**Comment by dashirov** [comment]
A patch is available in a forked repository here: https://github.com/dashirov/airbyte/commit/e67543cb66b18cefb5c5ac3a9cee16466844f725

I can request a PR if the community is OK with it.

**Comment by aoelvp94** [comment]
@dashirov Hi, I am interested on this issue, are you using that patch? Is that working?
