### ISSUE TITLE
MySQL: Doesn't sync data on first run

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#32456]
### Connector Name

source-mysql

### Connector Version

v3.1.3

### What step the error happened?

During the sync

### Relevant information

* Start local OSS Airbyte.
* Start local mysql db:
```
docker run --name mysql-binlog -e MYSQL_ROOT_PASSWORD=my-secret-pw \
-p 3306:3306 \
-v /mydatadir/var/lib/mysql \
mysql --binlog-format=ROW --binlog-row-image=full --server-id=1
```
* Log into `docker exec -it mysql-binlog mysql -uroot -p`
* Create some data
```
-- Create the database
CREATE DATABASE TestDB;

-- Use the created database
USE TestDB;

-- Create the 'Users' table
CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

-- Insert dummy data into the 'Users' table
INSERT INTO Users (name, email) VALUES 
('Alice Smith', 'alice.smith@example.com'),
('Bob Johnson', 'bob.johnson@example.com'),
('Carol Davis', 'carol.davis@example.com'),
('David Martinez', 'david.martinez@example.com'),
('Eva Lopez', 'eva.lopez@example.com');
```
* Set up an incremental CDC connection for the `TestDB` database and the `Users` table (host: `host.docker.internal`)
* Run sync - no data is synced
* Run sync again - no data is synced
* Add some more rows to the User table
* Run sync again - the new rows are synced, the old ones are not:

<img width="1196" alt="Screenshot 2023-11-13 at 11 26 11" src="https://github.com/airbytehq/airbyte/assets/1508364/4f4c81a4-f69e-452f-903d-5070d0132dcf">

First sync:
[aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_69_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13333822/aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_69_attempt_1_txt.txt)

Second sync: [aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_70_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13333826/aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_70_attempt_1_txt.txt)

Third sync:  [aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_71_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/13333828/aaff10fd_7e8e_498c_a992_a8fff88a7f08_job_71_attempt_1_txt.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by xiaohansong** [comment]
I tried these steps but I got all of initial 5 rows synced up:

<img width="1456" alt="Screenshot 2023-11-13 at 12 31 39 PM" src="https://github.com/airbytehq/airbyte/assets/5505742/9d11bcd0-c7e7-42e2-9ac6-37b5b9959b4f">

Here is the replication setting:
<img width="1590" alt="Screenshot 2023-11-13 at 12 32 39 PM" src="https://github.com/airbytehq/airbyte/assets/5505742/8d046e5f-bc93-4a1b-a598-3d8cb3ef5763">

Did I miss anything? @flash1293

**Comment by prateekmukhedkar** [comment]
@flash1293 Can you make sure that Connection State (under Settings tab, Advanced) is empty before you start the first sync? Or just hit reset.

**Comment by flash1293** [comment]
Resetting didn't help, but I updated my platform, the MySQL connector and created a new connection and it works fine with that. Not sure how I got into that state, but I think we can shelf it for now if no-one else is having the problem. I will recommend the same thing to the user.
