### ISSUE TITLE
Source Freshdesk: declare cursor fields

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3249]
## Tell us about the problem you're trying to solve
#3180 is happening because the Freshdesk source does not declare cursor fields in the catalog it outputs. We should output the cursor fields in the Freshdesk connector to prevent such issues.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368165154136) by [Unito](https://www.unito.io)

**Comment by vovavovavovavova** [comment]
in Source FresDesk and both in #3180  the configuration file named as `configured_catalog.json` . This configuration, like #3180 example , already contains empty cursor field 
```"source_defined_cursor": true,
  (...)
  "cursor_field": [],```

That was fixed in #2776 by adding default value if cursor field is empty.
