### ISSUE TITLE
Source Github: Allow rotating between multiple API keys

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3250]
## Tell us about the problem you're trying to solve
Github has stringent API key limits. Users have asked to have the connector supply providing multiple API keys and then have the connector rotate between them. 

The fastest way to do this would be to implement it directly in the connector. But we can also make this available to any connector by adding this as an authenticator in the CDK.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368165169868) by [Unito](https://www.unito.io)

**Comment by gaart** [comment]
@sherifnada 

We just merged this feature into master and released a new version of the connector. 

Upgrade your connector to version 0.1.6 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
