### ISSUE TITLE
Remove Normalization From Clickhouse

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#32528]
We will not be migrating Clickhouse to Destinations V2 at this time, instead we will remove normalization and update the raw table format
- [x] Remove Normalization option and normalization container
- [x] Implement New Raw Table Format w/o migrator
- [x] Add Breaking change window of 3 months
- [x] Update connector docs

**Comment by mattdavenport** [comment]
@jbfbell We are currently evaluating Airbyte+Clickhouse for a BI platform. Just so I'm clear, this task would effectively remove the method by which data is moved from a source to our Clickhouse destination into actual columns (normalization), and at that point Airbyte would only support inserting raw JSON blobs from sources into the Clickhouse destination?

**Comment by jbfbell** [comment]
@mattdavenport you are correct, we will update Clickhouse to use the new [Destination V2 Raw Table Format](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2/#breakdown-of-breaking-changes) (the table with a JSON blob of the record data). 

Airbyte will continue to support custom [DBT transformations via DBT cloud](https://docs.airbyte.com/cloud/managing-airbyte-cloud/dbt-cloud-integration/) which might be a good alternative.

**Comment by jbfbell** [comment]
Potentially could have issues:

- not required to upgrade CDK, but might make our lives easier
- updating to the new CDK version could also make our lives harder

**Comment by MaxMusing** [comment]
@jbfbell are there any plans to migrate ClickHouse to Destinations V2? Or rough estimate in how much work it would take? Normalization for ClickHouse would be greatly appreciated 🙏
