### ISSUE TITLE
Unable to build  image

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#32523]
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

master

### What step the error happened?

None

### Revelant information

I am unable to build image from main repo

./gradlew :airbyte-integrations:connectors:source-dynamodb:build 

### Relevant log output

```shell
> Task :checkPython FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkPython'.
> Python not found: .venv/bin/python3.11. This must be a bug of virtualenv support, please report it (https://github.com/xvik/gradle-use-python-plugin/issues). You can disable virtualenv usage with 'python.scope = USER'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
12 actionable tasks: 1 executed, 1 from cache, 10 up-to-date
```

**Comment by marcosmarxm** [comment]
From error you have a problem with your local setup (pyenv and Python version).
Make sure you have the `airbyte-ci` installed and try again.
