### ISSUE TITLE
Source Slack: bugfix incorrect thread messages timestamp

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3254]
## Description
In the Slack connector `threads` output stream, we expect the `ts` field to refer to the timestamp of the thread reply, and `thread_ts` to refer to the timestamp of the parent message which started the thread. See an example of this here in the [Slack API](https://api.slack.com/methods/conversations.replies#Response).

However, this is not working currently because the Singer tap we use [overwrites](https://github.com/singer-io/tap-slack/blob/master/tap_slack/transform.py#L37) the `thread_ts` field with the value of `ts`. This causes us to lose information about the parent timestamp by overwriting it with the timestamp value of the thread message itself. 

The second problem is that [`ts` is being formatted as an ISO8601 date](https://github.com/singer-io/tap-slack/blob/master/tap_slack/transform.py#L38) while `thread_ts` is not (`ts` is first copied into `thread_ts` then formatted into the ISO string). 

## Acceptance Criteria
1. Do not overwrite the value of `thread_ts` with `ts`
2. Format both strings as ISO dates (and make sure the catalog output by `discover` accurately reflects this)

**Comment by VasylLazebnyk** [comment]
@htrueman please leave the outcome
@sherifnada please review then, looks like for now we can not move further here

**Comment by sherifnada** [comment]
@htrueman @VasylLazebnyk just left a review
