### ISSUE TITLE
Rewrite sendgrid source using HTTP CDK

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3255]
## Tell us about the new integration you’d like to have
The [Sendgrid source](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-sendgrid/source_sendgrid/client.py) was written before we created the new python HTTP CDK. We should rewrite it using the CDK before implementing #1382. 

Also we should make sure to update the [documentation](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/sendgrid.md) to include the correct streams because it is currently out of date.

**Comment by htrueman** [comment]
Found bug that new implementation that there are no records in `stats_automations` and `segments` streams. But these streams actually has records (tested with code from master branch).
Fixing that issue.

**Comment by htrueman** [comment]
> Found bug that new implementation that there are no records in `stats_automations` and `segments` streams. But these streams actually has records (tested with code from master branch).

It was just wrong `data_field`, should be `data_field = "results"` for these sreams instead of `data_field = "result"`
