### ISSUE TITLE
MySQL connector failures 

### ISSUE THREAD

**Issue by Jamesvgonzalez** [airbytehq/airbyte#32570]
### Connector Name

Source - MySQL 

### Connector Version

3.1.5

### What step the error happened?

During the sync

### Relevant information

Here is the workspace: 

https://cloud.airbyte.com/workspaces/5d3f85f0-d3ce-4eae-8c6a-5e630426a453/connections/6e932388-89fe-4a49-8018-72f10bbf6ffc/job-history

Apparently, the connection broke when he changed all the syncs to incremental. Could be something to due with "whether the mysql user used for syncs has SLAVE or REPLICATION privilege.  

### Contribute

- [ ] Yes, I want to contribute

**Comment by Jamesvgonzalez** [comment]
@nguyenaiden

**Comment by evantahler** [comment]
We will not be working on this issue in the near-term.
