### ISSUE TITLE
Source Facebook: Allow for non-business accounts to connect

### ISSUE THREAD

**Issue by kmaxwell001** [airbytehq/airbyte#32572]
Currently, Airbyte requires a business ad-account in order to connect to our facebook source, however I don't believe this is a requirement by Facebook (Fivetran allows non-business accounts).

It looks like this code is blocking certain prospects from using our Facebook connector:

            if account_info.get("is_personal"):
                message = (
                    "The personal ad account you're currently using is not eligible "
                    "for this operation. Please switch to a business ad account."
                )

**Comment by tolik0** [comment]
The PR https://github.com/airbytehq/airbyte/pull/32731, which removes the check for a personal account, has already been merged into the dev branch. Users should be able to create connections with non-business accounts once the code freeze ends. Please let me know if users can successfully sync Facebook Marketing data after this release.
