### ISSUE TITLE
Proposal for regression testing source connectors

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#32602]
[placeholder] @girarda to fill in

**Comment by natikgadzhi** [comment]
Where can I read more? I _think_ I saw a related doc somewhere, but I'm getting slightly lost in them.

**Comment by girarda** [comment]
@natikgadzhi [the proposal is here](https://docs.google.com/document/d/1PhJyIbFbhGanLuAT9WyBBhOFccw05DcJ0yqy1bxfKGQ/edit#heading=h.w6y3nyyia0ks)

**Comment by girarda** [comment]
closing. will revisit in Q1 as part of debugging tools
