### ISSUE TITLE
Gitlab CE on premise instance issues.

### ISSUE THREAD

**Issue by ameyw** [airbytehq/airbyte#3265]
## Expected Behavior
Gitlab connector :  Should allow adding urls which do not have gitlab.com . As on premise instances will have own custom domains

## Current Behavior
Url which do not contain gitlab.com shows error due to validations

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._

## Steps to Reproduce
1.Add title 

1. Add connector as gitlab
1. Add a custom url

## Severity of the bug for you
 High 

## Airbyte Version
Foun

## Connector Version (if applicable)
0.1.1

## Additional context
_Environment, version, integration..._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368230048832) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@ameyw thanks for creating the issue! I have some questions about this. 

Is the Gitlab on-prem API guaranteed to be the same as the cloud one? Which version of GL / the GL API are you running?

**Comment by ameyw** [comment]
@sherifnada The CE and EE versions have similar api. we are currently on 13.9

**Comment by ameyw** [comment]
Is this issue resolved ..

**Comment by sherifnada** [comment]
@ameyw we're currently rewriting the Gitlab connector to move away from the Singer-based one. Once that is done it should be fairly straightforward to add this functionality. Would you be open to creating a PR to support it?

**Comment by Zirochkaa** [comment]
This ticket is blocked on #6822.
