### ISSUE TITLE
[source-hubspot] not allows incremental sync for `property_history` like docs suggest

### ISSUE THREAD

**Issue by masonhopkins** [airbytehq/airbyte#32652]
### Connector Name

source-hubspot

### Connector Version

1.7.0

### What step the error happened?

Other

### Relevant information

When setting up the connection from our Hubspot source to our destination, the `property_history` stream only gives full refresh append or overwrite for sync types, as opposed to incremental as the [connector's docs](https://docs.airbyte.com/integrations/sources/hubspot?_gl=1*d9qrhy*_gcl_aw*R0NMLjE2OTk1NzA2NDkuQ2owS0NRaUFvN0txQmhEaEFSSXNBS2haNHVnMHBxeVZsOG5fd25PMHVrWnk3V2FBVWFMMWRIT1psZ1QwZmRyNjZZeWFJNkRFT2tSN3d1Y2FBa2psRUFMd193Y0I.*_gcl_au*OTM5OTQzNTEuMTY5OTM3NjgwOS45OTU3NTUxMDQuMTcwMDI0MDAwNi4xNzAwMjQwMDA2*_ga*MTk4MDI0NTgzNy4xNjk5Mzc2ODA5*_ga_EDX3TPP6H7*MTcwMDIzOTg2Mi41LjEuMTcwMDI0MDY2Mi4wLjAuMA..#supported-streams) suggest should be available.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Please check documentation related to the special stream:
https://docs.airbyte.com/integrations/sources/hubspot#notes-on-the-property_history-streams
