### ISSUE TITLE
[destination-databricks] utilizes S3, but still list access key as required even though they aren't (IRSA)

### ISSUE THREAD

**Issue by johnsmclay** [airbytehq/airbyte#32684]
### Connector Name

destination-databricks

### Connector Version

1.1.0

### What step the error happened?

Configuring a new connector

### Relevant information

In the [resources/spec.json](https://github.com/airbytehq/airbyte/blame/9dae0d3c2102a65ce258e3c7215b4da671d46d41/airbyte-integrations/connectors/destination-databricks/src/main/resources/spec.json#L102) the parameters "s3_access_key_id" and "s3_secret_access_key" are listed as required and they probably shouldn't anymore.
It uses the same "io.airbyte.cdk.integrations.destination.s3.S3DestinationConfig" object for config which supports using role-based auth instead of an access key.
Probably would need to update [this part that creates the config in databricks connector](https://github.com/airbytehq/airbyte/blob/9dae0d3c2102a65ce258e3c7215b4da671d46d41/airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/s3/DatabricksS3StorageConfigProvider.java#L18-L28) to be like [the "official" S3 connector](https://github.com/airbytehq/airbyte/blob/9dae0d3c2102a65ce258e3c7215b4da671d46d41/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Destination.java#L18-L20).

The same is the case for [Starburst Galaxy](https://github.com/airbytehq/airbyte/blob/9dae0d3c2102a65ce258e3c7215b4da671d46d41/airbyte-integrations/connectors/destination-starburst-galaxy/src/main/java/io/airbyte/integrations/destination/starburst_galaxy/StarburstGalaxyS3Destination.java). I don't use that one, but it should also be an easy fix to make those parameters optional.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Closing - we've moved to Unity Catalog in the destination
