### ISSUE TITLE
Python CDK: implement best-effort syncing of streams

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3268]
## Tell us about the problem you're trying to solve
Let's say my source has 10 streams. 9 of them sync successfully, but 1 fails. Depending on the order of the sync, if the bad stream syncs first, the whole source will not sync any data. 

## Describe the solution you’d like
Instead we should `try/except` syncing every stream. If the stream fails, we should collect the error, skip syncing that stream and move to the next stream. At the end of the sync if we have collected any exceptions, fail the sync. 

This way, we make a best-effort in syncing data but still accurately reflect failures. 

we should report all the streams that failed
we should probably output one trace message per failure and eventually the platform should handle multiple failures. If they are the same they get grouped in sentry. If they are not they are split as separate incidents.

## Future improvements 
This might be enhanced in the future by outputting a specific exit code which indicates "partial failure" instead of today where 0 means success and anything else means failure with nothing in between.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368106923598) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
grooming notes: 
- we may even want to think of these as threads / futures rather than a for loop that accumulates failures. programmatically it may be better. 
- we should report all the streams that failed
- we should probably output one trace message per failure and eventually the platform should handle multiple failures. If they are the same they get grouped in sentry. If they are not they are split as separate incidents. 

TODO; 
- [ ] create a ticket for the platform to handle multiple failure reasons and report all of them to sentry. Keep in mind that there is a UI component here as well. it only shows one failure reason today.

**Comment by marcosmarxm** [comment]
I'll start scoping project next week (week no 35)

**Comment by evantahler** [comment]
Closing this in favor of https://github.com/airbytehq/airbyte/issues/16639
