### ISSUE TITLE
[Roadmap] Improved user invitation to workspaces/organizations

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#32712]
Allow to invite non SSO (Single Sign-On) users into your SSO organization as well as inviting non SSO users to get access to your organization's workspaces.

**Comment by nataliekwong** [comment]
We're continuing to progress on this project and expect to make this available in the quarter from Feb - April.

**Comment by timroes** [comment]
This has been scoped down to only allow non SSO users being invited to workspaces within an organization (not to the organization as organization members). This has been done by now. We still want to allow invitations into organizations and will likely work on this in the second half of 2024.
