### ISSUE TITLE
[Roadmap] Read-only roles in RBAC

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#32713]
Enable users to be added to workspaces and organizations as read-only, so they won't be able to make modifications to connections/sources/destinations.

**Comment by PavelSusloparov** [comment]
Upvote!

**Comment by PavelSusloparov** [comment]
Have you considered updating the terraform provider resources to facilitate user management from code?

**Comment by timroes** [comment]
This is now available in Enterprise and in Cloud with Teams addon.
