### ISSUE TITLE
[Roadmap] Custom Connectors available through Airbyte API & Terraform Provider

### ISSUE THREAD

**Issue by rileybrook** [airbytehq/airbyte#32744]
Custom Connectors are available through Airbyte API & Terraform Provider for Cloud, OSS and Self-Managed. 

Release target of February.

**Comment by meyerovb** [comment]
[Doc](https://docs.airbyte.com/integrations/custom-connectors) says this is scheduled for this month, any update?

**Comment by leonardovida** [comment]
I second @meyerovb question. Any upcoming plan of releasing this feature in the upcoming days @rileybrook? For us it's a "make or break" feature for a large deployment for clients. Otherwise we'd need to look elsewhere in the market, but we wouldn't want to!

**Comment by nataliekwong** [comment]
We're still planning on releasing this! We expect this to be available in the next few weeks as we wrap up the remaining items for the quarter. We'll update the issue here when this is officially available.

**Comment by nataliekwong** [comment]
You can now create custom connectors through the [API](https://reference.airbyte.com/reference/createsource). We are planning to also add this to Terraform in the next few weeks.

**Comment by miguelduarte18** [comment]
I thought this feature would be about adding custom Docker-based connectors into Airbyte.

The [Custom connectors](https://docs.airbyte.com/integrations/custom-connectors) page says:
```
Custom connectors are currently exclusive to Airbyte Open-Source deployments. However, there are plans for their release on Airbyte Cloud, scheduled for January 2024. You can track the progress on this development [here](https://github.com/orgs/airbytehq/projects/37?pane=issue&itemId=45471174).
```

And it points to the present item. I think this was a bit unclear? 

But regardless, can you share some details on the inclusion of custom Docker-based connectors in the cloud version?

**Comment by nataliekwong** [comment]
Hey @miguelduarte18, feel free to reach out to me directly at natalie@airbyte.io. we can enable Docker-based connectors for your Cloud workspace.

**Comment by tsopgniduhamel** [comment]
> You can now also [create custom connectors via our Terraform Provider](https://reference.airbyte.com/reference/using-the-terraform-provider#3-create-a-source):
> 
> ```
> resource "airbyte_source_custom" "custom" {
>   name = "custom source connector"
>   workspace_id = var.workspace_id
>   definition_id = "d96b3d38-a35c-4f68-902d-212f4b214ed2"
>   configuration = "{\"configuration_1\": \"setting_1\"}"
> }
> ```

Hello, 

please how to know the list of configs we can put tho create the custom connector ?

please any link ? any blog or article ?

Thanks in advance

**Comment by kschutt** [comment]
How does this work with Airbyte Cloud's Custom Connector Builder? We've tried to use the UUID from the URL, see `connector-uuid` below. However, when we set the presumed `connector-uuid` as the `definition_id` in the `airbyte_source_custom` Terraform provider, we receive a `resource-not-found` error. 

Is there something we are missing? Is this available yet for Airbyte Cloud's Builder?

```
https://cloud.airbyte.com/workspaces/{{ workspace-uuid }}/connector-builder/edit/{{ connector-uuid? }}
````

**Comment by Elvislim1991** [comment]
> How does this work with Airbyte Cloud's Custom Connector Builder? We've tried to use the UUID from the URL, see `connector-uuid` below. However, when we set the presumed `connector-uuid` as the `definition_id` in the `airbyte_source_custom` Terraform provider, we receive a `resource-not-found` error.
> 
> Is there something we are missing? Is this available yet for Airbyte Cloud's Builder?
> 
> ```
> https://cloud.airbyte.com/workspaces/{{ workspace-uuid }}/connector-builder/edit/{{ connector-uuid? }}
> ```
> 
> Edit: We were able to figure out the `sourceDefinitionId` by inspecting the `https://cloud.airbyte.com/api/v1/connector_builder_projects/get_with_manifest` call and parsing out the `$.builderProject.sourceDefinitionId` for anyone who gets stuck here like we did

Thanks, managed to find the definition_id through your comment

**Comment by lmossman** [comment]
@Elvislim1991 @kschutt you should also be able to get the `sourceDefinitionId` of your custom builder connector by going to `Sources > New source > Custom tab` and then click on your custom connector. The `sourceDefinitionId` is the UUID at the end of that page's URL:
<img width="1015" alt="Screenshot 2024-07-24 at 4 54 21 PM" src="https://github.com/user-attachments/assets/aa838e17-4f07-4ccb-8f5c-f8be2e57f526">

Is that sufficient for your needs? It should at least be better than inspecting network requests

**Comment by DaanDuppen** [comment]
My current understanding of deploying a connection with a custom source between two workspaces (dev -> prod) in Airbyte cloud is as follows:
1. I manually copy-paste the custom source yml manifest from dev to prod workspace
2. In prod I manually go to "source -> new -> custom" to get the id and fill this in in my terraform source definition
3. I run terraform to create the source
In the open source version of airbyte step 1 and 2 can actually be automated using the config api (until it is depricated) but it seems this is not available for the paid version. Am I correct in saying there is currently no way of automating step 1 and 2 in the cloud version of airbyte? Or am I missing something?

Thanks in advance!
