### ISSUE TITLE
[source-monday] Upcoming Monday API Version Breaking Change

### ISSUE THREAD

**Issue by nlanziner** [airbytehq/airbyte#32785]
### Connector Name

source-monday

### Connector Version

1.1.3

### What step the error happened?

Other

## Problem
The Monday API has released a version update, `2023-10` that contains [numerous breaking changes](https://developer.monday.com/api-reference/docs/api-versioning#release-schedule). 
![image](https://github.com/airbytehq/airbyte/assets/50338474/b9e1d920-84a7-4c74-bb4b-2634ed34acec)

Right now, there are no issues with the connector, because the Monday API defaults to the `2023-07` version, which is compatible with the source-monday connector. However, this will no longer be the case on January 15, 2024.

## Quick Fix Suggestion
To avoid the Monday connector fully breaking in January, we can continue to use the `2023-07` version of the API. This requires only a minor modification to the [requestor here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-monday/source_monday/manifest.yaml#L14-L18) to include a header with the api version specified.
`'API-Version' : '2023-07`.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/34108
