### ISSUE TITLE
support proxying the webapp to a non-root route

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3280]
A user is trying to proxy the server and webapp to routes using nginx:

```
    server {
        server_name ...;
        listen      443 ssl;
        ssl_certificate     ...;
        ssl_certificate_key ...;
        proxy_set_header Host $host;
        client_header_buffer_size       3M;
        large_client_header_buffers 4   3M;
        location /airbyte/ {
            proxy_pass http://airbyte-webapp:80/;
        }
        location /airbyte-server/ {
            proxy_pass http://airbyte-server:8001/;
        }
    }
```

I _think_ this would just involve updating `routes.tsx` to read from a new environment variable that allows setting a prefix for the various routes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368165402701) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@jrhizor can you explain a little more what support for this should look like? specifically how you imaging it being configured.

**Comment by Jasopaum** [comment]
Hello 👋 
I think I was at the origin of this feature request. What I had in mind is something like what airflow does (see [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html))

**Comment by jrhizor** [comment]
I was thinking we could use an environment variable for the prefix and use that in the webapp. I think we may need something similar for the API as well.

**Comment by jrhizor** [comment]
This also might introduce the possibility of using `kubectl proxy` to interact with the UI and API.

**Comment by LaRiffle** [comment]
Hey! 👋 
Any update on this side?

**Comment by jrhizor** [comment]
@LaRiffle There have been some frontend redirection changes that should make this easier. We haven't prioritized this ticket yet (and probably won't get to it for a while longer). If you (or someone else who's interested) wants to work on contributing this feature we could point you in the right direction.

**Comment by LaRiffle** [comment]
Thanks a lot for the update!

**Comment by japrogramer** [comment]
I'm also trying to proxy airbyte and have had no luck. all resources are expected to be in the root base path.
