### ISSUE TITLE
Source Ashby: more coverage of the relevant fields

### ISSUE THREAD

**Issue by imrehg** [airbytehq/airbyte#32813]
### What area the feature impact?

Connectors

### Relevant Information

The [Ashby source](https://docs.airbyte.com/integrations/sources/ashby) is missing a number of fields from the Ashby API:

- [interview schedules](https://developers.ashbyhq.com/reference/interviewschedulelist)' interview events
- [interview plans](https://developers.ashbyhq.com/reference/interviewplanlist)
- [interviews](https://developers.ashbyhq.com/reference/interviewlist)
- [interview stages](https://developers.ashbyhq.com/reference/interviewstagelist)

... among others. (These seem to be the main ones in practice that limit the use of the connector at its current stage).

**Comment by marcosmarxm** [comment]
Thanks @imrehg I'll review during the week.

**Comment by natikgadzhi** [comment]
@imrehg I've seen Source Ashby in Builder in the wild — I think we'll convert it to manifest-only first, and then add things to it.

**Comment by natikgadzhi** [comment]
Hey @imrehg! So, we've migrated the current Ashby implementation to be fully Builder compatible. Meaning, you should be able to "open" it in Builder and add anything you need, and then contribute back the PR.
