### ISSUE TITLE
[EPIC] Support Large Records

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#32825]
[Doc](https://docs.google.com/document/d/1eujDX1katRSwfWEploscqPthoO6etV5_q-Xy7wVn4vw/edit#heading=h.epkyx6u3tsnh)

There will always be sources that emit records too big for either the destination or platform to handle.  The [canonical example](https://github.com/airbytehq/airbyte/issues/31575#issuecomment-1863293991) is `source-shopify` emitting a `order` record which contains lots of items which then can't fit in a `destination-redshift` field (which has a 16mb limit).  This project is to allow any part of an Airbyte sync, which can't handle a record to:
* `NULL`-out the offending field
* Append error information to the record about what was modified and why
* Present these errors to users in the destination's `_airbyte_meta.errors` column

This follows the principal that:
* Data errors (too large) shouldn't cause sync errors (sync failures)
* Record modifications shouldn't happen, and if they do, lineage of the change needs to be perserved.
* Partial records useful, and better than no record at all

**Comment by evantahler** [comment]
A little more context on this topic is [here](https://github.com/airbytehq/airbyte/issues/31575#issuecomment-1841906115)

**Comment by evantahler** [comment]
This project requires an update to the Airbyte Protocol, tracked here: https://github.com/airbytehq/airbyte-protocol/pull/56

**Comment by rohaldb** [comment]
Hi @davinchia @evantahler I can see this as being completed, but no PR referencing this issue - has it in fact been completed? And if so, what is estimated release date? 
Thanks so much! This is a real blocker for us
