### ISSUE TITLE
[Enhancement] Do not type and dedupe if zero records emitted

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#32845]
We run typing and deduping at the end of a sync even if no records were emitted. Consider only typing and deduping if more than zero records were emitted

**Comment by cynthiaxyin** [comment]
This was a problem in airbytehq/oncall#3633 - the source emitted no records but T&D still ran and the total sync time was ~26-28 min (Postgres to Snowflake).

See https://airbytehq-team.slack.com/archives/C0671U3NTK8/p1700879047993029:
>Our incremental syncs are too long and T&D should be avoided when unnecessary. 0 record syncs still ran for 25+ minutes because they were running normalization.

**Comment by jbfbell** [comment]
Consider running and additional sql query prior to typing and deduping which checks for records which have `null` `loaded_at` column and only execute typing and dedpuing if it is greater than zero.

**Comment by edgao** [comment]
this was completed in https://github.com/airbytehq/airbyte/pull/33232 last week
