### ISSUE TITLE
[Roadmap] Stream-scoped breaking changes

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#32855]
Many breaking changes come with clear guidance indicating that the change only affects certain streams. 

In this case, only users syncing the affected streams will be notified and required to opt in. Users of the connector who are not syncing the affected streams will get the new latest version immediately with no action required.

**Comment by nataliekwong** [comment]
We're continuing to progress on this project and expect to make this available in the quarter from Feb - April.

**Comment by erohmensing** [comment]
This has been live since the beginning of February!
