### ISSUE TITLE
Source Bing Ads: Add Account Id Field to Connector

### ISSUE THREAD

**Issue by matthewbelair** [airbytehq/airbyte#32875]
### What area the feature impact?

Connectors

### Relevant Information

I need the ability to select the Account ID when creating the source. This could take the form of a new field in the UI. This would be useful to filter the streams on the selected Account ID and it would align the connector with other marketing-related connectors that allow the accounts to be specified (i.e. Facebook Marketing, Google Ads, etc.).

The Account ID can be [included in the Request Header elements](https://learn.microsoft.com/en-us/advertising/reporting-service/submitgeneratereport?view=bingads-13#request-header) when generating reports with the API.
Also useful: [Get Your Account and Customer IDs](https://learn.microsoft.com/en-us/advertising/guides/get-started?view=bingads-13#get-ids).

I currently have access to too many accounts with my user and the Bing Ads connector is unable to retrieve all the data.

**Comment by marcosmarxm** [comment]
> I currently have access to too many accounts with my user and the Bing Ads connector is unable to retrieve all the data.

It means when you try the current connector the sync failed because of permission issues?

**Comment by matthewbelair** [comment]
Currently, the sync fails because it takes too long to get the data from all ad accounts for which I have access under my Microsoft user. After a few hours, I need to manually cancel the sync.

I think that the syncs are looping (partitioning?) through each account for every stream, where I'd rather select only a subset of accounts (or one).

**Comment by matthewbelair** [comment]
Resolved with #33095 which gives the option to filter by account name.
