### ISSUE TITLE
[Redshift V2] Confirm Normalization Does not run for redshift v2

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#32903]
Make sure that:
- Transformations page where raw data or v1 normalization interacts correctly
- Shell script and platform sending correct env variable for in connector normalization
- Test OSS and Cloud

**Comment by cynthiaxyin** [comment]
[confirmed](https://airbytehq-team.slack.com/archives/C065B1LSTL7/p1701362647537519?thread_ts=1701362083.937009&cid=C065B1LSTL7) normalization is automatically skipped + Transformations tab can have any selection
