### ISSUE TITLE
Controlling resources for stderr, stdin, heartbeat...

### ISSUE THREAD

**Issue by monik-a** [airbytehq/airbyte#32923]
### Discussed in https://github.com/airbytehq/airbyte/discussions/32863

<div type='discussions-op-text'>

<sup>Originally posted by **monik-a** November 28, 2023</sup>
We have the newest Airbyte deployed (actually, we have two: 0.50.3 and 0.50.34) on Kubernetes. 
We incorporated resource requests/limits for all components and jobs too, but I couldn't find anything on how I can change the requests/limits values for `relay-stdout`, `relay-stderr`, `call-heartbeat-server` containers.
It'd be great if we could control them arbitrarily, but I want to at least even them out (request=limit).
I know it's managed somewhere [here](https://github.com/airbytehq/airbyte-platform/tree/main/airbyte-commons-with-dependencies/src/main/java/io/airbyte/commons/workers/config), but didn't find coresponding env variables or anything in the doc. 
Could you please point me in the right direction ? 🙏 </div>

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/discussions/32863
