### ISSUE TITLE
Add admin APIs for version pinning

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#32942]
# What

In order to power the Retool Admin UI, we need some admin-level APIs that allow creating/editing/deleting/listing scoped configuration entries relating to connector version configuration.

These APIs should call the scoped_configuration service.

Remember to auto set origin_id to the user that performs the api request when creating new config entries.

**Comment by bnchrch** [comment]
Enumerating API's (WIP)
*
