### ISSUE TITLE
When updating pipeline code the CI on the related PR should be run using the updated code

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#32947]
## Problem
If we change pipeline code in a PR, the CI is still run with a binary generated from the code on master

## Possible Solutions
1. 🚫 If pipeline code is edited -> pipx install (& don't download remote binary)
2. 👉 If pipeline code is edited -> wait for dev binary, then use dev binary
    * Rather than polling, we could make the test workflow dependent on the prerelease workflow.  
    * Look into passing GH artifacts around (which would save waiting for GCS and downloading) 
3. 🚫 Allow for a extra argument in the airbyte-ci pipelines that lets you target new binaries.

Qs:
* Worries about PIPX vs binary problems (eg SSL certs) that only appear in binary?
  * We could add a required check to not merge if the binary is not executable && exit 0

**Comment by evantahler** [comment]
RELEASE_URL=https://storage.googleapis.com/dev-airbyte-cloud-connector-metadata-service/airbyte-ci/releases AIRBYTE_CI_VERSION=b6892cb make tools.airbyte-ci.install
