### ISSUE TITLE
Add persistence methods / service for actor definition version pin

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#32940]
## What

Add methods to access actor_definition_version_pin

We should be able to:
- insert pin
- update pin by id
- delete pin
- get all pins for actor_definition_id
- get pin by actor_def_id + scope_id + scope_type

### Open Qs
Micronaut data? Services?

**Comment by bnchrch** [comment]
grooming:
- what is the right way to add these? Ask Bryce about micronaut data
- This is a new table, new service lets make sure to use micronaut data / kotlin
