### ISSUE TITLE
Source MSSQL: uses the CDC update method. When selecting the incremental synchronization mode, the decimal or numeric type data is synchronized to the destination with the wrong row data type.

### ISSUE THREAD

**Issue by UsenPang** [airbytehq/airbyte#32982]
### Connector Name

source-mssql

### Connector Version

3.0.0

### What step the error happened?

During the sync

### Relevant information

I created a type_decimal table in MSSQL 2016 and enabled CDC, as follows：

CREATE TABLE type_decimal  
(  
    id INT PRIMARY KEY,  
    tp_decimal DECIMAL(18, 4),  
    tp_numeric NUMERIC(18, 4),
		tp_float FLOAT
);  
  
INSERT INTO type_decimal (id, tp_decimal, tp_numeric, tp_float)  
VALUES (1, 123.45, 234.56, 123.45),  
       (2, 345.67, 456.78, 345.67),  
       (3, 567.89, 678.90, 567.89);

![Uploading QQ截图20231130232711.png…]()
    

### Relevant log output

```shell
The result of tp_decimal and tp_numeric is a string
{"id":1,"tp_decimal":"123.4500","tp_numeric":"234.5600","tp_float":123.45,"_ab_cdc_updated_at":"2023-11-30T15:27:44.595Z","_ab_cdc_lsn":"00000023:00000680:0001","_ab_cdc_event_serial_no":"null","_ab_cdc_cursor":170135806300000001,"_ab_cdc_deleted_at":null}

Normalized tabular data is Null
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by Xuquansheng** [comment]
UsenPang and i are one team, right now, we're trying to replicate both mssql 2016 database and postgresql 16 database into clickhouse with airbyte. Today, we found that airbyte platform have correctly converted data from Debezium connector Postgresql,which default mode is "decimal.handing.mode": "string", and not converted data from Debezium connector MSSQL, which default mode is same as   Postgresql. We also checked java code in airbyte source-postgres and  source-mssql, found that there is converting code for postgres, no converting code for mssql, which is not correct. Can someone take a look at converting code for postgres and add converting code for mssql? thanks.

**Comment by UsenPang** [comment]
I have checked the MSSQLConverter class and found that it has conversion for smallmoney data type, and this type of data can be correctly synchronized. However, there is no conversion code for decimal or numeric types. In contrast, the PostgresConverter has corresponding handling code and can synchronize correctly. If there is an issue in this area, I would greatly appreciate it being resolved.thanks.
Specific File: airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mssql/MSSQLConverter.java

**Comment by evantahler** [comment]
Closing this issue as we've revamped and certified source-mssql since this issue was written.  Please re-open a new issue if this persists.
