### ISSUE TITLE
Authenticate button in the Google Drive connector within the Airbyte open-source version

### ISSUE THREAD

**Issue by luongnv275** [airbytehq/airbyte#33036]
### Connector Name

DV360

### What type of integration

None

### Relevant Information

![image](https://github.com/airbytehq/airbyte/assets/103547802/fd140241-3524-40d9-ac81-65c984057aed)

### Contribute

- [ ] Yes, I want to contribute
```[tasklist]
### Tasks
```

**Comment by marcosmarxm** [comment]
Hello @luongnv275 the Oauth is only available in Cloud. Airbyte open source you need to manage the Oauth flow or use other type of credentials.
