### ISSUE TITLE
Clean up react-query updates that are triggered when a sync begins

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#33117]

**Comment by josephkmh** [comment]
Refining notes:
- Related to https://github.com/airbytehq/airbyte/issues/33116
- Whoever picks this up should keep in mind that @chandlerprall is currently working on stream/sync status work, which might overlap

**Comment by josephkmh** [comment]
Closing because we believe this has been fixed in the mean time with stream-centric UX work
