### ISSUE TITLE
Facebook Marketing Rate Limit

### ISSUE THREAD

**Issue by tuanchris** [airbytehq/airbyte#3313]
## Tell us about the problem you're trying to solve
Integration with Facebook Marketing is time-consuming since we have to request an increase in the Facebook API limit. We would have to submit a lot of information with a video to Facebook and the process takes too long. 

## Describe the solution you’d like
Integration should work right out the box without requesting an increase to Facebook. 

## Describe the alternative you’ve considered or used
* Airbyte should implement another authentication method for this source. For example, the integration made with Stitch is using Oauth authentication, and the connector seems to sleep for a period of time before calling the API (to get around the limit). 
* Airbyte should support selecting table & column for this source

## Are you willing to submit a PR?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368230623587) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@tuanchris thanks for opening this. We're working to implement OAuth method to add sources (https://github.com/airbytehq/airbyte/issues/768).

**Comment by jaimefr** [comment]
Hello, shouldn't this have fixed this issue? https://github.com/airbytehq/airbyte/pull/4820
