### ISSUE TITLE
Excessive disk usage during Postgres to BigQuery sync

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#3318]
## Expected Behavior
on-disk queue should not persist all the data till the very end of a sync. 
Data, that was already pushed to BQ, doesn't have to stay on disk. Using BQ Streaming API https://cloud.google.com/bigquery/streaming-data-into-bigquery or new Storage Write API https://cloud.google.com/bigquery/docs/write-api may help. Possibly core changes would be required as well.

Ideally disk usage should be not bigger than some reasonable buffer.

## Current Behavior
I performed a quite big sync "32.87 GB | 75,824,003 records | 6h 4m 36s | Sync" PGSQL -> BQ, 13 tables selected.
Disk usage was 11% in the beginning and it slowly grew to 94% and never decreased till the sync's final stages.
Data in all temp tables appeared only in the end even though many tables were processed by source hours ago.

## Logs
[logs-2-0.txt](https://github.com/airbytehq/airbyte/files/6451097/logs-2-0.txt)

## Steps to Reproduce
1. Set up a big sync with several tables
1. Observe disk usage during the sync with df command
1. Note that disk usage drops only after all tables were processed by source.

## Severity of the bug for you
High, because big synchronizations may eat lots of disk and even crash due "no space left on the device" error

## Airbyte Version
0.22.2-alpha

## Connector Version (if applicable)
Postgres 0.3.2
BigQuery 0.3.0

## Additional context
GCP e2-standard-8 (8 vCPUs, 32 GB memory), 64GB SSD
Postgres to Bigquery sync with multiple tables
 "32.87 GB | 75,824,003 records | 6h 4m 36s | Sync" PGSQL -> BQ, 13 tables selected.
Slack conversation: https://airbytehq.slack.com/archives/C01MFR03D5W/p1620314953027000

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368107616734) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
@cgardens is changing the behavior this week for how we apply backpressure to the source so we don't queue up a huge amount of information. This should be resolved as part of that change.

**Comment by akoshterek** [comment]
I did reset 2 PGSQL->BQ connections (all connectors are the latest) and forced syncs. Disk usage still drops only when a sync is about to finish.

2 big syncs and 1 small in the middle. On the right bottom graph you can see 2 spikes for read that happen near end of syncs.

So on-disk queue changes didn't seem to help in BQ case

![Screenshot 2021-05-18 at 16 40 09](https://user-images.githubusercontent.com/13558863/118783687-971c9900-b88f-11eb-99e0-48461b1fb274.png)

**Comment by davinchia** [comment]
@akoshterek what connector versions are you on?

**Comment by akoshterek** [comment]
@davinchia PGSQL 0.3.2 and BQ 0.3.2

**Comment by akoshterek** [comment]
Upgraded Airbyte to 0.24.2-alpha, PGSQL source 0.3.2, BQ dest 0.3.3

The situation became even worse on the same VM. 
<img width="676" alt="Screenshot 2021-05-27 at 15 35 25" src="https://user-images.githubusercontent.com/13558863/119840929-ae99f880-bf05-11eb-89ee-6b25c1313edd.png">

Disk usage dropped a bit after 1st sync completed but kept creeping up until I cancelled the 2nd one. But even after that 75% remained occupied until I exported config, shut it down and killed all volumes and reimported config back.

Performance became about 50% slower.
[logs-560-0.txt](https://github.com/airbytehq/airbyte/files/6554734/logs-560-0.txt)

**Comment by cgardens** [comment]
Just to make it clear, we are following up on this issue. We are tracking it over [here](https://github.com/airbytehq/airbyte/issues/3665).

**Comment by davinchia** [comment]
@akoshterek similiar to the other issue can you upgrade to the latest Airbyte version and give it a shot? We are hoping this was the underlying issue.

**Comment by akoshterek** [comment]
Sure

**Comment by davinchia** [comment]
@akoshterek curious, are you still seeing this? or has this subsided with the later versions? I know we made a bunch of changes to try and nip it.

**Comment by akoshterek** [comment]
@davinchia I will check and report back

**Comment by akoshterek** [comment]
@davinchia It seems 20Gb sync didn't affect disk usage at all 
Moreover, it looks pretty flat for the last 7 days (since upgrade to 0.27.0_

I am closing the issue

**Comment by davinchia** [comment]
Thanks!
