### ISSUE TITLE
Allow for looser request matching on query parameters

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#33202]
There are some cases where the specifics of the API is not important. For example, given an error then validate error handling. The fact that specific query parameters are passed is not important for this test. Hence allowing something like this would be nice:

```
        http_mocker.get(
            HttpRequest(
                url="https://api.stripe.com/v1/events",
                query_params=any()
            ),
            _a_response().with_status_code(500),
        )
```

**Comment by natikgadzhi** [comment]
Are we usually closing issues when the corresponding PR is merged, or only after we ship them to prod? This one I think can be closed?

**Comment by maxi297** [comment]
For this specific case, the very implicit acceptance criteria was that it was used in source-stripe integration tests.
