### ISSUE TITLE
container-orchestrator image starts orchestrator-normalization sync step on behalf of "admin-airbyte" default SA, despite override value

### ISSUE THREAD

**Issue by ilyasemenov84** [airbytehq/airbyte#33217]
### Helm Chart Version

0.50.2 - 0.50.3

### What step the error happened?

During the Sync

### Revelant information

The chart is deployed with `global.serviceAccountName` value, which overrides the default one (`airbyte-admin`).
Worker deployment has the custom value in `JOB_KUBE_SERVICEACCOUNT` env.
When the sync job gets triggered, a couple of transient pods succeed (like destination check, orchestrator-repl, source-read), but  `orchestrator-norm` pod fails with the error.

### Relevant log output

```shell
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1:443/api/v1/namespaces/airbyte-stg/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "normalization-snowflake-normalize-21567-1-gvrem" is forbidden: error looking up service account airbyte-stg/airbyte-admin: serviceaccount "airbyte-admin" not found.
                                                                                        │
```

**Comment by UKanamo** [comment]
I am facing the same issue and having trouble with it.
Is there any workaround for this issue?

**Comment by marcosmarxm** [comment]
You need to override the env variable: `JOB_KUBE_SERVICEACCOUNT` and change the value there too. It is a missing step in our documentation

**Comment by UKanamo** [comment]
Thanks! I attempted to set up the JOB_KUBE_SERVICEACCOUNT environment as follows, but it's not functioning yet:

```
JOB_KUBE_SERVICEACCOUNT: "airbyte-admin-xxx"

- name: JOB_KUBE_SERVICEACCOUNT
    valueFrom:
    configMapKeyRef:
      name: release-name-airbyte-env
      key: JOB_KUBE_SERVICEACCOUNT
```

Does this configuration differ from what you were expecting?

**Comment by ilyasemenov84** [comment]
> You need to override the env variable: `JOB_KUBE_SERVICEACCOUNT` and change the value there too. It is a missing step in our documentation
> 
> (edited) you're using the variable... which means it looks weird, looking into
As I mentioned in the issue description:
| Worker deployment has the custom value in JOB_KUBE_SERVICEACCOUNT env.
So, doesn't help in my case.

**Comment by UKanamo** [comment]
Is there any progress on this issue?
This problem is preventing me from running Airbyte on k8s and it's troublesome😓

**Comment by a-monteiro** [comment]
I have the same issue

**Comment by UKanamo** [comment]
@marcosmarxm 

In order to identify the problem area, I have examined the `airbyte-platform` repository. 
In my investigation, I noticed that in the env configuration, JOB_KUBE_SERVICEACCOUNT was not defined.

https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-commons-worker/src/main/java/io/airbyte/workers/sync/OrchestratorConstants.java

https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java

While I'm not particularly familiar with the configuration of airbyte, I wondered if adding a definition there might resolve the issue. What do you think?
