### ISSUE TITLE
Data sync Issue ( mainly updation/deletion)

### ISSUE THREAD

**Issue by axl-ankush** [airbytehq/airbyte#33242]
### Topic

airbyte data sync

### Relevant information

When I am updating/deleting any row on source mssql, airbyte creating new row in the table on the target instead of updating the existing record.  I am using cdc as update method and in that I am using incremental append option of data sync.  Airbyte treating each update or delete as a new insert.

**Comment by marcosmarxm** [comment]
This is the expected behavior to incremental + append. If you want to change the record you need to select incremental + dedup.

**Comment by marcosmarxm** [comment]
What destination are you using? The incremental + dedup is only available for a few destinations.

**Comment by axl-ankush** [comment]
I am using mysql as the destination. Can you suggest me options for which incremental sync append + dedup is available
