### ISSUE TITLE
Create a process for contacting customers with too large record errors

### ISSUE THREAD

**Issue by katmarkham** [airbytehq/airbyte#33260]
An error is thrown when a record larger than 20MB fails.  We should proactively be tracking instances and reaching out to customers about how to proceed.

Until a more long term solution is implemented to handle large records, we should email them inquiring whether or not they would like us to skip the records and log the PK (with LaunchDarkly) so that they may continue their syncs and do further investigation into the large records on their end.

**Comment by davinchia** [comment]
This will be handled by the better large records H1 Initiative. Not relevant anymore.
