### ISSUE TITLE
Fix error reporting in the UI

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#33272]
## What

The current error is very non-informative (very obscure null ref). We should make sure we can report at least the same amount of information as we did before the workload API.

## How

* Update error tracking to store the errors on workload failure
* Retrieve the error from the repl activity when applicable

**Comment by tryangul** [comment]
When we fail to return a well formed output in WorkloadApiWorker, we return `null` and eventually `reduceReplicationOutput` tries to deref it via getReplicationAttemptSummary and we blow up.

I think we need to handle the failure case, as `OrchestratorNameGenerator#getOrchestratorOutputLocation` seems to presume success.
