### ISSUE TITLE
bigquery destination can hang permanently when timing out requesting a token

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3330]
Slack conversation:
https://airbytehq.slack.com/archives/C01MFR03D5W/p1620655457149300

Logs for the attempt that never finishes: [logs-127-0.txt](https://github.com/airbytehq/airbyte/files/6453093/logs-127-0.txt)

It's likely a network issue caused the failure. However, we would expect this to fail and retry. Instead it's stuck as running and never retries.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368107797890) by [Unito](https://www.unito.io)

**Comment by misteryeo** [comment]
Staging uploads make this issue obsolete and we haven't seen this come up in a while. Closing for now but if anyone sees this crop up again, feel free to reopen.
