### ISSUE TITLE
File-based CDK: Add a CAT to ensure all file types covered

### ISSUE THREAD

**Issue by askarpets** [airbytehq/airbyte#33363]
### Topic

File-based CDK

### Relevant information

We need to add a CAT which checks that the sandbox account for a file-based connector has files with all types implemented in File-based CDK

**Comment by girarda** [comment]
@askarpets can you clarify the acceptance criteria?

A few questions I have:
- what's the test's purpose? Is it to verify there was a test read for all file types or the verify the connector technically supports all file types? If the latter, inspecting the spec might be an easy way to implement. If the former, can you clarify the approach?
- will this test run on all connectors with a [connector subtype file](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-s3/metadata.yaml#L10C3-L10C19)?
 - if not, how will the CAT framework know how which connector to run the test for?
- will there be a way to ignore specific file types as an escape hatch in case we need to support a connector that doesn't support one of them?  
- will the test be enabled by default for all connectors? If not, what's the trigger? eg will it be enabled for all certified or for all connectors with a ql >= 400?

**Comment by askarpets** [comment]
@girarda, please review my responses below:

- The purpose is to verify that for a file-based source connector there are all Airbyte supported file types present in its sandbox account, otherwise the test will fail asking to add missing file types. There should also be an option in acceptance test config to add ignored file types in case the source does not support them.
- Use of `connectorSubtype: file` is a good indicator to run this test.
- From my understanding, the test's criteria should be required for all certified file-based connectors.

Please let me know your thoughts regarding this. Thanks!
