### ISSUE TITLE
Concurrent CDK: add concurrency for all source-salesforce incremental syncs

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#33362]
Integrate the concurrent CDK with Source Salesforce for all incremental syncs.

### Implementation details

This will require us to translate between the old and new state messages if we want the ability to roll back the connector.

The pattern for creating this translation layer was implemented (but not productionized) for Stripe, but the actual details for translating between the old & new state messages (and back) will be specific to Salesforce.

Old state message format:
```
{
  "stream_state": { "SystemModstamp": "2021-01-18T21:18:20.000Z" },
  "stream_descriptor": { "name": "Account" }
}
```

New state message format:
```
{
  "charges":  {
    "state_type": "date-range",
    "metadata": { … },
    "slices": [
    {begin: 0, end: 1617030403, finished_processing: true}]
  }
}
```

### Acceptance Criteria
- [ ] Source Salesforce uses concurrency for all syncs.
- [ ] Test coverage exists for various combinations: running concurrent code when the connector takes in a concurrent state and the old state, and non-concurrent when the connector takes in a concurrent state and the old state.

**Comment by clnoll** [comment]
Grooming notes:
- Can we keep the date ranges of the chunks in memory but only persist up to the end timestamp of the first continuous chunk? Do a follow-up to update the state message later.
- Nice to have analytics around where the failure is (new AnalyticsMessage to show that some partitions were started and/or future ones were completed). This might not give us the full picture with the existing code since we bail out on the first error.

**Comment by girarda** [comment]
Noting we'll want to update the Cursor's logic to either optionally, or always use the most recent record even if there are slice boundaries. 

This could be done by removing or adding another condition to [observe method](https://github.com/airbytehq/airbyte/blob/333320edebc3524054d476e0b1283b552b7bb1fa/airbyte-cdk/python/airbyte_cdk/sources/streams/concurrent/cursor.py#L90C1-L94C19)

**Comment by natikgadzhi** [comment]
To make sure we don't forget about this one: is there a related PR in review? What's blocking this?
