### ISSUE TITLE
Generate initial debezium state and save in state (cdc based sync)

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#33396]
Before starting a CDC incremental sync we need to generate a state that will be read by debezium upon completion of the snapshot.
This state will function as a high watermark to know when to start the incremental sync from, containing all the necessary information in a format recognized by debezium.
This state will contain for example the status of LSN in the time we started the initial snapshot.

**Comment by prateekmukhedkar** [comment]
Instead of relying on Debezium to generate the state, we create it and then initialize Debezium with it.

**Comment by rodireich** [comment]
See implementation for
[MySQL](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mysql/MySqlDebeziumStateUtil.java#L234)
[Postgres](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/postgres/PostgresDebeziumStateUtil.java#L227)
[mongodb](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/debezium/internals/mongodb/MongoDbDebeziumStateUtil.java#L57)
