### ISSUE TITLE
MySQL gracefully handle UTF-16 characters

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3340]
The MySQL destination fails if it encounters UTF-16 characters. 

We should filter messages if they don't have the correct encoding support and we should make it clear in our docs what encodings we support.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368231206152) by [Unito](https://www.unito.io)

**Comment by rodireich** [comment]
I no longer see a problem here:
Attempted to sync a from mysql-source a DB encoded with UTF16 to both destination-mysql and postgres.
No error and data synced including unicode strings.
