### ISSUE TITLE
barebones HTML page for Oauth quickstart

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3341]
## Tell us about the problem you're trying to solve
Using connectors which require oauth requires a lot of toil. Airbyte currently doesn't support Oauth in the UI so the user needs to run some requests with finicky syntax via a combination of postman/curl and the browser to generate a refresh token. Given that Oauth was pushed back by another month, we should have an escape hatch to allow users to leverage oauth-based connectors like Salesforce or Okta in an easier way. 

## Describe the solution you’d like
The idea is to create a very quick and dirty barebones HTML/javascript page which can be used. The page should ask the user for required parameters to generate an auth code, generate a URL for them to visit to perform the auth in the browser then generate the auth code. They can then copy the auth code back into a form on the page to generate the refresh token. They can then input this into the connector. 

## Additional context
Salesforce and Okta are good test subjects.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368230951805) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
closed as no longer relevant.
