### ISSUE TITLE
Facebook source doesn't allow set up source with `include_deleted` selected

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3342]
## Expected Behavior
Should work with **included_deleted** option selected.

## Current Behavior
See video
https://user-images.githubusercontent.com/5154322/117728708-26ef8280-b1c0-11eb-9d61-904bf6c1f779.mov

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. try to set up a new Facebook source.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Dont have but can ask user.

@Jamakase just creating the issue started in convo: https://airbytehq.slack.com/archives/C01MFR03D5W/p1620408567078700

**Comment by Jamakase** [comment]
@cgardens @marcosmarxm 

There is an issue on the backend: for `included_deleted` we receive `default: "false"` when we actually should get `default: false` ( just as we receive it for ssl property in postgres source )
