### ISSUE TITLE
Temporal v1.20 .1 prints cleartext database password in logs

### ISSUE THREAD

**Issue by adrawbond-alto** [airbytehq/airbyte#33432]
### Helm Chart Version

0.50.2

### What step the error happened?

Other

### Revelant information

The Airbyte Helm chart is using [temporalio/auto-setup v1.20.1](https://github.com/airbytehq/airbyte-platform/blob/fecceaef771118ece798e44f90d8ebfe564643e0/charts/airbyte-temporal/values.yaml#L25), which prints the Airbyte database password in cleartext in the logs. This was a [known bug](https://github.com/temporalio/temporal/issues/3022) with Temporal, which they fixed in https://github.com/temporalio/docker-builds/pull/147. Upgrading `temporalio/auto-setup` to `v1.22.2.0` fixes the problem.

#### How to reproduce
Deploy Airbyte using the Helm chart to a Kubernetes cluster. Download the logs for the temporal pod using `kubectl logs`. You will observe near the top of the logs your database password in cleartext. Then, override the Helm chart value `temporal.image.tag` with `1.22.2.0` and redeploy the Helm chart. Check the temporal logs again, and the database password will no longer be present. You can further verify by exec'ing into the running temporal pods (first the `v1.20.1` pod, then the `v1.22.2.0` pod) and `cat`'ing out `auto-setup.sh` and observing the removal of the `-x` shell option in the script.

**Comment by marcosmarxm** [comment]
Airbyte uses v1.22.3 now https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-temporal/Dockerfile
Thanks for reporting the issue @adrawbond-alto

**Comment by adrawbond-alto** [comment]
The [Helm chart is still using 1.20.1](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte-temporal/values.yaml#L25).
