### ISSUE TITLE
Intercom Connector is failing on normalization step

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3344]
## Expected Behavior
The connector should apply normalization without failing.

## Logs
[logs-1-0 (1).txt](https://github.com/airbytehq/airbyte/files/6455513/logs-1-0.1.txt)

`2021-05-10 21:07:20 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - WARN: Unknown type for column team_ids at admins
2021-05-10 21:07:20 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - WARN: Unknown type for column admin_ids at admins`
`2021-05-10 21:07:42 INFO (/tmp/workspace/1/0) LineGobbler(voidCall):69 - 21:07:42 | 2 of 41 ERROR creating table model INTERCOM.CONVERSATION_PARTS............................................... [[31mERROR[0m in 3.38s]`

## Severity of the bug for you
Very low / Low / **Medium** / High / Critical

## Airbyte Version
0.22.2-alpha

## Connector Version (if applicable)
0.2.1

## Additional context
Destination is Snowflake.
Slack convo: https://airbytehq.slack.com/archives/C01MFR03D5W/p1620686086176400

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368166558438) by [Unito](https://www.unito.io)

**Comment by lazebnyi** [comment]
@marcosmarxm @sherifnada  Tested successfully on CDK connector. This issue is not present after migration from the singer.

[logs-1-0.txt](https://github.com/airbytehq/airbyte/files/7083676/logs-1-0.txt)

**Comment by sherifnada** [comment]
sgtm, thanks @lazebnyi
