### ISSUE TITLE
UI Import config is disabled

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3345]
## Expected Behavior
I should be able to import a exported configuration

## Current Behavior
Modal opens the option to select a file but after file selected with configuration nothing happens and Submit button keep disabled.
![image](https://user-images.githubusercontent.com/5154322/117737716-d46a9200-b1d0-11eb-89e5-6eaba633803c.png)

## Steps to Reproduce
1. set up new airbyte instance
1. admin / configuration / import

## Severity of the bug for you
Very low / Low / **Medium** / High / Critical

## Airbyte Version
0.22.2-alpha

## Additional context
You can use the export.gz to test running a fresh Airbyte install.
[export.gz](https://github.com/airbytehq/airbyte/files/6455553/export.gz)

**Comment by marcosmarxm** [comment]
@Jamakase to let you know I submitted a PR to correct the import endpoint #3343 maybe this could be blocking the Submit button to be enabled.

**Comment by marcosmarxm** [comment]
PR #3343 correct the API, I tested and it's working to import using it. But UI keeps not working after this.

**Comment by Jamakase** [comment]
@marcosmarxm According to the screenshot attached to the image - file was not selected in the file dialog. I tested it and everything worked fine with the file attached to this issue
<img width="562" alt="Снимок экрана 2021-05-14 в 12 11 22" src="https://user-images.githubusercontent.com/3767150/118249052-2c561100-b4cf-11eb-8b79-46b9b38017b5.png">
.

**Comment by Jamakase** [comment]
Closing it as non-reproducible.

@marcosmarxm please reopen it if you face this issue again.
