### ISSUE TITLE
[Issue] Problem when craete treaming

### ISSUE THREAD

**Issue by viettran97118** [airbytehq/airbyte#33488]
### Connector Name

Bigquery

### Connector Version

0.50.21

### What step the error happened?

Configuring a new connector

### Relevant information

I have problem when create a new connection. But Source and Destination are no problem. I was test connection.

![image](https://github.com/airbytehq/airbyte/assets/148329464/144170f3-8287-4558-bf2d-5fd3a90f3cf0)

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This is not a connector problem. Please check your network tab and check all API requests made or provide the api-server/server/worker logs.

**Comment by marcosmarxm** [comment]
Closed because is not reproducible.

**Comment by viettran97118** [comment]
I agree, I was deleted cached. It's working
