### ISSUE TITLE
Source Airtable: Investigate if connector was migrated to using personal access token

### ISSUE THREAD

**Issue by DanyloGL** [airbytehq/airbyte#33490]
### Connector Name

source-airtable

### Connector Version

4.1.5

### What step the error happened?

None

### Relevant information

This year Airtable [launched new API authentication methods](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a1bc791649464161a1ea9d46dc65ed07&_e=DlUewFewbdQP3MSt9ffP_SLjDlVWLrirMbyrQgHg8IUS-Yxxgev7KTgL49zNRgd-wOKrAf2W4u8LdHErvkkEp8Ns3mmodXjz_yoItLUwsQoij1wtMtSci2Uy_hfhQefaGdXrV0vEL8ew7_BQFzYJfUYy5hWEWE5eH4y6TkuWL_Hvgj_i-lNWp5LGqaxfPy_RfdyjqQDYmh8hbvd_5JDdgeWu0jP2Gh9pIQjwLA4z2meEnyOn3g-09sWlk7JNtLokl2BCc4aNncDKoTSPLWaclfHM8dQdxydPmx-90-pvRViVqufoYTOR7m9UkHOoGXSXLpBPtCxG2l_b3Maofbwr4pTHc5qxyp4KUOwazam4TStaPcdYHnT1QJXIuJ8obu-rwKvfDjuNn33LqwhVbFpwPlecFyHw-fYII5EZ3U7NiPt6qxnkemLxVihA5Omacdtrv2czsaryx-b_76WWTXSjg2vUyQFc2r4TvujZtYJVjYsX_xuB_6LcBmN1br5qO4ddvnzEbXpEnnX2FhyitcBEWh7J6Zod3VfU0I6pxvtShwIsJnz2jZ9l0eX55dy7ZCeD) and announced the upcoming deprecation of API keys on February 1st, 2024.

Need to investigate if the connector was migrated to using [personal access tokens](https://links.airtable.com/u/click?_t=1627610c3a6845988951459cbd28d02a&_m=a1bc791649464161a1ea9d46dc65ed07&_e=DlUewFewbdQP3MSt9ffP_VTvf21_1K1UJNChjuxXtnJ8TllVChHIu3jdNURHkiKLw6TEAHjkNcUd4z3LqFDF-5oXcSQ05zRvusTdrUyk5yUKvRNVJ71yRmCZyTH2Rh7UQmiQ3wYWcXxh2uDIbbqMEFgPC0jJPQkiNQvz5LaXlwDklnD8bFkpLAkrUE3rSo9nL_CHhASmfk8sxCssK7KiqsEi0w6rj3JOqSlW2MdQ8YMeSTVWOlTXknkRMaHU8SPSHuZt4exMPaLnwYf-VC4AlI8RHzr-QB6c4i2vPHyDd5MA0ITPk9iPqMg0SEjsbJqtqvO4yMhwyGFe6B7G6S9eBlVLs4ydI6jZ4AFdkJ6pn9kpy_cMwmXZ7lbCVfDK0R7SWNukTS838s9hKThFDhIu3frUdno49PSTIkIqDrMA_4zbLq_iaqZAynx6homr9RVJ4xgu4isgCa4G5ruVCObRcJN0dcjiOjG1HWGENixR6JQ%3D).

### Contribute

- [ ] Yes, I want to contribute

**Comment by tolik0** [comment]
Closing this issue as the Airtable Source already uses a Personal Access Token. [The docs](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/airtable.md#step-1-set-up-airtable) also have links to the correct Airtable resources for creating the new token.
