### ISSUE TITLE
Source Hubspot: owners_archive stream API changes

### ISSUE THREAD

**Issue by imrehg** [airbytehq/airbyte#33524]
### Connector Name

source-hubspot

### Connector Version

2.0.0

### What step the error happened?

Other

### Relevant information

The `owners_archived` stream is pulling from this [Owners](https://developers.hubspot.com/docs/api/crm/owners) endpoint, with the query parameter `archived` set to `true`. According to the docs this flag is to set:

> Whether to return only results that have been archived.

The behaviour of the API has recently (around 2023-11-13) has changed, and `archived=True` returns both archived and non-archived users, changing the output of this stream. This change has been acknowledged by HubSpot (as I've checked with them), but not that the docs are now incorrect.

AirByte should likely either:
- keep the original behaviour of `owners` / `owners_archived` streams, or
- make this change explicit as well (in docs).

### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Hubspot reverted the changes, closing.
