### ISSUE TITLE
Implement dedup in dest-mysql

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#33548]
legacy normalization doesn't support dedup for dest-mysql. DV2 test suites currently assume that all DV2 destinations support dedup. Investigate + decide. Either:
* don't support dedup in DV2, and modify our test suites to allow this
* add support for dedup in dv2

implementing dedup notes:
* normalization already requires mysql >=8.0.0, which supports the row_number function. jooq should be able to generate this syntax.
* mysql's `insert ... on duplicate` requires a primary key constraint (or unique index) to function. So we can either add that in the `create table` statement, or just do the basic insert+delete thing
* overall - dedup should be very doable

**Comment by edgao** [comment]
current theory: legacy normalization _does_ support dedup, we just never enabled it in dest-mysql's spec.json

**Comment by evantahler** [comment]
Grooming: We should do it.  Covered by normal Dv2 upgrade work
