### ISSUE TITLE
[destination-postgres] Full refresh - overwrite method removes permissions

### ISSUE THREAD

**Issue by suhl79** [airbytehq/airbyte#33542]
### Page URL

https://docs.airbyte.com/using-airbyte/core-concepts/sync-modes/full-refresh-overwrite

### Description

What I've encountered using Postgresql destination 0.4.0 happens when I use Full Refresh - Overwrite method while having a role credentials assigned to that particular table created by Airbyte. After the Airbyte resync the role credential disappears in Postgresql and I have to grant it again. What I suspect is happening is Airbyte deletes the original table in that mode and recreates it and when deleting the original table (instead of maybe purging the existing one) the existing, table specific credentials get "abandoned" forcing the sql server engine to remove them. I couldn't verify that in the documentation. Maybe it's something that should be explicitly explained or maybe there's an issue in the destination connector that shouldn't remove the existing table before creating a new one. I'm not sure.

**Comment by marcosmarxm** [comment]
Hello @suhl79 this behavior is expected. Airbyte destination will delete and recreate the tables. This is needed to ensure to capture new or excluded columns and also it's a design to keep the table while sync a new version of it.
If you need to apply additional roles/permissions probably you need to use dbt to run after the table is recreated.

**Comment by evantahler** [comment]
Docs will be updated to include a note about this via https://github.com/airbytehq/airbyte/pull/33584
