### ISSUE TITLE
[Redshift Dv2] Handle `svv_table_info` permissions

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#33552]
From [Slack thread](https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1702311247948029?thread_ts=1702299183.996059&cid=C0690DFUDGS).

>(paraphrased) V2 introduced a new "is your table empty" check, which relies on querying the `svv_table_info` view. we could modify that check to do some sort of select exists(...) query to avoid asking for more permissions, but presumably there’s a minor cost tradeoff there, especially wrt to upgrading.

Data point: beta user was OK with granting more permission to the Airbyte user (if we stick with this route, we should add this info to the docs)

**Comment by evantahler** [comment]
Grooming:
* Dv2 needs more permissions.  This table is what we use to get the approx # rows in the table (how we can tell if the table exists w.o doing a read).  This is equivalent to INFORMATION_SCHEMA (trading a potentially harder setup for faster syncs).  We should:
    1. Add a read to CHECK command to make sure we can access.  We should try a `SELECT * FROM svv_table_info  LIMIT 1` to check access. 
    2. Add to docs that we need READ permission on this table.
