### ISSUE TITLE
Add CAT scenario validating that a sync emits at least one stream status for a successful sync

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#33565]
## Description

The CDK has evolved and now allows for stream status messages to be emitted during a sync on a per-stream basis. [Relevant code](https://github.com/airbytehq/airbyte/blob/f8182bc18ec1b18cd12a976a38205c76936f6623/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L125-L145).

As part of our CAT suite, we should be verifying that a source emits the correct statuses. They are as follows:

- STARTED: Emitted once a stream passes the availability check
- RUNNING: Emitted after receiving the first record that should be sent to a destination
- INCOMPLETE: Emitted if there an `AirbyteTracedException` or general exception is encountered during a sync
- COMPLETE: Emitted after `_read_stream()` is complete and all records were sent to the destination for a stream.

## Implementation Details

We have a few options as to how granularly we want to validate this:

1. Maximum validation for each stream. We check that the stream emits messages following the entire lifecycle in order of STARTED, RUNNING, records/state, and COMPLETE/INCOMPLETE.
2. Validate STARTED and COMPLETE/INCOMPLETE at the beginning and end of sync.
3. Just validate the existence of STARTED and COMPLETE statuses

Additional notes:
- Each stream should track messages in separate buckets to check status message ordering because if we begin to parallelize streams, we should not rely on synchronous messages for every stream.
- Checking INCOMPLETE is not that easy from the CAT level and a good place where general integration tests could be helpful. This is worth a cursory glance, but if this proves difficult at CAT, this can be considered out of scope

To validate this test w/ a real example, an existing source can override the `abstract_source.read()` method and copy the default implementation into the source being tested w/ the stream status messaged removed.

## Acceptance Criteria

- [ ] There is a new test that tests that every stream that is enabled for a connector running CAT has a STARTED + END message
- [ ] New CAT test is run against an existing certified connector and passes
- [ ] New CAT test is run against a modified version of a connector where stream status is emitted incorrectly and fails

**Comment by girarda** [comment]
source-google-sheets could be a used as a negative test case since it does not emit stream statuses

**Comment by artem1205** [comment]
Testing for `STARTED`, `RUNNING` and `COMPLETE` will be implemented in https://github.com/airbytehq/airbyte/pull/34675.

We are unable to test `INCOMPLETE` message from outside as we use the **docker container** as an test object in our CAT tests. It means that we can only provide different config and/or catalog for `read` command. Providing wrong configuration could help us with getting an `INCOMPLETE` message, but we are stuck on [check availability](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/abstract_source.py#L121-L124) and can not even get to `STARTED` message:

```python3
try:
    timer.start_event(f"Syncing stream {configured_stream.stream.name}")
    stream_is_available, reason = stream_instance.check_availability(logger, self)
    if not stream_is_available:
        logger.warning(f"Skipped syncing stream '{stream_instance.name}' because it was unavailable. {reason}")
        continue
    logger.info(f"Marking stream {configured_stream.stream.name} as STARTED")
    ....
```

To bypass this, we need to somehow "disable" check_availability during this test, e.g. by adding extra argument to `read`
command: `read --disable_check_availability --config=.....`

сс @brianjlai @natikgadzhi
