### ISSUE TITLE
Source Monday: connector migration to new 2024-01 API version

### ISSUE THREAD

**Issue by DanyloGL** [airbytehq/airbyte#33579]
### Topic

Source Monday new API migration

### Relevant information

Support of current Monday's API version (2023-07) will end on [January 15th 2024](https://developer.monday.com/api-reference/docs/api-versioning#making-a-request).
Need to investigate and create a plan for connector migration to the new API version 2024-01.

**Comment by deanmorin** [comment]
Is this expected to be addressed before the API version end of life?

**Comment by midavadim** [comment]
> Is this expected to be addressed before the API version end of life?

yes, this task is in progress
