### ISSUE TITLE
Add createdAt to WebBackendConnectionRead

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#33583]
### Relevant information

In order to complete https://github.com/airbytehq/airbyte-platform-internal/issues/8761 we need a createdAt timestamp on the WebBackendConnectionRead object.

**Comment by tealjulia** [comment]
Any update on this?  The frontend work has been merged since Dec. 5 so we'd love to turn this feature (indicating free historical syncs in the UI) on!

**Comment by flutra-osmani** [comment]
> Any update on this? The frontend work has been merged since Dec. 5 so we'd love to turn this feature (indicating free historical syncs in the UI) on!

We haven't worked on it yet. Started looking into it.

**Comment by flutra-osmani** [comment]
This has already been deployed.
