### ISSUE TITLE
Source Facebook Marketing: Ad Creatives are missing source_instagram_media_id

### ISSUE THREAD

**Issue by philbirtles** [airbytehq/airbyte#33644]
### Connector Name

source-facebook-marketing

### Connector Version

1.2.1

### What step the error happened?

During the sync

### Relevant information

Source - Facebook Marketing is missing the field `source_instagram_media_id` from the Ad Creatives schema: https://developers.facebook.com/docs/marketing-api/reference/ad-creative

In some cases this is the only way to link a creative to an Instagram video directly.

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@philbirtles I can't find this field in the documentation you linked only `effective_instagram_media_id`, can you help finding where did you saw this info?
`

**Comment by philbirtles** [comment]
Hi Marcos, yeah no problem - so, the field I'm after is
`source_instagram_media_id`, the docs for it are here:
https://developers.facebook.com/docs/marketing-api/reference/ad-creative/ -
I've ended up building a custom connector to pull this, happy to share the
connector, but if you hit the graph api with
https://graph.facebook.com/v18.0/act_7<ad_account_id>/adcreatives?fields=source_instagram_media_id
you should see some pull through.

**Comment by marcosmarxm** [comment]
Thanks for the return @philbirtles I requested to the connector team to take a look in your pull request.
