### ISSUE TITLE
Generate normalization project from API for export

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3365]
## Tell us about the problem you're trying to solve
Following up on #3235, we need an easier way to start a custom dbt project.

## Describe the solution you’d like
it would be nice to have an export button that makes an API call to trigger normalization generation of DBT project so that it can be exported outside of a sync.

## Describe the alternative you’ve considered or used
Run a sync with normalization turned on and export the files from the sync run workspace.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368231602473) by [Unito](https://www.unito.io)

**Comment by jlitola** [comment]
Is there any workaround on how to accomplish this right now? Wasn't successful in trying to get data out from the normalization pod.

**Comment by cgardens** [comment]
closing as no relevant. export does not exist anymore.

**Comment by ChristopheDuong** [comment]
it is still relevant and not related to the export/import feature of configuration files.

As a workaround for the moment, you can deploy airbyte  OSS via docker, replicate the same setup and extract the generated normalization project following the documentation [here](https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-dbt)

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated the custom dbt transformation feature](https://github.com/airbytehq/airbyte/discussions/34860).
