### ISSUE TITLE
Source Stripe: sources API deprecated

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#33714]
As part of the `bank_accounts` stream, we use the endpoint "customers/{customer_id}/sources". This endpoint is not available in the documentation and stripe mentions explicitly that the sources API is deprecated (see https://stripe.com/docs/sources/customers). We should move away from this API.

~Even though it's less clear that this is deprecated, the `expands=data.sources` parameter is not in the API doc anymore (I would like someone else to confirm that). It would mean that the lazy pattern we have right now might not work eventually and we would need to query all the child to see if there is a bank account.~ Based on the comment from @askarpets below, the previous statement is not true as the doc now has an [Expand page](https://stripe.com/docs/expand) stating how expanding works. For the customer object, `sources` is marked as expandable (see image) so the logic lazy logic should stay the same.

![image](https://github.com/airbytehq/airbyte/assets/3360483/4228c99d-7e1a-41a4-85cb-40e454117768)

**Comment by askarpets** [comment]
@maxi297 it looks like `sources` is still available as an expandable attribute for the `customer` object ([doc](https://stripe.com/docs/api/customers/object#customer_object-sources)), so I believe we can use it. Could you please take a look and let me know if I'm wrong?
Thanks!
