### ISSUE TITLE
Add parent stream field to child URL path

### ISSUE THREAD

**Issue by dmvianna** [airbytehq/airbyte#33738]
### Topic

parent stream

### Relevant information

1. I have a source endpoint `/{{ config['clientnamespace'] }}/v1/Employees` that returns an array of `employee_id`;
2. I have another source endpoint `/{{ config['clientnamespace'] }}/v1/Employees/{{ employee_id }}/Schedules` that returns employee schedules.

I need to fetch all employee schedules.

This is a common scenario. I'm developing a connector for this external API, and Airbyte lets me inject fields from the parent stream into the child stream, but only as query parameters, header or body of the request. Not in the URL itself.

I believe this is desirable functionality. Is this the right venue to request this functionality, or would the project help prepare one such PR?

**Comment by marcosmarxm** [comment]
Closed as duplicated of a feature discussion https://github.com/airbytehq/airbyte/discussions/33739
