### ISSUE TITLE
Rename and/or explain the WebBackend endpoints

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#3373]
## Main Issue
Currently, the WebBackend endpoints serve as glue for our UI and are supersets of other endpoints. As a user, it is fairly unclear initially what purpose they serve, but it makes sense once it's explained. Furthermore, if users do decide to use some of the features on the WebBackend endpoints, we don't guarantee support and backwards compatibility for them. I suggest the following:

## Proposed Changes
* Update API docs to give an explanation about what these endpoints are
* Label the endpoints as experimental
* Brainstorm a new name for them if needed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368166719165) by [Unito](https://www.unito.io)

**Comment by evantahler** [comment]
Closing, as we will soon have a team working on our API in general
