### ISSUE TITLE
Google advertising feed data is missing this type of data simultaneously

### ISSUE THREAD

**Issue by Ageds** [airbytehq/airbyte#33740]
### Platform Version

0.50.32

### What step the error happened?

During the Sync

### Revelant information

Compared with ordinary ads, feed ads have two more items: product group and product cost;

**Comment by Ageds** [comment]
![Uploading lQLPJwgB2WEjp1PNAxnNBwCw5e6dPOLgNFYFdb3Sae5UAA_1792_793.png…]()

**Comment by Ageds** [comment]
![lQLPJwgB2WEjp1PNAxnNBwCw5e6dPOLgNFYFdb3Sae5UAA_1792_793](https://github.com/airbytehq/airbyte/assets/15166076/9a4c2297-5b62-46a2-baa1-48176716d155)

**Comment by marcosmarxm** [comment]
Closing the issue because misses what connector and version used.
Please post a summary about what is missing, some aggregations you made if you're using a custom report or what report is missing data.
