### ISSUE TITLE
Mock Retool UI

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#33766]
Links
* [Version 1 List UI](https://airbyte.retool.com/editor/5b34ecea-6f98-11ee-9f5a-635bbc0074b9/Playgrounds/Pedro%20Test%20-%20LD%20Version%20Overrides)
* [Version 1 Add/Edit UI](https://airbyte.retool.com/editor/e202ddd8-794b-11ee-babe-03d92c88246c/Playgrounds/Pedro's%20Playground)
* [User stories + UI review with Nora](https://www.notion.so/Notes-from-Retool-Call-fa2df1672bf24f779f980c4d8168ae1f?pvs=4)
* [Version 2 Add/Edit UI](https://airbyte.retool.com/apps/51f21580-a06d-11ee-8165-2f44c4293425/Ben's%20Playground)

**Comment by evantahler** [comment]
Done!
