### ISSUE TITLE
Google advertising feed data is missing this type of data simultaneously

### ISSUE THREAD

**Issue by Ageds** [airbytehq/airbyte#33793]
### Platform Version

0.50.32

### What step the error happened?

During the Sync

### Revelant information

![Dingtalk_20231214135101](https://github.com/airbytehq/airbyte/assets/15166076/dc250753-e6fa-424e-8193-c845d072f264)
![Dingtalk_20231227164018](https://github.com/airbytehq/airbyte/assets/15166076/67766996-fdc7-4920-9974-65a61b2ecf25)
![Dingtalk_20231227164104](https://github.com/airbytehq/airbyte/assets/15166076/a93d404b-ea04-478a-ac47-8ba6dc1041d4)

The above three pictures are airbyte synchronization Google Ads to bigquery configuration.....

![lQLPJwgB2WEjp1PNAxnNBwCw5e6dPOLgNFYFdb3Sae5UAA_1792_793](https://github.com/airbytehq/airbyte/assets/15166076/ffde5d97-7807-45a0-98c2-b36b5623a05e)

When I query the "D_DC_SZY_FEED-ALQRMKT_JP" series of ads in the bigquery editor, it shows no data. Other series data are synchronized successfully. This ad is a Google Ads feed ad. The difference between feed ads and ordinary ads: there are additional product groups and product costs； this problem has existed since early November

![Dingtalk_20231227164411](https://github.com/airbytehq/airbyte/assets/15166076/bb5935f5-c770-4faa-a614-e481589a1399)
![Dingtalk_20231227164824](https://github.com/airbytehq/airbyte/assets/15166076/f236d4e8-dbf1-426b-9a3c-9a161f407dba)

The task synchronization data is normal, but the Google Ads Feed series advertising data is missing.
Looking forward to your reply. Thank you.

**Comment by Ageds** [comment]
‘D_DC_SZY_FEED-ALL_QRMKT_JP‘ The wrong campaign was written above

**Comment by marcosmarxm** [comment]
You aren't using the Airbyte official Google Ads connector so it isn't possible to provide a support to a connector doesn't belong to the community project. Please raise the issue to the creator of this custom connector or try the official connector.
