### ISSUE TITLE
Airbyte-Hubspot Problem: Airbyte spend long time to create a table BigQuery. Spend a lot of money 

### ISSUE THREAD

**Issue by viettran97118** [airbytehq/airbyte#33791]
### Connector Name

Hubspot

### Connector Version

1.7.0

### What step the error happened?

None

### Relevant information

BigQuery v1.10.2
![image](https://github.com/airbytehq/airbyte/assets/148329464/4c0a5dc4-cf1a-4c2a-8e8c-9405976c8f92)

HubSpot v1.7.0
![image](https://github.com/airbytehq/airbyte/assets/148329464/aa8186cf-9489-498b-ac47-083adb43ccdd)

Streamming Log:
![image](https://github.com/airbytehq/airbyte/assets/148329464/ef2cdf68-575f-4dc9-8382-b59a5951dc6c)

Spend long time to create a table empty in Bigquery. When i audit log Bigquery.
[CREATE SCHEMA IF NOT EXISTS `hubspo.txt](https://github.com/airbytehq/airbyte/files/13775486/CREATE.SCHEMA.IF.NOT.EXISTS.hubspo.txt)

![image](https://github.com/airbytehq/airbyte/assets/148329464/b44b75b4-a934-43d0-b568-3e3ce01f54ab)

This is a root cause making the billing on those days is very high
![image](https://github.com/airbytehq/airbyte/assets/148329464/a5e321c7-1e5b-484c-a5fd-0bf68e275d31)

### Contribute

- [ ] Yes, I want to contribute

**Comment by viettran97118** [comment]
I can provide more Bigquery's logging relevant this streamming.

**Comment by viettran97118** [comment]
@marcosmarxm can you review that?

**Comment by marcosmarxm** [comment]
Are you using full refresh or incremental syncs?
What are the configuration for the Bigquery destination connector, are you using staging or batch method?

**Comment by viettran97118** [comment]
> Are you using full refresh or incremental syncs? What are the configuration for the Bigquery destination connector, are you using staging or batch method?

I use append + deduped

![image](https://github.com/airbytehq/airbyte/assets/148329464/fa40a7f1-e1ca-42bc-86a8-9f8118b99808)

**Comment by viettran97118** [comment]
additional, I config BigQuery batch processing

![image](https://github.com/airbytehq/airbyte/assets/148329464/cf6aa094-bd14-497b-9a47-fd1016429882)

**Comment by marcosmarxm** [comment]
The issue reported is about Bigquery problem but described Hubspot version. Please upgrade both connectors to latest version and if the problem persists open a new issue reporting a problem to Bigquery connectr.
