### ISSUE TITLE
CDK: Add support for efficient parent/child streams

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3380]
## Tell us about the problem you're trying to solve
Currently the main way for syncing nested resources in a REST API is to read the parent stream once, then read it again and for each record use that record to obtain a group of records from the child stream. 

For example if you have endpoints `/employees` and `employees/{employee-id}/events` to sync them via the `HttpStream` abstraction, the `EmployeeEvents` stream would need to read all data from the Employees stream again in order to pull events one by one. This is inefficient since it reads data more than is necessary. 

We could use caching to get around this, but depending on the volume of data this may be not reasonable (although I haven't thought much about exactly where this breaks down/for what size of datasets). 

## Describe the solution you’d like
I would love to have a way baked into the `HttpStream` abstraction to support this kind of relationship in an efficient way. Some common access patterns will be: 

1. Do a full refresh read for the parent and for each parent record, make a query in the child stream based on it 
1. Do an incremental read for the parent and for each record make a child stream query. The state of the parent is derived from the state of the child. 
1. Do an incremental read for the parent and for each record make a child stream query. The state of the parent is derived NOT from the state of the child.

Ideally we want to implement these cases such that parent_1 is read exactly only once. 

Some challenges: 

1. `AbstractSource` syncs one stream at a time and doesn't have a concept of syncing interleaved records from multiple streams at once. 
1. Pinning down an abstraction that fulfills the cases above might be tricky.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368108567184) by [Unito](https://www.unito.io)

**Comment by keu** [comment]
To implement the parent/child streams efficiently we have two options:
- change the order of sync in the source (reading parents and reading all requested children streams for each parent record)
- explicitly read parent stream inside children stream (inside stream_slices method) and add cache to the parent class.

# Option 1.
will require implementation of some `nested_stream` structure that will be traversed by source. The source will append `parent` slice to each instance of slice.
Pros:
 - don't have issues with large cache
 - support all kind of API and clients, not only HTTP and sync
Cons:
- don't support incremental read of parent, in case of such read requested and one of its child streams requested too the parent stream will be sync'ed as full refresh.

# Option 2.
Almost identical to 1 except the order doesn't matter, the parent stream will automatically create a cache on instantiation.
Pros:
- transparent, as there is minimal change to the way it works now
Cons:
- in the case of a very large parent stream or a big number of parent streams can consume a significant amount of memory. --- will work only with HTTP APIs.

The state management will be left outside of these abstractions, to make it simple and flexible enough, it might be changed next iteration/milestone

**Comment by keu** [comment]
### Option 1.
lets say we have following structure
```
class Parent:
    pass

class Child1:
    parent = Parent

class Child2:
    parent = Parent

class Child3:
    parent = Child2
```
```
catalog_streams = ["parent", "child2", "child3"]
```
then Source will build the following map before the read:
```
requested_streams = {
    "parent": [Child2()],
    "child2": [Child3()],
}
```
the reading algorithm will look like this
```
read parent
    read child2
        read child3
```
and the `_read_full_refresh` for example will look like this
```python
        slices = stream_instance.stream_slices(sync_mode=SyncMode.full_refresh, cursor_field=configured_stream.cursor_field)
        for slice in slices:
            slice.update({"parent": parent_record})  # <--- new code
            records = stream_instance.read_records(
                stream_slice=slice, sync_mode=SyncMode.full_refresh, cursor_field=configured_stream.cursor_field
            )
            for record in records:
                yield self._as_airbyte_record(configured_stream.stream.name, record)
```

**Comment by keu** [comment]
### Option 2.
works only for HttpStream.

- [ ] add caching to HttpStream, using vcrpy library and new property `use_cache`. When enabled stream should create cache file with `<name_of_the_stream>.yml` name.
- [ ] add `class HttpSubStream(HttpStream)` with constructor that accept parent (instance of the stream) and has `stream_slices` with default implementation that read parent stream
- [ ] add tests with source reading nested child (check cache work and slices method)

estimation is 8h - 16h
