### ISSUE TITLE
Documentation URL should not be a required field for add source/destination

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3382]
![Screen Shot 2021-05-12 at 3 10 03 PM](https://user-images.githubusercontent.com/9092207/118050459-28da5280-b334-11eb-8305-ac49aa8f8074.png)

documentation url is required in this form, but i'm not convinced that it should be. for a user adding their own custom connector it's not super reasonable that they need to have a documentation url. it's a custom connector after all.

 `StandardSourceDefinition` also currently sets documentationUrl to required. While for any connector that we publish, we should hold ourselves to setting a `documenationUrl`, we should not have this field be required for custom connectors.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368108580737) by [Unito](https://www.unito.io)

**Comment by timroes** [comment]
Labeling this for OSS team, since we'd first require the API to be changed to no longer enforce that property, before we can make the required FE changes.

**Comment by josephkmh** [comment]
The documentation URL field is no longer required in the UI, so closing this issue ✅
