### ISSUE TITLE
Job attempts do not respect latest connector version

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3383]
## Expected Behavior
If a sync attempt fails (e.g: due to a bug in the current connector version), then I go to the Admin UI to upgrade the connector version (to pick up the latest bug fix), I expect the next attempt in the sync to use the latest set connector version.

## Current Behavior
The connector does not change for all attempts in a particular job. 

## Steps to Reproduce
1. Setup postgres source, any destination
1. Turn off the postgres instance to force the sync to fail
1. Trigger a sync, it will fail. 
1. Quickly go to the admin UI and change the connector version
1. Go back to the sync page and view the logs of subsequent attempts. You'll notice they are using the same connector version (pre-version-chagne). 
1. cancel the attempt and start a new sync job. It is using the correct version. 

## Severity of the bug for you
Medium -- not critical but makes for a confusing UX

## Airbyte Version
0.22.3-alpha

## Connector Version (if applicable)
NA

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368108596131) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
fixed.
