### ISSUE TITLE
Fail sync when record counts are not equal

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#33862]
If the platform detects that the record count from the source does not equal the record count returned by the destination, the platform should fail the sync immediately, allowing any retries to kick in.  This logic should be gated by a feature flag.

**Comment by jdpgrailsdev** [comment]
source-mysql is scheduled to be released with the record counts in the state message this week (1/2).

**Comment by ahmedhamidibr** [comment]
@jdpgrailsdev is this feature released yet?
