### ISSUE TITLE
Column Selection

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#33894]
### Relevant information

Currently column selection is not very discoverable or intuitive.

![Screenshot 2024-01-03 at 11 54 17 AM](https://github.com/airbytehq/airbyte/assets/146028830/4897b542-4aa4-4fb0-be54-967b90d79a65)

A user can open a modal showing a stream's columns by clicking on the "All Fields" button on the Replication tab. This is not immediately obvious behavior, and has to be trained in the user.

Once opened, the modal can show hundreds of columns, which the user has to navigate by scanning and scrolling ([Fullstory](https://app.fullstory.com/ui/13AXQ4/session/7484572937148265711:(7484572937148265711!8624145539312139246(8694129142104067812(926100))))). Ideally a user should be able to easily search and select columns as they do streams on the replication tab.

Overall the UX of column selection can be improved and is related to bulk edit (#33893).

**Comment by josephkmh** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/32034, where I copied the content of this issue into the comment thread
