### ISSUE TITLE
airbyte-ci: don't report sentry issues on dev branches

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#33892]
Our #connectors-ci-errors gets loads of errors whenever we are developing a new feature or changing things on airbyte-ci. We are able to recognize when we're developing - we could mess with the SENTRY_DSN environment variable or create a new one specifically for sentry ignoring. 

I believe we could mess with the value [here](https://github.com/airbytehq/airbyte/pull/33519/files#diff-8bba74a834b43cc4f45b74d9e25f898d291bc2d8c537e423325e4da1487efaa1R159), only setting it in the case of the binary install 

Pros: 
* #connectors-ci-errors becomes less noisy and more actionable

Cons: 
* sentry no longer pings on all changes to airbyte ci, including e.g. small changes made by users outside of our team. that could mean we miss things

**Comment by evantahler** [comment]
Grooming:

* We already have a whole different install path for when we are working on airbyte-ci (pipx vs download)
* There exist multiple sentry environments (same DSN, but development vs prod) we can use that.  The default is "production", we could make it non-prod with an ENV var.

**Comment by pedroslopez** [comment]
python SDK options: https://docs.sentry.io/platforms/python/configuration/options/#environment

> By default the SDK will try to read this value from the SENTRY_ENVIRONMENT environment variable.
