### ISSUE TITLE
Salesforce connector - metadata fetched for every object

### ISSUE THREAD

**Issue by rdkrish-plivo** [airbytehq/airbyte#3390]
## Expected Behavior
Fetch metadata using `/describe` API only for the selected objects.

## Current Behavior
~650 `/describe` API requests are made to fetch metadata of every salesforce object per sync. This consumes a lot of salesforce API quota unnecessarily even when the objects are not selected.

Ref: https://github.com/singer-io/tap-salesforce/blob/master/tap_salesforce/**init**.py#L125

## Logs
```
Making GET request to https://company.salesforce.com/services/data/v41.0/sobjects/BrandingSetProperty/describe with params: None
```

## Steps to Reproduce
1. Set up the salesforce source connector.
1. Set up any destination connector.
1. Set up the connection between salesforce and destination by selecting only 1 object to sync.
1. Search for `/describe` in the sync log. Even for the unselected objects, we can notice that the metadata is fetched.

## Severity of the bug for you
Medium

## Airbyte Version
0.22.3-alpha

## Connector Version
source-salesforce-singer (v0.2.1)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368231667674) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@rdkrish-plivo this should have been fixed with the latest airbyte-native salesforce connector, could you upgrade to it and reopen the issue if the problem persists?

**Comment by rdkrish-plivo** [comment]
Thank you @sherifnada!
