### ISSUE TITLE
Source S3/S3 File <> Redshift V2: final tables are `NULL`ed out (Case Sensitivity issues with SUEPR)

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#33900]
See https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1703278044226589 for more screenshots + logs

From S3 source or file source with S3 file, Redshift V2 destination final tables only have `NULL` values
<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11f9a4901cf0d7313c77a7ebb1b3828b66aa8092/image%20%287%29.png" alt="image (7).png" />

Scoping down the problem:
- Equivalent V1 sync works fine
- MySQL source <> Redshift V2 destination works fine
- `_airbyte_data` in V2 raw tables looks OK
- Observed with loading via S3 staging, no data on standard inserts

**Comment by evantahler** [comment]
It looks like the same user is seeing the same problem for a Salesforce source as well ([slack](https://airbytehq-team.slack.com/archives/C0690DFUDGS/p1704427454742729))

**Comment by evantahler** [comment]
Here is what I believe is happening - CaseSensitivity within JSON is causing the problem.  The problem examples have case-sensitive property names.

```sql
DROP TABLE IF EXISTS evan_test.test;
CREATE TABLE evan_test.test (data super);
INSERT INTO evan_test.test (data) values (JSON_PARSE('{"a": 1, "B": 2}'));

SET enable_case_sensitive_identifier to FALSE; -- DEFAULT
SELECT data.a, data.B, data."B", "data"."B" FROM evan_test.test;
-- PRODUCES: 1, NULL, NULL, NULL

SET enable_case_sensitive_identifier to TRUE; -- DEFAULT
SELECT data.a, data.B, data."B", "data"."B" FROM evan_test.test;
-- PRODUCES: 1, NULL, 2, 2
```

So... we need to `SET enable_case_sensitive_identifier to TRUE;`

**Comment by gisripa** [comment]
Fixed. waiting for tests to pass to release

**Comment by evantahler** [comment]
(moving to in-progress)
