### ISSUE TITLE
Source Shopify: stream missed in docs

### ISSUE THREAD

**Issue by lazebnyi** [airbytehq/airbyte#33911]
### Page URL

https://docs.airbyte.com/integrations/sources/shopify

### Description

BalanceTransaction stream is not in docs

**Comment by btkcodedev** [comment]
BalanceTransaction stream is already present in docs
Ref:
https://github.com/airbytehq/airbyte/blob/699360cb8c43cc49ed049e080c8d7838cea5b405/docs/integrations/sources/shopify.md?plain=1#L114
