### ISSUE TITLE
Docker image for local development

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#3391]
## Tell us about the problem you're trying to solve
Currently, developers need to install quite a lot: https://docs.airbyte.io/contributing-to-airbyte/developing-locally

* Java 14
* Node 14
* Python 3.7
* Docker
* Postgresql
* Jq
* CMake

## Describe the solution you’d like
Use docker container with all dependencies installed, this will speed up onboarding of new contributors significantly.
With this developer will need only `git` and `Docker`

## Describe the alternative you’ve considered or used
Install dependencies locally (not an easy task on OS X for example)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368167124782) by [Unito](https://www.unito.io)

**Comment by tusharm** [comment]
+1 to this. 

I followed steps on https://docs.airbyte.io/contributing-to-airbyte/developing-locally but the gradle build failed for `airbyte-workers` module. Looking through the build reports, I noticed I was missing `jq` and `busybox` docker image (are these deps documented?).

**Comment by supertopher** [comment]
The goal of this issue may be completed by work in #3028

**Comment by supertopher** [comment]
I believe we have solved this problem through #23227

marking as closed.  If you disagree please give a yell.
