### ISSUE TITLE
Add a feature to support Looker self-hosted instance domain 

### ISSUE THREAD

**Issue by RahulPrasad** [airbytehq/airbyte#3393]
## Tell us about the problem you're trying to solve
While trying to setup a source for Looker using domain for self-hosted instance we get the following error:
`domain * - Domain for your Looker account, e.g. airbyte.cloud.looker.com (e.g. domainname.looker.com) Note: The value must match the pattern ^[a-zA-Z0-9._-]*\.looker\.com$
`
This is due to Airbyte currently only supporting Looker hosted instances

## Describe the solution you’d like
Airbyte should support self/customer-hosted instances so that domain can either be `looker.clientname.com` or an IP address followed by port for test instances (e.g. 123.123.123.123:9999)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368232030625) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
Thanks @RahulPrasad I added your request to our roadmap

**Comment by Janardhanpoola** [comment]
API endpoint for self hosted instances. Doc. link mentioned below:
https://docs.looker.com/setup-and-management/on-prem-install/installation#create_a_dns_record
