### ISSUE TITLE
WEBAPP_URL not overriding webhooks notifications

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#33942]
### Helm Chart Version

0.50.20

### What step the error happened?

Other

### Revelant information

In helm values we are setting `webapp.url` to our public URL in the format `"https://......"` and it is properly being set in the configmap, but the webhook notifications still show the internal URL.  We also see that on the airbyte-server pod, `WEBAPP_URL` is being set properly.

**Comment by joeybenamy** [comment]
> +1 here.
> 
> I've confirmed that the webapp pod is getting the proper ENV var for the public url, but doesn't seem to do anything with it. Notifications just come up with the default URL.
> 
> In addition to setting the value `webapp.url` in the helm values, which does seem to update the config map, I noticed that with that setting alone, I didn't see the ENV var for `WEBAPP_URL` in the env for the webapp pod. I then tried again by setting the `webapp.extraEnv` in the values.yaml to:
> 
> ```
> extraEnv:
>   - name: WEBAPP_URL
>     valueFrom:
>       configMapKeyRef:
>         name: airbyte-env
>         key: WEBAPP_URL
> ```
> 
> This change did show that it was pulling the expected url value, and was showing up properly within the pod. Ultimately though, the notifications still weren't using the URL in this value.
> 
> We're using [v0.50.20](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.20) as well.

Thanks for confirming this issue and providing the great observation!  I hope it will be fixed soon.

**Comment by nataliekwong** [comment]
@malikdiarra I recall you were working on this area - did this end up getting resolved?

**Comment by malikdiarra** [comment]
Yes, this should be fixed for the following kind of notifications:
- schema update
- job success
- job failure

Some other minor notifications are not fixed just yet. Let's keep that bug open until they are; I'll provide a list.

**Comment by malikdiarra** [comment]
Remaining notifications to address:
- [ ] Warning before a connection is disabled because it failed too many times.
- [ ] Connection disabled because it failed too many times.

**Comment by joeybenamy** [comment]
> Remaining notifications to address:
> 
> * [ ]  Warning before a connection is disabled because it failed too many times.
> * [ ]  Connection disabled because it failed too many times.

Do we still have to set this with an env var or is this exposed as a helm value?

**Comment by malikdiarra** [comment]
Hi @joeybenamy, it still requires setting up an env var. We want to expose it as an helm value but we are not working on that at the moment.
