### ISSUE TITLE
Update Google Ads/Analytics docs

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3394]
## Tell us about the documentation you'd like us to add or update
The Adwords source supports Full Refresh syncs. That is, every time a sync is run, Airbyte will copy all rows in the tables and columns you set up for replication into the destination in a new table.

## Are there any related areas of documentation that currently exist? Could you point to them? 
https://docs.airbyte.io/integrations/sources/google-adwords
https://docs.airbyte.io/integrations/sources/googleanalytics

[convo](https://airbytehq.slack.com/archives/C01AHCDHCKE/p1620807297376800) sherifnada tagging you to confirm docs can be improve to google ads and analytics

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368231833633) by [Unito](https://www.unito.io)

**Comment by misteryeo** [comment]
@edgao when you wrap up Google Ads, can you also address this issue?

**Comment by edgao** [comment]
yep, added this to the epic!

**Comment by edgao** [comment]
actually @misteryeo what needs to be updated here? docs for both adwords and analytics both state that full refresh and incrementals are supported (https://docs.airbyte.com/integrations/sources/google-ads and https://docs.airbyte.com/integrations/sources/google-analytics-v4)

**Comment by misteryeo** [comment]
Ah then let's close - thanks for clarifying!
