### ISSUE TITLE
App version has changed from v0.50.40 to v0.5.41 within helm chart 0.50.21

### ISSUE THREAD

**Issue by stevenmurphy12** [airbytehq/airbyte#33970]
### Helm Chart Version

0.50.21

### What step the error happened?

Upgrading the Platform or Helm Chart

### Revelant information

I am running an Airbyte deployment on Kubernetes, managed by Flux.

Yesterday (04-01-24) I upgraded the Flux `HelmRelease` to use helm chart `0.50.21`. This correlated with app version `0.50.40` (I know this as I downloaded the artefact at https://airbytehq.github.io/helm-charts/airbyte-0.50.21.tgz to manually inspect it, and still have that local copy).

Overnight, Airbyte app version `0.50.41` was released. Looking at the same artefact https://airbytehq.github.io/helm-charts/airbyte-0.50.21.tgz, it now shows the app version as `0.50.41`. 

Flux monitors the Helm repo, and as a result upgraded the app version of it's own accord.

I've been working on the assumption that these helm charts are immutable, and that a new helm chart release should have been generated? Is this true? Or was there a bug with this particular release?

**Comment by jetvp** [comment]
It appears the same Helm chart was updated a second time, with 0.50.21 being updated on the 8-01-24 as well now.  The prior update on the 4-01-24 had a deployment issue and caused Airbyte workers to fail without warning.

**Comment by jetvp** [comment]
This has happen now for all updates post the 4th of Janruary.  They are all overwritting 0.50.21 instead of creating new versions.

**Comment by malikdiarra** [comment]
Hi @stevenmurphy12, @jetvp, thanks for reporting this. We've made changes on our end to make sure it does not happen again.

Please reopen this ticket if you experience that issue again.
