### ISSUE TITLE
Destination Weaviate: Weaviate multitenancy is not supported 

### ISSUE THREAD

**Issue by Marcus0086** [airbytehq/airbyte#33992]
### Connector Name

destination-weaviate 

### Connector Version

0.2.13

### What step the error happened?

Other

### Relevant information

Weaviate multi tenancy is not enabled or configurable. 
Weaviate has a very good approach on isolating different tenant data. Can this be configured or enabled from airbyte destination?

### Contribute

- [X] Yes, I want to contribute

**Comment by flash1293** [comment]
@Marcus0086 I think this would be a great addition!

We thought about this a little bit before but ultimately didn't get to implement it.

There are multiple ways how this could work:
* A static string setting in the config object, and the whole sync goes to a specific tenant
* A per-record dynamic lookup by specifying a field name in the config which is used as tenant id
* Using the namespace coming from the source as tenant id

Is your use case one of those?

**Comment by Marcus0086** [comment]
Thanks for replying @flash1293.
Yes, one of my use case is first one, but I think the other two mentioned can also be very useful.
Currently I have a weaviate instance with multitenancy support. My schema supports it but I cannot move data from a source to weaviate based on a tenant id.

**Comment by flash1293** [comment]
Makes sense @Marcus0086 - you checked the "Want to contribute" checkbox, would you be willing to create a PR for this? It doesn't seem like a very difficult feature:
* Extend config model with an optional tenant id string field: https://github.com/airbytehq/airbyte/blob/e7f81656830b602a4d9c77e5c6efbdd5e6101718/airbyte-integrations/connectors/destination-weaviate/destination_weaviate/config.py#L55
* Extend the indexer class to pass it to the Weaviate client: https://github.com/airbytehq/airbyte/blob/e48355062ecd449927fa8d4e95616c5f36070778/airbyte-integrations/connectors/destination-weaviate/destination_weaviate/indexer.py#L30

If you open a PR with the basic functionality I can help getting it merged quickly.

**Comment by Marcus0086** [comment]
Yes @flash1293 , I will work on this and create a PR by weekend. And Thanks for pointing out the necessary files.

**Comment by flash1293** [comment]
Awesome, thanks! Assigned you to it, please let me know if something's ready to review, you have questions or can't work on it for any reason.

**Comment by Marcus0086** [comment]
Hey @flash1293 , here is the PR, please let me know if anything is required. Thanks
https://github.com/airbytehq/airbyte/pull/34229
