### ISSUE TITLE
[source-mongodb-v2] - CDC connector is not fetching changes and every few syncs performing full refresh

### ISSUE THREAD

**Issue by AronsonDan** [airbytehq/airbyte#33991]
### Connector Name

source-mongodb

### Connector Version

1.2.1

### What step the error happened?

None

### Relevant information

I have created few mongo connections and observing the following behavior:

1. first sync after a reset is performing a full refresh
2. next few syncs are not fetching any new/updated records
3. the next sync is performing a full refresh

The issue is quite sporadic and I cant notice any pattern.
Will be more than glad to provide logs if needed.

Im attaching screenshots of the job history tabs:
<img width="1305" alt="image" src="https://github.com/airbytehq/airbyte/assets/22011236/95c7e6b1-39a6-4ace-8370-9d7cb3237246">
<img width="1296" alt="image" src="https://github.com/airbytehq/airbyte/assets/22011236/5aafc693-3495-4295-83ba-3318e1a29da6">

<img width="1296" alt="image" src="https://github.com/airbytehq/airbyte/assets/22011236/f9e7800a-ff99-4850-937f-429845d6d6b9">
[68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_23599_attempt_3_txt.txt](https://github.com/airbytehq/airbyte/files/13854651/68c1d0e2_4cc2_43bc_b5db_99b9f5cea75d_job_23599_attempt_3_txt.txt)

### Contribute

- [ ] Yes, I want to contribute

**Comment by rodireich** [comment]
As shown, looks like records not getting pulled during incremental sync until after a few syncs when we fall back to initial.

**Comment by akashkulk** [comment]
Closing as we are tracking this with the epic : https://github.com/airbytehq/airbyte-internal-issues/issues/7329
