### ISSUE TITLE
Enforce enum user inputs to be distinct

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#34036]
## Context

In the connector builder, a user input can be added, with its type set to `enum`, and there is no enforcement that the values in the `Allowed values` input are distinct.

This is an issue, because having repeated values in an enum doesn't make logical sense, and results in a strange looking UI:
![image](https://github.com/airbytehq/airbyte/assets/22731524/bd3a0fdb-be31-4b4c-b266-25a1cd6a8d50)

## Acceptance Criteria
- The Builder UI enforces that every allowed value of an enum field is unique

**Comment by ShoelessTom** [comment]
Image is broken btw

**Comment by lmossman** [comment]
Grooming notes:
- If the user inputs the same value multiple times, mark the field as error and include an error message e.g. "values must be unique"
