### ISSUE TITLE
airbyte-ci: Unable access integration test report generated by airbyte-ci for Java integration tests

### ISSUE THREAD

**Issue by SatishChGit** [airbytehq/airbyte#34039]
### Topic

Access to Integration tests report

### Relevant information

Using airbyte-ci to execute integration tests of Teradata destination connector using `airbyte-ci connectors --name=destination-teradata test`. Unit and Integration tests are executing successfully through airbyte-ci and in console log, it was displaying as `There were failing tests. See the report at: file:///airbyte/airbyte-integrations/connectors/destination-teradata/build/reports/tests/integrationTestJava/index.html` but not able to access this report after airbyte-ci job completed or in workflow execution. Please refer link for more inforamation. https://github.com/Teradata/airbyte/actions/runs/7444027127/job/20249771372#step:11:2405. 

Teradata destination connector workflow to run Unit and Integration tests is defined as https://github.com/Teradata/airbyte/blob/master/.github/workflows/airbyte-ci-teradata-ci.yaml

**Comment by evantahler** [comment]
Said another way, we need a way to get the junit build reports out of dagger's runtime.

**Comment by evantahler** [comment]
@SatishChGit while you can't get to the HTML report, it won't contain more information than the logs:

```
250: [439.0s] TeradataDestinationAcceptanceTest > testCustomDbtTransformations() FAILED
250: [439.0s]     java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.normalizationIntegrationType" is null
250: [439.0s]         at io.airbyte.workers.normalization.DefaultNormalizationRunner.configureDbt(DefaultNormalizationRunner.java:89)
250: [439.0s]         at io.airbyte.workers.general.DbtTransformationRunner.run(DbtTransformationRunner.java:74)
250: [439.0s]         at io.airbyte.cdk.integrations.standardtest.destination.DestinationAcceptanceTest.testCustomDbtTransformations(DestinationAcceptanceTest.java:902)
250: [439.0s]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
250: [439.0s]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
250: [439.0s]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
250: [439.0s]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
250: [439.0s]         at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
250: [439.0s]         at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
250: [439.0s]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
250: [439.0s]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
250: [439.0s]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by SatishChGit** [comment]
> @SatishChGit while you can't get to the HTML report, it won't contain more information than the logs:
> 
> ```
> 250: [439.0s] TeradataDestinationAcceptanceTest > testCustomDbtTransformations() FAILED
> 250: [439.0s]     java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "this.normalizationIntegrationType" is null
> 250: [439.0s]         at io.airbyte.workers.normalization.DefaultNormalizationRunner.configureDbt(DefaultNormalizationRunner.java:89)
> 250: [439.0s]         at io.airbyte.workers.general.DbtTransformationRunner.run(DbtTransformationRunner.java:74)
> 250: [439.0s]         at io.airbyte.cdk.integrations.standardtest.destination.DestinationAcceptanceTest.testCustomDbtTransformations(DestinationAcceptanceTest.java:902)
> 250: [439.0s]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 250: [439.0s]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 250: [439.0s]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 250: [439.0s]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 250: [439.0s]         at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
> 250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
> 250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
> 250: [439.0s]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
> 250: [439.0s]         at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
> 250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
> 250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
> 250: [439.0s]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
> 250: [439.0s]         at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
> 250: [439.0s]         at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
> 250: [439.0s]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 250: [439.0s]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 250: [439.0s]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> ```

Thank you @evantahler. It would be good to provide a way to capture a report from airbyte-ci pipeline so that it can be published to other location like github page https://teradata.github.io/airbyte/.

Currently, we are generating report using gradle task ./gradlew :airbyte-integrations:connectors:destination-teradata:integrationTest and publishing it to github page. It would be nice to have branch name/ link to github source code with branch name on which report is generated.
