### ISSUE TITLE
Investigate adding "Quick Jobs" parity

### ISSUE THREAD

**Issue by tryangul** [airbytehq/airbyte#34030]
We want CHECK/DISCOVER jobs to not be affected (or at least minimally affected) when we are under heavy SYNC job load.

DoD
Investigate current implementation
Come up with gameplan for parity in Workload system

Ideas
Is a separate temporal queue based on workload type the path forward?

**Comment by benmoriceau** [comment]
Here is the different queue used for our operations:

| Operation | Run within sync | Queue                          | notes                                                                               |
|-----------|-----------------|--------------------------------|-------------------------------------------------------------------------------------|
| Replicate | n/a             | GCP_US_EXPAND_SYNC             |                                                                                     |
| Discovery | yes             | GCP_US_EXPAND_SYNC             | It runs as an activity and is sharing the same queue than the replication activity  |
| Discovery | no              | GCP_US_EXPAND_DISCOVER_SCHEMA  |                                                                                     |
| Check     | yes             | GCP_US_EXPAND_CHECK_CONNECTION | It runs as a child workflow and has the same configuration than the stand alone one |
| Check     | no              | GCP_US_EXPAND_CHECK_CONNECTION |                                                                                     |
| Spec      | n/a             | GET_SPEC                       |                                                                                     |

**Comment by benmoriceau** [comment]
I think that one implementation could be to modify the following function from the `WorkloadService` to include the worklow type and use a specific queue:
```
private fun getQueueName(geography: String): String {
    val context = Geography(geography)
    return featureFlagClient.stringVariation(WorkloadApiRouting, context)
  }
```
