### ISSUE TITLE
[normalization] Orphaned records in nested tables (child tables)

### ISSUE THREAD

**Issue by vivekin** [airbytehq/airbyte#34062]
### Connector Name

airbyte/normalization

### Connector Version

0.4.3

### What step the error happened?

Normalization

### Relevant information

Airbyte version:0.50.30
Deployment: Docker compose
Source: source-github 1.5.3
Destination: destination-postgres 0.4.0
Stream synced: pull_requests
Sync mode: Incremental Append + Deduped

There are orphaned records in the nested tables (ie. child tables) of a stream which are having `_airbyte_<stream name>_hashid` which is not present in the parent table.
This is happening because, when there is an update for a particular record in the source, the parent table gets updated and produces a new hash id and new records will be created in the nested tables with the new hash id.
But the cleanup of the records with the old hash id is not handled.

This is occurring for any stream which is having child tables and when the sync in incremental Append + deduped
**Sync 1**
Parent table
| _airbyte_unique_key              | assignees                                | title       | _airbyte_emitted_at        | _airbyte_pull_requests_hashid    |
|----------------------------------|------------------------------------------|-------------|----------------------------|----------------------------------|
| 57aa020cea974b2e1f7f0bcd4db3da66 | [{"id": 126227043, "login": "person_1"}] | sample text | 2024-01-05 13:35:22.876+00 | f6a8b3ed2c19c34460524bb59d5c56b5 |

Child table
| _airbyte_pull_requests_hashid    | login    | id        | _airbyte_emitted_at        | _airbyte_assignees_hashid        |
|----------------------------------|----------|-----------|----------------------------|----------------------------------|
| f6a8b3ed2c19c34460524bb59d5c56b5 | person_1 | 126227043 | 2024-01-05 13:35:22.876+00 | 11a4c8a8b56943429adec8443ff307a8 |

After changing assignees
**Sync 2**
Parent table
| _airbyte_unique_key              | assignees                               | title       | _airbyte_emitted_at       | _airbyte_pull_requests_hashid    |
|----------------------------------|-----------------------------------------|-------------|---------------------------|----------------------------------|
| 57aa020cea974b2e1f7f0bcd4db3da66 | [{"id": 151685535,"login": "person_2"}] | sample text | 2024-01-05 13:42:24.39+00 | 886cdba973f50bd7f0fdb7ada3f4d67c |

Child table
| _airbyte_pull_requests_hashid    | login    | id        | _airbyte_emitted_at        | _airbyte_assignees_hashid        |
|----------------------------------|----------|-----------|----------------------------|----------------------------------|
| f6a8b3ed2c19c34460524bb59d5c56b5 | person_1 | 126227043 | 2024-01-05 13:35:22.876+00 | 11a4c8a8b56943429adec8443ff307a8 |
| 886cdba973f50bd7f0fdb7ada3f4d67c | person_2 | 151685535 | 2024-01-05 13:42:24.39+00  | e7c3b24438cd954de40c36eee3e6d3c0 |

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Normalization is deprecated please upgrade your destination to use latest version of the connector with Dv2
