### ISSUE TITLE
Dagger excludes does not work for hidden files/folders

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#34070]
## Steps to reproduce
1. Add a .venv folder to any subdirectory that we load into Dagger
2. In the pipeline that loads that directory log the context of that .venv directory
3. Run the pipeline
4. 

**Expected**
Error as .venv folder should not exist

**Actual**
The .venv folder is in the dagger container

## Why
The standard `glob` library  in python 3.10 and lower does not follow hidden paths.
https://github.com/python/cpython/issues/81759
https://stackoverflow.com/questions/49047402/python-glob-include-hidden-files-and-folders

## Solutions
1. Use something other than glob
2. Update to 3.11
3. Write a hack around

**Comment by alafanechere** [comment]
Is it a Dagger problem or a problem in the client code (in the `get_repo_dir` https://github.com/airbytehq/airbyte/blob/main/airbyte-ci/connectors/pipelines/pipelines/models/contexts/pipeline_context.py#L217)

**Comment by bnchrch** [comment]
Its a problem in our client code! Namely globs evaluating before working directory set.
