### ISSUE TITLE
Fix sentry issue grouping for snowflake exception

### ISSUE THREAD

**Issue by gisripa** [airbytehq/airbyte#34074]
The following issues are same

https://github.com/airbytehq/oncall/issues/3879
https://github.com/airbytehq/oncall/issues/3897
https://github.com/airbytehq/oncall/issues/3897

Grouping issue is caused in spite of mangling the exception message because of this probably, leading to a combination of 
AIRBYTE_INTERNAL.ALL_UPPERCASE_RAW_TABLE, "airbyte_internal"."STREAM__raw__Table_name", "airbyte_internal"."ALL UPPERCASE WITH SPACES"

https://docs.snowflake.com/en/sql-reference/identifiers-syntax#controlling-case-using-the-quoted-identifiers-ignore-case-parameter

**Comment by cynthiaxyin** [comment]
Folding this into #33614
