### ISSUE TITLE
Airbyte CI should declare needed infra runners (Can't change airbyte-ci: Format action fails on airbyte-ci changes)

### ISSUE THREAD

**Issue by erohmensing** [airbytehq/airbyte#34076]
The pipx local install of airbyte-ci causes format to fail because format is running on the dagger 0.6.4 runner. The error looks like [this](https://airbytehq.sentry.io/issues/4831824596/events/02bee9de10c04151904b87c97a95d5ca/?alert_rule_id=14570850&alert_type=issue&environment=production&notification_uuid=bd9ff481-1986-4fb9-b096-fac00fb7183e&project=4505596642983936&referrer=next-event). Example [failure](https://github.com/airbytehq/airbyte/actions/runs/7467934607/job/20322417670?pr=34067) from PR: https://github.com/airbytehq/airbyte/pull/34067

<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW14QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e0ff84318e9f099a9902a1b355e460fffb3de24/image.png" alt="image.png" />
<img width="1570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXV4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b36405417434f59af442f8cc2d8eadf309379346/image.png" alt="image.png" />
(P.S. Definitely helpful logs!)

**Comment by alafanechere** [comment]
To overcome this kind of problem a clean solution would be to make the client (`airbyte-ci`) define the runner they're using.

It'd be nice to run, in an upstream job in the workflow a command such as:
`airbyte-ci format --requirements` which would not run anything but just output a json string like:
```
{"runner": "ci-runner-connector-format-medium-dagger-0-6-4", "dagger_sdk_version": "0.6.4"}
```

Then the `runs-on` field in the workflow can be dynamic: templated from the `--requirements` output.

`airbyte-ci format --requirements` would run on a default ubuntu GHA runner (not on our self hosted CI runners) and should not require a dagger client instantiation.

**Comment by erohmensing** [comment]
With https://github.com/dagger/dagger/issues/6379 closed, I think we can avoid spending time on mitigating this specific problem. I like the idea of airbyte-CI defining the relevant runner though, and think it's worth keeping around as an enhancement

**Comment by evantahler** [comment]
Grooming:
* `--requirements` could be appeneded to any command (what are the requirements for any command) OR top-level
