### ISSUE TITLE
Issues while syncing source to Postgres destination with normalization 

### ISSUE THREAD

**Issue by gordalina** [airbytehq/airbyte#3411]
## Expected Behavior
Slack connector should sync messages normally
Stripe connector should sync records normally

## Current Behavior
It's like a full dump is appended to the destination every sync, rather than the diff only.

From the logs it seems that the bookmark is never updated to the day it was synced as it is always 2021-04-01 (what I set as the starting date). 

## Logs
[slack.log](https://github.com/airbytehq/airbyte/files/6476469/slack.log)

## Steps to Reproduce
1. Create a slack source (start=2021-04-01)
1. Create a postgres destination
1. Create a connection between both
1. Have them sync once a day
1. After second sync see data doubled, and after third sync is tripled.

## Severity of the bug for you
High

## Airbyte Version
`0.20.0-alpha`

## Connector Version (if applicable)
`airbyte/destination-postgres:0.2.4`
`airbyte/source-slack-singer:0.2.1`

## Additional context
Running on GCE in GCP

**Comment by marcosmarxm** [comment]
Thanks for reporting this @gordalina! I added the issue to our roadmap and alert the team to analyze it. As far I know, @sherifnada is creating a Slack connector using CDK to improve reliability.

**Comment by gordalina** [comment]
@marcosmarxm this is also happening with stripe so I don't think it's connector-specific.

**Comment by sherifnada** [comment]
@gordalina I would expect this somewhat with the Slack connector due to how the Slack API works. But i'm surprised to hear about it with the Stripe connector. Is the issue happening on particular streams, or is it happening for all streams even the ones configured to sync incrementally?

**Comment by gordalina** [comment]
It is happening with all streams. I can confirm that Shopify has the same issue.

**Comment by sherifnada** [comment]
@gordalina we tried reproducing this without success on the shopify and stripe connectors. Silly question but can you double check that the connectors are set to sync data incrementally? Also, which connector versions are you using?

**Comment by ChristopheDuong** [comment]
> @gordalina we tried reproducing this without success on the shopify and stripe connectors. Silly question but can you double check that the connectors are set to sync data incrementally? Also, which connector versions are you using?

@sherifnada, It's also printed in the logs:

```
configured sync modes: {
  channels=full_refresh - append, 
  teams=incremental - append, 
  channel_members=full_refresh - append, 
  messages=incremental - append, 
  threads=incremental - append, 
  files=incremental - append, 
  users=incremental - append, 
  remote_files=incremental - append, 
  user_groups=full_refresh - append
}
```

**Comment by ChristopheDuong** [comment]
> It's like a full dump is appended to the destination every sync, rather than the diff only.

That's the expected behavior of streams configured with `full_refresh - append`

**Comment by gordalina** [comment]
That seems to be the issue, thank you!
