### ISSUE TITLE
Shopify connector timeouts or hits quota limits

### ISSUE THREAD

**Issue by gordalina** [airbytehq/airbyte#3412]
## Expected Behavior
Shopify connector should recover gracefully from when a connection timeout happens or the quota limit is hit.

## Current Behavior
Right now the connector fails and no data is normalized. From the logs, we see the error as collection timed out, but this may be related to quota limits.
On the next run, the connector starts from the beginning which leads to the same error.

## Logs
[shopify.log](https://github.com/airbytehq/airbyte/files/6476479/shopify.log)

## Steps to Reproduce
1. Create a connection from Shopify to Postgres with normalization
1. Sync
1. See it fail to normalize, but some data is created in the raw tables

## Severity of the bug for you
High

## Airbyte Version
`0.20.0-alpha`

## Connector Version (if applicable)
`airbyte/destination-postgres:0.2.4`
`airbyte/source-shopify-singer:0.2.1`

## Additional context
GCE on GCP

**Comment by sherifnada** [comment]
@gordalina we just published a fix in #3409 -- can you upgrade your connector version to `0.2.2` and try again?

**Comment by gordalina** [comment]
I'll try and let you know, thank you for the quick reply @sherifnada

**Comment by gordalina** [comment]
@sherifnada the new version worked like a charm, thank you!
