### ISSUE TITLE
Source S3 fails to load data from parquet file if value is NoneType

### ISSUE THREAD

**Issue by IlyaDropit** [airbytehq/airbyte#34151]
### Connector Name

source-s3

### Connector Version

 4.3.1

### What step the error happened?

During the sync

### Relevant information

When attempting to read Parquet files from S3 using the connector, there is an issue with casting timestamp values using `isoformat()`. The problem arises when a datetime field contains `NaT` (Not a Time[stamp]), which translates to a null value. In such cases, PyArrow throws a `'NoneType' object has no attribute 'isoformat'` error. As a result the whole row will be omitted  from replication, which is a problem if most of the values in the datetime fields are missing, but they are still important and must be present in the distention table.

The error occurs in [line 95-96 of parquet_parser.py](https://github.com/airbytehq/airbyte/blob/7d7f33c09f9502653d65cb155960c9ac6a5f6e56/airbyte-cdk/python/airbyte_cdk/sources/file_based/file_types/parquet_parser.py#L96) - `pa.types.is_time(parquet_value.type)` - `parquet_value.as_py().isoformat()`.

This error can be handled easily by adding a check for None before attempting to call the `isoformat()`.

Tried to find a workaround by using custom schema - by setting problematic fields as nulls (and even strings in some attempts) and it still didn’t work.

### Relevant log output

```shell
source > Error parsing record. This could be due to a mismatch between the config's file type and the actual file type, or because the file or record is not parseable. stream=orderAllocation file={path-to=s3-file.parquet} line_no=2 n_skipped=0
Stack Trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/stream/default_file_based_stream.py", line 90, in read_records_from_slice
    for record in parser.parse_records(self.config, file, self.stream_reader, self.logger, schema):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_types/parquet_parser.py", line 74, in parse_records
    **{
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_types/parquet_parser.py", line 75, in <dictcomp></dictcomp>
    column: ParquetParser._to_output_value(batch.column(column)[row], parquet_format)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/file_based/file_types/parquet_parser.py", line 96, in _to_output_value
    return parquet_value.as_py().isoformat()
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

### Contribute

- [X] Yes, I want to contribute

**Comment by mikebaldry-acu** [comment]
The same issue occurs with parquet files stored on Azure Blob Storage - it throws an exception on the exact same line. I assume this will be true for anything using that Parquet parser.

**Comment by enkeboll** [comment]
I am experiencing this issue on Airbyte Cloud, S3 v4.5.5.  I encountered this with null values in a Date column from a vendor who uses Spark to generate their parquet files.  I was able to reproduce with my own Pandas-generated parquet files:

```python
import pandas as pd

# Create sample data with null dates
data = {
    'id': [1, 2, 3, 4],
    'username': ['user1', 'user2', 'user3', 'user4'],
    'date': ['' for _ in range(4)]  # Empty dates
}

df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date']) # dates get converted to NaT
df.to_parquet('sample_dates_null.parquet')

# Create sample data with valid dates
data2 = {
    'id': [1, 2, 3, 4],
    'username': ['user1', 'user2', 'user3', 'user4'],
    'date': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04']
}

df2 = pd.DataFrame(data2)
df2['date'] = pd.to_datetime(df2['date'])
df2.to_parquet('sample_dates.parquet')
```
Creating an S3 source pointing to `sample_dates.parquet` works fine:
![image](https://github.com/airbytehq/airbyte/assets/4869523/c69fb9eb-7c0e-44c9-a669-27da5c832f4e)

Creating an S3 source pointing to `sample_dates_null.parquet` fails with the same "AttributeError: 'NoneType' object has no attribute 'isoformat'" error (now [line 104](https://github.com/airbytehq/airbyte/blob/1162302069f80c4c44bea7e3ec28d0454b67c98b/airbyte-cdk/python/airbyte_cdk/sources/file_based/file_types/parquet_parser.py#L104)):
![image](https://github.com/airbytehq/airbyte/assets/4869523/a614d17e-2e1c-40e0-9692-890574eefcba)

**Comment by ryjabe** [comment]
Coincidently, I think I came across the same error [again](https://cloud.airbyte.com/workspaces/afdc3f03-902a-489c-94ff-9c76daa5eedc/connections/82ae86bc-79a7-475e-8db2-1c64cd792208/job-history) for a different prospect (better health).  This is another read from Parquet, and getting an unexpected data type though I couldn't confirm its the same DT issue.  Adding it to the ticket.

**Comment by Shadde1993** [comment]
Hello,

I have issues when the first row in a parquet file contains NaT, but not with files that does contain a date time in the first row but not in the 5th or later rows.
