### ISSUE TITLE
[source-xero] All secrets are being replicated without expiry on GCP

### ISSUE THREAD

**Issue by abedzantout** [airbytehq/airbyte#34160]
### Connector Name

source-xero

### Connector Version

0.2.4

### What step the error happened?

During the sync

### Relevant information

No steps, just connect to Xero, and manually sync every hour. A new secret will be stored in the secrets manager every time a sync happens.

### Contribute

- [X] Yes, I want to contribute

**Comment by abedzantout** [comment]
Resolved by https://github.com/airbytehq/airbyte/issues/39316

However this requires a custom connection for now. Will work on others types of Auth in the next couple of weeks.

**Comment by ivorpad** [comment]
Glad to take this on if you haven't started yet, @abedzantout.
