### ISSUE TITLE
Unable to build new destination connector with gradle

### ISSUE THREAD

**Issue by afillatre** [airbytehq/airbyte#34167]
### Topic

buildConnectorImage step fails

### Relevant information

I'm unable to build a newly created connector because of the following error :

> 3: /Users/alex/Library/Caches/pypoetry/virtualenvs/pipelines-W9gxt-Nu-py3.10/bin/airbyte-ci connectors --name=destination-batch --disable-report-auto-open build --use-host-gradle-dist-tar ERROR: exit status 2
exit status 2

> Task :airbyte-integrations:connectors:destination-batch:buildConnectorImage FAILED

> FAILURE: Build failed with an exception.nation-batch:buildConnectorImage

> * What went wrong:
> Execution failed for task ':airbyte-integrations:connectors:destination-batch:buildConnectorImage'.
> Process 'command '/Users/alex/Documents/Workspaces/Geev/airbyte/.venv/bin/python'' finished with non-zero exit value 1

and

> Error: Invalid value for '--name': 'destination-batch' is not one of 'source-tyntec-sms', 'source-younium', 'source-pocket', [...]

**Steps to reproduce**

> git clone https://github.com/airbytehq/airbyte.git 
> cd airbyte-integrations/connector-templates/generator
> ./generate.sh
> cd -
> ./gradlew :airbyte-integrations:connectors:destination-batch:build

**Environment**
- Mac OS 14.1.2
- JDK 17

**Comment by marcosmarxm** [comment]
You need to use `airbyte-ci` to build connector today.

**Comment by afillatre** [comment]
@marcosmarxm I'm not sure I understand your answer, since : 

- the `build` task launches `airbyte-ci` underneath
- I did follow the existing documentation (or I think so)

What would be the right command and arguments to execute for a vanilla Java destination connector ?
