### ISSUE TITLE
Jira Sprint object load incrementally

### ISSUE THREAD

**Issue by rolldeep** [airbytehq/airbyte#3417]
## Tell us about the problem you're trying to solve
I'm trying to load information for [Jira Sprint](https://developer.atlassian.com/cloud/jira/software/rest/api-group-sprint/) incrementally. Currently your connector doesn't provide any functionality to load Jira's sprint information.

## Describe the solution you’d like
The solution would be the ability to incrementally load sprint's data.

## Describe the alternative you’ve considered or used
Currently my team is doing full update. 

## Are you willing to submit a PR?
Since there is no incremental update for Jira connector, I would like to contribute to the release of this functionality. So please provide some tips on where I can start working on implementation.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368074009997) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@rolldeep great timing -- we are actually currently working on this and are anticipating delivering it by the end of the week or next week at the latest. Will follow up with you here as we make progress!

**Comment by rolldeep** [comment]
@sherifnada thanks for your response. 
Looking forward to seeing your implementation of that feature.

**Comment by rolldeep** [comment]
Hi @sherifnada , how is it going with Jira's incremental load?

**Comment by artem1205** [comment]
@rolldeep, sprint stream cannot be updated using the incremental load, as there is no cursor field.
