### ISSUE TITLE
Ability to full refresh a single table

### ISSUE THREAD

**Issue by iamzjk** [airbytehq/airbyte#3419]
## Tell us about the problem you're trying to solve
When I have incremental sync, I know I can reset and full-refresh all tables from a source. I would love to be able to refresh a single table.

## Describe the solution you’d like
I'm not sure how the state/bookmark is being stored now, if there is a way to clear the bookmark for a single table, then we can reset/re-sync a single table.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?
Yes, if we can get some pointers to where the logic is, we can try contributing

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368197824586) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
duplicate https://github.com/airbytehq/airbyte/issues/6912
