### ISSUE TITLE
Airbyte UI not accessible with docker deployment

### ISSUE THREAD

**Issue by Marcus0086** [airbytehq/airbyte#34197]
### Platform Version

v0.50.43

### What step the error happened?

On deploy

### Revelant information

Cloned the latest airbyte and I got this error. 
Reinstalled by deleting images and volumes but still getting the issue.

<img width="1710" alt="image" src="https://github.com/airbytehq/airbyte/assets/43565099/423e402c-8c04-4565-8a3f-cf49c1ed98f0">

### Relevant log output

```shell
TypeError: Cannot destructure property 'defaultUserId' of 'BRe(...)' as it is undefined.
    at CHe (ConnectorBuilderTestInputService-196a33e5.js:104:168375)
    at Ke (App-36a15ce4.js:1:857)
    at Js (index-4c009345.js:38:19518)
    at nh (index-4c009345.js:40:43960)
    at Jv (index-4c009345.js:40:39724)
    at k_ (index-4c009345.js:40:39652)
    at Ya (index-4c009345.js:40:39506)
    at cs (index-4c009345.js:40:35874)
    at Xv (index-4c009345.js:40:34825)
    at A (index-4c009345.js:25:1559)
ql @ index-4c009345.js:40
Dv.o.componentDidCatch.n.callback @ index-4c009345.js:40
Hf @ index-4c009345.js:38
od @ index-4c009345.js:40
Gv @ index-4c009345.js:40
Gv @ index-4c009345.js:40
Gv @ index-4c009345.js:40
S_ @ index-4c009345.js:40
x_ @ index-4c009345.js:40
er @ index-4c009345.js:40
Xv @ index-4c009345.js:40
A @ index-4c009345.js:25
G @ index-4c009345.js:25
```

**Comment by marcosmarxm** [comment]
@Marcus0086 what versio of the platform are you running?
Can you share the server and worker logs?

**Comment by timroes** [comment]
Closing as inactive. Please feel free to still respond with more details and we'll happily reopen this issue if it still persists on the most recent Airbyte version.
