### ISSUE TITLE
Update Airbyte documentation of Generating source connector

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/airbyte#34238]
### Page URL

https://docs.airbyte.com/connector-development/config-based/tutorial/create-source

### Description

After running generator, Its only chowning a random connector and cuts off and doesn't move further
Ref screenshot:
![image](https://github.com/airbytehq/airbyte/assets/47392334/ff3bf4bf-9d7e-45d6-a718-f062c506ca43)

Possible fix: If there is a change in documentation, please include the change or update the generator shell

**Comment by smantri-moveworks** [comment]
Can you pull the latest changes from master? I see that a very old version of registry.dagger.io/engine is being pulled. The latest one is 0.9.6.

**Comment by btkcodedev** [comment]
Fixed: Cloned master repository again into different folder and after clearing docker caches with `docker system prune -a` and `docker-compose down --volumes --remove-orphans`
Generator seems working fine.
