### ISSUE TITLE
Enable workload services in Helm/K8s for OSS

### ISSUE THREAD

**Issue by jdpgrailsdev** [airbytehq/airbyte#34231]
Enable the workload services in the OSS Helm charts for Kubernetes.

- Check the resource impact of releasing this. This service consumes more resources, however it should reduce the resources the current worker consumes.

**Comment by AronsonDan** [comment]
May I ask what is that feature?

**Comment by davinchia** [comment]
Release document: https://docs.google.com/document/d/1G0GGEYRsOXPqVfQSo5Ak2pqQY5JcXZezLOrPY2bk1lI/edit
