### ISSUE TITLE
[source-hubspot] Incomplete companies property history stream

### ISSUE THREAD

**Issue by DDynamic** [airbytehq/airbyte#34304]
### Connector Name

source-hubspot

### Connector Version

2.0.2

### What step the error happened?

During the sync

### Relevant information

The `companies_property_history` stream is missing records because the `more_key` property has a typo - it should be `has-more` instead of `hasMore`.

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks @DDynamic for fixing the problem. The team will take a look in the next sprint. If you need this ASAP you can always build the connector locally and use meanwhile a dev version

**Comment by DDynamic** [comment]
Understood, thank you @marcosmarxm. I'll check back in a few weeks.
