### ISSUE TITLE
Amazon Seller Partner `InitiateOauth` API Bug

### ISSUE THREAD

**Issue by nis130** [airbytehq/airbyte#34319]
### Connector Name

destination-mysql

### Connector Version

3.0.1

### What step the error happened?

Configuring a new connector

### Relevant information

I am using Powered By Airbyte API's to create a source connection for Amazon Seller Partner. I used the [IntiateOauth](https://reference.airbyte.com/reference/initiateoauth) API to get the consent URL. After Signing  into my Amazon Seller Partner account I get the following error saying. "Invalid redirect url. Please validate the URL first".

<img width="1440" alt="Screenshot 2024-01-16 at 9 41 59 PM" src="https://github.com/airbytehq/airbyte/assets/35602510/9185b6de-5394-4d7c-91e9-1d0d6fd4fc29">

I have also attached the curl to get the consent url.
Thanks.

### Relevant log output

```shell
curl --request POST \
     --url https://api.airbyte.com/v1/sources/initiateOAuth \
     --header 'accept: application/json' \
     --header 'authorization: Bearer <BEARER_TOKEN> ' \
     --header 'content-type: application/json' \
     --data '
{
  "oAuthInputConfiguration": {
    "region": "US",
    "account_type": "Seller"
  },
  "sourceType": "amazon-seller-partner",
  "workspaceId": "<WORKSPAC_ID>",
  "redirectUrl": "https://beta.locale.ai"
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by nis130** [comment]
Hey @alafanechere can you maybe help me with this issue?

**Comment by askarpets** [comment]
Hello @nis130,
This issue has happened due to incorrect redirect URI passed to the request. This should be `https://cloud.airbyte.com/auth_flow` if you're using the cloud solution.

For the OSS solution, could you please try to follow steps described in [docs](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/amazon-seller-partner.md)?

Please let me know if you need any assistance with it.
Thanks!

**Comment by nis130** [comment]
I am using `initiateOauth` api for Powered By Airbyte Usecase (Airbyte Cloud). In this `redirect_url` is [user-defined](https://reference.airbyte.com/reference/creating-oauth-sources#:~:text=Note%3A%20The%20redirect%20URL%20you%20provide%20here%20does%20not%20need%20to%20be%20registered%20with%20Airbyte%20or%20the%20OAuth%20provider.%20The%20only%20requirements%20for%20the%20redirect%20are%20that%20it%3A) and not the one which Airbyte uses.

From what I understand reading the docs is that first `Oauth` of `Amazon Selling Partner` will redirect to https://api.airbyte.com/v1/oauth/callback then airbyte will store the secrets and then redirect to my url which is `https://beta.locale.ai` in this case.

Since, `https://api.airbyte.com/v1/oauth/callback` this URL is not added to the redirect url in amazon selling partner app I am getting this errors. Fix should be quite simply add `https://api.airbyte.com/v1/oauth/callback` in your Amazon Selling Partner App.

**Comment by askarpets** [comment]
This has now been added. Please check and let me know if you see any issues. Thanks!

**Comment by askarpets** [comment]
Closing the task for now. Please reopen if the issue still exists.
