### ISSUE TITLE
Make buttons on Remaining credits card primary + secondary

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#34310]
Currently the buttons on the remaining credits card are the same dark primary. 

![Image](https://github.com/airbytehq/airbyte/assets/146028830/d911a40e-9863-4b5f-934f-d3f7d207a054)

We should make one button primary (the preferred action) and the other secondary, so the user has a clear hierarchy of action.

![Image](https://github.com/airbytehq/airbyte/assets/146028830/89453c8e-6032-434a-9dee-f40274cc0271)

**Comment by nora-airbyte** [comment]
@nataliekwong Do you think "Buy credits" is the right primary action here? I took a guess

**Comment by nataliekwong** [comment]
Yep! 20% of the people on that page click it (compared to 2% talk to sales)
