### ISSUE TITLE
[source-github] Add `files` property to `commits` stream schema

### ISSUE THREAD

**Issue by dlouseiro** [airbytehq/airbyte#34318]
### Topic

Add new property to Source Github

### Relevant information

As documented in [Github's commits REST API](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits), one of the properties that is available when listing commits is `files`, which contains relevant information about each file changed within a commit (number of additions, deletions, etc).

I believe this property could be added to the Source Github, so I created this [PR](https://github.com/airbytehq/airbyte/pull/34317) to do so.

As it's my first contribution to Airbyte, I may be missing something, but I tried to strictly follow the contribution documents.

**Comment by marcosmarxm** [comment]
Thanks for the quick fix @dlouseiro the team will take a look next sprint to your contribution.

**Comment by lazebnyi** [comment]
@dlouseiro Thanks for your PR. But pull requests commits schema has not field files - https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-commits-on-a-pull-request
