### ISSUE TITLE
Make banners dismissable

### ISSUE THREAD

**Issue by nora-airbyte** [airbytehq/airbyte#34340]
It's pretty scary to have a full-width, brightly colored banner at the top of the product that the user can't even dismiss. I think when a banner is so ubiquitous like this, it paradoxically starts to fade into the background fulfills the opposite of its purpose: the user starts missing it/scanning over it.

We should make AlertBanners dismissible and trust the user to absorb the alert before dismissing.

**Comment by chandlerprall** [comment]
Closing notes:

* strong overlap with notification center
* could be part of No Red In App, but instead of removing banners could be a color choice
* low priority
