### ISSUE TITLE
Oracle Netsuite Connector

### ISSUE THREAD

**Issue by nifrali** [airbytehq/airbyte#3434]
## Tell us about the new integration you’d like to have
* Connector for Netsuite to Snowflake or BigQuery
 
## Describe the context around this new integration
*ERP Data to a common data platform
* Daily syncs
* JDBC or SOAP api

## Describe the alternative you are considering or using
Fivetran of Stitch Data

**Comment by marcosmarxm** [comment]
Thanks @nifrali for the request, but this duplicated issue #3212. I'll close as duplicated and let you know about any future updates.

**Comment by ChristopheDuong** [comment]
Maybe we could re-open this issue to handle the:
https://www.netsuite.com/portal/developers/resources/suitetalk-documentation.shtml

While #3212 would be about the paid NetSuite plugin:
https://www.netsuite.com/portal/platform/developer/suiteanalytics.shtml
