### ISSUE TITLE
Destination Redshift: investigate flakey tests

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#34386]
~A scenario that was causing flakey tests for me was updating `1s1t_config.json` locally to replace `use_1s1t_format: true` with the new `is_v2_destination: true` post GA. When running airbyte-ci test, I had a varying number of test failures, all of the form "Raw/Final table is incorrect". Here are some gradle scans:~
- ~1 failure https://scans.gradle.com/s/4mkguut5cy542~
- ~2 failures https://scans.gradle.com/s/e4gd67a4srs6y~
- ~11 failures https://scans.gradle.com/s/bn6celr243csq~

My test scenario was not realistic/not something that will actually happen. But @gisripa has seen flakey tests too like `RedshiftStandardInsertsTypingDedupingTest > identicalNameSimultaneousSync()`.

**Comment by jbfbell** [comment]
Potentially fixed as a result of other changes, will reopen if it happens again
