### ISSUE TITLE
[webapp] Icon disappears after upgrading/downgrading connector version

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#34385]
### Topic

icon webapp

### Relevant information

Airbyte is not displaying the icon when you upgrade or downgrade an official connector
https://www.loom.com/share/2a006e8c74ba4ca89db62e10bb070efe

**Comment by josephkmh** [comment]
This has been fixed! https://github.com/airbytehq/airbyte-platform-internal/pull/10803
