### ISSUE TITLE
Improve our story around specifying memory requirements in Java Connectors.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3440]
## Tell us about the problem you're trying to solve
We do not pass in memory requirements to our Docker containers today.

By default, Java 14 will set 1/4 of the Docker host's memory as a limit.

Some situations that will cause this:
1) Setting a large part size when using S3. Since part size directly affects total table size, a larger part size is required to sync larger tables. Current required memory = 20 (10 upload threads + 10 queue size) * part size.
2) When Java Source/Destinations read tables with large row sizes, they can run into OOM. This is related to #3439, since using record number as a batch size is the cause of most of our memory issues. Doing this ticket (on both source and destination) will let us specify sane connector memory defaults, and prevent OOM issues.

Today the only recourse our users have is to use a bigger instance.

## Describe the solution you’d like
Our eventual solution should provide users with an escape hatch to configure memory requirements if needed.

This will affect users with big table, which are most frequently our power users.

This is also a nice to have for when we get on Kube. It's not strictly required since we can not specify Kube memory requirements - this will put us in the same place as where we are now with our docker deploy.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368131700902) by [Unito](https://www.unito.io)

**Comment by danieldiamond** [comment]
👍  running into a lot of pain surrounding this issue. looking forward to having this resovled
