### ISSUE TITLE
[source-hubspot] missing data for `companies` stream

### ISSUE THREAD

**Issue by madisonschott** [airbytehq/airbyte#34446]
### Connector Name

Hubspot  (HubSpot Companies <> Redshift)
- only companies stream being synced in this specific connector 

### Connector Version

2.0.2

### Destination Version 

Redshift- 0.8.0

## Platform Version

0.50.5

### What step the error happened?

During the sync

### Relevant information

Missing data from the source that is available via Postman but for some reason not being retrieved via Airbyte, however, there are no errors I can see in the syncs and no reason that this source data would be missing. 

EX: 
<img width="1254" alt="Screenshot 2024-01-23 at 10 17 04 AM" src="https://github.com/airbytehq/airbyte/assets/126522345/5bd64693-4f37-43ea-8e1b-79695edf545d">

You can see the account_id and hubspot_company_record_id here, yet this is missing in source data. 

select * from airbyte.hubspot_companies_properties where account_id=1658852;
-- returns none

select * from airbyte.stg_airbyte__hubspot_companies where hubspot_company_record_id=18805387436;
-- returns none

There are over 8,000 company records that we are missing.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@madisonschott a few questions:
* how much records were ingested? (trying to calculate the % missing records)
* what version of Redshift connector are you using?
* (probably) you're using normalization, correct? are you able to query the raw table and check if the data is there?
* would be possible to run an experiment and create another connection and sync a full refresh and check if there is missing data too?

**Comment by madisonschott** [comment]
- at least 1,420,286 records- as this is the number of companies that have this `hubspot_company_record_id`
- Redshift 0.8.0
- (let me look)
- possible, yes probably, however this would be time consuming and I'm not sure it would solve the root issues, as I did run an entire resync and it took a day- what would this help you learn?

**Comment by madisonschott** [comment]
Looks like the accounts are not in the raw data either

**Comment by madisonschott** [comment]
@marcosmarxm I should be able to set up another connector if that will help us get to the root cause of this issue. Can you update me on why you think this would be helpful to getting to the root of the problem?

**Comment by marcosmarxm** [comment]
@madisonschott the suggestion is to use full refresh and see if the data is completed loaded or not. Because if it is we can narrow down the problem to incremental syncs and not paginations.

**Comment by madisonschott** [comment]
Ok, I did do a resync and the issue still persisted- wouldn't that mean it isn't due to incremental? But I will set up another stream.

**Comment by vsrekha213** [comment]
Topology: Hubspot -> Bigquery
I have added a new column in HubSpot-contacts, in the replication tab when I manually refreshed the source schema, I was able to get the list of changed schema, and again when I synced (mode: incremental + deduped) the new column is not updated in target.

**Comment by madisonschott** [comment]
@marcosmarxm There is so much data at the source, that the connector has just continually failed. I don't think it's going to be possible to completely run the sync from scratch again. Unless you can somehow take a look to see what is happening.

**Comment by madisonschott** [comment]
Any updates on this? I think it is safe to say that the issue is with the incremental logic.

**Comment by madisonschott** [comment]
@marcosmarxm any updates on this? We are still experiencing the same issues and will need to move to a different tool if it's not going to be resolved.

**Comment by artem1205** [comment]
working on it

**Comment by artem1205** [comment]
@madisonschott ,
Could you please clarify two questions for me?

1. There are over 8,000 of missing records. Do these records have something in common? E.g. date interval, archive status, etc.
2. Could you provide an example of request (and response) you've used in Postman?

**Comment by madisonschott** [comment]
1. Nope, I wasn't able to find a pattern.

**Comment by artem1205** [comment]
Hmm, could you provide logs? I'd like to inspect it.
Secondly, could you share your credentials for testing?

**Comment by madisonschott** [comment]
@artem1205 What logs would you like? There are no specific errors in the logs. And is there another way I can share credentials, as I don't feel safe sharing them in a public Github issue.

**Comment by artem1205** [comment]
@madisonschott , 
> What logs would you like?

Logs from the last sync.

> And is there another way I can share credentials?

Were you able to share credentials with @marcosmarxm ?

**Comment by marcosmarxm** [comment]
@madisonschott please contact me in Slack!

**Comment by artem1205** [comment]
Closing as no response.
will reopen it if the issue reoccurs.

**Comment by philk1991** [comment]
@marcosmarxm we're currently seeing this issue with `contacts`. Was this ever resolved?

**Comment by marcosmarxm** [comment]
@philk1991 the team wasn't able to reproduce the issue. Please open a new issue reporting what version and giving specific details so we can work on a fix.
