### ISSUE TITLE
Destinations BigQuery + Snowflake: set isV2Destination()

### ISSUE THREAD

**Issue by cynthiaxyin** [airbytehq/airbyte#34466]
We punted this during Redshift GA bc of CDK shenanigans. They don't actually use this code path but should set isV2Destination to true for completeness/correctness.

**Comment by cynthiaxyin** [comment]
BigQuery change is covered by #34468
Snowflake change is #34501

**Comment by cynthiaxyin** [comment]
reopening bc Snowflake broke

**Comment by gisripa** [comment]
Fixed here https://github.com/airbytehq/airbyte/pull/34528
