### ISSUE TITLE
[API] `/jobs` "500 Invalid Consent URL" when using orderBy

### ISSUE THREAD

**Issue by sneakersgames** [airbytehq/airbyte#34472]
### Topic

api orderBy 500 error

### Relevant information

Making a request to GET /jobs endpoint (https://reference.airbyte.com/reference/listjobs) using **orderBy** gives a 500 error, leaving out orderBy works as expected.

`/v1/jobs?connectionId=f6b24369-5c17-410a-900c-bfa875e70c69&limit=200&offset=0&jobType=sync&status=succeeded&orderBy=updatedAt%7CDESC`

Response:
{
    "type": "about:blank",
    "status": 500
}

Airbyte version 0.50.35 - deployed through Docker

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @sneakersgames maybe I wrong but there is a fix to the issue here https://github.com/airbytehq/airbyte-platform/pull/300

**Comment by dantribble** [comment]
I too am seeing this issue

**Comment by marcosmarxm** [comment]
Fixed by https://github.com/airbytehq/airbyte-platform/commit/eb2504aaaaa5f50dd12f30461c71928f6b516cff
