### ISSUE TITLE
Add version configuration context

### ISSUE THREAD

**Issue by pedroslopez** [airbytehq/airbyte#34487]
## What 

When configuring version overrides, we want to give folks the right context on what is currently configured that may affect the target/scope you're working with.

An example from the tech spec:

<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTMyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9f01c1e51b7371f63971527b9bf74201268bd9/image.png" alt="image.png" />
 
## Acceptance criteria

- Be aware of the current and latest versions being served for the given target.
- Be aware of configurations in place w/ lower priority than the current target. 
    - For example, if I'm configuring an actor-level version, see the workspace or organization-level configs that may be in place
 - Be aware of more specific configurations in place
     - For example, if I'm configuring a workspace-level version, see any actor-level configs that may take precedence over the one I'm currently configuring

**Comment by evantahler** [comment]
Grooming:
* data service split makes joins impossible (`scopedConfigurationService`). 
* The 'dirty' way to do this (joins) would be... Jooq?  But, DB implementations aren't shared. 

Given the service boundaries, we have to do a list-all between services and then filter (from caller). 

What should happen is that services could get read-only access to other repositories.  But... transactions?
