### ISSUE TITLE
Add SVGs for new connectors

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3450]
Since the first [issue](https://github.com/airbytehq/airbyte/issues/2122) where we set up icons for connectors, we have created many new sources and gordalina has kindly grabbed the svgs for a bunch of them [here](https://github.com/airbytehq/airbyte/issues/2122#issuecomment-823777810). We should incorporate these into the server when we have the chance.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368073233185) by [Unito](https://www.unito.io)

**Comment by alecmocatta** [comment]
Is there any updata on this? I see a load of icons (e.g. AWS CloudTrail) are visible on the Airbyte [connectors page](https://airbyte.io/connectors), but not in Airbyte itself?

**Comment by misteryeo** [comment]
Closing this issue as we'll be updating in this issue: https://github.com/airbytehq/airbyte/issues/13491
