### ISSUE TITLE
Add a button to request integrations in the UI when adding new sources/destinations

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3452]
## Tell us about the problem you're trying to solve
We want to make it super easy for users to communicate which sources & destinations they want to use in Airbyte. To this end, can we add a link on the page to add new sources/destinations which redirects them to the page to request a new integration (https://github.com/airbytehq/airbyte/issues/new?assignees=&labels=area%2Fintegration%2C+new-integration&template=new-integration-request.md&title=) ? I'm imagining this would go on the following page (and its destination equivalent): 

![Screen Shot 2021-05-17 at 1 54 17 PM](https://user-images.githubusercontent.com/6246757/118555870-0d968b00-b718-11eb-86bb-e7d6fb131155.png)

cgardens FYI for frontend prioritization

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368059590148) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Here's a suggestion of UI: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25296%3A0

**Comment by cgardens** [comment]
added to next sprint.

**Comment by Jamakase** [comment]
@cgardens Just noticed that we do not have API endpoint for it or I am looking into wrong place. Could you please say which endpoint should I use?

**Comment by johnlafleur** [comment]
@cgardens should we log that information directly into Orbit.love?

**Comment by cgardens** [comment]
I'm fine with just sending it there.

**Comment by johnlafleur** [comment]
I think the best would be to send the information gathered in a webhook: 
https://hooks.zapier.com/hooks/catch/6723499/bbubwxl/
So I can leverage Zapier to put it anywhere I need to. Can we do that?

**Comment by michel-tricot** [comment]
Why zapier directly and not segment?

**Comment by johnlafleur** [comment]
Segment would work as well, as I would still be able to get it on Zapier,
and we can leverage the data elsewhere.
Let's do Segment. But I would need the email address to be added to the
event in that case, this is important as it enables me to leverage Zapier.
I've added the segment event "Request a connector" in the Segment tracking
specs:
https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

**Comment by cgardens** [comment]
@Jamakase is is workable for you to report this to segment using the new event that john mentioned? Will you be able to easily pass the email address as one of the attributes?

**Comment by cgardens** [comment]
discussed off line. that's how the implementation is already setup to work.
