### ISSUE TITLE
Can't find data on destination (Snowflake)

### ISSUE THREAD

**Issue by royt-via** [airbytehq/airbyte#3461]
## Expected Behavior
Should be able to see the data on destination.

## Current Behavior
Couldn't find data on Snowflake (double checked destination connector's settings).
Files (with records) are being created on S3 but not copied into Snowflake.

## Logs
[Logs](https://drive.google.com/file/d/1Am6IE94XPg1YtorF_i-kZoXQsDvPNbs2/view?usp=sharing)

## Steps to Reproduce
1. Sync data from any source to Snowflake destination.

## Severity of the bug for you
Critical

## Airbyte Version
0.22.2-alpha

## Connector Version (if applicable)
airbyte/destination-snowflake 0.3.5

## Additional context
t3a.xlarge EC2

**Comment by royt-via** [comment]
UPDATE:
Found the data on a schema called `public`.
I'm syncing data from Postgres (`public` schema) into Snowflake (`airbyte` schema) but for some reason it looks like Airbyte is ignoring the schema I explicitly defined when setting up the destination connector.

**Comment by davinchia** [comment]
@royt-via this is our current behaviour. We mirror the source's schema will replicating data. The schema defined when setting up the destination is the default schema to use if the source doesn't define a namespace. See https://docs.airbyte.io/understanding-airbyte/namespaces#syncing for more info.

We've received several asks to make this configurable, so this is high up on our list to work on. How urgent is it for you?

**Comment by royt-via** [comment]
hey @davinchia, it's very important for me because I have multiple Postgres DBs I'd like to sync but by default all Postgres schemas called `public` so now I have issues with tables of the same name. I'm using the `prefix` option to deal with it for now but it's not convenient having multiple DBs under the same schema :/

**Comment by davinchia** [comment]
Understood. I am going to add #3481 into next week's work. Please follow that for updates.

I'm going to close this ticket for now since the original intent is solved.
