### ISSUE TITLE
Source-Google-Analytics-data-api - Issue

### ISSUE THREAD

**Issue by Riya-gupta-8** [airbytehq/airbyte#34715]
### Connector Name

Source-Google-Anlaytics-data-api

### Connector Version

0.11

### What step the error happened?

Other

### Relevant information

It is mentioned that using this source connector we can fetch multiple property ids data together by passing multiple property ids in property_ids key. But it didn't fetch the data of the all ids only fetches the first property id data. Is there anyone who had used this connector for the same purpose as mine.
I am not sure of the version that i have mentioned.
### Relevant log output

```shell
NA
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed because issue it isn't following the title and providing enough information about the issue.
