### ISSUE TITLE
Scrambled column order, data types and column name change when loading from MSSQL to MSSQL 

### ISSUE THREAD

**Issue by greiff81** [airbytehq/airbyte#34744]
### Connector Name

destination-mssql

### Connector Version

0.2.0

### What step the error happened?

Other

### Relevant information

I am aware of the data type mapping table that the connector uses to convert a non MSSQL source to an MSSQL destination.
However I think that when loading from MSSQL to MSSQL the column order, the data types and column names should remain unchanged.
In following example I am loading one table called TDWA92_EMPLOYEE from one database into another in the same SQL instance.
This is a screenshot of the source:
![image](https://github.com/airbytehq/airbyte/assets/77500582/7531477d-a8a7-4002-b9cd-3d4f7dff308e)

This is a screenshot of the target created by airbyte:
![image](https://github.com/airbytehq/airbyte/assets/77500582/3cedaf98-6b55-49d9-82a4-f9eea02f95d2)

Following issues appear when comparing source and target:
- the column order changed 
- the table name and column names are all lower case. 
- string data types were all converted to nvarchar(max) 
- all numeric data types to bigint. 
- Furthermore the not null contraint on LAST_UPDATE was dropped.

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment]
Airbyte is an ELT tool, not a MSSQL replication tool.  The choices we make are to make the ELT experience the best:
* We don't maintain column order - this makes schema migrations easier in the future
* We support (and cast-to) limited data types that all destinations can handle
* We don't move constraints.  Most data warehouses or files don't support constraints in the same way.
* We add additional columns that make learning about the ELT process in the destination easier (timestamps, etc)
