### ISSUE TITLE
Generate documentation for each test case/suite in SAT

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3474]
## Tell us about the documentation you'd like us to add or update
The high-level picture for source acceptance tests is described [here](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/testing-connectors) but it's not clear to me what each test case does. As a contributor to Airbyte it is very helpful when debugging to understand what each test is doing. 

## Are there any related areas of documentation that currently exist? Could you point to them? 
https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/testing-connectors

**Comment by keu** [comment]
https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/standard-source-tests
