### ISSUE TITLE
[source-shopify] Getting insufficient data for `customers` stream

### ISSUE THREAD

**Issue by Manoj-07** [airbytehq/airbyte#34764]
### Connector Name

airbyte/source-shopify

### Connector Version

0.5.0

### What step the error happened?

During the sync

### Relevant information

We are getting less number of customer profiles while trying to pull the data using the Shopify connector when compared to Klaviyo.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
The version used is quite old. Please update to latest one, if the issue persists please open a new issue.
