### ISSUE TITLE
Setup alerts for failed connector builds

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3477]
## Tell us about the problem you're trying to solve
We need a way to know when connector builds are failing so we can remedy the situation. We previously had the connector health page (removed here: https://github.com/airbytehq/airbyte/pull/3478) but because this didn't have any alerts associated with it, it was hard to proactively remedy any failures. This ticket tracks creating an alerting system for build failures. 

## Describe the solution you’d like
When a connector build has been failing repeatedly (more than 25% of builds, or some other reasonable percentage/metric) I would like to get a Slack alert which informs us about this so we can take action.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368196663606) by [Unito](https://www.unito.io)

**Comment by alafanechere** [comment]
I think the BuildReport bot posting in our #connector-health channel is already taking care of this.
More details about this alerting system:
* managed by this [GitHub action](https://github.com/airbytehq/airbyte/blob/master/.github/workflows/build-report.yml). It is * runs everyday at 1 PM UTC
* displays success/failure for beta and alpha connectors
* show success/failure in the last build and the two last builds

Our contractor team is monitoring the slack channel and appears to react when build failures occurs.

@sherifnada I think your requirements are met, shall we close this?

**Comment by sherifnada** [comment]
yup we can close!
