### ISSUE TITLE
Ability to override destination namespace.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3481]
## Tell us about the problem you're trying to solve
Today we mirror the source's namespace when syncing data.

This dedups on conflicting table names e.g. a `users` table in the `public` schema and a `users` table in a `staging` schema is replicated into `public` and `staging` schema respectively.

However, this is too inflexible in some cases where users want more logical naming over the replicated tables instead of the source's schema.

## Describe the solution you’d like
User should be able to configure the destination namespace at a table level when setting up a connection.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368196361379) by [Unito](https://www.unito.io)

**Comment by leecheeaun** [comment]
Just to follow up on this issue, as a user, I would like to have the ability to refer to my destination tables in BigQuery with logical names rather than using the default name space.

For example, if using the default name space, a query in dbt would look like:

```
with source as (
    select * from {{ source('dbo', 'payments') }}
)
```

If we had the ability to rename the schema to a logical name in the destination, the query would look like:

```
with source as (
    select * from {{ source('accounts', 'payments') }}
)
```

**Comment by royt-via** [comment]
hey @davinchia , any estimation on when this enhancement will be ready?

**Comment by davinchia** [comment]
@royt-via this is being worked on this week! Will keep you updated!

**Comment by andresbravog** [comment]
Thanks for the update @davinchia, if the solution gets done this week, when will it be released? I'm currently working on a dbt transformer to work around this problem so it would be really cool if we can just wait one week.

**Comment by erichartono** [comment]
+1 for this too. I upgraded from 0.18.0 to 0.24.4 and got this surprise. Thanks Davin. 🙏

**Comment by ChristopheDuong** [comment]
> Thanks for the update @davinchia, if the solution gets done this week, when will it be released? I'm currently working on a dbt transformer to work around this problem so it would be really cool if we can just wait one week.

I pushed two PRs to solve this issue, you can take a look and see the progress!

Usually, we release every week so you might get it next week if the PR are approved/merged this week!
If it's a blocker, let us know we can also make early releases too.

**Comment by johnlafleur** [comment]
Design suggestion: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25747%3A6310

**Comment by ChristopheDuong** [comment]
> However, for this feature, note that my PR are only the backend part of it, we still have to add some fields in the UI to enable the usage of it (should be quick)

FYI this issue will be addressed and closed once (UI) #3852 and (docs) #3886 will be merged. 

Hopefully, this can be completed next week and everything can be shipped as part of version `0.25.0-alpha`!

**Comment by andresbravog** [comment]
@ChristopheDuong is there any way to update that property via API or curl to start testing this out on the master branch?

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong is there any way to update that property via API or curl to start testing this out on the master branch?

The backend part just got merged into master, so it is not released yet either.
Therefore, you need to build and use a local airbyte image of the server as described here: https://docs.airbyte.io/contributing-to-airbyte/developing-locally#run-in-dev-mode-with-docker-compose

Then, yes you can definitely start using via API/curl as shown here:
https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/connections/create

**Comment by andresbravog** [comment]
I have tested this feature with the current master and using the API and is working nicely. Thanks @ChristopheDuong ! looking forward to having the UI in place so we can handle everything via the UI.

**Comment by cgardens** [comment]
closes https://github.com/airbytehq/airbyte/issues/4063

**Comment by ChristopheDuong** [comment]
The UI PR is being reviewed and will be merged soon!
https://github.com/airbytehq/airbyte/pull/4129#pullrequestreview-684959930

We should be able to release it as part of the 0.26 tomorrow (or shortly after)
