### ISSUE TITLE
[destination-snowflake] Connector Doesn't check of Schema Exists prior to attempting 'create if not exists schema' DDL

### ISSUE THREAD

**Issue by kcarrillorhoads** [airbytehq/airbyte#34819]
### Connector Name

destination-snowflake

### Connector Version

v3.5.4

### What step the error happened?

During the sync

### Relevant information

With the update of the new V2 Destinations we encountered an edge case where a role which did not have `create schema` privileges on the database was unable to properly sync because the destination would attempt to `create schema if not exists`
The snowflake role in question did not have the create schema grant (as that would allow it to overwrite other schemas in the database) as it was intended to only operate on specific schemas in that database.
We did validate that the role could create tables in the target schema but because the role didn't have `create schema` grants it caused the workflow to fail since that `create schema if not exists` statement was running.

Dagster encountered a similar problem and solved it by first doing a check if the schema exists prior to executing a create if not exists: https://github.com/dagster-io/dagster/pull/12802/files

### Contribute

- [ ] Yes, I want to contribute

**Comment by gpchandran** [comment]
Hi @jbfbell  @kcarrillorhoads 
any reason this defect is frozen state, I'm good to contribute for fix/validation added in the Destination-Snowflake connection: 

Triggering point :
https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/java/airbyte-cdk/typing-deduping/src/main/kotlin/io/airbyte/integrations/base/destination/typing_deduping/TyperDeduperUtil.kt
