### ISSUE TITLE
Getting 401 Access Denied on Login to Local Deployment

### ISSUE THREAD

**Issue by michaelimas** [airbytehq/airbyte#34823]
### Platform Version

0.50.47

### What step the error happened?

On deploy

### Revelant information

Getting this error when i open http://localhost:8000/ after a very standard docker deployment (ran ./run-ab-platform.sh and also tried docker-compose up):

🐙 Nope.
HTTP Error Code: 401
This deployment of Airbyte is protected by HTTP Basic Authentication. Please refer to the [Airbyte docs](https://docs.airbyte.com/) to learn more about:

[the default username/password](https://docs.airbyte.com/quickstart/deploy-airbyte)
[securing your Airbyte deployment](https://docs.airbyte.com/operator-guides/security) including turning off or changing the default username/password.
![Screenshot 2024-02-04 at 17 40 10](https://github.com/airbytehq/airbyte/assets/90142755/f88c1c65-c7c1-424c-8b1d-ce01ac280450)

**Comment by marcosmarxm** [comment]
Closing as none user reported the same issue.
