### ISSUE TITLE
[destination-redshift] Docs missing parameter 

### ISSUE THREAD

**Issue by meyerovb** [airbytehq/airbyte#34820]
### Connector Name

destination-redshift

### Connector Version

2.1.5

### What step the error happened?

None

### Relevant information

docs/integrations/destinations/redshift.md
References "Part Size" but that's not a configurable option.  Instead "File Buffer Count" is an option but it's not in the doc.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @meyerovb
