### ISSUE TITLE
Support Pinterest Marketing API

### ISSUE THREAD

**Issue by alderson59** [airbytehq/airbyte#3484]
## Tell us about the new integration you’d like to have
Pinterest Marketing API as a source

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368130497684) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
thanks @alderson59 I added the suggestion to the connector roadmap.

**Comment by sherifnada** [comment]
@cheyura fixed the issue. Moving out of blocked

**Comment by cheyura** [comment]
@sherifnada Pinterest ad campaign for 30 days with budget 30 USD (min daily is 1 USD) will start within 24 hours

**Comment by sherifnada** [comment]
@cheyura can we just keep it running instead of only 30 days?

**Comment by cheyura** [comment]
> @cheyura can we just keep it running instead of only 30 days?

@sherifnada Yes

**Comment by lazebnyi** [comment]
Application for creating the app in Pinterest now is pending. As far as I know from the update from @cheyura the request was sent on July 8. 

Original message from Pinterest: 

> Thank you for your interest in the Pinterest API! We're working on some updates to our program and are currently taking a pause in reviewing applications while we focus on what's next. If you'd still like to apply to our program we'll reach out to the email associated with your account once there's an update. We're excited to share with you what we've been working on.

**Comment by cheyura** [comment]
@lazebnyi app is ready
