### ISSUE TITLE
CDK: Allow to use Pydantic for specs

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#3486]
## Tell us about the problem you're trying to solve
Currently, we have specs defined as JSON Schemas, we could use Pydantic models (see source Klaviyo) instead.

## Describe the solution you’d like
AbstractSource should have property

```python
@property
def config_class(self)
    pass
```

that will return Pydantic model for config

```python
class ConnectorConfig(BaseModel):
    class Config:
        title = "Klaviyo Spec"

    api_key: str = Field(
        description='Klaviyo API Key',
        airbyte_secret=True,
    )
    start_date: str = Field(
        description="UTC date and time in the format 2017-01-25T00:00:00Z.",
        pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$",
        examples=["2017-01-25T00:00:00Z"],
    )
```

Source should parse it and accept it instead Mapping in its methods:

```python
def check_connection(self, logger, config: ConnectorConfig) -> Tuple[bool, any]:
    pass
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368130503558) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
we're moving away from using pydantic where possible as it makes it harder to allow non-engineers to edit specs
