### ISSUE TITLE
Incremental Sync - Deduped WITHOUT History

### ISSUE THREAD

**Issue by royt-via** [airbytehq/airbyte#3487]
## Tell us about the problem you're trying to solve
I'd like to sync data in an incremental way (records being updated and not appended) but no need for the history table.

## Describe the solution you’d like
Having a sync option - `Incremental Sync - Deduped` (no history)

## Describe the alternative you’ve considered or used
Using `Incremental Sync - Deduped History`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368072246878) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Thanks for the issue!

Could you elaborate on the problem you're trying to solve?

What is the problem of having the history table being generated in the destination? Do you have concerns about storage space being used or are there some other reasons why it is unwanted?

**Comment by royt-via** [comment]
Hi @ChristopheDuong, I'm trying to avoid both unused/unnecessary tables and inserts/copy commands on the destination DB

**Comment by ajzo90** [comment]
Hi! I would also like this feature. 
In addition to @royt-via, I also think that the cleanup details in the documentation is a bit vague and is open for interpretation as it is right now. Am I allowed to clean up the history table immediately for example, effectively eliminate the history mode? 
To resolve that I would prefer to have 1) a strict mode where cleanup is not allowed, and 2) deduped without history? 

> Note that in Incremental Deduped History, the size of the data in your warehouse increases monotonically since an updated record in the source is appended to the destination history table rather than updated in-place as it is done with the final table. If you only care about having the latest snapshot of your data, you may want to periodically run cleanup jobs which retain only the latest instance of each record in the history tables.

**Comment by ChristopheDuong** [comment]
## Quick implementation:
One approach is to clean up extra rows after normalization:
- The main piece of work that needs to be done for implementing this is to also purge the `_airbyte_raw_*` tables that are in history mode by default but to keep only the latest rows there too.
- Disabling the generation of the `_scd` tables is trivial to do but needs the ability to change the generated dbt project settings...

## Long term implementation
Another approach, but not so easy to execute is to always drop completely the `_airbyte_raw_*` tables after the normalization process ran. This would require an "Incremental batch normalization" (see https://github.com/airbytehq/airbyte/issues/2566 for more details)

**Comment by ajzo90** [comment]
I think of this proposal as an additional property in the protocol that each destination can opt in to support. 
It is possible for a destination to support this feature without the normalization (as I understand the protocol, and since the normalization is optional)

**Comment by ajzo90** [comment]
A related use case: to handle late arriving facts (ex https://discourse.getdbt.com/t/on-the-limits-of-incrementality/303) 
When a source transfer events with a window, say 3 last days. Noe it is neither a full nor an incremental sync. 

In that case It would make sense for the destination to dedup without history. 

On the source side it is allowed to use windows, since its follows the "at-least-once" delivery principle.

**Comment by ChristopheDuong** [comment]
> I think of this proposal as an additional property in the protocol that each destination can opt in to support.
> It is possible for a destination to support this feature without the normalization (as I understand the protocol, and since the normalization is optional)

Yes, you are right, there is also the option of a destination handling the sync mode completely on its own without relying on normalization at all.

There is a `supported_destination_sync_modes` enum in the spec.json of the destination where there could be an enum value to denote what you describe in there.
So even destination that don't support normalization (or that don't support dbt either), could still implement the sync modes such as dedupe with or without history etc

**Comment by ajzo90** [comment]
That would be awesome. It adds some complexity to the protocol and UI.

**Comment by davinchia** [comment]
This is now possible with Destinations V2.
