### ISSUE TITLE
[Roadmap] Destination Data Lake Databricks to Certified

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#34874]
Destination Databricks gains the [Destinations V2 treatment ](https://airbyte.com/blog/introducing-airbyte-destinations-v2-typing-deduping).  This includes the async framework (faster!) and better Typing and Deduplication, error handling, and more

**Comment by kendru** [comment]
Will this include supporting Destinations V2 for Databricks?

**Comment by evantahler** [comment]
> Will this include supporting Destinations V2 for Databricks?
Yes it will!

**Comment by kendru** [comment]
Is this still on the roadmap? The lack of support for transformations in the current Databricks destination is a major impediment for my team. We would be happy to help contribute if the there is any portion that is open to community contributions.

**Comment by evantahler** [comment]
Yep! It's coming in the next few months. Stay tuned!

**Comment by alexbegg** [comment]
I wanted to share that I am in the process of migrating from Redshift to Databricks and I would like to beta test a Destinations V2 version of the Databricks connector when available. I previously beta tested the Redshift Destinations V2 connector.

**Comment by nataliekwong** [comment]
We've released a modernized [Databricks destination (v3.1.0)](https://github.com/airbytehq/airbyte/pull/40692) with several new features, including typing & deduping (Destinations V2), refreshes, and [resumable full refresh](https://airbyte.com/blog/resumable-full-refresh-building-resilient-systems-for-syncing-data)!

We are now working towards certification in the coming months. If you have any feedback on v3.1.0, feel free to share it here.

**Comment by amelia-ay** [comment]
Hi, Thank you for developing this plugin. It is precisely what we badly need. We have now used versions 3.2.5 and 3.3.0, and then encountered some issues. When we synchronize data reaching 200+ tables and a single table has 3TB of data, an OutOfMemoryError occurs. We have tried adjusting the resource, but it didn't work. Could you please help and give some suggestions? Thanks again.

**Comment by nataliekwong** [comment]
@amelia-ay could you modify the connection's memory? https://docs.airbyte.com/operator-guides/configuring-connector-resources#configuring-connection-specific-requirements

**Comment by nataliekwong** [comment]
Databricks is now an Airbyte Connector, so I will go ahead and close this issue.

**Comment by amelia-ay** [comment]
> @amelia-ay could you modify the connection's memory? https://docs.airbyte.com/operator-guides/configuring-connector-resources#configuring-connection-specific-requirements
