### ISSUE TITLE
Source MSSQL: Pipeline sync issue for sql server source with CDC update method

### ISSUE THREAD

**Issue by adithya-k** [airbytehq/airbyte#34906]
### Topic

Sync failure for some tables from sql server source to postgres 

### Relevant information

My source is sql server and destination is postgres and using CDC for update method from source but my airbyte pipeline is failing and has multiple sync issues
Getting error like 
`Caused by: io.debezium.DebeziumException: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.sql.Timestamp (java.lang.Long is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform') `
the source table is fine and checked all the fields. But if I copy the data to another table and sync, the pipeline is running fine, with the error msgs in the log I'm not able to find the issue why its failing and happens for few tables and not all. Is there any known issue in sql server connection/source. This has been a major blocker for us to identify which table is causing the failure and how do we sync these tables to destination

**Comment by adithya-k** [comment]
After a lot of retries with different tables and the changing the columns mapped, I was able to find the issue for this. We have source tables which have default value constraint on some columns (Ex default value of (
'1970-01-01 00:00:00.000') ) because of this constraint airbyte pipeline sync is failing with above error but this is valid constraint in the source table and data is correct those tables which needs to flow during the sync process. What is the fix for this in airbyte

**Comment by evantahler** [comment]
we are about to start a beta program with a new version of the myssql source - are you interested in joining the beta?

cc @rodireich

**Comment by rodireich** [comment]
@adithya-k We'll be happy to let you try with the latest which I think resolved this issue in https://github.com/airbytehq/airbyte/pull/32573 .
Please let me know
