### ISSUE TITLE
Airbyte CDK (test): HttpResponse add headers

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#34910]
### Topic

add headers to HttpResponse

### Relevant information

In [Github](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#using-link-headers), nex_page is obtained from the headers:

airbyte-cdk/python/airbyte_cdk/test/mock_http/response.py

### Suggestion
add headers property to object
```python3

class HttpResponse:
    def __init__(self, body: str, status_code: int = 200, headers: dict = {}):
        self._body = body
        self._status_code = status_code
        self._headers = headers

    @property
    def body(self) -> str:
        return self._body
    @property
    def status_code(self) -> int:
        return self._status_code

    @property
    def headers(self) -> dict:
        return self._headers

```

**Comment by maxi297** [comment]
nit: we would also need to update https://github.com/airbytehq/airbyte/blob/e59b3f90cfcffc9d9b55806d9e2545a7666a3dac/airbyte-cdk/python/airbyte_cdk/test/mock_http/mocker.py#L63
