### ISSUE TITLE
UI Improvements around sync modes

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3494]
## Tell us about the problem you're trying to solve
To be clearer, the UI should show all sync modes but gray out the ones that are not available for selection with a little message/reason as to why.

For example, because the destination (or source) does not handle it.
Another reason for dedupe sync to potentially be grayed out would be if basic normalization is not enabled (see https://github.com/airbytehq/airbyte/issues/3209)

## Describe the solution you’d like
Can we rename the sync modes to label something like "Source: Full refresh | Dest: overwrite" too?

## Additional context
Two slack threads about the UI to better understand what the sync modes will do and why I can or can not select it:

* https://airbytehq.slack.com/archives/C021JANJ6TY/p1621287819288200?thread_ts=1621266047.283700&cid=C021JANJ6TY
* https://airbytehq.slack.com/archives/C01VDDEGL7M/p1621425979265800?thread_ts=1621418151.261400&cid=C01VDDEGL7M

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368195641522) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Design suggestion: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25419%3A23

**Comment by cgardens** [comment]
do this issue at the same time as this one as they are related: https://github.com/airbytehq/airbyte/issues/3499
