### ISSUE TITLE
Connection Settings UX Improvements

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3499]
## Tell us about the problem you're trying to solve
*  A user cannot easily determine where there data is going when they are setting up a connection. (reported by jrhizor on the SM project)
* I want to be able to filter field by those that are and are not selected.
* Free up more space to all for better explanations and tool tips when configuring a source. Right now cursor field, PK are crammed in and are a super tiny font size.

## Describe the solution you’d like
![PXL!UNITO-UNDERSCORE!20210519!UNITO-UNDERSCORE!215306940](https://user-images.githubusercontent.com/9092207/118889821-86314f00-b8b2-11eb-9734-9d6849e73386.jpg)

* Move the search bar out of the header for the streams table. Put it on its own line with additional filters.
* Proposed first set of filters: all, syncing, not syncing. (no preference on whether these are radio buttons or a dropdown)
* The header for the streams table only contains stream-level information, including: source namespace, source stream name, destination namespace, and destination stream name. (no preference on actual copy here, but I think these are the important concepts so that a user knows where there data is going, this should be the source of truth).
* Make stream elements have height of 2 lines (instead of one). The second line is dedicated to actually configuring the sync. Essentially grabbing what's squeezed into one row right now and giving it more space. This gives us more space to grow these configurations without having to keep playing games with spacing. It also allows us to hide cursor field and primary key when it is not relevant.
* destination namespace / stream name should reflect any modifiers. e.g. if a table prefix is set in the ui, then that prefix should appear as part of the stream name below.
* Separate streams and fields as different concepts and don't mix them. The stream table no longer has field-specific columns and the field table no longer has stream-specific columns.

johnlafleur

* you can see my suggestion above. I'm sure we can come up with better, but if you are bandwidth constrained, I can move forward with my napkin sketch.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368130293326) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
I think more than destination namespace + destination stream name users want to know exactly where this data is going in terms of their destination. Unless it's somehow clear in the UI if namespace corresponds to the dataset id in BQ or if it'll be part of the final table name it'll still be very confusing.

**Comment by ChristopheDuong** [comment]
Would it help to show graphically where things map from source to destination too?

For example, dbt generates a docs website with a lineage graph such as this example:

![Screenshot 2021-05-20 at 17 09 53](https://user-images.githubusercontent.com/7718175/119003948-6cfdd080-b98e-11eb-810e-fdbdc7bfb48b.png)

- in green in first "column", those are _airbyte_raw_<tables> 
- next "column" is _scd tables if any streams (2 of them here) were selected with `dedupe history` sync mode
- third "column" is the final tables of top-level streams
- other "columns" are nested substream being exploded in their own table

(sorry the names of the tables are ugly as they come from integration tests)

We could then add a bigger box enclosing the tables to show the schema for example

**Comment by cgardens** [comment]
For now let's go with this mockup. specifically just the one slide that is select in this link: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25464%3A0

changes include:
* fields move into their own sub table
* top-level columns change to only include stream level info
* add destination version of stream names and namespaces
* wrap long lines onto second row

**Comment by davinchia** [comment]
@cgardens I don't see a prefix in the figma mockup. is that going away? or are the mock ups not up to date?
