### ISSUE TITLE
Allow partial log inspection

### ISSUE THREAD

**Issue by rparrapy** [airbytehq/airbyte#3501]
## Tell us about the problem you're trying to solve
* I want to make sure a long sync is running without any issues.
* The current UI renders the complete sync log when trying to inspect it, which for hour-long runs can be slow and can even freeze the frontend.

## Describe the solution you’d like
I would like to be able to inspect just the last N lines of the log, like running the tail command on my machine.

## Additional context
https://airbytehq.slack.com/archives/C01MFR03D5W/p1621461502065400

## Are you willing to submit a PR?
At this point my bandwidth is limited but that might change in a few weeks.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368130261494) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
We are actively trying to move people away from looking at our logs. So we aren't going to work on this for now. Hope you understand!
