### ISSUE TITLE
Dedup sync mode in normalization should exclude cdc deleted row

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3506]
## Tell us about the problem you're trying to solve
When a row for a primary key is deleted and reported by cdc, it should be excluded from the final table that is supposed to be deduplicated properly

We need to add extra logic in the dedup mode to take cdc columns into account

**Comment by cgardens** [comment]
Is there a user ask attached to this? I think supporting PK deletes without a full refresh seems kinda niche. Maybe there's a use case here I'm not thinking of here though.

**Comment by marcosmarxm** [comment]
Close as duplicated of https://github.com/airbytehq/airbyte/issues/4160
