### ISSUE TITLE
last sync column sort has 3 states but the UI graphics only has 2

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#35127]
I think the sorting on the column has 3 states: 1) oldest to newest, 2) newest to oldest, 3) and not sorted (or something?). But when you click on the column header it only has 2 states: 1) arrow up or 2) arrow down. Feels like something here isn't lining up correctly. 

Video to show it.
https://www.loom.com/share/cf559897d50f4c81ba7d567e1e7c2d09?sid=65f4ccd1-3bcb-4caf-b4cd-f6caeb5def22

Workspace from the video: https://cloud.airbyte.com/workspaces/a0cc325a-d358-4df4-bdd4-c09d753b6afb/connections

Low prio, but wanted to make sure to surface it.

**Comment by josephkmh** [comment]
Refining notes:
- Real fix should be that one column is always used for sorting, so that option 3) does not happen. 
- If the column is not currently used for sorting, we could use an up-down-caret instead of just up (like it is now)
