### ISSUE TITLE
CDK: Allow opting-out of raising an exception in `HttpStream` when response status <=400<500

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3514]
## Tell us about the problem you're trying to solve
Today in the HTTP Stream, an error is thrown if the response status code a non-retryable (not 429 or 5XX) status code: https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/http.py#L204

In certain cases like the Asana API, an API might return a 4XX that can be remedied/fixed. For example, the API returns a 412 if the input query parameter `sync` is invalid, and the response will contain a new `sync` token that should be used. In this case, the request should not be considered a failure, and instead should be retried with the new parameter. 

## Describe the solution you’d like
I would like to have customer error handling logic in the HTTP Stream class. 

There's a few options we have here: 

## Option 1: specify which HTTP errors to ignore
In `HTTPStream` have a method: 

```
def error_status_codes_to_ignore() -> List[int]:
  return []
```

The user can override this method. If the response has status code present in this list, don't fail. 

## Option 2: allow specifying custom error handling for certain HTTP status codes
Similar to the above method but instead returns `Mapping[int, Callable[[requests.Response], None]`

## Option 3: don't fail on any HTTP error, let the user decide inside `parse_response`
This is the most flexible option but will require all connector users to inspect the response code. This would be the simplest one to implement in the CDK. 

# Follow-up items: 
- [ ] Create issues to update any connectors which `def _send_request` or other CDK methods

**Comment by keu** [comment]
I vote for option 3, because:
1. make interface complicated and difficult to follow
2. too verbose and don't play well with another error handling (errors inside body and headers)

**Comment by sherifnada** [comment]
@keu sorry, are you saying you vote for option 3 because it makes the iface difficult to follow? I'm not sure I follow

**Comment by keu** [comment]
@sherifnada no I listed other options with their drawbacks, i.e. option 1 and option 2

**Comment by sherifnada** [comment]
I think it will have a Boolean flag "auto_fail_on_errors" or something that lets the dev decide to opt out of this functionality if needed

**Comment by keu** [comment]
we need to see how it will play with backoff logic

**Comment by sherifnada** [comment]
Let's go with option 3 and find a way to handle backoff reasonably

**Comment by antixar** [comment]
Hi @sherifnada  and @keu,  
 AirByte CDK has the pretty decorator `user_defined_backoff_handler`. Perhaps will we upgrade it and will make it as public for developers?
As Is:
```
def user_defined_backoff_handler(max_tries: int, **kwargs):
    ...
```
To Be:
```
def user_defined_backoff_handler(max_tries: int=5, factor: int=5, acceptable_codes=None):
    ...
```
if acceptable_code is None, CDK will use standard logic(with 429 and >= 500). 
And it can be applied for all CDK functions where the 'response' (isinstance(arg, requests.Response) is one of possible function arguments.

```
@user_defined_backoff_handler(max_tries: int=100, factor: int=10, acceptable_codes=[412, 429]):
def parse_response(self, response: requests.Response, **kwargs) -> Iterable[Mapping]:
    ...
```

**Comment by antixar** [comment]
Or another idea: the new class decorator where all backoff magic will be hidden but its settings will be obvious.  
```
def user_defined_backoff_handler(max_tries: int=5, factor: int=5, acceptable_codes=None):
    def decorator(cls):
       pass

@user_defined_backoff_handler(max_tries=100, factor=10, acceptable_codes=[412, 429]):
class NewStream(HttpStream, ABC):
    pass
```
