### ISSUE TITLE
Create continuously running Google ad campaign to seed adwords account with data

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3519]
## Tell us about the problem you're trying to solve
We should create an adwords campaign with a max budget of something like $20/month in order to seed the adwords connector with data as it currently doesn't have data being populated for testing. 

## Describe the solution you’d like

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368195410088) by [Unito](https://www.unito.io)

**Comment by cheyura** [comment]
@sherifnada Configured ad campaign for Airbyte that will cot smth like 3 USD per day. Is it ok?
