### ISSUE TITLE
[destination-snowflake] OOM query optimization recommendations from Snowflake support

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#35191]
### Connector Name

destination-snowflake

### Connector Version

3.5.9

### What step the error happened?

During the sync

### Relevant information

We are experiencing Snowflake task failures when syncing Postgres to Snowflake.  We have worked with Snowflake support and determined that the Snowflake queries being executed are inefficient.  We are having successful syncs, but they are taking a huge amount of time.  It is taking nearly an hour and a half to sync 20,000 records (30MB).  Here are the recommendations from Snowflake support:

1. Rewrite deletes to use an aggregation instead of a window function:
Current query:
```
DELETE FROM "EMR_OLED"."ENCOUNTER" WHERE "_AIRBYTE_RAW_ID" IN ( SELECT "_AIRBYTE_RAW_ID" FROM ( SELECT "_AIRBYTE_RAW_ID", row_number() OVER ( PARTITION BY "ENCOUNTER_ID" ORDER BY "_AIRBYTE_EXTRACTED_AT" DESC ) as row_number FROM "EMR_OLED"."ENCOUNTER" ) WHERE row_number != 1 )
```
New query:
```
DELETE FROM "EMR_OLED"."ENCOUNTER" WHERE "_AIRBYTE_RAW_ID" != ( SELECT "_AIRBYTE_RAW_ID" FROM "EMR_OLED"."ENCOUNTER" ORDER BY "_AIRBYTE_EXTRACTED_AT" DESC LIMIT 1 )
```

2. Reduce MEMORY_SOFT_LIMIT to encourage the query to spill to disk earlier.
3. Reduce query concurrency using MAX_CONCURRENCY_LEVEL.

Complete response from Snowflake support for context:

> I have checked on the failed Transaction queries. 
> 
> We believe that the issue is due to too many jobs(a total of 1596 jobs running during the execution of the queries listed between 15:08 to 15:16 UTC) being scheduled at the same time in the same warehouse AIRBYTE_PROD (X-SMALL) which led to consuming too much memory.
> 
> 
> For eg: These two queries were started 1 second apart and consumed 17GB and 16GB of memory respectively:
> 01b20fce-0404-e8fb-000b-3e0702e11d5e
> 01b20fce-0404-e832-000b-3e0702e1910a
> 
> 
> NEXT ACTION ITEM: 
> 1. Rewrite the query to be more memory efficient. I see it is using a window function where a simple aggregation will do.
> Their current query:
>  
> 
> 
> 
> 
> DELETE FROM "EMR_OLED"."ENCOUNTER" WHERE "_AIRBYTE_RAW_ID" IN ( SELECT "_AIRBYTE_RAW_ID" FROM ( SELECT "_AIRBYTE_RAW_ID", row_number() OVER ( PARTITION BY "ENCOUNTER_ID" ORDER BY "_AIRBYTE_EXTRACTED_AT" DESC ) as row_number FROM "EMR_OLED"."ENCOUNTER" ) WHERE row_number != 1 )
> 
> 
> It looks like the user is simply trying to all rows except the one with the largest value of 
> _AIRBYTE_EXTRACTED_AT
> . May I suggest a rewrite along the lines of:
> 
> 
> 
> 
> DELETE FROM "EMR_OLED"."ENCOUNTER" WHERE "_AIRBYTE_RAW_ID" != ( SELECT "_AIRBYTE_RAW_ID" FROM "EMR_OLED"."ENCOUNTER" ORDER BY "_AIRBYTE_EXTRACTED_AT" DESC LIMIT 1 )
> 
> 
> I am assuming here that 
> "_AIRBYTE_RAW_ID"
>  is unique. User should check this query accomplishes its goals before running it.
> 
> 2..  You can reduce the MEMORY_SOFT_LIMIT to encourage the query to spill to disk earlier and non OOM. This may or may not work depending on what is using the memory.
> 
> 
> 
> 3.  You can reduce the query concurrency to avoid interference between one memory-hungry query and other queries on the system.
> There’s one parameter MAX_CONCURRENCY_LEVEL (Parameters | Snowflake Documentation ) that users can try setting to a smaller number (e.g., 4) and see if this helps mitigate the issue with lower concurrency level. You can try setting it for one of the users and let us know the results. Currently, it is set to 8 for this WH
> 
> ref: https://docs.snowflake.com/en/sql-reference/parameters#max-concurrency-level
> 
> Lowering the concurrency level for a warehouse can limit the number of concurrent queries running in a warehouse. When fewer queries are competing for the warehouse’s resources at a given time, a query can potentially be given more resources, which might result in faster query performance, particularly for a large/complex and multi-statement query.
> 
> 4. Another solution is to use a Bigger Warehouse as we see too many queries running at the same time on this X-Small Warehouse. 
> 
> refer : https://docs.snowflake.com/en/user-guide/performance-query-warehouse  
> https://www.snowflake.com/blog/managing-snowflakes-compute-resources/

### Relevant log output

```
2024-02-12 19:58:57 replication-orchestrator > sync summary: {
  "status" : "completed",
  "recordsSynced" : 19248,
  "bytesSynced" : 31229591,
  "startTime" : 1707762679461,
  "endTime" : 1707767937452,
  "totalStats" : {
    "bytesCommitted" : 31232817,
    "bytesEmitted" : 31232817,
    "destinationStateMessagesEmitted" : 17,
    "destinationWriteEndTime" : 1707767937435,
    "destinationWriteStartTime" : 1707762679468,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 1,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 1500,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 332,
    "recordsEmitted" : 19280,
    "recordsCommitted" : 19280,
    "replicationEndTime" : 1707767937450,
    "replicationStartTime" : 1707762679461,
    "sourceReadEndTime" : 1707767669860,
    "sourceReadStartTime" : 1707762679474,
    "sourceStateMessagesEmitted" : 17
  },
  "streamStats" : [ {
    "streamName" : "immunization",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 165447,
      "bytesEmitted" : 165447,
      "recordsEmitted" : 89,
      "recordsCommitted" : 89
    }
  }, {
    "streamName" : "procedure",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 163357,
      "bytesEmitted" : 163357,
      "recordsEmitted" : 112,
      "recordsCommitted" : 112
    }
  }, {
    "streamName" : "encounter",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 471214,
      "bytesEmitted" : 471214,
      "recordsEmitted" : 502,
      "recordsCommitted" : 502
    }
  }, {
    "streamName" : "process",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 178698,
      "bytesEmitted" : 178698,
      "recordsEmitted" : 29,
      "recordsCommitted" : 29
    }
  }, {
    "streamName" : "patient",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 7388,
      "bytesEmitted" : 7388,
      "recordsEmitted" : 8,
      "recordsCommitted" : 8
    }
  }, {
    "streamName" : "data_mapping",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 3226,
      "bytesEmitted" : 3226,
      "recordsEmitted" : 32,
      "recordsCommitted" : 32
    }
  }, {
    "streamName" : "family_member_history",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 138477,
      "bytesEmitted" : 138477,
      "recordsEmitted" : 120,
      "recordsCommitted" : 120
    }
  }, {
    "streamName" : "conference_order",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 2985,
      "bytesEmitted" : 2985,
      "recordsEmitted" : 4,
      "recordsCommitted" : 4
    }
  }, {
    "streamName" : "allergy_intolerance",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 15077,
      "bytesEmitted" : 15077,
      "recordsEmitted" : 5,
      "recordsCommitted" : 5
    }
  }, {
    "streamName" : "source",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0
    }
  }, {
    "streamName" : "document",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 469041,
      "bytesEmitted" : 469041,
      "recordsEmitted" : 726,
      "recordsCommitted" : 726
    }
  }, {
    "streamName" : "document_reference",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 695750,
      "bytesEmitted" : 695750,
      "recordsEmitted" : 573,
      "recordsCommitted" : 573
    }
  }, {
    "streamName" : "summary",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0
    }
  }, {
    "streamName" : "observation",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 15324720,
      "bytesEmitted" : 15324720,
      "recordsEmitted" : 5102,
      "recordsCommitted" : 5102
    }
  }, {
    "streamName" : "medication_request",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 1094568,
      "bytesEmitted" : 1094568,
      "recordsEmitted" : 670,
      "recordsCommitted" : 670
    }
  }, {
    "streamName" : "condition",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 9200167,
      "bytesEmitted" : 9200167,
      "recordsEmitted" : 4736,
      "recordsCommitted" : 4736
    }
  }, {
    "streamName" : "field_mapping",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 0,
      "bytesEmitted" : 0,
      "recordsEmitted" : 0,
      "recordsCommitted" : 0
    }
  }, {
    "streamName" : "practitioner",
    "streamNamespace" : "oled",
    "stats" : {
      "bytesCommitted" : 3302702,
      "bytesEmitted" : 3302702,
      "recordsEmitted" : 6572,
      "recordsCommitted" : 6572
    }
  } ],
  "performanceMetrics" : {
    "processFromSource" : {
      "elapsedTimeInNanos" : 1437789104,
      "executionCount" : 19352,
      "avgExecTimeInNanos" : 74296.66721785862
    },
    "readFromSource" : {
      "elapsedTimeInNanos" : 4985200683935,
      "executionCount" : 41904,
      "avgExecTimeInNanos" : 1.1896717936080088E8
    },
    "processFromDest" : {
      "elapsedTimeInNanos" : 2306424864,
      "executionCount" : 17,
      "avgExecTimeInNanos" : 1.3567205082352942E8
    },
    "writeToDest" : {
      "elapsedTimeInNanos" : 771513778,
      "executionCount" : 19297,
      "avgExecTimeInNanos" : 39981.021816862725
    },
    "readFromDest" : {
      "elapsedTimeInNanos" : 5251144597316,
      "executionCount" : 723051,
      "avgExecTimeInNanos" : 7262481.61929933
    }
  }
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @joeybenamy thanks for reporting the issue about the connector performance. The destination team already added it to the backlog and will return as soon as possible they can get working on this.

**Comment by joeybenamy** [comment]
> Hello @joeybenamy thanks for reporting the issue about the connector performance. The destination team already added it to the backlog and will return as soon as possible they can get working on this.

Thanks so much @marcosmarxm.  Let me know how else we can help improve Snowflake destination performance.  We are about to push a lot of data through Airbyte to Snowflake.

**Comment by jbfbell** [comment]
Hey @joeybenamy thanks for providing this feedback, however the Snowflake representative over simplified a bit

> It looks like the user is simply trying to [delete] all rows except the one with the largest value of
`_AIRBYTE_EXTRACTED_AT`

What the query is actually doing however is deleting all but the latest record for each `ENCOUNTER_ID` 

consider the following data:

| encounter_id | airbyte_id |
|--------------|-------------|
| 1 | 1 |
| 1 | 2 |
| 2 | 3 |
| 2 | 4 |
| 3 | 5 |

Airbyte's query updates the table as such:

| encounter_id | airbyte_id |
|--------------|-------------|
| 1 | 2 |
| 2 | 4 |
| 3 | 5 |

Where the updated query from snowflake will update the table this way:

| encounter_id | airbyte_id |
|--------------|-------------|
| 3 | 5 |

But the other suggestions from Snowflake support look promising!

**Comment by joeybenamy** [comment]
> Hey @joeybenamy thanks for providing this feedback, however the Snowflake representative over simplified a bit
> 
> > It looks like the user is simply trying to [delete] all rows except the one with the largest value of
> > `_AIRBYTE_EXTRACTED_AT`
> 
> What the query is actually doing however is deleting all but the latest record for each `ENCOUNTER_ID`
> 
> consider the following data:
> 
> encounter_id	airbyte_extracted_at
> 1	1
> 1	2
> 2	3
> 2	4
> 3	5
> Airbyte's query updates the table as such:
> 
> encounter_id	airbyte_extracted_at
> 1	2
> 2	4
> 3	5
> Where the updated query from snowflake will update the table this way:
> 
> encounter_id	airbyte_extracted_at
> 3	5
> But the other suggestions from Snowflake support look promising!

That makes sense.  Glad there is still some value in these suggestions!

**Comment by jbfbell** [comment]
@joeybenamy just to be clear and set the right expectations, the other suggestions such as setting the `MEMORY_SOFT_LIMIT` or `MAX_CONCURRENCY_LEVEL`, changing your warehouse size - are snowflake warehouse management suggestions, this would not be something we would change about the Snowflake Destination connector.

**Comment by joeybenamy** [comment]
> @joeybenamy just to be clear and set the right expectations, the other suggestions such as setting the `MEMORY_SOFT_LIMIT` or `MAX_CONCURRENCY_LEVEL`, changing your warehouse size - are snowflake warehouse management suggestions, this would not be something we would change about the Snowflake Destination connector.

Yes, understood.  Good to point out though!
