### ISSUE TITLE
[destination-postgres] v2.0.0 no normalization, column with "metric" instead

### ISSUE THREAD

**Issue by Blochergroup** [airbytehq/airbyte#35200]
### Connector Name

destination-postgresql

### Connector Version

2.0.0

### What step the error happened?

None

### Relevant information

Using the E2E test it source it works
![image](https://github.com/airbytehq/airbyte/assets/117825209/a57fbbd0-011b-4b6b-841a-9c02e2a99ef5)

But with Amazon Ads as source its just json:
<img width="1049" alt="image" src="https://github.com/airbytehq/airbyte/assets/117825209/6034d575-cce0-4e18-ba3d-03c1f4167048">

It seems like the "metric" column isn't handled properly by the new connector type. 

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @Blochergroup what do you mean the column wasn't handled properly? What data type you expect the `metrics` should be?

**Comment by Blochergroup** [comment]
@marcosmarxm With the v1 connector the transformation resulted in a different table with _metric at the end and all the columns were normalized. So I had a Table with adId, cost....

The cleanest solution would be to just normalize the metric column and add all data included in metric as a column in the same table.

**Comment by marcosmarxm** [comment]
Thanks for explaining. Typing-deduping works only normalizing the first level of the table.
You can read more https://docs.airbyte.com/using-airbyte/core-concepts/typing-deduping how the new method works.
The issue you reported is not an issue is the expected behavior.
