### ISSUE TITLE
make normalization's  hash inclusion in unnested table names optional

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3523]
The release of this change depends on https://github.com/airbytehq/airbyte/issues/3522

Consumers of tables produced by normalization cannot easily use nested tables due to the presence of hashes (used for collision prevention). These hashes are generally unnecessary outside of Postgres/similar dbs with low char limits for table names.

We should make this optional and set this to off by default except for Postgres/similar.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368129700092) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Following [discussions](https://docs.google.com/document/d/15t4CJtEk4eLwauP8YriqqMz27PwepRbTEA2jD0NJq8o/edit?usp=sharing) let's go with:

# Dynamic Hashing

Normalization automatically detects when hashing is needed and only does it for tables that require it.

## Pros
No extra user configuration

## Cons
Not 100% predictable, but should be rare. And we can at least expose it in the UI in the future so it will be super clear what will happen. We will be able to warn users ahead of time and allow them to override table names that will be hashed if it is easier for them...

This change will be breaking for normalization/naming; we are okay with this, but will need to message it.

**Comment by ChristopheDuong** [comment]
@avaidyanatha can we make sure to mention this issue/PR in the next release?

Some nested tables produced by normalization won't be refreshed anymore and new tables will be created instead.
The new tables won't have "hashes" in their names if it's not necessary.
