### ISSUE TITLE
Destination dropdown displays HTML (svg) source instead of something readable

### ISSUE THREAD

**Issue by ericdevries** [airbytehq/airbyte#3528]
## Expected Behavior
Not sure, I expect it to show a postgres icon and a name

## Current Behavior
When selecting a destination for a source, existing destinations appear as a bunch of svg source instead of a nicely displayed list. See screenshot for obvious bug

## Logs
![](https://user-images.githubusercontent.com/817612/119109276-55235c80-ba21-11eb-9d14-cfe66e524ec0.png)

## Steps to Reproduce
1. Create a destination
1. Create a new source
1. Try to select an existing destination

## Severity of the bug for you
Low (because I only have 1 destination atm)

## Airbyte Version
0.23.0-alpha

## Connector Version (if applicable)
Postgresql destination

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368060927336) by [Unito](https://www.unito.io)

**Comment by timroes** [comment]
This issue is no longer present. Closing this issue.
