### ISSUE TITLE
Redact sensitive fields in logs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#353]
## Expected Behavior
Logs should redact sensitive fields e.g: passwords or private keys. 

## Current Behavior
Logs tend to print everything in a provided message. For example: `http://localhost:8001/api/v1/destination_implementations/update` tends to print all of the credentials provided to the endpoint. 

## Steps to Reproduce
1. Create a destination in the UI
1. In the destination view in the UI, update the credentials for the destination
1. Save
1. Look at server logs

**Comment by cgardens** [comment]
@sherifnada is this done and closeable?

**Comment by sherifnada** [comment]
This is for server logs not for showing in the UI so this ticket is not closeable yet.
