### ISSUE TITLE
Postgresql source and destination wrongly sets schema

### ISSUE THREAD

**Issue by ericdevries** [airbytehq/airbyte#3530]
## Expected Behavior
If I configure a postgres destination with a default schema "datalayer", I expect it to use this schema for doing all the work.

## Current Behavior
Instead of using "datalayer" schema for creating the tmp tables, it writes to the "public" schema. This only happens when the source is also postgresql.

## Logs
```
i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):147 - {} - Preparing tmp table in destination started for stream prefixed-accounts. schema: public, tmp table name: _airbyte_1621587897755__airbyte_raw_prefixed_accounts
```

## Steps to Reproduce
1. Set up a source with postgres
1. Set up a destination, also postgres, in my case a different server. 
1. Set the default schema to be anything but public

## Severity of the bug for you
High

## Airbyte Version
0.23.0-alpha

## Connector Version (if applicable)
Source: 0.3.2
Destination: 0.3.4

## Additional context
*Environment, version, integration...*

**Comment by ChristopheDuong** [comment]
This is not an actual "bug", as it is documented to work like this here: https://docs.airbyte.io/understanding-airbyte/namespaces

> If I configure a postgres destination with a default schema "datalayer", I expect it to use this schema for doing all the work.
The "default" in airbyte vocabulary is seen as a fallback default value. If the namespace is already specified, then we use the specified one.

But we definitely need to iterate on the implementation of this feature to give more freedom to users that would want to emulate the behavior you are describing.

This is why we already have another issue that would permit you to address this here: https://github.com/airbytehq/airbyte/issues/3481

I believe this should therefore be a duplicate of your request here, right?

**Comment by ericdevries** [comment]
I understand the issue now, it also replicates schemas. In my opinion it should be completely oblivious to the source schema structure, because why would I want my oracle schema names to dictate the postgres schema names? Luckily this is in the "coming soon" list, and the other ticket does suggest an improvement that would fix this, so this can be closed
