### ISSUE TITLE
[source-facebook-marketing] fields are not valid for fields param after V19.0

### ISSUE THREAD

**Issue by meyerovb** [airbytehq/airbyte#35334]
### Connector Name

source-facebook-marketing

### Connector Version

1.3.0

### What step the error happened?

During the sync

### Relevant information

Vanilla first time sync, got an error

### Relevant log output

```shell
2024-02-15 20:47:46 platform > failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "(#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0",
  "externalMessage" : "Error: 100, (#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0.",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 85,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/base_insight_streams.py\", line 288, in stream_slices\n    for job in manager.completed_jobs():\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/async_job_manager.py\", line 74, in completed_jobs\n    self._start_jobs()\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/async_job_manager.py\", line 57, in _start_jobs\n    job.start()\n  File \"/airbyte/integration_code/source_facebook_marketing/streams/async_job.py\", line 268, in start\n    self._job = self._edge_object.get_insights(params=self._params, is_async=True)\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/adobjects/adaccount.py\", line 2871, in get_insights\n    return self.get_insights_async(fields, params, batch, success, failure, pending)\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/adobjects/adaccount.py\", line 2990, in get_insights_async\n    return request.execute()\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/api.py\", line 682, in execute\n    response = self._api.call(\n  File \"/usr/local/lib/python3.9/site-packages/backoff/_sync.py\", line 105, in retry\n    ret = target(*args, **kwargs)\n  File \"/airbyte/integration_code/source_facebook_marketing/api.py\", line 167, in call\n    response = super().call(method, path, params, headers, files, url_override, api_version)\n  File \"/usr/local/lib/python3.9/site-packages/facebook_business/api.py\", line 350, in call\n    raise fb_response.error()\nfacebook_business.exceptions.FacebookRequestError: \n\n  Message: Call was not successful\n  Method:  POST\n  Path:    https://graph.facebook.com/v17.0/act_235133657164090/insights\n  Params:  {'level': 'ad', 'action_breakdowns': '[\"action_type\"]', 'action_report_time': 'mixed', 'breakdowns': '[\"device_platform\"]', 'fields': '[\"account_currency\",\"account_id\",\"account_name\",\"action_values\",\"actions\",\"ad_click_actions\",\"ad_id\",\"ad_impression_actions\",\"ad_name\",\"adset_id\",\"adset_name\",\"age_targeting\",\"attribution_setting\",\"auction_bid\",\"auction_competitiveness\",\"auction_max_competitor_bid\",\"buying_type\",\"campaign_id\",\"campaign_name\",\"canvas_avg_view_percent\",\"canvas_avg_view_time\",\"catalog_segment_actions\",\"catalog_segment_value\",\"catalog_segment_value_mobile_purchase_roas\",\"catalog_segment_value_omni_purchase_roas\",\"catalog_segment_value_website_purchase_roas\",\"clicks\",\"conversion_rate_ranking\",\"conversion_values\",\"conversions\",\"converted_product_quantity\",\"converted_product_value\",\"cost_per_15_sec_video_view\",\"cost_per_2_sec_continuous_video_view\",\"cost_per_action_type\",\"cost_per_ad_click\",\"cost_per_conversion\",\"cost_per_estimated_ad_recallers\",\"cost_per_inline_link_click\",\"cost_per_inline_post_engagement\",\"cost_per_outbound_click\",\"cost_per_thruplay\",\"cost_per_unique_action_type\",\"cost_per_unique_click\",\"cost_per_unique_inline_link_click\",\"cost_per_unique_outbound_click\",\"cpc\",\"cpm\",\"cpp\",\"created_time\",\"ctr\",\"date_start\",\"date_stop\",\"engagement_rate_ranking\",\"estimated_ad_recall_rate\",\"estimated_ad_recall_rate_lower_bound\",\"estimated_ad_recall_rate_upper_bound\",\"estimated_ad_recallers\",\"estimated_ad_recallers_lower_bound\",\"estimated_ad_recallers_upper_bound\",\"frequency\",\"full_view_impressions\",\"full_view_reach\",\"gender_targeting\",\"impressions\",\"inline_link_click_ctr\",\"inline_link_clicks\",\"inline_post_engagement\",\"instant_experience_clicks_to_open\",\"instant_experience_clicks_to_start\",\"instant_experience_outbound_clicks\",\"labels\",\"location\",\"mobile_app_purchase_roas\",\"objective\",\"optimization_goal\",\"outbound_clicks\",\"outbound_clicks_ctr\",\"purchase_roas\",\"qualifying_question_qualify_answer_rate\",\"quality_ranking\",\"reach\",\"social_spend\",\"spend\",\"unique_actions\",\"unique_clicks\",\"unique_ctr\",\"unique_inline_link_click_ctr\",\"unique_inline_link_clicks\",\"unique_link_clicks_ctr\",\"unique_outbound_clicks\",\"unique_outbound_clicks_ctr\",\"updated_time\",\"video_15_sec_watched_actions\",\"video_30_sec_watched_actions\",\"video_avg_time_watched_actions\",\"video_continuous_2_sec_watched_actions\",\"video_p100_watched_actions\",\"video_p25_watched_actions\",\"video_p50_watched_actions\",\"video_p75_watched_actions\",\"video_p95_watched_actions\",\"video_play_actions\",\"video_play_curve_actions\",\"video_play_retention_0_to_15s_actions\",\"video_play_retention_20_to_60s_actions\",\"video_play_retention_graph_actions\",\"video_time_watched_actions\",\"website_ctr\",\"website_purchase_roas\",\"wish_bid\"]', 'time_increment': 1, 'action_attribution_windows': '[\"1d_click\",\"7d_click\",\"28d_click\",\"1d_view\",\"7d_view\",\"28d_view\"]', 'time_range': '{\"since\":\"2021-01-16\",\"until\":\"2021-01-16\"}'}\n\n  Status:  400\n  Response:\n    {\n      \"error\": {\n        \"message\": \"(#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0\",\n        \"type\": \"OAuthException\",\n        \"code\": 100,\n        \"fbtrace_id\": \"AQN_WcZYWz9CiMcJ270Aszx\"\n      }\n    }\n\n",
  "timestamp" : 1708029455237
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 85,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:366)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:235)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1708029455363
} ]
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello! Thank you for reporting this issue. It seems the Airbyte connector is currently using Facebook Business version 17, which might be causing the problem. We've added it to our connector backlog for further investigation.

**Comment by meyerovb** [comment]
except you can't default a new app to a previous api version, so i'll need to do something like mod the source code to add the api version to the url, which isnt configurable in the ui for the source.  i have no idea how to go about that
![image](https://github.com/airbytehq/airbyte/assets/362582/50e03a6a-6977-49bb-b396-3147fcddc8ab)

**Comment by marcosmarxm** [comment]
It looks only changing the version in the code won't fix the issue as the API return an error about fields not being allowed anymore. @meyerovb shared this to the team, hope to get an update soon.

**Comment by meyerovb** [comment]
See “Making Versioned Requests” on [this page](https://developers.facebook.com/docs/marketing-api/versions/). If you don’t put the version into the api url, it defaults to whatever you have set up in your settings. And for a new app u can’t set the settings back to an old version. So I’m stuck, but just modding the api url will be enough to unstick me (until v17 is fully removed that is, then everyone’s screwed).

**Comment by marcosmarxm** [comment]
@meyerovb team is investigating and will return during the week.

**Comment by ponlv** [comment]
Hello @marcosmarxm Is there any upgrade with facebook version issue?

**Comment by danilo-nzyte** [comment]
@marcosmarxm any update on this? This is a big issue for us at the moment trying to migrate to using Airbyte for Meta data.

**Comment by remipham** [comment]
Same issue here, tried to untick the fields in the replication tab but it still tries to fetch the unsupported fields.

**Comment by mehdigati** [comment]
Running into the same issue, it's breaking our reporting. Hope to get an update soon.

**Comment by brunopini** [comment]
+1 here

**Comment by pragmaticapt** [comment]
+1 here

**Comment by pragmaticapt** [comment]
> There’s a quick patch fix for this. You don’t need to update the connector to v19, you just have to put v17 into the api url you are using. That way it’ll stop erroring out for anyone who’s created an app recently on v19 until you get around to updating the connector.

Can you explain better?

Where did you change the URL ?

After the change, you commit the change to the docker image, right?

**Comment by meyerovb** [comment]
> > There’s a quick patch fix for this. You don’t need to update the connector to v19, you just have to put v17 into the api url you are using. That way it’ll stop erroring out for anyone who’s created an app recently on v19 until you get around to updating the connector.
> 
> Can you explain better?
> 
> Where did you change the URL ?
> 
> After the change, you commit the change to the docker image, right?

See my [comment above](https://github.com/airbytehq/airbyte/issues/35334#issuecomment-1948943242). I barely got this thing running in the first place, I really don’t wanna go screwing with the docker image or source code, I just want it fixed so I can click upgrade connector in the ui.

**Comment by danilo-nzyte** [comment]
> There’s a quick patch fix for this. You don’t need to update the connector to v19, you just have to put v17 into the api url you are using. That way it’ll stop erroring out for anyone who’s created an app recently on v19 until you get around to updating the connector.

@meyerovb could you explain specifically the steps to update the v17 API into the URL?

Are you talking about forking the repo, updating the source code, and using that for your deployment temporarily?

I haven't had to make any source code changes yet so any advice would be useful.

**Comment by artem1205** [comment]
@meyerovb, Airbyte has Facebook app with v17, and these fields ([listed in error message](https://github.com/airbytehq/airbyte/issues/35334#issue-2137438403)) are predefined for insights report.
To bypass this limitation I'd recommend you to create custom insight report and select there only available/required fields.
![image](https://github.com/airbytehq/airbyte/assets/36314070/35b88d37-551a-4f20-aa62-7bdf6f546965)

**Comment by mehdigati** [comment]
Hey @artem1205, thanks for your suggestion, just tested with the same fields on your screenshot and still have the same issue : `airbyte_cdk.utils.traced_exception.AirbyteTracedException: (#100) age_targeting, gender_targeting, labels, location, estimated_ad_recall_rate_lower_bound, estimated_ad_recall_rate_upper_bound, estimated_ad_recallers_lower_bound, estimated_ad_recallers_upper_bound are not valid for fields param after V19.0
`

Am I missing something ? Thanks

**Comment by artem1205** [comment]
@mehdigati ,

I selected these fields just as an example.
Did you left only custom_insight stream enabled in your connection?

**Comment by meyerovb** [comment]
@artem1205 can u just stick v17 into the dang url and release it tomorrow?  it'll fix the problem for now and keep us from all having to make forks and custom builds https://developers.facebook.com/docs/marketing-api/versions#calling_versioned_apis

**Comment by artem1205** [comment]
it is already pinned to v17.0

see [pyproject.toml](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/pyproject.toml#L21):
```
facebook-business = "==17.0.0"
```

and test to verify: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/unit_tests/integration/request_builder.py#L73

**Comment by meyerovb** [comment]
I apologize @artem1205 seems that creating a new app automatically upgrades all calls using that app's token to the "Upgrade API Version" setting of the app, and you can't set that to a deprecated version, so yeah everyone is stuck until the upgrade is released.  I had hoped the versioned call would override it, but it doesnt, dang.  I will now go the guaranteed fruitless route of asking facebook to downgrade that setting in my app lol, and let the client know their integration will have to wait.

**Comment by artem1205** [comment]
@meyerovb , have you tried to create a custom insight report without erroneous fields? 

https://github.com/airbytehq/airbyte/issues/35334#issuecomment-1969089566

**Comment by meyerovb** [comment]
@artem1205 
a> how exactly do I do that, where in the airbyte ui or is that in the facebook ui?
b> which of these do i turn off, everything that has "insight" in the name?
![image](https://github.com/airbytehq/airbyte/assets/362582/be5d2809-dcba-47e4-9dee-d8340dc1df9d)

**Comment by artem1205** [comment]
@meyerovb ,

> how exactly do I do that, where in the airbyte ui or is that in the facebook ui?

From airbyte UI, step 8 in Connector setup, please refert to  https://docs.airbyte.com/integrations/sources/facebook-marketing

> which of these do i turn off, everything that has "insight" in the name?

yes
