### ISSUE TITLE
New destination: AssertDestination for test

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3534]
## Tell us about the problem you're trying to solve
Following up on https://github.com/airbytehq/airbyte/pull/3473 we could make an AssertDestination that we can configure with a resource file of json records messages to expect

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368060767955) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
we have this with the e2e test destination. or can be easily added to it.
