### ISSUE TITLE
[destination-postgres] Dv2 does not use CASCADE when deleting tables

### ISSUE THREAD

**Issue by corbin-Tprime** [airbytehq/airbyte#35386]
### Connector Name

destination-postgres

### Connector Version

2.0.0

### What step the error happened?

During the sync

### Relevant information

Hello, it appears that there are some cascades missing from drop queries when running resets with postgres dest v 2.0.0

### Relevant log output

```shell
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: cannot drop table schema_name.table_name because other objects depend on it Detail: view schema_name depends on table schema_name.table_name Hint: Use DROP ... CASCADE to drop the dependent objects too.

```
```


### Contribute

- [ ] Yes, I want to contribute

**Comment by OhadSrur** [comment]
Just wondering how everyone else is managing this issue at the moment.
Did you write your own drop cascade scripts that execute before the sync? 
In our case, we have rolled back the connector to 0.6.3.

**Comment by BertrandMiannay** [comment]
We had this error due to view based on those tables.
We changed the view to materialized one, but other errors occurs so we did the same : downgrade to 0.6.3

**Comment by alepietrobon** [comment]
same issue here

**Comment by IlyaDropit** [comment]
@BertrandMiannay @OhadSrur How did downgrade PostgreSQL dest connector to 0.6.3? Don't see such option in Airbyte UI? Is it a flag in config file?

**Comment by OhadSrur** [comment]
@IlyaDropit in the Change To column, modify the version number manually and hit the Change button.

**Comment by edgao** [comment]
hey folks - couple questions:
* what are the "dependent objects" that are blocking the drop? (views, table with a foreign key reference, etc?)
* being extra cautious: adding a `cascade` will drop those objects. I want to be _very_ certain that that's actually desired behavior. (which it might be! `cascade` just makes me nervous 😅 so want to doublecheck with y'all - you're the experts in your own usecases! )
    * This would mean that after running certain sync operations, you will need to manually recreate those objects.
    * If those objects are tables, their data may be permanently lost (modulo your DB having backups or some other way to rebuild them).
    * (if you're managing these objects via dbt/etc, "manual" here means "when your dbt run completes")

**Comment by alepietrobon** [comment]
Strong agreement with @IlyaDropit here.  We use the same workflow.

I understand that drop cascade sounds scary, but it is definitely the intended behavior if we are triggering a full refresh from the connector.  Failing the sync is even worse. :)

**Comment by OhadSrur** [comment]
Another strong agreement here for both comments above! We also use dbt to build the views/tables immediately after Airbyte extraction is complete and has dropped the source tables.

We have carefully designed our process based on the assumption that Airbyte extraction drops and cascades all tables. This is how V1 used to work. Changing this behaviour on V2 without appropriate communication and without offering the previous behaviour seems strange to me.

What seems even stranger to me is that the V2 connector can't also drop **tables** without any foreign keys dependencies, the error message reads "table already exists". So changing my Views to Tables was not a workable workaround.

I think it would be appropriate in this case to reintroduce this option by adding a flag to the UI that allows you to select "Drop & Cascade",

**Comment by edgao** [comment]
Perfect, thanks for the input everyone! This should be a pretty straightforward option to add, stay tuned :)

And apologies for the disruption here - legacy normalization did a lot of things in hard to discover ways, and we missed this during the postgres dv2 beta period (probably because we encouraged testers to set up parallel workloads instead of plugging into their production flows). Future projects in this space should go a lot more smoothly.

**Comment by BertrandMiannay** [comment]
Shouldn't be possible, instead to have a drop option to avoid the drop ?
Based on what I understood of the codebase, the drop is made to replace previous table by the new one.

**Comment by edgao** [comment]
@BertrandMiannay that would require some more significant changes to the connector - can you submit a new issue for it? I'm interested to hear more about your usecase, just want to keep that discussion separate from the cascade stuff in this thread

**Comment by edgao** [comment]
Forgot to comment here - try out destination-postgres v2.0.9! There's a new config option to opt into drop with `cascade`. Figured I'd leave the default behavior as non-cascade for extra safety :P
