### ISSUE TITLE
Sync mode for CDC (Add New Data, Update Existing Data & Delete Existing Data)

### ISSUE THREAD

**Issue by mohamed-mubeen** [airbytehq/airbyte#3538]
Hi Team,

I am new to Airbyte, correct me if anything is misunderstood by me. 

I see four sync modes are supported in Airbyte (https://docs.airbyte.io/understanding-airbyte/connections).

As you know, normally in an ELT/ETL tool, below features are mostly used.

1. Full Data Initial Sync _(available & successful)_
1. CDC Sync _(unable to achieve)_
Reason: We are not able to achieve this via Full Refresh Append / Incremental Append / Incremental Deduped History.
1. Reset Data at the Destination _(available & successful)_

**Expectation:** 
CDC without any duplicates - Incremental Sync (when a new table/row/column is added)
CDC without any duplicates - Incremental Sync (when an exiting field value is changed)
CDC without any duplicates - Incremental Sync (when a exiting table/row/column is deleted)

This CDC sync mode is very important, as it saves computing costs when writing to target destination.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368070889710) by [Unito](https://www.unito.io)

**Comment by mohamed-mubeen** [comment]
Just now found an information on CDC support with initial support for Postgres via https://docs.airbyte.io/understanding-airbyte/cdc

Data Stores that I look forward to with CDC sync are,
a) PostgreSQL
b) Elasticsearch
c) MySQL

Thank you!

**Comment by sherifnada** [comment]
@mohamed-mubeen Postgres & mysql CDC are released, but I don't think Elastic Search natively supports it. Can you link to any docs for getting started on elastic CDC?

**Comment by mohamed-mubeen** [comment]
Thanks much! @sherifnada, 
As I am new to use ES data store, got to know recently that it doesn't have native support for CDC, as you mentioned.
Reference: https://discuss.elastic.co/t/how-to-maintain-the-cdc-change-data-capture-in-elasticsearch/161650
