### ISSUE TITLE
Exchange API connector not working 

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3541]
## Expected Behavior
Connect to API and get data

## Current Behavior
![image](https://user-images.githubusercontent.com/5154322/119205795-aeb27800-ba6f-11eb-9344-725dff8a5af3.png)

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._

## Steps to Reproduce
1. 
1. 
1. 

## Severity of the bug for you
Very low / Low / **Medium** / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
_Environment, version, integration..._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368060577387) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@sherifnada I added this to the next connector sprint because is the most common getting start connector used.

**Comment by Zirochkaa** [comment]
When visiting [ratesapi.io](https://ratesapi.io) I see this:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/19872253/119332483-51960c80-bc91-11eb-9be9-da872f66b05a.png">

When you follow [http://ratesapi.io](http://ratesapi.io) link (see screenshot):

<img width="774" alt="image" src="https://user-images.githubusercontent.com/19872253/119332601-7db18d80-bc91-11eb-9614-f9e752b0919e.png">

you are being redirected to [exchangeratesapi.io](https://exchangeratesapi.io/pricing/). So I think we need to look at exchangeratesapi.io docs.

**Comment by marcosmarxm** [comment]
@Zirochkaa looks the open endpoint was removed and now you need an APIKEY to use this API. Not completely sure about this too.
