### ISSUE TITLE
Add link to docs/how to guide when setting new source/destination

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3543]
## Tell us about the problem you're trying to solve
I think that when setting a new source Airbyte should display a link to the documentation/how to guide to that source, this can be very helpful to users.
Use case: new user setting a source postgres and need to choose between normal or CDC. Docs must explain difference between etc and how to check database is enabled to transfer using CDC...
![image](https://user-images.githubusercontent.com/5154322/119206752-72cce200-ba72-11eb-961f-f0690b834f89.png)

## Describe the solution you’d like
Return the link from the API request and display it on the web UI

## Describe the alternative you’ve considered or used
Enter Airbyte website / go to connector page / read docs 

## Are you willing to submit a PR?
No

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368070902395) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
duplicate https://github.com/airbytehq/airbyte/issues/2042
