### ISSUE TITLE
Icon problem on Admin page for Microsoft Team

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3544]
## Expected Behavior
show icon beside the connector title

## Current Behavior
Google Chrome
![image](https://user-images.githubusercontent.com/5154322/119207055-4feefd80-ba73-11eb-99f6-c52e65034237.png)

Firefox
![image](https://user-images.githubusercontent.com/5154322/119207107-917fa880-ba73-11eb-882f-156993958dc8.png)

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._

## Steps to Reproduce
1. 
1. 
1. 

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
_Environment, version, integration..._

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368070886097) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
Look this is a problem with the Microsoft Team svg file
view-source:https://raw.githubusercontent.com/airbytehq/airbyte/3fbb38273aca15848dbb4d1c9827354ad2f1c29a/airbyte-config/init/src/main/resources/icons/microsoft-teams.svg

![image](https://user-images.githubusercontent.com/5154322/119209974-3dc78c00-ba80-11eb-989e-4c070b737bab.png)

The icon was collect from Wikipedia [here](https://pt.wikipedia.org/wiki/Microsoft_Teams#/media/Ficheiro:Microsoft_Office_Teams_(2018%E2%80%93present).svg)
Maybe we need to find from another source.

**Comment by malikdiarra** [comment]
This appears to be fixed now
