### ISSUE TITLE
Use High-Priority just for UI-triggered Operations

### ISSUE THREAD

**Issue by tryangul** [airbytehq/airbyte#35476]
Background

All CHECK, DISCOVER, SPEC now run on the quick jobs pool not just the those triggered from the UI. This leads to extra load on the quick-jobs pool potentially slowing down UI triggered jobs.

This ticket may be broken down if we elect to do the work.

DoD:
Tag workloads with priority or queue name or some other identify via the API and persist this state to the database
Conditionally launch only workloads tagged as high-priority on the high priority (quick jobs) pools
Pass this information from the UI-triggered endpoints through the activities.

**Comment by davinchia** [comment]
Product implications: https://airbytehq-team.slack.com/archives/C03A8CSANPQ/p1709229559654789?thread_ts=1708012147.412519&cid=C03A8CSANPQ
