### ISSUE TITLE
Posthog connector fails with 403

### ISSUE THREAD

**Issue by ajsharp** [airbytehq/airbyte#35532]
### Connector Name

source-posthog

### Connector Version

1.0.0

### What step the error happened?

Configuring a new connector

### Relevant information

I configured an all access personal api key, but it looks like this connector is trying to query an endpoint that doesn't exist: `https://app.posthog.com/api/projects/projects`.

The [posthog projects endpoint](https://posthog.com/docs/api/projects#get-api-organizations-organization_id-projects) requires an organization_id -- so that needs to be added to the required config for this connector, and the endpoint configuration for this connector needs to be updated.

### Relevant log output

```shell
'Unable to connect to stream projects - Request to https://app.posthog.com/api/projects?limit=100 failed with status code 403 and error message This action does not support Personal API Key access'
```

### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Hey @ajsharp! Looks like the error message from the endpoint was `This action does not support Personal API Key access` — and you're saying you're using the personal API key to authenticate. 

On https://posthog.com/docs/api, I see they're saying: 

> Private GET, POST, PATCH, DELETE endpoints used for creating, updating, or deleting nearly all other non-event data in PostHog. They give the same access as if you were logged into your PostHog instance, but require authentication with your personal API key.

And the guide just below shows how to setup a personal API key. I get how that's confusing, and don't have a solution for you. 

Can you check with Posthog and see if you need to authenticate differently to use the projects endpoint?

Once you get this to work, would you be open to sharing the resulting connector with us? I'm pretty sure a lot of folks would benefit from a Posthog connector.

**Comment by domzae** [comment]
I came across this and think it was actually resolved by modifying the Scopes of the personal API key

**Comment by ajsharp** [comment]
I tried almost every variation of scopes -- I believe the issue is this connector is using outdated api endpoints. I believe the path needs to be modified according to their api docs, which means this connector needs to accept additional configuration -- an org id and project id. Unfortunately the org id is a bit of a slog to get -- you have to hit an endpoint to get it.

**Comment by natikgadzhi** [comment]
Thank you folks!

I was anxious that I haven’t looked at that yet, happy to see this cleaned
up. ❤️
