### ISSUE TITLE
Containerize connector code generator into docker image

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3558]
## Tell us about the problem you're trying to solve
currently users need to run `npm` from `airbyte-integrations/connector-templates` to bootstrap a new connector module. This is not a good UX as they need to install `node` and run `npm install` to run the generator. We should containerize the code generator for maximum portability. 

## Describe the solution you’d like
1. Package the generator module `airbyte-integrations/connector-templates/generator` in a Docker image. This image does not need to be released to Dockerhub and can just be built locally. 
1. The docker image should be invoked with `docker build . -t airbyte/connector-bootstrap && docker run -it airbyte/connector-bootstrap`. Since the generator outputs a fully formed connector module, we will also need to mount the relevant part of the filesystem via `-v $(pwd):/output`. We will also need to modify the generator to accept a variable indicating where in the filesystem it should output data to (right now it outputs to `../../connectors/` by default). 
1. Update all documentation which references the generator (grep for `npm run generate`) to use the new format.
1. Wrap the command in a bash script in the `airbyte-integrations/connector-templates/generator/generate.sh` directory to make it easy to consume. 

## Describe the alternative you’ve considered or used
Continue to require users to install `npm`. It's not the end of the world, but is not a great experience since almost none of our connectors are in JS.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200370480079868) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
if we do that, we probably want to wrap that in a shell script

**Comment by sherifnada** [comment]
good idea. Added to description.
