### ISSUE TITLE
[source-microsoft-sharepoint] Add grant-type `client_credentials` For OAuth2 Flow

### ISSUE THREAD

**Issue by babrar** [airbytehq/airbyte#35588]
### Connector Name

source-microsoft-sharepoint

### Connector Version

0.1.0

### What step the error happened?

Configuring a new connector

### Relevant information

Currently, the connector only supports the Refresh Token grant-type for OAuth authentication. However, it lacks support for the commonly used Client Credentials grant-type.

Conveniently, the `Office365-REST-Python-Client` library that the connector is based on, already provides client_credentials as a grant-type option for OAuth. For example:
```python
from office365.graph_client import GraphClient

# Authenticate using client credentials
client = GraphClient.with_client_secret(tenant_id, client_id, client_secret)
``` 
Adding this as a feature to the connector will greatly improve it's usuability.

Relevant contributor: @lazebnyi @tolik0

### Contribute

- [ ] Yes, I want to contribute

**Comment by babrar** [comment]
More specifically, `refresh_token` is a **required** attribute for the connector in the Airbyte UI. Therefore, the else condition is never triggered.

https://github.com/airbytehq/airbyte/blob/5d99614fc0f99d3755b39f9d008874210417b0a8/airbyte-integrations/connectors/source-microsoft-sharepoint/source_microsoft_sharepoint/stream_reader.py#L50-L53
--
Not all OAuth flows require refresh tokens, as outlined in the [MSAL docs](https://learn.microsoft.com/en-us/entra/msal/msal-authentication-flows#tokens):
![image](https://github.com/airbytehq/airbyte/assets/34361338/069f189f-7396-4e42-ba58-a63e25105573)

**Comment by marcosmarxm** [comment]
Hello @babrar Microsoft Sharepoint is a vital part of our community, but it's not currently on our roadmap for updates. This means it might take some time before it gets prioritized by the Airbyte Team. However, we encourage community involvement to improve it, and your contributions are welcome! If you're interested, please reach out to me on Slack so we can discuss how you can help. Thanks for your support!
