### ISSUE TITLE
[postgres] First sync attempt fails every time 

### ISSUE THREAD

**Issue by attaxia** [airbytehq/airbyte#35582]
### Connector Name

destination-postgres

### Connector Version

2.00

### What step the error happened?

During the sync

### Relevant information

Of multiple connections the first sync attempt always fails, with an error like in the log output below. The second attempt is succesful.

I'm not sure how to resolve the issue, also because I never touched the file mentioned in the error, it's generated by Airbyte.

### Relevant log output

```shell
Failure reason: Something went wrong during replication
io.airbyte.workers.exception.WorkerException: /tmp/workspace/16372/0

2024-02-23 08:48:01 normalization > [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.airbyte_utils.generated.airbyte_views
2024-02-23 08:48:48 normalization > Internal event buffer full. Earliest events will be dropped (FIFO).
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@attaxia the log shared doesn't corresponds with latest version of Postgres destination where normalization was deprecated. Please open a new issue and please upload the complete log file.
