### ISSUE TITLE
[source-MSSQL] varchar fields having length > 10 storing numericals writing empty strings

### ISSUE THREAD

**Issue by pooja-pai-1** [airbytehq/airbyte#35607]
### Connector Name

source-mssql

### Connector Version

3.6.0

### What step the error happened?

During the sync

### Relevant information

We have an MSSQL table where column is defined as Invoice varchar(21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
After a certain huge value(digit_ length > 7) for a column, all the subsequent values are coming as empty strings in the Bigquery table

### Contribute

- [ ] Yes, I want to contribute

**Comment by pooja-pai-1** [comment]
In MSSQL, in the CDC source log tables, the column value is coming as null

**Comment by evantahler** [comment]
Can you provide a create-table DDL statement and some values that reproduce the problem for us?

**Comment by rodireich** [comment]
Also if you can try with the latest version 4.0.8.
We made a major overhaul of source-mssql in version 4

**Comment by pooja-pai-1** [comment]
Hey!
The issue was related to the CDC enabling on the source table. So, once the CDC was disabled and re-enabled on the table, the issue got resolved.

Regards,
Pooja Pai
