### ISSUE TITLE
`run-ab-platform.sh` doesn't work on Windows?

### ISSUE THREAD

**Issue by F041** [airbytehq/airbyte#35617]
### Relevant information

Process from Win 10:

```
C:\Users\Gabriele>cd airbyte
C:\Users\Gabriele\airbyte>bash

/mnt/c/Users/Gabriele/airbyte$./run-ab-platform.sh

./run-ab-platform.sh: line 2: $'\r': command not found
```

How do I solve this?

**Comment by natikgadzhi** [comment]
@F041, Hey Gabriele, I personally don't know from the top of my head if we support running on Windows. Looks like at least the `run-ab-platform.sh` script doesn't like Windows, but you can run Airbyte on Docker Compose directly from the repo. 

```bash
cd airbyte
docker compose up
```

I'll try the script on Windows and report back to see if we can clean this up.

**Comment by natikgadzhi** [comment]
Alright, it looks like our `run-ab-platform.sh` has UNIX line endings: https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile

Should be an easy fix.

**Comment by natikgadzhi** [comment]
Okay, I figured it out. `run-ab-platform.sh` has `\r` line endings. Your particular Windows terminal [doesn't like it](https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types). You can use something like `dos2unix` to change the line ending sequences in the script, or just run Airbyte with `docker compose up`. 

Let me know if that didn't work for you.

**Comment by matttsai-orx** [comment]
> Okay, I figured it out. `run-ab-platform.sh` has `\r` line endings. Your particular Windows terminal [doesn't like it](https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types). You can use something like `dos2unix` to change the line ending sequences in the script, or just run Airbyte with `docker compose up`.
> 
> Let me know if that didn't work for you.

When I use `docker compose up` the container `airbyte-temporal` will give me error: `Unable to create dynamic config client. Error: unable to validate dynamic config: dynamic config: config/dynamicconfig/development.yaml: stat config/dynamicconfig/development.yaml: no such file or directory`.

Here is my solution:
Manually download the [development.yaml](https://github.com/airbytehq/airbyte-platform/blob/main/temporal/dynamicconfig/development.yaml) file from the Airbyte GitHub repository.

And put it under `airbyte\temporal\dynamicconfig`

Re-run the `docker compose up`

**Comment by natikgadzhi** [comment]
We've since switched to `abctl`, but I'm not sure `abctl` would work on Windows at all. /cc @bgroff

**Comment by matttsai-orx** [comment]
> We've since switched to `abctl`, but I'm not sure `abctl` would work on Windows at all. /cc @bgroff

`abctl` works on my windows and mac, but when I try to `Add a new Docker Connector` to the airbyte UI with `abctl` version, it gives me error `errors.http.default`
