### ISSUE TITLE
[source-mongodb] timeout creating new source

### ISSUE THREAD

**Issue by sjtutim** [airbytehq/airbyte#35619]
### Connector Name

MongoDb

### Connector Version

1.2.12

### What step the error happened?

Configuring a new connector

### Relevant information

failed,after save the connecter
<img width="915" alt="SCR-20240225-tecv" src="https://github.com/airbytehq/airbyte/assets/7855411/64a7d334-fb9d-470e-ad86-2fd4440701f6">

### Relevant log output

```shell
Configuration check failed
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers= [address=10.63.2.99:27018, type=UNKNOWN, state=CONNECTING, exception= {com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ss.SSLHandshakeException: Remote host terminated the handshake), caused by {java.io.EOFException: SSL peer shut down incorrectly}}]
```

### Contribute

- [X] Yes, I want to contribute

**Comment by xiaohansong** [comment]
Airbyte runs on docker env - are we sure the network setup was correct? Has mongodb accessible from airbyte docker containers?

**Comment by rodireich** [comment]
Connectivity issue.
@sjtutim we're you able to connect?
It looks like you're using a self managed mongodb.
Can you make sure SSL is turned on. 
[[instructions]](https://www.mongodb.com/docs/manual/tutorial/configure-ssl/)

**Comment by rodireich** [comment]
Connectivity issue.
@sjtutim we're you able to connect?
It looks like you're using a self managed mongodb.
Can you make sure SSL is turned on. 
[[instructions]](https://www.mongodb.com/docs/manual/tutorial/configure-ssl/)

Please reopen if this is still and issue.
