### ISSUE TITLE
Container network not available on connector workers

### ISSUE THREAD

**Issue by gokulchittaranjan** [airbytehq/airbyte#3564]
## Expected Behavior
The worker that runs the connector (source or destination) should have access to all the network locations that are also accessible to the scheduler. Alternatively, it should be possible to specify the networks that the worker container should be a part of when the `docker run` command is executed.

## Current Behavior
Unable to access other containers. 
Resorting to work around of exposing the services on other containers to ports on the localhost (host) and using them.

## Logs
```curl
{
  "status_code": 200
}
```

```curl
{
  "status_code": 200
}
```

The above results are obtained by running the curl command on the `airbyte-scheduler`

Now, 

```
2021-05-21 11:58:05 ERROR (/tmp/workspace/3/0) LineGobbler(voidCall):69 - urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=8063): Max retries exceeded with url: /update/data (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9585a99210>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

Similar error is obtained upon using `host='myservice'`.

## Steps to Reproduce
Create a connector that calls the service running in another docker container.

## Severity of the bug for you
High, since it does not allow us to integrate connectors with other running docker containers.

## Airbyte Version
0.23.0-alpha

## Connector Version (if applicable)
N/A

## Additional context
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
docker-compose version 1.29.1, build c34c88b2

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200372671309542) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
closed due to inactivity
