### ISSUE TITLE
[DB connectors] : Set debezium property errors.max.retries > 0 for DBZ connectors

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#35649]
### Relevant information

In https://github.com/airbytehq/airbyte/pull/26473/commits/b6005bc397409c315b765bf6f560c8b5110f06d5, we set the `errors.max.retires` param to 0 from 10. 

We're seeing a connection consistently fail because debezium keeps failing to connect to the source DB : https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1708626360559169. 

Explore increasing this parameters and understand why it was reset in the first place

**Comment by akashkulk** [comment]
Closing in favor of https://github.com/airbytehq/airbyte-internal-issues/issues/1783

**Comment by rose-m** [comment]
What was it closed in favor of? The linked issue is unfortunately internal. I also have the same problem right now and would like to use this as a band-aid until I can get to the root cause.
