### ISSUE TITLE
[source-getlago] Add `fees` support

### ISSUE THREAD

**Issue by jdenquin** [airbytehq/airbyte#35659]
### Connector Name

source-getlago

### Connector Version

0.3.0

### What step the error happened?

None

### Relevant information

- Add `fees` support for Lago https://doc.getlago.com/api-reference/fees/list-fees

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@jdenquin thansk for the PR at the moment there is a large community contribution backlog. I hope to get to your contribution soon.
