### ISSUE TITLE
[GA4][PSQL] identifier lengths cause errors

### ISSUE THREAD

**Issue by Gogoro** [airbytehq/airbyte#35654]
### Connector Name

source-ga4

### Connector Version

2.4.1

### What step the error happened?

During the sync

### Relevant information

When syncing data from Google Analytics 4 [GA4] to Postgres I get a lot of errors. After looking more into it I see that it's because Postgres has 63 character limit on max_identifier_length.

[https://www.postgresql.org/docs/current/runtime-config-preset.html](See the PSQL docs on the topic.)

As I understand it, changing Postgres to support longer identifiers requires compiling it with a different flag. This requires a lot of manual labour and is not very ideal.

Switching to a different database is an option, but our company has a goal of only use on-prem solutions for data management. A quick search shows that it's common to have ~63 character limit for OSS databases.

### Relevant log output

```shell
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
  Detail: Key (relname, relnamespace)=(user_acquisition_first_user_s_property_id_date_firstUserSo_idx1, 21743) already exists.
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @Gogoro it looks is similar to https://github.com/airbytehq/airbyte/issues/36440. Today the resolution is to turn off the field causing the issue. Closing to keep only one issue about the topic.
