### ISSUE TITLE
source-mongodb-v2 Connection string parsed incorrectly

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#35666]
### Connector Name

source-mongodb-v2

### Connector Version

1.2.13

### What step the error happened?

During the sync

### Relevant information

The connection string is appended with `?retryWrites=true` automatically in code.
This is creating odd connection string containing two `?` and can lead to problems such as when user configure the following connection string
```
mongodb+srv://******.mongodb.net/?readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS
```
Because of the hard-coded suffix the driver attempt to find a tag with a value of `ANALYTICS?retryWrites=false`

We should let the user paste a connection string.

### Contribute

- [ ] Yes, I want to contribute

**Comment by akashkulk** [comment]
Context : https://airbytehq-team.slack.com/archives/C043JHEEYKG/p1708992277052569

@rodireich says this will be a community PR
