### ISSUE TITLE
Unable to find Octavia CLI after v0.50.50

### ISSUE THREAD

**Issue by ngonimurove-sovtech** [airbytehq/airbyte#35694]
### Topic

missing octavia cli

### Relevant information

I'm unable to find the Octavia CLI folder in the Airbyte repo after v0.50.50. I can't find any information on why it's now unavailable or about alternatives. I want to use Octavia CLI for version control.

Could you please assist?

**Comment by marcosmarxm** [comment]
It was moved to https://github.com/marcosmarxm/octavia-cli/tree/main as managed community project.
