### ISSUE TITLE
Is it possible to programmatically add a custom connector?

### ISSUE THREAD

**Issue by ngonimurove-sovtech** [airbytehq/airbyte#35741]
### Topic

Add custom connector with API

### Relevant information

I am trying to add a custom connector to Airbyte without login into the UI. Ideally, I would like to deploy all connectors in ci. At the moment, I'm using Terraform to setup pre-existing connectors but it doesn't seem to cover custom connectors that have not already been configured into Airbyte. 

Thanks

**Comment by nataliekwong** [comment]
Hey there - we recently delivered the ability to create custom connectors via the API and terraform provider: https://github.com/airbytehq/airbyte/issues/32744

I'll close this for now, but if you have additional questions on how to do so, feel free to comment on the other issue!
