### ISSUE TITLE
Shopify Connector - pull additional endpoints

### ISSUE THREAD

**Issue by jacqueskpoty** [airbytehq/airbyte#3576]
My team at work will like to use Airbyte to pull data from shopify. We are pretty content with the hardwork that is already done. However we will like to add more API pulls such as: 

* Pages
* DiscountCodes

We are ready to contribute this for the community.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200376863279664) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@jacqueskpoty thanks for the issue! we'd definitely love to support this. What's your timeline? We are going to migrate shopify to an Airbyte-native connector like described in #3581. I estimate this might take a couple of weeks. Would you be open to waiting for that change and contributing to it or is this an urgent need for your team?

**Comment by jacqueskpoty** [comment]
@sherifnada thanks for the response. I will wait since singer will be deprecated. Also I will like to add the fact that in the current shopify connector, the only credentials accepted is connection through a private app(With the use of a private app API password). We will like to have the option to also connect as public app(using an API key and API secret key).
Will this be done in the new Shopify connector? If not i will like to contribute that as well because my company needs it.
