### ISSUE TITLE
Test different Python versions in Airbyte CDK

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3577]
## Tell us about the problem you're trying to solve
In the Airbyte CDK CI we only test the package on Python 3.7: https://github.com/airbytehq/airbyte/blob/master/.github/workflows/publish-cdk-command.yml#L44

we should change the CI such that it tests the package on all Python versions supported in [setup.py](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/setup.py#L56). 

## Describe the solution you’d like
Whenever the `/publish-cdk` workflow is triggered, it should first test the connector on all python versions supported before publishing it to Pypi.

To do this, we should find a way to run the workflow coded in `.github/workflows/publish-cdk.yaml` using all the versions of python we claim to support. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200376873960124) by [Unito](https://www.unito.io)

**Comment by keu** [comment]
To test different envs normally used [tox](https://tox.readthedocs.io/en/latest/)
