### ISSUE TITLE
[Roadmap] Enable Field/Column Selection through the API

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#35798]
As requested [here](https://github.com/airbytehq/airbyte/issues/36491), enable column or field selection to be available or configurable through the application / UI. This is not currently available through the API.

Definition of done: 

- Ability to view the catalog (field names and types) for all discovered streams
- Ability to enable or disable fields within each stream and save configuration

This will be available for all Airbyte products.

**Comment by AlexDouglasUK** [comment]
Any update on this? We would love this option

**Comment by nataliekwong** [comment]
Hey @AlexDouglasUK , thanks for your comment! We're currently planning for the next quarter. This has been raised as a priority to our Engineering, but not yet committed as we've been focused on making our syncs more reliable the first half of this year. If this does get committed, we'll add it here: https://go.airbyte.com/roadmap.

**Comment by nataliekwong** [comment]
New target release date of July 2024.

**Comment by sowla** [comment]
Thank you for the functionality and keeping us updated @nataliekwong! Would it be possible to share if adding this functionality to the terraform provider (https://github.com/airbytehq/terraform-provider-airbyte/issues/69) is also planned..?

**Comment by nataliekwong** [comment]
We have not yet planned on when it will be added to the terraform provider. While this issue is closed, I will update here when it has been added.

**Comment by pankaj-lmg** [comment]
Seems like it is added to the terraform provider, but not working. Ref: https://registry.terraform.io/providers/airbytehq/airbyte/latest/docs/data-sources/connection#selected_fields

**Comment by pankaj-lmg** [comment]
Seems like fieldSelectionEnabled is not exposed via terraform-provider, and hence it is always going as false. Due to which below happens in platform:
![image](https://github.com/airbytehq/airbyte/assets/153048240/fa6f179f-c7d6-4321-867b-a873551fc208)

@nataliekwong possible to get it fixed?

**Comment by nataliekwong** [comment]
Hi there, we have not yet planned when we will make this available in the Terraform Provider. I don't have an ETA at this time, but you can upvote or comment on this issue.

**Comment by Iyanumanuel** [comment]
Okay, thank you @nataliekwong  for the updates. Please let us know when it is available.

**Comment by dantonbertuol** [comment]
Hi @nataliekwong, i need an example using the selectedFields property. It's not in the documentation yet.

**Comment by kev-datams** [comment]
@dantonbertuol will you contribute to propose a PR ? 🙏
