### ISSUE TITLE
Slash command to build a PR from a fork.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3580]
## Tell us about the problem you're trying to solve
Today in order to build a contributor's PR, we have to create a mirror branch on origin to run the build. This is an annoying waste of time. This is because Github does not build PRs from forks to avoid running random code.

We should develop a slash command that runs the forked code for us. Because this is run after a review, the risk of running malicious code decreases and should be good enough for us.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200376836493822) by [Unito](https://www.unito.io)

**Comment by Phlair** [comment]
@davinchia let me know if https://github.com/airbytehq/airbyte/pull/5400 solves / doesn't solve / could solve with enhancements

**Comment by davinchia** [comment]
Thanks for tagging me @Phlair I left comments on the PR!

**Comment by davinchia** [comment]
No longer relevant.
