### ISSUE TITLE
[destination-snowflake] Set temporary tables to transient

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#35814]
### Connector Name

destination-snowflake

### Connector Version

3.5.14

### What step the error happened?

During the sync

### Relevant information

We are working with our Snowflake account team to optimize our Snowflake usage.  We have identified that Airbyte's Snowflake destination connector is not creating temporary tables as transient and therefore we are paying storage costs for those tables over the length of our retention period for our account.  Snowflake recommends that all temporary tables be created as transient so that the data is not retained after it is deleted from Snowflake.

Reference: https://docs.snowflake.com/en/user-guide/tables-temp-transient

### Contribute

- [ ] Yes, I want to contribute

**Comment by wojo** [comment]
Very important to keep costs down in Snowflake, especially the failsafe costs for this data.

**Comment by marcosmarxm** [comment]
@airbytehq/destinations can this issue be discussed in the sprint?

**Comment by evantahler** [comment]
In the current implementation, we do want these tables to persist across attempts - e.g. we rename them in some cases to the final tables (full refresh syncs).  We won't be working on this in the near future.
