### ISSUE TITLE
Migrate away from Singer-based connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3582]
## Tell us about the problem you're trying to solve
Airbyte started off as a Singer-based tool. We've since migrated to an Airbyte protocol that's compatible with Singer. As a result, we've built a number of connectors based on Singer taps. This presents a few points of friction: 

1. We need to fork the singer tap into a separate repo which presents all sorts of headaches:
  1. Need to grant access permissions separately
  1. We need to use git-based pip installs like [this one](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-appstore-singer/setup.py#L41)
  1. The iteration process is more friction-ful since you need to create a change in one repo, push it, then use branch-based pip installs like in #2 (e.g: `pip install 
  1. We need to tag commits which is not part of the standard workflow for connectors in github.com/airbytehq/airbyte
1. To onboard someone into the connectors codebase they need to know both the Singer protocol and ecosystem as well as the Airbyte tooling
1. All these painpoints combined make it harder to come in as a community contributor to contribute to a Singer-based connector
1. Singer taps vary in quality and support levels. Many of them receive no support from stitch. 
1. It's harder to use Airbyte native auto generators for generating unit tests 
1. Singer tap code is not uniform due to lack of abstractions/frameworks provided by stitch. This makes it more difficult to break into singer code. Airbyte-CDK based connectors should be much faster to understand for someone familiar with the patterns. 

## Describe the solution you’d like
I would like to migrate all of our Singer connectors to be Airbyte-native ones so we avoid the issues above.

Here are all the Singer-based connectors we currently offer: 

* Appsflyer
* Appstore
* ~Braintree~
* ~Github~
* ~Gitlab~
* ~Google Adwords~
* ~Google Analytics~
* ~Google Search Console~
* ~Intercom~
* ~Marketo~
* ~Mixpanel~
* Quickbooks
* ~Salesforce~
* ~Shopify~
* ~Slack~
* ~Twilio~
* ~Zendesk Suppot~
* Zoom

We should create tickets for these and one by one start migrating away from Singer

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200376917968613) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@sherifnada wdyt creating specific issues New Native Source: Marketo for example? 
There are new information the community brings and could be nice add into the issue. This way the contributor who create the new version have knowledge about some actual limitation.

**Comment by sherifnada** [comment]
@marcosmarxm SGTM
