### ISSUE TITLE
[helm] v0.54.88 all connectors are failing due to WorkerException

### ISSUE THREAD

**Issue by sc-yan** [airbytehq/airbyte#35870]
### Helm Chart Version

0.54.88

### What step the error happened?

Other

### Revelant information

all connectors are having this problem
`message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Running the launcher replication-orchestrator failed', type='java.lang.RuntimeException', nonRetryable=false`

### Relevant log output

```shell
message='io.temporal.serviceclient.CheckedExceptionWrapper: io.airbyte.workers.exception.WorkerException: Running the launcher replication-orchestrator failed', type='java.lang.RuntimeException', nonRetryable=false
```

**Comment by marcosmarxm** [comment]
Hello @sc-yan there are some breaking changes in latest Helm Chart version, please follow intructions here: https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm#migrate-from-old-chart-to-airbyte-v0520-and-latest-chart-version

**Comment by sc-yan** [comment]
thank you for the info! I will close  this issue then. will re-open it if there is any problem coming up

**Comment by sc-yan** [comment]
I followed the migration guide, but it doesn't work. although I specify to use external database in value.ymal, the helm chart will create a postgres pod and the boot-loader will try to connect it and then failed. 
but the old version works.

**Comment by marcosmarxm** [comment]
@sc-yan can you try latest version of Helm Chart and open a new issue if it persists?
