### ISSUE TITLE
[connector-builder] Datetime format cannot match the value with nanoseconds in connector builder

### ISSUE THREAD

**Issue by lamphuc** [airbytehq/airbyte#35912]
### Topic

Connector builder datetime issue with nanoseconds

### Relevant information

The connector builder is a perfect solution (thank you for the initiative) that covers 99% of our use cases.

However, when configuring the `Incremental Sync` for this particular API, I am struggling to match the datetime with this value `2024-03-07T00:00:02.331918064Z` as shown in the screenshot. The closest format that I can come up with is `%Y-%m-%dT%H:%M:%S.%fZ`.

<img width="1242" alt="Screenshot 2024-03-08 at 2 30 09 PM" src="https://github.com/airbytehq/airbyte/assets/6128352/ef3f226c-2956-403f-a47d-5d79e0c7173a">

The problem here is that our returned value has 9 digits after the decimal while the `%f` can only match up to 6 digits.

Can you please let me know how I can workaround this issue since it's more intuitive for us to use the connector builder rather than writing the code from the scratch.

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @lamphuc. @girarda would be possible to take a look here?

**Comment by girarda** [comment]
@lamphuc thanks for reporting this issue!

The easiest workaround would be to use a transformation to add a new field "timestamp_ms" which would be derived from "timestamp", but remove some precision so it can be parsed with %f. You can use this field as the cursor.

**Comment by lamphuc** [comment]
Thank you @girarda for the suggestion. Your solution works perfectly for us.

Keep up the good work :)
