### ISSUE TITLE
[source-gitHub] Internal Server Error

### ISSUE THREAD

**Issue by mavis-martins** [airbytehq/airbyte#35931]
### Connector Name

GitHub

### Connector Version

1.6.4

### What step the error happened?

Other

### Relevant information

Hello, i'm trying to connect my github with Airbyte, but at network window its showed the currently message:
Internal Server Error: Cannot invoke \"io.airbyte.api.model.generated.AirbyteCatalog.getStreams()\" because \"discovered\" is null"

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This is more related to the platform issue. What version of the platform are you using?

**Comment by mavis-martins** [comment]
> This is more related to the platform issue. What version of the platform are you using?

I'm using 0.40.9 airbyte's version

**Comment by marcosmarxm** [comment]
Please upgrade to latest version as this issue was fixed in latest versions. If doesn't solve the problem please open a new issue.
