### ISSUE TITLE
[destination-s3] connector is generating csv file with airbyte metadata columns enclosed in double quotes

### ISSUE THREAD

**Issue by maham151288** [airbytehq/airbyte#35957]
### Connector Name

destination S3

### Connector Version

0.5.9

### What step the error happened?

During the sync

### Relevant information

When data is synced S3 destination connector is adding airbyte metadata column names and values enclosed in double quotes. Is there a way to get rid of them? e.g.
"_airbyte_ab_id","_airbyte_emitted_at","_airbyte_data"
"465e901d-739a-4568-a5af-0567496034e8",1709812731552,"{""id"":""1"",""first_name"":""Michael"",""last_name"":""Perez"",""email"":""mperez0@chronoengine.com""}"

![snapshot-csv](https://github.com/airbytehq/airbyte/assets/49512284/74699c66-1a56-401f-b6e3-8521d4407e62)

### Contribute

- [ ] Yes, I want to contribute

**Comment by edgao** [comment]
this is unfortunately how CSV string-escapes work (https://datatracker.ietf.org/doc/html/rfc4180)

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes

> If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote

so if the original value is `{"foo": "bar"}`, then we'll generate an entry `"{""foo"": ""bar""}"`.

similarly

> Each field may or may not be enclosed in double quotes

and destination-s3 just defaults to quoting everything. There's no option to turn it off.
