### ISSUE TITLE
Improve Get Started Documentation

### ISSUE THREAD

**Issue by ghalaax** [airbytehq/airbyte#360]
## Tell us about the problem you're trying to solve
I am trying to install the airbyte application, on a Mac Os (catalina). 
I have no postgresql database available, and I would like to use the local CSV integration, to understand how the application is working.

## Describe the solution you’d like
* Recommend to install the latest version of Docker (mine was out of date and docker-compose wasn't working).
* I would like to see the docker commands to install a container with postgresql, and a link to a postgresql data visualization software.

## Describe the alternative you’ve considered or used
Not installing the software.

**Comment by ChristopheDuong** [comment]
Hi thanks for your feedbacks!

> I would like to see the docker commands to install a container with postgresql

In the "Getting started Tutorial", there is this section on how to bring a postgres instance up on your local machine: https://docs.airbyte.io/tutorials/getting-started#in-the-case-you-dont-have-a-readily-available-database-to-sync

And more specifically, how to start the container:
```docker run --rm --name airbyte-destination -e POSTGRES_PASSWORD=password -p 3000:5432 -d postgres```

Which would download a postgres docker image and start one (named "airbyte-destination") listening on your local machine listening to port 3000. (similarly there is the same command for sources too)

Have you been able to run these? 

Could you let us know if those instructions are not sufficient to guide you with a local install of postgres?

Maybe it would be less confusing if the source and the destination docker commands were separate?

> and a link to a postgresql data visualization software.

At the end, we recommended "visualizing" in a raw format the content produced by the sync:
```docker exec airbyte-destination psql -U postgres -c "SELECT * FROM public.users;"```

So you are suggesting, it would be helpful if we added some links to something like: https://eggerapps.at/postico/ and how to connect to such local postgres instance?

Thanks!

**Comment by cgardens** [comment]
It looks like we had added these instructions. Then we changed the getting started page to use a different example that doesn't require postgres. Think we can close this.
