### ISSUE TITLE
Choose Cloud Provider for Airbyte Cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3604]
## Tell us about the problem you're trying to solve
As we start moving forward with Airbyte Cloud we should choose which cloud provider we want to run it on.

Doc comparing AWS and GCP: https://docs.google.com/document/d/1lRx7nMx-LsrfHqVL1ZBuuuOa7vGOKIgT7xs6Eh_B9Xs/edit#heading=h.3b7ev6n8oh81

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200382746813589) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
GCP.

**Comment by michel-tricot** [comment]
easy!
