### ISSUE TITLE
Custom schema loader

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#36060]
## What
Developers should be able to define a custom schema loader for connectors that have a dynamic schema

## How
1. Add a CustomSchemaLoader type to the schema.
2. Allow the DeclarativeStream's schema_loader to be a CustomSchemaLoader
3. Update the component factory so it knows to call create_custom_component if the model is a CustomSchemaLoader

**Comment by girarda** [comment]
PR is ready for review https://github.com/airbytehq/airbyte/pull/36040/

**Comment by natikgadzhi** [comment]
For my education: so `CustomSchemaLoader` be a type of custom component, right?
