### ISSUE TITLE
Add total count of connectors to connector dashboard

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3608]
## Tell us about the problem you're trying to solve
We'd like to have a very clear indication of how many connectors we have shipping with Airbyte out of the box. 

The easiest way to do this is to query `source_definitions.yaml` and `destination_definitions.yaml` and count the number of entries in them (or count the number of files in the corresponding JSON file directories).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200382956041760) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
done in data studio

**Comment by marcosmarxm** [comment]
you are awesome
