### ISSUE TITLE
Relook closing OkHttpConnectionPool in Fabric8 Client.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3611]
## Tell us about the problem you're trying to solve
The pool is not closing properly today despite calling the various close functions. The pod remains alive for another 5 mins, which is the default time for reaping idle connections.

We are currently forcing the process to exit via System.exit(0).

## Describe the solution you’d like
* The easiest solution is to make the Fabric8 client's idle connection configurable, see https://github.com/fabric8io/kubernetes-client/issues/3170
* We can also try to understand why the OkHttpPool is not killing itself.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200383152009800) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
as of https://github.com/fabric8io/kubernetes-client/releases/tag/v5.5.0 this is unblocked
