### ISSUE TITLE
Document how to get access to AWS account + dev/staging/prod environments

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3620]
## Tell us about the documentation you'd like us to add or update
Giving someone access to environments in AWS is wonky because there's this whole OranizationAccountRole thing going on. We should document this somewhere so we don't have to tie ourselves into knots remembering how it works every time someone new joins the team. 

## Are there any related areas of documentation that currently exist? Could you point to them?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200383899062926) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
documented in new hire onboarding doc
