### ISSUE TITLE
Pulling worker lasts a significant amount of time

### ISSUE THREAD

**Issue by wkargul** [airbytehq/airbyte#36265]
### Topic

Pulling worker lasts a significant amount of time

### Relevant information

When initiating Airbyte deployment with the `./run-ab-platform.sh` script, the process of retrieving the worker image is notably time-consuming. This duration is not attributed to the speed or quality of my internet connection.

**Comment by marcosmarxm** [comment]
The image size remains the same size as always. The image size is quite big but its a project design, maybe there are some improvement in the future to reduce the image size.
<img width="1315" alt="image" src="https://github.com/airbytehq/airbyte/assets/5154322/f3e31000-0d84-456b-bacd-fc3f670ec472">

I'm closing the issue as it isn't a bug or impacting the deployment of new instances.
