### ISSUE TITLE
[destination-cdk] Unable to build new java destination connector with gradle

### ISSUE THREAD

**Issue by venkateshkelevo** [airbytehq/airbyte#36269]
### Topic

buildConnectorImage fails after hanging for 10 mins

### Relevant information

**Error Log:**
> Task :airbyte-integrations:connectors:destination-foresight:buildConnectorImage
root: Setting working directory to /home/venkateshk/airbyte
pipelines: airbyte-ci is up to date. Installed version: 4.5.4. Latest version: 4.5.4
pipelines: Called with dagger run: False
pipelines.cli.dagger_run: Running command: ['/home/venkateshk/bin/dagger', 'run', '/home/venkateshk/tmp_venv/airbyte_venv/bin/airbyte-ci', 'connectors', '--name=destination-foresight', '--disable-report-auto-open', 'build', '--use-host-gradle-dist-tar']
1: connect
1: > in init
1: starting engine 
1: starting engine [605.5s]NG [10m 25s]
1: connect ERROR: new client: context deadline exceeded
new client: context deadline exceeded

> Task :airbyte-integrations:connectors:destination-foresight:buildConnectorImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':airbyte-integrations:connectors:destination-foresight:buildConnectorImage'.
> Process 'command '/home/venkateshk/airbyte/airbyte-integrations/connectors/build/.venv/bin/python'' finished with non-zero exit value 1

**Steps to reproduce**

git clone https://github.com/airbytehq/airbyte.git
cd airbyte-integrations/connector-templates/generator
./generate.sh
cd ~/airbyte
./gradlew :airbyte-integrations:connectors:destination-foresight:build

**Environment:**
OS: RHEL8
Python version: 3.10.0
Java Version: 1.21.0

![image](https://github.com/airbytehq/airbyte/assets/80874219/4c559166-b802-4324-8a2a-1e35019c4f17)

**Comment by marcosmarxm** [comment]
You must use `airbyte-ci` to build and test connectors.
