### ISSUE TITLE
Outreach.io as  source of data

### ISSUE THREAD

**Issue by sylg** [airbytehq/airbyte#3627]
## Tell us about the new integration you’d like to have
Would love to be able to ingest outreach.io data  ([API doc](https://api.outreach.io/api/v2/docs))into our Snowflake db so we can join outbound campaign data with product usage in our analysis and modeling.

This is something that Stitch supports but not Fivetran.

## Describe the context around this new integration
* Sales teams wants data from outreach about which prospects is getting targeted by the BDR teams and wants to know which campaign they are receiving and finally, when was the last time this contact was contacted.

This will be on a fast sync time. 5-10min.
Would need to support all of the endponts in Outreach API ([docs](https://api.outreach.io/api/v2/docs))

## Describe the alternative you are considering or using
Will have to use Stitch as it's the only ETL provider that support it right now

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387048480264) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@sylg on it! we'll do some research and get back to you about prioritization

**Comment by po3na4skld** [comment]
## Integration Vetting

**Webhook-based?**

No

**Available authentication modes**

OAuth 2.0

**Connecting to the data source**



REST API

**Creating an account**









**How to populate the account with data?**

Can it be done entirely through the API?

Yes

Will it require some work through the UI? If so, what is required?

No

Will it require performing some paid action like running an Ad campaign?

No

Do you need any actions from Airbyte to populate the account with data?

No

**Available streams for sync**
 
[API reference](https://api.outreach.io/api/v2/docs#api-reference)

Audit
Account
Call Disposition
Call Purpose
Call
Compliance Request
CustomDuty
Content Category
Content Category Membership
Content Category Ownership
Duty
Email Address
Event
Favorite
Mail Alias
Mailbox
Mailing
Opportunity
Opportunity Prospect Role
Opportunity Stage
Persona
Phone Number
Profile
Prospect
Recipient
Role
Ruleset
Sequence State
Sequence Step
Sequence Template
Sequence
Snippet
Stage
Task Priority
Task
Team
Template
User
Webhook
Messenger Conversation
Messenger Message

**Do any streams support incremental sync?**

most of all streams support incremental on createdAt field
[Pagination description](https://api.outreach.io/api/v2/docs#pagination)

**Preparation scope & blockers**



None

**Other information/blockers**

Wait for the DEMO request accepted to retrieve API access.

 

Outreach API applications use the standard OAuth 2.0 authentication flow. Conceptually, this means that any application request will be using two distinct sets of credentials: The API key and secret that identify the application, and the username and password (or SSO access token) that identify the user. An application should never require that users enter an API key or secret of their own.

The Outreach API is rate-limited on a per-user basis, with a fixed limit of 10,000 requests per one-hour period. All responses include three rate-limiting headers: the X-RateLimit-Limit header indicates the maximum number of requests permitted per time period; the X-RateLimit-Remaining header indicates how many remaining requests are permitted within the current time period; and the X-RateLimit-Reset header (alias as the Retry-After header) indicates when the rate limit counter will reset. If the rate limit is exceeded, requests will receive a 429 HTTP response with a descriptive JSON error message.

**Comment by sherifnada** [comment]
comment from a community member: `This actually isn't in the documentation, but the base url gives you the custom fields mapping.`

**Comment by sherifnada** [comment]
We've received access to a sandbox account. See "Outreach.io setup instructions" in Lastpass for API access instructions and the normal account for accessing the sandbox account.

**Comment by danjsiegel1** [comment]
Feature request: trunc and load a list of all IDs/entity type returned in the latest get request into a table:

- account
- call
- mailing
- opportunity
- prospect
- sequence
- sequenceState
- task

The reason for this is that Outreach hard deletes certain items, and a list of all the current can be helpful to figure out which items have been deleted.

**Comment by sylg** [comment]
Any updates on this? I'm doing more things with the Outreach data and the Stitch connector don't support / track delete records which makes my life super complicated right now

**Comment by sherifnada** [comment]
@sylg would the delete tracking happen through webhooks?

**Comment by danjsiegel1** [comment]
@sherifnada the best way to do this is via platform events: https://api.outreach.io/api/v2/docs#respond-to-platform-events

Fivetran just released their connector as well: https://fivetran.com/docs/applications/outreach

**Comment by sherifnada** [comment]
@sylg @danjsiegel1 Got it! It pains me to say that Airbyte doesn't support webhooks at the moment (should be coming in Q4/Q1) so once this connector is released, it will not support the events endpoints you are looking for. Would you still be interested in the connector in this case?

**Comment by danjsiegel1** [comment]
I would still be interested in the connector. There are other ways to handle this as well. Outreach performs hard deletes of the data. I handle by using an update statement where I add a soft delete flag for anything not in the latest get request. Trunc and full-load would be an alternative strategy as well. 

A little bit more context about Outreach and how the platform works... Outreach has the sequences which you follow to basically outreach to entities. When something starts a sequence, they create tasks for the entire process, ie if you have 10 steps in your sequence, 10 tasks are created. If you get in contact with someone on step 1, steps 2-10 are hard deleted.
