### ISSUE TITLE
[Roadmap] Ensure data uptime when re-syncing data

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#36295]
We'll be working on improving the existing "Reset" feature. The feature will be renamed to "Refresh" and will ensure you have continued access to your data while we load in all historical data from the source. 

This will be available on both the stream and connection level and be available for all Airbyte products.

**Comment by nataliekwong** [comment]
This is now available for BigQuery as of [v0.63.1](https://github.com/airbytehq/airbyte/releases).

More Airbyte Connector destinations will add support for this feature over the coming weeks.

**Comment by nataliekwong** [comment]
This is now available for Snowflake (connector version 3.11.0). You must upgrade to platform 0.63.7 before upgrading to this connector version.

**Comment by nataliekwong** [comment]
This is now available for Redshift (connector version 3.3.0). You must upgrade to platform 0.63.7 before upgrading to this connector version.

**Comment by sowla** [comment]
Hi, just to double check, did the minimum platform version requirement also change to 0.63.7 for the BigQuery connector ([3 days ago](https://github.com/airbytehq/airbyte/commit/25d0030481267d8f0093df8ad78d7b9fbbab0d14#diff-71f64097f537f4492650bf539bdc98817ebf73178d7b7054a08b339abdd952f9)) as well?

**Comment by nataliekwong** [comment]
Yes, the minimum platform requirement for BigQuery is 0.63.7 to take advantage of the Refreshes feature. It is also noted in the changelog for v2.7.0 of BigQuery. https://docs.airbyte.com/integrations/destinations/bigquery (Expand the changelog).

**Comment by davinchia** [comment]
This is now available for Snowflake, Redshift and Postgres. Please see our [docs](https://docs.airbyte.com/operator-guides/refreshes) and [blogpost](https://airbyte.com/blog/introducing-refreshes-reimport-historical-data-with-zero-downtime) for more information.
