### ISSUE TITLE
Write a Document for Databricks Requirements

### ISSUE THREAD

**Issue by jbfbell** [airbytehq/airbyte#36291]
Need input from:
- Community
- Sales
- Databricks

We should find a design partner

**Comment by Sreesruth** [comment]
hi, @jbfbell @mid @zzztimbo @dtt101 @visnup , i would like to contribute to this, thankyou

**Comment by jbfbell** [comment]
Hey @Sreesruth I created [this discussion](https://github.com/airbytehq/airbyte/discussions/36394) please feel free to add your feedback there!

**Comment by jbfbell** [comment]
Closing now that Discussion is opened

**Comment by Sreesruth** [comment]
> Closing now that Discussion is opened

Got it.
