### ISSUE TITLE
Error during self installaiton  on MAC system

### ISSUE THREAD

**Issue by shyamshyre** [airbytehq/airbyte#36343]
### Platform Version

0.44.1

### What step the error happened?

On deploy

### Revelant information

on MAC curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.se/docs/sslcerts.html  curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above.

**Comment by marcosmarxm** [comment]
Please use at least 5 latest minor version of the platform to report new issues.

**Comment by shyamshyre** [comment]
Hi @marcosmarxm 
I'm not sure which version i m using as it's not yet deployed. But i've taken latest code from git so it should be the latest version.
Interestingly i landed into another issues while running 
sh ./run-ab-platform.sh
it shows as below



empty compose file
(base) shyam@MMXTWYP7W6 airbyte % sh ./run-ab-platform.sh
-e 
-e  █████╗ ██╗██████╗ ██████╗ ██╗   ██╗████████╗███████╗
-e ██╔══██╗██║██╔══██╗██╔══██╗╚██╗ ██╔╝╚══██╔══╝██╔════╝
-e ███████║██║██████╔╝██████╔╝ ╚████╔╝    ██║   █████╗  
-e ██╔══██║██║██╔══██╗██╔══██╗  ╚██╔╝     ██║   ██╔══╝  
-e ██║  ██║██║██║  ██║██████╔╝   ██║      ██║   ███████╗
-e ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝    ╚═╝      ╚═╝   ╚══════╝
-e                                             Move Data
-e 
-e found docker-compose.yaml locally!
-e found docker-compose.debug.yaml locally!
-e found .env locally!
-e found .env.dev locally!
-e found flags.yml locally!
-e found temporal/dynamicconfig/development.yaml locally!
-e Loading Shell Variables from .env...
-e Loading Shell Variables from .env.dev...

-e Starting Docker Compose
empty compose file

**Comment by marcosmarxm** [comment]
Please run `sh run-ab-platform.sh -r` to delete existing files and download them again. From logs it didn't download new version of files.
