### ISSUE TITLE
[destination-typesense] Unable to specify "path" configuration option

### ISSUE THREAD

**Issue by LanceXact** [airbytehq/airbyte#36372]
### Connector Name

destination-typesense

### Connector Version

0.1.3

### What step the error happened?

Configuring a new connector

### Relevant information

Typesense clusters can have a path as part of their URL. For example: {protocol}://{host}:{port}/{path}

Currently, only the following are configurable with this destination:
- protocol
- host
- port

This capability is shown in the js typescript client source code on GitHub:
https://github.com/typesense/typesense-js/blob/master/src/Typesense/ApiCall.ts#L389

### Contribute

- [x] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @LanceXact! Destination Typesense is a part of the community connectors, but it's not currently on the Airbyte roadmap for updates in next quarter. This means it might take some time before it gets prioritized by the team. However, we encourage community involvement to improve it, and your contributions are welcome! If you're interested, please reach out to me on Slack so we can discuss how you can help. Thanks for your support!
