### ISSUE TITLE
allow configurable resource management for kubernetes pods

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3638]
Allow specifying resource needs for pods. We could start with a global default (2gb or so) and allow tuning that default. Eventually we want to be able to configure this per source/destination pod on a specific sync.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387444123329) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
> configure this per source/destination pod on a specific sync.

Does this mean, we'd be adding a kubernetes advanced section in the connections page (when deployed on k8s)?
and these options would have to flow through the API all the way down to the scheduler?

**Comment by jrhizor** [comment]
Yeah there are multiple levels of this.

1) add default (and editable) resource allocations just for the core containers in a "production" Kustomize overlay
2) have default (and editable) resource allocations for launched pods in the production Kustomize overlay 
3) have default (and ui/api configurable) resource allocations per connector (which means they'd be stored in our configs) in a specific connection

1) can be achieved by just specifying the values in a yaml that extends the existing yamls
2) can be achieved by setting a default value in an `.env` file and passing that through, also in the "production" overlay (side note: we may also want to allow this for docker-compose, since we've seen some people want to tune their values in docker-compose as well)
3) this is the heaviest piece by far. we may be able to punt on this for a bit.
