### ISSUE TITLE
allow writing logs to cloud storage in kubernetes

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3639]
We need to save both worker logs and core logs. Log sweeping should sweep from cloud storage.

We'll also need to set this up for S3 first. We can likely punt on other Cloud Storage persistences (including GCS) for a bit after that.

**Acceptance Criteria**
- Sync logs should be viewable and downloadable even when syncs are run on a different node
- Check connection logs should be viewable and downloadable even when the job is run on a different node
- Server logs should be downloadable from Admin
- Scheduler logs should be downloadable from Admin

^ all of those should be from cloud storage, not disk

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387307317830) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
Done via #4053
