### ISSUE TITLE
[source-mailchimp] Incorrect primary key for `list_members` stream

### ISSUE THREAD

**Issue by NAjustin** [airbytehq/airbyte#36404]
### Connector Name

source-mailchimp

### Connector Version

1.1.2

### What step the error happened?

Other

### Relevant information

**The issue is that the `list_members` object currently has `primary_key` set to `id`, which is incorrect:**
- In Mailchimp, `members` are associated with `lists`. This means there will be one member record _per list_ they are on.
- `id` is a hash of the member's email address, which is obviously non-unique across lists
- This means that if you do an incremental sync with the current connector, you will only get one record per email—potentially resulting in record loss.

**Either of the following keys would be suitable:**
- `contact_id`, which is a non-email-specific identifier for the member within the list (so is unique across email+list)
- `web_id` is an integer and is also unique to the list+email combination
- `id` and `list_id` could also be used as a compound key with the same effect

**Mailchimp also discourages the use of `members`.`id` in their [docs](https://mailchimp.com/developer/marketing/api/list-members/list-members-info/) (see the `members`.`contact_id` response object), stating:**
>As Mailchimp evolves beyond email, you may eventually have contacts without email addresses. While the `id` is the MD5 hash of their email address, this `contact_id` is agnostic of contact’s inclusion of an email address.

This has been a longstanding issue in the Mailchimp source, but only affects accounts with the same contacts on multiple lists which may be why it's flown under the radar.

Happy to provide a PR with these changes.

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue and already fix it @NAjustin I hope to get a first review during this week.
As Mailchimp is a certified connector it can take some time to get it to merged as the team need to ensure it won't add new unnecessary breaking changes.

**Comment by NAjustin** [comment]
@marcosmarxm  FYI, with the rollout of the low-code 2.0.0 connector, I believe this issue can be closed (unless there's a desire to bugfix the previous versions for those who can't yet move to low-code for some reason).

**Comment by marcosmarxm** [comment]
Closing, idea is to upgrade to latest version.
