### ISSUE TITLE
Flatten json operation/mapper

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3641]
## Tell us about the problem you're trying to solve
An idea: We could have a generic JSON operation to insert in between source and destination that would be capable of transforming a heavily nested JSON into a flat json (not as part of normalization)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387616157534) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
closed as duplicate.
