### ISSUE TITLE
Destination S3: support writing Parquet data format

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3642]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Your answer

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200387481435866) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment]
Closed by #3908. Follow up issue: #4124.
