### ISSUE TITLE
Reduce source-mongodb default sync timeout for new connections

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#36457]
### Topic

one-off change for source-mongodb connections

### Relevant information

We're seeing a dip in success rate of source-mongodb connections.
Most of all errors are connections that errored out after their saved CDC cursor became invalid.
There are 2 things coming into play here:
1. New default behavior that completely error out a connection incase incremental CDC is no longer possible - in this case the saved portion of CDC is log no longer available on the server.
2. The Atlas platform (hosted mongodb) is more aggressive in recycling it CDC logs. And though the error is pointing into the relevant mongodb support page instructing how to do that, some user don't follow up.

Because the default 24 hours syncing timeout for new connections sends source-mongodb users into an error state, we should make a one-off change to the default value to reduce it to 6 hours.

**Comment by lmossman** [comment]
@rodireich @evantahler if 24 hour sync frequency sends users into an error state, should we actually disable that option for connections using this source?

**Comment by rodireich** [comment]
This is configurable on the managed atlas service, and I suspect that for self managed mongodb servers are going to be less aggressive in removal of logs.
So it's ok to leave it I think.

**Comment by lmossman** [comment]
@rodireich @evantahler this should definitely eventually go into the connector metadata service, but we can do this on the frontend for now for an immediate fix.

Also noting that cannot use different default sync frequency values depending on the configuration of the source (e.g. atlas or not), so this will just be a change to the default frequency for all mongodb sources regardless of configuration

**Comment by timroes** [comment]
Related to https://github.com/airbytehq/airbyte-internal-issues/issues/6313 we should figure out if we want it only on MongoDB or all CDC sources, and close one of those issues.

**Comment by lmossman** [comment]
Based on that issue I think it does make sense to do make this change for all CDC sources and therefore close out this issue in favor of that ^ one.

However that also complicates the issue because the sync frequency is a connection-level setting, and at that level we don't have any good way of looking into the source configuration to see if CDC is enabled for it

**Comment by rodireich** [comment]
The problem seems acute in MongoDB Atlas and while not as bad, I see a dip in mysql source success rate: currently at 97% for the last 2 weeks.
If possible we can reduce the default sync frequency for all connections matching source db + CDC.
If this gets too tricky we can do it for mongo.

**Comment by lmossman** [comment]
I've put up a quick fix to lower the default sync frequency for all new source-mongodb connections to 6 hours: https://github.com/airbytehq/airbyte-platform-internal/pull/11839

Note that as I stated above, we don't have a straightforward way to detect if the source uses CDC or not, so this change is just for any new connection using source-mongodb.
