### ISSUE TITLE
Getting error while deploying 0.54.140 or higher using helm 

### ISSUE THREAD

**Issue by kiran560** [airbytehq/airbyte#36474]
### Relevant information

when we deploy 0.54.140 or higher using helm getting below error 

Error: UPGRADE FAILED: template: airbyte/charts/worker/templates/deployment.yaml:326:15: executing "airbyte/charts/worker/templates/deployment.yaml" at <eq ((((.Values.global).secretsManager).awsSecretManager).authenticationType) "credentials">: error calling eq: incompatible types for comparison

**Comment by marcosmarxm** [comment]
@kiran560 please try with latest version and if the issue isn't fix please open a new issue sharing the values file for further debugging.

**Comment by mtrienis-dw-v2** [comment]
This still seems to be a problem on the latest version `0.79.1`
