### ISSUE TITLE
Refactor JDBC JSON_FORMAT

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3650]
## Tell us about the problem you're trying to solve
We copy and paste this snippet in a lot of places. We can refactor it into one static object. It's probably worth doing since this is just a verbose, esoteric JDBC configuration.

```
  private static final JSONFormat JSON_FORMAT = new JSONFormat().recordFormat(RecordFormat.OBJECT);
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200388235400123) by [Unito](https://www.unito.io)

**Comment by eliash0913** [comment]
If there is no one working on this. I would like to work on...

**Comment by cgardens** [comment]
yes! anyone can go for it!

**Comment by cgardens** [comment]
closed by https://github.com/airbytehq/airbyte/pull/7504 !
