### ISSUE TITLE
[source-amazon-seller-partner] All reports fail when reportOption=DAY

### ISSUE THREAD

**Issue by thedannywilcox** [airbytehq/airbyte#36543]
### Connector Name

source-amazon-seller-partner

### Connector Version

4.1.0

### What step the error happened?

Configuring a new connector

### Relevant information

I am using terraform to create a new Amazon Seller Partner source where reportOptions has reportPeriod=DAY, however, all of the reports that I've tried failed because airbyte is trying to query using 1 year of data at a time and seems to be ignoring the "Period in days" configuration.

Here are a list of reports tested so far:
* GET_VENDOR_TRAFFIC_REPORT
* GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT
* GET_VENDOR_SALES_REPORT
* GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT

If I had to guess what is happening, it looks like the initial query length is forced to 1 year which isn't supported when reportPeriod=DAY: https://github.com/airbytehq/airbyte/blob/67333ca6ea4f0fb1c7a11da9744485c4ccd23894/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L177 

Example terraform to replicate this behavior:

```resource "airbyte_connection" "this" {
  data_residency                = "auto"
  destination_id                  = "MY_DESTINATION"
  name                                 = "Amazon Seller Partner UK → S3"
  namespace_definition     = "custom_format"
  namespace_format          = "amazon_vendor_central_uk"

  non_breaking_schema_updates_behavior = "propagate_fully"

  prefix          = "test"
  source_id   = airbyte_source_amazon_seller_partner.this.source_id
  status         = "active"

  configurations = {
    streams = [
      {
        name      = "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT"
        sync_mode = "incremental_append"
      },
    ]
  }

  schedule = {
    schedule_type = "manual"
  }
}


resource "airbyte_source_amazon_seller_partner" "this" {
  configuration = {
    account_type    = "Vendor"
    aws_environment = "PRODUCTION"

    lwa_app_id        = "REDACTED"
    lwa_client_secret = "REDACTED"
    refresh_token     = "REDACTED"

    period_in_days = 1
    region         = "UK"


    report_options_list = [
      {
        options_list = [
          {
            option_name  = "reportPeriod"
            option_value = "DAY"
          }
        ]
        stream_name = "GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT"
      }
    ]
  }
  name = "Amazon Seller Partner (UK) test"
  workspace_id = var.airbyte_workspace_id
}
```

### Relevant log output

```shell
2024-03-26 23:38:33 source > Encountered an exception while reading stream GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 129, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 224, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 260, in _read_incremental
    for record_data_or_message in stream_instance.read_incremental(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 156, in read_incremental
    for record_data_or_message in records:
  File "/airbyte/integration_code/source_amazon_seller_partner/streams.py", line 418, in read_records
    raise AirbyteTracedException(internal_message=exception_message)
airbyte_cdk.utils.traced_exception.AirbyteTracedException: Failed to retrieve the report 'GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT' for period 2023-01-01T00:00:00Z-2023-12-31T23:59:59Z. This will be read during the next sync. Error: {'errorDetails': 'dataStartTime must be the same day as dataEndTime when reportPeriod=DAY'}
```

### Contribute

- [X] Yes, I want to contribute

**Comment by thedannywilcox** [comment]
I am still very new to Airbyte, so apologies if I am misunderstanding this but isn't this just forcing these reports to always be replication_start_date_limit_in_days when period_id_days < 30/90/365 (depending on report type)? 

Namely this line:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L206

`        self.period_in_days = max(period_in_days, self.replication_start_date_limit_in_days)  # ensure old configs work`

I can't see any way this could work for days?

**Comment by thedannywilcox** [comment]
If I update the [line of code](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L206) provided in the previous comment from `max` to `min` & add `replication_start_date = "2023-01-01T00:00:00Z"` explicitly, the above terraform works fine.

I don't understand the comment about old configs, so I don't know if there are downstream implications of this change. Regardless of the fix, happy to submit a PR.

**Comment by marcosmarxm** [comment]
The issue was triaged to the team backlog for further discussion in the next sprint session. If you're facing the same issue please react with 👍or leave a comment to help the team understand how many users are facing the issue.
