### ISSUE TITLE
[source-mysql] source lose `null` column

### ISSUE THREAD

**Issue by analytics-jabori** [airbytehq/airbyte#36553]
### Connector Name

source-mysql

### Connector Version

v3.3.13

### What step the error happened?

None

### Relevant information

source table have 4 column,but 2 columns are null
<img width="715" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/2da5647a-5a2a-45b8-b394-6a8af8699077">

when I sync data to s3, the json file content just have 2 column. **the null column have no key in json**.
![image](https://github.com/airbytehq/airbyte/assets/162086253/abfeb1c8-1d1e-457d-96db-730e3df3b277)

I need these two keys to ensure consistency in my data processing.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
To what destination are you sending the data?
@analytics-jabori are you able to share the schema desc from the source?

**Comment by evantahler** [comment]
Can you confirm that in the UI you have refreshed your schema as well?  What is the column type of the null collumns like `is_delete`?

**Comment by analytics-jabori** [comment]
> To what destination are you sending the data? @analytics-jabori are you able to share the schema desc from the source?

AWS S3.  the file format is jsonl
<img width="570" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/e1819169-b572-466d-8c8f-912f48900234">

**Comment by analytics-jabori** [comment]
> Can you confirm that in the UI you have refreshed your schema as well? What is the column type of the null collumns like `is_delete`?

<img width="1244" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/df1ad606-524c-434b-8538-faf675eb16ba">

**Comment by analytics-jabori** [comment]
> Can you confirm that in the UI you have refreshed your schema as well? What is the column type of the null collumns like `is_delete`?

source table have 4 columns: id(id), name, is_delete, is_use。
<img width="688" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/66d62282-5234-4a96-aed5-179299746098">
<img width="1099" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/5105c8fa-d193-4747-a2cd-97fa5291ac2d">

first, I reset this stream.
<img width="1301" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/6faba67e-60ca-4f77-b675-ff0156bad26c">

and then sync.

after finish, in S3 bucket have one jsonl file.
<img width="1395" alt="image" src="https://github.com/airbytehq/airbyte/assets/162086253/dad23569-0fd9-4c90-af85-10b29434f0d5">
the json content doesn't have "is_delete", "is_use" key.
I convert jsonl to txt. But the content is same.

[2024_03_30_1711827331165_0.txt](https://github.com/airbytehq/airbyte/files/14813157/2024_03_30_1711827331165_0.txt)

**Comment by analytics-jabori** [comment]
I think it should include all columns, even if it is empty.

{"id":0, "name":"jabori", "age": 40,"is_delete": null , "is_use": null}

**Comment by evantahler** [comment]
Grooming:

* Null values should always be present.  The set of keys in a record should be constant and match the schema.
* This problem exists in all sources.
