### ISSUE TITLE
New Connector: Dixa Export Conversations

### ISSUE THREAD

**Issue by hakiosos** [airbytehq/airbyte#3658]
## Tell us about the new integration you’d like to have
* Which source and which destination
Dixa
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
Export Conversations API: https://support.dixa.help/en/articles/174-export-conversations-via-api

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
My own team, we are creating a DW solution for a customer and would like to connect Dixa Conversations.
* How often do you want to run syncs?
Hourly
* If this is an API source connector, which entities/endpoints do you need supported?
https://exports.dixa.io/v1/conversation_export

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
We will create it ourselves, as we do need it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200389888159402) by [Unito](https://www.unito.io)

**Comment by olivermeyer** [comment]
I'll take a shot at this : )

**Comment by marcosmarxm** [comment]
awesome @olivermeyer if you need any assistance you can send messages to #connector-development in Slack
