### ISSUE TITLE
Users should be able to set composite primary keys in the UI.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3659]
## Tell us about the problem you're trying to solve
The Airbyte Protocol allows for arbitrarily complex composite primary key. i.e. Some flavor of incremental with normalisation enabled.

However, today the UI only supports source-defined cursors.

## Describe the solution you’d like
Users should be able to define composite cursors.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200390105454848) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I think this is already allowed:

![Screen Shot 2021-06-14 at 1 57 40 PM](https://user-images.githubusercontent.com/9092207/121958665-c2709780-cd18-11eb-9664-3f59759d4f52.png)

**Comment by hiteshsondhi88** [comment]
Is this limited to few types of sources/destinations?

I have tried this with MySQL as source (with CDC enabled) and Postgres as the destination but there are no checkboxes where I can select the keys.

**Comment by marcosmarxm** [comment]
@hiteshsondhi88 when you use CDC Airbyte already select the primary keys. You can read more here https://docs.airbyte.io/understanding-airbyte/cdc

**Comment by hiteshsondhi88** [comment]
@marcosmarxm thanks for the information but the issue with the current implementation is that we can't define custom composite keys with CDC and this is an issue if we have multiple sources(horizontally scaled) with the same destination
