### ISSUE TITLE
diagnostic script for support

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3668]
We get a lot of questions from users with something like "I'm running out of disk space, what do I do?" or "I'm getting this exception, what do I do?"

Then we go through a long back and forth to identify their configuration / versions / etc 

Instead, we could have a diagnostic bash script (maybe in `/tools/bin/diagnostic.sh`) that runs certain commands which will help debug.

Outputs of the script:

* OS Version
* if docker is installed
* docker version
* if docker-compose is installed
* docker-compose version
* if the docker daemon is running
* if the node has internet access (maybe even a small version of a speed test)
* Airbyte Version in .env
* Airbyte Version from an API call based on their .env
* All other non-sensitive .env keys/values
* Versions of connectors they're using via the API
* Disk space (overall disk space, `docker system df` / `docker system df -v`, /var/lib/docker/containers/*.log usage -- all the usual suspects)
* Total system memory

This should set up debugging specific logs much easier because it would provide all of the context we usually have to ask for on a case by case basis.

This should be a script and not part of core since it needs to be able to access non-Docker info.

We can also add stuff to this script over time to make it easier to debug overall.

We'll need a similar script for Kubernetes in the future, but that's beyond the scope of this issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200393257616023) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
@marcosmarxm what do you think?

**Comment by sherifnada** [comment]
we can also make this available in the UI as a button

**Comment by jrhizor** [comment]
> This should be a script and not part of core since it needs to be able to access non-Docker info.

**Comment by jrhizor** [comment]
In all seriousness it could be some combination.

**Comment by marcosmarxm** [comment]
> we can also make this available in the UI as a button

can we make this an API endpoint?
1. we can log this every set up so we can get this automatically.
2. available in the UI
3. if UI is not accessible you can `curl...` but we depend on the server probably.

other way is a sh script, we have a contribution done in a way already done here:
https://github.com/airbytehq/airbyte/blob/master/tools/bin/check_requirements.sh

**Comment by jrhizor** [comment]
That script checks requirements for building Airbyte, not for a running Airbyte. I think this would be a from-scratch endeavor.
