### ISSUE TITLE
cant get the value of conversion and cost per conversion (i want the purchase and cost per purchase ) from fb marketing

### ISSUE THREAD

**Issue by AdscalioDeveloper** [airbytehq/airbyte#36684]
### Topic

Fb Marketing Airbyte

### Relevant information

is there a problem with fb marketing and airbyte because my data pipeline cant get me conversion and cost per  conversion from fb  i have in my data pipeline the campaign name /campaign id / clicks /spend/conversion /cost per conversion , airbyte give me only the value of this  4 campaign name /campaign id / clicks /spend and in this 2 conversion /cost per conversion  it give me null ,what i want is to get the purchase and cost per purchase  for each campaign

**Comment by marcosmarxm** [comment]
Please use the correct form to report the issue. It is missing the connector version and provide any additional data to reproduce the problem. 
If data is missing please share some screenshots of FB report compared to Airbyte.
