### ISSUE TITLE
Add upgrade button to the app

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3673]
## Tell us about the problem you're trying to solve
* People try to upgrade Airbyte without ever seeing the upgrading docs. We want to do a better job getting users the info they need to upgrade successfully.

## Describe the solution you’d like
* Add an upgrade button above the help icon in the UI. When clicked this button will open in a new tab the upgrading airbyte docs page.

@johnlafleur does this sound okay for you? would you want to pick out the "upgrade" icon.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200394325831460) by [Unito](https://www.unito.io)

**Comment by johnlafleur** [comment]
Isn't this redundant with https://github.com/airbytehq/airbyte/issues/3003 ?

**Comment by cgardens** [comment]
@johnlafleur I don't think they are the same issue. This is specifically trying to improve the upgrade experience for the core platform, not for connectors.

Our main goal here is to improve the visibility of our upgrade instructions for the core platform

**Comment by johnlafleur** [comment]
Both are for the upgrading of the core platform...
Here's the design for #3003 https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=24505%3A0

**Comment by cgardens** [comment]
@Jamakase can we add the following button in the app ("Update" -- see screenshot below. Let's go with "Update" instead of "Updates".)

![Screen Shot 2021-06-24 at 12 51 53 PM](https://user-images.githubusercontent.com/9092207/123323860-f56e1480-d4ea-11eb-9e17-2de88baa1374.png)

## Must Have:
This button should open a new tab and link to `https://docs.airbyte.io/upgrading-airbyte`.

## Nice to have:
This button only appears when there is a new version of Airbyte available. This would be determined by fetching this file from github https://github.com/airbytehq/airbyte/blob/master/.env and comparing the `VERSION` variable to whatever version the webapp is running on. If the version on github is greatr than the button should appear (with a a red dot, like we do for the admin page). 

You can find the logic for how we do the version comparison in java [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-commons/src/main/java/io/airbyte/commons/version/AirbyteVersion.java#L93-L106); it might be a useful reference as you will likely need something similar in javascript.

@Jamakase lmk if the "nice to have" section feels reasonable to you.

**Comment by johnlafleur** [comment]
We'll use getbeamer.com to display those updates. 

Regarding Beamer: 
* Installation guide: https://www.getbeamer.com/blog/tutorial-how-to-use-beamer-in-your-website-or-app
* We would use our own icon in the left column (not theirs), so embedded widget
* You should have received an invitation to that tool
* Here's a design of how it should like: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26416%3A82098

**Comment by cgardens** [comment]
The first part of this is done. We have an upgrade button that links to docs. The second part of integration beamer still needs to be done. That's on me to understand what that entails first. Adjusting priority for now too since other cloud tasks are taking priority.

**Comment by timroes** [comment]
I'm going to close this, since the integration of beamer (which was the left work in this issue) hasn't been coming up recently. If we'll still consider this, we'll create a new issue targeted to that.
