### ISSUE TITLE
[terraform] cannot add streams to existing connection

### ISSUE THREAD

**Issue by adam-bloom** [airbytehq/airbyte#36756]
### Topic

Unable to use terraform to edit stream configuration after creation

### Relevant information

I wanted to add new streams to a connection. The current terraform provider throws a 400 error:

```
{"configurations":{"streams":[{"cursorField":["_ab_cdc_lsn"],"name":"<existing stream name>","primaryKey":[["id"]],"syncMode":"incremental_deduped_history"},{"name":"<stream to add>","syncMode":"incremental_deduped_history"} ...

│ HTTP/2.0 400 Bad Request
│ {"detail":"The body of the request contains an invalid connection
│ configuration. Primary key for stream: <existing stream name> is already pre-defined.
│ Please do NOT include a primary key configuration for this
│ stream.","type":"https://reference.airbyte.com/reference/errors","title":"bad-request","status":400}
```
The provider added the cursorField and primaryKey above - that is not stated in my configuration (only contains name and syncMode). I cannot figure out a workaround short of deleting the connection and recreating.

**Comment by adam-bloom** [comment]
@marcosmarxm is this the right place to create issues for the terraform provider? or do those belong elsewhere?

**Comment by bmschow** [comment]
I am also having a similar issue:
When I use terraform and try to specify a primary key in a stream for a postgres connection with a sync type of incremental_dedup_history i get
Primary
│ key for stream: plans is already pre-defined. Please do NOT include a
│ primary key configuration for this stream
however, if i do not specify a primary key it tells me I must specify a primary key.  I can get past this by specifying:
"primary_key": []
however, this still gives a terraform error:
When applying changes to
│ airbyte_connection.massdriver_workfront_teams_to_redshift, provider
│ "provider[\"registry.terraform.io/airbytehq/airbyte\"]" produced an
│ unexpected new value: .configurations.streams[0].primary_key: new element 0
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by adam-bloom** [comment]
@bmschow created https://github.com/airbytehq/terraform-provider-airbyte/issues/91 as well - which one should remain open and which should be closed?

**Comment by marcosmarxm** [comment]
@adam-bloom let's keep only the one in the terraform repo.
