### ISSUE TITLE
Source exchangerates API: clearer error message when a currency isn't supported

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3677]
## Tell us about the problem you're trying to solve
A user reported getting the following issue when running the exchangerates API: 

```
{"error": {"code": "base_currency_access_restricted",
"message": "An unexpected error ocurred. [Technical Support: support@apilayer.com]"
}
}
```

After some investigation this worked when they removed the base currency parameter. 

I suspect this happened because  the free tier of exchangerates doesn’t support specifying a currency (i think they give you euro or USD data by default). The cosmetic issue is the connector does not surface a good error message. 

## Describe the solution you’d like
I would like the connector to surface an easily understandable message explaining that the problem is that specifying base is not supported on the free tier. This will be tricky because we need to differentiate that error from a different error like the API token being wrong. Maybe we should use HTTP request codes e.g: 403 is invalid token, other ones mean a bad base. I'm not sure exactly what the right way to identify the difference is. 

Potentially one way to verify this is to make two requests in check: one without a base. If that succeeds API token is good. Then make another request with the base. If that succeeds then the issue is with the base. 

This should all be documented in the `check` command's method because this context is not obvious.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200394422997967) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
In documentation we comment:
> The exchange rates integration is a toy integration to demonstrate how Airbyte works with a very simple source.

Why do not remove the `base` parameter?

**Comment by jrhizor** [comment]
We could also just hardcode the currencies supported as a regex.

**Comment by cgardens** [comment]
Could it be an enum instead of a regex?

**Comment by vitaliizazmic** [comment]
@sherifnada you are right, Source Currency Switching is [supported only in paid plans](https://exchangeratesapi.io/pricing/). The default base currency is [EUR](https://exchangeratesapi.io/documentation/#basecurrency)
