### ISSUE TITLE
The check connection failed because of an internal error in the scheduler used by airbyte.

### ISSUE THREAD

**Issue by spunzon** [airbytehq/airbyte#36783]
### Platform Version

0.57.1

### What step the error happened?

During the Sync

### Revelant information

After updating to version 0.57.1 the sync of all connections fail. With version 0.51 it was working without problem. There is no log:
![image](https://github.com/airbytehq/airbyte/assets/38790201/0e27b12f-6ade-4726-95c1-064d8b715cda)
I add info about SO and Docker:

cat /etc/os-release:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

uname -r:
6.1.0-18-cloud-amd64

docker --version:
Docker version 26.0.0, build 2ae903e

docker compose version:
Docker Compose version v2.25.0

### Relevant log output

```shell
Failure reason: The check connection failed because of an internal error
The check connection failed because of an internal error in the scheduler used by airbyte.
```

**Comment by perangel** [comment]
Thank you for reporting this issue @spunzon 

This appears to be caused by a recent change that modifies the user the containers run as (no longer running as root). The solution is to recreate the `airbyte_workspace` docker volume (e.g. delete it and let it get recreated by docker compose) when you start Airbyte up again.

**Comment by techxorcist** [comment]
To avoid recreating the volume, this can also be resolved by changing the ownership of /tmp as outlined [here](https://github.com/airbytehq/airbyte/discussions/36984#discussioncomment-9086401).
