### ISSUE TITLE
Give a clearer visual indication that we are discovering schema

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#368]
## Tell us about the problem you're trying to solve
When schema discovery is being performed, it's not clear to the user what is happening. We should add a line of text underneath the loading screen that indicates to the user that schema discovery is being performed. 

Example screenshot: 
![Screen Shot 2020-09-21 at 4 03 15 PM](https://user-images.githubusercontent.com/6246757/93830051-fd2f1e80-fc23-11ea-96a7-bffdb4f863a8.png)

## Describe the solution you’d like
My suggestion is to add some text underneath or above the loading spinner that indicates to the user that we are performing schema discovery. @johnlafleur FYI

**Comment by sherifnada** [comment]
@johnlafleur Assigning this to you to figure out any necessary design details. Pls assign to artem aftewards.

**Comment by johnlafleur** [comment]
Here is a suggestion: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=5782%3A28959
Please reassign to Artem, if that looks good to you.

**Comment by cgardens** [comment]
I put one comment on the copy, but otherwise it looks good.
