### ISSUE TITLE
[source-MongoDB] Add support for UUID as _id field

### ISSUE THREAD

**Issue by jvollmuller-risk** [airbytehq/airbyte#36820]
### Connector Name

source-mongodb

### Connector Version

1.3.0

### What step the error happened?

None

### Relevant information

Our collection uses UUID as _id field instead of ObjectId. On this moment it is not supported and we cannot change it easiliy due to running production applications.

### Relevant log output

```shell
Only _id fields with the following types are currently supported: objectId, string, int, long
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@jvollmuller-risk I added this to the connector team backlog. I saw you created a PR and closed it, are you want to continue the contribution?

**Comment by antiqe** [comment]
Hello @jvollmuller-risk, we are looking at the same thing, if needed we can collaborate.

**Comment by evantahler** [comment]
The implementation in https://github.com/airbytehq/airbyte/pull/36789was a really good start

**Comment by jvollmuller-risk** [comment]
Is there a easy solution to make this work on my local installation? We use Docker to run it. Unfortunately, my Java skills aren't as strong as my Python skills; otherwise, I would create a PR.

**Comment by marcosmarxm** [comment]
@jvollmuller-risk this is in the current sprint. Team is working to implement the solution.

**Comment by rodireich** [comment]
@jvollmuller-risk and @jorgeparavicini 
Support for collection id column of UUID type is now live in source mongodb v1.3.13!

Please let us know how this is working for you.
Thanks

**Comment by jvollmuller-risk** [comment]
> @jvollmuller-risk and @jorgeparavicini Support for collection id column of UUID type is now live in source mongodb v1.3.13!
> 
> Please let us know how this is working for you. Thanks

Thanks! After the update the connection ran immediately without any errors!

**Comment by antiqe** [comment]
@rodireich Thanks a lot for this 💚
