### ISSUE TITLE
implement codecov in all python modules

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3686]
## Tell us about the problem you're trying to solve
I would like to know the unit test coverage of every python module we have when running `pytest`. 

## Describe the solution you’d like
I would like: 

1. codecov to be available in every python module by default. this should also be available in newly generated templates. 
1. to run codecov by default whenever I run `pytest`
1. Ideally i don't have to replicate the settings file for pytest in each project. But if we do it's not the end of the world as long as there is an easy way to edit them in batch.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200394660569770) by [Unito](https://www.unito.io)

**Comment by alafanechere** [comment]
Opened https://github.com/airbytehq/airbyte/issues/15441 for SAT
