### ISSUE TITLE
[source-s3, file-cdk] `avro` loader possibly doesn't handle "timestamp-..." types correctly?

### ISSUE THREAD

**Issue by imrehg** [airbytehq/airbyte#36920]
### Topic

CDK Avro timestamp logical types

### Relevant information

I was trying to load some Avro files with fields set with one of the _default_ logical types (in particular `timestamp-micros`), which internally uses a long integer type ([docs](https://avro.apache.org/docs/1.11.0/spec.html#Timestamp+%28microsecond+precision%29)).

In Airbyte (with the S3 source with a file generated by the below script as an input), I get a successful schema extraction when setting up the connector, but then such error when running the sync:

<img width="2036" alt="Screenshot 2024-04-09 at 13 29 46" src="https://github.com/airbytehq/airbyte/assets/38863/911e7c1d-66d5-4280-9ff1-8800ff54763e">

That is:
```
Error parsing record. This could be due to a mismatch between the config's file type and the actual file type, or because the file or record is not parseable.
[...]
ValueError: None is not a valid ComparableType
```

In Python, the below scripts write-then-read flow results in correct decoding of the field, without any custom logical readers::
```
{'temp': 0, 'date': datetime.datetime(2024, 4, 9, 5, 24, 9, 902062, tzinfo=datetime.timezone.utc)}
{'temp': 22, 'date': datetime.datetime(2024, 4, 9, 5, 25, 9, 902062, tzinfo=datetime.timezone.utc)}
{'temp': -11, 'date': datetime.datetime(2024, 4, 9, 5, 26, 9, 902062, tzinfo=datetime.timezone.utc)}
{'temp': 111, 'date': datetime.datetime(2024, 4, 9, 5, 27, 9, 902062, tzinfo=datetime.timezone.utc)}
```

Test file generation script:

```python
import datetime

from fastavro import parse_schema, reader, writer

schema = {
    "name": "LogicalTest",
    "type": "record",
    "fields": [
        {"name": "temp", "type": "int"},
        {
            "name": "date",
            "type": {"logicalType": "timestamp-micros", "type": "long"},
        },
    ],
}
parsed_schema = parse_schema(schema)

now = datetime.datetime.now(tz=datetime.timezone.utc)
delta = datetime.timedelta(minutes=1)

# 'records' can be an iterable (including generator)
records = [
    {"temp": 0, "date": now - 3 * delta},
    {"temp": 22, "date": now - 2 * delta},
    {"temp": -11, "date": now - delta},
    {"temp": 111, "date": now},
]

# Writing
with open("example.avro", "wb") as out:
    writer(out, parsed_schema, records)

# Reading
with open("example.avro", "rb") as fo:
    for record in reader(fo):
        print(record)
```

Is it a bug, or am I missing something / doing something wrong?

NB. other Logical Types I've tested (`uuid` that is stored as `string`, and `date` which is stored as `int`) seem to work.

**Comment by marcosmarxm** [comment]
@imrehg I added your inquiry to the team responsible for the CDK.
@natikgadzhi can you take a look in next grooming section?

**Comment by natikgadzhi** [comment]
@imrehg damn, we've dropped the ball here. 
@girarda do we know if avro is popular for us overall? Is this a priority?

**Comment by artem1205** [comment]
Hey @imrehg ,

CDK was updated to parse timestamp values, see https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/file_based/file_types/avro_parser.py#L181-L182

Could you try the latest version of connector?
