### ISSUE TITLE
Saved state can leave stale data if streams excluded from sync

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#36946]
### Connector Name

source-postgres

### Connector Version

3.3.23

### What step the error happened?

During the sync

### Relevant information

Problem was discovered with source-postgres but may very well exist on other db connectors that follow the same stream pattern [[workspace]](https://cloud.airbyte.com/workspaces/7c1a9ee7-09f6-49fe-bf98-8746ed05697e/connections/2f187a6d-7569-4059-9d64-48a69b25c1b2/job-history)

Steps to to recreate:
1. Add a number of incremental streams on a new CDC connection.
2. Sync in order to generate a saved state.
3. Disable one of the streams.
4. Reset the connection

Expected behavior:
Saved state is disposed of.

Actual Behavior:
Active streams are gone after a reset.
But we're left with the `shared_state` and the now disabled stream state

This in turn will cause a problem if the saved CDC lsn inside `shared_state` is purged on the server, as there's no way of getting rid of the `shared_state`.

### Example of a state that is stuck

```shell
{
  "shared_state": {
    "state": {
      "[\"orderingdb\",{\"server\":\"orderingdb\"}]": "{\"transaction_id\":null,\"lsn_proc\":580995 … }"
    }
  },
  "streamStates": [
    {
      "streamDescriptor": {
        "name": "<now disabled stream>",
        "namespace": "public"
      },
      "streamState": {
        "stream_name": "<now disabled stream>",
        "cursor_field": [],
        "stream_namespace": "public"
      }
    }
  ]
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by nataliekwong** [comment]
Related: https://github.com/airbytehq/airbyte-internal-issues/issues/2307

**Comment by evantahler** [comment]
Closing in favor of https://github.com/airbytehq/airbyte-internal-issues/issues/2307
