### ISSUE TITLE
new source: airbyte-native zoom connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3696]
## Tell us about the new connector you’d like to have
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. The new connector should have complete feature parity with the existing singer-based one. Once this is complete we should delete the singer-based connector and replace it with the new one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200395636242074) by [Unito](https://www.unito.io)

**Comment by vitaliizazmic** [comment]
While working on native connector I faced with next difficulties of use Zoom API:

1. Past meetings endpoints (meeting_files, meeting_poll_results) return error 404 for some meetings. Response 404 isn't described in meeting_poll_results API documentation. Description in meeting_files isn't clear, it says, that error 404 is returned when Meeting ID is invalid or not end. I checked Meetings List API and Get API, they don't return any fields, which help finding out if Meeting is ended. But there is endpoint for fetching [list of ended meeting instances](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/pastmeetings). When this list is empty past meetings endpoints return error 404. We can check if meeting is ended using this endpoint, but it requires at least one additional request for each meeting.
2. Registration meetings endpoints (meeting_registrants, meeting_questions) return error 400 with code 300 for all meetings. This behavior is not described in documentation. But after vetting Zoom documentation, I found out that only Licensed users have access to this [feature](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).  A [Licensed user](https://support.zoom.us/hc/en-us/articles/201363173-Account-types) is a paid account user.
3. Poll meetings endpoints (meeting_polls) return error 400 for all meetings too. Response 400 isn't described in API documentation. But poll [feature](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) also required Licensed user
4. Webinars and webinar related endpoints require [Webinar Plan](https://zoom.us/webinar). When Webinar Plan is missing, API returns Response 400. This behavior is not described in documentation. 
5. Report endpoints return error 400. They only available for Paid account. This behavior isn't described in documentation too.

**Comment by sherifnada** [comment]
@vitaliizazmic it looks like pretty much most of the useful endpoints here require a paid license. I'm going to apply for a sandbox account from zoom because this data is probably difficult to fake without a sandbox account. Until then, can you move to a different task? I'll mark this as blocked for now

**Comment by benweissbehavehealth** [comment]
@sherifnada will having a paid license unblock this issue? 

@michel-tricot  does Airbyte have plans to fund the unblocking of connector development?

**Comment by michel-tricot** [comment]
We do have paid accounts for zoom. This connector would have to make it higher in our priority list. 

Until it gets bumped up you have 2 options:
- someone from your team can implement one and we can help
- user our marketplace: https://discuss.airbyte.io/c/connector-marketplace/10/none

**Comment by marcosmarxm** [comment]
Closde by https://github.com/airbytehq/airbyte/pull/18179
