### ISSUE TITLE
new source: airbyte-native mixpanel connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3698]
## Tell us about the new connector you’d like to have
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. The new connector should support the same endpoints as the existing singer-based one. Once this is complete we should delete the singer-based connector and replace it with the new one.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200395642460024) by [Unito](https://www.unito.io)

**Comment by midavadim** [comment]
I am working on migration of mixpanel from singer to native airbyte source.

One of the stream that we need to implement is Export, which gives the following error when try to access it via API:

    Your plan does not support raw data export. Visit mixpanel.com/pricing to upgrade.

So, according to https://mixpanel.com/pricing/#pricing-core-features we need to upgrade plan to "Growth" $25/mo
