### ISSUE TITLE
docker-proxy logs fill all the space on the instance

### ISSUE THREAD

**Issue by killthekitten** [airbytehq/airbyte#36997]
### Platform Version

0.57.1

### What step the error happened?

Other

### Revelant information

We've just upgraded to v0.57.1 and ran out of space on a 50gb drive in about 24 hours. Investigation shows that the fastest growing file is the log of the new `docker-proxy` instance added that was add three weeks ago in this commit: https://github.com/airbytehq/airbyte-platform/commit/901401a668738d7cb26c2821425e8a7432c26eb1 (CC @davinchia @colesnodgrass @perangel).

![image](https://github.com/airbytehq/airbyte/assets/1201569/71203983-639c-4ae9-a040-8fcfa21d3222)

In our setup the log can be found in `/var/lib/docker/containers/${container_id}/${container_id}-json.log`. The file size is around 4 gigs a few hours after bootstrapping the instance.

The container ID matches the `docker-proxy` service running `alpine/socat` in `docker ps`:
```
...
976f891f7683   alpine/socat                              "socat -d -d -t 900 …"   8 hours ago     Up 8 hours     0.0.0.0:32768->2375/tcp, :::32768->2375/tcp                                                                                                                   airbyte-docker-proxy-1
```

The log tail contains identical messages similar to these:
```
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 239) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.262804779Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 239) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.262966846Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 214) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.263146252Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 239) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.263340783Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 215) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.263645151Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 215) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.263768557Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 215) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.264010453Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 239) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.264232637Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 239) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.264465207Z"}
{"log":"2024/04/11 14:51:31 socat[1567] N write(6, 0x7b2e3cc4d000, 216) completed\n","stream":"stderr","time":"2024-04-11T14:51:31.264638175Z"}  
```

Are the `-d -d` socat flags (verbose debug info) strictly necessary in a production deployment? Also, the logs mention `stderr` and are being written rapidly. Could it mean that our deployment is misconfigured, or is the amount of logs normal at this verbosity level?

The host system is Ubuntu 22.04 LT, here's the docker-compose.yaml:

```
  docker-proxy:
    image: alpine/socat
    command: -d -d -t 900 TCP-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    ports:
      - "2375"
    user: root
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    networks:
      - airbyte_internal
```

**Comment by killthekitten** [comment]
@perangel that's great, thanks for the quick response!

As for these particular logs, I guess it's nothing critical?

**Comment by perangel** [comment]
@killthekitten Correct, you can disregard those logs
Those flags have now been updated https://github.com/airbytehq/airbyte-platform/commit/d5bd6d2e5f8e1be007460372994298563a069b24
