### ISSUE TITLE
[source-facebook-marketing] Status filters not applied for Ad Insights streams

### ISSUE THREAD

**Issue by wmcguinn-octave** [airbytehq/airbyte#36998]
### Connector Name

source-facebook-marketing

### Connector Version

2.1.1

### What step the error happened?

During the sync

### Relevant information

When running a sync for Ad Insights, if the first attempt at the jobs never fails, all data is returned properly. But if a job fails twice and needs to be split into smaller jobs, it seems that the filters aren't applied properly and the default behavior is applied, i.e. deleted/archived ads are not synced.

Ideally the status filters from the config are used so that the data synced is consistent from run to run, regardless if a job needs to be split into smaller jobs

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@wmcguinn-octave I included the issue to the connector team backlog for further investigation.
