### ISSUE TITLE
new source: airbyte-native intercom connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3699]
## Tell us about the new connector you’d like to have
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. The new connector should support the same endpoints as the existing singer-based one. Once this is complete we should delete the singer-based connector and replace it with the new one.

**Comment by prasrvenkat** [comment]
Could we also make sure `conversation_parts` syncs incremental as well, (based on conversation state/update)?
Right now it sync all parts all the time, not just for the updated conversation. Limiting to that would be huge benefit for fairly frequent syncs as parts tend to be large in number.
Happy to help do this as well.
