### ISSUE TITLE
[source-Mongodb] Mongo to Postress new datasets are not loaded

### ISSUE THREAD

**Issue by fabianboerner** [airbytehq/airbyte#37026]
### Topic

New Datasets for connection Mongodb to Postgres not loaded

### Relevant information

We have setup a connection between mongodb and postgres but the data is not synced if new.

We have multiple connections from different databases in mongodb to one database with multiple schemas in postgress.

Here is the jobs list it is always showing 101 records no matter how many new records we actually got in  mongodb.

Resetting the data and resync works.

![image](https://github.com/airbytehq/airbyte/assets/115671732/9d8196e9-f719-4fb5-bd21-eb84b885b316)

* update

it seems through terraform the connection waiting time for the connector was set to 9 seconds, but the valid range should be 120 and 1200 seconds. I will check if this is the issues problem.

**Comment by marcosmarxm** [comment]
@fabianboerner included the issue in the connector team backlog.
Can you please provide what version of the connectors and platform are you using?

**Comment by evantahler** [comment]
Closing this issue due to lack of comment from OP - we need to know which version of the platform and connectors are in use.
