### ISSUE TITLE
Upgrade Airbyte according to doc - UI doesn't load (500 response from server)

### ISSUE THREAD

**Issue by royt-via** [airbytehq/airbyte#3707]
## Expected Behavior
Airbyte to load

## Current Behavior
Getting this error - `Version mismatch between 0.24.2-alpha and 0.22.2-alpha.\nPlease upgrade or reset your Airbyte Database, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte`

## Severity of the bug for you
Critical

## Airbyte Version
0.24.2-alpha

Pulled master from Github - including `.env` where the version variable is set to `0.24.2-alpha`
(All Airbyte images are of tag 0.24.2-alpha)
![image](https://user-images.githubusercontent.com/57411950/120048127-45d57d80-bfe4-11eb-8120-e8059b72c21d.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200396995442822) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@royt-via you need to submit the upgrade process described here https://docs.airbyte.io/upgrading-airbyte there are some config files we persist and using a new version they must be upgraded.

**Comment by marcosmarxm** [comment]
@royt-via I'll close this. The latest version of Airbyte has auto-migration which handle this issue.
