### ISSUE TITLE
Label PRs and issues coming from community members as `community`

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3719]
## Tell us about the problem you're trying to solve
We have a lot of PRs and issues being open and closed every day which is great, but that sometimes means contributions from the community are not easily seen. 

## Describe the solution you’d like
I want every PR and issue opened by a non-Airbyte employee to be labelled with the `community`. This is doable via Github actions but maybe there are off-the-shelf solutions.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200398204249119) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
First of all: there is are two fields in the API we can use `author_association` or `fork`. The first one is preferred. 
I look for a Github Action tool to do this but didn't found any who allow me to label using API fields.
We use a Github Action to insert into projects that do this but cannot add labels.
