### ISSUE TITLE
Improve Code Review Assignment Process

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3720]
A couple months ago, we started using a tool to auto assign code reviews. I think it is not really achieving the goals we set out for it. This issue will lay out the goals we set for it, the process we use, and how well the process is serving the goals. This last section is very subjective. The second part will then propose another iteration on this process.

### Goals:
* Spread out knowledge about the codebase across the whole team.
* Increase the number of reviews per PR
* Reduce wait times on code review
### Implementation
* Auto assign 2 people, filtering out zazmic PRs.
### Result:
* Most PRs are still merged with 1 review
* People are ignoring assignments as they are getting assigned to PRs that it doesn't make sense for them to review. This is bad because PR assignment notifications can no longer be trusted.
* People still do not really review significant PRs that they don't have context on.
* PRs are not getting reviewed in a timely fashion

Based on the stated goals, this solution is not really achieving them.

### Goals:
* Spread out knowledge about the codebase across the whole team.
* ~~Increase the number of reviews per PR~~ (advocating for dropping this as a goal as our behavior seems to indicate that we do not value it highly)
* Reduce wait times on code review
### Implementation Option 1: Remove Auto Assign Bot
* Just as we do a :tada: to demarcate PRs that should be highlighted in the weekly community slack update, find some way to tag PRs that we feel are with the broader team reading not necessarily reviewing. It is always fine to read a PR (and leave more comments) after it is merged.
* In cases where 2 people are paired up working on a project, it is fine for them to streamline their development by being primary reviewers on each other's work. They should apply judgment, however, and loop in another person to get an outside perspective when they think it would be valuable. Err on the side of asking for extra outside review. While it would be better if we could with high accuracy use an automatic tool to identify these cases, the auto assign bot is not able to do this, so in lieu of a tool we use judgment instead of not optimizing for this important case.
* Where possible, round robin the request for reviews.
* If you are assigned a review, you should have high confidence that you should actually do the review promptly. Unlike now, where I am personally ignoring the review-requested notification, because half of them are misfires.
### Implementation Option 2: Tune Auto Assign Bot
* Create a pool of engineers to handle internal PRs that touch `airbyte-integrations` and `airbyte-cdk`. Then create a separate pool for everything else.
* Create a pool of engineers to handle contributor PRs for `airbyte-integrations` and `airbyte-cdk`. Probably the same for contributor PRs on everything else.

The contributor auto assignment in Option 2 could be paired with Option 1 for internal PRs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200398463306322) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
1) sounds best although I think you should x out ~~Spread out knowledge about the codebase across the whole team.~~ as a goal.

**Comment by cgardens** [comment]
Killed the code review assignment bot. https://github.com/airbytehq/airbyte/pull/3974
