### ISSUE TITLE
UI: Make logs easier to read by allowing scrolling, use of the full window, and a smaller font

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#3725]
## Tell us about the problem you're trying to solve
Debugging involves spending a lot of time reading logs in the web browser UI.  Unfortunately, the UI makes it unnecessarily difficult to read them, in a few ways:

* The font isn't great for readability.  Thanks for using Courier Prime instead of Courier New :) but it still has a pretty small x-height, which makes the letters tougher to identify.
* The lines wrap, which makes it harder to find the start of each line, or to see repeated patterns in similar lines.
* Multiple spaces are collapsed into one space, so indentation is lost.
* Occasional long lines without spaces still run way off the right edge, so the view can scroll horizontally in an unhelpful way.
* The entire log is embedded directly in the page, which makes the next item/attempt very far away vertically, and hard to find when it's buried between huge logs.
* The width of the text box is limited to a small fixed amount (about 100 characters, even though most log lines are much longer), and it refuses to get wider even if I make my window wider.  (This is my personal pet peeve on lots of websites — please let me use my screen!  If I make my window really wide, that's because I want to use the extra width, not because I want to waste all that space.)

Compare fonts: Courier Prime vs. Menlo
![image](https://user-images.githubusercontent.com/236086/120038779-a3ec6b80-bfb8-11eb-9553-3482a3fc33b9.png)

Compare fonts: Courier Prime vs. SF Pro
![image](https://user-images.githubusercontent.com/236086/120038071-8bc81c80-bfb7-11eb-8420-942efde7679d.png)

Compare screen usage: limited width vs. unlimited width
![image](https://user-images.githubusercontent.com/236086/120038151-a7332780-bfb7-11eb-9af6-37bff6bd32b1.png)
![image](https://user-images.githubusercontent.com/236086/120038243-ce89f480-bfb7-11eb-9832-f60e33afcfc2.png)

## Describe the solution you’d like
A few small changes to CSS would probably do the trick: vertical and horizontal scrolling, unlimited width, a smaller font designed for high legibility, and white space in preformatted mode so indentation is visible.

## Describe the alternative you’ve considered or used
I'm currently using a user style in Chrome with the following CSS and I find it a lot better.  A proportional font even works pretty well, as long as tabular numerals are used (`font-variant-numeric: tabular-nums`).  I realize some of this is personal taste, but I hope you'll agree that it's easier to spot the exception in the second screenshot below:

Before:
![image](https://user-images.githubusercontent.com/236086/120038421-1872da80-bfb8-11eb-8d6b-755f9e6074bb.png)

After:
![image](https://user-images.githubusercontent.com/236086/120038428-1f99e880-bfb8-11eb-97ba-e85388aef356.png)

CSS:

```
.kubSQv, .ldyLiF {
    font-size: 11px;
    line-height: 13px;
    font-family: system-ui;
    font-variant-numeric: tabular-nums;
    white-space: pre;
    overflow: auto;
    max-height: 70vh;
}
.dbhMVG, .fdsIjn, .gglDmq {
    max-width: none;
    margin: 0 24px;
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200399042828463) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@zestyping thanks for the incredibly useful suggestions and detailed report! forwarding this to @johnlafleur for design consideration & @Jamakase as UI eng

@cgardens FYI

**Comment by Jamakase** [comment]
I do not think that we should make window wider. There are plenty of examples that follow quite the same format and I am pretty sure that we shouldn't reinvent the wheel. The idea here is that your eyes shouldn't follow z-pattern when you read something ( quite the same is described in ui guide that @johnlafleur sent before in slack ). So I am against `unlimited width` option.

As a solution for #2562, we are going to use react-lazylog and reiterate this task again if necessary after we gain some feedback ( discussed with @cgardens during the sync ).

Thank you so much for your suggestions, I will take into account them during the work on log view improvement.

**Comment by sherifnada** [comment]
what is the downside of making width scale with screen size?

**Comment by cgardens** [comment]
@Jamakase assigning this to you so that you can close it when you do the other log readability stuff.
