### ISSUE TITLE
Create an automatic API data generator

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3727]
## Tell us about the problem you're trying to solve
Populating an API with data is very time consuming, even when done through the API. If I want to populate data for many endpoints, each of which have a complicated schema or nested objects, then it is very time consuming to create test data to populate the API with (it's also very difficult to do correctly, including edge cases etc..). 

## Describe the solution you’d like
We have JSON schemas which describe each API. Why don't we create (or use a ready-made) tool that takes as input a JSON schema and generates random data which matches the given JSON schema. This has two benefits: 

1. Makes it a lot faster and higher quality to populate data in the API
1. Makes mocking API responses a breeze since we already have a test set which we can use to test the connector locally

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200399347721959) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment]
Two candidates here:
- https://github.com/json-schema-faker/json-schema-faker
- https://github.com/atomsfat/fake-schema-cli
