### ISSUE TITLE
[deploy] Getting Started Guide Fails Silently

### ISSUE THREAD

**Issue by benjcabalona1029** [airbytehq/airbyte#37308]
### Platform Version

0.57.2

### What step the error happened?

On deploy

### Revelant information

it fails silentl. Commenting 
set -o nounset # -u exit if a variable is not set
set -o errexit # -f exit for any command failure"

fixes the issue

### Relevant log output

```shell
No logs
```

**Comment by marcosmarxm** [comment]
Can you provide more information about what steps and OS you're using?

**Comment by benjcabalona1029** [comment]
I have tried it on both Linux Mint (which uses ubuntu 22.04) as well as ubuntu server 22.04.

Linux Mint is my laptop and the ubuntu-server is a VM running on proxmox.

**Comment by marcosmarxm** [comment]
@benjcabalona1029 what steps did you run? Are you using `abctl` or `run-ab-platform.sh` script?

**Comment by marcosmarxm** [comment]
Closed as inactive.
