### ISSUE TITLE
[destination-postgres] Airbyte OSS requires SSH Tunnel connection even if it is not chosen in configs

### ISSUE THREAD

**Issue by IlyaDropit** [airbytehq/airbyte#37319]
### Connector Name

destination-postgres

### Connector Version

2.0.9

### What step the error happened?

Updating the connector

### Relevant information

When creating a new connection or updating an existing `destination-postgres` connector on Airbyte OSS, Airbyte by default requires SSH Tunnel Method even though `No Tunnel` is chosen (see the log output). [According to documentation](https://docs.airbyte.com/integrations/destinations/postgres?_gl=1*9aj6t7*_gcl_au*OTA5MjU0MjA2LjE3MTI1ODIwNzU.#prerequisites), TLS and SSL for Postgres version 9.5 and above are only required for Airbyte Cloud with TLS being the default. However, there are no such requirements for OSS and up until recently Airbyte allowed regular connections to Postgres. Also, this connection was created a few months ago and is working fine otherwise.

Exact PostgreSQL version: `15.5`.
The Airbyte platform version is `0.57.1`

The problem appeared after upgrading to Destination v2, although I can not pinpoint an exact connector version when it happened.  

<img width="689" alt="Screenshot 2024-04-15 at 16 45 32" src="https://github.com/airbytehq/airbyte/assets/141125004/d840515b-5986-4c6f-a7ed-ce294b73c96a">

<img width="695" alt="Screenshot 2024-04-15 at 16 54 29" src="https://github.com/airbytehq/airbyte/assets/141125004/ec18097e-8175-4d06-b28f-0127404f5be7">

### Relevant log output

```shell
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.mode: must be a constant value allow, $.mode: does not have a value in the enumeration [allow]
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.mode: must be a constant value prefer, $.mode: does not have a value in the enumeration [prefer]
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.mode: must be a constant value require, $.mode: does not have a value in the enumeration [require]
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.mode: must be a constant value verify-ca, $.mode: does not have a value in the enumeration [verify-ca], $.ca_certificate: is missing but it is required
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.mode: must be a constant value verify-full, $.mode: does not have a value in the enumeration [verify-full], $.ca_certificate: is missing but it is required, $.client_certificate: is missing but it is required, $.client_key: is missing but it is required
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.tunnel_host: is missing but it is required, $.tunnel_port: is missing but it is required, $.tunnel_user: is missing but it is required, $.ssh_key: is missing but it is required, $.tunnel_method: must be a constant value SSH_KEY_AUTH
2024-04-15 13:34:52 INFO i.a.v.j.JsonSchemaValidator(test):121 - JSON schema validation failed.
errors: $.tunnel_host: is missing but it is required, $.tunnel_port: is missing but it is required, $.tunnel_user: is missing but it is required, $.tunnel_user_password: is missing but it is required, $.tunnel_method: must be a constant value SSH_PASSWORD_AUTH
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @IlyaDropit I added the issue to the destination team backlog for further discussion. Can you share the complete sync log? Are you not able to sync or only seeing these WARN msgs?

**Comment by marcosmarxm** [comment]
Also what is your platform version?

**Comment by IlyaDropit** [comment]
> Also what is your platform version?

Hi @marcosmarxm 

Thank you. The platform version is `0.57.1`

Since this is an existing connection, it is working with all our jobs as it used to be. It is only when I try to edit the destination connection (for example, activate `DROP CASCADE`) and save it, it is failing to save it. The messages are coming from the testing step which Airbyte runs before saving it.

I will post here complete sync log tomorrow.

**Comment by IlyaDropit** [comment]
@marcosmarxm 

Sorry, this was a false alarm. Devops help me to reconfigure the destination correctly after the upgrade and now it is working.

Closing it.

**Comment by marcosmarxm** [comment]
No problem at all!
