### ISSUE TITLE
File system abstraction for source/destination

### ISSUE THREAD

**Issue by ajzo90** [airbytehq/airbyte#3736]
## Tell us about the problem you're trying to solve
There are a lot of file system like APIs, for example s3, gcp buckets, sftp, ftp, ftps, hdfs, etc..
Most of the core logic is shared and related to how the airbyte stream is transformed from/to files/blobs. 
For the destination a potential transformation flow probably look like this

```
write: stream => encode (csv,json,avro,parquet,...) => compress (gzip,snappy,zstd,...) => encrypt (...) => store at path
```

and for sources 

```
read: load from path => decrypt => decompress => decode => stream
```

This makes it possible to extract the transformation from the connectors and only let the connectors implement an interface like this.

```
write(path, data)
read(path) => data

```

What is the current consensus around this? 
Does such an abstraction exist already? 
How would a contributor add/modify the transformation chain, for example adding a new serialisation format? 
Perhaps a chain like this

```
source (read from fs) container => 
transform container(s) (decode csv)  => 
worker container => 
transform container(s) (encode to parquet) => 
destination container (write to s3)
```

I suppose such a solution would require that the airbyte streams are separated and that the `read`,`write` calls adds a stream parameter. 

In addintion, functionality around `discovery` is the same (sources could just implement `list(path) => []files`). It's just a list of files/blobs. As a consequence, a shared implementation of for example globbing would be possible.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200399789029139) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
Thanks @ajzo90 !

on the source side we are using `smart_open` which gives us this ability but it doesn't work for listing. So our file source is limited because of that. We have a ticket to track this issue but we didn't get a chance to get to it (https://github.com/airbytehq/airbyte/issues/2512)

on the destination side, we are building the first one and we will likely follow up with a design very similar to what you're suggesting!

Out of curiosity would you be interested to work with us on this for sources?

**Comment by ajzo90** [comment]
I see. Is the plan to explore alternatives to the smart_open down the road? 

Great to see progress on the destination side. Is there an official place to follow the progress? 

I would be open for something. I have certainly fallen short on this task before, but at least I know what not to try, maybe... 
I'm not sure what the next step is. I would like to extract it more into a unix-like interface, but I am not sure how that aligns with your philosophy and priorities. 
What is your suggestion?

**Comment by michel-tricot** [comment]
For the destination here is the current MVP PR for s3 support: https://github.com/airbytehq/airbyte/pull/3672

I think we can create all the composable building blocks in the source connector and sequence them based on the source configuration. So not unix-like per se but composable. WDYT?

**Comment by evantahler** [comment]
This ticket has been quiet for over a year.  I'm closing it for now, but we can reference these ideas later if/when we decide to undertake more code sharing between connectors.
