### ISSUE TITLE
[source-paypal-transaction] connector misses transactions

### ISSUE THREAD

**Issue by anupam45** [airbytehq/airbyte#37385]
### Connector Name

source-paypal-transaction

### Connector Version

2.5.1

### What step the error happened?

During the sync

### Relevant information

We have noticed the Paypal Transaction source connector misses transactions that occur in a specific window.
We know that the transactions occurred in a particular Paypal account takes a few hours to show up via the Paypal API.  The delay is typically between 2-4 hours.   Those transactions are missed when a sync is set on a candence.
Here is an example
We have two streams 1) Balances (with full refresh overwite) 2) Transactions (incremental append). This occurs in Transactions stream 
- Transaction A occurs at **2024-03-27 03:27:50**
- Sync starts at **2024-03-27 05:00**, but transaction A is not yet visible in the API (the API lags a couple of hours); the latest transaction it actually sees is probably around 03:00
- Connector records the sync start time in the connection state
- Next sync starts at **2024-03-28 05:00** and asks PayPal for all transactions newer than the timestamp stored in the state, which is **2024-03-27 05:00**. So even though Transaction A could now be seen from the API, it's missed because the timestamp in the connector state is already ahead of it.

The way we understand under the code [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-paypal-transaction/source_paypal_transaction/manifest.yaml#L80-L97), is that the cursor should be the latest `transaction_updated_date` of transactions found via API which is not the behavior. 

We have noticed this in version `2.2.1` which is our production but I have tested with the same outcome in the latest `2.5.1` version as well.

Our short term mitigation is to set transactions stream to full refresh overwrite and a medium term fix is to fork the Paypal connector and set a lookback window option in the source which isn't present by default in this connector and hoping it works.

### Relevant log output

```shell
2024-03-28 05:01:45 source > Marking stream transactions as STARTED
154
2024-03-28 05:01:45 source > Syncing stream: transactions 
155
2024-03-28 05:01:45 source > Setting state of SourcePaypalTransaction stream to {'transaction_updated_date': '2024-03-28T05:03:25Z'} <The correct behavior should be something like {'transaction_updated_date': '2024-03-28T03:00:00Z'} according to the example described above>
156
2024-03-28 05:01:45 replication-orchestrator > Attempt 0 to update stream status running null:balances
157
2024-03-28 05:01:45 replication-orchestrator > Attempt 0 to stream status started null:transactions
158
2024-03-28 05:01:46 source > Read 0 records from transactions stream
159
2024-03-28 05:01:46 source > Marking stream transactions as STOPPED
160
2024-03-28 05:01:46 source > Finished syncing transactions
161
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This can be a complex problem @anupam45 thanks for reporting. Maybe the solution is to add some window to every run to ingest previous data to ensure it read all records. I added the issue to the team backlog to future resolution.

**Comment by bazarnov** [comment]
That's because the source-paypal-transactions still uses the old CDK low-code version, which uses the stream_slice as a cursor, instead of the `latest_record` observed from data. The point is to update the CDK version the source uses and fix the issues that come up with this change.

**Comment by anupam45** [comment]
@marcosmarxm @bazarnov, thank you for responses.  I have tested by forking the Paypal Transactions connector and added a lookback window in the manifest yaml file.  That does pick up the missing delayed transactions.  
Is there an timeline for this fix?  I am trying to weight my tradeoffs between using the custom connector or waiting for the release.
