### ISSUE TITLE
All syncs fail with "Check failed because of an internal error" since upgrading to 0.57.3

### ISSUE THREAD

**Issue by qmoret** [airbytehq/airbyte#37401]
### Topic

Issue with syncs 

### Relevant information

We upgraded from 0.51 to 0.57.3 and all our connections are failing now.

Destination is Postgres 2.0.9.

Can you please support ?

**Comment by qmoret** [comment]
Fixed with https://airbytehq.slack.com/archives/C021JANJ6TY/p1712852786264019?thread_ts=1711356903.827139&cid=C021JANJ6TY

**Comment by alrikvidal** [comment]
Hello,

I have the same probleme but cant access to slack
