### ISSUE TITLE
source-gitlab Pipeline stream not working since last upgrade

### ISSUE THREAD

**Issue by hugovandernotte** [airbytehq/airbyte#37436]
### Connector Name

source-gitlab

### Connector Version

4.0.0

### What step the error happened?

During the sync

### Relevant information

Since the upgrade was forced (I am using Airbyte cloud) to this new version of the source-gitlab, the pipelines stream does not work anymore and raise a credentials issue exception.

Everything was working well before gitlab was migrated to low-code, I regenerated new tokens, added all permissions, did the api calls on my end and everything work well, but the Airbyte sync always fail...

I noticed that in the mr you merged, in the stream.py file that was deleted, it was mentioned that Gitlab may return a 403 in case the pipeline feature was not activated on a project, that may come from that?

<img width="1131" alt="Screenshot 2024-04-19 at 16 15 49" src="https://github.com/airbytehq/airbyte/assets/20269780/1bf93dc5-134f-4233-8760-782fa1c01b4b">
<img width="923" alt="Screenshot 2024-04-19 at 16 20 15" src="https://github.com/airbytehq/airbyte/assets/20269780/8d9cc27c-736b-4473-b5df-65f910e80333">

### Contribute

- [ ] Yes, I want to contribute

**Comment by askarpets** [comment]
Hello @hugovandernotte,
The error code of `403` is still covered in the low-code implementation and it is safely ignored by the connector during a sync. It looks like a `500` code is returned from Gitlab in your case.
Could you please share either the connection ID or your credentials so we can investigate this case?
Thank you!

**Comment by hugovandernotte** [comment]
Thanks a lot for you answer, here is my connection_id (using airbyte cloud): e13edf5b-4f47-41f0-a22e-ccd6e98ec6bc

I checked that pipelines were activated on all projects and this is the case, so I do not know what else to check on my side
