### ISSUE TITLE
DOCKER COMPOSE : Could not find image: airbyte/

### ISSUE THREAD

**Issue by alrikvidal** [airbytehq/airbyte#37433]
### Platform Version

0.57.3

### What step the error happened?

Other

### Relevant information

Hello,

I encounter a consistent issue when initiating Airbyte using the command docker-compose up. Each attempt results in job failures, accompanied by the following error messages:

2024-04-18 22:21:45 platform > airbyte/source-postgres:3.3.18 not found locally. Attempting to pull the image...
2024-04-18 22:21:45 platform > Image does not exist.
2024-04-18 22:21:45 platform > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/source-postgres:3.3.18

However, when I start Airbyte using the script ./run-ab-platform.sh -b, everything functions correctly. This solution persists even after server restarts. To resume normal operation post-restart, I need to execute docker compose down followed by ./run-ab-platform.sh -b.

Could you please assist in resolving this Docker-related issue?

Thank you.

**Comment by natikgadzhi** [comment]
Huh, this doesn't sound right, one sec. I'm not sure why 3.3.18 doesn't show up for you, but latest is 3.3.26 here: https://hub.docker.com/layers/airbyte/source-postgres/3.3.26/images/sha256-e07ddc1311657625bd774381577dffb0391a86095e864d960d7db41b29e98dea?context=explore — can you restart your cluster so it picks up the latest version and try again?

**Comment by alrikvidal** [comment]
What do you mean by restarting the cluster? My Airbyte instance is installed on an Ubuntu server via the installation script.
And all source connectors are up to date

**Comment by franc-felipe** [comment]
Hello, I have the same problem. 
Did you find a solution?

2024-10-22 12:02:31 [46mplatform[0m > Image does not exist.
2024-10-22 12:02:31 [46mplatform[0m > Unexpected error while checking connection: 
io.airbyte.workers.exception.WorkerException: Could not find image: airbyte/destination-postgres:2.0.15
