### ISSUE TITLE
Failed to connect to raw.githubusercontent.com

### ISSUE THREAD

**Issue by karonluo** [airbytehq/airbyte#37460]
### Topic

Deploy CURL

### Relevant information

root@suruitong-vm:~/gitee/airbyte# ./run-ab-platform.sh 

 █████╗ ██╗██████╗ ██████╗ ██╗   ██╗████████╗███████╗
██╔══██╗██║██╔══██╗██╔══██╗╚██╗ ██╔╝╚══██╔══╝██╔════╝
███████║██║██████╔╝██████╔╝ ╚████╔╝    ██║   █████╗  
██╔══██║██║██╔══██╗██╔══██╗  ╚██╔╝     ██║   ██╔══╝  
██║  ██║██║██║  ██║██████╔╝   ██║      ██║   ███████╗
╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝    ╚═╝      ╚═╝   ╚══════╝
                                            Move Data

found docker-compose.yaml locally!
found docker-compose.debug.yaml locally!
found .env locally!
Downloading .env.dev
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 18 ms: Connection refused

**Comment by karonluo** [comment]
I access url: https://raw.githubusercontent.com/airbytehq/airbyte-platform/v0.57.3/ on browser , the web return : 403

**Comment by marcosmarxm** [comment]
This is likely to a be a problem in your network @karonluo can you try again. I was able to run the command in my laptop without any issues.

**Comment by marcosmarxm** [comment]
Closed as inactive and lack of information.
