### ISSUE TITLE
WorkerException: Could not find image: airbyte/source-declarative-manifest:0.79.1

### ISSUE THREAD

**Issue by shrey-0407** [airbytehq/airbyte#37461]
### Connector Name

custom connector

### Connector Version

newer

### What step the error happened?

None

### Relevant information

![image](https://github.com/airbytehq/airbyte/assets/72700552/063932a6-273a-46e0-88f3-091601f0d210)

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
You can check [here](https://hub.docker.com/layers/airbyte/source-declarative-manifest/0.79.1/images/sha256-a2da28a8c4e5c5fab63842067659d71ff4cada5b787ef19c558f4ba7092649bd?context=explore) the image is in Dockerhub.
Are you still experiencing the issue?
