### ISSUE TITLE
[destination-snowflake] Add AWS PrivateLink Support

### ISSUE THREAD

**Issue by joeybenamy** [airbytehq/airbyte#37510]
### Connector Name

destination-snowflake

### Connector Version

3.7.0

### What step the error happened?

Configuring a new connector

### Relevant information

We would like to use AWS PrivateLink with Snowflake, but the Snowflake connector only supports hosts that use the `snowflakecomputing.com` domain.  For AWS PrivateLink, we would use our own DNS or an AWS hostname (`amazonaws.com`).  Unfortunately we cannot proceed with adopting AWS PrivateLink for Snowflake if the Airbyte connector does not support custom hosts.

### Contribute

- [x] Yes, I want to contribute

**Comment by joeybenamy** [comment]
Not relevant anymore.  We can do this with private DNS

**Comment by Moreno-Yassine** [comment]
Hello @joeybenamy ,
Could you please share your solution (DNS records that you've implemented) to solve this issue ?

I'm having the same bit of trouble with Azure Private Link and Airbyte OSS

**Comment by joeybenamy** [comment]
> Hello @joeybenamy , Could you please share your solution (DNS records that you've implemented) to solve this issue ?
> 
> I'm having the same bit of trouble with Azure Private Link and Airbyte OSS

Sure.  However, we are using AWS not Azure so it might be a little different.  Once you work with Snowflake support to configure PrivateLink for your Snowflake tenant, you can run this Snowflake query `SELECT KEY, VALUE FROM TABLE(FLATTEN(input=>parse_json(SYSTEM$GET_PRIVATELINK_CONFIG())));` to get your config.  Take the privatelink-account-url value and create a CNAME in your internal/private DNS to point that value to the privatelink endpoint in your VPC.  So if your PrivateLink Account URL is `mgbXXXXX.us-east-1.privatelink.snowflakecomputing.com` then in the private DNS for your VPC you would create a private DNS zone for `privatelink.snowflakecomputing.com` and create a CNAME record for `mgbXXXXX.us-east-1.privatelink.snowflakecomputing.com` with a value of your VPC endpoint for PrivateLink.  In AWS this looks like `vpce-XXX-YYY.us-east-1.vpce.amazonaws.com`.  Then in Airbyte you just use the PrivateLink Account URL `mgbXXXXX.us-east-1.privatelink.snowflakecomputing.com`.  Your Airbyte OSS must be able to use the private DNS zone so that `mgbXXXXX.us-east-1.privatelink.snowflakecomputing.com`  resolves to your VPC endpoint.

**Comment by Moreno-Yassine** [comment]
Thanks a lot @joeybenamy , your insight was helpful to setup a Private DNS Zone on Azure and Airbyte is working like a charm !

**Comment by joeybenamy** [comment]
> Thanks a lot @joeybenamy , your insight was helpful to setup a Private DNS Zone on Azure and Airbyte is working like a charm !

I am really glad to hear that you got it working.  It took quite a bit of back and forth with Snowflake support and AWS support to find the solution, but it makes sense once you see it working!
