### ISSUE TITLE
Source Mysql->Typesense imports timestamps as strings

### ISSUE THREAD

**Issue by TimFung93** [airbytehq/airbyte#37560]
### Connector Name

destination-mssql

### Connector Version

0.2.63

### What step the error happened?

During the sync

### Relevant information

the schema that gets generated when airbyte syncs auto generates for dates to be strings. However according to the [typesense docs ](https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html#dates-times)there is no native datetime type so it would need to be converted to int64

![Screenshot 2024-04-24 at 7 45 30 PM](https://github.com/airbytehq/airbyte/assets/22329638/a65fa1a4-4a91-4cda-b27b-b386bbd751cb)

![Screenshot 2024-04-24 at 7 44 37 PM](https://github.com/airbytehq/airbyte/assets/22329638/3e6f978a-d309-4baf-98fa-266e8f40d574)

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed as the issue title doesn't correspond with connector described in the body text.
