### ISSUE TITLE
MySQL CDC not fetching records for Amazon Aurora

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#3756]
I synced MySQL Aurora instance in CDC replication mode. No records were fetched

Reason : 
We use debezium to fetch records from MySQL. We have a check in place [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/DebeziumRecordIterator.java#L82) which states that if for 5 seconds debezium didn't return any record, shutdown the debezium engine, connector and finish the sync. 

Turns out 5 seconds is not enough specially when the sync runs for the first time. When the sync runs for the first time, debezium takes a snapshot of the tables. This can take a while and for 5 seconds debezium doesnt return records. Cause of that Airbyte shuts down debezium engine and the sync finishes without fetching any data.

This was reported here as well https://airbytehq.slack.com/archives/C01MFR03D5W/p1622156351346000

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200403831585309) by [Unito](https://www.unito.io)

**Comment by tuanchris** [comment]
I'm having the same issue with MySQL Aurora. `Incremental - Append` mode doesn't work. Full refreshes do, however.

**Comment by subodh1810** [comment]
@tuanchris I just merged the fix for this. Upgrade your mysql docker image to get the changes.

**Comment by tuanchris** [comment]
Thanks @subodh1810, some other issue came up with normalization. I will create a new issue for that.
