### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by liudican** [airbytehq/airbyte#3758]
git clone https://github.com/airbytehq/airbyte.git
cd airbyte
docker-compose up

docker ps -a

e316dc849457        temporalio/auto-setup:1.7.0      "/entrypoint.sh /bin…"   About a minute ago   Up 36 seconds               6933-6935/tcp, 6939/tcp, 7234-7235/tcp, 7239/tcp, 0.0.0.0:7233->7233/tcp                                                                           airbyte-temporal
25ac21551261        airbyte/seed:0.24.4-alpha        "/bin/sh"                About a minute ago   Exited (0) 39 seconds ago                                                                                                                                                      airbyte-data-seed
b58a2cb9460e        airbyte/scheduler:0.24.4-alpha   "/bin/bash -c './wai…"   About a minute ago   Up 37 seconds                                                                                                                                                                  airbyte-scheduler
6d1ea5299af6        airbyte/init:0.24.4-alpha        "/bin/sh -c './scrip…"   About a minute ago   Exited (0) 36 seconds ago                                                                                                                                                      init
e40b80984bcf        airbyte/server:0.24.4-alpha      "/bin/bash -c './wai…"   About a minute ago   Up 39 seconds               8000/tcp, 0.0.0.0:8001->8001/tcp                                                                                                                   airbyte-server
206862058cb3        airbyte/db:0.24.4-alpha

docker logs 6d1ea5299af6
MOUNT: /local_parent
ROOT_PARENT: /tmp
ROOT: /tmp/airbyte_local
MOUNT_ROOT: /local_parent//airbyte_local

run logs:
init                | MOUNT: /local_parent
init                | ROOT_PARENT: /tmp
init                | ROOT: /tmp/airbyte_local
init                | MOUNT_ROOT: /local_parent//airbyte_local
init                | MOUNT: /local_parent
init                | ROOT_PARENT: /tmp
init                | ROOT: /tmp/airbyte_local
init                | MOUNT_ROOT: /local_parent//airbyte_local
init exited with code 0
and :
airbyte-temporal    | {"level":"info","ts":"2021-05-31T10:22:18.708Z","msg":"none","service":"matching","component":"matching-engine","lifecycle":"Starting","wf-task-queue-name":"/_sys/temporal-archival-tq/3","wf-task-queue-type":"Workflow","logging-call-at":"matchingEngine.go:188"}
airbyte-temporal    | {"level":"info","ts":"2021-05-31T10:22:18.726Z","msg":"none","service":"matching","component":"matching-engine","lifecycle":"Started","wf-task-queue-name":"/_sys/temporal-archival-tq/3","wf-task-queue-type":"Workflow","logging-call-at":"matchingEngine.go:202"}
airbyte-data-seed exited with code 0

please help me! thank you

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200403899784250) by [Unito](https://www.unito.io)

**Comment by liudican** [comment]
![image](https://user-images.githubusercontent.com/54348696/120180699-aa8c1480-c23e-11eb-832f-49f27b7491de.png)

**Comment by marcosmarxm** [comment]
@liudican is possible for you to access `localhost:8000`?

**Comment by marcosmarxm** [comment]
![image](https://user-images.githubusercontent.com/5154322/120222747-d6939f80-c216-11eb-9eb2-5a685f4ba418.png)

**Comment by cgardens** [comment]
@liudican hi! I'm going to close this due to inactivity. Feel free to reach back out / reopen if you're still running into problems.
