### ISSUE TITLE
Pipedrive connector

### ISSUE THREAD

**Issue by mcouto-sossego** [airbytehq/airbyte#3759]
## Tell us about the new connector you’d like to have
* Which source and which destination?

From Pipedrive to Anywhere.

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

N/A

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.

Tipically sales team.

* How often do you want to run syncs?

Hourly or Daily.

* If this is an API source connector, which entities/endpoints do you need supported?

Seems like it is already implemented in https://github.com/singer-io/tap-pipedrive

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

singer.io

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200404018830312) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
Thanks @mcouto-sossego #3321 already request this source.
I'll close this as duplicated but transfer the info to that issue.
