### ISSUE TITLE
Getting inconsistent decimal values in shopify orders

### ISSUE THREAD

**Issue by meyerovb** [airbytehq/airbyte#37645]
### Connector Name

source-shopify

### Connector Version

1.1.7

### What step the error happened?

None

### Relevant information

For some reason randomly the decimal values are being truncated off total_line_items_price, some of the rows have decimals though but I checked the api and it has the decimals there.

### Relevant log output

```shell
select total_line_items_price,
       total_line_items_price_set,
       total_line_items_price_set.shop_money.amount
from airbyte_shopify.orders 
where total_line_items_price <> total_line_items_price_set.shop_money.amount
limit 10

If you did this it doesn't return any rows:
where total_line_items_price::int <> total_line_items_price_set.shop_money.amount::int
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by meyerovb** [comment]
DAMNIT its also happening to current_subtotal_price, no wonder clients been so pissed

**Comment by marcosmarxm** [comment]
@meyerovb The version you're using is not the latest. I strongly recommend to you upgrade to latest as it fixes a lot of bugs. Some bugs that skip records.

**Comment by marcosmarxm** [comment]
Closed as the issue reported a problem with outdated version of the connector.
