### ISSUE TITLE
ISO 8601 outgoing date format issue

### ISSUE THREAD

**Issue by argylepayments** [airbytehq/airbyte#37643]
### Topic

Outgoing time encoding

### Relevant information

I am trying to get the outgoing date to be formatted like this "2013-10-20T19:20:30+01:00" which is standard ISO 8601. This is the correct python formatting code -- %Y-%m-%dT%H:%M:%S%:z. But the date is being encoding like this in the query string -- 2014-04-24T00%3A00%3A00%25%3Az. It is not encoding the timezone offset correctly.

**Comment by marcosmarxm** [comment]
@argylepayments can you provide more information of what are you trying to do, what steps you made, etc?
