### ISSUE TITLE
CDK: implement custom logging formatter to obfuscate secrets

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#3764]
## Tell us about the problem you're trying to solve
Currently, we have multiple ways to expose credentials in logs (info, exceptions, tests)

## Describe the solution you’d like
The only real way to secure credentials is to control logging output with a logging Formatter attached to the root logger.
This handler will get the connector's config and will replace all occurrence of values from fields marked as secret.

```python
class SecureFormatter(logging.Formatter):
    """ Custom formatter to prevent secrets leaking
    """
    def format(self, record: 'logging.LogRecord') -> str:
        msg = super().format(record)
        for secret in secrets:
            msg = msg.replace(secret, '***')
        return msg
```

## Describe the alternative you’ve considered or used
do manually

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200405283415880) by [Unito](https://www.unito.io)

**Comment by eliziario** [comment]
Create a simple log formatter that takes a bag of strings that are likely to precede sensitive information with the most usual variations like pass, password, secretkey, accesskey and so on. 

Store it as suitable class level attribute data structure with fast matching like a trie or even a simple set. 

For each log line, tokenize it using any non-alphanumeric char as delimiters, but ignore hyphens if not surround by spacem, so secret-key becomes after tokenization "secretkey"

Check tokens and for every matching token, obfuscate the next token with a placeholder char.
