### ISSUE TITLE
Replace custom multitple authenticators with Selective Authenticator

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#37658]
## What

Some connectors are still implementing multiple authenticators using a custom component. They should be updated to use a SelectiveAuthenticator.

Connector updates should not require a a breaking change. This might require a config migration

## Acceptance criteria
- [x] All connectors requiring multiple authenticators use a SelectiveAuthenticator

**Comment by tolik0** [comment]
Fixes:
- [ ] [Source Auth0](https://github.com/airbytehq/airbyte/pull/37770)
- [ ] [Source Square](https://github.com/airbytehq/airbyte/pull/37800)
