### ISSUE TITLE
[Roadmap] Show Sync Progress in the UI

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#37669]
In the UI, we'll show you how far your sync has progressed - how much data has been read and written. This is especially helpful for longer syncs moving lots of data!

This will be available to all Airbyte products.

**Comment by teallarson** [comment]
Sync progress has been released in [v0.63.3](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.63.3)

**Comment by sowla** [comment]
In case it's useful for any other users, in our experience, we only saw stream-level details after syncs were finished. We didn't really see progress **during** syncs until v.0.63.5, which seems to fit this [slack announcement](https://airbytehq.slack.com/archives/C023W76QGE4/p1722009229803889):
> The progress of active syncs is now reported every 10 seconds for increased visibility and tracking (available in OSS v.0.63.5)
