### ISSUE TITLE
[source-mongodb] Sync mode drop down isn't working

### ISSUE THREAD

**Issue by SridharCR** [airbytehq/airbyte#37741]
### Connector Name

source-mongodb

### Connector Version

1.3.8

### What step the error happened?

Configuring a new connector

### Relevant information

**Airbyte version: 0.58.0**
**Mode: Both docker compose and abctl**
**Steps to reproduce:**
1. Setup a proper source mongodb.
2. Setup a proper destination Tidb.
3. While configuring the connections, after the schema fetch, the user is unable to select the sync mode.

![Screenshot 2024-05-01 at 8 45 30 PM](https://github.com/airbytehq/airbyte/assets/22750196/ae328fce-8038-4ed0-940c-4f311a702545)

4. I can still able to create a connection which will obviously fail, giving below error.
![Screenshot 2024-05-01 at 8 46 33 PM](https://github.com/airbytehq/airbyte/assets/22750196/d72f963c-da01-4027-ba8d-4217cd869637)

**Things to do:**
1. Fix sync mode drop down
2. Add a validation, that connection can't be created when sync mode is not given

### Relevant log output

```shell
Log trace for creating the connection without sync mode

// HttpError
{
  "i18nKey": "errors.http.internalServerError",
  "i18nParams": {
    "status": 500
  },
  "name": "HttpError",
  "requestId": "2b48cezTJMGQ6oA3733nmT",
  "request": {
    "url": "/api/v1/web_backend/connections/get",
    "method": "post",
    "headers": {
      "Content-Type": "application/json"
    },
    "data": {
      "connectionId": "d426c365-6575-4b39-844d-eb92cbf97c24",
      "withRefreshedCatalog": false
    }
  },
  "status": 500,
  "response": {
    "message": "Internal Server Error: Index 0 out of bounds for length 0",
```

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Can you try connecting to a different, preferably certified, destination?

**Comment by marcosmarxm** [comment]
Closed due to lack of response and inability to recreate.
