### ISSUE TITLE
Document setting interactive_timeout and wait_timeout for MySQL CDC

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#3775]
We use debezium for MySQL CDC. 

While we have not observed any instances of this but its mentioned in the debezium docs https://debezium.io/documentation/reference/1.4/connectors/mysql.html#mysql-session-timeouts

```
When an initial consistent snapshot is made for large databases, your established connection could timeout while the tables are being read. You can prevent this behavior by configuring interactive_timeout and wait_timeout in your MySQL configuration file.
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200412685585149) by [Unito](https://www.unito.io)

**Comment by grishick** [comment]
We have not seen this happen yet, but we should update the documentation to reflect this.

**Comment by prateekmukhedkar** [comment]
Defaults are:
`interactive_timeout` : 28800 seconds (8 hours)
`wait_timeout` : 28800 seconds (8 hours)

Reference: [MySQL’s documentation](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout)

@subodh1810 for the initial sync with CDC what would we recommend to customers? Or are defaults OK?

**Comment by akashkulk** [comment]
We no longer use debezium for initial snapshots, closing
