### ISSUE TITLE
Acceptance test: accept state for dependent endpoints with parent id

### ISSUE THREAD

**Issue by vovavovavovavova** [airbytehq/airbyte#3777]
## Tell us about the problem you're trying to solve
Currently acceptance tests supports the following state:
`{cursor_field: value}`

Sometimes we have depedent endpoints like `path/some_id/something` . We need to store the state for each `some_id`, not the overall state.
Example:

```
{
  "<campaign_id>": {cursor_field: "<your_datetime>"},
  "<campaign_id2>": {cursor_field: "<your_datetime>"},
  "<campaign_id3>": {cursor_field: "<your_datetime>"},
}
```

Now acceptance test will fail.

## Additional context
Desired behaviour: I can have a complex state, test will be passed on this construction.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200412782725525) by [Unito](https://www.unito.io)

**Comment by girarda** [comment]
Closing because I haven't heard about substreams causing CATs to fail
