### ISSUE TITLE
Split ConnectorSpecification in the Airbyte Protocol

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3778]
## Tell us about the problem you're trying to solve
In the Airbyte protocol, we define a `ConnectorSpecification` object that contains extra properties for _ALL_ connectors.

## Describe the solution you’d like
Split ConnectorSpecification into general vs connector type sections of properties so we can have different objects for either sources or destinations

## Describe the alternative you’ve considered or used
Keep as it is but then if we define destination-specific properties, these will be applied to sources too and wouldn't make sense. For example `supportsNormalization` is a destination-specific boolean, not a source one. With the current implementation, we could inadvertently define a source that supports normalization...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200412686140702) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
closed as no longer relevant. this info should move to the actor definition.
