### ISSUE TITLE
Add documentation link or improve UX on sync mode (connection page)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3783]
## Tell us about the problem you're trying to solve
A user doesn't have full knowledge of sync modes and selects not the proper one.
![image](https://user-images.githubusercontent.com/5154322/120340241-339d5d00-c2cc-11eb-8018-38c38aeea391.png)

## Describe the solution you’d like
I think can be a great idea to add the link to sync mode documentation when users are setting this. 
Maybe only hyperlink the column name **Sync Setting** or we could add tooltip when mouse over.

## Describe the alternative you’ve considered or used
Going to docs manually and read about it.

## Are you willing to submit a PR?

Your answer

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200412830749380) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
added some more context in https://github.com/airbytehq/airbyte/issues/4085

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
Closing in favor of #14340
