### ISSUE TITLE
[helm] Storage type local is not working 

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#37836]
### Helm Chart Version

0.64.354

### What step the error happened?

None

### Relevant information

Hello,
   i would like to disable external storage and donot want to install minio server hence,  I tried with local however, helm install failed with state type empty error

 storage:
      type: "local"

Ask:
   Allow to disable minio and s3 all together .  logs are stored in new relic using fluent bit hence, we donot need to airbyte logs.

**Comment by marcosmarxm** [comment]
Hello @sivankumar86 I think this is something the team is planning for near future. So stay tuned in future releases of the Helm Chart.

**Comment by octavia-squidington-iii** [comment]
This issue was closed because it has been inactive for 20 days since being marked as stale.
