### ISSUE TITLE
current dev version fails when clicking on connection

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3793]
## Steps to Reproduce
1. Start fresh airbyte 
1. Configure sync
1. Try to go to the connections page and click on the connections

This won't work; it jumps and redirects until you reload the page.

## Severity of the bug for you
Critical 

It makes it impossible to access a connection without reloading the page. It isn't obvious that a reload is necessary and will feel very buggy to users trying us out.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200413327904339) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
I didn't check if it was in the previous release or not.

**Comment by jrhizor** [comment]
It's actually doing it on the current production release `0.24.4-alpha`.

Logs:
```
airbyte-server      | 2021-06-02 05:26:29 ERROR i.a.s.RequestLogger(filter):105 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.19.0.1 POST 400 /api/v1/source_definitions/get - {}
```

Failing request as curl:
```
curl 'http://localhost:8001/api/v1/source_definitions/get' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:8000' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:8000/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw '{}' \
  --compressed
```

Screenshot in UI after clicking (first is adblock, others are due to this error):
![Screen Shot 2021-06-01 at 10 28 30 PM](https://user-images.githubusercontent.com/120362/120428561-b6ec9c00-c328-11eb-980f-ca5dd55d6168.png)

**Comment by jrhizor** [comment]
Since this works after reloading the page and because the request being made doesn't contain the correct payload, I believe this is a frontend issue.

@Jamakase any thoughts?

**Comment by Jamakase** [comment]
@jrhizor I asked about same issue yesterday in slack:

'''Sometimes I receive error
{"message":"The received object did not pass validation","details":"property: getSourceDefinition.arg0.sourceDefinitionId message: must not be null invalid value: null"}
 for the request Request URL: http://localhost:8001/api/v1/source_definitions/get

airbyte-server      | 2021-06-01 17:56:08 ERROR i.a.s.RequestLogger(filter):105 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.26.0.1 POST 400 /api/v1/source_definitions/get - {}
Does anybody have faced same issue? I am using hubspot -> pg'''

After I reload the page - same request passes. Does 'get - {}' from the logs above means that server somehow received empty id?

**Comment by jrhizor** [comment]
Ah I missed that, sorry. 

Yes, the backend log shows it is sending an empty JSON object in the request. The `Failing request as curl:` is the request being made copied as a curl which has `{}` as the payload, so the frontend is making a request with an empty json payload.

I was doing exchangerates -> local csv, so it doesn't look connector-dependent. 

I've been able to replicate this reliably (with different connectors) on `dev` and the latest release (haven't checked on earlier releases).

It isn't clear to me what `source_definitions` should be looking up in the first place. After I reload, `source_definitions` isn't requested when accessing the connections page or the page for a specific connector.

**Comment by Jamakase** [comment]
Something strange is happening and I can't reproduce it anymore.

Just to clarify where we get this id from - we call `web_backend/connections/get` which returns also source. Then we use `connection.source.sourceDefinitionId` to get sourceDefinition by id from source, but somehow it was not present in the response. Is that possible at all?
