### ISSUE TITLE
Source Postgres: create comprehensive data type tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3795]
## Tell us about the problem you're trying to solve
Same as https://github.com/airbytehq/airbyte/issues/3562 for Postgres
postgres version: postgres:13-alpine
https://www.postgresql.org/docs/13/datatype.html#:~:text=The%20following%20types%20(or%20spellings,without%20time%20zone)%2C%20xml%20.

TODO:

1. Read documentation and prepare tricky use cases for each type of data. 
2. Implement comprehensive test. 
3. Prepare pull request, pass all checks. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200413427027728) by [Unito](https://www.unito.io)

**Comment by etsybaev** [comment]
|**Data Type** |**Example values**|**Comment** | **Common test result** | **CDC test result** |
|----|----|----|----|----|----|
| bigint |  -9223372036854775808", "9223372036854775807", "0", "null" |  | ok | ok |
| bigserial  | "1", "9223372036854775807", "0", "-9223372036854775808" |  | ok | ok |
| serial | "1", "2147483647", "0", "-2147483647" |  | ok | ok |
| smallserial |  "1", "32767", "0", "-32767" |  | ok | ok |
