### ISSUE TITLE
source Oracle DB: Create comprehensive data type tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3796]
## Tell us about the problem you're trying to solve
Same as https://github.com/airbytehq/airbyte/issues/3562 but for Oracle

Version for datatypes 11g of the dialect.
https://docs.oracle.com/cd/E11882_01/server.112/e41085/sqlqr06002.htm#SQLQR959

TODO:

1. Read documentation and prepare tricky use cases for each type of data. 
2. Implement comprehensive test. 
3. Prepare pull request, pass all checks. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200413427486564) by [Unito](https://www.unito.io)

**Comment by heade** [comment]
[Oracle Built-In Data Types](https://docs.oracle.com/cd/E11882_01/server.112/e41085/sqlqr06002.htm#SQLQR959
)
Data Type | Category of edge case | Example values | Comment | Common test result | 
-- | -- | -- | -- | -- | 
char | null | `null`, `a`, `ab`, `abc` | &nbsp; | ok |
varchar2 | character set | `null`, `тест` | &nbsp; | ok |
varchar2 | character set | `⚡ test ��` | &nbsp; | ok |
varchar2 | character set | `{\|}!\"#$%&'()*+,-./:;<=>?@[]^_~` | &nbsp; | ok |
varchar2 | character set | `chr(33) \\|\\| chr(34) \\|\\| chr(35) \\|\\| chr(36) \\|\\| chr(37) \\|\\| chr(38) \\|\\| chr(39) \\|\\| chr(40) \\|\\| chr(41)` | !"#$%&'() | ok |
nvarchar2 | character set | `null`, `テスト` | &nbsp; | ok |
number | edge values | `null`, `1`, `123.45` | Magnitude 1E-130 .. 10E125 | ok |
number | edge values | `123.89` | NUMBER(6,-2): `100.0` | ok |
float | null | `126.45`, `126` |  | ok |
float | null | `1.34`, `126.45` | float(5): `1.3`, `130.0`  | ok |
binary_float | edge values | `1.17549E-38f`, `3.40282347E+038f`, `BINARY_FLOAT_INFINITY` |  | ok |
binary_double | edge values | `2.22507485850720E-308`, `1.79769313486231E+308`, `BINARY_DOUBLE_INFINITY` |  | ok |
date | zero date | 0000-00-00,&nbsp;2021-00-00,&nbsp;2021-05-00 | | ok |
date | edge values | `4700-01-01 00:00:00 BC`, `9999-12-31 23:59:59` | | ok |
timestamp | null | `2020-06-10 06:14:00.742000000` | | ok |
timestamp | null | `21-FEB-2009 18:00:00 EST`, `21-FEB-2009 18:00:00 -5:00` |timestamp with time zone | ok |
interval | null | `INTERVAL '10-2' YEAR TO MONTH`, `INTERVAL '9' MONTH` |interval year to month | ok |
blob | extreem value | `utl_raw.cast_to_raw('some content here')` |Binary Large Object: (4 Gigabytes - 1) * (database block size) | ok |
clob | extreem value | `utl_raw.cast_to_raw('some content here')` |Character Large Object: (4 Gigabytes - 1) * (database block size) | ok |
raw | edge values | `utl_raw.cast_to_raw('some content here')` |Maximum size is 2000 bytes | ok |
