### ISSUE TITLE
Support for newer version of Postgres 

### ISSUE THREAD

**Issue by czomo** [airbytehq/airbyte#38182]
### Topic

postgres platform 13 database

### Relevant information

>  Currently, Airbyte requires connection to a Postgres 13 instance.

As docs states airbyte platform support only postgres13 as database backend. EOL for postgres 13 is `13 Nov 2025(Ends in 1 year and 6 months)` https://endoflife.date/postgresql 

Are there any plans for work on this field?

**Comment by mathetes87** [comment]
It would be great to know if newer versions are already supported. I've been trying to use neon.tech as the database and they only support versions 14 to 16. I was facing a number of errors originating from the `airbyte-temporal` container in a vanilla database and I assumed it was due to the postgres version!

**Comment by mathetes87** [comment]
Please, any information on this? @bgroff

**Comment by hongbo-miao** [comment]
It actually supports well. I tested with latest Postgres 16.3 have opened the pull request and removed the limitation https://github.com/airbytehq/airbyte/pull/39510

I succeed with a clean Postgres 16.3, I have published all deployment codes using Terraform at https://github.com/hongbo-miao/hongbomiao.com/issues/17463#issuecomment-2180242019 :smiley:
(And all issues I met and solutions as well in first comment :wink:)

**Comment by mathetes87** [comment]
That is super useful to know! Thanks!

**Comment by joeybenamy** [comment]
Looking for info on Postgres 17 support.

**Comment by marcosmarxm** [comment]
This discussion was solved as Airbyte now support Postgres+13. I created an issue to improve the documentation to inform min/max version supported as external database: https://github.com/airbytehq/airbyte/issues/48542 

@joeybenamy please add your comment there.
