### ISSUE TITLE
split "core" and "connectors" build in CI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3828]
## Tell us about the problem you're trying to solve
* brace yourself the naming here is a big ambiguous with previously existing naming conventions.
* we have a full build and a shortened build ("CORE_ONLY"). the latter still depends on connectors (for at least formatting). 

## Describe the solution you’d like
* my goal is to be able to push a change to the core platform and have only direct dependencies of the core platform are built. _nothing_ to do with connectors. this is to decrease false negatives in build failures (which are relatively frequent).

heads up sherifnada

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200418295457753) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment]
As long as we can always build everything from a simple gradle command, i am all for it!

**Comment by jrhizor** [comment]
How are you planning on handling normalization? I think that's the only "core" thing that's Python (and 99% of our false negatives are Python related).
