### ISSUE TITLE
Request for community feedback: Amazon Kinesis Destination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3830]
## Tell us about the new connector you’d like to have
I would like to be able to push data to Amazon kinesis. 

## Describe the alternative you are considering or using

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200418372600279) by [Unito](https://www.unito.io)

**Comment by noah-goodrich** [comment]
Why do we need to treat this as being separate from Kafka? https://github.com/airbytehq/airbyte/issues/3830

If we can just configure where our Kafka server will be, I would think we can mostly just point to KInesis instead.
