### ISSUE TITLE
New sources should run integration tests using normalization enabled

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3838]
## Tell us about the problem you're trying to solve
Check if catalog.json is compatible with the dynamic dbt normalization process.

## Describe the solution you’d like
Run a sync using postgres as destination.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Your answer

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200419175595853) by [Unito](https://www.unito.io)

**Comment by bleonard** [comment]
Old issue. Closing unless @evantahler wants to look into this.
