### ISSUE TITLE
Source MySQL: unsigned numeric values larger than signed integer size break connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3840]
## Expected Behavior
I expect Airbyte syncs to succeed when replicating a MySQL table which contains an unsigned int column in which some of the values are larger than 2^32-1. 

Slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1622696364083700

## Current Behavior
The sync breaks as reported by a user. They sent the following logs: 

```
2021-06-03 05:13:13 ERROR (/tmp/workspace/59/2) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.RuntimeException: java.sql.SQLDataException: Value '4176160650' is outside of valid range for type java.lang.Integer
```

## Suggestions for solution
If we can identify inside the connector if the column is unsigned then we should use `Long` for unsigned and `Integer` otherwise. 

If we can't identify if the column is unsigned then we should always use long. 

## Steps to Reproduce
1. Create a table in a mysql db with column unsigned int 
1. insert a row with value 3428724653
1. run a sync from airbyte to any destination
1. :bomb: 

## Severity of the bug for you
High -- preventing user from using Airbyte

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200419820358096) by [Unito](https://www.unito.io)

**Comment by DoNotPanicUA** [comment]
Hi @sherifnada,
I need you advice here. 
This case is unexpected not only for us, but also for [the JDBC doc](https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/guide/jdbc/getstart/mapping.doc.html) which we used as a source for mapping types. 
In addition, this option "unsigned" is not common for JDBC sources and there is no way to get easily it as a parameter. 
So, I tried different ways how to handle this and here is my list of solutions so far:
- Map source INTEGER with Java LONG for all cases.
:heavy_check_mark: Simple implementation
-
