### ISSUE TITLE
Destination Bigquery: When raw data set changed away from `airbyte_internal`, `airbyte_internal` is still being creataed

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#38473]
Destination Version: airbyte/destination-bigquery:2.4.20

**Comment by evantahler** [comment]
Will be closed by https://github.com/airbytehq/airbyte/pull/38132

**Comment by stephane-airbyte** [comment]
@gisripa assigned to you

**Comment by nadavkaner** [comment]
I see #38132 is merged, is this issue solved?

**Comment by edgao** [comment]
it should be - try upgrading to destination-bigquery 2.5.1

**Comment by evantahler** [comment]
Closing - we think this is solved now.
