### ISSUE TITLE
Choose a namespace configuration strategy in the UI

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#3852]
## Tell us about the problem you're trying to solve
Following up on #3481 to provide some control to users on choosing the destination namespace. 

## Describe the solution you’d like
On the connection settings page:
I would like an option to select which namespace to use in the destination:

1. Replicate and mirror the schema and tables naming from the source
2. Write all tables into the default schema defined in the destination connector settings

![Screenshot 2021-06-03 at 17 21 27](https://user-images.githubusercontent.com/7718175/120669903-2f21a180-c490-11eb-9796-50d97fd0c169.png)

3. In the case of custom namespace format, I can type the name of the schema to use

![Screenshot 2021-06-03 at 17 24 38](https://user-images.githubusercontent.com/7718175/120670330-98a1b000-c490-11eb-9409-2672a19ab9f9.png)

Figma: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25747%3A6310

## Additional context
Tech specs docs: https://docs.google.com/document/d/1qFk4YqnwxE4MCGeJ9M2scGOYej6JnDy9A0zbICP_zjI/edit#heading=h.jhq4pmn56qrf

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200422330095907) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@Jamakase this issue is making UI changes in the same place as this [one](https://github.com/airbytehq/airbyte/issues/3499), so it may make sense to do them together.
