### ISSUE TITLE
Amplitude and Hubspot connector

### ISSUE THREAD

**Issue by amoghkulkarni123** [airbytehq/airbyte#3854]
## Tell us about the new connector you’d like to have
* Which source and which destination?
           Source: Amplitude and Hubspot
           Destination: Snowflake
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
           No
## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
           Data engineering team
* How often do you want to run syncs?
           Hourly, Daily, Weekly
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
            We will build our own connector through Amplitude or Hubspot APIs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200422476364550) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
@amoghkulkarni123 Hubspot is available, see the [docs](docs.airbyte.io/integrations/sources/hubspot) and Amplitude is WIP, should be merged soon. See #3664
