### ISSUE TITLE
Connector Pipedrive: custom fields do not sync

### ISSUE THREAD

**Issue by gmzgian** [airbytehq/airbyte#38557]
### Connector Name

Pipedrive-postgres

### Connector Version

2.2.2

### What step the error happened?

Other

### Relevant information

We have an issue with syncing Pipedrive to Postgres.

The existence of the custom fields is recorded in the xxx_fields tables but their value per record (nor the column itself) is not present in the xxx tables, nor in the _airbyte_raw_xxx tables. Turning off the basic normalization (and resyncing everything) won't resolve the issue either.

Tested it with xxx being `deals`, `organizations`, and `persons`.
The custom field just does not show up in these three tables (`deals`, `organizations`, and `persons`)
Only in the xxx_fields (persons_fields) as a column name only. No values anywhere to be found.

Thanks for the help!

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Duplicated of https://github.com/airbytehq/airbyte/issues/33622
