### ISSUE TITLE
Storybook site (components.airbyte.dev) down, no DNS records

### ISSUE THREAD

**Issue by jettdc** [airbytehq/airbyte#38566]
### Topic

Storybook

### Relevant information

https://components.airbyte.dev/?path=/story/connector-connectorform--preview

<img width="741" alt="Screenshot 2024-05-22 at 9 50 37 AM" src="https://github.com/airbytehq/airbyte/assets/58793088/c5409cca-88d9-45ef-81e6-308aacc90811">

This site has been down for a week at least. It's [linked in the docs](https://docs.airbyte.com/connector-development/connector-specification-reference) so it should either be fixed to be publicly available or removed from the docs

**Comment by joeybenamy** [comment]
There's no DNS records for [components.airbyte.dev](http://components.airbyte.dev/) so yes it would be down for everyone.

**Comment by joeybenamy** [comment]
```
$ dig components.airbyte.dev
;; communications error to 172.22.96.1#53: timed out
```
