### ISSUE TITLE
airbyte-ci tool using broken dependency

### ISSUE THREAD

**Issue by jettdc** [airbytehq/airbyte#38570]
### Topic

airbyte-ci cli tool v4.14.0

### Relevant information

airbyte-ci v4.14.0 relies on `docker-py:7.0.0` which broke with the latest `requests@2.32` release, meaning airbyte-ci commands that leverage docker are broken:

```
 Error: Could not connect to docker daemon: Error while fetching server API version: Not supported URL scheme http+docker    
```

fix was merged for docker-py here https://github.com/docker/docker-py/pull/3257 but is not released yet.

**Comment by jettdc** [comment]
Temporary fix

```diff
diff --git a/airbyte-ci/connectors/pipelines/pyproject.toml b/airbyte-ci/connectors/pipelines/pyproject.toml
index 485dcb6892..644ae2bd48 100644
@@ -19,7 +19,7 @@ docker = "^7"
 semver = "^3"
 airbyte-protocol-models = "*"
 jinja2 = "^3.0.2"
-requests = "^2.31"
+requests = "2.31.0"
 airbyte-connectors-base-images = {path = "../base_images", develop = true}
 connector-ops = {path = "../connector_ops", develop = true}
 toml = "^0.10.2"
```

**Comment by natikgadzhi** [comment]
Huh, my impression was that `^2.31` would not update to 2.32, let me check.

**Comment by natikgadzhi** [comment]
Yep, running `poetry lock` gives me `requests 2.31` still. Can you give me an example of a scenario that fails for you?
