### ISSUE TITLE
Waiting for source thread to join (log hanging when sync is running)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3857]
## Expected Behavior
The sync process should continually print logs.

## Current Behavior
Hang on Waiting for the source thread to join.
Already seen this happening with Strip, Freshdesk: #3715 
This is confusing for users because they cannot know if the source is actually running.

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._

## Steps to Reproduce
1. set up any source from API like (Stripe, Salesforce, Freshdesk)
1. destination (pgsql)
1. run sync

## Severity of the bug for you
Very low / Low / Medium / **High** / Critical

## Airbyte Version
0.24.4-alpha

## Connector Version (if applicable)
~

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200422850921112) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
This is fixed with #3874 .
