### ISSUE TITLE
Freshdesk fails after 300 pages

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#3858]
### User Report
Got this error for Freshdesk, how do I report this for fixing?? It ran for 6 hours only to get this error :disappointed::

```
Validation failed: [{'field': 'page', 'message': 'You cannot access tickets beyond the 300th page. Please provide a smaller page number.', 'code': 'invalid_value'}]
```

[slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1622730415124900)

## Expected Behavior
according to freshdesk [docs](https://developers.freshdesk.com/api/):

```
 2. A maximum of 300 pages (9000 tickets) will be returned.
```

* I'm not sure what the behavior should be here if we should either 1. change the filters so that once we hit page 300, we make a new query that lets us cheat and access the 301st page (not sure how possible this is) 2. just stop at 300 pages and not throw an error. Freshdesk seems somewhat opinionated on not exposing really old information. In the slack thread I'm asking the user what they prefer. 

## Current Behavior
* It fails.

sherifnada heads up

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200422893709667) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
We can probably fix this by using stream slices and the `updated_at` parameter on the ticket list endpoint.

**Comment by bazarnov** [comment]
I suppose that [this line of code](https://developers.freshdesk.com/api/#best_practices) give the iterator possibility to look back over the 300+ pages, and we can try to limit the rate first from 500 to 300 as a quick fix.

**Comment by rytiszolubasf** [comment]
I would suggest after quering 300 pages, take the last page last ticket updated_at and use it in the sequencial query.
this is the query that would allow that since you filter them:
https://{{subdomain}}.freshdesk.com/api/v2/tickets?per_page=100&order_by=updated_at&order_type=asc&updated_since=2021-06-03T14:56:12Z&include=stats, description, requester

**Comment by sherifnada** [comment]
@bazarnov that stops the failure but doesn't allow the user to sync all tickets. I think we can also implement something like what @rytiszolubasf suggested. It should work very well assuming records are returned in sorted order of update. WDYT we go with that suggestion?
