### ISSUE TITLE
Snowflake destination automatic clustering turned on

### ISSUE THREAD

**Issue by ltw94** [airbytehq/airbyte#38642]
### Connector Name

destination-snowflake

### Connector Version

2.0.0

### What step the error happened?

Other

### Relevant information

Whilst we are not having an error with the connector itself, we are seeing that the connector is turning automatically automatic clustering in the tables it is writing in Snowflake. How can we turn this off in the connection settings? I cannot see this option available in the UI.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
This reports a problem using an outdated version of Snowflake destination. Please upgrade to latest version and if the issue persists file a new Github Issue.
