### ISSUE TITLE
[source-MySQL] Can't select incremental sync in CDC-based connection

### ISSUE THREAD

**Issue by mrmooon** [airbytehq/airbyte#38659]
### Connector Name

source-mysql

### Connector Version

 3.4.1

### What step the error happened?

Configuring a new connector

### Relevant information

We have a connection from  MySQL to S3 using CDC as the update method. However, we can't select the incremental strategy for two particular streams. As I understand it, Airbyte should be able to retrieve the data incrementally based on the metadata of the binary logs, regardless of the structure of the table schema.

<img width="309" alt="Screenshot 2024-05-25 at 11 54 02" src="https://github.com/airbytehq/airbyte/assets/24896223/88ff5bf3-9071-4506-b6a2-7265a10ce8b6">

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@mrmooon it looks is affecting only 2 streams, with others are you able to select incremental?
Can you confirm both tables are configured to use CDC in MySQL?

**Comment by mrmooon** [comment]
> @mrmooon it looks is affecting only 2 streams, with others are you able to select incremental? Can you confirm both tables are configured to use CDC in MySQL?

Hey, @marcosmarxm. Yes, we update data incrementally with the rest of the streams (more than 150 tables split across multiple connections).

AFAIK all the table updates are written to the binary logs. The only difference from other streams is that these two streams don't have an id column in the source DB.

**Comment by mrmooon** [comment]
Hello @akashkulk! These tables don't have a PK. I understand this is a requirement for[`Incremental Sync - Append + Deduped` strategy](https://docs.airbyte.com/using-airbyte/core-concepts/sync-modes/incremental-append-deduped) when the data in the destination is updated to maintain the state of the source system (type 1 SCD). But, does the [incremental append](https://docs.airbyte.com/using-airbyte/core-concepts/sync-modes/incremental-append) require a PK in the source system to identify changed records? To my understanding, the binlog offset allows you identify which was the last record ingested. Sorry if this is a trivial question.
