### ISSUE TITLE
[source-google-analytics-data-api] unable to configure source: configuration check failed

### ISSUE THREAD

**Issue by thomaslenaour** [airbytehq/airbyte#38693]
### Connector Name

source-google-analytics-data-api

### Connector Version

2.4.2

### What step the error happened?

Configuring a new connector

### Relevant information

When trying to configure a new Google Analytics 4 (GA4) source from the Airbyte Cloud dashboard, I get this Internal Server Error.

### Steps to reproduce
1. Go to Google Analytics (GA4) new source page
2. Authenticate via Google (OAuth)
3. Set a valid Property ID
4. Click on "Set up source" button

### Screenshot error
![image](https://github.com/airbytehq/airbyte/assets/35400119/3e577667-feb2-47ba-9702-4383514d33fb)

### Relevant log output

```shell
io.airbyte.workers.exception.WorkerException: CHECK operation returned a non zero exit code, the exit code is: 1
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by thomaslenaour** [comment]
**Update:** I managed to configure the source via Airbyte API and overriding OAuth credentials with a custom Google Cloud project.

However, when I try to create the Connection on Airbyte Cloud (Google Analytics => Big Query) I get another **Internal Server Error**: Discovering schema failed.

### Screenshot
![image](https://github.com/airbytehq/airbyte/assets/35400119/42deb874-bb64-4e30-abc7-3298ceba4eef)

### Relevant log output
```
io.airbyte.workers.exception.WorkerException: DISCOVER operation returned a non zero exit code, the exit code is: 1
```

**Comment by marcosmarxm** [comment]
Sorry the delay to get into this issue @thomaslenaour are you still experiencing the problem?

**Comment by marcosmarxm** [comment]
Close due lack of response.
