### ISSUE TITLE
Gradle Core build is flaky.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3877]
## Expected Behavior
The Gradle build should only build changed code and ignore unchanged code.

## Current Behavior
Jared and I were pairing on a change together. Something that was working on my system at the same git hash was not working on his. We confirmed this was build system related by cloning airbyte to a different directory and confirming the same git hash worked when running from the second directory.

## Steps to Reproduce
We don't know what causes the system to get into this state. Once it is in this state, the error is reproducible by running any command that uses Gradle's usual caching e.g. `./gradle composeBuild`. We suspect it's because something is being cached when it should not.

## Severity of the bug for you
Low - we can get around this by running `--rerun-tasks` for now.

**Comment by cgardens** [comment]
i don't think we have seen this a long time
