### ISSUE TITLE
Add SSL for MySQL (mariaDB)

### ISSUE THREAD

**Issue by dl-lim** [airbytehq/airbyte#3882]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Trying to connect to MySQL server with SSL
JDBC url parameter does not accept ?requireSSL=true&useSSL=true&verifyServerCertificate=false
Connection fails when db user requires SSL.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see
Allow SSL connection

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.
Add a VPN connection to the db server and not use SSL.

## Are you willing to submit a PR?

Your answer
Not technical in that area.

Reference:
https://github.com/airbytehq/airbyte/pull/2757

**Comment by marcosmarxm** [comment]
thanks @alderson59 I added your request on the connector roadmap.

**Comment by grishick** [comment]
This is a duplicate of https://github.com/airbytehq/airbyte/issues/6985
