### ISSUE TITLE
[FR] Cron style Custom Sync Frequency

### ISSUE THREAD

**Issue by alderson59** [airbytehq/airbyte#3883]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Selecting sync frequency is now on a regular interval based on the available settings only.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see
A "Custom" option allowing a cron interval, for example "0 2,3,4, 0 * *", "0 14 * * 0" etc.
This allows flexibility to not load certain servers during critical production hours.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.
Not available with airbyte.

## Are you willing to submit a PR?

Your answer
Not technical in this area.

**Comment by jrhizor** [comment]
related https://github.com/airbytehq/airbyte/issues/2170

A temporary workaround is to trigger syncs with the API using an actual cron. Obviously not ideal and we are planning on adding first class cron-style scheduling at some point.

**Comment by marcosmarxm** [comment]
Closed as duplicated #2170 
I change priority to high because there a lot of request for this fearture.
