### ISSUE TITLE
Expose a user friendly way to input dates in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3897]
## Tell us about the problem you're trying to solve
Today users have to input dates manually in UTC format e.g: `2010-11-12T13:14:15Z` which is annoying. As a user I would rather use a date picker. 

## Describe the solution you’d like
For fields which take dates as input, display a date picker on the UI instead of manually typing these strings. 

I realize there will be some nuance to this depending on the output format of the date. So we may need to set some conventions in `spec.json` for setting the `format` of the date string.

**Comment by sherifnada** [comment]
@timroes flagging this as a real nice-to-have to maintain a polished user experience.

**Comment by sherifnada** [comment]
cc @airbytehq/frontend

**Comment by edmundito** [comment]
This issue has been replaced by #12197
