### ISSUE TITLE
Custom connectors display as always having a new version 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3898]
## Expected Behavior
I expect a custom connector added in the UI to only notify that there is a new version if there is actually a new version of the connector. In this case, it seems like the UI is always suggesting there is a new version when there isn't: 

![Screen Shot 2021-06-04 at 9 46 21 AM](https://user-images.githubusercontent.com/6246757/120835853-b9621800-c519-11eb-8939-02bc35af7fd3.png)

## Current Behavior
*Tell us what happens instead of the expected behavior.*

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. Add a custom connector (could be one that already exists in the connector list) 
1. See this issue

## Severity of the bug for you
Low 

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

**Comment by timroes** [comment]
Tried on a recent version and this seems to no longer be reproducible.
