### ISSUE TITLE
S3 Destination Connector for Alternative S3

### ISSUE THREAD

**Issue by panhavad** [airbytehq/airbyte#3900]
## Tell us about the problem you're trying to solve
I want to just the existing just release S3 destination connector, in a way that it can be configured with Alternative S3 (Like Minio or Ceph).

## Describe the solution you’d like
Most of the parameters will be the same as AWS S3.
Just there should some extra field required:
- IP and Port Field -> So that it knows the request should go to my hosted S3, not AWS
If we want to use AWS just leave that IP and PORT field blank, something like that.
- Region Field -> For Minio region is optional.

**Comment by panhavad** [comment]
>are you willing to contribute?

Yes, sure. If the team has no plan to go with this feature.

**Comment by elthariel** [comment]
I was investigating this a bit. Just a few notes to help you:

This is where the config is fetched https://github.com/airbytehq/airbyte/blob/c13b9883e87dd25f6ece730c54e8a8b3c6579604/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3DestinationConfig.java

It seems the s3 client is built here: https://github.com/airbytehq/airbyte/blob/c13b9883e87dd25f6ece730c54e8a8b3c6579604/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/S3Consumer.java#L72

and finally, it seems this is the method used to configure the s3 client endpoint: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.html#setEndpointConfiguration-com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration-

**Comment by panhavad** [comment]
Great @tuliren @marcosmarxm Thank you for the review and merge.
The merge should be solved this issue.
