### ISSUE TITLE
set AIRBYTE_ENTRYPOINT for base images and bump all connectors

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3903]
- [x] set `AIRBYTE_ENTRYPOINT` in base image
- [x] set `AIRBYTE_ENTRYPOINT` for connectors with custom entrypoints
- [x] set `AIRBYTE_ENTRYPOINT` for normalization (happening as part of https://github.com/airbytehq/airbyte/pull/3866 potentially)
- [x] set `AIRBYTE_ENTRYPOINT` for transform images (need to check if any aren't set programatically) 
- [x] bump/publish all image versions
- [x] re-add error for `KubePodProcess` if an `AIRBYTE_ENTRYPOINT` isn't detected
- [x] java standard test should check for this ENV variable
- [x] python standard test should check for this ENV variable https://github.com/airbytehq/airbyte/issues/4262

The reason I'm creating this is because it's easy to get confused when debugging when this isn't working properly. It's better for it to be fully specified.

**Comment by sherifnada** [comment]
We should add this to new connector templates

**Comment by davinchia** [comment]
As of #4539 all connectors should have the AIRBYTE ENTRYPOINT set except for the connectors in the deprecated section of the PR's description.
