### ISSUE TITLE
include checkpointing destination updates in next release migration

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#3906]
After checkpointing was introduced, if a destination connector isn't bumped to the post-checkpointing version incremental stops working incrementally and the last state message from before checkpointing is used indefinitely. This causes sync sizes  for incremental to monotonically increase indefinitely.

If there are no breaking changes (which I believe there are not) we should include bumping the destination versions in a migration for the next release to ensure that users do not have stuck state.

@cgardens wdyt?

**Comment by davinchia** [comment]
Pretty sure this no longer applies as checkpointing has been out for a while now and we've solved this.
