### ISSUE TITLE
Link our docs with Github tickets and update them automatically

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#3918]
### Tell us about the documentation you'd like us to add or update.
https://docs.airbyte.io/understanding-airbyte/namespaces

There is a section **Coming soon**, maybe we should always address new features to their tickets on Github.
With that in mind, we could create a Github bot to automatically create a new ticket to update documentation.
@avaidyanatha WDYT? Not every time we ship a feature we remember to update docs.

Example:
**Coming Soon**
- Ability to prefix namespaces (Issue 456).
- Ability to configure custom namespaces (Issue 123).
- Ability to toggle the functionality of the namespace (Issue 111).

Issue 111 is closed them a new ticket is open to update doc and add relevant documentation related to that feature. 

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by ChristopheDuong** [comment]
FYI I am updating the docs of the example you took on the namespace as part of my PR here https://github.com/airbytehq/airbyte/pull/3886
