### ISSUE TITLE
Source Hubspot incorrect schema and streams reading failure

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#3927]
## Expected Behavior
Hubspot should not raise exception for any streams. 
All the streams may return records or source may be configured to skip empty streams to avoid test fails.
Acceptance tests must pass with no fails.

## Current Behavior
- Schema is incorrect
```
record = {'about_us': None, 'address': None, 'address2': None, 'annualrevenue': None, ...}
spec = {'about_us': None, 'address': None, 'address2': None, 'annualrevenue': None, ...}
    @staticmethod
    def remove_extra_fields(record: Any, spec: Any) -> Any:
        """Remove keys from record that spec doesn't have, works recursively"""
        if not isinstance(spec, Mapping):
            return record
        assert isinstance(record, Mapping), "Record or part of it is not a dictionary, but expected record is."
        result = {}
        for k, v in spec.items():
>           assert k in record, "Record or part of it doesn't have attribute that has expected record."
E           AssertionError: Record or part of it doesn't have attribute that has expected record.
E           assert 'first_conversion_date' in {'about_us': None, 'address': None, 'address2': None, 'annualrevenue': None, ...}
../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:138: AssertionError
```

- It has a bunch of empty streams
```
E           AssertionError: All streams should return some records, streams without records: {'email_events', 'owners', 'products', 'quotes', 'contact_lists', 'forms', 'tickets', 'subscription_changes', 'campaigns', 'line_items', 'engagements'}
E           assert not {'campaigns', 'contact_lists', 'email_events', 'engagements', 'forms', 'line_items', ...}
../../bases/source-acceptance-test/source_acceptance_test/tests/test_core.py:109: AssertionError
```
Although at least owners  stream is not actually empty (tested with Postman), so it's reading bug on our side.

- No permissions for workflows stream using our lastpass API key.

@yevhenii-ldv reported:
I had 403 error for Workflows stream with message:
`"This hapikey (xxx) does not have proper permissions! (requires any of [automation-access])"`
I looked at Connector-Health and it started in June.
The Re-generation of the `api_key` did not help in any way.
I tried to search the forum for similar errors and found these similar queries (they say that the subscription may have ended by Workflows):
https://community.hubspot.com/t5/APIs-Integrations/This-hapikey-xxx-does-not-have-proper-permissions-requires-any/td-p/223248
https://community.hubspot.com/t5/APIs-Integrations/This-hapikey-xxxx-does-not-have-proper-permissions-requires-all/td-p/349606

## Logs
[acceptance.log](https://github.com/airbytehq/airbyte/files/6608957/acceptance.log)
[read.log](https://github.com/airbytehq/airbyte/files/6608958/read.log)

## Steps to Reproduce
1. Setup hubspot source locally
1. Run `python main_dev.py read --config secrets/config.json --catalog sample_files/configured_catalog.json`
1. Run `python -m pytest -p integration_tests.acceptance` to see more logs

## Severity of the bug for you
High

## Airbyte Version
0.24.5-alpha

## Connector Version (if applicable)
0.1.3

**Comment by potatozerg** [comment]
@htrueman Hi, I'm still facing this issue:
`@yevhenii-ldv reported:
I had 403 error for Workflows stream with message:
"This hapikey (xxx) does not have proper permissions! (requires any of [automation-access])"`

Is this issue still exist after your PR?
