### ISSUE TITLE
Ingesting chunk of data each run instead of Full Replication

### ISSUE THREAD

**Issue by phamduyly** [airbytehq/airbyte#3929]
## Tell us about the problem you're trying to solve
As replication are all useful. However, there are some big tables with more than 80 Mils records, nearly 7 years worth of data that we have in our company that we would like to be able to extract chunk of data in the span of 5 -10 days each. If there is a different connectors or any kind of mechanism for this request would be nice.

## Describe the solution you’d like
As state above, I want to be able to extract chunk of data each run. Or if better, able to customize  flexible day span. 

## Describe the alternative you’ve considered or used
So we are building this mechanism in-house and have been using it for a while. For big tables, this really works well with Airflow backfilling concept. 

## Are you willing to submit a PR?

Your answer

**Comment by sherifnada** [comment]
@phamduyly which connectors would you like this for? Or are you saying for all connectors?

**Comment by ajzo90** [comment]
One potential solution:
In case the source is ordered and incremental, the source can choose to emit a limited number of messages. 
To start with, this can be implemented in a specific source, and be controlled with the config.  (i.e. maxRecordsToEmit = 10000). This in combination with a high sync frequency should resolve your issue.

**Comment by phamduyly** [comment]
Hi @sherifnada, currently, MySQL, Postgres and MongoDB would be nice.

Hi @ajzo90, is what you said implemented? or it will need to develop in the connectors? Your solutions is great. In the end, the end goals is to reduce the huge load of, said ingesting a big tables at once

**Comment by ajzo90** [comment]
No, I was talking about a hypothetic solution.
If this is a blocker to you, you can always implement a specific source that fits your own needs.

**Comment by sherifnada** [comment]
@ajzo90 great point about incremental. 

The easiest way to do this would probably be in the sources themselves. Seeing as we are standardizing on using the Airbyte CDK for developing sources (Java one de-facto already exists, needs to be cleaned up and released with better docs) I think we can add this functionality to the Python and Java CDKs as a default out-of-the-box feature for connectors which want it. Adding it in the connectors themselves would give the connector author flexibility over whether the connector should use that feature/whether it makes sense for it given its particular context.

**Comment by sherifnada** [comment]
Related issue for Python CDK: https://github.com/airbytehq/airbyte/issues/2681

We should also implement something similar for the Java CDK.

**Comment by ajzo90** [comment]
Another possible solution would be to add a "stop cursor" and let the source use that for filtering, it can be defined either manually or by increment the state cursor with some interval (eg 1 week of data etc..). 
The benefit is that the source do not need to be sorted, but it can not guarantee how many records that will be emitted.
