### ISSUE TITLE
SAT: Support flexible state comparison in incremental test

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3938]
## Tell us about the problem you're trying to solve
In some cases, connectors which function correctly output records whose cursor field values are smaller than the input state. This is especially ubiquitous in marketing connectors like facebook marketing or google ads where data in the source can be updated up to N days after being generated. Those connectors often a lookback window where they pull all records generated N days before the input state. This is a correct implementation. However, the SAT isn't flexible enough to allow expressing this edge case. As a result those connectors must disable the SAT incremental test like in [this PR](https://github.com/Velocity-Engineering/airbyte/pull/3/files).

## Describe the solution you’d like
Some way to solve the problem above. One idea is to allow the user to input some python code which mutates the state output by the first incremental sync to make it correct

## Describe the alternative you’ve considered or used
Disable SAT incremental test and write custom integration tests

**Comment by keu** [comment]
Actually, I think FB behaves incorrectly as a stream. It should produce only updated records in that case.
This behavior with lookback window only happens with Insights - i.e. reports. We read reports for N days, and here we are confusing the `date` of the report and its `updated_ts`. So IMHO Insights stream should read N days but output only those were `updated_ts >= state.value`
