### ISSUE TITLE
Analytics: Measure site to install conversion

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#394]
## Tell us about the problem you're trying to solve
If a user is opt-in for analytics we should be able to measure the conversion from website/docs to actual installs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368167811302) by [Unito](https://www.unito.io)

**Comment by timroes** [comment]
Since this is a very old issue, @nataliekwong are you aware if this is still something we can't meassure, but would need to meassure or is this doable nowadays?
