### ISSUE TITLE
[source-slack] Threads from private channels are not synced

### ISSUE THREAD

**Issue by ctdio** [airbytehq/airbyte#39414]
### Connector Name

source-slack

### Connector Version

1.1.5

### What step the error happened?

During the sync

### Relevant information

I noticed that threads from private channels are not being ingested. Digging around a bit, I see that the `include_private_channels` configuration is not used when querying channels in the threads stream. The request for channels only specifies `public_channels`. 

It looks like a pretty simple fix, I'll submit a PR soon.

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Awesome!
