### ISSUE TITLE
dbt Cloud Integration problem

### ISSUE THREAD

**Issue by gurbuzertunga** [airbytehq/airbyte#39428]
### Topic

dbt Cloud Integration

### Relevant information

I am trying to add a new service token for dbt Cloud Integration but your system keeps throwing errors.http.internalServerError.

I created the dbt account and generated the service token. when pasted, airbyte cloud integrations throws the error.

here is a screenshot as well
![Screenshot from 2024-06-10 18-41-19](https://github.com/airbytehq/airbyte/assets/65021553/54dc6cb4-50d0-4b79-a1f4-d62b93a2dc62)

**Comment by marcosmarxm** [comment]
Thanks @gurbuzertunga I added this to the platform team backlog. If you prefer you can also open a [support ticket](https://support.airbyte.com/hc/en-us) to get updates about the issue.

**Comment by gurbuzertunga** [comment]
> @gurbuzertunga Are you running on a region or with a custom URL in dbt Cloud that's not `cloud.getdbt.com`? If so, this will be the issue, since we currently don't allow you to specify a custom dbt URL. We're currently actively working on enabling this and will have an update available soon that will allow you to specify your custom API endpoint to talk to.

Hi @timroes  Thanks for the reply. Yes it seems even though my account is a team account and served from North America servers, it seems it's not being served from cloud.getdbt.com but rather with an account_prefix.us1.dbt.com. I'm trying to see how to translate this account to use cloud.getdbt.com. Any tips would be appreciated!

**Comment by teallarson** [comment]
If you check the Integrations page again, you should be able to enter that now!

**Comment by gurbuzertunga** [comment]
> If you check the Integrations page again, you should be able to enter that custom access URL now.

Hi @teallarson,  Just did a test and this time without an error message it doesn't work. see the image below:

![image](https://github.com/airbytehq/airbyte/assets/65021553/2208066c-f9dd-442a-885a-af08f784dbad)

**Comment by malikdiarra** [comment]
hi @gurbuzertunga, can you retry by removing the `https://` prefix and the trailing `/`

**Comment by gurbuzertunga** [comment]
> hi @gurbuzertunga, can you retry by removing the `https://` prefix and the trailing `/`

hi @malikdiarra, same error happening. to provide more context I'm sending the api call payload and responses in the screenshots below:

![image](https://github.com/airbytehq/airbyte/assets/65021553/a7963383-4115-40ed-ba12-0269f3dd19de)
![image](https://github.com/airbytehq/airbyte/assets/65021553/1ced3c6d-4be7-4aca-8604-53b934343ea2)

**Comment by gurbuzertunga** [comment]
hi @malikdiarra any updates on this issue?

**Comment by malikdiarra** [comment]
hi @gurbuzertunga, I've got a fix that I'm hoping to ship this week; I'm currently still testing it.

**Comment by malikdiarra** [comment]
HI @gurbuzertunga, can you confirm everything is working on your end now?
