### ISSUE TITLE
Schema page does not display more than 6k tables.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3942]
## Expected Behavior
If I have a database with many tables, I expect to be able to view all the tables after the discover schema operation.

Side thought: since there are so many tables, we might need some search functionality here.

## Current Behavior
The operation completes. I am able to see the initial page, but the UI crashes after.

## Steps to Reproduce
1. Run discover schema on a database with more than 6k tables.

## Severity of the bug for you
 Low

**Comment by davinchia** [comment]
Aside from frontend improvements, one possible solution is:
* save the entire catalog after a discover operation.
* modify the discover api to be able to paginate on the saved catalog

**Comment by cgardens** [comment]
@davinchia Is your feeling that there is any purely UI solution here? 6K tables sounds like a lot to me, not super obvious that this is a FE problem. I agree with your second comment that pagination could help here. I'm asking, because if you think there's an easy fix, that's great!

**Comment by marcosmarxm** [comment]
@cgardens no, https://github.com/airbytehq/airbyte/issues/3943 is related with this issue too.

**Comment by davinchia** [comment]
@cgardens I think it depends on how we want to do this. 

If we want to keep this purely UI, we can paginate using client memory. My sense is this is not long term sustainable.

The solution I want is to introduce either introduce pagination or regex or both into the discover route, and have it only return the filtered result. This would be FE and Server changes. Pagination is useful for users that don't necessarily know all their tables. Regex is useful for users who do know. Have to think more to which I prefer.

As Marcos pointed, we also need to increase the maximum number of tables we are read. I'd consider that work separate from the one here.

**Comment by timroes** [comment]
Closing this in favor of our generic pagination issue https://github.com/airbytehq/airbyte/issues/11114 as well as https://github.com/airbytehq/airbyte/issues/11762
