### ISSUE TITLE
Repeated DD_AGENT_HOST item in docker-compose.yaml services.server.environment

### ISSUE THREAD

**Issue by altxtech** [airbytehq/airbyte#39444]
### Platform Version

0.63.0

### What step the error happened?

On deploy

### Relevant information

On the raw docker-compose.yaml file (https://raw.githubusercontent.com/airbytehq/airbyte-platform/v0.63.0/docker-compose.yaml)

The services.server.environment array has 2 repeated instances of the value "DD_AGENT_HOST=${DD_AGENT_HOST}"  at positions 14 and 54.

In certain situations, it is possible for the ./run-ab-platform.sh script to fail because of this.
Still trying to figure out the exact steps of how to reproduce this issue, but it does happen.

**Comment by agonbina** [comment]
Ran into the same issue just now. One line has to be removed.

**Comment by marcosmarxm** [comment]
This was fixed in https://github.com/airbytehq/airbyte-platform/commit/ad284c13f1bcbf80e6035f7c6b5705fd2e304f45 if you pull the file again it is already correct.
