### ISSUE TITLE
Suggestions for protocol changes

### ISSUE THREAD

**Issue by ajzo90** [airbytehq/airbyte#3945]
Hi. 
I tried to collect a few ideas for some potential changes that can improve the airbyte protocol long term. 
It's a summary from a few slack discussion I initiated recently, and in particular [https://airbytehq.slack.com/archives/C019WJFR1JT/p1622103941088300].
It should be seen as a first draft for describing potential suggestions. It's a bit messy and not at all complete, but I hope it could spark some discussions around potential improvements.  I tend to take shortcuts when describing issues, so please let me know if something is unclear. 
Note that I am not fully aware of upcoming additions, and I am basing these suggestions on how I interpret the current public protocol documentation and my limited (~3 weeks) experience using airbyte.  

### Current behaviour
First a summary over the protocol messages and their intended side effects through a sync process (source -> worker -> destination).

#### Source
* emit `LOG`, `RECORD`, `STATE`

#### Worker
* read and persist `STATE`. Basically persist it and give it to the source to the next sync.
* read and dump/persist `LOG`
* read and collect stats (number of bytes, number of records) from `RECORD`
* read, validate, transform and emit `RECORD`. The transformation is that it updates a stream name in case the connection is configured with a prefix. Eg if a prefix `p_` is used, it transforms:
```
{"type":"RECORD","record":{"stream":"table1","data":{"id":1},"emitted_at":1622208594225}}
```
into 
```
{"type":"RECORD","record":{"stream":"p_table1","data":{"id":1},"emitted_at":1622208594225}}
```

#### Destination
* reads `RECORD` and insert in some storage.
* No output allowed (according to documentation)
* Not clear how to communicate failures 

### Limitations
With the current protocol it is not possible for the worker to effectively communicate information back to the worker. 
Example of informative information could be 
1) progress, how many rows it has observed or inserted. Use a specific message rather than the more generic log.
2) formatted log/error messages. 
3) job status (did the job succeed, why did it not success)
4) job information (per stream?) (number of observed records, number of inserted records, number of updated records, etc..)
5) snapshot (I know this is work in progress, but mention it anyway since I don't know how it is suppose to work) to partially commit large sync jobs. 

Another concern is that the worker are doing work that it could delegate to the destination. The worker would be simpler if its only purpose was to initiate the source/destination processes and only listen to the output stream from the worker. In particular I noticed some overhead, that I think is not necessary in the core of airbyte (e.g. it's not good running a lot of concurrent jobs, even if it scales horizontally. I would prefer 1MB RAM and 1% CPU over 100MB RAM and 100% memory (or whatever numbers..)).

#### Source
* (same) emit `LOG`, `RECORD`, `STATE`
* (new, optional) emit `PROGRESS`. Example `{"type":"PROGRESS","progress":{"records": 1000}}`

#### Worker
* (new, its a simplification of responsibilities) initiate source/destination processes and pass through raw data
* (change) listens for `STATE`, `LOG` from destination and handle it the same as from sources today
* (new) listen for `RESULT`, `PROGRESS`. To inform user. Can be implementation later.

##### Protocol extension
* read `RECORD` and insert in some storage.
* (new, required) read `LOG` from source and bounce it back to the worker. 
* (new, required) emit `RESULT` For example `{"type":"RESULT","result":{"status": "ok", "inserted": 1000, "updated": 100, "totalRecords": 10000}}` or
* (new, optional) read + emit`STATE` (hint for destination that it can use, or not) and emit the same state if/when it is fulfilled. For example a source might be ordered and able to emit `STATE` hints every, say 1000, records. But the destination might not commit changes until it got all data. So it's up to the destination to use the `STATE` hints. It can only use the `STATE` hints passed from the source. 
`{"type":"RESULT","result":{"status": "failed", "reason": "unexpected something...", "consequence":"full roll back"}}`
* (new, optional) emit `PROGRESS`. Similar as from source. Need to separate it somehow. 

##### Config extension
In addition to protocol messages extensions above, it would also *require* changes in `ConfiguredAirbyteStream` in the config.
By adding `name` and `namespace` in `ConfiguredAirbyteStream` the destination know how the source stream (`stream.name`, `stream.namespace`) should be mapped.
This would also allow further extensions in API/UI to change the destination for any streams.

#### Summary and implementation considerations. 
* Use `name`, `namespace` in the `ConfiguredAirbyteStream` is an extension to the config. All destinations must adapt to this change, else it will stop working in case prefix is used.
* `STATE` is backward compatible if the destination just bounces it back to the worker. I don't know how the snapshot feature work. Might be colliding or converging ideas.
* `RESULT` only affect destination. Should be required for explicit acknowledge a successful process. The specific statistics can be optional, but recommended. 
* `LOG` and `PROGRESS` are informative messages that is useful in UI/monitoring. It's should be trivial (but optional) for the connectors to emit those. No breaking change. Need to figure out how to distinguish them.

**Comment by ChristopheDuong** [comment]
> In addition to protocol messages extensions above, it would also require changes in ConfiguredAirbyteStream in the config.
By adding name and namespace in ConfiguredAirbyteStream the destination know how the source stream (stream.name, stream.namespace) should be mapped.
This would also allow further extensions in API/UI to change the destination for any streams.
> Use name, namespace in the ConfiguredAirbyteStream is an extension to the config. All destinations must adapt to this change, else it will stop working in case prefix is used.

Have you seen this ticket we've been working on yet? https://github.com/airbytehq/airbyte/issues/3481
That's adding "responsibility" to the worker on top of the prefixing to also handle the namespaces.

**Comment by ajzo90** [comment]
Yes, I have seen that discussion. It's actually included above under `Config extension` section. I think it should cover what's needed.

**Comment by ajzo90** [comment]
I haven't looked into the solution yet though, I'll do it in later today.

**Comment by ajzo90** [comment]
Ah ok, I see, so it effectively transforms
```
{"type":"RECORD","record":{"stream":"table1","data":{"id":1},"emitted_at":1622208594225}}
``` 
into 
```
{"type":"RECORD","record":{"namespace":"my-ns", "stream":"table1","data":{"id":1},"emitted_at":1622208594225}}
```
and modifies the `AirbyteStream` type accordingly. 

It's diverging further from the solution I am proposing. 
I would like to get keep the message as it is, and do the namespace, name (`prefix + stream.name` or manual) in the `ConfiguredAirbyteStream` type.

**Comment by ajzo90** [comment]
This is how I'm thinking:
On the destination side you (probably) need to open (or prepare a statement, or whatever makes sense) a resource and get back a handle/reference for each stream and put it to a map: `stream -> handle`. In the open/prepare you use the namespace and name from the config and when you need the handle/reference in the record iterations you get the handle from the original stream name.

**Comment by evantahler** [comment]
I'm going to close this issue for now, as we've made some updates!
* STATE messages now can be per-stream or global
* Streams can have namespaces!
* The worker does record how many records of each type have been emitted, and stores that information as a summary of the sync
* the new AirbyteTraceMessage allows for additional metadata to be emitted from sources.  Today that's error message decoration, but in the future it will be metrics and stats with which we can display better information as a sync is running.  

Thanks for all the ideas!
