### ISSUE TITLE
[source_younium] Unable to connect to stream account 

### ISSUE THREAD

**Issue by KapitanFernand** [airbytehq/airbyte#39451]
### Connector Name

source_younium

### Connector Version

0.3.4

### What step the error happened?

During the sync

### Relevant information

Trying to authenticate the younium source with credentials, I have the following issue:
```
Configuration check failed
'Unable to connect to stream account - Error while generating access token: {"error":"invalid_grant","error_description":"invalid_username_or_password"}'
```

The issue is I believe a change of auth URL made by younium

### Contribute

- [X] Yes, I want to contribute

**Comment by KapitanFernand** [comment]
This could be solved in:
- _airbyte-integrations/connectors/source-younium/source_younium/manifest.yaml_
by replacing:
`    url_base:
      "{{ 'https://apisandbox.younium.com' if config['playground'] else 'https://api.younium.com'
      }}"
    http_method: "GET"`
to:
`    url_base:
      "{{ 'https://apisandbox.younium.com' if config['playground'] else 'https://eu.younium.com'
      }}"
    http_method: "GET"`

**Comment by marcosmarxm** [comment]
@KapitanFernand would be nice to find Younium API documentation showing where the `eu.` prefix is valid and exists others. Let say you're in USA or Europe. Maybe the solution is to introduce a toggle selector to help the user.

**Comment by KapitanFernand** [comment]
Looks like I wrongly thought the current domain was not available anymore for the EU. It's still weird for younium to allow you to log in from eu.younium.com or app.younium.com - apologize for the confusion
