### ISSUE TITLE
Issue starting airbyte from docker-compose

### ISSUE THREAD

**Issue by arjunanandkumar** [airbytehq/airbyte#39454]
### Topic

Cannot start airbyte

### Relevant information

I'm trying to run Airbyte on an M2 mac, and can't seem to get it up and running going by the instructions [here](https://docs.airbyte.com/deploying-airbyte/docker-compose).

The worker and server never start, and it is constantly looping over this:

```
airbyte-worker                    | 2024-06-13 11:49:36 WARN i.a.c.t.TemporalUtils(getTemporalClientWhenConnected):158 - Waiting for namespace default to be initialized in temporal...
```

Any idea what is going on here?

**Comment by marcosmarxm** [comment]
I'm closing this issue as there are no steps provided to recreate the problem, and no other users have reported the same issue.
