### ISSUE TITLE
v0.63.0 validation error array items[14,54] must be unique

### ISSUE THREAD

**Issue by fdegier** [airbytehq/airbyte#39481]
### Platform Version

0.63.0

### What step the error happened?

On deploy

### Relevant information

Existing installation was working fine, following steps in documentation to upgrade.

```
curl -sOO https://raw.githubusercontent.com/airbytehq/airbyte/master/run-ab-platform.sh
./run-ab-platform.sh -r
./run-ab-platform.sh --dnt
```

Error:
```
validating ~/airbyte/docker-compose.yaml: services.server.environment array items[14,54] must be unique
```

**Comment by bago2k4** [comment]
+1

**Comment by matttsai-orx** [comment]
+1

**Comment by marcosmarxm** [comment]
@kodermax @bago2k4 @fdegier Docker compose is  scheduled to be deprecated. I'm closing the issue as this won't be fixed. Please move your deployment to use `abctl` or Helm.

More information: https://github.com/airbytehq/airbyte/discussions/40599
