### ISSUE TITLE
[source-appsflyer] `organic_in_app_events` doesn't load data for all dates 

### ISSUE THREAD

**Issue by aalkuatova** [airbytehq/airbyte#39484]
### Connector Name

source-appsflyer

### Connector Version

0.2.1

### What step the error happened?

Other

### Relevant information

[appsflyer_logs.txt](https://github.com/user-attachments/files/15836678/appsflyer_logs.txt)
![image](https://github.com/airbytehq/airbyte/assets/87410465/cff8dec0-5809-49f5-b585-b3057c0276dc)

With a new connector version (0.2.1) organic_in_app_events endpoint when running sync starting from 90 days (as the max possible historical date in api) it loads data for random dates not covering every date (provided in screenshot). 

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/39407
