### ISSUE TITLE
Automatically add newly-released connectors to existing airbyte workspaces

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3949]
## Tell us about the problem you're trying to solve
When a new connector is released, existing users don't have an easy path for starting to use it. They have to add it as a custom connector which is cumbersome.

## Describe the solution you’d like
I would like to have a button on the Admin UI similar to the "update all connectors" button which adds all new connectors to the Airbyte instance's connector index. 

This might require a backend API update too as I think(?) right now updating connector versions would require downloading each of their docker images which could unnecessarily take a lot of space on the host machine.

**Comment by cgardens** [comment]
@sherifnada do we need a button for this? Should we just show connectors that are available in github but not yet installed like we would any other connector? Then if the user selects it, we would just automatically download it?

**Comment by sherifnada** [comment]
@cgardens I like that approach more. This could happen automatically on the backend I suppose where every time we fetch the latest list of connectors, new ones automatically get added to the index

**Comment by cgardens** [comment]
we do this.
