### ISSUE TITLE
Stripe: Duplicate records in a full rewrite stream

### ISSUE THREAD

**Issue by killthekitten** [airbytehq/airbyte#39583]
### Platform Version

0.60.0

### What step the error happened?

During the Sync

### Relevant information

This has happened in the Stripe v3.17.4 -> BigQuery v1.2.20 sync on a self-hosted Airbyte 0.60.0.

Every record in the subscriptions table is duplicated twice, with the same hash and normalization date but different `_airbyte_emitted_at` and `_airbyte_ab_id`:

![image](https://github.com/airbytehq/airbyte/assets/1201569/077aee18-6f44-41b1-b0c8-e7e1adefe86b)

Not sure how relevant this is, but this morning we restarted the Airbyte instance in the middle of the sync. The stream is set to full rewrite.

**Comment by killthekitten** [comment]
The issue fixed itself in the following sync. Given that the Stripe syncs are generally long – we had to wait 24 hours for it to be over – I'd love to prevent this from happening in the future

**Comment by marcosmarxm** [comment]
The Bigquey connector version reported in the issue is an old one. Please update to the latest one and if the issue repeats open a new issue reporting the problem.
