### ISSUE TITLE
Depoly Failed

### ISSUE THREAD

**Issue by jusl-song** [airbytehq/airbyte#39623]
### Helm Chart Version

0.63.1

### What step the error happened?

On deploy

### Relevant information

Kubernetes v1.21.11

NAME                               	CHART VERSION	APP VERSION	DESCRIPTION
airbyte/airbyte                    	0.199.0      	0.63.1     	Helm chart to deploy airbyte
airbyte/airbyte-api-server         	0.199.0      	0.63.1     	Helm chart to deploy airbyte-api-server
airbyte/airbyte-bootloader         	0.199.0      	0.63.1     	Helm chart to deploy airbyte-bootloader
airbyte/airbyte-cron               	0.40.37      	0.40.17    	Helm chart to deploy airbyte-cron
airbyte/airbyte-workload-api-server	0.49.18      	0.50.33    	Helm chart to deploy airbyte-api-server
airbyte/connector-builder-server   	0.199.0      	0.63.1     	Helm chart to deploy airbyte-connector-builder-...
airbyte/cron                       	0.199.0      	0.63.1     	Helm chart to deploy airbyte-cron
airbyte/keycloak                   	0.199.0      	0.63.1     	Helm chart to deploy airbyte-keycloak
airbyte/keycloak-setup             	0.199.0      	0.63.1     	Helm chart to deploy airbyte-keycloak-setup
airbyte/metrics                    	0.199.0      	0.63.1     	Helm chart to deploy airbyte-metrics
airbyte/pod-sweeper                	0.199.0      	0.63.1     	Helm chart to deploy airbyte-pod-sweeper
airbyte/server                     	0.199.0      	0.63.1     	Helm chart to deploy airbyte-server
airbyte/temporal                   	0.199.0      	0.63.1     	Helm chart to deploy airbyte-temporal
airbyte/webapp                     	0.199.0      	0.63.1     	Helm chart to deploy airbyte-webapp
airbyte/worker                     	0.199.0      	0.63.1     	Helm chart to deploy airbyte-worker
airbyte/workload-api               	0.50.3       	0.50.35    	Helm chart to deploy the workload-api service
airbyte/workload-api-server        	0.199.0      	0.63.1     	Helm chart to deploy the workload-api service
airbyte/workload-launcher          	0.199.0      	0.63.1     	Helm chart to deploy airbyte-workload-launcher

### Relevant log output

```shell
Error: INSTALLATION FAILED: failed pre-install: unable to build kubernetes object for pre-install hook airbyte/templates/env-configmap.yaml: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.AIRBYTE_URL
```

**Comment by marcosmarxm** [comment]
Closing as it lack steps to reproduce the problem or provide information about OS etc. @jusl-song please open a new issue an provide all information can be useful to reproduce the issue in other env.
