### ISSUE TITLE
Snowflake Connector not finishing sync

### ISSUE THREAD

**Issue by tylerdelange** [airbytehq/airbyte#3967]
## Current Behavior
When trying to do a mySQL -> Snowflake sync I am seeing an issue which appears that Snowflake completed freezes when processing data. This occurs when trying to use both "Standard Inserts" and "AWS S3 Staged". 

Total Size of mySQL DB 1 GB
Table Schema is attached.
[BorrowersTableSchema.pdf](https://github.com/airbytehq/airbyte/files/6619240/BorrowersTableSchema.pdf)

Trying to import 2.3 Million records.
mySQL sync completes.
Snowflake does not, Included in the snowflake logs. As of this time nothing has happened for over an hour, and airbyte still show the connection in "syncing" status. Also, I have not seen anything written yet to a S3 bucket.

## Severity of the bug for you
High

## Airbyte Version
0.24.7

## Connector Version (if applicable)
mySQL 0.3.5
Snowflake 0.3.7

[SnowflakeLogs.txt](https://github.com/airbytehq/airbyte/files/6619027/SnowflakeLogs.txt)

**Comment by tylerdelange** [comment]
I just did a test locally with docker and the sync works. Maybe this is my EC2 docker running out of memory?

**Comment by marcosmarxm** [comment]
@tylerdelange could add more information about this error?

**Comment by marcosmarxm** [comment]
Closing this, @tylerdelange was able to run the sync after scaling up the instance.
