### ISSUE TITLE
Adding a new integration shouldn't require a code change

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#397]
## Tell us about the problem you're trying to solve
Today adding an integration requires:

* adding an integration spec to the project (config/init)
* modifying Integrations.java

## Describe the solution you’d like
The integration should be fully contained in a docker image and we should expose a way to register that integration into Airbyte.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368232463321) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
I think we achieved this with the admin tab.
