### ISSUE TITLE
Improve Python package formatting workflow

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3971]
## Tell us about the problem you're trying to solve
Today if I run `:airbyte-integrations:connectors:source-blah:airbytePythonFormat` then only `.py` files are formatted. This means I still need to run `./gradlew format` on the whole project to format any JSON files (or any other type) in the directory. This somewhat defeats the point

## Describe the solution you’d like
I propose two solutions: 
1. rename `airbytePythonFormat` to just `format` which is easier to remember
2. run other formatters in that directory only. 

Alternatively we may want to encapsulate the formatting logic entirely within the Python package and stop relying on Gradle entirely for formatting (but still allow gradle to run formatting in CI), maybe by using a make-based approach.

**Comment by keu** [comment]
solved by #4005
