### ISSUE TITLE
[EPIC] Support "reverse ELT" destinations i.e: API destinations 

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3982]
Today we only support loading into file systems/data bases/data warehouses. 

In the near future, we also want to support loading into api systems for the 'reverse etl' use case.

**Comment by SanjeevSingla19** [comment]
Please include bulk data import to Shopify.

**Comment by bizzareus** [comment]
Looking forward to this. Loading data through APIs.

**Comment by sherifnada** [comment]
@SanjeevSingla19 @bizzareus would either of you be open to having a call with our team to understand your usecase for reverse ETL?

**Comment by mkstayalive** [comment]
@davinchia @SanjeevSingla19 @bizzareus Airbyte currently doesn't support this use case and they don't have a milestone for this. Please check out Castled.io's Github repo (I'm a maintainer), it may fit your needs - https://github.com/castledio/castled

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Reverse ETL](https://app.harvestr.io/components/0/list/QWeYaPxyb)
