### ISSUE TITLE
New Source Typeform

### ISSUE THREAD

**Issue by lctammy** [airbytehq/airbyte#3988]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**Comment by sherifnada** [comment]
The connector should pull data for a single form ID input by the user. 

Endpoints we should support: 
* [Forms](https://developer.typeform.com/create/reference/retrieve-form/) -- this should be full refresh only
* [Form Responses](https://developer.typeform.com/responses/reference/retrieve-responses/) -- this should be incremental

We currently do not have an account with Typeform. We'll need to: 
1. create one using integration-test@airbyte.io. We should pay for the lowest pricing tier which gives API access. 
2. populate it with data (probably through the API) creating forms, questions, and responses -- important: we should populate every field so when integration tests are running they accurately verify that we read every field
3. implement the connector

**Comment by cheyura** [comment]
Typeform Account created. Creds in LastPass. DevApp with ClientID and Client Secret also created so that you can generate access tokens for API requests.(Oauth 2.0)
Credit Card is not attached since up to 10 responses is free (we can populate data with UI for free). Lets discuss with @sherifnada if need some payments

**Comment by sherifnada** [comment]
@cheyura once we begin impl let's use the cheapest subscription tier -- let's wait until we are about to implement this connector though

**Comment by cheyura** [comment]
> @cheyura once we begin impl let's use the cheapest subscription tier to populate with data

@sherifnada 10 responses is free. Is that enough?

**Comment by sherifnada** [comment]
can we do a few hundred? say 200-300?

**Comment by cheyura** [comment]
> can we do a few hundred? say 200-300?
@sherifnada 250 responses per month - 33.5 USD. Ok?

**Comment by sherifnada** [comment]
ok
