### ISSUE TITLE
[source-mongo]  data loading only first time

### ISSUE THREAD

**Issue by mohithsairamreddy** [airbytehq/airbyte#39917]
### Connector Name

mongodb

### Connector Version

1.3.15

### What step the error happened?

During the sync

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@mohithsairamreddy can you provide more information about the connection? How big is the Mongo collection? Can you try another destination to ensure this is not a problem with S3? Can you share a log file or a screenshot providing more details about the issue?

**Comment by marcosmarxm** [comment]
Closed due to lack of response.
