### ISSUE TITLE
Allow headers to be added in the request for refreshing access token

### ISSUE THREAD

**Issue by santels** [airbytehq/airbyte#4016]
## Tell us about the problem you're trying to solve
Regarding the connector development, I'm using the [OAuth2Authenticator](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/auth/oauth.py) and I see that there's currently no way to add header(s) to the [token refresh call](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/streams/http/auth/oauth.py#L79).

The source I'm working on requires an authorization header (Basic token) to be able to send an authorized header to their authorization server.

## Describe the solution you’d like
It's good if the developers have an option to attach an optional header as the OAuth2Authenticator is instantiated--which will be used in the `refresh_access_token` method.

## Describe the alternative you’ve considered or used
No alternatives so far except from modifying the OAuth2Authenticator class to accept headers.

**Comment by Zirochkaa** [comment]
## Task breakdown

- [ ] Accept headers in `__init__()` and use them in `refresh_access_token()`;
- [ ] Add tests for headers.
