### ISSUE TITLE
[Blocker] Airbyte sync jobs are failing with docker repo throttle error

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#40213]
### Connector Name

source-gitlab

### Connector Version

0.1.6

### What step the error happened?

During the sync

### Relevant information

docker registry API is throttling and there is no option to append custom artificatory prefix .  I would like to change to 

jfrog.io/airbyte/source-gitlab:0.1.6 instead of docker.io/airbyte/source-gitlab:0.1.6. it would be great if you can add it in  airbyte config 

### Relevant log output

```shell
Failed to pull image "airbyte/source-gitlab:0.1.6": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/airbyte/source-gitlab:0.1.6": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/airbyte/source-gitlab/manifests/sha256:ead1096ab45cc01c705e1e3e8392d98bd8015145271079b0776b1c4d0e591e3c: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
If you need more quota to request connector images from Dockerhub the recommendation is to login to Docker.

**Comment by ana-cafemedia** [comment]
I am encountering the same issue. Logging in to Docker does not resolve this problem as there is a rate limit to how many times you can pull :-(
