### ISSUE TITLE
Invalid parsing of mongodb _id field (UUID field,  type: binData)

### ISSUE THREAD

**Issue by siddharth96ss** [airbytehq/airbyte#4021]
## Expected Behavior
If the _id field in mongodb is **UUID** of form
```
"_id": {
        "$binary": "YkrYedM4QKGkq0lkcTZ4pQ==",
        "$type": "3"
    }
```

Then, it should be parsed as a hexadeimal string as shown below

**hexadecimal string:**

`"624ad879-d338-40a1-a4ab-4964713678a5"`

## Current Behavior

Currently, the _id field is being parsed as a string like **"#<BSON::Binary:0x00007f70d8381350>"**
In this process, **information is being lost**. the _id field which was unique in mongodb now has duplicates after being parsed this way.

## Steps to Reproduce
1. Have a mongodb table with an _id field in the form Binary("xxxxxxxxx" , 3)
2. Sync it into your warehouse

## Severity of the bug for you
High, it's blocking all development with our data because now the _id column has duplicates.

## Airbyte Version
0.23.0-alpha

## Connector Version (if applicable)
MongoDb connector.  Version: 0.3.1

## Additional context

Node.js code to convert UUID to hexadecimal
```

function Bin2HexUUID(bin){
    var hex = new Buffer(bin, 'base64').toString('hex');
    return hex.replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/, function (){
        return arguments[1]+"-"+arguments[2]+"-"+arguments[3]+"-"+arguments[4]+"-"+arguments[5];
    });
}
//use example
var binary_id = { "$binary" : "YkrYedM4QKGkq0lkcTZ4pQ==", "$type" : "3" };
console.log(Bin2HexUUID(binary_id.$binary));


```

**Comment by davinchia** [comment]
@sherifnada had a meeting with the folks who filed this ticket today. they have a business deadline of 4 weeks so it'll be great if can get to this before hand.
