### ISSUE TITLE
[Roadmap] Track incrementally synced rows (add an "_AIRBYTE_SYNC_ID" column)

### ISSUE THREAD

**Issue by justin-dropbase** [airbytehq/airbyte#4025]
## Tell us about the problem you're trying to solve

I'd like to keep track of which rows correspond to which sync job by attaching a sync ID beside each row. For example, if I sync a connection at 6 AM, then receive new data in a sync at 10 AM, how can I tell exactly which new rows were from the 10 AM sync? The closest feature that Airbyte offers is the _AIRBYTE_EMITTED_AT column, but I don't think it can be used to effectively distinguish sync jobs. [I confirmed on Slack here](https://airbytehq.slack.com/archives/C01MFR03D5W/p1623253333331900) that this feature does not exist and was recommended to open this issue. 

## Describe the solution you’d like
This is what I'd ideally like: The first row comes from Sync A and the second row came from Sync B. I can tell the sync job that each row came from by the "batch_id" (or sync_id) column. I believe this functionality would be compatible with the "Incremental Sync" options since I'm assuming "Full refresh" wouldn't allow for this. 

![syncid](https://user-images.githubusercontent.com/83237369/121531201-3256e900-c9cc-11eb-9b71-1742de585237.png)

**Comment by michel-tricot** [comment]
Hey Justin, that's a very good issue. We want to track a lot more meta-data about replications. 

@cgardens FYI

**Comment by cgardens** [comment]
Thanks! I agree as well.

**Comment by cgardens** [comment]
note: from planning meeting. we should be thoughtful about other metadata to include.

**Comment by michel-tricot** [comment]
Should we store these metadata as a json object?

**Comment by haliva-firmbase** [comment]
@cgardens is there an ETA when it's going to be released?

**Comment by cgardens** [comment]
@haliva-firmbase my hope is that we would start work on this in the next 2 weeks. we will be doing some work on our scheduler and will likely bundle this in as part of that project.

**Comment by andreasholmesberge** [comment]
Any updates on the status of this? is it in progress, any eta? this will help a lot!

**Comment by cgardens** [comment]
@andreasholmesberge thanks for your interest. Obviously my previous estimate was off. 😞 . We ended up having to re-prioritize in some other features. Right now we are targeting to start work on this in the second week of october.

**Comment by animer3009** [comment]
This issue is from 2021...
Something new happening about this?
Are you going add mew column?
I guess this is very important change.

**Comment by animer3009** [comment]
even just one new column witch will show unique ID for sync iteration will help a lot!

**Comment by evantahler** [comment]
cc @malikdiarra would it be possible to get the the platform's job_id as an environment variable sent to the connector?

**Comment by nauxliu** [comment]
I'm also facing the same issue as @animer3009

**Comment by davinchia** [comment]
We will be adding this column. I expect this to be released in the next few months. @evantahler is in charge of this work.

**Comment by evantahler** [comment]
Note: sync_id will be added to the `_airbyte_meta` JSON column within [V2 destinations](https://docs.airbyte.com/release_notes/upgrading_to_destinations_v2)

**Comment by tturkenitz** [comment]
Hi, I might be mistaken, but it seems like V2 Destinations are only relational DBs. Is there a reason why we can't have a unique identifier for a Sync Job regardless of the destination?

Today, Airbyte emits `_airbyte_ab_id` and `_airbyte_emitted_at`, can we not have a `_airbyte_sync_id` and lock use the Sync Job identifer for this purpose?

**Comment by evantahler** [comment]
Now that the Airbyte platform provides sync_id to the destination, it's up to every destination to include it in how it writes the records.  We'll be taking care of updating the certified destinations, and relying on our community to update the rest.

**Comment by tturkenitz** [comment]
Absolutely, evantahler.

It just wasn't clear from your last comment if the work will be limited to V2 or all certified connectors. Community connectors are up to the community to update - no question about it. 

Thanks!

**Comment by evantahler** [comment]
Closing this issue as our certified destinations now store sync_id within the _airbyte_meta object column!
