### ISSUE TITLE
Add option to not delete staging data using snowflake/redshift destination

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4030]
## Tell us about the problem you're trying to solve
As a user I want to keep the staging data transferred to S3/GCS for future usages (change the datawarehouse, use Athena)

## Describe the solution you’d like
Add an option to select (delete/keep staging data) when creating the destination with the S3 staging option.

For this to be useful, the output path persisted by the connector needs to be predictable so users can consume it reliably. For example, it needs to have a pattern like: 

`s3://<bucketname>/<some_prefix>/<source_data_namespace_name>/<table_name>/*files*` 

See the [S3 destination connector docs](https://docs.airbyte.io/integrations/destinations/s3#configuration) for an example of what this path should look like. 

## Implementation steps
There are roughly two stages to implementing this: 
1. [ ] Instead of re-inventing the wheel w.r.t output paths and whatnot, refactor the redshift destination to use the S3 CSV writer under the hood (`S3CsvWriter.java` in the `io.airbyte.integrations.destination.s3.csv` package) - https://github.com/airbytehq/airbyte/issues/8550
2. [ ] Add and leverage a boolean flag to the connector configuration which configures whether or not the data is retained after a sync to redshift. - https://github.com/airbytehq/airbyte/issues/8552

Start by doing this for the Redshift destination only. We can get to Snowflake afterwards. 

Please create GH issues for both of these and add them to the upcoming ConnCore milestone for clearer tracking of the components of this issue. 

### Refactoring the redshift destination to use the S3 destination code
1. Rename and `@Deprecate` the existing `S3StreamCopier` and `S3StreamCopierFactory` classes to indicate that this implementation should no longer be used. The reason we're renaming and deprecating instead of just refactoring the class itself is because that class is used by other destinations like Snowflake etc.. so we are trying to limit the scope of the connectors we're changing here. 
2. Create a new class `S3StreamCopier` which leverages the S3 class `S3CsvWriter` under the hood. See the `DatabricksStreamCopier` class for an example of what reusing an S3Writer looks like. That example uses Parquet but it should be very similar to what you will need to do here. You should take care to ensure that your implementation is functionally equivalent to the deprecated class in step 1, apart from re-using . Take care to write unit tests for this class. 
3. Refactor the `RedshiftStreamCopier` class to use the class you created in step 2. Also write unit tests for this class as needed. once again, apart from filepaths, it should function the same as the previous implementations. 
4. Test and publish the redshift copy destination.

By the end of this step, staging files should now be output in a filesystem path equivalent to the one used by the S3 destination. Apart from this, no functionality should be changed. 

Congrats! You're (logically speaking) halfway there. 

### Adding and leveraging the boolean flag
Now we need to expose a user configuration which leverages 
1. Expose a boolean option in the spec.json allowing the user to configure. Familiarize yourself with the [Connector Developer UX handbook](https://docs.airbyte.io/connector-development/ux-handbook) to understand how the title and description properties should be set on this option. After Octavia Squidington III, the UX handbook is a connector developer's best friend. 
2. Pass the parameter throughout the destination, appropriately using it to decide whether or not to delete the staging files. Note that it may be useful to expose a new method in the `S3StreamCopier` class (and `S3CsvWriter`) class `Map<String, String> getStreamOutputPaths()` which returns the paths in which files for different streams are written. This will allow the Redshift destination to be told where the output paths are, instead of assuming them, which is dangerous since a refactor of the S3CsvWriter to write files to a different location would break the Redshift Copy destination. 
3. Write unit tests for all of this functionality. 
4. create a PR, publish, etc...

## Are you willing to submit a PR?
No

**Comment by bioticinteractions** [comment]
would be a great feature.

**Comment by danieldiamond** [comment]
@tuttle please add your 👍  to the issue description. this is a useful measure for the airbyte team to understand user feature requests and i imagine help prioritise

**Comment by bioticinteractions** [comment]
for my use case, having it up in s3 means we're able to distribute the data through s3 rather than snowflake. We're finding it would be faster and easier to go through s3 since that is our data lake rather than query a relational database.

as far as having the 'raw' data still in the relational database, that would be fine with me. options would definitely be appreciated: (1) only relational database (2) only blob storage, (3) both relational and blob.

if that's the s3 object would be the exact 'raw' tables in the relational database, thats fine! it wouldnt be optimal, since i would prefer a 'standard' tabular format but thats a trivial problem.

one additional feature could be (that would largely be 'dressing') to customize the s3 key: `/yyyymmddss_replication_namespace/....../table_name_namespace_id.parquet'

but again, no worries on the aesthetics of things. if airbyte just keeps the objects in the namespace for each run, we can deal with that too! thanks

**Comment by ChristopheDuong** [comment]
> for my use case, having it up in s3 means we're able to distribute the data through s3 rather than snowflake. We're finding it would be faster and easier to go through s3 since that is our data lake rather than query a relational database.

> one additional feature could be (that would largely be 'dressing') to customize the s3 key: `/yyyymmddss_replication_namespace/....../table_name_namespace_id.parquet'

Are you aware of this destination https://docs.airbyte.io/integrations/destinations/s3 ? 
Could you give more details on why using a pure blob storage destination such as that one would not be preferable, rather than use a snowflake/redshift destination and keep their staging persisted after the sync?

**Comment by tuliren** [comment]
This option is already implemented for the Databricks destination:

Option:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-databricks/src/main/resources/spec.json#L144

Code:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-databricks/src/main/java/io/airbyte/integrations/destination/databricks/DatabricksStreamCopier.java#L186

It should be pretty simple to do.

**Comment by edgao** [comment]
redshift was completed in https://github.com/airbytehq/airbyte/issues/8552
snowflake was completed in https://github.com/airbytehq/airbyte/issues/8820
