### ISSUE TITLE
Support Postgres SSL connection

### ISSUE THREAD

**Issue by batianusrey** [airbytehq/airbyte#4034]
Currently the Postgres connector has an SSL toggle, however there is no where to specify the appropriate information to establish the SSL connection:
- CA certificate.
- Client certificate.
- Client key.
- Client key password.
- SSL Mode.

This is a must for us a all the connections to our Postgres databases require SSL.

**Comment by TMFRook** [comment]
Is this still actually in progress? FWIW I observed the communication between Airflow and my Postgres db is encrypted.

**Comment by TMFRook** [comment]
Just to be clear, SSL is implemented for Postgres, right? Just that these options can't be used.

**Comment by james-accel** [comment]
The lack of functionality to allow for client certificates etc to be specified for a Postgres connector is a blocker for us to use Airbyte. Specifically our use case is connecting to a Heroku private space DB, which allows for external connections using certificates.

**Comment by alexandr-shegeda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/4034?planning-poker) with ZenHub @andriikorotkov

**Comment by andriikorotkov** [comment]
@alexandr-shegeda

**Comment by grishick** [comment]
@andriikorotkov given the limitations of current spec UI it makes sense to make SSL option as oneOf. However, I do not like the idea of making a backwards incompatible change, as we haven't yet figured out how to gracefully handle backwards incompatible change in spec during an upgrade. Ideally, we would have an ability to show/hide fields conditionally (there is a proposal and a spec in the works for that). I suggest we keep SSL option as boolean on/off flag and add the other SSL options as optional. Once the UI is able to show/hide fields based on values of other fields, we'll improve the UI for the SSL-specific options.

**Comment by VitaliiMaltsev** [comment]
https://github.com/airbytehq/airbyte/pull/14574 was merged. Please proceed
