### ISSUE TITLE
Airbyte feature requests

### ISSUE THREAD

**Issue by dmdmishra** [airbytehq/airbyte#4037]
Hi Team,

Does airbyte provides or plan to provide any of the following features/connectors:

1) API to start / view status of job in airbyte.
2) Connector for Denodo - data virtualization platform
3) Kafka consumer connector
4) data quality or data validation within airbyte to produce results with good and bad records after validation checks. Something what great expectations does.
5) CDC support for oracle and SQL server including all dml operations on primary keys , partitions , updates , deletes and truncates.
6) convert input files into desired output files, like JSON to avro or JSON to CSV etc..
7) calling custom API as source and target connectors.
8) data encryption at rest and transit
9) running transformation within snowflake without moving the data out of it and using the processing power of snowflake.
10) using spark mpp power to move historical data for m source to s3.

**Comment by dmdmishra** [comment]
Any thought

**Comment by marcosmarxm** [comment]
@dmdmishra all of them are valid suggestion. But can you open specific issues to them be discuss individually?

**Comment by marcosmarxm** [comment]
For point 3: https://github.com/airbytehq/airbyte/issues/2655

**Comment by marcosmarxm** [comment]
> data quality or data validation within airbyte to produce results with good and bad records after validation checks. Something what great expectations does.
We have source connection json or csv and you can choose the destination you prefer. At the moment we support json or csv. You can create specific issues to have avro.

**Comment by marcosmarxm** [comment]
> running transformation within snowflake without moving the data out of it and using the processing power of snowflake.

We recently release the custom operators where you can use dbt with snowflake to do this. You can read more about [here](https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-airbyte)

**Comment by marcosmarxm** [comment]
Closing this because is not a unit of request and need to break into each point. @dmdmishra  Feel free to open them invidually.
