### ISSUE TITLE
Add an environment variable to set the web app port

### ISSUE THREAD

**Issue by otravers** [airbytehq/airbyte#4049]
## Tell us about the problem you're trying to solve
I'm trying to set up a Portainer stack using the git repository without having to download and edit docker-compose.yaml file.

## Describe the solution you’d like
Have the ability to set the web app port to something else than 8000 via an environment variable.

## Additional context

Portainer provides a convenient GUI to manage Docker containers, images, networks, etc. Via its "stacks" you can load a series of containers directly from Github, which is what I'm trying to do with Airbyte:
![image](https://user-images.githubusercontent.com/3731532/121611923-60b5e200-ca27-11eb-8482-72fdf8919c82.png)

https://documentation.portainer.io/v2.0/stacks/create/

**Comment by marcosmarxm** [comment]
@otravers I think this is great. do you want to contribute to that?

**Comment by otravers** [comment]
Sorry, I don't have the dev skills.

**Comment by marcosmarxm** [comment]
No problem @otravers. I submit a PR to enable this kind of deploy.

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by marcosmarxm** [comment]
Today Airbyte uses the proxy container. Closing because it doesn't reflect the project status.
