### ISSUE TITLE
Improve doc develop locally

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4050]
### Tell us about the documentation you'd like us to add or update.
Some users want to contribute to Airbyte adding or changing connectors but think for that need to deploy Airbyte core.
We should made this more clear to contributors that is not necessary to do that.

@avaidyanatha WDYT?

### If applicable, add links to the relevant docs that should be updated
- [Developing Locally](https://docs.airbyte.io/contributing-to-airbyte/developing-locally)

**Comment by avaidyanatha** [comment]
Yeah agreed, I think there's also some other improvements to this doc that can be made along the way.

**Comment by marcosmarxm** [comment]
I really like the [Airflow Contributors Quickstart](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst)
It's directly to ALL type of users. For Airbyte should exists one for CORE changes and another for CONNECTORS.
