### ISSUE TITLE
automatically clean up temporary tables from failed syncs 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4059]
If a destination fails, a bunch of `_airbyte_<some number, not ‘raw’>` temporary tables exist and are never cleaned up. See https://airbytehq.slack.com/archives/C019WJFR1JT/p1623378865339700 for an example of someone manually cleaning these up.

We should clean these up automatically. I imagine this should happen within the connectors. Maybe if the timestamp for the temporary run is > a certain threshold?

**Comment by marcosmarxm** [comment]
This is a duplicate of https://github.com/airbytehq/airbyte/issues/7011
