### ISSUE TITLE
Webapp to take TRACKING_STRATEGY into account

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#406]
## Tell us about the problem you're trying to solve
Webapp has segment always enabled

## Describe the solution you’d like
Webapp should take TRACKING_STRATEGY into account and only use segment if configured so.

**Comment by Jamakase** [comment]
@michel-tricot The thing is that env variables for webapp are bundled during the build ( `gradle build` ) and any changes in .env and docker-compose won't affect them.

Though If .env will be added into airbyte-webapp directory - then dotenv plugin will pick them, but I suppose it is not convenient to store env variables in different places.

As a possible solution: we can update airbyte-webapp/build.gradle to also get variables from `root/.env` during the build and they will be bundled into the assets.

If we want to manipulate what variables are used during `docker-compose up` then in case we still follow static bundle way - we can have node server or nginx to replace variable with name `SERVER_VAR_REPLACE` to env variable provided to the process before returning assets to client. 

Or we need to consider having a sort of SSR, to build a page on the fly but it is a bit different task.

**Comment by cgardens** [comment]
> If we want to manipulate what variables are used during docker-compose up then in case we still follow static bundle way - we can have node server or nginx to replace variable with name SERVER_VAR_REPLACE to env variable provided to the process before returning assets to client.

I think this sounds like what we want. For all of our other docker containers, these env variables are passed on `docker-compose up`, so I think what you described here matches best.
