### ISSUE TITLE
MSSql source using a non-clustered index for initial snapshot

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#40602]
### Connector Name

source-mssql

### Connector Version

4.0.32

### What step the error happened?

During the sync

### Relevant information

An mssql table contains a primary key in a *non*clustered index,
and a clustered index.

In this case our initial sync is supposed to prefer the clustered index when choosing an `orderedColumn`
But we see in log
```
selected ordered column field name: [nonclustered primary key]
```

This leads to slow sync and to possible locking - due to unnecessary sorting by primary key.

Ensure that the correct logic is applied when selected the ordered column for the purpose of initial sync.

### Relevant log output

```shell
https://cloud.airbyte.com/workspaces/53188b95-9f00-4378-bdbd-1637091163d9/connections/e6d01f4e-d804-486b-8112-af61a48a0791/job-history#13831210::0
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by octavia-squidington-iii** [comment]
Zendesk ticket #[7082](https://airbyte1416.zendesk.com/agent/tickets/7082) has been linked to this issue.

**Comment by evantahler** [comment]
[Relevant slack thread ](https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1719252875278429)
