### ISSUE TITLE
MongoDB JSON Arrays Appearing with Ruby syntax in target

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#4062]
## Expected Behavior
JSON Objects and Array types retrieved from MongoDB should be valid JSON arrays with key:value pairs

## Current Behavior
Data appears with Ruby hash syntax key=>value  , example below  

"hrBests": "[{\"value\"=>180, \"startTick\"=>2081, \"duration\"=>5}, {\"value\"=>180, \"startTick\"=>2080, \"duration\"=>10}, {\"value\"=>179, \"startTick\"=>2078, \"duration\"=>30}, {\"value\"=>178, \"startTick\"=>2075, \"duration\"=>60}, {\"value\"=>176, \"startTick\"=>1992, \"duration\"=>120}, {\"value\"=>173, \"startTick\"=>1898, \"duration\"=>300}, {\"value\"=>169, \"startTick\"=>1723, \"duration\"=>480}, {\"value\"=>167, \"startTick\"=>1633, \"duration\"=>600}, {\"value\"=>159, \"startTick\"=>1033, \"duration\"=>1200}, {\"value\"=>155, \"startTick\"=>433, \"duration\"=>1800}]"

## Logs
[logs-24-0.txt](https://github.com/airbytehq/airbyte/files/6640630/logs-24-0.txt)

## Steps to Reproduce
1. Create connection for MongoDB source to Redshift target (no normalization)
2. Execute data load
3. Review data in target

## Severity of the bug for you
High 

## Airbyte Version
0.24.6-alpha

## Connector Version (if applicable)
0.3.2

## Additional context
*Environment, version, integration...*

**Comment by marcosmarxm** [comment]
Hello @JCWahoo the MongoDB Java connector was released. Can you test it and check if your data is correctly transformed?

**Comment by marcosmarxm** [comment]
I'll close because this is from a deprecated connector.
