### ISSUE TITLE
Allow for custom schema per connection

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#4063]
## Tell us about the problem you're trying to solve
When setting up a connection, I'd like to select a custom schema/namespace in the destination so that each source is loaded to a separate target schema. Currently, to accomplish this would require setting up multiple destinations of the same type with unique target schemas

## Describe the solution you’d like
The ability to override the configured destination schema with a custom one at the connection level

## Describe the alternative you’ve considered or used
Currently using table prefixes, but as the number of sources grows this is becoming difficult to manage within a single schema

## Are you willing to submit a PR?

Not sure I can solve it, but happy to take look if you point me in the right direction

**Comment by cgardens** [comment]
Agreed. @ChristopheDuong is finishing up a project for that now: https://github.com/airbytehq/airbyte/issues/3481

My feeling is when that issue is complete, we'll have met the requirements mentioned in this issue.

**Comment by JCWahoo** [comment]
This is currently released, many thanks!
