### ISSUE TITLE
Add FullStory snippet to all pages in web app

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#4065]
## Tell us about the problem you're trying to solve
To improve the onboarding experience for users, by optimizing their path through the product. 

## Describe the solution you’d like
Add the Fullstory tracking snippet to all pages in Airbyte, so that we can utilize the data to review user sessions and understand where the UI/UX can be improved. 

## Describe the alternative you’ve considered or used
Alternative solutions like SmartLook, LogRocket.

## Additional context
A relevant help article from FullStory: https://help.fullstory.com/hc/en-us/articles/360020828233-Get-up-and-running
The FullStory snippet to deploy in the <head> of the web application:
```
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
window['_fs_org'] = '13AXQ4';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
    o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
    g.anonymize=function(){g.identify(!!0)};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.log = function(a,b){g("log",[a,b])};
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
    g.setVars=function(n, p){g('setVars',[n,p]);};
    g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
    if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
    g._v="1.3.0";
})(window,document,window['_fs_namespace'],'script','user');
</script>
```

**Comment by cgardens** [comment]
@nataliekwong will we be remove paper cups or are we just doing both in tandem?

**Comment by nataliekwong** [comment]
In tandem for now. I would like to validate FullStory is the solution for us before we migrate fully to it.

**Comment by jrhizor** [comment]
I added the snippet but we'll still want to have a customerId submitted per user.

We should also add customerId-level [identification](https://help.fullstory.com/hc/en-us/articles/360020828113-FS-identify-Identifying-users) like we do for Segment. I'm not positive where this should go (part of `AnalyticsService`? part of a different service?) so I'm going to switch the assignment to @Jamakase
