### ISSUE TITLE
Something went wrong within the airbyte platform

### ISSUE THREAD

**Issue by MoralesPablo** [airbytehq/airbyte#40666]
### Platform Version

CLOUD 

### What step the error happened?

During the Sync

### Relevant information

ALL our connectors are failing under the error: Something went wrong within the Airbyte platform.

**Comment by nataliekwong** [comment]
Hi there! 

For Cloud status and updates, you can follow along on the status page here: https://status.airbyte.com/. You can also reach out to our Technical Support team using the Help bar in the app.

I will close this for now, but let me know if you have further questions!
