### ISSUE TITLE
[source-postgres] Dead link of "Debezium heartbeat query (Advanced) -> setup guide" in postgres-source-connector

### ISSUE THREAD

**Issue by hongbo-miao** [airbytehq/airbyte#40690]
### Topic

postgres-source-connector

### Relevant information

Currently in this postgres-source-connector, this "Debezium heartbeat query (Advanced) -> setup guide" points to https://docs.airbyte.com/integrations/sources/postgres/postgres-wal-disk-consumption-and-heartbeat-action-query which is a dead link, it would be great to update, thanks! ☺️

![image](https://github.com/airbytehq/airbyte/assets/3375461/35681121-449d-4425-948d-b7cfe981122d)

**Comment by marcosmarxm** [comment]
@Adorism can you check this issue related to config docs?

**Comment by hongbo-miao** [comment]
Hi @marcosmarxm @marcosmarxm I fixed at https://github.com/airbytehq/airbyte/pull/40716 ☺️
Will track there, thanks!
