### ISSUE TITLE
Stripe Connector Balance Transactions Issue

### ISSUE THREAD

**Issue by akshayi1** [airbytehq/airbyte#4069]
## Expected Behavior
If I select all data objects to sync from Stripe to Postgres, all data should be synced (and normalized, since I'd selected that too) without any issues.

## Current Behavior
Currently, if I select Balance Transactions in addition to any other data object, it gets all the Balance Transactions (over 60k records), but once it reaches the end, it just hangs. It doesn't fail or anything, but neither does it proceed. However, if I exclude Balance Transactions, and select any other combination of data objects to sync from Stripe, it works perfectly.

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. Select all data objects for Stripe
2. Start the sync to Postgres
3. It hangs after Balance Transactions are synced (must have sizeable number of transactions)
4. De-select Balance Transactions, reset and sync data.
5. It works fine now. Which is weird :)

## Severity of the bug for you
High 

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
Source (Stripe) - 0.1.12
Destination (Postgres) - 0.3.6

## Additional context
Everything is running locally on MacOS

**Comment by sherifnada** [comment]
@akshayi1 could you share the logs from your "failing" syncs?

**Comment by sherifnada** [comment]
@akshayi1 any updates from your end?

**Comment by bazarnov** [comment]
This issue and many more schema-related issues with source-stripe were fixed in 0.1.14. Please make sure the connector is updated to that version. If already updated - this is the answer why it's working)
