### ISSUE TITLE
Platform should validate an entered cron expression to align frontend and backend error handling

### ISSUE THREAD

**Issue by hongbo-miao** [airbytehq/airbyte#40715]
### Topic

airbyte-webapp

### Relevant information

Currently `0 0 15 * * 1` shows valid in the UI, but it is not.
The good thing is when you click "save changes", it shows invalid.

The correct one is `0 0 15 ? * 1`.

It will be great to let the UI shows invalid for  `0 0 15 * * 1` as well. 😃

![image](https://github.com/airbytehq/airbyte/assets/3375461/fac70876-5071-4d3c-be0c-25be92f1adb7)

https://www.javainuse.com/cron is good resource to validate whether it is actually valid.

You can see `0 0 15 * * 1` is invalid:
![image](https://github.com/airbytehq/airbyte/assets/3375461/8a78120f-494c-4e03-9ff3-eb9370268746)

You can see `0 0 15 ? * 1` is invalid:

![image](https://github.com/airbytehq/airbyte/assets/3375461/e11c9827-7814-4a9c-b83a-40d9a66191d7)

**Comment by nataliekwong** [comment]
The frontend sees this as valid but the backend does not. One solution would be to create a backend endpoint that validates the cron, and only show the preview if the validation passes.

**Comment by josephkmh** [comment]
This has been fixed on Airbyte Cloud and will go out in the next OSS release.
