### ISSUE TITLE
Unable to import Airbyte configuration due 413 Request Entity Too Large error

### ISSUE THREAD

**Issue by akoshterek** [airbytehq/airbyte#4086]
## Expected Behavior
File should be imported

## Current Behavior
I have an Airbyte instance that was running for a while. I'd like to move it's configuration to another instance.
Both are 0.24.8-alpha
Export configuration works fine and produced a file slightly bigger than 1Mb.
Import fails with message
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
```

I've unpacked the archive and found that ATTEMPTS.yaml and JOBS.yaml files are very big.
Exporting all jobs and attempts seems to be useless, or at least there should be an option to export a smaller file with the latest checkpoints only.

## Severity of the bug for you
Medium
was able to recreate config from scratch

## Airbyte Version
0.24.8-alpha

**Comment by jrhizor** [comment]
Marking as high since it seems likely that this will be an increasingly large problem over time, and something blocking upgrades is pretty important.

We'll have to bump https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size it looks like?

**Comment by akoshterek** [comment]
Increasing max request size would mitigate the problem but not solve it entirely.

I can imagine an instance with frequent syncs (append or CDC), in such case configuration archive would grow pretty fast.

Long term solution would discard too old runs IMHO. Why would I need them? Configuration and latest checkpoints should be enough in the most cases. Possibly you'd like to have different kinds of export.

**Comment by jrhizor** [comment]
Good point @akoshterek. I think we probably need both, since it's possible that user configs could hit the max without including any job attempts. Created https://github.com/airbytehq/airbyte/issues/4111 to track discarding old runs.

**Comment by marcosmarxm** [comment]
Close this after #4126 and #4111 will deal with the problem of large-files export.

**Comment by akoshterek** [comment]
worth releasing a new version perhaps?

**Comment by cgardens** [comment]
agreed. we should release a patch for this today. @marcosmarxm would you be willing to do that?

**Comment by asamiller** [comment]
I'm getting this error trying to upgrade to `0.26.0-alpha`. Is there a patch coming?

**Comment by marcosmarxm** [comment]
@asamiller `0.26.0-alpha` has the solution implemented. I'll take a look on that.

**Comment by asamiller** [comment]
I was running 0.22 and exported the config. The `airbyte_archive.tar.gz` file is 13.2mb if that helps.

**Comment by marcosmarxm** [comment]
I was able to upgrade from `0.24.2-alpha` to `0.26.0-alpha`. @asamiller is possible to confirm your migration process or share more information?

**Comment by asamiller** [comment]
@marcosmarxm I followed the instruction in the [upgrade guide](https://docs.airbyte.io/upgrading-airbyte). Here's the steps I took:

1. `docker-compose down` then `docker-compose up -d db server webapp` on my EC2 box.
2. Export the configuration file. Got a gzip file that is 13.1mb.
3. Migrated the config:
  ```
  docker run --rm -v /Users/asa/Downloads/airbyte-migrate:/config airbyte/migration:0.26.0-alpha --\
    --input /config/airbyte_archive.tar.gz\
    --output /config/airbyte_archive_migrated.tar.gz
  ```
4. Updated the `docker-compose.yml` to the current version from the repo. Then `docker-compose up -d`
5. Skipped config, went to admin, clicked import, selected the `airbyte_archive_migrated.tar.gz` file. Then the page reloads but the configuration isn't applied. Looking in the network activity dev tool, I see `api/v1/deployment/import` fails with the 413 status.

When I unzip the exported config, `airbyte_db/JOBS.yaml` and `airbyte_db/ATTEMPTS.yaml` are both almost 150MB. I tried replacing them with empty files, zipping it and uploading. The import is successful, but the config doesn't apply.

**Comment by jonasgribas** [comment]
Hi dears,

Share with you if it is of importance to someone, because I have the same problem reported.
After changing Nginx to Haproxy, we immediately solved the problem. Without performing additional configuration in Haproxy...


I didn't go in depth to check why Nginx has this problem, but it was the fastest way to solve my problem, as I had a problem with Nginx in production before.

**Comment by jonasgribas** [comment]
Hi dears,

Share with you if it is of importance to someone, because I have the same problem reported.
After changing Nginx to Haproxy, we immediately solved the problem. Without performing additional configuration in Haproxy...


I didn't go in depth to check why Nginx has this problem, but it was the fastest way to solve my problem, as I had a problem with Nginx in production before.
