### ISSUE TITLE
after onboarding, evaluate experience setting up first connection with a thumbs up/thumbs down

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4087]
We can add a panel after the first connection setup to ask if a user had a good experience or not. If they didn't we can have a form that asks for feedback. This would encourage users to communicate difficulties they had in setup that were not specifically sync success/failure-related.

We need more avenues for evaluating the easiness of the original flow, especially as we iterate on it.

**Comment by cgardens** [comment]
This is a cool idea. @johnlafleur @avaidyanatha wdyt?

**Comment by avaidyanatha** [comment]
We should make sure that it doesn't slow users down. If someone routinely cleans out their volumes and starts fresh all the time in testing/dev environments, this may feel noisy. One of the reasons people really like using Airbyte is the velocity, and anything that gets in the way of that will hurt us.

That said, I really like the idea and want more data around this. Maybe a pop-up that has a timer to disappear if not clicked on? Definitely worth discussing further.

**Comment by johnlafleur** [comment]
I think we can make it as not too noisy and feel natural on the user flow. Will definitely work on a UI for it.
It will also help @nataliekwong on knowing which sessions to watch for on FullStory (or equivalent) to see if we can have more insights from the feedback).

**Comment by johnlafleur** [comment]
Design suggestion: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25903%3A50

**Comment by cgardens** [comment]
Cool. Where should this feedback go? segment?

**Comment by johnlafleur** [comment]
I would think so, so we can push it to BQ. Wdyt @nataliekwong ?

**Comment by nataliekwong** [comment]
Yep, it should pass through Segment so we can use Amplitude/BQ to report.

**Comment by nataliekwong** [comment]
I've added details about the additional Segment track call here, in rows 76 - 82 in "Feedback Survey": https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

**Comment by johnlafleur** [comment]
Following a discussion with @jrhizor , I actually think we got it wrong here. 
We shouldn't be asking for feedback after the connection setup, but after the first sync was successful. 
It would let them know about the sync and ask them if the data fits with their expectations. At that point, asking for feedback is a great way to assess if we're actually doing the job right and if the onboarding experience is simple enough. 

Here's the suggestion for the new design: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25296%3A0
The popup would be displayed as soon as the first sync is completed. And if you're not logged in, then at the next connection.

**Comment by timroes** [comment]
This feedback mechanism exists today, so closing this.
