### ISSUE TITLE
communicate to the user in the UI about what tables to expect

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4088]
If a first-time user syncs data from a source into a warehouse destination, the first thing they'll do is check the destination for the tables they created. If they use a SQL client or the BigQuery UI (for example) they'll likely see an ocean of `_airbyte_raw` tables that are first alphabetically before their actual tables. 

This is especially confusing if they specified a prefix.

I'm a bit torn on how to actually communicate this information. Maybe this can be where we configure normalization.

**Comment by jrhizor** [comment]
This is especially confusing if someone thinks they know what "Basic Normalization" means and then they come in with an expectation of the data format and are disappointed.

**Comment by marcosmarxm** [comment]
@jrhizor maybe improve docs or create a doc (What happens during a sync) to show a more detailed process?

**Comment by jrhizor** [comment]
We need this to be easy to understand **outside of the docs**. Users don't always proactively visit the docs and it's highly unlikely that they will read through them in detail if they're just trying us out for the first time. If it appears like we aren't working, they may just drop off using us entirely instead of attempting to debug what is actually expected behavior.

**Comment by cgardens** [comment]
@jrhizor 100% agree. Do the changes mentioned in this issue (https://github.com/airbytehq/airbyte/issues/3499) (that artem is working on this week) address your concerns? Unfortunately, it's not going to be perfect, there are still going to be some naming discrepancies, but I think it will get users much closer than we are now.

Also I think this is a great call out and a good thing for us to keep in mind in general when we think about usability. Specifically when putting stuff in the docs is enough versus when we need to give up real estate in the UI to explain stuff. 
> We need this to be easy to understand outside of the docs. Users don't always proactively visit the docs and it's highly unlikely that they will read through them in detail if they're just trying us out for the first time.

**Comment by jrhizor** [comment]
Oh I didn't see the latest Figma mockup. That addresses some of the concerns and feels like a huge step forward.

To close this issue, there are two major elements missing:

1) It must be clear that `_airbyte_raw` tables are created since that can make first time-users think Airbyte isn't working. If  a user trying us out enables normalization and then get confused by additional tables (or maybe not even make it to seeing the normalized tables since _ is first alphabetically) they might just stop using us altogether at that point.

2) As long as there are naming discrepancies this won't be sufficient. The point is to have a source of truth. Ultimately that source of truth should be API-accessible as well. From a user perspective having precise data destinations isn't a particularly high bar.

**Comment by cgardens** [comment]
I agree with what @jrhizor is saying here. I want to take this initial step here as I think I think it'll get things to be a lot clearer _and_ the technical path to getting here is pretty clear. It'll be a first step. The technical path to getting to perfect alignment of names is a bit more nebulous.

**Comment by edmundito** [comment]
Discussed with @andyjih. This is a valid issue, but closing it because there hasn't been any community engagement. Will revisit it when the time comes in the future.
