### ISSUE TITLE
hide the concept of normalization from users in the UI by default

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4089]
In a demo with a first time user, they visited the link to basic normalization from the configuration, skimmed the page, got a very rough idea of what it was doing and ended up selecting it. When asked afterwards if they understood what it was doing, they said "no" emphatically.

It would make more sense as a setting at the connection level, perhaps hidden under an `Advanced` settings section. It should be on by default for most supported cases.

**Comment by sherifnada** [comment]
related #3681

**Comment by edmundito** [comment]
Closing as not planned.
