### ISSUE TITLE
allow the "new connection" flow to add an existing destination

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4093]
If a user adds a connection in onboarding then goes directly to the connections page and adds a new connection, they don't see their existing destination as an option. It looks like you have to configure destinations per-sync. 

In many ways it's _more_ intuitive to create a connection from the connection page instead of source/destination pages, so this is likely something that could happen frequently for new users.

**Comment by cgardens** [comment]
@jrhizor I agree. I encountered this the other day as well. Is the UI change obvious or should we get a design for it?

**Comment by jrhizor** [comment]
I think the only UI change is just what page you end up on after completing onboarding, so I don't think it needs a mockup? I assume there's some sort of redirect at the end.

**Comment by tuliren** [comment]
Can we also allow reuse existing sources in the "new connection" flow?
