### ISSUE TITLE
make it easier to run webapp without an api running

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4098]
From looking at:
- https://stackoverflow.com/questions/32845674/setup-nginx-not-to-crash-if-host-in-upstream-is-not-found
- https://serverfault.com/questions/876308/kubernetes-dns-resolver-in-nginx

It looks like providing a DNS server would need to be provided via an environment variable that matches either Docker's internal DNS server or Kuberentes's internal DNS server. This allows it to retry until it resolves it instead of just failing when the service isn't able to be resolved. 

Marking this as low, but Artem may want to bump this if this is a problem for his iteration cycle.

**Comment by cgardens** [comment]
@jrhizor I'm not super clear on what problem this is trying to solve. Mostly not sure how much work can be done on the UI without the API. Is there a known use case here? Would it be cool if I removed the "good first issue" label. It's not super obvious

**Comment by jrhizor** [comment]
We're preserving the functionality to plug in another API into the frontend via env variable for example. If we're running the server separately for some reason you can't just run the webapp container by itself right now.

I thought this would be potentially disruptive to @Jamakase . If it isn't a problem for him we can just close this.
