### ISSUE TITLE
Beta release placeholder

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4103]
We have a milestone for this: https://github.com/airbytehq/airbyte/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Airbyte+Beta+Release%22

I'm creating this issue as a placeholder so we can discuss what we want to do for the beta.

**Comment by jrhizor** [comment]
These are the themes I see for tickets that move us towards beta:
1. Confidence in protocol stability (in terms of backwards-compatibility)
   * Have versioned specs with the potential for creating a compatibility matrix for core/connectors
   * Be prepared for supporting sharding
   * Be prepared for streaming sources
2. Easy to operate
   * Easy upgrades https://github.com/airbytehq/airbyte/issues/2598
   * Prevent version incompatibilities by upgrading connectors in migrations
   * The UI should be able to support 1000s of tables / large catalogs at a reasonable speed
   * Sane defaults should exist for sync modes / cursor fields
      * For our core API connectors (Stripe, for example), a user should be able to go through a sync without considering any options outside of naming / credentials and end up with a sane output without thinking about normalization/namespaces/sync modes/etc.
      * We should reduce the cognitive load for new users.
3. Predictable behavior
   * Users should understand exactly what tables will be created as a result of their sync
      * This should be explicit in the UI and not require knowledge of namespaces/normalization internals/etc to figure out. 
      * If a user is at the end of the sync process and is wondering where data will end up, we've failed.
      * Related: https://github.com/airbytehq/airbyte/issues/3499 + https://github.com/airbytehq/airbyte/issues/3852
   * Data types should propagate https://github.com/airbytehq/airbyte/issues/1006

**Comment by erichartono** [comment]
@jrhizor If I may add another item to beta list, it would be great to support sync frequency at specified hours explicitly from UI. E.g. Daily sync at 4 AM. 
https://github.com/airbytehq/airbyte/issues/2170 is a step closer to this outcome. 🙏

**Comment by cgardens** [comment]
goals met but release label strategy changed. closing.
