### ISSUE TITLE
MySQL CDC Decimal handling

### ISSUE THREAD

**Issue by rlin264** [airbytehq/airbyte#4105]
## Expected Behavior
MySQL Decimal values should be converted to a numeric value in the raw data and then converted to a float in the normalization step.

## Current Behavior
I currently have a MySQL table (connected to BigQuery) with column of type decimal(10,4) where this decimal value is converted to a string. For example, the value 0.188 is awlays mapped to the string "B1g=" and 0.311 is mapped to "DCY=".
The subsequent normalization step then fails since the genreated SQL attempts to cast the string to a float.

## Logs

[logs-37-0.txt](https://github.com/airbytehq/airbyte/files/6650122/logs-37-0.txt)

## Steps to Reproduce
1. Create and fill a MySQL table with decimal columns
2. Set up Airbyte MySQL source conenctor with CDC
3. Set up connection to BigQuery
4. Run sync

## Severity of the bug for you
High

## Airbyte Version
0.24.7-alpha

## Connector Version (if applicable)
0.3.7

**Comment by tylerdelange** [comment]
We are having the same issue with our Snowflake destination.

**Comment by alderson59** [comment]
Having this issue with a mariadb:10.4 source when pulling a large table into postgres. (Using CDC and incremental sync)

Issue only occurs with incremental. No problem with full refresh.

Getting errors like:
`invalid input syntax for type double precision: "Amp/8A=="`
`invalid input syntax for type double precision: "AjpvQA=="`

**Comment by tylerdelange** [comment]
Article for fixing the decimal conversion in
