### ISSUE TITLE
Cut a new base image version on Python 3.10

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#41061]
We want to upgrade our connector image to Python 3.10.
We should cut a new base image version based on top of Python 3.10.
Once released the `up-to-date` workflow will automatically make connectors use the latest version.

**Comment by natikgadzhi** [comment]
The idea here is to first patch vulnerabilities in 3.9 (that is merged) in bae image 1.2.3, and then go to 3.10. Will take about a week overall to move over.
