### ISSUE TITLE
Make a `/version-bump` slash command that bumps versions of changed connectors in a PR

### ISSUE THREAD

**Issue by natikgadzhi** [airbytehq/airbyte#41071]
## Problem

When Dependabot makes a PR into a Python source, it changes only `pyproject.toml` and `poetry.lock`. 

To merge such a PR, we need a few things:
- Make it run CI and make sure it passes. #airbyte-internal-issues/6979
- Bump the version (this issue)

I think we have a version bump command in `airbyte-ci`, so let's do two things: 
1. Provide a new slash command `/version-bump` that bumps the version of affected connectors
2. Make sure that this flow is triggered automatically for PRs from dependabot (separate issue).

## Acceptance criteria

- `/version-bump connector-name [--version patch | minor | major] [--message ...] ` slash command  that: 
  - determines the list of changed connectors
  - posts a comment to the issue that tracks it's execution (like `/format-fix`)
  - bumps the version of a connector in `pyproject.toml`
  - bumps the version of a connectors in `metadata.yaml` (key `dockerImageTag`)
  - adds a changelog line to docs (`docs/integrations/{connector-name}.md` if it exists, but does not fail if it does not exist.

## Impact

Once we have this, @ChristoGrab's work and @btkcodedev and @pabloescoder's work will be MUCH easier. And @marcosmarxm will be very happy — we will eliminate the next biggest time hog in accepting community contributions.

**Comment by marcosmarxm** [comment]
> bumps the version of a connector in pyproject.toml
 it is possible to also run `poetry lock`?

**Comment by natikgadzhi** [comment]
@marcosmarxm yep: https://github.com/airbytehq/airbyte/issues/41070

**Comment by natikgadzhi** [comment]
DONE! We now have `/bump-version` command. https://github.com/airbytehq/airbyte/pulls/46252
