### ISSUE TITLE
Replace Postgres Instruction video 

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#4119]
### Tell us about the documentation you'd like us to add or update.
The onboarding flow has a link to a Postgres tutorial (https://www.youtube.com/watch?v=Rcpt5SVsMpk) at the bottom of each page in the flow. Since it has been some time since it was created, it could be replaced by fresher content that is also shorter in length. 

![Screen Shot 2021-06-11 at 5 49 45 PM](https://user-images.githubusercontent.com/38087517/121980957-df2dbf00-cd5a-11eb-975d-62cf4c23a31b.png)

**Comment by misteryeo** [comment]
Closing this since it's old.
