### ISSUE TITLE
Add secrets fields to Custom DBT transformation configuration

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4133]
## Tell us about the problem you're trying to solve
Following up on #2959, when configuring a dbt transformation to clone a git repository.
There should be secrets fields to use in the case of a private repository. The secret fields should be masked and hidden when editing the configurations.

**Comment by cgardens** [comment]
no longer relevant.

**Comment by aliavni** [comment]
@cgardens I found this issue while trying to use a private repository for dbt transformations. Is there a solution for this?

**Comment by cgardens** [comment]
Unfortunately there is not. We are going to drop support for this feature and instead recommend that folks use another orchestration tool like dagster or airflow ([docs](https://docs.airbyte.com/operator-guides/using-dagster-integration) on how to integrate it with airbyte)

**Comment by aliavni** [comment]
@cgardens I am late to this party, but what is the reason this feature is being dropped? If it is the private repo issue, I think it can be fixed by providing debt project files directly rather than trying to pull from GitHub directly.

I think dbt transformations is such a great feature and I would be sad to see it dropped.

**Comment by cgardens** [comment]
This issue actually perfectly encapsulates why we are dropping it. At this time, our goal really is not to be an orchestration tool, but by having this feature people start to expect that we are. In addition, it requires us to spend a lot of time figuring out a support matrix for dbt (which version of dbt do we support? how do we do private repos? dbt community edition or dbt cloud?). This feature has made us accidentally tip toe into a whole area that's not our core competency, and so it leads a disappoint experience for our users. We think you can get a better experience by using us with a free oss orchestration tool.

**Comment by aliavni** [comment]
I understand the decision. Thanks @cgardens

**Comment by prathamagrawal28** [comment]
Hi there, I want to create a dbt transformation in airbyte, but my repository is private so is it possible to use that repo?
