### ISSUE TITLE
S3 Destination Connector - Support JSON format

### ISSUE THREAD

**Issue by panhavad** [airbytehq/airbyte#4153]
## Tell us about the problem you're trying to solve
Currently, the S3 Destination supports only CSV and Parquet format. It would be great to output direct as a JSON format.

## Describe the solution you’d like
Users will be able to destinate using S3 Destination Connector that supports JSON output as a JSON file.

## Are you willing to submit a PR?
Yes, I would like to contribute to this feature. If the team could put it in the roadmap.

**Comment by panhavad** [comment]
Will you accept the contribution for this, I will start working on this as soon as you guys okay with it. @marcosmarxm

**Comment by davinchia** [comment]
I will defer to @tuliren who has more context on this

**Comment by tuliren** [comment]
Hi @panhavad, yes, we are going to support [JSONL](https://jsonlines.org/) output on S3 destination very soon, probably this week.

**Comment by panhavad** [comment]
That's nice so you working on this right? No need to contribute from me haha. Anything for me to keep track progress of the update on this JSON support (issue link)?

**Comment by tuliren** [comment]
> Anything for me to keep track progress of the update on this JSON support (issue link)?

Well, this is the issue for this topic. I will update this issue when the PR is out.

**Comment by tuliren** [comment]
@panhavad JSONL support has been merged.
