### ISSUE TITLE
Add to ConnectorSpecification a Features map to declare what they support

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4157]
## Tell us about the problem you're trying to solve
We've been adding `supportsXXX` flags in the `ConnectorSpecification` object of the Airbyte protocol: https://github.com/airbytehq/airbyte/blob/e468c2c2a76ebcac0647fab57d533f594fe2ef0a/airbyte-protocol/models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L235

## Describe the solution you’d like
We can refactor these into a single map of supported features where the key would be the feature name it supports and the value would be the boolean.

It would make it easier to add feature flags without having to modify the protocol?

## Describe the alternative you’ve considered or used
Individual `supportsXXX` flags

## Additional context
https://github.com/airbytehq/airbyte/pull/4031#pullrequestreview-681077420

**Comment by cgardens** [comment]
Agreed. I like this idea.

**Comment by cgardens** [comment]
closed as no longer relevant. we now add information like this to the actor definition.
