### ISSUE TITLE
[source-google-drive] "value-not-found" Google Drive OAuth Override - Bad Request

### ISSUE THREAD

**Issue by vansh-ar0ra** [airbytehq/airbyte#41660]
### Connector Name

source-google-drive

### Connector Version

0.0.12

### What step the error happened?

Configuring a new connector

### Relevant information

While using Google Drive Source connector programmatically, with OAuth using my own google client Id and credentials, when I try to create the connector, I get the following error.

I have all the fields using the Airbyte API refernce. However, this gets fixed when I remove the sourceType from the request, and instead add definitionId in the request by fetching it from the metadata of the connector in airbyte github repo.
This helps me create the source, howevever, while creating the connection with the source created using this method, I am getting the 500 Internal server Error, and while checking the source on the Web app, I realised it was because of not performing OAuth Override for the source.

Now, the main issue is while performing the OAuth override for Google-drive.
I am getting the same value not found error, received while I was trying to create the source adding the sourceType in the request.
However, trying to add the definitionId in the request, instead of name for the OAuth override request doesn't work.
I don't know why the API is giving an error while I am trying to create source or perform OAuth override for the google-drive connector.
The same is working perfectly for the google sheets connector. The difference in both connectors is that GDrive is in marketplace while Google Sheets, inherently is supported by Airbyte.
How can I perform OAuth override for Google Drive given the error I am encountering? I have a strong need to use my own google client credentials.
Any help in this regard would be greatly appreciated.
Thanks!

### Relevant log output

```shell
{
    "status": 400,
    "type": "https://reference.airbyte.com/reference/errors",
    "title": "value-not-found",
    "detail": "The submitted value could not be found.",
    "documentationUrl": null,
    "data": {
        "value": "google-drive"
    }
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by LemonFace0309** [comment]
Also running into this error

**Comment by mous222** [comment]
Running into the same error, any news/updates ?

**Comment by MaiAditya** [comment]
Any updates on this error, I am also getting the same error.

**Comment by pmossman** [comment]
There was indeed a missing name mapping for this connector. I added a mapping from the google-drive source name to its underlying definitionId in [this commit](https://github.com/airbytehq/airbyte-platform/commit/fa846c181623ff1f73742e0f1483f51eaa4f600a)

I also just kicked off a release of version 0.64.2 which will contain the fix, should be available shortly! Please re-open if you're still running into a similar issue after trying this out on 0.64.2
