### ISSUE TITLE
Allow running docker-compose up with VERSION=dev to use dev-tagged integrations

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#417]
This will make it easier to iterate locally, because it will guarantee that local images are the right version. The current workflow is to tag integrations with the version locally or change the version to dev in Integrations.java.

**Comment by cgardens** [comment]
@jrhizor given the admin UI, do you feel this is still worth doing?

**Comment by jrhizor** [comment]
Nope.
