### ISSUE TITLE
Use variables params in source/destination settings

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4179]
## Tell us about the problem you're trying to solve

For the HTTP connector I want to use variables params (today, yesterday, from 7 days ago) in the body call, for example:
- {"date": $today}

The request came from [slack convo](https://airbytehq.slack.com/archives/C01VDDEGL7M/p1623841376039500).

## Describe the solution you’d like
Some common variables to use like:
- today
- yesterday
- 7 past days
- X past days

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Your answer

**Comment by malikdiarra** [comment]
duplicate of #4252
