### ISSUE TITLE
Destination MSSQL: `The server supports a maximum of 2100 parameters`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4181]
## Expected Behavior
Works

## Current Behavior

From [slack convo
](https://airbytehq.slack.com/archives/C01MFR03D5W/p1623738527015200)Hello AirByte folks :smile: its my first attempt so i would like to first congratulate everyone for the amazing work you guys are doing!
I came here in search for the knowledge of the masters , my first attempt i am trying something quite simple, i wanted to move data from Zendesk -> MSSQL both certified connectors, but it turns out i am failing in the process , it continues to present me the following error:
```
ERROR (/tmp/workspace/13/0) LineGobbler(voidCall):85 - Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
the data was fetched from the API, the tables were created in the database, but no data is sent.
Its probably something silly , but i am a little clueless at the moment , so any help is most appreciated
```

Other user had problem using Postgres with MSSQL

## Logs
[logs-14-0.txt](https://github.com/airbytehq/airbyte/files/6671970/logs-14-0.txt)

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / **High** / Critical

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
airbyte/destination-mssql:0.1.3 

## Additional context
*Environment, version, integration...*

**Comment by marcosmarxm** [comment]
some additional info: https://github.com/knex/knex/issues/2986

**Comment by mystmaker33** [comment]
I am having the same issue trying to replicate a table from a MS SQL Server database to a different MS SQL Server database on the same server. I have found that the max number of rows I can have in the source table is 700. At 701 rows the job fails:
![Airbyte MSSQL Error](https://user-images.githubusercontent.com/17733077/126563835-3b37e567-3d96-4af9-a83f-aac2ce09c4fa.png)

**Comment by marcosmarxm** [comment]
[slack convo with more info](https://airbytehq.slack.com/archives/C01MFR03D5W/p1626798438065500) thanks a lot @mystmaker33

**Comment by joshualee-ifesworld** [comment]
bumping into this issue as well, is there a configuration in the airbyte that allows us to limit the amount of rows inserted per batch?

**Comment by isstaff** [comment]
I'm also running into this issue when syncing data from Salesforce to MSSQL.
I'm running v. 0.29.2 of Airbyte

**Comment by marcosmarxm** [comment]
@joshualee-ifesworld and @isstaff is possible to upgrade to latest version of MSSQL connector?

**Comment by joshualee-ifesworld** [comment]
yes i've upgraded it is working perfectly! thanks again!
