### ISSUE TITLE
Make S3 output filename configurable

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4184]
## Tell us about the problem you're trying to solve
The current S3 output filename is `<date>_<timestampe-millis>_<part-number>.<extension>`. It can be helpful to include the sync ID in the filename. Even better, we can make the filename configurable.

## Describe the solution you’d like
Add a new parameter to let users configure the filenames by combining preset components in any arbitrary way (similar to setting up the bash prompt).

For example:
```
{date}_{timestamp}_{sync_id}_{part_number}.{format_extension}
```

Possible components to support:

- `{date}`: default to `yyyy_MM_dd`; can specify the format like `{date:yyyy_MM}`.
-  `{timestamp}`: default to millis; can specify the unit like: `{timestamp:millis}`, `{timestamp:micro}`
- `{sync_id}`
- `{format_extension}`
- `{part_number}`

Classes to start adding from:
1. Update config file S3DestinationConfig(). But check how this will affect other connectors that use S3 under the hood. May affect backward compatibility. 
2. Start check how to process from BaseS3Writer -> getOutputFilename(...)
Also check "S3 Path Format" approach for an example

Some components may be required, like `{part_number}`.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?
N/A

**Comment by alexandertsukanov** [comment]
@tuliren Just a couple of questions:

1. Are we OK with `{ }` placeholders? Or we should better to consider `${ }` ?
2. Should the UI have some validation on client side? In case, user will try to input some placeholder we don't support? e.g. `{region}`
