### ISSUE TITLE
abctl local install failing with limited diagostics as to what has failed or why

### ISSUE THREAD

**Issue by jonseymour** [airbytehq/airbyte#41938]
### What happened?

abctl failing to install with little info about what is going wrong.

```
[airbyte@ip-10-11-65-26 ~]$ abctl local install -v
  INFO    Using Kubernetes provider:
            Provider: kind
            Kubeconfig: /opt/airbyte/.airbyte/abctl/abctl.kubeconfig
            Context: kind-airbyte-abctl
 SUCCESS  Found Docker installation: version 25.0.3
 SUCCESS  Port 8000 appears to be available
  INFO    No existing cluster found, cluster 'airbyte-abctl' will be created
  DEBUG   Creating data directory '/opt/airbyte/.airbyte/abctl/data'
  ERROR   Cluster 'airbyte-abctl' could not be created
  ERROR   unable to create kind cluster: failed to init node with kubeadm: command "docker exec --privileged airbyte-abctl-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
```

### What did you expect to happen?

ab would be installed and start running

### Abctl Version

<details>

```console
$ abctl version
version: v0.7.1
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.20.12
 Git commit:        4debf41
 Built:             Wed Feb 28 00:29:45 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.20.12
  Git commit:       f417435
  Built:            Wed Feb 28 00:30:22 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.11
  GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba
 runc:
  Version:          1.1.11
  GitCommit:        4bccb38cc9cf198d52bebf2b3a90cd14e7af8c06
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
AME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

</details>

**Comment by jonseymour** [comment]
Part of the issue here is that undoubtedly the issue has something to do wth kind but because abctl abstracts away kind from the end user, I am left with no idea at all about how to progress the diagnosis.

It doesn't help that I am completely new to both airbyte and kind and only have rudimentary knowledge of kubernetes. 

I really don't have the a clue about where to start. I added -v to the arguments but that didn't provide any useful level of diagnostics.

What am I meant to do here?

**Comment by jonseymour** [comment]
I am going to close this since when I nuked the EBS volume and EC2 volume and retried it all just worked, so I really have no idea what went wrong the first time. 

I may raise a separate issue about the lack of guidance in the documentation about how to apply other non-default configuration to an abctl instance. It is obvous how to do this with docker compose - edit the .env file and restart - but isn't clear how to do post local install configuration to an abctl instance.

**Comment by jonseymour** [comment]
I think I may have reproduced the issues on a separate system on the second attempt to install via abctl having first removed the original installation with abctl local uninstall.

**Comment by jonseymour** [comment]
I've created a 2nd issue #41992 with a more concrete test case for reproducing the failure reported here.

**Comment by sergio-toro** [comment]
I'm having the same error, somehow when I run abctl local uninstall left me in a state I can't longer install it due to the `airbyte-abctl-control-plane` not being pulled or started

**Comment by Vishnuram-cloudside** [comment]
> ### What happened?
> abctl failing to install with little info about what is going wrong.
> 
> ```
> [airbyte@ip-10-11-65-26 ~]$ abctl local install -v
>   INFO    Using Kubernetes provider:
>             Provider: kind
>             Kubeconfig: /opt/airbyte/.airbyte/abctl/abctl.kubeconfig
>             Context: kind-airbyte-abctl
>  SUCCESS  Found Docker installation: version 25.0.3
>  SUCCESS  Port 8000 appears to be available
>   INFO    No existing cluster found, cluster 'airbyte-abctl' will be created
>   DEBUG   Creating data directory '/opt/airbyte/.airbyte/abctl/data'
>   ERROR   Cluster 'airbyte-abctl' could not be created
>   ERROR   unable to create kind cluster: failed to init node with kubeadm: command "docker exec --privileged airbyte-abctl-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
> ```
> 
> ### What did you expect to happen?
> ab would be installed and start running
> 
> ### Abctl Version
> ### Docker Version
> ### OS Version

use sudo abctl local install
