### ISSUE TITLE
Implement Kube Logging for other Cloud Providers.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4200]
## Tell us about the problem you're trying to solve
Today we only support S3. Implement this for the other cloud providers.

## Describe the solution you’d like
- [x] GCS logging
- [ ] Azure logging (https://github.com/airbytehq/airbyte-internal-issues/issues/169)
- [x] Minio logging

**Comment by mhensley-cls** [comment]
FYI - Some orgs utilizing on prem kubernetes might leverage something like https://min.io/ - an S3 API compliant storage alternative.

**Comment by jrhizor** [comment]
@mhensley-cls we're actually planning on supporting minio as the default testing option so users won't need to configure s3/gcs when testing.

**Comment by mhensley-cls** [comment]
Ahh, cool. Found it - https://github.com/airbytehq/airbyte/issues/4206
