### ISSUE TITLE
upgrade postgres library version

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#42002]
https://airbyte.metabaseapp.com/question/9733-connectors-current-critical-vulnerabilties

`airbyte-destination-postgres` and `airbyte-destination-postgres-strict-encrypt` needs postgresql>=42.6.1

Steps:
* Upgrade library version in the connector's gradle file
* Test and validate and test with a new dev image
* merge

**Comment by evantahler** [comment]
Replacing this issue with https://github.com/airbytehq/airbyte-internal-issues/issues/8881
