### ISSUE TITLE
[source-MSSQL] Full refresh Overwrite does not work in some cases

### ISSUE THREAD

**Issue by coespain** [airbytehq/airbyte#42041]
### Connector Name

source-mssql

### Connector Version

4.0.35

### What step the error happened?

During the sync

### Relevant information

I am doing a sync from an SQL Server to postgres DB.

When upgrading to the latest versions of the airbyte/source-mssql source we have detected that for connections configured with the “Scan Changes with User Defined Cursor” update method for some tables with Sync mode: Full refresh Overwrite, it does not work correctly. It only happens for some tables, we have not been able to determine what is different, apparently these tables are the same as the others. The first execution does it correctly, but from the second synchronization it doesn't read records and empties the destination table

<img width="848" alt="airbyte_sync" src="https://github.com/user-attachments/assets/f3162094-c5bb-45fd-b6d0-0c5d005b0a53">

### Contribute

- [ ] Yes, I want to contribute

**Comment by akashkulk** [comment]
I think this is related to this issue : https://github.com/airbytehq/oncall/issues/5935. @benmoriceau to confirm.

**Comment by akashkulk** [comment]
@coespain is the issue occurring between syncs or attempts within the sync?

**Comment by benmoriceau** [comment]
I am not sure that it is related. Would it be possible to have the platform version running this?

**Comment by mahadeveaswar** [comment]
We are also facing similar issue with sync between MSSQL and Redshift. Running Airbyte **v0.52.0**

**Comment by pholterman** [comment]
@benmoriceau We are also facing this issue with sync between MySQL and Snowflake. 
Airbyte version: 0.50.35
Source: MySQL v3.6.5
Destination: Snowflake v3.10.1

However, it is not that the second time it always has 0 results, sometimes it processes new rows,  as if it is an incremental load.
![image](https://github.com/user-attachments/assets/be152972-9194-4d50-8cc0-25d7831c2bfe)

**Comment by firewall413** [comment]
same issue here! 
Airbyte: 0.57.3
Microsoft SQL Server 4.1.8
Destination: S3

**Comment by cbuckle1** [comment]
Airbyte version: 0.50.47
Source: MSSQL v4.1.11
Destination: Snowflake v3.10.1

Seeing the same issue

**Comment by Razifmalik** [comment]
Seeing same issue

Airbyte version: 0.54.152
source: bing ads 2.7.3
destination: Snowflake 3.4.0

First time it does a full refresh and second time just does an incremantal load even though the sync method used is full refresh overwrite

**Comment by theyueli** [comment]
we just discussed this issue, for RFR to work correctly, we requre airbyte be 0.58.0 or above. Please upgrade airbyte and let us know if you still see this issue.

Closing the ticket and please reopen if issue remains.
