### ISSUE TITLE
Ongoing: support for DB sources running CATs

### ISSUE THREAD

**Issue by clnoll** [airbytehq/airbyte#42084]
Currently:
- Finding a way to remove the artifacts exported from the setup container to the host machine.
- Added config information about the connector type so we can give CDC sources separate behavior (not ideal, trying to find a way to make it more abstract).
- Fixed bug where we couldn't copy files from container to host (https://github.com/airbytehq/airbyte/pull/42426).
- Added a final teardown option to be run after all tests (https://github.com/airbytehq/airbyte/pull/42517).

**Comment by natikgadzhi** [comment]
A few pings this week, seemingly fixed tests not running in airbyte-ci as opposed to local pytest

**Comment by natikgadzhi** [comment]
Thank you for keeping track of issues and closing this off!
