### ISSUE TITLE
Connector extracting the data for the first property ID

### ISSUE THREAD

**Issue by ali-al-najjar** [airbytehq/airbyte#42110]
### Connector Name

destination-bigquery

### Connector Version

2.4.12

### What step the error happened?

During the sync

### Relevant information

I added multiple property ids as an array in the property ids field. The connector extracts just the first one.
So for example these two ids, 1738294 and 5729978930 it will get the data for 1738294.
If I switch between them it will get data for the 5729978930 and not the other. I believe there is an issue with the for loop for the property ids.
Last point that this is not something new, I checked all the versions of the source and tested them and nothing was working for all the ids.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Closing as Destination Bigquery doesn't have property id.

**Comment by ali-al-najjar** [comment]
@marcosmarxm Sorry for this mistake you're right I meant source-google-analytics-data-api. I created this[ other issue](https://github.com/airbytehq/airbyte/issues/42464) and I believe a lot of people are facing the same problem.
