### ISSUE TITLE
Allow Running kubernetes E2E tests on different kube backends 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4212]
We should run kube acceptance tests against GKE and EKS since the underlying api behavior can differ from minikube/docker-for-desktop.

Create an RFC/Tech Spec addressing: 
* Decide if we should have a persistent GKE cluster or not. 
* Decide if we should run integration tests on a cadence or on demand (and if so how) 
* Ability to push dev images to GCR to be picked up by GKE when running integration tests
* Allow configuring end-to-end tests to run on either Kind or docker-compose with test containers, then also GKE

Then create follow up tickets and work on them as needed.

**Comment by cgardens** [comment]
What cadence should we be running these at? Every master build? Or every N hours have we have moved towards with connector.

**Comment by jrhizor** [comment]
Maybe every N hours

Running this on demand is the highest prio, every N hours second.

**Comment by jrhizor** [comment]
https://github.com/airbytehq/airbyte/pull/4219/files was basically my scratchpad for testing on GKE and points at the kinds of db operations we'll need to abstract out to allow working with testcontainers and external resources on kubernetes

**Comment by jrhizor** [comment]
To flesh out https://github.com/airbytehq/airbyte/pull/4219#issuecomment-864314698 more: 

We need to:
1. change the interface for getting credentials to something that allows spinning up a db in kube
2. handle uploading to a container registry (maybe a private docker hub repo?) and using those in the tests on an external platform.

**Comment by subodh1810** [comment]
Tech spec : https://docs.google.com/document/d/170JgBmRJwkuGWNZxy41bkyd6z4hAkhuKbNhZtxFtaJo/edit#heading=h.eejw85ea1yu1
