### ISSUE TITLE
Connection Page: Have Bulk/Multiple Sync Settings

### ISSUE THREAD

**Issue by numphileo** [airbytehq/airbyte#4226]
## Tell us about the problem you're trying to solve
1. There are cases wherein there are many tables, and to change the sync settings, one has to make the changes to every single table. 
2. Automate fetching of the cursor fields, and sort them by frequency in the filter. 

## Describe the solution you’d like
1. It’d really help if there was an option to change the sync settings for all tables.
2. The cursor field can be fetched from the db, usually, it is common names such as created_on, modified_on and so on. So the user can select that, for working with db. Most of these filters can be put vertically, so that it can accommodate more collapsible options.

## Describe the alternative you’ve considered or used
I've described that in the solution, and also, attaching images to it. 
1. 
![image](https://user-images.githubusercontent.com/68155102/122634623-cc214300-d0fc-11eb-91aa-fc10e56da180.png)

2. 
![image](https://user-images.githubusercontent.com/68155102/122634611-c1ff4480-d0fc-11eb-9ebd-bffaa4b7102c.png)

## Are you willing to submit a PR?
Yes, I can request a team mate to go through the repo, and prepare a PR - however, it may take us some time.

**Comment by sherifnada** [comment]
from #4762 

## Tell us about the problem you're trying to solve
As the customer/user of Airbyte, I would like to have the option to select the same sync method to all streams at once, on the stage of setting up the connections between the source connector and the destination.

## Describe the solution you’d like
Add a button or the dropdown list with the options to choose between: 
`full-refresh overwrite,  full-refresh append, Incremental refresh append, Incremental refresh append+deduplicate`

## Describe the alternative you’ve considered or used
Now it's difficult to select all the streams to a single specified sync method, the only option you have is to set sync mode for each stream manually, if you have them over 100, it takes a long time.

**Comment by jrhizor** [comment]
We should not include stream-specific namespace editing in this issue.
