### ISSUE TITLE
Harvest Connector

### ISSUE THREAD

**Issue by flexa-rob** [airbytehq/airbyte#4230]
## Expected Behavior
*Enter Harvest API Key and Account ID, click "Set up Source" and connection test succeeds*

## Current Behavior
Connection test fails with "Unable to connect to Harvest API with the provided credentials - KeyError('api_token')" - when using token that works via curl

## Logs
*![image](https://user-images.githubusercontent.com/82925669/122692660-c7ce6480-d279-11eb-84ad-8dc795ad9c51.png)*

## Steps to Reproduce
1. Generate API token and test using curl
2. Set up Harvest source
3. Enter API key and Account ID fields
2. Click "Set up Source" 

## Severity of the bug for you
High

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
`airbyte-integrations/connectors/source-harvest/source_harvest/spec.json` uses `api_key` for the API Key input field, where `airbyte-integrations/connectors/source-harvest/source_harvest/source.py` uses `config["api_token"]` when reading the API Key

**Comment by marcosmarxm** [comment]
@flexa-rob can you update the connector to version `0.1.2`? you can do this in the Admin page.

**Comment by flexa-rob** [comment]
Thanks @marcosmarxm - v0.1.2 successfully to Harvest. I'll try sync some data =)
