### ISSUE TITLE
New Source: Close.com

### ISSUE THREAD

**Issue by moqca** [airbytehq/airbyte#4231]
## Tell us about the new connector you’d like to have
* Which source and which destination?
Source: Close.com / Close.io 

## Describe the context around this new connector
Close.com is a web based CRM for sales teams. It handles lead generation ad follow up
* Which team in your company wants this integration, what for? This helps us understand the use case.
Sales and marketing to track lead quality, life cycle, historical performance, lead and total possible sale value
* How often do you want to run syncs?
5mins
* If this is an API source connector, which entities/endpoints do you need supported?
Leads, contacts, activities, opportunities, tasks, memberships, users, organizations

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Manual exports / trying to develop connector myself

**Comment by cheyura** [comment]
### Integration Vetting
**Webhook-based? (no/partially/yes)**
Partially

Available authentication modes (API key/Oauth/other)

Creating an account


Has Sandbox environment ?


How to populate the account with data?


Integration supports incremental sync?


Other information/blockers

**Comment by cheyura** [comment]
@sherifnada Sandbox is created for more than trial term, API key generated. Vetting is above, ready for populating

**Comment by sherifnada** [comment]
thanks @cheyura !
