### ISSUE TITLE
improve latency of kubernetes operations

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4233]
Many of our UI and API operations depend on launching Kubernetes pods. Some of our state waiting logic could be improved to minimize the amount of time it takes to launch and run these processes.

This is a placeholder ticket for the general class of issues. Specific problems and implementations merit their own issues.

**Comment by jrhizor** [comment]
We can likely tune the backoff parameters for various waits in `KubePodProcess`.

**Comment by EDjur** [comment]
Hi @jrhizor !

I just deployed in GKE and noticed that a lot of operations are a lot slower than on my laptop just using docker-compose.

As you say, it looks like a lot of the time is wasted on PodInitializing state (due to some checks?).

Do you know if there is any progress on this?

**Comment by jrhizor** [comment]
@davinchia has actually been investigating this in depth the last couple weeks. We expect to get most check operations to something more comparable with the docker-compose versions in the next week or two (probably with just a few seconds of additional overhead).

**Comment by EDjur** [comment]
Oh that's excellent news! Thank you both!

**Comment by tovbinm** [comment]
@jrhizor any news to share on this?

**Comment by davinchia** [comment]
This is done. We've gotten this down to 4 - 5 seconds overhead in general including creating pods & code execution.
