### ISSUE TITLE
Orbit.love Connector

### ISSUE THREAD

**Issue by Adovenmuehle** [airbytehq/airbyte#4239]
## Tell us about the new connector you’d like to have
* Which source and which destination? The source will be from the [orbit.love API](https://docs.orbit.love/reference)
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? As far as I can tell, the API is pretty new and only has a [v1 swagger spec](https://app.orbit.love/api-docs/v1/swagger.json)

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
I'm a consultant who works with two clients who are looking for this integration. One of which is [streamlit](https://streamlit.io). We're wanting to get the orbit data into their warehouse for analysis on open source engagement.
* How often do you want to run syncs? I would imagine daily is probably fine.
* If this is an API source connector, which entities/endpoints do you need supported? Users, Activities, Members, Workspaces

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Write some custom python to consume the API and call it from Airflow.

**Comment by marcosmarxm** [comment]
thanks @Adovenmuehle i added the connector in the roadmap for connector development.

**Comment by cheyura** [comment]
Webhook-based? (no/partially/yes)
Partially https://docs.orbit.love/docs/webhooks


Available authentication modes (API key/Oauth/other)
Orbit uses API tokens to authorize access to the API. You can find your API tokens on the Account Settings page.

Has Sandbox environment ?
No

How to populate the account with data?
The simpliest way is UI. Already populated. @sherifnada please take a quick view on populated data


Available streams for sync
Activity Types
Users
Activities
Members
Notes
Reports
Workspaces


Integration supports incremental sync?
No


Other information/blockers
No

**Comment by cheyura** [comment]
@sherifnada Ready for implementation

**Comment by sherifnada** [comment]
thanks @cheyura !

**Comment by andrewm4894** [comment]
We have a use case for Orbit <-> BigQuery at Netdata Cloud. I'd be happy to help test or help in some way.
