### ISSUE TITLE
Local and workspace volumes should be scoped by airbyte_

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#424]
From jrhizor 's demo with roshan.

`airbyte_local` already is. `dev_root` => `airbyte_dev_root`?.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368109522468) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
@jrhizor can we close this?

**Comment by cgardens** [comment]
I think this is done now? `dev_root` isn't a thing anymore and `airbyte_local` is already properly scoped.

**Comment by jrhizor** [comment]
Yeah this is good to close. The directory it's in provides a prefix so you end up with:
```
→ docker volume ls | grep airbyte
local     airbyte_data
local     airbyte_db
local     airbyte_workspace
```
