### ISSUE TITLE
[abctl] New install failing when creating new sources `An unknown error occurred. (HTTP 504)`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#42404]
### What happened?

I am not able to create new sources (I tried with Faker and Support Zendesk). Both failed with the same error.

![image](https://github.com/user-attachments/assets/7c7bd3bb-b89a-46ac-85dc-cd4a2c5f549f)

### What did you expect to happen?

1. Have better error to understand what is causing the problem.
2. Be able to create the source.

### Abctl Version

<details>

```console
$ abctl version
# version: v0.8.2
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Fri Jun 28 23:59:41 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.32.0 (157355)
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

</details>

### OS Version

<details>

```console
# On Mac:
$ uname -a
Darwin Marcos--MacBook-Pro---C02FL0ZCMD6R 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
```

</details>

**Comment by perangel** [comment]
I am not able to reproduce this with a new `abctl` install neither on my older version or on the latest `0.8.2`

**Comment by saiprasath-anjane** [comment]
@marcosmarxm and @perangel Yeah same issue here, it works fine with cloud, but not with the recent `abctl-v0.8.2`. Firstly I got 504 error, then later I got 400 error, I have mentioned the same in [PR #55](https://github.com/airbytehq/abctl/pull/55) as well.
I'm using the same credentials for both source and destination in cloud and local, but not able to create it in local for both source and destination.

**Comment by marcosmarxm** [comment]
This was solved after increasing the CPU and memory allocated to my Desktop Docker.

**Comment by saiprasath-anjane** [comment]
@marcosmarxm actually even after installing v0.9.1 I get the same error
<img width="926" alt="image" src="https://github.com/user-attachments/assets/1bc3a865-7d29-46f7-82ee-dac82dff773c">

**Comment by mikhail-vlasenko** [comment]
> Increasing the CPU and memory

same, t3.large on aws wasn't enough (despite never using more than 50% RAM), t3.2xlarge worked

**Comment by techieshark** [comment]
Same issue here. It's unclear what the issue is from the error alone ("504"); if the issue is in fact a cpu/mem issue, is there some way to expose that to the user? I had 4gb allocated to docker, will try with more.
