### ISSUE TITLE
Missing configuration fields for SSL authorization in MSSQL connector

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#4242]
## Expected Behavior
The configuration fields trustStorePassword and trustStoreName for a connection with the SSL method 'Encrypted (verify certifcate)' in the MSSQL connector should be displayed.

## Current Behavior
The trustStorePassword and trustStoreName configuration fields are not displayed in the configuration screen. When saving the connection, an error is finally thrown that these fields are not filled.

## Logs
[server-logs-anonym.txt](https://github.com/airbytehq/airbyte/files/6687801/server-logs-anonym.txt)

![Bildschirmfoto 2021-06-18 um 10 50 18](https://user-images.githubusercontent.com/39857259/122789556-b99f3900-d2b7-11eb-83cb-7c4e664f8158.png)

## Steps to Reproduce
1. Create MSSQL source
2. SSL method 'Encrypted (verify certifcate)'

## Severity of the bug for you
High

## Airbyte Version
v0.25.0-alpha (production) but also tested on v0.26.1-alpha

## Connector Version (if applicable)
MSSQL: 0.3.2

## Additional context
I would like to help and debug the connector, but don't know how this works with the MSSQL connector. Maybe an entry in the documentation on this topic would be useful.

**Comment by rodireich** [comment]
Issue resolved with the latest source mssql
