### ISSUE TITLE
[source-woocommerce] Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jordi-ydteam** [airbytehq/airbyte#42462]
### Connector Name

source-woocommerce

### Connector Version

0.2.12

### What step the error happened?

During the sync

### Relevant information

I am experiencing an issue where no data is being loaded into Airbyte from my WooCommerce connection. Specifically, when I run the streams for products and orders, I see zero records loaded. However, when I attempt to retrieve the same data using a Python script, I encounter the following error:

````
JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
````

This error indicates the presence of a Byte Order Mark (BOM) in the JSON response from WooCommerce.

However, when I handle the BOM appropriately in Python using json.loads(data.decode('utf-8-sig')), the data loads correctly.

Here is an example of the function that works:

````
import requests
from requests.auth import HTTPBasicAuth
import json

consumer_key = 'ck_'
consumer_secret = 'cs_'
woocommerce_url = 'https://example.com/wp-json/wc/v3/'

def fetch_data(endpoint):
    url = f"{woocommerce_url}{endpoint}"
    response = requests.get(url, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    if response.status_code == 200:
        data = response.content.decode('utf-8-sig')
        return json.loads(data)
    else:
        raise Exception(f"Failed to fetch data: {response.status_code}")

products = fetch_data('products')
orders = fetch_data('orders')

````
Given this, I suspect that Airbyte might be failing silently due to this BOM issue without raising any explicit errors.

### Question:

Is it possible to modify the WooCommerce connector in Airbyte to handle or strip out the BOM from the JSON response to ensure that data is loaded correctly?

### Relevant log output

```shell
Cell In[17], line 19, in check_woocommerce_endpoint(endpoint)
     16 response = requests.get(url, auth=HTTPBasicAuth(consumer_key, consumer_secret))
     18 if response.status_code == 200:
---> 19     data = response.json()
     20     if data:
     21         print(f"Found {len(data)} records in {endpoint}.")

File /usr/local/lib/python3.10/dist-packages/requests/models.py:978, in Response.json(self, **kwargs)
    974     return complexjson.loads(self.text, **kwargs)
    975 except JSONDecodeError as e:
    976     # Catch JSON-related errors and raise as requests.JSONDecodeError
    977     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 978     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Can you update to the latest woocommerce? @strosek was just converting it to low-code recently and fixing some things there, I hope it's related and it could already be taken care of. Ping us if not.
