### ISSUE TITLE
Identify if Postgres CDC requires capped queue 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#4253]
In issue https://github.com/airbytehq/airbyte/issues/3969#issuecomment-864007649 we identified that mysql cdc implementation was suffering from OOM cause of queue implementation. We should try to analyse if the same problem exists in postgres as well cause we use the same approach there as well

**Comment by grishick** [comment]
Looking at https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/debezium/src/main/java/io/airbyte/integrations/debezium/AirbyteDebeziumHandler.java base class this appears to be addressed already in this [PR #4580](https://github.com/airbytehq/airbyte/pull/4580)
