### ISSUE TITLE
Zendesk Support connection is running slow

### ISSUE THREAD

**Issue by erichartono** [airbytehq/airbyte#4258]
## Expected Behavior
For syncing less than 100 records, it would be great to sync within 1-2 mins.

## Current Behavior
Last sync was 97 records for 53 mins.

![image](https://user-images.githubusercontent.com/19322804/122837229-17bf3100-d337-11eb-9758-e27d5d294aab.png)

## Logs
[logs-38-0.txt](https://github.com/airbytehq/airbyte/files/6689869/logs-38-0.txt)

## Steps to Reproduce
1. Zendesk Support to Redshift using S3

## Severity of the bug for you
Low

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
Zendesk Support 0.2.2
Redshift 0.3.9

## Additional context
EC2 T3.Large instance

**Comment by marcosmarxm** [comment]
@sherifnada fyi, this could be something from the zendesk?

**Comment by sherifnada** [comment]
@erichartono how much data is in the redshift destination? I'm trying to determine if this is related to normalization or if the issue is coming from zendesk

**Comment by marcosmarxm** [comment]
@erichartono can you subscribe to issue pointed by Sherif?

I'll add this information to troubleshooting area because can become a recurrent question.

**Comment by danieldiamond** [comment]
@erichartono 

I assume that log provided is not from the original 7h sync?
I cancelled my sync after 4 hours (and 80,000 lines of logging) and watching the API activity in zendesk. The number of requests were ~30,000. Worried this is performing 1 request per record or similar...

**Comment by ojofranco** [comment]
<img width="830" alt="imagen" src="https://user-images.githubusercontent.com/9533710/124862940-dc01a980-df7b-11eb-9078-0631dcc610d5.png">

We have a really big Zendesk acount, after upgrade to zendesk-support 0.2.3 the time for sync reduce  from  15-20 hours to less than 1.  The  normalization of the Custom Tickets Fields  dbt model   (zendesk_tickets_custom_fields)   improve the  latency.  I had to  drop the _airbyte temporal tables.

**Comment by Mohmmadhd** [comment]
> <img alt="imagen" width="830" src="https://user-images.githubusercontent.com/9533710/124862940-dc01a980-df7b-11eb-9078-0631dcc610d5.png">
> 
> We have a really big Zendesk acount, after upgrade to zendesk-support 0.2.3 the time for sync reduce from 15-20 hours to less than 1. The normalization of the Custom Tickets Fields dbt model (zendesk_tickets_custom_fields) improve the latency. I had to drop the _airbyte temporal tables.

@ojofranco What dbt model are you referring to?
