### ISSUE TITLE
New Source: Chargebee

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4265]
## Tell us about the new connector you’d like to have
I'd like to support pulling data from chargebee https://apidocs.chargebee.com/docs/api

**Comment by sherifnada** [comment]
A user has already contributed their connector (which they report they've been using in prod for some time ) in #3410 . We should use our own sandbox credentials to push that connector over the finish line.

**Comment by Zirochkaa** [comment]
## Integration Vetting
**Webhook-based? (no/partially/yes)**
partially. [Events](https://apidocs.chargebee.com/docs/api/events?prod_cat_ver=2), for example, support webhooks

**Available authentication modes (API key/Oauth/other)**
[HTTP Basic Auth](https://apidocs.chargebee.com/docs/api?prod_cat_ver=2#api_authentication)

**Connecting to the data source**
_if API Source, what kind of API? (SOAP/GraphQL/REST/other)_
REST

**Creating an account**
_self-service free account available? If yes then create it using integration-test@airbyte.io (you should be getting emails sent to this email address)_
yes and already created. Right now it has a trial which will expire in 13 days. Maybe a free account will suit us. If no then the cheapest account costs $299/month (if billed monthly, annually will cost $249/month).

**How to populate the account with data?**





**Available streams for sync**
[Subscription](https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=2#list_subscriptions)
[Customers](https://apidocs.chargebee.com/docs/api/customers?prod_cat_ver=2#list_customers)
[Invoices](https://apidocs.chargebee.com/docs/api/invoices?prod_cat_ver=2#list_invoices)
[Orders](https://apidocs.chargebee.com/docs/api/orders?prod_cat_ver=2#list_orders)
[Plans](https://apidocs.chargebee.com/docs/api/plans?prod_cat_ver=1&lang=curl) (our account doesn't have suppost for this stream, see below screenshot)

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/19872253/124707870-1af31900-df02-11eb-9a9b-3f621e9e05b6.png">

[Addons](https://apidocs.chargebee.com/docs/api/addons?prod_cat_ver=1&lang=curl) (our account doesn't have suppost for this stream, see below screenshot)

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/19872253/124707801-00b93b00-df02-11eb-8a8e-b6f32fff4c5f.png">


and some other streams

**Do any streams support incremental sync?**
Some streams support incremental sync using following format `updated_at[after] = "1243545465"`:
[Subscription](https://apidocs.chargebee.com/docs/api/subscriptions?prod_cat_ver=2#list_subscriptions_updated_at)
[Customers](https://apidocs.chargebee.com/docs/api/customers?prod_cat_ver=2#list_customers_updated_at)
[Invoices](https://apidocs.chargebee.com/docs/api/invoices?prod_cat_ver=2#list_invoices_updated_at)
[Orders](https://apidocs.chargebee.com/docs/api/orders?prod_cat_ver=2#list_orders_updated_at)
[Plans](https://apidocs.chargebee.com/docs/api/plans?prod_cat_ver=1&lang=curl#list_plans_updated_at)
[Addons](https://apidocs.chargebee.com/docs/api/addons?prod_cat_ver=1&lang=curl#list_addons_updated_at)

**Preparation scope & blockers**

We don't have an access to 2 streams - `Plans` and `Addons`, when we are doing requests to that streams we are getting `400` error code.

**Other information/blockers**

**Comment by sherifnada** [comment]
sounds like this might be a result of the API version upgrade described in [this link](https://apidocs.chargebee.com/docs/api/upgrade?prod_cat_ver=2) 

<img width="1404" alt="Screen Shot 2021-07-06 at 11 36 26 PM" src="https://user-images.githubusercontent.com/6246757/124711494-ff145680-deb2-11eb-91c6-7fab9f022b69.png">

Let's add support for the following endpoints if possible: 
* Items 
* Item prices
* Attached Items
This way we maintain backwards compatibility and use the newest API version.
