### ISSUE TITLE
Google Ads remove required fields from spec.json

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4268]
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
![image](https://user-images.githubusercontent.com/5154322/122919586-c7e06a00-d336-11eb-9833-dc39c27005a8.png)

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

**Comment by sherifnada** [comment]
solved in #4288
