### ISSUE TITLE
Source PostHog: Support self hosted PostHog instances

### ISSUE THREAD

**Issue by asamiller** [airbytehq/airbyte#4283]
## Tell us about the problem you're trying to solve
We use the self hosted version of PostHog. I'd like to sync the data with AirByte but there's no way to specify the URL for our instance. 

## Describe the solution you’d like
The ability to set the URL of our PostHog instance on the New Source screen and have it sync with that instead of the cloud version.

## Are you willing to submit a PR?
Sorry, no

**Comment by coeurdestenebres** [comment]
@asamiller I've started working on the bounty
