### ISSUE TITLE
airbyte-ci tool incorrectly errors out if airbytehq/airbyte is not one of the remote repositories

### ISSUE THREAD

**Issue by jettdc** [airbytehq/airbyte#42837]
### Topic

airbyte-ci

### Relevant information

See here: https://github.com/airbytehq/airbyte/blob/a7fb873ba6dfe224a1f62c234e97eda73e323705/airbyte-ci/connectors/pipelines/pipelines/cli/ensure_repo_root.py#L14

If `airbytehq/airbyte` is not listed as a repo remote, then the airbyte-ci tool exits. I'm working on a fork of the repo and this was not automatically set for me when I cloned the repo, meaning I had to manually go in and add:

```
git remote add airbyte https://github.com/airbytehq/airbyte.git
```

which is fine but it should either:
- Use a smarter check
- Or document in that warning message that you need to add the repo as a remote

since I needed to dig through the code to find this

**Comment by natikgadzhi** [comment]
Doesn't the warning message below the line you linked show up?

Airbyte CI is by design highly coupled with this repo. It's not ideal, but it helped us move quickly early on. Ideally, of course, we should make it repository agnostic. In the meantime, a PR with a better warning would be welcome.
