### ISSUE TITLE
[source-Mongodb] schema auto detection is unreliable

### ISSUE THREAD

**Issue by fabianboerner** [airbytehq/airbyte#42862]
### Connector Name

airbyte/source-mongodb-v2

### Connector Version

1.4.3

### What step the error happened?

Configuring a new connector

### Relevant information

the schema autodetection changes object -> null or endDate -> null this causes the target connector postgres to store the time as json b and in case of dates it crashes our BI application on a postgres query.

Here in the screenshot you can see the schema changes already existings strings to null wich then are synced as jsonb to postgres and eventually crashing the queries:

![image](https://github.com/user-attachments/assets/4c6e246d-cd41-4187-9825-a958cf2c031a)

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@airbytehq/dbsources can someone take a look into this. @fabianboerner is it possible to share the schema from Mongo collection?

**Comment by fabianboerner** [comment]
for exampe job statistics schema:

`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "_id": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[a-fA-F0-9]{24}$"
        }
      },
      "required": ["$oid"]
    },
    "id": {
      "type": "string",
      "format": "uuid"
    },
    "jobReference": {
      "type": "string",
      "format": "uuid"
    },
    "positionId": {
      "type": "string",
      "format": "uuid"
    },
    "internalCampaignId": {
      "type": "string",
      "format": "uuid"
    },
    "externalCampaignId": {
      "type": "string",
      "format": "uuid"
    },
    "channelId": {
      "type": "string",
      "format": "uuid"
    },
    "platform": {
      "type": "string"
    },
    "date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": ["$date"]
    },
    "paidApplications": {
      "type": "integer",
      "minimum": 0
    },
    "paidClicks": {
      "type": "integer",
      "minimum": 0
    },
    "paidConversions": {
      "type": "integer",
      "minimum": 0
    },
    "paidImpressions": {
      "type": "integer",
      "minimum": 0
    },
    "organicApplications": {
      "type": "integer",
      "minimum": 0
    },
    "organicClicks": {
      "type": "integer",
      "minimum": 0
    },
    "organicConversions": {
      "type": "integer",
      "minimum": 0
    },
    "organicImpressions": {
      "type": "integer",
      "minimum": 0
    },
    "spent": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number",
          "minimum": 0
        },
        "currency": {
          "type": "string",
          "enum": ["EUR", "USD", "GBP", "JPY", "CHF", "AUD", "CAD"]
        }
      },
      "required": ["amount", "currency"]
    }
  },
  "required": ["_id", "id", "jobReference", "positionId", "internalCampaignId", "externalCampaignId", "channelId", "platform", "date"]
}`

**Comment by theyueli** [comment]
@fabianboerner Airbyte currently derives the schema via sampling. If the data that contains the data is not sampled, then it thinks the schema has changed. If your schema doesn't change much in your use case, you could increase the value of "Document discovery sample size (Advanced)" in the MongoDB connector's configuration to a much larger value, e.g.,  100000. (you can even make it as large as the number of records in your data).  Our sampling procedure then iterates the first 100000 records to determine the current schema.

**Comment by fabianboerner** [comment]
@theyueli Hi, we already set the maximum. It didnt help. With patience if i hit refesh source schema enough i get the right schema. Is it so difficult to make the schema editable or to have an advanced editor to enter a json schema or something simliar?

**Comment by evantahler** [comment]
>  Is it so difficult to make the schema editable or to have an advanced editor to enter a json schema or something simliar?

That's not something we have on our roadmap at this time.  

It seems like you've got a collection with vastly different properties in your records.  Airbyte expects data that's more-or-less consistent in each collection.  If we can't discover a regular shape for your data, you can disable [schema enforcement](https://docs.airbyte.com/integrations/sources/mongodb-v2#schema-enforcement) from your source, and you'll get all the data from your source, but in a "data" object.  You can then expand & type-cast that in your destination, given a schema you know more about.

**Comment by evantahler** [comment]
Closing this issue as something we will not work on at this time, and there's a path forward via disabling scheme enforcement.

**Comment by fabianboerner** [comment]
@evantahler MongoDB is document based system, there are no schema definition on top that enforce saving the document that way. For mongodb that means every null value is a additional data on the disc. Its not like a sql where the database has columns and null values have no additional storage impact.

If we enforce null to be written we have additional storage cost for the collection and the index.

The schema is not vastly different, there is a difference of a key "endDate" is stored or not stored because it is not a required field.

**Comment by evantahler** [comment]
If you really want to get into the weeks and manually define a schema, you can modify the content of the catalog for the connection in the airbyte database, but that is not something we recommend or support going forward.

**Comment by fabianboerner** [comment]
Thats not something we will go for, if not provided through airbyte. We dont have the resources to maintain this.

We will try to figure something out.  

But i think a schema definition for mongodb is a needed addition, because also in an initial setup of a collection there is no schema or documents. It would eventually destroy the schema definition on the destination or if you rely on airbyte the table would be missing.

**Comment by fabianboerner** [comment]
I think this is also an issue when the document evolves and in later version get another attribute and only 100 documents of 100000 have the new attribute.

To no make it possible to have a schema for mongodb on airbyte puts us for huge problems.

**Comment by evantahler** [comment]
@fabianboerner you are describing the problems of moving a schemaless object into a schema-aware system!  That is why for your use-case we recommend that you disable schema enforcement, and move the raw objects to your destination as blobs.

**Comment by fabianboerner** [comment]
that is not a solution if the main purpose is to move data into systems that are used by BI-Tools that rely mostly on SQL. That would defeat the purpose and in our case would need weeks of refactoring.

**Comment by evantahler** [comment]
I've created this discussion (https://github.com/airbytehq/airbyte/discussions/45130) to carry the converstation forward.  At this time, we are not prioritizing this work, but we may if we receive significant community interest.   Also, pull requests with feature additions are always welcome!
