### ISSUE TITLE
[abctl] In place install fails due to previously used port

### ISSUE THREAD

**Issue by Andrew-InTheBox** [airbytehq/airbyte#42945]
### What happened?

When attempting to run abctl local install to do an in-place upgrade, it fails and reports that port 8000 is unavailable.  

### What did you expect to happen?

abctl should spin down the containers, update/upgrade everything, and restart without losing local configuration data.

### Abctl Version

<details>

```console
$ abctl version
version: v0.11.0
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:55:52 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop  ()
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

**Comment by yourdevDex** [comment]
I also encounter this. 404 not found. Whats the solution?

**Comment by colesnodgrass** [comment]
@Andrew-InTheBox @yourdevDex 

Could you provide what the following two commands return?
```
docker ps | grep  airbyte-abctl
```
```
curl -v http://localhost:8000/api/v1/instance_configuration 1> /dev/null
```

**Comment by Andrew-InTheBox** [comment]
Sure thing.

`acb@ACBDESKTOP:~$ docker ps | grep airbyte-abctl
c68f404f5229   kindest/node:v1.29.1   "/usr/local/bin/entr…"   4 weeks ago   Up 34 seconds   0.0.0.0:8000->80/tcp, 127.0.0.1:34491->6443/tcp   airbyte-abctl-control-plane
acb@ACBDESKTOP:~$ curl -v http://localhost:8000/api/v1/instance_configuration 1> /dev/null
*   Trying 127.0.0.1:8000...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/v1/instance_configuration HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Temporarily Unavailable
< Date: Mon, 12 Aug 2024 19:48:25 GMT
< Content-Type: text/html
< Content-Length: 190
< Connection: keep-alive
<
{ [190 bytes data]
100   190  100   190    0     0   153k      0 --:--:-- --:--:-- --:--:--  185k
* Connection #0 to host localhost left intact`

**Comment by Andrew-InTheBox** [comment]
Any updates or recommended work-arounds on this?

**Comment by abuchanan-airbyte** [comment]
Can you try this with the newer version of abctl `v0.14.2`?

**Comment by abuchanan-airbyte** [comment]
@Andrew-InTheBox did you get this working with a newer version?
