### ISSUE TITLE
When changing schema setting, previously selected tables are lost

### ISSUE THREAD

**Issue by tylerdelange** [airbytehq/airbyte#4295]
## Current Behavior
When selecting tables to sync for a connection you would expect that if you needed to make changes to the schema later that the tables would persist and still be selected when using the 'Update latest source schema" option. But after clicking this button ALL tables are then selected by default.

We have a ton of tables and have had to split the tables into many different connections. Which means every time we have to do a schema change we lose all the previously "SELECTED" tables and have to manually select all the tables again which is very time consuming.

## Steps to Reproduce
1. Create a connection
2. Select one or more tables to sync
3. Save connection
4. Go back into connection
5. Click "Update latest source schema" button
6. ALL tables are now selected and previously selected tables are lost

## Severity of the bug for you
High

## Connector Version (if applicable)
mySQL 0.3.8
airbyte 0.26.2-alpha

**Comment by kyle-cheung** [comment]
+1, my source schema is updated once a week and having to sift through a list of 300 to reselect 10 of them is quite a nuisance

**Comment by nataliekwong** [comment]
Closing, as this has been resolved for some time!

Verified in v0.50.34 and Cloud.
