### ISSUE TITLE
SAT: Validate input config.json against spec.json

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4299]
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
There was a case where a connector was published and the spec.json didnt match the field name used by connector.
Probably because when developing connector is used the `secrets/config.json` and at the end is not validating using a UI acceptance test or the spec.json flow.
Should be have a test case for that.

Probably two issues related with this are:
- https://github.com/airbytehq/airbyte/issues/4268
- https://github.com/airbytehq/airbyte/issues/4221

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / **High** / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

@sherifnada and @tuliren fyi

**Comment by tuliren** [comment]
Good idea. So we can add a test case in the integration test that validate the `secrets/config.json` against the schema defined in `spec.json`. One potential issue is that sometimes the `secrets/config.json` from GitHub secret is just a partial config, and the code patch it with specific configurations. But this is not too big a problem. We can make `secrets/config.json` to always be complete.

**Comment by sherifnada** [comment]
related: https://github.com/airbytehq/airbyte/issues/2711
