### ISSUE TITLE
support pre-text for configs starting with local paths

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#430]
The local CSV config would be much easier to fill out if it prefixed the path with the local root. It seems like some persistence constants need to be made available to integrations so they can use them in their rendering.

This is kind of tricky so we have to think about how to do it so we aren't stuck with a terrible interface.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368168011533) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
To make sure I understand.... if `LOCAL_ROOT=/tmp/airbyte_local`, then the value in the box would start out as `/tmp/airbyte_local` and the user would just add onto the end of it?
