### ISSUE TITLE
[destination-snowflake] Why use insert+delete+delete instead of merge?

### ISSUE THREAD

**Issue by svickers** [airbytehq/airbyte#43046]
### Topic

Destination data loading inefficiencies

### Relevant information

We recently switched from fivetran to airbyte and while we saved a bit of money.  We also saw a massive *10x* increase in snowflake credit usage, more than making up for the money saved.   This is almost entirely due to how airbyte inserts the updated records as duplicates and then has to go back through and delete the earlier versions.  

Here is the problem statement: 
```sql
DELETE FROM "AIRBYTE_V2"."RECEIPTITEMS"
WHERE "_AIRBYTE_RAW_ID" IN (
  SELECT "_AIRBYTE_RAW_ID" FROM (
    SELECT "_AIRBYTE_RAW_ID", row_number() OVER (
      PARTITION BY "RECEIPTITEMID" ORDER BY "_AB_CDC_CURSOR" DESC NULLS LAST, TIMESTAMPADD(
  HOUR,
  EXTRACT(timezone_hour from "_AIRBYTE_EXTRACTED_AT"),
  TIMESTAMPADD(
    MINUTE,
    EXTRACT(timezone_minute from "_AIRBYTE_EXTRACTED_AT"),
    CONVERT_TIMEZONE('UTC', "_AIRBYTE_EXTRACTED_AT")
  )
)
 DESC
    ) as row_number FROM "AIRBYTE_V2"."RECEIPTITEMS"
  )
  WHERE row_number != 1
);
```
This table is 4 billion rows deep and this query is responsible for not one, but **two** full table scans of 56 GB each.  At the *very* least it should be querying on the primary key that we have specified in airbyte, which incidentally is also the cluster key. Using the unclustered long string of  _airbyte_raw_id is bad bad bad.  The table is also always growing so will just cost more and more in compute power and time with each passing day.

The solution to this is to not create duplicate records at all.  Instead of inserting everything from the raw table and then going back through to delete the updates and also delete the deletes, it could be handled with a single merge statement:

```sql
MERGE INTO "AIRBYTE_V2"."RECEIPTITEMS" as final USING (select * from "airbyte_internal"."airbyte_v2_raw__stream_ReceiptItems" where _airbyte_loaded_at is null) as staging ON final.receipt_id = staging._airbyte_data:receipt_id
    WHEN MATCHED AND staging._airbyte_data:_ab_cdc_deleted_at is not null THEN DELETE
    WHEN MATCHED THEN UPDATE SET 
        final._airbyte_extracted_at = staging._airbyte_extracted_at,
        final._ab_cdc_updated_at = staging._airbyte_data:_ab_cdc_updated_at::timestamp_tz,
        final.customer_name = staging._airbyte_data:customer_name,
        final.total_amount = staging._airbyte_data:total_amount
    WHEN NOT MATCHED THEN INSERT (_airbyte_raw_id, _airbyte_extracted_at, _ab_cdc_updated_at, receipt_id, customer_name, total_amount) 
    VALUES (staging._airbyte_raw_id, staging._airbyte_extracted_at, staging._airbyte_data:_ab_cdc_updated_at::timestamp_tz, staging._airbyte_data:receipt_id, staging._airbyte_data:customer_name, staging._airbyte_data:total_amount);
```

Here is a script to create example tables with the 2 different methods of getting the data updated.  When trialing on a xs warehouse with 100M records the results were as follows:
Merge: 29s, 4.06GB scanned
Airbyte:  1m 11s, 7.42GB scanned

```sql
-- 1. Create sample of target table of 100m records
CREATE OR REPLACE TABLE target_receipts (_airbyte_raw_id varchar, _airbyte_extracted_at timestamp_tz, _ab_cdc_updated_at timestamp_tz, _ab_cdc_deleted_at timestamp_tz, receipt_id number, customer_name varchar, total_amount number);
insert into target_receipts (_airbyte_raw_id, _airbyte_extracted_at, receipt_id, customer_name, total_amount)
select uuid_string(), current_timestamp(), random(), randstr(15,random()), uniform(0,100,random()) from table(generator(rowCount => 100000000));

-- 2. Create sample stream table for inserting/updating
-- Fill with 50k records, 1% to be updated and 1% to be deleted
CREATE OR REPLACE TABLE airbyte_raw_receipts (_airbyte_raw_id varchar, _airbyte_extracted_at timestamp_tz, _airbyte_loaded_at timestamp_tz, _airbyte_data variant);
insert into airbyte_raw_receipts
select uuid_string(), 
    current_timestamp(), 
    null, 
    { 
        'receipt_id':iff(uniform(1,10,random())=1, receipt_id, random()), -- 1% of rows to be updated
        'customer_name':randstr(15,random()),
        'total_amount':uniform(0,100,random()),
        '_ab_cdc_deleted_at': iff(uniform(1,10,random())=1,current_timestamp,null), -- 1% of rows to be deleted
        '_ab_cdc_updated_at': current_timestamp()
    } from target_receipts
    order by random()
    limit 50000;

-- 3. Run MERGE method
MERGE INTO target_receipts as final USING (select * from airbyte_raw_receipts where _airbyte_loaded_at is null) as staging ON final.receipt_id = staging._airbyte_data:receipt_id
    WHEN MATCHED AND staging._airbyte_data:_ab_cdc_deleted_at is not null THEN DELETE
    WHEN MATCHED THEN UPDATE SET 
        final._airbyte_extracted_at = staging._airbyte_extracted_at,
        final._ab_cdc_updated_at = staging._airbyte_data:_ab_cdc_updated_at::timestamp_tz,
        final.customer_name = staging._airbyte_data:customer_name,
        final.total_amount = staging._airbyte_data:total_amount
    WHEN NOT MATCHED THEN INSERT (_airbyte_raw_id, _airbyte_extracted_at, _ab_cdc_updated_at, receipt_id, customer_name, total_amount) 
    VALUES (staging._airbyte_raw_id, staging._airbyte_extracted_at, staging._airbyte_data:_ab_cdc_updated_at::timestamp_tz, staging._airbyte_data:receipt_id, staging._airbyte_data:customer_name, staging._airbyte_data:total_amount);

-- 4. AIRBYTE method  ** Run step2 again to start with a fresh stream table **
BEGIN TRANSACTION;
INSERT INTO target_receipts --insert everything
(_airbyte_raw_id, _airbyte_extracted_at, _ab_cdc_updated_at, _ab_cdc_deleted_at, receipt_id, customer_name, total_amount
)
WITH intermediate_data AS (
  SELECT
  _airbyte_raw_id,
  _airbyte_extracted_at,
  _airbyte_data:_ab_cdc_updated_at as _ab_cdc_updated_at,
  _airbyte_data:_ab_cdc_deleted_at as _ab_cdc_deleted_at,
  _airbyte_data:receipt_id as receipt_id,
  _airbyte_data:customer_name as customer_name,
  _airbyte_data:total_amount as total_amount
  FROM airbyte_raw_receipts
  WHERE _airbyte_loaded_at is null
), new_records AS (
  SELECT
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _ab_cdc_updated_at,
    _ab_cdc_deleted_at,
    receipt_id,
    customer_name,
    total_amount
  FROM intermediate_data
    ), numbered_rows AS (
        SELECT *, row_number() OVER (
            PARTITION BY receipt_id ORDER BY _ab_cdc_updated_at DESC NULLS LAST, _airbyte_extracted_at DESC
    ) AS row_number
  FROM new_records
)
SELECT 
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _ab_cdc_updated_at,
    _ab_cdc_deleted_at,
    receipt_id,
    customer_name,
    total_amount
FROM numbered_rows
WHERE row_number = 1;

DELETE FROM target_receipts  --delete outdated records
WHERE _airbyte_raw_id IN (
  SELECT _airbyte_raw_id FROM (
    SELECT _airbyte_raw_id, row_number() OVER (
      PARTITION BY receipt_id ORDER BY _ab_cdc_updated_at DESC NULLS LAST, TIMESTAMPADD(
          HOUR,
          EXTRACT(timezone_hour from _AIRBYTE_EXTRACTED_AT),
          TIMESTAMPADD(
            MINUTE,
            EXTRACT(timezone_minute from _AIRBYTE_EXTRACTED_AT),
            CONVERT_TIMEZONE('UTC', _AIRBYTE_EXTRACTED_AT)
          )
    )
 DESC
    ) as row_number FROM target_receipts
  )
  WHERE row_number != 1
);


DELETE FROM target_receipts  --delete deleted records
WHERE _AB_CDC_DELETED_AT IS NOT NULL;

COMMIT;
```

Tell me what I'm missing, because this is painful.

Query plan comparison
![Screenshot_325](https://github.com/user-attachments/assets/33394ae3-af47-4040-8343-172984a0602d)

**Comment by marcosmarxm** [comment]
Thank you for the detailed analysis, @svickers. @airbytehq/destinations, could someone review the insights in this analysis?

**Comment by marcosmarxm** [comment]
@svickers This is something the team is aware of, and there are future plans to improve it. For now, Evan wrote a [blog post](https://airbyte.com/blog/cost-conscious-advanced-elt-strategies-for-data-deduplication) providing a workaround if you're facing this problem.

**Comment by sumeetgajjar** [comment]
It seems a `MERGE` approach was implemented in #31683
However, it was reverted in https://github.com/airbytehq/airbyte/commit/13e2672fe8c31b25b2d0f61c020cf21a00dddc61, Since the revert was pushed directly the reason for the revert is missing.

Started a thread to understand the reason for the revert: https://github.com/airbytehq/airbyte/pull/31683#issuecomment-2272445211

**Comment by gisripa** [comment]
@svickers  Super thanks for analyzing this. We tried to modify the query to use `MERGE` and unfortunately had to rollback because of claims from a couple of customers that there was an increased activity in their warehouse with the `MERGE` statement. We never got around to verify if that claim was true on our end. Coincidentally I'm looking into it this week. Would you be open to testing a pre-release version after I test and verify on our end.

**Comment by evantahler** [comment]
Reference: https://github.com/airbytehq/airbyte-internal-issues/issues/8364

**Comment by svickers** [comment]
@gisripa Yes happy to help verify.

**Comment by gisripa** [comment]
@svickers  I have a pre-release image if you want to try out `3.11.7-dev.d41069cac4`. But if you want me to pin this version on your workspace let me know.

**Comment by svickers** [comment]
@gisripa Here is our workspace, will we be able to toggle between the destination version per connection? https://cloud.airbyte.com/workspaces/7ee09b4e-dc84-41c1-b8e9-7c415a13f952/

**Comment by gisripa** [comment]
@svickers  Currently not doable at connection level, the version pin will apply to the whole workspace. I'm coming up better option, to have a toggle in connection configuration so you can opt-in like how you already have `Snowflake (Destination V2)` with a new destination configured. I'll keep you posted after release.

**Comment by gisripa** [comment]
@svickers version 3.11.9 should have an option flag to opt-in using MERGE (you should get in on cloud automatically once the connector is published)

**Comment by svickers** [comment]
@gisripa Any idea when this will be available in cloud?

**Comment by svickers** [comment]
@johnny-schmidt Not seeing that option and the connector version is still showing as 3.9.0, even when trying to add a brand new snowflake destination.

**Comment by evantahler** [comment]
Ah! Apologies - your Airbyte cloud workspace had a pin that was holding you back to version 3.9.0 of destination-snowflake.  I'm removed it, and you now have the latest version of the connector.

**Comment by svickers** [comment]
@evantahler  Ahhh can you please change it back?! All of our syncs have failed since you have made this change!! Please please pleas!

**Comment by tybernstein** [comment]
Hey @svickers, I pinned your existing Snowflake Connector back to version 3.9.0. You can cancel are currently running syncs and the following sync will run on version 3.9.0

**Comment by stephane-airbyte** [comment]
Please file a ticket so we can investigate why the sync failed
