### ISSUE TITLE
Figure out how to handle database migrations in upgrade process

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4306]
## Tell us about the problem you're trying to solve
* For Airbyte Cloud (and some users already) we will have too much data in the database for us to import / export every time we want upgrade.
* Since we moved to having "auto upgrades", it means that we need discrete database migrations anytime we change the database schema. We used to be able to avoid that because the database was always starting fresh each time. We need to figure out how those migrations will be applied in the upgrade process (and potentially how they will be applied in the CI/CD for Airbyte Cloud)

## Describe the solution you’d like
* Whatever solution we come up with is not allowed to start / stop core docker containers. e.g. we cannot stop and start the airbyte-db container.

**Comment by tuliren** [comment]
Features to implement:
- Run the migration in place incrementally, instead of full refresh.
- Be able to change both the configs and the config database schema (#4289).
- [Maybe] Track migration info in the database.
- [Maybe] Detach migration from Airbyte version.
