### ISSUE TITLE
Add feedback for update buttons

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#431]
It isn't clear if you click Sync Now, or update the info for a source or destination that your request is actually being processed (or that it succeeds for the source/destination updates).

**Comment by cgardens** [comment]
@johnlafleur - can you weigh in on this. Maybe you and @jrhizor  can come up with a suggestion?

**Comment by jrhizor** [comment]
Maybe it can show an updating circle on or next to it before switching to a check mark that goes away when new data is entered into the form?

`[ button ]` --click--> `[ button spinner ]` --wait for success--> `[ button ✓ ]`

**Comment by cgardens** [comment]
@johnlafleur did you want to do some designs for general button responsiveness per the discussion last week?

**Comment by johnlafleur** [comment]
Here's a suggestion of a design for all buttons: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=16493%3A0

**Comment by michel-tricot** [comment]
wouldn't we be half way there by just changing the color on push and setting it back to what it was on release?

**Comment by johnlafleur** [comment]
Half way indeed. I think it would be best to have one good behavior that we will apply to all buttons. But it can wait post-launch and we can do your suggestion @michel-tricot in the meantime.

**Comment by cgardens** [comment]
@Jamakase for now let's do what michel suggested

> wouldn't we be half way there by just changing the color on push and setting it back to what it was on release?
