### ISSUE TITLE
track environments for deployments

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4311]
We'd like to understand how Airbyte is used so we can focus improvements/testing on our most used platforms.

There are a few places people deploy Airbyte:
* gcp vm / aws vm / azure vm
* gke / eks / aks / digitalocean kube / minikube / docker for desktop / kind
* local laptops Win/Mac/Linux

It would be nice to guess at which setting these are in. Some we might be able to infer from specific ENV variables being present, others from the local IP, others from the kube version, etc.

**Comment by marcosmarxm** [comment]
@nataliekwong fyi

**Comment by nataliekwong** [comment]
This is great! We can use this to tailor our messaging to users who have yet to deploy to cloud.

**Comment by cgardens** [comment]
part of this is done. we now know if the deployment is cloud or OSS and we know if it's docker or GKE. this issue is calling for more granularity than that though, so i am going to unassign it from myself for now and leave it open as i am not going to get to that level of granularity now.
