### ISSUE TITLE
Feature: To update state of a connection through API

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#4319]
## Tell us about the problem you're trying to solve
We have created a small CLI tool `airbyte-compose`

Uses
1. Multiple airbyte containers
2. It can take an input sources, destinations, connections and create these if not created.
3. Also has commands to create, delete source, connection and destination

We are using this to create all backup everyday so we are saving respective state also. And in case if everything is gone we would like to use this to create all connections on the fly and update the state for the same.

## Are you willing to submit a PR?
I would be happy to pick. I need some guidelines on where to start

**Comment by marcosmarxm** [comment]
oh! @harshithmullapudi can we schedule a call to you show us this? This would be something amazing to us

**Comment by harshithmullapudi** [comment]
Sure @marcosmarxm it's very initial but helps us a log. https://github.com/harshithmullapudi/airbyte-cli 
![Screenshot from 2021-07-03 12-11-48](https://user-images.githubusercontent.com/17528887/124345684-04924800-dbf8-11eb-9aaa-61a8572a0b8b.png)
![Screenshot from 2021-07-03 12-10-36](https://user-images.githubusercontent.com/17528887/124345687-0825cf00-dbf8-11eb-998a-5056bbd1b58e.png)
![Screenshot from 2021-07-03 12-10-19](https://user-images.githubusercontent.com/17528887/124345690-0a882900-dbf8-11eb-9c3c-407fd7366513.png)
![Screenshot from 2021-07-03 12-10-00](https://user-images.githubusercontent.com/17528887/124345692-0cea8300-dbf8-11eb-973d-0334f5aa3c1e.png)
![Screenshot from 2021-07-03 12-09-29](https://user-images.githubusercontent.com/17528887/124345693-0f4cdd00-dbf8-11eb-9c12-c763adc566e7.png)

**Comment by evantahler** [comment]
Closing this issue now that we have the Octavia CLI
