### ISSUE TITLE
Source MySQL: Support connecting via SSH tunnel

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4320]
## Describe the alternative you’ve considered or used
Expose my database to the public internet or run Airbyte in a VPN

## Additional context

**Comment by TMFRook** [comment]
Does this mean that these fields in the MySQL connector setup page don't actually do anything?

![image](https://user-images.githubusercontent.com/68116003/150598938-503170a8-91ec-4ff2-9b16-f2eeca114b82.png)

**Comment by sherifnada** [comment]
nope just means this issue is a duplicate :) closing
