### ISSUE TITLE
mySQL -> Snowflake Ingestion gets stuck in between mySQL to Snowflake transition

### ISSUE THREAD

**Issue by tylerdelange** [airbytehq/airbyte#4322]
## Current Behavior
Usually, but not always, after the mySQL connection closes, the connection run just completely stalls in "Running" status. I have had a running connection now for several hours and it is not moving to the following step (either transferring to Debezium or Snowflake connector).  It occurs to be happening primarily with larger tables. 50M + records.

I am do a mySQL (CDC) to Snowflake (using S3 staging) connection.

Also, I tried both resetting the connection and completely deleting the connection and re-creating it. The same problems occured.

## Logs

Server Logs
[ServerLogs.txt](https://github.com/airbytehq/airbyte/files/6711709/ServerLogs.txt)

mySQL Logs (--tail)
2021-06-24 17:51:26 INFO i.a.i.s.j.AbstractJdbcSource(lambda$read$4):193 - {} - Closing database connection pool.
2021-06-24 17:51:26 INFO i.a.i.s.j.AbstractJdbcSource(lambda$read$4):195 - {} - Closed database connection pool.
2021-06-24 17:51:26 INFO i.a.i.b.IntegrationRunner(run):118 - {} - Completed integration: io.airbyte.integrations.source.mysql.MySqlSource
2021-06-24 17:51:26 INFO i.a.i.s.m.MySqlSource(main):314 - {} - completed source: class io.airbyte.integrations.source.mysql.MySqlSource

Snowflake Logs
[snowflakeLogs.txt](https://github.com/airbytehq/airbyte/files/6712034/snowflakeLogs.txt)

## Steps to Reproduce
1. Create a mySQL source with CDC
2. Create Snowflake with S3 staging destination
3. Attempt ingestion of larger table (50 - 100M records)

## Severity of the bug for you
Very High

## Connector Version (if applicable)
airbyte 0.26.2-alpha
mySQL 0.3.8
snowflake 0.3.9

## Additional context
Running the container on an extremely large "m5.16xlarge" instance with 1 TB of storage.

**Comment by danieldiamond** [comment]
might be related https://github.com/airbytehq/airbyte/issues/5277

**Comment by grishick** [comment]
@danieldiamond we have upgraded Debezium version in MySQL and made many improvements to MySQL Source connector. Do you still see this problem with the latest version of MySQL Source Connector?

**Comment by grishick** [comment]
Closing the issue as unreproducible
