### ISSUE TITLE
[abctl] Deployment is not ready: airbyte-abctl/airbyte-abctl-connector-builder-server

### ISSUE THREAD

**Issue by cevangelo** [airbytehq/airbyte#43299]
### What happened?

Tried to install Airbyte locally with abctl tool but no luck.
Everythinh goes as planned until i start to get the message "Deployment is not ready: airbyte-abctl/airbyte-abctl-connector-builder-server" for several minutes which after 15 minutes leeds to a timeout.

### What did you expect to happen?

I suppose after this the airbyte platoform would be successfully deployed locally.

### Abctl Version

<details>

```console
$ abctl version
(version: v0.11.1)
```

</details>

### Docker Version

<details>

```console
$ docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:14 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:14 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

</details>

**Comment by dotsoftsa** [comment]
@marcosmarxm Hello there, would you need any more info for this? Is there a way to send you a more detailed report using abctl?

**Comment by cevangelo** [comment]
The problem was solved by using a faster internet connection with the same VM instance. It seems that the download of the assets was taking a lot longer than expected thus the timeout.
