### ISSUE TITLE
list of destinations should still be accessible after modifying the destination

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#433]
This is buggy if not an actual bug. 

Right now, if you go to the list of destinations, select your destination, and edit it, you can never return to the list of destinations. This feels odd from the user's perspective.

**Comment by cgardens** [comment]
@johnlafleur - do you want to weigh in on this? 

I am fairly ambivalent on this one. You can always see our destinations in our docs, but I can definitely see the argument for having this in the UI too. I'm sort of inclined to not worry about this one until we start having multiple destinations you can sync to at once in the UI, but I don't feel too strongly.

If we think this is something we want to do for soon then we should mock something up.

**Comment by cgardens** [comment]
i think this is all done with the admin view.
