### ISSUE TITLE
[source-hubspot] Infinite loop for crm search results

### ISSUE THREAD

**Issue by ehearty** [airbytehq/airbyte#43317]
### Connector Name

source-hubspot

### Connector Version

 4.2.14

### What step the error happened?

During the sync

### Relevant information

Search result sets > 10k create in an endless loop if the CRM contains > 10k records with the same last modified time. https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1214 

HubSpot recently began running a "Batch Update" process at the end of the month (to reset marketing status, etc) which sets all affected records to the exact same timestamp. See example below:

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/fa581539-e4d0-4323-b6b8-bbc33f0eae0b">

Since HubSpot won't let you pull more than 10k search results at a time, the connector grabs the last updated time of the last 10k received and uses that timestamp as a starting point to pull the next 10k. For example, if the first query was "get all contacts updated after 12AM on 08/01/2024," then we'd grab the first 10k records that match that criteria and then use the highest timestamp in that response (let's say it's 3PM on 08/01/2024) to run a subsequent request using the query "get all contacts updated after 3PM on 08/01/2024."

When all of the returned records in the result set have the same last modified date, however, it will keep rerunning the same query. 

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@airbytehq/dev-python can someone take a look into this issue as it looks Hubspot had made a change in their API?

**Comment by girarda** [comment]
@aldogonzalez8 can you take a look?

**Comment by aldogonzalez8** [comment]
@marcosmarxm is this affecting all the streams for hubspot? Is there any connection I can take a look?

**Comment by aldogonzalez8** [comment]
Ok, the code that @girarda pointed is for CRMSearchStream so probably this is a problem for all these streams
![image](https://github.com/user-attachments/assets/80cb8786-19dc-4238-aeaf-accac766a867)

**Comment by aldogonzalez8** [comment]
@marcosmarxm any update on a connector id with this problem?

**Comment by marcosmarxm** [comment]
> @marcosmarxm is this affecting all the streams for hubspot? Is there any connection I can take a look?

I don't know. @ehearty do you more information about the issue?
I'll keep it open to get more insights from the community.

**Comment by jtruty** [comment]
@ehearty I don't see this in my Hubspot account - is this a bulk action that is limited to your account? Is this on all objects or only specific ones? In any case, I see how this is an issue if this type of bulk action occurs. Also, we can *only* sort on a single field: https://developers.hubspot.com/docs/api/crm/search#:~:text=Only%20one%20sorting%20rule%20can%20be%20applied%20to%20any%20search so when this happens we cannot use last modified date to sort/filter results. Maybe a sort by `hs_object_id`, with a `last_modified_date` filter for paging would work better.

**Comment by aldogonzalez8** [comment]
> Ok, the code that @girarda pointed is for CRMSearchStream so probably this is a problem for all these streams ![image](https://private-user-images.githubusercontent.com/168454423/355935288-d5e1a518-67cc-4ca1-a610-41898b718e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQ2NDAsIm5iZiI6MTcyMzEzNDM0MCwicGF0aCI6Ii8xNjg0NTQ0MjMvMzU1OTM1Mjg4LWQ1ZTFhNTE4LTY3Y2MtNGNhMS1hNjEwLTQxODk4YjcxOGU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNjI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTMwZTVjMTQzOWM2ZDAyZWQ4NWNiNmI4MjFjMWJmNzhmYmViMGJiMzEzZjliNzNlMmE2NjBlMTVjYjk1ZjllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WWk2AHuA5kE-OHJjfTL5Vx6sr5chnNSapkMvA-SR0OA)
> 
> update: correct streams in image

*potential problem

**Comment by aldogonzalez8** [comment]
@ehearty Would be useful if Update the connector to only pull 10k records and ignore the 400 error in the scenario you described?

**Comment by aldogonzalez8** [comment]
> @ehearty Would be useful if we update the connector to only pull 10k records and ignore the 400 error in the scenario you described?

Hey @ehearty, any thoughts on this?

**Comment by ehearty** [comment]
@aldogonzalez8 @marcosmarxm @jtruty @girarda I apologize for the late response, been busy with other issues at work.

Gonna try to address all the questions I received: 
 - I don't believe the bulk update is something special or limited to our hubspot account, but it's possible (and likely) that we're disabling marketing status for a *higher volume* of contacts in hubspot each month than is typical for other clients - so we might be the only user exceeding that 10k limit for this process at this time
 - I'm aware that we can only sort on a single field in HS, and to get around this limitation, I updated our custom HS connector to filter on *both* HS object id AND timestamp, then to sort by HS object id. So the timestamps return out of order, but once we finish iterating through all the results we should have all the data (much like the full refresh where we also don't sort with the timestamp). In order to accomplish this, I had to disable updating the state after each iteration, but it's been working perfectly for us for the last month or so. 
 - I actually started on a PR to incorporate this fix into the official connector, but will need to update the unit and integration tests before I can submit. If you want to take a look at the changes so far (and they're pretty minor), here's a link: https://github.com/airbytehq/airbyte/compare/master...ehearty:airbyte:ehearty/source-hubspot-search-stream-fix

**Comment by jtruty** [comment]
@ehearty looks great - this should address for all search streams.

**Comment by ehearty** [comment]
> @ehearty looks great - this should address for all search streams.

Thanks for taking a look! Now I just need to figure out why such a presumably small change has broken so many unit tests... I'll try to find some time in the next couple of weeks to finally submit that PR.

**Comment by ehearty** [comment]
###Update 

My submitted PR is here: https://github.com/airbytehq/airbyte/pull/44899

If anyone knows what the `Check if a review is required from Connector teams on fork` is or why it's failing, please shoot me a message.

**Comment by aldogonzalez8** [comment]
> @aldogonzalez8 @marcosmarxm @jtruty @girarda I apologize for the late response, been busy with other issues at work.
> 
> Gonna try to address all the questions I received:
> 
> * I don't believe the bulk update is something special or limited to our hubspot account, but it's possible (and likely) that we're disabling marketing status for a _higher volume_ of contacts in hubspot each month than is typical for other clients - so we might be the only user exceeding that 10k limit for this process at this time
> * I'm aware that we can only sort on a single field in HS, and to get around this limitation, I updated our custom HS connector to filter on _both_ HS object id AND timestamp, then to sort by HS object id. So the timestamps return out of order, but once we finish iterating through all the results we should have all the data (much like the full refresh where we also don't sort with the timestamp). In order to accomplish this, I had to disable updating the state after each iteration, but it's been working perfectly for us for the last month or so.
> * I actually started on a PR to incorporate this fix into the official connector, but will need to update the unit and integration tests before I can submit. If you want to take a look at the changes so far (and they're pretty minor), here's a link: [master...ehearty:airbyte:ehearty/source-hubspot-search-stream-fix](https://github.com/airbytehq/airbyte/compare/master...ehearty:airbyte:ehearty/source-hubspot-search-stream-fix)

@marcosmarxm @jtruty @girarda  I will try to summarize @ehearty changes as they make sense in my head, but I want to put it out if anyone has concerns:

Before:

1. Request data to HS on the search endpoint 
   - filter on the latest state (timestamp).
   - ordered. by timestamp
2. We use the token returned in response to paginate.
3. If the token is none, pagination is over
4. If pagination >10000 records, we start a new request as we can't get further because HS doesn't want that.
5. New request will use the latest/greatest timestamp
6. if all data has identical timestamps because some batch update occurred, a new request would try to use the same initial timestamp, and we get the infinite loop.

After:

1. Request data on HS in the search endpoint:
   - filter on the latest state (timestamp)
   - Filter on latest object id/primary_key with initial None
   - Filter on timestamp < current_sync to not have "open-ended queries"
2. We use the token returned in response to paginate.
3. If the token is none, pagination is over
4. If pagination > 1000 records, we start a new request because we can't go further, as HS doesn't want that.
5. New requests will filter like:
   - **Filter still on the latest state before sync started**
   - Use the latest object ID/primary_key obtained from the previous pagination process (technically, it's the same loop, so pagination is not over, but we restart because of the 10,000 limit and that stuff.).
   - Again, Filter on timestamp < current_sync to not have "open-ended queries"
6. if all data has identical timestamps because some batch update occurred, this will not affect the pagination process as we also filtered and now instead sorted by object ID rather than timestamp.
9. We are happy because it is not an infinite loop.

**Comment by aldogonzalez8** [comment]
@ehearty closing this, thanks for the help!
