### ISSUE TITLE
Error invoking scheduled task for bean [io.airbyte.cron.jobs.DeclarativeSourcesUpdater] Network is unreachable java.net.SocketException: Network is unreachable

### ISSUE THREAD

**Issue by sachin261997** [airbytehq/airbyte#43351]
### Platform Version

0.63.13

### What step the error happened?

On deploy

### Relevant information

I have deployed airbyte through docker but getting below error in starting airbyte-cron container:
ERROR i.m.s.DefaultTaskExceptionHandler(handle):47 - Error invoking scheduled task for bean [io.airbyte.cron.jobs.DeclarativeSourcesUpdater] Network is unreachable
java.net.SocketException: Network is unreachable

### Relevant log output

```shell
2024-08-07 07:30:32 ERROR i.m.s.DefaultTaskExceptionHandler(handle):47 - Error invoking scheduled task for bean [io.airbyte.cron.jobs.DeclarativeSourcesUpdater] Network is unreachable
java.net.SocketException: Network is unreachable
```

**Comment by marcosmarxm** [comment]
@sachin261997 Docker support is deprecated. Please upgrade to use `abctl`.
