### ISSUE TITLE
🐛 [source-hubspot] Engagements associations not retrieved in Incremental sync

### ISSUE THREAD

**Issue by kev-datams** [airbytehq/airbyte#43352]
### Connector Name

source-hubspot

### Connector Version

4.2.14

### What step the error happened?

During the sync

### Relevant information

Hello 👋 

We are currently using Hubspot source connector `v4.2.14` to retrieve distinct `Engagements` via their respective streams (ie `Engagements calls`, `Engagements emails`, etc) in `Incremental` to GCS:

<img width="1244" alt="Capture d’écran 2024-08-07 à 10 44 15" src="https://github.com/user-attachments/assets/a70b34da-370e-4ca3-958c-994dd07f738a">

---
We launched 2 sync:
1. First incremental sync, starting from `2024-08-01T00:00:00Z`, with empty connector `state` => very long to run: >10 hours
2. Second incremental sync, forcing the connector `state` to start from `2024-08-01T00:00:00Z` for each stream (
[cf connection-state.json](https://github.com/user-attachments/files/16520949/connection-state.json)) in order to extract and compare same data scopes => quite fast to run: 15 min

<img width="1086" alt="Capture d’écran 2024-08-07 à 11 31 23" src="https://github.com/user-attachments/assets/816d1a7c-f817-4f5c-bc6e-1739115c85fe">

---
We observed below results in output (read via BigQuery external table over the AVRO GCS files):
<img width="1119" alt="Capture d’écran 2024-08-07 à 10 54 28" src="https://github.com/user-attachments/assets/25290645-13e8-490d-ab59-fdf569f91819">

---
**⚠️ Issues identified**:
1. the `Companies` field is properly retrieved for the First incremental sync (row 1) BUT **wrongly empty** for the Second incremental sync (row 2)
2. above issue is the same:
- for `Contacts` and `Deals` associations also
- over **all** `Engagements` objects types (calls, meetings, notes, emails, tasks)
3. I also noticed in the stream logs a `schema validation error` specific to the `contacts` (eg: ```Schema validation errors found for stream _engagements_meetings. Error messages: [$.contacts[2]: integer found, [null, string] expected, $.contacts[1]: integer found, [null, string] expected, $.contacts[0]: integer found, [null, string] expected]```)
 
**Complementary question**: why is first sync so long ?

---
**Hypothesis**: there is a difference [if state is set or not](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1184) at associations reading time, leading to using `_read_associations` VS `_flat_associations` methods (as `EngagementsXxx` inherits from `CRMSearchStream`)

NB: [according to the doc](https://docs.airbyte.com/integrations/sources/hubspot#notes-on-the-engagements-stream), the `EngagementsAll` and `EngagementsRecent` Python classes are not used for the specific engagements streams.

Thank you for your help 🙏 

### Relevant log output

Full Airbyte logs to debug the 3 issues:
- [first incremental sync](https://github.com/user-attachments/files/16520977/default_workspace_logs_239_txt.txt)
- [second incremental sync](https://github.com/user-attachments/files/16520978/default_workspace_logs_242_txt.txt)

### Contribute

- [x] Yes, I want to contribute

**Comment by kev-datams** [comment]
Hi @bazarnov, @brianjlai, @davydov-d, @augan-rymkhan, it seems you hardly contributed to this connector
Please do you have any idea how to solve it ?
Thanks a lot 🔥

**Comment by kev-datams** [comment]
I tried to debug the case but did not succeed to properly launch an incremental sync in local, if you have any suggestion...

Command used:
`poetry run source-hubspot read --config secrets/config.json --catalog my-catalog.json --state my-state.json`

my-catalog.json:
```
{
  "streams": [
    {
      "stream": {
        "name": "engagements_notes",
        "json_schema": {},
        "supported_sync_modes": ["full_refresh", "incremental"],
        "source_defined_cursor": true,
        "default_cursor_field": ["updatedAt"]
      },
      "sync_mode": "incremental",
      "cursor_field": ["updatedAt"],
      "destination_sync_mode": "append"
    }
  ]
}
```

my-state.json
```
[
  {
    "stream": {
      "stream_descriptor": {
        "name": "engagements_notes"
      },
      "stream_state": {
        "updatedAt": "2024-08-01T00:00:00Z"
      }
    }
  }
]
```

**Comment by kev-datams** [comment]
I observed that the engagements_notes.json schema contains:
```
"companies": {
      "description": "Companies associated with the engagement note",
      "type": ["null", "array"],
      "items": {
        "type": ["null", "string"]
      }
    }
```
=> companies field is an array of strings

But this [portion of code](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py#L1167) generates list of integers.

What do you think about adding a `str()` in order to have:
`associations_list.extend(str(association["toObjectId"]) for association in group["to"])`

**Comment by kev-datams** [comment]
Proposed PR : https://github.com/airbytehq/airbyte/pull/43381

NB: it will not solve the third point: `I also noticed in the stream logs a schema validation error specific to the contacts (eg: Schema validation errors found for stream _engagements_meetings. Error messages: [$.contacts[2]: integer found, [null, string] expected, $.contacts[1]: integer found, [null, string] expected, $.contacts[0]: integer found, [null, string] expected])`
=> perhaps adding a `str()` somewhere ? 🤔

**Comment by marcosmarxm** [comment]
cc @airbytehq/dev-python can someone take a look into this issue?

**Comment by kev-datams** [comment]
Hi @marcosmarxm, do you know who is in charge of checking the "third point" ? (for other ones, my PR looks good 🙏 )
