### ISSUE TITLE
[Broken] Metric helm chart is broken

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#43379]
### Helm Chart Version

latest

### What step the error happened?

None

### Relevant information

deployment failed with yaml to json conversion at line 25. it seems, imagepullsecrets having issue with indentation.

**Comment by marcosmarxm** [comment]
Sorry @sivankumar86 closing the issue as you're not providing the version. Please open an issue and provide all information to be able to reproduce the problem.
