### ISSUE TITLE
Jira Connector declares "created" cursor field but does not include it in its catalog

### ISSUE THREAD

**Issue by Amitmak** [airbytehq/airbyte#4341]
#### users (Mode:  Full refresh - Overwrite) 
But while synching connector we are getting error "Caused by: io.airbyte.workers.WorkerException: Normalization Failed".
Attached complete logs for reference. 

#### Can someone help me to resolve this issue ?
[logs-232-2.txt](https://github.com/airbytehq/airbyte/files/6714758/logs-232-2.txt)

**Comment by marcosmarxm** [comment]
Thanks for opening this @Amitmak I addressed this to the connector team take a look.

**Comment by ChristopheDuong** [comment]
This seems to be because the Jira source is defining cursor fields "created" but does not declare it in its catalog...

Related to https://github.com/airbytehq/airbyte/issues/3752

**Comment by sherifnada** [comment]
this is a WIP in our upcoming sprint

**Comment by vovavovavovavova** [comment]
ok about this issue we have the following:
The `issues` stream declared both in schemas and configured_catalog (if used) do have the following fields `['expand', 'id', 'self', 'key', 'renderedFields', 'properties', 'names', 'schema', 'transitions', 'operations', 'editmeta', 'changelog', 'versionedRepresentations', 'fieldsToInclude', 'fields']` and does not have the required cursor_field `created`, also some fields here without data-type. So first of all this will be checked and fixed.
