### ISSUE TITLE
[abctl] Missing exposing API port 8001?

### ISSUE THREAD

**Issue by baugarcia** [airbytehq/airbyte#43423]
### What happened?

We just did an airbyte install using abctl. Everything seems to be working fine, the cluster is created and no errors are reported.

We hava Airflow triggering the sync jobs on Airbyte, which used to work fine on the docker-compose version we had. But on this new version (0.63.14 with abctl install), we get a connection refused when triggering the job through the API.

There is no reason for a connection refused networking-wise. We have already checked connectivity and the webpage is accesible, so this is only related to the API port:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.126.1.11', port=8001): Max retries exceeded with url: /api/v1/connections/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05dcef6f50>: Failed to establish a new connection: [Errno 111] Connection refused'))


[2024-08-09, 11:46:38 UTC] {{standard_task_runner.py:107}} ERROR - Failed to execute job 52888 for task REDACTED(HTTPConnectionPool(host='REDACTED', port=8001): Max retries exceeded with url: /api/v1/connections/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f05dcef6f50>: Failed to establish a new connection: [Errno 111] Connection refused')); 28600)
```

### What did you expect to happen?

abctl installation to leave any needed port available. Looks like it is mising a port forward or opening the API port

### Abctl Version

<details>

```console
$ abctl version
version: v0.11.1
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.20.12
 Git commit:        4debf41
 Built:             Mon Feb 12 00:00:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.20.12
  Git commit:       f417435
  Built:            Mon Feb 12 00:00:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.11
  GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba
 runc:
  Version:          1.1.11
  GitCommit:        4bccb38cc9cf198d52bebf2b3a90cd14e7af8c06
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.3.20240312"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
```

</details>

**Comment by szemek** [comment]
@baugarcia there were some changes recently
https://reference.airbyte.com/reference/standalone-server-deprecation-and-migration-to-airbyte-server
> This change has gone live as of v0.63.9. If you upgrade to or past that version the standalone airbyte-api-server will no longer be in use and you'll have to follow the migration steps below.

> OSS users using the airbyte-api-server need to migrate their API calls to reference the airbyte_server. If you were using the Airbyte API, you will have to update callers to point to airbyte-server/api/public as the base URL. Anything already pointing to the airbyte-server needs no change.

> For example, an API call localhost:8006/v1/workspaces must be migrated to: localhost:8001/api/public/v1/workspaces

`abctl` uses port 8000 by default. Also, without any extra ingress/reverse proxy API endpoints require `/api/public` prefix.
It's high chance that Airflow operator for Airbyte doesn't reflect those changes, so I think it would be good to create an issue in Airflow repository https://github.com/apache/airflow/issues

**Comment by baugarcia** [comment]
Yes, I will create an issue in their repository so that they can change it on their and or offer a workaround

Thank you for your help and support!
