### ISSUE TITLE
Track StandardSyncSummary with breakdown and more granular steps

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4342]
## Tell us about the problem you're trying to solve
StandardSyncSummary is currently tracking sync durations/throughput during "replication" (read source/write destination)

## Describe the solution you’d like
We should also have a breakdown of runtime and possibly throughput (amount of data manipulated) by each operations other than source/destination connectors (such as normalization or custom operations).

Status of each steps could also help to differentiate replication failures vs normalization failures

StandardSyncSummary should also “grep” for exceptions and include breakdown between 
- source exit code & exceptions
- destination exit code & exceptions
- normalization exit code & exceptions

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by cgardens** [comment]
@ChristopheDuong does what's defined in the spec mentioned in [this issue](https://github.com/airbytehq/airbyte/issues/2591) address what you are getting at here? if so let's close this one as duplicate?
