### ISSUE TITLE
[platform] Workload launcher has duplicate entries in container envs

### ISSUE THREAD

**Issue by film42** [airbytehq/airbyte#43432]
### Helm Chart Version

0.414.0

### What step the error happened?

Upgrading the Platform or Helm Chart

### Relevant information

Only thing I changed was the helm chart version. I was previously on 0.242.2 . In airbyte versions I was upgrading from 0.63.3 to 0.63.14.

The errors is:
```
      .spec.template.spec.containers[name="airbyte-workload-launcher-container"].env: duplicate entries for key [name="JOB_MAIN_CONTAINER_CPU_REQUEST"]
      .spec.template.spec.containers[name="airbyte-workload-launcher-container"].env: duplicate entries for key [name="JOB_MAIN_CONTAINER_CPU_LIMIT"]
      .spec.template.spec.containers[name="airbyte-workload-launcher-container"].env: duplicate entries for key [name="JOB_MAIN_CONTAINER_MEMORY_REQUEST"]
      .spec.template.spec.containers[name="airbyte-workload-launcher-container"].env: duplicate entries for key [name="JOB_MAIN_CONTAINER_MEMORY_LIMIT"]
```

Duplicates without conditionals defined here: https://github.com/airbytehq/airbyte-platform/blob/v0.63.14/charts/airbyte-workload-launcher/templates/deployment.yaml#L229-L323

Looks like this error happened because of the switch from airbyte server to the workload launcher and new api service.

I asked in slack but didn't get any feedback. Figured I'd open a ticket: https://airbytehq.slack.com/archives/C021JANJ6TY/p1723157877530959

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @film42. Is this only a warning message or stopping the server pod to start?
cc @airbytehq/platform-move

**Comment by film42** [comment]
It fails to apply the change to the kube api.

**Comment by davinchia** [comment]
Hi, we've removed the duplicate env vars as of 0.429.0. I tested and this should be working fine now. Let me know if you have any more questions!

**Comment by film42** [comment]
Works for me! Thanks!
