### ISSUE TITLE
Improve variable parsing in dbt custom run

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4348]
## Tell us about the problem you're trying to solve
We need to handle better how parse variables when running dbt custom commands
[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624557207430200)

## Describe the solution you’d like
Improve the `entrypoint.sh` when running custom dbt

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

**Comment by vsayer** [comment]
I also had to follow https://github.com/dbt-labs/dbt-codegen/issues/37#issuecomment-858864486 to get variable parsing working.

Basically enclosing the whole body in double-quotes and enclosing each key and value with single-quotes.

**Comment by yuhuishi-convect** [comment]
Bumped into this problem today as well.
Might need a better example on this page: https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-airbyte#using-a-custom-run-with-variables

**Comment by cgardens** [comment]
not going to work on this one anytime soon.
