### ISSUE TITLE
Add license check into CI

### ISSUE THREAD

**Issue by jamakase** [airbytehq/airbyte#4349]
## Tell us about the problem you're trying to solve
Currently, we do not check via CI if we violate the license clauses of libraries we include.

We should check libs for:
- python
- java
- typescript

## Describe the alternative you’ve considered or used
I have used https://fossa.com/ in a few projects, but we can use any of them. Probably

**Comment by cgardens** [comment]
@timroes is this something we still want to do? or should we close?

**Comment by timroes** [comment]
Since we have a license check for the webapp. And we currently don't have any further plans for introducing this to the backend code (also the inclusion of backend dependencies is usually way more contained than our npm dependencies) I'll close this for now.
