### ISSUE TITLE
Documentation: add steps to customize Airbyte normalization with custom dbt run

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4351]
### Tell us about the documentation you'd like us to add or update.
https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-dbt
https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-airbyte

shows people how to do, but we need a small list showing the steps to do that. (from [Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624641386019700?thread_ts=1624558824.435500&cid=C01MFR03D5W):
- Enable airbyte’s normalization for connection and run first sync.
- Find generated dbt project folder in running container
- Export project to separate repository
- Tweak parameters for project
- Disable airbyte’s normalization and enable custom normalization using new repo

My suggestion is adding this list of steps in this section:
https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-airbyte#transformations-with-airbyte

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by arimbr** [comment]
Hi @marcosmarxm ! I believe that what you listed has been done by @tuanchris on [this upcoming recipe](https://docs.google.com/document/d/1HFdKro6qgN-k2_t_gJzWdUsWl4ZVP1z-Fl8VX66uOw8/edit#) on this other issue https://github.com/airbytehq/write-for-the-community/issues/53. After publishing the recipe on our blog should we include some of this content in the doc also or link to the recipe from the docs?

**Comment by cgardens** [comment]
Closed as won't do because we have [deprecated the custom dbt transformation feature](https://github.com/airbytehq/airbyte/discussions/34860).
