### ISSUE TITLE
Validate that input config matches spec inside all java connectors by default

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4352]
## Tell us about the problem you're trying to solve
Today if the input config in a connector does not match the connector's `spec.json` then the connector will not validate it. 

## Describe the solution you’d like
Modify the `Destination` and `Source` java abstractions to automatically validate that the input config to `discover`, `read`, `check`, and `write` matches the connector's spec. This way the child class does not need to do anything about validation -- it is automatically handled for it. 

## Describe the alternative you’ve considered or used
Test for this in acceptance tests, which is complementary to this issue. 

## Additional context

**Comment by etsybaev** [comment]
Hi @sherifnada.
Could you please a bit clarify the acceptance criteria for this task?  As far as I know, we have a spec.json for each connector. We read it and then UI form is built based on that spec.  We also have some checks using browser's features (like all mandatory fields are set and son) and once the form is submitted we call the "check" method to verify that all values are correct and we may connect to the source.  And if it's ok - then we move forward with "discover", "read" and "write" tasks.  So it's not very clear what exactly is expected from this task. Many thanks in advance!

**Comment by sherifnada** [comment]
@etsybaev today if we run a connector like `docker run XYZ read --config /path/file.json` and the `--config` does not conform to the `spec.json` then we don't do an explicit validation in the connector, which means it may run on an incorrect config. 

The acceptance criteria for this task is that all java connectors should validate the input `config.json` independent of whether the UI or any other entity has validated it on their behalf. Does that help clarify?

**Comment by etsybaev** [comment]
A follow-up ticket has been created for bumping up versions and releasing all the java-based connectors
https://github.com/airbytehq/airbyte/issues/4748
