### ISSUE TITLE
Shopify Source Indicates Upgrade Available, No version to upgrade to

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#4356]
## Expected Behavior
Shopify connector marked for upgrade should have upgrade path

## Current Behavior
No version appears in the source "Change To" column, attempting to upgrade results in "Sorry something went wrong"

## Logs
Not sure where these would be located, but happy to provide if you can point me there

## Steps to Reproduce
1. Notice admin tile has red dot indicating an upgrade to a connector is available, get excited  
2. Go to Admin > Sources
3. See that it's just the "broken" Shopify connector that cannot be upgraded beyond 0.2.2

## Severity of the bug for you
Very Low

## Airbyte Version
0.26.2-alpha

## Connector Version (if applicable)
0.2.2

## Additional context
N/A

**Comment by marcosmarxm** [comment]
This problem is more a front-end problem with the server API.
