### ISSUE TITLE
Bigquery destination SCD table does not work with array type from source Postgres table

### ISSUE THREAD

**Issue by shreyaspurohit** [airbytehq/airbyte#4357]
## Expected Behavior
The SCD table in BigQuery should have array values from postgres table populated instead of null.

## Current Behavior
The SCD table in BigQuery has null populated for array values. The _airbyte_raw_table has the array values transferred from postgres correctly. But the transformation from _airbyte_raw_table to table_scd populates null in the array field. Thanks to the help from @marcosmarxm on slack, we were able to find the root cause of the issue to be the usage of the [legacy](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#legacy_json_extraction_functions) JSON function - `json_extract_scalar` in the DBT model for the SCD in BigQuery. The `json_query` or `json_query_array` should be used based on if the destination column needs to be `string` or `array` type as per [this](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#standard_json_extraction_functions_recommended) Google docs.

## Logs
1. Postgres tables: [postgres_sql_log.txt](https://github.com/airbytehq/airbyte/files/6718463/postgres_sql_log.txt)
1. _airbyte_raw_table on BigQuery screenshot: <img width="1405" alt="airbyte_raw_array_test_table" src="https://user-images.githubusercontent.com/1802661/123477623-2ade3500-d5b3-11eb-92c7-a886f62aa5e2.png">
1. SCD table on BigQuery screenshot: <img width="1406" alt="array_test_scd_table" src="https://user-images.githubusercontent.com/1802661/123477718-4cd7b780-d5b3-11eb-8025-04566ac5e84b.png">
1. Sync logs: [logs-55-0.txt](https://github.com/airbytehq/airbyte/files/6718483/logs-55-0.txt)
1. DBT generated models: [dbt_array_test_scd_sql.txt](https://github.com/airbytehq/airbyte/files/6718485/dbt_array_test_scd_sql.txt)

## Steps to Reproduce
1. Create a test table in postgres with `create table array_test (id bigserial primary key, values text[] not null, created_at timestamptz not null DEFAULT (NOW() AT TIME ZONE 'utc'));`
1. Insert some data - insert into array_test(values) values('{"a","b","c"}');
1. Configure a CDC from postgres to BigQuery
1. Run the Sync
1. Look at data in SCD tables. The data `{"a", "c", "c"}` is missing. (the data is present in _raw_airbyte_array_test)

## Severity of the bug for you
High

## Airbyte Version
0.25.0-alpha

## Connector Version (if applicable)
Destination (bigquery): 0.3.6
Source (postgres): 0.3.4

## Additional context
n/a

**Comment by ChristopheDuong** [comment]
In the catalog, the field `values` is marked as `"values":{"type":"string"}` but the record is an array of string. 

If it was an array of string, then normalization would try to unnest it, but Postgres CDC is not being consistent here

**Comment by tuliren** [comment]
TODO:
- [ ] #8749 has been merged. Need to publish affected databases to pick up this change.
