### ISSUE TITLE
Data sync results in ~2x local disk write

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4366]
Slack [thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1624530912420100)

## Expected Behavior
- When syncing data from Salesforce to S3 (CSV), users expect that there is no significant amount of local disk write.
- The UI shows the byte size of the data synced to the destination.

## Current Behavior
- When syncing 500MB data, there is a ~2x local disk write.
- The UI seems to show the local disk write (1.18GB).
- We need to figure out:
  - What exactly is written to local disk?
    - `Destination::defaultOutputRecordCollector` prints every record to stdout. If this goes to the logs, it counts as 1x write.
    - From Jared: this is necessary to share the output with the sync worker. But the docker logging is probably capturing that and storing it resulting in more writes.
  - What is the value in the UI?
  - Will the amount of data written to disk to be linear to that being synced to the destination?

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Airbyte Version
Found in the .env file in the root of the project.

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.

## Additional context
*Environment, version, integration...*

**Comment by olivermeyer** [comment]
This issue was spotted with the following versions:
* Airbyte 0.26.2-alpha
* destination-s3 0.1.6

**Comment by davinchia** [comment]
@olivermeyer are you still seeing this?

**Comment by olivermeyer** [comment]
> @olivermeyer are you still seeing this?

Can't say, we stopped using the S3 destination in favour of the Redshift destination.
