### ISSUE TITLE
When I choose a data source and a data destination, why are there no streams to choose from?

### ISSUE THREAD

**Issue by Hanyujun10224803** [airbytehq/airbyte#43722]
### Relevant information

![image](https://github.com/user-attachments/assets/3173b66d-7452-4b01-8683-28e84da40c5c)
Please tell me why, thank you.

**Comment by Hanyujun10224803** [comment]
The provided documents can't be viewed completely in the step of setting connection, and it's impossible for a new user to build a synchronous test case quickly, and the provided cloud environment is not easy to use. I hope it can be improved, thank you.

**Comment by marcosmarxm** [comment]
Closing as this isn't using the right template. @Hanyujun10224803 please open an issue reporting a problem with the connector. Provide as much information you have as today there is only a screenshot which isn't helpful to debug or reproduce the problem. Check the credentials and provide data about the database user you're using have schema permissions etc.
