### ISSUE TITLE
Zendesk not loading username and facebook/twitter id

### ISSUE THREAD

**Issue by coquej** [airbytehq/airbyte#4373]
## Expected Behavior
When using airbyte/source-zendesk-support-singer connector, facebook/twitter id and username from tickets (via field) are not being loaded in the destination, but Zendesk API can give that information.

## Current Behavior
Not loading facebook id, twitter id nor username in tickets table.

## Severity of the bug for you
High

## Connector Version 
airbyte/source-zendesk-support-singer connector 0.2.2

**Comment by sherifnada** [comment]
@coquej this is blocked on #4422 . We'll make sure to fix this issue as a follow up to that one.
