### ISSUE TITLE
Custom images all return 504 when trying to set up local connectors

### ISSUE THREAD

**Issue by dslockhart** [airbytehq/airbyte#43893]
### What happened?

I have moved from using the deprecated `run-ab-platform.sh` script to the abctl homebrew-installed app. I have managed to set it up and test an out-the-box connector but any docker image, which when I try to add a custom connector using a local docker image, I get a 504 message returned. Is there some place I can see further error logs?

### What did you expect to happen?

These images work fine on v0.50.22, both locally and in production. I would like to be able to test them locally using abctl app

### Abctl Version

<details>

```console
$ abctl version
version: v0.11.1
```

</details>

### Docker Version

<details>

```console
$ docker version
 Docker Desktop 4.29.0 (145265)
```

</details>

### OS Version

<details>

```console

# On Mac:
$ uname -a
Darwin GB5ANNM0FH1FQML 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:54:20 PDT 2024; root:xnu-10063.141.1~2/RELEASE_X86_64 x86_64
```

</details>

**Comment by colesnodgrass** [comment]
Currently `abctl` doesn't support an easy way to view logs (there is an ongoing discussion about how best to support this), but as this tool configures [kubernetes in docker](https://kind.sigs.k8s.io/), you can use existing [kubernetes](https://kubernetes.io/docs/tasks/tools/#kubectl) tools to view the logs. 

To view the pods
```
kubectl --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig -n airbyte-abctl get pods
```
and then to view the logs of a specific pod
```
kubectl --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig -n airbyte-abctl logs [POD NAME]
```

**Comment by marcosmarxm** [comment]
@dslockhart you need to load the images to `kind`, please run:
`kind load docker-image airbyte/custom-connector:dev --name airbyte-abctl`

**Comment by dslockhart** [comment]
Thank you @marcosmarxm  this has solved the issue for me \m/ -_- \m/

**Comment by dslockhart** [comment]
Could it have something to do with this log:
`2024-08-15 14:38:17 ERROR i.a.s.a.ApiHelper(execute):49 - Unexpected Exception
java.lang.IllegalStateException: Get Spec job failed.`  ?
Because if I run 
` docker run --rm -i airbyte/source-xxx:latest spec` I get a successful output

**Comment by marcosmarxm** [comment]
I need to run some tests @dslockhart

**Comment by dslockhart** [comment]
please let me know if you need more thorough logs
