### ISSUE TITLE
Import older airbyte export thinks it succeeded when it didn't, fails to show error

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#4393]
## Expected Behavior
I exported from 0.24.2 (demo site) and imported into 0.26 which shouldn't work, and should show an error.

## Current Behavior
The UI acts like the process succeeded (refreshes page, doesn't show an error) even though no connectors are actually brought in and the log shows that the incorrect version was detected.  This results in a confusing UI display that implies it worked when it didn't.

## Logs

Running locally on mac with docker-compose up.

Import failed
airbyte-server      | java.io.IOException: Imported VERSION (0.24.2-alpha) is incompatible with current Airbyte version (0.26.4-alpha).
airbyte-server      | Please upgrade your Airbyte Archive, see more at https://docs.airbyte.io/tutorials/upgrading-airbyte
airbyte-server      | 
airbyte-server      | 	at io.airbyte.server.handlers.ArchiveHandler.checkImport(ArchiveHandler.java:149) ~[io.airbyte-airbyte-server-0.26.4-alpha.jar:?]
airbyte-server      | 	at io.airbyte.server.handlers.ArchiveHandler.importData(ArchiveHandler.java:123) ~[io.airbyte-airbyte-server-0.26.4-alpha.jar:?]

## Steps to Reproduce
1. Import an old-version export into the newer code base.

## Severity of the bug for you
Low

## Airbyte Version
0.26.4-alpha

**Comment by cgardens** [comment]
this version is no longer supported.
