### ISSUE TITLE
Allow setting connection name in the UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4407]
## Tell us about the problem you're trying to solve
* I want to be able to set the name for my connection when I configure it in the UI.

slack convo: https://airbytehq.slack.com/archives/C019WJFR1JT/p1624984188040200

## Describe the solution you’d like
* The API already has support for name, so this should be a purely UI task.
* The name field should be optional
* By default we should fill it in with `{source_name} <> {destination_name}`
* A user can then enter whatever value they want if they don't like the default.

**Comment by ameyabhope** [comment]
We're very excited about this and would be open to contribute if pointed out in the right direction.

**Comment by bodschut** [comment]
I would also love to have this feature. I have a couple of connections with same source and destination that run on different schedules and target different source tables. It's getting difficult to discern between them in the UI..

**Comment by cgardens** [comment]
We need to update existing name fields in db.

**Comment by cgardens** [comment]
This issue will deal with a subset of https://github.com/airbytehq/airbyte/issues/7251

**Comment by cgardens** [comment]
Execution Plan:
* Change the API to persist the same thing we display in the UI
* Run database migration backfill existing connections with "default" to use the name we would show in the UI
* By default keep current name, but add option in the UI to override the default.

**Comment by timroes** [comment]
@cgardens Can we maybe automatically generate a name in the migration that is presentable in the UI, so we wouldn't need a fallback for the `default` connections, and e.g. generate the name to be "{sourceName} ➔ {destinationName}".

**Comment by cgardens** [comment]
yes! I believe that is what @harshithmullapudi is planning to do.

**Comment by harshithmullapudi** [comment]
This feat is added to API and migration is also handled here https://github.com/airbytehq/airbyte/pull/11153. Next task is to add it to the UI.

@misteryeo is it possible to get some wireframes here?

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Naming connections](https://app.harvestr.io/components/0/list/hF6kPhhDu)

**Comment by misteryeo** [comment]
Have added this as a task for Nico: https://app.asana.com/0/1201442598829240/1201995926046967/f

**Comment by nmacri** [comment]
@misteryeo @harshithmullapudi @cgardens Adding a small piece of community feedback to this issue.  I can see that that connection name is configurable now in the UI 🎉 .  It would also be helpful to have that name (or a sensible default) populated on the listing page for connections in the UI.  We are configuring connections using the Octavia CLI and generating separate connections for each stream w/in a source.  Understand that this usage pattern is a bit novel, but having the connection name in this UI view would be 💯 🏆  (it's currently hard to see which connection is which 😕 )

![image](https://user-images.githubusercontent.com/581267/160939641-e550f2c1-1fa8-4c06-bc7f-c2884d1b7c7b.png)

**Comment by timroes** [comment]
@misteryeo I think the mocks for this conflict with our plans for adding cron expressions as a schedulign option (see https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=32245%3A149479), which would already use the space beside the replication interval. When building this we should keep this in mind, and make sure the connection name will take a separate layout than the cron expressions will need.

**Comment by misteryeo** [comment]
Good point, thanks @timroes for spotting that. Will dig into this!

**Comment by harshithmullapudi** [comment]
@misteryeo are the mocks up to date. Can I pick the UI part?

**Comment by edmundito** [comment]
@harshithmullapudi If you're interested in working on this issue, please follow up with @timroes about working with the frontend team.

**Comment by misteryeo** [comment]
We'll be revising the designs and updating here in the next few days.

**Comment by misteryeo** [comment]
@harshithmullapudi here's the revised designs that includes the cron expresssion: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?node-id=33740%3A179711

cc: @timroes to QA and make sure there's no further conflicts here.

**Comment by cgardens** [comment]
@harshithmullapudi any idea on when this will wrap up? not a rush at all, just to get a rough expectation.

**Comment by harshithmullapudi** [comment]
@cgardens have raised a PR for the same https://github.com/airbytehq/airbyte/pull/12803
