### ISSUE TITLE
MongoDB Source Integration

### ISSUE THREAD

**Issue by toileto** [airbytehq/airbyte#441]
Hi team, I'd like to fly a request with the following details.

## Tell us about the new integration you’d like to have
- Source: MongoDB
- Destination: 
   - BigQuery
   - GCS

## Describe the context around this new integration
The integration can help us with ingesting data easily from MongoDB to our data lake. Batch-processing will be enough (15-minutes, 30-minutes, hourly, daily). Data will be ingested, stored to both BigQuery and GCS data lake. This will be used mainly by our data team only. 

## Describe the alternative you are considering or using
Since the integration is not yet available, I don't mind trying to create the integration by myself if _decent_ documentation is provided.

Thank you!
Warm regards

**Comment by michel-tricot** [comment]
Thank you Yusuf for this issue. Our next milestone will be focused on Integrations both increasing the number but also simplifying the process to add one. MongoDB is high in our list.

**Comment by toileto** [comment]
Hi @michel-tricot @cgardens,

Thank you for picking up this ticket, much appreciated!
Looking forward to seeing the landing of this new integration!

**Comment by nikita-mk** [comment]
I would like to work on this issue.

**Comment by michel-tricot** [comment]
Hey @nikita-mk thanks for the call this morning! There is actually someone already working on a WIP with #2125

**Comment by nikita-mk** [comment]
No problem. I would work on something else then.
