### ISSUE TITLE
Source Paypal Transaction - rate limit review

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#4415]
Official Rate limit (docs: https://developer.paypal.com/docs/api/rate-limiting/) does not contain any concrete numbers

But experience with sandbox and article (https://www.paypal.com/us/smarthelp/article/why-did-i-get-api-error-code-429-ts2115) says that limit seems like is: 
 
50 reqs/min and backoff time about 5 mins.
 
These params should be reviewed.

**Comment by annalvova05** [comment]
Close it as unactual. Back off already implemented.
