### ISSUE TITLE
Can't get passed Getting Started screen after fresh installation

### ISSUE THREAD

**Issue by betizad** [airbytehq/airbyte#44198]
### What happened?

I can't get passed "Getting Started" screen right after it is installed with abctl. Installation. Os is running on a VM in Azure with a reverse proxy to forward all incoming https (443 port) to localhost:8000.

### What did you expect to happen?

I enter email and organization name, but clicking "Getting  Started"  button does not do anything. 
![image](https://github.com/user-attachments/assets/37eb56b8-50af-475f-bb06-1e2787d56072)

### Abctl Version

<details>

```console
$ abctl version
version: v0.12.2
```

</details>

### Docker Version

<details>

```console
$ docker version
27.1.2
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

```

</details>

**Comment by marcosmarxm** [comment]
Hello @betizad can you check the discussion https://github.com/airbytehq/airbyte/discussions/44021 and see if you're not having the problem of trying to access your http connection instance?

**Comment by betizad** [comment]
I tried local install with `--insecure-cookies` flag but the result is the same. I'm kind if stuck at the registration page where you set your email and organization. I can't get passed it to enter username and password.  Any other advice or debugging/logging that I can do to investigate further?

**Comment by betizad** [comment]
I also tried running `kubectl exec --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig --namespace airbyte-abctl -it airbyte-db-0 -- psql -U airbyte -d db-airbyte -t -A -c 'SELECT * FROM "organization"'` and I get

`00000000-0000-0000-0000-000000000000|Default Organization|00000000-0000-0000-0000-000000000000||2024-08-19 21:58:02.751884+00|2024-08-19 21:58:02.751884+00|f|f|f`

**Comment by betizad** [comment]
@marcosmarxm I updated abctl to v0.13.0 and did the installation again with the options mentioned in https://github.com/airbytehq/airbyte/discussions/44021 but still can't get passed the email and organization setting screen. Is there another way to set this through command line rather than doing it by the GUI?

**Comment by betizad** [comment]
with the addition of --email option for abctl local credentials in 0.13.0, I can set the email address and even chnage to a new password, but still stuck at the "Specify your prefernces" screen to enter email and organization.

**Comment by marcosmarxm** [comment]
I see, @betizad please feel free to reach me on Airbyte Slack so we can jump in a quick call.

**Comment by betizad** [comment]
On which Id Can i reach you?

**Comment by bmills22** [comment]
I am also experiencing this with a reverse proxy. I tried #44021 recommendations as well with no luck.

Seems like I am getting a 403 on load for POST /api/v1/users/get, and a 403 when "Get Started" is clicked for POST /api/v1/instance_configuration/setup

ubuntu 24.04
nginx/1.18.0 (Ubuntu)
docker v27.1.2
abctl v0.13.1
Version 127.0.6533.120 (Official Build) (arm64) (incognito)

**Comment by betizad** [comment]
After a discussion with @marcosmarxm I managed to get it working on port 8000 with insecure-cookies and without reverse proxy:
`abctl local install --no-browser --insecure-cookies --host xxx-vm-airbyte-04.westeurope.cloudapp.azure.com`
I set the email and organisation, and then later I can login via the credentials provided by `abctl local credentials`.

The question is if one can set it up with secure-cookies and reverse proxy to HTTPS/443 port?

**Comment by marcosmarxm** [comment]
@betizad do you mind opening a Github Discussion for that question. I'm going to close this one as solved.
