### ISSUE TITLE
Source Google Ads: ad_group_ad stream does not have cost_micros field

### ISSUE THREAD

**Issue by lucas-CDV** [airbytehq/airbyte#44191]
### Topic

google ads ad_group_ad cost_micros

### Relevant information

Hello,

Could you please add `cost_micros`  field in the `ad_group_ad` stream? I would like to get the cost in ad granularity.
Google Ads API Doc reference: [https://developers.google.com/google-ads/api/fields/v15/ad_group_ad#metrics.cost_micros](https://developers.google.com/google-ads/api/fields/v15/ad_group_ad#metrics.cost_micros
)

Currenly working with v 3.3.4 google ads connector.

Thanks!

**Comment by marcosmarxm** [comment]
Please open an issue reporting a problem with connector.
