### ISSUE TITLE
.net core connector template missing

### ISSUE THREAD

**Issue by mikhail-baleika** [airbytehq/airbyte#4432]
## Tell us about the problem you're trying to solve
.net core connector template missing.

## Describe the solution you’d like
It would be great to have a .net core connector template. It would be great to have an ability to generate .net core connector the same way as for java and python right now.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?
I'd like to participate in development, but I'm not sure time allows.

**Comment by sherifnada** [comment]
@mikhail-baleika would you be open to contributing this?
