### ISSUE TITLE
SurveyMonkey: allow user to select replication strategy

### ISSUE THREAD

**Issue by vovavovavovavova** [airbytehq/airbyte#4433]
## Tell us about the problem you're trying to solve
Accordinately to https://github.com/airbytehq/airbyte/pull/4097#discussion_r660644361 
we need to choose `replication_strategy` . It should allow user to decide either replicate all surveys in SurveyMonkey Source, either choose survey ids - in UI.

## Describe the solution you’d like
Add a block to spec.json which is a oneOf called replication_strategy like this to allow a user to choose whether to replicate everything or only specific survey IDs:
```
"objects_to_replicate": {
	"type": "object",
    "title": "Surveys to replicate",
    "description": "Replicate all surveys or some of them?",
    "oneOf": [
      {
        "title": "Replicate all surveys",
        "additionalProperties": false,
        "required": ["method"],
        "properties": {
          "method": {
            "type": "string",
            "enum": ["replicate_all"],
            "default": "replicate_all"
          }
        }
      },
      {
        "title": "Replicate some surveys",
        "additionalProperties": false,
        "required": ["method", "survey_ids"],
        "properties": {
          "method": {
            "type": "string",
            "enum": ["replicate_some"],
            "default": "replicate_some"
          }, 
          "survey_ids": {
          	"type": "array", 
          	"items": {
          		"type": "string"
          	}
          }
        }
      }
  	]
}	
```
this will allow a user to choose whether they want to replicate everything or only specific IDs.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by leo-schick** [comment]
@vovavovavovavova in my opinion, this is deprecated. The survey ids in the configuration are optional in the current version.. When you do not specify any survey id, all surveys are replicated. So, this extra config option is not necessary.
