### ISSUE TITLE
Kubernetes S3 Logging - Support Instance Roles

### ISSUE THREAD

**Issue by afranzi** [airbytehq/airbyte#4438]
## Tell us about the problem you're trying to solve
The current integration with S3 forces us to use AWS keys. We use to deploy all our projects into k8s and configure the AWS rights by using IRSA roles, so AWS keys are not required anywhere.

## Describe the solution you’d like
It would be great if AWS keys are not provided, then the pod/source/destination tries to use the credentials chain by using ENV vars, instance role, etc.

**Comment by marcosmarxm** [comment]
Thanks @afranzi for opening ths. The problem is using the env vars to log to S3 using Kubernetes right?

**Comment by afranzi** [comment]
Hi @marcosmarxm , the idea (for us) would be not using env vars, but using the [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) attached to the namespace + service account of the pod executing the process.

**Comment by marcosmarxm** [comment]
cool, I''m asking this because now we have the S3 connectors but also Airbyte being deployed in AWS using S3. I'm going to rename to be more clear to people know about the issue.

**Comment by Pinimo** [comment]
Hi, I think this issue has been duplicated with this one, more recently active: https://github.com/airbytehq/airbyte/issues/5942

**Comment by afranzi** [comment]
I'm closing this one in favor of the #5942

**Comment by gvillafanetapia** [comment]
but https://github.com/airbytehq/airbyte/issues/5942 talks about IRSA access for source and destination connectors, not exactly for S3 logging, right?
