### ISSUE TITLE
[platform] DBT Cloud Transformation not working after Sync job

### ISSUE THREAD

**Issue by abhinav-sreekumar** [airbytehq/airbyte#44498]
### Relevant information

Hello Airbyte Community,
I am trying to integrate DBT Cloud with Airbyte Cloud. I've configured the connection using the access URL in the format https://<ACCOUNT PREFIX>.us1.dbt.com/ and a service token. The connection appears to be working since I can select DBT Cloud jobs within Airbyte.
However, the transformation is not running after the sync job. When I check the logs, I see the following:

```
2024-08-21 09:21:33 platform > ----- START POST REPLICATION OPERATIONS -----
2024-08-21 09:21:33 platform > 
2024-08-21 09:21:33 platform > Invoking webhook operation XXXXXXXXXXXXXXXX...
2024-08-21 09:21:34 platform > Invoking webhook operation "dbt cloud" using URL "https://cloud.getdbt.com/api/v2/accounts/XXXXXXXXX/jobs/XXXXXXXXX/run/"...
2024-08-21 09:21:35 platform > Webhook operation "dbt cloud" (XXXXXXXXXXXXXXXX) response: 401 {"status": {"code": 401, "is_success": false, "user_message": "Invalid token.", "developer_message": null}, "data": null}
2024-08-21 09:21:35 platform > Webhook XXXXXXXXXXX completed unsuccessfully
2024-08-21 09:21:35 platform > 
2024-08-21 09:21:35 platform > ----- END POST REPLICATION OPERATIONS -----
```
Interestingly, when I use Postman to make an API call to https://<ACCOUNT PREFIX>.us1.dbt.com/api/v2/accounts/XXXXXXXXX/jobs/XXXXXXXXX/run/ it works fine.
Could someone help me figure out why the transformation isn't running as expected in Airbyte? Why is airbyte making an api to call cloud.getdbt.com when I have specifically mentioned a different access URL?
Thank you!

**Comment by marcosmarxm** [comment]
Thanks @abhinav-sreekumar for reporting the problem. @airbytehq/platform-compose can someone take a look into this?

**Comment by abhinav-sreekumar** [comment]
I'm assuming the custom access URL was being saved because I was able to pick between my different DBT cloud jobs. This is my workspace ID.`43cfe2f0-ac3f-482b-83fe-55cb2ec89047`. Today on trying to integrate with DBT cloud in the same way. Airbyte is throwing this error
`dbt Cloud denied access. Please verify your service token and access URL.`
I made an API call to dbt cloud with the same access url and service token and  i'm getting a response on postman

**Comment by abhinav-sreekumar** [comment]
I had already added the DBT cloud config and the connection was successful. On the transformation page of the connection i was able to pick between the different DBT jobs. The issue was that it was not running the jobs. On friday, I removed the Integration and while trying to add it again(going through the same flow that I did the last time) It stopped working.

**Comment by malikdiarra** [comment]
Hi @abhinav-sreekumar, we indeed had an issue with dbt integration that we resolved at the end of last week. I'm sorry for the poor communication.
