### ISSUE TITLE
JWT issuer not configured

### ISSUE THREAD

**Issue by sudip-mondal-2002** [airbytehq/airbyte#44492]
### Topic

powered by airbyte

### Relevant information

Can't access the autheticated endpoints.

Way to reproduce:
Go to powered by airbyte
Create a access token using the access token api
then list down the sources/create a source/do similar operation
```
{
  "code": 401,
  "message": "Jwt issuer is not configured"
}
```

**Comment by nataliekwong** [comment]
Hi there,

We have released a fix for this issue. Can you retry and see if the issue persists?
Linking also to the Github discussion in case it's helpful https://github.com/airbytehq/airbyte/discussions/44487

**Comment by octavia-squidington-iii** [comment]
Zendesk ticket #[7871](https://airbyte1416.zendesk.com/agent/tickets/7871) has been linked to this issue.
