### ISSUE TITLE
HTTP connector doesnt display form when selected

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4449]
## Enviroment
- **Airbyte version**:  0.26.4-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker 
- **Source Connector and version**:  HTTP connector
- **Destination Connector and version**: ~
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Selecting a new source connector

## Current Behavior
The HTTP connector spins for a while and doenst show the form to fill.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
@nataliekwong fyi

**Comment by Jamakase** [comment]
The form is displayed correctly in 0.27.0-alpha. It is possible that some error occurred when the request was sent.

Addressing #4526 and #3809 should bring better UX in such cases.

![image](https://user-images.githubusercontent.com/3767150/124354042-39bc8b80-dc34-11eb-8de2-ae590a1875c8.png)

**Comment by marcosmarxm** [comment]
Confirm that Airbyte 0.27.0-alpha the connector is working properly, thanks @Jamakase
