### ISSUE TITLE
Clarify in docs relationship to Singer project from Stitch/Talend?

### ISSUE THREAD

**Issue by alexanderdean** [airbytehq/airbyte#445]
Hi - Airbyte looks like a cool project!

I was trying to find the [integrations library](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/src/main/java/io/airbyte/integrations) and it seemed empty with references to the most-excellent [Singer](https://github.com/singer-io) project from [Stitch/Talend](https://www.stitchdata.com/).

Can you guys clarify in your documentation the relationship/dependency between Stitch and Airbyte?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368233045024) by [Unito](https://www.unito.io)

**Comment by alexanderdean** [comment]
I think a good comparator is the Meltano project from GitLab which is very clear on its Singer dependencies: https://meltano.com/

**Comment by michel-tricot** [comment]
Thanks for the feedback.

Singer does a good job at creating standalone connectors (although the quality varies a lot). We focus on creating a company wide integration platform. We are using some singer connectors to bootstrap our project but we’re still figuring out what place it should have over the long term.

We will likely maintain some sort of compatibility with their protocol so they can be orchestrated and be usable out-of-the-box in Airbyte.

**Comment by alexanderdean** [comment]
Thanks @michel-tricot - makes a lot of sense. Certainly no harm in bootstrapping - we used the Piwik (now Matomo) JavaScript Tracker to bootstrap [Snowplow](https://github.com/snowplow/snowplow) back in 2012.

The idea of generalizing the Singer protocol so that multiple projects could use it and potentially connector authors could go polyglot is super-interesting...

**Comment by cgardens** [comment]
Closing as no longer relevant. We do not rely on Singer at all anymore.
