### ISSUE TITLE
[Source google-ads] latest version connector upgrade in airbyte removed 10 streams like keyword_view, ad_group_ad_legacy

### ISSUE THREAD

**Issue by aalkuatova** [airbytehq/airbyte#44501]
### Connector Name

source-google-ads

### Connector Version

 3.6.5

### What step the error happened?

Updating the connector

### Relevant information

There was the folllowing error in google ads connector: 500 Internal error encountered. [type_url: "type.googleapis.com/google.ads.googleads.v15.errors.GoogleAdsFailure" value: "\n%\n\002P\002\022\037An internal error has occurred.\022\026nz4nFRswxwEKMJ5g6_06Wg" ]
Upgrading a connector to the latest version (3.6.5) fixed this error but then airbyte showed "Non-breaking schema updates detected" and wanted to remove 10 streams, however these streams are persisted in a streams.py file (example KeywordView). Why did it remove those streams?

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@airbytehq/dev-python can someone check this question about Google Ads?

**Comment by girarda** [comment]
@aalkuatova what version are you upgrading from? `keyword_view` is still an available stream in `3.7.0`

**Comment by aalkuatova** [comment]
@girarda I have upgraded to version 3.6.5

**Comment by aalkuatova** [comment]
@girarda from the very early version like 3.2.0, I've tried 3.7.0, still keyword_view not available

**Comment by girarda** [comment]
Can you share a screenshot of your connection schema?

![Screenshot 2024-08-26 at 6 31 52 PM](https://github.com/user-attachments/assets/5325f233-f390-4e8e-9196-19654cf9a4f8)

**Comment by aalkuatova** [comment]
![image](https://github.com/user-attachments/assets/02e33fa7-06ca-401b-9245-302ec7843eb6)
![image](https://github.com/user-attachments/assets/78c9c3ab-bd3e-4d6a-bf16-27d29263576b)

**Comment by girarda** [comment]
@aalkuatova do you have a manager account? [We do restrict the stream to non manager accounts](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py#L281).

**Comment by natikgadzhi** [comment]
Closing! Feel free to reopen if this is still a problem.
