### ISSUE TITLE
source-google-ads -  Upgrade Google API to v17

### ISSUE THREAD

**Issue by Naman-2001** [airbytehq/airbyte#44545]
### Connector Name

source-google-ads

### Connector Version

3.6.5

### What step the error happened?

Other

### Relevant information

Our team is extracting google ads information from the source. We want to get information about the **asset groups** and the particular **date** for which the metrics are generated. For this we need the **segments.date** property as mentioned in there documentation. Upon analysis segments are not present in asset_groups in v15 of google API but in v16 onwards.

[V15 Docs](https://developers.google.com/google-ads/api/fields/v15/asset_group)
[V17 Docs](https://developers.google.com/google-ads/api/fields/v17/asset_group)

We looked upon the[ airbyte github code](https://github.com/airbytehq/airbyte/blob/6fd9f08b9a073ce36d73fcf13c2f56e3a6a8db97/airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py#L65C20-L65C94) - where v15 is supported as of yet.

We request the Airbyte team to update the google api version so that we can extract relevant metrics.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks @Naman-2001 for requesting this feature I included it to the connector team backlog.

**Comment by Naman-2001** [comment]
Can we expect any ETA on this @marcosmarxm ? Thanks.

**Comment by girarda** [comment]
@Naman-2001 you can upgrade your connector to v3.7.0 to use v17 of the API.
