### ISSUE TITLE
[platform] airbyte-minio-0 pod restarts because of storage space is full

### ISSUE THREAD

**Issue by venkateshkelevo** [airbytehq/airbyte#44556]
### Topic

Is there way to cleanup minio storage space automatically to avoid the space issues

### Relevant information

airbyte-minio-0 pod restarts because of pvc storage space is full. The job logs are going to /storage/airbyte-storage/job-logging. Is there a way to cleanup automatically to avoid the space issues?

Thanks.

**Comment by marcosmarxm** [comment]
Thanks @venkateshkelevo are you deploying using abctl or helm?

**Comment by venkateshkelevo** [comment]
I am using helm for deployment

**Comment by venkateshkelevo** [comment]
@marcosmarxm, Could you confirm is there any way to achieve auto cleanup of logs?

**Comment by bgroff** [comment]
You should be able to `kubectl exec -it -n airbyte-abctl airbyte-minio-0 -- /bin/bash` into the pod and remove those files.

**Comment by adrian-martinez-onestic** [comment]
> You should be able to `kubectl exec -it -n airbyte-abctl airbyte-minio-0 -- /bin/bash` into the pod and remove those files.

This answer does not address the "automatically" part of the issue description.
