### ISSUE TITLE
Cloud - marketplace publishing bug

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/airbyte#44564]
### Platform Version

Latest Cloud Version

### What step the error happened?

During the Sync

### Relevant information

Creating PR Via builder ui is currently broken
Ref:
![image](https://github.com/user-attachments/assets/9b74deec-f098-45e6-b41f-f4c3d8a15ee9)

**Comment by natikgadzhi** [comment]
@erohmensing is looking into this.

**Comment by erohmensing** [comment]
https://github.com/airbytehq/airbyte-platform-internal/pull/13641 should close this once it's deployed

**Comment by btkcodedev** [comment]
Issue cleared in cloud✅
