### ISSUE TITLE
🎉New Source: Reddit

### ISSUE THREAD

**Issue by btkcodedev** [airbytehq/airbyte#44561]
### Topic

Reddit API source for sentiment analysis

### Relevant information

The source connector for Reddit would allow users to explore subreddit info for sentiment analysis,
Flexible query parameters would allow users to type in their needs.

### Objective

Provide flexible reddit connector with query parameters

### Streams

Self: Self info for indexing
Message inbox: Self message info for indexing
Subreddit explore: ListPartitioned subreddits info
Subreddit popular: Popular subreddits search
Reddits search using query: Given q parameter with user input

### More info

Outh reference
https://github.com/reddit-archive/reddit/wiki/OAuth2-Quick-Start-Example

API reference:
https://www.reddit.com/dev/api/oauth

**Comment by natikgadzhi** [comment]
I'd include a "subreddit" stream that syncs up a particular subreddit given the name in config. OR a list of subreddits. 

The problem that this connector is very likely to hit is rate limits. Please document that and make decent error handling.
