### ISSUE TITLE
Migrating from Docker Compose failed using abctl tool

### ISSUE THREAD

**Issue by tim0n3** [airbytehq/airbyte#44583]
### What happened?

Cannot successfully install airbyte 0.63.19 using `abctl local install --migrate`

Logs:
[abctl-logs.txt](https://github.com/user-attachments/files/16727119/abctl-logs.txt)
[redacted-docker-compose.yaml.txt](https://github.com/user-attachments/files/16727046/redacted-docker-compose.yaml.txt)
[redacted-env.txt](https://github.com/user-attachments/files/16727047/redacted-env.txt)

### What did you expect to happen?

Migration from docker stack to abctl cluster per the documentation > [Migrating from Docker Compose](https://docs.airbyte.com/using-airbyte/getting-started/oss-quickstart#migrating-from-docker-compose-optional)

### Abctl Version

<details>

```console
$ abctl version
# [paste output here](version: v0.13.1)
```

</details>

### Docker Version

<details>

```console
$ docker version
# Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# On Mac:
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by marcosmarxm** [comment]
```
            Message: Failed to pull image "airbyte/webapp:0.63.19": failed to pull and unpack image "docker.io/airbyte/webapp:0.63.19": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/airbyte/webapp/manifests/sha256:f83cfbb9960a81127570b6c1ee7fb8d0f7e1f1a3f68b76f3b953c3dc73ecb39e: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Are you logged into Docker? `docker login`

**Comment by tim0n3** [comment]
Thanks for getting back to me so quickly.

I shall restore my working snapshot and attempt this again - this Friday - after signing in to docker.

**Comment by tim0n3** [comment]
Update: so I managed to restore a snapshot and re-ran through the migration process.
- login to docker cli
- followed the steps in the documentation (linked above)
- ran abctl migration command under screen 
- C-a d d to leave the abctl command running in the background and carried on with my day.
- Checked right now to be met with the following output lasting over 7Hrs:
![Screenshot 2024-08-27 at 16 26 15](https://github.com/user-attachments/assets/3b755014-406a-4e81-abcf-b4e4c1e07a4e)
![Screenshot 2024-08-27 at 16 26 44](https://github.com/user-attachments/assets/a9582881-7636-46bf-b2a8-9732cf0a72db)

Any suggestions? I'm running this on a headless instance:
