### ISSUE TITLE
Airbyte fetching the job info from Old workspace

### ISSUE THREAD

**Issue by ananth-spikeup** [airbytehq/airbyte#44605]
### Relevant information

With the new setup Airbyte workspace Id got changed however the get jobs api (https://localhost:1000/api/v1/jobs/get) fetching the job ids from old workspace and its pointing to old docker images.
Restarted all the components like webapp, temporal, worker etc., but issue not resolved.

**Comment by marcosmarxm** [comment]
Sorry @ananth-spikeup I'm closing the issue as it doesn't provide steps, version, anything to reproduce the problem. Please feel free to open a new one providing as much information you have.
