### ISSUE TITLE
Exception Notification for UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4461]
## Tell us about the problem you're trying to solve
In cloud or OSS when a user experience an error in the UI we want to be exposed to that.

## Describe the solution you’d like
Sentry?

**Comment by cgardens** [comment]
@johnlafleur @avaidyanatha @nataliekwong - Is there any objection to adding sentry to the UI in the OSS product. It should expose frontend errors that people experience. We will definitely want to add this is the cloud version, but I think it can only helpful in the OSS version too.

@sherifnada you might want to weigh in to since you were talking about implementing sentry for connectors or part of the backend.

**Comment by avaidyanatha** [comment]
@cgardens I personally love Sentry and am 100% on board.

**Comment by nataliekwong** [comment]
No objections from me.

**Comment by sherifnada** [comment]
Do you know if sentry is a good fit for uploading potentially large log files? That's the only open question for me -- if not then we'll need to implement something else custom for that, otherwise SGTM

**Comment by johnlafleur** [comment]
No objections on my side as well.

**Comment by cgardens** [comment]
> Do you know if sentry is a good fit for uploading potentially large log files? That's the only open question for me -- if not then we'll need to implement something else custom for that, otherwise SGTM

I don't know the answer to that. I've only ever used it with the UI.

**Comment by cgardens** [comment]
This is out of scope for the private beta launch, but is worth doing shortly after as it will allow us to be proactive on problems. I think we will want to turn it on for OSS and cloud, but to start let's just turn it on for cloud so it is super clear what we're looking at. once we get some experience with the tool (and are confident that we can split up the metrics for cloud and oss) we will turn it on for both.

**Comment by timroes** [comment]
Closing this, since we have Sentry implemented nowadays, which does allow us to track exceptions and errors in the webapp.
