### ISSUE TITLE
New source: Trello

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4462]

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
partially:
https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/

**Available authentication modes (API key/Oauth/other)** 
API key:
https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/
OAuth 1.0:
https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/#using-basic-oauth

**Has Sandbox environment?** 
Yes:
https://trello.com/b/cW1IZpB1/amfam-imlp-round-1-complete

**How to populate the account with data** 
UI,
API

**Available streams for sync** 
Boards
Lists
Cards
Actions

**Integration supports incremental sync?** 
No

**Other information/blockers** 
API limits:
https://developer.atlassian.com/cloud/trello/guides/rest-api/limits/
Rate limits:
https://developer.atlassian.com/cloud/trello/guides/rest-api/rate-limits/
Community sample projects:
https://developer.atlassian.com/cloud/trello/guides/community/community-projects/"

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation.

**Comment by sherifnada** [comment]
thanks @igrankova !
