### ISSUE TITLE
New Source: Google Analytics v4

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4463]
## Tell us about the new connector you’d like to have
Google Analytics v4 API

## Describe the alternative you are considering or using
Use the current GA v3 connector available in Airbyte

**Comment by shmf** [comment]
Hello @sherifnada adding here my comment as at Soho House we are using GA3 and GA4 and it would be great to have both on Airbyte!
Also subscribing so I get notified if something change.
Thanks

**Comment by davidvermeersch** [comment]
@sherifnada adding v4 would be much appreciated
