### ISSUE TITLE
Auto-upgrade connector versions when they have had backwards compatible updates

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4470]
## Tell us about the problem you're trying to solve
I want my connection to pick up a backwards-compatible connector upgrade (bugfix or performance improvement) without any intervention from me

Specifically, this is during the upgrade process, it should upgrade not just unused connectors but also in-use connectors to the latest patch for the current minor version (as determined by that release's definition list).

**Comment by cgardens** [comment]
relates to GA: https://docs.google.com/document/d/1q9ncTSja4pZFJYEEs_AQ6NKOJOrMzcWq7KSyHCx4lPw/edit#heading=h.ebg70bleg9sd

**Comment by jrhizor** [comment]
We should add the ability to disable this using an environment variable flag and we should communicate that users mirroring connector images will need to switch off this auto-update feature here.
