### ISSUE TITLE
GitHub Connector: Get data from all repositories in an organization

### ISSUE THREAD

**Issue by jgtvares** [airbytehq/airbyte#4473]
## Tell us about the problem you're trying to solve
I'm not able to retrieve data from all repositories in a GitHub organization at once.
The GitHub connector only supports a list of repositories separated by space. 
In a big organization with more than 600 projects, it becomes impossible to retrieve all of them like this.

## Describe the solution you’d like
I thought of two solutions:
1. Add a field to input the organization name (or URL) and retrieve data from all repositories in it.
2. Get data from repositories by team slug (Organization/team).

**When querying data I should be able to filter by archived or not archived repositories.**

## Describe the alternative you’ve considered or used
We considered using a GitHub Webhook, when a repository is created, to trigger a Lambda function that uses Airbyte's API to update the source.

## Additional context
My team and I have been testing Airbyte + Grafana for a while now to measure our software delivery performance based on the [Four Key Metrics](https://itrevolution.com/measure-software-delivery-performance-four-key-metrics/) model.
We're seeing a lot of potential in Airbyte, but the limitation mentioned in this issue is keeping us from taking the next step.

## Are you willing to submit a PR?

Yes.

**Comment by marcosmarxm** [comment]
Thanks @jgtvares at the moment the Github connector is being rebuild using the Native Airbyte CDK in https://github.com/airbytehq/airbyte/pull/4174. Probably will continue using the listing parameter to get repositories. I think after releasing the connector can be easy extend it to a custom connector for your use case. @sherifnada wdyt? or this could be added to the Github connector itself?

**Comment by jgtvares** [comment]
> Thanks @jgtvares at the moment the Github connector is being rebuild using the Native Airbyte CDK in #4174. Probably will continue using the listing parameter to get repositories. I think after releasing the connector can be easy extend it to a custom connector for your use case. @sherifnada wdyt? or this could be added to the Github connector itself?

:pray:

**Comment by sherifnada** [comment]
We should add this to the Github connector as an option for sync. It should not be a challenging project, and would be a great feature to have IMO.

**Comment by sherifnada** [comment]
@jgtvares would you be open to contributing this feature?

**Comment by jgtvares** [comment]
> @jgtvares would you be open to contributing this feature?

I would love to! It would be a great experience!
But I'm really invested at work and I wouldn't have time to dedicate myself.
I hope I can contribute in a near future, maybe in another feature!
