### ISSUE TITLE
Airbyte Cloud: Sign up / Login flow

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4485]
## Tell us about the problem you're trying to solve
For Airbyte Cloud a user needs to be able to sign up / login like a normal SaaS app.

## Describe the solution you’d like
* [Mock ups](https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Website?node-id=26319%3A100).
* We will be using Auth0 as the auth provider

**Comment by cgardens** [comment]
blocked because this will be hard to work on before @jrhizor finishes up speccing out the Auth0 stuff.

**Comment by cgardens** [comment]
this should be blocked anymore. reach out to @jrhizor &  @davinchia with any questions in #_dev_platform_and_cloud in slack.

**Comment by davinchia** [comment]
* should not

**Comment by Jamakase** [comment]
Done
