### ISSUE TITLE
[destination-timeplus] Please upgrade Airbyte cloud with latest version

### ISSUE THREAD

**Issue by jovezhong** [airbytehq/airbyte#44916]
### Connector Name

destination-timeplus

### Connector Version

0.1.0

### What step the error happened?

During the sync

### Relevant information

I am a paid customer on airbyte cloud and load various data from hubspot/ga4/github into our own data platform: timeplus.com

I wrote the `destination-timeplus` more than 1 year ago and released 0.1.0. After that it seems that airbyte engineering team made some update. The latest version is 0.1.17. However in airbyte cloud, it remains 0.1.0

Recently when I loading data from linkedin to timeplus, I got error to generate table schema in timeplus based on linkedin
```
  File "/airbyte/integration_code/destination_timeplus/destination.py", line 73, in write
    DestinationTimeplus.create_stream(
  File "/airbyte/integration_code/destination_timeplus/destination.py", line 101, in create_stream
    tp_stream.column(name.strip(), DestinationTimeplus.type_mapping(v))
  File "/airbyte/integration_code/destination_timeplus/destination.py", line 112, in type_mapping
    type_def['items'] = v['items']
KeyError: 'items'
```
I did some debug, this was lead by the linkedin connector doesn't include `items` for array type
```json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "followerCountsByGeo": { "type": ["array", "null"] },
    "organizationalEntity": { "type": ["string", "null"] },
    "followerCountsByFunction": { "type": ["array", "null"] },
    "followerCountsByIndustry": { "type": ["array", "null"] },
    "followerCountsBySeniority": { "type": ["array", "null"] },
    "followerCountsByGeoCountry": { "type": ["array", "null"] },
    "followerCountsByAssociationType": { "type": ["array", "null"] },
    "followerCountsByStaffCountRange": { "type": ["array", "null"] }
  },
  "additionalProperties": true
}
```
I can fix this by releasing a new version of destination-timeplus. But this connector hasn't been updated for almost 1 year. I understand marketplace connectors are at different SLA but I noticed many other marketplace connectors are running the latest version.

Long story short, please update airbyte cloud with latest `destination-timeplus`. I probably will publish more versions with more enhancements. But if the connector version cannot be updated, there is no way for me to fix the issue on airbyte cloud. I don't want to leave airbyte cloud and go back to self-hosted airbyte.

### Relevant log output

```shell
File "/airbyte/integration_code/destination_timeplus/destination.py", line 73, in write
    DestinationTimeplus.create_stream(
  File "/airbyte/integration_code/destination_timeplus/destination.py", line 101, in create_stream
    tp_stream.column(name.strip(), DestinationTimeplus.type_mapping(v))
  File "/airbyte/integration_code/destination_timeplus/destination.py", line 112, in type_mapping
    type_def['items'] = v['items']
KeyError: 'items'
```
```


### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment]
Hey @jovezhong! Thank you for contributing the destination in the first place. 

Yep, I see we've archived it in cloud — it was not used at the moment, and it didn't pass it's own integration tests. Would you be open to revive it? 

The updates that you see (0.1.17) are probably automated dependency updates and version bumps. 

To get this thing back, you would need to: 

1. In [metadata.yaml](https://github.com/airbytehq/airbyte/blob/59d4255415561e8bf2d609f2854e9ce4194f7dc9/airbyte-integrations/connectors/destination-timeplus/metadata.yaml#L11), turn registryOverrides back to `enabled: true` for both Cloud and OSS.
2. Bump the Airbyte CDK version in `pyproject.toml` to `^4.6.1` (current), then run `poetry lock`.
3. Make sure at least unit tests are passing 
4. Bump the version in `pyproject.toml`, `metadata.yaml`, and the docs page. 
5. Put that into a PR. 

I'll happily approve it, and then we can see if the new version works nicely.

**Comment by jovezhong** [comment]
thank you @natikgadzhi . I submitted https://github.com/airbytehq/airbyte/pull/44758 a while ago and will make more changes per your team's feedback

**Comment by girarda** [comment]
Closing as the connector has been updated in https://github.com/airbytehq/airbyte/pull/44758. Thanks @jovezhong !

**Comment by jovezhong** [comment]
Thank you, I just realized https://docs.airbyte.com/integrations/destinations/timeplus is updated (without the archived status)
