### ISSUE TITLE
[abctl] Database Corruption during migration / Error executing PERSIST: ERROR: could not read block 8

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#44935]
### What happened?

After upgrading a docker compose setup to abctl and upgrading the BigQuery destination we are seeing this error breaking all our connections:
Caused by: io.temporal.failure.ApplicationFailure: message='Server error : 500 Internal Server Error {"message":"Internal Server Error","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/workload/create","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Internal Server Error: Error executing PERSIST: ERROR: could not read block 8 in file \"base/16385/17447\": read only 0 of 8192 bytes","logref":null,"path":null,"_links":{},"_embedded":{}}]}}', type='io.airbyte.workload.api.client.generated.infrastructure.ServerException', nonRetryable=false
Would be happy if anyone had any idea what is causing this or how to troubleshoot. I haven't found anyone with a similar problem on Github issues.

[Slack Thread](https://airbytehq.slack.com/archives/C021JANJ6TY/p1724696479364259)

**Comment by marcosmarxm** [comment]
At the moment it looks impacted 2 users in Airbyte Slack. It isn't clear what caused or reproduce the issue.

**Comment by marcosmarxm** [comment]
From Thomas there is a workaround:
> Hi, so eventually I was able to fix this one myself by searching the web for similar could not read block 8 in file errors and there were just very few hits but they all talked about postgres. In the end it turned out the abctl local migrate step somehow corrupted the postgres DB but luckily a REINDEX schema public; followed by VACUUM FULL; was able to recover it

**Comment by spunzon** [comment]
I have a similar error when I try a replication:
message='io.airbyte.workload.api.client.generated.infrastructure.ServerException: Server error : 500 Internal Server Error {"message":"Internal Server Error","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/workload/create","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Internal Server Error: Error executing PERSIST: ERROR: could not read block 4 in file \"base/16385/127275\": read only 0 of 8192 bytes","logref":null,"path":null,"_links":{},"_embedded":{}}]}}', type='java.lang.RuntimeException', nonRetryable=false

I tried the workaround but I get this error:

`kubectl exec --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig --namespace airbyte-abctl -it airbyte-db-0 -- psql -U airbyte -d db-airbyte
E0902 15:13:06.124534  117417 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0902 15:13:06.126085  117417 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0902 15:13:06.128036  117417 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
E0902 15:13:06.129990  117417 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp [::1]:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?`
