### ISSUE TITLE
Populate shopify sandbox account with data

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4496]
## Tell us about the problem you're trying to solve
We have credentials in lastpass for a shopify sandbox account where we can create fake transactions. 

We want to populate the account with data for all streams supported by the Shopify connector: 

Abandoned Checkouts
Collects
Custom Collections
Customers
Draft Orders
Discount Codes
Metafields
Orders
Products
Transactions
Pages
Price Rules

For each of these streams, we want to create 200+ entries through the API. To do this you'll need to sign in, obtain an API token, and create these resources. 

If they can only be created through the UI, then create 10.

**Comment by cheyura** [comment]
@sherifnada For JolieCookie https://jolicookie.myshopify.com/admin/orders?selectedView=all 50+orders(in different statuses  for 27 customers) have been already populated by eng team. May I close this one?

**Comment by sherifnada** [comment]
@cheyura this ticket is Not for the jolicookie Shopify account. It is for the sandbox account present in LastPass

**Comment by cheyura** [comment]
@sherifnada JolieCookie is one of the shops in sandbox account 
![image](https://user-images.githubusercontent.com/84457236/124581671-f6dbfd00-de59-11eb-9098-23610648e3e1.png)

**Comment by sherifnada** [comment]
Got it. For this ticket let's create resources only in the airbyte-integration-test store

**Comment by cheyura** [comment]
@sherifnada The data for all streams above is generated

**Comment by sherifnada** [comment]
Thank you @cheyura! Closing this ticket.
