### ISSUE TITLE
When user subscribes to feature updates or security updates in preferences setup, we need to add them to the corresponding lists

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#450]
## Tell us about the problem you're trying to solve
We're not logging them yet automatically, we should. 
If we could use 2 different webhooks with the email address on it, that will be enough for me to log them in the right list on Mailchimp.
If we can't use webhooks, which format are we thinking about? To be discussed

## Additional context
We use Mailchimp to send the emails.

**Comment by cgardens** [comment]
Webhooks seem like a reasonable approach to me, as long as it can be done without exposing any secrets.

**Comment by cgardens** [comment]
Looks like this should be possible. [mailchimp webhook docs](https://mailchimp.com/developer/guides/sync-audience-data-with-webhooks/).

@johnlafleur can you provide the urls for the webhooks? once we have that we should be good to go.

**Comment by michel-tricot** [comment]
Isn't it something that we could do we segment?

**Comment by cgardens** [comment]
Oh. Interesting. If it's possible that would be preferred.

**Comment by johnlafleur** [comment]
Mailchimp can be listed as a destination on Segment. So it might be possible.
However, it won't be plugged to Orbit (and less importantly, we won't receive the Slack notification). 

I'm wondering if Segment can only be more blocked than a webhook by ad blockers.

**Comment by johnlafleur** [comment]
I was able to implement it using Segment => Webhook => Zapier => Orbit + Mailchimp + Slack. All good
