### ISSUE TITLE
Build cache breaking publish process for connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4508]
https://github.com/airbytehq/airbyte/pull/4507 was created as a workaround to for publishing connectors in CI. The change was made by disabling the gradle cache completely. 

This issue is a follow to revert that change once the problem has been debugged correctly. 

It's actually unclear if the build cache is even needed for publishing connectors, so I'm going to mark this issue as low priority.

**Comment by davinchia** [comment]
See #4559 for the eventual fix + follow up work.
