### ISSUE TITLE
[airbyte-cd]  upgrade nltk package `>3.8.1`

### ISSUE THREAD

**Issue by XRFate** [airbytehq/airbyte#45121]
### Topic

package dependencies

### Relevant information

 i am using `llama-index-core`. the package conflicted with nltk's version. 
[nltk update ](https://github.com/nltk/nltk/issues/3305) 
currently airbyte-cdk locked at 3.8.1  please upgrade to enable more features and compatibility with other repos

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @XRFate. The issue was included in the backlog but won't be prioritized right now.

**Comment by natikgadzhi** [comment]
This is done now too.
