### ISSUE TITLE
[source-looker] connector version not up to date

### ISSUE THREAD

**Issue by qchuchu** [airbytehq/airbyte#45129]
### Connector Name

source-looker

### Connector Version

0.2.7

### What step the error happened?

Configuring a new connector

### Relevant information

The current Looker Connector Version on Airbyte Cloud is the 0.2.7, which is deprecated (the latest one is the 1.0.6).

Hence, it makes it impossible to create a connection using this connector, because it uses a deprecated API (3.1 of Looker).

![image](https://github.com/user-attachments/assets/0d9e2916-28f8-4db1-9704-ffd779fb1764)

https://docs.airbyte.com/integrations/sources/looker?_gl=1*orunmk*_gcl_au*MjExMTg2MzQ2Ny4xNzI1MjcyNzQ3

Would it be possible to upgrade the connector version on Airbyte Cloud ? 

@topefolorunso for the followup :) 

Thanks for your help

### Contribute

- [ ] Yes, I want to contribute

**Comment by topefolorunso** [comment]
@natikgadzhi  @ChristoGrab @marcosmarxm please advise

Cloud version of source looker doesn't align with current version

**Comment by marcosmarxm** [comment]
The reason is because the metadata is set to false to update this connector in cloud.
@natikgadzhi / @ChristoGrab now with marketplace should we restore the connector in cloud?
https://github.com/airbytehq/airbyte/blob/d02d29c054772739f9e3f4cbdf835040883f5056/airbyte-integrations/connectors/source-looker/metadata.yaml#L15-L17

**Comment by ChristoGrab** [comment]
Huh, this is an interesting case. It seems that the removal from the catalog in 0.2.8 was part of an automated update, so it may have been removed unintentionally? I've reached out to my team for confirmation and will circle back soon as I have an answer. 

My naive guess is that it should be fine to re-enable the current version in the Cloud registry. If there is a valid reason not to do so, we can at least remove the deprecated version from the Cloud catalog to avoid any confusion and clarify that it is OSS-only.

**Comment by qchuchu** [comment]
Thanks @ChristoGrab for the followup ! Don't hesitate if I can help in any way, waiting for your team reply then

**Comment by ChristoGrab** [comment]
@qchuchu Good news, we got approval to get the current version back in the Cloud catalog! [Link to the PR](https://github.com/airbytehq/airbyte/pull/45161) 

I'm not sure how often the registries are updated so it might take a moment to show up, but you should soon be able to find version `1.0.7` listed.

**Comment by qchuchu** [comment]
Great news !! I was already able to upgrade, thank you very much for the reactivity 😍😍

**Comment by natikgadzhi** [comment]
Tell me more! Metadata monitoring didn’t spot this.
