### ISSUE TITLE
[abctl] Can't login when behind nginx reverse proxy

### ISSUE THREAD

**Issue by craigbloodworth** [airbytehq/airbyte#45197]
### What happened?

After migrating from docker compose to abctl I now can't login to Airbyte as it sits behind an nginx reverse proxy for SSL. I'm using the new credentials provided by `abctl local credentials`

The following error is returned:
```
{
  "url": "https://***/login",
  "airbyteVersion": "0.64.1",
  "errorType": "HttpError",
  "errorConstructor": "gd",
  "error": {
    "i18nKey": "errors.http.forbidden",
    "i18nParams": {
      "status": 403
    },
    "name": "HttpError",
    "requestId": "7uxTFsUotDWzNJVUQfhadG",
    "request": {
      "url": "/api/login",
      "method": "post",
      "headers": {
        "Content-Type": "application/json"
      },
      "data": {
        "username": "***",
        "password": "***"
      }
    },
    "status": 403,
    "response": ""
  },
  "stacktrace": "HttpError: errors.http.forbidden\n    at Mve (https://***/assets/core-ewtsdo5l3e.js:119:10572)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
  "featureFlags": {}
}
```

### What did you expect to happen?

A usual login as before

### Abctl Version

<details>

```console
$ abctl version
version: v0.14.1
```

</details>

### Docker Version

<details>

```console
$ docker version
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.14
 Git commit:        ced0996
 Built:             Tue Jun 25 22:37:33 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.14
  Git commit:       a61e2b4
  Built:            Tue Jun 25 22:38:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.12
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
```

</details>

**Comment by craigbloodworth** [comment]
Might be useful info...I set the --host flag to the FQDN of the nginx proxy however when airbyte starts it still states:

`INFO   Airbyte should be accessible via http://localhost:8000`

Shouldn't localhost be replaced with the FQDN?

**Comment by marcosmarxm** [comment]
Hello @craigbloodworth, thanks for reporting the issue. The only customization during the installation is the use of the flag `--host` and not custom values files, correct? Can you share the nginx config file you made?

**Comment by marcosmarxm** [comment]
+ can you share the airbyte-server logs?

**Comment by craigbloodworth** [comment]
> Hello @craigbloodworth, thanks for reporting the issue. The only customization during the installation is the use of the flag `--host` and not custom values files, correct? Can you share the nginx config file you made?

Yes that's correct. Nginx config is standard:

```
server {
  listen 443 ssl;
  server_name airbyte.***.co.uk;
  client_max_body_size 200M;
  ssl_certificate /etc/nginx/ssl/***.crt;
  ssl_certificate_key /etc/nginx/ssl/***.key;

  location / {
    proxy_pass http://localhost:8000;
    proxy_set_header Cookie $http_cookie; 
    proxy_read_timeout 3600; 
  }
}
```

**Comment by cbeauch** [comment]
I'm getting a similar issue. When I turn on global auth, I get the following error and no popup to enter the password

```
{
  "url": "https://airbyte.xxx.com/",
  "airbyteVersion": "0.63.19",
  "errorType": "HttpError",
  "errorConstructor": "gd",
  "error": {
    "i18nKey": "errors.http.unauthorized",
    "i18nParams": {
      "status": 401
    },
    "name": "HttpError",
    "requestId": "u69Cywzz3CXR4CrtK3Ci1d",
    "request": {
      "url": "/api/v1/users/get",
      "method": "post",
      "headers": {
        "Content-Type": "application/json"
      },
      "data": {
        "userId": "00000000-0000-0000-0000-000000000000"
      }
    },
    "status": 401,
    "response": {
      "message": "Unauthorized",
      "_embedded": {
        "errors": [
          {
            "message": "Unauthorized",
            "_embedded": {},
            "_links": {}
          }
        ]
      },
      "_links": {
        "self": {
          "href": "/api/v1/users/get",
          "templated": false
        }
      }
    }
  },
  "stacktrace": "HttpError: errors.http.unauthorized\n    at Rve (https://airbyte.helcim.com/assets/core-du4n84dfbx.js:119:10478)",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
  "featureFlags": {}
}
```

**Comment by marcosmarxm** [comment]
@cbeauch what do you mean: 
> When I turn on global auth

**Comment by cbeauch** [comment]
> @cbeauch what do you mean:
> 
> > When I turn on global auth
> 
> I got answered [here](https://airbytehq.slack.com/archives/C021JANJ6TY/p1725899280694249)
> 
> ```
> global:
>   auth:
>     enabled: true
> ```

```yaml
global:
  auth:
    enabled: true
```
From this doc: 
https://docs.airbyte.com/deploying-airbyte/integrations/authentication

**Comment by cbeauch** [comment]
> @cbeauch what do you mean:
> 
> > When I turn on global auth
> 
> I got answered [here](https://airbytehq.slack.com/archives/C021JANJ6TY/p1725899280694249)
> 
> ```
> global:
>   auth:
>     enabled: true
> ```

Yeah, that's me. Following this doc: https://docs.airbyte.com/deploying-airbyte/integrations/authentication

I think it might be the webapp trying to hit https://mydomain.airbyte.com/api/v1/users/get but is getting blocked. Looking into that right now

**Comment by cbeauch** [comment]
Yeah, all good. just had to whitelist the service IP for the api endpoint

**Comment by betizad** [comment]
@cbeauch How did you manage to resolve the issue? I'm facing the same problem.

**Comment by cbeauch** [comment]
> @cbeauch How did you manage to resolve the issue? I'm facing the same problem

The front-end pod will reach out the to domain address instead of using the internal pod address. In my case, I had to whitelist the cluster egress IP on the firewall for the Airbyte domain.

**Comment by dombegin** [comment]
@craigbloodworth we too have nginx (for SSL termination and more) in front of Airbyte and faced the same issue after the migration to abctl.

What seemed to do the trick was to overwrite the Origin header on the proxy request to make it look as a local request (i.e. not from our hostname).

`proxy_set_header Origin      "http://127.0.0.1:8000";`

Not really sure how safe it is, but at least with this temporary fix the frontend is working again

**Comment by craigbloodworth** [comment]
Thanks so much for the workaround @dombegin, I can confirm it's worked for me too.

@marcosmarxm I would suggest therefore that the --host flag in abctl isn't being respected
