### ISSUE TITLE
allow configuring a custom sync interval in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4520]
## Tell us about the problem you're trying to solve
I would like to be able to configure a number other than the UI provided defaults (say sync every 7 minutes)

**Comment by davinchia** [comment]
Related to #2170

**Comment by philippeboyd** [comment]
@sherifnada any news on this?

**Comment by davinchia** [comment]
Everyone is focused on Cloud now so this is likely to be pushed to next month. This is definitely on the roadmap though!

**Comment by cgardens** [comment]
duplicate of https://github.com/airbytehq/airbyte/issues/2170. something we are working on again.
