### ISSUE TITLE
NotificationService is not handling errors correctly.

### ISSUE THREAD

**Issue by Jamakase** [airbytehq/airbyte#4526]
## Enviroment
- **Airbyte version**:  0.26.4-alpha
- **OS Version / Instance**: macos
- **Deployment**: Docker 
- **Source Connector and version**:  ~
- **Destination Connector and version**: ~
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Selecting a new source connector

## Current Behavior
It was reported numerous times by different users that network errors ( 500 and etc ) are swallowed by UI and do not display a notification or any other type of info when it happens.

https://airbytehq.slack.com/archives/C01MFR03D5W/p1625210485374500

## Expected Behavior
At least an error notification should be fired when an error occurs.

**Comment by cgardens** [comment]
We are sure that this is happening on versions of the app that were released after the notification service was published, right? Just wanted to sanity check.
