### ISSUE TITLE
Unable to retrieve credentials in Linux

### ISSUE THREAD

**Issue by nihalvv** [airbytehq/airbyte#45347]
### What happened?

nihal@nihalga:~$ abctl local credentials
  INFO    Using Kubernetes provider:
            Provider: kind
            Kubeconfig: /home/nihal/.airbyte/abctl/abctl.kubeconfig
            Context: kind-airbyte-abctl
  ERROR   unable to inspect container: Error response from daemon: No such container: airbyte-abctl-control-plane
I have checked docker containers and pods. I've also changed the permissions 
sudo chmod 755 /home/nihal/.airbyte/abctl. 
Everything looks fine, but I'm getting this error.

### What did you expect to happen?

I expected to retrieve credentials. 

### Abctl Version

<details>

```console
$ abctl version version: v0.14.2
# paste output here
```

</details>

### Docker Version

Client: Docker Engine - Community
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:15:15 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.0 (165256)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### OS Version

Ubuntu 24.04 LTS

**Comment by bgroff** [comment]
Can you try running an `abctl local uninstall` then an `abctl local install` again?
