### ISSUE TITLE
User Request Limit Reached Error Despite Zero Call Count in X-App-Usage Header

### ISSUE THREAD

**Issue by namwelast** [airbytehq/airbyte#45385]
### Topic

User Request Limit Issue

### Relevant information

![img_v3_02ek_4d07fdd7-3c7e-4b1e-87e6-6ace713f86hu](https://github.com/user-attachments/assets/1d8b0c0c-09a4-4469-85da-5695e14f6a5f)
please help me

**Comment by marcosmarxm** [comment]
Closed as lack information. It looks is a connector problem, please open a connector issue if not please provide as much context, information and steps to reproduce the issue.
