### ISSUE TITLE
[source-rss] Problem with some specific URLs

### ISSUE THREAD

**Issue by Sebastien73** [airbytehq/airbyte#45389]
### Connector Name

source-rss

### Connector Version

1.0.17

### What step the error happened?

Configuring a new connector

### Relevant information

Hello everyone,

I would like to use the RSS connector, but not all URLs work with it, and I can't figure out what's causing the issue.

In the UI, when initializing the connector with the following URL:

    https://www.ledauphine.com/rss

I get the following error:
```
Configuration check failed
'Unable to connect to stream items - Request to https://www.ledauphine.com/rss/ failed with status code 404 and error message None'
```
I know that trailing slash is in log output, but it seems to be added by your connector ?

I tried using the feedparser library in a local Python script, and this URL does return data.
I tried using this two version of your connector : 1.0.1 and 1.0.17 -> Same result.

You can see the following screenshot for the result : 

![init_connector_1 0 17](https://github.com/user-attachments/assets/300d0b61-041d-4a6d-8b05-4cb469fa7cd0)

I have the problem with other URLs as well, you can see these in the following list : 

[https://feeds.a.dj.com/rss/RSSWorldNews.xml](https://feeds.a.dj.com/rss/RSSWorldNews.xml)
[https://www.france24.com/fr/rss](https://www.france24.com/fr/rss)
[https://www.france24.com/fr/europe/rss](https://www.france24.com/fr/europe/rss)
[https://www.france24.com/fr/france/rss](https://www.france24.com/fr/france/rss)
[https://www.nouvelobs.com/rss](https://www.nouvelobs.com/rss)
[https://www.la-croix.com/RSS/UNIVERS](https://www.la-croix.com/RSS/UNIVERS)
[https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml](https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml)

Thanks a lot.

### Contribute

- [ ] Yes, I want to contribute

**Comment by Sebastien73** [comment]
For information, some URLs no longer work. They worked and now I get the same error message when I retest the source

**Comment by marcosmarxm** [comment]
Thanks for reporting the issue @Sebastien73 RSS source is a community connector and it isn’t in the current roadmap for improvements. If you want to contribute fixing the issue please reach me out in Slack so I can provide you instructions to make the contribution.

**Comment by natikgadzhi** [comment]
@Sebastien73 a workaround: try adding `?` in the end of the URL so the CDK / requests library does not slap a slash to it. That should work.

**Comment by syspect-sec** [comment]
In the end, I have created a [pull request for this issue](https://github.com/airbytehq/airbyte/pull/69828).
