### ISSUE TITLE
[source-declarative-manifest] The manifest version is greater than the airbyte-cdk package version

### ISSUE THREAD

**Issue by xhensiladoda** [airbytehq/airbyte#45398]
### Helm Chart Version

0.551.0

### What step the error happened?

During the creation of a source from a custom connector created with the Builder UI.

### Relevant information

I can create the connector but I cannot create the source with it.

### Issue
Impossible to create a source with custom connector because of the following error:
```
jsonschema.exceptions.ValidationError: The manifest version 4.6.2 is greater than the airbyte-cdk package version (4.3.0). Your manifest may contain features that are not in the current CDK version.
```
The error is in the `main` container of the _manifest check_ pod creation. The image of the `main` container is: `airbyte/source-declarative-manifest:4.3.0`.

The version of the `airbyte-cdk` in the `airbyte-connector-builder-server` is `4.6.2`.
```
[airbyte@airbyte-connector-builder-server-57c558c554-zwc79 app]$ pip show airbyte-cdk
Name: airbyte-cdk
Version: 4.6.2
Summary: A framework for writing Airbyte Connectors.
Home-page: https://github.com/airbytehq/airbyte
Author: Airbyte
Author-email: contact@airbyte.io
License: MIT
Location: /home/airbyte/.pyenv/versions/3.10.14/lib/python3.10/site-packages
```

Airbyte Helm chart info

```
> helm show chart airbyte/airbyte
apiVersion: v2
appVersion: 0.64.3
dependencies:
[...]
description: Helm chart to deploy airbyte
name: airbyte
type: application
version: 0.551.0
```

I see new versions for`airbyte/source-declarative-manifest` have been released: https://hub.docker.com/r/airbyte/source-declarative-manifest/tags.
And that the latest source code changes refer to a new `airbyte-cdk`: https://github.com/airbytehq/airbyte/blob/e679191b54fc990916c9bdf7b34c03e298279953/airbyte-integrations/connectors/source-declarative-manifest/pyproject.toml#L20.

In addition, I tried to change the `airbyte-cdk` version from the Airbyte Builder UI and it seems there is a bug since after I change the version, the value is reverted to `4.6.2`. So whatever version I specify, it is always reverted to `4.6.2`.

![image](https://github.com/user-attachments/assets/1baeabce-3a52-4e22-93d9-9d012920cc6e)

I tried with another Helm chart, e.g. the previous version `0.524.0` and I could specify the version of `airbyte-cdk` correctly.

So it seems there is a bug with the current Helm chart Airbyte UI.

So I see two problems here:

**1. Why do we refer to an older image of `airbyte/source-declarative-manifest` that has an older `airbyte-cdk`?
2. Why can't we change the version of the `airbyte-cdk` from the Builder UI with Helm chart 0.551.0?**

### Relevant log output

```shell
Using AIRBYTE_ENTRYPOINT: python /airbyte/integration_code/main.py
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 91, in run
    handle_command(args)
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 46, in handle_command
    handle_remote_manifest_command(args)
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 69, in handle_remote_manifest_command
    source = create_manifest(args)
  File "/airbyte/integration_code/source_declarative_manifest/run.py", line 86, in create_manifest
    return ManifestDeclarativeSource(config.get("__injected_declarative_manifest"))
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 68, in __init__
    self._validate_source()
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py", line 206, in _validate_source
    raise ValidationError(
jsonschema.exceptions.ValidationError: The manifest version 4.6.2 is greater than the airbyte-cdk package version (4.3.0). Your manifest may contain features that are not in the current CDK version.
```

**Comment by descampsk** [comment]
I got the same issue with helm chart 1.0.0.

The container has the following image:

```
  main:
    Container ID:  containerd://f00b616717e9edadd9ddc8373f8b4f3bdbd6b799e225a1f265bf97c201fb6ee0
    Image:         airbyte/source-declarative-manifest:4.3.0
```

**Comment by descampsk** [comment]
Possible workaround:

```SQL
SELECT
  id
FROM
  "public"."actor_definition_version"
INNER JOIN
  "public"."actor_definition"
ON
  actor_definition.id = actor_definition_version.actor_definition_id
WHERE
  docker_repository = 'airbyte/source-declarative-manifest'
  AND name = '<NAME>';


UPDATE
  "public"."actor_definition_version"
SET
  docker_image_tag='4.6.2'
WHERE
  id = '<ID_RETRIEVED>';
```

**Comment by descampsk** [comment]
This workaround does not seem to work a long time. When Airbyte pod restart, it seems to reset the docker_image_tag to 4.6.2...

**Comment by natikgadzhi** [comment]
Can you check a fresh abctl install for 1.0+? This should not happen, you should see source declarative manifest and `version` tag to be around 5.7.5 at the moment.

**Comment by descampsk** [comment]
```
SELECT * FROM
  "public"."declarative_manifest_image_version" LIMIT 1000;
```

does not have a 5 major

![Image](https://github.com/user-attachments/assets/5d998d7f-43fa-4b2f-b58a-8b05051ccbba)

**Comment by descampsk** [comment]
I had to do 
```sql
INSERT INTO
  declarative_manifest_image_version
VALUES
  (5, '5.7.5', DEFAULT, DEFAULT, 'sha256:4832cc13b262b4cae4ba72b07da544e6ee2f5d216b7147483480d5ebc5d0d7ca');
```
