### ISSUE TITLE
[source-klaviyo] Using retired API revision for campaigns and profiles

### ISSUE THREAD

**Issue by gwenhoogeboom** [airbytehq/airbyte#45412]
### Connector Name

source-klaviyo

### Connector Version

2.10.4

### What step the error happened?

None

### Relevant information

It seems that the Klaviyo connector is using a deprecated api revision for the campaigns and profiles steam that are about to retire. Could someone please update the revision version?

Campaigns
- Endpoint: /api/campaigns
- Revision: 2023-06-15
- Retires: in 275 days

Profiles
- Endpoint:/api/profiles
- Revision: 2023-02-22
- Retires: in 162 days

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Thanks for bringing this to our attention. I included the issue to the connector team and they will eventually update the API to a newer version.

**Comment by natikgadzhi** [comment]
We have @DanyloGL who is looking over deprecations — we won't let it expire. ;)

**Comment by gwenhoogeboom** [comment]
Please reopen this issue, the revision is still used and will retire in less than 2 months

**Comment by DanyloGL** [comment]
@gwenhoogeboom hi, we have separate ticket for Klaviyo API versions update tracking.
Here are the schedule for used API versions sunset:

- Stream Profile: API version 2023-02-22, sunset date: 2/22/2025
- Stream Campaigns: API version 2023-06-15, sunset date: 6/15/2025
- Other streams: API version 2023-10-15 , sunset date: 10/15/2025

Thanks!

**Comment by tuday2** [comment]
> [@gwenhoogeboom](https://github.com/gwenhoogeboom) hi, we have separate ticket for Klaviyo API versions update tracking. Here are the schedule for used API versions sunset:
> 
> * Stream Profile: API version 2023-02-22, sunset date: 2/22/2025
> * Stream Campaigns: API version 2023-06-15, sunset date: 6/15/2025
> * Other streams: API version 2023-10-15 , sunset date: 10/15/2025
> 
> Thanks!

Where is this ticket?

**Comment by natikgadzhi** [comment]
@DanyloGL if it's in the internal repo, it's OK to copy&paste to the public one so folks have clarity on it. 

If it's in 2 months, we should make sure this work it assigned. Ping me if you're under-resourced on this! I think community devs should be a good fit.

**Comment by tuday2** [comment]
> [@DanyloGL](https://github.com/DanyloGL) if it's in the internal repo, it's OK to copy&paste to the public one so folks have clarity on it.
> 
> If it's in 2 months, we should make sure this work it assigned. Ping me if you're under-resourced on this! I think community devs should be a good fit.

@natikgadzhi  Just to clarify it's less then 2 months, its 46 days from now (2/22/2025). Thank you!!

**Comment by DanyloGL** [comment]
@natikgadzhi, sure here is the link to the [issue](https://github.com/airbytehq/airbyte-internal-issues/issues/6572)

**Comment by SvenInsightFirst** [comment]
Hi @natikgadzhi @DanyloGL We're slowly closing in on the first sunset date (2/22/2025). Could you update us on the current status of this issue?

**Comment by spot-jon** [comment]
> Hi [@natikgadzhi](https://github.com/natikgadzhi),
> 
> According to your comment in [this issue](https://github.com/airbytehq/airbyte/issues/50941), you were expecting to ship a new version last week. I might be wrong, but I don't see any version yet that includes these changes. Are you still on track for the first sunset date later this week? We would really like to know, as we're running Airbyte self-hosted and would thus need to upgrade the relevant connector manually.

I'm in the same boat -- and we are continually getting warnings from Klaviyo (and my client)

**Comment by tuday2** [comment]
> Hi [@natikgadzhi](https://github.com/natikgadzhi),
> 
> According to your comment in [this issue](https://github.com/airbytehq/airbyte/issues/50941), you were expecting to ship a new version last week. I might be wrong, but I don't see any version yet that includes these changes. Are you still on track for the first sunset date later this week? We would really like to know, as we're running Airbyte self-hosted and would thus need to upgrade the relevant connector manually.

Yes my client keeps getting warnings from Klaviyo, we are very close to sunset date at this point.
