### ISSUE TITLE
413 when creating connection

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [airbytehq/airbyte#45423]
### What happened?

When creating a connection between a Postgres source and Snowflake destination, I get a 413 error. I know this is not an adapter issue, because I have configured the same type of connection in this instance without issues. The only difference between the 2 connections is that I have added a replication slot and publication to the Postgres source. 

I have also edited the nginx.conf file at /etc/nginx to have this line in the http section: `client_max_body_size 0;`, which did not change anything, even after restarting nginx. 

### What did you expect to happen?

The connection to be created successfully

### Abctl Version

<details>

```console
$ abctl version
# version: v0.12.2
```

</details>

### Docker Version

<details>

```console
$ docker version
# Client: Docker Engine - Community
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:50:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       f9522e5
  Built:            Mon Aug 12 11:50:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

### OS Version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</details>

**Comment by marcosmarxm** [comment]
Hello @jeremy-thomas-roc can you share the complete error message/payload?
Are you able to create other connections maybe using (Source Faker / e2e test destination)?

**Comment by jeremy-thomas-roc** [comment]
The only error I get is this: 
![image](https://github.com/user-attachments/assets/9b3d2681-f6c8-4488-8a63-80af9b1c383f)

I can create other connections, I have a similar Postgres -> Snowflake connection configured already.

**Comment by marcosmarxm** [comment]
Can yo check the Network tab -> Developer Tools? It can provide a more complete response from the request.

**Comment by jeremy-thomas-roc** [comment]
![image](https://github.com/user-attachments/assets/258cf261-857d-45f5-99ad-df3055633fea)

There's the request/response details, it's a pretty generic 413 error for request too large.

**Comment by alenoir** [comment]
Same here with update google analytics connection and multiple propety_ids. In request payload my syncCatalog -> stream contain 1481 streams, I thinks it's because each property ids create streams (cf https://github.com/airbytehq/airbyte/issues/42464)
![CleanShot 2024-09-13 at 09 02 46](https://github.com/user-attachments/assets/f4fbe8a9-3940-44a2-8162-4d1b2e7a8382)

**Comment by alxgrh** [comment]
I have the same issue. Error occurs if source DB contains many tables, 1123 in my case. This issue was reported many times
https://github.com/airbytehq/airbyte/issues/4086
https://github.com/airbytehq/airbyte/issues/18822
https://github.com/airbytehq/airbyte/issues/22631


I can connect to the docker container via 
```
docker exec -it airbyte-abctl-control-plane bash
```

But I'm not sure how to edit and reload nginx conf. I see nginx in a processes list
```
root@airbyte-abctl-control-plane:/# ps axu | grep nginx.conf
statd       6737  0.0  0.1 122540 12248 ?        S    Sep12   0:00 nginx: master process /usr/bin/nginx -c /etc/nginx/nginx.conf
```
but neither config or binary files exist on that path. It looks like it's running inside some container environment (container inside container!)

Does anyone know how to restart nginx in Airbyte container?

**Comment by alxgrh** [comment]
I've solved this problem, having reinstalled the Airbyte with docker-compose - https://docs.airbyte.com/deploying-airbyte/docker-compose

**Comment by jeremy-thomas-roc** [comment]
> I've solved this problem, having reinstalled the Airbyte with docker-compose - https://docs.airbyte.com/deploying-airbyte/docker-compose

Do you mean it worked out-of-the-box, or you were then able to edit the nginx.conf to get it to work correctly?

**Comment by alxgrh** [comment]
> > I've solved this problem, having reinstalled the Airbyte with docker-compose - https://docs.airbyte.com/deploying-airbyte/docker-compose
> 
> Do you mean it worked out-of-the-box, or you were then able to edit the nginx.conf to get it to work correctly?

It worked out-of-the-box. I didn't do any additional steps.

**Comment by japerry911** [comment]
adding annotation to `ingress-abctl` namespace worked for me -

`kubectl edit ingress ingress-abctl -n airbyte-abctl --kubeconfig ~/.airbyte/abctl/abctl.kubeconfig`

then add under metadata (50m = 50 mb, if you need more add higher number, etc..)...

```yaml
metadata:
  annotations:
     nginx.ingress.kubernetes.io/proxy-body-size: "50m" 
```

Should work momentarily.. Just a temporarily fix though, I don't know if this is best method, but works for me.

**Comment by bgroff** [comment]
@japerry911 your method is the correct method. Airbyte has also adjusted these limits in the close PR above.
