### ISSUE TITLE
Refactor source database creation

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#4547]
This ticket is a result of PR review #4123.

## Tell us about the problem you're trying to solve
To the database implemented were added information about used configs. Due to the current implementation, they were added using setters instead of a constructor.
The root cause of this decision is the significant amount of changes required for that.

## Describe the solution you’d like
Refactor current implementation in order to put config objects as constructor input params.

**Comment by sherifnada** [comment]
@DoNotPanicUA can we do this once we've tackled more user-impacting issues in the sprint like #4487 ?
