### ISSUE TITLE
Custom Sync frequencies

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#4549]
## Tell us about the problem you're trying to solve
Would be nice to have custom sync frequencies. **_Sometimes you don't need to sync something every day or few hours, especially if it's a full overwrite sync._** We should have the option to set custom frequencies (Every X Y) such as **Every 2 days** or **Every week**, etc.

Currently we're limited to 

- Manual
- Every 5 min
- Every 15 min
- Every 30 min
- Every hour
- Every 2 hours
- Every 3 hours
- Every 6 hours
- Every 8 hours
- Every 12 hours
- Every 24 hours

## Describe the solution you’d like
Have a custom form where we specify the custom frequencies. **Every N Hours/Days/Weeks**

**Comment by rparrapy** [comment]
Perhaps we could support cron syntax on top of the currently available options?

**Comment by ChristopheDuong** [comment]
Yes, it'd be related to https://github.com/airbytehq/airbyte/issues/2170

**Comment by marcosmarxm** [comment]
Thanks for opening this @philippeboyd! I'm closing because is duplicated with #2170
