### ISSUE TITLE
Google AdWords API is deprecated to use Google Ads API

### ISSUE THREAD

**Issue by jaimefr** [airbytehq/airbyte#4556]
## Enviroment
- **Airbyte version**:  0.25.0-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Google AdWords 0.2.5
- **Destination Connector and version**: Snowflake
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
Not able to set up a new connection because tests fails

## Expected Behavior
New connection tests OK

## Logs
No logs available

<details>
<summary>LOG</summary> 

```

No logs because I can't set up the connection.

```

When trying to set up the connection, the test shows the message: [QuotaCheckError.INVALID_TOKEN_HEADER @ ; trigger:'New developers must use the Google Ads API: https://developers.google.com/google-ads/api/docs/start']

</details>

## Steps to Reproduce
1. Create a new Google AdWords source credentials after April 28
2. Try to set up a new source using those credentials

![Screenshot 2021-07-05 at 22 37 51](https://user-images.githubusercontent.com/20720305/124517237-c5284f00-dde3-11eb-832a-7784ea0d57ca.png)

Based on this information, any new developer with tokens issued after April 28 are not able to use the AdWords API, we need to use de Google Ads API: https://developers.google.com/adwords/api/docs/guides/signup?hl=en

**Comment by marcosmarxm** [comment]
@sherifnada I think this can be solved by https://github.com/airbytehq/airbyte/issues/3457.

**Comment by jaimefr** [comment]
> @sherifnada I think this can be solved by #3457.

Yes, I think this issue is duplicated, sorry, so this one can be closed.

I have created a PR to add this info in the Documentation: https://github.com/airbytehq/airbyte/pull/4561

**Comment by sherifnada** [comment]
@jaimefr pushing the Google Ads connector into beta is a goal of ours this month. Track the progress here: #4420

**Comment by jaimefr** [comment]
Thanks @sherifnada you can close this issue.
