### ISSUE TITLE
Wrike missing from list of sources

### ISSUE THREAD

**Issue by satasoy-wuersch** [airbytehq/airbyte#45596]
### Connector Name

source-wrike

### Connector Version

0

### What step the error happened?

Other

### Relevant information

Wrike is no longer listed as a source

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
The documentation says Wrike is only available in OSS: https://docs.airbyte.com/integrations/sources/wrike

It is listed in OSS:
<img width="626" alt="image" src="https://github.com/user-attachments/assets/8a7870f6-56c4-45cd-81c7-3bc05fe0b2f4">

**Comment by satasoy-wuersch** [comment]
I missed that somehow, thank you. I haven't set up the OSS version yet, was on free trial of the cloud version (it disappeared from there).
