### ISSUE TITLE
Troubleshooting increase batchSize and add section in database source

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4569]
### Tell us about the documentation you'd like us to add or update.
Some users are trying to sync 100Gb+ tables and sometimes got timeout exceptions. One way to help them is guiding them how to increase the batchSize. Issue https://github.com/airbytehq/airbyte/issues/4314 try to solve this making the batchSize configurable but this doc can be a workaround for now.

[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1625466487438700)

### If applicable, add links to the relevant docs that should be updated
- [Link to relevant docs page](https://docs.airbyte.io)

**Comment by ilijaNL** [comment]
Bump
