### ISSUE TITLE
Ability to deploy airbyte to heroku

### ISSUE THREAD

**Issue by barnaby** [airbytehq/airbyte#457]
## Tell us about the problem you're trying to solve
I'd like to be able to easily deploy airbyte to heroku

## Describe the solution you’d like
I'd like a [deploy to heroku button](https://devcenter.heroku.com/articles/heroku-button) on the main repo readme page.

**Comment by michel-tricot** [comment]
Thank Barnaby. This is going to be available soon.

**Comment by jrhizor** [comment]
After looking into this more, it looks like Heroku doesn't support functionality we need to run Airbyte. 

There are two problems here:

1. Heroku doesn't offer persistent disk storage
We do have https://github.com/airbytehq/airbyte/issues/1494 to address this.

2. Heroku doesn't support running containers within Heroku.

Heroku would need to support one of the following to allow us to do this:
- Kubernetes deployments
- `docker-compose`
- Run VMs
- Running Docker-in-Docker

The other alternative would be to use non-containerized integrations which negates one of the main benefits of Airbyte.

I'm going to close this and mark as "won't do" for now. We'd love to be able to support a one click install like this for Heroku, and we should definitely reopen this if they ever add the features necessary to run Airbyte.

**Comment by tomtaylor** [comment]
FWIW, Heroku does allow running containers. Some documentation here: https://devcenter.heroku.com/articles/container-registry-and-runtime

**Comment by tommyh** [comment]
@jrhizor since #1494 was recently closed and heroku’s support for containers, is this feature possible?

**Comment by sherifnada** [comment]
@tommyh @tomtaylor the need here is to have a dockerized application launch other containers i.e: connectors when a sync is run. Does docker support one docker application launching another docker application?

**Comment by jrhizor** [comment]
@sherifnada it would also either need to be able to run multiple containers in a private network or add auth to each internal component (including launched connectors)
