### ISSUE TITLE
Make "upgrade all" button resilient to deleting connectors from index

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4570]
## Enviroment
- **Airbyte version**:  latest
- **Severity**: High
- **Step where error happened**: Pressing the "upgrade all" button in Airbyte's admin UI

## Current Behavior
server throws 500

from slack DM: 

> as far as I can tell this triggers calling /api/v1/source_definitions/update for each connector (e.g. `{"sourceDefinitionId":"932e6363-d006-4464-a9f5-102b82e07c06"})`. Problem is this is returning 500 on at least twilio-singer source throwing a NPE and failing the upgrade all. @ Davin pointed out twilio singer is deprecated so it seems possible it's the deprecated connectors that would throw 500s and cause this

## Expected Behavior
succeeds

## Logs
no logs available 

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. click update all button in UI with an instance whose connector index contains a connector removed from the UI 
2.
3.

**Comment by davinchia** [comment]
Tracked this down to:
```
2021-07-09 07:41:08 ERROR i.a.s.e.InvalidInputExceptionMapper(infoFromConstraints):50 - {workspace_app_root=/tmp/workspace/server/logs} - ===== error:
airbyte-server     | javax.validation.ConstraintViolationException: updateSourceDefinition.arg0.dockerImageTag: must not be null
airbyte-server     | 	at org.glassfish.jersey.server.validation.internal.DefaultConfiguredValidator.onValidate(DefaultConfiguredValidator.java:159) ~[jersey-bean-validation-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.validation.internal.ValidationInterceptorExecutor.proceed(ValidationInterceptorExecutor.java:90) ~[jersey-bean-validation-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.validation.internal.DefaultConfiguredValidator.validateResourceAndInputParams(DefaultConfiguredValidator.java:122) ~[jersey-bean-validation-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:114) ~[jersey-server-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
airbyte-server     | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
```

**Comment by davinchia** [comment]
The webapp expects the an image tag to appear in the latest list. Since this connector has been deprecated (and thus deleted), this tag is blank. The frontend sends a blank tag to the api, causing this error.

**Comment by davinchia** [comment]
This can be replicated by checking out the 0.27.0-alpha version. This version contains `twilio-singer` that has now been deprecated. Clicking on update all gives us the same error.
