### ISSUE TITLE
New destination: Elasticsearch

### ISSUE THREAD

**Issue by rigobcastro** [airbytehq/airbyte#4577]
* Which source and which destination?

The first version could be integrating with popular databases

![Airbyte Elastic](https://user-images.githubusercontent.com/1006483/124660523-ed5b9080-de6b-11eb-9463-ffb10a1d7507.png)

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

Elasticsearch +6 or +7 support for Cloud and OpenSource versions. 

* Which team in your company wants this integration, what for? This helps us understand the use case.

Data and Dev teams, Elasticsearch provides a powerful layer for search and analytics purposes. Similar to https://docs.airbyte.io/integrations/destinations/meilisearch

* How often do you want to run syncs?

near-realtime is preferred in most of cases.

* What are you considering doing if you don’t have this integration through Airbyte?

Alternatives

Source database -> Debezium Source connector -> Kafka -> Elasticsearch sink connector -> Elasticsearch

Source database -> Debezium Server -> Pubsub/Kinesis -> Lambda/Cloud Function -> Elasticsearch

(I like this alternative)
Source database -> Airbyte -> Pub/Sub -> Cloud function -> Elasticsearch

Source database -> Logstash JDBC Plugin -> Elasticsearch

**Comment by sherifnada** [comment]
@rigobcastro thanks for creating this request! What is the UX you want for interacting with the connector?  i.e: What inputs/configuration do you want to give it, and how do you want the output to look like? Should all input Airbyte streams be written to the same place, different places, etc.?

**Comment by rigobcastro** [comment]
@sherifnada I updated the image including the UI possible targets. Let me create a some diagram with e2e use cases to explain better your questions.

**Comment by edvinasbartkus** [comment]
At [Argyle](https://argyle.com) we use Airbyte with source MySQL and destination BigQuery. It works like charm. We would love to extend it by adding specific tables being exported to specific ElasticSearch indices. In our perspective, UX would allow to choose which tables to export and to what indices to export the data (one-to-one matching).

**Comment by michel-tricot** [comment]
Someone from Elastic mentioned that we should be using the new client: https://github.com/elastic/elasticsearch-java when we start implementing this connector

**Comment by rigobcastro** [comment]
Thanks guys! Let me know if you need something from me.

**Comment by olivermeyer** [comment]
> Someone from Elastic mentioned that we should be using the new client: https://github.com/elastic/elasticsearch-java when we start implementing this connector

I'm not sure whether something similar exists for the Java client, but I just wanted to point out that the latest versions (>=7.14) of the Python client for ElasticSearch block any "non-official" ES clusters. This affects users of AWS OpenSearch and any other hosted ES service. If this also affects the Java client, I don't know how this should be handled (one generic ES connector for all providers vs or one connector per provider), but worth keeping in mind.

**Comment by marcosmarxm** [comment]
This was implemented in #7005
