### ISSUE TITLE
Increase Salesforce integration test account API quota

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4579]
## Tell us about the problem you're trying to solve
The Salesforce integration test account we use does not have a lot of bandwidth for repeatedly running tests. 

## Describe the solution you’d like
Higher API quota. We should investigate how to do this. Also we should mention in our docs how we did it in order to help users who may have the same problem.

**Comment by cheyura** [comment]
@sherifnada Currently we have developer edition of salesforce that allows 15000 APIs daily with severe restrictions for tech support. Thus, probably we should wait for response for a long time. 
The problem could be solved in 3 ways:
1. The most easy but requires verification - change 'Api-type' from 'rest' to 'bulk'. Batches will allow to pull 150,000,000 records (15,000 batches x 10,000 records per batch maximum)
2.  Wait for response form support and increase quota for Developer edition (it may take long time with high probability of failure, i wrote in simple chat, no access to fast support or email)
3.  Upgrade plan. More  information https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_api.htm. For example Enterprise edition will allow to do 100,000 + (number of licenses x calls per license type) calls
