### ISSUE TITLE
Cleanup RAW tables on destination when doing a Full Refresh - Overwrite

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#4581]
## Tell us about the problem you're trying to solve
When doing a `Full Refresh - Overwrite` from MSSQL to Snowflake (for instance; can be any roughly any source/destination supporting `Full Refresh - Overwrite`), we end up with RAW tables in the destination that are technically useless once the data has been normalized. It essentially doubles the spaces needed.

## Describe the solution you’d like
When doing a `Full Refresh - Overwrite` and if Normalization is checked, we should have the ability to cleanup (delete) the RAW tables in the destination (`_AIRBYTE_RAW_<table_name>`)

## Describe the alternative you’ve considered or used
Manually deleting all RAW tables in destination

**Comment by marcosmarxm** [comment]
I think for some use cases people want to keep the raw tables. Maybe adding a option in the connection setting page to execute this automatically. Other solution is to have a standard custom dbt operator to execute this. WDYT @philippeboyd

**Comment by ashishgupta-97065** [comment]
+1 would be great to have the ability to select whether I want the raw table or not. In some cases it's an unnecessary overload on disk and extra management when connecting db to analytics tools

**Comment by ChristopheDuong** [comment]
related to https://github.com/airbytehq/airbyte/issues/4521

**Comment by cgardens** [comment]
This should be done!
