### ISSUE TITLE
Documentation: Compare Airbyte to is missing image

### ISSUE THREAD

**Issue by AetherUnbound** [airbytehq/airbyte#4592]
### Tell us about the documentation you'd like us to add or update.

It looks like there's an image missing from the Fivetran vs Airbyte doc! Here's the link to the line: https://github.com/airbytehq/airbyte/blame/master/docs/faq/differences-with/fivetran-vs-airbyte.md#L5

The current link (https://airbyte.io/wp-content/uploads/2021/01/Airbyte-vs-Fivetran.png) seems to be moved permanently and just redirects to the main site. I tried poking around the repo a bit but wasn't able to find a similar image.

**Comment by marcosmarxm** [comment]
Thanks @AetherUnbound looks this is happening to all comparisons! So I updated the title.

**Comment by AetherUnbound** [comment]
Oh goodness! I didn't think to check the other ones. Thanks!

**Comment by marcosmarxm** [comment]
@avaidyanatha could you take a look, probably this happened because of the new website.

@AetherUnbound https://dzone.com/articles/the-state-of-open-source-data-integration-and-etl here you can check the missing image :D
