### ISSUE TITLE
Gather several sections in one icon on left column layout

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#4593]
See suggestions of design: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26418%3A84767

cc @cgardens @Jamakase 
Could be done at the same time as https://github.com/airbytehq/airbyte/issues/3673

**Comment by timroes** [comment]
Closing this for now, since rather old and the linked figma seems to no longer exists. Please feel free to update and reopen if still required.
