### ISSUE TITLE
🚀Source Amazon SP API: create dev app and sandbox credentials

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4595]
## Tell us about the problem you're trying to solve
For the Amazon SP source, we should create sandbox credentials as described [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#the-selling-partner-api-sandbox) and add them to lastpass. 

This will be in preparation for https://github.com/airbytehq/airbyte/issues/4594

**Comment by vovavovavovavova** [comment]
The account was created; the config is stored in LastPass under name `AWS amason sp api selling-partner-api config`
