### ISSUE TITLE
[connector-request] AdRoll

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45960]
This is a **suggestion** to create a connector for **AdRoll** using the UI Connector Builder.
The website for the connector is https://www.adroll.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by ombhardwajj** [comment]
@marcosmarxm  assign this to me please !

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm 
I've raised a PR please check it out !! #46514

**Comment by ombhardwajj** [comment]
# Streams Added
1) [Assets By Eid](https://developers.adroll.com/docs/adroll-ad-api/1/routes/assets/%7Beid%7D/get)
2) [Segments](https://developers.adroll.com/docs/adroll-audience-api/1/routes/segments/get)
3) [AdGroup](https://developers.adroll.com/docs/adroll-campaign-api/1/routes/adgroup/get)
4) [Campaign](https://developers.adroll.com/docs/adroll-campaign-api/1/routes/campaign/get)
5) [Strategy](https://developers.adroll.com/docs/adroll-campaign-api/1/routes/strategy/get)
6) [All Strategies](https://developers.adroll.com/docs/adroll-campaign-api/1/routes/strategy/all/get)
7) [GeoTarget](https://developers.adroll.com/docs/adroll-geotarget-api/1/overview)
8) [Advertisable](https://developers.adroll.com/docs/adroll-organization-api/1/routes/advertisable/get/get)
9) [Active pixels for an advertiseable](https://developers.adroll.com/docs/adroll-organization-api/1/routes/advertisable/get_pixel/get)
10) [Consent Banner Config for an Advertisable](https://developers.adroll.com/docs/adroll-organization-api/1/routes/consent_banner/get/get)
11) [Pixel](https://developers.adroll.com/docs/adroll-organization-api/1/routes/pixel/get/get)
12) [All segments with a pixel](https://developers.adroll.com/docs/adroll-organization-api/1/routes/pixel/get_segments/get)

Just to make it clear , I was getting errors for these streams so they havent been added 
1) [Ads](https://developers.adroll.com/docs/adroll-ad-api/1/routes/ads/get)   ---->INVALID SCHEMA 
2) [Ad by EId](https://developers.adroll.com/docs/adroll-ad-api/1/routes/ads/%7Beid%7D/get).  ---->USER MUST BE ADMIN 

3) [Assets](https://developers.adroll.com/docs/adroll-ad-api/1/routes/assets/get).  ---->INVALID SCHEMA 
4) [Segment by EId](https://developers.adroll.com/docs/adroll-audience-api/1/routes/segments/%7Bsegment_eid%7D/get) ---->Error 500 something went wrong 

P.S. I tried to get around with these , but I was not successful

**Comment by ombhardwajj** [comment]
Update : I've added 5 new streams !!
We can now also fetch All Campaigns , AdGroups and Ads !!

**Comment by marcosmarxm** [comment]
Awesome!
