### ISSUE TITLE
[connector-request] BallotReady

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45968]
This is a **suggestion** to create a connector for **BallotReady** using the UI Connector Builder.
The website for the connector is https://www.ballotready.org.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by parthiv11** [comment]
@marcosmarxm  https://developers.civicengine.com/docs/api/v1

please can you let us know which endpoints are required in it

**Comment by marcosmarxm** [comment]
All
<img width="326" alt="image" src="https://github.com/user-attachments/assets/1d662705-41d1-49ac-9507-baef3a419f83">

**Comment by yellow-raven** [comment]
It looks like the REST API is being deprecated. Wouldn't it be wiser to map the GraphQL API?
![Image](https://github.com/user-attachments/assets/3bb4318b-51c6-420e-b522-9e5b56993c26)

**Comment by vantadata-lmorgan** [comment]
@marcosmarxm I'm willing to pick this up focusing on the GraphQL API, thoughts?

**Comment by marcosmarxm** [comment]
The connector builder doesn't support GraphQL API @vantadata-lmorgan so I'm going to close this issue to not cause problem for trying to implement it. Please select another issue from the list!
