### ISSUE TITLE
[connector-request] FreightView

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45989]
This is a **suggestion** to create a connector for **FreightView** using the UI Connector Builder.
The website for the connector is https://www.freightview.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm 
I wish to start working on this!
PR already submitted for #45960

**Comment by parthiv11** [comment]
@ombhardwajj I want to just inform your, I tried and getting in OAuth authorization.

I debugged and found that problem is with `request` sent by UI builder and having header `"Content-Length": "157", ` which is causing error


**Request**
```json
{
  "url": "https://api.freightview.com/v2.0/auth/token",
  "body": "grant_type=client_credentials&client_id=****&client_secret=****",
  "headers": {
    "User-Agent": "python-requests/2.32.3",
    "Accept-Encoding": "gzip, deflate",
    "Accept": "*/*",
    "Connection": "keep-alive",
    "Content-Length": "157",
    "Content-Type": "application/x-www-form-urlencoded"
  },
  "http_method": "POST"
}
```


**Reposnse**
```json
{
  "status": 401,
  "body": {
    "name": "UNAUTHORIZED",
    "message": "Invalid credentials.",
    "requestId": "1603119b-7359-42b7-9018-********"
  },
  "headers": {
  }
}



@marcosmarxm

**Comment by ombhardwajj** [comment]
I think you are right @parthiv11 
I am getting the same error even with POSTMAN
Therefore I wont be able to work on this @marcosmarxm

**Comment by parthiv11** [comment]
I think should work in postman, can you share request you used @ombhardwajj

**Comment by ombhardwajj** [comment]
Sent a POST Req at `https://api.freightview.com/v2.0/auth/token`
With Body : 
x-www-form-urlencoded
client_id : xxxxxx 
client_secret  : xxxx 
grant_type : client_credentials
@parthiv11

**Comment by parthiv11** [comment]
@marcosmarxm please checkout this issue

**Comment by marcosmarxm** [comment]
Do you want to give a try @parthiv11 ? Sorry won't be able to help debugging, if it isn't possible to implement the connector using the builder please select another issue.

**Comment by parthiv11** [comment]
it is possible but, as per my debugging UI builder have problem handler this OAuth.

more specifically problem is in mismatch of `Content-Length": "157",` with actual length.

so you can inform Builder team about this

**Comment by marcosmarxm** [comment]
I'm going to check next week.

**Comment by parthiv11** [comment]
@marcosmarxm done this, assign this to me
