### ISSUE TITLE
[connector-request] Expensify

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45987]
This is a **suggestion** to create a connector for **Expensify** using the UI Connector Builder.
The website for the connector is https://www.expensify.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by Harmaton** [comment]
Please assign this issue to me @marcosmarxm

**Comment by Harmaton** [comment]
Hello @marcosmarxm , according to expensify's documentation, they use a static url endpoint [endpoint](https://integrations.expensify.com/Integration-Server/ExpensifyIntegrations) , 

The endpoints are defined in the urlencoded body 

1. Report Exporter
2. Report Downloader
3. Expense Creator
4. Report Creator  
5.

Greenlight ?

**Comment by Harmaton** [comment]
Also, I am having a problem working with the url encoded body, could you by any chance have a reference on working with jinja macro url form encoded body as per this [documentation](https://documenter.getpostman.com/view/28050470/2sA35D74CW#59162d63-c4c3-42f5-a49f-5394d4ba8d53). It would help. Thanks
