### ISSUE TITLE
Source MySQL: SSL authentication certificate import

### ISSUE THREAD

**Issue by ronnyrit** [airbytehq/airbyte#4599]
## Tell us about the new connector you’d like to have
* Which source and which destination? Source MySQL
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB?  No

## Describe the context around this new connector
* Which team in your company wants this integration, what for? To connect Google Cloud SQL (MySQL) that require SSL Certificate import
* How often do you want to run syncs? 1 hours

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte? Turn off SSL but use internal IP

**Comment by potatozerg** [comment]
@sherifnada Hi Sherif, is it possible to provide an estimate (a rough one would be great) on this?

**Comment by pierre-b** [comment]
Hi guys, in order to connect a Singlestore DB cluster (MySQL driver) I also need this SSL support with import of private key + cert + CA.
I don't have any viable workaround for this at the moment.
Thanks

**Comment by sherifnada** [comment]
Hi everyone, currently bandwidth constrained on supporting this at the moment. Hopefully we can pick this up next week, hopefully ship by mid august at most.

**Comment by pierre-b** [comment]
Thanks @sherifnada for the update!
