### ISSUE TITLE
[connector-request] GetFeedback

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45992]
This is a **suggestion** to create a connector for **GetFeedback** using the UI Connector Builder.
The website for the connector is https://www.getfeedback.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by abhi8960git** [comment]
hey @marcosmarxm  i would like to work on this assign this to me.

**Comment by jaswal-shubham** [comment]
hey @marcosmarxm Please assign this issue to me

**Comment by marcosmarxm** [comment]
Unassigned because no updates.

**Comment by Aliya-Tariq** [comment]
Please assign this issue to me

**Comment by marcosmarxm** [comment]
Hello @Aliya-Tariq the event has ended, do you wanna still implement this connector?

**Comment by Aliya-Tariq** [comment]
Yesa

**Comment by marcosmarxm** [comment]
All yours!
