### ISSUE TITLE
[connector-request] Google Business Profile

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45994]
This is a **suggestion** to create a connector for **Google Business Profile** using the UI Connector Builder.
The website for the connector is https://www.google.com/business.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by bala-ceg** [comment]
@marcosmarxm can i work on this issue, since i completed my last one

**Comment by bala-ceg** [comment]
@marcosmarxm, I got the below error while trying the google business. I am trying to resolve it . In the meanwhile can i be assigned with a new issue?
'''
HttpError 429 when requesting https://mybusinessaccountmanagement.googleapis.com/v1/accounts?alt=json returned "Quota exceeded for quota metric 'Requests' and limit 'Requests per minute' of service 'mybusinessaccountmanagement.googleapis.com' for consumer 'project_number:437339952263'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_location': 'global', 'service': 'mybusinessaccountmanagement.googleapis.com', 'quota_metric': 'mybusinessaccountmanagement.googleapis.com/default_requests', 'quota_limit': 'DefaultRequestsPerMinutePerProject', 'consumer': 'projects/437339952263', 'quota_limit_value': '0'}}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Request a higher quota limit.', 'url': 'https://cloud.google.com/docs/quotas/help/request_increase'}]}]">
'''

**Comment by bala-ceg** [comment]
Hi @marcosmarxm,
For setting up Google Business API,  it seems we need to get approval from google business team and it is a long process. 
Can i try a connector for [Youtube Data API](https://developers.google.com/youtube/v3/guides/implementation). 
Airbyte currently supports [youtube-analytics](https://docs.airbyte.com/integrations/sources/youtube-analytics), there is mention about support for YouTube Data API is Coming soon

**Comment by marcosmarxm** [comment]
You can give a try, please open a new issue for Youtube explaining what endpoints you're going to implemnet and why it is different from the existing one.
