### ISSUE TITLE
[connector-request] Google Calendar

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45995]
This is a **suggestion** to create a connector for **Google Calendar** using the UI Connector Builder.
The website for the connector is https://calendar.google.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by bala-ceg** [comment]
@marcosmarxm can you please assign this issue to me ?

**Comment by bala-ceg** [comment]
As per the rest documentation linked [here](https://developers.google.com/calendar/api/v3/reference). Below are the list of streams that we could support in airbyte google calendar integration

- Acl
- CalendarList
- Calendars
- Channels
- Colors
- Events
- Freebusy
- Settings

**Comment by marcosmarxm** [comment]
Go forward!

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/46306
