### ISSUE TITLE
[connector-request] Freshteam

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#45990]
This is a **suggestion** to create a connector for **Freshteam** using the UI Connector Builder.
The website for the connector is https://www.freshworks.com/hrms.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by itsxdamdam** [comment]
Hi @marcosmarxm 
I'd like to work on this

**Comment by parthiv11** [comment]
@itsxdamdam on which product are you working ?

![image](https://github.com/user-attachments/assets/06ff1c52-bd12-41da-905a-4424847a094b)

**Comment by itsxdamdam** [comment]
@parthiv11 I'm working on Freshservice for Business Teams

**Comment by itsxdamdam** [comment]
Hi @marcosmarxm jsut to clarify Freshteam is Freshservice.

**Comment by marcosmarxm** [comment]
Airbyte already has a Freshservice connector, if it is the case you need to select another connector @itsxdamdam

**Comment by itsxdamdam** [comment]
I just checked and I believe Freshservice and its products are covered.

I'll be picking another connector now

**Comment by seanm202** [comment]
> This is a **suggestion** to create a connector for **Freshteam** using the UI Connector Builder. The website for the connector is https://www.freshworks.com/hrms.
> 
> If you want to try, claim this issue and start working on it following the steps below.
> 
> ### Steps:
> 1. Comment in the issue and wait to be assigned to start working on it.
> 2. Map the API endpoints (get approval to move to 3 step)
> 3. Describe steps to get credentials.
> 4. Create the connector using the UI Builder
> 
> Important
> 
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.
> 
> Caution
> 
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

//I would like to work on this. #haktoberfest2024#airbyte
