### ISSUE TITLE
Destination Redshift: Enable SSL authentication 

### ISSUE THREAD

**Issue by olivermeyer** [airbytehq/airbyte#4600]
## Tell us about the problem you're trying to solve
I need to enable SSL for my Redshift destination, which is currently not possible.

## Describe the solution you’d like
The source should take an `sslmode` parameter, with the following options in line with the Redshift [doc](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html):
* disable
* allow
* prefer
* require
* verify-ca
* verify-full

Additionally, and if required, the connector should retrieve and use the CA certificates for Redshift from https://s3.amazonaws.com/redshift-downloads/redshift-ca-bundle.crt (as per the doc). Note that this is no longer required if the client uses Redshift JDBC driver with version > 1.2.8.1005 (again as per the doc).

## Describe the alternative you’ve considered or used
None - without this feature, it is not possible to connect to a Redshift cluster with requires SSL.

## Are you willing to submit a PR?
Sadly I'm not comfortable with Java so I'll have to pass on this one :-(

**Comment by marcosmarxm** [comment]
thanks @olivermeyer there are some requests for SSL using other databases. I added this to the connector roadmap.

**Comment by olivermeyer** [comment]
I just corrected the issue as in my case it has to do with the Redshift destination, not source! However this should probably be applied to the source as well.

> there are some requests for SSL using other databases.
Indeed - I would expect this to be a common request for all DBs as SSL is pretty standard nowadays.

**Comment by sherifnada** [comment]
I believe SSL is enabled for redshift by default so closing this
