### ISSUE TITLE
[connector-request] Mention

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46014]
This is a **suggestion** to create a connector for **Mention** using the UI Connector Builder.
The website for the connector is https://mention.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by ash-x4** [comment]
I think i'll be able to complete this one @marcosmarxm 
Please assign it to me 🙏

**Comment by ombhardwajj** [comment]
Can I work on this please , if you haven't started yet @ash-x4 ?
 cc: @marcosmarxm

**Comment by marcosmarxm** [comment]
All yours @ombhardwajj

**Comment by ombhardwajj** [comment]
Authentication : API Key
Streams to be added :
1)Alerts
2)Alert
3)Mentions
4)Mention
5)Mention Children
6)Accounts
7)Account
8)Tags
9)Alert Authors
10)Alert Tasks
11)Statistics
12)Tasks
Pagination available for : Alerts , mentions , Mention children , Alert authors , Alert Tasks 
@marcosmarxm I am going ahead with these.

**Comment by ombhardwajj** [comment]
@marcosmarxm 
PR raised !! Please review 🙇
