### ISSUE TITLE
[connector-request] Quora Ads

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46033]
This is a **suggestion** to create a connector for **Quora Ads** using the UI Connector Builder.
The website for the connector is https://www.quora.com/business.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by bala-ceg** [comment]
@marcosmarxm Can i work on this since  the issue [#45994](https://github.com/airbytehq/airbyte/issues/45994) is having some issues to setup the API

**Comment by bala-ceg** [comment]
Below are the endpoints in the Quora Ads which can be converted to streams

| Endpoint                                     |
|----------------------------------------------|
| GET /accounts/{account-id}                   |
| GET /campaigns/{campaign-id}                 |
| GET /ad-sets/{ad-set-id}                     |
| GET /ads/{ad-id}                             |
| GET /accounts/                               |
| GET /account/{account-id}/lead-gen-forms     |
| GET /account/{account-id}/recent-leads       |
| GET /me                                      |

**Comment by bala-ceg** [comment]
While researching, the api key for https://www.quora.com/ads/conversion_api_doc# is publicly available and  previous Quora Ads access  request have to be obtained from quora team

**Comment by marcosmarxm** [comment]
Are you going to get an API key or do you think it won't be possible?

**Comment by bala-ceg** [comment]
I have emailed the quora team, but i have the key for [conversion_api]( https://www.quora.com/ads/conversion_api_doc#) which has only POST Resource stream. can i implement that first and try the rest ?

**Comment by marcosmarxm** [comment]
Please provide a list of what endpoints you're planning to implement first

**Comment by bala-ceg** [comment]
@marcosmarxm, This is the only endpoint available to implement [Track conversion event](https://www.quora.com/ads/conversion_api_doc#/paths/~1conversion/post)
I have requested the api key access with quora team. If i get it i will implement all of the above mentioned GET endpoints in my first comment

**Comment by marcosmarxm** [comment]
Let's wait for the GET endpoints.

**Comment by itsxdamdam** [comment]
@marcosmarxm I am also trying to request api key access from quora team

**Comment by bala-ceg** [comment]
@itsxdamdam @marcosmarxm i have obtained the api key from quora team and i am working on the connector.

**Comment by marcosmarxm** [comment]
Connector wasn't find in user workspace to run proper tests. Waiting to get connector in Airbyte Cloud workspace to run evaluation.
