### ISSUE TITLE
[connector-request] ReferralHero

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46037]
This is a **suggestion** to create a connector for **ReferralHero** using the UI Connector Builder.
The website for the connector is https://referralhero.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by bala-ceg** [comment]
@marcosmarxm I worked on #46306 connector, can i try this?

**Comment by bala-ceg** [comment]
@marcosmarxm, below are the end points mentioned in the link [here](https://support.referralhero.com/integrate/rest-api/endpoints-reference). First stream is the subset of all the other streams. Can you goahead?

Here’s a table containing all the **GET** request endpoints:

| **Description**                                   | **Endpoint**                                                  |
|---------------------------------------------------|---------------------------------------------------------------|
| Retrieve all lists                                | `GET https://app.referralhero.com/api/v2/lists`              |
| Get List Leaderboard                              | `GET https://app.referralhero.com/api/v2/lists/:uuid/leaderboard` |
| Get list rewards                                  | `GET https://app.referralhero.com/api/v2/lists/:uuid/bonuses` |
| Retrieve all subscribers from a list              | `GET https://app.referralhero.com/api/v2/lists/:uuid/subscribers` |
| Retrieve subscriber by ID                          | `GET https://app.referralhero.com/api/v2/lists/:uuid/subscribers/:subscriber_id` |
| Retrieve subscriber by email                       | `GET https://app.referralhero.com/api/v2/lists/:uuid/subscribers/retrieve_by_email` |
| Retrieve subscriber by MWR                         | `GET https://app.referralhero.com/api/v2/lists/:uuid/subscribers/retrieve_by_mwr` |
| Retrieve all referrals of a subscriber             | `GET https://app.referralhero.com/api/v2/lists/:uuid/subscribers/:subscriber_id/referred` |

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/46338
