### ISSUE TITLE
[connector-request] Reddit Ads

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46036]
This is a **suggestion** to create a connector for **Reddit Ads** using the UI Connector Builder.
The website for the connector is https://ads.reddit.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by rytismi** [comment]
Hey @marcosmarxm, I'd like to work on this :)

**Comment by marcosmarxm** [comment]
@rytismi do you have any update about implementation of this connector?

**Comment by rytismi** [comment]
hey @marcosmarxm , had trouble authenticating with the API. Process seems too overcomplicated. You can unassign me.

**Comment by itsxdamdam** [comment]
@marcosmarxm I'd like to try my hands on this

**Comment by marcosmarxm** [comment]
Contributor doesn't have enough data to test properly the connector + Reddit Ads API token expires very frequent without a good option to use an Auth in UI Builder.
