### ISSUE TITLE
[connector-request] Ringover

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46041]
This is a **suggestion** to create a connector for **Ringover** using the UI Connector Builder.
The website for the connector is https://www.ringover.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by 15vaibhav2003** [comment]
Hi @marcosmarxm  
I think this is perfect for me to work upon! Please assign it to me :)

**Comment by 15vaibhav2003** [comment]
Hey @marcosmarxm 
I tried working around this but my API key isn't working .. I think it will take time to get a fix around that so I am leaving this one and I'll try to get my hands  on #46080

**Comment by bishalbera** [comment]
@marcosmarxm I would like to try this next.
