### ISSUE TITLE
[connector-request] Smartwaiver

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46058]
This is a **suggestion** to create a connector for **Smartwaiver** using the UI Connector Builder.
The website for the connector is https://www.smartwaiver.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by avirajsingh7** [comment]
@marcosmarxm Already raised pr for assigned issue,
Next I want to work on this issue, Please assign me this issue
Thanks

**Comment by avirajsingh7** [comment]
Hey @marcosmarxm , 

In this api pagination is not define, and we can get only certain number of records which are on first page and parameter limit can only between 1-300 for some endpoint
I don't fill this connector will be good addition to airbyte
LMK your views.

IF we want to add this are following endpoint we can add

[waiver templates](https://api.smartwaiver.com/api/docs#list-waiver-templates)
[Signed Waivers](https://api.smartwaiver.com/api/docs#list-signed-waivers)
[Detailed Signed Waivers](https://api.smartwaiver.com/api/docs#retrieve-a-signed-waiver)

**Comment by marcosmarxm** [comment]
You can also implement the `checkin` endpoint right? This one has offset/pagination.
For waivers let's use limit 300 and add a warning note in the connector page.

**Comment by avirajsingh7** [comment]
Hey @marcosmarxm,
Trying to do some work around to get all records for this [Signed Waivers](https://api.smartwaiver.com/api/docs#list-signed-waivers) enpoint
By using fromDts and toDts for pagination
Like if we got first 300 records for 1 oct 2024 to current date
and lets consider we got first 300 record with max date 2 oct 2024
then fetching records from 2oct 2024 to current date  (This includes timestamp also)


<img width="824" alt="Screenshot 2024-10-08 at 11 24 34 PM" src="https://github.com/user-attachments/assets/0c97cbf3-ebbf-4742-b03c-1d12b1cd38c6">

When calling next_page_token in query parameters getting none value ([Check slack](https://airbytehq.slack.com/archives/C027KKE4BCZ/p1728201759864939))

Now when I pass fromDts in Body Json this is working properly, but there is no mention of passing this as body json in api docs
Should I create connector by passing this as body json.

<img width="807" alt="Screenshot 2024-10-08 at 11 31 53 PM" src="https://github.com/user-attachments/assets/e098e867-6b34-47ad-a19d-dc22291547b3">


LMK if this is fine with you
