### ISSUE TITLE
[connector-request] Squarespace

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46068]
This is a **suggestion** to create a connector for **Squarespace** using the UI Connector Builder.
The website for the connector is https://www.squarespace.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by vspanxcode** [comment]
Hello @marcosmarxm, I would like to work on this,  please assign me this issue

**Comment by marcosmarxm** [comment]
@vspanxcode do you have update about implementation of this connector?

**Comment by vspanxcode** [comment]
@marcosmarxm couldn't find proper account for this

**Comment by avirajsingh7** [comment]
Please assign me this one , I will take a look

**Comment by avirajsingh7** [comment]
Hey @marcosmarxm 
To add [orders](https://developers.squarespace.com/commerce-apis/retrieve-all-orders) and [transaction](https://developers.squarespace.com/commerce-apis/retrieve-all-transactions)  require payment processor setup 

I have added all the other endpoints
And API doc seems updated I was able to generate schema through response in api docs (using mock api to get data and send it to airbyte and using schema generated by airbyte)

LMK if I should add this endpoint or not

**Comment by marcosmarxm** [comment]
I'm ok, you can include some note mentioning/warning users about both endpoints.
