### ISSUE TITLE
[connector-request] Spotify Ads

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46065]
This is a **suggestion** to create a connector for **Spotify Ads** using the UI Connector Builder.
The website for the connector is https://ads.spotify.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by marcosmarxm** [comment]
All yours @bishalbera

**Comment by bishalbera** [comment]
@marcosmarxm Hey how can i use the ai assistant to help me building the connector using the connector builder ui? I was following [this](https://docs.airbyte.com/connector-development/connector-builder-ui/ai-assist) but couldnt find the ai assistant button . Is it only available for airbyte cloud?

**Comment by marcosmarxm** [comment]
Yes, we recommend to create a trial account to use AI builder :)

**Comment by bishalbera** [comment]
@marcosmarxm I’ve encountered some API endpoints that support both GET  and POST like ads or campaign . When defining streams for the connector, should I strictly use the GET method to pull data, or is there ever a scenario where I would use POST for streams as well? Thanks

**Comment by marcosmarxm** [comment]
Most cases you're going to use GET, some APIs have a POST Search endpoint.

**Comment by bishalbera** [comment]
> Most cases you're going to use GET, some APIs have a POST Search endpoint.

ok got it . So far ai assistant is doing great job and lastly what does it mean by "Describe steps to get credentials"? Do I've to create some kind of guide also?

**Comment by marcosmarxm** [comment]
If Spotify has a page showing how to get credentials/doing auth to the API is great.

**Comment by bishalbera** [comment]
> If Spotify has a page showing how to get credentials/doing auth to the API is great.

Okay, I'll do that. However, I'm currently getting warnings that say no records could be extracted from the response for some streams, which is normal because they haven't been created yet (such as ad, ad set). I tried to create those, but I can't because it requires enabling billing, which I don't want to do. As a result, the 'contribute to Airbyte' option is disabled. What should I do now?
<img width="1710" alt="Screenshot 2024-10-03 at 8 31 44 AM" src="https://github.com/user-attachments/assets/6e83903e-4c62-4fa7-881d-b9d0d8cb8b94">

**Comment by marcosmarxm** [comment]
This is a prerequisite @bishalbera. It is described in the issue:

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

If you don't have data to test the connector it won't be possible to contribute this connector. Please contact me in Airbyte Slack.

**Comment by bishalbera** [comment]
@marcosmarxm I've sent you a dm in slack.

**Comment by csanchez-resourcemedia** [comment]
Hey team,

I have both a paid Spotify account and a paid Airbyte account. I'm happy to step in if @bishalbera has run into a hard-block. Would be grateful to contribute as this would be directly used at our nonprofit org.

Thanks!

**Comment by marcosmarxm** [comment]
@csanchez-resourcemedia you can go!

**Comment by csanchez-resourcemedia** [comment]
Awesome on it! I'll make a first pass tomorrow and send an update!
