### ISSUE TITLE
[connector-request] Splash

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46063]
This is a **suggestion** to create a connector for **Splash** using the UI Connector Builder.
The website for the connector is https://splashthat.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by parthiv11** [comment]
i would like to work on this, as completed other issues

i would make PR once get assigned @marcosmarxm

**Comment by marcosmarxm** [comment]
Any updates on Splash @parthiv11 ?

**Comment by parthiv11** [comment]
Not getting API Access, so this issue is open to others having Splash API
access
