### ISSUE TITLE
[connector-request] Tempo.io

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46074]
This is a **suggestion** to create a connector for **Tempo.io** using the UI Connector Builder.
The website for the connector is https://www.tempo.io.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by pangeran-bottor** [comment]
Hi @marcosmarxm , I would like to work on this. Thank you!

**Comment by pangeran-bottor** [comment]
Hi @marcosmarxm , from [Tempo REST API Documentation](https://apidocs.tempo.io/), I would like to start with these endpoints first. Let me know what you think.

- [Retrieve Accounts](https://apidocs.tempo.io/#tag/Accounts/operation/getAccounts)
- [Retrieve all Customers](https://apidocs.tempo.io/#tag/Customers/operation/getCustomers)
- [Retrieve Teams](https://apidocs.tempo.io/#tag/Team/operation/getTeams)
- [Retrieve Worklogs](https://apidocs.tempo.io/#tag/Worklogs/operation/getWorklogs)

**Comment by marcosmarxm** [comment]
Looks good @pangeran-bottor

**Comment by marcosmarxm** [comment]
@pangeran-bottor do you have any updates about the connector implementation?

**Comment by pangeran-bottor** [comment]
@marcosmarxm It turned out I haven't be able to find a time to work on this so I unassigned myself 🙏

**Comment by aazam-gh** [comment]
I would like to work on this next
