### ISSUE TITLE
[connector-request] WordPress

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46087]
This is a **suggestion** to create a connector for **WordPress** using the UI Connector Builder.
The website for the connector is https://wordpress.org.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by bishalbera** [comment]
@marcosmarxm I would like to try this

**Comment by bishalbera** [comment]
@marcosmarxm the ``block-types`` endpoint is giving me a 400 bad request error when I'm sending the req from ui builder but when I'm sending the same req from postman its giving me 200 . what should I do? Thanks

**Comment by bishalbera** [comment]
> This is the only endpoint causing issue?

Ya rest are all tested and ok @marcosmarxm 
<img width="1710" alt="Screenshot 2024-10-04 at 7 09 56 PM" src="https://github.com/user-attachments/assets/97d2770c-9869-47b3-a5de-02592685b637">

**Comment by marcosmarxm** [comment]
Let's move without that endpoint for now.

**Comment by bishalbera** [comment]
> Let's move without that endpoint for now.

ok then I'm raising the PR for it now :)

**Comment by JoeyAzarAddbloom** [comment]
Hello, we are interested in this one as well. Kindly let me know if we can collaborate on it or if we can jump on to create another connector.
