### ISSUE TITLE
[connector-request] Vonage

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46083]
This is a **suggestion** to create a connector for **Vonage** using the UI Connector Builder.
The website for the connector is https://www.vonage.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by gupta-arpan** [comment]
Hi @marcosmarxm , unassigning this because couldn't get credentials for this one.

**Comment by aazam-gh** [comment]
Assigning this next as concord API  creds will require more time by their support team

**Comment by aazam-gh** [comment]
@marcosmarxm according to the vonage api docs we have https://developer.vonage.com/en/getting-started/concepts/authentication#api-key-and-secret

3 different auths with JWT containing the userful endpoints for which we should query. However as JWT is not yet supported by the connector builder, this cannot be implmeneted :(

**Comment by marcosmarxm** [comment]
Please select another issue!
