### ISSUE TITLE
Destination S3 to Parquet/Avro: Handle empty objects with additionalProperties=true

### ISSUE THREAD

**Issue by blotouta2** [airbytehq/airbyte#4608]
## Enviroment
- **Airbyte version**:  example is 0.25.0-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**: (if applicable example Salesforce 0.2.3)  Slack 0.2.3
- **Destination Connector and version**: (if applicable example Postgres 0.3.3)  Destination S3 0.1.7
- **Severity**: High 
- **Step where error happened**:  Sync job 

## Current Behavior
i was trying to send data from facebook marketing to destination s3 in parquet format but it give me error. it works well with S3 CSV format previously.

## Expected Behavior
Data will be sync in parquet format.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*
[slack-s3-parquet.txt](https://github.com/airbytehq/airbyte/files/6779120/slack-s3-parquet.txt)

<details>
<summary>LOG</summary> 

```

Logs are attached as txt file.

```

</details>

**Comment by sherifnada** [comment]
Schema of the faulty object: 
```
 "pinned_info": {
      "type": [
        "null",
        "object"
      ],
      "additionalProperties": true,
      "properties": {}
    }
```

**Comment by tuliren** [comment]
The root cause is that `pinned_info` does not have predefined `properties`, and currently we don't support `additionalProperties`, and Parquet does not like schemaless fields.

Related issue: #4124.

**Comment by tuliren** [comment]
Ping Rytis Zolubas when this is done.
