### ISSUE TITLE
[connector-request] UpPromote

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46080]
This is a **suggestion** to create a connector for **UpPromote** using the UI Connector Builder.
The website for the connector is https://www.uppromote.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by aazam-gh** [comment]
Issued a PR for Simplesat. Will work on this next :)

**Comment by 15vaibhav2003** [comment]
Please assign this to me @marcosmarxm !

**Comment by marcosmarxm** [comment]
@15vaibhav2003 any update about the implementation of this connector?

**Comment by avirajsingh7** [comment]
@15vaibhav2003 if you are not continuing on this one,
Can I take this one?

**Comment by marcosmarxm** [comment]
@15vaibhav2003 clearing your assign. 
@avirajsingh7 it is yours.
