### ISSUE TITLE
[connector-request] Xsolla

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46089]
This is a **suggestion** to create a connector for **Xsolla** using the UI Connector Builder.
The website for the connector is https://xsolla.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by avirajsingh7** [comment]
Hey @marcosmarxm, please assign me this issue

**Comment by avirajsingh7** [comment]
Hey @marcosmarxm,
Here are API I am looking to intergrate

[Get Game List](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-games-list/#tag/game-keys/operation/get-games-list) 
[Get DRM list](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-drm-list/#tag/game-keys/operation/get-drm-list) 
[Get virtual items list](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-virtual-items/#tag/virtual-items-and-currency/operation/get-virtual-items) 
[Get Virtual Currency List](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-virtual-currency/#tag/virtual-items-and-currency/operation/get-virtual-currency) 
[Get virtual currency package list](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-virtual-currency-package/) 
[Get items Group list](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-item-groups/)
[Get list of bundles](https://developers.xsolla.com/api/digital-distribution-hub/operation/get-bundle-list/)

**Comment by avirajsingh7** [comment]
There are [subscription api](https://developers.xsolla.com/api/subscriptions/operation/get-plans/) also :
But it has different base url https://developers.xsolla.com/api/ and above mentioned endpoint has different base url  https://store.xsolla.com/api/v2

**Comment by marcosmarxm** [comment]
Lets start with the first endpoints and if have some space include the subscription or have a separated connector.

**Comment by avirajsingh7** [comment]
@marcosmarxm ,

In this source we can take project_id from user as input and have source specific to that project_id or can get all the project_id from this [endpoint](https://developers.xsolla.com/api/igs-bb/operation/get-projects/) and making every other stream child of this stream.

For now I have already created source with first approach, 
LMK if you prefer second approach

**Comment by marcosmarxm** [comment]
The best solution is to retrieve all project ids from the endpoint

**Comment by avirajsingh7** [comment]
Can not implement second solution because it has different authentication method than other endpoints

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/46295
