### ISSUE TITLE
[connector-request] Zoho Books

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46093]
This is a **suggestion** to create a connector for **Zoho Books** using the UI Connector Builder.
The website for the connector is https://www.zoho.com/books.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by ash-x4** [comment]
I wish to work on this @marcosmarxm !

**Comment by ash-x4** [comment]
This is a really big issue and would require a lot sincere effort since so many endpoints are involved. I dont think I will have enough time to go through all this hence I am leaving it . Ill choose another one

**Comment by bishalbera** [comment]
@marcosmarxm I would like to try this next . Also the endpoints seem exactly the same as Zoho inventory one only the base url is diff .
