### ISSUE TITLE
[connector-request] Zoho Campaigns

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46094]
This is a **suggestion** to create a connector for **Zoho Campaigns** using the UI Connector Builder.
The website for the connector is https://www.zoho.com/campaigns.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm  I would like to work on this!

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm I've mapped the API endpoints .
Please have a look and let me know if I can proceed ahead or if some correction is needed!
### 1. Campaign Details Stream
**API Endpoint**: /getcampaigndetails  
**Method**: GET  
**Description**: Fetches details of a specific campaign including status, sender information, and associated mailing lists.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/getcampaigndetails  
**Required Parameters**:
- `campaignkey`: (String) Get it from `recentcampaigns` response
- `resfmt`: (String) XML or JSON  
**Response Fields**:
- campaign_details: email_type, reply_to, campaign_name, sent_time, email_subject, email_from, email_options
- campaign_reports: forward_percent, hardbounce_count, unsent_count, open_percent, etc.  
**Pagination**: No  
**Incremental Sync**: No  

### 2. Campaign Reports Stream
**API Endpoint**: /campaignreports  
**Method**: GET  
**Description**: Retrieves campaign reports, including opens by time and reach metrics.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/campaignreports  
**Required Parameters**:
- `campaignkey`: (String) Get it from `recentcampaigns` response
- `resfmt`: (String) XML or JSON  
**Response Fields**:
- campaign_details: campaign_name, email_subject, sent_time
- campaign_reports: opens_count, click_percent, bounce_percent, etc.  
**Pagination**: No  
**Incremental Sync**: No  

### 3. Recent Campaigns Stream
**API Endpoint**: /recentcampaigns  
**Method**: GET  
**Description**: Fetches details of the five most recent campaigns created in your organization.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/recentcampaigns  
**Required Parameters**:
- `sort`: (String) asc/desc
- `fromindex`: (Integer) starting index for the campaign list
- `range`: (Integer) number of records to retrieve
- `resfmt`: (String) XML or JSON  
**Response Fields**:
- campaign_key, campaign_name, created_date_string, campaign_status  
**Pagination**: Yes  
**Incremental Sync**: No  

### 4. Recently Sent Campaigns Stream
**API Endpoint**: /recentsentcampaigns  
**Method**: GET  
**Description**: Fetches recently sent campaigns from your organization.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/recentsentcampaigns  
**Required Parameters**:
- `limit`: (Integer) Limit to fetch recent campaigns
- `resfmt`: (String) XML or JSON  
**Response Fields**:
- sent_time, campaign_name, campaign_key, created_time  
**Pagination**: No  
**Incremental Sync**: No  

### 5. View Coupon Details Stream
**API Endpoint**: /coupon/coupondetails  
**Method**: POST  
**Description**: Retrieves coupon details like campaign name, recipient, coupon code, and status.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/coupon/coupondetails  
**Required Parameters**:
- `couponCode`: (String) Coupon code from the recent coupon campaign
- `type`: (String) XML or JSON  
**Response Fields**:
- coupon_details: coupon_id, coupon, status, senton, expireon, recipient  
**Pagination**: No  
**Incremental Sync**: No  

### 6. Get Open Custom Workflows Stream
**API Endpoint**: /workflow  
**Method**: GET  
**Description**: Fetches a list of open custom workflows in your organization.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/workflow  
**Required Parameters**:
- `details`: (JSON) key-value pairs like page, limit, sort_order, user, trigger_type  
**Response Fields**:
- workflows: workflow_key, workflow_name, created_time  
**Pagination**: Yes (using `page` and `limit`)  
**Incremental Sync**: No  

### 7. Get List Advanced Details Stream
**API Endpoint**: /getlistadvanceddetails  
**Method**: GET  
**Description**: Fetches advanced details about a mailing list, including contact stats and campaign history.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/getlistadvanceddetails  
**Required Parameters**:
- `listkey`: (String) List key of the mailing list  
**Response Fields**:
- contact_stats, localsubscribers, campaign_details, web_client, brower_type, mobile_devices  
**Pagination**: Yes  
**Incremental Sync**: No  

### 8. Get List Contacts Stream
**API Endpoint**: /getlistsubscribers  
**Method**: GET  
**Description**: Fetches contacts from a mailing list based on their status.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/getlistsubscribers  
**Required Parameters**:
- `listkey`: (String) List key of the mailing list  
- `status`: (String) active/recent/unsub/bounce  
**Response Fields**:
- contact_email, firstname, lastname, phone  
**Pagination**: Yes (using `fromindex` and `range`)  
**Incremental Sync**: No  

### 9. Get Segment Contacts Stream
**API Endpoint**: /getsegmentcontacts  
**Method**: GET  
**Description**: Fetches contacts within a specific segment along with their details.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/getsegmentcontacts  
**Required Parameters**:
- `cvid`: (Number) Segment ID  
**Response Fields**:
- contact_email, firstname, lastname, companyname, added_time  
**Pagination**: Yes  
**Incremental Sync**: No  

### 10. Update List Stream
**API Endpoint**: /updatelistdetails  
**Method**: POST  
**Description**: Updates a mailing list’s name or associates a signup form with it.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/updatelistdetails  
**Required Parameters**:
- `listkey`: (String) List key of the mailing list  
- `newlistname`: (String) New name for the mailing list  
- `signupform`: (String) public/private  
**Response Fields**:
- status, message  
**Pagination**: No  
**Incremental Sync**: No  

### 11. Total Contacts Stream
**API Endpoint**: /listsubscriberscount  
**Method**: GET  
**Description**: Retrieves the total number of contacts in a list by status (active, unsubscribed, bounce, etc.).  
**Request URL**: https://campaigns.zoho.com/api/v1.1/listsubscriberscount  
**Required Parameters**:
- `listkey`: (String) List key  
- `status`: (String) active/unsub/bounce/spam  
**Response Fields**:
- no_of_contacts  
**Pagination**: No  
**Incremental Sync**: No  

### 12. Get Topics Stream
**API Endpoint**: /topics  
**Method**: GET  
**Description**: Fetches all topics available in your Zoho Campaigns account.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/topics  
**Required Parameters**:
- `from_index`: (Integer) Start index  
- `range`: (Integer) Number of topics to fetch  
**Response Fields**:
- topic_id, topic_name, primaryList  
**Pagination**: Yes  
**Incremental Sync**: No  

### 13. Get Products Stream
**API Endpoint**: /topics/products  
**Method**: GET  
**Description**: Retrieves all products created in your Zoho Campaigns account.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/topics/products  
**Required Parameters**:
- `from_index`: (Integer) Start index  
- `range`: (Integer) Number of products to fetch  
**Response Fields**:
- product_id, product_name  
**Pagination**: Yes  
**Incremental Sync**: No  

### 14. Get All Tags Stream
**API Endpoint**: /tag/getalltags  
**Method**: GET  
**Description**: Retrieves all tags created in your Zoho Campaigns organization.  
**Request URL**: https://campaigns.zoho.com/api/v1.1/tag/getalltags  
**Response Fields**:
- tag_name, tag_color, tag_created_time, tag_desc, tagged_contact_count  
**Pagination**: No  
**Incremental Sync**: No

**Comment by ombhardwajj** [comment]
Hey @marcosmarxm 
After investing significant time to this I've realized
The OAuth Authenticator requires an empty body and `Authorization: Zoho-oauthtoken  {{ config["oauth_access_token"] }}` Header . Tried doing that in YAML but didnt work out
I have gone through the docs , I dont think its possible with UI connector builder or low code.
Am I right??
![WhatsApp Image 2024-10-03 at 01 26 50](https://github.com/user-attachments/assets/6a198495-3dc4-4d5a-b007-48f006d067af)
<img width="1228" alt="Screenshot 2024-10-03 at 1 33 04 AM" src="https://github.com/user-attachments/assets/bc5c0aaf-71be-47d8-a92c-fa57012c3635">

**Comment by marcosmarxm** [comment]
@ombhardwajj are you able to run a request using Postman, maybe this can help you understand better how to structure your request. If not you can move to another connector.

**Comment by ombhardwajj** [comment]
@marcosmarxm  I tried with POSTMAN already!Request only goes through when we have 
`Authorization: Zoho-oauthtoken  {{ config["oauth_access_token"] }} ` Header and empty body.
I will take a new issue ! But you can keep me assigned on this , I will try to contribute this conenctor , maybe once the Hackathon ends !!

**Comment by ombhardwajj** [comment]
@marcosmarxm I think i can work on #45960

**Comment by ombhardwajj** [comment]
Just to highlight since OAuth req are similar for all zoho offerings , #46030 #46031 and #46093 will also be needed to built using Python connector..
@marcosmarxm

**Comment by marcosmarxm** [comment]
No problem, select another connector to work.

**Comment by bishalbera** [comment]
@marcosmarxm hey I've already submitted a pr for the prev issue and now I would like to try this :)
