### ISSUE TITLE
postgres source connection check fails if the db has no tables 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#461]
## Expected Behavior
The connection check should succeed regardless of tables.

## Current Behavior
The check fails with a `CRITICAL 0 tables were discovered across the entire cluster` error.

## Steps to Reproduce
Add a postgres source that doesn't have any table.s

## Severity of the bug for you
Low

This would be nice to fix but it would be much more useful short term to provide better insight into connection check failures.

**Comment by cgardens** [comment]
i'm going to close this. this issue was reported for the postgres source that was implemented using singer so it's referring to an entirely different implementation now.  i don't have any reason to think that the new implementation is particularly susceptible to this issue.
