### ISSUE TITLE
make it easier to understand check connection errors

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#462]
It needs to be easy for users to understand why connection checks are failing. Usually these failures are caused by inability access a host/port/db/api due to networking, credentials, etc. 

Possible short term fix:
Expose failure logs in the UI so it's easy to debug why the connection failed. Right now this is accessible from `docker-compose up` logs or by viewing the persisted logs for the connection check job, but that is not easy to use. 

Possible long term fix: 
Allow the integration to map errors to specific fields alongside a custom connection error.

**Comment by cgardens** [comment]
i think this is handled by the new changes in FE. putting it in milestone so that we make sure it is actually done.

**Comment by cgardens** [comment]
This is in progress in this issue: https://github.com/airbytehq/airbyte/issues/1121. going to close as duplicate.
