### ISSUE TITLE
Dynamically change schema

### ISSUE THREAD

**Issue by agrass** [airbytehq/airbyte#4632]
## Tell us about the problem you're trying to solve
Add new attributes on the schema depending on the data I receive from the source. 

## Describe the solution you’d like
Automatically check the schema and if something changed will modify the connection. For example on BigQuery add new columns on the table.  Another solution will be to don't specify a fixed schema and auto build a schema with the data received. 

## Describe the alternative you’ve considered or used
Right now I'm just setting a fixed schema

## Are you willing to submit a PR?
Yes

**Comment by davinchia** [comment]
Is this similar to https://github.com/airbytehq/airbyte/issues/1037?

**Comment by agrass** [comment]
@davinchia Yes it's similar, but my case is not for multi tenant is for one specific model already configured that news field/attributes are added after configured. It would be awesome to auto detect that new attributes and update the schema, change the schema automatically without needed to reconstruct everything.

**Comment by marcosmarxm** [comment]
@agrass closing this as Airbyte support schema propagation now:
<img width="1033" alt="image" src="https://github.com/airbytehq/airbyte/assets/5154322/e12d03ee-a67e-4dfc-8f97-e47d8b84ad28">
