### ISSUE TITLE
[source-postgres] TypeError: Cannot read properties of undefined (reading 'split') when editing or creating source.

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [airbytehq/airbyte#46346]
### Connector Name

source-postgres

### Connector Version

3.6.21

### What step the error happened?

Updating the connector

### Relevant information

Any time I load up the details page for a Postgres source, whether creating new or editing existing, I see the page briefly, and then it errors out. I tested other sources and did not get this error.

### Relevant log output

```shell
{
  "url": "https://airbyte.roc360.com/workspaces/42f0cf01-a901-4f0c-b381-a2034a342c13/source/f2a21370-7701-45a7-a98b-bb8ba2f2c0d0",
  "airbyteVersion": "1.0.0",
  "errorType": "TypeError",
  "errorConstructor": "TypeError",
  "error": {},
  "stacktrace": "TypeError: Cannot read properties of undefined (reading 'split')\n    at ne (https://airbyte.roc360.com/assets/DocumentationPanel-nc1lze43su.js:2:739)\n    at oR (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:38:19551)\n    at SB (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:44099)\n    at bB (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:39820)\n    at Gee (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:39747)\n    at ob (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:39597)\n    at u8 (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:36709)\n    at Gu (https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:38:3287)\n    at https://airbyte.roc360.com/assets/core-klzzp8kfpr.js:40:34285",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
  "featureFlags": {}
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by mkhinda29** [comment]
Just spun up Airbyte opensource using abctl yesterday to play around and got something very similar with postgres connector 3.6.21.  This is from my browser console:
```text
Navigated to http://localhost:8000/workspaces/3c38ce6f-cad7-4a84-9b22-9365049536b7/connections/new-connection?sourceType=new&sourceDefinitionId=decd338e-5647-4c0b-adf4-da0e75f5a750
TypeError: s is undefined
    ne http://localhost:8000/assets/DocumentationPanel-m4r58wojbs.js:2
    cR http://localhost:8000/assets/core-icl96mliue.js:38
    AB http://localhost:8000/assets/core-icl96mliue.js:40
    TB http://localhost:8000/assets/core-icl96mliue.js:40
```

**Comment by jeremy-thomas-roc** [comment]
I can also confirm moving back to 3.6.19 fixes it for me as well

**Comment by varunnmiglani** [comment]
getting this on connector version 2.0.28 as well

**Comment by snehilk1312** [comment]
was having the same error . Tried in different browsers too. Moving back to 3.6.19 fixes it for me .

**Comment by MagdaSzultk** [comment]
I also had the same error, changing to 3.6.19 helped.

**Comment by hectorhugogzz** [comment]
has anyone found a fix for this error?

**Comment by natikgadzhi** [comment]
Hey! thank you for reporting, I'm trying to reproduce. 

When you hit this, can you please tell me if:
1. Other sources also crash the new source page? Or is it just source-postgres?
2. You're all using Airbyte OSS, and all on 1.1.0?

**Comment by natikgadzhi** [comment]
Yep, I can reproduce this. 

Here's what I did and what setup I have:
1. `abctl local install`
2. Navigate to Sources → New → click Postgres on the list of connectors
3. It fails with the screenshot that others posted above on `s.split`

```
 abctl version
version: v0.18.0
  INFO    A new release of abctl is available: v0.18.0 -> v0.18.1
          Updating to the latest version is highly recommended
~/src/airbytehq/airbyte-platform-internal master !4
❯ abctl local status
  INFO    Using Kubernetes provider:
            Provider: kind
            Kubeconfig: /Users/natikgadzhi/.airbyte/abctl/abctl.kubeconfig
            Context: kind-airbyte-abctl
 SUCCESS  Found Docker installation: version 27.1.1
 SUCCESS  Existing cluster 'airbyte-abctl' found
  INFO    Found helm chart 'airbyte-abctl'
            Status: deployed
            Chart Version: 1.1.0
            App Version: 1.1.0
  INFO    Found helm chart 'ingress-nginx'
            Status: deployed
            Chart Version: 4.11.3
            App Version: 1.11.3
  INFO    Airbyte should be accessible via http://localhost:8000
  INFO    A new release of abctl is available: v0.18.0 -> v0.18.1
          Updating to the latest version is highly recommended
~/src/airbytehq/airbyte-platform-internal master !4
```

**Comment by natikgadzhi** [comment]
So, we think it's a regression that we've fixed in Cloud, but the commit with the fix was not included in the 1.1 release.

We will either release a patch, or roll 1.2 with the fix soon.

You could install 1.0 instead, that should work as a workaround.

**Comment by natikgadzhi** [comment]
@bgroff is going to ship a release with the fix tomorrow.

**Comment by natikgadzhi** [comment]
Hey folks! We've resolved this. If you hit this issue in your cluster, please make sure that you're trying to use source-postgres 3.6.22 and up. AFAIK the cluster would pick up updated connector definitions every time it restarts.

**Comment by deepansh96** [comment]
Hey airbyte noob here. Can anyone point me to the documentation which explains how to make sure that the source postgres connector is using 3.6.22 version and up?

**Comment by natikgadzhi** [comment]
Depending on how you run airbyte, just restart your cluster. Airbyte would ingest fresh connector registry when it starts.

**Comment by JTolosaNalanda** [comment]
This error still persists with the last version abctl and the postgres connector 3.6.22

**Comment by mpjunior92** [comment]
I also ran into this issue when running Airbyte locally using abctl on macOS and the default Postgres connector version. Upgrading the connector to 3.6.22 and restarting the Docker container did not solve the issue. I manually set the connector version to 3.6.19 like suggested above and restarted the container. After that, UI loaded just fine.

**Comment by phankins99** [comment]
I'm still having this issue as well i just followed the quickstart guide in the documentation for the Amazon Ec2 setup and i get this error on the postgres source only. didn't work on 3.6.22 or 3.6.21.

**Comment by natikgadzhi** [comment]
At this point, it’s probably another thing. Also, 1.2 release will be out
later this week, let me know if you can reproduce it there.
