### ISSUE TITLE
Create sandbox account for DataScope connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4648]
## Tell us about the problem you're trying to solve
Obtain a sandbox account for https://mydatascope.com/ and populate it with data. A contributor already created a PR in #4636 but we need a sandbox account to test it in CI.

**Comment by oustynova** [comment]
a contributor created a PR to add the connector

**Comment by marcosmarxm** [comment]
@oustynova looks we don't have the credentials yet.

**Comment by oustynova** [comment]
@marcosmarxm Unblockers will have a look

**Comment by ycherniaiev** [comment]
@marcosmarxm @Sandbox is done.LastPass: Datascope sandbox. API docs: https://dscope.github.io/docs/

**Comment by marcosmarxm** [comment]
@ycherniaiev I'm not able to access Datascope with creds in LastPass. can you check this?

**Comment by ycherniaiev** [comment]
@marcosmarxm resolved
