### ISSUE TITLE
New Destination: Google Sheets

### ISSUE THREAD

**Issue by TimStoppard** [airbytehq/airbyte#4650]
## Tell us about the new connector you’d like to have
* Which source and which destination?

**We would like to use AirByte to connect our marketing platforms to our Google Sheets dashboard, so we are missing a couple of elements:**

**1) Sources: Microsoft Ads and Pinterest Ads are the most urgent (FB Ads and Google Ads are already there)
2) Destination: Google Sheets. We may be able to use Google Big Query but have not used this so far.**

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

**We want to pull our marketing data into our dashboards daily. Currently we use a bespoke program written in Python which connects to the platform APIs and delivers data to a Google Sheet. We then use this as our source for dashboards.**

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**We will either redevelop our Python software (which needs to be regularly updated when marketing platform APIs change), or pay for a service like Supermetrics.**

**Comment by sherifnada** [comment]
@TimStoppard Pinterest & bing ads are a work in progress. Would you be open to contributing the Google Sheets destination? No pressure, just thought I'd ask.

**Comment by TimStoppard** [comment]
@sherifnada thanks for your reply - I'm a dumb marketing guy but it's great to know Pinterest and Bing are coming. I will ask our developers if we can somehow contribute Google Sheets as destination, or alternatively if we can figure out how to use Google Big Query

**Comment by sherifnada** [comment]
@TimStoppard if marketing folks can understand Google Ads performance reports then they're in the top echelon of intelligence as far as I'm concerned :) 

LMK how things turn out on your end!

**Comment by TimStoppard** [comment]
Haha - thank you and will do!

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by misteryeo** [comment]
@Givo29 We're working on this this quarter so it should be complete by latest end of June if not earlier. Closing this issue in favor of the active one here: https://github.com/airbytehq/airbyte/issues/11918. Feel free to follow along!
