### ISSUE TITLE
Destination S3: Allow special chars for table_prefix

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#4654]
Hi,
I am trying to write to S3 destination with keys formatted as `static_prefix/source=<namespace>/object=<table_name>/<filename>`, like this:
![screenshot](https://user-images.githubusercontent.com/35332423/125048604-62afa700-e0a0-11eb-99ef-41a1f5b06b35.png)

aitbyte is normalizing the path to only contain letters and unserscores, resulting in paths like this:
```static_prefix/source_<namespace>/object_<table_name>/<filename>```

configured paths should not be modified

**Comment by marcosmarxm** [comment]
thanks @m-ronchi. I know the use of `=` when you partitioned your data using parquet format. https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines probably is possible to do. @tuliren tagging you here see some opinion.

**Comment by etsybaev** [comment]
Hi @m-ronchi .

Many thanks for your ticket.
Quick question: are you interested in "=" symbos only or in some other symbols as well? 

Thanks

**Comment by m-ronchi** [comment]
Hi,
basically, I wanted to be able to configure an [AWS Glue crawler](https://docs.aws.amazon.com/glue/latest/dg/crawler-s3-folder-table-partition.html) to create a partitioned spectrum schema.

other than the `=` character (mandatory to be able to partition), I may need the other characters, e.g. `.../date=2022-03-15/...`

I haven't tested url encoding

yes, the screenshot is what I have on my spectrum sources

**Comment by etsybaev** [comment]
https://github.com/airbytehq/airbyte/pull/11173
