### ISSUE TITLE
Airbyte Integration Missing Payload for Zulip Notifications

### ISSUE THREAD

**Issue by Aditya8840** [airbytehq/airbyte#46557]
### Topic

Airbyte Notifications

### Relevant information

I'm working on integrating Airbyte with Zulip, but I'm encountering an issue where the webhook does not contain a payload for Zulip notifications. Currently, it only works for Slack notifications and does not include the necessary data for Zulip integration.

It appears that the current webhook implementation for Airbyte does not provide a payload that Zulip can interpret, limiting its use to Slack notifications only. What would be the recommended approach to extend the payload to include fields that Zulip requires?
Any suggestions on how to proceed with this would be highly appreciated.

https://github.com/user-attachments/assets/08b7a2df-7604-48d9-a1e5-41dfebda678e

**Comment by nataliekwong** [comment]
Hi there, which notification types are you interested in receiving those webhook notifications for? We only offer non-Slack notifications for Failed and Successful syncs.

**Comment by Aditya8840** [comment]
Hi @nataliekwong, Thank you for your response. Zulip offers organized chats and 120+ native integrations, it makes sense to develop the Airbyte integration to handle all relevant cases in the data sync lifecycle

**Comment by nataliekwong** [comment]
We currently do not offer JSON payloads for any notification outside of Failed & Successful syncs, but we will consider adding additional notification coverage in the future roadmap!
