### ISSUE TITLE
[connector-request] Navan

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#46617]
This is a **suggestion** to create a connector for **Navan** using the UI Connector Builder.
The website for the connector is https://www.navan.com.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to 3 step)
3. Describe steps to get credentials.
4. Create the connector using the UI Builder

> [!IMPORTANT]
> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> [!CAUTION]
> This is a **suggestion** and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend to follow steps above.

**Comment by aazam-gh** [comment]
Chargedesk API creds will take a while to receive, will work on this instead

**Comment by aazam-gh** [comment]
@marcosmarxm seems like Navan has only one api [endpoint](https://app.navan.com/open-api/documentation/swagger-ui/#/Booking%20Data/getBookingReport)

do we need to implement this connector?

**Comment by aazam-gh** [comment]
Unassign this for now, will work on it later

**Comment by aazam-gh** [comment]
Taking this up again

**Comment by naaa760** [comment]
Hello @marcosmarxm 
I want to work on this issue!

**Comment by marcosmarxm** [comment]
You'd have one issue @naaa760
