### ISSUE TITLE
Source Github: Support syncing multiple repositories

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4662]
## Tell us about the problem you're trying to solve
I'd like to be able to specify a list of repositories which can be synced from Github using the Airbyte connector

**Comment by garden-of-delete** [comment]
+1. The Singer connector has this functionality.

**Comment by sherifnada** [comment]
@garden-of-delete agreed -- this is on the roadmap for this month or early next month in addition to #4473
