### ISSUE TITLE
Use Dixa Sandbox in CI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4667]
## Tell us about the problem you're trying to solve
#4358 introduced a Dixa connector from an awesome community contributor @olivermeyer. In order to continuously run integration tests/CI on the connector, we need a sandbox account on Dixa that we can populate with data to test the API. This ticket tracks that effort. 

I've already reached out to Dixa and am waiting to hear back from them. 

Once we use that Sandbox account in CI make sure to find all `TODOs` in the connector module related to CI and fix them.

**Comment by sherifnada** [comment]
Account created, now we should populate it with data for the connector

**Comment by cheyura** [comment]
@sherifnada Dixa demo account (long historical data) API token is on LastPass
