### ISSUE TITLE
[Roadmap] Support XML formats in Connector Builder

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#46753]
Our Connector Builder will support APIs that return XML formats. We will use a decoder to parse the returned data into a JSON format that works with the Connector Builder.

**Comment by Tom-DK** [comment]
I've noticed XML is available already for Airbyte Cloud. Any idea, when this will be released for Airbyte Oss?

**Comment by nataliekwong** [comment]
It will be available in the next release of Airbyte OSS (1.2.0), which occurs about every month. You can monitor the status of the releases here: https://github.com/airbytehq/airbyte/releases. When it's released, I will close this issue as well.

**Comment by nataliekwong** [comment]
This has been released with [Airbyte v1.2.0](https://github.com/airbytehq/airbyte/releases/tag/v1.2.0).
