### ISSUE TITLE
[destination-snowflake] incorrect transaction handling leads to missing data

### ISSUE THREAD

**Issue by zeev-finaloop** [airbytehq/airbyte#46936]
### Connector Name

destination-snowflake

### Connector Version

3.11.7

### What step the error happened?

During the sync

### Relevant information

I believe there is a critical bug in snowflake destination. When you run a snowflake destination with `append+deduped`, it generates the following structure (more or less):
```sql
begin transaction;
  insert into table ...;
  delete from table ...;
  ...
commit;
```
The begin transaction; and commit; parts are added by some utility function called transactionally.
The issue with snowflake is that the commits are session level and not transaction level. So in case the delete fails, the insert will still be committed. Airbyte then detects the failure and reruns the transaction. Now we have inserted the same records twice, and when the delete runs, the way it is written, it deletes both of the records. I believe this to be a major issue.
What should work for snowflake is to wrap the transaction in a script block and handle the exception. Something like:
```sql
BEGIN
  begin transaction;
    INSERT INTO table ...;
    DELETE FROM table ...;
  commit;
EXCEPTION
WHEN OTHER THEN
  ROLLBACK;
END;
```
I believe the fix is small, but not sure where to do it as I don't understand the architecture very well.

To reproduce snowflake's behaviour, you can run:
```sql
begin transaction;
INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2);

INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2),
    
    ('kuku', 'Johnson',  2);
commit;
```
You will see that the first insert was indeed committed, although the second one fails.
This code does the job:
```sql
BEGIN
begin transaction;
INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2);

INSERT INTO employees (employee_ID, last_name, department_ID) VALUES

    (107, 'Richards', 1),

    (108, 'Paulson',  1),

    (109, 'Johnson',  2),

    ('kuku', 'Johnson',  2);
commit;
EXCEPTION
WHEN OTHER THEN
    ROLLBACK;
END;
```

### Contribute

- [x] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
@airbytehq/destinations Could someone look into this issue? It may be an edge case where the connector isn't working properly, but it still negatively impacts users.

**Comment by xyfer17** [comment]
@zeev-finaloop could you please assign this issue to me

**Comment by zeev-finaloop** [comment]
@xyfer17 I think I have the solution, I just currently struggle how to run snowflake integration tests locally/wait for someone to approve for it to run in ci. If you could help. it would be great. Take a look at the pr. Thanks
