### ISSUE TITLE
Airbyte sync vs replication: Performance

### ISSUE THREAD

**Issue by ashishgupta-97065** [airbytehq/airbyte#4693]
Hey Guys, quick check in

For postgres to postgres data transfer would a db sync / replication be better (it's realtime and lighter as it would sync only the changes) or would airbyte have any advantages (usability definitely is one).

I guess the same applies to other dbs as well (Oracle, MS SQL).

Regards
Ashish

Regards

**Comment by misteryeo** [comment]
Closing this as there's no action here for engineering team - please post your questions to https://discuss.airbyte.io/ if a follow-up is needed!
