### ISSUE TITLE
[connector-request] FxFeed

### ISSUE THREAD

**Issue by ombhardwajj** [airbytehq/airbyte#46947]
This is a suggestion to create a connector for FxFeed using the UI Connector Builder.
The website for the connector is https://fxfeed.io/.

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

**Comment by marcosmarxm** [comment]
Discussion: https://github.com/airbytehq/airbyte/discussions/46946

**Comment by ombhardwajj** [comment]
PR raised , please review 🚀 
Currently I havent added the TimeSeries stream since the schema has hardcoded dates 😞 
It looks like this 

`{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": true,
  "properties": {
    "2024-10-01": {
      "properties": {
        "AED": {
          "type": [
            "number",
            "null"
          ]
        },
        "AUD": {
          "type": [
            "number",
            "null"
          ]
        },
        "AZN": {
          "type": [
            "number",
            "null"
          ]
……//other currencies},
      "type": [
        "object",
        "null"
      ]
    },
    "2024-10-02": {
      "properties": {
        "ADA": {
          "type": [
            "number",
            "null"
          ]
        },
        "AED": {
          "type": [
            "number",
            "null"
          ]
        },
……//other currencies},
      "type": [
        "object",
        "null"
      ]
    }
`

**Comment by marcosmarxm** [comment]
FxFeed is more a service to build an app using currency data instead of extracting data. I don't believe it adds much more value compared to existing connectors for that reason I'm declining this contribution.
