### ISSUE TITLE
Upgrade debezium version for Oracle Source to support more connectors 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#4695]
Currently we are using debezium version 1.4.2. In order to support more connectors like oracle, etc. we need to upgrade the debezium version. As per the docs for [oracle](https://debezium.io/documentation/reference/1.4/connectors/oracle.html) 
the version 1.4.2 oracle connector is in incubating state. The later versions provide more stable connector

Currently postgres, mysql and sql server connectors use version 1.4.2. We need to make sure that the upgrade doesnt break existing connectors and they stay as backward compatible. For example in sql server we track the db schema history and its saved in a file, we need to make sure that the later version is compatible with the format of saved history of previous version. Same is true for offset.

**Comment by cgardens** [comment]
Should we just do this as a pre-req (or part of) doing oracle CDC?

**Comment by subodh1810** [comment]
I think we should do it as a pre-requisite for Oracle CDC

**Comment by grishick** [comment]
As we move MySQL to beta, let's evaluate if we can/need to upgrade Debezium for MySQL as well.

**Comment by grishick** [comment]
@subodh1810 AFAIK, this is already done for MySQL. If so, please close as done. Otherwise, please estimate with the team.

**Comment by grishick** [comment]
This is already done for MySQL, so removing from MySQL Epic and renaming for Oracle

**Comment by tuliren** [comment]
The common library is already upgraded to Debezium 1.9.2. The prerequisite work is done for Oracle.
