### ISSUE TITLE
Request 'Delighted' as a Data Source

### ISSUE THREAD

**Issue by mwon-mercato** [airbytehq/airbyte#4700]
## Tell us about the new connector you’d like to have
* Data Source is called Delighted (https://app.delighted.com/dashboard_
* I do not need a specific version.

## Describe the context around this new connector
* We use Delighted to track consumer NPS.  Our entire company benefits from this data.
* As of right, I think hourly is fine.
* I am not clear here but here is documentation for their API.  https://app.delighted.com/docs/api

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?  Manual CSV download.  Its painful. Help! :)

## Are you willing to submit a PR? (I am not qualified unfortunately.)

Remove this with your answer :-)

**Comment by marcosmarxm** [comment]
thanks @mwon-mercato https://github.com/airbytehq/airbyte/issues/2969 is already requesting for this new source. I'm closing this as duplicated. You can :+1: on that issue showing this is important to you.

**Comment by marcosmarxm** [comment]
also @mwon-mercato https://github.com/airbytehq/airbyte/pull/4551 is open to review to implement this source! So soon this will be released!
