### ISSUE TITLE
[platform] Hardcoded namespace causing issues

### ISSUE THREAD

**Issue by mickutz** [airbytehq/airbyte#47023]
### Helm Chart Version

1.1.0

### What step the error happened?

On deploy

### Relevant information

Just wanted to point out a small bug in the airbyte chart.
The namespace for the ClusterRoleBinding [here](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/serviceaccount.yaml#L67) is hardcoded to `ab` and will cause issues if namespace is called something else.
There are workarounds, but would be nice to have a quick fix pushed in.

**Comment by pmossman** [comment]
This is resolved by https://github.com/airbytehq/airbyte-platform/commit/b5941657308f3dc60d4a1e4f3f6902efe8bb602d
