### ISSUE TITLE
Airbyte Cloud: prevent uploading custom docker containers

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4711]
## Tell us about the problem you're trying to solve
In the initial versions of Airbyte Cloud, for security considerations, we will _not_ allow users to upload custom docker containers. There are 2 places where we allow this currently:
1. We allow a user to upload a custom connector (destination or source) in the admin page.
2. We allow a user to upload a custom container as part of the custom transformations in the connection settings.

## Describe the solution you’d like
We would like the following resolutions in the respective cases:
1. Hide the `+ New Connector` button in the admin > destinations / sources page.
2. Do not allow a user to add a custom transformation in the connection settings.

**Comment by jrhizor** [comment]
We also have backend issues preventing adding the custom behavior in the api. The piece for preventing adding connector definitions is already in place. https://github.com/airbytehq/airbyte/issues/5003 is pending review but will limit the ability to create operators with custom dbt images, which is another case where custom docker images are required.

This ticket (https://github.com/airbytehq/airbyte/issues/4711) should also include preventing the configuration of dbt transformations in cloud.
