### ISSUE TITLE
Google drive uncstructured api processing?

### ISSUE THREAD

**Issue by ikelkar** [airbytehq/airbyte#47127]
### Topic

google drive source unstructured api

### Relevant information

Hi,

I've been experimenting with the google drive source (0.0.12) and the `Document File Type Format`. It only supports `local` processing at the moment and doesn't have the ability to provide a url to the unstructured.io api. When will this be supported? I've noticed some other sources that have the Document File Type format support api (e.g. Google Cloud Storage (GCS))

Thanks

**Comment by marcosmarxm** [comment]
Issue was opened using the wrong template. Please open a new issue using the right [template](https://github.com/airbytehq/airbyte/issues/new?template=1-issue-connector.yaml)
