### ISSUE TITLE
[connector-request] TMDB

### ISSUE THREAD

**Issue by faria-karim-porna** [airbytehq/airbyte#47134]
### Topic

New connector request

### Relevant information

This is a suggestion to create a connector for TMDB using the UI Connector Builder. The website for the connector is https://www.themoviedb.org.

Relevant information
https://developer.themoviedb.org/docs/getting-started

**Comment by faria-karim-porna** [comment]
Hi @marcosmarxm Would you please assign this to me?

**Comment by marcosmarxm** [comment]
All yours @faria-karim-porna
