### ISSUE TITLE
Airbyte Cloud: Scope endpoints by workspace

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4714]
## Tell us about the problem you're trying to solve
Some of the endpoints in the Config API are not scoped by workspace. This was previously fine as we could assume that all workspaces in a deployment belonged to the same owner. In Airbyte Cloud that assumption is no longer safe. 

## Describe the solution you’d like
The following endpoints need to now be scoped by workspace id.
* [ ] /v1/logs/get
* [ ] /v1/deployment/export
* [ ] /v1/deployment/import
* [ ] /v1/destination_definitions/list (but not /v1/destination_definitions/list_latest ?)
* [ ] /v1/source_definitions/list (but not /v1/source_definitions/list_latest ?)

## Describe the alternative you’ve considered or used
When we add an "organization" level to our data model, it may make more sense for some of these endpoints to be scoped by organization instead of workspace.

**Comment by jrhizor** [comment]
These won't block the closed beta release as far as I can tell. Do you agree?

If we are temporarily disabling custom connectors, I think all of those can just be admin-level access.

**Comment by cgardens** [comment]
agreed with jared's comment. we can just lock down these features for now. removing from milestone.

**Comment by mfsiega-airbyte** [comment]
Closing as obsolete.
