### ISSUE TITLE
Google ads connector prefix not working

### ISSUE THREAD

**Issue by tristaningenius** [airbytehq/airbyte#47241]
### Connector Name

source-google-ads

### Connector Version

3.7.9

### What step the error happened?

During the sync

### Relevant information

Hi

The prefix datastream is not working since version 3.7.0 + airbyte last version.

I tried with mysql destination connector

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @tristaningenius are you talking about the stream prefix (see image):
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/2e5a1b30-413d-4816-9195-a4c34c34c607">
