### ISSUE TITLE
Export import feature should manage only connections configurations + state per workspace

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4731]
## Tell us about the problem you're trying to solve
When using the export/import functionality, the produced archive should only include connections/source/destination/etc of the selected workspace. In addition, we should (optionally?) include the state objects of those connections too but not the whole job history (we don't export/import logs anyway atm)

Why?
- exporting and purging the jobs/attempts makes it difficult to write the proper query and retrieve only the X last jobs 
- the archive size is growing depending on how many jobs are included per connection and can induce OOM when importing (for not so important data point, we usually tell users to flush the jobs/attempts files to solve these)

## Describe the solution you’d like
Simplify the export / import API endpoints to scope and reduce the data being archived.

Limit the exported configuration objects to the current workspace, so this API is easier to use when multiple users with different workspace permissions would try to manipulate their config

## Context
for example user encountering OOM on slack:
- https://airbytehq.slack.com/archives/C01MFR03D5W/p1622537189471400 
- https://airbytehq.slack.com/archives/C01MFR03D5W/p1626168123256600?thread_ts=1626159868.249100&cid=C01MFR03D5W

**Comment by cgardens** [comment]
Nice. Thanks for writing this.

Is there something straight forward we can do to get the state in the config database? Like is there any reason why it is a terrible idea to just add a table in the config database for this that tracks the last state for each connection? 

I feel like if there's a 1-day project where we can make this sort of alteration to our data model it might unlock a lot and be really high leverage. But I'm not sure that I'm missing some complexity. WDYT, @ChristopheDuong ?

**Comment by ChristopheDuong** [comment]
> Is there something straight forward we can do to get the state in the config database? Like is there any reason why it is a terrible idea to just add a table in the config database for this that tracks the last state for each connection?

I think this makes sense to do this work. In addition, it makes it much simpler to manipulate it afterward such as in this feature request: https://github.com/airbytehq/airbyte/issues/3092#issuecomment-828127687 where we would want the ability to edit/reset/jump back the state in the UI.

cc @sherifnada

**Comment by cgardens** [comment]
closing as no longer relevant (import / export has been removed).
