### ISSUE TITLE
Improve how extract/load YAML data for dbt

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4733]
## Tell us about the problem you're trying to solve
https://github.com/airbytehq/airbyte/pull/4721 improve the regex to extract data for profile, but we need a better approach to handle this.

## Describe the solution you’d like
Probably a Python module with tests.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by ChristopheDuong** [comment]
sorry i also created it: https://github.com/airbytehq/airbyte/issues/4734
