### ISSUE TITLE
Improve custom dbt transformation handling profiles.yml

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4734]
## Tell us about the problem you're trying to solve
As follow up to https://github.com/airbytehq/airbyte/pull/4721, do proper yaml parsing/extract to be used in https://github.com/airbytehq/airbyte/blob/7decb12818ad2cc0c7b3039c3d5e620236250edd/airbyte-workers/src/main/resources/dbt_transformation_entrypoint.sh#L7

## Describe the solution you’d like
we should write (a python?) script that uses a yaml parser to load the `dbt_project.yml` file and output the name of the profile being used, something like: `load yaml file; print(config.get("profile"))` it would be more robust

**Comment by marcosmarxm** [comment]
Python `yaml` is native so probably should be easy to do this! :D
