### ISSUE TITLE
[Connector-Request] Supabase

### ISSUE THREAD

**Issue by bishalbera** [airbytehq/airbyte#47351]
### Topic

This is a suggestion to create a connector for Supabase using the UI Connector Builder. The website for the connector is https://supabase.com/.

### Relevant information

api docs : https://api.supabase.com/api/v1#tag/auth

**Comment by bishalbera** [comment]
@marcosmarxm I think this will be good one as its one of the popular popular open source firebase alternatives. If you thinks the same then assign me this please. :)

**Comment by marcosmarxm** [comment]
You can use Postgres to sync data from Supabase.
