### ISSUE TITLE
[New-Connector] Benzinga API

### ISSUE THREAD

**Issue by bala-ceg** [airbytehq/airbyte#47368]
### Topic

New Connector Request

### Relevant information

**Relevant information**
This is a suggestion to create a connector for Benzinga  using the UI Connector Builder.
The website for the connector is https://docs.benzinga.com/home

If you want to try, claim this issue and start working on it following the steps below.

**Steps:**
Comment in the issue and wait to be assigned to start working on it.
Map the API endpoints (get approval to move to step 3).
Describe steps to get credentials.
Create the connector using the UI Builder.
Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

**Comment by bala-ceg** [comment]
![Image](https://github.com/user-attachments/assets/84c2608c-737d-489a-a27f-876058aee1fa)
@marcosmarxm, can you please assign this issue to me? I am facing errors in pushing to github

**Comment by bala-ceg** [comment]
@marcosmarxm i am facing issues in pushing the code to github for this repository alone.can i manually create a pr for this connector

**Comment by marcosmarxm** [comment]
I tried the connector and 2 streams aren't working (historical and dailyquotes) . Some of stream dont'have the right record selector.
Historical stream must implement incremental instead of hardcoded start and end date.

**Comment by marcosmarxm** [comment]
Connector is working properly. @bala-ceg had some issues submitting the contribution and I made using my token: https://github.com/airbytehq/airbyte/pull/48455
