### ISSUE TITLE
[source-bigquery] Not able to create connection between Bigquery to Redshift

### ISSUE THREAD

**Issue by vbosh** [airbytehq/airbyte#47371]
### Connector Name

source-bigquery

### Connector Version

0.4.2

### What step the error happened?

None

### Relevant information

I'm testing Airbyte locally on my machine with BigQuery source and Redshift destination. The source and the destination were created suffessfully. When I try to create the connection though, I'm receiving the following error:

```
Airbyte is temporarily unavailable. Please try again. (HTTP 502)
```

Nothing else. 

Then I've created an account in Airbyte cloud and I've created the same source and destination targets and I can successfully create a connection. 

I'm very disappointed with this product. I have to spend a lot of time debugging issues that should be straightforward.

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Hello @vbosh sorry to hear you're having troubles using Airbyte. The issue you're having is likely something with the server and not the connector. Do you mind providing more information about how are you deploying Airbyte locally? How much resources (cpu/memory) the server you're deploying has. 

Bests

**Comment by marcosmarxm** [comment]
Closing due to unresponsiveness and insufficient information to debug the issue. Feel free to reach me if you want to reopen it.
