### ISSUE TITLE
Provide code coverage feedback in PRs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#474]
## Tell us about the problem you're trying to solve
I would like to know the test coverage of my pull request or the master branch. #473 introduced basic code coverage, but I'd like to be able to see it in the branch I'm making changes to. 

## Describe the solution you’d like
Display a badge or report in each pull request which shows the code coverage of the code in that branch. 

## Additional context
codecov.io seems to be a leading tool in this regard.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368168553723) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment]
@jdpgrailsdev I believe this is already done?

**Comment by jdpgrailsdev** [comment]
> @jdpgrailsdev I believe this is already done?

@davinchia Not entirely, if I understand the ask in this ticket.  The OSS code base does have the JaCoCo code coverage plugin applied to all projects and does generate coverage reports.  It does not currently put a badge on the pull request to show the level of coverage.  It does have the configuration to fail a build if a level of coverage is not met for any module, but that is a soft failure currently (it logs the lack of meeting the requirement, but does not fail the build).  In summary, there is still some work to do to meet the problem statement in this issue, but some of the foundational work has been done.

**Comment by oustynova** [comment]
resolved within this task
https://github.com/airbytehq/airbyte/pull/21376
