### ISSUE TITLE
[connector-request] Attio

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47415]
### Topic

This is a suggestion to create a connector for Attio using the UI Connector Builder. The website for the connector is https://attio.com/

### Relevant information

https://developers.attio.com/

**Comment by parthiv11** [comment]
@marcosmarxm confirm that this connector   can be added and assign to me

**Comment by Hamza-gth** [comment]
@parthiv11 any updates on this

**Comment by artemSolovevToloka** [comment]
@parthiv11 hey! any udates on this topic?

**Comment by rsottil** [comment]
any updates on this?
