### ISSUE TITLE
https://get.airbyte.com abctl install script assumes "which" utility is available

### ISSUE THREAD

**Issue by m1tk4** [airbytehq/airbyte#47413]
### Page URL

https://docs.airbyte.com/using-airbyte/getting-started/oss-quickstart

### Description

The abctl install script at https://docs.airbyte.com/using-airbyte/getting-started/oss-quickstart assumes "which" utility is available on the target server - which is not the case for example with standard Almalinux/Rocky CT containers on Proxmox.

It then proceeds to check for presence of curl/wget and fails, reporting that "curl nor wget are available" while either one of those may be installed, and its "which" that is missing.

**Comment by m1tk4** [comment]
Sorry I meant the script you get when you curl https://get.airbyte.com

**Comment by marcosmarxm** [comment]
For cases where the get.airbyte.com script doesn't work there are instructions to download the tar files and manually install. It isn't viable to provide quick script installation to all OS.
