### ISSUE TITLE
[connector-request] JotForm

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47436]
### Topic

This is a suggestion to create a connector for Jotform using the UI Connector Builder. The website for the connector is https://jotform.com/

### Relevant information

https://api.jotform.com/docs

**Comment by bishalbera** [comment]
@parthiv11 will you work on this? or is it for anybody?

**Comment by parthiv11** [comment]
I have done it already

**Comment by bishalbera** [comment]
so please at least comment on it to get it assigned otherwise stupid people like me think its available to get assigned :) @parthiv11

**Comment by parthiv11** [comment]
@marcosmarxm confirm that this connector   can be added and assign to me

**Comment by parthiv11** [comment]
> so please at least comment on it to get it assigned otherwise some people like me may think its available to get assigned :) [@parthiv11](https://github.com/parthiv11)

sorry brother for confusion, for next time I will make sure to comment

**Comment by bishalbera** [comment]
> > so please at least comment on it to get it assigned otherwise some people like me may think its available to get assigned :) [@parthiv11](https://github.com/parthiv11)
> 
> sorry brother for confusion, for next time I will make sure to comment

no problem :)

**Comment by bishalbera** [comment]
@marcosmarxm there is already a [jotform](https://docs.airbyte.com/integrations/sources/jotform) connector available :(
