### ISSUE TITLE
Connection Sync Issues Following Data Reset

### ISSUE THREAD

**Issue by fahademali** [airbytehq/airbyte#47523]
### Topic

Sync Conflict and Failure Post-Reset

## Issue Summary
After resetting data on Airbyte **v0.50.33**, the stream goes into a pending state. Subsequent "sync now" attempts (immediate or delayed) result in two different error scenarios.

## Airbyte Version
v0.50.33

# Steps to Reproduce

1. Perform a reset on the stream.
2. Wait until the reset job completes successfully.
3. Reproduce either of the following scenarios:
   - Scenario 1: Immediately attempt to "sync now" after the reset job’s success.
   - Scenario 2: Wait approximately 20 minutes after the reset job’s success, then attempt to "sync now."

# Observed Behavior
- **Scenario 1: Immediate Sync Conflict**
  Attempting "sync now" right after the reset job completes returns the error: "a sync is already in place." (See screenshot A).

- **Scenario 2: Delayed Sync Failure**
  Waiting about 20 minutes and then attempting "sync now" results in the initial reset job’s logs being updated to a failure status, with message (See screenshot B): 
    >   "Failure reason: Something went wrong within the Airbyte platform."

# Connections Tested
This issue has been observed across multiple integrations:

1. Google Sheets -> S3
2. Mailchimp -> BigQuery
3. S3 -> Redshift

# Expected Behavior
After a successful reset job, the stream should support a "sync now" command without triggering errors in either scenario.

Screen shot A:
![Image](https://github.com/user-attachments/assets/3b87323d-2f50-49c7-9bc8-9006f16b46a8)

Screen shot B:
![Image](https://github.com/user-attachments/assets/3c60e4bd-16e5-4499-a885-56dc9c4fbe34)

**Comment by marcosmarxm** [comment]
@fahademali can you upgrade to latest version and check if the issue are still there?

**Comment by marcosmarxm** [comment]
Closed due to lack of response and use of an outdated platform version.
