### ISSUE TITLE
"Newsletter with feature update" changes the status of "security updates"

### ISSUE THREAD

**Issue by MaxwellJK** [airbytehq/airbyte#4755]
## Enviroment
- **Airbyte version**:  0.27.2-alpha
- **OS Version / Instance**: Mac OS
- **Deployment**: Docker
- **Source Connector and version**: na
- **Destination Connector and version**: na
- **Severity**: Low
- **Step where error happened**: Update settings
- 
## Current Behavior
Clicking on the sentence "Newsletter with feature update" changes the status of  "Security Updates"

https://user-images.githubusercontent.com/11026691/125751793-73fbf82a-1bdc-441b-b5e1-793e2d572933.mov

## Expected Behavior
Clicking on the sentence "Newsletter with feature update" changes the status of  "Newsletter with feature update"

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1. Go to Settings
2. Go to Notification
3. Click on the sentence "Newsletter with feature update"

**Comment by davinchia** [comment]
@Jamakase
