### ISSUE TITLE
Create a 404 Page.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4760]
## Tell us about the problem you're trying to solve
1) Today as a user I am always redirected to the main app page when I try to navigate to a page that doesn't exists. 
2) When we are on cloud (cloud.airbyte.io), a portion of our requests will no longer be governed by the webapp(today's localhost) or gitbook(the main airbyte.io site), this means we require a 404 page.

## Describe the solution you’d like
We should have a generic 404 page to navigate users to. Cloud will require this.

We do not have to change behaviour for use case #1 if we don't want to.

## Additional context
We might want to try and use the generic gitbook 404 page for consistency?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment]
fyi @paulpalamarchuk created this issue for a 404 page. We'll start on this immediately.

**Comment by johnlafleur** [comment]
Design suggestion: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25296%3A0

**Comment by davinchia** [comment]
@timroes do you know if we have this?

**Comment by nataliekwong** [comment]
@timroes Can I close this, now that we have the "Oops" Octavia screen?

**Comment by timroes** [comment]
I think this has been solved by now. Reading through the original description I think most of the points noted down are now so outdated that they are not applying anymore.
