### ISSUE TITLE
[source-woocomerce] Replication errors incorrect date format

### ISSUE THREAD

**Issue by bapt-XV** [airbytehq/airbyte#47713]
### Connector Name

source-woocommerce

### Connector Version

0.5.0

### What step the error happened?

During the sync

### Relevant information

With the connection:  source WooCommerce &rarr; destination MySQL.

I am encountering issues with null dates in the connector. Certain date fields are not matching the expected RFC 3339 date-time pattern, causing schema validation errors.

During the replication process, the following streams have fields with null values:

**Orders**
  - `date_created`
  - `date_completed_gmt`
  - `date_paid`
  - `date_modified`
  - `date_modified_gmt`
  - `date_paid_gmt`
  - `date_completed`
  - `date_created_gmt`

**Products**
  - Multiple image date fields not matching the date-time pattern.

**Coupons**
  - `date_created`
  - `date_modified`
  - `date_modified_gmt`
  - `date_created_gmt`

**Product Variations**
  - `date_created`
  - `date_modified`
  - `date_modified_gmt`
  - `date_created_gmt`

The logs indicate errors such as:

`does not match the date-time pattern must be a valid RFC 3339 date-time`

This is how the date is formatted when making a WooCommerce API call: 

`"date_modified": "2024-10-28T09:57:33"`

**Environment:**

- Airbyte orchestrator: `airbyte/container-orchestrator:1.1.0`
- Source connector: `airbyte/source-woocommerce:0.5.0`
- Destination connector: `airbyte/destination-mysql:1.0.2` 

These validation errors indicate that the date fields are not in the expected format, which causes issues with data processing.
Let me know if you need further clarification!

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment]
Are the sync failing? Can you share a sync log? What platform version are you using?
