### ISSUE TITLE
Clean up Webapp Nginx for Cloud

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4781]
## Tell us about the problem you're trying to solve
Once we are on Cloud, we no longer need the Nginx we currently have.

This is currently doing two main things:
1) Forwarding request with `/api` to the right path. This is no longer needed.
2) Setting some global dom variables so everything works as expected. This is what we need to figure out.

## Describe the solution you’d like
For cloud, we want to get rid of Nginx entirely. The variables should be set in another manner.

**Comment by davinchia** [comment]
fyi @paulpalamarchuk ticket for tracking on Application side.

**Comment by cgardens** [comment]
@davinchia assigning to you since you are owning it. feel free to reassign if that is wrong.

**Comment by davinchia** [comment]
we are going to shift this to after all the frontend work for cloud is done

**Comment by davinchia** [comment]
e.g. #5003 , #4711

**Comment by timroes** [comment]
@davinchia Is this still relevant, or can this be closed?
