### ISSUE TITLE
Instagram connector failing for all user-related tables

### ISSUE THREAD

**Issue by jimbeepbeep** [airbytehq/airbyte#4783]
## Enviroment
- **Airbyte version**:  example is 0.27.0-alpha
- **OS Version / Instance**: GCP Compute Engine (n1-standard-1)
- **Deployment**: Docker
- **Source Connector and version**: Instagram 0.1.6
- **Destination Connector and version**: BigQuery 0.3.6
- **Severity**: High
- **Step where error happened**: Sync job 

## Current Behavior
I upgraded both Airbyte and the Instagram Connector on 9th July for housekeeping, however since that date the user_insights, user_lifetime_insights and users have been failing.

## Expected Behavior
Sync all tables as normal

## Logs
[logs-268-2.txt](https://github.com/airbytehq/airbyte/)
[logs-268-1.txt](https://github.com/airbytehq/airbyte/)
[logs-268-0.txt](https://github.com/airbytehq/airbyte/)

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Set up Instagram Source
2. Set up BigQuery Destination
3. Sync (all defaults)

**Comment by sherifnada** [comment]
thanks for creating the report @jimbeepbeep , will look into it!

**Comment by keu** [comment]
@jimbeepbeep, I tracked the issue, it is in different format of state files that new version uses. If that is possible could you please remove states and try again?

**Comment by jimbeepbeep** [comment]
Thanks for the quick response - I've just upgraded Airbyte and Connector versions today and am running a full sync, however we have 140+ accounts so it takes a while.  When it is complete (success or fail) I will post the new logs here.

**Comment by jimbeepbeep** [comment]
It's been running for about 12hrs already, which normally means it'll fail... logs are here:

[logs-285-0.txt](https://github.com/airbytehq/airbyte/files/6833508/logs-285-0.txt)

**Comment by keu** [comment]
Thanks, @jimbeepbeep , just to clarify, did you reset the connection from the UI? because I still can see errors related to old state file format.

**Comment by jimbeepbeep** [comment]
I didn't as I don't want to reset old data - is there a a way of doing that but preserving historic data?

**Comment by sherifnada** [comment]
@keu I think we will have to add backwards compatibility for the old format in the connector itself, manually changing state is not going to be very doable here

**Comment by jimbeepbeep** [comment]
Just leaving the logs here - this is the full failed fun from yesterday, there should be ~120k records but it says it's failed with ~360k records, looking like it's processing the media stream three times:

[logs-285-0 (1).txt](https://github.com/airbytehq/airbyte/files/6834287/logs-285-0.1.txt)

**Comment by jimbeepbeep** [comment]
Final fail log, sync disabled for now
[logs-285-1.txt](https://github.com/airbytehq/airbyte/files/6835748/logs-285-1.txt)

**Comment by keu** [comment]
@jimbeepbeep , I have added support of previous state format. Once thing that still not clear to me - you said `360k records` where do you see this? I can't think of any reason it reads any stream multiple times.

**Comment by jimbeepbeep** [comment]
Check this out: 
![Screen Shot 2021-07-18 at 4 58 00 pm](https://user-images.githubusercontent.com/34912260/126072013-f6651435-3859-4dc3-88a9-e644d23516dc.png)

You can see on the successful runs there are ~120k records, but on the failed runs there are approx ~360k per run: 
![Screen Shot 2021-07-18 at 5 00 12 pm](https://user-images.githubusercontent.com/34912260/126072063-d64f7d96-ce41-4035-8b72-83238d10fb8d.png)
![Screen Shot 2021-07-18 at 5 00 04 pm](https://user-images.githubusercontent.com/34912260/126072064-566cee5f-def5-4226-8008-068689922661.png)
![Screen Shot 2021-07-18 at 4 59 57 pm](https://user-images.githubusercontent.com/34912260/126072065-cc6f4940-d4f2-40d1-a0ec-61de0058ae2a.png)

**Comment by keu** [comment]
Thanks, @jimbeepbeep, I can see 3 attempts, so I think this is expected behavior, not very optimal though.

**Comment by keu** [comment]
@jimbeepbeep, I've just published the new version, please let me if the issue was solved.
Thanks

**Comment by jimbeepbeep** [comment]
Thanks @keu, I have upgraded to the latest connector and a running the sync, fingers crossed I'll let you know how it goes

**Comment by jimbeepbeep** [comment]
@keu you are a legend sir, works an absolute dream.  Thanks so much for your hard work, @sherifnada your team is amazing, thanks as always.  Also thanks to whoever made the new Airbyte upgrade process so smooooth, it was a total nightmare before and now it works like magic!

**Comment by keu** [comment]
Thank you for your kind words, @jimbeepbeep. This false wouldn't be possible without the hard work of @yevhenii-ldv. And of course, thanks for your patience trying all our fixes.
