### ISSUE TITLE
The Avro output format for the S3 destination is not selectable on the UI

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4790]
## Enviroment
- **Airbyte version**:  0.27.0-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Destination Connector and version**: S3 0.1.8
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
When I try to setup an S3 destination with the Avro output format, the page will reset itself, and there is a `TypeError` in the console.

## Expected Behavior
Users should be able to select Avro as the output format.

## Logs
There is no warning or error from the server log.

## Steps to Reproduce
1. Go to the `Destinations` page and select `S3` as the destination type:

<img width="485" alt="Screen Shot 2021-07-16 at 11 23 31" src="https://user-images.githubusercontent.com/1933157/125992486-b1f4acaf-14d6-48fc-bed2-1933f28631ed.png">

2. Scroll down to the `Output Format` and select `Avro: Apache Avro`:

<img width="409" alt="Screen Shot 2021-07-16 at 11 23 40" src="https://user-images.githubusercontent.com/1933157/125992543-7d18e889-2d31-413f-a654-ed1604884d9f.png">

3. The page will reset all my previous selections:

<img width="836" alt="Screen Shot 2021-07-16 at 11 26 00" src="https://user-images.githubusercontent.com/1933157/125992601-d2f42651-fe0c-4d9d-bdf3-8cb36bf9fb2b.png">

4. Check the console, and you can see the error message.

```js
TypeError: Cannot read property 'order' of undefined
    at FormSection.tsx:157
    at Array.some (<anonymous>)
    at FormSection.tsx:157
    at Object.useMemo (react-dom.production.min.js:172)
    at t.useMemo (react.production.min.js:23)
    at e (FormSection.tsx:154)
    at oa (react-dom.production.min.js:157)
    at Vs (react-dom.production.min.js:267)
    at Eu (react-dom.production.min.js:250)
    at Cu (react-dom.production.min.js:250)
```

## Are you willing to submit a PR?
@Jamakase, would you mind taking a look? One potential root cause I an think of is that the Avro output `spec` has a nested `oneOf` object inside another `oneOf` object. Does the frontend support multiple layers of `oneOf`s?

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-s3/src/main/resources/spec.json#L87

**Comment by AlexandruManolache1** [comment]
Same behaviour is for GCS as destination connector
