### ISSUE TITLE
[connector-request] cognitoforms

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47944]
### Topic

This is a suggestion to create a connector for cognitoforms using the UI Connector Builder. The website for the connector is https://www.cognitoforms.com/

### Relevant information

https://www.cognitoforms.com/support/476/data-integration/cognito-forms-api/api-reference

**Comment by parthiv11** [comment]
@marcosmarxm check this if a connector can be made for this as 2 possible streams for now

if connector can be made assign me

**Comment by marcosmarxm** [comment]
You need to answer what insights you can extract from this data.

**Comment by parthiv11** [comment]
> You need to answer what insights you can extract from this data.

currently only forms and form fields 

entries required entry_id but no endpoint provides entry_id

**Comment by marcosmarxm** [comment]
Being a form service the most important is to have access to all entries from forms. I don't think at the moment this is a good one.
