### ISSUE TITLE
[connector-request] Formbricks

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47948]
### Topic

This is a suggestion to create a connector for formbricks using the UI Connector Builder. The website for the connector is https://www.formbricks.com/

### Relevant information

https://documenter.getpostman.com/view/11026000/2sA3Bq5XEh

**Comment by parthiv11** [comment]
@marcosmarxm check and assign me

**Comment by marcosmarxm** [comment]
What insights / use cases you can extract from this service?

**Comment by parthiv11** [comment]
> What insights / use cases you can extract from this service?

![Image](https://github.com/user-attachments/assets/05abaeae-7012-4b5b-ae1b-76f4be27933d)

**Comment by marcosmarxm** [comment]
go forward
