### ISSUE TITLE
[connector-request] SendFox

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47953]
### Topic

This is a suggestion to create a connector for SendFox using the UI Connector Builder. The website for the connector is https://SendFox.com/

### Relevant information

https://help.sendfox.com/article/278-endpoints

**Comment by parthiv11** [comment]
@marcosmarxm check and assign me

**Comment by marcosmarxm** [comment]
What insights / use cases you can extract from this service?
