### ISSUE TITLE
[connector-request] Pabbly Subscription Billing

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47956]
### Topic

This is a suggestion to create a connector for Pabbly using the UI Connector Builder. The website for the connector is [Pabbly Subscription Billing](https://www.pabbly.com/subscriptions/)

### Relevant information

https://apidocs.pabbly.com/

**Comment by parthiv11** [comment]
@marcosmarxm please approve and assign

**Comment by marcosmarxm** [comment]
What insights / use cases you can extract from this service?

**Comment by parthiv11** [comment]
> What insights / use cases you can extract from this service?

![Image](https://github.com/user-attachments/assets/2b6e552a-2a5c-44bc-9754-e0ca9a658d1e)

**Comment by parthiv11** [comment]
@marcosmarxm need help in refund stream,

**Comment by bishalbera** [comment]
> [@marcosmarxm](https://github.com/marcosmarxm) need help in refund stream,

marcos mostly reply you after 12hrs till then maybe I can help. whats the issue? @parthiv11

**Comment by parthiv11** [comment]
In refunds endpoint return status code 400 when no refund is provided for corresponding transaction and 200 with record when refund is done 


As status code of 400 is returned for some transaction, UI Builder restricts me from making PR

Already tried error handler in builder with code 400 to ignore

@bishalbera see if you can help, thank you for helping

**Comment by bishalbera** [comment]
> In refunds endpoint return status code 400 when no refund is provided for corresponding transaction and 200 with record when refund is done
> 
> As status code of 400 is returned for some transaction, UI Builder restricts me from making PR
> 
> Already tried error handler in builder with code 400 to ignore
> 
> [@bishalbera](https://github.com/bishalbera) see if you can help, thank you for helping

@parthiv11 I'm not sure about this behaviour. usually 400 status code means you're missing some parameters or something like that. if there is no refund associated with that `customer_id` it should send back an empty array with 200 status code . At lease that what happens with me. It's quite normal that every transaction will not be refunded. Did you doubled checked that you're not missing any required parameters cause 400 means bad req .

**Comment by bishalbera** [comment]
After looking into the docs I understood that you are passing the `customer_id` as path parameter not query parameter. Idealy it should give you 404 for that. I think there's nothing you can do as its apis behaviour. You can mostly supress that 400 error using error handlers which I believe you already did. Now lets wait for what @marcosmarxm has to say :)

**Comment by marcosmarxm** [comment]
> In refunds endpoint return status code 400 when no refund is provided for corresponding transaction and 200 with record when refund is done
> 
> As status code of 400 is returned for some transaction, UI Builder restricts me from making PR
> 
> Already tried error handler in builder with code 400 to ignore
> 
> [@bishalbera](https://github.com/bishalbera) see if you can help, thank you for helping

The Connector Builder is not testing error handlers today. I'm going to take a look in your workspace later today.
