### ISSUE TITLE
[connector-request] SendPulse

### ISSUE THREAD

**Issue by parthiv11** [airbytehq/airbyte#47955]
### Topic

This is a suggestion to create a connector for sendpulse using the UI Connector Builder. The website for the connector is https://sendpulse.com/

### Relevant information

https://sendpulse.com/tr/integrations/api

**Comment by parthiv11** [comment]
@marcosmarxm check and assign

**Comment by marcosmarxm** [comment]
What insights / use cases you can extract from this service?

**Comment by parthiv11** [comment]
> What insights / use cases you can extract from this service?

![Image](https://github.com/user-attachments/assets/4485e811-0e46-4aab-87a3-ba36ca52e453)

**Comment by marcosmarxm** [comment]
Go forward
