### ISSUE TITLE
[connector-request] Mail250

### ISSUE THREAD

**Issue by ombhardwajj** [airbytehq/airbyte#47977]
This is a suggestion to create a connector for Mail250 using the UI Connector Builder.
The website for the connector is https://mail250.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

**Comment by bishalbera** [comment]
@ombhardwajj can you give me api docs link for this?

**Comment by ombhardwajj** [comment]
Ofcourse my friend @bishalbera !! 😄 
Here it is https://api.mail250.com/
And just curious—what’s inspired your own affectionate attention to my issues lately? 😉

**Comment by bishalbera** [comment]
You didn't commented that you're working on these 🙄...or willing to work

**Comment by ombhardwajj** [comment]
@bishalbera I raised this issue specifically because I plan to work on it! 😊 I already have an active account and am just waiting for my API key from the team. As soon as that’s in hand, I’ll move forward with building the connector.

**Comment by ombhardwajj** [comment]
The Mail250 team has informed me that the APIs are no longer in existence and hence the connector can not be built.
Closing this issue!
