### ISSUE TITLE
[connector-request] Tinyemail

### ISSUE THREAD

**Issue by ombhardwajj** [airbytehq/airbyte#47971]
This is a suggestion to create a connector for Tinyemail using the UI Connector Builder.
The website for the connector is https://tinyemail.com/

If you want to try, claim this issue and start working on it following the steps below.

### Steps:
1. Comment in the issue and wait to be assigned to start working on it.
2. Map the API endpoints (get approval to move to step 3).
3. Describe steps to get credentials.
4. Create the connector using the UI Builder.   

> Airbyte doesn't have sandbox credentials for this connector. You must have access/credentials to the service provider to create the connector.

> This is a suggestion, and there may be cases where creating the connector using the Builder won't be possible. To minimize the risk of investing a lot of time directly in creating the connector, we strongly recommend following the steps above.

**Comment by bishalbera** [comment]
@marcosmarxm we can made only campaigns and contacts stream with this . Do you think we should proceed with this source?

**Comment by ombhardwajj** [comment]
Hi @bishalbera  , just wanted to add that having two streams, like campaigns and contacts, is a solid start for a useful connector. There are connectors on Airbyte's marketplace that support just a single stream, such as [Exchangerates](https://docs.airbyte.com/integrations/sources/exchange-rates), and they still serve valuable use cases.

With TinyEmail, campaigns and contacts cover essential data for many marketing workflows

**Comment by bishalbera** [comment]
> Hi [@bishalbera](https://github.com/bishalbera) , just wanted to add that having two streams, like campaigns and contacts, is a solid start for a useful connector. There are connectors on Airbyte's marketplace that support just a single stream, such as [Exchangerates](https://docs.airbyte.com/integrations/sources/exchange-rates), and they still serve valuable use cases.
> 
> With TinyEmail, campaigns and contacts cover essential data for many marketing workflows

That's a point

**Comment by marcosmarxm** [comment]
> [@marcosmarxm](https://github.com/marcosmarxm) we can made only campaigns and contacts stream with this . Do you think we should proceed with this source?

I'll review the contribution and if it has stream are useful to extract and generate insights it's ok.
