### ISSUE TITLE
SendGrid connector fails, even though log says successful

### ISSUE THREAD

**Issue by rahimnathwani** [airbytehq/airbyte#4801]
## Environment
- **Airbyte version**: 0.27.3-alpha
- **OS Version / Instance**: Linux 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux
- **Deployment**: docker
- **Source Connector and version**: Sendgrid 0.2.5
- **Destination Connector and version**: Postgres 0.3.6
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync job fails and gives up after 3 tries, even though the logs say 'completed successfully'. And no data gets written to my target.

## Expected Behavior
Sync job should complete and populate my database.

## Logs
[logs-168-0.txt](https://github.com/airbytehq/airbyte/files/6833926/logs-168-0.txt)

**Comment by sherifnada** [comment]
@rahimnathwani is the UI showing the job status as succeeded or failed? The logs are misleading here: Airbyte makes a best effort to sync data in the case of a failure. The "success" part is referring specifically to normalization. 

If the job status in the UI or API is showing successful, that's a real issue. 

I'm attempting to reproduce this on my side but haven't found success so far. Will update you as soon as I can repro

**Comment by rahimnathwani** [comment]
In the UI it's showing failure.

**Comment by sherifnada** [comment]
fixed in #4839
