### ISSUE TITLE
Transient failure in JobSubmitterTest

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4804]
From time to time, `JobSubmitterTest` may fail with the following exception:

```
JobSubmitterTest > OnlyOneJobIdRunning > testOnlyOneJobCanBeSubmittedAtOnce() FAILED
    org.mockito.exceptions.verification.TooManyActualInvocations: 
    jobPersistence.getNextJob();
    Wanted 5 times:
    -> at io.airbyte.scheduler.app.JobSubmitterTest$OnlyOneJobIdRunning.testOnlyOneJobCanBeSubmittedAtOnce(JobSubmitterTest.java:264)
    But was 6 times:
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
    -> at io.airbyte.scheduler.app.JobSubmitter.run(JobSubmitter.java:74)
        at io.airbyte.scheduler.app.JobSubmitterTest$OnlyOneJobIdRunning.testOnlyOneJobCanBeSubmittedAtOnce(JobSubmitterTest.java:264)
```

The most recent example is [this one](https://github.com/airbytehq/airbyte/runs/3090175431).

I briefly looked into it, but have not figured it out yet. @davinchia, FYI.

**Comment by davinchia** [comment]
This happens before the counter increments but the thread finishes before the call is actually made.

I've removed this and replaced it with an `atLeast(2)` check. The same principle applies - we want to make sure the final call is only made once even though there are more than one upstream calls.

Part of #5292 .

**Comment by tuliren** [comment]
Oh, I see. Since the test calls `shutdownNow` on the thread pool, the pool can be shut down without finishing its work. If `shutdown` is called instead, I think the check will always be correct.

**Comment by davinchia** [comment]
Yeap, but I figured we don't actually have to wait as long as we test that the second call is always once despite the first call being greater than one (hence atLeast 2)
