### ISSUE TITLE
[source-gorgias] malformed date parsing

### ISSUE THREAD

**Issue by appleseed-iii** [airbytehq/airbyte#48106]
### Connector Name

source-gorgias

### Connector Version

0.0.1

### What step the error happened?

During the sync

### Relevant information

# Error

There are a handful of streams failling on date time parsing with errors like the below

```
No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00
```

## Steps

we are using the gorgias connector with the following streams turned on:

1. gorgias_account
2. gorgias_custom-fields
3. gorgias_customers
4. gorgias_events
5. gorgias_integrations
6. gorgias_messages
7. gorgias_satisfaction-surveys
8. gorgias_tags
9. gorgias_teams
10. gorgias_tickets
11. gorgias_users
12. gorgias_views
13. gorgias_views_items

Error logs are below, showing which streams are failing on the date time parsing.

cc: @natikgadzhi

### Relevant log output

2024-11-01 10:05:06 source > Encountered an exception while reading stream tickets
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 192, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 381, in read_records
    self.cursor.observe(_slice, current_record)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 138, in observe
    self._is_within_daterange_boundaries(record, stream_slice.get(start_field), stream_slice.get(end_field))  # type: ignore # we know that stream_slices for these cursors will use a string representing an unparsed date
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 346, in _is_within_daterange_boundaries
    return start_datetime_boundary <= self.parse_date(record_cursor_value) <= end_datetime_boundary
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 255, in parse_date
    raise ValueError(f"No format in {self.cursor_datetime_formats} matching {date}")
ValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00

...

2024-11-01 10:45:52 source > Encountered an exception while reading stream satisfaction-surveys
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 192, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 381, in read_records
    self.cursor.observe(_slice, current_record)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 134, in observe
    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 255, in parse_date
    raise ValueError(f"No format in {self.cursor_datetime_formats} matching {date}")
ValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-07-12T18:07:34+00:00

...

2024-11-01 11:04:24 source > Encountered an exception while reading stream events
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 192, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 381, in read_records
    self.cursor.observe(_slice, current_record)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 134, in observe
    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 255, in parse_date
    raise ValueError(f"No format in {self.cursor_datetime_formats} matching {date}")
ValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-10-29T17:36:36+00:00

...

2024-11-01 11:04:25 source > Encountered an exception while reading stream views_items
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 192, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 381, in read_records
    self.cursor.observe(_slice, current_record)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py", line 128, in observe
    self._cursor_per_partition[self._to_partition_key(stream_slice.partition)].observe(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 138, in observe
    self._is_within_daterange_boundaries(record, stream_slice.get(start_field), stream_slice.get(end_field))  # type: ignore # we know that stream_slices for these cursors will use a string representing an unparsed date
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 346, in _is_within_daterange_boundaries
    return start_datetime_boundary <= self.parse_date(record_cursor_value) <= end_datetime_boundary
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 255, in parse_date
    raise ValueError(f"No format in {self.cursor_datetime_formats} matching {date}")
ValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00

...

2024-11-01 11:04:25 source > Encountered an exception while reading stream messages
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 133, in read
    yield from self._read_stream(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py", line 239, in _read_stream
    for record_data_or_message in record_iterator:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py", line 192, in read
    for record_data_or_message in records:
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py", line 136, in read_records
    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py", line 381, in read_records
    self.cursor.observe(_slice, current_record)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 134, in observe
    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py", line 255, in parse_date
    raise ValueError(f"No format in {self.cursor_datetime_formats} matching {date}")
ValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T10:59:29+00:00

...

2024-11-01 11:05:39 replication-orchestrator > failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 133, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 239, in _read_stream\n    for record_data_or_message in record_iterator:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py\", line 192, in read\n    for record_data_or_message in records:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 136, in read_records\n    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 381, in read_records\n    self.cursor.observe(_slice, current_record)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 138, in observe\n    self._is_within_daterange_boundaries(record, stream_slice.get(start_field), stream_slice.get(end_field))  # type: ignore # we know that stream_slices for these cursors will use a string representing an unparsed date\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 346, in _is_within_daterange_boundaries\n    return start_datetime_boundary <= self.parse_date(record_cursor_value) <= end_datetime_boundary\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 255, in parse_date\n    raise ValueError(f\"No format in {self.cursor_datetime_formats} matching {date}\")\nValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00\n",
  "timestamp" : 1730455506486,
  "streamDescriptor" : {
    "name" : "tickets"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-07-12T18:07:34+00:00",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 133, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 239, in _read_stream\n    for record_data_or_message in record_iterator:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py\", line 192, in read\n    for record_data_or_message in records:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 136, in read_records\n    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 381, in read_records\n    self.cursor.observe(_slice, current_record)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 134, in observe\n    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 255, in parse_date\n    raise ValueError(f\"No format in {self.cursor_datetime_formats} matching {date}\")\nValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-07-12T18:07:34+00:00\n",
  "timestamp" : 1730457952637,
  "streamDescriptor" : {
    "name" : "satisfaction-surveys"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-10-29T17:36:36+00:00",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 133, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 239, in _read_stream\n    for record_data_or_message in record_iterator:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py\", line 192, in read\n    for record_data_or_message in records:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 136, in read_records\n    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 381, in read_records\n    self.cursor.observe(_slice, current_record)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 134, in observe\n    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 255, in parse_date\n    raise ValueError(f\"No format in {self.cursor_datetime_formats} matching {date}\")\nValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-10-29T17:36:36+00:00\n",
  "timestamp" : 1730459064375,
  "streamDescriptor" : {
    "name" : "events"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 133, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 239, in _read_stream\n    for record_data_or_message in record_iterator:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py\", line 192, in read\n    for record_data_or_message in records:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 136, in read_records\n    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 381, in read_records\n    self.cursor.observe(_slice, current_record)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py\", line 128, in observe\n    self._cursor_per_partition[self._to_partition_key(stream_slice.partition)].observe(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 138, in observe\n    self._is_within_daterange_boundaries(record, stream_slice.get(start_field), stream_slice.get(end_field))  # type: ignore # we know that stream_slices for these cursors will use a string representing an unparsed date\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 346, in _is_within_daterange_boundaries\n    return start_datetime_boundary <= self.parse_date(record_cursor_value) <= end_datetime_boundary\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 255, in parse_date\n    raise ValueError(f\"No format in {self.cursor_datetime_formats} matching {date}\")\nValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00\n",
  "timestamp" : 1730459065449,
  "streamDescriptor" : {
    "name" : "views_items"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T10:59:29+00:00",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 133, in read\n    yield from self._read_stream(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 239, in _read_stream\n    for record_data_or_message in record_iterator:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/streams/core.py\", line 192, in read\n    for record_data_or_message in records:\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/declarative_stream.py\", line 136, in read_records\n    yield from self.retriever.read_records(self.get_json_schema(), stream_slice)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/retrievers/simple_retriever.py\", line 381, in read_records\n    self.cursor.observe(_slice, current_record)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 134, in observe\n    is_highest_observed_cursor_value = not self._highest_observed_cursor_field_value or self.parse_date(\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py\", line 255, in parse_date\n    raise ValueError(f\"No format in {self.cursor_datetime_formats} matching {date}\")\nValueError: No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T10:59:29+00:00\n",
  "timestamp" : 1730459065712,
  "streamDescriptor" : {
    "name" : "messages"
  }
}, {
  "failureOrigin" : "source",
  "failureType" : "config_error",
  "externalMessage" : "During the sync, the following streams did not sync successfully: tickets: AirbyteTracedException(\"No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00\")\nsatisfaction-surveys: AirbyteTracedException(\"No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-07-12T18:07:34+00:00\")\nevents: AirbyteTracedException(\"No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-10-29T17:36:36+00:00\")\nviews_items: AirbyteTracedException(\"No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T08:48:50+00:00\")\nmessages: AirbyteTracedException(\"No format in ['%Y-%m-%dT%H:%M:%S.%f%z'] matching 2024-11-01T10:59:29+00:00\")",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 8, in <module>\n    run()\n  File \"/airbyte/integration_code/source_declarative_manifest/run.py\", line 93, in run\n    handle_command(args)\n  File \"/airbyte/integration_code/source_declarative_manifest/run.py\", line 46, in handle_command\n    handle_local_manifest_command(args)\n  File \"/airbyte/integration_code/source_declarative_manifest/run.py\", line 53, in handle_local_manifest_command\n    launch(source, args)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 259, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 131, in run\n    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.read(source_spec, config, config_catalog, state))\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/entrypoint.py\", line 189, in read\n    for message in self.source.read(self.logger, config, catalog, state):\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/declarative/manifest_declarative_source.py\", line 165, in read\n    yield from super().read(logger, config, catalog, state)\n  File \"/usr/local/lib/python3.10/site-packages/airbyte_cdk/sources/abstract_source.py\", line 177, in read\n    raise AirbyteTracedException(message=error_message, failure_type=FailureType.config_error)\nairbyte_cdk.utils.traced_exception.AirbyteTracedException: None\n",
  "timestamp" : 1730459065718
}, {
  "failureOrigin" : "destination",
  "failureType" : "transient_error",
  "internalMessage" : "Some streams either received an INCOMPLETE stream status, or did not receive a stream status at all: null.gorgias_views_items, null.gorgias_account, null.gorgias_customers, null.gorgias_users, null.gorgias_views, null.gorgias_satisfaction-surveys, null.gorgias_tickets, null.gorgias_tags, null.gorgias_events, null.gorgias_integrations, null.gorgias_messages, null.gorgias_custom-fields, null.gorgias_teams\nio.airbyte.commons.exceptions.TransientErrorException: Some streams were unsuccessful due to a source error. See logs for details.",
  "externalMessage" : "Some streams were unsuccessful due to a source error. See logs for details.",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "from_trace_message" : true,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.commons.exceptions.TransientErrorException: Some streams were unsuccessful due to a source error. See logs for details.\n\tat io.airbyte.cdk.integrations.destination.async.AsyncStreamConsumer.close(AsyncStreamConsumer.kt:215)\n\tat kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseableJVM.kt:48)\n\tat io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.kt:215)\n\tat io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.kt:119)\n\tat io.airbyte.cdk.integrations.base.IntegrationRunner.run$default(IntegrationRunner.kt:113)\n\tat io.airbyte.integrations.destination.bigquery.BigQueryDestinationKt.main(BigQueryDestination.kt:566)\n",
  "timestamp" : 1730459139237
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromSource(BufferedReplicationWorker.java:364)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithHeartbeatCheck$3(BufferedReplicationWorker.java:222)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1730459066640
}, {
  "failureOrigin" : "destination",
  "internalMessage" : "Destination process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the destination connector",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:500)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:215)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1730459139316
}, {
  "failureOrigin" : "replication",
  "internalMessage" : "io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 19,
    "jobId" : 94
  },
  "stacktrace" : "java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:545)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:243)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.LocalContainerAirbyteDestination.close(LocalContainerAirbyteDestination.kt:62)\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:543)\n\t... 5 more\n",
  "timestamp" : 1730459139338
} ]

### Contribute

- [x] Yes, I want to contribute

**Comment by btkcodedev** [comment]
Yep, on it👍

**Comment by btkcodedev** [comment]
PR https://github.com/airbytehq/airbyte/pull/48378
