### ISSUE TITLE
Cannot configure CDC in Postgres Source

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4810]
## Enviroment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**:  macOS
- **Deployment**:  Docker
- **Source Connector and version**: Postgres source v0.3.7
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
* I want to configure postgres for cdc but the option does not appear in the UI.
![Screen Shot 2021-07-18 at 3 03 25 PM](https://user-images.githubusercontent.com/9092207/126083723-214fe37f-ff71-402f-be20-7079d8856561.png)

@sherifnada  fyi

**Comment by sherifnada** [comment]
@cgardens I'm unable to reproduce this on 0.27.3-alpha, where was this issue reported from?

**Comment by cgardens** [comment]
i was on a dev branch that i thought was master. but if it' can't be
recreated let's close.
