### ISSUE TITLE
Figure out why logging Process.info does not work in Docker.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4824]
## Tell us about the problem you're trying to solve
All the logging in `WorkerUtils` is gated on Kubernetes because the process implementation does not fulfill the `info` method even though we are using Java's native `ProcessBuilder`. Why is that?

**Comment by oustynova** [comment]
@davinchia is it still actual?

**Comment by davinchia** [comment]
I think we figured this out. I'll close for now.
