### ISSUE TITLE
Source Facebook Marketing: SAT fails on schema validation

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#4827]
The problem with schema is that FB wraps numeric values into strings.
The schema says it is `null` or `numeric` but in the record it is `"1234"`.

## Steps to Reproduce
Run SAT on the latest FB connector
**UPDATE:** use this comment for instructions https://github.com/airbytehq/airbyte/issues/4827#issuecomment-886981239

## Possible fix
1. update schemas - set type = `['null', 'string']`, this is less desirable solution because destination will loose any type info.
2. do transform while reading inside streams, according to schema type. i.e. 'numeric' -> int, float

**Comment by Zirochkaa** [comment]
I can't reproduce this bug because of the following error:

![image](https://user-images.githubusercontent.com/19872253/126965480-edbe22c3-10e4-4b47-8309-732c57439f27.png)

The above error was also occurring in [these 3 failed builds](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/source-facebook-marketing/):
<img width="965" alt="image" src="https://user-images.githubusercontent.com/19872253/126965828-dea33bf3-6bb2-4999-aa48-366c37000db0.png">

**Comment by Zirochkaa** [comment]
I had to change few things in order to run tests and all tests passed, see [screenshot](https://github.com/airbytehq/airbyte/pull/4978#issue-696866063). Also I linked a PR with changes I made to tests. So I can't reproduce this issue.

**Comment by Zirochkaa** [comment]
I commented out `validate_schema: no` line in `acceptance-test-config.yml` file and still wasn't able to reproduce this issue.

![image](https://user-images.githubusercontent.com/19872253/126995634-c3fc0a6d-76c9-4fa4-8937-1acf10e2ebf2.png)

**Comment by keu** [comment]
Ok, it seems our config bypass the dates with records, so all problematic streams are empty. To reproduce this use the following config:
```json
{
  "start_date": "2021-02-01T00:00:00Z",
  "account_id": "your_account",
  "access_token": "your_token",
  "include_deleted": false,
  "insights_lookback_window": 14,
  "insights_days_per_job": 1,
}
```

```
ERROR    root:test_core.py:136 The ad_sets stream has the following schema errors:
'0' is not of type 'null', 'number'

Failed validating 'type' in schema['properties']['daily_budget']:
    {'exclusiveMaximum': True,
     'exclusiveMinimum': True,
     'maximum': 100000000000000000000000000000000,
     'minimum': -100000000000000000000000000000000,
     'multipleOf': 1e-06,
     'type': ['null', 'number']}

On instance['daily_budget']:
    '0'
--------------------------------------------------------------------------------
'5000' is not of type 'null', 'number'

Failed validating 'type' in schema['properties']['budget_remaining']:
    {'exclusiveMaximum': True,
     'exclusiveMinimum': True,
     'maximum': 100000000000000000000000000000000,
     'minimum': -100000000000000000000000000000000,
     'multipleOf': 1e-06,
     'type': ['null', 'number']}

On instance['budget_remaining']:
    '5000'
--------------------------------------------------------------------------------
```
in the end
```
        if streams_errors:
>           pytest.fail(f"Please check your json_schema in selected streams {tuple(streams_errors.keys())}.")
E           Failed: Please check your json_schema in selected streams ('ad_sets', 'ads_insights', 'ads_insights_age_and_gender').
```

**Comment by keu** [comment]
@Zirochkaa  please check this PR to get the idea 
https://github.com/airbytehq/airbyte/pull/4994

**Comment by Zirochkaa** [comment]
@keu which config do we have in GitHub secrets for Facebook Marketing source?

**Comment by Zirochkaa** [comment]
We need to:
- [ ] Create `transform()` function and apply it on each record (~10h)
- [ ] Check that `transform()` works for 3 above mentioned streams (~2h)

**Comment by Zirochkaa** [comment]
We decided to use this issue as an experiment to write a generic class for performing transformations of record so it'll require more time than the estimate above.

**Comment by Zirochkaa** [comment]
With latest changes from `master` branch SAT tests are failing:

![Screen Shot 2021-07-30 at 10 41 15 PM](https://user-images.githubusercontent.com/19872253/130197998-a4a4586b-9606-4432-9c76-8630f1b2dd7d.png)

**Comment by Zirochkaa** [comment]
With latest changes from master branch SAT tests are failing:

![image](https://user-images.githubusercontent.com/19872253/130198096-1cc9b7c0-b44c-4956-ba00-b36e69ff4eea.png)

**Comment by Zirochkaa** [comment]
Blocked on #5592.
