### ISSUE TITLE
Add bash translations for connector development on Windows

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4832]
## Tell us about the problem you're trying to solve
While developing on the Airbyte platform isn't supported on Windows, developing Python connectors should be completely doable. We should add some bash command translations in READMEs and docs to make sure these instructions are clear for Windows devs.

**Comment by blake-enyart** [comment]
@sherifnada, I'm limited to a Windows machine right now. Doe you have any recommendations on CDK connector development working on Windows?
