### ISSUE TITLE
Reset pods are created without tolerations

### ISSUE THREAD

**Issue by SamyDjemai** [airbytehq/airbyte#48380]
### Helm Chart Version

1.1.1

### What step the error happened?

Other

### Relevant information

While replication pods take tolerations into consideration, reset pods are created without tolerations, which results in Pending pods due to node taints.

I've opened https://github.com/airbytehq/airbyte-platform/pull/369 to solve this problem.

**Comment by marcosmarxm** [comment]
@abuchanan-airbyte is working on a fix (if I'm not wrong) and it will be released in next release. Please correct me if I'm wrong.

**Comment by abuchanan-airbyte** [comment]
I wasn't aware or working on a fix, but the linked PR (https://github.com/airbytehq/airbyte-platform/pull/369) looks correct. 

This technically belongs to the Move Team, I think.

**Comment by abuchanan-airbyte** [comment]
Fixed in https://github.com/airbytehq/airbyte-platform/commit/84a7536639fceda98cb923e832369ed533f734cf 

The fix will be included in the 1.2 release

**Comment by marcosmarxm** [comment]
You're awesome @abuchanan-airbyte !
