### ISSUE TITLE
Shopify connector should convert prices into numbers

### ISSUE THREAD

**Issue by rohansingh** [airbytehq/airbyte#4841]
## Tell us about the problem you're trying to solve
Most price-related fields created by the Shopify connector are strings. For example, `total_price` on `orders` is a string. This makes it difficult to do simple math or create sales reports.

## Describe the solution you’d like
I'd like the Shopify connector to transform price fields into numbers.

## Describe the alternative you’ve considered or used
I could write a custom transformation with dbt, but it seems like the Shopify connector should natively do this.

## Additional context
Discussion here:
https://airbytehq.slack.com/archives/C01MFR03D5W/p1626731077032400

Shopify's API returns prices as strings, often with a separate field specifying the currency. See fields like `total_price` and `total_tax` here:
https://shopify.dev/api/admin/rest/reference/orders/order#properties-2021-07

So it makes sense that the connector treats these as strings. However, it'd be really nice if it could handle the transformation.

## Are you willing to submit a PR?
This is a bit beyond me at the moment.

**Comment by Zirochkaa** [comment]
Scoping:

- [ ] Look through each stream and change the type of field from `"string"` to `"number"` where field is actually a number (4-5 h because, at least for me, Shopify docs are very laggy and slow)
- [ ] Create `transform()` function and apply it on each record in `ShopifyStream.parse_response()` and `IncrementalShopifyStream.filter_records_newer_than_state()` functions (~2h)
- [ ] Check that `transform()` works for all streams (~1h)

**Comment by vitaliizazmic** [comment]
I detected next price fields, which should be changed to number:
1. Abandoned checkouts
    - tax_lines
      - price
    - total_line_items_price
    - total_tax
    - subtotal_price
    - line_items
      - compare_at_price
      - line_price
      - discount_allocations
        - amount
      - tax_lines
         - price
      - price
    - total_discounts
    - shipping_lines
      - price
      - tax_lines
      - price
      - original_shop_price
      - original_shop_markup
    - customer
      - total_spent
    - total_price

2. Collects
	
3. Custom Collections

4. Customers
    - total_spent

5. Discount Codes

6. Draft Orders
    - customer
      - total_spent
    - line_items
      - price
      - price_set
        - shop_money
          - amount
        - presentment_money
          - amount
      - total_discount
      - total_discount_set
        - shop_money
          - amount
        - presentment_money
          - amount
      - tax_lines
        - price
        - price_set
	  - shop_money
            - amount
          - presentment_money
            - amount
    - shipping_line
      - tax_lines
        - price
	- price_set
          - shop_money
            - amount
          - presentment_money
            - amount
      - price
    - tax_lines
      - price
      - price_set
        - shop_money
          - amount
        - presentment_money
          - amount
    - total_price

7. Metafields

8. Order Refunds
    - refund_line_items
      - subtotal_set
        - shop_money
          - amount
        - presentment_money
          - amount
    - total_tax_set
      - shop_money
        - amount
      - presentment_money
        - amount
    - total_tax
    - line_item
			price
			tax_lines
				price_set
					shop_money
						amount
					presentment_money
						amount
				price
			price_set
				shop_money
					amount
				presentment_money
					amount
			pre_tax_price
			total_discount_set
				shop_money
					amount
				presentment_money
					amount
			discount_allocations
				amount
				amount_set
					shop_money
						amount
					presentment_money
						amount
			pre_tax_price_set
				shop_money
					amount
				presentment_money
					amount
			total_discount

9. Order Risks
    - score - this field has type error

10. Orders
	current_subtotal_price
	current_subtotal_price_set
		shop_money
			amount
		presentment_money
			amount
	current_total_discounts
	current_total_discounts_set
		shop_money
			amount
		presentment_money
			amount
	current_total_duties_set ????
	current_total_price
	current_total_price_set
		shop_money
			amount
		presentment_money
			amount
	current_total_tax
	current_total_tax_set
		shop_money
			amount
		presentment_money
			amount
	original_total_duties_set ????
	subtotal_price
	subtotal_price_set
		shop_money
			amount
		presentment_money
			amount
	tax_lines
		price
		price_set
			shop_money
				amount
			presentment_money
				amount
	total_discounts
	total_discounts_set
		shop_money
			amount
		presentment_money
			amount
	total_line_items_price
	total_line_items_price_set
		shop_money
			amount
		presentment_money
			amount
	total_outstanding
	total_price
	total_price_set
		shop_money
			amount
		presentment_money
			amount
	total_price_usd
	total_shipping_price_set
		shop_money
			amount
		presentment_money
			amount
	total_tax
	total_tax_set
		shop_money
			amount
		presentment_money
			amount
	total_tip_received
	customer
		total_spent
	fulfillments
		line_items
			price
			price_set
				shop_money
					amount
				presentment_money
					amount
			total_discount
			total_discount_set
				shop_money
					amount
				presentment_money
					amount
			tax_lines
				price
				price_set
					shop_money
						amount
					presentment_money
	line_items
		price
		price_set
			shop_money
				amount
			presentment_money
				amount
		total_discount
		total_discount_set
			shop_money
				amount
			presentment_money
				amount
		tax_lines
			price
			price_set
				shop_money
					amount
				presentment_money
					amount
	shipping_lines
		discounted_price
		discounted_price_set
			shop_money
				amount
			presentment_money
				amount
		price
		price_set
			shop_money
				amount
			presentment_money
				amount

11. Pages

12. Price Rules

13. Products
      - variants
        - price
        - compare_at_price
        - presentment_prices
          - price
            - amount
          - compare_at_price

14. Transactions
      - amount
