### ISSUE TITLE
Sendgrid connector should take a human-readable date rather than an integer timestamp

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4842]
## Tell us about the problem you're trying to solve
the sendgrid source connector takes as input for replication start date an integer timestamp. 

## Describe the solution you’d like
a more usable date string e.g: full or partial ISO formatted string. This must also be backwards compatible with the integer timestamp to avoid breaking any existing users of sendgrid.

**Comment by davydov-d** [comment]
https://github.com/airbytehq/airbyte/pull/16400
could not link the PR in a proper input field
