### ISSUE TITLE
Google Analytics source: support oauth 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4850]
## Tell us about the problem you're trying to solve
As a user trying to sync data from GA using the GCP/svc account/key JSON auth method currently available is not very user friendly ( i may not always have access to a cloud account). I would rather use the standard oauth mechanism to obtain a refresh token. 

## Additional context

**Comment by hbd** [comment]
Is this complete? Looks like these related issues were completed:
* https://github.com/airbytehq/airbyte/issues/4850

**Comment by sherifnada** [comment]
yup it is complete, thanks @hbd
