### ISSUE TITLE
Figure out an init script to set up the database.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4858]
## Tell us about the problem you're trying to solve
Today, this is part of the init db script on the db pod. We need a way to do this using CloudSQL that accommodates Cloud, Docker deploy and normal Kube deploy.

See: https://airbytehq.slack.com/archives/C026HMBDWFJ/p1626596462084000

**Comment by cgardens** [comment]
This seems like it overlaps with what @tuliren is working on? Is this something in scope for how you're thinking about it? If it is not, can it be?

**Comment by tuliren** [comment]
I did created an issue for it: #4872. I did not plan to work on it soon previously. But since it looks more important than I think, I can work on it this sprint. This is not a difficult task.
