### ISSUE TITLE
In Onboarding, add a link to the video tutorial

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#486]
Here is the link to the video: https://www.youtube.com/watch?v=Rcpt5SVsMpk&feature=emb_logo

Here is a suggestion of design:
https://www.figma.com/file/pO3Ob5W0yKUFOQzvg8TR3z/Airbyte?node-id=1%3A4958

Note: this is a low priority and a non-blocker to release 0.2.0

@cgardens

**Comment by cgardens** [comment]
This is my bad. I didn't move it into the todo queue in v0.2.0 so artem didn't see it. have done so and adding it to v0.3.0 release.
