### ISSUE TITLE
Export configs in plain text from production with ease

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#4867]
## Tell us about the problem you're trying to solve
- This is an idea from @ChristopheDuong.
- Users should be able to export configs in plain text from the production deployment with ease.
- They can check in the configs for version control.
- The export process can be done programmatically (e.g. in CI).

## Describe the solution you’d like
- Implement a `ProductionConfigPersistence` that can read configs from and write they to a production deployment.
- Put the implementation in a docker container that people can use independently from the Airbyte server.
- The docker container can then be used in any process for configs import and export.

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

**Comment by sbakiu** [comment]
It would be very helpful to have all the Airbyte connector configurations tracked on VCS for multiple reasons:
- Changes are tracked and can be reverted after faulty deployments
- The whole infrastructure can be replicated in another environment
- Recover fast from disasters

**Comment by evantahler** [comment]
I think the Octavia CLI solves this! Closing.
