### ISSUE TITLE
🐛 [Helm] MinIO logging is broken

### ISSUE THREAD

**Issue by kev-datams** [airbytehq/airbyte#48746]
### Helm Chart Version

1.2.0

### What step the error happened?

Upgrading the Platform or Helm Chart

### Relevant information

hello,

it looks like Airbyte helm chart version `1.2.0` is bugged regarding logs with default `MinIO` storage, as nothing is displayed in the UI:

![Image](https://github.com/user-attachments/assets/e3cd6e59-d750-4d9c-8832-79dae8eef0c2)

if I switch to Airbyte helm chart version `1.1.1`, I now have logs as usual:

![Image](https://github.com/user-attachments/assets/993722e3-6615-4601-ab5d-6c15e9afb61c)

any idea on how to identify the root cause ? 🙏 

thanks ! 👍

**Comment by kev-datams** [comment]
hello @marcosmarxm, do you know if someone is working on it for fixing ? 🙏

**Comment by marcosmarxm** [comment]
@airbytehq/platform-deployments can someone take a look into this issue?

**Comment by abuchanan-airbyte** [comment]
I'm not able to reproduce this. On a fresh 1.2.0 install using the default minio config, logs work fine for me, even with a small number of records

<img width="1156" alt="Image" src="https://github.com/user-attachments/assets/8c08c6c0-7a04-4ea4-b2bc-690682f470f7" />

**Comment by abuchanan-airbyte** [comment]
I tried with 1.2.0

**Comment by kev-datams** [comment]
I switched to using GCS, we can consider it closed if not reproducible.
Thanks for investigation 🙏
