### ISSUE TITLE
allow workspace-specific connector definitions

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4877]
This is a prerequisite to allowing custom connector definitions in the cloud version of Airbyte. 

There are a few interesting problems here:
- How does this impact seeding?
- Should we have both a fixed set of deployment-level connector versions and also connectors per workspace?
- How do we do updates across cloud if there's a connector incompatible change?
- Permissions around these operations.

**Comment by girarda** [comment]
done. thanks @xiaohansong !
