### ISSUE TITLE
Refactor ConfigSchema enum for flexibility

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#4880]
## Tell us about the problem you're trying to solve
We need to refactor the `ConfigPersistence` to make it more flexible and reduce code duplication on config persistence.

## Describe the solution you’d like
`ConfigPersistence` interface & class hierarchy should handle `string` config types instead of enum so that if some enum value is removed from the enum in the future, the code is better able to manage it.

It is also more easily to add new config types.

**Comment by cgardens** [comment]
so is the idea that anywhere we do `ConfigSchema` we would take string instead? Is the enum providing any value? Would it be worthwhile to have the implementation of `ConfigPersistence` use String but to layer on top if the enum versions or is that just noise?

**Comment by ChristopheDuong** [comment]
While Implementing the refactoring, it seems we need a few methods/fields from `ConfigSchema` so it is not just replacing the enum value with a simple string but an object (interface) instead

I'm not sure if we need some kind of versions in there...
