### ISSUE TITLE
Standup Cloud API in K8s

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#4888]
## Tell us about the problem you're trying to solve
@ChristopheDuong finished up the implementation of the cloud API https://github.com/airbytehq/airbyte/issues/4446. We want to be able to stand up that API in K8s and in our cloud infra structure.

## Describe the solution you’d like
* [ ] - it runs in our cloud infra
* [ ] - helm charts

**Comment by davinchia** [comment]
this is linked to https://github.com/airbytehq/airbyte-cloud/issues/81
