### ISSUE TITLE
Follow up on S3 Logging Fix.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#4915]
## Tell us about the problem you're trying to solve
* Merge https://github.com/bluedenim/log4j-s3-search/pull/101 into OSS upstream.
* Update our dependency version.
* Decide what to do with CloudRepo.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
@davinchia can we close this?

**Comment by davinchia** [comment]
Yes
