### ISSUE TITLE
use clusterip instead of nodeport

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#4916]
@davinchia pointed out that this would make more sense for internally-facing kubernetes services.

**Comment by michel-tricot** [comment]
can't you keep the nodeport and put an `Ingress` or `LoadBalancer` on top?

**Comment by jrhizor** [comment]
It's more the opposite direction.

The db/temporal have `NodePort` when they actually don't need it; clusterIP is sufficient. https://github.com/airbytehq/airbyte/blob/master/kube/resources/db.yaml#L6

For the webapp/api we'll want `NodePort` and then a layer on top.
