### ISSUE TITLE
Shopify source incremental | append not working

### ISSUE THREAD

**Issue by jacqueskpoty** [airbytehq/airbyte#4923]
I set up a connection with a Shopify source and json destination. I selected INCREMENTAL | APPEND  as the destination sync mode. It pulls all the data at the first job and attempt which is normal. However for the subsequent jobs, it's syncing part of the data that has already been synced. I added screenshot of the connection settings, the log of the first job and the second job.
<img width="1418" alt="Screen Shot 2021-07-22 at 2 53 44 PM" src="https://user-images.githubusercontent.com/11681938/126695841-cbab55d9-4e2e-4f44-88c5-90b6dc9ca494.png">
<img width="1420" alt="Screen Shot 2021-07-22 at 2 54 32 PM" src="https://user-images.githubusercontent.com/11681938/126695915-4b2f6062-a0ea-48a2-9ec7-c0b88b4ed2ac.png">
[logs-210-0.txt](https://github.com/airbytehq/airbyte/files/6864698/logs-210-0.txt)
[logs-209-0.txt](https://github.com/airbytehq/airbyte/files/6864700/logs-209-0.txt)

**Comment by sherifnada** [comment]
@jacqueskpoty could the issue be explained by https://docs.airbyte.io/understanding-airbyte/connections/incremental-append#inclusive-cursors?

**Comment by jacqueskpoty** [comment]
@sherifnada Im not sure. The link you sent explains that the source can still fetch some data in case the cursor field is not granular enough. In this case, "created_at" is used as the cursor field. It's a datetime(date+time+seconds) which is a granular field.
I made a test by downgrading the shopify source to the version 0.1.7 and i did not have that problem. The 0.1.7 used the "updated_at" as cursor field.
As conclusion we should rather use "updated_at" as cursor field or allow to select a cursor field on the UI or API.

**Comment by bazarnov** [comment]
@jacqueskpoty according to the build recomendation and the general policy described by @sherifnada in the comment above, this is not a bug, but rather feature, as far as we should be 'at least 1 record delivery guarantee' that everything is working and connector access the data properly. In this frustrating situation we can recommend the following:

- use other destination than JSON LOCAL FILE, that supports normalization and deduplication (or add support of normalization to JSON LOCAL, CSV LOCAL destinations)
- try to update anything in your account (any stream that could be updated using UI, a.k.a = products, orders, etc) and run the sync again, the result should be expected last 11 records you've synced before + the records you changed
- after that if you run sync again, there should be less than 11 records in output, indicating that the connector catch the changes using `updated_at` as expected.

Feel free to provide your feedback on those steps.
