### ISSUE TITLE
Shopify integration schema discrepancy (products.json)

### ISSUE THREAD

**Issue by JianhaoZhang** [airbytehq/airbyte#4927]
## Enviroment
- **Airbyte version**:  0.27.3-alpha
- **OS Version / Instance**: irrelevant
- **Deployment**: Docker
- **Source Connector and version**: 0.1.10
- **Destination Connector and version**: Irrelevant
- **Severity**: Medium / High
- **Step where error happened**: Create source

## Current Behavior
Currently, the schema/products.json file in the Shopify integration describes the response schema of REST API [https://shopify.dev/api/admin/rest/reference/shipping-and-fulfillment/fulfillment](url)

## Expected Behavior
It should instead describe the response schema of REST API [https://shopify.dev/api/admin/rest/reference/products/product#index-2021-07](url) according to the documentation

## Logs
N/A

## Steps to Reproduce
1. Retrieve the schema from a shopify source
2. Expecting schema of products
3. Instead getting schema of fulfillments

## Are you willing to submit a PR?
Not at the moment.

**Comment by sherifnada** [comment]
@JianhaoZhang thanks for the report! will take a look
