### ISSUE TITLE
Obtain and use BambooHR sandbox

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4931]
## Tell us about the new connector you’d like to have
https://documentation.bamboohr.com/docs

**Comment by igrankova** [comment]
Contacted to BambooHR: Ethan Clark | Account Expansion Executive, 385-332-8367, eclark@bamboohr.com
Test accounts are $99 per month.
Decided to reach out later, right before the implementation.

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
partially:
https://documentation.bamboohr.com/docs/webhooks

**Available authentication modes (API key/Oauth/other)** 
OpenID Connect to Authenticate and Retrieve an API Key:
https://documentation.bamboohr.com/page/authenticate-integration

**Has Sandbox environment?** 
Yes:
https://partners.bamboohr.com/test-account/

**How to populate the account with data** 
UI,
API:
https://documentation.bamboohr.com/reference

**Available streams for sync** 
Employees
Employee Files
Company Files
Reports
Tabular Data
Account Information
Time Off
Photos
Last Change Information
Login
Benefits
Time Tracking
Goals
Training

**Integration supports incremental sync?** 
No

**Other information/blockers** 
-

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation

**Comment by igrankova** [comment]
@misteryeo Hi, Andy
I've requested the sandbox and received the response. BambooHR want 99$/month for it.
![image](https://user-images.githubusercontent.com/87977540/161918050-a57a80f7-c60d-4761-92ee-8c08365bf589.png)
**Here is the payment link:** https://sl.bamboohr.com/t/10754/c/088175d8-2f17-44c8-8f8b-b30023258daa/NB2HI4DTHIXS6YTBNVRG633IOIXHGZLDOVZGKLTGN5ZGGZJOMNXW2L3QMF4W2ZLOORZT643VMJWWS5CFNZQWE3DFMQ6WMYLMONSSM43UPFWGKPLJNZWGS3TFEZTGSZLMMRPWCY3DN52W45CJMQ6TQYJRGI4TAM3GG5TGINDGGQYWKMBRG5TGMNLFGMYWMMZRGJRTOZJGNFZWI5DQHVYDC===/bamboohr-secure-force-com-payments

**Comment by misteryeo** [comment]
@igrankova Thanks for this! We don't have BambooHR as an urgent connector so let's mark this as blocked and we can revisit later.

**Comment by igrankova** [comment]
The sandbox is available:
URL: https://airbytetest.bamboohr.com/
Username: sherif@airbyte.io
LastPass: BambooHR sandbox
