### ISSUE TITLE
New Source: Braze

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4932]
## Tell us about the new connector you’d like to have
https://www.braze.com/docs/developer_guide/home

**Comment by karinakuz** [comment]
**Integration Vetting**

**Webhook-based? (no/partially/yes)**
if partially, mention which endpoints are webhook-based
**_no_**

**Available authentication modes (API key/Oauth/other)**
_**authentication key https://www.braze.com/docs/api/api_key/**_

**Connecting to the data source**
what kind of API is it? (SOAP/GraphQL/REST/other)
**_Rest API_**

is there an SDK available? Can we connect with HTTP requests directly?
**_Customers using Braze’s EU database should use the https://rest.fra-01.braze.eu/ endpoint. This endpoint will be used when configuring the Braze iOS, Android, and Web SDKs._**
https://www.braze.com/docs/developer_guide/platform_integration_guides/web/initial_sdk_setup/
**_SDK Endpoints_** https://www.braze.com/docs/user_guide/administrative/access_braze/sdk_endpoints/

If this is a database/datalake/pubsub source, does it have a JDBC driver or Java SDK?
_**Java SDK**_
https://js.appboycdn.com/web-sdk/latest/doc/modules/appboy.html

**Creating an account**
Select one of the below options
self-service free account available?_ If yes then create it using integration-test@airbyte.io (you should be getting emails sent to this email address)
**_no, sent letter to the Sales_**
_Braze's pricing model isn't public, but typically ranges from $50K - $220K depending on service entitlements and product inclusions. This means that Braze charges for individual features such as API calls, updating tags, and exporting data from their system._

**Comment by sherifnada** [comment]
I applied for the Braze partnership program

**Comment by sivankumar86** [comment]
Any update on this feature

**Comment by igrankova** [comment]
hi, @sivankumar86, we are working on the sandbox request to implement this connector and Braze team asks us about our mutual customers. Do you have a Braze account? Can you help us and share your contacts as a Braze customer?

**Comment by sivankumar86** [comment]
Hi @igrankova ,
     We are using braze however, I cannot share any details due to security and privacy reason.

**Comment by igrankova** [comment]
Hi, @sivankumar86, thank you for your reply. Is it possible for you to contact alex.wiseman@braze.com directly and confirm that you are our mutual customer? Or maybe someone from your company could contact Braze?

**Comment by koconder** [comment]
@igrankova I’m an enterprise Braze customer, do you want me to reach out to them?

**Comment by sivankumar86** [comment]
> [alex.wiseman@braze.com](mailto:alex.wiseman@braze.com)

 I have reached out to provided contact and also, included braze point of contact from my company.

**Comment by igrankova** [comment]
Hi!
So much appreciate! We are working on the partner program and soon expecting to receive a sandbox. The recommendation from the mutual customers is a very important part of this work.

**Comment by igrankova** [comment]
Unblocked:
Received a sandbox account, LastPass name: Braze Sandbox Account
Created an App: Airbyte, the API Key generated

**Comment by koconder** [comment]
@igrankova im happy to help with any connector build as an airbyte maintainer and an enterprise Braze customer. Just reach out 👍

**Comment by lazebnyi** [comment]
duplicate - https://app.zenhub.com/workspaces/python-connectors-6262f8b593bb82001df56c65/issues/gh/airbytehq/airbyte/19129
