### ISSUE TITLE
New Source: Zoho CRM

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4934]
## Tell us about the new connector you’d like to have
https://www.zoho.com/crm/developer/docs/api/v2/

**Comment by igrankova** [comment]
@sherifnada 
**Webhook-based? (no/partially/yes)** 
partially:
https://www.zoho.com/blog/crm/trigger-sms-alerts-using-zoho-crm-webhooks.html

**Available authentication modes (API key/Oauth/other)** 
There're two ways of authorization: OAuth and API key:
https://www.zoho.com/crm/developer/docs/functions/auth-method.html

**Has Sandbox environment?** 
Yes:
https://www.zoho.com/crm/developer/sandbox.html?src=dd
Dev environment:
https://developers.zoho.com/crm/tab/Home/begin

**How to populate the account with data** 
UI,
Bulk write API:
https://www.zoho.com/crm/developer/docs/api/v2/bulk-write/overview.html

**Available streams for sync** 
Organization
Users
Profiles
Territories
Photo and Attachments
Currencies
Files
Notes
Tags: Leads, Accounts, Contacts, Deals, Campaigns, Tasks, Cases, Events, Calls, Solutions, Products, Vendors, Price Books, Quotes, Sales Orders, Purchase Orders, Invoices, Custom, Notes, Activities

**Integration supports incremental sync?** 
No

**Other information/blockers** 
API Limits:
https://www.zoho.com/developer/help/api/api-limits.html

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation

**Comment by chris-cressman-immo** [comment]
Hello, is there any planned date of release for this connector yet?

Thanks

**Comment by davydov-d** [comment]
#11589
