### ISSUE TITLE
Amazon SP: Support (even) more API endpoints

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4936]
## Tell us about the problem you're trying to solve

Inventory
Shipments
Vendor Inventory
Vendor Shipments
FBA Inventory
FBA Orders
FBA Shipments

**Comment by htrueman** [comment]
**Product Requirements & features**

1. What is the “ideal end state” for the features offered by this connector? At a minimum mention:
a. Output schema
_All schemas are [documented](https://github.com/amzn/selling-partner-api-models/tree/main/models) with swagger._
b. Authentication
_AWS users complicated auth system, which is documented [here](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html). Already implemented in #4863._
c. Include more topics as you see fit depending on the connector (etc…)
_We may use https://github.com/saleweaver/python-amazon-sp-api lib for some code samples and inspiration.
It is also not clear for now on how to get list `Shipments` records, going to research later._
2. What is the release roadmap for this connector?
a. Which features are absolutely necessary for the MVP release?
_First we are going to implement `FBA Inventory` (seems to be already implemented), `FBA Orders`, `FBA Shipments` streams. As they are records streams and easy to implement. Then `Vendor Inventory`, `Vendor Shipments` streams. `Inventory` and `Shipments` need to be researched more before implementation._
3. Check if and how [Fivetran](http://fivetran.com) or [Stitch Data](http://stitchdata.com) support this connector 
_Fivetran [does not support](https://support.fivetran.com/hc/en-us/community/posts/1500000077062-New-Connector-Amazon-Selling-Partner-API-SP-API-) Amazon SP connector.
Same for [Stitchdata](https://www.stitchdata.com/integrations/sources/)._

**Implementation Scoping**

- Describe the pagination strategy used by the API
_It's `NextToken` query param in all the streams. If we add this token, then no other params are supported._
- Describe the authentication strategy used by the API. If Oauth, go into detail about how the token can be obtained and if there are any special gotchas.
_Oauth. Auth strategy is really complex. But shortly: we need to transform, encode and subscribe initial credentials, then get access/refresh token from Amazon, then use it to auth requests. More details in [docs](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html)_ 
- Describe how we will populate the sandbox account with data 
_Now we are using our test account, but there are no actual data in most streams. Thus we need to either user some prod account (I can't use `Amazon SP API (owned by cart.com)` creds from LastPass, as there are no enough permissions) or fill test account with some real data._
- How will rate limiting be handled?
 _Rate limits are specified in the docs for each API type https://github.com/amzn/selling-partner-api-docs/tree/main/references These may be configured and for now our default backoff approach should be enough handle it._
- Type of the API? (REST/SOAP/GraphQL/other)
_REST_

**Integration details**
_link_
