### ISSUE TITLE
Feature Request: Make Airbyte Self Updatable

### ISSUE THREAD

**Issue by jgtvares** [airbytehq/airbyte#4951]
## Tell us about the problem you're trying to solve
Today, Airbyte is not self updatable, like we update connectors for example.
So, in order to update we need to download the more recent Docker setup files from Airbyte's repo.

## Describe the solution you’d like
In Airbyte settings we should be able to see if there is a new version of the core app (similar to what we have for connectors today). And, if there is, we should be able to update it right away.

## Describe the alternative you’ve considered or used
I have considered:
- A cron job to check if the main Airbyte Docker image was updated. And, if so, download the image and restart the container.
- Another alternative would be to download the files from Airbyte's repo again if the image changes.

## Are you willing to submit a PR?

No.

**Comment by cgardens** [comment]
@jgtvares we aren't planning to pursue this in the short term. the complexity / error-proneness of trying to do this outweighs the benefit in our opinion. We have made the migration process significantly easier. We also plan to expose in the airbyte UI a notification to let users know there is a newer version of Airbyte available.
