### ISSUE TITLE
Handle APIs which emit numbers as strings 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4984]
## Tell us about the problem you're trying to solve
Some APIs like Facebook or Shopify output numbers as strings e.g: #4827 and #4841 This probably happens in more APIs as well. 

Given that this is probably a ubiquitous issue we should have a simple and easy way to handle it. 

There are some options here: 
1. In the catalog type definition for such fields, add an annotation e.g: `airbyte_type_hint: number` indicating that a particular string is actually a number and then have Airbyte or the destination worker. This is nice because the source doesn't have to worry about transformation. On the other hand it is not ideal because we'd be relying on each destination to support this custom type hint. 
2. Do the transformation in the source directly (e.g: hardcode which fields have this issue and transform in the code), making sure the JSON Schema type is output as `number` in the catalog. if we go this route we might want to add this capability into the CDK. 
3. Something else I'm not thinking of

## Describe the solution you’d like
1. Research and decide on which option to use
2. create follow up tickets for implementation

**Comment by keu** [comment]
1. we can just use existing json_schema field `airbyte_type_hint` -> `format`

**Comment by sherifnada** [comment]
redundant now that we have type transformer
