### ISSUE TITLE
allow listing connections for workspace without iterating through all connections

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5002]
Right now `ConnectionsHandler.listConnectionsForWorkspace` computes the connections for a workspace by reading all connections and then filtering to find ones that match the specified workspace.

This is obviously inefficient and will likely cause performance problems in the future.

The main issue behind this is that we need the ability to store or index the connections by workspace, which is non-trivial.

**Comment by malikdiarra** [comment]
This has been fixed.
