### ISSUE TITLE
CDK: Support GraphQL streams more seamlessly

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5032]
## Tell us about the problem you're trying to solve
The Python CDK's HttpStream abstraction is geared heavily towards REST, RPC, and SOAP APIs. While it's possible to hit a GraphQL API using the HttpStream abstraction, the experience can be made even more seamless. As a connector developer pulling data from a graphQL API, I would love to have a framework/helper similar to HttpStream (maybe `GraphQLStream`, a subclass) which can be used to pull data from a GQL API. 

## Describe the solution you’d like
A set of classes similar to `HttpStream` which facilitate pulling data from GraphQL APIs.

## Additional context

**Comment by keu** [comment]
@sherifnada an example would be a nice addition
