### ISSUE TITLE
Source Github: implement client-side throttling of requests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5036]
## Tell us about the problem you're trying to solve
related to #2742 

Sometimes a user wants to use up only N% of their API quota. For example, GH allows only 5000 requests per hour, and the token may be shared between Jenkins and Airbyte. in that case the user doesn't want Airbyte to use up more than say 30% of the quota so it doesn't block jenkins. 

## Describe the solution you’d like
A parameter in the connector configuration which controls how much of the API quota it uses. 

**Urgency:** Nice-to-have

**Comment by grubberr** [comment]
@sherifnada

What do you think how it's better to add the new config parameter for customers for this feature:

1. Requests per hour: [5000] # please enter a value between 1 .. 5000 , for example 3600

2. Throttling in %: [100] # please enter some value between 0 .. 100, for example 80

Your option?
