### ISSUE TITLE
Use SUPER data type on Redshift destination for raw JSON data

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#5050]
## Tell us about the problem you're trying to solve
I'd like the option utilize the SUPER column type when loading data to a Redshift destination. https://docs.aws.amazon.com/redshift/latest/dg/r_SUPER_type.html  

## Describe the solution you’d like
Allow for checkbox selection on either the destination or connection to utilize SUPER data type as the target for the column _airbyte_data. Experimenting with this data type I've found performance to be increased during normalization, as well for allowing greater flexibility when creating source queries/views without normalization

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

## Are you willing to submit a PR?
Just recently got a local build setup, will explroe

**Comment by aforlorncat1** [comment]
Throwing some support for SUPER. We currently leverage this data type for large JSON fields that exceed the max VARCHAR length in Redshift.
