### ISSUE TITLE
ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: YEAR

### ISSUE THREAD

**Issue by ayyoubmaulana** [airbytehq/airbyte#5070]
Hi, i try to replicate data using incremental deduped for the first time in table client_order from Mysql to BigQuery but i got this error, can someone explain whats going on ?

![Screenshot (30)](https://user-images.githubusercontent.com/53739205/127465642-d13e9dfd-ad42-4a8f-bfef-a13df39cb943.png)

i found this in source MySQL

![Screenshot (31)](https://user-images.githubusercontent.com/53739205/127465742-7841a63e-7bb8-403e-ad29-d9993bd452b5.png)

does that is the problem ?

**Comment by sherifnada** [comment]
@ayyoubmaulana can you share the full log?

**Comment by marcosmarxm** [comment]
This should be added to the comprehensive data tests in mysql

**Comment by ayyoubmaulana** [comment]
[logs-2974-0.txt](https://github.com/airbytehq/airbyte/files/6904669/logs-2974-0.txt)

this my full log @sherifnada

**Comment by etsybaev** [comment]
Might be related to https://github.com/airbytehq/airbyte/issues/3931

**Comment by ayyoubmaulana** [comment]
but it still error for me @etsybaev

**Comment by roychri** [comment]
I am having a similar problem, even when using `zerodatetimebehavior=Converttonull` on the source jdbc options.
This is using MySQL -> PostgreSQL.

See my troubleshooting report: https://airbytehq.slack.com/archives/C01MFR03D5W/p1636037752111300

Here are my logs:
[logs-65-0.txt](https://github.com/airbytehq/airbyte/files/7479522/logs-65-0.txt)

**Comment by sherifnada** [comment]
cc @tuliren for database reliability issues

**Comment by tuliren** [comment]
MySQL year is now parsed as a string, instead of a date.

In the future, we may consider changing a year value to an integer. But currently our internal Json representation only supports `number`, but not `integer`. So we cannot store them as integers yet. Follow up issue here: https://github.com/airbytehq/airbyte/issues/8722
