### ISSUE TITLE
MSSQL Server invalid character sync on THAI_CI_AS collation (varchar)

### ISSUE THREAD

**Issue by apiasak** [airbytehq/airbyte#5077]
## Enviroment
- **Airbyte version**:  0.28.1-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker Desktop
- **Source Connector and version**:  Microsoft SQL Server (MSSQL)
- **Destination Connector and version**: LOCAL CSV
- **Severity**:  Medium
- **Step where error happened**: Sync Job

## Current Behavior
We store Thai character in varchar field on MSSQL. Our collation is THAI_CI_AS so the it works fine with sql editor, apps.
Although when we sync the data from this source to any destination the result is showing invalid Thai charactor.
I tried several destination CSV, JSON, GBQ  still not working. 

## Expected Behavior
The data should show Thai character properly. Please note when we use other ETL tool such as Pentaho it can configure the char

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```


```

</details>

## Steps to Reproduce
1. Create MSSQL Server database and change collation to THAI_CI_AS
2. Create table contains varchar 
3. Insert data with Thai char into the field.
PS. I think we can use any collation to test, it should have the same issue when the unicode string store in varchar and it is difficult to change the data type on the source.

**Comment by sherifnada** [comment]
thanks @apiasak, will take a look very soon!

**Comment by apiasak** [comment]
Hi guys,

I did re-import the data and seems it was an issue with the data itself not about the connection.

Thanks for the follow-up.
