### ISSUE TITLE
Define the v1 of our data protocol

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#509]
## Tell us about the problem you're trying to solve
I want to have a formal definition of how sources and destinations can exchange data

## Describe the solution you’d like
I would like a very simple protocol that allows me to build upon for the next versions.
I want to make it trivial to implement for a source contributor.
I want it to be easy to write a compatibility layer with singer

## Describe the alternative you’ve considered or used
Singer protocol. It has a lot of cruft and is too permissive in what it lets through,

**Comment by cgardens** [comment]
done. meet airbyte-protocol.
