### ISSUE TITLE
Get sandbox account for short.io and populate it with data

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5092]
## Tell us about the problem you're trying to solve
This will help us continuously test the contribution in #5073

**Comment by igrankova** [comment]
@sherifnada 
1. Sandbox: https://app.short.io/users/dashboard/235589/links
2. 2 test domains: 1hsf.short.gy, air.shortcm.li 
3. Populated with different links to shorten, made clicks for statistics.

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation

**Comment by sherifnada** [comment]
thanks @igrankova!
