### ISSUE TITLE
Annotate string date fields with the right `format` label

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5096]
## Tell us about the problem you're trying to solve
Today, we write date fields/columns as VARCHAR in database destinations. Very soon, however, we will start writing date fields with the correct types in the destination, once we complete #1006 . 

Since we didn't previously support first class date types, many connectors did not annotate date fields with the correct `format` e.g: instead of outputting: 

```
"created_at" {
  "type": "string", 
  "format": "datetime"
}
```

we just output: 

```
"created_at": {
  "type": "string"
}
```

In order for us to start writing date columns with the correct formats in the destination, we need to correctly annotate date columns with the right `format` field. 

As described by the [JsonSchema Spec](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times), there are three date types: 

1. date-time
2. date
3. time

We should go through all of our connectors and make sure that all of the schemas output by them correctly annotate any date fields with the correct `format` label. The most common date fields are going to be `created_at` and `updated_at` (though they may have some variation in their name like `created`, `creation_date`, `timestamp` etc...)

For each source, we should create a PR updating its schema, then publish a new version of that connector.

**Comment by cheyura** [comment]
@sherifnada done. Please see the link:
https://docs.google.com/spreadsheets/d/1-hmZ83PzW1iTy7RlHP4QX7dcMigEfdMm94Yohg5mlj8/edit#gid=2111357565

**Comment by sherifnada** [comment]
great! @cheyura could you consult with @antixar and @midavadim about the best way to roll this change out?

**Comment by midavadim** [comment]
PLAN TODO:
1. Find all 'date' related attrs (DONE)
2. Check actual format (example) for each 'date' related attribute (it is quite a big task)
3. Update related schemas

QUESTION - what should we do in edge cases:
1. What if there is a custom datetime format (not ISO)?
2. What if there is no real example?
3. What if connector's tests are not working (not possible to test updates)?

SOLUTION:
1. do not add 'format' field 
2. re-format value to ISO format (could impact cursors, slicing etc so it requires good tests)

**Comment by sherifnada** [comment]
We can support the `date-time` and `date` formats described [here](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times). 

solution 1 sounds good. 

solution 2: For re-formatting the value to ISO, it may be useful to have a helper in the CDK which is given the "paths" to date fields in the output JSON object, and it automatically converts it to the right format. We're working on something similar to this right now actually so for now, let's not do formatting in code since we will soon have a helper for it. For now if something will need special formatting let's keep track of it and come back to it once we have the helper. 

> What if connector's tests are not working (not possible to test updates)?
This is why fixing builds is useful :) Let's prioritize fixing builds based on this.
