### ISSUE TITLE
MySQL normalization generates null values for text columns with more than 512 characters

### ISSUE THREAD

**Issue by julianopiovezan** [airbytehq/airbyte#5099]
## Enviroment
- **Airbyte version**:  0.28.0-alpha
- **OS Version / Instance**: Debian bullseye/sid, AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.5
- **Destination Connector and version**: MySQL 0.1.9
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
MySQL normalization creates text columns as varchar(512). If the source column has more than 512 characters, the destiny column is getting null.

## Expected Behavior
Destiny column should be filled with the source content.

## Logs
<details>
<summary>LOG</summary> 

```

```

</details>

## Source table definition and test data

```

create table test
(
	id integer primary key,
	topic text
);

insert into public.test (id, topic) values (1, 'a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters a very long string with more than 512 characters');

```

## Steps to Reproduce
1. Create the test table in a postgres db with the above statement.
2. Setup a postgres source.
3. Setup a mysql destination.
4. Setup a connection.
5. Run sync.
6. Check final normalized table.

## Are you willing to submit a PR?
At the moment, no.

**Comment by ilizunov** [comment]
Hi everybody, any workaround found?

**Comment by julianopiovezan** [comment]
I had to disable the default normalization and implemented a custom transformation using dbt.

**Comment by cgardens** [comment]
Normalization is being re-vamped for MySQL as we speak. That will solve this issue.
