### ISSUE TITLE
Potential Bug in migration leads to missing 'basic normalisation' schema message.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5101]
## Current Behavior
See this slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1627641052018500

I haven't been able to reproduce this, so placeholder ticket for now.

**Comment by marcosmarxm** [comment]
Anyone having this problem a workaround solutions is update the destination name and save it. This process will remove the `basic_normalization` field and your connection should start working again.
