### ISSUE TITLE
full source support on integration interface v2

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#511]
For the new sources:
- [x] json schema generation from new protocol
- [x] use generated types in `base-python`
- [ ] support state handling
- [ ] combine discovery output with the "mask" schema provided to the source within `base-singer` (similar to `SingerCatalogConverters` functionality
- [x] send logs as messages
- [ ] improve error handling
- [ ] add tests
- [ ] add more comprehensive type hinting
- [ ] user consistent naming & directories (`destination-csv-singer` for singer-based, ` destination-csv` for internal)
- [ ] flatten integrations directory
- [ ] create an archetype for singer sources

**Comment by cgardens** [comment]
@jrhizor is this still relevant or should we close?
