### ISSUE TITLE
Make the abstract files source framework available in the cdk

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#5111]
## Tell us about the problem you're trying to solve
Currently the [abstract files source](https://github.com/airbytehq/airbyte/tree/master/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract) sits within the S3 source connector. This makes adding new source connectors like GCS, SFTP, Azure etc. using this abstraction awkward.

## Describe the solution you’d like
This will likely piggyback on the solution for https://github.com/airbytehq/airbyte/issues/12004

Refactor S3 source package structure, pulling out the abstract files source so that S3 source and other new sources can build off it independently.

TBD one of:
- We integrate abstract files source into the cdk
- We make abstract files source its own pypi library

notes on above decision:
- abstract-files-source currently depends on the cdk, would this make it fit better within or outside?

As part of this issue, improve the clarity of the spec across abstract files and any child connectors. If possible go to modularised yaml specs but if keeping pydantic have it more obvious where spec modules are and why. ([slack thread for reference](https://airbytehq-team.slack.com/archives/C02TL38U5L7/p1650470892277149)).

Would also be nice to have a generator for file source connectors to minimise developer effort.

## Describe the alternative you’ve considered or used
An alternative without requiring refactor would be to simply copy the abstract files source code into each new connector, not ideal.
Another alternative is to use the more simple method of basing the child docker image off the files-abstract-source image, however as discussed [in this issue](https://github.com/airbytehq/airbyte/issues/12004) we want to go for pythonic pypi libs.

**Comment by alexandrethm** [comment]
Hi! Are they any plans on when to do this? I will need the [File source](https://docs.airbyte.com/integrations/sources/file) for multiple sources, and it would be really helpful to have pattern matching and incremental sync. Happy to contribute if you'd like

**Comment by sherifnada** [comment]
Moving this out of the current sprint , deprioritized in favor of other Q2 projects at the moment, will revisit oson

**Comment by sherifnada** [comment]
https://github.com/airbytehq/airbyte/pull/14410 has a WIP version of this that is paused.
