### ISSUE TITLE
SAP ERP System/SAP S/4 Hana Connector

### ISSUE THREAD

**Issue by pavanreddyCS** [airbytehq/airbyte#5112]
Hi Team,

Are we having any connector to connect the SAP system and read data from SAP application tables?

Please Advise.

Thanks
Pavan

**Comment by sherifnada** [comment]
We have #3413 to track this issue -- would that cover your scneario?

**Comment by pavanreddyCS** [comment]
yes, this covers my scneario.

**Comment by sherifnada** [comment]
@pavanreddyCS closing this one as a duplicate then -- please leave any comments in #3413 
In terms of timeline this is not immediately prioritized. Please leave a 👍🏼 reaction on the linked issue to help us prioritize.

**Comment by jrosskopf** [comment]
For everybody stumbling on this issue, you may find our experiments interesting: https://github.com/DataZooDE/erpl-airbyte-connectors
