### ISSUE TITLE
Scope import / export by workspace id

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5124]
## Tell us about the problem you're trying to solve
For the cloud version of the product we want to allow a user to import and export their configurations, just like they would in the OSS version. That being said, we need to scope those import / exports by workspace (or org level when we get to it). Obviously a user should only be able to export their own configurations and import configurations into their own workspace.

### Thinking about what needs to be scoped by workspace
This will require some thought because basically have 4 cases for import / export:
1. **auto migration OSS** - does not need to be scoped by workspace id.
2. **auto migration cloud** - does not need to be scoped by workspace id, we want to migrate everything
3. **manual import / export OSS** - not super clear if it should be scoped by workspace id or not. in most cases it won't matter since OSS generally only has one workspace. that being said, in the cases where that is not true, it will be annoying / confusing to have to import / export one workspace at a time
4. **manual import / export cloud** - must be scoped by workspace id

### Inserting By Workspace
The other trick here is that all of our import / export functionality does a full replace of the data. All existing records are wiped out and replaced by new ones. This is easy and keeps things simple, but will not longer be a viable model in cases where we are scoping by workspace. So the replace functionality needs to surgically delete all records (in jobs and configs) related to a specific workspace before importing the new ones.

## Priority
I think we will need this almost immediately after the private beta launch but I think we can eek by without it before then. Trying to be pretty draconian with what the critical path is.

**Comment by ChristopheDuong** [comment]
it sounds like we would need a new export/import endpoint pair such as:

## Export/Import not scoped by workspace id:
- auto migration OSS: we want to migrate everything
- auto migration cloud: we want to migrate everything

## Export/Import scoped by workspace id:
- manual import / export OSS - scoped by workspace id. In most cases it won't matter since OSS generally only has one workspace. that being said, in the cases where that is not true, the API could still be used for export/import without workspace id scopes (used by migrations)
- manual import / export cloud - must be scoped by workspace id

**Comment by ChristopheDuong** [comment]
> Obviously a user should only be able to export their own configurations and import configurations into their own workspace.

@cgardens, however, they shouldn't be able to export/import standard definitions (source/destinations), right?
For instance, changing the docker image URL (dangerous) or even the version tag of a connector could affect all other workspaces too...

**Comment by jrhizor** [comment]
When we allow custom images we will likely want to allow importing and exporting definitions. 

We should still allow exporting it (in case they're going from SaaS to non-SaaS) but ignore it on importing?
