### ISSUE TITLE
S3 Destination hangs on overwrite

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5128]
## Environment
- **Airbyte version**:  0.29.2
- **OS Version / Instance**: AWS EC2
- **Deployment**: docker
- **Source Connector and version**: Google Sheets
- **Destination Connector and version**: S3 Destination 0.1.9
- **Step where error happened**: Sync job

## Current Behavior
S3 Destination with full refresh hangs.

> When syncing from GSheets to S3 I find I need to use “Full Refresh | Append” as the sync mode as opposed to overwrite. The reason for this is that when I run the synchronization in Overwrite mode it gets stuck on “Waiting for destination thread to join”

Originally thought this was a permissions issue where the user had only append permissions as opposed to create / replace. But that has been update (see permission below) and the problem persists:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": "arn:aws:s3:::my-bucket-name/*"
        }
    ]
}
```

If it is a permissions issue of some sort we should make it very clear to the user where the inadequate permission is. If it is not, then we got to figure it out. 😅 

[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1627588078101000) where we discuss this problem (you need to scroll to the bottom). 

Possibly related to an earlier problem that this user ran into. [slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1625696285118900)

## Expected Behavior
Full refresh should work for the S3 destination (regardless of source)

FYI @sherifnada && @tuliren

**Comment by andriikorotkov** [comment]
@cgardens, In order for everything to work correctly, it is also necessary that the user whose "S3 Key Id" and "S3 Access Key" are used have access to both the bucket and its contents. Policies to use:
