### ISSUE TITLE
Support for more Granular Data Types

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5129]
## Tell us about the problem you're trying to solve
Airbyte supports a few very broad data types: `STRING`, `NUMBER`, `OBJECT`, `ARRAY`, `BOOLEAN`, `NULL`. While this has allowed us to iterate quickly, we recognize that having such broad data types can make the output data very difficult to work with. 

The easiest example is that `DATETIME` gets converted to a string, which means a user has to parse that string into a `DATETIME` if they want to query on it. The other place where this often feels inadequate is in the case of numbers. Treating longs, ints, shorts, floats, doubles, etc as discrete data types will be more efficient in many cases and make the output data easier to work with.

Related issues: 
https://github.com/airbytehq/airbyte/issues/2390
https://github.com/airbytehq/airbyte/issues/1864
https://github.com/airbytehq/airbyte/issues/1006
https://github.com/airbytehq/airbyte/issues/4071
https://github.com/airbytehq/airbyte/issues/3932
https://github.com/airbytehq/airbyte/issues/3931
https://github.com/airbytehq/airbyte/issues/4515

## Describe the solution you’d like
Our goal is to add support for a richer set of data types so that the data that we output is as close as possible to the data that is input (in terms of type). This will make that data more familiar to the user and easier to query.

Depending on where we take this, it will open up other spaces to us, e.g. geospatial data, etc.

This project requires a lot of area:
* Mapping out how to handle these types in the core platform. 
* Figuring out what to do in cases where destinations do not support all of the types that we support. This includes figuring out what conversion we need to do _and_ how to track it in our configuration. 
* Planning how migrate existing connectors incrementally to use the richer set of data types.

**Comment by tuanchris** [comment]
Hi @cgardens, do you have any updates on this? Right now integration from relational databases like Postgres has very generic data types and it's a lot of work to convert all of them to the correct ones. For e.g. int columns are all float, date & timestamp columns are all string.

**Comment by cgardens** [comment]
@tuanchris hiya, i don't have a clear idea of when this will happen yet. it is definitely something we will do but no timeline yet. if you can get some more :+1: on this issue that would help us understand how valuable it is to the community versus other priorities.

**Comment by tuanchris** [comment]
Hi @cgardens, I'm happy to try working on a PR if you can help point me in the right direction. Our pain point using Airbyte at the moment is that we have to do a lot of manual type casting in dbt after integration whereas if we use tools like Stitch, Fivetran, we won't have to worry about converting data types.

**Comment by cgardens** [comment]
Hi @tuanchris. It is a change that will touch a few different places. 
1. The place to start is here to make the platform aware of new data types: `JsonSchemaPrimitive.java` and anywhere it is used
2. Then for the database code you'd have to add the new types here `JdbcSourceOperations` (or for your respective database) (@tuliren may be able to point you in a slightly clearer direction on this)
3. Finally we would need to add logic in normalization to parse those types (@ChristopheDuong can comment on that better than i can)

**Comment by tuliren** [comment]
For databases, we are in the progress of fixing all the type issues on the source side. To patch the destination side, however, it will take more time. Some fundamental changes may be needed to better support those types on the destination (e.g. do the type conversion directly in the destination connector, instead of doing it through dbt).

@tuanchris, what are the destinations you need to have better type support?

**Comment by tuanchris** [comment]
> For databases, we are in the progress of fixing all the type issues on the source side. To patch the destination side, however, it will take more time. Some fundamental changes may be needed to better support those types on the destination (e.g. do the type conversion directly in the destination connector, instead of doing it through dbt). Modifying the current `JsonSchemaPrimitive` enums may not be the best approach. These enums may need to be changed to a class.
> 
> @tuanchris, what are the destinations you need to have better type support?

@tuliren we would love to have support for BigQuery and Snowflake. The most common sources that we are using are Postgres and MySQL. It would be great to have these sources and destinations work well together.

**Comment by nauxliu** [comment]
Any updates on this?

**Comment by edgao** [comment]
it's in-progress - we've written some new tests to check connectors for all the types being supported, but still need to bring connectors into compliance with those tests. This is being tracked in https://github.com/airbytehq/airbyte/issues/9441

**Comment by alafanechere** [comment]
@edgao I wondered if the effort tracked in #9441 will make JDBC connectors output integer type in JSON instead of the number type which results in storing float in the destination?

**Comment by edgao** [comment]
I don't think it will, but it does give us a better framework for supporting that distinction.

**Comment by sherifnada** [comment]
#9441 does this, closing

**Comment by alafanechere** [comment]
@edgao I opened this [issue](https://github.com/airbytehq/airbyte/issues/12606) as a followup to my previous comment. Let me know if its a duplicate, or if a broader one exists.
