### ISSUE TITLE
Mistake in JSON schema

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#5133]
https://github.com/airbytehq/airbyte/blob/9e5054b891cf185fa125e2dba1cd50b1b527d56f/airbyte-integrations/connectors/source-harvest/source_harvest/schemas/clients.json#L28-L30
https://help.getharvest.com/api-v2/clients-api/clients/clients/

**Comment by cheyura** [comment]
@sherifnada @igrankova

**Comment by sherifnada** [comment]
@cheyura I'm not sure I understand what this issue is tracking. Can you clarify what the expected follow up action here is?

**Comment by igrankova** [comment]
@sherifnada the Currency can't have the date-time format, we suppose there should be removed the date-time format for this variable.

**Comment by grubberr** [comment]
it's already fixed in this commit 845f84b4174a7c25a32e411dcbc035af045a7dec
