### ISSUE TITLE
SendGrid source doc: mention that legacy marketing campaigns are not supported

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#5163]
In SendGrid, there are two different toolsets with two different APIs: "new marketing campaigns" and "legacy marketing campaigns".  Lots of people are still using the "legacy marketing campaigns" (as [SendGrid has not set any date for retiring them yet](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns#faqs), [migrating to the new marketing campaigns is a non-trivial amount of work](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns#how-do-i-upgrade-my-marketing-campaigns-plan), and [SendGrid is not providing automated migration tools](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns#why-arent-you-migrating-my-account-automatically)).

It would be great for the [SendGrid documentation](https://docs.airbyte.io/integrations/sources/sendgrid) to highlight that the source connector only supports the new marketing campaigns, not legacy marketing campaigns.  Legacy marketing campaigns will fail with the somewhat mysterious error:

```
HTTPError: 403 Client Error: FORBIDDEN for url: https://api.sendgrid.com/v3/marketing/campaigns
```

So, calling this out up front will save people significant time.  Draft:

> **Note:** SendGrid provides two different kinds of marketing campaigns, "legacy marketing campaigns" and "new marketing campaigns".  **Legacy marketing campaigns are not supported by this source connector.**  If you are seeing a `403 FORBIDDEN` error message for `https://api.sendgrid.com/v3/marketing/campaigns`, it might be because your SendGrid account uses legacy marketing campaigns.

**Comment by avida** [comment]
Updated a doc, @zestyping  many thanks
