### ISSUE TITLE
DNS support for ssh-tunnel bastion host for connector testing infrastructure

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#5167]
We have a bastion host for use in testing ssh tunnel features from airbyte connectors.  The bastion is hosted on AWS with a public IP and proxies for a private RDS instance (used only for automated testing).  To connect to the bastion, we're currently hard-coding the public IP address, which is not ideal in case of node failure.  We'd like a standard DNS entry for it instead, preferably in Route53 so we can update it from the same terraform that would recreate the bastion node, causing a change of ip.

This may require some DNS configuration adjustments to support the feature in addition to the A record itself.

Terraform is in airbyte/airbyte-integrations/aws/ssh_tunnel/*.tf

**Comment by davinchia** [comment]
No longer applies.
