### ISSUE TITLE
Automate publishing new integration images

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#517]
## Tell us about the problem you're trying to solve
Publishing new integration images requires manually running `./tools/integrations/manage.sh`. This is cumbersome (especially when updating multiple integrations), easy to forget, and can possibly run out of sync with the core app (it is possible to upgrade the core codebase to rely on an integration version that has not been published to dockerhub). 

## Describe the solution you’d like
An automated way to push integrations to dockerhub if their versions have been bumped, preferably as part of the build process.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368110203392) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment]
would be nice if it also used something like this to update dockerhub docs https://github.com/peter-evans/dockerhub-description

**Comment by ChristopheDuong** [comment]
yes, please!!

Or at least similar to how we launch integration tests on a connector with a GitHub comment

**Comment by girarda** [comment]
closing because I interpret the ask as being /publish. @sherifnada feel free to reopen if you disagree
