### ISSUE TITLE
New Source: Heap Analytics

### ISSUE THREAD

**Issue by kyle-cheung** [airbytehq/airbyte#5170]
## Tell us about the new connector you’d like to have
* Source is [Heap Analytics](https://developers.heap.io/reference)
* Destinatoin is Snowflake

## Describe the context around this new connector
* Our Product team uses Heap Analytics instead of Amplitude for our Product Analytics. Would be great if we could get this data into our warehouse for analysis

## Describe the alternative you are considering or using
*Alternative is to use another third-party ETL provider

## Are you willing to submit a PR?
Not technical enough!

**Comment by sherifnada** [comment]
@kyle-cheung is it an option for you to enable Heap Connect to dump the data to any of the data warehouses mentioned [here](https://help.heap.io/category/integrations/data-warehouses/)?

**Comment by kyle-cheung** [comment]
@sherifnada i didnt realize this was available! I definitely could, though I think it might require a premium subscription with them. Will check it out

**Comment by sherifnada** [comment]
yeah, since Heap doesn't expose an export API directly, airbyte wouldn't be able to pull heap data without using Heap Connect to dump the data to S3 or something first

**Comment by sherifnada** [comment]
@kyle-cheung were you able to look into the S3 export?

**Comment by kyle-cheung** [comment]
@sherifnada I was able to use Heap connect and access their shared db. Thanks for following up!
