### ISSUE TITLE
Wrong number records using MySQL innoDB vs columnstore engine

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5183]
## Enviroment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Try to sync two tables one created with innoDB engine and other with columnstore.
Both sync job succeded but one table missed one record.
[Slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1627563482058400)

## Expected Behavior
Should work for both engine.

## Logs
No logs.

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Investigating

**Comment by grishick** [comment]
GL team, could you please test this and determine if:
1. The problem still exists
2. If the problem exists, is the source emitting all the records and the destination is missing one or is the source not emitting some records

**Comment by yurii-bidiuk** [comment]
I tried to reproduce this issue with a different configuration, but it's not reproducible for me. I close this ticket.
