### ISSUE TITLE
Slack as a source - unable to complete sync - goes into retry mode

### ISSUE THREAD

**Issue by krishmanoh2** [airbytehq/airbyte#5184]
Is this your first time deploying Airbyte: Yes
OS Version / Instance: CentOS 8
Memory / Disk: 128Gb / 1Tb SSD
Deployment: Docker
Airbyte Version: 0.29.2-alpha
Source name/version: Slack
Destination name/version: local CSV
Description: I'm trying to sync for the first time and the process doesn't finish.
## Current Behavior
Initial sync is stuck on channel_members and looks to go into a retry loop. I see some data being written (when destination is local CSV) to channel_members, but others (messages, threads, users etc) are empty.

I had initially tried with Postgres a destination, however it showed the same behavior (minus the logs showing the errors). Local CSV reported errors.

## Expected Behavior
Initial sync should complete and incremental should continue.

## Logs
Attached. Can send more logs if needed.
[Untitled.txt](https://github.com/airbytehq/airbyte/files/6931219/Untitled.txt)

## Steps to Reproduce
1. Configure source as slack
2. Configure local csv as target
3. Initial sync

## Are you willing to submit a PR?
Not at the moment
[logs-7-0.txt](https://github.com/airbytehq/airbyte/files/6931207/logs-7-0.txt)

**Comment by lazebnyi** [comment]
@krishmanoh2 Thanks for your issue. Could you provide a full log file with full attempts list? Thanks!

**Comment by lazebnyi** [comment]
According to last log it's normal behavior for slack connector. Repeating line `Retrying. Sleeping for 3 seconds` means that we get 429 error and retry after time is 3 min and after we get record than we send request again and get same situation. 

```
Request -> 429 Respose 
Wait 3 sec
Request -> 200 Response
Request -> 429 Response  
Wait 3 sec
Request -> 200 Response
Request -> 429 Response  
Wait 3 sec
Request -> 200 Response
...
```

Only after 5 429 Response in a row we get erorr.  

Waiting time and frequency Slack chose dynamically based on diferent parameters. 

May be you have full log with erorrs for all attemts (like you send before logs-7-0.txt but with all attemts)?

**Comment by krishmanoh2** [comment]
[logs-201-1_csv.txt](https://github.com/airbytehq/airbyte/files/7010739/logs-201-1_csv.txt)
[logs-199-0_mysql.txt](https://github.com/airbytehq/airbyte/files/7010740/logs-199-0_mysql.txt)

I let it run and it finally succeeded. Csv as destination failed once. Is this normal with slack as a source? It took ~4hrs. Csv was close to 5hrs. The volume is trivial.

**Comment by lazebnyi** [comment]
Unfortunately, Retry-After time sets on Slack side. So, the duration of sync depends on Slack API.
