### ISSUE TITLE
Import Configuration removes all available connectors

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#5187]
## Enviroment
- **Airbyte version**:  example is 0.29.2-alpha
- **Source Connector and version**: any
- **Destination Connector and version**:any
- **Severity**:  Medium
- **Step where error happened**: Deploy

## Current Behavior
exporting and reimporting the configuration through the webapp (settings -> configuration -> import) causes all available sources ad destinations to disappear, except those that are actually used

## Expected Behavior
everything should stay the same

## Steps to Reproduce
1. deploy a fresh airbyte instance
2. add a connection (from any source to any destination)
3. export configuration to .gz
4. import that same file

all other sources and destination disappear from settings

exported config: 
[3a5dae59-975c-43da-aa8c-daea94e49816.gz](https://github.com/airbytehq/airbyte/files/6931659/3a5dae59-975c-43da-aa8c-daea94e49816.gz)

**Comment by tuliren** [comment]
I can reproduce this issue with the latest commit from the master branch: abde7c77278ce6efb221a37c82a71a629d7d3b2e. Still looking for the root cause.
