### ISSUE TITLE
Deduplicate all directory names to avoid producing jars with conflicting names.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5188]
## Tell us about the problem you're trying to solve
As title.

This is only a problem when Cloud modules try to depend on jars with the same name. The jars override each other and produce a mess.

This unblocks letting us properly depend on the OSS repo.

## Describe the solution you’d like
Directories with identical names will take on the parent directory name to dedup.

**Comment by davinchia** [comment]
good idea on adding assertions to check for conflicting names. let me play around with this.

**Comment by lmossman** [comment]
Maybe a dumb question, but have we checked if there is a way to set the jar name to use the full directory path? E.g. if the path is `airbyte-config/init` then the jar name is set to something like `airbyte-config-init` or `airbyte-config_init`?

**Comment by jrhizor** [comment]
@lmossman the complication is having the jars be able to specify dependencies on each other. If we rename them AND update the dependencies in the published jars to point at the new names, that would work.
