### ISSUE TITLE
Creating a workspace in cloud requires 2 API calls

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5191]
## Tell us about the problem you're trying to solve
When creating a workspace for the cloud version of the product the UI needs to make to API calls:
```
workspacesService.create
cloudWorkspacesService.create
```
A UI or API user should be able to make a single API call to setup a workspace.

**Comment by cgardens** [comment]
fyi @ChristopheDuong . would be curious how you would think about this one.

**Comment by Jamakase** [comment]
Also 1 more use case that we found - we should not only create cloud_workspace, but create proper permissions for user.
