### ISSUE TITLE
Set endpoint resource access controls on cloud api

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5194]
## Tell us about the problem you're trying to solve
For the Config API we scope the access to endpoints based on who is logged in. We need to do the same for all of the endpoints in the Cloud API. We want to do this after we have a working E2E demo as it'll be easier to implement this way.

**Comment by jrhizor** [comment]
Released + with automated tests. Still needs a deploy and some manual testing (ty @davinchia for doing this) but anything that comes up should be a new issue.

**Comment by davinchia** [comment]
UI testing with Charles shows this should be okay.

Also tested with curl to make sure this is gated.
