### ISSUE TITLE
Enforce downtime in deploy for cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5195]
## Tell us about the problem you're trying to solve
This is not a typo ^. For right now the app assumes one server pod is running and that every time we deploy there could be a schema change. We plan to fix this soon, but until then, whenever we deploy, all existing pods should be spun down before new ones are spun up.

**Comment by davinchia** [comment]
@cgardens I think we can leave temporal up?

**Comment by cgardens** [comment]
at least until we decide to upgrade temporal. 😛  is there a reason to not just take it down? is it particularly slow or something. it seems like by leaving temporal up we could have jobs that are still running when we restart which might mean that if we make a change in core they may complete and be incompatible. that being said, if there some other overriding concern with taking temporal down then that's okay.

**Comment by jrhizor** [comment]
If the scheduler's down it doesn't really matter if the temporal service is up.

**Comment by davinchia** [comment]
Hmm nvm, I'm going to recreate everything to keep it consistent.
