### ISSUE TITLE
create web backend endpoint for creating a non-default workspace 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5206]
see https://airbytehq.slack.com/archives/C0229LM09T4/p1628120772085000?thread_ts=1628119248.075500&cid=C0229LM09T4 for more context

**Comment by cgardens** [comment]
does this overlap with  https://github.com/airbytehq/airbyte/issues/5191 or should we handle it separately?

**Comment by jrhizor** [comment]
this is a duplicate
