### ISSUE TITLE
Cloud sign up should incorporate email verification.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5214]
## Tell us about the problem you're trying to solve
After signing up, a user should be required to verify email before proceeding. Today we just let users log in.

## Describe the solution you’d like
Placeholder ticket - need to do more digging into how to do so.

**Comment by davinchia** [comment]
This is done on the frontend. We are going to give users a day before enforcing this on the backend.

**Comment by tuliren** [comment]
I can confirm that this is already working in dev cloud.
