### ISSUE TITLE
use the full width of the screen when displaying logs in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5220]
## Tell us about the problem you're trying to solve
The window for reading logs is too small: 
<img width="1792" alt="Screen Shot 2021-08-04 at 11 02 17 PM" src="https://user-images.githubusercontent.com/6246757/128299489-b722abd4-aae7-4ea3-ad7e-3cdf8be64565.png">

## Describe the solution you’d like
1. Allow the log window to take up 90 or 95% of the window size
<img width="1661" alt="Screen Shot 2021-08-04 at 11 01 46 PM" src="https://user-images.githubusercontent.com/6246757/128299271-fcb78a4d-390c-4e01-b9a5-da2fdd2ef400.png">
2. Disable the need for horizontal scrolling within the wide window 

A solution could potentially be to create a button which opens a full-screen modal with the logs

cc @jrhizor

**Comment by jrhizor** [comment]
This is a somewhat commonly requested feature.

**Comment by cgardens** [comment]
agreed. i thought we had another issue for this but i can't find it right now.

**Comment by cgardens** [comment]
Let's also use the full length of the page too. 
![Screen Shot 2021-08-07 at 2 20 54 PM](https://user-images.githubusercontent.com/9092207/128614117-10317595-d1dd-408b-b305-73db9474497f.png)
