### ISSUE TITLE
Display news assets for Airbyte Cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5226]
## Tell us about the problem you're trying to solve
We have the skeleton of sign up / login UI. We need the news assets that should be displayed on the right.
<img width="1789" alt="Screen Shot 2021-08-04 at 9 47 05 PM" src="https://user-images.githubusercontent.com/9092207/128387459-61c206ef-58be-4223-8403-ca979991c139.png">

@johnlafleur can you provide the news assets and then we'll get them added.

**Comment by johnlafleur** [comment]
The good point with Figma is that I shouldn't have to export the asset as the developer can do that by themselves, in the format they need. Or am I missing anything?
Here's the link to the Figma: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26178%3A142

**Comment by cgardens** [comment]
@johnlafleur thanks! That works for me.

**Comment by Jamakase** [comment]
@johnlafleur yeah that works, but there is 1 problem with "Tfir" logo - it is actually not an asset but just an object built from shapes. Could you please provide an asset for it?

**Comment by johnlafleur** [comment]
Here's an asset for TFIR: 
![TFiR_Logo_2020](https://user-images.githubusercontent.com/68561602/128647178-d089d061-1ce3-4ab9-ada9-b6d2309f459f.png)
