### ISSUE TITLE
Add workspace slug to url in webapp

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5227]
## Tell us about the problem you're trying to solve
> Artem brought up a good idea that we can provide a better experience by actually displaying the current workspace id in the url e.g. airbyte.io/workspaceSlug/rest-of-the-path .  Sounds like the changes would be on the webapp so we won't need to do anything on the backend. This would work since we are routing all request other that those starting with /cloud and /api to the webapp

[slack convo](https://airbytehq.slack.com/archives/C0229LM09T4/p1628157317094300) with unanimous agreement.

**Comment by jrhizor** [comment]
If this was supported in the OSS side it would be 90% of https://github.com/airbytehq/airbyte/issues/3305 as well

**Comment by cgardens** [comment]
It looks like this might help with UI routing as well. I'm noticing that when I refresh the page while in my workspace, I end up back in the list of workspaces. Also if an exception is ever throw, I end up back in the list of workspaces as well. In both cases, I think it would be more ergonomic to end up in the "main" page for whatever the current workspace a user is using. Because it seems related to these routing issues, I am going to increase the priority. If we want to do something else to solve the routing issue we can lower priority again.

**Comment by cgardens** [comment]
moved this to post beta launch. going to do a smaller change to start with to get us through the launch: https://github.com/airbytehq/airbyte/issues/5284
