### ISSUE TITLE
Multiline connector spec field fails to honor the "airbyte_secret": true tag.

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#5231]
## Enviroment
- **Airbyte version**:  0.29.2-alpha
- **OS Version / Instance**: macos
- **Deployment**: docker-compose

## Current Behavior

The following json produces a connector spec field which should be hidden like a password, with an eyeball icon for show/hide, but instead it treats it as an unprotected text area.  The plain text is always clearly visible.

```
              "tunnel_usersshkey": {
                "title": "SSH Private Key",
                "description": "OS-level user account ssh key credentials for logging into the bastion host.",
                "type": "string",
		 "airbyte_secret": true,
                "multiline": true,
                "order": 7
              }
```    

If I remove the multiline indicator, the field acts like a password entry area like expected.  If I put multiline back in, it no longer works as a password field.

## Expected Behavior

The airbyte_secret:true indicator should work even on a multi-line field.

**Comment by sherifnada** [comment]
@cgardens @jrhizor not quite blocking for cloud but heavy related

**Comment by cgardens** [comment]
cool. still a lot of FE stuff to get to before wednesday. adding it to the list but towards the bottom for right now.

**Comment by Jamakase** [comment]
@jennybrown8 Actually behaviour with multiline differs a bit from one with password: it displays next component instead:

![image](https://user-images.githubusercontent.com/3767150/140643561-ce7b45a9-a775-4679-9b1e-74314878c917.png)

So when you create connection: it will be displayed as textarea but when editing everything will be hidden.

I have created small PR, which handles cases when initial value was set to empty string during creation. Everything else here is working as intended ( https://github.com/airbytehq/airbyte/issues/2015#issuecomment-791452223 )

@jrhizor @cgardens
