### ISSUE TITLE
New Source: Airbyte native Google Search Console

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5235]
## Tell us about the problem you're trying to solve
As part of the migration away from Singer based connectors in #3582 we want to rewrite this connector using the Airbyte CDK. We should perform vetting as normal and treat this as a brand new connector rather than copy all features the Singer connector supports.

**Comment by gaart** [comment]
@sherifnada

We just merged this connector into master and released a new version of the connector. 

The connector will be available in the next release of Airbyte (we usually release every Tuesday). If you can't wait and want to get started now trying it out in a running Airbyte instance, add the connector like described in https://docs.airbyte.io/integrations/custom-connectors#adding-your-connectors-in-the-ui . The information for the connector is: 

**Display Name**: Google Search Console
**Docker repository name**: airbyte/source-google-search-console
**Docker image tag**: 0.1.0
**Documentation URL**: hub.docker.com/r/airbyte/source-google-search-console

Please let us know if you have any further questions. 

Enjoy!
