### ISSUE TITLE
Airbyte CDK: allow extra request parameters

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#5246]
## Tell us about the problem you're trying to solve
I'd like to make sending the requests more configurable for each stream. For now it seems to be too much hardcoded.

## Describe the solution you’d like
I'd like to make request/prepared request args configurable. Assuming smth like
``` 
request = self._session.prepare_request(requests.Request(**self.get_prepared_request_kwags(
    stream_state=stream_state, 
    stream_slice=stream_slice, 
    next_page_token=next_page_token,
    headers=dict(request_headers, **self.authenticator.get_auth_header())))
)
```
So `get_prepared_request_kwags` is going to return a dict with params, required in any case. `get_prepared_request_kwags` should also have a default response, because the override is not required in most cases.

## Describe the alternative you’ve considered or used
The alternative with I've used is described below. Another alternative which I think is just to add `auth` arg to `_create_prepared_request`. But it's just a quick fix, and won't help us if we need some additional params in the future.

## Additional context
I've used to override `_create_prepared_request` in https://github.com/airbytehq/airbyte/pull/4863 just to be able to add `auth` arg to the prepared request, which is common `requests` flow.

## Are you willing to submit a PR?

Yes.

**Comment by girarda** [comment]
this can be done either with HttpStream or low-code. Feel free to reopen and update if you disagree
