### ISSUE TITLE
Review connector's failure report and fix if possible

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5253]
## Enviroment
GH

## Current Behavior

FAILED TWO LAST BUILDS - 45 connectors:
destination-scaffold-destination-python ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841490
source-amplitude                        ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841559
source-appsflyer-singer                 ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841571
source-asana                            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841593
source-cockroachdb                      ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841698
source-exchangeratesapi-singer          ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841770
source-facebook-marketing               ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841779
source-github-singer                    ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841818
source-gitlab                           ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841827
source-gitlab-singer                    ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841829
source-google-adwords-singer            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841857
source-google-search-console-singer     ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841893
source-google-sheets                    ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841903
source-google-workspace-admin-reports   ✅❌✅❌✅❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841912
source-googleanalytics-singer           ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841925
source-harvest                          ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841941
source-instagram                        ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841950
source-intercom-singer                  ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105841985
source-jdbc                             ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842017
source-klaviyo                          ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842026
source-looker                           ✅✅✅✅✅✅✅✅❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842053
source-mixpanel-singer                  ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842115
source-mssql                            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842144
source-mysql                            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842148
source-okta                             ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842160
source-plaid                            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842249
source-postgres                         ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842250
source-python-http-tutorial             ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842297
source-quickbooks-singer                ✅✅❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842324
source-recharge                         ❌✅❌❌❌✅❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842332
source-redshift                         ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842344
source-scaffold-java-jdbc               ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842365
source-scaffold-source-http             ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842366
source-scaffold-source-python           ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842375
source-shopify-singer                   ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842390
source-slack                            ❌✅❌✅❌✅❌✅❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842393
source-slack-singer                     ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842398
source-snapchat-marketing                ✅✅✅✅✅❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842408
source-stock-ticker-api-tutorial        ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842453
source-stripe                           ✅✅❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842454
source-surveymonkey                     ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842465
source-tempo                            ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842476
source-twilio                           ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842490
source-zendesk-chat                     ❌❌❌❌❌❌❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842496
source-zendesk-support-singer           ✅✅✅✅✅✅❌❌❌❌ https://github.com/airbytehq/airbyte/actions/runs/1105842506

## Expected Behavior
All tests should pass

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by sherifnada** [comment]
@midavadim why don't we pick 3 of these builds per developer to fix this sprint? We'll slowly make progress on this over the next couple of weeks without overwhelming any one developer.

**Comment by sherifnada** [comment]
we should also be sure to ignore builds from deleted `-singer` connectors: 

* mixpanel
* github
* gitlab
* slack
* shopify 
* intercom

**Comment by midavadim** [comment]
Whole review with 'failure' classification
https://docs.google.com/spreadsheets/d/1xq2OVuSbE-mGLqLX8ghi2Od3jJc_Kdi2-9-ufE3BqLc/edit#gid=0
![Failure](https://user-images.githubusercontent.com/3889748/132841327-d65807c6-a974-4a7e-a204-04ff6a2a7379.png)

**Comment by midavadim** [comment]
Failure by priority:

**Schema:**
source-amplitude
source-asana
source-chargebee
source-gitlab
source-google-adwords-singer 
source-google-search-console-singer
source-google-sheets
source-harvest
source-klaviyo
source-okta
source-pipedrive
source-posthog
source-quickbooks-singer
source-sendgrid
source-slack
source-smartsheets 
source-surveymonkey
source-tempo
source-twilio
source-zendesk-sunshine

**Spec:**
source-bing-ads  
source-s3

**Test:**
source-cart
source-dixa
source-facebook-marketing
source-jdbc
source-prestashop 
source-scaffold-java-jdbc   
source-snapchat-marketing
source-stripe
source-zendesk-support
source-square

**Creds:**
source-appsflyer-singer
source-python-http-tutorial
source-scaffold-source-http 
source-scaffold-source-python
source-stock-ticker-api-tutorial
source-zuora

**Connection:**
source-cockroachdb
source-plaid
source-recharge

**Comment by midavadim** [comment]
#5979 
#5978 
#5977 
#5972
