### ISSUE TITLE
Handle when a user tries to delete their only workspace

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5264]
## Tell us about the problem you're trying to solve
If a user tries to delete their only workspace, they will be thrown in a bad state (I am guessing that this is true, I have not had the opportunity to test it yet). The system assumes that user has at least one workspace in a lot of places.

## Describe the solution you’d like
I'd suggest that in the short term we do not allow the user to delete a workspace if it is their only workspace and display an error message saying so.

## Tasks
- [ ] _(backend) implement this validation in the API_
- [ ] _(frontend) expose the error message in the UI_

@davinchia @jrhizor what do you think? how should we treat the urgency of this?

**Comment by jrhizor** [comment]
low for private beta launch, high for public beta
