### ISSUE TITLE
Parallelize any checks needed to configure a connection

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5268]
## Tell us about the problem you're trying to solve
In the case where a source and destination are already configured, if a user tries to create a new connection with them, they must wait for the following to happen _serially_: source check connection, destination check connection, source discover schema. These 3 operations can be kicked off all at the same time. Doing so will decrease wait times for configuring a connection. 

To the user, the feedback should appear serially. e.g. if discover fails first while source check is still running, we should not tell the user that discover failed until source check connection completes. if it succeeds then we would just show the discover failure and if it fails, we should just show the check connection failure and not the discover failure.

In the case where the source already exists and the destination is new or the destination already exists but the source is new, the same is true that we can kick off all 3 of these operations in parallel.

**Comment by jrhizor** [comment]
We ended up removing the redundant checks.
