### ISSUE TITLE
UI Exception after creating a destination

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5270]
## Tell us about the problem you're trying to solve
In the onboarding flow or the create connection flow, after hitting submit on the create destination step (assuming the check connection succeeds), a UI error gets thrown which redirects the user back to the workspaces list page. It does not seem to happen when just creating a destination from the destinations tab. Looks like it is triggered by some logo asset not loading properly. This may be specific to airbyte cloud? I haven't tests on OSS. I know the hosted version has had some kinks to work out with loading image assets.

Video 

https://user-images.githubusercontent.com/9092207/128615027-6d95fa49-2ded-4049-9167-643981f5d1d5.mp4

Screenshot of error logs
![Screen Shot 2021-08-07 at 3 09 00 PM](https://user-images.githubusercontent.com/9092207/128615016-a74000a3-3aea-4c09-a081-e06962a23edd.png)

**Comment by Jamakase** [comment]
This is the same issue as #4893

Logo or image download never crashes the app. 

Should we close it as duplicate?
