### ISSUE TITLE
issues with workspace/list

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5280]
see slack conversation: https://airbytehq.slack.com/archives/C0229LM09T4/p1628510168187600

> Artem observed that deleting a workspace (that isn’t the last workspace) led to errors in the workspace list route 
> 
> And apparently later on deletes weren’t removing workspaces. Unsure if that is a result of the list route breaking or something else

**Comment by jrhizor** [comment]
Can we close this?
