### ISSUE TITLE
Support option for "split worker mode" where separate source workers run on individual entities of a source

### ISSUE THREAD

**Issue by cjwooo** [airbytehq/airbyte#5283]
## Tell us about the problem you're trying to solve
We sometimes pull extremely large sources, such as very large/old Jira projects, and sometimes the entities of a source, e.g. Github repositories or Jira projects, etc., have misconfigurations that prevent our connector (non-Airbyte currently) from completing. We don't want our connector to fail because one of the entities is misconfigured.

## Describe the solution you’d like
Support a split-worker mode where Airbyte spawns multiple worker containers, with each worker assigned to an entity of the source.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
My understanding of this issue is that it is per-stream resiliency. Going to close it as a duplicate. Agreed this is very valuable and something we are considering early next year.
