### ISSUE TITLE
Source Hubspot fails in normalization step.

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5293]
## Enviroment
- **Airbyte version**:  0.29.1-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Docker
- **Source Connector and version**:Hubspot
- **Destination Connector and version**: Not informed
- **Severity**: Very Low / Low / Medium / **High** / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Hubspot fails in normalization step because bad double value in catalog.

## Expected Behavior
Should work.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```
[limited-log.txt](https://github.com/airbytehq/airbyte/files/6958675/limited-log.txt)
```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Not at the moment

**Comment by sherifnada** [comment]
It looks like empty strings are being output as doubles. In this case we should output them as nulls.
