### ISSUE TITLE
Change Snowflake database level permission to schema level

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5301]
## Tell us about the problem you're trying to solve
Some users don't have full permission in destination but they should be able to use Airbyte to sync data.

## Describe the solution you’d like
I dont have full knowledge of the impact of just changing the permission level right now. Maybe the connector can validate the user permission level and restrict some features based on his level: namespacing overwritten, table deletes, etc. 

## Describe the alternative you’ve considered or used
~

## Additional context
Maybe the connector can work fine with schema permision but need to validate for normalization module.

## Are you willing to submit a PR?

Not atm.

**Comment by sashaNeshcheret** [comment]
@marcosmarxm please take a look at #6005 PR, in scope of it we decreased level of permissions from database to schema to allowing users sync to snowflake with schema ownership level. Is it enough, or you mean something else?

**Comment by alexandr-shegeda** [comment]
@subodh1810 could you probably assist us in this issue?
cc @misteryeo @sherifnada

**Comment by sherifnada** [comment]
@alexandr-shegeda @sashaNeshcheret I believe #6005 fixes the issue, closing this one.
