### ISSUE TITLE
Categorise connector based on global state or cursor per stream state

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5315]
## Epic
- https://github.com/airbytehq/airbyte/issues/6912

## Description
Tech spec: https://docs.google.com/document/d/1-2O3Kzfg9LIQUK0D1Rlc3WD31pQQ09Zqi2N6jtnBZhk/edit#
For schema evolution, we need a mechanism to identify whether a connector supports cursor per stream or has a global state(like cdc connectors). 

As part of this issue we need a way to ask the connector to tell us which kind of state logic it supports

**Comment by cgardens** [comment]
done
