### ISSUE TITLE
Implement a logic to reset an individual stream

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5317]
## Epic
- https://github.com/airbytehq/airbyte/issues/6912

## Description
As part of this issue we need to build a way to reset the data for an individual stream. 

New Requirements:
* Wipe out the entire state for a connector.
* Wipe out the state for individual streams.
* Wipe out the data for individual streams.
* Wipe out all data for a connector.
    * We can tolerate some misses here. e.g. if we try to wipe out the data but the current schema doesn't contain all streams because the schema evolved, it is okay if those streams not in the catalog are not wiped out.

The requirements and implementation for this issue are laid out in this [section of the spec](https://docs.google.com/document/d/10cpbytxVzuwSpLtAA4fQeDoXRE17sY81h0bTrUPSE7s/edit#heading=h.gfiykkub1u29).

**Comment by cgardens** [comment]
@annalvova05 @lmossman @benmoriceau @gosusnp - I have updated this issue to clarify some of the questions that came up in grooming today.

**Comment by danieldiamond** [comment]
@evantahler is this complete? Does this mean self-hosted airbyte instances are able to reset individual streams within a connector now?
