### ISSUE TITLE
Beacon CRM Source

### ISSUE THREAD

**Issue by joshualee-ifesworld** [airbytehq/airbyte#5325]
## Tell us about the new connector you’d like to have
* Which source and which destination? Beacon CRM source (https://www.beaconcrm.org)
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? not really, just the latest API will do

## Describe the context around this new connector
* Which team in your company wants this integration, what for? finance, donor services, IT, comms, senior mgmt
* How often do you want to run syncs? daily
* If this is an API source connector, which entities/endpoints do you need supported? People, Organization, Payments, Campaign, Funds, Subscriptions, GiftAid Claims, Gift Aid Declarations, Household

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte? manual daily CSV upload

## Are you willing to submit a PR? can be discussed, we would like to know further what are the PR requirements. thank you.

**Comment by igrankova** [comment]
@joshualee-ifesworld, can I ask you to support us in requesting the API key for Airbyte from the Beacon CRM support? They tell that they generate the API key for the paying customers only and if our customer would ask them for this, they will generate API key for Airbyte.

**Comment by joshualee-ifesworld** [comment]
@igrankova hi there, thanks for looking into this.
It seem like beacon's API key are only available for paying customers. in fact even their API documentation is only accessible to paying customers. 
I'll get back to u on this as soon as possible.

**Comment by joshualee-ifesworld** [comment]
Hi @igrankova, we were informed by Beacon that someone from Airbytes got in touch with them about building a connector. I assume that would be from you. We've confirmed with them that we are the ones initiating this. 
In fact for the past 1 week+ we were trying to speak with our account manager about this but he was on long leave. 

Airbytes have informed us that they will send the API keys directly to Airbytes for this. thank you so much

**Comment by igrankova** [comment]
Hi, @joshualee-ifesworld. Thank you for the confirmation. Yesterday I received the API Key from Beacon and now I can finish the vetting process for this connector. It will be implemented according to our development plan.

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
No

**Available authentication modes (API key/Oauth/other)** 
API key:
https://developers.beaconcrm.org/docs/account/21526

**Has Sandbox environment?** 
Yes,
https://app.beaconcrm.org/

**How to populate the account with data** 
UI,
API:
https://developers.beaconcrm.org/docs/account/21526

**Available streams for sync** 
Campaigns
Campaign members
Cases
Evens
Event attendees
Funds
Grants
Legacies
Major gifts
Memberships
Organisations
Payments
Payouts
People
Subscription
Tasks
Tickets
Volunteer applications

**Integration supports incremental sync?** 
No

**Other information/blockers** 
API key for the sandbox account is saved in LastPass. Filled up the test account with data from UI.

**Comment by igrankova** [comment]
@sherifnada, Vetting is completed, ready for implementation

**Comment by joshualee-ifesworld** [comment]
Hi @igrankova  i noticed that a few of the stream items that i have in my subscription is not included in your list. Namely "gift aid claims", "gift aid declaration", "household" and "subscription plan". 

we are reaching out on our end to Beacon to check if the dummy account they provided isnt complete.

**Comment by igrankova** [comment]
@joshualee-ifesworld, I've checked the API docs and the sandbox, and didn't find the streams you mentioned. Please let me know the Beacon's response about this issue.

**Comment by joshualee-ifesworld** [comment]
hi @igrankova, i believe it should be possible for us to build custom conectors on airbyte for customized data such as "household" and "subscription plans" right?

**Comment by igrankova** [comment]
hi, @joshualee-ifesworld, we have the plans to implement connector with custom streams in the future, but we initially prioritize standard streams. unfortunately I can't tell you the delivery date yet.

**Comment by joshualee-ifesworld** [comment]
noted, thank you so much. Really appreciate all the great work that you and your team are doing.

**Comment by joshualee-ifesworld** [comment]
Hi @igrankova, if you don't mind can i ask if there are any progress on this connector? thank you.
