### ISSUE TITLE
UI does not show error when download logs api returns a non success status code

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5330]
![Screen Cast 2021-08-10 at 10 05 55 PM](https://user-images.githubusercontent.com/9092207/128972755-8b61d5c0-d4b9-4aa5-88cd-de5e6c45adb8.gif)

## Environment
- **Airbyte version**:  example is 0.29.4-alpha

## Current Behavior
* when the download logs button returns a non-success status code the UI takes the error response and downloads it to a file.

## Expected Behavior
* ui should display an error in a popup (using the existing notification service)

**Comment by edmundito** [comment]
@cgardens would you recall how you got a 401 response when trying to download the log?

**Comment by edmundito** [comment]
Chatted with @timroes over slack. This screen is no longer available in cloud, and at least the issue should not occur on this page. However, I will add a notification if there is a download error.
