### ISSUE TITLE
Connector setup fails on Kubernetes for some image names

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#5331]
## Enviroment
- **Airbyte version**:  example is 0.29.2-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source/Destination Connector and version**: multiple
- **Severity**: Critical
- **Step where error happened**: Setup new connection / Update connector

## Current Behavior
setup and upgrade connector fails on kube if docker image name ends with `-` followed by exactly 10 characters, because pod name gets truncated to begin with `-`, which is invalid

## Expected Behavior
pod should be created and operation should succeed

## Logs
[scheduler-log.txt](https://github.com/airbytehq/airbyte/files/6966787/scheduler-log.txt)

## Steps to Reproduce
1. deploy on kube
2. either upgrade or setup connector with 10 character name (e.g. source "Google Ads" or "Prestashop", destination "Local JSON")

slack thread: https://airbytehq.slack.com/archives/C01MFR03D5W/p1628080477275700

**Comment by marcosmarxm** [comment]
Thanks for reporting this @m-ronchi. @davinchia / @jrhizor fyi.
