### ISSUE TITLE
Remove worker dependency from normalization module version

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5349]
## Tell us about the problem you're trying to solve
https://github.com/airbytehq/airbyte/blob/12ed325e28f7e23fe3ab5496d8cacaa6b917a8d4/airbyte-workers/src/main/java/io/airbyte/workers/normalization/DefaultNormalizationRunner.java#L50
This can lead to a problem when we upgrade normalization. We need to wait for a new Airbyte release to be able to use. Or, if we introduce a bug in normalization people can't downgrade to a older version and keep using Airbyte.

## Describe the solution you’d like
Probably we could add a env variable to be more flexible choosing the normalization operation version.

## Describe the alternative you’ve considered or used
None
## Are you willing to submit a PR?

Yes

**Comment by jrhizor** [comment]
I think what we've discussed before is having the normalization version be in sync with the overall Airbyte version. It's very hard to guarantee a range of versions compatible with a normalization version, so it's effectively tied to the same version anyway at the moment (which is why it isn't configurable).

**Comment by jrhizor** [comment]
related: https://github.com/airbytehq/airbyte/issues/2054

**Comment by ChristopheDuong** [comment]
Even if normalization is tied to an airbyte version, it could sometimes be helpful to have the ability to hot-swap/plug another normalization image

But this should probably be an exception rather than the general usage

**Comment by evantahler** [comment]
Closing this in favor of https://github.com/airbytehq/airbyte/issues/16671 which will strongly decouple normalization from the workers
