### ISSUE TITLE
🐛 Source mixpanel: basic normalization fails with duplicate field names

### ISSUE THREAD

**Issue by caiopedroso** [airbytehq/airbyte#5355]
## Enviroment
- **Airbyte version**:  0.29.4-alpha
- **OS Version / Instance**: macOS
- **Deployment**:  Docker
- **Source Connector and version**: Mixpanel (0.1.0) 
- **Destination Connector and version**: BigQuery (0.3.12)
- **Severity**: High
- **Step where error happened**:  Sync job

## Current Behavior
I’m trying to sync for the first time and the process fails in the normalization step, apparently, something broke the dbt process, the log is attached.
If I try without normalization (raw data), it runs successfully

## Expected Behavior
The normalized data appears at BigQuery without any error

## Logs

[logs-10-0.txt](https://github.com/airbytehq/airbyte/files/6970980/logs-10-0.txt)

**UPDATE - Apparently I have a field called username and another one userName, when I check the destination_catalog.json, I can see both fields, maybe this is causing the ambiguity that BigQuery is not able to resolve?

## Steps to Reproduce
1. Create a Mixpanel Source Connection and a BigQuery destination
2. Try to sync  with the Basic Normalization selected

**Comment by sherifnada** [comment]
> **UPDATE - Apparently I have a field called username and another one userName, when I check the destination_catalog.json, I can see both fields, maybe this is causing the ambiguity that BigQuery is not able to resolve?

@caiopedroso yup that would do it 😅 is renaming these an option at all?

**Comment by caiopedroso** [comment]
Sadly Mixpanel don't handle renaming properties/events, they only a have a feature called merge, but I'm not sure that it will hide one of the properties, I can try that.. keep u posted.

**Comment by caiopedroso** [comment]
@marcosmarxm  , Got you, I will try that, just waiting for the release of a fix for the M1 version and update here if I come up with a solution.

**Comment by misteryeo** [comment]
@caiopedroso is this still an issue?

**Comment by caiopedroso** [comment]
Yes @misteryeo , I was not able to work myself in a custom dbt model to try to solve that, if it's something that can be "out of the box" on airbyte, would appreciate it.

**Comment by roman-romanov-o** [comment]
@caiopedroso I've added handling of such case into Export stream in connector

Try to update to latest version of connector, that will fix your problem
