### ISSUE TITLE
Self hosted installation sending requests to https://dev-cloud.airbyte.io

### ISSUE THREAD

**Issue by dinesh-chander** [airbytehq/airbyte#5360]
## Enviroment
- **Airbyte version**:  example is 0.29.3-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker 
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**:  Low 
- **Step where error happened**: Deploy 

## Current Behavior
Self hosted version is sending requests to https://dev-cloud.airbyte.io. For e.g 
https://dev-cloud.airbyte.io/cloud/v1/web_backend/permissions/list_workspaces_by_user

## Expected Behavior
Is this expected? Ideally, the installation should be self contained (except integrations) and user/workspace data should be managed in local DB.

## Logs
*If applicable, please upload the logs from the failing operation. 
![image](https://user-images.githubusercontent.com/4879886/129134540-bc706a4d-0cdd-4ac3-a3a9-b51edf1e61fd.png)

## Steps to Reproduce
1. clone repository
2. docker compose up
3. check chrome dev console

## Are you willing to submit a PR?

No.

**Comment by cgardens** [comment]
Hi @dinesh-chander can you try upgrading to 0.29.4? The issues you mentioned are know for 0.29.3. Unfortunately we made a mistake when we published that release. I believe 0.29.4 should resolve all of the problems are you seeing. If it does not, feel free to re open the issue.
