### ISSUE TITLE
Define source and destination spec date fields as 'date'

### ISSUE THREAD

**Issue by inigomarquinez** [airbytehq/airbyte#5361]
## Tell us about the problem you're trying to solve

We're creating our own user interface so the users can define several sources. For that, we're retrieving the [source definition](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#tag--source_definition_specification). Some of the fields are dates, but they are marked as string. And it's a little bit frustrating having to write the date instead of selecting it using a datepicker.

## Describe the solution you’d like

I'd like those fields that represent dates to be marked as `date` instead of `string`.

## Describe the alternative you’ve considered or used

-

## Additional context

See `start_date` below (it's a text input):

<img width="659" alt="Captura de pantalla 2021-08-12 a las 9 21 49" src="https://user-images.githubusercontent.com/25435858/129154990-5c75095f-159e-4557-9a31-b09734f86f7c.png">

## Are you willing to submit a PR?

No

**Comment by moiz-lakkadkutta** [comment]
hey i am quite new to open source contribution so i can i give it a try?

**Comment by sherifnada** [comment]
@moiz-lakkadkutta go for it!
