### ISSUE TITLE
Add DynamoDB as the destination

### ISSUE THREAD

**Issue by jinnig** [airbytehq/airbyte#5385]
## Tell us about the new connector you’d like to have
* Which source and which destination?
I want to use DynamoDB as the destination.
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
No
## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
I use this for my personal project.
* How often do you want to run syncs?
daily

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
I can load the data into S3 and use Lambda to ingest the data into DynamoDB.

## Are you willing to submit a PR?
Yes, I will implement the connector and submit a PR.

**Comment by YQ-Wang** [comment]
Hey, I happen to need this destination as well. Let me know if I can be any help on this.

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/5561
