### ISSUE TITLE
BambooHR

### ISSUE THREAD

**Issue by aizenshtat** [airbytehq/airbyte#5413]
* Source: https://www.bamboohr.com/ destinations - postgres database and gcp bigquery

* Bomboo HR is an HR operational platform and we use it in our company for the on boarding, payroll, employee data etc. HR team is the primary user, but reports are used by many other departments. Mostly contains data about employees, and org structure. 

* Sync frequency: once a day

* It's an API connector, here are the API docs https://documentation.bamboohr.com/docs/getting-started

* Alternative: we are currently parsing the API using pandas before loading it to the database.

**Comment by sherifnada** [comment]
This was implemented in #5054 - @aizenshtat would it fulfill your needs?
