### ISSUE TITLE
New Source: Optimizely

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#5429]
## Tell us about the new connector you’d like to have
Optimizely - formerly known as Episerver - is a software company that provides web content management (WCM) (or CMS), digital commerce and digital marketing through its cloud service Episerver Digital Experience Platform. 

We use Optimizely to plan and target our newsletter campaigns. To analyze the campaigns and mailing performance, we need a way to extract the data into our data warehouse

## Are you willing to submit a PR?
We have already developed a connector for Optimizely and will create a PR for it :)

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
partially:
https://api.campaign.episerver.net/apidoc/index.html#/Webhooks

**Available authentication modes (API key/Oauth/other)** 
Rest API:
https://docs.developers.optimizely.com/web/docs/rest-api-getting-started
OAuth 2:
https://library.optimizely.com/docs/api/app/v2/index.html#section/Authentication/oauth2
Personal Token Authentication:
https://docs.developers.optimizely.com/web/docs/personal-token

**Has Sandbox environment?** 
Yes,
https://app.optimizely.com/v2/profile/api
Instructions:
https://docs.developers.optimizely.com/web/docs/technology-partners#sandbox-account

**How to populate the account with data** 
UI,
API:
https://library.optimizely.com/docs/api/app/v2/index.html

**Available streams for sync** 
Projects
Campaigns
Experiments
Audiences
Pages
Events
Attributes
Groups
Extensions
Plan
Scheduled Jobs
User
Collaborators
List Attributes
Sections
Features
Subject Access Requests
Environments
Search
Change History
Attribution
Export Credentials
Impressions Usage
Recommendations

**Integration supports incremental sync?** 
No

**Other information/blockers** 
API terms:
https://www.optimizely.com/legal/terms/api/

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation

**Comment by noah-abramson** [comment]
Would love to leverage this as well - any update on pushing this GA?
