### ISSUE TITLE
Shopify Connector Rate Limiting

### ISSUE THREAD

**Issue by manavkohli** [airbytehq/airbyte#5441]
## Enviroment
- **Airbyte version**:  example is 0.27.1-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.11
- **Destination Connector and version**: Postgres
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Right now, incremental sync jobs are taking somewhere between 12-14 hours. Given the size of the data (and performance we've seen with other ETL providers), I think the way in which data is being fetched may be suboptimal. It definitely could be the case that jobs do indeed require this amount of time, but am seeing loads for ~1 hour of syncing/backing off for with at most 100s of records, which should be well below the rate limit given that much time. 

Overall, 1,017 records read took 13 hours and 55 minutes on our most recent sync. According to the [Shopify API](https://shopify.dev/api/usage/rate-limits), we should be able to do 2 requests/second/store (with leaky bucket approach), which should be well below for that many records loaded.

All of the tables in this sync are being replicated using the "Incremental - Deduped + History" sync strategy.

## Expected Behavior
Load time should be <1 hour given Shopify rate limiting strategy.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

(Logs attached)
[logs-39-0.txt](https://github.com/airbytehq/airbyte/files/6995320/logs-39-0.txt)

<details>
<summary>LOG</summary> 

```
```

</details>

## Steps to Reproduce
1. Create a Shopify source/destination
2. Run sync jobs on a 24 hour schedule
3. Monitor sync times

## Are you willing to submit a PR?

Let me know if helpful

**Comment by marcosmarxm** [comment]
thanks for reporting this @manavkohli. @sherifnada for your information

**Comment by sherifnada** [comment]
@manavkohli thanks for the pointers! This is definitely helpful. Will update this issue as we move along.

**Comment by manavkohli** [comment]
@sherifnada @bazarnov thanks so addressing so quickly!
