### ISSUE TITLE
Airbyte Cloud: Onboarding Flow

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5445]
## Tell us about the problem you're trying to solve
In the [mock ups](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26178%3A387) the onboarding flow is re-styled. I'm not entirely sure if this was implemented and it is a bug that it is not showing up in cloud or if it still needs to be implemented (@Jamakase can you tell me which one it is?).

## Describe the solution you’d like
* Airbyte Cloud should use the new onboarding flow from the mock ups
* OSS should use the same onboarding flow (related to styles of oss and cloud should be the same see: https://github.com/airbytehq/airbyte/issues/5444)

**Comment by Jamakase** [comment]
It still needs to be implemented. Looks like currently, even old onboarding is disabled for cloud. I will update it as a section in separate PR and then will implement a new flow.
