### ISSUE TITLE
Document how to use StoryBook for connector configurations

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5446]
## Tell us about the problem you're trying to solve
@Jamakase added a cool tool called StoryBook to the FE code. It enables us to run just an individual react component. This is very helpful in the case where for a connector, we want to see what its configuration will look like in the UI. We can get a super fast iteration cycle by just loading it in story book without having to rebuild the world.

## Describe the solution you’d like
The ask for this issue is for @Jamakase to document how this can be used by other developers on the team.

@sherifnada - FYI. You'll think this is cool

**Comment by sherifnada** [comment]
Artem mentioned this earlier, sounds great! Will be a great companion to the [connector specification reference](https://docs.airbyte.io/connector-development/connector-specification-reference)

**Comment by jrhizor** [comment]
@sherifnada docs for this are available at https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/docs/HowTo-ConnectionSpecification.md
