### ISSUE TITLE
Frontend work for Signup Email Verification.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5453]
## Tell us about the problem you're trying to solve
Front end part of #5214.

1) Only users with verified email should be allowed to log in.
2) A user should be prompted to verify his email on sign up.
3) If an unverified user tries to log in, they should be prompted to re-verify their email.

How to is in this comment: https://github.com/airbytehq/airbyte/issues/5214#issuecomment-895304526

The backend will also have to enforce this, however does not block this.

**Comment by davinchia** [comment]
@Jamakase, Charles told me that the mockups include email verification. Lmk if it's not clear!

**Comment by davinchia** [comment]
Artem, we will also have to update the webapp to use prompt the user to verify their email when they update it. Up to you whether this ticket will cover both or we can split that work out.

**Comment by Jamakase** [comment]
Fixed in #5597
