### ISSUE TITLE
Release Airbyte Opensource core/platform via github actions

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5459]
Currently our release process is manual which makes it bug prone. We should try to build a github action that we can run on demand which would build images from whatever is available in master and then push em to docker hub and then update github with release and tag as well. Basically all the steps involved in the current release process.

**Comment by davinchia** [comment]
also update this doc: https://docs.google.com/document/d/1Q1N4oomtz3rXqqn97nMB5rfcM_Dd2K3in5vmYPWdjjY/edit#heading=h.rslbpj40lw24
