### ISSUE TITLE
Bigquery source connector can't fetch data with nested structs

### ISSUE THREAD

**Issue by cereusperuv** [airbytehq/airbyte#5460]
## Enviroment
- **Airbyte version**: 0.29.8
- **OS Version / Instance**: Windows 10
- **Deployment**: Docker desktop
- **Source Connector and version**: airbyte/source-bigquery 0.1.1
- **Destination Connector and version**: airbyte/destination-snowflake 0.3.12
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
Sync stops for BigQuery tables with array of nested structs. Error message:

`Exception in thread "main" java.lang.UnsupportedOperationException: Retrieving field value by name is not supported when there is no fields schema provided`

Array of just struct works fine.

## Expected Behavior
Sync should complete.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Create bigquery table with nested struct, such as e.g.
```
with
  bertil as (
    select
      "Bertil" AS name,
      190 as height,
      [struct<key string, value STRUCT<string_val string>>('work_place', struct('N/A')),
       struct<key string, value STRUCT<string_val string>>('country', struct('Sweden'))] as persons),
  linda as (
    select
      "Linda" AS name,
      176 as height,
      [struct<key string, value STRUCT<string_val string>>('work_place', struct('Home')),
       struct<key string, value STRUCT<string_val string>>('country', struct('Sweden'))] as persons),
  combined as (
    select *
    from bertil 
    union all 
    select *
    from linda )
select *
from combined
```
2. Start sync job

## Are you willing to submit a PR?

Not at this point.

**Comment by sherifnada** [comment]
note for implementation: we should add this as a test to as many shared comprehensive tests as possible (comprehensive, acceptance, jdbc, etc..)
