### ISSUE TITLE
New source: Prometheus

### ISSUE THREAD

**Issue by fwerva** [airbytehq/airbyte#5464]
## Tell us about the new connector you’d like to have
[Prometheus](https://prometheus.io/) is a free monitoring and alerting software which records real-time metrics.

## Describe the context around this new connector
* I would like to store aggregated data to generate insights and share them with the management
* I want to store the data on a daily basis
* Prometheus is using the HTTP-API which is reachable under `/api/v1`
* Expression queries via API endpoints
* Data is specifically nested and might cause trouble with Basic Normalization. [More Information](https://prometheus.io/docs/prometheus/latest/querying/api/)

## Describe the alternative you are considering or using
* Alternative was to use the [HTTP/REST API Connector](https://airbyte.io/connectors/rest-api) which unfortunately has been removed [#5185](https://github.com/airbytehq/airbyte/pull/5185)
* Use customized [Grafana](https://grafana.com/) Dashboards

**Comment by sherifnada** [comment]
@fwerva for the record: you can still use the HTTP connector by adding it as a custom connector for the moment. Would that help alleviate the immediate pain point? 

Which endpoints do you want to pull data from in the Prometheus API?

**Comment by fwerva** [comment]
> for the record: you can still use the HTTP connector by adding it as a custom connector for the moment. Would that help alleviate the immediate pain point?

Sure, this should be fine :)

At the moment, we are only using the /query endpoint to pull data from the Prometheus API, because the right PROM-QL statements allow us to select the spececific data we need. The requests somehow look like this

- `localhost:9090/api/v1/query?query=100 * (1 - avg by(instance)(irate(node_cpu{mode='idle'}[5m])))`
- `http://localhost:9090/api/v1/query?query=mysecondquery`

However, there are a lot of other endpoints which could be useful in the future:
- /query_range  
- /series  
- /labels  
- /label/<label_name>/values 
- etc.

**Comment by igrankova** [comment]
"Webhook-based? (no/partially/yes) 
partially:
https://prometheus.io/docs/alerting/latest/configuration/#webhook_config

**Available authentication modes (API key/Oauth/other)** 
Prometheus supports basic authentication and TLS.
https://prometheus.io/docs/prometheus/latest/configuration/https/
OAuth 2

**Has Sandbox environment?** 
No, install locally:
https://prometheus.io/download/

**How to populate the account with data** 
UI,
API:
https://prometheus.io/docs/prometheus/latest/querying/api/

**Available streams for sync** 
query
query_range
series
labels
label values
query_exemplars
targets
rules
alerts
metadata
alertmanagers
config
flags
runtimeinfo
buildinfo
tsdb
walreplay
snapshot
delete_series
clean_tombstones

**Integration supports incremental sync?** 
No:
There is no support for incremental updates.
https://prometheus.io/docs/prometheus/latest/http_sd/#requirements-of-http-sd-endpoints

**Other information/blockers** 
HTTP API:
https://prometheus.io/docs/prometheus/latest/management_api/

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation
