### ISSUE TITLE
New source: Microsoft excel online (sharepoint)

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5475]
## Tell us about the new connector you’d like to have
As an Airbyte user, I'd like to be able to pull spreadsheets from Microsoft sharepoint.

## Describe the context around this new connector
Airbyte supports Google sheets, but excel/Sharepoint has a large userbase as well

## Describe the alternative you are considering or using
spreadsheets anywhere singer tap

**Comment by igrankova** [comment]
Can't create Sandbox subscription. Error: "This service is temporarily unavailable due to a high volume of requests. Please try again later". Made several tries during a week, it doesn't allow to subscribe and I can't continue Vetting process.

**Comment by sherifnada** [comment]
Let's set a reminder to try again in one week if possible

**Comment by igrankova** [comment]
> Let's set a reminder to try again in one week if possible

I'm trying to manage this issue with the Microsoft support (created the support ticket)

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
partially:
https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks

**Available authentication modes (API key/Oauth/other)** 
Excel Services REST API
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-rest-api
Excel JavaScript API
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview?view=excel-js-preview

**Has Sandbox environment?** 
Yes:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing

**How to populate the account with data** 
UI,
OData:
https://docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-with-excel-services-rest-in-sharepoint

**Available streams for sync** 
Charts
Comments
Conditional formatting
Custom functions
Data validation
Events
PivotTables
Ranges and Cells
RangeAreas (Multiple ranges)
Shapes
Tables
Workbooks and Application-level APIs
Worksheets

**Integration supports incremental sync?** 
No

**Other information/blockers** 
-

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation

**Comment by alexsubota** [comment]
Hi, any news about this connector?

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [New Source: Microsoft SharePoint](https://app.harvestr.io/components/0/list/TWTSMXt0y)

**Comment by akshaysinghUdaan** [comment]
Hello guys, I am very new to open source. I have created a sharepoint excel online connector which is a custom implementation. It was done using microsoft graph API. I can contribute to this connector. 
@igrankova / @sherifnada  can you guide me into how to start? Anyone else already working on it? I have gone through contribution guidelines.

**Comment by nataliekwong** [comment]
Closing this issue as the Microsoft Sharepoint connector is now available in the Airbyte Connector Catalog.

You can read more about it here: https://docs.airbyte.com/integrations/sources/microsoft-sharepoint
