### ISSUE TITLE
Expose `WHERE` queries and transactions in config database

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5479]
## Tell us about the problem you're trying to solve
* Because of its origins as a file based database, the `ConfigPersistence` does not expose any functionality for `WHERE` queries or cross-resource transactions.
* `WHERE` queries. We allow for two read operations in the `ConfigPersistence`. 1. Look up a single record by id (efficiently). 2. List all records of a resource type (e.g. list all connections). If we ever need to do a where clause (e.g. list all connections from source X; or all permissions records for user Y), we list _all_ of the records for the resource and then filter in memory. This is already breaking for users with many connections.
* Cross-Resource Transactions: We cannot currently support doing multiple inserts as a single transaction. An example where this can run into correctness issues is in the case of user creation. When we create a user record, we want to create the permission record that connects a user to their default workspace at the same time we create the user. If one is not created, then we don't want to create the other.

## Follow on tasks
* Once we have this we can start paginating our APIs. This should be handled as a separate issue.

## Describe the solution you’d like
* As an engineer, I want to be able to write `WHERE` queries and do cross-resource inserts. 
* No preference on how much of the existing interface we keep. Totally fine if we expose a more SQL-like iface.

## Additional context
* PG supports querying and creating indexes on jsonb. Based on this, how should we sequence the work? Do we want to move to a relational schema _before_ we tackle this project or after? The deliverable of being able to do efficient `WHERE` and inserts with transactions is very important so we should be attentive to de-risking that.
* When we do move to a relational schema can we leverage jooq (or equivalent) to give us an objected oriented way of interacting with the database. e.g can jooq generate java classes for each of tables?

**Comment by tuliren** [comment]
> PG supports querying and creating indexes on jsonb. Based on this, how should we sequence the work? Do we want to move to a relational schema before we tackle this project or after? The deliverable of being able to do efficient WHERE and inserts with transactions is very important so we should be attentive to de-risking that.

I think normalizing the tables to a relational schema should be relatively easy to do with the new migration system. We can do that first.

> When we do move to a relational schema can we leverage jooq (or equivalent) to give us an objected oriented way of interacting with the database. e.g can jooq generate java classes for each of tables?

We can leverage jooq even without the generated code.

**Comment by tuliren** [comment]
Design doc:
https://docs.google.com/document/d/1h0AGPrEOpbdlryT03p8H-hhCOLApp2p6g7cG0KpE9wY/edit

**Comment by cgardens** [comment]
@tuliren thanks for doing this spec!

Platform team discussed. Instead of going for this incremental step we want to go straight for normalizing the database. our current schema is causing a lot of headache. closing in favor of: https://github.com/airbytehq/airbyte/issues/7867
