### ISSUE TITLE
🎉 Source Shopify: fetch all Shopify metafields

### ISSUE THREAD

**Issue by gehtalles-de** [airbytehq/airbyte#5493]
I'm trying to replicate all Shopify data to a Postgres database to use that data for internal software tools. We are using a lot of metafields for storing additional information about products and variants. Right now, Airbyte only fetches metafields that have "Shop" as the owner_resource. 

It would be nice if, or in our case even necessary that, Airbyte syncs the metafields of all resources. 

https://shopify.dev/api/admin/rest/reference/metafield

**Comment by sherifnada** [comment]
@gehtalles-de would you be open to submitting a PR to include this functionality in the connector?
