### ISSUE TITLE
New Source: Shopware

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#5494]
## Tell us about the new connector you’d like to have
We use Shopware as our online store system and want to extract the data using API. 

## Describe the context around this new connector
We want to use all entities / endpoints

## Describe the alternative you are considering or using
Currently we can use the MySql Connector, but we want to use the API cause API entities already contain information about foreign table relationships.

## Are you willing to submit a PR?
Yes, we are currently working on such a connector

**Comment by cheyura** [comment]
**Webhook-based? (no/partially/yes)**
Partially, woth custom ApI endpoint https://forum.shopware.com/t/how-to-implement-a-webhook-endpoint-in-shopware/46504


**Available authentication modes (API key/Oauth/other)**
OAuth 2.0.
_Grant Types_
OAuth 2.0 defines various ways that users can authenticate, so-called application grant types. The Admin API supports two grant types or -flows:
> Client Credentials Grant
> Resource Owner Password Grant
> (Refresh Token Grant)
https://shopware.stoplight.io/docs/admin-api/docs/concepts/authentication-authorisation.md


**Creating an account**
Self-service, Free



**How to populate the account with data?**
UI, API

**Available streams for sync**
Entity Reference: https://shopware.stoplight.io/docs/admin-api/docs/resources/entity-reference.md


Integration supports incremental sync?


Other information/blockers

**Comment by cheyura** [comment]
@sherifnada Trial account created. We can create test transactions in both trial (14 days) and usual (free) account. But for usual (free) account integration with PayPal is needed. I have corporate credit card but no PayPal creds for this card
