### ISSUE TITLE
Source Google Ads: investigate CI failure

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5503]
## Current Behavior
https://dnsgjos7lj2fu.cloudfront.net/tests/summary/source-google-ads/
```
self = <jsonschema.validators.create.<locals>.Validator object at 0x7f89507eca10>
args = (***'conversion_window_days': 14, 'credentials': ***'client_id': '303213526762-.apps.googl...cs.conversions, campaign.start_date FROM campaign', 'table_name': 'unhappytable'***, 'customer_id': '4651612872', ...***)
kwargs = ***
error = <ValidationError: "Additional properties are not allowed ('custom_queries' was unexpected)">
```

## Expected Behavior
CI should work without failure.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by yevhenii-ldv** [comment]
@marcosmarxm 
Looks like the `spec` test falls, as it finds an extra field `custom_queries`. Apparently the creds have been updated, but this [PR](https://github.com/airbytehq/airbyte/pull/5302) is not yet in the `master` branch.

**Comment by marcosmarxm** [comment]
@yevhenii-ldv CI is working again https://dnsgjos7lj2fu.cloudfront.net/tests/summary/source-google-ads/ I think https://github.com/airbytehq/airbyte/pull/5509 solves this. I'm closing because #5302 solves another issue.
