### ISSUE TITLE
Stripe Source can't sync Customers on 0.29.9-alpha - Normalization Failed

### ISSUE THREAD

**Issue by erichartono** [airbytehq/airbyte#5515]
## Enviroment
- **Airbyte version**:  0.29.9-alpha
- **Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Stripe 0.1.16
- **Destination Connector and version**: Redshift 0.3.12
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
I had a connection that could sync Stripe Customers data on 0.29.4-alpha version. After upgrading to 0.29.9-alpha, I can't sync Customers data anymore. All other objects are synced successfully. 

I tried to create new EC2 instance and run the same scenario, and got the same result. 

- Database Error in model customers_cards
- column table_alias._airbyte_nested_data does not exist
- Normalization Failed

## Expected Behavior
Strip Customers data should sync without issue

## Logs
[logs-1-0 (1).txt](https://github.com/airbytehq/airbyte/files/7010975/logs-1-0.1.txt)

## Steps to Reproduce
1. Install AirByte 0.29.9-alpha on new EC2 instance
2. Setup connection from Stripe to Redshift with only Customers object to sync
3. Run sync

**Comment by erichartono** [comment]
I experimented to setup clean AirByte on new EC2 instance, running 0.29.4-alpha and normalization 0.1.38 on this scenario. It worked without a glitch. Hope this is helpful. 
 
![image](https://user-images.githubusercontent.com/19322804/129991915-78df00bd-7adc-43e7-a2f8-07fc9eb70822.png)

**Comment by marcosmarxm** [comment]
thanks @erichartono https://github.com/airbytehq/airbyte/pull/5467 is solving this issue.

**Comment by erichartono** [comment]
Thanks @marcosmarxm.
