### ISSUE TITLE
Enable bubbling up the failure reason of a connector in the API/UI more clearly

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5518]
## Tell us about the problem you're trying to solve
Currently the only way for a user to understand why a particular connector/sync has failed is to look at the logs. These are very technical logs which are not easy for a non-engineer to parse. For example, if the reason my API is failing is because my API or refresh token expired, then my best way of finding out is parsing the logs. 

## Describe the solution you’d like
It would be nice to have a convention around how a connector can communicate messages which get bubbled up to the UI in an easily-digestible manner. For example, if a connector "knows" that the failure reason was because their Oauth refresh token expired (something which is very actionable for the user -- they need to reauthenticate) then we want this to be displayed in the UI as the "failure reason" of a sync, something like a clear error message with the right styling etc.. which says the connector failed for that reason. We could even piggyback on this and create all sorts of interesting UX on top of it. For example if a connection fails and there is an actionable solution the user can take (e.g refresh token expiry) they we might even want to send them an email with a call to action.

## Describe the alternative you’ve considered or used
parsing logs

**Comment by cgardens** [comment]
done
