### ISSUE TITLE
Smart Sheet Conector /  Columns Scrambled

### ISSUE THREAD

**Issue by AlexandruManolache1** [airbytehq/airbyte#5520]
## Enviroment
- **Airbyte version**:  0.29.8-alpha
- **OS Version / Instance**: GCP Compute Engine
- **Deployment**:Docker
- **Source Connector and version**: SmartSheet 0.1.5
- **Destination Connector and version**: BigQuery 
- **Severity**:Medium
- **Step where error happened**: sync job

## Current Behavior
columns arrive in BigQuery Json columns scrambled. The values seem to be OK, but the names are wrong(column1, instead of column2, Column3 instead of column 4 ..etc) 

## Expected Behavior
Columns names match the ones in SmartSheet

## Logs
[logs-119-0.txt](https://github.com/airbytehq/airbyte/files/7012542/logs-119-0.txt)

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Create a sync job with smartsheet as source and bigquery as destinations
2.Check if the columns names are correctly added to the values
3.

**Comment by marcosmarxm** [comment]
thanks for reporting this @AlexandruManolache1 I added this to the connector roadmap. Do you want to contribute and work solving this issue?

Probably the solution resides in this block:https://github.com/airbytehq/airbyte/blob/1954284f6f45a4629fdaeaa9cf4f48fdd0619656/airbyte-integrations/connectors/source-smartsheets/source_smartsheets/source.py#L137-L140

**Comment by sherifnada** [comment]
@AlexandruManolache1 would you be able to provide a copy of the sheet so we can reproduce?

**Comment by AlexandruManolache1** [comment]
hi @sherifnada , let me try pls to save a copy and mask it, it has some internal company data

**Comment by yevhenii-ldv** [comment]
hi @AlexandruManolache1 
This copy from you was very helpful to us, as we tried many different SmartSheets and failed to reproduce the bug that you described. If you can provide us with a copy (of course, without any secret data, we are only interested in the format of the Smartsheet itself, in order to understand what the problem may be) - it would be great.

Thanks in advance!

**Comment by AlexandruManolache1** [comment]
hi @yevhenii-ldv , @sherifnada  i created a dummy file, same format with mine. I tested and has the same behaviour. 
What is your email so that i can share it with you?

**Comment by AlexandruManolache1** [comment]
i shared it with Sherif, let me know your email also pls. thx!!!

**Comment by yevhenii-ldv** [comment]
Hi @AlexandruManolache1!
yep, of course, you can send to this email: `y.kurochkin@zazmic.com`

**Comment by AlexandruManolache1** [comment]
done

**Comment by yevhenii-ldv** [comment]
@sherifnada It looks like the error is not in Connector, but in Destination.
I tried to run the commands locally: `python main.py read` and everything returned with correct data and column names.
However, having started UI and tried to use the same credentials to obtain data from Smartsheet and save them to the CSV, the column names did change.

**Comment by sherifnada** [comment]
thanks @yevhenii-ldv - will follow up

**Comment by tehnorm** [comment]
Also seeing this with a postgres destination.

**Comment by tehnorm** [comment]
Wondering if this block might have something to do with it? https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-smartsheets/source_smartsheets/source.py#L27

Smart Sheet has a few additional column types that often need some special handling when pulling from their API. https://help.smartsheet.com/learning-track/level-1-get-started/columns
