### ISSUE TITLE
Password logged as plain text

### ISSUE THREAD

**Issue by shmf** [airbytehq/airbyte#5522]
## Enviroment
- **Airbyte version**:  0.29.7-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: High
- **Step where error happened**: Deploy

## Current Behavior
Passwords visible in the logs
![image](https://user-images.githubusercontent.com/84322199/130033375-501c3a97-4b02-4379-8350-195500ee214c.png)

## Expected Behavior
Passwords should not be visible

**Comment by jrhizor** [comment]
@tuliren can you take a look at this?

**Comment by tuliren** [comment]
Got. Pushing a fix now.
