### ISSUE TITLE
source-acceptance test: 'NoneType' object has no attribute 'config_key'

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#5533]
## Enviroment
- **Airbyte version**:  no matter
- **OS Version / Instance**: macOS, Ubuntu 20.04
- **Deployment**: Docker, locally
- **Source Connector and version**: no matter
- **Destination Connector and version**: no matter
- **Severity**: Medium
- **Step where error happened**: Tests / SAT

## Current Behavior
When runs the `python -m pytest integration_tests -p integration_tests.acceptance` within `.venv` of particular connector it gives the next error:
```
INTERNALERROR>     test_configs = getattr(config.tests, items[0].cls.config_key())
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'config_key'
```
BUT:
when runs the same test suit but using docker command:
```
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp:/tmp \
    -v $(pwd):/test_input \
    airbyte/source-acceptance-test \
    --acceptance-test-config /test_input
```
It just pass through without any issue.

## NOTE:
The issue is not seems to be for newly created connectors using template connector generator, but for existing ones.

## Expected Behavior
`python -m pytest integration_tests -p integration_tests.acceptance` passes for all python source connectors, which uses `source-acceptance-test`

## Logs

<details>
<summary>LOG</summary> 

   [LOG LINK](https://github.com/airbytehq/airbyte/files/7016278/SAT.Error.txt)

</details>

## Steps to Reproduce
1. Clone Master Repo or create the branch
2. Choose the source connector, ex: `source-stripe`
3. Following connector's `ReadMe.md` execute: 
```
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```
4. Build the connector with Docker: (source-stripe is just an example, but it has the same issue)
`./gradlew :airbyte-integrations:connectors:source-stripe:build` 
or
`docker build . -t airbyte/source-stripe:dev`
5. Get the test credentials from LastPass and create the config.json file for test execution.
6. Run `python -m pytest integration_tests -p integration_tests.acceptance` .... it should fail with the error above.
7. `IF STEP 6 == FAILED` run the same test using docker command:
```
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp:/tmp \
    -v $(pwd):/test_input \
    airbyte/source-acceptance-test \
    --acceptance-test-config /test_input
```
It should pass fine.

## Are you willing to submit a PR?
I hope not, because this is not even the issue but some mistake of the user and simply something is missed.

**Comment by avida** [comment]
You don't need  to specify any module path for pytest  when running with source_acceptance_test
```bash
python -m pytest -p source_acceptance_test.plugin
```
Tried this on couple of connectors (facebook-marketing, braintree, amazon-ads) and it works fine for me. @bazarnov please check it on your side.

**Comment by bazarnov** [comment]
Thanks, I will.

**Comment by bazarnov** [comment]
```
python -m pytest -p source_acceptance_test.plugin
``` 
Command works as expected. No mentioned issues came out. 

@sherifnada I think this is the issue:
We have the following line inside of the any connector's `ReadMe.md` template?
```
To run your integration tests with acceptance tests, from the connector root, run
 
" python3 -m pytest integration_tests -p integration_tests.acceptance "

```
Which is not always working as expected.
I think this issue could be close. Thanks.
