### ISSUE TITLE
Ability to mention tolerations for scheduled pods

### ISSUE THREAD

**Issue by prasrvenkat** [airbytehq/airbyte#5536]
## Tell us about the problem you're trying to solve
When deploying to GKE in an existing cluster,  we usually like to mention affinity for certain loads to be run only one certain node-pools/nodes and nowhere else, no other loads can run in those node pools as well. This is achieved by using taints+tolerations. This makes sure certain workloads (with tolerations) run only on certain node-pools (with taints)

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

This works for deployment yamls already defined, with a simple kustomization on top. But does not work for scheduled pods since they are created programatically.

## Describe the solution you’d like
Add optional set of environment variables to mention tolerations and use it when building pods using `io.fabric8.kubernetes.api.model.PodBuilder`

## Describe the alternative you’ve considered or used
Alternate is to either run Airbyte workloads onto same nodes as our workloads OR
Run in separate cluster all together. 
We would like to avoid doing either if possible.

## Additional context
![image](https://user-images.githubusercontent.com/47996246/130104222-7daa9f1c-8f64-45f4-88d4-4a3ab2401697.png)
![image](https://user-images.githubusercontent.com/47996246/130104805-c051ca58-70a1-4eda-8a10-71d63f9f3a1b.png)

## Are you willing to submit a PR?
Yes! Happy to!

**Comment by jrhizor** [comment]
I'm definitely all for adding configurability for launched pods.

Maybe it would be easier long term to support adding a template for the spun up job that could be loaded from a `ConfigMap`? Then a user could customize any field by specifying a YAML override?

**Comment by davinchia** [comment]
@jrhizor that makes sense.

I do want to limit the configurable fields to metadata/where the pods are scheduled on. Retaining control over where the pods's lifecycle and data access is important since that's pretty crucial to jobs start/stop.

The template can include:
1) Taints and tolerations
2) Labels
3) Namespace

For the time being, I'm inclined to add taints and tolerations as field for now.

**Comment by jrhizor** [comment]
Sounds reasonable @davinchia
