### ISSUE TITLE
Support DBT environment variables via run command

### ISSUE THREAD

**Issue by manavkohli** [airbytehq/airbyte#5557]
## Tell us about the problem you're trying to solve
We run custom transformations on our data. However, we don't want to expose our database credentials in VCS. Each one of our connections has a separate set of database credentials. DBT profiles can only read runtime arguments from the `env_var`functions, which precludes us from being able to pass them through the `variable` argument.

## Describe the solution you’d like
We would like to pass the credentials via environment variables, i.e.
```
DBT_NAME=test DBT_HOST=test DBT_USER=test DBT_PASSWORD=test dbt run --models tag:test 
```

## Describe the alternative you’ve considered or used
I have not found an alternative solution to this for storing environment variables securely.

## Additional context
It feels like there should be some solution here that someone else has come up with? 

## Are you willing to submit a PR?

Sure

**Comment by marcosmarxm** [comment]
@manavkohli it's possible to you use the custom run describe in this docs? https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-airbyte#using-a-custom-run-with-variables

**Comment by manavkohli** [comment]
@marcosmarxm unfortunately this will not work - the custom run variables correspond to a DBT `variable`, which *cannot* be read in a `profile`. The `profile` only has access to environment variables via the `env_var` function from what I've gathered

**Comment by cgardens** [comment]
@manavkohli  Would it be possible to override the entrypoint on the docker container that you are using so that the entrypoint handles injecting the environment values for you?

**Comment by manavkohli** [comment]
@cgardens unfortunately not, each destination has separate credentials and uses a different database within our postgres instance. FWIW I think this actually would benefit a lot of people, using `env_var` in the profiles seems to be the suggested approach from DBT to avoid checking in sensitive fields

**Comment by cgardens** [comment]
Got it! Makes sense. Thank you for the clarification.

**Comment by cgardens** [comment]
Closing. We're not going to get to this one anytime soon.
