### ISSUE TITLE
The data moved has duplicates

### ISSUE THREAD

**Issue by foinduati** [airbytehq/airbyte#5565]
I have recently moved data from freshdesk to our snowflake warehouse. However the data there is too much.  We have 90k tickets but the data on airbyte shows 500k. We noticed that the data was duplicated at least 30 times. Could you please tell use why this is happening.

**Comment by sherifnada** [comment]
@foinduati hello! Airbyte provides an at-least-once delivery guarantee. Duplicates can happen if the sync is run multiple times or if the sync mode. 

Can you provide more info about your sync mode/number of syncs run? 

Some helpful resources: https://docs.airbyte.io/understanding-airbyte/connections
