### ISSUE TITLE
Source Iterable: add new endpoints 

### ISSUE THREAD

**Issue by emilyhawkins-drizly** [airbytehq/airbyte#5574]
## Tell us about the problem you're trying to solve
We are considering switching from bringing in iterable data from fivetran to airbyte. We need some additional iterable endpoints available for that to happen. 
- [campaign history](https://api.iterable.com/api/docs#campaigns_campaigns) (i think this might be the same as the current campaigns endpoint in airbyte but wanted to add it here just to make sure)
- [campaign metrics](https://api.iterable.com/api/docs#campaigns_metrics)
- [events](https://api.iterable.com/api/docs#events_track)

These exist in fivetran (https://fivetran.com/docs/applications/iterable)

## Describe the solution you’d like
Add these additional endpoints to the iterable connector 

## Describe the alternative you’ve considered or used
staying with fivetran 

## Are you willing to submit a PR?
no

**Comment by marcosmarxm** [comment]
thanks for requesting this @emilyhawkins-drizly I added this to the connector roadmap backlog.

**Comment by gaart** [comment]
@emilyhawkins-drizly 

We just merged this feature into master and released a new version of the connector. 

Upgrade your connector to version 0.1.8 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
