### ISSUE TITLE
Snowflake Source/Destination doesn't respect DATE data type

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#5577]
## Environment
* **Airbyte version**:  0.29.11-alpha
* **OS Version / Instance**: GCP COS
* **Deployment**: Docker
* **Source Connector and version**: Snowflake 0.1.1
* **Destination Connector and version**: Snowflake 0.3.12
* **Severity**: Medium
* **Step where error happened**: Schema discovery

## Current Behavior
Snowflake date types are not respected when setting up schemas

### Schema in Snowflake
![image](https://user-images.githubusercontent.com/3239656/130493920-faa8f1d2-605e-4a74-93fe-e365dceae82d.png)

### Schema in Airbyte
![image](https://user-images.githubusercontent.com/3239656/130493950-2eca1474-f812-452e-993b-37d4d1b796fc.png)

## Expected Behavior
TRANSACTION_DATE should be a date type

## Steps to Reproduce
1. Create table in Snowflake with a Date column type
1. Setup a source and destination snowflake to snowflake

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126680022927) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
@subodh1810 the implementation of date types in normalization modules works for database sources or only when you have specificy date type in schema?

**Comment by sherifnada** [comment]
@philippeboyd thanks for the report! We're gradually rolling out proper date support across our sources. We'll keep you updated here when we get to this one.

**Comment by subodh1810** [comment]
@marcosmarxm we need to specify the `date-time` format in the JSON schema of the stream, then only normalization would pick it up
> @subodh1810 the implementation of date types in normalization modules works for database sources or only when you have specificy date type in schema?

**Comment by yurii-bidiuk** [comment]
Currently, the Snowflake source provides the DATE type as a string because all JDBC sources provide only primitive JSON types. To write fields as a DATE type we need support date-time format in JsonSchema for Snowflake source. This support would be possible after the implementation of #7777. So I'm moving this ticket on hold and will back again when #7777 is ready.

**Comment by yurii-bidiuk** [comment]
In scope of this ticket we need to:
- in `SnowflakeSourceOperations` override `getJsonType()` and set `JsonSchemaType` date types for  corresponding `jdbcType`
- modify acceptance tests
- do the manual testing with sync to ensure that the output source JSON schema contains the right `format` for date fields
- when source schema is ready, verify if normalization for destination-snowflake is able to handle JSON schema with date-time `format` and create a follow-up ticket if required
