### ISSUE TITLE
track api endpoint latency in cloud

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5601]
It'd be great to understand the performance around API endpoints for cloud. It'll be important to ensure long-term that operations do not exhibit rare worst case behavior if our optimizations continue to maintain low response times.

In the case of endpoints that we haven't optimized yet (like endpoints that depend on listing configs) it would be good to know how behavior is changing over time.

**Comment by cgardens** [comment]
@davinchia is this something that are in the initial metrics that GL are tracking?

**Comment by davinchia** [comment]
Not explicitly. This is a good point. I'll make sure this is done before Public.

**Comment by davinchia** [comment]
This is exposed via Google Endpoints today.
