### ISSUE TITLE
Changing to external postgres db fails

### ISSUE THREAD

**Issue by apostoltego** [airbytehq/airbyte#5602]
## Enviroment
- **Airbyte version**:  0.29.12
- **OS Version / Instance**: Linux AMI / AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: n/a
- **Destination Connector and version**: n/a
- **Severity**: High
- **Step where error happened**: Deploy

## Current Behavior
Attempting to change from internal db to an external Postgres host causes several issues:

1. If user config already exists in the server then the application fails to startup.
2. After resolving with the steps outlined further below there were errors preventing the old config from being imported due to the file being too large. This required that attempts to be deleted in order to get the config back.
3. State was reset on multiple connectors even though the JOBS.yaml was kept in place

No 3. is quite problematic for certain connectors that allow only a certain number of days backfill (e.g. freshdesk allows just 30days back) and as a result this can cause downstream problems. 

## Expected Behavior
*Tell us what should happen.*

- Application should start and use new db
- Config should be importable in full
- State should be retained

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

airbyte-scheduler   | Caused by: io.airbyte.validation.json.JsonValidationException: json schema validation failed.
airbyte-scheduler   | errors: $.workspaceId: is missing but it is required

**For 2nd problem**
airbyte-webapp      | 2021/08/24 22:08:05 [error] 29#29: *56 client intended to send too large body: 243296768 bytes, client: 172.22.0.1, server: localhost, request: "POST /api/v1/deployment/import HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/settings/configuration"
</details>

## Steps to Reproduce
1. Deploy airbyte with default config on an ec2 instance with docker
2. Create some data (couple of syncs)
3. Bring server down with docker-compose down
4. Change .env to custom postgres database
5. docker-compose up

## Are you willing to submit a PR?

I've resolved with the following steps but I'm not sure if these address the root cause:

1. docker-compose down
2. docker-compose down --volumes
3. Removed db service from docker-compose.yaml
4. Deleted airbyte db from external server and created fresh.
5. Modified configuration files in order to reduce size in mb
6. Reset data sources and started connectors from scratch
 
I suspect there’s two separate issues that might be worth highlighting in the docs:

1. Existing config will causes issues with the server and shouldn’t exist in the instance
2. Ensure the db is empty (?) - this might not be necessary for people starting fresh and could be isolated just to my particular case. During the first attempt of setting the DB up the tables were created and 

Remove this with your answer.

**Comment by marcosmarxm** [comment]
@tuliren fyi, do you have idea if it's possible to change from local to external database?

**Comment by tuliren** [comment]
> @tuliren fyi, do you have idea if it's possible to change from local to external database?

Yes, changing from local to external database should be automatic. The steps listed in this issue are correct:

> Steps to Reproduce
> 1. Deploy airbyte with default config on an ec2 instance with docker
> 2. Create some data (couple of syncs)
> 3. Bring server down with docker-compose down
> 4. Change .env to custom postgres database
> 5. docker-compose up

The prerequisites are: 1) the provided user should have permission to create tables under the `public` schema and the specified database; 2) the database should not have an existing table whose name clashes with any of the airbyte tables (e.g. `airbyte_configs`) under the `public` schema.

@apostoltego, would you mind sharing the full server log?

**Comment by tuliren** [comment]
> I suspect there’s two separate issues that might be worth highlighting in the docs:
> 1. Existing config will causes issues with the server and shouldn’t exist in the instance

Hmm, this is not true. The configs should be ported automatically. The detailed server log may provide more insights.

> 2. Ensure the db is empty (?) - this might not be necessary for people starting fresh and could be isolated just to my particular case. During the first attempt of setting the DB up the tables were created and

Oh, actually this is probably the root cause for the first attempt. The server will check if any of the tables already exist. If the answer is yes, the assumption is that the configs have been ported to the database. This is kind of mentioned in the documentation: https://docs.airbyte.io/operator-guides/configuring-airbyte-db#initializing-the-database

> If you provide an empty database to Airbyte and start Airbyte up for the first time, the server will automatically create the relevant tables in your database.

I will update the doc to emphasize this. Thank you for pointing it out.

**Comment by apostoltego** [comment]
@tuliren there's no server logs unfortunately for me to provide due to the volumes being removed and the almost  "fresh" start whilst trying to implement this. 

All-in-all reflecting back on this, the issue first arose on 0.29.9. During that attempt tables had been created on the database. After that, even though the original issue was fixed it still required an empty db which led to the majority of the issues. I believe having known that the migration from local files to the external db happens on it's own this would have been avoided.

Docs changes should cover it.

**Comment by tuliren** [comment]
Got it. Thank you for confirming that the doc change covers this issue.
