### ISSUE TITLE
TikTok Ads Sandbox: populate all possible streams

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#5612]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cheyura** [comment]
@sherifnada For sandbox such streams as campaigns, ad groups and apps are populated. For ads and audiences we are waring for prod account payamnet unblocking form tiktok

**Comment by midavadim** [comment]
We have good working account for prod and sandbox tiktok accounts
