### ISSUE TITLE
DAT: test array output types

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5625]
## Tell us about the problem you're trying to solve
#5563 happened because a source emitted an array in its catalog without setting the `items` property. This is technically valid JSON schema. A destination should be able to handle such arrays, probably by casting whatever is in that field to string or bytes or something. 

## Describe the solution you’d like
I would like DAT to test that arrays are written correctly to a destination using any of the permutations it has: 

`{type: array}`
`{type:array, items: {type: object}}`
`{type:array, items: {type: string}}`
etc....

Add these test cases on a branch. Once these test cases are added, some destinations will probably start failing. Create tickets for them and add them to the sprint then fix them on separate PRs (or the same PR if it's small enough).

Once all the tickets are addressed, merge the test cases and fixes into master. 

See the full array specification [here](https://json-schema.org/understanding-json-schema/reference/array.html)

**Comment by DoNotPanicUA** [comment]
Done by epic #9441
