### ISSUE TITLE
DAT: comprehensive type testing

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5626]
## Tell us about the problem you're trying to solve
We keep running into issues like #5625 where a connector breaks due to "but-what-about-this-data-type" style of errors. We should instead systematically go through all the JSON schema types we support and their formats and make sure they are tested as part of DAT. We should break down this effort as needed. 

For the record, we don't support any `format`s on types except `date-time` and `date` on strings. 

## Describe the solution you’d like
DAT should test all JSON schema types.

**Comment by DoNotPanicUA** [comment]
Done by epic #9441
