### ISSUE TITLE
New source: Taboola

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5659]
## Tell us about the new connector you’d like to have

* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
**Integration Vetting**

Webhook-based? (no/partially/yes) if partially, mention which endpoints are webhook-based 
**_no_**

Available authentication modes (API key/Oauth/other) 
**_oAuth2_** https://developers.taboola.com/backstage-api/reference#authentication-basics

Connecting to the data source what kind of API is it? (SOAP/GraphQL/REST/other) 
**_REST API_** https://developers.taboola.com/backstage-api/reference#backstage-api

is there an SDK available? Can we connect with HTTP requests directly? 
**_SDK_** https://developers.taboola.com/backstage-api/reference#java-client-sdk

If this is a database/datalake/pubsub source, does it have a JDBC driver or Java SDK? 
**_Java Backstage SDK_** https://github.com/taboola/backstage-api-java-client

Creating an account Select one of the below options self-service free account available?
**_no, price starts from $10 a day._**
**_Sent letter about sandbox to_** support@taboola.com

**Comment by karinakuz** [comment]
On the Taboola request have sent additional information (Oct 18) but no answer with solution or partner program suggestion received. Sent letter to receive any update (Dec 21).
