### ISSUE TITLE
figure out which version to display in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5673]
From Artem:
> This is how we currently handle Airbyte_version. Is it actually correct? We always pick version based on the version that is set docker-compose, however it doesn’t guarantee that client is of the same version. Because if user ran app, then somehow switched version ( made an upgrade ) and his webapp was not rebuilt somehow - he may have newer version displayed on webapp, however the webapp version will be still old. Do you see what I mean?

It isn't clear if we should display the build version, the env version, pull it from the API, or have some combination.

Not super important right now but might cause some confusion.

**Comment by timroes** [comment]
Closing this for now, due to ongoing changes in our release process, and will reconsider this as part of that.
