### ISSUE TITLE
Setup linting rules to verify javadocs on java classes

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5676]
## Tell us about the problem you're trying to solve
The kind of issue described in #5670 shouldn't really happen with some reasonable linting. Each java class should probably have a javadoc explaining its purpose.

**Comment by marcosmarxm** [comment]
To execute this we need a dependency task adding docs for all classes. At the moment this is not possible to implement.

**Comment by evantahler** [comment]
Closing this issue.
* We've got linting now with PMD
* We've got far better testing
* We've got Micronaut and better code organization
