### ISSUE TITLE
Improve persistence seeding lifecycle

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#568]
## Tell us about the problem you're trying to solve
When run for the first time, Airbyte seeds the persistence layer with a list of the supported source & destination definitions. Currently there are two issues with that process: 

1. primary keys (UUIDs) are hardcoded into seed records. This makes for a bad DX when adding a new integration since the developer needs to manually generate and hardcode a UUID. Furthermore, this is unreliable since one could accidentally duplicate UUIDs between integrations. 
1. The seeding step is not re-run more than once per Airbyte installation. This means that if the seed data changed between releases, a running integration that gets upgraded to a new release will not receive the new seed data (e.g: new "out-of-the-box" connector definitions).

## Describe the solution you’d like
1. As a developer contributing a connector definition to airbyte, I would like not to have to manually generate a hardcoded UUID when adding the definition. 
1. As a user of a running airbyte instance, I would like to receive any new standard/seed data included in new Airbyte releases. Ideally this would run as a migration upon updating my airbyte version.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368233869631) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
done
