### ISSUE TITLE
Support import of old archives in configs persistence

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#5682]
## Tell us about the problem you're trying to solve
- After moving to database-based config persistence, we may no longer import archives with an old version.
- In the file-based world, everything is just a file. So no matter how the schema changes, we can read and write the files.
- In the database world, the database can only consume data with a certain schema. So old archives may not work on the latest version of Airbyte.
- We will soon run into this problem when we make any structure change to the `airbyte_configs` table. For example, if we break this table into multiple ones, one per config type, import will immediately break for all old configs.

@cgardens, FYI.

## Describe the solution you’d like
- Import archives older than v0.29.x and migrate them to v0.29.x using the file-based migration system.
- Implement an importer that can understand v0.29.x config schema, and load them into a side database.
  - We need a separate importer whenever there is schema change in the airbyte_configs table.
- Migrate the configs from v0.29.x to the latest version using the Flyway migration system.
- Import the configs from the side database to the main database.

## Describe the alternative you’ve considered or used
- Users can do the following to manually upgrade an old config archive:
  - Launch an old Airbyte server that matches their config version.
  - Import old configs into the server.
  - Upgrade the server to the latest version. The configs will be automatically migrated to the latest version.
  - Export the configs.

## Additional context
N/A

## Are you willing to submit a PR?
Yes.

**Comment by cgardens** [comment]
i think we agreed not to support this.
