### ISSUE TITLE
Source Hubspot: add date-type to fields in all schemas

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5688]
## Tell us about the problem you're trying to solve

PR #5685 removed all date-time format from streams.
PR #5661 adds tests in sources to validate the json format and will help adding this to schemas.

## Describe the solution you’d like
All fields in streams should be format correctly in normalization.

## Describe the alternative you’ve considered or used
None

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by bazarnov** [comment]
@marcosmarxm you forgot to to add the correct PR in changelog of Hubspot connector during this update. https://docs.airbyte.io/integrations/sources/hubspot#overview 
It says: 0.1.11 = PR of 5463, and must be yours.
