### ISSUE TITLE
Source - HTTP API Request - Iterate over multiple URL parameters.

### ISSUE THREAD

**Issue by BenHadman** [airbytehq/airbyte#5709]
A HTTP API source connector which can iterate over multiple url parameters and send to a one destination.

Commonly APIs provide data on a one-record-per-request basis and not in one bulk response.
It would be beneficial to have a source which can iterate over multiple parameters and send to a destination.

https://example.com/?parameter={paramName}

| paramName  |
|----------------|
|  goblins |
|  tigers |
| elephants  |
|  giraffes |

In order to declare the parameters perhaps a csv file could be uploaded or a textarea box provided to paste the parameters into the UI. An even more advanced option would be to read a csv file on a remote source eg Google Cloud Storage and take a particular columns values as the parameters.

I think it would be best to have this connector agnostic of a particular service or endpoint so that it can be used as a general connector to multiple APIs.

**Comment by marcosmarxm** [comment]
The HTTP Source is deprecated @BenHadman you can easily achieve this using the CDK with a custom connector.
https://docs.airbyte.io/connector-development/tutorials/cdk-tutorial-python-http

I'm closing this but let me know if you need any assistance developing the custom connector.
