### ISSUE TITLE
Woo Commerce not displayed as Sources

### ISSUE THREAD

**Issue by Mansi-Chauhan27** [airbytehq/airbyte#5727]
I have just Started Exploring Airbyte, Wanted to test Woo Commerce connector, but it is not displayed in Source List but displayed as source in airbyte's documentation.

I have done local deployment for airbyte following the documentaion given.

Can You Please help?

**Comment by marcosmarxm** [comment]
@Mansi-Chauhan27 Woo-Commerce is a WIP https://github.com/airbytehq/airbyte/pull/5121 after this is merged you're going to be able to use it.
