### ISSUE TITLE
Redshift destination : remove extra serialization

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#5741]
This is a problem, we are not going to do `Jsons.serialize` twice for Redshift. First in the `isValidData` method and then here

_Originally posted by @subodh1810 in https://github.com/airbytehq/airbyte/pull/5336#discussion_r696009986_

**Comment by haoranyu** [comment]
It seems to be only one Jsons.serialize call in isValidData now. Is this issue still valid?

**Comment by andriikorotkov** [comment]
This task is no longer relevant. These changes were added on 15.09.21 - in this pull request - https://github.com/airbytehq/airbyte/pull/5998
