### ISSUE TITLE
S3 source should work for non-AWS S3 storages

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#5751]
Currently S3 source is tied to AWS S3 (with url strings etc.). Should be relatively straightforward to extend this to support other storage systems following S3 protocol.

**Comment by sherifnada** [comment]
@Phlair what's an example of this? Minio? Any examples you add would help make this a reality :D

**Comment by Phlair** [comment]
Some examples:
- [MinIO](https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html)
- [Ceph](https://docs.ceph.com/en/mimic/radosgw/s3/python/)
- [LeoFS](https://leo-project.net/leofs/docs/admin/protocols/s3/)
- [Wasabi](https://wasabi-support.zendesk.com/hc/en-us/articles/115002579891-How-do-I-use-AWS-SDK-for-Python-boto3-with-Wasabi-)

The ideal soultion would be provider agnostic, such that the code uses boto3 to handle s3 compatible storage systems in a single generic approach, rather than cases for each S3 provider and setting in spec. The generic approach would then just use a user-provided base url along with access and secret keys to hit the relevant storage (AWS could be default for base url perhaps)
