### ISSUE TITLE
ARM CPU Support for Docker

### ISSUE THREAD

**Issue by wiamsuri** [airbytehq/airbyte#5752]
## Tell us about the problem you're trying to solve
I am interested in running Airbyte docker container on ARM CPU architecture

## Describe the solution you’d like
Add ARMv8 architecture for building docker image

## Are you willing to submit a PR?
From quickly glancing at the github workflows, I see that it triggers some EC2 instance to run image building, so I have no idea where is the scripts for building docker images.

**Comment by marcosmarxm** [comment]
@wiamsuri each connector and Airbyte component has it's individual Dockerfile. What environment are you trying to use with ARM?

**Comment by wiamsuri** [comment]
I'm interested in running it on a Raspberry Pi, which uses 64bit ARMv8
