### ISSUE TITLE
Source Google Search Console: add a couple demo sites to the test account

### ISSUE THREAD

**Issue by gaart** [airbytehq/airbyte#5759]
the connector supports pulling data for multiple websites at a time. However, this is currently not tested, because we only have one website that we use for testing, airbyte.com. So we want to add google search console to another website/domain that we control. This ticket encompasses: 

1. Getting access to one additional domain for which we can pull google search console metrics
2. Use that new site in integration/acceptance testing for the connector

It may be more pragmatic just to mock this with unit tests and trust that a single website is sufficient for the integration test case.

**Comment by misteryeo** [comment]
Assignee should look to take the suggested pragmatic approach and implement unit tests for this issue instead: 

> It may be more pragmatic just to mock this with unit tests and trust that a single website is sufficient for the integration test case.
