### ISSUE TITLE
Allow for lookback window on incremental load  - Stripe/All Sources

### ISSUE THREAD

**Issue by JCWahoo** [airbytehq/airbyte#5765]
## Tell us about the problem you're trying to solve
I'm attempting to replace my existing Stitch(Singer) Stripe integration w/ Airbyte. I've run into a few scenarios where updates are arriving late to existing objects (charges, invoices, subscriptions). Due to this, I must use a full refresh rather than incremental load for those streams

## Describe the solution you’d like
In reviewing the Singer spec, their connection is using a 30 day lookback window for incremental load. I'd like the ability to set this lookback window as part of any incremental source, but specifically Stripe for this use case. Rather than requesting records where >= last_cursor, I'd like to retrieve where >= last_cursor - {my prescribed interval in days})

## Describe the alternative you’ve considered or used
I'm currently using Stitch :-) 

## Additional context
By either adding this default lookback or allowing the user to choose, we're meeting/exceeding the capabilities of our competitors

## Are you willing to submit a PR?
This is one where I feel like it sounds easy enough to add the lookback, though I suspect this cursor implementation has further ramifications depending on source

## Acceptance Criteria
1. Add an optional integer input `lookback_window_days` to the stripe connector which causes the connector . This option should default to 0. The option should also be annotated with `advanced=true` for when there is a separate advanced options section in the UI.

**Comment by sherifnada** [comment]
thanks for the suggestion @JCWahoo ! Will make this available soon. I've updated the description to make it clearer what airbyte should do when supporting this.

**Comment by sherifnada** [comment]
@eliziario moving this out of the sprint for now

**Comment by JCWahoo** [comment]
Do we know when it might be worked on?

**Comment by avida** [comment]
@JCWahoo Added lookback_window_days parameter please update connector to  0.1.20 version

**Comment by JCWahoo** [comment]
@Dmytro It doesnt appear I can save this setting, both save and retest are
not available

[image: image.png]
