### ISSUE TITLE
[EPIC] Oauth Support in Platform

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#5769]
# MVP 

#### UI
- [x] #5644
- [x] #5646 
- [x] #5645 
- [x] #5770
- [x] #6027
- [x] #5651 

#### Server
- [x] #5643 
- [x] #5641 
- [x] #5638 
- [x] #5637 
- [x] #5640 
- [x] #5639 
- [x] #5647 
- [ ] #5895
- [x] #5771
- [x] #5772
- [x] #5773
- [x] #5774
- [x] #5920
- [x] #5919
- [x] #6026

#### Cloud Server
- [x] #5775
- [x] #6024
- [x] #6102
- [x] #6094 
- [x] #6103
- [x] #6104

#### Protocol/Connectors
- [x] #5632 
- [x] #5633
- [x] #5634

**After all cloud server work is done**
- [x] #6112
- [x] #6109
- [x] #6110
- [ ] #7037
- [x] #6111
- [x] Apply for complete public access for salesforce

# Ideally-MVP-but-not-strictly-necessary
- [x] #5636 
- [x] #5635 
- [x] #4982
- [ ] https://github.com/airbytehq/airbyte/issues/6019
- [ ] #6083 

# Post-MVP
- [x] #5648 
- [ ] #5141

**Comment by ChristopheDuong** [comment]
Should we also add this ticket? https://github.com/airbytehq/airbyte/issues/6083
