### ISSUE TITLE
Revert to using named volumes

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#578]
## Tell us about the problem you're trying to solve
`docker-compose` pushed an update that has made local volumes unusable on mac (issue: https://github.com/docker/compose/issues/7867). That has forced us to remove the use of local named volumes and instead mount raw directories. This precipcated a bunch of hacks (PR: https://github.com/airbytehq/airbyte/pull/576)

## Describe the solution you’d like
* Once `docker-compose` has addressed this [issue](https://github.com/docker/compose/issues/7867), we should bring back local named volumes. 
* We should also get rid of the dependency between `*_DOCKER_MOUNT` and `*_ROOT`. Currently if a directory is being mounted, these two env variables need to be set to be the same absolute path.

**Comment by cgardens** [comment]
we have gone ahead and went full to using volumes.

**Comment by tom-haines** [comment]
@cgardens  re docs/info, issue is still marked as a TODO see [.env.dev in v0.50.30](https://github.com/airbytehq/airbyte-platform/blob/v0.50.30/.env.dev#L15) (just fyi)

**Comment by joceliovieira** [comment]
any updates?
