### ISSUE TITLE
New Source: SearchMetrics

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5795]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sherifnada** [comment]
@irynakruk let's not sign up for an account on this one yet, we will get one from a partner

**Comment by igrankova** [comment]
**Webhook-based? (no/partially/yes)** 
no

**Available authentication modes (API key/Oauth/other)** 
API key:
https://developer.searchmetrics.com/docs/apiv4-documentation/docs/Getting-Started.md#getting-started

**Has Sandbox environment?** 
No
partner account (Sherif: we will get an account from a partner - https://github.com/airbytehq/airbyte/issues/5795#issuecomment-914431069)

**How to populate the account with data** 
API calls:
https://developer.searchmetrics.com/docs/apiv4-documentation/docs/Overview.md

**Available streams for sync** 
RESEARCH
Organic
Keywords
Paid
Links
Universal
Content

PROJECT
Organic
Keywords

ADMIN
Status
Search Engines
Countries

**Integration supports incremental sync?** 
No

**Other information/blockers** 
prod demo:
https://app.searchmetrics.com

**Comment by igrankova** [comment]
@sherifnada Vetting is completed, ready for implementation (I researched all info I could find without the account. We need to get the partner's account for implementation).
