### ISSUE TITLE
Zendesk Support Upgrade - Ticket Metrics Events

### ISSUE THREAD

**Issue by Howard3** [airbytehq/airbyte#5802]
## Tell us about the new connector you’d like to have
* This is an upgrade to the existing Zendesk Support Source 
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? **No**

## Describe the context around this new connector
* Which team in your company wants this integration, what for? Business intelligence
* How often do you want to run syncs? 24 hours
* If this is an API source connector, which entities/endpoints do you need supported? Currently the Zendesk Support connector supports **sla_policies**, **ticket_metrics**, and **tickets** however, these are not able to be referenced to one another without the use of the source endpoint **[Ticket Metric Events](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_metric_events/)**, this endpoints data acts as the "glue" between a lot of these data sources.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?
I can try!

**Comment by sherifnada** [comment]
@Howard3 let us know if you need a hand with creating a PR!

**Comment by jonoirwinrsa** [comment]
@sherifnada @Howard3 PR that addresses this issue here: https://github.com/airbytehq/airbyte/pull/8168

**Comment by misteryeo** [comment]
Closing as this PR was merged: https://github.com/airbytehq/airbyte/pull/8316
