### ISSUE TITLE
Improve CI pipeline

### ISSUE THREAD

**Issue by gaart** [airbytehq/airbyte#5807]
## Tell us about the problem you're trying to solve
Some steps of pipeline lead to the failed build in case it's not necessary. E.g. step
```
ensure-images-exist:
name: "Ensure all required Docker images exist on Dockerhub"
```
is triggered even before the connector is published and there should not be any image on Dockerhub.
As a result we see "Some checks were not successful"

## Describe the solution you’d like
Change the pipeline to do the only necessary steps and do not fail when there's no actual errors

**Comment by jrhizor** [comment]
How do we ensure that images are being published properly then?
