### ISSUE TITLE
Integration Testing for SSH using a docker container

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#5811]
## Tell us about the problem you're trying to solve
Improve the process of acceptance testing by allowing doing acceptance / integration testing using a bastion running in a docker container. Right now we have a dedicated host in AWS that we use. 

Why do we care?
1. We'd rather not maintain the bastion infra if we don't have to 
2. It means that the tests require secrets as an input which adds a bit more friction. If we use docker that would not be necessary.
3. It requires having a static instance of the database we trying to test running! Because the bastion is static it also needs to be forwarding to some database in our VPC so we need a statically running db as well. This limits the tests we can right and means we're paying for and maintaining a database for no good reason. Ideally we could spin up dbs and bastion all in docker!

@sherifnada fyi

**Comment by cgardens** [comment]
I'm putting this as a high priority, as I really think we should fix this before we trying to develop SSH connectors for any other databases. Happy to adjust if others think this is not a pre-req.

**Comment by cgardens** [comment]
Adding a diagram of the problem to make it a little clearer. https://docs.google.com/drawings/d/1StbJMqN9v5unzxxu121vdiZrxAKzLm3gEHCdlb_uXb4/

**Comment by sherifnada** [comment]
thanks @cgardens!

cc @alexandr-shegeda
