### ISSUE TITLE
Sendgrid connector should support Marketing Campaigns' Single Send Stats

### ISSUE THREAD

**Issue by gregdale** [airbytehq/airbyte#5820]
## Tell us about the problem you're trying to solve
We are trying to acquire our email marketing data. Airbyte's existing Sendgrid integration does not support our key table, Single Send Stats. (It does support Automation Stats but we are not users of that.) 

## Describe the solution you’d like
Airbyte would connect to Marketing Campaign Single Send Stats as described here: https://docs.sendgrid.com/api-reference/marketing-campaign-stats/get-all-single-sends-stats

## Describe the alternative you’ve considered or used
This is blocking us from using Airbyte for Sendgrid stats. 

## Are you willing to submit a PR?
I'm on the product/business end, so I was hoping not :) but can re-examine if its not a priority to improve. Possibly related to https://github.com/airbytehq/airbyte/issues/2117

**Comment by igrankova** [comment]
Hi, @gregdale 
We are looking for a contributor who is a Sendgrid customer. We need help with the partner program. If this customer contacts Sendgrid sales team and confirms that uses Airbyte, it would help us to get the partnership. 
Let me know if there's something you can help with.
Thank you in advance.
