### ISSUE TITLE
CI Sandbox for Commerce Tools connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5823]
## Tell us about the problem you're trying to solve
A community contributor submit a new source for Commerce Tools https://commercetools.com/.
The credentials are needed to run integration tests.

The https://github.com/airbytehq/airbyte/pull/5957 is adding this new source 

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by igrankova** [comment]
To obtain a sandbox we can apply to [Partner Program](https://commercetools.com/partner-program/join)
