### ISSUE TITLE
Investigate the effect of huge WAL logs on Postgres CDC source sync

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5837]
A user reported that their Postgres source connector running in CDC mode was not able to fetch the changes during incremental updates. Take a look at the following logs
``` 
2021-09-02 08:23:46 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-02 08:23:46 [32mINFO[m i.d.c.p.PostgresStreamingChangeEventSource(searchWalPosition):268 - {} - Searching for WAL resume position
2021-09-02 08:28:44 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-02 08:28:44 [32mINFO[m i.a.i.d.i.DebeziumRecordIterator(computeNext):98 - {} - Closing cause next is returned as null
```
The two logs have a difference of 5 minutes. We wait for 5 minutes and there were no records returned by debezium and as a result we shutdown the sync. The last log from debezium is `2021-09-02 08:23:46 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-09-02 08:23:46 [32mINFO[m i.d.c.p.PostgresStreamingChangeEventSource(searchWalPosition):268 - {} - Searching for WAL resume position
`

Even after 5 minutes of waiting debezium didn't return any record which caused the sync to shut down. 

The user reported that they dropped and recreated the logical replication slot, and now have successful syncs. WAL was at ~250GB before they dropped it.

Our guess is that 5 minutes is not enough to find the resume position if WAL grows too big?

Slack ref : https://airbytehq.slack.com/archives/C01MFR03D5W/p1630662717338800?thread_ts=1630572024.268600&cid=C01MFR03D5W
[logs-1338-0.txt](https://github.com/airbytehq/airbyte/files/7105731/logs-1338-0.txt)

**Comment by sherifnada** [comment]
Additional instance of this happening in https://github.com/airbytehq/oncall/issues/90:
[logs-31085-0 (2).txt](https://github.com/airbytehq/airbyte/files/7850460/logs-31085-0.2.txt)

**Comment by grishick** [comment]
Exit criteria:
 - test (could be manual)
 - test results: how long it takes to read 250GB WAL. 
 - Test scenarios: 
      1. WAL log is occupied with events from the table we are syncing
      2. WAL log is occupied with events from a table we are not syncing

Estimate: L (one sprint). To set this up will take some time.

**Comment by tuliren** [comment]
Experiment doc:
https://docs.google.com/document/d/1-IDDtL77DMl0nwqZ9XUlhTg3mW3TfAis5cO90S81TXE/edit

**Comment by tuliren** [comment]
The investigation is done. Here are the follow-up tickets:
- https://github.com/airbytehq/airbyte/issues/13207
- https://github.com/airbytehq/airbyte/issues/13208
- https://github.com/airbytehq/airbyte/issues/13209
