### ISSUE TITLE
Replace personal tokens in Airbyte github action wotkflows with dedicated account token

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5838]
Currently we are using our own personal tokens in github action workflows. We should create a dedicated github account and use tokens from that account. Some tokens that we use : 
secrets.SLASH_COMMAND_PAT : @jrhizor personal token, its being used by multiple workflows
secrets.SELF_RUNNER_GITHUB_ACCESS_TOKEN : @davinchia personal token

The above two tokens are used by multiple workflows such as Slash command, Release Airbtye open source, etc.

**Comment by davinchia** [comment]
@supertopher @git-phu is this already done? or do we have stuff left here?

**Comment by cpdeethree** [comment]
These were all consolidated as part of a PAT consolidation project we wrapped up in Q4 22
