### ISSUE TITLE
Import config from file doesn't work in 0.29.14-alpha+

### ISSUE THREAD

**Issue by Voronenko** [airbytehq/airbyte#5841]
## Enviroment
- **Airbyte version**:  example is 0.29.14-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Postgres
- **Destination Connector and version**: Postgres
- **Severity**: Low
- **Step where error happened**: Restore configuration

## Current Behavior
 When I am trying to restore configuration by uploading config file, nothing happens , except /health call appearing in network log

## Expected Behavior
  Configuration should be restored from file

**Comment by marcosmarxm** [comment]
thanks for reporting this @Voronenko. I tried and got same problem with my local instance.
[server-logs (5).txt](https://github.com/airbytehq/airbyte/files/7118143/server-logs.5.txt)
[scheduler-logs (4).txt](https://github.com/airbytehq/airbyte/files/7118144/scheduler-logs.4.txt)


Steps to reproduce:
- start Airbyte, create a source/destionation, sync a job, export configs
- docker-compose down -v
- docker-compose up and try import the config.

**Comment by cgardens** [comment]
@marcosmarxm is this still a problem in recent versions?

**Comment by cgardens** [comment]
no longer supported
