### ISSUE TITLE
create a backend property for "completed first sync"

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5884]
In order for us to show the :+1: / :-1: display on the frontend after completing the first sync, we need to expose the value to the frontend. We could do this by augmenting the user's response to include this property. We could do this at the user level and look it up at in their workspaces to ensure they've successfully completed a sync.

**Comment by benmoriceau** [comment]
Fully merged, https://github.com/airbytehq/airbyte/issues/8113 has been created as a follow up on the frontend part.
