### ISSUE TITLE
handle multiple users going through onboarding for the same workspace

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5885]
Right now the connection setup wizard is effectively per-workspace not per-user. We should define the expected behavior here. 

probably related: https://github.com/airbytehq/airbyte/issues/5884 and https://github.com/airbytehq/airbyte/issues/5883

**Comment by timroes** [comment]
Per workspace is desired at the moment, no recent discussion on that, so closing this off.
