### ISSUE TITLE
programatically configure our github ec2 runner amis

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5913]
It'd be great to define the AMIs in Packer (https://www.packer.io/) so it's easy to extend and modify the image.

**Comment by jrhizor** [comment]
Jenny mentioned this when I was mentioning that it was tricky to experiment with build AMIs @davinchia

**Comment by jrhizor** [comment]
related: https://github.com/airbytehq/airbyte/issues/4559

**Comment by cpdeethree** [comment]
This was completed as part of another story, our ami's are now defined with packer
