### ISSUE TITLE
Allow user to provide custom options in CDC database connectors

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#5916]
We should allow users to provide custom options such as `batch_size` in CDC connectors. This has a risk to it that a user might make an incorrect choice so we should try to educate people on how to use it and if they are not sure then stick with the default values.

**Comment by yurii-bidiuk** [comment]
Hi @subodh1810 
Is this ticket relevant now?
If yes, could you please clarify what you mean by custom options?
Should it be some predefined CDC properties where the user can enter only value? Or we should add some input field and users will be able to enter the key and value, something like: `max.batch.size=1024;max.queue.size=8192;`

**Comment by prateekmukhedkar** [comment]
Do we see connections setup with incorrect values for Postgres source? Intuitively thinking that users setting up CDC know what they are doing. We should include these in our documentation but do we need any changes in the UI? cc @subodh1810 @misteryeo

**Comment by subodh1810** [comment]
We dont allow users to provide input for these parameters in CDC mode for any connector. But now that I think of it, perhaps we should make the choice for them instead of them having to decide cause chances are pretty high that they wouldnt know how to set the right value.

**Comment by misteryeo** [comment]
Closing based on latest comment.
