### ISSUE TITLE
Connecting a Postgres database running locally fails

### ISSUE THREAD

**Issue by mathewtrivett** [airbytehq/airbyte#5918]
Hi Airbyte team, really excited about what you are building. I'm currently trying to evaluate Airbyte to handle our data engineering workload.

I wanted to initially test it on my local machine using a local database running inside a Homebrew installed version of Postgres.

## Environment

- **Airbyte version**:  0.29.15-alpha
- **OS Version / Instance**: Mac OS Mojave 10.14.6
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.11
- **Destination Connector and version**: N/A
- **Severity**: Low
- **Step where error happened**: Setup new connection

## Current Behaviour

I have Postgres running locally, installed by Homebrew. 

I'm running Airbyte using the Getting started instructions to try and connect a source. The database and user exist and I can connect to it fine using the `psql` command. Even testing it like this `psql -h localhost -p 5432 analytics -U analytics` works fine.

When I try to add this database as a source in Airbyte using the following details:

Host: localhost
Port: 5432
Database: analytics
User: analytics
Password: *****

Then I get the following error:

```
The connection tests failed.
Could not connect with provided configuration. Error: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
```

Is this something to do with it running in Docker and localhost referencing the running container?

## Expected Behavior

I expect to be able to connect to the Postgres database running on my local machine to help me evaluate Airbyte and test things locally.

## Logs

N/A

## Steps to Reproduce

1. Install Postgres with Homebrew
2. Create a database and user in the Postgres database run by Homebrew
3. Clone the Airbyte repo
4. Run docker compose up
5. Go to create a new source using the credentials for the Homebrew run database.

## Are you willing to submit a PR?

I'm not a Java developer unfortunately.

**Comment by marcosmarxm** [comment]
@mathewtrivett take a look in [our docs](https://docs.airbyte.io/troubleshooting/new-connection#connection-refused-errors-when-connecting-to-a-local-db). This is a problem with container network. Let me know if this solve your problem. If the two options don't work try to use: host.docker.internal

**Comment by mathewtrivett** [comment]
Thanks for the quick response I'll take a look.
