### ISSUE TITLE
Shopify Source should be friendly for SaaS / Multi-Tenant developers

### ISSUE THREAD

**Issue by derekybainbridge** [airbytehq/airbyte#5927]
## Tell us about the problem you're trying to solve

For the Shopify Source the current authentication method requires the api_password. If you're in a SaaS or multi-tenant situation you have to talk to customers to get this api_key (I believe).  We are a SaaS platform trying to no-touch self-onboard customers.  We can perform an Oauth2 standard key exchange and can get the auth_token for their Shopify account to call the API programatically, we just can't use that key to input into our Airbyte configuration. Is it possible to have the Shopify Source support oAuth auth_token (The Airbyte FB Ads and Google Ads use this oAuth mechanism by supporting an auth_token already)

## Describe the solution you’d like
In the Shopify source the ability to specify an auth_token and any needed data to call the Shopify api Instead of (or alongside of) the api_passsword

## Describe the alternative you’ve considered or used
Now we have to talk to customers one-by-one and ask them to grant us access to their store.  As we scale this will slow us down, again the FB Ads, Google Ads, etc we can just use OAuth to do the work here and not have to give customers special instructions.

## Additional context
FB ads, Google Ads, etc already support an Oauth2 auth_token in the Airbyte UI, so the patterns there could be followed.

## Are you willing to submit a PR?
Sure

**Comment by sherifnada** [comment]
@derekybainbridge are you working on supporting this? If so, do you have an ETA? I'm looking into wider oauth support for many connectors and it would help me plan the roadmap if I understand any planned contributions

**Comment by derekybainbridge** [comment]
Hiya,
I haven't started yet, unsure when I'll be able to get to it.  Do you know
the rough level of effort, I haven't built/modified a connector in Airbyte.
For purposes of roadmapping probably plan on building this internally and
I'll reach out if I can take a swing at it.

Thanks,
Derek

**Comment by sherifnada** [comment]
@derekybainbridge FYI Shopify now supports oauth -- please see the latest connector version and you should be able to pass the output from the oauth flow you implement into the connector and support the use case you describe!
