### ISSUE TITLE
CI Sandbox for Mailgun

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#5932]
## Tell us about the new connector you’d like to have
PR https://github.com/airbytehq/airbyte/pull/5904 adds Mailgun with Singer. We need the sandbox to run integration tests.

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
Creating the sandbox account
[ ] create an account, get API key (30m) 

Generating access credentials to the account
[ ] in Postman create Access Token that can be used to access the API (1h)

Populating the account with data and receiving them from API
[ ] Create in Postman API requests for Messages, Domains, IPs, Events, Tags, Bounces, Complaints, Unsubscribes . (3h)
