### ISSUE TITLE
Migrate Airbyte Cloud Helm charts over to use open source Helm chart

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#5934]
## Tell us about the problem you're trying to solve
Follow up to #5891 

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by malikdiarra** [comment]
this has been completed.
