### ISSUE TITLE
Overlapping HTML elements in Firefox

### ISSUE THREAD

**Issue by drjeep** [airbytehq/airbyte#5952]
## Enviroment
- **Airbyte version**:  0.29.17-alpha
- **OS Version / Instance**: CentOS 7.9 (server), Fedora 33 (client), Firefox 90
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.11
- **Destination Connector and version**: BigQuery 0.4.0
- **Severity**: Low
- **Step where error happened**: Setup new connection / Update connector
![Screenshot 2021-09-09 at 16-43-14 Airbyte Connections Edge4Health → BigQuery](https://user-images.githubusercontent.com/3074521/132708978-054a9209-9503-40f8-b75c-b482d28f5c71.png)

## Current Behavior
*List of tables overlap other UI elements when it's larger than the viewport (scrollbar does not work)*

## Expected Behavior
*List of tables should scroll and not overlap other UI elements*

## Steps to Reproduce
1.Setup a new connection using a Postgres source with > 20 tables (depending on screen resolution)

## Are you willing to submit a PR?
No

**Comment by marcosmarxm** [comment]
@drjeep is it possible for you test on another web browser to validate the problem persist?

**Comment by drjeep** [comment]
It works in Chrome and Microsoft Edge, so the problem is with Firefox. Those are the only browsers I have access to.

**Comment by marcosmarxm** [comment]
thanks! this give us much more info!

**Comment by salmonsd** [comment]
Can confirm issue is with Firefox; works in Safari.

**Comment by salmonsd** [comment]
@drjeep this has been fixed in [`0.29.22-alpha`](https://github.com/airbytehq/airbyte/releases/tag/v0.29.22-alpha) with #6369 

cc: @marcosmarxm

**Comment by misteryeo** [comment]
Closing this out as it's been fixed with a new version.
