### ISSUE TITLE
source chargebee - fix schema related failure

### ISSUE THREAD

**Issue by midavadim** [airbytehq/airbyte#5976]
the connector's build [is failing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md). This issue tracks fixing it.

**Comment by Zirochkaa** [comment]
Looks like it's an issue in schemas because in test logs there are a lot of following errors:
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/19872253/134024422-0b715ee9-9d48-4aa3-80b6-94c18216b10c.png">
