### ISSUE TITLE
Cloud: Setup bootstrap script for adding instancewide variables on server startup

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6024]

**Comment by ChristopheDuong** [comment]
Once https://github.com/airbytehq/airbyte-cloud/pull/220 is merged in, I think we'd need to update some ESP deployments to expose these endpoints services? 

Then, we'd be able to use the API and set these initial scripts on the cloud, am I right @davinchia?

**Comment by octavia-squidington-iii** [comment]
Octavia says yes!

**Comment by ChristopheDuong** [comment]
let's merge https://github.com/airbytehq/airbyte-cloud/pull/262 and close this issue?

@sherifnada WDYT?

**Comment by sherifnada** [comment]
SGTM let's do it @ChristopheDuong
