### ISSUE TITLE
Only hide Oauth inputs if UI is running for cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6027]
Today the UI by default hides all the parameters specified in the `authSpecification.oauth2Spec.oauthFlowInitParameters` field. 

However, if we release this as it is in the OSS version then most users will not be able to use any oauth connetors, since Oauth params will not be set in the OSS version (not by default at least), and the oauth process is not well documented. 

So when running in OSS we should not hide any oauth fields in the user input forms

**Comment by sherifnada** [comment]
@Jamakase FYI just realized this might be an issue, so we should only apply your logic if it's running on cloud until we have a better long term fix for this.

**Comment by sherifnada** [comment]
cc @jrhizor

**Comment by ChristopheDuong** [comment]
What if the params were not hidden in the UI (or at least moved into an advanced oauth tab/panel instead), would that give the ability to user to "override" the instance-wide credentials and have the option to provide their own?

**Comment by sherifnada** [comment]
Potentially, but it seems simpler to just hide for now in cloud?
