### ISSUE TITLE
Obtain public developer application for the asana source connector

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6071]
## Tell us about the problem you're trying to solve
Obtain a public developer application for the asana connector like specified in #6070 

### Requirements for obtaining the developer application
TBD

**Comment by cheyura** [comment]
@sherifnada done. Access creds https://app.asana.com/0/my-apps/1200986308629153/settings, lastpass - Asana sandbox test admin user

**Comment by sherifnada** [comment]
thanks @cheyura !

**Comment by ycherniaiev** [comment]
For now app is private. https://app.asana.com/0/my-apps/1200986308629153/settings . Lastpass: asana
