### ISSUE TITLE
Add OAuth support for zendesk-support connector

### ISSUE THREAD

**Issue by sujitsagar** [airbytehq/airbyte#6076]
## Tell us about the problem you're trying to solve
We are planning to use `zendesk-support` connector and we can only use with access_token authorization method. Current document mentions it will be added in future

## Describe the solution you’d like
We need add OAuth authorization support 

## Describe the alternative you’ve considered or used
We have been using singer-io's tap-zendesk till now. We are looking to integrate in-house alternative

## Additional context
--- N/A ---

## Are you willing to submit a PR?
Yes.

**Comment by artem1205** [comment]
Added in https://github.com/airbytehq/airbyte/pull/11162
