### ISSUE TITLE
Normalization integration-test wait for test container database to start

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6091]
## Current Behavior
In integration tests for normalization postgres and mysql run tests using docker container. In Ubuntu this contsainers took a while to start and this cause tests to failed.

## Expected Behavior
Should wait containers be ready and start tests.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by ChristopheDuong** [comment]
Duplicates of https://github.com/airbytehq/airbyte/issues/6048
