### ISSUE TITLE
Source-Salesforce: Bulk API limited to 10,000 records

### ISSUE THREAD

**Issue by jagannathsrs** [airbytehq/airbyte#6122]
## Enviroment
- **Airbyte version**:  0.29.17-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**:  salesforce 0.1.0
- **Destination Connector and version**: snowflake 0.3.13
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
When using the Bulk API option for Salesforce source, it only pulls 10,000 records for any object.
## Expected Behavior
Should be able to pull more than that since the [SF Bulk API documentation](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_bulkapi.htm#batch_allocations) does not specify any record limitation, only file size limitation.

I forked the SF repo and changed the limit 
 https://github.com/airbytehq/airbyte/blob/6ceccadf21bd6cbb563b4fb3ed0e7643b209ae88/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L119 from 10,000 to 500,000 and it works better. Is there any reason this limit was applied in the first place? 

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
thanks, @jagannathsrs! @yevhenii-ldv can you give your opinion on this?

**Comment by yevhenii-ldv** [comment]
hello @jagannathsrs! This limit is specified for a one-time request to receive data on a stream, but there is pagination, which, when not all data is retrieved, asks for the next batch of data.
Please tell me which streams you have a problem with?

**Comment by jagannathsrs** [comment]
Hey @yevhenii-ldv! I am facing this issue with both custom and standard streams. So far I've tried Account, AccountContactRelation, Contact. All of them have more than 50k + records and only synced 10,000 records.

**Comment by yevhenii-ldv** [comment]
@jagannathsrs Thanks a lot for the information, I'll see what might not work correctly.

**Comment by jagannathsrs** [comment]
Here is some more data to help you debug. Row counts from the Airbyte native connector and from the modified connected where I updated the limit to 500,000 records limit. Note the Did not sync is not an issue since I forgot to select that table while syncing.

TABLE_NAME | ROW_COUNT_NATIVE_CONNECTOR | ROW_COUNT_MODIFIED_CONNECTOR
-- | -- | --
SF_AIR_ACCOUNT | 10001 | 12978
SF_AIR_ACCOUNTCONTACTRELATION | 10000 | 21669
SF_AIR_AFFILIATE_NETWORK__C | 68 | 68
SF_AIR_BILLING_PROFILE__C | 10000 | 77579
SF_AIR_CONTACT | 10000 | 14282
SF_AIR_OPPORTUNITY | 10000 | 89191
SF_AIR_PRODUCT2 | 10000 | 201618
SF_AIR_QUOTE_LINE__C | 10000 | 282465
SF_AIR_QUOTE__C | 10000 | 88705
SF_AIR_SITE_STORE__C | 10000 | 11770
SF_AIR_TENANT_NETWORK_STORE__C | 10000 | Did not Sync
SF_AIR_TENANT__C | 15 | Did not Sync
SF_AIR_USER | 292 | 292

I am also attaching the logs from both the runs. Hope these help!
[airbyte-sf-native-logs.txt](https://github.com/airbytehq/airbyte/files/7180083/airbyte-sf-native-logs.txt)
[airbyte-sf-modified-logs.txt](https://github.com/airbytehq/airbyte/files/7180090/airbyte-sf-modified-logs.txt)

**Comment by yevhenii-ldv** [comment]
@jagannathsrs 

We just merged this fix into master and released a new version of the connector. 

Upgrade your connector to version 0.1.1 and get started. To upgrade your connector version, go to the admin panel in the left hand side of the UI, find this connector in the list, and input the latest connector version. 

Please let us know if you have any further questions. 

Enjoy!
