### ISSUE TITLE
SQL Server on premise as destination

### ISSUE THREAD

**Issue by dubravcik** [airbytehq/airbyte#613]
## Tell us about the new integration you’d like to have
I'd like to have SQL Server data warehouse as destination (on-premise I don't mean Azure Synapse). There are only few cloud alternatives (Fivetran and Skyvia). It is classic data warehouse for many companies which are longer on the market and they don't want to migrate to cloud warehouse.

**Comment by dmonder** [comment]
I agree. Our organization is Microsoft-driven and would need to put this into a SQL Server database.

**Comment by michel-tricot** [comment]
Out of curiosity is the SQL server from RDS (https://aws.amazon.com/rds/sqlserver/) or the one in https://hub.docker.com/_/microsoft-mssql-server the one you're talking about?
Thanks

**Comment by dmonder** [comment]
I would seek to export my data to my locally hosted SQL Server, which would be roughly equivalent to the docker version, though I am not using docker for my SQL Server.

**Comment by rabel** [comment]
I would also like an SQL Server destination.

**Comment by ReinierKop** [comment]
+1
