### ISSUE TITLE
Clean up helm chart after we merge it in.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#6131]
## Tell us about the problem you're trying to solve
* Clean up the awesome Helm chart contribution from #5891 .
* Create an issue summarising Airbyte's next steps with Kubernetes deploys.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
* understand it
* fix build errors
* deprecate kustomize
* run acceptance tests

**Comment by davinchia** [comment]
This is old and no longer relevant.
