### ISSUE TITLE
Typo in documentation link

### ISSUE THREAD

**Issue by zainearnest** [airbytehq/airbyte#6137]
https://github.com/airbytehq/airbyte/blob/4c0d1a039983a135823d69a222fc2fad82cdb1ad/airbyte-integrations/connectors/source-bigquery/src/main/resources/spec.json#L2

This should be https://docs.airbyte.io/integrations/sources/bigquery

**Comment by marcosmarxm** [comment]
thanks @zainearnest do you want to submit a patch PR?

**Comment by cgardens** [comment]
this was fixed.
