### ISSUE TITLE
Update Onboarding Docs

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#614]
## Tell us about the problem you're trying to solve
* Discovered while trying to onboard chris; missing or outdate docs
* worker actions and descriptions (outdated) ([current docs](https://github.com/airbytehq/airbyte/blob/master/docs/architecture/configuration-data-model.md))
* docker compose (specify minimum version)

**Comment by avaidyanatha** [comment]
@cgardens Is this issue still up to date? I think we do mention docker-compose versioning, but am not sure about the worker actions/descriptions.

**Comment by cgardens** [comment]
all fixed. closeable.
