### ISSUE TITLE
Hubspot connector: Use correct schema for owners table

### ISSUE THREAD

**Issue by Tomo-Sai** [airbytehq/airbyte#6147]
**Enviroment**

**Is this your first time deploying Airbyte:** No
**OS Version / Instance:** AWS
**Deployment:** EC2
**Airbyte Version:** 0.29.17-alpha
**Source name/version:** Hubspot 0.1.13
**Destination name/version:** Postgres 0.3.11
**Severity**: High
**Step**: Sync
**Description/ Current Behavior:** fields _type, ownerid, isactive, portalid, signature, remotelist, activeuserid, hascontactaccess, useridincludinginactive_ have null for all records. 

**Expected Behavior:**
fields _type, ownerid, isactive, portalid, signature, remotelist, activeuserid, hascontactaccess, useridincludinginactive_ have values for all records.

**Logs:**
No error in logs, just missing fields.
example of airbyte_data field in raw table 
{"id", "email", "teams": [{"id", "name"}], "userId", "archived", "lastName", "createdAt", "firstName", "updatedAt"}

**Steps to Reproduce**
Setup a sync with the Hubspot connector on an account that has Owners data.
Run a sync
multiple fields mentioned in the description will not be retrieved.

**Comment by sherifnada** [comment]
@Tomo-Sai I don't see these fields in the API schema described here
![Screen Shot 2021-09-16 at 8 18 23 PM](https://user-images.githubusercontent.com/6246757/133718761-5fdb1535-ee39-45ea-bccf-59791558547e.png)


Are these custom properties?

**Comment by Tomo-Sai** [comment]
@sherifnada looks like those fields are removed in hubspot v3 (the hubspot [v2 version](https://legacydocs.hubspot.com/docs/methods/owners/get_owners) has it). Can the owners table schema in Airbyte be changed to match hubspot v3 schema? Seems like Airbyte is calling v3 but the schema in Airbyte owners table is still v2.
<img width="366" alt="owners" src="https://user-images.githubusercontent.com/79871867/133820013-c3406f5e-306c-4d18-9f92-799066773e36.png">
