### ISSUE TITLE
Add Sendgrid Email Activity API to Sendgrid connector

### ISSUE THREAD

**Issue by gregdale** [airbytehq/airbyte#6150]
## Tell us about the problem you're trying to solve
A significant part of Sendgrid's utility is transactional, API-driven email sends. The analytics and history for these sends are available from a different API than the one that is currently implemented.

## Describe the solution you’d like
Add the [Email Activity Feed API](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages) to the Airbyte Sendgrid connector.

## Describe the alternative you’ve considered or used
No alternatives available.

## Are you willing to submit a PR?
Can't at the moment

**Comment by sherifnada** [comment]
relevant: to test this endpoint requires purchasing additional email history like described in the docs https://docs.sendgrid.com/for-developers/sending-email/getting-started-email-activity-api

**Comment by martinibach** [comment]
@sherifnada could you take a look at this again, please? Most companies use Sendgrid for transactional emails. The current connector is pretty much useless without analytics for transactional emails.

**Comment by darynaishchenko** [comment]
@gregdale for today, this stream is already developed in this [PR](https://github.com/airbytehq/airbyte/pull/13571)
