### ISSUE TITLE
Make Shopify enforced data solution a general utility in the CDK

### ISSUE THREAD

**Issue by vitaliizazmic** [airbytehq/airbyte#6152]
## Tell us about the problem you're trying to solve
Sometime sources API return not convenient for using type of values which should be transformed. E.g, according to issue #4841 Shopify stream returns price fields as a string. This makes it difficult to do simple math or create sales reports.

## Describe the solution you’d like
Use general enforced data solution.

## Describe the alternative you’ve considered or used
Enforced data solution was created for Shopify source #5244 This solution can become a part of CDK.

**Comment by bazarnov** [comment]
It's done as `TypeTransformer` in CDK.
