### ISSUE TITLE
Got "Duplicate key airbyte/destination-keen" when relaunch airbyte

### ISSUE THREAD

**Issue by lorriexingfang86** [airbytehq/airbyte#6157]
Hi,

I got:

` Config database has been initialized; updating connector definitions from the seed if necessary...
airbyte-server      | Exception in thread "main" java.lang.IllegalStateException: Duplicate key airbyte/destination-keen (attempted merging values io.airbyte.config.persistence.DatabaseConfigPersistence$ConnectorInfo@7fab4be7 and io.airbyte.config.persistence.DatabaseConfigPersistence$ConnectorInfo@a64e035)
airbyte-server      | 	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
airbyte-server      | 	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
airbyte-server      | 	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
airbyte-server      | 	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
airbyte-server      | 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
airbyte-server      | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
airbyte-server      | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
airbyte-server      | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
airbyte-server      | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
airbyte-server      | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
airbyte-server      | 	at io.airbyte.config.persistence.DatabaseConfigPersistence.getConnectorRepositoryToInfoMap(DatabaseConfigPersistence.java:374)
airbyte-server      | 	at io.airbyte.config.persistence.DatabaseConfigPersistence.updateConfigsFromSeed(DatabaseConfigPersistence.java:301)
airbyte-server      | 	at io.airbyte.config.persistence.DatabaseConfigPersistence.lambda$loadData$0(DatabaseConfigPersistence.java:80)
airbyte-server      | 	at io.airbyte.db.Database.lambda$transaction$0(Database.java:51)
airbyte-server      | 	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564)
airbyte-server      | 	at org.jooq.impl.Tools$12$1.block(Tools.java:4926)
airbyte-server      | 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
airbyte-server      | 	at org.jooq.impl.Tools$12.get(Tools.java:4923)
airbyte-server      | 	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616)
airbyte-server      | 	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533)
airbyte-server      | 	at io.airbyte.db.Database.transaction(Database.java:51)
airbyte-server      | 	at io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:51)
airbyte-server      | 	at io.airbyte.config.persistence.DatabaseConfigPersistence.loadData(DatabaseConfigPersistence.java:77)
airbyte-server      | 	at io.airbyte.server.ServerApp.getServer(ServerApp.java:182)
airbyte-server      | 	at io.airbyte.server.ServerApp.main(ServerApp.java:256)
`
Error when launch airbyte on my local. I've tried to restart/delete docker image and rerun everything again but nothing works.

Does anyone have same issue? How to solve it?

Thanks!

**Comment by marcosmarxm** [comment]
@lorriexingfang86 please upgrade to the latest version. Also, please use the template to create new issues because it gives us minimal information to help you.

**Comment by lorriexingfang86** [comment]
@marcosmarxm thanks! I deleted my current project repository and git clone and launch it again, it works now.
