### ISSUE TITLE
Normalization: set primary key field as primary key in final table

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6161]
## Tell us about the problem you're trying to solve
From [slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1631742330376900).
Some users want to use the final table with other tools that require tables have primary key.
> I have additional tables I'm creating in the same db that link to these tables via foreign keys.
I was trying to set up a couple other tools to use as an internal admin portal (directus, nocodb, budibase) and all of them depend on primary keys to different degrees

## Describe the solution you’d like
For simple cases (primary key field is not nested) set the final tables with primary key.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by ChristopheDuong** [comment]
primary/clustering/partition keys or whatever index could be set by the user as a final dbt custom transformation step too

See thread https://airbytehq.slack.com/archives/C01MFR03D5W/p1623410359429800?thread_ts=1623396575.421800&cid=C01MFR03D5W

**Comment by chrisshaw** [comment]
(While having this doen for me would still be better :wink: ) Is this something supported in Cloud, @ChristopheDuong? I was looking at the docs and this was my initial plan, but I'm using the Cloud beta. It doesn't look like it's supported there.
