### ISSUE TITLE
Allow uploading files as part of a connector's config in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6162]
## Tell us about the problem you're trying to solve
Sometimes a connector needs access to an uploaded file e.g: an SSL certificate or JSON key credentials. Today there is no way to upload a file via the UI. 

## Describe the solution you’d like
I'm not sure what the right solution is. One possibility is to add a new annotation `file: true` which then tells the UI that this should be uploaded rather than input via a textbox e.g: 

```
{
  "type": "string", 
  "file": "true"
  "airbyte_secret": true
 ...
}
```

We may need backend changes to do this, and potentially support for multipart uploads in the API if it doesn't already exist (idk if it does). 

## Describe the alternative you’ve considered or used
Copy pasting contents of files

**Comment by timroes** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/4084
