### ISSUE TITLE
source cart: fix test failures

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6171]
the connector's build [is failing](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/builds.md). This issue tracks fixing it.

**Comment by yevhenii-ldv** [comment]
@sherifnada 
I see 10 out of 10 correct [builds](https://dnsgjos7lj2fu.cloudfront.net/tests/summary/source-cart/) for the Cart connector, perhaps it meant a different connector?
