### ISSUE TITLE
New Source: Airbyte-native Mailgun

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6172]
#5904 introduced a singer-based version of mailgun contributed by a community member. We want to support this connector but due to licensing and technical issues with Singer we need to move it to a native connector.

**Comment by yevhenii-ldv** [comment]
## Integration Vetting
**Webhook-based? (no/partially/yes)**

**Available authentication modes (API key/Oauth/other)**

**Connecting to the data source**



**Creating an account**





**How to populate the account with data?**






**Do any streams support incremental sync?**


**Preparation scope & blockers**

**Other information/blockers**

**Comment by sergei-solonitcyn** [comment]
## Product Requirements & features

### 1. What is the “ideal end state” for the features offered by this connector?
- Mailgun REST entities (subentities) map to Airbyte streams
- Only API key is required to make requests

### 2. What is the release roadmap for this connector?
- Domains and Messages endpoints seem to be required for very minimal functionality
- All other endpoints available in the free plan would provide advanced benefits
- These endpoints require a paid plan and could be implemented afterwards:
  - Inbox subentities (Results, Seed lists, 
  - IP pools
  - Routes
  - Validate
### 3. Check if and how Fivetran or Stitch Data support this connector 
- Fivetran doesn’t support Mailgun and doesn’t plan to do it. Related request still has only one vote for it: https://support.fivetran.com/hc/en-us/community/posts/4408445558807-New-Connector-Mailgun
- Integration solution by Stitchdata also isn’t detected

**Comment by sergei-solonitcyn** [comment]
## Implementation Scoping
### Commonalities across the API endpoints
- #### Pagination strategy
  According to the docs some endpoints have a <**limit**> field with different default and min/max values for different endpoints. The responses provide **previous** and **next** pages urls
- #### Authentication strategy
  HTTP Basic Auth with **Private API key** is used for every request, so it could be used as a config data for the connector
- #### Populate the sandbox account with data
  It’s possible to create a script which would automatically generate some data. It would use the API functionality itself, but the UI doesn’t provide the whole functionality
- #### Handling rate limits
  In case of exceeding rate limits (300 requests per minute) the endpoints return a rate limit response: 
```
{
        "retry-seconds": 60,
}
```
Which should be handled in the obvious way

**Comment by sherifnada** [comment]
@sergei-solonitcyn thanks for providing the context! the initial two streams you proposed sound good for a start. Let's move ahead with that scope!

**Comment by sergei-solonitcyn** [comment]
Agree, **Events** is defenitely good one to be in the MVP.
Getting to work.
