### ISSUE TITLE
Obtain public developer application for the Jira source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#6181]
TBD

**Comment by igrankova** [comment]
[EPIC] Oauth developer applications #6070

**Comment by ycherniaiev** [comment]
access oauth client here: https://developer.atlassian.com/console/myapps/4daa1d51-471e-4cbe-af53-b8b53cf1dcb6/settings

**Comment by igrankova** [comment]
Created an OAuth app for JIRA: https://airbyteio.atlassian.net/secure/admin/oauth-credentials
Find creds - LastPass name: Jira Cloud integration tests
Docs to change permissions are [here](https://support.atlassian.com/jira-cloud-administration/docs/integrate-with-self-hosted-tools-using-oauth/#Integratingwithself-hostedtoolsusingOAuth-CreateOAuthcredentialsinJiraCloud).
