### ISSUE TITLE
Obtain public developer application for the Tempo source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#6197]
TBD

**Comment by igrankova** [comment]
[EPIC] Oauth developer applications #6070

**Comment by cheyura** [comment]
@sherifnada Done. Access OAuth client https://airbyteio.atlassian.net/plugins/servlet/ac/io.tempo.jira/tempo-app#!/configuration/identity-service. Oauth flow passed

**Comment by sherifnada** [comment]
thanks @cheyura
