### ISSUE TITLE
Obtain public developer application for the Snowflake source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#6201]
TBD

**Comment by igrankova** [comment]
[EPIC] Oauth developer applications #6070

**Comment by cheyura** [comment]
JDBC by default

**Comment by cheyura** [comment]
JDBC by default

**Comment by igrankova** [comment]
Created the Public Snowflake SECURITY INTEGRATION, name: AIRBYTE.
To receive Client ID and Secret:
In the Snowflake App add a new worksheet and run the sql query: select system$show_oauth_client_secrets('AIRBYTE');
LastPass cred name:  Snowflake integration test account
