### ISSUE TITLE
mysql CDC failure on unselected table

### ISSUE THREAD

**Issue by matfiorlh** [airbytehq/airbyte#6205]
## Enviroment
- **Airbyte version**:  0.29.19-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mysql:0.4.4
- **Destination Connector and version**: airbyte/destination-bigquery:0.4.0
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behaviour

Sync job fails to parse a table creation statement (this is a known issue, see: https://issues.redhat.com/browse/DBZ-3559), however the table is not selected for replication. This happens only if you select CDC with incremental sync mode.

## Expected Behavior

Only selected tables should be replicated, hence no error should appear as the statement should be parsed correctly.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

[logs-1-0.txt](https://github.com/airbytehq/airbyte/files/7185236/logs-1-0.txt)

</details>

## Steps to Reproduce
1.  set up mysql connection as a source, select CDC (at least one table in your source schema should have a column with type json _utf8mb3).
2. set up a bigquery destination (you should be able to replicate with any destination but I have not tested yet).
3. set up connection between source with incremental mode.
4. start the sync

## Are you willing to submit a PR?

yes I am.

**Comment by matfiorlh** [comment]
could this be resolved simply by updating debezium to the latest version?

**Comment by subodh1810** [comment]
We have upgraded debezium to latest version (1.9) for mysql so this bug should be fixed since the [issue](https://issues.redhat.com/browse/DBZ-3559)  mentions fix is released in 1.7 debezium version
