### ISSUE TITLE
Error editing BigQuery destination

### ISSUE THREAD

**Issue by HyanBatista** [airbytehq/airbyte#6216]
## Enviroment
- **Airbyte version**:  0.29.17-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: Microsoft SQL Server (MSSQL) 0.3.5 
- **Destination Connector and version**: BigQuery 0.4.0 
- **Severity**: Medium
- **Step where error happened**: Setup new destination / Update created destination by setting loading method as GCS staging

## Current Behavior
The change isn't applied.

## Expected Behavior
The new configuration should be applied and showed by the browser.

## Logs
Using the browser we caught these logs which we think could help solving the issue.
![airbyte_js_logs](https://user-images.githubusercontent.com/54192614/133787660-de99c705-465a-44c1-be93-158f90a3a9e2.jpg)

## Steps to Reproduce
1. Create a BigQuery destination with the loading method of standard inserts.
2. Edit the destination by changing the loading method to GCS staging.

**Comment by sherifnada** [comment]
@HyanBatista does this also happen if you create a new bigquery destination?

**Comment by HyanBatista** [comment]
> @HyanBatista does this also happen if you create a new bigquery destination?

No, it doesn't.

**Comment by edmundito** [comment]
I tested this against `v0.40.4,` and I was not able to reproduce it. Please let us know if you see this again and will be happy to re-open it.
