### ISSUE TITLE
Facebook Marketing Source:  Add "Ad Image" stream.

### ISSUE THREAD

**Issue by jd-sanders** [airbytehq/airbyte#6226]
## Tell us about the problem you're trying to solve
I am using the Facebook Marketing source connector, and would like to be able to see the performance of various ads next to the link of the associated image in the creative.  

In certain cases, the image url is contained in the Ad Creative object, which is one of the core streams synced with the Facebook Marketing connector.  

In many cases, however, that's not where the data is stored.

## Describe the solution you’d like

In the many cases where the image url of an ad creative is not available in the Ad Creative stream, it is because it is stored in the Ad Library and can be accessed with a different object through the Marketing API:  `Ad Image`

https://developers.facebook.com/docs/marketing-api/reference/ad-image

I would like to be able to sync the Ad Image stream along with the existing streams (Ad, Adset, Ad Creative, Campaign, and Ad Insights)

## Describe the alternative you’ve considered or used
I have not found a workaround for getting the data.

## Are you willing to submit a PR?

Not immediately

**Comment by sherifnada** [comment]
@jd-sanders thanks for creating the issue! will update prioritization here
