### ISSUE TITLE
Add a page in the UI to set instancewide variables

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6253]
## Tell us about the problem you're trying to solve
Currently to set instancewide variables one needs to run a curl request like: 

```
curl -X POST \
    -H 'Content-type: application/json' \
    $API_URL/source_oauths/oauth_params/create \
    -d '{"sourceDefinitionId": "'"$GOOGLE_ADS_DEF_ID"'", "params":{"credentials":{"client_id": "'"$CLIENT_ID"'", "client_secret":"'"$CLIENT_SECRET"'", "developer_token":"'"$DEVELOPER_TOKEN"'" }}}'
```

## Describe the solution you’d like
I would like to be bind instancewide variables to a connector through the UI instead of having to do an API call

This UI view should only be available for super admins

**Comment by evantahler** [comment]
What are instancewide  used for?

**Comment by sherifnada** [comment]
oauth

**Comment by evantahler** [comment]
If it's only for super-admins, is doing things with a SQL GUI the way to go?  Until we sort out what we want to do with oAuth, I'm wary of "enhancing" things...

**Comment by sherifnada** [comment]
yeah this was created ~15 months ago when the project first shipped and this was an improvement with what we knew back then. I think we should close this since we have better ideas on where to go from here
