### ISSUE TITLE
Source Greenhouse: support oauth

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6270]
## Tell us about the problem you're trying to solve
With the release of Airbyte Cloud, we need to start supporting Oauth for this connector, since it's the recommended way of authenticating users into a SaaS application. 

If this connector doesn't support oauth already (i.e: doesn't accept a client_id and client_secret) then we need to update its spec to accept those parameters. I suggest that this be a oneof nested inside a top-level field called "authentication": 

`
{
  authentication: {
     type: object
     oneOf: [ 
       // api key,
       // oauth
     ] 
  }
}
`

See the connector spec reference in the docs for reference on how a oneof can be implemented.

This should be done in a backwards compatible manner i.e: users currently supplying authentication info in the config's top-level should not be impacted by this change. 

## Acceptance Criteria

1. The connector supports oauth webflow authentication with client_id/client_secret 
2. Oauth properties are annotated properly. See [this PR](https://github.com/airbytehq/airbyte/pull/6022) for an example

**Comment by gaart** [comment]
1) Harvest API
This API currently used in greenhouse connector
The Harvest API was designed to allow our customers to export their data from Greenhouse
docs: https://developers.greenhouse.io/harvest.html#introduction
authentication – Basic Auth only:  https://developers.greenhouse.io/harvest.html#authentication

2) Candidate Ingestion API
The Candidate Ingestion API enables sourcing partners with whom Greenhouse shares mutual customers to submit prospects and candidates
docs: https://developers.greenhouse.io/candidate-ingestion.html#introduction
authentication – OAuth 2.0 and Basic Auth: https://developers.greenhouse.io/candidate-ingestion.html#authentication

3) Job Board API, Assessment API – useless for connector
