### ISSUE TITLE
Source Smartsheets: support oauth

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6280]
## Tell us about the problem you're trying to solve
With the release of Airbyte Cloud, we need to start supporting Oauth for this connector, since it's the recommended way of authenticating users into a SaaS application. 

If this connector doesn't support oauth already (i.e: doesn't accept a client_id and client_secret) then we need to update its spec to accept those parameters. I suggest that this be a oneof nested inside a top-level field called "authentication": 

`
{
  authentication: {
     type: object
     oneOf: [ 
       // api key,
       // oauth
     ] 
  }
}
`

See the connector spec reference in the docs for reference on how a oneof can be implemented.

This should be done in a backwards compatible manner i.e: users currently supplying authentication info in the config's top-level should not be impacted by this change. 

## Acceptance Criteria

1. The connector supports oauth webflow authentication with client_id/client_secret 
2. Oauth properties are annotated properly. See [this PR](https://github.com/airbytehq/airbyte/pull/6022) for an example

**Comment by sherifnada** [comment]
@midavadim is this actually in progress? moving to backlog, please let me know if you're actually working on it

**Comment by TBernstein4** [comment]
@igrankova @sherifnada does the fact that the access token expires in 7 days mean that a user would have to re-authenticate every 7 days if they use OAuth? Did this also remove the option for Cloud users to use just the API key to Authenticate?

**Comment by TBernstein4** [comment]
Can I get clarification on my first question. Will any user that sets up their Smartsheets Connection via OAuth have to re-authenticate every 7 days?

**Comment by TBernstein4** [comment]
This could be a problem because currently the "re-authenticate" button is broken ([Issue](https://github.com/airbytehq/alpha-beta-issues/issues/565)) for existing connections so the user would have to make a new connector every 7 days.
