### ISSUE TITLE
Drive billing backoffice work.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#6303]
## Tell us about the problem you're trying to solve
Catch all issue to figure out engineering work for billing backoffice processes.

This needs to be done by public launch, preferable a week before for testing.

Working PRD [here](https://docs.google.com/document/d/1Xnv-8z28uRekgo-X9rfd1_cIdeo3RbKxHZk5G4btrMQ/edit?usp=sharing).

**Comment by cgardens** [comment]
not relevant anymore
