### ISSUE TITLE
Add filters and segments to Google Analytics API payload

### ISSUE THREAD

**Issue by Jonas56kdigital** [airbytehq/airbyte#6305]
## Tell us about the problem you're trying to solve
Currently, the Google Analytics (GA) connectors only support metrics and dimensions. For most seasoned users of GA API, filters and segments are applied to almost every API request. Airbyte not supporting this thus withhelds a huge part of the usefulness of the connector for such users.

## Describe the solution you’d like
Note: I believe that Airbyte currently have source connectors for both GA API v3 and v4 (Core Reporting API). I am personally agnostic to which API you provide the solution for. 

I believe for GA v3 would be easier to make a solution for, given the simpler spec of the API, however v4 is somewhat more capable/more features.

I think a solution that would make Airbyte extremely useful for a lot of intermediate users who are not as comfortable with JSON files would to be to have a web interface like this one, where you can setup queries in a HTM form: https://ga-dev-tools.web.app/query-explorer/

Now for me personally, just to be able to include a more complete GA API v3 request payload would a big step forward:

`
{ "request_name": "Daily Traffic Sources - Country: Canada",
"payload" {
    "metrics:" "ga:sessions",
    "dimensions":"ga:date,ga:source,ga:medium",
    "filters":"ga:source==Google",
    "segment":"sessions::condition::ga:country==Canada"
}`

Hope this helps!

**Comment by marcosmarxm** [comment]
Thanks @Jonas56kdigital I added the request to our backlog. This is something critical to you?

**Comment by Jonas56kdigital** [comment]
Yes, it would increase the usefulness of Airbyte 10x for me as a web analyst. That feature would mean I can implement it on many more clients and would mean that the AIrbyte Cloud could be a strong competitor to Supermetrics and other digital marketing data-extraction tools.

**Comment by ivanovzlatan2** [comment]
This is a very important feature for GA analysts. Voting with a +1.

**Comment by rhaegar2803** [comment]
I will claim this issue.

**Comment by itaseskii** [comment]
I will claim this issue.

**Comment by skowsikaxl** [comment]
This is a very important feature. Can't wait to use if this is available.

**Comment by itaseskii** [comment]
@skowsikaxl It will be really soon.

**Comment by cjullian** [comment]
This is definitely a major feature. I agree with @Jonas56kdigital when he says it would increase the usefulness of Airbyte 10x...
@itaseskii Is it in development yet?
Thanks

**Comment by krisjan-oldekamp** [comment]
@itaseskii is this still in development? Otherwise I can help?
