### ISSUE TITLE
Source Google Analytics v4: allow run GA account without view id

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6326]
## Tell us about the problem you're trying to solve
From slack convo:

Is this your first time deploying Airbyte: Yes
OS Version / Instance: Ubuntu 20.04
Memory / Disk: 8Gb / 160GB SSD
Deployment: Docker
Airbyte Version: 0.29.2-alpha
Source name/version: Google Analytics v4 0.1.1
Destination name/version: Postgres 0.3.10
Step: Create New Source
Description: Source connector require View ID but GA4 doesn't have View. Since this connector is v4 so how can I pull data from my website that uses GA4 instead of UA.
This problem happens all version. Our Google Analytics connector and Google Analytics v4 connector both require View ID. But View ID only exist on Google Analytics properties using UA tag. Google Analytics v4 now offers properties with GA4 tag. Properties with GA4 tag don't have View so I cannot use our connectors to pull data. I think we need to update our connector.
I don't know how to create a Github issue though smh.

## Describe the solution you’d like
![image](https://user-images.githubusercontent.com/5154322/134071810-94d6dc0c-b9c5-409d-a92f-8acc6bfa3381.png)
I don't know if only removing the VIEW_ID field as required will work.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by lazebnyi** [comment]
Hi, 

For now, we get reports using method [reports.batchGet](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?hl=en#ReportRequest) which required view id.

You always can enable [Universal Analytics ](https://stackoverflow.com/questions/64510635/how-do-i-get-view-id-from-google-analytics-4).

**Comment by shizlie** [comment]
Hi,

As I understand, with GA4 you won't need View id but only customer reports. Now GA4 seems to become the standard tag for Google Analytics. So I think we need this.

To enable Universal Analytics, they will have to update their website tags or connect property. I am not sure this new UA view will have historical data that was collected by GA4 tags.
So as an analyst myself I cannot change the website code but ask the dev which is quite time consuming.

**Comment by spacecowboy** [comment]
Just to chime in, this is currently blocking us from importing our Google Analytics data as well

**Comment by alexchouraki** [comment]
Same thing for us, I'll be following this ticket!

**Comment by bodschut** [comment]
Yes, we also need this :-)

**Comment by alekseipico** [comment]
Same for us, GA switched to V4 and can not use connector anymore

**Comment by oisidnel** [comment]
Same for us.

**Comment by dwsh** [comment]
Google will begin sunsetting Universal Analytics, and all of UA tags won't work on 23rd July 2023. 
So moving the Google analytics connector from UA to GA4 is a must

**Comment by kmclaugh** [comment]
There should be a different GA4 connector for Airbyte. Despite the name, GA4 is really nothing like UA. It's essentially a completely different product.

**Comment by javier-tarazaga** [comment]
Is there any plans for this to actually happen anytime soon?

**Comment by e-capi** [comment]
Any updates on this issue?

**Comment by tfbecker** [comment]
I asked on slack -> they told me to look at this [thread](https://discuss.airbyte.io/t/ga4-support-without-universal-access-property-from-airbyte/621/2)
bottom line is: no priority - will probably release this when it is more time pressing = closer to july 2023

**Comment by kmclaugh** [comment]
Here's the new [GA4](https://developers.google.com/analytics/devguides/reporting/data/v1) reporting API. Note that it's a completely different API from the Universal Analytics reporting API used by this airbyte connector. As such, we'll need different connector.

In the meantime though, GA4 has a built-in Big Query export that you can use to get it's data into a data warehouse.

**Comment by misteryeo** [comment]
Hi everyone, sorry for the radio silence here. Our team is going to dig in to see how we can fix this and will keep this thread updated!

**Comment by misteryeo** [comment]
For the assignee, now that https://github.com/airbytehq/airbyte/issues/10007 has been closed - let's scope this issue.
