### ISSUE TITLE
default displaySetupWizard to true for cloud

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#6330]
@Jamakase noticed that this value wasn't being set properly.

Currently in OSS we set it to be `true` for the first workspace created/seeded on server startup and false otherwise. For cloud we need to be able to select this option via the api call. This requires adding an optional `displaySetupWizard` to `WorkspaceCreate` in the  OSS API and setting that value in the call made form the Cloud API.

**Comment by cgardens** [comment]
What the consequence of this not being set properly? Is that why the onboarding flow isn't showing up?

**Comment by jrhizor** [comment]
yeah
