### ISSUE TITLE
QA for SSH connectors on Cloud

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6333]
## Tell us about the problem you're trying to solve
SSH is relatively new. We should do some stress testing on them in cloud. Non-postgres Source AND Destination if we've got the infrastructure for it already; otherwise just test postgres.

## QA Checklist
- [ ] - create a new source with a non-postres source. have it connect a database in our infrastructure via a bastion (we already have a bastion).
- [ ] - create a new destination with a non-postgres destination. have it connect to a database in our infrastructure via a bastion (we already have a bastion).
- [ ] run a sync between the two and make sure the data is moved correctly

**Comment by cgardens** [comment]
We had a user use this and confirm that worked.

**Comment by airbyte-jenny** [comment]
Testing infrastructure is unavailable for this as testing was switched to inside docker containers.  This is not testable with our current infra.  Closing as untestable.
