### ISSUE TITLE
Source MSSQL: CDC sync fails with exception `Can't obtain database name`

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6336]
## Enviroment
Is this your first time deploying Airbyte: No
OS Version / Instance: linux / EC2 t2.large
Memory / Disk: 8 GB RAM / 40 GB volume
Deployment: Docker
Airbyte Version: 0.29.2-alpha
Source name/version: MSSQL 0.3.3 (CDC enabled)
Destination name/version: Snowflake
Step: Replication jobs with: CDC & Incremental Dedup + History

## Current Behavior
We’re trying to move to CDC-based replication on existing MSSQL -> Snowflake connectors, so we’ve enabled CDC, snapshot isolation and ensured that primary keys exist for the source table. However, we’re encountering repeated failures when both CDC and incremental: dedup + history are enabled.

Not sure how combinations of these settings are being handled, but this connector succeeds when CDC is enabled on the source and full-refresh is set as the method during source schema discovery/setup.
Logs attached, not sure what to make of them but noticing a failure to validate the JSON schema. Any help would be greatly appreciated

## Expected Behavior
The sync should succeed

## Logs
[mssql_cdc_failed.txt](https://github.com/airbytehq/airbyte/files/7198982/mssql_cdc_failed.txt)

## Steps to Reproduce
1. TBD
2.
3.

**Comment by prateekmukhedkar** [comment]
@sherifnada we made significant improvements to the ms-sql connector and are in process of certifying it. Internal testing, ongoing usage has not surface this error and I am inclined to close the issue.
