### ISSUE TITLE
Source Facebook Marketing: upgrade to v12

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6337]
## Enviroment
Source Version: Facebook Marketing 0.2.17
From [slack convo](https://airbytehq.slack.com/archives/C021JANJ6TY/p1632132231355500)

## Current Behavior
The connection tests failed.
```"FacebookAPIException('Error: 2635, (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v12.0.')"```

## Expected Behavior
Airbyte connector should handle the newest version of the API that was release 4 days ago.

## Logs
![image](https://user-images.githubusercontent.com/5154322/134086100-752875de-7ebd-4342-a7e7-8ecccde62eec.png)

## Acceptance Criteria
1. Verify there are no breaking changes for FBv12
2. If there are none, upgrade the connector and any relevant schemas. If there are breaking changes, consult with @sherifnada to make a decision. 

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

**Comment by Jonas56kdigital** [comment]
Have created a pastebin with the error messages I got when I used the custom connector that works with v12:

https://pastebin.com/raw/nKYw7WNh

What I believe is the key error:

`Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 33, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
    raise e
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 219, in _read_full_refresh
    for record in records:
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 384, in read_records
    yield self.transform(obj.export_all_data())
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 120, in transform
    self.convert_to_schema_types(record, schema["properties"])
  File "/airbyte/integration_code/source_facebook_marketing/streams.py", line 168, in convert_to_schema_types
    elif not isinstance(value, self.get_python_type(schema[key]["type"])):
KeyError: 'type'`

**Comment by Zirochkaa** [comment]
I was able to reproduce KeyError locally:

![image](https://user-images.githubusercontent.com/19872253/135042899-9ffefd90-a502-469e-9646-9ab86a45e2cf.png)

Right now this issue is blocked on #6170.

**Comment by Zirochkaa** [comment]
Tests were fixed in #6170 so this issue is no longer blocked.
![image](https://user-images.githubusercontent.com/19872253/135220236-05b5303a-4cd6-4453-a658-2e5e624717e9.png)

**Comment by Zirochkaa** [comment]
I wasn't able to reproduce `FacebookAPIException` error.
```
(zazmic-airbyte-3.8-dev) ➜  source-facebook-marketing git:(master) /Users/oleh/.virtualenvs/zazmic-airbyte-3.8-dev/bin/python /Users/oleh/Dropbox/work/zazmic/airbyte/airbyte-integrations/connectors/source-facebook-marketing/main.py check --config secrets/config.json
{"type": "LOG", "log": {"level": "INFO", "message": "Select account <AdAccount> {\n    \"account_id\": \"212551616838260\",\n    \"id\": \"act_212551616838260\"\n}"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Check succeeded"}}
{"type": "CONNECTION_STATUS", "connectionStatus": {"status": "SUCCEEDED"}}
```

`check` command worked without any issues.
I'm using source-facebook-marketing with `0.2.18` version and v11 API:
```
(zazmic-airbyte-3.8-dev) ➜  source-facebook-marketing git:(master) pip freeze | grep facebook
facebook-business==11.0.0
```

**Comment by Zirochkaa** [comment]
So I'll just upgrade API to v12, run tests and run `read` command for streams to verify that nothing is broken. Also I'll look at facebook docs for API v12 to check if there are some changes in schemas for streams.
