### ISSUE TITLE
building an integration image (and its underlying code) shouldn't require multiple commands

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#634]
Right now you have to run `build` and then `buildImage` to compile java and then package it into the image. 

One possible solution is to make buildImage gradle tasks depend on their project's build task. Another is to parameterize the build process in some way.

**Comment by michel-tricot** [comment]
The convention is that build generates artifacts so having buildImage to depend on build breaks that convention

**Comment by michel-tricot** [comment]
You could change the issue to describe the observed issue instead a suggested solution

**Comment by cgardens** [comment]
this is completed.
