### ISSUE TITLE
Requesting for New Connector (DynamoDB)

### ISSUE THREAD

**Issue by kailashjoshi018** [airbytehq/airbyte#6342]
## Tell us about the new connector you’d like to have
* Which source and which destination?
DynamoDB

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
NA

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
We store events data in DynamoDB and need to pull the data to Redshift.

* How often do you want to run syncs?
3 hours
* If this is an API source connector, which entities/endpoints do you need supported?
NA
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 
NA

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
Hevo Data / Fivetran / Stitch

## Are you willing to submit a PR?
Sorry, I can't :(

**Comment by misteryeo** [comment]
@kailashjoshi018 closing this issue in favor of a pre-existing request - #3561. Please feel free to subscribe to that issue instead.
