### ISSUE TITLE
Obtain public developer application for the Microsoft Teams source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#6344]
TBD

**Comment by igrankova** [comment]
[EPIC] Oauth developer applications #6070

**Comment by cheyura** [comment]
Done. Access OAuth client https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/ca31436c-4b32-4ed2-8e3b-d48914e18713/isMSAApp/. OAuth flow passed. Use tenant=consumers to reach accounts behind Airbyte Organization
