### ISSUE TITLE
CDK: Add streaming caching functionality.

### ISSUE THREAD

**Issue by yevhenii-ldv** [airbytehq/airbyte#6352]
## Tell us about the problem you're trying to solve
Many connectors have nested streams that depend on the existing parent stream. It would be great to be able to enable caching for the stream, so that when you run it repeatedly, we do not spend time and limit on requests, but receive information from the cache file.
An example of how the stream cache works can be found in the `GitHub` connector.

**Comment by keu** [comment]
@yevhenii-ldv #3380 already solves this

**Comment by yevhenii-ldv** [comment]
@keu thanks, then I'll close this issue..
