### ISSUE TITLE
Source Amplitude: connector throws 404 when dont have any data

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6375]
## Enviroment
OS Version / Instance: EC2 micro.a4
 Memory / Disk: 12Gb / 256Tb SSD
Deployment: Kubernetes Airbyte 
Version: 0.28.1-alpha 
Source name/version: Amplitude 0.1.0 
Destination name/version: Postgres 

## Current Behavior
I'm trying to sync for the first time and the process has been failed due to 404 errors from client api .

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by blotouta2** [comment]
File "/airbyte/integration_code/source_amplitude/api.py", line 160, in read_records
    yield from super().read_records(sync_mode, cursor_field, stream_slice, stream_state)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 228, in read_records
    response = self._send_request(request)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 204, in _send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://amplitude.com/api/2/export?start=20210904T01&end=20210907T00

**Comment by marcosmarxm** [comment]
Hi @blotouta2 from Amplitude [docs](https://developers.amplitude.com/docs/export-api), can you double check the start/end date you'd used?
> 


404 | Request data for a time range during which no data has been collected for the project, then you will receive a 404 response from our server.
-- | --

**Comment by blotouta2** [comment]
Yes, i used start and end date from the current month.

**Comment by sherifnada** [comment]
@blotouta2 and you can confirm there is data in the account?

**Comment by blotouta2** [comment]
<img width="1159" alt="Screenshot 2021-09-24 at 12 03 49 PM" src="https://user-images.githubusercontent.com/71813415/134629078-534cf976-6629-4259-9931-29c5db702446.png">

@sherifnada dashboard shows that we have 256 events since last 1 month
