### ISSUE TITLE
Type mismatch of _airbyte_emitted_at - BigQuery

### ISSUE THREAD

**Issue by tsrancsik** [airbytehq/airbyte#6401]
## Enviroment
- **Airbyte version**:  example is 0.29.13-alpha
- **OS Version / Instance**: GCP n2d-standard-4
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.3.11
- **Destination Connector and version**: BigQuery 0.4.0
- **Severity**: High
- **Step where error happened**: Sync job
- 
## Current Behavior
The job fails due to type mismatch on _airbyte_emitted_at. It used to be timestamp type but the latest connectors would like to load strings.

## Expected Behavior
_airbyte_emitted_at values' type is always timestamp.

## Logs
```2021-09-22 13:12:34 ERROR () LineGobbler(voidCall):85 - Caused by: com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table ... Field _airbyte_emitted_at has changed type from TIMESTAMP to STRING```

## Steps to Reproduce
1. Sync any table from Postgres to BigQuery with the mentioned versions.

**Comment by SrancsikAtBitrise** [comment]
Same issue with different sources.

**Comment by SrancsikAtBitrise** [comment]
Reverting to version 0.3.12 solved the issue.

**Comment by sherifnada** [comment]
@tsrancsik can you try upgrading to the latest bq version? the type should have been fixed now. Feel free to close if fixed.

**Comment by sherifnada** [comment]
resolved
