### ISSUE TITLE
Add `airbyte-worker` in Helm Chart

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6416]
## Tell us about the problem you're trying to solve
after https://github.com/airbytehq/airbyte/pull/5737 you need to use the worker container separate from scheduler. Right now, The Helm chart dont setup the worker.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by jonstacks** [comment]
@marcosmarxm, If you can assign it to me, I should be able to get a PR out tonight.

**Comment by jagannathsrs** [comment]
@jonstacks you might also want to consider #5585  which lets you add taints and nodeSelector for work pods via ENV variables. Thank you for your awesome contribution! :D

**Comment by jonstacks** [comment]
@jagannathsrs,

This should be able to be accomplished by supplying `worker.extraEnv` in the PR above. My hope was to leave this flexible enough that we don't have to do anything to the helm chart when there is a new release of the app that just exposes more config through environment variables. https://github.com/airbytehq/airbyte/pull/6427/files#diff-d60c0e39913dd37ad4be7f921bb25dcc2b732ac351208fcba42bbb1f0d621214R419-R425

**Comment by jrhizor** [comment]
I believe @jagannathsrs is referring to a change that allows customizing taints/node selection for _connector_ pods launched by _worker_ pods, not the worker pods themselves.

**Comment by jonstacks** [comment]
@jrhizor, I might have read the code wrong, but is it correct to say that the workers read the environment variables `WORKER_POD_TOLERATIONS`, etc and uses those when launching the connectors? If so, the PR should cover that use case for passing in extra environment variables with `worker.extraEnv`. If you wanted to set the `nodeSelector` or `tolerations` on the worker pods themselves, you would use `worker.nodeSelector` and `worker.tolerations`, respectively.

**Comment by jrhizor** [comment]
Ah makes sense :+1:
