### ISSUE TITLE
how to run application on intellij without docker as a java application

### ISSUE THREAD

**Issue by Tharaka8999** [airbytehq/airbyte#6430]
I'm trying to modify the MySQL connector but I'm unable to get the updated result.  I tried with Gradle build and docker-compose up it didn't work. so I wanted to know how can I modify the code and get the expected output and debug it.

**Comment by marcosmarxm** [comment]
Hi @Tharaka8999 I recommend to follow this [doc](https://docs.airbyte.io/connector-development/tutorials/building-a-java-destination) to develop locally. If you have any errors please enter our [Slack Community](https://airbytehq.slack.com/join/shared_invite/zt-snz9dnd2-82ukC7C6rPWyattYUks6Xg#/shared-invite/email) and we can help you!
