### ISSUE TITLE
Improve Google Ads Connector to support multiple customer ids

### ISSUE THREAD

**Issue by MariscottiSmile** [airbytehq/airbyte#6437]
## Tell us about the problem you're trying to solve

I need to extract data from multiple Google Ads accounts, but the current version of the Google Ads source only accept one customer id (so just one account). 

## Describe the solution you’d like

I would like the same solution to be implemented as it was for the Google AdWords source: https://github.com/airbytehq/airbyte/issues/2903 . So I want to be able to add a list of customer ids.

## Describe the alternative you’ve considered or used

The alternative is to create one source for each account, but it is quite a repetitive task and it is not lean to maintain in the future.

## Additional context

Google Ads also has manager accounts, so it would be even better to be able to insert only the customer id of the manager account, and be able to extract the data from all the sub-accounts

## Are you willing to submit a PR?

No, I do not have the skills.

**Comment by yevhenii-ldv** [comment]
We have a [custom PR](https://github.com/airbytehq/airbyte/pull/7547) that implemented this functionality, but the contributor abandoned this PR.
It remains to resolve a few comments and finalize the state for several `CUSTOMER ID's`.
