### ISSUE TITLE
Source overview screen should actually describe the source (show host, port at minimum)

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6444]
## Tell us about the problem you're trying to solve
As a user of airbyte, when I click on one of my sources in the list of sources, I expect to see the details of that source.  This way, if my teammate named it poorly or vaguely, or I'm wondering if it goes to the correct (dev/qa/prod) database, I can see at a glance how it's set up and what database it is for.

## Describe the solution you’d like
On the source screen, I'd like to see a (read-only, concise) summary of the important "Settings" values as the first thing in the Overview tab.  It's okay for it to show me the corresponding destination below that, but I clicked on the source because I wanted to see the source, not because I wanted to see the destination.   (This probably has a parallel for the destination page to show destination host/port config, instead of only showing the source.)

## Describe the alternative you’ve considered or used
Right now, when I click on a source, the first thing I see is a destination.  I click on "src-postgres" to figure out which database server that's reading from to, and I see "Destination Name: BigQuery".  That's not what I'm there for.  I'm there to learn about my source.  It took me 3 tries double-checking my click path before I realized that there's also a second tab "Settings" that probably has what I need; and then it's writeable, which is a little scary when all I'm trying to do is identify what server is being used.  Especially in production, I don't _want_ to accidentally change the settings.  I just want to see it tell me which server the source is reading from.  Principle of least surprise: When I drill-down into a source, I want to see details of that source (not first see, to my surprise, its corresponding destination).

Something like this bit in red is what I expect to see.  I mainly care about the "where" component of the config so I can verify that the right database is being used; I can dig into the "how" in the Settings tab if I really need to.
<img width="1186" alt="Screen Shot 2021-09-24 at 4 15 23 PM" src="https://user-images.githubusercontent.com/85510829/134740744-3e905158-e596-4557-9933-151bfbd48eb7.png">

**Comment by nataliekwong** [comment]
Hey Jenny! Just closing the loop here as I've been combing through the backlog. Earlier this year we updated the behavior to match what you've described - clicking on a source shows you the source config rather than the connections!
