### ISSUE TITLE
Dropdown UI for connector config tears away from the relevant field when the mouse scrolls the page

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6448]
## Enviroment
- **Airbyte version**:  0.29.19-alpha
- **OS Version / Instance**: macos, chrome browser
- **Deployment**: docker-compose
- **Severity**: low
- **Step where error happened**: Configuring an S3 source connector's aws region

## Current Behavior
1. Starting creating an S3 source connector.
2. There is a dropdown for aws region.  Click it.  It shows a dropdown.
3. Move the mouse outside of the dropdown, and scroll down on the page behind it.
4. Notice that the dropdown "tears away" from the field it belongs with.
5. Now put the mouse over the dropdown and try to click a selection.
6. Notice that the dropdown "runs away" from the mouse and you cannot click the selection.
7. Then you can try again to mouse over and click a selection, and it will work.

## Expected Behavior
When I scroll the page in step 3, the dropdown should remain attached to its relevant field, and should scroll with the page instead of tearing away.  This would also mean it doesn't run away from my mouse when I try to click a selection.

**Comment by edmundito** [comment]
Screenshot showing what happens after I scroll:
![image](https://user-images.githubusercontent.com/168664/188225984-a0304cdd-bdac-48e5-8631-43403db18c40.png)

**Comment by edmundito** [comment]
@matter-q I tried looking into this issue but one of the challenging things is when dropdowns are inside elements that are set to `overflow: auto`. For example, the dropdowns in the connection streams table because the streams table has a max height set.

Maybe some of these issues could be resolved with #15653

**Comment by matter-q** [comment]
@edmundito Thanks for the information. I have some thoughts to resolve this issue

**Comment by matter-q** [comment]
We need to wait until the task related to updating React Select will be resolved. It could fix the current issue.
