### ISSUE TITLE
QA Cloud Onboarding Flow

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6484]
## Tell us about the problem you're trying to solve
Historically there has been some instability here and we have recently torn up a lot of this stuff, so we need to make triple sure it is good shape.

As part of this process, we should write down exactly the steps we take as part of this QA so that we can synthesize it into a cypress test in Q4.

## QA Checklist
- [x] - as a new user, i am presented with the onboarding flow
- [x] - i am able to complete the full onboarding flow without error
- [ ] - if I close my browser in the middle of the onboarding flow and then come back, i can pick up where i left off in the onboarding flow
- [ ] - ~~if i click "skip onboarding", i never see the onboarding flow again (we don't have a skip onboarding anymore)~~
- [x] - once i have completed the onboarding flow, i never see the onboarding flow again. note: onboarding button stays.

**Comment by sherifnada** [comment]
just checked this, it's not working as intended. Repro steps: 

1. Sign up
2. you will be asked to verify your email. I copy pasted the link for email verification into my browser and visited it. 
3. I was then placed on the "sources" tab. 

When I sign out and back in, I'm not taken to an onboarding flow. When I visit the cloud URL I am also not taken to an onboarding flow, but rather to the sources page. 

When I click the "onboarding" tab on the left explicitly, I am taken to the onboarding flow.

**Comment by jrhizor** [comment]
@tuliren created https://github.com/airbytehq/airbyte/issues/6814 to follow up
