### ISSUE TITLE
QA OAuth

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6487]
It's a new feature! Let's sanity check it works in the UI.

As part of this process, we should write down exactly the steps we take as part of this QA so that we can synthesize it into a cypress test in Q4.

**Comment by cgardens** [comment]
@sherifnada || @ChristopheDuong do you want to create a checklist of what we should be qaing here?

**Comment by ChristopheDuong** [comment]
https://www.loom.com/share/5d093a25552e4a90bcb0f839d375343c?sharedAppSource=personal_library
