### ISSUE TITLE
QA Billing / Usage Metrics 

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6488]
It's a new feature! Let's sanity check it works in the UI.

As part of this process, we should write down exactly the steps we take as part of this QA so that we can synthesize it into a cypress test in Q4.

## QA Checklist
- [x] - as an instance admin i can add credits to a workspace
- [x] - as a user i can see my current credit balance
- [x] - as a user i can see how many credits i have used in the last 30 days

**Comment by subodh1810** [comment]
So I managed to update the credits for a workspace using the script which is point number 1

For 2 and 3 take a look at following screenshot 
<img width="1792" alt="Screenshot 2021-10-05 at 2 38 35 PM" src="https://user-images.githubusercontent.com/28527634/136005017-be3ef0c5-a5c2-4d27-bcb8-3cda38b93b0b.png">
