### ISSUE TITLE
QA Cloud UI Performance

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6491]
In the initial private beta launch, the UI performance was very slow. We have made some improvements. Let's take a look at where we are now. 

## QA Checklist
- [x] - The "get spec" step should always be fast. That is when I select which source or destination I want to use, there is no delay in the form being shown.

**Comment by ChristopheDuong** [comment]
Some tests and recording on speed: https://www.loom.com/share/a7cc60397d084998939c29814555d32f

**Comment by cgardens** [comment]
this has since been fixed by this pr: https://github.com/airbytehq/airbyte/pull/6646. the get spec call is now very snappy!
