### ISSUE TITLE
Source worker container hangs forewever on network partition during read data loop

### ISSUE THREAD

**Issue by amorskoy** [airbytehq/airbyte#6500]
## Current Behavior

With source-file on CSV (HTTPS storage).
If network connectivity to source disappears during read data loop(corresponds to job log lines like `Records read XXX` by DefaultReplicationWorker), it just hangs, connector is alive forever, job state is **Running** even after network is back.

`Strace` capture for the container - seems like endless wait for a futex release over some stale resource (probably tcp socket?):
```
pid 27390] epoll_pwait(4, [], 128, 0, NULL, 824636977728) = 0
[pid 14553] epoll_pwait(4,  <unfinished ...>
[pid 27390] epoll_pwait(4,  <unfinished ...>
[pid 14553] <... epoll_pwait resumed> [], 128, 0, NULL, 0) = 0
[pid 14553] futex(0xc00007f150, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 14548] <... nanosleep resumed> NULL) = 0
[pid 14548] futex(0x5636776c27d8, FUTEX_WAIT_PRIVATE, 0, {tv_sec
```

## Enviroment
- **Airbyte version**:  0.29.17-alpha
- **OS Version / Instance**: Ubuntu 18.04.6 LTS
- **Deployment**: both Docker or Kubernetes deploy env
- **Source Connector and version**: source-file:0.2.6
- **Destination Connector and version**: destination-csv:0.2.8
- **Severity**: Medium (or High, as it is part of retry policies and probably HA)
- **Step where error happened**: Sync job

## Expected Behavior
It looks like there is a couple of issues:
* I am not notified on sync error (or at least job status change expected)
* There is no job continuation - seems that I need manually reset connection?

## Logs
Log attached
[logs-7-0.txt](https://github.com/airbytehq/airbyte/files/7242139/logs-7-0.txt)

## Steps to Reproduce
1. create source - file (https), 68K lines - [procurement dataset](https://data.ny.gov/api/views/8w5p-k45m/rows.csv?accessType=DOWNLOAD)
2. attached destination (local file CSV)
3. started sync job (manual, overwrite, basic normalization)
4. waited until ~40% is downloaded (based on log output Records read: 29000)
5. then just disabled WiFi on laptop. The job remains in a `Running` state.
6. leaving it for a couple of minutes to simulate network issue
7. then I've re-enabled WiFi

Nothing changed, job is still in the same `Running` state, destination file is not updated since then.

## Are you willing to submit a PR?
Not now at least

**Comment by marcosmarxm** [comment]
Thanks for bringing this @amorskoy and already give a way to test it, we need to improve how to handle this type of situation in the worker.
