### ISSUE TITLE
🐛 Source Hubspot: Fix SAT incremental tests

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#6509]
## Enviroment
- **Airbyte version**:  0.1.24
- **OS Version / Instance**: any
- **Source Connector and version**: Hubspot 0.1.16

- **Severity**: Low
- **Step where error happened**: Deploy

## Current Behavior
SAT incremental tests are disable for now because of this error: `'<=' not supported between instances of 'int' and 'str'`

## Expected Behavior
SAT incremental tests should work properly. I suggest to take this issue after a https://github.com/airbytehq/airbyte/issues/5114 (or as the part of https://github.com/airbytehq/airbyte/issues/5114)

## Steps to Reproduce
1. Setup the Hubspot connector
2. Uncomment incremental tests section in `acceptance-test-config.yml`
3. Run acceptance tests

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by vitaliizazmic** [comment]
Data type mismatch in state was fixed in the PR #8699. Also incremental test was uncommented and implemented  supporting of increment sync.
