### ISSUE TITLE
Document the format for SSH key

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6514]
## Tell us about the problem you're trying to solve
We have added support for SSH in postgres source and destination. There are some details to generating a correctly formatted SSH key that are not intuitive / easy to mess up. We need to make sure to add them into our docs.

**Comment by airbyte-jenny** [comment]
Documented in
https://github.com/airbytehq/airbyte/pull/6585

Also improved the wording on the connector setup screens, so the ssh-keygen command is available at point of use.

**Comment by klogdog** [comment]
Airbyte should generate the key. It has the libraries setup to do this and there is no good reason that it cannot generate and store the private key and provide the pulbic key for installs. 

This should be an integrated feature. SSH key auth should also have a password field for those that wish to password protect their SSH private keys.
