### ISSUE TITLE
improve usability of job run page

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#652]
There are number of problems with this page.

- log lines shouldn't be wrapped (we could either extend the width of the page to the entire screen, have side scrolling inside the log view, or both)
- you don't know attempt you are on 
- you can't view logs for different attempts
- it just says Running if it's actually retrying, which is confusing
- it just says Cancelled if it failed at max retries, which is confusing
- time running isn't reliable. I've seen it stuck at 1s for a while.
- cancel button for job for when it's stuck

**Comment by cgardens** [comment]
@jrhizor I'm going to close this issue. I think we have now done all of the things you mentioned except job cancellation. We have a new specific issue for job cancellation here https://github.com/airbytehq/airbyte/issues/1404
