### ISSUE TITLE
🎉 Source Greenhouse: Fill all implemented streams with data

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#6546]
## Tell us about the problem you're trying to solve
For now we have these empty stream in the Greenhouse connector:
`applications.demographics_answers`,
`demographics_answer_options`,
`demographics_answers`,
`demographics_answers.answer_options`
`demographics_question_sets`,
`demographics_question_sets.questions`,
`demographics_questions`
So these are marked as `empty_stream` in the SAT config, so we couldn't properly test them.

## Describe the solution you’d like
We need to find a way on how to fill these streams with data.
 
For the demographic streams it's not clear on how to fill the data. For instance, there is the docs on how to add demographic question set: https://support.greenhouse.io/hc/en-us/articles/360039535731. But there are on `Custom Demographic Question Sets` section at the place where docs mentions it to be.

So I think we need to spend some time trying different approaches on how to fill the data and/or ask the Greenhouse support team for the guidance.

## Describe the alternative you’ve considered or used
No alternatives.

## Additional context
Issue appeared after the new streams were added in https://github.com/airbytehq/airbyte/pull/6377.

## Are you willing to submit a PR?
I will

**Comment by htrueman** [comment]
## Scoping report

To fill the demographics streams data: 
1. Go to https://www.greenhouse.io/ -> Main menu [Inclusion]
2. Configure tools to reduce bias (link with gear icon on the left)
3. Custom Demographic Question Sets -> Add questions

We need to first contact the Greenhouse support team to enable `Custom Demographic Question Sets` as this option is not available for out test account.

See [Custom Demographic Questions](https://support.greenhouse.io/hc/en-us/articles/360039535731-Create-Custom-Demographic-Question-Set), [Create Custom Demographic Question Set](https://support.greenhouse.io/hc/en-us/articles/360004588971-Custom-Demographic-Questions-).

For the `interviews`, `applications.interviews` and `rejection_reasons` there are actually records exist in Greenhouse. We need to schedule some interviews in the future. Past interviews are not returned by the API.

**Comment by htrueman** [comment]
@sherifnada good news, Greenhouse gave us access to the Expert tier. So this issue is unblocked.

**Comment by sherifnada** [comment]
excellent! I'll move it to next sprint, not this one
