### ISSUE TITLE
help links in onboarding (source/dest creation) should open in a new window

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#655]
When you click on an instruction link while setting up a source for example, clicking on the link takes you away from the page and you lose all of the configuration you've entered so far. Ideally these just opens in a different window so you don't lose any work.

**Comment by cgardens** [comment]
@Jamakase - These links come from the backend, so probably we need to change how we write the anchor tags on the backend. Can you tell us what you would need us to do for this to work?
