### ISSUE TITLE
Add button to download airbyte-worker logs in UI

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6553]
## Tell us about the problem you're trying to solve
The latest version of Airbyte (0.29.22+) the scheduler/worker were separated. Some cases for debugging we need the logs that resides in the worker container. 
This depends on: #6554

## Describe the solution you’d like
Add a button in Setting Page to download worker logs too.

## Describe the alternative you’ve considered or used
Ask users to generate a file using `docker logs airbyte-worker > worker.log`

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by jrhizor** [comment]
Are you talking about worker pods or connector pods? Worker pods currently output to the same location as scheduler logs and are available to download from that endpoint. Are you suggesting splitting the scheduler and worker log output endpoints or something else?

**Comment by cgardens** [comment]
added
