### ISSUE TITLE
Create API endpoint to generate/download worker logs

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6554]
## Tell us about the problem you're trying to solve
Use with #6553

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
done
