### ISSUE TITLE
Upgrade to 0.30.1 failed AutoMigration

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6555]
## Enviroment
- **Airbyte version**:  0.29.22-alpha to 0.31.1-alpha
- **OS Version / Instance**: macOS

## Current Behavior
Have an instance 0.29 and tried to upgrade to latest (0.30+ version) and failed
```
Automatic Migration failed
2021-09-29T23:36:47.918000+00:00 airbyte-server/8f5440247217/ java.lang.IllegalArgumentException:
Input data schema does not match declared input schema STANDARD_WORKSPACE.
```

## Expected Behavior
Automigration must work without problem

## Logs
[server.log](https://github.com/airbytehq/airbyte/files/7255611/server.log)

## Steps to Reproduce
1. create a instance using 0.29 version
2. docker-compose down
3. upgrade to 0.30

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by cgardens** [comment]
@marcosmarxm  is this still an issue?

**Comment by davinchia** [comment]
@marcosmarxm bump.

**Comment by marcosmarxm** [comment]
No it isn't anymore.
