### ISSUE TITLE
:memo: Readme.md files: add class hierarchy

### ISSUE THREAD

**Issue by avida** [airbytehq/airbyte#6561]
Recently we introduced bootstrap.md files for giving person that unfimilar with source API and connector implementation logic quick introduction before he/she dives into a code.

It would be great for readability to provide class hierarchy like its done for amanzon [ads streams](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/common.py)

Here is a link to discussion where I tried to generate [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) file hierarchy using pyreverse tool (which is part of pylint package):  https://github.com/airbytehq/airbyte/pull/6550#discussion_r719111162 Perfectly it should be something much simpler like this one for amazon ads:
![image](https://user-images.githubusercontent.com/437607/135422694-86f3c22e-2254-4c98-b4d3-fac3e7b577ae.png)

As an acceptance criteria for this issue I would lilke to have tool for generating ASCII class hierarchy based on pyreverse generated DOT file and put this hierarchy somewhere in the docs (like bootstrap.md of somewhere else).

**Comment by Phlair** [comment]
I would suggest rather than creating a new doc for this, it can go in the README.md.
Wdyt?

**Comment by avida** [comment]
It makes sense, will update an issue title
