### ISSUE TITLE
Snowflake destination: support key/passphrase auth

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6588]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126591210810) by [Unito](https://www.unito.io)

**Comment by sashaNeshcheret** [comment]
We have close [issue](https://github.com/airbytehq/airbyte/issues/12255), that will add non encrypted private/public keys auth to Snowflake, so in scope of this ticket we should add ability for encrypting key and it will applicable only for destination.
