### ISSUE TITLE
Stop attempting to sync if the 2 last syncs failed (so 6 attempts)

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#6593]
Currently, we're attempting to sync whatever the last sync status was, and this is the major thing driving our internal costs high.

@cgardens

**Comment by marcosmarxm** [comment]
This is also a complaint some users from OSS complained about. The solution to this was to add a MAX_SYNC_ATTEMPT env variable where the user can select how many attempts they want. The main reason: sync attempt to failed job consumes API quota.

**Comment by evantahler** [comment]
closing in favor of duplicate https://github.com/airbytehq/airbyte/issues/9673
