### ISSUE TITLE
When setting up Google Analytics v4 as a source, the docs link will link back to the docs for Google Analytics and not Google Analytics v4

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#6598]
<img width="809" alt="Screen Shot 2021-10-01 at 4 49 53 PM" src="https://user-images.githubusercontent.com/68561602/135572069-4b617cb4-763e-41ff-86a8-c04f3e93f7d7.png">

**Comment by sherifnada** [comment]
fixed
