### ISSUE TITLE
Unable to get spec and create source

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#6600]
On Airbyte Cloud, I can't connect the PokeAPI source, as I see an infinite loading wheel. 

<img width="894" alt="Screen Shot 2021-10-01 at 4 56 51 PM" src="https://user-images.githubusercontent.com/68561602/135572570-631b0201-f280-4378-85f1-260c59b98771.png">

**Comment by ChristopheDuong** [comment]
This is not restricted to PokeAPI only.

It also happens on some other connectors too.

**Comment by jrhizor** [comment]
Fixed by @cgardens 

There was a problem with how the bucket cache was reading from GCS. It was trying to read at the root directory when pulling logs for a job.

**Comment by cgardens** [comment]
closed by https://github.com/airbytehq/airbyte/pull/6646
