### ISSUE TITLE
openAPI specification is not working for python get connection endpoint

### ISSUE THREAD

**Issue by Markcial** [airbytehq/airbyte#6604]
## Current Behavior
The generated openAPI code for python is not working for the connection get endpoint because a string field is not marked as optional and the server returns null

## Expected Behavior
Either set the namespace attribute on connection get as optional or have the server return an empty string
</details>

## Steps to Reproduce
1. Generate python openAPI client with: [openAPI generator]
2. Request to the [get connection endpoint]
3. An exception will be thrown about wrong datatype 

## Are you willing to submit a PR?

I don't mind giving some help if pointed with the specific places where to modify

[openAPI generator]: https://github.com/OpenAPITools/openapi-generator#openapi-generator
[get connection endpoint]: https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/connections/get

**Comment by marcosmarxm** [comment]
@Markcial is it possible to share the complete error in the console output?
