### ISSUE TITLE
UI spams API with requests on failure

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6650]
## Current Behavior
* There is an error being throw in cloud where the UI cannot configure Fullstory and the `fileConfigProvider` is throwing an exception. See errors below.
* When these errors appear the UI immediately tries to make a request to the API again. It is spamming the API with 0 wait requests and issuing thousands of requests in less than a minute.

## Expected Behavior
* Need to figure out why Fullstory. Maybe just an env variable missing? If is it what env variable?
* Need to figure out why `fileConfigProvider` is failing
* Need to make sure that when the UI is in a failure state it doesn't fall into a busy loop of spammying requests.
* We will also want to unrevert the commit that jared reverted (see below)

### What we have done so far
* We originally thought a recent UI change was the problem so @jrhizor reverted it out in this PR: https://github.com/airbytehq/airbyte/pull/6644. This did _not_ fix the problem.
* After further debugging this PR: https://github.com/airbytehq/airbyte/pull/6649 fixed the issue. But obviously at a high cost. It just is removing Fullstory and `fileConfigProvider` which is not actually an acceptable solution. Currently the cloud webapp is running off of this PR.

## Log
![Screen Shot 2021-10-01 at 8 29 34 PM](https://user-images.githubusercontent.com/9092207/135725971-1abedb7e-aa41-45b3-92ab-e6feaee1e3a7.png)
![Screen Shot 2021-10-01 at 8 33 47 PM](https://user-images.githubusercontent.com/9092207/135725972-07b81cce-6185-44b5-b129-a2f8a51ab039.png)
![Screen Shot 2021-10-01 at 9 41 07 PM](https://user-images.githubusercontent.com/9092207/135725973-7192bb4c-00f9-46f4-8be7-67b0d56fe55e.png)
s

**Comment by cgardens** [comment]
Reducing the priority here. The issue was that when we were building the webapp we were missing some env variables. We were replacing the file `airbyte-webapp/.env` with the "secrets" in last pass when instead should have been appending to it.

**Comment by Jamakase** [comment]
I believe the root cause of infinite spamming is in ErrorBoundary. We have there a logic for retries. 

We could either try to rerender ui and it will fetch the same again but then we get into infinite loop of rerendering in case of errors or just fail and write like something bad happened.

**Comment by jrhizor** [comment]
I think the fact that we retry is fine, we just need exponential backoff so it doesn't make 500req/s.

**Comment by Jamakase** [comment]
@cgardens

> Need to figure out why fileConfigProvider is failing
 I think its because no config.json was not attached. This error is just a log and it actually doesn't fail the app.

> Need to figure out why Fullstory. Maybe just an env variable missing? If is it what env variable?
something wrong happening with env variables

**Comment by Jamakase** [comment]
> I think the fact that we retry is fine, we just need exponential backoff so it doesn't make 500req/s.

I think it could be not evident for user. Probably its better to fail fast

**Comment by cgardens** [comment]
Fair enough. It doesn't have to be backoff. Can just be an error. The key thing I want to avoid is just pummeling our servers. I actually saw a related issue now. 

During a deploy the UI loses contact with the server (because it is down, which is a separate problem), but while it can't connect or right after the server starts back up it starts attacking the server again. 
![Screen Shot 2021-10-04 at 1 42 29 PM](https://user-images.githubusercontent.com/9092207/135922315-e31174c1-a29e-4249-8090-d3d0dc6672cb.png)
