### ISSUE TITLE
New Source: RingCentral

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#6706]
## Tell us about the new connector you’d like to have
Please support the RingCentral source, this is the only integration that keeps us using Stitch.

## Describe the context around this new connector
dbt-labs have open-sourced the Singer tap at here:
https://github.com/dbt-labs/tap-ringcentral

## Describe the alternative you are considering or using
Stich.

## Are you willing to submit a PR?

No, I'm not familiar with Python.

**Comment by marcosmarxm** [comment]
Thanks @nauxliu for requesting this new source. I added to the roadmap.

**Comment by VasylLazebnyk** [comment]
@marcosmarxm Karina will contact support in order to get OAuth token. Steps in the documentation do not work - we get an error. So now we need more time to find a way how to obtain it. Will keep you posted.

**Comment by karinakuz** [comment]
Sandbox account is created and filled with the data, Oauth credentials are received, added to the LastPass with the name "RingCentral" and tested for the main streams:
- Voice call https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/call-log
- SMS https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/message-store
- Fax https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/fax

**Comment by karinakuz** [comment]
Sandbox account is created and filled with the data, Oauth credentials are received, added to the LastPass with the name "RingCentral" and tested for the main streams:
- Voice call https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/call-log
- SMS https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/message-store
- Fax https://platform.devtest.ringcentral.com/restapi/v1.0/account/703492005/extension/703492005/fax

Schemas
