### ISSUE TITLE
Gracefully handle the case where a connector is exposed in Cloud (and used) but not in Catalog

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6723]
## Tell us about the problem you're trying to solve
In anticipation of the Cloud launch we completed this issue: https://github.com/airbytehq/airbyte/issues/6628 which enforces that the connectors in Cloud are exactly the connectors we want to expose.

One edge case that we may want to handle more gracefully going forward is the case when a connector is in cloud and has a connection (and or source / destination) set up with it. Just deleting the connector definition will be unintuitive to the user and may actually break things (the data model assumes that a definition exists if a source or destination is setup).

We need to through and figure out how we want to handle this case. Roughly the two options seem to be: 
1. don't remove these definitions but warn, which requires manual intervention.
2. remove them automatically and disable associated connections / sources / destinations.

The first might preferable to avoid really catastrophic mistakes where we turn off a ton of connections due to a typo something like that.

@sherifnada wdyt?

**Comment by cgardens** [comment]
(can be a good first issue if we scope out some of the solution details a bit better)

**Comment by sherifnada** [comment]
the ideal outcome would be to keep any connections turned on but remove the ability to add these connectors in new connections and have a separate stream for winding down/sunsetting those connectors. This way even if it was done in error then it's not a catastrophic problem.
