### ISSUE TITLE
MongoDB ssh connection

### ISSUE THREAD

**Issue by guillim** [airbytehq/airbyte#6725]
## Tell us about the problem you're trying to solve
I'm a bit frustrated since SSH connection to Mongo database is not provided yet in the connector.

## Describe the solution you’d like
Similar to what is available in Postgres connector, we could have the option to use an SSH tunnel with mongo as well

**Comment by marcosmarxm** [comment]
The Mongo Connector is in beta stage.
> Beta: While this connector is well tested and is expected to work a majority of the time, it was released recently. There may be some unhandled edge cases but Airbyte will provide very quick turnaround for support on any issues (we'll publish our target KPIs for support turnaround very soon). All beta connectors will make their way to certified status after enough field testing.

I added this issue to the connector Roadmap, @guillim thanks for requesting this!

**Comment by Startouf** [comment]
Hello, any ETA for MongoDB SSH connection ?

**Comment by grishick** [comment]
I filed separate issues for destination and source connectors:
https://github.com/airbytehq/airbyte/issues/17271
https://github.com/airbytehq/airbyte/issues/17272

**Comment by azizwarsi** [comment]
> I filed separate issues for destination and source connectors: https://github.com/airbytehq/airbyte-internal-issues/issues/965 #17272



> I filed separate issues for destination and source connectors: https://github.com/airbytehq/airbyte-internal-issues/issues/965 #17272

Is SSH available for source mongodb connector

**Comment by dixonl90** [comment]
I can't access the connector issue link above to see the status, but the destination connector does seem to have SSH tunnel functionality now. Any progress on the tunnel functionality for a MongoDB source?

**Comment by syedhanicf** [comment]
mongodb source connector is still missing SSH tunnel functionality. Can we reopen this issue?
