### ISSUE TITLE
Cloud Reset password header is incorrect

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#6728]
## Current Behavior
When I try to reset my password after entering my email I see the following: 

![Screen Shot 2021-10-04 at 11 47 25 AM](https://user-images.githubusercontent.com/6246757/135907209-364a2354-c6f2-4241-8b9b-e471c0aa3e56.png)

`confirmRestPassword.yourNewPassword` is not the correct header

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by cgardens** [comment]
confirmed this was fixed.
