### ISSUE TITLE
FrontEnd: display connector version Create New and other pages

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6739]
## Tell us about the problem you're trying to solve
Displaying the current version is useful and helps when you upgrade the connector to make sure you're in the correct version.
![image](https://user-images.githubusercontent.com/5154322/135923018-3a749f44-7ffb-460b-bc9e-4a96aada248e.png)

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by timroes** [comment]
I feel adding a version in this view to the connector would be bloating this view a bit. The version is visible under settings (where the upgrade anyway needs to happen). I'd recommend not adding a version there. @andyjih what are your thoughts?

**Comment by andyjih** [comment]
@timroes Agreed, at least for now. We can better figure out how to get people to use the latest version through other parts of the product.
