### ISSUE TITLE
Destination Snowflake: change tables or have option to select from `transient` to `permament` type

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6743]
## Tell us about the problem you're trying to solve
> Snowflake supports creating transient tables that persist until explicitly dropped and are available to all users with the appropriate privileges. Transient tables are similar to permanent tables with the key difference that they do not have a Fail-safe period. As a result, transient tables are specifically designed for transitory data that needs to be maintained beyond each session (in contrast to temporary tables), but does not need the same level of data protection and recovery provided by permanent tables.

need to do a cost/benefit analysis with a rough effort estimate.
TODO:

differences between permanent and transient tables?
make decision on whether permanent is feasible, maybe with effort estimate. scope what work is needed.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sherifnada** [comment]
copy of https://github.com/airbytehq/airbyte/issues/8681
