### ISSUE TITLE
Connection testing seems unreasonably slow

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6746]
## Enviroment
- **Airbyte version**:  0.30.9-alpha
- **OS Version / Instance**: dev cloud
- **Deployment**: kubernetes
- **Severity**: Medium
- **Step where error happened**: Setting up a source or destination

## Current Behavior
I fill in correct connection details for a postgres source.  The app then tests the connection, but takes an extremely long time doing it, before finally succeeding.  Then it advances to the next page to set up a destination, and it must still (re)validate the source before it lets me proceed.  Then it takes a really long time testing the connection to the destination.

## Expected Behavior

Testing a connection should take less than 3 seconds.  Any long-wait step that's unavoidable in the wizard should happen at the end of manual entry, so it isn't leaving a person sitting and waiting on it.  If a validation check must take time, wait on it until the end of the workflow, and then do all the validations at once, so the user can switch tasks while they wait.  But ideally, connecting to an existing database should not be a slow operation in the first place.

**Comment by cgardens** [comment]
What can we do?
* pod launch issues
* UI - are we testing the source connection twice in a row?
* Does re-testing existing connections help?
* Parallelize checks: https://github.com/airbytehq/airbyte/issues/5268
