### ISSUE TITLE
Clicking "Onboarding" in cloud trapped me in the confirm-verify-email page instead of the onboarding demos

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6747]
Version, dev cloud.

I was signed in and navigating around.  I clicked Onboarding (for the second time) and it went to the wrong place.  I expected to see the training info like I did the first time.  But this second time, it took me to the confirm-verify-email page instead.  Navigating with my browser's built-in back button changes my url, but the page displayed is still the confirm-verify-email visual content, even going several pages back; I'm trapped.

Manually editing my url back to the main dev cloud address works briefly to show the app, though Onboarding is still highlighted in the left menu.  Then redirection kicks in automatically, and I end up back on the confirm-verify-email page again.  (I already verified my email a while ago.)

If I go to dev cloud by editing the url, and quickly click off to a different menu item instead of onboarding, then the app stays up and stops redirecting me to the wrong spot.

Severity: Medium

**Comment by airbyte-jenny** [comment]
Retesting this with a brand new account in an incognito browser window, the bug reproduces still.  This is a breaking bug for newly signed-up users.

**Comment by timroes** [comment]
Closing since the confirm verify email page has been removed.
