### ISSUE TITLE
Docker build instructions for source connectors.

### ISSUE THREAD

**Issue by whereistejas** [airbytehq/airbyte#6771]
Hi,
First things first, this is an awesome project!

I have been trying to build the docker image for postgres using the following command:
```
docker build https://github.com/airbytehq/airbyte/raw/master/airbyte-integrations/connectors/source-postgres/Dockerfile
```

But, I run into the following error:
```bash
Downloading build context from remote url: https://github.com/airbytehq/airbyte/raw/master/airbyte-integrations/connectors/source-postgres/Dockerfile     286B
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM airbyte/integration-base-java:dev
pull access denied for airbyte/integration-base-java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Am I missing something or is that the way it is supposed to be? Thanks, in advance!

**Comment by marcosmarxm** [comment]
Please read our documentation https://docs.airbyte.com/connector-development/tutorials/building-a-java-destination it's not possible to build the connector only running docker build.
