### ISSUE TITLE
Button "Sign Up" from the confirm-email-validation waiting page fails to take me to the Sign Up page

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6780]
]## Enviroment
- **Airbyte version**:  dev cloud
- **OS Version / Instance**: dev cloud
- **Deployment**: kubernetes
- **Severity**: Medium
- **Step where error happened**: Confirm email

## Current Behavior
I filled out an incorrect email address when I filled in the sign-up form.  While waiting on the "confirm your email" waiting page, I noticed my typo.  I wanted to press "Sign Up" button to start fresh and try again.  I pressed the button but it didn't take me to the sign-up form.  I was using mac safari at the time.

## Expected Behavior
Pressing "Sign Up" should take me to the new user sign up form.

**Comment by timroes** [comment]
Closing since this page no longer exists.
