### ISSUE TITLE
migrate oss airbyte to use a separate db table for secrets

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#6806]
We recently added the ability to use GSM as a secrets store for a new Airbyte installation. This causes a lot of branches in code for different behavior or misleading names when retrieving configs that may or may not include secrets depending on the underlying implementation.

A better long-term solution would be to move the OSS version to always split secrets out, even if it is merely a k-v lookup in the database. We could encrypt this based on an env var encryption key, too.

This would allow us to eliminate all of the divergent code paths and also improve security for users that are running OSS Airbyte.

**Comment by cgardens** [comment]
@jrhizor wasn't this done? or should it still be open?
