### ISSUE TITLE
"Current workspace" meaning is unclear when the browser has multiple tabs open to multiple workspaces

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6807]
## Enviroment
- **Airbyte version**:  dev cloud
- **OS Version / Instance**: mac chrome
- **Deployment**: kubernetes
- **Severity**: Medium
- **Step where error happened**: Onboarding

## Current Behavior
When a user has multiple airbyte browser tabs open, and switches workspace in some tab, and then tries to continue with a workflow in progress in another tab, it's unclear what workspace should be used, and what the side effects of the user's actions are, such as if they're currently creating a connection/sync in a workspace.

## Expected Behavior
When the user switches workspace, any other tabs which reference the old workspace should either have their session invalidated, or should clearly and consistently show what workspace they're actually on so the user isn't confused.

**Comment by Jamakase** [comment]
@jrhizor I believe this task is a bit bigger than just fixing the workspace. I think we also need to decide what to do with auth in such case. If the user logs out - should we also log him out in all other tabs?
