### ISSUE TITLE
`EnvConfigs` should only be accessed from main methods

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6828]
## Tell us about the problem you're trying to solve
We have an abstraction called `Configs` that is design to make it easy to pull environment variables for apps. The intention for this abstraction was for us to grab these environment variables in the top level of applications (i.e. in their main method) so that it was very easy to parse where all environment variables are being used. We want to avoid setting the precedent that environment variables can be accessed from anywhere in the code base. Over time, we've slipped and `new EnvConfigs()` is cropping up all over the place. As a refactor, we should push these back up into main methods and dependency inject any variables that we need. 

<img width="1081" alt="Screen Shot 2021-10-05 at 9 03 26 PM" src="https://user-images.githubusercontent.com/9092207/136138917-10ae27c8-6670-4af5-8edb-87d12ffdb875.png">

**Comment by tuliren** [comment]
@cgardens, constructing the `EnvConfigs` is necessary to run the migration to copy the job attempt state to the config database, because the migration from one database needs to connect to another database. There is no way to pass it in from the `main` method, which is controlled by Flyway.
