### ISSUE TITLE
Source MongoDB v2: Query failed with error code 13

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6834]
## Enviroment
Is this your first time deploying Airbyte: yes
OS Version / Instance: Linux EC2 e2-standard-8
Deployment: Docker
Airbyte Version: 0.30.9-alpha
Source name: MongoDB 0.1.1
destination: BigQuery 0.1.4

## Current Behavior
2021-10-06 07:35:24 ERROR () LineGobbler(voidCall):65 - Exception in thread "main" com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on swiftDB to execute command { find: "system.views", readConcern: { level: "majority" }, filter: {}, batchSize: 10000, $db: "swiftDB", $clusterTime: { clusterTime: Timestamp(1633505723, 5), signature: { hash: BinData(0, F75FBAE530F6E59A84B4A99B6D7CF4CCA430A5CD), keyId: 6981424998405636098 } }, lsid: { id: UUID("ea8ea187-17c4-4937-a77d-5a43f2503edc") } }' on server prod-main-shard-00-02-pri.imcen.gcp.mongodb.net:27017

The airbyte can't find system.views collection in Mongo. On reading about it more, I'm finding that even root or dbAdmin don't have access to system.views
https://jira.mongodb.org/browse/SERVER-27554?focusedCommentId=1468276&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#co[…]276
Why are we using system.views to infer schema rather shouldn't we use listCollections to infer schema, so that everyone has access to it

## Expected Behavior
*Tell us what should happen.*

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answe
[logs-7f07ed99-34dc-4094-b705-8a2aa1c2267d-.txt](https://github.com/airbytehq/airbyte/files/7292512/logs-7f07ed99-34dc-4094-b705-8a2aa1c2267d-.txt)
r.

**Comment by callmephilip** [comment]
I am running into this on the latest version (`0.1.19`) of the connector:

```
 Additional Failure Information: com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'not authorized on DATABASE_NAME to execute command { aggregate: "system.views", readConcern: { level: "majority" }, pipeline: [ { $limit: 10000 }, { $project: { arrayofkeyvalue: { $objectToArray: "$$ROOT" } } }, { $unwind: "$arrayofkeyvalue" }, { $group: { _id: null, allkeys: { $addToSet: "$arrayofkeyvalue.k" } } } ], cursor: {}, $db: "inspire", $clusterTime: { clusterTime: Timestamp(1670852783, 1), signature: { hash: BinData(0, EF52FA2B44E6F84D43BB94376F0430FAF9052BD3), keyId: 7114654136603246594 } }, lsid: { id: UUID("8cd43d46-ea90-4632-a33e-30b287470808") } }' on server inspire-stats-shard-00-01.8reja.mongodb.net:27017. The full response is {"operationTime": {"$timestamp": {"t": 1670852783, "i": 1}}, "ok": 0.0, "errmsg": "not authorized on inspire to execute command { aggregate: \"system.views\", readConcern: { level: \"majority\" }, pipeline: [ { $limit: 10000 }, { $project: { arrayofkeyvalue: { $objectToArray: \"$$ROOT\" } } }, { $unwind: \"$arrayofkeyvalue\" }, { $group: { _id: null, allkeys: { $addToSet: \"$arrayofkeyvalue.k\" } } } ], cursor: {}, $db: \"inspire\", $clusterTime: { clusterTime: Timestamp(1670852783, 1), signature: { hash: BinData(0, EF52FA2B44E6F84D43BB94376F0430FAF9052BD3), keyId: 7114654136603246594 } }, lsid: { id: UUID(\"8cd43d46-ea90-4632-a33e-30b287470808\") } }", "code": 13, "codeName": "Unauthorized", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1670852783, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "71L6K0Tm+E1Du5Q3bwQw+vkFK9M=", "subType": "00"}}, "keyId": 7114654136603246594}}}
```

**Comment by SebastienFrantz** [comment]
Same case. 
I have a bench of connections using mongodb but only one bumped into this error. 
I am also running on the latest version (`0.1.19`) and Airbyte is running on Kubernetes on the version (`0.44.5`)

**Comment by callmephilip** [comment]
@SebastienFrantz make sure you are running these using a user with read-only access rights. i believe this was the issue we ran into
