### ISSUE TITLE
Provide official API Client/SDK using swagger codegen.

### ISSUE THREAD

**Issue by dinesh-chander** [airbytehq/airbyte#6861]
## Problem
Currently, If I want to use Airbyte using API interface, I have to create a custom Airbyte Client in my code. A official client will make the job easier.

## Describe the solution you’d like
Provide Airbyte API SDK using swagger codegen (https://github.com/swagger-api/swagger-codegen) for different languages. 

## Are you willing to submit a PR?
No

**Comment by evantahler** [comment]
For now, you can use our [Open API definitions](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml) from and view them in the [Swagger editor](https://editor-next.swagger.io/)

![Screen Shot 2022-08-24 at 10.27.05 AM.png](https://images.zenhubusercontent.com/625848c232857a5abeb89721/8da4d9ed-42ec-4ff2-ba3f-0b4c07a72ccc)
