### ISSUE TITLE
Round value of source attribute with type "integer"

### ISSUE THREAD

**Issue by antixar** [airbytehq/airbyte#6875]
## Enviroment
- **Airbyte version**:  0.30.1-alpha
- **OS Version / Instance**: Fedora 32
- **Deployment**: Docker (docker-compose)
- **Source Connector and version**: source-tiktok-marketing:0.1.0 [PR ](https://github.com/airbytehq/airbyte/pull/5887) with this connector (it is not deployed yet)
- **Destination Connector and version**: any 
- **Severity**: Low

My assumption is that UI or server rounds huge integer values.
![image](https://user-images.githubusercontent.com/11213273/136412507-fdb398d0-7261-41dc-8d2b-3a25f84f5b6b.png)

## Current Behavior
The spec setting for this field:
```
   "app_id": {
       "title": "App Id",
        "description": "The App id applied by the developer.",
        "type": "integer"
   }
```

## Expected Behavior
2 possible results:
- pass value as is
- return a validation error

<details>
<summary>LOG</summary> 
this is debug message. The exception generated a config values. The input app_id value was 99999999999999999
```
TiktokException("AAAA Access token is invalid, when you call access_token or refresh_token api, old token will become invalid. => {'start_date': '2021-01-01', 'access_token': 'ewewew', 'environment': {'secret': 'wererere', 'app_id': 100000000000000000, 'environment': 'prod'}}")
```
</details>

## Steps to Reproduce
  - build the airbyte/source-tiktok-marketing:0.1.0 image
  - add it to a sources' list
  - try to create a new source. with the following settings: Environment = Production, App ID = 1234567890123456789 (or any value >= 99999999999999999)

**Comment by midavadim** [comment]
I have checked spec.py, app_id already has string type
