### ISSUE TITLE
Airbyte-Cloud local dev install does not work

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6881]
## Enviroment
- **Airbyte version**:  0.30.15-alpha
- **OS Version / Instance**: mac os
- **Deployment**: kubernetes via helm
- **Severity**: Medium
- **Step where error happened**: helm install

## Current Behavior
1. I started by nuking the existing kubernetes airbyte oss deployment from my airbyte oss git clone directory: `kubectl delete "$(kubectl api-resources --namespaced=true --verbs=delete -o name | tr "\n" "," | sed -e 's/,$//')" --all`
2. Then I switched to my airbyte-cloud git cloned directory.
3. I ran a helm install and it failed.  ` helm install ab ./infra/kube/airbyte -f ./infra/kube/airbyte/values-local.yaml` with an error `Error: INSTALLATION FAILED: namespaces "jobs" not found` 
4. I tried to create the namespace, which worked.  `kubectl create ns jobs`
5. I tried to run install again. `helm install ab ./infra/kube/airbyte -f ./infra/kube/airbyte/values-local.yaml` 
6. I got an error `Error: INSTALLATION FAILED: cannot re-use a name that is still in use` 
7. I tried to delete the namespace, which worked.  `kubectl delete ns jobs`
8. I tried again on the helm install and got the same error about cannot reuse a name.

## Expected Behavior
A cloud developer should be able to trivially install the application locally for development.

**Comment by davinchia** [comment]
This has been fixed.
