### ISSUE TITLE
Auto Migration process took high memory usage throwing OOM

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6885]
## Enviroment
Environment
OS Version: Ubuntu 18.04
Instance: GCP N.2 medium, 4 vcpu, 16gb ram
Airbyte version: 0.30.15-alpha
Deployment: Docker compose, from source
Severity: Critical
Step where error happened: Upgrading Airbyte from 0.29.22-alpha to 0.30.15-alpha
Current Behavior
When I try to upgrade Airbyte from 0.29.22-alpha to 0.30.15-alpha, the airbyte-server container attempts migration, and reports success for indefinite times until the JVM run out of memory. The server was never responsive to the calls from webapp container.
Expected Behavior
The airbyte server should be up and working.
The logs of airbyte-server / docker-compose.

## Current Behavior
I have an instance of Airbyte and when tried auto-migrate the process throw a OOM.

## Expected Behavior
I dont expected to scale-up my instance only for migrate version.

## Logs
[airbyte-docker-log.txt](https://github.com/airbytehq/airbyte/files/7307902/airbyte-docker-log.txt)

[full-docker-log.txt](https://github.com/airbytehq/airbyte/files/7307905/full-docker-log.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by cgardens** [comment]
I believe @lmossman 's fixes should have addressed this:
https://github.com/airbytehq/airbyte/pull/8609
https://github.com/airbytehq/airbyte/pull/8648
