### ISSUE TITLE
Google Analytics Date Time Issue

### ISSUE THREAD

**Issue by skbalahere** [airbytehq/airbyte#6887]
While we are using Airbyte to pull data from GA to Postgres. The date field in GA is in YYYYMMDD format, but when we see it in postgres it is considered as Text and it has created text column.

**Comment by annalvova05** [comment]
@skbalahere can you please send more information about:

- do you set basic normalization?
- which columns don't transform data to date-time? `ga_date` or some others?

**Comment by annalvova05** [comment]
During investigation and sync with @skbalahere, discovered that the problem reproduces only for custom reports in the `ga_date` column.
