### ISSUE TITLE
Anchor links on https://docs.airbyte.io/ do not work (case mismatch)

### ISSUE THREAD

**Issue by tuttle** [airbytehq/airbyte#6895]
Many, possibly all anchor links do not work on the doc website.

For example on page

https://docs.airbyte.io/understanding-airbyte/basic-normalization

there is an inline link "normalization rules" leading to `#Rules`, which does not exist. Firefox does not jump to `#rules`, which does exist.

**Comment by marcosmarxm** [comment]
@avaidyanatha can you check this issue?

**Comment by marcosmarxm** [comment]
Closing because is working now
