### ISSUE TITLE
Add support for per-stream state to the Airbyte Protocol

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6911]
## Epic
- https://github.com/airbytehq/airbyte/issues/6912

## Tell us about the problem you're trying to solve
We want to add per-stream state support to the Airbyte Protocol. The goal here is that connectors that support pre-stream state will be able to get access to features (e.g. schema evolution). In this issue we must accomplish the following:
* Update the Airbyte Protocol to include per-stream state
* Update the platform to gracefully handle per-stream state. For now there should no functionality change.
* Define the process by which an existing connector can be migrated to support per-stream

**Comment by blake-enyart** [comment]
Hi there,
How difficult would it be to jump in on some feature development for this? We have been tracking this epic for sometime now and would love to be able to contribute to this if there is an entry point to this that won't slow you down too much.

**Comment by cgardens** [comment]
definition of done: 
* new `AirbyteStateMessage` struct merged into master.
