### ISSUE TITLE
[EPIC] Per-Stream State

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#6912]
## Tell us about the problem you're trying to solve
Add support for allowing a user to add or remove a table _without_ needing to resync data

[PRD](https://docs.google.com/document/d/144N5o3HVAuZuuI4f9Ox25QiOKcgm4Ap6nv9ymAExtDQ/edit#)

[tech spec](https://docs.google.com/document/d/1-2O3Kzfg9LIQUK0D1Rlc3WD31pQQ09Zqi2N6jtnBZhk/edit#heading=h.j7xt1bopdf05)

[Designs](https://www.figma.com/proto/etaOkOsnXMoKwbfhCD71kw/WEB-APP-(all)?page-id=33740%3A179711&node-id=34344%3A198325&viewport=393%2C-752%2C0.25&scaling=min-zoom&starting-point-node-id=34344%3A198325&show-proto-sidebar=1)

## Tasks
* https://github.com/airbytehq/airbyte/issues/5317
* https://github.com/airbytehq/airbyte/issues/5315
* https://github.com/airbytehq/airbyte/issues/6911

## Issues affected
* https://github.com/airbytehq/airbyte/issues/6089
* https://github.com/airbytehq/airbyte/issues/3520

**Comment by ksoenandar** [comment]
Hi team, is this in active development? For some source whose underlying object schema continually gets updated, Airbyte doesn't scale all that well as I need to reset the entire connection with all the unrelated tables as well.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Schema Evolution](https://app.harvestr.io/components/0/list/woe8PAqO7)

**Comment by judahrand** [comment]
This is also crucial for us to be able to enable CDC. Our database is very very large and so if we try to run the initial sync for all tables in one go our WAL accumulates to dangerous levels.

**Comment by misteryeo** [comment]
@ksoenandar @blake-enyart @judahrand we're planning on tackling this in the coming quarter - stay tuned!

**Comment by blake-enyart** [comment]
Hey @misteryeo!
Just seeing some feature releases come through that might be related to this. Any updates on timelines for when this might be completed?

**Comment by cgardens** [comment]
Should be out for postgres in the next 2 weeks. All other connectors will follow shortly after that.

**Comment by satyavarma** [comment]
Does this also help in the case of refreshing the schema to get the new columns added in the source(Salesforce) table to an already existing stream?

**Comment by cgardens** [comment]
Yes, it will. We are starting by only rolling it out to postgres. But once we are happy with how that it is working, it'll roll out to all connectors.

**Comment by FilipeAraujo** [comment]
@cgardens @edmundito  sorry to ask if it was already released but do you have an estimation of when this will be released? thanks

**Comment by blake-enyart** [comment]
@andyjih, I just wanted to check to confirm.

Is this closed because the PostgreSQL source now has per-stream state implemented?

**Comment by kyle-cheung** [comment]
is this now released and which version was this pushed to?
@cgardens
