### ISSUE TITLE
Build Stabilization: We should be mirroring external Java packages to a company-controlled mirroring/caching server

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6928]
Current Behavior
Currently, our CI/CD pipeline builds can fail unpredictably due to external server outages beyond our control. 

Expected Behavior
We should be mirroring public Java packages to a company-controlled caching/mirroring server, and modify our builds to pull from there. That mirror server can pull from a public upstream when it must serve an image it hasn't seen yet, but after that it should serve from cache. This is a standard pattern used in many companies to stabilize build pipelines, as well as reduce throttling considerations from external servers.

**Comment by davinchia** [comment]
We do do this for Java. I'm going to close this ticket.
