### ISSUE TITLE
Redshift: Use SUPER type for JOSN columns

### ISSUE THREAD

**Issue by nauxliu** [airbytehq/airbyte#6929]
## Tell us about the problem you're trying to solve
Right now the JSON columns type is `character varying`, change it to the Redshift SUPER type will make JSON queries more convenient and speed up queries.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?
No

**Comment by aforlorncat1** [comment]
Upvoted, related to [#5050 ](https://github.com/airbytehq/airbyte/issues/5050)
