### ISSUE TITLE
Source iterable: Normalisation bug

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#6941]
## Enviroment
OS Version / Instance:20.04.3 LTS, t3.large
Memory / Disk: 8Gb / 90
Deployment: Docker  
Airbyte Version: 0.29.12-alpha 
Source name/version: iterable 0.1.7 
Destination name/version: redshift/0.3.14 
Step: initial sync 

## Current Behavior
initial sync fails. Something during the normalization fails. Either: Normalization executed in 3. or KeyError: 'id'. Logs attached

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
[logs-55-2.txt](https://github.com/airbytehq/airbyte/files/7319764/logs-55-2.txt)
your long log
output here

```

[logs-58-0.txt](https://github.com/airbytehq/airbyte/files/7319765/logs-58-0.txt)
</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by sherifnada** [comment]
this seems to be an issue with how normalization interacts with the schema output by the connector. My guess is that PK is not declared correctly on one of the iterable streams.

**Comment by sherifnada** [comment]
Next steps: setup iterable with incremental-dedupe and verify if this issue appears

**Comment by sherifnada** [comment]
Next steps: setup iterable with incremental-dedupe and verify if this issue appears

**Comment by yevhenii-ldv** [comment]
Hi @harshithmullapudi!
I investigated this issue and found that the error is not reproducible at this point in time (I used the `Iterable` connector version `0.1.13`).
In the older version (namely, the one that you indicated as used) for streams with the `email_` prefix, the Primary Key was indicated as `id`, but in version `0.1.9` this was fixed, and now there should not be a similar problem.
Could you please update the version of the Iterable connector to the current one (namely, to `0.1.13`) and try to start the synchronization again, and inform me about the result of the synchronization please.

**Comment by harshithmullapudi** [comment]
Hey @yevhenii-ldv I tried it with latest and was not able to reproduce it anymore. Thanks for checking it out. 👍🏻 . I am closing this.
