### ISSUE TITLE
Add option to set specific sync time instead of simply frequency for 24 hour sync.

### ISSUE THREAD

**Issue by jwilsie** [airbytehq/airbyte#6983]
## Tell us about the problem you're trying to solve
Setting a daily (or even multiple daily) sync events at very specific times to automate report creation with updated data.  Currently to set a 24 hour update frequency at a specific time in airbyte, one has to set it to 24 hour frequency and manually run the sync at that time.  If that needs to run at 3:30AM, the initial sync must be manually kicked off at 3:30AM.

## Describe the solution you’d like
If 24 hour frequency is selected, allow a time picker to schedule when the sync should take place. Adding multiple daily sync events on a schedule would also be useful.

**Comment by maxgmaxg** [comment]
Is this being worked on? It would be a very useful feature.

**Comment by marcosmarxm** [comment]
Close as duplicate of #2170

**Comment by kyleprier** [comment]
Is this feature going to be added? It's super annoying to have to manually kick off a job at nite to schedule a daily job

**Comment by marcosmarxm** [comment]
Yes it was added to latest version of Airbyte, please choose CRON method.
