### ISSUE TITLE
Airbyte on Graviton2 (ARM based AWS EC2 instance)

### ISSUE THREAD

**Issue by welly87** [airbytehq/airbyte#6986]
Hi All, 

Currently i'm trying to port airbyte to graviton2 (arm64) and fix a couple of issues. However some of test that use mockito failed as i upgrade to Java 17 and latest gradle version. 

As i can't find Java 14 distribution on arm68 in openjdk archieve. And i don't want to take times to recompile JDK. 

The repo is here

https://github.com/weltam/airbyte/tree/gv2 

You can find notes on some issues and action taken from this folder

https://github.com/weltam/airbyte/tree/gv2/graviton2

It still need tidying up for sure. It's quite a long journey. 

https://github.com/weltam/airbyte/commits/gv2

I understand if this not a priority for now. Feel free to check the repos

Cheers

**Comment by marcosmarxm** [comment]
Did you try to install jenv? There are some problems using Java 17 because blocks using Gradle 7+.
@tuliren / @jrhizor any additional info here?

**Comment by davinchia** [comment]
@jrhizor is this done?
