### ISSUE TITLE
In demo app, the GitHub connection is marked as successful while it's failing

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#6990]
On https://demo.airbyte.io/connections, you can see that the connections with "Github native..." is in green light. 
But if you drill down in the connection - https://demo.airbyte.io/connections/60c3d6d3-c8ad-453e-9d53-cbba04c47762 -, you will see that all syncs fail. 

cc @marcosmarxm

**Comment by michel-tricot** [comment]
Do we care about the fact that it is syncing right now?

**Comment by marcosmarxm** [comment]
> Do we care about the fact that it is syncing right now?
I would like to have the icon, for users with a large number of connections, this can be helpful to know what sync is in the running step. Why? There is a limit of parallel runners and sometimes you can see a connection in Pending state and need to figure out what connection is blocking it.
