### ISSUE TITLE
Source S3 - CSV with no header

### ISSUE THREAD

**Issue by iamzjk** [airbytehq/airbyte#7012]
## Tell us about the problem you're trying to solve
We are trying to load CSV files from S3 into our Redshift. These CSV files don't have a header row. Airybte is reading the first data row as headers, and there is no option to configure this with the current connector.

## Describe the solution you’d like
Source S3 uses Pyarrow, which has a way to specify `column_names` in [`ReadOptions`](https://arrow.apache.org/docs/python/generated/pyarrow.csv.ReadOptions.html#pyarrow.csv.ReadOptions)
In the [current source-s3 code](https://github.com/airbytehq/airbyte/blob/1773e41e47a69d22a1c575bb8a13f34aa4ed06a7/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/csv_parser.py#L31), we only allow passing `block_size` and `encoding`.
We can either:
- add `column_names` option
- or allow passing in `json_schema` like what we do now with [convert options](https://github.com/airbytehq/airbyte/blob/1773e41e47a69d22a1c575bb8a13f34aa4ed06a7/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/csv_parser.py#L47)

## Additional context
![Screen Shot 2021-10-13 at 12 23 37 PM](https://user-images.githubusercontent.com/11445672/137175869-1461433c-6da7-4f76-b96e-466a0462b00b.png)

## Are you willing to submit a PR?
Yes, if the Airbye team can agree upon the solution, I'm willing to submit a PR for this.

**Comment by sherifnada** [comment]
solved in https://github.com/airbytehq/airbyte/pull/7058
