### ISSUE TITLE
CI Sandbox for OneSignal

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7028]
## Tell us about the problem you're trying to solve
We need credentials to run integration tests for communty contribution https://github.com/airbytehq/airbyte/pull/6998

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by igrankova** [comment]
@marcosmarxm, we have creds in LastPass: onesignal.com. Is this account suitable for test purposes?

**Comment by igrankova** [comment]
the integration is merged
