### ISSUE TITLE
CI Sandbox for Freshservices

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7029]
## Tell us about the problem you're trying to solve
We need integration account to test communitu contribution for https://github.com/airbytehq/airbyte/pull/6967

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
created sandbox account with data, received token for api, added to LastPass with name 'Freshservice', tested api for streams:
Agents 
Assets 
Changes 
Locations 
Problems 
Products 
Purchase orders 
Releases 
Requesters 
Software
Tickets 
Vendors

**Comment by Zirochkaa** [comment]
@karinakuz what about `domain_name` field? I see that in LastPass you added only `API key` field.
Could you please update `freshservices source test creds` with creds (`domain_name`, `api_key`) to our sandbox account? Right now there are creds for the contributor's account.
![image](https://user-images.githubusercontent.com/19872253/140546909-84263443-2643-4ecc-b353-04615be77d7c.png)
