### ISSUE TITLE
CI Sandbox for Retently

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7030]
## Tell us about the problem you're trying to solve
We need CI sandbox for Retently https://github.com/airbytehq/airbyte/pull/6966

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
7-days free trial account is created (for using API account should be with Professional tariff plan: $239 / per month, paid yearly), sent request for the sandbox, received api key, filled account with the data, tested api for:
- Customers https://app.retently.com/api/v2/nps/customers
- Feedback https://app.retently.com/api/v2/feedback
- Outbox https://app.retently.com/api/v2/nps/outbox
- Templates https://app.retently.com/api/v2/nps/templates
- Reports https://app.retently.com/api/v2/reports
Companies and Campaigns are not available for trial.
