### ISSUE TITLE
[EPIC] Source DB Benchmark Tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7035]
## Tell us about the problem you're trying to solve
As part of making our databases more reliable, we should start working on a test suite containing benchmarks for validating that our DB connectors are able to serve certain workloads/scales. 

The idea is that today, we see a lot of issues around DB replication that we cannot reproduce (doc containing [example of problems](https://docs.google.com/spreadsheets/d/1E-fo4EE4pTAJFz3Kfsa347PjAir22CsYpohaYPieVSo/edit#gid=0)) so we want to create a test harness specifically for reproducing this style of test. I have not thought about what shape it should take. 

Suggested benchmarks are available in the Q4 prios doc: 

https://docs.google.com/document/d/17EcJClZBJ-2Sa4HgmeD4rxgZ8aozi7B5squ9TjX_QRQ/edit#heading=h.v66ysrgf09i3

## Describe the solution you’d like

- [x] #8243 
- [x] #8712
- [x] Analyze possible bottleneck
- [x] #7489
- [x] Create an RDS instance
- [x] #8048

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by tuliren** [comment]
MVP baseline results:

<img width="693" alt="Screen Shot 2021-12-06 at 15 52 11" src="https://user-images.githubusercontent.com/1933157/145260339-df6104ab-9b8e-45c8-934e-98a98ffb5a36.png">

**Comment by tuliren** [comment]
Closed with #8215
