### ISSUE TITLE
Apply for complete public access for google search console

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7037]
We need to apply for the google oauth scope: `https://www.googleapis.com/auth/webmasters.readonly` and get it approved by Google on our Google Cloud production environment. 

For our unblocker team to manage this, we need to give them access via terraform to our environment. This is currently in progress via this PR https://github.com/airbytehq/airbyte-cloud/pull/1519

Once they have access, they should be able to use their emails to access the appropriate Google Cloud project via https://console.cloud.google.com/ and apply for access to the appropriate scopes. 

Steps to do this are: 
1. Deploy Google Search Console to Airbyte Cloud (you'll need help from an engineer to do this) **with** full oauth credentials. Make sure this works on dev first before adding it to production. If it helps to add more engineers to our GCP environments, please make a request with the infra team to do this. 
1. **Immediately** following the step above In the dev/staging/prod environments, request the scope above via [this page](https://console.cloud.google.com/apis/credentials/consent/edit?project=prod-ab-cloud-proj) (this page points to the prod env). It's very important to do this as soon as possible after the step above, otherwise the connector will be broken in production. It's not necessary to immediately get approval (that will take some time) but it's important to **request** the scope as soon as possible after deploying the connector because it will allow us to serve up to 100 users in production until our request is approved, which should be more than enough time.
2. Go through the approval process. Once we get approved and the app is working in production, this ticket should be considered completed.

**Comment by ycherniaiev** [comment]
@sherifnada @baz @alexandertsukanov  Please be informed that GCP has several kinds of scopes: sensitive,non-sensitive and restricted. Last two need approval from Google, but first doesn't. The scope you mentioned "https://www.googleapis.com/auth/webmasters.readonly" is non-sensitive and doesn't need approval. Can we close this issue now?

**Comment by sherifnada** [comment]
up to python team -- if needed permissions are available then sounds good w me
