### ISSUE TITLE
Airbyte Cloud Connector Health dashboard, alerting, and debugging story

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7042]
## Tell us about the problem you're trying to solve
We want a way of: 

1. Having clear visibility on success rates for all connectors in Airbyte Cloud
2. taking proactive remedial action when a connector experiences failure (whether it's a widespread failure for many users or a particular failing connector). 

Some things to think about here are going to be: what is an engineer's monitoring/alerting/debugging path? how do they know something is wrong? How can they react? What should our remediation approach be for widespread vs contained (but consistent) failures? 

## Describe the solution you’d like
the output of this ticket should be a short RFC containing both product requirements/goals and some technical ideas to help orient us towards a solution. Implementing the solution will (mostly) immediately follow the RFC.

**Comment by girarda** [comment]
we have:
- sentry
- pages
- health dashboard in metabase

Further improvements can be tracked in more specific issues
