### ISSUE TITLE
CDK: Create common pydantic models to be used in spec, OAuth config and stream schemas

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#7048]
## Tell us about the problem you're trying to solve
To avoid code duplication and prevent copy-paste errors it would be nice to have shared pydantic models.

## Describe the solution you’d like
model should support proper nullable values
remove title if necesary
support internal configuration options
It should be possible to specify spec model for the Source.
If you do the actual pydantic object will be passed as the config instead of raw python dictionary.

## Describe the alternative you’ve considered or used
Do it manually everytime

## Are you willing to submit a PR?
yes

**Comment by sherifnada** [comment]
moving away from pydantic in favor of JSON to allow non-engineers to contribute to specs
