### ISSUE TITLE
Source Stripe: allow connected accounts sync

### ISSUE THREAD

**Issue by scott-schubert** [airbytehq/airbyte#7057]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

We operate a marketplace where buyers interact with sellers and make payments through Stripe. We have onboarded 300 brands onto Stripe and want to import all Stripe data from all connected accounts. Presently, we would have to create one connector per connected account in order to sync that data.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see
We would like to sync all data from connected accounts through a single Stripe connector, providing a single account ID and restricted secret key. 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.
We might be able to do this through the Airbyte API, but haven't tried that out yet.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sherifnada** [comment]
this is supported

**Comment by meshuamam** [comment]
@sherifnada maybe i'm misunderstanding, but from what i see, the stripe connector for balance transactions will do one of the following:
1. Fetch the balance transactions on the "top" account level if we don't supply an account id
2. Fetch the balance transactions for a specific connected account if we supply an account id

so for 300 connected accounts, someone would need 300 different connections, defined manually, isn't it so?

**Comment by predam** [comment]
@sherifnada Can you provide more details on how it is supported? I couldn't find any information

**Comment by rjoelnorgren** [comment]
@sherifnada, I am unable to sync payouts from connected accounts. I do however see many accounts coming through https://docs.stripe.com/api/accounts/list. Any idea what is wrong?

**Comment by rjoelnorgren** [comment]
Following up with information from Airbyte support, connected accounts are not (fully?) supported. I think the docs on the connector should make this limitation clear, as it's a really common use case. For any platform of a meaningful size, the proposed workaround is simply not viable.

> Currently, the Airbyte Stripe Connector does not natively support pulling payouts for connected accounts in a single connection. While the Stripe API does allow access to connected accounts' data using the account parameter, Airbyte requires separate connections to be set up for each connected account. Each connection would need its own API key or OAuth token specific to the connected Stripe account.
