### ISSUE TITLE
Link Airbyte Cloud status page to Airbyte Cloud Webapp.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#7072]
## Tell us about the problem you're trying to solve
We now have a status page at status.airbyte.io. We should link this within the Webapp. Maybe by the sidebar?

## Describe the solution you’d like
It should be easy for a user to navigate from the webapp to the status page.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment]
@johnlafleur will leave the design up to you!

**Comment by davinchia** [comment]
@Jamakase I see this has been in review for a while now. What's the status here?

**Comment by Jamakase** [comment]
@davinchia there is small problem with sidemenu positioning which I need to address. I will make sure that it is merged today.
