### ISSUE TITLE
Source S3 - Add start_date option

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#7075]
## Tell us about the problem you're trying to solve
Currently the S3 source will always start at 1970 (i.e. from the earliest ever files in the bucket). It would be good to allow the user to optionally input a custom start_date for their connection.

## Describe the solution you’d like
Implement an optional start_date parameter in source-s3 (probably more specifically within abstract-files-source) that is used as the base cursor value if no state is present (on first sync or a full refresh).

**Comment by artem1205** [comment]
Added in https://github.com/airbytehq/airbyte/pull/25010
