### ISSUE TITLE
Fully remove deprecated connectors in Cloud

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7082]
## Current Behavior
 During the Cloud private beta, we let users pick any connector in our catalog.
 Later on, we realized we shouldn't have allowed using connectors whose platforms required oauth
 But by that point, some users were already leveraging them, so removing them would crash the app for users
instead we'll filter out those connectors from this drop down menu, and retain them in the backend
 This way, they will not be available for usage in new connections, but they will be available for users
 already leveraging them.

the current situation is confusing because users can see these on the admin page but not in the connector drop down menu: 

![image](https://user-images.githubusercontent.com/6246757/137529782-a585da77-1277-4de1-b0bf-ffa0d6e59dee.png)
![image](https://user-images.githubusercontent.com/6246757/137529807-fe68bef0-8fcd-40c8-ad73-451721c6e7f3.png)

The full list of connectors is available [here](https://github.com/airbytehq/airbyte/commit/d232c0233e3e66c51c42d5bf7145c810b833d5a0#diff-1727cb7855798711b88cadcb42142934a2e9c43aea862a28913a9d34b6a0802dR91)

## Expected Behavior
Once the connectors become available in cloud, change user configuration to leverage the new connectors and one by one, remove the deprecated connectors from the connector list and the DB. This will probably require some manual DB querying to fix things.

**Comment by girarda** [comment]
connectors can be fully hidden either from the FE or by configuring them as [private](https://internal-docs.airbyte.io/runbooks/enable-private-connectors-for-workspace)
