### ISSUE TITLE
Incorrect link to BigQuery docs

### ISSUE THREAD

**Issue by mik-laj** [airbytehq/airbyte#7103]
### Tell us about the documentation you'd like us to add or update.

Here we have incorrect link. 
https://github.com/airbytehq/airbyte/blob/4c0d1a039983a135823d69a222fc2fad82cdb1ad/airbyte-integrations/connectors/source-bigquery/src/main/resources/spec.json#L2
https://github.com/airbytehq/airbyte/blob/4c0d1a039983a135823d69a222fc2fad82cdb1ad/airbyte-integrations/connectors/source-bigquery/src/main/resources/spec.json#L26
We should do the following change
```
-https://docs.airbyte.io/integrations/source/bigquery
+https://docs.airbyte.io/integrations/sources/bigquery
```
### If applicable, add links to the relevant docs that should be updated
As above

**Comment by harshithmullapudi** [comment]
Hey @mik-laj is it possible to contribute for this ?

**Comment by marcosmarxm** [comment]
The issue was fixed already.
