### ISSUE TITLE
oAuth backend for lever-hiring source

### ISSUE THREAD

**Issue by avida** [airbytehq/airbyte#7110]
Part of #7000 story

Implement lever-hiring  oauth backend and do e2e test.

**Comment by eliziario** [comment]
https://github.com/airbytehq/airbyte/pull/7677

**Comment by sherifnada** [comment]
@eliziario removing this from the sprint until we prioritize it for airbyte cloud

**Comment by eliziario** [comment]
Preparing it for the demo, doing e2e testing found some issues on streams auth
