### ISSUE TITLE
Instrument the worker.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#7155]
## Tell us about the problem you're trying to solve
Emit 50/85/95/95 percentile time taken to create new Kube pods. 

See [tech spec](https://docs.google.com/document/d/1IkO2VsrRdJnZJ6bb8ZyrwyzKXc2U9UkEzVryunfVzLM/edit?usp=sharing) for more details.

## Describe the solution you’d like
A Datadog metric is added to the [GKE apps dashboard](https://app.datadoghq.com/dashboard/e76-ez9-zff/gke-apps-dashboard?tpl_var_gke-env=stage-gke-cluster&from_ts=1634180476027&to_ts=1634213828048&live=false).

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment]
https://github.com/airbytehq/airbyte-cloud/wiki/Custom-Metrics

**Comment by airbyte-jenny** [comment]
> Emit 50/85/95/95 percentile time taken to create new Kube pods.

This seems like it's conflating two things - the time taken to create a particular pod, versus the aggregate analytics across many pods.  We should be emitting raw data, only.  Aggregates get calculated in an analytics or dashboarding tool with the ability to set begin and end timestamps, filters, and other query details.

I'll take this to mean "Emit the amount of time taken to create new pods" with the understanding that percentiles are calculated later.

**Comment by airbyte-jenny** [comment]
https://github.com/kubernetes/kube-state-metrics looks like it might solve this for us in batch.

**Comment by davinchia** [comment]
This is done.
