### ISSUE TITLE
pre-install kubectl / helm / socat on kube build ami

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7176]
Most of the remaining issues with the Kube build (as documented in https://docs.google.com/document/d/1QWG7BxUc5ddR1sKs5nJYAedshP7R9gxVp2I55XULklg/edit) are related to items that we could pre-package in the AMI.

Socat install failures:
```
socat install failed with E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2586 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

Kubectl install failures:
```
Service 'worker' failed to build: The command '/bin/sh -c curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.14/bin/linux/amd64/kubectl' returned a non-zero code: 137
```

We still have occasional cases where we get an `IncompleteRead` or where everything fully stalls -- we still don't have leads on those issues.

**Comment by cgardens** [comment]
@jrhizor have we looked into whether there is some other existing AMI that people use for this that has the deps we need? i know when we talked last week, we both felt like this should be a somewhat common use case.

**Comment by davinchia** [comment]
This is done.

<img width="1079" alt="Screen Shot 2022-04-05 at 5 24 37 PM" src="https://user-images.githubusercontent.com/9772859/161723143-2e789c91-32b6-4537-94be-724ad5e43d8c.png">

**Comment by davinchia** [comment]
There are no more install command in our main build script as of this comment.

**Comment by cgardens** [comment]
nice!
