### ISSUE TITLE
Airbyte API: tag endpoints with the version they are released in

### ISSUE THREAD

**Issue by hbd** [airbytehq/airbyte#7185]
### Tell us about the documentation you'd like us to add or update.
This is a feature request for the API docs. I'd like endpoints to be tagged with the version of Airbyte they were introduced in. Especially when working with the various search endpoints more recently, this would be super helpful.

Example: 
![image](https://user-images.githubusercontent.com/6836886/137976372-813f2999-bebe-4eca-822a-c2c32060c383.png)

Note the version number next to the endpoint title.

### If applicable, add links to the relevant docs that should be updated
Anything in the API docs, e.g. https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/sources/search

**Comment by marcosmarxm** [comment]
The Airbyte API solves the issue as the API is versioned.
<img width="783" alt="image" src="https://github.com/airbytehq/airbyte/assets/5154322/08e88bdd-8d80-4177-a2a0-f703aa98fbbf">
