### ISSUE TITLE
Postgres timestamp with time zone is parsed as string

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#7187]
## Enviroment
- **Airbyte version**:  `0.30.20-alpha`
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: `airbyte/source-postgres:0.3.11`
- **Destination Connector and version**: `airbyte/destination-postgres:0.3.11`
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
- Slack [thread](https://airbytehq.slack.com/archives/C019WEENQRM/p1634317376002800).

## Expected Behavior
- Postgres `timestamp with time zone` should be parsed as a timestamp.

## Logs
N/A

## Steps to Reproduce
N/A

**Comment by subodh1810** [comment]
This is a very old issue and I think we have changed how we handle timestamp data type so this should be fixed, closing this
