### ISSUE TITLE
Airbyte Logs end at 100000

### ISSUE THREAD

**Issue by chandininekkantti** [airbytehq/airbyte#7189]
## Enviroment
- **Airbyte version**:  example is 0.30.20-alpha
- **OS Version / Instance**: GCP c2 , 128GB memory
- **Deployment**:  Docker 
- **Source Connector and version**: Snowflake
- **Destination Connector and version**: GCS
- **Severity**: Critical
- **Step where error happened**:Sync job 

## Current Behavior
- Trying to sync very large 1TB dataset and the job  has been running for more than 2 days and noticed the logs are stuck at 1000000. In other words, the job is still running and airbyte is not able to log more than 1million entries in to the log file.  I have replicated it on different machine and the behavior is same. 

## Expected Behavior
- Expect to see the logs.

**Comment by evantahler** [comment]
Is this issue still occuring?

**Comment by evantahler** [comment]
I'm closing this issue because we haven't heard back from the original poster in a few months.  Please let us know if you are still seeing this problem.
