### ISSUE TITLE
No data is persisted when running source and destination when running connector image directly

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#7196]
## Enviroment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
- Slack [thread](https://airbytehq.slack.com/archives/C01VDDEGL7M/p1634400483280600).

## Expected Behavior
- We should be able to run source and destination connector images without the Airbyte server.

## Logs
- See the slack [thread](https://airbytehq.slack.com/archives/C01VDDEGL7M/p1634400483280600) for logs.

## Steps to Reproduce
- Run the script [here](https://gist.github.com/mik-laj/8ef52fa9d8895400086b0a6d78403026).

**Comment by mik-laj** [comment]
@tuliren Have you had time to look at it?

**Comment by gdberrio** [comment]
I seem to be having the same issue as described above, with the Google Ads Source and Postgres Destination.
On the source side, everything works fine:
docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests sigma-google-ads read --config /secrets/config.json --catalog /integration_tests/test_catalog.json > data.json

The data.json has all of the data I requested. My assumption was then, from reading the docs, that I could pipe the data.json to the destination connector and use it to send the data to postgres:
cat data.json | docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/sample_files:/sample_files postgres-airbyte write --config /secrets/config.json --catalog /sample_files/configured_catalog.json

The connector creates the table in Postgres, but is empty.

**Comment by gdberrio** [comment]
Found the issue with my code... I forgot the -i flag to allow docker to get the stdin stream I was piping.
