### ISSUE TITLE
🚀 Source Azure Table Storage:  create dev app and sandbox credentials 

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7203]
## Tell us about the new connector you’d like to have

For the Azure Table Storage source, we should create sandbox credentials as described here and add them to lastpass.

This will be in preparation for #7095

**Comment by karinakuz** [comment]
Received OAuth access token (in LastPass 'Azure Table Storage'), added table, got table data through api:
https://airbyteteststorage.table.core.windows.net/Test
