### ISSUE TITLE
Encapsulate template generator code via Gradle

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#722]
## Tell us about the problem you're trying to solve

#700 introduced autogeneration of new modules via Plop. We'd like to bring this in line with our other JS modules by having it be launched completely from Gradle, with a setup similar to that of `airbyte-webapp` that encapsulates the JS version in gradle dependencies. This will also allow us to make changes to the template module without having to impact how end users leverage it.

**Comment by cgardens** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/725
