### ISSUE TITLE
Facebook Marketing: Incremental/Deduped mode probably should be removed / Airbyte: Support the concept of a "version field"

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#7224]
## Enviroment
- **Airbyte version**: 0.29.19-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.19
- **Destination Connector and version**: BigQuery 0.4.0
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
The Facebook Marketing connector allows you to choose the "Incremental / Deduped + history" mode for the `ads_insights` streams.  We attempted to sync the `ads_insights` stream in this mode, using [`ad_id`, `date_stop`] as the primary key, because there should be one record of daily metrics for each ad.  But when we run the sync, we get lots of redundant records with the same `ad_id` and same `date_stop`.

## Expected Behavior
What we really want is to just keep the most recently retrieved version of each record.  But it appears there is no way to express that in Airbyte, because we are required to choose a cursor field, and it doesn't look like there's any field provided by the Facebook API that would be suitable as a cursor field.  In other words, we don't want it to "overwrite any existing record with the same primary key if the cursor field is greater"; we just want it to "overwrite any existing record with the same primary key every time".

A look at the source code for the `source-facebook-marketing` connector shows that the `cursor_field` for this stream is `date_start`.  That works for "Incremental / Append" mode, but doesn't work for "Incremental / Deduped + history" mode.

So the course of action I would suggest is:

1. For now, just remove the declared support for "Incremental / Deduped + history" mode, for `ads_insights` and all similar streams.

2. Figure out how to add support for "Incremental / Deduped + history" mode that uses the `date_start` value as a cursor to decide which data to fetch, but doesn't use it as a cursor to decide what data to overwrite.  Maybe this is a new sync mode, or a toggle option on the existing sync mode.  Or, for the best flexibility, instead of two field settings (primary key and cursor field), have three field settings: primary key, fetch cursor, and version, where the version field can be any ordinal type, and the deduplication process keeps the copy with the largest version.  So in this use case, the primary key would be [`ad_id`, `date_start`], the fetch cursor would be `date_start`, and the version field would  be `_airbyte_emitted_at` (or nothing).

**Comment by sherifnada** [comment]
@zestyping is this issue due to an attribution window? e.g: if the attribution window is 28 days, the connector always retrieves data from the past 28 days no matter what. So if the sync runs once per day, I would expect records for any given date to show up once per day for the next 28 days. Also, are the values coming in these records actually different, if you know? (I suppose if the issue is that there is no deterministic ordering of always keeping the latest version and it just overwrites randomly, then that's bad)

I like the idea of adding `emitted_at` as a cursor field as well to account for this

**Comment by sherifnada** [comment]
@ChristopheDuong are there any gotchas when using composite cursors with normalization?

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong are there any gotchas when using composite cursors with normalization?

Not sure no, dedup sync mode should already be using the composite cursor as it always use `_airbyte_emitted_at` as a backup from the defined cursor in the UI.

```
order by
            date is null asc,
            date desc,
            _airbyte_emitted_at desc
```
https://github.com/airbytehq/airbyte/blob/b88fc446529b06b35c88793aabcb92b6806a04d1/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/bigquery/test_simple_streams/first_output/airbyte_incremental/scd/test_normalization/dedup_exchange_rate_scd.sql#L58


@zestyping, can you verify by exporting the generated SQL models from normalization and edit the query as you are suggesting?
You would be changing the `partition by` and `order by` clauses of the `_airbyte_end_date` and _`airbyte_active_row`.

With your proposed changed to fetch cursor, primary key and version columns, would the query be de-duplicating as expected?

**Comment by ChristopheDuong** [comment]
I'm not sure I understand why the current de-dup query is not working though...

Is the currently generated SQL looks like this?
```
select
  ad_id, 
  date_stop,
  value
group by ab_id, date_stop
order by date_start is null, date_start, emitted_at
```

**Comment by zestyping** [comment]
@ChristopheDuong I'll have a look.  How do I find the generated SQL?  Is there a flag I can set to make it print out the SQL to the log, or somewhere I can look for a relevant file?

**Comment by zestyping** [comment]
@sherifnada I can change the attribution window — for example, if I shorten it to 7 days, then fewer duplicate records are added.  But the number of records always grows with each sync (i.e. more duplicate records are added each time), which isn't how Incremental & Deduped is supposed to work, right?  Isn't the invariant that, if no records have been updated in the source, there should be no change in the destination?  And even if records have been updated in the source, if no _new_ records have been created, there should be no change in the _number_ of rows in the destination?

**Comment by misteryeo** [comment]
@ChristopheDuong @sherifnada reminder to respond to @zestyping

**Comment by ChristopheDuong** [comment]
> @ChristopheDuong I'll have a look. How do I find the generated SQL? Is there a flag I can set to make it print out the SQL to the log, or somewhere I can look for a relevant file?

You can follow this series of tutorials that shows how to do this:
- Extracting final "native" SQL queries: https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-sql
- Extracting dbt SQL models: https://docs.airbyte.com/operator-guides/transformation-and-normalization/transformations-with-dbt

**Comment by ChristopheDuong** [comment]
> In general, I'm quite confused by the existence of the "Full refresh & Append" and "Incremental & Append" modes, both of which cause the number of rows in the destination to grow without bound every time you run a sync. Why would anyone ever want the number of rows in their destination to be affected by the sync frequency? Why would anyone ever want to store more copies of the same data when nothing has changed?)

To answer your questions, it's because:
> BigQuery is by design append-only preferred. That means that you better let duplicate rows from the same entity in the table and write your queries to always read most recent row. 
From: https://stackoverflow.com/a/48177344

So, our approach so far is to "append" in the destination connector and get normalization (or the user) to do the de-duplication afterward. Of course, we need to supply the proper partition_by/order_by keys for that to happen properly.

It doesn't mean that the destination bigquery connector would not try to "upsert" in the future either (since merge statements are now available for BQ) but that requires extra work that we haven't had time to spend on yet (and dbt is handling this for us in the normalization approach)

p.s.: Thanks Andy for the reminder!

**Comment by misteryeo** [comment]
Let us know if there's anything else outstanding here @zestyping!

**Comment by misteryeo** [comment]
Closing since there's no response but please re-open if needed!
