### ISSUE TITLE
New Destination Firestore: create dev account and sandbox credentials

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7236]
## Tell us about the new connector you’d like to have

For the Firestore source, we should create sandbox credentials as described here and add them to lastpass.

This will be in preparation for #7231

**Comment by harshithmullapudi** [comment]
@marcosmarxm can you help me here on pointing who is responsible for GCP ?

**Comment by karinakuz** [comment]
Account with database is created, credentials are saved in LastPass with the name 'Google Firestore (Firebase)', Oauth token was generated and tested in Postman with request: https://airbyte-project-323dc-default-rtdb.firebaseio.com/City.json
