### ISSUE TITLE
New Source Paystack: create dev account and sandbox credentials

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7248]
## Tell us about the new connector you’d like to have

For the Paystack, we should create sandbox credentials as described here and add them to lastpass.

This will be in preparation for #7214

**Comment by karinakuz** [comment]
Created sandbox account, received access key, added credentials to LastPass with the name "Paystack", filled account with the data through APIs, get data through APIs for the streams:

- Subaccount
- Settlement
- Transaction
- Customer
- Refund
- Invoice
- Subscription
- Plan
- Transfer Recipient

(impossible to create data for the streams: Dispute, Transfer, Settlement)
