### ISSUE TITLE
New Source Confluence: create dev account and sandbox credentials

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7249]
## Tell us about the new connector you’d like to have

For the Confulence source, we should create sandbox credentials as described here and add them to lastpass.

This will be in preparation for #7241

**Comment by karinakuz** [comment]
Created sandbox account with data, credentials are added to LastPass wit name 'Confluence', tested APIs for next streams:
- Content https://airbyteio.atlassian.net/wiki/rest/api/content
- Theme https://airbyteio.atlassian.net/wiki/rest/api/settings/theme
- Space https://airbyteio.atlassian.net/wiki/rest/api/space
- Space Content (pages and blogs) https://airbyteio.atlassian.net/wiki/rest/api/space/~489891918/content
- Blog https://airbyteio.atlassian.net/wiki/rest/api/content/698089500
- Page https://airbyteio.atlassian.net/wiki/rest/api/content/697761858
- Group https://airbyteio.atlassian.net/wiki/rest/api/group
