### ISSUE TITLE
Test that template generation produces valid modules

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#725]
## Tell us about the problem you're trying to solve
#700 introduced template generation for java destinations. However, since that change now houses templates instead of actual code, we can't verify that the output of that template is valid java code. The task here is to add a test suite which verifies that the output of that module is valid code.

**Comment by cgardens** [comment]
I would suggest we just focus on the python and singer templates for now. I don't think the java destination is worth a ton of time.
