### ISSUE TITLE
Connection Setting Page (connection name, timeout per connection, notification per connection)

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7251]
## Tell us about the problem you're trying to solve
I want to have the option to give a specific name to my connection, right now it's not possible.
![image](https://user-images.githubusercontent.com/5154322/138328996-2079b771-a9b6-4e9f-990c-a8a014c38be6.png)

Also some features should be connection-level:
- timeout and retries (right now Airbyte allow setting as a env variable for global usage, but If I have one large connection and other which is smaller I want to control this for each connection)
- notification (I do'nt want to receive notification to every sync only for the most critical)
- connection name (when you use multiple connections with same source/destination like split streams from source... not having names for connection is confuse)

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by timroes** [comment]
I'm closing this issue, since it combines multiple different asks. Please feel free to open individual issues for the individual different requests.
