### ISSUE TITLE
Restructure Namespace documentation

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7255]
### Tell us about the documentation you'd like us to add or update.
When navigating to the page describing Namespaces (https://docs.airbyte.io/understanding-airbyte/namespaces), the user is presented with a long page with a lot of details on the namespace. For a first-time user, this can be intimidating, and the general Cloud user has not previously heard of this term. 

In a usability test call, the user navigated to the page, and was not able to find a straightforward explanation with simple examples of the three options. They would have liked to see the three options (Mirror Source, Mirror Destination, Custom) with a top-level explanation (or diagram?) of what a Namespace was. I see an opportunity for the content on the page to be restructured to make it faster for users to comprehend. 

### If applicable, add links to the relevant docs that should be updated
https://docs.airbyte.io/understanding-airbyte/namespaces

**Comment by Amruta-Ranade** [comment]
@nataliekwong Can you verify if the Core Concepts for Cloud users doc satisfies the request: https://docs.airbyte.com/cloud/core-concepts

**Comment by nataliekwong** [comment]
Yep it does!
