### ISSUE TITLE
Dynamically change destination Namespace in UI

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7258]
## Tell us about the problem you're trying to solve
I would like to be certain where the data will end up in my destination before I start my first sync. I would also like to understand how changing the selection of the Namespace Configuration (Mirror Source, Mirror Destination, and Custom format) affects where the data appears in the destination.

## Describe the solution you’d like
I would like to see the table-level text change when the namespace configuration selection changes. Currently, when changing namespace configuration, it doesn’t change the value for destination namespace and stream name in the table, and this is confusing. It makes me believe that toggling this option does not make a difference in where the data will appear.

## Additional context
I noticed this confusion on a usability call with a Cloud user onboarding to Airbyte.

**Comment by edmundito** [comment]
Reviewed with @andyjih. This behavior already exists.
