### ISSUE TITLE
Allow sources to immediately access STATE messages output by the destination 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7265]
## Tell us about the problem you're trying to solve
A user is contributing the Amazon SQS connector. 

For this conversation, the SQS connector works as follows: 
1. a consumer reads messages from the queue. For each message, the API returns the message plus a "read receipt"
2. A consumer can delete messages from the queue by sending the read receipt back to the API with a DELETE request
3. If a message is not deleted, then the next time a user starts a fresh read, they will see it
4. Messages not manually deleted expire after 14days 

The assumptions above make it basically infeasible to implement incremental sync for this connector without risking data loss because the source connector can't guarantee that the destination has succeeded in persisting the data. It is also not feasible to use the `STATE` message passed in the next sync to delete data because the read receipts are unique every time the message is read. Therefore, one way this connector can implement incremental sync is to put all read receipts in the current message batch in a STATE message sent to the destination alongside the records, then in the same process receive the STATE message output by the destination indicating that batch has been written as soon as the destination has persisted them. 

However this is not possible now because the source only receives a single state message at the beginning of its process, and does not expect receiving any more state messages. 

This reveals that some assumptions made by Airbyte today do not hold: 
1. It assumes the source system can hold the data for a "long" time
2. assumes the source system can always expose a cursor to support incremental sync

## Describe the solution you’d like
I would like the Airbyte protocol and server/worker to loopback STATE messages output by the destination into the source so the source can update its underlying data store appropriately. 

## Describe the alternative you’ve considered or used
Not supporting incremental sync
doing some wonky staging logic on the server side

**Comment by sherifnada** [comment]
AFAICT this would be an issue for many streaming sources which have an ACK mechanism. In that sense, I don't think it's critical, but it would help improve things

An alternative would be to have an HA component in the middle of Airbyte where data is staged and which gives a stronger guarantee that ACKing/deleting data from the source is ok even if we don't know what exactly happened with the destination

**Comment by cgardens** [comment]
@sherifnada can we close this one. Doesn't seem to be too popular or relevant at this point. We can create a new issue when we decide to support this.
