### ISSUE TITLE
CI Sandbox for Salesforce Pardot

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7276]
## Tell us about the problem you're trying to solve
We need integration account to test community contribution: https://github.com/airbytehq/airbyte/pull/7091

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by VasylLazebnyk** [comment]
@marcosmarxm blocked here - Salesforce throwing error when we obtains oAuth application for Pardot in Salesforce dashboard. 
Also, they are no longer accept non-automated support requests sent from their Dashboard when we create tickets in the Help and Support section. 
The only way is to call them to live support by phone number 1-800-667-6389.

**Comment by karinakuz** [comment]
Create an issue with login to Pardot account with Salesforce credentials 

Case #41889254
Your case has been submitted!
We'll send you an email with all the details.
https://help.salesforce.com/s/cases
