### ISSUE TITLE
Marketo source fails during sync

### ISSUE THREAD

**Issue by chriestensonb** [airbytehq/airbyte#7286]
## Enviroment
- **Airbyte version**:  0.30.21-alpha
- **OS Version / Instance**: Pop!_OS 21.4
- **Deployment**: Docker
- **Source Connector and version**: Marketo 0.1.0 
- **Destination Connector and version**: Local JSON 0.2.8 
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
*I'm attempting to sync for the first time and the process errors out after syncing the first table.  Also failed for version 0.30.15 and 0.29.22*

## Expected Behavior
*Sync should complete without error.*

## Logs
<details>
<summary>LOG</summary>
Relevant lines here (full logs attached):

```

2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 - Traceback (most recent call last):
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -   File "/airbyte/integration_code/main.py", line 33, in <module>
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -     launch(source, sys.argv[1:])
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
2021-10-21 21:46:21 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Read 16346 records from campaigns stream
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -     for message in source_entrypoint.run(parsed_args):
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
2021-10-21 21:46:21 INFO () DefaultAirbyteStreamFactory(internalLog):90 - Syncing stream: leads
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -     for message in generator:
2021-10-21 21:46:21 ERROR () LineGobbler(voidCall):65 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 121, in read
2021-10-21 21:46:21 ERROR () DefaultAirbyteStreamFactory(internalLog):88 - Encountered an exception while reading stream SourceMarketo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 213, in _read_full_refresh
    slices = stream_instance.stream_slices(sync_mode=SyncMode.full_refresh, cursor_field=configured_stream.cursor_field)
  File "/airbyte/integration_code/source_marketo/source.py", line 193, in stream_slices
    date_slice["id"] = export["exportId"]
KeyError: 'exportId'

```
[logs-2-2.txt](https://github.com/airbytehq/airbyte/files/7400752/logs-2-2.txt)

</details>

## Steps to Reproduce
1. Setup instance.
2. Create Connector.
3. Run Sync.

## Are you willing to submit a PR?

Not at the moment.

**Comment by chriestensonb** [comment]
@lazebnyi I spent a little bit more time yesterday digging into this error.  One thing that I noted is that it appears to happen when a bulk export job doesnt have the expected structure.  According to the [Marketo bulk api documents](https://developers.marketo.com/rest-api/bulk-extract/) there are daily volume limits and limits on the number of queued jobs.  If those limits are hit in this sync process the returned json will not be of the expected format (though I would expect the error to be caught elsewhere).  This could be one cause of these errors, and explain why it feels like it works sometimes.

Operating under the hypothesis that this is what was happening, I waited 24 hours (for the daily limits to reset), and limited the scope of the sync to only a single table (leads).  The sync on this ran successfully for a while until I hit the error below (full logs attached).  I'm not sure that this error is related to the one that this issues is about but posting it here just in case you have any insights as to what could be causing it.
```
2021-11-03 19:03:58 ERROR Encountered an exception while reading stream SourceMarketo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 117, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 147, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 219, in _read_full_refresh
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 374, in read_records
    yield from self.parse_response(response, stream_state=stream_state, stream_slice=stream_slice)
  File "/airbyte/integration_code/source_marketo/source.py", line 234, in parse_response
    for i, value in enumerate(next(csv.reader([values], skipinitialspace=True)))
  File "/airbyte/integration_code/source_marketo/source.py", line 234, in <dictcomp>
    for i, value in enumerate(next(csv.reader([values], skipinitialspace=True)))
  File "/airbyte/integration_code/source_marketo/utils.py", line 86, in format_value
    return float(value)
ValueError: could not convert string to float: 'false'
```
[logs-13-2.txt](https://github.com/airbytehq/airbyte/files/7477667/logs-13-2.txt)

**Comment by lazebnyi** [comment]
@chriestensonb Hi, thanks for your work. Yes, you are right reason of issue is response of export doesn't have the expected structure. According to first log I have a question what value you set to window_in_days for first sync (log-2-2.log)? 
For second log that another issue the reason for which is bad data type for some field in schema. Now I try to find for which field is wrong. 

About limits, yes you are right that we have limit for queued jobs, but marketo connector work consistently with each bulk extract, so in each time we have only one queued job.

**Comment by chriestensonb** [comment]
@lazebnyi The `window_in_days` values for this was 30, but I did also try to run with a value of 7 and had the same error.

It is good to know that the connector will not exceed the number of jobs queued limit.  However, I am curious about the 500mb per day limit.  It seems that if the connector hits / exceeds that limit during a sync, then it could cause an error, and any subsequent runs would also get this error until the limit resets at the end of the 24 hour period.

**Comment by lazebnyi** [comment]
I think we can add ignoring of 500 mb error limit. And if during sync we get daily rate limit error we save data which we collect in other bulk extract before error during sync. Following sync for streams which used bulk extract will be empty before limits will not be restored back. 

But if we face with bulk extract which size will be more 500 size need ask customer to put less day window. 

@sherifnada Did you have any suggestions about that situation or my own?🙂

**Comment by sherifnada** [comment]
from a UX POV I'd suggest the following: 

* The connector should "magically" know how many requests it can gracefully make in a given day. 
* Based on this knowledge, the connector should sync as much data as it can in a single day then succeed (i.e: hitting the max limit should not count as a connector failure), and it should emit a STATE message which allows it to continue where it left off on the next sync
* We should indicate that this is the behavior in the docs
* We should also create an issue to allow the user to configure the max limit, in the case that (though ideally this is unnecessary, if the connector can just figure out how much data it can sync)

@chriestensonb @lazebnyi wdyt?

**Comment by chriestensonb** [comment]
@sherifnada I like this, and agree that it is a good path forward. i.e. The user should neither need to know, nor care that the API has limits.

**Comment by chriestensonb** [comment]
@lazebnyi Re: The data type error that I posted in the comments: `ValueError: could not convert string to float: 'false'`.  I dug a little bit deeper on that, and the schema that AirByte discovers only has 2 fields which it says should be floats.  I have verified that neither have bad/string values in them.  I am otherwise unable to decide why this errors is happening.  

One thing that I think might be happening is that there is a boolean field that is mostly null, and the parser attempts to infer its data type by looking at samples of data from that field.  Because it is mostly null, it sees null values and determines it is a float.  It then errors when it hits the few actual non null values in that field, which are strings or Booleans.  I don't know how to find out if this is the case though.  Any suggestions?

**Comment by lazebnyi** [comment]
@chriestensonb So, if I understand right. For fields `urgency` and `annualRevenue` in export leads from 2020-11-13T00:00:00Z to 2020-12-13T00:00:00Z you have value which is null or number data type?

**Comment by lazebnyi** [comment]
@sherifnada I think we can manipulate and count only size of response, so we could not predict size of next response. So, we can only sync before we get an error “1029, Export daily quota exceeded” and inform about that in log. And in the next sync start from state which was before we get an error. 

About allow the user to configure the max limit I think that not necessary, because all user will be use max value (500Mb) which already provided by API. I see no reason for the user to reduce their limits.

**Comment by chriestensonb** [comment]
> @chriestensonb So, if I understand right. For fields `urgency` and `annualRevenue` in export leads from 2020-11-13T00:00:00Z to 2020-12-13T00:00:00Z you have value which is null or number data type?

Yes. I have verified that only nulls or number data types are in that data.

**Comment by lazebnyi** [comment]
@chriestensonb Ok, for witch data fields you have 'false' value in export leads from 2020-11-13T00:00:00Z to 2020-12-13T00:00:00Z?

And if it possible could we switch communication to slack it can be faster there :)

**Comment by chriestensonb** [comment]
@lazebnyi I am double checking the data now.  It is unlikely that will be able to export the leads data for you, but can run a number of diagnostic tests on it and report back.  

Good idea, moving communication to slack.

**Comment by sherifnada** [comment]
@lazebnyi any updates on this issue?

**Comment by lazebnyi** [comment]
@sherifnada As we talk added logs and published them to Docker hub as release candidate version (0.1.1-rc). 

@chriestensonb Could you check Slack DM? I already send you 3 days ago info about the next steps with connector release candidate version.

**Comment by sherifnada** [comment]
ah of course. Thanks for the reminder! It's probably helpful to include such updates on tickets just to make sure they are not lost in Slack DMs ;)

**Comment by chriestensonb** [comment]
@lazebnyi Apologies for the delay.  I have upgraded and used the (0.1.1-rc) for the Marketo connector.  The additional logs are very helpful.  This issue is about two things, so I have addressed both in different sets of logs.

1.  The original issue where we saw a KeyError, and believed it was related to hitting the daily limits on the API.  Now the logs show this `Export daily quota 500MB exceeded.` but the run still fails.  However on the second retry it succeeds but give the same message for each data source and doesn't seem to sync anything.  I believe this to be as good as it gets given the API's daily limit.  Logs attached:
[logs-3-0-2021_11_30-export_quota.txt](https://github.com/airbytehq/airbyte/files/7629642/logs-3-0-2021_11_30-export_quota.txt)
[logs-3-1-2021_11_30-export_quota.txt](https://github.com/airbytehq/airbyte/files/7629643/logs-3-1-2021_11_30-export_quota.txt)

2.  The data type issue where there seems to be a mismatch between the schema and the values in the data.  The info in the logs in now very helpful, but somewhat confusing.  The column name and the value in the column don't make sense together (e.g. id column having a value of Zach, or NumberOfEmployees having a value of Investing).  I cannot find such instances in the data that I actually have in Marketo.  It feels like the column and values have somehow become miss-aligned.  Logs attached (Note: I had to redact some PII from data values in the logs.):
[logs-1-0-2021_11_30-dtype_error.txt](https://github.com/airbytehq/airbyte/files/7629674/logs-1-0-2021_11_30-dtype_error.txt)

**Comment by lazebnyi** [comment]
@chriestensonb Thanks for your work! Your logs can help a lot!

1. Fixed in the new version of the connector. 

2. Added a new logger. I think the problem with parsing CSV files. 

The new version is 0.1.1-rc.1

**Comment by chriestensonb** [comment]
I have updated and run again.  It does looks like the problem is with the parsing of the csv.  The logs print out a lot of the data which contains some PII.  Here are the last 100 lines where I have redacted some of the values.
```
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - cookies: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - externalSalesPersonId: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadPerson: 108321
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadRole: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadSource: PPL
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadStatus: 0. Nurture
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadScore: 75
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - urgency: 5.0
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - priority: 140
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - relativeScore: 2
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - relativeUrgency: 3
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - rating: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - personPrimaryLeadInterest: 111249
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadPartitionId: 1
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadRevenueCycleModelId: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - leadRevenueStageId: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - acquisitionProgramId: 1034
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - mktoAcquisitionDate: 2021-10-18T18:51:42Z
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - site: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - billingStreet: "406 Broadway Ave
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - billingCity:  #369"
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - billingState: Santa Monica
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - billingCountry: California
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - billingPostalCode: United States
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - mainPhone: REDACTED_URL
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - annualRevenue: REDCATED_PHONE_NUMBER
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - numberOfEmployees: 1.38067008E8
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - industry: 654
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - sicCode: Retail
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - mktoCompanyNotes: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - externalCompanyId: Overview: REDACTED_URL Be free. Enjoy the ride.
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - id: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - personType: REDACTED_FULL_NAME
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - mktoIsPartner: contact
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - isLead: false
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - mktoIsCustomer: true
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - isAnonymous: false
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - salutation: false
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - firstName: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - middleName: David
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - fax: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - title: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - contactCompany: Director of Data Analytics and Science
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - dateOfBirth: 65
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - address: null
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - city: "Los Angeles
source - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(internalLog):97 - state:  California
source - 2021-12-07 05:10:00 ERROR () DefaultAirbyteStreamFactory(internalLog):95 - Encountered an exception while reading stream SourceMarketo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
    for record in records:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records
    yield from self.parse_response(response, stream_state=stream_state, stream_slice=stream_slice)
  File "/airbyte/integration_code/source_marketo/source.py", line 227, in parse_response
    self.logger.info(f"{header}: {values.split(',')[j]}")
IndexError: list index out of range
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/main.py", line 13, in <module>
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     launch(source, sys.argv[1:])
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 108, in launch
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     for message in source_entrypoint.run(parsed_args):
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 99, in run
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     for message in generator:
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     raise e
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 106, in read
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     internal_config=internal_config,
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     for record in record_iterator:
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 208, in _read_full_refresh
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     for record in records:
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 353, in read_records
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     yield from self.parse_response(response, stream_state=stream_state, stream_slice=stream_slice)
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -   File "/airbyte/integration_code/source_marketo/source.py", line 227, in parse_response
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 -     self.logger.info(f"{header}: {values.split(',')[j]}")
source - 2021-12-07 05:10:00 ERROR () LineGobbler(voidCall):82 - IndexError: list index out of range
2021-12-07 05:10:00 INFO () DefaultReplicationWorker(run):138 - Source thread complete.
2021-12-07 05:10:00 INFO () DefaultReplicationWorker(run):139 - Waiting for destination thread to join.
destination - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 05:10:00 INFO i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):80 - {} - Airbyte message consumer: succeeded.
destination - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 05:10:00 INFO i.a.i.d.c.CsvDestination$CsvConsumer(close):196 - {} - finalizing consumer.
destination - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 05:10:00 INFO i.a.i.d.c.CsvDestination$CsvConsumer(close):212 - {} - File output: /local/_airbyte_raw_leads.csv
destination - 2021-12-07 05:10:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-07 05:10:00 INFO i.a.i.b.IntegrationRunner(run):153 - {} - Completed integration: io.airbyte.integrations.destination.csv.CsvDestination
2021-12-07 05:10:00 INFO () DefaultReplicationWorker(run):141 - Destination thread complete.
2021-12-07 05:10:00 ERROR () DefaultReplicationWorker(run):145 - Sync worker failed.
io.airbyte.workers.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteSource.close(DefaultAirbyteSource.java:117) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:143) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:49) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:167) ~[io.airbyte-airbyte-workers-0.33.5-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-12-07 05:10:00 INFO () DefaultReplicationWorker(run):169 - sync summary: io.airbyte.config.ReplicationAttemptSummary@5324e61a[status=failed,recordsSynced=393,bytesSynced=862587,startTime=1638853530643,endTime=1638853800884]
2021-12-07 05:10:00 INFO () DefaultReplicationWorker(run):178 - Source did not output any state messages
2021-12-07 05:10:00 WARN () DefaultReplicationWorker(run):186 - State capture: No new state, falling back on input state: io.airbyte.config.State@44b102e7[state={}]
2021-12-07 05:10:00 INFO () TemporalAttemptExecution(get):137 - Stopping cancellation check scheduling...
2021-12-07 05:10:00 INFO () ConfigRepository(updateConnectionState):515 - Updating connection e3909752-e094-4d52-a821-24cd3a9eb456 state: io.airbyte.config.State@398af591[state={}]
2021-12-07 05:10:00 INFO () DatabaseConfigPersistence(updateConfigRecord):273 - Updating STANDARD_SYNC_STATE record e3909752-e094-4d52-a821-24cd3a9eb456
```

**Comment by lazebnyi** [comment]
Thanks for this log! I think this [PR](https://github.com/airbytehq/airbyte/pull/8483#pullrequestreview-828995599) should help with your issue.

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/8483
