### ISSUE TITLE
Each Platform artifact should be responsible for building its own artifacts

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#7306]
## Tell us about the problem you're trying to solve
The platform is comprised of several modules, e.g. server, scheduler, webapp, etc. We are in an odd state where the the build for each of these modules does _not_ actually produce the artifacts that get used. e.g. I expect ./gradlew :airbyte-server:build (or some other task in `:airbyte-server`) to build the docker container that the server runs in. What happens today, is that there's instead a project level task called `composeBuild` that leverages `docker-compose` to build each artifact.

I think we should keep a task called `composeBuild` that has the same contract as the one today. In other words, calling `composeBuild` should produce the full set of artifacts needed to run the platform. But each submodule should have the knowledge of how to build its own docker containers. 

This will make iterating on individual submodules faster because you will no longer have to rebuild docker containers that you know are not relevant. In this world, I would expect that `composeBuild` will just leverage the tasks on each sub module to build the docker containers instead of needing to do `docker-compose build`.

## misc
Maybe we can reuse the `airbyteDocker` task we already have here? If so then, `composeBuild` would just depend on the `airbyteDocker` task for each platform sub module.

**Comment by benmoriceau** [comment]
I created https://github.com/airbytehq/airbyte/issues/7549 to do that in the cloud project as well

**Comment by benmoriceau** [comment]
A PR has been merged for this issue in https://github.com/airbytehq/airbyte/pull/7746
