### ISSUE TITLE
Source Hubspot: Add tickets_company_associations stream

### ISSUE THREAD

**Issue by ksoenandar** [airbytehq/airbyte#7317]
## Tell us about the problem you're trying to solve
Trying to link a ticket to the company so that I can better understand the linkages of issues raised with the types of companies.

## Describe the solution you’d like
A new table that captures the association between a ticket and a company. 

## Are you willing to submit a PR?
Would love to if I know how!

**Comment by marcosmarxm** [comment]
@ksoenandar could you try latest version of Hubspot connector the association to company was added to the ticket stream.

**Comment by marcosmarxm** [comment]
This was added in https://github.com/airbytehq/airbyte/pull/11423 let me know if doesn't attend your expecations.
