### ISSUE TITLE
Customize Notification Message for success/failure jobs

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7359]
## Tell us about the problem you're trying to solve
I want to customize the message Airbyte send for success/failure jobs.
I want to have some default options (date, connectionId, source...) and with that create a custom text

```
The sync <CONNECTION_ID> failed! This sync use <SOURCE_NAME> to destination <DESTINATION_NAME>
```

Also this feature will help users who want to use the notificatioin to process the output and trigger other action.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by cgardens** [comment]
Closes as won't do. Let's get the basic emails to be good first and then revisit.
