### ISSUE TITLE
S3 Parquet Format Data Source Shows Format As CSV In Settings

### ISSUE THREAD

**Issue by lewisdawson** [airbytehq/airbyte#7374]
Configured an S3 data source with the parquet format. I later went to the settings tab for the source and noticed it shows up as having a csv format rather than a parquet format.

![image](https://user-images.githubusercontent.com/5010504/138801273-aaff8ddc-e37a-4076-b039-f61abb051272.png)

Running Airbyte version `0.30.22-alpha` in Docker on MacOS 10.15.7. After cloning the repo, started Airbyte via `docker-compose up` with no modifications to the docker compose file or the .env file. Seeing the same issue in both Firefox 93.0 and Chrome 95

**Comment by sherifnada** [comment]
@lewisdawson are you still seeing this issue on the latest version of Airbyte? a related fix was recently merged: https://github.com/airbytehq/airbyte/pull/7520
