### ISSUE TITLE
Don't infer schema when loading data as "raw"

### ISSUE THREAD

**Issue by noel** [airbytehq/airbyte#7401]
## Tell us about the problem you're trying to solve
when loading a file from S3 to Snowflake I want to prevent airbyte from inferring the table schema.  e.g. I want everything to load as raw strings and I will cast with dbt. Airbyte is setting some attributes as integer even when I set the connection with Raw data - no normalization

## Describe the solution you’d like
I would like Raw to be Raw and all cols to get ingested as strings so I can do data validations etc and then cast with dbt.

## Describe the alternative you’ve considered or used
Specifying the schema in the connection, but this is cumbersome especially for sources with 300+ cols

**Comment by Phlair** [comment]
related issue: https://github.com/airbytehq/airbyte/issues/6480

**Comment by noel** [comment]
Yes it is. Should I close this one?

**Comment by Phlair** [comment]
Sure, close as duplicate 👍 
I'm just writing up a feasible approach to solve this in the other issue
