### ISSUE TITLE
Error connecting to MariaDB (binlog_row_image could not be queried)

### ISSUE THREAD

**Issue by coquej** [airbytehq/airbyte#7404]
## Enviroment
- **Airbyte version**:  example is 0.29.0-alpha
- **OS Version / Instance**: Windows
- **Deployment**: Docker
- **Source Connector and version**:MySQL 0.3.8
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
Appears error message: "Could not query the variable binlog_row_image". 
It seems to be due to the version of the MariaDB database we want to extract info from, but we cannot update the database as we are not the owners of the DB. 
Is there a possibility to change anything in the connector to make it work as we cannot update the version of the DB?

**Comment by coquej** [comment]
I see in #7600 this is solved, but after updating the connector this is still happening. Is it possible to avoid the binlog_row_image parameter in any way?

**Comment by sherifnada** [comment]
@coquej will look into it and come back soon with an answer!

**Comment by mkhokh-33** [comment]
hi @freesmith , @coquej 
Could I ask for more information from your side:
1. which replication method did you choose for a source `STANDARD`  or   `CDC`
2. if possible, pls provide MariaDB version

Thanks

**Comment by freesmith** [comment]
Ho,
1. Standard replication
2. 5.5.60 is our MariaDB server version
Thanks!

**Comment by coquej** [comment]
Hi, my case is exacty the same as @freesmith. Thanks!
