### ISSUE TITLE
Source Mailchimp: add oauth flow (java part)

### ISSUE THREAD

**Issue by annalvova05** [airbytehq/airbyte#7406]
Source Mailchimp: add oauth flow (java part)

https://mailchimp.com/developer/marketing/guides/access-user-data-oauth-2/

=========== JAVA PART ================

**Approve access from the customer side using:**
client_id

https://login.mailchimp.com/oauth2/authorize?response_type=code&client_id=1234567890&redirect_uri=https://airbyte.io/

**Get redirect url with 'code':**

https://airbyte.io/?code=33333333

**Obtain token using**

curl https://login.mailchimp.com/oauth2/token
-X POST
-H 'Content-Type: application/json'
-d '{
"client_id": "1234567890",
"client_secret": "2222222",
"grant_type": "authorization_code",
"code": "3333333",
"redirect_uri": "https://airbyte.io/"
}'

RESPONSE:
{
"access_token": "1q2w3e4r5t6y.",
"expires_in": "0",
"scope": null
}

OAuth access tokens do not expire.

**Obtain server_prefix (dc) using**

curl https://login.mailchimp.com/oauth2/metadata
-X GET
-H 'Authorization: Bearer <access_token>'

RESPONSE:
{
    "dc": "us2",
    "role": "admin",
    "accountname": "Airbyte",
    "user_id": 123,
    "login": {
        "email": "email@email.com",
        "avatar": null,
        "login_id": 12345,
        "login_name": "email@email.com",
        "login_email": "email@email.com"
    },
    "login_url": "https://login.mailchimp.com",
    "api_endpoint": "https://us2.api.mailchimp.com"
}

============== PYTHON PART =====================

API requests using access_token and server_prefix (dc).

$ curl
-s https://{server_prefix}.api.mailchimp.com/3.0/campaigns
-H 'Authorization: Bearer <access_token>'

**Comment by antixar** [comment]
Duplicate
It'll be fixed with #6273
