### ISSUE TITLE
Implement testing for OAuth on Google Analytics connector

### ISSUE THREAD

**Issue by Phlair** [airbytehq/airbyte#7420]
Follow on from https://github.com/airbytehq/airbyte/issues/4982

## Tell us about the problem you're trying to solve
Currently none of our OAuth connectors have real integration testing. This issue is aimed at going from 0 -> 1.

## Describe the solution you’d like
Set up OAuth testing, as described in the [RFC for OAuth testing](https://docs.google.com/document/d/1UoYZKJAFkm5olKqqJwwFhzdVfJh8gMgZ1cfbHyYNCkQ/edit#) (currently wip), for the Google Analytics source.

Since we've set up a few Google sources for OAuth already, this may stretch goal into adding testing for all of them if the flows are near identical so that extra work is close to zero.

**Comment by ChristopheDuong** [comment]
Since #7827 is out, there should be integration tests on the connectors that support OAuth to also include the new `AdvancedAuth` object instead of implementing only the old `AuthSpecification`
