### ISSUE TITLE
Source MongoDBv2: Not able to handle `-` in source namespace

### ISSUE THREAD

**Issue by jwilsie** [airbytehq/airbyte#7435]
OS Version / Instance: Ubuntu 20.04
Deployment: docker-compose
Airbyte Version: 0.30.23-alpha
Source/version: airbyte/source-mongodb-v2 0.1.3
Destination name/version: airbyte/destination-postgres 0.3.11
Severity: High

![image](https://user-images.githubusercontent.com/176929/139145515-df1a17e7-1373-4f4c-9432-b9d14e3b571a.png)

[logs-12042-0.txt](https://github.com/airbytehq/airbyte/files/7429221/logs-12042-0.txt)

**Comment by evantahler** [comment]
This should be fixed in the latest version of the connector
