### ISSUE TITLE
Zendesk Support: Ticket custom fields not extracted properly after normalization

### ISSUE THREAD

**Issue by asyarif93** [airbytehq/airbyte#7441]
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: Amazon Linux / EC2 t3a.large
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: Zendesk Support 0.1.3
- **Destination Connector and version**: Bigquery 0.4.1
- **Severity**: Medium
- **Step where error happened**: When Look table result

## Current Behavior
in table `tickets` item in field `custom_fields` is `{"id":114101613833,"value":"87"}` however in table `tickets_custom_fields` the `value` field is `null`

## Expected Behavior
in table `tickets_custom_fields` the `value` field should be `87`

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Image Reference

<details>
<summary>Images</summary> 

custom fields in tickets table

![value in tickets table](https://user-images.githubusercontent.com/30652154/139233967-2ac49102-65ba-4f75-9d01-13bdc1241d96.png)

value in tickets_custom_fields table

![Screenshot from 2021-10-28 14-22-20](https://user-images.githubusercontent.com/30652154/139234073-c28d79cd-0878-4815-b5cd-3a8647c85d6a.png)

airbyte generated normalization query

![Screenshot from 2021-10-28 14-22-51](https://user-images.githubusercontent.com/30652154/139234214-7502be2e-477b-4de4-897d-91680a7721e5.png)

</details>

## Steps to Reproduce
1. set catalog schema to `tickets`

## Are you willing to submit a PR?

Remove this with your answer.
Yes

**Comment by sherifnada** [comment]
it seems like the cause of this issue is that the `value` field here does not contain a schema. Therefore the fix here would be to identify the right schema/data types in the catalog, and normalization will be able to address it correctly.
