### ISSUE TITLE
Facebook Pages: Remove commerce_merchant_settings from request

### ISSUE THREAD

**Issue by everysize** [airbytehq/airbyte#7443]
## Enviroment
- **Airbyte version**:  0.30.23-alpha
- **OS Version / Instance**: Ubuntu 20
- **Deployment**: Docker
- **Source Connector and version**: Facebook Pages 0.1.2
- **Destination Connector and version**: Postgres
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior & Solution
The Source Connector for "Facebook Pages" is not working. When you add an access_token and the page_id and test the connection you receive an error because of "(#200) Missing Permissions".

The connector requests a field which is not permitted to use with the communicated permissions from the doc (https://docs.airbyte.io/integrations/sources/facebook-pages).

The field "commerce_merchant_settings" has to be removed from the request, than it will work.

You can try it: (replace {YOUR_PAGE_ID} and {YOUR_ACCESS_TOKEN})
- [Not working](https://graph.facebook.com/v12.0/{YOUR_PAGE_ID}?access_token={YOUR_ACCESS_TOKEN}&fields=id%2Cabout%2Cad_campaign%2Caffiliation%2Capp_id%2Cartists_we_like%2Cattire%2Cawards%2Cband_interests%2Cband_members%2Cbio%2Cbirthday%2Cbooking_agent%2Cbuilt%2Ccan_checkin%2Ccan_post%2Ccategory%2Ccategory_list%2Ccheckins%2Ccompany_overview%2Cconnected_page_backed_instagram_account%2Ccontact_address%2Ccountry_page_likes%2Ccover%2Cculinary_team%2Ccurrent_location%2Cdelivery_and_pickup_option_info%2Cdescription%2Cdescription_html%2Cdifferently_open_offerings%2Cdirected_by%2Cdisplay_subtext%2Cdisplayed_message_response_time%2Cemails%2Cengagement%2Cfan_count%2Cfeatured_video%2Cfeatures%2Cfollowers_count%2Cfood_styles%2Cfounded%2Cgeneral_info%2Cgeneral_manager%2Cgenre%2Cglobal_brand_page_name%2Cglobal_brand_root_id%2Chas_added_app%2Chas_transitioned_to_new_page_experience%2Chas_whatsapp_business_number%2Chas_whatsapp_number%2Chometown%2Chours%2Cimpressum%2Cinfluences%2Cis_always_open%2Cis_chain%2Cis_community_page%2Cis_eligible_for_branded_content%2Cis_messenger_bot_get_started_enabled%2Cis_messenger_platform_bot%2Cis_owned%2Cis_permanently_closed%2Cis_published%2Cis_unclaimed%2Cis_webhooks_subscribed%2Cleadgen_tos_acceptance_time%2Cleadgen_tos_accepted%2Cleadgen_tos_accepting_user%2Clink%2Clocation%2Cmembers%2Cmerchant_review_status%2Cmessenger_ads_default_icebreakers%2Cmessenger_ads_default_page_welcome_message%2Cmessenger_ads_default_quick_replies%2Cmessenger_ads_quick_replies_type%2Cmission%2Cmpg%2Cname%2Cname_with_location_descriptor%2Cnetwork%2Cnew_like_count%2Coffer_eligible%2Coverall_star_rating%2Cpage_token%2Cparking%2Cpayment_options%2Cpersonal_info%2Cpersonal_interests%2Cpharma_safety_info%2Cphone%2Cpickup_options%2Cplace_type%2Cplot_outline%2Cpreferred_audience%2Cpress_contact%2Cprice_range%2Cprivacy_info_url%2Cproduced_by%2Cproducts%2Cpromotion_eligible%2Cpromotion_ineligible_reason%2Cpublic_transit%2Crating_count%2Crecord_label%2Crelease_date%2Crestaurant_services%2Crestaurant_specialties%2Cschedule%2Cscreenplay_by%2Cseason%2Csingle_line_address%2Cstarring%2Cstart_info%2Cstore_code%2Cstore_location_descriptor%2Cstore_number%2Cstudio%2Csupports_donate_button_in_live_video%2Ctalking_about_count%2Ctemporary_status%2Cunread_message_count%2Cunread_notif_count%2Cunseen_message_count%2Cusername%2Cverification_status%2Cvoip_info%2Cwebsite%2Cwere_here_count%2Cwhatsapp_number%2Cwritten_by%2Cagencies%2Calbums%2Cblocked%2Ccall_to_actions%2Ccanvas_elements%2Ccommerce_merchant_settings%2Cevents%2Cfeed%2Cglobal_brand_children%2Cgroups%2Cimage_copyrights%2Cindexed_videos%2Cinsights_exports%2Cinstagram_accounts%2Clikes%2Clive_encoders%2Clive_videos%2Clocations%2Cnativeoffers%2Cpage_backed_instagram_accounts%2Cphotos%2Cposts%2Cproduct_catalogs%2Cpublished_posts%2Cratings%2Croles%2Crtb_dynamic_posts%2Cscheduled_posts%2Csettings%2Ctabs%2Ctagged%2Cvideo_lists%2Cvideos%2Cvisitor_posts)
- [Working](https://graph.facebook.com/v12.0/{YOUR_PAGE_ID}?access_token={YOUR_ACCESS_TOKEN}&fields=id%2Cabout%2Cad_campaign%2Caffiliation%2Capp_id%2Cartists_we_like%2Cattire%2Cawards%2Cband_interests%2Cband_members%2Cbio%2Cbirthday%2Cbooking_agent%2Cbuilt%2Ccan_checkin%2Ccan_post%2Ccategory%2Ccategory_list%2Ccheckins%2Ccompany_overview%2Cconnected_page_backed_instagram_account%2Ccontact_address%2Ccountry_page_likes%2Ccover%2Cculinary_team%2Ccurrent_location%2Cdelivery_and_pickup_option_info%2Cdescription%2Cdescription_html%2Cdifferently_open_offerings%2Cdirected_by%2Cdisplay_subtext%2Cdisplayed_message_response_time%2Cemails%2Cengagement%2Cfan_count%2Cfeatured_video%2Cfeatures%2Cfollowers_count%2Cfood_styles%2Cfounded%2Cgeneral_info%2Cgeneral_manager%2Cgenre%2Cglobal_brand_page_name%2Cglobal_brand_root_id%2Chas_added_app%2Chas_transitioned_to_new_page_experience%2Chas_whatsapp_business_number%2Chas_whatsapp_number%2Chometown%2Chours%2Cimpressum%2Cinfluences%2Cis_always_open%2Cis_chain%2Cis_community_page%2Cis_eligible_for_branded_content%2Cis_messenger_bot_get_started_enabled%2Cis_messenger_platform_bot%2Cis_owned%2Cis_permanently_closed%2Cis_published%2Cis_unclaimed%2Cis_webhooks_subscribed%2Cleadgen_tos_acceptance_time%2Cleadgen_tos_accepted%2Cleadgen_tos_accepting_user%2Clink%2Clocation%2Cmembers%2Cmerchant_review_status%2Cmessenger_ads_default_icebreakers%2Cmessenger_ads_default_page_welcome_message%2Cmessenger_ads_default_quick_replies%2Cmessenger_ads_quick_replies_type%2Cmission%2Cmpg%2Cname%2Cname_with_location_descriptor%2Cnetwork%2Cnew_like_count%2Coffer_eligible%2Coverall_star_rating%2Cpage_token%2Cparking%2Cpayment_options%2Cpersonal_info%2Cpersonal_interests%2Cpharma_safety_info%2Cphone%2Cpickup_options%2Cplace_type%2Cplot_outline%2Cpreferred_audience%2Cpress_contact%2Cprice_range%2Cprivacy_info_url%2Cproduced_by%2Cproducts%2Cpromotion_eligible%2Cpromotion_ineligible_reason%2Cpublic_transit%2Crating_count%2Crecord_label%2Crelease_date%2Crestaurant_services%2Crestaurant_specialties%2Cschedule%2Cscreenplay_by%2Cseason%2Csingle_line_address%2Cstarring%2Cstart_info%2Cstore_code%2Cstore_location_descriptor%2Cstore_number%2Cstudio%2Csupports_donate_button_in_live_video%2Ctalking_about_count%2Ctemporary_status%2Cunread_message_count%2Cunread_notif_count%2Cunseen_message_count%2Cusername%2Cverification_status%2Cvoip_info%2Cwebsite%2Cwere_here_count%2Cwhatsapp_number%2Cwritten_by%2Cagencies%2Calbums%2Cblocked%2Ccall_to_actions%2Ccanvas_elements%2Cevents%2Cfeed%2Cglobal_brand_children%2Cgroups%2Cimage_copyrights%2Cindexed_videos%2Cinsights_exports%2Cinstagram_accounts%2Clikes%2Clive_encoders%2Clive_videos%2Clocations%2Cnativeoffers%2Cpage_backed_instagram_accounts%2Cphotos%2Cposts%2Cproduct_catalogs%2Cpublished_posts%2Cratings%2Croles%2Crtb_dynamic_posts%2Cscheduled_posts%2Csettings%2Ctabs%2Ctagged%2Cvideo_lists%2Cvideos%2Cvisitor_posts)

## Logs

<details>
<summary>LOG</summary> 

```
{
   "error": {
      "message": "(#200) Missing Permissions",
      "type": "OAuthException",
      "code": 200,
      "fbtrace_id": "XXXXXXXXXXXXXXXXXX"
   }
}

```

</details>

**Comment by Zirochkaa** [comment]
Hello @everysize.
I went through [Connect a User Page](https://docs.airbyte.io/integrations/sources/facebook-pages#connect-a-user-page) part of the documentation:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/19872253/141734525-64e53c74-2b1d-40a0-b45b-67267e821076.png">
and generated a token for those 4 permissions. Then I checked 2 links which you provided (Working and Not working) and they both are working for me meaning that I didn't get any errors, only the data.

I also run `check` command (which tests the connection) and it also worked.
Could you please go through [Connect a User Page](https://docs.airbyte.io/integrations/sources/facebook-pages#connect-a-user-page) part of the documentation one more time, generate token, test connection and tell me the result?

**Comment by Zirochkaa** [comment]
@everysize I noticed that you are using `0.1.2` version of Facebook Pages connector. 11 days ago we published `0.1.3` version of Facebook Pages connector (#7440) and it looks like this new version should fix your issue. Could you please upgrade to `0.1.3` version and try again?

**Comment by Zirochkaa** [comment]
I checked on `0.1.2` version and while testing the connection I got `403 Client Error: Forbidden for url ...` error.
Then I checked on `0.1.3` version and test for connection passed. So I believe updating to `0.1.3` version will fix this issue for you.

**Comment by Zirochkaa** [comment]
I am closing this PR because solution was described in the comments above.
