### ISSUE TITLE
Add explicit record validation to standard source test suite

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#745]
## Tell us about the problem you're trying to solve
Currently the standard source test verifies that a source outputs _any_ records when `read` is called. #715 introduces simple regex matching to validate that a given set of record patterns were emitted. Eventually we'd also like the ability to validate the exact set of records that was emitted from the source.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368235306932) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment]
I think it'd be preferable to send the output records and logs back to the implementation and allow it to do whatever testing it needs to on the output. I think it's rare that we'll be able to do exact matching (especially with `emitted_at` and the fact that most `data` elements will contain non-exact objects.
