### ISSUE TITLE
Measure active connections

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#748]
## Tell us about the problem you're trying to solve
We need a way to distinguish active connections from inactive ones metrics-wise.
Why? So that we know when a company is actually using us for their data pipelines, and we can build case studies with them (and eventually upgrade them). 
The number of deployments is not a good KPI. 

## Describe the solution you’d like
First, we should agree on what "active" connection means. 1st suggestion: it is a connection with a recurring frequency through which data flows every day.

Then we could send a Segment event on the backend side of the app, every time a sync is done. Having this info on Segment will help us leverage it in any tool we want. 
I added a suggestion of event, named "Connection Sync" here: https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit?usp=sharing

## Additional context
I don't think we log syncs in any way on our side. I'm not sure this is a good solution though.
For the moment, with Segment, we only track when a user sets up a connection, but nothing about active connections.

@cgardens

**Comment by johnlafleur** [comment]
@cgardens I think we should prioritize this the fastest possible, as we're ramping up the number of connectors. 
I let you add the milestone.

**Comment by johnlafleur** [comment]
Was this pushed on prod? I can't see the new event on Segment.

**Comment by cgardens** [comment]
@johnlafleur  It's in prod now. It wasn't before yesterday. Let me know if you continue to have issues
