### ISSUE TITLE
🎉 Source Jira: Fill empty streams with data

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#7488]
## Tell us about the problem you're trying to solve
For now we have these empty stream in the Jira connector:
`project_permission_schemes`,
`epics`,
 `screen_tab_fields`, 
`sprint_issues`,
`sprints`.

So these are marked as `empty_streams` in the SAT config, so we couldn't properly test them.

## Describe the solution you’d like
We need to find a way on how to populate these streams with data.

## Describe the alternative you’ve considered or used
None

## Additional context
Issue appeared in https://github.com/airbytehq/airbyte/pull/7408

## Are you willing to submit a PR?

I could

**Comment by ycherniaiev** [comment]
in order to have more flexibility in populating streams "YOUR SUPPORT TICKET NUMBER
[PA-128714](https://getsupport.atlassian.com/servicedesk/customer/portal/37/PA-128714)"is created

**Comment by ycherniaiev** [comment]
Please use JIRA TEST TOKEN on lastpass to test

**Comment by ycherniaiev** [comment]
and please be aware that "Sandboxes can only be created with Jira Software Premium or Enterprise plans. Testing for integrations can be done when starting a Jira Software evaluation. Once you have created a Premium Jira Software evaluation you will be able to manage product sandboxes."
