### ISSUE TITLE
Clicking the oauth button is not a required operation

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7495]
## Enviroment
- **Airbyte version**:  Airbyte Cloud
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: Facebook latest
- **Severity**: Medium
- **Step where error happened**: Setup new connection 

## Current Behavior
I was setting up an FB marketing connector and accidentally forgot to click the authenticate button. I clicked the "setup connection" button and it happily accepted and tried to create the source. The source failed and I was confused about why. Then I realized I hadn't clicked the "authorize" button for oauth. 

## Expected Behavior
If I didn't click the authorize button then I shouldn't be able to click the "Create source" button -- it should be treated as a required param.

**Comment by Jamakase** [comment]
@sherifnada How should we handle it for edit mode? Should we force user pass auth again? Or in edit mode there is not need to pass oauth again.

**Comment by sherifnada** [comment]
@Jamakase in edit mode there is no need to pass again

**Comment by jrhizor** [comment]
We won't be getting to this until early Jan.

**Comment by tealjulia** [comment]
Saw this still hanging out in our bug backlog.

We're adding a validation check for this field in https://github.com/airbytehq/airbyte/pull/15625

However, we dynamically configure the validation schema based on the connector spec.  As noted in the PR linked, some Connectors (ie: Mailchimp and Salesforce) do require these Auth-related fields.  Others (ie: Hubspot, Google Ads, Google Sheets) do not and allow Connector setup/testing still.

@sherifnada based on that this feels like a connectors-side change.  Does that seem correct?
