### ISSUE TITLE
Postgres Destination Connection Check message are unhelpful

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7496]
## Current Behavior
I tried a connection check to postgres, but it failed. The connection check UI said: 

![Screen Shot 2021-10-29 at 9 25 28 AM](https://user-images.githubusercontent.com/6246757/139469991-13ad1ec5-2e38-412d-811c-d0068922f9c6.png)

This was not helpful, so i looked at the logs and found: 

`Caused by: java.net.UnknownHostException: xxx@yyy.compute-1.amazonaws.com`

which is a much more actionable message. 

## Expected Behavior
Display a helpful error message. 

## Logs
[logs-c92f555e-11ff-4a46-a572-9d1a251ceb4f-.txt](https://github.com/airbytehq/airbyte/files/7443537/logs-c92f555e-11ff-4a46-a572-9d1a251ceb4f-.txt)

**Comment by misteryeo** [comment]
Being addressed https://github.com/airbytehq/airbyte/issues/11322
