### ISSUE TITLE
UI should display time in local timezone

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7497]
## Current Behavior

The time is 9:33 AM PST. I ran a connection check and and the logs had the following timestamp next to it (EST timezone):
![Screen Shot 2021-10-29 at 9 36 24 AM](https://user-images.githubusercontent.com/6246757/139471428-92eff67c-c7bd-430d-8c53-741f75491fc1.png)

## Expected Behavior
Times should be displayed in the user's local timezone

@jrhizor assigning to you for triage

**Comment by jrhizor** [comment]
Complications for day by users for billing page. Maybe we should have that be fixed to a specific timezone?

**Comment by jrhizor** [comment]
Can't change log timestamps on the fly.

**Comment by Jamakase** [comment]
@sherifnada Actually I have figured out that it may be not that easy to display TZ as backend returns just timestamp. Is this timestamp UTC based or it could depend on where server is running?

We have 2 options:
- always return dates in some tz
- return from backend time in some other format with offset ( ISO 8601 and etc )

**Comment by sherifnada** [comment]
I think the UX is ultimately up to Jared/john, but it seems to make the most sense to display it in the UI user's current timezone if possible, and also show the timezone e.g (PST)

**Comment by jrhizor** [comment]
@Jamakase we're returning unix timestamps in the jobs today, right? So no time zone needed.

**Comment by edmundito** [comment]
@andyjih Could you review this and help us define how ideally we want to show the date & time to users?

**Comment by Marcaccio-Mutt** [comment]
HI!
There are news about this issue? :thinking:

**Comment by timroes** [comment]
Checked this, and we show times in your local time zone by now across the UI. Only exception is the logs, though times inside them are basically part of the individual log lines and nothing the UI "renders", so I consider this to be solved.
