### ISSUE TITLE
Add an automated broken link checker to make sure documentation links are up to date

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#752]
## Tell us about the problem you're trying to solve
We currently do not have a way to tell if a change to the code or the documentation broke a URL somewhere in our codebase. It would be ideal to have a check that reports broken links in our repo to make sure our documentation is always up to date.

**Comment by ChristopheDuong** [comment]
In python, we have a tool called Sphinx to handle documentation generation like Javadoc

One of its feature is to do exactly what you are describing (check for broken url links)
https://stackoverflow.com/questions/14492743/have-sphinx-report-broken-links

Get started:
https://medium.com/better-programming/auto-documenting-a-python-project-using-sphinx-8878f9ddc6e9
