### ISSUE TITLE
Update Shopify catalog to contain inventory_item table containing product cost price

### ISSUE THREAD

**Issue by milo157** [airbytehq/airbyte#7527]
## Enviroment
- **Source Connector and version**: Shopify 0.1.21

## Current Behavior
Currently, the catalog only syncs the inventory_levels table however it should sync the inventory_item table. The reason for this is that table contains the cost price of a product which is used in many calculations such as gross margin etc.

## Expected Behavior
The connector should sync the inventory_item table which can be found here: https://shopify.dev/api/admin-rest/2021-10/resources/inventoryitem#top

## Are you willing to submit a PR?
Potentially

**Comment by sherifnada** [comment]
@milo157 i've relabelled this as a feature request rather than a bug report - please LMK if I'm missing something

**Comment by jonoirwinrsa** [comment]
Hi @sherifnada I have created a PR to add these features -  https://github.com/airbytehq/airbyte/pull/7973

This is my first contribution to Airbyte so there are a few things that I am a little uncertain about but I think they can all be addressed the in PR process.

Is there anything more I need to do to get it reviewed?

**Comment by misteryeo** [comment]
Looks like this has been merged so closing this issue!
