### ISSUE TITLE
Support 3 Days, 7 Days, 15 Days to the scheduling

### ISSUE THREAD

**Issue by deltasmithdev** [airbytehq/airbyte#7530]
So, currently, the maximum sync is 24 hours. Can we simply add 3 days, 7 days, 15 days option in the configuration? Specifically 7 days and 15 days as there might be many people who is looking for this kind of configuration.

**Comment by marcosmarxm** [comment]
I'll close this in favor of https://github.com/airbytehq/airbyte/issues/2170 which solve the same problem with more flexibility.
