### ISSUE TITLE
Following a link to another workspace does not change the workspace

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#7534]
## Enviroment
- **Airbyte version**:  cloud

## Current Behavior
When I am given a link to the cloud app, e.g. https://cloud.airbyte.io/source/266295e7-a71f-4c77-90bc-306e050cf12e, the UI doesn't switch to the workspace of the link I went to, it just stays on whatever workspace I was on previously. When this happens, the UI breaks. It technically brings me to the page of the resource that is associated with the link, but because the workspace context hasn't change, any action I perform doesn't work and I get shunted back into the previous workspace I was in.

## Expected Behavior
I expect the workspace context in the UI to switch to the workspace relevant to the link clicked on (assuming I'm authorized to access it).

This makes debugging issues in cloud really hard, because you need to separately figure out what the workspace is by looking in the db.

@Jamakase @jrhizor

**Comment by cgardens** [comment]
@marcosmarxm is this something that would help you?

**Comment by Jamakase** [comment]
@cgardens we don't yet support workspaceId in slug, so when you open such link, there is no way to actually no that it is for this or that workspace.


We have a task #5227 though and based on our discussion with @jrhizor it is planned for q1. Should we prioritize it higher?
