### ISSUE TITLE
reduce java image sizes by using `ADD` docker command

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7551]
## Tell us about the problem you're trying to solve
We can probably reduce the docker image size of our java based connectors by using the ADD command instead of COPYing the tar archive. See this [PR for an example](https://github.com/airbytehq/airbyte/pull/7537/files)

## Describe the solution you’d like
use the ADD command to reduce the size of the docker images

**Comment by syed-awais-ali** [comment]
I have forked the repo and will paste the PR 
@sherifnada FYI.

**Comment by sherifnada** [comment]
@syed-awais-ali I believe we do not need this change after the revert that happened to #8516 -- apologies if you have already spent effort on this. Closing this issue and apologies again about any confusion here

**Comment by syed-awais-ali** [comment]
Ah, okay. @sherifnada No worries. Thanks. I had made changes to several files though but that's cool. Do you think of any other issue that I could explore and pick up? Otherwise, I will search for open issues. Thanks

**Comment by sherifnada** [comment]
Of course! Look for "accepting-contributions" label or choose any issue that seems interesting and ask the creator if it's open to contribution
