### ISSUE TITLE
Source Jira: add more streams (currently supported in Stitch/Singer)

### ISSUE THREAD

**Issue by prconstruct** [airbytehq/airbyte#7557]
## Tell us about the problem you're trying to solve
We are planning to move our data pipelines from Stitch to Airbyte. We have a pipeline from Jira. The below list of APIs is missing in Airbyte but is available in Stitch/Singer.
1. changelogs
2. components
3. issue_transitions
4. resolutions
5. roles
6. versions
7. worklogs

## Describe the solution you’d like
It would be really great if these APIs are added to the Source JIRA.

## Describe the alternative you’ve considered or used
As I mentioned we are already using Stitch and planning to migrate. As an alternate, Meltano is providing these apis since it's also a singer-based ecosystem.

## Are you willing to submit a PR?
No

**Comment by btkcodedev** [comment]
@YowanR I would like to give it a try :)
Also of course I will be asking for help from the community.

**Comment by YowanR** [comment]
Hi @btkcodedev, I've assigned the issue to you! Looking forward to your contribution! 💪 🚀

**Comment by YowanR** [comment]
@btkcodedev Are you still planning to work on this one?

**Comment by btkcodedev** [comment]
Nope, Please leave to the community @YowanR

**Comment by geekwhocodes** [comment]
@YowanR I'll give it a try.

**Comment by justinbchau** [comment]
@geekwhocodes - you got it!

**Comment by artem1205** [comment]
working on it as no response received
