### ISSUE TITLE
don't fail listing definitions if the format from the server is invalid

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7567]
#6975 resulted in a duplicate entry resulting in the problem observed in https://airbytehq.slack.com/archives/C01MFR03D5W/p1635865547477900

No invalid input from this file should impact availability of OSS or Cloud installations of Airbyte.

**Comment by airbyte-jenny** [comment]
Investigating the original report, it looks like https://github.com/airbytehq/airbyte/pull/7565 was used to resolve the short-term issue by removing a duplicate source definition from airbyte-config/init/src/main/resources/seed/source_definitions.yaml 

This error caused a crash on the onboarding page, at AirbyteRequestService.ts:75 saying there were multiple definitions; this is just a wrapper on making some request to the backend (not entirely obvious which one).  We should be able to reproduce by duplicating a definition locally for testing.

**Comment by airbyte-jenny** [comment]
Modify getLatestSources() and getLatestDefinitions() to catch Throwable.  Look for NoInternet test cases and modify that test case file to include formatting problems and json deserialization problems.
