### ISSUE TITLE
Skip generating empty files - S3 destination

### ISSUE THREAD

**Issue by gitnaveenmanohar** [airbytehq/airbyte#7587]
**Current behavior**:
An empty csv file (_with headers only_) is generated at the end of each postgres CDC sync. This happens even though there are no new insert/delete/update to capture from the source table(s).

**Expected behavior**: 
If there are no new records to pull from the source during CDC sync, skip creating empty files with headers in the destination.

<img width="660" alt="empty_files" src="https://user-images.githubusercontent.com/93374852/140022180-e941dd98-5bc3-41c9-a887-907c785a3c7e.PNG">

**Additional environment details**:
Is this your first time deploying Airbyte: Yes
OS Version / Instance: Local Docker on Windows
Memory / Disk: 16GB / 500 GB SSD
Deployment: Local
Airbyte Version: 0.29.21-alpha
Source name/version: Postgres 0.3.11
Destination name/version: Amazon S3 0.1.12
Step: On Manual Sync - Incremental CDC

**Comment by harshithmullapudi** [comment]
Thanks for this. Team will look into this shortly

**Comment by prconstruct** [comment]
I think this issue is with S3. In my case Mongodb is the source and s3(JSONL) is the destination.  Empty files are created when no records extracted. Could you please prioritize this?

**Comment by prconstruct** [comment]
Hello @sherifnada , could you please let me know when we can expect this bug to be fixed? Also this related S3 destination connector. Whatever source it could be, it ends by creating empty files in S3 when no records are populated by the sync jobs.

**Comment by sherifnada** [comment]
@prconstruct can you help me understand the impact of this on your workflow?

**Comment by prconstruct** [comment]
@sherifnada : we have 200+ tables from different source connectors, loading to S3 using the S3 destination connector. The sync job is used to run as frequently as it could be, some are scheduled to run every minute. There are lambdas that get triggered based on S3 event notifications. If we could restrict these empty files, we could save the execution of lambda.

**Comment by prconstruct** [comment]
@sherifnada: I see many updates happening for Destination S3. It would be really helpful if the empty file generation is fixed.

**Comment by klogdog** [comment]
@sherifnada 
+1 I am also experiencing this issue on a test connector I made before deploying to a customer's system.

The impact is hundreds of thousands of unnecessary writes and then  subsequent cleanup required prior to processing. Why do write, read, delete, of a 0 record update?

**Comment by VitaliiMaltsev** [comment]
this issue was fixed in scope of https://github.com/airbytehq/airbyte/pull/11294
