### ISSUE TITLE
`docker run --rm airbyte/source-oracle:0.3.8 spec` hangs forever

### ISSUE THREAD

**Issue by alsuren** [airbytehq/airbyte#7593]
## Enviroment
- **Airbyte version**:   airbyte/source-oracle:0.3.8
- **OS Version / Instance**: macOS (docker desktop on an M1 mac, so it might be an emulation issue? I will check on a native linux box and edit the issue with my findings)
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-oracle:0.3.8
- **Severity**: Very Low
- **Step where error happened**: `docker run --rm airbyte/source-oracle:0.3.8 spec`

## Current Behavior
This command prints out: 
```
2021-11-03 09:51:40 INFO i.a.i.s.o.OracleSource(main):174 - {} - starting source: class io.airbyte.integrations.source.oracle.OracleSource
```
and then hangs forever, using 100% of a core (docker has 4 cores allocated to it).

## Expected Behavior
`docker run --rm airbyte/source-oracle:0.3.7 spec` takes 6 seconds to complete. I would expect 0.3.8 to take a similar amount of time.

## Logs

There is only 1 line of logs printed
```
2021-11-03 09:51:40 INFO i.a.i.s.o.OracleSource(main):174 - {} - starting source: class io.airbyte.integrations.source.oracle.OracleSource
```
If anyone knows how to make java print a backtrace, I can include that too.

## Steps to Reproduce
1. `docker run --rm airbyte/source-oracle:0.3.8 spec`

## Are you willing to submit a PR?

I am more comfortable with Python than Java (and I only tried the oracle source out of curiosity, rather than a burning desire to interface with oracle dbs), so I might not be the best person to fix this one. If I have issues with other sources then I will definitely submit PRs though.

**Comment by marcosmarxm** [comment]
See issue #2017 closing because is related to Mac M1 deploy and not the connector itself.
