### ISSUE TITLE
Create deployment documentation using HELM Chart

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7602]
### Tell us about the documentation you'd like us to add or update.
Explain in detail on how you can deploy Airbyte using Helm chart

**Comment by marcosmarxm** [comment]
@avaidyanatha this is pretty important, a lot of users are starting using the Airbyte now using the Helm Chart.

**Comment by Amruta-Ranade** [comment]
I think this [doc](https://docs.airbyte.com/deploying-airbyte/on-kubernetes-via-helm) addresses the issue
