### ISSUE TITLE
New Source: Drip

### ISSUE THREAD

**Issue by karinakuz** [airbytehq/airbyte#7604]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
Sandbox account is created, partially filled with the data, received token for private integration, tested apis, tried solve the issue with receiving credentials for public integration, sent letter to support. Added credentials to Last Pass with the name 'Drip'

**Comment by karinakuz** [comment]
Oauth credentials are added to LastPass, tested apis with Bearer for the next streams:
- Accounts https://api.getdrip.com/v2/accounts
- Event_actions https://api.getdrip.com/v2/4069217/event_actions
- Conversions https://api.getdrip.com/v2/4069217/goals
- Subscribers https://api.getdrip.com/v2/4069217/subscribers
- User https://api.getdrip.com/v2/user
- Single-Email Campaigns https://api.getdrip.com/v2/4069217/broadcasts
- Email Series Campaigns https://api.getdrip.com/v2/4069217/campaigns
- Workflows https://api.getdrip.com/v2/4069217/workflows

**Comment by karinakuz** [comment]
Your trial ends on November 17, 2021.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [New Source: Drip](https://app.harvestr.io/components/0/list/JqTLwJOZ2)

**Comment by natikgadzhi** [comment]
We have this issue here: #45983, closing this as duplicate.
