### ISSUE TITLE
Facebook Pages connector show update 0.1.3 but there is only 0.1.2 available

### ISSUE THREAD

**Issue by beatkind** [airbytehq/airbyte#7625]
## Enviroment
- **Airbyte version**:  0.30.25-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Severity**: Medium
- **Step where error happened**: Update connector

## Current Behavior
The UI shows that the latest Facebook pages connector is in the version 0.1.3, when you try to update the connector the worker tries to pull the docker image for this version, but the latest version in the docker registry is 0.1.2. So the worker cannot pull the docker image because it does not exist. 

https://hub.docker.com/r/airbyte/source-facebook-pages/tags

## Expected Behavior
The Facebook connector should not display a new version, or a new version should be published into Docker Hub.

## Steps to Reproduce
1. Update Facebook Pages Connector

**Comment by beatkind** [comment]
It seems like this is the related pull request: https://github.com/airbytehq/airbyte/pull/7440

**Comment by avida** [comment]
Oops, my bad, forgot to publish image, will be ready in ~10 minutes

**Comment by beatkind** [comment]
@avida thanks for publishing, I tested it and works perfect now!

**Comment by avida** [comment]
You are welcome! Thanks for quick report
