### ISSUE TITLE
Sync job does not finish - Mysql to S3

### ISSUE THREAD

**Issue by jefersonmsantos** [airbytehq/airbyte#7641]
## Enviroment
- **Airbyte version**:  example is 0.30.20-alpha
- **OS Version / Instance**: GKE optimized
- **Deployment**: Kubernetes
- **Source Connector and version**: source.-mysql / 0.4.8
- **Destination Connector and version**:destinatio-s3 / 0.1.12
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Executing mysql connector to S3 destination. After read all records, it looks like something gets hanged and the job does not finish.

## Expected Behavior
Finish sync job and store parameters for next sync (CDC).

## Logs
[logs-112-0 (1).txt](https://github.com/airbytehq/airbyte/files/7476716/logs-112-0.1.txt)

<details>
<summary>LOG</summary> 

```

</details>

## Steps to Reproduce
1. Create source from mysql
2. Create destination s3
3. Run sync

**Comment by sherifnada** [comment]
cc @tuliren added to the database project

**Comment by grishick** [comment]
@jefersonmsantos we have made many improvements to MySQL source connector in the year since this issue was filed. Is it still happening?

**Comment by jefersonmsantos** [comment]
@grishick , sorry, stopped using airbyte due to this and other errors. I do not know if it would be solved.

**Comment by grishick** [comment]
Closing this as unreproducible.
