### ISSUE TITLE
attempting to access a workspace you don't have access to should show an error

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7643]
Right now you just see a blank page if you can't access a workspace. In the console you can see `{error":"Project doesn't exist or is not active"}`. 

We should still show the sidebar and have a message in the body saying that the page can't be accessed. This might also be related to how we handle 404s.

**Comment by Jamakase** [comment]
@jrhizor There is small problem with displaying sidebar - almost every it's item requires current workspace.

I think in this case we should display some placeholder and a link ( button ) to redirect to SelectWorkspace page.

**Comment by jrhizor** [comment]
Sounds good to me. Maybe could have the icons greyed out and still have the drop down at the top of the sidebar (just without anything selected)
