### ISSUE TITLE
CI Sandbox for Zenloop

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7646]
## Tell us about the problem you're trying to solve
We need an integration account to test community contribution https://github.com/airbytehq/airbyte/pull/7380

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
Sandbox account with data is created, credentials are added to LastPass with name 'Zenloop', api tested with Bearer token for the streams:
- All surveys https://api.zenloop.com/v1/surveys
- All surveys groups https://api.zenloop.com/v1/survey_groups
- All survey answers https://api.zenloop.com/v1/surveys/{survey_id}/answers
- All surveys group answers https://api.zenloop.com/v1/survey_groups/{survey_group_id}/answers

**Comment by igrankova** [comment]
Reopend by the request from Saj Dider to reactivate sandbox account (expired trial period)

**Comment by igrankova** [comment]
@sajarin,
Found all previous emailing with Karina and tried to contact the person she contacted with. But he is not available anymore. I sent the last email where they provide us the free account as a sandbox to the support operator and hope it could help us to speed up the reactivation.

**Comment by igrankova** [comment]
@sajarin ,
The account is reactivated! If you need something else here, let me know:)
