### ISSUE TITLE
`complete_oauth_flow` is called twice for google ads 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#7650]
## Tell us about the problem you're trying to solve
We seem to be making two calls to `complete_oauth_flow` once we receive an auth code from google, which makes the UI not show any visual success clues. 

The issue is demonstrated in this video: https://www.loom.com/share/6da17af4728c49258871f925c70c5aa1

It's worth noting that creating the source works (the refresh token seems to be retained correctly) but 

## Describe the solution you’d like
we should make only one API call, and show a visual cue that it succeeded.

**Comment by sherifnada** [comment]
assigning to @jrhizor for triage

**Comment by sherifnada** [comment]
also confirmed this happening for salesforce

**Comment by tuliren** [comment]
This is also happening for Github.

**Comment by tuliren** [comment]
@ChristopheDuong, FYI the frontend is fixed now. We need to deploy cloud to pick up this change.
