### ISSUE TITLE
Improve auth flow for google sheets

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#766]
## Tell us about the problem you're trying to solve
Google Sheets currently supports a complicated flow to setup the source connector. There exists a way to make this seamless for the user by using Oauth and redirects in the UI, but is more difficult for Airbyte to implement. 

The 2 options to auth into Gsheets (and most other google app APIs) are: 

1. Service Accounts
1. Oauth (in our case via redirect in the UI)

The gsheets connector currently supports service account only, and contains a cumbersome setup. We could make this setup easier by maintaining service accounts server side, but it would still require the user to enable the APIs via the google dev console which isn't friendly towards technical people. 

The other option is to support OAuth with UI based redirect. The high level changes we would need to make to support this are: 

* We’d register an OAuth token with google that identifies Airbyte as an entity to Google. Once we do this, google gives us a URL where we can redirect users so they can auth with their own google account credentials.
* When configuring the google sheet connector, we’d add a button on the UI that points them to this URL and tell them to click it. Once they grant permission via the Google UI, google will redirect them back to Airbyte, along with a token that was generated based on their authenticated request.
* The UI must capture this token and include it as part of the connector’s configuration (similar to capturing user input, but this would be coming from a server) sent to the backend to configure the server.
* The connector would need to periodically refresh the token if it has an expiration date

A picture from the [Google documentation](https://developers.google.com/identity/protocols/oauth2) describing this process:

![image](https://user-images.githubusercontent.com/6246757/97765756-90cff680-1ad0-11eb-8599-35b3726ef914.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368112300648) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
Superseded by https://github.com/airbytehq/airbyte/issues/6255
