### ISSUE TITLE
Setup new MongoDb Source doesn't work

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7663]
## Enviroment
- **Airbyte version**:  0.30.23-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: MongoDB 0.1.3
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
![image](https://user-images.githubusercontent.com/5154322/140444929-73a0f150-11ac-4120-a0c7-ae4d1773212b.png)

## Expected Behavior
should be able to connect

## Logs
[logs-5ed85463-dedd-4c10-b401-45c02340773c-.txt](https://github.com/airbytehq/airbyte/files/7479962/logs-5ed85463-dedd-4c10-b401-45c02340773c-.txt)

## Steps to Reproduce
1. create a new mongo source using integration account creds
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by andriikorotkov** [comment]
@marcosmarxm, @sherifnada, I have connected directly to the cloud and cannot see any databases named "test". Here are all the databases that have already been created.

![2021-11-08_12-45](https://user-images.githubusercontent.com/88329385/140728700-c80d8f5a-bd71-4142-94cc-670b0f243959.png)

Connecting to an existing database is going well.

![2021-11-08_12-47](https://user-images.githubusercontent.com/88329385/140728920-60131e97-ef02-46a2-aa43-7bf2daf039b8.png)
