### ISSUE TITLE
Source Facebook Marketing: Fix schema fields with $ref displaying in UI

### ISSUE THREAD

**Issue by htrueman** [airbytehq/airbyte#7672]
Issue appeared in https://github.com/airbytehq/airbyte/pull/7605.

## Enviroment
- **Airbyte version**:  0.1.32
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.21
- **Destination Connector and version**: Postgres 0.3.11
- **Severity**: Low
- **Step where error happened**: Setup new connection

## Current Behavior
`null` field types in fields where we use `$ref` in field definition instead of `array` or `object` types. See screenshot attached.

<img width="1310" alt="Screenshot 2021-11-05 at 15 36 19" src="https://user-images.githubusercontent.com/14863647/140519005-96e2ccf6-c304-467f-98d9-841b28ae879d.png">

## Expected Behavior
Field types should be displayed correctly.

## Steps to Reproduce
1. Setup new connection with given source and destination.
2. Check connector settings.

## Are you willing to submit a PR?

I think it should submit someone who worked with UI.

**Comment by sherifnada** [comment]
@htrueman should this be closed?
