### ISSUE TITLE
🎉 Source PayPal transactions: support `OAuth2.0`

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#7706]
## Tell us about the problem you're trying to solve
With the release of Airbyte Cloud, we need to start supporting Oauth for this connector, since it's the recommended way of authenticating users into a SaaS application.

If this connector doesn't support oauth already (i.e: doesn't accept a client_id and client_secret) then we need to update its spec to accept those parameters. There are two ways to do this:

If the connector already supports some auth mechanism like api_key, I suggest that this be a oneof nested inside a top-level field called "authentication":

{ authentication: { type: object oneOf: [ // api key, // oauth ] } }

If the connector only supports webflow oauth, then no changes are needed to the properties format and we will only need to add annotations.

See the connector spec reference in the docs for reference on how a oneof can be implemented.

This should be done in a backwards compatible manner i.e: users currently supplying authentication info in the config's top-level should not be impacted by this change.

## Acceptance criteria
The connector supports oauth webflow authentication with client_id/client_secret in a backwards compatible manner
Oauth properties are annotated properly. See this PR for an example

**Comment by cheyura** [comment]
Access public OAuth client https://developer.paypal.com/developer/applications/edit/QVdwSTJzNU9xUUVlaFVSMVdoMmtQWGVJT29DMy1PdHg3SFVvb3BvTVgtckU5OXl2cG5PaGZhVmQzLW5xZkFxdDVkUUhzdFZXZGFaNFEwSm4=?appname=Airbyte

**Comment by bazarnov** [comment]
Blocked for now on getting "partnership status", and scopes for getting data from streams from prod using OAuth2.0 with user consent method.

**Comment by ycherniaiev** [comment]
@bazarnov Transactions Endpoint is now availbale. Please run this command: 
```
curl -v -X GET https://api-m.sandbox.paypal.com/v1/reporting/transactions?start_date=2021-06-30T00:00:00-0700&end_date=2021-07-28T23:59:59-0700&transaction_id=5TY05013RG002845M&fields=all&page_size=100&page=1 \
-H "Content-Type: application/json" \
-H "Authorization: Bearer A21AAJmcXIInC_CIgdJVMvHy4kwdAuhD-lYCdbHxaE6_VJI7FJYxj3i5WVtIfY8jBbTJA5iCJp9-rU2FDc4sceUy75TWO6ogA"
``` to check this

**Comment by bazarnov** [comment]
We should also test the OAuth flow using basic Postman requests, based on this update, @cheyura could you assist with this?

**Comment by ycherniaiev** [comment]
@bazarnov Sure

**Comment by igrankova** [comment]
Still blocked on getting "partnership status", and scopes for getting data from streams from prod using OAuth2.0 with user consent method.
