### ISSUE TITLE
DEV_ROOT not updated by init steps when docker-compose up

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#771]
## Expected Behavior
When i run `docker-compose up` command, i expect files to be updated in the dev_root (such as the STANDARD_SOURCE files) 
## Current Behavior
This process doesn't seem to be working unless i delete the dev_root directory...

## Steps to Reproduce
1. Make changes to a STANDARD_SOURCE file
1. rebuild etc
1. start docker-compose up

## Severity of the bug for you
 Medium 

## Additional context
*Environment, version, integration...*
Not sure if this is reproducible for everyone or it might be a particularity since i'm running on a linux machine?

**Comment by cgardens** [comment]
The current behavior that you described is the desired behavior. The `dev_root/data` directory is effectively the persistence layer of a database. If every time you ran `compose up` the contents of the database were deleted that would be really unintuitive. 

The idea here is that we want to seed the database one time with the initial sources, but then after that we don't overwrite. If you do want to reseed the database, then yes, you need to manually clear `dev_root`. 

I agree this isn't a super obvious thing and would ask that you propose where in the docs we could mention this behavior to make it clearer. Or if you want to propose a different behavior we look at that, but the desired behavior you described doesn't sound like it will be intuitive.

**Comment by cgardens** [comment]
i think this isn't relevant anymore.
