### ISSUE TITLE
Source Iterable: 401 Client Error - Unauthorized for url

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7735]
## Enviroment
OS Version / Instance: Linux EC2 m5.2xlarge
Deployment: Docker
Airbyte Version: 0.30.20-alpha
Source name: Iterable 0.1.9
destination: Redshift 0.3.19

 Trying iterable for the first time. Does not work. Is it because this is a read_only API key?
 
## Current Behavior
401 Client Error: Unauthorized for url: https://api.iterable.com/api//export/data.json....
Also API key is being output to logs! (edited) 

## Expected Behavior
*Tell us what should happen.*

## Logs
[logs-10916-0.txt](https://github.com/airbytehq/airbyte/files/7496898/logs-10916-0.txt)

## Slack Convo
https://airbytehq.slack.com/archives/C01MFR03D5W/p1635482271308800

## Acceptance Criteria
1. Verify that a read_only key is sufficient for reading all streams. If it is not, then change the documentation to indicate this
2. Ensure that the API key is never logged anywhere like mentioned in the Slack conversation

**Comment by htrueman** [comment]
## Scoping report ##

1. Verify that a read_only key is sufficient for reading all streams. If it is not, then change the documentation to indicate this
> Well, according to the logs, we send requests to `https://api.iterable.com/api//export/data.json`, which is wrong url. I'm not sure how it's even possible. Code seem to be ok. So perhaps it is already fixed, I'll check out on each stream.

2. Ensure that the API key is never logged anywhere like mentioned in the Slack conversation
> We indeed output the `api_key` to the logs, because it's a query param in that case. This exception is raised in `requests` lib. I think to catch this in our CDK and replace the sensitive values with stars.

**Comment by danieldiamond** [comment]
hi @htrueman 

> Well, according to the logs, we send requests to https://api.iterable.com/api//export/data.json, which is wrong url. I'm not sure how it's even possible. Code seem to be ok. So perhaps it is already fixed, I'll check out on each stream.

i've just used the latest iterable version `0.1.13`, which seems to be using a correct URL and still seeing the error

```
401 Client Error: Unauthorized for url: https://api.iterable.com/api/export/data.json?api_key=******&startDateTime=2021-06-01+00%3A00%3A00&endDateTime=2021-07-01+00%3A00%3A00&dataTypeName=emailBounce
```

**Comment by danieldiamond** [comment]
Updates. I just created a new API key with `standard` privileges instead of `read-only` and it appears to work. So it appears to be a permission issue, which is something can be detailed in airbyte iterable connector docs.

**Comment by htrueman** [comment]
> Updates. I just created a new API key with `standard` privileges instead of `read-only` and it appears to work. So it appears to be a permission issue, which is something can be detailed in airbyte iterable connector docs.

Many thanks for your updates. Glad to hear your issue disappeared. I'll update the doc section for Iterable.
By the way, the issue with logging the credentials explicitly is also going to fixed soon, as soon as the https://github.com/airbytehq/airbyte/pull/8211 PR is reviewed and merged.
