### ISSUE TITLE
Document (& improve process for) transferring config across separate deployments

### ISSUE THREAD

**Issue by emily-flambe** [airbytehq/airbyte#7738]
Recently I was having trouble trying to transfer a configuration across separate Airbyte deployments (e.g., `dev` to `prod`). Specifically, the tricky step involves compressing the altered configuration folder in such a way that Airbyte can import it successfully. With some help from @ChristopheDuong (in [this Slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1636143791206800)) I was able to successfully compress my file using this command (where `config-new` is the directory containing the config files I wanted to import):

```
cd config-new
tar zcvf ../config-new.tar.gz *
```

If you try, as I did, to simply google things like "how to compress a folder to TAR", you run into issues - for example, simply running `tar -czf config-new.tar.gz config-new` results in an extraneous directory called `config-new` appearing in the compressed archive, which causes Airbyte to throw an error when trying to import it (specifically it is looking for the VERSION file, and that extra directory messes it up).

Transferring a configuration across deployments (with changes, e.g. find-and-replace to update the workspaceId) seems like an important use case to support - which Airbyte technically does, but currently other people trying to do the same thing I did are likely to hit similar errors, unless they come across the slack thread 😎 

Chris's feature suggestion: maybe the import archive feature should uncompress, try to find the VERSION file in the directory or a subdirectory to determine the “root” of the archive and start importing from there instead

**Comment by marcosmarxm** [comment]
This was relevant when Airbyte had the option to export all configs to a zip file. Today this isn't possible anymore.
You can transfer your instance A to instance B moving the Airbyte Database or you can use Terraform to easily replicate connections across different envs.
