### ISSUE TITLE
Source MSSQL: Connector provides binary values instead of string for hierarchyid, geometry and geography datatypes

### ISSUE THREAD

**Issue by sashaNeshcheret** [airbytehq/airbyte#7739]
In scope of #4270 issue was converted datatypes with wrong values in custom operations, but for following data types the root cause is selecting data as binary instead of string.

## Current Behavior

'hierarchyid'. Airbyte returns binary representation instead of readable one
to test use:
// create table dbo_1_hierarchyid1 (test_column hierarchyid);
// insert dbo_1_hierarchyid1 values ('/1/1/');
// select test_column ,test_column.ToString() AS [Node Text],test_column.GetLevel() [Node Level]
// from dbo_1_hierarchyid1;
'geometry'. Airbyte returns binary representation instead of text one. Proper select query example: SELECT test_column.STAsText() from dbo_1_geometry;
'geography'. Airbyte returns binary representation instead of text one. A proper select query example: SELECT test_column.STAsText() from dbo_1_geography;

## Expected Behavior
A connector should transform source data into an Airbyte datatype without value/meaning losses.
Following data types should be selected as string instead of binary - hierarchyid, geometry and geography.

**Comment by xiaohansong** [comment]
https://github.com/airbytehq/airbyte/pull/14379 it looks like this ticket has addressed this issue. Also I tested this in my local airbyte and seems we can parse it out correctly.

```

2023-12-20 22:11:02 destination > INFO i.a.i.d.e.l.FirstNLogger(log):27 [2023-12-20T22:10:57.803Z] Types #0001: {"id":"1","money":20.07}
2023-12-20 22:11:02 destination > INFO i.a.i.d.e.l.FirstNLogger(log):27 [2023-12-20T22:10:57.803Z] Types #0002: {"id":"1","geometry":"LINESTRING(100 100, 20 180, 180 180)"}
2023-12-20 22:11:02 destination > INFO i.a.i.d.e.l.FirstNLogger(log):27 [2023-12-20T22:10:57.803Z] Types #0003: {"id":"2","geography":"LINESTRING(-122.36 47.656, -122.343 47.656)"}
```
