### ISSUE TITLE
Template Generator Fails without manually installing plop

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#774]
## Expected Behavior
* I expect to be able to follow the [instructions in the readme](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/README.md#creating-a-new-integration) without errors. 
* I should not need to install `plop` myself (or if i do, which isn't ideal but maybe unaboidable, i should be instructed to do so in the readme)

## Current Behavior
* error when running generate

## Steps to Reproduce
* I ran `airbyte-integrations/connector-templates/generator`
* then: `npm run generate`
* got this error:
```
➜  airbyte git:(cgardens/rest_source) cd airbyte-integrations/connector-templates/generator
➜  generator git:(cgardens/rest_source) npm run generate


> airbyte-connector-generator@0.1.0 generate /Users/charles/code/airbyte/airbyte-integrations/connector-templates/generator
> plop

sh: plop: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! airbyte-connector-generator@0.1.0 generate: `plop`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the airbyte-connector-generator@0.1.0 generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/charles/.npm/_logs/2020-11-01T23_13_30_458Z-debug.log
➜  generator git:(cgardens/rest_source) yarn install plop
yarn install v1.22.4
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add plop" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Workaround 
`yarn add plop` before hand seems to fix this issue and I can continue with the rest of the instructions.

@sherifnada would you mind taking a look at this?

**Comment by michel-tricot** [comment]
@sherifnada Is it just missing `npm install`?
