### ISSUE TITLE
Source Facebook Marketing: Support multiple Facebook accounts

### ISSUE THREAD

**Issue by mlavoie-sm360** [airbytehq/airbyte#7740]
## Tell us about the problem you're trying to solve
The Facebook Marketing source currently requires for one and only one account to be provided during the initial configuration. If you manage multiple Facebook Marketing accounts, it would be extremely handy to be able to sync data from many or even from all available Facebook accounts, not just one.

## Describe the solution you’d like
In the configuration, `account_id` should support multiple values and/or no values at all (to trigger a sync of all available accounts).

## Describe the alternative you’ve considered or used
An alternative would be to configure a source for each available account. Agencies can manage dozens (or even hundreds) of different accounts. This process would be impractical the more accounts you manage. If new accounts are added and removed on a regular basis, maintaining such a list becomes chaotic.

## Are you willing to submit a PR?
I will have a PR to share shortly and would greatly appreciate help and feedback making sure the changes are solid.

**Comment by misteryeo** [comment]
Updating the issue to reflect that the PR is blocked on @mlavoie-sm360 until further notice.

**Comment by jagannathsrs** [comment]
Team, any update on this?

**Comment by YowanR** [comment]
Going to reassign this issue to the community :)

**Comment by marcosmarxm** [comment]
Closed by https://github.com/airbytehq/airbyte/pull/33538
