### ISSUE TITLE
WebApp: provide option to select time and date formats

### ISSUE THREAD

**Issue by lizdeika** [airbytehq/airbyte#7745]
## Tell us about the problem you're trying to solve
Time and date formats in UI are not changeable and are everywhere in am/pm for time and MM/DD for dates

## Describe the solution you’d like
Ability to change time and date formats

## Additional context
Related issue but not the same https://github.com/airbytehq/airbyte/issues/7497

**Comment by marcosmarxm** [comment]
Latest version of Airbyte webapp allows you to pick date from a calendar.
