### ISSUE TITLE
CI Sandbox for Sumo Logic

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#7747]
## Tell us about the problem you're trying to solve
We need an integration account for [Sumo Logic API](https://help.sumologic.com/APIs) to test community contribution #7283

**Comment by alafanechere** [comment]
@karinakuz the Sumo Logic stream for this contribution is related to the messages that come from the Search Job API.

**Comment by karinakuz** [comment]
30-days free trial account is created, access credentials are added to the LastPass with the name 'Sumo Logic', api tested for the streams:
- search job https://api.sumologic.com/api/v1/search/jobs/2448F2FCBAB9E9A3
- search job messages https://api.sumologic.com/api/v1/search/jobs/2448F2FCBAB9E9A3/messages?offset=0&limit=10
