### ISSUE TITLE
Source Amazon Seller: add data in Order stream and re-enable acceptance tests

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7751]
## Tell us about the problem you're trying to solve
We need data inside this stream to check_connection and run tests.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by misteryeo** [comment]
@marcosmarxm can you elaborate on what is required for this issue?
