### ISSUE TITLE
Source Github: reactions streams don't display schema in UI and fail sync

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7770]
## Enviroment
- **Airbyte version**:  0.30.31-alpha / Cloud
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Github 0.2.3
- **Destination Connector and version**: Postgres 0.3.11
- **Severity**: Very Low / **Low** / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
The reactions streams don't display in UI the option to show fields.
![image](https://user-images.githubusercontent.com/5154322/140836275-42afe0f6-0d14-47dc-a960-09b606632b83.png)

Selecting reactions and others streams
![image](https://user-images.githubusercontent.com/5154322/140836535-d4635625-1e3d-45db-91dd-153669bec6d1.png)

## Expected Behavior
I'm trying to sync reactions streams.

## Logs
```
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 - Traceback (most recent call last):
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/bin/transform-catalog", line 8, in <module>
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     sys.exit(main())
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 82, in main
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     TransformCatalog().run(args)
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 35, in run
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     self.process_catalog()
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 62, in process_catalog
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 53, in process
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     stream_processors = self.build_stream_processor(
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 134, in build_stream_processor
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     properties = get_field(get_field(stream_config, "json_schema", message), "properties", message)
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 225, in get_field
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 -     raise KeyError(message)
normalization - 2021-11-09 02:11:31 ERROR () LineGobbler(voidCall):82 - KeyError: "'json_schema'.'properties' are not defined for stream commit_comment_reactions"
```

Complete logs: [logs-18-0.txt](https://github.com/airbytehq/airbyte/files/7501565/logs-18-0.txt)

## Steps to Reproduce
1. setup github with integration account
2. setup postgres with normalization
3. select reaction streams 💣 

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by grubberr** [comment]
I see that in github source container is old airbyte-cdk 0.1.25
which incorrectly resolve jsonschema $ref(s).

I have updated airbyte-cdk to the latest version 0.1.33 and it resolved problem with parsing $ref(s)

it looks like we need to bump version of source container and just re-build it with more fresh python dependencies

**Comment by grubberr** [comment]
already resolved in https://github.com/airbytehq/airbyte/issues/6883
