### ISSUE TITLE
  CI Sandbox for Outreach

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7781]
## Tell us about the problem you're trying to solve
Credentials and itnegraiton account for community contribution: #7507

**Comment by karinakuz** [comment]
Get OAuth credentials, filled account with the data, tested APIs for the streams:

- Calls https://api.outreach.io/api/v2/calls
- Events https://api.outreach.io/api/v2/events
- Opportunities https://api.outreach.io/api/v2/opportunities
- Prospects https://api.outreach.io/api/v2/prospects
- Sequences https://api.outreach.io/api/v2/sequences
- Tasks https://api.outreach.io/api/v2/tasks
