### ISSUE TITLE
Custom labels for dynamically created pods in Kube

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#7790]
## Tell us about the problem you're trying to solve
Some K8S cluster may have a tool to enforce some pod labeling requirements (example [here](https://airbytehq.slack.com/archives/C01MFR03D5W/p1636459091332000)). 
We do not yet support custom labelling for dynamically created pods, this prevent K8S users with strong  pod labelling policies to run sync jobs.

## Describe the solution you’d like
A new `JOB_POD_LABELS` variable field in `.env`?

**Comment by evantahler** [comment]
@alafanechere do you know if this is still an issue?

**Comment by Jumanjii** [comment]
Hi @cpdeethree 👋,
We've encountered the same problem, and I'm trying to find a solution. I noticed that you moved it back to the triage stage last week.

Should we explore alternative workarounds, or do you believe a fix might be available soon?

**Comment by ilyasemenov84** [comment]
Just submitted a new [issue](https://github.com/airbytehq/airbyte/issues/33068) related to this one.
