### ISSUE TITLE
Optional Json Logging for Java Platform Code

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#7794]
## Tell us about the problem you're trying to solve
Provide structured logging as a feature-flagged option, not just plaintext logs.

## Describe the solution you’d like
Tech spec https://docs.google.com/document/d/1vasDNWOzoAEaExs_6OlUz5xYzmqISzUSae0DTYlyWxE/edit#

Tasks:

- [ ] Create env var for feature flag, and carry it through the MDC setup.
- [ ] Separate each existing config out to separate files, eliminating null destinations.
- [ ] Modify the code to honor the feature flags for choosing which config file to load, and fall back on log4j2.xml original file.  Add a bootstrapping line to every main() to pick up the log config from the classpath based on feature flags.  Verify that it’s functional locally.
- [ ] Modify the two test cases that check logging content.  Make the secrets redaction test work in both cases.  Duplicate the log format testing to provide a text and a json variant of the already parameterized method (not sure if this can DRY or not).
- [ ] If it exists, modify Jared’s newest logging test case that ensures no missed logs by verifying the line content of logs, and give it an alternate path to compare json logs.  The test itself matches in purpose to what we’ll need for validating that the json implementation is correct anyway.
- [ ] Run testing locally to ensure everything builds and starts up cleanly.  Run a PR build to ensure all of those contextual tests are still passing.
- [ ] Configure gitlab-ci to use the plaintext version of the logs for readability in error output in CI.
- [ ] Get review, tweak, and cut a release of OSS.
- [ ] Configure airbyte-cloud to send a feature flag of whichever format we prefer for rolling out there.  Cut a release of cloud.

**Comment by evantahler** [comment]
Closing this for now, in the future we'll have an epic to ret-think our logging in general.  Step 1 is for all the connectors to emit structured logs (e.g. https://github.com/airbytehq/airbyte/pull/15668) and then we can work on filtering them in display by source/destination/platform and severity. 

cc @salima-airbyte
