### ISSUE TITLE
Readiness and liveness probes for job pods

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#7810]
## Tell us about the problem you're trying to solve
It appears that our job pods are missing readiness / liveness probes. Some K8S cluster configuration might require these to be set. Moreover it might also help to increase our job pods availability.

## Describe the solution you’d like
We should call the PodBuilder with  `.withLivenessProbe` and `.withReadinessProbe` in `KubePodProcess` but I'm not really aware of which command could be run to assert liveness or readiness.

**Comment by davinchia** [comment]
@alafanechere I don't really think this is really applicable today since the kube pod process creation is explicitly checking for these and the default is sufficient. Are users running into this today?

**Comment by alafanechere** [comment]
> @alafanechere I don't really think this is really applicable today since the kube pod process creation is explicitly checking for these and the default is sufficient. Are users running into this today?

I think I opened this issue according to a user request. I think they needed the probes to be set to comply with a global cluster policy they have.
