### ISSUE TITLE
New source: Weatherstack

### ISSUE THREAD

**Issue by darian-heede** [airbytehq/airbyte#7816]
## Tell us about the new connector you’d like to have
* We need a source connector for the [Weatherstack API](https://weatherstack.com/documentation), any destination (e.g. postgres)
* Current version

## Describe the context around this new connector
* We use weather data for modeling purposes
* We run daily syncs
* Required entities/endpoints:
  * Current Weather: api.weatherstack.com/current
  * Historical: api.weatherstack.com/historical
  * Forecast: api.weatherstack.com/forecast
  * Location lookup: api.weatherstack.com/autocomplete

## Are you willing to submit a PR?
Yes

**Comment by harshithmullapudi** [comment]
Hey @darian-heede you are going to pick this ?

**Comment by darian-heede** [comment]
Hi @harshithmullapudi, yes, my colleague Imon and I are working on this one.

**Comment by robgleason** [comment]
Hello, I was looking for sources to work on, and I gave this one a shot. The PR I made is #16473

**Comment by darian-heede** [comment]
Thank you for taking this up @robgleason!
