### ISSUE TITLE
Limit number of parallel connections possible

### ISSUE THREAD

**Issue by mrismailt** [airbytehq/airbyte#7818]
## Tell us about the problem you're trying to solve
I have a single instance (albeit a large one) that is running on EC2 and has multiple connections set up to run every 24 hours. Over time, additional connections are added. It's not crucial that they run at a precise time, just that the data gets loaded roughly once every 24 hours. The problem I'm facing is not being able to control the maximum number of parallel connections that may run at once. For example, if I have 5 connections, each set to run every 24 hours, depending on when I first ran each connection they may coincidentally end up running at the same time every day. If the instance is not large enough the handle this, it will crash. Instead of this possibility, I would like the ability to restrict Airbyte to a max number of parallel runs. Meaning, if it so happens that Airbyte finds itself having to run all 5 connections at once, if I have the max set to 2, it will only run 2 at a time and wait for one to complete before starting the next one. This will ensure that the instance stays up (since for my use case it is not so important that they run at precisely that time, as long as they eventually run)

## Describe the solution you’d like
I would like the ability to restrict Airbyte to a max number of parallel runs. Meaning, if it so happens that Airbyte finds itself having to run all 5 connections at once, if I have the max set to 2, it will only run 2 at a time and wait for one to complete before starting the next one. This will ensure that the instance stays up (since for my use case it is not so important that they run at precisely that time, as long as they eventually run)

## Describe the alternative you’ve considered or used
Since we currently have no way of limiting max parallel runs, I have to manually arrange for the runs to guarantee they don't run at the same time. Meaning, I have to manually run each new connection at a time that no other connection is running and I have to record this somewhere so that I know when *not* to run a future new connection.

**Comment by harshithmullapudi** [comment]
Hey @mrismailt did you discuss this in our slack channel ? If so can you add the slack convo link here? If not you can also post this in our slack channel for more visibility

**Comment by mrismailt** [comment]
@harshithmullapudi  https://airbytehq.slack.com/archives/C021JANJ6TY/p1635952361183700

**Comment by murphpdx** [comment]
Was this ever resolved?

**Comment by marcosmarxm** [comment]
Yes, you can configure the `.env` variables:
https://github.com/airbytehq/airbyte/blob/cd4f445d494bbc43575f50a3c61dc525df2da601/.env#L79-L85

Closing issue because is solved already.
