### ISSUE TITLE
How can I set connector API rate limit?

### ISSUE THREAD

**Issue by z1qaw** [airbytehq/airbyte#7825]
### Tell us about the documentation you'd like us to add or update.
I have my CRM API requests per second restriction to 7 or my API token will be banned. How can I handle it on my custom python connector?

**Comment by harshithmullapudi** [comment]
Hey @z1qaw since the making requests part is hold with the connector do you think we can handle this in our logic. As in can we ensure in our connector code that we won't make more than 7 calls by having some wait time or something ?

**Comment by harshithmullapudi** [comment]
Also @z1qaw would request to post this in connector-development channel since you can get more help there ?

**Comment by z1qaw** [comment]
> 
> 
> Also @z1qaw would request to post this in connector-development channel since you can get more help there ?

How can I do this? Could you help me?

**Comment by marcosmarxm** [comment]
You can create backoff policies to stop sending requests. Today isn't possible to control the number of request per minute the Airbyte CDK makes.
