### ISSUE TITLE
Airbyte 0.30.38-alpha: UncaughtExceptionMapper at `/api/v1/health` IllegalArgumentException: argument "content" is null

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7838]
## Enviroment
- **Airbyte version**:  0.38.38-alpha
- **OS Version / Instance**: MacOS
- **Deployment**: Docker
- **Source Connector and version**: -
- **Destination Connector and version**: -
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
I'd upgraded my instance to latest and got this error. I'll try a fresh instance too.

## Expected Behavior
*Tell us what should happen.*

## Logs
Complete logs: [server-logs (14).txt](https://github.com/airbytehq/airbyte/files/7516761/server-logs.14.txt)

## Steps to Reproduce
1. I had a Airbyte isntance 0.30.25
2. Upgrade to 0.30.38-alpha will throw the error after server start
3. UI and sync works, but it's weird

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
Slack convo from user: https://airbytehq.slack.com/archives/C01MFR03D5W/p1636570085390900

**Comment by marcosmarxm** [comment]
A new instance doesn't throw the error.

**Comment by JeroniMan** [comment]
Hi! I have the same problem, when i try create connection with source MongoDB and destination BigQuery.

Enviroment:
- Airbyte version: 0.32.11-alpha
- OS Version / Instance: Ubuntu 20.04 LTS / GCP
- Deployment: Docker
- Source Connector and version: MongoDb 0.1.8
- Destination Connector and version: BigQuery 0.5.0

I find similar error in my server's logs:
`2021-12-02 23:16:18 ERROR () UncaughtExceptionMapper(toResponse):22 - Uncaught exception
java.lang.IllegalArgumentException: argument "content" is null ... `

@marcosmarxm I don't have access in slack, how did you solve this problem? Thanks.

**Comment by cgardens** [comment]
is this happening on the most recent version of the app?

**Comment by misteryeo** [comment]
@JeroniMan can you confirm that once you've upgraded to the latest version of the app, you no longer experience this issue?

**Comment by marcosmarxm** [comment]
I'll close this due inactivity.
