### ISSUE TITLE
Standardize config labels on source/destination setup

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7841]
## Tell us about the problem you're trying to solve
In setup, some connectors will say “Start Date” while others say “start_date”. This inconsistency in form labels gives the impression to the user that Airbyte isn’t professional

## Describe the solution you’d like
Consistency in how the configuration fields are labelled. These should be readable, like "Start Date" instead of "start_date". 

## Suggested implementation approach
1. in all connectors, find the ones whose `spec.json` does not have a title property. If a connector doesn't have a `spec.json` ask an engineer for help in determining whether it defines the `title` property. 
2. update them in a single PR to have a `title` and `description` property
3. update all connector specifications and bump their versions in dockerfile and index
3. publish the connectors without running tests (use the flag `run-tests=false` in the `/publish` command)

**Comment by igrankova** [comment]
https://docs.google.com/spreadsheets/d/14_gZuRDkofHvmgRdntDWdiB5elUzbAmFaQcQzMKr_VQ/edit?usp=sharing
