### ISSUE TITLE
Connector Logos do not all appear in dropdown selection

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7842]
## Tell us about the problem you're trying to solve
When a user sees the dropdown of connector options for a new source or destination, some have the favicon/logo icon show up next to the name, and other do not. 

## Describe the solution you’d like
Check all connectors available and ensure the logo appears next to them. 

## Implementation Strategy
1. Collect `.svg` logos for all of our currently available connectors in OSS (but first make sure it doesn't already have an icon, check the directory in step 2 below)
2. Place them in `airbyte-config/init/src/main/resources/icons/`
3. Create a PR to update each connector definition in `airbyte-config/init/src/main/resources/seed/source_definitions.yaml` and `airbyte-config/init/src/main/resources/seed/destination_definitions.yaml` to point to the new assets
4. Verify by running Airbyte locally `SUB_BUILD=PLATFORM ./gradlew build && VERSION=dev docker-compose up` that the logos were imported successfully

**Comment by ycherniaiev** [comment]
@antixar @bazarnov @lazebnyi Some of the logos not available on UI are already in https://github.com/airbytehq/airbyte/tree/master/airbyte-config/init/src/main/resources/icons.
Logos that are not on UI **AND** not in https://github.com/airbytehq/airbyte/tree/master/airbyte-config/init/src/main/resources/icons are here https://drive.google.com/drive/folders/13CadeEvCESHnOhoshalV8_h2pXNwizhr

**Comment by ycherniaiev** [comment]
Status on logos as of 24.11.2022
[Logos_Status_24.11.2022.xlsx](https://github.com/airbytehq/airbyte/files/7596575/Logos_Status_24.11.2022.xlsx)
