### ISSUE TITLE
Various UX improvements for Salesforce

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7847]
## Tell us about the problem you're trying to solve
In the setup of the Salesforce configuration, we ask for a date as a required input. This is highly unusual as Salesforce is like a database - it should just sync everything as a full refresh initially. 

## Describe the solution you’d like
We could either remove the field altogether or make this an optional field. For Close.com, we make this an optional field. 
“start_date - The start date to sync data. Leave blank for full sync. Format: YYYY-MM-DD. (e.g. 2021-01-01) “

## Acceptance Criteria

1. Make the `start_date` optional
2. Change the pattern for start date from `YYYY-MM-DDTXX:XX:XXZ` to `YYYY-MM-DD` (but it should still accept previous format for compatbility)
2. add `title` and description to all properties in Salesforce's input spec

**Comment by augan-rymkhan** [comment]
@sherifnada Do we really need to change `start_date` format to `YYYY-MM-DD` if user can enter `2021-11-21T00:00:00Z` when time is not important ?

**Comment by sherifnada** [comment]
@Augan93 it's a nice to have from a UX POV. The ideal scenario really is to have a date picker but until then this makes for a not so great user experience. See the personas section in the UX handbook: https://docs.airbyte.io/connector-development/ux-handbook for more info on why our less technical users might find this option hard to understand
