### ISSUE TITLE
Clarify the setup fields for Source Facebook Marketing

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7848]
## Tell us about the problem you're trying to solve
The fields in the Facebook setup are not organized in a logic order. End Date is optional, but listed first. Users don't understand which fields required or optional. 

## Describe the solution you’d like
1. Start Date should be listed first
2. End Date should be listed after Start Date, and the label changed to End Date (Optional)
3. Custom Insights can be relabelled as “Custom Insights (Optional)” with help text as to what it is. A user sees this configuration and assumed they need to fill something in. Users are confused on whether they should fill something in. They should understand that the connection will work even if they do not fill in anything here. 
4. Account ID should show an example value (eg. 111111111111) in the help text. One user thought it had to start with “cus_” or “act_”  because other tools accept it this way or it's displayed in the Facebook UI this way.

**Comment by bazarnov** [comment]
Closed due to: https://github.com/airbytehq/airbyte/pull/8234#issuecomment-1016248376
