### ISSUE TITLE
Source Postgres: DB values '-Infinity', 'Infinity', 'Nan' are parsed as null

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#7871]
## Current Behavior
**float8,  double precision, float, numeric, decimal, real**: Values '-Infinity', 'Infinity', 'Nan' will not be parsed correctly. Parsed values for all of them are `null`.
Please see:
`case NUMERIC, DECIMAL -> o.put(columnName, nullIfInvalid(() -> r.getBigDecimal(i)));`

## Expected Behavior
Values '-Infinity', 'Infinity', 'Nan' should not be parsed as `null`

**Comment by andriikorotkov** [comment]
Liren added changes that fix this error in his pull request - https://github.com/airbytehq/airbyte/pull/8308
