### ISSUE TITLE
Showing connector docs in UI is broken

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#7874]
## Enviroment
- **Airbyte version**:  0.30.39-alpha
- **OS Version / Instance**: macOS
- **Deployment**:  Docker
- **Source Connector and version**: pokeapi
- **Step where error happened**:  Setup new connection

## Current Behavior
When I click on Setup Guide the window that opens doesn't contain docs.

![Screen Shot 2021-11-11 at 10 17 45 AM](https://user-images.githubusercontent.com/9092207/141349179-1284883a-aec6-4009-94d5-a20622eaf2bf.png)

## Steps to reproduce
* `docker-compose up`
* Go to set up a source. 
* Select poke api
* Select setup guide

## Expected Behavior
The window should contain the docs for that connector

heads up @jrhizor  @isalikov @Jamakase for prioritization
fyi: @avaidyanatha as a stakeholder

**Comment by Jamakase** [comment]
I believe regression was introduced by @benmoriceau somewhere in this PR #7746

**Comment by Jamakase** [comment]
Though we still should display better message in such cases.

**Comment by benmoriceau** [comment]
I am working on a fix at the moment

**Comment by jrhizor** [comment]
@Jamakase this should also be part of the e2e tests.

**Comment by jrhizor** [comment]
fixed by https://github.com/airbytehq/airbyte/pull/7882

**Comment by cgardens** [comment]
thanks everyon!
