### ISSUE TITLE
Source Amplitude: add better response error msg to return error 400 reason file is too big

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7900]
## Tell us about the problem you're trying to solve

When users with large Amplitude data want to sync they receive a 400 error...
From Amplitude docs:
![image](https://user-images.githubusercontent.com/5154322/141402682-5f9a880b-9729-46cf-817b-5841b39bf1b4.png)
https://developers.amplitude.com/docs/export-api

## Describe the solution you’d like
If I receive this error maybe we need to return a better response to user the logs aren't clear.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by connor-napster** [comment]
Whats the best way to push this along?

**Comment by itaseskii** [comment]
I'll claim this issue.
