### ISSUE TITLE
Docker build is not working anymore for webapp

### ISSUE THREAD

**Issue by Jamakase** [airbytehq/airbyte#7907]
Docker build command ( `docker build . `) is not working anymore for webapp. 

It was quite convenient as it allowed to build any image and tag. There is `gradlew :airbyte-webapp:assemble` task now, but it is not convenient as it is difficult to find image and tag it later.

I believe that it should be always possible to just run `docker build . ` in any directory and assemble new image without additional efforts.

**Comment by jrhizor** [comment]
If you run `VERSION=something ./gradlew :airbyte-webapp:assemble` you'll be able to build `airbyte/webapp:something` with a single command. Is that sufficient to make it as convenient?

In order for us to move towards incremental Gradle builds, we need to use a subdirectory to stage files. If specifying the version above is insufficient, should we move the copying logic into the `npm build` command and out of Gradle?

**Comment by Jamakase** [comment]
Oh, I believe that's enough then. I was not able to find it in docs.
