### ISSUE TITLE
Obtain public developer application for the Monday.com source connector

### ISSUE THREAD

**Issue by cheyura** [airbytehq/airbyte#7909]
## Tell us about the problem you're trying to solve
Obtain a public developer application for the Monday.com connector like specified in #6070

## Requirements to obtain public developer application
#6070

**Comment by igrankova** [comment]
"The Public App - OAuth needs to be done to submit an app
LastPass creds name: Monday. 
The OAuth flow passed successful"

**Comment by igrankova** [comment]
The App is public.
