### ISSUE TITLE
(CDC) Source Postgres: add support for tsquery type

### ISSUE THREAD

**Issue by yurii-bidiuk** [airbytehq/airbyte#7911]
When running logical replication (CDC), `tsquery` values are transmitted as `null`.
Add support to represent `tsquery` values in the right way.

**Comment by alexandr-shegeda** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/7911?planning-poker) with ZenHub @yurii-bidiuk
