### ISSUE TITLE
add ARM build for platform

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7930]
We're going to regularly run into issues like https://github.com/airbytehq/airbyte/issues/7929 if we aren't able to detect regressions.

**Comment by evantahler** [comment]
Research and notes @ https://www.notion.so/Multiplatform-Docker-Builds-6c3c441d951f4410bdf47a8125fbb195

**Comment by davinchia** [comment]
E.g. we see multi-arch when looking at the images on docker.

<img width="1568" alt="Screenshot 2022-05-12 at 4 52 40 PM" src="https://user-images.githubusercontent.com/9772859/168031970-e4b3a08b-29eb-462e-ad8b-ad46a4313c82.png">
