### ISSUE TITLE
Destination BigQuery Denormalized: error message: JSON table encountered too many errors using Source Bing Ads

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7934]
## Enviroment
>Hey everyone! I hope you're all save and well
I need some help, for sure I'm missing something, hope you can help...
All connectors I have, it works but all tables in bigquery are empty after the sync...
The weird thing is that all tables are created but they are empty... Does someone have the same problem?
Is this your first time deploying Airbyte: NO
OS Version / Instance: Ubuntu Desktop 20.04 LTS
Memory / Disk: 16Gb / 512 ssd
Deployment: LOCAL
Airbyte Version: LAST
Bing Ads connector version - 0.1.1
Bigquery connector version - 0.5.0

## Current Behavior
Trying to sync Source Bing Ads to BigQuery Denormalized.

## Expected Behavior
*Tell us what should happen.*

## Logs
Complete logs: [log_airbyte_error.txt](https://github.com/airbytehq/airbyte/files/7530377/log_airbyte_error.txt)

## Steps to Reproduce
I couldn't reproduce this error using our Integration Account. Maybe need to add a specific values in our account.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
[slack convo](https://airbytehq.slack.com/archives/C01MFR03D5W/p1636391984286300)

**Comment by VitaliiMaltsev** [comment]
can not reproduce this issue with latest version of BigQuery Denormalized connector. Did not receive any response from contributor is it persists at the moment. 
I believe we can close this one and reopen this ticket if we would have similar errors, cause [this](https://github.com/airbytehq/airbyte/issues/7938) feature merged into master. 
@marcosmarxm WDYT?

**Comment by VitaliiMaltsev** [comment]
@subodh1810 please advise
