### ISSUE TITLE
[EPIC] Change JsonSchemaPrimitive to a class

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#7944]
## Tell us about the problem you're trying to solve
According to conversation in https://github.com/airbytehq/airbyte/pull/7859 it's needed to change JsonSchemaPrimitive from enum to class which allows more flexible specifications

**Comment by tuliren** [comment]
- This issue needs a design doc first. We need to fully understand its impact on the destination side.
- If the implementation does not break destinations, carry on according to the design doc.
- If the implementation does break destinations, we need to
  - Update the destinations first (probably in `dbt`) to be compatible with both the date + time format, as well as the date-only format first.
  - Then make the change on the source side.

**Comment by VitaliiMaltsev** [comment]
@tuliren created design doc https://docs.google.com/document/d/1MxVLBuN2xDye0IPKsCsp4L5HLU6JosnWRxp3kEekpgw/edit. Please review
