### ISSUE TITLE
sanbox crendentials for : New source VTEX

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7954]
## Tell us about the problem you're trying to solve
Sandbox cred for #7791

**Comment by karinakuz** [comment]
Sent message to support about sandbox account

**Comment by karinakuz** [comment]
Sent message to support about sandbox account https://vtex.com/us-en/contact/ (Nov 19)
Sent letter to support about sandbox account  info@vtex.com (Dec 06)
No one answer received.

**Comment by harshithmullapudi** [comment]
Hey @karinakuz any response here ?

**Comment by karinakuz** [comment]
Hi @harshithmullapudi, today I've received a letter from VTEX with request  for more details about Airbyte and I've sent an answer. Waiting for updates from VTEX.

**Comment by jlpetracca** [comment]
UP
