### ISSUE TITLE
SAT: Configured catalog should be taken from discovery result by default

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#7955]
## Tell us about the problem you're trying to solve
Currently SAT runs using configured catalogs from files like `integration_tests/configured_catalog.json` etc
This makes it difficult to track if all streams were tested. Testing not all streams should be an exceptional scenario, so by default SAT will take configured catalog from discovery command and use the default configuration.

## Describe the solution you’d like
If you commit `configured_catalog_path` in `acceptance-test-config.yml` file it will default to generated catalog from discovery command.

## Describe the alternative you’ve considered or used
Generate configured catalog with the following script:
```python
from airbyte_cdk.models import ConfiguredAirbyteCatalog, AirbyteMessage, ConfiguredAirbyteStream, DestinationSyncMode


record = AirbyteMessage.parse_raw(input())
for stream in record.catalog.streams:
    stream.json_schema = {}
streams = [
    ConfiguredAirbyteStream(
        stream=stream,
        sync_mode=stream.supported_sync_modes[0],
        destination_sync_mode=DestinationSyncMode.append
    ) for stream in record.catalog.streams
]
configured_catalog = ConfiguredAirbyteCatalog(streams=streams)
print(configured_catalog.json(indent=4))
```

## Are you willing to submit a PR?
yes

**Comment by sherifnada** [comment]
@keu I was under the impression that this is the purpose of the `excluded_streams` property in acceptance-test-config.yml. That is: if a stream is not specified in that property (perhaps with a `reason` flag -- we don't currently have this) then SAT should fail

**Comment by keu** [comment]
> @keu I was under the impression that this is the purpose of the `excluded_streams` property in acceptance-test-config.yml. That is: if a stream is not specified in that property (perhaps with a `reason` flag -- we don't currently have this) then SAT should fail

@sherifnada , yeah, being there, but recently found out that it is not true

**Comment by sherifnada** [comment]
@keu should we fix that instead?

**Comment by keu** [comment]
> @keu do you know why not? should we fix that instead?

@sherifnada I think it was left as a TODO, so we should fix it.

**Comment by augan-rymkhan** [comment]
Check if `configured_catalog_path ` is not provided then generate `ConfiguredAirbyteCatalog` from `discovered_catalog` fixture in `[configured_catalog_fixture](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/source-acceptance-test/source_acceptance_test/conftest.py#L63)`.
