### ISSUE TITLE
Sentry: Investigate env configuration of Sentry

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#7957]
Document here how Sentry can be configured using env.
...
Propose a way to make it optional.
...
Integration with Sentry on non-cloud Airbyte is outside of the scope.

**Comment by avida** [comment]
# Sentry.io investigation report

Sentry is platform for automatically reporting and monitoring exceptions for application. It comes with cdk that available for about 30 languages including python, java and react js. We are already using Sentry.io in out frontend application.

## Configuration
To start using Sentry we need only to know data source name (DSN) which can be found on `Client Keys (DSN)` tab from project settings.
	
For python it uses sys.excepthook mechanism to report unhandled exceptions, so to make it work we need to call sentry_sdk.init function:

```python
import sentry_sdk
sentry_sdk.init(
    "<DSN>",
    traces_sample_rate=1.0
)
```
traces_sample_rate is parameter configuring number of error sent from 0 % (0) up to 100 % (1.0). Also it could be controlled dynamicly by setting `traces_sampler` parameter.
## Logging to Sentry and trace rate
As it mentioned above Sentry captures unhandled exception over sys.excepthooks.
Also it could log handled exception and custom messages: 
```python
sentry_sdk.capture_message('Something went wrong')
try:
    raise Exception("")
except Exception as e:
    sentry_sdk.capture_exception(e)
```

Also Sentry has python logging integration and by default captures all logging records with `error` and `exception` log level.
Details: https://docs.sentry.io/platforms/python/guides/logging/
## Context

It could be provided additional information by setting context :

```python
sentry_sdk.set_context("context name", <context dict> )
```
Every time we set context with same name previous context is overriden. There could be more than one context with diffrent names.

Details here: https://docs.sentry.io/platforms/python/enriching-events/context/

## Breadcrumbs

Breadcrumbs are trail of events that lead to an error. 

```python
sentry_sdk.add_breadcrumb(
    category="request",
    message=f"Request {url}",
    data=<data dict>
    level='info',
    )
```

Breadcrumbs can be filtered/dropped by setting before_breadcrumb hook:
```python
def before_breadcrumb(crumb, hint):
    return None

sentry_sdk.init(
    ...
    before_breadcrumb=before_breadcrumb
)
```

Maximum amount of breadcrumbs can be configured by `max_breadcrumbs` keyword for `sentry_sdk.init` function


More details: https://docs.sentry.io/platforms/python/enriching-events/breadcrumbs/

## Sensitive info scrubbing

Every event that being sent by sentry could be filtered/modified by before_send hook:
```python
def before_send(event, hint):
    event["sensitive-info"] = None
    return event

sentry_sdk.init(before_send=before_send)
```
Breadcrumbs can be stripped as well

More details: https://docs.sentry.io/platforms/python/configuration/filtering/, 
https://docs.sentry.io/platforms/python/data-management/sensitive-data/


## Tags and Environments
To filter and categorize issues we can use tags:

```python
sentry_cdk.set_tag("source", "facebook-marketing")
```
Also there is built in "environment" tag that being set on init method:
```python
sentry_sdk.init(
    ...
    environment="cloud"
)

```
Details: https://docs.sentry.io/platforms/python/enriching-events/tags/


## Performance monitoring
Sentry also performance performance monitoring service. Depends on platfrom it could be [automatic](https://docs.sentry.io/platforms/python/performance/instrumentation/automatic-instrumentation/) (for Django, Flask, Celery etc) and [custom](https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/)

To enable custom performance monitoring we need mark code that we are interested with Sentry transaction. To inspect performance inside single transaction spans could be used, for example running  this code:
```python
def sleep_func():
    with sentry_sdk.start_span(op="sleep func span", description=sleep_func.__name__):
        time.sleep(1)
def time_func():
    with sentry_sdk.start_transaction(op="task", name=time_func.__name__):
        with sentry_sdk.start_span(op="time func span", description=time_func.__name__):
            time.sleep(0.3)
        sleep_func()
time_func()
```
would create an event on Sentry platform with unique id and detailed execution chart:
![image](https://user-images.githubusercontent.com/437607/142204898-0a3eb936-2506-48ac-bd34-e76c1aaa3068.png)


Details: https://docs.sentry.io/platforms/python/performance/

## Testing

Sentry could be used to trace pytest logs with pytest-sentry plugin: https://pypi.org/project/pytest-sentry/

To test Sentry in our unittest we can either override [transport parameter](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/consts.py#L46) with custom [callable](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/transport.py) or setup custom server like they do on their own [unittests](https://github.com/getsentry/sentry-python/blob/master/tests/test_transport.py)

**Comment by sherifnada** [comment]
@avida this looks great. Thanks for the thorough investigation. I really like everything I'm seeing here. We'll need to be extra careful about the records being recorded. Some requirements I see to implement this in production fully: 

1. we probably don't want to send any events from local or dev environments, maybe even OSS as well. Is it possible for sentry to automatically be turned on if a certain env variable is present, otherwise it would operate as a blackhole? 
2. I would love to give it a try on a connector, taking special care to test that secrets are not sent to sentry. How can we do this without having to do custom code for the connector? 

would love to give it a try on an existing connector

**Comment by avida** [comment]
@sherifnada  Thanks!

1. Yes, we can configure this in the code. To make sentry work its enough to provide unique DSN (data source name) and also we going to need some variable to set connector name for filtering (not sure  if its possible to get connector's name from CDK code) 
2. I would love do this as well, planning to do this ASAP (after resolving github check_connection defect) It would require to make changes in the CDK code (and update CDK version for connector).

**Comment by RomanKrasavtsev** [comment]
Should we now use `JOB_ERROR_REPORTING_SENTRY_DSN` instead of `SENTRY_DSN` env var? 

https://github.com/airbytehq/airbyte/blob/3a9aa97d903b03c0d5ee8b673a4aaa3542952ae0/docker-compose.yaml#L101
https://github.com/airbytehq/airbyte/blob/4e236b5b42213572b759f07541891cb593e69d68/airbyte-workers/src/main/resources/application.yml#L116
