### ISSUE TITLE
Sentry: Test integration for one of the connectors

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#7959]
We need to 

- implement test integration with Sentry for one of our connectors and 
- deploy it in sandbox cloud env (if any exist).

Later this can be moved to CDK and enabled for all connectors if the MVP will be successful.

**Comment by tuliren** [comment]
@keu, the current approach only works for Python source connector. Is there any plan to test it for Java source connectors?

**Comment by keu** [comment]
@tuliren Sentry has integration with Java apps as well, https://docs.sentry.io/platforms/java/
The original plan was about delivering MVP, AFAIK there is no such thing as CDK for Java we will have test integration for each Java connector by implementing the same steps described in the MVP plan for Python.
