### ISSUE TITLE
Cannot Sync records with timezone +00:00 when last cursor field was +07:00

### ISSUE THREAD

**Issue by ayyoubmaulana** [airbytehq/airbyte#7962]
## Enviroment
- **Airbyte version**:  example is 0.30.15-alpha
- **Deployment**: Docker
- **Source Connector and version**: MySQL version 0.4.4
- **Destination Connector and version**: BigQuery version 0.3.7
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
i replicate mysql table using airbyte 0.30.15, and i set cursor : updated_at
when updated_at +7 record get successfully but not success when updated_at +00:00
any airbyte version updated that has capability to convert timezone in cursor

![Screenshot - 2021-11-11T095639 308](https://user-images.githubusercontent.com/53739205/141719070-9f2bde41-d475-4701-bafb-dea0e355d42b.png)

there is no error but for the records with +00:00 timezone will not updated in BigQuery because in cursor airbyte use +07:00, So for all records with +00:00 will never be sync to BQ or not updated in BQ

![Screenshot - 2021-11-12T091600 336](https://user-images.githubusercontent.com/53739205/141719133-67c72e67-4ea9-4385-813b-044770d7a8f1.png)

## Expected Behavior
Should be convert timezone automatically from +7:00 to +0:00 or vice versa, so for records with +00:00 timezone can sync to Bigquery even the last cursor was +07:00

**Comment by ayyoubmaulana** [comment]
I will try to syncronize again using newer version of Airbyte

**Comment by misteryeo** [comment]
Any update on this @ayyoubmaulana?

**Comment by misteryeo** [comment]
Closing as we haven't heard back. Please reopen if this persists.
