### ISSUE TITLE
Airbyte should clearly expose a persistence interface for connectors across syncs

### ISSUE THREAD

**Issue by marc-marketparts** [airbytehq/airbyte#7984]
## Tell us about the problem you're trying to solve
I am implementing a new python source to synchronize Neo4j graph database.
As schemas are dynamic, and not constraint in this type of database, we fetch it by sending a specific Neo4j query, which scans a sample of the database.
This query can takes a long time (minutes) depending on the db volumetry and available server resources.
So I would like to implement caching of the schemas for all calls but the discover step.

To make it worked accross syncs, the source need to have access to a persistent area, to store and read cached data.

## Describe the solution you’d like
As Airbyte handles the start/stop of each connector container, Airbyte should create a specific shared volume and make it available for sources and destinations that need some persistence, the same way Airbyte does for its core components (db noteworthy).
Airbyte should manage connector namespaces in that volume too, to avoid any risk of collision.

NB : if the current Airbyte implementation handle this use case already, the documentation should clearly describe it.

## Describe the alternative you’ve considered or used
My current implementation uses the /local folder on my source container which is mapped to /tmp/airbyte_local AFAIK.
It works on docker desktop but I did not test it on k8s (it would not on multi-pods probably), and I did not found any detailed information about the use of this folder, or other mounted directories. 

## Additional context
N/A

## Are you willing to submit a PR?
No

**Comment by sherifnada** [comment]
The persistence interface currently availabe is the STATE message. There are currently no plans to add another interface. Please re-open if a separate mechanism is needed
