### ISSUE TITLE
improve async loading of workspaces

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7985]
We should either load all workspaces in async or only load them when the user clicks on the change workspace popup.

This costs us 1-2s of loading time and we might not even need these resources.

**Comment by jrhizor** [comment]
Specifically, the goal on Cloud should be for the onboarding workflow for a new workspace to appear as quickly as possible. Are there any low-hanging fruit for speeding this up?

**Comment by jrhizor** [comment]
Should we have a backend endpoint for just showing if onboarding is required to remove the number of requests?

**Comment by jrhizor** [comment]
The backend also has a very slow `web_backend/connections/list` call for existing workspaces.

**Comment by jrhizor** [comment]
@Jamakase can look at job polling improvements for the onboarding flow.

**Comment by timroes** [comment]
This issue is now meant to only track async loading of workspaces.

The slowness of `web_backend/connections/list` should be solved via #10056 and improving the performance of the onboarding state is tracked via #10403
