### ISSUE TITLE
Add Scylladb in the connector index 

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7988]
## Tell us about the problem you're trying to solve
Community PR adds this new destination: https://github.com/airbytehq/airbyte/pull/7468
All tests passed but we need a better technical review. I addd this issue to add this connector in connector index after this happens.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by evantahler** [comment]
Looks like it's added!

https://github.com/airbytehq/airbyte/blob/d8b07fa4b8e6fd842416cfec3d7089f3461738ae/airbyte-config/init/src/main/resources/seed/destination_definitions.yaml#L304-L310
