### ISSUE TITLE
Automate seed spec updates

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#7996]
## Tell us about the problem you're trying to solve
The existing process of updating seed connector specs is somewhat cumbersome (described [here](https://github.com/airbytehq/airbyte/tree/a534bb2a8f29b20e3cc7c52fef1bc3c34783695d/airbyte-config/specs)). It requires our engineers and contractors to run a separate gradle command after updating connector definitions in the seed and commit another change to the PR. 

This step is easy to forget and results in broken master builds if forgotten. It is also a step that touches internals of the platform which connector developers shouldn't need to worry about, and since it is the same every time it is asking to be automated.

See the slack thread that inspired this ticket here: https://airbytehq.slack.com/archives/C0229LM09T4/p1636512557316000

## Describe the solution you’d like
To solve this, we should have gradle automatically fetch these specs as part of the build and write them to a resource file in the build directory, rather than having a human manually run a command and write the changes to a file in the git repo.

The downside of this is that it will add more time to the platform build, as it cannot read the existing spec file from the git repo to see which specs have already been downloaded, and instead needs to download them fresh from GCS every time. Part of this ticket will involve evaluating this added build time to determine if it is too high. Gradle caching should be explored to try to improve the local development experience here.

## Describe the alternative you’ve considered or used
An alternative approach is having the build or github auto-commit the spec file changes to the git repo whenever changes are made to the seed definitions. However, this is a more controversial approach which we have avoided in the past, and should likely only be chosen if we holistically change our thinking about auto-commits, i.e. with formatting as well.

## Are you willing to submit a PR?
Yes

**Comment by lmossman** [comment]
@sherifnada do you have an idea of the urgency around this? We are trying to decide how it fits with our Q4 priorities, so I'd like to know if this "generate seed spec" process is still causing a lot of headaches with the connector teams

**Comment by sherifnada** [comment]
not q4 urgent

**Comment by davinchia** [comment]
@lmossman is this still relevant?

**Comment by sherifnada** [comment]
I believe it is done already

**Comment by lmossman** [comment]
Actually I don't think we ever did this - AFAIK when a connector definition is changed, that change still needs to be manually applied to the seed resource files through a gradle command (unless someone made a change to automate this that I am unaware of?). This ticket was about automating that process. 
@sherifnada do you have a sense of if this is still causing any headaches for the connectors team? I haven't noticed OSS build failures resulting from this in a while - that had been the main motivation for this in the past. Maybe people are just used to applying these seed changes now when merging connector definition changes?

**Comment by sherifnada** [comment]
@lmossman I believe we now do this as part of the work done in https://github.com/airbytehq/airbyte/pull/11712
