### ISSUE TITLE
Configure a custom list of Survey Monkey IDs to pull in instead of pulling all surveys

### ISSUE THREAD

**Issue by danieldiamond** [airbytehq/airbyte#7997]
## Tell us about the problem you're trying to solve
Survey monkey is pulling data in each stream for all surveys. this is blowing our API limits

## Describe the solution you’d like
Ability to filter a specific list of survey IDs in the configuration step

## Describe the alternative you’ve considered or used
Can't think of an alternative

**Comment by sherifnada** [comment]
Great call @danieldiamond -- will follow up with ETAs in a few days once we've done some backlog work
