### ISSUE TITLE
Write tech spec for integrating with Billing vendor

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#7999]
### Tell us about the documentation you'd like us to add or update.
Once we have finalized our decision for which billing vendor we go with, we need to write a tech spec for integrating our system with the billing vendor.

### If applicable, add links to the relevant docs that should be updated

**Comment by cgardens** [comment]
spec: https://docs.google.com/document/d/1WLr7Leaj5Iyy5bBEjr1TGhNL8HhSB_evbM_psEwKyAI/edit
