### ISSUE TITLE
Add ability to specify schemas to MS SQL source connector

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#8014]
## Tell us about the problem you're trying to solve
The problem applies to MSSQL but can also apply to any kind of SQL connection.
Airbyte connection settings is unusable when source has hundreds or thousands of tables.
UX wise, the connection settings page for big databases is terrible and unusable.

## Describe the solution you’d like
In the Connection settings, it would be interesting to specify the schemas that we want to sync. Same thing applies to selecting the sync settings for all tables (Linked to issue #4586). It would be nice to have the resource's type also (table, view) as I don't necessarily want to sync the views (for instance); we need a feature to filter those out.

## Describe the alternative you’ve considered or used
Waste hours and click on checkboxes of the tables I want to sync (UI is also slow and not very responsive)

## Additional context
Use case: we have a client that we need to sync all the tables (1629). They use MSSQL so it's a Database-Schema-Table concept.
When setting the source connection we specify the source Database, which is fine, however, in a MSSQL database we can have multiple schemas and those schemas can have A LOT of tables each. When I arrive on the Connection settings page, I have all of the schemas which the user (source) has access to. Which results the connection settings page to have thousands of source resources (tables and views)

**Comment by mkhokh-33** [comment]
hi @jrhizor , @Jamakase, @misteryeo
This changes requires UI  changes. Here is document with some proposals - https://docs.google.com/document/d/1tANl8-KFRa_6ddP7akSeRTFpwPuKwL8CnAmWEH6YgwA/edit.
could you please have a look and provide me with possible requirements

**Comment by grishick** [comment]
This is already solved for Postgres
<img width="684" alt="Screen Shot 2022-07-13 at 2 33 56 PM" src="https://user-images.githubusercontent.com/1310940/178840703-a48b2cc6-bf8b-41ca-a320-6d66893342ad.png">

**Comment by sashaNeshcheret** [comment]
After last changes this issue require adding ability to specify list of schemas that should be discovered during setting connectors up.
So in scope of this issue we need:
- add optional field "Schemas" to spec (for backward compatibility);
- handle list of schemas during discovery, if it is empty, all existing schemas will be discovered;
- add or updated existing tests with new functionality;

**Comment by sashaNeshcheret** [comment]
Open question: should we add default value to "Shemas" field, for mssql it is "dbo", or leave the field as empty for discovering all schemas as previously.
@grishick

**Comment by grishick** [comment]
> Open question: should we add default value to "Shemas" field, for mssql it is "dbo", or leave the field as empty for discovering all schemas as previously. @grishick

I'd say let's add default "dbo", in order to avoid running into the problem with schema response being too large during connector setup.
