### ISSUE TITLE
Blotout and Airbyte

### ISSUE THREAD

**Issue by ojasviharsola** [airbytehq/airbyte#8022]
At Blotout, we appreciate Airbyte’s work in enabling security and privacy-focused teams to build an EL+T stack inside of their VPC -- in infrastructure they own and operate (vs. wrapping a VPC around 3P data infrastructure).

We have been and will continue to remain avid contributors to the Airbyte ecosystem -- we moved from Meltano because we appreciated what the vision for Airbyte (previously via MIT) could do to make data safer for enterprises by keeping it in their own networks.
 
### What is Blotout?
Blotout is a single-tenant CDP and Analytics platform that lets enterprises collect, manage, and activate customer data from within their own lake or warehouse. It replaces SaaS offerings with a lossless and compliant platform that operates within a company's own VPC.
### How does Blotout deploy with its customers?
- Blotout serves the ‘Bring your Cloud’ use case enabling software in customer VPC, delivered via Terraform and updated via Argo CD. Blotout has no access to code or data in this use case.
- Blotout serves the ‘Build your Cloud as a Managed Service’ use case enabling hardware on 250 data centers and software that is accessible only to Customer, delivered via Terraform and updated via Argo CD. Blotout has no access to code or data in this case.
### What product use cases does Blotout solve for?
1. *Cross platform analytics and marketing attribution*
In this use case, Blotout does not use Airbyte. Cross platform clickstream data is collected and unified for customers in their control.
2. *Customer data platform, analytics, marketing attribution, and marketing activation*
In this use case, Blotout uses Airbyte as an API service and has custom developed UI based DBT models that unifies customer journeys, and customer profiles using a no code toolkit. Blotout provided Native SDK and Airbyte API for EL + T are used to bring data that is then normalized for analytics, attribution, and eventually data activation.
3. *Infrastructure modernization*
This use case works like the previous one, but the native SDK is optional. It allows data pulls via the Airbyte API but uses Blotout normalization engine to provide a data lake (or warehouse) that has a measurement, attribution, and activation stack built in.
We are filing this as a public Github issue to confirm that Airbyte is appropriate to use in the Blotout stack under the Elastic License and that it will remain open source.

**Comment by marcosmarxm** [comment]
Closing the issue @ojasviharsola feel free to submit a PR with the documentation.
