### ISSUE TITLE
Source FB Marketing: Deprecate the `Insights Days per job` parameter

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8027]
## Tell us about the problem you're trying to solve
A question from a user: 

> For the Facebook Marketing API, how do I know if I have a lot of data? Put another way, how could I spot if I have too much data for a given time period and thus calibrate my time period to suit the size of my data?

![image](https://user-images.githubusercontent.com/6246757/142080944-267bc3ea-7db6-4248-8846-94c12d071e75.png)

IMO exposing this option was a tactical error on our part. Like described in our new [UX handbook](https://docs.airbyte.io/connector-development/ux-handbook#input-configuration), input configuration like this is an implementation detail and should not be offloaded to the user. We should just remove it and use the default value of 1. 

## Acceptance Criteria
1. option is removed from spec.json (in a backwards compatible way)
2. a sensible value is chosen by default

**Comment by misteryeo** [comment]
Adding this comment for visibility - PR is ready to be merged but pending #8385

**Comment by bazarnov** [comment]
Closed due to: https://github.com/airbytehq/airbyte/pull/8234#issuecomment-1016248376
