### ISSUE TITLE
Can't deploy airbyte-minio to GKE Autopilot

### ISSUE THREAD

**Issue by yu-iskw** [airbytehq/airbyte#8033]
## Enviroment
- **Airbyte version**:  v0.32.0-alpha
- **OS Version / Instance**: macOS 11.6
- **Deployment**: kubernetes (GKE Autopilot)
- **Severity**: TBA (Very Low / Low / Medium / High / Critical)
- **Step where error happened**: Deploy

## Current Behavior
When I tried to deploy airbyte v0.32.0-alpha with `kubectl apply -k kube/overlays/stable-with-resource-limits` to GKE Autopilot, only `airbyte-minio` was not launched due to the constrain of GKE Autopilot.

## Expected Behavior
The pod of `airbyte-minio` has to be deployed.

## Logs
```bash
Error from server ([denied by autogke-no-host-port] container airbyte-minio specifies a host port; disallowed in Autopilot. Requesting user: <xxxxx@xxxxx.com> and groups: <["system:authenticated"]>): error when creating "kube/overlays/stable-with-resource-limits": admission webhook "validation.gatekeeper.sh" denied the request: [denied by autogke-no-host-port] container airbyte-minio specifies a host port; disallowed in Autopilot. Requesting user: <xxxxx@xxxxx.com> and groups: <["system:authenticated"]>
```

## Steps to Reproduce
1. Launch a GKE Autopilot cluster
2. Deploy airbyte v0.32.0-alpha with `kubectl apply -k kube/overlays/stable-with-resource-limits`

## Are you willing to submit a PR?
I would love to, but I have no idea to completely solve it at the moment.

**Comment by spacecowboy** [comment]
Also ran into this today

**Comment by yu-iskw** [comment]
@spacecowboy Thank you for solving the issue.

**Comment by spacecowboy** [comment]
> @spacecowboy Thank you for solving the issue.

Thanks ;D but it was actually @jrhizor that solved it.

**Comment by spacecowboy** [comment]
But I can confirm that the fix will work - it's what I did locally to workaround it
