### ISSUE TITLE
Source Google Search Console: `/test connector` command is failing on github

### ISSUE THREAD

**Issue by Zirochkaa** [airbytehq/airbyte#8038]
## Current Behavior
There are 3 failed test runs: [this](https://github.com/airbytehq/airbyte/runs/4207908627?check_suite_focus=true), [this](https://github.com/airbytehq/airbyte/runs/4208278840?check_suite_focus=true) and [this](https://github.com/airbytehq/airbyte/runs/4228214502?check_suite_focus=true). They all have one error - `Process 'command 'docker'' finished with non-zero exit value 137`. Judging by [this](https://stackoverflow.com/questions/38967991/why-are-my-gradle-builds-dying-with-exit-code-137/39705290#39705290) answer on stackoverflow there is not enough memory. Maybe we need to increase the instance used for testing in CI.

Locally tests are green.
![image](https://user-images.githubusercontent.com/19872253/142154230-4960c846-9454-469f-be76-8002f0acb893.png)

Here is my computer configuration:
![image](https://user-images.githubusercontent.com/19872253/142154200-10656f42-75fb-443a-87e8-220d5fd1be27.png)

## Expected Behavior
Tests should finish without `Process 'command 'docker'' finished with non-zero exit value 137` error.

## Are you willing to submit a PR?
Remove this with your answer.

**Comment by sherifnada** [comment]
@Zirochkaa could the issue be somewhere in SAT? iirc it accumulates records in memory. if this is a very high volume connector then that might be related? 

but the build is running on an AWS c5.2xlarge which has 8 CPUs and 16 cores, so i'm a little perplexed at why it's failling
