### ISSUE TITLE
AirbyteProtocol: emitted_at needs to be moved to the top level of AirbyteMessage

### ISSUE THREAD

**Issue by keu** [airbytehq/airbyte#8041]
## Tell us about the problem you're trying to solve
It is hard to tell when each message was produced, and how much elapsed between two messages.
Currently, only RECORD message has timestamp column - `emitted_at`.

## Describe the solution you’d like
Add `emitted_at` column to AirbyteMessage.

## Describe the alternative you’ve considered or used
N/A

## Are you willing to submit a PR?
yes

**Comment by evantahler** [comment]
Closing, as I think this is done.
