### ISSUE TITLE
populate DB instance with dummy data for benchmarks

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#8048]
## Tell us about the problem you're trying to solve
We need to implement an SQL script that will generate a dummy date for benchmark purposes. 
Desired row/table size described in this [doc](https://docs.google.com/spreadsheets/d/1GFOuvT1US0Vs8wZTGfy5XhaymM7oOwEe9GOxoFTi5Hs)

Row | Size (B) | Size (KB)
-- | -- | --
Regular | 10,000 | 10
Small | 500 | 0.50

Table | Row Count | Regular Row (%) | Small Row (%) | Large Row (%) | Table Size (B) | Table Size (GB)
-- | -- | -- | -- | -- | -- | --
Regular | 50,000 | 99% | 0% | 1% | 995,000,000 | 1
Small | 10,000 | 0% | 100% | 0% | 5,000,000 | 0.01

Database | Table Count | Regular Table | Small Table | Large Table | Database Size (B) | Database Size (GB)
-- | -- | -- | -- | -- | -- | --
Regular | 25 | 25 | 0 | 0 | 24,875,000,000 | 25
Half-regular | 10 | 10 | 0 | 0 | 10,737,000,000 | 10
Many small tables | 1,000 | 0 | 1,000 | 0 | 5,000,000,000 | 5

## Describe the solution you’d like
- [x] prepare the SQL procedure for populating the table with dammy data
- [x] create/populate the database with a small data set (1000 streams with total size 5GB)
- [x] create/populate the database with a half-regular data set (10 streams with total size 10GB)
- [x] create/populate the database with a regular data set (25 streams with total size 25GB)
- [x] modify the script and create databases for Postgres 
- [x] modify the script and create databases for MsSQL 
- [x] add all scripts and documentation for their running to repository
- [x] test with different options for CPU and Memory values
- [x] make it possible for performance tests to transfer CPU and Memory values as parameters

## Additional context- [ ] modify the script and create databases for MsSQL 
In order to reduce computing time, we can generate data for 1 table and then clone this table so many times as we need.

**Comment by andriikorotkov** [comment]
Database source benchmark design - https://docs.google.com/spreadsheets/d/1GFOuvT1US0Vs8wZTGfy5XhaymM7oOwEe9GOxoFTi5Hs/edit#gid=388679515
