### ISSUE TITLE
How to control the connector's docker network

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#8052]
## Tell us about the problem you're trying to solve
We are tring to use airbyte on docker swarm, and we faced a problem:
we can't control the docker network parameters to make a connector's docker instance connect to privates db.

## Describe the solution you’d like
I'd like that there will be the possibility to define the docker run command or all the docker run parameters as advanced settings on Source/Destination adding dialogue.

## Describe the alternative you’ve considered or used
The alterative is to open all the dbs to the specific instance of airbye. This means keep trak of ports and servers.

## Additional context
Our instance of airbyte we want to place must be able to co

## Are you willing to submit a PR?
I'm don't have the understanding of the code to make the change/ or find an existing solution that I'm not aware of.

PS: Nice work, it is a great project:)

**Comment by jrhizor** [comment]
Can you try setting the `DOCKER_NETWORK` environment variable? That should control the docker network for launched pods. It's one global setting, not something you can override on a per-connector basis. Is that sufficient for your use case?

**Comment by AM-I-Human** [comment]
I think it is that. I try it in the worker and keep tract of the `docker network inspect` and seems to be that for my use case.
I'm going to try it in the docker swarm!
I did not found any documentation about it, perhaps it is missing?
Thank you very much for the answer Jared.

**Comment by jrhizor** [comment]
We definitely need to document our env vars. Created https://github.com/airbytehq/airbyte/issues/8066 to follow up on that.

Please let us know if it works. If it does we can close this issue.

**Comment by AM-I-Human** [comment]
It worked, 
my OPS team was able to put it on Docker Swarm (with some sweat) and comunicate with our private databases.👍
