### ISSUE TITLE
unit test singer_helpers.py

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#806]
## Tell us about the problem you're trying to solve
Add unit tests for singer_helpers.py

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368235859197) by [Unito](https://www.unito.io)

**Comment by cgardens** [comment]
not relevant given it is being deprecated: https://github.com/airbytehq/airbyte/issues/6164
