### ISSUE TITLE
Write a script to perform the intermediate upgrade to v0.32.0

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#8076]
## Tell us about the problem you're trying to solve
Upgrading past v0.32.0 currently requires a user to checkout the OSS repo at that version, run docker-compose up, bring it back down, and then upgrade to the version they want. This process leaves a lot of room for user error and should be made simpler so that it requires no thought from the user.

## Describe the solution you’d like
A script should be introduced that users can run to perform the intermediate upgrade for them. Something like a `upgrade-0-32-0.sh` which roughly looks like
```
docker-compose down
git checkout v0.32.1-alpha
docker-compose up
```

## Describe the alternative you’ve considered or used
An alternative is to have `docker-compose up` do this automatically for users, but that would likely require much more engineering effort which may not be worth investing in this one-time upgrade process

## Are you willing to submit a PR?
Yes

**Comment by cgardens** [comment]
e.g. upgrade-0-32-0.sh and optionally can pass --force to blow up definitions that don't work? agreed. it does seem easier than what we are asking users to do now.

**Comment by cgardens** [comment]
The platform team discussed this today. The consensus was that we should wait for feedback before moving forward on this. While a script may simplify the upgrade process slightly in the success case, we are worried that there are a lot of edge cases that will be hard to handle and in those cases the script will making the experience _much_ worse.

e.g. What if the user isn't just using `git clone` for the .env file but is pulling it manually. 
e.g. What should the script do if as the .env file evolves? Does it just overwrite the existing .env file that the user has? What is the consequence of that.

We could potentially write a script for very narrow case e.g. user is using docker-compose and has the full airbyte repo cloned and they are running airbyte from the root of that cloned project's working directory.

@sherifnada heads up.

**Comment by cgardens** [comment]
won't do
