### ISSUE TITLE
Source Zendesk Support: add `brands` stream

### ISSUE THREAD

**Issue by zbrak** [airbytehq/airbyte#8095]
## Tell us about the new connector you’d like to have
* We need the [Brands endpoint for Zendesk Support](https://developer.zendesk.com/api-reference/ticketing/account-configuration/brands/) available for full refresh into denormalized BigQuery destination. Bonus would be incremental append.
* No specific version - believe endpoint is available through existing connection.

## Describe the context around this new connector
* We need this integration to support our Zendesk reporting stack. We have a tenant that aggregates many small other tenants together. Due to the nature of Zendesk, the implementation relies on "Brands" object to split out some functionality - making "Brands" the primary way we identify tickets coming from different sub-tenants.  
* Syncs would run at the same frequency as the rest of Zendesk. It's a relatively small record set, but could grow to several thousand.
* Specifically looking for the Brands endpoint to be added to the existing connector.
* Yes, Pliancy is company name.

## Describe the alternative you are considering or using
Currently, we are running this "Brands" endpoint through Google cloud Data Fusion.
We are also relying on a paid stitch integration for Zendesk. Given we have this added it would allow us to transition this connection off of Stitch and data fusion

## Are you willing to submit a PR?
Unfortunately, I do not have the development chops to run the connector, but have taken a stab at putting together the JSON schema for it attached here.

Thanks so much for considering!
[brands.json.zip](https://github.com/airbytehq/airbyte/files/7563857/brands.json.zip)

**Comment by sherifnada** [comment]
@zbrak thanks for opening this request! We're currently focused on reliability and performance of existing connectors, so sadly for this feature request it isn't something we will prioritize at the moment. The fastest way to get it done would be to open a PR!

**Comment by davydov-d** [comment]
Closing as already implemented
