### ISSUE TITLE
allow seeing full field names during connection configuration

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#8106]
Currently connection configuration truncates field names. Here's an example from the Github source:
![Screen Shot 2021-11-18 at 1 46 51 PM](https://user-images.githubusercontent.com/120362/142492902-623a0149-6106-4da7-a384-a17657eaca52.png)

This causes users to go through a painful flow like needing to copy and paste text into different windows to see if the row related to “commit_comments_reactions” or  “commit_comments” before configuring the sync settings.

**Comment by johnlafleur** [comment]
One way to solve this is with resizable columns: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=28787%3A119017

**Comment by jrhizor** [comment]
I like resizable columns. I also think we can have the connector settings page extend to full page width instead of having a limited max width.

**Comment by johnlafleur** [comment]
Actually, the new layout is full width indeed.

**Comment by edmundito** [comment]
Comment from @Upmitt:

Could we limit the width of a table to a min-width and add a horizontal scroll?

**Comment by edmundito** [comment]
Reviewed with @andyjih . See comment above.
