### ISSUE TITLE
Update the feedback modal behavior

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#8113]
Some backend changes have been perform in order to make the display of this modal more robust in the UI. The goal being to stop relying on the local storage.

## Changes needed

The `WorkspaceRead` object has been changed in order to have 2 new properties:
- firstCompletedSync: indicate that a workspace has finished performing its first sync
- feedbackDone: indicate if a feedback have been provided (without considering the content of the feedback)
Those 2 new fields must be use instead of the local storage to display the modal. The logic being: it is displayed if `firstCompletedSync` is true and `feedbackDone` is false.

A new configApi endpoint has been added to specify that a feedback has been done. It doesn't perform any action apart from setting `feedbackDone` to true for the workspaceId provided in parameters. The endpoint is named `tag_feedback_status_as_done` and take a `WorkspaceGiveFeedback` which only contains a workspaceId as an input parameter

Dod:

- [ ] The modal is display or not based on information from the backend
- [ ] When the user have provided a feedback the new endpoint is called and the backend is updated

**Comment by timroes** [comment]
The feedback modal has been removed from the code by now and is handled via third party survey tools.
