### ISSUE TITLE
Reduce the number of "sync now" prompts after the first connection

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#8114]
## Tell us about the problem you're trying to solve
After the connection settings are set for the first connection, the user is prompted at the bottom of the page to "Sync Now". 
Then, the user is redirected to a new page where there is another "Sync Now" button.
After clicking that button, it shows another "Sync Now" button with a line of text removed. 
Once that is clicked, the user then sees the progress bar showing the sync has started.

The current user perception is that this is a bug. 

## Describe the solution you’d like
Remove the two "Sync Now" buttons from the onboarding flow after the connection settings, so that the user automatically understands that the sync starts as soon as they save the connection settings. After clicking "Sync Now" on the connection settings, the redirect should show a page with a sync progress bar. 

fyi @johnlafleur @jrhizor

**Comment by johnlafleur** [comment]
Could you add some screenshots to illustrate the current flow please?

**Comment by nataliekwong** [comment]
Here is a Loom I recorded of a test: https://www.loom.com/share/d4e6392d6d3649408186965e51e2bfbe

- First click: Set up Connection on the connection settings
- Second click: Sync Now
- Third click: Sync Now

Only after the third click does the status / running bar show up.

**Comment by johnlafleur** [comment]
I thought the sync would be automatically triggered once the connection is set up. Maybe the specs were a bit confusing. 
But this is what I think the specs should be. @jrhizor who should we involve to fix this issue?

**Comment by nataliekwong** [comment]
Resolving as flow has been simplified now.
