### ISSUE TITLE
Normalization to Snowflake failed when Google Sheet name has space 

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8116]
## Enviroment
- **Airbyte version**:  0.30.20-alpha
- **OS Version / Instance**: GCP
- **Deployment**: Docker
- **Source Connector and version**: Google Sheets 0.2.5
- **Destination Connector and version**: Snowflake 0.3.17
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
sync failed if the Google Sheet has a space in the name.

## Expected Behavior
*Tell us what should happen.*

## Logs
Complete logs: [logs-7402-0 (1).txt](https://github.com/airbytehq/airbyte/files/7566852/logs-7402-0.1.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by annalvova05** [comment]
@marcosmarxm Could you please send more details about the sheet or the sheet example (like sheet name and table headers)? Because I cannot reproduce a bug with the current description. We replace whitespaces to underscore, also numbers are allowed.

**Comment by marcosmarxm** [comment]
Closing this because is not reproducible anymore.
