### ISSUE TITLE
Set "Sync Mode" for all streams when setting up a connection

### ISSUE THREAD

**Issue by joshuataylor** [airbytehq/airbyte#8128]
## Tell us about the problem you're trying to solve
When setting up a new connection that has a lot of tables (think hundreds), and I want to have the same type on all the columns, I want to be able to bulk set the column options.
![image](https://user-images.githubusercontent.com/225131/142562206-291f2aad-c8c1-44bb-9491-c59b2b242afd.png)

It would also be amazing to choose a cursor field bulk as well, maybe type in an option and if the field has it, it'll pick that or be null so the form can't be submitted. (example, `updated_at` as a cursor, if a table doesn't have that, then leave blank).

## Describe the solution you’d like
A form field to choose the option.

## Describe the alternative you’ve considered or used
Just ticking them all.

## Additional context
I hate checking boxes.

## Are you willing to submit a PR?
Sure, if the community thinks it's a good idea. I think this will be a positive change, but would love some discussion.

**Comment by renzobecerra** [comment]
+1 - It's very tedious to check the sync mode boxes on source connectors like Salesforce that can have thousands of objects!

**Comment by marcosmarxm** [comment]
@timroes this is not done in latest version already?
![image](https://user-images.githubusercontent.com/5154322/157749540-0fc9739e-9b4c-4f62-a494-e198891965f8.png)

**Comment by timroes** [comment]
Yes, sorry wasn't aware of this duplicate. This has been closed via https://github.com/airbytehq/airbyte/pull/9025
