### ISSUE TITLE
WebBackend Updates for Supporting Multiple Destinations

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#813]
## Tell us about the problem you're trying to solve
Artem has requested help with the following updates: 

"""
So far only few comments on API:
1.
```
/v1/web_backend/connections/get and /v1/web_backend/connections/list
I need info for destination (the same as for Source)
destinationName
destinationId
destinationImplementationId
connectionConfiguration
```
2. I need data for Destination column in form like `[{name: “”, connectorName: “”}]`
"""

https://airbytehq.slack.com/archives/C01AHCE38KW/p1604449779088300

**Comment by cgardens** [comment]
@sherifnada looks like you've knocked this one out. good to close?

**Comment by sherifnada** [comment]
Yup, can close
