### ISSUE TITLE
Increase width of drop down in connector configuration menu

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8130]
## Tell us about the problem you're trying to solve

The dropdown width clips the text

![Screen Shot 2021-11-18 at 10 24 47 PM](https://user-images.githubusercontent.com/6246757/142575412-34f63688-37e1-4a27-8331-9dbe4efde731.png)

## Describe the solution you’d like
I would like the dropdown to fit all the text (at least up to the width of the form)

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend
