### ISSUE TITLE
Airbyte-scheduler DDOSes database

### ISSUE THREAD

**Issue by FUT** [airbytehq/airbyte#8132]
## Enviroment
- **Airbyte version**:  0.30.25-alpha
- **OS Version / Instance**: Ubuntu 20.04.1 LTS
- **Deployment**:  Docker 
- **Source Connector and version**: Google Analytics | airbyte/source-google-analytics-v4 | 0.1.9
- **Destination Connector and version**: Postgres | airbyte/destination-postgres | 0.3.11
- **Severity**:  High
- **Step where error happened**: Ongoing

## Current Behavior
Airbyte scheduler issues just a crazy amount of requests to our database (200k per hour OR 50-100 per second). We have around 800 connections and 50k finished jobs in the database. All of them are complete. We have at most 5 jobs running concurrently at any time.

![image](https://user-images.githubusercontent.com/965875/142625978-9b4158e1-274b-42a0-b01d-799987264a58.png)

Based on the SQL requests I was able to narrow down the sources of these requests to:
[getJob](https://github.com/airbytehq/airbyte/blob/3226b22dea5c7bc036ddfd37d77047dcc2e894da/airbyte-scheduler/persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java#L327)
[getLastReplicationJob](https://github.com/airbytehq/airbyte/blob/3226b22dea5c7bc036ddfd37d77047dcc2e894da/airbyte-scheduler/persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java#L372)

The further investigation gave me nothing. These requests are used here and there and it is hard to judge which part is the source of the issue.

If I stop only the scheduler container - no requests are coming in. So, I am 100% sure that they are generated by scheduler.

## Expected Behavior
Airbyte scheduler should send a reasonable amount of requests.

## Logs
I was not able ot get some logs related to this issue from Airbyte scheduler. It just sends a lot of requests silently

<details>
<summary>LOG</summary> 

```



```

</details>

## Steps to Reproduce
1. Create 800 connections
2. Check database queries count

## Are you willing to submit a PR?
Yes, but I need help to understand where is the issue.

**Comment by tuliren** [comment]
Thank you for creating this issue, and performing the analysis.

Some initial thoughts on this issue:
1. The first query looks efficient enough. The second query should have a dedicated index. Its performance is ok, but can be better. Currently the `jobs` table only has one index on the `id` column.
2. The large number of queries is not completely unexpected. The schedule needs to check if a job should run for every connection periodically. But there must be some optimization we can be in this area.

**Comment by FUT** [comment]
@tuliren thank you for the details! That helped me to track down the source of the issue finally.

Airbyte runs jobs scheduler every 5 seconds. And inside the job scheduler we have [N+1 requests loop](https://github.com/airbytehq/airbyte/blob/3226b22dea5c7bc036ddfd37d77047dcc2e894da/airbyte-scheduler/app/src/main/java/io/airbyte/scheduler/app/JobScheduler.java#L84) which depends on the count of connections. One request is fired when `jobPersistence.getLastReplicationJob` is called and the second one is fired when `scheduleJobPredicate.test` is called.

That can be improved with some kind of preload functionality for the connections list.

To be honest, I am a weak Java developer. Thus I am not sure that I can solve that issue on my own. I will try to add an extra index as a temporary solution according to your recommendations. Thank you!

**Comment by marcosmarxm** [comment]
@FUT can you try latest version of Airbyte? The Scheduler is deprecated and maybe this is not an issue anymore.

**Comment by evantahler** [comment]
Closing, as current versions of Airbyte do not use the scheduler.
