### ISSUE TITLE
searching only searches logs currently on the screen

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#8136]
When trying to debug an issue with logs, I often type ⌘F and search for something. In Chrome, all I can do is search within the text that's currently showing, not the entire downloaded log file. This makes it easy to search for something like "Exception" or a specific debug message and think that it isn't present.

**Comment by marcosmarxm** [comment]
maybe filter logs based on level: INFO, ERROR, WARN too, this would help creating issues =)

**Comment by Jamakase** [comment]
@jrhizor actually that's not possible. We use a lib that uses `react-window` and it is main feature of it. What it actually does: doesn't render all the values. If we render all logs - we could face performance problems.

Right now there is no way to change the behavior and allow searching it with chrome, but we may enable searching with search control that is already implemented in the lib

![image](https://user-images.githubusercontent.com/3767150/144683988-e706c623-427c-4dfb-855d-feeebf9620b0.png)

**Comment by timroes** [comment]
Closing in favor of https://github.com/airbytehq/airbyte/issues/12129
