### ISSUE TITLE
Create `/publish` command to external images

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8138]
## Tell us about the problem you're trying to solve
Right now we don't have the option to release new connectors outside the main repository.
The main reason is because we use a GCS cache to get specs.
We need to create another `/publish` command works with external images, example is https://github.com/airbytehq/airbyte/pull/7837

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by alafanechere** [comment]
Two new connectors publications are currently blocked:
* https://github.com/airbytehq/airbyte/pull/9155
* https://github.com/airbytehq/airbyte/pull/7837

**Comment by marcosmarxm** [comment]
@harshithmullapudi edit the `manage.sh` inside `/tools/integrations` and create a new command `/publish-external example/source-external:0.1.0`
