### ISSUE TITLE
CI Sandbox for Parcel Perform

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8139]
## Tell us about the problem you're trying to solve
Need credentials to test community contribution: https://github.com/airbytehq/airbyte/pull/7926 for [Parcel Perform](parcelperform.com) source.

Some concerns were raised [here](https://github.com/airbytehq/airbyte/pull/7926#issuecomment-967444794) around fake data generation, we should figure this out with the service provider.

**Comment by karinakuz** [comment]
**Free Trial account is created (expiration date 2021-12-12)**, OAuth token is received, credentials are added to the LastPass with the name "Parcel Perform". APIs are tested for two streams:

**Shipments List** https://api.parcelperform.com/v5/shipment/list/?created_date_from=2021-11-01T10:30:00&created_date_to=2021-11-30T10:30:00&carrier_reference=usps
**Shipment Details** https://api.parcelperform.com/v5/shipment/details/?shipment_id=shipment001&shipment_uuid=a0fe1b96-3932-4d91-b9b4-a7073c72236b
