### ISSUE TITLE
Repairs of commits' CI  tests

### ISSUE THREAD

**Issue by antixar** [airbytehq/airbyte#8208]
## Statuses of CI jobs is not relevant
9 of 10 of PR commits can have several failed CI jobs. For example:

![image](https://user-images.githubusercontent.com/11213273/143042263-b28fbbc9-8efb-41ef-b4f1-211b24691a18.png)
As rule as these are same jobs:

- Airbyte CI / Acceptance Tests (Kube)
- Airbyte CI / Run Frontend Test (push)
- Airbyte CI / Ensure all required Docker images exist on Dockerhub (push)
Other jobs can be broken because logic of version bumping is not linear. For example:
 - Airbyte CI / Platform: Build (push) - this job tries to validate the spec files (`./airbyte-config/init/src/main/resources/seed/source_specs.yaml`) but it is not up to date and can be updated after a connector publishing only.
 
The main goal of this CI jobs are blocking of following merging  if any job is failed. But these CI jobs can lose credibility of contributors if a lot of CI jobs' attempts are failed after any code changes. And developers often can merge/publish without checking of CI results. And as result sometimes we have master branch failures after "broken" code.

## How to fix this
Make this CI jobs stable obviously. So each developer will understand to his changes can break something if any one CI job of CI is failed. 
We may do it in several passes:
1. switch off all jobs with periodic environment issues (k8s etc) and jobs for validation of bumping versions.
2. limit contributors' permissions. Anyone will not be able to merge without a last successful CI status. Certainly a bit of people should have extended permissions for support of repos.
3. Fix broken, non-stable CI jobs. For this we can create follow-up issues.

**Comment by sherifnada** [comment]
@jrhizor @davinchia @cgardens thoughts? I'm flexible on sequencing 1/2/3 but feels like we need to pull the trigger on this

**Comment by davinchia** [comment]
I don't think we should do 1 since it removes the impetus for us to fix this + we'd be running blind.

3 is something that is actively worked on, it's just that it's quite difficult to get the K8s cluster stable.

I vote for 2 since it prevents bad merges and is a forcing function to get things to a stable point. Ideally we would also have an escape hatch in case of hot fixes.

**Comment by girarda** [comment]
life is much better now. we can open specific issues as problems come up
