### ISSUE TITLE
🐛 Source Zendesk Support: Tickets to BigQuery Denormalized keeps failing.

### ISSUE THREAD

**Issue by zbrak** [airbytehq/airbyte#8209]
## Enviroment
- **Airbyte version**:  0.32.4-alpha
- **OS Version / Instance**: 1.21.5-gke.1302
- **Deployment**: Google Kubernetes Engine
- **Source Connector and version**: Zendesk Support 0.1.7
- **Destination Connector and version**: Bigquery Denormalized Struct
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
Tickets stream will not complete - have isolated to this stream - says error in error handling?

I've had similar issues with some ticket submissions (the source email) being exceptionally large, and maxes out ingest at 50k characters on a field. 

## Expected Behavior
Trying to pull our tickets down keeps failing. This is a key endpoint to replicate.

## Logs
Logs attached!
[logs-522-0.txt](https://github.com/airbytehq/airbyte/files/7588966/logs-522-0.txt)

## Steps to Reproduce
1. Source Zendesk Support setup.
2. Destination BigQuery denormalized.
3. Connection with tickets as only source endpoint, incremental append.

**Comment by zbrak** [comment]
Update! Got a successful initial run (possible it was peak hours that caused API failure?)
Leaving open in hopes of a second opinion - otherwise feel free to close!

[logs-860-0.txt](https://github.com/airbytehq/airbyte/files/7596086/logs-860-0.txt)

**Comment by sherifnada** [comment]
@zbrak for the second sync, I'm not seeing any exceptions in the logs? Could you say more about what you're seeing?

**Comment by DoNotPanicUA** [comment]
Hi @zbrak ,
I fully reworked the BigQuery Denormalized destination a few weeks before Christmas. Many known bugs were fixed 🐛 🔥 
Even in case you still have an issue, we need a new log.
May I ask you to try one more time using the latest destination and source versions?
Source Zendesk : `0.1.12` 
Destination BigQuery Denormalized : `0.2.7`

**Comment by misteryeo** [comment]
@zbrak I'm going to close this out based on the above comment - if you find that the issue still persists, please let us know and reference this issue.
