### ISSUE TITLE
Create end to end tests that check that binary data is passed correctly from GA DB sources to GA destinations

### ISSUE THREAD

**Issue by mkhokh-33** [airbytehq/airbyte#8210]
Different jdbc source connectors handle binary data in different way
During the work on #5878 for MySql source

1.we added and fixed data type tests in order to check that all binary data will be transformed into base64 encoded string and passed to destination
2. fixed behavior and tests for cdc data type to pass binary data types as base64 

## Expected Behavior
1. We should check that all jdbc sources send binary data as base64, check data type test for them, fix, add new ones to be  sure that the behavior is the same for all of them
2. Check cdc data type tests and cdc configuration for source to be sure that data passed as base64, add or fix some tests as well 

## Current Behavior
Seems that in current implementation we see different way to handle binary data in different jdbc source connectors.

**Comment by tuliren** [comment]
This is probably an outdated issue. We already have data type tests ensuring that the binary columns are outputted in base64 string.

Also this data type doc suggests to use the raw binary encoding from the source side:
https://docs.google.com/document/d/1FupBVPMlDTU2QnEOxN42BKvdWk-Yha8604MnU5EmDRQ/edit#heading=h.5y0jyqxpv6l
