### ISSUE TITLE
Basic Normalization does not escape/quote field names on table alter

### ISSUE THREAD

**Issue by lizdeika** [airbytehq/airbyte#8240]
## Enviroment
- **Airbyte version**:  example is 0.32.6-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: https://github.com/airbytehq/airbyte/pull/8021
- **Destination Connector and version**: Postgres 0.3.12) 
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
I have changed stream schema from this:
```
{
  "title": "Seller Feedback Data Reports",
  "description": "Seller Feedback Data Reports",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "date": {
      "type": ["null", "string"],
      "format": "date"
    },
    "rating": {
      "type": ["null", "number"]
    },
    "comments": {
      "type": ["null", "string"]
    },
    "response": {
      "type": ["null", "string"]
    },
    "order-id": {
      "type": ["null", "string"]
    },
    "rater-email": {
      "type": ["null", "string"]
    }
  }
}
```

to this:
```
{
  "title": "Seller Feedback Data Reports",
  "description": "Seller Feedback Data Reports",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "Date": {
      "type": ["null", "string"],
      "format": "date"
    },
    "Rating": {
      "type": ["null", "number"]
    },
    "Comments": {
      "type": ["null", "string"]
    },
    "Response": {
      "type": ["null", "string"]
    },
    "Order ID": {
      "type": ["null", "string"]
    },
    "Rater Email": {
      "type": ["null", "string"]
    }
  }
}
```

Basic normalization tried to alter staging dbt table and failed because field names are not escaped/quoted. (See LOG)

I have removed the table completely and on the next sync table was created without issues. 
I assume Basic Normalization escapes/quotes field names on table creation but not on table altering.

## Expected Behavior
alter table escapes/quotes field names

## Logs
<details>
<summary>LOG</summary> 

```

database-postgresql134-1  | 2021-11-24 14:56:13.301 UTC [382] ERROR:  syntax error at or near "Order" at character 405
database-postgresql134-1  | 2021-11-24 14:56:13.301 UTC [382] STATEMENT:  /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "normalize", "target_name": "prod", "node_id": "model.airbyte_utils.get_seller_feedback_data_stg"} */
database-postgresql134-1  |
database-postgresql134-1  | 	    alter table "mono"."_airbyte_airbyte"."get_seller_feedback_data_stg"
database-postgresql134-1  |
database-postgresql134-1  |
database-postgresql134-1  | 	               add column Date date,
database-postgresql134-1  |
database-postgresql134-1  | 	               add column Comments character varying(256),
database-postgresql134-1  |
database-postgresql134-1  | 	               add column Order ID character varying(256),
database-postgresql134-1  |
database-postgresql134-1  | 	               add column Rater Email character varying(256)
database-postgresql134-1  | 	            ,
database-postgresql134-1  |
database-postgresql134-1  |
database-postgresql134-1  | 	                drop column date,
database-postgresql134-1  |
database-postgresql134-1  | 	                drop column comments,
database-postgresql134-1  |
database-postgresql134-1  | 	                drop column order-id,
database-postgresql134-1  |
database-postgresql134-1  | 	                drop column rater-email

```

</details>

## Steps to Reproduce
1. Create stream schema with a field "some-field"
2. Change stream schme field name to "Some Field"
3. Resync

## Workaround
1. Either drop/delete the final table completely to force a full-refresh from dbt which would generate and use a `CREATE TABLE` statement instead.
2. Manually execute the proper `ALTER` statement on the destination to rename the field correctly. Next time normalization, and thus dbt is run, it won't try to alter the field name and would avoid this exception.

**Comment by ChristopheDuong** [comment]
Sounds like this would need a bug fix on dbt repository

**Comment by ChristopheDuong** [comment]
If you take a look at this repository: https://github.com/airbytehq/testing_dbt/

You can find the exact scenario you are encountering here: https://github.com/airbytehq/testing_dbt/blob/2d8f87b721e13122dd5fd9fa8088ee7734f9017e/output/postgres-3-schema-change-FAILED-dbt.log#L1613

**Comment by ChristopheDuong** [comment]
Blocked by https://github.com/dbt-labs/dbt-core/issues/4423

**Comment by lizdeika** [comment]
Sounds like `a fix is available in dbt` is the way to go

**Comment by cgardens** [comment]
Do we have a sense of how many sources this affects? If it’s a lot, is it worth considering doing our own macro? Sounds like google ads might be affected which is obviously a big one.

**Comment by ChristopheDuong** [comment]
> Sounds like google ads might be affected which is obviously a big one.

It seems like source google ads's catalog have columns names using `.` characters, so the columns would need to be manipulated with quotes.

https://github.com/airbytehq/airbyte/blob/84d1456fcf6103fecd091b1a4cb24b0195f660d1/airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/accounts.json#L5

With incremental, when a new column needs to be added (or is renamed), dbt will detect it and tries to make an `ALTER` statement to fix that automatically. Unfortunately, because of the special characters, it fails to do so.

A workaround for now would be to delete the table entirely, so dbt would not try to make an alter statement but a create table instead (which handles quotes in column names with special characters properly)

**Comment by ChristopheDuong** [comment]
> is it worth considering doing our own macro? 

I'm not familiar with the dbt-core codebase enough, so I am not 100% sure this is doable with custom macros to override these `alter` statements. If someone has pointers or is willing to try doing this, that would help a lot yes!

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
