### ISSUE TITLE
Airbyte upgrade run migrations repeatedly.

### ISSUE THREAD

**Issue by vladimir-remar** [airbytehq/airbyte#8258]
## Enviroment
- **Airbyte version**:  from 0.30.23-alpha to 0.32.0-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Severity**: Medium
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
At some point, the upgrade run the migration over and over repeatedly, I got some errors( log attached) .
We have some custom conectors, thats why We create an other EC2 instance to do this upgrade including `VERSION_0_32_0_FORCE_UPGRADE` on .env file just to see what happens with our connections.

## Expected Behavior
execute the upgrade

## Logs
[airbyte-upgrade.log](https://github.com/airbytehq/airbyte/files/7604384/airbyte-upgrade.log)

## Steps to Reproduce
1. docker-compose down
2. wget -N https://raw.githubusercontent.com/airbytehq/airbyte/v0.32.0-alpha/{.env,docker-compose.yaml}
3. docker-compose up

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by jrhizor** [comment]
What does "We create an other EC2 instance to do this upgrade" mean?

**Comment by vladimir-remar** [comment]
@jrhizor Hi! Thanks for the answer. We recreate the same image into another instance to mess around with the upgrades, since we wont to do the upgrade in prod.

**Comment by lmossman** [comment]
Another user experiencing a similar issue: https://airbytehq.slack.com/archives/C01MFR03D5W/p1637706856376500

**Comment by marcosmarxm** [comment]
I request to @vladimir-remar to remove manually the custom connection and test again, to narrow down the problem.

**Comment by lmossman** [comment]
For both users, it looks like these are the last log lines before the server restarts:
```
airbyte-server      | 2021-11-25 16:04:27 INFO i.a.s.ConfigDumpImporter(checkImport):167 - {workspace_app_root=/tmp/workspace/server/logs} - Checking Airbyte Version to import AirbyteVersion{version='0.32.0-alpha', major='0', minor='32', patch='0'}
airbyte-server      | 2021-11-25 16:04:48 INFO o.j.t.JooqLogger(info):312 - {workspace_app_root=/tmp/workspace/server/logs} - Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
airbyte-server      | 2021-11-25 16:04:53 INFO o.j.t.JooqLogger(info):312 - {workspace_app_root=/tmp/workspace/server/logs} - Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
```

**Comment by lmossman** [comment]
@vladimir-remar we suspect that the issue here is that the size of the data in your jobs database is too large to upgrade. Could you verify for us the size of your job data? You can do this by exporting your config and checking the size of the file that is generated, or by counting the number/size of rows in your jobs database.

**Comment by vladimir-remar** [comment]
@lmossman quick update: the size of the `JOBS.yaml` is 185.2 MB
@marcosmarxm I'm removing the custom connectors now, so I need some time to make it work.

**Comment by vladimir-remar** [comment]
@jrhizor @marcosmarxm @lmossman Hi again!
I was able to upgrade Airbyte from 0.30.23-alpha to 0.32.0-alpha by doing the follows:
- Export config.
- Edit and remove the content from `ATTEMPTS.yaml` file, I do not edit the `JOBS.yaml` file.
- Import the new config.
The  problem here is I lost the `state` from all connections, I do not care about the logs, but lost the state it is a big issue indeed.
I am open to suggestions.

**Comment by cgardens** [comment]
next steps: We have struggled to reproduce this ourselves. @lmossman is going to try to work with someone in the community who is running into this problem so that we can better understand how to reproduce.

**Comment by lmossman** [comment]
@vladimir-remar do you still have the original unedited config export files?

If so, would you be willing to hop on a call with us so that we could go through those files with you and try to determine if there is any issue with your config files? If yes, then what time would work best for you? We are on Pacific time so if there is any good overlap between our timezones' working hours that would be best.

**Comment by kailashjoshi018** [comment]
Same for me while upgrading to 0.32.0-alpha from 0.31.0-alpha. Did a force update on airbyte_metdata table to change the airbyte_version to 0.32.0-alpha and it worked for me. Not sure, if this is the correct way, but at least solved my issue.

**Comment by lmossman** [comment]
@kailashjoshi018 Are you able to share the full logs from when you tried to upgrade from 0.31.0 to 0.32.0?

**Comment by lmossman** [comment]
An update here: we have been able to reproduce the issue, and we believe we have identified the root cause. We have implemented a fix and will be distributing it soon - I will post again on this issue once I have more information!

**Comment by lmossman** [comment]
@vladimir-remar @kailashjoshi018 
We have released the fix for this issue. Please try upgrading to `v0.32.0-alpha-patch-1`, which includes the fix, and let us know if you have any other issues

**Comment by ninomllr** [comment]
I have the same issue on v0.33.10-alpha.

**Comment by vladimir-remar** [comment]
@lmossman I tried without modifying the `ATTEMPS.yaml` file and it seems to work, I did in a backup from my EC2 Instance, but I had to move from t3.large to t3.xlarge. But now when I try to do the same in my actual(pro) EC2 instance which run in a t3.xlarge it does not work, at some point it runs out of memory and the loop migrations starts again. I will try to change the instance type to t3.2xlarge and I hope it works. 
After the conclucision that the size of files `ATTEMPS` and `JOBS` it is the mainly problem here, do you guys are planning to include some kind of tool to clean or reduce those files? Even in the UI, add something to remove some entries from attemps particularly.
