### ISSUE TITLE
🐛 Source Facebook Marketing: Excessive type conversion warnings

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#8274]
## Enviroment
- **Airbyte version**: 0.32.6-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Facebook Marketing 0.2.26
- **Destination Connector and version**: BigQuery 0.5.0
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
The sync job runs, but while doing so it produces about 30,000 error messages that look like these: 

```
source - 2021-11-27 01:00:30 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Syncing stream: ads_insights 
source - 2021-11-27 01:00:30 INFO () DefaultAirbyteStreamFactory(internalLog):97 - Setting state of ads_insights stream to {'date_start': '2021-11-11T00:00:00+00:00', 'include_deleted': False}
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '382' is not of type 'null', 'integer'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '8.02625' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '4.098511' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '1.675043' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '8.755909' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '1.512801' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '8.84828' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '9.132558' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '0.584894' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '1.032128' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '65311' is not of type 'null', 'integer'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '0.110242' is not of type 'null', 'number'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '72' is not of type 'null', 'integer'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '141' is not of type 'null', 'integer'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '63278' is not of type 'null', 'integer'
source - 2021-11-27 01:00:36 WARN () DefaultAirbyteStreamFactory(internalLog):96 - '0' is not of type 'null', 'number'
```

I have sampled a few of these error messages and confirmed that the numbers (integer or fractional) exist in the input JSON, and are in fact numbers and not strings.  So it would seem that they conform to the schema just fine.

A few extra warnings would usually be only a minor issue, but in this case they are so numerous that they are starting to take up gigabytes and gigabytes of disk space, and they are making the rest of the logs hard to read.

Note that this only seems to happen for the `ads_insights` stream, not for the other streams.

## Expected Behavior
I think we shouldn't be seeing any of these messages because the input values are of the correct and expected types.

## Logs
See above.

## Steps to Reproduce
1. Set up a Facebook Marketing source.
2. Connect it to a BigQuery destination.
3. Enable the ads_insights stream.
4. Run a sync.

**Comment by avida** [comment]
Looks like  it has been fixed in #7863 and should be gone after #7904 merged (0.2.25 version). Will check it out again.

**Comment by avida** [comment]
Tried to reproduce it on 0.2.24, got a lot of warnings:

![0 2 24](https://user-images.githubusercontent.com/437607/143843134-a44c4f4f-582f-4482-9d88-d76a99f593d9.png)
Same on 0.2.26, no warnings at all:

![0 2 26](https://user-images.githubusercontent.com/437607/143843146-e409c51a-910c-4f7f-8f72-280974e6b4b0.png)

@zestyping  Could you please confirm that you are using 0.2.26 version? I see description says version: Facebook Marketing 0.2.26 but wanted to double check cause I believe problem should gone with 0.2.25 connector version

**Comment by zestyping** [comment]
Hi, thank you!  I did make a mistake in reporting the version number (because I had outstanding changes and got confused).  After upgrading, the issue is gone.  Apologies for taking your time!
