### ISSUE TITLE
New Source: Adjust

### ISSUE THREAD

**Issue by koji-m** [airbytehq/airbyte#8275]
## Tell us about the new connector you’d like to have
* Which source and which destination?
  Source - Adjust (https://www.adjust.com)
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
  The latest version

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
  Our team need to sync Adjust's KPI statistics to our data platform. The statistics were synced by Adjust's auto Raw Data Reporting. But we cannot ingest the data by Raw Data Reporting now, beacause Facebook has stopped provinding AMM(Advanced Mobile Measurement) program.
* How often do you want to run syncs?
  daily
* If this is an API source connector, which entities/endpoints do you need supported?
  * Adjust KPI Service - https://help.adjust.com/en/article/kpi-service
    * Especially App KPIs - https://help.adjust.com/en/article/kpi-service#app-kpis
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 
  No, I don't have the permissions to do that.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
We may develop the data ingestion part for our data platform. As we've started using Airbyte in production, it would be nice to be able to integrate this sync process into Airbyte.

## Are you willing to submit a PR?
Yes, I'm willing to!

**Comment by YowanR** [comment]
Connector already exists so closing this issue as completed.
