### ISSUE TITLE
All-in-one static code checker to be run locally as well as during CI pipelines

### ISSUE THREAD

**Issue by sergei-solonitcyn** [airbytehq/airbyte#8278]
Subtask for https://github.com/airbytehq/airbyte/issues/8137
At first, we want to run a set of static code checkers as a part of our code quality assurance during CI pipelines.
On the other hand the tool should provide a possibility to run all possible checks locally, without requesting for external services.
Also it has to be pretty simple in usage, like one-two words command without lots of individual manual settings.

**Comment by sherifnada** [comment]
@sergei-solonitcyn is this different from the current code checks we have in https://docs.airbyte.io/contributing-to-airbyte/monorepo-python-development#formatting-linting?

**Comment by sergei-solonitcyn** [comment]
@sherifnada now I reconfigured those a bit.
But also working on independent checks which would able to be run for the whole code. We could implement it independently in CI pipeline with custom reports.
Our current repo structure prevents to i.e. run `mypy` for the whole project, as we don't have solid python packages structure but just usual directories instead. It makes us to check every connector iteratively.
Also I believe it's better to have a choice to just check the code without forcing proposed changes. It should help us to improve a level of code ownership.
