### ISSUE TITLE
Source Github: rate limit backoff seems to trigger connection timeout from github API

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8285]
## Tell us about the problem you're trying to solve
As detailed in https://github.com/airbytehq/oncall/issues/26 it seems like the github connector rate limit backoff "upsets" the github API in some way. It seems like it always causes a connection termination. I created this separate issue because that one encompasses a problem unrelated directly to the connector. 

Looking at the logs, the formula is something like: 

```
Backing off for N seconds
Backing off for 60 seconds
Connection terminated
```

Here is an example log line (enriched with extra logs i added in the image `airbyte/source-github:20211124-rc1`)
```
source - 2021-11-24 20:21:44 ERROR DefaultAirbyteStreamFactory(internalLog):95 - Response: {"message":"API rate limit exceeded for user ID 38087517.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}. Headers {'X-OAuth-Scopes': '', 'Content-Security-Policy': "default-src 'none'", 'X-RateLimit-Used': '5000', 'Date': 'Wed, 24 Nov 2021 20:21:44 GMT', 'Vary': 'Accept-Encoding, Accept, X-Requested-With', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-RateLimit-Resource': 'core', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-RateLimit-Reset': '1637786446', 'X-Accepted-OAuth-Scopes': 'repo', 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': '*', 'X-XSS-Protection': '0', 'X-GitHub-Request-Id': '06DC:63BC:A69055:138781A:619E9ED7', 'x-oauth-client-id': 'a73408cbac605f1b3660', 'Content-Encoding': 'gzip', 'X-RateLimit-Remaining': '0', 'X-GitHub-Media-Type': 'github.v3; format=json', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-RateLimit-Limit': '5000', 'Server': 'GitHub.com'}
source - 2021-11-24 20:21:44 INFO DefaultAirbyteStreamFactory(internalLog):97 - Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)
source - 2021-11-24 20:40:50 INFO DefaultAirbyteStreamFactory(internalLog):97 - Retrying. Sleeping for 1141.9097278118134 seconds
source - 2021-11-24 20:40:50 ERROR DefaultAirbyteStreamFactory(internalLog):95 - Response: {"message":"API rate limit exceeded for user ID 38087517.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}. Headers {'X-OAuth-Scopes': '', 'Content-Security-Policy': "default-src 'none'", 'X-RateLimit-Used': '5000', 'Date': 'Wed, 24 Nov 2021 20:21:44 GMT', 'Vary': 'Accept-Encoding, Accept, X-Requested-With', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-RateLimit-Resource': 'core', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-RateLimit-Reset': '1637786446', 'X-Accepted-OAuth-Scopes': 'repo', 'Content-Type': 'application/json; charset=utf-8', 'Access-Control-Allow-Origin': '*', 'X-XSS-Protection': '0', 'X-GitHub-Request-Id': '06DC:63BC:A69055:138781A:619E9ED7', 'x-oauth-client-id': 'a73408cbac605f1b3660', 'Content-Encoding': 'gzip', 'X-RateLimit-Remaining': '0', 'X-GitHub-Media-Type': 'github.v3; format=json', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-RateLimit-Limit': '5000', 'Server': 'GitHub.com'}
source - 2021-11-24 20:40:50 INFO DefaultAirbyteStreamFactory(internalLog):97 - Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)
source - 2021-11-24 20:41:52 INFO DefaultAirbyteStreamFactory(internalLog):97 - Retrying. Sleeping for 60 seconds
source - 2021-11-24 20:41:52 INFO DefaultAirbyteStreamFactory(internalLog):97 - Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
source - 2021-11-24 20:42:03 INFO DefaultAirbyteStreamFactory(internalLog):97 - Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 1 tries. Waiting 5 seconds then retrying...
source - 2021-11-24 20:42:03 INFO DefaultAirbyteStreamFactory(internalLog):97 - Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
source - 2021-11-24 20:42:29 INFO DefaultAirbyteStreamFactory(internalLog):97 - Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 1 tries. Waiting 5 seconds then retrying...
```

To reproduce this issue, use the following configuration with any type of Github authentication: 
<img width="749" alt="Screen Shot 2021-11-24 at 2 03 34 PM" src="https://user-images.githubusercontent.com/6246757/143312525-5df56392-5a05-4f90-9632-f7ebe6e5d4e7.png">

fyi these logs were obtained with the connector version available [on this branch](https://github.com/airbytehq/airbyte/tree/sherif/github-ratelimit-debugging). I suspect you should be able to reproduce this issue by maxing out your rate limit on a particular API token then observing this behavior. 

This tells me there is a smell with how we are handling rate limiting. 

## Describe the solution you’d like
Rate limit backoff should not trigger a connection timeout

**Comment by augan-rymkhan** [comment]
@sherifnada I reproduced this error on my local machine by setting `time.sleep(300)` # seconds. After awaking when we try to send request by resetting connection, get http.client.RemoteDisconnected error, because Github closes the connection without any response. _(log is provided below)_

![connection closed](https://user-images.githubusercontent.com/93112548/144459595-cdb0c7d7-c18a-4700-98fa-415fc827caca.JPG)


Then tested by setting header "Connection" to "close".  In this case, no such issue happened. Opening a new tcp connection for each http request will slow down the sync process. But I think it's only one reliable solution for now.


> send: b'GET /repos/airbytehq/airbyte/branches?per_page=100&page=2 HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: PostmanRuntime/7.28.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: token f45446617ebcabec085910e78c6b98a000167c3a\r\n\r\n'
reply: ''

{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 1 tries. Waiting 5 seconds then retrying..."}}
Starting new HTTPS connection (27): api.github.com:443
{"type": "LOG", "log": {"level": "DEBUG", "message": "Starting new HTTPS connection (27): api.github.com:443"}}
send: b'GET /repos/airbytehq/airbyte/branches?per_page=100&page=2 HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: PostmanRuntime/7.28.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: token f45446617ebcabec085910e78c6b98a000167c3a\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: GitHub.com
header: Date: Thu, 02 Dec 2021 15:38:54 GMT
header: Content-Type: application/json; charset=utf-8
header: Transfer-Encoding: chunked
header: Cache-Control: private, max-age=60, s-maxage=60
header: Vary: Accept, Authorization, Cookie, X-GitHub-OTP
header: ETag: W/"5c8336abd46d64c4409a1af335e4ecdf5eef3686895bb34dd76da7873d8ca9c0"
header: X-OAuth-Scopes: admin:org, repo
header: X-Accepted-OAuth-Scopes:

**Comment by sherifnada** [comment]
@augan-rymkhan do you have an idea of how much it slows the sync by? what is the tradeoff in this choice?

**Comment by augan-rymkhan** [comment]
@sherifnada I can do researh on the performance for comparing. The tradeoff  is the connector does not face this error after long time sleep.

**Comment by augan-rymkhan** [comment]
Before configuring HTTPAdapter

```
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Retrying. Sleeping for 877.2983934879303 seconds"}}

{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Retrying. Sleeping for 60 seconds"}}

{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 5.0s (requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Caught retryable error '('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))' after 1 tries. Waiting 5 seconds then retrying..."}}
{"type": "RECORD", "record": {"stream": "issue_comment_reactions", "data": {"id": 127835852, "node_id": "MDg6UmVhY3Rpb24xMjc4MzU4NTI=", "user": {"login": "jrhizor", "id": 120362, "node_id": "MDQ6VXNlcjEyMDM2Mg==", "avatar_url": "https://avatars.githubusercontent.com/u/120362?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jrhizor", "html_url": "https://github.com/jrhizor", "followers_url": "https://api.github.com/users/jrhizor/followers", "following_url": "https://api.github.com/users/jrhizor/following{/other_user}", "gists_url": "https://api.github.com/users/jrhizor/gists{/gist_id}", "starred_url": "https://api.github.com/users/jrhizor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jrhizor/subscriptions", "organizations_url": "https://api.github.com/users/jrhizor/orgs", "repos_url": "https://api.github.com/users/jrhizor/repos", "events_url": "https://api.github.com/users/jrhizor/events{/privacy}", "received_events_url": "https://api.github.com/users/jrhizor/received_events", "type": "User", "site_admin": false}, "content": "+1", "created_at": "2021-09-10T22:40:38Z", "repository": "airbytehq/airbyte"}, "emitted_at": 1638540853342}}
```

Raised requests.exceptions.ConnectionError is handled by Default backoff handler, then we sleep 5 seconds.


After configuring HTTPAdapter described here: https://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter

In HttpStream __init__ method:

        self._session = requests.Session()
   
        # Test
        MAX_RETRIES = 3
        adapter = requests.adapters.HTTPAdapter(max_retries=MAX_RETRIES)
        self._session.mount('https://', adapter)
        self._session.mount('http://', adapter)
        print('\n\nMy: adapter setup.\n\n')
        # Test

max_retries – The maximum number of retries each connection should attempt. Note, this applies only to failed DNS lookups, socket connections and connection timeouts, 
never to requests where data has made it to the server. By default, Requests does not retry failed connections.


After connection-related errors it retries to connect again. 
```
{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Retrying. Sleeping for 877.8840591907501 seconds"}}

{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException)"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Retrying. Sleeping for 60 seconds"}}


{"type": "LOG", "log": {"level": "WARN", "message": "Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /repos/airbytehq/airbyte/issues/comments/941290749/reactions?per_page=100"}}
{"type": "RECORD", "record": {"stream": "issue_comment_reactions", "data": {"id": 132269456, "node_id": "REA_lALOEN7yYc44GvT9zgfiRZA", "user": {"login": "jrhizor", "id": 120362, "node_id": "MDQ6VXNlcjEyMDM2Mg==", "avatar_url": "https://avatars.githubusercontent.com/u/120362?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jrhizor", "html_url": "https://github.com/jrhizor", "followers_url": "https://api.github.com/users/jrhizor/followers", "following_url": "https://api.github.com/users/jrhizor/following{/other_user}", "gists_url": "https://api.github.com/users/jrhizor/gists{/gist_id}", "starred_url": "https://api.github.com/users/jrhizor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jrhizor/subscriptions", "organizations_url": "https://api.github.com/users/jrhizor/orgs", "repos_url": "https://api.github.com/users/jrhizor/repos", "events_url": "https://api.github.com/users/jrhizor/events{/privacy}", "received_events_url": "https://api.github.com/users/jrhizor/received_events", "type": "User", "site_admin": false}, "content": "+1", "created_at": "2021-10-13T15:18:05Z", "repository": "airbytehq/airbyte"}, "emitted_at": 1638540849653}}
```
Retries should succeed to establish a new connection.



ConnectionError will not be propagated to the default backoff handler,

**Comment by sherifnada** [comment]
great, let's go with this impl @augan-rymkhan . Thanks for the investigation!
