### ISSUE TITLE
Destination: Local JSON - Autocreate folder for each stream and create files without overlapping filenames. 

### ISSUE THREAD

**Issue by prconstruct** [airbytehq/airbyte#8293]
## Tell us about the problem you're trying to solve
Currently, we have deployed airbyte in AWS EC2 and using S3 - JSONL as the destination. Our ops team doesn't agree to key in the User credentials/secrets to access the S3 bucket. So we have mounted the S3 bucket to the EC2 and the plan is to use it as a local file system. This removes the need for user credentials/secrets. Now we are using Local JSON as the destination. The way the file written to the destination is totally different between S3 and Local JSON connectors.

In S3, the folders are created "Automatically" based on the stream and the files are created in a way that it doesn't get overwritten. But in Local JSON, the folder needs to be Key in and the file name is based on the stream name.

## Describe the solution you’d like
**We would like to have a similar way of file writing mechanism as in S3 for Local JSON**. So the expectation is, in Local JSON - a high-level directory will be configured as part of connector configuration. The subfolders need to be created based on connectors and streams. And the JSONL file needs to be created uniquely for each run without getting overwritten (for ex., the file name appended with timestamp)

## Describe the alternative you’ve considered or used
No alternative as of now

## Are you willing to submit a PR?
Since I'm not familiar in JAVA, I cannot help here.

**Comment by sherifnada** [comment]
@prconstruct what would allow your ops team to feel comfortable using the S3 connector? we're not devoting as much time into the local JSON destination as it's meant more as a "demo" destination. We're focused more on reliability and performance improvements to more ubiquitous connectors like S3 so I'd love to understand if there's anything we could do to make the S3 destination more viable.

**Comment by prconstruct** [comment]
@sherifnada : our Ops expectation is to obtain access using the IAM role (it could be the one attached to the EC2 machine)

**Comment by prconstruct** [comment]
@sherifnada : I agree to close this one as the expectation should be updating the feature of the S3 destination. Please close this one.
