### ISSUE TITLE
🐛 Source Salesforce 0.1.7 fails with _csv.Error: line contains NUL

### ISSUE THREAD

**Issue by ogirardot** [airbytehq/airbyte#8300]
## Enviroment
- **Airbyte version**: 0.32.6-alpha
- **OS Version / Instance**: GCP/GKE
- **Deployment**: Kubernetes
- **Source Connector and version**: Salesforce 0.1.7
- **Destination Connector and version**: Bigquery 0.5.0 (or denormalized 0.1.10)
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
The saleforce incremental sync fails:
```
Traceback (most recent call last):
  File "/airbyte/integration_code/source_salesforce/source.py", line 85, in read
    internal_config=internal_config,
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 136, in _read_stream
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 181, in _read_incremental
    for record_counter, record_data in enumerate(records, start=1):
  File "/airbyte/integration_code/source_salesforce/streams.py", line 249, in read_records
    for count, record in self.download_data(url=job_full_url):
  File "/airbyte/integration_code/source_salesforce/streams.py", line 213, in download_data
    for i, row in enumerate(csv_data):
_csv.Error: line contains NUL
```

## Expected Behavior
The salesforce sync should work

## Logs

[logs-451-1.txt](https://github.com/airbytehq/airbyte/files/7624316/logs-451-1.txt)

## Steps to Reproduce
1. just trying to sync

## Are you willing to submit a PR?
YES !

**Comment by sherifnada** [comment]
@ogirardot could you download the full logs from the Airbyte UI and share them here to help us understand the full context of the failure?

**Comment by ogirardot** [comment]
sure,
[logs-451-1.txt](https://github.com/airbytehq/airbyte/files/7619439/logs-451-1.txt)

**Comment by alafanechere** [comment]
Thanks @ogirardot for opening the issue, I allowed myself to edit the issue a bit. @sherifnada I added this to GL Python Backlog, let me know if I should not do this.

**Comment by grubberr** [comment]
According to logs, you got `null` byte character in your stream which crash python `cve` module with this exception `_csv.Error: line contains NUL`. I cannot reproduce this bug locally that why
I have generated temp docker image `airbyte/source-salesforce:20211201-1` (PR https://github.com/airbytehq/airbyte/pull/8405) which has to fix this problem.
@ogirardot can you please re-sync your data using this docker image and tell me result and send logs?

Thank you

**Comment by ogirardot** [comment]
tested for 24 hours and no issue detected, the patch looks great

**Comment by grubberr** [comment]
@ogirardot 
Can you please send you logs? (or maybe grep  yourselves, whatever is more convenient for you)
I want to check if you have pattern `Filter 'null' bytes from string, size reduced` in logs 
Thanks!
