### ISSUE TITLE
🐛 Source Confluence: missing seed files

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8307]
Source Confluence connector is not available for users because it's not listed in `./airbyte-config/init/src/main/resources/seed/source_definitions.yaml`

**Comment by YowanR** [comment]
@alafanechere this looks like it has been resolved. Can you confirm before I close this issue?

**Comment by darynaishchenko** [comment]
> @alafanechere this looks like it has been resolved. Can you confirm before I close this issue?

@YowanR I can confirm. It's listed in https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L370
