### ISSUE TITLE
Source Recurly: refactor to use the CDK

### ISSUE THREAD

**Issue by vitaliizazmic** [airbytehq/airbyte#8318]
The Recurly connector currently uses an old pattern, we should migrate it to use the new CDK. It's part of #6164.

## Describe the solution you’d like
see #6164 for clearer instructions

**Comment by mohamagdy** [comment]
@vitaliizazmic @sherifnada any work done to migrate Recurly to CDK yet? If not, I can work on it as we need an `incremental` sync mode for the Recurly source and it will make more sense to add the `incremental` sync mode after migrating to CDK and not extending the `base-python` Recurly connector, right?

**Comment by sherifnada** [comment]
hi @mohamagdy ! It should be moved soon -- vitalii is managing it. Afterwards we'd be more than happy to support a contribution!

**Comment by mohamagdy** [comment]
Hi @sherifnada, 

Sounds like a plan. Looking forward to it. Thanks for the update.
