### ISSUE TITLE
Set resource limits on containers pods to avoid pod eviction

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#8319]
## Tell us about the problem you're trying to solve
See original oncall issue for details: https://github.com/airbytehq/oncall/issues/1

This issue is that containers `main`, `remote-stdin`, `relay-stderr`, `relay-stdout`, and `call-heartbeat-server` all do not have any resource requests, so when the node that these pods are scheduled on runs low on resources, these pods get evicted as they are always "above" their resource requests (which is 0 if not configured). 

## Describe the solution you’d like
The solution is to add resource request configurations to these containers, likely in the KubePodProcess file [here](https://github.com/airbytehq/airbyte/blob/a65b493f5ab4046e13ff3fc4a886add6e589be76/airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java#L322-L365). These resource request settings should likely be configurable so that they can be raised/lowered by users as needed.

**Comment by jrhizor** [comment]
This seems pretty high prio since it can result in quite a few number of "sync stability" bugs if we're hitting capacity limits.
