### ISSUE TITLE
Periodically run connection checks on all connectors in a workspace and notify of failure

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8322]
## Tell us about the problem you're trying to solve
Let's say I'm a user who setup a connector e.g: postgres successfully using SSH authenticaiton. Then, I change my firewall settings and accidentally now the connector i setup is invalid. I would like to receive a notification informing me that the connection check is no longer succeeding (perhaps trying it 2 or 3 times if it is failing to make sure the failure is persistent).

**Comment by jrhizor** [comment]
Are alerts on sync failures insufficient for this purpose?

**Comment by sherifnada** [comment]
Good point. I guess the problem here is that the user hadn't setup alerting. I wonder if we should setup email alerting by default, at least on cloud.

**Comment by evantahler** [comment]
Closing because we have sync failure notifications, and will be making those more robust in the future
