### ISSUE TITLE
Source Google Ads: Add network fields to Click View stream

### ISSUE THREAD

**Issue by arniwesth** [airbytehq/airbyte#8331]
## Tell us about the problem you're trying to solve
Get more fields for `[Google Ads](https://docs.airbyte.io/integrations/sources/google-ads) Click View`

## Describe the solution you’d like
I need these additional fields in the `Google Ads Click View`:
```
segments.ad_network_type, 
campaign.network_settings.target_content_network, 
campaign.network_settings.target_google_search, 
campaign.network_settings.target_partner_search_network, 
campaign.network_settings.target_search_network
```

## Describe the alternative you’ve considered or used
Making a custom `GAQL` does not seem to be a feasible solution as `click_view` requires `segments.date` in the `WHERE` clause.

## Are you willing to submit a PR?
Currently, it will be difficult to set off time for this, but I will see what I can do.

**Comment by vitaliizazmic** [comment]
@arniwesth could you please clarify why making a custom GAQL isn't seem a feasible solution?
