### ISSUE TITLE
Instagram Source Connector:Authenticate button does not work

### ISSUE THREAD

**Issue by ycherniaiev** [airbytehq/airbyte#8337]
## Steps to reproduce:
Choose Instagram Source and press "Authenticate" button

## Current Behavior
Nothing happens. 
Client ID is not added to config:
![image](https://user-images.githubusercontent.com/94798230/144054125-b463b751-fd5c-452a-b1c3-841b63aa1fe9.png)

## Expected Behavior
You are redirected to Consent Screen

**Comment by lazebnyi** [comment]
@sherifnada Hi, I think the solution for this issue is to set instancewide parameters for Instagram on the cloud. Could you help with this?

**Comment by sherifnada** [comment]
@lazebnyi which params should be set for the connector? can you point me to them in lastpass?

**Comment by lazebnyi** [comment]
@sherifnada client_id and client_secret. You can find it in `Facebook Developer App client_id / client_secret` creds in LastPass.

**Comment by sherifnada** [comment]
can you follow the instructions [here](https://airbytehq.slack.com/archives/C022G3PV0H1/p1640073759347100?thread_ts=1640012408.343400&cid=C022G3PV0H1) to add them to the dev environment and test it there?

**Comment by lazebnyi** [comment]
@sherifnada Successfully tested on dev environment. [PR](https://github.com/airbytehq/airbyte-cloud/pull/794) for deployment.

**Comment by bazarnov** [comment]
@sherifnada you can check and test the Instagram OAuth Flow using this `dev-1` resource: https://dev-1-cloud.airbyte.io/
Currently it's deployed from this PR: https://github.com/airbytehq/airbyte-cloud/pull/794

**Comment by lazebnyi** [comment]
On hold 
Waiting publishing on prod - https://github.com/airbytehq/airbyte-cloud/pull/794

**Comment by bazarnov** [comment]
Successfully deployed and tested on prod https://cloud.airbyte.com/

<img width="1298" alt="Screenshot 2022-02-03 at 16 36 23" src="https://user-images.githubusercontent.com/22987674/152363706-0e5d138d-3187-4d8c-82d7-fe9dcdfda04a.png">
