### ISSUE TITLE
Airbyte-cancelled syncs show as successsful

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#8339]
## Tell us about the problem you're trying to solve
A connection shows up as successful on the "Connections" page despite having never succeeded. This is misleading to the end user as it indicates that the connection is successful at a glance, but when looking into the sync history, it shows as never having been successful. This causes latency in raising issues with connectors. 

## Describe the solution you’d like
A different icon used (the red x) instead of a green successful checkmark for any connection whose most recent sync was not successful.

In the example shown, each sync errored and was subsequently cancelled by Airbyte (not the end user). 

<img width="1440" alt="Screen Shot 2021-11-30 at 8 39 52 AM" src="https://user-images.githubusercontent.com/38087517/144089732-29efb614-e4c1-4822-a782-5f4ca1e702dc.png">

<img width="1436" alt="Screen Shot 2021-11-30 at 8 39 57 AM" src="https://user-images.githubusercontent.com/38087517/144089747-a77818cf-717f-4e2c-94a7-e0c989e3a25f.png">

**Comment by cgardens** [comment]
My guess it that the root cause is the same as this OC issue: https://github.com/airbytehq/oncall/issues/46 . All future updates will be on that issue until it is closed or until we realize it is a different root cause.

**Comment by jrhizor** [comment]
duplicate: https://github.com/airbytehq/airbyte/issues/6990

**Comment by edmundito** [comment]
No longer valid. The status icons have been updated to better reflect this.
