### ISSUE TITLE
Update fields in source-connectors specifications: amplitude, apify-dataset, appstore-singer, aws-cloudtrail, azure-table, bigcommerce, bigquery, braintree, cart, chargebee

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#8364]
Update fields in source-connectors specifications: 

source-amplitude
source-apify-dataset
source-appstore-singer
source-aws-cloudtrail
source-azure-table
source-bigcommerce
source-bigquery
source-braintree
source-cart
source-chargebee

[EPIC] Add title and description properties to each field in connectors specifications and order input fields appropriately #8324

**Comment by yevhenii-ldv** [comment]
blocked publish by https://github.com/airbytehq/airbyte/issues/8767
