### ISSUE TITLE
Add ability to change start date

### ISSUE THREAD

**Issue by schlattk** [airbytehq/airbyte#8377]
Currently once a source has been set up, changing the time from when the sync starts doesn't affect the sync process, without doing a complete data reset. It would be beneficial to have the ability to go back further in time without having to do that.

**Comment by alafanechere** [comment]
Hi @schlattk thanks for this suggestion, could you tell for which connector you'd like this feature specifically?

**Comment by marcosmarxm** [comment]
I tested using latest version of Airbyte (0.40.22) and was able to change start date from Zendesk Support connector.
