### ISSUE TITLE
[EPIC] Docker image version for testcontainers in  integration tests

### ISSUE THREAD

**Issue by mkhokh-33** [airbytehq/airbyte#8384]
## Tell us about the problem you're trying to solve
 Some integration tests create db test containers with specified version, like mysql for example : "mysql:8.0"
 Some of them no like cockroach "cockroachdb/cockroach" in this case the latest version were taken
  If the latest version will be taken we can face a situation when the latest changes will fail integration tests
 We need to check all connector to use the stable version of image for test containers.

## Describe the solution you’d like
1. Check all integration test in order to see which of them use latest or specified docker image for test containers and change the latest to stable 
1. Maybe we should consider an idea to have a separate integration test with different 2 docker images(the latest one and the last stable versions)
2. Think about the way to specify in documentation version of db or other source which are supported by connector 
3. Think about policy to follow source/destination latest releases and update docker image versions for test containers in integration tests
- [x] #8667
- [x] #8670
- [x] #8671
- [x] #8672

## Additional context
I faced with the problem when integration test was using always the latest docker image version.
Test start failing without any code changes because the new version of docker image was pushed and it contains some changes which broke existing tests

**Comment by VitaliiMaltsev** [comment]
In Acceptance tests currently used docker images:

**Destinations**
Cassandra → cassandra:3.11.11
Elasticsearch → docker.elastic.co/elasticsearch/elasticsearch:7.15.1
Postgres → postgres:13-alpine
Kafka → confluentinc/cp-kafka:6.2.0
Kinesis → localstack/localstack:0.12.20
MariaDB → mariadb/columnstore:latest  
MeiliSearch → getmeili/meilisearch:latest
MongoDB → mongo:4.0.10
Mqtt → hivemq/hivemq-ce:2021.2
MSSQL → mcr.microsoft.com/mssql/server:2019-latest
MySQL → mysql:8.0
Oracle → gvenzl/oracle-xe:18.4.0-slim
Pulsar → apachepulsar/pulsar:2.8.1
Redis → redis:6.0
Scylla → scylladb/scylla:4.5.0

**Sources**

ClickHouse → yandex/clickhouse-server:21.8.8.29-alpine
Cockroach → cockroachdb/cockroach:v20.2.18
Db2 → ibmcom/db2:11.5.5.0
PostgreSQL → postgres:13-alpine
Kafka → confluentinc/cp-kafka:6.2.0
MongoDB → mongo:4.0.10
MSSQL → mcr.microsoft.com/mssql/server:2019-latest
MySQL → mysql:8.0
Oracle → epiclabs/docker-oracle-xe-11g
