### ISSUE TITLE
Source Google Search Console: possibility to work with Domain Property

### ISSUE THREAD

**Issue by heinhofman** [airbytehq/airbyte#8387]
## Tell us about the problem you're trying to solve
When using a [Domain Property](https://support.google.com/webmasters/answer/10431861) in Google Search Console I'm unable to add this to the configuration of the Airbyte Source Connector. 

## Describe the solution you’d like
Instead of the possibility to only add [URL-prefix property](https://support.google.com/webmasters/answer/10432366), I would like to [add both types of property](https://support.google.com/webmasters/answer/34592). By making it possible to add both in the config. 

The URL of the property to retrieve, as defined by Search Console.: 

Examples:
 http://www.example.com/ (for a URL-prefix property) 
 sc-domain:example.com (for a Domain property)

[See the API documentation.](https://developers.google.com/webmaster-tools/search-console-api-original/v3/sites/get) 

## Describe the alternative you’ve considered or used
I've tried to input the Domainproperty as: sc-domain:example.com this won't work. 

## Additional context
Non

## Are you willing to submit a PR?
No

**Comment by krisjan-oldekamp** [comment]
Tried the same here (adding sc-domain:example.com as the property). Able to save the configuration but fetching data doesn't work.

**Comment by itaseskii** [comment]
@heinhofman Can you please verify if this issue has been fixed for you? I'm unable to reproduce it and the above comment has reported that the issue should be fixed with 0.35.11-alpha.

**Comment by YowanR** [comment]
@heinhofman Any updates on this one? If not, we should move to close this.

**Comment by heinhofman** [comment]
Hi @YowanR it works as inteded. THNX
