### ISSUE TITLE
Explore replacing env vars with config files.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#8393]
## Tell us about the problem you're trying to solve
As Airbyte configurability grows, it is becoming more and more unwieldy to use env vars.

The main issue here is that the env var file becomes a mess and it's tough to read/understand what is going on .

## Describe the solution you’d like
We should
- move to config files.
- with the option to override with env vars, if needed.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by evantahler** [comment]
cc @jdpgrailsdev 
I think the Micronaut config files solve this nicely!
