### ISSUE TITLE
CI Sandbox My Hours

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8401]
We'd need an integration account for [MyHours](https://myhours.com/) to test this community contribution: https://github.com/airbytehq/airbyte/pull/8270

**Comment by karinakuz** [comment]
Free trial account is created (Pro trial expires in 14 days) with the data. Credentials are added to the LastPass with 'MyHours' name. API tested for the next main streams:
- All Projects https://api2.myhours.com/api/Projects/getAll
- Project Details https://api2.myhours.com/api/Projects/1668471/overview
- All Clients https://api2.myhours.com/api/Clients
- All Team Members https://api2.myhours.com/api/Users/getAll
- Dashboard Report (Group by Project-Tasks) https://api2.myhours.com/api/Reports/distribution?DateFrom=2021-12-01&DateTo=2021-12-30&ReportGroup=0
- Dashboard Report (Group by Tasks) https://api2.myhours.com/api/Reports/distribution?DateFrom=2021-12-01&DateTo=2021-12-30&ReportGroup=1
- Dashboard Report (Group by Client-Projects) https://api2.myhours.com/api/Reports/distribution?DateFrom=2021-12-01&DateTo=2021-12-30&ReportGroup=2
- Dashboard Report (Group by Team members) https://api2.myhours.com/api/Reports/distribution?DateFrom=2021-12-01&DateTo=2021-12-30&ReportGroup=3
- All Time Logs https://api2.myhours.com/api/Reports/activity?DateFrom=2021-12-01&DateTo=2021-12-30

**Comment by karinakuz** [comment]
Free trial account (full-featured)  is extend for 90 days.

**Comment by karinakuz** [comment]
We have now extended trial period till 1 Apr 2022.
