### ISSUE TITLE
Improve database usability by providing better feedback of invalid inputs

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8404]
Need scoping.

**Comment by grishick** [comment]
The solution should probably include using new AirbyteTraceMessage (https://github.com/airbytehq/airbyte/issues/12322, https://github.com/airbytehq/airbyte/issues/12161, https://github.com/airbytehq/airbyte/issues/12519)

**Comment by grishick** [comment]
@tuliren can you add more scope?
