### ISSUE TITLE
Airbyte Cloud Demo Videos Incorrect

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#8409]
## Tell us about the problem you're trying to solve
Both thumbnails on the Airbyte Cloud onboarding flow lead to the same demo video being loaded. The demo video refers to an OSS implementation and begins with the first frame using `docker compose`.

## Describe the solution you’d like
Left thumbnail should be a demo video - this video needs to be re-recorded to be for Airbyte Cloud, not OSS. 
Right thumbnail should open up a new tab with the demo instance.

## Describe the alternative you’ve considered or used
N/A

## Additional context
![Airbyte Get Started 2021-11-17 at 6 35 17 PM](https://user-images.githubusercontent.com/16851149/144328225-34863012-39bd-456b-a12d-da1e012b3f0e.jpg)

## Are you willing to submit a PR?
N/A

**Comment by misteryeo** [comment]
cc: @johnlafleur as promised - we'll likely need a new thumbnail design.

Does Abhi record the demo video for Cloud?

**Comment by johnlafleur** [comment]
It's actually an implementation bug. 
The initial specs were the following: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=26178%3A387

So the 2nd thumbnail is wrong and should open https://demo.airbyte.io in a new tab.

**Comment by onelharrison** [comment]
This issue exists in the following components.

-  [WelcomeStep](https://github.com/airbytehq/airbyte/blob/f37d13ffa3a004ffea47446b34a1d8e93b85ba57/airbyte-webapp/src/pages/OnboardingPage/components/WelcomeStep.tsx#L52)
- [FinalStep](https://github.com/airbytehq/airbyte/blob/f37d13ffa3a004ffea47446b34a1d8e93b85ba57/airbyte-webapp/src/pages/OnboardingPage/components/FinalStep.tsx#L74)
