### ISSUE TITLE
Improve Documentation Sidesheet UI

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#8411]
## Tell us about the problem you're trying to solve
Setup Guide sidesheet UI is difficult to parse and incorrectly formatted as well as having markdown / code exposed.

## Describe the solution you’d like
Fix the way this sidesheet renders so that tables are shown and the page break is rendered correctly similar to our actual docs site. This particular example is Amplitude but applies to any tables that should be rendered from docs.

The Apify Dataset sidesheet also shows some weird meta description at the top of the page.

## Describe the alternative you’ve considered or used
N/A

## Additional context
![Airbyte Get Started 2021-11-17 at 6 52 00 PM](https://user-images.githubusercontent.com/16851149/144331508-466de5a7-7f33-4b05-93c8-b12e4825432f.jpg)

## Are you willing to submit a PR?
N/A

**Comment by jrhizor** [comment]
We should try to:
* match the Gitbook format
* filter out description/Gitbook metadata
* filter out html comments

**Comment by misteryeo** [comment]
@timroes FYI, I'm still seeing metadata appear in sidesheets in Cloud: https://share.getcloudapp.com/qGurmNZz

**Comment by timroes** [comment]
@misteryeo thanks for the report. I've created https://github.com/airbytehq/airbyte/issues/10491 to track this.
