### ISSUE TITLE
Investigate Deprecating API Type parameter in Source Salesforce

### ISSUE THREAD

**Issue by augan-rymkhan** [airbytehq/airbyte#8419]
## Enviroment
- **Airbyte version**: 
- **OS Version / Instance**: 
- **Deployment**: *
- **Source Connector and version**: Salesforce
- **Destination Connector and version**: *
- **Severity**: Low 
- **Step where error happened**: 
## Current Behavior
*Tell us what happens.*

## Expected Behavior
Deprecate "API Type" parameter in Source Salesforce. This is an implementation detail that we should remove eventually.

## Acceptance Criteria
The output of this issue should be a proposal/document describing whether it is possible to deprecate this option, and what are the tradeoffs when doing so.

**Comment by sherifnada** [comment]
@augan-rymkhan actually this is one of the very few cases where it _might_ not an implementation detail. Salesforce actually has two different account types: sandbox and production. They operate in different domains (my.salesfroce.com and test.salesforce.com). If you can find a way to identify reliably if the user should be using a sandbox account, great, let's do it. But I suspect it may be difficult especially with oauth

**Comment by sherifnada** [comment]
@augan-rymkhan I just realized why you created this issue, because of my comment on the other PR. 

That comment was directed at the "API Type" parameter not the sandbox, apologies for putting it on the wrong line.

**Comment by augan-rymkhan** [comment]
@sherifnada no worry, I have updated it.

**Comment by augan-rymkhan** [comment]
### Scoping report

By default we should try to use BULK API.

Pros and cons of BULK API version:

Pros:
1) BULK API returns a `csv` file. It helps to avoid rate limit. 
2) It also supports incremental sync.

Cons:
1) Salesforce BULK API currently does not support loading fields with data type base64 and compound data (nested object)
   If the stream's schema contains base64 or/and nested object, use REST version of the stream.

2) BULK API is not supported by some streams.
   We should use REST version of stream.

**Comment by sherifnada** [comment]
Some questions: 

1. what does `base64` correspond to in Salesforce? I'm trying to understand how often a user will have a base64 object or a compound data field, which would impact this. 
2. what is the performance difference between bulk and REST API performance?

**Comment by augan-rymkhan** [comment]
1.  `base64` corresponds to binary files 
For more info you can check [this](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/primitive_data_types.htm).


Address, Geolocation are [compound data field.](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/compound_fields_address.htm)

**Comment by sherifnada** [comment]
@misteryeo do you feel comfortable making the call here?

**Comment by sherifnada** [comment]
@augan-rymkhan can you do one more test with very high volume of data? I suspect that for a sufficiently high volume of data in a single stream, BULK is faster than REST. It may be useful to know what that is. 

My guess is we may want to follow the strategy of: for the initial sync, always use bulk. For the incremental syncs, use REST. Just a guess though.

**Comment by augan-rymkhan** [comment]
I tried to import 1million records for **Note** stream via BULK API, but it created only 10K records, because we reached storage limit in Salesforce account.
![image](https://user-images.githubusercontent.com/93112548/147489015-14c3c8df-3a37-4dc3-9db4-96836ae8e8a1.png)

**Comment by augan-rymkhan** [comment]
![image](https://user-images.githubusercontent.com/93112548/147529770-aeefe47b-8415-409c-a806-91b9c95a602a.png)

**Comment by sherifnada** [comment]
@augan-rymkhan what storage limit are you referring to? is it on salesforce side? feel free to increase it as needed.

**Comment by augan-rymkhan** [comment]
@sherifnada 
Yes, we need to increase data storage in Salesforce account. I've found this:
   _You can increase your data storage by buying additional data storage. It can be purchased on Your Account or by contacting your Account representative._ 
https://help.salesforce.com/s/articleView?id=000334051&type=1
I think we need help from your side here.

**Comment by sherifnada** [comment]
@augan-rymkhan feel free to use the connectors credit card to purchase more quota, find it in lastpass

**Comment by sherifnada** [comment]
also @augan-rymkhan I think I don't follow why we need to increase the storage limit. Didn't we already write 1 million records which we read via the batch API? why do we need to store things separately for the REST API?

**Comment by augan-rymkhan** [comment]
@sherifnada I don't think we have 1 million records for one stream. The idea was to import more rows for one stream, then compare performance BULK vs REST. Not for only REST API.

**Comment by sherifnada** [comment]
sorry I misread your earlier message about 10k records as 10M -- nvm me

**Comment by augan-rymkhan** [comment]
A Partner Developer Edition is a licensed version of the free Developer Edition that includes more storage, features, and licenses. Partner Developer Editions are free to enrolled Salesforce partners. [For more](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/intro_de_sandbox.htm)

![image](https://user-images.githubusercontent.com/93112548/148181705-6a508f33-7827-4fd7-93be-3f68aa42eca4.png)
