### ISSUE TITLE
Source Google Ads: Add `Geographic` and `Keyword` streams

### ISSUE THREAD

**Issue by cobobrien** [airbytehq/airbyte#8424]
## Tell us about the new connector you’d like to have
* Which source and which destination?

_This is an enhancement to an existing source connector - Google Ads_

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB?

_No_

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.

_We rely on metrics from these two views being pulled. They are not currently supported by Shopify, so it would be great to include them_

* How often do you want to run syncs?
_Daily_

* If this is an API source connector, which entities/endpoints do you need supported?

_Geographic Views - https://developers.google.com/google-ads/api/rest/reference/rest/v8/customers.geographicViews_
_Keyword Views - https://developers.google.com/google-ads/api/rest/reference/rest/v8/customers.keywordViews_

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name?
_NA_

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
_Calling the Google Ads API directly on behalf of users_

## Are you willing to submit a PR?
_Yes, incoming_

**Comment by misteryeo** [comment]
@harshithmullapudi since we merged [#8521 ](https://github.com/airbytehq/airbyte/pull/8521), can you confirm and close this issue which I believe should now be implemented?

**Comment by misteryeo** [comment]
Closing as PR was merged.
