### ISSUE TITLE
decide on method to scale up Temporal

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#8440]
Look at plugging in a HA version of Temporal into the OSS Helm and Cloud Helm versions of Airbyte.

We can't do this easily for non-Helm OSS Kube, so we'll keep that non-HA.
For OSS Helm we should add the option of plugging in a chart for https://github.com/temporalio/helm-charts so we can offer an HA option.
For Cloud Helm we could either take the same approach as OSS Helm. We should also investigate Temporal's cloud offering and see if it's appropriate for our use case.

**Comment by evantahler** [comment]
We use temporal cloud now!
