### ISSUE TITLE
scale test scheduler2

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#8454]

**Comment by cgardens** [comment]
From our Q4 OKRs
> KR: Ability to support 5K active connections
> KR: Ability to support 1K parallel syncs

**Comment by pmossman** [comment]
Findings and action items out of this load test are documented [here](https://docs.google.com/document/d/1au7DMjYtavnO8jKdZuQOv4TgyPoG12KMM7cRaX4Tfg8/edit#)
