### ISSUE TITLE
CI Sandbox for Source Hellobaton 

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8476]
## Tell us about the problem you're trying to solve
Need credentials to test community contribution for new source Hellobaton https://github.com/airbytehq/airbyte/pull/8461

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
Sent two letters with request to Hello Baton (Nov 15 and 17)

**Comment by marcosmarxm** [comment]
Thanks @karinakuz. The contributor shared his credentials, but for integration account we need an account.

**Comment by karinakuz** [comment]
There is no answer from Baton after I shared more details Dec 17, sent one more letter to receive any update from Baton

**Comment by karinakuz** [comment]
Sandbox with data is created, credentials are added to Last Pass with the name 'Hello Baton', tested api for the streams:
- activity_list https://airbyte-integration-test.hellobaton.com/api/activity/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- activity_read https://airbyte-integration-test.hellobaton.com/api/activity/348852/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- companies_list https://airbyte-integration-test.hellobaton.com/api/companies/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- companies_read https://airbyte-integration-test.hellobaton.com/api/companies/4745/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- projects_list https://airbyte-integration-test.hellobaton.com/api/projects?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- projects_read https://airbyte-integration-test.hellobaton.com/api/projects/6325/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- phases_list https://airbyte-integration-test.hellobaton.com/api/phases/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- phases_read https://airbyte-integration-test.hellobaton.com/api/phases/3923/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- tasks_list https://airbyte-integration-test.hellobaton.com/api/tasks/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- tasks_read https://airbyte-integration-test.hellobaton.com/api/tasks/172375/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- task_attachments_list https://airbyte-integration-test.hellobaton.com/api/task_attachments/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- task_attachments_read https://airbyte-integration-test.hellobaton.com/api/task_attachments/11834/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- milestones_list https://airbyte-integration-test.hellobaton.com/api/milestones/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- milestones_read https://airbyte-integration-test.hellobaton.com/api/milestones/35215/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- users_list https://airbyte-integration-test.hellobaton.com/api/users/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
- users_read https://airbyte-integration-test.hellobaton.com/api/users/44756/?api_key=7HhThgSq.fm2ToWJakp2yp26uaWrklApYadz5LsAF
