### ISSUE TITLE
Depend on versioned image of normalization base before v0.5.0 release

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#848]
## Tell us about the problem you're trying to solve
We [currently](https://github.com/airbytehq/airbyte/blob/master/airbyte-workers/src/main/java/io/airbyte/workers/normalization/DefaultNormalizationRunner.java#L46)  depend on the `dev` image. Must publish a versioned image and depend on it in the code. 

We also shouldn't hardcode this in Java, but this issue is the bare minimum needed before release.

**Comment by cgardens** [comment]
closed by https://github.com/airbytehq/airbyte/pull/930
