### ISSUE TITLE
SAT should verify data is coming from all streams except if the developer explicitly opts out

### ISSUE THREAD

**Issue by augan-rymkhan** [airbytehq/airbyte#8481]
## Tell us about the problem you're trying to solve
SAT should verify data is coming from all streams except if the developer explicitly opts out.

## Describe the solution you’d like
For example, if there are streams A and B and the user provides a configured catalog containing only A, the test should fail.
If the developer has to skip tests for some streams , there should be an option saying that they are skipping those streams, as well as providing a reason.

## Are you willing to submit a PR?

Yes

**Comment by keu** [comment]
closing as `won't fix` - this feature is already in place and matches the current behaviour of SAT
