### ISSUE TITLE
🐛 Source MongoDB: arm64 image is not available (Apple M1)

### ISSUE THREAD

**Issue by bendicethesecond** [airbytehq/airbyte#8488]
## Environment
- **Airbyte version**:  0.32.11-alpha
- **OS Version / Instance**: macOS M1
- **Deployment**: docker-compose quickstart
- **Source Connector and version**: Mongodb 0.1.8 
- **Severity**: Low
- **Step where error happened**: Setup new connection

## Current Behavior
When setting up a mongodb connector on an M1 when creating the connection it sits on the spinner on testing connection.

## Expected Behavior
Should test the connection and either return an error or success

## Logs

<details>
<summary>LOG</summary> 

```

`airbyte-worker     | 2021-12-03 13:50:08 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/2e468b57-aafe-47ed-9049-4d530ff9d1cd/0/logs.log} - WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

```

</details>

## Steps to Reproduce
1. Create mongodb connection on m1 mac
2. Test connection

**Comment by alafanechere** [comment]
Just to add a bit of context: looks like the failure comes from the image used in `./airbyte-integrations/connectors/source-mongodb/Dockerfile.test`

**Comment by marcosmarxm** [comment]
Latest version has arm64 for Mongodb
![image](https://user-images.githubusercontent.com/5154322/204869079-01245615-9666-461e-af80-b2f562ab3c8c.png)
