### ISSUE TITLE
Create customer in billing vendor upon CloudWorkspace creation for test billing user

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#8496]
## Tell us about the problem you're trying to solve
This is a ticket within the [Integrate backend with billing vendor Epic](https://github.com/airbytehq/airbyte/issues/8463)

To start integrating with the billing vendor, we must first create customers in their platform so that we can start reporting credit usage for those customers.

## Describe the solution you’d like
Upon creation of a CloudWorkspace in the CloudWorkspaceHandler, the following logic should be executed **for a test billing user ID only**:

- An API request should be made to the billing vendor to create a customer in their system, with the external customer ID set to the workspace ID and the name set to the workspace name. Add trial credits to the customer with 1-month expiration times if this is the first CloudWorkspace created for the billing user.
- In addition to creating the customer, the billing plan created in https://github.com/airbytehq/airbyte/issues/8504 should be applied to the newly created customer, through another API call to the billing vendor.
- ~While the workspace ID can be used to reference the customer in some requests to the billing vendor, there are also requests that require the billing vendor's customer ID to be used, so we need to store the billing vendor's customer ID that gets returned upon creation. This can be stored as a new column on the CloudWorkspace, or in a completely new table~ 
It was recently discovered the Orb actually supports using external customer ID (i.e. workspace ID) for _all_ requests, so this is no longer necessary
- If the request to create the customer in the billing vendor is unsuccessful, the CloudWorkspaceHandler endpoint should still create the CloudWorkspace and succeed - this will keep us isolated from any vendor downtime that might occur. In this case, the customer creation will happen lazily in another part of the app (separate ticket).

The above logic should be encapsulated in a billing vendor-specific lib/module, to which other vendor-API logic will be added as needed in future tickets.

## Describe the alternative you’ve considered or used
Instead of storing the customer ID on our side, we could opt to not store it at all. Instead, before making any request that requires the customer ID, we would need to first make a separate request to fetch the customer ID from the external customer ID, and then use that in the desired request. 

However, storing the customer ID on our side makes things slightly more efficient and may be useful in some debugging cases. We could always use the above strategy as a fallback if a CloudWorkspace does not have a customer ID stored on our side for some reason.

**Comment by cgardens** [comment]
How do we handle the case if the vendor is "down"? Should we still be able to create new users / customers in airbyte, even if we can't create them in the billing vendor?
