### ISSUE TITLE
Compare billing vendor credit consumption to ours

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#8506]
## Tell us about the problem you're trying to solve
This is a ticket within the [Integrate backend with billing vendor Epic](https://github.com/airbytehq/airbyte/issues/8463)

After a day or two of reporting usage from our CreditProcessingCronJob to the billing vendor, we need to validate that the credit balances in our database are equal to the credit balances in the billing vendor, and investigate/fix any inconsistencies that are found.

## Describe the solution you’d like
The best solution would be some sort of script that fetches the balances of all CloudWorkspaces in the cloud db, compares each to the balance of the corresponding customer in the billing vendor, and outputs a summary of which balances are inconsistent between the two, if any. 

If any inconsistencies are found, they should be investigated to determine why an inconsistency occurred. Things that will prove useful in this investigation are looking at CreditConsumptionRecords generated by the CreditProcessingCronJob, and using the billing vendor's API to fetch the credit ledger to see when and why credits were deducted to cause the resulting balance.

## Describe the alternative you’ve considered or used
A not as great but potentially less time-consuming solution would be manually checking several balances as a sample to see if there are any inconsistencies, and if none are found then concluding that the systems are in sync.

**Comment by cgardens** [comment]
Once we get to a place where we are not seeing discrepancies, how long should we continue running the test?

**Comment by lmossman** [comment]
I think a full week of no credit discrepancies would be a pretty solid indicator that we can move forward with the rest of the tickets

**Comment by lmossman** [comment]
It has been validated that credit discrepancies between Orb and Airbyte are only due to Orb's credit calculations being _more_ precise than Airbyte's.
