### ISSUE TITLE
   :bug: Source Mailchimp Failed to change version on UI

### ISSUE THREAD

**Issue by VitaliiMaltsev** [airbytehq/airbyte#8526]
## Current Behavior
During version changing in Settings Tab on UI an error persists

Logs
`airbyte-worker      | 2021-12-06 09:06:12 INFO i.a.w.p.DockerProcessFactory(create):127 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0 --network host --log-driver none airbyte/source-mailchimp:dev spec
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} - Traceback (most recent call last):
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -   File "/airbyte/integration_code/main.py", line 8, in <module>
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -     from airbyte_cdk.entrypoint import launch
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/__init__.py", line 2, in <module>
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -     from .entrypoint import AirbyteEntrypoint
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 16, in <module>
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -     from airbyte_cdk.sources import Source
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/__init__.py", line 1, in <module>
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -     from .abstract_source import AbstractSource
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 31, in <module>
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} -     from airbyte_cdk.utils.event_timing import create_timer
airbyte-worker      | 2021-12-06 09:06:13 ERROR i.a.c.i.LineGobbler(voidCall):82 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} - ModuleNotFoundError: No module named 'airbyte_cdk.utils'
airbyte-worker      | 2021-12-06 09:06:13 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):170 - {job_log_path=/tmp/workspace/1dd9f984-cb13-4dea-8eec-6a65f12ead18/0/logs.log} - Completing future exceptionally...`
## Expected Behavior
*Tell us what should happen.*

**Comment by bazarnov** [comment]
No need to be fixed.
