### ISSUE TITLE
oneOf does not work for source-file

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#853]
## Expected Behavior
* Based on which storage type the user picks different fields in the form should appear for the user to fill in.

## Current Behavior
* Fields do not change.

## Context
* this not unexpected. we knew that the jsonschema that is in source-file's spec was going to have to be tweaked. now we just go make sure we do it.

**Comment by cgardens** [comment]
@ChristopheDuong - based on this conversation is this something you think that you can update? https://airbytehq.slack.com/archives/C01AHCE38KW/p1604449950089400

**Comment by ChristopheDuong** [comment]
Ok I will take a look

**Comment by varunbpatil** [comment]
Hi, just a curious onlooker here. The `oneOf` in the jsonschema seems to be not very nice especially with `storage` marked as required and then the enum taking only one value and also `storage` being repeated multiple times.

How about using the technique described [here](https://json-schema.org/understanding-json-schema/reference/conditionals.html)?

```
"provider": {
  "type": "object",
  "required": ["storage"],
  "properties": {
    "storage": {
      "type": "string",
      "enum": ["HTTPS", "GCS", "S3", "SSH", "SCP", "SFTP", "LOCAL"]
    }
  },
  "allOf": [
    {
      "if": {
        "properties": { "storage": { "const": "GCS" } }
      },
      "then": {
        "properties": { "service_account_json": { "type": "string" } }
      }
    },
    {
      "if": {
        "properties": { "storage": { "const": "S3" } }
      },
      "then": {
        "properties": { 
          "aws_access_key_id": { "type": "string" }, 
          "aws_secret_access_key": { "type": "string", "airbyte_secret": true } 
        }
      }
    }
  ]
}
```

Seems more readable to me and less error prone (like in #962)
