### ISSUE TITLE
🐛 Normalization fails due to ambiguous column name

### ISSUE THREAD

**Issue by darian-heede** [airbytehq/airbyte#8553]
## Environment
- **Airbyte version**:  Latest version
- **OS Version / Instance**: Arch Linux 5.15.6-arch2-1
- **Deployment**: Docker
- **Source Connector and version**: Personio connector, we're building right now (please see [here](https://github.com/airbytehq/airbyte/issues/8333)).
- **Destination Connector and version**: Latest Postgres
- **Severity**: Medium
- **Step where error happened**: Normalization

## Current Behavior
When running normalization on the raw data written to the postgres schema by the write step we get the following dbt error for a specific nested table:
```plain
Database Error in model employees_attributes_cost_centers_value (models/generated/airbyte_tables/personio/employees_attributes_cost_centers_value.sql)
  column reference "value" is ambiguous
  LINE 29: and "value" is not null
               ^
  compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/personio/employees_attributes_cost_centers_value.sql
```

The compiled model experiencing this error is the following:
```sql
with __dbt__cte__employees_attributes_cost_centers_value_ab1 as (

-- SQL model to parse JSON blob stored in a single column and extract into separated field columns as described by the JSON Schema
-- depends_on: "airbyte".personio."employees_attributes_cost_centers"

select
    _airbyte_cost_centers_hashid,
    jsonb_extract_path_text(_airbyte_nested_data, 'type') as "type",
    jsonb_extract_path(_airbyte_nested_data, 'attributes') as "attributes",
    _airbyte_ab_id,
    _airbyte_emitted_at,
    now() as _airbyte_normalized_at
from "airbyte".personio."employees_attributes_cost_centers" as table_alias
-- value at employees/attributes/cost_centers/value
cross join jsonb_array_elements(
        case jsonb_typeof("value")
        when 'array' then "value"
        else '[]' end
    ) as _airbyte_nested_data
where 1 = 1
and "value" is not null
)
```

I can replicate the error when executing the query on the database. The problem is that `table_alias` has a column called `value` and `_airbyte_nested_data` does as well, creating the ambiguity for the where clause `and "value" is not null`. I expect it should be qualified as `and "table_alias"."value" is not null`.

I expect this error to always happen in this situation, i.e. when cross joining the elements of a nested array.

The json schema for the `cost_centers` object is the following:
```json
"cost_centers": {
  "type": "object",
  "properties": {
    "label": {
      "type": "string"
    },
    "value": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "attributes": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "percentage": {
                "type": "integer"
              }
            }
          }
        }
      }
    },
    "type": {
      "type": "string"
    },
    "universal_id": {
      "type": "string"
    }
  },
  "required": [
    "label",
    "type",
    "universal_id",
    "value"
  ]
},
```

## Expected Behavior
The normalization should execute successfully on the affected tables.

## Are you willing to submit a PR?
No

**Comment by alafanechere** [comment]
@ChristopheDuong are you aware of this kind of problem and have a workaround suggestion.

**Comment by ChristopheDuong** [comment]
No, I am not sure why this is happening with a quick look at the catalog/sql.

Comparing to this https://github.com/airbytehq/airbyte/blob/fbe557f2d9cbf8ed4c9c15b363ce28a61a7925ae/airbyte-integrations/bases/base-normalization/integration_tests/normalization_test_output/postgres/test_nested_streams/first_output/airbyte_incremental/test_normalization/nested_stream_with_c___names_partition_data.sql#L26
(note that both "DATA" and "value" are reserved keywords in Postgres)

it sounds to be a similar use case. so I guess we'd need to replicate the same catalog in a test and dig into this.

**Comment by marcosmarxm** [comment]
Postgres has been migrated to Destination v2 using typing-deduplication, so this issue is no longer relevant.
