### ISSUE TITLE
CI Sandbox Rockset increase the number of collections in integration account

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8556]
## Tell us about the problem you're trying to solve
The Integration Test account is limited to 10 collections only, this won't allow us running the tests. We need to upgrade the plan to have more quota creating collections in Rockset.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sbaldwin-rs** [comment]
The max number of collections for the testing organization has been bumped to 50.

**Comment by marcosmarxm** [comment]
thanks @sbaldwin-rs
