### ISSUE TITLE
CI sandbox prod upgrade for Paypal transaction

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8575]
Our current credentials for Paypal Transaction API are using `sandbox = true`. Due to instability of the sandbox API declared in this issue : https://github.com/airbytehq/airbyte/issues/8012, could we have an a Paypal account to use prod (`sandbox = false`). Current CI builds of Paypal Transaction are [failing](https://github.com/airbytehq/airbyte/actions/runs/1544312066)  with the same error declared in the mentionned issue, and when I tried to update our CI `PAYPAL_TRANSACTION_CREDS` with `sandbox = false` we face a 401 error while refreshing token which leads me to the conclusion our current sandbox account is not working with "prod" Paypal.

**Comment by alafanechere** [comment]
Thank you very much @karinakuz !!!

**Comment by alafanechere** [comment]
@karinakuz do you think we could create a transaction on the Paypal Live account, I think it will fix the following CI error:
`AssertionError: All streams should return some records, streams without records: ***'transactions'***`.

**Comment by karinakuz** [comment]
@alafanechere Unfortunately, I can't do any transaction on the Paypal Live account
