### ISSUE TITLE
Diagnosis check: Confirm oauth refresh_token & params validity

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#8595]
## Tell us about the problem you're trying to solve
When a connector using oauth fails, we need to make sure that it's not an error coming from the credentials/refresh_token not being valid anymore

## Describe the solution you’d like
Being able to run a diagnosis check to confirm validity of oauth parameters

**Comment by sherifnada** [comment]
This will be handled by connector ops as part of OAuth work in the future
