### ISSUE TITLE
Validate Airbyte Json Message against the declared catalog

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#8596]
## Tell us about the problem you're trying to solve
When a source emits a record data, we should be able to make sure it validates against the JSON schema or downstream process expecting certain types for example may fail.

## Describe the solution you’d like
When writing a record to the destination, we should be able to validate the record and make sure it follows the specifications of the source connector. (this will not always be caught by acceptance tests because it depends on the content of the source database or API version)

**Comment by girarda** [comment]
@sherifnada we good to close this since this is done by the platform?

There might be a case for doing additional validation from the connector builder or for enforcing TypeTransforms but I think it should be tracked in more specific issues

**Comment by sherifnada** [comment]
yup!
