### ISSUE TITLE
Implement Segment event tracking

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#86]
Here is the Segment workspace we will be using: https://app.segment.com/dataline/home

Here are the specs for the event tracking: 
https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit?usp=sharing

We need Identify, Page and Track events. 

@cgardens

**Comment by cgardens** [comment]
please use the `customerId` returned by `workspaces/get` as the user id for segment.

**Comment by cgardens** [comment]
@Jamakase - as a heads up, i will handle the "User Traits" section and all of the events in the "Track" tab. anything else i haven't mentioned you can still handle on the frontend. lmk if you don't think this division makes sense or if i have missed anything that you feel needs to happen on the backend.
