### ISSUE TITLE
Zendesk Support: use cursor-based pagination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8602]
## Tell us about the problem you're trying to solve
Zendesk [recently announced an improved pagination mechanism using cursors](https://support.zendesk.com/hc/en-us/articles/4408824785946-Announcing-API-rate-limits-for-Offset-based-Pagination) that we should use.

## Describe the solution you’d like
The connector should use cursor based pagination instead of offset based.

**Comment by asyarif93** [comment]
I'll take this issue, I have working implementation for this in ticket metrics.

for a note. this cursor-based pagination have different mechanism compared to existing `IncrementalSortedPageStream`
in `ticket_audits docs`:
> [This endpoint uses a variant of cursor pagination with some differences from cursor pagination used in other endpoints.](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_audits/#pagination)

I think I'll make class for `IncrementalUnortedPageStream`, `IncrementalSortedPageStream` and put existing `IncrementalSortedPageStream` implementation into `TicketAudits`. Wdyt? @sherifnada

**Comment by sherifnada** [comment]
Thanks @asyarif93 ! will take a look soon

@antixar can someone from teh team review the contribution
