### ISSUE TITLE
UI does not tell the truth on connection page

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#8619]
## Tell us about the problem you're trying to solve
in this issue, the user is using special characters in the target namespace/table name:
https://github.com/airbytehq/airbyte/issues/6661#issuecomment-988665278

The UI should tell the user what is really going to happen to their data once sync completes (before It actually runs)
But here, there are differences between what is shown in the UI and what airbyte actually does in reality:
- no namespace is shown in "destination_namespace" (the connection is configured with "mirror from source" but source does not have a namespace, so it should default backt o destination_namespace from destination settings)
- the stream name is not what is really happening

## Describe the solution you’d like
- UI should include the special characters -> `_` conversions when pre-computing destination table names (or namespace)
- In case a source does not give a namespace, the namespace from destination settings should be displayed (with character conversions if appropriate)

**Comment by jrhizor** [comment]
I don't think this is really a frontend issue in isolation. For the stream name logic we should be retrieving that from the backend. Similarly, it would be better if much of the namespace logic was hidden behind an endpoint.

**Comment by ChristopheDuong** [comment]
on this other issue, we're also talking about changing the protocol to add some charset field support from the connector  spec that the platform & UI would have to refer to, to know what is going to be replaced by `_` or not:

https://github.com/airbytehq/airbyte/issues/6661#issuecomment-989200860

**Comment by evantahler** [comment]
cc @edmundito is this still an issue?

**Comment by evantahler** [comment]
Closing because we haven't seen this in a while... we can re-open if that's not the case
