### ISSUE TITLE
🐛 Source Google Analytics to destination BigQuery: various failures

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#8625]
## Environment
- **Airbyte version**:   0.33.5-alpha
- **OS Version / Instance**: Container-Optimized OS from Google
- **Deployment**: Kubernetes
- **Source Connector and version**: Google Analytics 0.1.12
- **Destination Connector and version**: BigQuery 0.5.0
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
So I tried to run 3 times with basic normalization. 
1. failure on the first attempt. second attempt succeeded but no actual data was moved?
[logs-54-0.txt](https://github.com/airbytehq/airbyte/files/7676295/logs-54-0.txt)
[logs-54-1.txt](https://github.com/airbytehq/airbyte/files/7676299/logs-54-1.txt)

2. failure on the first attempt due to json? second attempt was clean
[logs-55-0.txt](https://github.com/airbytehq/airbyte/files/7676311/logs-55-0.txt)
[logs-55-1.txt](https://github.com/airbytehq/airbyte/files/7676313/logs-55-1.txt)

3. same as above
[logs-57-0.txt](https://github.com/airbytehq/airbyte/files/7676340/logs-57-0.txt)
[logs-57-1.txt](https://github.com/airbytehq/airbyte/files/7676330/logs-57-1.txt)
 
## Expected Behavior
success on the first run.

## Logs
logs provided above 

## Steps to Reproduce
1. set-up connectors
2. sync

## Are you willing to submit a PR?
no

**Comment by sherifnada** [comment]
could be due to #8643

**Comment by misteryeo** [comment]
@TSkrebe we'd like to look into this further but suspect #8643 may have fixed it. Is this issue still persisting for you?

**Comment by TSkrebe** [comment]
haven't noticed these issues with the latest version.
