### ISSUE TITLE
🐛 Source Facebook Pages: Test connection failing (nonexisting field: live_encoders)

### ISSUE THREAD

**Issue by leo-pragi** [airbytehq/airbyte#8626]
## Environment
- **Airbyte version**:  example is 0.29.17-alpha
- **OS Version / Instance**: Ubuntu 18.04 EC2
- **Deployment**: EKS
- **Source Connector and version**: Facebook Pages 0.1.5 
- **Severity**: High
- **Step where error happened**: Setup new source

## Current Behavior
Creating Facebook pages source is failing with 400 Client Error in test connection page with 400 Client Error: Bad Request.

## Expected Behavior
Airbyte should be able to test the connection successfully or can throw 401/404. 

## Logs
N/A

## Debug result:
I also looked what’s the problem by making the same API call which resulted in:
```
{
   "error": {
      "message": "(#100) Tried accessing nonexisting field (live_encoders) on node type (Page)",
      "type": "OAuthException",
      "code": 100,
      "fbtrace_id": "AnGU-_FoJD-vjZ68ywqyvti"
   }
}
```

## Steps to Reproduce
1. Create a new facebook pages connection
2. Fill id page_id and access_token (with relevant permission)
3. Click `Test Connection`

## Are you willing to submit a PR?
Yes!

**Comment by alafanechere** [comment]
It looks like our connectors tries to query the `live_encoders` field that is not accessible. Is it due to a FB API update or because of a custom page setup on your side @leo-pragi ?

**Comment by leo-pragi** [comment]
Recently we test this connector with newly created facebook page without any customisation and its failing with that too.

**Comment by alafanechere** [comment]
Ok thanks for the details @leo-pragi, our team added this to an upcoming milestone.
