### ISSUE TITLE
Destination Postgres: Support setting of database role

### ISSUE THREAD

**Issue by darian-heede** [airbytehq/airbyte#8627]
## Tell us about the problem you're trying to solve
The `config.json` for destination-postgres and the normalization takes a username and password. All database objects that are then created by Airbyte are then owned by the username set in the config. In our datawarehouse we use _nologin_ roles for permissions management. This implies that a role needs to be owner of database objects and not a user. As it is right now, we need to add a stage to our pipelines that resets the ownership before further steps can happen (e.g. data provisioning).

## Describe the solution you’d like
I would like to be able to specify a [`database role`](https://www.postgresql.org/docs/8.4/sql-set-role.html) in the destination `config.json` that will be set, before database objects are created. This will have the specified role be owner of any created database objects. I want this to work with the destination-postgres connector as well as the normalization, which also created tables.

## Describe the alternative you’ve considered or used
After the destination-postgres write and the normalization run, we have to transfer the table ownership to a role before any data processing can happen. For this to work, we have an additional job in our pipelines that consumes resources. 

## Are you willing to submit a PR?
No

**Comment by darian-heede** [comment]
Hi, is there any news regarding this issue?

**Comment by darian-heede** [comment]
For the base-normalization enabling this is trivial and I'm willing to submit a PR. For destination-postgres implementing this seems to be more complicated though.

**Comment by marcosmarxm** [comment]
@darian-heede thanks for requesting this. Probably this will impact the Abstract JDBC and this is the reason why is more complicated compared to normalization one.

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.

**Comment by darian-heede** [comment]
Hi @marcosmarxm, this issue is not just related to normalization but mainly about the ability to set the database role for the destination-postgres connector. IMHO it is still a useful feature to have.
