### ISSUE TITLE
String format validation fails irrecoverably in the source connector setup UI

### ISSUE THREAD

**Issue by monai** [airbytehq/airbyte#8629]
## Environment

- **Airbyte version**:  0.33.3-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Linnworks 0.1.3
- **Destination Connector and version**: None
- **Severity**: Normal
- **Step where error happened**: Connector setup

## Current Behavior

Source connector setup UI fails with "Unknown error occurred" when value entered to spec field of `"type": "string", "format": "date-time"` is invalid. Moreover, the browser's back button doesn't work; you have to completely reload the Airbyte UI and start connector set up all over again.

![Screenshot 2021-12-08 at 16 01 55](https://user-images.githubusercontent.com/1473062/145221342-debfa5b0-9b61-4050-a816-cd520e810918.png)

[Some connectors even workaround](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-github/source_github/spec.json#L67) this issue with custom pattern validation despite requiring RFC 3339 formatted date. The format `date-time` has been in JSON Schema since the beginning.

## Expected Behavior

I expect Airbyte UI to show format validation error inline, just like other errors. Moreover, it would be very convenient to autocomplete entered date to full RFC 3339 format, e.g., when a user enters `2021-01-01`, it should automatically complete it to full form `2021-01-01T00:00:00:00+00:00` since it's the actual user intention.

## Logs

```
airbyte-server     | 2021-12-08 13:51:40 ERROR c.n.s.DateTimeValidator(isLegalDateTime):91 - {workspace_app_root=/tmp/workspace/server/logs} - The supplied date/time format type does not match the specification, expected: date-time
airbyte-server     | 2021-12-08 13:51:40 INFO i.a.s.e.KnownExceptionMapper(toResponse):21 - {workspace_app_root=/tmp/workspace/server/logs} - Known exception
airbyte-server     | 2021-12-08 13:51:40 ERROR i.a.s.RequestLogger(filter):93 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.18.0.3 POST 422 /api/v1/sources/create - {"name":"linnworks2","sourceDefinitionId":"e63a6ce8-d61b-438c-b803-49ffaf8a25d3","workspaceId":"efc1b78c-e817-42ab-a615-6dc8cfb29f08","connectionConfiguration":"REDACTED"}
```

## Steps to Reproduce

1. Click create `+ new source`.
2. Select source that has `"type": "string", "format": "date-time"` spec field, e.g., Linnworks.
3. Fill in all required fields.
4. Enter a valid partial date to the date-time field.
5. Click `Set up source`.

## Are you willing to submit a PR?

Maybe.

**Comment by alafanechere** [comment]
Just to add a bit of details here's the specs of the Linnworks connector:

```json
{
  "documentationUrl": "https://docsurl.com",
  "connectionSpecification": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Linnworks Spec",
    "type": "object",
    "required": ["application_id", "application_secret", "token", "start_date"],
    "additionalProperties": false,
    "properties": {
      "application_id": {
        "title": "Application ID",
        "type": "string"
      },
      "application_secret": {
        "title": "Application secret",
        "type": "string",
        "airbyte_secret": true
      },
      "token": {
        "title": "Token",
        "type": "string"
      },
      "start_date": {
        "title": "Start date",
        "type": "string",
        "format": "date-time"
      }
    }
  }
}
```
