### ISSUE TITLE
Publish automatically `strict-encrypt` version of connectors after the normal version

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8634]
## Tell us about the problem you're trying to solve
There are some database connectors with strict-encrypt. The idea is to publish automatically the version of those connectors after publishing the normal version.
1. Have a workflow to publish automatically the connector;
2. Have tests to validate and fail built CI if it's published.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by tuliren** [comment]
Instead of publishing two variants, I think we can get rid of the `strict-encrypt` one completely.

One proposal:
1. Add a cloud environment variable that is specific to the Airbyte cloud deployment.
    - Or reuse an existing one if it exists. 
2. Pass the environment variable to the connector container.
3. When the connector detects such an environment variable, it updates the spec and behave just like the `strict-encrypt` version.

**Comment by davinchia** [comment]
@evantahler we already do this in the [Cloud Webapp](https://github.com/airbytehq/airbyte-cloud/blob/master/cloud-webapp/Dockerfile#L7-L30) to avoid splitting the frontend code between two repos so there is already precedent there. Although this might seem slightly weird on the OSS side, I think it's very slight complexity for a rather clean solution so I like this idea.

**Comment by tuliren** [comment]
## Migration Plan
- [ ] Merge https://github.com/airbytehq/airbyte/pull/13522
- [ ] Publish a new OSS version.
- [ ] Update `CloudConnectorCatalogGenerator` in `airbyte-cloud` once this change has been published in the new version.
- [ ] Replace source-postgres-strict-encrypt with source-postgres.
    - Either by database migration, or manually in the production database.

**Comment by evantahler** [comment]
Closing this, as this quarter we are going to get rid of the Strict Encrypt connectors!
