### ISSUE TITLE
Source Sendgrid: Add legacy marketing campaigns information 

### ISSUE THREAD

**Issue by PVMer** [airbytehq/airbyte#8651]
We need to bring in Legacy Marketing Information from API - GET /categories/stats. 

Currently the Sendgrid connector does not support Legacy Marketing information.

**Comment by marcosmarxm** [comment]
@PVMer I'm closing this because isn't a good idea to add legacy streams. Feel free to request missing streams from current Sendgrid version.

**Comment by GodStar721** [comment]
How can I track any email(state
)
