### ISSUE TITLE
KeyError('window_in_days') in Google Analytics Source Connector

### ISSUE THREAD

**Issue by kirstenhipolito** [airbytehq/airbyte#8655]
## Environment
- **Airbyte version**:  0.32.6-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: Google Analytics 0.1.12
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
I'm trying to set up a new Google Analytics source, but I get `KeyError('window_in_days')`. It seems this is a parameter in connection configuration, but I'm not sure how I can set a value for it on UI.

## Expected Behavior
The source should set up successfully.

## Logs
The failed logs dropdown at the bottom contains one line:

<details>

<summary>LOG</summary> 

```
2021-12-09 09:12:13 INFO TemporalAttemptExecution(get):116 - Executing worker wrapper. Airbyte version: 0.32.6-alpha
```

</details>

Images of the error and the logs are below:

<details>

<summary>Images</summary> 

![image](https://user-images.githubusercontent.com/48355953/145368601-b5912bf0-aa56-40dc-a174-60e95216b99b.png)
![image](https://user-images.githubusercontent.com/48355953/145368616-2e153412-e018-4de5-a5a0-89c4f1ab1fa3.png)

</details>

## Steps to Reproduce
1. In the Source tab, click '+ new source'.
2. Choose source type Google Analytics.
3. Populate the fields. For the Google Analytics credentials, use a service account.
4. Click 'Set up source'.

**Comment by sherifnada** [comment]
@antixar @lazebnyi seems like this is related to the latest change to GA, mind taking a look?
