### ISSUE TITLE
Can We Create HyperTable Using Postgres Connector

### ISSUE THREAD

**Issue by arjunnikhil03** [airbytehq/airbyte#8662]
Hello Team,

I am using a Postgres connector for a destination. The pipeline works properly. My only question is how I can create a hypertable using the Postgres destination connector. I am using TimescaleDB in cluster mode. I want to create a distributed table.

**Comment by marcosmarxm** [comment]
It's not possible TimescaleDB is not supported as a connector at the moment. I'll close the issue
