### ISSUE TITLE
Source Google Ads: Add end_date configuration

### ISSUE THREAD

**Issue by iberchid** [airbytehq/airbyte#8666]
## Tell us about the problem you're trying to solve
I would like to be able to specify and end date up to which the data needs to be fetched.

## Describe the solution you’d like
Add end_date field to spec and allow for setting the value of the date until which the data should be fetched.

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
Thanks @iberchid looks you'd already submitted the code! Amazing.

**Comment by misteryeo** [comment]
@marcosmarxm confirming with you that given the above PR merge, we can close this issue? If so, can you close this issue?
