### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by romvarac** [airbytehq/airbyte#867]
## Expected Behavior
*Tell us what should happen.*

## Current Behavior
*Tell us what happens instead of the expected behavior.*

## Steps to Reproduce
1. [Set up](https://docs.airbyte.io/getting-started-tutorial)
1. Create source (connect to postgres (staging env): connection success)
<img width="263" alt="Screen Shot 2020-11-10 at 10 23 44" src="https://user-images.githubusercontent.com/20069996/98623809-0775bb00-233f-11eb-8058-70ec9631c377.png">
 2. Next step: 
<img width="372" alt="Screen Shot 2020-11-10 at 10 24 47" src="https://user-images.githubusercontent.com/20069996/98623843-19575e00-233f-11eb-9448-37209f7c679d.png">
There is a error:
<img width="1426" alt="Screen Shot 2020-11-10 at 09 56 03" src="https://user-images.githubusercontent.com/20069996/98623864-2411f300-233f-11eb-9c68-5538dd1d018f.png">

## Severity of the bug for you
Very low / Low / Medium / High / Critical

## Additional context
*Environment, version, integration...*

**Comment by sherifnada** [comment]
Hi @romvarac, 

Thanks for filing this issue. We're investigating and will report back soon.

**Comment by cgardens** [comment]
@romvarac - could you provide the logs from docker-compose up process. My guess is something is breaking on the server side, but we need that information to help more. So far we haven't been able to reproduce your issue.

**Comment by romvarac** [comment]
I haven't been able to reproduce my issue, too, maybe something is bypass. Thanks for your help 👍
