### ISSUE TITLE
pytest: plan to reach 95% test coverage for connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8689]
## Tell us about the problem you're trying to solve
This ticket aims to solve the following question: how can we reach 95% test coverage on our connectors? 

## Describe the solution you’d like
A plan for how we can reach 95% test coverage on our connectors. e.g: is it enforced at the pytest level? If so, what's the migration plan for connectors to prevent all builds from suddenly failing? ticket generation etc.

**Comment by keu** [comment]
pytest coverage plugin supports failing of the tests if min coverage is not met, but I don't know how to disable this per connector basis.
