### ISSUE TITLE
Source Github: trial GraphQL API 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8705]
## Tell us about the problem you're trying to solve
same as #8503 but for github

**Comment by lazebnyi** [comment]
Using [Github GraphQL search query](https://docs.github.com/en/graphql/reference/queries#searchresultitemconnection) we can use filtering and get the list of objects (issues, pr and etc.) what we need without losing performance on iterating throw a full list of data.

In `airbytehq/airbyte` we have 4903 issues, using the search query and filter grather than 0 for reactions we get 548 issues which will definitely have not less than 1 reaction.


**Request:**
```
query {
  search(first: 3, type: ISSUE, query: "repo:airbytehq/airbyte is:issue reactions:>0") {
    issueCount
    edges {
      node {
        ... on Issue {
          id
          databaseId
          }
        }
      }
    }
  }
```

**Response:**
```
{
  "data": {
    "search": {
      "issueCount": 548,
      "edges": [
        {
          "node": {
            "id": "I_kwDOEN7yYc5DPtd9",
            "databaseId": 1128191869
          }
        },
        {
          "node": {
            "id": "I_kwDOEN7yYc5DPQNH",
            "databaseId": 1128072007
          }
        },
        {
          "node": {
            "id": "I_kwDOEN7yYc5DNRvN",
            "databaseId": 1127553997
          }
        }
      ]
    }
  }
}
```



For all parents streams (issues, pr and etc.), we can use [GraphQL query](https://docs.github.com/en/graphql/overview/explorer) to get all nested data for other nested streams (comments, labels, milestones and etc.), but we need to change CDK to parse response with high performance. Example for GraphQL request what return all reactions for repo below.

**Request:**
```
query {
  search(first: 3, type: ISSUE, query: "repo:airbytehq/airbyte is:issue reactions:>0") {
    issueCount
    edges {
      node {
        ... on Reactable {
          reactions(first: 2) {
            pageInfo {
              hasNextPage
              endCursor
    	}
            edges {
              node {
                id
                databaseId
                content
                reactable {
                  id
                }
                user {
                  id
                }
                createdAt
              }
            }
          }
        }
      }
    }
  }
}
```

**Response:**
```
{
  "data": {
    "search": {
      "issueCount": 548,
      "edges": [
        {
          "node": {
            "reactions": {
              "pageInfo": {
                "hasNextPage": false,
                "endCursor": "Y3Vyc29yOnYyOpHOCNxkZA=="
              },
              "edges": [
                {
                  "node": {
                    "id": "REA_lAHOEN7yYc5DPtd9zgjcZGQ",
                    "databaseId": 148661348,
                    "content": "THUMBS_UP",
                    "reactable": {
                      "id": "I_kwDOEN7yYc5DPtd9"
                    },
                    "user": {
                      "id": "MDQ6VXNlcjg5NDcyMzgw"
                    },
                    "createdAt": "2022-02-09T08:55:38Z"
                  }
                }
              ]
            }
          }
        },
        …
      ]
    }
  }
}
```

Also more info about migration from REST to GraphQL https://docs.github.com/en/graphql/guides/migrating-from-rest-to-graphql.

**Comment by sherifnada** [comment]
@lazebnyi Some questions:

- is the rate limit for GQL the same as the REST API? How long does it take to sync N records from M streams, many of which are nested?
- What is the performance of a full sync in a large repo if we compare GQL and RESt? 
- Are all resources supported via GQL? 
- Are there any limitations we should know when using GqL? 

The Shopify ticket has some good examples of answering these deeper concerns.

**Comment by lazebnyi** [comment]
@sherifnada thanks for the questions. Some answers are below.
 I hope that help answers your question. If not, let me know😁

| Criteria | GQL | REST |
|------|-----|-----|
| Rate Limit (req/hour) |  [5000](https://docs.github.com/en/graphql/overview/resource-limitations#rate-limit) | [15000](https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps) |
| Speed  (N records from M streams) |  K sec   | between 3*K and 4*K sec  |
| Supported by all resources | No |  Yes |

Migrating from REST to GraphQL represents a significant shift in API logic. As we see from the table GQL can improve the performance of connectors, especially for nested streams. But we have only 8 nested streams in 28 GitHub streams. 

Using GQL API help to query only relevant data using filtering, but only for part of streams. The differences between REST as a style and GraphQL as a specification make it difficult—and often undesirable—to replace REST API calls with GraphQL API queries on a one-to-one basis. For some of the nested streams, we can use GQL, but for full connectors, this brings us more problems than solutions. Also, we should remember about [Resource limitations](https://docs.github.com/en/graphql/overview/resource-limitations) for GQL:

- Node limit
   - Clients must supply a first or last argument on any [connection](https://docs.github.com/en/graphql/guides/introduction-to-graphql#connection).
   - Values of first and last must be within 1-100.
   - Individual calls cannot request more than 500,000 total [nodes](https://docs.github.com/en/graphql/guides/introduction-to-graphql#node).

**Comment by sherifnada** [comment]
Thanks for the helpful details @lazebnyi , closing this issue as it seems the recommendation is that GQL does not present a clear benefit.
