### ISSUE TITLE
CDK: create new singer based connector failed running check command

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8710]
## Current Behavior
[Slack convo](https://airbytehq.slack.com/archives/C01VDDEGL7M/p1639085893191100)
I'm trying to generate a new singer based connector andd having problem running the commands. Start working after changed the import from `airbyte_cdk.entrypoint` to `base_python.entrypoint`.

>Hello. I am having an issue with trying to run a check on a singer source I am attempting to develop by running python main.py check --config secrets/config.json . When attempting to run the command I am getting back the message {"type": "LOG", "log": {"level": "FATAL", "message": "'ConfigContainer' object has no attribute 'items'"}}. I confirmed that the spec is valid and that my config.json is valid json and contains all the required fields. (edited) 

>Hmm, so FWIW it does look like the error is related to launch() from airbyte_cdk.entrypoint . I’m comparing this with a working singer source’s main.py which imports launch() from base_python.entrypoint. When I change the import statement from from airbyte_cdk.entrypoint import launch to from base_python.entrypoint import launch, the config is recognized.

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by franloza** [comment]
I'm not sure if this is a good first issue. I've been reading the code and finding some mismatches between the `Connector` interface and the `SingerSource` class.

The method `configure` in the`Connector` interface requires to return a `Mapping`:
https://github.com/airbytehq/airbyte/blob/c51fb7afe62188c9fd0f05aef4d437228c0b78f3/airbyte-cdk/python/airbyte_cdk/connector.py#L32

However, the implementation of `configure` in the `SingerSource` class returns a `ConfigContainer` object, which does not implement the methods required to be a `Mapping`. The specified return type is also wrong:
https://github.com/airbytehq/airbyte/blob/c51fb7afe62188c9fd0f05aef4d437228c0b78f3/airbyte-cdk/python/airbyte_cdk/sources/singer/source.py#L28-L36

I've tried to get more information about how I could solve this issue but I could not find a good way to solve this issue as I'm lacking context about the `ConfigContainer` class.

Some possible related issues/PRs:
- https://github.com/airbytehq/airbyte/pull/1331
- https://github.com/airbytehq/airbyte/issues/1322

Any idea of what's the best way to solve this issue?

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by alafanechere** [comment]
@aadityasinha-dotcom 

> Can I work on this issue?

Sure!
