### ISSUE TITLE
Accessing source config in transform_function ?

### ISSUE THREAD

**Issue by lizdeika** [airbytehq/airbyte#8711]
Hi,

https://github.com/airbytehq/airbyte/blob/161a1ee7b5c7375f16cffcd8f6d1eb4adc1cb437/airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py#L451-L457

Transform function normalizes source `Date` field that is needed later for slicing.
The problem is that date format in source comes in different formats depending on Amazon marketplace,
for example US `M/D/YY` , UK `D/M/YY`
So I need to map marketplaces to their date formats like:
```
{
  "US": "M/D/YY",
  "UK": "D/M/YY",
}
```
How do I access `self.marketplace_ids` in transform_function as it appears to be static :/ 
or Source config that would contain the selected marketplace_ids?

**Comment by alafanechere** [comment]
Hi @lizdeika I think you could try to use a closure for this case. In drafted a quick code example, let me know what you think.

```python
class MyStream(HttpStream, ABC):
    transformer = TypeTransformer(TransformConfig.DefaultSchemaNormalization | TransformConfig.CustomSchemaNormalization)

    def __init__(self, config_based_date_format):
        self.config_based_date_format = config_based_date_format
        transform_function = self.get_custom_transform()
        self.transformer.registerCustomTransform()

    def get_custom_transform(self):
        def custom_transform_function(original_value, field_schema):
            if original_value and "format" in field_schema and field_schema["format"] == "date":
                transformed_value = pendulum.from_format(original_value, self.config_based_date_format).to_date_string()
                return transformed_value
            return original_value
        return custom_transform_function
 ```

**Comment by lizdeika** [comment]
Thanks @alafanechere ! That did the trick. This could really be usable to have in documentation about custom transform functions: https://docs.airbyte.io/connector-development/cdk-python/schemas#custom-schema-type-transformation

**Comment by alafanechere** [comment]
Glad I could help here. Yes that's a good point. I'll update the doc.
