### ISSUE TITLE
Re-evaluate MySQL year type

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8722]
The returned year value from MySQL can either be a `java.sql.Short` (when `yearIsDateType=false`) or a `java.sql.Date` with the date set to January 1st, at midnight (when `yearIsDateType=true`). Currently, `JsonSchemaPrimitive` does not support integer, but only supports number. Because the number type will be interpreted as a double in many destinations, and it is weird to show a year as a double, we set `yearIsDateType=true` in the JDBC connection string, and parse the returned year value as a string (#7970). The case can be re-evaluated when `JsonSchemaPrimitive` supports integer.

**Comment by girarda** [comment]
Would it make sense to do like Apache Arrow and support dates as primitives? https://arrow.apache.org/docs/python/api/datatypes.html

**Comment by tuliren** [comment]
> Would it make sense to do like Apache Arrow and support dates as primitives?

Yes, we do support dates as primitives in our internal type. However, it looks like the Apache Arrow type system actually does not support the year type.

We probably need to add a new primitive type just for year. According to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Years), it expresses a year with integers (positive integers for AD years, 0 for 1BC, and negative integers for years earlier than 1BC), which seems pretty reasonable.

**Comment by grishick** [comment]
MySQL Source currently returns year as Strings. We could change it to Integer, which will keep connections backwards compatible.
