### ISSUE TITLE
Support deleting Source / Destination definitions

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#8732]
## Tell us about the problem you're trying to solve
* We want to allow a user to remove a connector definition from their Airbyte instance.
* This helps in cases where they have a custom connector that they do not want anymore.
* Helps clear out old connectors that do not exist or are not supported anymore.

## Describe the solution you’d like
* In the UI and API we should expose the ability to delete a connector definition.
* We should leverage the pattern we use when deleting a connector. That pattern is:
    * First disable all of the resources that depend on the thing being deleted
    * Set the `tombstone` field on the resource being deleted to true.

Source/Destination Definition do not currently have a `tombstone` field so we should add it.

## Execution Plan
- [x] Add `tombstone` field to source/destination definitions
- [x] Add endpoint to the api `source_definitions/delete` and `destination_definitions/delete`.
- [x] Unit Tests
- [ ] Create issue for UI team to add a delete button.

**Comment by cgardens** [comment]
Self-assigning until we have Parker in the system so nobody takes this issue.

**Comment by jrhizor** [comment]
If someone deletes a standard connector and then upgrades (which reimports the list), do we expect the connector to still be tombstoned?

**Comment by cgardens** [comment]
haha just found this old issue on this: https://github.com/airbytehq/airbyte/issues/2319. apparently we've been meaning to this for a long time!

**Comment by pmossman** [comment]
@jrhizor I will create an issue for the frontend portion of this issue now that the API changes are released. Do you think we'll want mockups for the delete button / workflow, or is it a small enough change where that won't be necessary?

**Comment by jrhizor** [comment]
No mockups necessary, should just be able to add a red delete button like when deleting source for each definition row.

**Comment by jeff-skoldberg-ct** [comment]
+1 this is needed!

**Comment by samos123** [comment]
Doesn't seem like this feature was ever completed? I just used latest in master and I didn't find any way to delete a custom destination.
