### ISSUE TITLE
 Airbyte-scheduler and Airbyte-worker Max RAM percentage is 25%

### ISSUE THREAD

**Issue by chandininekkantti** [airbytehq/airbyte#8735]
## Environment
- **Airbyte version**:  example is 0.33.10-alpha
- **OS Version / Instance**: Windows 10
- **Deployment**:Docker  deploy env
- **Severity**: Critical
- **Step where error happened**: Deploy 

## Current Behavior
I notice that in Airbyte-scheduler and Airbyte-worker Max RAM percentage is set to 75% for JVM in both containers. However, when I do  _java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"_  ,  I'm only seeing 25% allocated.

## Expected Behavior
I was hoping to see 75% allocated to the JVM

## Logs

![Screenshot (167)](https://user-images.githubusercontent.com/47557006/145735255-4f2697a1-05f8-4dc2-a0c8-abf3c5c0a32f.png)

<img width="1135" alt="2021-12-13" src="https://user-images.githubusercontent.com/47557006/145735278-5a40554f-a8c3-4221-a715-a8d1bf9db168.png">

<details>
<summary>LOG</summary> 

## Steps to Reproduce
1. Deploy 0.33.10-alpha in Windows 10 Docker env
2. Connect to worker/Scheduler containers
3. Check maxRAM allocated

## Are you willing to submit a PR?
No

**Comment by alafanechere** [comment]
Hello @chandininekkantti,
The command you ran is directly referring to java defaults, by default maxRamPercentage is set to 25%. 
We override this default when we are launching our applications with the `-XX:MaxRAMPercentage=75.0` flag.
You can double check the output of your command by changing it a bit: 
`java  -XX:MaxRAMPercentage=75.0 -XX:+PrintFlagsFinal -version  | grep -Ei 'maxheapsize|maxram'` 

If you want to be 100% sure that we are allowing 75% of ram usage you can install `ps aux` in the container (apt-get update && apt-get install -y procps) and run `ps aux` command which will show you the command with which the application was started, something like `/usr/local/openjdk-17/bin/java -XX:MaxRAMPercentage=75.0 -classpath /app/airbyte-workers-0.33.11-alpha/lib/io.airbyte-airbyte-workers-0.33.11-alpha.jar:/app/airbyte-workers-0.33.11-alpha/lib/io.airbyte-airbyte-api-0.33.11-al`. 

Do you encounter memory related problems that led you to check this memory configuration?

**Comment by chandininekkantti** [comment]
Thanks for clarifying. 

Yes, we have noticed few memory related problems when syncing large tables (>200M rows and > 100GB).

**Comment by alafanechere** [comment]
@chandininekkantti I'd suggest you to increase your Airbyte instance memory and increase `JOB_POD_MAIN_CONTAINER_MEMORY_LIMIT` if needed. By default a docker container is using a maximum of 25% of the available memory on the host.

**Comment by chandininekkantti** [comment]
> increase your Airbyte instance memory and increase JOB_POD_MAIN_CONTAINER_MEMORY_LIMIT
- May I request to guide me on how to increase Airbyte instance memory and JOB_POD_MAIN_CONTAINER_MEMORY_LIMIT ? I define in Airbyte server Docker env variables ? 

> By default a docker container is using a maximum of 25% of the available memory on the host.
- Sorry, I should have mentioned, my host RAM is 32GB and seems by default latest Docker for Windows on Windows 10 is using 75% (24.99GB) or may be its 25GB instead ?

**Comment by alafanechere** [comment]
`JOB_POD_MAIN_CONTAINER_MEMORY_LIMIT` is an environment variable you can set in the `.env` file that is used by our `docker-compose`.
You could set this to `JOB_POD_MAIN_CONTAINER_MEMORY_LIMIT=25g` to allow the job container to use up to 25gb of RAM.

The memory allocation you give to the docker engine really depends on your context, you can change memory given to docker in the docker settings.

**Comment by chandininekkantti** [comment]
I think my query is answered, we can close this if you wish.
