### ISSUE TITLE
Implement sorting for Sources & Destinations

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#8754]
## Tell us about the problem you're trying to solve
For workspaces with more than a handful of sources or destinations, it's difficult to manage in the current UI. 

## Describe the solution you’d like
The columns within the Sources and Destinations UI should support sorting by ascending or descending order similar to what exists today in the Connections UI. 

Specifically, the `name`, `connector`, `destination` / `source` columns should be able to be sorted. 

## Describe the alternative you’ve considered or used
Using the browser's native find functionality to manually search for sources or destinations in the list.

## Additional context
What exists today in Connections:
![Airbyte  Connections 2021-12-13 at 10 36 42 AM](https://user-images.githubusercontent.com/16851149/145869022-1b72ce26-a479-4c4f-9849-18ad982ae0cb.jpg)

What's missing from Sources / Destinations:
![Airbyte  Sources 2021-12-13 at 10 37 11 AM](https://user-images.githubusercontent.com/16851149/145869088-33464b64-f60f-4651-957b-629806d80f0c.jpg)

**Comment by cgardens** [comment]
Note: this is client-side only for the MVP.

**Comment by cgardens** [comment]
@harshithmullapudi would you be able to take a look at this issue next week?

**Comment by harshithmullapudi** [comment]
Yeah I can take a look at this

**Comment by harshithmullapudi** [comment]
@cgardens made a PR for the feature

**Comment by harshithmullapudi** [comment]
@misteryeo here on the sources page if the source has multiple destinations how will the sorting be handled?

**Comment by misteryeo** [comment]
@harshithmullapudi We sort first by the Source Name alphabetically and then by the Destination Name alphabetically.

**Comment by harshithmullapudi** [comment]
![Screenshot 2022-04-13 at 3 24 21 PM](https://user-images.githubusercontent.com/17528887/163153017-cd5bbe83-e508-4df9-a0f5-2b9924eaf48c.png)

@misteryeo here for the destinations column you have 2 destinations how do you want me to handle the sorting? I am bit not clear here

**Comment by misteryeo** [comment]
As discussed, we should just sort NAme, Connector and Last Sync for both Source and Destination views.
