### ISSUE TITLE
🐛  Broken HelmCharts v0.33.11

### ISSUE THREAD

**Issue by mohamagdy** [airbytehq/airbyte#8783]
## Environment
- **Airbyte version**:  example is 0.33.11-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: HelmCharts
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Critical
- **Step where error happened**: During the deployment and after the deployment when running a connector

## Current Behavior
1. While deploying I got 

```shell
Error: UPGRADE FAILED: template: airbyte/charts/minio/templates/NOTES.txt:86:4: executing "airbyte/charts/minio/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $requiredMinioPasswordErrors) "context" $)>: error calling include: template: airbyte/charts/common/templates/_errors.tpl:21:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail:
--
13-Dec-2021 23:20:47 | PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
13-Dec-2021 23:20:47 | Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
13-Dec-2021 23:20:47 | Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
13-Dec-2021 23:20:47 |  
13-Dec-2021 23:20:47 | 'accessKey.password' must not be empty, please add '--set accessKey.password=$ACCESS_KEY' to the command. To get the current value:
13-Dec-2021 23:20:47 |  
13-Dec-2021 23:20:47 | export ACCESS_KEY=$(kubectl get secret --namespace "data" airbyte-minio -o jsonpath="{.data.access-key}" \| base64 --decode)
13-Dec-2021 23:20:47 |  
13-Dec-2021 23:20:47 | 'secretKey.password' must not be empty, please add '--set secretKey.password=$SECRET_KEY' to the command. To get the current value:
13-Dec-2021 23:20:47 |  
13-Dec-2021 23:20:47 | export SECRET_KEY=$(kubectl get secret --namespace "data" airbyte-minio -o jsonpath="{.data.secret-key}" \| base64 --decode)
13-Dec-2021 23:20:47 |  
13-Dec-2021 23:20:47 | Failed deploying Helm Chart!

```
2. After fixing (1), I got 
```shell021-12-13 22:57:58 INFO i.a.s.RequestLogger(filter):95 - {cloud_workspace_app_root=/workspace/server/logs} - REQ 10.30.33.154 GET 200 /api/v1/health
======= service endpoint: http://airbyte-minio:%!s(int=9000)
``` 
when running a connectorwhen running a connector

## Expected Behavior
The deployment and running a connector should be error free after deploying to Kubernetes with HelmCharts.

## Are you willing to submit a PR?
Yes

**Comment by alafanechere** [comment]
Hi @mohamagdy could you be more specific about the error you encounter. I'm not seeing a complete error in your

>  "After fixing (1) I got" 
>```
> ======= service endpoint: http://airbyte-minio:%!s(int=9000)
>``` when running a connector

**Comment by mohamagdy** [comment]
Hi @alafanechere. Sorry if the error was not clear but it says the MinIO endpoint is `http://airbyte-minio:%!s(int=9000)` which is obviously not correct as it tried to parse the port `9000` as a string in the `printf`. I don't have access to the failing logs anymore now, but the rest error logs were just `connection refused` and the only clear log related to the issue was:

```shell
======= service endpoint: http://airbyte-minio:%!s(int=9000)
```

This is not related to #8805

**Comment by vnourdin** [comment]
Did your PR #8784 fixed this ?
I added [a comment](https://github.com/airbytehq/airbyte/pull/8784/files#r770349602), we can discuss here if you prefer

**Comment by mohamagdy** [comment]
Yes #8784 should solve it. Closing this issue.
