### ISSUE TITLE
Destination MSSQL: JDBC connection with advanced params

### ISSUE THREAD

**Issue by lfzuluagah** [airbytehq/airbyte#8785]
Our customer has an on-prem database in SQLServer with some additional parameters as domain and Integrated Security, in the normal JDBC connectors those parameters are added in an additional parameters string to concatenate with the other parameters

ex
jdbc:jtds:sqlserver://host:port/databasename;domain=mydoman;Integrated Security=true

## Describe the solution you’d like
Possibility to add additional parameters in source or destination connections.

it is a blocker to move to airbyte as a data loader tool, analyzing other tools regards to this blocker

thanks for your help in advance

**Comment by lfzuluagah** [comment]
@alafanechere  what happens if I need to use it as a destination and need the same additional params

**Comment by alafanechere** [comment]
@lfzuluagah I changed the title to make it clear it also involves destinations. I guess it could be fixed in a PR for both.

**Comment by lfzuluagah** [comment]
> @lfzuluagah I changed the title to make it clear it also involves destinations. I guess it could be fixed in a PR for both.

thank you, do you know what is the possible ETA for this PR?

**Comment by tuliren** [comment]
Postgres also does not allow extra JDBC params. We should add this feature to both Postgres & SQL Server.

Given that the holidays are coming, the ETA is probably mid January 2022.

**Comment by lfzuluagah** [comment]
Hi, happy new year, any advance on this PR?

**Comment by noahkawasakigoogle** [comment]
This is another issue that could be solved by this: https://github.com/airbytehq/airbyte/issues/9467

I think the title should be something like "Support Additional Parameters input for JDBC based Sources/Destinations". A lot of customer deployments will need to set additional params to connect to their databases successfully and it would be infeasible for Airbyte to have to add custom UI inputs for every possible value.

**Comment by tuliren** [comment]
> Hi, happy new year, any advance on this PR?

Unfortunately our team does not have enough bandwidth to work on this. It is in the backlog, but has not been prioritized yet. Currently it's hard to provide an ETA.

**Comment by tuliren** [comment]
> This is another issue that could be solved by this: #9467
> 
> I think the title should be something like "Support Additional Parameters input for JDBC based Sources/Destinations". A lot of customer deployments will need to set additional params to connect to their databases successfully and it would be infeasible for Airbyte to have to add custom UI inputs for every possible value.

Good point. I created an epic issue for aggregation: https://github.com/airbytehq/airbyte/issues/9501

**Comment by lfzuluagah** [comment]
@alafanechere  @tuliren  any advance on this improvement??

thanks for your help in advance!!!

**Comment by noahkawasakigoogle** [comment]
What database specifically are you asking about @lfzuluagah?

**Comment by sashaNeshcheret** [comment]
Seems it is already resolved by [pr](https://github.com/airbytehq/airbyte/pull/11010) and can be closed as duplicate

**Comment by luke-oa** [comment]
Is this actually possible now? jTDS requires a change to the URL itself, not just params appended to the URL string. As far as I can tell it [looks as though the base URL string](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java#L151) is static and that there's still no way to change it to `jdbc:jtds:sqlserver:`
