### ISSUE TITLE
CI Sandbox account for Qualaroo

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#8800]
## Tell us about the problem you're trying to solve
Need Qualaroo credentials to test communty contribution https://github.com/airbytehq/airbyte/pull/8623

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by karinakuz** [comment]
Account with the data is created **(15-day free trial)** . Credentials are added to LastPass with the name 'Qualaroo
'. Tested API for:
- All surveys https://api.qualaroo.com/api/v1/nudges/
- Responses for a survey https://api.qualaroo.com/api/v1/nudges/222042/responses
