### ISSUE TITLE
Keyword search should be enabled for existing source/destination dropdown 

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#8802]
## Tell us about the problem you're trying to solve
Currently, I have to scroll through the list of my existing sources or destinations to manually find the one I want to choose.

## Describe the solution you’d like
The text box should allow me to type the first few letters of my existing source or destination name to dynamically filter for what appears in the dropdown list so that I don't have to scroll through to find my desired source or destination.

## Describe the alternative you’ve considered or used
Manually look through for the one I want.

## Additional context
![Airbyte  New connection 2021-12-14 at 4 57 02 PM](https://user-images.githubusercontent.com/16851149/146103220-65e61da9-ec85-4d33-afd9-458700b1aa14.jpg)

**Comment by andyjih** [comment]
Closing this issue as fixed.
