### ISSUE TITLE
🐛 Source stripe: events stream error parsing JSON

### ISSUE THREAD

**Issue by jagannathsrs** [airbytehq/airbyte#8803]
## Environment
- **Airbyte version**: 0.33.12-alpha
- **OS Version / Instance**: Amazon Linux 2
- **Deployment**: Kubernetes
- **Source Connector and version**: Stripe 0.1.23 
- **Destination Connector and version**: Snowflake 0.3.20 
- **Severity**: High
- **Step where error happened**: Sync Job

## Current Behavior
Events stream from the Strip connector fails with the following error while normalization:
```
normalization - 2021-12-15 01:55:22 INFO LineGobbler(voidCall):82 - 01:55:22 | 1 of 2 START table model STRIPE_EVENTS.EVENTS................................................................ [RUN]
normalization - 2021-12-15 01:55:24 INFO LineGobbler(voidCall):82 - 01:55:24 | 1 of 2 OK created table model STRIPE_EVENTS.EVENTS........................................................... [SUCCESS 1 in 1.73s]
normalization - 2021-12-15 01:55:24 INFO LineGobbler(voidCall):82 - 01:55:24 | 2 of 2 START table model STRIPE_EVENTS.EVENTS_REQUEST........................................................ [RUN]
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | 2 of 2 ERROR creating table model STRIPE_EVENTS.EVENTS_REQUEST............................................... [ERROR in 1.37s]
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 01:55:25 | Finished running 2 table models in 4.83s.
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Completed with 1 error and 0 warnings:
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Database Error in model EVENTS_REQUEST (models/generated/airbyte_tables/STRIPE_EVENTS/EVENTS_REQUEST.sql)
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 -   100069 (22P02): Error parsing JSON: unknown keyword "req_OfvdWqHxblArvk", pos 19
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/STRIPE_EVENTS/EVENTS_REQUEST.sql
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - 
normalization - 2021-12-15 01:55:25 INFO LineGobbler(voidCall):82 - Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
2021-12-15 01:55:27 INFO KubePodProcess(getReturnCode):591 - Exit code for pod normalization-sync-14397-2-krhgu is 1
```
## Expected Behavior
Events stream should be synced without errors

**Comment by grubberr** [comment]
@jagannathsrs 
Can you please help to debug this problem? It's not easy to reproduce on our side.

If it is possible please run the new sync again and spot the correct `/data` directory for your sync in logs.
Usually, this directory looks like `/data/2/0`

You can read more about this here: 
https://docs.airbyte.io/operator-guides/browsing-output-logs#understanding-the-docker-run-commands

After you found your data directory you can archive it and send to us for investigation 
for example, using such command:

```
rm -rf airbyte_data.tar.gz
docker run -ti --rm -v airbyte_workspace:/data -v `pwd`:/mnt ubuntu tar cfz /mnt/airbyte_data.tar.gz --exclude=*config.json -C /data/2/0 .
ls airbyte_data.tar.gz
airbyte_data.tar.gz
```

PLEASE KEEP YOUR ATTENTION !!!
I have added exclude option for tar `--exclude=*config.json` to exclude config(s) with your credentials from the resulting archive, feel free to exclude additional files from the archive if needed. I am mostly interested in SQL files generated by `dbt` tool.

**Comment by jagannathsrs** [comment]
[logs-33-2.txt](https://github.com/airbytehq/airbyte/files/7749122/logs-33-2.txt)

**Comment by jagannathsrs** [comment]
[airbyte_data.zip](https://github.com/airbytehq/airbyte/files/7749247/airbyte_data.zip)

**Comment by grubberr** [comment]
Thank you for the sent archive it really helped to debug the problem.
It looks like for some reason Stripe API produces a result which we do not expect:
for objects in `events` stream we expect:

```
{
  ...
  "request": {
    "id": ...,
    "idempotency_key": ...
  }
  ...
}
```

But according to snowflake error message in your logs:
`Error parsing JSON: unknown keyword "req_OfvdWqHxblArvk", pos 19`
it's structure is  just `type: string` ( not `type: object` )

```
{
  ...
  "request": "req_OfvdWqHxblArvk"
  ...
}
```

But I want to prove it to finally fix the problem!

Can you please sync your data again but without normalization?

<img width="749" alt="Screenshot 2021-12-20 at 23 12 16" src="https://user-images.githubusercontent.com/195743/146888483-790c40b3-9020-4001-b867-5eb15a9056fe.png">

Probably you would need to re-setup your connection (or create another one). You can also sync only `events` stream to make things faster. It has to successfully sync your data to Snowflake.

After that in Snowflake Worksheets do some SQL queries debug stored raw objects:

```
SELECT get_path(parse_json(_AIRBYTE_DATA), 'request') 
  FROM "ANALYTICS"."DBT"."_AIRBYTE_RAW_EVENTS" 
 WHERE typeof(get_path(parse_json(_AIRBYTE_DATA), 'request')) = 'VARCHAR';

SELECT get_path(parse_json(_AIRBYTE_DATA), 'request') 
  FROM "ANALYTICS"."DBT"."_AIRBYTE_RAW_EVENTS" 
 WHERE typeof(get_path(parse_json(_AIRBYTE_DATA), 'request')) = 'OBJECT';
```

(update `"ANALYTICS"."DBT"."_AIRBYTE_RAW_EVENTS"`  to your database.schema path )

Please send your results.

**Comment by jagannathsrs** [comment]
Result of `VARCHAR`

```
"req_OfvdWqHxblArvk"
"req_OfvdWqHxblArvk"
"req_OfvdWqHxblArvk"
"req_OfvdWqHxblArvk"
"req_OfvdWqHxblArvk"
```

Result of 'OBJECT'

None

[_AIRBYTE_RAW_STRIPE_EVENTS__202112211902.csv](https://github.com/airbytehq/airbyte/files/7759670/_AIRBYTE_RAW_STRIPE_EVENTS__202112211902.csv)
