### ISSUE TITLE
🐛 Source Zendesk chat: created_at field parsing error in Bans stream

### ISSUE THREAD

**Issue by bruno-nirello** [airbytehq/airbyte#8819]
## Environment
Is this your first time deploying Airbyte: No
**OS Version** / Instance: Ubuntu 20.04
**Machine type** e2-standard-8 ( 8 CPU )
**Memory / Disk:** 32Gb / 100 GB ssd
**Deployment**: Docker
**Airbyte Version:** 0.33.9-alpha
**Source name/version:** airbyte/source-zendesk-chat:0.1.5
**Destination name/version:** airbyte/destination-bigquery:0.5.0
**Severity**: medium
**Step where error happened**: Sync job 

## Current Behavior
Pendulum parsing the date column `created_at` return `TypeError: expected string or bytes-like object`

## Expected Behavior
Parse the date correctly

## logs
[logs-18-2.txt](https://github.com/airbytehq/airbyte/files/7721873/logs-18-2.txt)

## Steps to Reproduce
1. Sync every table without the big ones `agent_timeline` and `triggers`
2. Try to sync start date = "2021-12-14T00:00:00Z

## Are you willing to submit a PR?
Yes

**Comment by alafanechere** [comment]
It looks like the `created_at` fields returned by the API on the `Bans` stream cannot be parsed by pendulum. This bug might occur because the `created_at` field is optional according to the [API doc.](https://developer.zendesk.com/api-reference/live-chat/chat-api/bans/#list-bans).
