### ISSUE TITLE
Copy issues to Connectors Roadmap

### ISSUE THREAD

**Issue by oustynova** [airbytehq/airbyte#8841]
Please copy all the issues with label area/connectors from issues https://github.com/airbytehq/airbyte/issues to Master Backlog https://github.com/orgs/airbytehq/projects/1/views/1
Also, issues **from GL Python** should be copied to https://github.com/orgs/airbytehq/projects/1/views/6?layout=board with relevant statuses distribution:
Done => Done
In Review (Airbyte) => Airbyte Review
In Review (internal) => Internal Review
Implementation in progress => Implementation in progress
On hold => On hold 
Ready for implementation (prioritized) => Ready for implementation
Backlog (scoped) => Ready for implementation
Prioritized for scoping => Ready for implementation
Backlog (unscoped) => Need scoping
Backlog => Need scoping

issues **from GL Java** should be copied to https://github.com/orgs/airbytehq/projects/1/views/7 with relevant statuses distribution:
Done => Done
In Review (Airbyte) => Airbyte Review
In Review (internal) => Internal Review
Implementation in progress => Implementation in progress
On hold => On hold 
Ready for implementation (prioritized) => Ready for implementation
Backlog (scoped) => Ready for implementation
Prioritized for scoping => Ready for implementation
Backlog (unscoped) => Need scoping
Backlog => Need scoping

**Comment by oustynova** [comment]
And also
opened issues from https://github.com/airbytehq/oncall/issues
should be copied to https://github.com/orgs/airbytehq/projects/1/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%5D&filterQuery=
Master Backlog

**Comment by lazebnyi** [comment]
Action for adding new issue merged ([PR](https://github.com/airbytehq/oncall/pull/101)). Old issue from oncall repo, GL Python and GL Java linked to new Connectors Roadmap by team and statuses.
