### ISSUE TITLE
Deprecate the authentication type "API Key" from the cloud HubSpot source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#8846]
## Tell us about the problem you're trying to solve
The requirement from HubSpot for the public apps is to have OAuth only authentication method.

## Describe the solution you’d like
Deprecate the `API Key` authentication option from the cloud `source-hubspot` connector.
The cloud connector should have only OAuth2.0 authentication, but for the localhost the auth stays the same: OAuth and API Key.

**Comment by igrankova** [comment]
As far as the OAuth authentication method is not yet implemented for the Quotes stream from the HubSpot side, we need to postpone this issue until it is implemented.

**Comment by lazebnyi** [comment]
Fixed in https://app.zenhub.com/workspaces/python-connectors-6262f8b593bb82001df56c65/issues/gh/airbytehq/airbyte/18484
