### ISSUE TITLE
Migration step for 0.31.0-alpha fails

### ISSUE THREAD

**Issue by jeroenlanckmans** [airbytehq/airbyte#8847]
## Environment
- **Airbyte version**:  0.30.23-alpha
- **OS Version / Instance**: Debian 10 gcp
- **Deployment**:  Docker
- **Severity**: High
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
Migration from 0.30.23-alpha to 0.32.0-alpha-patch-1 fails on migration steps for 0.31.0-alpha
Following error is printed:
> Caused by: com.fasterxml.jackson.core.JsonParseException: Expected a field name (Scalar value in YAML), got this instead: <org.yaml.snakeyaml.events.MappingStartEvent(anchor=null, tag=null, implicit=true)>
 at [Source: (sun.nio.ch.ChannelInputStream); line: 48912, column: 15]

## Expected Behavior
Migration should not fail

## Logs
[server.log](https://github.com/airbytehq/airbyte/files/7728788/server.log)

## Steps to Reproduce
Run the upgrade

## Are you willing to submit a PR?
No

**Comment by alafanechere** [comment]
Hi @jeroenlanckmans could you describe the step you took for upgrading:
Did you follow this [guide](https://docs.airbyte.io/operator-guides/upgrading-airbyte#upgrading-on-docker)? Mainly running `docker-compose down` before upgrade?

**Comment by jeroenlanckmans** [comment]
Yes, I followed that guide, ran docker-compose down, updated the .env and compose file and then tried to bring it back up.

**Comment by jeroenlanckmans** [comment]
found the issue, seems a connector configuration for a google sheet contained a `:\n` sequence which caused issues during the parsing. Updating the configuration fixed this
