### ISSUE TITLE
publish our own temporalio/auto-setup:1.13.0 docker image for both architectures

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#8849]
`airbyte-temporal` should extend an image that is published with both architectures. We can retag the Intel-compatible `temporalio/auto-setup:1.13.0` image as `airbyte/temporal-auto-setup:1.13.0` and build our own for arm using the script in the docs.

**Comment by pmossman** [comment]
`airbyte/temporal-auto-setup:1.13.0` with both architectures can be found here: https://hub.docker.com/r/airbyte/temporal-auto-setup/tags

Steps taken:
1. Tag `temporalio/auto-setup:1.13.0` as `airbyte/temporal-auto-setup:1.13.0-amd64`
2. Modify `build-temporal.sh` locally to name and tag the image as `airbyte/temporal-auto-setup:1.13.0-arm64`, then run it.
3. `docker login` as `airbytebot`
4. `docker push airbyte/temporal-auto-setup:1.13.0-amd64`
5. `docker push airbyte/temporal-auto-setup:1.13.0-arm64` 
6. Create a new manifest list with both architectures:
```
❯ docker manifest create airbyte/temporal-auto-setup:1.13.0 \
--amend airbyte/temporal-auto-setup:1.13.0-amd64 \
--amend airbyte/temporal-auto-setup:1.13.0-arm64
```
7. Push the new manifest:
```
❯ docker manifest push airbyte/temporal-auto-setup:1.13.0
```

**Comment by jrhizor** [comment]
Can we also update https://github.com/airbytehq/airbyte/blob/master/airbyte-temporal/Dockerfile#L2 to point at that image?

**Comment by pmossman** [comment]
Yep, I have a branch with that change + some README instructions for version updates, will have a PR up for that soon!
