### ISSUE TITLE
Airbyte 0.34.0-alpha won't start locally 

### ISSUE THREAD

**Issue by tovbinm** [airbytehq/airbyte#8852]
## Environment
- **Airbyte version**:  0.34.0-alpha
- **OS Version / Instance**: MacOS
- **Deployment**: Docker
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Severity**: High
- **Step where error happened**: Start Airbyte

## Current Behavior
I pulled the latest master branch (commit [`3a690296`](https://github.com/airbytehq/airbyte/commit/3a6902963d2014f0bfa451dc9e30d1487eacc08b)) and ran `docker-compose up`. But `airbyte-scheduler` is waiting for Flyway to apply migrations, which do not pass.

## Expected Behavior
All Airbyte service start up correctly.

## Logs
```
airbyte-scheduler   | 2021-12-16 17:47:00 INFO i.a.s.a.SchedulerApp(waitForServer):200 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Waiting for server to become available...
airbyte-server      | 2021-12-16 17:47:02 INFO o.f.c.i.l.s.Slf4jLog(info):49 - {workspace_app_root=/tmp/workspace/server/logs} - Flyway Community Edition 7.14.0 by Redgate
airbyte-scheduler   | 2021-12-16 17:47:02 INFO i.a.s.a.SchedulerApp(waitForServer):200 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Waiting for server to become available...
airbyte-server      | 2021-12-16 17:47:04 INFO o.f.c.i.l.s.Slf4jLog(info):49 - {workspace_app_root=/tmp/workspace/server/logs} - Flyway Community Edition 7.14.0 by Redgate
airbyte-scheduler   | 2021-12-16 17:47:04 INFO i.a.s.a.SchedulerApp(waitForServer):200 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Waiting for server to become available...

//..... some time later

airbyte-server      | 2021-12-16 17:48:25 INFO o.f.c.i.l.s.Slf4jLog(info):49 - {workspace_app_root=/tmp/workspace/server/logs} - Flyway Community Edition 7.14.0 by Redgate
airbyte-server      | Exception in thread "main" java.lang.RuntimeException: Timeout while waiting for database to fulfill minimum flyway migration version..
airbyte-server      | 	at io.airbyte.db.instance.MinimumFlywayMigrationVersionCheck.assertMigrations(MinimumFlywayMigrationVersionCheck.java:63)
airbyte-server      | 	at io.airbyte.server.ServerApp.assertDatabasesReady(ServerApp.java:119)
airbyte-server      | 	at io.airbyte.server.ServerApp.getServer(ServerApp.java:143)
airbyte-server      | 	at io.airbyte.server.ServerApp.main(ServerApp.java:201)
airbyte-server exited with code 1
```

## Steps to Reproduce
1. Pull the latest master branch 
2. run `docker-compose up`

**Comment by marcosmarxm** [comment]
@tovbinm this is a new instance or did you migrate from a previous version?

**Comment by marcosmarxm** [comment]
I'm checking a new deployment to identify the issue.

**Comment by marcosmarxm** [comment]
Deploying a new instance doesn't reproduce the problem; @tovbinm what version are you before upgrading?

**Comment by marcosmarxm** [comment]
I spin up a `0.32.11-alpha` and migrate to `0.34.0-alpha` and was able to migrate without problems. @tovbinm waiting for your return. If any other user has problem with this we can raise to critical.

**Comment by tovbinm** [comment]
I was on `0.33.8-alpha` when I tried running `0.34.0-alpha`.

Just now I tried deleting all the Airbyte containers and volumes and to straight to `0.34.0-alpha`. It did start just fine.
