### ISSUE TITLE
DB Sources: only show a table can sync incrementally if at least one column can be used as a cursor field

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8858]
## Current Behavior
To sync a table incrementally from a DB, it must have a `comparable` column that can be used as a cursor. However, if no such column exists (e.g: all columns are `UUID`s) then that table fundamentally cannot be synced incrementally without using CDC. Today, however, it is allowed to choose _any_ column as a cursor even if it doesn't make sense. See [this issue](https://github.com/airbytehq/airbyte/issues/8857) for the correct longer term solution (exposing a notion of valid cursor fields)

valid cursor fields are listed [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-db/lib/src/main/java/io/airbyte/db/jdbc/JdbcSourceOperations.java#L70) for jdbc sources

Example issue which prompted this: https://github.com/airbytehq/oncall/issues/63

## Expected Behavior
DB sources should first verify if a table has `Comparable` fields before declaring it can be synced incrementally and if not, only declare `full_refresh` as a valid sync mode for that table.

**Comment by alexandr-shegeda** [comment]
Assigned to @mkhokh-33 to proceed with the scoping

**Comment by mkhokh-33** [comment]
@sherifnada , @alexandr-shegeda  I've created scoping document for this with possible solutions - https://docs.google.com/document/d/1nUsuYdpHiexRoU-138h-TCGzwFqnkfm8-Q2AQsO8MOM/edit.
Could you please have a look.

**Comment by grishick** [comment]
@mkhokh-33 as discussed in the document, lets implement Proposal A before we release Postgres Source GA. The long term solution (proposal B and [https://github.com/airbytehq/airbyte/issues/8857](https://github.com/airbytehq/airbyte/issues/8857) can be done in later.
