### ISSUE TITLE
More robust data type & schema permutations testing in Destination Acceptance Tests

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#8862]
## Tell us about the problem you're trying to solve
DAT provides some good guarantees that a destination works as intended. However, it does not do a thorough verification that any data type expressable via JsonSchema can be written to a destination. For example, we've had some issues recently related to data types and schema declarations in JsonSchema: 

1. https://github.com/airbytehq/airbyte/issues/7939 valid json schema declaration which failed in destination s3
2. https://github.com/airbytehq/airbyte/pull/7288 valid json schema declaration which failed in destination s3
3. https://github.com/airbytehq/airbyte/issues/6871 valid json schema declaration which failed in destination s3

## Describe the solution you’d like
I would like to test all possible combinations of valid json schema declarations in DAT so that we can proactively verify that destinations can handle data coming from sources, rather than play whack-a-mole.

**Comment by sherifnada** [comment]
relevant: https://docs.airbyte.io/understanding-airbyte/json-avro-conversion#untyped-array
example of something not currently covered in the type system: https://github.com/airbytehq/airbyte/issues/8280

potential steps: 
1. defining the subset of JSONSchema that all destinations should be able to support
2. coding it into DAT

**Comment by edgao** [comment]
self notes:
* normalization supported types https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_catalog/utils.py

**Comment by sherifnada** [comment]
goals for this week: 
- wrap up design
- create project plan

**Comment by sherifnada** [comment]
tech spec was created, epic here: https://github.com/airbytehq/airbyte/issues/9441
