### ISSUE TITLE
Prevent slow or failing discover calls for databases

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8864]
Currently when setting up a JDBC database connection, users can specify which database to read from, but not about the schemas. The `discover` method tries to get a catalog including all the schemas. If a schema contains lots of tables and columns, even if that schema is not what we want to sync from, it will slow down the `discover` call, or even fail it.

We need to have a way to prevent this:
- Ideally, the set up page can guide users through this process. For example, it first retrieves the schemas, let users select which schema to sync, and then retrieves only the tables under the chosen schemas. This approach requires lots of changes.
- As a quick fix, we can add a new parameter to allow users to specify which schemas to read.

**Comment by evantahler** [comment]
Checking if this is still an active problem
