### ISSUE TITLE
🐛 Source S3 (CSV):  invalid UTF8 data

### ISSUE THREAD

**Issue by lolrenx** [airbytehq/airbyte#8867]
## Environment
- **Airbyte version**:  0.34.1-alpha
- **OS Version / Instance**:  AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: S3 0.1.7
- **Destination Connector and version**: 0.3.17
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Normalization job throws error 

## Expected Behavior
Sync successful

## Logs
[logs-187-1.txt](https://github.com/airbytehq/airbyte/files/7734288/logs-187-1.txt)
[logs-187-2.txt](https://github.com/airbytehq/airbyte/files/7734289/logs-187-2.txt)

<details>
<summary>LOG</summary> 

```
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 - Completed with 1 error and 0 warnings:
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 - 
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 - Database Error in model qr_unfiltered (models/generated/airbyte_incremental/public/qr_unfiltered.sql)
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -   syntax error at or near "'", "_airbyte_ab_id", "_airbyte_emitted_at", "_airbyte_normalized_at", "_airbyte_qr_unfiltered_hashid")
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -       (
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -          select "date", "q_id", "email", "title", "is_fake", "user_id", "lastname", "firstname", "debut_hour", "q_response", "sessions_id", "companies_id", "_ab_source_file_url", "_ab_additional_properties", "_ab_source_file_last_modified", "20211217_084000_00019_p9b4y"'"
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -   LINE 10: ...ile_last_modified", "20211217_084000_00019_p9b4y"'", "_airb...
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -                                                                 ^
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/public/qr_unfiltered.sql
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 - 
normalization - 2021-12-17 10:03:43 INFO () LineGobbler(voidCall):82 - Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

</details>

## Steps to Reproduce
1. S3 csv source file (Athena request result) 
2. destination PostgreSQL db
3. sync (error with all sync mode options) 

## Are you willing to submit a PR?
no (not qualified)

**Comment by lolrenx** [comment]
source and destination catalog : 

```
{"streams":[{"stream":{"name":"qr-unfiltered","json_schema":{"type":"object","properties":{"date":{"type":["null","string"]},"q_id":{"type":["null","number"]},"email":{"type":["null","string"]},"title":{"type":["null","string"]},"i
s_fake":{"type":["null","boolean"]},"user_id":{"type":["null","number"]},"lastname":{"type":["null","string"]},"firstname":{"type":["null","string"]},"debut_hour":{"type":["null","string"]},"q_response":{"type":["null","string"]},"
sessions_id":{"type":["null","number"]},"companies_id":{"type":["null","number"]},"_ab_source_file_url":{"type":"string"},"_ab_additional_properties":{"type":"object"},"_ab_source_file_last_modified":{"type":"string","format":"date
-time"},"\u001B20211217_084000_00019_p9b4y\"'":{"type":["null","string"]}}},"supported_sync_modes":["full_refresh","incremental"],"source_defined_cursor":true,"default_cursor_field":["_ab_source_file_last_modified"],"source_defined
```

**Comment by alafanechere** [comment]
Hi @lolrenx I think the root cause comes from an encoding problem on your source file.
PyArrow can't read / cast it properly because a record causes:
`pyarrow.lib.ArrowInvalid: In CSV column #0: CSV conversion error to large_string: invalid UTF8 data`

Could you check in we which encoding your source file is encoded and adapt the `encoding` file of the source configuration?
![Screen Shot 2021-12-20 at 09 35 24](https://user-images.githubusercontent.com/5551758/146737162-b6c74fef-d27c-4fe2-8e27-53f36d6b17ef.png)

I suspect the column `\u001B20211217_084000_00019_p9b4y` to be the culprit due to it's strange name.

**Comment by lolrenx** [comment]
makes sense, this is AWS programmatically naming Athena query results. I'll see to rename them on the fly.
