### ISSUE TITLE
Document how to add basic normalization to new destinations

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#887]
## Tell us about the documentation you'd like us to add or update
We've added basic normalization but don't describe the path for adding it to new integrations. We've held off on doing it because as a new feature it's been changing alot and not ready to document. Once we feel it is stable we should add docs.

Splitting out from Basic Normalization Issue https://github.com/airbytehq/airbyte/issues/782

**Comment by ChrisZou** [comment]
Hi, any update on this? I'm building a destination connector for our db and would like it to support normalization. Haven't found any step by step guide yet.

**Comment by grishick** [comment]
@ChrisZou we are planning to make some big changes to how normalization works in the next couple of months, so we are not going to document this until then.

**Comment by marcosmarxm** [comment]
Normalization is deprecated and removed from the codebase. @evantahler closing this issue.
