### ISSUE TITLE
🐛 Source Recurly: testing connection fails with Exceeded quota limits

### ISSUE THREAD

**Issue by stefanocascavilla** [airbytehq/airbyte#8876]
Hello,

We are experiencing issues with the Recurly 0.2.6 (latest version) connector. After we insert the **api_token** required, before creating the source, Airbyte is stuck on the **Testing connection** message. After about 10 minutes a **Exceeded quota limits** error appears, but it's not a quota issue because all our other services that leverage Recurly work as expected.

[Server logs](https://github.com/airbytehq/airbyte/files/7755965/server-logs.1.txt)

**Comment by alafanechere** [comment]
Hi @stefanocascavilla could you please provide the server logs. 
You can download these from the settings page
<img width="1058" alt="Screen Shot 2021-12-20 at 10 15 42" src="https://user-images.githubusercontent.com/5551758/146742772-b650a7ec-89cb-467c-96a1-63dd159a9de4.png">

**Comment by yevhenii-ldv** [comment]
Hello, @stefanocascavilla!
I have investigated your problem with the Recurlu connector. Unfortunately, I was not able to reproduce an error like yours. I also created a new account for Recurlu and tried to connect it - and everything worked out without any problems.

In this regard, I have a request to you, try to update the connector version to the latest one that we currently have (version 0.3.0) and try again to create a connection (please check that you do not have any extra spaces left in `api_token`). If this time there is an error, could you please make a screen of the error of the test that you receive and attach it along with the answer.

**Comment by stefanocascavilla** [comment]
Hello @yevhenii-ldv, I tried out the 0.3.0 connector's version and was able to set up the connector correctly. Thank you!
