### ISSUE TITLE
S3 Destination : Json to Avro converter should change format of `date-time` to `timestamp-micros`

### ISSUE THREAD

**Issue by DoNotPanicUA** [airbytehq/airbyte#8886]
According to https://github.com/airbytehq/airbyte/blob/master/docs/understanding-airbyte/json-avro-conversion.md#built-in-formats all `date-time` types in a format attribute should be replaced by `timestamp-micros`.
Current implementation converts type `string` with format `date-time` into `long` type with `date-time` instead of `timestamp-micros`.

---

From @tuliren: the description of this issue is probably incorrect. The Json to Avro schema converter already converts Json format `date-time` to Avro logical type `timestamp-micros`. What we need to do is to not have a specific case for `timestamp-micros` because this format should never exist in the Json schema.

**Comment by tuliren** [comment]
A few other TODOs for the Json -> Avro schema converter:
- [ ] Create a separated one for Json -> BigQuery schema converter.
- [ ] Maybe refactor the namespace generation logic. If not, add unit tests.
