### ISSUE TITLE
Postgres source date includes time, and cannot handle BC dates

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8903]
We can make Postgres source return the correct date only format. However, the change is reverted ([commit](https://github.com/airbytehq/airbyte/pull/8726/commits/e1dac8ed19197f7e66235a9f7f96967fb6c8db41)) in #8726, because we are not sure if the destination / dbt can handle a BC date string correctly.

**Comment by tuliren** [comment]
Date handling in normalization:
https://github.com/airbytehq/airbyte/pull/8726#discussion_r772594870
https://github.com/airbytehq/airbyte/pull/8726#discussion_r772596643

**Comment by TBernstein4** [comment]
A user encountered this error related to normalizing BC Dates. Version info the Postgres (1.0.19) <> and the Snowflake (0.4.38) , both running Airbyte 0.40.17 under Docker on Ubuntu.

```
Database Error in model ********* (models/generated/airbyte_tables/*****/*****.sql) 100040 (22007): Date '0001-12-07 BC' is not recognized compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/*****/*****.sql,retryable=<null>,timestamp=1666774207256], io.airbyte.config.FailureReason@136014f7[failureOrigin=normalization,failureType=system_error,internalMessage=100040 (22007): Date '0001-12-07 BC' is not recognized,externalMessage=Normalization failed during the dbt run. This may indicate a problem with the data itself.,metadata=io.airbyte.config.Metadata@a9ef4db[additionalProperties {attemptNumber=2, jobId=1506, from_trace_message=true}],stacktrace=AirbyteDbtError: 1 of 1 ERROR creating table model *****............................................................... [ERROR in 87.01s]
```
@VitaliiMaltsev Has anything changed that would cause this issue to return?
