### ISSUE TITLE
UI should output why check connection fails if reason is available

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#893]
## Tell us about the problem you're trying to solve

The backend often mentions why a connection to a source is not possible. However the UI does not propagate this. 
UI: 
![Screen Shot 2020-11-10 at 5 04 05 PM](https://user-images.githubusercontent.com/6246757/98752286-be415d80-2376-11eb-8db1-e633967f1a71.png)
Backend logs: 
<img width="959" alt="Screen Shot 2020-11-10 at 5 04 18 PM" src="https://user-images.githubusercontent.com/6246757/98752300-c6010200-2376-11eb-868f-21934392eef8.png">

as a UI user it would be very helpful if I can know what went wrong so I can fix it. The current message is not actionable.

**Comment by ChristopheDuong** [comment]
In stitch, you have access to the logs in the UI when testing connection setup, it's very convenient...

Plus we already display the logs when running sync so it's not completely new?

**Comment by sherifnada** [comment]
done
