### ISSUE TITLE
Define a variable to get the current date in order to use it for partitioning purposes.

### ISSUE THREAD

**Issue by stefanocascavilla** [airbytehq/airbyte#8956]
It would be nice to have the possibility to have a global variable representing the current date in order to use it in the connection configuration.

ex. If we'd like to partition the data in the destination by using the **extraction_date**, we are not able to do so.

**Comment by marcosmarxm** [comment]
thanks for requesting this @stefanocascavilla, can you check if https://github.com/airbytehq/airbyte/issues/4178 is something similar to your request?

**Comment by stefanocascavilla** [comment]
Hello,
It's similar but we'd like to have a kind of environment variable for the date in order to be used in the custom path prefix

**Comment by evantahler** [comment]
Closing this for now, as we have no short or mid-term plans to do this.  We don't have a way at the moment to inject environment variables into a connector's configuration.  If you are going to use this for a custom connector, you could always make your container's init script export export the [current date](https://stackoverflow.com/questions/20485749/how-to-set-a-variable-to-current-date-and-date-1-in-linux).
