### ISSUE TITLE
Source Salesforce: add new field into spec.json for setting Salesforce's `user`

### ISSUE THREAD

**Issue by yevhenii-ldv** [airbytehq/airbyte#8961]
## Tell us about the problem you're trying to solve
Add the ability to specify a user for the Salesforce connector to access only pre-configured streams,  [see the example from fivetran](https://fivetran.com/docs/applications/salesforce/setup-guide#createnewuserandprofileinsalesforceoptional)

## Are you willing to submit a PR?
yes

**Comment by sherifnada** [comment]
@yevhenii-ldv isn't the user supposed to instead login as that user via oauth and present a refresh_token scoped for that user, instead of adding a `user` field to spec.json?

**Comment by yevhenii-ldv** [comment]
> @yevhenii-ldv isn't the user supposed to instead login as that user via oauth and present a refresh_token scoped for that user, instead of adding a `user` field to spec.json?

Sherif, yep, I see. Created PR only with updated Salesforce's docs
