### ISSUE TITLE
Airbyte Jira conector is not bringing all the historical data

### ISSUE THREAD

**Issue by MatheusFreitas25** [airbytehq/airbyte#8963]
## Environment
- 0.34.0-alpha
- AWS EC2
- DOCKER
- Jira 0.2.15
- Redshift 0.3.21
- High
- Sync job

## Current Behavior
using the old jira connector (v0.2.6) I can get all the historical data but it doesn’t have all the tables, and it takes 6-7 hours for a single sync. Using the most current connector (v0.2.15) I get all the tables I need but I’m not getting all the data, they should be approximately 165,000 and only 800 arrive and is creating about 500 tables in the database

## Expected Behavior
The connector should bring all the historical data from the tables I selected according to the date that was passed.

## Logs
[logs-4650-0.txt](https://github.com/airbytehq/airbyte/files/7745949/logs-4650-0.txt)

**Comment by marcosmarxm** [comment]
Thanks @MatheusFreitas25 I added the issue to our connector roadmap.

**Comment by vitaliizazmic** [comment]
I've checked logs and found out that syncing was interrupted by fail of syncing Board issues stream. Board issues are received for each Board by ID, Connector accordingly firstly gets Boards. And syncing of Boards failed with error "403 Client Error: Forbidden for url". 
According to [documentation](https://developer.atlassian.com/cloud/jira/software/rest/api-group-other-operations/#api-agile-1-0-board-get) 403 error is returned when the user does not have valid license.
Also I've [asked](https://community.atlassian.com/t5/Jira-Software-questions/Jira-Software-Cloud-REST-API-Get-all-boards-403-response/qaq-p/1900645#U1900934) Atlassian Community about this issue and received answer. According to response "403 errors usually indicates that the user you are executing the API request against doesn't have proper permissions".

**Comment by vitaliizazmic** [comment]
Hello @MatheusFreitas25, could you please check conditions bellow

1. You have valid license.
2. You have permissions and your user has been setup to be able to view the boards you are looking to return as well as the projects those boards belong to.
3. Login with your user and open this [link](https://kovi.atlassian.net/rest/agile/1.0/board?projectKeyOrId=10014) in browser and check if status code is 200.

**Comment by MatheusFreitas25** [comment]
Thanks, i'll check it today

**Comment by VasylLazebnyk** [comment]
Closing this issue until the @MatheusFreitas25 will get back with his feedback. 
Matheus - if the issue still appears - feel free to reopen the ticket.
