### ISSUE TITLE
Running duration of in progress job is incorrect in the UI 

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#897]
## Expected Behavior
My sync job has been running for a few minutes, but the UI shows it as running for 5s. 

![Screen Shot 2020-11-10 at 5 29 19 PM](https://user-images.githubusercontent.com/6246757/98753905-4a08b900-237a-11eb-957a-5c8709c0e870.png)

## Reproduce
1. start a manual sync
1. click into the source's page
1. sit there for a while -- the duration counter doesn't update even when the page is refreshed

**Comment by cgardens** [comment]
i think this has been fixed, but let's confirm it.

**Comment by cgardens** [comment]
double checked. it has. we don't show duration until it's done. we just show created at. we do show zeroes until it's done which is a tad awkward but livable for now.
