### ISSUE TITLE
Webpage error when trying to create a source with Source E2E Test connector

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#8973]
## Environment
- **Airbyte version**:  0.34.2-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Kubernetes
- **Source Connector and version**: `airbyte/source-e2e-test:0.1.1`
- **Destination Connector and version**: n/a
- **Severity**: Medium
- **Step where error happened**: Create Source

## Current Behavior
After adding the `airbyte/source-e2e-test:0.1.1` custom connector, I try to create a Source using that connector. When I select that connector from the dropdown, I get the following error in the chrome console:
```
react-dom.production.min.js:216 TypeError: Failed to fetch
    at <anonymous>:1:876
    at Documentation.ts:2
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
```
and the webpage just shows `Cannot reach server. The server may still be starting up.`

No errors are logged in my `airbyte-server` or `airbyte-webapp` containers, so this seems to be a frontend issue. I was able to successfully create a source from this connector on Dec 16 and before, so this seems like a regression.

## Expected Behavior
I expect to be able to create a Source using the `airbyte/source-e2e-test` custom connector.

## Steps to Reproduce
1. Add the `airbyte/source-e2e-test` source connector, with version `0.1.1`
2. Try to create a Source using that connector

**Comment by timroes** [comment]
@lmossman Given this issue is a couple of month old, are you still able to reproduce this and if so, could you have a copy of the request that fails?

**Comment by lmossman** [comment]
@timroes I am no longer able to reproduce this, so I'm going to close this issue out.
