### ISSUE TITLE
Normalization double quotes postgres identifiers

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#898]
## Expected Behavior
When I sync data from salesforce to postgresql with normalization turned on I expect to find normalized tables in PG. 

## Current Behavior
raw sync completes but normalization fails

<img width="1758" alt="Screen Shot 2020-11-10 at 5 42 49 PM" src="https://user-images.githubusercontent.com/6246757/98754735-28103600-237c-11eb-8cd3-9c4ba13ca7c9.png">

## Steps to Reproduce
1. Sync Salesforce to postgres (I sync'ed all SF tables)
1. raw sync completes, but normalization fails
1. Look at server logs. I observe the exception abvoe

## Severity of the bug for you
High

**Comment by sherifnada** [comment]
The actual cause of this issue is that postgres is not handling uppercase table names: 
![](https://files.slack.com/files-pri/T01AB4DDR2N-F01F650USHW/screen_shot_2020-11-10_at_6.48.05_pm.png)

**Comment by ChristopheDuong** [comment]
Does the alter table command works if you quote the table names though?

To inspect manually with DBT, you can navigate to the /tmp/* workspace in the normalize folder and play with the quoting style. 
You could find what works or not in Postgres by changing the settings in the sources.yml that is generated in the `models/generated` directory

(which influence the behavior of the macro `adapter.quote_as_configured`)
