### ISSUE TITLE
Run the source database benchmarks with various CPU and memory limits

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8981]
- Run it in CI or locally.
- Use different combinations of `--cpulimit` and `--memorylimit` to find the lower bound of the resource requirement.

Desired result: a benchmark test can be run periodically to determine how much time a given DB source size takes with given CPU and memory limits. For the first iteration, we need to focus only on Postgres as the source DB.

**Comment by grishick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/8981?planning-poker) with ZenHub @tuliren @edgao @subodh1810

**Comment by grishick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/8981?planning-poker) with ZenHub @noahkawasaki-airbyte
