### ISSUE TITLE
CI Sandbox: Flexport

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8986]
We need an integration account for[ Flexport' API](https://apidocs.flexport.com/reference/introduction?_ga=2.239322435.1923824721.1633364104-1920615614.1632529090&_gac=1.61530462.1629930124.CjwKCAjw1JeJBhB9EiwAV612y8aIe4BP1GOpa8cOG2J2HUrJhy_YVZ7WmGt-8k9UDAuqBCEh9pYjCBoCmU0QAvD_BwE) to test and publish this PR: https://github.com/airbytehq/airbyte/pull/8777

**Comment by karinakuz** [comment]
Signed up and sent letter about sandbox, waiting the answer from support

**Comment by karinakuz** [comment]
No answer - sent one more request through the website and letter via email

**Comment by alafanechere** [comment]
@karinakuz, did you receive any update from Flexport?

**Comment by karinakuz** [comment]
@alafanechere I received the same standard answer from Flexport  (hello@flexport.com)  to all my letters: 

Hi there,

Thanks for reaching out to Flexport. We're here to make moving freight as easy, cost-effective, and transparent as possible. We look forward to learning about your shipping needs, and will be in touch soon.

**Comment by karinakuz** [comment]
I've left one more request on their site https://www.flexport.com/contact-us/

**Comment by karinakuz** [comment]
I sent letter about sandbox account to lbovolenta@flexport.com, ben.widdowson@flexport.com (contacts from contributors) and  teamece@flexport.com  on 5 January but still no answer
