### ISSUE TITLE
🐛 Connector setup crashes if the request to documentation URL returns an HTTP error

### ISSUE THREAD

**Issue by monai** [airbytehq/airbyte#9003]
## Environment
- **Airbyte version**:  example is 0.34.2-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: any
- **Destination Connector and version**: any
- **Severity**: Critical
- **Step where error happened**: Setup new source connector

## Current Behavior

If a request to an URL provided in `documentationUrl` in connector's spec returns an HTTP error, Airbyte UI crashes irrecoverably and without any meaningful error message.

spec.json:

```json
{
  "documentationUrl": "http://example.com/",
  "connectionSpecification": {
    ...
  }
}
```

This PR introduced the bug:
https://github.com/airbytehq/airbyte/commit/cc038cd196273f49f55f7583ad19618000239a11#diff-a83d73533fd7ed3d76530f879ebc04a9f7cb258edb64773ae008f24b62854779R12

It assumes specific `documentationURL` values without any check and error recovery, while the CDK code generator defaults the property to `https://docsurl.com`. Therefore this commit renders all newly generated connectors failing without any visible error message.

## Expected Behavior

I expect all errors during UI interactions to be visible in the UI.

In addition, I expect newly introduced conventions, assumptions, formats, etc., to be deployed throughout the codebase. At this PR merge commit, the connector generator emits the code that doesn't conform to these new assumptions: https://github.com/airbytehq/airbyte/blob/cc038cd196273f49f55f7583ad19618000239a11/airbyte-integrations/connector-templates/source-python-http-api/source_%7B%7BsnakeCase%20name%7D%7D/spec.json.hbs#L2

## Logs

![Screenshot 2021-12-21 at 17 13 59](https://user-images.githubusercontent.com/1473062/146957490-5dda20ee-7b0a-4203-88e8-f3758326d60f.png)

## Steps to Reproduce

1. Generate a new source connector.
2. Build a container.
3. Create a new source in UI.

## Are you willing to submit a PR?

No

**Comment by marcosmarxm** [comment]
Thanks @monai. I workaround is to use: `localhost`

**Comment by sherifnada** [comment]
this has been fixed
