### ISSUE TITLE
logs.minio.enabled in values.yaml set to false does not prevent the creation of a minio deployment 

### ISSUE THREAD

**Issue by nord-ine** [airbytehq/airbyte#9010]
it will be best to fix the double usage of minio.enabled and logs.minio.enabled . I think that the best solution is to describe s3 connections outside logs namespace .
the  helm charts dependency use minio.enabled and not logs.minio.enabled , so if you don't want an internal minio without this flag (minio.enabled) it still installed

**Comment by marcosmarxm** [comment]
thanks @nord-ine can you submit a PR to correct this problem?

**Comment by marcosmarxm** [comment]
Closing due inactivity. @nord-ine please test latest version of helm deployment.
