### ISSUE TITLE
Postgres Source Connector Hides Materialized Views

### ISSUE THREAD

**Issue by jedwards-gc** [airbytehq/airbyte#9012]
## Environment
- **Airbyte version**:  example is 0.32.5-alpha
- **OS Version / Instance**: Amazon Linux 2, AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 0.3.14+
- **Destination Connector and version**: N/A
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Setup new connection / Update latest source schema

## Current Behavior
Materialized views don't show up in the source schema due to this change: https://github.com/airbytehq/airbyte/pull/8010 v0.3.13 and earlier worked fine, but after 0.3.14 materialized views don't show up. Views and tables work fine, but materialized views don't. Here's a StackOverflow post I found that describes how getting privileges for materialized views is different from regular views and tables: https://stackoverflow.com/questions/38728548/list-grants-and-privileges-for-a-materialized-view-in-postgresql

## Expected Behavior
Materialized views should be included in the source schema catalog

## Logs
N/A

## Steps to Reproduce
1. In the source database, create a materialized view (e.g. `CREATE MATERIALIZED VIEW my_table AS ...`)
2. In Airbyte click "Update source schema" button and the materialized view won't be in the list

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment]
Thanks @jedwards-gc I added the issue in the connector roadmap.

**Comment by marcosmarxm** [comment]
@misteryeo it's possible to check this issue? another user in our [Slack commented](https://airbytehq-team.slack.com/archives/C021JANJ6TY/p1645220853029199) was not able to pull views from Postgres either.

**Comment by jedwards-gc** [comment]
@marcosmarxm @misteryeo I hadn't heard back on this so I tracked down the problem and opened this issue with my findings: https://github.com/airbytehq/airbyte/issues/10389

**Comment by jablonskijakub** [comment]
@misteryeo can you give any comment? it's quite urgent for my case and otherwise I would start working on another way to integrate materialized views to my db. thank you for your help!

**Comment by misteryeo** [comment]
Hey @jedwards-gc @jablonskijakub apologies for the delay here - we'll take a look at this this week and come back to you on this thread!

**Comment by jablonskijakub** [comment]
Hey @misteryeo. Could you let us know if you have managed to take a look and made any progress re this issue? thanks a lot.

**Comment by misteryeo** [comment]
@etsybaev should be able to provide an update here.

**Comment by jablonskijakub** [comment]
thanks a lot. @etsybaev could you please share an update with us?

**Comment by etsybaev** [comment]
Hi there.
Sorry, I didn't see this ticket before. I will take a look,
In my previous PR, I'd created a Materialized view and was able to process it (also added captures). 
But probably there are also some other ways that hadn't been considered to some issues with autogenerated roles.

**Comment by etsybaev** [comment]
Closing this ticket as particular roles issue trying to solve in another opened issue https://github.com/airbytehq/airbyte/issues/10389
