### ISSUE TITLE
Normalisation fails on Hubspot to Redshift (Airbyte - 0.34.4-alpha Redshift - 0.3.23 Hubspot - 0.1.29) 

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#9014]
## Environment
- **Airbyte version**:  0.34.4-alpha
- **OS Version / Instance**: AWS EC2 T3a XL $ uname -a
Linux eu-west-1.compute.internal 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Deployment**: Docker 
- **Source Connector and version**:Hubspot 0.1.29
- **Destination Connector and version**: Redshift 0.3.23
- **Severity**:  High
- **Step where error happened**:  Sync job 

## Current Behavior
Sync works when normalization is not done but fails when normalization is done  
Augustin:airbyte:  2 hours ago
It's a normalization issue, the normalization fails at casting a millisecond timestamp (1564531200000) to an appropriate format for your destination. Could you please tell me which destination you are using? I'd encourage you to open an issue on our repo as this looks like a bug we could fix. If by any chance you find a line items record on Hubspot that has this timestamp in the createdAt our updatedAt field it would be great for troubleshooting (it corresponds to Wednesday, 31 July 2019 00:00:00).

I can't find the line in question having looked if you can provide me more guidance on how to find it happy to provide 

## Expected Behavior

Noralization should work and complete with out issue. 

[logs-206-1.txt](https://github.com/airbytehq/airbyte/files/7758113/logs-206-1.txt)
[logs-206-0.txt](https://github.com/airbytehq/airbyte/files/7758114/logs-206-0.txt)

## Logs
See atteched.

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Sync from hubspot to redshift
2.
3.

**Comment by marcosmarxm** [comment]
Thanks @nthbooth-feedr I added the issue to the connector roadmap.

**Comment by flotenva** [comment]
I am experiencing a similar issue here:

- Airbyte version: 0.35.0-alpha
- OS Version / Instance: AWS EC2 T3a M
- amzn2-ami-kernel-5.10-hvm-2.0.20211201.0-x86_64-gp2
- Deployment: Docker
- Source Connector and version:Hubspot 0.1.29
- Destination Connector and version: PostgreSQL
- Severity: High
- Step where error happened: Sync job

**Comment by flotenva** [comment]
There seems to be an issue with normalization - specifically with date/time conversion. These are the logs:

2022-01-03 23:19:31 normalization > 23:19:31 | Finished running 19 table models in 660.24s.
2022-01-03 23:19:31 normalization > 
2022-01-03 23:19:31 normalization > Completed with 1 error and 0 warnings:
2022-01-03 23:19:31 normalization > 
2022-01-03 23:19:31 normalization > Database Error in model line_items_properties (models/generated/airbyte_tables/airbyte_hubspot/line_items_properties.sql)
2022-01-03 23:19:31 normalization >   date/time field value out of range: "1743465600000"
2022-01-03 23:19:31 normalization >   HINT:  Perhaps you need a different "datestyle" setting.
2022-01-03 23:19:31 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_hubspot/line_items_properties.sql
2022-01-03 23:19:31 normalization > 
2022-01-03 23:19:31 normalization > Done. PASS=18 WARN=0 ERROR=1 SKIP=0 TOTAL=19

After the run is completed with the aforementioned error, another run is attempted with the same result.

**Comment by augan-rymkhan** [comment]
It seems this issue is related to #9264

**Comment by augan-rymkhan** [comment]
It was fixed in PR [10576](https://github.com/airbytehq/airbyte/pull/10576)
