### ISSUE TITLE
New Source: Dremio

### ISSUE THREAD

**Issue by kurousa** [airbytehq/airbyte#9031]
## Tell us about the new connector you’d like to have
* Which source and which destination?
   * Source

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
   * Want to support for since 4.0.x.

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
   * We use this to DWH and analyze the data by other plaform.

* How often do you want to run syncs?
   * It's not clear, but it needs to be synchronized at regular intervals.

* If this is an API source connector, which entities/endpoints do you need supported?
   * We want run query on the Dremio, and retrieve the result by airbyte.

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 
   * We probably not possible.

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
  * Currently no alternative.
## Are you willing to submit a PR?

if need it, but we cant`t pull from docker image of CDK connector-bootstrap currentry.  
Is it private?

**Comment by pipat-flowacc** [comment]
I have a similar use case too. I plan to use Dremio as a central Data Lakehouse, but my team still needs RedShift for analytics. 
Having a Dremio source connector would mediate the transition from Data Warehouse in RedShift to Data Lakehouse in Dremio.

**Comment by jdbranham** [comment]
This would make my life so much easier =]

Is anyone developing it already?

**Comment by ycherniaiev** [comment]
**Integration Vwtting**

Webhook-based? (no/partially/yes) 
no

Available authentication modes (A key/Oauth/other) 
API:
https://superset.apache.org/docs/rest-api
OAuth:
https://superset.apache.org/docs/installation/configuring-superset#custom-oauth2-configuration

Has Sandbox environment? 
No:
Business intelligence web application, local installation and connecting to different databases or data sources:
https://superset.apache.org/docs/intro
Installing Superset Locally Using Docker Compose:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

How to populate the account with data 
UI:
https://superset.apache.org/docs/creating-charts-dashboards/exploring-data#exploring-data-in-superset
Superset's public REST API follows the OpenAPI specification:
https://superset.apache.org/docs/rest-api
YAML:
https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources

Available streams for sync 
Datasets
Databases

Integration supports incremental sync? 
No:
Async Queries via Celery:
https://superset.apache.org/docs/installation/async-queries-celery

Other information/blockers 
Installation and configuration additional info:
https://www.programmersought.com/article/42687163708/"

**Comment by lazebnyi** [comment]
[Scoping Document for Dremio](https://docs.google.com/document/d/1Y09BvNXCQEDJK-DakSslXyHaPAxPjwe5Wv9cof6qbCw/)
