### ISSUE TITLE
UI Settings > Sources/Destinations useless space creates horizontal scroll

### ISSUE THREAD

**Issue by lizdeika** [airbytehq/airbyte#9035]
## Environment
- **Airbyte version**:  0.35.0-alpha
- **OS Version / Instance**: aws ec2
- **Deployment**: Docker
- **Severity**: Medium
- **Step where error happened**: Settings UI
- **Device**: MacBook Pro (13-inch, M1, 2020)
- **Browser**: Safari 15.1
- **Screen resolution**: 2560x1600

## Current Behavior
Browser window maximized, full width, full height for the screen.
UI Settings Sources and Destinations tables have lots of useless white space which creates horizontal scroll and one can not see Action buttons without scrolling out

![space](https://i.ibb.co/sQn14M4/Space.png)

## Expected Behavior
Tables should fit in the screen that is big enough (2560x1600)

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. 
2.
3.

**Comment by marcosmarxm** [comment]
This is fixed in latest version
![image.png](https://images.zenhubusercontent.com/6196866ff4b9a806bbd927e6/7a5b20e7-213d-46b2-b08e-375ab1934176)
