### ISSUE TITLE
Find a replacement for gitbook

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#905]
## Tell us about the problem you're trying to solve
Although we are thankful to have access to the OSS edition of Gitbook, it has become a real time sink to work with it over the past few months. To list a some of the issues we've encountered:
- keeps creating new files and changing links -> results in bloated PR and unnecessary conflicts
- sometime instead of setting the link to a relative path, it sets the branch blob leading to broken links
- no automated checking of the links -> easy to have a broken links
- no easy way to add analytics -> we have a nasty cloudflare hack to rewrite the documents on the fly
- unresponsive support
- documentation edition doesn't work well with our github workflow (branches & pr). We tried to work around it with variants but is still a very flaky experience as there is a lag in updates

What we like about Gitbook:
- Opinionated design so we can focus on the content instead of building yet another UI and UX
- WYSIWYG is very convenient
- Pretty visual extensions

**Comment by avaidyanatha** [comment]
Closing for now, will reopen if we reassess this in the future.
