### ISSUE TITLE
🐛  Source Zendesk support: getting stuck everytime in report ticket_metrics

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9052]
## Environment
Is this your first time deploying Airbyte: No
*OS Version* / Instance: Ubuntu 20.04
*Machine type* e2-highmem-16 ( 2 CPU )
*Memory / Disk:* 16Gb / 100 GB ssd
*Deployment*: Docker
*Airbyte Version:* 0.34.4-alpha
*Source name/version:* airbyte/source-zendesk-support:0.1.10
*Destination name/version:* airbyte/destination-bigquery:0.5.1
*Description*: getting stuck everytime in report *ticket_metrics.*

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1640120654180600?thread_ts=1640120654.180600&cid=C01MFR03D5W

**Comment by marcosmarxm** [comment]
Logs from the user: [logs-26-1.txt](https://github.com/airbytehq/airbyte/files/7764955/logs-26-1.txt)
