### ISSUE TITLE
🐛 Source Zendesk Chat: Only a subset of record are synced

### ISSUE THREAD

**Issue by BrennaPaine** [airbytehq/airbyte#9054]
We are trying to upload the Zendesk Chat data into Snowflake.  I was able to use the UI to move the Call data but when I try to do the same process for Chat, it will only get about 800 records.  I need all the data or at least 2021.  Can you help?

**Comment by alafanechere** [comment]
Hi @BrennaPaine, It would be awesome if you could fill our issue template to get more details for us to help you.
We'd at least need: 
* The Airbyte version you are running.
* The connector version you are using.
* The sync attempt logs. You can download them from the UI.

**Comment by marcosmarxm** [comment]
Closing due lack of infomration.
