### ISSUE TITLE
Missing logs in the UI on the schema fetch step

### ISSUE THREAD

**Issue by krishagel** [airbytehq/airbyte#9056]
## Environment
- **Airbyte version**:  0.35.1
- **OS Version / Instance**: Amazon Linux release 2 (Karoo)
- **Deployment**: Docker
- **Source Connector and version**: File 0.2.8
- **Destination Connector and version**: MySQL 0.1.15
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
When adding a destination to a setup source, if it fails to fetch the schema, we used to be able to see the logs. That button is no longer visible in the UI

## Expected Behavior
We should be able to see the logs via a dropdown as we have in previous releases.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

<img width="1329" alt="CleanShot 2021-12-22 at 09 29 12@2x" src="https://user-images.githubusercontent.com/530001/147132183-3d7e6bf6-4964-4c04-a24d-15573fcf66c9.png">


```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by krishagel** [comment]
<img width="1329" alt="CleanShot 2021-12-22 at 09 29 12@2x" src="https://user-images.githubusercontent.com/530001/147132277-3cdf8b13-6182-42f6-a70d-bcab1f48ccbe.png">

**Comment by alafanechere** [comment]
@misteryeo do you know if this is a bug or a design decision?

**Comment by jrhizor** [comment]
This is an oversight. We should add the ability to view logs for failed discoveries.

**Comment by toandm** [comment]
Please add this. I have an issue that the discover method works on my local machine, both running as docker and as python code. But when deployed on the remote machine, it failed at the discover phase. I have no idea why.

**Comment by adnanjmi21** [comment]
I am also getting the same  error for source mysql , is there any other way to pull the logs
