### ISSUE TITLE
Source S3: error with encoding reading csv file

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9059]
*Is this your first time deploying Airbyte*: No
*OS Version / Instance*: Ubuntu t3.xlarge
*Memory / Disk*: 16 /100 Gb
*Deployment*: Docker
*Airbyte Version*: 0.34.1-alpha
*Source name/version*: S3 0.1.7
*Destination name/version*: Redshift 0.3.21
*Description*: I'm setting my connection and doing the initial sync but incurs in random error.
`pyarrow.lib.ArrowInvalid: CSV parser got out of sync with chunker`
It's not at specific point because in one run what when airbyte reads 316000 records and the other when 2000 records. I attach the logs.

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1640118333173600?thread_ts=1640118333.173600&cid=C01MFR03D5W

**Comment by marcosmarxm** [comment]
https://github.com/airbytehq/airbyte/blob/3cb669bc5d003c62da72544d73aed49e5587865f/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/csv_spec.py#L33-L36

**Comment by marcosmarxm** [comment]
The user was able to read the file using the code:
```
import csv

with open('26532476_20211202.txt', encoding='ISO-8859-1') as csv_file:
    row_count = sum(1 for row in csv_file)
    csv_reader = csv.reader(csv_file, delimiter='|')
    for row in csv_reader:
        print(row)
```

**Comment by yevhenii-ldv** [comment]
Hi @octavia-squidington-iii!
I've investigated your question and the logs.
We have a field (optional) for specifying the `encoding` of your `csv` file, and according to the logs, the value "latin_1" is indicated there. This is not entirely correct encoding, could you please create a connection again and specify the values of `latin-1` or `iso-8859-1` in the `encoding` field, and check how your synchronization will work this time.

![image](https://user-images.githubusercontent.com/34103125/148238042-0351d594-ff11-43b1-8522-0dc322e1ce08.png)


Also, it would be nice if you updated the S3 connector version to 0.1.8, there are changes mainly only in the specification, but for the purity of the experiment it would not be superfluous.

Looking forward to your feedback

**Comment by VasylLazebnyk** [comment]
This ticket is closed, contributor confirms this issue is not actual after Yevhen's comment in [Slack conversation](https://airbytehq.slack.com/archives/C01MFR03D5W/p1640118333173600)

**Comment by sharath-rama** [comment]
I tried both latin-1 or iso-8859-1, still I see the same error
