### ISSUE TITLE
Google Ads Source: `Numeric value 'KEYWORD' is not recognized` normalization error

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9069]
## Current Behavior
from [slack](https://airbytehq.slack.com/archives/C019WEENQRM/p1640203679026500)

the Google Ads connector where it is not able to normalize the keyword_report table (log error: 100038 (22018): Numeric value 'KEYWORD' is not recognized) because of a wrong type definition here: https://github.com/airbytehq/airbyte/blob/13ac480a8b0024360d35c20fd6d640296b57f137[…]source-google-ads/source_google_ads/schemas/keyword_report.json

## Expected Behavior
normalization should succeed

**Comment by grubberr** [comment]
@sherifnada @marcosmarxm 
is it already fixed here
https://github.com/airbytehq/airbyte/pull/9071
?

**Comment by marcosmarxm** [comment]
Yes @grubberr
