### ISSUE TITLE
Add preview functionality in connectors

### ISSUE THREAD

**Issue by rajumnit** [airbytehq/airbyte#9074]
## Tell us about the problem you're trying to solve
Today, If we want to see sample data there is no proper way. There should be OOTB support for preview of different stream that return just n (5,10,20..) lines

## Describe the solution you’d like
Add preview functionality in each connector

## Describe the alternative you’ve considered or used
Read

## Are you willing to submit a PR?
Depends on work required.

**Comment by marcosmarxm** [comment]
Closes as duplicated from https://github.com/airbytehq/airbyte/issues/6250
