### ISSUE TITLE
Is airbyte production ready?

### ISSUE THREAD

**Issue by ilijaNL** [airbytehq/airbyte#9075]
Hello,
Since I couldn't find any documentation about this, 
I wonder if airbyte is production ready and which company's are using it in production. I am considering using airbyte for a customer however since I see the alpha release tags I wonder if it is a right decision.

Thanks

**Comment by alafanechere** [comment]
Hi @ilijaNL, I'd encourage you to reach us on our[ Slack.](https://slack.airbyte.io/) You'll be able to meet with Airbyte users to share some insights about their product usage.

**Comment by ilijaNL** [comment]
@alafanechere thanks, I will don't. However it is nice to mention somewhere on the docs either airbyte is production ready or not for future researchers.
