### ISSUE TITLE
Correct Source Posthog CI tests

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9088]
Looks Source Posthog is failing CI: https://github.com/airbytehq/airbyte/actions/runs/1615296300
There is an open community contribution doing changes to this connector and we need the tests working to approve the change.

Error
```
response.raise_for_status()\n  File \"/usr/local/lib/python3.7/site-packages/requests/models.py\", line 953, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://app.posthog.com/api/event/sessions"***
```

**Comment by avida** [comment]
Fixed as #9082 have been merged
