### ISSUE TITLE
🐛 Logs print SLF4J warn as errors

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9093]
_Is this your first time deploying Airbyte:_ no
_OS Version / Instance:_ Linux EC2 m5.2xlarge
_Deployment:_ Docker
_Airbyte Version:_ 0.34.1-alpha
_Source:_ MySQL 0.5.1
_Destination_: Snowflake 0.3.21
_Description:_

```SLF4J
...
destination - 2021-12-18 23:05:00 ERROR () LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.16.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
destination - 2021-12-18 23:05:00 ERROR () LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```

All of our connections failing now

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1639867371003400?thread_ts=1639867371.003400&cid=C01MFR03D5W

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126595449855) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment]
Our logs are printing SLF4J as ERROR in sync. See screenshot, my sync was successful but the ERROR are printed.
![image](https://user-images.githubusercontent.com/5154322/147290520-14e3d17f-b247-45e7-890a-2aa37c28915e.png)

**Comment by danavatavu** [comment]
Is this your first time deploying Airbyte: no
OS Version / Instance: AWS EKS
Deployment: Kubernetes
Airbyte Version: 0.35.3-alpha
Source: Snowflake
Destination: Snowflake 
Description:  Sync jobs succeed but errors are appearing in logs:
ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Class path contains multiple SLF4J bindings.
ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.16.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
ERROR i.a.c.i.LineGobbler(voidCall):82 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

**Comment by thisisile** [comment]
I am getting the same error.
