### ISSUE TITLE
Can airbyte connectors be used individually to read data from source?

### ISSUE THREAD

**Issue by secretlyvogon** [airbytehq/airbyte#9102]
As per [AIrbyte's documentation](https://docs.airbyte.io/understanding-airbyte/airbyte-specification), each connector is defined as a docker container which implements certain functions. For the source connector, the `read()` command should output a stream of messages to STDOUT. 

I have been trying out the postgres source connector and I was successfully able to run the `spec()` and `check()` commands to obtain a JSON string in the console output. However, when I ran the `read()` function, I only see the logs and I am unable to find the message stream in the console logs. The docs mention that the container outputs it to STDOUT. I am unsure how to read from STDOUT. 

The doc indicates that the message stream can be stored to a file by running the command like:

```
docker run --rm -i airbyte/source-postgres:0.3.17 read --config <config-file-path> --catalog <catalog-file-path> > message_stream.json
```
However, the file only contains logs which I can anyway see from the docker logs output. 
Can you help me find the JSON message stream?

**Comment by misteryeo** [comment]
Hi @secretlyvogon closing this out as this isn't the forum for asking questions. Please redirect your question to https://discuss.airbyte.io/
