### ISSUE TITLE
Remove support for Kustomize

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9108]
## Tell us about the problem you're trying to solve
Helm is much more highly used and is more widely adopted by the K8s community. Kustomize hasn't been an ergonomic way to use Airbyte. Helm has been easier to use and more widely adopted by our community. For now, we prefer to provide excellent support to one tool

**Comment by TSkrebe** [comment]
>Kustomize hasn't been an ergonomic way to use Airbyte. 
Can you please expand on this point?
>Helm has been easier to use and more widely adopted by our community.
I disagree. I've tried to use both and kustomize was hands down easier to operate. Helm char is not published, chart versions are not bumped upon changes, not possible to do easily extend manifests e.g. add custum serviceaccount name for all deployments.

**Comment by cpdeethree** [comment]
This was completed as part of the platform monorepo project
