### ISSUE TITLE
Version and Publish Helm Charts

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9109]
## Tell us about the problem you're trying to solve
Currently are helm charts are un-versioned. We want to version them and then push them to a public repository where one can pull them with `helm install`.

@jrhizor @davinchia do you know where we want to push our helm charts to? Or does that require some investigation?

**Comment by cgardens** [comment]
@davinchia goal is for the infra team to tackle this one.

**Comment by jrhizor** [comment]
There are some ideas in https://github.com/airbytehq/airbyte/issues/1868 but we still need to choose.

**Comment by jrdzha** [comment]
I am interested in testing out Airbyte. Is there any ETA on publishing the helm chart?

**Comment by nhuray** [comment]
@cgardens I would be also interested to deploy Airbyte on our Kubernetes cluster using Helm. What can we do to help to move forward ?

**Comment by cpdeethree** [comment]
This was completed since ~Q3 of last year https://github.com/airbytehq/helm-charts
