### ISSUE TITLE
Refactor Cloud to inherit / override from OSS Helm images

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9110]
## Tell us about the problem you're trying to solve
Cloud currently has its own set of helm charts (even for OSS components of the project). We want to leverage the OSS helm charts (once they have been improved) to improve the reliability and decrease the maintenance cost of Cloud and helm.

**Comment by cgardens** [comment]
@davinchia goal is for the infra team to tackle this one.

**Comment by cpdeethree** [comment]
This was taken care of as part of the monorepo project
