### ISSUE TITLE
[EPIC] Helm Charts V2

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9111]
## Tell us about the problem you're trying to solve
* The goal of this project is to knock out high priority improvements to our helm / K8s offering

## Projects
* https://github.com/airbytehq/airbyte/issues/9107 (BE)
* https://github.com/airbytehq/airbyte/issues/9108 (BE)
* https://github.com/airbytehq/airbyte/issues/9109 (Infra)
* https://github.com/airbytehq/airbyte/issues/9110 (Infra)

@davinchia I labelled my understanding of who is doing what. Can you confirm please?

**Comment by davinchia** [comment]
The last 2 issues are somewhat big - I think they can be broken down more. Apart from that, this is correct. Will work with the infra team to figure it out.
