### ISSUE TITLE
Billing Cron should be able to handle deleted configs

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#9128]
Right now if a config such as a source/destination connection or a standard sync is deleted from DB then the billing cron would break cause of ConfigNotFound exception. This is possible when a connection was created, it ran few jobs and then it was deleted from DB, the billing cron would start and try to find the details of this connection but fail. This should be handled gracefully.

**Comment by michel-tricot** [comment]
Shouldn't tombstones instead of deletion fix that?

*Michel Tricot*
Co-Founder & CEO @ Airbyte <https://airbyte.io/>
+1 415-307-4864
GitHub <https://github.com/airbytehq/airbyte> | LinkedIn
<https://www.linkedin.com/in/micheltricot/>

**Comment by jrhizor** [comment]
I thought I fixed this as part of https://github.com/airbytehq/airbyte/pull/8355

Was it happening somewhere else?

**Comment by cgardens** [comment]
@subodh1810 I think because we tombstone configurations this should actually not be a problem. The issue in the dev environment is that some records had been deleted manually (something we don't do in prod). I'm going to close it, but let me know if you think I'm missing a case.
