### ISSUE TITLE
New Source Bing Webmaster

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9130]
## Tell us about the problem you're trying to solve
I want to ingest data from https://www.bing.com/webmasters

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by fev4** [comment]
We would like to see this as well. It would be useful in order to compare growth metrics between Google Search Console and Bing Ads. Not having this data forces us to use manual extracts from Bing Webmaster, which is not desirable.

**Comment by spunzon** [comment]
It would be really nice to hace this source on Airbyte.
