### ISSUE TITLE
Source Salesforce: REST API reads only 1000 records from some streams

### ISSUE THREAD

**Issue by augan-rymkhan** [airbytehq/airbyte#9136]
## Environment
- **Airbyte version**:  0.35.2-alpha
- **OS Version / Instance**: *
- **Deployment**: *
- **Source Connector and version**: Source Salesforce 0.1.12
- **Destination Connector and version**: *
- **Severity**: High 
- **Step where error happened**: Sync job

## Current Behavior
There is an issue with pagination in REST API streams, it reads only 1000 records for some streams. Different streams return different records count in the response for the REST api call (records count per api call). Our current [implementation](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L52) expects that, each REST API call response will contain 2000 records (because we limit by [page_size](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L24)) in the body if end of records is not reached.

![image](https://user-images.githubusercontent.com/93112548/147545311-bb5cdd6e-671a-41bd-b6c3-76630bf2c775.png)
While BULK API reads 10101 records from the same stream (**Note**):
![image](https://user-images.githubusercontent.com/93112548/147545364-cb739174-b698-47a5-95b1-2fc9dc878bb7.png)

## Expected Behavior
It should read all records.

## Steps to Reproduce
1. Choose Note stream and REST API

## Are you willing to submit a PR?
Yes

**Comment by augan-rymkhan** [comment]
![image](https://user-images.githubusercontent.com/93112548/147529770-aeefe47b-8415-409c-a806-91b9c95a602a.png)

Salesforce returns 1000 records, but self.page_size = 2000
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L300

**Comment by augan-rymkhan** [comment]
I found that some streams have problem with native pagination on Salesforce side (REST API version).
For example:
Stream: `PermissionSetTabSetting`
TotalSize: 17513
Actual returned records: 4780

The problem is [totalSize](https://developer.salesforce.com/docs/platform/functions/guide/recordqueryresult) returned in result does not always match to the actual number of records returned.

![image](https://user-images.githubusercontent.com/93112548/147681742-d4fef6f0-4999-4bd1-8c86-cc24b13ddb93.png)

Today I also found that, BULK API reads 4780 records from **PermissionSetTabSetting** stream too.
So, I decided to complete implementation provided in PR [9151](https://github.com/airbytehq/airbyte/pull/9151).

**Comment by augan-rymkhan** [comment]
I tried to write to Salesforce Support about native pagination issue on Salesforce side, described in the comment above.
But I faced this error on https://help.salesforce.com/s/manage-all-orgs. 
![image](https://user-images.githubusercontent.com/93112548/147775454-9040d650-7a25-4e48-8da8-68e77095ff0b.png)

**Comment by augan-rymkhan** [comment]
I wrote to Salesforce Support about incorrect `totalSize` field in native pagination on 5 January. But they did not response yet.

![image](https://user-images.githubusercontent.com/93112548/149376019-8d3160a7-9cb8-4280-b648-f3c37445bfdb.png)

**Comment by sherifnada** [comment]
@augan-rymkhan I don't understand the tradeoff here - are you saying the PR does not fix the issue and that we need SF to respond? or that the PR fixes the issue but is a bad way of fixing it? From my POV I care the most about fixing the bug with the REST stream however it can be done.

**Comment by augan-rymkhan** [comment]
@sherifnada [PR](https://github.com/airbytehq/airbyte/pull/9151) fixes this issue proper way [recommended](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_query.htm) by the SF docs, only I wanted to be sure that we can rely on native pagination on Salesforce side.
I can move this to Code Review stage and merge if you're ok.
