### ISSUE TITLE
Source Stripe: add stream `accounts`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9167]
## Tell us about the problem you're trying to solve
Add new stream: https://stripe.com/docs/api/accounts
Requested by [slack convo](https://airbytehq-team.slack.com/archives/C019WJFR1JT/p1640717898117200)

## Describe the solution you’d like
This endpoint is important to a community user.

## Describe the alternative you’ve considered or used
Don't have

## Are you willing to submit a PR?
Not this time.

**Comment by jagannathsrs** [comment]
Is this being worked on or can I contribute? We have a requirement for this stream and would like to sync this asap.

**Comment by misteryeo** [comment]
@jagannathsrs not currently being worked on - would love for you to contribute!

**Comment by YowanR** [comment]
Hello! We expect this stream to be incremental :)

**Comment by haithem-souala** [comment]
Hey @YowanR, i would like to work on this one!

**Comment by YowanR** [comment]
Awesome, @haithem-souala ! Assigned the issue to you and looking forward to your contribution! 💪

**Comment by haithem-souala** [comment]
Hey @YowanR, the PR is ready for review.
