### ISSUE TITLE
🐛 Source confluence not available

### ISSUE THREAD

**Issue by tuanchris** [airbytehq/airbyte#9171]
## Environment
- **Airbyte version**:  0.32.4-alpha
- **OS Version / Instance**: example macOS
- **Deployment**: local
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
![image](https://user-images.githubusercontent.com/52090179/147626898-20c53064-b3d0-4c82-add5-fc0f0236a96a.png)

## Expected Behavior
Source Confluence should be available https://docs.airbyte.io/integrations/sources/confluence

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by alafanechere** [comment]
@harshithmullapudi it looks like you merged this connector but `Confluence` is not part of our `source_definitions.yaml` nor `source_spec.yaml`. Could you take care of adding Confluence to make the connector available in the UI? Let me know if it's not an oversight on your part and it was not added on purpose.

**Comment by harshithmullapudi** [comment]
https://github.com/airbytehq/airbyte/pull/9831
