### ISSUE TITLE
🐛 Source MariaDB: CDC DDL statement couldn’t be parsed

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9196]
*Is this your first time deploying Airbyte*: No
*OS Version / Instance*: Amazon Linux 2
*Memory / Disk*: 4Gb / 32 GB SSD
*Deployment*: Docker
*Airbyte Version*: 0.32.8-alpha
*Source name/version*: MariaDB 10.4.21 using mysql:0.4.11
*Destination name/version*: Postgres 13.3 using  postgres:0.3.12
*Step*: On sync
*Description*: The third scheduled sync throws errors and the process doesn't finish. I had enabled CDC. Retention logs configured for 168 hrs on read replica.

The error is: `Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'flush table'`

### Logs: 
[Untitled (1).txt](https://github.com/airbytehq/airbyte/files/7793966/Untitled.1.txt)

[Slack conversation
]( https://airbytehq.slack.com/archives/C01MFR03D5W/p1640819144485300?thread_ts=1640819144.485300&cid=C01MFR03D5W)

**Comment by grishick** [comment]
We have upgraded Debezium to 1.9+ from 1.4+ and need to confirm this issue is still happening.

**Comment by grishick** [comment]
Todo @grishick get in touch with Diana Paredes, who mentioned the issue in Airbyte Slack to confirm if this is still an issue

**Comment by grishick** [comment]
I have asked GL Java team to test MariaDB: https://github.com/airbytehq/airbyte/issues/15836

**Comment by grishick** [comment]
PMed Diana on Slack

**Comment by fcatanzaro** [comment]
Same error in MySQL on 0.40.17 with latest mysql connector.  
"DDL statement couldn't be parsed"  Was working but now it crashes when trying to parse the definition of a recently changed view.

**Comment by michaelsonnle** [comment]
+1 we have the same error in mysql (1.10.13), airbyte version 0.40.22 with a stored procedure. 

`io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'CREATE DEFINER= mm-lop@%PROCEDURE getPickingOrderData`

@grishick is there any workaround?

**Comment by jan-benisek** [comment]
+1 We have the same for `mysql`
```io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'CREATE ALGORITHM=UNDEFINED DEFINER=`master`@`%` SQL SECURITY DEFINER VIEW `foo` AS select
```
Airbyte 0.40.23, mysql 1.0.15

**Comment by michaelsonnle** [comment]
Are there any news?

**Comment by michaelsonnle** [comment]
Hey @marcosmarxm & @grishick ,

can you please take another look at this? 
The problem seems to be related to Debezium. We often struggle because we have several stored procedures, which also have to be adjusted frequently. 
Then the connection no longer works at all. Unfortunately, the ticket has been open for a year now and there is no solution.

This is a great pity because it probably affects several users.

**Comment by samzhao2008** [comment]
Still happens for mysql. 
```
Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`xxx`@`%` SQL SECURITY DEFINER VIEW `v_query_log` AS select...
```
airbyte: 0.50.39
MySQL v3.3.0

The connection stops working. Data stops syncing. In my opinion, creating views is a very normal operation. If every time when a view is created, and then the connection stops working, it would be very painful to use this tool. Is there any workaround?

**Comment by michaelsonnle** [comment]
Hey @marcosmarxm & @grishick ,

this still happens for mysql:

`Caused by: io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'CREATE DEFINER=`mm-lop`@`%` PROCEDURE `getOrderData`(`

airbyte: 0.63.4
MySQL: 3.4.12

Is there any workaround?

**Comment by marcosmarxm** [comment]
@airbytehq/jdbc-connectors it is affecting users (MariaDB and MySQL) can someone take a look?

**Comment by marcosmarxm** [comment]
It looks user was able to [workaround](https://airbytehq.slack.com/archives/C054V9JFTC6/p1721193291507279?thread_ts=1720800276.173229&cid=C054V9JFTC6):
yeah but the same issue is affecting mysql connector as well
For now to solve this I have modified the source code of source-mysql connector to include following debezium config as well
`database.history.skip.unparseable.ddl='true'`

**Comment by abhisheksingh94** [comment]
I was able to fix this by adding 'schema.history.internal.skip.unparseable.ddl' = true in the source-mysql/src/main/java/io/airbyte/integrations/source/mysql/cdc/MySqlCdcProperties.java file and building the connector again using airbyte-ci 

lets hope there's some official fix from Airbyte Dev themselves
