### ISSUE TITLE
🐛 Source Jira: custom attributes do not have context leading to 404 errors

### ISSUE THREAD

**Issue by ian-masters** [airbytehq/airbyte#9218]
## Environment
- **Airbyte version**: 0.35.2-alpha
- **OS Version / Instance**: Ubuntu 18.04.6 LTS
- **Deployment**: Docker
- **Source Connector and version**: Jira 0.2.18
- **Destination Connector and version**: local-csv 0.2.8
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Set up the source and destination. Click sync on the onboarding page. It spends about 10 minutes syncing and I see files and content in the destination directory for the csv destination so it's pulling some data. It runs through the 3 attempts and each one fails with the exception in the logs below.

## Expected Behavior
Successful sync

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

[logs-3-2.txt](https://github.com/airbytehq/airbyte/files/7793309/logs-3-2.txt)

</details>

## Steps to Reproduce
1. https://docs.airbyte.io/quickstart/deploy-airbyte
2. Add the jira source
3. Add the local-csv destination
4. Press sync now on the onboardnig page

## Are you willing to submit a PR?

No

**Comment by ian-masters** [comment]
Think I've narrowed this down a bit. I think it errors out on custom fields with PROJECT scope. We have 3 of them which are defined as:

```
    {
        "id": "customfield_10043",
        "key": "customfield_10043",
        "name": "As a...:",
        "untranslatedName": "As a...:",
        "custom": true,
        "orderable": true,
        "navigable": true,
        "searchable": true,
        "clauseNames": [
            "As a...:",
            "As a...:[Short text]",
            "cf[10043]"
        ],
        "scope": {
            "type": "PROJECT",
            "project": {
                "id": "10007"
            }
        },
        "schema": {
            "type": "string",
            "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textfield",
            "customId": 10043
        }
    },
```

The failing api call can be reprod in postman with a GET to:

```
https://hadean.atlassian.net/rest/api/3/field/customfield_10043/context
```

Which returns:

```
{
    "errorMessages": [
        "The custom field was not found."
    ],
    "errors": {}
}
```

And a 404. The project that it's scoped to is not the project that I'm trying to sync

**Comment by ian-masters** [comment]
Confirmed. I deleted the 3 fields from our Jira instance and I now get a successful sync. This is fine for me as a workaround for now.

The project they belonged to is Team-managed so any custom attributes you add are only valid within the project. This means they don't have a context so the field/*/context api call doesn't make sense for them and the 404 back from Jira I think is the correct response.

**Comment by alafanechere** [comment]
Thank you for the investigation @ian-masters and the workaround solution, our team will look into it.

**Comment by JCWahoo** [comment]
Any updates here? Setting custom fields in source config doesnt appear to have any impact on the integration

**Comment by marcosmarxm** [comment]
Jeff I added the issue to Connector team backlog to their prioritization.

**Comment by JCWahoo** [comment]
Thanks - I'm not getting any errors as above, just curious of custom  fields should be working or not?

**Comment by grubberr** [comment]
This PR https://github.com/airbytehq/airbyte/pull/20128 has to resolve this issue
