### ISSUE TITLE
Source Prestashop: Failed with Integration Tests

### ISSUE THREAD

**Issue by yevhenii-ldv** [airbytehq/airbyte#9222]
## Environment
- **Prestashop connector**:  version 0.1.0
- **Severity**: Medium
- **Step where error happened**: SAT tests

## Current Behavior
*Failed.*

## Expected Behavior
*Successfully pass.*

## Are you willing to submit a PR?
Yes

**Comment by grubberr** [comment]
I think now this issue can be closed
https://github.com/airbytehq/airbyte/actions/runs/3469884419 - PASSED

**Comment by grubberr** [comment]
This issue already not actual
Connector was re-written with Low-code CDK
Last working build here: https://github.com/airbytehq/airbyte/actions/runs/3469884419
