### ISSUE TITLE
🐛 Call-heartbeat-server container is getting OOMKilled

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#9233]
## Environment
- **Airbyte version**:  0.35.2-alpha
- **OS Version / Instance**: linux
- **Deployment**: kubernetes
- **Source Connector and version**: mongo 0.1.9
- **Destination Connector and version**: bigquery 0.6.1
- **Severity**: Critical
- **Step where error happened**: In the middle of the sync

## Current Behavior
call-heartbeat-server container is getting OOMKilled. That happens with both source and destination connectors.

Previous memory bump PR for posterity: https://github.com/airbytehq/airbyte/pull/8727

## Expected Behavior
No OOMKills via increased defaults, configurable envvars or updating call-heartbeat-server behaviour.

## Logs
```
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 30 Dec 2021 18:42:04 +0200
      Finished:     Thu, 30 Dec 2021 18:44:08 +0200
```

![Screenshot 2021-12-31 at 08 21 42](https://user-images.githubusercontent.com/4008242/147807270-6520209d-8f99-45bf-8fe9-1459d2599108.png)

## Steps to Reproduce
We only noticed this when we tried to move data from our production DB which have much more records then our test DB. 

Collection document count: 366K
Collection size: ~1GB

## Are you willing to submit a PR?
no, too little context

**Comment by alafanechere** [comment]
@davinchia do you think we can expose `DEFAULT_SIDECAR_RESOURCES` as an env var?

**Comment by TSkrebe** [comment]
Yes, that's one of the workarounds I'm suggesting. Although, it feels like this is internal part of airbyte that should not be exposed to the client.

I haven't looked into code but if container's memory usage somehow depends on the connector, then having static limits is a wrong approach (even if I can configure it through env vars) and might lead to severe memory over allocation.

**Comment by davinchia** [comment]
Let's increase it. I don't want to make it injectable yet since this really shouldn't be changing much.

@TSkrebe can you describe the type of data you are syncing? Are you perhaps syncing data with fat rows?

**Comment by TSkrebe** [comment]
@davinchia
largest row (mongo json document) is at 15.8KB, avg at ~ 3KB.

**Comment by TSkrebe** [comment]
Tested with a new version and it works 🎉 

_Call-heartbeat-server_ memory usage was steadily increasing in the first two minutes and reached 28.6 MiB. After that it remained flat.
