### ISSUE TITLE
Expose the Airbyte API in a separate ingress in K8s

### ISSUE THREAD

**Issue by Javier162380** [airbytehq/airbyte#9247]
## Tell us about the problem you're trying to solve
What are you trying to do, and why is it hard? A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by alafanechere** [comment]
@Javier162380, could you please edit the description to add a bit of detail and context related to this request?

**Comment by marcosmarxm** [comment]
Close due lack of information.
