### ISSUE TITLE
Document allowable table and field names

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#925]
## Tell us about the documentation you'd like us to add or update
We only officially support table and field names which contain alphanumeric or underscore characters. other names might work but it is highly destination dependent.

**Comment by cgardens** [comment]
# Rules
* Source names must be unique. Will be prepended to output tests
* Sync Worker enforces
  * unicode, alphanumeric, lower case
  * key collision, it picks one
* Discover warns about rule violations
  * nice to have: discovery says what name will map to

**Comment by michel-tricot** [comment]
can you add `_` to the pattern?

**Comment by sherifnada** [comment]
Documentation merged in #968

**Comment by sherifnada** [comment]
#972 #954 and #973 have been created to track non-docs items on this. Closing this issue.
