### ISSUE TITLE
When refreshing a schema do not automatically select all tables and reset existing ones.

### ISSUE THREAD

**Issue by pcothenet** [airbytehq/airbyte#9256]
## Tell us about the problem you're trying to solve

I am replicating about 50 tables, with some of them failing for reasons unknown. Therefore, I am adding tables one by one. 
- Once a table works, I'm not touching it and want it to continue replicating incrementally. I don't want to reset it.

Currently, adding a new table requires refreshing the schema:
- All tables in the schema get selected by default (even ones that I had deliberately unselected)
- This forces a reset of all tables

## Describe the solution you’d like

When refreshing the schema in the UI:
- Do not select all new tables by default
- Remember which tables were deliberately not selected
- Do not force resets if I'm only adding new tables

## Describe the alternative you’ve considered or used

I'm using the API to add my tables one by one (with a combination of `/v1/sources/discover_schema` and `/v1/connections/update`) without resetting their state.

## Additional context

Some tables are failing full replication (for an unrelated reason) so I do not want to reset them every time

## Are you willing to submit a PR?

This seems a little too much part of the core UX ;-)

**Comment by marcosmarxm** [comment]
Thanks for requesting this @pcothenet, could you read this issue about the schema evolution project? https://github.com/airbytehq/airbyte/issues/6912
Let me know if you think is a duplicate.

**Comment by pcothenet** [comment]
@marcosmarxm it is pretty related yes. But without even thinking about resetting the schema, it would be nice if the UI could remember which table you did not select. Today, it only saves the table you selected. And when you refresh, adds them all automatically.

**Comment by marcosmarxm** [comment]
@timroes this issue is solved now, correct?

**Comment by octavia-squidington-iii** [comment]
cc @airbytehq/frontend

**Comment by timroes** [comment]
The UI issue described here is solved nowadays and the reset of unnecessary tables is addressed via https://github.com/airbytehq/airbyte/issues/6912
