### ISSUE TITLE
Cannot look at logs when test connection fails

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9257]
https://user-images.githubusercontent.com/9092207/147977403-7bb8088b-2496-4821-9690-422b5afbf002.mp4

## Environment
- **Airbyte version**:  cloud

## Current Behavior
* after i click "retest destination" and get a connection failure, if i attempt to click on the logs, i get an error.

@Jamakase @jrhizor

**Comment by Jamakase** [comment]
It looks like some unexpected response was returned from backend.

@cgardens could you please attach a response from the backend as it will ease figuring out what exactly is wrong.
