### ISSUE TITLE
Bump all python modules to 3.10

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9258]
## Tell us about the problem you're trying to solve
Python 3.7 doesn't have M1 docker images, which makes it difficult to work with for any new engineers coming onto Airbyte. 3.10 doesn't suffer from this problem and is backwards compatible, so there should be no problem with migrating our current python connectors to that one. 

## Describe the solution you’d like
Python 3.10 in all Docker images

**Comment by sherifnada** [comment]
related discussion: https://airbytehq.slack.com/archives/C02LM2R4R6E/p1638465597178000

**Comment by noahkawasakigoogle** [comment]
I'm working on a related [PR](https://github.com/airbytehq/airbyte/pull/9230/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R136) that could help out in this case. 

Once this merges I can refactor all the python integrations to read from `.python-version`, like the Java based integrations using `JDK_VERSION`. Python ones can go `FROM python:${PYTHON_VERSION}`. This would actually get all connectors and airbyte core in-sync on the same python version. Would probably super nice long-term and reduce confusion from different people using different versions.

**Comment by davinchia** [comment]
we decided to bump this to 3.9. see https://github.com/airbytehq/airbyte/issues/11657 for context
