### ISSUE TITLE
Normalization fails on Hubspot to Postgres

### ISSUE THREAD

**Issue by flotenva** [airbytehq/airbyte#9264]
[logs-17-0.txt](https://github.com/airbytehq/airbyte/files/7804831/logs-17-0.txt)
## Environment
- **Airbyte version**:  0.35.0-alpha
- **OS Version / Instance**: Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type
- **Deployment**: Docker
- **Source Connector and version**: Hubspot 0.1.29
- **Destination Connector and version**: Postgres 0.3.13
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
I am getting the following error (attached below) when syncing HubSpot data to our Postgres database. There seems to be an issue with normalization.

## Expected Behavior
*Tell us what should happen.*

## Logs

<details>
<summary>LOG</summary> 

```
2022-01-03 23:59:51 normalization > 23:59:51 | Finished running 19 table models in 666.79s.
2022-01-03 23:59:51 normalization > 
2022-01-03 23:59:51 normalization > Completed with 1 error and 0 warnings:
2022-01-03 23:59:51 normalization > 
2022-01-03 23:59:51 normalization > Database Error in model line_items_properties (models/generated/airbyte_tables/airbyte_hubspot/line_items_properties.sql)
2022-01-03 23:59:51 normalization >   date/time field value out of range: "1743465600000"
2022-01-03 23:59:51 normalization >   HINT:  Perhaps you need a different "datestyle" setting.
2022-01-03 23:59:51 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/airbyte_hubspot/line_items_properties.sql
2022-01-03 23:59:51 normalization > 
2022-01-03 23:59:51 normalization > Done. PASS=18 WARN=0 ERROR=1 SKIP=0 TOTAL=19
```
</details>

## Steps to Reproduce
1.
2.
3.

**Comment by marcosmarxm** [comment]
The root cause is because a field in Hubspot stream is declared as date-time or timestamp but isn't.

**Comment by flotenva** [comment]
I've noticed that my issue with normalization of the line_items_properties model may be related to this other previously reported bug:
https://github.com/airbytehq/airbyte/issues/6592

**Comment by keu** [comment]
this ticket will also close #6592 (no need to reproduce)
Plan of attack:
- run SAT and verify that schema is correct
- check that columns from the logs (with errors) contain data, add data if necessary
- reproduce issue by creating hubspot + postgres connection

**Comment by yevhenii-ldv** [comment]
@keu I moved according to your plan, and the following came out:
- [ ] run SAT and verify that schema is correct  - SAT tests pass perfectly and without errors. The scheme is correct both for the main values of this stream and for additional properties.
- [ ] check that columns from the logs (with errors) contain data, add data if necessary - Values for this stream existed before, and today I added another new value and tried to fill in additional properties for it as much as possible. As a result, all the same it was not possible to receive the data with a similar error.
- [ ] reproduce issue by creating hubspot + postgres connection - Both of my syncs were successful.
![image](https://user-images.githubusercontent.com/34103125/149964065-d838a374-dcfd-494c-9c90-7363bb2fafe6.png)

**Comment by sherifnada** [comment]
it seems the `line_items_properties` there is a field which is a date/time type, but is not actually readable as this type because the value is too big? `1743465600000`

**Comment by flotenva** [comment]
Hi Augan and sorry for the late reply.
I had a chance to look at the data in the '_airbyte_raw_line_items' table where, I believe, the raw data gets stored before it is normalised to produce the 'line_items_properties' table that is throwing the error in Airbyte. I found the value that triggered the 'out of range' error and it belongs to the field:
-  hs_recurring_billing_end_date
I had a look at the actual Line Item in HubSpot and that field contains future dates (e.g. 07/02/2024)
Hope that helps

**Comment by augan-rymkhan** [comment]
@flotenva Thanks this helped me to reproduce the issue.
I am working on the solution.
![image](https://user-images.githubusercontent.com/93112548/155150271-92ba9262-f323-45ca-b70b-dddcd369db4f.png)

**Comment by augan-rymkhan** [comment]
@flotenva It was fixed in version 0.1.43
Could you check with this version?

**Comment by flotenva** [comment]
Hi @augan-rymkhan,
I ran a sync with HubSpot 0.1.44 but it got stuck at the following:
`2022-02-24 22:32:09 destination > 2022-02-24 22:32:09 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):131 - Preparing tables in destination completed.`

I realised this was already happening with a previous version of the connector (HubSpot 0.1.42). 

`Reset your data` works fine but when running a `Sync now`, it reaches the `Preparing tables in destination completed.` step and then it gets stuck. For this specific connection, I am only syncing the following streams (HubSpot Sales):
- deal_pipelines
- deals
- line_items
- products
- quotes

I have attached the logs. I stopped the process after around 45 minutes of getting stuck at that step - you can see the timestamp difference between line 50 and line 51 in the logs.

[logs-96.txt](https://github.com/airbytehq/airbyte/files/8137255/logs-96.txt)

I have tried deleting all tables in the database prior to doing a `Reset your data` but, it fails when syncing data. 

I let a previous sync attempt run until failure (with version 0.1.42) and it went on for 17h 30m until I cancelled it - so something is not working as intended.

**Comment by flotenva** [comment]
Hi @augan-rymkhan,
I forgot to mention on my previous message that I have got another HubSpot connection with HubSpot CRM-related streams (Contacts, Companies, etc) and it is working fine.

**Comment by augan-rymkhan** [comment]
@flotenva Hi, I have run sync with the streams below, it works for me. 
source-hubspot:0.1.44

![image](https://user-images.githubusercontent.com/93112548/155655523-9f50f077-c7a0-42e6-b66f-ba4c88ed8913.png)

- deal_pipelines
- deals
- line_items
- products
- quotes

Did you try sync with version source-hubspot: 0.1.43  ? if not can you try it? and let me know thanks

**Comment by flotenva** [comment]
Hi @augan-rymkhan,
I have tried syncing data for each of those streams separately... and I am only getting the issue I mentioned previously with the DEALS stream. No issues with the other stream including the line_items stream.

**Comment by augan-rymkhan** [comment]
@flotenva Can you run the sync without normalization only DEALS stream?
What is the chosen sync mode?

**Comment by augan-rymkhan** [comment]
@flotenva Could you run the sync only `deals` with hubspot version **0.1.41**  ?

In version **0.1.42** `deals` stream schema was changed in PR [10492](https://github.com/airbytehq/airbyte/pull/10492/files). This change might broke that stream.

**Comment by augan-rymkhan** [comment]
@flotenva Can you open a new issue related to **DEALS** stream gets stuck?

**Comment by flotenva** [comment]
Hi @augan-rymkhan ,
I can confirm that the Sync Data for DEALS stream also fails when set to 'Raw data - no normalization'.

**Comment by flotenva** [comment]
It seems the issue with DEALS stream has already been reported https://github.com/airbytehq/airbyte/issues/10544
