### ISSUE TITLE
Support connector configuration via environment variables

### ISSUE THREAD

**Issue by reubano** [airbytehq/airbyte#9267]
## Tell us about the problem you're trying to solve

Configuring connectors is quite cumbersome

## Describe the solution you’d like

I would like to be able to configure connectors via environment variables

## Describe the alternative you’ve considered or used
Copy/paste

## Additional context

[Meltano](https://docs.meltano.com/guide/configuration#configuration-layers) looks for configuration values in

- Environment variable
- meltano.yml project file
- project's system database
- parent plugin's own configuration
- default plugin's value

## Are you willing to submit a PR?
sure

**Comment by marcosmarxm** [comment]
Thanks for requesting this @reubano. @alafanechere is working in the Airbyte CLI, which can achieve some of features you're requesting.

**Comment by alafanechere** [comment]
Hi @reubano, if you want more details about this project feel free to have a look at this [deck](https://docs.google.com/presentation/d/10RjkCzBiVhCivnjSh63icYI7wG6S0N0ZIErEIsmXTqM/edit?usp=sharing).

**Comment by reubano** [comment]
Thanks @alafanechere! Where should i put my comments/suggestions?

**Comment by alafanechere** [comment]
> Thanks @alafanechere! Where should i put my comments/suggestions?

Feedback is welcomed as comments on the deck.

**Comment by marcosmarxm** [comment]
I'm not closing this because is different from Octavia CLI.

**Comment by evantahler** [comment]
Re-tagging this to `area/ocatvia-cli`.  For now, the path forward for using environment variables to set up a connector would be to allow for variables in Octavia's config files, and then apply those changes.  Due to the way we run Airbyte (e.g. lots of docker containers), there's not a per-connection way to pass environment variables easily to a container.

**Comment by marcosmarxm** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/4035
