### ISSUE TITLE
🐛 Source Delighted: Date Range being Skipped

### ISSUE THREAD

**Issue by Zirochkaa** [airbytehq/airbyte#9273]
Subtask for #8906.

## Current Behavior
Also it is seen that data between certain time period is skipped. For ex: Data between november 2020 to august 2021 is skipped in the syncs While connecting to the API directly, was able to confirm data do exists for that time frame.

## Expected Behavior
Data with a certain Created date range is being skipped which it should not.

## Are you willing to submit a PR?
Yes.

**Comment by Zirochkaa** [comment]
Hi @tredencegithub, I investigated this issue, and I can't reproduce it. I checked all 4 streams. I checked how they work with `since` parameter (when you set up the connector) and how they work with the state, in each case each stream was working fine all data was synced without any gaps.
Could you please upgrade delighted source to version `0.1.2` and try again?
Looking forward to your feedback.

**Comment by tredencegithub** [comment]
@Zirochkaa The data looks good on the table after connector upgrade.
