### ISSUE TITLE
Snowflake destination connection check should verify the schema exists

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#928]
## Tell us about the problem you're trying to solve
Snowflake succeeds it connection check even if the schema does not exist.

**Comment by sherifnada** [comment]
This is potentially a problem with BQ and Postgres -- i haven't checked

**Comment by zzstoatzz** [comment]
@sherifnada in this same vein, syncs do not fail when the configured snowflake role does not have the correct privileges to access a given schema/table. From what I've seen, it hangs indefinitely with status `Running`. Here are the logs from a run where I saw this - let me know if I can provide more context.


[logs-3-0.txt](https://github.com/airbytehq/airbyte/files/6888046/logs-3-0.txt)

**Comment by sherifnada** [comment]
connector now creates schema if it doesn't exist
