### ISSUE TITLE
Configuration import: an import error is not displayed in the UI.

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9287]
## Environment
- **Airbyte version**: 0.35.3-alpha
- **OS Version / Instance**:  Ubuntu 20.04
- **Deployment**: Docker
- **Severity**: Medium 
- **Step where error happened**: Import of a config dump to a new Airbyte instance

## Current Behavior
When two versions are incompatible the import of a config dump shows an error in the server logs that is not displayed in the UI.
This problem was mentioned in [this slack conversation](https://airbytehq.slack.com/archives/C01MFR03D5W/p1641307052149900).
## Expected Behavior
Show an import error in the UI.

## Logs
[server-logs (2).txt](https://github.com/airbytehq/airbyte/files/7809380/server-logs.2.txt)

## Steps to Reproduce
1. Export configuration from an "old" Airbyte version
2. Import configuration into a newer Airbyte version

**Comment by harshithmullapudi** [comment]
Hey @alafanechere I understand this problem but isn't it like we have to import in the same version and then upgrade so that it does automatic migration?

**Comment by alafanechere** [comment]
@harshithmullapudi the problem is just that this error is not sent back to the user in the front-end making it "silent" and the users are unaware of what actions they could take to fix this.

**Comment by edmundito** [comment]
Won't fix. Feature to be removed in #16403
