### ISSUE TITLE
Spec out how to make Check and Discover operations faster.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#9303]
## Tell us about the problem you're trying to solve
Depending on the endpoint, and schema being discovered, this can take anywhere from 10 seconds to a minute today.

This is too slow for Cloud users. We want to speed this up to an operation that completes within Y seconds (arbitrarily set at 10 seconds for now).

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment]
https://docs.google.com/spreadsheets/d/1SxMMQZxzq7eJWMdpG9wTX0flT74VpIT7V_TwcPrkUrM/edit?usp=sharing

**Comment by cgardens** [comment]
[Go Forward Plan from Davin](https://docs.google.com/document/d/1-2tbNaI3mnq5Bx5xfD11lTMbfP5Go1VUwFCiuU8L-hk/edit#heading=h.uv0c9sk66qdt)

**Comment by jrhizor** [comment]
related: https://github.com/airbytehq/oncall/issues/119

**Comment by davinchia** [comment]
This is done. Closing this for follow up work in the linked issues.
