### ISSUE TITLE
Source Orb: New connector implementation

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#9318]
## Tell us about the problem you're trying to solve
It would be nice to retrieve data from orb

https://docs.withorb.com/reference
The API key for testing is at the bottom of the Lastpass secret `dev-gsm-conf.yaml`
The actual application page is at https://app.billwithorb.com/, but they need to set up an account for you to access it.

**Comment by sherifnada** [comment]
@lmossman should this be closed?

**Comment by lmossman** [comment]
Yes it should, the Orb source connector exists and is being actively used by Airbyte
