### ISSUE TITLE
Unify source database benchmarks

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9324]
Currently there are many benchmark database:

- test100tables240coumns100recordsDb (this one can be removed)
- test1000tables240columns200recordsDb
- test5000tables240columns200recordsDb
- testInterim15tableswith50000recordsDb
- testRegular25tables50000recordsDb
- testSmall1000tableswith10000recordsDb

We want to:
1. Remove the ones that we no longer need, and only keep these:
    - test1000tables240columns200recordsDb
    - test5000tables240columns200recordsDb
    - testRegular25tables50000recordsDb
    - testSmall1000tableswith10000recordsDb
2. Unify their names to `t<table_count>_c<column_count>_r<record_count>_s<row_size>`.
    - E.g. `t1000_c8_r50k_s100k`

**Comment by andriikorotkov** [comment]
@tuliren, I have renamed all databases in the format you specified in this problem. For postgres - I moved each schema to separate databases. it speeds up performance tests.
![2022-01-19_15-12](https://user-images.githubusercontent.com/88329385/150161417-76dbf519-0293-4ce3-896f-07a887325f47.png)

![2022-01-19_15-15](https://user-images.githubusercontent.com/88329385/150161438-9097c93a-9674-4ff0-98b9-bdc3df22a98a.png)

![2022-01-19_15-16](https://user-images.githubusercontent.com/88329385/150161462-4ac1eb45-0bce-4b32-b635-6ef47aa731be.png)
