### ISSUE TITLE
DBT without git repository

### ISSUE THREAD

**Issue by BEIIKS** [airbytehq/airbyte#9332]
I work in a private network, without Git.
In order to use dbt you have to provide a link to git repo, so I thought of ways to get around this:
clone the project -> archive into zip file -> serve the file with nginx and than use the nginx server as custom git repo

Opinions?

**Comment by harshithmullapudi** [comment]
Hey @BEIIKS just food for thought. It would be better if you can use success hook which we provide in settings and then you can run your custom DBT in DBT cloud or something ?

Does the above way not possible or did I get it wrong ?

**Comment by ChristopheDuong** [comment]
If you are able to write a bash script to download your zip file, I'm guessing this improvement described here could serve this purpose? https://github.com/airbytehq/airbyte/issues/5590

**Comment by BEIIKS** [comment]
@harshithmullapudi cant find anything about "success hook", is this relative to airbyte or git?

**Comment by BEIIKS** [comment]
@ChristopheDuong your issue is relative to the dbt command, i need somehow to get over the git repo

**Comment by BEIIKS** [comment]
> If you are able to write a bash script to download your zip file, I'm guessing this improvement described here could serve this purpose? #5590

your issue is relative to the dbt command, i need somehow to get over the git repo

**Comment by ChristopheDuong** [comment]
> your issue is relative to the dbt command, i need somehow to get over the git repo

yes, the original goal is to let users tune multiple dbt commands as they wish. But this would be done via a bash script input in the UI. So in the bash script, you are free to run other commands other than dbt to get over the git repo. It doesn't have to be only dbt commands.

**Comment by BEIIKS** [comment]
> > your issue is relative to the dbt command, i need somehow to get over the git repo
> 
> yes, the original goal is to let users tune multiple dbt commands as they wish. But this would be done via a bash script input in the UI. So in the bash script, you are free to run other commands to get over the git repo. It doesn't have to be only dbt commands.

Sure, but the git repo url field is a require one, so anyway in the proccess airbyte would try to clone something.

I need to figure out how to give airbyte the project without repostiroy

**Comment by eembees** [comment]
We have encountered a workaround for this which may or may not fit your usecase as well.
1. Identify the path to the `airbyte_workspace` volume `docker volume inspect airbyte_workspace`
2. symlink your local repo to work in this repo `sudo ln -s dbt-repo /var/lib/docker/volumes/airbyte_workspace/_data/dbt-repo`
3. provide this local filepath to your airbyte configuration URL: `/data/dbt-repo`

**Comment by cgardens** [comment]
We aren't going to pick this up. We want to stay away from orchestrating dbt. We recommend using Airflow or Dagster to do this orchestration. [Docs](https://docs.dagster.io/integrations/airbyte).
