### ISSUE TITLE
🐛 Destination Snowflake: Source container not shutting down after error

### ISSUE THREAD

**Issue by prudhvi85** [airbytehq/airbyte#9346]
## Environment
- **Airbyte version**:  0.29.22-alpha
- **OS Version / Instance**: Ubuntu 20.04/ec2 16gb ram and 4cores
- **Deployment**: Docker
- **Severity**:  Critical
- **Step where error happened**: Sync job 

## Current Behavior
We are using Airbyte to sync data from various sources to various destinations. One of our destinations is snowflake. we had a trial version of snowflake and it got expired today. I observed the following issues:
- Even though there is an error the source docker container does not exit.
- The docker container is stuck and can't even kill it using docker kill command
- New jobs are not scheduled after one of these containers is stuck.

## Expected Behavior
Whenever there is an error, the source image should stop and attempt to retry. if the number of retries reached the limit set in config the job should fail. 

## Logs
![image](https://user-images.githubusercontent.com/5214499/148457855-9f9ee905-83a8-4db1-903e-817974e90b93.png)

## Steps to Reproduce
1. create a connection from source to an expired snowflake instance. 
2.  check the running containers to see what all containers are stuck

**Comment by alafanechere** [comment]
I consider this error critical because the "zombie" containers are preventing new job runs. @prudhvi85 are you using the latest Destination Snowflake connector version (`0.3.23` as of today)? If not, please upgrade and let us know if the problem persists.

**Comment by alafanechere** [comment]
Could you also be more specific about which containers are not exited: source, destination, or both?

**Comment by prudhvi85** [comment]
@alafanechere  Source connecters get stuck.

**Comment by prudhvi85** [comment]
@alafanechere  I have updated snowflake connector to 0.3.23 and the problem still persists

**Comment by alafanechere** [comment]
Thanks for the details @prudhvi85, could you please attach an entire sync log file that you can download from the UI? The screenshot you attached contains an error from the destination, not from the source.

**Comment by prudhvi85** [comment]
@alafanechere I am 100% sure I logged into the source MySQL container to get those logs. I am not sure why I see this in the source. 

Logs from the UI :

"2022-01-06 16:40:06 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.29.22-alpha"

Only we can see the above line in UI when this issue happens.

**Comment by alafanechere** [comment]
@prudhvi85 could you please upgrade Airbyte to the latest version, retry and send the full sync attempt log?

**Comment by prudhvi85** [comment]
@alafanechere  I think this issue is fixed in the latest version. After the error, all the containers related to that job are killed.
