### ISSUE TITLE
🐛 Source Facebook pages: access_token key error

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9349]
Is this your first time deploying Airbyte: No

OS Version / Instance: Ubuntu 20.4 
Memory / Disk: 64 / 960

Deployment: Docker
Airbyte Version: 0.35

Source name/version: Facebook Pages / 0.1.6

Destination name/version: Snowflake / 0.4.0

Description: Getting failed sync, although the tables for raw and normalization are being created/populated in Snowflake. 

**See attached log**

[logs-10-2.txt](https://github.com/airbytehq/airbyte/files/7826728/logs-10-2.txt)

**Error**

```
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 107, in run
    for message in generator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 92, in read
    stream_instances = {s.name: s for s in self.streams(config)}
  File "/airbyte/integration_code/source_facebook_pages/source.py", line 45, in streams
    access_token = self.generate_page_access_token(page_id, access_token)
  File "/airbyte/integration_code/source_facebook_pages/source.py", line 41, in generate_page_access_token
    return r.json()["access_token"]
KeyError: 'access_token'
```

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1641510879047700?thread_ts=1641510879.047700&cid=C01MFR03D5W

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126634601972) by [Unito](https://www.unito.io)

**Comment by alafanechere** [comment]
The error arises during the call to `SourceFacebookPages.streams`, generating a page access token (by calling `generate_page_access_token`). 
The response from Graph API does not have an `access_token`, hence the `KeyError`. Better error handling in `generate_page_access_token` could help understand the response payload and display a more meaningful error.

**Comment by lgomezm** [comment]
@misteryeo I'm claiming this issue.

**Comment by artem1205** [comment]
fixed while migrating to Low-code
