### ISSUE TITLE
Spec for differentiating errors needing user intervention from connector/platform bugs in reporting

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9350]
## Tell us about the problem you're trying to solve
In order to reliably measure connector quality, we need to know when a connector fails because of a bad configuration/something requiring user intervention (e.g: expired oauth token) vs. failing due to a bug or some other reason. the former category could artificially inflate failure rates, so we want a way to exclude it from tracking.

If the person working on this is distinct from @ChristopheDuong it may be helpful to sync with @ChristopheDuong to catch up on our analytics / event reporting at the moment. 

## Describe the solution you’d like
up to the discretion of the implementer

**Comment by ChristopheDuong** [comment]
There is not enough data in segment data to connect check_connection events back to a connection.

So current metrics can't leverage the past check_connection event data until we make changes to platform as described in the following tech spec: https://docs.google.com/document/d/14hYJTUFIXHQ7JBB-gq2EBGrAvPBaEatDyOZMsUH12bI/edit

**Comment by sherifnada** [comment]
closing since tech spec was ratified by platfiorm team
