### ISSUE TITLE
Create a well defined charset for namespaces and test them in DAT

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9351]
## Tell us about the problem you're trying to solve
issues like https://github.com/airbytehq/airbyte/issues/7435 happen because we don't have clear rules for what characters should be allowed in a namespace. In addition, destinations don't have clear guidance around how to handle namespaces which contain special characters e.g: a custom namespace with a `-` or a space could cause a destination to fail. 

## Describe the solution you’d like
1. define exactly what characters / rules are allowed in a namespace (both custom and source-defined namespaces).
1. Destinations should be resilient towards all allowed characters
2. DAT should test that all destinations can handle all namespace chars. For this one it is super important that we put on the chaos monkey hat in choosing namespace values in the test to make sure the destination can handle everything we throw at it.

**Comment by tuliren** [comment]
## Sprint summary
Did not have time to look into this yet.

**Comment by tuliren** [comment]
## Sprint summary
Done
- Snowflake specific namespace tests.
Remaining
- Need to generalize the solution.
ETA
- End of this week (Feb 25th).

**Comment by tuliren** [comment]
TODO
- [ ] Publish an initial rule set.

**Comment by sherifnada** [comment]
#### plan: 
**MVP**
- publish initial ruleset. This should describe which characters are allowed, how we perform namespace mappings, how we handle name conflicts if they exist, and boundary conditions (e.g: max length)
- implement the initial rule set in an **opt-in** DAT testcase
- bring Snowflake & Bigquery into compliance with it
**Post-MVP**
**UI**
- render the resulting namespace 
- enforce max length limitations
**Backend**
- implement that test case for the rest of the connectors 
- make the testcase opt-out in DAT

**Comment by tuliren** [comment]
[Destination identifier name spec](https://docs.google.com/document/d/1vHDEgQ5VGCAx9UqE4BYx5mesJSYMKmGe4V47p5a8pRg/edit?usp=sharing)
