### ISSUE TITLE
Create an airbyte-shell environment with nix-shell for development

### ISSUE THREAD

**Issue by noahkawasakigoogle** [airbytehq/airbyte#9358]
## Tell us about the problem you're trying to solve
Different people developing on Airbyte with different local environments

## Describe the solution you’d like
Create an airbyte [`nix-shell`](https://nixos.org/manual/nix/unstable/command-ref/nix-shell.html) that would load all dependencies and tools/packages for you (docker, python, java, jq, etc). You would cd into airbytes github repo, and automatically be dropped into a new shell with a prompt like `airbyte-shell`. Everyone who develops in Airbyte would now be using the exact same environment with the same versions of everything. It would work across platforms/OS's and it would help Airbytes community contribution based strategy to ensure that potentially hundreds/thousands of contributors are in-sync with the correct tools. This would essentially reduce developer friction to get started contributing to airbyte, and increase developer velocity.

## Describe the alternative you’ve considered or used
An alternative is to create scripts to install everything, here: https://github.com/airbytehq/airbyte/issues/9239

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment]
This is a great idea @noahkawasakigoogle !

**Comment by samrose** [comment]
Did you ever figure this out? I am pretty good with nix, and could likely help.

**Comment by cpdeethree** [comment]
This isn't an area we are actively looking at currently, but we welcome contributions!
