### ISSUE TITLE
 Access to airbyte/integration-base-java resource

### ISSUE THREAD

**Issue by RevRebel** [airbytehq/airbyte#9364]
When running 

 "docker build . -t airbyte/destination-XXXXX:dev" (XXXXX removed actual name for logging the error)

cli message ....

Sending build context to Docker daemon  50.56MB
Step 1/11 : FROM airbyte/integration-base-java:dev AS build
pull access denied for airbyte/integration-base-java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

results in the following error above for  "airbyte/integration-base-java"

**Comment by alafanechere** [comment]
Hi @RevRebel you need to build the image with `gradlew`: 
`./gradlew :airbyte-integrations:connectors:destination-XXXX:airbyteDocker`

**Comment by marcosmarxm** [comment]
Close because is not an issue.
