### ISSUE TITLE
New Source: Azure Blob Storage

### ISSUE THREAD

**Issue by ravikottu** [airbytehq/airbyte#9374]
## Tell us about the new connector you’d like to have
* Source as Azure Blob as similar as we have a source connector for S3 Bucket

## Describe the context around this new connector
* Need this connector as similar as we have a source connector for S3 Bucket. Most of our projects are with Azure and we should be able to move b/w Azure and S3 

## Describe the alternative you are considering or using
Azure Blob as as File source is available but it currently works only for one file at a time thus it does not qualify to fulfil our requirement

**Comment by jrolom** [comment]
@marcosmarxm I believe we already have Azure Blob Storage so I think we can close this issue
