### ISSUE TITLE
Parallelly triggered  jobs are moving into pending state after certain limit

### ISSUE THREAD

**Issue by naveenpatnana** [airbytehq/airbyte#9375]
## Environment
- **Airbyte version**:  0.35.4-alpha
- **OS Version / Instance**:  Ubuntu 20.04.3 LTS/ EC2
- **Deployment**:  Docker
- **Severity**: Critical
- **Step where error happened**: Sync job 

## Current Behavior
*We have triggered 50 jobs parallely(to stress test our server) with the below configuration in .env file:
### APPLICATIONS ###
# Scheduler #
# Relevant to scaling.
SUBMITTER_NUM_THREADS=50

# Worker #
# Relevant to scaling.
MAX_SYNC_WORKERS=100
MAX_SPEC_WORKERS=50
MAX_CHECK_WORKERS=50
MAX_DISCOVER_WORKERS=50

After triggering the jobs, At a point we hit resource limit of the system and all the jobs went to pending state. After the resources are avaliable none of the pending state jobs started.
<img width="1324" alt="Screenshot 2022-01-10 at 10 45 18 AM" src="https://user-images.githubusercontent.com/90193804/148721031-8de79bda-ff8b-4c49-962b-cca9c82eb65f.png">
<img width="934" alt="Screenshot 2022-01-10 at 10 45 36 AM" src="https://user-images.githubusercontent.com/90193804/148721049-36383f38-5fe7-4881-9061-55add3035753.png">
We waited for 15 hours, even then those jobs are not started they are still in pending state.

*

## Expected Behavior
*We are expecting the Pending state jobs should start when there are sufficient resources *

## Logs
*Logs for the scheduler:
2022-01-10 05:19:28 INFO i.a.s.a.JobSubmitter(lambda$attemptJobSubmit$0):110 - Attempting to submit already running job 84. There are probably too many queued jobs.
2022-01-10 05:19:33 INFO i.a.s.a.JobSubmitter(lambda$attemptJobSubmit$0):110 - Attempting to submit already running job 84. There are probably too many queued jobs.
2022-01-10 05:19:38 INFO i.a.s.a.JobSubmitter(lambda$attemptJobSubmit$0):110 - Attempting to submit already running job 84. There are probably too many queued jobs.
2022-01-10 05:19:43 INFO i.a.s.a.JobSubmitter(lambda$attemptJobSubmit$0):110 - Attempting to submit already running job 84. There are probably too many queued jobs.
2022-01-10 05:19:48 INFO i.a.s.a.JobSubmitter(lambda$attemptJobSubmit$0):110 - Attempting to submit already running job 84. There are probably too many queued jobs.

*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. change the .env config with the given changes above.
2.Trigger 50 parallel jobs at a time.

**Comment by alafanechere** [comment]
@benmoriceau is this a scheduling issue and behavior you are aware of?

**Comment by naveenpatnana** [comment]
@alafanechere @benmoriceau 
Do we have any update on top of this?

**Comment by jagannathsrs** [comment]
One thing to note is that `MAX_SUMBITTER_THREADS = (MAX_SYNC_WORKERS + MAX_SPEC_WORKERS + MAX_CHECK_WORKERS + MAX_DISCOVER_WORKERS)` which means even though you set it to 50 if you have 50 discover jobs, all other types of works will be in pending state and wait for discover schemas to finish. Maybe there's an issue with check/discover workers that's not letting them finish?

**Comment by alafanechere** [comment]
Going in the direction of @jagannathsrs, @naveenpatnana could you try to set MAX_SUMBITTER_THREADS=250 and check the behavior? It could also be helpful to get a dump of your job table in the airbyte database to troubleshoot.

**Comment by hokam** [comment]
Hi @naveenpatnana, is this issue resolved ? after applying the above mentioned changes.

**Comment by octavia-squidington-iii** [comment]
Marcos Marx commented: One thing to note is that `MAX_SUMBITTER_THREADS = (MAX_SYNC_WORKERS + MAX_SPEC_WORKERS + MAX_CHECK_WORKERS + MAX_DISCOVER_WORKERS)` which means even though you set it to 50 if you have 50 discover jobs, all other types of works will be in pending state and wait for discover schemas to finish. Maybe there's an issue with check/discover workers that's not letting them finish?

**Comment by marcosmarxm** [comment]
Can you test latest version with the new scheduler (Temporal) you only need to specify the MAX_SYNC_WORKERS

**Comment by marcosmarxm** [comment]
Closing due inactivity.
