### ISSUE TITLE
🐛 Source Shopify: 403 error on sync (PriceRules stream)

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9384]
## Environment
- **Airbyte version**: 0.35.4-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.27
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
The user in this [slack conversation](https://airbytehq.slack.com/archives/C01MFR03D5W/p1641590373101700) faces a 403 forbidden error. This error should not happen after a connection check.
The existing connection check does not validate permissions on all Shopify streams (the `Shop` stream only)

## Expected Behavior
No permission error after the connection check.

## Logs
[shop_sync_fail.log](https://github.com/airbytehq/airbyte/files/7839792/shop_sync_fail.log)

**Comment by grubberr** [comment]
Can you please update `sources-shopify` to the latest verion `0.1.31`  and re-setup sync from scratch.
Starting from `0.1.30` [Changelog](https://github.com/airbytehq/airbyte/blob/master/docs/integrations/sources/shopify.md#changelog)
this connector checks permissions and only shows streams for which it has access.

If your shopify auth token missed permission for reading `PriceRules` stream you need to add this permission for your token: `read_price_rules`


<img width="624" alt="Screenshot 2022-02-10 at 12 12 59" src="https://user-images.githubusercontent.com/195743/153385925-417ef2ee-8b55-49d8-864b-52813b872868.png">

**Comment by bazarnov** [comment]
@alafanechere is this issue is still relevant?

**Comment by bazarnov** [comment]
Closed, as No Need to fix. The instructions was given to the Customer: https://github.com/airbytehq/airbyte/issues/9384#issuecomment-1034745685
