### ISSUE TITLE
Test Normalization on Empty Streams

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#939]
## Tell us about the problem you're trying to solve
* BQ fails when it tries to normalize a stream in a sync if that stream has no data. 

## Describe the solution you’d like
* This is not a case we have tested and came up by accident, so it is probably a problem in snowflake and PG too. We should add it to the standard tests.

**Comment by cgardens** [comment]
Details: Synced an empty postgres table into big query with basic normalization turned on.

**Comment by sherifnada** [comment]
@cgardens I'm unable to replicate this issue in our integration test account. Any more details you can provide about how this happened? I tested with both sync'ing only empty tables and sync'ing a mix of empty and full tables.

**Comment by cgardens** [comment]
I will try again tomorrow then with the db tables I was syncing to see if I
can figure out what's up.

**Comment by cgardens** [comment]
Closing. Will reopen if i can reproduce.
