### ISSUE TITLE
Source Stripe: improve performance

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9404]
## Tell us about the problem you're trying to solve
Stripe's API rate limit is 100 requests/second, and each page of data can retrieve 100 records. This means that in theory we should be able to pull data very quickly (up to 10k records per second, assuming an HTTP request takes 1 second to return). 

A user reported that their Stripe connector was taking much longer than their in-house handwritten connector. Stripe is an important connector, so we should explore the feasibility of this. 

## Describe the solution you’d like
Investigate ways we can improve the connector's sync speed to come much closer to fully utilizing the per second quota limit provided by Stripe.

**Comment by pushchris** [comment]
Would love to see the performance of this connector improved. Our Stripe connection is taking 9+ hours to run to pull < 320k records. For comparison, on other ELT's the same sync takes <10min. Not exactly sure why there is such a disparity.

**Comment by midavadim** [comment]
We have Improved performance for streams with substreams: invoice_line_items, subscription_items, bank_accounts
We significantly decreased the number of required requests for mentioned streams. 
Previously, 1 request was needed for each extracted record.
