### ISSUE TITLE
REST API does not sync data

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#942]
## Expected Behavior
I setup REST API source to sync data to Postgres with the following config: 

<img width="987" alt="Screen Shot 2020-11-11 at 11 31 42 PM" src="https://user-images.githubusercontent.com/6246757/98909005-14e19100-2476-11eb-999e-57f9f9e96bf5.png">

<img width="681" alt="Screen Shot 2020-11-11 at 11 32 17 PM" src="https://user-images.githubusercontent.com/6246757/98909059-26c33400-2476-11eb-8f12-b9d0dec124d0.png">

then I run a manual sync and see this exception in the logs: 

```
Failed close procedure.
airbyte-scheduler | 2020-11-12 07:28:33 ERROR i.a.c.i.LineGobbler(voidCall):69 - {job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/1} - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.
airbyte-scheduler | 2020-11-12 07:28:33 ERROR i.a.c.i.LineGobbler(voidCall):69 - {job_id=11, job_log_filename=logs.log, job_root=/tmp/workspace/11/1} - catalog: {"streams":[]} ,
```

However, the schema is correctly selected. But there seems to be an issue somewhere where we don't consider a stream selected if it has no selected fields. This is a problem for the REST API source because it does not contain any known fields ahead of time.

**Comment by cgardens** [comment]
weird. this definitely used to work. i can take a look tomorrow!

**Comment by cgardens** [comment]
weirder still. this config works:
![Screen Shot 2020-11-11 at 11 43 47 PM](https://user-images.githubusercontent.com/9092207/98910262-c9c87d80-2477-11eb-8ca6-d761e9dc22a9.png)

(but then neither BQ nor csv destination were able to process the information output by the sources -- probably because there are so many special characters in the field names.🙄 )

**Comment by sherifnada** [comment]
Bumping out of 0.5.1
