### ISSUE TITLE
Connector check should not succeed if snowflake cannot access external S3 staging

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9423]
## Environment
Cloud or OSS: OSS
Version: 0.30.21-alpha
Source Id/Name/Version: S3 0.1.5
Destination Id/Name/Version: Snowflake 0.3.16
Step Issue Happened: Syncing data from S3 to Snowflake

## Current Behavior
User ran a sync to snowflake with incorrect permissions configured. The destination failed with 403. however, they should not be able to configure a destination which will 403 on a sync. 

## Expected Behavior
User shouldn't be able to get past connection configuration if needed permissions aren't setup. 

## Logs
See https://github.com/airbytehq/oncall/issues/95 for logs (can't share here since it contains customer data)

## Steps to Reproduce
?

**Comment by tuliren** [comment]
@sherifnada, I don't think this is a problem. We are already returning `FAILED` when the persistence check throws any exception:

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/copy/CopyDestination.java#L48-L55

**Comment by misteryeo** [comment]
Closing based on Liren's comments.
