### ISSUE TITLE
Integrate ARM connector image building and publishing in CI

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9426]
## Description
- To run Airbyte on M1 / ARM machines, we need to build and publish ARM images.
- The platform side of the work is tracked in https://github.com/airbytehq/airbyte/issues/7930.
- This issue tracks that on the connector side.

## Acceptance Criteria
- Figure out how to build and publish ARM connector images locally.
- Update the `publish` command to build and publish both `amd64` and `arm64` connector images at the same time.
- Enable ARM image publishing for one connect.
  - Let's start with `BigQuery` destination.

**Comment by tuliren** [comment]
I have assigned this issue to GL Java team, since the connector we choose here is `BigQuery` destination, which is a Java connector. Feel free to hand over to a different team if that makes more sense.

**Comment by tovbinm** [comment]
Is there an ETA on this?

**Comment by davinchia** [comment]
@evantahler we can close this yes?

**Comment by davinchia** [comment]
@evantahler I'm going to close this since I think it's done. Feel free to reopen if there is work left.
