### ISSUE TITLE
Google Sheets Incremental Sync

### ISSUE THREAD

**Issue by leiii** [airbytehq/airbyte#9432]
Hi, we would like to use Airbyte to sync data from Google Sheets, where our daily data collection/operation runs on. However, according to the doc (https://docs.airbyte.com/integrations/sources/google-sheets), currently, Airbyte cannot do incremental sync from Google Sheets. Also from the doc, it said this feature will come soon. We would like to know the roadmap of this feature.

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by alafanechere** [comment]
Hi @leiii , I close this issue as this a duplicate of this one https://github.com/airbytehq/airbyte/issues/3936
