### ISSUE TITLE
Source Pipedrive: Custom Fields

### ISSUE THREAD

**Issue by ProdigyMaster** [airbytehq/airbyte#9433]
## Tell us about the problem you're trying to solve
In Pipedrive there is an option to add custom fields to the organization. In my case: Sales Person working in Pipedrive CRM creates a custom field for user attribution source and sets it to google/organic.  I would like to have values from Pipedrive's custom fields in my data warehouse and track changes on them. 

Custom Files are very important in Pipedrive, and for our workflow.

## Describe the solution you’d like
I would like to be able to get data from the following endpoints and transfer them to our data warehouse. And be able to associate custom fields with specific objects and values.
- [OrganizationFields](https://developers.pipedrive.com/docs/api/v1/OrganizationFields#getOrganizationFields) - Them most important fields - 
- [ActivityFields](https://developers.pipedrive.com/docs/api/v1/ActivityFields#getActivityFields) - 
- [ProductFields](https://developers.pipedrive.com/docs/api/v1/ProductFields#getProductFields) -
- [DealFields](https://developers.pipedrive.com/docs/api/v1/DealFields#getDealFields) - 
- [PersonFields](https://developers.pipedrive.com/docs/api/v1/PersonFields#getPersonFields)

For example, our Sales Person set the organization's custom field "attribution_source" to "google/organic". I would like to be able to get value from this custom filed for a specific organization in the data warehouse:
organization_id: 123 , attribution_source: "google_organic"

## Describe the alternative you’ve considered or used
No alternative, custom coding in Python.

Thank You, take care 😉

**Comment by alafanechere** [comment]
It looks like there might be a workaround using custom transformation as mentioned in this related issue: https://github.com/airbytehq/airbyte/issues/6918

**Comment by itaseskii** [comment]
I'll claim this issue

**Comment by emeagenciadigital** [comment]
Still, there's no way to relate a person to it's custom fields .

**Comment by marcosmarxm** [comment]
> 

It's missing a field @emeagenciadigital ?

**Comment by emeagenciadigital** [comment]
On normalization to bug query it’s missing a way to see the custom fields related to 1 record . 

there’s no way to relate a “person” or “deal” or “organization” to its custom fields . 

For example I have a custom field on person called “genre” there’s currently no way of me swing the genre of my contacts .

**Comment by emeagenciadigital** [comment]
With respect;
This is a complete scheme of stitch pipedrive ETL that does includes all relations 

https://www.stitchdata.com/docs/integrations/saas/pipedrive

And this one from Synchub is also complete

https://www.synchub.io/connectors/pipedrive/datamodel

**Comment by JorgeOsorio97** [comment]
Was this solved? I am looking into the same problem.

**Comment by neurotroph** [comment]
Hi everyone. Thank you for including the additional streams in the Pipedrive connector with #11870.
The issue mentioned by @JorgeOsorio97 and @emeagenciadigital and also faced by us, however, remains unsolved:

By [Pipedrive's documentation](https://developers.pipedrive.com/docs/api/v1/Deals):
> Each deal consists of standard data fields but can also contain a number of custom fields. The custom fields can be recognized by long hashes as keys. These hashes can be mapped against DealField.key. The corresponding label for each such custom field can be obtained from DealField.name.

These custom fields are missing from both the normalized tables and the raw JSON data in `airbyte_internal`. It would be great if this gets addressed.

My recommended solution would be to include a column `custom_fields` in the normalized output which includes the custom field data as JSON. To my understanding this would be the most flexible solution.
