### ISSUE TITLE
:bug: Source Jira: 400 client error bad request for url

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9436]
_Is this your first time deploying Airbyte_: Yes
_OS Version / Instance_: Windows
_Memory / Disk_: 16Gb / 500Gb SSD
_Deployment_: Docker
_Airbyte Version_: 0.35.5-alpha
_Source name/version_: Jira 0.2.18
_Destination name/version_: Snowflake 0.3.21
_Step_: On sync
_Description_: When I try to sync the Jira `issues` table into Snowflake I get `400 Client Error: Bad Request for url:`. I've attached the sync and server logs.

[logs-33-0.txt](https://github.com/airbytehq/airbyte/files/7855857/logs-33-0.txt)
[server-logs (3).txt](https://github.com/airbytehq/airbyte/files/7855858/server-logs.3.txt)

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1641998743269100?thread_ts=1641998743.269100&cid=C01MFR03D5W

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126634859561) by [Unito](https://www.unito.io)

**Comment by darynaishchenko** [comment]
I checker a work of connector and didn't find any issues related to this error. As I can see in slack thread this error was occurred because of user permissions, not of connector.
