### ISSUE TITLE
Google Ads Customer ID Link is Broken

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9438]
## Environment
- **Source Id/Name/Version**: Google Ads

In the Google Ads Source connection settings page the "doc" link for the Customer ID is broken and goes to a "page not found". 

<img width="1165" alt="Screen_Shot_2022-01-11_at_11_08_12_AM" src="https://user-images.githubusercontent.com/93952107/148997873-9d0d4575-c32f-4f4e-a9f5-87f8fb042248.png">

**Comment by edgao** [comment]
this was resolved on jan 19 https://github.com/airbytehq/airbyte/commit/a1e2b6383d4e2e911adff57052d715101ef33474#diff-2f6a32b67d7c88a2a4ccbb67200caeb69066953dea81994ec68a171414a11d0dL2181
