### ISSUE TITLE
Run the new DAT(s) against all destinations and find destinations that are not compliant

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#9444]
Depends on https://github.com/airbytehq/airbyte/issues/9443

After the tests are written, run them against all our destinations.

For destinations which are failing because they don't support the optionally-supported types (large numbers and unions), add them in a comment on this issue.

For destinations which don't support one or more of the mandatory types, create an issue to fix them. Add that issue to the "Noncompliant destinations" section of the main epic (https://github.com/airbytehq/airbyte/issues/9441).

**Comment by DoNotPanicUA** [comment]
|Destination name| Base test| Object test | Array test | Object + Array test |
|---|---|---|---|---|
| MySql | :heavy_check_mark:  | :heavy_check_mark: | :x: | :x: |
| MsSql | :x:  | :x: | :x: | :x: |
| Oracle | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

TBD

**Comment by DoNotPanicUA** [comment]
|Destination name| Base test| Object test | Array test | Object + Array test |
|---|---|---|---|---|
| MySql | :heavy_check_mark:  | :heavy_check_mark: | :x: | :x: |
| MsSql | :x:  | :x: | :x: | :x: |
| Oracle | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| Postgres | :x:  | :x: | :x: | :x: |

TBD

**Comment by DoNotPanicUA** [comment]
Hi @edgao ,
I've executed our tests for all Java destinations and now we have a full picture.
Please note that I did some improvements that I mentioned in the #9443 issue. I will create a PR for the common part and will prepare separated PRs to enable tests for destinations where it works fine.
What is the next step? Shall we create tickets for non-compatible destinations and fix them?

**Comment by edgao** [comment]
nice! Yep, next step would be to make tickets and fix the destinations that don't work. Can you add them to the `Noncompliant destinations` section on the epic? https://github.com/airbytehq/airbyte/issues/9441
