### ISSUE TITLE
Determine which database sources can produce the optionally-supported types

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#9447]
This is an investigative ticket to determine which database sources are capable of producing large numbers or unions.

For sources which can produce large numbers, create a new issue to update that source so that it declares affected fields using `{"type": "string", "airbyte_type": "big_integer"}` (or `big_number`). Offhand, I would expect many of the JDBC sources to be affected. For example, [Postgres](https://github.com/airbytehq/airbyte/blob/7c4ae134734de1409e30f08efe52fee4c7c5b07e/airbyte-integrations/connectors/source-postgres/src/main/java/io/airbyte/integrations/source/postgres/PostgresSourceOperations.java#L137) has `NUMERIC` and `DECIMAL` types, which we currently map to a `number` type.

For destinations which can produce unions, create a new issue to update their documentation to reflect this.

Remember to add those issues into the "Noncompliant sources " section of the epic (https://github.com/airbytehq/airbyte/issues/9441).

**Comment by grishick** [comment]
Related issue describing a problem with all numbers being converted to double: https://github.com/airbytehq/airbyte/issues/11627

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Improve DB/DW data mappings](https://app.harvestr.io/components/0/list/wOUds4X9B)

**Comment by alexandr-shegeda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Java-Connectors-625f0102b11304001e0f6c6e/issues/airbytehq/airbyte/9447?planning-poker) with ZenHub @yurii-bidiuk @DoNotPanicUA @mkhokh-33

**Comment by grishick** [comment]
After an internal discussion we realized that all DB sources support optionally supported types, because those are part of ANSI SQL standard. I will close this issue and open separate issues for source-specific fixes.
