### ISSUE TITLE
Normalization runs even if destination sync fails

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#946]
## Expected Behavior
I set up a source from File from my local filesystem.
After successfully replicating data once, i make changes to the source settings with the following URL (which is wrong):
`file:///tmp/airbyte_local/edge_case_messages.txt` as described in #935 

I would be fine if the source/destination sync fails but probably wouldn't be too happy to delete my data in the warehouse when such an error occurs? (it breaks downstream pipeline until i fix my replication with proper settings)

Not sure, if we thought about what we should do in case of errors when running the syncs?

## Current Behavior
The source-file connector fails to load the file from the docker image so it throws an exception and stops, the `_raw` table in the destination actually gets flushed and is now empty.
But even though that first step failed, the normalization (and DBT) is still triggered to refresh the normalized tables which in turn becomes empty too.

## Steps to Reproduce
1. Load successfully local file to destination
1. Change source parameters to wrong settings
1. Sync

## Severity of the bug for you
Medium

**Comment by cgardens** [comment]
@ChristopheDuong this is fixed when we fixed making normalization wait for the sync to complete, right? is this closeable?
