### ISSUE TITLE
Polish Connection Settings UI Text

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#9462]
## Tell us about the problem you're trying to solve
Text in the Connection Settings UI are incorrectly positioned, padded or spaced. More clearly seen in the attached screenshot.

## Describe the solution you’d like
Padding, positioning and space for field descriptions should be consistent. The Namespace Configuration description and the Table Prefix description should be consistent. The new line under Basic Normalization which says "Don't worry..." should be correctly spaced and probably not in plain text since it's important information for a new user. It's also unclear if this text refers to just the normalization choice or everything in the set up. 

## Additional context
![Airbyte New Source 🔊 2022-01-12 at 5 04 00 PM](https://user-images.githubusercontent.com/16851149/149247495-014ae5e7-7a93-4ed8-9d4e-f5cae877168e.jpg)

**Comment by jrhizor** [comment]
The first two red boxes are already out of date in the upcoming pr. This ticket is only for the final box now.
