### ISSUE TITLE
Github action cannot launch

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9463]
When running an action, there is the following "log" before failing:

> Found online and idle self-hosted runner in the current repository that matches the required labels: 'miu70'
> Waiting for the runner to pick up this job...
> Job is about to start running on the runner: ip-10-0-47-153 (repository)

When the page is refreshed, the logs are gone, and the exception is `This check failed`.

Example: https://github.com/airbytehq/airbyte/runs/4795864285?check_suite_focus=true
Slack thread: https://airbytehq.slack.com/archives/C02LM2R4R6E/p1642022690028500

**Comment by davinchia** [comment]
This is fixed with #9466
