### ISSUE TITLE
Increase the batch size of number of records printed in logs 

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9464]
Today Airbyte logs every 1000 records this can create really huge logs when users try to pull large tables (100M)
If someone try to read 100M records will hit the maximum number of rows allow from our log system too.
https://github.com/airbytehq/airbyte/blob/9b1ed03fe482f5154f6c1843b1be76de87f3605d/airbyte-workers/src/main/java/io/airbyte/workers/DefaultReplicationWorker.java#L250-L252

**Comment by evantahler** [comment]
Closing... this is fine for now. the Logs are already big 🤷‍♀️

**Comment by marcosmarxm** [comment]
@evantahler the idea was to increase from 1000 to 10k or 100k :p so large syncs won't blow the max log lines.

**Comment by evantahler** [comment]
Is there limit to the number of log lines?  We have lots more debugging and JSON printing of sync metrics we've added recently...

**Comment by marcosmarxm** [comment]
100k if I not wrong.

**Comment by evantahler** [comment]
Maybe @supertopher can you confirm that there's a limit to how big our log files can be?
