### ISSUE TITLE
Snowflake destination: set query_tag in the UI

### ISSUE THREAD

**Issue by pjleiwa6g** [airbytehq/airbyte#9467]
## Tell us about the problem you're trying to solve
I would like to know which queries were run by Airbyte in Snowflake. This can be used to determine costs and solve issues.

## Describe the solution you’d like
In Snowflake a session parameter called 'query_tag' can be set. At this moment a fixed value for 'query_tag' is set when use the basic normalization option. The value then is: 'query_tag=normalization'. I would like this option to be extended:

* The value for the query_tag should be set in the UI, in the config parameters of the Snowflake destination connector.
* Multiple values should be entered like this: {"tool":"airbyte","datasource":"applicationX"}
* I would be nice if the name of the source connector can be used as an variable, so it can be passed to the query_tag.

## Describe the alternative you’ve considered or used
An alternative is to set the parameter value on user level. This means an extra user should be created. And If you want have different query_tags per data source, multiple users should be created.

## Additional context
See screenshot for an example

![airbyte!UNITO-UNDERSCORE!query!UNITO-UNDERSCORE!tag](https://user-images.githubusercontent.com/93518481/149289049-72b0f2a1-4216-437d-b74a-ed0ed38f277a.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126635074016) by [Unito](https://www.unito.io)

**Comment by RogerDataNL** [comment]
Being able to use query tags to dissect for which connector / customer / source we are running airbyte for is important for us too!

**Comment by noahkawasakigoogle** [comment]
I'd actually suggest broadening this issue to be "Snowflake destination: Allow additional JDBC parameters" so users can input _any_ additional JDBC parameters. 

This would mean anything from [Snowflake's JDBC Driver Parameters](https://docs.snowflake.com/en/user-guide/jdbc-parameters.html) _and_  [Snowflake Parameter](https://docs.snowflake.com/en/sql-reference/parameters.html) can work, which gives users way more power to customize their connection abilities (which saves you time from more requests from adding a UI input for every particular param someone might need). I tested with `QUERY_TAG` as a JDBC string param and it went thought

This would support setting `QUERY_TAG` through an additional params input instead. There would just need to be a quick check here: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py#L207

To first see if the `config` contains (case-insensitive) the `QUERY_TAG` key and only set Airbyte's default if its empty.

**Comment by noahkawasakigoogle** [comment]
Working on this here: https://github.com/airbytehq/airbyte/pull/9623/files

First time I've done something with connectors for Airbyte so it might take a bit to make sure im doing everything needed

**Comment by pjleiwa6g** [comment]
@noahkawasakigoogle I see you added an option to enter additional jdbc parameters. Very nice. In my original story I was looking to set the query_tag. In the Snowflake documentation I don't see query_tag as one of the jdbc params [https://docs.snowflake.com/en/user-guide/jdbc-parameters.html](url) . Did you tested it for this specific setting?

**Comment by sashaNeshcheret** [comment]
Seems the issues was fixed by [PR](https://github.com/airbytehq/airbyte/pull/9623), @pjleiwa6g please confirm it. @grishick this issue may be closed as fixed.

**Comment by pjleiwa6g** [comment]
@sashaNeshcheret  Yes, its fixed by https://github.com/airbytehq/airbyte/pull/9623
