### ISSUE TITLE
Source Tiktok: wrong type in campaign schema

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9491]
## Environment
- **Airbyte version**:  0.32.2-alpha
- **OS Version / Instance**: Not informed.
- **Deployment**: Not informed.
- **Source Connector and version**: Tiktok 0.1.1
- **Destination Connector and version**:  Bigquery 0.3.7
- **Severity**: Very Low / **Low** / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Sync fails during normalization

## Expected Behavior
Should work

## Logs
Complete logs: [logs-106032-0.txt](https://github.com/airbytehq/airbyte/files/7866417/logs-106032-0.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

No

**Comment by midavadim** [comment]
According to official docs https://ads.tiktok.com/marketing_api/docs?id=1708582970809346:
'campaigns' stream has 'bid_type' attr name with 'number' type.

but log message says that value was 'BID_TYPE_NO_BID'
    Database Error in model test_tiktok_campaigns (models/generated/airbyte_tables/airbyte/test_tiktok_campaigns.sql
    Bad double value: BID_TYPE_NO_BID
    
So seems like, this is actually 'string' with 'enumeration'. which can be found in Enumeration doc:

https://ads.tiktok.com/marketing_api/docs?id=1701890985340929
Bidding Strategy (bid_type)


SOLUTION change type from number to string for 'campaigns' stream  'bid_type' attr name

**Comment by ayyoubmaulana** [comment]
so for this issue we need to change type in TikTok Ads Dashboard from number to string ?
