### ISSUE TITLE
Decide which destinations we want to support the optional types (large numbers / unions)

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#9495]
Depends on https://github.com/airbytehq/airbyte/issues/9444 to find the list of destinations.

for destinations which don't support large numbers / unions:
* decide whether they need to support them right now
* if yes: create an issue to add support
* if no: create an issue to reject those types + add to the connector doc that they reject those types

**Comment by tuliren** [comment]
> add to the readme that they reject those types

I think we probably want to put it in the connector doc instead of README? Usually the README is for developers, not users.

**Comment by edgao** [comment]
bigint/bignum are no longer real things; unions are a whole separate can of worms
