### ISSUE TITLE
CDK: typing errors

### ISSUE THREAD

**Issue by augan-rymkhan** [airbytehq/airbyte#9500]
## Environment
- **Airbyte version**:  
- **OS Version / Instance**: *
- **Deployment**: *
- **Source Connector and version**: CDK
- **Severity**: Low 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
When running `mypy airbyte_cdk` gives 46 typing errors.
![image](https://user-images.githubusercontent.com/93112548/149468218-81f289e5-d068-4024-b6d9-12143ed55612.png)

## Expected Behavior
Need to fix typing errors

## Steps to Reproduce
1. Go to airbyte_cdk
2. `mypy airbyte_cdk`

## Are you willing to submit a PR?
Yes

**Comment by vitaliizazmic** [comment]
I've checked running ```mypy airbyte_cdk``` output. Seven errors are related to decorators implementation in ```sentry.py```. Two errors are in ```schema_helpers.py```. Other errors connected with ```sources.singer``` code. 
Most errors are ["Incompatible type error"](https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides). E.g, ```Return type "str" of "read_catalog" incompatible with return type "ConfiguredAirbyteCatalog" in supertype "Source"``` in ```singer.source```  It's needed to significantly rewrite singer source code to fix this issues. I'm not sure if I should do this. For other errors I created PR #9926

**Comment by VasylLazebnyk** [comment]
@sherifnada please take a look on Vitaliy's comment above, thanks

**Comment by sherifnada** [comment]
@vitaliizazmic excluding singer from the MyPy checks is fine for now, let's create a separate ticket to handle the singer piece specifically

**Comment by vitaliizazmic** [comment]
@sherifnada I've created separate issue and have one question to clarify. Should I add singer piece to exclude in ```.mypy.ini``` configs?

**Comment by sherifnada** [comment]
@vitaliizazmic sure but please add a comment explaining why it's excluded and pointing to any relevant github issue

**Comment by keu** [comment]
@sherifnada @vitaliizazmic I don't think this is what we want in this case. MyPy should be enabled for all CDK to prevent adding code that doesn't comply.
Instead we should disable MyPy in specific lines explicitly (`# type: ignore`)
