### ISSUE TITLE
🐛 Helm: bootloader timeout (never completed issue)

### ISSUE THREAD

**Issue by KennethanCeyer** [airbytehq/airbyte#9512]
## Background

If user run the repo's `charts/airbyte` helm chart, bootloader runs through `pre-install, pre-upgrade` hook, but bootloader  waits for PostgreSQL connection and does not run, leading to a timeout issue after 600 seconds.

## Issue

![image](https://user-images.githubusercontent.com/7090315/149519965-c708699b-8c29-4a18-8320-27e4ae81fe35.png)

To summarize in single sentence, We can not use `helm install charts/airbyte` without modifying `charts/airbyte/templates/bootloader/pod.yaml` file.

**Details**

If you look at the code below, bootloader  has `pre-install, pre-upgrade` hooks. Due to this, the helm deployment operation that starts the PostgreSQL service does not work, and because of this, the bootloader starts to wait permanently. (Circular wait, deadlock occurs)

https://github.com/airbytehq/airbyte/blob/dbddd7b3c587f132d4e83f998031e3c81a450273/charts/airbyte/templates/bootloader/pod.yaml#L9

## Solution

Removing the helm.sh/hook line solves this problem.
However, I do not know the reason why added the pre-install, pre-upgrade hook,
so I would like to get your opinions here before create a PR.

## Additional

The description of deployment via helm is insufficient. (including documentation for the `ci.sh` command)
Would it be okay to create a PR related to the documentation of helm as well?

**Comment by novotl** [comment]
👍 Experiencing the same issue, you described the deadlock correctly. IMO the correct solution is to change `pre-install` to `post-install` here https://github.com/airbytehq/airbyte/blob/cb6d9abcab0a14a881d002a60f4337e305b8dd45/charts/airbyte/templates/bootloader/pod.yaml#L9

**Comment by alafanechere** [comment]
Yes you're right @novotl, feel free to open a PR for this.

**Comment by alafanechere** [comment]
We thought about adding the same hooks to the Postgresql database deployment. Feel free to check out this branch and check if the error persists: https://github.com/airbytehq/airbyte/pull/9556

**Comment by feluelle** [comment]
@alafanechere it this did not solve this issue. I still have to remove `helm.sh/hook: pre-install,pre-upgrade` line to make it work.

**Comment by NipunaPrashan** [comment]
@alafanechere I am experiencing the issue now with latest changes. Seems the issue is still there.

**Comment by marcosmarxm** [comment]
@KennethanCeyer closing due inactivity, please test latest version of Helm deployment.
