### ISSUE TITLE
Http Rest API data sources

### ISSUE THREAD

**Issue by JAXPARROW** [airbytehq/airbyte#9517]
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by alafanechere** [comment]
Hi @JAXPARROW we encourage user with this needs to build their own connector with our CDK. We had an HTTP rest connector but we found that there are lots of cases in which using a general connector leads to poor user experience, as there are countless edge cases for different API structures, different authentication policies, and varied approaches to rate-limiting. We believe that enabling users to more easily create connectors is a more scalable and resilient approach to maximizing the quality of the user experience. 

If you still want to give a try to our old HTTP Rest connector your can check this out: https://github.com/airbytehq/airbyte/pull/9451/files
