### ISSUE TITLE
CI sandbox for PersistIq

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9519]
We received a contribution https://github.com/airbytehq/airbyte/pull/9515 for a new [PersistIq](https://www.persistiq.com/v2) source connector. Can we create a sandbox account on this service?

**Comment by karinakuz** [comment]
Sandbox (14-days free trial) with data is ready, all credentials are added to the LastPass, api for the main streams are tested in Postman:
- Users https://api.persistiq.com/v1/users
- Leads https://api.persistiq.com/v1/leads
- Leads Statuses https://api.persistiq.com/v1/lead_statuses
- Leads Fields https://api.persistiq.com/v1/lead_fields
- Campaigns https://api.persistiq.com/v1/campaigns
- Events https://api.persistiq.com/v1/events
