### ISSUE TITLE
Destination Clickhouse: enable `supportDBT` in spec.json

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9522]
## Tell us about the problem you're trying to solve
This was disabled because tests weren't passing. We need to correct tests and re-enable this feature.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by alafanechere** [comment]
[Another user request on slack](https://airbytehq-team.slack.com/archives/C019WJFR1JT/p1645537912884679).

**Comment by rdkrish-plivo** [comment]
Any update on when would custom dbt transformation be enabled for clickhouse destination?

**Comment by arashlayeghi** [comment]
We really need this feature. Any update on this?

**Comment by marcosmarxm** [comment]
@alafanechere do you think it's something we can solve? or we should escalate to connector team?

**Comment by bmikaili** [comment]
We would also need this feature.

**Comment by grishick** [comment]
custom DB transformations currently fail on Clickhouse, so

**Comment by grishick** [comment]
supportsDbt flag has already been added to Clickhouse

**Comment by snikch** [comment]
@grishick are you sure you're correct? I'm currently seeing it as `false` on `main`. 

https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-clickhouse/src/main/resources/spec.json

A new issue has recently been opened asking for this support. https://github.com/airbytehq/airbyte/issues/25147

**Comment by snikch** [comment]
Note: A PR was made for this, but closed without reason. https://github.com/airbytehq/airbyte/pull/10550

**Comment by nailele** [comment]
Hello, any update on when would custom dbt transformation be enabled for clickhouse destination?
We would need this feature.
