### ISSUE TITLE
Updates to workspace names are not reflected in the workspace name display 

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#9524]
## Environment
- prod cloud

## Current Behavior
On Cloud, when I go to Settings > Workspace Settings > General Settings and I update the name of the workspace, it correctly updates the name of the CloudWorkspace in the prod cloud db. However, this does _not_ update the name of the workspace in the top-left corner. Here is a screenshot that shows this:
<img width="594" alt="Screen Shot 2022-01-14 at 4 20 12 PM" src="https://user-images.githubusercontent.com/22731524/149600849-dda5c064-3ff0-4b83-9fdf-c5480bbba835.png">

My guess as to what is happening here is that the UI only writes the update to the `cloud_workspace` table in the `prod-cloudapi` db, but it does not write the update to the `workspace` table in the `prod-configapi` db, and this is likely where the workspace name is being pulled from to show in the upper-left corner. 

## Expected Behavior
Updating the workspace name in the UI should be reflected in the workspace name shown in the upper-left corner. This can likely be achieved through either of the following approaches:
1. Making the update write to the `workspace` table in `prod-configapi` db as well
2. Having the UI pull the workspace name from the `prod-cloudapi` `cloud_workspace` table instead of the `prod-configapi` `workspace` table

## Steps to Reproduce
1. Update the name of a workspace in the cloud UI
2. See the the workspace name is not updated in the upper-left corner

**Comment by lmossman** [comment]
Duplicate of https://github.com/airbytehq/airbyte/issues/9125

**Comment by timroes** [comment]
Closed as of 0.35.13-alpha. Workspace names are now correctly in sync all across the UI. When updating there is still a page refresh needed to update the sidebar, which we'll address at some later point in time.
