### ISSUE TITLE
🐛 Source AppStore: connect Connector Stops Working After First Day

### ISSUE THREAD

**Issue by pushchris** [airbytehq/airbyte#9530]
## Environment
- **Airbyte version**:  35.4
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: 0.2.6
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
The connector stops fetching values once the original start date falls outside of the 365 day mark from the current date. This makes the connector semi-useless since most users will start out by setting the date to one year back to get as much data as possible (Apple limits you to 365 days back), but then the connector stops working the very next day. You end up having to manually decide how to fetch data.

## Expected Behavior
I would expect that after setting the date originally, I wouldn't have to set it again and the latest data would continually be imported. Internally Airbyte should be either moving the date one day ahead every day, only fetch data since the last time data was fetched, or retry with a newer date if no data is received.

**Comment by marcosmarxm** [comment]
AppStore connector was archived and won't be prioritized for now.
