### ISSUE TITLE
Create local benchmark runs for data warehouse destinations

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9535]
## Description
Similar to the performance test for the source database connectors, we want to be able to run the destination container locally and separately from the Airbyte end-to-end pipeline.

## Acceptance criteria
- Have a fixed dataset (or use the mock API source) to be consumed by the destination connector.
- Be able to solely run the destination connector container locally.
- Have clear documentation about how to run the local benchmark.

## Timeline
ETA: Jan 28th.

**Comment by evantahler** [comment]
Closing this in favor of the E2E testing epic https://github.com/airbytehq/airbyte/issues/15152
