### ISSUE TITLE
Hide secrets in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#956]
## Tell us about the problem you're trying to solve
When entering sensitive data like a password in the UI, it is always made visible instead of being formatted like a password e.g: as I type, I'll see `hunter2` instead of `******`. We need a way to annotate these fields in the UI and potentially have a "show" button which toggles showing the value of the field as its being input.

**Comment by cgardens** [comment]
Going to close this in favor of new issue (https://github.com/airbytehq/airbyte/issues/986) that encompasses how we will handle secrets in both UI and API.
