### ISSUE TITLE
Destination Clickhouse: normalization failed due `_ab_cdc_deleted_at` isn't nullable

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9560]
## Environment
- **Airbyte version**:  Not informed
- **OS Version / Instance**:  
- **Deployment**:  
- **Source Connector and version**:  Source with CDC enabled
- **Destination Connector and version**:  Clickhouse with Normalization
- **Severity**: Very Low / Low / **Medium** / High / Critical
- **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
 i have an issue in cdc source to destination sync type is (incremental | deputed history)
`
normalization > DB::Exception: Cannot convert NULL value to non-Nullable type: while executing 'FUNCTION _CAST(_ab_cdc_deleted_at :: 5, 'String' :: 10) -> _CAST(_ab_cdc_deleted_at, 'String') String : 9': (while reading from part /var/lib/clickhouse/store/bfb/bfb95fab-8dc9-49f6-bfb9-5fab8dc9e9f6/all_1_1_0_4/): While executing MergeTreeInOrder. 
`

Stack trace:
and when i saw the query that exist for that table i found it like this.
so why the deleted_at is not nullable when the other fields is nullable?
```
CREATE TABLE cdc_dep_employees.departments_scd (
  `_airbyte_unique_key` String,
  `_airbyte_unique_key_scd` String,
  `dept_no` String,
  `dept_name` String,
  `_ab_cdc_log_pos` Nullable(Float64),
  `_ab_cdc_log_file` String,
  `_ab_cdc_deleted_at` String,
  `_ab_cdc_updated_at` Nullable(String),
  `_airbyte_start_at` Nullable(String),
  `_airbyte_end_at` Nullable(String),
  `_airbyte_active_row` UInt8,
  `_airbyte_ab_id` String,
  `_airbyte_emitted_at` DateTime64(3, 'GMT'),
  `_airbyte_normalized_at` DateTime,
  `_airbyte_departments_hashid` String
) ENGINE = MergeTree
ORDER BY
  tuple() SETTINGS index_granularity = 8192
```

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by MahmoudElhalwany** [comment]
> ## Environment
> * **Airbyte version**:  0.35.5-alpha
> * **OS Version / Instance**: mac os
> * **Deployment**: Docker
> * **Source Connector and version**:  Source with CDC enabled
> * **Destination Connector and version**:  Clickhouse with Normalization
> * **Severity**: Very Low / Low / **Medium** / High / Critical
> * **Step where error happened**: Deploy / **Sync job** / Setup new connection / Update connector / Upgrade Airbyte
> 
> ## Current Behavior
> i have an issue in cdc source to destination sync type is (incremental | deputed history) `normalization > DB::Exception: Cannot convert NULL value to non-Nullable type: while executing 'FUNCTION _CAST(_ab_cdc_deleted_at :: 5, 'String' :: 10) -> _CAST(_ab_cdc_deleted_at, 'String') String : 9': (while reading from part /var/lib/clickhouse/store/bfb/bfb95fab-8dc9-49f6-bfb9-5fab8dc9e9f6/all_1_1_0_4/): While executing MergeTreeInOrder. `
> 
> Stack trace: and when i saw the query that exist for that table i found it like this. so why the deleted_at is not nullable when the other fields is nullable?
> 
> ```
> CREATE TABLE cdc_dep_employees.departments_scd (
>   `_airbyte_unique_key` String,
>   `_airbyte_unique_key_scd` String,
>   `dept_no` String,
>   `dept_name` String,
>   `_ab_cdc_log_pos` Nullable(Float64),
>   `_ab_cdc_log_file` String,
>   `_ab_cdc_deleted_at` String,
>   `_ab_cdc_updated_at` Nullable(String),
>   `_airbyte_start_at` Nullable(String),
>   `_airbyte_end_at` Nullable(String),
>   `_airbyte_active_row` UInt8,
>   `_airbyte_ab_id` String,
>   `_airbyte_emitted_at` DateTime64(3, 'GMT'),
>   `_airbyte_normalized_at` DateTime,
>   `_airbyte_departments_hashid` String
> ) ENGINE = MergeTree
> ORDER BY
>   tuple() SETTINGS index_granularity = 8192
> ```
> 
> ## Expected Behavior
> _Tell us what should happen._
> 
> ## Logs
> _If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._
> 
> LOG
> ## Steps to Reproduce
> 
> ## Are you willing to submit a PR?
> Remove this with your answer.

**Comment by edgao** [comment]
@MahmoudElhalwany have you tried this again recently? I just tested this with a simple CDC sync (postgres->clickhouse) and it worked out of the box:
```
7c0fbb100034 :) select * from foo_table_scd limit 5;

SELECT *
FROM foo_table_scd
LIMIT 5

Query id: c729c6a8-7fdd-4ea4-af66-ed874d43775a

┌─_airbyte_unique_key──────────────┬─_airbyte_unique_key_scd──────────┬──────id─┬─bar────────┬───_ab_cdc_lsn─┬─_ab_cdc_deleted_at─┬─_ab_cdc_updated_at───────┬─_airbyte_start_at────────┬─_airbyte_end_at─┬─_airbyte_active_row─┬─_airbyte_ab_id───────────────────────┬─────_airbyte_emitted_at─┬─_airbyte_normalized_at─┬─_airbyte_foo_table_hashid────────┐
│ 00004B5BC54FEBBCE44F56C1DA6FB530 │ D66DBBDB86F8C0DD358A5EE43F9F7E7F │ 9813343 │ cbc2006dc7 │ 1235004424192 │ ᴺᵁᴸᴸ               │ 2022-06-30T15:45:21.732Z │ 2022-06-30T15:45:21.732Z │ ᴺᵁᴸᴸ            │                   1 │ 5688c38c-966c-4756-be5a-d416f5db542a │ 2022-06-30 15:45:12.781 │    2022-06-30 15:46:22 │ DF3E498E24BE09FDF50AFB5087051118 │
│ 0000DEB92D5F0615C75EC1139D0373BD │ 15F231877FA5E8E4C0AC9D74096395C8 │ 9878213 │ 9878213-1  │ 1235004424192 │ ᴺᵁᴸᴸ               │ 2022-06-30T15:45:24.198Z │ 2022-06-30T15:45:24.198Z │ ᴺᵁᴸᴸ            │                   1 │ 10148f0f-5499-49df-953e-ccac80b5373f │ 2022-06-30 15:45:12.781 │    2022-06-30 15:46:22 │ D762443A94023F39BE73F4793C3926C3 │
│ 0000FBBC4B13A990D28E13D668366405 │ C53B2BDDFB7503675670B7E7040E7510 │ 9732161 │ 9732161-1  │ 1235004424192 │ ᴺᵁᴸᴸ               │ 2022-06-30T15:45:19.184Z │ 2022-06-30T15:45:19.184Z │ ᴺᵁᴸᴸ            │                   1 │ 96189b4d-e052-4237-9598-9735c44cadbd │ 2022-06-30 15:45:12.781 │    2022-06-30 15:46:22 │ C82D55DBBADFF59B7FAE1A5390A54062 │
│ 000168192A1B92AC4C4E39FFBD822CE5 │ A9C196279E62698F8090DB0F6AACCD43 │ 9838147 │ a12f88c9f5 │ 1235004424192 │ ᴺᵁᴸᴸ               │ 2022-06-30T15:45:22.638Z │ 2022-06-30T15:45:22.638Z │ ᴺᵁᴸᴸ            │                   1 │ 6bbdc1b3-4051-41a6-add9-2ea55ce57607 │ 2022-06-30 15:45:12.781 │    2022-06-30 15:46:22 │ F8B24B84A5299768C9ED2675E658857B │
│ 000199542C02997B1E7C60128001CFF7 │ 681518349038E458291C932D2279718D │ 9868435 │ 6e2d8af7c7 │ 1235004424192 │ ᴺᵁᴸᴸ               │ 2022-06-30T15:45:23.551Z │ 2022-06-30T15:45:23.551Z │ ᴺᵁᴸᴸ            │                   1 │ b374ad5b-72d4-4510-a310-1e7f9bc4292d │ 2022-06-30 15:45:12.781 │    2022-06-30 15:46:22 │ D772DEFC08372FFFFF776AD0D14FA31E │
└──────────────────────────────────┴──────────────────────────────────┴─────────┴────────────┴───────────────┴────────────────────┴──────────────────────────┴──────────────────────────┴─────────────────┴─────────────────────┴──────────────────────────────────────┴─────────────────────────┴────────────────────────┴──────────────────────────────────┘

5 rows in set. Elapsed: 0.009 sec.
```
