### ISSUE TITLE
Backup All job for airbyte

### ISSUE THREAD

**Issue by WarayutPeem** [airbytehq/airbyte#9562]
## Tell us about the problem you're trying to solve
1. I would like to know how to backup all job in airbyte.
2. I want duplicate job airbyte (Production to Local)

## Describe the solution you’d like
I have 2 jobs
I want to backup 2 job (All)
![image](https://user-images.githubusercontent.com/93768994/149859321-22dd3eee-1aee-46ee-a4cf-77f12cdd9c5b.png)

**Comment by harshithmullapudi** [comment]
Hey @WarayutPeem you can export the config from settings -> configuration and that will have all the info

**Comment by WarayutPeem** [comment]
Hey @harshithmullapudi, I export gz file from production server.

**Comment by WarayutPeem** [comment]
@harshithmullapudi, Later I imported the gz file into the machine, the result is nothing and have 2 jobs in local

**Comment by WarayutPeem** [comment]
@harshithmullapudi, Example Production, have 120+ job
![image](https://user-images.githubusercontent.com/93768994/149899244-da6f2bd8-d208-42d7-a111-574969722bf3.png)

Example GZ File Export 
![image](https://user-images.githubusercontent.com/93768994/149899352-11e286b7-067a-43ec-880a-d4ff244270f7.png)

Example Import GZ File in Local
![image](https://user-images.githubusercontent.com/93768994/149899501-df202896-3948-4dd9-bf79-60d1744227cb.png)
![image](https://user-images.githubusercontent.com/93768994/149899564-3afacc42-8a02-457e-b7dd-ddd9b55ab955.png)
