### ISSUE TITLE
To know size/number of records in source before download starts.

### ISSUE THREAD

**Issue by sheshan-doye-konvergeai** [airbytehq/airbyte#9566]
## Tell us about the problem you're trying to solve
Want to show progress bar for download or estimated time of download.

## Describe the solution you’d like
If we get number of records that source has for provided configuration before download starts, will help.

## Describe the alternative you’ve considered or used
getting it after download completed.
## Additional context
We can show this as part of schema discovery request.

**Comment by evantahler** [comment]
cc @sherifnada this would be helpful to display a sync progress bar... can you close this story and link to that proposed feature?
