### ISSUE TITLE
Source Intercom: conversion_parts is not fetched by the source

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9572]
*Is this your first time deploying Airbyte*: No
*OS Version / Instance*: debian-10-buster, GCP e2-standard-2
*Deployment*: Docker
*Airbyte Version*: _0.32.0-alpha_
*Source/version*: Intercom 0.1.12
*Destination name/version*: BigQuery 0.5.1

I have two issues with Intercom:
• Tables on “Incremental append/deduped” Sync mode appear as empty in Bigquery but tables on Full refresh Overwrite have data in them
• On `conversation_parts` table with Full refresh sync mode, the field `conversation_id` is always null. This prevents me from linking them back to the full conversation entity
I tried using both normalization options and Access Token has all Read permissions enabled. Let me know if I can help with anything! I haven’t seen any issue related on Github

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1642063449327900?thread_ts=1642063449.327900&cid=C01MFR03D5W

**Comment by sean-mckeever** [comment]
Chiming in as I have a very similar issue. Most of my intercom data has been able to sync as expected. However, the conversations_parts data is not loading correctly. 

The total airbyte sync of our Intercom data took 19 hours. However, 13+ of those hours were spent on the conversation_parts stream. At the end of this time, only 142 total records were created in the resulting conversation_parts table. (In reality, we should have greater than 100,000 conversation_parts).

Moreover, of the 142 conversation_part records that were created, there is no way to link them to the 'conversation' object. The conversation object does not have the conversation_part array the API says it can have, and the conversation_part records do not have a conversation_id.

**Comment by sean-mckeever** [comment]
I am still newer to this (so please correct me if I am off here), but it appears the Intercom API changed, which might be causing the issue.
Previously, it appears that when requesting all 'conversation' objects, they would each include an array of conversation_parts. Now however, the conversation_part array is only included when requesting a single conversation (and is not included when requesting all conversations).

As this appears to be the only way to access conversation_parts, the API now is no longer returning most conversation_parts and is not able to link conversations to conversation_parts

**Comment by lazebnyi** [comment]
Fixed in https://github.com/airbytehq/airbyte/pull/11206
