### ISSUE TITLE
Add container name for source/destination container launched by Airbyte worker

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9584]
## Tell us about the problem you're trying to solve
Today the worker launch containers using the command:
```
2022-01-18 22:49:20 INFO i.a.w.p.DockerProcessFactory(create):171 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/27940/0 --network host --log-driver none airbyte/destination-snowflake:0.3.24 write --config destination_config.json --catalog destination_catalog.json
``` 

we can add the tag `--name <docker-container-name>_<4-lenght-hash>`
With the name would be very easy to identify the container I need to inspect.

One example where this can be useful:
![image](https://user-images.githubusercontent.com/5154322/150031946-c90908cb-bb55-4cbb-b427-bf188bdb7a20.png)

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by shyngysnurzhan** [comment]
Hi, Marcos, can you suggest where can I get docker-container-name and 4-length-hash?

**Comment by marcosmarxm** [comment]
It's not possible today, this issue suggest the container name and hash as a solution
