### ISSUE TITLE
Create env variable DEBUGGING=true to allow verbose debugging

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9587]
## Tell us about the problem you're trying to solve
This variable can be used during a deployed instance to print more verbose response from connectors, databases or the platform.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by evantahler** [comment]
This might be a step in the right direction https://github.com/airbytehq/airbyte/pull/15895.
