### ISSUE TITLE
Fetch facebook marketing source in small batches

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9593]
## Tell us about the problem you're trying to solve
- Some of the streams in the Facebook Marketing source requires async processing on Facebook's end. Their processes are not very reliable, resulting in transient failures on our end.
- Currently we always try to retrieve all data within the specified date range with one API call, which means 1) it can take Facebook a long time to process the data, and 2) each failure is very expensive and can waste a lot of time.

## Describe the solution you’d like
- Fetch the data in multiple small batches.

## Describe the alternative you’ve considered or used
- There are probably other solutions. We should think more about this.

## Additional context
- https://github.com/airbytehq/oncall/issues/86

**Comment by misteryeo** [comment]
Revisit this once https://github.com/airbytehq/airbyte/pull/9805 is closed

**Comment by jpmmcneill** [comment]
Hey @tuliren 👋

Was there any further discussion on this? I think this is related to something we are seeing with our facebook-marketing pulls.
