### ISSUE TITLE
Investigate Python ERD generation tools

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#9595]
## Tell us about the problem you're trying to solve
Find a good Python tool to generate ERD schema for the source connector documentation. Estimate implementation time and complexity.

**[EPIC] Make the schema output by a source easier to discover and understand** #3731

**Comment by lazebnyi** [comment]
Done. Scoping below.
https://docs.google.com/document/d/15ZohXu_tnC1cYLsAfr4ccpsrCtx4Z14YFrcr2Dj0-oI
