### ISSUE TITLE
Standardize JDBC Connector Testing: Add JDBC string and property static tests 

### ISSUE THREAD

**Issue by noahkawasakigoogle** [airbytehq/airbyte#9598]
## Tell us about the problem you're trying to solve
No JDBC property/string tests for all JDBC connectors

## Describe the solution you’d like
Just add tests that pass in a `JsonNode config` with some values and check that the correct properties and JDBC string is generated. 

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?
Yes

**Comment by evantahler** [comment]
Closing, as this doesn't seem to be an in-progress issue
