### ISSUE TITLE
Fail checks on PRs that didn't run CI

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#9600]
Currently when you open a PR from a fork it won't run CI. But the PR will still be marked as all checks passed, since CI never ran:

![screenshot-20220119-143909](https://user-images.githubusercontent.com/877229/150142701-ec9b96a3-f6f1-4639-9e66-78a681ec7b41.png)

I think it would be benefitial if we'd have a check (or any of the CI steps) actually failing and marking a check as failed if a PR didn't run CI at all, just so we're aware before merging, that a PR hasn't passed CI.

Additionally it would also be nice if we could allow those PRs by a comment of a member/collaborator to actually run through CI. Something similar e.g. to this PR: https://github.com/elastic/kibana/pull/122174#issuecomment-1003171165 where the PR will initially hold off buildnig until a member leaves a comment that it's fine to have it run on CI.

**Comment by noahkawasakigoogle** [comment]
whoa.. are Airbyte PRs able to merge without passing all checks?

**Comment by evantahler** [comment]
cc @supertopher I think this kind of thing belongs with your new team

**Comment by cpdeethree** [comment]
This is completed.
