### ISSUE TITLE
Snowflake : Investigate removing Insert/GCS/S3 load methods 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#9602]
We have support for Snowflake Internal staging loading method. We should investigate if we can remove the following load methods 
 - [x] Insert
 - [ ] S3 Staging
 - [ ] GCS staging
 
 We should also keep in mind how would this change affect existing connectors and write a migration if required. Try to make  this change backward compatible

**Comment by ChristopheDuong** [comment]
Related issue even if the options were to disappear: https://github.com/airbytehq/airbyte/issues/9618

**Comment by sherifnada** [comment]
Scope is focused on inserts for this week, blob storage less critical
