### ISSUE TITLE
Snowflake : Support for  Airbyte cloud to work with Snowflake network policies

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#9603]
In snowflake warehouse a customer can create a network policy to only allow specific IPs to connect to a snowflake instance. If a customer has this setup, Airbyte cloud  should be able to work with this setup. 

1. We can expose a set of our cloud IPs so that customer knows which IPs to whitelist
1. ?

Ref : https://docs.snowflake.com/en/user-guide/network-policies.html#

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126635247520) by [Unito](https://www.unito.io)

**Comment by subodh1810** [comment]
Ref : https://airbytehq-team.slack.com/archives/C02TXT37Y3Y/p1642605670031600

**Comment by VitaliiMaltsev** [comment]
@subodh1810 please clarify if this ticket is related to snowflake source or destination? Or to both?
