### ISSUE TITLE
🐛 Source MongoDB: DBRefs are not handled

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9604]
## Environment
- **Airbyte version**:  0.35.2-alpha
- **Source Connector and version**: airbyte/source-mongodb-v2:0.1.11
- **Severity**: High
- **Step where error happened**:  Sync job

## Current Behavior
This issue was created following [this](https://airbytehq-team.slack.com/archives/C01MFR03D5W/p1642600734249300) slack discussion.
Link between mongo document can be expressed in Mongo with [Database Reference](https://docs.mongodb.com/manual/reference/database-references/).
I think our connector is not handling this kind of inter-document link properly, leading to this kind of error: `org.bson.cojavadecs.configuration.CodecConfigurationException: Can't find a codec for class com.mongodb.DBRef.`

## Expected Behavior
Properly parse document with DBRefs

## Logs
[sync logs](https://github.com/airbytehq/airbyte/files/7898074/logs-200-2.txt)

## Steps to Reproduce
1. Sync a collection that has documents with DBRefs

**Comment by NahidOulmi** [comment]
I am encountering this issue and will try to provide a quick fix to this, by ignoring the faulty bson field for example.

**Comment by NahidOulmi** [comment]
Here is a PR to fix this issue : https://github.com/airbytehq/airbyte/pull/10276

**Comment by alafanechere** [comment]
Closed after merge of https://github.com/airbytehq/airbyte/pull/10276
