### ISSUE TITLE
Add support for integrations tests in python sources

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#961]
## Tell us about the problem you're trying to solve
* I want to be able to write integrations tests in python sources outside of the standard tests. 
* I want these tests to run as part of the CI

## Current
* We don't run integrations tests other than standard tests for python sources.
* In our docs we imply that you can: [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/source-python/NEW_SOURCE_CHECKLIST.md.hbs#L23-L24) and [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connector-templates/source-singer/NEW_SOURCE_CHECKLIST.md.hbs#L24-L25), but you can't.

**Comment by ChristopheDuong** [comment]
Yes! I would be interested to know how to plug my integration tests as part of the build here:
`airbyte-integrations/connectors/source-file/integration_tests/integration_source_test.py`

**Comment by sherifnada** [comment]
@cgardens what prevents someone from running integration tests in a python module today? the steps would be: 
1. write the test and place it in the integration tests directory
2. add a task to gradle.build that runs it as part of the build, similar to the unit testing task.

**Comment by cgardens** [comment]
To my knowledge it's just that we don't have the Gradle stuff setup for it.
I know that chris and zazmic both wrote integration tests that they have
been able to run manually (not using Gradle). See the mailchimp and file
sources.
