### ISSUE TITLE
🐛  SonarQube doesn't measure Java code coverage

### ISSUE THREAD

**Issue by antixar** [airbytehq/airbyte#9613]
Now the SQ workflow doesn't measure Java code coverage. We need to fix it
All details of the current implementation are [here](https://github.com/airbytehq/airbyte/pull/8362)

**Comment by evantahler** [comment]
We've removed the sonarscan/sonarcube workflow from the project via https://github.com/airbytehq/airbyte/pull/17609.  Closing.
