### ISSUE TITLE
Snowflake : Benchmark snowflake destination in cloud and identify potential issues

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#9614]
After Liren finishes up with his benchmark work to create mock source, use it to benchmark snowflake destination in cloud

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126632370994) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment]
Warehouse Benchmark workspace: [`[Benchmark] Destination Warehouse`](https://cloud.airbyte.io/workspaces/f4bbed8e-8533-4d14-82dd-277b672164d8/connections)

**Comment by sherifnada** [comment]
goals: 
1. understand scale of data 
2. validate that every data type works with high performance (not focused on correctness)

**Comment by subodh1810** [comment]
I have not been able to carry out the benchmarking because the connector keeps dying. Ref : https://github.com/airbytehq/oncall/issues/124#issuecomment-1033042049

**Comment by evantahler** [comment]
Closing  - this will be part of the E2E test tool
