### ISSUE TITLE
Airbyte server container uses too much memory

### ISSUE THREAD

**Issue by isu182** [airbytehq/airbyte#9620]
## Environment
- **Airbyte version**:  0.35.5-alpha
- **OS Version / Instance**: GCP e2-standard-4
- **Deployment**: Docker
- **Source Connector and version**: MySQL 0.5.1
- **Destination Connector and version**: BigQuery 0.6.5
- **Severity**: High

## Current Behavior
When I start up the docker containers everything is fine. The **airbyte/server** container is using only 2.2% of the VM-s memory, until I load the UI in my browser. 
At that point the **airbyte/server** container starts eating up the memory like there is no tomorrow. It goes up to 35%-40% using more then 5 Gib of memory. 
But keep in mind there is no job running or any heavy task. I just loaded the connections list where I have 5 connections listed all with manual sync.  

## Expected Behavior
I would expect the container to release the memory after the page loads, because there is no memory heave task running.
I imagine this cannot be a common issue because I would have found other peoples complaints.

## Logs
`docker stats` before I load the UI in my browser
![before](https://user-images.githubusercontent.com/6310450/150211354-1883aa1a-cd5c-4e58-970e-024488d43914.png)

After I lead the UI:
![after](https://user-images.githubusercontent.com/6310450/150211553-06e07d28-3abc-443c-8a61-6b171384b822.png)

## Steps to Reproduce
1. start the containers: `docker-compose up -d`
2. check the stats: `docker stats`
3. load the UI: visit http://localhost:8000/
4. check the stats again: `docker stats` 

Thank you, and keep up the good work! Airbyte is fantastic tool.

**Comment by marcosmarxm** [comment]
@isu182 @priithaamer please test latest version #9636 tried to solve the issue.
