### ISSUE TITLE
Add Engagements endpoint to Hubspot API

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#9632]
See linked from Harvestr

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Source: Hubspot](https://app.harvestr.io/components/0/list/84ferjH7F)

**Comment by nataliekwong** [comment]
Working on it - test

**Comment by garygcd** [comment]
I saw per https://github.com/airbytehq/airbyte/pull/8887 that `engagements` now uses the `Get Recent `endpoint, which limits the record count.

Was this ticket opened for the purpose of working with `Get All`?

**Comment by gregklaus** [comment]
I've the same issue. 
I don't understand why they use the get recent endpoint.

**Comment by nataliekwong** [comment]
Hey @garygcd and @gregklaus  - you can follow this issue to modify the endpoint: https://github.com/airbytehq/airbyte/issues/26365.

As a temporary workaround you can try syncing the data first with a Full Refresh sync mode, which will sync all records with no rate limit, and then for subsequent syncs, switch to incremental afterwards if you're updating less than 10,000 records with each sync attempt.

**Comment by nataliekwong** [comment]
The Engagements stream is available as of v0.1.38 (released 2022-02-03). Read more about Hubspot here: https://docs.airbyte.com/integrations/sources/hubspot
