### ISSUE TITLE
Paginate Job History

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9645]
## Tell us about the problem you're trying to solve
When getting a list of jobs for a connection we should paginate the returned jobs. This method gets called frequently and should be relatively straight forward to paginate.

### Acceptance Criteria
- Determine what our API convention should be for pagination (this is the convention we will likely use everywhere).
- Implement it for job history endpoint.

**Comment by pmossman** [comment]
It looks like [pagination is already implemented ](https://github.com/airbytehq/airbyte/blob/master/airbyte-server/src/main/java/io/airbyte/server/handlers/JobHistoryHandler.java#L83-L91)for the job list endpoint.

The API [supports a pagination param](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L3116-L3118) with `pageSize` and `rowOffset`. I'll create a frontend issue to take advantage of this in the UI

**Comment by pmossman** [comment]
Frontend issue: https://github.com/airbytehq/airbyte/issues/10323
