### ISSUE TITLE
Integration Test for Basic Normalization Module

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#965]
## Tell us about the problem you're trying to solve
* This module should have tests that run against an external database (or maybe we could make them unit tests and run against a locally run postgres docker container). Either way, it needs more holistic tests.

Splitting this out from the main Basic Normalization issue: https://github.com/airbytehq/airbyte/issues/782

**Comment by ChristopheDuong** [comment]
As part of #970, we could add a test from (a generated dataset) with more than 100 columns?
https://github.com/airbytehq/airbyte/pull/970#pullrequestreview-530286919

**Comment by sherifnada** [comment]
this is now available
