### ISSUE TITLE
Alerting for the Demo

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9656]
## Tell us about the problem you're trying to solve
Often we learn about issues about our demo instance from users or anecdotal evidence from other employees. The demo is a lot of user's and customer's first interactions with Airbyte, so if it is broken, that's a big deal. We should be notified when there are problems programatically.

1. Identify the common issues that we have seen.
2. Set up monitoring and notifications to tell us when the demo is not working.

**Comment by harshithmullapudi** [comment]
# Proposal

We can create a slack channel initially and let failure notification flow into it. This can help us identify problems and we can be reactive and fix the issues.

**Comment by harshithmullapudi** [comment]
We have created #demo-airbyte-alerts channel and the errors of demo.airbyte.io are flowing into this channel.
