### ISSUE TITLE
Tracking version number being used

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/airbyte#967]
## Tell us about the problem you're trying to solve
We don't know what version of Airbyte our users are using. Knowing it would enable us to track how new versions are being adopted, and to provide better customer support

## Describe the solution you’d like
We need to add a property "version_id" to all events we sent. 
It's been added on https://docs.google.com/spreadsheets/d/1qQPMBdz86yMBiyXpjw91D3HoP6hN7yIPRmLrF7xWOgA/edit#gid=1567609168

@cgardens

**Comment by cgardens** [comment]
done.

**Comment by cgardens** [comment]
done in the API. waiting for it to be done in UI too. this issue tracks the UI work: https://github.com/airbytehq/airbyte/issues/1092

**Comment by cgardens** [comment]
done now: https://github.com/airbytehq/airbyte/issues/1092
