### ISSUE TITLE
Disable a sync if it is failing repeatedly

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9673]
## Tell us about the problem you're trying to solve
There is a point at which, if a sync is not going to succeed it should stop trying until a human intervenes. In an ideal world, the job would be able to say the failure state it was in and whether the failure was possibly fixed by a retry. While we will start exposing this metadata that will allow us to quarantine some jobs quickly, there will still be cases where we don't know if a retry will help but after a certain number of failed retries we want to stop.

## Describe the solution you’d like
There are a few things we need here, and possibly they should be addressed as different issues / tasks.
* The ability to detect that a job has failed for a reason that is not going to be fixed by retry. It requires either user, technical support intervention, or engineering intervention.
* In cases where a job fails repeatedly but isn't labeled non-retryable, we eventually stop retrying. We need to figure out what threshold we stop at.
* The UI needs to be transparent to the user about what is going on in each of these cases.
* After user intervention, the sync should start trying again.

**Comment by evantahler** [comment]
@andyjih We are doing this in cloud... did this features also get to OSS?

**Comment by andyjih** [comment]
@evantahler It did not, no.

**Comment by grhaonan** [comment]
> @andyjih We are doing this in cloud... did this feature also get to OSS?

Hi team, any timeline and plan to put this feature in open source version as well? this seems to be a standard requirement, we are also facing the same need. Thank you

**Comment by davinchia** [comment]
This is not something we are exposing in OSS for now.
