### ISSUE TITLE
can't delete connections through UI

### ISSUE THREAD

**Issue by answerMA** [airbytehq/airbyte#9674]
## Environment
- **Airbyte version**:  example is 0.35.5-alpha
- **OS Version / Instance**: Centos7
- **Deployment**:  Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Low 
- **Step where error happened**: Sync job 

## Current Behavior
as I clicked "delete this connection" in the connection setting page, and confirmed to delete, then nothing happened. the connection still exists

## Expected Behavior
connections should be deleted

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by cgardens** [comment]
@answerMA thanks for reaching out. if you refresh the page does it go away. i think there's a known caching issue in the UI.

**Comment by wjmolina** [comment]
It doesn't go away even if you refresh the UI. In fact, when I click on its "Sync now" button, I get the message
```
Something went wrong
Internal Server Error: The connection manager workflow for connection 96310eb8-f96c-4d63-b69c-244a4940a73b is deleted, so no further operations cannot be performed on it.
```

**Comment by mattppal** [comment]
I'm having the same issue

**Comment by wjmolina** [comment]
> I'm having the same issue

You could set the `status` of the offending `connection` to `deprecated` in the Airbyte database.

**Comment by craunas** [comment]
Im getting the same error message on v.44.2 when generating connections with Octavia CLI. The connections was orginally created  v0.40.29 and I wanted to move them to an Airbyte instance on a newer version.

Had a quick look in the db and one thing I noticed was that the connections created manually on the new version got an source_catalog_id referring to an entry in public.actor_catalog.

The connections imported by Octavia was missing source_catalog_id.

Any workaround or solution for this?

**Comment by katesclau** [comment]
I had a similar issue, where the connection manager and the connection were unresolved, and the only thing that fixed it for me was to delete the connection from the Airbyte db hard. After that, I was able to recreate the connection.
