### ISSUE TITLE
Research Facebook Marketing source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#9676]
## Complete the following exercise for Facebook Marketing source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:

[EPIC] GA & Beta Connector Research #9675

**Comment by karinakuz** [comment]
https://docs.google.com/document/d/1lQlxwLt22CFMAG3qTWYn4MpRSi2XCLQVqEkb0XeqBeA/edit?usp=sharing

**Comment by misteryeo** [comment]
Reviewed and looks good!

**Comment by ycherniaiev** [comment]
@misteryeo We need to restore research since Karina's research is lost.
https://docs.google.com/document/d/1Hle3k7kWsItRwO3vPfKlZPDQmmDNelsgzsT-upjz2k8/edit#

**Comment by misteryeo** [comment]
Thanks for reopening - the restored one looks good.

cc: @YowanR to clarify and close as needed

**Comment by YowanR** [comment]
LGTM -- Closing this research as complete. Thanks @ycherniaiev
