### ISSUE TITLE
Research Google Ads source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#9677]
## Complete the following exercise for Google Ads source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:
https://docs.google.com/document/d/1zOu9rBTHLg3JX3oI770B-WNaEkD88saKqp7PjG1Cqr0/edit?usp=sharing

[EPIC] GA & Beta Connector Research #9675

**Comment by igrankova** [comment]
@misteryeo, I've finished the research, you can find doc in the description. Let me know if I can do something more for this task.

**Comment by misteryeo** [comment]
Reviewing @igrankova and adding a few comments. But wanted to say that so far from the research docs, this is the gold standard - amazing work! Love the detail and the breakdown of information!

**Comment by igrankova** [comment]
Hi, Andy!Thank you very much for such a high evaluation of my work. I will do my best to continue on a same level. I’ll take into account comments and make updates accordingly. Iryna GrankovaSystem Business Analyst (Unblocker)Global Logic+380636306253 From: AndySent: 27 січня 2022 р. 19:57To: airbytehq/airbyteCc: Iryna Grankova; MentionSubject: Re: [airbytehq/airbyte] Research Google Ads source connector (Issue #9677) Reviewing @igrankova and adding a few comments. But wanted to say that so far from the research docs, this is the gold standard - amazing work! Love the detail and the breakdown of information!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by igrankova** [comment]
@misteryeo Andy, can I close this issue or I need to add something more here?
