### ISSUE TITLE
Source Kafka: Basic normalisation is not working

### ISSUE THREAD

**Issue by answerMA** [airbytehq/airbyte#9683]
## Environment
- **Airbyte version**:  example is 0.35.5-alpha
- **OS Version / Instance**: centos7
- **Deployment**:  Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
I set Kafka as source, while set postgres database as destination.

then data with json format like {"time":"2022-01-01", "data":100} feed to kafka.

when I check the source catalog, it says the schema is fixed like 

Kafka subscribe method: {"topic_pattern":"timeseries","subscription_type":"subscribe"}
{"type":"CATALOG","catalog":{"streams":[{"name":"timeseries","json_schema":{"type":"object","properties":{"value":{"type":"string"}}},"supported_sync_modes":["full_refresh","incremental"],"default_cursor_field":[],"source_defined_primary_key":[]}]}}

why am i get the json scheme like {"value":{"type":"string"}} ? It should be like {data: type, time:type} something

so at this time, I come up a workaround,

at first time, I have to use connection with basic norm way to sync data from kafka,

then I switched basic norm option to raw norm, and click sync now

next I modified the destination_catalog.json file which created by schduled job before, set up new shema which I wanted, then run the destination_catalog command again, thus will loader correct data and schema into postgres tables

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by answerMA** [comment]
Hey bro, that's awesome, and it really works fine now.

May I know if in the future this feature will be added into kafka source as it tranforms data into correct schema automatically ?

**Comment by marcosmarxm** [comment]
Closed because lack of information. @answerMA please reopen if the issue continue and fill the template correctly.
