### ISSUE TITLE
Documentation bug: Both onboarding videos point to the same video

### ISSUE THREAD

**Issue by makalaaneesh** [airbytehq/airbyte#9692]
### Tell us about the documentation you'd like us to add or update.
Hi! In the onboarding section on the airbyte webapp, both the video buttons point to the same video (demo of salesforce->snowflake integration). 

![image](https://user-images.githubusercontent.com/6829754/150523582-3335fbea-f1e3-411c-9064-5b128e6e2b33.png)

**Comment by marcosmarxm** [comment]
This page was removed.
