### ISSUE TITLE
Support for docker run's "--add-host" argument

### ISSUE THREAD

**Issue by rnagy90** [airbytehq/airbyte#9693]
It would be nice, to add additional host for the containers started by the `airbyte-worker`.
Because you are not able to "hack" this argument in the `DOCKER_NETWORK` environment variable after the network name, it's a little tricky to reach applications running on the host machine.
The most common suggestion is to add the well known "magic" domain to the container's **/etc/hosts** file like this:
```
--add-host host.docker.internal:host-gateway
```
or in compose
```
extra_hosts:
  - "host.docker.internal:host-gateway"
```
After this you can reference the host machine's network via the `host.docker.internal` domain.

**Example**:
The airbyte stack is running in a docker environment, but the PostgreSQL database is running in the host machine (security, maintenance reasons and for non docker based applications).
The configured airbyte destination is a PostgreSQL one and we want to reach it from the local network.

My suggestion is to add it as an optional environment variable and I think the most convenient name for this is _EXTERNAL_HOSTS_.

**Workaround**
If someone want a workaround for this, you can use a custom, external network and it's gateway combination to reach the host machine's application.

1.: create a docker network manually.
2.: set the `DOCKER_NETWORK` environment variable in the **worker** service as the previously created network's name
3.: enable the network's `Gateway` value in the **pg_hba.conf**
4.: configure the PostgreSQL source/destination host also with the `Gateway` value
5.: (optinally) if you have to, add every container in the stack to the network

**Comment by tmotyl** [comment]
How do you ".: set the DOCKER_NETWORK environment variable in the worker service as the previously created network's name" ?
If I'm not mistaken, airbyte is creating new container to run postgres connector, so it's not using the worker container directly?

**Comment by tmotyl** [comment]
after investigation I found out that the destination postgress container (which is created on the fly) is being connected to "host" network.
So using "localhost" as host worked out.
![image](https://github.com/airbytehq/airbyte/assets/515397/b437acc6-4513-4da1-81ed-c8f63c91da45)

**Comment by davinchia** [comment]
No longer relevant since we deprecated docker.

**Comment by rnagy90** [comment]
> after investigation I found out that the destination postgress container (which is created on the fly) is being connected to "host" network. So using "localhost" as host worked out. ![image](https://private-user-images.githubusercontent.com/515397/314448992-b437acc6-4513-4da1-81ed-c8f63c91da45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODk3MjcsIm5iZiI6MTcyNzY4OTQyNywicGF0aCI6Ii81MTUzOTcvMzE0NDQ4OTkyLWI0MzdhY2M2LTQ1MTMtNGRhMS04MWVkLWM4ZjYzYzkxZGE0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwOTQzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmM0ZDUxOGNjMmNjYmRmNGI1ZmZiZmEzMDcxMmIxYmNlNDVlYjZjZGRlOWYxOWI0NjVjMGY5NzJiYjVkMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.d-XbtacFWjN4hE2YIPqxxslxKgznAXGOyU5aq2KvSEA)

I am sorry for the late reply, but I wasn't very active in these months and totally forgot about this ticket.
Thank you for you investigation, but we experienced that the `host.docker.internal` approach is not very reliable (also in other stacks), because on server restarts we had to change some configurations.
Because of this, we used internal domains to resolve the issue.
