### ISSUE TITLE
Source Chargebee: add new streams `coupon`, `event` and `transaction`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9702]
## Tell us about the problem you're trying to solve
Add streams not supported to Chargebee connector.

## Describe the solution you’d like
A clear and concise description of what you want to see happen, or the change you would like to see

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by marcosmarxm** [comment]
Sure @aadityasinha-dotcom ! I'll assign this issue to you

**Comment by aadityasinha-dotcom** [comment]
Thanks 👍

**Comment by joelluijmes** [comment]
I don't know if you were still planning to work on this @aadityasinha-dotcom, nor didn't want to take over. But I've just noticed this issue, yet already created a PR to implement `event` stream #10143 🙈

**Comment by aadityasinha-dotcom** [comment]
I guess I will work on the `coupon` and `transaction` stream. @joelluijmes
