### ISSUE TITLE
Push Orb requests to Datadog and add alerting for exceptions

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#9710]
## Tell us about the problem you're trying to solve
See tech spec for context on the billing vendor project: https://docs.google.com/document/d/1WLr7Leaj5Iyy5bBEjr1TGhNL8HhSB_evbM_psEwKyAI/edit#heading=h.fa72b39y2m99

As Orb is a fairly new product, we have taken steps to protect ourselves from any downtime in the Orb API, e.g. [caching responses](https://github.com/airbytehq/airbyte-cloud/pull/878) and automatically retrying customer initialization. However, these changes mean that failures when calling the Orb API are hidden from our users as well as our engineers.

As Airbyte engineers, we would like to have greater visibility into our calls to the Orb API, which will help us understand the following which may be helpful for debugging:
- If our API calls are failing (and which status codes they are failing with - are they input failures from us, or failures caused by Orb e.g. downtime?)
- How long our API calls are taking - will be useful if we need to investigate degraded Airbyte UI performance
- Pagerduty alerts if Orb API call error rate reaches above some threshold so that our OC can contact Orb. Can start with a low threshold (e.g. 5%) and modify this if too noisy

## Describe the solution you’d like
- Modify our [Orb client](https://github.com/airbytehq/airbyte-cloud/blob/master/billing/src/main/java/io/airbyte/billing/orb/OrbClientImpl.java) to track Orb requests, responses, and request->response times in Datadog
- Use the [DogStatsDMetricSingleton](https://github.com/airbytehq/airbyte/blob/master/airbyte-metrics/lib/src/main/java/io/airbyte/metrics/lib/DogStatsDMetricSingleton.java) to push the above data to Datadog
- Set up alerting on these these Orb metrics to post in slack or pagerduty when failures occur above some frequency threshold

**Comment by jdpgrailsdev** [comment]
@davinchia and I spoke about the broader use of APM (application performance monitoring) within OSS and cloud.  Here are a few highlights of our conversation:

- We both agreed that using APM for the types of metrics referenced in this ticket is the correct approach over having to hand-roll the recording of stats via the statsD integration.
- We discussed the differences between using the [Open Telemetry project](https://github.com/open-telemetry) vs the [DataDog vendor specific APM Java agent](https://app.datadoghq.com/apm/docs?architecture=host-based&language=java).

The **tl;dr** of the above discussion is that using OTEL would have benefits beyond this ticket -- it would allow the OSS side to use it and allow customers to provide their own configuration regarding which observability platform receives the data (Prometheus, New Relic, Data Dog, Lightstep to name a few support OTEL for APM).

As a result of the discussion, my plan is to time-box utilizing the OTEL APM agent in the Billing app to see if 1) we can get it to work and 2) it provides us with the necessary level of telemetry data to not only fulfill this ticket, but also give us application-level telemetry to be able to monitor the performance of our applications.  If OTEL doesn't work for us, it is a very small additional effort to switch over to the DataDog vendor specific agent for APM.

This ticket will be used as a springboard to gauge the direction of the larger effort to add APM to all of our apps.

**Comment by pmossman** [comment]
@jdpgrailsdev I'm going to close this since you marked it as 'Done', but feel free to re-open if that's not right
