### ISSUE TITLE
require acknowledgement of terms when using alpha or beta connectors

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9712]
We need to add in-app acknowledge of terms prior to using alpha or beta connectors. If I understand correctly, all connectors will show in the drop down, but clicking on one of the alpha/beta connectors will trigger some sort of display which requires confirming some terms.

**Comment by jrhizor** [comment]
@misteryeo 
1. Can you confirm that this issue covers both "Alpha Connector Access" and "Alpha Beta In-app Terms" from [your spreadsheet](https://docs.google.com/spreadsheets/d/12KARzawjbPrLYsQMDIYrwWqtVhMtgFazw45aPrgGxbI/edit#gid=0)?
2. When will we have a mockup for this?

**Comment by juliachvyrova** [comment]
@jrhizor I couldn't find texts for `beta` connectors in figma. Is the text the same as for `alpha`? Or we don't need `beta` for this release?

**Comment by jrhizor** [comment]
@misteryeo For alpha connectors we have:
```
<b>Alpha</b> connectors are in active development. The release may not be feature complete and breaking changes may be introduced. \n\nOn occasion, we will reach out to users to gather feedback so that we can improve the connector."
```

Should we have the exact same for beta or different messaging?

**Comment by misteryeo** [comment]
Thanks for raising this - we should have different messaging - let's use the following:

- **For Alpha:** "Alpha connectors are in development. We strongly discourage production use cases and do not offer support SLAs. The release may not be feature complete and breaking changes may be introduced."
- **For Beta:** "Beta connectors are considered stable and reliable with no backwards incompatible changes but has yet to be used by a larger group of users so we expect there to be some small issues and bugs to iron out. 

As an FYI, this is just paraphrasing what we plan on publishing [in public docs](https://docs.google.com/document/d/1R6SDCdbIGwR-j7D4OKnNTHHsvZ9kkuEQ3StOsDNd5Gw/edit#) at launch.
