### ISSUE TITLE
Please Provide scram-sha-512 authentication support for kafka.

### ISSUE THREAD

**Issue by hitk6** [airbytehq/airbyte#9726]
I am using airbyte to send data to kafka cluster but in airbyte there is no option of scram-sha-512 authentication with SASL_SSL. 
Currently, airbyte only supports scram-sha-216 authentication with SASL_SSL.

**Comment by harshithmullapudi** [comment]
Hey  @hitk6 will you be able to contribute to this?

**Comment by marcosmarxm** [comment]
Closed by #10186
