### ISSUE TITLE
fix "sources are tools..." copy during onboarding

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9731]
The onboarding flow has incorrect copy at various steps referencing sources instead of destinations. Every onboarding step says "Sources are tools" underneath.

**Comment by juliachvyrova** [comment]
In figma there are "Sources are tools" text on sourse/destination/connection steps. 
@jrhizor could you give me right text for these steps?

**Comment by jrhizor** [comment]
Sorry for the late reply on this, didn't notice it before.

For sources: "Sources are connectors that pull data from a data source."
For destinations: "Destinations are connectors that pushes data to a data source."
For connections: "Connections represent a sync between a source and a destination."
