### ISSUE TITLE
set "Every 24 hours" as the default sync frequency

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9733]
It's very common for new users to set up the connection settings and fail when they don't enter in a sync frequency. It's kind of difficult to figure out what field isn't correct.

**Comment by jrhizor** [comment]
@misteryeo I know in the spreadsheet thread you originally mentioned defaulting this to manual, but I believe it would make more sense to default this to every 24hr since 1) it will start the users first sync right away automatically 2) reading "every 24 hours" instantly makes a user think of schedules vs "manual" and 3) it encourages a user to get the value of regular updates. Please let me know if you disagree.

**Comment by misteryeo** [comment]
@jrhizor This makes sense to me.

Just want to loop in @nataliekwong @erica-airbyte in case their experience with customers deviates from this proposed path.

**Comment by nataliekwong** [comment]
Agreed with defaulting to every 24 hours.

**Comment by erica-airbyte** [comment]
@misteryeo my only concern about defaulting to a times frequency is if they are just testing and it just is successful and then they forget that it is running and they do not realize it then they get a bill from their destination and get angry at us. I think we need to make sure that we have automated account disable after a trial end date. Is that planned for GA? If so then I agree with a 24 hour sync default

**Comment by jrhizor** [comment]
We will stop syncing after they run out of free credits. Is that sufficient?

**Comment by erica-airbyte** [comment]
Yeah that could work
