### ISSUE TITLE
temporarily hide role selection in cloud

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9734]
Users can only give admin rights to any user in the account, and do not see value in seeing the "Role" selection on user creation.

This is temporary since eventually we will offer other roles for the user.

**Comment by misteryeo** [comment]
**Issue was linked to Harvestr Discovery:**  [Hide "Role" for Users](https://app.harvestr.io/components/0/list/lkyLByBFT)

**Comment by edmundito** [comment]
Location: Settings -> Access Management -> Invite User
