### ISSUE TITLE
standalone connector catalog in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9736]
Representing our connectors in-app in a visual way that makes improves discoverability and increases real estate to include more information about each given connector. Mock ups [here](https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=29958%3A127349).

**Comment by jrhizor** [comment]
@sherifnada we will need a way to share the information necessary for a catalog from connectors (most likely with something similar to how we load the docs in the UI).

**Comment by edmundito** [comment]
@timroes this is currently in the product backlog but it's very big - can you re-prioritize?

**Comment by timroes** [comment]
@sherifnada Could you clarify why we closed this? This is something we'd still like to go for, since we see that the selection and specifically discoverability of connectors in the UI isn't really great at the moment.

**Comment by sherifnada** [comment]
@timroes was doing backlog cleanup. I just closed this ticket since I think this will likely resurface with a lot more details in the future. Happy to reopen if you think it's useful!

**Comment by timroes** [comment]
@sherifnada It's fine keeping this closed if we plan to write a PRD still for this later on :) Just wanted to make sure this wasn't discarded fully.

**Comment by sherifnada** [comment]
yup definitely not completely discarded
