### ISSUE TITLE
put the cloud webapp behind a CDN

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9741]

**Comment by jrhizor** [comment]
@davinchia Who should I have @Jamakase talk to on the infra side to make sure this gets out?

**Comment by jrhizor** [comment]
We should include assets/markdown files from the frontend build in the CDN release.

**Comment by davinchia** [comment]
@jrhizor can he talk to @paulpalamarchuk and on https://github.com/airbytehq/airbyte-cloud/issues/755

**Comment by jrhizor** [comment]
I think the two of them did talk recently? Are there any more open questions @Jamakase and @paulpalamarchuk ?

**Comment by timroes** [comment]
@Jamakase @paulpalamarchuk Could you give a quick status update about this here, please?

**Comment by Jamakase** [comment]
@timroes just as Jared said - I have provided all the info to Pavel already via slack.

Not aware about the progress though.

**Comment by timroes** [comment]
Closing this, since this is already happening as of today.
