### ISSUE TITLE
Use logged in user information to identify in Fullstory

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#9747]
We should use the [`identify` API](https://developer.fullstory.com/identify) in Fullstory to pass on information about the actual signed in user, similar to what we do with [segment](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/core/analytics/AnalyticsService.ts#L27). We should ideally pass in most of the information we have on the [`user`](https://github.com/airbytehq/airbyte/blob/master/airbyte-webapp/src/packages/cloud/lib/domain/users/types.ts) object,

**Comment by jrhizor** [comment]
@nataliekwong what's the urgency of this?

**Comment by timroes** [comment]
Since this issue was originally from me: I wouldn't see it as super urgent. It would help inspecting fullstories and especially filter internal traffic from real users, which would be benefitial, but it's not a "must happen within the next sprint". Natalie, please feel free to add if you have a different priority for this.
