### ISSUE TITLE
add a progress bar for running the check connection and discover commands

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9756]
For checking connection and running the discover commands, we should expose a progress bar. Since it's very non-trivial to set this up for the first time, we should have the progress bar behavior match the "expected" durations of each of the operations and exit early.

For checking connections: 15s
For discoveries: 2min

**Comment by jrhizor** [comment]
@Jamakase do we need mockups for this?

**Comment by cgardens** [comment]
Cool! How is the progress bar going to track progress? Is there a backend API?

**Comment by cgardens** [comment]
Nice! Clever way of thinking about the first iteration.
