### ISSUE TITLE
🐛 Source Amazon S3: wrong schema stored in state  

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#9758]
## Environment
* Airbyte: 0.35.5-alpha
* Source: airbyte/source-s3 0.1.9
* Destination: airbyte/destination-bigquery 0.6.5

## Current Behavior
[Related slack conversation](https://airbytehq.slack.com/archives/C01MFR03D5W/p1643028088050800)

1. The user sets a valid schema for his Parquet file in the source configurations.
2. A different schema is stored in the state, 
3. The catalog is corrupted because it does not describe the real data schema.
4. Normalization fails

## Expected Behavior
1. User forces a schema in the source configurations
2. Sync fails if the type cast can't happen
3. The schema stored in the state for incremental sync matches the schema defined by the user and the underlying coerced date.

## Logs
Schema defined by the user in the source config:
```json
{"id": "string", "twitter": "string", "scraped_at": "string"}
```

Setting state logs (`scraped_at` field is considered to be an integer): 
```
2022-01-22 18:18:13 [44msource[0m > Setting state of twitter_screen_names stream to {'schema': {'id': 'string', 'twitter': 'string', 'scraped_at': 'integer', '_ab_source_file_url': 'string', '_ab_additional_properties': 'object', '_ab_source_file_last_modified': 'string'}, '_ab_source_file_last_modified': '2022-01-22T17:51:10+0000'}
```

But during schema inference this is logged, showing that the user defined schema is used for inference, but that it's different from what is stored in the state.
```
2022-01-22 18:18:15 [44msource[0m > Detected mismatched datatype on column 'scraped_at', in file 'twitter/2022/01/22/twitter_screen_names.parquet'. Should be 'string', but found 'integer'. Airbyte will attempt to coerce this to string on read.
```
## Steps to Reproduce
1. Upload a parquet file with int column
2. Create an S3 source with custom schema, declaring the int column to be a string
3. Run the sync
4. Check if the source catalog has the custom schema defined by the user

**Comment by feliche93** [comment]
Sample file with following schema:

```
<pyarrow._parquet.ParquetSchema object at 0x11c85eec0>
required group field_id=-1 schema {
  optional binary field_id=-1 id (String);
  optional binary field_id=-1 twitter (String);
  optional int96 field_id=-1 scraped_at;
}
`
``

**Comment by alafanechere** [comment]
Hi @feliche93, do you still have this problem? Could you please try to recreate a connection with the S3 source in its latest version?

**Comment by sherifnada** [comment]
@lazebnyi can you confirm you were able to reproduce this issue? George's [review indicates he wasn't able to](https://github.com/airbytehq/airbyte/pull/12105#pullrequestreview-953189464)

**Comment by lazebnyi** [comment]
@sherifnada Few days ago we discussed with George about that issue. And unfortunately I couldn't reproduce on real data and only with mocking some data I can get those issue. And as we discussed with @Phlair we can close issue and PR. What you think about that?
