### ISSUE TITLE
Add mailchimp docs

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#976]
## Tell us about the documentation you'd like us to add or update
Mailchimp does not currently have gitbook documentation. This issue encompasses: 

- [ ] add documentation for Mailchimp on gitbook 
- [ ] update the spec to point to the gitbook docs
- [ ] hotfix the published mailchimp image

**Comment by cgardens** [comment]
Good call. Forgot to do this after merging zazmic's mailchimp work.
