### ISSUE TITLE
Database sources (Postgres, MySQL, MSSQL, etc) cannot sync only a subset of columns

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#9771]
## Issue Summary
- Currently there is no way to sync a subset of columns using the Postgres source connector.
- When setting up a connection, we can only choose which tables to sync, but not columns.
- If the user account used for setting up the connection only has partial permission, and can only access a subset of columns, the catalog will still show the full table with all columns (this is unexpected), and the connection check will pass. However, the data sync will fail with `permission denied` exception.

## Temporary Solution
- The short term workaround is to create a view on the subset of columns to sync, and create a user with full `SELECT` permission on that view.

## Reference
- https://github.com/airbytehq/oncall/issues/112#issuecomment-1020541589
- https://github.com/airbytehq/oncall/issues/129
- https://github.com/airbytehq/airbyte/issues/2227

## Notes
It is unclear how the user account with partial table permission can retrieve the full table catalog, or even catalogs of other tables and views that the account has no permission to. Here is the script to reproduce this:

```sql
-- connect with an admin user to a database named "postgres"
create schema if not exists column_permission_test;

set search_path to column_permission_test;

create table t1 (col1 integer, col2 boolean, col3 integer, col4 boolean);
insert into t1 (col1, col2, col3, col4) values (1, true, 1, false);
insert into t1 (col1, col2, col3, col4) values (2, true, 2, false);
insert into t1 (col1, col2, col3, col4) values (3, true, 3, false);
insert into t1 (col1, col2, col3, col4) values (4, true, 4, false);
insert into t1 (col1, col2, col3, col4) values (5, true, 5, false);
select * from t1;
-- output all columns

-- the following role can only read col1 and col2 in table t1
create role column_permission_role login password 'password';
grant connect on database postgres to column_permission_role;
grant usage on schema column_permission_test to column_permission_role;
grant select (col1, col2) on table t1 to column_permission_role;

-- read the table with permission to only col1 and col2
set role column_permission_role;
select * from column_permission_test.t1;
-- permission denied for table t1
select col1, col2 from column_permission_test.t1;
-- output col1 and col2

-- create view on col1 and col2
create view t1_col12 (col1, col2) as select col1, col2 from t1;
select * from t1_col12;
-- output col1 and col2

-- create view on col3 and col4
create view t1_col34 (col3, col4) as select col3, col4 from t1;
select * from t1_col34;
-- output col3 and col4
```

As of Postgres source version `0.1.7`, after running the above script, set up a Postgres source connector with the `column_permission_role` user. The catalog it retrieves will include all four columns of the table `t1`, and its views.

See the details and the experiment in https://github.com/airbytehq/oncall/issues/129.

**Comment by grishick** [comment]
I think this is done now with column selection

**Comment by fran-martinez-frontiers** [comment]
Hi @grishick,
Can you show how to select the columns. I was not able to find it.
Thanks
