### ISSUE TITLE
connection doesn't work after updating source schema

### ISSUE THREAD

**Issue by answerMA** [airbytehq/airbyte#9777]
## Environment
- **Airbyte version**:  example is 0.35.5-alpha
- **OS Version / Instance**: centos7
- **Deployment**: Dockerv
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**:  Low
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
In the connection setting page, as I click the button 'Update latest source schema'.

it reports "Pending" in the Sync History, and says waiting for the logs.

and nothing happened for a long time

## Expected Behavior
*Tell us what should happen.*

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by answerMA** [comment]
yes, these changes for the source has been saved. At that time I didn't know that fact we can use API to modify catalog.json, so I have to change source to try to make the correct scheme be shown at connection settings page. So, once I save the changes for source, and click update the latest source shema, it then died. But I have not tried to update destination, because nothing changed for destination.

**Comment by alafanechere** [comment]
@answerMA You should update the source schema using the API. The source schema is defined by the connector and modifying its catalog with the API can lead to unexpected errors.

**Comment by marcosmarxm** [comment]
Close because lack of information.
