### ISSUE TITLE
Time based synchronisations 

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#9788]
## Tell us about the problem you're trying to solve
There are some sync's that when writing to Redshift are maxing out the database. 

While this is fine if it was out of hours during working hours it causes issues. 

We could increase the size of Redshift there is cost associated with that when it is idle overnight.

## Describe the solution you’d like
Time based synchronisation of jobs allowing them to run at specific time as configuration option. 

## Describe the alternative you’ve considered or used
Not found another one.

**Comment by jrhizor** [comment]
This is a known pain point. Most people get around this today by using Airflow/Prefect/crons to call the Airbyte API to run manual syncs in a specific timeframe. 

We will also offer support for this in https://github.com/airbytehq/airbyte/issues/2170 (we're working on it soon!)

Closing this issue as a duplicate.
