### ISSUE TITLE
Segment calls 'attempt_id' don't align

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#9796]
## Current Behavior
The first attempt_id has changed to now record as 1 in the connector_jobs Segment call after January 20, 2022. The attempt_id  for connector_jobs  now starts at 1 (used to start at 0), whereas the attempt_id for credit_consumption  still begins at 0. This change looks like it took effect on 1/20, so any credit usage dashboards show 0 credits used after 1/20 as the join between the two tables is required to get the connection metadata.

Example of 1 connection from BigQuery where you can see at which job it switched from 0 to 1:
`select sent_at,connection_id,job_id,attempt_id from api.connector_jobs where connection_id = '02b8df9b-f125-4429-baff-b89ff2d91c67' and attempt_stage = 'ENDED' order by attempt_id desc
`
Link to originating Slack: https://airbytehq-team.slack.com/archives/C02U2SSHP9S/p1643128164085700

## Expected Behavior
The first attempt_id in the connector_jobs table should start at 1, not at 0. Or the credit consumption should match to start at 0 as well. Ideally it just goes back to what it was, but if we can't, then the next best solution is to have them match.

**Comment by ChristopheDuong** [comment]
The `attempt_id` sent to Segment is not a real id, it's based on the size of the attempts list in the job object:
https://github.com/airbytehq/airbyte/blob/e3e05d79655bc0b2b4c3fbc0c05b8d90fce6dcd8/airbyte-scheduler/persistence/src/main/java/io/airbyte/scheduler/persistence/job_tracker/JobTracker.java#L124

**Comment by timroes** [comment]
Removed the FE team, since this seems to be a backend event.
