### ISSUE TITLE
Source Google Ads: Add new fields to keyword report and search performance report

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9835]
## Tell us about the problem you're trying to solve

Requested by Adriel from Cart.com

For the "keyword_report" could you add these fields:
- Campaign
- Ad Group
- Cost
- Clicks
- Impressions
- Conversions
- Conv. Value
- Quality Score
The documentation for those can be found here: https://developers.google.com/adwords/api/docs/appendix/reports/keywords-performance-report

Could we also bring in the Search Query Performance Report. These are the necessary fields:
- Date
- Search Keyword
- Search Keyword Match Type
- Campaign
- Ad Group
- Spend
- Impressions
- Clicks
- Conversions
- Conv. value
- Quality Score

## Describe the solution you’d like
Have this fields to generate better reports

## Describe the alternative you’ve considered or used
Wait until have this fields enabled

## Additional context
None

## Are you willing to submit a PR?
Not this time.

**Comment by Znk5Lo6YPEtfe3D6rIK3wfNa19bwn4qfGlTFIun** [comment]
I need these 2 fields for the Google Ads connector:
Conversions by Conversion Time
Conversion Value by Conversion Time

**Comment by tolik0** [comment]
For keyword_report new fields are added in [#30091](https://github.com/airbytehq/airbyte/pull/30091/files#diff-05dd7328488af2d1c3a8325ecd212fbfc924f0da5ccfde6924bf244bdf35abfd). Other stream is from old version of Google Ads
