### ISSUE TITLE
Facebook Marketing Source: Support "Replicate Incremental Deletes"

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#9842]
## Tell us about the problem you're trying to solve
Support replicating incremental deletes to reach parity for GA connector as per [research](https://docs.google.com/document/d/1lQlxwLt22CFMAG3qTWYn4MpRSi2XCLQVqEkb0XeqBeA/edit#).

**Comment by sherifnada** [comment]
cc @antixar about your question during our call: incremental deletes are not a special feature of the Airbyte protocol. They are implemented using the same primitives available today. 

For example, Postgres CDC (which replicates deleted records) using the following mechanism: 

- each stream has a primary key
- each stream has a cursor field
- each stream has a `_ab_deleted` field

to indicate that the record with primary key `X` was deleted, the connector outputs a record with primary key `X`, higher cursor field than the previous output, and `_ab_deleted` = true. All other fields in the record would be null. 

For example: 

```
# first appearance of a record
{primary_key: 1, cursor: 10, name: sherif, favorite_food: pizza, _ab_deleted: false}
...
# when the record is deleted
{primary_key: 1, cursor: 11, name: null, favorite_food: null, _ab_deleted: true}
```

Using the incremental dedupe sync mode, this achieves the effect of incrementally "deleting" records in the destination

**Comment by misteryeo** [comment]
FYI, @sherifnada will dig into this tomorrow @lazebnyi

**Comment by sherifnada** [comment]
@lazebnyi since we already support pulling deleted/archived records, we should just add a note to the docs (in the table which says support incremental deletes) detailing what it means, something like: 

> The FB API doesn’t have a concept of deleting records in the same way that a database does. While a user could archive or delete an ad campaign, there is still a record of that campaign having existed in the FB API. If configured by the user, the Facebook connector replicates records for campaigns or ads even if they were archived or deleted from the Facebook platform.
