### ISSUE TITLE
Destination MongoDb: Upload custom certificate to connect to a replica-set

### ISSUE THREAD

**Issue by farisam** [airbytehq/airbyte#9843]
Hi Airbyte Team,

I’m trying to connect the destination to alicloud apsaraDB for mongoDB and I get this error:

> Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@2575f671. Client view of cluster state is {type=REPLICA_SET, servers=[{address=dds-pub.mongodb.ap-southeast-5.rds.aliyuncs.com:3717, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}

I already open this issue on slack (https://airbytehq.slack.com/archives/C01VDDEGL7M/p1643283752262100) and airbyte team suggest me to open an issue and upload the custom ssl certificate. Can you provide me the link to upload the certificate? 

Thanks

**Comment by farisam** [comment]
hi @alafanechere , seems like my issue is duplicate with my issue #9843 , can you elaborate more?

**Comment by alafanechere** [comment]
> hi @alafanechere , seems like my issue is duplicate with my issue #9843 , can you elaborate more?

Sorry, I pasted the wrong issue number. I fixed my previous message.

**Comment by AndriBastiaanssen** [comment]
I have the same problem. Is there any solutions?
