### ISSUE TITLE
Require two airbyter reviews on changes to spec.json

### ISSUE THREAD

**Issue by edgao** [airbytehq/airbyte#9844]
Until we have more robust backwards-compatibility handling for breaking spec changes, require two airbyter reviews when the spec is changed to reduce the chance of not catching a breaking change. The second reviewer should only need to read spec.json, which will hopefully not be a huge LOE increase.

This could be as simple as modifying the PR template. Or it could be some automation to automatically tag a second reviewer if a PR touches `airbyte-integrations/connectors/*/spec.json`.

**Comment by marcosmarxm** [comment]
There is auto-label bot, probably it's possible to use it to trigger a message to the team OR use other bot to random assign members from connector team to review changes.
