### ISSUE TITLE
Decide on long term build vision

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#9855]
## Problem
A change to connectors can break the platform build and vice-versa. There is often very poor (aka long) feedback loops to know if my change broke something on the other "side of the fence". Plus, there are some flaky builds which, when failing, do not tell me if it was because of my change or because of flakiness. Either this means many CI checks become noise and are ignored, or it means developer waste a _ton_ of time trying to figure out why irrelevant CI checks are failing. 

Some ideas for a solution: 
- completely split connectors and platform build trees. Equivalent to if the root dir had two directories `platform/` and `connectors/` which have two completely different builds. the first step is to determine what the connector build looks like in such a world. 
- use pre-commit tests which tell me if the build was flaky because of me or because it was that way before. 
fundamentally it feels like the first option is the correct one long term. The build requirements for the platform are very different from those of connectors (latter is polyglot and needs compatibility with different toolchains, some are incremental builds, some are very siloed eg python, etc..). 

I think the right next step here is for someone to take some time to think about the right build system long term for connectors and propose some paths on how to incrementally get there. It is super important that this is incremental otherwise this project will likely not get done. 

this issue was written in collaboration with @jrhizor

**Comment by sherifnada** [comment]
Some interesting examples: Apache beam has a polyglot repo with SDKs in different languages: 

https://github.com/apache/beam

they also use pre-commit and post-commit tests which tell the author if their change messed things up: https://github.com/apache/beam/pull/16632#partial-pull-merging

**Comment by noahkawasakigoogle** [comment]
I have way less familiarity here, but how extensive is the directory structure between the platform side and the connector set in terms of what files on one side can break a build for the other side? 

In the short term, there could be either some simple gradle additions to declare dependancies:

```
dependencies {
    implementation files('libs/something_local.jar')
}
```

And two GA workflows to run some basic tests (like smoke tests but for a simple build) if those areas are changed on the other side

```
# Ensure platform changes run basic connector tests
on:
  pull_request:
    paths:
      - 'paths/**/*'

# Ensure connector changes run basic platform tests
on:
  pull_request:
    paths:
      - 'paths/**/*'
```

In the long term:

Has Airbyte ever considered using [Bazel](https://bazel.build/)? It requires more _exact_ dependency graphs between "projects" (targets in Bazel terms) which commonly based on [`srcs`](https://docs.bazel.build/versions/main/be/general.html#filegroup.srcs) rules (a list of files that a build target depends on). I've found gradle's generic task based dependency system vague in trying to determine what in Airbyte's build system depends on what and why. This was made to manage Google's monorepo/many languages structure, which Airbyte is also kind of doing. Could be a migration to consider someday, though it would likely be massive project I think it could pay off.

**Comment by sherifnada** [comment]
@noahkawasakigoogle 

>  how extensive is the directory structure between the platform side and the connector set in terms of what files on one side can break a build for the other side?

the main issues are usually: 
* the connector index (`source_definitions.yaml` and `destination_defintions.yaml`) was updated but the subsequent steps which autogen some code weren't run properly
* formatting breaks the overall repo's build
So they're rarely "actual" build breakages

I like the idea of smoke tests as they reduce the time to feedback

re: Bazel, we initially considered it in 2020 when first starting the project and discarded it because Gradle's IDE integration was better and Gradle's developer experience was pretty good in comparison. Realities may have changed almost two years down the road now.

**Comment by noahkawasakigoogle** [comment]
Gotcha! Thanks. 

In response to 

>formatting breaks the overall repo's build
So they're rarely "actual" build breakages

I think this would help: https://github.com/airbytehq/airbyte/issues/7566#issuecomment-1013898533

But I dont have context on why Airbyte's GA dont already do this so I could be missing something
