### ISSUE TITLE
Destination MongoDb: add normalization

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#9864]
## Tell us about the problem you're trying to solve
I'm trying to avoid the extra level of indentation in the documents. Because ORM model will break.
All documents have the data in `_airbyte_data` and the collection have the the prefix airbyte_raw
eg: the collection airbyte_raw_INFOBIKE_EDIZIONE
```
[
  {
    _id: ObjectId("61ee879f399a9d1f227c5584"),
    _airbyte_data: {
      ANNO_EDIZIONE_DEL_FILE_AAAA: '2022',
      MESE_EDIZIONE_DEL_FILE_MM: '02',
      DATA_AGGIORNAMENTO_DEL_FILE_AAAAMMGG: '20211220',
      TAPPO_NUMERICO: '0'
    },
    _airbyte_data_hash: 'f3ed19d8-2826-38b0-8162-8068ab5b238a',
    _airbyte_emitted_at: '2022-01-24T10:59:10.273'
  }
]
```

## Describe the solution you’d like
I want to be able to mirror the source, or at least have the collections without the airbyte_raw prefix and have the airbyte necessary information inside airbyte_data, while removing the level airbyte_data
eg: the collection airbyte_raw_INFOBIKE_EDIZIONE become INFOBIKE_EDIZIONE
```
[
  {
    _id: ObjectId("61ee879f399a9d1f227c5584"),
    ANNO_EDIZIONE_DEL_FILE_AAAA: '2022',
    MESE_EDIZIONE_DEL_FILE_MM: '02',
    DATA_AGGIORNAMENTO_DEL_FILE_AAAAMMGG: '20211220',
    TAPPO_NUMERICO: '0'
    _airbyte_data_hash: 'f3ed19d8-2826-38b0-8162-8068ab5b238a',
    _airbyte_emitted_at: '2022-01-24T10:59:10.273'
  }
]
```

## Describe the alternative you’ve considered or used
Now i need to add a mongodb function that remove the indentation level or try to use apache Nifi

**Comment by marcosmarxm** [comment]
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.
