### ISSUE TITLE
[JAVA][SENTRY] Integrate all Java-Based connectors with Sentry

### ISSUE THREAD

**Issue by alexandertsukanov** [airbytehq/airbyte#9867]
## Tell us about the problem you're trying to solve
In scope of issue https://github.com/airbytehq/airbyte/issues/9328, was created PR to integrate sentry with the next connectors:

- BigQuery
- BigQuery-denormalized
- Snowflake

This changes are also required for all Java-based connectors. . Please, consider this ticket as "**Ready for Implementation**" when [9328](https://github.com/airbytehq/airbyte/issues/9328) will be merged.

**Comment by tuliren** [comment]
I moved this issue out of the GL project for now. I am looking into this one.

**Comment by tuliren** [comment]
This issue is partially addressed in https://github.com/airbytehq/airbyte/pull/9745.
