### ISSUE TITLE
API: Reset connection doesn't consistently work

### ISSUE THREAD

**Issue by zds97** [airbytehq/airbyte#9872]
## Environment
- **Airbyte version**:  0.34.2-alpha
- **OS Version / Instance**: Ubuntu 20.04, GCP 
- **Deployment**: Docker
- **Source Connector and version**: Shopify 0.1.26
- **Destination Connector and version**: Postgres 0.3.13
- **Severity**: Medium
- **Step where error happened**: Resetting data via the API

## Current Behavior
I’m running into an issue when trying to reset data via the API (api/v1/connections/reset). Occasionally it seems to create a “sync” job when trying to reset the data manually. This doesn’t happen every time,  Here’s the response data from hitting api/v1/connections/reset when it triggers a “sync” job.
```
{
  job: {
    id: 660,
    configType: 'sync',
    configId: '71a629ed-afa7-4f47-ad91-447a1b6b4255',
    createdAt: 1643340794,
    updatedAt: 1643340796,
    status: 'running'
  },
  attempts: [ { attempt: [Object], logs: [Object] } ]
}
```

## Expected Behavior
The expectation is that calling the `/api/v1/connections/reset` endpoint results in a reset data job being created each time

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1 Create a destination to Postgres via the UI
2. Create a source to Shopify via the API
3. Create a connection between the Shopify source and Postgres destination via the API (Incremental Sync)
4. Sync the connection via the API
5. Once the sync has completed, update the source to have a different starting date via the API
6. Reset the data in the connector via the API <----- This is where the problem occurs

## Are you willing to submit a PR? 
Yes

**Comment by alafanechere** [comment]
Hi @zds97 when you call `api/v1/connections/reset`, does a reset job always run even if you receive a `sync` job type in the response?

**Comment by zds97** [comment]
@alafanechere No, it appears to be an actual sync job.

**Comment by Kopiczek** [comment]
We have the same problem.
I think this happens when connection is currently syncing and you issues a reset API call.
The result actually returns the currently running job (verified from inspecting the network)

Current running sync
![image](https://user-images.githubusercontent.com/5090824/154137012-4a9c4229-b920-4f96-b51d-292f2bb4242b.png)

Result of reset call
![image](https://user-images.githubusercontent.com/5090824/154137085-f9a632d5-76e9-405a-89e8-c0c3c119b04b.png)

**Comment by jrhizor** [comment]
This problem should be resolved with https://github.com/airbytehq/airbyte/issues/10021 (likely in the next month or so)
