### ISSUE TITLE
🐛 Destination Postgres: Reset Doesn't Handle Source Schema Changes, e.g. doesn't really reset

### ISSUE THREAD

**Issue by jedwards-gc** [airbytehq/airbyte#9880]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: AWS EC2 AmazonLinux 2, r5d.xlarge
- **Deployment**: Docker
- **Source Connector and version**: Postgres 0.4.3 (probably N/A)
- **Destination Connector and version**: Postgres 0.3.13 (probably N/A)
- **Severity**: Critical
- **Step where error happened**: Reset / Sync job

## Current Behavior
This primarily affects Incremental|Dedup+History, but should apply to other sync modes. Currently when running a reset, data is removed from the raw tables and destination (final) tables and clears out the sync_state record. Data is left in the stage tables (under the technical namespace/schema) and in the SCD tables. This causes two problems, one is reliably reproducible, the other is intermittent.
1) If the source schema has changed, the schema of the stage table is not updated, and breaks sync jobs, for example: 
![airbyte_sync_failed](https://user-images.githubusercontent.com/85513583/151599233-bbbcea76-86bf-4d60-af0c-6462ea63ae3d.png). I know there are several Github issues related to source schema changes (e.g. [#3520](https://github.com/airbytehq/airbyte/issues/3520)), but this seems to be distinct from those.
2) Several times I've had problems where, after a reset (without source schema changes) the destination/final tables will remain empty. My intuition is it has to do with the stage and scd tables still having data in them. That said, truncating the tables doesn't fix it, I generally have to drop all the tables (raw, stage, scd, and final) to get syncs to work again.

## Expected Behavior
I would expect a reset to:
1) clear out the sync state (which Airbyte currently does, but sometimes I have to delete the record itself, even if the state is empty)
2) truncate the raw tables
3) drop the stage, scd, and final tables and recreate them using the current sync catalog. Even without dropping and recreating all the tables, at least recreate/update the stage table so it has all the right columns

## Screenshots
Here is a table in the source database (all columns present):
![source_table](https://user-images.githubusercontent.com/85513583/151601191-1fb41975-30dc-427a-96b7-3350ca1030df.png)

Here's the table in the sync catalog (all columns present):
![airbyte_connection_settings](https://user-images.githubusercontent.com/85513583/151601297-271905df-b5f9-4a7c-96b8-26c36d393418.png)

Here's the stage table in the technical name space (missing columns):
![airbyte_stage_table](https://user-images.githubusercontent.com/85513583/151601437-02b0a05a-5907-44cc-99b7-f27938bb743e.png)

Here's the final/destination table (all columns present):
![destination_table](https://user-images.githubusercontent.com/85513583/151601534-135bfdbb-6675-4942-b8c2-190bd6e6d5e3.png)

## Steps to Reproduce
1. Setup a connection in Airbyte
2. Add/Change columns in a table in the source database
3. Execute a reset job
4. Check the stage table has been updated to match, the stage and scd tables are empty

## Are you willing to submit a PR?
Possibly, with some guidance on where to start

**Comment by misteryeo** [comment]
Closing this issue as it's a duplicate - a bit more context on the other issue already so merging this into that. @jedwards-gc please follow along at https://github.com/airbytehq/airbyte/issues/5417
