### ISSUE TITLE
🐛 Source Salesforce:  calls for distinct timestamp capped at 400 records (leads stream)

### ISSUE THREAD

**Issue by nwayne94** [airbytehq/airbyte#9883]
# Environment
- OS Version / Instance: Mac OS 11.5.2
- Memory / Disk: 32 GB
- Deployment: Docker
- Airbyte Version: 0.35.10-alpha
- Source name/version: Salesforce 0.1.23
- Destination name/version: S3 0.2.7
- Severity: Critical
---
# Current Behavior
It appears records from Leads table is capped at 400 records for each distinct timestamp. We currently have a Salesforce connection through AppFlow and used it to validate that we should, indeed, see thousands of records for certain timestamps, rather than the 400
---
#Screenshots
<img width="307" alt="Screen Shot 2022-01-28 at 2 41 43 PM" src="https://user-images.githubusercontent.com/95312884/151629355-b0f30950-0b61-4f42-9406-3759208caadb.png">
<img width="290" alt="Screen Shot 2022-01-28 at 2 41 23 PM" src="https://user-images.githubusercontent.com/95312884/151629360-f898aeb0-b3f0-4ad3-8556-d2d5c0963854.png">

**Comment by alafanechere** [comment]
Hi @nwayne94, is your replication successful according to Airbyte UI?

**Comment by nwayne94** [comment]
@alafanechere yes.

**Comment by bazarnov** [comment]
@nwayne94 Have you tried to update the `source-salesforce` up to `0.1.23` (the latest version) ?

**Comment by nwayne94** [comment]
@bazarnov 
1. We just updated to the latest version and still seeing the same problems
2. I misspoke and we are are using S3 as the destination
3. All the other tables we pull in are working fine

**Comment by bazarnov** [comment]
@nwayne94 
4. Have you used `REST` or `Bulk` option to call SF API from connector?
5. Could you please `distinct count` the `id` for `Lead` object only in SalesForce before and after the replication, just to make sure we have pulled out all the Leads correctly? (test it out only on Lead stream)

**Comment by nwayne94** [comment]
4. We are using whatever the default call option is in Airbyte. The UI version we are on (0.35.10-alpha) no longer provides the option to choose between the two

**Comment by bazarnov** [comment]
This could be the Rate-Limit issue, please try to sync only the `Lead` stream, and check the output, if you didn't make it earlier, of course.

**Comment by nwayne94** [comment]
@bazarnov this is only with the Lead stream, sorry for not clarifying that

**Comment by bazarnov** [comment]
@nwayne94 Just to be clear, does the issue still persist? Should we dig more into it?

**Comment by nwayne94** [comment]
@bazarnov yes, it is still an issue. When we initially talked to @marcosmarxm, he mentioned that it could be a pagination problem with the Lead stream 🤷

**Comment by bazarnov** [comment]
@nwayne94 Please sync the Leads stream only and share the logs here, please. Thank you.

**Comment by misteryeo** [comment]
Following up here @nwayne94

**Comment by marcosmarxm** [comment]
@nwayne94 I'm closing in favor of https://github.com/airbytehq/airbyte/pull/13658 please open a new issue if the issue persists.
