### ISSUE TITLE
discover and check_connection should not hold open api connections

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9884]
This is starting to become a problem. If you're behind a gateway with timeouts or if you have many clients, this won't scale. This is something that has been a known issue for a while, but we weren't tracking it as far as I can tell.

Basically we need some request / request id model for these.

**Comment by sherifnada** [comment]
@jrhizor related but separate: we should also measure runtime of these operations on different deployment models and in a vacuum i.e: how long does it take salesforce to discover a catalog of 1000 streams? we need to optimize these runtimes such that a solution like this is unnecessary (though this may be unavoidable in the absolute case)

**Comment by tuliren** [comment]
> @jrhizor related but separate: we should also measure runtime of these operations on different deployment models and in a vacuum i.e: how long does it take salesforce to discover a catalog of 1000 streams? we need to optimize these runtimes such that a solution like this is unnecessary (though this may be unavoidable in the absolute case)

I am going to track this with Sentry. I think the MVP won't automatically relate the runtime with number of streams. But at least we should know the time for each connector.

**Comment by jrhizor** [comment]
Definitely agree with needing to understand + optimize the times it takes to run these operations on the connector side. My main point here is that the platform shouldn't need to care about how long it takes like we do today.

**Comment by evantahler** [comment]
I think we can close this issue - we now that we run CHECK before /every/ sync, and things seem to be running OK!
