### ISSUE TITLE
allow configuring different temporal workflow/activity settings for cloud vs OSS

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9887]
On OSS, we generally want to err on the side of infinite timeouts so users get an experience that "just works" out of the box, even if they're doing something unexpected, like running a very long discovery job. (This is why we don't have resource limits by default in many places, for example).

Our Temporal timeouts/etc should be something we can configure independently for Cloud because we need to be more strict on limits.

The approach may be to allow these to be Helm-configurable values, or to actually implement and run separate worker nodes.

**Comment by evantahler** [comment]
Closing because we are working to have temporal jobs self-heal via https://github.com/airbytehq/airbyte/issues/14277
As far as the UX is concerned, we also want to stop retrying jobs that fail too often and notify the user in some way.
