### ISSUE TITLE
Source-defined comparable 

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#989]
Child of https://github.com/airbytehq/airbyte/issues/987

## Tell us about the problem you're trying to solve
* Provide interface for sources to specify the comparable for a stream (when no user input is required).
* Maybe a no-op after https://github.com/airbytehq/airbyte/issues/988 

Likely worth just trying to migrate a source that should define its own comparable (e.g. exchange rates api) to use incremental and then see if there's anything that needs to be done to make it easier to support it. There may be some helpers that are worth writing. Then again there may be nothing extra that need to be done at all.

**Comment by sherifnada** [comment]
For non-singer integrations, this should just be an implementation rather than an iface change. Example is #1080
