### ISSUE TITLE
Set maximum number of job attempts per connection

### ISSUE THREAD

**Issue by jordan-glitch** [airbytehq/airbyte#9904]
I am working with various custom sources and would like to be able to configure the `SYNC_JOB_MAX_ATTEMPTS` on a per connection basis, as some connectors afford more retries than others. Currently, this is not possible, as the `SYNC_JOB_MAX_ATTEMPTS` variable can only be set globally.

**Comment by cgardens** [comment]
@jordan-glitch can you help me understand why you need different retries for different connections?

**Comment by evantahler** [comment]
Closing due to lack of response

**Comment by tovbinm** [comment]
This could be a precious addition.

**Comment by mertkarabulutt** [comment]
This would be hugely valuable, I also need the same feature. Most of my sources connects with APIs so they can attempt multiple times if syncs fail but my MYSQL connectors connects to a production database which I don't want to exhaust the database with multiple attempts. Would be great if we can set this source/connection specific.

**Comment by lavData** [comment]
I think in k8s need be customize the deployment.
