### ISSUE TITLE
Bootloader pod fails due to non-semantic versioning of custom connector

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#9921]
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: linux
- **Deployment**: kube
- **Severity**: Low
- **Step where error happened**: Upgrade Airbyte

## Current Behavior
When upgrading Airbyte, bootloader failed because there was a custom connector with non-semantic versioning:
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid version string: 3a77955\
```

## Expected Behavior
Do not allow to create connectors with non-semver labels OR
Update bootloader to allow such labeling

**Comment by alafanechere** [comment]
Hi @TSkrebe, Airbyte expects semantic versioning of connectors. There's room for improvement in terms of validation of version label,  this is why I'll tag this issue as an enhancement suggestion.
Your error can be fixed if you change the version of your custom connector to a semantic versioning label.

**Comment by evantahler** [comment]
Closing for now - we will require connectors to support semantic versions.  In the future we can add checks fo this.
