### ISSUE TITLE
Research Mailchimp source connector

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#9924]
## Complete the following exercise for Mailchimp source connector:

1. What do people use this service for? 
2. What are the common use cases for pulling data from this connector?
3. What is the exhaustive list of features and data streams could this connector support? 
This should at least include:
  - Output schema: How will tables/entities/etc.. map to Airbyte streams and fields?
  - Authentication
  - Include more topics as you see fit depending on the connector (etc…)
4. Of the above exhaustive list, which features and data streams does the connector support today? Please highlight what we are currently missing.
5. How does Fivetran and Stitch Data support this connector? 
  - Do they support this connector?
  - What features or data streams do they support?
  - What features or data streams do they not support? 
  - Do you have any suggestions on how our connector can/should be different or better?

## Put here a link to the research details Doc:
https://docs.google.com/document/d/1SuPoss68t2r5b-6zU2hlWAe34RE1za0sRbGvkAGM04M/edit?usp=sharing

[EPIC] GA & Beta Connector Research #9675

**Comment by karinakuz** [comment]
Research result:  https://docs.google.com/document/d/1orYG8xiKVDqYpa_6nDofLWcKE_OxW98x6rin5THSmvM/edit?usp=sharing

**Comment by igrankova** [comment]
@misteryeo, @annalvova05 the research is finished

**Comment by annalvova05** [comment]
New file with research result: https://docs.google.com/document/d/1SuPoss68t2r5b-6zU2hlWAe34RE1za0sRbGvkAGM04M
