### ISSUE TITLE
Document how to use persistent volumes instead of a docker volume

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#994]
## Tell us about the documentation you'd like us to add or update
* When using the docker version of the app, i want to be able to use a persistent volume instead of a docker volume

**Comment by ChristopheDuong** [comment]
It seems like this tutorial is out of date on my mac as i don't have such `tty` file:
https://timonweb.com/docker/getting-path-and-accessing-persistent-volumes-in-docker-for-mac/

I've been trying to understand the one below and trying external volumes:
https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html

**Comment by ChristopheDuong** [comment]
Digging up the issues, it seems there was this tragic one: https://github.com/airbytehq/airbyte/pull/576

That might have been caused by this explanation:
```
There seems to be no way to use custom location when using a named-volume (only the bind-mounts are able to) with a default Docker installation
```
https://stackoverflow.com/a/63242859

**Comment by ChristopheDuong** [comment]
As a conclusion, should I try to write some airbyte-launcher.sh script that will wrap things around and take care of creating external volumes etc before invoking docker-compose up (or down) ?

**Comment by cgardens** [comment]
I think we would prefer to _not_ have to use a script to launch the app. At least as long as that is feasible. 

If I'm reading the SO article you provided correctly it seems like you could get around it anyway. If you use the plugin that the person describes it seems like the docs for how to do this could roughly be:
1. all our normal install instructions
1. install the 3rd party module (`local-persist `) to make a named bind mount
1. edit the docker-compose file to use the named volumes that just use a pth.
1. `docker-compose up`

Am I missing something? Do we need a script?

**Comment by jrhizor** [comment]
We don't want users need to install a docker plugin.

**Comment by cgardens** [comment]
@jrhizor gave me the low down and made a very persuasive argument that we should either go all bind mounts or all volumes. Sounds like volumes might be the slightly more ergonomic thing. Anyway, I'm in agreement with jared on this and will let him take over on explaining what he wants.

**Comment by ChristopheDuong** [comment]
Yes, we had that discussion too!

And our conclusion was that if we go down the choice of:
> Sounds like volumes might be the slightly more ergonomic thing.

Then we probably would have to do the launcher script if that's fine with you?
> I think we would prefer to not have to use a script to launch the app. At least as long as that is feasible.

Otherwise, all bind mounts...

**Comment by jrhizor** [comment]
So what Charles and I discussed later was an all persistent volume approach which is basically what we have in the production docker-compose.yaml already; we can use that exact approach for the dev environment as well, only keeping bind mounts for the local file directory for csv outputs and file inputs. We can probably even use the same files for Docker Compose in prod and dev, just with different .env files. 

In that case, the main challenges are making it easy to handle the contents of these mounts. Typical operations would be viewing logs/other files on the volumes, copying the contents from the volumes into a directory (which could be used for the version controlling use case), or replacing the content of the volume with the contents of a directory. These operations don't have good documentation today, but if they do, we can use the simple, docker-managed mounts everywhere.

Then, we don't need any launch script at all. 

Does that seem reasonable?
