### ISSUE TITLE
Audit secrets handling

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#9946]
Epic: https://github.com/airbytehq/airbyte/issues/9646

### Acceptance Criteria
- A document exists describing locations in code where secrets are used, along with a recommendation for any improvements to be made.
- Once this document exists, revisit the epic and add any newly discovered tasks that came out of the audit

**Comment by benmoriceau** [comment]
https://whimsical.com/secret-usage-DWdpNNmVuJthyo3sLJ87oE This is a diagram that represent where the secret are used.
