### ISSUE TITLE
Basic Normalization: Overrule default parameter values (query_tag a.o.) 

### ISSUE THREAD

**Issue by pjleiwa6g** [airbytehq/airbyte#9953]
## Tell us about the problem you're trying to solve
When using 'basic normalization' for a Snowflake destination, the value of query_tag is set to 'normalization'.  I would like to have an option to overrule this value. 

Related issues, in which query_tag and other dbc parameters can be set: https://github.com/airbytehq/airbyte/pull/9623 which also solves this issue: https://github.com/airbytehq/airbyte/issues/9467, but it only does this for the 'raw' method.

## Describe the solution you’d like
I would like to have the solution for https://github.com/airbytehq/airbyte/pull/9623/ to be extended. So when a query_tag is entered in the UI it would overrule the default query_tag which is used for normalization. And also other additional parameters that are set should overrule the default.

## Describe the alternative you’ve considered or used
Use the 'raw' method and do the normalization outside of Airbyte.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126617252585) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment]
In that case the `destination-snowflake`'s spec should have a specific `query-tag` property instead of a generic jdbc-params.

Then in normalization you can check if the query-tag field is populated and use it or fallback to `normalization` here:
https://github.com/airbytehq/airbyte/blob/a5182471837d3f406fada3897f8017a14ab2d46f/airbyte-integrations/bases/base-normalization/normalization/transform_config/transform.py#L207

**Comment by pjleiwa6g** [comment]
An possibility is to extract the query_tag value from the jdbc-params. If it's not in the jdbc-params, one can fall back to the default normalization.

Something like this (in transform.py):

- parameter ->query_tag
- jdbc_url_params ->config["jdbc_url_params"]
- default -> normalization

```python
    ....    
    import urllib.parse
    ....

    def transform_snowflake(config: Dict[str, Any]):
    ....
        query_tag=TransformConfig.get_jdbc_param_value("query_tag".upper(),config["jdbc_url_params"].upper(),"normalization")
    ....
       "query_tag": query_tag,
    ....
    
    def get_jdbc_param_value(parameter,jdbc_url_params,default_value):
        parameter_length=len(parameter) + 1 # +1 because of the = sign
        parameters=jdbc_url_params.split(',')
        parameter_value=default_value
        
        for i in parameters:
            if i.startswith(parameter):
                parameter_value=urllib.parse.unquote(i[parameter_length:])
                                
                return parameter_value

**Comment by ChristopheDuong** [comment]
Sure it seems fine, you're welcome to push a PR there!

**Comment by vishjain** [comment]
Hi, Can you please assign this task? Thanks!

**Comment by marcosmarxm** [comment]
Basic normalization is deprecatd and was removed for Snowflake.
