### ISSUE TITLE
Set a limit duration of source connectors to run

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#9957]
## Tell us about the problem you're trying to solve
A source connector could be running indefinitely if it streams data continuously without encountering any errors.

## Describe the solution you’d like
Expose (or not) a default parameter for how long a source connector can be running before "checkpointing" states or gracefully terminating.

## Describe the alternative you’ve considered or used
Let it run until it gets killed someday

## Additional context
We currently observe syncs that are "stuck" and not doing anything.
It is hard to differentiate between syncs that are running normally for hours/days without exceptions and outputting records little by little.

**Comment by skalyanapu-mtuity** [comment]
@ChristopheDuong - Are you able to find a workaround for this issue - We're facing the same issue, the pipeline is running indefinitely and going beyond the total count of records at the source.

**Comment by ChristopheDuong** [comment]
No, sorry I don't have workaround for the moment.

In which source connector are you seeing this issue?

**Comment by skalyanapu-mtuity** [comment]
We're using salesforce as source and BigQuery as destination @ChristopheDuong
