### ISSUE TITLE
Schedule a regular check_connection workflow

### ISSUE THREAD

**Issue by ChristopheDuong** [airbytehq/airbyte#9970]
## Tell us about the problem you're trying to solve
Following https://github.com/airbytehq/airbyte/issues/9969 from [tech spec](https://docs.google.com/document/d/14hYJTUFIXHQ7JBB-gq2EBGrAvPBaEatDyOZMsUH12bI/edit#heading=h.u9chfrq9hv0) from https://github.com/airbytehq/airbyte/issues/9350

## Describe the solution you’d like
Implement a temporal workflow to schedule check_connection operations and save their outcomes using persistence methods from https://github.com/airbytehq/airbyte/issues/9969

**Comment by evantahler** [comment]
Updated within https://github.com/airbytehq/airbyte/issues/12119
