### ISSUE TITLE
Source Bing Ads: change account id field name 

### ISSUE THREAD

**Issue by joepbuhre** [airbytehq/airbyte#9972]
I tried to setup the Bing Ads connector as source. However following the exact steps I got the following error: `"Exception(\"You don't have accounts assigned to this user.\")"` . 

So I followed the whole setup again step by step and Airbyte requested an Account ID from me. When I went to the docs Microsoft said:
> _The URL will contain a cid key/value pair in the query string that identifies your customer ID, and an aid key/value pair that identifies your account ID._

So I thought the Account Id was the aid key/value pair. However: when I inserted it in Airbyte it the gave above error. Well, cue 3 hours later. I thought let's have a look at the JSON  request/response of airbyte. And then I saw the following JSON.

```
{
   "sourceDefinitionId":"xxxxxx-xxxxxxx-xxxxxx-xxxxxx",
   "connectionConfiguration":{
      "reports_start_date":"2020-01-01",
      "monthly_reports":false,
      "developer_token":"xxxxxxxxxxxxxxxx",
      "weekly_reports":false,
      "hourly_reports":false,
      "refresh_token": "xxx....xxxxxxx",
      "daily_reports":true,
      "client_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "customer_id":"xxxxxxx",
      "client_id":"xxxxxx-xxxxxx-xxxxxx-xxxxxx",
      "accounts":{
         "selection_strategy":"all"
      },
      "user_id":"12345678"
   }
}
```
So I found out that the field that in Airbyte, which is called Account Id, was send as user_id . On top of that, in the source of the Bing Ads connector I found the following: [https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L97](https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L97). 

So I dove into it further, and checked the url which microsoft provided. I found three values: cid, aid and **uid**
https://ads.microsoft.com/cc/Users?cid=12345678&aid=12345678&uid=12345678987 . 
Well, what are the chances that this is the user_id that is being send over JSON. I swapped out the values and BAM, miracle happened. It worked!

So I forked the repo and tried to change the value, but I couldn't test it. So I did my best to document the problem and point you all in the right direction.

TLDR
Account Id in the Bing ads connector should be called User Id. The file/line where it should be changed is 

[https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L97](https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L97)
&&
[https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L98](https://github.com/airbytehq/airbyte/blob/98b5aabd187a7338e01114c373a397d3aae3590e/airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json#L98). 

Account Id should be changed to User Id

**Comment by itaseskii** [comment]
I'll claim this issue.

**Comment by aharelick** [comment]
This issue will be handled by an internal team, I'm removing it from the Maintainer program.
