### ISSUE TITLE
🐛 Destination GCS: `Set up destination` button does nothing when setting up a destination with compression

### ISSUE THREAD

**Issue by philippeboyd** [airbytehq/airbyte#9980]
## Environment
- **Airbyte version**:  0.35.14-alpha
- **Deployment**: Docker
- **Destination Connector and version**: Google Cloud Storage (GCS) 0.1.20
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
`Set up destination` button does nothing when setting up a `Google Cloud Storage (GCS)` Destination.

* **No HTTP request is being made.**
* **No error in the front-end console**

![image](https://user-images.githubusercontent.com/3239656/152039588-e3e3d889-c87f-413e-8a3e-839362765f0d.png)

## Expected Behavior
Destination should be set, or at least get an error message stating what's wrong in the front-end.

## Steps to Reproduce
1. Reproduce example provided in above image

**Comment by philippeboyd** [comment]
Title edited: the issue seems to be when setting `Avro` **WITH** Compression (any type of compression)

When setting `No Compression`, it works

![image](https://user-images.githubusercontent.com/3239656/152041113-7ef59e81-ce0e-4a62-a015-ebcbb86ca846.png)

**Comment by tuliren** [comment]
This is probably related to the `oneOf` bug on the UI: https://github.com/airbytehq/airbyte/issues/8291

I noticed in another connector that if there is a `oneOf` inside another `oneOf`, the parameters are messed up. The final value can come from fields of multiple elements within the `oneOf` array, and is considered invalid. But it's hard to tell what exactly goes wrong.
